### ISSUE TITLE
[MoeVideo] Unable to extract OpenGraph title

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#10474]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.28**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ y -v 'http://moevideo.net/video/00297.0036103fe3d513ef27915216fd29'
[debug] System config: []
[debug] User config: ['-4', '-f', 'best', '--prefer-free-formats', '--no-cache-dir', '--no-mtime', '--youtube-skip-dash-manifest']
[debug] Command-line args: ['-v', 'http://moevideo.net/video/00297.0036103fe3d513ef27915216fd29']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.28
[debug] Python version 3.6.0a4 - Linux-4.7.0-rc7-686-i686-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.1.3, ffprobe 3.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[MoeVideo] 00297.0036103fe3d513ef27915216fd29: Downloading webpage
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/moevideo.py", line 66, in _real_extract
    title = self._og_search_title(webpage)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 759, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 747, in _og_search_property
    escaped = self._search_regex(og_regexes, html, name, flags=re.DOTALL, **kargs)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 650, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

http://moevideo.net/video/00297.0036103fe3d513ef27915216fd29

**Comment by yan12125** [comment]
This page displays a [404 video](http://playreplay.net/video/404.mp4.mp4). I guess it indicates 404 not found. Do you have other examples?

**Comment by stepshal** [comment]
@yan12125 video redirects to playerplay.me 
Video on moevideo.net is unsupported:
http://moevideo.net/news/shaja-labaf-i-otryad-samoubijc

**Comment by cogonide** [comment]
@ghost Is this issue still a problem?

**Comment by yan12125** [comment]
Most likely not. The second example has also gone - it attempts to load an invalid YouTube video. On the other hand, moevideo has been supported since 2014 (https://github.com/ytdl-org/youtube-dl/pull/3691).

And ghost is a special GitHub account, representing deleted accounts. It will not respond, so closing anyway.
