### ISSUE TITLE
Need option to prioritize different conditions

### ISSUE THREAD

**Issue by Saklad5** [ytdl-org/youtube-dl#10506]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.08.31_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.31**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.08.31
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---
### Description of your _issue_, suggested solution and other information

I would like to be able to automatically get the best possible file, _regardless of _format__, but still prefer a format if the highest quality is available in it. At the moment, this isn’t really possible.

On YouTube, for instance, MP4s are not available in 8K. WebM is, so the behavior I’d like is to download that. However, this will only occur if I do not specify a preferred format at all, using “bestvideo". If I add that argument to my config file, I won’t download MP4 even when it _is_ available at the highest quality. Even if I immediately convert it to MP4 using ffmpeg, this wastes power and time needlessly.

The alternate approach, of course, is to use “bestvideo[ext=mp4]”. This will download the best available MP4 file, which is ultimately what I want in most cases. **However**, using such an argument with the aforementioned 8K video will result in a 4K MP4, as YouTube does not provide higher resolutions in that format.

Right now, there is a way to prioritize a chosen format and choose the best from it. I believe there should be the opposite as well: prioritize the best quality, and choose a format from that if available. That means it would always download the best, preferring a given format but choosing another one if it isn’t available.

**Comment by dstftw** [comment]
Provide **concrete** example.

**Comment by Saklad5** [comment]
“youtube-dl https://www.youtube.com/watch?v=sLprVF6d7Ug <https://www.youtube.com/watch?v=sLprVF6d7Ug> -f bestvideo” gives an 8K WebM video.
 “youtube-dl https://www.youtube.com/watch?v=sLprVF6d7Ug <https://www.youtube.com/watch?v=sLprVF6d7Ug> -f bestvideo[ext=mp4]” gives a 4K MP4 video.

“youtube-dl https://www.youtube.com/watch?v=IJhgZBn-LHg <https://www.youtube.com/watch?v=IJhgZBn-LHg> -f bestvideo” gives a 4K WebM video.
“youtube-dl https://www.youtube.com/watch?v=IJhgZBn-LHg <https://www.youtube.com/watch?v=IJhgZBn-LHg> -f bestvideo[ext=mp4]” gives a 4K MP4 video.

I want to have youtube-dl get me the 8K WebM video from the first link and the 4K MP4 video from the second link.

Yours truly,
	Jeremy Saklad
	(saklad5@me.com)
	+1(210)254-5606

On 30 August 2016, at 9:34 PM, Sergey M. <notifications@github.com> wrote:

Provide concrete example.

**Comment by Starsam80** [comment]
What about `-f "bestvideo[ext=webm][height>2160]/bestvideo[ext=mp4][height<=2160]"`? It seems to work for me:

```
$ youtube-dl -f "bestvideo[ext=webm][height>2160]/bestvideo[ext=mp4][height<=2160]" "https://www.youtube.com/watch?v=sLprVF6d7Ug" "https://www.youtube.com/watch?v=IJhgZBn-LHg"
[youtube] sLprVF6d7Ug: Downloading webpage
[youtube] sLprVF6d7Ug: Downloading video info webpage
[youtube] sLprVF6d7Ug: Extracting video information
[youtube] sLprVF6d7Ug: Downloading MPD manifest
[download] Destination: Ghost Towns in 8K-sLprVF6d7Ug.webm
[download] 100% of 397.69MiB in 00:31
[youtube] IJhgZBn-LHg: Downloading webpage
[youtube] IJhgZBn-LHg: Downloading video info webpage
[youtube] IJhgZBn-LHg: Extracting video information
[youtube] IJhgZBn-LHg: Downloading MPD manifest
[download] Destination: How Earth Moves-IJhgZBn-LHg.mp4
[download] 100% of 1.17GiB in 01:38
```

**Comment by Saklad5** [comment]
That’s my current solution. That may not work with other sites, however, and it is a rather makeshift solution anyway.
Yours truly,
	Jeremy Saklad
	(saklad5@me.com)
	+1(210)254-5606

On 30 August 2016, at 10:04 PM, Starsam80 <notifications@github.com> wrote:

What about -f "bestvideo[ext=webm][height>2160]/bestvideo[ext=mp4][height<=2160]"? It seems to work for me:

$ youtube-dl -f "bestvideo[ext=webm][height>2160]/bestvideo[ext=mp4][height<=2160]" "https://www.youtube.com/watch?v=sLprVF6d7Ug" "https://www.youtube.com/watch?v=IJhgZBn-LHg"
[youtube] sLprVF6d7Ug: Downloading webpage
[youtube] sLprVF6d7Ug: Downloading video info webpage
[youtube] sLprVF6d7Ug: Extracting video information
[youtube] sLprVF6d7Ug: Downloading MPD manifest
[download] Destination: Ghost Towns in 8K-sLprVF6d7Ug.webm
[download] 100% of 397.69MiB in 00:31
[youtube] IJhgZBn-LHg: Downloading webpage
[youtube] IJhgZBn-LHg: Downloading video info webpage
[youtube] IJhgZBn-LHg: Extracting video information
[youtube] IJhgZBn-LHg: Downloading MPD manifest
[download] Destination: How Earth Moves-IJhgZBn-LHg.mp4
[download] 100% of 1.17GiB in 01:38

**Comment by Saklad5** [comment]
If this isn't clear, my issue is that the solution mentioned above works on the assumption that MP4s are available up to 4K, and not available above that. This may only be true for YouTube, and may not apply to other extractors or even YouTube itself in the future.

I feel it is preferable to actually specify what I desire in the config, rather than specifying a series of requirements that just HAPPEN to do what I want right now. This is a broadly applicable improvement, too, and unless I am mistaken is easy to implement. I'd do it myself if I had the time to work out how GitHub commits work right now.
