### ISSUE TITLE
[Redtube]An extractor error has occurred.

### ISSUE THREAD

**Issue by advertcn** [ytdl-org/youtube-dl#10518]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.08.31_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.31**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.08.31
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---
### Description of your _issue_, suggested solution and other information

Explanation of your _issue_ in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your _issue_ required an account credentials please provide them or explain how one can obtain them.

**Comment by advertcn** [comment]
```
[root@m etc]# youtube-dl -v http://www.redtube.com/66418
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.redtube.com/66418']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.31
[debug] Python version 2.6.6 - Linux-2.6.32-642.3.1.el6.x86_64-x86_64-with-centos-6.8-Final
[debug] exe versions: ffmpeg N-81437-g76d377d-static, ffprobe N-81437-g76d377d-static
[debug] Proxy map: {}
[RedTube] 66418: Downloading webpage
ERROR: Video 66418 has been removed
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/redtube.py", line 33, in _real_extract
    raise ExtractorError('Video %s has been removed' % video_id, expected=True)
ExtractorError: Video 66418 has been removed
```

http://www.redtube.com/66418
youtube-dl returns all Redtube request as "ERROR, Video XXX has been removed". Redtube has changed its way of returning 404 videos.

**Comment by dstftw** [comment]
Post the output of `youtube-dl -v http://www.redtube.com/66418 --dump-pages`.

**Comment by advertcn** [comment]
While it seems redtube changed their page again and now youtube-dl is working now.

Except it, may I ask how to build youtube-dl myself? Sorry I'm good at C but really not familiar with python.

From the guide, it said:
"Since June 2012 (#342) youtube-dl is packed as an executable zipfile, simply unzip it (might need renaming to youtube-dl.zip first on some systems) or clone the git repository, as laid out above. If you modify the code, you can run it by executing the __main__.py file. To recompile the executable, run make youtube-dl."

I can unzip the file and exectute the __main__.py file. But I can recompile the executable by running "make youtube-dl". It shows me:

```
[root@youtube test]# make youtube_dl
make: Nothing to be done for `youtube_dl'.
```

**Comment by yan12125** [comment]
Here's a typo in your command. It should be:
```
$ make youtube-dl
```

**Comment by advertcn** [comment]
Hello,

It still didn't work.

```
[root@youtube test]# make youtube-dl
make: *** No rule to make target `youtube-dl'.  Stop.
[root@youtube test]#
```

**Comment by yan12125** [comment]
Can you paste the content of ```Makefile```?

**Comment by advertcn** [comment]
I think maybe this is the problem.

Under the folder 'youtube_dl', there's no Makefile. Below are the files in this folder:

```
[root@youtube youtube_dl]# ls -l
total 476
-rwxr-xr-x 1 root root 99783 Aug 30 19:38 YoutubeDL.py
-rw-r--r-- 1 root root 17955 Aug 30 19:38 __init__.py
-rwxr-xr-x 1 root root   467 Aug 30 19:38 __main__.py
-rw-r--r-- 1 root root 15211 Aug 30 19:38 aes.py
-rw-r--r-- 1 root root  2980 Aug 30 19:38 cache.py
-rw-r--r-- 1 root root 88570 Aug 30 19:38 compat.py
drwxr-xr-x 2 root root  4096 Sep  2 03:39 downloader
drwxr-xr-x 2 root root 20480 Sep  2 03:39 extractor
-rw-r--r-- 1 root root  8904 Aug 30 19:38 jsinterp.py
-rw-r--r-- 1 root root 38341 Aug 30 19:38 options.py
drwxr-xr-x 2 root root  4096 Sep  2 03:39 postprocessor
-rw-r--r-- 1 root root  8715 Aug 30 19:38 socks.py
-rw-r--r-- 1 root root 31483 Aug 30 19:38 swfinterp.py
-rw-r--r-- 1 root root  6923 Aug 30 19:38 update.py
-rw-r--r-- 1 root root 94371 Aug 30 19:38 utils.py
-rw-r--r-- 1 root root    68 Aug 30 19:39 version.py
```

**Comment by yan12125** [comment]
Oh I forgot that the zipped file does not contain ```Makefile```, as there's no need for end users to build it again. If you need Makefile, use git. [Developer instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#developer-instructions) should help.

**Comment by advertcn** [comment]
Thanks very much.

It works now!

**Comment by razor1907** [comment]
@advertcn 
Just wondering if your "own" copy of youtube-dl includes extracting extra metadata like "categories" and "tags".

If so, please share the command with the community. If not, feel free to consider this as a kind request : )

thanks!

**Comment by advertcn** [comment]
@razor1907 

I would suggest you use their hubtraffic.com to pull a CSV file and use youtube-dl to download videos only
