### ISSUE TITLE
[brightcove:legacy] ERROR: Empty playlist

### ISSUE THREAD

**Issue by pepoluan** [ytdl-org/youtube-dl#10724]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.09.19_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.19**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl --verbose 'http://video.ew.com/v/115441812/video.htm'
[debug] System config: []
[debug] User config: [u'--prefer-ffmpeg', u'--ffmpeg-location', u'/usr/local/bin/ffmpeg']
[debug] Command-line args: [u'--verbose', u'http://video.ew.com/v/115441812/video.htm']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.19
[debug] Python version 2.7.10 - CYGWIN_NT-10.0-2.6.0-0.304-5-3-x86_64-64bit
[debug] exe versions: ffmpeg N-81400-g15dd56c
[debug] Proxy map: {}
[generic] video: Requesting header
[redirect] Following redirect to http://video.ew.com/v/115441812/zootopia-deleted-scene-see-nick-and-judy-s-romantic-mix-up.htm
[generic] zootopia-deleted-scene-see-nick-and-judy-s-romantic-mix-up: Requesting header
WARNING: Falling back on generic information extractor.
[generic] zootopia-deleted-scene-see-nick-and-judy-s-romantic-mix-up: Downloading webpage
[generic] zootopia-deleted-scene-see-nick-and-judy-s-romantic-mix-up: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: 'Zootopia' deleted scene: See Nick and Judy's romantic mix-up
[generic] playlist 'Zootopia' deleted scene: See Nick and Judy's romantic mix-up: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:legacy] AQ~~,AAAAAA0Xi_s~,r1xMuE8k5NzvRLJ-N_Qaw5vxu-5-vbe2: Downloading playlist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 355, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/brightcove.py", line 277, in _real_extract
    return self._get_playlist_info(player_key[0])
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/brightcove.py", line 320, in _get_playlist_info
    raise ExtractorError('Empty playlist')
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---
### Description of your _issue_, suggested solution and other information

Playing the video in its entirety works on the EW site without having to register and/or login.

But downloading using `youtube-dl` _always_ results in the same error, "Empty playlist".

**Comment by remitamine** [comment]
no longer exists.
