### ISSUE TITLE
[noco] Support for playlist

### ISSUE THREAD

**Issue by mitsukarenai** [ytdl-org/youtube-dl#10864]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.02**
- [x] README/FAQ/search
- [x] Feature request (request for a new functionality)

Main extractor contributor: @dstftw 

---

I'd like to suggest adding support for Noco's playlists, to allow download for a full series.

Example, with the "latest episodes" page:
`http://noco.tv/emissions/64-4-148/olydri-studio/noob/derniers-episodes`
{homepage} /emissions/ {playlist id} / {editor studio} / {series title slug} / {optional sorting filter; default: newest first}

Each episode is inside a `<div class="item">`, from which the fist link goes like:
`http://noco.tv/emission/17205/olydri-studio/noob/s06e03-accomplissement`
and is already supported by the Noco extractor URL matching. However, only the 30 newest episodes are listed in the HTML code of the page, older episodes get loaded by "infinite scroll".

Sidenote: Noco also uses this URL format:
`http://noco.tv/famille/148/olydri-studio/noob`
{homepage} / famille / {series id} / {editor studio} / {series title slug}

Which is an information page sorting by seasons, related contents, most viewed episode,  suggestions... From the actual series, the 15 most recent episodes can be seen in the slide menu, older ones get loaded by "infinite slide".

Pinpointing all episodes from a specific series may be quite challenging :(

**Comment by Alwaysin** [comment]
+1 for this
