### ISSUE TITLE
youtube-dl freazes

### ISSUE THREAD

**Issue by buzz3rs** [ytdl-org/youtube-dl#11014]
youtube-dl freazes when trying to download and extract audio from YouTube
I use the following command on ubuntu server :
`youtube-dl -o "./tmp/%(title)s.%(ext)s" --verbose --extract-audio --audio-format mp3 http://youtu.be/YQHsXMglC9A`
And i get this :

> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: [u'-o', u'./tmp/%(title)s.%(ext)s', u'--verbose', u'--extract-audio', u'--audio-format', u'mp3', u'http://youtu.be/YQHsXMglC9A']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2016.10.21.1
> [debug] Python version 2.7.6 - Linux-4.2.0-c9-x86_64-with-Ubuntu-14.04-trusty
> [debug] exe versions: avconv 11.3-6, avprobe 11.3-6
> [debug] Proxy map: {}
> [youtube] YQHsXMglC9A: Downloading webpage
> [youtube] YQHsXMglC9A: Downloading video info webpage
> [youtube] YQHsXMglC9A: Extracting video information
> [youtube] {22} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {43} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {18} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {36} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {17} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {137} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {248} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {136} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {247} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {135} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {244} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {134} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {243} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {133} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {242} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {160} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {278} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {140} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {171} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {249} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {250} signature length 40.41, html5 player en_US-vflEz7zqU
> [youtube] {251} signature length 40.41, html5 player en_US-vflEz7zqU
> [debug] Invoking downloader on u'https://r5---sn-5hne6ney.googlevideo.com/videoplayback?ms=au&ipbits=0&pl=23&mv=u&mt=1477323648&mn=sn-5hne6ney&mm=31&keepalive=yes&key=yt6&ip=130.211.74.70&clen=6020814&source=youtube&lmt=1445520219092080&upn=JzMmybeeBMw&expire=1477345322&id=o-AOr6HrH08h8kIHNrpAmxFgUODiXAaCN-XNEw9W9cOI8s&gir=yes&itag=251&mime=audio%2Fwebm&dur=366.821&ei=yisOWOqZEIi6W42osKgE&requiressl=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&signature=83DD79CF884BC8C485598680D87101D4D891AFB6.162E75B9789F7F59C290F93D736AA0BB7F9B5CE6&ratebypass=yes' 

And then the script freazes ..
it was working before with the same script and link..
any ideas ?

**Comment by dstftw** [comment]
`--force-ipv4`?
