### ISSUE TITLE
pluralsight not working - using 2016.10.25

### ISSUE THREAD

**Issue by philg4iio** [ytdl-org/youtube-dl#11030]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.10.25_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.25**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.10.25
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---
### Description of your _issue_, suggested solution and other information

Explanation of your _issue_ in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your _issue_ requires account credentials please provide them or explain how one can obtain them.

**Comment by philg4iio** [comment]
C:\YouTube-dl>youtube-dl --sleep-interval 60 --max-sleep-interval 100 --verbose --username phil@autom8tions.com.au --password G4iioG4iio -o "c:\YouTube-dl /%(playlist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" https://app.pluralsight.com/library/courses/illustrator-cc-fundamentals/table-of-contents
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--sleep-interval', '60', '--max-sleep-interval', '100', '--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', '-o', 'c:\\YouTube-dl /%(playlist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', 'https://app.pluralsight.com/library/courses/illustrator-cc-fundamentals/table-of-contents']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.10.25
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] illustrator-cc-fundamentals: Downloading course JSON
[pluralsight:course] illustrator-cc-fundamentals: Downloading course data JSON
[download] Downloading playlist: Illustrator CC Fundamentals
[pluralsight:course] playlist Illustrator CC Fundamentals: Collected 64 video ids (downloading 64 of them)
[download] Downloading video 1 of 64
[pluralsight] Downloading login page
[pluralsight] Logging in as phil@autom8tions.com.au
[pluralsight] illustrator-cc-fundamentals-m1-0: Downloading JSON metadata
[pluralsight] illustrator-cc-fundamentals-m1-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] illustrator-cc-fundamentals-m1-0: Waiting for 4 seconds to avoid throttling
[debug] Invoking downloader on 'http://vid.pluralsight.com/expiretime=1477434439/6518638ee941730f92a005bf95f1afbb/clip-videos/matthew-pizzi/illustrator-cc-fundamentals-m1/illustrator-cc-fundamentals-m1-01/1280x720mp4/20160309201627.mp4'
[download] Sleeping 87.14572303108751 seconds...
[download] Destination: c:\YouTube-dl#\Illustrator CC Fundamentals\1-What Is Adobe Illustrator\01 - What Is Adobe Illustrator - What Is Adobe Illustrator.mp4
[download] 100% of 11.35MiB in 00:21
[download] Downloading video 2 of 64
[pluralsight] illustrator-cc-fundamentals-m2-0: Downloading JSON metadata
[pluralsight] illustrator-cc-fundamentals-m2-0: Downloading mp4-high-widescreen viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Unauthorized
[pluralsight] illustrator-cc-fundamentals-m2-0: Waiting for 5 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9smmfv95\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9smmfv95\build\youtube_dl\extractor\common.py", line 356, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9smmfv95\build\youtube_dl\extractor\pluralsight.py", line 286, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9smmfv95\build\youtube_dl\extractor\common.py", line 923, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by booyaa** [comment]
@philg4iio you might want to change your pluralsight password, you've posted by mistake.

**Comment by philg4iio** [comment]
Thanks for letting me know..

**Comment by philg4iio** [comment]
Thank you for letting me know - Phil 

Get Outlook for iOS




On Wed, Oct 26, 2016 at 6:24 PM +1000, "Mark Sta Ana" <notifications@github.com> wrote:












@philg4iio you might want to change your pluralsight password, you've posted by mistake.
