### ISSUE TITLE
HTTP Error 500 for "Enviado Especial" at ATresPlayer.com

### ISSUE THREAD

**Issue by vitaminace33** [ytdl-org/youtube-dl#11062]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.10.26_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.26**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl --verbose http://www.atresplayer.com/television/programas/enviado-especial/temporada-1/capitulo-1-programa-caso-pablo-ibar_2016021000468.html 2&> error.txt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.atresplayer.com/television/programas/enviado-especial/temporada-1/capitulo-1-programa-caso-pablo-ibar_2016021000468.html', u'2']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2016.10.26
[debug] Python version 2.7.12 - Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.8-0ubuntu0.16.04.1, avprobe 2.8.8-0ubuntu0.16.04.1, ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[AtresPlayer] capitulo-1-programa-caso-pablo-ibar: Downloading webpage
[AtresPlayer] 20160210-EPISODE-00036-false: Downloading player JSON
[AtresPlayer] capitulo-1-programa-caso-pablo-ibar: Downloading timestamp
[AtresPlayer] capitulo-1-programa-caso-pablo-ibar: Downloading windows video JSON
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 403, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

---

Although the site atresplayer.com is a video site for several Spanish channels (Antena 3, La Sexta), it does not work like regular video sites (e.g. youtube). Still the urls are pretty descriptive. So far I never had any problem to download videos of a tv show called "El Intermedio", like
http://www.atresplayer.com/television/programas/el-intermedio/temporada-11/capitulo-25-17-10-16-las-tarjetas-black-petit-comit_2016101700599.html
The site blocks non-Spanish ips, but youtube-dl seems to bypass this flawlessly (with no specially action by the user). However, it gives an error when downloading videos from the documentary show "Enviado Especial", as in the example above. This is the only program that gives me problems.

**Comment by jaimeMF** [comment]
When trying to play that video in the browser it asks to login, so you'll need to register and use `--username`  or [the .netrc file](https://github.com/rg3/youtube-dl/blob/master/README.md#authentication-with-netrc-file).

**Comment by vitaminace33** [comment]
You are right and not. Let me explain: in this particular site,to login allows to see some content or simply change the video quality form SD to HD (both features not available to non-logged users). Still, youtube-dl bypasses this (as well as region constraints) and always downloads the HD version (with no-login whatsoever). I guess the "blockage" is only done at some first level of the code and it is not checked afterwards. So, you are right when you say that perhaps I should login, but I have just tried it and I receive the same error (even through vpn). I can however see the content through the browser (while logged-in and vpn-connected to override region constraints).

Thx for your interest.

```
@@ -1,12 +1,14 @@
-$ youtube-dl --verbose http://www.atresplayer.com/television/programas/enviado-especial/temporada-1/capitulo-1-programa-caso-pablo-ibar_2016021000468.html 2&> error.txt
+$ youtube-dl --username '##########' --verbose http://www.atresplayer.com/television/programas/enviado-especial/temporada-1/capitulo-1-programa-caso-pablo-ibar_2016021000468.html
 [debug] System config: []
 [debug] User config: []
-[debug] Command-line args: [u'--verbose', u'http://www.atresplayer.com/television/programas/enviado-especial/temporada-1/capitulo-1-programa-caso-pablo-ibar_2016021000468.html', u'2']
-[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
+[debug] Command-line args: [u'--username', u'PRIVATE', u'--verbose', u'http://www.atresplayer.com/television/programas/enviado-especial/temporada-1/capitulo-1-programa-caso-pablo-ibar_2016021000468.html']
+Type account password and press [Return]: 
+[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
 [debug] youtube-dl version 2016.10.26
 [debug] Python version 2.7.12 - Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
 [debug] exe versions: avconv 2.8.8-0ubuntu0.16.04.1, avprobe 2.8.8-0ubuntu0.16.04.1, ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1, rtmpdump 2.4
 [debug] Proxy map: {}
+[AtresPlayer] Logging in as ##########
 [AtresPlayer] capitulo-1-programa-caso-pablo-ibar: Downloading webpage
 [AtresPlayer] 20160210-EPISODE-00036-false: Downloading player JSON
 [AtresPlayer] capitulo-1-programa-caso-pablo-ibar: Downloading timestamp
```

**Comment by jaimeMF** [comment]
I don't use the website regularly and don't have an account. But I don't think youtube-dl has never been able to download videos that require an account without login in.
By the way could you post the entire output when you use `--username`?

**Comment by vitaminace33** [comment]
> [...] I don't think youtube-dl has never been able to download videos that require an account without login in.

Precisely, I am telling you that in this site you can. In fact, I use youtube-dl without login nor vpn and never had any problem. You can try to do so in the other link I gave above. However, if you to see this same content from a browser and out of Spain, you won't be able to do so.
> By the way could you post the entire output when you use --username?

From the previous diff, you can see that the ONLY differences are the extra lines
```
Type account password and press [Return]: 
[AtresPlayer] Logging in as ##########
```

**Comment by jaimeMF** [comment]
> Precisely, I am telling you that in this site you can. In fact, I use youtube-dl without login nor vpn and never had any problem. You can try to do so in the other link I gave above. However, if you to see this same content from a browser and out of Spain, you won't be able to do so.

I'm from Spain, I can download videos that doesn't require an account in the browser (like http://www.atresplayer.com/television/programas/el-intermedio/temporada-11/capitulo-33-31-10-16-entrevista-iaki-gabilondo_2016103100888.html or http://www.atresplayer.com/television/programas/salvados/temporada-12/capitulo-3-entrevista-pedro-snchez_2016102800609.html), but both links you posted ask for registration. Does it also happen to you from Spain? Maybe you are right and you could download videos that require registration before, but I don't know if I have ever tried to.

> From the previous diff, you can see that the ONLY differences are the extra lines

OK, I just looked at it and didn't notice it was the diff between both outputs, I wasn't paying too much attention :)

**Comment by vitaminace33** [comment]
The links from the TV shows you provide ask for registration only after some days (weeks). Still, you will anyway have to login to see the content on HD on the browser, if not only SD is available. Notice that, if you use youtube-dl on these links or the one I provided ("El Intermedio"), you will download the HD version directly without having to login and even from abroad.
