### ISSUE TITLE
[anitube] video can' t be downloaded

### ISSUE THREAD

**Issue by gspace3d** [ytdl-org/youtube-dl#11199]
---
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.14.1**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
---
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
Resentry, when I try to download a video from anitube.se I got following message.
(Before 1 month or so, that was OK. and I'm using the latest version of youtube-dl)

~/youtube-dl.exe --verbose "http://www.anitube.se/video/44584/Hyouka-01"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.anitube.se/video/44584/Hyouka-01']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2016.11.14.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-56793-g01e3340
[debug] Proxy map: {}
[anitube.se] 44584: Downloading webpage
[anitube.se] 44584: Downloading XML
[anitube.se] 5fddf0a651a7f5844768: Checking sd video format URL
[anitube.se] 5fddf0a651a7f5844768: sd video format URL is invalid, skipping
ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9fh1o2s3\build\youtube_dl\YoutubeDL.py", line 705, in extract_info
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9fh1o2s3\build\youtube_dl\YoutubeDL.py", line 751, in process_ie_result
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9fh1o2s3\build\youtube_dl\YoutubeDL.py", line 1327, in process_video_result
youtube_dl.utils.ExtractorError: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Can anyone help me ?

**Comment by charon2019** [comment]
@dstftw, this can be closed. Site is down.
