### ISSUE TITLE
[netease:song] support is brocken

### ISSUE THREAD

**Issue by bones7456** [ytdl-org/youtube-dl#11216]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.14.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.14.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

$ ~/youtu.be/youtube-dl --verbose 'http://music.163.com/#/album?id=34720827'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://music.163.com/#/album?id=34720827']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version **2016.11.14.1**
[debug] Python version 2.7.9 - Linux-4.4.21-v7+-armv7l-with-debian-8.0
[debug] exe versions: none
[debug] Proxy map: {}
[netease:album] 34720827: Downloading album data
[download] Downloading playlist: 周杰伦的床边故事
[netease:album] playlist 周杰伦的床边故事: Collected 10 video ids (downloading 10 of them)
[download] Downloading video 1 of 10
[netease:song] 415792916: Downloading song info
[netease:song] 415792916: Checking song URL
[netease:song] 415792916: song URL is invalid, skipping
[netease:song] 415792916: Checking song URL
ERROR: Unable to download webpage: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/pi/youtu.be/youtube-dl/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/pi/youtu.be/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/pi/youtu.be/youtube-dl/youtube_dl/utils.py", line 872, in http_open
    req)
  File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 408, in _read_status
    raise BadStatusLine(line)

**Comment by yan12125** [comment]
Can you play these songs in browsers? And are you in China? As far as I know Netease blocks IPs outside Mainland China.
And by the way #10418 may help

**Comment by bones7456** [comment]
@yan12125 yes, In my Chrome, I can play these songs, I sure in China, and have a China IP.

**Comment by yan12125** [comment]
@bones7456 Could you try #10418?

**Comment by bones7456** [comment]
@yan12125 Yes! It's work. thanks! And thanks @jialongl for #10418
