### ISSUE TITLE
Can't download video, only audio

### ISSUE THREAD

**Issue by john745** [ytdl-org/youtube-dl#11236]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://pmd-dash.ficfiles.com/WM/FLAC_FOD_BRA/417/1007/806817347630_4056000.mpd
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://pmd-dash.ficfiles.com/WM/FLAC_FOD_BRA/417/1007/806817347630_4056000.mpd']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.11.18
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 3.0
[debug] Proxy map: {}
[generic] 806817347630_4056000: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 806817347630_4056000: Downloading webpage
[generic] 806817347630_4056000: Extracting information
[debug] Invoking downloader on 'http://pmd-dash.ficfiles.com/WM/FLAC_FOD_BRA/417/1007/806817347630_4056000_2-encrypted_track1_dashinit_46ecca6347f14240ac627448ba0dbe6f_.mp4'
[download] Destination: 806817347630_4056000-806817347630_4056000.m4a
[download] 100% of 37.60MiB in 00:08
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- Single video: http://www.foxplaybrasil.com.br/watch/806817347630

---

### Description of your *issue*, suggested solution and other information

Hello guys, I'm trying to download this video but the problem is that yt-dl only downloads one audio track from the file and than finishes. The playlist file has 6 audio files and 6 video files. Am I doing something wrong?

**Comment by dstftw** [comment]
DASH DRM is not supported.

**Comment by john745** [comment]
Oh I see. Thanks! :)

**Comment by 89z** [comment]
Issue should be closed, URL is dead
