### ISSUE TITLE
No season numbers in crunchyroll extractor

### ISSUE THREAD

**Issue by Badtz13** [ytdl-org/youtube-dl#11266]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

My command:
```
youtube-dl -v -o "E:/shows/%(series)s/Season %(season_number)s/s%(season_number)se%(episode_number)s - %(episode)s.%(ext)s" --write-sub --sub-lang enUS --embed-subs --playlist-start 1 http://www.crunchyroll.com/food-wars-shokugeki-no-soma --skip-download
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-o', 'E:/shows/%(series)s/Season %(season_number)s/s%(season_number)se%(episode_number)s - %(episode)s.%(ext)s', '--write-sub', '--sub-lang', 'enUS', '--embed-subs', '--playlist-start', '1', 'http://www.crunchyroll.com/food-wars-shokugeki-no-soma', '--skip-download']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.11.08.1
[debug] Python version 3.5.1 - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg 2.8.4, ffprobe N-79000-g66edd86, rtmpdump 2.3
[debug] Proxy map: {}...
<end of log>
```
The folders and files created by this command all work, except for the part where I use the season number. 'Na' is substituted for 'season', 'season_id', 'season_number, and all of the chapter ones as well. Is this due to the way that crunchyroll displays seasons, or is it something that can be added to the crunchyroll extractor?

**Comment by badtzmaru** [comment]
I don't know enough about youtube-dl to know if this helps, but It looks as if the season number is displayed on the page. The element has an xpath of ``` //*[@id="showmedia_about_media"]/h4[2] ```

**Comment by oxguy3** [comment]
Not seeing that element in the page @badtzmaru; tested on http://www.crunchyroll.com/oreimo. I'm pretty sure Crunchyroll doesn't have the season numbers anywhere. I generally just use the %(series)s value and then use `mmv` to fix it afterwards.

**Comment by badtzmaru** [comment]
@oxguy3 Oh, do you need it on the playlist page? I was going off of the pages of the individual pages.

**Comment by badtzmaru** [comment]
Also can't you just use the title attribute of the list items similar to this //*[@id="showview_content_videos"]/ul/li[1]/a ?

**Comment by 6cUbi57z** [comment]
Old post but it's still open so I'll put this here for anyone else looking for a solution.

Crunchyroll doesn't have a concept of season numbers (anime seasons tend to differ between Japan and US releases).

I think `%(series)s` is meant as the name of the show (i.e. TV series), the best option (at the moment at least) is to use `%(season)s` instead. This will give you the name of the season. For single-season shows it just uses the anime name. For multiple season shows, it should appear as it does in Crunchyroll (i.e. "Fairy Tail", "Fairy Tail Series 2", "Fairy Tail Final Season")
