### ISSUE TITLE
Support avclub.com native videos

### ISSUE THREAD

**Issue by teancom** [ytdl-org/youtube-dl#11282]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
$ youtube-dl -v 'http://www.avclub.com/video/trashcan-sinatras-cover-wye-oaks-holy-holy-242512'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.avclub.com/video/trashcan-sinatras-cover-wye-oaks-holy-holy-242512']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.22
[debug] Python version 2.7.12 - Darwin-16.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2
[debug] Proxy map: {}
[generic] trashcan-sinatras-cover-wye-oaks-holy-holy-242512: Requesting header
WARNING: Falling back on generic information extractor.
[generic] trashcan-sinatras-cover-wye-oaks-holy-holy-242512: Downloading webpage
[generic] trashcan-sinatras-cover-wye-oaks-holy-holy-242512: Extracting information
[OnionStudios] 4383: Downloading JSON metadata
[OnionStudios] 4383: Downloading m3u8 information
[debug] Invoking downloader on u'http://v.theonion.com/onionstudios/video/4383/1080.mp4'
[download] Destination: Trashcan Sinatras interview-4383.mp4
[download] 100% of 44.65MiB in 00:45
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.avclub.com/video/trashcan-sinatras-cover-wye-oaks-holy-holy-242512
- Single video: http://www.avclub.com/video/chrissy-and-hawley-cover-erasures-little-respect-246325

---

### Description of your *issue*, suggested solution and other information

When trying to download videos from avclub.com (Native - they embed a lot of videos from Youtube, et. al), youtube-dl appears to grab the secondary video, not the primary one. If you go to my example links, you'll see that the "primary" video (the one of the band actually performing the song) is above-the-fold, and then there is a secondary video (a short interview with the band) that is lower down. I would prefer that youtube-dl grabs both, or only the primary video, either one.

**Comment by yan12125** [comment]
onionstudios embeds. However youtube-dl can't handle multiple videos from different websites in a page well yet
