### ISSUE TITLE
[ruutu] Add support for DRM videos

### ISSUE THREAD

**Issue by okhs** [ytdl-org/youtube-dl#11319]
Hello!

I am using version 2016.11.27

I get the error

"
C:\yt>youtube-dl --verbose http://www.ruutu.fi/video/2602150
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.ruutu.fi/video/2602150']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.11.27
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82664-g801b5c1
[debug] Proxy map: {}
[Ruutu] 2602150: Downloading XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\extractor\ruutu.py", line 104, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\extractor\common.py", line 924, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
"

on some videos (children's cartoons), other videos like http://www.ruutu.fi/video/2824453
work as expected with youtube-dl.

**Comment by dstftw** [comment]
This video requires paid subscription. Can you watch it in browser without being logged in?

**Comment by okhs** [comment]
You don't need paid subscription with youtube-dl. I don't have account on that site, and latest youtube-dl
downloads 
http://www.ruutu.fi/video/2764073
Holmes NYC just fine. Videos are not DRM-protected.
The only problem is the kids section.

**Comment by dstftw** [comment]
It means nothing. Ability to bypass the need of subscription for some videos does not mean it will work for all videos. They may have different protection/delivery mechanisms for different content (and they do as you see).
In any case an account is required to at least figure out what happens behind the scenes for this kind of videos.

**Comment by okhs** [comment]
Okey. I ordered an account. Where should I submit the account details?

**Comment by dstftw** [comment]
You can PM me via email in my profile.

**Comment by okhs** [comment]
Email sent

**Comment by dstftw** [comment]
This is a DRM video and it's delivered differently: http://gatling.nelonenmedia.fi/media-xml-cache?id=2602150.
```
...
<DRM check_url="http://gatling.nelonenmedia.fi/auth/drm_access" asset_id="episode_115123625_201604291302_5VV7yx">1</DRM>
...
```

**Comment by okhs** [comment]
OK. Thanks anyway for your efforts!
