### ISSUE TITLE
Yahoo View site request

### ISSUE THREAD

**Issue by dare2** [ytdl-org/youtube-dl#11333]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://view.yahoo.com/show/the-real-oneals/episode/60803453/the-real-tradition

youtube-dl https://view.yahoo.com/show/the-real-oneals/episode/60792423/the-real-dates --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://view.yahoo.com/show/the-real-oneals/episode/60792423/the-real-dates', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81409-ga3cab3d
[debug] Proxy map: {}
[generic] the-real-dates: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-real-dates: Downloading webpage
[generic] the-real-dates: Extracting information
ERROR: Unsupported URL: https://view.yahoo.com/show/the-real-oneals/episode/60792423/the-real-dates
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\generic.py", line 2433, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://view.yahoo.com/show/the-real-oneals/episode/60792423/the-real-dates

---

**Comment by yan12125** [comment]
On my machine this page says:
```
This video is unavailable at this time. We apologize for
any inconvenience.

If this error is occurring repeatedly, we may be
experiencing technical difficulties. Please visit Hulu
Support for more help.
```
Can you watch this video?

**Comment by dare2** [comment]
Enough time had passed since I posted this issue that the video had expired. Try this one instead:

https://view.yahoo.com/show/the-real-oneals/episode/60808750/the-real-fit

**Comment by yan12125** [comment]
Got the same message with the new URL, too. Does it require a specific browser or geolocation? I'm using Firefox on Linux and I'm in Taiwan.

**Comment by dare2** [comment]
It may be geolocated to the US. It works for me on Chrome in Windows 7.

**Comment by remitamine** [comment]
depends on hulu support #1629.
