### ISSUE TITLE
Channel 5 (my5, milkshake): downloading fails

### ISSUE THREAD

**Issue by Pledkae** [ytdl-org/youtube-dl#11407]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl --verbose --hls-prefer-native http://akahls.channel5.com/C5216600005/C5216600005A/20161021103928/video/1500/C5216600005A_1500.m3u8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--hls-prefer-native', u'http://akahls.channel5.com/C5216600005/C5216600005A/20161021103928/video/1500/C5216600005A_1500.m3u8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.09
[debug] Python version 2.7.11 - Linux-4.3.0-5-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] C5216600005A_1500: Requesting header
[generic] C5216600005A_1500: Downloading m3u8 information
[debug] Invoking downloader on u'http://akahls.channel5.com/C5216600005/C5216600005A/20161021103928/video/1500/C5216600005A_1500.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 34
[download] Destination: C5216600005A_1500-C5216600005A_1500.mp4
[download]   2.9% of ~56.09MiB at 350.28KiB/s ETA 03:07Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 444, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 434, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 705, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 751, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1435, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1699, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 146, in real_download
  File "/home/xubuntu/.local/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/home/xubuntu/.local/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/home/xubuntu/.local/lib/python2.7/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: AES key must be either 16, 24, or 32 bytes long
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Playlist: http://akahls.channel5.com/C5216600005/C5216600005A/20161021103928/C5216600005A.m3u8?faxs=1
- Playlist: http://akahls.channel5.com/C5216600005/C5216600005A/20161021103928/video/1500/C5216600005A_1500.m3u8

---

### Description of your *issue*, suggested solution and other information

.m3u8 links are obtained from milkshake.tv or channel5.com (same result for both sites). Seems geo-blocked, so UK VPN is needed outside UK.
Downloading fails with and without --hls-prefer-native
I'd be very grateful if downloading is possible somehow. Thanks!

**Comment by Ectomind1990** [comment]
Has downloading from Channel 5 ever worked?

Their catch-up TV service was previously called "Demand 5" and is now called "My5". Issue #6543 is a request for Demand 5, so it should probably be closed?

I don't know how to obtain the m3u8 URLs given above.  I would like to see URLs like this supported: https://www.my5.tv/cant-pay-well-take-it-away/season-4/episode-20 (That episode will be until December 2017.  The available shows can be browsed at https://www.my5.tv/categories/all )

**Comment by LevelPulse** [comment]
Any update?

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30242
