### ISSUE TITLE
New flags regarding Download archive file

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#11580]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

In order to manage my automated downloads of some videos more easily, I have set a archive file with the `--download-archive` flag in an user wide configuration file. If I now want to download a video manually, these videos are checked against the archive file. At this point I am sometimes missing several options.
1. If the video has already been downloaded, the download is prevented. If I wan't to (re-)download the video (again), I have no simple option to do so. Solution: New flag `--force-download` - (Re-)downloads the video even if found in the archive file.
2. If the video has not already been downloaded, the download succeeds and is logged in the archive file. I have no option to disable the logging. Solution: New flag `--prevent-archive-logging` - Respects the archive file, but prevents appending it.
3. I am missing the option to ignore the archive file altogether. Solution: New flag `--ignore-archive` - Ignores the contents of the archive files altogether and obviously prevents logging as well. 

As a temporary workaround I have configured several different configuration files and am using the `--config-location` flag. But it would be nice to have a simpler and more streamlined solution.

**Comment by dirkf** [comment]
For Unix-like systems, `--download-archive /dev/null` on the command line would override a value specified in a config file and achieve all of 1-3.

In Windows, [`NUL`](https://ss64.com/nt/nul.html) used to work like this, but I haven't got a recent Windows for testing.
