### ISSUE TITLE
Plus7 MPD/m3u8

### ISSUE THREAD

**Issue by RedPenguin2** [ytdl-org/youtube-dl#11636]
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.05**

- [ X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
youtube-dl -v https://au.tv.yahoo.com/plus7/what-went-down/-/watch/33412628/what-went-down-tue-13-dec-season-1-episode-42/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://au.tv.yahoo.com/plus7/what-went-down/-/watch/33412628/what-went-down-tue-13-dec-season-1-episode-42/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.10.25
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-78313-g6632802, rtmpdump 2.4
[debug] Proxy map: {}
[Yahoo] what-went-down-tue-13-dec-season-1-episode: Downloading webpage
[brightcove:legacy] ref:33412628: Downloading webpage
[brightcove:legacy] ref:33412628: Extracting information
[debug] Invoking downloader on 'https://yahoo7p-a.akamaihd.net/2376984108001/201612/2295/5246884126001/2376984108001_5246884126001_5235518335001.m3u8'
[hlsnative] Downloading m3u8 manifest
WARNING: hlsnative has detected features it does not support, extraction will be delegated to ffmpeg
[download] Destination: What Went Down - Tue 13 Dec, season 1 episode 42-5235518335001.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
' -i https://yahoo7p-a.akamaihd.net/2376984108001/201612/2295/5246884126001/2376984108001_5246884126001_5235518335001.m3u8 -c copy -f mp4 -bsf:a aac_adtstoasc 'file:What Went Down - Tue 13 Dec, season 1 episode 42-5235518335001.mp4.part'
ffmpeg version N-82966-g6993bb4 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 43.100 / 55. 43.100
  libavcodec     57. 70.100 / 57. 70.100
  libavformat    57. 61.100 / 57. 61.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 68.100 /  6. 68.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
[hls,applehttp @ 00000000025324a0] SAMPLE-AES encryption is not supported yet
[hls,applehttp @ 00000000025324a0] Failed to open segment of playlist 0
[hls,applehttp @ 00000000025324a0] SAMPLE-AES encryption is not supported yet

Plus7 in Australia has it now that you cannot use the m3u8 file.

After noticing how the Kodi 7Plus addon does it, YouTube-DL I think could implement it so easily.

For the following video:

https://au.tv.yahoo.com/plus7/what-went-down/-/watch/33366365/what-went-down-mon-12-dec-season-1-episode-40/#page1

Plus7 in Kodi first goes to:

https://edge.api.brightcove.com/playback/v1/accounts/2376984108001/videos/ref:33642615

This seems to be what YouTube-DL is already doing but Kodi then grabs the MPD link vs the m3u8.

It then goes to the mpd at:

https://yahoo7pdash-a.akamaihd.net/2376984108001/2376984108001_5258841828001_5258816577001.mpd

It then goes to:

https://wvlic.brightcove.com/proxy/5228905847001 for the widevine license.

Then it just combined the two at once and plays.

**Comment by WolfganP** [comment]
It happens to me as well (ie https://au.tv.yahoo.com/my-kitchen-rules/video/watch/34496541/my-kitchen-rules-sun-26-feb-season-8-episode-16/#page1 ) but the weird thing is that this error doesn't show always.

Sometimes the episode downloads without a hitch; sometimes -F shows only 3 hls formats available (like the previous link) and sometimes many more (hls and http; ie previous episode https://au.tv.yahoo.com/plus7/my-kitchen-rules/-/watch/34469498/my-kitchen-rules-wed-22-feb-season-8-episode-15/#page1 ). 

It doesn't seem to be a geo-restriction issue. Maybe Plus7 is changing the page during the day and relaxing the encryption?

**Comment by voltagex** [comment]
https://codeload.github.com/glennguy/script.module.drmhelper/zip/master seems to have a way around this.
