### ISSUE TITLE
Last modified (mtime) not being set on certain clip

### ISSUE THREAD

**Issue by Christolito** [ytdl-org/youtube-dl#11718]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-o', u'%(title)s.%(ext)s', u'-x', u'--audio-format', u'mp3', u'--audio-quality', u'128K', u'--add-metadata', u'--prefer-ffmpeg', u'--restrict-filenames', u'-v', u'https://www.youtube.com/watch?v=2MqJ--MduBM']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.10
[debug] Python version 2.7.10 - Darwin-16.3.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[youtube] 2MqJ--MduBM: Downloading webpage
[youtube] 2MqJ--MduBM: Downloading video info webpage
[youtube] 2MqJ--MduBM: Extracting video information
[youtube] 2MqJ--MduBM: Downloading MPD manifest
[debug] Invoking downloader on u'https://r7---sn-jvhixh-bvue.googlevideo.com/videoplayback/id/d8ca89fbe31db813/itag/140/source/youtube/requiressl/yes/mm/31/mn/sn-jvhixh-bvue/initcwndbps/3157500/pl/20/mv/m/ms/au/ratebypass/yes/mime/audio%2Fmp4/otfp/1/gir/yes/clen/584085/lmt/1481717621690630/dur/36.733/key/dg_yt0/upn/CMKVoWKK3bk/mt/1484423158/signature/4CD38F30C5AAD2C8AD8E233E6B5ADB926984CC77.39197C676D2E3B257636782DFF376A389576CFBA/ip/83.248.134.85/ipbits/0/expire/1484445093/sparams/ip,ipbits,expire,id,itag,source,requiressl,mm,mn,initcwndbps,pl,mv,ms,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 5
[download] Destination: Extra_Tack_for_denna_sasong.m4a
[download] 100% of 570.32KiB in 00:00
[ffmpeg] Correcting container in "Extra_Tack_for_denna_sasong.m4a"
[debug] ffmpeg command line: ffmpeg -y -i file:Extra_Tack_for_denna_sasong.m4a -c copy -f mp4 file:Extra_Tack_for_denna_sasong.temp.m4a
[ffmpeg] Adding metadata to 'Extra_Tack_for_denna_sasong.m4a'
[debug] ffmpeg command line: ffmpeg -y -i file:Extra_Tack_for_denna_sasong.m4a -vn -acodec copy -metadata 'comment=Johan tackar för denna säsong! Vi är tillbaka 9e januari. Kom gärna med förslag på vad ni skulle vilja se oss spela! God jul & Gott nytt år!

Rollspel live varje måndag mellan ca 18.15 - 22.00. Följ oss gärna här eller på vår Twitch-kanal.

Twitch; http://bit.ly/rmtwitch
Facebook; http://bit.ly/rmfaceb
Twitter; http://bit.ly/rmtwitt

Prenumerera på vår Youtube-kanal! Missa inte ett fummelslag igen! http://bit.ly/rmtubesub' -metadata 'description=Johan tackar för denna säsong! Vi är tillbaka 9e januari. Kom gärna med förslag på vad ni skulle vilja se oss spela! God jul & Gott nytt år!

Rollspel live varje måndag mellan ca 18.15 - 22.00. Följ oss gärna här eller på vår Twitch-kanal.

Twitch; http://bit.ly/rmtwitch
Facebook; http://bit.ly/rmfaceb
Twitter; http://bit.ly/rmtwitt

Prenumerera på vår Youtube-kanal! Missa inte ett fummelslag igen! http://bit.ly/rmtubesub' -metadata 'artist=Rollspelsmåndag' -metadata 'title=Extra | Tack för denna säsong!' -metadata date=20161214 -metadata 'purl=https://www.youtube.com/watch?v=2MqJ--MduBM' file:Extra_Tack_for_denna_sasong.temp.m4a
[debug] ffmpeg command line: ffprobe -show_streams file:Extra_Tack_for_denna_sasong.m4a
[ffmpeg] Destination: Extra_Tack_for_denna_sasong.mp3
[debug] ffmpeg command line: ffmpeg -y -i file:Extra_Tack_for_denna_sasong.m4a -vn -acodec libmp3lame -b:a 128k file:Extra_Tack_for_denna_sasong.mp3
Deleting original file Extra_Tack_for_denna_sasong.m4a (pass -k to keep)

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=2MqJ--MduBM

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

When getting some clips in my channel (not all), the mtime is not set correctly on the mp3. Its set to the download date & time. I have previously downloaded this clip (but deleted it and emptied the trash)  so its not overwriting something. I can see that the mp4a also has the wrong date before its deleted. If I pass the -k i get the "WARNING: Requested formats are incompatible for merge and will be merged into mkv." but when I look at the files, all of them has the correct date (including the mp3) except the mp4a, which has the downloaded date.

**Comment by dotysan** [comment]
Try this #27138.
