### ISSUE TITLE
[mixcloud] Use API to extract metadata

### ISSUE THREAD

**Issue by a-l-e-k** [ytdl-org/youtube-dl#11721]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.14**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

- Single audio: http://www.mixcloud.com/BlackJack/acid-pauli-on3-radio/

**description**
The (upload date) is not written in the Output filename template. There is a field "created_time" for upload date/time on Mixcloud.

**log**
```
youtube-dl.exe -v --get-filename -o "%(upload_date)s %(title)s" http://www.mixcloud.com/BlackJack/acid-pauli-on3-radio/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--get-filename', '-o', '%(upload_date)s %(title)s', 'http://www.mixcloud.com/BlackJack/acid-pauli-on3-radio/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.01.14
[debug] Python version 3.4.4 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-67100-g6dc99fd, ffprobe N-67100-g6dc99fd, rtmpdump 2.4
[debug] Proxy map: {}
NA Acid Pauli - On3 Radio

<end of log>
```

API: http://api.mixcloud.com/BlackJack/acid-pauli-on3-radio/

**Comment by dstftw** [comment]
>There is a field "created_time" for upload date/time on Mixcloud.

No such field available on the webpage.

**Comment by a-l-e-k** [comment]
I found this field at http://api.mixcloud.com/BlackJack/acid-pauli-on3-radio/

```
"key": "/BlackJack/acid-pauli-on3-radio/", 
"created_time": "2014-10-03T23:43:32Z", 
"audio_length": 7185,
...
```
