### ISSUE TITLE
unable to extract subtitle_lang_code (crunchyroll.com)

### ISSUE THREAD

**Issue by Veykiou** [ytdl-org/youtube-dl#11734]
WARING unable to extract subtitle_lang_code; please report this issue on http://yt-dl.org/bug

I use:
youtube-dl  --format 1080p --write-sub --sub-lang frFR --sub-format ass --username myusername --password mypassword http://www.crunchyroll.com/chain-chronicle-the-light-of-haecceitas-/episode-4-the-light-of-haecceitas-726411

**Comment by federicorosso1993** [comment]
I usually use --all-subs to avoid that problem.
