### ISSUE TITLE
Inifite loop parsing profiles

### ISSUE THREAD

**Issue by frogd** [ytdl-org/youtube-dl#11922]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.31*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.31**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

When parsing profile pages on pornhub it continues checking the next page until it receives a 404 error or it doesn't receive results. If you continue adding ?page=2 ?page=3 etc it will return the same thing over and over.

The code is in pornhub.py function def _real_extract at line #275

**Comment by dstftw** [comment]
>If you continue adding ?page=2 ?page=3 etc it will return the same thing over and over

Wrong:
```
PS C:\Dev\youtube-dl\master> py -2.7 .\youtube_dl\__main__.py http://www.pornhub.com/users/zoe_ph/videos/public -F --write-page --proxy 127.0.0.1:8118
[PornHubUserVideos] zoe_ph: Downloading page 1
[PornHubUserVideos] Saving request to zoe_ph_http_-_www.pornhub.com_users_zoe_ph_videos_publicpage=1.dump
[PornHubUserVideos] zoe_ph: Downloading page 2
[PornHubUserVideos] Saving request to zoe_ph_http_-_www.pornhub.com_users_zoe_ph_videos_publicpage=2.dump
[PornHubUserVideos] zoe_ph: Downloading page 3
[PornHubUserVideos] Saving request to zoe_ph_http_-_www.pornhub.com_users_zoe_ph_videos_publicpage=3.dump
[PornHubUserVideos] zoe_ph: Downloading page 4
[PornHubUserVideos] Saving request to zoe_ph_http_-_www.pornhub.com_users_zoe_ph_videos_publicpage=4.dump
[PornHubUserVideos] zoe_ph: Downloading page 5
[PornHubUserVideos] Saving request to zoe_ph_http_-_www.pornhub.com_users_zoe_ph_videos_publicpage=5.dump
[PornHubUserVideos] zoe_ph: Downloading page 6
[download] Downloading playlist: zoe_ph
[PornHubUserVideos] playlist zoe_ph: Collected 301 video ids (downloading 301 of them)
[download] Downloading video 1 of 301
[PornHub] ph588806e20e58c: Downloading webpage
[PornHub] Saving request to ph588806e20e58c_http_-_www.pornhub.com_view_video.phpviewkey=ph588806e20e58c.dump
[info] Available formats for ph588806e20e58c:
format code  extension  resolution note
240P-400K    mp4        240p        400k
480P-600K    mp4        480p        600k
720P-1500K   mp4        720p       1500k  (best)
[download] Downloading video 2 of 301
[PornHub] ph584e4d5a6948d: Downloading webpage

ERROR: Interrupted by user
```

**Comment by frogd** [comment]
Seeing it work when there's multiple pages like that. 

Try here: http://www.pornhub.com/users/suzu89/videos
