### ISSUE TITLE
[screencast-o-matic] Support embedded players

### ISSUE THREAD

**Issue by xczheng** [ytdl-org/youtube-dl#11976]
youtube-dl -v http://screencast-o-matic.com/watch/cbV2r4Q5TL
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://screencast-o-matic.com/watch/cbV2r4Q5TL']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.01
[debug] Python version 3.6.0 - Linux-3.2.61-grsec-modsign-x86_64-with-debian-wheezy-sid
[debug] exe versions: avconv 0.8.17-4, avprobe 0.8.17-4, ffmpeg 3.2.2-static, ffprobe 3.2.2-static
[debug] Proxy map: {}
[ScreencastOMatic] cbV2r4Q5TL: Downloading webpage
ERROR: Unable to extract setup code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/colinz/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/colinz/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 369, in extract
    return self._real_extract(url)
  File "/home/colinz/lib/python3.6/site-packages/youtube_dl/extractor/screencastomatic.py", line 29, in _real_extract
    r"(?s)jwplayer\('mp4Player'\).setup\((\{.*?\})\);", webpage, 'setup code'),
  File "/home/colinz/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 672, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract setup code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ThomasChr** [comment]
Confirmed.
The video does not use the mp4player (which screencastomatic is supposed to use according to the extractor test) instead it uses Adobe Flash.

I'm not sure if youtube-dl has some tricks to download flash videos but at least for this URL there is a rewrite in the extractor code needed.

**Comment by yan12125** [comment]
It uses an embedded player: http://screencast-o-matic.com/embed?ff=true&sc=cbV2r4Q5TL&fromPH=true&a=1
