### ISSUE TITLE
Site support request: http://svenskhockey.play.livearena.com/

### ISSUE THREAD

**Issue by vasilyeu-pavel** [ytdl-org/youtube-dl#11991]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.04.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [х] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.04.1**

### Before submitting an *issue* make sure you have:
- [х] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [х] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [х] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl-2017.02.04.1 -v "https://sportsnortheu02.str
eaming.mediaservices.windows.net/ea8248c4-5730-414f-8be0-91c05733c81a/923c8ef4-a
ebf-4c91-a752-83de8da8af02.ism/manifest(format=mpd-time-csf)"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://sportsnortheu02.streaming.mediaservic
es.windows.net/ea8248c4-5730-414f-8be0-91c05733c81a/923c8ef4-aebf-4c91-a752-83de
8da8af02.ism/manifest(format=mpd-time-csf)']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.02.04.1
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-52233-gee94362, ffprobe N-52233-gee94362
[debug] Proxy map: {}
[generic] manifest(format=mpd-time-csf): Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest(format=mpd-time-csf): Downloading webpage
[generic] manifest(format=mpd-time-csf): Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpwby3zsth\bu
ild\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpwby3zsth\bu
ild\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpwby3zsth\bu
ild\youtube_dl\extractor\generic.py", line 1729, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpwby3zsth\bu
ild\youtube_dl\extractor\common.py", line 936, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.

**Comment by yan12125** [comment]
Please paste the video URL rather than the manifest's

**Comment by vasilyeu-pavel** [comment]
http://svenskhockey.play.livearena.com/sub/brynasifj20superelit/Vod/900ea5c3c03e4330c4e500949aa4ef7a

hockey@instatsport.com 
hockey12345

**Comment by yan12125** [comment]
Please don't paste passwords on public forums. You should modify your password NOW.

**Comment by vasilyeu-pavel** [comment]
This video is private, I understand all the responsibility, you can not open a video without any login and password
