### ISSUE TITLE
Site support request: www.cstar.fr

### ISSUE THREAD

**Issue by jesus2099** [ytdl-org/youtube-dl#11990]
This is a TV replay site:

- Single video: http://www.cstar.fr/spectacles/pid8433-spectacles.html?vid=1433603 `==` http://cstar.fr/pid8433.html?vid=1433603
- Playlist: http://www.cstar.fr/spectacles/pid8433-spectacles.html `==` http://cstar.fr/pid8433.html
- Playlist with more than one video: http://www.cstar.fr/docs-mags/pid6275-le-zap.html == http://cstar.fr/pid6275.html

※ `/pid8433` where 8433 is like a program ID  ; and `1433603` is like a video ID

**Comment by LucBerge** [comment]
http://www.cstar.fr mouved to https://www.mycanal.fr/chaines/cstar

**Comment by jesus2099** [comment]
@LucBerge, you close this ticket because it will be handled by #18240?

**Comment by remitamine** [comment]
mycanal.fr is already supported, #18240 is about problems with mycanal.fr DRM protected videos.

**Comment by jesus2099** [comment]
Oh great! Lucky move!
