### ISSUE TITLE
ERROR: Cannot get resampling context

### ISSUE THREAD

**Issue by Ankou** [ytdl-org/youtube-dl#1226]
Hi,

I am unable to recode to mp4.

Output of command is below:

 youtube-dl -v -t --recode-video mp4 http://www.youtube.com/watch?v=8B8jRMMkCyo
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['-v', '-t', '--recode-video', 'mp4', 'http://www.youtube.com/watch?v=8B8jRMMkCyo']
[debug] youtube-dl version 2013.08.09
[debug] Python version 2.6.6 - Linux-2.6.32-279.5.2.el6.i686-i686-with-centos-6.3-Final
[debug] Proxy map: {}
[youtube] Setting language
[youtube] 8B8jRMMkCyo: Downloading video webpage
[youtube] 8B8jRMMkCyo: Downloading video info webpage
[youtube] 8B8jRMMkCyo: Extracting video information
[download] Destination: Homer Simpson Explains Minecraft in 10 Seconds-8B8jRMMkCyo.webm
[download] 100.0% of 680.51KiB at 362.19KiB/s ETA 00:00
[ffmpeg] Converting video from webm to mp4, Destination: Homer Simpson Explains Minecraft in 10 Seconds-8B8jRMMkCyo.mp4
ERROR: Cannot get resampling context
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 589, in post_process
    keep_video_wish,new_info = pp.run(info)
  File "/usr/bin/youtube-dl/youtube_dl/PostProcessor.py", line 230, in run
    self.run_ffmpeg(path, outpath, [])
  File "/usr/bin/youtube-dl/youtube_dl/PostProcessor.py", line 85, in run_ffmpeg
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

ffmpeg -version
FFmpeg version 0.6.5, Copyright (c) 2000-2010 the FFmpeg developers
  built on Aug 26 2012 21:44:06 with gcc 4.4.6 20120305 (Red Hat 4.4.6-4)
  configuration: --enable-gpl --enable-shared --enable-pthreads
  libavutil     50.15. 1 / 50.15. 1
  libavcodec    52.72. 2 / 52.72. 2
  libavformat   52.64. 2 / 52.64. 2
  libavdevice   52. 2. 0 / 52. 2. 0
  libswscale     0.11. 0 /  0.11. 0
FFmpeg 0.6.5
libavutil     50.15. 1 / 50.15. 1
libavcodec    52.72. 2 / 52.72. 2
libavformat   52.64. 2 / 52.64. 2
libavdevice   52. 2. 0 / 52. 2. 0
libswscale     0.11. 0 /  0.11. 0

Thanks!

**Comment by dirkf** [comment]
Historical.
