### ISSUE TITLE
Crunchyroll thinks my membership isn't Premium

### ISSUE THREAD

**Issue by vivia** [ytdl-org/youtube-dl#12464]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ ./youtube-dl --verbose --cookies cookies.txt --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" --no-check-certificate --write-sub --sub-lang=enUS --prefer-ffmpeg  "http://www.crunchyroll.com/polar-bear-cafe/episode-6-pandas-diet-strive-for-it-wild-panda-595197" 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--cookies', u'cookies.txt', u'--user-agent', u'Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0', u'--no-check-certificate', u'--write-sub', u'--sub-lang=enUS', u'--prefer-ffmpeg', u'http://www.crunchyroll.com/polar-bear-cafe/episode-6-pandas-diet-strive-for-it-wild-panda-595197']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.15
[debug] Python version 2.7.13 - Linux-4.9.0-2-amd64-x86_64-with-debian-9.0
[debug] exe versions: avconv 3.2.4-1, avprobe 3.2.4-1, ffmpeg 3.2.4-1, ffprobe 3.2.4-1, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] 595197: Downloading webpage
ERROR: crunchyroll returned error: Note: This video requires a <a href="/freetrial?src=geo_sm">Premium Membership</a> to watch in your region.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/crunchyroll.py", line 404, in _real_extract
    raise ExtractorError('crunchyroll returned error: %s' % msg['message_body'], expected=True)
ExtractorError: crunchyroll returned error: Note: This video requires a <a href="/freetrial?src=geo_sm">Premium Membership</a> to watch in your region.
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

There is this series that I'm not able to download. youtube-dl claims that I need a premium membership to download this, but I do have one, and in fact I can get to the "please install Flash" webpage on my browser or watch this video from the same account on my Kodi device. I can also download other series using the same command line, but not this one.

**Comment by paetre** [comment]
I have this problem as well and it persists with the 2017.04.26 version as well.  Also with Linux x86_64 architecture (Linux-4.8.0-49-generic-x86_64-with-Ubuntu-16.10-yakkety), and also with Python 2.7.13.  I've also got a Crunchyroll Premium account as well.

What I was noticing when I tried using _youtube-dl -F _http://www.crunchyroll.com/[URL]  --cookies cookies.txt_ was that only 360p and 480p formats were being listed.  So I issued, the same command on a Windows machine (built-in Python 3.4.4 in the binary) and all the formats were listed.  In the end, I set my Ubuntu Linux machine to default to Python 3.5 and everything worked fine (2017.03.15 and 2017.04.26).  Just for some reason, Python 2.7.13 seems to be having issues with the cookies.txt file.

**Comment by vivia** [comment]
They appear to be two different issues. I tried with python3 and I'm still getting the same error :(

In my case, youtube-dl seems to download the webpage before parsing the cookies, from what I can tell.

**Comment by paetre** [comment]
I'll try to retrace my steps and see what I did in a couple hours when I have a bit more time.  I did offer to gift dstftw a Crunchyroll Premium trial account (via email) as I'm just an end-user myself.

**Comment by Starsam80** [comment]
Try re-exporting the cookies from the browser. I've had this happen to me a few times.
