### ISSUE TITLE
[vidzi] Get Error Wrong IP

### ISSUE THREAD

**Issue by best-job** [ytdl-org/youtube-dl#12629]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.03**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
youtube-dl -v http://vidzi.tv/embed-a7btehrmc0j0.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://vidzi.tv/embed-a7btehrmc0j0.html']
[debug] Encodings: locale cp1256, fs mbcs, out cp720, pref cp1256
[debug] youtube-dl version 2017.04.03
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[Vidzi] a7btehrmc0j0: Downloading webpage
[Vidzi] a7btehrmc0j0: Downloading m3u8 information
[debug] Invoking downloader on 'http://77.81.98.60:8777/hls/gnuqic3xue2qedz7nlyrrgttk2zkxog2sgn2w3acbk6dgk3bmxnl73po366a/chunk.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1
[download] Destination: CimaClub Com Billions S02E05  HDTV-a7btehrmc0j0.mp4
[download] 100% of 39.00B in 00:00
WARNING: a7btehrmc0j0: malformated aac bitstream. Install ffmpeg or avconv to fix this automatically.

youtube-dl --source-address http://vidzi.tv/embed-a7btehrmc0j0.html
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

E:\Youtube-dl>youtube-dl --source-address -v http://vidzi.tv/embed-a7btehrmc0j0.html
[Vidzi] a7btehrmc0j0: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 11001] getaddrinfo failed> (caused by URLError(gaierror(11001, 'getaddrinfo failed'),))
...
<end of log>
```
---
- Single video: http://vidzi.tv/embed-a7btehrmc0j0.html
---
### Description of your *issue*, suggested solution and other information

The program generates the link but there is a problem with the IP address :
http://77.81.98.60:8777/hls/gnuqic3xue2qedz7nlyrrgttk2zkxog2sgn2w3acbk6dgk3bmxnatyxo366a/chunk.m3u8
But Result :  Wrong IP: (10.128.33.238) vs 5.0.16.246

**Comment by dstftw** [comment]
```
PS C:\dev\youtube-dl\master> py -3.6 .\youtube_dl\__main__.py http://vidzi.tv/embed-a7btehrmc0j0.html
[Vidzi] a7btehrmc0j0: Downloading webpage
[Vidzi] a7btehrmc0j0: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 452
[download] Destination: CimaClub Com Billions S02E05  HDTV-a7btehrmc0j0.mp4
[download]   0.4% of ~399.85MiB at 701.10KiB/s ETA 52:59
ERROR: Interrupted by user
```

**Comment by best-job** [comment]
what's the problem ? I have tried a lot and could not download the video

**Comment by best-job** [comment]
And also this problem With vidzi:
ERROR: Unable to download webpage: <urlopen error [Errno 7] no address associated with hostname.> (caused by URLError(gaierror(7, 'no address associated with hostname.'),))

**Comment by best-job** [comment]
what's solve this problem

**Comment by XWhatevs** [comment]
He clearly added the `cant-reproduce` tag, which means that the issue is on your end.
