### ISSUE TITLE
Problems with downloading games from watch.nba.com

### ISSUE THREAD

**Issue by mariuszkorba** [ytdl-org/youtube-dl#12675]
Hi

Great project - really useful for watching videos off-line.

Though I cannot get the latest binary to download anything from my NBA League Pass subscription.
Tried all flavour of the url, i.e.: https://watch.nba.com/game/20170407/ATLCLE?s=i
and getting:
>ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

When in verbose I'm getting this:
>[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://watch.nba.com/game/20170407/ATLCLE?s=i', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.03
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-85274-g9fe73b0-tessus
[debug] Proxy map: {}
[NBA] ATLCLE: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/nba.py", line 137, in _real_extract
    path = remove_start(self._search_regex(r'data-videoid="([^"]+)"', webpage, 'video id'), '/')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 778, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Does anyone have the same issue or know other way of downloading games from nba?
Would appreciate your comments / views

Cheers
m

**Comment by masonelmore** [comment]
It looks like the site requires authentication.  I'm not able to test it because I do not have an account.  Have you tried using the `--username` and `--password` options?

`youtube-dl --username YOUR_USERNAME --password YOUR_PASSWORD https://watch.nba.com/game/20170407/ATLCLE?s=i`

**Comment by roselove33** [comment]
Hello

**Comment by mariuszkorba** [comment]
Hi **masonelmore**

Thanks for your comment.
Yeap, tried the `-u` and `-p` but unfortunately no joy - I get the same error... :(

m

**Comment by raffam** [comment]
Same problem, `--username` and `--password` options doesn't solve it, can provide active NBA League Pass account credentials to developers, NBA website seems to be supported on the youtube-dl list

**Comment by OddBloke** [comment]
I'm also seeing this issue using cookies.txt from watch.nba.com
