### ISSUE TITLE
Site support request: pusher.com/sessions

### ISSUE THREAD

**Issue by in-in** [ytdl-org/youtube-dl#12772]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://pusher.com/sessions/meetup/the-realtime-guild/golangs-realtime-garbage-collector
- Single video: https://pusher.com/sessions/meetup/reactivate-london/from-css-preprocessors-to-styled-components

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

**Comment by Abhinav1217** [comment]
Plus one for pusher.com videos. Those keynotes are very informative.

**Comment by yan12125** [comment]
Generic Wistia embeds, however malformed HTML confuses youtube-dl
```
!=
<!doctype html>
<html lang="en">
<head>
```

**Comment by in-in** [comment]
I'm closing the issue because now I can download videos from pusher.com/sessions without any problems. Moreover, it looks like they're uploading their videos on YouTube https://www.youtube.com/user/pusherapp/videos
