### ISSUE TITLE
news.sky.com does not work with every video

### ISSUE THREAD

**Issue by dban0001** [ytdl-org/youtube-dl#13055]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl "http://news.sky.com/video/the-mystery-space-plane-you-shouldnt-know-anything-about-10869049" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://news.sky.com/video/the-mystery-space-plane-you-shouldnt-know-anything-about-10869049', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.09
[debug] Python version 2.7.12 - Linux-4.4.0-21-generic-x86_64-with-LinuxMint-18-sarah
[debug] exe versions: ffmpeg N-85548-g3390a2b, ffprobe N-85548-g3390a2b, rtmpdump 2.4
[debug] Proxy map: {}
[generic] the-mystery-space-plane-you-shouldnt-know-anything-about-10869049: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-mystery-space-plane-you-shouldnt-know-anything-about-10869049: Downloading webpage
[generic] the-mystery-space-plane-you-shouldnt-know-anything-about-10869049: Extracting information
ERROR: Unsupported URL: http://news.sky.com/video/the-mystery-space-plane-you-shouldnt-know-anything-about-10869049
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1955, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 198, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2834, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://news.sky.com/video/the-mystery-space-plane-you-shouldnt-know-anything-about-10869049
```

**Comment by MttCastelli** [comment]
PS C:\Users\Matteo> youtube-dl.exe -v https://video.sky.it/sport/calcio/serie-a/video-allegri-adani-sky-confronto-integrale/v508397.vid
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://video.sky.it/sport/calcio/serie-a/video-allegri-adani-sky-confronto-integrale/v508397.vid']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.04.30
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {'ftp': 'ftp://10.255.255.105:3128', 'https': 'https://10.255.255.105:3128', 'http': 'http://10.255.255.105:3128'}
[generic] v508397: Requesting header
WARNING: Could not send HEAD request to https://video.sky.it/sport/calcio/serie-a/video-allegri-adani-sky-confronto-integrale/v508397.vid: HTTP Error 405: Method Not Allowed
[generic] v508397: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] v508397: Extracting information
ERROR: Unsupported URL: https://video.sky.it/sport/calcio/serie-a/video-allegri-adani-sky-confronto-integrale/v508397.vid
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\extractor\generic.py", line 3320, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://video.sky.it/sport/calcio/serie-a/video-allegri-adani-sky-confronto-integrale/v508397.vid

PS C:\Users\Matteo>
