### ISSUE TITLE
This video is unavailable purchased YouTube TV Show

### ISSUE THREAD

**Issue by bignadad** [ytdl-org/youtube-dl#13075]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.09**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

D:\tmp\yt>youtube-dl -v http://www.youtube.com/watch?v=NyaJ5KkgXec -u xxxx@xxxx.com

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.youtube.com/watch?v=NyaJ5KkgXec', '-u', 'PRIVATE']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.09
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
Type 2-step verification code and press [Return]:
[youtube] Submitting TFA code
[youtube] Checking cookie
[youtube] NyaJ5KkgXec: Downloading webpage
[youtube] NyaJ5KkgXec: Downloading video info webpage
[youtube] NyaJ5KkgXec: Extracting video information
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpup5muf90\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpup5muf90\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpup5muf90\build\youtube_dl\extractor\youtube.py", line 1827, in _real_extract
youtube_dl.utils.ExtractorError: This video is unavailable.
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Trying to download a purchased tv show from youtube

**Comment by dstftw** [comment]
For any further investigations you must provide account credentials.

**Comment by bignadad** [comment]
How can i do that securely?

**Comment by dstftw** [comment]
By email. Also, what is your location? The video is geo restricted.

**Comment by bignadad** [comment]
what email. also my account is setup with 2-step verification. I am in the US

**Comment by dstftw** [comment]
In my profile. You'll have to disable TFA.

**Comment by bignadad** [comment]
emailed.

**Comment by saudalwasly** [comment]
I have got the same problem. Is it solved already? I hope you can share the resolution.

**Comment by SuperDOS** [comment]
same here

**Comment by SuperDOS** [comment]
here's a free video that need to be purchased that can be tested with [https://www.youtube.com/watch?v=0cz5YQWdpMc](url)

**Comment by yuuzhan** [comment]
I am also experiencing this issue.

I have run the command with --write-pages and have various dump files that I could send if that helped.

I think the issue is that the following is on the page:
`    <h1 id="unavailable-message" class="message">
              This video is unavailable.

    </h1>`

As well as the following:

`yt.setConfig({
    'YPC_LOADER_JS': "\/yts\/jsbin\/www-ypc-vflMg-NsA\/www-ypc.js",
    'YPC_LOADER_CSS': "\/yts\/cssbin\/www-ypc-vflXFWcXr.css",
    'YPC_SIGNIN_URL': "https:\/\/accounts.google.com\/XXXX",
    'DBLCLK_ADVERTISER_ID': "XXXX",
    'DBLCLK_YPC_ACTIVITY_GROUP': "XXXX",
    'SUBSCRIPTION_URL': "\/subscription_ajax",
    'YPC_SWITCH_URL': "\/signin?XXXXfeature=purchases",
    'YPC_GB_LANGUAGE': "en_US",
    'YPC_MB_URL': "https:\/\/payments.youtube.com\/payments\/v4\/js\/integrator.js?ss=md",
    'YPC_TRANSACTION_URL': "\/transaction_handler",
    'YPC_SUBSCRIPTION_URL': "\/ypc_subscription_ajax",
    'YPC_POST_PURCHASE_URL': "\/ypc_post_purchase_ajax",
    'YTR_FAMILY_CREATION_URL': "https:\/\/families.google.com\/webcreation?usegapi=1",
    'YTO_GTM_DATA': {'event': 'purchased', 'purchaseStatus': 'success'},
    'YTO_GTM_1_BUTTON_CLICK_DATA': {'event': 'landingButtonClick', 'buttonPosition': '1'},
    'YTO_GTM_2_BUTTON_CLICK_DATA': {'event': 'landingButtonClick', 'buttonPosition': '2'}
  });`

Let me know if you want the full dump files.

**Comment by rdurdle** [comment]
Similiar issue.

`
youtube-dl --verbose -u user@domain.com "https://www.youtube.com/watch?v=xvyuGtWNX6o"

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-u', u'PRIVATE', u'https://www.youtube.com/watch?v=xvyuGtWNX6o']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.11
[debug] Python version 2.7.12 - Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] xvyuGtWNX6o: Downloading webpage
[youtube] xvyuGtWNX6o: Downloading video info webpage
[youtube] xvyuGtWNX6o: Extracting video information
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1948, in _real_extract
    raise ExtractorError(unavailable_message, expected=True)
ExtractorError: This video is unavailable.
`

**Comment by rogiervandenberg** [comment]
Same issue:
```terminal
youtube-dl https://www.youtube.com/watch\?v\=FKUvkKsTzV8 --cookie cookies.txt -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=FKUvkKsTzV8', u'--cookie', u'cookies.txt', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.15.1
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] FKUvkKsTzV8: Downloading webpage
[youtube] FKUvkKsTzV8: Downloading video info webpage
[youtube] FKUvkKsTzV8: Extracting video information
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1949, in _real_extract
    raise ExtractorError(unavailable_message, expected=True)
ExtractorError: This video is unavailable.
```
Without the cookie (with my logged in session) I successfully can download the trailer...

**Comment by saudalwasly** [comment]
It seems that the --cookie option expects a specific format, e.g., Netscape format.

anyone with luck on this problem yet?

**Comment by rogiervandenberg** [comment]
this is the same: https://github.com/rg3/youtube-dl/issues/14459

**Comment by uruiamme** [comment]
So it looks like if I buy or rent a video from YouTube, the downloader doesn't work. I have the same issue and the same error. "This video is unavailable." Windows, Youtube-dl 2017.10.29 latest version.
