### ISSUE TITLE
Remove from Playlist on Completed Download

### ISSUE THREAD

**Issue by mneimeyer** [ytdl-org/youtube-dl#131]
This is a request to add an option to remove a video from the playlist when download is successfully completed.

I would find this very useful, for example, with YouTube's "Watch Later" playlist and a cron script. The end result being that every night I could have my system download anything I added to my Watch Later playlist during the day.

Would probably need to make sure that it can handle an empty playlist (in the event nothing is added to the playlist that day) and would be nice to be able to specify on the command line what folder to download the videos to.

Thanks!

**Comment by dirkf** [comment]
Nowadays: `--download-archive ...`.
