### ISSUE TITLE
Support for Minds.com

### ISSUE THREAD

**Issue by someguy736** [ytdl-org/youtube-dl#13220]
I would like to request [Minds.com](https://www.minds.com) support if you get the chance.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by someguy736** [comment]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.05.26
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```
youtube-dl -v "https://www.minds.com/archive/view/715172106794442752"
[debug] System config: []
[debug] User config: [u'--no-check-certificate', u'--output', u'/home/main/dlr/%(uploader)s/%(upload_date)s/%(title)s/%(title)s-%(id)s.%(ext)s', u'--user-agent', u'Mozilla/5.0 (compatible)', u'--audio-quality', u'0', u'--merge-output-format', u'mp4', u'--sub-lang', u'en', u'--all-subs', u'--sub-format', u'srt', u'--embed-subs', u'--write-description', u'--retries', u'10', u'--sleep-interval', u'1', u'--max-sleep-interval', u'5', u'-i', u'-f', u'(mp4)[height=360]/(mp4)[height=480]/[height=1080]/best', u'--playlist-end', u'35', u'--dateafter', u'20151104', u'--download-archive', u'/home/main/.config/youtube-dl/archive', u'--no-call-home', u'--external-downloader', u'aria2c', u'--external-downloader-args', u"--continue=true --check-integrity=true --max-connection-per-server=5 --min-split-size=1M --max-tries=0 --user-agent='Mozilla/5.0 (compatible)'"]
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.minds.com/archive/view/715172106794442752']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.26
[debug] Python version 2.7.12 - Linux-4.4.0-75-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 715172106794442752: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 715172106794442752: Downloading webpage
[generic] 715172106794442752: Extracting information
ERROR: Unsupported URL: https://www.minds.com/archive/view/715172106794442752
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1970, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 32, column 41
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2795, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.minds.com/archive/view/715172106794442752

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.minds.com/archive/view/715172106794442752
- Single video: ???
- Playlist: ???

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I wasn't sure I needed anything else for a site support request. Nonetheless I have provided the requested information.

**Comment by Tatsh** [comment]
I am working on this in my fork.
