### ISSUE TITLE
[Request] Support neo-magazin-royale.de

### ISSUE THREAD

**Issue by Nothing4You** [ytdl-org/youtube-dl#13473]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ ~/youtube-dl -v http://www.neo-magazin-royale.de/zdi/artikel/137606/neo-magazin-royale-vom-22-06-2017.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.neo-magazin-royale.de/zdi/artikel/137606/neo-magazin-royale-vom-22-06-2017.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.23
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.8
[debug] exe versions: avconv 11.9-6, avprobe 11.9-6
[debug] Proxy map: {}
[generic] neo-magazin-royale-vom-22-06-2017: Requesting header
WARNING: Falling back on generic information extractor.
[generic] neo-magazin-royale-vom-22-06-2017: Downloading webpage
[generic] neo-magazin-royale-vom-22-06-2017: Extracting information
ERROR: Unsupported URL: http://www.neo-magazin-royale.de/zdi/artikel/137606/neo-magazin-royale-vom-22-06-2017.html
Traceback (most recent call last):
  File "/home/user/youtube-dl/youtube_dl/extractor/generic.py", line 1971, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/user/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/home/user/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 13, column 2
Traceback (most recent call last):
  File "/home/user/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/home/user/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/home/user/youtube-dl/youtube_dl/extractor/generic.py", line 2796, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.neo-magazin-royale.de/zdi/artikel/137606/neo-magazin-royale-vom-22-06-2017.html
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.neo-magazin-royale.de/zdi/artikel/137606/neo-magazin-royale-vom-22-06-2017.html
- Single video: http://www.neo-magazin-royale.de/zdi/artikel/137571/rto-ehrenfeld-harder-better-faster-stronger.html

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

They're using the same player as zdf.de, which is already supported. Same video downloads via https://www.zdf.de/comedy/neo-magazin-mit-jan-boehmermann/neo-magazin-royale-mit-jan-boehmermann-vom-22-juni-2017-100.html just fine.

**Comment by flak3** [comment]
The start button of the player contains a data-sophoraid element:
```html
<a href="#" data-player="PROTO_PLAYER_137606_500_0" data-sophoraid="neo-magazin-royale-mit-jan-boehmermann-vom-22-juni-2017-100" data-sophoraimage="" tabindex="0" class="module-player overlay" title="(Quelle: ZDF)" data-ready="true"></a>
```
Putting the content into the ZDF link like this: `https://www.zdf.de/comedy/neo-magazin-mit-jan-boehmermann/<content>.html` and passing it to the ZDF extractor should work.

**Comment by rusty-snake** [comment]
`neo-magazin-royale.de` is now a redirect to `https://www.zdf.de/comedy/neo-magazin-mit-jan-boehmermann`. I think this can be closed.
