### ISSUE TITLE
Support for Spreaker.com

### ISSUE THREAD

**Issue by rudolphos** [ytdl-org/youtube-dl#13480]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.23**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-ci', '--write-thumbnail', '--sub-format', 'ass/srt/best', '--write-auto-sub', '--convert-subs', 'srt', '--write-description', '--write-info-json', '-f', 'bestvideo+bestaudio/best', '-o', '/Videos/%(uploader)s - %(title)s (%(id)s).%(ext)s', '-v', 'http://www.spreaker.com/show/andre-dorseys-show']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.06.23
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-81774-g64545dd, rtmpdump 2.4
[debug] Proxy map: {}
[generic] andre-dorseys-show: Requesting header
WARNING: Falling back on generic information extractor.
[generic] andre-dorseys-show: Downloading webpage
[generic] andre-dorseys-show: Extracting information
[generic] player?show_id=2452465&autoplay=false: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player?show_id=2452465&autoplay=false: Downloading webpage
[generic] player?show_id=2452465&autoplay=false: Extracting information
ERROR: Unsupported URL: https://widget.spreaker.com/player?show_id=2452465&autoplay=false
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\YoutubeDL.py", line 762, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\extractor\generic.py", line 2796, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://widget.spreaker.com/player?show_id=2452465&autoplay=false
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.spreaker.com/user/dmgaming/should-madden-18-be-half-price
- Single video: http://api.spreaker.com/download/episode/12166906/should_madden_18_be_half_price.mp3
- Playlist: http://www.spreaker.com/show/andre-dorseys-show
- RSS: http://www.spreaker.com/show/2452465/episodes/feed

---

**Comment by mayeaux** [comment]
Did this ever get merged?

**Comment by lstolcman** [comment]
> 
> 
> Did this ever get merged?

bump for this :)

**Comment by tjesp** [comment]
I'm on "2019.09.01" and I miss this :)

**Comment by rudolphos** [comment]
bump 2+ years later
