### ISSUE TITLE
[hbo] add support for subtitles

### ISSUE THREAD

**Issue by SeanPM5** [ytdl-org/youtube-dl#13709]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)

### Description of your *issue*, suggested solution and other information
HBO is a supported site and works great, but currently it does not find the captions/subtitles. These are already listed inside the xml file as "captionUrl".

- Example video: http://www.hbo.com/silicon-valley/episodes/4/35-the-patent-troll/video/ep-35-preview.html?autoplay=true
- XML ("captionUrl" is near top): http://render.lv3.hbo.com/data/content/global/videos/data/1462950.xml
- Subtitles file: http://i.lv3.hbo.com/assets/captions/series/silicon-valley/season-04/ep-35-preview-61999306_PRO35_CC_2.xml

**Comment by matan129** [comment]
Shotgun! (on it - from Hacktoberfest TLV)

**Comment by glirios** [comment]
If this issue is still available, I would like to try to take it on.
