### ISSUE TITLE
Issues With Videos On Atresplayer

### ISSUE THREAD

**Issue by Pcsl** [ytdl-org/youtube-dl#13807]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.atresplayer.com/television/programas/aho
ra-caigo/temporada-1/capitulo-1431-13-07-17_2017071200923.html', 'cookies', '\\c
ookies.txt', '-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[AtresPlayer] Logging in as zqianvxd@vomoto.com
[AtresPlayer] capitulo-1431-13-07-17: Downloading webpage
[AtresPlayer] 20170712-EPISODE-00904-false: Downloading player JSON
[AtresPlayer] capitulo-1431-13-07-17: Downloading timestamp
[AtresPlayer] capitulo-1431-13-07-17: Downloading windows video JSON
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (
caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make
 sure you are using the latest version; type  youtube-dl -U  to update. Be sure
to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\bu
ild\youtube_dl\extractor\common.py", line 502, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\bu
ild\youtube_dl\YoutubeDL.py", line 2166, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

This issue is related with Atresplayer. Atresplayer has 3 kind of videos:
- Public: Everyone can play them
- Private: They are identified by a lock and you need to log in to be able to watch them
- Premium: You have to pay a subscription to be able to play them

Youtube-dl has issues downloading ANY Public, Private or Premium videos from webpages like [this](http://www.atresplayer.com/television/programas/ahora-caigo/). When trying to download Private or Premium Videos, issues appear as you can check on the previous log.

However, I have no problems to download public videos from webpages like [this](http://www.atresplayer.com/television/programas/me-resbala/) one.

I created a test account so you can check issues with any kind of videos:
Login: zqianvxd@vomoto.com
Password: youtube-dl

You can see more "private" videos if you go to this [URL](http://www.atresplayer.com/television/programas/ahora-caigo/) and scroll right until you see locked videos. If you scroll right even more, you will see Premium videos.

Any idea about what is causing the Error 500?

**Comment by rosek86** [comment]
Hi, I have the same problem using 2017.12.31 version.
