### ISSUE TITLE
[bfmtv][brightcove] A valid ID was not sent for this player

### ISSUE THREAD

**Issue by skyghis** [ytdl-org/youtube-dl#13912]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.13*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.13**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.bfmtv.com/mediaplayer/video/l-installation-spectaculaire-du-toit-de-la-gare-de-clamart-971789.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.13
[debug] Python version 2.7.13 - Linux-4.10.0-32-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: ffmpeg 3.2.4-1build2, ffprobe 3.2.4-1build2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] l-installation-spectaculaire-du-toit-de-la-gare-de-clamart-971789: Requesting header
WARNING: Falling back on generic information extractor.
[generic] l-installation-spectaculaire-du-toit-de-la-gare-de-clamart-971789: Downloading webpage
[generic] l-installation-spectaculaire-du-toit-de-la-gare-de-clamart-971789: Extracting information
[download] Downloading playlist: L’installation spectaculaire du toit de la gare de Clamart
[generic] playlist L’installation spectaculaire du toit de la gare de Clamart: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:legacy] 5540343101001: Downloading webpage
ERROR: brightcove said: A valid ID was not sent for this player.
Traceback (most recent call last):
  File "/home/ghislain/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/home/ghislain/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/home/ghislain/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 304, in _real_extract
    videoPlayer[0], query, referer=referer)
  File "/home/ghislain/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 327, in _get_video_info
    'brightcove said: %s' % error_msg, expected=True)
ExtractorError: brightcove said: A valid ID was not sent for this player.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.bfmtv.com/mediaplayer/video/l-installation-spectaculaire-du-toit-de-la-gare-de-clamart-971789.html

**Comment by jeekajoo** [comment]
I don't know how to fix this issue, but here is a workaround for people stumbling-on here. Example:
```
# Get the URL of the brightcove playlist and download it
wget "http://c.brightcove.com/services/mobile/streaming/index/rendition.m3u8?assetId=5675829860001&pubId=5132998232001&videoId=5675822746001" -O playlist.txt
# Download each file from the playlist
cat playlist.txt 
wget ...
# Concatenate previously download video files
ffmpeg -i "concat:1.mp4|2.mp4|3.mp4|4.mp4|5.mp4" -c copy -bsf:a aac_adtstoasc BFMTV.mp4
```

**Comment by sammcj** [comment]
FYI this is still an issue, I'll give a fresh example:

```
youtube-dl -v "airrace.redbull.com/m/en_US/video/kazan-2018-round-14"
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'airrace.redbull.com/m/en_US/video/kazan-2018-round-14']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.01
[debug] Python version 2.7.5 (CPython) - Linux-4.18.5-1.el7.elrepo.x86_64-x86_64-with-centos-7.5.1804-Core
[debug] exe versions: avconv v13_dev0-533-gd30719e, avprobe v13_dev0-533-gd30719e, ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[generic] kazan-2018-round-14: Requesting header
WARNING: Falling back on generic information extractor.
[generic] kazan-2018-round-14: Downloading webpage
[generic] kazan-2018-round-14: Extracting information
[download] Downloading playlist: Kazan 2018 - Round of 14 | Red Bull Air Race
[generic] playlist Kazan 2018 - Round of 14 | Red Bull Air Race: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:legacy] 5826997238001: Downloading webpage
ERROR: brightcove said: A valid ID was not sent for this player.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 304, in _real_extract
    videoPlayer[0], query, referer=referer)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 327, in _get_video_info
    'brightcove said: %s' % error_msg, expected=True)
ExtractorError: brightcove said: A valid ID was not sent for this player.
```
