### ISSUE TITLE
[Request] - Hoopla (https://www.hoopladigital.com)

### ISSUE THREAD

**Issue by level42ca** [ytdl-org/youtube-dl#13926]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.13*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.13**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.hoopladigital.com/play/11118419/0
- Single video: https://d2jzd220tonkw9.cloudfront.net/cen_6t01/cen_6t01_browser_multi.wvm_0.mp4

Both links above are the same, the Hoopla link simply pulls the data from the CloudFront link.

---

### Description of your *issue*, suggested solution and other information

Looking to get https://www.hoopladigital.com added. Seems the videos are actually hosted on cloudfront.net, but whenever I download them via other means the files seem to come in all corrupt.

Hoopla does require authentication to watch, and I can provide these credentials to anyone who is interested in tackling this. Just PM me.

**Comment by michaelaris** [comment]
bump! also would like to see.

**Comment by MDS0LDI3R** [comment]
This would be a great feature.

**Comment by Truanifan** [comment]
Was searching for a way to do this very thing. If this hasn't been implemented yet would you please consider it? I would also really like to see hoopla added.

**Comment by Geremia** [comment]
@level42ca youtube-dl can download your Cloudfront link, but it the resultant audio file is DRM-protected. Are you requesting that youtube-dl strip the DRM?

**Comment by Geremia** [comment]
@level42ca  Also, [Bento4]() ([website](https://www.bento4.com/), [GitHub repo](https://github.com/axiomatic-systems/Bento4)) has a [`mp4decrypt`](https://www.bento4.com/documentation/mp4decrypt/) command could decrypt the MP4 using some key which youtube-dl could probably find.

**Comment by iconoclasthero** [comment]
Is there a way to get that key?

**Comment by bmdbenson** [comment]
Alternative: you can record anything streamable to PC with either the free **_OBS Studio_** or **_Xbox Game Bar_**. Slower than downloading but it works.

**Comment by 89z** [comment]
Issue should be closed, account needed

**Comment by iconoclasthero** [comment]
You need to know what you're doing, but here's a PowerShell script that works on Ubuntu 20.04+, and presumably Windows:
https://github.com/iconoclasthero/Hoopla-DL

**Comment by Littlemac123** [comment]
> You need to know what you're doing, but here's a PowerShell script that works on Ubuntu 20.04+, and presumably Windows: https://github.com/iconoclasthero/Hoopla-DL I didn't write it and I'm not supporting it, but if you want to try your hand with it...

this was recently taken down from a DMCA request heres a backup i have on my laptop <3
[hoopla-dl.ps1.zip](https://github.com/ytdl-org/youtube-dl/files/11659482/hoopla-dl.ps1.zip)

**Comment by dirkf** [comment]
Unless there are items that can be played in the browser with DRM disabled, this site can't be supported in yt-dl. All the indications above are that this isn't the case.

>...this was recently taken down from a DMCA request ...

That should have been a hint that you shouldn't post the script here.

**Comment by Amraan-Amjad** [comment]
Will this work on audiobooks?
@dirkf

**Comment by ckujau** [comment]
> Will this work on audiobooks? @dirkf

Since this issue is closed, this won't work at all :-\

**Comment by dirkf** [comment]
No-one can tell since this question didn't explain what was meant by "this", nor what audiobooks might have to do with the issue. Especially since the issue discussion basically finished 5 years ago, I considered the question to be spam. @Amraan-Amjad may wish to study #30839 and linked material and then submit a new and comprehensible issue; or not.
