### ISSUE TITLE
upload_date kicking out "(NA)" ... script saying it's an issue with uploader_id ... playlists no longer work either.

### ISSUE THREAD

**Issue by ApparentlyNot** [ytdl-org/youtube-dl#13930]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.13*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.13**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

So the issue;

The script worked fine until a few days ago, now it will return an _(NA)_ rather than the **upload_date**, even though it says it's an error with the **uploader_id** argument.

So the example below (it's a random vid! Don't judge me!) will now be named;
**_[Looper] (NA) Disney Movie Sequels You Never Knew Existed.mp4_**

When previously it would have been;
**_[Looper] [16082017] Disney Movie Sequels You Never Knew Existed.mp4_**

Any ideas why suddenly the upload_date argument is suddenly causing me issues?

```
D:\yt\Script>D:\yt\Script\youtube-dl -f 22 -a list.txt --mark-watched --youtube-skip-dash-manifest --console-title --retries 10 --cookies cookies.txt -i -o "D:\yt\[%(uploader)s] (%(upload_date)s) %(title)s.%(ext)s" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '22', '-a', 'list.txt', '--mark-watched', '--youtube-skip-dash-manifest', '--console-title', '--retries', '10', '--cookies', 'cookies.txt', '-i', '-o', 'D:\\yt\\[%(uploader)s] (%(upload_date)s) %(title)s.%(ext)s', '-v']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=yFj-ak-s6CY']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.08.13
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] yFj-ak-s6CY: Downloading webpage
[youtube] yFj-ak-s6CY: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] yFj-ak-s6CY: Marking watched
[debug] Invoking downloader on 'https://r13---sn-aigllnsz.googlevideo.com/videoplayback?mm=31&requiressl=yes&ipbits=0&ms=au&signature=3684B0EEB3A1070D01F7B517A471D711549BF523.C43F78AACC86B1E592CE00FBF18DE9A1E219BC48&ratebypass=yes&source=youtube&mv=m&initcwndbps=1517500&pl=17&mn=sn-aigllnsz&dur=360.327&ei=0jmUWc72PMmNWPbZnKAJ&itag=22&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&lmt=1500911906513100&ip=194.72.129.42&mime=video%2Fmp4&key=yt6&expire=1502907955&id=o-AJRlvxmHnwHXltwYHL6imzEtYVs90xILOLjYDug2KtjW&mt=1502886277'
[download] Destination: D:\yt\[Looper] (NA) Disney Movie Sequels You Never Knew Existed.mp4
[download]   1.7% of 58.80MiB at 884.61KiB/s ETA 01:06
ERROR: Interrupted by user
...
<end of log>
```

... also, the script now doesn't recognise playlists (entire channel links eg https://www.youtube.com/channel/github/videos) as having any videos. Previously it'd count the pages then grab em all.

This is true for playlists/channels I'm half way through downloading. They now don't work (without ANY change to the script).

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by ApparentlyNot** [comment]
D:\yt\Script>D:\yt\Script\youtube-dl -f 22 -a list.txt --mark-watched --youtube-skip-dash-manifest --console-title --retries 10 --cookies cookies.txt -i -o "D:\yt\[%(uploader)s] (%(upload_date)s) %(title)s.%(ext)s" -v --dump-pages
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '22', '-a', 'list.txt', '--mark-watched', '--youtube-skip-dash-manifest', '--console-title', '--retries', '10', '--cookies', 'cookies.txt', '-i', '-o', 'D:\\yt\\[%(uploader)s] (%(upload_date)s) %(title)s.%(ext)s', '-v', '--dump-pages']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=7y1UDTtNx3w']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.08.13
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 7y1UDTtNx3w: Downloading webpage
[youtube] Dumping request to https://www.youtube.com/watch?v=7y1UDTtNx3w&gl=US&hl=en&has_verified=1&bpctr=9999999999
PCFkb2N0eXBlIGh0bWw+PGh0bWwgc3R5bGU9ImZvbnQtc2l6ZTogMTBweDtmb250LWZhbWlseTogUm9ib3RvLCBBcmlhbCwgc2Fucy1zZXJpZjsgYmFja2dyb3VuZC1jb2xvcjogI2ZhZmFmYTsiPjxoZWFkPjwhLS0gT3JpZ2luIFRya.... lots and lots

**Comment by dstftw** [comment]
Post the **FULL** output.

**Comment by ApparentlyNot** [comment]
[dump.txt](https://github.com/rg3/youtube-dl/files/1229391/dump.txt)

**Comment by ApparentlyNot** [comment]
So it can't be reproduced, any ideas on a fix? What would you try?

**Comment by ApparentlyNot** [comment]
I don't know if it's worth someone somewhere knowing, but the latest update has finally fixed this issue! Hooray!
