### ISSUE TITLE
No 4:3 formats available to download from FX Networks on videos which have them

### ISSUE THREAD

**Issue by cablebox** [ytdl-org/youtube-dl#13972]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', u'--ap-mso', u'Comcast_SSO', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE']
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'-v', u'http://www.simpsonsworld.com/video/275196995796']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.09
[debug] Python version 2.7.13 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[FXNetworks] 275196995796: Downloading webpage
[FXNetworks] 275196995796: Retrieving Media Token
[ThePlatform] UXICmlcSyjHT: Downloading SMIL data
[ThePlatform] UXICmlcSyjHT: Checking video URL
[ThePlatform] UXICmlcSyjHT: Checking video URL
[ThePlatform] UXICmlcSyjHT: Checking video URL
[ThePlatform] UXICmlcSyjHT: Checking video URL
[ThePlatform] UXICmlcSyjHT: Checking video URL
[ThePlatform] UXICmlcSyjHT: Checking video URL
[ThePlatform] UXICmlcSyjHT: Downloading JSON metadata
[info] Available formats for UXICmlcSyjHT:
format code  extension  resolution note
http-395     mp4        480x270     395k 
http-595     mp4        480x270     595k 
http-895     mp4        640x360     895k 
http-1427    mp4        1024x576   1427k 
http-1927    mp4        1280x720   1927k 
http-2627    mp4        1280x720   2627k  (best)
```
---

### Description of your *issue*, suggested solution and other information

The Simpsons on FX supports both 4:3 and 16:9 versions of some (usually earlier) episodes, however only the 16:9 versions are presented as formats which are available for download. During playback on their site in a browser, a 4:3/16:9 toggle is visible, however clicking it does not change the URL shown in the menu bar.

**Comment by Coasterghost** [comment]
It also appears that the issue stems from the fact that the links are just on the page in HTML. There are for those early episodes 4 streams. This is what it looks like the earlier episodes in the HTML code: 

  | var url_4x3 = '-link here-';
  | var url_4x3_commentary = '-link here-';
  | var url_16x9 = '-link here-';

**Comment by astrowonk** [comment]
I think the issue is the [regex that grabs the underlying link](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/fxnetworks.py) from theplatform never sees the var url_4x3 that Coasterghost notes above. 

` video_data = extract_attributes(self._search_regex(
            r'(<a.+?rel="https?://link\.theplatform\.com/s/.+?</a>)', webpage, 'video data'))`

Now one could change the regex to find the url that appears after `url_4x3` but that would break any url that doesn't have that. I also don't know what sort of ways that a user could pass a flag that tells the extractor "I want the 4x3 version;"  I only discovered youtube-dl a few weeks ago.

One day, I will try to just change the regex and compile myself and see if it actually successfully grabs the 4x3 with the `video_data` extracted from the 4x3 url.
