### ISSUE TITLE
Unable to download Wired.com's embedded videos.

### ISSUE THREAD

**Issue by antdude** [ytdl-org/youtube-dl#14146]
Example from https://www.wired.com/video/2017/07/how-a-son-made-a-chat-bot-of-his-dying-dad web page:

$ youtube-dl -v "https://www.wired.com/video/how-a-son-made-a-chat-bot-of-his-dying-dad/iframe?videoId=5963c752f24dd35cb6000010&autoplay=true&muted=0&adsDisabled=0&iu=3379/wiredcom.dart/culture"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.wired.com/video/how-a-son-made-a-chat-bot-of-his-dying-dad/iframe?videoId=5963c752f24dd35cb6000010&autoplay=true&muted=0&adsDisabled=0&iu=3379/wiredcom.dart/culture']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.02
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.9
[debug] exe versions: ffmpeg 3.2.5-1, ffprobe 3.2.5-1, rtmpdump 2.4
[debug] Proxy map: {}
[CondeNast] how-a-son-made-a-chat-bot-of-his-dying-dad: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('data-player',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/condenast.py", line 218, in _real_extract
    params = self._extract_video_params(webpage)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/condenast.py", line 135, in _extract_video_params
    'playerId': params['data-player'],
KeyError: 'data-player'
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/condenast.py", line 218, in _real_extract
    params = self._extract_video_params(webpage)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/condenast.py", line 135, in _extract_video_params
    'playerId': params['data-player'],
KeyError: 'data-player'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 447, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('data-player',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thank you in advance. :)

**Comment by remitamine** [comment]
No longer accessible.

**Comment by llacb47** [comment]
@remitamine video moved to `https://www.wired.com/video/watch/how-a-son-made-a-chat-bot-of-his-dying-dad`

**Comment by remitamine** [comment]
> @remitamine video moved to `https://www.wired.com/video/watch/how-a-son-made-a-chat-bot-of-his-dying-dad`

Supported with the latest version.
