### ISSUE TITLE
HTTP Error 403: Forbidden while downloading videos

### ISSUE THREAD

**Issue by youtube-dl-user003** [ytdl-org/youtube-dl#14288]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.15**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--verbose', u'https://www.pluralsight.com/courses/javascript-module-fundamentals']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.15
[debug] Python version 2.7.12 - Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] javascript-module-fundamentals: Downloading course JSON
[pluralsight:course] javascript-module-fundamentals: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/youtube/dev/programs/youtube-dl-2017.09.15/youtube-dl/youtube_dl/extractor/common.py", line 503, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/youtube/dev/programs/youtube-dl-2017.09.15/youtube-dl/youtube_dl/YoutubeDL.py", line 2177, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

...
<end of log>
```

### Description of your *issue*, suggested solution and other information

I was trying to download a video for my future reference, which I normally do, and in between the download process was interrupted. On command line a HTTP Error 403 was shown. Further I was asked to raise a bug request. Any help is appreciated.

Note: I have verified that I am on the latest version of youtube-dl.

**Comment by MoBattah** [comment]
You can download PluralSight videos by finding the video link in the page source. Not sure if that helps you at all.

**Comment by ggkr** [comment]
I think the issue is being caused by "I'm not a robot" mechanism. 
the behavior and error of this issue seems to be identical to when you try downloading without authentication at all (--username and --password flags)

**Comment by VarunVachis** [comment]
> I think the issue is being caused by "I'm not a robot" mechanism.
> the behavior and error of this issue seems to be identical to when you try downloading without authentication at all (--username and --password flags)
How to remove im not a robot mechanism.

**Comment by virumax** [comment]
Facing same issue for https://www.raywenderlich.com/977854-data-structures-algorithms-in-swift/lessons/4
