### ISSUE TITLE
How to get list of All udemy Courses present in my account

### ISSUE THREAD

**Issue by ilokeshk** [ytdl-org/youtube-dl#14345]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.09.24
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Hi I need to get the full list of All udemy Courses present in my account. For what I have to do ?

**Comment by hashmachine07** [comment]
You can't download all the courses in one go. Try downloading a course at one time.  
1) Use the Course URL .
2) Keep max n min flags .
3) Pass your account credentials
4) Optional: Use -V flag for diagnostics .

You can try this below cmd. It will save the course chapter wise.

 `youtube-dl --min-sleep-interval XXX --max-sleep-interval XXX --verbose --username YOUR_USERNAME --password YOUR_PASSWORD -o "c:\YouTube-dl /%(playlist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" https://site@site.com`

Please check the description [https://github.com/rg3/youtube-dl#options](url) for more options

**Comment by ilokeshk** [comment]
Yeah Got it.
Between, Consider the following scenario.
1. I have bought a Paid Udemy Course.
2. But I haven't enrolled/subscribed to that course.
3. When ever I'm trying to download that course... it is showing... below error.

ERROR: Course 9666084 is not free. You have to pay for it before you can download. Use this URL to confirm purchase: https://www.udemy.com/payment/checkout/?boId=374904&boType=course

Why this happens ? It is not getting enrolled by script.

But when I manually enrol to that course. I'm able to download it.

**Comment by ilokeshk** [comment]
Also, is there any way to download the course with captions, pdf, files attached ?

**Comment by hashmachine07** [comment]
You have to manually enroll into the courses. Without enrolling, You won't have access to it. The app just does the downloading part. Use "--all-subs" flag for all captions.

**Comment by bijukumarnarayanan** [comment]
how to use this for downloading after a specific chapter numer/name

**Comment by salytwo** [comment]
I have around 150 course in my udemy account, does this utility list the course titles as text output ?
with or without their links.

**Comment by LubosKolouch** [comment]
Looks like nobody is able to answer...

**Comment by hashmachine** [comment]
U can download the courses only 1 at a time. All videos in the course will be downloaded along with their title, serial no and in your choice of folder.
Here's a simple template
./youtube-dl.exe --verbose -o "<DESTINATION PATH>/%(playlist_index)s - %(title)s.%(ext)s" <LINK>
