### ISSUE TITLE
Site request for bibel.TV

### ISSUE THREAD

**Issue by z1atk0** [ytdl-org/youtube-dl#14361]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v "http://www.bibeltv.de/mediathek/video/sich-finden-sich-verlieren-6059/?no_cache=1&cHash=fccfbe868928ea4795ccf0e1e822a0dd"
[debug] System config: []
[debug] User config: [u'--proxy', u'', u'--rate-limit', u'12M']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.bibeltv.de/mediathek/video/sich-finden-sich-verlieren-6059/?no_cache=1&cHash=fccfbe868928ea4795ccf0e1e822a0dd']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.24
[debug] Python version 2.7.14 - Linux-4.12.11-i686-Intel-R-_Core-TM-_i3-3220_CPU_@_3.30GHz-with-slackware-14.2
[debug] exe versions: ffmpeg 2.8.12, ffprobe 2.8.12, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?no_cache=1&cHash=fccfbe868928ea4795ccf0e1e822a0dd: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?no_cache=1&cHash=fccfbe868928ea4795ccf0e1e822a0dd: Downloading webpage
[generic] ?no_cache=1&cHash=fccfbe868928ea4795ccf0e1e822a0dd: Extracting information
ERROR: Unsupported URL: http://www.bibeltv.de/mediathek/video/sich-finden-sich-verlieren-6059/?no_cache=1&cHash=fccfbe868928ea4795ccf0e1e822a0dd
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2125, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 51, column 122
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 777, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2980, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.bibeltv.de/mediathek/video/sich-finden-sich-verlieren-6059/?no_cache=1&cHash=fccfbe868928ea4795ccf0e1e822a0dd
```
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.bibeltv.de/mediathek/video/sich-finden-sich-verlieren-6059/?no_cache=1&cHash=fccfbe868928ea4795ccf0e1e822a0dd
- Single video: http://www.bibeltv.de/mediathek/video/familienbande-6014/?no_cache=1&cHash=107d64d56a46c075a29ebb6c9959e469
- Single video: http://www.bibeltv.de/mediathek/video/die-perfekte-welle-2116/?no_cache=1&cHash=2621942a550fd7bcb5f90839e9e07098

... and more at http://www.bibeltv.de/mediathek/highlights/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Site request for bibel.TV, http://www.bibeltv.de/mediathek/

**Comment by ranzeyer** [comment]
The site „https://www.bibeltv.de/mediathek“ is still not supported. I tried to download the following videos:
- https://www.bibeltv.de/mediathek/videos/der-veteran-665375
- https://www.bibeltv.de/mediathek/videos/wohltun-errettet-vom-tode-615270

Here is youtube-dl’s output:
youtube-dl -v https://www.bibeltv.de/mediathek/videos/der-veteran-665375
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bibeltv.de/mediathek/videos/der-veteran-665375']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.1.4
[debug] Proxy map: {}
[generic] der-veteran-665375: Requesting header
WARNING: Falling back on generic information extractor.
[generic] der-veteran-665375: Downloading webpage
[generic] der-veteran-665375: Extracting information
ERROR: Unsupported URL: https://www.bibeltv.de/mediathek/videos/der-veteran-665375
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\generic.py", line 3350, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.bibeltv.de/mediathek/videos/der-veteran-665375

Watching the videos on the Website works fine. I can’t see any geoblocking issue.

**Comment by Der-Moench-mit-der-Peitsche** [comment]
Since Bibel TV (https://www.bibeltv.de/mediathek) is still not supported here's another attempt: 

Two video examples:
- https://www.bibeltv.de/mediathek/videos/325870-am-abzug
- https://www.bibeltv.de/mediathek/videos/329703-sprachkurs-in-malaiisch

YouTube-DL's output:
```
D:\YouTube-DL>youtube-dl -v https://www.bibeltv.de/mediathek/videos/325870-am-abzug
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bibeltv.de/mediathek/videos/325870-am-abzug']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.01.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-90866-g48330500ef
[debug] Proxy map: {}
[generic] 325870-am-abzug: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 325870-am-abzug: Downloading webpage
[generic] 325870-am-abzug: Extracting information
ERROR: Unsupported URL: https://www.bibeltv.de/mediathek/videos/325870-am-abzug
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\extractor\generic.py", line 3467, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.bibeltv.de/mediathek/videos/325870-am-abzug
```

```
D:\YouTube-DL>youtube-dl -v https://www.bibeltv.de/mediathek/videos/329703-sprachkurs-in-malaiisch
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bibeltv.de/mediathek/videos/329703-sprachkurs-in-malaiisch']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.01.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-90866-g48330500ef
[debug] Proxy map: {}
[generic] 329703-sprachkurs-in-malaiisch: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 329703-sprachkurs-in-malaiisch: Downloading webpage
[generic] 329703-sprachkurs-in-malaiisch: Extracting information
ERROR: Unsupported URL: https://www.bibeltv.de/mediathek/videos/329703-sprachkurs-in-malaiisch
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\extractor\generic.py", line 3467, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.bibeltv.de/mediathek/videos/329703-sprachkurs-in-malaiisch
```

I can only agree with what @ranzeyer said above: 

> Watching the videos on the Website works fine. I can’t see any geoblocking issue.

Would be great if someone could make Bibel TV working! (Or at least explain what's the geo-restricted problem here...)
Thanks a lot
