### ISSUE TITLE
[twitch:vod] Make the same format code for 720 live and offline vod 

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#14478]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

I noticed that format code for live (that are recording while stream is live) and offline vods on twitch are different:
`720-0` and `720p-1` in live vod:
```
C:\Users\User>youtube-dl -F https://go.twitch.tv/videos/181353207
[twitch:vod] 181353207: Downloading vod info JSON
[twitch:vod] 181353207: Downloading vod access token
[twitch:vod] 181353207: Downloading m3u8 information
[info] Available formats for v181353207:
format code  extension  resolution note
Audio_Only   mp4        audio only    0k , mp4a.40.2
160p         mp4        284x160       0k , avc1.4D400C, mp4a.40.2
360p         mp4        640x360       0k , avc1.4D401E, mp4a.40.2
480p         mp4        852x480       0k , avc1.4D401E, mp4a.40.2
720p-0       mp4        1280x720      0k , avc1.4D401F, mp4a.40.2
720p-1       mp4        1280x720      0k , avc1.4D401F, mp4a.40.2
864p         mp4        1536x864      0k , avc1.64002A, mp4a.40.2 (best)
```
`720p` and `720p60` in offline vod:
```
C:\Users\User>youtube-dl -F https://go.twitch.tv/videos/181353207
[twitch:vod] 181353207: Downloading vod info JSON
[twitch:vod] 181353207: Downloading vod access token
[twitch:vod] 181353207: Downloading m3u8 information
[info] Available formats for v181353207:
format code  extension  resolution note
Audio_Only   mp4        audio only    0k , mp4a.40.2
160p         mp4        284x160       0k , avc1.4D400C, mp4a.40.2
360p         mp4        640x360       0k , avc1.4D401E, mp4a.40.2
480p         mp4        852x480       0k , avc1.4D401E, mp4a.40.2
720p-0       mp4        1280x720      0k , avc1.4D401F, mp4a.40.2
720p-1       mp4        1280x720      0k , avc1.4D401F, mp4a.40.2
864p         mp4        1536x864      0k , avc1.64002A, mp4a.40.2 (best)
```
Is there are reason for this?
I ask live vods to use `720p` and `720p60` instead.

Examples:
https://go.twitch.tv/videos/181353207 (live)
https://go.twitch.tv/videos/181045697 (offline)
https://go.twitch.tv/streamerhouse/videos/all

**Comment by dirkf** [comment]
Format IDs are only stable by accident. Use the format selection options to specify what sort of thing you want rather than its format ID.
