### ISSUE TITLE
[HBO] HBO extractor broken after site redesign

### ISSUE THREAD

**Issue by SeanPM5** [ytdl-org/youtube-dl#14629]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.29**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)

### Description of your *issue*, suggested solution and other information
HBO has completely redesigned their website and updated URL's etc, which had the unfortunate side effect of breaking the existing youtube-dl hbo extractor. From what I can gather they have switched from using video ID's to video paths instead. The same information as before is still accessible, just at different URL's.

Here is the video page: https://www.hbo.com/video/curb-your-enthusiasm/seasons/season-09/episodes/5-thank-you-for-your-service/videos/s9-ep-5-preview

And here is the XML file (found via View Page Source): https://www.hbo.com/services/hbo/video.xml/vpath=/content/hbodata/en/series/curb-your-enthusiasm/seasons/season-09/episodes/5-thank-you-for-your-service/videos/s9-ep-5-preview.xml

Another example:
Video Page: https://www.hbo.com/video/game-of-thrones/seasons/season-07/episodes/6-beyond-the-wall/videos/s7-ep-6-beyond-the-wall-preview

XML file: https://www.hbo.com/services/hbo/video.xml/vpath=/content/hbodata/en/series/game-of-thrones/seasons/season-07/episodes/6-beyond-the-wall/videos/s7-ep-6-beyond-the-wall-preview.xml

(Note: many of their videos now open in "popup" / lightbox type windows now, but to get these video page URL's you can simply click on "Copy Link" or "Email" in the top right of their video player.)

<hr>

Essentially to get the XML file you replace the "https://www.hbo.com/video/" portion of the URL with "https://www.hbo.com/services/hbo/video.xml/vpath=/content/hbodata/en/series/" , keep the rest of the URL the same, and then add ".xml" to the end of that.

There might be a better way to do this.

And since this is somewhat related, thought it was worth mentioning #13709 which was a request for adding subtitles support (subtitles are in these same XML files).

**Comment by tobijjah** [comment]
Your proposal works only with content from the series section. If you consider content from the movie or specials section the metadata request goes to:
- **Specials:** https://www.hbo.com/services/hbo/video.xml/vpath=/content/hbodata/en/specials/ 
-  **Movies:** https://www.hbo.com/services/hbo/video.xml/vpath=/content/hbodata/en/movies/

Movies example:
- **Movie URL:** https://www.hbo.com/video/movies/split/videos/trailer
- **Meta URL:** https://www.hbo.com/services/hbo/video.xml/vpath=/content/hbodata/en/movies/split/videos/trailer.xml

Specials example:
- **Special URL:** https://www.hbo.com/video/specials/night-of-too-many-stars/videos/trailer
- **Meta URL:** https://www.hbo.com/services/hbo/video.xml/vpath=/content/hbodata/en/specials/night-of-too-many-stars/videos/trailer.xml
