### ISSUE TITLE
Basic authentication support for SOCKS proxy

### ISSUE THREAD

**Issue by TheDcoder** [ytdl-org/youtube-dl#14637]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

I would like to see support for basic [SOCKS5](https://en.wikipedia.org/wiki/SOCKS#SOCKS5) username and password authentication because not all proxies accept unauthenticated connections 😄

**Comment by yan12125** [comment]
It's supported since long time ago. It doesn't work for you?

**Comment by TheDcoder** [comment]
Well, I don't see any options/parameters which accept credentials for proxies, I have searched for it a couple of times in README 😕

**Comment by yan12125** [comment]
How about this?
```
--proxy socks5://username:password@hostname:port/
```
Adding some notes in README is indeed necessary 👍

**Comment by TheDcoder** [comment]
I didn't know about the syntax!
```
C:\Users\TheDcoder>youtube-dl socks5://username:password@hostname:port --simulate https://www.youtube.com/watch?v=jNQXAC9IVRw
[youtube] jNQXAC9IVRw: Downloading webpage
[youtube] jNQXAC9IVRw: Downloading video info webpage
[youtube] jNQXAC9IVRw: Extracting video information
[youtube] jNQXAC9IVRw: Downloading MPD manifest

```
So I guess it works 😁, I agree, there should be notes about the syntax in the README.

**Comment by tobijjah** [comment]
It is already mentioned in the repo readme.md but not in the docstring if you call `youtube-dl --help`. 
```
--proxy URL                      Use the specified HTTP/HTTPS/SOCKS proxy.
                                 To enable experimental SOCKS proxy, specify
                                 a proper scheme. For example
                                 socks5://127.0.0.1:1080/. Pass in an empty
                                 string (--proxy "") for direct connection
```

**Comment by TheDcoder** [comment]
@tobijjah doesn't demonstrate the authentication syntax

**Comment by tobijjah** [comment]
Modification proposal?
```
--proxy URL                      Use the specified HTTP/HTTPS/SOCKS proxy.
                                 To enable experimental SOCKS proxy, specify
                                 a proper scheme. For example
                                 socks5://hostname:port/ or 
                                 socks5://username:password@hostname:port/ 
                                 for username and password authentication. 
                                 Pass in an empty string (--proxy "") for 
                                 direct connection.
```

**Comment by yan12125** [comment]
Thanks for pull requests :)

Now we need another documentation improvement - modifications in option descriptions should go to ```options.py```. Relevant sections in README.md are re-generated from options.py in each release.

I haven't check whether such a syntax works for HTTP proxies or not. If so the additional sentence should go before "To enable experimental SOCKS proxy..."

**Comment by tobijjah** [comment]
I checked it (with my vpn provider) for http as well as https and it works as it should. The first #14639 pull request modifies `options.py`. We just have to append your proposal to this pull request. Oh, the README.md is auto generated, this means I can close the second pull request.
**Proposal**
```
--proxy URL                      Use the specified HTTP/HTTPS/SOCKS proxy.
                                 To enable HTTP/HTTPS/SOCKS proxy, specify
                                 a proper scheme. For example:
                                 http://hostname:port/
                                 https://hostname:port/
                                 sock5://hostname:port/
                                 or
                                 http://username:password@hostname:port/ 
                                 https://username:password@hostname:port/ 
                                 socks5://username:password@hostname:port/ 
                                 for username and password authentication.
                                 Pass in an empty string (--proxy "") for 
                                 direct connection.
```
**Check for http/https**
```
youtube-dl -v --test  --proxy http://foo:bar@foo:bar/ https://www.youtube.com/watch?v=zDb7dAnm79I
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--test', '--proxy', 'http://foo:bar@foo:bar/', 'https://www.youtube.com/watch?v=zDb7dAnm79I']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.5.2 - Linux-4.10.0-37-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {'https': 'http://foo:bar@foo:bar/', 'http': 'http://foo:bar@foo:bar/'}
[youtube] zDb7dAnm79I: Downloading webpage
[youtube] zDb7dAnm79I: Downloading video info webpage
[youtube] zDb7dAnm79I: Extracting video information
[youtube] zDb7dAnm79I: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] CocoRosie - Fairy Paradise (Live on KEXP)-zDb7dAnm79I.mkv has already been downloaded and merged
```

**Comment by metin02oktay** [comment]
If username contain "@", how can ı do that? My school proxy's username is email address that is contain "@"

**Comment by Crystal-RainSlide** [comment]
> 
> 
> If username contain "@", how can ı do that? My school proxy's username is email address that is contain "@"

Try replace the "@" in the username with `%40`, which is the URL encoded version of "@", `encodeURIComponent("@")` in JavaScript.

See [`encodeURIComponent()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) on MDN.
