### ISSUE TITLE
Prefer ffmpeg HLS decoder for v.redd.it

### ISSUE THREAD

**Issue by stewartadam** [ytdl-org/youtube-dl#14748]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Site v.reddit.com should prefer ffmpeg HLS downloader instead of native. Using the native downloader results in some video corruption and artifacting, e.g. visible within the first few seconds of this source: `youtube-dl https://v.redd.it/poqkxthgcpxz`

**Comment by romellem** [comment]
Just a note for anyone wonder how to use the **ffmpeg HLS downloader**, add the `--hls-prefer-ffmpeg` flag to your command.

So using OP's sample URL, to get rid of the video corruption / artifacts, you'd run

    youtube-dl --hls-prefer-ffmpeg https://v.redd.it/poqkxthgcpxz

**Comment by michealespinola** [comment]
The example format of...

    youtube-dl --hls-prefer-ffmpeg https://v.redd.it/poqkxthgcpxz

...did not work for me.  What this caused instead is that ffmpeg closed the video stream at he point of of corruption - ignoring the remainder of the video.   Example video:

    https://www.reddit.com/r/gifs/comments/bml3yp/just_a_clean_and_crisp_punch_to_the_noggin/

**Comment by alext69** [comment]
--hls-prefer-ffmpeg give a worse result in [my case](https://github.com/ytdl-org/youtube-dl/issues/22542), which I had glitches.
youtube-dl --hls-prefer-ffmpeg https://v.redd.it/5k899ezasdp31
The result is a completely broken video. The only way to download this video, without glitches, is through ripsave.com

**Comment by kyleratti** [comment]
@alext69 @FichteFoll I can also confirm that `--hls-prefer-ffmpeg` causes the audio desync/audio-only after X seconds issue.

Seems you have to choose between video artifacts every 6 seconds or broken video + desynced audio.

**Comment by JamesTheAwesomeDude** [comment]
This is definitely still present on

* youtube-dl version `2020.05.29`
* Python version `3.8.2` (CPython)
* Fedora 32
* ffmpeg `4.2.3-static`, ffprobe `4.2.3-static`

[stderr](https://github.com/ytdl-org/youtube-dl/files/4698825/err.log)
[stdout](https://github.com/ytdl-org/youtube-dl/files/4698826/out.log)

**Comment by kyleratti** [comment]
Thank you @dstftw and @tsia!
