### ISSUE TITLE
Cant find Pokemon Special Episodes link?

### ISSUE THREAD

**Issue by noctis90210** [ytdl-org/youtube-dl#14751]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other
---
I just have some question about downloading pokemon episodes on pokemon.com
I can download regular episodes, but i cant download the special episodes (origins & generations episodes)
Unlike regular episodes that has its own webpage, these special episodes directly opens a stream/video window on the episode list.
How can i find the specific webpage for these episodes so we can download it?
thanks and have a nice day...

**Comment by yan12125** [comment]
Not sure what's a "special episode". Could you give steps for how to get to a special episode? Better with screenshots.
