### ISSUE TITLE
Requested format not available — Pluralsight

### ISSUE THREAD

**Issue by omareg94** [ytdl-org/youtube-dl#14814]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'C:\\Users\\AAAA\\Desktop\\cookies.txt', '-o', 'C:\\Users\\AAAA\\Desktop\\downloaded\\%(playlist)s\\%(playlist_index)s - %(chapter_number)s. %(chapter)s - %(title)s.%(ext)s', '--min-sleep-interval', '31', '--max-sleep-interval', '32', 'https://app.pluralsight.com/library/courses/realistic-interiors-3ds-max-marvelous-designer-2072/', '--playlist-start', '1', '-f', 'mp4-medium-cachefly/mp4-medium-edgecast', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-82966-g6993bb4
[debug] Proxy map: {}
[pluralsight:course] realistic-interiors-3ds-max-marvelous-designer-2072: Downloading course JSON
[download] Downloading playlist: Modeling Realistic Interiors in 3ds Max and Marvelous Designer
[pluralsight:course] playlist Modeling Realistic Interiors in 3ds Max and Marvelous Designer: Collected 34 video ids (downloading 34 of them)
[download] Downloading video 1 of 34
[pluralsight] realistic-interiors-3ds-max-marvelous-designer-2072-m1-0: Downloading course JSON
[pluralsight] realistic-interiors-3ds-max-marvelous-designer-2072-m1-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] realistic-interiors-3ds-max-marvelous-designer-2072-m1-0: Waiting for 3 seconds to avoid throttling
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 795, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 992, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 887, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 849, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 1612, in process_video_result
youtube_dl.utils.ExtractorError: requested format not available
...
<end of log>
```
---
### When I try to download specific format `mp4-medium-cachefly/mp4-medium-edgecast` it tells `ERROR: requested format not available`. I'm sure that the format is available because the `--list-formats` outputs:
```
[info] Available formats for realistic-interiors-3ds-max-marvelous-designer-2072-m1-1-hq:
format code                    extension  resolution note
mp4-low-edgecast               mp4        640x480
mp4-low-cachefly               mp4        640x480
mp4-medium-edgecast            mp4        848x640
mp4-medium-cachefly            mp4        848x640
webm-high-cachefly             webm       1024x768
webm-high-edgecast             webm       1024x768
mp4-high-cachefly              mp4        1024x768
mp4-high-edgecast              mp4        1024x768
webm-high-widescreen-cachefly  webm       1280x720
webm-high-widescreen-edgecast  webm       1280x720
mp4-high-widescreen-edgecast   mp4        1280x720
mp4-high-widescreen-cachefly   mp4        1280x720   (best)
```
Also I observed something that may be the result of that. That when I input `-f mp4-medium` it successfully get to `[pluralsight] realistic-interiors-3ds-max-marvelous-designer-2072-m1-0: Downloading mp4-medium viewclip JSON` but it tills the format isn't available. But when I input `-f mp4-medium-cachefly` (which is listed in format list), it's mistaken to get to `[pluralsight] realistic-interiors-3ds-max-marvelous-designer-2072-m1-0: Downloading mp4-high-widescreen viewclip JSON` only without going to download the medium viewclip JSON.

**Comment by ohhai** [comment]
I have something similar, maybe.
Downloading from Vimeo with format specification 'bestaudio[abr<=200]' and getting "ERROR: requested format not available"

However the formats list contains two matching options:

```
format code                                        extension  resolution note
dash-akfire_interconnect_quic_sep-audio-921291431  m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-fastly_skyfire_sep-audio-921291431            m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-akfire_interconnect_quic_sep-audio-921291473  m4a        audio only DASH audio  256k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-fastly_skyfire_sep-audio-921291473            m4a        audio only DASH audio  256k , m4a_dash container, mp4a.40.2 (48000Hz)
```

**Comment by dirkf** [comment]
If this error persists (that is, if anyone can download any video from Pluralsight at all). please open a new issue.
