### ISSUE TITLE
[vhx] Add support for VHX.tv

### ISSUE THREAD

**Issue by deadman36g** [ytdl-org/youtube-dl#14835]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl --verbose https://troma.vhx.tv/witchcraft-666/videos/witchcraft-666
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://troma.vhx.tv/witchcraft-666/videos/witchcraft-666']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.15
[debug] Python version 2.7.10 - Darwin-17.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4
[debug] Proxy map: {}
[generic] witchcraft-666: Requesting header
WARNING: Falling back on generic information extractor.
[generic] witchcraft-666: Downloading webpage
[generic] witchcraft-666: Extracting information
ERROR: Unsupported URL: https://troma.vhx.tv/witchcraft-666/videos/witchcraft-666
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2170, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3075, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://troma.vhx.tv/witchcraft-666/videos/witchcraft-666
```

This site does require a paid subscription which I have and can use to help solve

**Comment by Karmak23** [comment]
Hello. I think the issue should be re-labelled VHX.tv (not troma), because I've got one which is https://whynothome.vhx.tv/ for a documentary, and VHX.tv seems to be a generic hoster for VOD.

**Comment by 07416** [comment]
@deadman36g Did you provide account credentials for the maintainers? vhx.tv isn't on [the list of supported websites](https://rg3.github.io/youtube-dl/supportedsites.html).

**Comment by deadman36g** [comment]
I no longer have an account to use, but I believe at the time I used the --cookies option

**Comment by trapexit** [comment]
I have account credentials if needed for troma.vhx.tv

**Comment by thibaultmol** [comment]
Dropout tv seems to work and they use Vimeo OTT (vhx.tv  https://vimeo.com/ott/home) as well. So downloading single videos probably works. (downloading an entire show at once probably won't though)

**Comment by derekantrican** [comment]
Found these steps on reddit that worked for me: https://www.reddit.com/r/Pirate/comments/fgux6o/comment/fzo2c8z/?utm_source=share&utm_medium=web2x&context=3 . Reproducing here in case the comment is removed:

> I've been figuring this out all day only to find that everything else I wanted to download besides Werq The World S1 uses Widevine DRM instead, which is pretty much uncrackable. But for anything like WTW S1 and whatever else might still use Vimeo OTT:
>
> I did this on Firefox but I assume anything else will be the same
>
> Play video and then right click, inspect element.
>
> Go to the "Network" tab and refresh the page. Under the "embed.vhx.tv" domain, find the long "subdocument" file with user tokens. Open in a new tab.
>
> Repeat the first step.
>
> Go to the "Network tab" and refresh the page. Under the "player.vimeo.com" domain, find the long "json" file with user tokens. Open in a new tab.
>
> CTRL + F, "1080". Cycle until you find a highlight that comes with a link a few lines below. Open the link.
>
> The video is now playing in a non-Vimeo player. You can now right click to download through your browser or copy and paste into JDownloader.
>
> If you need extra help then I can send you the video I recorded to remind myself, just lemme know.
>
> Also, if you know a good 1080p download source for every season's Untucked then please dm me, cause that's mainly what I went on this whole quest for and I can't download them cause of Widevine.
> 
> Edit: https://youtu.be/tBOLzcMqcZ4

I was able to follow those steps to download from dropout.tv (#19146)
