### ISSUE TITLE
"This video is unavailable" when attempting to download purchased movie.

### ISSUE THREAD

**Issue by RalphORama** [ytdl-org/youtube-dl#14896]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--cookies', 'cookies.txt', 'https://www.youtube.com/watch?v=vCCqOTExzNA']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.12.02
[debug] Python version 3.6.3 - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}
[youtube] vCCqOTExzNA: Downloading webpage
[youtube] vCCqOTExzNA: Downloading video info webpage
[youtube] vCCqOTExzNA: Extracting video information
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "l:\program files\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "l:\program files\python36\lib\site-packages\youtube_dl\extractor\common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "l:\program files\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1960, in _real_extract
    raise ExtractorError(unavailable_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.
```

---

### Description of your *issue*, suggested solution and other information

Basically, I'm trying to download a movie I purchased on YouTube. I've read some other issues and seen that downloading a purchased movie may or may not work, but I've encountered different errors than the ones described in those tickets.

I've encountered several errors in my various attempts: 

1. `youtube-dl -u <email> -p <pass> -2 <123456>`: Got `WARNING: Unable to submit TFA code: HTTP Error 500: Internal Server Error`,
    - Seen in #13050.
2. `youtube-dl -u <email> -p <app password>`: Got `WARNING: Unable to login: Invalid password`
    - Seen in #5053.
3. `youtube-dl --cookies "cookies.txt"`: My current issue.

I used the cookies.txt plugin for Chrome to export my cookies. Whenever I try to download the video this way, I get the error `ERROR: This video is unavailable.` This is similar to #13075 and #14459. However, I've downloaded YouTube Red videos this way before, so I'm not sure why this would be an problem.

If there's a solution I'm missing or a way I can help find one, I'd love to know.

- - - - -

## Update

I took a shot at disabling 2FA and attempted `youtube-dl -u <email> -p <pass>`. While youtube-dl successfully logged in. When I first attempted the command, youtube-dl downloaded the trailer for the movie. When I ran the command again, I once again got the error `This video is unavailable.`

The output for the first time I ran the command:

```
L:\Users\Ralph\Videos>youtube-dl -u "PRIVATE" --verbose "https://www.youtube.com/watch?v=vCCqOTExzNA"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '--verbose', 'https://www.youtube.com/watch?v=vCCqOTExzNA']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.12.02
[debug] Python version 3.6.3 - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] vCCqOTExzNA: Downloading webpage
[youtube] EoUmZy-KOtQ: Downloading webpage
[youtube] EoUmZy-KOtQ: Downloading video info webpage
[youtube] EoUmZy-KOtQ: Extracting video information
[youtube] EoUmZy-KOtQ: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r5---sn-p5qlsns6.googlevideo.com/videoplayback?id=128526672f8a3ad4&itag=217&source=youtube&requiressl=yes&initcwn
dbps=1601250&ei=pZgjWvrwMIOu8gTUwLfwBA&pl=26&ms=au&gcr=us&mv=m&mn=sn-p5qlsns6&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=85480524&lmt=1465092054475
921&dur=85.168&signature=2DB45296C15D19244BA728A74786224CD9C656E7.94DB28F9FDEC65D766365BD33D6CD816059FEE92&key=dg_yt0&mt=1512282213&ip=<MY.IP.ADD.RESS>&ipbits=0&expire=1512303877&sparams=ip,ipbits,expire,id,itag,source,requiressl,initcwndbps,ei,pl,ms,gcr,mv,mn,mm,ratebypass,mime,gir,clen
,lmt,dur'
[download] Destination: Shredderman Rules! - Trailer-EoUmZy-KOtQ.f217.mp4
[download]   9.8% of 81.52MiB at  4.22MiB/s ETA 00:17
ERROR: Interrupted by user
```

The output for the second time I ran the command:

```
L:\Users\Ralph\Videos>youtube-dl -u "PRIVATE" --verbose "https://www.youtube.com/watch?v=vCCqOTExzNA"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '--verbose', 'https://www.youtube.com/watch?v=vCCqOTExzNA']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.12.02
[debug] Python version 3.6.3 - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] vCCqOTExzNA: Downloading webpage
[youtube] vCCqOTExzNA: Downloading video info webpage
[youtube] vCCqOTExzNA: Extracting video information
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "l:\program files\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "l:\program files\python36\lib\site-packages\youtube_dl\extractor\common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "l:\program files\python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1960, in _real_extract
    raise ExtractorError(unavailable_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.
```

**Comment by hf1985** [comment]
I have the same problem. This is my verbose:

C:\WINDOWS\system32>youtube-dl -v https://www.youtube.com/watch?v=AxU-aohdnf0
[debug] System config: []
[debug] User config: ['--netrc', '--cookies', 'C:/Users/hf198/Downloads/cookies.txt', '-o', 'D:/Video/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=AxU-aohdnf0']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.12.02
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] AxU-aohdnf0: Downloading webpage
[youtube] AxU-aohdnf0: Downloading video info webpage
[youtube] AxU-aohdnf0: Extracting video information
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcuf0d0kb\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcuf0d0kb\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcuf0d0kb\build\youtube_dl\extractor\youtube.py", line 1960, in _real_extract
youtube_dl.utils.ExtractorError: This video is unavailable.
