### ISSUE TITLE
Can't download the video from mpd url (Corus)

### ISSUE THREAD

**Issue by pauloup** [ytdl-org/youtube-dl#14910]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

**youtube-dl with original URL:** 
```
youtube-dl -F -v "https://www.globaltv.com/canadaswalkoffame/video/full-episodes/beyond-famous-canadas-walk-of-fame/video.html?v=1108595267862"
[debug] System config: []
[debug] User config: [u'--prefer-ffmpeg', u'--ignore-errors', u'--write-sub']
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'-v', u'https://www.globaltv.com/canadaswalkoffame/video/full-episodes/beyond-famous-canadas-walk-of-fame/video.html?v=1108595267862']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.02
[debug] Python version 2.7.14 - Linux-4.13.0-17-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: avconv 3.3.4-2, avprobe 3.3.4-2, ffmpeg 3.3.4-2, ffprobe 3.3.4-2, rtmpdump 2.4
[debug] Proxy map: {}
[Corus] 1108595267862: Downloading JSON metadata
[Corus] 1108595267862: Downloading SMIL data for HLSAdobeAccessDRM
[Corus] 1108595267862: Downloading m3u8 information
[Corus] 1108595267862: Downloading SMIL data for DesktopHLS Default
[Corus] 1108595267862: Downloading m3u8 information
[Corus] 1108595267862: Downloading SMIL data for MP4 MBR
[Corus] 1108595267862: Downloading m3u8 information
[Corus] 1108595267862: Downloading SMIL data for RenditionWithDRM
[Corus] 1108595267862: Downloading m3u8 information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/corus.py", line 95, in _real_extract
    }, feed_info['account_id'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 362, in _extract_feed_info
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1067, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**youtube-dl with MPD URL:**
```
youtube-dl -F -v "https://globaltvvideo.corusdigitaldev.com/globaltv/content/vod/Shaw_-_GlobalTV/471/855/1108595267862/1512315457_drm_a6cee7d9-b1ae-45e5-9b47-3199e2528336.ism/.mpd"
[debug] System config: []
[debug] User config: [u'--prefer-ffmpeg', u'--ignore-errors', u'--write-sub']
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'-v', u'https://globaltvvideo.corusdigitaldev.com/globaltv/content/vod/Shaw_-_GlobalTV/471/855/1108595267862/1512315457_drm_a6cee7d9-b1ae-45e5-9b47-3199e2528336.ism/.mpd']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.02
[debug] Python version 2.7.14 - Linux-4.13.0-17-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: avconv 3.3.4-2, avprobe 3.3.4-2, ffmpeg 3.3.4-2, ffprobe 3.3.4-2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] .mpd: Requesting header
WARNING: Falling back on generic information extractor.
[generic] .mpd: Downloading webpage
[generic] .mpd: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2201, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1067, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

I'm trying to download the video on this page (restricted to Canada, I'm using VPN):
https://www.globaltv.com/canadaswalkoffame/video/full-episodes/beyond-famous-canadas-walk-of-fame/video.html?v=1108595267862

With Firefox I got an url with .mpd:
https://globaltvvideo.corusdigitaldev.com/globaltv/content/vod/Shaw_-_GlobalTV/471/855/1108595267862/1512315457_drm_a6cee7d9-b1ae-45e5-9b47-3199e2528336.ism/.mpd

I got the mpd file with this content:
https://pastebin.com/C5V1dhma

I'd like to get the 540p video file. I tried with the urls I got, but couldn't get any.

Can anyone help with this?

**Comment by remitamine** [comment]
youtube-dl does not support DRM protected videos.

**Comment by pauloup** [comment]
@remitamine Sorry, I just thought I had a quite similar issue to #13482, also a DRM protected video and supported (and solved indeed).

**Comment by remitamine** [comment]
no the manifest in the other issue does not contain the `ContentProtection` element(not DRM protected).

**Comment by pauloup** [comment]
It's not what Firefox presents me when I visit the site. The actual video is 404 now, but every other video in the site displays a DRM message: https://imgur.com/a/ZgepK 

But I see what you mean, you're right about the manifest. Maybe they changed the protection since then, including just now the ContentProtection element. Thank you a lot for your help in this issue!
