### ISSUE TITLE
pluralsight error

### ISSUE THREAD

**Issue by jaan143** [ytdl-org/youtube-dl#14920]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.02**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.12.02
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information
i am getting error in some pluralsight courses but these are i can watch in browser but when trying to download then i am getting error and it happens mostly new courses here is details

PS C:\Users\hams> youtube-dl --verbose -o 'D:\contents\New folder/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s'
https://app.pluralsight.com/library/courses/migrating-applications-angularjs-angular --sleep-interval 90 --limit-rate 25
0k --playlist-start 3 --username **** --password ****
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-o', u'D:\\contents\\New folder/%(playlist)s/%(playlist_index)s - %(title)s.
%(ext)s', u'https://app.pluralsight.com/library/courses/migrating-applications-angularjs-angular', u'--sleep-interval',
u'90', u'--limit-rate', u'250k', u'--playlist-start', u'3', u'--username', u'PRIVATE', u'--password', u'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.12.02
[debug] Python version 2.7.12 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] migrating-applications-angularjs-angular: Downloading course JSON
[download] Downloading playlist: Migrating Applications from AngularJS to Angular
[pluralsight:course] playlist Migrating Applications from AngularJS to Angular: Collected 64 video ids (downloading 62 o
f them)
[download] Downloading video 1 of 62
[pluralsight] Downloading login page
[pluralsight] Logging in as *****
[pluralsight] 13ef3bdf-c00a-4bfe-a7c1-50c28afec411-1: Downloading course JSON
[pluralsight] 13ef3bdf-c00a-4bfe-a7c1-50c28afec411-1: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 13ef3bdf-c00a-4bfe-a7c1-50c28afec411-1: Waiting for 2 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'http://vid5.pluralsight.com/expiretime=1512613925/ba69913de27867404e949037a7b19175/clip
s/resolution/768783db-1a36-4349-8401-aba01cf0b5a8/mp4/1280x720.mp4'
[download] Sleeping 90 seconds...
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1892, in process_info
    success = dl(filename, info_dict)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1831, in dl
    return fd.download(name, info)
  File "c:\python27\lib\site-packages\youtube_dl\downloader\common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "c:\python27\lib\site-packages\youtube_dl\downloader\http.py", line 286, in real_download
    establish_connection()
  File "c:\python27\lib\site-packages\youtube_dl\downloader\http.py", line 74, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2195, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

PS C:\Users\hams>

**Comment by Druopel** [comment]
Been getting the same HTTP Error 404 last few days, was on the odd title last week this week seems to be on nearly all titles

**Comment by mstickler** [comment]
Seems to be random at times, so it might be difficult to reproduce. I've had courses where "just waiting" and trying again later solved the issue.

**Comment by Anil86** [comment]
Not all videos of the course are downloaded. For videos which are not downloaded have an error: `ERROR: unable to download video data: HTTP Error 404: Not Found`. 
Youtube-dl version: 2017.12.10.0
[Pluralsight course](https://app.pluralsight.com/library/courses/dealing-with-new-company-culture)

**Comment by mstickler** [comment]
@Druopel @Anil86 

It seems to be an issue with (some of the servers) hosting the video files. Forcing a video format with -f "<video format>" and selecting one from the list below, should help until a new version is available.

#1280x720
mp4-high-widescreen-edgecast-0
mp4-high-widescreen-cachefly-0
mp4-high-widescreen-cachefly-1
mp4-high-widescreen-edgecast-1

# 1024x768
mp4-high-edgecast-0
mp4-high-cachefly-0
mp4-high-cachefly-1
mp4-high-edgecast-1

Works for me.

**Comment by jaan143** [comment]
@mstickler  bro can you write here exact command of video format plz

**Comment by mstickler** [comment]
Using the command from above it would result in:

Command: youtube-dl **-f "mp4-high-widescreen-edgecast-0"** --verbose --username **** --password **** --sleep-interval 120 --ignore-errors -o "%(autonumber)01d. %(title)s.%(ext)s" "https://app.pluralsight.com/library/courses/dealing-with-new-company-culture"

If mp4-high-widescreen-edgecast-0 doesn't work, try mp4-high-widescreen-cachefly-0 and so on.

**Comment by dirkf** [comment]
If this issue persists, it's likely to be related to #29234.
