### ISSUE TITLE
twitter: Non-monotonous DTS in output stream 0:0; previous: 2612 61, current: 258258; changing to 261262. This may result in incorrect timestamps  in the output file.

### ISSUE THREAD

**Issue by RingoTheDog** [ytdl-org/youtube-dl#14934]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

`youtube-dl.py -v "https://twitter.com/BellatorMMA/status/937079503297290240"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://twitter.com/BellatorMMA/status/9370
79503297290240']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.12.02
[debug] Python version 2.7.6 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-89409-g4678339e74, rtmpdump 2.4
[debug] Proxy map: {}
[twitter] 937079503297290240: Downloading webpage
[twitter:card] 937079503297290240: Downloading webpage
[twitter:card] 937079503297290240: Downloading m3u8 information
[twitter:card] 937079503297290240: Downloading mobile webpage
[twitter:card] 937079503297290240: Downloading main script
[twitter:card] 937079503297290240: Downloading mobile API data
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://video.twimg.com/amplify_video/937077800
443379714/pl/1280x720/H3wA2u6M9oqeoSJl.m3u8'
[download] Destination: Bellator MMA - Knockout of the year candidate We agree.
Watch last night's show stopping @DreamkillerMT spinning elbow from all angles!
-937079503297290240.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "Accept-Charse
t: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0
 (Chrome)
" -i "https://video.twimg.com/amplify_video/937077800443379714/pl/1280x720/H3wA2
u6M9oqeoSJl.m3u8" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:Bellator MMA - Kno
ckout of the year candidate We agree. Watch last night's show stopping @Dreamkil
lerMT spinning elbow from all angles! -937079503297290240.mp4.part"
ffmpeg version N-89409-g4678339e74 Copyright (c) 2000-2017 the FFmpeg developers

  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --e
nable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libblur
ay --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopu
s --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --ena
ble-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-lib
x264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-z
lib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-c
uvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-l
ibmfx
  libavutil      56.  5.100 / 56.  5.100
  libavcodec     58.  6.103 / 58.  6.103
  libavformat    58.  2.103 / 58.  2.103
  libavdevice    58.  0.100 / 58.  0.100
  libavfilter     7.  7.100 /  7.  7.100
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/0/3000/1280x720/8PpRchykihXJj3AS.ts', offse
t 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/0/3000/1280x720/8PpRchykihXJj3AS.ts' for reading
[h264 @ 00000000035a55a0] Reinit context to 1280x720, pix_fmt: yuv420p
Input #0, hls,applehttp, from 'https://video.twimg.com/amplify_video/93707780044
3379714/pl/1280x720/H3wA2u6M9oqeoSJl.m3u8':
  Duration: 00:00:52.62, start: 0.066733, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High), 1 reference frame ([27][0][0][0] / 0x001B),
 yuv420p(left), 1280x720, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, flt
p
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Bellator MMA - Knockout of the year candidate We agree.
 Watch last night's show stopping @DreamkillerMT spinning elbow from all angles!
 -937079503297290240.mp4.part':
  Metadata:
    encoder         : Lavf58.2.103
    Stream #0:0: Video: h264 (High), 1 reference frame (avc1 / 0x31637661), yuv4
20p(left), 1280x720 (0x0), q=2-31, 29.97 fps, 29.97 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/3000/6000/1280x720/wWgYcmKCzE5KDP8x.ts', of
fset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/3000/6000/1280x720/wWgYcmKCzE5KDP8x.ts' for reading
frame=   90 fps=0.0 q=-1.0 size=     512kB time=00:00:02.98 bitrate=1404.5kbits/
[mp4 @ 00000000037b00a0] Non-monotonous DTS in output stream 0:0; previous: 2612
61, current: 258258; changing to 261262. This may result in incorrect timestamps
 in the output file.
[mp4 @ 00000000037b00a0] Non-monotonous DTS in output stream 0:0; previous: 2612
62, current: 261261; changing to 261263. This may result in incorrect timestamps
 in the output file.
[mp4 @ 00000000037b00a0] Non-monotonous DTS in output stream 0:1; previous: 1433
60, current: 141181; changing to 143361. This may result in incorrect timestamps
 in the output file.
[mp4 @ 00000000037b00a0] Non-monotonous DTS in output stream 0:1; previous: 1433
61, current: 142205; changing to 143362. This may result in incorrect timestamps
 in the output file.
[mp4 @ 00000000037b00a0] Non-monotonous DTS in output stream 0:1; previous: 1433
62, current: 143229; changing to 143363. This may result in incorrect timestamps
 in the output file.
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/6000/9000/1280x720/2fOUB53JZKBn278t.ts', of
fset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/6000/9000/1280x720/2fOUB53JZKBn278t.ts' for reading
frame=  180 fps=112 q=-1.0 size=    1280kB time=00:00:05.92 bitrate=1768.9kbits/
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/9000/12000/1280x720/q36sD0rUN-gtIxoW.ts', o
ffset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/9000/12000/1280x720/q36sD0rUN-gtIxoW.ts' for reading
frame=  270 fps=105 q=-1.0 size=    2048kB time=00:00:08.91 bitrate=1882.0kbits/
frame=  350 fps=113 q=-1.0 size=    2816kB time=00:00:11.51 bitrate=2004.0kbits/
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/12000/15000/1280x720/f_JAXcDIZvQN0S3w.ts',
offset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/12000/15000/1280x720/f_JAXcDIZvQN0S3w.ts' for reading
frame=  364 fps=101 q=-1.0 size=    2816kB time=00:00:11.97 bitrate=1925.8kbits/
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/15000/18000/1280x720/AOv6Nb-J5_RN6yHm.ts',
offset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/15000/18000/1280x720/AOv6Nb-J5_RN6yHm.ts' for reading
frame=  450 fps=102 q=-1.0 size=    3584kB time=00:00:14.93 bitrate=1966.5kbits/
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/18000/21000/1280x720/3oatyzZETSnVyQWj.ts',
offset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/18000/21000/1280x720/3oatyzZETSnVyQWj.ts' for reading
frame=  540 fps=101 q=-1.0 size=    4352kB time=00:00:17.91 bitrate=1989.8kbits/
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/21000/24000/1280x720/C1C56riMicvdQOlx.ts',
offset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/21000/24000/1280x720/C1C56riMicvdQOlx.ts' for reading
frame=  630 fps=100 q=-1.0 size=    5120kB time=00:00:20.92 bitrate=2004.4kbits/
frame=  678 fps= 99 q=-1.0 size=    5376kB time=00:00:22.45 bitrate=1961.2kbits/
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/24000/27000/1280x720/a1ZulDysnwa-2wtj.ts',
offset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/24000/27000/1280x720/a1ZulDysnwa-2wtj.ts' for reading
frame=  720 fps= 94 q=-1.0 size=    5632kB time=00:00:23.91 bitrate=1929.5kbits/
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/27000/30000/1280x720/IzxerIOjLSME9w8d.ts',
offset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/27000/30000/1280x720/IzxerIOjLSME9w8d.ts' for reading
frame=  810 fps= 96 q=-1.0 size=    6400kB time=00:00:26.91 bitrate=1947.6kbits/
frame=  852 fps= 95 q=-1.0 size=    6656kB time=00:00:28.26 bitrate=1929.3kbits/
frame=  892 fps= 94 q=-1.0 size=    6912kB time=00:00:29.59 bitrate=1913.2kbits/
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/30000/33000/1280x720/42IoThuOrvDM0hpZ.ts',
offset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/30000/33000/1280x720/42IoThuOrvDM0hpZ.ts' for reading
frame=  901 fps= 90 q=-1.0 size=    7168kB time=00:00:29.92 bitrate=1962.1kbits/
frame=  933 fps= 89 q=-1.0 size=    7424kB time=00:00:30.96 bitrate=1964.1kbits/
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/33000/36000/1280x720/gTYRGbvMrmbcqMkS.ts',
offset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/33000/36000/1280x720/gTYRGbvMrmbcqMkS.ts' for reading
frame=  990 fps= 86 q=-1.0 size=    7936kB time=00:00:32.91 bitrate=1975.2kbits/
frame= 1060 fps= 88 q=-1.0 size=    8448kB time=00:00:35.20 bitrate=1966.0kbits/
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/36000/39000/1280x720/WsAwETYLWar5JGAE.ts',
offset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/36000/39000/1280x720/WsAwETYLWar5JGAE.ts' for reading
frame= 1079 fps= 86 q=-1.0 size=    8448kB time=00:00:35.92 bitrate=1926.5kbits/
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/39000/42000/1280x720/mHKlz3PaLXtV3uzO.ts',
offset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/39000/42000/1280x720/mHKlz3PaLXtV3uzO.ts' for reading
frame= 1169 fps= 87 q=-1.0 size=    8960kB time=00:00:38.93 bitrate=1885.4kbits/
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/42000/45000/1280x720/E0CMnANq7Atb_DbV.ts',
offset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/42000/45000/1280x720/E0CMnANq7Atb_DbV.ts' for reading
frame= 1259 fps= 88 q=-1.0 size=    9728kB time=00:00:41.91 bitrate=1901.2kbits/
frame= 1295 fps= 83 q=-1.0 size=    9984kB time=00:00:43.04 bitrate=1900.2kbits/
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/45000/48000/1280x720/bzYJ2YGPFpqz_htB.ts',
offset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/45000/48000/1280x720/bzYJ2YGPFpqz_htB.ts' for reading
frame= 1349 fps= 82 q=-1.0 size=   10496kB time=00:00:44.92 bitrate=1913.9kbits/
frame= 1391 fps= 82 q=-1.0 size=   10752kB time=00:00:46.24 bitrate=1904.6kbits/
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/48000/51000/1280x720/p4QTFoqa574egHaO.ts',
offset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/48000/51000/1280x720/p4QTFoqa574egHaO.ts' for reading
frame= 1439 fps= 81 q=-1.0 size=   11008kB time=00:00:47.91 bitrate=1882.2kbits/
frame= 1490 fps= 78 q=-1.0 size=   11520kB time=00:00:49.54 bitrate=1904.6kbits/
[hls,applehttp @ 00000000004616e0] HLS request for url 'https://video.twimg.com/
amplify_video/937077800443379714/vid/51000/52619/1280x720/wHaH-TN4jsx7vBCm.ts',
offset 0, playlist 0
[hls,applehttp @ 00000000004616e0] Opening 'https://video.twimg.com/amplify_vide
o/937077800443379714/vid/51000/52619/1280x720/wHaH-TN4jsx7vBCm.ts' for reading
frame= 1529 fps= 78 q=-1.0 size=   11520kB time=00:00:50.91 bitrate=1853.3kbits/
No more output streams to write to, finishing.
frame= 1577 fps= 80 q=-1.0 Lsize=   11704kB time=00:00:52.54 bitrate=1824.9kbits
/s speed=2.67x
video:10823kB audio:826kB subtitle:0kB other streams:0kB global headers:0kB muxi
ng overhead: 0.480061%
Input file #0 (https://video.twimg.com/amplify_video/937077800443379714/pl/1280x
720/H3wA2u6M9oqeoSJl.m3u8):
  Input stream #0:0 (video): 1577 packets read (11082484 bytes);
  Input stream #0:1 (audio): 2467 packets read (862841 bytes);
  Total: 4044 packets (11945325 bytes) demuxed
Output file #0 (file:Bellator MMA - Knockout of the year candidate We agree. Wat
ch last night's show stopping @DreamkillerMT spinning elbow from all angles! -93
7079503297290240.mp4.part):
  Output stream #0:0 (video): 1577 packets muxed (11082484 bytes);
  Output stream #0:1 (audio): 2467 packets muxed (845572 bytes);
  Total: 4044 packets (11928056 bytes) muxed
[ffmpeg] Downloaded 11985318 bytes
[download] 100% of 11.43MiB`

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://twitter.com/BellatorMMA/status/937079503297290240

---

### Description of your *issue*, suggested solution and other information

Similar issue was disccussed here: 
https://github.com/rg3/youtube-dl/issues/10719
...and was said to be fixed in FFMPEG 3.2

I have FFMPEG 3.4 and am seeing similar issues with twitter video.

The downloaded file plays correctly but I believe there is something incorrect with the time base that is being written, as if I try to do a post download transcode with FFMPEG the result is an audio drop at the point that of the "Non-Monotonous DTS" errors.  

I realize this is more of an FFMPEG/59.94 tbc vs 29.97 fps issue...but if anyone has ideas idea on how to address these audio drop outs/timing issues, it would be much appreciated.

thanks as always
Ringo

**Comment by glenn-slayden** [comment]
This can be fixed by adding `-vsync drop` to the **ffmpeg** command line:
<pre>ffmpeg.exe -i "x.f244.webm" -i "x.f140.m4a" <b>-vsync drop</b> -c copy -map "0:v:0" -map "1:a:0" "x.temp.mkv"</pre>

Fortunately, the argument can easily be specified in **youtube-dl** via the `--postprocessor-args` option on the command line (or in the configuration file):

    --postprocessor-args "-vsync drop" "-vsync drop"

**Comment by shillshocked** [comment]
I get "vsync: No such file or directory" when I use that.
