### ISSUE TITLE
[dplay] Add support for playlists

### ISSUE THREAD

**Issue by MrDemocracy** [ytdl-org/youtube-dl#14960]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl http://www.dplay.no/praktisk-info-med-jon-almaas/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.dplay.no/praktisk-info-med-jon-almaas/', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.10
[debug] Python version 2.7.13 - Darwin-17.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] praktisk-info-med-jon-almaas: Requesting header
WARNING: Could not send HEAD request to http://www.dplay.no/praktisk-info-med-jon-almaas/: HTTP Error 405: Method Not Allowed
[generic] praktisk-info-med-jon-almaas: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] praktisk-info-med-jon-almaas: Extracting information
ERROR: Unsupported URL: http://www.dplay.no/praktisk-info-med-jon-almaas/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 2163, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 3063, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.dplay.no/praktisk-info-med-jon-almaas/
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.dplay.no/praktisk-info-med-jon-almaas/season-1-episode-1/
- Single video: http://www.dplay.no/neste-sommer/season-1-episode-1-gratis/
- Playlist: http://www.dplay.no/praktisk-info-med-jon-almaas/
- Playlist: http://www.dplay.no/neste-sommer/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

All the episode links can be found in a json file, that is loaded when the page loads.
Example with "Praktisk info med Jon Almaas": `http://www.dplay.no/api/v2/ajax/shows/15882/seasons/?items=14&sort=episode_number_desc&video_types=-clip&page=0`
<img width="1280"  src="https://user-images.githubusercontent.com/23060864/33887644-ba3398c0-df4a-11e7-84e6-5db36ab30a30.png">
<img width="1280" src="https://user-images.githubusercontent.com/23060864/33887655-c403a5c0-df4a-11e7-8302-f40f54a5a5d6.png">

**Comment by craftpag** [comment]
Hello MrDemocracy!

since you have mentioned:
Single video: http://www.dplay.no/praktisk-info-med-jon-almaas/season-1-episode-1/
Single video: http://www.dplay.no/neste-sommer/season-1-episode-1-gratis/
Playlist: http://www.dplay.no/praktisk-info-med-jon-almaas/
Playlist: http://www.dplay.no/neste-sommer/

A while ago, do you have a new solution to download neste sommer and praktisk info med jon almaas from discoveryplus.com/no with youtube-dl? 
Hope you can help with a solution:)
