### ISSUE TITLE
[twitter] Add support for subtitles

### ISSUE THREAD

**Issue by SeanPM5** [ytdl-org/youtube-dl#14977]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.10**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
---

### Description of your *issue*, suggested solution and other information

youtube-dl supports Twitter (and works great) but it does not seem to find the subtitles/captions. Here is a video with subtitles - see the "CC" button in bottom right of video player: https://twitter.com/ResidentFOX/status/941025075049803776 

When I perform the "youtube-dl --list-subs" command, it says the video has no subtitles (even though it does):

```
iMac:Desktop Sean$ youtube-dl --list-subs https://twitter.com/ResidentFOX/status/941025075049803776
[twitter] 941025075049803776: Downloading webpage
[twitter:card] 941025075049803776: Downloading webpage
[twitter:card] 941025075049803776: Downloading m3u8 information
[twitter:card] 941025075049803776: Downloading mobile webpage
[twitter:card] 941025075049803776: Downloading main script
[twitter:card] 941025075049803776: Downloading mobile API data
[twitter:card] 941025075049803776: Downloading m3u8 information
941025075049803776 has no subtitles
```
Would be very helpful if youtube-dl could get these. Thanks.

**Comment by remitamine** [comment]
not accessible in the browser:
> This video has been deleted.

**Comment by SeanPM5** [comment]
Hi, here is a working Twitter video with subtitles:

https://twitter.com/themandalorian/status/1188986316194635777

**Comment by SeanPM5** [comment]
@remitamine Hi, here is a working Twitter video with subtitles:

https://twitter.com/themandalorian/status/1188986316194635777

You can see in the video player (at least on desktop) a CC button to turn on captions.

**Comment by remitamine** [comment]
this depends on #6106, so support for this type of subtitles has be added before woking on this issue,

**Comment by SeanPM5** [comment]
Thank you, appreciate the clarification 👍
