### ISSUE TITLE
@phihag Please make donations via ethereum available!

### ISSUE THREAD

**Issue by jk-85** [ytdl-org/youtube-dl#15194]
@phihag 
I really want to like to see a donation address for ethereum on the youtube-dl github homepage in the future, because bitcoin has soo high fees.

**Comment by yan12125** [comment]
How fees are determined for ethereum? I wonder if it will become the second bitcoin. AFAIK fees for bitcoin _were_ low.

If it's necessary I can set up an ethereum account (or any other cryptocurrency) and send money to the existing paypal account. How do you think @phihag?

**Comment by jk-85** [comment]
You can type in any amount in EUR here and get the miners fee for ethereum: https://anycoindirect.eu/en/buy/ethers. Since some weeks it's also gone up a little bit, but no comparison to bitcoin. You can use the Exodus wallet for example, this is a nice and uncomplicated multi-wallet for bitcoin, ethereum and others. But the exchange-rates between cryptos seems to be a little bit high in my personal opinion in Exodus, but you don't have to exchange.

**Comment by Hrxn** [comment]
> [..] Exodus wallet [..]

This one? `https://www.exodus.io`

**Comment by jk-85** [comment]
Yes, this one. This is no offline-wallet, but it's ok for me personally and I think for your donations also.

**Comment by vxbinaca** [comment]
You could use Blockchain.info for donations. I also second Etherium donations, Bitcoin has insane fees.

**Comment by jk-85** [comment]
Ah ok, you're right. I forgot, there was a "donation" button on every address I saw. so, when I use this donation button, there are no bitcoin fees? Or do I misunderstand this?

**Comment by jk-85** [comment]
Litecoin donations would be even better, but Ethereum is very stable the last weeks and often goes up.

**Comment by vxbinaca** [comment]
Either way, Bitcoin is dying due to it's own limitations. Etherium, Litecoin and a as of yet undecided by the community privacy coin will end up reigning supreme.
