### ISSUE TITLE
Can't download playlist items from Mixcloud

### ISSUE THREAD

**Issue by akapitany** [ytdl-org/youtube-dl#15197]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### Bug description

youtube-dl runs normally (without any error message) but it shows empty playlist.

```
youtube-dl --playlist-items 1-10 -v 'https://www.mixcloud.com/napiutravalo/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--playlist-items', '1-10', '-v', 'https://www.mixcloud.com/napiutravalo/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.07
[debug] Python version 3.6.4 (CPython) - Linux-4.14.3-1-ARCH-x86_64-with-arch
[debug] exe versions: none
[debug] Proxy map: {}
[mixcloud:user] napiutravalo_uploads: Downloading user profile
[download] Downloading playlist: Napi-útra-való (uploads)
[mixcloud:user] napiutravalo_uploads: Download list of uploads (page 1)
[mixcloud:user] playlist Napi-útra-való (uploads): Downloading 0 videos
[download] Finished downloading playlist: Napi-útra-való (uploads)
```

**Comment by redwards510** [comment]
I have the same problem with 
```
youtube-dl -v --embed-thumbnail --playlist-reverse https://www.mixcloud.com/benxo/uploads
```
on `2018.01.21`

**Comment by udvarit** [comment]
Can't download a person's favourites either, yt-dl shows empty playlist. Version `2018.04.16`.

`$ youtube-dl https://www.mixcloud.com/pikpik/favorites/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.mixcloud.com/pikpik/favorites/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.16
[debug] Python version 2.7.12 (CPython) - Linux-4.13.13-6-pve-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1
[debug] Proxy map: {}
[mixcloud:user] pikpik_favorites: Downloading user profile
[download] Downloading playlist: Pikpik (favorites)
[mixcloud:user] pikpik_favorites: Download list of favorites (page 1)
[mixcloud:user] playlist Pikpik (favorites): Downloading 0 videos
[download] Finished downloading playlist: Pikpik (favorites)`

**Comment by 2ge** [comment]
Hi, 

any news on this?
```
$ youtube-dl https://www.mixcloud.com/ReggaeRevolutionRadioShow/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.mixcloud.com/ReggaeRevolutionRadioShow/', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 2.7.10 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[mixcloud:user] ReggaeRevolutionRadioShow_uploads: Downloading user profile
[download] Downloading playlist: REGGAE REVOLUTION (uploads)
[mixcloud:user] ReggaeRevolutionRadioShow_uploads: Download list of uploads (page 1)
[mixcloud:user] playlist REGGAE REVOLUTION (uploads): Downloading 0 videos
[download] Finished downloading playlist: REGGAE REVOLUTION (uploads)
```
