### ISSUE TITLE
[DMAX] New DMAX site no longer works for video downloads

### ISSUE THREAD

**Issue by schuetze** [ytdl-org/youtube-dl#15234]
Hello everyone,

it looks like DMAX has a new online presence that does no longer work with youtube-dl. Please add the support for the new DMAX site layout:
e.g.
https://www.dmax.de/programme/steel-buddies/

When I use the windows version of the tool with the new DMAX site, the following happens:

F:\steel buddies>youtube-dl.exe https://dplaynordics-vod-01.akamaized.net/dplaydni/19404/0/hls/322486001/219937601-prog_index.m3u8?version_hash=f6308079
[generic] 219937601-prog_index: Requesting header
WARNING: Could not send HEAD request to https://dplaynordics-vod-01.akamaized.net/dplaydni/19404/0/hls/322486001/219937601-prog_index.m3u8?version_hash=f6308079: HTTP Error 403: Forbidden
[generic] 219937601-prog_index: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

F:\steel buddies>youtube-dl.exe -U
youtube-dl is up-to-date (2018.01.07)

F:\steel buddies>youtube-dl.exe --verbose https://dplaynordics-vod-01.akamaized.net/dplaydni/19404/0/hls/322486001/219937601-prog_index.m3u8?version_hash=f6308079
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://dplaynordics-vod-01.akamaized.net/dplaydni/19404/0/hls/322486001/219937601-prog_index.m3u8?version_hash=f6308079']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.01.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-63100-g5460ab7, ffprobe N-63100-g5460ab7
[debug] Proxy map: {}
[generic] 219937601-prog_index: Requesting header
WARNING: Could not send HEAD request to https://dplaynordics-vod-01.akamaized.net/dplaydni/19404/0/hls/322486001/219937601-prog_index.m3u8?version_hash=f6308079: HTTP Error 403: Forbidden
[generic] 219937601-prog_index: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\build\youtube_dl\extractor\common.py", line 517, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4k56gdgt\build\youtube_dl\YoutubeDL.py", line 2198, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

F:\steel buddies>

Greetings, and thanks in advance,

schuetze

**Comment by dr1s** [comment]
+1

**Comment by heptathlon** [comment]
DMAX does not work with programme overview pages such as https://www.dmax.de/programme/undercover-billionaire

[generic] undercover-billionaire: Requesting header
WARNING: Falling back on generic information extractor.
[generic] undercover-billionaire: Downloading webpage
[generic] undercover-billionaire: Extracting information
ERROR: Unsupported URL: https://www.dmax.de/programme/undercover-billionaire
