### ISSUE TITLE
6play not working

### ISSUE THREAD

**Issue by DavidTre07** [ytdl-org/youtube-dl#15248]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
The documentation says that 6play is supported but I'm getting this error:
```
./youtube-dl --verbose https://www.6play.fr/salvation-p_7981/Saison-1-episode-6-c_11853113
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.6play.fr/salvation-p_7981/Saison-1-episode-6-c_11853113']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.14
[debug] Python version 2.7.14 (CPython) - Linux-4.14.11-300.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven
[debug] exe versions: none
[debug] Proxy map: {}
[6play] 11853113: Downloading JSON metadata
[6play] 11853113: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[6play] 11853113: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[6play] 11853113: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[6play] 11853113: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/sixplay.py", line 86, in _real_extract
    self._sort_formats(formats)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1069, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by cafehaine** [comment]
see #14719 for a working account

**Comment by DavidTre07** [comment]
Hello,
I think this problem is not related to flash or an account needs.
If you want to centralize all tickets in relation with 6play, I will follow the #14719 

Thanks.

**Comment by catkfr** [comment]
Hello,
Following this issue: 6play not working for me either: HTTP 403 as well.

**Comment by tmpaccount56** [comment]
Here is a quick fix:

In file "/usr/lib/python3.6/site-packages/youtube_dl/extractor/sixplay.py" replace
                    asset_url = re.sub(r'/([^/]+)\.ism/[^/]*\.m3u8', r'/\1.ism/\1.m3u8', asset_url)
by
                    asset_url = re.sub(r'/([^/]+)\.ism/[^/]*\.m3u8', r'/\1.ism/Manifest.m3u8', asset_url)

Tested with https://www.6play.fr/top-chef-p_872/episode-1-saison-9-c_11874201

**Comment by cafehaine** [comment]
Can comfirm it works, tested with https://www.6play.fr/norbert-commis-d-office-p_4668/Yaniss-piratage-de-fruits-de-mer-Emmanuel-sabotage-de-quiche-c_11817466
Do you want to create a pr @tmpaccount56 ?

**Comment by ManuCart** [comment]
Thanks @tmpaccount56, good job
Need a commit for this patch

**Comment by ManuCart** [comment]
Have you tried the patch from @tmpaccount56
For me it work for time limited replay

**Comment by 89z** [comment]
Issue should be closed, URL appears to be dead
