### ISSUE TITLE
[YouTube] get_video_info with el=info has invalid parameters

### ISSUE THREAD

**Issue by Protuhj** [ytdl-org/youtube-dl#15246]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

Relevant portion below is the 'el=info' bit.
If you attempt to load the URL in a browser, you can see that it returns an error message.

```
python -m youtube_dl -F --print-traffic Sq3-W6BYpRU
[snip]
[youtube] Sq3-W6BYpRU: Downloading video info webpage
send: u'GET /get_video_info?ps=default&el=info&video_id=Sq3-W6BYpRU&hl=en&sts=17541&disable_polymer=true&gl=US&eurl=
[/snip]
```
---

### Description of your *issue*, suggested solution and other information

When attempting to load YouTube formats, the 'el=info' page (which used to serve the DASH MPD URL) contains the following error text in the resulting file:

```
errorcode=2&reason=Invalid+parameters.&status=fail
```

Either the el=info page should be removed, or a valid parameter set should be determined.

**Comment by anxdpanic** [comment]
el=vevo also returns Invalid parameters.

The valid el parameters I was able to find from the player.js; 'leanback', 'embedded', 'detailpage', 'editpage', 'adunit', 'previewpage', 'profilepage'
None seem to return dashmpd anymore unless it's live, my channel, or drm content.

**Comment by 89z** [comment]
Issue should be closed, that API is not used anymore
