### ISSUE TITLE
vrtnu subtitles aren't downloaded

### ISSUE THREAD

**Issue by creativefre** [ytdl-org/youtube-dl#15424]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.vrt.be/vrtnu/a-z/eigen-kweek/seizoen-2/coloradokevers/
- Single video: https://www.vrt.be/vrtnu/a-z/blue-planet-ii--nederlandstalig-/2017/blue-planet-ii--nederlandstalig--s2017a4-big-blue/
---

### Description of your *issue*, suggested solution and other information

Downloading video's works perfect. But subtitles are available with the video's on the vrt website. I've tried every possible command for downloading these subtitles but only the video gets downloaded. 

Hopefully this is possible to implement.

The python file where the vrtnu download is implemented is called canvas.py

**Comment by pbienst** [comment]
Could you link to the duplicate report, so that we can subscribe there? Thanks!

**Comment by dstftw** [comment]
Search: webvtt.
