### ISSUE TITLE
Attempting to download rented Vimeo video | ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.

### ISSUE THREAD

**Issue by tylerforesthauser** [ytdl-org/youtube-dl#15549]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

```
youtube-dl -u xxx@xxx.xxx --referer https://vimeo.com/ondemand/dekalbelementary/253137925 https://player.vimeo.com/video/253137925 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'--referer', u'https://vimeo.com/ondemand/dekalbelementary/253137925', u'https://player.vimeo.com/video/253137925', u'-v']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.08
[debug] Python version 2.7.10 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[vimeo] Logging in
[vimeo] 253137925: Downloading webpage
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 470, in _real_extract
    webpage, urlh = self._download_webpage_handle(request, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 539, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 528, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 485, in _real_extract
    expected=True)
ExtractorError: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
<end of log>
```

---

### Attempting to download rented Vimeo video

I just rented a video on Vimeo's website so there is no referrer I'm aware of. But I've tried using every variation I can think of...

`youtube-dl -u xxx@xxxx.xxx --referer https://vimeo.com/ondemand/dekalbelementary/253137925 https://player.vimeo.com/video/253137925`

`youtube-dl -u xxx@xxxx.xxx --referer https://vimeo.com/253137925 https://player.vimeo.com/video/253137925`

`youtube-dl -u xxx@xxxx.xxx --referer https://vimeo.com/ondemand/dekalbelementary/253137925 https://vimeo.com/ondemand/dekalbelementary/253137925`

`youtube-dl -u xxx@xxxx.xxx  https://vimeo.com/ondemand/dekalbelementary/253137925`

All of them give me the following error:

```
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
```

If I don't have a referrer, what do I do?

**Comment by dstftw** [comment]
You must provide account credentials for any work on this issue.

**Comment by tylerforesthauser** [comment]
tyler@foresthauser.com
M00nshine

**Comment by naldinho70** [comment]
Hello tylerforesthauser! you should add the link to the page that contains the video link example: https://www.site.com/page containing the videos or video / video link / # tab7355

or in the page that contains the video you copy the link with the right mouse and paste in youtube-dl
youtube-dl -f "best" link url page containing the video

I hope you can understand, it can be with private videos too.

**Comment by tylerforesthauser** [comment]
@dstftw My rental is about to expire in ~4 hours. No expectations or anything, I appreciate whatever help you're able to provide. Should I rent it again or maybe just accept defeat? Thank you very much for your time.

**Comment by dstftw** [comment]
For now you can download it with `--hls-prefer-native https://skyfire.vimeocdn.com/1518372607-0x67bc4d2e2d55050e545244d6b1c42b3a752984b6/253137925/video/922129565,922129550,922129549,922129548/master.m3u8`

**Comment by tylerforesthauser** [comment]
Whoa, amazing! Thank you so much! Are you able to shed some light on 1) how you got those urls and/or 2) why the standard url doesn't work?

**Comment by 9KuuCqmtebjTD** [comment]
Also interested in how this works.

**Comment by plugpoint** [comment]
#1099

Latest post has a fix

**Comment by yuliskov** [comment]
@9KuuCqmtebjTD, here the steps

* Open Chrome and press F12 key. DevTools should appear.
* Select `Network` panel inside DevTools.
* Reload page with video with F5 key. Now you should see network requests performed.
* Filter out the network requests by type `config` inside search filed. 
* Open content of the selected request (Open new tab)
* Search here `m3u8` substring.
* This should be the link what you have wanted.

![capture](https://user-images.githubusercontent.com/5897464/44271772-adf7b200-a243-11e8-8778-a2cbc7f9e060.JPG)
