### ISSUE TITLE
Unable to download show from FXNow (Simpsons World) with my cable provider using Adobe Pass

### ISSUE THREAD

**Issue by nhubbard** [ytdl-org/youtube-dl#15563]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

My log of this is below:
```
youtube-dl http://www.simpsonsworld.com/video/273376835817 --ap-mso WOW --ap-username PRIVATE --ap-password PRIVATE -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.simpsonsworld.com/video/273376835817', '--ap-mso', 'WOW', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.08
[debug] Python version 3.6.4 (CPython) - Linux-4.14.16-300.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven
[debug] exe versions: none
[debug] Proxy map: {}
[FXNetworks] 273376835817: Downloading webpage
[FXNetworks] 273376835817: Downloading Provider Redirect Page
[FXNetworks] 273376835817: Downloading Provider Login Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/fxnetworks.py", line 64, in _real_extract
    query['auth'] = self._extract_mvpd_auth(url, video_id, 'fx', resource)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/adobepass.py", line 1513, in _extract_mvpd_auth
    mso_info.get('password_field', 'password'): password,
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/adobepass.py", line 1365, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 805, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

I patched the list of supported providers in my own local copy like so:

```
    // wya010
    'WOW': {
        'name': 'WOW!',
        'username_field': 'username',
        'password_field': 'password'
    },
    // hin020-02
```

I still have gotten nowhere. I can provide credentials for this Adobe Pass provider.

**Comment by nhubbard** [comment]
@dstftw I sent you an email with the login information.

**Comment by dstftw** [comment]
I've no interest working on that.

**Comment by nhubbard** [comment]
@dstftw I would really like to try to work on it, but I have no clue where to start at in implementing it. If you could give me a couple pointers, I could try to implement it on my own.
I also sent the account information because you were the one that added the TV provider account needed label. Sorry about that.
