### ISSUE TITLE
Dplay.no isn't working with premium content.

### ISSUE THREAD

**Issue by Mssol94** [ytdl-org/youtube-dl#15707]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--prefer-ffmpeg', '-u', 'PRIVATE', '-p', 'PRIVATE', '--all-sub', '--write-thumbnail', '--output', '\\\\10.0.0.18\\i\\Media\\TV-Serier\\Helt Perfekt\\Helt Perfekt - S%(season_number)sE%(episode_number)s - WEBDL-%(height)sp.%(ext)s', '--convert-subs', 'vtt', '--embed-subs', 'https://www.dplay.no/videoer/thomas-giertsen-helt-perfekt/sesong-8-episode-2']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.02.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[debug] Using fake IP 84.211.84.128 (NO) as X-Forwarded-For.
[DPlay] thomas-giertsen-helt-perfekt/sesong-8-episode-2: Downloading webpage
[DPlay] thomas-giertsen-helt-perfekt/sesong-8-episode-2: Downloading token
[DPlay] thomas-giertsen-helt-perfekt/sesong-8-episode-2: Downloading JSON metadata
[DPlay] thomas-giertsen-helt-perfekt/sesong-8-episode-2: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfqykkd7x\build\youtube_dl\extractor\common.py", line 519, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfqykkd7x\build\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Dplay.no isn't working with the premium content even if I'm passing with -u and -p. Dplay is working as normal with the non-premium content.

**Comment by tingvold** [comment]
Same issue here, even when using cookies gathered from a logged in user.

@remitamine, I can provide you with an account that you can test with. I'f we find a fix, I'm guessing it will apply to dplay.{no|se|dk}.
