### ISSUE TITLE
[music.yandex.ru] Album URL not fully downloaded (extract errors)

### ISSUE THREAD

**Issue by Sality777** [ytdl-org/youtube-dl#15844]
[ x] I've verified and I assure that I'm running youtube-dl 2018.03.10
Before submitting an issue make sure you have:
[x ] At least skimmed through the README, most notably the FAQ and BUGS sections
[x ] Searched the bugtracker for similar issues including closed ones
[x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
What is the purpose of your issue?
[ x] Bug report (encountered problems with youtube-dl)
 Site support request (request for adding support for a new site)
 Feature request (request for a new functionality)
 Question
 Other
Hi all.
Playlist URL https://music.yandex.ru/users/rdsrecords.ru/playlists/1002 not fully downloaded.
LOG (177 lines):

$ LANG=en_US.UTF-8 ydl -v https://music.yandex.ru/users/rdsrecords.ru/playlists/1002
[debug] System config: []
[debug] User config: ['--external-downloader', 'aria2c']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://music.yandex.ru/users/rdsrecords.ru/playlists/1002']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.10
[debug] Git HEAD: 08250b6
[debug] Python version 3.6.4 (CPython) - Linux-4.15.8-1-zen-x86_64-with-arch
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[yandexmusic:playlist] 1002: Downloading missing tracks JSON
[download] Downloading playlist: Дискотека 80/90-х
[yandexmusic:playlist] playlist Дискотека 80/90-х: Collected 18 video ids (downloading 18 of them)
[download] Downloading video 1 of 18
[yandexmusic:track] 28132335: Downloading track JSON
[yandexmusic:track] 28132335: Downloading track location JSON
WARNING: "release_year" field is not numeric - forcing int conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s81f.storage.yandex.net/get-mp3/00290b621dba957b93f0ce2a659a72fd/00056745204bc51e/music/37/8/data-0.2:27247162298:6345246?track-id=41975435&from=service-10-track&similarities-experiment=default'
[download] Corona - The Rhythm Of The Night-28132335.mp3 has already been downloaded
[download] 100% of 6.05MiB
[download] Downloading video 2 of 18
[yandexmusic:track] 28132345: Downloading track JSON
[yandexmusic:track] 28132345: Downloading track location JSON
WARNING: "release_year" field is not numeric - forcing int conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s72myt.storage.yandex.net/get-mp3/3dc0327631f7fb4b07572c6e25eca7c9/0005674520739fbd/music/46/4/data-0.2:28025076801:5626774?track-id=41975445&from=service-10-track&similarities-experiment=default'
[download] Savage - Don'T Cry Tonight-28132345.mp3 has already been downloaded
[download] 100% of 5.37MiB
[download] Downloading video 3 of 18
[yandexmusic:track] 28132336: Downloading track JSON
[yandexmusic:track] 28132336: Downloading track location JSON
WARNING: "release_year" field is not numeric - forcing int conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s152man.storage.yandex.net/get-mp3/48a4c3f12bad343b2f96fe790ff3ac88/0005674520e749aa/music/54/6/data-0.3:37916468120:6132087?track-id=41975436&from=service-10-track&similarities-experiment=default'
[download] Ice MC - It's A Rainy Day-28132336.mp3 has already been downloaded
[download] 100% of 5.85MiB
[download] Downloading video 4 of 18
[yandexmusic:track] 28132344: Downloading track JSON
[yandexmusic:track] 28132344: Downloading track location JSON
WARNING: "release_year" field is not numeric - forcing int conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s79iva.storage.yandex.net/get-mp3/607692bf5025395cb0b4dd2391bcd886/00056745210f63d9/music/29/1/data-0.13:26945183548:5356564?track-id=41975444&from=service-10-track&similarities-experiment=default'
[download] Samantha - Call Me-28132344.mp3 has already been downloaded
[download] 100% of 5.11MiB
[download] Downloading video 5 of 18
[yandexmusic:track] 28132357: Downloading track JSON
[yandexmusic:track] 28132357: Downloading track location JSON
WARNING: "release_year" field is not numeric - forcing int conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s99iva.storage.yandex.net/get-mp3/733ae0b0af091114d8ac573201ea32a4/00056745213b93c8/music/3/3/data-0.14:13971560508:5730846?track-id=41975458&from=service-10-track&similarities-experiment=default'
[download] Whigfield - Sexy Eyes-28132357.mp3 has already been downloaded
[download] 100% of 5.47MiB
[download] Downloading video 6 of 18
[yandexmusic:track] 28132351: Downloading track JSON
[yandexmusic:track] 28132351: Downloading track location JSON
WARNING: "release_year" field is not numeric - forcing int conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s18man.storage.yandex.net/get-mp3/8878c085755ee7cb7a02b3be97d12619/00056745216a45a9/music/25/3/data-0.14:25460736485:5370983?track-id=41975451&from=service-10-track&similarities-experiment=default'
[download] 2 Unlimited - No Limit-28132351.mp3 has already been downloaded
[download] 100% of 5.12MiB
[download] Downloading video 7 of 18
[yandexmusic:track] 27395676: Downloading track JSON
[yandexmusic:track] 27395676: Downloading track location JSON
WARNING: "release_year" field is not numeric - forcing int conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s84iva.storage.yandex.net/get-mp3/860b25d5d5662db1e9638b26f6d52ed0/00056745219a2141/music/45/6/data-0.6:22337152136:6295718?track-id=40797558&from=service-10-track&similarities-experiment=default'
[download] Double You - You Are The One-27395676.mp3 has already been downloaded
[download] 100% of 6.00MiB
[download] Downloading video 8 of 18
[yandexmusic:track] 28132342: Downloading track JSON
[yandexmusic:track] 28132342: Downloading track location JSON
WARNING: "release_year" field is not numeric - forcing int conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s02vla.storage.yandex.net/get-mp3/4a1701420537f5f57024975d5112475c/0005674521c4bb13/music/55/2/data-0.58:6415321139:6669373?track-id=41975442&from=service-10-track&similarities-experiment=default'
[download] Savage - Radio-28132342.mp3 has already been downloaded
[download] 100% of 6.36MiB
[download] Downloading video 9 of 18
[yandexmusic:track] 25042647: Downloading track JSON
[yandexmusic:track] 25042647: Downloading track location JSON
WARNING: "release_year" field is not numeric - forcing int conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s18man.storage.yandex.net/get-mp3/bed450b72cfa23423c757137327c8ce5/0005674521ed7ba8/music/18/1/data-0.17:37104372607:5008612?track-id=37011840&from=service-10-track&similarities-experiment=default'
[download] Ice MC - Take Away The Colour-25042647.mp3 has already been downloaded
[download] 100% of 4.78MiB
[download] Downloading video 10 of 18
[yandexmusic:track] 28132346: Downloading track JSON
[yandexmusic:track] 28132346: Downloading track location JSON
WARNING: "release_year" field is not numeric - forcing int conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s30sas.storage.yandex.net/get-mp3/5acf9fcdc1d56092a5d213a63ba208f2/000567452219cacd/music/26/3/data-0.2:2565915048:5803571?track-id=41975446&from=service-10-track&similarities-experiment=default'
[download] Dana International - Diva'99-28132346.mp3 has already been downloaded
[download] 100% of 5.53MiB
[download] Downloading video 11 of 18
[yandexmusic:track] 27395672: Downloading track JSON
[yandexmusic:track] 27395672: Downloading track location JSON
WARNING: "release_year" field is not numeric - forcing int conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s109myt.storage.yandex.net/get-mp3/687ad3d68eca775c1bbee5e0c07efc25/00056745223fe80d/music/35/4/data-0.15:38067686453:5870653?track-id=40797554&from=service-10-track&similarities-experiment=default'
[download] 2 Unlimited - Let The Beat Control Your Body-27395672.mp3 has already been downloaded
[download] 100% of 5.60MiB
[download] Downloading video 12 of 18
[yandexmusic:track] 27395669: Downloading track JSON
[yandexmusic:track] 27395669: Downloading track location JSON
WARNING: "release_year" field is not numeric - forcing int conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s105myt.storage.yandex.net/get-mp3/d6f610b264eb92e6b787c8d9dc08e695/0005674522688bde/music/12/4/data-0.9:6658457007:5043721?track-id=40797551&from=service-10-track&similarities-experiment=default'
[download] Savage - I'm Loosing You-27395669.mp3 has already been downloaded
[download] 100% of 4.81MiB
[download] Downloading video 13 of 18
[yandexmusic:track] 28132349: Downloading track JSON
[yandexmusic:track] 28132349: Downloading track location JSON
WARNING: "release_year" field is not numeric - forcing int conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s153man.storage.yandex.net/get-mp3/8d7dac55c6cd3b183fb9bb4b5d3b1bab/000567452296c1c1/music/28/2/data-0.14:18093731763:4969115?track-id=41975449&from=service-10-track&similarities-experiment=default'
[download] Corona - Try Me Out-28132349.mp3 has already been downloaded
[download] 100% of 4.74MiB
[download] Downloading video 14 of 18
[yandexmusic:track] 28132358: Downloading track JSON
[yandexmusic:track] 28132358: Downloading track location JSON
WARNING: "release_year" field is not numeric - forcing int conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s49man.storage.yandex.net/get-mp3/493f946c66f49c87a9d189fcb561db73/0005674522bea7ce/music/34/2/data-0.2:27288286308:5597308?track-id=41975459&from=service-10-track&similarities-experiment=default'
[download] Double You - Dancing With An Angel-28132358.mp3 has already been downloaded
[download] 100% of 5.34MiB
[download] Downloading video 15 of 18
[yandexmusic:track] 28132370: Downloading track JSON
[yandexmusic:track] 28132370: Downloading track location JSON
WARNING: "release_year" field is not numeric - forcing int conversion, there is an error in extractor
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s70iva.storage.yandex.net/get-mp3/73bc55b51ecab88912c296d2db7a261b/0005674522e90ee7/music/31/4/data-0.2:7180358975:5495117?track-id=41975472&from=service-10-track&similarities-experiment=default'
[download] Destination: Ann Lee - 2 Times-28132370.mp3
[debug] aria2c command line: aria2c -c --min-split-size 1M --max-connection-per-server 4 --out 'Ann Lee - 2 Times-28132370.mp3.part' --header 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0 (Chrome)' --header 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,;q=0.7' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,/*;q=0.8' --header 'Accept-Encoding: gzip, deflate' --header 'Accept-Language: en-us,en;q=0.5' --check-certificate=true -- 'http://s70iva.storage.yandex.net/get-mp3/73bc55b51ecab88912c296d2db7a261b/0005674522e90ee7/music/31/4/data-0.2:7180358975:5495117?track-id=41975472&from=service-10-track&similarities-experiment=default'

03/13 12:12:00 [NOTICE] Downloading 1 item(s)
[#69df1b 4.1MiB/5.2MiB(79%) CN:3 DL:637KiB ETA:1s]
03/13 12:12:08 [NOTICE] Download complete: /home/ydl/pop/Ann Lee - 2 Times-28132370.mp3.part

Download Results:
gid |stat|avg speed |path/URI
======+====+===========+=======================================================
69df1b|OK | 690KiB/s|/home/ydl/pop/Ann Lee - 2 Times-28132370.mp3.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 5495117 bytes
[download] 100% of 5.24MiB
[download] Downloading video 16 of 18
[yandexmusic:track] 28132383: Downloading track JSON
[yandexmusic:track] 28132383: Downloading track location JSON
Traceback (most recent call last):
File "/home/ydl/.src/youtube-dl/youtube_dl/main.py", line 19, in 
youtube_dl.main()
File "/home/ydl/.src/youtube-dl/youtube_dl/init.py", line 471, in main
_real_main(argv)
File "/home/ydl/.src/youtube-dl/youtube_dl/init.py", line 461, in _real_main
retcode = ydl.download(all_urls)
File "/home/ydl/.src/youtube-dl/youtube_dl/YoutubeDL.py", line 1989, in download
url, force_generic_extractor=self.params.get('force_generic_extractor', False))
File "/home/ydl/.src/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
return self.process_ie_result(ie_result, download, extra_info)
File "/home/ydl/.src/youtube-dl/youtube_dl/YoutubeDL.py", line 995, in process_ie_result
extra_info=extra)
File "/home/ydl/.src/youtube-dl/youtube_dl/YoutubeDL.py", line 857, in process_ie_result
extra_info=extra_info)
File "/home/ydl/.src/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
ie_result = ie.extract(url)
File "/home/ydl/.src/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
ie_result = self._real_extract(url)
File "/home/ydl/.src/youtube-dl/youtube_dl/extractor/yandexmusic.py", line 144, in _real_extract
return self._get_track_info(track)
File "/home/ydl/.src/youtube-dl/youtube_dl/extractor/yandexmusic.py", line 102, in _get_track_info
'url': self._get_track_url(track['storageDir'], track['id']),
File "/home/ydl/.src/youtube-dl/youtube_dl/extractor/yandexmusic.py", line 88, in _get_track_url
% (data['host'], key, data['ts'] + data['path'], storage[1]))
TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by dstftw** [comment]
Playlist no longer available.
