### ISSUE TITLE
can't download from tv.naver.com

### ISSUE THREAD

**Issue by Starteer** [ytdl-org/youtube-dl#15886]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.14**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### full verbose output
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://tv.naver.com/v/2846258']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-90299-g939440ad1a, ffprobe N-90299-g939440ad1a
[debug] Proxy map: {}
[Naver] 2846258: Downloading webpage
ERROR: According to the request of the right holder,
the clip is not available in your country.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph71axfm2\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph71axfm2\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph71axfm2\build\youtube_dl\extractor\naver.py", line 53, in _real_extract
youtube_dl.utils.ExtractorError: According to the request of the right holder,
the clip is not available in your country.

...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

I can't download any video from tv.naver.com, it always gives me an error that the clip is not available in my country but I'm sure It's available because I can watch it in chrome.
Thank you

**Comment by WJSNLuda** [comment]
I have the same error but I can open the link in my browser.
Link example: http://tv.naver.com/v/1052122

[10/17/17 22:23:04] ERROR: This content is not available in your region
[10/17/17 22:23:04] This video is available in United States, Canada.
