### ISSUE TITLE
America's Test Kitchen Format Selection argument not working properly.

### ISSUE THREAD

**Issue by samantonioli** [ytdl-org/youtube-dl#15892]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl https://www.americastestkitchen.com/episode/566-grown-up-comfort-classics -f '[filesize<1000M]' -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.americastestkitchen.com/episode/566-grown-up-comfort-classics', u'-f', u'[filesize<1000M]', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 2.7.10 (CPython) - Darwin-17.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4, rtmpdump 2.4
[debug] Proxy map: {}
[AmericasTestKitchen] 566: Downloading webpage
[Kaltura] 1_4pwg43i0: Downloading video info JSON
[Kaltura] 1_4pwg43i0: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 888, in process_ie_result
    new_result, download=download, extra_info=extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 850, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1615, in process_video_result
    expected=True)
ExtractorError: requested format not available


```

---

### Description of your *issue*, suggested solution and other information

Using the "-f" argument on America's Test Kitchen videos yields "requested format not available" even though there is. When using the "-F" argument to list the available formats, it lists plenty of formats available that are less than 1000M in size, these include: 

hls-1031     mp4        640x360    1031k 
mp4-1545     mp4        1280x720   1545k , isom container, avc1, 29fps, ~253.00MiB
hls-1639     mp4        1280x720   1639k 
mp4-2628     mp4        1280x720   2628k , isom container, avc1, 29fps, ~424.00MiB
mp4-4128     mp4        1920x1080  4128k , isom container, avc1, 29fps, ~668.00MiB
mp4-20694    mp4        1920x1080  20694k , mp42 container, avc1, 29fps, ~3.24GiB (best)

Instead I also tried -f '[vbr<5000k]' and it also told me that the requested format is not available. Basically I'm trying to download the **second best** available format, the 1080p version that is not the 3.24GiB version.

**Comment by StevenDTX** [comment]
Are you using cookies?

```
E:\>c:\support\youtube-dl.exe --restrict-filenames --continue --no-check-certificate --ignore-errors --verbose https://www.americastestkitchen.com/episode/578-diner-style-favorites-with-a-twist --cookies e:\cookies\cookies.txt -f mp4-4080
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '--continue', '--no-check-certificate', '--ignore-errors', '--verbose', 'https://www.americastestkitchen.com/episode/578-diner-style-favorites-with-a-twist', '--cookies', 'e:\\cookies\\cookies.txt', '-f', 'mp4-4080']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-89980-ge752da5464, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[AmericasTestKitchen] 578: Downloading webpage
[Kaltura] 0_62frjvw1: Downloading video info JSON
[Kaltura] 0_62frjvw1: Downloading m3u8 information
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1445801/sp/144580100/playManifest/entryId/0_62frjvw1/format/url/protocol/http/flavorId/0_26pqir9q'
[download] Destination: Diner-Style_Favorites_with_a_Twist-0_62frjvw1.mp4
[download]   2.4% of 668.75MiB at  5.84MiB/s ETA 01:51
```

**Comment by StevenDTX** [comment]
Nevermind...looks like that one URL you posted might be a bit wonky. I still got it to download:

Formats available:
```
E:\>c:\support\youtube-dl.exe --restrict-filenames --continue --no-check-certificate --ignore-errors --verbose https://www.americastestkitchen.com/episode/566-grown-up-comfort-classics -F
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '--continue', '--no-check-certificate', '--ignore-errors', '--verbose', 'https://www.americastestkitchen.com/episode/566-grown-up-comfort-classics', '-F']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-89980-ge752da5464, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[AmericasTestKitchen] 566: Downloading webpage
[Kaltura] 1_4pwg43i0: Downloading video info JSON
[Kaltura] 1_4pwg43i0: Downloading m3u8 information
[info] Available formats for 1_4pwg43i0:
format code  extension  resolution note
3gp-372      3gp        320x176     372k , 3gp4 container, mpeg-4 visual, 29fps, ~60.90MiB
mp4-471      mp4        640x360     471k , isom container, avc1, 29fps, ~77.20MiB
hls-515      mp4        640x360     515k
mp4-670      mp4        640x360     670k , isom container, avc1, 29fps, ~110.00MiB
hls-723      mp4        640x360     723k
webm-827     webm       640x360     827k , webm container, v_vp8, 29fps, ~136.00MiB
mp4-964      mp4        640x360     964k , isom container, avc1, 29fps, ~156.00MiB
hls-1031     mp4        640x360    1031k
mp4-1545     mp4        1280x720   1545k , isom container, avc1, 29fps, ~253.00MiB
hls-1639     mp4        1280x720   1639k
mp4-2628     mp4        1280x720   2628k , isom container, avc1, 29fps, ~424.00MiB
mp4-4128     mp4        1920x1080  4128k , isom container, avc1, 29fps, ~668.00MiB
mp4-20694    mp4        1920x1080  20694k , mp42 container, avc1, 29fps, ~3.24GiB (best)

```

Actual download:
```
E:\>c:\support\youtube-dl.exe --restrict-filenames --continue --no-check-certificate --ignore-errors --verbose https://www.americastestkitchen.com/episode/566-grown-up-comfort-classics -f mp4-4128
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '--continue', '--no-check-certificate', '--ignore-errors', '--verbose', 'https://www.americastestkitchen.com/episode/566-grown-up-comfort-classics', '-f', 'mp4-4128']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-89980-ge752da5464, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[AmericasTestKitchen] 566: Downloading webpage
[Kaltura] 1_4pwg43i0: Downloading video info JSON
[Kaltura] 1_4pwg43i0: Downloading m3u8 information
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1445801/sp/144580100/playManifest/entryId/1_4pwg43i0/format/url/protocol/http/flavorId/1_5swnux8k'
[download] Destination: Grown_Up_Comfort_Classics-1_4pwg43i0.mp4
[download] 100% of 667.54MiB in 02:01
```

**Comment by samastrophe** [comment]
I see that using "-f mp4-4128" works, but when I'm trying to batch download multiple urls, the "second best" option isn't always 4128k, so using that to find the second best option for multiple URLS still won't work. That's why I was using "<1000" because although all of the second best options aren't always exactly 4128, they're ALL less than 1GB in size.

**Comment by remitamine** [comment]
America's Test Kitchen no longer uses Kaltura(file size no present in metadata).
