### ISSUE TITLE
Pluralsight Videos not downloading

### ISSUE THREAD

**Issue by Perinban** [ytdl-org/youtube-dl#16028]
Below I have attached the Verbose Ouput error that I have faced with downloading the Pluralsight Video from the latest version

$ youtube-dl --username xxxxx --password xxxxx--verbose --continue --sleep-interval 35 --max-sleep
-interval 120 --sub-lang en --sub-format srt --write-sub "https://app.pluralsight.com/library/courses/kali-linux-penetration-testing-ethical-hacking/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose', '--continue', '--sleep-interval', '35', '--max-sleep-interval', '120', '--sub-lang', 'en', '--sub-format', 'srt', '--write-sub', 'https://app.pluralsight.com/library/courses/kali-linux-penetration-testing-ethical-hacking/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.03.26.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] kali-linux-penetration-testing-ethical-hacking: Downloading course JSON
[download] Downloading playlist: Penetration Testing and Ethical Hacking with Kali Linux
[pluralsight:course] playlist Penetration Testing and Ethical Hacking with Kali Linux: Collected 96 video ids (downloading 96 of them)
[download] Downloading video 1 of 96
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] kali-linux-penetration-testing-ethical-hacking-m1-0: Downloading course JSON
[pluralsight] kali-linux-penetration-testing-ethical-hacking-m1-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] kali-linux-penetration-testing-ethical-hacking-m1-0: Waiting for 2 seconds to avoid throttling
[pluralsight] kali-linux-penetration-testing-ethical-hacking-m1-0: Downloading captions JSON
[debug] Default format spec: best/bestvideo+bestaudio
[info] Writing video subtitles to: Introduction-kali-linux-penetration-testing-ethical-hacking-m1-01.en.srt
[debug] Invoking downloader on 'http://vid20.pluralsight.com/clips/resolution/63373318-9db1-4c6a-82d2-5853149f0365/current/mp4/1280x720.mp4?ek6mqLmcd-Bh1LtzHIxUIVPQrgwci2fLXHQfcxQ22vBrMrz7ItkfZwck49sEmY4tFvDgAiA6Hp7ZSjqr_t8SPy1XKdbxuoJxDAX7QDfuBWvXtchrY0PRGiC66pJqC7uDLjp9m-hUeFdIBeWxVHwodIAPW6JNmA2DrJeRW0pZ4ZNHuGkDoDdc5CKbQLn9'
[download] Introduction-kali-linux-penetration-testing-ethical-hacking-m1-01.mp4 has already been downloaded
[download] 100% of 1.32MiB
[download] Downloading video 2 of 96
[pluralsight] kali-linux-penetration-testing-ethical-hacking-m1-1: Downloading course JSON
[pluralsight] kali-linux-penetration-testing-ethical-hacking-m1-1: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] kali-linux-penetration-testing-ethical-hacking-m1-1: Waiting for 4 seconds to avoid throttling
[pluralsight] kali-linux-penetration-testing-ethical-hacking-m1-1: Downloading captions JSON
[debug] Default format spec: best/bestvideo+bestaudio
[info] Writing video subtitles to: Kali Linux 2.0-kali-linux-penetration-testing-ethical-hacking-m1-02.en.srt
[debug] Invoking downloader on 'http://vid5.pluralsight.com/expiretime=1522340614/73cf16bf84f647cd659b1b800266f447/clips/resolution/61016d63-1b19-43f7-9d62-9759088315bf/current/mp4/1280x720.mp4'
[download] Kali Linux 2.0-kali-linux-penetration-testing-ethical-hacking-m1-02.mp4 has already been downloaded
[download] 100% of 49.40MiB
[download] Downloading video 3 of 96
[pluralsight] kali-linux-penetration-testing-ethical-hacking-m1-2: Downloading course JSON
[pluralsight] kali-linux-penetration-testing-ethical-hacking-m1-2: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\common.py", line 519, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by dstftw** [comment]
You must provide account credentials for any work on this issue.

**Comment by MacFlurry** [comment]
hello,

how can I give you privately my account ? 

Regards

**Comment by Perinban** [comment]
@dstftw How Could I share my personal account? I tried the same thing with both linux and windows version, I get the same error. I think its maybe with the version

**Comment by dstftw** [comment]
By mail in my profile.

**Comment by MacFlurry** [comment]
thanks @dstftw , is @Perinban account enough or do you need mine too ?

Regards

**Comment by MacFlurry** [comment]
@Perinban hello, did you give @dstftw your credentials ?

Regards

**Comment by MacFlurry** [comment]
weird, seems to work now. 😳

**Comment by Perinban** [comment]
@MacFlurry It seems to work for me too. So, I didn't give my credentials
