### ISSUE TITLE
MixCloud: download of an user public "uploads" page doesn't work anymore

### ISSUE THREAD

**Issue by JoshLambda** [ytdl-org/youtube-dl#16057]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.26.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.26.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.mixcloud.com/vaneaph/uploads/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.26.1
[debug] Python version 2.7.14 (CPython) - Linux-4.13.0-37-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: ffmpeg 3.3.4-2, ffprobe 3.3.4-2
[debug] Proxy map: {}
[mixcloud:user] vaneaph_uploads: Downloading user profile
[download] Downloading playlist: med Oh (uploads)
[mixcloud:user] vaneaph_uploads: Download list of uploads (page 1)
[mixcloud:user] playlist med Oh (uploads): Downloading 0 videos
[download] Finished downloading playlist: med Oh (uploads)

<end of log>
```
---

### Description of your *issue*, suggested solution and other information

**Web site**: mixcloud.com

**Description**: Downloading the audio content of an **user uploads page** doesn't work anymore.

**How to reproduce**: Click on any user name, then click on the _Shows_ tab. Downloading the whole content, using the url in the browser address bar with youtube-dl used to work. But now it always finds "0 videos".

**Example URL**: https://www.mixcloud.com/vaneaph/uploads/

**Example command**: youtube-dl -v "https://www.mixcloud.com/vaneaph/uploads/"

_(verbose log output was provided above)_

**Comment by nimbius** [comment]
2018.12.31 is also affected.

**Comment by xybydy** [comment]
it still is not solved yet.
