### ISSUE TITLE
[Pornhub] Can't download at pornstar level

### ISSUE THREAD

**Issue by ipkpjersi** [ytdl-org/youtube-dl#16078]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
 youtube-dl https://www.pornhub.com/pornstar/liz-vicious -i --download-archive downloaded.txt -o "/data/rips/%(uploader)s/%(title)s.%(ext)s" -f best -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.pornhub.com/pornstar/liz-vicious', '-i', '--download-archive', 'downloaded.txt', '-o', '/data/rips/%(uploader)s/%(title)s.%(ext)s', '-f', 'best', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.03
[debug] Python version 3.5.2 (CPython) - Linux-4.13.0-37-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 3.4.git-1ubuntu2, avprobe 3.4.git-1ubuntu2, ffmpeg 3.4.git-1ubuntu2, ffprobe 3.4.git-1ubuntu2
[debug] Proxy map: {}
[generic] liz-vicious: Requesting header
WARNING: Falling back on generic information extractor.
[generic] liz-vicious: Downloading webpage
[generic] liz-vicious: Extracting information
[download] Downloading playlist: Liz Vicious Porn Videos | Pornhub.com
[generic] playlist Liz Vicious Porn Videos | Pornhub.com: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Invoking downloader on 'data:"+o+";base64,"+E+"'
ERROR: Incorrect padding
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 995, in process_ie_result
    extra_info=extra)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 850, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 1623, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 1896, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 1835, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/downloader/common.py", line 365, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/downloader/http.py", line 340, in real_download
    establish_connection()
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 2199, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1567, in data_open
    data = base64.decodebytes(data)
  File "/usr/lib/python3.5/base64.py", line 553, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Pornstar:  https://www.pornhub.com/pornstar/liz-vicious

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I cannot download videos at the pornstar level on GitHub.

**Comment by Hrxn** [comment]
Not implemented yet?

**Comment by ipkpjersi** [comment]
Oh, I didn't know this wasn't implemented. Are there any plans to implement this?

**Comment by ipkpjersi** [comment]
So I guess that's a no..? :octocat:

**Comment by Hrxn** [comment]
Not necessarily.. 😄

**Comment by tarnationfiend** [comment]
Slightly related but are you able to download a channel? I've been having issues and managed it just once

**Comment by parmjitv** [comment]
Hi @ipkpjersi,

Looks like we need to add support for non-verified pornstar video collections - a new PR will be submitted shortly to address this.

Cheers,

Parmjit V.
