### ISSUE TITLE
Bug on BFM

### ISSUE THREAD

**Issue by 2edff206** [ytdl-org/youtube-dl#16303]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl http://rmc.bfmtv.com/emission/vous-etes-une-bombe-atomique-quand-un-auditeur-drague-apolline-de-malherbe-en-direct-sur-rmc-1431155.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://rmc.bfmtv.com/emission/vous-etes-une-bombe-atomique-quand-un-auditeur-drague-apolline-de-malherbe-en-direct-sur-rmc-1431155.html', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.25
[debug] Python version 2.7.14 (CPython) - Linux-4.13.0-38-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: ffmpeg 3.3.4-2, ffprobe 3.3.4-2
[debug] Proxy map: {}
[generic] vous-etes-une-bombe-atomique-quand-un-auditeur-drague-apolline-de-malherbe-en-direct-sur-rmc-1431155: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vous-etes-une-bombe-atomique-quand-un-auditeur-drague-apolline-de-malherbe-en-direct-sur-rmc-1431155: Downloading webpage
[generic] vous-etes-une-bombe-atomique-quand-un-auditeur-drague-apolline-de-malherbe-en-direct-sur-rmc-1431155: Extracting information
[download] Downloading playlist: « Vous êtes une bombe atomique! »: quand un auditeur drague Apolline de Malherbe en direct sur RMC
[generic] playlist « Vous êtes une bombe atomique! »: quand un auditeur drague Apolline de Malherbe en direct sur RMC: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:legacy] 5777130037001: Downloading webpage
[brightcove:legacy] 5777130037001: Extracting information
ERROR: Unable to extract video url for 5777130037001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 304, in _real_extract
    videoPlayer[0], query, referer=referer)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 335, in _get_video_info
    return self._extract_video_info(video_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 448, in _extract_video_info
    raise ExtractorError('Unable to extract video url for %s' % video_id)
ExtractorError: Unable to extract video url for 5777130037001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by mdamien** [comment]
Also reproduced today with the latest version on this url: https://www.bfmtv.com/mediaplayer/replay/premiere-edition/
