### ISSUE TITLE
URL's of vrtnu.be give error 403: Forbidden

### ISSUE THREAD

**Issue by henklietaert** [ytdl-org/youtube-dl#16348]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows

[debug] System config: [u'-f', u'bestvideo[height<=?1080]+bestaudio/best', u'--mark-watched', u'-o', u'/Users/USER/Downloads/YT/%(title)s.%(ext)s', u'-n']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.vrt.be/vrtnu/a-z/the-vietnam-war/1/the-vietnam-war-s1a1/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.01
[debug] Python version 2.7.10 (CPython) - Darwin-17.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
[VrtNU] the-vietnam-war-s1a1: Downloading webpage
[VrtNU] the-vietnam-war-s1a1: Downloading JSON metadata
[Canvas] pbs-pub-3a1cfe7b-762a-4bcf-9c4b-52487a3e284d$vid-282b4a61-5af4-495b-80dd-35f278c75ad0: Downloading JSON metadata
[Canvas] pbs-pub-3a1cfe7b-762a-4bcf-9c4b-52487a3e284d$vid-282b4a61-5af4-495b-80dd-35f278c75ad0: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Canvas] pbs-pub-3a1cfe7b-762a-4bcf-9c4b-52487a3e284d$vid-282b4a61-5af4-495b-80dd-35f278c75ad0: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[Canvas] pbs-pub-3a1cfe7b-762a-4bcf-9c4b-52487a3e284d$vid-282b4a61-5af4-495b-80dd-35f278c75ad0: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden
[Canvas] pbs-pub-3a1cfe7b-762a-4bcf-9c4b-52487a3e284d$vid-282b4a61-5af4-495b-80dd-35f278c75ad0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "youtube-dl/youtube_dl/extractor/canvas.py", line 72, in _real_extract
    self._sort_formats(formats)
  File "youtube-dl/youtube_dl/extractor/common.py", line 1130, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

### Description of your *issue*, suggested solution and other information

When trying to download a video from vrtnu.be the program gives error 403: Forbidden. A free account can be made on the homepage: vrtnu.be
It used to work a couple of months ago.

**Comment by remitamine** [comment]
```
[VrtNU] the-vietnam-war-s1a1: Downloading webpage
[VrtNU] the-vietnam-war-s1a1: Downloading JSON metadata
[Canvas] pbs-pub-3a1cfe7b-762a-4bcf-9c4b-52487a3e284d$vid-282b4a61-5af4-495b-80dd-35f278c75ad0: Downloading JSON metadata
[Canvas] pbs-pub-3a1cfe7b-762a-4bcf-9c4b-52487a3e284d$vid-282b4a61-5af4-495b-80dd-35f278c75ad0: Downloading m3u8 information
[Canvas] pbs-pub-3a1cfe7b-762a-4bcf-9c4b-52487a3e284d$vid-282b4a61-5af4-495b-80dd-35f278c75ad0: Downloading MPD manifest
WARNING: [Canvas] Unknown MIME type application/mp4 in DASH manifest
[Canvas] pbs-pub-3a1cfe7b-762a-4bcf-9c4b-52487a3e284d$vid-282b4a61-5af4-495b-80dd-35f278c75ad0: Downloading ISM manifest
[Canvas] pbs-pub-3a1cfe7b-762a-4bcf-9c4b-52487a3e284d$vid-282b4a61-5af4-495b-80dd-35f278c75ad0: Downloading f4m manifest
[debug] Invoking downloader on 'https://ondemand-b.lwc.vrtcdn.be/content/vod/vid-282b4a61-5af4-495b-80dd-35f278c75ad0-CDN_6/vid-282b4a61-5af4-495b-80dd-35f278c75ad0-CDN_6_nodrm_56a05937-d2e7-485f-819a-7bde4422e4d2.ism/vid-282b4a61-5af4-495b-80dd-35f278c75ad0-CDN_6_nodrm_56a05937-d2e7-485f-819a-7bde4422e4d2-audio_nld=93375-video=1965416.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 558
[download] Destination: Déjà vu (1858-1961)-pbs-pub-3a1cfe7b-762a-4bcf-9c4b-52487a3e284d$vid-282b4a61-5af4-495b-80dd-35f278c75ad0.mp4
[download]   0.3% of ~386.77MiB at 251.95KiB/s ETA 35:01
```

**Comment by gd** [comment]
Seeing the same issue with 2018.09.01, just like in
https://github.com/rg3/youtube-dl/issues/17083
There one cannot comment, here is the debug log:

[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--username=PRIVATE', u'--password=PRIVATE', u'https://www.vrt.be/vrtnu/a-z/occupied/1/occupied-s1a1/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.01
[debug] Python version 2.7.15 (CPython) - Linux-4.17.19-200.fc28.x86_64-x86_64-with-fedora-28-Twenty_Eight
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
[VrtNU] occupied-s1a1: Downloading webpage
[VrtNU] occupied-s1a1: Downloading JSON metadata
[Canvas] pbs-pub-44664a3d-7b0a-4670-a7ea-3c7bcad3a848$vid-26cabcb9-77d8-4df1-9bc0-627a6cbf1351: Downloading JSON metadata
[Canvas] pbs-pub-44664a3d-7b0a-4670-a7ea-3c7bcad3a848$vid-26cabcb9-77d8-4df1-9bc0-627a6cbf1351: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Canvas] pbs-pub-44664a3d-7b0a-4670-a7ea-3c7bcad3a848$vid-26cabcb9-77d8-4df1-9bc0-627a6cbf1351: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[Canvas] pbs-pub-44664a3d-7b0a-4670-a7ea-3c7bcad3a848$vid-26cabcb9-77d8-4df1-9bc0-627a6cbf1351: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden
[Canvas] pbs-pub-44664a3d-7b0a-4670-a7ea-3c7bcad3a848$vid-26cabcb9-77d8-4df1-9bc0-627a6cbf1351: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
No longer available.
