### ISSUE TITLE
Invoke ffmpeg automatically after download

### ISSUE THREAD

**Issue by ddevault** [ytdl-org/youtube-dl#1653]
It would be quite nice to offer some ffmpeg arguments in the invocation of youtube-dl. For example:

```
youtube-dl http://youtube.com/foobar :-filter "atempo:1.2" output.mp3
```

This would download the file, then run:

```
ffmpeg -i file.mp4 -filter "atempo:1.2" output.mp3
```

I find myself using ffmpeg right after youtube-dl nearly every time, so this would be a nice thing to have.

**Comment by dirkf** [comment]
Nowadays: `--exec ...`
