### ISSUE TITLE
Add support for zoom.us

### ISSUE THREAD

**Issue by Manwithpants812** [ytdl-org/youtube-dl#16597]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.30*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.30**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```

C:\Users\lol\Downloads>youtube-dl -v "https://zoom.us/recording/play/SILVuCL4bFtRwWTtOCFQQxAsBQsJljFtm9e4Z_bvo-A8B-nzUSYZRNuPl3qW5IGK"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://zoom.us/recording/play/SILVuCL4bFtRwWTtOCFQQxAsBQsJljFtm9e4Z_bvo-A8B-nzUSYZRNuPl3qW5IGK']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.05.30
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-90710-gaedbf1640c
[debug] Proxy map: {'http': 'http://127.0.0.1:8888', 'https': 'https://127.0.0.1:8888'}
[generic] SILVuCL4bFtRwWTtOCFQQxAsBQsJljFtm9e4Z_bvo-A8B-nzUSYZRNuPl3qW5IGK: Requesting header
WARNING: Falling back on generic information extractor.
[generic] SILVuCL4bFtRwWTtOCFQQxAsBQsJljFtm9e4Z_bvo-A8B-nzUSYZRNuPl3qW5IGK: Downloading webpage
[generic] SILVuCL4bFtRwWTtOCFQQxAsBQsJljFtm9e4Z_bvo-A8B-nzUSYZRNuPl3qW5IGK: Extracting information
[download] Downloading playlist: Video Conferencing, Web Conferencing, Webinars, Screen Sharing
[generic] playlist Video Conferencing, Web Conferencing, Webinars, Screen Sharing: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://ssrweb.zoom.us/cmr/replay/2018/01/31/627969148/F85683EA-FC4D-47B8-AC75-278AA849BD2A/GMT20180131-020020_GAZ-Transf_1920x1050.mp4?response-content-type=video/mp4&Expires=1527847067&Signature=Y5R1LVfnStShrH2ceHsIhBlvkpzo3UOOKy~RFEsUzkaIq1hA~Q5AeH0U6Dc-RfZcvTJaBvqpGgEXxVrIzLBER2W-Bu~yblrtagAVg7PTI5xqbdZqcUow~dCEY6rrydv~58FiQaK3XuEbT68M-g9cyVRw5dQHCpmOkHfBAFCGGOKHfoMmb8fermpP5nDafKWXWdUSWpE1QF1bG05eQUIgNktezUX3N5yqoMno7PTNuu5zc8bjY-kqBljFEnaHIcShnLFUjWZpIKkqE~bPJsmAF7CavWGcB9eKxAlb2vv60RVDcP7bMe3~hRF-RaNpEtiHiWoDqxVuYAo7sLIHUsWuOw__&Key-Pair-Id=APKAJFHNSLHYCGFYQGIA'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpreyzoe3x\build\youtube_dl\YoutubeDL.py", line 1908, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpreyzoe3x\build\youtube_dl\YoutubeDL.py", line 1847, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpreyzoe3x\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpreyzoe3x\build\youtube_dl\downloader\http.py", line 340, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpreyzoe3x\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpreyzoe3x\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
https://zoom.us/recording/play/SILVuCL4bFtRwWTtOCFQQxAsBQsJljFtm9e4Z_bvo-A8B-nzUSYZRNuPl3qW5IGK

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

**Comment by IceT75** [comment]
On this link youtube-dl last version of 30-5 gave this error
HTTP Error 403: Forbidden

https://cp450888-vh.akamaihd.net/i/mtviestor/_!/intlod/MTVInternational/MBUS/TACTIC/201805/VIAMTVIPYC0259OHDL9/IT_INGOODCOMPANY_QNG000619_,384x216_400_m30,512x288_750_m30,640x360_1200_m30,768x432_1700_m30,960x540_2200_m31,1280x720_3500_h32,.mp4.csmil/master.m3u8?hdnea=st%3D1527863866%7Eexp%3D1527878266%7Eacl%3D%2Fi%2Fmtviestor%2F_*%2Fintlod%2FMTVInternational%2FMBUS%2FTACTIC%2F201805%2FVIAMTVIPYC0259OHDL9%2FIT_INGOODCOMPANY_QNG000619_%2C384x216_400_m30%2C512x288_750_m30%2C640x360_1200_m30%2C768x432_1700_m30%2C960x540_2200_m31%2C1280x720_3500_h32%2C.mp4.csmil%2F*%7Ehmac%3D645ff56fc636861c84c1813abac438d00b0bfbf5053b025a88fd3d20792ecd67&__a__=off&__b__=450&__viacc__=NONE

**Comment by IceT75** [comment]
On this link youtube-dl last version of 30-5 gave this error
HTTP Error 403: Forbidden

https://cp450888-vh.akamaihd.net/i/mtviestor/_!/intlod/MTVInternational/MBUS/TACTIC/201805/VIAMTVIPYC0259OHDL9/IT_INGOODCOMPANY_QNG000619_,384x216_400_m30,512x288_750_m30,640x360_1200_m30,768x432_1700_m30,960x540_2200_m31,1280x720_3500_h32,.mp4.csmil/master.m3u8?hdnea=st%3D1527863866%7Eexp%3D1527878266%7Eacl%3D%2Fi%2Fmtviestor%2F_*%2Fintlod%2FMTVInternational%2FMBUS%2FTACTIC%2F201805%2FVIAMTVIPYC0259OHDL9%2FIT_INGOODCOMPANY_QNG000619_%2C384x216_400_m30%2C512x288_750_m30%2C640x360_1200_m30%2C768x432_1700_m30%2C960x540_2200_m31%2C1280x720_3500_h32%2C.mp4.csmil%2F*%7Ehmac%3D645ff56fc636861c84c1813abac438d00b0bfbf5053b025a88fd3d20792ecd67&__a__=off&__b__=450&__viacc__=NONE

**Comment by IceT75** [comment]
On this link youtube-dl last version of 30-5 gave this error
HTTP Error 403: Forbidden

https://cp450888-vh.akamaihd.net/i/mtviestor/_!/intlod/MTVInternational/MBUS/TACTIC/201805/VIAMTVIPYC0259OHDL9/IT_INGOODCOMPANY_QNG000619_,384x216_400_m30,512x288_750_m30,640x360_1200_m30,768x432_1700_m30,960x540_2200_m31,1280x720_3500_h32,.mp4.csmil/master.m3u8?hdnea=st%3D1527863866%7Eexp%3D1527878266%7Eacl%3D%2Fi%2Fmtviestor%2F_*%2Fintlod%2FMTVInternational%2FMBUS%2FTACTIC%2F201805%2FVIAMTVIPYC0259OHDL9%2FIT_INGOODCOMPANY_QNG000619_%2C384x216_400_m30%2C512x288_750_m30%2C640x360_1200_m30%2C768x432_1700_m30%2C960x540_2200_m31%2C1280x720_3500_h32%2C.mp4.csmil%2F*%7Ehmac%3D645ff56fc636861c84c1813abac438d00b0bfbf5053b025a88fd3d20792ecd67&__a__=off&__b__=450&__viacc__=NONE
