### ISSUE TITLE
RTVE.ES No longer working

### ISSUE THREAD

**Issue by pengstrom** [ytdl-org/youtube-dl#16779]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.19*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--all-subs', '--embed-subs', '--write-sub', 'www.rtve.es/alacarta/videos/servir-y-proteger/servir-proteger-capitulo-154/4363357/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.19
[debug] Python version 3.6.4 (CPython) - Linux-4.14.13-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] 4363357: Downloading JSON metadata
[rtve.es:alacarta] 4363357: Downloading url information
[rtve.es:alacarta] 4363357: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 500: Internal Server Error
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/rtve.py", line 152, in _real_extract
    self._sort_formats(formats)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

Earlier this month (June 6), I could download from `rtve.es`. Now however, I get an error. I guess the site changed its format. The previous issues are therefore probably not relevant.

**Comment by felisucoibi** [comment]
It's hapening to me in some videos too in 2019, so it works in some but i think there is another method in some videos and is not working, like in this one....
http://www.rtve.es/alacarta/videos/abuela-de-verano/abuela-verano-abuelo/1183803/

**Comment by felisucoibi** [comment]
this bug can be closed i think

**Comment by peteruhrig** [comment]
Hi, I think there has been a change in format for some rtve URLs. For instance, this one here fails:
`youtube-dl https://www.rtve.es/alacarta/videos/el-condensador-de-fluzo/`
It seems to be the main page of the programme, displaying the latest episode.

But if you look at the source of the page, you will spot this:
`<link rel="canonical" href="https://www.rtve.es/alacarta/videos/el-condensador-de-fluzo/mariposas-estomago-grandes-historias-amor/5790525/" />`
With that link, it works.

What does not work is the extraction of the subtitles, but they are there in plain sight in the page source:
```
<span>Transcripción completa</span>
--
  | </span>
  | <div class="blindBox trasBox be_on">
  |  
  | <p data-config='{"init":0}'>
  | <c.vtt_yellow>El amor puede ser un fin de semana
  | en Par&#xED;s, un beso en g&#xF3;ndola</c.vtt_yellow>
  | </p>
  |  
  | <p data-config='{"init":3.12}'>
  | <c.vtt_yellow>o como dec&#xED;a Perales,
  | una gota de agua en un cristal.</c.vtt_yellow>
  | </p>
  |  
  | <p data-config='{"init":6.2}'>
  | <c.vtt_yellow>Cada uno tenemos nuestra definici&#xF3;n,
  | aunque por supuesto,</c.vtt_yellow>
  | </p>
  |  
  | <p data-config='{"init":9.28}'>
  | <c.vtt_yellow>Perales sienta c&#xE1;tedra.
  | Estoy hablando del amor cort&#xE9;s,</c.vtt_yellow>
  | </p>
  |  
  | <p data-config='{"init":12.56}'>
  | <c.vtt_yellow>el que para algunos autores
  | surgi&#xF3; en la Edad Media.</c.vtt_yellow>
  | </p>
  |  
  | <p data-config='{"init":15.76}'>
  | <c.vtt_yellow>Los trovadores le cantaban a un amor
  | noble y puro frente al matrimonio,</c.vtt_yellow>
  | </p>
  |  
  | <p data-config='{"init":19.08}'>
  | <c.vtt_yellow>que entonces no era m&#xE1;s
  | que un arreglo entre familias.</c.vtt_yellow>
  | </p>
  |  
  | <p data-config='{"init":22.16}'>
  | <c.vtt_yellow>Luego llegaron
  | las novelas rom&#xE1;nticas del XIX,</c.vtt_yellow>
  | </p>
```
