### ISSUE TITLE
LnkGo URL scheme changed, "Unsupported URL" error

### ISSUE THREAD

**Issue by mrplumber** [ytdl-org/youtube-dl#16834]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://lnk.lt/video/greiti-pietus-ar-rusija-laimes-politiskai/36401
- Single video: https://lnk.lt/video/neigalieji-tv-bokste/37413
- Playlist: no playlist feature.

---

### Description of your *issue*, suggested solution and other information

lnkgo.lt domain now redirects to lnk.lt domain

**Comment by web-party** [comment]
👍

**Comment by r-pankevicius** [comment]
@web-party , @mrplumber 

As I saw some time ago, they switched to pure JavaScript based player. Something too heavy-metal to parse. Or tell me otherwise if we have such extractors in youtube-dl. I don't want to employ javascript engine like v8 just to do master-crawling untill they change something.

So if they don't want to be downloaded and mixed-in by folks, f**k them off.

I'd suggest to delete youtube_dl/extractor/lnkgo.py and live without it.
