### ISSUE TITLE
How to login to vlive.tv to download paid contents?

### ISSUE THREAD

**Issue by hjeondv** [ytdl-org/youtube-dl#16887]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

I'm trying to download a video on vlive.tv. In vlive.tv, there are channel+, where only a paid user can view the contents, similar to youtube red(now premium). 

However, this sites supports multiple logins like Naver, Line, Facebook, and Twitter. I currently login via facebook. Just typing in my facebook email address, it doesn't work.

```
PS C:\Users\Administrator\Downloads> .\youtube-dl.exe -u myemail@gmail.com https://www.vlive.tv/video/66178
Type account password and press [Return]:
[vlive] 66178: Downloading webpage
ERROR: Coming soon!
PS C:\Users\Administrator\Downloads>
```

Any suggestions?

**Comment by socialily** [comment]
you wouldn't be able to do anything since youtube-dl doesnt support vplus content :(

**Comment by socialily** [comment]
because: cookies don't import well (or i'm messing something up) and: they are drm protected

**Comment by hjeondv** [comment]
@socialily 

Thanks for your reply. However, the vlive CH+ contents are NOT DRM protected.

```
https://globalv-rmcnmv.akamaized.net/global/read/global_v_2018_07_04_213/5d83267e-7f1f-11e8-9ebf-0000000041ed.mp4?__gda__=(PRIVATE)
```

This is a sample URL of CH+ content. I hided the last few part because that's the access key to view that url. I can download a regular mp4 using a chrome extension(Free Video Downloader). However, it will be so hard to do the same thing like 50 times to download them all.

As you said, I found it is not possible to download them via youtube-dl. (native auth, cookies don't work.)

Anyway, thanks for your interest.

**Comment by hjeondv** [comment]
@socialily 

Just login(the ID must be subscribed to CH+ you want to view), and go to the video you want to download.

Assuming your are using chrome, just press F12 for chrome developer tools, and go to the Elements tab.

You can get the url of the video.

**Comment by hymiyalee** [comment]
OMG can't believe I find this.
I am working on download the video I already paid.

**Comment by hymiyalee** [comment]
I have downloaded the youtube-dl and tried with it to download videos from youtube, worked well.
But... how can I get the paid content's url in Vlive?

**Comment by afrinaad** [comment]
@hjeondv  the latest vlive seems like there is no url for the video right?

**Comment by anaryax** [comment]
You can't download the video with a direct link to the video. If you use your browser you can find the m3u8 playlist and attempting to download it will fail, too, but youtube-dl is able to download individual TS files if you add  `?__gda__=(PRIVATE)` to each of them. I don't know if this is of any help, but if it was possible to take `?__gda__=(PRIVATE)` from the playlist URL and then add it to the files of the playlist downloading would be possible.

Right now you can download all TS files and use ffmpeg to concat, but vtt subtitles probably won't work.

**Comment by zhuppyra** [comment]
@hjeondv i've found the url to ch+ video i'd like to download but when i put the link into youtube-dl it gave me error 403 forbidden message. can you help me with this?

**Comment by biwubo** [comment]
If anyone has a CH+ account and wants to see support added for downloading CH+ videos to youtube-dl then please email me if you're willing to share your account details. My email is biwubo@protonmail.com
