### ISSUE TITLE
Georestrictions on France.tv: How to use the BROWSER PLUGIN PROXY in my YT command lines?

### ISSUE THREAD

**Issue by NiesmialyGosc** [ytdl-org/youtube-dl#16937]
Hi ALL,

Hope this post finds you well!

I need to bypass the geo-restriction to download videos from France.TV.. but **sometimes none** of the proxies listed on this page http://spys.one/free-proxy-list/FR/ works for me!

This was a sample of my attempts:

D:\MOVIE\TOOLS&BATCHFILES\AUDIO\SERIAL\VIDEOS\ffmpeg\bin>youtube-dl --proxy 51.2
55.235.168:80 https://www.france.tv/france-2/parents-mode-d-emploi/542731-emission-du-lundi-2-juillet-2018.html
[FranceTVSite] 542731-emission-du-lundi-2-juillet-2018: Downloading webpage
**ERROR: Unable to download webpage: <urlopen error timed out> (caused by URLError (timeout('timed out',),))**

(Socks5 proxies e. g. "youtube-dl **--proxy socks5://87.117.120:10080** https://www.france.tv/france-2/parents-mode-d-emploi/542731-emission-du-lundi-2-juillet-2018.html" don't work either. NOTE I've highlighted **sometimes**. I just wonder if this occasional issue can be eliminated by using the browser plugin VPN so that I don't have to keep seeking a different proxy.)

This browser plugin VPN: SetupVPN (see screenshot below; Here's the [GOOGLE APP link)](https://chrome.google.com/webstore/detail/setupvpn-lifetime-free-vp/oofgbpoabipfcfjapgnbbjjaenockbdp) does allow me to **WATCH videos** from the site: https://www.france.tv/france-2/parents-mode-d-emploi/542731-emission-du-lundi-2-juillet-2018.html
![setupvpn](https://user-images.githubusercontent.com/40756687/42432468-40307d86-837d-11e8-9c47-30b33dd13067.png),
However, it only controls the connectivity through browser, and you know it doesn't work when I want to **DOWNLOAD videos** from there.

Is it possible at all to **PROXY FROM MY BROWSER PLUGIN SetupVPN when typing YOUTUBE-DL command lines**? If yes, how? (I know SetupVPN has a separate app to serve as a system-wide proxy but I've got some errors with a newly installed package and meanwhile I can't seem to fix it, so this is not an option for me now) What command should I use? Is it something like "youtube-dl socks5://127.0.0.1:1080" ? But no luck either. Please HELP!

Many thanks!
NiesmialyGosc

**Comment by dstftw** [comment]
You can't use browser plugins with youtube-dl.
