### ISSUE TITLE
YT does not work for SixPlay videos that require login credentials

### ISSUE THREAD

**Issue by NiesmialyGosc** [ytdl-org/youtube-dl#16949]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

D:\MOVIE\TOOLS&BATCHFILES\AUDIO\SERIAL\VIDEOS\ffmpeg\bin>youtube-dl --proxy 51.1
5.121.195:3128 --verbose --username xxx@gmail.com https://www.6play.fr/legends-p_5814/saison-1-episode-1-c_11566636
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', '51.15.121.195:3128', '--verbose', '--use
rname', 'PRIVATE', 'https://www.6play.fr/legends-p_5814/saison-1-episode-1-c_115
66636']
Type account password and press [Return]:***
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.07.10
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-89508-g1f1207145a, ffprobe N-89508-g1f1207145a
[debug] Proxy map: {'http': '51.15.121.195:3128', 'https': '51.15.121.195:3128'}

[6play] 11566636: Downloading JSON metadata
ERROR: Unable to download JSON metadata: '' (caused by BadStatusLine("''",)); pl
ease report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\extractor\common.py", line 599, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\utils.py", line 1102, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1279, in connect
  File "C:\Python\Python34\lib\http\client.py", line 874, in connect
  File "C:\Python\Python34\lib\http\client.py", line 852, in _tunnel
  File "C:\Python\Python34\lib\http\client.py", line 356, in _read_status

---

### Description of your *issue*, suggested solution and other information

1, I've used 51.15.121.195:3128 (which is a French proxy I've found on http://spys.one/free-proxy-list/FR/) to bypass the geo-blocking on https://www.6play.fr, but it might expire so please replace it with any French proxy you know that works.

2, The following video *is* available online but it requires you to log in to the 6play site with your Gmail credential:
https://www.6play.fr/legends-p_5814/saison-1-episode-1-c_11566636
So please could you replace the email address after "--username" with your actual Gmail address for the test..

Btw, after this issue has been fixed, for some reasons **may I ask for a portable .exe file for windows: youtube-dl.exe** instead of a package of python scripts which requires installation? Or could you please tell me how I can run these scripts in my Windows OS at workspace without any additional authorization? I don't think busybox would do the trick, true?

Thank you!
NiesmialyGosc

**Comment by dirkf** [comment]
If the same result occurred using cookies, see #24967.
Closing for age.
