### ISSUE TITLE
buildseries.com fails to find video file 

### ISSUE THREAD

**Issue by nopedd** [ytdl-org/youtube-dl#16947]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

This site does not download auy video just small file, it fails to get the video

youtube-dl --no-check -v https://www.buildseries.com/video/5b43b33fdbaab32daa090d27/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check', '-v', 'https://www.buildseries.com/video/5b43b33fdbaab32daa090d27/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.07.10
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] 5b43b33fdbaab32daa090d27: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 5b43b33fdbaab32daa090d27: Downloading webpage
[generic] 5b43b33fdbaab32daa090d27: Extracting information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://delivery.vidible.tv/video/redirect/5b43b3
3fdbaab32daa090d27.mp4?bcid=56e9e5c0ff690c1d9008d4e6&amp;w=1280&amp;h=720&amp;en
c=mp4&amp;domain=cdn.vidible.tv'
[download] Destination: Jake Weary Discusses TNT's 'Animal Kingdom'-5b43b33fdbaa
b32daa090d27.mp4
[download] 100% of 1.11KiB in 00:00

same also for uk site https://www.buildseries.com/uk/

**Comment by bato3** [comment]
HINT: 
It's probably videos from AOL, embed is:
```html
<!-- TAG START { player: "TEST - BUILD - with related", owner: "AOL BUILD", for: "AOL BUILD" } -->
          <div id="57f3bdfba01b4d76c57c2282" class="vdb_player vdb_57f3bdfba01b4d76c57c228256e9e5c0ff690c1d9008d4e6">
            <script async type="text/javascript" src="//delivery.vidible.tv/jsonp/pid=57f3bdfba01b4d76c57c2282/vid=5b43b33fdbaab32daa090d27/56e9e5c0ff690c1d9008d4e6.js"></script>
          </div>
```
and second for this same video:
```html
<!-- TAG START { player: "Embed Player", owner: "Embed Company", for: "Embed" } -->
<div class="vdb_player vdb_5688f66de4b040e17d9912265688f5c1e4b0f2c97f395156" 
  vdb_params="m.refbcid=56e9e5c0ff690c1d9008d4e6&m.refpid=57f3bdfba01b4d76c57c2282">
    <script type="text/javascript" src="//delivery.vidible.tv/jsonp/pid=5688f66de4b040e17d991226/vid=5b43b33fdbaab32daa090d27/5688f5c1e4b0f2c97f395156.js"></script>
</div>
<!-- TAG END { date: 07/14/18 } -->
```

**Comment by bato3** [comment]
@dstftw time to add AOL to generic: https://github.com/rg3/youtube-dl/search?q=vidible&unscoped_q=vidible

**Comment by remitamine** [comment]
redirects to yahoo.com.
