### ISSUE TITLE
Site support request https://es.dplay.com/

### ISSUE THREAD

**Issue by holaznog** [ytdl-org/youtube-dl#16969]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.07.10
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- Single video: https://es.dplay.com/dmax/la-fiebre-del-oro/temporada-8-episodio-1/

youtube-dl.exe -f best --verbose "https://es.dplay.com/dmax/la-fiebre-del-oro/temporada-8-episodio-1/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--verbose', 'https://es.dplay.com/dmax/la-fiebre-del-oro/temporada-8-episodio-1/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.07.10
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91470-g28ed68fa31, ffprobe N-91470-g28ed68fa31
[debug] Proxy map: {}
[generic] temporada-8-episodio-1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] temporada-8-episodio-1: Downloading webpage
[generic] temporada-8-episodio-1: Extracting information
ERROR: Unsupported URL: https://es.dplay.com/dmax/la-fiebre-del-oro/temporada-8-episodio-1/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\extractor\generic.py", line 3258, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://es.dplay.com/dmax/la-fiebre-del-oro/temporada-8-episodio-1/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by anonbeat** [comment]
the class DPlayItIE in the extractor dplay.py supports this site but a change for the url is needed. I tested changing 'it' to 'es' and it worked. It should be very simple to add support for it.

**Comment by MttCastelli** [comment]
Downloading from DPlayIt seems to work, except for this error:
WARNING: unable to extract series

Complete log prompt, I've just replaced media content with '...'. :
`
PS C:\Users\Matteo\Desktop> youtube-dl.exe -U
youtube-dl is up-to-date (2018.12.09)
PS C:\Users\Matteo\Desktop>PS C:\Users\Matteo\Desktop> youtube-dl.exe https://it.dplay.com/... -f hls-3330
[DPlayIt] ...: Downloading webpage
[DPlayIt] ...: Downloading JSON metadata
[DPlayIt] ...: Downloading m3u8 information
WARNING: unable to extract series; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract episode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 428
[download] Destination: ....mp4
[download]  81.6% of ~1.72GiB at 11.64MiB/s ETA 01:11`


Regards

**Comment by Mecawento** [comment]
Hello if there is anybody here it is not working...

Test:
Windows 7 SP1 x64 in command prompt with admin rights
Python 3.7.3
youtube-dl==2019.4.7

youtube-dl.exe -f best --verbose "https://es.dplay.com/dkiss/cinco-por-sorpresa/temporada-3-episodio-1/"

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--verbose', 'https://es.dplay.com/dkiss/cinco-por-sorpresa/temporada-3-episodio-1/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.09.10
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-93147-g9326117bf6, ffprobe N-93147-g9326117bf6, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] temporada-3-episodio-1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] temporada-3-episodio-1: Downloading webpage
[generic] temporada-3-episodio-1: Extracting information
ERROR: Unsupported URL: https://es.dplay.com/dkiss/cinco-por-sorpresa/temporada-3-episodio-1/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://es.dplay.com/dkiss/cinco-por-sorpresa/temporada-3-episodio-1/

Thank you anyway!

**Comment by felisucoibi** [comment]
Hi @Mecawento it says y9ou are using other version becuse you are using other version.
There is a pr waiting to make es.dplay.com work again but not merged since 1 year ago.

**Comment by felisucoibi** [comment]
Its broken new api for dplay.com
