### ISSUE TITLE
Problems with automatically setting the video's mtime to the server's modification time

### ISSUE THREAD

**Issue by epitron** [ytdl-org/youtube-dl#1709]
Youtube-DL recently changed its behaviour in a way that broke how I was using it. It used to set the `mtime` to when the file was downloaded; now it's set to when the file was uploaded to the video site.

This means that I can't sort my videos by download time anymore. It's problematic when you have a large download directory, or multiple collections, which you slowly process over time.

The only other downloader I've found with this default behaviour is `wget`. All the other downloaders -- browsers, torrent programs, curl, scp -- set the `mtime` to the time that you downloaded the file. (This is the [the definition of mtime](https://en.wikipedia.org/wiki/Mtime).)

I can see how people would want to save the video creation date. Luckily, there's a pull request in the pipeline (#1708) that writes this information -- _and more_ -- to the file's xattrs.

So, you can have it all: files sorted by download date, and their creation date!

How 'bout it?

**Comment by SS64** [comment]
I think you can argue this either way, but it confused me at first having the download file's date/time appear to be wrong, in most cases the date always seems to be about 23 hours ago for some reason - would be nice if the --no-mtime option was a little more prominent in the docs/online help.

**Comment by epitron** [comment]
I think the strongest argument is that every other program (except wget) sets the mtime to the current time, and the ctime to the remote file's time. 

Knowing the order you downloaded files in a directory helps you process them more easily.

**Comment by dsoprea** [comment]
+1 on all (changing the default, setting the ctime to this value instead of the ctime, setting the xattrs).

**Comment by yan12125** [comment]
+1 for making ```--no-mtime``` as the default. IMO youtube-dl is a video/audio downloader. All other actions besides downloading the _contents_ of video/audio streams shouldn't be there unless explicitly requested.

> setting the xattrs

-1 on this. xattrs shouldn't be added without ```--xattrs```

**Comment by dsoprea** [comment]
In keeping consistent with your remarks, I understand where you are coming
from.

I'm indifferent, though setting these doesn't operationally or visually
interfere with anyone or anything (so we might as well).



Dustin

**Comment by untotren** [comment]
+1

**Comment by allanlaal** [comment]
+1

I was expecting this behaviour and completely lost track of what I've downloaded because it was using random mtime dates for files

**Comment by NickSto** [comment]
+1 million

I think having the default date modified be the upload date violates the principle of least astonishment, since most tools set it to the current time. People will assume it operates like most other tools, as I did, and it can cause real problems.

I went years without realizing what it was actually doing. I really like to have a record of when I first found and downloaded a video, and now there's years of videos I've saved where I have no idea what period of my life they're from. The worst part is, it effectively poisoned the date modifieds on all the videos downloaded before that as well. If I see a video with a date from before that period, I don't know if it's actually from then, or if it's one downloaded with youtube-dl with a date that artificially put it back then.

It wasn't until I was trawling through the list of options and saw `--no-mtime` that I realized what happened. At the very least, I'd recommend putting a note somewhere prominent about what the default date modified will be.

**Comment by polonskiy** [comment]
`--no-mtime` definitely should be default.
I have almost deleted new videos with `find /youtube -type f -mtime +7 -delete`.

**Comment by SS64** [comment]
The current behaviour would make sense if the server time related to the original video's creation date, but it's not. I'm not even sure that it is reliably related to the upload date?

**Comment by graywolf** [comment]
I'm not sure if you are counting votes or anything, but `+1` for this. I've just out of habit tried `ls -rtl` to find the downloaded video from youtube and was bit confused it was nowhere to be find.

While `--mtime` could be possible handy, I think vast majority of people would expect `--no-mtime` to be the default, same way as other downloaders work.

But that's just, like, my opinion `^_^`

**Comment by shivdhar** [comment]
+1 for `--no-mtime` to be the default, and `--xattrs` and, in fact, `--add-metadata` too.

These are flags that add information without breaking anything AFAIK, which is a good thing and definitely should be on by default. 

`--mtime` by default is just plain confusing.

**Comment by yomajo** [comment]
Problem: music folder is arranged by last modified, so latest downloaded songs are at the top. Currently youtube-dl messes this up using last modified which is ~5days off.

Suggestion: **use scrape timestamp instead of headers**.

**Comment by dirkf** [comment]
What is a potential bug is that `--no-mtime` exists but there is no `--mtime` to override that if set as a default in a site or user config. Until this is fixed the advice that, if you like `--no-mtime`, you can make it the default, is not completely sound.
```diff
--- old/youtube_dl/options.py
+++ new/youtube_dl/options.py
@@ -734,8 +734,12 @@
         action='store_true', dest='nopart', default=False,
         help='Do not use .part files - write directly into output file')
     filesystem.add_option(
+        '--mtime',
+        action='store_true', dest='updatetime', default=True,
+        help='Use the Last-modified header to set the file modification time (default)')
+    filesystem.add_option(
         '--no-mtime',
-        action='store_false', dest='updatetime', default=True,
+        action='store_false', dest='updatetime',
         help='Do not use the Last-modified header to set the file modification time')
     filesystem.add_option(
         '--write-description',
```
Then:
```console
$ python -m youtube_dl --help
...
  Filesystem Options:
...
    --mtime                              Use the Last-modified header to set
                                         the file modification time (default)
    --no-mtime                           Do not use the Last-modified header to
                                         set the file modification time
...
$ devscripts/cli_to_api.py --no-mtime --mtime
{}
$
```

**Comment by dirkf** [comment]
Finally, on platforms with POSIX _touch_, you could use `--exec touch -m {}` to set the file modification time to the current (ie, download) time, or in Windows _cmd_ use [some other hack](https://ss64.com/nt/touch.html) with `--exec ...`.
