### ISSUE TITLE
[Crunchyroll] Cannot download video and subtitles with an account (Says Preview Video)

### ISSUE THREAD

**Issue by RGFRv2** [ytdl-org/youtube-dl#17115]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

**case 1 - With a premium account on a premium video**
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-f', u'[height=720]', u'--write-sub', u'--sub-format', u'ass', u'--sub-lang', u'frFR', u'http://www.crunchyroll.com/oneroom/episode-4-hanasaka-yui-is-near-me-774694']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.29
[debug] Python version 2.7.9 (CPython) - Linux-3.16.0-4-amd64-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 2.6.9, ffprobe 2.6.9, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 774694: Downloading webpage
ERROR: Ceci est un extrait. Pour visionner la vidéo en entier,  testez gratuitement notre offre !!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/crunchyroll.py", line 429, in _real_extract
    raise ExtractorError(note_m)
ExtractorError: Ceci est un extrait. Pour visionner la vid\xe9o en entier,  testez gratuitement notre offre !!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**case 2 - With a premium account on a free video**

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-f', u'[height=720]', u'--write-sub', u'--sub-format', u'ass', u'--sub-lang', u'frFR', u'http://www.crunchyroll.com/oneroom/episode-3-hanasaka-yui-is-sulking-774693']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.29
[debug] Python version 2.7.9 (CPython) - Linux-3.16.0-4-amd64-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 2.6.9, ffprobe 2.6.9, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 774693: Downloading webpage
ERROR: crunchyroll returned error: The CSRF token is invalid. Please try to resubmit the form.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/crunchyroll.py", line 435, in _real_extract
    raise ExtractorError('crunchyroll returned error: %s' % msg['message_body'], expected=True)
ExtractorError: crunchyroll returned error: The CSRF token is invalid. Please try to resubmit the form.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Premium video : http://www.crunchyroll.com/oneroom/episode-4-hanasaka-yui-is-near-me-774694
- Free video: http://www.crunchyroll.com/oneroom/episode-3-hanasaka-yui-is-sulking-774693

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

(Sorry about my English)

Hi,

I have a problem when I launch Youtube-dl to download a video on Crunchyroll.

- When I launch a premium video with a premium account, it gives me the case 1.

- When I launch a free video with a premium account, it gives me case 2.

- When I launch a free video without an account, it works to download the video and subtitles.

Any idea how to solve this ?

**Comment by RGFRv2** [comment]
I'll try that, thanks.

**Comment by kenichi512** [comment]
I updated my cookies and my User Agent but the result is the same.

**Comment by calvinc64** [comment]
For your Info, I Used following command: `youtube-dl --no-check-certificate --recode-video mp4 --cookies cookies.txt --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36" --all-subs URL`

This worked for me (The Browser String must be the same as your Browser) 
Like I Said @RGFRv2 I've exported the cookies from the browser where I am allready did go through the process of Cloudflare and Login with account and password.

Because the Login is stored in the cookies, you can access all Episodes without Username and Password.

**Comment by kenichi512** [comment]
I added the --no-check-certificate and I tried to have the rest of the data correctly, but the result does not change.

[Crunchyroll] Logging in
[Crunchyroll] 776051: Downloading webpage
ERROR: crunchyroll returned error: The CSRF token is invalid. Please try to resubmit the form.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\crunchyroll.py", line 435, in _real_extract
youtube_dl.utils.ExtractorError: crunchyroll returned error: The CSRF token is invalid. Please try to resubmit the form.

**Comment by calvinc64** [comment]
ok have you tried youtube-dl -U before?

Maybe you're not up to date... the newest version did work for me when I wrote the commend.

**Comment by kenichi512** [comment]
updated to version 2018-08-04 last Wednesday 8. I checked again recently and there was no new version.

**Comment by kenichi512** [comment]
It really is sad. Even before it was possible to enter the user data and you could have access to premium content. Now, not even that.

**Comment by Abu3safeer** [comment]
So that means I have to get cookies from browser? so -u and -p flags has no use?

**Comment by calvinc64** [comment]
Actually the current version should not work anymore because of a change in the player from flash to html5 but you can get the .m3u8 from the vilos.config.media array when youre on the video site and then export it with vlc player.

**Comment by Abu3safeer** [comment]
To be honest I wanted to get use of downloading video and subtitle and mix them into one mkv file, so I don't have to do anything.

The thing is ffmpeg is no longer working with m3u8, I don't know why, but it keeps throwing error messages even if I put m3u8 link directly in the command.

So alternatively I am using youtube-dl until I find a solution for ffmpeg.

**Comment by calvinc64** [comment]
> 
> 
> To be honest I wanted to get use of downloading video and subtitle and mix them into one mkv file, so I don't have to do anything.
> 
> The thing is ffmpeg is no longer working with m3u8, I don't know why, but it keeps throwing error messages even if I put m3u8 link directly in the command.
> 
> So alternatively I am using youtube-dl until I find a solution for ffmpeg.

Ah no just open the first M3U8 with an Text-Editor and copy the fitting link for you (e.g. the 1920x1080 one) and then it should work. Just tried to use them in VLC and everything worked. by the way this is the only way why I want the Media directly, because I want to stream them in VLC ;D

**Comment by Abu3safeer** [comment]
> Ah no just open the first M3U8 with an Text-Editor and copy the fitting link for you (e.g. the 1920x1080 one) and then it should work. Just tried to use them in VLC and everything worked. by the way this is the only way why I want the Media directly, because I want to stream them in VLC ;D

My internet is not fast enough to stream directly, I should download media to have good watching experience.
