### ISSUE TITLE
https://nrk.radio.no not working

### ISSUE THREAD

**Issue by OiPenguin** [ytdl-org/youtube-dl#17112]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```

$ youtube-dl -v https://radio.nrk.no/serie/transmission#t=33m55.84s
[debug] System config: []
[debug] User config: [u'--no-mtime', u'-o', u'~/Videos/YouTube-DL/%(title)s-%(id)s.%(ext)s', u'--write-thumbnail', u'--sub-format', u'srt', u'--all-subs', u'--convert-subs', u'srt', u'--add-metadata']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://radio.nrk.no/serie/transmission#t=33m55.84s']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.29
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-29-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2
[debug] Proxy map: {}
[NRKTVSeries] transmission#t=33m55.84s: Downloading webpage
WARNING: unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract OpenGraph description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: transmission#t=33m55.84s
[NRKTVSeries] playlist transmission#t=33m55.84s: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: transmission#t=33m55.84s
lars@Lars-Yoga-720:~$ 
```

### Description of your *issue*, suggested solution and other information

https://radio.nrk.no is the hub of radio shows by the main Norwegian broadcaster. According to https://rg3.github.io/youtube-dl/supportedsites.html this is a supported site.  The TV-arm at https://tv.nrk.no works great, however I get the above error when attempting to download radio shows.

**Comment by barsnick** [comment]
This is identical to #21926 and others: Radio playlists currently return 0 items. Some of those tickets were closed as duplicates for #18304, which basically describes the totally changed site. You can still - or again - download single episodes.

BTW, the URL in this issue's title is wrong and misleading. "https://nrk.radio.no" -> "https://radio.nrk.no".
