### ISSUE TITLE
CrunchyRoll Download says preview of video

### ISSUE THREAD

**Issue by 619beave** [ytdl-org/youtube-dl#17116]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.07.29
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by bato3** [comment]
possible duplicate https://github.com/rg3/youtube-dl/issues/17115

(Probably crunchroll disable RCP - Login)

**Comment by 619beave** [comment]
The weird thing is that it worked earlier this morning.

**Comment by RGFRv2** [comment]
Same problem. 
 
So there's a solution?

**Comment by bato3** [comment]
I have different error, but I'm think it is similar cuse:
```
ERROR: Wrong login info: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Moved Temporarily (caused by HTTPError());
```

Original login procedure only make request to RCP-login-page, and don't check is login was OK

I can't get your error, but:

- install python
- download my fix https://github.com/bato3/youtube-dl/tree/crunchroll2
- run by `youtube-dl>python -m youtube_dl`

**Comment by RGFRv2** [comment]
I have this by running the command with your fix: 

`python -m youtube_dl --verbose -u USER -p PASS --skip-download --write-sub --sub-format "ass" --sub-lang "frFR" http://www.crunchyroll.com/oneroom/episode-4-hanasaka-yui-is-near-me-774694`

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--skip-download', u'--write-sub', u'--sub-format', u'ass', u'--sub-lang', u'frFR', u'http://www.crunchyroll.com/oneroom/episode-4-hanasaka-yui-is-near-me-774694']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.21
[debug] Python version 2.7.9 (CPython) - Linux-3.16.0-4-amd64-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 2.6.9, ffprobe 2.6.9, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/youtube-dl-master/youtube_dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "youtube_dl/__init__.py", line 472, in main
    _real_main(argv)
  File "youtube_dl/__init__.py", line 462, in _real_main
    retcode = ydl.download(all_urls)
  File "youtube_dl/YoutubeDL.py", line 2001, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 501, in extract
    self.initialize()
  File "youtube_dl/extractor/common.py", line 405, in initialize
    self._real_initialize()
  File "youtube_dl/extractor/crunchyroll.py", line 118, in _real_initialize
    self._login()
  File "youtube_dl/extractor/crunchyroll.py", line 75, in _login
    cf_page = self.cf_solve_and_download_webpage(login_page, self._LOGIN_URL)
AttributeError: 'CrunchyrollIE' object has no attribute 'cf_solve_and_download_webpage'

```

**Comment by bato3** [comment]
@RGFRv2 it look you don't have this: https://github.com/bato3/youtube-dl/blob/crunchroll2/youtube_dl/extractor/common.py#L2821-L2877

I get fresh copy, and this work for me. (Sometimes on second run - I don't know why sometimes on _get token_ crunchy returns second challegne)

**Comment by Rikku1990** [comment]
@bato3, I have the same problem as @RGFRv2 , could you please post an example so that we / I understand how exactly this should work?

**Comment by RGFRv2** [comment]
@bato3 
It's working! 

This modification will be added in a new version of Youtube-DL? 
Because right now, I can't run my scripts normally :/

@Rikku1990 

It is necessary to clone the branch "crunchroll2" of the git of bato3 https://github.com/bato3/youtube-dl/tree/crunchroll2

Here is the command :

git clone -b crunchroll2 --single-branch https://github.com/bato3/youtube-dl.git

```
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.29
[debug] Git HEAD: 1659616
[debug] Python version 2.7.9 (CPython) - Linux-3.16.0-4-amd64-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 2.6.9, ffprobe 2.6.9, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] Solving Cloudflare challenge (5s)
[Crunchyroll] Sending Cloudflare challenge
[Crunchyroll] Get new CSRF Token
[Crunchyroll] Logging in
[Crunchyroll] 774694: Downloading webpage
[Crunchyroll] 774694: Downloading media info for 360p
[Crunchyroll] 774694: Downloading stream info for 360p
[Crunchyroll] 774694: Downloading m3u8 information
[Crunchyroll] 774694: Downloading media info for 480p
[Crunchyroll] 774694: Downloading stream info for 480p
[Crunchyroll] 774694: Downloading m3u8 information
[Crunchyroll] 774694: Downloading media info for 720p
[Crunchyroll] 774694: Downloading stream info for 720p
[Crunchyroll] 774694: Downloading m3u8 information
[Crunchyroll] 774694: Downloading media info for 1080p
[Crunchyroll] 774694: Downloading stream info for 1080p
[Crunchyroll] 774694: Downloading m3u8 information
[Crunchyroll] 774694: Downloading media info
[Crunchyroll] 774694: Downloading subtitles for English (US)
[Crunchyroll] 774694: Downloading subtitles for Español
[Crunchyroll] 774694: Downloading subtitles for Español (España)
[Crunchyroll] 774694: Downloading subtitles for Français (France)
[Crunchyroll] 774694: Downloading subtitles for Português (Brasil)
[Crunchyroll] 774694: Downloading subtitles for العربية
[Crunchyroll] 774694: Downloading subtitles for Italiano
[Crunchyroll] 774694: Downloading subtitles for Deutsch
[Crunchyroll] 774694: Downloading subtitles for Русский
[info] Writing video subtitles to: One Room (Saison 2) Épisode 4 – Yui Hanasaka est à mes côtés-774694.frFR.ass
...
```

**Comment by bato3** [comment]
@Rikku1990 Just install python, and downoad repo: https://github.com/bato3/youtube-dl/archive/crunchroll2.zip (no `git` need)

@RGFRv2 IDK when, but code need some refactoring - so not so fast. Especially, I'm just learning python. So every hint is indicated

btw - for better experience add `--cookie=cookie.txt`. This allows you to avoid the cloudflare-challenge on the "second" run

**Comment by RGFRv2** [comment]
@bato3 

For now I'll go through an alias and we'll see later.

Thanks again !

**Comment by bato3** [comment]
>    1. It should be detected and solved at generic webpage download level not in extractor.

I don't know how to do, but I would like to see how should this be do. (My Python experience is about 2 weeks)

>    2. It should not use any non public domain code.

on MIT License: https://github.com/Anorov/cloudflare-scrape/blob/master/LICENSE
enough credits

>    3. It should not use nodejs.

`cloudflare-scrape` perviously use `PyExecJS` but switched to `node`. You can still think about using `phantom`, but this one is also suspended.

**Comment by 619beave** [comment]
@RGFRv2

When will the fix be applied to the new version?  

Just wondering...

Thanks

**Comment by bato3** [comment]
@619beave according to decision @dstftw it won't. 

I hope someone else will do it better

**Comment by dystopia2017** [comment]
@RGFRv2 Hello could you provide a windows binary, or explain how to compile or run your scripts on windows. I have python installed, but when i do "python setup.py" it just errors out with

`setup.py:73: UserWarning: Skipping file youtube-dl.bash-completion since it is not present. Type  make  to build all automatically generated files.
  warnings.warn('Skipping file %s since it is not present. Type  make  to build all automatically generated files.' % `fn)``

**Comment by bato3** [comment]
@dystopia2017 this file is in ./devscripts/


they use https://github.com/rg3/youtube-dl/blob/master/devscripts/buildserver.py but I don't know details (only `wget "http://$buildserver/build/rg3/youtube-dl/youtube-dl.exe?rev=$REV" -O youtube-dl.exe`) or https://github.com/rg3/youtube-dl/blob/master/devscripts/wine-py2exe.sh

**Comment by bato3** [comment]
I'm curious how long it will work.

**Comment by leprasson** [comment]
I updated to latest windows veriosn 2018.08.04 and now i get this message :

> crunchyroll returned error : the CSRF token is invalid. please try to resubmit the form

**Comment by besweeet** [comment]
Same problem as @leprasson. That's when manually specifying the user agent and cookies.txt.

**Comment by kseniasolo** [comment]
For the moment, I use the following line and everything works.

> /usr/bin/python /home/private/youtube_dl/__main__.py -u PRIVATE -p PRIVATE -f "[height="1080"]" --write-sub --sub-format "ass"  --sub-lang "enUS" --hls-prefer-native http://www.crunchyroll.com/attack-on-titan/episode-40-old-story-776025

I'm working on linux, but I think this can work on Windows too.

**Comment by federicorosso1993** [comment]
@N0197exe  I know how to use cookies... but how do you convert that string
"/usr/bin/python /home/private/youtube_dl/main.py "
to windows?

Can someone from the development team implement kseniasolo fix (if it make sense)?

**Comment by bato3** [comment]
For my: It gave me cloudflare anti boot test on login page.

**Comment by federicorosso1993** [comment]
I tried with --cookies and user-agent and even -u PRIVATE -p PRIVATE:
 ./youtube-dl.exe -u PRIVATE -p PRIVATE --username myuser --password mypassword http://www.crunchyroll.com/gintama/episode-358-countless-kings-774987 --cookies cookies.txt --user-agent "USER-AGENT"
I still get the 
ERROR: crunchyroll returned error: The CSRF token is invalid. Please try to resubmit the form.

**Comment by N0197exe** [comment]
@federicorosso1993.
as @bato3 says:
> Just install python, and downoad repo: https://github.com/bato3/youtube-dl/archive/crunchroll2.zip

then go to the download path, in my case it is: "C:\Users\Lenovo\Downloads\youtube-dl-crunchroll2\youtube_dl" there you will find "main.py" (will have underscores)

I go to the location with the cmd and do the following example:
> main.py -u PRIVATE -p PRIVATE --verbose --cookies cookies.txt --write-sub --sub-format "ass" --sub-lang "enUS" http://www.crunchyroll.com/attack -on-titan / episode-40-old-story-776025

**Comment by federicorosso1993** [comment]
@N0197exe Ah ok, thank you.
Still it would be great to get a single .exe file... I created a small UI for my personal use (where I can get url, cookies and user-agent with one click), if I have to use main.py I need to change my code.

**Comment by 619beave** [comment]
Thanks for the help.  The PYthon script is working as:

E:\youtube-dl-crunchroll2\youtube_dl\__main__.py  -v -u PRIVATE -p PRIVATE -f "[height <=? 1080]" --sub-lang enUS --sub-format "ass" --write-sub "%1"

This is a batch file that is run from another folder where the encodes are muxed together

**Comment by freddiaN** [comment]
@bato3 I tried your fix but I got this output instead.
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--geo-bypass-country', 'US', '--username', 'PRIVATE', '--password', 'PRIVATE', '--all-subs', '--verbose', 'https://crunchyroll.com/darling-in-the-franxx']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.29
[debug] Python version 3.7.0 (CPython) - Linux-4.17.12-arch1-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg n4.0.2, ffprobe n4.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 3.230.14.11 (US) as X-Forwarded-For.
[crunchyroll:playlist] Logging in
ERROR: Unable to extract login form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/jonas/Downloads/youtube-dl-crunchroll2/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/jonas/Downloads/youtube-dl-crunchroll2/youtube_dl/extractor/common.py", line 501, in extract
    self.initialize()
  File "/home/jonas/Downloads/youtube-dl-crunchroll2/youtube_dl/extractor/common.py", line 405, in initialize
    self._real_initialize()
  File "/home/jonas/Downloads/youtube-dl-crunchroll2/youtube_dl/extractor/crunchyroll.py", line 120, in _real_initialize
    self._login()
  File "/home/jonas/Downloads/youtube-dl-crunchroll2/youtube_dl/extractor/crunchyroll.py", line 87, in _login
    login_page, 'login form', group='form')
  File "/home/jonas/Downloads/youtube-dl-crunchroll2/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract login form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by bato3** [comment]
@ freddiaN strange. This error is raised after solving cloudflare challenge.

Please add `--write-pages` and attach saved requests (eg paste it in https://pastebin.com/)

**Comment by puxlit** [comment]
I can reproduce the above error with Python 3.7 too. It seems that reading `http.client.HTTPResponse` (from `fp` of the `urllib.error.HTTPError` raised when making the initial request to `https://www.crunchyroll.com/login?next=%2Facct%2Fmembership`) yields nothing. Consequently, `has_cf_challenge` gets tested against an empty string (skipping the bulk of @bato3's contribution), and we finally bail when searching for the login token (again against that empty string).

**Comment by bato3** [comment]
I can't reproduce. I always have some HTML in response. 

@puxlit You talk about first `login_page` (is empty)? Can you try change `fail_url` to `_LOGIN_URL`.

And can you store cookies by  `--cookie` and what cookies is in?. `__cfduid` + `c_visitor` - without CF challenge, `cf_clearance` - after CF challenge, `c_d`, `c_userid`, `c_userkey` - crunchroll cookies

**Comment by puxlit** [comment]
Yes, `login_page` appears to be empty. Changing `fail_url` doesn't seem to make a difference. Only `__cfduid` and `c_visitor` appear to be set.

Your patch works fine on Python 2(.7.15) though; not sure about other versions of Python 3.

**Comment by puxlit** [comment]
Okay, it would seem that `HTTPError` closes `fp` when the error's destroyed, thanks to [bpo-15002](https://bugs.python.org/issue15002) (introduced in [Python 3.4.1](https://docs.python.org/3.4/whatsnew/changelog.html#id42)). Given that's the case, I doubt anything that relies on `_request_webpage`'s `expected_status` functionality will work.

**Comment by FoxMcloud5655** [comment]
Not that I have anything to add to the discussion, but I also encounter this error with the most recent version of youtube-dl.

**Comment by bato3** [comment]
@puxlit Can you fix it, will you report it as a new issue?

**Comment by federicorosso1993** [comment]
Still nothing changed
ERROR: crunchyroll returned error: The CSRF token is invalid. Please try to resubmit the form.

**Comment by FoxMcloud5655** [comment]
As a workaround, I've logged in using my web browser, then saved the cookies into a text file.  You can then use said cookies to "stay" logged in when you run your command on youtube-dl.

**Comment by federicorosso1993** [comment]
Ok now I know what the main problem is.
I was using --username and --password and --cookies and --user-agent.
But unlike the first time right now if you use --username and --password it will ignore -cookies and --user-agent.
I think it's better if I can use both and if one fail youtube-dl try to use the other system to log in.
I say this because if the cookies are too old the download will fail too, so you cannot ignore --username and --password if you use --cookies and --user-agent.

Right now, for my personal UI, I'm using a double download line:
./youtube-dl.exe --username myuser --password mypass http://www.crunchyroll.com/gintama/episode-358-countless-kings-774987 --cookies cookies.txt --user-agent "myagent"; ./youtube-dl.exe http://www.crunchyroll.com/gintama/episode-358-countless-kings-774987 --cookies cookies.txt --user-agent "myagent"

Of course right now the first line always fail, in the future, if the log in will be fixed, it will download the episode two times (so it's not ideal at all)... That's why I ask you if you can fix and keep in mind that "I should be able to use both method at the same time to log in"

**Comment by Kojirosan** [comment]
Its work with the last version of Youtube-dl (2018.09.01), but not for the premium video
