### ISSUE TITLE
[site support request] - **raiplayradio.it**

### ISSUE THREAD

**Issue by miguelindurain28bpm** [ytdl-org/youtube-dl#17141]
It would be nice to have a possibility to download audiobooks from **raiplayradio.it**,
for example - https://www.raiplayradio.it/playlist/2017/12/Centanni-di-solitudine-8f58783b-6ff4-4b26-b0ba-d0948b5701b2.html

**Comment by mfrasca** [comment]
more recently, radio-rai has made it impossible, to download anything from their site unless going through the site (not firefox friendly), or their apps.  first they removed their RSS feeds, and now they completely stopped putting the audio files in the old http://www.radio.rai.it/podcast/ location.

file names now look like this: blob:https://www.raiplayradio.it/63bc6362-d2cd-4326-9b21-5ccd90ec6d20, and the uuid4 string is not the same as the html page.

I'm not sure if the uuids are generated on the fly, and how long they stay valid.  I have tried manually downloading the same file I just downloaded using opera, and I got a 404 error.
