### ISSUE TITLE
HiDive "ERROR: HiDive said: PremiumContent"

### ISSUE THREAD

**Issue by Redwarz1** [ytdl-org/youtube-dl#17168]
I might just be missing something here but no matter what I do I can't get videos to download. I've tried using the raw m3u8 file and get 404 errors. 

## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.hidive.com/stream/watamote-no-matter-how-i-look-at-it-its-you-guys-fault-im-not-popular/s01e001', '--cookies', 'cookies.txt', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-90810-g153e920892, ffprobe N-90810-g153e920892
[debug] Proxy map: {}
[HiDive] None: Downloading webpage
[HiDive] Logging in
[HiDive] watamote-no-matter-how-i-look-at-it-its-you-guys-fault-im-not-popular/s01e001: Downloading JSON metadata
ERROR: HiDive said: PremiumContent
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\hidive.py", line 76, in _real_extract
youtube_dl.utils.ExtractorError: HiDive said: PremiumContent
```

**Comment by dunn** [comment]
Are you on the free trial?  Based on https://help.hidive.com/support/solutions/articles/27000018287-how-can-i-cancel-my-hidive-membership- my guess is they've blocked it for non-paying members:

> If you are a premium member and you cancel your account, your membership will be active until the end of your billing cycle. 
> 
> If you are a free trial customer you will immediately lose access to HIDIVE premium services.

**Comment by darkhelmet2016** [comment]
It no longer works as they have changed the api again.

**Comment by ThomasLech** [comment]
Hello, did anybody get it to work? We're paying for our HIDIVE account every month and we're experiencing the same issue.

Thanks in advance!

**Comment by YewTreeWeb** [comment]
Hi @ThomasLech I had the same issue but got it to work with `youtube-dl https://www.hidive.com/stream/farming-life-in-another-world/s01e001 --user-agent "Mozilla/5.0" --cookies "www.hidive.com_cookies.txt" --referer "https://www.hidive.com/stream/farming-life-in-another-world/s01e001"` You can't use `-u` or `-p` and instead a generated cookie.txt file while you're logged into the HIDIVE site. I use 'GET cookies.txt LOCALLY' extension to download them. Hope this helps

**Comment by dirkf** [comment]
Continued in #32441.
