### ISSUE TITLE
[Crunchyroll] ERROR: Wrong login info: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.

### ISSUE THREAD

**Issue by justLetMeSubmitABugReport** [ytdl-org/youtube-dl#17190]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
user@laptop ~ $ youtube-dl http://www.crunchyroll.com/my-hero-academia/episode-54-shiketsu-high-lurking-775773 -u USERNAME -p PASSWORD -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.crunchyroll.com/my-hero-academia/episode-54-shiketsu-high-lurking-775773', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-34-generic-x86_64-with-LinuxMint-18-sarah
[debug] exe versions: ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
ERROR: Wrong login info: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Moved Temporarily (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 599, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 644, in http_error_302
    self.inf_msg + msg, headers, fp)
...
<end of log>
```

---

---

### Description of your *issue*, suggested solution and other information

The username and password is correct, but it says "Wrong login info". This was working fine as of July 27th, but now I am unable to download anything from Crunchyroll.

It looks like this same issue is referenced here: https://github.com/rg3/youtube-dl/issues/17116#issuecomment-409188539

I haven't tested the fix mentioned in that comment, but it would be nice if youtube-dl could be updated to officially fix the issue. Thank you.

**Comment by noobmagnet** [comment]
Getting this error on version **2018.08.04**

**Comment by nascalsn** [comment]
Getting this error on version **2018.09.26**

**Comment by nascalsn** [comment]
Getting this error on version **2018.10.05**

**Comment by remitamine** [comment]
https://github.com/rg3/youtube-dl#how-can-i-speed-up-work-on-my-issue

**Comment by shinji257** [comment]
Please only contribute in this thread (don't just issue bump) please!

Anyways I did some digging on this issue.  It looks like the issue is here during the CrunchyRoll login.

crunchyroll.py -- Line 59-67
```python
    def _login(self):
        username, password = self._get_login_info()
        if username is None:
            return

        self._download_webpage(
            'https://www.crunchyroll.com/?a=formhandler',
            None, 'Logging in', 'Wrong login info',
            data=urlencode_postdata({
                'formname': 'RpcApiUser_Login',
                'next_url': 'https://www.crunchyroll.com/acct/membership',
                'name': username,
                'password': password,
            }))
```

When I attempt to run that url manually even the browser shows 302 redirects happening in a loop which it eventually halts.  This looks like a change on CrunchyRoll ends for how the authentication should be happening.  What I'm not understanding is why it works fine for Windows and not on Linux since authentication would be happening the same way for both.

Changing the parameters doesn't seem to work... yet.

Watching headers shows the login form is posting the following parameters back to itself (I think).
login_form[name] (username)
login_form[password] (password)
login_form[redirect_url] (redirect url)
login_form[_token] (a seemingly random token -- it changes each load)

As of right now changing the parameters at the function noted above stops the 302 loop but also doesn't login successfully.

**Comment by bato3** [comment]
@shinji257 You use `requests.Session` to get login page. But you import only CloudFlare cookies. I'm thinking, that you should import _crunchy_ session. You get `login_form[_token]` in different session that you send it.

BTW: 
1. `RpcApiUser_Login` for some users works OK, but `crunchyroll.com/login` always raise cf-challenge. Your changes disable login feature for all users without `cfscrape`.
1. Why you run cfscrape before checking is `username` provided?
2. Use `login_form = self._form_hidden_inputs(self._LOGIN_FORM, page)` instead `BeautifulSoup`
3. Are you aware that you are not checking if you logged in correctly?
4. Is it possible that `requests.Session` stores the last response? (In `scraper.get_token` you get login form, but in next line you get )
5. Sometimes I had problems when I tried to log in and I had an active session from a previous call (`--cookie=cookie.txt`). And if you download the login page anyway, you should check if you are logged in. (If you do not do it, you may not get the login form and `_token`)
6. You make some [strange changes](https://github.com/shinji257/youtube-dl/commit/db6228a679b749bc3139d343788789aa5b0cf5b8) in `README.md`
