### ISSUE TITLE
Youtube: authentication failure

### ISSUE THREAD

**Issue by HPP8140** [ytdl-org/youtube-dl#17216]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u':ytwatchlater', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-s', u'-j', u'--flat-playlist', u'--write-pages']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.9 (CPython) - Linux-3.14.0-kirkwood-tld-1-armv5tel-with-debian-8.10
[debug] exe versions: avconv 11.11-6, avprobe 11.11-6, ffmpeg 0.8.21-6
[debug] Proxy map: {}
WARNING: Unable to login: Invalid password
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2801, in _real_extract
    _, playlist = self._extract_playlist('WL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2316, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist does not exist.
...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. 

Youtube fails to authenticate. Looks like the sign-in page has been redesigned again. Previous reference: https://github.com/rg3/youtube-dl/issues/12973

**Comment by HPP8140** [comment]
Got presented with verification on another desktop machine logging into gmail. Now the login on the linux box running the app above is able to login again.

**Comment by KrumpetPirate** [comment]
Having much the same issue here. Been happening for the last couple of days.

**Comment by zion2k** [comment]
I changed my youtube account to 2FA and back to normal password. That seems to solve the problem for 4 days. Since today have the "invalid password" error again.

**Comment by HPP8140** [comment]
Yeah, happening again today for me as well.

**Comment by iGoreSchmidt** [comment]
Seems like it depends on IP,
2 days ago i was in other country and had 

> Unable to login: Invalid password

today, from home, it "works": password is OK but 

> 'Unable to submit TFA code: HTTP Error 500: Internal Server Error'

:D

**Comment by HPP8140** [comment]
Switched to cookie authentication instead of user/pass and it appears to be working.

**Comment by cjamesdesigner** [comment]
How do you do this? is cookie authentication the same as .netrc?

**Comment by HPP8140** [comment]
https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-pass-cookies-to-youtube-dl

**Comment by Fabian42** [comment]
This report is still open, right? I'm getting the same "Invalid password" warning and videos are not being marked as watched. Version 2019.11.28, tested today.

**Comment by omeringen** [comment]
I am experiencing this for about ~4 days. (maybe more, i run youtube-dl weekly)
- I tried on different machines and OS's (Win10, Win7)
- Tried with different WAN ip adresses.

Here is the verbose:

`
f:\vid>youtube-dl.exe -v -i -u *** -p *** -f "[height<=?800]" https://www.youtube.com/playlist?list=WL
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-i', '-u', 'PRIVATE', '-p', 'PRIVATE', '-f',
'[height<=?800]', 'https://www.youtube.com/playlist?list=WL']
[debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:watchlater] Downloading login page
[youtube:watchlater] Looking up account info
[youtube:watchlater] Logging in
WARNING: Unable to login: Invalid password
[youtube:watchlater] WL: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjf
mc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjf
mc\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjf
mc\build\youtube_dl\extractor\youtube.py", line 3227, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjf
mc\build\youtube_dl\extractor\youtube.py", line 2730, in _extract_playlist
youtube_dl.utils.ExtractorError: This playlist does not exist.


f:\vid>
`

**Comment by denus69** [comment]
## Checklist

- [ x ] I'm reporting a broken site support
- [ x ] I've verified that I'm running youtube-dl version **2019.11.28**
- [ x ] I've checked that all provided URLs are alive and playable in a browser
- [ x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x ] I've searched the bugtracker for similar issues including closed ones


## Verbose log

```
[debug] System config: []                                                                                                                                                                      
[debug] User config: []                                                                                                                                                                        
[debug] Custom config: []                                                                                                                                                                      
[debug] Command-line args: ['-f', 'best', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v', 'https://youtu.be/J7msxRmoA5o']                                                                              
[debug] Encodings: locale cp1251, fs mbcs, out cp1251, pref cp1251                                                                                                                             
[debug] youtube-dl version 2019.11.28                                                                                                                                                          
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1                                                                                                                                
[debug] exe versions: ffmpeg N-65616-g7cdef77                                                                                                                                                  
[debug] Proxy map: {}                                                                                                                                                                          
[youtube] Downloading login page                                                                                                                                                               
[youtube] Looking up account info                                                                                                                                                              
[youtube] Logging in                                                                                                                                                                           
WARNING: Unable to login: Invalid password                                                                                                                                                     
[youtube] J7msxRmoA5o: Downloading webpage                                                                                                                                                     
[youtube] J7msxRmoA5o: Downloading embed webpage                                                                                                                                               
[youtube] J7msxRmoA5o: Refetching age-gated info webpage                                                                                                                                       
ERROR: Content Warning                                                                                                                                                                         
This video may be inappropriate for some users.                                                                                                                                                
       Sign in to confirm your age                                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                             
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info                                                   
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 530, in extract                                                 
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\youtube.py", line 2148, in _real_extract                                         
youtube_dl.utils.ExtractorError: Content Warning                                                                                                                                               
This video may be inappropriate for some users.                                                                                                                                                
       Sign in to confirm your age                                                                                                                                                             
```


## Description

I can't login on YouTube and can't download video when authorization is required.
In google profile settings "Less secure app access" is "On".

**Comment by bitraid** [comment]
From [README.md](https://github.com/ytdl-org/youtube-dl/blob/master/README.md):
>Passing cookies to youtube-dl is a good way to workaround login when a particular extractor does not implement it explicitly. **Another use case is working around CAPTCHA some websites require you to solve in particular cases in order to get access (e.g. YouTube, CloudFlare).**

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://youtu.be/J7msxRmoA5o', '--cookies', 'cookies.txt', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2019-12-17-bd83191, ffprobe git-2019-12-17-bd83191, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] J7msxRmoA5o: Downloading webpage
[youtube] J7msxRmoA5o: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r3---sn-vuxbavcx-5ui6.googlevideo.com/videoplayback?expire=1577207510&ei=dvIBXvbQKMOrgAf-vLOIBg&ip=178.147.93.202&id=o-A
KACdRm3OPKkNKz0bbHQVaGA7knBxEEbwaPbXQ0-T1Q4&itag=136&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mm=31%2C29&m
n=sn-vuxbavcx-5ui6%2Csn-4g5ednle&ms=au%2Crdu&mv=m&mvi=2&pl=16&initcwndbps=785000&mime=video%2Fmp4&gir=yes&clen=13314429&dur=249.560&lmt=1541860492337570&mt=1577
185844&fvip=3&keepalive=yes&fexp=23842630&c=WEB&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALg
xI2wwRAIgAeshPJZmKwY8zGY91KT2TXtQkJnLYPwbqTEioB2Zs0ACIB4hIUqXnzdC_i1Y5QyQPVnHWdkjWRq5sE3pCreKKVib&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylm
l4wRAIgGWUsKC2SDvOJ44IvUohcli19qKzZGK8NA2_P1UsdzaECIEPOsbok8yY0cd1THEIcTVMjsXIyNtHcgPmAtB3Cl8qp&ratebypass=yes'
[download] Destination: MINE by Álvaro de la Herrán-J7msxRmoA5o.f136.mp4
[download] 100% of 12.70MiB in 00:19
[debug] Invoking downloader on 'https://r3---sn-vuxbavcx-5ui6.googlevideo.com/videoplayback?expire=1577207510&ei=dvIBXvbQKMOrgAf-vLOIBg&ip=178.147.93.202&id=o-A
KACdRm3OPKkNKz0bbHQVaGA7knBxEEbwaPbXQ0-T1Q4&itag=251&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-vuxbavcx-5ui6%2Csn-4g5ednle&ms=au%2Crdu&mv=m&mvi=2&pl=16&ini
tcwndbps=785000&mime=audio%2Fwebm&gir=yes&clen=4203740&dur=249.601&lmt=1541861657916130&mt=1577185844&fvip=3&keepalive=yes&fexp=23842630&c=WEB&txp=5411222&spara
ms=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIgcaaNeNQMgj8QRkqbO1vdyw6f8omDgeoxYlLLnOarXKsCIQD1mtq5t-wk5Z
f5llD5OgvGCN_TH6nA6J5WcKime0JZRA%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgGWUsKC2SDvOJ44IvUohcli19qKzZGK8NA2_P1UsdzaECIEPOsbok
8yY0cd1THEIcTVMjsXIyNtHcgPmAtB3Cl8qp&ratebypass=yes'
[download] Destination: MINE by Álvaro de la Herrán-J7msxRmoA5o.f251.webm
[download] 100% of 4.01MiB in 00:06
[ffmpeg] Merging formats into "MINE by Álvaro de la Herrán-J7msxRmoA5o.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:MINE by Álvaro de la Herrán-J7msxRmoA5o.f136.mp4" -i "file:MINE by Álvaro de la Herrán-J
7msxRmoA5o.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:MINE by Álvaro de la Herrán-J7msxRmoA5o.temp.mkv"
Deleting original file MINE by Álvaro de la Herrán-J7msxRmoA5o.f136.mp4 (pass -k to keep)
Deleting original file MINE by Álvaro de la Herrán-J7msxRmoA5o.f251.webm (pass -k to keep)
``

**Comment by denus69** [comment]
@bitraid Thank you, it works.

But previously youtube-dl worked perfectly without this trick.

**Comment by Joshfindit** [comment]
# SUGGESTION

**Change `youtube-dl` so that it's crystal-clear that login is failing.**

It's very easy to skim past `WARNING: Unable to extract result entry` and think that the `ERROR: This playlist does not exist.` is the real problem.
