### ISSUE TITLE
Site Support Request: Cook's Country (by America's Test Kitchen)

### ISSUE THREAD

**Issue by samantonioli** [ytdl-org/youtube-dl#17234]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v https://www.cookscountry.com/episode/564-when-only-chocolate-will-do
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.cookscountry.com/episode/564-when-only-chocolate-will-do']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-17134-Microsoft-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 564-when-only-chocolate-will-do: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 564-when-only-chocolate-will-do: Downloading webpage
[generic] 564-when-only-chocolate-will-do: Extracting information
[Kaltura] 1_h3hjom15: Downloading video info JSON
[Kaltura] 1_h3hjom15: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://cdnapi.kaltura.com/p/1445801/sp/144580100/playManifest/entryId/1_h3hjom15/format/url/protocol/http/flavorId/1_t8fvcz1n?referrer=aHR0cHM6Ly93d3cuY29va3Njb3VudHJ5LmNvbQ=='
[download] Destination: CCTV1012-When-Only-Chocolate-Will-Do-WEB.mp4-1_h3hjom15.mp4
[download]  10.5% of 4.05GiB at 15.21MiB/s ETA 04:04
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Full episode: https://www.cookscountry.com/episode/564-when-only-chocolate-will-do
- Single recipe video: https://www.cookscountry.com/videos/3685-fluffy-baked-polenta-with-red-sauce

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Cook's Country is a spinoff site that is extremely closely related to America's Test Kitchen. There is already support for America's Test Kitchen within youtube-dl, and due to the sites being extremely similar, I assume that adding support for Cook's Country shouldn't be too difficult. I tried myself but I am not versed enough in Python to understand completely how to do it. Honestly I bet that someone more familiar with Python and the way youtube-dl scripts work could crank this out in under a half hour by using the americastestkitchen.py extractor as a template.

**Comment by sayem314** [comment]
This site works fine for me.

https://pastecode.xyz/view/49c4b644
https://pastecode.xyz/view/a5cd8337
