### ISSUE TITLE
BBC Compatability No Longer Works with Newest Update

### ISSUE THREAD

**Issue by darthhaggis** [ytdl-org/youtube-dl#17252]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
D:\Video\Downloads>youtube-dl https://www.bbc.co.uk/iplayer/episode/b05tkbw0/pet
er-rabbit-series-2-12-the-tale-of-the-highflying-badger -v
[debug] System config: []
[debug] User config: ['--all-subs', '--sub-format', 'srt', '--convert-subs', 'sr
t', '--embed-subs', '--merge-output-format', 'mkv', '--recode-video', 'mkv', '--
format', 'bestvideo[width=1280]+bestaudio/best', '-o', 'D:/Video/Downloads/%(ser
ies)s/%(series)s - %(season_number)sx%(episode_number)02d - %(title)s [%(height)
s] [%(id)s].%(ext)s', '--prefer-ffmpeg', '--ffmpeg-location', 'D:\\Video\\FFMPEG
\\bin', '--download-archive', 'D:/Video/Downloads/Archive.txt', '--exec', 'D:\\V
ideo\\FFMPEG\\bin\\ffmpeg.exe -i {} -map 0 {}_+.mkv']
[debug] Custom config: []
[debug] Command-line args: ['https://www.bbc.co.uk/iplayer/episode/b05tkbw0/pe
ter-rabbit-series-2-12-the-tale-of-the-highflying-badger', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-90771-g5079e96bcc, ffprobe N-90771-g5079e96bcc
[debug] Proxy map: {}
[bbc.co.uk] b05tkbw0: Downloading video page
[bbc.co.uk] b05tkbw0: Downloading playlist JSON
[bbc.co.uk] b05tkbvs: Downloading media selection XML
[bbc.co.uk] b05tkbvs: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b05tkbvs: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b05tkbvs: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[bbc.co.uk] b05tkbvs: Downloading MPD manifest
[bbc.co.uk] b05tkbvs: Downloading m3u8 information
[bbc.co.uk] b05tkbvs: Downloading m3u8 information
[bbc.co.uk] b05tkbvs: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b05tkbvs: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b05tkbvs: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b05tkbvs: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b05tkbvs: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[bbc.co.uk] b05tkbvs: Downloading MPD manifest
[bbc.co.uk] b05tkbvs: Downloading m3u8 information
[bbc.co.uk] b05tkbvs: Downloading m3u8 information
[bbc.co.uk] b05tkbvs: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b05tkbvs: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b05tkbvs: Downloading captions
[bbc.co.uk] b05tkbvs: Downloading captions
ERROR: Unable to download XML: HTTP Error 403: Forbidden (caused by HTTPError())
; please report this issue on https://yt-dl.org/bug . Make sure you are using th
e latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with 
the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\bui
ld\youtube_dl\extractor\common.py", line 599, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\bui
ld\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt

<end of log>
```

---

### Description of your *issue*, suggested solution and other information

The BBC site was working up until the latest update of the software. Since updating, there have been a lot of 403 (Forbidden) errors being produced that were not present on previous builds of the software. A resolution or work around suggestions for this issue would be greatly appreciated as most BBC content is only available for a limited amount of time.

**Comment by jamesdeluk** [comment]
Same issue with --list-subs. Using 2019-01-02.

**Comment by dirkf** [comment]
Problem show is no longer available.
