### ISSUE TITLE
HMNow Site Support Request

### ISSUE THREAD

**Issue by Bajdman** [ytdl-org/youtube-dl#17262]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v https://www.hmnow.com/films/snowy_river_s1e01
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.hmnow.com/films/snowy_river_s1e01']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91314-gbd47cca6a7, ffprobe N-91314-gbd47cca6a7
[debug] Proxy map: {}
[generic] snowy_river_s1e01: Requesting header
WARNING: Falling back on generic information extractor.
[generic] snowy_river_s1e01: Downloading webpage
[generic] snowy_river_s1e01: Extracting information
ERROR: Unsupported URL: https://www.hmnow.com/films/snowy_river_s1e01
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\generic.py", line 3274, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.hmnow.com/films/snowy_river_s1e01
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.hmnow.com/films/snowy_river_s1e01
- Single video: https://www.hmnow.com/films/my_boyfriends_dogs
- Single video: https://ll-c.ooyala.com/e1/gxcTJ1ZjE6OFw5oKgdTI4ujL5vCKQhg6/1/dash/1.mpd

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Attempting to download from HMNow and unable to do so. Looks like HMNow might be utilizing dash and ooyala.

Credentials to login will be active until August 23rd 2018
Username: youtubedl@yahoo.com
Password: Youtube-dl

**Comment by denobisipsis** [comment]
If you decrypt the call 

http://player.ooyala.com/nuplayer?autoplay=1&hide=all&embedCode=$embedcode

there is one downloadable link

for the link https://www.hmnow.com/films/my_boyfriends_dogs

http://player.ooyala.com/nuplayer?autoplay=1&hide=all&embedCode=gxcTJ1ZjE6OFw5oKgdTI4ujL5vCKQhg6

**Comment by Bajdman** [comment]
Appreciate the input. I unfortunately don't need that video, but just posted it as another example. Snowy river is what i'm after

**Comment by denobisipsis** [comment]
http://cdn.videos.bloomberg.com/5yd3I4ODE6utCv_78wkNuE_aTvwFzZlJ/DOcJ-FxaFrRg4gtDIwOmk2OjBrO97z6k

**Comment by Bajdman** [comment]
This is perfect, but i have to ask was this an extraction of the HMNow site, or, found elsewhere on a different site? I'm obviously interested in knowing how to find this for the other episodes in the series.

**Comment by denobisipsis** [comment]
decrypting http://player.ooyala.com/nuplayer?autoplay=1&hide=all&embedCode=5yd3I4ODE6utCv_78wkNuE_aTvwFzZlJ

**Comment by Bajdman** [comment]
Any tips on where i can go to learn how to decrypt the call mentioned above?

**Comment by stinkteeth** [comment]
If you watch the network traffic for the call to h..ps://player.ooyala.com/sas/player_api/v2/authorization/embed_code ...
You can get the base64 encoded url to the SD video.
If you want the 7000k 1080p video, you'll have to decrypt the widevine.  It is a very generic implementation of widevine.

In order for youtube-dl to support the SD video download, auth support needs to be added for this site.

**Comment by Bajdman** [comment]
That was the extra bit of guidance i needed. Thanks!

**Comment by bobskie708** [comment]
I am interested in support for Hallmark Movies Now if it is still in the pipeline for the future.

**Comment by EagleScreech** [comment]
> I am interested in support for Hallmark Movies Now if it is still in the pipeline for the future.

Same here. I cannot get any manual function to work properly.
