### ISSUE TITLE
[npo] Download NPO Start Plus content

### ISSUE THREAD

**Issue by mwesten** [ytdl-org/youtube-dl#17277]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: [u'-o', u'~/Movies/youtube-dl/%(title)s-%(season_number)s-%(episode_number)s-%(episode)s.%(ext)s', u'--write-description', u'--write-info-json', u'--write-thumbnail', u'--write-sub', u'--netrc', u'--audio-format', u'mp3', u'--keep-video', u'--prefer-ffmpeg']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.npostart.nl/wild-thailand/30-08-2018/POW_03551845']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.15 (CPython) - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.0, ffprobe 4.0
[debug] Proxy map: {}
[npo] POW_03551845: Downloading JSON metadata
[npo] POW_03551845: Downloading token
[npo] POW_03551845: Downloading formats JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/npo.py", line 179, in _real_extract
    return self._get_info(video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/npo.py", line 342, in _get_info
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
<end of log>
```

---

### Description of your *issue*, suggested solution and other information
Public movies that are available to **NPO Start** users can be downloaded. Movies that are only available to **NPO Start Plus** users can be seen on the URL fed to youtube-dl, but cannot be downloaded with this script.

**Comment by dstftw** [comment]
You did not pass authenticated cookies.

**Comment by mwesten** [comment]
Thanks @dstftw, Even with the cookies it won't find the file...
```
[debug] System config: []
[debug] User config: [u'-o', u'~/Movies/youtube-dl/%(title)s-%(season_number)s-%(episode_number)s-%(episode)s.%(ext)s', u'--write-description', u'--write-info-json', u'--write-thumbnail', u'--write-sub', u'--netrc', u'--audio-format', u'mp3', u'--keep-video', u'--prefer-ffmpeg']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.npostart.nl/wild-thailand/30-08-2018/POW_03551845', u'--cookies', u'/Users/mwesten/Downloads/__cookies/npostart-cookies.txt']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.15 (CPython) - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.0, ffprobe 4.0
[debug] Proxy map: {}
[npo] POW_03551845: Downloading JSON metadata
[npo] POW_03551845: Downloading token
[npo] POW_03551845: Downloading formats JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/npo.py", line 179, in _real_extract
    return self._get_info(video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/npo.py", line 342, in _get_info
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

I've looked at the difference of the file that is received when calling a public file like: https://www.npostart.nl/wild-thailand/16-08-2018/POW_03551843

get the token: http://ida.omroep.nl/app.php/auth/POW_03551843
get the JSON: http://ida.omroep.nl/app.php/POW_03551843?adaptive=yes&token=[FOUND TOKEN]
returns the following JSON:

```javascript
{
  "limited": false,
  "site": null,
  "items": [
    [
    {
      "label": "Adaptive",
      "contentType": "odi",
      "url": "https:\/\/odis.omroep.nl\/video\/ida\/adaptive\/cc5d1dfec4f9e716254dd9137e5b900a\/5b79c643\/POW_03551843\/1?extension=m3u8&type=jsonp&callback=?",
      "format": "hls"
    },
    {
      "label": "Hoog",
      "contentType": "odi",
      "url": "https:\/\/odis.omroep.nl\/video\/ida\/h264_std\/d47cdb0c1c205076bd7b59c7007e72f8\/5b79c643\/POW_03551843\/1?type=jsonp&callback=?",
      "format": "mp4"
    },
    {
      "label": "Normaal",
      "contentType": "odi",
      "url": "https:\/\/odis.omroep.nl\/video\/ida\/h264_bb\/a7b285193c62acbb673f998437e55445\/5b79c643\/POW_03551843\/1?type=jsonp&callback=?",
      "format": "mp4"
    },
    {
      "label": "Laag",
      "contentType": "odi",
      "url": "https:\/\/odis.omroep.nl\/video\/ida\/h264_sb\/0098bfcb79a0265c8914d5f33cb2a23f\/5b79c643\/POW_03551843\/1?type=jsonp&callback=?",
      "format": "mp4"
    }]
  ]
}
```

When fetching the Plus content:
get the token: http://ida.omroep.nl/app.php/auth/POW_03551845
get the JSON: http://ida.omroep.nl/app.php/POW_03551845?adaptive=yes&token=[FOUND TOKEN]

returns the following JSON:
```javascript
{
  "limited": false,
  "site": null,
  "items": [
    [
    {
      "label": "",
      "contentType": "url",
      "url": "npo+drm:\/\/plusvod.omroep.nl\/POW_03551845",
      "format": "adaptive"
    }]
  ]
}
```

Because there is no valid download URL there, it cannot download a file, but the web-player just plays fine.... Not sure what is the method used there.....

**Comment by stinkteeth** [comment]
As the label states, some credentials are needed to check this.  But if "npo+drm" means anything, it probably means that the plus content has drm.

**Comment by Derkades** [comment]
NPO Start uses widevine DRM for all content: https://tweakers.net/nieuws/149840/npo-start-blokkeert-sinds-maart-downloads-van-streams-met-behulp-van-drm.html

**Comment by elisaado** [comment]
any update on this?

**Comment by Derkades** [comment]
> any update on this?

Probably out of scope for youtube-dl if not impossible since it uses DRM

**Comment by elisaado** [comment]
I see, thank you

**Comment by 89z** [comment]
Issue should be closed, video appears to be broken

**Comment by Ahwxorg** [comment]
Have you found any working answers? Looking to download all of "Even tot Hier", "Flikken Rotterdam" and some other crap. I would be able to run a script 24/7 over a span of about a month if that's necessary.

**Comment by bobberg** [comment]
Problem is still there unfortunately. Wanted to have an episode of something locally.

**Comment by Ahwxorg** [comment]
@bobberg you could use [https://downloadgemist.nl](https://downloadgemist.nl), but since they are able to do this, this should be possible right? yt-dlp and youtube-dl don't work for me, and I don't feel like paying someone to download content which I already pay monthly for...
