### ISSUE TITLE
Unsupported URL: phoenix.de

### ISSUE THREAD

**Issue by mcnesium** [ytdl-org/youtube-dl#17354]
phoenix.de has had a relaunch recently. Now Downloads fail due to unsupported URL error:

```
~$ youtube-dl --version
2018.08.22
~$ youtube-dl https://www.phoenix.de/sendungen/dokumentationen/mein-ausland/gespaltenes-land---schweden-hat-die-wahl-a-324347.html
[generic] gespaltenes-land---schweden-hat-die-wahl-a-324347: Requesting header
WARNING: Falling back on generic information extractor.
[generic] gespaltenes-land---schweden-hat-die-wahl-a-324347: Downloading webpage
[generic] gespaltenes-land---schweden-hat-die-wahl-a-324347: Extracting information
ERROR: Unsupported URL: https://www.phoenix.de/sendungen/dokumentationen/mein-ausland/gespaltenes-land---schweden-hat-die-wahl-a-324347.html

```
the video is on the bottom of the page

**Comment by h-2** [comment]
:+1:

**Comment by majewsky** [comment]
This is still an issue with version 2019.05.20 and video URL https://www.phoenix.de/sendungen/gespraeche/phoenix-runde/nach-dem-wahldebakel---cdu-und-spd-im-taumel-a-1052290.html. On the website, the video player self-identifies as "ZDF player" in the right-click menu, so maybe logic could be shared with the code for ZDF Mediathek.

**Comment by matthiasroos** [comment]
The player might be the same as for ZDF Mediathek, but it is loaded by javascript, rendering the ZDF code useless and making everything very complcated and tedious. Therefore, I am out.

**Comment by mcnesium** [comment]
This issue is not solved yet. Why has it been closed?

    m@x ~/downloads youtube-dl --version
    2021.02.22
    
    m@x ~/downloads youtube-dl https://www.phoenix.de/sendungen/dokumentationen/mensch--mythos-a-1303895.html
    [generic] mensch--mythos-a-1303895: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] mensch--mythos-a-1303895: Downloading webpage
    [generic] mensch--mythos-a-1303895: Extracting information
    ERROR: Unsupported URL: https://www.phoenix.de/sendungen/dokumentationen/mensch--mythos-a-1303895.html
