### ISSUE TITLE
not support bilibili with multi-video?

### ISSUE THREAD

**Issue by NeezerGu** [ytdl-org/youtube-dl#17376]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.28*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.28**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Problum
Not support url : https://www.bilibili.com/video/av30552710
Code:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.bilibili.com/video/av30552710']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.28
[debug] Python version 2.7.15 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[BiliBili] 30552710: Downloading webpage
[BiliBili] 30552710: Downloading video info page
[BiliBili] 30552710: Downloading video info page
ERROR: BiliBili said: Video is hidden.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bilibili.py", line 165, in _real_extract
    self._report_error(video_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bilibili.py", line 101, in _report_error
    raise ExtractorError('%s said: %s' % (self.IE_NAME, result['message']), expected=True)
ExtractorError: BiliBili said: Video is hidden.
```

**Comment by arthasgxy** [comment]
anyone can help me ?

**Comment by dirkf** [comment]
Now "啊叻？视频不见了？" (G says "ah la? Video is missing?")

yt-dl:
>... cannot extract title 

yt-dlp:
>...Unknown error occurred during API check (code -404)

That's a better result, although 404 is not exactly "Unknown".
