### ISSUE TITLE
[Site support request] stream.me

### ISSUE THREAD

**Issue by RyanBabij** [ytdl-org/youtube-dl#17673]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v https://www.stream.me/archive/narcissa/narcissas-stream/kl46vDd62A                                 
[debug] System config: []                                                                                          
[debug] User config: []                                                                                            
[debug] Custom config: []                                                                                          
[debug] Command-line args: ['-v', 'https://www.stream.me/archive/narcissa/narcissas-stream/kl46vDd62A']            
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252                                                  
[debug] youtube-dl version 2018.09.18                                                                              
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299                                                     
[debug] exe versions: ffmpeg N-87130-g2b9fd15, ffprobe N-87130-g2b9fd15                                            
[debug] Proxy map: {}                                                                                              
[generic] kl46vDd62A: Requesting header                                                                            
WARNING: Falling back on generic information extractor.                                                            
[generic] kl46vDd62A: Downloading webpage                                                                          
[generic] kl46vDd62A: Extracting information                                                                       
ERROR: Unsupported URL: https://www.stream.me/archive/narcissa/narcissas-stream/kl46vDd62A                         
Traceback (most recent call last):                                                                                 
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpipjeparb\build\youtube_dl\YoutubeDL.py", line 
92, in extract_info                                                                                                
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpipjeparb\build\youtube_dl\extractor\common.py"
 line 507, in extract                                                                                              
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpipjeparb\build\youtube_dl\extractor\generic.py
, line 3298, in _real_extract                                                                                      
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.stream.me/archive/narcissa/narcissas-stream/kl46vDd
2A                                                                                                                 

<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.stream.me/archive/narcissa/narcissas-stream/kl46vDd62A
- Single video: https://www.stream.me/archive/narcissa/narcissas-stream/kl46vDd62A?t=03:36:33
- Playlist: None

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Stream.me is a gaming video streaming site which currently is not listed in the supported URLs list. There is a large amount of content on there so I think it would be good to add support for this site.

**Comment by Tatsh** [comment]
This one is easy. From the page, look in the `<script>` tags for the line defining `__context`. In that JSON there are several m3u8 URIs under the key `href` and there is a JSON URI as well. The JSON URI is what the desktop will follow first to get m3u8 URIs. URL: `https://video.creekcdn.com/mediasvc/v1/playlist/aiw/v/0/res/3/kl46vDd62A.json`

![screenshot-20180929084054](https://user-images.githubusercontent.com/724848/46245867-71cb7b80-c3c3-11e8-9bb6-d44bd00f76dd.png)

There are two formats for streaming and one format for the MP4.

The single video link would be supported but it would just do the same thing as the one without a timestamp. For splitting the video from that point you should use something like ffmpeg.
