### ISSUE TITLE
Unable to download JSON metadata: HTTP Error 404

### ISSUE THREAD

**Issue by StinutsPeanuts** [ytdl-org/youtube-dl#17680]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.vrt.be/vrtnu/a-z/w817/3/w817-d20160613-sseizoen-3a2/', '--verbose', 'flag']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.7.0 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg N-92058-gefb65abedf, ffprobe N-92058-gefb65abedf, phantomjs 2.1.1, rtmpdump 2.3
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
[VrtNU] w817-d20160613-sseizoen-3a2: Downloading webpage
[VrtNU] w817-d20160613-sseizoen-3a2: Downloading JSON metadata
[Canvas] pbs-pub-0d0240d1-ac29-471a-aa7e-dfdeb3cdc1e7$vid-60d0e52c-a602-4289-8a97-1d15cbae25b3: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python3.7\lib\site-packages\youtube_dl\extractor\common.py", line 604, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python3.7\lib\site-packages\youtube_dl\YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python3.7\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\python3.7\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python3.7\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\python3.7\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\python3.7\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

---

### Description of your *issue*, suggested solution and other information

First off I tried to download a couple of links with --batch-file "listOfLinks.txt" (All from the same website)... The first video's worked, downloaded perfectly normal. Then stumbled upon this problem. I tried with this link only, but still the same error... The video can be played on the website itself (after logging in ofcourse) and all other videos can be downloaded of the same website, just this one won't...  I don't really know what to look for next...

**Comment by FabianMeul** [comment]
Just chiming in to let you guys know I'm running into the same issue.

Works perfectly fine;
https://www.vrt.be/vrtnu/a-z/kamp-waes/1/kamp-waes-s1a1/
https://www.vrt.be/vrtnu/a-z/kamp-waes/1/kamp-waes-s1a2/
https://www.vrt.be/vrtnu/a-z/kamp-waes/1/kamp-waes-s1a3/
https://www.vrt.be/vrtnu/a-z/kamp-waes/1/kamp-waes-s1a4/

Gives the error as described above;
https://www.vrt.be/vrtnu/a-z/kamp-waes/1/kamp-waes-s1a5/

```
Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```
