### ISSUE TITLE
[VrtNU] Site not working

### ISSUE THREAD

**Issue by editicalu** [ytdl-org/youtube-dl#17701]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.vrt.be/vrtnu/a-z/pano/2018/pano-s2018a10/', '--username', 'PRIVATE', '--password', 'PRIVATE', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.7.0 (CPython) - Linux-4.18.10-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg n4.0.2, ffprobe n4.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
[VrtNU] pano-s2018a10: Downloading webpage
WARNING: [VrtNU] pano-s2018a10: Failed to parse JSON Invalid \escape: line 6 column 26 (char 112)
[VrtNU] pano-s2018a10: Downloading JSON metadata
[Canvas] pbs-pub-6eaa65b7-988b-4153-9e95-37c8e07c582a$vid-ab216d5e-24f5-490c-9ae4-4abedc7772ca: Downloading JSON metadata
[Canvas] pbs-pub-6eaa65b7-988b-4153-9e95-37c8e07c582a$vid-ab216d5e-24f5-490c-9ae4-4abedc7772ca: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno -2] Name or service not known>
[Canvas] pbs-pub-6eaa65b7-988b-4153-9e95-37c8e07c582a$vid-ab216d5e-24f5-490c-9ae4-4abedc7772ca: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno -2] Name or service not known>
[Canvas] pbs-pub-6eaa65b7-988b-4153-9e95-37c8e07c582a$vid-ab216d5e-24f5-490c-9ae4-4abedc7772ca: Downloading ISM manifest
WARNING: Failed to download ISM manifest: <urlopen error [Errno -2] Name or service not known>
[Canvas] pbs-pub-6eaa65b7-988b-4153-9e95-37c8e07c582a$vid-ab216d5e-24f5-490c-9ae4-4abedc7772ca: Downloading f4m manifest
WARNING: Unable to download f4m manifest: <urlopen error [Errno -2] Name or service not known>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./ydl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "./ydl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "./ydl/youtube_dl/extractor/canvas.py", line 73, in _real_extract
    self._sort_formats(formats)
  File "./ydl/youtube_dl/extractor/common.py", line 1286, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
### Description of your *issue*, suggested solution and other information

I tried to download a video from VrtNU, but was unable to do so.

**Comment by peturdainn** [comment]
Another example, using the .mpd URL from their site:
(yes, I know, this is 2 versions behind)

webpage: https://www.vrt.be/vrtnu/a-z/still-alice/2014/still-alice/
manifest URL: https://ondemand-vrt.akamaized.net/content/vod/vid-32cbc3f8-a937-4a72-a1e1-a83bdfb301f9-CDN_2/vid-32cbc3f8-a937-4a72-a1e1-a83bdfb301f9-CDN_2_drm_b0115079-a59e-4386-a073-49aec1d4440d.ism/.mpd

output:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://ondemand-vrt.akamaized.net/content/vod/vid-32cbc3f8-a937-4a72-a1e1-a83bdfb301f9-CDN_2/vid-32cbc3f8-a937-4a72-a1e1-a83bdfb301f9-CDN_2_drm_b0115079-a59e-4386-a073-49aec1d4440d.ism/.mpd', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.10
[debug] Python version 3.6.6 (CPython) - Linux-4.18.0-1-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 3.1.5, ffprobe 3.1.5, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] .mpd: Requesting header
WARNING: Falling back on generic information extractor.
[generic] .mpd: Downloading webpage
[generic] .mpd: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/generic.py", line 2346, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by xplorr** [comment]
Can someone fix this or suggest a quickfix in the canvas.py file?

**Comment by Twilkie** [comment]
@xplorr https://github.com/rg3/youtube-dl/pull/18629/files

**Comment by mantebridts** [comment]
I'm having an issue with vrt.nu too, is this the same as described here, or should I open a new issue?

```
--verbose -F https://ondemand-vrt.akamaized.net/content/vod/vid-dbcfb47c-82ee-4797-b6ec-1c4b78d740ef-CDN_3/vid-dbcfb47c-82ee-4797-b6ec-1c4b78d740ef-CDN_3_drm_9279842c-01bc-4c68-9810-48162a4c64da.ism/.mpd
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-F', u'https://ondemand-vrt.akamaized.net/content/vod/vid-dbcfb47c-82ee-4797-b6ec-1c4b78d740ef-CDN_3/vid-dbcfb47c-82ee-4797-b6ec-1c4b78d740ef-CDN_3_drm_9279842c-01bc-4c68-9810-48162a4c64da.ism/.mpd']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.17
[debug] Python version 2.7.10 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[generic] .mpd: Requesting header
WARNING: Falling back on generic information extractor.
[generic] .mpd: Downloading webpage
[generic] .mpd: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2362, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1292, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by xplorr** [comment]
@mantebridts: thanks for your efforts, but works only for some vrtnu url's.
Does not work for (examples): 
https://www.vrt.be/vrtnu/a-z/my-brilliant-friend/1/my-brilliant-friend-s1a1/
https://www.vrt.be/vrtnu/a-z/cirque-du-soleil--worlds-away/2012/cirque-du-soleil--worlds-away-cirque-du-soleil-worlds-away/
