### ISSUE TITLE
Safaribooksonline url redirects to Oreily.com : Unsupported URL

### ISSUE THREAD

**Issue by SomuSysAdmin** [ytdl-org/youtube-dl#17781]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
(venv) E:\CCNA_2018>youtube-dl -u username@domain.com -p password-Fv https://www.safaribooksonline.com/learning-paths/learning-path-ccna/9780134840215/9780134664330-ICN1_01_01_05
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-Fv', 'https://www.safaribooksonline.com/learning-paths/learning-path-ccna/9780134840215/9780134664330-ICN1_01_01_05']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.7.0 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 9780134664330-ICN1_01_01_05: Requesting header
[redirect] Following redirect to https://www.oreilly.com/learning-paths/learning-path-ccna/9780134840215/9780134664330-ICN1_01_01_05
[generic] 9780134664330-ICN1_01_01_05: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 9780134664330-ICN1_01_01_05: Downloading webpage
[generic] 9780134664330-ICN1_01_01_05: Extracting information
ERROR: Unsupported URL: https://www.oreilly.com/learning-paths/learning-path-ccna/9780134840215/9780134664330-ICN1_01_01_05
Traceback (most recent call last):
  File "e:\ccna_2018\venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "e:\ccna_2018\venv\lib\site-packages\youtube_dl\extractor\common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "e:\ccna_2018\venv\lib\site-packages\youtube_dl\extractor\generic.py", line 3298, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.oreilly.com/learning-paths/learning-path-ccna/9780134840215/9780134664330-ICN1_01_01_05
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video:  https://www.oreilly.com/learning-paths/learning-path-ccna/9780134840215/9780134664330-ICN1_01_01_05

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

When I try to execute the command to download a video from `Safaribooksonline.com`, the site redirects to an `oreily.com` domain, which then causes an exception stating that the site isn't supported. For example, 'https://www.safaribooksonline.com/learning-paths/learning-path-ccna/9780134840215/9780134664330-ICN1_01_01_05' redirects to ' https://www.oreilly.com/learning-paths/learning-path-ccna/9780134840215/9780134664330-ICN1_01_01_05' and causes the error.

NOTE: The credentials to log in to the site can be obtained by signing up with any email ID; no card details required.

**Comment by SomuSysAdmin** [comment]
Note: If this is by chance a duplicate (even though I couldn't find any similar topic), please provide a link to the solution. Thanks!

**Comment by sdi22** [comment]
I can confirm this being a issue, as some URL's at safaribooks.com now redirect to oreilly.com. This is another example: 
https://www.safaribooksonline.com/learning-paths/learning-path-acquiring/9781491998458/

> [redirect] Following redirect to https://www.oreilly.com/learning-paths/learning-path-acquiring/9781491998458/
[generic] 9781491998458: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 9781491998458: Downloading webpage
[generic] 9781491998458: Extracting information
ERROR: Unsupported URL: https://www.oreilly.com/learning-paths/learning-path-acquiring/9781491998458/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.oreilly.com/learning-paths/learning-path-acquiring/9781491998458/

**Comment by NghiaSE** [comment]
https://www.safaribooksonline.com/learning-paths/learning-path-building/9781491996782/
was redirected to
https://www.oreilly.com/learning-paths/learning-path-building/9781491996782/
then
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.oreilly.com/learning-paths/learning-path-building/9781491996782/

**Comment by kutkin54** [comment]
The link for safaribooksonline is no longer used in the URL. There is a new domain called as www.learning.oreiily.com being used now. There may be a need to include a new extractor for this.

**Comment by knrastogi** [comment]
https://www.safaribooksonline.com has migrated to www.learning.oreiily.com  and all https://www.safaribooksonline.com links redirect to  www.learning.oreiily.com. The new domain issues the username and password which is not supported on safari domain,.

ERROR: Unsupported URL: https://www.oreilly.com/learning-paths/learning-path-acquiring/9781491998458/

**Comment by knrastogi** [comment]
Microsoft Windows [Version 10.0.17763.168]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Param>cd c:\safarivids

c:\safarivids>youtube-dl
[generic] 10000MNLV201732: Requesting header
[redirect] Following redirect to https://learning.oreilly.com/library/view/learning-clientside-graphql/10000MNLV201732/
[generic] 10000MNLV201732: Requesting header
[generic] 10000MNLV201732: Downloading webpage
[generic] 10000MNLV201732: Extracting information
ERROR: Unsupported URL: https://learning.oreilly.com/library/view/learning-clientside-graphql/10000MNLV201732/
[generic] 10000MNLV201729: Requesting header
[redirect] Following redirect to https://learning.oreilly.com/library/view/react-in-motion/10000MNLV201729/
[generic] 10000MNLV201729: Requesting header
[generic] 10000MNLV201729: Downloading webpage
[generic] 10000MNLV201729: Extracting information
ERROR: Unsupported URL: https://learning.oreilly.com/library/view/react-in-motion/10000MNLV201729/

c:\safarivids>

**Comment by blueray453** [comment]
Though it does not download from -
https://www.safaribooksonline.com/learning-paths/learning-path-ccna/9780134840215/
or,
https://www.oreilly.com/learning-paths/learning-path-ccna/9780134840215/

But it does download from -
https://learning.oreilly.com/videos/learning-path-ccna/9780134840215/

So, for the time being do not use the previous two URLs. Use the last one.

**Comment by brennebeck** [comment]
@blueray453 this no longer seems to be the case? I'm unable to download at all from the new site.

**Comment by vikiaiteam** [comment]
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.safaribooksonline.com/learning-paths/learning-path-ccna/9780134840864/

C:\youtube-dl-master\downloaded>youtube-dl -u XXXX@hotmail.com -p XXXX -v --all-subs -i -c -w -o "E:\safaribooksonline\%(playlist)s\%(playlist_index)s
-%(title)s.%(ext)s" --external-downloader aria2c.exe https://www.safaribooksonline.com/learning-paths/learning-path-ccna/9780134840864/ --convert-subs srt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-v', '--all-subs', '-i', '-c', '-w', '-o', 'E:\\safaribooksonline_2020\\%(playlist)s\\%(playlist_index)s-%(title)s
.%(ext)s', '--external-downloader', 'aria2c.exe', 'https://www.safaribooksonline.com/learning-paths/learning-path-ccna/9780134840864/', '--convert-subs', 'srt']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.03.01
[debug] Python version 3.7.2 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 9780134840864: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 9780134840864: Downloading webpage
[generic] 9780134840864: Extracting information
ERROR: Unsupported URL: https://www.safaribooksonline.com/learning-paths/learning-path-ccna/9780134840864/
Traceback (most recent call last):
  File "c:\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "c:\python37-32\lib\site-packages\youtube_dl\extractor\common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "c:\python37-32\lib\site-packages\youtube_dl\extractor\generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.safaribooksonline.com/learning-paths/learning-path-ccna/9780134840864/
