### ISSUE TITLE
cda.pl extractor stopped working

### ISSUE THREAD

**Issue by s416058** [ytdl-org/youtube-dl#17803]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-config', u'-f', u'best', u'https://www.cda.pl/video/24798179a', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-36-lowlatency-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.0.2-1, ffprobe 4.0.2-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[CDA] 24798179a: Downloading webpage
[CDA] 24798179a: Downloading 360p version information
WARNING: Unable to download webpage: HTTP Error 404: 
WARNING: [CDA] Unable to download 360p version information
[CDA] 24798179a: Downloading 720p version information
WARNING: Unable to download webpage: HTTP Error 404: 
WARNING: [CDA] Unable to download 720p version information
[CDA] 24798179a: Downloading 1080p version information
WARNING: Unable to download webpage: HTTP Error 404: 
WARNING: [CDA] Unable to download 1080p version information
[debug] Invoking downloader on u'https://vwaw114.cda.pl/F-5MihJhb8UPBcbHFxlO7Q/1538839278/lq14c1eb5a45310c7e0a0c23c9aabed90fe05a68e96c2d9eb95762dea119e459ecadc.mp4?nc=2'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1908, in process_info
    success = dl(filename, info_dict)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "./youtube-dl/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "./youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "./youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
...
<end of log>
```

**Comment by gapl** [comment]
Same thing here. Any update?

**Comment by bato3** [comment]
probably reason:
```
set-cookie: vToken=cfc69aaf6e4aaab2876f1fdfef9aaee0; path=/kV6YzbvSmY9TYkOuT4sGuA/1539130480/lq018856af7795259e6911e4fd1e4f573a.mp4; domain=.cda.pl
```

**Comment by zk1234** [comment]
Why closed? The problem still exists.

**Comment by bato3** [comment]
@zk1234 closed is duplicate: #17853 not this issue

**Comment by zk1234** [comment]
Oops! I haven't noticed that. Sorry.

**Comment by ZaxonXP** [comment]
version 2018.11.23 the same issue exist:

```
user@localhost:~$ youtube-dl -v -F https://www.cda.pl/video/274897559/vfilm
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.cda.pl/video/274897559/vfilm']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.23
[debug] Python version 2.7.13 (CPython) - Linux-4.16.0-0.bpo.2-686-pae-i686-with-debian-9.6
[debug] exe versions: ffmpeg 3.3.9, ffprobe N-91378-g3f95337
[debug] Proxy map: {}
[CDA] 274897559: Downloading webpage
[CDA] 274897559: Downloading 720p version information
WARNING: Unable to download webpage: HTTP Error 404: 
WARNING: [CDA] Unable to download 720p version information
[CDA] 274897559: Downloading 1080p version information
WARNING: Unable to download webpage: HTTP Error 404: 
WARNING: [CDA] Unable to download 1080p version information
[info] Available formats for 274897559:
format code  extension  resolution note
lq           mp4        480p       
```

**Comment by s416058** [comment]
@ZaxonXP 

```
youtube-dl -v  https://www.cda.pl/video/274897559/vfilm
[debug] System config: []
[debug] User config: ['--format', 'bestvideo[height<=?1440]+bestaudio/best', '--output', '~/Videos/YouTube/%(uploader)s/%(title)s-%(id)s.%(ext)s', '--sub-format', 'best', '--sub-lang', 'pl,en', '--write-sub', '--ignore-errors', '--no-warnings', '--netrc']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.cda.pl/video/274897559/vfilm']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.07
[debug] Python version 3.6.7 (CPython) - Linux-4.15.0-39-lowlatency-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.0.2-1, ffprobe 4.0.2-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[CDA] 274897559: Downloading webpage
[CDA] 274897559: Downloading 720p version information
[CDA] 274897559: Downloading 1080p version information
[debug] Invoking downloader on 'https://vrbx205.cda.pl/mewoHF_zSijM0wgP-aeKAw/1543509245/lqc7502d7bd22cd829949394ef4694f755.mp4'
[download] Destination: /home/lelf/Videos/YouTube/NA/Czy warto suplementować witaminę D-274897559.mp4
[download]  10.2% of 19.59MiB at  1.60MiB/s ETA 00:10^C
ERROR: Interrupted by user
```

I don't know why, but for some time now cda has been working for me normally. I have version 2018.11.07. On the latest version it also works.

**Comment by ZaxonXP** [comment]
It does not work for me (tried with the same URL). Would it be that a different Python version make a difference?

**Comment by zk1234** [comment]
> @ZaxonXP @bato3
> 
> ```
> youtube-dl -v  https://www.cda.pl/video/274897559/vfilm
> [debug] System config: []
> [debug] User config: ['--format', 'bestvideo[height<=?1440]+bestaudio/best', '--output', '~/Videos/YouTube/%(uploader)s/%(title)s-%(id)s.%(ext)s', '--sub-format', 'best', '--sub-lang', 'pl,en', '--write-sub', '--ignore-errors', '--no-warnings', '--netrc']
> [debug] Custom config: []
> [debug] Command-line args: ['-v', 'https://www.cda.pl/video/274897559/vfilm']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2018.11.07
> [debug] Python version 3.6.7 (CPython) - Linux-4.15.0-39-lowlatency-x86_64-with-Ubuntu-18.04-bionic
> [debug] exe versions: ffmpeg 4.0.2-1, ffprobe 4.0.2-1, phantomjs 2.1.1, rtmpdump 2.4
> [debug] Proxy map: {}
> [CDA] 274897559: Downloading webpage
> [CDA] 274897559: Downloading 720p version information
> [CDA] 274897559: Downloading 1080p version information
> [debug] Invoking downloader on 'https://vrbx205.cda.pl/mewoHF_zSijM0wgP-aeKAw/1543509245/lqc7502d7bd22cd829949394ef4694f755.mp4'
> [download] Destination: /home/lelf/Videos/YouTube/NA/Czy warto suplementować witaminę D-274897559.mp4
> [download]  10.2% of 19.59MiB at  1.60MiB/s ETA 00:10^C
> ERROR: Interrupted by user
> ```
> 
> I don't know why, but for some time now cda has been working for me normally. I have version 2018.11.07. On the latest version it also works.

It works fine for me, too (both with Python2 and with Python3).

**Comment by ZaxonXP** [comment]
So what is the problem in my case? How to find it out?

**Comment by rewida17** [comment]
Yup, its work but try get link's to different quality than 480p ;) impossible at this time

**Comment by ZaxonXP** [comment]
That is the thing. Try to use `-F` option with the links and you will see the difference.

**Comment by bato3** [comment]
CDA changed his code. [this](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/cda.py#L170) is now `http://www.cda.pl/https://www.cda.pl/video/24798179a/vfilm?wersja=1080p`

BTW: they count page downloading in cookie `vasty`

**Comment by Kondzio18** [comment]
Someone fixed the problem with "Unable to download .... version information" ?
