### ISSUE TITLE
[RTE.ie] JSON error downloading Six One News

### ISSUE THREAD

**Issue by oisinq** [ytdl-org/youtube-dl#17822]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
> youtube-dl https://www.rte.ie/player/ie/show/rte-news-six-one-30003249/10949081/ -v

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.rte.ie/player/ie/show/rte-news-six-one-30003249/10949081/', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.10 (CPython) - Darwin-18.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[rte] 10949081: Downloading JSON metadata
ERROR: rte said: The content you are trying to view is not available. It may be restricted to another territory, or copyright has expired. (2)
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rte.py", line 23, in _real_extract
    item_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 864, in _download_json
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 842, in _download_json_handle
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 617, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download JSON metadata: HTTP Error 404: NOT FOUND (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rte.py", line 30, in _real_extract
    expected=True)
ExtractorError: rte said: The content you are trying to view is not available. It may be restricted to another territory, or copyright has expired. (2)
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

I'm trying to download some episodes of RTÉ News from [here](https://www.rte.ie/player/ie/show/rte-news-six-one-30003249/10948791/). Whenever I try to download an episode, I get the error above. I've tried to debug the issue myself, it seems that the JSON file retrieved is displaying an error - [see here](https://feeds.rasset.ie/rteavgen/getplaylist/?format=json&id=10948791&type=web). Here's an [example JSON file](https://feeds.rasset.ie/rteavgen/getplaylist/?format=json&id=10810821&type=web) that you can get from most other shows on the site. I'm not sure if this is some more DRM or just a simple bug, but I can't figure out how to fix it.

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by oisinq** [comment]
That's fair,
