### ISSUE TITLE
FranceTVSite ERROR: Unable to extract video ID

### ISSUE THREAD

**Issue by jesus2099** [ytdl-org/youtube-dl#17835]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

BUG REPORT
=========

For **FranceTVSite**, prior to youtube-dl and ffmpeg updates — ffmpeg was 2016 and youtube-dl was I don’t remember — donwload was OK but A/V multiplex was NG.

- https://www.france.tv/spectacles-et-culture/theatre-danse-opera/737497-heiva-i-paris-2018.html
- https://www.france.tv/france-o/heiva-2018/737499-meilleurs-moments-du-heiva.html
- https://www.france.tv/spectacles-et-culture/musique-concerts/716645-l-outre-mer-fait-son-olympia.html

Then I updated both youtube-dl and ffmpeg and it is now worse as download itself is now NG (**ERROR: Unable to extract video ID**):

```
E:\TV>youtube-dl --verbose https://www.france.tv/spectacles-et-culture/theatre-danse-opera/737497-heiva-i-paris-2018.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.france.tv/spectacles-et-culture/theatre-danse-opera/737497-heiva-i-paris-2018.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-92132-g0a41a8bf29, ffprobe N-92132-g0a41a8bf29
[debug] Proxy map: {'http': 'http://proxy__._________.__:80', 'https': 'http://proxy__._________.__:80'}
[FranceTVSite] 737497-heiva-i-paris-2018: Downloading webpage
ERROR: Unable to extract video ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\francetv.py", line 280, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 986, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 977, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by baptx** [comment]
Same problem with France TV Info:
```
bapt@dell:~$ youtube-dl --verbose https://www.francetvinfo.fr/replay-jt/france-2/13-heures/jt-de-13h-du-jeudi-18-avril-2019_3255555.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.francetvinfo.fr/replay-jt/france-2/13-heures/jt-de-13h-du-jeudi-18-avril-2019_3255555.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-17-generic-x86_64-with-Ubuntu-18.10-cosmic
[debug] exe versions: avconv 4.0.2-2, avprobe 4.0.2-2, ffmpeg 4.0.2-2, ffprobe 4.0.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[francetvinfo.fr] jt-de-13h-du-jeudi-18-avril-2019_3255555: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/francetv.py", line 377, in _real_extract
    webpage, 'video id').split('@')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Duplicates: https://github.com/ytdl-org/youtube-dl/issues/20639 https://github.com/ytdl-org/youtube-dl/issues/20619

The workaround is to open the browser console before loading the video and then get the m3u8 URL in the network tab.

**Comment by jesus2099** [comment]
I was able to download two documentaries indeed this week so I guess it's why you closed this ticket. It's fixed. Thanks! 😀

**Comment by jesus2099** [comment]
Actually the issue is still there.
Where is the open ticket?
We reopen this one?

**Comment by cappert** [comment]
@jesus2099 please open a new issue with URL and version. and paste the issue number here.

**Comment by baptx** [comment]
@jesus2099 @cappert it may be better to keep the original issue open instead of closing and creating a duplicate issue every time. If you create a new issue, it would be nice to mention this issue also.

**Comment by cappert** [comment]
Thanks for adding the URL.

**Comment by cappert** [comment]
`https://www.france.tv/spectacles-et-culture/theatre-et-danse/328767-37e-festival-international-du-cirque-de-monte-carlo.html` downloads fine for me.

I'm downloading from France. **Where are you located?**
It might be geo-blocked. 

the segments URLs are something like: 
`https://replayftv-vh.akamaihd.net/i/streaming-adaptatif_france-dom-tom/2019/S30/J2/209283653-5d377c0c9603e-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/segment2_4_av.ts?null=0`

(notice `france-dom-tom`)
