### ISSUE TITLE
[VK.COM] '--download-archive' commandline does not save uploader ID

### ISSUE THREAD

**Issue by nulledone** [ytdl-org/youtube-dl#17848]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['-f', 'best', '--download-archive', 'vk.archive', '--ignore-errors']
[debug] Command-line args: ['--config-location', 'vk.com', 'https://vk.com/video447593212_456239020,', 'https://vk.com/video-156864573_456239020', '-v']
[debug] Encodings: locale cp1254, fs mbcs, out cp1254, pref cp1254
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-91487-g1809f1cda9, ffprobe N-91487-g1809f1cda9
[debug] Proxy map: {}
[vk] 447593212_456239020: Downloading webpage
[vk] 447593212_456239020: Downloading m3u8 information
[download] doc447593212_468273708.mp4 has already been recorded in archive
[vk] -156864573_456239020: Downloading webpage
[vk] -156864573_456239020: Downloading m3u8 information
[download] Blue Sleep - mattress test has already been recorded in archive
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

When a video is downloaded with --download-archive command line, youtube-dl puts video ID to specified archive file. Some videos from different uploaders can have same video ID such as the links below;
https://vk.com/video447593212_456239020 
https://vk.com/video-156864573_456239020

**Comment by blndev** [comment]
Yes. 
Thats really an issue in the Archive-File the whole Video ID from URL must be stored.

**Comment by blndev** [comment]
That was quick. I just checked out the sources to do that as well ;-)

Just a hint for thread owner: when downloading, also the Filename is checked (if filename is already existing, file is also not downloaded but marked in archive as finished).

I solved it by the following Filename pattern: -o ~/autodown/%(extractor)s/%(uploader)s-_-%(title)s-id%(id)s.%(ext)s

**Comment by nulledone** [comment]
@blndev Yes I had a different naming with url(vid+uploader id) embedded to overcome this as well.

**Comment by Edwardwsr** [comment]
Just a trace for thread owner: when downloading, additionally the Filename is checked if filename is already existing, file is also no longer downloaded however marked in archive as finished.
