### ISSUE TITLE
Site Support Request for CBS Movie URLs

### ISSUE THREAD

**Issue by digitalhybrid** [ytdl-org/youtube-dl#17870]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

I've just discovered that CBS now have a streaming movies sections available on their website.

The URLs are live and do work in a web browser.

Could we have site supported added for these types of URLs, please ...

https://www.cbs.com/movies/capote/QplUqqv_vzInIsh_XLdEH5A8QIiYU0oj/

Thanks in advance.

**Comment by dare2** [comment]
I understand that most movies are DRM protected, but I can't imagine that certain specials or documentaries are also locked. For instance, https://www.cbs.com/movies/building-star-trek/wQH9yE_y_Dt4ekDYm3yelhhY2KXvOra_

Could this be investigated?

**Comment by 0xC0000054** [comment]
> Could this be investigated?

I have found that many of the CBS/Paramount+ specials and documentaries can be downloaded by manually passing the download ID to the CBS extractor.
Note that any DRM protected movies will still fail to download.

Using Building Star Trek as an example:

The full URL will not work due to the youtube-dl extractor not supporting it:

`youtube-dl --hls-prefer-native https://www.paramountplus.com/movies/building-star-trek/wQH9yE_y_Dt4ekDYm3yelhhY2KXvOra_/`

But it works if you manually extract the download ID (`wQH9yE_y_Dt4ekDYm3yelhhY2KXvOra_`) from the URL and pass it to the CBS/Paramount+ extractor:

`youtube-dl --hls-prefer-native cbs:wQH9yE_y_Dt4ekDYm3yelhhY2KXvOra_`

The `--hls-prefer-native` option is used to try and fix an audio sync issue with CBS downloads, see issue #27972 for details.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30491

**Comment by 89z** [comment]
The previous suggestion does not work in all cases:

~~~
PS C:\> youtube-dl --hls-prefer-native cbs:eyT_RYkqNuH_6ZYrepLtxkiPO1HA7dIU
[CBS] eyT_RYkqNuH_6ZYrepLtxkiPO1HA7dIU: Downloading XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
~~~

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29038
