### ISSUE TITLE
[amcnetworks] Support movies on BBC America

### ISSUE THREAD

**Issue by gkoelln** [ytdl-org/youtube-dl#17871]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.bbcamerica.com/?amcn_video_movie=vertigo', '-F', '--cookies', 'C:\\Users\\greg\\Dropbox\\Scripts\\cookies.txt', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[generic] ?amcn_video_movie=vertigo: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?amcn_video_movie=vertigo: Downloading webpage
[generic] ?amcn_video_movie=vertigo: Extracting information
[download] Downloading playlist: Vertigo | BBC America
[generic] playlist Vertigo | BBC America: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[ThePlatform] pI16Gz_nRfaD: Downloading SMIL data
ERROR: This content requires a valid, unexpired auth token.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\theplatform.py", line 297, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\theplatform.py", line 44, in _extract_theplatform_smil
youtube_dl.utils.ExtractorError: This content requires a valid, unexpired auth token.
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.bbcamerica.com/?amcn_video_movie=vertigo
- Single video: http://www.bbcamerica.com/?amcn_video_movie=the-birds
- Single video: http://www.bbcamerica.com/?amcn_video_movie=rear-window
- Single video: http://www.bbcamerica.com/?amcn_video_movie=psycho
- Single video: http://www.bbcamerica.com/?amcn_video_movie=adv-space-time

---

**Comment by 89z** [comment]
None of those links are valid anymore

**Comment by 89z** [comment]
@gkoelln I am thinking about implementing this site, can you please update original post with a valid example?

**Comment by 89z** [comment]
I checked the current Web and Android clients. It seems DRM is used in all cases. Also the three URLs I found:

https://github.com/ytdl-org/youtube-dl/blob/49c5293014bc11ec8c009856cd63cffa6296c1e1/youtube_dl/extractor/amcnetworks.py#L18-L45

all return 404.

**Comment by gkoelln** [comment]
Videos are now DRM-protected.

**Comment by 89z** [comment]
Seems my previous comment was removed, here it is again. I was able to successfully download and decrypt this media:

https://github.com/89z/mech/tree/013158b6/research/bbcamerica

**Comment by 89z** [comment]
@gkoelln are you still interested in this? I think I am now able to make an implementation. I did one already for Roku and Paramount
