### ISSUE TITLE
Unable to download pornhub user videos

### ISSUE THREAD

**Issue by zzzeusss** [ytdl-org/youtube-dl#17936]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
sh-4.3$ youtube-dl https://www.pornhub.com/users/velvetveronica/videos/public -i -w -o "ph/%(uploader)s/%(title)s [%(id)s].%(ext)s" -f best --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.pornhub.com/users/velvetveronica/videos/public', u'-i', u'-w', u'-o', u'ph/%(uploader)s/%(title)s [%(id)s].%(ext)s', u'-f', u'best', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.12 (CPython) - Linux-4.9.87-xxxx-std-ipv6-64-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15-0ubuntu0.16.04.1, ffprobe 2.8.15-0ubuntu0.16.04.1
[debug] Proxy map: {}
[PornHubUserVideos] velvetveronica: Downloading page 1
[PornHubUserVideos] velvetveronica: Downloading page 2
[PornHubUserVideos] velvetveronica: Downloading page 3
[PornHubUserVideos] velvetveronica: Downloading page 4
[PornHubUserVideos] velvetveronica: Downloading page 5
[PornHubUserVideos] velvetveronica: Downloading page 6
[PornHubUserVideos] velvetveronica: Downloading page 7
...
...
...
[PornHubUserVideos] velvetveronica: Downloading page 492
[PornHubUserVideos] velvetveronica: Downloading page 493
[PornHubUserVideos] velvetveronica: Downloading page 494
[PornHubUserVideos] velvetveronica: Downloading page 495
[PornHubUserVideos] velvetveronica: Downloading page 496
ERROR: Unable to download webpage: [Errno 104] Connection reset by peer (caused by error(104, 'Connection reset by peer')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 604, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1027, in http_response
    content = resp.read()
  File "/usr/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 588, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 648, in _read_chunked
    value.append(self._safe_read(amt))
  File "/usr/lib/python2.7/httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Any pornhub user video page (e.g., https://www.pornhub.com/users/velvetveronica/videos/public, or removing the /videos and/or /videos/public)

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I've been unable to download user videos for some time, with the above output being consistent.

**Comment by parmjitv** [comment]
Hi @zzzeusss,

I believe this is related to issue #16078.  Apparently Pornhub has implemented some site changes regarding the user profiles, and this is causing some problems when trying to fetch playlists of videos.

A new PR has already been submitted to address this, unfortunately the peer review has been stalled for some time now.

Cheers,

Parmjit V.

**Comment by github-userx** [comment]
I’m very surprised that the pull request hasn’t been accepted after all these months?

**Comment by github-userx** [comment]
I’m very surprised that the pull request hasn’t been accepted after all these months?

**Comment by github-userx** [comment]
@parmjitv how can I run / use your version or Pornhub extractor?

**Comment by parmjitv** [comment]
@github-userx - Strictly speaking we should pull code that has been vetted and merged by the collaborators, as this will be properly maintained over time.  At any rate the pull request needs some work yet - please see PR #17454 for details.

Cheers,

Parmjit V.

**Comment by github-userx** [comment]
Ok, thanks for this Update and Information! Unfortunately i am not a programmer myself and can’t take this on. I’m surprised that this extractor has not bigger demand apparently.
kind regards
