### ISSUE TITLE
Limit filesize and/or execution time for rtmpdump

### ISSUE THREAD

**Issue by demiantres** [ytdl-org/youtube-dl#1794]
Hi,

AFAIK the rtmpdump tool does not have support for maximum filesize or execution time limit parameters. Would it be possible to add this to the youtube-dl script (e.g. by terminating rtmpdump when a certain time has passed or the target file reaches a given size)?

Regards,

**Comment by dirkf** [comment]
External issue, or create a wrapper script for such a case.
