### ISSUE TITLE
Request: set amount of video to download

### ISSUE THREAD

**Issue by demiantres** [ytdl-org/youtube-dl#1795]
Hi,

The "--max-filesize" parameter skips the complete video if its size is too big. I think it would be useful to have an option to download only a given number of bytes from a video (e.g. --max-downloadsize 50m). As we are dealing with streaming videos there is usually no problem with playing back partial videos.

Regards,

**Comment by dirkf** [comment]
No, but you could use an external downloader with suitable parameters for this.
