### ISSUE TITLE
Cannot download from WDR

### ISSUE THREAD

**Issue by annomatik** [ytdl-org/youtube-dl#17989]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v https://kinder.wdr.de/tv/wissen-macht-ah/sendungen/ein-pfund-gehacktes-100.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://kinder.wdr.de/tv/wissen-macht-ah/sendungen/ein-pfund-gehacktes-100.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.13 (CPython) - Linux-4.14.52-v7+-armv7l-with-debian-9.4
[debug] exe versions: avconv 3.2.10-1, avprobe 3.2.10-1, ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ein-pfund-gehacktes-100: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ein-pfund-gehacktes-100: Downloading webpage
[generic] ein-pfund-gehacktes-100: Extracting information
ERROR: Unsupported URL: https://kinder.wdr.de/tv/wissen-macht-ah/sendungen/ein-pfund-gehacktes-100.html
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2324, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 172, column 2
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3298, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://kinder.wdr.de/tv/wissen-macht-ah/sendungen/ein-pfund-gehacktes-100.html
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- Playlist: https://kinder.wdr.de/tv/wissen-macht-ah/
- Single video: https://kinder.wdr.de/tv/wissen-macht-ah/sendungen/sendung-ueber-reste-100.html
- Single video: https://kinder.wdr.de/tv/wissen-macht-ah/sendungen/ein-pfund-gehacktes-100.html

---

### Description of your *issue*, suggested solution and other information

Something has changed for the WDR site. Until a couple of weeks, the URLs looked differently and worked. Now, if I try to download WDR videos, it no longer works.

What I found out until now:
1) WDR is still using a "master.m3u8 file for videos, so it should be possible to fix this
2) The "master.m3u8" link hides in a Javascript, e.g. for "ein Pfund gehacktes", it is in http://deviceids-medp.wdr.de/ondemand/174/1744817js, the link to that Javascript can be found with the CSS class "mediaLink video" (a simple grep)

**Comment by Xan-Kun** [comment]
I just encountered the same issue.
Example URL:
https://kinder.wdr.de/tv/die-sendung-mit-der-maus/av/video-lachgeschichte---der-kleine-maulwurf-schneemann-100.html
In the JavaScript file 
http://deviceids-medp.wdr.de/ondemand/135/1353468.js
there is the actual m3u8 URL:
wdradaptiv-vh.akamaihd.net/i/medp/ondemand/deChAt/fsk0/135/1353468/,1353468_15725209,1353468_15725213,1353468_15725211,1353468_15725210,1353468_15725212,.mp4.csmil/master.m3u8

If I give this URL to youtube-dl, the download starts and a perfectly fine file with the default name
NA_master.mp4
is created.
I guess the NA just means "not available", as there was obviously no meta-data to work with.
If someone could point in the right direction, I would be happy to try to get this feature implemented.

Thanks for the great software, keep the code coming :-)

**Comment by devurandom** [comment]
> I just encountered the same issue.
> Example URL:
> https://kinder.wdr.de/tv/die-sendung-mit-der-maus/av/video-lachgeschichte---der-kleine-maulwurf-schneemann-100.html

For "Die Sendung mit der Maus" see also: #16448
