### ISSUE TITLE
forbidden after about 6 hours or 3.7 gig filesize

### ISSUE THREAD

**Issue by ejonesss** [ytdl-org/youtube-dl#17987]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

it is the latest because i installed on october 20 2018 on an instance of osx 10.12 on vmware fusion.

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

i am saying other because i am not sure if it is a bug or something on youtube so if it is a bug you can upgrade the request to bug

after downloading a live stream https://www.youtube.com/watch?v=4PRCnWDhaxI overnight

this morning i got up to a 403 forbidden  sorry i did not capture the exact errors since i got a great run.

i renamed the file downloaded during the overnight so it would not be overwritten by a retest.

i retested and no forbidden errors so youtube did not ban me.

i looked at the file size and it was like 3.7 gig so i thought it was a file size limit of 4 gig on the mp4 container (suggestion  if it is a file size limit it would be nice if youtube-dl could split or remux into another container like mkv witch does not have a size limit (i have seen bluray rips run like 50 gig in mkv)

then i looked at the length of the file in player and it was just 30 seconds of the 6 hour limit of quicktime so maybe it is a time limit (again splitting or a different container like mkv).

if youtube is seeing the user agent and is banning youtube rippers  you may want to allow us to change the user agent string that is sent to youtube.

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by ejonesss** [comment]
update:

here is the error message i get at the end

D9BD1D016F6EBC16FEAD681EFDC8F.7EB68415600C49B5E36DD8B99A5D5DCF32672750/key/dg_yt0/playlist/index.m3u8' for reading
[https @ 0x7fcc6d509fc0] HTTP error 403 Forbidden
[hls,applehttp @ 0x7fcc6d803000] keepalive request failed for 'https://manifest.googlevideo.com/api/manifest/hls_playlist/id/4PRCnWDhaxI.0/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/r4---sn-2xouxaxq5u5-5cxs.googlevideo.com/playlist_type/DVR/ei/juPUW-_4Mtm08wSskrTwCg/gcr/us/mm/32/mn/sn-2xouxaxq5u5-5cxs/ms/lv/mv/u/pl/22/dover/11/playlist_duration/30/keepalive/yes/manifest_duration/30/beids/9466588/mt/1540677934/disable_polymer/true/ip/75.97.176.9/ipbits/0/expire/1540700142/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,playlist_type,ei,gcr,mm,mn,ms,mv,pl/signature/131870401B9D9BD1D016F6EBC16FEAD681EFDC8F.7EB68415600C49B5E36DD8B99A5D5DCF32672750/key/dg_yt0/playlist/index.m3u8', retrying with new connection: Server returned 403 Forbidden (access denied)
[https @ 0x7fcc6d512ec0] HTTP error 403 Forbidden
[hls,applehttp @ 0x7fcc6d803000] Failed to reload playlist 0
[https @ 0x7fcc6d512ec0] HTTP error 403 Forbidden
[hls,applehttp @ 0x7fcc6d803000] Failed to reload playlist 0
frame=647728 fps= 30 q=-1.0 Lsize= 3877871kB time=05:59:50.98 bitrate=1471.3kbits/s speed=   1x    
video:3528594kB audio:337359kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.308282%

**Comment by 1-877-448-4820** [comment]
It's not because of the size of the file. Every time I try it, I get a break from YouTube in (6 hours±10 seconds). [Version 2019.01.09](https://github.com/rg3/youtube-dl/releases/tag/2019.01.10) and still it does.

 Might be YouTube's “`Video paused. Continue watching?`” thingy. If that's the case, _youtube-dl_ should make some “interactions” repeatedly.

**Comment by DanGamingTV** [comment]
Unfortunately, YouTube only keeps stream urls valid for about 6 hours. To overcome this, you will need to repeatedly get new stream urls every 6 hours. I made a script that does this, hopefully it will work for you.
[Click here for the script](https://gist.github.com/DanGamingTV/3aff7feedb38bec9d859f9a5f29d982c)
