### ISSUE TITLE
AdultSwim - Unable to extract initial data

### ISSUE THREAD

**Issue by geitda** [ytdl-org/youtube-dl#18025]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
youtube-dl --verbose http://www.adultswim.com/videos/the-venture-bros/the-saphrax-protocol
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.adultswim.com/videos/the-venture-bros/the-saphrax-protocol']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.10.29
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg 3.4, ffprobe N-91206-g9827bb88e7-ffmpeg-windows-build-helpers
[debug] Proxy map: {}
[AdultSwim] the-saphrax-protocol: Downloading webpage
ERROR: Unable to extract initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "c:\python36\lib\site-packages\youtube_dl\extractor\common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "c:\python36\lib\site-packages\youtube_dl\extractor\adultswim.py", line 89, in _real_extract
    webpage, 'initial data'), display_id)
  File "c:\python36\lib\site-packages\youtube_dl\extractor\common.py", line 978, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

Does not require authorization credentials. Was working with other similar URLs (e.g. http://www.adultswim.com/videos/the-venture-bros/the-forecast-manufacturer) on 2018-10-23 with 2018.09.10. Tried the above today and neither 2018.09.10 nor 2018.10.29 work correctly.

**Comment by lordairivis** [comment]
Currently still broken with ```2018.11.03```

```[debug] System config: []```
```[debug] User config: []```
```[debug] Custom config: []```
```[debug] Command-line args: [u'--verbose', u'http://www.adultswim.com/videos/off-the-air/sound']```
```[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8```
```[debug] youtube-dl version 2018.11.03```
```[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-38-generic-x86_64-with-LinuxMint-19-tara```
```[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1```
```[debug] Proxy map: {}```
```[AdultSwim] sound: Downloading webpage```
```ERROR: Unable to extract initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```
```Traceback (most recent call last):```
```  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info ie_result = ie.extract(url)```
```  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract ie_result = self._real_extract(url)```
```  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adultswim.py", line 89, in _real_extract webpage, 'initial data'), display_id)```
```  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 983, in _search_regex raise RegexNotFoundError('Unable to extract %s' % _name)```
```RegexNotFoundError: Unable to extract initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```
