### ISSUE TITLE
"Blizzcon.com" Site Support Request

### ISSUE THREAD

**Issue by gorbiWTF** [ytdl-org/youtube-dl#18055]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.03**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Site support request (request for adding support for a new site)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://blizzcon.com/watch?v=5bc4202383792ad352e52f5a', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.11.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] watch?v=5bc4202383792ad352e52f5a: Requesting header
[redirect] Following redirect to https://blizzcon.com/en-us/watch?v=5bc4202383792ad352e52f5a
[generic] watch?v=5bc4202383792ad352e52f5a: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?v=5bc4202383792ad352e52f5a: Downloading webpage
[generic] watch?v=5bc4202383792ad352e52f5a: Extracting information
ERROR: Unsupported URL: https://blizzcon.com/en-us/watch?v=5bc4202383792ad352e52f5a
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://blizzcon.com/en-us/watch?v=5bc4202383792ad352e52f5a
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video (watchable for free): https://blizzcon.com/watch?v=5bc4202383792ad352e52f5a
- Single video (only with "Virtual Ticket"): https://blizzcon.com/watch?v=5bd6191dead09ac9b69f131d
- Playlist: There aren't any.

---

**Comment by pirate486743186** [comment]
It's all german and i don't understand german, so correct me. I understood, that you had to log in.That is free, but still need a paid virtual ticket.....

and it also uses DRM .....

**Comment by gorbiWTF** [comment]
> 
> 
> It's all german and i don't understand german, so correct me. I understood, that you had to log in.That is free, but still need a paid virtual ticket.....
> 
> and it also uses DRM .....

I edited my post and changed the links so they shouldn't be German any more. You don't have to login to watch the free videos, just for the paid content ("Virtual Ticket").

**Comment by 89z** [comment]
Issue should be closed, URLs are dead
