### ISSUE TITLE
[dl fail] Is netease module still being maintained?

### ISSUE THREAD

**Issue by inkuxuan** [ytdl-org/youtube-dl#18051]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Full command and output:

```
C:\Users\inkux\Desktop>youtube-dl https://music.163.com/#/song?id=33166366 --verbose --proxy ""
[debug] System config: []
[debug] User config: ['--proxy', 'socks5://[censored]/']
[debug] Custom config: []
[debug] Command-line args: ['https://music.163.com/#/song?id=33166366', '--verbose', '--proxy', '']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2018.10.29
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-90414-gabf35afb6f, ffprobe N-90414-gabf35afb6f
[debug] Proxy map: {}
[netease:song] 33166366: Downloading song info
[netease:song] 33166366: Checking song URL
[netease:song] 33166366: song URL is invalid, skipping
[netease:song] 33166366: Checking song URL
[netease:song] 33166366: song URL is invalid, skipping
[netease:song] 33166366: Checking song URL
[netease:song] 33166366: song URL is invalid, skipping
[netease:song] 33166366: Checking song URL
[netease:song] 33166366: song URL is invalid, skipping
[netease:song] 33166366: Checking song URL
[netease:song] 33166366: song URL is invalid, skipping
[netease:song] 33166366: Checking song URL
[netease:song] 33166366: song URL is invalid, skipping
[netease:song] 33166366: Checking song URL
[netease:song] 33166366: song URL is invalid, skipping
[netease:song] 33166366: Checking song URL
[netease:song] 33166366: song URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpadzwnijc\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpadzwnijc\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpadzwnijc\build\youtube_dl\extractor\neteasemusic.py", line 164, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpadzwnijc\build\youtube_dl\extractor\common.py", line 1287, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
------
I've noticed from the issue page that netease module had been down for quite a while in 2016, but since I got an instruction to report this and those issues are pretty aged, I decided to report it anyway.

I was downloading this song which is totally playable in my browser(Google Chrome), and is also downloadable as a mp3 file using netease client (PC, Android), of course using a Chinese IP address.

As you can see youtube-dl correctly recognized the ID of the song from its URL but has been unable to obtain any format.

And if this module is never going to be maintained for a period of time, I think it's a good idea to disable the module if it is believed it will never work again, so no one gets a bug report request when they see netease music in your support sites list and then fails to download using yt-dl, given that netease is a pretty popular music site in China.

------

**Comment by blackjack4494** [comment]
Well there I am. Pretty late but I randomly came across this extractor.

There are changes on netease (music.163.com). They changed endpoints and have more than one now. Also their response is different.

Song (data as in m4a) related api is
`https://music.163.com/weapi/song/enhance/player/url/v1?csrf_token=`
song details is now
`https://music.163.com/weapi/v3/song/detail?csrf_token=`
and so on. if there is enough interest I can update the extractor.

**Comment by DopefishJustin** [comment]
@blackjack4494 I for one would be interested. Tried to use it just now and came across this report.

**Comment by jarvis-666** [comment]
Hi, I think this is still not solved, because the traceback still remains the same, how can we start fixing this? There is also a geolocation restriction in this case.

**Comment by TianyiShi2001** [comment]
[This API](https://github.com/Binaryify/NeteaseCloudMusicApi) written in Node.js is able to get the real audio file URL with a given ID and quality. For example, https://api.moeblog.vip/163/ is a deployment of this API, and the real URL of the song with ID 29848621 can be got by `https://api.moeblog.vip/163/?type=url&id=29848621&br=128`. It worked.

Thus, examining the [Node.js API](https://github.com/Binaryify/NeteaseCloudMusicApi) will be helpful.

Geolocation restriction, like paid contents, seems to be unable to bypass, at least by this API.

I'll come back in a week after I finish my exams and try to fix this issue if no one else is going to do it.

**Comment by TianyiShi2001** [comment]
I've translated relevant parts of the Node.js API to python, and the following script is able to get the real music file URL with a given id (needs [pycrypto](https://pypi.org/project/pycrypto/)):

```python
import requests
import json
from hashlib import md5
from Crypto.Cipher import AES
import Crypto
import time
from random import randint

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Linux; U; Android 9; zh-cn; Redmi Note 8 Build/PKQ1.190616.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.141 Mobile Safari/537.36 XiaoMi/MiuiBrowser/12.5.22",
    "Content-Type": "application/x-www-form-urlencoded",
    "Referer": "https://music.163.com",
}


KEY = "e82ckenh8dichen8"


def pad(data):
    pad = 16 - len(data) % 16
    return data + pad * chr(pad)


def make_data_and_headers(song_id):
    KEY = "e82ckenh8dichen8"
    URL = "/api/song/enhance/player/url"
    cookie = {
        "osver": None,
        "deviceId": None,
        "appver": "8.0.0",
        "versioncode": "140",
        "mobilename": None,
        "buildver": "1623435496",
        "resolution": "1920x1080",
        "__csrf": "",
        "os": "pc",
        "channel": None,
        "requestId": f"{int(time.time()*1000)}_{randint(0, 1000):04}",
    }
    text = json.dumps(
        {"ids": f"[{song_id}]", "br": 999000, "header": cookie},
        separators=(",", ":"),
    )
    message = f"nobody{URL}use{text}md5forencrypt"
    m = md5()
    m.update(message.encode("latin1"))
    digest = m.hexdigest()

    data = f"{URL}-36cd479b6b5-{text}-36cd479b6b5-{digest}"

    data = '/api/song/enhance/player/url-36cd479b6b5-{"ids":"[33894312]","br":999000,"header":{"appver":"8.0.0","versioncode":"140","buildver":"1623455100","resolution":"1920x1080","__csrf":"","os":"pc","requestId":"1623455100782_0489"}}-36cd479b6b5-a036727d6cb4f68dc27d0e1962f56eb8'

    data = pad(data)

    cipher = Crypto.Cipher.AES.new(KEY, AES.MODE_ECB)
    encrypted = cipher.encrypt(data.encode("latin1"))

    headers = HEADERS
    process_v = lambda v: v if v is not None else "undefined"
    headers.update(
        {"Cookie": "; ".join([f"{k}={process_v(v)}" for [k, v] in cookie.items()])}
    )
    return (f"params={encrypted.hex().upper()}", headers)


if __name__ == "__main__":
    song_id = input("song_id? (default to 491233178)")
    if not song_id:
        song_id = 491233178
    data, headers = make_data_and_headers(491233178)
    # print(data)
    # print(headers)
    r = requests.post(
        "https://interface3.music.163.com/eapi/song/enhance/player/url",
        data=data,  # json.dumps(data, separators=(",", ":")),
        headers=HEADERS,
    )
    print(r.json())
```

The next challenge is to adapt it into youtube-dl
