### ISSUE TITLE
Site Request for dlive.tv

### ISSUE THREAD

**Issue by nyanmeister** [ytdl-org/youtube-dl#18080]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```

$ youtube-dl --version
2018.11.03

$ youtube-dl -v https://dlive.tv/p/theralphretort+2odT12WRg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://dlive.tv/p/theralphretort+2odT12WRg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.03
[debug] Python version 3.5.3 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9.5
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[generic] theralphretort+2odT12WRg: Requesting header
WARNING: Falling back on generic information extractor.
[generic] theralphretort+2odT12WRg: Downloading webpage
[generic] theralphretort+2odT12WRg: Extracting information
ERROR: Unsupported URL: https://dlive.tv/p/theralphretort+2odT12WRg
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/generic.py", line 3298, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://dlive.tv/p/theralphretort+2odT12WRg

```

---
- Single video: https://dlive.tv/p/theralphretort+2odT12WRg
- Playlist: N/A
---

**Comment by ksjk1998** [comment]
hey, just wanted to let you know that a hotfix for this is to veiw the page source, ctrl+f ".m3u8", copy/paste the link, change unicode escape characters like \\u002F to their actual characters. (replace \\u002F to /). and execute

**Comment by CeruleanSky** [comment]
For the live stream, you can get the m3u8 from the url as follows:

re.compile(r'^https?://(?:www.)?dlive.tv/(\w+).*$')
username = _RE_URL.match(url).group(1)
m3u8 = 'https://live.dlivecdn.com/hls/live/{0}.m3u8'.format(username)

The live.dlivecdn.com m3u8 will contain as such as "https://mn-nl-glb.mncdn.com/dlive/transcode-X-XXX/username/playlist.m3u8" which will 404 when the livestream is offline.

youtube-dl works fine with a direct link to https://live.dlivecdn.com/hls/live/{0}.m3u8'.format(username) when the stream is online.

**Comment by nyanmeister** [comment]
> For the live stream, you can get the m3u8 from the url as follows:
> 
> re.compile(r'^https?://(?:www.)?dlive.tv/(\w+).*$')
> username = _RE_URL.match(url).group(1)
> m3u8 = '[https://live.dlivecdn.com/hls/live/{0}.m3u8'.format(username)](https://live.dlivecdn.com/hls/live/%7B0%7D.m3u8'.format(username))
> 
> The live.dlivecdn.com m3u8 will contain as such as "https://mn-nl-glb.mncdn.com/dlive/transcode-X-XXX/username/playlist.m3u8" which will 404 when the livestream is offline.
> 
> youtube-dl works fine with a direct link to [https://live.dlivecdn.com/hls/live/{0}.m3u8'.format(username)](https://live.dlivecdn.com/hls/live/%7B0%7D.m3u8'.format(username)) when the stream is online.

Thanks for the details! Been using the .m3u8 bit since the other user suggested it, until the site gets more official support.

**Comment by kebabkalle** [comment]
Any progress on this one?

**Comment by ealgase** [comment]
@kebabkalle working on it

**Comment by babadoctor** [comment]
Updates?

**Comment by ealgase** [comment]
I need to find a way to properly extract the dictionary keys.

**Comment by mayeaux** [comment]
+1 for this!
