### ISSUE TITLE
VVVVID: add support for playlists

### ISSUE THREAD

**Issue by percheperche** [ytdl-org/youtube-dl#18130]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www
.vvvvid.it/#!show/845/sword-art-online-alicization']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.11.07
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-92356-g89a0d33e3a, ffprobe N-92356-g89a0d33e3a, r
tmpdump 2.5
[debug] Proxy map: {}
[generic] sword-art-online-alicization: Requesting header
WARNING: Falling back on generic information extractor.
[generic] sword-art-online-alicization: Downloading webpage
[generic] sword-art-online-alicization: Extracting information
ERROR: Unsupported URL: https://www.vvvvid.it/#!show/845/sword-art-online-aliciz
ation
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\bu
ild\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\bu
ild\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\bu
ild\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.vvvvid.it/#!show
/845/sword-art-online-alicization
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: Already working
- Playlist: https://www.vvvvid.it/#!show/845/sword-art-online-alicization
Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I want download a playlist from VVVVID, but it doesn't support it. I have tried with and without putting my credentials with no results.

**Comment by pjammo** [comment]
Referrence: [VVVVID-Downloader](https://github.com/CoffeeStraw/VVVVID-Downloader)

**Comment by ale5000-git** [comment]
Hi, has the season detection been fixed?

**Comment by remitamine** [comment]
yes, it will be supported in the next version(thank to the work done by @nixxo).

**Comment by ale5000-git** [comment]
@remitamine
Hi, unfortunately season detection still doesn't work with release 2020.12.31, sample link: `https://www.vvvvid.it/show/892/sword-art-online-alicization-war-of-underworld/1545/693801/nelle-terre-del-nord`.
The filename is `...SwordArtOnline_S04Ep01...` but it incorrectly detect S01.

**Comment by nixxo** [comment]
@ale5000-git 

unfortunately thats a problem of vvvvid website.
```
[VVVVID] 693801: Downloading JSON metadata
#0 dict(30)
    ['season_id'] => int(1545)
    ['number'] => str(2) "01"
    ['show_title'] => str(49) "Sword Art Online: Alicization - War of Underworld"
    ['seen'] => bool(False)
    ['season_number'] => int(1)
    ['show_id'] => int(892)
    ['show_type'] => int(4)
    ['ondemand_type'] => int(3)
    ['id'] => int(11930)
    ['video_id'] => int(693801)
```

as you can see from the data downloaded trom the vvvvid website the seson_number value is 1 (one).

the s04e01 part is only found in the m3u8 manifest url.

I'll do some test with other show to check if it's something shared across the website.

**Comment by remitamine** [comment]
the patterns that i found so far are, `Ep\d+` and `S\d+Ep\d+`, i already prepared a patch for this.

**Comment by nixxo** [comment]
ok, I was doing it as well.

I'm also looking at #27601.

**Comment by ale5000-git** [comment]
Thanks.
