### ISSUE TITLE
sibnet.ru does not download

### ISSUE THREAD

**Issue by LyoSU** [ytdl-org/youtube-dl#18182]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl https://video.sibnet.ru/rating/video3485877-Kot_i_nevidimaya_pregrada/%D1%8D/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://video.sibnet.ru/rating/video3485877-Kot_i_nevidimaya_pregrada/%D1%8D/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.07
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1
[debug] Proxy map: {}
[generic] э: Requesting header
WARNING: Falling back on generic information extractor.
[generic] э: Downloading webpage
[generic] э: Extracting information
[generic] э: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[generic] э: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://video.sibnet.ru/shell.php?videoid=3485877'
[download] Destination: Кот и невидимая преграда-shell.php
[download] 100% of 9.52KiB in 00:00
```

Video from the site is loaded as php instead of the video itself. This is clearly visible on the penultimate line. I saw that you were previously addressed with this problem, but the question was supposedly closed by a duplicate. The problem still exists, tested on version 2018.11.07

**Comment by BladeMight** [comment]
I can confirm this with version ` 2018.11.23 `, looks like they updated the player data, now it doesn't include the key and other parameters, 
 e.g.: 
>https://dv25.sibnet.ru/32/29/93/3229930.m3u8?st=MXCJ_3JuXXVBtPKw2_Tvbw&e=1543369000&stor=25&noip=1&start=

became:

>https://video.sibnet.ru/v/5be6d130afd927ae6241de07cdd78f12/3464673.m3u8

And without these keys it returns 403 - forbidden.

**Comment by BladeMight** [comment]
I created some bash script which retrieves direct URL and video title from Sibnet video URL: (codename **cusi**, from **CU**rl and **SI**bnet)

### cusi

```bash
#!/bin/bash
url="$1"
H1="Accept-Encoding: identity;q=1, *;q=0"
H2="Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6,zh;q=0.5"
H3="User-Agent: Mozilla/5.0 (Linux; Android 4.4.2; Nexus 4 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.114 Mobile Safari/537.36"
H4="chrome-proxy: frfr"
H5="Accept: */*"
H6="Connection: keep-alive"
H7="Range: bytes=0-"
H8="Referer: $url"
resp=$(curl -s -H "$H1" -H "$H2" -H "$H3" -H "$H4" -H "$H5" -H "$H6" -H "$H7" --compressed "$url" | iconv -f cp1251 -t utf-8 )
accepturl=$(echo "$resp" | grep -iP '\d+\.mp4' | sed -re 's/.*(\/v\/.*?mp4)", type.*/https:\/\/video.sibnet.ru\1/g')
title=$(echo "$resp" | grep -iP '<title>' | sed -re 's/.*<title>(.*?)<\/title>.*/\1/g')
echo "Video-Title: $title"
echo "Accept-URL: $accepturl"
directurl=$(curl -I "$accepturl" -s -H "$H1" -H "$H2" -H "$H3" -H "$H4" -H "$H5" -H "$H6" -H "$H7" -H "$H8" --compressed | awk 'BEGIN{IGNORECASE=1} match($0, /location: (.*)/, z) {printf "https:%s", z[1]}')
echo "Direct-URL: $directurl"
```

Use it like this:

```bash
cusi 'https://video.sibnet.ru/rating/video3485877-Kot_i_nevidimaya_pregrada/%D1%8D/'
Video-Title: Кот и невидимая преграда - видео ролик смотреть на Video.Sibnet.Ru
Accept-URL: https://video.sibnet.ru/v/b191e90609fb5399adb254d0b25d84e5/3485877.mp4
Direct-URL: https://dv98.sibnet.ru/32/46/57/3246579.mp4?st=4stkVc1w1SUE6q_GTlmfzw&e=1551123000&stor=26&noip=1
```

**Comment by bato3** [comment]
one header what you need is `"Referer`

```
youtube-dl https://video.sibnet.ru/shell.php?videoid=3422904 --add-header "Referer: https://video.sibnet.ru/shell.php?videoid=3422904" 
```

btw @BladeMight in current cusi you remove 2 first lines and I have error:
 `awk: line 1: syntax error at or near ,`

**Comment by BladeMight** [comment]
@bato3 Somehow two lines were out in cusi... Btw, I created repository: [BladeMight/cusi](https://github.com/BladeMight/cusi), and added some other scripts. 
I measured the Sibnet download speed of youtube-dl's (MPD/m3u8) and cusi's (direct mp4) and seems like cusi + aria2c is 6-8 faster:
- youtube-dl - 300~400KB
- cusi+aria2c- ~2500KB(my maximum speed)

**Comment by professeurjt** [comment]
yt-dl not working for sibnet , I just tried a simple method and it works well if it helps you to be able to download from sibnet; I don't know if I have the right to leave you the link! but hey I just do it if it can help. Thank you and good day.

youtu.be/xbRl8Vs7pkE
