### ISSUE TITLE
Exclude dubs in crunchyroll download

### ISSUE THREAD

**Issue by PonyFlare** [ytdl-org/youtube-dl#18235]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Is there a simple way to exclude dubs (or choose a specific one) from a crunchyroll download?
[Durara](https://www.crunchyroll.com/durarara), for example, has both Japanese and English available, but there is only a single page - so it should be downloading everything in both languages if I point youtube-dl to that url. 
[Dragon Maid](https://www.crunchyroll.com/miss-kobayashis-dragon-maid) would be even worse without a filter, since it has a total of 5 languages.

I could of course choose each episode I want to download individually (and will if I have to), but I'm looking for something I can add to the command line to do it automatically.

**Comment by PonyFlare** [comment]
Ah, thanks. 

> hls-audio-frFR-hardsub-frFR-401   mp4        428x240    [frFR]  401k , avc1.42c015, 23.974fps, mp4a.40.2
> hls-audio-frFR-hardsub-frFR-547   mp4        640x360    [frFR]  547k , avc1.4d401e, 23.974fps, mp4a.40.2
> hls-audio-frFR-hardsub-frFR-1008  mp4        848x480    [frFR] 1008k , avc1.4d401f, 23.974fps, mp4a.40.2
> hls-audio-frFR-hardsub-frFR-2525  mp4        1280x720   [frFR] 2525k , avc1.640028, 23.974fps, mp4a.40.2
> hls-audio-frFR-hardsub-frFR-5778  mp4        1920x1080  [frFR] 5778k , avc1.640028, 23.974fps, mp4a.40.2
> hls-audio-frFR-401                mp4        428x240    [frFR]  401k , avc1.42c015, 23.974fps, mp4a.40.2
> hls-audio-frFR-547                mp4        640x360    [frFR]  547k , avc1.4d401e, 23.974fps, mp4a.40.2
> hls-audio-frFR-1009               mp4        848x480    [frFR] 1009k , avc1.4d401f, 23.974fps, mp4a.40.2
> hls-audio-frFR-2526               mp4        1280x720   [frFR] 2526k , avc1.640028, 23.974fps, mp4a.40.2
> hls-audio-frFR-5781               mp4        1920x1080  [frFR] 5781k , avc1.640028, 23.974fps, mp4a.40.2 (best)

and further down... 

> ...
> hls-audio-jaJP-6422-1               mp4        1920x1080  [jaJP] 6422k , avc1.640028, 23.974fps, mp4a.40.2
> hls-audio-jaJP-6422-2               mp4        1920x1080  [jaJP] 6422k , avc1.640028, 23.974fps, mp4a.40.2 (best)

So a filter for [format_id*=jaJP] seems to work. Problem is it still goes through every single file and errors if specified format is not available. This means a need for -i and much extra wait time while it goes through each video. It keeps it entirely automated past giving the URL, at least.

**Comment by Yavos** [comment]
A possible solution/workaround might be to use the `--playlist-start` and `--playlist-end` parameters.
Since what videos will be shown is depending on your link (country code used) and it seems to always start at the bottom you could just do a little math and figure out what to skip.

Also given the country code in playlists is working (should be fixed soon) you could filter a bit by that.
