### ISSUE TITLE
[twitch:vod] Cannot download subscriber vods

### ISSUE THREAD

**Issue by flugasak** [ytdl-org/youtube-dl#18245]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.18**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'best', u'--cookies', u'../cookies-2018-11-19.txt', u'https://www.twitch.tv/videos/335626867', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.18
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-34-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: avconv 2.8.15-0ubuntu0.16.04.1, avprobe 2.8.15-0ubuntu0.16.04.1, ffmpeg 2.8.15-0ubuntu0.16.04.1, ffprobe 2.8.15-0ubuntu0.16.04.1
[debug] Proxy map: {}
[twitch:vod] 335626867: Downloading vod info JSON
[twitch:vod] 335626867: Downloading vod access token
[twitch:vod] 335626867: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 403: ERROR (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 605, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

...
<end of log>
```

---

### Cannot download subscriber VODs

While trying to download subsriber VODs I get the error listed above. I've tried on two separate machines and a few different VOD URLs, but all from the same channel (since I'm only subscribed to that particular channel). 

I'm aware that debugging this requires a paid subscription, but I'm hoping since it's twitch that won't be a problem.

**Comment by sylware** [comment]
extractors for live stream lists (per game/etc) is required for noscript/light www browsers.
That said, I cannot open a new issue anymore on github with a noscript/light browser (probably some recent microsoft rotten work)

**Comment by flugasak** [comment]
> extractors for live stream lists (per game/etc) is required for noscript/light www browsers.
> That said, I cannot open a new issue anymore on github with a noscript/light browser (probably some recent microsoft rotten work)

Mind elaborating? 

I'm not a developer, I just figured I'd report the bug. Are you saying there has to be a livestream list extractor for the twitch extractor to work?

.. and how does Microsoft relate to this..?

**Comment by flugasak** [comment]
> There are 2 separate issues, github/microsoft relates to the second one.

So, in other words, you issues have nothing to do with the bug I reported. 

You're choosing to use a browser that doesn't support javascript, so you instead post your feature-request into my bug report.

May I suggest you set up a browser that supports scripts, with which you can add feature-requests? At least that way you wouldn't have to muck up the todo lists for git projects? =/

**Comment by sylware** [comment]
On Wed, Nov 28, 2018 at 09:15:35PM -0800, flugasak wrote:
> > There are 2 separate issues, github/microsoft relates to the second one.
> 
> So, in other words, you issues have nothing to do with the bug I reported. 
> 
> You're choosing to use a browser that doesn't support javascript, so you instead post your feature-request into my bug report.
> 
> May I suggest you set up a browser that supports scripts, with which you can
> add feature-requests? At least that way you wouldn't have to muck up the todo
> lists for git projects? =/

If microsoft did not break the support of noscript browsers on github for new
issues (was working fine before microsoft took control of it) , I wouldn't have
jumped into an issue that "look alike" what I would need from youtube-dl.

You don't understand why noscript browsers are so important to support, I was
like you a few years ago. That said, I use youtube-dl _because_ I run noscript
browsers (it allows me to setup a neat modular browsing experienced).

Then: I'll try to contact youtube-dl coders to suggest them to move to a platform
which has noscript browser support.

I have to apologize to you though: I should have not hijacked your issue, but
this browser support red line makes myself behave inappropriately.

**Comment by dirkf** [comment]
Stale, multiple reworks since this version.
