### ISSUE TITLE
[Feature request] Extra flags for GUI applications embedding youtube-dl on Windows

### ISSUE THREAD

**Issue by Faith001** [ytdl-org/youtube-dl#18311]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---

### Description of your *issue*, suggested solution and other information
Every time we get to conversion with ffmpeg, a console window opens up for the remainder of ffmpeg's operation due to the way Windows handles new processes being spawned.

Would it be possible for an extra extra option to be passed when embedding youtube-dl, denoting that the application is graphical so that the calls to the postprocessor can go from

https://github.com/rg3/youtube-dl/blob/d19600df07128c73ef7242af7e1cd8c819951aba/youtube_dl/postprocessor/ffmpeg.py#L164

https://github.com/rg3/youtube-dl/blob/d19600df07128c73ef7242af7e1cd8c819951aba/youtube_dl/postprocessor/ffmpeg.py#L199

to

`  handle = subprocess.Popen(cmd, stderr=compat_subprocess_get_DEVNULL(), stdout=subprocess.PIPE, stdin=subprocess.PIPE, creationflags=0x08000000)
`

and

`
p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE, creationflags=0x08000000)
`

respectively.

Where ` 0x08000000 ` is ` CREATE_NO_WINDOW ` as per https://docs.microsoft.com/en-us/windows/desktop/procthread/process-creation-flags

This would also require a platform check since this would only work on Windows.
I've tried this and it works , would've made a pull request but I'm not too familiar with the codebase, just managed to track down where and how ffmpeg was being called to patch it for myself.

**Comment by dirkf** [comment]
Continued in #22627, with a work-around.
