### ISSUE TITLE
Is the site "animeheaven.eu" considered under copyright infringement?

### ISSUE THREAD

**Issue by njscorpion** [ytdl-org/youtube-dl#18378]
Is the site "animeheaven.eu" considered under copyright infringement?

If yes please go ahead and close this issue. Thank you.

Otherwise please conseder this a site request.

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.03**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://animeheaven.eu/watch.php?a=Qualidea%20Code']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.12.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 3.4
[debug] Proxy map: {}
[generic] watch: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch: Downloading webpage
[generic] watch: Extracting information
ERROR: Unsupported URL: http://animeheaven.eu/watch.php?a=Qualidea%20Code
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\generic.py", line 3318, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://animeheaven.eu/watch.php?a=Qualidea%20Code
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://animeheaven.eu/watch.php?a=Qualidea%20Code&e=9
- Playlist: http://animeheaven.eu/i.php?a=Qualidea%20Code [Don't think this would be considered as a valid play list but still!]

Thank you!

**Comment by percheperche** [comment]
definetely illegal

**Comment by percheperche** [comment]
and there is already a download function
