### ISSUE TITLE
Downloading explicit dailymotion fail

### ISSUE THREAD

**Issue by coffeecore** [ytdl-org/youtube-dl#18398]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*
---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
➜ youtube-dl --verbose --netrc -F https://www.dailymotion.com/embed/video/x27ibq7
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--netrc', u'-F', u'https://www.dailymotion.com/embed/video/x27ibq7']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.03
[debug] Python version 2.7.15 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[dailymotion] x27ibq7: Downloading webpage
[dailymotion] x27ibq7: Downloading metadata JSON
ERROR: dailymotion said: Contenu Explicite
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 206, in _real_extract
    self._check_error(metadata)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 347, in _check_error
    '%s said: %s' % (self.IE_NAME, title), expected=True)
ExtractorError: dailymotion said: Contenu Explicite
```

---

### Description of your *issue*, suggested solution and other information

I can't download explicit video from Dailymotion when I provide `.netrc`. Youtube-dl looks getting page and after use credentials in .netrc, but video is marked explicit, so you must be login to watch it

And thanks you for your awesome app.

**Comment by ealgase** [comment]
Does logging in with `--username` and `--password` work?

**Comment by coffeecore** [comment]
No, same error. Program gets metadata before to log in ?

**Comment by coffeecore** [comment]
Ok, I understand problem. Url to get metada has `embedder=https%3A%2F%2Fwww.dailymotion.com%2Fvideo%2Fx6ycmii`. If I remove it, I can get metada, even if video is marked Explicit.

Possible to remove this if you set `--age-limit` to 18 or 21 ? Or I'm just lucky it works ?
