### ISSUE TITLE
[NRK] Ambiguous subtitle duration thousands

### ISSUE THREAD

**Issue by forthrin** [ytdl-org/youtube-dl#18399]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.03**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
- [X] Bug report (encountered problems with youtube-dl)

```
$ youtube-dl --write-sub --sub-lang no --convert-subtitles srt --verbose https://tv.nrk.no/serie/unge-lovende/sesong/4/episode/2/avspiller
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--write-sub', u'--sub-lang', u'no', u'--convert-subtitles', u'srt', u'--verbose', u'https://tv.nrk.no/serie/unge-lovende/sesong/4/episode/2/avspiller']
[debug] Encodings: locale UTF-8, fs utf-8, out utf8, pref UTF-8
[debug] youtube-dl version 2018.12.03
[debug] Python version 2.7.15 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://nordond34c-f.akamaihd.net/i/no/open/ps/km/kmte20006218/kmte20006218ca/kmte20006218ca_,141,316,563,1266,2250,.mp4.csmil/index_4_av.m3u8?null=0'
```

Please see the subtitles at: https://undertekst.nrk.no/prod/KMTE20/00/KMTE20006218CA/TMP/KMTE20006218CA.ttml

      <p begin="00:01:59.320" dur="00:00:04.60" style="left">-Vil dere ha dette?<br />-Det tar vi etterpå.</p>
      <p begin="00:02:03.680" dur="00:00:04.940" style="left">Jeg tenkte du skulle<br />sitte der og Elise her.</p>

Notice the duration that ends with ".60". When converting to `.srt`, youtube-dl incorrectly interprets this as ".600" rather than the ".060" evidently intended by the author, causing several subtitles to overrun the succeeding subtitle, which in turn makes VLC annoyingly display the subtitles over each other. The problem applies for all subtitled videos on the entire site, so it's a major nuisance.

**Comment by evexoio** [comment]
04.60 *is* 04.600

I don't get it, why would we convert .60 to .060? isn't this a mistake from the subtitles author end?

**Comment by forthrin** [comment]
@evexoio: They probably do something like `sprintf("...:%d", thousands)` rather than `sprint("...:%03d", thousands)`. So you could argue both ways, really. Asking for a fix here seemed easier them asking a major broadcaster. Will fixing it break any other sites?

**Comment by forthrin** [comment]
```
diff --git a/youtube_dl/utils.py b/youtube_dl/utils.py
index 0c830ba71..64082114f 100644
--- a/youtube_dl/utils.py
+++ b/youtube_dl/utils.py
@@ -2642,5 +2642,5 @@ def parse_dfxp_time_expr(time_expr):
 
-    mobj = re.match(r'^(\d+):(\d\d):(\d\d(?:(?:\.|:)\d+)?)$', time_expr)
+    mobj = re.match(r'^(\d+):(\d\d):(\d\d)\.(\d+)$', time_expr)
     if mobj:
-        return 3600 * int(mobj.group(1)) + 60 * int(mobj.group(2)) + float(mobj.group(3).replace(':', '.'))
+        return 3600 * int(mobj.group(1)) + 60 * int(mobj.group(2)) + int(mobj.group(3)) + float("%03d" % int(mobj.group(4))) / 1000
```

**Comment by evexoio** [comment]
@forthrin can you open a PR please?

**Comment by forthrin** [comment]
@evexoio: The patch above should do the trick. Happy to help.

**Comment by forthrin** [comment]
@dstftw: Could this patch be applied?

**Comment by forthrin** [comment]
In `test/test_utils.py` around line 1245, XML `00:00:02.08` wants to assert as `00:00:02,080`, whereas for NRK, this would mean `00:00:02,008`. Which site does the XML in the test code come from? Or more to the point, for how many sites does "08" mean "080" as opposed to "008"? I would say that anything else than three thousand digits is ambiguous and therefore invalid. However, we can't expect the sites to change their data, so how should the code handle this? I can think of two possible ways:

1. Let extractors call the subtitle converter with a flag saying how to interpret invalid data.
2. Validate the time codes on a general basis so overlapping time codes are made non-overlapping.

**Comment by forthrin** [comment]
I've found a way to get around the issue.

The site provides two subtitle formats, VTT and TTML, where only the latter has the thousands issue.

However, youtube-dl doesn't pick up the VTT file, because the site metadata points to a m3u8 file, which again points to a VTT file. This may be non-standard, but that's how they do it.

By jumping ahead to VTT file and adding `--sub-format vtt/ttml` on the command line, the problem disappears.

I am not proud of this dirty code, as I assume it breaks with several internal programming conventions, but I couldn't find any other way to do it at the moment, and it works.

Maybe someone can suggest a way to clean up the code, so it can be submitted to the project?

```
diff --git a/youtube_dl/extractor/nrk.py b/youtube_dl/extractor/nrk.py
index 072f920a9..7a120376a 100644
--- a/youtube_dl/extractor/nrk.py
+++ b/youtube_dl/extractor/nrk.py
@@ -4,2 +4,3 @@ from __future__ import unicode_literals
 import re
+import os
 
@@ -18,2 +19,3 @@ from ..utils import (
     try_get,
+    determine_ext,
 )
@@ -78,5 +80,12 @@ class NRKBaseIE(InfoExtractor):
                     subtitle_url = asset.get('%sSubtitlesUrl' % subtitle)
+                    subtitle_url = compat_urllib_parse_unquote(subtitle_url)
                     if subtitle_url:
+                        ext = determine_ext(subtitle_url)
+                        if ext == "m3u8":
+                            m3u8 = self._download_webpage(subtitle_url, ext)
+                            head = os.path.dirname(subtitle_url)
+                            tail = re.findall(r'(?i)(.*\.vtt)', m3u8)[0]
+                            subtitle_url = '%s/%s' % (head, tail)
                         subtitles.setdefault('no', []).append({
-                            'url': compat_urllib_parse_unquote(subtitle_url)
+                            'url': subtitle_url
                         })
diff --git a/youtube_dl/utils.py b/youtube_dl/utils.py
index 08af57bae..a203a7e19 100644
--- a/youtube_dl/utils.py
+++ b/youtube_dl/utils.py
@@ -2760,2 +2760,5 @@ def parse_dfxp_time_expr(time_expr):
 
+    if re.match(r'\D\d{1,2}$', time_expr):
+        print('NOTICE: Ambiguous timecode in subtitles: ' + time_expr)
+
     mobj = re.match(r'^(\d+):(\d\d):(\d\d(?:(?:\.|:)\d+)?)$', time_expr)
```
