### ISSUE TITLE
Lecturio Error: ERROR: unable to open for writing: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by cr7mmsa** [ytdl-org/youtube-dl#18502]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.09**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v --cookies cookies.txt https://app.lecturio.com/medical-courses/sympathetic-nervous-system-hypothalamus-as-sympathetic-output-driver-and-horners-syndrome.lecture
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'cookies.txt', 'https://app.lecturio.com/medical-courses/sympathetic-nervous-system-hypothalamus-as-sympathetic-output-driver-and-horners-syndrome.lecture']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.12.09
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[Lecturio] sympathetic-nervous-system-hypothalamus-as-sympathetic-output-driver-and-horners-syndrome: Downloading webpage
[Lecturio] sympathetic-nervous-system-hypothalamus-as-sympathetic-output-driver-and-horners-syndrome: Downloading JSON metadata
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://d31o3fxohn22zc.cloudfront.net/1606232300-120216-o-20160608_01_04_Neuroanatomy_Canby_Craig-v1-st1.mp4?Expires=1544654246&Key-Pair-Id=APKAJXIJCNEVQLT2FFDQ&Signature=YWzTuD8mNGw68iB-QbOoTD9KBqucYYpqxAqmTZWEdTgk51qxFF5QkHKEus6cYZAklaRvWbZwpa29i0KOW1AdxS6fANZTAMoWlKGsOg8bv3iAkRwkf99aXh1HZTGPJ11L00WAsIdgw5akp~PwkuAHm4dQafsfBsQ~Z-LGRZBhMNE_'
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'Sympathetic Nervous System (SNS) - Hypothalamus as Sympathetic Output Driver and Horners Syndrome-24454.mp4.part'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg8efod20\build\youtube_dl\downloader\http.py", line 250, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg8efod20\build\youtube_dl\utils.py", line 458, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'Sympathetic Nervous System (SNS) - Hypothalamus as Sympathetic Output Driver and Horners Syndrome-24454.mp4.part'
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
The error message is self-explanatory.

**Comment by freecorvette** [comment]
I was intrigued to get this particular error (`ERROR: unable to open for writing: [Errno 2] No such file or directory`) while running youtube-dl from a specific directory, but not from another. It turned out that the movie had a long name and, along with the first directory name, led to a path that was longer than the [maximum path length allowed in Windows, which is 260 characters](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file):

> In the Windows API (with some exceptions discussed in the following paragraphs), the maximum length for a path is MAX_PATH, which is defined as 260 characters. A local path is structured in the following order: drive letter, colon, backslash, name components separated by backslashes, and a terminating null character.

**Comment by dirkf** [comment]
See #29912.
