### ISSUE TITLE
Support request for vidmoly.me

### ISSUE THREAD

**Issue by irfantogluk** [ytdl-org/youtube-dl#18535]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
root@server:~# youtube-dl -v https://vidmoly.me/d/awldnru3yq2c
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vidmoly.me/d/awldnru3yq2c']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.6 (CPython) - Linux-4.15.0-36-generic-x86_64-with-Ubu                                                                                        ntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.0                                                                                        4.1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[generic] awldnru3yq2c: Requesting header
WARNING: Falling back on generic information extractor.
[generic] awldnru3yq2c: Downloading webpage
[generic] awldnru3yq2c: Extracting information
ERROR: Unsupported URL: https://vidmoly.me/d/awldnru3yq2c
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/generic.py", line 3151, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://vidmoly.me/d/awldnru3yq2c

```

**Comment by irfantogluk** [comment]
Embedded URL format:
```
root@server:~# youtube-dl https://vidmoly.me/embed-mpt4u4h31h2d.html
[generic] embed-mpt4u4h31h2d: Requesting header
WARNING: Falling back on generic information extractor.
[generic] embed-mpt4u4h31h2d: Downloading webpage
[generic] embed-mpt4u4h31h2d: Extracting information
ERROR: Unsupported URL: https://vidmoly.me/embed-mpt4u4h31h2d.html
```

**Comment by irfn-net** [comment]
Any progress?

**Comment by keremcankabadayi** [comment]
+1

**Comment by isidentical** [comment]
+1

**Comment by elbasan** [comment]
+1

**Comment by etherx-dev** [comment]
works with https://github.com/yt-dlp/yt-dlp if you're still wondering

**Comment by dirkf** [comment]
Anyone who wants this should complete a new Site Support Request with valid test URLs: #30839.

**Comment by Vangelis66** [comment]
> Anyone who wants **this**

... FWIW, **vidmoly**'s [ToS](https://vidmoly.me/tos) explicitly state: 

> You will not use any automated system, **software**, or device to **index**, compile, collect or **copy any content residing on servers used by the Service**

Make what you want of that 😜 ...

**Comment by dirkf** [comment]
So no web browsers, then?
