### ISSUE TITLE
Jamendo Playlists

### ISSUE THREAD

**Issue by kousu** [ytdl-org/youtube-dl#18564]
### Checklist

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

Jamendo support was merged a couple years ago (#10132) but it doesn't work -- or at least, doesn't currently work -- on albums, the same way bandcamp and youtube playlists do. I assume the parser needs tweaking now I guess? It just says there's 0 tracks found.

### Site Examples

https://www.jamendo.com/album/68337/timeless-piano-dreams

```
$ youtube-dl  -v https://www.jamendo.com/album/68337/timeless-piano-dreams
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.jamendo.com/album/68337/timeless-piano-dreams']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.09
[debug] Python version 3.7.1 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[JamendoAlbum] timeless-piano-dreams: Downloading webpage
[download] Downloading playlist: Vladimir Sterzer - Timeless Piano Dreams
[JamendoAlbum] playlist Vladimir Sterzer - Timeless Piano Dreams: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: Vladimir Sterzer - Timeless Piano Dreams
```

**Comment by bugsug** [comment]
I experience the same issue, maybe there's a problem with the regex filtering the track ids out: `r'<a[^>]+href=(["\'])(?P<path>(?:(?!\1).)+)\1[^>]+class=["\'][^>]*js-trackrow-albumpage-link'`

**Comment by bugsug** [comment]
When somebody works on this issue, he could also integrate support for downloading all tracks of an artist and all tracks of a playlist. Example urls:
* https://www.jamendo.com/artist/440692/jekk
* https://www.jamendo.com/playlist/500458937/best-of-november-2018

**Comment by bugsug** [comment]
If you are on GNU/Linux (maybe also on other Unix-like systems), you could use following combination of commands to download all songs of an artist from jamendo:

`curl [link to artists jamendo page] | grep -oP '(?<=\<a href=").*?(?=" class="link-wrap js-trackrow-trackrow-link"\>)' | sed -e 's/\/track/https:\/\/jamendo.com\/track/g' | youtube-dl -f [format] --batch-file /dev/stdin`

An example could be:

`curl https://www.jamendo.com/artist/428294/pokki-dj | grep -oP '(?<=\<a href=").*?(?=" class="link-wrap js-trackrow-trackrow-link"\>)' | sed -e 's/\/track/https:\/\/jamendo.com\/track/g' | youtube-dl -f mp31 --batch-file /dev/stdin`

I only tested it with the bourne-again shell, but it may (and should!) also work in combination with other shells.

If you do not know what this commands do, let me know so I can explain it to you.

**Comment by bugsug** [comment]
Hint: Cover arts are not included / embedded in the ogg version of the songs, but in the mp3 version.
