### ISSUE TITLE
Jamendo "WARNING: unable to extract duration"

### ISSUE THREAD

**Issue by kousu** [ytdl-org/youtube-dl#18565]
### Checklist

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Output

```
$ youtube-dl -v https://www.jamendo.com/track/592180/winter-dreams
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.jamendo.com/track/592180/winter-dreams']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.09
[debug] Python version 3.7.1 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[Jamendo] winter-dreams: Downloading webpage
WARNING: unable to extract duration; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://flac.jamendo.com/?trackid=592180&format=flac&from=app-97dab294'
[download] Vladimir Sterzer - Winter Dreams-592180.flac has already been downloaded
[download] 100% of 12.62MiB
```

```
$ youtube-dl -v -g https://www.jamendo.com/track/592180/winter-dreams
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-g', 'https://www.jamendo.com/track/592180/winter-dreams']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.09
[debug] Python version 3.7.1 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
WARNING: unable to extract duration; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: bestvideo+bestaudio/best
https://flac.jamendo.com/?trackid=592180&format=flac&from=app-97dab294
```

### Description of your *issue*, suggested solution and other information

`youtube-dl` is warning me that it can't find a duration. It still manages to download the file and show its URL.

**Comment by matthias4217** [comment]
I guess I've fixed it in 615b0193b80ff63fdd5036f3ccde4bd80591cbd0, however it's my first contribution to youtube-dl and I'm not sure what I did is perfect (but tests pass)
Note that the duration could also be found in a json in the webpage. However I've encountered issue with this.

I've tested two songs (one of them was already in the youtube-dl tests), and the relevant variable in the json was `PT0.21S` for the one lasting 210s, and PT0.141S for the other, lasting 141s. This seem very inconsistent and I don't really understand what's going on. It may be a problem internal to Jamendo.

However, the duration is also in another place in the page, in a more convenient format (210 or 141 for example) and I've decided to use this instead.

I'm writing this in case the duration extraction break again.
