### ISSUE TITLE
America's Test Kitchen and Cook's Country - Subtitle Support for Zype

### ISSUE THREAD

**Issue by samantonioli** [ytdl-org/youtube-dl#18566]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl https://www.americastestkitchen.com/episode/607-home-for-the-holidays --list-subs
[AmericasTestKitchen] 607: Downloading webpage
[Zype] 5bd0d243e338f9135500bb3e: Downloading webpage
[Zype] 5bd0d243e338f9135500bb3e: Downloading m3u8 information
5bd0d243e338f9135500bb3e has no subtitles
Sams-MacBook-Pro:~ samantonioli$ youtube-dl https://www.americastestkitchen.com/episode/607-home-for-the-holidays --list-subs -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.americastestkitchen.com/episode/607-home-for-the-holidays', u'--list-subs', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.17
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4, rtmpdump 2.4
[debug] Proxy map: {}
[AmericasTestKitchen] 607: Downloading webpage
[Zype] 5bd0d243e338f9135500bb3e: Downloading webpage
[Zype] 5bd0d243e338f9135500bb3e: Downloading m3u8 information
5bd0d243e338f9135500bb3e has no subtitles
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.americastestkitchen.com/episode/607-home-for-the-holidays

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Requesting subtitle extraction support for ATK and CC, along with other Zype services. Here's some info to let someone get started with this. You can find the .vtt english captions manually with the following instructions: 

Source video: https://www.americastestkitchen.com/episode/607-home-for-the-holidays

1) Use page inspector and search for  for "zype_id" and "api_key".
2) Plug [zype_id] and [api_key] into the following URL:
https://player.zype.com/embed/[zype_id].js?api_key=[api_key]
3) The .js gives the following:
```
textTracks: [
          {
            src: 'https://upload.zype.com/video/5bd0d243e338f9135500bb3e/subtitles/5bd0d664e338f9136100cb42.vtt?1540413028',
            srclang: 'en',
            kind: 'captions',
            label: 'English'
```
4) https://upload.zype.com/video/5bd0d243e338f9135500bb3e/subtitles/5bd0d664e338f9136100cb42.vtt is the subtitle file.

I hope someone can integrate this into the Zype/americastestkitchen/cookscountry extractors!

**Comment by remitamine** [comment]
will be supported in the next version.
