### ISSUE TITLE
[twitch] subtitles (chat) fail to download

### ISSUE THREAD

**Issue by ealgase** [ytdl-org/youtube-dl#18593]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'bestvideo+bestaudio/best', u'--download-archive', u'a.txt', u'--merge-output-format', u'mkv', u'-i', u'--all-subs', u'--embed-subs', u'--embed-thumbnail', u'--add-metadata', u'--write-annotations', u'--write-description', u'--write-info-json', u'--write-annotations', u'--write-thumbnail', u'--write-sub', u'-v', u'-o', u'%(uploader)s/%(title)s %(id)s.%(ext)s', u'--yes-playlist', u'https://www.twitch.tv/videos/329973004']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.09
[debug] Python version 2.7.12 (CPython) - Linux-3.14.0-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15-0ubuntu0.16.04.1, ffprobe 2.8.15-0ubuntu0.16.04.1, phantomjs 2.1.1
[debug] Proxy map: {}
[twitch:vod] 329973004: Downloading vod info JSON
[twitch:vod] 329973004: Downloading vod access token
[twitch:vod] 329973004: Downloading m3u8 information
[info] Writing video description to: Smallant1/SM64 1 Star PB 46_52 v329973004.description
[info] Writing video annotations to: Smallant1/SM64 1 Star PB 46_52 v329973004.annotations.xml
WARNING: There are no annotations to write.
[info] Writing video subtitles to: Smallant1/SM64 1 Star PB 46_52 v329973004.rechat.json
WARNING: Unable to download subtitle for "rechat": Unable to download webpage: <urlopen error [Errno -5] No address associated with hostname> (caused by URLError(gaierror(-5, 'No address associated with hostname'),))
[info] Writing video description metadata as JSON to: Smallant1/SM64 1 Star PB 46_52 v329973004.info.json
[twitch:vod] v329973004: Downloading thumbnail ...
[twitch:vod] v329973004: Writing thumbnail to: Smallant1/SM64 1 Star PB 46_52 v329973004.jpg
[debug] Invoking downloader on u'https://vod.edgecast.hls.ttvnw.net/20fe21a260ca0cdd6e87_smallant1_31027988608_1007874719/chunked/highlight-329973004.m3u8'
[download] Smallant1/SM64 1 Star PB 46_52 v329973004.mp4 has already been downloaded
[download] 100% of 1.21GiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:Smallant1/SM64 1 Star PB 46_52 v329973004.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Smallant1/SM64 1 Star PB 46_52 v329973004.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Smallant1/SM64 1 Star PB 46_52 v329973004.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:Smallant1/SM64 1 Star PB 46_52 v329973004.temp.mp4'
[ffmpeg] Adding metadata to 'Smallant1/SM64 1 Star PB 46_52 v329973004.mp4'
[debug] ffmpeg command line: ffmpeg -y -i 'file:Smallant1/SM64 1 Star PB 46_52 v329973004.mp4' -c copy -metadata 'comment=' -metadata 'description=' -metadata 'artist=Smallant1' -metadata 'title=SM64 1 Star PB 46:52' -metadata 'date=20181031' -metadata 'purl=https://www.twitch.tv/videos/329973004' 'file:Smallant1/SM64 1 Star PB 46_52 v329973004.temp.mp4'
[ffmpeg] Embedding subtitles in 'Smallant1/SM64 1 Star PB 46_52 v329973004.mp4'
ERROR: [Errno 2] No such file or directory: 'Smallant1/SM64 1 Star PB 46_52 v329973004.rechat.json'
Traceback (most recent call last):
  File "/home/ealgase/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 804, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/ealgase/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 858, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/ealgase/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1636, in process_video_result
    self.process_info(new_info)
  File "/home/ealgase/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1983, in process_info
    self.post_process(filename, info_dict)
  File "/home/ealgase/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2048, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/ealgase/.local/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 393, in run
    self.run_ffmpeg_multiple_files(input_files, temp_filename, opts)
  File "/home/ealgase/.local/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 182, in run_ffmpeg_multiple_files
    os.stat(encodeFilename(path)).st_mtime for path in input_paths)
  File "/home/ealgase/.local/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 182, in <genexpr>
    os.stat(encodeFilename(path)).st_mtime for path in input_paths)
OSError: [Errno 2] No such file or directory: 'Smallant1/SM64 1 Star PB 46_52 v329973004.rechat.json'
---

### Description of your *issue*, suggested solution and other information

Downloading of subtitles (the chat) for Twitch videos fails.

**Comment by vxbinaca** [comment]
They're not subtitles. The extractor doesn't support chat. Same with youtube chat, and comments.

**Comment by ealgase** [comment]
It previously extracted chat from the rechat endpoint (which has been removed).

**Comment by zachary-D** [comment]
I'm having this same issue.  Does anyone know of any fixes?

I think making the modifications in this PR might work - https://github.com/ytdl-org/youtube-dl/pull/15828 - but I haven't tried them yet

**Comment by ealgase** [comment]
You can use https://github.com/PetterKraabol/Twitch-Chat-Downloader/

**Comment by zachary-D** [comment]
Is there a way to tie that into youtube-dl?

**Comment by ealgase** [comment]
Not without scripting it yourself.

**Comment by za3k** [comment]
@remitamine Should this be closed after #15828? I'm not really sure or I'd do it myself.

**Comment by vxbinaca** [comment]
`rechat` subtitles count as the text chat, I vote to close.

**Comment by za3k** [comment]
Come on mate, did you even read this issue, or just the title? This is 
rechat JSON failing to parse and ffmpeg erroring out.

**Comment by za3k** [comment]
Sorry, that was totally confusing! I opened a second bug with an almost 
identical title, and thought you were voting to close ten seconds after 
I opened it. I'm the bad reader here for sure! Thanks for your quick 
response >< My apologies.
