### ISSUE TITLE
unable to extract thumbnail; please report this : site=https://www.franceculture.fr/emissions/

### ISSUE THREAD

**Issue by gycram** [ytdl-org/youtube-dl#18807]
$youtube-dl --verbose https://www.franceculture.fr/emissions/la-recherche-montre-en-main/la-recherche-montre-en-main-du-mercredi-10-octobre-2018
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.franceculture.fr/emissions/la-recherche-montre-en-main/la-recherche-montre-en-main-du-mercredi-10-octobre-2018']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-12-lowlatency-x86_64-with-Ubuntu-18.10-cosmic
[debug] exe versions: avconv 4.0.2-2, avprobe 4.0.2-2, ffmpeg 4.0.2-2, ffprobe 4.0.2-2, rtmpdump 2.4
[debug] Proxy map: {}
[FranceCulture] la-recherche-montre-en-main-du-mercredi-10-octobre-2018: Downloading webpage
**WARNING: unable to extract thumbnail; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.**
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://media.radiofrance-podcast.net/podcast09/14312-10.10.2018-ITEMA_21845051-2.mp3'
[download] Destination: La fabrique des algorithmes de recommandation et de management -la-recherche-montre-en-main-du-mercredi-10-octobre-2018.mp3
[download] 100% of 5.10MiB in 00:04

**Comment by nicolasmx** [comment]
Same issue.
