### ISSUE TITLE
Channel 9 Support

### ISSUE THREAD

**Issue by sirinath** [ytdl-org/youtube-dl#1885]
1) Single

http://channel9.msdn.com/Events/Visual-Studio/Launch-2013/-NET-Development

2) Event

http://channel9.msdn.com/Events/Visual-Studio/Launch-2013

3) Shows

http://channel9.msdn.com/Shows/Defrag-Tools

4) Tags

http://channel9.msdn.com/Tags/fsharp

5) Series

http://channel9.msdn.com/Series/Whats-New-in-Windows-81-for-IT-Pros

**Comment by devkhan** [comment]
I think almost all of the mentioned types work now.

Should this be closed?

**Comment by d-line** [comment]
Is there a reason we have no upload_date for channel9? I understand that those dates on Channel9 are not dates of upload, but rather recording start/stop. But it is useful to have some sort of time stamp for the video file.

**Comment by TRox1972** [comment]
As @devkhan mentions, videos on the website seems to be working as of 2016.05.21.2, though the provided 'external' URLs does not.
