### ISSUE TITLE
Google Drive confirmation code warning

### ISSUE THREAD

**Issue by nixxo** [ytdl-org/youtube-dl#18877]
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--verbose', 'https://drive.google.com/open?id=1UhAEdTDZnIKUwAjIA5CMi7R4PtVkU4T4']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2019.01.16
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-92696-ge5a0013c4a, ffprobe N-92696-ge5a0013c4a, rtmpdump 2.4
[debug] Proxy map: {}
[GoogleDrive] 1UhAEdTDZnIKUwAjIA5CMi7R4PtVkU4T4: Downloading webpage
[GoogleDrive] 1UhAEdTDZnIKUwAjIA5CMi7R4PtVkU4T4: Requesting source file
WARNING: unable to extract confirmation code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[info] Available formats for 1UhAEdTDZnIKUwAjIA5CMi7R4PtVkU4T4:
format code  extension  resolution note
18           mp4        640x360    
59           mp4        854x480    
22           mp4        1280x720   
37           mp4        1920x1080  (best)

```

---

the file download is not a problem. It gives me this warning so I reported it but the downloaded file is ok.

**Comment by Coaggly** [comment]
I just had the same experience

**Comment by felix-rufus** [comment]
Still happening

rod@alx:~$ youtube-dl -F --verbose  https://drive.google.com/file/d/1u8SwJOZ6F0XeZJ6q9J7EoGk8ElIyOyW9
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--verbose', 'https://drive.google.com/file/d/1u8SwJOZ6F0XeZJ6q9J7EoGk8ElIyOyW9']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.8.1 (CPython) - Linux-5.5.1-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[GoogleDrive] 1u8SwJOZ6F0XeZJ6q9J7EoGk8ElIyOyW9: Downloading webpage
[GoogleDrive] 1u8SwJOZ6F0XeZJ6q9J7EoGk8ElIyOyW9: Requesting source file
WARNING: unable to extract confirmation code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[info] Available formats for 1u8SwJOZ6F0XeZJ6q9J7EoGk8ElIyOyW9:
format code  extension  resolution note
18           mp4        640x360    
59           mp4        854x480    
22           mp4        1280x720   (best)
