### ISSUE TITLE
Vimeo album protected with password can not be downloaded

### ISSUE THREAD

**Issue by baliur** [ytdl-org/youtube-dl#18967]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
./youtube-dl http://vimeo.com/album/xxxxxxx -v --video-password secretpw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://vimeo.com/album/xxxxxxx', u'-v', u'--video-password', u'PRIVATE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.23
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-36-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4
[debug] Proxy map: {}
[generic] xxxxxxx: Requesting header
[redirect] Following redirect to https://vimeo.com/album/xxxxxxx
[vimeo:album] xxxxxxx: Downloading page 1
[vimeo:album] xxxxxxx: Verifying the password
ERROR: Unable to extract list title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/vimeo.py", line 912, in _real_extract
    return self._extract_videos(album_id, 'https://vimeo.com/album/%s' % album_id)
  File "./youtube-dl/youtube_dl/extractor/vimeo.py", line 848, in _extract_videos
    list_title = next(title_and_entries)
  File "./youtube-dl/youtube_dl/extractor/vimeo.py", line 825, in _title_and_entries
    yield self._extract_list_title(webpage)
  File "./youtube-dl/youtube_dl/extractor/vimeo.py", line 787, in _extract_list_title
    return self._TITLE or self._html_search_regex(self._TITLE_RE, webpage, 'list title')
  File "./youtube-dl/youtube_dl/extractor/common.py", line 992, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract list title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

Password protected vimeo album can not be downloaded. Album id and password is not public.

**Comment by LearnSomethingNewEveryDay** [comment]
same error for me

**Comment by ckalinwi** [comment]
I get the same error, output looks effectively identical except Python version is 2.7.12.

**Comment by ckalinwi** [comment]
Still a problem under release 2019.02.18.
