### ISSUE TITLE
Formatted Output Template to Create Playlists, Library Maintenance and Integrate with Other Programs in Scripts.

### ISSUE THREAD

**Issue by sirinath** [ytdl-org/youtube-dl#1896]
Is it possible to provide the ability to write formatted output to a file according to a give template format. Many play list formats are xml so you can add start of file text middle text end of file text. 

The substitution can take the format similar to the -o option. 

Like wise you can use this to create a html file to index the downloads. 

Another application is that this can be used to generate a script for completion moving once finished. Similar to a feature in torrent clients. 

The template opinions that are needed is
Header
1st file template
Odd template
Even template
Last file template
Separator template

Also some distinction should be made raw variables and variables in the template for file names. Also some control over the number of digits in an ID.

**Comment by dirkf** [comment]
#1864.
