### ISSUE TITLE
Support for ZDF tivi download missing

### ISSUE THREAD

**Issue by isotopp** [ytdl-org/youtube-dl#1905]
KK:~ kris$ youtube-dl --verbose http://www.tivi.de/tiviVideos/beitrag/Kurzgeschichten/1175070/1457912?view=flash
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.tivi.de/tiviVideos/beitrag/Kurzgeschichten/1175070/1457912?view=flash']
[debug] youtube-dl version 2013.11.28.1
[debug] Python version 2.7.5 - Darwin-13.0.0-x86_64-i386-64bit
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
[generic] 1457912?view=flash: Downloading webpage
[generic] 1457912?view=flash: Extracting information
ERROR: Unsupported URL: http://www.tivi.de/tiviVideos/beitrag/Kurzgeschichten/1175070/1457912?view=flash; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 428, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 131, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 227, in _real_extract
    raise ExtractorError(u'Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.tivi.de/tiviVideos/beitrag/Kurzgeschichten/1175070/1457912?view=flash; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by rusty-snake** [comment]
ZDFtivi now uses also zdf.de.
