### ISSUE TITLE
[Feature Request] Full resolution SoundCloud artwork download

### ISSUE THREAD

**Issue by AwesomeAwesomeAwesome** [ytdl-org/youtube-dl#19071]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30.1**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included:
- Example track: https://soundcloud.com/jinkamusic/ghost2u
- The regular thumbnail: https://i1.sndcdn.com/artworks-000472040832-c39wes-t500x500.jpg
- Its full resolution version: https://i1.sndcdn.com/artworks-000472040832-c39wes-original.jpg

---

### SoundCloud provides for most of its tracks a high resolution artwork

**And it's extremely easy to access!** You simply need to replace the `-t500x500` part of the url with `original` or in some very rare cases with `original size`.

There already exists a script that adds a download button for every artwork (https://greasyfork.org/en/scripts/14591-soundcloud-album-art-downloader), however there is no way to automatise it.

An additional handle to force download full/original size artwork would simplify the process.

**Comment by davidchalifoux** [comment]
I was just about to make this request, thanks for putting it in!
I too would really like to see this added.

**Comment by RomanKarwacik** [comment]
This is already possible, by using the ``--embed-thumbnail `` flag, and editing the thumbnail url:
```
--- a/youtube_dl/extractor/soundcloud.py
+++ b/youtube_dl/extractor/soundcloud.py
@@ -218,7 +218,7 @@ class SoundcloudIE(InfoExtractor):
             self.report_extraction(name)
         thumbnail = info.get('artwork_url') or info.get('user', {}).get('avatar_url')
         if isinstance(thumbnail, compat_str):
-            thumbnail = thumbnail.replace('-large', '-t500x500')
+            thumbnail = thumbnail.replace('-large', '-original')
         username = try_get(info, lambda x: x['user']['username'], compat_str)
 
         def extract_count(key):
```
However, I am not sure if it should be made permanent, I would prefer an option for choosing the thumbnail quality.

**Comment by pyxelr** [comment]
@AwesomeAwesomeAwesome @RomanKarwacik: 
I would also prefer to choose between original / 500x500 size. The original is too large for my requirements, hence significantly increases the file size.
Is there some easy way to specify the dimensions of the thumbnail in youtube-dl?

**Comment by pyxelr** [comment]
> @AwesomeAwesomeAwesome @RomanKarwacik:
> I would also prefer to choose between original / 500x500 size. The original is too large for my requirements, hence significantly increases the file size.
> Is there some easy way to specify the dimensions of the thumbnail in youtube-dl?

Problem solved. 
It simply required to modify a single line of soundcloud.py:
`elif image_id == 'original':` into `elif image_id == 't500x500':`
