### ISSUE TITLE
Last version of youtube-dl don't work on this mediaset.it link

### ISSUE THREAD

**Issue by IceT75** [ytdl-org/youtube-dl#19076]
Hi please tell me why youtube-dl don't work on this mediaset link:

youtube-dl "https://www.mediasetplay.mediaset.it/video/
icircuitidellamore/i-circuiti-dellamore_F309070501000104"

[Mediaset] F309070501000104: Downloading JSON metadata
[Mediaset] F309070501000104: Downloading MPEG4 SD SMIL data
[Mediaset] F309070501000104: Downloading MPEG4 HD SMIL data
ERROR: None of the available releases match the specified AssetType, Protection
Scheme, and/or Format preferences

Thank you

**Comment by IceT75** [comment]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30.1**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

**Comment by DOTTORGRAZY** [comment]
same problem with the link:
https://www.mediasetplay.mediaset.it/video/lacasadifamiglia/la-casa-di-famiglia_F308518301000101

**Comment by shkretov** [comment]
Same problem with:
https://www.mediasetplay.mediaset.it/video/squadraantimafia6/seconda-puntata_F306131401000201
youtube-dl version is **2019.08.02**
browser plays video just fine
