### ISSUE TITLE
issue with Facebook group posts: if a post contains two videos, you can download just the first one

### ISSUE THREAD

**Issue by hpta** [ytdl-org/youtube-dl#19131]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

When a group post contains 2 videos you cannot download the second one.
steps to reproduce:

create a facebook group
in the group, start writing a post and upload two videos into it (drag and drop)
confirm
try
youtube-dl  -v first_video_url --username "your_email" --password "your_password"  -works ok
youtube-dl  -v second_video_url --username "your_email" --password "your_password"  -it downloads the first video

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/100033620354545/videos/106560053808006/', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2019.01.30.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 106560053808006: Downloading webpage
WARNING: unable to extract uploader; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract thumbnail URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://scontent.fprg2-1.fna.fbcdn.net/v/t66.18014-6/45160005_182968539349636_5214338457739844986_n.mp4?_nc_cat=103&efg=eyJ2ZW5jb2RlX3RhZyI6Im9lcF9oZCJ9&_nc_ht=scontent.fprg2-1.fna&oh=6f75f737734957ab0d285509e4bc42f5&oe=5CE80050'
[download] Destination: Facebook video #106560053808006-106560053808006.mp4
[download] 100% of 471.67KiB in 00:00
...
<end of log>
```

---

---

**Comment by alexvong1995** [comment]
Please provide the required username and password, otherwise it is impossible
to download the above videos.

**Comment by hpta** [comment]
Alright, I created a Facebook account and short videos for testing.
try
youtube-dl.exe https://www.facebook.com/100033620354545/videos/106559927141352/ --username "john.ptacnik@gmail" --password "SuperSecretPassword123"
youtube-dl.exe https://www.facebook.com/100033620354545/videos/106560053808006/ --username "john.ptacnik@gmail" --password "SuperSecretPassword123"

The name of the group is "Pokus group".
First video shows a mouse, the second shows a mug (but you can download just the mouse video)
You can use these credentials to log into Facebook to check this, however Facebook security might be a hassle (suspicious activity based on geographical location or something, I don't know)

**Comment by alexvong1995** [comment]
@hpta

You are right, I cannot login even with the given username and
password. Maybe there's geo restriction. I think you'll have to wait for
others to help.

**Comment by rautamiekka** [comment]
You **really** shouldn't use someone else's Fb acc even if you could login to it cuz Fb has systems in place which **will** detect an anomaly in the login habits (geo change from country to another, geo change within the country over a long distance, even mere failed attempts to login), which either immediately or later results in the acc getting flagged for security check. If/when Fb has gotten wise, you won't even get outta the check without a consequence or even a ban.

Same for some other sites. In short, don't try it.

**Comment by hpta** [comment]
Try it with your facebook account, it should work - I've made the test group public and facebook seems to require just any login for this, so just fill in your credentials.
youtube-dl.exe https://www.facebook.com/100033620354545/videos/106559927141352/ --username "" --password ""
youtube-dl.exe https://www.facebook.com/100033620354545/videos/106560053808006/ --username "" --password ""
You'll get a notification about an unrecognized login though.
Or follow the steps to reproduce in the original post - create your own group post with videos.

**Comment by hpta** [comment]
Not sure if it helps but with chrome developer tools I've found that when I'm on the page with the post the div containing these two videos looks like this: [div.txt](https://github.com/rg3/youtube-dl/files/2843180/div.txt). Search for "href" and you'll get the video urls. In xml viewer this div looks weird - like it isn't properly enclosed. And even with the second video in the foreground you'll get this kind of div with two links. So maybe youtube-dl always matches just the first link when doing its pattern matching (or something like that, I have no idea how it works)

**Comment by alexvong1995** [comment]
@rautamiekka

Thanks for the advice, but I do all my youtube-dl testings through tor,
so I should be fine. Also, other tor users can login using the onion
link, so my youtube-dl testings shouldn't cause trouble to them.
