### ISSUE TITLE
Error in _parse_mpd_formats for Live Vimeo streams

### ISSUE THREAD

**Issue by bahsan** [ytdl-org/youtube-dl#19144]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v -F https://player.vimeo.com/video/315104824
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://player.vimeo.com/video/315104824']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.30.1
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 315104824: Downloading webpage
[vimeo] 315104824: Extracting information
[vimeo] 315104824: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 404: Not Found
[vimeo] 315104824: Downloading fastly_live m3u8 information
[vimeo] 315104824: Downloading fastly_live MPD information
WARNING: [vimeo] 315104824: Failed to parse XML not well-formed (invalid token): line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2019.1.30.1', 'console_scripts', 'youtube-dl')()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2019.1.30.1-py2.7.egg/youtube_dl/__init__.py", line 472, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2019.1.30.1-py2.7.egg/youtube_dl/__init__.py", line 462, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2019.1.30.1-py2.7.egg/youtube_dl/YoutubeDL.py", line 2005, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2019.1.30.1-py2.7.egg/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2019.1.30.1-py2.7.egg/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2019.1.30.1-py2.7.egg/youtube_dl/extractor/vimeo.py", line 682, in _real_extract
    info_dict_config = self._parse_config(config, video_id)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2019.1.30.1-py2.7.egg/youtube_dl/extractor/vimeo.py", line 170, in _parse_config
    fatal=False)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2019.1.30.1-py2.7.egg/youtube_dl/extractor/common.py", line 2002, in _extract_mpd_formats
    formats_dict=formats_dict, mpd_url=mpd_url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2019.1.30.1-py2.7.egg/youtube_dl/extractor/common.py", line 2012, in _parse_mpd_formats
    if mpd_doc.get('type') == 'dynamic':
AttributeError: 'NoneType' object has no attribute 'get'
```

---

### Description of your *issue*, suggested solution and other information

youtube-dl is failing when getting info from **Live** Vimeo streams. HLS are being parsed correctly, but DASH don't.

I cannot guarantee that the provided link will stay up, but I can update it when I get another one, and help troubleshooting if needed.

**Comment by alexvong1995** [comment]
@babsan
I cannot reproduce it either. I get the following output:
```
alexvong1995@debian:~$ torsocks youtube-dl -v -F https://player.vimeo.com/video/315104824
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://player.vimeo.com/video/315104824']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.27
1549405785 WARNING torsocks[7537]: [syscall] Unsupported syscall number 217. Denying the call (in tsocks_syscall() at syscall.c:568)
[debug] Python version 3.7.0 (CPython) - Linux-4.19.0-1-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[vimeo] 315104824: Downloading webpage
[vimeo] 315104824: Extracting information
[vimeo] 315104824: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 404: Not Found
[vimeo] 315104824: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 315104824: Downloading fastly_skyfire m3u8 information
[vimeo] 315104824: Downloading akfire_interconnect_quic MPD information
[vimeo] 315104824: Downloading akfire_interconnect_quic MPD information
[vimeo] 315104824: Downloading fastly_skyfire MPD information
[vimeo] 315104824: Downloading fastly_skyfire MPD information
[info] Available formats for 315104824:
format code                                         extension  resolution note
dash-akfire_interconnect_quic_sep-audio-1219174131  m4a        audio only DASH audio  137k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-fastly_skyfire_sep-audio-1219174131            m4a        audio only DASH audio  137k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-akfire_interconnect_quic_sep-video-1219174131  mp4        640x360    DASH video  697k , mp4_dash container, avc1.64001E, 25fps, video only
dash-fastly_skyfire_sep-video-1219174131            mp4        640x360    DASH video  697k , mp4_dash container, avc1.64001E, 25fps, video only
dash-akfire_interconnect_quic_sep-video-1219174126  mp4        960x540    DASH video 1825k , mp4_dash container, avc1.64001F, 25fps, video only
dash-fastly_skyfire_sep-video-1219174126            mp4        960x540    DASH video 1825k , mp4_dash container, avc1.64001F, 25fps, video only
dash-akfire_interconnect_quic_sep-video-1219174129  mp4        1280x720   DASH video 3037k , mp4_dash container, avc1.640020, 25fps, video only
dash-fastly_skyfire_sep-video-1219174129            mp4        1280x720   DASH video 3037k , mp4_dash container, avc1.640020, 25fps, video only
http-360p                                           mp4        640x360    25fps
hls-akfire_interconnect_quic-686                    mp4        640x360     686k , avc1.64001E, 25.0fps, mp4a.40.2
hls-fastly_skyfire-686                              mp4        640x360     686k , avc1.64001E, 25.0fps, mp4a.40.2
dash-akfire_interconnect_quic-video-1219174131      mp4        640x360    DASH video  697k , mp4_dash container, avc1.64001E, 25fps, mp4a.40.2 (48000Hz)
dash-fastly_skyfire-video-1219174131                mp4        640x360    DASH video  697k , mp4_dash container, avc1.64001E, 25fps, mp4a.40.2 (48000Hz)
http-540p                                           mp4        960x540    25fps
hls-akfire_interconnect_quic-1779                   mp4        960x540    1779k , avc1.64001F, 25.0fps, mp4a.40.2
hls-fastly_skyfire-1779                             mp4        960x540    1779k , avc1.64001F, 25.0fps, mp4a.40.2
dash-akfire_interconnect_quic-video-1219174126      mp4        960x540    DASH video 1825k , mp4_dash container, avc1.64001F, 25fps, mp4a.40.2 (48000Hz)
dash-fastly_skyfire-video-1219174126                mp4        960x540    DASH video 1825k , mp4_dash container, avc1.64001F, 25fps, mp4a.40.2 (48000Hz)
http-720p                                           mp4        1280x720   25fps
hls-akfire_interconnect_quic-2867                   mp4        1280x720   2867k , avc1.640020, 25.0fps, mp4a.40.2
hls-fastly_skyfire-2867                             mp4        1280x720   2867k , avc1.640020, 25.0fps, mp4a.40.2
dash-akfire_interconnect_quic-video-1219174129      mp4        1280x720   DASH video 3037k , mp4_dash container, avc1.640020, 25fps, mp4a.40.2 (48000Hz)
dash-fastly_skyfire-video-1219174129                mp4        1280x720   DASH video 3037k , mp4_dash container, avc1.640020, 25fps, mp4a.40.2 (48000Hz) (best)
```
Does the error persist?

**Comment by bahsan** [comment]
Thanks for testing! Unfortunately the Vimeo live stream has ended and is now processed as a VOD, which is correctly handled by the current version of youtube-dl. The issue is very specific to Vimeo streams that are **currently live**. I included earlier the MPD manifest as it was received while live to help troubleshoot.

I am trying as best as I can to find some longer-lasting live stream links...

**Comment by alexvong1995** [comment]
@bahsan

bahsan <notifications@github.com> writes:

> Thanks for testing! Unfortunately the Vimeo live stream has ended and is now processed as
> a VOD, which is correctly handled by the current version of youtube-dl. The issue is very
> specific to Vimeo streams that are currently live. I included earlier the MPD manifest as it
> was received while live to help troubleshoot.
>
You're welcomed! Looking at the MPD, I think the real links might be of
the form (regex ahead):

  [^<>]*googlevideo\.com[^<>]*

Of course, we need to test it to be really sure.

> I am trying as best as I can to find some longer-lasting live stream links...
>
Good luck!

**Comment by Ali008** [comment]
Unfortunately, I have the same issue with live streaming vimeo

`C:\Users\Ali008> youtube-dl.exe -f best https://player.vimeo.com/video/331660616
[vimeo] 331660616: Downloading webpage
[vimeo] 331660616: Extracting information
[vimeo] 331660616: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 404: Not Found
[vimeo] 331660616: Downloading fastly_live m3u8 information
[vimeo] 331660616: Downloading fastly_live MPD information
WARNING: [vimeo] 331660616: Failed to parse XML not well-formed (invalid token): line 1, column 0
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\YoutubeDL.py", line 2008, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\vimeo.py", line 694, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\vimeo.py", line 170, in _parse_config
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\common.py", line 2026, in _extract_mpd_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\common.py", line 2036, in _parse_mpd_formats
AttributeError: 'NoneType' object has no attribute 'get'`
