### ISSUE TITLE
Support for Dropout.tv and intl.dropout.tv

### ISSUE THREAD

**Issue by thibaultmol** [ytdl-org/youtube-dl#19146]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies=cookies.txt', 'https://intl.dropout.tv/um-actually/season:1/videos/c-3po-s-origins-hp-lovecraft-the-food-album-with-weird-al-yankovic', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.01.30.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[generic] c-3po-s-origins-hp-lovecraft-the-food-album-with-weird-al-yankovic: Requesting header
WARNING: Falling back on generic information extractor.
[generic] c-3po-s-origins-hp-lovecraft-the-food-album-with-weird-al-yankovic: Downloading webpage
[generic] c-3po-s-origins-hp-lovecraft-the-food-album-with-weird-al-yankovic: Extracting information
ERROR: Unsupported URL: https://intl.dropout.tv/um-actually/season:1/videos/c-3po-s-origins-hp-lovecraft-the-food-album-with-weird-al-yankovic
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp36zpl0n4\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp36zpl0n4\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp36zpl0n4\build\youtube_dl\extractor\generic.py", line 3320, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://intl.dropout.tv/um-actually/season:1/videos/c-3po-s-origins-hp-lovecraft-the-food-album-with-weird-al-yankovic
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://intl.dropout.tv/um-actually/season:1/videos/c-3po-s-origins-hp-lovecraft-the-food-album-with-weird-al-yankovic
- Single video: https://intl.dropout.tv/ch-shorts/season:21/videos/the-super-bowl-isn-t-about-football
- Playlist: https://intl.dropout.tv/ch-shorts/season:21

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I've tried downloading them by extracting my cookies but that doesn't seem to work either.
(I followed a guide)
You can start a free trial on their website if you want to test it as well.

**Comment by remitamine** [comment]
related to #14835.

**Comment by ealgase** [comment]
Fortunately, there isn't any DRM, at least on the first video link.

**Comment by theg00s3** [comment]
Not super relevant, but if you have a subscription, you can use the developer tools, Control+F for "auth" and copy that link into myvid.download

**Comment by natis1** [comment]
They have recently changed their playlist format with their "dropout 2.0." Before they had a m3u8 file for each resolution.
Now they have a single json file that contains all resolutions and in each resolution a segments array containing start and end times in seconds, relative url, and file size.

**Comment by thibaultmol** [comment]
Should mention that now (I can't remember if they did before) but now seem to just be using Vimeo for their video hosting. So if you provide a cookies.txt file with the logged in credentials, downloading single videos works **perfectly**.
```
youtube-dl "https://www.dropout.tv/dimension-20/season:9/videos/the-stabber-of-the-evening" --cookies cookies.txt
[generic] the-stabber-of-the-evening: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-stabber-of-the-evening: Downloading webpage
[generic] the-stabber-of-the-evening: Extracting information
[vhx:embed] 1471916: Downloading webpage
[vhx:embed] 1471916: Downloading JSON metadata
[vhx:embed] 1471916: Downloading akfire_interconnect_quic m3u8 information
[vhx:embed] 1471916: Downloading akfire_interconnect_quic m3u8 information
[vhx:embed] 1471916: Downloading fastly_skyfire m3u8 information
[vhx:embed] 1471916: Downloading fastly_skyfire m3u8 information
[vhx:embed] 1471916: Downloading akfire_interconnect_quic MPD information
[vhx:embed] 1471916: Downloading akfire_interconnect_quic MPD information
[vhx:embed] 1471916: Downloading fastly_skyfire MPD information
[vhx:embed] 1471916: Downloading fastly_skyfire MPD information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1111
[download] Destination: Untitled-1471916.fhls-fastly_skyfire_sep-5060.mp4
[download] 100% of 3.84GiB in 01:15:42
[dashsegments] Total fragments: 1112
[download] Destination: Untitled-1471916.fdash-fastly_skyfire_sep-audio-d6fadea2.m4a
[download] 100% of 202.90MiB in 10:19
[ffmpeg] Merging formats into "Untitled-1471916.mp4"
Deleting original file Untitled-1471916.fhls-fastly_skyfire_sep-5060.mp4 (pass -k to keep)
Deleting original file Untitled-1471916.fdash-fastly_skyfire_sep-audio-d6fadea2.m4a (pass -k to keep)

```

Downloading entire playlists/shows doesn't work though.

**Comment by rtisticxplosions** [comment]
Hi, I've been looking into this for a little bit and am struggling because I always get the error "ERROR: Unsupported URL: https://www.dropout.tv/videos/prompocalypse". I can download successfully by using the vimeo OTT link, but I can't download using the dropout link even while passing cookies using the guide (https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-pass-cookies-to-youtube-dl).

To test like for like, I even tried downloading the video from the URL thibaultmol used in their example, using the following command: youtube-dl "https://www.dropout.tv/dimension-20/season:9/videos/the-stabber-of-the-evening" --cookies dropout.tv_cookies.txt

This resulted in the same error: "ERROR: Unsupported URL: https://www.dropout.tv/dimension-20/season:9/videos/the-stabber-of-the-evening".

Again, I do have a bit more of an involved workaround for this, so it's not a massive issue, but since I'm new to youtube-dl, I thought I would double check that I did not do anything obviously daft.

**Comment by rtisticxplosions** [comment]
> 
> 
> Hi, I've been looking into this for a little bit and am struggling because I always get the error "ERROR: Unsupported URL: https://www.dropout.tv/videos/prompocalypse". I can download successfully by using the vimeo OTT link, but I can't download using the dropout link while passing cookies using the guide (https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-pass-cookies-to-youtube-dl).
> 
> To test like for like, I tried downloading the video from the URL thibaultmol used in their example, using the following command: youtube-dl "https://www.dropout.tv/dimension-20/season:9/videos/the-stabber-of-the-evening" --cookies dropout.tv_cookies.txt
> 
> This resulted in the same error: "ERROR: Unsupported URL: https://www.dropout.tv/dimension-20/season:9/videos/the-stabber-of-the-evening".
> 
> Again, I do have a bit more of an involved workaround for this, so it's not a massive issue, but since I'm new to youtube-dl, I thought I would double check that I did not do anything obviously daft.

Anyone struggling with this, I realised that the cookies file in the same folder as youtube-dl was not being used, and it was instead creating a new cookies file in my root user folder. When I put a longer path to the exact location of the cookies file, it started working!
