### ISSUE TITLE
VRV - Can't download single episodes or movies

### ISSUE THREAD

**Issue by dawnerd** [ytdl-org/youtube-dl#19229]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
~/rips  youtube-dl --cookies cookies.txt --username troy@somany.us --verbose https://vrv.co/watch/GR8V3VM5R/Angst
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--cookies', u'cookies.txt', u'--username', u'PRIVATE', u'--verbose', u'https://vrv.co/watch/GR8V3VM5R/Angst']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.08
[debug] Python version 2.7.15 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[vrv] None: Downloading webpage
[vrv] Downloading Token Credentials JSON metadata
[vrv] GR8V3VM5R: Downloading resource path JSON metadata
[vrv] GR8V3VM5R: Downloading CMS Signing JSON metadata
[vrv] GR8V3VM5R: Downloading video JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 605, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

I see the vrv extractor was recently fixed but I can't get it to work for single episodes/movies. Series do seem to work so perhaps its just missing the url for singles?

**Comment by human-blip** [comment]
I am seeing very similar behaviour with youtube-dl version 2019.04.01
Series and individual episodes in a series work but movies do not.
No login required for the following example.

...
youtube-dl -v https://vrv.co/watch/G6NQXZ1J6/Lily-CAT
[debug] System config: []
[debug] User config: [u'--user-agent', u'Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://vrv.co/watch/G6NQXZ1J6/Lily-CAT']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.01
[debug] Python version 2.7.16rc1 (CPython) - Linux-4.19.0-2-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.1.1-1, ffprobe 4.1.1-1, phantomjs 2.1.1, rtmpdump 2.4
[vrv] None: Downloading webpage
[vrv] G6NQXZ1J6: Downloading resource path JSON metadata
[vrv] G6NQXZ1J6: Downloading CMS Signing JSON metadata
[vrv] G6NQXZ1J6: Downloading video JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube
-dl with the --verbose flag and include its complete output.
  File "/home/mike/bin/youtube-dl/youtube_dl/extractor/common.py", line 626, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/mike/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
...

**Comment by remitamine** [comment]
pushed a quick fix that works for individual movie URLs, for example with the movie listing URL posted by @human-blip this will work with [subtitled](https://vrv.co/watch/GRK5XZP36/Movie-Subtitled) and [dubbed](https://vrv.co/watch/GRMGPZ1PR/Movie-Dubbed) links.

**Comment by human-blip** [comment]
Thanks remitamine.

**Comment by gnations56** [comment]
I have been having an issue downloading movies from VRV HiDive. I am unable to download movies that require registration

**Comment by remitamine** [comment]
@gnations56 make sure that you can watch the video in the browser
this video requires an account with access to Hidedive content, so I can't test it and try to fix the problem if it really exists.

**Comment by gnations56** [comment]
the video does work in the browser.

**Comment by AlvoErrado2** [comment]
I can watch the movie in the browser, but I can't download the file. Series is downloaded without error, but any movie has this error.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose', 'https://vrv.co/watch/GR8V3VM5R/Angst']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 3.7.3rc1 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 3.3.9, ffprobe 3.3.9, rtmpdump 2.4
[debug] Proxy map: {}
[vrv] None: Downloading webpage
[vrv] Downloading Token Credentials JSON metadata
[vrv] GR8V3VM5R: Downloading resource path JSON metadata
[vrv] GR8V3VM5R: Downloading CMS Signing JSON metadata
[vrv] GR8V3VM5R: Downloading object JSON metadata
[vrv] GR8V3VM5R: Downloading video JSON metadata
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/user/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/home/user/.local/lib/python3.7/site-packages/youtube_dl/extractor/vrv.py", line 161, in _real_extract
    self.raise_login_required()
  File "/home/user/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 935, in raise_login_required
    expected=True)
youtube_dl.utils.ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
```

**Comment by gnations56** [comment]
@remitamine I can test out fixes if you need me to

**Comment by remitamine** [comment]
I can't fix anything without having access to one of the videos that trigger the error.

**Comment by AlvoErrado2** [comment]
@remitamine I can provide you with the account, how do I contact you?

**Comment by remitamine** [comment]
email address in my profile.

**Comment by AlvoErrado2** [comment]
@remitamine, I sent the data to your email.

**Comment by Stzam** [comment]
Im having a problem with merging the files i got the latest version of youtube dl its downloads but i get this is error  [ffmpeg] Merging formats into "The Cocoon of Caprice, Part 1-G69VMK00Y.mp4"
ERROR: file:The Cocoon of Caprice, Part 1-G69VMK00Y.fdash-audio-ja-JP-f2-v1-x3.mp4: No such file or directory any ideas on how to fix this @darkhelmet2016
