### ISSUE TITLE
Dimecasts Support

### ISSUE THREAD

**Issue by sirinath** [ytdl-org/youtube-dl#1974]
1) Episode

http://www.dimecasts.net/Content/WatchEpisode/205

2) Tag

http://www.dimecasts.net/Casts/ByTag/Linq2Sql

**Comment by TRox1972** [comment]
URL for the first video can be found at `<source src=http://s3.amazonaws.com/Dimecasts/Episodes/episode.205/Stream_WebApi.ConsumingEndpoints.mp4 type='video/mp4' />
`

**Comment by remitamine** [comment]
redirects now to a youtube channel.
