### ISSUE TITLE
cygwin + Ctrl-C doesn't cancel the script

### ISSUE THREAD

**Issue by Garfield22** [ytdl-org/youtube-dl#1978]
Hi,

I am aware of https://github.com/rg3/youtube-dl/issues/481 , but it doesn't help me.

I am trying to kill youtube-dl by pressing CTRL-C. It works in windows cmd console, but it does not work in cygwin mintty console.

I have python installed not from cygwin, but as usual windows version.
My OS: windows 7 (x64)
Cygwin: 2.831 (32 bit)
Python version: Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32
youtube-dl  version: 2013.12.11.2
youtube-dl was installed with pip help: pip install --upgrade youtube_dl

Sample:
youtube-dl http://www.youtube.com/watch?v=sao5-VCcRkQ
or
youtube-dl "http://www.youtube.com/watch?v=sao5-VCcRkQ"
or
youtube-dl 'http://www.youtube.com/watch?v=sao5-VCcRkQ'

It creates 3 processes ( ps -W | grep -i python ):
    12004    3992   12004       8940  pty0    1000 20:01:53 /cygdrive/d/Python27/Scripts/youtube-dl
    12004    3992   12004       8940  pty0    1000 20:01:53 /cygdrive/d/Python27/Scripts/youtube-dl
    12084       0       0      12084  ?          0 20:01:54 D:\Python27\python.exe

When I press CTRL-C youtube-dl ( PID = 12004 ) process is terminated, but python (PID = 12084 ) is still running and continue making text output.

I have to kill python manually with command "taskkill.exe /F /IM python.exe" from second mintty console.

help me please :-)

**Comment by dirkf** [comment]
Let Cygwin be Cygwin!
