### ISSUE TITLE
TravelChannel is broken again

### ISSUE THREAD

**Issue by gr4ndmux** [ytdl-org/youtube-dl#19857]
Much love and whats with the spamsville...

Hope it doesnt bury this, but right now travel channel is broken again.
seems like some patchwork is needed

got this - https://www.travelchannel.com/shows/ghost-adventures/episodes/ripleys-believe-it-or-not
to turn into this - https://sni-i.akamaihd.net/i/0284/0284476_,6,5,4,3,2,1,.mp4.csmil/master.m3u8

and it works with streamlink, please fix when you get the time.

Thanks so much your totally awesome!

**Comment by swiizypenis** [comment]
> Much love and whats with the spamsville...
> 
> Hope it doesnt bury this, but right now travel channel is broken again.
> seems like some patchwork is needed
> 
> got this - https://www.travelchannel.com/shows/ghost-adventures/episodes/ripleys-believe-it-or-not
> to turn into this - https://sni-i.akamaihd.net/i/0284/0284476_,6,5,4,3,2,1,.mp4.csmil/master.m3u8
> 
> and it works with streamlink, please fix when you get the time.
> 
> Thanks so much your totally awesome!

getting buried now

**Comment by gr4ndmux** [comment]
thanks swizzy figure my legit bug sandwich is easier to find now, dude spend that time tweeting POTOUS or something hahaha
