### ISSUE TITLE
reddit error

### ISSUE THREAD

**Issue by wankio** [ytdl-org/youtube-dl#20030]
youtube-dl https://www.reddit.com/r/gifs/comments/au27kt/not_today/

> [RedditR] au27kt: Downloading JSON metadata
> [Reddit] xl0duc2uvei21: Downloading m3u8 information
> [Reddit] xl0duc2uvei21: Downloading MPD manifest
> [Reddit] xl0duc2uvei21: Downloading thumbnail ...
> Traceback (most recent call last):
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python37\Scripts\youtube-dl.exe\__main__.py", line 9, in <module>
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\__init__.py", line 472, in main
>     _real_main(argv)
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\__init__.py", line 462, in _real_main
>     retcode = ydl.download(all_urls)
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2006, in download
>     url, force_generic_extractor=self.params.get('force_generic_extractor', False))
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 805, in extract_info
>     return self.process_ie_result(ie_result, download, extra_info)
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 897, in process_ie_result
>     new_result, download=download, extra_info=extra_info)
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 859, in process_ie_result
>     return self.process_video_result(ie_result, download=download)
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 1640, in process_video_result
>     self.process_info(new_info)
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 1842, in process_info
>     self._write_thumbnails(info_dict, filename)
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2398, in _write_thumbnails
>     uf = self.urlopen(t['url'])
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2224, in urlopen
>     req = sanitized_Request(req)
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\utils.py", line 561, in sanitized_Request
>     return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\urllib\request.py", line 328, in __init__
>     self.full_url = url
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\urllib\request.py", line 354, in full_url
>     self._parse()
>   File "c:\users\gen32uc\appdata\local\programs\python\python37\lib\urllib\request.py", line 383, in _parse
>     raise ValueError("unknown url type: %r" % self.full_url)
> ValueError: unknown url type: 'default'

**Comment by jwilk** [comment]
@wankio, in the future please include youtube-dl output when run with the `-v` option, in a [fenced block](https://help.github.com/en/articles/creating-and-highlighting-code-blocks#fenced-code-blocks) for better formatting.

Anyway, I've managed to reproduce it here:
```console
$ youtube-dl --verbose --write-thumbnail https://old.reddit.com/r/gifs/comments/au27kt/not_today/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--write-thumbnail', 'https://old.reddit.com/r/gifs/comments/au27kt/not_today/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.5.3 (CPython) - Linux-2.6.32-042stab134.8-x86_64-with-debian-9.8
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[RedditR] au27kt: Downloading JSON metadata
[Reddit] xl0duc2uvei21: Downloading m3u8 information
[Reddit] xl0duc2uvei21: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[Reddit] xl0duc2uvei21: Downloading thumbnail ...
Traceback (most recent call last):
  File "/home/jwilk/.local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/home/jwilk/.local/lib/python3.5/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/home/jwilk/.local/lib/python3.5/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/jwilk/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/jwilk/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/jwilk/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 899, in process_ie_result
    new_result, download=download, extra_info=extra_info)
  File "/home/jwilk/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/jwilk/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1642, in process_video_result
    self.process_info(new_info)
  File "/home/jwilk/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1844, in process_info
    self._write_thumbnails(info_dict, filename)
  File "/home/jwilk/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2400, in _write_thumbnails
    uf = self.urlopen(t['url'])
  File "/home/jwilk/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2226, in urlopen
    req = sanitized_Request(req)
  File "/home/jwilk/.local/lib/python3.5/site-packages/youtube_dl/utils.py", line 561, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'default'
```
