### ISSUE TITLE
[Generic] `Referer` header required to MPD / m3u8 download 

### ISSUE THREAD

**Issue by bato3** [ytdl-org/youtube-dl#20217]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When I run download process with `Referrer` i'ts OK
`youtube-dl https://video.sibnet.ru/shell.php?videoid=3422904 --add-header "Referer: https://video.sibnet.ru/shell.php?videoid=3422904"` but on default it returns 403.

I'm thinking, that `Referrer` should be added to all downloads

```
youtube-dl https://video.sibnet.ru/shell.php?videoid=3422904
[generic] shell: Requesting header
WARNING: Falling back on generic information extractor.
[generic] shell: Downloading webpage
[generic] shell: Extracting information
[generic] shell: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[generic] shell: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[download] Destination: Доставщик пиццы спросил разрешения сыграть на фортепиано-shell.php
```
Also: https://github.com/rg3/youtube-dl/issues/18182

**Comment by BladeMight** [comment]
The `generic` IE has no rule for Sibnet, but has a similar [rule for Brightcove Legacy Studio embeds](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/generic.py#L2418).

**Comment by idMysteries** [comment]
![image](https://user-images.githubusercontent.com/11484976/109951624-fb977580-7cee-11eb-9b47-24e231c401d5.png)
I can download video from "dv9.sibnet.ru"
