### ISSUE TITLE
[adobepass] disneynow: Unable to extract POST URL directv now

### ISSUE THREAD

**Issue by speakerender** [ytdl-org/youtube-dl#20213]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://disneynow.go.com/shows/elena-of-avalor/season-02/episode-21-movin-on-up/vdka8040775?pid=PL553044961', '--ap-mso', 'ATTOTT', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.03.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-89439-g1215889bc1, ffprobe N-89439-g1215889bc1
[debug] Proxy map: {}
[Go] vdka8040775: Downloading webpage
[Go] VDKA8040775: Downloading JSON metadata
[Go] VDKA8040775: Downloading Provider Redirect Page
[Go] VDKA8040775: Downloading Provider Login Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\go.py", line 137, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\adobepass.py", line 1508, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\adobepass.py", line 1360, in post_form
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\common.py", line 992, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\common.py", line 983, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://disneynow.go.com/shows/elena-of-avalor/season-02/episode-21-movin-on-up/vdka8040775?pid=PL553044961

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Unable to extract any videos on https://disneynow.go.com that require the adobepass.  When trying to use --cookie I get an error that I need to use Adobe Pass. ~~Appears to be similar error to issue #18901~~.  Issue is actually related to #17770 that reports Directv now being broken

**Comment by speakerender** [comment]
Any of the videos that require Adobe Pass authentication result in the same error.  Error occurs still with 2019.03.09

**Comment by speakerender** [comment]
Testing further, the issue isn't with go extractor.  issue is with adobepass. page that is getting back has:
'''
<noscript>
    <p>
        <strong>Note:</strong> Since your browser does not support JavaScript,
        you must press the Continue button once to proceed.
    </p>
</noscript>
'''
performing a submit there seems to get back the right page/form that then needs values populated

**Comment by nevafuse** [comment]
@speakerender If you email me your mso creds, I can take a look.  I'd recommend changing your password first if you use that password for other accounts. My email is my username at gmail.

**Comment by speakerender** [comment]
I've actually gotten to the point of parsing the html from the logon page.  It looks like ngdio was working on a solution in #17770.

**Comment by speakerender** [comment]
Here is a link to a patch that should allow directv now auth to work. 
[https://github.com/speakerender/youtube-dl/tree/directvnow-auth-fix](https://github.com/speakerender/youtube-dl/tree/directvnow-auth-fix)

**Comment by darkhelmet2016** [comment]
Don't even get that far and get this.

ERROR: 'ÿþ' is not a valid URL. Set --default-search "ytsearch" (or run  youtube
-dl "ytsearch:ÿþ" ) to search YouTube
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y
3w\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y
3w\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y
3w\build\youtube_dl\extractor\generic.py", line 2230, in _real_extract
youtube_dl.utils.ExtractorError: 'ÿþ' is not a valid URL. Set --default-search "
ytsearch" (or run  youtube-dl "ytsearch:ÿþ" ) to search YouTube

**Comment by darkhelmet2016** [comment]
I am on windows so the exe pulls from git.

**Comment by speakerender** [comment]
The patch I have doesn't make an exe, you'd have to run the actual python.  I've updated the branch to latest from this project.
Follow the steps for setting up as a developer and you can execute it via the following:
 python -m youtube_dl <disneynow url> --ap-mso ATTOTT --ap-username <directv now username> --ap-password <directv now password>

**Comment by darkhelmet2016** [comment]
I am on windows so it uses the path for youtube-dl.exe

**Comment by darkhelmet2016** [comment]
> The patch I have doesn't make an exe, you'd have to run the actual python. I've updated the branch to latest from this project.
> Follow the steps for setting up as a developer and you can execute it via the following:
> python -m youtube_dl --ap-mso ATTOTT --ap-username --ap-password
> 
> > I am on windows so the exe pulls from git. But that is now outdated as it uses 2019.05.20.
> 
> As of right now, the current version I get from the official exe is 2019.05.20 . The branch I created is not merged into the official master branch.
And that is why was getting other errors which they deleted the comment for when tried using your fix and running it from the python path.

**Comment by speakerender** [comment]
Just tested with several videos requiring authentication for disneynow.go.com they worked just fine with the merged latest from master.  (two different series). hopefully this resolves your issue as well.

**Comment by darkhelmet2016** [comment]
Having the same issue but on https://www.fxnetworks.com/fxx. Maybe all extractors need to be updated For Direttvnow?

[debug] Encodings: locale cp1252, fs mbcs, out cp65001, pref cp1252
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[FXNetworks] 1528749123645: Downloading webpage
[FXNetworks] 1528749123645: Downloading Provider Redirect Page
[FXNetworks] 1528749123645: Downloading Provider Login Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org
/bug . Make sure you are using the latest version; type  youtube-dl -U  to updat
e. Be sure to call youtube-dl with the --verbose flag and include its complete o
utput.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y
3w\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y
3w\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y
3w\build\youtube_dl\extractor\fxnetworks.py", line 64, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y
3w\build\youtube_dl\extractor\adobepass.py", line 1508, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y
3w\build\youtube_dl\extractor\adobepass.py", line 1360, in post_form
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y
3w\build\youtube_dl\extractor\common.py", line 1013, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y
3w\build\youtube_dl\extractor\common.py", line 1004, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report t
his issue on https://yt-dl.org/bug . Make sure you are using the latest version;
 type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose f
lag and include its complete output.

**Comment by speakerender** [comment]
I just tried two different shows on the fxx site, and it worked without issue using my branch.  The Directv Now change I made in my branch is to the authentication library (adobepass.py) this changes it for all extractors.

**Comment by darkhelmet2016** [comment]
Then why do my error codes say other wise?

**Comment by speakerender** [comment]
Windows 10 OS, 
[debug] Python version 3.7.2 (CPython) - Windows-10-10.0.17134-SP0:
Command running:
python -m youtube_dl  <url_of_video> --ap-mso ATTOTT --ap-username <my Directv Now Username> --ap-password <my Directv Now Password>

If the authentication pages are different per user (no idea why they would be) It doesn't look like I'll be able to assist.

**Comment by darkhelmet2016** [comment]
I can not do python -m youtube_dl.

**Comment by darkhelmet2016** [comment]
Disney Now has changed its address to just https://disneynow.com/

**Comment by dstftw** [comment]
For any work on this you must provide MSO credentials.

**Comment by dcxmurphy** [comment]
> Here is a link to a patch that should allow directv now auth to work.
> https://github.com/speakerender/youtube-dl/tree/directvnow-auth-fix

Noob here. How am I supposed to apply this patch? I have no idea what to do to get this fix.
