### ISSUE TITLE
Recognize Error When Merging Extention

### ISSUE THREAD

**Issue by goodboi69** [ytdl-org/youtube-dl#20221]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\username>youtube-dl -f bestvideo+bestaudio --merge-output-format mp4 https://www.youtube.com/watch?v=FiX1WYee3NA
[youtube] FiX1WYee3NA: Downloading webpage
[youtube] FiX1WYee3NA: Downloading video info webpage
[download] Destination: Fastest nope in the west-FiX1WYee3NA.f136.mp4
[download] 100% of 3.00MiB in 00:00
[download] Destination: Fastest nope in the west-FiX1WYee3NA.f251.webm
[download] 100% of 326.71KiB in 00:00
[ffmpeg] Merging formats into "Fastest nope in the west-FiX1WYee3NA.mp4"
ERROR:   Stream #1:0 -> #0:1 (copy)

C:\Users\username>
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=FiX1WYee3NA

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

If when downloading a Youtube video without checking the type of best video and audio fails to merge the specified file extention, could youtube-dl recognize this fail and try another extention. In the example above I tried the best video and audio with the mp4 extention and it failed. But with the mkv extention it merged fine. Now, youtube-dl can recognize errors so it could be possible.

**Comment by ttpcodes** [comment]
I'm seeing this issue as well, on version 2019.03.18. Here are some more URLs that cause an error when merging:
- https://www.youtube.com/watch?v=k9iYm9PEAHg
- https://www.youtube.com/watch?v=hMc8naeeSS8

I'll update this comment as I dig up more links I've had issues with, but please look into this issue.

**Comment by remitamine** [comment]
missing verbose log.

**Comment by ttpcodes** [comment]
Thanks for the heads up about the `ffmpeg` version. I updated to the latest `ffmpeg` version and this issue has disappeared.

**Comment by genewitch** [comment]
adding a full error message:
```youtube-dl -v  --merge-output-format mp4 -f 'bestvideo[height<=480]+bestaudio/best[height<=480]' https://www.youtube.com/playlist?list=PLgUGfzMeW6jJLx3asjLlVepax5U9HowbC
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--merge-output-format', 'mp4', '-f', 'bestvideo[height<=480]+bestaudio/best[height<=480]', 'https://www.youtube.com/playlist?list=PLgUGfzMeW6jJLx3asjLlVepax5U9HowbC']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.01
[debug] Python version 3.6.5 (CPython) - Linux-4.14.65-gentoo-x86_64-QEMU_Virtual_CPU_version_2.5+-with-gentoo-2.6
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[youtube:playlist] PLgUGfzMeW6jJLx3asjLlVepax5U9HowbC: Downloading webpage
[download] Downloading playlist: New building lot; excavation
[youtube:playlist] playlist New building lot; excavation: Downloading 13 videos
[download] Downloading video 1 of 13
[youtube] Az45HYnAAps: Downloading webpage
[youtube] Az45HYnAAps: Downloading video info webpage
[debug] Invoking downloader on 'https://r1---sn-q4fl6ns7.googlevideo.com/videoplayback?ei=VLGiXN6fCYmltQer94ewDw&mm=31%2C26&ipbits=0&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&initcwndbps=207500&c=WEB&id=o-AEzVBU4kdbsu3QoSnFL0NsQYbaBqSM-ZA6luzt2NAQqq&gir=yes&clen=114506032&mn=sn-q4fl6ns7%2Csn-5uaeznys&ms=au%2Conr&mt=1554166027&mv=m&ip=107.77.200.172&signature=219048D99326CD2672B768A2B701AD552B0CCC0F.89F747874BF5CBCA7BE87F9F0A3376794F6A483E&fvip=1&dur=853.894&lmt=1536152368931361&keepalive=yes&expire=1554187700&pl=24&mime=video%2Fmp4&key=yt6&source=youtube&requiressl=yes&itag=135&ratebypass=yes'
[download] Installing a driveway entrance-Az45HYnAAps.f135.mp4 has already been downloaded
[download] 100% of 109.20MiB
[debug] Invoking downloader on 'https://r1---sn-q4fl6ns7.googlevideo.com/videoplayback?ei=VLGiXN6fCYmltQer94ewDw&mm=31%2C26&ipbits=0&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&initcwndbps=207500&c=WEB&id=o-AEzVBU4kdbsu3QoSnFL0NsQYbaBqSM-ZA6luzt2NAQqq&gir=yes&clen=14495983&mn=sn-q4fl6ns7%2Csn-5uaeznys&ms=au%2Conr&mt=1554166027&mv=m&ip=107.77.200.172&signature=404AC5DE103EB89305A8A6C8977CAA0F679ED637.9E93FC1878322871945B19F0F7DE7F86524611AE&fvip=1&dur=853.921&lmt=1536241599029616&keepalive=yes&expire=1554187700&pl=24&mime=audio%2Fwebm&key=yt6&source=youtube&requiressl=yes&itag=251&ratebypass=yes'
[download] Installing a driveway entrance-Az45HYnAAps.f251.webm has already been downloaded
[download] 100% of 13.82MiB
[ffmpeg] Merging formats into "Installing a driveway entrance-Az45HYnAAps.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Installing a driveway entrance-Az45HYnAAps.f135.mp4' -i 'file:Installing a driveway entrance-Az45HYnAAps.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Installing a driveway entrance-Az45HYnAAps.temp.mp4'
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2052, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
```

youtube-dl version 2019.04.01; ffmpeg version 4.1.3

**Comment by remitamine** [comment]
@genewitch you have to select compatible formats for the container that you have selected(mp4 and m4a formats for the mp4 container).
