### ISSUE TITLE
Lrt.lt site redesign

### ISSUE THREAD

**Issue by w00faz** [ytdl-org/youtube-dl#20264]
Lrt.lt did a site redesign, can't download videos anymore.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.lrt.lt/mediateka/irasas/1013714532/laba-diena-lietuva', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.18
[debug] Python version 3.7.2 (CPython) - Linux-4.14.102-1-MANJARO-x86_64-with-arch-Manjaro-Linux
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[lrt.lt] 1013714532: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/lrt.py", line 70, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1305, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by bro1** [comment]
I am working on a fix. 
I have it running and tests passing on my machine, so I'll try to create a pull request soon

**Comment by gytisrepecka** [comment]
Any news on this issue? Looks like videos can't be downloaded with version `2019.08.02`.

**Comment by w00faz** [comment]
Works fine with the fix provided altho you have to apply it manually.

**Comment by lifepillar** [comment]
Just tried @bro1's patch, but I still get an error:

```
]./bin/youtube-dl -v https://www.lrt.lt/mediateka/irasas/54391/septynios-kauno-dienos
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.lrt.lt/mediateka/irasas/54391/septynios-kauno-dienos']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 2.7.17 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[lrt.lt] 54391: Downloading webpage
ERROR: No video formats found; […]
```

**Comment by bro1** [comment]
Hi @lifepillar, I think you failed to patch it properly, as I have just tested it again:

python -m youtube_dl  -v https://www.lrt.lt/mediateka/irasas/54391/septynios-kauno-dienos

And it's working totally fine.
