### ISSUE TITLE
[Globo] Problem with some titles 

### ISSUE THREAD

**Issue by DESKTOP-RX90B689** [ytdl-org/youtube-dl#20319]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.09*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.09**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\Suporte>youtube-dl -F -v https://globoplay.globo.com/v/6953616/programa/ --cookies %USERPROFILE%\Videos\cookies.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://globoplay.globo.com/v/6953616/programa/', '--cookies', 'C:\\Users\\Suporte\\Videos\\cookies.txt']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.03.09
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-93022-g260f1960e7, ffprobe N-93022-g260f1960e7
[debug] Proxy map: {}
[Globo] 6953616: Downloading JSON metadata
[Globo] 6953616: Downloading security hash for 5be4f781636d6102de000000_360_1080_m3u8
[Globo] 5be4f781636d6102de000000_360_1080_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 6953616: Downloading security hash for 5b775102636d6120eb000000_240_1080_l_mpd
[Globo] 5b775102636d6120eb000000_240_1080_l_mpd: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[Globo] 6953616: Downloading security hash for 5b775102636d6120eb000000_240_1080_l_manifest
[Globo] 5b775102636d6120eb000000_240_1080_l_manifest: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden
[Globo] 6953616: Downloading security hash for 5b775102636d6120eb000000_90_720_mpd
[Globo] 5b775102636d6120eb000000_90_720_mpd: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[Globo] 6953616: Downloading security hash for 5b775102636d6120eb000000_240_720_mpd
ERROR: Globo returned error: User has exceeded the simultaneous access limit.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy110f8qy\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy110f8qy\build\youtube_dl\extractor\common.py", line 522, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy110f8qy\build\youtube_dl\extractor\globo.py", line 122, in _real_extract
youtube_dl.utils.ExtractorError: Globo returned error: User has exceeded the simultaneous access limit.
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Only with some titles does this error occur. I would like to know if there is a solution, if there is any one just read the mpd file and do the rest, because using the mpd file URL also occurs errors.

youtube-dl  -F -v https://vodstreaming01a.video.globo.com/p10777/r90_720/v96/da/af/df/6953616_df45291c9283f39d56847100402c2b590a8f502e/6953616-manifest.ism/6953616.mpd --cookies %USERPROFILE%\Videos\cookies.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://vodstreaming01a.video.globo.com/p10777/r90_720/v96/da/af/df/6953616_df45291c9283f39d56847100402c2b590a8f502e/6953616-manifest.ism/6953616.mpd', '--cookies', 'C:\\Users\\Suporte\\Videos\\cookies.txt']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.03.09
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-93022-g260f1960e7, ffprobe N-93022-g260f1960e7
[debug] Proxy map: {}
[GloboArticle] 6953616: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy110f8qy\build\youtube_dl\extractor\common.py", line 619, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy110f8qy\build\youtube_dl\YoutubeDL.py", line 2225, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by Rafa1310** [comment]
Can someone help me?

**Comment by lucasmcoelho** [comment]
Youtube-dl still with problems about simultaneous acess and dont find video links on globoplay

**Comment by IeUDE** [comment]
I can confirm, same problem as OP.
