### ISSUE TITLE
cannot download any video from youtube

### ISSUE THREAD

**Issue by trollepierre** [ytdl-org/youtube-dl#20325]
I run `brew install youtube-dl`

and 
`youtube-dl 'https://www.youtube.com/watch\?v\=rywUS-ohqeE'`

and got this error:

WARNING: Could not send HEAD request to https://www.youtube.com/watch\?v\=rywUS-ohqeE: HTTP Error 404: Not Found
[generic] watch\?v\=rywUS-ohqeE: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ealgase** [comment]
You're quoting the backslashes, remove them from the command and it should work.
