### ISSUE TITLE
[YAHOO] error missing video tag

### ISSUE THREAD

**Issue by xkkdd** [ytdl-org/youtube-dl#20332]
Hello,
I got an error message trying to download from Yahoo:
https://www.yahoo.com/entertainment/watch-2-chainz-ariana-grande-160629226.html
![1552448447(1)](https://user-images.githubusercontent.com/44890589/54252285-2548b680-4585-11e9-8c04-846a3e6042d8.png)

**Comment by meali2085** [comment]
I'm new to the code base. But my best guess (from how much code I have seen), it is not able to retrieve embed youtube video information and hence throwing the error. 
The url it ends up constructing to download video is https://video.media.yql.yahoo.com/v1/video/sapi/streams/dca032bb-3797-3aa4-857a-14e2ad1b82eb
