### ISSUE TITLE
[Viafree] "Failed to parse JSON" error 

### ISSUE THREAD

**Issue by forthrin** [ytdl-org/youtube-dl#20338]
```
WARNING: [Viafree] avsnitt-1: Failed to parse JSON Expecting ',' delimiter: line 1 column 342 (char 341)
```

- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.09**
- [X] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
- [X] Bug report (encountered problems with youtube-dl)

**Comment by Limero** [comment]
I have this same issue. Please, create a pull request, so it can be merged.

Error I get:
```
WARNING: [Viafree] avsnitt-1: Failed to parse JSON Expecting ',' delimiter: line 1 column 342 (char 341)
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by forthrin** [comment]
Sure. One question: Do you know if I need to create one branch per pull request? (I tried pushing this commit just now, and then it got intertwined with another, unrelated pull request for youtube-dl.)

**Comment by Limero** [comment]
Afaik. As long as the first commit is not merged, you'll have to put this one on a separate branch or both will be added.

**Comment by forthrin** [comment]
Thanks. Do you know how many days one can expect to wait until they merge? It's almost a week since I added the other pull request, and I wanted to see how they handle things before I commit more.

**Comment by forthrin** [comment]
@Limero: I'm having some difficulties with creating pull requests. If you are seasoned with pull requests and Git in general, let me know if you can help do this correctly.

**Comment by ezeenova** [comment]
@forthrin Your commit has somehow been orphaned. Perhaps someone --force push'ed something over it, or the branch containing it was deleted. To fix this, follow these steps: https://stackoverflow.com/a/34618633/2173323

**Comment by forthrin** [comment]
I deleted the whole thing because things got messed up. If I have youtube-dl (`upstream`), my fork (`origin`) and a local fix branch (`foo`), how do I update `foo` with the latest commits from `upstream`?
