### ISSUE TITLE
Unable to obtain file audio codec with ffprobe

### ISSUE THREAD

**Issue by RomanScott** [ytdl-org/youtube-dl#20333]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.09*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.09**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
Traceback (most recent call last):
  File "site-packages/youtube_dl/YoutubeDL.py", line 2052, in post_process
  File "site-packages/youtube_dl/postprocessor/ffmpeg.py", line 274, in run
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "modules/downloaders/youtube.py", line 66, in downloadMedia
  File "site-packages/youtube_dl/YoutubeDL.py", line 2006, in download
  File "site-packages/youtube_dl/YoutubeDL.py", line 805, in extract_info
  File "site-packages/youtube_dl/YoutubeDL.py", line 859, in process_ie_result
  File "site-packages/youtube_dl/YoutubeDL.py", line 1640, in process_video_result
  File "site-packages/youtube_dl/YoutubeDL.py", line 1987, in process_info
  File "site-packages/youtube_dl/YoutubeDL.py", line 2054, in post_process
  File "site-packages/youtube_dl/YoutubeDL.py", line 622, in report_error
  File "site-packages/youtube_dl/YoutubeDL.py", line 592, in trouble
youtube_dl.utils.DownloadError: ERROR: WARNING: unable to obtain file audio codec with ffprobe
```

---

### Description of your *issue*, suggested solution and other information

Hello, I have run into a very strange issue. I am trying to use youtube-dl to extract audio files from YouTube and download them. I only get this issue in a Mac environment, on Windows it works perfectly.

Here is my Python code:

```
        downloadOptions = {
            'progress_hooks': [progressHook],
            'outtmpl': mediaPath + '/%(id)s.%(ext)s',
            'format': 'bestaudio/best',
            'subtitlesformat': 'srt/ttml/best',
            'ffmpeg_location': FFMPEG_FOLDER_LOCATION,
            'writesubtitles': True,
            'writeautomaticsub': True,
            'noplaylist': True,
            'call_home': False,
            'postprocessors': [
                {
                    'key': 'FFmpegExtractAudio',
                    'preferredcodec': 'wav',
                },
                {
                    'key': 'FFmpegSubtitlesConvertor',
                    'format': 'srt',
                },
            ],
        }

        with youtube_dl.YoutubeDL(downloadOptions) as ydl:
            try:
                ydl.download([url])
```

Please help!

**Comment by dstftw** [comment]
Most likely ffprobe/ffmpeg is broken/does not run in your environment.

**Comment by RomanScott** [comment]
@dstftw

Neither my ffmpeg nor my ffprobe is broken though and they both work in a Mac environment.

**Comment by RomanScott** [comment]
@dstftw

It also says this in the error report:

```
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 2052, in post_process
  File "youtube_dl/postprocessor/ffmpeg.py", line 274, in run
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe
```
