### ISSUE TITLE
HTTP Error 503 - Consistently fails to download a given YouTube.com video

### ISSUE THREAD

**Issue by Alan3285** [ytdl-org/youtube-dl#20331]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.09*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
```
$ youtube-dl --verbose https://www.youtube.com/watch?v=mWcwf3_FKSs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=mWcwf3_FKSs']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.09
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] mWcwf3_FKSs: Downloading webpage
[youtube] mWcwf3_FKSs: Downloading video info webpage
[youtube] mWcwf3_FKSs: Downloading MPD manifest
WARNING: [youtube] mWcwf3_FKSs: Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r3---sn-j5aa2a0n-53ae.googlevideo.com/videoplayback?ipbits=0&expire=1552467463&mime=video%2Fmp4&itag=134&ei=p3GIXKzfLfOQ3LUP_ZiHwAk&mv=m&dur=3423.060&initcwndbps=1300000&mn=sn-j5aa2a0n-53ae%2Csn-a5meknlz&requiressl=yes&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cotfp%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-APkWDnUHFBV68Y-ilQi6PyTx_LpRS-nhA-XU9lw1S5Tf&ms=au%2Conr&mt=1552443897&gir=yes&pl=16&signature=0370A13653F0A308CE09C3B97B7CEBD7C794052D.4EAB08F66EE7D1A882768E63C823FC0469903B7B&keepalive=yes&ip=101.98.39.44&key=yt6&mm=31%2C26&aitags=133%2C134%2C160&clen=109885750&source=youtube&c=WEB&fvip=3&otfp=1&lmt=1507483050476049&ratebypass=yes'
[download] Destination: Tales Of The Unexpected 059 05x08 pattern of guilt-mWcwf3_FKSs.f134.mp4
[download]   5.7% of 104.80MiB at 216.26KiB/s ETA 07:47[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/home/alan/.local/lib/python2.7/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/home/alan/.local/lib/python2.7/site-packages/youtube_dl/downloader/http.py", line 182, in establish_connection
    raise RetryDownload(err)
RetryDownload
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

The YouTube.com video as shown in the error log consistently fails to download with an HTTP Error 503.  I have tried running it as an admin, and normal user, but it makes no difference.

I can download other YouTube videos without any issues.

Thanks,

Alan.

**Comment by Alan3285** [comment]
Hi,

This was marked as a duplicate of:

https://github.com/ytdl-org/youtube-dl/pull/15840

but that seems to relate to a new feature request?

Thanks,

Alan.

**Comment by dstftw** [comment]
Nothing to do with that issue. Server side youtube error, select another format.
