### ISSUE TITLE
Openload error

### ISSUE THREAD

**Issue by delixia** [ytdl-org/youtube-dl#20343]
~# youtube-dl -v -j https://openload.co/embed/t0cW_0Jy3q0/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-j', 'https://openload.co/embed/t0cW_0Jy3q0/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.09
[debug] Python version 3.6.7 (CPython) - Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 522, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/openload.py", line 401, in _real_extract
    'stream URL'))
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 997, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Post the output with `--dump-pages`. Remove any other options.

**Comment by delixia** [comment]
### Test print after 
```
       p = subprocess.Popen([
            self.exe, '--ssl-protocol=any',
            self._TMP_FILES['script'].name
        ], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

       with open(self._TMP_FILES['html'].name, 'rb') as f:
            print(f.read().decode('utf-8'))
```

![2019-03-16 (2)](https://user-images.githubusercontent.com/48543231/54473394-ba5be180-4809-11e9-849e-408d434178dc.png)


### Test print before
```
        with open(self._TMP_FILES['html'].name, 'rb') as f:
            print(f.read().decode('utf-8'))
         
        p = subprocess.Popen([
            self.exe, '--ssl-protocol=any',
            self._TMP_FILES['script'].name
        ], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

![2019-03-16 (3)](https://user-images.githubusercontent.com/48543231/54473432-1161b680-480a-11e9-9c3a-d98b0873718b.png)

**Comment by delixia** [comment]
### Test print before PhantomJS 

```
        with open(self._TMP_FILES['html'].name, 'rb') as f:
            print(f.read().decode('utf-8'))
```
before    
        
```
        p = subprocess.Popen([
            self.exe, '--ssl-protocol=any',
            self._TMP_FILES['script'].name
        ], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

![2019-03-16 (3)](https://user-images.githubusercontent.com/48543231/54473516-6f42ce00-480b-11e9-9aa4-dc20a4cc27c9.png)


Test print after PhantomJS

```
        with open(self._TMP_FILES['html'].name, 'rb') as f:
            print(f.read().decode('utf-8'))
```
After    
        
```
        p = subprocess.Popen([
            self.exe, '--ssl-protocol=any',
            self._TMP_FILES['script'].name
        ], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

![2019-03-16 (2)](https://user-images.githubusercontent.com/48543231/54473525-81bd0780-480b-11e9-87b4-40735827957c.png)

**Comment by userisuserisuser** [comment]
Did you find a fix for this? Happens for me.

**Comment by dirkf** [comment]
Please open a new issue according to #30839 if you have a current failure case.
