### ISSUE TITLE
get url in python

### ISSUE THREAD

**Issue by Zipdox** [ytdl-org/youtube-dl#20347]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.09*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.09**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

I'm writing a python script and I need to get the direct URL in a variable.
I did this but it prints the URL on screen and doesn't end up in the variable.
```
from __future__ import unicode_literals
import youtube_dl



ydl_opts = {
    'format': 'bestaudio/best',
    'forceurl': 'yes',
    'skip_download': 'yes',
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    url = ydl.download(['https://www.youtube.com/watch?v=BaW_jenozKc'])
    print('link:')
    print(str(url))
```

**Comment by dstftw** [comment]
This is expected behavior of `forceurl`. You must use `extract_info`.
