### ISSUE TITLE
Reddit Videos Are Downloading The MPD Manifest Instead of Video File

### ISSUE THREAD

**Issue by barrycarey** [ytdl-org/youtube-dl#20356]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.09*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.09**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl https://v.redd.it/ofl84n7bu2d21 -v 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://v.redd.it/ofl84n7bu2d21', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.09
[debug] Python version 3.6.7 (CPython) - Linux-4.15.0-45-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4
[debug] Proxy map: {}
[Reddit] ofl84n7bu2d21: Downloading m3u8 information
[Reddit] ofl84n7bu2d21: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://v.redd.it/ofl84n7bu2d21/DASHPlaylist.mpd'
[download] Destination: ofl84n7bu2d21-ofl84n7bu2d21.fdash-VIDEO-4.mp4
[download] 100% of 2.86KiB in 00:01
[debug] Invoking downloader on 'https://v.redd.it/ofl84n7bu2d21/DASHPlaylist.mpd'
[download] Destination: ofl84n7bu2d21-ofl84n7bu2d21.fdash-AUDIO-1.m4a
[download] 100% of 2.86KiB in 00:01
[ffmpeg] Merging formats into "ofl84n7bu2d21-ofl84n7bu2d21.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:ofl84n7bu2d21-ofl84n7bu2d21.fdash-VIDEO-4.mp4 -i file:ofl84n7bu2d21-ofl84n7bu2d21.fdash-AUDIO-1.m4a -c copy -map 0:v:0 -map 1:a:0 file:ofl84n7bu2d21-ofl84n7bu2d21.temp.mp4
ERROR: file:ofl84n7bu2d21-ofl84n7bu2d21.fdash-VIDEO-4.mp4: Invalid data found when processing input
Traceback (most recent call last):
  File "/home/barry/PycharmProjects/sandbox/venv/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2052, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/barry/PycharmProjects/sandbox/venv/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/barry/PycharmProjects/sandbox/venv/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:ofl84n7bu2d21-ofl84n7bu2d21.fdash-VIDEO-4.mp4: Invalid data found when processing input

...
<end of log>
```

### Description of your *issue*, suggested solution and other information

All Reddit hosted downloads are failing.  When the format selector is left as default it's attempting to download the MPD manifest as a video.  The resulting .mp4 video is only a few KB in size.  Changing the extension to .txt and opening it confirms it's the manifest file. 

![image](https://user-images.githubusercontent.com/3161456/54406444-8faa4580-46b0-11e9-9cc5-706492323730.png)

![image](https://user-images.githubusercontent.com/3161456/54406579-03e4e900-46b1-11e9-8fbb-ca153cb3d162.png)

**Comment by barrycarey** [comment]
What issue is this a duplicate of?  I didn't see anything similar

**Comment by matejm** [comment]
I have the exact same problem. Have you found a solution?

**Comment by barrycarey** [comment]
It's fixed in the repo but not in PyPi. 

Change your requirements file to point to the git link instead of the pip package.
