### ISSUE TITLE
Is it possible to resume after videos have been converted to audio?

### ISSUE THREAD

**Issue by Futureknows** [ytdl-org/youtube-dl#20364]
In other words, can youtube-dl recognize converted audio files as  completed so it doesn't repeat the download and conversion of the entire playlist?

**Comment by dstftw** [comment]
`--download-archive`.

**Comment by Futureknows** [comment]
I am using `--download-archive` as follows:

`youtube-dl -x -c -w --audio-format best --download-archive archive.txt https://www.youtube.com/channel/*
`

It downloads the whole audio file before ffmpeg reports `exists, skipping`.
When downloading default video formats, it recognizes the existing video and skips before downloading.
