### ISSUE TITLE
-b option, and the FAQ.

### ISSUE THREAD

**Issue by EvanCarroll** [ytdl-org/youtube-dl#20375]
Currently we say this in the [faq](https://github.com/ytdl-org/youtube-dl/blob/067aa17edf5a46a8cbc4d6b90864eddf051fa2bc/README.md#L777)

> Most people asking this question are not aware that youtube-dl now defaults to downloading the highest available quality as reported by YouTube, which will be 1080p or 720p in some cases, so you no longer need the -b option. For some specific videos, maybe YouTube does not report them to be available in a specific high quality format you're interested in. In that case, simply request it with the -f option and youtube-dl will try to download it.

When I do `-F` though I get

```
$ youtube-dl "https://youtu.be/U9o49qwa6hk" -F
[youtube] U9o49qwa6hk: Downloading webpage
[youtube] U9o49qwa6hk: Downloading video info webpage
[info] Available formats for U9o49qwa6hk:
format code  extension  resolution note
249          webm       audio only DASH audio   56k , opus @ 50k, 35.25MiB
250          webm       audio only DASH audio   71k , opus @ 70k, 43.87MiB
171          webm       audio only DASH audio  108k , vorbis@128k, 60.45MiB
251          webm       audio only DASH audio  128k , opus @160k, 77.95MiB
140          m4a        audio only DASH audio  133k , m4a_dash container, mp4a.40.2@128k, 88.09MiB
278          webm       256x108    144p  105k , webm container, vp9, 24fps, video only, 39.02MiB
160          mp4        256x108    144p  105k , avc1.4d400b, 24fps, video only, 17.32MiB
242          webm       426x180    240p  196k , vp9, 24fps, video only, 48.43MiB
133          mp4        426x180    240p  205k , avc1.4d400d, 24fps, video only, 29.61MiB
243          webm       640x270    360p  334k , vp9, 24fps, video only, 80.96MiB
134          mp4        640x270    360p  499k , avc1.4d4015, 24fps, video only, 64.12MiB
244          webm       854x360    480p  564k , vp9, 24fps, video only, 128.13MiB
135          mp4        854x360    480p  892k , avc1.4d401e, 24fps, video only, 124.91MiB
247          webm       1280x540   720p 1149k , vp9, 24fps, video only, 248.99MiB
136          mp4        1280x540   720p 1760k , avc1.4d401f, 24fps, video only, 217.94MiB
248          webm       1920x810   1080p 2007k , vp9, 24fps, video only, 425.60MiB
137          mp4        1920x810   1080p 3260k , avc1.640028, 24fps, video only, 380.21MiB
271          webm       2560x1080  1440p 6453k , vp9, 24fps, video only, 1.01GiB
313          webm       3840x1620  2160p 13201k , vp9, 24fps, video only, 3.14GiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 245.43MiB
18           mp4        640x270    medium  349k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 242.26MiB
22           mp4        1280x540   hd720  441k , avc1.64001F, mp4a.40.2@192k (44100Hz) (best)
```

You can see the `22` says `"(best)"`. However, the default pulls down 313 (which really is the best as it's `3840x1620`. However, that resolution is also insane. I would love to have a `--sane-best` or something. Or, perhaps even an option to set an upward bound like `--best 1080p` where it tries to download the closest format to 1080p with audio without exceeding that (as my screen isn't even 1080p). This would do what YouTube seems to do (as it never goes over 1080p, but always seems to prefer that resolution in my laptop).

Anyway, it doesn't seem necessary to force me to have to read `-F` to get the desired behavior. Am I missing something and to explicitly choose the hd1080 or hd720 option.

Comparing 

    youtube-dl "https://youtu.be/U9o49qwa6hk" -f "bestvideo[height<=?1080]+bestaudio/best"
    youtube-dl "https://youtu.be/U9o49qwa6hk" -f 22

The top downloads 1.1gb + the bottom downloads 300 mb.

**Comment by dstftw** [comment]
Read FAQ on format selection.
