### ISSUE TITLE
Complete Log History for BAT/CMD in Windows

### ISSUE THREAD

**Issue by ArchivistGoals** [ytdl-org/youtube-dl#20388]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x ] Feature request (request for a new functionality)
- [ x Question
- [ ] Other

---

Is there a way to log the entire CMD output history (when youtube-dl is executed within Windows) while channels/videos are being archived/downloaded? When I run my script using a BAT file, it will display recent history only up to a point. Is there a way to log the entire run, beginning to end?

**Comment by dstftw** [comment]
Redirect stdout and stderr to file.

**Comment by ArchivistGoals** [comment]
How would I go about adding that to my script? I'm using Windows, and not familiar with how to do that. Thanks!
