### ISSUE TITLE
Invalid SHA256 for /downloads/latest/youtube-dl

### ISSUE THREAD

**Issue by 0xpr03** [ytdl-org/youtube-dl#20386]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [X] Other

---

### Description of your *issue*, suggested solution and other information

The version you can download from `https://yt-dl.org/downloads/latest/youtube-dl` is not the same as the one from `https://yt-dl.org/downloads/2019.03.09/youtube-dl`, which is now (17.03.19) marked as the latest one, according to `https://rg3.github.io/youtube-dl/update/versions.json`.
I detected this as my auto-update system errored out due to non-matching SHA signatures. Is this intended behavior ?

**Comment by dstftw** [comment]
youtube-dl is no longer hosted at rg3. rg3 will be kept as mirror for some time but it may take some delay to update.
