### ISSUE TITLE
[Pornhub] Dowloads form Pronhub fail sometimes with TypeError: int() argument must be a string or a number, not 'list'

### ISSUE THREAD

**Issue by throwaway75** [ytdl-org/youtube-dl#20403]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.pornhub.com/view_video.php?viewkey=ph5c539060057b7']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.18
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-16-generic-x86_64-with-Ubuntu-18.10-cosmic
[debug] exe versions: ffmpeg 4.0.2-2, ffprobe 4.0.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[PornHub] ph5c539060057b7: Downloading pc webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 472, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 462, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2006, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 794, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 225, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1924, in int_or_none
TypeError: int() argument must be a string or a number, not 'list'
```

### Description of your *issue*, suggested solution and other information
Sometimes a download from pornhub.com fails with the stacktrace shown above. This does not always happen and does not depend on the video. Running the same command multiple times fails sometimes and succeeds sometimes.
Dump of a failed download: https://gist.github.com/throwaway75/c67b7f30a269495aff3bafecaf884d7c

**Comment by nimeir** [comment]
Bug is easy to replicate. It happens like 1 out of 10 times. 

It is due to extra media definitions that leds to some kind of a manifest. Can someone shed light on what this is?

`{'defaultQuality': False, 'format': 'dash', 'videoUrl': 'https://cvc.phncdn.com/dash/videos/201902/01/205041911/,720P_4000K,480P_2000K,240P_400K,_205041911.mp4.urlset/manifest.mpd?chv3GnoUsCyDFYUIyUqLVEjCSCx7EuHYjYUr-0cpw0V8WjY7oVSARBn-O6DnOYQ24mtfZk15JMTh12DGytmbHooJwUDRe7mqlHkj5JN4hAQlFxiUWrZm9gc2yFHVarR0j-IxRj9LrT6luHPoa_gD6cRltLLh0A9qYwf98kV28snrY3S8NLY', 'quality': [720, 480, 240]}`
