### ISSUE TITLE
Request: Support for CriterionChannel.com

### ISSUE THREAD

**Issue by cheese-industries** [ytdl-org/youtube-dl#20408]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.criterionchannel.com/for-all-mankind/videos/for-all-mankind']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.03.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92833-gfccba32b4c
[debug] Proxy map: {}
[generic] for-all-mankind: Requesting header
WARNING: Falling back on generic information extractor.
[generic] for-all-mankind: Downloading webpage
[generic] for-all-mankind: Extracting information
ERROR: Unsupported URL: https://www.criterionchannel.com/for-all-mankind/videos/for-all-mankind
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpcs52imf5\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpcs52imf5\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpcs52imf5\build\youtube_dl\extractor\generic.py", line 3320, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.criterionchannel.com/for-all-mankind/videos/for-all-mankind
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

They haven't fully launched yet and are putting one film on the site per week. The only currently available film is here: https://www.criterionchannel.com/for-all-mankind/videos/for-all-mankind
 
---

### Description of your *issue*, suggested solution and other information

I'm requesting support for CriterionChannel.com. The site requires login, but offers a free one-month trial that can be cancelled at any time.

**Comment by 89z** [comment]
If you can provide credentials I can try to fix it. Run the following command and reply back with the output:

~~~
echo USER:PASS | age -a -r age1zkz9g0kld97vs826j0r7p3ghvz3zcyd4tcqr2vrxpt0uux7mkycsl77hy6
~~~

https://github.com/FiloSottile/age

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30449

**Comment by 89z** [comment]
The media links are easily available:

https://drm.vimeocdn.com/1641090211-0xa72ebd75caa973a40bb219b0f03ab854de999dcd/01/432/13/327163529/1281250748,1281250737,1281250749,1281250740/1281250749-4-t1.m4s?assetId=327163529

but they are protected by Vimeo DRM
