### ISSUE TITLE
[Twitch] collection support

### ISSUE THREAD

**Issue by cromefire** [ytdl-org/youtube-dl#20414]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Playlist: https://www.twitch.tv/collections/KFti877JixXiHQ (the first I found)

---

### Description of your *issue*, suggested solution and other information

See the url above for a random collection example, a collection is Twitch's version of a "playlist", currently ytdl thinks it's a streamer

```
ERROR: collections is offline
```

**Comment by mtilbury** [comment]
Hi, I've confirmed this issue still exists with the latest version, and specifying the `--yes-playlist` flag still results in the same error. It looks like there just isn't an information extractor to handle collections. I'm going to work on this.

**Comment by Kcee8** [comment]
Is this still being worked on?

**Comment by cromefire** [comment]
The PR is ready someone would just need to merge it

**Comment by zouhair** [comment]
This would be a nice thing to have
