### ISSUE TITLE
YouTube missing videos when Downloading Channel, Possibly VEVO Accounts only?

### ISSUE THREAD

**Issue by timethrow** [ytdl-org/youtube-dl#20415]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl --config-location "/mnt/e/Personal Documents/Infrastructure/Scripts/YouTube-DL/YT-DownloadConfig.txt" -a /mnt/e/Personal\ Documents/Infrastructure/Scripts/YouTube-DL/YT-Music.txt -o "/mnt/f/My Music/Videos/YouTube Channel/%(uploader)s/%(title)s.%(ext)s" >> musiclog.log
[debug] System config: []
[debug] User config: []
[debug] Custom config: [u'-i', u'--continue', u'--no-post-overwrites', u'--download-archive', u'/mnt/e/Personal Documents/Infrastructure/Lists/YT-MasterArchive.txt', u'--prefer-ffmpeg', u'--merge-output-format', u'mkv', u'--write-sub', u'--all-subs', u'--convert-subs', u'srt', u'--embed-subs', u'--add-metadata', u'--write-description', u'--write-info-json', u'-v']
[debug] Command-line args: [u'--config-location', u'/mnt/e/Personal Documents/Infrastructure/Scripts/YouTube-DL/YT-DownloadConfig.txt', u'-a', u'/mnt/e/Personal Documents/Infrastructure/Scripts/YouTube-DL/YT-Music.txt', u'-o', u'/mnt/f/My Music/Videos/YouTube Channel/%(uploader)s/%(title)s.%(ext)s']
[debug] Batch file urls: [u'https://www.youtube.com/channel/UC5MujsH-hrVWHBBfSSmv18A', u'https://www.youtube.com/playlist?list=PLwceFb1owDJnLxu3zmeQrfjdfBKSe3gYl', u'https://www.youtube.com/channel/UCqk3CdGN_j8IR9z4uBbVPSg', u'https://www.youtube.com/user/LordeMusic', u'https://www.youtube.com/user/LadyGagaVEVO', u'https://www.youtube.com/user/Marinaandthediamonds', u'https://www.youtube.com/user/SiaVEVO', u'https://www.youtube.com/user/adelelondon', u'https://www.youtube.com/channel/UC-huZzH2Ozkkt3lSIOSriQg', u'https://www.youtube.com/channel/UCPHjpfnnGklkRBBTd0k6aHg', u'https://www.youtube.com/user/icreateddisco/videos', u'https://www.youtube.com/channel/UCIjYyZxkFucP_W-tmXg_9Ow', u'https://www.youtube.com/user/davidguettavevo', u'https://www.youtube.com/channel/UCt-am4x4ZyeohfgM85qFgdQ', u'https://www.youtube.com/channel/UCYvmuw-JtVrTZQ-7Y4kd63Q']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2019.03.18
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.2.6-1, ffprobe 3.2.6-1
[debug] Proxy map: {}
...
<end of log>
```

When downloading Music Channels from YouTube some of the videos are missing and not includes in the downlaods for example;

https://www.youtube.com/user/icreateddisco/videos

Only shows 70 videos available, however many more are uplaoded and playable, an example of a missing one would be;

https://www.youtube.com/watch?v=DkeiKbqa02g

```
[youtube:user] icreateddisco: Downloading channel page
[youtube:playlist] UUIjYyZxkFucP_W-tmXg_9Ow: Downloading webpage
[download] Downloading playlist: Uploads from Calvin Harris
[youtube:playlist] playlist Uploads from Calvin Harris: Downloading 70 videos
[download] Downloading video 1 of 70
```

Another example is this channel;
https://www.youtube.com/user/florencemachine

A few that are missing are ;
https://www.youtube.com/watch?v=ScxZwXH09Ws
https://www.youtube.com/watch?v=HajiEqEtIRY
https://www.youtube.com/watch?v=zMBTvuUlm98

```
[youtube:user] florencemachine: Downloading channel page
[youtube:playlist] UU5MujsH-hrVWHBBfSSmv18A: Downloading webpage
[download] Downloading playlist: Uploads from florencemachine
[youtube:playlist] playlist Uploads from florencemachine: Downloading 37 videos
[download] Downloading video 1 of 37
[youtube] iu7YURHcmKI: Downloading webpage
[youtube] iu7YURHcmKI: Downloading video info webpage
```

All the missing videos seem to be official Music Videos or Lyric Videos for officially released stuff, everything else seems to be fine and included. So far only noticed it on the vevo style accounts.

Is there away to get youtube-dl to download all the videos in the channel including the music videos.

**Comment by ealgase** [comment]
Not a youtube-dl issue, this is actually YouTube lying about the true channel of the video.  The channel that video is hosted on is UCaHNFIob5Ixv74f5on3lvIw.

**Comment by timethrow** [comment]
Thanks for that, How did you find that Channel ID, it seems to have more in it?

I thought I found the one for 'https://www.youtube.com/user/florencemachine' as 'https://www.youtube.com/channel/UC5MujsH-hrVWHBBfSSmv18A' but its still shows the same number of videos and there are videos missing (same examples as above)

```
youtube-dl https://www.youtube.com/channel/UC5MujsH-hrVWHBBfSSmv18A
[youtube:channel] UC5MujsH-hrVWHBBfSSmv18A: Downloading channel page
[youtube:playlist] UU5MujsH-hrVWHBBfSSmv18A: Downloading webpage
[download] Downloading playlist: Uploads from florencemachine
[youtube:playlist] playlist Uploads from florencemachine: Downloading 37 videos
[download] Downloading video 1 of 37
[youtube] iu7YURHcmKI: Downloading webpage
[youtube] iu7YURHcmKI: Downloading video info webpage
```

I tried playing a video and getting the Channel ID from the User underneath the video but that did not seem to work in this case.

Thanks

**Comment by timethrow** [comment]
Dont worry, think I have found it now;

```
youtube-dl -j --skip-download "https://www.youtube.com/watch?v=zMBTvuUlm98" | jq -r '.channel_url'
```
