### ISSUE TITLE
Cannot download vimeo video

### ISSUE THREAD

**Issue by Tjorriemorrie** [ytdl-org/youtube-dl#20428]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

```
$  pipenv run youtube-dl -v https://www.homegrownfoodsummit.com/john-livingston-chicken-mini-business/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.homegrownfoodsummit.com/john-livingston-chicken-mini-business/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.03.18
[debug] Python version 3.6.0 (CPython) - Windows-10-10.0.15063-SP0
[debug] exe versions: ffmpeg 2.8.4, ffprobe N-87353-g183fd30
[debug] Proxy map: {}
[generic] john-livingston-chicken-mini-business: Requesting header
WARNING: Falling back on generic information extractor.
[generic] john-livingston-chicken-mini-business: Downloading webpage
[generic] john-livingston-chicken-mini-business: Extracting information
ERROR: Unsupported URL: https://www.homegrownfoodsummit.com/john-livingston-chicken-mini-business/
Traceback (most recent call last):
  File "c:\cygwin64\home\jaco.jansen\.virtualenvs\youtube-cyogsqqv\lib\site-packages\youtube_dl\YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "c:\cygwin64\home\jaco.jansen\.virtualenvs\youtube-cyogsqqv\lib\site-packages\youtube_dl\extractor\common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "c:\cygwin64\home\jaco.jansen\.virtualenvs\youtube-cyogsqqv\lib\site-packages\youtube_dl\extractor\generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.homegrownfoodsummit.com/john-livingston-chicken-mini-business/
```

it seems that url should be easily supported

**Comment by Hrxn** [comment]
How so? That's not a Vimeo link?

**Comment by ealgase** [comment]
@Hrxn It's a Vimeo embed that isn't properly extracted.

**Comment by Hrxn** [comment]
Yeah, but how is youtube-dl supposed to know?
Isn't there some Vimeo button in the video corner? Or a share link, or the embed link functionality? Might get the Vimeo link from there.

**Comment by Tjorriemorrie** [comment]
A lot of sites put vimeo videos without download links embedded on their
webpages - it is also private and not available on vimeo. They do this so
that users purchase the videos or products, etc. This used to work, but has
been breaking now - vimeo must have changed something.
Let me know if the page has been removed, I'll probably find others.

**Comment by ealgase** [comment]
> Yeah, but how is youtube-dl supposed to know?
> Isn't there some Vimeo button in the video corner? Or a share link, or the embed link functionality? Might get the Vimeo link from there.

youtube-dl is supposed to find Vimeo embeds and download them.  In this case, finding the embed fails.  As @Tjorriemorrie said, you can't view it directly on Vimeo.
