### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by hasnogaems** [ytdl-org/youtube-dl#20440]
```
F:\>youtube-dl --ffmpeg-location F:\twitch download\ffmpegnew\bin --hls-prefer-n
ative https://www.youtube.com/watch?v=4HNwJR_XfJs
ERROR: 'download\\ffmpegnew\\bin' is not a valid URL. Set --default-search "ytse
arch" (or run  youtube-dl "ytsearch:download\ffmpegnew\bin" ) to search YouTube
```

**Comment by merkle-root** [comment]
Put quotes around the ffmpeg path.

Your command line is interpreting `F:\twitch` and `download\ffmpegnew\bin` as separate arguments, because of the space. 
With command lines, you have to put quotes around paths that contains spaces.

**Comment by hasnogaems** [comment]
> Put quotes around the ffmpeg path.
> 
> Your command line is interpreting `F:\twitch` and `download\ffmpegnew\bin` as separate arguments, because of the space.
> With command lines, you have to put quotes around paths that contains spaces.

I tried ' ' and " " quotes with no sucess.

**Comment by bitraid** [comment]
`\"` escapes the quote. the string should end with `bin"`
