### ISSUE TITLE
Hotstar downloading is not working properly 

### ISSUE THREAD

**Issue by rahiblogger** [ytdl-org/youtube-dl#20450]
When i was trying to download video from hotstar manually by Youtubedl is getting 403 error.
Here is the complete youtube-dl output for hotstar video:

(venv) [root@103-211-219-47 vd]# youtube-dl --verbose https://www.hotstar.com/sports/cricket/vivo-ipl-2018/chennai-super-kings-vs-sunrisers-hyderabad-m186561/match-clips/mighty-csk-boss-srh-for-third-title/2001614574
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.hotstar.com/sports/cricket/vivo-ipl-2018/chennai-super-kings-vs-sunrisers-hyderabad-m186561/match-clips/mighty-csk-boss-srh-for-third-title/2001614574']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.18
[debug] Python version 3.6.6 (CPython) - Linux-3.10.0-862.3.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
[debug] exe versions: none
[debug] Proxy map: {}
[hotstar] 2001614574: Downloading webpage
[hotstar] 2001614574: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
File "/root/vd/venv/lib64/python3.6/site-packages/youtube_dl/extractor/common.py", line 626, in _request_webpage
return self._downloader.urlopen(url_or_request)
File "/root/vd/venv/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2225, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
response = meth(req, response)
File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
return self._call_chain(*args)
File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
result = func(*args)
File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by dstftw** [comment]
It's geo restricted.

**Comment by rahiblogger** [comment]
But some days ago it was working. Suddenly it is not working now.
There are 2-3 geo restriction which is working good.
