### ISSUE TITLE
How does download-archive work with private or deleted videos in a playlist?

### ISSUE THREAD

**Issue by Kaos-Industries** [ytdl-org/youtube-dl#20455]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Hey there. I've been using `youtube-dl` for a few years now to download my playlists from YouTube so I can listen to them offline, but I'm now looking into automating the process, and as a result, I'm wondering a few things about the underlying workings of `youtube-dl`.

I've been looking into the `--download-archive` as a method for backing up the latest videos from my YouTube playlists to a local drive, but a big motivation for me backing up the playlists in the first place is so I can stop losing YouTube videos that suddenly get deleted or made private, so I'm wondering - how exactly does `--download-archive` handle videos that have been deleted or made private? 

Alternatively, if anyone experienced at automation with bash knows of a better method for doing what I'm planning to do here, I'm entirely open to it.

**Comment by dstftw** [comment]
What do you mean by handle videos? `--download-archive` has nothing to do with private or deleted videos. All it does is storing ids of downloaded videos in archive file and skipping videos with ids already present in this file.

**Comment by Kaos-Industries** [comment]
> 
> 
> What do you mean by handle videos? `--download-archive` has nothing to do with private or deleted videos. All it does is storing ids of downloaded videos in archive file and skipping videos with ids already present in this file.

And how exactly do private and deleted videos factor into that? They are included when downloading a playlist with `--flat-playlist` means they're listed - are they also included in the archive file when using `--download-archive`?

**Comment by dstftw** [comment]
`--flat-playlist` does not download videos and has nothing to do with download archive.
Again: ids are included into download archive only after successful file download. If a video is deleted or unavailable then you can't download it thus can't store in download archive.
