### ISSUE TITLE
[CWTV] Episode # Mismatch

### ISSUE THREAD

**Issue by jaylweb** [ytdl-org/youtube-dl#20461]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--get-filename', '-f', 'mp4[height=720]', '--continue', '--no-check-certificate', '-o', '%(series)s - s%(season_number)02de%(episode_number)02d - %(title)s.%(ext)s', 'https://www.cwtv.com/shows/legacies/lets-just-finish-the-dance/?play=a86515a5-2a0e-43d8-9546-64f1bc4f6da4', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.03.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-92963-g1ea5529dd2, ffprobe N-92963-g1ea5529dd2, rtmpdump 2.4
[debug] Proxy map: {}
Legacies - s01e04 - Let's Just Finish the Dance.mp4

```

---
### Description of your *issue*, suggested solution and other information

Episode number is for the below Legacies link is '14' but youtube-dl keeps saying it's '04'.  This has occurred for every Legacies episode past 10.  For example, '11' is returned as '01'.  

https://www.cwtv.com/shows/legacies/lets-just-finish-the-dance/?play=a86515a5-2a0e-43d8-9546-64f1bc4f6da4

When I look at the dump using the write-pages parameter, I can see the following info in one of the files and it shows it as episode 14. 

`
		<param name="assetId" value="a86515a5-2a0e-43d8-9546-64f1bc4f6da4"/>
		<param name="brand" value="CWTV"/>
		<param name="bugEnabled" value="false"/>
		<param name="contentType" value="Full Episodes"/>
		<param name="episodeNumber" value="14"/>
		<param name="isFullEpisode" value="true"/>
		<param name="publishDate" value="2019-03-14T00:00:00-0700"/>
		<param name="seasonNumber" value="1"/>
		<param name="seriesCode" value="LGC"/>
		<param name="seriesTitle" value="Legacies"/>
		<param name="tmsId" value="EP029731020014"/>
		<param name="videoId" value="a86515a5-2a0e-43d8-9546-64f1bc4f6da4"/>
`

I've attached the dump files for your review. 

[Legacies_Episode_14_write-pages_Output.zip](https://github.com/ytdl-org/youtube-dl/files/3000480/Legacies_Episode_14_write-pages_Output.zip)

**Comment by compguy284** [comment]
As far as I can tell the following line is what causes this issue.
`episode = episode.lstrip(season)`
https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/cwtv.py#L82

**Comment by jaylweb** [comment]
That makes sense.  If the episode number was 114, then lstrip(1) would remove "11" leaving "4" since it removes all of the "1" characters at the left of the string.  

Could the solution be as simple as this? 
`episode = episode[1:]`
