### ISSUE TITLE
How to disable or bypass the enforced PAC proxy script set by corporate Group Policy in my browser

### ISSUE THREAD

**Issue by NiesmialyGosc** [ytdl-org/youtube-dl#20467]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
D:\video>youtube-dl --proxy 51.38.234.95:8080 --all-subs --convert-subs srt -o"
2228.mp4" -v https://www.france.tv/france-3/plus-belle-la-vie/plus-belle-la-vie-
saison-9/943823-plus-belle-la-vie.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', '51.38.234.95:8080', '--all-subs', '--con
vert-subs', 'srt', '-o 2228.mp4', '-v', 'https://www.france.tv/france-3/plus-bel
le-la-vie/plus-belle-la-vie-saison-9/943823-plus-belle-la-vie.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2019.03.18
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-89508-g1f1207145a, ffprobe N-89508-g1f1207145a
[debug] Proxy map: {'https': '51.38.234.95:8080', 'http': '51.38.234.95:8080'}
[FranceTVSite] 943823-plus-belle-la-vie: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [WinError 10054] An existing c
onnection was forcibly closed by the remote host> (caused by URLError(Connection
ResetError(10054, 'An existing connection was forcibly closed by the remote host
', None, 10054, None),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpcs52im
f5\build\youtube_dl\extractor\common.py", line 626, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpcs52im
f5\build\youtube_dl\YoutubeDL.py", line 2225, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpcs52im
f5\build\youtube_dl\utils.py", line 1140, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open


D:\video>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

The network connectivity at my home is terribly poor and it takes more than 5 hours to download a video of 300MB! And the downloads are interrupted from time to time. Therefore I have to download the videos in my office..

However, I cannot disable or bypass the Automatic Configuration Script (proxy.pac) set by the corporate Group Policy in my browser LAN Settings to download videos using a French proxy.. 

Is there a way to bypass group policy and disable the .pac proxy configuration script or is it possible for my French proxy to override the .pac in order for it to work..

![PAC](https://user-images.githubusercontent.com/40756687/54901545-bdde1f80-4f11-11e9-96b6-44308f3d7ae6.png)
![DAMN GROUP POLICY](https://user-images.githubusercontent.com/40756687/54901546-be76b600-4f11-11e9-88bb-baa14cc7ca5a.png)

Thank you!
NiesmialyGosc

**Comment by NiesmialyGosc** [comment]
Isn't it even possible to defeat the Group Policy and set a command-prompt-wide proxy in youtube-dl command lines for video download???

**Comment by dstftw** [comment]
youtube-dl does not use these settings. Most likely your public proxy is dead.
