### ISSUE TITLE
Metadata parser won't even gather album info

### ISSUE THREAD

**Issue by modern-hermit** [ytdl-org/youtube-dl#20475]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

The request is about metadata. It's too limited, mainly on YouTube: even if the video has information about the music album, the extractor won't get it.
I've been trying to download a playlist; to analyze the problem with fewer objects, I've been using [this video](https://www.youtube.com/watch?v=Z7shb-2SxXM). It has album metadata; but even with `writeinfojson=True`, I can't seem to find the album's name. I'm using
`options = dict(quiet=False,
				addmetadata=True,
				writethumbnail=True,
               outtmpl=out_dir + "\\%(title)s.%(ext)s",
               format="bestaudio/best",
			   prefer_ffmpeg=True,
			   writeinfojson=True,
               ffmpeg_location=os.path.join(os.getcwd(), r"mp3_ytdl\ffmpeg"),
               postprocessors=[{"key": "FFmpegExtractAudio", "preferredcodec": "mp3"},
			   {'key': 'FFmpegMetadata'},
			   {'key': 'EmbedThumbnail', 'already_have_thumbnail': True}])
`

as options, but I had no advance at all. Please give us more info about music metadata!

**Comment by remitamine** [comment]
```
youtube-dl -j https://www.youtube.com/watch?v=Z7shb-2SxXM | jq .album
"Infections of a Different Kind (Step I)"
```
