### ISSUE TITLE
Ignore active livestreams

### ISSUE THREAD

**Issue by Kjarrval** [ytdl-org/youtube-dl#20485]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I believe a parameter option to ignore active livestreams could be a useful feature. For example when I'm downloading a whole YouTube channel, youtube-dl would start downloading the active livestream and be stuck on it until it the broadcast has completed, which might be many hours. An ignore option for those livestreams could be useful in the cases where the user feels it's sufficient to download the livestream recording sometime later.

Since the output template option is_live exists, it might only be a matter of utilising information which is already available within youtube-dl. Meaning if is_live is True, that video is skipped/ignored if that parameter is given.

**Comment by preekaur** [comment]
Is this issue still up for grabs? I am a student at the University of Michigan looking to contribute to an open source project for a class assignment. We are expected to work on open issues which are not being tackled at the moment. If someone is pursuing this issue, I would appreciate it if you could let me know

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl/issues/12946#issuecomment-298299093
