### ISSUE TITLE
RegexNotFoundError on RTP channel

### ISSUE THREAD

**Issue by PortPhil** [ytdl-org/youtube-dl#20480]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```

```
paul@paul-NC10 ~ $ youtube-dl --verbose -o "/home/paul/Videos/%(title)s.%(ext)s" --fragment-retries 1 https://www.rtp.pt/play/p5285/e397170/jornal-da-tarde-2019 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-o', u'/home/paul/Videos/%(title)s.%(ext)s', u'--fragment-retries', u'1', u'https://www.rtp.pt/play/p5285/e397170/jornal-da-tarde-2019']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.18
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-143-generic-i686-with-LinuxMint-18.3-sylvia
[debug] exe versions: ffmpeg 3.2.6-1, ffprobe 3.2.6-1, phantomjs 2.1.1, rtmpdump 2.4-n111-gitfa8646d-ppa10p1
[debug] Proxy map: {}
[RTP] e397170: Downloading webpage
ERROR: Unable to extract player config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rtp.py", line 40, in _real_extract
    r'(?s)RTPPLAY\.player\.newPlayer\(\s*(\{.*?\})\s*\)', webpage, 'player config')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I'm using version 2019.03.18. I tried to download the programme I've pasted from The RTP website but got the error message above. Downloads have worked fine in the past. Whilst the programme will stream perfectly in a browser, I prefer to download. I'm afraid that's about all I can tell you.

**Comment by mtilbury** [comment]
Hi, I've confirmed this issue exists with the link you've provided. Also, the [test case URL](http://www.rtp.pt/play/p405/e174042/paixoes-cruzadas) for rtp has a similar error:  `ERROR: Unable to extract player config`

I'm assuming that the site has changed its layout, and now the extractor can't get the player config information it needs. I'm going to take a look at this.

**Comment by PortPhil** [comment]
Hi,
That's good news. Thanks for looking at it.

**Comment by nimeir** [comment]
I made a pull request for a fix here: https://github.com/ytdl-org/youtube-dl/pull/20484
I did the test case and it seems to be working.
