### ISSUE TITLE
extract audio without reencoding

### ISSUE THREAD

**Issue by yvikt** [ytdl-org/youtube-dl#20483]
Hi
Do youtube-dl option --extract-audio extracts audio without reencodinng?
I mean is there option -c:a copy in ffmpeg postprocessing after downloading original video?
I want to be sure that the audio is preserved in its original (native) codec.
Thanks!

**Comment by dstftw** [comment]
Depends on whether custom `--audio-format` is specified or not.

**Comment by yvikt** [comment]
For example 
youtube-dl -f 251 -x  https://www.youtube.com/watch?v=ZRSNy8DcIDk
What happens here? Does transcoding occur in this case, or just saving original stream without transcoding?

**Comment by dstftw** [comment]
No transcoding occurs.

**Comment by yvikt** [comment]
thanks a lot
