### ISSUE TITLE
"The uploader has not made this video available in your country." but it's actually available in every country...

### ISSUE THREAD

**Issue by kazoooka** [ytdl-org/youtube-dl#20494]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

---

- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

---

- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
```
<beginning of log>
./youtube-dl  https://www.youtube.com/watch?v=PGNiXGX2nLU -v
[debug] System config: [u'--force-ipv4', u'--no-check-certificate']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=PGNiXGX2nLU', u'-v']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2019.03.18
[debug] Python version 2.7.9 (CPython) - Linux-4.15.18-12-pve-x86_64-with-debian-8.11
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] PGNiXGX2nLU: Downloading webpage
[youtube] PGNiXGX2nLU: Downloading video info webpage
ERROR: The uploader has not made this video available in your country.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1982, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: The uploader has not made this video available in your country.
<end of log>
```

---

So i'm using youtube-dl like shown in the log but i can't seem to get the video because i get the message "The uploader has not made this video available in your country.". 
The thing is - my server stands in germany - i'm also in germany. I can watch the video on my computer but not download it on the server... 

I checked the georestrictions of the video but it's globally allowed...

https://polsy.org.uk/stuff/ytrestrict.cgi?ytid=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DPGNiXGX2nLU

Hope someone here can help me...

**Comment by dstftw** [comment]
Can you watch it in browser from exactly this server machine and exactly this network interface in the first place?

**Comment by kazoooka** [comment]
No i can't because it's a GUIless Debian machine...
