### ISSUE TITLE
not working since this mounth on https://www.france.tv

### ISSUE THREAD

**Issue by felixltx** [ytdl-org/youtube-dl#20504]
youtube-dl --verbose https://www.france.tv/france-3/brokenwood/brokenwood-saison-5/932733-dix-petits-heritiers.html
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.france.tv/france-3/brokenwood/brokenwood-saison-5/932733-dix-petits-heritiers.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.30
[debug] Python version 3.7.2 (CPython) - Linux-5.0.3-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
[debug] exe versions: ffmpeg 4.0.3, ffprobe 4.0.3
[debug] Proxy map: {}
[FranceTVSite] 932733-dix-petits-heritiers: Downloading webpage
ERROR: Unable to extract video ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/francetv.py", line 280, in _real_extract
    webpage, 'video ID').split('@')
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 992, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video ID; please report this issue on https://yt-dl.org/bug

**Comment by duramuss** [comment]
This should be reopened:

youtube-dl version 2019.04.01

youtube-dl --verbose "https://www.france.tv/france-5/le-monde-en-face/939909-brexit-les-coulisses-d-un-divorce.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.france.tv/france-5/le-monde-en-face/939909-brexit-les-coulisses-d-un-divorce.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.01
[debug] Python version 2.7.15 (CPython) - Linux-4.19.7-pds98-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[FranceTVSite] 939909-brexit-les-coulisses-d-un-divorce: Downloading webpage
[FranceTV] ca61bf3d-2a97-4b8d-ac8c-0eede7f802f1: Downloading video JSON
[FranceTV] ca61bf3d-2a97-4b8d-ac8c-0eede7f802f1: Downloading geo restriction info
[FranceTV] ca61bf3d-2a97-4b8d-ac8c-0eede7f802f1: Downloading signed m3u8-download manifest URL
[FranceTV] ca61bf3d-2a97-4b8d-ac8c-0eede7f802f1: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[FranceTV] ca61bf3d-2a97-4b8d-ac8c-0eede7f802f1: Downloading signed hls_v5_os manifest URL
[FranceTV] ca61bf3d-2a97-4b8d-ac8c-0eede7f802f1: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "dl/youtube-dl-2019.03.18/youtube-dl/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "dl/youtube-dl-2019.03.18/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "dl/youtube-dl-2019.03.18/youtube-dl/youtube_dl/extractor/francetv.py", line 209, in _real_extract
    return self._extract_video(video_id, catalog)
  File "dl/youtube-dl-2019.03.18/youtube-dl/youtube_dl/extractor/francetv.py", line 169, in _extract_video
    self._sort_formats(formats)
  File "dl/youtube-dl-2019.03.18/youtube-dl/youtube_dl/extractor/common.py", line 1326, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
