### ISSUE TITLE
[Feature request] : Add a -d option to store the current downloaded video to a specific directory

### ISSUE THREAD

**Issue by sebma** [ytdl-org/youtube-dl#20502]
## Please follow the guide below
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Can you please add a `-d` option with a string argument to store the current downloaded video to a specific directory (that is different from the default directory which I have given with the -o `DIR/%(title)s.%(ext)` option) : 

`$ youtube-dl -d $myDIR/ $url`

**Comment by dstftw** [comment]
What's the point of this? Just use this specific directory in `-o` argument.

**Comment by sebma** [comment]
@dstftw Here is the point : I believe each option of any console tool (such as `youtube-dl`) should be atomic : 

>        -o, --output TEMPLATE
>               Output filename template, see the "OUTPUT TEMPLATE" for all  the
>               info
> 

`-o` should be used for filename pattern ONLY.

I always use the same filename pattern which I store in `youtube-dl.conf` for convenience purposes.

I don't want to type the following commands each time I want to store videos in different directories with the same video filename pattern : 

`$ youtube-dl -o"DIR1/%(title)s__%(format_id)s__%(id)s.%(ext)s" ...`
and then another time : 
`$ youtube-dl -o"DIR2/%(title)s__%(format_id)s__%(id)s.%(ext)s" ...`
and then another time : 
`$ youtube-dl -o"DIR3/%(title)s__%(format_id)s__%(id)s.%(ext)s" ...`

This can become very laborious over time, don't think ?

I'm hoping you would reopen my feature request.

Jesus bless you.

**Comment by sebma** [comment]
@dstftw I'm sorry but your solution does not work :
```
$ youtube-dl -o tmp2/ http://www.youtube.com/watch?v=Fl50abzGYG4
[youtube] Fl50abzGYG4: Downloading webpage
[youtube] Fl50abzGYG4: Downloading video info webpage
[youtube] Fl50abzGYG4: Looking for automatic captions
[youtube] Fl50abzGYG4: Downloading MPD manifest
ERROR: unable to open for writing: [Errno 21] Is a directory: 'tmp2/'
```

**Comment by vinqin** [comment]
Agree with @sebma. Please accept this convenient feature.
