### ISSUE TITLE
[Stitcher] Poor Metadata Extraction

### ISSUE THREAD

**Issue by wertercatt** [ytdl-org/youtube-dl#20510]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.18*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
powerkitten@blaze-pc:~$ youtube-dl -v https://www.stitcher.com/podcast/brashgames/brashcast/e/48566743
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.stitcher.com/podcast/brashgames/brashcast/e/48566743']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.18
[debug] Python version 3.6.7 (CPython) - Linux-4.20.0-15.1-liquorix-amd64-x86_64-with-Ubuntu-18.10-cosmic
[debug] exe versions: ffmpeg 4.0.2-2, ffprobe 4.0.2-2
[debug] Proxy map: {}
[Stitcher] 48566743: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://www.brashgames.co.uk/wp-content/uploads/2016/04/Brashcast_Episode_58.mp3'
[download] Destination: Brashcast - Episode 58 – DC is La Liga and Marvel is the Premiership-48566743.mp3
[download] 100% of 102.28MiB in 00:38
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

youtube-dl doesn't provide proper metadata for Stitcher urls. It doesn't include the release date or the show that uploaded it. This is a problem for the archival script "tubeup" as it causes archived podcast episodes to not be properly credited. See https://archive.org/details/Stitcher-48566742 for an example of how it gets messed up. https://www.stitcher.com/podcast/brashgames/brashcast/e/48566742 has the metadata needed to properly credit them, but that metadata doesn't make it to info.json resulting in the script getting confused.

**Comment by preekaur** [comment]
Is this issue still open? I would love to take a shot at it :)

**Comment by wertercatt** [comment]
@preekaur hasn't been fixed to my knowledge, so feel free.
