### ISSUE TITLE
downloading worst audio+video and perhaps combining?

### ISSUE THREAD

**Issue by osmand** [ytdl-org/youtube-dl#20511]
when downloading -f worst or "-f worst-audio+worst-video/worst" it downloads first format

that has both audio and video,

but smallest audio size plus size of smallest video is much smaller than that

I think a feature that can download smallest both and combine them perhaps would be desirable

for backup archive purposes (of the knowledge)

perhaps by running ffmpeg externally

thanks

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.18**

- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

**Comment by dstftw** [comment]
`worstaudio` and `worstvideo` without dashes.

**Comment by osmand** [comment]
thanks a lot I couldnt find it in the manual or where I looked.
