### ISSUE TITLE
disneynow.go.com

### ISSUE THREAD

**Issue by pYbiz** [ytdl-org/youtube-dl#20542]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.01*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.01**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.04.01
[debug] Python version 3.6.8 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg N-93294-g056a2ac168, ffprobe N-93294-g056a2ac168
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://disneynow.go.com/disney-channel-original-movies/the-cheetah-girls/vdka0_x5lchobu

### Description of your *issue*, suggested solution and other information

Im trying to download from https://disneynow.go.com/disney-channel-original-movies/the-cheetah-girls/vdka0_x5lchobu but it says 

```
C:\Users\admin\Desktop\youtube-dl>youtube-dl --ap-mso TWC --ap-username xxxx --ap-password xxxx https://disneynow.go.com/disney-channel-original-movies/the-cheetah-girls/vdka0_x5lchobu
[Go] vdka0_x5lchobu: Downloading webpage
[Go] VDKA0_x5lchobu: Downloading JSON metadata
[Go] VDKA0_x5lchobu: Downloading Provider Redirect Page
[Go] VDKA0_x5lchobu: Downloading Provider Login Page
[Go] VDKA0_x5lchobu: Logging in
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by compguy284** [comment]
I'm willing to bet that the TWC mso as been basically deprecated/renamed for/to Spectrum. See bug/issue #20466

**Comment by pYbiz** [comment]
I tried spectrum also, same error

**Comment by nlistgarten** [comment]
@pYbiz have you tried `--ap-mso Charter_Direct`?

**Comment by joshbgosh10592** [comment]
I'm in the same boat with Verizon FiOS, using "--ap-mso Verizon" with correct creds.

**Comment by dstftw** [comment]
For any work on this you must provide MSO credentials.
