### ISSUE TITLE
amcnetworks: ERROR: Unable to extract media url;

### ISSUE THREAD

**Issue by portableos8989** [ytdl-org/youtube-dl#20552]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.01*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', 'https://www.amc.com/shows/the-walking-dead/video-ex                           >
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.01
[debug] Python version 3.7.3 (CPython) - Linux-4.9.112-15119402-aarch64-with-libc
[debug] exe versions: ffmpeg 4.1.2, ffprobe 4.1.2
[debug] Proxy map: {}
[AMCNetworks] spoilers-wrapping-up-season-9-of-the-walking-dead: Downloading webpage
ERROR: Unable to extract media url; please report this issue on https://yt-dl.org/bug . Make sure you are                           >
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 794, i                           >
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line                           >
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/youtube_dl/extractor/amcnetworks.py",                           >
    webpage, 'media url')
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line                           >
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract media url; please report this issue on https://yt-                      
..
<end of log>
```

---

### Downloading videos from https://www.amc.com/shows/the-walking-dead with youtube-dl fails now. This is free content and doesn't need a TV provider login that I can tell. I did try also to download witb the TV provider login, but same results of failure. This did work last month March 2019. Please help resolve.

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by portableos8989** [comment]
Why is this incomplete?

**Comment by remitamine** [comment]
Duplicate of #20354.
