### ISSUE TITLE
bestaudio codecs vorbis or opus

### ISSUE THREAD

**Issue by dreamchonghua** [ytdl-org/youtube-dl#20567]
How to make （bestaudio[ext=webm]）Choice"vorbis"，Instead of "opus",Thank you

The code is as follows：youtube-dl.exe -f bestvideo[ext=webm]+bestaudio[ext=webm] --merge-output-format webm https://www.youtube.com/watch?v=r3V4sBPxMow --proxy "127.0.0.1:1080" --external-downloader aria2c --external-downloader-args "-x 90 -k 1M"
![20190405050806](https://user-images.githubusercontent.com/22128443/55588631-d72c6a80-5760-11e9-8abc-0c1c53f38fd9.png)

**Comment by remitamine** [comment]
this is an issue tracker for `youtube-dl` command line tool.

**Comment by dstftw** [comment]
`-f bestaudio[ext=webm][acodec*=vorbis]`.

**Comment by dreamchonghua** [comment]
Thank you. I've developed it myself. The code is as follows. Thank you.

youtube-dl.exe -f bestvideo[ext=webm]+bestaudio[ext=webm][acodec=vorbis] --merge-output-format webm https://www.youtube.com/watch?v=r3V4sBPxMow --proxy "127.0.0.1:1080" --external-downloader aria2c --external-downloader-args "-x 90 -k 1M"
