### ISSUE TITLE
How to automatically download the highest quality webm

### ISSUE THREAD

**Issue by dreamchonghua** [ytdl-org/youtube-dl#20565]
How to automatically download the highest quality webm, my code is as follows：
youtube-dl.exe -f bestvideo[ext=webm]+bestaudio[ext=webm] --merge-output-format mp4 https://www.youtube.com/watch?v=r3V4sBPxMow --proxy "127.0.0.1:1080" --external-downloader aria2c --external-downloader-args "-x 90 -k 1M"

The downloaded video is silent. Thank you.

**Comment by dstftw** [comment]
You can't merge webm into mp4 container, don't touch `--merge-output-format` if you have no idea of what you are doing.
