### ISSUE TITLE
Can --update be used in the same command line when downloading a video?

### ISSUE THREAD

**Issue by DaveF63** [ytdl-org/youtube-dl#20570]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.01**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Question-

Using windows 7 running from a batch file

**Can --update be used in the same command line when downloading a video or does it have to be run as a separate command?**
I've tried:
```
youtube-dl --update -f best --prefer-ffmpeg --no-continue --no-part -o "C:\Downloads\xx.mp4" https://www.youtube.com/watch?v=XbsrlKg2oUY
```
&
```
youtube-dl --update
youtube-dl -f best --prefer-ffmpeg --no-continue --no-part -o "C:\Downloads\xx.mp4" https://www.youtube.com/watch?v=XbsrlKg2oUY
```
Used another batch file to `call` two separate batch files each containing one of the above lines.
Used `start /wait ` option for each line.

This is the output every time:

> [youtube] XbsrlKg2oUY: Downloading webpage
> [youtube] XbsrlKg2oUY: Downloading video info webpage
> [download] Destination: C:\Downloads\Video\Clouds of Witness\xx.mp4
> [download]  23.2% of 34.51MiB at  7.36MiB/s ETA 00:03 Access is denied.
> Updated youtube-dl to version 2019.04.01.
> [download] 100% of 34.51MiB in 00:04

It downloads but doesn't delete `youtube-dl.exe.new` The second command to download the video doesn't wait & appears to lock the update process.
Is there a solution?

**Comment by dstftw** [comment]
Solutions is not to run further commands until update is complete.

**Comment by DaveF63** [comment]
Hmm.. Not much of a solution. 

I've looked a bit deeper at this page: https://ytdl-org.github.io/youtube-dl/download.html
wget/curl could be used to d/l https://yt-dl.org/downloads/2019.04.01/youtube-dl.exe if the folder wasn't formatted as the latest date.

Is there a reason it can't be in a 'latest' folder similar to the unix versions?
