### ISSUE TITLE
Download the title of the file

### ISSUE THREAD

**Issue by reov** [ytdl-org/youtube-dl#20578]
When my server created the config download youtube video, I found that many characters of the downloaded title are empty, but there is no problem with windows, the config content is -o /root/Downloads/%(title)s.%(ext)s
--exec "rclone move {} /root/GoogleDrive/youtube-dl/", 
on ssh
youtube-dl https://www.youtube.com/watchv=3AyrbaUUF70&list=PLAy_aKkcOIK4e1de9i0P0bVIfDz4wYkQS&index=266&t=0s
[3] 31380
[4] 31381
[5] 31382
[2]   Done                    youtube-dl https://www.youtube.com/watch?v=3AyrbaUUF70
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[youtube] 3AyrbaUUF70: Downloading webpage
[youtube] 3AyrbaUUF70: Downloading video info webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: /root/Downloads/MMD.f299.mp4
[download] 100% of 80.76MiB in 00:03
[download] Destination: /root/Downloads/MMD.f251.webm
[download]  62.9% of 3.18MiB at 20.71MiB/s ETA 00:0

However, this is the case on windows.
youtube-dl https://www.youtube.com/watch?v=3AyrbaUUF70&list=PLAy_aKkcOIK4e1de9i0P0bVIfDz4wYkQS&index=266&t=0s
[youtube] 3AyrbaUUF70: Downloading webpage
[youtube] 3AyrbaUUF70: Downloading video info webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: [MMD]儒雅恋人言和 #遗世蒹葭-3AyrbaUUF70.f299.mp4
[download] 100% of 80.76MiB in 00:12
[download] Destination: [MMD]儒雅恋人言和 #遗世蒹葭-3AyrbaUUF70.f251.webm
[download] 100% of 3.18MiB in 00:00
[ffmpeg] Merging formats into "[MMD]儒雅恋人言和 #遗世蒹葭-3AyrbaUUF70.mkv"
Deleting original file [MMD]儒雅恋人言和 #遗世蒹葭-3AyrbaUUF70.f299.mp4 (pass -k to keep)
Deleting original file [MMD]儒雅恋人言和 #遗世蒹葭-3AyrbaUUF70.f251.webm (pass -k to keep)

**Comment by remitamine** [comment]
> WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.

and also quote the url: https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command

**Comment by reov** [comment]
I looked at other problems, the easiest way is to update the python, the latest version can
