### ISSUE TITLE
Report url of downloading video in progress hook

### ISSUE THREAD

**Issue by bbappserver** [ytdl-org/youtube-dl#20579]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.01*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

`youtube-dl` should report the url it's operating on in the python progress hooks.
When the calling process cannot always determine the url because sometimes `youtube-dl` is used to process playlists.  However the calling process may need to collect the page url, and perhaps the url of the actual video stream.

---
### Description of your *issue*, suggested solution and other information

`youtube-dl` should report the url it's operating on in the python progress hooks.
When the calling process cannot always **determine the url because sometimes `youtube-dl` is used to process playlists**.  However the calling process may need to collect the page url, and perhaps the url of the actual video stream.

Simply add a two items to progress hooks:

- `page_url`:The page in which the currently downloaded media was embed
- `data_url`: The network location of the media backing the player embedded in the page (if applicable)

**Comment by dstftw** [comment]
Progress hook is supposed to deliver downloading progress information not metadata. Any video metadata must be extracted separately if needed.
