### ISSUE TITLE
Youtube-dl BUG with MPV Playing at 60 fps in config.

### ISSUE THREAD

**Issue by fwanky** [ytdl-org/youtube-dl#20589]
Youtube-dl version 2019.03.18
Arch
mpv 0.29.1
When using the flag [fps<=?60] in ytdl-format=bestvideo[height<=?1080][fps<=?60]+bestaudio/best in your mpv config, videos will cease to play at 60fps and will go to 30 for some odd reason.

As you can see, it's playing at the highest quality, like i wanted, but 30 and not 60?
https://0x0.st/zZaw.txt

More info here, https://github.com/mpv-player/mpv/issues/6616

Thanks.

**Comment by dstftw** [comment]
You are getting exactly what you request: bestvideo format with height under 1080 and fps under 60 that is format 136. If you want 60 fps you must specify 60 fps exactly not <=.

**Comment by fwanky** [comment]
Well how do I specify it so it's 60?
