### ISSUE TITLE
How to remove zero padding from playlist_index

### ISSUE THREAD

**Issue by blueray453** [ytdl-org/youtube-dl#20582]
The documentation says -

> playlist_index (numeric): Index of the video in the playlist padded with leading zeros according to the total length of the playlist

I do not want the leading zeros.

The template I am currently using is

`youtube-dl -o '%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s'`

The file names currently look like the following -

001-First-File.mp4
002-Second-File.mp4
.....
105-HundredFifth-File.mp4

**I want it to look like the following -**

1-First-File.mp4
2-Second-File.mp4
....
105-HundredFifth-File.mp4

How can I do that?

**Comment by dstftw** [comment]
Use `d` formatter not `s`.
