### ISSUE TITLE
 jwplatform.py is broken with  https://github.com/joedborg/youtube-dl/pull/49

### ISSUE THREAD

**Issue by ipaha** [ytdl-org/youtube-dl#20596]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.07*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**
youtube-dl --version
2019.04.07

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] User config: []

[debug] Custom config: []

[debug] Command-line args: [u'--verbose', u'--prefer-ffmpeg', u'--format', u'bestaudio', u'--extract-audio', u'--audio-format', u'opus', u'--audio-quality', u'0', u'--keep-video', u'--output', u'\u0421\u0432\u043e\u0439 \u0441\u043e\u0431\u0441\u0442\u0432\u0435\u043d\u043d\u044b\u0439 \u043f\u0443\u0442\u044c (\u0414\u0435\u0432\u0438\u0434 \u0414\u043e\u0440\u043d\u0430\u043d).f%(format_id)s.%(ext)s', u'https://content.jwplatform.com/manifests/NdSc5Qlg.m3u8?exp=1554635121']

[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8

[debug] youtube-dl version 2019.04.07

[debug] Git HEAD: a46d9e5

[debug] Python version 2.7.16 (CPython) - Darwin-15.6.0-x86_64-i386-64bit

[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.0, ffprobe 4.0

[debug] Proxy map: {}

[generic] NdSc5Qlg: Requesting header

WARNING: Could not send HEAD request to https://content.jwplatform.com/manifests/NdSc5Qlg.m3u8?exp=1554635121: HTTP Error 403: Forbidden

[generic] NdSc5Qlg: Downloading webpage

ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

File "/Users/pavel.shevtsiv/IdeaProjects/youtube-dl/youtube_dl/extractor/common.py", line 626, in _request_webpage

return self._downloader.urlopen(url_or_request)

File "/Users/pavel.shevtsiv/IdeaProjects/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen

return self._opener.open(req, timeout=self._socket_timeout)

File "/anaconda2/lib/python2.7/urllib2.py", line 435, in open

response = meth(req, response)

File "/anaconda2/lib/python2.7/urllib2.py", line 548, in http_response

'http', request, response, code, msg, hdrs)

File "/anaconda2/lib/python2.7/urllib2.py", line 473, in error

return self._call_chain(*args)

File "/anaconda2/lib/python2.7/urllib2.py", line 407, in _call_chain

result = func(*args)

File "/anaconda2/lib/python2.7/urllib2.py", line 556, in http_error_default

raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Playlist:  https://content.jwplatform.com/manifests/NdSc5Qlg.m3u8?exp=1554638831\&sig=b7f01a3ce1e275dffe6ff74599f02ac5

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

jwplatform.py is broken with
https://github.com/joedborg/youtube-dl/pull/49
locally checked
git checkout b0ead0e youtube_dl/extractor/jwplatform.py

[debug] Command-line args: [u'--verbose', u'--prefer-ffmpeg', u'--format', u'bestaudio', u'--extractaudio', u'--audio-format', u'opus', u'--audio-quality', u'0', u'--keep-video', u'--output',
u'⧵u0421⧵u0432⧵u043e⧵u0439 ⧵u0441⧵u043e⧵u0431⧵u0441⧵u0442⧵u0432⧵u0435⧵u043d⧵u043d⧵
u044b⧵u0439 ⧵u043f⧵u0443⧵u0442⧵u044c (⧵u0414⧵u0435⧵u0432⧵u0438⧵u0434
⧵u0414⧵u043e⧵u0440⧵u043d⧵u0430⧵u043d).f%(format_id)s.%(ext)s', u'https://content.jwplatform.
com/manifests/NdSc5Qlg.m3u8?exp=1554638831&sig=b7f01a3ce1e275dffe6ff74599f02ac5']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Git HEAD: a46d9e5
[debug] Python version 2.7.16 (CPython) - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.0, ffprobe 4.0
[debug] Proxy map: {}
[generic] NdSc5Qlg: Requesting header
[generic] NdSc5Qlg: Downloading m3u8 information
[debug] Invoking downloader on u'https://jwpsrv­vh.akamaihd.net/i/content/conversions/
wdjHsEgT/videos/NdSc5Qlg­1174958.m4a/index_0_av.m3u8?hdnts=exp=1554645949~acl=*/
NdSc5Qlg­1174958.m4a/*~hmac=f21b00021afd9b239203835df49484
9caf1e458daeb9c4b7fc4fc90a17b0a748'
So it is working for previous comm

command to run
python -m youtube_dl --verbose --prefer-ffmpeg --format 'bestaudio' --extract-audio --audio-format "opus"
--audio-quality 0 --keep-video --output 'Свой собственный путь (Девид Дорнан).f%(format_id)s.%(ext)s'
https://content.jwplatform.com/manifests/NdSc5Qlg.m3u8?exp=1554638831\&sig=
b7f01a3ce1e275dffe6ff74599f02ac5

**Comment by dstftw** [comment]
Does not work in browser either.

**Comment by ipaha** [comment]
Hi, @dstftw . This issue is valid. @remitamine knows all details and has fixed the issue. I've just checked this version 9c01725 . Now it is working as expected.
