### ISSUE TITLE
Unable to download GDC videos.

### ISSUE THREAD

**Issue by antdude** [ytdl-org/youtube-dl#20594]
Example:

$ youtube-dl -v https://www.gdcvault.com/play/1025777/Classic-Game-Postmortem-Command-Conquer
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.gdcvault.com/play/1025777/Classic-Game-Postmortem-Command-Conquer']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.4.2 (CPython) - Linux-3.16.0-8-amd64-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
[GDCVault] Classic-Game-Postmortem-Command-Conquer: Downloading webpage
WARNING: [GDCVault] It looks like http://www.gdcvault.com/play/1025777 requires a login. Try specifying a username and password and try again.
WARNING: [GDCVault] Could not login.
ERROR: Unable to extract xml filename; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/gdcvault.py", line 166, in _real_extract
    start_page, 'xml filename')
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 1013, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract xml filename; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by sophiepeithos** [comment]
@dstftw I am sorry, but could you tell me which issue this issue is duplicated with?
