### ISSUE TITLE
Bitrate/resolution priority switch

### ISSUE THREAD

**Issue by welljsjs** [ytdl-org/youtube-dl#20606]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

#### Before submitting an *issue* make sure I have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of my *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of my *issue*, suggested solution and other information

Currently, the bitrate of videos takes priority over the resolution. 

It'd be great if this behaviour could be changed (resolution over bitrate) with a single flag. 

At the time, this is only possible by using a very large format flag (f.ex. `-f 'bestvideo[height >= 1920]/[height >= 1280]/[height >= 720]/...'`. 

Sometimes, I'd like to download the file with the higher resolution instead of a higher bitrate. 

A simple switch flag would be extremely convenient (f.ex. `--priority-bitrate` and `--priority-resolution` where `--priority-bitrate` is the default behaviour).

**Comment by dstftw** [comment]
No, since this does not scale. Custom formats sorting option should be implemented instead.
