### ISSUE TITLE
Mediasite Extractor issue

### ISSUE THREAD

**Issue by th3picow** [ytdl-org/youtube-dl#20607]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.07*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\User\Downloads>youtube-dl --cookies=cookies.txt --verbose https://mediasite.uis.no/Mediasite/Catalog/catalogs/mat200-v2019
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies=cookies.txt', '--verbose', 'https://mediasite.uis.no/Mediasite/Catalog/catalogs/mat200-v2019']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[MediasiteNamedCatalog] mat200-v2019: Downloading webpage
ERROR: Unable to extract catalog id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\extractor\mediasite.py", line 362, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\extractor\common.py", line 1004, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract catalog id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

Fails at extracting download links from catalog, leave a comment and I'll supply you with cookies.txt or username and password for the site (added dstftw to repository with username and password and cookies.txt as you have resolved my previous issues)

**Comment by dstftw** [comment]
![image](https://user-images.githubusercontent.com/1908898/55740568-8e70fc00-5a55-11e9-8e74-1a49afe16bde.png)

**Comment by th3picow** [comment]
Ahh sorry, renamed it so must have broken link. Resent invite

**Comment by dstftw** [comment]
Either invalid or expired cookies file.
```
> py -2.7 .\youtube_dl\__main__.py https://mediasite.uis.no/Mediasite/Catalog/catalogs/mat200-v2019 --cookies cookies.txt -i
[MediasiteNamedCatalog] mat200-v2019: Downloading webpage
[MediasiteCatalog] 5d5fac2b-9183-4986-94f9-747913dccfff: Downloading webpage
[MediasiteCatalog] 5d5fac2b-9183-4986-94f9-747913dccfff: Downloading JSON metadata
[download] Downloading playlist: MAT200 - Matematiske Metoder 2 - våren 2019
[MediasiteCatalog] playlist MAT200 - Matematiske Metoder 2 - våren 2019: Collected 41 video ids (downloading 41 of them)
[download] Downloading video 1 of 41
[Mediasite] fddc7950dbc643e6af1a903c2279f1071d: Downloading webpage
[Mediasite] fddc7950dbc643e6af1a903c2279f1071d: Downloading JSON metadata
[Mediasite] fddc7950dbc643e6af1a903c2279f1071d: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 404: Not Found
[Mediasite] fddc7950dbc643e6af1a903c2279f1071d: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[Mediasite] fddc7950dbc643e6af1a903c2279f1071d: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 404: Not Found
[Mediasite] fddc7950dbc643e6af1a903c2279f1071d: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
ERROR: unable to download video data: HTTP Error 404: Not Found
[download] Downloading video 2 of 41
[Mediasite] 5f69fa18cf6946e192114c5fa9c88cf31d: Downloading webpage
[Mediasite] 5f69fa18cf6946e192114c5fa9c88cf31d: Downloading JSON metadata
[Mediasite] 5f69fa18cf6946e192114c5fa9c88cf31d: Downloading ISM manifest
WARNING: [Mediasite]  is not a supported codec
[Mediasite] 5f69fa18cf6946e192114c5fa9c88cf31d: Downloading MPD manifest
[Mediasite] 5f69fa18cf6946e192114c5fa9c88cf31d: Downloading ISM manifest
WARNING: [Mediasite]  is not a supported codec
[Mediasite] 5f69fa18cf6946e192114c5fa9c88cf31d: Downloading MPD manifest
[Mediasite] 5f69fa18cf6946e192114c5fa9c88cf31d: Downloading ISM manifest
WARNING: [Mediasite]  is not a supported codec
[Mediasite] 5f69fa18cf6946e192114c5fa9c88cf31d: Downloading MPD manifest
[Mediasite] 5f69fa18cf6946e192114c5fa9c88cf31d: Downloading ISM manifest
WARNING: [Mediasite]  is not a supported codec
[Mediasite] 5f69fa18cf6946e192114c5fa9c88cf31d: Downloading MPD manifest
[dashsegments] Total fragments: 1092
[download] Destination: MAT200 mandag_4_8_2019-5f69fa18cf6946e192114c5fa9c88cf31d.fvideo1-1.2-1_V_video_1.mp4
[download]   0.2% of ~152.36MiB at 509.86KiB/s ETA 20:58
ERROR: Interrupted by user
```

**Comment by th3picow** [comment]
Tried with new cookies.txt and just inputting username and password directly into youtube-dl commandline with --username and --password but I still just get the same error

'''
C:\Users\magnus\Downloads>py -2.7 C:\Users\magnus\Downloads\youtube-dl-master\youtube_dl\__main__.py https://mediasite.uis.no/Mediasite/Catalog/catalogs/mat200-v2019 --cookies=cookies.txt -i -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://mediasite.uis.no/Mediasite/Catalog/catalogs/mat200-v2019', u'--cookies=cookies.txt', u'-i', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.04.07
[debug] Python version 2.7.16 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[MediasiteNamedCatalog] mat200-v2019: Downloading webpage
ERROR: Unable to extract catalog id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\magnus\Downloads\youtube-dl-master\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\magnus\Downloads\youtube-dl-master\youtube_dl\extractor\common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\magnus\Downloads\youtube-dl-master\youtube_dl\extractor\mediasite.py", line 362, in _real_extract
    r'CatalogId\s*:\s*["\'](%s)' % _ID_RE, webpage, 'catalog id')
  File "C:\Users\magnus\Downloads\youtube-dl-master\youtube_dl\extractor\common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract catalog id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


C:\Users\magnus\Downloads>py -2.7 C:\Users\magnus\Downloads\youtube-dl-master\youtube_dl\__main__.py https://mediasite.uis.no/Mediasite/Catalog/catalogs/mat200-v2019 --username username --password password -i -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://mediasite.uis.no/Mediasite/Catalog/catalogs/mat200-v2019', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'-i', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.04.07
[debug] Python version 2.7.16 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[MediasiteNamedCatalog] mat200-v2019: Downloading webpage
ERROR: Unable to extract catalog id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\magnus\Downloads\youtube-dl-master\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\magnus\Downloads\youtube-dl-master\youtube_dl\extractor\common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\magnus\Downloads\youtube-dl-master\youtube_dl\extractor\mediasite.py", line 362, in _real_extract
    r'CatalogId\s*:\s*["\'](%s)' % _ID_RE, webpage, 'catalog id')
  File "C:\Users\magnus\Downloads\youtube-dl-master\youtube_dl\extractor\common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract catalog id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


C:\Users\magnus\Downloads>py -3.7 C:\Users\magnus\Downloads\youtube-dl-master\youtube_dl\__main__.py https://mediasite.uis.no/Mediasite/Catalog/catalogs/mat200-v2019 --username username --password password -i -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://mediasite.uis.no/Mediasite/Catalog/catalogs/mat200-v2019', '--username', 'PRIVATE', '--password', 'PRIVATE', '-i', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.7.0 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[MediasiteNamedCatalog] mat200-v2019: Downloading webpage
ERROR: Unable to extract catalog id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\magnus\Downloads\youtube-dl-master\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\magnus\Downloads\youtube-dl-master\youtube_dl\extractor\common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\magnus\Downloads\youtube-dl-master\youtube_dl\extractor\mediasite.py", line 362, in _real_extract
    r'CatalogId\s*:\s*["\'](%s)' % _ID_RE, webpage, 'catalog id')
  File "C:\Users\magnus\Downloads\youtube-dl-master\youtube_dl\extractor\common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract catalog id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
'''

Even tried launching it from the command line like you did, even tried different versions of python. Are you using windows aswell?

**Comment by th3picow** [comment]
nevermind it's working now
