### ISSUE TITLE
New downloads from ITV Hub not working

### ISSUE THREAD

**Issue by johnreay** [ytdl-org/youtube-dl#20617]
Example follows

john@systemj ~/Videos/TV Shows/2019 $ youtube-dl --verbose "https://www.itv.com/hub/the-widow/2a5540"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.itv.com/hub/the-widow/2a5540']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-47-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: avconv 3.4.4, avprobe 3.4.4, ffmpeg 3.1.3-static, ffprobe 3.4.4, rtmpdump 2.4
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[debug] Using fake IP 25.51.31.191 (GB) as X-Forwarded-For.
[ITV] 2a5540: Downloading webpage
ERROR: Unable to extract params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/itv.py", line 62, in _real_extract
    r'(?s)(<[^>]+id="video"[^>]*>)', webpage, 'params'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by remitamine** [comment]
youtube-dl does not support show pages, for now, you can use individual episode URLs(ex: https://www.itv.com/hub/the-widow/2a5540a0001).

**Comment by mattheys** [comment]
I've used the following node-red code to generate a playlist file that you can then download with 
```youtube-dl -i --download-archive archive.txt -a playlist.txt --socket-timeout 2```  

```
[{"id":"66b17bde.aeffa4","type":"inject","z":"61dd4d54.ab17d4","name":"","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"Test","payloadType":"str","x":110,"y":50,"wires":[["a706303.2a852d"]]},{"id":"a706303.2a852d","type":"http request","z":"61dd4d54.ab17d4","name":"","method":"GET","ret":"txt","url":"https://www.itv.com/hub/the-hive/1a9014","tls":"","x":150,"y":100,"wires":[["3ca0343f.d0007c"]]},{"id":"3ca0343f.d0007c","type":"html","z":"61dd4d54.ab17d4","name":"","property":"payload","outproperty":"payload","tag":"a.complex-link","ret":"attr","as":"single","x":200,"y":150,"wires":[["3cb6e303.7763ac"]]},{"id":"3cb6e303.7763ac","type":"function","z":"61dd4d54.ab17d4","name":"","func":"var txt = \"\";\n\nmsg.payload.forEach(function(data){\n    if(data.href.includes('the-hive')){\n        txt += data.href + \"\\n\"; \n    }\n});\n\nmsg.payload = txt;\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":210,"y":200,"wires":[["dec7963e.3f01d8"]]},{"id":"dec7963e.3f01d8","type":"file","z":"61dd4d54.ab17d4","name":"","filename":"/mnt/data/playlist.txt","appendNewline":false,"createDir":false,"overwriteFile":"true","x":290,"y":250,"wires":[[]]}]
```

A bit of automation and you could have node-red export the playlist a few mins before a cron job runs youtube-dl.
