### ISSUE TITLE
[geo-bypass AT] not working ever

### ISSUE THREAD

**Issue by avagraha** [ytdl-org/youtube-dl#20613]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.07*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.04.07
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

[geo-bypass AT] not working ever
The output is a video with warning available from austria only. I guess that geobypass is not working even if i see the changed ip.

I tried both commands

1)

y -v --geo-bypass https://tvthek.orf.at/profile/Archiv/7648449/Neues-beim-Wiener-Sommernachtskonzert/13919349/Neues-beim-Wiener-Sommernachtskonzert/13995118

2)

C:\Users\andrea>y -v --geo-bypass-country AT https://tvthek.orf.at/profile/Archiv/7648449/Neues-beim-Wiener-Sommernachtskonzert/13919349/Neues-beim-Wiener-Sommernachtskonzert/13995118
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--geo-bypass-country', 'AT', 
'https://tvthek.orf.at/profile/Archiv/7648449/Neues-beim-Wiener-Sommernachtskonzert/13919349/Neues-beim-Wiener-Sommernachtskonzert/13995
118']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-92765-g2744d6b-Reino, ffprobe 
N-92765-g2744d6b-Reino
[debug] Proxy map: {}
[debug] Using fake IP 84.113.128.149 (AT) as X-Forwarded-For.
[orf:tvthek] 13995118: Downloading webpage
[orf:tvthek] 13995118: Downloading m3u8 information
[orf:tvthek] 13995118: Downloading f4m manifest
[orf:tvthek] 13995118: Downloading f4m manifest
[orf:tvthek] 13995118: Downloading f4m manifest
[orf:tvthek] 13995118: Downloading f4m manifest
[orf:tvthek] 13995118: Downloading m3u8 information
[orf:tvthek] 13995118: Downloading m3u8 information
[orf:tvthek] 13995118: Downloading m3u8 information
[orf:tvthek] 13995118: Downloading m3u8 information
[orf:tvthek] 13995118: Checking hls-QXB-Adaptiv-1572 video format URL
[orf:tvthek] 13995118: Checking hls-Q1A-Niedrig-1572 video format URL
[orf:tvthek] 13995118: Checking hls-Q4A-Mittel-1572 video format URL
[orf:tvthek] 13995118: Checking hls-Q6A-Hoch-1572 video format URL
[orf:tvthek] 13995118: Checking hls-Q8C-Sehr hoch-1572 video format URL
[download] Downloading playlist: 13995118
[orf:tvthek] playlist 13995118: Collected 1 video ids (downloading 1 of 
them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 
'https:://apasfiis.sf.apa.at/ipad/cms-austria_abr/20160525_0900_in_02_Neues-beim-Wien_____13919349__o__1147162205__s13995118.mp4/chunklist.m3u8?lbs=20190408202053066&orig
in=http%253a%252f%252fvarorfvod.sf.apa.at%252fsystem_clips%252fgeoprotection_q5a.mp4%252fchunklist.m3u8&ip=2.40.118.139&ua=Mozilla%252f5.0%2b(X11%253b%2bLinux%2bx86_64%253b%2brv%253a59.0)%2bGecko%252f
20100101%2bFirefox%252f59.0'
[download] Destination: Neues beim Wiener Sommernachtskonzert-13995118.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "Cookie: 
ASP.NET_SessionId=bmvjqye02h2ahgg1hr4nprwn
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 
Firefox/59.0
X-Forwarded-For: 84.113.128.149
" -i 
"https://apasfiis.sf.apa.at/ipad/cms-austria_abr/20160525_0900_in_02_Neues-beim-Wien_____13919349__o__1147162205__s13995118.mp4/chunklist.m3u8?lbs=20190408202053066&origin=http%253a%252f%252fvaro
rfvod.sf.apa.at%252fsystem_clips%252fgeoprotection_q5a.mp4%252fchunklist.m3u8&ip=2.40.118.139&ua=Mozilla%252f5.0%2b(X11%253b%2bLinux%2bx86_64%253b%2brv%253a59.0)%2bGecko%252f20100101%2bFirefox%252f59.
0" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:Neues beim Wiener 
Sommernachtskonzert-13995118.mp4.part"
ffmpeg version N-92765-g2744d6b-Reino Copyright (c) 2000-2018 the FFmpeg 
developers
  built with gcc 8.2.0 (GCC)
  configuration: --arch=x86 --target-os=mingw32 --cross-prefix=/cygdrive/m/ffmpeg-windows-build-helpers-master/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32- 
 --pkg-co
nfig=pkg-config --pkg-config-flags=--static --extra-version=Reino --enable-gray 
 --enable-version3 --disable-debug --disable-doc --disable-htmlpages --disable-manpages 
 --disable-podpages --disable-txtp
ages --disable-w32threads --enable-avisynth --enable-frei0r --enable-filter=frei0r 
 --enable-gmp --enable-gpl --enable-libaom --enable-libass --enable-libbluray 
 --enable-libbs2b --enable-libcaca --extr
a-cflags=-DCACA_STATIC --enable-libfdk-aac --enable-libflite --enable-libfontconfig 
 --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc 
 --enable-libmp3lame --enab
le-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 
 --enable-libopenmpt --enable-libopus --enable-librubberband --enable-libsnappy 
 --enable-libsoxr --enable-libspee
x --enable-libtheora --enable-libtwolame --extra-cflags=-DLIBTWOLAME_STATIC  
--enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx 
 --enable-libwebp --enable-libx264 --enable-li
bx265 --enable-libxavs --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzvbi 
 --enable-mbedtls --extra-cflags='-march=pentium3' --extra-cflags='-mtune=athlon-xp' 
 --extra-cflags=-O2 --extr
a-cflags='-mfpmath=sse' --extra-cflags=-msse --enable-static --disable-shared 
 --prefix=/cygdrive/m/ffmpeg-windows-build-helpers-master/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-i686/i686-w64-mingw32  libavutil      56. 25.100 / 56. 25.100  libavcodec     58. 42.104 / 58. 42.104  libavformat    58. 25.100 / 58. 25.100  libavdevice    58.  6.101 / 58.  6.101  libavfilter     7. 46.101 /  7. 46.101  libswscale      5.  4.100 /  5.  4.100  libswresample   3.  4.100 /  3.  4.100  libpostproc    55.  4.100 / 55.  4.100[tcp @ 00affd40] Starting connection attempt to 185.85.29.106 port 443[tcp @ 00affd40] Successfully connected to 185.85.29.106 port 443[hls,applehttp @ 00af9280] HLS request for url'https://varorfvod.sf.apa.at/system_clips/geoprotection_q5a.mp4/media_0.ts?lbs=20190408202053066&ip=2.40.118.139&ua=Mozilla%252f5.0%2b(X11%253b%2bLinux%2bx86_64%253b%2brv%253a59.0)%2bGecko%252f20100101%2bFirefox%252f59.0', offset0, playlist 0[hls,applehttp @ 00af9280] Opening'https://varorfvod.sf.apa.at/system_clips/geoprotection_q5a.mp4/media_0.ts?lbs=20190408202053066&ip=2.40.118.139&ua=Mozilla%252f5.0%2b(X11%253b%2bLinux%2bx86_64%253b%2brv%253a59.0)%2bGecko%252f20100101%2bFirefox%252f59.0' for reading[tcp @ 009bc900] Starting connection attempt to 185.85.28.129 port 443[tcp @ 009bc900] Successfully connected to 185.85.28.129 port 443[h264 @ 009ceac0] Reinit context to 960x544, pix_fmt: yuv420pInput #0, hls,applehttp, from'https://apasfiis.sf.apa.at/ipad/cms-austria_abr/20160525_0900_in_02_Neues-beim-Wien_____13919349__o__1147162205__s13995118.mp4/chunklist.m3u8?lbs=20190408202053066&origin=http%253a%252f%252fvarorfvod.sf.apa.at%252fsystem_clips%252fgeoprotection_q5a.mp4%252fchunklist.m3u8&ip=2.40.118.139&ua=Mozilla%252f5.0%2b(X11%253b%2bLinux%2bx86_64%253b%2brv%253a59.0)%2bGecko%252f20100101%2bFirefox%252f59.0':  Duration: 00:00:10.04, start: 0.000000, bitrate: 0 kb/s  Program 0    Metadata:      variant_bitrate : 0    Stream #0:0: Data: timed_id3 (ID3  / 0x20334449)    Metadata:      variant_bitrate : 0    Stream #0:1: Video: h264 (Main), 1 reference frame ([27][0][0][0] /0x001B), yuv420p(tv, left), 960x540 (960x544) [SAR 1:1 DAR 16:9], 25 fps, 25tbr, 90k tbn, 50 tbc    Metadata:      variant_bitrate : 0    Stream #0:2: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo,fltp    Metadata:      variant_bitrate : 0Output #0, mp4, to 'file:Neues beim WienerSommernachtskonzert-13995118.mp4.part':  Metadata:    encoder         : Lavf58.25.100    Stream #0:0: Video: h264 (Main), 1 reference frame (avc1 / 0x31637661),yuv420p(tv, left), 960x540 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr,90k tbn, 90k tbc    Metadata:      variant_bitrate : 0    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp    Metadata:      variant_bitrate : 0Stream mapping:  Stream #0:1 -> #0:0 (copy)  Stream #0:2 -> #0:1 (copy)Press [q] to stop, [?] for helpNo more output streams to write to, finishing.e=00:00:09.72bitrate=1510.3kbits/s speed=2.58xframe=  251 fps= 67 q=-1.0 Lsize=    1839kB time=00:00:10.00bitrate=1506.7kbits/s speed=2.65xvideo:1598kB audio:234kB subtitle:0kB other streams:0kB global headers:0kBmuxing overhead: 0.431283%Input file #0(https://apasfiis.sf.apa.at/ipad/cms-austria_abr/20160525_0900_in_02_Neues-beim-Wien_____13919349__o__1147162205__s13995118.mp4/chunklist.m3u8?lbs=20190408202053066&origin=http%253a%252f%252fvarorfvod.sf.apa.at%252fsystem_clips%252fgeoprotection_q5a.mp4%252fchunklist.m3u8&ip=2.40.118.139&ua=Mozilla%252f5.0%2b(X11%253b%2bLinux%2bx86_64%253b%2brv%253a59.0)%2bGecko%252f20100101%2bFirefox%252f59.0):  Input stream #0:0 (data): 0 packets read (0 bytes);  Input stream #0:1 (video): 251 packets read (1636112 bytes);  Input stream #0:2 (audio): 469 packets read (242506 bytes);  Total: 720 packets (1878618 bytes) demuxedOutput file #0 (file:Neues beim WienerSommernachtskonzert-13995118.mp4.part):  Output stream #0:0 (video): 251 packets muxed (1636112 bytes);  Output stream #0:1 (audio): 469 packets muxed (239223 bytes);  Total: 720 packets (1875335 bytes) muxed[AVIOContext @ 00a0bb80] Statistics: 2 seeks, 11 writeouts[AVIOContext @ 009c1b80] Statistics: 1966856 bytes read, 0 seeks[AVIOContext @ 0099ea80] Statistics: 347 bytes read, 0 seeks[ffmpeg] Downloaded 1883423 bytes[download] 100% of 1.80MiB in 00:05[download] Finished downloading playlist: 13995118C:\

**Comment by dstftw** [comment]
It's not supposed to work in all cases.

**Comment by avagraha** [comment]
In what cases it is supposed to work? You confirm that geobypass doest work ever?

**Comment by avagraha** [comment]
Anyway until february it was suposed to work because it worked.

**Comment by dstftw** [comment]
Option description clearly states how it works and when.
