### ISSUE TITLE
Unable to extract course id

### ISSUE THREAD

**Issue by RobotNetwork** [ytdl-org/youtube-dl#20625]
user@localhost~$ youtube-dl --version
2019.04.07

youtube-dl - username@gmail.com -p ******* -o '~/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/the-modern-python3-bootcamp/ --verbose -s
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-o', '~/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s', 'https://www.udemy.com/the-modern-python3-bootcamp/', '--verbose', '-s']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.7.1 (CPython) - Linux-4.18.0-17-generic-x86_64-with-debian-buster-sid
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in
[udemy:course] the-modern-python3-bootcamp: Downloading webpage
[udemy:course] 1350984: Downloading course curriculum
[download] Downloading playlist: 1350984
[udemy:course] playlist 1350984: Collected 253 video ids (downloading 253 of them)
[download] Downloading video 1 of 253
[udemy] Downloading login popup
[udemy] 9166920: Downloading webpage
ERROR: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 216, in _real_extract
    course_id, _ = self._extract_course_info(webpage, lecture_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 79, in _extract_course_info
    r'data-course-id=["\'](\d+)', webpage, 'course id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by RobotNetwork** [comment]
Apologies.

Make sure you are using the latest version: run youtube-dl --version and ensure your version is 2019.04.01. If it's not, read this FAQ entry and update. Issues with outdated version will be rejected.
[X] I've verified and I assure that I'm running youtube-dl 2019.04.01
Before submitting an issue make sure you have:
[X] At least skimmed through the README, most notably the FAQ and BUGS sections
[X] Searched the bugtracker for similar issues including closed ones
[X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

**Comment by isaaci** [comment]
> 
> 
> Apologies.
> 
> Make sure you are using the latest version: run youtube-dl --version and ensure your version is 2019.04.01. If it's not, read this FAQ entry and update. Issues with outdated version will be rejected.
> [X] I've verified and I assure that I'm running youtube-dl 2019.04.01
> Before submitting an issue make sure you have:
> [X] At least skimmed through the README, most notably the FAQ and BUGS sections
> [X] Searched the bugtracker for similar issues including closed ones
> [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

I have the latest version 2019.04.07 and still I am getting the same error...
