### ISSUE TITLE
is there a way to find out where the configuration file of youtube-dl is ?

### ISSUE THREAD

**Issue by shirishag75** [ytdl-org/youtube-dl#20627]
Is there a way to find out where the configuration file of youtube-dl is ? The only info. I could find is - 

```
 --config-location PATH
              Location of the configuration file; either the path to the config or its containing directory.
```

which means you could give it a path but not a way to query it.

**Comment by dstftw** [comment]
Configurations are stored at default locations. `--config-location` is used to provide user configuration under custom location. Read [FAQ](https://github.com/ytdl-org/youtube-dl#configuration).
