### ISSUE TITLE
[YourPorn] Domain changed to sxyprn.com

### ISSUE THREAD

**Issue by dapperfish** [ytdl-org/youtube-dl#20628]
YourPorn.sexy Domain changed to sxyprn.com which breaks the extractor and then falls back to the generic downloader which gets the thumbnail instead of video 

youtube-dl --verbose 'https://sxyprn.com/post/5cad9f8a26d51.html?sk=Many-Vids&so=0&ss=latest'               
[debug] System config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://sxyprn.com/post/5cad9f8a26d51.html?sk=Many-Vids&so=0&ss=latest']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.7.3 (CPython) - Linux-5.0.7-arch1-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] Proxy map: {}
[generic] 5cad9f8a26d51: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 5cad9f8a26d51: Downloading webpage
[generic] 5cad9f8a26d51: Extracting information
[generic] playlist Lunaxjames - Fucking My Asian Sex Doll - Manyvids #asian #bubblebutt #pale #roleplay #pigtails on SexyPorn: Collected 12 video ids (downloading 12 of them)
[download] Downloading video 1 of 12
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s10.trafficdeposit.com//blog/vid/5a6534e03bbb4/5cab7d0bd2a31/vidthumb.mp4'
1-1.mp4
[download] 100% of 249.05KiB in 00:00
[download] Downloading video 2 of 12
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s18.trafficdeposit.com//blog/vid/5c7aa58c8c195/5caa34cd5927b/vidthumb.mp4'
1-2.mp4
[download] Downloading video 3 of 12
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s14.trafficdeposit.com//blog/vid/5ba53b584947a/5cacd0a1ad653/vidthumb.mp4'
1-3.mp4
[download] 100% of 123.50KiB in 00:00
[download] Downloading video 4 of 12
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s19.trafficdeposit.com//blog/vid/5ab2a85d635c4/5ca9a3d3675fb/vidthumb.mp4'
1-4.mp4
[download] 100% of 172.44KiB in 00:00
[download] Downloading video 5 of 12
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s19.trafficdeposit.com//blog/vid/5ba53b584947a/5cab801a05f9b/vidthumb.mp4'
1-5.mp4
[download] 100% of 118.19KiB in 00:00
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s4.trafficdeposit.com//blog/vid/5b68a7a3c3d95/5cad071036ebd/vidthumb.mp4'
[download] Destination: Lunaxjames - Fucking My Asian Sex Doll - Manyvids #asian #bubblebutt #pale #roleplay #pigtails on SexyPorn (6)-5cad9f8a26d51-6.mp4
[download] 100% of 135.05KiB in 00:00
[download] Downloading video 7 of 12
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s20.trafficdeposit.com//blog/vid/59b613729e694/5cada7480fcec/vidthumb.mp4'
[download] Destination: Lunaxjames - Fucking My Asian Sex Doll - Manyvids #asian #bubblebutt #pale #roleplay #pigtails on SexyPorn (7)-5cad9f8a26d51-7.mp4
[download] 100% of 176.89KiB in 00:00
[download] Downloading video 8 of 12
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s8.trafficdeposit.com//blog/vid/5ab2a85d635c4/5cad9dce1958a/vidthumb.mp4'
[download] Destination: Lunaxjames - Fucking My Asian Sex Doll - Manyvids #asian #bubblebutt #pale #roleplay #pigtails on SexyPorn (8)-5cad9f8a26d51-8.mp4
[download] 100% of 155.98KiB in 00:00
[download] Downloading video 9 of 12
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s15.trafficdeposit.com//blog/vid/5ab2a85d635c4/5cad966a5596a/vidthumb.mp4'
[download] Destination: Lunaxjames - Fucking My Asian Sex Doll - Manyvids #asian #bubblebutt #pale #roleplay #pigtails on SexyPorn (9)-5cad9f8a26d51-9.mp4
[download] 100% of 380.13KiB in 00:01
[download] Downloading video 10 of 12
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s13.trafficdeposit.com//blog/vid/5ba53b584947a/5cad35c5ce1e4/vidthumb.mp4'
[download] Destination: Lunaxjames - Fucking My Asian Sex Doll - Manyvids #asian #bubblebutt #pale #roleplay #pigtails on SexyPorn (10)-5cad9f8a26d51-10.mp4
[download] 100% of 254.63KiB in 00:00
[download] Downloading video 11 of 12
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s4.trafficdeposit.com//blog/vid/5ba53b584947a/5cad2dd3ee706/vidthumb.mp4'
[download] Destination: Lunaxjames - Fucking My Asian Sex Doll - Manyvids #asian #bubblebutt #pale #roleplay #pigtails on SexyPorn (11)-5cad9f8a26d51-11.mp4
[download] 100% of 272.29KiB in 00:00
[download] Downloading video 12 of 12
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://s18.trafficdeposit.com//blog/vid/899334366634979328/5cad288db659a/vidthumb.mp4'
[download] Destination: Lunaxjames - Fucking My Asian Sex Doll - Manyvids #asian #bubblebutt #pale #roleplay #pigtails on SexyPorn (12)-5cad9f8a26d51-12.mp4
[download] 100% of 279.43KiB in 00:00
[download] Finished downloading playlist: Lunaxjames - Fucking My Asian Sex Doll - Manyvids #asian #bubblebutt #pale #roleplay #pigtails on SexyPorn

**Comment by JChris246** [comment]
#20646 closes this issue
