### ISSUE TITLE
Forbidden youtube url with -g 

### ISSUE THREAD

**Issue by guanzhiyou** [ytdl-org/youtube-dl#20626]
I have an VM on GCP, and when I use `youtube-dl -g https://m.youtube.com/watch?v=m2bM-r-2KYs` to get a link , it will return a link like this `https://r1---sn-5ualdn7r.googlevideo.com/videoplayback?requiressl=yes&mime=video%2Fmp4&ratebypass=yes&mm=31%2C29&txp=5532432&mn=sn-5ualdn7r%2Csn-5uaeznr6&ms=au%2Crdu&mt=1554879688&mv=m&dur=2955.110&key=yt6&expire=1554901337&source=youtube&pl=23&beids=9466585&ip=34.73.6.135&ipbits=0&sparams=dur%2Cei%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&signature=436DDCE5D99C5D4C0DD8B9F3788CAF0DCA1B787E.4FE971DF537005625837C99735503389F2556106&ei=-JStXLimNIW48wTwq7uYBw&id=o-AKz8MUVRglXIPoXR9Bl6a_8-f1wl0BiHpuXRW84Xh-QL&gcr=us&itag=22&fvip=1&c=WEB&lmt=1550360964452306&title=🔴 Subway Surfers World Tour 2018 - Chicago Gameplay Livestream`. 
This link has a param named **gcr** , I can not use this link to download video because ' gcr=us ' and I am in Thailand.  When I excute the command in the local, it works ,because ' gcr=th '.  
I searched it on Google  but could not find anything related to this. Is there anything you can do about it?

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser
