### ISSUE TITLE
04/10/2019, Version 2019.04.07: Unableto extract course id (DO NOT CLOSE!)

### ISSUE THREAD

**Issue by isaaci** [ytdl-org/youtube-dl#20633]
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [ ]X [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### OUTPUT:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.udemy.com/aws-certified-solutions-architect-associate', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version **2019.04.07**
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-86755-g0780ad9
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in
[udemy:course] aws-certified-solutions-architect-associate: Downloading webpage
[udemy:course] 362328: Downloading course curriculum
[download] Downloading playlist: 362328
[udemy:course] playlist 362328: Collected 211 video ids (downloading 211 of them)
[download] Downloading video 1 of 211
[udemy] Downloading login popup
[udemy] 13885822: Downloading webpage
**### ERROR: Unable to extract course id;** please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\extractor\udemy.py", line 216, in _real_extract
  **### File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\extractor\udemy.py", line 79, in _extract_course_info**
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\extractor\common.py", line 1004, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by isaaci** [comment]
I do not understand...why these issues get closed without an answer?

**Comment by remitamine** [comment]
read the label.

**Comment by isaaci** [comment]
I did. It say duplicate. Where is the answer??

**Comment by remitamine** [comment]
duplicate -> already reported -> look for the status of the issue that is already opened.
it's not too difficult to find the issue that has been already opened(the first issue when you search for `Udemy` or `Unable to extract course id`).

**Comment by isaaci** [comment]
Understood. The one that is open is #20491 but is labeled as 'Cannot reproduce', which means, for someone else it is working but not for many others. I want to know how is it working for the one who cannot reproduce the same error??

**Comment by remitamine** [comment]
the server might respond differently for different users/IPs.

**Comment by isaaci** [comment]
How is that possible? I am developer myself, mostly C# and slightly python. If the format of the course id is known then the code has to work for everyone. Users or IPs are not even in the picture. Honestly, I don't have time otherwise I would have look at the code myself.

**Comment by remitamine** [comment]
have you ever worked on this project or in a similar project, the server can obviously modify the request depending on the source for several reasons:
- IPs(ex: geo-restriction).
- Auth(ex: premium content, mature content).
- User-Agent(ex: blocking certain user-agents, serving a different page for mobile users).
- the number of requests made by an IP(ex: serve a captcha page).
- serving a beta version of a website to a subset of users.
...

**Comment by isaaci** [comment]
I have not worked on this project at all but similar, yes. In each situation, once the response is received, if the format is known, it shouldn't matter from what IP or geographic location you are hitting the server. Course id is course id. Just glancing at the python snippet, it seems regex could be the issue. Again, I have not looked deep into this, yet. That's my guess based on other comments I have read.

**Comment by remitamine** [comment]
I didn't say that the course changes after the response is received I'm saying that the response(the structure of the webpage, it possible that PerimeterX Bot Defender page is being served) you receive may differ from what others get.
