### ISSUE TITLE
youtube-dl skips downloading more than one format when using download-archive

### ISSUE THREAD

**Issue by adsad213** [ytdl-org/youtube-dl#20645]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.07*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-i', '-o', 'yt/%(uploader)s/%(title)s-%(id)s.%(ext)s', '-v', '-a', 'ytc.txt', '--download-archive', 'youtube-dl-archive.txt', '-f', 'bestvideo,bestaudio', '--write-sub', '--all-subs', '-R', '500', '--write-description', '--write-info-json', '--write-annotations']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.7.3 (CPython) - Linux-5.0.7-arch
[debug] exe versions: ffmpeg 4.1.2, ffprobe 4.1.2
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

My configuration, as shown in the flags, has -f bestvideo,bestaudio , thus downloading a .mp4 and .webm (each for video and audio) to avoid merging with ffmpeg, since my goal is to download both separately (I know bestvideo+bestaudio merges them, but I want them separate). Doing this standalone works fine and downloads both, the problem arises when I add --download-archive youtube-dl-archive.txt , since it checks if it downloaded, and when it finished downloading the VIDEO, when it downloads the audio, the url is already present in the archive.txt, thus it skips downloading the audio. The issue is that a video should only be added to the archive.txt, when both the video and audio are downloaded, not skipping a format ([info] videoID: downloading video in 2 formats), it only downloads one format, since when it finishes downloading ONE format, it is added to the archive, and when it downloads the next format, since the ID is present in the archive, it skips the next format.
example, downloading one video, downloads only the .mp4 and skips the .webm or audio part, and so on, with -f bestvideo,bestaudio

**Comment by adsad213** [comment]
@dstftw dupe?

**Comment by adsad213** [comment]
Could you at least tell me where the duplicate is, or the solution for this? @dstftw

**Comment by chicacvr** [comment]
I'm seeing the same bug.
