### ISSUE TITLE
can not get working best url

### ISSUE THREAD

**Issue by Celsyum** [ytdl-org/youtube-dl#20642]
`youtube-dl --version` 2019.04.07

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
case 1:

fails to get working url from https://www.youtube.com/watch?v=4ic7RNS4Dfo

cmd: youtube-dl -v -g -f best https://www.youtube.com/watch?v=4ic7RNS4Dfo
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-g', u'-f', u'best', u'https://www.youtube.com/watch?v=4ic7RNS4Dfo']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 2.7.9 (CPython) - Linux-3.16.0-4-amd64-x86_64-with-debian-8.11
[debug] exe versions: avconv 3.2.10-1, ffmpeg 3.2.10-1, ffprobe 3.2.10-1
[debug] Proxy map: {}
https://r1---sn-vgqsknez.googlevideo.com/videoplayback?fvip=1&lmt=1547463256349260&dur=118.561&source=youtube&expire=1555017593&ratebypass=yes&mime=video%2Fmp4&itag=22&sparams=dur%2Cei%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&txp=5532432&key=yt6&mn=sn-vgqsknez%2Csn-tt1eln7l&mm=31%2C26&mt=1554995433&id=o-ANt5MYlQo7OF_ADNXXinq7e0cQaYVO0CK2jUoLpxa7jC&ip=2001%3A4801%3A7824%3A104%3Abe76%3A4eff%3Afe10%3A89b3&pl=32&mv=u&c=WEB&ipbits=0&ms=au%2Conr&requiressl=yes&ei=GVuvXIrhEMKdD5z2rcgC&signature=254C898F234BDBEEDB7DB8B32FC429DF594CED39.800D036C388B7CA79340B0F37875CFBAFF26332A

```

case 2

fails to get url at all from https://www.youtube.com/watch?v=xba-yF6MwC0

cmd: youtube-dl -v -g -f best https://www.youtube.com/watch?v=xba-yF6MwC0
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-g', u'-f', u'best', u'https://youtu.be/xba-yF6MwC0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 2.7.9 (CPython) - Linux-3.16.0-4-amd64-x86_64-with-debian-8.11
[debug] exe versions: avconv 3.2.10-1, ffmpeg 3.2.10-1, ffprobe 3.2.10-1
[debug] Proxy map: {}
ERROR: This video is not available.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1982, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is not available.

```

**Comment by dstftw** [comment]
The error is self explanatory.

**Comment by Celsyum** [comment]
how this error can be self explanatory ? 
case 1: video url is not valid , command everytime return not working url
case 2: error: "video is not available" , but you can still watch video on youtube, how video can not be available?

**Comment by dstftw** [comment]
1. https://github.com/ytdl-org/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser
2. So what? Can you watch it from the same machine and same network interface?

**Comment by Celsyum** [comment]
thanks for pointing out causes.
