### ISSUE TITLE
TikTok Extractor Without Watermark

### ISSUE THREAD

**Issue by Zipdox** [ytdl-org/youtube-dl#20644]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Since TikTok changed the layout the extractor returns a video with a watermark. I found a solution involving a JavaScript variable.
The easiest way to get the video URL without watermark is this code:
`window.__INIT_PROPS__["/share/video/:id"]["videoData"]["itemInfos"]["video"]["urls"][2].replace("watermark=1", "watermark=0");`
If you can't use JavaScript, `window.__INIT_PROPS__` is declared in `<script>` in the head.

**Comment by reallyuniquename** [comment]
Does it still work? 

I don't see watermark param in the video url, adding it manually doesn't help either.

Yet there are online tools that rip videos without watermark. How do they do it?

**Comment by yt-dddd775500** [comment]
I can't figure out how to get the JavaScript to work either.

However, apps such as TikMate are still able to download videos without the watermark.

Anyone know how they're doing it?

**Comment by reallyuniquename** [comment]
I don't think that javascript trick works anymore. 

TikTok extractor in `youtube-dl` is very basic, you can see `WARNING: Falling back on generic information extractor.` in its log. It just grabs `src` attribute of `video` tag.

I believe services that can download videos without watermark abuse internal TikTok API for mobile apps. See https://github.com/szdc/tiktok-api/issues/73 and https://github.com/Pinanchen/TikTok-Free for general idea.

**Comment by reallyuniquename** [comment]
New mechanism for tiktok without watermark #24563

**Comment by Zipdox** [comment]
I found a new solution.
Userscript here: https://github.com/Zipdox/tiktok-download-userscript/blob/23ba50ec065a82dbe48e4989567f6808fa3207bd/tiktok-dl.user.js#L28
Breakdown of workings here: https://github.com/ytdl-org/youtube-dl/issues/24563

**Comment by runraid** [comment]
I got this working with youtube-dl using the above Javascript as an example.

I created a pull request here - https://github.com/ytdl-org/youtube-dl/pull/25895

**Comment by Zipdox** [comment]
This method is broken now.
