### ISSUE TITLE
YouTube-DL: Prepend '-- ' option.., work, NOT as expected.

### ISSUE THREAD

**Issue by RangaSE** [ytdl-org/youtube-dl#20649]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.07*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.04.07
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.
=>
We saw this in YouTube-DL README.md file:
Either prepend  https://www.youtube.com/watch?v=  or separate the ID from the options with  -- :
youtube-dl -- -wNyEUrxzFU 
youtube-dl "https://www.youtube.com/watch?v=-wNyEUrxzFU" 
... I tried the same with multiple (individual) video files, but, it didn't work as expected; only the last video in the Comand line worked satisfactorily. These are the latest log for your information:

Microsoft Windows [Version 10.0.17763.379]
(c) 2018 Microsoft Corporation. All rights reserved.

< 11-04-2019 & 21:55:09.25 | C:\Users\admin> youtube-dl[2019.04.07] -ci --no-playlist --embed-thumbnail -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -o "D:\Downloads\%(title)s(u%(upload_date)s; %(duration)s; %(height)sp)YT '%(uploader)s'.%(ext)s" -- V1mtDir12Ts
[youtube] V1mtDir12Ts: Downloading webpage
[youtube] V1mtDir12Ts: Downloading video info webpage
[youtube] Downloading just video V1mtDir12Ts because of --no-playlist
[youtube] V1mtDir12Ts: Downloading thumbnail ...
[youtube] V1mtDir12Ts: Writing thumbnail to: D:\Downloads\Uttarakhand Tourism _ Xplore India _ #Uttarakhand _ Travelxp India Tourism_ _India Tourism Place(u20181031; 34; 720p)YT 'TravelXp HD'.jpg
[download] D:\Downloads\Uttarakhand Tourism _ Xplore India _ #Uttarakhand _ Travelxp India Tourism_ _India Tourism Place(u20181031; 34; 720p)YT 'TravelXp HD'.mp4 has already been downloaded and merged
[atomicparsley] Adding thumbnail to "D:\Downloads\Uttarakhand Tourism _ Xplore India _ #Uttarakhand _ Travelxp India Tourism_ _India Tourism Place(u20181031; 34; 720p)YT 'TravelXp HD'.mp4"

< 11-04-2019 & 21:55:28.32 | C:\Users\admin> youtube-dl[2019.04.07] -ci --no-playlist --embed-thumbnail -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -o "D:\Downloads\%(title)s(u%(upload_date)s; %(duration)s; %(height)sp)YT '%(uploader)s'.%(ext)s" -- N_sZbS4Ei6s -- wN_ArXr8AzM
[youtube] N_sZbS4Ei6s: Downloading webpage
[youtube] N_sZbS4Ei6s: Downloading video info webpage
[youtube] Downloading just video N_sZbS4Ei6s because of --no-playlist
[youtube] N_sZbS4Ei6s: Downloading thumbnail ...
[youtube] N_sZbS4Ei6s: Writing thumbnail to: D:\Downloads\Indian Railways' New 'Luxury' Chair Cars With Aircraft-Like Features(u20170109; 394; 1080p)YT 'The Financial Express'.jpg
[download] D:\Downloads\Indian Railways' New 'Luxury' Chair Cars With Aircraft-Like Features(u20170109; 394; 1080p)YT 'The Financial Express'.mp4 has already been downloaded and merged
[atomicparsley] Adding thumbnail to "D:\Downloads\Indian Railways' New 'Luxury' Chair Cars With Aircraft-Like Features(u20170109; 394; 1080p)YT 'The Financial Express'.mp4"
ERROR: '--' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:--" ) to search YouTube
[youtube] wN_ArXr8AzM: Downloading webpage
[youtube] wN_ArXr8AzM: Downloading video info webpage
[youtube] Downloading just video wN_ArXr8AzM because of --no-playlist
[youtube] wN_ArXr8AzM: Downloading thumbnail ...
[youtube] wN_ArXr8AzM: Writing thumbnail to: D:\Downloads\UDAY EXPRESS  - India's First Business Class DOUBLE DECKER Express Train _ FIRST Departure(u20180406; 230; 1080p)YT 'TheTrainGuy'.jpg
[download] Resuming download at byte 18826942
[download] Destination: D:\Downloads\UDAY EXPRESS  - India's First Business Class DOUBLE DECKER Express Train _ FIRST Departure(u20180406; 230; 1080p)YT 'TheTrainGuy'.f137.mp4
[download] 100% of 94.10MiB in 05:23
[download] Destination: D:\Downloads\UDAY EXPRESS  - India's First Business Class DOUBLE DECKER Express Train _ FIRST Departure(u20180406; 230; 1080p)YT 'TheTrainGuy'.f140.m4a
[download] 100% of 3.55MiB in 00:14
[ffmpeg] Merging formats into "D:\Downloads\UDAY EXPRESS  - India's First Business Class DOUBLE DECKER Express Train _ FIRST Departure(u20180406; 230; 1080p)YT 'TheTrainGuy'.mp4"
Deleting original file D:\Downloads\UDAY EXPRESS  - India's First Business Class DOUBLE DECKER Express Train _ FIRST Departure(u20180406; 230; 1080p)YT 'TheTrainGuy'.f137.mp4 (pass -k to keep)
Deleting original file D:\Downloads\UDAY EXPRESS  - India's First Business Class DOUBLE DECKER Express Train _ FIRST Departure(u20180406; 230; 1080p)YT 'TheTrainGuy'.f140.m4a (pass -k to keep)
[atomicparsley] Adding thumbnail to "D:\Downloads\UDAY EXPRESS  - India's First Business Class DOUBLE DECKER Express Train _ FIRST Departure(u20180406; 230; 1080p)YT 'TheTrainGuy'.mp4"

< 11-04-2019 & 22:04:34.61 | C:\Users\admin> Exit
Is it a Bug? I don't know. Please, do the needful, if necessary.
ATB! Regards,

**Comment by dstftw** [comment]
`--` is a delimiter indicating the end of options. It must only be used once.

**Comment by RangaSE** [comment]
Many Tanks Mr. Sergey M!
I can not see any delimiters in README.md, the Help file. Can you shed light on the 'delimiter' indicating the end of Options, Please.
Also, in the latest help file, we saw some new options as 'video-get'. I think it goes beyond my level of understanding; can I expect some more explaining of the same?
ATB! Regards,

**Comment by RangaSE** [comment]
OOPS! Please read the first line as 'Many Thanks Mr. Sergey M!' (my kbd problem.)
