### ISSUE TITLE
[safarionlinebooks] ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by kutkin54** [ytdl-org/youtube-dl#20640]
## Please follow the guide below
Dear youtube-dl programmers,
I am using the youtube-dl 2019.04.07 version to download a video from learning.oreilly.com, and have obtained the problem of'ERROR: Unable to download JSON metadata: HTTP Error 403' as shown in the picture below. So, I cannot download the video at all. Please assist me to solve this problem. 

![safari_error](https://user-images.githubusercontent.com/25189239/55943870-a2914500-5c71-11e9-83bb-16fed097c0ad.png)

**Comment by kutkin54** [comment]
Sorry, I do not understand how to proceed to try out the fix. Can the solution like changing of the Python codes be found in the Duplicate section? Please reply.

**Comment by remitamine** [comment]
look at the issue that is already opened.
