### ISSUE TITLE
FUNimation no longer working

### ISSUE THREAD

**Issue by oobedoob** [ytdl-org/youtube-dl#20665]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.07*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.funimation.com/shows/seven-mortal-sins/the-proud-fallen-angel/uncut/?lang=english']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[Funimation] the-proud-fallen-angel: Downloading webpage
WARNING: [Funimation] the-proud-fallen-angel: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\extractor\funimation.py", line 100, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\extractor\common.py", line 1134, in _html_search_meta
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\extractor\common.py", line 1013, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\extractor\common.py", line 1004, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Looks like FUNimation may have updated their site within the last week or so as everything was working fine and now I'm not able to download any videos from their site now. Hopefully I've filled out everything you need.

**Comment by axipher** [comment]
Also having the same issue

**Comment by SwimmingLink** [comment]
On that video, I get
"This video contains mature content.
To continue, log in or create an account."
However, testing on a TV-14 show (which doesn't require a login), I still can't use youtube-dl. I was able to find (without youtube-dl) a playlist per audio language (each containing playlists for resolutions), but can't find subtitles at all… :\

**Comment by darkhelmet2016** [comment]
Looks like the authorization has changed.
$.ajax({
--
  | contentType: 'application/json',
  | data: data,
  | dataType: 'json',
  | headers: {'Authorization': 'Token ' + token},

**Comment by darkhelmet2016** [comment]
The header data and play list data for resolution possibly has also changed.

360p
540p
720p
810p
1080p

**Comment by SwimmingLink** [comment]
Building a new cookie file, I was able to see the A/V streams again with youtube-dl. The cookie file seems to expire really fast though and you'll need to keep creating new ones (no idea on accurate pinpoint timing), but I still can't use it to get subtitles, so you'll still have to get those another way (monitor your traffic for a vtt file. not sure if different videos have different formatted subs, so might want to keep your eyes open for "ass", "srt", etc., but the first episode of Haruhi Suzumiya was labled 052e1285-0337-403f-a898-59e34409aad1.vtt hosted on cloudfront.net)

**Comment by darkhelmet2016** [comment]
They have 3 subtle formats. srt, .dfxp, and .vtt. You could probably have it try to download all subtitle formats and covert to another format if possible for muxig if needed. --all-subs --sub-lang en --write-sub --convert-subs to the format you want. Might or might not work but what have been using on sites like Crunchy.

**Comment by SwimmingLink** [comment]
--all-subs doesn't find anything on funimation. I haven't needed to convert yet, what I grab raw has been compatible. I'm unfamiliar with .dfxp though...

**Comment by darkhelmet2016** [comment]
Then it may not know hot to extract them properly for the funimation downloader. https://en.wikipedia.org/wiki/Timed_Text_Markup_Language It is a format that believe is used by Netflix. You don't have to monitor the traffic, you can find it in the video info of a file in chrome. Look for the file you want and have it open it and save it as what you want. These files are from The Melancholy of Haruhi Suzumiya Episode 1 Japanese sub.

https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1508682/Japanese/1508682_Japanese_5ade2278-f15c-e711-8175-020165574d09.vtt

https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1508682/Japanese/1508682_Japanese_5ede2278-f15c-e711-8175-020165574d09.srt

https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1508682/Japanese/1508682_Japanese_5dde2278-f15c-e711-8175-020165574d09.dfxp

**Comment by SwimmingLink** [comment]
How does one view said video info in Chrome? It sounds like this may make things a lot easier than what I've been doing...

**Comment by darkhelmet2016** [comment]
The English dub has closed caption subs and the Japanese dub has subs subs for the Japanese translation. In chrome when playing a video when you right click on the video chose view frame source and it is easier than trying to look at all the streaming info than using dev tools and just do a search for subtitle using ctrl+f English is for the Dub and Japanese is for the sub when looking for the subtitle links.

**Comment by SwimmingLink** [comment]
I don't get a "view frame source" in my right-click menu :\ My two right-click menus on the video in Chrome look like this:
![image](https://user-images.githubusercontent.com/34524859/58683921-edf3d580-833b-11e9-9be1-df80f82fb2b2.png) ![image](https://user-images.githubusercontent.com/34524859/58683946-0b28a400-833c-11e9-8ad1-7e20a9ebdd55.png)
Or is "Inspect" the same thing?

**Comment by darkhelmet2016** [comment]
Are you on windows?

**Comment by darkhelmet2016** [comment]
view-source:https://www.funimation.com/player/148980/?bdub=0&lang=english&qid=undefined is for The Melancholy of Haruhi Suzumiya Episode 1 English dub. It would have to be in this format but would have to make sure you have the view-source in front of it.

**Comment by SwimmingLink** [comment]
Oh, yes, I'm on Windows. Sorry, I keep forgetting that this is more of a Linux thing. Thank you though! This totally works and is much better than what I've been doing!

**Comment by SwimmingLink** [comment]
I'm still failing to find URLs for the files with Japanese audio though... :\ I'm only seeing stuff for English.

**Comment by SwimmingLink** [comment]
Anyone use the USERNAME & PASSWORD commands rather than cookies? If that works better, I should probably do that rather than constantly re-generating my cookie file to use...

**Comment by Fordi** [comment]
Here's my failed output:

    $ youtube-dl 'https://www.funimation.com/shows/robihachi/traveling-companions-journey-to-the-star/?qid=5246c8f3bc7cf55c' --verbose --username '[redacted]' --password '[redacted]'
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: [u'https://www.funimation.com/shows/robihachi/traveling-companions-journey-to-the-star/?qid=5246c8f3bc7cf55c', u'--verbose', u'--username', u'PRIVATE', u'--password', u'PRIVATE']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2019.06.27
    [debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-54-generic-x86_64-with-LinuxMint-19-tara
    [debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
    [debug] Proxy map: {}
    [Funimation] Logging in
    [Funimation] traveling-companions-journey-to-the-star: Downloading webpage
    WARNING: [Funimation] traveling-companions-journey-to-the-star: Failed to parse JSON No JSON object could be decoded
    ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
        ie_result = ie.extract(url)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
        ie_result = self._real_extract(url)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/funimation.py", line 100, in _real_extract
        ], webpage, fatal=True)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1135, in _html_search_meta
        html, display_name, fatal=fatal, group='content', **kwargs)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
        res = self._search_regex(pattern, string, name, default, fatal, flags, group)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
        raise RegexNotFoundError('Unable to extract %s' % _name)
    RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by cdmatter** [comment]
I am seeing the same issue on the latest version of youtube-dl (2019.07.14).  Here is my failed output.d

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'-v', u'https://www.funimation.com/shows/how-not-to-summon-a-demon-lord/battle-for-legitimacy/?qid=d07c7809e5d65ce9', u'--username', u'PRIVATE', u'--password', u'PRIVATE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.14
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-54-generic-x86_64-with-elementary-5.0-juno
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[Funimation] Logging in
[Funimation] battle-for-legitimacy: Downloading webpage
WARNING: [Funimation] battle-for-legitimacy: Failed to parse JSON No JSON object could be decoded
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/funimation.py", line 100, in _real_extract
    ], webpage, fatal=True)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1135, in _html_search_meta
    html, display_name, fatal=fatal, group='content', **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
