### ISSUE TITLE
Bug when downloading

### ISSUE THREAD

**Issue by vikashinchennai** [ytdl-org/youtube-dl#20672]
root@developer:~/upload# youtube-dl \
>   --username 'asdasdasdsad' \
>   --password 'xxxxxxx' \
>   --default-search auto \
>   https://app.pluralsight.com/library/courses/html-css-javascript-big-picture/table-of-contents \
>   -o "/root/upload/%(playlist)s/%(chapter_number)s. %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s" \
>   --sleep-interval 10
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[pluralsight:course] html-css-javascript-big-picture: Downloading JSON metadata
[pluralsight:course] html-css-javascript-big-picture: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
root@kgetechnologies:~/upload#

**Comment by vikashinchennai** [comment]
what is incomplete, please explain mre

**Comment by remitamine** [comment]
you didn't fill the issue template.
