### ISSUE TITLE
source-address not working as expected?

### ISSUE THREAD

**Issue by Elite** [ytdl-org/youtube-dl#20670]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.07*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Since youtube was rate limiting my server ip, I got new ip allocated from my web host and added it to `eth0` using `ip addr add xx.xx.xx.YYY/24 dev eth0`, I can see both the ip's when using ` ip addr` command.

`    inet xx.xxx.xxx.xxx/24 brd xx.xxx.xxx.xxx scope global eth0
       valid_lft forever preferred_lft forever
    inet xx.xxx.xxx.YYY/24 scope global secondary eth0
       valid_lft forever preferred_lft forever
`

To make use of the new ip address, I used `'source-address':source_ip,` in my python script but the resulting url from youtube still has my older IP address. 

What am I missing here?

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L264

**Comment by Elite** [comment]
The syntax seems fine, can you pls tell what am I missing here?

**Comment by remitamine** [comment]
it's `source_address` not `source-address`

**Comment by Elite** [comment]
Pls. fix the front page options, I copy pasted from there.

![sshot-1](https://user-images.githubusercontent.com/5461439/56128382-164a8f00-5f9d-11e9-9aca-41ad129dbfa3.png)

**Comment by dstftw** [comment]
These are command line options not python API options.

**Comment by Elite** [comment]
OK, go it. 

However, I guess both some should be in harmony for ease of use and clear understanding.

**Comment by dstftw** [comment]
That's technically impossible since not all options have the same meaning.
