### ISSUE TITLE
treehouse error

### ISSUE THREAD

**Issue by jaan143** [ytdl-org/youtube-dl#20677]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.07*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

### Description of your *issue*, suggested solution and other information

i am getting this error in every course please can you fix it @remitamine  bro account email i already sent you by email

PS C:\Users\HDNLRG> youtube-dl --verbose -o 'd:\contents\New folder/%(playlist)s/%(playlist_index)s - %(title)s.%(ex
t)s' https://teamtreehouse.com/library/continuous-integration-with-jenkins --username abc@123.com --p
assword 12345
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', 'd:\\contents\\New folder/%(playlist)s/%(playlist_index)s - %(title)s.%(e
xt)s', 'https://teamtreehouse.com/library/continuous-integration-with-jenkins', '--username', 'PRIVATE', '--password', '
PRIVATE']
[debug] Encodings: locale cp1255, fs mbcs, out cp862, pref cp1255
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.5.4 (CPython) - Windows-2012ServerR2-6.3.9600-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[TeamTreeHouse] Downloading signin page
[TeamTreeHouse] Logging in
[TeamTreeHouse] continuous-integration-with-jenkins: Downloading webpage
[TeamTreeHouse] continuous-integration-with-jenkins: Downloading stages page
[download] Downloading playlist: Continuous Integration with Jenkins
[TeamTreeHouse] playlist Continuous Integration with Jenkins: Collected 21 video ids (downloading 21 of them)
[download] Downloading video 1 of 21
[TeamTreeHouse] introduction-82: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://videos.teamtreehouse.com/videos/DevTools-Continuous-Integration-with-Jenkins-S1-
V1-720p.mp4?token=5cb6f95c_492ba21b189180661d8deec17d2c8ae3df8aa81a'
[download] Destination: d:\contents\New folder\Continuous Integration with Jenkins\01 - Introduction.mp4
[download] 100% of 3.98MiB in 00:00
[download] Downloading video 2 of 21
[TeamTreeHouse] continuous-integration-with-jenkins: Downloading webpage
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the
latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.
ERROR: Unable to extract stages path; please report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and in
clude its complete output.
Traceback (most recent call last):
  File "c:\program files\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\program files\python35\lib\site-packages\youtube_dl\extractor\common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "c:\program files\python35\lib\site-packages\youtube_dl\extractor\teamtreehouse.py", line 128, in _real_extract
    webpage, 'stages path')
  File "c:\program files\python35\lib\site-packages\youtube_dl\extractor\common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract stages path; please report this issue on https://yt-dl.org/bug .
Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl
with the --verbose flag and include its complete output.

PS C:\Users\HDNLRG>

**Comment by remitamine** [comment]
```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
```
youtube-dl can't determine wheather the page contain a video or not untill it start the extraction, and to be honest the extractor is not much used as lots of courses contain more text lessons and quizes than videos.

**Comment by jaan143** [comment]
@remitamine  its giving error in all rest videos only first video is downloading in all courses

**Comment by remitamine** [comment]
yes, because the course contains only one video.
