### ISSUE TITLE
--get-title return the description of the video with Facebook

### ISSUE THREAD

**Issue by TaktakTaktouk** [ytdl-org/youtube-dl#20687]
- After the new updates of Facebook --get-title return the description of the video but not the title:

youtube-dl --get-title 'https://www.facebook.com/KeepVideo1/videos/268885554046939' -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--get-title', u'https://www.facebook.com/KeepVideo1/videos/268885554046939', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 2.7.9 (CPython) - Linux-2.6.32-042stab133.2-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
The eventful life of a little blue car.

- And --get-description return nothing:

youtube-dl --get-description 'https://www.facebook.com/KeepVideo1/videos/268885554046939' -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--get-description', u'https://www.facebook.com/KeepVideo1/videos/268885554046939', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 2.7.9 (CPython) - Linux-2.6.32-042stab133.2-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best

Can you fix this, please?

**Comment by dstftw** [comment]
This is [expected behavior](https://github.com/ytdl-org/youtube-dl/blob/e6c9ae31df1196dc12607b83be01141eb52b80b6/youtube_dl/extractor/facebook.py#L419).

**Comment by TaktakTaktouk** [comment]
@dstftw The video has a title and a description and I tested this with many Facebook videos and always the same issue. YouTube-dl is no longer able to extract title and description from Facebook. 
Please reopen this issue
