### ISSUE TITLE
Download only playlists created by user

### ISSUE THREAD

**Issue by kik4444** [ytdl-org/youtube-dl#20685]
If I provide the link https://www.youtube.com/user/USERNAME/playlists to youtube-dl, how can I filter only specific playlists to be downloaded, e.g. only playlists from the "Created Playlists" category, ignoring playlists such as "Liked videos", without directly giving it the link to every single playlist?

**Comment by remitamine** [comment]
use the playlist group URL(contains `shelf_id=`).

**Comment by kik4444** [comment]
Though when I try `playlists?shelf_id=0&view=1` or just `playlists?shelf_id=0` or the entire `playlists?view=1&sort=dd&shelf_id=0`, it always either downloads everything regardless of my selection, including the liked videos, or it downloads only the first 4 latest playlists, ignoring the rest.

**Comment by remitamine** [comment]
works fine for me, if it doesn't work for you then post the URLs you're trying to download(make sure you're using the latest version).

**Comment by kik4444** [comment]
Currently I'm testing it with (https://www.youtube.com/user/NicoB7700/playlists?view=1&sort=dd&shelf_id=0). I noticed that you get different links when selecting Created Playlists from the dropdown menu than from the Created Playlists button in the playlists tab. Namely pressing the button filters out Liked Videos whereas the dropdown menu link does not, but using the former in youtube-dl still includes the liked videos

**Comment by remitamine** [comment]
actually, the import parameter is `view`.
judging by the number of the extracted playlists it matches the number of playlists that appear on browser.
```
youtube-dl -J --flat-playlist 'https://www.youtube.com/user/NicoB7700/playlists?view=1&flow=grid' | jq '.entries | length'
150
```
```
youtube-dl -J --flat-playlist 'https://www.youtube.com/user/NicoB7700/playlists?view=52&flow=grid' | jq '.entries | length'
2
```

**Comment by kik4444** [comment]
The command `youtube-dl -J --flat-playlist 'https://www.youtube.com/user/NicoB7700/playlists?view=1&flow=grid'` seems to return all the playlist URLs, including ones for `liked videos` that I want to filter out
