### ISSUE TITLE
[Openload] hotlinking detect

### ISSUE THREAD

**Issue by bato3** [ytdl-org/youtube-dl#20688]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.07*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
eg first test URL
```youtube-dl https://openload.co/f/kUEfGclsU9o
[Openload] kUEfGclsU9o: Downloading embed webpage
[Openload] kUEfGclsU9o: Executing JS on webpage
[download] Destination: skyrim_no-audio_1080.mp4-kUEfGclsU9o.mp4
[download] 100% of 31.86MiB in 00:05
```
(see download size), and in content are nice pigeons 

![Screen](https://user-images.githubusercontent.com/11570/56224637-3303c700-6070-11e9-8eac-7cc7f1e87093.png)

**Comment by ealgase** [comment]
I can reproduce, however, using `curl $(youtube-dl -g <url>)` or `aria2c $(youtube-dl -g <url>)` works.  I'll continue investigating.

**Comment by ealgase** [comment]
It actually looks like the user agent header is the cause of the issue:

With user-agent header:

```
(bionic)ealgase@localhost:~/Downloads$ aria2c -c --min-split-size 1M --max-connection-per-server 4 --out skyrim_no-audio_1080.mp4-kUEfGclsU9o.mp4.part --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36'   -- 'https://openload.co/stream/kUEfGclsU9o~1555517883~108.171.0.0~T2khQ6uF?mime=true'

04/16 12:21:55 [NOTICE] Downloading 1 item(s)

04/16 12:21:56 [NOTICE] CUID#7 - Redirecting to https://1fiagea.oloadcdn.net/dl/l/tt9PMhaCCmfO9QFH/KDA_8nZ2av4/x.mp4?mime=true
[#927eb2 0B/0B CN:1 DL:0B]                                                                                                                                                                              
04/16 12:21:57 [NOTICE] CUID#9 - Redirecting to https://1fiagea.oloadcdn.net/dl/l/tt9PMhaCCmfO9QFH/KDA_8nZ2av4/x.mp4?mime=true

04/16 12:21:57 [NOTICE] CUID#11 - Redirecting to https://1fiagea.oloadcdn.net/dl/l/tt9PMhaCCmfO9QFH/KDA_8nZ2av4/x.mp4?mime=true

04/16 12:21:57 [NOTICE] CUID#10 - Redirecting to https://1fiagea.oloadcdn.net/dl/l/tt9PMhaCCmfO9QFH/KDA_8nZ2av4/x.mp4?mime=true
[#927eb2 31MiB/31MiB(99%) CN:1 DL:2.6MiB]                                                                                                                                                               
04/16 12:22:09 [NOTICE] Download complete: /home/ealgase/Downloads/skyrim_no-audio_1080.mp4-kUEfGclsU9o.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
927eb2|OK  |   2.6MiB/s|/home/ealgase/Downloads/skyrim_no-audio_1080.mp4-kUEfGclsU9o.mp4.part

Status Legend:
(OK):download completed.
```

Without user-agent header:

```
(bionic)ealgase@localhost:~/Downloads$ aria2c -c --min-split-size 1M --max-connection-per-server 4 --out skyrim_no-audio_1080.mp4-kUEfGclsU9o.mp4.part -- 'https://openload.co/stream/kUEfGclsU9o~1555517883~108.171.0.0~T2khQ6uF?mime=true'

04/16 12:21:05 [NOTICE] Downloading 1 item(s)

04/16 12:21:05 [NOTICE] CUID#7 - Redirecting to https://1fiag6j.oloadcdn.net/dl/l/WSBIZhBGEGfeAE8Y/kUEfGclsU9o/skyrim_no-audio_1080.mp4?mime=true
[#c5cfa1 0B/0B CN:1 DL:0B]                                                                                                                                                                              
04/16 12:21:07 [NOTICE] CUID#9 - Redirecting to https://1fiag6j.oloadcdn.net/dl/l/WSBIZhBGEGfeAE8Y/kUEfGclsU9o/skyrim_no-audio_1080.mp4?mime=true

04/16 12:21:07 [NOTICE] CUID#10 - Redirecting to https://1fiag6j.oloadcdn.net/dl/l/WSBIZhBGEGfeAE8Y/kUEfGclsU9o/skyrim_no-audio_1080.mp4?mime=true

04/16 12:21:07 [NOTICE] CUID#11 - Redirecting to https://1fiag6j.oloadcdn.net/dl/l/WSBIZhBGEGfeAE8Y/kUEfGclsU9o/skyrim_no-audio_1080.mp4?mime=true
[#c5cfa1 9.5MiB/9.7MiB(97%) CN:2 DL:749KiB]                                                                                                                                                             
04/16 12:21:20 [NOTICE] Download complete: /home/ealgase/Downloads/skyrim_no-audio_1080.mp4-kUEfGclsU9o.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
c5cfa1|OK  |   746KiB/s|/home/ealgase/Downloads/skyrim_no-audio_1080.mp4-kUEfGclsU9o.mp4.part

Status Legend:
(OK):download completed.
```

It seems they've hardcoded the header youtube-dl uses and returns the "no hotlinking" video for it, as any change in the header makes it so it returns the correct video.
