### ISSUE TITLE
Openload extract url without ip protection

### ISSUE THREAD

**Issue by Lollinos** [ytdl-org/youtube-dl#20686]
When you run youtube-dl https://openload.co/f/fOPVhhGiZk8/Shazam.2019.iTALiAN.MD.HDTS.XviD-iSTANCE.avi (this link is only an example...), it gives something like http://openload.co/stream/fOPVhhGiZk8~1555503934~<###.###.0.0~ilNAa4gA?mime=true .
This url is restricted only to the IP that make the request. If you try analyze the ajax requests, you can find this url https://oqt1on.oloadcdn.net/dl/l/RPc5KFN7THjMq1VO/?mime=true that is open to everyone without ip restriction.

Could be possibile to have this one via youtube-dl?

Thank you,
Loris

**Comment by dstftw** [comment]
Wrong. Final URL behind redirect URL is either doesn't work from another IP.
```
{"msg":"download ISP is different to request ISP. request: AS12389 download: AS36850","status":403}
```
