### ISSUE TITLE
[Support request] openloed.co

### ISSUE THREAD

**Issue by smed79** [ytdl-org/youtube-dl#20691]
**Purpose of the issue**

- [x] Site support request (request for adding support for a new site)

**example URLs**

- `https://openloed.co/embed/bs1NWj1dCag/`

**Description of the issue**

Support request of "openlo**e**d\.co" which is a mirror of "openlo**a**d\.co"

**Comment by ealgase** [comment]
FFS how many domains can they make?

**Comment by ealgase** [comment]
Also, now I'm curious: where did you find this domain?

**Comment by smed79** [comment]
> where did you find this domain?

I maintain "[Liste FR](https://easylist-downloads.adblockplus.org/liste_fr.txt)" and ABP users [report](https://help.eyeo.com/adblockplus/report-an-issue) me where the ads are not blocked, so sometimes i can be in advance for new used domains (e.g [easylist#3276](https://git.io/fjY6X)).

> how many domains can they make?

Sites that have copyright issues, frankly change their domains to have an alternative at hand when they lose control. The 2nd scenario, they use new domain to escape adblocker whenever ads are blocked on their site (e.g [abp-filters-anti-cv#111](https://git.io/fjYiU)).

**Comment by ealgase** [comment]
Ah, cool!

I'm curious where people find these domains in the first place, though, as I don't see Openload advertising them.

**Comment by smed79** [comment]
> where people find these domains in the first place

on "Movie Streaming Sites".

**Comment by smed79** [comment]
@ealgase @dstftw new domain : `https://oload.services/embed/bs1NWj1dCag/`


there is also `openload.cc` & `openload.fun` but seems to be a fake for me (not sure).

**Comment by ealgase** [comment]
openload.cc is run by the fake file hosters of the internet, also running anonfile.com and megaupload.nz.  openload.fun is a search engine for pirated content on openload.
