### ISSUE TITLE
Download pauses in the middle until user clicks [enter] key in command prompt

### ISSUE THREAD

**Issue by mugenishere** [ytdl-org/youtube-dl#20690]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.17*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.04.17
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```
PROBLEM + SOLUTION FOR EVERYONE!

PROBLEM = command prompt gets stuck in between the download. Then I have to hit enter to get it to work again. 

SOLUTION: Disable the quick-edit mode as described here: https://stackoverflow.com/questions/33883530/why-is-my-command-prompt-freezing-on-windows-10

Sure. It hangs somewhere in between. I don't remember the exact point. But it just waited there for an hour until I brought the focus to the command-prompt and then clicked [enter] key. Once I tapped it, it immediately continued. Here're the complete logs:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-o', 'C:/Mugen/videos/test.mp4', 'https://www.youtube.com/embed/qKP9ZujwUUQ', '-f', 'bestvideo[height<=480] + bestaudio/best[height<=480]']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.03.18
[debug] Python version 3.6.2 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg git-2017-12-29-0c78b6a, ffprobe git-2017-12-29-0c78b6a
[debug] Proxy map: {}
[youtube] qKP9ZujwUUQ: Downloading webpage
[youtube] qKP9ZujwUUQ: Downloading video info webpage
[youtube] qKP9ZujwUUQ: Downloading MPD manifest
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/sparams/as%2Cei%2Chfr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cplayback_host%2Crequiressl%2Csource%2Cexpire/mn/sn-ci5gup-cag6%2Csn-ci5gup-h55z/id/a8a3fd66e8f05144/expire/1555457897/source/youtube/mv/m/ms/au%2Crdu/ip/122.171.163.242/key/yt6/itag/0/ipbits/0/mt/1555436266/initcwndbps/692500/requiressl/yes/hfr/all/playback_host/r5---sn-ci5gup-cag6.googlevideo.com/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/ei/CRO2XJr1DKmB3LUPtKOL-Ak/fvip/5/mm/31%2C29/signature/C6D298024E9127DA7D540E7D71B85DD88D309ABF.9B04166760DACC6676B2360954AAA3D2E7965429/pl/20'
[dashsegments] Total fragments: 86
[download] Destination: C:/Mugen/videos/test.f135.mp4
[download]  79.1% of ~20.88MiB at  2.65MiB/s ETA 00:28

---

### Description of your *issue*, suggested solution and other information

I've got some automation going on in which I invoke youtube-dl by starting a command-prompt and pass it a bunch of parameters. 

* Param for the video/audio quality (because I don't want to download too big file sizes)
* Param for the destination location + file name

In the whole process, it keeps downloading the videos with various launches. However, every now and then it gets stuck in-between. It's more like it's gone to sleep mode. Once this happens then it can even be hours before it resumes again. I need to select the command prompt with my mouse and then hit an [enter] key.

***Another important observation: ***
I think that the command prompt goes into this "select" mode as described over here: https://stackoverflow.com/questions/33883530/why-is-my-command-prompt-freezing-on-windows-10

I'm currently trying out this solution. Will update this thread again if it reproduces. If it doesn't, then the correct solution for this issue is as described in the link. We need to disable quick-edit mode for cmd.

**Comment by dstftw** [comment]
Totally unrelated to youtube-dl as described by your link.

**Comment by mugenishere** [comment]
Yes. It is unrelated. But I'm pretty sure that someone else is going to come across this issue and I hope that this ticket serves as a placeholder to direct them to the right solution.

An update from my side. I tried out the solution in the link and it's working fine. youtube-dl (aka whatever application is running in cmd prompt) does not hang by itself anymore.
