### ISSUE TITLE
gfycat.com url changes

### ISSUE THREAD

**Issue by jamesxmcintosh** [ytdl-org/youtube-dl#20696]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

gfycat.com has added dashes to some urls [https://gfycat.com/acceptablehappygoluckyharborporpoise-baseball](https://gfycat.com/acceptablehappygoluckyharborporpoise-baseball) causing a HTTP Error. 
This could be fixed by excluding dashes in the url InfoExtractor.

**Comment by Hrxn** [comment]
Isn't this some kind of hint, or a tag, or a file name if you want?

Because the scheme for the ID still seems the same, i.e. it should work as before.
What happens if you remove that part behind the hyphen (and the hyphen)?
I'd guess it will still work just as before.
