### ISSUE TITLE
Issue with quotation marks in Output Template

### ISSUE THREAD

**Issue by Germs2004** [ytdl-org/youtube-dl#20702]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.17*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.17**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
ERROR OUTPUT
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--format', u'best', u'--no-progress', u'--output', u"'wwwroot/downloads/%(title)s_%(resolution)s.%(ext)s'", u'https://www.youtube.com/watch?v=C0DPdy98e4c']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-17-generic-x86_64-with-Ubuntu-18.10-cosmic
[debug] exe versions: none
[debug] Proxy map: {}

STANDARD OUTPUT
[youtube] C0DPdy98e4c: Downloading webpage
[youtube] C0DPdy98e4c: Downloading video info webpage
[debug] Invoking downloader on u'https://r2---sn-hp57yn7r.googlevideo.com/videoplayback?initcwndbps=1591250&pl=16&dur=17.600&source=youtube&ratebypass=yes&requiressl=yes&gir=yes&id=o-AFhRsMT_L_xXUezlCx8Zd5i1lb2RHUf7qac7d4_S0aMf&clen=552999&ip=47.195.20.236&ei=C-C3XJjgBq_Kj-8PsKyz-Ag&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&signature=D01F952BB591AB4585EDD88F3C7B1D2EE960CF21.DF138C77CD23E7694FACD6433FB776EEDDED4D8A&ms=au%2Crdu&mt=1555554227&mv=m&mm=31%2C29&mn=sn-hp57yn7r%2Csn-hp57kn7l&c=WEB&fvip=3&mime=video%2Fmp4&key=yt6&expire=1555575915&lmt=1407413068816851&ipbits=0&itag=18'
[download] Destination: 'wwwroot/downloads/TEST VIDEO_480x360.mp4'
[download] Download completed
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=C0DPdy98e4c

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

When I run youtube-dl with single quotes around the Output Template, it actually creates a folder with a quote in the folder name.

For this example, I ran this command:
`
youtube-dl --verbose --format best --no-progress --output 'wwwroot/downloads/%(title)s_%(resolution)s.%(ext)s' https://www.youtube.com/watch?v=C0DPdy98e4c
`
and it created path and file like this (notice the two single quotes):
/var/www/mywebsite/'wwwroot/downloads/TEST VIDEO_480x360.mp4'
but I wanted it to create a file like this:
/var/www/mywebsite/wwwroot/downloads/TEST VIDEO_480x360.mp4

I am running this on ubuntu from a website created with C# and .Net Core.  The website runs youtube-dl using the .net feature "Process.Start()".  If I copy/paste the same command directly into my terminal, it works fine and creates the file without any extra quotes.  Even though it seems somehow related to .Net Core, I think youtube-dl should be smarter at parsing single and double quotes around the Output Template.  If you have any tips for fixing this another way, I'd be happy to try it.

Here's my .Net Core code:
```
        StringBuilder sbOutput = new StringBuilder();
        StringBuilder sbError = new StringBuilder();

        using (Process process = new Process())
        {
            ProcessStartInfo psi = new ProcessStartInfo();
            psi.FileName = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "youtube-dl.exe" : "youtube-dl";

            string QuoteMark = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "\"" : "'";
            psi.Arguments = String.Format("--verbose {0} {1} {2} {3}",
                "--format best",
                "--no-progress",
                "--output " + QuoteMark + "wwwroot/downloads/" + "%(title)s_%(resolution)s.%(ext)s" + QuoteMark,
                RequestedVideo);

            psi.CreateNoWindow = true;
            psi.UseShellExecute = false;
            psi.RedirectStandardError = true;
            psi.RedirectStandardOutput = true;
            process.StartInfo = psi;
            

            process.OutputDataReceived += new DataReceivedEventHandler((sender, e) =>
            {
                sbOutput.AppendLine(e.Data);
            });
            process.ErrorDataReceived += new DataReceivedEventHandler((sender, e) =>
            {
                sbError.AppendLine(e.Data);
            });

            sbOutput.AppendLine("Starting with this command:");
            sbOutput.AppendLine(psi.FileName + ' ' + psi.Arguments);
            sbOutput.AppendLine("------------------------------------");
            sbOutput.AppendLine();

            process.Start();

            // Asynchronously read the standard output of the spawned process. 
            // This raises OutputDataReceived events for each line of output.
            process.BeginOutputReadLine();
            process.BeginErrorReadLine();

            process.WaitForExit();
            process.Close();
        };
```

**Comment by dstftw** [comment]
Nothing to do with youtube-dl. Most likely .NET Core process API does not support single quotes.

**Comment by Germs2004** [comment]
In case anyone else has the same problem calling youtube-dl from a C# program, my only known workaround is to remove the quotes from around the arguments and just ensure that the arguments have no spaces.
