### ISSUE TITLE
Strange subtitle problem 

### ISSUE THREAD

**Issue by jackTaw88** [ytdl-org/youtube-dl#20708]
Hi,

my version: 2019.04.01

Youtube-dl downloads a subtitle which I can not find it from youtube.com video player's subtitle settings:

> youtube-dl -i --write-auto-sub --sub-lang "el,en,en-US,en-UK,en-GB" https://www.youtube.com/watch?v=RiM5a-vaNkg

But the downloaded "en" language is:

> How the worst moments in our lives make us who we are _ Andrew Solomon-RiM5a-vaNkg.en.vtt

start with:
```
WEBVTT
Kind: captions
Language: en

00:00:00.000 --> 00:00:07.000
 Translator: Riyad Almubarak Checker: Anwar Dafa-Alla 

00:00:12.749 --> 00:00:16.192
 As a teacher of difficulties 
```

But on youtube page can not find this words. How can this happening? I want the orjinal translations too :(

The persone on the video says something else... I check "auto-translate" from youtube too. But it is also different..

Thank you

**Comment by dstftw** [comment]
`--write-sub` not `--write-auto-sub`.
