### ISSUE TITLE
 MPD collection from Youtube playlist

### ISSUE THREAD

**Issue by 20183300** [ytdl-org/youtube-dl#20704]
Hi. I am collecting MPDs from YouTube playlists.

For example, 
youtube-dl -j PLc2E-LG3LmTRiIKM-jqJ7z8B_rwYz7cCD --ignore-errors  | jq '.formats[0].manifest_url' >> 1.csv

This command can be used to collect MPDs. Many playlists return null, or an error occurs due to copyright or copyright issues in *.csv file

Is there a way to get the ID of the video when I get the MPD URL at the same time ?

youtube-dl -j PLc2E-LG3LmTRiIKM-jqJ7z8B_rwYz7cCD --ignore-errors --get-id   | jq '.formats[0].manifest_url' >> 1.csv

This command will cause a pipe error.

**Comment by dstftw** [comment]
Parse both from JSON output.
