### ISSUE TITLE
Site Support Request: verystream.com

### ISSUE THREAD

**Issue by ealgase** [ytdl-org/youtube-dl#20701]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.17*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
(bionic)ealgase@localhost:~/Downloads$ youtube-dl -v https://verystream.com/stream/c1GWQ9ngBBx/Big_Buck_Bunny.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://verystream.com/stream/c1GWQ9ngBBx/Big_Buck_Bunny.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 3.7.2 (CPython) - Linux-3.14.0-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] Big_Buck_Bunny: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Big_Buck_Bunny: Downloading webpage
[generic] Big_Buck_Bunny: Extracting information
ERROR: Unsupported URL: https://verystream.com/stream/c1GWQ9ngBBx/Big_Buck_Bunny.mp4
Traceback (most recent call last):
  File "/home/ealgase/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/ealgase/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/home/ealgase/.local/lib/python3.7/site-packages/youtube_dl/extractor/generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://verystream.com/stream/c1GWQ9ngBBx/Big_Buck_Bunny.mp4
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://verystream.com/stream/c1GWQ9ngBBx/Big_Buck_Bunny.mp4
- Single video: https://verystream.com/e/c1GWQ9ngBBx/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

This is another child site of Openload, so code from the Streamango or Openload extractors may be useful.

**Comment by rryanq** [comment]
I believe that adding support for the example you provided would violate copyright laws.

**Comment by ealgase** [comment]
> I believe that adding support for the example you provided would violate copyright laws.

Why?  Big Buck Bunny is under a permissive license.

**Comment by rryanq** [comment]
Oh okay, my bad. Are you working on this yourself? I've been looking into it a bit.

**Comment by ealgase** [comment]
Nope, the Openload sites are too daunting for me to try.

**Comment by etmatrix** [comment]
I release a pull request  #20738 for that
