### ISSUE TITLE
Facebook no longer Supported?

### ISSUE THREAD

**Issue by TaktakTaktouk** [ytdl-org/youtube-dl#20711]
I am no longer able to download videos from Facebook. I tried with several videos of several pages and always the same error.

> youtube-dl https://www.facebook.com/RewindMyCartoons/videos/2261718780748237/ -v
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'https://www.facebook.com/RewindMyCartoons/videos/2261718780748237/', u'-v']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2019.04.17
> [debug] Python version 2.7.9 (CPython) - Linux-2.6.32-042stab133.2-x86_64-with-debian-8.11
> [debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1
> [debug] Proxy map: {}
> [facebook] 2261718780748237: Downloading webpage
> [facebook] 2261718780748237: Downloading webpage
> [facebook] 2261718780748237: Downloading webpage
> ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
>     ie_result = ie.extract(url)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
>     ie_result = self._real_extract(url)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 471, in _real_extract
>     video_id, fatal_if_no_video=True)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 380, in _extract_from_url
>     raise ExtractorError('Cannot parse data')
> ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> 
>

**Comment by EnthusiastAnon** [comment]
yeah same here

**Comment by kalemi19** [comment]
Same here even after updating to the latest version (2019.04.17)
