### ISSUE TITLE
Feature request: Resume all downloads in directory

### ISSUE THREAD

**Issue by Esokrates** [ytdl-org/youtube-dl#20714]
Imagine I start a couple of downloads and somehow I need to reboot before they are done. Now finding all download urls again and invoking youtube-dl is unnecessary work. 

Instead I propose the following: There should be a command-line argument like
youtube-dl --resume-all </path/to/dir> 
which would resume all partially downloaded files in the directory.
The download link should be stored in extended file attributes, if the file system does not support this, this feature is simply not supported, or you could store the link in an external file.

Even nicer would be if all the command-line args would be stored too that are invoked with downloading the specific file.

**Comment by dstftw** [comment]
```
-a, --batch-file FILE            File containing URLs to download ('-' for
                                 stdin), one URL per line. Lines starting
                                 with '#', ';' or ']' are considered as
                                 comments and ignored.
```
