### ISSUE TITLE
Any chance we could get rid of the "tl;dr" strings in the README?

### ISSUE THREAD

**Issue by EAFSC** [ytdl-org/youtube-dl#20713]
I really find this software useful and powerful, but I feel "dirty" knowing that it has "tl;dr" in the README (or at least on the Github main page). I despise that phrase and those who use it, and I have a feeling that the smart author(s) of this software just wanted to use youthful slang, and had seen this in use frequently by dumb people.

It really annoys me when intelligent people seemingly encourage laziness/stupidity. The "too long; didn't read" (especially spelled in all-lowercase) thing should never, ever be encouraged in any way. Instead, one might use "Summary" or "In short" or something.

Small things like this can really make a big psychological difference.

**Comment by dstftw** [comment]
I see no problems using acronyms conventional to programming/internet field.

**Comment by EAFSC** [comment]
Well, you could be part of a positive change.

**Comment by Hrxn** [comment]
> Small things like this can really make a big psychological difference.

[citation needed]
