### ISSUE TITLE
Kajabi Support

### ISSUE THREAD

**Issue by automatorMaxima** [ytdl-org/youtube-dl#20723]
[ x] I've verified and I assure that I'm running youtube-dl 2019.04.17
Before submitting an issue make sure you have:
[x ] At least skimmed through the README, most notably the FAQ and BUGS sections
[ x] Searched the bugtracker for similar issues including closed ones
[ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
What is the purpose of your issue?
  Bug report (encountered problems with youtube-dl)
[x ] Site support request (request for adding support for a new site)
  Feature request (request for a new functionality)
[ x] Question
  Other
If the purpose of this issue is a site support request please provide all kinds of example URLs support for which should be included (replace following example URLs by yours):
Single video: https://bit.ly/2ZjQw6N
Playlist: unsure how to extract the playlist url

**Comment by rryanq** [comment]
The link you provided requires an account to access.

**Comment by remitamine** [comment]
missing the verbose log, post the original video URL.
