### ISSUE TITLE
[Question, Feature Request] Output, how many items in a playlist, series, season, show, or ... etc?

### ISSUE THREAD

**Issue by GenuineSounds** [ytdl-org/youtube-dl#20725]
It would be nice to have a "simulate" or otherwise output command to display how many items are in [your current] URL. And if there is a fairly simple solution available I'd love to hear it. I'm primarily using PowerShell (believe it or not) for my youtube-dl scripts atm. Despite how awkward it is to use in some areas (I'm looking at YOU -- passing in arguments!) I am finding it quite powerful in it's own right but I'd love to be able to either find out how many items are in a playlist, series, or season or have youtube-dl reauth to vrv after some arbitrary time.

VRV seems to be very particular and will straight up deauth after some amount of time so I just write a script that re-runs youtube-dl with authentication after some amount of runs using a manual `--playlist-items $Min-Max ` or something like `--playlist-items 1-61,123-196,271-341,413-1086`

I will close this issue regardless of if I get help as most of the issues are incredibly verbose and not worth posting on the GitHub so thank you in advance.

Feel free to delete this issue or send me to some support forum instead.

**Comment by GenuineSounds** [comment]
Also if there is an easy way to check if the show has seasons or not it would be a great help for automated scripts I'm writing.

**Comment by dstftw** [comment]
`--dump-single-json --flat-playlist`. Count number of entries.
