### ISSUE TITLE
Request: Option to limit total maximum downloaded content

### ISSUE THREAD

**Issue by polski-g** [ytdl-org/youtube-dl#20730]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.17*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Feature request is an option to limit maximum consumed disk space for downloads. Something like `--max-total-files-size` such that the youtube-dl process would halt if the total number of bytes consumed on your local hard drive exceeds this argument. It would be a safety precaution against things like 1) Malicious user input on a web-app, 2) filling up your disk if you are trying to download an entire channel but don't realize how big it is.

This is different than `--max-files` as that option could by "bypassed" by a single 200GB video, for example.

**Comment by nipan09** [comment]
HI! I am a new contributor on github and I want to take up this issue. Provide me the necessary help required.

**Comment by Thomasedv** [comment]
For single files, is this not covered by the `--max-filesize` option? Does not download files with a size above the given filesize. Granted it doesn't completely help in your second case, but that would at least set an upper limit (number of uploads times the max size) Though having the space needed is more up to the user for situations where they want to download an entire channel, in my opinion.
