### ISSUE TITLE
Download audio only (aac from mp4)

### ISSUE THREAD

**Issue by DajMiliona** [ytdl-org/youtube-dl#20747]
I Was try download audio aac from mp4.
youtube-dl.exe - ERROR: requested format not available

ffmpeg.exe - can download only aac from the same url

https://i.imgur.com/Ci5nwyn.png

Latest youtube-dl.exe and ffmpeg.exe

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#format-selection
> bestaudio: Select the best quality audio only-format. May not be available.

I think what you want to use is:
```
-x, --extract-audio              Convert video files to audio-only files
                                 (requires ffmpeg or avconv and ffprobe or
                                 avprobe)
```
