### ISSUE TITLE
[Question] progress_hooks status finished not called  when file exist?

### ISSUE THREAD

**Issue by hangocanh2303** [ytdl-org/youtube-dl#20750]
Hi,
When files in folder exist, progress_hooks finished status not call ? How can I call progress_hooks finished status when file exist

**Comment by dstftw** [comment]
Progress hook with `finished` status is called when file is already present.

**Comment by loworbitmoonsun** [comment]
This is however not the case when the file is in the download archive. Actually reusing the file would be a lot easier if the progress hook would still be called.
