### ISSUE TITLE
HTTP Error 400: Bad Request when trying

### ISSUE THREAD

**Issue by Mikeltxo15** [ytdl-org/youtube-dl#20755]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.17*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X ] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.17**

### Before submitting an *issue* make sure you have:
- [ X ] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [ X ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ X ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--call-home', '-i', '--download-archive', '/home/%user%/Youtube/Archive', '-o', '~/Youtube/%(upload_date)s-%(title)s-%(uploader)s.%(ext)s', '-u', 'PRIVATE', '-p', 'PRIVATE', '-f', 'bestvideo[height<481]+bestaudio', 'https://www.youtube.com/playlist?list=WL']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 3.7.3 (CPython) - Linux-5.0.8-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: 190.183.34.193
[youtube:watchlater] Downloading login page
[youtube:watchlater] Looking up account info
[youtube:watchlater] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube:watchlater] WL: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2927, in _real_extract
    _, playlist = self._extract_playlist('WL')
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2439, in _extract_playlist
    raise ExtractorError(message, expected=True)
youtube_dl.utils.ExtractorError: This playlist does not exist.
```

---

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Hello, I´ve been using youtube-dl for some months now, through the use of a script I wrote. What it does is log in to youtube with my credentials and download the Watch Later playlist, to which I previously add the videos I want to see. In this way, I don't need to manually input the individual URL of all the videos I want to see. However, two weeks ago, the script stopped working. When I run the command on it's own, it exits with a HTTP Error 400: Bad Request saying it couldn't log in to my account, therefore it couldn't find the playlist either.
The problem seems similar to the one present in Bug Report #2975, but in that case it could log into the account but failed in detecting the videos, while in this case it fails to log in. That's why i opened a different Issue.
My guess is Youtube probably changed something about the way to login, which is causing this error.
Many thanks, I'm sorry i can't give more info, and good luck. Also, thanks for all the work needed to create and mantain this program, it's really helpful.

**Comment by omeringen** [comment]
Hi,
I am experienceing HTTP Error 400 about ~3 days.
Restarted router, changed my DNS but no difference.

```
PS C:\WINDOWS\system32> F:\vid\youtube-dl.exe -U -v -u username -p pass -f "[height<=?800]" -o "F:\vid\%(upload_date)s.%(title)s.%(ext)s" https://www.youtube.com/playlist?list=WL
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-U', '-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '-f', '[height<=?800]', '-o', 'F:\\vid\\%(upload_date)s.%(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=WL']
[debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
[debug] youtube-dl version 2019.04.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
youtube-dl is up-to-date (2019.04.17)
[youtube:watchlater] Downloading login page
[youtube:watchlater] Looking up account info
[youtube:watchlater] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube:watchlater] WL: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\youtube.py", line 2927, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\youtube.py", line 2439, in _extract_playlist
youtube_dl.utils.ExtractorError: This playlist does not exist.
```

```
PS C:\WINDOWS\system32> F:\vid\youtube-dl.exe -U -v -u 'username' -p 'pass' -f "[height<=?800]" -o "F:\vid\%(upload_date)s.%(title)s.%(ext)s" :ytsubs --dateafter 20190418
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-U', '-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '-f', '[height<=?800]', '-o', 'F:\\vid\\%(upload_date)s.%(title)s.%(ext)s', ':ytsubs', '--dateafter', '20190418']
[debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
[debug] youtube-dl version 2019.04.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
youtube-dl is up-to-date (2019.04.17)
[youtube:subscriptions] Downloading login page
[youtube:subscriptions] Looking up account info
[youtube:subscriptions] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
[youtube:subscriptions] playlist Youtube Subscriptions: Downloading 0 videos
[download] Finished downloading playlist: Youtube Subscriptions
```

**Comment by Mikeltxo15** [comment]
@dstftw This is not a duplicate of Issue #2975 , they are different problems. Me, @Mikeltxo15 , @omeringen and @Quaraxkad are experiencing this issue, and it was not resolved in the 3 successive updates after the issue first appeared.

**Comment by dstftw** [comment]
Duplicate of #11270.
