### ISSUE TITLE
Error Youtube-dl

### ISSUE THREAD

**Issue by wellton** [ytdl-org/youtube-dl#20766]
This is last version.

![image](https://user-images.githubusercontent.com/2234645/56626993-6ae3af00-661a-11e9-96a2-99cb45c57258.png)

**Comment by tmgiewont** [comment]
Having this same bug too

**Comment by wtfjuan** [comment]
same

**Comment by Droffig61** [comment]
Same issue, but looks like this may be the issue.  https://github.com/ytdl-org/youtube-dl/issues/20758.
Hope a new exe will be released soon.  My output in in that ticket...

**Comment by AllOgreTheWorld** [comment]
Same issue here

**Comment by ChenWeird** [comment]
D:\Youtube> youtube-dl --proxy socks5://127.0.0.1:6666/ "https://www.youtube.com/playlist?list=PLA567CE235D39FA84" -o '%(playlist)s/%(playlist_index)s - %(ti
tle)s.%(ext)s' --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', 'socks5://127.0.0.1:6666/', 'https://www.youtube.com/playlist?list=PLA567CE235D39FA84', '-o', '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', '--verbose']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2019.04.17
[debug] Python version 3.6.6 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: none
[debug] Proxy map: {'http': 'socks5://127.0.0.1:6666/', 'https': 'socks5://127.0.0.1:6666/'}
[youtube:playlist] PLA567CE235D39FA84: Downloading webpage
[download] Downloading playlist: Tutorial Series for Arduino
[youtube:playlist] playlist Tutorial Series for Arduino: Downloading 15 videos
[download] Downloading video 1 of 15
[youtube] fCxzA9_kg6s: Downloading webpage
[youtube] fCxzA9_kg6s: Downloading video info webpage
ERROR: fCxzA9_kg6s: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\chenw\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\chenw\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "c:\users\chenw\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1693, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: fCxzA9_kg6s: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by khalid-hussain** [comment]
This issue has been repeated a couple of times already.

https://github.com/ytdl-org/youtube-dl/issues/20764
https://github.com/ytdl-org/youtube-dl/issues/20761
https://github.com/ytdl-org/youtube-dl/issues/20758

**Comment by wellton** [comment]
apparently google has hacked the hacker galley =)

**Comment by brachism** [comment]
I assume Google/YouTube rolled out a changed today.   I downloaded a few videos this afternoon with no issue.  This evening every URL I've try (dozens) results in this _**"token parameter not in video info for unknown reason error on every video."_**  Even videos I downloaded hours earlier today now fail.  Updating via "youtube-dl -U" didn't help...

**Comment by wellton** [comment]
> This issue has been repeated a couple of times already.
> 
> #20764
> #20761
> #20758
> 
> Possible (temporary) solution: [#20758 (comment)](https://github.com/ytdl-org/youtube-dl/issues/20758#issuecomment-486016882)

SHOWWW. THANKS
