### ISSUE TITLE
HTTP Error 503

### ISSUE THREAD

**Issue by FelixChery** [ytdl-org/youtube-dl#20785]
youtube-dl -v --write-sub --write-auto-sub --output "%(upload_date)s-%(title)s.%(ext)s" --skip-downl
oad -i -c --dateafter 20080101 --datebefore 20091231 https://www.youtube.com/cha
nnel/UCKVsdeoHExltrWMuK0hOWmg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--write-sub', '--write-auto-sub', '--output',
 '%(upload_date)s-%(title)s.%(ext)s', '--skip-download', '-i', '-c', '--dateafte
r', '20080101', '--datebefore', '20091231', 'https://www.youtube.com/channel/UCK
VsdeoHExltrWMuK0hOWmg']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:channel] UCKVsdeoHExltrWMuK0hOWmg: Downloading channel page
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading webpage
[download] Downloading playlist: Uploads from KTN News Kenya
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #1
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #2
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #3
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #4
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #5
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #6
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #7
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #8
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #9
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #10
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #11
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #12
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #13
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #14
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #15
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #16
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #17
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #18
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #19
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #20
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #21
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #22
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #23
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #24
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #25
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #26
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #27
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #28
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #29
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #30
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #31
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #32
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #33
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #34
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #35
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #36
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #37
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #38
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #39
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #40
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #41
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #42
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #43
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #44
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #45
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #46
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #47
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #48
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #49
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #50
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #51
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #52
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #53
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #54
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #55
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #56
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #57
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #58
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #59
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #60
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #61
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #62
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #63
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #64
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #65
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #66
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #67
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #68
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #69
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #70
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #71
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #72
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #73
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #74
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #75
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #76
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #77
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #78
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #79
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #80
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #81
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #82
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #83
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #84
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #85
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #86
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #87
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #88
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #89
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #90
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #91
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #92
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #93
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #94
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #95
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #96
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #97
[youtube:playlist] UUKVsdeoHExltrWMuK0hOWmg: Downloading page #98
ERROR: Unable to download JSON metadata: HTTP Error 503: Service Unavailable (ca
used by HTTPError()); please report this issue on https://yt-dl.org/bug . Make s
ure you are using the latest version; type  youtube-dl -U  to update. Be sure to
 call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf
78\build\youtube_dl\extractor\common.py", line 626, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf
78\build\youtube_dl\YoutubeDL.py", line 2227, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 502, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 685, in http_error_302
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt

**Comment by FelixChery** [comment]
I was downloading subtitles for certain videos on a youtube channel based on upload date. What could be the cause of this or the alternative way to do so?

**Comment by dstftw** [comment]
Most likely temporary youtube side issue.
