### ISSUE TITLE
error "token" parameter not in video info

### ISSUE THREAD

**Issue by itaj-sherman** [ytdl-org/youtube-dl#20781]
Windows 10 command line:
D:\import\youtube>youtube-dl -U
...
D:\import\youtube>youtube-dl --list-formats --verbose https://www.youtube.com/watch?v=yAONMYnkh4o
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--list-formats', '--verbose', 'https://www.youtube.com/watch?v=yAONMYnkh4o']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.04.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.0.2
[debug] Proxy map: {}
[youtube] yAONMYnkh4o: Downloading webpage
[youtube] yAONMYnkh4o: Downloading video info webpage
ERROR: yAONMYnkh4o: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\youtube.py", line 1693, in _real_extract
youtube_dl.utils.ExtractorError: yAONMYnkh4o: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Nick-Dillon** [comment]
I have had the same problem, with the same "token" error message but on Linux instead of Windows. It has been working fine until today

**Comment by Levomar** [comment]
I have the same problem ''token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

I reupdated the version of youtube-dl, but nothing seems to work.

**Comment by kissmvc** [comment]
Same problem with token - xnolavzfBcY - probably general problem on YT.

**Comment by titanicjb** [comment]
Same to me but on MacOS.  I have also updated to version 2019.04.17, without any help.  Download-URL was https://www.youtube.com/watch?v=L45b1zb2BEI

**Comment by darinhouston** [comment]
Same here.  MacOS -- several different computers, various videos and versions of youtube-dl
