### ISSUE TITLE
token parameter not in video

### ISSUE THREAD

**Issue by Radosveta** [ytdl-org/youtube-dl#20783]
Radosvetas-MacBook-Pro:~ radost$ youtube-dl https://youtu.be/pijcRr_xNy0
[youtube] pijcRr_xNy0: Downloading webpage
[youtube] pijcRr_xNy0: Downloading video info webpage
ERROR: pijcRr_xNy0: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Radosvetas-MacBook-Pro:~ radost$ 

Radosvetas-MacBook-Pro:~ radost$ youtube-dl --verbose https://youtu.be/pijcRr_xNy0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://youtu.be/pijcRr_xNy0']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 2.7.10 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] pijcRr_xNy0: Downloading webpage
[youtube] pijcRr_xNy0: Downloading video info webpage
ERROR: pijcRr_xNy0: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1693, in _real_extract
    video_id=video_id)
ExtractorError: pijcRr_xNy0: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Radosvetas-MacBook-Pro:~ radost$ youtube-dl --version
2019.04.17

**Comment by DSigmund** [comment]
administrator@FS-FM-IPTV-203:~$ youtube-dl https://www.youtube.com/watch?v=xJKj0pFE2_Y --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=xJKj0pFE2_Y', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 2.7.6 (CPython) - Linux-3.13.0-24-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] xJKj0pFE2_Y: Downloading webpage
[youtube] xJKj0pFE2_Y: Downloading video info webpage
ERROR: xJKj0pFE2_Y: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1693, in _real_extract
    video_id=video_id)
ExtractorError: xJKj0pFE2_Y: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Radosveta** [comment]
still does not work

**Comment by darinhouston** [comment]
ditto

**Comment by darinhouston** [comment]
% ./youtube-dl --verbose -x --audio-format mp3 "http://youtu.be/stwxIMsDLyY"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-x', u'--audio-format', u'mp3', u'http://youtu.be/stwxIMsDLyY']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 2.7.16 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[youtube] stwxIMsDLyY: Downloading webpage
[youtube] stwxIMsDLyY: Downloading video info webpage
ERROR: stwxIMsDLyY: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1693, in _real_extract
    video_id=video_id)
ExtractorError: stwxIMsDLyY: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
