### ISSUE TITLE
This video is unavailable

### ISSUE THREAD

**Issue by MantaRayDeeJay** [ytdl-org/youtube-dl#20793]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.24*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.04.24
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by MantaRayDeeJay** [comment]
I have downloading errors with some youtube videos as single or in a video list. In a list, if a video is "unavailable", the program stop and doesn't scan other videos in the list. (Stopping on the first error).

1a) Single file Issue : 
```
youtube-dl

youtube-dl.exe --list-formats --batch-file "D:\Informatique\_Projets\_Training\BACH\Youtube Download\yt_solo_video.txt"

[youtube] ZFdHB0z4Qww: Downloading webpage
[youtube] ZFdHB0z4Qww: Downloading video info webpage
WARNING: Unable to extract video title
ERROR: This video is unavailable.
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-overwrites', '--format', '137+140/136+140/135+140/134+140/best', '--merge-output-format', 'mp4', '--batch-file', 'D:\\Informatique\\_Projets\\_Training\\BACH\\Youtube Download\\yt_solo_video.txt', '--verbose']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=ZFdHB0z4Qww']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[youtube] ZFdHB0z4Qww: Downloading webpage
[youtube] ZFdHB0z4Qww: Downloading video info webpage
WARNING: Unable to extract video title
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\youtube.py", line 1992, in _real_extract
youtube_dl.utils.ExtractorError: This video is unavailable.
```
1b) Video list issue : 
```
youtube-dl

youtube-dl.exe --list-formats --batch-file "D:\Informatique\_Projets\_Training\BACH\Youtube Download\yt_solo_video.txt"

[youtube:playlist] Downloading playlist PLoSIOFPSXQoOvw98ekM9rwydxI4IWRKpQ - add --no-playlist to just download video ZFdHB0z4Qww
[youtube:playlist] PLoSIOFPSXQoOvw98ekM9rwydxI4IWRKpQ: Downloading webpage
[download] Downloading playlist: Tomorrowland -  Artist Interviews
[youtube:playlist] playlist Tomorrowland -  Artist Interviews: Downloading 52 videos
[download] Downloading video 1 of 52
[youtube] ZFdHB0z4Qww: Downloading webpage
[youtube] ZFdHB0z4Qww: Downloading video info webpage
WARNING: Unable to extract video title
ERROR: This video is unavailable.
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-overwrites', '--format', '137+140/136+140/135+140/134+140/best', '--merge-output-format', 'mp4', '--batch-file', 'D:\\Informatique\\_Projets\\_Training\\BACH\\Youtube Download\\yt_solo_video.txt', '--verbose']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=ZFdHB0z4Qww&list=PLoSIOFPSXQoOvw98ekM9rwydxI4IWRKpQ&index=1']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLoSIOFPSXQoOvw98ekM9rwydxI4IWRKpQ - add --no-playlist to just download video ZFdHB0z4Qww
[youtube:playlist] PLoSIOFPSXQoOvw98ekM9rwydxI4IWRKpQ: Downloading webpage
[download] Downloading playlist: Tomorrowland -  Artist Interviews
[youtube:playlist] playlist Tomorrowland -  Artist Interviews: Downloading 52 videos
[download] Downloading video 1 of 52
[youtube] ZFdHB0z4Qww: Downloading webpage
[youtube] ZFdHB0z4Qww: Downloading video info webpage
WARNING: Unable to extract video title
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\youtube.py", line 1992, in _real_extract
youtube_dl.utils.ExtractorError: This video is unavailable.
```

2) video link sample where the error occurs : 
https://www.youtube.com/watch?v=ZFdHB0z4Qww&list=PLoSIOFPSXQoOvw98ekM9rwydxI4IWRKpQ&index=1
Videos 1 and 3 have a **Private** Status, so when the error occurs, it prevents all next video downloading.

**Comment by MantaRayDeeJay** [comment]
I think it joins an other issue : https://github.com/ytdl-org/youtube-dl/issues/20568

**Comment by remitamine** [comment]
```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
```
