### ISSUE TITLE
Token parameter missing in youtube-dl

### ISSUE THREAD

**Issue by subhamoy-guha** [ytdl-org/youtube-dl#20799]
DYTa6oaRGWA: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Facing this type of issue from last few days

**Comment by bill-kuykendall** [comment]
Been retired 10 years.  Former geek, current dinosaur.  Running Ubuntu 18.04/2 Desktop.  Just installed youtube-dl on this version 2 hours ago to download a rare '50's video.  Have used this app occasionally on earlier versions of Ubuntu over the past few years.  Hadn't installed app on this version prior to today, so it should be fully up to date.  Error log attached (output from "youtube-dl --verbose https://www.youtube.com/watch?v=P94ypz9Pzio >/tmp/error.log 2>&1")

[error.log](https://github.com/ytdl-org/youtube-dl/files/3300972/error.log)
  Received message attached.

**Comment by bill-kuykendall** [comment]
The other copy of the same movie on youtube (https://www.youtube.com/watch?v=P94ypz9Pzio) produces an identical error.

**Comment by bitraid** [comment]
As your log indicates, you are running (outdated) version `2018.03.14`.
