### ISSUE TITLE
pip package wrong version - related to the token issue

### ISSUE THREAD

**Issue by isakrubin** [ytdl-org/youtube-dl#20798]
$ which youtube-dl
/usr/local/bin/youtube-dl

$ sudo rm /usr/local/bin/youtube-dl

$ hash -r;which youtube-dl                                                                                                                                   
youtube-dl not found

$ sudo pip3 install youtube_dl -U --force --no-cache                                                                                                         
Collecting youtube_dl
  Downloading https://files.pythonhosted.org/packages/41/4f/b9d6a4dff6cf176d593d494deade44db19654adc3188b7e2842f21a1f31b/youtube_dl-2019.4.24-py2.py3-none-any.whl (1.8MB)
     |████████████████████████████████| 1.8MB 2.7MB/s
Installing collected packages: youtube-dl
  Found existing installation: youtube-dl 2019.4.24
    Uninstalling youtube-dl-2019.4.24:
      Successfully uninstalled youtube-dl-2019.4.24
Successfully installed youtube-dl-2019.4.24

$ hash -r;which youtube-dl
/usr/local/bin/youtube-dl

$ youtube-dl --version
2019.01.23

Which in turn gives the token issue lots of users are reporting, could there be an issue in the pip package?

Expected the 2019.04.24 version.......

**Comment by dstftw** [comment]
Most likely you have several instanses of youtube-dl installed.

**Comment by isakrubin** [comment]
No there are no other versions installed, don't close the issue so quickly.

I think this could be the reason so many people report on the token issue, as upgrading using pip installs the wrong version.

$ sudo find / -xdev -iname youtube-dl                                                                                                                        
/usr/local/bin/youtube-dl

$ /usr/local/bin/youtube-dl --version
2019.01.23

$ sudo rm /usr/local/bin/youtube-dl                                                                                                                          

$ sudo pip3 install youtube_dl -U --force --no-cache                                                                                                         
Collecting youtube_dl
  Downloading https://files.pythonhosted.org/packages/41/4f/b9d6a4dff6cf176d593d494deade44db19654adc3188b7e2842f21a1f31b/youtube_dl-2019.4.24-py2.py3-none-any.whl (1.8MB)
     |████████████████████████████████| 1.8MB 2.6MB/s
Installing collected packages: youtube-dl
  Found existing installation: youtube-dl 2019.4.24
    Uninstalling youtube-dl-2019.4.24:
      Successfully uninstalled youtube-dl-2019.4.24
Successfully installed youtube-dl-2019.4.24

$ sudo find / -xdev -iname youtube-dl
/usr/local/bin/youtube-dl

$ /usr/local/bin/youtube-dl --version
2019.01.23

**Comment by isakrubin** [comment]
Try for yourself, install/upgrade using pip on fresh machine/vm and check the version installed.

**Comment by dstftw** [comment]
```
user@user-VirtualBox:~$ youtube-dl --version
The program 'youtube-dl' is currently not installed. You can install it by typing:
sudo apt install youtube-dl
user@user-VirtualBox:~$ sudo pip3 install youtube-dl
[sudo] password for user: 
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting youtube-dl
  Downloading https://files.pythonhosted.org/packages/41/4f/b9d6a4dff6cf176d593d494deade44db19654adc3188b7e2842f21a1f31b/youtube_dl-2019.4.24-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 31.8MB/s 
Installing collected packages: youtube-dl
Successfully installed youtube-dl-2019.4.24
You are using pip version 19.0.3, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
user@user-VirtualBox:~$ youtube-dl --version
2019.04.24
```
