### ISSUE TITLE
Can't download from Tiktok

### ISSUE THREAD

**Issue by EnthusiastAnon** [ytdl-org/youtube-dl#20809]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl.exe --verbose https://www.tiktok.com/share/video/6682711605567884550
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tiktok.com/share/video/6682711605567884550']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 3.4.1, ffprobe N-68994-g4df01d5, phantomjs 2.1.1
[debug] Proxy map: {}
[TikTok] 6682711605567884550: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\tiktok.py", line 101, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\common.py", line 1004, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

I can't download any TikTok video and supported sites lists it as supported site.

**Comment by eastons9** [comment]
I'm having the same problem. It seems that TikTok have changed the code on their share pages (both for channels and individual videos). This is evident from the most recent video now being double the size of older videos (which was previously not the case).

**Comment by bandicootdancing** [comment]
Also having trouble extacting but this is what I'm getting. The playlist does have videos. They seem to be changing this often. 

` ` youtube-dl https://www.tiktok.com/share/user/6579676783468429313
[TikTokUser] 6579676783468429313: Downloading JSON metadata
[download] Downloading playlist: 6579676783468429313
[TikTokUser] playlist 6579676783468429313: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: 6579676783468429313
``

**Comment by eastons9** [comment]
A positive, however, when this issue is resolved, is that TikTok now no longer limits the share pages to just the 24 most recent videos, so hopefully we'll be able to pull the entire user account using YouTube-DL.

**Comment by bandicootdancing** [comment]
Yes, that's a good sign but doesn't help when the extractor breaks every time they make a change. Here's the latest error I've received with the latest version of youtube-dl and a single video link. 

``` youtube-dl --verbose https://www.tiktok.com/share/video/6662567494319951105
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.tiktok.com/share/video/6662567494319951105']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.13 (CPython) - Linux-4.19.0-0.bpo.1-amd64-x86_64-with-debian-9.5
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[TikTok] 6662567494319951105: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/media/sdan/cptn/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/media/sdan/cptn/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/media/sdan/cptn/bin/youtube-dl/youtube_dl/extractor/tiktok.py", line 101, in _real_extract
    r'\bdata\s*=\s*({.+?})\s*;', webpage, 'data'), video_id)
  File "/media/sdan/cptn/bin/youtube-dl/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

**Comment by VasiliPupkin256** [comment]
The list of videos can be fetched using urls of this form `https://m.tiktok.com/share/item/list?id=...&type=1&count=48&minCursor=0&maxCursor=0&_signature=...` the structure of json and maxCursor is straightforward. But the way it builds signature field is weird. It is now built by https://s16.tiktokcdn.com/tiktok/falcon/static/js/d7a62754.js in an obfuscated function "KS+a", these js url and function name can be different for you.

**Comment by ColinTheShark** [comment]
Adding to this in hopes to be helpful.

    clnshrk@SharkTank:~/ydl$ ydl --version
    2019.05.20
    clnshrk@SharkTank:~/ydl$ ydl https://www.tiktok.com/share/video/6678387681216433414 --verbose
    [debug] System config: []
    [debug] User config: [u'--format', u'mp4', u'--merge-output-format', u'mp4', u'-o', u'~/ydl/%(title)s.%(ext)s']
    [debug] Custom config: []
    [debug] Command-line args: [u'https://www.tiktok.com/share/video/6678387681216433414', u'--verbose']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2019.05.20
    [debug] Python version 2.7.13 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9.9
    [debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
    [debug] Proxy map: {}
    [TikTok] 6678387681216433414: Downloading webpage
    ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tiktok.py", line 101, in _real_extract
    r'\bdata\s*=\s*({.+?})\s*;', webpage, 'data'), video_id)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1004, in _search_regex
        raise RegexNotFoundError('Unable to extract %s' % _name)
    RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
