### ISSUE TITLE
Error in downloading some, but not all videos

### ISSUE THREAD

**Issue by JDoes** [ytdl-org/youtube-dl#20803]
On some videos, youtube-dl does not work, but on others, it works just fine. I have attempted to update and reboot my computer. Here is the --verbose output. It says in the terminal that I can update to the latest version, but the version it says is 2019.04.19, not the 2019.04.24 as it says in the instructions here.

youtube-dl --verbose https://www.youtube.com/watch?v=Ofn7jqPDTeY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=Ofn7jqPDTeY']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-47-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4
[debug] Proxy map: {}
[youtube] Ofn7jqPDTeY: Downloading webpage
[youtube] Ofn7jqPDTeY: Downloading video info webpage
ERROR: Ofn7jqPDTeY: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1693, in _real_extract
    video_id=video_id)
ExtractorError: Ofn7jqPDTeY: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by bilinbs** [comment]
Please try updating again using the command ```youtube-dl -U``` and then try again.

**Comment by nutelina** [comment]
I have it too, updated youtube-dl this happened today for the first time only for youtube.com older videos, newer. It seems Google changed something.
