### ISSUE TITLE
cant download from youtube anymore

### ISSUE THREAD

**Issue by ehsanfaal** [ytdl-org/youtube-dl#20821]
Hi friends. its been some days which i cant download from youtube anymore.
what should I do?

➜ torsocks youtube-dl -c -i -f best --verbose -a links
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-c', '-i', '-f', 'best', '--verbose', '-a', 'links']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=vksfnZaZ0A4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.08
1556182509 WARNING torsocks[7191]: [syscall] Unsupported syscall number 217. Denying the call (in tsocks_syscall() at syscall.c:488)
[debug] Python version 3.6.7 (CPython) - Linux-4.15.0-48-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4, phantomjs 1556182511, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] vksfnZaZ0A4: Downloading webpage
[youtube] vksfnZaZ0A4: Downloading video info webpage
ERROR: vksfnZaZ0A4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ehsan/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/home/ehsan/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/home/ehsan/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1689, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: vksfnZaZ0A4: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by mitalix** [comment]
I got something very similar today ... 

youtube-dl https://www.youtube.com/watch?v=S9ax8uqfLrg --verbose
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=S9ax8uqfLrg', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.30
[debug] Python version 3.7.3 (CPython) - Linux-5.0.8-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
[debug] exe versions: ffmpeg 4.0.4, ffprobe 4.0.4
[debug] Proxy map: {}
[youtube] S9ax8uqfLrg: Downloading webpage
[youtube] S9ax8uqfLrg: Downloading video info webpage
ERROR: S9ax8uqfLrg: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1689, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: S9ax8uqfLrg: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
