### ISSUE TITLE
"token" parameter not in video info for unknown reason

### ISSUE THREAD

**Issue by zipidy** [ytdl-org/youtube-dl#20830]
sudo youtube-dl -F https://www.youtube.com/watch?v=6uE04nQfO-Q --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.youtube.com/watch?v=6uE04nQfO-Q', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.18
[debug] Python version 3.5.2 (CPython) - Linux-5.0.0-13-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 15b385e, ffprobe 15b385e
[debug] Proxy map: {}
[youtube] 6uE04nQfO-Q: Downloading webpage
[youtube] 6uE04nQfO-Q: Downloading video info webpage
ERROR: 6uE04nQfO-Q: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/snap/youtube-dl/711/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/snap/youtube-dl/711/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/snap/youtube-dl/711/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1689, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: 6uE04nQfO-Q: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Ledram** [comment]
I'm having the same issue ... I'm getting an error when I download anything about a "token parameter" not in video.  I tried like 5 videos, none of them worked (different channels, etc).  I am running a debian environment, and never had issues before.  I tried uninstalling and reinstalling with python/pip but it says that I need python version 18.0 or something? 

**Here's my verbose output:**
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.17
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-4-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
[debug] exe versions: ffmpeg 4.1.1-1, ffprobe 4.1.1-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
```

**And one of the errors:**
```
ERROR: y62zj9ozPOM: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1689, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: y62zj9ozPOM: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

**Comment by zipidy** [comment]
Don't waste your time with this non-functioning app. Just use this https://ytmp3.cc/
