### ISSUE TITLE
youtube-dl updating on windows 10

### ISSUE THREAD

**Issue by IoanPaleru** [ytdl-org/youtube-dl#20831]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.24**
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
- [x] Checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [x] Question

![youtube-dl](https://user-images.githubusercontent.com/35790889/56772348-afd92400-6787-11e9-96da-ba0bb46cd008.jpg)

Hi. When typing "youtube-dl --update" in a cmd or powershell window in windows 10 to update it, it gives an error message that says "The system cannot find the file specified.", and even though it says "Updated youtube-dl to version 2019.04.24.", you can tell that it isn't updated, because if you type "youtube-dl --version", it says "2018.12.03. I've already added youtube-dl's program path to the environment variables path list in windows 10's system properties, so do you know why it isn't updating and how to get it to update properly? When I try and update it the same way with my windows 7 computer, it updates properly. Thanks.

**Comment by dstftw** [comment]
Most likely you have several instances of youtube-dl in `PATH`.

**Comment by IoanPaleru** [comment]
There's only one instance of youtube-dl in path. I figured out how to update youtube--dl though, go to youtube-dl's installation directory, right-click it and select properties, security, and give all group or user names all permissions, then open the directory, right-click on youtube-dl and select compatibility, and check run this program as administrator, then open a cmd prompt in youtube-dl's installation directory by pressing and holding shift and right-clicking anywhere in the white space in that folder, and select open command window here, then type youtube-dl --update and youtube-dl will update properly, but to run other commands such as youtube-dl --version, you need to uncheck run this program as administrator.

However, you never used to need to do all that to update youtube-dl, simply adding in to the environment variables path list in system properties, opening a cmd prompt window from any folder, then typing youtube-dl --update used to be able to update it properly. Now it doesn't update properly on windows 7 or 10.

It would be great if you could fix it so that it updates properly, and easily. Other than that, it's a great program. Thanks.

**Comment by IoanPaleru** [comment]
Hi, is there a way to merge all of these similar service requests: "https://github.com/ytdl-org/youtube-dl/issues/20831", "https://github.com/ytdl-org/youtube-dl/issues/20832", "https://github.com/ytdl-org/youtube-dl/issues/20887", and "https://github.com/ytdl-org/youtube-dl/issues/20888" into one service request? Thanks.

Hi. You provided me with the "--format "best[ext=mp4][height<=720]" command to use to download and convert files as 720p mp4 a while ago when I wanted help with that, because I didn't know which command to use. Everything was working fine and youtube-dl was able to download videos properly and convert them in that format until recently. Can you please tell me what command to use for youtube-dl to download videos in 720p (in this case, in the available 720x480 resolution), and mux the available streams using ffmpeg into an mp4 file? So far, I've only found out how to get youtube-dl to download the videos in the correct 720x480 available resolution, but it saves them as mkv files, and I want to find out how to get it to use ffmpeg to convert them to mp4 files. I'd really appreciate it, since the faq is very confusting for average computer users. Youtube-dl is a very good program by the way, once people know how to use it. Thank you.
