### ISSUE TITLE
FtQ5KUBpDq4: "token" parameter not in video info for unknown reason;

### ISSUE THREAD

**Issue by mohitsinhchavda** [ytdl-org/youtube-dl#20859]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.04.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by Ledram** [comment]
I see these are all getting labeled as "outdated version", but it seems like I'm not the only one having issues getting the updated version as it seems to only be compatible with pip 18.0, do I really have to roll back my pip installation to make it work, or am i misunderstanding something!? @dstftw  thanks in advance

**Comment by Hrxn** [comment]
Why rolling back? The latest version of youtube-dl seems to just work fine with the latest version of pip, at least for me. What exactly is the issue?

**Comment by Ledram** [comment]
I'm getting the "token" parameter error every time I attempt to use youtube-dl ... I actually tried rolling back pip anyway, and I still get the same error...
```"token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

After following some trouble shooting on here, I tried making sure I had the updated version of youtube-dl.  Not sure if I started with regular apt last night or pip (can't remember), but now, when I try to update using apt, it works fine, saying I have the new version: 
```
sudo apt-get install youtube-dl 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
youtube-dl is already the newest version (2019.01.17-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

However, I still get this issue when I try to use youtube-dl on any video

When I try to update using pip, I get:
```sudo pip install --upgrade youtube_dl
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pip 18.1 (/usr/lib/python3/dist-packages), Requirement.parse('pip==18.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==18.0' distribution was not found and is required by the application
```

Any ideas?  Thanks!

**Comment by dstftw** [comment]
Again: you are using an outdated version of youtube-dl. Your update fails due to broken pip. Fix it.
