### ISSUE TITLE
Will youtube-dl download livestreams when input a youtube channel url?

### ISSUE THREAD

**Issue by jmliz** [ytdl-org/youtube-dl#20854]
I want to run a cron task that executes youtube-dl to download a whole channel and updates whenever the creator uploads a new video or livestream.

I want to download all new livestreams along with the new videos by just giving the youtube channel url to youtube-dl. Is that possible? Will it download as it is live or wait until the creator publishes it? My plan is to make a full archive of some valuable youtube channels and to include lives.

**Comment by jmliz** [comment]
I'm sorry this is out of scope. I just followed the Support link in the website. Where should I address this question then?

**Comment by jmliz** [comment]
@remitamine ?

**Comment by remitamine** [comment]
you have to search online or make your script.
I think that [this script](https://github.com/jaimeMF/media-subscriptions) can do part of the task that you want.
also, you might look for help at a forum related to data archival(ex: https://www.reddit.com/r/DataHoarder/).
