### ISSUE TITLE
ERROR: 3an6NlxPo84: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug 

### ISSUE THREAD

**Issue by garvint** [ytdl-org/youtube-dl#20866]
youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.18.1
[debug] Python version 3.5.3 - Linux-4.9.0-8-amd64-x86_64-with-BunsenLabs-9.6-helium
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1, rtmpdump 2.4
[debug] Proxy map: {}

i check on apt-get and youtube-dl is the latest version

**Comment by slatunje** [comment]
I am facing the same issue

**Comment by rezamar555** [comment]
Same here

**Comment by Extemma** [comment]
same as well

**Comment by shuttah627** [comment]
All videos are pulling this error in my testing. Possibly something on youtube's end has just been deployed and its broken the current yt-dl build.

**Comment by adeptg** [comment]
Same for me. Tested on yt-dl 2018.09.10, 2019.01.17 and 2019.04.24 with the same result
Video example: https://www.youtube.com/watch?v=xeQe-TemEfI
But looiks like it can be reproduced on any video

**Comment by garvint** [comment]
> All videos are pulling this error in my testing. Possibly something on youtube's end has just been deployed and its broken the current yt-dl build.

this appears to be correct, i tried youtube-dl with this result:

[generic] watch?time_continue=175: Requesting header
[redirect] Following redirect to https://www.youtube.com/
[generic] www.youtube: Requesting header
WARNING: Falling back on generic information extractor.
[generic] www.youtube: Downloading webpage
[generic] www.youtube: Extracting information
ERROR: Unsupported URL: https://www.youtube.com/


youtube itself is blocking the method

**Comment by remitamine** [comment]
@garvint update youtube-dl and read https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command.

**Comment by adeptg** [comment]
@remitamine  seems like I have the latest version and still have the same issue. Should I file another bug report?

**Comment by remitamine** [comment]
if you're getting the same error then you're not using the latest version(2019.04.24).
