### ISSUE TITLE
[heavy-r.com] Connection interrupt leads to unplayable video file

### ISSUE THREAD

**Issue by charon2019** [ytdl-org/youtube-dl#20869]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.04.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl --verbose https://www.heavy-r.com/video/350613/Ass_Fuck_For_Petite_Daughter/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.heavy-r.com/video/350613/Ass_Fuck_For_Petite_Daughter/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.5.2 (CPython) - Linux-4.15.0-041500-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 3.2.4-1yavdr0, avprobe 3.2.4-1yavdr0, ffmpeg 3.2.4-1yavdr0, ffprobe 3.2.4-1yavdr0, rtmpdump 2.4
[debug] Proxy map: {}
[generic] Ass_Fuck_For_Petite_Daughter: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Ass_Fuck_For_Petite_Daughter: Downloading webpage
[generic] Ass_Fuck_For_Petite_Daughter: Extracting information
[download] Downloading playlist: Ass Fuck For Petite Daughter
[generic] playlist Ass Fuck For Petite Daughter: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://cluster4a.heavy-r.com/v/9452d85d6e8cdddc7a349cf8b03ce480/5cc56ad8/vid/a2/1c/01/a21c01391f1908c.mp4'
[download] Destination: Ass Fuck For Petite Daughter-Ass_Fuck_For_Petite_Daughter.mp4
[download]  78.8% of 24.68MiB at 255.33KiB/s ETA 00:20[download] Got server HTTP error: Downloaded 20399373 bytes, expected 25881388 bytes. Retrying (attempt 1 of 10)...
[download] Destination: Ass Fuck For Petite Daughter-Ass_Fuck_For_Petite_Daughter.mp4
[download] 100% of 24.68MiB in 01:38
[download] Finished downloading playlist: Ass Fuck For Petite Daughter

```

## Description

After a connection interrupt - quite oftently caused by the webserver - the video file is broken and unplayable.

As you can see in the log, after 78.8%, the connection broke down. The video file is only playable up to this point. After that, broken.

Unfortunately, the same issue occurs, when you download the url with `wget`. It happens with a lot of videos on that platform recently. It's not due to one broken file, nor does it happen at the same point in the file all the time. Downloading becomes a role the dice game.

Seems like the web server doesn't properly resume the connection at the requested byte.

Youtube-dl should go back a little and redownload a few kilobytes and or binary overlap the downloaded part and the new part instead of just appending the new to the old.

**Comment by dstftw** [comment]
Redownloading starting few bytes back won't make any difference if a webserver handles range requests improperly.
