### ISSUE TITLE
[Youtube] Merging fails with 2019.04.24

### ISSUE THREAD

**Issue by yetipenguin** [ytdl-org/youtube-dl#20872]
I'm using youtube-dl 2019.04.24 to download a youtube video. Im getting the error "debug" after the merge output:
`youtube-dl https://www.youtube.com/watch?v=dbGS7gWmJZA
[youtube] dbGS7gWmJZA: Downloading webpage
[youtube] dbGS7gWmJZA: Downloading video info webpage
[download] Destination: Sick Shoes-dbGS7gWmJZA.f248.webm
[download] 100% of 4.00MiB in 00:05
[download] Destination: Sick Shoes-dbGS7gWmJZA.f171.webm
[download] 100% of 2.24MiB in 00:03
[ffmpeg] Merging formats into "Sick Shoes-dbGS7gWmJZA.webm"
ERROR: "debug"`

With --verbose:
`youtube-dl --verbose https://www.youtube.com/watch?v=dbGS7gWmJZA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=dbGS7gWmJZA']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.24
[debug] Python version 2.7.6 (CPython) - Linux-3.13.0-108-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, ffmpeg 11.3-6
[debug] Proxy map: {}
[youtube] dbGS7gWmJZA: Downloading webpage
[youtube] dbGS7gWmJZA: Downloading video info webpage
[youtube] {18} signature length 43.42, html5 player vflU6l_su
[youtube] {137} signature length 43.42, html5 player vflU6l_su
[youtube] {248} signature length 43.42, html5 player vflU6l_su
[youtube] {136} signature length 43.42, html5 player vflU6l_su
[youtube] {247} signature length 43.42, html5 player vflU6l_su
[youtube] {135} signature length 43.42, html5 player vflU6l_su
[youtube] {244} signature length 43.42, html5 player vflU6l_su
[youtube] {134} signature length 43.42, html5 player vflU6l_su
[youtube] {243} signature length 43.42, html5 player vflU6l_su
[youtube] {133} signature length 43.42, html5 player vflU6l_su
[youtube] {242} signature length 43.42, html5 player vflU6l_su
[youtube] {160} signature length 43.42, html5 player vflU6l_su
[youtube] {278} signature length 43.42, html5 player vflU6l_su
[youtube] {140} signature length 43.42, html5 player vflU6l_su
[youtube] {171} signature length 43.42, html5 player vflU6l_su
[youtube] {249} signature length 43.42, html5 player vflU6l_su
[youtube] {250} signature length 43.42, html5 player vflU6l_su
[youtube] {251} signature length 43.42, html5 player vflU6l_su
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r4---sn-4g5e6n7r.googlevideo.com/videoplayback?id=o-AIIq3a_x_iJfwuZyIGMRVpMKaAgT3CP1cFCAXS2dD98C&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&itag=248&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-4g5e6n7r%2Csn-4g5ednle&ms=au%2Crdu&mv=m&pl=20&ei=R5rFXPfiENS9gAfH0baoBg&gcr=de&initcwndbps=758750&mime=video%2Fwebm&gir=yes&clen=4191013&dur=141.000&lmt=1539718325458723&mt=1556453805&fvip=4&keepalive=yes&c=WEB&txp=2301222&ip=94.217.122.225&ipbits=0&expire=1556475559&sparams=ip%2Cipbits%2Cexpire%2Cid%2Caitags%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cgcr%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&key=yt8&signature=F0FE510D228EA71A16A9988945039364F6D15735.B1E6126DC711B06EE445EBCB9C21A83CDC3154B6&ratebypass=yes'
[download] Destination: Sick Shoes-dbGS7gWmJZA.f248.webm
[download] 100% of 4.00MiB in 00:05
[debug] Invoking downloader on u'https://r4---sn-4g5e6n7r.googlevideo.com/videoplayback?id=o-AIIq3a_x_iJfwuZyIGMRVpMKaAgT3CP1cFCAXS2dD98C&itag=171&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-4g5e6n7r%2Csn-4g5ednle&ms=au%2Crdu&mv=m&pl=20&ei=R5rFXPfiENS9gAfH0baoBg&gcr=de&initcwndbps=758750&mime=audio%2Fwebm&gir=yes&clen=2345288&dur=141.056&lmt=1539717933516874&mt=1556453805&fvip=4&keepalive=yes&c=WEB&txp=2301222&ip=94.217.122.225&ipbits=0&expire=1556475559&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cgcr%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&key=yt8&signature=C821A85387AC7380C874287A44633E19C68AA464.914E99A1013EAF35DE183655957CED19F308388D&ratebypass=yes'
[download] Destination: Sick Shoes-dbGS7gWmJZA.f171.webm
[download] 100% of 2.24MiB in 00:03
[ffmpeg] Merging formats into "Sick Shoes-dbGS7gWmJZA.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Sick Shoes-dbGS7gWmJZA.f248.webm' -i 'file:Sick Shoes-dbGS7gWmJZA.f171.webm' -c copy -map '0:v:0' -map '1:a:0' 'file:Sick Shoes-dbGS7gWmJZA.temp.webm'
ERROR: "debug"
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2054, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: "debug"`

This also happens with other videos.

**Comment by rautamiekka** [comment]
Works perfectly here:
```
C:\Users\jaervinen>\ProgramData\Anaconda3\python.exe K:\_DOWNLOADS_\youtube-dl.pyc --verbose --ignore-config "https://www.youtube.com/watch?v=dbGS7gWmJZA"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--ignore-config', 'https://www.youtube.com/watch?v=dbGS7gWmJZA']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.7.2 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] dbGS7gWmJZA: Downloading webpage
[youtube] dbGS7gWmJZA: Downloading video info webpage
[youtube] {18} signature length 43.42, html5 player vflU6l_su
[youtube] dbGS7gWmJZA: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vflU6l_su/en_US/base.js
[youtube] {137} signature length 43.42, html5 player vflU6l_su
[youtube] {248} signature length 43.42, html5 player vflU6l_su
[youtube] {136} signature length 43.42, html5 player vflU6l_su
[youtube] {247} signature length 43.42, html5 player vflU6l_su
[youtube] {135} signature length 43.42, html5 player vflU6l_su
[youtube] {244} signature length 43.42, html5 player vflU6l_su
[youtube] {134} signature length 43.42, html5 player vflU6l_su
[youtube] {243} signature length 43.42, html5 player vflU6l_su
[youtube] {133} signature length 43.42, html5 player vflU6l_su
[youtube] {242} signature length 43.42, html5 player vflU6l_su
[youtube] {160} signature length 43.42, html5 player vflU6l_su
[youtube] {278} signature length 43.42, html5 player vflU6l_su
[youtube] {140} signature length 43.42, html5 player vflU6l_su
[youtube] {171} signature length 43.42, html5 player vflU6l_su
[youtube] {249} signature length 43.42, html5 player vflU6l_su
[youtube] {250} signature length 43.42, html5 player vflU6l_su
[youtube] {251} signature length 43.42, html5 player vflU6l_su
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r4---sn-qo5-ixas.googlevideo.com/videoplayback?id=o-AFTMCQ0DPlWE7uylFVQNqqcojFY9BcatVeKlAZyzVBJY&itag=18&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-qo5-ixas%2Csn-5go7ynez&ms=au%2Crdu&mv=m&pl=21&ei=T5zFXOHePIza7QT1vYGIDA&gcr=fi&initcwndbps=857500&mime=video%2Fmp4&gir=yes&clen=2783440&ratebypass=yes&dur=141.107&lmt=1539717126814503&mt=1556454385&fvip=4&c=WEB&txp=2311222&ip=176.93.196.187&ipbits=0&expire=1556476080&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cgcr%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&key=yt8&signature=8498D2A7C854A3C40B769E595B09B6758BABE290.C8DCB163284C8419C6E989909762CD088205E028'
[download] Destination: Sick Shoes-dbGS7gWmJZA.mp4
[download] 100% of 2.65MiB in 00:02
```

**Comment by yetipenguin** [comment]
@dstftw Could you provide a link to the original issue as you closed this one as a duplicate? Thank you! :-)
