### ISSUE TITLE
youtube-dl doesn't download youtube videos in proper resolution and format

### ISSUE THREAD

**Issue by IoanPaleru** [ytdl-org/youtube-dl#20887]
Hi, when trying to download these links: "https://www.youtube.com/watch?v=ezopeXwUukQ", "https://www.youtube.com/watch?v=1WjxBLgsQy8", and "https://www.youtube.com/watch?v=0DdPkt2QOKk" using the "-v --ignore-errors --format "best[ext=mp4][height<=720]" -o %(title)s.%(ext)s --cache-dir "C:\Users\Computer User\Music\youtube-dl and libav 11.3 files cache and downloads" --batch-file Files.txt" command, youtube-dl downloads them as 540x360 and 480x320 mp4, or 720x480 mkv files, but other youtube downloaders are able to download and convert those same files from the available streams as 720x480 mp4 files. It seems that issue is that youtube-dl isn't able to download and convert the proper available streams and merge them to create mp4 files, so is there a way to fix that? If other youtube downloaders can do that, then why can't youtube-dl? Thanks.

**Comment by dstftw** [comment]
Read [FAQ](https://github.com/ytdl-org/youtube-dl#format-selection) on what does `best` mean.

**Comment by IoanPaleru** [comment]
Hi. You provided me with the "--format "best[ext=mp4][height<=720]" command to use to download and convert files as 720p mp4 a while ago when I wanted help with that, because I didn't know which command to use. Everything was working fine and youtube-dl was able to download videos properly and convert them in that format until recently. Can you please tell me what command to use for youtube-dl to download videos in 720p (in this case, in the available 720x480 resolution), and mux the available streams using ffmpeg into an mp4 file? So far, I've only found out how to get youtube-dl to download the videos in the correct 720x480 available resolution, but it saves them as mkv files, and I want to find out how to get it to use ffmpeg to convert them to mp4 files. I'd really appreciate it, since the faq is very confusting for average computer users. Youtube-dl is a very good program by the way, once people know how to use it. Thank you.

**Comment by WolfganP** [comment]
Use the -F param and see which formats are available for your video, then choose between availables

**Comment by IoanPaleru** [comment]
When using the --list-formats command, it says that there's a 720x480 mp4 video stream available. Up until recently, I was using the "--format "best[ext=mp4][height<=720]" command that dstftw gave me a while ago, and it was downloading and converting 720p mp4 files just fine, but now it isn't working anymore, it's only downloading 720x480 mkv files, or 540x360 and 480x320 mp4 files for these links: "https://www.youtube.com/watch?v=ezopeXwUukQ", "https://www.youtube.com/watch?v=1WjxBLgsQy8", and "https://www.youtube.com/watch?v=0DdPkt2QOKk". Other youtube downloaders can download and convert these files as 720x480 mp4 files just fine. What command do I use to get youtube-dl to download it, merge it with an m4a audio stream, and save it as an mp4 instead of an mkv? I'd appreciate some help if anyone knows how to do that. Let me know if you need more information. Thanks.

C:\Users\Computer User\Music\youtube-dl and libav 11.3 files cache and downloads>youtube-dl --list-formats https://www.youtube.com/watch?v=ezopeXwUukQ
[youtube] ezopeXwUukQ: Downloading webpage
[youtube] ezopeXwUukQ: Downloading video info webpage
[info] Available formats for ezopeXwUukQ:
format code  extension  resolution note
249          webm       audio only DASH audio   59k , opus @ 50k, 3.18MiB
250          webm       audio only DASH audio   76k , opus @ 70k, 4.14MiB
171          webm       audio only DASH audio  122k , vorbis@128k, 7.17MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 8.35MiB
251          webm       audio only DASH audio  149k , opus @160k, 8.17MiB
278          webm       216x144    144p   83k , webm container, vp9, 30fps, video only, 4.97MiB
160          mp4        216x144    144p  103k , avc1.4d400c, 30fps, video only, 4.16MiB
242          webm       360x240    240p  194k , vp9, 30fps, video only, 9.73MiB
133          mp4        360x240    240p  210k , avc1.4d400d, 30fps, video only, 7.40MiB
243          webm       540x360    360p  357k , vp9, 30fps, video only, 17.27MiB
134          mp4        540x360    360p  547k , avc1.4d401e, 30fps, video only, 17.11MiB
244          webm       720x480    480p  643k , vp9, 30fps, video only, 29.90MiB
135          mp4        720x480    480p 1004k , avc1.4d401e, 30fps, video only, 34.16MiB
18           mp4        540x360    medium , avc1.42001E, mp4a.40.2@ 96k, 32.90MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 49.70MiB (best)

C:\Users\Computer User\Music\youtube-dl and libav 11.3 files cache and downloads>

**Comment by WolfganP** [comment]
That's your answer: 720x480 means width = 720, height = 480; "--format "best[ext=mp4][height<=720]" just fallback to get the best stream available below your criteria (format 135 = 480p)

**Comment by IoanPaleru** [comment]
Using the "--format "best[ext=mp4][height<=720]" command, youtube-dl only downloads 540x360 or 480x320 mp4 files, but it used to be able to download the 720x480 mp4 file (if 720p wasn't available). With a different command, youtube-dl can download the available 720x480 file, but it only outputs it as an mkv instead of mp4 file with that resolution. Do you know which command to use other than the one I've been using, to get youtube-dl to download either 720p or the next best available quality (which in this case is 480p), but output it as an mp4 instead of mkv file? Thanks.

**Comment by WolfganP** [comment]
You have plenty of examples about format selection in https://github.com/ytdl-org/youtube-dl#format-selection , probably good to use the precedence operator '/' for controlled fallbacks. You may force what you want in your specific video as: -f 135+140 --merge-output-format mp4
Plus the program is also triggering an error as your last argument is 'pause'

**Comment by IoanPaleru** [comment]
Ok, thanks, but youtube-dl used to do all of that automatically and download and format videos in the correct resolutions with the command I was using.

**Comment by vjmass** [comment]
Yes you're right I've been downloading videos for my club performances, and the best way without consuming a lot of resources from the computer for me it's to download thru the terminal
I've come up with this options for my configuration file to make my life easier, which it's best video from mp4 with best audio from m4a merged to a MP4 file

-f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 -o ~/Downloads/$

I edit the youtube-dl.conf file inside /etc/
so when you open the terminal you type

cd /etc/

then you edit the conf file with the editing tool from terminal which it's nano, with super user credentials

sudo nano youtube-dl.conf

it's going to ask for the password and the file it'll be empty, type your options and the next time you hit youtube-dl just put the URL to your youtube video and voila it'll be all automatic no further options needed, remember to close and save the file just hit Control + X (Close) and it'll ask you to save the file, press Y on the keyboard and then ENTER, that's it.

Hope it helps!
