### ISSUE TITLE
DRM protected

### ISSUE THREAD

**Issue by Ruppi007** [ytdl-org/youtube-dl#20885]
Checklist
[ x] I'm reporting a broken site support
[ x] I've verified that I'm running youtube-dl version 2019.04.24
[ x] I've checked that all provided URLs are alive and playable in a browser
[ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
[x ] I've searched the bugtracker for similar issues including closed ones

Verbose log

C:\Users\Stephan\Desktop>youtube-dl -v https://www.tvnow.at/serien/buffy-im-bann-der-daemonen-17265/staffel-1/episode-1-das-zentrum-des-boesen-1498886
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.tvnow.at/serien/buffy-im-bann-der-daemonen-17265/staffel-1/episode-1-das-zentrum-des-boesen-1498886']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[TVNow] buffy-im-bann-der-daemonen/das-zentrum-des-boesen: Downloading JSON metadata
[TVNow] 1498886: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[TVNow] 1498886: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden
[TVNow] 1498886: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[TVNow] 1498886: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[TVNow] 1498886: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 404: Not Found
[TVNow] 1498886: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
ERROR: Video 1498886 is DRM protected
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\tvnow.py", line 170, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\tvnow.py", line 64, in _extract_video
youtube_dl.utils.ExtractorError: Video 1498886 is DRM protected

Is it possible to download a DRM Protected Video?

**Comment by dstftw** [comment]
Not possible.
