### ISSUE TITLE
BRIGHTCOVE / RMC DECOUVERTE

### ISSUE THREAD

**Issue by coveroid** [ytdl-org/youtube-dl#20895]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.04.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

> C:\wamp64\www\ytdl>youtube-dl -j https://rmcdecouverte.bfmtv.com/mediaplayer-direct/ -v
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['-j', 'https://rmcdecouverte.bfmtv.com/mediaplayer-direct/', '-v']
> [debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
> [debug] youtube-dl version 2019.04.24
> [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
> [debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1
> [debug] Proxy map: {}
> [debug] Default format spec: bestvideo+bestaudio/best
> {"tbr": 1096.0, "extractor": "brightcove:new", "webpage_url": "http://players.brightcove.net/1969646226001/default_default/index.html?videoId=5500352445001#__youtubedl_smuggle=%7B%22geo_countries%22%3A+%5B%22FR%22%5D%7D", "height": 480, "tags": ["applications mobiles", "live"], "protocol": "m3u8_native", "acodec": "mp4a.40.2", "id": "5500352445001", "upload_date": "20170710", "display_id": "5500352445001", "description": "RMCDecouverte Live KB Applications", "subtitles": {}, "webpage_url_basename": "index.html", "format_id": "hls-1096", "formats": [{"format": "hls-296 - 320x180", "vcodec": "avc1.66.30", "height": 180, "preference": null, "protocol": "m3u8_native", "acodec": "mp4a.40.2", "ext": "mp4", "width": 320, "http_headers": {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0", "Cookie": "_alid_=E2+cVTtE6CfBwlQGc0lZ6w==", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Encoding": "gzip, deflate", "X-Forwarded-For": "90.11.68.178", "Accept-Language": "en-us,en;q=0.5", "Accept": "application/json;pk=BCpkADawqM2ebty4iw7jJs6V1OBbhzTqkxifyhMXPza3wJXdLBPe88u5glATJGkuWz2olkJ8-KExAEkrL7iaamh3HDwQAk7yFWkCsEQAZk2p1jTIAcPwx_kf80kBg8Vt3-ORUmUD5X_bBoYK"}, "format_id": "hls-296", "tbr": 296.0, "url": "https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/index_200_av-p.m3u8?sd=10&rebase=on&id=AgAlqfnmWN1TZwTBxlzrXruyz7HhPan64hjFjTZ4l%2fcgUzC6ejTHMl7LBzUrIFpOehiVezFtigVOlw%3d%3d&hdntl=exp=1556615812~acl=%2fi%2f*~data=hdntl~hmac=3b244f6bb9251b89ddf5d1aa7e504b275068c71689c0fad74fa0c1c4a22b56bc", "fps": null, "manifest_url": "https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/master.m3u8?__nn__=5375862360001&hdnea=st=1556528400~exp=1556532000~acl=/i/*~hmac=db8f9fd0870db22d2515c891db018a53a173f61e04844021121b97cc7dfaa8f1"}, {"format": "hls-696 - 512x288", "vcodec": "avc1.77.30", "height": 288, "preference": null, "protocol": "m3u8_native", "acodec": "mp4a.40.2", "ext": "mp4", "width": 512, "http_headers": {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0", "Cookie": "_alid_=E2+cVTtE6CfBwlQGc0lZ6w==", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Encoding": "gzip, deflate", "X-Forwarded-For": "90.11.68.178", "Accept-Language": "en-us,en;q=0.5", "Accept": "application/json;pk=BCpkADawqM2ebty4iw7jJs6V1OBbhzTqkxifyhMXPza3wJXdLBPe88u5glATJGkuWz2olkJ8-KExAEkrL7iaamh3HDwQAk7yFWkCsEQAZk2p1jTIAcPwx_kf80kBg8Vt3-ORUmUD5X_bBoYK"}, "format_id": "hls-696", "tbr": 696.0, "url": "https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/index_600_av-p.m3u8?sd=10&rebase=on&id=AgAlqfnmWN1TZwTBxlzrXruyz7HhPan64hjFjTZ4l%2fcgUzC6ejTHMl7LBzUrIFpOehiVezFtigVOlw%3d%3d&hdntl=exp=1556615812~acl=%2fi%2f*~data=hdntl~hmac=3b244f6bb9251b89ddf5d1aa7e504b275068c71689c0fad74fa0c1c4a22b56bc", "fps": null, "manifest_url": "https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/master.m3u8?__nn__=5375862360001&hdnea=st=1556528400~exp=1556532000~acl=/i/*~hmac=db8f9fd0870db22d2515c891db018a53a173f61e04844021121b97cc7dfaa8f1"}, {"format": "hls-1096 - 848x480", "vcodec": "avc1.77.30", "height": 480, "preference": null, "protocol": "m3u8_native", "acodec": "mp4a.40.2", "ext": "mp4", "width": 848, "http_headers": {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0", "Cookie": "_alid_=E2+cVTtE6CfBwlQGc0lZ6w==", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Encoding": "gzip, deflate", "X-Forwarded-For": "90.11.68.178", "Accept-Language": "en-us,en;q=0.5", "Accept": "application/json;pk=BCpkADawqM2ebty4iw7jJs6V1OBbhzTqkxifyhMXPza3wJXdLBPe88u5glATJGkuWz2olkJ8-KExAEkrL7iaamh3HDwQAk7yFWkCsEQAZk2p1jTIAcPwx_kf80kBg8Vt3-ORUmUD5X_bBoYK"}, "format_id": "hls-1096", "tbr": 1096.0, "url": "https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/index_1000_av-p.m3u8?sd=10&rebase=on&id=AgAlqfnmWN1TZwTBxlzrXruyz7HhPan64hjFjTZ4l%2fcgUzC6ejTHMl7LBzUrIFpOehiVezFtigVOlw%3d%3d&hdntl=exp=1556615812~acl=%2fi%2f*~data=hdntl~hmac=3b244f6bb9251b89ddf5d1aa7e504b275068c71689c0fad74fa0c1c4a22b56bc", "fps": null, "manifest_url": "https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/master.m3u8?__nn__=5375862360001&hdnea=st=1556528400~exp=1556532000~acl=/i/*~hmac=db8f9fd0870db22d2515c891db018a53a173f61e04844021121b97cc7dfaa8f1"}], "http_headers": {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0", "Cookie": "_alid_=E2+cVTtE6CfBwlQGc0lZ6w==", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Encoding": "gzip, deflate", "X-Forwarded-For": "90.11.68.178", "Accept-Language": "en-us,en;q=0.5", "Accept": "application/json;pk=BCpkADawqM2ebty4iw7jJs6V1OBbhzTqkxifyhMXPza3wJXdLBPe88u5glATJGkuWz2olkJ8-KExAEkrL7iaamh3HDwQAk7yFWkCsEQAZk2p1jTIAcPwx_kf80kBg8Vt3-ORUmUD5X_bBoYK"}, "duration": 0.0, "manifest_url": "https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/master.m3u8?__nn__=5375862360001&hdnea=st=1556528400~exp=1556532000~acl=/i/*~hmac=db8f9fd0870db22d2515c891db018a53a173f61e04844021121b97cc7dfaa8f1", "fulltitle": "RMCDecouverte Live KB 2019-04-29 19:16", "width": 848, "format": "hls-1096 - 848x480", "timestamp": 1499688095, "requested_subtitles": null, "playlist_index": null, "playlist": null, "is_live": true, "preference": null, "thumbnail": null, "ext": "mp4", "uploader_id": "1969646226001", "_filename": "RMCDecouverte Live KB 2019-04-29 19_16-5500352445001.mp4", "url": "https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/index_1000_av-p.m3u8?sd=10&rebase=on&id=AgAlqfnmWN1TZwTBxlzrXruyz7HhPan64hjFjTZ4l%2fcgUzC6ejTHMl7LBzUrIFpOehiVezFtigVOlw%3d%3d&hdntl=exp=1556615812~acl=%2fi%2f*~data=hdntl~hmac=3b244f6bb9251b89ddf5d1aa7e504b275068c71689c0fad74fa0c1c4a22b56bc", "extractor_key": "BrightcoveNew", "title": "RMCDecouverte Live KB 2019-04-29 19:16", "vcodec": "avc1.77.30", "fps": null}

 <more lines>

## Description

I'm sorry to reopen the issues https://github.com/ytdl-org/youtube-dl/issues/20894 but we cant play any link if we do like on the answer or please exeplain how to do 

```
C:\wamp64\www\ytdl>youtube-dl -F https://rmcdecouverte.bfmtv.com/mediaplayer-direct/
[RMCDecouverte] mediaplayer-direct: Downloading webpage
[brightcove:new] 5500352445001: Downloading webpage
[brightcove:new] 5500352445001: Downloading JSON metadata
[brightcove:new] 5500352445001: Downloading m3u8 information
[info] Available formats for 5500352445001:
format code  extension  resolution note
hls-296      mp4        320x180     296k , avc1.66.30, mp4a.40.2
hls-696      mp4        512x288     696k , avc1.77.30, mp4a.40.2
hls-1096     mp4        848x480    1096k , avc1.77.30, mp4a.40.2 (best)

C:\wamp64\www\ytdl>youtube-dl -f hls-296 -g https://rmcdecouverte.bfmtv.com/mediaplayer-direct/
https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/index_200_av-p.m3u8?sd=10&rebase=on&id=AgAlqfnmWN1Tlo7OxlxKm9VP9Ms346KMriW+0Ew5%2f1gitsDmzmKGfeQew%2fl8recE9N9w%2fQW%2fjqOPhA%3d%3d&hdntl=exp=1556619278~acl=%2fi%2f*~data=hdntl~hmac=08eb72b32085bac74143367e0f64dd2260310a2e54afb1ca5c31f97a73e015f4

C:\wamp64\www\ytdl>ffplay -i https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/index_200_av-p.m3u8?sd=10&rebase=on&id=AgAlqfnmWN1Tlo7OxlxKm9VP9Ms346KMriW+0Ew5%2f1gitsDmzmKGfeQew%2fl8recE9N9w%2fQW%2fjqOPhA%3d%3d&hdntl=exp=1556619278~acl=%2fi%2f*~data=hdntl~hmac=08eb72b32085bac74143367e0f64dd2260310a2e54afb1ca5c31f97a73e015f4
ffplay version 4.1.1 Copyright (c) 2003-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[https @ 0000029b7ce79e40] HTTP error 403 Forbiddenq=    0B f=0/0
https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/index_200_av-p.m3u8?sd=10: Server returned 403 Forbidden (access denied)
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0
'rebase' is not recognized as an internal or external command,
operable program or batch file.
'id' is not recognized as an internal or external command,
operable program or batch file.
'hdntl' is not recognized as an internal or external command,
operable program or batch file.

```
The command sees working but after all the link are not playeable (only check for live stream) , same from the original website as `http://players.brightcove.net/1969646226001/default_default/index.html?videoId=5500352445001`, So the workaround is not anymore working unfortunately : https://github.com/ytdl-org/youtube-dl/issues/18595

**Comment by dstftw** [comment]
>- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
