### ISSUE TITLE
Brightcove Rmc decouverte

### ISSUE THREAD

**Issue by coveroid** [ytdl-org/youtube-dl#20898]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.04.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\wamp64\www\ytdl>youtube-dl -F https://rmcdecouverte.bfmtv.com/mediaplayer-direct/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://rmcdecouverte.bfmtv.com/mediaplayer-direct/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1
[debug] Proxy map: {}
[RMCDecouverte] mediaplayer-direct: Downloading webpage
[debug] Using fake IP 90.87.247.160 (FR) as X-Forwarded-For.
[brightcove:new] 5500352445001: Downloading webpage
[brightcove:new] 5500352445001: Downloading JSON metadata
[brightcove:new] 5500352445001: Downloading m3u8 information
[info] Available formats for 5500352445001:
format code  extension  resolution note
hls-296      mp4        320x180     296k , avc1.66.30, mp4a.40.2
hls-696      mp4        512x288     696k , avc1.77.30, mp4a.40.2
hls-1096     mp4        848x480    1096k , avc1.77.30, mp4a.40.2 (best)

C:\wamp64\www\ytdl>youtube-dl -f hls-296 -g https://rmcdecouverte.bfmtv.com/mediaplayer-direct/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'hls-296', '-g', 'https://rmcdecouverte.bfmtv.com/mediaplayer-direct/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1
[debug] Proxy map: {}
https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/index_200_av-p.m3u8?sd=10&rebase=on&id=AgA6puaqlYdQRFrkxlzqR5O0r0EKORVN7L+xnnpkkngDeuJlKpAtnYf1NpdCz55gm6PJ%2fvCBFXYncw%3d%3d&hdntl=exp=1556624858~acl=%2fi%2f*~data=hdntl~hmac=ec0462d64c8ed3e5e9f951f8f51d3ad78eaf09740fb40c5fccea2953d6d15162

C:\wamp64\www\ytdl>ffplay -i https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/index_200_av-p.m3u8?sd=10&rebase=on&id=AgA6puaqlYdQRFrkxlzqR5O0r0EKORVN7L+xnnpkkngDeuJlKpAtnYf1NpdCz55gm6PJ%2fvCBFXYncw%3d%3d&hdntl=exp=1556624858~acl=%2fi%2f*~data=hdntl~hmac=ec0462d64c8ed3e5e9f951f8f51d3ad78eaf09740fb40c5fccea2953d6d15162
ffplay version 4.1.1 Copyright (c) 2003-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[https @ 000001daa8849d00] HTTP error 403 Forbiddenq=    0B f=0/0
https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/index_200_av-p.m3u8?sd=10: Server returned 403 Forbidden (access denied)
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0
'rebase' is not recognized as an internal or external command,
operable program or batch file.
'id' is not recognized as an internal or external command,
operable program or batch file.
'hdntl' is not recognized as an internal or external command,
operable program or batch file.
```

## Description

I'm sorry to reopen the issues (fourth time ..., , Do you really want solve issue or just close it ?) #20894  We cant play any link, if we do like on the answer, or please explain us how to do ? 

The command seems working but after, all the link are not playeable (only check for live stream) , same from the original website (brightcove) , So the workaround is not anymore working unfortunately , and to be clear my IP adress is in France, so its not a geo-restrictions problem
Thanks for your support

**Comment by eMPee584** [comment]
U need to **quote** the 'URL'! You can see at the end of shell output that it interprets fragments of the URL as distinct commands which it unsuccessfully tries to execute..
> ```
> C:\wamp64\www\ytdl>ffplay -i https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/index_200_av-p.m3u8?sd=10&rebase=on&id=AgA6puaqlYdQRFrkxlzqR5O0r0EKORVN7L+xnnpkkngDeuJlKpAtnYf1NpdCz55gm6PJ%2fvCBFXYncw%3d%3d&hdntl=exp=1556624858~acl=%2fi%2f*~data=hdntl~hmac=ec0462d64c8ed3e5e9f951f8f51d3ad78eaf09740fb40c5fccea2953d6d15162
> […]
> [https @ 000001daa8849d00] HTTP error 403 Forbiddenq=    0B f=0/0
> https://nextmediahdslive-lh.akamaihd.net/i/RMCDECOUVERTE_KB@300868/index_200_av-p.m3u8?sd=10: Server returned 403 Forbidden (access denied)
>     nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0
> 'rebase' is not recognized as an internal or external command,
> operable program or batch file.
> 'id' is not recognized as an internal or external command,
> operable program or batch file.
> 'hdntl' is not recognized as an internal or external command,
> operable program or batch file.
> ```

**Comment by eMPee584** [comment]
@coveroid 
"For Windows you have to use the double quotes" ( https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command )
