### ISSUE TITLE
extractor https://www.televizeseznam.cz/

### ISSUE THREAD

**Issue by tomasyk** [ytdl-org/youtube-dl#20900]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.04.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
Hi, I am unable to download video from this site:
https://www.televizeseznam.cz
e.g. https://www.televizeseznam.cz/video/adost/bonus-proc-ministerstvo-zivotniho-prostredi-cr-nechce-zavest-zalohovani-pet-lahvi-63903108
It seems it is somehow connected to www.stream.cz, but youtube-dl did not find StreamCZ extractor and I am unable to force it.
I propose to add new extractor for this site or modify StreamCZ to recognize this site.

**Comment by Modryz** [comment]
+1

**Comment by schunka** [comment]
Can someone do anything about this and process it? This is taking really long with no feedback at all.
