### ISSUE TITLE
show latest version prominently on website

### ISSUE THREAD

**Issue by TomRoche** [ytdl-org/youtube-dl#20905]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I recently had a problem with your usually-excellent product, which told me

    ERROR: oZmmPVg-yz0: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update.

I checked the latter link, but am using Debian, hence that was useless. Eventually I just reinstalled, but, IMHO, *It Would Be Useful* to

1. show the current-release-version stamp (currently=`2019.04.30`) prominently on (e.g.)

* the GitHub "homepage", e.g. @ https://github.com/ytdl-org/youtube-dl#installation
* the [update page](https://yt-dl.org/update) referenced in the stock error message
* the [latest-version item on the CONTRIBUTING page](https://github.com/ytdl-org/youtube-dl/blob/master/CONTRIBUTING.md#are-you-using-the-latest-version)

2. update the version stamp in those docs when building new releases

This should also be easy (depending on your build process), since you seem to be updating the new-issue template with the current-version-stamp already.

**Comment by dstftw** [comment]
This will barely have any effect. There are clear instructions and current version in the new issue template - nobody reads it.
