### ISSUE TITLE
Default to downloading the correct framerate

### ISSUE THREAD

**Issue by spongbros** [ytdl-org/youtube-dl#20926]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Currently, `bestvideo`, the default option, does not download the best version of the video. As noted in https://github.com/ytdl-org/youtube-dl/issues/20924#issuecomment-488352225, downloading a 720p60 YouTube video with youtube-dl produces a 720p30 file - equivalent to throwing away half of the video content. youtube-dl should default to downloading videos in their correct framerate, rather than arbitrarily forcing lower framerates.

**Comment by dstftw** [comment]
This is expected behavior since 30 fps video has higher bitrate.
