### ISSUE TITLE
ITV gets on screen signed language video instead of a normal unsigned video

### ISSUE THREAD

**Issue by suFDHAI78fyw78q09Y98yfd** [ytdl-org/youtube-dl#20936]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe" --geo-bypass-country "GB" --ignore-config -v --all-subs --sub-format "vtt" --sub-lang "en" --fixup "never" -f "best" "https://www.itv.com/hub/the-professionals/L0845a0044"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--geo-bypass-country', 'GB', '--ignore-config', '-v
', '--all-subs', '--sub-format', 'vtt', '--sub-lang', 'en', '--fixup', 'never',
'-f', 'best', 'https://www.itv.com/hub/the-professionals/L0845a0044']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.04.30
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-91691-g962c931-Reino, ffprobe N-91691-g962c931-Re
ino, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP ok (GB) as X-Forwarded-For.
[ITV] L0845a0044: Downloading webpage
[ITV] L0845a0044: Downloading XML
WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[ITV] L0845a0044: Downloading JSON metadata
[ITV] L0845a0044: Downloading m3u8 information
[debug] Invoking downloader on 'https://itvpnpdotcom-a.akamaihd.net/IMM-00054-00
5-003/18/1/VAR012/IMM-00054-005-003_18_1_VAR012.ism/IMM-00054-005-003_18_1_VAR01
2-audio=128000-video=1503019.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 236
[download] Destination: Hijack-L0845a0044.mp4
[download] 100% of 562.01MiB in 04:22
```

## Description

There are two picture placements for the same video on the web page. Both insert placements have the same ID number L0845a0044 only. When download this Youtube-dl downloads an on screen signed language video. Needing the normal non on screen signed video but unable to get or unknown how to as video has the same ID on the web page.

**Comment by remitamine** [comment]
youtube-dl downloads the same video that can be viewed in the browser.
provide instruction or screenshot on how to access the normal version(without sign language).

**Comment by suFDHAI78fyw78q09Y98yfd** [comment]
As said the page has two pictures for the same episode mouse over each and they both show "L0845a0044" and that is all that can be chosen. Mention in case some extra parsing can be done background to see if exists two video under same ID. If so for us to have option to get signed or non signed. Unknown if you have come by this yet or is something new the broadcasters are doing.

Maybe there error I though but why two picture placements on not one but sometimes a few videos. But always both picture placements for the show will have the same ID.

Appreciated if without ID nothing can be done but is an opportunity to look at web page and parsing ID to see if it is something new the broadcasters are doing. Not so beneficial if all becomes like this.

NSFW please indicate what needs editing and which button is the edit button to edit it.

**Comment by suFDHAI78fyw78q09Y98yfd** [comment]
NSFW done a search for its meaning.

Not safe for work (often shortened to the acronym NSFW) is an Internet slang or shorthand used to mark URLs and hyperlinks which link to videos or websites pages containing nudity, intense sexuality, profanity, violence or other potentially disturbing subject matter, which the viewer may not wish to be seen looking at in a public or formal environment, including a workplace or school.

**Comment by remitamine** [comment]
Provide **Clear** Instructions or Screenshots on how to access the normal version(without sign language).
