### ISSUE TITLE
  [question only]. Playlists. Eventual special characters. Assured ban.

### ISSUE THREAD

**Issue by avagraha** [ytdl-org/youtube-dl#20953]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERe

Hi, perhaps jq.exe and sed.exe (syntax error with " and '' and ' : but one of 
these is needed when the URL has a "&"...) are 
not required for my purpose and YTDL maybe the desired working solution (?), 
anyway what to do to be able to download the entire playlist into a specific 
folder...without be banned due to the high number of requests? is TYDL able 
to do that?

source with 275 videos:

https://www.youtube.com/playlist?list=PLKGVLbbpbIUR5UXZDAERugDq6iZoE0QgD&fbclid=IwAR29-kHf4-54cNBs1j1KivoESJTVZ2qooFbc_7FwOVos49rpybrxDZm0Ai8

thanks a lot for suggestions.

PS:
While doing
--dump-json -i 
"PLKGVLbbpbIUR5UXZDAERugDq6iZoE0QgD&fbclid=IwAR29-kHf4-54cNBs1j1KivoESJTVZ2qooFbc_7FwOVos49rpybrxDZm0Ai8"
I got an one-kilometer-long log without any space...a big nonsense for my 
purpose,
instead this maybe helpful for other playlists (i.e. when the titles of each 
video are different and you have to establish what videos you want):
-i --get-filename --skip-download 
"PLKGVLbbpbIUR5UXZDAERugDq6iZoE0QgD&fbclid=IwAR29-kHf4-54cNBs1j1KivoESJTVZ2qooFbc_7FwOVos49rpybrxDZm0Ai8"

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient

**Comment by avagraha** [comment]
1)
Clicking on your link I go:
https://postimg.cc/625mB9f0

2) your reply here (and the purpose of the collaborator) was itself 
sufficient too, therefore I asked:
https://github.com/ytdl-org/youtube-dl/pull/20845#issuecomment-487124064
