### ISSUE TITLE
Found a Bug when try extract videos

### ISSUE THREAD

**Issue by Calistu** [ytdl-org/youtube-dl#20969]
ERROR: "Video-Link": "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1624, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: "Video-Link": "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jameswilsongrant** [comment]
Some here, looks to be happening with all videos (vevo or non).

`$ youtube-dl --verbose https://www.youtube.com/watch?v=oJnF5VxTO5g
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=oJnF5VxTO5g']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.18
[debug] Git HEAD: e0b5b4e
[debug] Python version 3.5.2 (CPython) - Darwin-18.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] oJnF5VxTO5g: Downloading webpage
[youtube] oJnF5VxTO5g: Downloading video info webpage
ERROR: oJnF5VxTO5g: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/ryanm/Desktop/dlbot/venv/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/Users/ryanm/Desktop/dlbot/venv/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/Users/ryanm/Desktop/dlbot/venv/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1693, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: oJnF5VxTO5g: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ 
`

**Comment by jameswilsongrant** [comment]
Update youtube-dl with youtube-dl -U

I found this was an issue in an older version I had installed in a virtual environment but a fresh upgrade cleared it.

**Comment by lestjoel11** [comment]
Sorry but do you mind elaborating cause I'm using the Persepolis Download manager and I get this same error, there's no existing youtube-dl.exe in the persepolis download manager folder to update, where do I find the exe to update?
Thanks.
