### ISSUE TITLE
SBS 'ERROR: Unable to download XML: <urlopen error [WinError 10060]'

### ISSUE THREAD

**Issue by astrometrics** [ytdl-org/youtube-dl#20962]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

>python -m youtube_dl -v "https://www.sbs.com.au/ondemand/video/306166851616/borgen-a-child-of-denmark"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.sbs.com.au/ondemand/video/306166851616/borgen-a-child-of-denmark']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.04.30
[debug] Python version 3.7.3 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-93755-ga5387f983d, ffprobe N-93755-ga5387f983d
[debug] Proxy map: {}
[SBS] 306166851616: Downloading JSON metadata
ERROR: Unable to download JSON metadata: <urlopen error [WinError 10060] A connection attempt failed because the connect
ed party did not properly respond after a period of time, or established connection failed because connected host has fa
iled to respond> (caused by URLError(TimeoutError(10060, 'A connection attempt failed because the connected party did no
t properly respond after a period of time, or established connection failed because connected host has failed to respond
', None, 10060, None)))
  File "D:\RDUsr\bin\rt\py\v3\x64\lib\site-packages\youtube_dl\extractor\common.py", line 626, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "D:\RDUsr\bin\rt\py\v3\x64\lib\site-packages\youtube_dl\YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "D:\RDUsr\bin\rt\py\v3\x64\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "D:\RDUsr\bin\rt\py\v3\x64\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "D:\RDUsr\bin\rt\py\v3\x64\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\RDUsr\bin\rt\py\v3\x64\lib\site-packages\youtube_dl\utils.py", line 984, in http_open
    req)
  File "D:\RDUsr\bin\rt\py\v3\x64\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)

>python -m youtube_dl --version
2019.04.30

## Description

It's possible to watch the video on chrome, but when downloading with youtube-dl, there's the error above...

**Comment by dstftw** [comment]
Network issue on your side.

**Comment by astrometrics** [comment]
Hi, why would it be "Network issue on your side." (my side) if I can watch the movie on chrome? Isn't that a bit illogical? (thanks everyone for youtube-dl by the way)

**Comment by dstftw** [comment]
Being able watching in Chrome means nothing. Chrome may be configured to use proxy, vpn plugin, etc. As already said network is not available from command line on your side. wget, curl and other won't work as well.
