### ISSUE TITLE
Opposite of --add-metadata

### ISSUE THREAD

**Issue by Fabian42** [ytdl-org/youtube-dl#20977]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I don't want thumbnails and other metadata in my audio files, so it would be nice to not download them at all, instead of having to first download them and then later deleting them with another program.

(Reasoning for not wanting metadata: They are harder to change than file names and some media players prefer metadata like "title" over the file name if there is one, making them show unexpected names or even sort based on them. And for example some music creators have a weird taste for images, so I don't want their thumbnails.)

**Comment by ealgase** [comment]
Just don't use `--add-metadata`?  Files from YouTube don't have built in metadata.

**Comment by Fabian42** [comment]
Ok, then I take back my YouTube example. But for example I just downloaded some music from Bandcamp and it has metadata, including thumbnails.

**Comment by dstftw** [comment]
youtube-dl does not add any metadata until you explicitly tell it to do so. If the original media already contains metadata you can crop it with any tool of your choice by executing it in `--exec`.

**Comment by Fabian42** [comment]
It definitely does. Please reopen.
![image](https://user-images.githubusercontent.com/10481506/57288125-37dcf900-70b9-11e9-89a5-6acb2c0ce3ba.png)

**Comment by Fabian42** [comment]
The command used for that was `youtube-dl -f bestaudio <URL>`.

**Comment by dstftw** [comment]
Once again: this metadata is embedded in file itself by bandcamp.
