### ISSUE TITLE
Mixcloud profile / uploads download not working

### ISSUE THREAD

**Issue by Czechball** [ytdl-org/youtube-dl#20972]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: [u'-x', u'-f', u'bestaudio', u'--audio-format', u'best', u'--add-metadata', u'--embed-thumbnail', u'--metadata-from-title', u'%(artist)s - %(title)s', u'-o', u'/home/czechball/Hudba/%(uploader)s/%(title)s (%(acodec)s - %(abr)skbps).%(ext)s', u'-i']
[debug] Custom config: []
[debug] Command-line args: [u'https://www.mixcloud.com/officialsjc/uploads/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.9
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[mixcloud:user] officialsjc_uploads: Downloading user profile
[download] Downloading playlist: SJC (uploads)
[mixcloud:user] officialsjc_uploads: Download list of uploads (page 1)
[mixcloud:user] playlist SJC (uploads): Downloading 0 videos
[download] Finished downloading playlist: SJC (uploads)
```

## Description

Even tho there are seemingly no errors in the process, youtube-dl won't download any songs when url of a MixCloud profile is used (I tried both https://www.mixcloud.com/[profile]/uploads/ and https://www.mixcloud.com/[profile]/ ). Single shows can be downloaded without any issue.

**Comment by EMMANATT** [comment]
MixCloud profile is used ,,

**Comment by Czechball** [comment]
The "profile" is meant to be a placeholder for an actual username. For example, https://mixcloud.com/czechball/uploads/

**Comment by mtilbury** [comment]
It appears that the issue occurs with [playlists](https://www.mixcloud.com/RedBullThre3style/playlists/tokyo-finalists-2015/) as well. I'm working on a fix now.

**Comment by Czechball** [comment]
The issue still persists in `2019.05.20`

**Comment by moodmosaic** [comment]
Any news on this? :heart:
