### ISSUE TITLE
[shahid] playlist on reverse

### ISSUE THREAD

**Issue by AboSari** [ytdl-org/youtube-dl#20973]
when i want download specify episode from playlist 

EX: 
`youtube-dl https://shahid.mbc.net/ar/series/%D9%81%D9%88%D9%82-%D8%A7%D9%84%D8%B3%D8%AD%D8%A7%D8%A8/series-309369 --playlist-items 1`

--playlist-items is 1, but it's download episode 30

**Comment by remitamine** [comment]
you might want to use:
```
--playlist-reverse               Download playlist videos in reverse order
```
there is nothing we can do, the API does not respect the `order` param.
