### ISSUE TITLE
Could not write header for output file #0

### ISSUE THREAD

**Issue by 1seekr** [ytdl-org/youtube-dl#20987]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.04.30**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
sr:2 /mnt/fs5t/video/uToob/190507 yd -v https://www.bbc.com/news/av/world-europe-40469343/music-loving-dog-upstages-orchestra-in-turkey

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.bbc.com/news/av/world-europe-40469343/music-loving-dog-upstages-orchestra-in-turkey']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.12 (CPython) - Linux-4.10.0-38-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[bbc] music-loving-dog-upstages-orchestra-in-turkey: Downloading webpage
[bbc] p057h4pv: Downloading media selection XML
[bbc] p057h4pv: Downloading m3u8 information
[bbc] p057h4pv: Downloading m3u8 information
[bbc] p057h4pv: Downloading MPD manifest
[bbc] p057h4pv: Downloading m3u8 information
[bbc] p057h4pv: Downloading m3u8 information
[bbc] p057h4pv: Downloading MPD manifest
[bbc] p057h4pv: Downloading m3u8 information
[bbc] p057h4pv: Downloading m3u8 information
[bbc] p057h4pv: Downloading MPD manifest
[bbc] p057h4pv: Downloading m3u8 information
[bbc] p057h4pv: Downloading m3u8 information
[bbc] p057h4pv: Downloading MPD manifest
[download] Downloading playlist: Music-loving dog upstages orchestra
[bbc] playlist Music-loving dog upstages orchestra: Collected 1 video ids (downl
oading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://vod-dash-ww-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd/45c1bc-p057h4pv/vf_p057h4pv_141f68de-f62b-4b98-b3e3-c9182fa4b5d7.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?s=1557201022&e=1557244222&h=6ea81b08bcfb55ffe2fe6ab446433754'
[dashsegments] Total fragments: 15
[download] Destination: Music-loving dog upstages orchestra-p057h4pv.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-video=1570000.mp4
[download] 100% of 10.09MiB in 00:07
[debug] Invoking downloader on u'https://vod-dash-ww-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd/45c1bc-p057h4pv/vf_p057h4pv_141f68de-f62b-4b98-b3e3-c9182fa4b5d7.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?s=1557201022&e=1557244222&h=6ea81b08bcfb55ffe2fe6ab446433754'
[dashsegments] Total fragments: 15
[download] Destination: Music-loving dog upstages orchestra-p057h4pv.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-audio_eng_1=128000.m4a
[download] 100% of 828.40KiB in 00:02
[ffmpeg] Merging formats into "Music-loving dog upstages orchestra-p057h4pv.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Music-loving dog upstages orchestra-p057h4pv.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-video=1570000.mp4' -i 'file:Music-loving dog upstages orchestra-p057h4pv.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-audio_eng_1=128000.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Music-loving dog upstages orchestra-p057h4pv.temp.mp4'
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2054, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args) 
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

## Description

WRITE DESCRIPTION HERE
I'm attempting to download a video from the BBC site.  Seeing that a previous report of this problem resulted in advice to update ffmpeg, I took a look at the version I have installed.  The Synaptic package manager indicates that the version I have is the most recent one available.  The command itself says:

ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609

**Comment by dstftw** [comment]
Outdated ffmpeg.

**Comment by 1seekr** [comment]
Well, the version of ffmpeg I'm using is apparently the latest one in the Ubuntu repository (I'm using Linux Mint, which is based upon Ubuntu).

**Comment by 1seekr** [comment]
CC-kun has kindly pointed me at https://www.itzgeek.com/how-tos/linux/ubuntu-how-tos/how-to-install-ffmpeg-on-ubuntu-18-04-ubuntu-16-04-linux-mint-19.html

I will try using that recipe.
