### ISSUE TITLE
YouTube-DL: %Environment Variables% are NOT properly Detected!

### ISSUE THREAD

**Issue by RangaSE** [ytdl-org/youtube-dl#20988]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
< 05-05-2019 & 19:34:46.86 | C:\Users\admin> youtube-dl[2019.04.30] -ci --yes-playlist --playlist-start 17 --playlist-end 33 --embed-thumbnail -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"  --download-archive Vitalanei_Pidi_(Uptodate-19).txt -o "%TOSHIBA%\%SRIHARI%\SVBCTTD Tamil\Vitalanai Pidi (Uptodate-19)\%(title)s(u%(upload_date)s; %(duration)s; %(height)sp)YT '%(uploader)s'.%(ext)s" https://www.youtube.com/playlist?list=PLAhHqKT2PCdnTfsY4ckgdhcsPvrmsfetq
[youtube:playlist] PLAhHqKT2PCdnTfsY4ckgdhcsPvrmsfetq: Downloading webpage
[download] Downloading playlist: Vitalane Pidi (Uptodate-19)
[youtube:playlist] playlist Vitalane Pidi (Uptodate-19): Downloading 17 videos
[download] Downloading video 1 of 17
[download] Vitalane Pidi | EP 17 | 10-03-19 | SVBC TTD Tamil has already been recorded in archive
[download] Downloading video 2 of 17
[youtube] 0eEqM_2JWCg: Downloading webpage
[youtube] 0eEqM_2JWCg: Downloading video info webpage
ERROR: Error in output template: unsupported format character 'T' (0x54) at index 1 (encoding: 'cp1252')
[download] Downloading video 3 of 17
[download] Vitalane Pidi | EP 19 | 12-03-19 | SVBC TTD Tamil has already been recorded in archive
[download] Downloading video 4 of 17

ERROR: Interrupted by user

< 05-05-2019 & 19:35:39.90 | C:\Users\admin> set
....
( Ooh! ** Missing One Env. Var.!! ** 'Set TOSHIBA=F:\Vista n Bk-up, RS\RangSE' )
< 05-05-2019 & 19:42:12.21 | C:\Users\admin> Set TOSHIBA=F:\Vista n Bk-up, RS\RangSE
< 05-05-2019 & 19:44:40.40 | C:\Users\admin> youtube-dl[2019.04.30] -ci --yes-playlist --playlist-start 17 ...
( ..Without any problem, the Programme runs!)
May be someone already noticed, or didn't come across.
May I suggest? as "Error: '%Env_Var%' is NOT Set!" , where %Env_Var%, an Environment Variable, that was/is Undefined/Yet to be defined; also we need to work on whether it is Environment Variable or Option Parameter! [ such as '%(..' is Option; otherwise, an Environment Variable. ]
Regards,

**Comment by dstftw** [comment]
No, cause youtube-dl can't know your intention - whether you wanted to reference non existing env variable or just improperly used the output template.

**Comment by RangaSE** [comment]
@dstftw : Respected Sir, I think you missing a point: ' - o %(option)s...' i.e. any option in Output Template, starts with '%(', whereas %ENV_VAR% does NOT have '(', the Left Parenthesis. I was/am thinking, we can take advantage of the Difference. Nothing Else.
Regards,
