### ISSUE TITLE
How to get direct link of subtitle?

### ISSUE THREAD

**Issue by jeraldpunx** [ytdl-org/youtube-dl#20995]
How to list all direct link of subtitle, like the direct link of video?

on video it's like this.

```
youtube-dl.exe --get-url VIDEO_LINK
```
but on subtitle it's different, I've tried this 

youtube-dl--sub-lang en --all-subs --write-auto-sub --skip-download VIDEO_LINK

**Comment by dstftw** [comment]
Parse from `--dump-json`.
