### ISSUE TITLE
WARNING: unable to extract channel id  "https://youtu.be/J3udNz5_syg"

### ISSUE THREAD

**Issue by JanCoombs** [ytdl-org/youtube-dl#21004]
jan:PedramShoji_Interconnected$ 
jan:PedramShoji_Interconnected$ youtube-dl --limit-rate 88K --verbose "https://youtu.be/J3udNz5_syg"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--limit-rate', u'88K', u'--verbose', u'https://youtu.be/J3udNz5_syg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9.8
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[youtube] J3udNz5_syg: Downloading webpage
[youtube] J3udNz5_syg: Downloading video info webpage
WARNING: unable to extract channel id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r3---sn-u5a3u5a3-cgn6.googlevideo.com/videoplayback?id=o-AP-6KjbR0LMnCrSklejFBUoDDDLF8-VHq0dmgWCkqedE&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&itag=248&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-u5a3u5a3-cgn6%2Csn-aigzrn7l&ms=au%2Crdu&mv=m&pl=16&ei=T53SXM_TEN361wby-7CIBw&pcm2=yes&initcwndbps=646250&mime=video%2Fwebm&gir=yes&clen=527328707&dur=4529.291&lmt=1557301713284855&mt=1557306617&fvip=4&keepalive=yes&c=WEB&txp=5535432&ip=79.77.40.118&ipbits=0&expire=1557328303&sparams=ip%2Cipbits%2Cexpire%2Cid%2Caitags%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cpcm2%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&signature=D6B937F6A549B333E43941338A72C9D33DE91348.069A0BBCEA775A0DEFA00118ACB237A51C778BB8&key=yt8&ratebypass=yes'
[download] Resuming download at byte 446640342
[download] Destination: Interconnected - Episode 1 – The Missing Piece in Health and Longevity-J3udNz5_syg.f248.webm
[download] 100% of 502.90MiB in 14:51
[debug] Invoking downloader on u'https://r3---sn-u5a3u5a3-cgn6.googlevideo.com/videoplayback?id=o-AP-6KjbR0LMnCrSklejFBUoDDDLF8-VHq0dmgWCkqedE&itag=251&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-u5a3u5a3-cgn6%2Csn-aigzrn7l&ms=au%2Crdu&mv=m&pl=16&ei=T53SXM_TEN361wby-7CIBw&pcm2=yes&initcwndbps=646250&mime=audio%2Fwebm&gir=yes&clen=63572368&dur=4529.321&lmt=1557299524852148&mt=1557306617&fvip=4&keepalive=yes&c=WEB&txp=5531432&ip=79.77.40.118&ipbits=0&expire=1557328303&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cpcm2%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&signature=A5D826380A69A1CD3DD2FC809F9CCBA6C0C26D6F.203F3CEF46C0844CEE2C90BC9147AC96412FB139&key=yt8&ratebypass=yes'
[download] Destination: Interconnected - Episode 1 – The Missing Piece in Health and Longevity-J3udNz5_syg.f251.webm
[download] 100% of 60.63MiB in 11:43
[ffmpeg] Merging formats into "Interconnected - Episode 1 – The Missing Piece in Health and Longevity-J3udNz5_syg.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Interconnected - Episode 1 – The Missing Piece in Health and Longevity-J3udNz5_syg.f248.webm' -i 'file:Interconnected - Episode 1 – The Missing Piece in Health and Longevity-J3udNz5_syg.f251.webm' -c copy -map '0:v:0' -map '1:a:0' 'file:Interconnected - Episode 1 – The Missing Piece in Health and Longevity-J3udNz5_syg.temp.webm'
Deleting original file Interconnected - Episode 1 – The Missing Piece in Health and Longevity-J3udNz5_syg.f248.webm (pass -k to keep)
Deleting original file Interconnected - Episode 1 – The Missing Piece in Health and Longevity-J3udNz5_syg.f251.webm (pass -k to keep)
jan:PedramShoji_Interconnected$

**Comment by tedder** [comment]
existing issue for this: #20982
