### ISSUE TITLE
Facebook download speed slow

### ISSUE THREAD

**Issue by mmjjb** [ytdl-org/youtube-dl#21018]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Downloading from Facebook goes extremely slow, about 40Kb/s.
When I download the same video trough curl, I get normal speeds. Any idea what the issue can be?

```[debug] youtube-dl version 2019.04.30
[facebook] 1393626100686564: Downloading webpage

[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://video-ort2-1.xx.fbcdn.net/v/t42.9040-2/10000000_136940690132218_8752927939458236416_n.mp4?_nc_cat=104&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2h...'
[download] Resuming download at byte 40036579
[download] Destination: Test...-1393626100686564.554v.mp4
[download]  28.2% of 136.59MiB at 38.11KiB/s ETA 43:57
```

I have tried to use `--http-chunk-size` but it has no improvement

**Comment by bpsib** [comment]
I also find downloading Facebook videos very slow. I also get an error about connection being closed around every 15 minutes. It's a pain when downloading large videos.

**Comment by cfreds** [comment]
You can try using a VPN, maybe the videos will download from anothers server (CDN)

**Comment by mmjjb** [comment]
@cfreds the same video URL downloads fine with curl

**Comment by michaelzs1994** [comment]
Same here,mate.Speed is limit in 35-40kb/s always.

**Comment by TaktakTaktouk** [comment]
I have the same problem.
But when I watch the video, it loads very quickly, so I do not think it's a Facebook issue.
