### ISSUE TITLE
www.tele5.de has been updated and does not work anymore

### ISSUE THREAD

**Issue by Bitdigger42** [ytdl-org/youtube-dl#21020]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

youtube-dl -v 'https://www.tele5.de/star-trek/raumschiff-voyager/ganze-folge/das-vinculum/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.tele5.de/star-trek/raumschiff-voyager/ganze-folge/das-vinculum/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 3.6.5 (CPython) - Linux-4.14.65-gentoo-x86_64-AMD_Phenom-tm-_II_X4_925_Processor-with-gentoo-2.6
[debug] exe versions: ffmpeg 3.4.5, ffprobe 3.4.5, rtmpdump 2.4
[debug] Proxy map: {}
[generic] das-vinculum: Requesting header
WARNING: Falling back on generic information extractor.
[generic] das-vinculum: Downloading webpage
[generic] das-vinculum: Extracting information
ERROR: Unsupported URL: https://www.tele5.de/star-trek/raumschiff-voyager/ganze-folge/das-vinculum/
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.tele5.de/star-trek/raumschiff-voyager/ganze-folge/das-vinculum/

## Description

Site www.tele5.de has been redesigned and does not work anymore. Last successful try was on May 6th 2019.
New overview Url for a series the worked before (containes links to single episodes):
https://www.tele5.de/star-trek/raumschiff-voyager/

Url to a single episode:
https://www.tele5.de/star-trek/raumschiff-voyager/ganze-folge/das-vinculum/
https://www.tele5.de/star-trek/raumschiff-voyager/ganze-folge/inhumane-praktiken/

Each of this episodes is valid for seven days.

Best regards
Bitdigger42

**Comment by uahim** [comment]
confirmed for
https://www.tele5.de/filme/schlefaz-dragon-crusaders/
or any other video linked on
https://www.tele5.de/filme/online/

I am only a regex/python noob, but from what I see all that needs to be updated is `_VALID_URL` as their url format changed for both types of videos, so adding `/ganze-folge/` and `/filme/` to the regex should do the trick.
maybe @dstftw could look into it?

thanks
