### ISSUE TITLE
Manpage reference to otherwise unlisted option '-A' or '--auto-number'

### ISSUE THREAD

**Issue by jamespharvey20** [ytdl-org/youtube-dl#21021]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.04.30**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
man youtube-dl
```

or

```
youtube-dl --help
```

## Description

`man youtube-dl` doesn't list `-A` or `--auto-number` under options, and `youtube-dl --help` doesn't list it at all.

Yet, `man youtube-dl` under "FAQ" and "I'm getting an error when trying to use output template" references it:

````
   I'm getting an error when trying to use output template:
       error: using output template conflicts with using title, video ID or auto number

       Make sure you are not using -o with any of these options -t, --title, --id, -A or --auto-number set in command line or in a configuration file.  Remove the latter if any.
````

Haven't checked source & git history.  Maybe this is an undocumented option, or maybe this is an option previously removed with a dangling reference to it in the FAQ.

**Comment by dstftw** [comment]
`--auto-number` is deprecated.
