### ISSUE TITLE
Was asked to report a bug - first time I have done this

### ISSUE THREAD

**Issue by pobblebottom** [ytdl-org/youtube-dl#21035]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.04.30**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

$ youtube-dl --verbose https://www.youtube.com/watch?v=X8vumVOtgso
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=X8vumVOtgso']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.10 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] X8vumVOtgso: Downloading webpage
[youtube] X8vumVOtgso: Downloading video info webpage
[youtube] {18} signature length 40.43, html5 player vflHkKkEW
[youtube] {137} signature length 40.43, html5 player vflHkKkEW
[youtube] {248} signature length 40.43, html5 player vflHkKkEW
[youtube] {136} signature length 40.43, html5 player vflHkKkEW
[youtube] {247} signature length 40.43, html5 player vflHkKkEW
[youtube] {135} signature length 40.43, html5 player vflHkKkEW
[youtube] {244} signature length 40.43, html5 player vflHkKkEW
[youtube] {134} signature length 40.43, html5 player vflHkKkEW
[youtube] {243} signature length 40.43, html5 player vflHkKkEW
[youtube] {133} signature length 40.43, html5 player vflHkKkEW
[youtube] {242} signature length 40.43, html5 player vflHkKkEW
[youtube] {160} signature length 40.43, html5 player vflHkKkEW
[youtube] {278} signature length 40.43, html5 player vflHkKkEW
[youtube] {140} signature length 40.43, html5 player vflHkKkEW
[youtube] {171} signature length 40.43, html5 player vflHkKkEW
[youtube] {249} signature length 40.43, html5 player vflHkKkEW
[youtube] {250} signature length 40.43, html5 player vflHkKkEW
[youtube] {251} signature length 40.43, html5 player vflHkKkEW
WARNING: unable to extract channel id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r1---sn-fpqxc5oq-hxal.googlevideo.com/videoplayback?id=o-AAtPTG62mf-B_O7ZI3V6WPeaOwAb_5vs_wg9ocYqwLzd&itag=18&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-fpqxc5oq-hxal%2Csn-ntq7yner&ms=au%2Crdu&mv=m&pl=24&ei=dvTUXN-NEO2k3LUP3ua5qAE&initcwndbps=1798750&mime=video%2Fmp4&gir=yes&clen=12079911&ratebypass=yes&dur=241.301&lmt=1542250195809187&mt=1557460013&fvip=3&c=WEB&txp=5431432&ip=203.129.25.152&ipbits=0&expire=1557481686&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&key=yt8&signature=3EADEF15057999AD5772EAC5C2164E56E1403EE9.8F75DBB33D121FFA52B213EFA1FF074B63D2B779'

## Description

Yt-dl is reporting that channel id is unable to be extracted. The result is a download of an inferior quality (640x360) video when 1080p version exists and is working on Youtube

**Comment by sudovijay** [comment]
Seems to be already fixed in #21003, you can wait for next release :)
