### ISSUE TITLE
Unable to download webpage: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by glebermon** [ytdl-org/youtube-dl#21036]
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 3.7.3 (CPython) - Darwin-18.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

tried to download course from udemy

**Comment by actionableinsights** [comment]
ERROR: can't find the current version. Please try again later.
