### ISSUE TITLE
Some v.redd.it videos have visual issues every 6 seconds.

### ISSUE THREAD

**Issue by AaronV-T** [ytdl-org/youtube-dl#21034]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PS D:\Downloads> .\youtube-dl.exe -v https://v.redd.it/mmrx3kz5d2x21
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://v.redd.it/mmrx3kz5d2x21']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.04.30
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[Reddit] mmrx3kz5d2x21: Downloading m3u8 information
[Reddit] mmrx3kz5d2x21: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://v.redd.it/mmrx3kz5d2x21/HLS_360_v4.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 9
[download] Destination: mmrx3kz5d2x21-mmrx3kz5d2x21.mp4
[download] 100% of 6.46MiB in 00:02
```

## Description

Some v.redd.it videos have strange visual issues at around 6 seconds, 12 seconds, 18 seconds, etc (I have uploaded some [examples](https://imgur.com/a/CxJMPIt) in which you can see that the problems occur at practically the same time in each video).

Here are `ffprobe` results on 3 v.redd.it videos I downloaded today and that have issues and 1 v.redd.it video that I downloaded today and has no issues:

    Input #0, mpegts, from '.\bad1.mp4':
      Duration: 00:00:09.69, start: 1.471233, bitrate: 2169 kb/s
      Program 1
        Metadata:
          service_name    : Service01
          service_provider: FFmpeg
        Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 432x768 [SAR 1:1 DAR 9:16], 28.08 fps, 28.08 tbr, 90k tbn, 56.15 tbc
		
    Input #0, mpegts, from '.\bad2.mp4':
      Duration: 00:00:53.70, start: 1.466667, bitrate: 1009 kb/s
      Program 1
        Metadata:
          service_name    : Service01
          service_provider: FFmpeg
        Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 640x396 [SAR 3201:3200 DAR 97:60], 30 fps, 30 tbr, 90k tbn, 60 tbc
		
    Input #0, mpegts, from '.\bad3.mp4':
      Duration: 00:00:29.94, start: 1.466600, bitrate: 1034 kb/s
      Program 1
        Metadata:
          service_name    : Service01
          service_provider: FFmpeg
        Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 476x432 [SAR 7020:7021 DAR 65:59], 30 fps, 30 tbr, 90k tbn, 60.06 tbc

    Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\good1.mp4':
      Metadata:
        major_brand     : iso5
        minor_version   : 1
        compatible_brands: avc1iso5dsmsmsixdash
        encoder         : Lavf57.71.100
      Duration: 00:00:12.77, start: 0.000000, bitrate: 4821 kb/s
        Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 608x1080 [SAR 2205:2204 DAR 49:87], 1490 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
        Metadata:
          handler_name    : VideoHandler

As you can see, all of the broken videos specify `mpegts` and are missing metadata.

The videos that have problems after downloaded came from: https://v.redd.it/mmrx3kz5d2x21, https://v.redd.it/jh36uwq0b7x21, and https://v.redd.it/va1hxr74i2x21

**Comment by AaronV-T** [comment]
@dstftw Can you tell me which issue this is a duplicate of so that I may follow it?

**Comment by makeworld-the-better-one** [comment]
@AaronV-T Check out the new issue: #21270

**Comment by z0z0z** [comment]
@dstftw Please tell us what issue this is a duplicate of.
