### ISSUE TITLE
[youtube] Extract channel ID?

### ISSUE THREAD

**Issue by avagraha** [ytdl-org/youtube-dl#21037]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

C:\Users\ad>y -v https://www.youtube.com/watch?v=JI-q5YarveA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=JI-q5YarveA']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.04.30
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-93674-g1e01f66-Reino, ffprobe 
N-93674-g1e01f66-Reino, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] JI-q5YarveA: Downloading webpage
[youtube] JI-q5YarveA: Downloading video info webpage
[youtube] {22} signature length 40.43, html5 player vflHkKkEW
[youtube] {43} signature length 40.43, html5 player vflHkKkEW
[youtube] {18} signature length 40.43, html5 player vflHkKkEW
[youtube] {313} signature length 40.43, html5 player vflHkKkEW
[youtube] {271} signature length 40.43, html5 player vflHkKkEW
[youtube] {137} signature length 40.43, html5 player vflHkKkEW
[youtube] {248} signature length 40.43, html5 player vflHkKkEW
[youtube] {136} signature length 40.43, html5 player vflHkKkEW
[youtube] {247} signature length 40.43, html5 player vflHkKkEW
[youtube] {135} signature length 40.43, html5 player vflHkKkEW
[youtube] {244} signature length 40.43, html5 player vflHkKkEW
[youtube] {134} signature length 40.43, html5 player vflHkKkEW
[youtube] {243} signature length 40.43, html5 player vflHkKkEW
[youtube] {133} signature length 40.43, html5 player vflHkKkEW
[youtube] {242} signature length 40.43, html5 player vflHkKkEW
[youtube] {160} signature length 40.43, html5 player vflHkKkEW
[youtube] {278} signature length 40.43, html5 player vflHkKkEW
[youtube] {140} signature length 40.43, html5 player vflHkKkEW
[youtube] {171} signature length 40.43, html5 player vflHkKkEW
[youtube] {249} signature length 40.43, html5 player vflHkKkEW
[youtube] {250} signature length 40.43, html5 player vflHkKkEW
[youtube] {251} signature length 40.43, html5 player vflHkKkEW
WARNING: unable to extract channel id; please report this issue on 
https:://yt-dl.org/bug . Make sure you are using the latest version; type 
youtube-dl -U  to update. Be sure to call youtube-dl with t
he --verbose flag and include its complete output.
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 
'https://r12---sn-8vq54voxpu-ca9e.googlevideo.com/videoplayback?id=o-ALPe90Lkfh3qkncOVM-BU7yokcWPzyCcmqY0GupfFpPx&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C
244%2C247%2C248%2C271%2C278%2C313&itag=313&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-8vq54voxpu-ca9e%2Csn-hpa7zns6&ms=au%2Crdu&mv=m&pcm2cms=yes&pl=24&usequic=no&ei=uszUXIzmJsqN1gKByZ-ABA&initcwnd
bps=898750&mime=video%2Fwebm&gir=yes&clen=744516189&dur=363.663&lmt=1545357342380809&mt=1557449833&fvip=1&keepalive=yes&c=WEB&txp=2211222&ip=2.40.118.133&ipbits=0&expire=1557471514&sparams=ip%2Cipbits
%2Cexpire%2Cid%2Caitags%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cusequic%2Cei%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&key=yt8&signature=64B049CBF513CA703EDE32F6A5B2A2B986FF5230
.A6C388E974467B930486506E7FA27CC315A171FD&ratebypass=yes'
[download] Destination: 2018 冬の横浜夜景 & クリスマスイルミネーション　[4K]  YOKOHAMA Christmas 
illuminations-JI-q5YarveA.f313.webm
[download]   0.1% of 710.03MiB at 47.12KiB/s ETA 04:16:50

## Description

WRITE DESCRIPTION HERE
===================
at 690MB of 710MB the download stopped. CMD.exe: unable to do Ctrl+C
expected behaviour?

**Comment by avagraha** [comment]
please refer the main topic, so I follow it. thanks.



  ----- Original Message -----

**Comment by MCOfficer** [comment]
#20982 (fixed in #21003)

**Comment by avagraha** [comment]
thanks a lot, much appreciated.



  ----- Original Message -----
