### ISSUE TITLE
Pluralsight password having "\" character.

### ISSUE THREAD

**Issue by parthdmaniar** [ytdl-org/youtube-dl#21030]
## Checklist

- [Yes] I'm reporting a broken site support issue
- [ Yes] I've verified that I'm running youtube-dl version **2019.04.30**
- [Yes] I've checked that all provided URLs are alive and playable in a browser
- [Yes] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [Yes] I've searched the bugtracker for similar bug reports including closed ones
- [Yes] I've read bugs section in FAQ

## Verbose log

-->

```
youtube-dl --username "REDACTED" --password "Alphabets replaced with * only symbols kept as is }~**+8**\**" --verbose --sleep-interval 120 "https://app.pluralsight.com/library/courses/operationalizing-cyber-threat-intel-pivoting-hunting/table-of-contents"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--verbose', u'--sleep-interval', u'120', u'https://app.pluralsight.com/library/courses/operationalizing-cyber-threat-intel-pivoting-hunting/table-of-contents']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.16 (CPython) - Linux-5.0.0-13-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] operationalizing-cyber-threat-intel-pivoting-hunting: Downloading JSON metadata
[download] Downloading playlist: Operationalizing Cyber Threat Intel: Pivoting & Hunting
[pluralsight:course] playlist Operationalizing Cyber Threat Intel: Pivoting & Hunting: Collected 36 video ids (downloading 36 of them)
[download] Downloading video 1 of 36
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 528, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 432, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 165, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 215, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I suspect " \ " character in the password to be causing this issue. I have  used the same command line with the same switches to successfully connect and login using different name and password.

My password without numbers and alphabets has the following:      }~+\

**Comment by rautamiekka** [comment]
Since you're on NIX, try replacing the double quotes surrounding your pw with single quotes.

**Comment by parthdmaniar** [comment]
I am using the same command line and switches (including double quotes) with different password and it works perfect. Once this is one, I will try with single quotes and the PWD i had.

Hopefully, I will find my first bug :D

**Comment by parthdmaniar** [comment]
`youtube-dl --username "parth.maniar@willistowerswatson.com" --password '}~+8\' --verbose --sleep-interval 120 "https://app.pluralsight.com/library/courses/operationalizing-cyber-threat-intel-pivoting-hunting/table-of-contents"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--verbose', u'--sleep-interval', u'120', u'https://app.pluralsight.com/library/courses/operationalizing-cyber-threat-intel-pivoting-hunting/table-of-contents']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.16 (CPython) - Linux-5.0.0-13-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] operationalizing-cyber-threat-intel-pivoting-hunting: Downloading JSON metadata
[download] Downloading playlist: Operationalizing Cyber Threat Intel: Pivoting & Hunting
[pluralsight:course] playlist Operationalizing Cyber Threat Intel: Pivoting & Hunting: Collected 36 video ids (downloading 36 of them)
[download] Downloading video 1 of 36
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 528, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 432, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 165, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 215, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`


Still the same thing. (YAY and sorry).

**Comment by dstftw** [comment]
For any work on this you must provide account credentials.

**Comment by parthdmaniar** [comment]
I can provide the credentials, could you confirm who should I direct message those to?
