### ISSUE TITLE
mp3 download from youtube

### ISSUE THREAD

**Issue by PVasileff** [ytdl-org/youtube-dl#21051]
Before last update I dowload + convert yotube videos to mp3 with:

`youtube-dl -f best --extract-audio --audio-quality 320K --audio-format mp3 https://www.youtube.com/watch?v=XXXXXX`

with ffmpeg. 
After update Iog an error:

> WARNING: unable to extract channel id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> ERROR: unable to download video data: HTTP Error 403: Forbidden

Can you tell me what is changed and how to make it to work again?

**Comment by PVasileff** [comment]
Whats meen incomplete?

**Comment by dstftw** [comment]
Bother to read issue template.
