### ISSUE TITLE
Random youtube video returning unstreamable Stream URL

### ISSUE THREAD

**Issue by wootiown** [ytdl-org/youtube-dl#21052]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.04.30**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Description

No Verbose Log as the issue is currently present in Python 3.7.

When using the code
```
            ydl_opts = {
                'format': 'bestaudio',
            }

            with youtube_dl.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(yturl, download=False)
            print(info['formats'][0]['url'])
```
to retrieve the stream URL of youtube tracks, every track I've tested works perfectly EXCEPT FOR 
https://www.youtube.com/watch?v=cJOp0N5hK2c, for some reason. Instead of linking a stream for an m4a or mp3, i'm prompted to download a file titled 'yt8.' When passing the URL to python-vlc to play it, the video appears when it shouldnt and VLC throws a load of redirect errors.

**Comment by dstftw** [comment]
```
PS C:\Dev\youtube-dl\master> py -3.7 .\youtube_dl\__main__.py https://www.youtube.com/watch?v=cJOp0N5hK2c -f bestaudio
[youtube] cJOp0N5hK2c: Downloading webpage
[youtube] cJOp0N5hK2c: Downloading video info webpage
[youtube] cJOp0N5hK2c: Downloading MPD manifest
[dashsegments] Total fragments: 43
[download] Destination: Sable Symphony - Open Up Your Eyes (Metal Cover)-cJOp0N5hK2c.m4a
[download]  62.8% of ~3.14MiB at  6.29MiB/s ETA 00:00
ERROR: Interrupted by user
```
