### ISSUE TITLE
python3 /usr/local/bin/youtube-dl

### ISSUE THREAD

**Issue by itskando** [ytdl-org/youtube-dl#21055]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

OS Version:

FreeBSD plex 11.2-STABLE FreeBSD 11.2-STABLE #0 r325575+3b66a34f3aa(HEAD): Wed Feb 27 14:31:54 EST 2019     root@nemesis.tn.ixsystems.com:/freenas-releng/freenas/_BE/objs/freenas-releng/freenas/_BE/os/sys/FreeNAS.amd64  amd64

youtube-dl version: 

2019.04.30

```
root@plex:~ # youtube-dl --version
env: python: No such file or directory
root@plex:~ # python3 youtube-dl --version
python3: can't open file 'youtube-dl': [Errno 2] No such file or directory
root@plex:~ # python3 /usr/local/bin/youtube-dl --version
2019.04.30
```

Is there a way to not need to type the youtube-dl path when entering the command?
Is there a way to not need to type python3 when entering the command?

**Comment by dstftw** [comment]
Add `python` alias.
