### ISSUE TITLE
[youtube:watchlater] Unable to log in: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by HPP8140** [ytdl-org/youtube-dl#21065]
## Checklist

- [x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.05.11**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

[debug] System config: [u'--hls-prefer-native']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u':ytwatchlater', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-s', u'-j', u'--flat-playlist', u'--write-pages']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968
[debug] youtube-dl version 2019.05.11
[debug] Python version 2.7.9 (CPython) - Linux-3.14.0-kirkwood-tld-1-armv5tel-with-debian-8.10
[debug] exe versions: avconv 11.11-6, avprobe 11.11-6, ffmpeg 0.8.21-6
[debug] Proxy map: {}
WARNING: Unable to log in: HTTP Error 400: Bad Request
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 3077, in _real_extract
    _, playlist = self._extract_playlist('WL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2589, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist does not exist.

## Description

Looks like the login form may have changed and youtube-dl is unable to login to download the watchlater playlist

**Comment by sngbrdb** [comment]
It would be really nice if people who close bugs as "duplicate" would reference the original bug.  I'm still having this issue with 2019.07.02, and can't find the original - just a bunch of "closed as duplicate", and one original issues from 2014 that doesn't apply.

**Comment by sdudley7** [comment]
Receiving the same issue

**Comment by t-schroeder** [comment]
Still having this issue with 2019.11.28. From time to time I update youtube-dl but I haven't been able to download my watch later playlist for like half a year now.
