### ISSUE TITLE
Not all resolutions/formats listed for youtube

### ISSUE THREAD

**Issue by emansugoba** [ytdl-org/youtube-dl#21070]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.05.11**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

$ youtube-dl -v --list-formats https://www.youtube.com/watch?v=VdxPUzY4_hQ
[debug] System config: []
[debug] User config: ['--ffmpeg-location', 'C:/Program Files/ffmpeg-3.3.2-win64-static/bin', '--format', 'bestvideo+bestaudio/best', '--merge-output-format', 'mkv', '--youtube-skip-dash-manifest', '--all-subs', '--add-metadata', '--embed-subs']
[debug] Custom config: []
[debug] Command-line args: ['-v', '--list-formats', 'https://www.youtube.com/watch?v=VdxPUzY4_hQ']
[debug] Encodings: locale cp1255, fs utf-8, out cp1255, pref cp1255
[debug] youtube-dl version 2019.05.11
[debug] Python version 3.6.0 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[youtube] VdxPUzY4_hQ: Downloading webpage
WARNING: video doesn't have subtitles
[info] Available formats for VdxPUzY4_hQ:
format code  extension  resolution note
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 8.03MiB
134          mp4        640x360    360p  606k , avc1.4d401e, 24fps, video only, 20.52MiB
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k, 29.11MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 43.21MiB
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)

## Description

When opening the above URL in youtube, an 1080p option is available. When listing formats using youtube-dl, no 1080p format is listed.

**Comment by dstftw** [comment]
```
PS C:\Dev\youtube-dl\master> py -2.7 .\youtube_dl\__main__.py VdxPUzY4_hQ -F
[youtube] VdxPUzY4_hQ: Downloading webpage
[youtube] VdxPUzY4_hQ: Downloading video info webpage
[youtube] VdxPUzY4_hQ: Downloading MPD manifest
[info] Available formats for VdxPUzY4_hQ:
format code  extension  resolution note
139          m4a        audio only DASH audio   65k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k (44100Hz)
160          mp4        256x144    DASH video  108k , mp4_dash container, avc1.4d400b, 24fps, video only
133          mp4        426x240    DASH video  242k , mp4_dash container, avc1.4d400c, 24fps, video only
134          mp4        640x360    DASH video  606k , mp4_dash container, avc1.4d401e, 24fps, video only
135          mp4        854x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 24fps, video only
136          mp4        1280x720   DASH video 2310k , mp4_dash container, avc1.4d4016, 24fps, video only
137          mp4        1920x1080  DASH video 4331k , mp4_dash container, avc1.64001e, 24fps, video only
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k, 29.11MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 43.21MiB
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
```

**Comment by dstftw** [comment]
Don't touch `--youtube-skip-dash-manifest` in you have no idea of what you are doing.
