### ISSUE TITLE
support for https://unacademy.com/

### ISSUE THREAD

**Issue by ramjmi** [ytdl-org/youtube-dl#21093]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.05.11**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [ ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://unacademy.com/lesson/vector-space-lesson-1-in-hindi/RD9SAOJX/?source=Course
- Single video: https://unacademy.com/lesson/vector-space-lesson-2-in-hindi/7C823QYM
- Playlist: https://unacademy.com/course/linear-algebra-for-csir-net-math/D74R1NTF

## Description

WRITE DESCRIPTION HERE
Sir/Madam
Plz provide the youtube-dl support for the site https://unacademy.com/. I am unable to download playlist from this. Also, site provides download option to its android app. Support for this site is not helping me only but thousands of students in their learning.

**Comment by dstftw** [comment]
For any work on this you must provide account credentials.

**Comment by ramjmi** [comment]
login details:
ramjmi@gmail.com
ram12345
