### ISSUE TITLE
Safari extractor - unable to extract csrf token

### ISSUE THREAD

**Issue by gopherunner** [ytdl-org/youtube-dl#21098]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

I'm having the following issue while trying to use the Safari extractor:

[safari:course] Downloading login form
ERROR: Unable to extract csrf token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by hoangphuc2019** [comment]
Find and replace in safari.py:
csrf = self._html_search_regex(
        r"name='**csrfmiddlewaretoken**'\s+value='([^']+)'",
        login_page, 'csrf token')

    login_form = {
        '**csrfmiddlewaretoken**': csrf,
        'email': username,
        'password1': password,
        'login': 'Sign In',
        'next': '',
    }
Old: **csrfmiddlewaretoken** --> New: **csrfsafari**
