### ISSUE TITLE
Why are certain site support requests "locked and limited conversation to collaborators"

### ISSUE THREAD

**Issue by ealgase** [ytdl-org/youtube-dl#21113]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Issues like #21019 have been locked (but not closed) without a given reason.  Does this mean that it's actively being developed by the collaborators, or that it's not going to be supported, etc?

The reason I ask is that I'm interested in creating an extractor for that site, but with the issue in the current state, I'm not sure if I should.

**Comment by dstftw** [comment]
Issues are locked due to either flood, excessive bumping or offtopic.

**Comment by ealgase** [comment]
OK, thanks for the info.  Is it safe to work on an extractor, then?
