### ISSUE TITLE
Use youtube-dl in c++/qt projects

### ISSUE THREAD

**Issue by LinArcX** [ytdl-org/youtube-dl#21119]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question
Hi. i want to use youtube-dl in a qt application. but i don't know how. anyone here has same experience to use youtube-dl in a c++/qt project?

WRITE QUESTION HERE

**Comment by dstftw** [comment]
`QProcess`.

**Comment by LinArcX** [comment]
@dstftw I know about QPorcess. but i want to get android output too. so i can't use QProcess anymore.
