### ISSUE TITLE
Uninstall last version in Python package

### ISSUE THREAD

**Issue by mohseneslami** [ytdl-org/youtube-dl#21111]
Hello, why in CMD type for C:\>youtube-dl --version
2018.11.23

but when try for update 

C:\>pip install --upgrade youtube-dl
Requirement already up-to-date: youtube-dl in c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages (2019.5.11)

How delete or remove all youtube-dl from my PC and again install it

**Comment by Hrxn** [comment]
Remove old youtube-dl from `PATH`.

**Comment by dstftw** [comment]
Remove the opposite way you installed them.
