### ISSUE TITLE
Try another format if "Did not get any data blocks" error

### ISSUE THREAD

**Issue by sikro94** [ytdl-org/youtube-dl#21121]
- [* ] I'm reporting a broken site support issue
- [ *] I've verified that I'm running youtube-dl version **2019.05.11**
- [ *] I've checked that all provided URLs are alive and playable in a browser
- [ *] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ *] I've searched the bugtracker for similar bug reports including closed ones
- [ *] I've read bugs section in FAQ

## Verbose log

root@ns:~/test# youtube-dl -f 22/18 --ffmpeg-location /usr/local/bin/ffmpeg --verbose https://www.youtube.com/watch?v=sCwOUOcVZhs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'22/18', u'--ffmpeg-location', u'/usr/local/bin/ffmpeg', u'--verbose', u'https://www.youtube.com/watch?v=sCwOUOcVZhs']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2019.05.11
[debug] Python version 2.7.13 (CPython) - Linux-4.9.168-xxxx-std-ipv6-64-x86_64-with-debian-9.8
[debug] exe versions: ffmpeg 4.1.2, ffprobe 4.1.2
[debug] Proxy map: {}
[youtube] sCwOUOcVZhs: Downloading webpage
[youtube] sCwOUOcVZhs: Downloading video info webpage
[youtube] {22} signature length 43.40, html5 player vflaT82Q3
[youtube] {43} signature length 43.40, html5 player vflaT82Q3
[youtube] {18} signature length 43.40, html5 player vflaT82Q3
[youtube] {137} signature length 43.40, html5 player vflaT82Q3
[youtube] {248} signature length 43.40, html5 player vflaT82Q3
[youtube] {136} signature length 43.40, html5 player vflaT82Q3
[youtube] {247} signature length 43.40, html5 player vflaT82Q3
[youtube] {135} signature length 43.40, html5 player vflaT82Q3
[youtube] {244} signature length 43.40, html5 player vflaT82Q3
[youtube] {134} signature length 43.40, html5 player vflaT82Q3
[youtube] {243} signature length 43.40, html5 player vflaT82Q3
[youtube] {133} signature length 43.40, html5 player vflaT82Q3
[youtube] {242} signature length 43.40, html5 player vflaT82Q3
[youtube] {160} signature length 43.40, html5 player vflaT82Q3
[youtube] {278} signature length 43.40, html5 player vflaT82Q3
[youtube] {140} signature length 43.40, html5 player vflaT82Q3
[youtube] {171} signature length 43.40, html5 player vflaT82Q3
[youtube] {249} signature length 43.40, html5 player vflaT82Q3
[youtube] {250} signature length 43.40, html5 player vflaT82Q3
[youtube] {251} signature length 43.40, html5 player vflaT82Q3
[debug] Invoking downloader on u'https://r1---sn-25ge7nl6.googlevideo.com/videoplayback?id=o-AD6_2eGYkfqdMVTDS7LpuRp7j8gjLguUBDXI8Q-_puLb&itag=22&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-25ge7nl6%2Csn-25glene6&ms=au%2Crdu&mv=m&pl=21&ei=R6DdXPrBDJvmhAf0hKz4Dg&initcwndbps=226250&mime=video%2Fmp4&ratebypass=yes&dur=247.756&lmt=1558016974533226&mt=1558028266&fvip=1&c=WEB&txp=5511222&ip=51.83.37.75&ipbits=0&expire=1558049959&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cinitcwndbps%2Cmime%2Cratebypass%2Cdur%2Clmt&key=yt8&signature=D544DA61ED2F3E4968C06D08F6ED25BF56F03F0F.0F248614EF740E7DF9B1A5D5437FA0045D3FC398'
[download] Resuming download at byte 76963

ERROR: Did not get any data blocks
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1642, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1915, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1854, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 312, in download
    self.report_error('Did not get any data blocks')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 586, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

## Description

Hello,

I understood on other posts that this error was related to youtube.

However, I can't download the video in another format. Indeed, for this video https://www.youtube.com/watch?v=sCwOUOcVZhs format 22 displays this error, but format 18 works. In the order, it is filled in 22/18, obviously it does not try to download in the second format.

How to make sure that it makes an attempt with the second format rather than returning the error? Thank you

**Comment by dstftw** [comment]
You can't do that.

**Comment by titirino159** [comment]
> You can't do that.

Hey, the script can't be modified to detect this error and try the format 18 ?

**Comment by Watilin** [comment]
I support this request. The “no data blocks” issue gets rather frequent on Youtube at times, and it would be nice to have youtube-dl automatically switch to an alternate format whenever it’s needed.

**Comment by ventilaar** [comment]
> You can't do that.

But you should be able to. Why else would the manual mention this?

> If you want to download multiple videos and they don't have the same formats available, you can specify the order of preference using slashes.
