### ISSUE TITLE
Error download video youtube: "token" parameter not in video info for unknown

### ISSUE THREAD

**Issue by cfreds** [ytdl-org/youtube-dl#21126]
## Checklist
- [x] I've verified that I'm running youtube-dl version **2019.05.11**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've read bugs section in FAQ

## Verbose log

```
ERROR: x6w1M0OTGQE: "token" parameter not in video info for unknown reason; 
please report this issue on https://yt-dl.org/bug . 
Make sure you are using the latest version; 
type  youtube-dl -U  to update. 
Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

This problem with youtube-dl 2019.05.11 when a try to download videos from youtube of my feed (i added my gmail and pass). 
But only fail if use cronjob (for automatic downloads) when i run the script manually works without problems.
I always love update this software and i remember this script stop to work on april 15.
My vps use Ubuntu 16.04

**Comment by RolfHausen** [comment]
Same here, i get the same issue. I have freshly installed this program for the first time using the Software Center on Linux Mint. i also did an apt-get upgrade after the install to ensure i have the latest version. But nothing has changed. So i guess it is really a bug.

**Comment by bcc32** [comment]
@remitamine This issue should be re-opened.  It was encountered using the latest version, 2019.05.11.
