### ISSUE TITLE
how to run youtube-dl on my embedded device?

### ISSUE THREAD

**Issue by zhpower** [ytdl-org/youtube-dl#21127]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I want to run the youtube-dl  on my embedded device. it's a arm arch and without python environment .
Is it possible to build youtube-dl as a bin file and run it?

Thanks

**Comment by dstftw** [comment]
You must have python environment in order to run youtube-dl.
