### ISSUE TITLE
oreilly support broken

### ISSUE THREAD

**Issue by mohseneslami** [ytdl-org/youtube-dl#21138]
hello, when fix oreilly support again? it's not support anymore

[safari:course] Downloading login form
ERROR: Unable to extract csrf token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Stop posting duplicates and wait for the next release.
