### ISSUE TITLE
Package managers like apt doesn't download latest version of youtube-dl 

### ISSUE THREAD

**Issue by Moamen-Zakaria** [ytdl-org/youtube-dl#21137]
Package managers like apt doesn't download latest version of youtube-dl, even the link in the download page [http://ytdl-org.github.io/youtube-dl/download.html](url), it says "2019.05.11" but when i download and check it's version 2019.1.17, some people may not realize they
![Screenshot_20190518_171046](https://user-images.githubusercontent.com/13944918/57971564-297fbe80-7990-11e9-89f1-02e3c7f74bfb.png)
 didn't download the latest version, and think there's a problem with the program, thanks for your considerations.

**Comment by dstftw** [comment]
We do not control 3rd party package managers. Report this to corresponding mantainers.
