### ISSUE TITLE
Improve Youtube scrapping speed

### ISSUE THREAD

**Issue by axzxc1236** [ytdl-org/youtube-dl#21146]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.05.11**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

There is too many Youtube related issues to check (even if I use "request label" there is still 22 pages)...it would take me hours or days.

## Description

WRITE DESCRIPTION HERE

I observed youtube-dl's behavior from terminal output, it looks like it scraps every video title/url of a Youtube channel before it starts to check other conditions (for example if a video is in --download-archive file or if video meets --dateafter).

(Sorry if that's not how it really works.)

My propose: Since youtube-dl get up to 100 videos' information in every request (from what I saw in terminal output), why not check these conditions everytime you get video informations from Youtube, then say if the earliest video in this list if already archived or doesn't meet dateafter condition, just don't keep scrapping youtube channel/playlist.

Benefit: Let's say A Youtube channel with 2000+ videos uploads a new video everyday, and I run youtube-dl script to archive the channel every week, it would only request 100 videos' information instead of 2000+ videos' information.

**Comment by ealgase** [comment]
> I observed youtube-dl's behavior from terminal output, it looks like it scraps every video title/url of a Youtube channel before it starts to check other conditions (for example if a video is in --download-archive file or if video meets --dateafter).

If the video is in a download archive, that's not the case.  As for scraping every video to check --dateafter, that's necessary to get the published date.

**Comment by dstftw** [comment]
Playlist is not necessarily sorted by date.
