### ISSUE TITLE
ERROR: 'SafariCourseIE' object has no attribute

### ISSUE THREAD

**Issue by mohseneslami** [ytdl-org/youtube-dl#21140]
Hello, I find safari.py that edit for authentication

https://github.com/ytdl-org/youtube-dl/commit/a9e03736dfb2038d6a569e6305f4ac727a8ac71b

i copy and paste in youtube_dl\extractor\safari.py and run 

[safari:course] Downloading login page
[safari:course] Logging in
ERROR: 'SafariCourseIE' object has no attribute '_apply_first_set_cookie_header'

I hope help me

**Comment by dstftw** [comment]
Read developer instructions.
