### ISSUE TITLE
Arguments  to download in specific quality

### ISSUE THREAD

**Issue by ozone1864** [ytdl-org/youtube-dl#21148]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Dear ytdl,
First of all thank you for this super tool until now to download any video from any website but there is something that I can't find. What is the argument to download in specific quality for example 1280x720 or 1920*1080,
Can you elaborate and much thanks.
Best Regards,

**Comment by bitraid** [comment]
> I've looked through the README and FAQ for similar questions

You can set a format selection based on *height* and/or *width*. Details and examples are on the README.

**Comment by ozone1864** [comment]
> > I've looked through the README and FAQ for similar questions
> 
> You can set a format selection based on _height_ and/or _width_. Details and examples are on the README.

Okay thank you !
