### ISSUE TITLE
yt-dl chooses webm container for a single opus/vorbis stream, how do I get the typical ogg/opus.

### ISSUE THREAD

**Issue by mzso** [ytdl-org/youtube-dl#21149]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have this for format: `-f (bestaudio[acodec=opus]/bestaudio[acodec=vorbis]/bestaudio[acodec^=m4a]/bestaudio) -o %(title)s.%(ext)s`

I get webm for opus and vorbis.

I much prefer having the typical extension for their respective formats: Opus, Ogg, M4A

**Comment by dstftw** [comment]
`-x`.

**Comment by mzso** [comment]
> 
> 
> `-x`.

Thanks. I missed  that.
