### ISSUE TITLE
Why is my cookie file blank (Using api)

### ISSUE THREAD

**Issue by kenkit** [ytdl-org/youtube-dl#21158]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
```python
import youtube_dl
import json
from youtube_dl.compat import compat_cookiejar, compat_urllib_request
from youtube_dl.utils import make_HTTPS_handler, YoutubeDLHandler

def youtube_get(url):
    params={}
    jar = compat_cookiejar.MozillaCookieJar("cooke.txt")
    cookie_processor = compat_urllib_request.HTTPCookieProcessor(jar)
    proxies = compat_urllib_request.getproxies()
    proxy_handler = compat_urllib_request.ProxyHandler(proxies)
    https_handler = make_HTTPS_handler(params)
    ydlh = YoutubeDLHandler(params)
    opener = compat_urllib_request.build_opener(https_handler, proxy_handler, cookie_processor, ydlh)
    compat_urllib_request.install_opener(opener)
    y=youtube_dl.YoutubeDL({'outtmpl':u'','skip_download':True,'dumpjson': True,'dump_single_json': True}, auto_init=False)
    y.add_default_info_extractors()
    object = y.extract_info(url, download=False)
    jar.save()
    return json.dumps(object);
```
I'm new to python, using some code I found on https://programtalk.com/python-examples/youtube_dl.YoutubeDL/
Thanks in advance

**Comment by dstftw** [comment]
You should not touch anything apart from options dict where you must set `cookiefile`.

**Comment by kenkit** [comment]
Hi, thanks for responding. I don't get what you mean by touching the options dict, but how do I improve that code. 
If you could write a few lines on how I can fix this I'd be most greatfull, I'm using that function from a c++ program, after coming from using cmdline.

**Comment by kenkit** [comment]
@dstftw Can you please show me how to solve this ?
