### ISSUE TITLE
Unsupported URL tvplay.tv3.lt

### ISSUE THREAD

**Issue by ViliusSutkus89** [ytdl-org/youtube-dl#21153]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.05.11**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl "https://tvplay.tv3.lt/i-siaure-10278493" -v       
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://tvplay.tv3.lt/i-siaure-10278493', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.11
[debug] Python version 3.7.3 (CPython) - MY_KERNEL_VERSION_REDACTED
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] i-siaure-10278493: Requesting header
WARNING: Falling back on generic information extractor.
[generic] i-siaure-10278493: Downloading webpage
[generic] i-siaure-10278493: Extracting information
ERROR: Unsupported URL: https://tvplay.tv3.lt/i-siaure-10278493
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/generic.py", line 3329, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://tvplay.tv3.lt/i-siaure-10278493

```

## Description

I believe tvplay.tv3.lt changed their url, I think it used to be tv3play.tv3.lt, as a result the tvplay extractor doesn't work for tv3.lt anymore.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Same issue here. They once again dropped one part of the URL (it was `https://tvplay.tv3.lt/i-siaure/i-siaure-10278493/` before, now its just `https://tvplay.tv3.lt/i-siaure-10278493/`). #17344 is similar.

**Comment by kuco28** [comment]
same for Estonian one https://tvplay.tv3.ee and Latvian https://tvplay.skaties.lv
