### ISSUE TITLE
[9tsu] Add support for 9tsu.com

### ISSUE THREAD

**Issue by slord399** [ytdl-org/youtube-dl#21159]
## Checklist

- [ x] I'm reporting a new site support request
- [x ] I've verified that I'm running youtube-dl version **2019.05.11**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that none of provided URLs violate any copyrights
- [ x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

## Description

Site support request (request for adding support for a new site)
example URLs
https://video.9tsu.com/videos/view?vid=127112

Description of the issue
Support request of video.9tsu.com (mirror of 9tsu.com)

**Comment by nindogo** [comment]
Hi,

the latest development version of youtube-dl supports this. Please update to use that one.

```bash
PS C:\Users\hp\Documents\code\Python\youtube-dl\master\0001\master> python -m youtube_dl --verbose https://video.9tsu.com/videos/view?vid=127112
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://video.9tsu.com/videos/view?vid=127112']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.05.20
[debug] Git HEAD: 25b83c2a0
[debug] Python version 3.7.3 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[generic] view?vid=127112: Requesting header
WARNING: Falling back on generic information extractor.
[generic] view?vid=127112: Downloading webpage
[generic] view?vid=127112: Extracting information
[download] Downloading playlist: 20時半スタート：【特集】話題の書：中国からの静かなる侵略『サイレントインベージョン』を徹底解説（424)奥山真司のリアリズムで見る国際ニュース「アメ通LIVE」 | 9tsu
[generic] playlist 20時半スタート：【特集】話題の書：中国からの静かなる侵略『サイレントインベージョン』を徹底解説（424)奥山真司のリアリズムで見る国際ニュース「アメ通LIVE」 | 9tsu: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://arc3.cloudflares.xyz:81/download/85ef58761c6275c44cf7b55b37c9834b/5ce7d4e6/user43365/1271125493b01.mp4'
[download] Resuming download at byte 7372662
[download] Destination: 20時半スタート：【特集】話題の書：中国からの静かなる侵略『サイレントインベージョン』を徹底解説（424)奥山真司のリアリズムで見る国際ニュース「アメ通LIVE」 _ 9tsu-viewvid=127112.mp4
[download]  28.0% of 200.56MiB at 231.11KiB/s ETA 10:39
ERROR: Interrupted by user```

**Comment by slord399** [comment]
Thank you for your information.
I can confirm it is working with latest release.
Things is out embed player on the software is not able to retrieve DL link from Video Link.
It immediately start working once I place DL Link.
Thank you for your cooperation.
