### ISSUE TITLE
linux version is outdated: 2018.09.10

### ISSUE THREAD

**Issue by githubeing** [ytdl-org/youtube-dl#21156]
no matter what way i download youtube-dl for linux, its version is so outdated:
```
$ youtube-dl --version
2018.09.10
```

e.g. the following file returns the same: `https://youtube-dl.org/downloads/latest/youtube-dl-2019.05.11.tar.gz`

i've also checked that the latest release supports news.sky.com, so i tried 
```
youtube-dl "http://news.sky.com/video/the-mystery-space-plane-you-shouldnt-know-anything-about-10869049" --verbose
```
and got

```
ERROR: Unsupported URL: https://news.sky.com/video/the-mystery-space-plane-you-shouldnt-know-anything-about-10869049
```
-- so i know this is not the error in version string but the file itself is of outdated version

**Comment by WolfganP** [comment]
Most likely youtube-dl in your path is not the version being updated (by pip or whatever method you use).
Check it with `which youtube-dl`

**Comment by githubeing** [comment]
thank you! you're right! i've called it `$ youtube-dl` while had to call: `$ ./youtube-dl`
