### ISSUE TITLE
add support for jpfilms.online

### ISSUE THREAD

**Issue by healthforms** [ytdl-org/youtube-dl#21163]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.05.11**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://jpfilms.online/movies/lone-wolf-and-cub-baby-cart-to-hades

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free
