### ISSUE TITLE
youtube-dl DASH video: Show the ffmpeg command output

### ISSUE THREAD

**Issue by sant527** [ytdl-org/youtube-dl#21176]
I am using youtube-dl. I wanted to know how DASH videos are downloded using ffmpeg. Can we see in the verbose the ffmpge command output also

## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by remitamine** [comment]
youtube-dl does not use ffmpeg to download DASH videos.
