### ISSUE TITLE
Youtube-dl cannot download

### ISSUE THREAD

**Issue by DomagojDz** [ytdl-org/youtube-dl#21187]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by DomagojDz** [comment]
I have version 2019.05.20.
Ubuntu 18.04.2 LTS

When I enter URL of this video event, Youtube DL automatically downloads only audio recording.
When you click the video, it plays a short 10 sec video jingle. After that, real video follows.
There is a link to audio version, that is what ytb-dl downloads, but:

How do I make it donwload the video instead?

Here's the link, take any interview (except first on a list for each day)

https://digitaldementiasummit.com

**Comment by bitraid** [comment]
I only see one video on this site (which downloads fine) - maybe it needs registration to access the "interviews"? Anyway, the "Ask question" issue template is not the right one for this case. You should provide the url of a video and the verbose log of youtube-dl. You might also want to try the `-F` switch to view the available formats (and then use the `-f` switch to select the one you want, if there are more than one).

**Comment by DomagojDz** [comment]
Yes, one must be registered to access interviews. It is not complicated. Whatever I do, youtube-dl "sees" only audio recording that is provided on a link below video while it plays. Each day there is one intro video and other videos are in form of interviews. Those interviews are what I am trying to rip.

**Comment by bitraid** [comment]
It is expected for youtube-dl to fail if the site requires login. You can try the `--cookies` option (make sure you have read the README and FAQ on how to use it, and how to output and post the verbose log).

**Comment by DomagojDz** [comment]
Anyway, youtube-dl recognizes no video on the web page regardless that video is actually playing. And I am unable to locate actual link to it on a page.

**Comment by bitraid** [comment]
>youtube-dl recognizes no video on the web page 

Thats because there is no video unless you are logged in.

>regardless that video is actually playing.

Thats because you are logged in with the browser - that doesn't give access to youtube-dl.
**You must use the browser's cookies.**

**Comment by DomagojDz** [comment]
I saved browser cookies in a file and ran:

youtube-dl --cookies /home/domagoj/cookies.txt https://digitaldementiasummit.com/expert/jay-davidson/

and it won't work, but is this path to cookies.txt in line with how linux works?

**Comment by DomagojDz** [comment]
'''youtube-dl --cookies /home/domagoj/cookies.txt https://digitaldementiasummit.com/expert/jay-davidson/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--cookies', u'/home/domagoj/cookies.txt', u'https://digitaldementiasummit.com/expert/jay-davidson/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] jay-davidson: Requesting header
WARNING: Falling back on generic information extractor.
[generic] jay-davidson: Downloading webpage
[generic] jay-davidson: Extracting information
[download] Downloading playlist: Jay Davidson - Digital Dementia Summit
[generic] playlist Jay Davidson - Digital Dementia Summit: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://hto-content.s3.amazonaws.com/user_videos/255bd064-d0b7-48d5-9e37-42bf83f2ce49/audio/mp3/128/255bd064-d0b7-48d5-9e37-42bf83f2ce49.mp3'
[download] Jay Davidson - Digital Dementia Summit-jay-davidson.mp3 has already been downloaded
[download] 100% of 29.71MiB
[download] Finished downloading playlist: Jay Davidson - Digital Dementia Summit'''
