### ISSUE TITLE
'list' 'index' not recognized as an interne command

### ISSUE THREAD

**Issue by nico92GitHub** [ytdl-org/youtube-dl#21180]
Hello!
I run youtube-dl from a batch (.bat) that calls a .vbs script to grab the clipboard's contents after I've copied the url address into youtube.com.
Often times, youtube-dl displays something like:
'list' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
[youtube] 0bcIjILqORM: Downloading webpage
[youtube] 0bcIjILqORM: Downloading video info webpage
[download] Destination: Whole Lotta Love (Remaster)-0bcIjILqORM.mp4
[download] 100% of 9.33MiB in 00:01
'list' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
     (from this adr: https://www.youtube.com/watch?v=0bcIjILqORM)
- - - - - - - - or:
[youtube] Z66Q8Px_2fc: Downloading webpage
[youtube] Z66Q8Px_2fc: Downloading video info webpage
[download] Destination: JAWA HISTORY 1929-1980  photos and videos-Z66Q8Px_2fc.mp4
[download] 100% of 66.73MiB in 00:06
     (from this adr: https://www.youtube.com/watch?v=Z66Q8Px_2fc)

In any case, the video is downloaded correctly and readable.

What is your point of view about these non-blocking error messages ???
Looking forward to your return,
Best regards,
Nicolas

**Comment by bitraid** [comment]
You must add quotes to the url.

**Comment by nico92GitHub** [comment]
Ok, merci :)
I did not think about it, but I just corrected my script and everything is OK!
Regards,
Nico
