### ISSUE TITLE
How to download summit videos

### ISSUE THREAD

**Issue by DomagojDz** [ytdl-org/youtube-dl#21196]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I am trying to download videos from here https://digitaldementiasummit.com/dznprs/ but youtube-dl is downloading only .mp3 provided on the same web page. I download such events quite often but since Firefox plugins became unable to do it recently, I am struggling to satisfy youtube-dl without any success.
Can anyone simply register to this event and try it, instead of making a whole thread of discussion?

This is the best I achieved so far:

youtube-dl https://digitaldementiasummit.com/expert/jay-davidson/ --cookies /home/domagoj/cookies.txt -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://digitaldementiasummit.com/expert/jay-davidson/', u'--cookies', u'/home/domagoj/cookies.txt', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] jay-davidson: Requesting header
WARNING: Falling back on generic information extractor.
[generic] jay-davidson: Downloading webpage
[generic] jay-davidson: Extracting information
[download] Downloading playlist: Jay Davidson - Digital Dementia Summit
[generic] playlist Jay Davidson - Digital Dementia Summit: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://hto-content.s3.amazonaws.com/user_videos/255bd064-d0b7-48d5-9e37-42bf83f2ce49/audio/mp3/128/255bd064-d0b7-48d5-9e37-42bf83f2ce49.mp3'
[download] Jay Davidson - Digital Dementia Summit-jay-davidson.mp3 has already been downloaded
[download] 100% of 29.71MiB
[download] Finished downloading playlist: Jay Davidson - Digital Dementia Summit

**Comment by bitraid** [comment]
I took a closer look and it seems that these are segmented vimeo videos, which youtube-dl can't download directly. You have to open the (browser) inspector (on the page) go "Network -> XHR", find and click on a "Name" with `*.m3u8` and from the "Headers" copy the "Request URL" and pass it to youtube-dl.

**Comment by DomagojDz** [comment]
Thanks, there's nothing with .m3u8 extension. And where is "Name" actually located?
![Screenshot from 2019-05-24 21-36-56](https://user-images.githubusercontent.com/50909676/58352738-c8168e80-7e6c-11e9-8787-ef25164077e3.png)

**Comment by bitraid** [comment]
At your inspector, it's in the "File" field called `playlist.m3u8`.

**Comment by DomagojDz** [comment]
Something's moving now :-) let's see how it ends (but it downloads at the speed of streaming).
Thanks!

**Comment by DomagojDz** [comment]
OK, this works, but with one caveat in case of using "/" for multiple targets. 
If I set youtube-dl to rip multiple streams one after another, it returns "playlist-playlist.mp4 already downloaded" because it gives the same name to each output file (playlist-playlist.mp4), instead of adding numbers to a "copy", eg . "playlist-playlist(1).mp4"

**Comment by remitamine** [comment]
use original Vimeo URLs(pass `--referer` option if needed).

**Comment by bitraid** [comment]
>OK, this works, but with one caveat in case of using "/" for multiple targets.

I think you've misunderstood the use of `/`.

>each output file has the same name.

Use `-o` option to set the name beforehand.

**Comment by DomagojDz** [comment]
> use original Vimeo URLs(pass `--referer` option if needed).

Bitraid, you think this is possible in this case?

I do separate streams with "/" and yt-dl catches it but gives same names to outputs. I'll try with -o

**Comment by bitraid** [comment]
The only vimeo link the page provides is that of the playlist. If you view the page source and search for `m3u8`, you will find the playlist url (in the `src` field of `player.playlist`) pointing to vimeo.com - but still outputs the same name for each file.
