### ISSUE TITLE
Gounlimited.to - Extractor question

### ISSUE THREAD

**Issue by Micelar** [ytdl-org/youtube-dl#21198]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, i have recently tried to make extractor for gounlimited however i see that there is no video tag included in view-source, probably that tag is included in their javascript so my question is, is that possible to grab that tag from their javascript? 

Please do not judge me as my python skill is near 0 but im trying to learn :)

**Comment by dstftw** [comment]
If browser does this then it's obviously possible.
