### ISSUE TITLE
Does youtube-dl consider passwords with a semicolon as invalid

### ISSUE THREAD

**Issue by WillPittenger** [ytdl-org/youtube-dl#21190]
My YouTube password has a semicolon in the password.  I tried the password both with and without quotes.  Each time, I'm told the password is invalid.  Yet, both the user name and password were entered correctly.  Do I need to escape the semicolon?

**Comment by dstftw** [comment]
Escaping rules depend on your shell.

**Comment by WillPittenger** [comment]
Then I should have mentioned the password was specified in the configuration file. I'm using PowerShell as my shell on Windows 10.
