### ISSUE TITLE
[tvnow] 1080p possible with m3u8 from page source

### ISSUE THREAD

**Issue by starvedhorror** [ytdl-org/youtube-dl#21201]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've searched the bugtracker for similar issues including closed ones

Example URL

https://www.tvnow.de/serien/wir-sind-jetzt-17556/staffel-1/episode-2-hangover-bullenreiten-und-ein-daniel-im-gebuesch-1584891

Feeding the above link directly into youtube-dl limits the download options to this (a few separate audio/video tracks too, but that doesn't seem to be relevant), essentially limiting the video downloaded to ~1 gigabyte 540p with 3300k bitrate.

hls-666             mp4        640x360     666k , avc1.4D001F@ 500k, 25.0fps, mp4a.40.2@128k
hls-1196            mp4        640x360    1196k , avc1.4D001F@1000k, 25.0fps, mp4a.40.2@128k
hls-1726            mp4        960x540    1726k , avc1.4D001F@1500k, 25.0fps, mp4a.40.2@128k
hls-3316            mp4        960x540    3316k , avc1.4D001F@3000k, 25.0fps, mp4a.40.2@128k

However it is possible to get a proper 1080p/~8000k/~2.5GB video searching the page source, looking for the last m3u8 playlist there (there are 3 of them, and the last one is the correct one). In this case it is

https://vodnowusoawshls.secure.footprint.net/proxy195/clear/ngvod/tvnow/1584891-3-14157.ism/fairplay.m3u8

The options for it are

666          mp4        640x360     666k , avc1.4D001F@ 500k, 25.0fps, mp4a.40.2@128k
1196         mp4        640x360    1196k , avc1.4D001F@1000k, 25.0fps, mp4a.40.2@128k
1726         mp4        960x540    1726k , avc1.4D001F@1500k, 25.0fps, mp4a.40.2@128k
3316         mp4        960x540    3316k , avc1.4D001F@3000k, 25.0fps, mp4a.40.2@128k
6496         mp4        1280x720   6496k , avc1.64001F@6000k, 25.0fps, mp4a.40.2@128k
8616         mp4        1920x1080  8616k , avc1.640028@8000k, 25.0fps, mp4a.40.2@128k

This is all done without login in, simply by going to the page.

Essentially youtube-dl does not recognize the best possible video source (playlist) for [tvnow], and it would be nice if it did so without going into the page source.

**Comment by starvedhorror** [comment]
As a side note it is also possible to download premium episodes (i.e. unavailable without registration) by using the last link & substituting the episode ID with the one you need. 

https://vodnowusoawshls.secure.footprint.net/proxy195/clear/ngvod/tvnow/[EPISODE-ID].ism/fairplay.m3u8

Though first you will need to get said ID by feeding the episode link into youtube-dl and using the -g command with it.

**Comment by e2iplayer** [comment]
Do you know what fairplay mean?
Your links are DRM protected. 
Did you try to play them for example in the VLC?

**Comment by starvedhorror** [comment]
They are not DRM protected & download perfectly well. And yes, they also play in VLC. They might be region locked though, but a VPN can help with that.

**Comment by e2iplayer** [comment]
OK - thank you for the info.
