### ISSUE TITLE
ERROR: Error in output template: incomplete format (encoding: 'cp1252')

### ISSUE THREAD

**Issue by Coder-Book** [ytdl-org/youtube-dl#21202]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: ['-o', 'W:/YouTube/%(uploader)s/%(playlist)s/%(title)s.%(ext)']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?list=PL-p5XmQHB_JTcMSvPmXMzNe7ZPMxEx_Oz', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.7.3 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] PL-p5XmQHB_JTcMSvPmXMzNe7ZPMxEx_Oz: Downloading webpage
[download] Downloading playlist: i3 Ricing and Configuration
[youtube:playlist] playlist i3 Ricing and Configuration: Downloading 15 videos
[download] Downloading video 1 of 15
[youtube] 7t6iOag6kcE: Downloading webpage
[youtube] 7t6iOag6kcE: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
ERROR: Error in output template: incomplete format (encoding: 'cp1252')
Traceback (most recent call last):
  File "c:\users\aiden\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 710, in prepare_filename
    filename = expand_path(outtmpl).replace(sep, '') % template_dict
ValueError: incomplete format
```

## Description

After I created my `youtube-dl.conf` file in my local user directory, I started getting the error `ERROR: Error in output template: incomplete format (encoding: 'cp1252')`. I have no clue as to if the issue is because of the `-o` option in my config or a video encoding error

**Comment by remitamine** [comment]
missing `s` character at the end of the output template.

**Comment by The-Deepest-Net** [comment]
You can add % symbol to escape, Example:
`youtube-dl -o "%%(title)s.%%(ext)s" ` (**URL**)
