### ISSUE TITLE
more user frendly format selection syntax

### ISSUE THREAD

**Issue by ArtiiP** [ytdl-org/youtube-dl#21215]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

for now to select video other than best i must write some magic code for -f option

may by better just accept easy to remember strings like 480p 720p >360p(this one select 480 but not 720 1080p)  1080p 720p.mp4 720p.webm etc 

in this mode audio format selected automaticaly without transcoding (if posible already "mixed' in stream)

**Comment by dstftw** [comment]
I don't see any point in this. `[height>360]` is not any harder to remember that `>360p`. Format selection syntax is quite straightforward and simple while also flexible. Introducing another less flexible notation does not make any sense.
