### ISSUE TITLE
Sooviet Movies Online

### ISSUE THREAD

**Issue by jimlynnjulian** [ytdl-org/youtube-dl#21213]
## Checklist

- [x ] I'm reporting a new site support request
- [x ] I've verified that I'm running youtube-dl version **2019.05.20**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that none of provided URLs violate any copyrights
- [x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

-https://sovietmoviesonline.com/drama/73-andrey-rublev.html

## Description
In all cases, the video dowloaded is a 20 minute segment and no more. A page with multi-part videos downloads all parts but no longer than 20 minute segments.

**Comment by dstftw** [comment]
The video on the page is 20 minutes long.
