### ISSUE TITLE
Need help please! Downloading private video - can't add credentials

### ISSUE THREAD

**Issue by karen1nicola** [ytdl-org/youtube-dl#21212]
Hi

I'm new to all this. I'm trying to save some videos from fb that my sister uploaded of my nieces (i've got them in SD via the source code method, but I really want to save them in the max quality). They are private videos so I  know I need to add credentials, but I can't figure out how to do it.

I started:  with youtube-dl "https://www.facebook.com/carlyshipp84/videos/pcb.10161812542360113/10161812540565113"
which returned this:
[facebook] 10161812540565113: Downloading webpage
[facebook] 10161812540565113: Downloading webpage
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.

and this is where I came unstuck. I don't know how to format/write the entry correctly to make this work. 

I tried: 
youtube-dl --XXXXXXXX --XXXXXXX "https://www.facebook.com/carlyshipp84/videos/pcb.10161812542360113/10161812540565113"
(where the XXXXs are my actual username and password) but just get this back:
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: --XXXXXXXX

I tried to add my cookies in by making a copy of the file, sticking it on the desktop, adding 
#HTTP Cookie File as the first line (with a space after the hash - is that right?). I typed:

youtube-dl --cookies /Users/Karen1Nicola/Desktop/Cookies.txt "https://www.facebook.com/carlyshipp84/videos/pcb.10161812542360113/10161812540565113"
and that returned the same as the first time;
[facebook] 10161812540565113: Downloading webpage
[facebook] 10161812540565113: Downloading webpage
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
 
So I couldn't have added the cookies correctly. (And I noticed that a new Cookies.txt file appeared on the desktop that isn't the one I placed there)

I'm lost now! Can someone walk me through this step by step as if I'm an idiot please?!

Cheers

EDIT:

I just tried renaming the cookies file I put on the desktop to Cookies.txt (as it wasn't showing the extension) and ran this again:
youtube-dl --cookies /Users/Karen1Nicola/Desktop/Cookies.txt "https://www.facebook.com/carlyshipp84/videos/pcb.10161812542360113/10161812540565113"

and this came back:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 441, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 418, in __init__
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2318, in _setup_opener
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1165, in load
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 26: ordinal not in range(128)

EDIT2: I also tried the other video url I got for it, but it didn't make a difference:
youtube-dl --cookies /Users/Karen1Nicola/Desktop/Cookies.txt "https://www.facebook.com/carlyshipp84/videos/10161812530485113/"

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#authentication-options
