### ISSUE TITLE
404 error on codewithmosh

### ISSUE THREAD

**Issue by debendraoli** [ytdl-org/youtube-dl#21211]
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2019.05.20**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[generic] 357787: Requesting header
[redirect] Following redirect to https://codewithmosh.com/p/mastering-react
[generic] mastering-react: Requesting header
WARNING: Falling back on generic information extractor.
[generic] mastering-react: Downloading webpage
[generic] mastering-react: Extracting information
[TeachableCourse] Downloading codewithmosh.com login page
[TeachableCourse] Logging in to codewithmosh.com
[TeachableCourse] mastering-react: Downloading webpage
[download] Downloading playlist: Mastering React
[TeachableCourse] playlist Mastering React: Collected 201 video ids (downloading 201 of them)
[download] Downloading video 1 of 201
[Teachable] Downloading codewithmosh.com login page
[Teachable] Logging in to codewithmosh.com
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
## Description

I am using latest version of youtube-dl ` 2019.05.20` in my Arch Linux with python 3.7 installed.

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by debendraoli** [comment]
Yes I provided it in .netrc file.

Format:
`machine codewithmosh.com login <username> password <password>`

Command line:
`youtube-dl https://codewithmosh.com/courses/enrolled/357787 --netrc`

**Comment by designDemon** [comment]
did this finally work on codewithmosh.

If yes can you guide me through it please.. thanks.
