### ISSUE TITLE
Extracted broken urls, 403 error

### ISSUE THREAD

**Issue by serkandaglioglu** [ytdl-org/youtube-dl#21218]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

For https://www.youtube.com/watch?v=LOZuxwVk7TU video I extract download urls in my localhost and in my server with youtube-dl. I extract urls with "youtube-dl --skip-download --write-info-json" command. 

Both of localhost and server is extract different urls for same format. 
For example for m4a file :

Localhost extracted m4a url = https://r2---sn-hgn7yn7l.googlevideo.com/videoplayback?id=o-AJEGmXtIF19RHVjn7UPNTNP_G78DgbhnyeXGG8Jm8Jnm&itag=140&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-hgn7yn7l%2Csn-hpa7znsd&ms=au%2Conr&mv=m&pl=22&ei=tVfqXMG5KMPT1gKV_bvgBA&gcr=tr&initcwndbps=823750&mime=audio%2Fmp4&gir=yes&clen=3417069&dur=211.069&lmt=1556970060308142&mt=1558861634&fvip=2&keepalive=yes&c=WEB&txp=5532432&ip=46.196.21.103&ipbits=0&expire=1558883349&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cgcr%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&key=yt8&signature=9C6D65520F230002ED31B34C1D90EBBD4A64F7A9.3B716F9D4BC46BC37EFB941EF273D93EC245B1C3&ratebypass=yes

In my server extracted m4a url = https://r2---sn-ab5szn7r.googlevideo.com/videoplayback?id=o-AOi8DBUZ4DtIzRi0JDRcbb9w1E-kHtHKu4bnZzEMHQtG&itag=140&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-ab5szn7r%2Csn-ab5l6nsk&ms=au%2Crdu&mv=m&pl=23&ei=1FfqXIWjLNPVhwak4abgBQ&gcr=us&initcwndbps=122500&mime=audio%2Fmp4&gir=yes&clen=3417069&dur=211.069&lmt=1556970060308142&mt=1558861634&fvip=3&keepalive=yes&c=WEB&txp=5532432&ip=142.93.50.2&ipbits=0&expire=1558883380&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cgcr%2Cinitcwndbps%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&key=yt8&signature=5509305939EFDFBD2787AF3E3083885F84A74BA4.DA8C53AAECEA090BA033BBA50F38450FCBBCF939&ratebypass=yes

The problem is localhost m4a url is working and i download m4a file without any problem. But in server when i try to download m4a file it throws 403 forbidden error for extracted download url.

This stuation is same for many videos. I tried many videos in my localhost and it worked for all. But when i tried many videos in my server it doesnt worked most of videos, extracted download urls throws 403 forbidden error. But in server sometimes it works for some other videos.

In my server I extract urls with "youtube-dl --skip-download --write-info-json" and getting download m4a url from json file and url is broken. But when I list formats with "youtube-dl -F URL" and download m4a with this command "youtube-dl -f 140 URL" youtube download the m4a file without any problem but when i try to download file with extracted m4a url in json file it throws 403 error.

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser
