### ISSUE TITLE
List of other sites like Youtube

### ISSUE THREAD

**Issue by nico92GitHub** [ytdl-org/youtube-dl#21227]
Hello!

Before coming here, I searched without success on "https://github.com/ytdl-org/youtube-dl/blob/master/README.md#faq" a list of other sites where youtube-dl can download videos.
The only information found on this subject is "from YouTube.com and a few more sites".
Please, what are these "few more sites" ?
Because, I run youtube-dl from a .bat which itself launches a .vbs script to retrieve the contents of the clipboard after making a copy of a URL only on youtube currently.
In the content of the clipboard recovered, I test the string "youtube.com" to filter.
That's why I'd like to know the list of possible sites to add other filters. Ouf!

While waiting for your answer, congratulations for this youtube-dl project that works perfectly with its many options.

Regards,
Nicolas

**Comment by Hrxn** [comment]
https://github.com/ytdl-org/youtube-dl/blob/master/docs/supportedsites.md

?

**Comment by dstftw** [comment]
You should not filter URLs in the first place since generic extractor can potentially handle any URL.
