### ISSUE TITLE
The Great Courses Plus

### ISSUE THREAD

**Issue by huyansm** [ytdl-org/youtube-dl#21221]
## Checklist

- [x ] I'm reporting a new site support request
- [ x] I've verified that I'm running youtube-dl version **2019.05.20**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that none of provided URLs violate any copyrights
- [ x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

https://www.thegreatcoursesplus.com/films/title/linear-algebra-powerful-transformations

I'll send account via PM

**Comment by huyansm** [comment]
The other post is currently closed, how to re-open a request?

**Comment by idiosyn** [comment]
Where is the other thread? I can't find it.
