### ISSUE TITLE
postprocessing functionality

### ISSUE THREAD

**Issue by divya369** [ytdl-org/youtube-dl#21226]
## Checklist

- [ ] I'm reporting a feature request
- [ ] I've verified that I'm running youtube-dl version **2019.05.20**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
We are trying to download the video using youtube_dl object in python scripting. During the preprocessing, we want our audio file with these following configuration :
1. Channel : mono
2. Encoding : pcm16

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#post-processing-options
