### ISSUE TITLE
 Site Support Request: rtp.pt

### ISSUE THREAD

**Issue by Snow344** [ytdl-org/youtube-dl#21220]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.rtp.pt/play/p4897/a-guerra-dos-abismos
- Single video: https://www.rtp.pt/play/p4897/e409009/a-guerra-dos-abismos

**Comment by somini** [comment]
This was closed without any comment, see #20484
