### ISSUE TITLE
[facebook] Unable to extract thumbnail URL

### ISSUE THREAD

**Issue by endzi007** [ytdl-org/youtube-dl#21224]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\Admin\Documents\programiranje\newDesktopDownloader\static>youtube-dl --
get-thumbnail https://www.facebook.com/365daysshow/videos/230504267825765/ --ver
bose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--get-thumbnail', 'https://www.facebook.com/365daysshow/videos/230504267825765/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-93385-g85649b6523, ffprobe N-93385-g85649b6523
[debug] Proxy map: {}
WARNING: unable to extract thumbnail URL; please report this issue on https://yt
-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  t
o update. Be sure to call youtube-dl with the --verbose flag and include its com
plete output.
[debug] Default format spec: bestvideo+bestaudio/best
```

## Description

Not able to extract thumbnail, even when I try to with --dump-json, I get JSON but thumbnail field value is "null". 
I'm using youtube-dl on windows 7 machine.
P.S. I am able to download video with no problems.

**Comment by ruyihaoren** [comment]
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.6.6 (CPython) - Linux-2.6.18-194.32.1.el5PAE-i686-with-redhat-5.11-Final
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 427495184498179: Downloading webpage
WARNING: unable to extract thumbnail URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: best/bestvideo+bestaudio

**Comment by ruyihaoren** [comment]
$ youtube-dl 'https://www.facebook.com/scifrimacroscope/videos/344349012932332/' -o astoryofsas.mp4 --write-thumbnail --verbose             
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.facebook.com/scifrimacroscope/videos/344349012932332/', u'-o', u'astoryofsas.mp4', u'--write-thumbnail', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 2.6.6 (CPython) - Linux-2.6.18-194.32.1.el5PAE-i686-with-redhat-5.11-Final
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 344349012932332: Downloading webpage
WARNING: unable to extract thumbnail URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://scontent-icn1-1.xx.fbcdn.net/v/t39.24130-6/10000000_166546651030238_625299862115664586_n.mp4?_nc_cat=111&efg=eyJ2ZW5jb2RlX3RhZyI6Im9lcF9oZCJ9&_nc_ht=scontent-icn1-1.xx&oh=0b2611d036064208f9c535b47327dbd0&oe=5D5B6622'
