### ISSUE TITLE
Copyright 

### ISSUE THREAD

**Issue by Mikolaj98p** [ytdl-org/youtube-dl#21237]
## Checklist

- [ x ] I'm asking a question
- [ x ] I've looked through the README and FAQ for similar questions
- [ x ] I've searched the bugtracker for similar questions including closed ones

## Question

I have "bug" on downloading music from `https://www.youtube.com/watch?v=RZ9c7SOzPDo`
Youtube-dl prints: `ERROR: This video contains content from TOY'S FACTORY INC., who has blocked it on copyright grounds.`.

**Comment by jcousins-ynap** [comment]
It will be blocked on youtube. This is not an issue for this repo.
