### ISSUE TITLE
Ability to force use of cookies instead of MSO provider

### ISSUE THREAD

**Issue by dellis87** [ytdl-org/youtube-dl#21231]
## Checklist

- [x ] I'm reporting a feature request
- [x ] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Would like the ability to force the use of cookies instead of a MSO provider.  I currently have DIsh and YouTubeTV.  Neither of these are supported providers, but I am able to use cookies on all scripps sites.  However, sites like TBS, FX, and Disney I get the message that I have to use a MSO provider.  I would like to request that a force use of cookies option be added to the extractors. 

d@ellis-media:/mnt/c/youtube-dl$ python3 ./youtube-dl --cookies=/mnt/c/youtube-dl/tbsnew.txt https://www.tbs.com/movies/star-wars-the-force-awakens-theatrical --output '/mnt/c/Videos/%(title)s/%(title)s.%(ext)s' --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies=/mnt/c/youtube-dl/tbsnew.txt', 'https://www.tbs.com/movies/star-wars-the-force-awakens-theatrical', '--output', '/mnt/c/Videos/%(title)s/%(title)s.%(ext)s', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.6.7 (CPython) - Linux-4.4.0-17763-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[TBS] star-wars-the-force-awakens-theatrical: Downloading webpage
[TBS] 5025c3110be2275a9269a69c172028be5002779e: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/tbs.py", line 59, in _real_extract
    'auth_required': video_data.get('authRequired') == '1',
  File "./youtube-dl/youtube_dl/extractor/turner.py", line 212, in _extract_ngtv_info
    m3u8_url, media_id, ap_data or {}, tokenizer_query)
  File "./youtube-dl/youtube_dl/extractor/turner.py", line 40, in _add_akamai_spe_token
    query['accessToken'] = self._extract_mvpd_auth(ap_data['url'], content_id, ap_data['site_name'], ap_data['site_name'])
  File "./youtube-dl/youtube_dl/extractor/adobepass.py", line 1409, in _extract_mvpd_auth
    raise_mvpd_required()
  File "./youtube-dl/youtube_dl/extractor/adobepass.py", line 1374, in raise_mvpd_required
    'and --ap-username and --ap-password or --netrc to provide account credentials.', expected=True)
youtube_dl.utils.ExtractorError: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.

**Comment by remitamine** [comment]
cookies can't be used to authorize Adobe Pass requests for Turner Media websites.
