### ISSUE TITLE
【Essential Feature Needed】Automatically remove dot(.) at the end of filename/dirname.

### ISSUE THREAD

**Issue by Originalimoc** [ytdl-org/youtube-dl#21239]
Filename end with a dot is not well supported across Linux/Windows.
When `%(uploader)s` or `%(title)s` and other vars contain a dot at the end, may create a file or folder can't be managed by the system and fail to create on SMB/CIFS if downloading to remote.

**Comment by Originalimoc** [comment]
and add --nodotremoval option to maintain current behavior is ideal.

**Comment by dstftw** [comment]
Dot at the end of path point is already sanitized by `#` on Windows.

**Comment by Originalimoc** [comment]
Client on Linux downloading to remote SMB/CIFS has problem.
