### ISSUE TITLE
how to use proper formatting option in the case of skipping unavailable video from playlist

### ISSUE THREAD

**Issue by apache123** [ytdl-org/youtube-dl#21232]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

when a video is unavailable in a playlist the naming format that I use is look like that, the ordering numbers are skipping the number of unavailable video for example in this case it skipped number 3 and other numbers how can i fix that. I use this formatting style
-o "~/Users/apachee/%(playlist)s/%(chapter)s/%(playlist_index)s-%(title)s.%(ext)s"
<img width="252" alt="Screen Shot 2019-05-27 at 7 22 54 PM" src="https://user-images.githubusercontent.com/9536310/58431490-c5a77500-80b6-11e9-91bc-429be9ecb6e9.png">

**Comment by dstftw** [comment]
Fix what? This is correct and expected behavior.

**Comment by apache123** [comment]
I mean the order of number I want it to be 1,2,3,4,5,6 but it is 1,2,4,6,8,11
