### ISSUE TITLE
[Crunchyroll] can't download in 720p and 1080p

### ISSUE THREAD

**Issue by Ripper346** [ytdl-org/youtube-dl#21243]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
.\youtube-dl.exe -v -F 'https://www.crunchyroll.com/it/a-certain-magical-index/episode-1-unrest-777723'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.crunchyroll.com/it/a-certain-magical-index/episode-1-unrest-777723']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-91961-g5109c38162, ffprobe N-91961-g5109c38162
[debug] Proxy map: {'no': '192.168.99.100'}
[crunchyroll] 777723: Downloading webpage
[crunchyroll] 777723: Downloading media info for 480p
[crunchyroll] 777723: Downloading stream info for 480p
[crunchyroll] 777723: Downloading m3u8 information
[crunchyroll] 777723: Downloading media info for 360p
[crunchyroll] 777723: Downloading stream info for 360p
[crunchyroll] 777723: Downloading m3u8 information
[crunchyroll] 777723: Downloading media info for 1080p
[crunchyroll] 777723: Downloading stream info for 1080p
[crunchyroll] 777723: Downloading media info for 720p
[crunchyroll] 777723: Downloading stream info for 720p
[crunchyroll] 777723: Downloading media info
[info] Available formats for 777723:
format code  extension  resolution note
hls-398-0    mp4        428x240     398k , avc1.42c015, 23.974fps, mp4a.40.2
hls-398-1    mp4        428x240     398k , avc1.42c015, 23.974fps, mp4a.40.2
hls-398-2    mp4        428x240     398k , avc1.42c015, 23.974fps, mp4a.40.2
hls-398-3    mp4        428x240     398k , avc1.42c015, 23.974fps, mp4a.40.2
hls-398-4    mp4        428x240     398k , avc1.42c015, 23.974fps, mp4a.40.2
hls-398-5    mp4        428x240     398k , avc1.42c015, 23.974fps, mp4a.40.2
hls-559-0    mp4        640x360     559k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-559-1    mp4        640x360     559k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-559-2    mp4        640x360     559k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-559-3    mp4        640x360     559k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-559-4    mp4        640x360     559k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-559-5    mp4        640x360     559k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-1034-0   mp4        848x480    1034k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-1034-1   mp4        848x480    1034k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-1034-2   mp4        848x480    1034k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-1034-3   mp4        848x480    1034k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-1034-4   mp4        848x480    1034k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-1034-5   mp4        848x480    1034k , avc1.4d401f, 23.974fps, mp4a.40.2 (best)
```

## Description

The maximum resolution for any video of Crunchyroll is now only 480p. From the website I can watch the same episodes in 720p or 1080p without being logged in. The same behavior is on single episode, playlist and different locale urls. Also it's no more visible the language of the versions (it seems that there isn't any subbed version among the 480p).

**Comment by Asusagawa** [comment]
You need to be logged in and have a Premium account.

**Comment by Atemu** [comment]
You didn't have to previously and other tools such as `streamlink` can still fetch high res streams just fine.

**Comment by Ripper346** [comment]
> You need to be logged in and have a Premium account.

So you are saying that I can watch in 1080p on the website but youtube-dl needs a premium account to have access to the same content I view for free?! Are you sure?

**Comment by Atemu** [comment]
Yup.

![image](https://user-images.githubusercontent.com/18599032/58579323-1354e680-824b-11e9-8b4e-4053e3e6d24c.png)

**Comment by darkhelmet2016** [comment]
Yes, unless otherwise stated you have to have a premium account to watch most content or use a program to download higher than 480p. The first ep is usually free in 720/1080p on their site.

**Comment by duncannah** [comment]
Yep, you were able to download 720p and 1080p before, and it works on the site too.

**Comment by TommoCrabb** [comment]
If you start playing the episode in your browser in 1080p; then use your browser's dev tools to get the URL of the m3u8 file; then feed the URL into youtube-dl; youtube-dl will download the episode in 1080p with no problems. 

I've never had any sort of account with Crunchyroll, premium or not, and I've managed to download the last two episodes of Shield Hero in 1080p using this method. The point being, there's no problem with youtube-dl being able to download the higher resolution streams, at the moment it just can't find where they are.

**Comment by TommoCrabb** [comment]
Oh, I should also point out that all of this is completely contingent on what country you're in and what show you're trying to watch, as I have discovered by using a VPN.

**Comment by darkhelmet2016** [comment]
And since this is not an actual bug and it works just fine when you log in this will probably get closed out.

**Comment by TommoCrabb** [comment]
> it works just fine when you log in

That would suggest that in the last two weeks Crunchyroll have changed how streams are loaded for people who aren't signed in, but left things unchanged for people who are signed in.

**Comment by Ripper346** [comment]
> If you start playing the episode in your browser in 1080p; then use your browser's dev tools to get the URL of the m3u8 file; then feed the URL into youtube-dl; youtube-dl will download the episode in 1080p with no problems.

That works, I was expecting that youtube-dl did it by itself like it did until no long time ago. But since that this isn't a lack of the software because "you have to get the premium for an already free thing" nor a bug because there isn't an actual error, I will look forward to download manually or use another software like the one wrote by atemu

**Comment by AlexIIL** [comment]
I've looked at this a little bit and it seems that 720p and 1080p are offered under `adaptive_hls`, but the others are not? I tried changing `youtube_dl/extractor/vrv.py`.`_extract_vrv_formats()` to accept `adaptive_hls` (in addition to `hls` and `dash`) and that seems to fix it. (Or is that unrelated to this?)

**Comment by TommoCrabb** [comment]
@AlexIIL is there any chance you could expand on what you did? I have no experience editing youtube-dl extractors. Cheers.

**Comment by AlexIIL** [comment]
Essentially I made this change to the code: https://github.com/AlexIIL/youtube-dl/commit/f85a1a32b59e15dad00b7b62c126930a5143f470. However I've not worked in python or with youtube-dl before so those might not be enough (ignoring the debug print statements).

**Comment by TommoCrabb** [comment]
@AlexIIL just tested your patch. Worked like a charm. Well done. Thanks.

**Comment by Index10** [comment]
I use it to get the streaming link from any episode (hardcoded), When I use the -F command, I always got all the resolutions to all the language available like:
`crunchyroll] 780923: Downloading audio-jaJP-hardsub-ruRU m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-itIT m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-arME m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-esES m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-frFR m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-deDE m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-esLA m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-enUS m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-ptBR m3u8 information`

But now I just get 
`[crunchyroll] Logging in
[crunchyroll] 782737: Downloading webpage
[crunchyroll] 782737: Downloading media info for 480p
[crunchyroll] 782737: Downloading stream info for 480p
[crunchyroll] 782737: Downloading m3u8 information
[crunchyroll] 782737: Downloading media info for 1080p
[crunchyroll] 782737: Downloading stream info for 1080p
[crunchyroll] 782737: Downloading media info for 360p
[crunchyroll] 782737: Downloading media info for 720p
[crunchyroll] 782737: Downloading stream info for 720p
[crunchyroll] 782737: Downloading media info`

And it just gives me 
`format code  extension  resolution note
hls-410-0    mp4        428x240     410k , avc1.42c015, 23.974fps, mp4a.40.2
hls-410-1    mp4        428x240     410k , avc1.42c015, 23.974fps, mp4a.40.2
hls-548-0    mp4        640x360     548k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-548-1    mp4        640x360     548k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-1025-0   mp4        848x480    1025k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-1025-1   mp4        848x480    1025k , avc1.4d401f, 23.974fps, mp4a.40.2 (best)`

It's a premium account, so I don't know what is happening.

**Comment by Atemu** [comment]
Both of your posted episodes work for me, are you on the newest version?  (2019.07.02)
