### ISSUE TITLE
Lossless codecs

### ISSUE THREAD

**Issue by Qbsoon** [ytdl-org/youtube-dl#21249]
- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

Hi! 
I wanted to request feature of downloading audio in lossless codecs. I'm downloading music with --audio-format m4a, but then I have aac, but I'd like to have alac.

**Comment by cfreds** [comment]
We download audio m4a format because YouTube is native. You cant download alls formats, only m4a and opus

**Comment by dstftw** [comment]
You can't download in lossless format since Youtube only serves lossy.
