### ISSUE TITLE
how can I specify number formatting

### ISSUE THREAD

**Issue by apache123** [ytdl-org/youtube-dl#21260]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

when I use autonumber the number would be 00001 then 00002 how can I make it 1 then 2 I don't want those zero before the number

**Comment by dstftw** [comment]
https://docs.python.org/2/library/stdtypes.html#string-formatting
