### ISSUE TITLE
Wait time between playlist

### ISSUE THREAD

**Issue by guidocaffa** [ytdl-org/youtube-dl#21263]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

It would be desirable for YouTube DL to have the option to set a timeout between each download video. When using the --batch-file command you can not configure wait times between each link, this would be useful for some sites that can block you from accessing the API.

**Comment by remitamine** [comment]
```
--sleep-interval SECONDS         Number of seconds to sleep before each
                                 download when used alone or a lower bound
                                 of a range for randomized sleep before each
                                 download (minimum possible number of
                                 seconds to sleep) when used along with
                                 --max-sleep-interval.
--max-sleep-interval SECONDS     Upper bound of a range for randomized sleep
                                 before each download (maximum possible
                                 number of seconds to sleep). Must only be
                                 used along with --min-sleep-interval.
```

**Comment by guidocaffa** [comment]
--sleep-interval and --max-sleep it's used (in pluralsight) to wait between each VIDEO, but what i want is to wait between each video collection (in pluralsight case is a course). For example, if i want to download a course, wihc is compose by many videos, the parameters is used to wait between EACH video, not between each course i put into my batch video list. I think this two parameters arn't for this....

**Comment by mysakthiivel** [comment]
you can use windows pc timeout command

**Comment by mysakthiivel** [comment]
Linux sleep command

**Comment by mysakthiivel** [comment]
youtube-dl www.
timeout 300 (second)
youtube-dl www.

**Comment by Nikain** [comment]
this function can cause youtube premium worth nothing ...

**Comment by rautamiekka** [comment]
To be fair, there ain't much of a point to YT Premium anyway.
