### ISSUE TITLE
[Site Support Request] add AsianCrush sister sites: Yuyutv and MidnightPulp (same player)

### ISSUE THREAD

**Issue by Kenifornication** [ytdl-org/youtube-dl#21281]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video (movie): https://www.midnightpulp.com/video/010400v/drifters/
- Single video (movie): https://www.yuyutv.com/video/013886v/the-act-of-killing/
- Single video (episode): https://www.yuyutv.com/video/peep-show/013922v-warring-factions/
- Series page: https://www.yuyutv.com/series/013920s/peep-show/

## Description

This is a sister site to AsianCrush (already supported by youtube-dl since https://github.com/ytdl-org/youtube-dl/commit/560050669b1e98bc76c797256c6e21719541b2ac), both of which use the same player and technology. Youtube-DL allows access to higher bitrate streams than available on the frontend which is what I'm after.

Please and thank you very much.

**Comment by ealgase** [comment]
Are there series pages on Midnight Pulp?

**Comment by Kenifornication** [comment]
> Are there series pages on Midnight Pulp?

indeed there is:
https://www.midnightpulp.com/series/017280s/creamy-mami/
https://www.midnightpulp.com/series/016375s/mononoke/

**Comment by ealgase** [comment]
Thanks.  I'm working on this extractor (fortunately pretty easy).

**Comment by Kenifornication** [comment]
> Thanks. I'm working on this extractor (fortunately pretty easy).

Thanks for taking a look at it, I would've given it a whirl myself if I knew either Python or Git lol
