### ISSUE TITLE
Add Ability To Skip ONLY Blocked YouTube Videos

### ISSUE THREAD

**Issue by faultywarrior** [ytdl-org/youtube-dl#21286]
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running youtube-dl version **2019.05.20**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I'd like to see the ability to have a more advanced version of the -i flag that only skips YouTube videos which are blocked, but still will cause a stop if any other error is encoutered.

**Comment by dstftw** [comment]
What is blocked in the first place? youtube-dl does not recognize blocked/private/georestricted/whatever. Provide example URLs.
