### ISSUE TITLE
Not able to download subs off Crunchyroll

### ISSUE THREAD

**Issue by WaifuKiller** [ytdl-org/youtube-dl#21287]
I was able to download subtitles a few month ago. And now this happens now. Also thank you for making this program really help me get better subtitles for my blu-ray collection!

F:\Test download\Anime TB>youtube-dl --skip-download --all-sub https://www.crunchyroll.com/bakemonogatari
[crunchyroll:playlist] bakemonogatari: Downloading webpage
[download] Downloading playlist: Bakemonogatari
[crunchyroll:playlist] playlist Bakemonogatari: Collected 12 video ids (downloading 12 of them)
[download] Downloading video 1 of 12
[crunchyroll] 610921: Downloading webpage
[crunchyroll] 610921: Downloading media info for 360p
WARNING: Unable to download XML: HTTP Error 429: Too Many Requests
[crunchyroll] 610921: Downloading stream info for 360p
WARNING: Unable to download XML: HTTP Error 429: Too Many Requests
[crunchyroll] 610921: Downloading media info for 480p
WARNING: Unable to download XML: HTTP Error 429: Too Many Requests
[crunchyroll] 610921: Downloading stream info for 480p
WARNING: Unable to download XML: HTTP Error 429: Too Many Requests
[crunchyroll] 610921: Downloading media info for 1080p
WARNING: Unable to download XML: HTTP Error 429: Too Many Requests
[crunchyroll] 610921: Downloading stream info for 1080p
WARNING: Unable to download XML: HTTP Error 429: Too Many Requests
[crunchyroll] 610921: Downloading media info for 720p
WARNING: Unable to download XML: HTTP Error 429: Too Many Requests
[crunchyroll] 610921: Downloading stream info for 720p
WARNING: Unable to download XML: HTTP Error 429: Too Many Requests
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by nichwall** [comment]
Did you ever get it working?

It looks like you tried downloading too many videos in too short of a time. I had a similar issue and waiting a little while fixed it. You can also use the `--sleep-interval` parameter to reduce the likelihood of it happening again.

Using youtube-dl 2020.05.03, your command worked on my machine and downloaded the videos as mp4 with embedded english subs without a problem.
