### ISSUE TITLE
[Crunchyroll] Title extractor broken

### ISSUE THREAD

**Issue by WhiteRabbit56** [ytdl-org/youtube-dl#21291]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe --verbose https://www.crunchyroll.com/fruits-basket
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.crunchyroll.com/fruits-basket']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.7.2 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg N-93542-gecdaa4b4fa, phantomjs 2.1.1
[debug] Proxy map: {}
[crunchyroll:playlist] fruits-basket: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\program files\python\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\program files\python\lib\site-packages\youtube_dl\extractor\common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "c:\program files\python\lib\site-packages\youtube_dl\extractor\crunchyroll.py", line 666, in _real_extract
    webpage, 'title')
  File "c:\program files\python\lib\site-packages\youtube_dl\extractor\common.py", line 1013, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "c:\program files\python\lib\site-packages\youtube_dl\extractor\common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Crunchyroll has updated their website, breaking the name regex.
Changing the regex on line 665 of extractor/crunchyroll.py resolves the issue.

`r'(?s)<h1[^>]*>\s*<span itemprop="name">(.*?)</span>'`

to

`r'(?s)<meta content="(.*?)" itemprop="name">'`

**Comment by Tazeki** [comment]
Can confirm I'm having the same issue with all playlists.  Thank you @WhiteRabbit56 for the quick fix!

**Comment by Lame11a** [comment]
Confirm for Internet Archive (https://archive.org).  Version 2019.05.20 worked on archive playlists on 6/5/2019, no longer works as of 6/6/2019.

**Comment by SwimmingLink** [comment]
Sorry for my ignorance, but is there an easy way for me to make this fix in Windows before the official fix is released? I only have my .exe. :\

**Comment by alexpizarroj** [comment]
@dstftw Is the PR from dunn good enough to merge? Can confirm I'm having the same issue on the windows version.

**Comment by SwimmingLink** [comment]
This still isn't working for me. Was the fix not included in the latest update? (Windows)

**Comment by dstftw** [comment]
Not included.
