### ISSUE TITLE
embeding translation subtitles from youtube are broken

### ISSUE THREAD

**Issue by voidplayer** [ytdl-org/youtube-dl#21295]
How to test it:

```
python -m youtube_dl  https://www.youtube.com/watch?v=utwOAxm6Cak --write-auto-sub --sub-lang en,de --embed-sub
```

```en``` subtitle work fine, ```de``` subtitle is messed up with random tags. If you download the subtitle without embedding it, it also works fine

**Comment by dstftw** [comment]
This is what Youtube serves for this video.
