### ISSUE TITLE
When download from twitch in the end it do "[ffmpeg] Fixing malformed AAC bitstream" and it take huge amount of space to do. 

### ISSUE THREAD

**Issue by hasnogaems** [ytdl-org/youtube-dl#21296]
Pretty often when I'm running out of space and downloading huge stream around 10 gig, this operation fail. What is weird if I manually download with ffmpeg source file that mmpeg trying to apply this "Fixing malformed AAC bitstream" to is fine and can be played after "Fixing malformed AAC bitstream" fails. 

But if it automatical download with https://www.godo.dev/tutorials/python-record-twitch/ and I get same error, then source file cannot be opened.

What this "Fixing malformed AAC bitstream" do, can it be turned off by default?

**Comment by Linuxdirk** [comment]
This also sometimes happens to already downloaded files when you provide multiple streams and one of the streams was already downloaded.

**Comment by dstftw** [comment]
You can skip this with `--fixup never` though the media will be most likely have playback issues.
