### ISSUE TITLE
Question: How do you download --all-formats except webm?

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [ytdl-org/youtube-dl#21293]
I'm trying to download all formats for DASH support using this article:

https://shkspr.mobi/blog/2017/07/using-youtube-to-transcode-videos-to-dash-on-the-command-line/

My question is: How can I download everything except .webm files?

**Comment by ealgase** [comment]
If you're doing this for DASH support, I'd use the Python library with some scripting.

**Comment by TimeTravelersHackedMe** [comment]
What do you mean? Is there some sample code you can refer to?

**Comment by ealgase** [comment]
Do you know Python?

**Comment by TimeTravelersHackedMe** [comment]
Very little but I'm open to it

**Comment by ealgase** [comment]
Install the youtube-dl Python module and check out the documentation https://github.com/ytdl-org/youtube-dl#embedding-youtube-dl (not great but you should be able to look up the functionality you need).

**Comment by TimeTravelersHackedMe** [comment]
Thanks! Guess I have to learn some py
