### ISSUE TITLE
Convert Audio To Single (Mono) Channel Audio

### ISSUE THREAD

**Issue by RomanScott** [ytdl-org/youtube-dl#21316]
## Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2019.05.20**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

Hello! I'm using the Python youtube-dl library. I was wondering if there was a way, in the 'postprocessors' section of the download options in the YoutubeDL() function, to make it so that we can change the number of audio channels, as I want to convert the audio I downloaded into mono channel.

Thank you

**Comment by dstftw** [comment]
You have to write a custom postprocessor.
