### ISSUE TITLE
login to youtube not working

### ISSUE THREAD

**Issue by MatrixView** [ytdl-org/youtube-dl#21313]
- [x ] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe -i -u ...... -p ....... :ytsubs --max-downloads 5 --skip-download -j --no-check-certificate --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-i', '-u', 'PRIVATE', '-p', 'PRIVATE', ':ytsubs', '--max-downloads', '5', '--skip-download', '-j', '--no-check-certificate', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-89894-g18e2ac032e, ffprobe N-67388-g37425fc, phantomjs 2.1.1, rtmpdump 2.4-47-gc26c541
[debug] Proxy map: {}
WARNING: Unable to log in: HTTP Error 400: Bad Request
```

## Description

Hi guys,

Since yesterday evening, about 12-15 hrs ago, I get:  "Unable to log in HTTP Error 400: Bad Request".  I've logged in with the same credentials in a browser and that works just fine.

Hopefully you can fix this...  or tell me what I'm doing wrong... [although I've been using the same commandline with those params (minus the verbose) for years successfully]

Thanx!

**Comment by MatrixView** [comment]
Nice that you closed this...  but a duplicate to what issue?   What I found with this error is that youtube-dl needed to be fixed in the past...   

Thanx!

**Comment by MatrixView** [comment]
@dstftw Could you please provide a link how to solve this...?  The duplicate tag doesn't help as other issues from the past with this error do not provide a solution...  :-(

**Comment by MatrixView** [comment]
This is for people that run into this issue too:
I've been looking for a workaround for hours, and finally found one!

What I've done is install the cookies plugin in chrome:
https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg?hl=en

Then go to https://youtube.com, login and press that cookie plugin button to save a cookies.txt
As an extra I also went to https://accounts.google.com/ and save another cookies2.txt file

I merged those 2 text files into one YT-cookies.txt file and then addes the following parameter to youtube-dl:

--cookies=YT-cookies.txt

of course you can prefix the txt file with the path.

...then login works again. :-)   at least, for me...

Shouldn't this be in the FAQ for youtube-dl?

**Comment by hub2git** [comment]
@matrixview, thanks for your last comment. I followed your instructions and am again able to log into my Youtube account. Appreciate it!

**Comment by MatrixView** [comment]
@hub2git Thanx for your appreciation, glad to have helped someone with this.

What seems to be even better is that youtube-dl automatically updates the given cookie file, so it doesn't seem to expire. I found out because I had the cookie file open in Notepad++ and it reports changes once I run my script (containing the youtube-dl line with the cookie parameter)

I understand it is frustrating for the admins of this project to support youtube-dl and so many sites, google authentication, etc... while users keep asking the same questions regularly, but sometimes you just don't know how to solve an error and any past reported issue that comes remotely close doesn't have a workaround either or got solved by a fix/update to the program itself.

I really love Youtube-DL, I use it almost as much as PowerShell and Xidel. It's invaluable in any webscraping/downloading toolbox.

**Comment by donmiyamar** [comment]
I tried the steps outline by @MatrixView after already attempting the same in Firefox. I still get the 400: Bad Request

```
[youtube:channel] Downloading login page
[youtube:channel] Looking up account info
[youtube:channel] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube:channel] replaced-here-for-privacy: Downloading channel page
[youtube:playlist] Downloading login page
[youtube:playlist] Looking up account info
[youtube:playlist] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube:playlist] replaced-here-for-privacy: Downloading webpage
[download] Downloading playlist: Uploads from Adison Briana
[youtube:playlist] replaced-here-for-privacy: Downloading page #1
[youtube:playlist] replaced-here-for-privacy: Downloading page #2
[youtube:playlist] playlist Uploads from replaced-here-from-someone: Downloading 225 videos
[download] Downloading video 1 of 225
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
```

**Comment by peteruhrig** [comment]
Same problem for me.

**Comment by sarffy1986** [comment]
Hello kérlek téged bocsánatot kérek mindenkitől de  én nem akárnék
proplémát soha nem is akartam senkivel én ha tudom megse próbáltam volna
soha
2020. febr. 27. 14:39 ezt írta ("Peter Uhrig" <notifications@github.com>):
