### ISSUE TITLE
[discussion] sites covered by generic extractor

### ISSUE THREAD

**Issue by ealgase** [ytdl-org/youtube-dl#21317]
# The problem
Many sites work with `youtube-dl`'s generic extractor.  However, the generic extractor often misses metadata, and doesn't often work for playlists.  This has resulted in some frustrating situations, such as #21142 (although that is definitely not the only one).
# The question
Should `youtube-dl` support sites that the generic extractor works for, to add support for metadata and playlists?

**Comment by crs00** [comment]
Yes.

**Comment by dstftw** [comment]
The general rule is not to add separate extractors (until pressing need) if the generic one is capable of handling.
