### ISSUE TITLE
ExtractorError: Unsupported URL: http://video.anyfiles.pl

### ISSUE THREAD

**Issue by esamo** [ytdl-org/youtube-dl#2131]
user@machine:~$ youtube-dl --verbose http://video.anyfiles.pl/Ziemia+planeta+tajemnic.+Najdziwniejsze+miejsca./Nauka+i+technologia/video/89499
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://video.anyfiles.pl/Ziemia+planeta+tajemnic.+Najdziwniejsze+miejsca./Nauka+i+technologia/video/89499']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.01.08
[debug] Python version 2.7.3 - Linux-3.2.0-58-generic-x86_64-with-Ubuntu-12.04-precise
[debug] Proxy map: {}
[generic] 89499: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 89499: Downloading webpage
[generic] 89499: Extracting information
ERROR: Unsupported URL: http://video.anyfiles.pl/Ziemia+planeta+tajemnic.+Najdziwniejsze+miejsca./Nauka+i+technologia/video/89499; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 155, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 346, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://video.anyfiles.pl/Ziemia+planeta+tajemnic.+Najdziwniejsze+miejsca./Nauka+i+technologia/video/89499; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

user@machine:~$ youtube-dl -U
youtube-dl is up-to-date (2014.01.08)

**Comment by ealgase** [comment]
Should be closed, site no longer exists.
