### ISSUE TITLE
WARNING: You have requested multiple formats but ffmpeg or avconv are not instal led. The formats won't be merged.

### ISSUE THREAD

**Issue by mevsme** [ytdl-org/youtube-dl#21315]
## Checklist

- [* ] I'm asking a question
- [* ] I've looked through the README and FAQ for similar questions
- [*] I've searched the bugtracker for similar questions including closed ones

## Question

At my previous Win  7 x64 I had ffmpeg available from CMD and I could do ````youtube-dl -f 134+140 URL```` and it worked fine. Now I have all the same config, ffmpeg installed into the PATH, youtube-dl too, but I get this error about missing ffmpeg or avconv. What possible problem can be? Is it permission issue? At the previous Windows system my youtube-dl was in the system32 directory and it worked fine. This time the binary was crashing and I put it into another PATH directory.

**Comment by crs00** [comment]
Use chocolatey to install ffmpeg.

**Comment by dstftw** [comment]
ffmpeg is not on your `%PATH%`.

**Comment by HanOddbjorn** [comment]
Just put ffmpeg.exe in the same folder as youtube-dl.exe
