### ISSUE TITLE
make acodec and vcodec selectable as the codec without additional information

### ISSUE THREAD

**Issue by Golutazem** [ytdl-org/youtube-dl#21323]
Multiple versions were tested, including a freshly built one from git 2e11e51c0 , version 2019.05.20.

At least for the avc1 and mp4a codecs, the selectors acodec and vcodec represent other additional information and it is currently not possible to specify a selector which selects 'any avc1' or 'any mp4a'. This feature would be to make such selection possible.

For example, a video can have formats avc1.64002a and avc1.4d4020 available for 1080p@60 and 720p@60.  This feature would make those selectable by vcodec=avc1 or another selector to be revealed to the user.

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#format-selection
> Also filtering work for comparisons = (equals), **^= (starts with)**, $= (ends with), *= (contains) and following string meta fields:
