### ISSUE TITLE
BitChute error

### ISSUE THREAD

**Issue by EchoTiger** [ytdl-org/youtube-dl#21320]
This error seems to pop whenever I try to use links from BitChute:

> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['https://www.bitchute.com/video/GJUfoPN11pc3', '--verbose']
> [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
> [debug] youtube-dl version 2019.05.20
> [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
> [debug] exe versions: ffmpeg N-92833-gfccba32b4c, ffprobe N-92833-gfccba32b4c
> [debug] Proxy map: {}
> [BitChute] GJUfoPN11pc3: Downloading webpage
> [BitChute] GJUfoPN11pc3: Checking video URL
> ERROR: Unable to download webpage: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\extractor\common.py", line 626, in _request_webpage
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\YoutubeDL.py", line 2227, in urlopen
>   File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
>   File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
>   File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpt31j5y3w\build\youtube_dl\utils.py", line 1140, in https_open
>   File "C:\Python\Python34\lib\urllib\request.py", line 1186, in do_open
>   File "C:\Python\Python34\lib\http\client.py", line 1227, in getresponse
>   File "C:\Python\Python34\lib\http\client.py", line 386, in begin
>   File "C:\Python\Python34\lib\http\client.py", line 356, in _read_status
>

**Comment by dstftw** [comment]
```
> py -3.6 .\youtube_dl\__main__.py https://www.bitchute.com/video/GJUfoPN11pc3
[BitChute] GJUfoPN11pc3: Downloading webpage
[BitChute] GJUfoPN11pc3: Checking video URL
[download] Destination: Why Christianity Isn't Good For Europe-GJUfoPN11pc3.mp4
[download]   1.7% of 14.30MiB at 320.03KiB/s ETA 00:44
ERROR: Interrupted by user
```

**Comment by EchoTiger** [comment]
Yea, must've been something with the website when I was trying.
All seems completely fine today.
