### ISSUE TITLE
'convertsubtitles'

### ISSUE THREAD

**Issue by maaiika** [ytdl-org/youtube-dl#21353]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by maaiika** [comment]
'convertsubtitles': "ass" dosnot work in python
def youtube_download(youtube_url):
    ydl_opts = {
        'proxy':'socks5://127.0.0.1:1081',
        'outtmpl': '%(id)s%(ext)s',
        'formats' : '1',
        #'allsubtitles': True,

        'writesubtitles':True,
        'writeautomaticsub':True,
        'subtitleslangs':['en'],
        'convertsubtitles': "ass",


    }

    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download([youtube_url])

if __name__ == '__main__':
    youtube_download('https://www.youtube.com/watch?v=lMZY_9QNe4I')

[youtube] lMZY_9QNe4I: Downloading webpage
[youtube] lMZY_9QNe4I: Downloading video info webpage
[youtube] lMZY_9QNe4I: Looking for automatic captions
[info] Writing video subtitles to: lMZY_9QNe4Imp4.en.vtt
[download] lMZY_9QNe4Imp4.mp4 has already been downloaded and merged


but works in cmd
youtube-dl -f 137/136/22/18+140 --write-sub --write-auto-sub --sub-lang en --convert-subs ass https://www.youtube.com/watch?v=lMZY_9QNe4I --proxy socks5://127.0.0.1:1081
[youtube] lMZY_9QNe4I: Downloading webpage
[youtube] lMZY_9QNe4I: Downloading video info webpage
[youtube] lMZY_9QNe4I: Looking for automatic captions
[info] Writing video subtitles to: Primitive Technology - Polynesian Arrowroot Flour-lMZY_9QNe4I.en.vtt
[download] Destination: Primitive Technology - Polynesian Arrowroot Flour-lMZY_9QNe4I.mp4
[download] 100% of 132.59MiB in 01:09
[ffmpeg] Converting subtitles
Deleting original file Primitive Technology - Polynesian Arrowroot Flour-lMZY_9QNe4I.zh-Hans.en(pass -k to keep)

**Comment by maaiika** [comment]
'postprocessors':[{'key': 'FFmpegSubtitlesConvertor','format': 'ass',}]

**Comment by luizcieslak** [comment]
hey @maaiika did you find a solution to convert the subtitle to the ASS format?
