### ISSUE TITLE
Can not download full video from safaribooks

### ISSUE THREAD

**Issue by hoangphuc2019** [ytdl-org/youtube-dl#21355]
## Checklist

- [X ] I'm reporting a broken site support
- [X ] I've verified that I'm running youtube-dl version **2019.06.08**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
Only part of the video is downloaded. Not full video.

youtube-dl -v  --cookies ../cookies.txt https://learning.oreilly.com/videos/learning-apache-cassandra/9781771372947/9781771372947-video191654
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', '../cookies.txt', 'https://learning.oreilly.com/videos/learning-apache-cassandra/9781771372947/9781771372947-video191654']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.7.3 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.2, ffprobe 4.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[Kaltura] 9781771372947-video191654: Downloading webpage
[Kaltura] 0_91hh26su: Downloading video info JSON
[Kaltura] 0_91hh26su: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://cfvod.kaltura.com/scf/hls/p/1926081/sp/192608100/serveFlavor/entryId/0_91hh26su/v/2/flavorId/0_bmi86itb/name/a.mp4/clipTo/60000/index.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cDovL2Nmdm9kLmthbHR1cmEuY29tL3NjZi9obHMvcC8xOTI2MDgxL3NwLzE5MjYwODEwMC9zZXJ2ZUZsYXZvci9lbnRyeUlkLzBfOTFoaDI2c3Uvdi8yKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU2MDI0OTc2OH19fV19&Signature=a7SIolfPWi9QeaSuiZfk9fpL0LnCJ5Jecbp6kgEy5FYCPbGHjFVBUp6qjddMFPH8kiyP4oUuhfFV50y3CizhoMdShPLHr7JT8395IY~6cI7NOqGEat6To9kdbT0nrBJ2dTdFDzbZtYzgrNo~ll8rTtTzOE0NOEzyBdyge2LnlPTf3P8Tas-ewOaush8WDznH8YmEN97Hr421neG-nPvzADAtQRHNlhHtIKIGHcnhTVLrV6IimdPJTnPLvw03SZEjDYzoMHuerrpQmF9exeplEYdzgwqYrfM723I3clvmPLYtGYWUUIoqTzItInllGtIE8sSKpoTAPHu62LSRBAOnFg__&Key-Pair-Id=APKAJT6QIWSKVYK3V34A'
[download] Introducing The Course-0_91hh26su.mp4 has already been downloaded
[download] 100% of 1.94MiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:Introducing The Course-0_91hh26su.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Introducing The Course-0_91hh26su.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Introducing The Course-0_91hh26su.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:Introducing The Course-0_91hh26su.temp.mp4'

**Comment by dstftw** [comment]
You must use account credentials.

**Comment by rrjanbiah** [comment]
Isn't it redundant to pass credentials when setting cookie file?
