### ISSUE TITLE
How does youtube-dl detect advertisements?

### ISSUE THREAD

**Issue by ischmidt20** [ytdl-org/youtube-dl#21363]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Fox Sports Go recently changed their streaming service. Previously, I used to be able to record live streams and download event replays by passing headers into streamlink. However, recording live with streamlink "works" just fine, but because commercials have some kind of different codec than the actual content, I can't do anything with the resulting .ts file.

However, I can download replays from FOX.com just fine, using a youtube-dl command like this: `youtube-dl --hls-prefer-native -f 3750 https://content-auso1.uplynk.com/preplay2/6f324d0648b34576b36ce49160add428/391dec8c1a9a07b70d3062e4bf1a6e3c/4sQNPrWNbJWMzPMP2RXiNy2SFAhlIDUYbUwS2TJwN94h.m3u8?pbs=38dc148aad7c4a7f981a8dd57493a625`

The big problems with this are that a) I have to wait until a replay is posted; and b) FOX is very inconsistent as to which events get replays posted and which do not, meaning I'm SOL if I'm trying to save an event that just doesn't have a replay for some reason. If I could record live, this wouldn't be an issue, but again, the commercials are throwing things off.

One of the output lines from youtube-dl is `[hlsnative] Total fragments: 1815 (not including 504 ad)`.

So my question is: how does youtube-dl detect which segments are ads in the .m3u8 file? If I can figure that out, perhaps I can rig streamlink to ignore those segments when recording, saving me a lot of trouble.

Thanks!

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl/blob/427cc215310804127b55744fcc3664ede38a4a0d/youtube_dl/downloader/hls.py#L78-L80
