### ISSUE TITLE
[VRTnu] Unsupported Media Type

### ISSUE THREAD

**Issue by laurensscheers** [ytdl-org/youtube-dl#21371]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.vrt.be/vrtnu/a-z/appel-d-urgence/2/appel-d-urgence-s2a1/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-93539-g8607e29fa3, ffprobe N-93539-g8607e29fa3
[debug] Proxy map: {}
[VrtNU] appel-d-urgence-s2a1: Downloading webpage
WARNING: [VrtNU] appel-d-urgence-s2a1: Failed to parse JSON Invalid \escape: line 31 column 21 (char 649)
[VrtNU] appel-d-urgence-s2a1: Downloading JSON metadata
[Canvas] pbs-pub-cd09cc3c-5178-49c1-9387-715cb9ad98ff$vid-d0b7cfaa-fd96-448e-9923-281b10261bfa: Downloading JSON metadata
[Canvas] pbs-pub-cd09cc3c-5178-49c1-9387-715cb9ad98ff$vid-d0b7cfaa-fd96-448e-9923-281b10261bfa: Downloading m3u8 information
[Canvas] pbs-pub-cd09cc3c-5178-49c1-9387-715cb9ad98ff$vid-d0b7cfaa-fd96-448e-9923-281b10261bfa: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 415: Unsupported Media Type
[Canvas] pbs-pub-cd09cc3c-5178-49c1-9387-715cb9ad98ff$vid-d0b7cfaa-fd96-448e-9923-281b10261bfa: Downloading MPD manifest
[Canvas] pbs-pub-cd09cc3c-5178-49c1-9387-715cb9ad98ff$vid-d0b7cfaa-fd96-448e-9923-281b10261bfa: Downloading ISM manifest
[Canvas] pbs-pub-cd09cc3c-5178-49c1-9387-715cb9ad98ff$vid-d0b7cfaa-fd96-448e-9923-281b10261bfa: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\extractor\canvas.py", line 77, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found
```

## Description

At first glance, https://www.vrt.be/vrtnu/a-z/appel-d-urgence/2/appel-d-urgence-s2a1/ is the only video on VRTnu that returns this kind of error, so the priority is not that high at the moment 😉. But of course you never know if this will happen with multiple videos in the future.

When I open the URL in my browser, first an advertisement is played as a separate video before the main video starts. With all the other videos on VRTnu, the main video starts immediately and any advertising is incorporated in it.

**Comment by dstftw** [comment]
![image](https://user-images.githubusercontent.com/1908898/59361351-eda40300-8d5b-11e9-830f-7fe26d32419c.png)

For any work on this you must provide reproducible environment.

**Comment by laurensscheers** [comment]
Indeed, this program can only be viewed within the EU with a Belgian account.
Now I have tested some things:
- When I use a VPN connection from Belgium to a non-EU country, I get the same black screen as in the comment above.
- With a VPN connection from Belgium to another EU country, I have to enter a Belgian mobile phone number.
![VRTnu need for phone number (small)](https://user-images.githubusercontent.com/11779158/59368900-7e201a80-8d3f-11e9-9996-95feefae331c.png)
- When I watch the video in Belgium without the usage of a VPN, I don't have to enter a mobile phone number and I have never linked one to my account.

I therefore assume that a VPN to Belgium should suffice to reproduce the environment. Can someone please confirm this?

**Comment by laurensscheers** [comment]
Of which issue is this a duplicate? 
Because I have searched through some other reported issues with VRTnu and for all those I have tried I can confirm that, if the url is still alive (#20384 for example), it can still be downloaded without any problem.
So this issue seems a new one to me.

**Comment by remitamine** [comment]
it's the same error but caused by a different problem, so it's not actually a duplicate, but all the formats served for this video are DRM protected, which youtube-dl does not support.

**Comment by laurensscheers** [comment]
I already feared that it was DRM-protected 😒. Is there a way I can get an overview of all the present streams, including the drm-protected ones? I thought this could be found in the manifest file, but unfortunately this is not the case.

For example: https://www.vrt.be/vrtnu/a-z/we-were-three/2017/we-were-three/

a part of the manifest file:
```
# variants
#EXT-X-STREAM-INF:BANDWIDTH=216000,CODECS="mp4a.40.2,avc1.42C01E",RESOLUTION=416x234,FRAME-RATE=25,AUDIO="audio-aacl-62",CLOSED-CAPTIONS=NONE
vid-cb480ef9-5a2f-4352-a6ff-94caabadbfbc-CDN_1_drm_e6569f32-8cad-4607-833c-59278b9824ea-video=143960.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=480000,CODECS="mp4a.40.2,avc1.42C01E",RESOLUTION=480x270,FRAME-RATE=25,AUDIO="audio-aacl-93",CLOSED-CAPTIONS=NONE
vid-cb480ef9-5a2f-4352-a6ff-94caabadbfbc-CDN_1_drm_e6569f32-8cad-4607-833c-59278b9824ea-video=363709.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=868000,CODECS="mp4a.40.2,avc1.42C01E",RESOLUTION=640x360,FRAME-RATE=25,AUDIO="audio-aacl-93",CLOSED-CAPTIONS=NONE
vid-cb480ef9-5a2f-4352-a6ff-94caabadbfbc-CDN_1_drm_e6569f32-8cad-4607-833c-59278b9824ea-video=728977.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1179000,CODECS="mp4a.40.2,avc1.42C01F",RESOLUTION=768x432,FRAME-RATE=25,AUDIO="audio-aacl-93",CLOSED-CAPTIONS=NONE
vid-cb480ef9-5a2f-4352-a6ff-94caabadbfbc-CDN_1_drm_e6569f32-8cad-4607-833c-59278b9824ea-video=1023133.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2080000,CODECS="mp4a.40.2,avc1.4D401F",RESOLUTION=960x540,FRAME-RATE=25,AUDIO="audio-aacl-93",CLOSED-CAPTIONS=NONE
vid-cb480ef9-5a2f-4352-a6ff-94caabadbfbc-CDN_1_drm_e6569f32-8cad-4607-833c-59278b9824ea-video=1873240.m3u8
```
The available formats:

```
format code   extension  resolution note
HLS_AES-220   mp4        416x234     220k , avc1.42C01E@ 143k, 25.0fps, mp4a.40.2@ 62k
HLS_AES-485   mp4        480x270     485k , avc1.42C01E@ 363k, 25.0fps, mp4a.40.2@ 93k
HLS_AES-872   mp4        640x360     872k , avc1.42C01E@ 728k, 25.0fps, mp4a.40.2@ 93k
HLS_AES-1184  mp4        768x432    1184k , avc1.42C01F@1023k, 25.0fps, mp4a.40.2@ 93k
HLS_AES-2085  mp4        960x540    2085k , avc1.4D401F@1873k, 25.0fps, mp4a.40.2@ 93k (best)
```

So even though the URLs in the manifest file show that only DRM streams are available, downloadable AES encrypted streams are available too. Where could I find these?

**Comment by remitamine** [comment]
it looks like a server issue on `remix-cf-vrt.akamaized.net` domain, the URL(https://remix-cf-vrt.akamaized.net/remix/18f7b87b-2715-490c-9ac6-8f05fbf5c7e4/remix_aes.ism/.m3u8) for AES formats return `HTTP Error 415: Unsupported Media Type`, while on the second(working) URL, the formats are served from `ondemand-cf-vrt.akamaized.net`.
