### ISSUE TITLE
Add new method of installation in Readme to

### ISSUE THREAD

**Issue by alexandreramosdev** [ytdl-org/youtube-dl#21387]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

This package is in Community repository of Archlinux. I can add in readme new method of installation sudo pacman -S youtube-dl to improve this documetion.

**Comment by dstftw** [comment]
This will not be added. We do not control Community repository of Archlinux.

**Comment by alexandreramosdev** [comment]
I'm understand
