### ISSUE TITLE
Camtube.co site support is not working now

### ISSUE THREAD

**Issue by prodigy007** [ytdl-org/youtube-dl#21398]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\WINDOWS\system32>youtube-dl https://camtube.co/recording/w0wgirls-130619-1737-chaturbate-couple -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://camtube.co/recording/w0wgirls-130619-1737-chaturbate-couple', '-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[CamTube] w0wgirls-130619-1737-chaturbate-couple: Downloading session token
[CamTube] w0wgirls-130619-1737-chaturbate-couple: Downloading JSON metadata
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://api.camtube.co/recordings/37a3b57d-6971-4763-b4c9-8f5f455bc616/manifest.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 156
[download] Destination: w0wgirls-130619-1737-chaturbate-couple-37a3b57d-6971-4763-b4c9-8f5f455bc616.mp4
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 5 of 10)...

ERROR: Interrupted by user
```

## Description

WRITE DESCRIPTION HERE
I think it does not work now Camtube.co site support.

**Comment by dstftw** [comment]
You must have paid account.

**Comment by prodigy007** [comment]
> You must have paid account.

I bought a paid access and tried it with cookies, but it doesn't work at all. I will not remove any program to capture video: Internet Download Manager, TubeDigger, StreamTransport as well. I can give access login / password at the time of repair. In any case, even for free access (5 MB of video) youtube-dl does not work already.

youtube-dl https://camtube.co/recording/w0wgirls-130619-1737-chaturbate-couple --cookies "cookies.txt" -o "C:/Programs/%(title)s-%(id)s.%(ext)s"

**Comment by prodigy007** [comment]
![1111](https://user-images.githubusercontent.com/13364186/59567821-7cc25b00-907b-11e9-9b62-af2b9d662b5f.JPG)
@dstftw  I don't understand python. But it seems to me that there is no work at all in extractor ?

**Comment by dstftw** [comment]
Wrong.

**Comment by prodigy007** [comment]
@dstftw  I don't mean working with the --cookies parameter, you can show the extractor where implemented, how to get cookies from the file

**Comment by dstftw** [comment]
Implemented what? You don't need to get cookies from the file in extractor code in the first place.

**Comment by prodigy007** [comment]
@dstftw Where, then, is in the Kamtuba extractor, the 'if' condition, where you will either take the file from the --cookiesparameter or they will be obtained upon request, as now, there is a strict request for receiving NEW cookies, instead of taking everything from the file, it seems like this straightforward code:: token = self._download_json (
              '% s / rpc / session / new'% self._API_BASE, display_id,
              'Downloading session token') ['token']

Вообще можно писать на русском ? вы вроде бы русскоговорящий
