### ISSUE TITLE
How to set credentials in testing new extractor

### ISSUE THREAD

**Issue by fauresystems** [ytdl-org/youtube-dl#21394]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

I create a branch and added YourExtractor, it works.
I want to add a test URL which requires user/passsword: https://fr.pornhubpremium.com/view_video.php?viewkey=ph5cd051fa7a6fc

How do I add the credentials to run :
test/test_download.py TestDownload.test_YourExtractor

**Comment by dstftw** [comment]
Add to params
https://github.com/ytdl-org/youtube-dl/blob/b85eae0f057a0afdf1da9d6034c19327c8de33cf/youtube_dl/YoutubeDL.py#L142-L143
