### ISSUE TITLE
--xattrs option should write metadata even with --download-archive

### ISSUE THREAD

**Issue by rieje** [ytdl-org/youtube-dl#21393]
## Checklist
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Potentially a bug, but `-xattrs` in conjunction with `--download-archive` option currently results in xattr not being written to file's xattrs if the video has already been written to archive and thus not downloaded. However, without the `--download-archive` option and with the video already downloaded, xattr will be written. 

`--xattrs` should always result in metadata being written to the files.

**Comment by dstftw** [comment]
This is expected behavior.
