### ISSUE TITLE
Cannot find aria2 conf path in windows 7

### ISSUE THREAD

**Issue by sunnyday2006** [ytdl-org/youtube-dl#21403]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

D:\Files\Mediadown>youtube-dl.exe -v --proxy http://127.0.0.1:5080/ -o "D:\Library\Videos\%%(title)s.%%(ext)s" https://www.youtube.com/watch?v=5lKeAT1Gy7I --external-downloader aria2c --external-downloader-args "--conf-path=aria2.conf"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--proxy', 'http://127.0.0.1:5080/', '-o', 'D:\\Library\\Videos\\%
%(title)s.%%(ext)s', 'https://www.youtube.com/watch?v=5lKeAT1Gy7I', '--external-downloader', 'aria2c', '--external-downloader-args', '--conf-path=aria2.conf']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1
[debug] Proxy map: {'http': 'http://127.0.0.1:5080/', 'https': 'http://127.0.0.1:5080/'}
[youtube] 5lKeAT1Gy7I: Downloading webpage
[youtube] 5lKeAT1Gy7I: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r4---sn-n4v7snee.googlevideo.com/videoplayback?expire=1560642488&ei=Vy8FXbyRNcbwkgb6lp7ACg&ip=170.130.15.214&id=o-ACOZfEgamPZVVoScBQ8zuhw4uAOITCnQ97ZXy26qm5Qn&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-n4v7snee%2Csn-n4v7knll&ms=au%2Crdu&mv=u&pl=22&mime=video%2Fmp4&gir=yes&clen=186974829&dur=641.733&lmt=1557365458751521&mt=1560620610&fvip=4&keepalive=yes&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRgIhALNbsAG2piZgft6mNTg7sHp83cPzStdodS4UqyHxwoSsAiEAvnBJxFmMzR7N7Vdd8HEAfmKYGPtRA2TbOxhTYrqw0FA%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl&lsig=AHylml4wRQIgV_CH3b6HE6h5Mlz7KzfCKS5TzxGEfVCMA8o6QiY1LyECIQDNhLGBEhjGdv_Jr9uD_BR3KkvRpN26iucjUBxK5LWvWg%3D%3D&ratebypass=yes'
[download] Destination: D:\Library\Videos\%(title)s.%(ext)s.f137
[debug] aria2c command line: aria2c -c "--conf-path=aria2.conf" --dir "D:\Library\Videos" --out "%(title)s.%(ext)s.f137.part" --header "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0)Gecko/20100101 Firefox/59.0" --header "Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7" --header "Accept-Encoding: gzip, deflate" --header "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
--header "Accept-Language: en-us,en;q=0.5" --all-proxy "http://127.0.0.1:5080/" "--check-certificate=true" -- "https://r4---sn-n4v7snee.googlevideo.com/videoplayback?expire=1560642488&ei=Vy8FXbyRNcbwkgb6lp7ACg&ip=170.130.15.214&id=o-ACOZfEgamPZVVoScBQ8zuhw4uAOITCnQ97ZXy26qm5Qn&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-n4v7snee%2Csn-n4v7knll&ms=au%2Crdu&mv=u&pl=22&mime=video%2Fmp4&gir=yes&clen=186974829&dur=641.733&lmt=1557365458751521&mt=1560620610&fvip=4&keepalive=yes&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRgIhALNbsAG2piZgft6mNTg7sHp83cPzStdodS4UqyHxwoSsAiEAvnBJxFmMzR7N7Vdd8HEAfmKYGPtRA2TbOxhTYrqw0FA%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl&lsig=AHylml4wRQIgV_CH3b6HE6h5Mlz7KzfCKS5TzxGEfVCMA8o6QiY1LyECIQDNhLGBEhjGdv_Jr9uD_BR3KkvRpN26iucjUBxK5LWvWg%3D%3D&ratebypass=yes"
**Configuration file aria2.conf is not found.**
Usage: aria2c [OPTIONS] [URI | MAGNET | TORRENT_FILE | METALINK_FILE]...
Printing options tagged with '#help'.
See 'aria2c -h#help' to know all available tags.
Options:
 -h, --help[=TAG|KEYWORD]     Print usage and exit.
                              The help messages are classified with tags. A tag
                              starts with "#". For example, type "--help=#http"
                              to get the usage for the options tagged with
                              "#http". If non-tag word is given, print the usage
                              for the options whose name includes that word.

                              Possible Values: #basic, #advanced, #http, #https, #ftp, #metalink, #b
ittorrent, #cookie, #hook, #file, #rpc, #checksum, #experimental, #deprecated, #help, #all
                              Default: #basic
                              Tags: #basic, #help

Refer to man page for more information.

ERROR: aria2c exited with code 1
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\
__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\
__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\
YoutubeDL.py", line 2008, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\
YoutubeDL.py", line 807, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\
YoutubeDL.py", line 861, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\
YoutubeDL.py", line 1642, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\
YoutubeDL.py", line 1909, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\
YoutubeDL.py", line 1854, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\
downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\
downloader\external.py", line 64, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\
downloader\common.py", line 165, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\
YoutubeDL.py", line 624, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp3esl0iyj\build\youtube_dl\
YoutubeDL.py", line 586, in trouble

## Description

WRITE DESCRIPTION HERE

I have trouble on adding aria2 download in conf path. My system is windows 7, and it is no problem when i use aria2 without youtube-dl, in the form like that "aria2c.exe --conf-path=D:/aria2/aria2.conf".

While i try to use aria2 as the external-download for youtube-dl, it is unsuccessful whether in the form '--external-downloader-args "--conf-path=D:/aria2/aria2.conf"' OR '--external-downloader-args "--conf-path=aria2.conf"' (i put the configuration in the C:\Users\Administrator\\.aria2\aria2.conf). When i just use aria2 in youtube-dl without "external-downloader-args" command, it works in spite of no configuration.

Is it sth wrong?
I think it is related to this https://github.com/ytdl-org/youtube-dl/issues/16957.
aria2 documentation on --conf-path=<PATH>
$HOME/.aria2/aria2.conf, otherwise $XDG_CONFIG_HOME/aria2/aria2.conf

**Comment by dstftw** [comment]
Most likely invalid path.

**Comment by sunnyday2006** [comment]
So what is the correct path writing in this situation?
