### ISSUE TITLE
Support for RTL Most (HU)

### ISSUE THREAD

**Issue by RevSnowfox** [ytdl-org/youtube-dl#21405]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.rtlmost.hu/fokusz-p_7718/fokusz-2019-06-07-c_12405389
- Single video: https://www.rtlmost.hu/fokusz-p_7718/fokusz-2019-06-13-c_12410409
- Single video: https://www.rtlmost.hu/fokusz-plusz-p_7722/fokusz-plusz-2019-02-16-c_12285521
- Single video: https://www.rtlmost.hu/fokusz-plusz-p_7722/fokusz-plusz-2019-05-11-c_12372155
- Single video: https://www.rtlmost.hu/xxi-szazad-p_7730/xxi-szazad-2019-03-05-c_12297657
- Single video: https://www.rtlmost.hu/xxi-szazad-p_7730/xxi-szazad-a-vasfuggony-is-eltunt-a-hatarrol-2019-04-23-c_12347399
- Show page URL linking to all videos of a show: https://www.rtlmost.hu/xxi-szazad-p_7730

## Description

RTL Most is the free VOD and replay portal of RTL Klub, the most viewed television station in Hungary. The site used Silverlight (ISM) in the past, now they use a technology that makes downloading nontrivial. I tried snooping with WireShark, but failed.

Every show on the site has an integer ID that is at least 4 digits long as well as an 8 digit integer video ID,

If the website requires login credentials to play back videos:
Click on "Bejelentkezés" (Login).
- Email address ("Email cím"): [rtlmosttest @ bullbeer.org]
- Password ("Jelszó"): [YTDLtest01]

Account email address is confirmed and birthday is set. The site was georestricted to Hungarian IP addresses in the past, not sure if they still do it.

**Comment by kovacsattila-hun** [comment]
It seems downloading RTLMost videos are broken. I get error message with 404 code. Please fix.
Example videolink: `https://www.rtlmost.hu/video/clip_12592087`

**Comment by ddsdas4** [comment]
Nekem nem müködik a youtube-dl-lel az rtlmost.hu  adások letöltése. Tudna valaki segíteni?

**Comment by wbadam** [comment]
It seems like the issue is that RTL Most only serves DRM protected stream which cannot be downloaded. A better error message would be useful.

**Comment by antivirtel** [comment]
Same error here, would be useful to have an extract message. I'm using a ~/.netrc file, but it doesn't seem to help:
```python
$ youtube-dl -n https://www.rtlmost.hu/mit-nezel-p_18995/bucsuzik-az-orszag-tanara-mit-nezel-13-resz-interju-nagy-ervinnel-c_12913691 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-n', 'https://www.rtlmost.hu/mit-nezel-p_18995/bucsuzik-az-orszag-tanara-mit-nezel-13-resz-interju-nagy-ervinnel-c_12913691', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.5 (CPython) - Linux-5.4.0-91-generic-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[6play] 12913691: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/path-to/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/path-to/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/path-to/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/path-to/lib/python3.9/site-packages/youtube_dl/extractor/sixplay.py", line 113, in _real_extract
    self._sort_formats(formats)
  File "/path-to/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
rtlmost.hu is recognised by the 6Play.fr (M6) extractor, but see #24967.
