### ISSUE TITLE
How can i get audio,like mp3,thanks

### ISSUE THREAD

**Issue by wangbohao123** [ytdl-org/youtube-dl#21402]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by dstftw** [comment]
`-x --audio-format mp3`.

**Comment by wangbohao123** [comment]
yes,it is work,but i still download webm format.
and thank you for your reply -v-

**Comment by beantowel** [comment]
@wangbohao123 i got the same result, the audio file was webm format and can't be opened by most of the audio player/processor
