### ISSUE TITLE
Is it possible to download metadata, descriptions, thumbnails or titles of deleted or blocked videos?

### ISSUE THREAD

**Issue by AnnanFay** [ytdl-org/youtube-dl#21406]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

In my old watch later playlist there are several deleted videos, but also some which have titles and thumbnails but which are unwatchable because they have been blocked. Here is an example:

![image](https://user-images.githubusercontent.com/766048/59557506-3a454380-8fd3-11e9-9fc2-92f149308ff5.png)

When downloading with youtube-dl can the metadata associated with blocked videos be saved? Can the IDs of deleted videos be saved?

I want to clean out my watch later playlist, but would like to store the details of removed videos in case it it useful later.

**Comment by dstftw** [comment]
Write a script the will consume JSON playlist data and do whatever you need.

**Comment by AnnanFay** [comment]
For anyone else trying to do this, it's the `-i --dump-single-json` option.

**Comment by AnnanFay** [comment]
@dstftw Actually, I don't think that works.

Did you mean some other way by your comment?

Using `--dump-single-json` gives `null` entries and doesn't give any more data.
