### ISSUE TITLE
New extractor ready for pull request, 2 questions

### ISSUE THREAD

**Issue by fauresystems** [ytdl-org/youtube-dl#21412]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
New extractor from pornhubpremium is ready:
1) shall I rename yourextractor.py to pornhubpremium.py ?
2) test require username/password, I'd prefer not to let them in the file, or I can for a small period so you can run the test, whot sould I do ?

**Comment by dstftw** [comment]
1. You must place it in `pornhub.py`.
2. You must provide account credentials to core developer.
