### ISSUE TITLE
Cannot download metadata json for YouTube countdown ("Premier") videos

### ISSUE THREAD

**Issue by mariomadproductions** [ytdl-org/youtube-dl#21414]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=q5n6_Elz0GI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 2.7.13 (CPython) - Linux-4.19.42-v7+-armv7l-with-debian-9.9
[debug] exe versions: avconv 3.2.14-1, avprobe 3.2.14-1, ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[youtube] q5n6_Elz0GI: Downloading webpage
[youtube] q5n6_Elz0GI: Downloading video info webpage
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2077, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.
```

## Description

Cannot download metadata json (using --write-info-json) for YouTube countdown ("Premier") videos. Using --write-pages I could manually extract the info I wanted (the publication date).

**Comment by dstftw** [comment]
This is expected behavior.

**Comment by mariomadproductions** [comment]
Is there no way to force youtube-dl to ignore this error and create the metadata file?

**Comment by mariomadproductions** [comment]
> This is expected behavior.

Is there no way to force youtube-dl to ignore this error and create the metadata file?

**Comment by dstftw** [comment]
No.

**Comment by mariomadproductions** [comment]
Could you explain why?

**Comment by dstftw** [comment]
Explain what? This is how it's implemented. Extraction does not make sense without valid media available.
