### ISSUE TITLE
Playlist numbering control?

### ISSUE THREAD

**Issue by mihalski** [ytdl-org/youtube-dl#21422]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is it possible to set the number of digits for playlist downloads?
For example a 112 video playlist on Udemy. You start the download and the videos are named 001, 002 and so on because youtube-dl detects that 112 is 3 digits. Resume after you've downloaded the first 12 videos and now the remained will be (for example) 13 to 112 which is 99 videos (2 digits) and they will now be numbered without the leading 0's.

Example of original download:
`072. Powers of negative bases`

Example of resumed download:
`72. Powers of negative bases`

Hopefully I've just overlooked some option.

Thank you for this wonderful program!

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#output-template

**Comment by mihalski** [comment]
Sorry, I totally forgot to mention that I was using an output template.

```
youtube-dl -o '%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s' https://www.udemy.com/course_name/
```

`
playlist_index (numeric): Index of the video in the playlist padded with leading zeros according to the total length of the playlist
`

This does not appear to function as described. ie "padded with leading zeros according to the TOTAL length of the playlist". Instead it is padded with leading zeros according to the REMAINING length of the playlist when --playlist-start is used.

**Comment by dstftw** [comment]
Again: read the documentation on output template.
>The special sequences may be formatted according to [python string formatting operations](https://docs.python.org/2/library/stdtypes.html#string-formatting).
