### ISSUE TITLE
No video formats found for Pluralsight

### ISSUE THREAD

**Issue by gnanam336** [ytdl-org/youtube-dl#21437]
## Checklist

- [ ] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
youtube-dl --version
2019.06.08
youtube-dl https://app.pluralsight.com/library/courses/reactive-programming-java-8-rxjava/table-of-contents
[pluralsight:course] reactive-programming-java-8-rxjava: Downloading JSON metadata
[download] Downloading playlist: Reactive Programming in Java 8 With RxJava
[pluralsight:course] playlist Reactive Programming in Java 8 With RxJava: Collected 39 video ids (downloading 39 of them)
[download] Downloading video 1 of 39
[pluralsight] reactive-programming-java-8-rxjava-m1-concepts-0: Downloading JSON metadata
[pluralsight] reactive-programming-java-8-rxjava-m1-concepts-0: Downloading mp4-high viewclip graphql
[pluralsight] reactive-programming-java-8-rxjava-m1-concepts-0: Waiting for 2 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You must authenticate for this course.
