### ISSUE TITLE
Transcoding WebM (Opus) to Vorbis (Ogg)

### ISSUE THREAD

**Issue by ChrisKolan** [ytdl-org/youtube-dl#21433]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

On Windows machine, I am using youtube-dl to download audio in the best quality which is WebM (Opus). I am transcoding that file to Vorbis (ogg) with the following command:

`youtube-dl.exe -f bestaudio[ext=webm] --no-mtime --add-metadata  --restrict-filenames -o "-%(title)s-%(id)s.%(ext)s" https://www.youtube.com/watch?v=4KcQ90UbRsg --postprocessor-args "-c:a libvorbis -q:a 5 output.ogg"`

This gives me output.ogg file
Is it possible that the file name is the same as the WebM file only with a different extension?

"-%(title)s-%(id)s.%(ext)s" gives -Royalty_Free_Music_Dance_LiQWYD-4KcQ90UbRsg.webm
Desired filename: -Royalty_Free_Music_Dance_LiQWYD-4KcQ90UbRsg.ogg

Is it possible to achieve this in a one-liner?

**Comment by dstftw** [comment]
1. Best quality audio is not necessarily webm.
2. `-x --audio-format`.

**Comment by ChrisKolan** [comment]
So let's assume that the best quality is not WebM. My question remains: how to convert that format to Vorbis (Ogg)?

**Comment by dstftw** [comment]
Did you read my post at all?

**Comment by BUAWF** [comment]
> 1. Best quality audio is not necessarily webm.
> 2. `-x --audio-format vorbis`.

God Bless You Dear.
Only one thing, how to strip or remove all or (how much ever is possible) the metadata ?
Whats the command for it ?

Please help, Would be Heartily appreciated.
Thanks.
