### ISSUE TITLE
progress_hook and already downloaded videos?

### ISSUE THREAD

**Issue by Elite** [ytdl-org/youtube-dl#2144]
While using  the below code and listening to `progress_updates`, no information is pushed either to `Logger` object neither anything gets updated in `progress_hook(pr)` telling that video is already downloaded. How to get that information? 

Wouldn't it be good to emit an finished status to `progress_hook` in such a condition?

```
directory = os.path.join(os.path.expanduser('~'), 'Desktop')
        ydl_options = {
            'outtmpl': os.path.join(directory, '%(title)s-%(id)s.%(ext)s'),
            'logger': Logger(),
            'nooverwrites': True,
            'continuedl': True,
        }

        with YoutubeDL(ydl_options) as ydl:
            ydl.add_default_info_extractors()
            ydl.add_progress_hook(progress_hook)
            ydl.download([self.url])
```

**Comment by dirkf** [comment]
If it's not been changed yet, it probably won't be.
