### ISSUE TITLE
404 on acast

### ISSUE THREAD

**Issue by benoliver999** [ytdl-org/youtube-dl#21444]
This is the command I tried:

`youtube-dl https://play.acast.com/s/theintelligencepodcast/a7a69868-ebe9-4950-8d13-8bac9642d622 --verbose`

The output is:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://play.acast.com/s/theintelligencepodcast/a7a69868-ebe9-4950-8d13-8bac9642d622', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.7.3 (CPython) - Linux-5.1.9-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[acast] a7a69868-ebe9-4950-8d13-8bac9642d622: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

```

**Comment by kebabkalle** [comment]
You can use this instead, https://rss.acast.com/theintelligencepodcast

**Comment by ssixty** [comment]
Thanks for the rss tip, there are downsides sadly:

 - can't use  --download-archive file as everything is detected as 'generic media'
 - other metadata like episode numbers, upload date etc. is not picked up

**Comment by benoliver999** [comment]
This is true.

The other reason I haven't closed the issue is that you lose the ability 
to just paste a URL straight into YTDL.

**Comment by biwubo** [comment]
@ssixty Sorry for not being able to respond earlier, I looked into this briefly the day the issue was opened and was not able to find an elegant solution in a short time.

I see that @remitamine has merged a change closing this issue however for me one of the URLs in the test cases throws a 404 error even though it's playable in the browser. It's this one: `https://play.acast.com/s/rattegangspodden/s04e09-styckmordet-i-helenelund-del-22` and it works without the change.

Just a heads up for now, I can take a look when I find the time.
