### ISSUE TITLE
Archive logfile not created when using --skip-download when getting subtitles.

### ISSUE THREAD

**Issue by altimumdelta** [ytdl-org/youtube-dl#21454]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
N/A
```

## Description

When --skip-download is used apparently --download-archive has no effect. 

It has to initialize each youtube video download and only then figures out there's a subtitle file already present, the process is very slow, almost the same as if when it's downloading them.

**Comment by dstftw** [comment]
This is expected behavior.
