### ISSUE TITLE
Uploader metadata for xvideos-pornhub

### ISSUE THREAD

**Issue by wankio** [ytdl-org/youtube-dl#21458]
xvideos and pornhub have uploader/channel/model-name

It would be great if youtube-dl can support it, so filename will be (uploader/channel/model-name) - (title)

thank

**Comment by dstftw** [comment]
This is already supported.

**Comment by wankio** [comment]
@dstftw  but uploader - uploader_id is not working

**Comment by jingofett** [comment]
It works for pornhub but not xvideos, it gives me NA when I use uploader, creator, uploader_id, channel. Using `--write-info-json` shows that it's not being pulled at all for xvideos.
