### ISSUE TITLE
Bug - RegexNotFoundError: Unable to extract user

### ISSUE THREAD

**Issue by jesusgt** [ytdl-org/youtube-dl#21462]
This has started happening 7 days ago when downloading from DailyMotion

**Youtube_dl version** 
~/bin/youtube-dl --version
2019.06.08

**Command used**: 
./youtube_dl https://www.dailymotion.com/haa-2-2/videos --verbose -i --match-title 'home|away' --reject-title 'preview|peek' --dateafter now-7days --download-archive download.log -o ~/dl/

**Error:**
`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.dailymotion.com/haa-2-2/videos', u'--verbose', u'-i', u'--match-title', u'home|away', u'--reject-title', u'preview|peek', u'--dateafter', u'now-10days', u'--download-archive', u'/home/xuxo/dl/videos/Home-Away/.downloaded', u'-o', u'Home&Away-%(upload_date)s-%(id)s.%(ext)s']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2019.06.08
[debug] Python version 2.7.14 (CPython) - Linux-4.4.0-109-generic-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 3.4.1-1, avprobe 3.4.1-1, ffmpeg 3.4.1-1, ffprobe 3.4.1-1, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion:user] haa-2-2: Downloading webpage
ERROR: Unable to extract user; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/xuxo/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/xuxo/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/xuxo/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 486, in _real_extract
    webpage, 'user'))
  File "/home/xuxo/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/xuxo/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract user; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

`

**Comment by Joelpls** [comment]
full_user isn't finding any matching regex in the webpage HTML. The regex might have to change. I assume it's trying to get the title of the webpage?
https://github.com/ytdl-org/youtube-dl/blob/695720ebe81166b3ee249eb3916e3c7819ef57a8/youtube_dl/extractor/dailymotion.py#L484-L486

The playlist HTML scraper doesn't seem to find any video URLs on the user's videos page. Maybe dailymotion's HTML has changed? 
https://github.com/ytdl-org/youtube-dl/blob/695720ebe81166b3ee249eb3916e3c7819ef57a8/youtube_dl/extractor/dailymotion.py#L469 
^This for loop isn't finding any videos.

**Comment by jesusgt** [comment]
Then the dailymotion plugin must be broken then.
As I said. The command above was working properly, and finding/downloading the videos matching the regex a month ago. Sadly it is no longer the case

**Comment by Timtam** [comment]
Even though thats rather obvious, but it still didn't change.
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ffmpeg-location', u'D:/ffmpeg/bin/', u'--verbose', u'https://www.dailymotion.com/GenialDaneben']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2019.08.02
[debug] Python version 2.7.14 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[dailymotion:user] GenialDaneben: Downloading webpage
ERROR: Unable to extract user; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\dailymotion.py", line 492, in _real_extract
    webpage, 'user'))
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract user; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
