### ISSUE TITLE
Proccess videos using ffmpeg and does not save the video to disk

### ISSUE THREAD

**Issue by Gaploid** [ytdl-org/youtube-dl#21472]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Hi,
I'm using youtube-dl to download videos with external ffmpeg downloader that produce images at the same time. Something like that 
`youtube-dl --hls-prefer-ffmpeg --fixup warn  --external-downloader ffmpeg --external-downloader-args "-filter_complex \"[0:v]fps=2,crop=in_w/3.84:in_h/21.6:in_w/2.74:in_h/1.43, scale=in_w*2:in_h*2,unsharp=luma_msize_x=7:luma_msize_y=7:luma_amount=2.5[out1];[0:v]fps=2,crop=in_w/2.96:in_h/21.62:in_w/1.58:in_h/5.68, scale=in_w*2:in_h*2,unsharp=luma_msize_x=7:luma_msize_y=7:luma_amount=2.5[out2]\" -map [out1] -map -c:a -q:v 1 C:\\temp\\images\\middle%d.tiff -map [out2] -map -c:a -q:v 1 C:\\temp\\images\\up%d.tiff" --restrict-filenames --skip-unavailable-fragments -o 439815364.mp4 "https://www.twitch.tv/videos/439815364"`

I really need only these images and I don't need the final .mp4 file. Is there any option not to save the final video file to disk? I've tried option "--skip-download" with no success it even did not start the downloading process.

**Comment by dstftw** [comment]
Remove it with `--exec`.

**Comment by Gaploid** [comment]
Thanks for the fast response!

I'm trying to avoid consuming a lot of space on a disk. I don't have space on the disk to download the whole video. That's why I'm trying to save only some part of the video in images and don't need the video itself. Your solution will not help the unfortunatly cause at the end I still need space for the whole video.

**Comment by Gaploid** [comment]
It seems I've figured out how to do that through pipes.  Here is the final command to do that:
`youtube-dl --hls-prefer-ffmpeg -o - "https://www.twitch.tv/videos/439815364" | ffmpeg -i pipe: -filter_complex "[0:v]fps=2,crop=in_w/3.84:in_h/21.6:in_w/2.74:in_h/1.43, scale=in_w*2:in_h*2,unsharp=luma_msize_x=7:luma_msize_y=7:luma_amount=2.5[out1];[0:v]fps=2,crop=in_w/2.96:in_h/21.62:in_w/1.58:in_h/5.68, scale=in_w*2:in_h*2,unsharp=luma_msize_x=7:luma_msize_y=7:luma_amount=2.5[out2]" -map [out1] -map -c:a -q:v 1 C:\temp\images\middle%d.tiff -map [out2] -map -c:a -q:v 1 C:\temp\images\up%d.tiff`
