### ISSUE TITLE
No video formats found

### ISSUE THREAD

**Issue by jd1008** [ytdl-org/youtube-dl#21480]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2019.06.21**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: [u'-ci', u'-f', u'best', u'-v', u'--sub-lang', u'en', u'--convert-subs', u'srt', u'--embed-subs', u'--fixup', u'warn', u'--audio-quality', u'320k']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-F', u'https://www.youtube.com/watch?v=nN0zA48bifc']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2019.06.21
[debug] Python version 2.7.5 (CPython) - Linux-3.19.8-100.fc20.x86_64-x86_64-with-fedora-20-Heisenbug
[debug] exe versions: avconv 11.7, avprobe 11.7, ffmpeg 3.1.3-static, ffprobe N-51556-ge278500
[debug] Proxy map: {}
[youtube] nN0zA48bifc: Downloading webpage
[youtube] nN0zA48bifc: Downloading embed webpage
[youtube] nN0zA48bifc: Refetching age-gated info webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2349, in _real_extract
    self._sort_formats(formats)
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Well, I wanted to download the video, and youtube-dl said no formats.
and yet, some other videos do download. Not sure what the difference is between 
videos that are downloadable vs videos that are not.

**Comment by grvldmr1** [comment]
Have the same problem. 
Someone says, that youtube API has changed, so some of the new videos cannot be downloaded using youtube-dl.

For instance, 
https://www.youtube.com/watch?v=VjXG2QcyvtA
https://www.youtube.com/watch?v=sMk9vs844HY
https://www.youtube.com/watch?v=VjXG2QcyvtA
https://youtu.be/zUDXj8REpAI
https://youtu.be/7MXXrbqRCiE
https://youtu.be/IhAAQ-WwLYc
