### ISSUE TITLE
Is there a way to get the urls of individual videos in a playlist?

### ISSUE THREAD

**Issue by WillPittenger** [ytdl-org/youtube-dl#21485]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

Suppose I have a playlist P with 3 videos. Because of the possibility of the 2nd video being marked private, market deleted,or not being available in the requested format; I'm thinking of separate calls to youtube-dl for each video. But first, I need the individual urls. This needs to be as though I visited the playlist page and manually copied the individual URLs from there. This needs to work even for videos that can't be downloaded. I can detect errors later.

I ask because I have a PowerShell function that simplifies downloading playlists. I want it to skip invalid videos. If a video isn't available in a given format, I want my function to try other formats and then call ffmpeg to convert.

**Comment by dstftw** [comment]
`--dump-json --flat-playlist`.

**Comment by WillPittenger** [comment]
Thanks.

**Comment by abhiank** [comment]
@dstftw How do I save this json output to a file? I tried - 
`youtube-dl --dump-json --flat-playlist -o /User/username/Desktop/list.json PLFftu4DSZBSwrGiOlZXKHRSoKArsKSuz9`

**Comment by abhiank** [comment]
Thanks, but I found a way to do that : 
`youtube-dl --dump-single-json --flat-playlist PLFftu4DSZBSwrGiOlZXKHRSoKArsKSuz9 > /Users/abhimanyu/Desktop/list.json
`
