### ISSUE TITLE
Unable to download complete videos form learning.oreilly.com - formally safaribooksone.com

### ISSUE THREAD

**Issue by BarDev** [ytdl-org/youtube-dl#21481]
I cannot download the complete video from learning.oreilly.com.

As an example, I'm trying to download the following complete video from learning.oreilly.com with the following command.  Only the first minute of the video is downloaded.

Note: it seems safaribooks.com is redirected to learning.oreilly.com

`youtube-dl https://learning.oreilly.com/videos/oreilly-software-architecture/9781492050506/9781492050506-video324051`

I've downloaded my cookies for learning.oreilly.com and used the --cookies parameter. I've also tried using the parameters username and password (-u, -p).  But none of these options allows me to download the complete video.

Am I doing something wrong? If so, what should I do to download the complete video?

Here the output when using the debug parameter (-v):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://learning.oreilly.com/videos/oreilly-software-architecture/9781492050506/9781492050506-video323962', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.7.2 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Kaltura] 9781492050506-video323962: Downloading webpage
[Kaltura] 0_zjiaubsp: Downloading video info JSON
[Kaltura] 0_zjiaubsp: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1926081/sp/192608100/playManifest/entryId/0_zjiaubsp/format/url/protocol/http/flavorId/0_jrxc57nz'
[download] Destination: Progressive delivery - The evolution of your software development lifecycle (sponsored by LaunchDarkly) - Adam Zimman (LaunchDarkly)-0_zjiaubsp.mp4
[download] 100% of 36.79MiB in 00:07
```

**Comment by dstftw** [comment]
You must pass credentials.

**Comment by BarDev** [comment]
It seems my issue was that I was using the incorrect credentials. Using username and password works and also using the --netrc parameter works.
