### ISSUE TITLE
What are the possible return values from youtube-dl?

### ISSUE THREAD

**Issue by WillPittenger** [ytdl-org/youtube-dl#21498]
## Checklist

- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

Is there a list of possible return codes from youtube-dl?  I'm working on my PowerShell script and can catch those.  Different return codes will trigger different processing.

**Comment by dstftw** [comment]
There are no specific return codes. You should not treat return code in any special way apart from standard meaning of 0 and non-0 values. There is actually one success non-0 code currently exist (that violates non-0 semantics) but it's likely to be removed in future.
