### ISSUE TITLE
Get decrypted signature from python script

### ISSUE THREAD

**Issue by Elite** [ytdl-org/youtube-dl#21499]
- [X ] I'm asking a question
- [X ] I've looked through the README and FAQ for similar questions
- [X ] I've searched the bugtracker for similar questions including closed ones

## Question

I am currently using `pytube` to get decipher signature from my project as below:

```
from pytube import cipher
html="base.js CONTENT HERE" 
unsig= 'ALgxI2wwRgIhAN3cG9UXPZSyZcwx2fTOFvbKT_5CAb475HUHuTjSjOw-AiEAjaY1JtcKuHMQkHyCt5cKGBqazj7mpR4EQ1nwGYvhkEc=' 
signature = cipher.get_signature(html, unsig)
print signature
```

But that project is not updated regularly and would like to use `youtube-dl` for same. Is this possible, if yes pls. provide pointers for same.

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl/blob/695720ebe81166b3ee249eb3916e3c7819ef57a8/youtube_dl/extractor/youtube.py#L2005-L2006

**Comment by Elite** [comment]
Sorry for the noob query but I tried a lot but was not able to figure out a way to import this function my script :(

**Comment by Elite** [comment]
Asked for help at stack and from the reply it seems it cant be done with current ytdl exposed methods !! Pls. check - https://stackoverflow.com/questions/56734345/correct-way-to-call-function-from-imported-python-package/56734930#56734930

**Comment by silverbacknet** [comment]
You were trying to call it static. Don't do that, it won't work. Initialize a new instance and then call _decrypt_signature(), it's not hard at all.

**Comment by Elite** [comment]
Isn't this the correct usage?

```
from youtube_dl.extractor.youtube import YoutubeIE

import youtube_dl.extractor.youtube as yt
help(yt)

yt=YoutubeIE()

video_id = 'HRfNqYoO9EU'
player_url="https://www.youtube.com/yts/jsbin/player_ias-vfl49f_g4/en_US/base.js" 
unsig= 'ALgxI2wwRgIhAN3cG9UXPZSyZcwx2fTOFvbKT_5CAb475HUHuTjSjOw-AiEAjaY1JtcKuHMQkHyCt5cKGBqazj7mpR4EQ1nwGYvhkEc=' 

signature = yt._decrypt_signature(unsig, video_id, player_url)
print(signature)
```
