### ISSUE TITLE
How to download youtube playlist info using youtube-dl in a python program?

### ISSUE THREAD

**Issue by abhiank** [ytdl-org/youtube-dl#21505]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

I'm trying to download info about all items in a youtube playlist. I've figured out the command to execute on the terminal but I'm unable to figure out its equivalent code when embedded in a python program. 

Here's the terminal command I use : 
`youtube-dl --dump-single-json --flat-playlist PLFftu4DSZBSwrGiOlZXKHRSoKArsKSuz9 > /Users/abhimanyu/Desktop/list.json
`

Here's how far I got in embedded python : 
```
import youtube_dl

ydl = youtube_dl.YoutubeDL({'dump_single_json': 'True',
                            'extract_flat' : 'True'})

with ydl:
    result = ydl.download([
        'https://www.youtube.com/playlist?list=PLFftu4DSZBSwrGiOlZXKHRSoKArsKSuz9'])

print(len(result))
```

I also tried `ydl.extract_info` but that starts fetching info about each video individually which I don't need.

**Comment by dstftw** [comment]
Arguments are bools not strings.

**Comment by abhiank** [comment]
Oh thank you @dstftw. That was a really silly mistake 😅.  I'm still kinda new to Python so the syntax confuses me sometimes. 

Ps. It worked!

**Comment by abhiank** [comment]
Hey @dstftw, I'm stuck again. I'm unable to capture the json output into a variable. In the current code, result only has a value of 0 and not the json which I was expecting. How do I do that?

**Comment by silverbacknet** [comment]
When downloading, 0 means success. Anything else means an error. (Classic C behavior.)

You were on the right track, `result = ydl.extract_info(url, False)` should give what you want. Default is to download everything, which you don't want, thus download=False.

**Comment by abhiank** [comment]
Thank you @silverbacknet
