### ISSUE TITLE
issue: "recompile FFmpeg with openssl"

### ISSUE THREAD

**Issue by LinuxOpa** [ytdl-org/youtube-dl#21503]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

ok, "recompile FFmpeg with openssl", do you know a good HOWTO for dummies?
hints welcome!

**Comment by dstftw** [comment]
Google it.

**Comment by LinuxOpa** [comment]
for those who are interested: "https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu"
add --enable-openssl to the compilation parameters
happy compiling...
