### ISSUE TITLE
Default audio download isnt highest quality

### ISSUE THREAD

**Issue by superlonglong** [ytdl-org/youtube-dl#21509]
## Checklist

- [ x] I've verified that I'm running youtube-dl version **2019.06.21**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl -v -x https://www.youtube.com/watch?v=o_zD1YCj2fk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-x', 'https://www.youtube.com/watch?v=o_zD1YC
j2fk']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.06.21
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] o_zD1YCj2fk: Downloading webpage
[youtube] o_zD1YCj2fk: Downloading video info webpage
[youtube] {18} signature length 104, html5 player vfl49f_g4
[youtube] {137} signature length 104, html5 player vfl49f_g4
[youtube] {248} signature length 104, html5 player vfl49f_g4
[youtube] {136} signature length 104, html5 player vfl49f_g4
[youtube] {247} signature length 100, html5 player vfl49f_g4
[youtube] {135} signature length 104, html5 player vfl49f_g4
[youtube] {244} signature length 104, html5 player vfl49f_g4
[youtube] {134} signature length 100, html5 player vfl49f_g4
[youtube] {243} signature length 104, html5 player vfl49f_g4
[youtube] {133} signature length 100, html5 player vfl49f_g4
[youtube] {242} signature length 104, html5 player vfl49f_g4
[youtube] {160} signature length 104, html5 player vfl49f_g4
[youtube] {278} signature length 104, html5 player vfl49f_g4
[youtube] {140} signature length 100, html5 player vfl49f_g4
[youtube] {171} signature length 104, html5 player vfl49f_g4
[youtube] {249} signature length 104, html5 player vfl49f_g4
[youtube] {250} signature length 100, html5 player vfl49f_g4
[youtube] {251} signature length 104, html5 player vfl49f_g4
[debug] Invoking downloader on 'https://r2---sn-fpqxc5oq-hxae.googlevideo.com/vi
deoplayback?expire=1561370023&ei=R0kQXaWqEcHRz7sPiNiW4AE&ip=119.18.0.170&id=o-AO
t-8uBf-YuA5JvjB5QXrjkCAfUveEur8qvUfnsBGmVj&itag=171&source=youtube&requiressl=ye
s&mm=31%2C29&mn=sn-fpqxc5oq-hxae%2Csn-ntqe6n7k&ms=au%2Crdu&mv=m&pl=24&initcwndbp
s=2488750&mime=audio%2Fwebm&gir=yes&clen=2657363&dur=157.731&lmt=156085012590574
8&mt=1561348324&fvip=5&keepalive=yes&beids=9466585&c=WEB&txp=2301222&sparams=exp
ire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&
lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgATSS0FtQcD2dJxvKV
on2KhhO2dqPFJOgR7F2W2qtEyQCIEQGZ2NRUCLxBI5gLLx41g3rju70oxB5G_drapRsunQ5&sig=ALgx
I2wwRQIhANQmBr1wbyJzwp_8_I1VyFuFKA_a61BR_vVcLXtJeK8sAiA1UUwcHMOn-Vx9jc2ZnACTpJ6x
8yxcj3gzDoQsViL9xg==&ratebypass=yes'
[download] blink 182 - What's My Age Again for Brass Quintet and Drums with shee
t music-o_zD1YCj2fk.webm has already been downloaded
[download] 100% of 2.53MiB
ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_
g4\build\youtube_dl\YoutubeDL.py", line 2054, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_
g4\build\youtube_dl\postprocessor\ffmpeg.py", line 272, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_
g4\build\youtube_dl\postprocessor\ffmpeg.py", line 166, in get_audio_codec
youtube_dl.utils.PostProcessingError: ffprobe/avprobe and ffmpeg/avconv not foun
d. Please install one.

## Description

-x chooses the largest file, not the highest bitrate.

Youtube has many different audio qualities for this song

https://www.youtube.com/watch?v=o_zD1YCj2fk

as seen in this -F

format code  extension  resolution note
249          webm       audio only DASH audio   66k , opus @ 50k, 1.04MiB
250          webm       audio only DASH audio   87k , opus @ 70k, 1.36MiB
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k, 2.44MiB
251          webm       audio only DASH audio  160k , opus @160k, 2.62MiB
171          webm       audio only DASH audio  162k , vorbis@128k, 2.53MiB

file chosen when you don't specify is the 128k vorbis, not the 160k opus. this punishes opus for being more efficient.

also, if youtube is being so kind as to wrap things up in .opus for us, we dont really need ffmpeg?

**Comment by ealgase** [comment]
youtube-dl's quality selection always picks largest filesize over bitrate, if you don't like it, specify manually.

It's not wrapped in .opus, it's wrapped in .webm, the codec is opus.

**Comment by dstftw** [comment]
It selects format with max total bitrate as reported by metadata that is 171.
