### ISSUE TITLE
To be able to choose different extractor, and why.

### ISSUE THREAD

**Issue by felisucoibi** [ytdl-org/youtube-dl#21519]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.06.21**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description
 In this issue somebody ask for a force-stractor stractor
But was closed because it did not make sense, i think it does.
https://github.com/ytdl-org/youtube-dl/issues/13891

I think can be usefull, for example for this website
www.rtve.es
There are some stractors, rtve.es:alacarta, rtve.es:infantil etc...

The rtve.es:alacarta  extractor  gets better quality than rtve:infantil
So i woud like to use the rtve:alacarta instead the one that is autodetected.

EXAmple url, it gets 480p video, but with rtve:alacarta could be 570p:
http://www.rtve.es/infantil/serie/amanecer-croods/video/abu-hechicera/4103601/

**Comment by dstftw** [comment]
Bother to at least read my comment.

**Comment by felisucoibi** [comment]
> Bother to at least read my comment in issue linked.

thanks for your kindness, i readed obviously your answer.
And yotube-dl works perfect after my hack to force use the extractor i want.
