### ISSUE TITLE
[disneynow.go.com] Falling back on generic information extractor. / Unsupported URL

### ISSUE THREAD

**Issue by RuneMagle** [ytdl-org/youtube-dl#21528]
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
C:\Users\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs --convert-subs srt https://disneynow.com/shows/amphibia/season-01/episode-06-sprig-vs-hop-pop-girl-time/vdka10596720 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', '--convert-subs', 'srt', 'https://disneynow.com/shows/amphibia/season-01/episode-06-sprig-vs-hop-pop-girl-time/vdka10596720', '-v', '--no-check-certificate', '--hls-prefer-ffmpeg']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.06.21
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-93294-g056a2ac168, ffprobe N-93294-g056a2ac168, rtmpdump 2.4
[debug] Proxy map: {}
[generic] vdka10596720: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vdka10596720: Downloading webpage
[generic] vdka10596720: Extracting information
WARNING: [generic] vdka10596720: Failed to parse JSON Expecting value: line 7 column 29 (char 244)
ERROR: Unsupported URL: https://disneynow.com/shows/amphibia/season-01/episode-06-sprig-vs-hop-pop-girl-time/vdka10596720
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\extractor\generic.py", line 3316, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://disneynow.com/shows/amphibia/season-01/episode-06-sprig-vs-hop-pop-girl-time/vdka10596720
...
<end of log>
```

---
- Single video: https://disneynow.com/shows/amphibia/season-01/episode-06-sprig-vs-hop-pop-girl-time/vdka10596720
- Single video: https://disneynow.com/shows/ravens-home/season-03/episode-02-lost-at-chelsea/vdka10600539

---

### Description of *issue*
Seems to happen with all videos on DisneyNow. I think it might be because of a new change in the URL, since it says it is unsupported.

**Comment by ashr31** [comment]
Me too. I've tried even doing it and changing it to disneynow.go.com, but turns out that they've shifted it completely. Time to issue an update?

**Comment by 987computer** [comment]
It appears Mixer is doing the same thing, where the tool assumes the VOD link is for downloading a currently online stream...

**Comment by Cov-fefe** [comment]
Also having this issue.  Was able to download from Disneynow on June 6th using a 2018 version of Youtube-DL. 

Tried again yesterday on the 2018 version and received an error message about URL not supported.

Updated to 2019.06.21 and same issue.  See output below

`youtube-dl -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 https://disneynow.com/shows/handy-manny/season-03/episode-48-valentines-day-party/vdka0_9yqgli8o
[generic] vdka0_9yqgli8o: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vdka0_9yqgli8o: Downloading webpage
[generic] vdka0_9yqgli8o: Extracting information
ERROR: Unsupported URL: https://disneynow.com/shows/handy-manny/season-03/episode-48-valentines-day-party/vdka0_9yqgli8o`

**Comment by RuneMagle** [comment]
Where should I send a tv provider account?
