### ISSUE TITLE
BBC URLs not downloading

### ISSUE THREAD

**Issue by methodphoto** [ytdl-org/youtube-dl#21525]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.06.21**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-f', u'mp4', u'https://www.bbc.co.uk/programmes/m0006775']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.21
[debug] Python version 2.7.10 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[bbc.co.uk] m0006775: Downloading video page
[bbc.co.uk] m0006775: Downloading playlist JSON
[bbc.co.uk] m0006775: Downloading legacy playlist XML
ERROR: Unable to download XML: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)```


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Please make sure the description is worded well enough to be understood, see https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

Trying various BBC URLs and get errors as shown in the log
https://www.bbc.co.uk/programmes/m0006775

**Comment by ethereal99** [comment]
i also have the same problem. the videos play on bbc iplayer but i cannot download using the latest youtube-dl

`T:\youtube-dl>youtube-dl --verbose "https://www.bbc.co.uk/iplayer/episode/b00hq3
27/the-high-life-6-dunk" -o recording.ts
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.bbc.co.uk/iplayer/episode/
b00hq327/the-high-life-6-dunk', '-o', 'recording.ts']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.06.21
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[bbc.co.uk] b00hq327: Downloading video page
[bbc.co.uk] b00hq327: Downloading playlist JSON
[bbc.co.uk] b000cfg7: Downloading media selection XML
[bbc.co.uk] b000cfg7: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 503: Service Temporarily Un
available
[bbc.co.uk] b000cfg7: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Temporaril
y Unavailable
[bbc.co.uk] b000cfg7: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Temporaril
y Unavailable
[bbc.co.uk] b000cfg7: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Temporaril
y Unavailable
[bbc.co.uk] b000cfg7: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 503: Service Temporaril
y Unavailable
[bbc.co.uk] b000cfg7: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [SSL: SSLV3_ALERT_HANDS
HAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:600)>
[bbc.co.uk] b000cfg7: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_H
ANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:600)>
[bbc.co.uk] b000cfg7: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_H
ANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:600)>
[bbc.co.uk] b000cfg7: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_H
ANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:600)>
[bbc.co.uk] b000cfg7: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_H
ANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:600)>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_
g4\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_
g4\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_
g4\build\youtube_dl\extractor\bbc.py", line 577, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_
g4\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.
`

thank you

**Comment by stoney27** [comment]
Hi, 
I am having the same issue as the above to users.
Any help would be appreciated and let me know if I can run any commands or give more debug output.

Running the code on a Mac. OS 10.14.5
`youtube-dl -U                                                                                                                                      
youtube-dl is up-to-date (2019.06.21)`

### Error:
```
~ » youtube-dl --verbose https://www.bbc.co.uk/iplayer/episode/p06cxp2y/eastenders-the-real-stories-series-1-6-eugenes-story 
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: [u'--verbose', u'https://www.bbc.co.uk/iplayer/episode/p06cxp2y/eastenders-the-real-stories-series-1-6-eugenes-story']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2019.06.21
    [debug] Python version 2.7.10 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
    [debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
    [debug] Proxy map: {}
    [bbc.co.uk] p06cxp2y: Downloading video page
    [bbc.co.uk] p06cxp2y: Downloading playlist JSON
    [bbc.co.uk] p06d0nb4: Downloading media selection XML
    [bbc.co.uk] p06d0nb4: Downloading MPD manifest
    WARNING: Failed to download MPD manifest: HTTP Error 503: Service Temporarily Unavailable
    [bbc.co.uk] p06d0nb4: Downloading m3u8 information
    WARNING: Failed to download m3u8 information: HTTP Error 503: Service Temporarily Unavailable
    [bbc.co.uk] p06d0nb4: Downloading m3u8 information
    WARNING: Failed to download m3u8 information: HTTP Error 503: Service Temporarily Unavailable
    [bbc.co.uk] p06d0nb4: Downloading m3u8 information
    WARNING: Failed to download m3u8 information: HTTP Error 503: Service Temporarily Unavailable
    [bbc.co.uk] p06d0nb4: Downloading m3u8 information
    WARNING: Failed to download m3u8 information: HTTP Error 503: Service Temporarily Unavailable
    [bbc.co.uk] p06d0nb4: Downloading MPD manifest
    WARNING: Failed to download MPD manifest: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
    [bbc.co.uk] p06d0nb4: Downloading m3u8 information
    WARNING: Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
    [bbc.co.uk] p06d0nb4: Downloading m3u8 information
    WARNING: Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
    [bbc.co.uk] p06d0nb4: Downloading m3u8 information
    WARNING: Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
    [bbc.co.uk] p06d0nb4: Downloading m3u8 information
    WARNING: Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
    ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
        ie_result = ie.extract(url)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
        ie_result = self._real_extract(url)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 577, in _real_extract
        self._sort_formats(formats)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
        raise ExtractorError('No video formats found')
    ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
```
> py -3.7 .\youtube_dl\__main__.py https://www.bbc.co.uk/programmes/m0006775
[bbc.co.uk] m0006775: Downloading video page
[bbc.co.uk] m0006775: Downloading playlist JSON
[bbc.co.uk] m0006773: Downloading media selection XML
[bbc.co.uk] m0006773: Downloading MPD manifest
[bbc.co.uk] m0006773: Downloading m3u8 information
[bbc.co.uk] m0006773: Downloading m3u8 information
[bbc.co.uk] m0006773: Downloading MPD manifest
[bbc.co.uk] m0006773: Downloading m3u8 information
[bbc.co.uk] m0006773: Downloading m3u8 information
[bbc.co.uk] m0006773: Downloading MPD manifest
[bbc.co.uk] m0006773: Downloading m3u8 information
[bbc.co.uk] m0006773: Downloading m3u8 information
[bbc.co.uk] m0006773: Downloading MPD manifest
[bbc.co.uk] m0006773: Downloading m3u8 information
[bbc.co.uk] m0006773: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 126
[download] Destination: Book of the Week, Modern Nature, Episode 2-m0006773.mp4
[download]   7.9% of ~32.21MiB at  1.08MiB/s ETA 01:06
ERROR: Interrupted by user
```
