### ISSUE TITLE
site support/feature request: livejournal.com

### ISSUE THREAD

**Issue by ytdluser** [ytdl-org/youtube-dl#21526]
Checklist

    I'm reporting a site feature request
    I've verified that I'm running youtube-dl version 2019.06.21
    I've searched the bugtracker for similar site feature requests including closed ones

Description

Downloading videos from URLs like "https://*.livejournal.com/video/*" does not work.
Example:

X:\video>youtube-dl -v "https://andrei-bt.livejournal.com/video/album/407/?mode=view&id=51272"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://andrei-bt.livejournal.com/video/album/407/?mode=view&id=51272']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.06.21
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-93214-g7e4d3dbe18, ffprobe N-93214-g7e4d3dbe18
[debug] Proxy map: {}
[generic] ?mode=view&id=51272: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?mode=view&id=51272: Downloading webpage
[generic] ?mode=view&id=51272: Extracting information
ERROR: Unsupported URL: https://andrei-bt.livejournal.com/video/album/407/?mode=view&id=51272
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmppgbwk_g4\build\youtube_dl\extractor\generic.py", line 3316, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://andrei-bt.livejournal.com/video/album/407/?mode=view&id=51272

The livejournal.com is a generic blogging platform. The video itself is usually referenced like this: https://andrei-bt.livejournal.com/video/album/407/?mode=view&id=51272 while the page where it is embedded could be seen here https://andrei-bt.livejournal.com/1363799.html

Thank you in advance!

**Comment by mindsolve** [comment]
I do not know whether or not this is helpful, but that page is using a player called EaglePlayer.
The `video/album/` page contains the text `"storageid":<number here>` inside of a <script> tag.
With this storageId you can request the API for video information:
`https://vc.videos.livejournal.com/api/player_data?id=<$storageId>`, which returns a JSON response.
Of special interest is the following tree:
`playlist`.`viewports[0]`.`medialist[0]`.`sources`.`secure_m3u8`.`auto`
which contains a URL in this form:
`https://view.eaglecdn.com/api/resources/<random code>/secure_link_player?expired=2&account=lj&type=hlsvod`.
This URL contains in `data`[0] the URL to the m3u8 file.

Hope this helps in any way!
