### ISSUE TITLE
YT playlist DL dies completely on copyright block

### ISSUE THREAD

**Issue by Baylink-gh** [ytdl-org/youtube-dl#21521]
- [ ] I'm reporting a broken site support issue
- [ x ] I've verified that I'm running youtube-dl version **2019.06.21**
- [ x ] I've checked that all provided URLs are alive and playable in a browser
- [ x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x ] I've read bugs section in FAQ
- [ x ] I've not only read, but can recite, and do promulgate Tatham on bug reporting and Raymond on Smart Questions

## Verbose log

```
C:\proj\amj>youtube-dl --geo-bypass https://www.youtube.com/playlist?list=PLNsr2wccuVS_9GLw001Efp03JjY9i8FEu
[youtube:playlist] PLNsr2wccuVS_9GLw001Efp03JjY9i8FEu: Downloading webpage
[download] Downloading playlist: AMJ
[youtube:playlist] playlist AMJ: Downloading 28 videos
[download] Downloading video 1 of 28
[youtube] 6Jx9QILJeEY: Downloading webpage
[youtube] 6Jx9QILJeEY: Downloading video info webpage
[download] Destination: History Channel Documentary Top Secret Story of Abraham Lincoln Full Documentary-6Jx9QILJeEY.webm
[download] 100% of 237.61MiB in 00:22
[download] Downloading video 2 of 28
[youtube] KJVuqYkI2jQ: Downloading webpage
[youtube] KJVuqYkI2jQ: Downloading video info webpage
[download] Destination: Lincoln Official Trailer #1 (2012) Steven Spielberg Movie HD-KJVuqYkI2jQ.mp4
[download] 100% of 11.82MiB in 00:01
[download] Downloading video 3 of 28
[youtube] v6iat5U8hpc: Downloading webpage
[youtube] v6iat5U8hpc: Downloading video info webpage
[youtube] v6iat5U8hpc: Downloading js player vfl49f_g4
[youtube] v6iat5U8hpc: Downloading js player vfl49f_g4
[download] Destination: Lincoln - The Untold Stories (Documentary)-v6iat5U8hpc.webm
[download] 100% of 491.74MiB in 00:44
[download] Downloading video 4 of 28
[youtube] c-W5fGCAzOk: Downloading webpage
[youtube] c-W5fGCAzOk: Downloading video info webpage
[download] Destination: The Truth About Abraham Lincoln-c-W5fGCAzOk.mp4
[download] 100% of 207.46MiB in 00:19
[download] Downloading video 5 of 28
[youtube] ji-QRt2Osb0: Downloading webpage
[youtube] ji-QRt2Osb0: Downloading video info webpage
ERROR: This video contains content from Starmedia_Affiliate, who has blocked it on copyright grounds.
C:\proj\amj>
[ ... further videos were expected here, but the program exited ...]
```

## Description

When I point the program at a YouTube playlist, I understand if it won't download videos which YouTube likewise would not play, because an owner's filed a copyright strike against them.  But I'd expect that it's behavior would be to skip the video, and proceed to the next element in the playlist.

Instead, it just dies.

Is it impossible to proceed because YT does the playlist serialization, and won't *provide* the next video?  The web player generally just moves on to the next clip.

**Comment by Baylink-gh** [comment]
Also, I note, *it doesn't tell you the name of the video that's killing it*, just the filename...

**Comment by dstftw** [comment]
This is expected behavior.

**Comment by bitraid** [comment]
@Baylink-gh use `--ignore-errors`

**Comment by Baylink-gh** [comment]
Note to dstftw: Bitraids reply was *useful*; yours really wasn't.   Thanks, bit.

I *did* the homework you asked of me on the bug report...

**Comment by dstftw** [comment]
No you did not. It clearly asks to use search for questions answered thousands of times.
