### ISSUE TITLE
YouTube: Include option to treat "HTTP Error 503: Service Unavailable" for specific format as: format unavailable

### ISSUE THREAD

**Issue by spiralsam** [ytdl-org/youtube-dl#21527]
- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.06.21**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I've come across video that although it has audio on the site, it (apparently?) does not have any available separate audio format associated with it. Download attempt is using "-f bestaudio" parameter.  youtube-dl makes download attempts with familiar output such as:

"[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 1 of 10)..."

Then aborts. This is similar to #18916. However, "-f best" with "-x" audio conversion options can possibly work fine enough (it does in my own cases). The problem is that the format selection options described in documentation for auto-selecting other formats when preferred ones are unavailable do not seem to work. For example, this cannot be used: "-f bestaudio/best" (plus "-x ..." for my cases). Youtube-dl simply aborts after attempting "bestaudio" format (after default 10 retries of HTTP Error 503), but then won't attempt "best" afterward.

I assume this is expected behavior (?), but especially for playlists it can be undesirable. So perhaps there can be an option to treat this YouTube 503 Error as invalid format. This way, alternative formats can then be auto-attempted using the "/" format selection option.

**Comment by bitraid** [comment]
The  "Error 503" means there is a problem with the server or with your network . There is nothing for youtube-dl to do - if you try later or from different network, it should work. For example, the video link from #18916 (you didn't provide any video link here) works fine with me, for every format.
