### ISSUE TITLE
WARNING: Could not send HEAD request to 

### ISSUE THREAD

**Issue by NickCarchidi** [ytdl-org/youtube-dl#21533]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2019.06.21**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

Everything was working fine up until this morning. 

I receive the following error:

"[download] Harry Potter and the Sorcerer's Stone Part 2 Flipendo Challange has already been recorded in archive

[download] Finished downloading playlist: Harry Potter and the Sorcerer's Stone PC Walkthrough

WARNING: The url doesn't specify the protocol, trying with http

[generic] best: Requesting header

WARNING: Could not send HEAD request to http://(bestvideo[width>=1920]/bestvideo)+bestaudio/best: <urlopen error [Errno 11001] getaddrinfo 
failed>

[generic] best: Downloading webpage

ERROR: Unable to download webpage: <urlopen error [Errno 11001] getaddrinfo failed> (caused by URLError(gaierror(11001, 'getaddrinfo failed'),))

D:\Y19>PAUSE
Press any key to continue . . ."

My script, which was working fine up until a few hours ago:

youtube-dl -o --format --batch-file  "YouTube_Channels.txt" "(bestvideo[width>=1920]/bestvideo)+bestaudio/best" --download-archive YouTube_Channel_Archive.txt --output "%%(uploader)s/%%(upload_date)s_%%(title)s/%%(title)s_%%(resolution)s_%%(id)s.%%(ext)s" --add-metadata --write-info-json --write-all-thumbnails --embed-subs --all-subs --write-description --ignore-errors --write-annotation --merge-output-format mkv
PAUSE

What is the issue, here? Thanks!

**Comment by sdudley7** [comment]
Same issue
