### ISSUE TITLE
Get Download URL from `get_video_info` document

### ISSUE THREAD

**Issue by KevinKelbie** [ytdl-org/youtube-dl#21541]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, I'm sorry if this isn't the right place but if you could point me in the right direction that would be great. I am trying to get the download URL for a video that is blocked in my country, I figured I'd use tor browser to get access to the video, and download the `get_video_info` document, which worked. I tried parsing the download URL on my own but for this video its not working, I think its got something to do with #897 but I could be wrong.

My question is, does youtube-dl have a parse only mode that I can pass the document into rather than it fetching it itself.

Something like: `youtube-dl --url-from-file get_video_info`

**Comment by dstftw** [comment]
No such option and most likely this won't work. You must use proxy with youtube-dl itself.
