### ISSUE TITLE
500: Soundcloud

### ISSUE THREAD

**Issue by kaotisk-hund** [ytdl-org/youtube-dl#21546]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.06.27**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl --verbose https://soundcloud.com/t-m-t-p-75623799/shady-noons-at-the-place-ambient-industrial-set-mix 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://soundcloud.com/t-m-t-p-75623799/shady-noons-at-the-place-ambient-industrial-set-mix']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.24
[debug] Python version 2.7.16 - Linux-5.1.11-300.fc30.x86_64-x86_64-with-fedora-30-Thirty
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[soundcloud] t-m-t-p-75623799/shady-noons-at-the-place-ambient-industrial-set-mix: Resolving id
[soundcloud] t-m-t-p-75623799/shady-noons-at-the-place-ambient-industrial-set-mix: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 503, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2178, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

## Description

WRITE DESCRIPTION HERE

I get a 500 error when trying to download from soundcloud

**Comment by pfarnham** [comment]
You've checked that you're running the latest version 2017.09.27,  but in fact, the log states that you're using version 2017.09.24. Nonetheless, I'm getting 500 Internal Server Errors on soundcloud as well.

**Comment by rkomar4815** [comment]
I'm also having this issue.

**Comment by pengmengnanlan** [comment]
I'm also having this issue. Actually it worked successfully yestarday(27/06), but now I'm getting 500 Internal Server Errors on soundcloud.
