### ISSUE TITLE
problem with youtube-dl used in batch script

### ISSUE THREAD

**Issue by stax76** [ytdl-org/youtube-dl#21548]
I've youtube-dl in my user PATH, I can use `youtube-dl.exe` in my batch script but I cannot use the short version `youtube-dl`, maybe someone can confirm that it is a general problem or knows how to fix it.

location is:

D:\Projekte\CS\mpv.net\mpv.net\bin\x64\youtube-dl.exe

**Comment by dstftw** [comment]
Most likely invalid `%PATH%`.
