### ISSUE TITLE
Reencoiding to same format with --recode-video

### ISSUE THREAD

**Issue by SegiH** [ytdl-org/youtube-dl#21557]
## Checklist

- [x] I've verified that I'm running youtube-dl version 2019.06.27
- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Verbose Log
Not an error so it's not needed

## Description
If you pass the argument --recode-video with a format such as mp4 and the video is already in that same format, is Youtube-DL smart enough to not recode the video ?

**Comment by dstftw** [comment]
It is.

**Comment by SegiH** [comment]
perfect thanks!
