### ISSUE TITLE
[https @ 0000000003001860] HTTP error 403 Forbidden [crypto @ 0000000003001740] Unable to open resource: [hls,applehttp @ 00000000024825a0] Failed to open segment of playlist

### ISSUE THREAD

**Issue by ComputerUser-CU** [ytdl-org/youtube-dl#21554]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello,

I'm trying to download an MP4 video which is being streamed as fragmented ts files with m3u8 playlist. The screenshot of the Network tab in Opera Devtools is as follows:
![XHR](https://user-images.githubusercontent.com/20037489/60344379-03f4c480-99d4-11e9-8d80-b2570cb1b7c4.png)

So from there, I'm giving youtube-dl the URL of the entry beginning with "_chunklist_w.._". In the first try, youtube-dl recorded the stream for only about 3 minutes 38 seconds before giving up. The verbose logs are here:
[FailedDownload(Verbose).txt](https://github.com/ytdl-org/youtube-dl/files/3339354/FailedDownload.Verbose.txt)

Googling the issue threw up [this webpage](https://gi thub.com/ytdl-org/youtube-dl/issues/10015). Also, another webpage suggested that using `--hls-prefer-native` was preferable in such cases since FFMPEG doesn't handle network recording very well. So with the  `--hls-prefer-native` flag, I got these logs: 
[FailedDownload(hls).txt](https://github.com/ytdl-org/youtube-dl/files/3339596/FailedDownload.hls.txt)

I'm sorry I forgot to take verbose logs with the `--hls-prefer-native` above.

Anyhow, I noticed that [this webpage](https://gi thub.com/ytdl-org/youtube-dl/issues/10015) also talked of installing python-crypto and then using `--hls-prefer-native`. So I installed Python 3.7.3 (the latest version of Python) for windows. Then, I got python-crypto_2.6.1.orig.tar.gz from [this page's](https://packages.debian.org/stretch/python-crypto) right hand column. However, as I tried installing python-crypto with the command `python setup.py install`, I got this error:
`warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
building 'Crypto.Random.OSRNG.winrandom' extension
error: Unable to find vcvarsall.bat`

As I went through the README file in the python-crypto package, it said that "_PyCrypto is written and tested using Python version 2.1 through 3.2_". Also, [this youtube video](https://www.youtube.com/watch?v=1PnU67wwF5A) suggested installing Python 2.7.x since PyCrypto worked best with it. So I uninstalled Python 3.7.3 and installed 2.7.16 (python-2.7.16.amd64.msi) from https://www.python.org.

Then, I installed PyCrypto by running the command `pip install pycrypto` as suggested [here](https://pypi.org/project/pycrypto/). It also asked me to install Microsoft C++ Compiler for Python 2.7 which I duly complied with. PyCrypto was finally installed successfully.

However, I am unable to download the complete video even now. The verbose logs for ffmpeg download and hls-prefer-native download are as follows:
[FailedDownload(Verbose)(ffmpeg)(evenAfterPyCrypto).txt](https://github.com/ytdl-org/youtube-dl/files/3339605/FailedDownload.Verbose.ffmpeg.evenAfterPyCrypto.txt)
[FailedDownload(hls)(Verbose)(evenAfterPyCrypto).txt](https://github.com/ytdl-org/youtube-dl/files/3339606/FailedDownload.hls.Verbose.evenAfterPyCrypto.txt)

Also, if I try to install python-crypto using `python setup.py install` at the location of my python-crypto_2.6.1.orig.tar package, I still get the error:
`building 'Crypto.Random.OSRNG.winrandom' extension
error: Unable to find vcvarsall.bat`

As I googled this error, I got [this webpage](https://www.tylerbutler.com/2014/12/installing-binary-python-packages-on-windows/#update-setuptools-and-pip). I already have Microsoft C++ Compiler for Python 2.7 installed. So I updated my setuptools and pip as suggested there. But the issue still persists. The logs for this are below:
`
D:\Downloads\python-crypto_2.6.1.orig.tar\pycrypto-2.6.1>python setup.py install
running install
running build
running build_py
running build_ext
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
building 'Crypto.Random.OSRNG.winrandom' extension
error: Unable to find vcvarsall.bat

D:\Downloads\python-crypto_2.6.1.orig.tar\pycrypto-2.6.1>`

Kindly suggest what I need to do right in order to be able to download these videos.

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
