### ISSUE TITLE
how to automatically re-try or continue downloading?

### ISSUE THREAD

**Issue by ixiangwang** [ytdl-org/youtube-dl#21564]
Hi guys: i'm using a VPN software "_**Psiphon 3**_" to get access to Youtube,but it is not stable,
So when Psiphon fails to connect the Internet, the downloading via "**_youtube-dl_**" will also stop.
eveytime i have to type the download command manually,is there a way to re-try or continue downloading automatically?(means when Psiphon has access to the Internet,youtube-dl will automatically continue the previous downloading?)

**Comment by dstftw** [comment]
```
-R, --retries RETRIES            Number of retries (default is 10), or
                                 "infinite".
```

**Comment by ixiangwang** [comment]
> ```
> -R, --retries RETRIES            Number of retries (default is 10), or
>                                  "infinite".
> ```

THANKS so much...
