### ISSUE TITLE
Downloading Soundcloud sets on latest yt-dl results in 500 error

### ISSUE THREAD

**Issue by gsot-xyz** [ytdl-org/youtube-dl#21573]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.06.27**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
.\youtube-dl.exe -v https://soundcloud.com/trentkainalu/sets/lotus-gate
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://soundcloud.com/trentkainalu/sets/lotus-gate']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.06.27
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-93851-gdcc999819d
[debug] Proxy map: {}
[soundcloud:set] trentkainalu/sets/lotus-gate: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjzs7t34q\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjzs7t34q\build\youtube_dl\YoutubeDL.py", line 2227, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

Every time I try to download a Soundcloud set (or even a single song from Soundcloud,) I get this HTTP 500 error with no further information other than it being an "internal server error" while downloading the JSON metadata.

Set link: [https://soundcloud.com/trentkainalu/sets/lotus-gate](https://soundcloud.com/trentkainalu/sets/lotus-gate)

**Comment by gsot-xyz** [comment]
Sorry, I don't know what this is a duplicate of. Which bug report or missed FAQ page do I refer to for fixing this issue?

**Comment by remitamine** [comment]
> I've searched the bugtracker for similar bug reports including **closed ones**
