### ISSUE TITLE
Youtube-dl Multi Thread

### ISSUE THREAD

**Issue by Daringbaaz** [ytdl-org/youtube-dl#21577]
Hello Youtube-dl Team, I am New in Youtube-dl and i am trying to Download .mpd Files
But The Downloading Speed is Too Slow, is There any Commands that will Download Files Using Multi-Thread Like External Downloaders,

or Suggest Me any External Downloader Which Support .mpd Links and Boost My Download Speed

**Comment by dstftw** [comment]
No such command.
