### ISSUE TITLE
What command to download best audio only from yt video?

### ISSUE THREAD

**Issue by hasnogaems** [ytdl-org/youtube-dl#21579]
In best quality.

**Comment by ealgase** [comment]
`youtube-dl -x videourl`

**Comment by kuco28** [comment]
> `youtube-dl -x videourl`

Not quite. The best audio quality on YouTube for stereo is opus.
This command download aac audio which is not the best. Well, if video have 5.1 then it is but not for stereo.
Proper command to get best stereo audio is
`youtube-dl -f 251 videourl`
