### ISSUE TITLE
Not downloading certain url

### ISSUE THREAD

**Issue by spencerw96** [ytdl-org/youtube-dl#21572]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.06.27**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --verbose [youtube] 71Cs1pddOO4: Downloading js player vflxACNZ2
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '[youtube]', '71Cs1pddOO4:', 'Downloading', 'js', 'player', 'vflxACNZ2']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.7.3 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: '[youtube]' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:[youtube]" ) to search YouTube
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2230, in _real_extract
    % (url, url), expected=True)
youtube_dl.utils.ExtractorError: '[youtube]' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:[youtube]" ) to search YouTube
```

## Description

WRITE DESCRIPTION HERE
I was using youtube-dl and it was working just fine until I tried downloading from this url
https://www.youtube.com/watch?v=71Cs1pddOO4
I've updated youtube-dl and tried typing the youtube-dl command by putting comments around the url

**Comment by remitamine** [comment]
your command is wrong, pass the URL directly to `youtube-dl`.
