### ISSUE TITLE
[bilibili] Downloading videos on page 2 and 3 etc

### ISSUE THREAD

**Issue by Ngaruhoe** [ytdl-org/youtube-dl#21581]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

When I use youtube-dl on bilibili videos that are compiled in a playlist, it only downloads the first video. 
For example youtube-dl.exe -f best https://www.bilibili.com/video/av57347465/ only let's me download the first video, no matter if I add the /?p=2 or /?p=3 at the end which shows the other parts on bilibili. 
Ticket #16354 seems to be the same issue, but the proposed fixes did not work for me and the linked hastebin is expired, which is why I can't try using the bilibili.py mentioned in the comments. 
Thanks in advance for any help!

**Comment by Ngaruhoe** [comment]
Why was the thread closed when I explicitly stated that I checked the other
threads already, but the proposed changes didn't work for me?

**Comment by bitraid** [comment]
Probably because there is an already open issue (#16052) about this.

**Comment by awei78** [comment]
@Ngaruhoe: 
Your issue same as #20555
Please view: http://www.cr-soft.net/archives/how-to-download-bilibili-video.html
And use youtube-dl_pl.exe, It got the correct cid
