### ISSUE TITLE
Add Python script documentation to docs

### ISSUE THREAD

**Issue by mvbattista** [ytdl-org/youtube-dl#21582]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.06.27**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

For use in a python script, parameters are different than those listed in `README.md` for command line usage. For example, in `README.md`:

```
    --cookies FILE                   File to read cookies from and dump cookie
                                     jar in
```

When trying to call in a standalone Python script importing `youtube_dl`, the same functionality is passed in the `'cookiefile'` argument. 

```
with youtube_dl.YoutubeDL({'cookiefile': '/path/to/cookies.txt'}) as ytdl:
```

Documentation on the translation between command line arguments and Python object instantiation arguments will help developers as opposed to searching through library source code.

**Comment by dstftw** [comment]
List of available programmatic options is clearly mentioned in embedding guide.

**Comment by mvbattista** [comment]
So why can't [this in-code documentation](https://github.com/ytdl-org/youtube-dl/blob/3e4cedf9e8cd3157df2457df7274d0c842421945/youtube_dl/YoutubeDL.py#L137-L312) be moved to a separate embedding Markdown file?
