### ISSUE TITLE
Does youtube-dl have slight delay on start?

### ISSUE THREAD

**Issue by XezolesS** [ytdl-org/youtube-dl#21580]
## Checklist
- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question
I'm trying to make discord bot written in C# and trying to use youtube-dl to play audio from youtube. 
But when the youtube-dl is executed, it delayed about 4 seconds to run. I want this process run immediately.
I don't know whether it is a natural thing or not. Is there any way to fix this?

Here's my arguments in case it needed.

this is for download youtube video.
```
Process prcs = Process.Start(new ProcessStartInfo
{
    FileName = "cmd",
    Arguments = $"/C youtube-dl -o - \"{url}\" | ffmpeg -hide_banner -loglevel panic -i pipe:0 -ac 2 -f s16le -ar 48000 pipe:1",
    UseShellExecute = false,
    RedirectStandardOutput = true,
    CreateNoWindow = true
});
```

and this is for getting the information of youtube video.
```
Process prcs = Process.Start(new ProcessStartInfo
{
    FileName = "youtube-dl",
    Arguments = $"-q -s --get-title --get-duration \"{url}\"",
    UseShellExecute = false,
    RedirectStandardOutput = true,
    CreateNoWindow = true
});
```

**Comment by dstftw** [comment]
On slow machine it may take some time to start. Lazy extractors feature may reduce it to some extent.
