### ISSUE TITLE
Relation between --list-extractors and --extractor-descriptions

### ISSUE THREAD

**Issue by kuerbis** [ytdl-org/youtube-dl#21609]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Do the list-positions of the extractor-descriptions returned by `--extractor-descriptions` correspond to the list-positions of the extractors returned by `--list-extractors`?

For example is the 150. extractor-description of the `--extractor-descriptions`-list the description of the 150. extractor of the `--list-extractors`-list?

**Comment by dstftw** [comment]
No such guarantee.
