### ISSUE TITLE
PluralSight downloads seem to have stopped working - "Unable to download webpage: HTTP Error 403: Forbidden"

### ISSUE THREAD

**Issue by marcthayer** [ytdl-org/youtube-dl#21601]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'-o', u'~/PluralSight/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', u'--sleep-interval', u'60', u'https://app.pluralsight.com/library/courses/test-driven-development-big-picture', u'--playlist-start', u'1', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 2.7.16 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[pluralsight:course] test-driven-development-big-picture: Downloading JSON metadata
[download] Downloading playlist: Test-driven Development: The Big Picture
[pluralsight:course] playlist Test-driven Development: The Big Picture: Collected 31 video ids (downloading 31 of them)
[download] Downloading video 1 of 31
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

## Description

PluralSight doesn't seem to be working for me and a few other people I checked with. It was working as of last week when I first tried this tool to successfully download one course. While trying to download another yesterday, I started running into the above 403 error. Updating to the latest version of this tool didn't change anything, and I don't think that one course a week is enough to trigger any blocks on my side.

Mostly I want someone else to try to confirm if it's account specific to us or not, though all the people I checked with are under different accounts and download at very different frequencies, but all of us are getting 403s now.

**Comment by marcthayer** [comment]
There seem to be a couple posts tangentially related, and some get closed when referring back to this issue: https://github.com/ytdl-org/youtube-dl/issues/20266. However, it's still odd that the same command worked and has been working for several people but only now suddenly is not for all of them.

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by marcthayer** [comment]
@dstftw I did. Is there something in the output that makes it look like they aren't being provided? For additional context, the exact same command works to request Udemy videos. So something on PluralSight is breaking it.

**Comment by marcthayer** [comment]
Also note in the original description above, "It was working as of last week when I first tried this tool to successfully download one course." So the same command also worked on PluralSight the week before. Nothing's changed on my side, account-wise.

**Comment by ajorpheus** [comment]
@marcthayer 

> I did. Is there something in the output that makes it look like they aren't being provided?

I think @dstftw means that in order to reproduce/fix the bug, the youtube-dl devs need a pluralsight account.

**Comment by ajorpheus** [comment]
@dstftw : What is the recommended, confidential way of providing credentials to the devs?

**Comment by LakunleD** [comment]
@dstftw Do you still need a pluralsight account to test with? I can provide you with one

**Comment by Korayem** [comment]
@dstftw I can spare ann account to fix this

**Comment by bellalMohamed** [comment]
Simple fix
1- Download this extension for chrome: https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg
this allows you to read the site cookies; 

2- go to https://pluralsight.com and login to your account

3 - press on the extension icon and download the cookies file 

4 - run the download command  no need to add username or password

youtube-dl --sleep-interval 10 "https://app.pluralsight.com/library/courses/javascript-best-practices" --cookies ~/Downloads/cookies.txt

happy downloading :D

**Comment by adanijel** [comment]
This doesn't seem to work anymore: 
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Applications/MAMP/Library/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/Applications/MAMP/Library/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Applications/MAMP/Library/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/Applications/MAMP/Library/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Applications/MAMP/Library/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by JayabharathP** [comment]
Even I'm getting the same error. The solution provided by @bellalMohamed did not work for me. Although, I am extracting Udemy courses instead of PluralSight. I have checked other bugs & all of them were referenced to this issue.

Can someone please assist with what might be causing this?

**Comment by JayabharathP** [comment]
@dstftw
