### ISSUE TITLE
URL that always gets the latest Windows version?

### ISSUE THREAD

**Issue by WillPittenger** [ytdl-org/youtube-dl#21605]
## Checklist

- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

Is there a URL that always evaluates to the latest Windows version?  I know the python/Linux builds have a single command.  I need something like https://yt-dl.org/downloads/latest-major/youtube-dl.exe

**Comment by dstftw** [comment]
http://yt-dl.org/downloads/latest/youtube-dl.exe

**Comment by WillPittenger** [comment]
Thanks. :D
