### ISSUE TITLE
Youtube-dl repeat a link after video finishes 

### ISSUE THREAD

**Issue by peererror** [ytdl-org/youtube-dl#21621]
I am using youtube-dl pipeline to ffmpeg for    rtsp stream and pushes to rtsp server. Then  clients can play rtsp from vlc or other rtsp players. My problem is that I want to loop same video after it is ended so then when a client is connect it can view video playing
I have user loop=1 arg with YouTube link but no effect.

**Comment by dstftw** [comment]
Write a script.

**Comment by peererror** [comment]
@dstftw thanks for comment how can I use the script to loop video after it ended
