### ISSUE TITLE
youtube_dl.utils.DownloadError: ERROR: 2nli1Gc4Bzw: "token" parameter not in video info (2019.07.02 version))

### ISSUE THREAD

**Issue by moondra2017** [ytdl-org/youtube-dl#21637]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2019.07.02**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

-->

```
C:\Users\Moondra>youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.07.02
[debug] Python version 2.7.12 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-88514-gd5995c531d, ffprobe N-88514-gd5995c531d, phantomjs 2.1.
1
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]
```

## Description

I am trying to run the code from the readme in Python:

```
from __future__ import unicode_literals
import youtube_dl

ydl_opts = {}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://www.youtube.com/watch?v=BaW_jenozKc'])

```

and I am running into the following error:

```
ERROR: BaW_jenozKc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Moondra\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Moondra\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\extractor\common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Moondra\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1392, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: BaW_jenozKc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Moondra/Desktop/testing_youtube.py", line 6, in <module>
    ydl.download(['https://www.youtube.com/watch?v=BaW_jenozKc'])
  File "C:\Users\Moondra\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 1896, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "C:\Users\Moondra\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 783, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Moondra\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Moondra\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 559, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: BaW_jenozKc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>>> 
```

**Comment by bitraid** [comment]
How/when did you download the source code?

**Comment by moondra2017** [comment]
I installed via PIP today.

**Comment by moondra2017** [comment]
Ah, sorry my mistake. It seems I updated wrong version of Python.

**Comment by junior-sorin** [comment]
Hi there!

I'm hitting the same issue, please find the output from my terminal:

 ~ $ youtube-dl --verbose https://www.youtube.com/watch?v=IfPkIH_zM0w
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=IfPkIH_zM0w']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.8 (CPython) - Linux-4.15.0-52-generic-x86_64-with-Peppermint-9-bionic
[debug] exe versions: ffmpeg 3.4.6-0ubuntu0.18.04.1, ffprobe 3.4.6-0ubuntu0.18.04.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] IfPkIH_zM0w: Downloading webpage
[youtube] IfPkIH_zM0w: Downloading video info webpage
ERROR: IfPkIH_zM0w: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1624, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: IfPkIH_zM0w: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


Hopefully would help,

With kind regards,
Junior
