### ISSUE TITLE
[question] Is it possible to auto number the videos with the title included?

### ISSUE THREAD

**Issue by blackoutworm** [ytdl-org/youtube-dl#21634]
Hi there. When I try using both number and the title tag (youtube-dl --auto-number -o "%(title)s.%(ext)s"), I get an error.
Is there a way around this?
Reason is that the title tag does not include the episode number.

**Comment by dstftw** [comment]
You must use it in template itself.

**Comment by blackoutworm** [comment]
How do I do that?

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#output-template
