### ISSUE TITLE
(question) different configuration for each extractor

### ISSUE THREAD

**Issue by KaMyKaSii** [ytdl-org/youtube-dl#21635]
## Checklist

- [x] I'm asking a question
- - [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is there any way to use different configurations for different extractors? For YouTube I would like it to be used:
 `-f "webm[height=1080][fps=60]"+bestaudio/"webm[height=720][fps=60]"+bestaudio/"webm[height=1080]"+bestaudio/"webm[height=720]"+bestaudio/"mp4[height=1080][fps=60]"+bestaudio/"mp4[height=720][fps=60]"+bestaudio/"mp4[height=1080]"+bestaudio/"mp4[height=720]"+bestaudio/best`
While for all other extractors: `-f bestvideo+bestaudio/best`
If it is not possible, could anyone consider implementing this idea in youtube-dl?  Thank you!

**Comment by dstftw** [comment]
Not possible. Though custom config can be specified with `--config-location`.
