### ISSUE TITLE
I've tried to download audio + video using -f but still seperated

### ISSUE THREAD

**Issue by jeraldpunx** [ytdl-org/youtube-dl#21643]
```
<?php

        $url = "https://www.youtube.com/watch?v=2MRdtXWcgIw";
        $cmd = 'youtube-dl -g -f bestvideo+bestaudio/best ' . escapeshellarg($url);
        exec($cmd, $outputsd);
        print_r($outputsd);
```

This is my code, it shows separated link for audio and video instead of combined with different quality.

![image](https://user-images.githubusercontent.com/5249781/60680105-9dccdd80-9ebc-11e9-8641-44066b02f130.png)

**Comment by dstftw** [comment]
Bother to read FAQ.

**Comment by jeraldpunx** [comment]
can I used the ffmpeg.exe and youtube-dl.exe in same folder on project? without using the PATH environment ?
