### ISSUE TITLE
Is skipping live youtube streams possible?

### ISSUE THREAD

**Issue by R01NDev** [ytdl-org/youtube-dl#21649]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is it possible to skip livestreams when downloading from XML subscribers list.

**Comment by R01NDev** [comment]
why was this question closed exactly?

**Comment by TaktakTaktouk** [comment]
Try '!is_live'  if you don't want to download live videos

**Comment by R01NDev** [comment]
Thank you, any idea if the library downloads the stream after it's done streaming ?
________________________________
