### ISSUE TITLE
May I ask you a question about youtube-dl

### ISSUE THREAD

**Issue by realhongkong** [ytdl-org/youtube-dl#21652]
## Checklist

- [o] I'm asking a question
- [o] I've looked through the README and FAQ for similar questions
- [o] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
__
Hello!
May I ask you a question? 
I'm using your program.(youtube-dl)

Once i see the YouTube video i want on "Stats for Nerds," 
it says
"Current / Optimal Res
1280x720@30 / 1280x720@30

Codecs
avc1.4d401f (136) / mp4a.40.2 (140)"

And when i run your program in cmd, i get a lot of information.

​If I find the "audio only" file and the "video only" file that the codec (avc1.4d401f / mp4a.40.2 )matches, and save it together, will it be the same as the original(youtube file)?

Or is it the same as the original if I store the number that says (best) at the bottom?

​The file (best) has the largest capacity, but its "video codec" name is slightly different. 

​The last question is, when you save your program, don't you change(transcoded) or compress it?

(And I know that when you upload to YouTube, the file is automatically transcoded.
It's okay that you've been transcoded once on YouTube.
But I don't want to be transcoded once again when I download mp4 using your program. :) )

Please answer it for me.
Thank you.
And Sorry, for my bad English. :)

__

**Comment by Hrxn** [comment]
> ​If I find the "audio only" file and the "video only" file that the codec (avc1.4d401f / mp4a.40.2 )matches, and save it together, will it be the same as the original(youtube file)?

Yes. If by original you mean what you've just watched in your browser before.

> The last question is, when you save your program, don't you change(transcoded) or compress it?

No, nothing is transcoded by default. Unless you change output format options, or pass other options to ffmpeg etc.

**Comment by realhongkong** [comment]
Thank you for your kind and quick reply.
Among your answers, I don't understand the exact meaning of " pass other options to ffmpeg etc." 
Can you give me an example? I'm so sorry. :)
