### ISSUE TITLE
Twitch-specific output template name - 'game'

### ISSUE THREAD

**Issue by bekarau** [ytdl-org/youtube-dl#21655]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

The output templates include a good number of items to format an output file name by, I'm using updated_date, title and ext currently. But as gaming is the primary focus of Twitch, not being able to extract the 'game' title into the output filename is a gap for this tool.

I've tried going through various output template item names but from what I can tell, none of them currently map to game.

**Comment by dstftw** [comment]
Currently only generic metadata is allowed.
