### ISSUE TITLE
[YouTube] Specific track not working due to change in MPD

### ISSUE THREAD

**Issue by anahc14** [ytdl-org/youtube-dl#21656]
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.07.02**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

youtube-dl.exe -f 136 https://www.youtube.com/watch?v=Ctgn4qvwmCE -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '136', 'https://www.youtube.com/watch?v=Ctgn4qvwmCE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Ctgn4qvwmCE: Downloading webpage
[youtube] Ctgn4qvwmCE: Downloading video info webpage
[youtube] Ctgn4qvwmCE: Downloading MPD manifest
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1562335057/ei/8QIfXe77B8iD1wKjp5mADg/ip/195.76.192.2/id/0ad827e2abf09821/source/youtube/requiressl/yes/playback_host/r3---sn-h5q7dnlk.googlevideo.com/mm/31%2C26/mn/sn-h5q7dnlk%2Csn-25glene7/ms/au%2Conr/mv/m/mvi/2/pl/20/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1091250/mt/1562313342/fvip/3/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Citag/sig/ALgxI2wwRQIhAObJVPxx93R1fZ19lHNu4bPO1M12Wo3s87icmNdoW0AvAiBe-r_Xm_h-lpHZCnoV0loR-ypHgwV_eR4rDS_OyAdJ5g%3D%3D/lsparams/playback_host%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AHylml4wRgIhANE3FGArli28rtuzfb8MkMD2LUDs23-7wnFl0PH4cwU6AiEA0TEu5gK6nlFYs-iwlVmhekDTQdRyuZBy9lasMj37XRw%3D'
[dashsegments] Total fragments: 22
[download] Destination: Join Ericsson on The quest for easy-Ctgn4qvwmCE.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3 (attempt 3 of 10)... 

## Description
We have tried to download the video with an specific track. Its URL is in the verbose.

[info] Available formats for Ctgn4qvwmCE:
format code  extension  resolution note
139          m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
140          m4a        audio only DASH audio  129k , m4a_dash container, mp4a.40.2@128k (44100Hz)
278          webm       256x144    DASH video   95k , webm_dash container, vp9, 25fps, video only
160          mp4        256x144    DASH video  108k , mp4_dash container, avc1.4d400b, 25fps, video only
242          webm       426x240    DASH video  220k , webm_dash container, vp9, 25fps, video only
133          mp4        426x240    DASH video  242k , mp4_dash container, avc1.4d400c, 25fps, video only
243          webm       640x360    DASH video  405k , webm_dash container, vp9, 25fps, video only
134          mp4        640x360    DASH video  635k , mp4_dash container, avc1.4d401e, 25fps, video only
244          webm       854x480    DASH video  752k , webm_dash container, vp9, 25fps, video only
135          mp4        854x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 25fps, video only
247          webm       1280x720   DASH video 1505k , webm_dash container, vp9, 25fps, video only
136          mp4        1280x720   DASH video 2310k , mp4_dash container, avc1.4d4016, 25fps, video only
248          webm       1920x1080  DASH video 2646k , webm_dash container, vp9, 25fps, video only
137          mp4        1920x1080  DASH video 4358k , mp4_dash container, avc1.640028, 25fps, video only
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k, 6.44MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 9.42MiB
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best) 

And we have detected that in f-136 (720 resolution, mp4) we get this:

[youtube] Ctgn4qvwmCE: Downloading webpage
[youtube] Ctgn4qvwmCE: Downloading video info webpage
[youtube] Ctgn4qvwmCE: Downloading MPD manifest
[dashsegments] Total fragments: 22
[download] Destination: Join Ericsson on The quest for easy-Ctgn4qvwmCE.mp4
[download]   9.1% of ~18.21MiB at  7.33MiB/s ETA 00:04   [download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3 (attempt 3 of 10)... 
 
**We think the problem could be related to:** 

```
<Representation id="136" codecs="avc1.4d4016" width="1280" height="720" startWithSAP="1" maxPlayoutRate="1" bandwidth="2310000" frameRate="25">
            <BaseURL>https://r3---sn-h5q7dnlk.googlevideo.com/videoplayback/expire/1562332650/ei/ivkeXbPzGpKH1wbE17DwBg/ip/83.49.165.152/id/0ad827e2abf09821/itag/136/source/yt_otf/requiressl/yes/mm/31,29/mn/sn-h5q7dnlk,sn-h5q7kned/ms/au,rdu/mv/m/mvi/2/pl/16/initcwndbps/1066250/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt/1520263585881423/mt/1562310972/fvip/3/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,mime,otfp,otf,lmt/sig/ALgxI2wwRQIhAPL0Ds-SLmX2OdMTOaRhxEAkg4PqpIWJqE5s40CQwSZhAiARPmO70AQdtsEgSKyPm0Zeys-xFlqK885aaJTGANMq4Q%3D%3D/lsparams/mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AHylml4wRAIgaJSCdoATq31kCY7GxDi1pzy1a9UzTwrheU2pH_drGK0CID2F1yU9tJcm5ixCVoMcUvN2rPere0FO63FRgwU-k9lq/</BaseURL>
            <SegmentList>
               <Initialization sourceURL="sq/0" />
               <SegmentURL media="sq/1/dur/5.120" />
               <SegmentURL media="sq/2/dur/5.120" />
               <SegmentURL media="sq/3/dur/5.120" />
               <SegmentURL media="sq/4/dur/5.120" />
               <SegmentURL media="sq/5/dur/5.120" />
               <SegmentURL media="sq/6/dur/5.120" />
               <SegmentURL media="sq/7/dur/5.120" />
               <SegmentURL media="sq/8/dur/5.120" />
               <SegmentURL media="sq/9/dur/5.120" />
               <SegmentURL media="sq/10/dur/5.120" />
               <SegmentURL media="sq/11/dur/5.120" />
               <SegmentURL media="sq/12/dur/5.120" />
               <SegmentURL media="sq/13/dur/5.120" />
               <SegmentURL media="sq/14/dur/5.120" />
               <SegmentURL media="sq/15/dur/5.120" />
               <SegmentURL media="sq/16/dur/5.120" />
               <SegmentURL media="sq/17/dur/5.120" />
               <SegmentURL media="sq/18/dur/5.120" />
               <SegmentURL media="sq/19/dur/5.120" />
               <SegmentURL media="sq/20/dur/5.120" />
               <SegmentURL media="sq/21/dur/1.960" />
            </SegmentList>
         </Representation> 
```
 

That this time (in 720 resolution), we get the SegmentURL in seconds instead of ranges, as it is in the rest of cases.

**Comment by dstftw** [comment]
Server side youtube error.
