### ISSUE TITLE
I would like to ask you one thing "m4a" "youtube-dl"

### ISSUE THREAD

**Issue by realhongkong** [ytdl-org/youtube-dl#21661]
## Checklist

- [ ✓ ] I'm asking a question
- [ ✓] I've looked through the README and FAQ for similar questions
- [ ✓] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hello everyone! 
I would like to ask you one thing. 
I only want the audio file from the youtube video and I was wondering this "m4a audio only Dash audio" is the Youtube video's original audio file?
( I know that when you upload to YouTube, the file is automatically transcoded.)
If I choose and save "m4a", does it become to be transcoded once again? 

​

**Comment by dstftw** [comment]
No, it does not.

**Comment by realhongkong** [comment]
You meant Youtube video's original audio file?

**Comment by ealgase** [comment]
It's the file as YouTube serves it, so it's only been transcoded once (when originally uploaded to YouTube)
