### ISSUE TITLE
[mytvsuper] Site support request for free videos

### ISSUE THREAD

**Issue by ProgrammerAKL** [ytdl-org/youtube-dl#21663]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Playlist: https://programme.mytvsuper.com/tc/104823/y-angle
- Playlist: https://programme.mytvsuper.com/en/104823/y-angle-2019

## Description

These videos can definitely be played by creating a free account; no payment is required. There may be a geo-restriction (Hong Kong) at some stage of the process, but I do not know whether the URL of the manifest would actually be geo-restricted or not.

**Comment by dstftw** [comment]
For any work on this you must provide:
1. account credentials
2. working proxy/VPN
