### ISSUE TITLE
Autonumber-start in conjunction with -o "%(title)s.%(ext)s".

### ISSUE THREAD

**Issue by blackoutworm** [ytdl-org/youtube-dl#21670]
Hi there. I want the playlist of files to be numbered from 01 and up.
But using it in conjunction with -o "%(title)s.%(ext)s" doesn't work.
I have consulted the manuals and googled around, but haven't been able to fix this.
Am I missing something or is this a bug or something?
Here's my entire command. Please see if there are any errors in here.
youtube-dl --no-post-overwrites -o "%(title)s.%(ext)s" --ignore-errors -f best --playlist-start 51 --autonumber-start "01" "URL".

**Comment by dstftw** [comment]
I've already been answered to use autonumber in output template itself.

**Comment by blackoutworm** [comment]
What does that even mean?
I asked yesterday but you sent a link to the commands.
So what exactly am I suppose to do?

**Comment by blackoutworm** [comment]
How do I use autonumber in template?

**Comment by dstftw** [comment]
Bother to read the link.
