### ISSUE TITLE
Codec selection

### ISSUE THREAD

**Issue by Mikolaj98p** [ytdl-org/youtube-dl#21674]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How I can select witch codec video will be downloaded?

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#format-selection

**Comment by Mikolaj98p** [comment]
I mean automated. One video has `298` for best video mp4, 2'nd - `136`

**Comment by dstftw** [comment]
Bother to read URL linked.
