### ISSUE TITLE
Async ytsearch5

### ISSUE THREAD

**Issue by nadal28** [ytdl-org/youtube-dl#21671]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, I would like to know if is possible to make `youtube-dl ytsearch5:"searchQuery" --get-id` to run in async manner because I only want an info list about those videos(no ffmpeg).
For now, it takes up to 7 seconds to retrieve info about 5 videos instead of to do 5 simultaneous request.

Thanks in advance

**Comment by dstftw** [comment]
`--get-id` will not run any ffmpeg or download anything apart from metadata. If you want to run it async (whatever that means for your) then it's your responsibility to do so. It won't make it any fasted though.

**Comment by nadal28** [comment]
@dstftw Hello, thanks for your response.
Look at the following: https://i.imgur.com/YggOeJo.jpg
Im searching 3 videos, but it takes too much time. Why? Because the script goes video by video scrapping them, instead of scrape the three at the same time.
Imagine about try to get 10 videos..., any solution on this?
