### ISSUE TITLE
Trying to embed video statistics to meta-data

### ISSUE THREAD

**Issue by JavonLegend** [ytdl-org/youtube-dl#21688]
Good Day,

I want to know if its possible to write basic youtube video info like view count, likes, dislikes and uploader to a video's meta-data when converting it from mp4 to mkv..

I've searched and couldn't find much info on the post processors command list,

Any help will be useful

**Comment by dstftw** [comment]
Not possible.

**Comment by JavonLegend** [comment]
@dstftw Thanks for replying though :)
