### ISSUE TITLE
To download multi-part videos from Bilibili

### ISSUE THREAD

**Issue by hit-1160300227** [ytdl-org/youtube-dl#21686]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

When I use youtube-dl to download videos that consists of multi-part videos on bilibili , it only downloads the first video repeatedly.
Just like "https://www.bilibili.com/video/av55175398/?p=2",  the "?p=<page_id>" param are just ignored and this tool can only download the video corresponds to "?p=1".
I think we can add a playlist extractor.And make some changes to the function _real_extract in bilibili.py. But I am not sure if it works.

**Comment by someziggyman** [comment]
Hey guys, not sure if I understand correctly. please help. So this fix has already been merged and can be used in youtube-dl latest build right?
The reason I'm asking is: the other day I tried to download this Kpop concert with 2 parts:
1) https://www.bilibili.com/video/av57748844?p=1
2) https://www.bilibili.com/video/av57748844?p=2

However, youtube-dl returns the same video for both links:
format code  extension  resolution note
0            flv        unknown    1.46GiB

Am I doing something wrong?
