### ISSUE TITLE
Openload doesn't work

### ISSUE THREAD

**Issue by Jan-NiklasB** [ytdl-org/youtube-dl#21683]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x]   (Do all seem to be incomplete) I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose https://oload.site/embed/_NJqDjE4GGM/Futurama.S06E16.Ghost.in.the.Machines.720p.BluRay.DD5.1.x264-CtrlHD.mkv
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://oload.site/embed/_NJqDjE4GGM/Futurama.S06E16.Ghost.in.the.Machines.720p.BluRay.DD5.1.x264-CtrlHD.mkv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-38-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: avconv 3.4.6, avprobe 3.4.6, ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1
[debug] Proxy map: {}
[Openload] _NJqDjE4GGM: Downloading embed webpage
[Openload] _NJqDjE4GGM: Executing JS on webpage
ERROR: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/openload.py", line 429, in _real_extract
    'stream URL')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I extracted the used URL from another Side.
Using the URL i get to the Video directly on openLoad.
On May 6th it still worked this way.

**Comment by Jan-NiklasB** [comment]
Any Idea where the Problem could be?
The error still is there on my PC.
Only thing I changed since last time it worked is that I updated my OS from LM 18.3 to LM 19

**Comment by tmczar** [comment]
This problem exists for others too. I've got Ubuntu 18, and exactly the same problem. (my issue was also closed as "can't reproduce" too.)

**Comment by Jan-NiklasB** [comment]
@dstftw could it be a problem regarding only Ubuntu based operating Systems?
Which OS hace you used for trying to reproduce this problem

**Comment by tmczar** [comment]
@dstftw  Problem seems to be connected with Ubuntu version of user. I've checked problem on several machines with fresh installs of youtube-dl with following results:
Ubuntu 18: does not work (checked two times, once on fresh install of Ubuntu with only phantomjs and youtube-dl installed)
Mint 18: works perfectly (please note, that Mint 18 is based on Ubuntu 16, while Mint 19 which @Jan-NiklasB uses is based on Ubuntu 18 and does not work)
These results strongly suggest, that something on Ubuntu 18 creates conflict with youtube-dl on openload.

**Comment by dstftw** [comment]
This has nothing to do with OS as OP clearly states it worked before. Most likely your are just banned.

**Comment by tmczar** [comment]
@dstftw  Geez. OP clearly states: "I updated my OS from LM 18.3 to LM 19".
Also, half of test was done on one machine: Linux Mint (LM) 18 was working, and then i've used Live version of Ubuntu 18, installed phantomjs and downloaded fresh youtube-dl, and it was not working, so it is no ban.
I will say this again: OP had system based on Ubuntu 16, and youtube-dl was working. Then he updated system to the one based on Ubuntu 18 and it broke.
I've checked this lead, and got results showing, that everything is ok on Ubuntu 16, but "just does not work" on Ubuntu 18.
This problem is easily reproducible: just stick Ubuntu 18 Live USB to the comp, and try to use youtube-dl to download something from openload - You will get the same errors as us.

**Comment by bitraid** [comment]
```
$ uname -a && youtube-dl -v 'https://oload.site/embed/_NJqDjE4GGM/Futurama.S06E16.Ghost.in.the.Machines.720p.BluRay.DD5.1.x264-CtrlHD.mkv'
Linux ubuntu 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://oload.site/embed/_NJqDjE4GGM/Futurama.S06E16.Ghost.in.the.Machines.720p.BluRay.DD5.1.x264-CtrlHD.mkv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.27
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.18.0-15-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[Openload] _NJqDjE4GGM: Downloading embed webpage
[Openload] _NJqDjE4GGM: Executing JS on webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://oload.site/stream/_NJqDjE4GGM~1562954300~2a02:587::~vgrHJCE8?mime=true'
[download] Destination: Futurama.S06E16.Ghost.in.the.Machines.720p.BluRay.DD5.1.x264-CtrlHD.mkv.mp4-_NJqDjE4GGM.mp4
[download]   1.8% of 218.17MiB at  4.06MiB/s ETA 00:52^C
ERROR: Interrupted by user
```
Can you play the video in the browser?

**Comment by tmczar** [comment]
Yes, there is no problem with playing video on the browser.
youtube-dl is installed by directly downloading.
```
$ uname -a & youtube-dl --verbose https://oload.site/embed/_NJqDjE4GGM/Futurama.S06E16.Ghost.in.the.Machines.720p.BluRay.DD5.1.x264-CtrlHD.mkv
[1] 8128
Linux navita 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://oload.site/embed/_NJqDjE4GGM/Futurama.S06E16.Ghost.in.the.Machines.720p.BluRay.DD5.1.x264-CtrlHD.mkv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-54-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1
[debug] Proxy map: {}
[Openload] _NJqDjE4GGM: Downloading embed webpage
[Openload] _NJqDjE4GGM: Executing JS on webpage
ERROR: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/openload.py", line 429, in _real_extract
    'stream URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Jan-NiklasB** [comment]
Well, as mentioned by @tmczar and @bitraid youtube-dl was installed by download and updated by command -U to the newest available version.
The link works perfectly in Firefox but isn't downloadable in yt-dl

This is the output with the exactly same command as used by @bitraid:

`uname -a && youtube-dl -v 'https://oload.site/embed/_NJqDjE4GGM/Futurama.S06E16.Ghost.in.the.Machines.720p.BluRay.DD5.1.x264-CtrlHD.mkv'
Linux Kein-PC 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://oload.site/embed/_NJqDjE4GGM/Futurama.S06E16.Ghost.in.the.Machines.720p.BluRay.DD5.1.x264-CtrlHD.mkv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-38-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: avconv 3.4.6, avprobe 3.4.6, ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1
[debug] Proxy map: {}
[Openload] _NJqDjE4GGM: Downloading embed webpage
[Openload] _NJqDjE4GGM: Executing JS on webpage
ERROR: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/openload.py", line 429, in _real_extract
    'stream URL')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`
