### ISSUE TITLE
FORK OF THE VIDEO

### ISSUE THREAD

**Issue by username1565** [ytdl-org/youtube-dl#21682]
## Checklist

- [x] I'm reporting a feature request
- [ ] I've verified that I'm running youtube-dl version **2019.07.02**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

Can you add the ability TO MAKE THE FORK OF THE VIDEO on youtube, in the future?
This can correlate with copyright, but if author of the video not want to block all videos, this can have diverse authors.

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient
