### ISSUE TITLE
Post gpg signing keys on GitHub or homepage? OpenPGP sks keyserver system is fatally flawed.

### ISSUE THREAD

**Issue by EauBureau** [ytdl-org/youtube-dl#21689]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

The OpenPGP sks keyserver system is broken.[1,2] Could you post copies of your signing keys here on GitHub or on the homepage as a workaround? Perhaps you could also start signing with OpenBSD's signify or minisign too?[3,4,5]

Thank you.

Thanks for youtube-dl too. It's indispensable :thumbsup:

[1] https://news.ycombinator.com/item?id=20312826
[2] https://news.ycombinator.com/item?id=20370385
[3] https://blog.gtank.cc/modern-alternatives-to-pgp/
[4] https://github.com/aperezdc/signify
[5] https://jedisct1.github.io/minisign/

**Comment by EauBureau** [comment]
No opinions on this?

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl/issues/19199#issuecomment-462598681

**Comment by EauBureau** [comment]
Thanks for that.
Any chance you could put those two links on the [official download page](https://ytdl-org.github.io/youtube-dl/download.html) or  on the README.md on the [official GitHub page?](https://github.com/ytdl-org/youtube-dl)
Save others having to fumble around for them.
