### ISSUE TITLE
Flagged duplicated Issue close, however, it was not, since the original report was removed.

### ISSUE THREAD

**Issue by jppoa** [ytdl-org/youtube-dl#21697]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have reported a bug. and it was removed from issues (Issue #21628), I then reopen today "Fix Extractor sxyprn.com and biqle.ru" (Issue #21696), it was marked as duplicated and closed.
However, the problem persists and I was not able to find any other OPEN issue dealing with the problem. I would then ask for the reopen of the Issue #21696, if possible.

**Comment by bitraid** [comment]
What about #21645 and #21364 ?
