### ISSUE TITLE
[Yahoo! Japan News] Support Request

### ISSUE THREAD

**Issue by kylepw** [ytdl-org/youtube-dl#21698]
## Checklist

- [ x ] I'm reporting a new site support request
- [ x ] I've verified that I'm running youtube-dl version **2019.07.14**
- [ x ] I've checked that all provided URLs are alive and playable in a browser
- [ x ] I've checked that none of provided URLs violate any copyrights
- [ x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Playlist: https://news.yahoo.co.jp
- Playlist: https://headlines.yahoo.co.jp/videonews/
- Single video: https://headlines.yahoo.co.jp/videonews/fnn?a=20190719-00421051-fnn-soci

## Description

I'd like to request support for Yahoo Japan News. Full support should be covered in PR #21265   which was checked but not yet merged.

**Comment by kylepw** [comment]
@dstftw @remitamine This should be solved with PR #21265. Could you please check/merge this PR? Thank you.

**Comment by kylepw** [comment]
@dstftw @remitamine PR #21265 resolves this issue. Could you please check/merge? Thank you.

**Comment by dstftw** [comment]
Stop bumping this over and over again. This will be checked when someone will have time to do so.
