### ISSUE TITLE
I want to use threading app youtube-dl?

### ISSUE THREAD

**Issue by vonyrhatoe** [ytdl-org/youtube-dl#21716]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

I use code php on my site this code is here [LINK](https://medium.com/@saqibrazzaq/how-to-play-youtube-videos-in-html5-player-with-youtube-dl-and-php-on-linux-962158a74011)

but when the python high traffic uses the most CPU 100% before proceeding to YouTube-DL which causes high CPU and error pages.
can the youtube-dl application be used with threading python?
and what is the code so that I can apply it?

can anyone help me?

**Comment by dstftw** [comment]
Threading won't make any difference since web server already processes requests in parallel that's what actually causes high load on high traffic.
