### ISSUE TITLE
Search only for "Artist - Topic"-like channels on ytsearch

### ISSUE THREAD

**Issue by lordvico** [ytdl-org/youtube-dl#21722]
Related or not to my previous question, Youtube began to upload high-quality music in channels similar [to this one](https://www.youtube.com/channel/UCq1zzbah4_59USxpkSxc43w), named like this: `Artist name - Topic`. I assume its for Youtube Music.

Is possible to make `ytsearch` to only search for videos uploaded in these channels?

Thanks a lot!

**Comment by remitamine** [comment]
read the decumentation.

**Comment by lordvico** [comment]
Where's the documentation? The link on official website just redirect to the Readme of this repository which is just `youtube-dl --help` with fancy markdown formatting.

**Comment by remitamine** [comment]
> Where's the documentation? The link on official website just redirect to the Readme of this repository which is just `youtube-dl --help` with fancy markdown formatting.

- no, it's not.
- the answer is actually there in [OPTIONS](https://github.com/ytdl-org/youtube-dl#options) section.

**Comment by lordvico** [comment]
`--default-search`?

**Comment by remitamine** [comment]
not, at all.
simply it's not possible, and you would've been able to know that if you looked at [Video Selection Options](https://github.com/ytdl-org/youtube-dl#video-selection) and in particular `--match-filter` option.
there is already a feature request for wildcard filtering of video metadata.
it would be better next time to actually fill the issue template properly, read the documentation and search for similar issues before submitting an issue.

**Comment by lordvico** [comment]
Okay, but you dont need to be such a dick. Anyway thanks for point me to `--match-filter` option
