### ISSUE TITLE
Does --skip-unavailable-fragments finalize the video?

### ISSUE THREAD

**Issue by altimumdelta** [ytdl-org/youtube-dl#21720]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Does it just skip on any error like 404 or 503 and finalized the download with the available fragments or not?

**Comment by dstftw** [comment]
What do you mean by finalize in the first place?

**Comment by altimumdelta** [comment]
To mux/merge and save the video as downloaded and treat it as if it's complete, sorry I'm doing this in the context of an archive, not for a one off download.

**Comment by dstftw** [comment]
It will skip unavailable fragments and output video with only downloaded fragments. Also such skipped fragments are unlikely to be available on the next run since each fragment is retried by default before being skipped.
It's also not possible to continue on the next run since fragments are not stored individually but joined immediately for saving disk storage.

**Comment by altimumdelta** [comment]
Well ... fififurfufi ... this means over ~20% of all my videos maybe be more or less broken and unplayable in some cases if the fragment missing was the file header ?

This should be dealth with immediately, this means all my 1TB archives are quite a bit less useful if everytime there were unavailable fragments the video was labeled as "100% complete". The sheer number of videos means it would be extremely tedious to go and check each video one by one, it would help if I saved all the logs correctly which I didn't since I was simultaneously learning about youtube dl and improving my scripts, only now a few days ago I got up to that point.

There really should be some kind of verification ability to verify the integrity, redownload the ones with missing fragments, my skills are limited but I'm willing to do something if I can to help with this.

**Comment by altimumdelta** [comment]
I just noticed stoping and restarting suppose to continue but I see some .part files being left over and the file seems to be completely skipped, some kind of timing coincidence has written the file into the download log as "finished" and the program doesn't seem to check the extension is still .part ... oh 

I also was suspicious why the heck is ffmpeg remuxing the videos so long to mkv, the ones which aren't fragmented to Audio and Video, the debug line does not show -acodec copy and vcodec copy options which means it's using default values for, that's a critical issue right there, it's re-coding the whole video which is complete nonsense, sorry I'm being a bit fuming now that I have to start from scratch but I guess I can just suck it up and treat it as "training" or "experience", I should have figured out this before, should have paid attention to the messaging more.

This is some heavily unwelcome and unrealiable behavior across the board and is not compatible with the whole point of creating an archive, I'm basically having to stop everything until it's solved, I'll take a look at the code myself even.

I guess with what I meant "finalize" is the point it writes the URL to the download logfile, that's where it treats it as already downloaded, it does seem to check files, and I even noticed a clever trick to make it recode the videos to a custom container by deleting the download log it will start downloading each, find it already exists by filename and will just recode it without downloading, that's good behavior, but it should be proper to make an option in the config rather than such a hidden trick.

I think I spoke about the recode-video option name context before, I think I didn't realize at the time it wasn't remuxing, or I completely forgot and kept using the command because I have quite a lot of scripts and sometimes I do get lost and forget as I keep updating the overall default template that is used by all of them.

**Comment by altimumdelta** [comment]
I was able to tweak together a solution, it will abort on all errors, won't recode, will overwrite, and put it all into a Windows Task so it starts every 5 minutes but doesn't make a new instance if it exists, so after the batch craps out it will restart it, but in such a case where a particular video will simply not work for many many hours the solution isn't practical enough still, it keeps retrying and retrying and now it gets more complicated trying to skip this individual video adding a filter but most importantly requiring human intervention to make that filter so I have to again come back and keep checking if it stalled or not. But okay I'm just wishing for this convenience, although  the time/effort spent on this stuff is well worth it in the end anyway.

**Comment by altimumdelta** [comment]
I might put up a separate proper feature requests for these points, some already are, and I understand that normally archive-mode isn't used but in that case it would be more welcome to do things for reliability/backup/failsafe rather than storage space, if people prefer storage space over broken video than that I guess is their right to think so, I apologize for steaming out a bit, I got over it, adjusted my scripts for good and even tho I have to check every 2 hours to add new filters, it does manage to do the job right for now, but I don't want to say this is it and it's solved, the whole point of such a program is to be able to manage the whole thing by it self, without major external tricks, right.

All those are great but all I would need is simply a "deferr download", it's unavailable, it's error, skip it don't abort and continue but don't mark it as downloaded, there's no issue with having to restart the script, the issue is that when a video or fragment-s are unavailable they're unavailable a really long time, a day or two, which means the script just loops on the same video.

So I have to keep adding --match-filter "id != 'URL_ID' & id != etc etc" - But I'm just glad it at least works as a workaround.
