### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by zapetin52** [ytdl-org/youtube-dl#21728]
Hi i am trying to download a youtube video, but show these:

**ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError());**

Using a VDS, 
my Python Code:
ydl_opts = {'format': 'best',"verbose": False,"quiet": False,"forcefilename": True,'restrictfilenames':True}

 with youtube_dl.YoutubeDL(ydl_opts) as ydl: ydl.download([idYtb]);

But is not working. 
Please help me. thnks

**Comment by TaktakTaktouk** [comment]
it seems that you have been banned by youtube

**Comment by zapetin52** [comment]
@TaktakTaktouk perhaps. Could you help me? do you know any solution?

**Comment by TaktakTaktouk** [comment]
Your IP address was banned permanently by YouTube. You need to renew it or use `--source-address`
