### ISSUE TITLE
audio metadata issue

### ISSUE THREAD

**Issue by poe81** [ytdl-org/youtube-dl#21725]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Hello everyone,

I was hoping i could get help with wv downloader

I keep getting this error:

ERROR - client - Could not find audio metadata
ERROR - client - cannot auto select audio language

How can i fix this?

Thank you

**Comment by poe81** [comment]
Wait this is closed?

**Comment by poe81** [comment]
why?

**Comment by remitamine** [comment]
this is an issue tracker for `youtube-dl`, not `WV Downloader`.
