### ISSUE TITLE
youtube url with youtube-dl not work

### ISSUE THREAD

**Issue by ilpadrinovl** [ytdl-org/youtube-dl#21730]
hi,if i put the url of youtube with youtube-dl i have this error:

You will get:

HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug .

how i can fix?

**Comment by Hrxn** [comment]
@dstftw 

Suggestion: Put the "please report this issue on .." error message behind a conditional, in cases for HTTP errors like `429, 404` etc.

**Comment by dstftw** [comment]
No. It's impossible to know what's the reason of such errors, server side issues or it's just a site/API redesign so that youtube-dl requests nonexistant/non-anymore-working endpoints.

**Comment by ilpadrinovl** [comment]
and for you impossible to fix?

**Comment by dstftw** [comment]
Fix what? There are no problems on youtube-dl side. You are banned by Youtube.
