### ISSUE TITLE
get direct download links for merged videos

### ISSUE THREAD

**Issue by ganeendra** [ytdl-org/youtube-dl#21738]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Hi,

can i know is there anyway for me to generate a direct download link for merged videos  (video + audio )?  I already know there is a mereged video available with best quality but I need to know is there anyway for me to select video and audio format and get url for that in order for me to stream it. 

youtube-dl -f 255+160 URL 

following code will merge the video + audio but it generates file not a stream url. I need know is there anyway for me to get a stream link without creating a temp file while merging 

Thanks

**Comment by dstftw** [comment]
Youtube does not store merged videos.

**Comment by ganeendra** [comment]
Thanks for your reply 

Okay but how does youtube-dl generates a best merged video ? I just need to know is there anyway for me to do that by myself? 

Thanks

**Comment by dstftw** [comment]
By muxing video and audio with ffmpeg.

**Comment by ganeendra** [comment]
Thanks. 

Could you please provide me a sample code ?  I mean how does it output a link after merging with ffmpeg. ?

Thanks in adavance

**Comment by dstftw** [comment]
Again: it **does not output link**. Files are muxed on your local filesystem.
