### ISSUE TITLE
Exclude all adult sites by default

### ISSUE THREAD

**Issue by aurora-of-earth** [ytdl-org/youtube-dl#21739]
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.07.02**
- [x ] I've searched the bugtracker for similar feature requests including closed ones

## Description

- Move all adult site extractors to a separate folder.
- Make them not available by default and available only with something like a cli flag(e.g. --include-adult) or a boolean config <pre>allowAdult=true</pre>

That's the least of what that can be done.
If you want I'll do it, but I'm not so hopeful you'd accept the PR.

**Comment by dstftw** [comment]
No.

**Comment by aurora-of-earth** [comment]
@dstftw Are you the project owner?
Why don't you do that?

**Comment by dstftw** [comment]
This is useless since separating extractors is not enough for complete and reliable adult content isolation.
