### ISSUE TITLE
Error 429 too many requests

### ISSUE THREAD

**Issue by farazpartoei** [ytdl-org/youtube-dl#21742]
this issue may be duplicated but I have been using youtube-dl for 2 years and this issue started to happen from yesterday
is there any new restriction from google side 
or does anyone have the same issue here which occurred recently?

**Comment by nikooo777** [comment]
Youtube has implemented a new throttling feature: https://torrentfreak.com/youtube-blocks-popular-mp3-stream-ripping-sites-190710/

I'm so mad.... if anyone has more details regarding this they're more than welcome!

What I gathered so far:

IPv4 IPs are banned after some time, depending how intensely they're used.
IPv6 IPs are banned in chuncks (they throttle the whole /64 subnet!)
