### ISSUE TITLE
How to read error using ydl.extract_info?

### ISSUE THREAD

**Issue by mitguru007** [ytdl-org/youtube-dl#21747]
Hello!
  How to read error message with bellow code? 

>  ydl = YoutubeDL()
    info  = ydl.extract_info(url, download=False)
    jsondata = json.dumps(info)

Please help, Thank you,

**Comment by dstftw** [comment]
Catch exceptions.

**Comment by mitguru007** [comment]
thank you bro. Can you please give the code. i am new in python.
