### ISSUE TITLE
Broken download link

### ISSUE THREAD

**Issue by sanyarnd** [ytdl-org/youtube-dl#21755]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
Youtube-dl download link for the latest 2019.07.02 is broken, e.g:
https://github.com/ytdl-org/youtube-dl/releases/download/2019.07.02/youtube-dl.exe

**Comment by remitamine** [comment]
latest version is 2019.07.12.

**Comment by sanyarnd** [comment]
@remitamine 
it's returned in [version.json](https://rg3.github.io/youtube-dl/update/versions.json):
![image](https://user-images.githubusercontent.com/6544384/61137505-4cc97480-a4ce-11e9-855b-f653c94a0289.png)
![image](https://user-images.githubusercontent.com/6544384/61137533-5521af80-a4ce-11e9-85d0-184e260c6545.png)

**Comment by remitamine** [comment]
youtube-dl moved to `ytdl-org` organization, you should use the new domain:
https://ytdl-org.github.io/youtube-dl/update/versions.json
