### ISSUE TITLE
Support for Shudder

### ISSUE THREAD

**Issue by VinCubed** [ytdl-org/youtube-dl#21757]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.07.12**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.shudder.com/play/4834871
- Single video: https://www.shudder.com/play/4834872

## Description

WRITE DESCRIPTION HERE
Will email credentials if needed

**Comment by Flowdeeps** [comment]
Would love to see support for this so I could drag stuff down for when I'm flying

**Comment by OverlordQ** [comment]
Shudder uses PlayReady or FairPlay, so it's DRM'd.

**Comment by VinCubed** [comment]
OK, I'd incorrectly assumed many of the other items supported also had some form of DRM. Thanks for responding.
