### ISSUE TITLE
Error : Video not available

### ISSUE THREAD

**Issue by Elite** [ytdl-org/youtube-dl#21753]
- [ X] I'm reporting a broken site support issue
- [X ] I've verified that I'm running youtube-dl version **2019.07.12**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

## Verbose log
```
youtube-dl -v -F https://www.youtube.com/watch?v=PMYLjbUz34w&feature=youtu.be
[1] 1082
root@IS-52763:~# [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.youtube.com/watch?v=PMYLjbUz34w']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.12
[debug] Python version 2.7.9 (CPython) - Linux-3.16.0-6-amd64-x86_64-with-debian-8.6
[debug] exe versions: ffmpeg N-82067-g4d92bd3-static, ffprobe N-82067-g4d92bd3-static
[debug] Proxy map: {}
[youtube] PMYLjbUz34w: Downloading webpage
[youtube] PMYLjbUz34w: Downloading video info webpage
ERROR: This video is not available.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 2097, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is not available.

```

## Description
Get `ExtractorError: This video is not available.` on many videos like the one above. Works absolutely fine in a browser.

EDIT: Well it works on my personal PC but not on my server. If a video is Geo-restricted I usually get a relevant `youtube-dl` error stating the same!!!

**Comment by Elite** [comment]
@dstftw Can you pls tell why would this be invalid. I have edited the issue with my findings.

EDIT: Well it works on my personal PC but not on my server. If a video is Geo-restricted I usually get a relevant youtube-dl error stating the same!!!

EDIT2: https://polsy.org.uk/stuff/ytrestrict.cgi?ytid=PMYLjbUz34w shows my server country to be valid for this video.

**Comment by dstftw** [comment]
The error is self-explanatory. If you open it in browser from the same network interface you'll get the same error.
