### ISSUE TITLE
Can we chain proxys ?

### ISSUE THREAD

**Issue by randinfo** [ytdl-org/youtube-dl#21751]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Can we chain proxys like this --proxy http://xxx --proxy http://yyy ?

**Comment by dstftw** [comment]
You can only use one proxy.

**Comment by randinfo** [comment]
How can i achieve that ? any idea ?
