### ISSUE TITLE
Problem With Live Transmission in Y

### ISSUE THREAD

**Issue by catalan63** [ytdl-org/youtube-dl#21762]
## Checklist

- [* ] I'm reporting a broken site support
- [ *] I've verified that I'm running youtube-dl version **2019.07.12**
- [ *] I've checked that all provided URLs are alive and playable in a browser
- [ *] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
build@MSS-ONE:~/MSS-ONE/temp$ youtube-dl https://www.youtube.com/watch?v=KTJXlMn                                                                                                                                A1c0 video.mp4
[youtube] KTJXlMnA1c0: Downloading webpage
[youtube] KTJXlMnA1c0: Downloading video info webpage
[youtube] KTJXlMnA1c0: Downloading MPD manifest
[download] Destination: DW - Deutsche Welle Live TV  (Deutsch)-KTJXlMnA1c0.f136.                                                                                                                                mp4
[download]  93.0% of 274.19KiB at 405.98KiB/s ETA 00:00^C
ERROR: Interrupted by user
build@MSS-ONE:~/MSS-ONE/temp$ youtube-dl -v https://www.youtube.com/watch?v=KTJX                                                                                                                                lMnA1c0 video.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=KTJXlMnA1c0                                                                                                                                ', u'video.mp4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.12
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-54-generic-x86_64-with-U                                                                                                                                buntu-18.04-bionic
[debug] exe versions: ffmpeg N-94166-g9269bccbb3, ffprobe N-94166-g9269bccbb3
[debug] Proxy map: {}
[youtube] KTJXlMnA1c0: Downloading webpage
[youtube] KTJXlMnA1c0: Downloading video info webpage
[youtube] KTJXlMnA1c0: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r4---sn-p5qs7n7s.googlevideo.com/videop                                                                                                                                layback?expire=1562991091&ei=kwUpXYyLHsW4gwPl0bOgAw&ip=158.50.77.241&id=KTJXlMnA                                                                                                                                1c0.0&itag=136&aitags=133%2C134%2C135%2C136%2C160&source=yt_live_broadcast&requi                                                                                                                                ressl=yes&mm=44%2C26&mn=sn-p5qs7n7s%2Csn-vgqsenl7&ms=lva%2Conr&mv=m&mvi=3&pl=20&                                                                                                                                initcwndbps=313750&live=1&hang=1&noclen=1&mime=video%2Fmp4&gir=yes&mt=1562969371                                                                                                                                &fvip=5&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Cre                                                                                                                                quiressl%2Clive%2Chang%2Cnoclen%2Cmime%2Cgir&sig=ALgxI2wwRAIge9et2E13C3D0cKJI3E5                                                                                                                                pfJOozOCNDKsWl4bPzqnSRgECIGPIBpsDJEsmMK_Zkc7aYs75HblB_1EIRIww6bjjkehX&lsparams=m                                                                                                                                m%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgDubMI9CLn6UuxX_MkbKJ4                                                                                                                                xpfG4F4uISdIC2JodkLVRsCIQCTR4fK_qSeWKQp4POQoM2iuLllz8vCa3mlXUHxeTBFcw%3D%3D&rate                                                                                                                                bypass=yes'
[download] Resuming download at byte 261120
[download] Destination: DW - Deutsche Welle Live TV  (Deutsch)-KTJXlMnA1c0.f136.                                                                                                                                mp4
[download]  71.8% of 710.56KiB at 406.04KiB/s ETA 00:00youtube-dl ht

## Description

WRITE DESCRIPTION HERE

Hello people, about one week You.tube change the workflow of live transmission. 
In the past i get the video with FFMPEG and i get the HLS Links with Youtube-DL doing 

youtube-dl -F youtube-link
youtube-dl -f 96 -g youtube-link

but right now, when i make the -F to list the option i see that the video is separated from the video, is not a big problem, because if we get correct links for video and audio we can use the option map in FFmpeg. But the problem is we can get the correct links, whe i get a link and put it to download it download a small fragment of the video and stop.

In the -F it shows is downloading a MPD manifest and something saying DASH and i read somewhere that is from Mpeg Dash protocol.

Is the new toy of youtube is dash FFmpeg has a DASH demuxer, but we need the MPD link of the video.

Yesterday a Youtube-dl developper close the report of another user and marked as solved, i update the youtube-dl that is in my Ubuntu and put youtube-dl dirctly to download the video, and it stop after few seconds of video, so it make me think is only a frament.

Today morning i tested streamlink and is working, but it says is downloading from a HLS Link, i dont know what or where but is working, the problem they have not much options to configure, because i need to save the viedeo in HLS and it can only save the video in mp4, and they dont have an option to share link where they are getting the video (i know if i read the source code i can do, but i am not a developper yet, i am start studyng and is hard to me).

So, i cant save the live feeds in youtube with youtube-dl and i cant get the necessary information to make that with FFMPEG. I only can do with streamlink, but i am working on a project to put youtube on a SDI card, and if i make with streamlink i need to make three process, one to create the mp4, another to create the HLS and another to put the video on the SDI.

If youtube create a way to get the links of the MPD like we do with the HLS channels i think is great (if the problem is that).

Thanks in advance Youtube-DL team.

**Comment by catalan63** [comment]
Where OS duplicated?

**Comment by remitamine** [comment]
> I've searched the bugtracker for similar issues including **closed ones**

**Comment by catalan63** [comment]
But if you have a solution you can share with us what it was? In The git version we can get The MPD links?

**Comment by catalan63** [comment]
Did you update The documentación?

**Comment by catalan63** [comment]
There was two updates of The software in The pip repository since yesterday,  is The git version fully functional? If it is i can take time how The compilation is,  if its not i preffer to wait,  but all this information is useful

**Comment by remitamine** [comment]
> But if you have a solution you can share with us what it was?

https://github.com/ytdl-org/youtube-dl/commit/27019dbb4b4829b5e1910c6b714f904ce8fad680
> In The git version we can get The MPD links?

no, you will get HLS links.
> There was two updates of The software in The pip repository since yesterday

the fix has been committed a few hours after 2019.07.12 release.
> The git version fully functional?

yes, it is.
