### ISSUE TITLE
[YouTube Live] Cannot get m3u8 link

### ISSUE THREAD

**Issue by bagdenisov** [ytdl-org/youtube-dl#21770]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.12**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

>youtube-dl -v https://www.youtube.com/channel/UCiUiZUDSpuiMiiecRBEOZEQ/live -g
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/channel/UCiUiZUDSpuiMiiecRBEOZEQ/live', '-g']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.07.12
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-93506-g27c94c57dc, ffprobe N-93506-g27c94c57dc
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
https://r1---sn-c5niuxaxjvh-045l.googlevideo.com/videoplayback?expire=1563040663&ei=N8cpXce_Bou_7QTJ0LKgAg&ip=[my_ip]&id=4C1GqHm3xJc.1&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160&source=yt_live_broadcast&requiressl=yes&mm=44%2C29&mn=sn-c5niuxaxjvh-045l%2Csn-n8v7znsy&ms=lva%2Crdu&mv=m&mvi=0&pl=17&initcwndbps=585000&live=1&hang=1&noclen=1&mime=video%2Fmp4&gir=yes&mt=1563018984&fvip=18&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Clive%2Chang%2Cnoclen%2Cmime%2Cgir&sig=ALgxI2wwRgIhANaiH5217OKcb1iHxY29C-VIRQA6lyg0XMrI-QPxL8jiAiEAr3PCH0T1jhSpm6c_C1cjSXgfaUk7Rdyc5-SWzSeuAvo%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgBpal_oMhIgmmgRfDnMlBMvJP-gXXzjuMbpGIz9NEC0kCIG0aOHgBNSbBlO_3COunwBPwWPrJ26o6dzkP09j1TPap&ratebypass=yes
https://r1---sn-c5niuxaxjvh-045l.googlevideo.com/videoplayback?expire=1563040663&ei=N8cpXce_Bou_7QTJ0LKgAg&ip=[my_ip]&id=4C1GqHm3xJc.1&itag=140&source=yt_live_broadcast&requiressl=yes&mm=44%2C29&mn=sn-c5niuxaxjvh-045l%2Csn-n8v7znsy&ms=lva%2Crdu&mv=m&mvi=0&pl=17&initcwndbps=585000&live=1&hang=1&noclen=1&mime=audio%2Fmp4&gir=yes&compress=yes&mt=1563018984&fvip=18&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Clive%2Chang%2Cnoclen%2Cmime%2Cgir%2Ccompress&sig=ALgxI2wwRAIgc96g51tC6FA5E50a80Wvd2JK4gYu5OPd2ms1V-HUU3gCIEV3YmUKNorrWBMQgwJdhd0rI6xZ8jfybKCZHkCallxg&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgBpal_oMhIgmmgRfDnMlBMvJP-gXXzjuMbpGIz9NEC0kCIG0aOHgBNSbBlO_3COunwBPwWPrJ26o6dzkP09j1TPap&ratebypass=yes

>youtube-dl -v https://www.youtube.com/channel/UCiUiZUDSpuiMiiecRBEOZEQ/live
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/channel/UCiUiZUDSpuiMiiecRBEOZEQ/live']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.07.12
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-93506-g27c94c57dc, ffprobe N-93506-g27c94c57dc
[debug] Proxy map: {}
[youtube:live] UCiUiZUDSpuiMiiecRBEOZEQ: Downloading webpage
[youtube] 4C1GqHm3xJc: Downloading webpage
[youtube] 4C1GqHm3xJc: Downloading video info webpage
[youtube] 4C1GqHm3xJc: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r1---sn-c5niuxaxjvh-045l.googlevideo.com/videoplayback?expire=1563040691&ei=U8cpXdvQFJO8yQXc253ABw&ip=[my_ip]&id=4C1GqHm3xJc.1&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160&source=yt_live_broadcast&requiressl=yes&mm=44%2C29&mn=sn-c5niuxaxjvh-045l%2Csn-n8v7znsy&ms=lva%2Crdu&mv=m&mvi=0&pcm2cms=yes&pl=17&initcwndbps=585000&live=1&hang=1&noclen=1&mime=video%2Fmp4&gir=yes&mt=1563018984&fvip=18&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Clive%2Chang%2Cnoclen%2Cmime%2Cgir&sig=ALgxI2wwRQIgPQQxCXoyIm9takrzx0ZRyxWbZkp79UiU4rQq2-fQ_yQCIQDBWCyIFhr6I5Ak1iDsz_wDFv7etWs-tknFr9eqnAJUIQ%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgBtk484TZtjGgbATabCvQg8AALRzscRvdtALWCin5LgoCIQCKyfGO7u6m5Lr3HyNEEaEjdJEd_mW7f3pVo4g6zc-JEw%3D%3D&ratebypass=yes'
[download] Resuming download at byte 1047552
[download] Destination: Кухня 6 сезон LIVE-4C1GqHm3xJc.f137.mp4
[download]  92.2% of 1.62MiB at 10.40MiB/s ETA 00:00 ^C

## Description

WRITE DESCRIPTION HERE

In currently time youtube-dl grab only 1 segment of stream like a video. And that's all I want to say.

**Comment by bagdenisov** [comment]
please send link of original similar issue

**Comment by remitamine** [comment]
> I've searched the bugtracker for similar issues including **closed ones**
