### ISSUE TITLE
mp3 tagging doesn't work as one might expect

### ISSUE THREAD

**Issue by Volker-Weissmann** [ytdl-org/youtube-dl#21785]
## Checklist

- [ x] I'm reporting a feature request
- [ x] I've verified that I'm running youtube-dl version **2019.07.14**
- [x ] I've searched the bugtracker for similar feature requests including closed ones

## Description

If you run
youtube-dl --extract-audio --audio-format mp3 "https://youtu.be/Sqk3B2041uk" --output test.mp3
id3v2 -t "cooltitle" -a "coolartist" test.mp3
and open the resulting test.mp3 file using rythmbox, rythmbox doesn't know that the titel is "cooltitle" and that the artist is "coolartist". 
But if you run
youtube-dl --extract-audio --audio-format mp3 "https://youtu.be/Sqk3B2041uk" --output "test.%(ext)s"
id3v2 -t "cooltitle" -a "coolartist" test.mp3
instead it works.
I think it is very unintuitive that the first version doesn't work. It would be nice if that would change, because I don't want other people to write the first one and then ask themselves for hours why this doesn't work.

**Comment by dstftw** [comment]
Output template is a template for downloaded file. Never hardcode ext for it.

**Comment by Volker-Weissmann** [comment]
> Output template is a template for downloaded file. Never hardcode ext for it.

It would be nice if this would be better explained in the manfile.
