### ISSUE TITLE
Problem with finished youtube live video

### ISSUE THREAD

**Issue by afsharsafavi** [ytdl-org/youtube-dl#21782]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.07.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl https://www.youtube.com/watch?v=XOivaAXRfW8 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=XOivaAXRfW8', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.14
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] XOivaAXRfW8: Downloading webpage
[youtube] XOivaAXRfW8: Downloading video info webpage
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2109, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.

## Description

WRITE DESCRIPTION HERE

Hello
It seems there is a problem with finished live video in Youtube.
For example, for downloading this video, I got an error:
https://www.youtube.com/watch?v=XOivaAXRfW8

**Comment by afsharsafavi** [comment]
I checked it with different IP location/country, and I've got the same error

**Comment by zontargs** [comment]
I am having the same issue with finished livestreams. This is due to a change in youtube-dl from 2019.07.12 to 2019.07.14, as I was able to download finished livestreams which failed with .14 as soon as I rolled back to .12
