### ISSUE TITLE
ERROR: YouTube said: The uploader has not made this video available in your country on artist videos

### ISSUE THREAD

**Issue by TheGr33k** [ytdl-org/youtube-dl#2179]
Hi 

I am not able to download files from certain popular artists(Pitbull and Ke$ha )
I ran the following command
youtube-dl -f 18 http://www.youtube.com/watch?v=hHUbLv4ThOo

I get 
[youtube] Setting language
[youtube] hHUbLv4ThOo: Downloading webpage
[youtube] hHUbLv4ThOo: Downloading video info webpage
ERROR: YouTube said: The uploader has not made this video available in your country.

I tried from 3 different servers each located in Atlanta , Seattle and Netherlands respectively but i still get same error

Btw the software is really awesome and is definitely a great piece of work 

Regards

**Comment by sae13** [comment]
is there any way I say youtube-dl skip videos u can delete from playlist?

**Comment by tanmauwu** [comment]
As it's been almost five years, and @Buzut seemed to have provided a solution, perhaps this issue should be closed.

**Comment by kolcon** [comment]
This is now quite old issue - should be probably closed...
