### ISSUE TITLE
ERROR: This video is unavailable.

### ISSUE THREAD

**Issue by wenxinxu** [ytdl-org/youtube-dl#21794]
## Checklist
- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2019.07.14**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=QhXToslnPvA', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.14
[debug] Python version 3.6.8 (CPython) - Linux-4.4.0-137-generic-x86_64-with-debian-stretch-sid
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] QhXToslnPvA: Downloading webpage
[youtube] QhXToslnPvA: Downloading video info webpage
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/sailhome/alexiaxu/anaconda3/envs/AQA/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/sailhome/alexiaxu/anaconda3/envs/AQA/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/sailhome/alexiaxu/anaconda3/envs/AQA/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 2109, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.
```

## Description

I tried to download a series of videos, none of them has restrictions or needs authentication. I could open all of them on an incognito browser. Does anybody know why I cannot download them?

The videos are:
- https://www.youtube.com/watch?v=cYkUl8MrXgA
- https://www.youtube.com/watch?v=V5parOfpuEQ
- https://www.youtube.com/watch?v=Y4ARBzok9aU

**Comment by wenxinxu** [comment]
@dstftw Sorry I did not found that previous post that is solved on this topic. Could you please point me to some solution regarding the problem? Thank you very much!

**Comment by dstftw** [comment]
Wait for the next release.
