### ISSUE TITLE
YouTube-DL: Feature Request of 'Video Quality' option in 'Output Template'.

### ISSUE THREAD

**Issue by RangaSE** [ytdl-org/youtube-dl#21804]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.07.16**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
Greetings!
I  have an Issue/Feature Request for (explicit) 'Video Quality' in (of my) videos; same video, one is '1080p' and the other is '2160p' with same title. This one is having '16:9' ratio (HD, 1.77777..8). But, not always! There are many other ratios such as '1.85', '2.20','2.35' or '2.40'. And some are having higher ratios as well.
For example, a normal video with '16:9' ratio:
...
[ffmpeg] Merging formats into "D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.mp4"
[debug] ffmpeg command line: ...
Deleting original file D:\Downloads\Train Ride to Tibet on the Worlds Highest Railway (u20181031; 641; 2160p30)YT 'We're the Russos'.f313.webm (pass -k to keep)
....
And another video NOT having '16:9' ratio:
...
[ffmpeg] Merging formats into "D:\Downloads\The Fantastic Four - Trailer (2005) (u20110130; 146; 808p24)YT 'QualityIsNumber1'.mp4"
Deleting original file D:\Downloads\The Fantastic Four - Trailer (2005) (u20110130; 146; 808p24)YT 'QualityIsNumber1'.f137.mp4 (pass -k to keep)
...
The last one is supposed to be '1080p24', I am giving Output Template as ' -o "D:\Downloads\%(title)s (u%(upload_date)s; %(duration)s; %(height)sp%(fps)s)YT '%(uploader)s'.%(ext)s" -- ' since, YT-DL doesn't have option for Video Quality (Output Template).
{ Also, you can note that the duration is in 'second' (146;) instead of 'h,m,s' (0,2,26;) If you want only the function/procedure, (like durationHMS) may be I can help. }
Thanks for (your) Patience.
ATB! Regards,

**Comment by RangaSE** [comment]
Greetings!
I just don't understand that 'dstftw' did as 'incomplete' and 'Closed'.
I made 'A Feature Request' for 'Video Quality' such as 1080p or 2160p, only when they are in 4:3 or 16:9 aspect ratios (AR) and showed two references for the same, as, 4:3 and 16:9 and not in those AR. So, I don't think the term 'Incomplete' apply.
ATB! Regards,

**Comment by dstftw** [comment]
Your explanation is total mess I don't even want to bother deciphering.
If you want something to be implemented you must clearly explain what you're requesting, how to obtain such information with concrete examples URLs.

**Comment by RangaSE** [comment]
(P.S.: Please , see 'Stats for Nerds' option on Right click. ATB!)
