### ISSUE TITLE
no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info

### ISSUE THREAD

**Issue by rahulpathakgit** [ytdl-org/youtube-dl#21814]
Hi,

Facing this error on Ubuntu 18.04

youtube-dl https://youtu.be/LbDOCJcDRoo --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://youtu.be/LbDOCJcDRoo', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.16
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-25-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {'http': <proxy details removed>, 'https': '<proxy details removed>'}
[youtube] LbDOCJcDRoo: Downloading webpage
[youtube] LbDOCJcDRoo: Downloading video info webpage
WARNING: Unable to extract video title
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2109, in _real_extract
    raise ExtractorError('no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info')
ExtractorError: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by remitamine** [comment]
```
python  __main__.py https://youtu.be/LbDOCJcDRoo
[youtube] LbDOCJcDRoo: Downloading webpage
[youtube] LbDOCJcDRoo: Downloading video info webpage
[youtube] LbDOCJcDRoo: Downloading MPD manifest
[download] Destination: Kernel Recipes 2017 - An introduction to the Linux DRM subsystem - Maxime Ripard-LbDOCJcDRoo.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0  275M    0 1638k    0     0   247k      0  0:18:59  0:00:06  0:18:53  401k
```

**Comment by gacekssj4** [comment]
@remitamine Have same issue with downloading

However, tried video from issue creator, and can download it fine. For me this one does not work. Maybe will be reproducable with this one.

	user@DESKTOP F:\tmp\youtube-dl\youtube-manual
	$ youtube-dl -f best -x "https://music.youtube.com/watch?v=ojjDhdoPF6E"
	[youtube:playlist] Downloading playlist RDAMVMojjDhdoPF6E - add --no-playlist to just download video ojjDhdoPF6E
	[youtube:playlist] RDAMVMojjDhdoPF6E: Downloading page 1 of Youtube mix
	[download] Downloading playlist: RDAMVMojjDhdoPF6E
	[youtube:playlist] playlist RDAMVMojjDhdoPF6E: Collected 0 video ids (downloading 0 of them)
	[download] Finished downloading playlist: RDAMVMojjDhdoPF6E

	user@DESKTOP F:\tmp\youtube-dl\youtube-manual
	$ youtube-dl -f best -x "https://music.youtube.com/watch?v=ojjDhdoPF6E"
	[youtube] ojjDhdoPF6E: Downloading webpage
	[youtube] ojjDhdoPF6E: Downloading video info webpage
	ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Verbose:

	[debug] System config: []
	[debug] User config: ['--write-sub', '--sub-lang', 'en', '--convert-subs', 'ass', '--embed-sub', '--user-agent', 'Mozilla/5.0 (Linux; Android 7.0; SM-G892A Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Mobile Safari/537.36', '--ffmpeg-location', 'ffmpeg.exe', '--external-downloader', 'ffmpeg.exe']
	[debug] Custom config: []
	[debug] Command-line args: ['--ffmpeg-location', 'G:\\cli_aliases', '-f', 'best', '-x', '--verbose', 'https://www.youtube.com/watch?v=ojjDhdoPF6E']
	[debug] Encodings: locale cp1250, fs mbcs, out cp65001, pref cp1250
	[debug] youtube-dl version 2019.07.16
	[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
	[debug] exe versions: ffmpeg N-94334-gab4795a085, ffprobe N-94334-gab4795a085, phantomjs 2.1.1
	[debug] Proxy map: {}
	[youtube] ojjDhdoPF6E: Downloading webpage
	[youtube] ojjDhdoPF6E: Downloading video info webpage
	ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	Traceback (most recent call last):
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 530, in extract
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\youtube.py", line 2109, in _real_extract
	youtube_dl.utils.ExtractorError: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by gacekssj4** [comment]
@remitamine I can download video of @rahulpathakgit fine, but have problem with different one. Maybe this will help:

	youtube-dl --verbose https://www.youtube.com/watch?v=ojjDhdoPF6E
	[debug] System config: []
	[debug] User config: ['--write-sub', '--sub-lang', 'en', '--convert-subs', 'ass', '--embed-sub', '--user-agent', 'Mozilla/5.0 (Linux; Android 7.0; SM-G892A Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Mobile Safari/537.36', '--ffmpeg-location', 'ffmpeg.exe', '--external-downloader', 'ffmpeg.exe']
	[debug] Custom config: []
	[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=ojjDhdoPF6E']
	[debug] Encodings: locale cp1250, fs mbcs, out cp65001, pref cp1250
	[debug] youtube-dl version 2019.07.16
	[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
	WARNING: ffmpeg-location ffmpeg.exe does not exist! Continuing without avconv/ffmpeg.
	[debug] exe versions: phantomjs 2.1.1
	[debug] Proxy map: {}
	WARNING: ffmpeg-location ffmpeg.exe does not exist! Continuing without avconv/ffmpeg.
	WARNING: ffmpeg-location ffmpeg.exe does not exist! Continuing without avconv/ffmpeg.
	[youtube] ojjDhdoPF6E: Downloading webpage
	[youtube] ojjDhdoPF6E: Downloading video info webpage
	ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	Traceback (most recent call last):
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 530, in extract
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\youtube.py", line 2109, in _real_extract
	youtube_dl.utils.ExtractorError: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by remitamine** [comment]
```
youtube-dl https://www.youtube.com/watch?v=ojjDhdoPF6E
[youtube] ojjDhdoPF6E: Downloading webpage
[youtube] ojjDhdoPF6E: Downloading video info webpage
[download] Destination: Amon Amarth - Shield Wall (Official Audio)-ojjDhdoPF6E.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  3 12.4M    3  416k    0     0   137k      0  0:01:33  0:00:03  0:01:30  431k
```

**Comment by gacekssj4** [comment]
OK.. then can't help more... seems to apply to random video for different people as I still can't download it

**Comment by takashi-fkd** [comment]
I got the same issue and I solved it. The cause of the issue was UA because when I set some UA like mobile device (Android, iPhone etc) by --user-agent option, the request was redirected to m.youtube.com once and then went back to www.youtube.com again. So, maybe the behavior gave bad effect to parse its response.
I wish you good luck.

**Comment by piotao** [comment]
Same error for me, here's Linux Mint 19.3 with python 3.7m:

youtube-dl https://www.youtube.com/watch?v=F7tMuUekYQA --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=F7tMuUekYQA', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.6.9 (CPython) - Linux-5.3.0-28-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube] F7tMuUekYQA: Downloading webpage
[youtube] F7tMuUekYQA: Downloading video info webpage
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/piotao/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/piotao/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/piotao/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 2109, in _real_extract
    raise ExtractorError('no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info')
youtube_dl.utils.ExtractorError: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
