### ISSUE TITLE
7plus (Australia) "No video formats found"

### ISSUE THREAD

**Issue by chogam** [ytdl-org/youtube-dl#21816]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.07.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

G:\>youtube-dl -v "https://7plus.com.au/mstarastarsstarh?episode-id=MASH8-024"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://7plus.com.au/mstarastarsstarh?episode
-id=MASH8-024']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.07.16
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.1.3
[debug] Proxy map: {}
[7plus] MASH8-024: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_
l6\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_
l6\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_
l6\build\youtube_dl\extractor\sevenplus.py", line 61, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_
l6\build\youtube_dl\extractor\brightcove.py", line 695, in _parse_brightcove_met
adata
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_
l6\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.-->

## Description

I saw other closed issues that looked similar to this marked as DRM but I do not think this is the case for this particular URL because:
1.  It is part of a series, and the other episodes are available.
2.  Episode 21  ("https://7plus.com.au/mstarastarsstarh?episode-id=MASH8-021") originally had the same error until I updated youtube-dl to version 2019.07.16.  This makes me suspect that the fix for Episode 21 was not comprehensive enough to catch the issue with Episode 24

**Comment by remitamine** [comment]
```
youtube-dl https://7plus.com.au/mstarastarsstarh?episode-id=MASH8-021
[7plus] MASH8-021: Downloading JSON metadata
[7plus] MASH8-021: Downloading m3u8 information
[7plus] MASH8-021: Downloading MPD manifest
[7plus] MASH8-021: Downloading MPD manifest
[7plus] MASH8-021: Downloading JSON metadata
[download] Destination: S8 E21 - Goodbye, Cruel World-MASH8-021.fhls-1711.mp4
ffmpeg version n4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[hls,applehttp @ 0x555eb29f3f80] Opening 'https://manifest.prod.boltdns.net/license/v1/aes128/5303576322001/33d98f03-1faf-4ce8-b1b2-911e8174d8b9/f3b6af63-c021-48e5-9021-992f4946ee29?fastly_token=...' for reading
[hls,applehttp @ 0x555eb29f3f80] Opening 'crypto+https://7plus-sevennetwork.akamaized.net/media/v1/hls/v5/aes128/5303576322001/33d98f03-1faf-4ce8-b1b2-911e8174d8b9/5424c6e1-f289-47aa-aa93-c66b9b6167fa/f3b6af63-c021-48e5-9021-992f4946ee29/5x/segment0.ts?akamai_token=...' for reading
Input #0, hls,applehttp, from 'https://manifest.prod.boltdns.net/manifest/v1/hls/v5/aes128/5303576322001/33d98f03-1faf-4ce8-b1b2-911e8174d8b9/5424c6e1-f289-47aa-aa93-c66b9b6167fa/10s/rendition.m3u8?fastly_token=...':
  Duration: 00:23:07.68, start: 0.080000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 896x504 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:S8 E21 - Goodbye, Cruel World-MASH8-021.fhls-1711.mp4.part':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 896x504 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
frame=  137 fps=0.0 q=-1.0 size=    1024kB time=00:00:05.36 bitrate=1565.1kbits
```

**Comment by chogam** [comment]
Episode 24 is the one that is not working.  Can you test that one please?
https://7plus.com.au/mstarastarsstarh?episode-id=MASH8-024

Episode 21 was the one that was fixed by updating to the current version.

**Comment by remitamine** [comment]
this episode has only DRM protected formats.

**Comment by chogam** [comment]
Thanks.
