### ISSUE TITLE
Highest supported FFMPEG version?

### ISSUE THREAD

**Issue by BaronKrause** [ytdl-org/youtube-dl#21826]
I'm using the windows binary and noticed when testing a v.reddit video that when using the newest 4.1.x version of FFMPEG that there is errors after the first 3-4 seconds in the form of video freeze/pixelation before clearing up. (using just the basic "youtube-dl.exe http://videolink.com" command)

This seems to happen on every version of FFMPEG 4.x, both 32 and 64 bit from 4.0 to the newest git version. Once you dip below to the last released 3.x version (3.4.2) and below, the merged result seemed to be flawless (no noticeable difference from the unmerged source).

Is ffmpeg 4.0 not fully compatible with youtube-dl in some way?

This was the test video I used incase it is specific to this example:
https://www.reddit.com/r/DragaliaLost/comments/cdw67i/when_july_20th_hits/?st=jy8zrzeg&sh=57092f6b

**Comment by remitamine** [comment]
on the contrary, it's advised to always use the latest version as there are several things that do not work on older versions or work better on newer versions(av1 codec support, better support for m3u8 formats merging...).
if it's the case that latest version does not work with a particular video while it does work on an older version than it's probably a regression that you should report at the [FFmpeg bug tracker](https://trac.ffmpeg.org/).

**Comment by remitamine** [comment]
BTW, it works fine for me with FFmpeg 4.1.3 on Archlinux.

**Comment by BaronKrause** [comment]
> 
> 
> BTW, it works fine for me with FFmpeg 4.1.3 on Archlinux.

Weird, I just did a bit more testing, it seems that when playing the videos inside chrome they all run fine, its just VLC that has issues with the merged v.reddit video at the 4-5 second marker if it was made using version 4.0 or higher.

**Comment by remitamine** [comment]
so it's probably a problem with VLC 4, not FFmpeg, as it works for me with VLC 3.0.7 and MPV 0.29.1.
