### ISSUE TITLE
Strange problem with FFMPEG on windows

### ISSUE THREAD

**Issue by gacekssj4** [ytdl-org/youtube-dl#21829]
## Checklist

- [ x ] I'm asking a question
- [ x ] I've looked through the README and FAQ for similar questions
- [ x ] I've searched the bugtracker for similar questions including closed ones

## Question

Not sure if I'm doing anything wrong, but somehow I cannot seem to run yt-download from different folder than it is in.

### file locations
avconv is in `C:\avconv`
ffmpeg and youtube-dl is in `D:\youtub-dl`

Program only detects ffmpeg when I'm running it from folder where exe is.

Note: both `D:\youtub-dl` and `C:\avconv` are added to `%PATH%`

### Full console log.

	C:\>avconv
	avconv version v13_dev0-1440-g34c1133, Copyright (c) 2000-2018 the Libav developers
	  built on Jan  8 2018 22:16:49 with gcc 4.8.3 (Gentoo 4.8.3 p1.1, pie-0.5.9)
	Hyper fast Audio and Video encoder
	usage: avconv [options] [[infile options] -i infile]... {[outfile options] outfile}...

	Use -h to get full help or, even better, run 'man avconv'

	C:\>ffmpeg
	ffmpeg version N-94334-gab4795a085 Copyright (c) 2000-2019 the FFmpeg developers
	  built with gcc 9.1.1 (GCC) 20190716
	  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
	  libavutil      56. 30.100 / 56. 30.100
	  libavcodec     58. 53.101 / 58. 53.101
	  libavformat    58. 28.102 / 58. 28.102
	  libavdevice    58.  7.100 / 58.  7.100
	  libavfilter     7. 56.101 /  7. 56.101
	  libswscale      5.  4.101 /  5.  4.101
	  libswresample   3.  4.100 /  3.  4.100
	  libpostproc    55.  4.100 / 55.  4.100
	Hyper fast Audio and Video encoder
	usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

	Use -h to get full help or, even better, run 'man ffmpeg'

	C:\>youtube-dl -x https://www.youtube.com/watch?v=xxxxx
	WARNING: ffmpeg-location ffmpeg.exe does not exist! Continuing without avconv/ffmpeg.
	WARNING: ffmpeg-location ffmpeg.exe does not exist! Continuing without avconv/ffmpeg.
	WARNING: ffmpeg-location ffmpeg.exe does not exist! Continuing without avconv/ffmpeg.
	[youtube] xxxxx: Downloading webpage
	[youtube] xxxxx: Downloading video info webpage
	[youtube] xxxxx: Downloading embed webpage
	WARNING: unable to extract uploader nickname
	WARNING: unable to extract video thumbnail
	WARNING: video doesn't have subtitles
	[download] Destination: title_title_title_title_title_title-xxxxx.webm
	WARNING: ffmpeg-location ffmpeg.exe does not exist! Continuing without avconv/ffmpeg.
	ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.

	:\>cd /D D:\youtub-dl

	D:\youtub-dl>youtube-dl -x https://www.youtube.com/watch?v=xxxxx
	[youtube] xxxxx: Downloading webpage
	[youtube] xxxxx: Downloading video info webpage
	[youtube] xxxxx: Downloading embed webpage
	WARNING: unable to extract uploader nickname
	WARNING: unable to extract video thumbnail
	WARNING: video doesn't have subtitles
	[download] Destination: title_title_title_title_title_title-xxxxx.webm
	ffmpeg version N-94334-gab4795a085 Copyright (c) 2000-2019 the FFmpeg developers
	  built with gcc 9.1.1 (GCC) 20190716
	  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
	  libavutil      56. 30.100 / 56. 30.100
	  libavcodec     58. 53.101 / 58. 53.101
	  libavformat    58. 28.102 / 58. 28.102
	  libavdevice    58.  7.100 / 58.  7.100
	  libavfilter     7. 56.101 /  7. 56.101
	  libswscale      5.  4.101 /  5.  4.101
	  libswresample   3.  4.100 /  3.  4.100
	  libpostproc    55.  4.100 / 55.  4.100
	Input #0, matroska,webm, from 'https://r4---sn-u2oxu-f5fe7.googlevideo.com/videoplayback?expire=1563504216&ei=-NkwXe24M9ap7gPNzIz4Bw&ip=83.31.3.158&id=o-AEi_JxxrTxkLGUmcBbx3zhFPfYVjoLInbPhQEN8xaVg6&itag=251&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-u2oxu-f5fe7%2Csn-5hnekn7d&ms=au%2Conr&mv=m&mvi=3&pcm2cms=yes&pl=24&initcwndbps=705000&mime=audio%2Fwebm&gir=yes&clen=32303547&dur=1860.281&lmt=1540301732490072&mt=1563482500&fvip=4&keepalive=yes&c=WEB&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIhAMy6Oy63-8JOcHaFUuHL08f7M6-_lMbve8RC4GwLAJ7jAiB3UYC_qgNoRwndEEpePfe0evQwCWxgbZMLcMpP0_oJnA%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgTSmD_qVJNVy1NahvatJTpTPSN2-8hztj_vvwTcY1tR0CIQDtXmqPoD6W8x_2PFPkSobGaoVX5x1rkrcW61aBZRtfrA%3D%3D&ratebypass=yes':
	  Metadata:
		encoder         : google/video-file
	  Duration: 00:31:00.28, start: -0.007000, bitrate: 138 kb/s
		Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
	Output #0, webm, to 'file:title_title_title_title_title_title-xxxxx.webm.part':
	  Metadata:
		encoder         : Lavf58.28.102
		Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
	Stream mapping:
	  Stream #0:0 -> #0:0 (copy)
	Press [q] to stop, [?] for help
	https://r4---sn-u2oxu-f5fe7.googlevideo.com/videoplayback?expire=1563504216&ei=-NkwXe24M9ap7gPNzIz4Bw&ip=83.31.3.158&id=o-AEi_JxxrTxkLGUmcBbx3zhFPfYVjoLInbPhQEN8xaVg6&itag=251&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-u2oxu-f5fe7%2Csn-5hnekn7d&ms=au%2Conr&mv=m&mvi=3&pcm2cms=yes&pl=24&initcwndbps=705000&mime=audio%2Fwebm&gir=yes&clen=32303547&dur=1860.281&lmt=1540301732490072&mt=1563482500&fvip=4&keepalive=yes&c=WEB&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIhAMy6Oy63-8JOcHaFUuHL08f7M6-_lMbve8RC4GwLAJ7jAiB3UYC_qgNoRwndEEpePfe0evQwCWxgbZMLcMpP0_oJnA%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgTSmD_qVJNVy1NahvatJTpTPSN2-8hztj_vvwTcY1tR0CIQDtXmqPoD6W8x_2PFPkSobGaoVX5x1rkrcW61aBZRtfrA%3D%3D&ratebypass=yes: Immediate exit requested
	Error writing trailer of file:title_title_title_title_title_title-xxxxx.webm.part: Immediate exit requested
	size=     425kB time=00:00:29.56 bitrate= 117.8kbits/s speed=28.5x
	video:0kB audio:498kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
	Exiting normally, received signal 2.

	ERROR: Interrupted by user

**Comment by dstftw** [comment]
Do you even read the output?
>WARNING: ffmpeg-location ffmpeg.exe does not exist! Continuing without avconv/ffmpeg.

**Comment by gacekssj4** [comment]
Sorry @dstftw ... but have you seen console output? youtube-dl only detects it if its in same folder... its available in whole system...

**Comment by gacekssj4** [comment]
```
C:\>ffmpeg
ffmpeg version N-94334-gab4795a085 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190716
[trimmed]
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...```

**Comment by dstftw** [comment]
Output clearly tells you that path you passed in with `--ffmpeg-location` **does not exist**. Don't touch `--ffmpeg-location` if you have no idea of what you are doing.
