### ISSUE TITLE
EduGyaan site support request

### ISSUE THREAD

**Issue by ComputerUser-CU** [ytdl-org/youtube-dl#21839]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.07.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single Video: http://theiashub.edugyaan.com/video/index/122221?cbid=5042

It's a playlist. There are no single video webpages on this website.

## Description

WRITE DESCRIPTION HERE

This is reference to the following issues:

- [here](https://github.com/ytdl-org/youtube-dl/issues/21806), 

- [here](https://github.com/ytdl-org/youtube-dl/issues/21646), and

- [here](https://github.com/ytdl-org/youtube-dl/issues/17597)

Kindly add support for AES-128 encrypted HLS videos (such as those streamed via edugyaan.com)

If needed, credentials can be emailed.

**Comment by ComputerUser-CU** [comment]
Oh! I see! I forgot to add the Example URLs. They could be found in the first issue I listed. But I understand that they must have been mentioned here for everyone's reference.

Please find then below:
- Single video: https://5ad66d227b0c1.streamlock.net/edusecure/_definist/64/1212/5042/121513/64_1212_5042_121513_0.mp4/chunklist_w1422491268.m3u8?isPrimary=true&ref=http%3A%2F%2Ftheiashub.edugyaan.com&sessionId=1l0gahmb2ueads99d190bfcnn4&userId=231644&username=singhal.shagun%40gmail.com&videoId=121513

There are no playlist URLs. The M3U8 playlist URL mentioned above contains partial URLs of the various TS segments.

**Comment by remitamine** [comment]
no, post the URLs of the original webpages, not the m3u8 manifest, and verbose log of the command used.

**Comment by ComputerUser-CU** [comment]
Oh! Then things change.
Then the URL of the original webpage is: http://theiashub.edugyaan.com/video/index/122221?cbid=5042
It's a playlist.

**Comment by ComputerUser-CU** [comment]
Yeah. So for account, how can I share the details? If anyone's interested, I can email them.

**Comment by ComputerUser-CU** [comment]
Regarding account credentials, please email me at lastaspiration@gmail.com. I'll share the credentials there.

If there are any better sharing mechanisms, kindly do let me know. I'll share the credentials via the same.

**Comment by ComputerUser-CU** [comment]
I can confirm that @remitamine's suggested modifications in hls.py in [this thread](https://github.com/ytdl-org/youtube-dl/issues/21806) did indeed help me download the entire video file. However, with respected to videos downloaded with `--hls-prefer-native` 
1. In absence of FFMPEG, youtube-dl reported malformed AAC bitstream. And the downloaded video couldn't be played either by VLC or by Potplayer.
2. In presence of FFMPEG, youtube-dl went on the fix the malformed AAC bitsream. However, the resultant videos were truncated. e.g.: As against the expected duration of 2 hours 40 minutes, a resultant video was only 30-odd minutes long.

In case I used FFMPEG to download the videos, 
1. FFMPEG would sometimes download all the fragments of the video, but write only the fragments worth initial few minutes into the MP4 file;
2. Sometimes FFMPEG would not download the later fragments at all and throw some encryption-related error 

In either case, neither the HLS downloader nor FFMPEG were able to download and reproduce complete video files.

**Comment by ComputerUser-CU** [comment]
HLS native downloader produced this file:
https://drive.google.com/open?id=1M8gJMd_-OhX6qJD5KTxBHkavU64w-_WY

It cannot be opened by even VLC. Handbrake as well as ffmpeg says, moov atom not found.

Here is the log I try to perform any operation with ffmpeg on this file:
[MOOV Atom Issue.txt](https://github.com/ytdl-org/youtube-dl/files/3414255/MOOV.Atom.Issue.txt)
