### ISSUE TITLE
Can no longer download any video from VRV.co

### ISSUE THREAD

**Issue by MindController** [ytdl-org/youtube-dl#21830]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.07.16**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
C:\Program Files (x86)\DVD_tools\youtube-dl>youtube-dl https://vrv.co/watch/GYNVDG8XR/Stake-Land --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vrv.co/watch/GYNVDG8XR/Stake-Land', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.07.16
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-93485-g5282cbae61
[debug] Proxy map: {}
[vrv] None: Downloading webpage
[vrv] GYNVDG8XR: Downloading resource path JSON metadata
[vrv] GYNVDG8XR: Downloading CMS Signing JSON metadata
[vrv] GYNVDG8XR: Downloading object JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https
://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl wit
h the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", lin
e 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\YoutubeDL.py", line 2227,
 in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default


C:\Program Files (x86)\DVD_tools\youtube-dl>
```

## Description

I have a premium subscription to VRV.co.  Recently I started getting this HTTP Error 403: Forbidden.  I'm using the -u and -p flags for my username and password, but regardless of using them or not, I get this error.  An example of a URL would be:

https://vrv.co/watch/GYNVDG8XR/Stake-Land

or

https://vrv.co/watch/GRVDNPK3R/The-Last-Drive-in-With-Joe-Bob-Briggs-July-2018-Marathon:The-Last-Drive-In-with-Joe-Bob-Briggs-Rabid

**Comment by Mrifk** [comment]
probably fixed by https://github.com/ytdl-org/youtube-dl/commit/1824bfdcdff1af4bfc4f7f6ed885d45ee7e8c376 ? hasn't been put in the latest version yet.
