### ISSUE TITLE
Convert command line arguments to use in python script

### ISSUE THREAD

**Issue by daniel-sudz** [ytdl-org/youtube-dl#21831]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

I am aware that you can embed arguments to run youtube-dl within a python script like so: https://github.com/ytdl-org/youtube-dl#embedding-youtube-dl.  However, I am wondering if it is possible to convert command line arguments such as -v --restrict-filenames --ignore-errors and pass them into a an embedded youtube-dl call.

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl/blob/3e4cedf9e8cd3157df2457df7274d0c842421945/youtube_dl/YoutubeDL.py#L137-L312
