### ISSUE TITLE
JSON - --download-archive support

### ISSUE THREAD

**Issue by SirWindfield** [ytdl-org/youtube-dl#21845]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is it currently possible to retrieve a playlist's videos (as json) and have archive support too at the same time? My goal is to retrieve only the newest video's metadata of a playlist (without downloading the video itself).

Something along the lines of `youtube_dl <playlist_url> -j --flat-playlist --download-archive archive.txt`. This should only return the json for videos that are not in archive.txt.

**Comment by dstftw** [comment]
Not possible.
