### ISSUE TITLE
YouTube fragments not found, endless error

### ISSUE THREAD

**Issue by horusra** [ytdl-org/youtube-dl#21851]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2019.07.16**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: ['--no-mtime', '-f', 'bestvideo+bestaudio']
[debug] Custom config: []
[debug] Command-line args: ['-o', 'I:\\Youtube\\%(playlist)s\\%(playlist_index)003d_%(title)s.%(ext)s', '--all-subs', '--embed-subs', '--verbose', '-i', 'https://www.youtube.com/playlist?list=PL0iycuXI4xZnfBlNpmKiesInbniI2Bn4r']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.07.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-86537-gae6f6d4, ffprobe N-86537-gae6f6d4
[debug] Proxy map: {}
[youtube:playlist] PL0iycuXI4xZnfBlNpmKiesInbniI2Bn4r: Downloading webpage
[download] Downloading playlist: TwinMotion 2019 For Beginners
[youtube:playlist] playlist TwinMotion 2019 For Beginners: Downloading 43 videos
[download] Downloading video 1 of 43
[youtube] 5ldItoXuOsA: Downloading webpage
[youtube] 5ldItoXuOsA: Downloading video info webpage
WARNING: video doesn't have subtitles
[youtube] 5ldItoXuOsA: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] I:\Youtube\TwinMotion 2019 For Beginners\001_TwinMotion 2019 Tutorial Teaser.mkv has already been downloaded and merged
[ffmpeg] There aren't any subtitles to embed
[download] Downloading video 2 of 43
[youtube] s2LUjcqZ9Gg: Downloading webpage
[youtube] s2LUjcqZ9Gg: Downloading video info webpage
WARNING: video doesn't have subtitles
[download] I:\Youtube\TwinMotion 2019 For Beginners\002_TwinMotion 2019 - Basics.webm has already been downloaded and merged
[ffmpeg] There aren't any subtitles to embed
[download] Downloading video 3 of 43
[youtube] TC3KUVGFNWU: Downloading webpage
[youtube] TC3KUVGFNWU: Downloading video info webpage
WARNING: video doesn't have subtitles
[youtube] TC3KUVGFNWU: Downloading MPD manifest
[download] I:\Youtube\TwinMotion 2019 For Beginners\003_TwinMotion 2019 - Basics Extended Cut.webm has already been downloaded and merged
[ffmpeg] There aren't any subtitles to embed
[download] Downloading video 4 of 43
[youtube] UJHRBSzM_Ns: Downloading webpage
[youtube] UJHRBSzM_Ns: Downloading video info webpage
WARNING: video doesn't have subtitles
[download] I:\Youtube\TwinMotion 2019 For Beginners\004_TwinMotion 2019 - Working with Objects.webm has already been downloaded and merged
[ffmpeg] There aren't any subtitles to embed
[download] Downloading video 5 of 43
[youtube] GkiqlCxM6s0: Downloading webpage
[youtube] GkiqlCxM6s0: Downloading video info webpage
WARNING: video doesn't have subtitles
[youtube] GkiqlCxM6s0: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1563737467/ei/G2k0XbXIGsyOV4CXpLgP/ip/190.2.145.106/id/1a48aa942c4ceacd/source/youtube/requiressl/yes/playback_host/r3---sn-5hnednlr.googlevideo.com/mm/31%2C26/mn/sn-5hnednlr%2Csn-2gb7sn7s/ms/au%2Conr/mv/m/mvi/2/pl/24/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/255000/mt/1563715722/fvip/3/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Citag/sig/ALgxI2wwRQIhAOIGFu80BIJu66YyIXf8FkmLKDZ1CqkGFyR4ryFQqo1rAiB6GBz9dgf41clZNFUam542Ym2xitbQGEJerBh8xfLJ0w%3D%3D/lsparams/playback_host%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AHylml4wRAIgAwQbVkkmk-5fWEut1G5Gh7jCvpcEdtvHRHjMEwkUBAMCIH6EVsM7g4_5GllEWv9Riu3w40AafZy1EV2VZf3f6_3m'
[dashsegments] Total fragments: 25
[download] Destination: I:\Youtube\TwinMotion 2019 For Beginners\005_TwinMotion 2019 - LiveLink [Revit].f248.webm
[download]  16.0% of ~4.29MiB at  2.06MiB/s ETA 00:05 [download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5 (attempt 10 of 10)...
[download] Skipping fragment 5...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 6 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 6 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 6 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 6 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 6 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 6 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 6 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 6 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 6 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 6 (attempt 10 of 10)...
[download] Skipping fragment 6...
[download]  20.0% of ~4.94MiB at  2.12MiB/s ETA 20:46  [download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 8 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 8 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 8 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 8 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 8 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 8 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 8 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 8 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 8 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 8 (attempt 10 of 10)...
[download] Skipping fragment 8...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 9 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 9 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 9 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 9 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 9 (attempt 5 of 10)...
[

## Description

Trying to download a playlist of videos, but ytdl always gets stuck on the 5th video, and keeps trying to look for fragments but not finding any. The playlist is:
https://www.youtube.com/playlist?list=PL0iycuXI4xZnfBlNpmKiesInbniI2Bn4r

**Comment by srikanta159** [comment]
facing same issue.

**Comment by dstftw** [comment]
Server side Youtube error.
