### ISSUE TITLE
[sixplay] New resolution

### ISSUE THREAD

**Issue by Europe57** [ytdl-org/youtube-dl#21858]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.07.16**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

New resolution are available on the site 6play.fr:
- 1280x720
- 1248x702
- 960x540

They are not detected by Youtube-DL:

youtube-dl -k -R "infinite" http://www.6play.fr/the-rookie-the-flic-of-los-angeles-p_14355/season-1-episode-8-c_12429743 -E
[6play] 12429743: Downloading JSON metadata
[6play] 12429743: Downloading webpage
[6play] 12429743: Downloading m3u8 information
[6play] 12429743: Downloading MPD manifest
[6play] 12429743: Downloading webpage
[6play] 12429743: Downloading m3u8 information
[6play] 12429743: Downloading MPD manifest
[info] Available formats for 12429743:
format code extension resolution note
dash-audio1 = 93468-0 m4a audio only [en] audio DASH 93k, m4a_dash container, mp4a.40.2 (48000Hz)
dash-audio1 = 93468-1 m4a audio only [en] DASH audio 93k, m4a_dash container, mp4a.40.2 (48000Hz)
dash-video_eng = 300000-0 mp4 400x226 [en] 300k DASH video, mp4_dash container, avc1.42001E, 25fps, video only
dash-video_eng = 300000-1 mp4 400x226 [in] DASH video 300k, mp4_dash container, avc1.42001E, 25fps, video only
dash-video_eng = 801000-0 mp4 640x360 [en] DASH video 801k, mp4_dash container, avc1.42001E, 25fps, video only
dash-video_eng = 801000-1 mp4 640x360 [en] DASH video 801k, mp4_dash container, avc1.42001E, 25fps, video only
dash-video_eng = 1501000-0 mp4 720x406 [en] DASH video 1501k, mp4_dash container, avc1.42001E, 25fps, video only
dash-video_eng = 1501000-1 mp4 720x406 [en] DASH video 1501k, mp4_dash container, avc1.42001E, 25fps, video only
hls-418-0 mp4 400x226 418k, avc1.42001E @ 300k, 25.0fps, mp4a.40.2 @ 93k
hls-418-1 mp4 400x226 418k, avc1.42001E @ 300k, 25.0fps, mp4a.40.2 @ 93k
hls-949-0 mp4 640x360 949k, avc1.42001E @ 801k, 25.0fps, mp4a.40.2 @ 93k
hls-949-1 mp4 640x360 949k, avc1.42001E @ 801k, 25.0fps, mp4a.40.2 @ 93k
hls-1691-0 mp4 720x406 1691k, avc1.42001E@1501k, 25.0fps, mp4a.40.2 @ 93k
hls-1691-1 mp4 720x406 1691k, avc1.42001E@1501k, 25.0fps, mp4a.40.2 @ 93k (best)

Thank you for adding these resolutions.

**Comment by remitamine** [comment]
most likely the qualities mentioned are DRM protected.
