### ISSUE TITLE
VRV Still getting HTTP Error 403

### ISSUE THREAD

**Issue by phharley17** [ytdl-org/youtube-dl#21863]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '-F', 'https://vrv.co/watch/GYP55W8KY/CatDog:Squirrel-Dog-Brothers-Day']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.07.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-93461-g6e42021128
[debug] Proxy map: {}
[vrv] None: Downloading webpage
[vrv] Downloading Token Credentials JSON metadata
[vrv] GYP55W8KY: Downloading resource path JSON metadata
[vrv] GYP55W8KY: Downloading CMS Signing JSON metadata
[vrv] GYP55W8KY: Downloading object JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpaxmfe_l6\build\youtube_dl\YoutubeDL.py", line 2227, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

Hi, I've noticed this was posted about 6 days ago, was closed and redirected to a possible fix? maybe I am missing something but is still seems like not working. Any suggestions or possible solution? it was working as of **July 11th, 2019** which was the last time I downloaded. I tried with every link I tried back them and doesn't seem to work, even with querying the available audio and video stream with the **-F** argument, I keep getting HTTP Error 403. My VRV account is active and is **not open/streaming** while it tried to download, I can see the same content just fine on the browser. 

Here is the link: https://vrv.co/watch/GYP55W8KY/CatDog:Squirrel-Dog-Brothers-Day

Thank you so much for this amazing program and your commitment to it!

**Comment by remitamine** [comment]
not released yet.
