### ISSUE TITLE
youtube-dl: “--skip download” cancels out “--download-archive” (non-video material)

### ISSUE THREAD

**Issue by SillyScribe95** [ytdl-org/youtube-dl#21878]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

SO question (link here):

https://stackoverflow.com/questions/57168566/youtube-dl-skip-download-cancels-out-download-archive-non-video-materi

trying to download a Youtube playlist's json metadata (NOT VIDEOs):

**--skip download** ignores video downloads, just giving the .json info

**--download-archive** archive.txt saves a URL list of previously downloaded videos from this playlist to archive.txt, and skips over them if I run the youtube-dl command again.

However, including --skip download in the commands results in URLs of each video not being added to archive.txt, which suggests yt-dl only counts videos as extracted metadata and no . Are the two commands able to run together in any format/order or is this a bug?

EXAMPLE CODE:

`youtube-dl -i --write-info-json --skip-download --download-archive __archive___.txt < PLAYLIST >`

**Comment by remitamine** [comment]
```
--download-archive FILE          Download only videos not listed in the
                                 archive file. Record the IDs of all
                                 downloaded videos in it.
```
> Record the IDs of all **downloaded** videos in it.

**Comment by SillyScribe95** [comment]
Thanks! Just checking if there's a command equivalent to _--download-archive_ for non-video material, or could this be appropriated for such purposes?

**Comment by SillyScribe95** [comment]
I made reference to this in the original post with "previously downloaded videos"; apologies if that wasn't clear.

Just checking if there's a command equivalent to --download-archive for non-video metadata, or could it be appropriated for such purposes?

**Comment by remitamine** [comment]
no, there is no such option.

**Comment by TomArrow** [comment]
I would also like this option if possible. I'm trying to download all descriptions from a channel, but many videos are restricted and due to DNS issues it skips random ones, so I have to sit through thousands of download attempts hoping it will get them all eventually.

**Comment by akaleeroy** [comment]
Please consider adding this option. I downloaded GBs worth of videos only to realise the playlist was ongoing. Renamed the files into something sane, so the only option now to continue where I left off is using a `--download-archive` log file. I'm not about to waste that much bandwidth on re-downloading just to produce the log.

The format for the `--download-archive` log file is

```
youtube AdL9Yd0lB_k
youtube YxBZbzIXNTg
youtube qsE_XxfFQ0w
youtube AdL9Yd0lB_k
...
```

As a workaround one could use `youtube-dl --get-id <channel/playlist url> >> archive.log` then prepend `youtube ` to each line.

**Comment by tieTYT** [comment]
Why is this, and many other issues closed without any response from the developers?
