### ISSUE TITLE
Youtube-dl php script

### ISSUE THREAD

**Issue by sikro94** [ytdl-org/youtube-dl#21877]
Hello,

I have been using youtube-dl for a long time, and I now want to install it on my dedicated server to make it easier for me to download content.

I created a php script that allows me to download the video of my choice to the server, then I download it to my computer, pretty cool!

I am now trying to improve this script in order to redirect only the feed to avoid uploading the video to the server. 

Example with this site: https://mpgun.com
**It seems to redirect the stream without downloading the video to the server. If you try to download a video that lasts 3 hours, the site will offer you the download immediately!**

I think ffmpeg allows you to do that, only I don't know where to start in the code. 

Do you have any idea how to set this up in php?

Thank you

**Comment by megustador** [comment]
Hi, any updates on this? I also want to kinda forward the stream, and not to download the video to the server, as the app will be on heroku and heroku fs is read-only.

**Comment by titirino159** [comment]
:)

**Comment by triplesixman** [comment]
> Hello,
> 
> I have been using youtube-dl for a long time, and I now want to install it on my dedicated server to make it easier for me to download content.
> 
> I created a php script that allows me to download the video of my choice to the server, then I download it to my computer, pretty cool!
> 
> I am now trying to improve this script in order to redirect only the feed to avoid uploading the video to the server.
> 
> Example with this site: https://mpgun.com
> **It seems to redirect the stream without downloading the video to the server. If you try to download a video that lasts 3 hours, the site will offer you the download immediately!**
> 
> I think ffmpeg allows you to do that, only I don't know where to start in the code.
> 
> Do you have any idea how to set this up in php?
> 
> Thank you

`    header('Content-Description: File Transfer');
    header('Cache-Control: must-revalidate');
    header('Pragma: public');
    header("Content-Disposition: attachment; filename=\"video.mp4\"");
    header("Content-Type: application/octet-stream");
    
    $cmd = "youtube-dl -o - [LINK]";
    $cmd = passthru($cmd, $status);`

If you want to use ffmpeg, you have to make a pipe at the end of the command like : `youtube-dl[...] | ffmpeg -i - -f mp3 -ab 192k -vn -`
