### ISSUE TITLE
go.discovery.com reverting to generic parser

### ISSUE THREAD

**Issue by cyperous** [ytdl-org/youtube-dl#21876]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.07.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: ['-f', 'bestvideo[ext=webm]+bestaudio/best', '--postprocessor-args=-strict unofficial', '--merge-output-format', 'mkv']
[debug] Custom config: []
[debug] Command-line args: ['https://go.discovery.com/tv-shows/naked-and-afraid-xl/full-episodes/goodbye-cruel-waterworld', '-F', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.16
[debug] Python version 3.7.4 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] goodbye-cruel-waterworld: Requesting header
WARNING: Falling back on generic information extractor.
[generic] goodbye-cruel-waterworld: Downloading webpage
[generic] goodbye-cruel-waterworld: Extracting information
ERROR: Unsupported URL: https://go.discovery.com/tv-shows/naked-and-afraid-xl/full-episodes/goodbye-cruel-waterworld
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3333, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://go.discovery.com/tv-shows/naked-and-afraid-xl/full-episodes/goodbye-cruel-waterworld

## Description

Do not close this as you did the others, the following url can be used in a browser without the need for credentials.

https://go.discovery.com/tv-shows/naked-and-afraid-xl/full-episodes/goodbye-cruel-waterworld

Something has changed within the last week or so.  Some urls on the site needed a cookie and others like above do not.  Both are not working. I don't need you to validate urls on this site that need a cookie.  if the parser works for the url above then the cookie one will too.

**Comment by AchillesPDX** [comment]
This appears to be fixed in the latest code (or at least attempted to be fixed) here: 
https://github.com/ytdl-org/youtube-dl/commit/3b446ab3519948980630e3328b971385826ffba8
but a new build hasn't been pushed out. No idea when builds get made unfortunately as I'm waiting to download the latest Savage Builds behind the scenes.

**Comment by Diegus83** [comment]
You can still use the version with the latest commit without waiting for a release. Check the developer notes. Basically you want to clone the repository to your machine and run
`python -m youtube_dl`
