### ISSUE TITLE
Is there a way to make youtube-dl remember what videos already been downloaded from the channel url?

### ISSUE THREAD

**Issue by hasnogaems** [ytdl-org/youtube-dl#21880]
Even if I physically delete the videos itself. I need to download thousands of videos from the channel but my drive capacity not allow to store it all at the same time, so I upload excess videos to cloud, but youtube-dl if I issue new command to download channel will download them again. I think it remember within command being executed but when you issue the same command again he forget. And I cannot finish all downloads within 1 command because some error usually occur andI need to reissue the command.

**Comment by dstftw** [comment]
`--download-archive`. Maybe you'll already learn how to use search?
