### ISSUE TITLE
Beginner Problem to DL PBS NOVA Apollo's Daring Mission, Can AnyOne Do This?

### ISSUE THREAD

**Issue by KermitJohnson** [ytdl-org/youtube-dl#21884]
Am a beginner but have been able to download PBS NOVA and other videos using youtube-dl-gui-0.4 port  (need port because can not install apps on the Win7 PC that use to dl videos).

Am unable to dl "Apollo's Daring Mission" https://www.pbs.org/wgbh/nova/video/apollos-daring-mission/  and do not know if it is me or the app that is causing this problem.

If can not dl, 
![1 Apollo's Daring Mission Queued ed](https://user-images.githubusercontent.com/53269207/61808634-ca17b200-ae09-11e9-8f09-d1d3add2eba7.png)
![2 Apollo's Daring Mission Error DL completed ed](https://user-images.githubusercontent.com/53269207/61808647-d00d9300-ae09-11e9-9c1b-78c4062364b5.png)

hope someone else is interested in this video and will make available for dl.

Have included screens

**Comment by Vangelis66** [comment]
@KermitJohnson 

NOVA links aren't supported by default by the `pbs.org` extractor: 
```
youtube-dl -F https://www.pbs.org/wgbh/nova/video/apollos-daring-mission/ =>

[pbs] Downloading JSON metadata
[pbs] apollos-daring-mission: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. Be 
sure to call youtube-dl with the --verbose flag and include its complete output.
```
Those links don't contain a **video ID string**, which is necessary for yt-dl's `pbs.org` extractor.

WORKAROUND: 

Head to the main PBS.org site and search there for the same NOVA video via its title, i.e. `Apollo's Daring Mission`: 

https://www.pbs.org/search/?q=Apollo%27s+Daring+Mission

First result should be the episode you're after, its URI is: 

https://www.pbs.org/video/apollos-daring-mission-ntnwii/

where `ntnwii` is the missing videoID; feed yt-dl this alternate link and it'll work: 
```
youtube-dl -F https://www.pbs.org/video/apollos-daring-mission-ntnwii/ => 

[pbs] Downloading JSON metadata
[pbs] apollos-daring-mission-ntnwii: Downloading webpage
[pbs] apollos-daring-mission-ntnwii: Downloading widget/partnerplayer page
[pbs] apollos-daring-mission-ntnwii: Downloading portalplayer page
[pbs] apollos-daring-mission-ntnwii: Downloading 0 video url info
[pbs] apollos-daring-mission-ntnwii: Downloading m3u8 information
[pbs] apollos-daring-mission-ntnwii: Downloading 1 video url info
[pbs] apollos-daring-mission-ntnwii: Checking http-730k video URL
[pbs] apollos-daring-mission-ntnwii: http-730k video URL is invalid, skipping
[pbs] apollos-daring-mission-ntnwii: Checking http-3000k video URL
[pbs] apollos-daring-mission-ntnwii: Checking http-2000k video URL
[pbs] apollos-daring-mission-ntnwii: http-2000k video URL is invalid, skipping
[pbs] apollos-daring-mission-ntnwii: Checking http-1100k video URL
[pbs] apollos-daring-mission-ntnwii: http-1100k video URL is invalid, skipping
[info] Available formats for 3019743416:
format code  extension  resolution note
0            mp4        unknown
hls-233      mp4        416x234     233k , avc1.64000c, mp4a.40.2
hls-461      mp4        480x270     461k , avc1.640015, mp4a.40.2
hls-848      mp4        640x360     848k , avc1.64001e, mp4a.40.2
hls-1261     mp4        768x432    1261k , avc1.64001e, mp4a.40.2
hls-2180     mp4        960x540    2180k , avc1.64001f, mp4a.40.2
hls-3202     mp4        1280x720   3202k , avc1.64001f, mp4a.40.2
http-3202    mp4        1280x720   3202k , avc1.64001f, mp4a.40.2 (best)
```
Remove the `-F` switch or assign your preferred mode via the `-f` option and bob's your ankle!

**Comment by Vangelis66** [comment]
@dstftw 

Let me first thank you once again publicly for the extreme service you and the rest of the developers are doing here! 👍 

Can I ask why the `pbs.org` extractor doesn't support subtitle fetching? 

With the sample video URI posted in my previous comment, 

`https://www.pbs.org/video/apollos-daring-mission-ntnwii/`

I had to resort to URL-sniffing to retrieve: 

`https://ga.video.cdn.pbs.org/videos/nova/b944b72b-6983-494c-927e-f3c132195d2f/2000075229/hd-16x9-mezzanine/6qzp6jjr_nova4518-captions.m3u8`

(WebVTT subtitle stream), which was converted to SRT via FFmpeg: 
```
ffmpeg -v 8 -stats -i "https://ga.video.cdn.pbs.org/videos/nova/b944b72b-6983-494c-927e-f3c132195d2f/2000075229/hd-16x9-mezzanine/6qzp6jjr_nova4518-captions.m3u8" -vn -an -c:s srt "Subs_en.srt"
```
Kindly consider implementing subtitles support... Many thanks in advance 😄

**Comment by KermitJohnson** [comment]
Vangelis66

Thank you for your detailed explanation!  

As a beginner for this app am overloaded with the command line options which is why I am using the gui.

Clarification:  guess I am slow.  For the workaround to work, seems I need to add to https://www.pbs.org/video/apollos-daring-mission-ntnwii/  the correct ending.

For the example above would you please post what the complete string should be to enable dl.

Also is there either written or video tutorials concerning PBS workarounds?
