### ISSUE TITLE
How to try except for ERROR: Did not get any data blocks

### ISSUE THREAD

**Issue by R01NDev** [ytdl-org/youtube-dl#21888]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I could not find a way to try catch this Error: ERROR: Did not get any data blocks
this error is occurring frequently when downloading from a large list of youtube channels. 
A normal try except doesn't do anything, Help would be appreciated

**Comment by m0ck69** [comment]
This error happens to me a lot and I don't download from youtube.

**Comment by R01NDev** [comment]
Sadly don't expect to get support here, all issues get closed for no reason. If you need help you should go to reddit youtubedl and ask there, lots of friendly people.
