### ISSUE TITLE
Age-Limit parameter does not work

### ISSUE THREAD

**Issue by Herbsel** [ytdl-org/youtube-dl#21883]
Hi There,

I'm using a fresh installation on my Synology DiskStation. On this i have a full root login with bash via IPKG. 

When I try to test the youtube-dl with a 3 titled Playlist, the first download normaly. But the aage restricted won't. I have looked every entry in Google but nothing had helped.

```
youtube-dl -f best -o "/volume1/video/%(title)s.%(ext)s" --age-limit 90 https://www.youtube.com/playlist?list=PLlpNfBXfCu0UoZ5EnYejgLd2kCAQ8QdVP

[download] Downloading video 2 of 3
[youtube] sQ5baa1r43M: Downloading webpage
[youtube] sQ5baa1r43M: Downloading embed webpage
[youtube] sQ5baa1r43M: Refetching age-gated info webpage
ERROR: Content Warning

DiskStation> youtube-dl --version                                                                                                                              
2019.07.16
```

Best regards
Herbsel

**Comment by dstftw** [comment]
Nothing to do with age limit. You must authenticate.
