### ISSUE TITLE
Error: "cannot create a file when that file already exists"

### ISSUE THREAD

**Issue by DrGogu** [ytdl-org/youtube-dl#21898]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have the latest version of youtube-dl (2019.07.16). Even in previous versions I would frequently get this error when downloading playlists from youtube. "cannot create a file when that file already exists", though no such files were there. It was a fresh download. I'm left with a file ending with TEMP in the filename, then the playlist download process is stopped because of that error. Any way to fix that? Thanks

**Comment by dstftw** [comment]
Post complete verbose log clearly demonstrating the issue.
