### ISSUE TITLE
How do I make youtube-dl use standard output

### ISSUE THREAD

**Issue by WhoseTheNerd** [ytdl-org/youtube-dl#21893]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How can I use standard output to pipe output to another programs input. Like so:
`$ youtube-dl -x --audio-format wav -o _ https://www.youtube.com/watch?v=n8X9_MgEdCg | sudo ./fm_transmitter -f 88.4 _`, with error code `Error: Cannot open _, file does not exist`
**How can I pipe youtube-dl output into ./fm_transmitter input?**

**Comment by remitamine** [comment]
it's a dash not an undersore, `-o -` not `-o _`.

**Comment by WhoseTheNerd** [comment]
`youtube-dl: error: Cannot download a video and extract audio into the same file! Use "-.%(ext)s" instead of "-" as the output template`

**Comment by remitamine** [comment]
which means that you can't extract audio and at the same time send it to standard output.
