### ISSUE TITLE
Error: "cannot create a file when that file already exists"

### ISSUE THREAD

**Issue by DrGogu** [ytdl-org/youtube-dl#21897]
I have the latest version of youtube-dl (2019.07.16).  Even in previous versions I would frequently get this error when downloading playlists from youtube.  "cannot create a file when that file already exists", though no such files were there. It was a fresh download.  I'm left with a file ending with TEMP in the filename, then the playlist download process is stopped because of that error.   Any way to fix that?  Thanks

**Comment by DrGogu** [comment]
At least provide an explanation why the thread is closed and what do next.
What you are doing is not very helpful to new users.

**Comment by dstftw** [comment]
Bother to read new issue template.
