### ISSUE TITLE
Support for downloading Facebook Stories

### ISSUE THREAD

**Issue by jdunn0** [ytdl-org/youtube-dl#21899]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.07.16**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I would like support for downloading [Facebook Stories](https://www.facebook.com/help/126560554619115) in youtube-dl.

Facebook Stories are similar to Snapchat, in that you create a video that stays up for 24 hours and is then deleted (though by default Facebook will archive your own stories so you can see them after that but no one else can).

**Comment by jdunn0** [comment]
I created a public Facebook Story [that can be seen here](https://www.facebook.com/stories/10214763852396598/UzpfSVNDOjEwMjE0NzY0MDM5NDQxMjc0/).

I used the Chromium Inspect tool to find the video element.
It says the XPath of the video element is `//*[@id="xt_uniq_1"]/div[2]/div[1]/div/video` so it seems Facebook sticks the video element under a few other elements in the source code.

The video element [source is here](https://video-sea1-1.xx.fbcdn.net/v/t42.1790-2/68196069_819994765061727_7245223413420667161_n.mp4?_nc_cat=107&efg=eyJybHIiOjMwMCwicmxhIjo1MTIsInZlbmNvZGVfdGFnIjoic3ZlX3NkIn0%3D&_nc_oc=AQkhO35ZPqoDnJTzIs5o2RATKfJAYcN2iBy5sKZ2w3hrJTW4qcxFMpQTli3yoQQ7wLE&rl=300&vabr=95&_nc_ht=video-sea1-1.xx&oh=26f525dc96f26f806950cc55da5deddb&oe=5D3A6841).

It would appear that the video URL points to an MP4 file.

Facebook Stories are either a picture or a video depending on the options you select, I'm only really interested in downloading the videos anyway and it seems possible to add support for that to youtube-dl to make things easier then using the Chromium inspect tool each time I want to download a video.

**Comment by morrowsend** [comment]
I can't download using the mp4 links as of today's date (at least). The page erros states  `URL signature expired ` in the link you provided and `Bad URL timestamp` when I visit a story and inspect the source for the full link.

**Comment by baptx** [comment]
Since some blob videos like Facebook stories and WebRTC livestreams cannot be downloaded with youtube-dl, I made a script here: https://gist.github.com/baptx/8a1549d91996a37378faca159b3adc17

**Comment by dirkf** [comment]
Continued in #32492.
