### ISSUE TITLE
ERROR:Unable to download webpage

### ISSUE THREAD

**Issue by BlueprintBT** [ytdl-org/youtube-dl#21896]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Running youtube-dl I'm getting the following output with errors :

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--download-archive', u'/home/giorgio/MyMusic/youtube-dl_done.txt', u'-i', u'-x', u'--audio-format', u'flac', u'--audio-quality', u'0', u'--playlist-start', u'1', u'--playlist-end', u'1', u'-o', u'/home/giorgio/MyMusic/AA-Singles/%(title)s.%(ext)s', u'https://www.youtube.com/watch?v=iy1YyXCVE5g']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.16
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-5-amd64-x86_64-with-debian-10.0
[debug] exe versions: ffmpeg 4.1.3-1, ffprobe 4.1.3-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {'ftp': 'http://', 'http': 'http://', 'https': 'http://'}
[youtube] iy1YyXCVE5g: Downloading webpage
ERROR: Unable to download webpage: <urlopen error no host given> (caused by URLError('no host given',))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 2724, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1164, in do_open
    raise URLError('no host given')

I have no firewalls configured on Debian 10 and no proxies.
I can't figure out what's wrong.
Can anybody help me?
Thank you in advance,
Giorgio.

**Comment by dstftw** [comment]
Fix your proxy environment.
