### ISSUE TITLE
Delete older videos from archive

### ISSUE THREAD

**Issue by amishmm** [ytdl-org/youtube-dl#21892]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I am using --download-archive option from 1-2 years now to record the videos already downloaded.

Now that list has grown to more than 10000 video IDs. How do I clean it up?

Is it stored randomly? Or in order of of download time? (looks like it)

Normally I download videos of last two days only (--dateafter today-1day). So is it safe to delete first 9500 video IDs making sure that it would still not be redownloaded? (because they will be older than 2 days anyway)

Thank you

**Comment by dstftw** [comment]
New entries are appended to the end of a file. This is all context you have.
