### ISSUE TITLE
Support for allcaster

### ISSUE THREAD

**Issue by mojz3sz** [ytdl-org/youtube-dl#21921]
## Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2019.07.27**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [ ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

-Single video: https://allcaster.pl/serial-online/halt-and-catch-fire/S01E03
## Description

Here's the output from the terminal:
youtube-dl -v 'https://allcaster.pl/serial-online/halt-and-catch-fire/S01E03'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://allcaster.pl/serial-online/halt-and-catch-fire/S01E03']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.27
[debug] Python version 3.7.3 (CPython) - Linux-4.19.61-1-MANJARO-x86_64-with-arch-Manjaro-Linux
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] S01E03: Requesting header
WARNING: Falling back on generic information extractor.
[generic] S01E03: Downloading webpage
[generic] S01E03: Extracting information
ERROR: Unsupported URL: https://allcaster.pl/serial-online/halt-and-catch-fire/S01E03
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3333, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://allcaster.pl/serial-online/halt-and-catch-fire/S01E03

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).

**Comment by mojz3sz** [comment]
Thx for so fast response but also sorry for taking your time.
Best regards

niedz., 28 lip 2019 o 23:02 Sergey M. <notifications@github.com> napisał(a):
