### ISSUE TITLE
Embedding subtitles ends in ERROR: Conversion failed!

### ISSUE THREAD

**Issue by thrdroom** [ytdl-org/youtube-dl#21929]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.07.27**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
./youtube-sync update PursuitofWonder
[youtube:channel] UC-tLyAaPbRZiYrOJxAGB7dQ: Downloading channel page
[youtube:playlist] UU-tLyAaPbRZiYrOJxAGB7dQ: Downloading webpage
[download] Downloading playlist: Uploads from Pursuit of Wonder
[youtube:playlist] UU-tLyAaPbRZiYrOJxAGB7dQ: Downloading page #1
[youtube:playlist] playlist Uploads from Pursuit of Wonder: Downloading 118 videos
[download] Downloading video 1 of 118
[youtube] oGVhOWqsBWM: Downloading webpage
[youtube] oGVhOWqsBWM: Downloading video info webpage
[info] Writing video subtitles to: SYNC/PursuitofWonder/ID/oGVhOWqsBWM.en.vtt
[download] Destination: SYNC/PursuitofWonder/ID/oGVhOWqsBWM.mkv
[download] 100% of 46.87MiB in 00:02
[ffmpeg] Embedding subtitles in 'SYNC/PursuitofWonder/ID/oGVhOWqsBWM.mkv'
ERROR: Conversion failed!
[download] Downloading video 2 of 118
ERROR: Interrupted by user
```

## Description

When i try to download all videos of a channel via [youtube-sync](https://github.com/PotcFdk/youtube-sync) i get the error "Conversion failed!" at the step "[ffmpeg] Embedding subtitles in 'SYNC/PursuitofWonder/ID/oGVhOWqsBWM.mkv'". Is this error youtube-dl or ffmpeg related? How to fix this?

The url of the video is [https://www.youtube.com/watch?v=oGVhOWqsBWM](https://www.youtube.com/watch?v=oGVhOWqsBWM) and the quality setting i use to download is "22/136+bestaudio[ext=m4a]/bestvideo[height<=720]+bestaudio[ext=m4a]/best[height<=720]"

**Comment by thrdroom** [comment]
WHY incomplete? What is missing?

**Comment by thrdroom** [comment]
WHY incomplete? What is missing? @dstftw

**Comment by dstftw** [comment]
Post the full verbose output.

**Comment by thrdroom** [comment]
> Post the full verbose output.

This IS the Full verbose output...i dont got more!!!!

**Comment by dstftw** [comment]
No, it's not. Read new issue template.

**Comment by thrdroom** [comment]
> No, it's not. Read new issue template.

ok updated. check above

**Comment by dstftw** [comment]
Do not hardcode extension in output template.
