### ISSUE TITLE
WARNING: Unable to extract video title

### ISSUE THREAD

**Issue by McFlat** [ytdl-org/youtube-dl#21936]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.07.27**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

same as other issues created about this ticket, heres a link to the most recent issue which was closed, but still the problem exists. https://github.com/ytdl-org/youtube-dl/issues/21934

**Comment by JolieOlsen** [comment]
Also getting this on the latest version after the push.

here's my verbose log:

C:\Users\user\Downloads>youtube-dl https://www.youtube.com/watch?v=RpOlTN2xdwg -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=RpOlTN2xdwg', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.07.27
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] RpOlTN2xdwg: Downloading webpage
[youtube] RpOlTN2xdwg: Downloading video info webpage
WARNING: Unable to extract video title
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r5---sn-n4v7sney.googlevideo.com/videoplayback?expire=1564467204&ei=pIs_XdCyAYbYwQGY87jQBA&ip=76.242.89.43&id=o-AHwF0VdrF4sz6H38WtglXPH8ZEH4-2BH7oCMXYP7WW4Y&itag=22&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-n4v7sney%2Csn-n4v7knl6&ms=au%2Crdu&mv=m&mvi=4&pl=20&initcwndbps=1088750&mime=video%2Fmp4&ratebypass=yes&dur=32.438&lmt=1472083032002671&mt=1564445517&fvip=5&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIhAKz2Bu-xWVpk9rp_KLMMPfp_W03toVKkiA-YuTymT3UJAiATXloysIICJdL9oWQTgKAmvKK0SYpgvjDqTO3XzbLHug%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgKTntdpK6btCTkSgtONv_xyLuS-A17c80NZsIoSzeJysCIQDpeX7epNuW34qCQ7V9QiyJPbG1P7lTMapppxSnHzI9yg%3D%3D'
[download] Destination: _-RpOlTN2xdwg.mp4
[download] 100% of 4.71MiB in 00:02

**Comment by holland11** [comment]
I think it may have been fixed here https://github.com/ytdl-org/youtube-dl/commit/8dbf751aa241475dd8a7a6d3040713b5874fd057 but I only use the .exe so I'm waiting for that to get rebuilt in a new release.

**Comment by botder** [comment]
It works for me on master branch, try this if you installed with pip:
```
pip install --upgrade git+https://github.com/ytdl-org/youtube-dl.git@master
```
