### ISSUE TITLE
Youtube video titles blank in version 2019.07.27

### ISSUE THREAD

**Issue by jeffjapan** [ytdl-org/youtube-dl#21937]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2019.07.27**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://youtu.be/cHEIYcs7LRs', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.27
[debug] Python version 3.7.4 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.1.4, ffprobe 4.1.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] cHEIYcs7LRs: Downloading webpage
[youtube] cHEIYcs7LRs: Downloading video info webpage
WARNING: Unable to extract video title
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r3---sn-8xgp1vo-cvne.googlevideo.com/videoplayback?expire=1564470442&ei=Spg_XZeUCpiU8wSf5rP4Aw&ip=108.41.168.66&id=o-ABKsg5QBbJSY7JlwtyPrtWCx7gqcNl7lxA1Wpl6GJ7Mm&itag=313&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-8xgp1vo-cvne%2Csn-ab5l6nsr&ms=au%2Crdu&mv=m&mvi=2&pl=16&pcm2=yes&initcwndbps=2046250&mime=video%2Fwebm&gir=yes&clen=812591363&dur=677.310&lmt=1563958863024256&mt=1564448712&fvip=6&keepalive=yes&c=WEB&txp=2316222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cpcm2%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRAIgD1PlcC-gcBkM6sFwQe7C8aTAUgqdvxMW_IOT2Wj-we4CIHF2VpkaXMQmnG6IW-LDHXzYMgWlh91ZTIK3wnjv5gpz&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAOdecZfCy0aJO5A7j0Qs8WiGTyA-meVv7qOdJz-gW4cyAiA5aSFXrFfBcwwMq9iEkD2diUeL7Tev7B9_UWvJEVoVRg%3D%3D&ratebypass=yes'
[download] Resuming download at byte 22986591
[download] Destination: _-cHEIYcs7LRs.f313.webm

## Description

For video's that I try after upgrading to 2019.07.27, the video's title is saved as _

Ex:
youtube-dl https://youtu.be/cHEIYcs7LRs
   [youtube] cHEIYcs7LRs: Downloading webpage
   [youtube] cHEIYcs7LRs: Downloading video info webpage
   WARNING: Unable to extract video title

Video's name will be:
_-cHEIYcs7LRs.webm

Video's name should be something like:
Dell XPS 15 7590 REVIEW - The Perfect Laptop-cHEIYcs7LRs.webm

**Comment by kuroblack** [comment]
confirmed, same issue using

youtube-dl.exe --console-title --no-progress --no-check-certificate --ignore-errors --playlist-start 1 -xf bestaudio "RDPRy59ec5csQ"
