### ISSUE TITLE
Please tell me what is the tool you are used to build youtube-dl.exe?

### ISSUE THREAD

**Issue by ssc19940105** [ytdl-org/youtube-dl#21941]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Excuse me? Can I ask a question? What is the tool you are used to build youtube-dl.exe?

**Comment by ssc19940105** [comment]
Sorry.I want to ask how to pack python projrct to single exe file like this (youtube-dl.exe).

**Comment by dstftw** [comment]
`py2exe`.

**Comment by ssc19940105** [comment]
Thanks
