### ISSUE TITLE
youtube titles are broken

### ISSUE THREAD

**Issue by hakanb78** [ytdl-org/youtube-dl#21947]
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2019.07.30**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Hi, 
Youtube-dl doesn't get the youtube titles for nearly last 24 hours. It seems they've changed something on youtube side causing this feature to break. FYI

Thanks

**Comment by jcguu95** [comment]
I solved this problem by using the latest version (2019-08-02): https://github.com/ytdl-org/youtube-dl/releases/tag/2019.08.02/
