### ISSUE TITLE
ERROR: Unable to extract uploader name

### ISSUE THREAD

**Issue by neomohsen** [ytdl-org/youtube-dl#21952]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2019.07.30**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

$ youtube-dl https://www.youtube.com/watch?v=OtRW-CY_iTA
[youtube] OtRW-CY_iTA: Downloading webpage
[youtube] OtRW-CY_iTA: Downloading video info webpage
WARNING: Unable to extract video title
[youtube] OtRW-CY_iTA: Extracting video information
ERROR: Unable to extract uploader name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by choward232** [comment]
Anyone resolve this issue?

**Comment by alex1a** [comment]
I'm having the same issue with ubuntu18, installing youtube-dl from apt.
I uninstall it, download from source and work (https://github.com/ytdl-org/youtube-dl/blob/master/README.md#installation).

**Comment by PrabhanshuAttri** [comment]
Installing youtube-dl from apt can replicate the issue.

Try uninstalling using the following
```
sudo apt-get purge youtube-dl
```

Then reinstall using pip
```
sudo python3 -m pip install youtube-dl
```
This installed v2019.09.28 for me and the issue got fixed.

**Comment by aveetron** [comment]
`sudo apt-get --only-upgrade install youtube-dl`
