### ISSUE TITLE
How do I use the modeules ffmpeg and ffprobe correctly? I have issues with the mp3 files. 

### ISSUE THREAD

**Issue by l1k2j3h4g5** [ytdl-org/youtube-dl#21958]
## Checklist
- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question
In the readme it says:

     -x, --extract-audio         Convert video files to audio-only files
                                 (**requires ffmpeg or avconv and ffprobe or
                                 avprobe**)

So I included that at the top of my node.js file:

    const ffmpeg = require('ffmpeg');
    const ffprobe = require('ffprobe');

In terminal I ran

    $ npm install ffmpeg -save
    $ npm install ffprobe -save

which gave me a package json file of: 

    "dependencies": {
       "ffmpeg": "0.0.4",
       "ffprobe": "^1.1.0",
       "youtube-dl": "1.13.1"
     },

My function that then downloads the file as mp3 and uploads it to S3 is:

    exports.handler = function(event, context, cb) {   
      if (!event.videoUrl) {
        return cb(new Error('videoUrl missing in event'));
      }
      const s3 = new AWS.S3({apiVersion: '2006-03-01'});
      const passtrough = new stream.PassThrough();

      var downloadOptions = ['--extract-audio', '--audio-format', 'mp3']

      const dl = youtubedl(event.videoUrl, downloadOptions, {maxBuffer: Infinity});
      dl.once('error', (err) => {
        cb(err);
      });
      const key = `${context.awsRequestId}.mp3`;
      const upload = new AWS.S3.ManagedUpload({
        params: {
          Bucket: process.env.BUCKET_NAME,
          Key: key,
          Body: passtrough
        },
        partSize: 1024 * 1024 * 64 // in bytes
      });

      upload.on('httpUploadProgress', (progress) => {
        console.log(`[${event.videoUrl}] copying video ...`, progress);
      });

      upload.send((err) => {
        if (err) {
          cb(err);
        } else {
          cb(null, {
            bucketName: process.env.BUCKET_NAME,
            key,
            url: `s3://${process.env.BUCKET_NAME}/${key}`
          });
        }
      })
      

      dl.pipe(passtrough);
    }

It downloads the file and saved it as `.mp3` as expected. 

So how do I know there is an issue? 

Every time I try to use that file in an AWS Transcribe Job it says:

> The media format provided does not match the detected media format.

and when I download the file and try to run it in VLC or iTunes it forces the player to close and does not play. 

Do I need to do anything else to get the encoding correct?

**Comment by dstftw** [comment]
Wrong forum.

**Comment by l1k2j3h4g5** [comment]
is this the "question" section for the module "Youtube-dl" ?

**Comment by dstftw** [comment]
No, youtube-dl has nothing to do with nodejs modules.
