### ISSUE TITLE
Possible issues with extracting tiles

### ISSUE THREAD

**Issue by Jesse415** [ytdl-org/youtube-dl#21965]
## Checklist

- [X ] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
When I type in cli $ youtube-dl -e (or --get-title) https://...somevideo... I recieve a WARNING: Unable to extract video title. Is this a bug or something I am doing wrong? I dont think this happened before. Thank you

**Comment by appleton-tom** [comment]
The latest version [2019.07.30] seemed to fix the lack of title, but the title is still unavailable on a video labelled as "Age-restricted video (based on Community Guidelines)".

Command line -
youtube-dl  -v --skip-download  --write-description  https://www.youtube.com/watch?v=X8f1gDssdi4

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--skip-download', '--write-description', 'https://www.youtube.com/watch?v=X8f1gDssdi4']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2019.07.30
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-72324-g8ce564e, ffprobe N-72324-g8ce564e
[debug] Proxy map: {}
[youtube] X8f1gDssdi4: Downloading webpage
[youtube] X8f1gDssdi4: Downloading embed webpage
[youtube] X8f1gDssdi4: Refetching age-gated info webpage
WARNING: Unable to extract video title
WARNING: unable to extract uploader name
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video description to: _-X8f1gDssdi4.description

**Comment by donmiyamar** [comment]
This should still be open. It still doesn't work correctly, even with the latest version

**Comment by sarim** [comment]
Issue not is not solved for age restricted videos.
