### ISSUE TITLE
Looking to ask if https://youtube-dl.org/ is a fraudulent impersonation website

### ISSUE THREAD

**Issue by MystesofEternity** [ytdl-org/youtube-dl#21974]
#5805  Checklist
* [x] I'm asking a question
* [x] I've looked through the README and FAQ for similar questions
* [x] I've searched the bugtracker for similar questions including closed ones

## Question
As the title says, I would like to confirm if this is the case. I tried to scan the website through Virustotal and it seems good but I want to know if this is supposed to be a new official website for youtube dl on a better looking domain or not.
https://youtube-dl.org/

Thanks for the hard work!

**Comment by dstftw** [comment]
This is our domain.
