### ISSUE TITLE
Skylinewebcam wrong AR 5:4

### ISSUE THREAD

**Issue by avagraha** [ytdl-org/youtube-dl#21973]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

https://www.skylinewebcams.com/it/webcam/italia/liguria/imperia/festival-sanremo-ariston.html

i.e.
https://hddn01.skylinewebcams.com/live.m3u8?a=jqg97hucspn4285kkhp9hqvj75
(or obviously a refreshed one!!)

Why this video (better ALL the videos) in the browser runs with the correct AR (by 
eyes I suppose 16:9)
https://postimg.cc/w3x71R93

while the video (all the videos!) downloaded by YTDL runs with a very wrong AR (5:4!!!): see the shape of the people here, I guess that they look in a unacceptable 
stretched way:
https://postimg.cc/z39Z9425

I doubt that this is expected behaviour both of YTDL and skylinewebcam 
developers, but at the same time I doubt that Firefox is doing misteriouses in real time postprocessing to add amelioraments to the AR. What to do?
I wonder if all the users never noticed this strange AR..in the (original 
?) stream and how they can accept it. Thanks for verifying and for some explanations or a good resolution. In the meantime i send the link to sky people and to the owner of the theatre but i am sceptic about a solution from theirside. And all the other mountain wecam? Are they all with wrong setyings at source? I have to admit that i dont see compliants. No idea how to solve this terrific 5:4. If the browser displays the same AR then ok i have nothing to say but since the browser displays the same stream perfectly have you a command to force the right 16:9?
Log here
C:\Users\>y -v https://www.skylinewebcams.com/it/webcam/italia/liguria
/imperia/festival-sanremo-ariston.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.skylinewebcams.com/it/webcam
/italia/liguria/imperia/festival-sanremo-ariston.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.07.30
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-94137-g89b9690-Reino, ffprobe N-94137-g89b96
90-Reino, rtmpdump 2.4
[debug] Proxy map: {}
[SkylineWebcams] festival-sanremo-ariston: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://hddn01.skylinewebcams.com/live.m3u8
?a=s3ke92jse6ka5c7tkid9bge9k0'
[download] Destination: Live Webcam Sanremo - Teatro Ariston 2019-08-01 13_
36-festival-sanremo-ariston.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "Accept-L
anguage: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (K
HTML, like Gecko) Chrome/73.0.3683.55 Safari/537.36
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
" -i 
"https://hddn01.skylinewebcams.com/live.m3u8?a=s3ke92jse6ka5c7tkid9bge
9k0" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:Live Webcam Sanremo - Teat
ro Ariston 2019-08-01 13_36-festival-sanremo-ariston.mp4.part"
[tcp @ 009df940] Starting connection attempt to 37.187.169.72 port 443
[tcp @ 009df940] Successfully connected to 37.187.169.72 port 443
[hls @ 009d8bc0] Skip ('#EXT-X-VERSION:3')
[hls @ 009d8bc0] HLS request for url 
'https://hddn01.skylinewebcams.com/084
10102GP8X-1564659349987.ts', offset 0, playlist 0
[hls @ 009d8bc0] Opening 
'https://hddn01.skylinewebcams.com/08410102GP8X-15
64659349987.ts' for reading
[tcp @ 00ecf780] Starting connection attempt to 37.187.169.72 port 443
[tcp @ 00ecf780] Successfully connected to 37.187.169.72 port 443
[hls @ 009d8bc0] HLS request for url 
'https://hddn01.skylinewebcams.com/084
10102GP8X-1564659357905.ts', offset 0, playlist 0
[hls @ 009d8bc0] Opening 
'https://hddn01.skylinewebcams.com/08410102GP8X-15
64659357905.ts' for reading
[tcp @ 00ee9940] Starting connection attempt to 37.187.169.72 port 443
[tcp @ 00ee9940] Successfully connected to 37.187.169.72 port 443
[h264 @ 00f034c0] Reinit context to 1280x1024, pix_fmt: yuv420p
[hls @ 009d8bc0] max_analyze_duration 5000000 reached at 5000000 microsecon
ds st:0
[hls @ 009d8bc0] Could not find codec parameters for stream 1 (Audio: aac (
[15][0][0][0] / 0x000F), 0 channels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' opt
ions
Input #0, hls, from 
'https://hddn01.skylinewebcams.com/live.m3u8?a=s3ke92js
e6ka5c7tkid9bge9k0':
  Duration: N/A, start: 25172.700000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High), 1 reference frame ([27][0][0][0] / 0x0
01B), yuv420p(left), 1280x1024, 11 fps, 11 tbr, 90k tbn, 180k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Live Webcam Sanremo - Teatro Ariston 2019-08-01 13
_36-festival-sanremo-ariston.mp4.part':
  Metadata:
    encoder         : Lavf58.28.101
    Stream #0:0: Video: h264 (High), 1 reference frame (avc1 / 0x31637661),
 yuv420p(left), 1280x1024 (0x0), q=2-31, 11 fps, 11 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
[hls @ 009d8bc0] HLS request for url 
'https://hddn01.skylinewebcams.com/084
10102GP8X-1564659365897.ts', offset 0, playlist 0
[https @ 00ecd500] Opening 
'https://hddn01.skylinewebcams.com/08410102GP8X-
1564659365897.ts' for reading
frame=   89 fps=0.0 q=-1.0 size=     512kB time=00:00:08.00 bitrate= 524.3k
frame=  121 fps= 96 q=-1.0 size=     768kB time=00:00:10.90 bitrate= 576.8k
frame=  152 fps= 83 q=-1.0 size=    1024kB time=00:00:13.72 bitrate= 611.1k
frame=  177 fps= 75 q=-1.0 size=    1280kB time=00:00:16.00 bitrate= 655.4k
frame=  209 fps= 73 q=-1.0 size=    1536kB time=00:00:18.90 bitrate= 665.5k
frame=  240 fps= 70 q=-1.0 size=    1792kB time=00:00:21.72 bitrate= 675.7k
 bytes);
Total: 352 packets (2749404 bytes) muxed
[AVIOContext @ 085f0c00] Statistics: 2 seeks, 14 writeouts
[AVIOContext @ 00ed4fc0] Statistics: 2135304 bytes read, 0 seeks
[AVIOContext @ 00ef3040] Statistics: 713272 bytes read, 0 seeks
[AVIOContext @ 083c0e00] Statistics: 550 bytes read, 0 seeks
[AVIOContext @ 00ebae40] Statistics: 550 bytes read, 0 seeks
Exiting normally, received signal 2.
[ffmpeg] Interrupted by user
[ffmpeg] Downloaded 2621488 bytes
[download] 100% of 2.50MiB in 00:18

**Comment by dstftw** [comment]
Original stream resolution is 1280x1024. Most likely they rescale on fly.
