### ISSUE TITLE
(duplicate) Site request: CTC.RU (videomore.ru?)

### ISSUE THREAD

**Issue by SlazE888** [ytdl-org/youtube-dl#21981]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.08.02**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

## Description

#10717 need to be reopened. I'm added a new comment, have a look please.

**Comment by dstftw** [comment]
Video is DRM protected. Stop posting duplicates. This is your last warning.
