### ISSUE TITLE
Need a way to detect videos with missing fragments

### ISSUE THREAD

**Issue by hofmand** [ytdl-org/youtube-dl#21989]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.08.02**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I believe I have downloaded videos with missing fragments. Is there a quick way for youtube-dl to detect which downloaded videos were assembled from missing fragments so I can try to download them again?

From now on, I'm using `--abort-on-unavailable-fragment` but I'm looking for some automated process to verify my previously downloaded videos.

**Comment by dstftw** [comment]
Not possible.
