### ISSUE TITLE
YouTube update, unable to get filename~

### ISSUE THREAD

**Issue by lib-xdown** [ytdl-org/youtube-dl#21998]
YouTube update, unable to get filename!

**Comment by particl3s** [comment]
I'm not sure if this is related but mine states 'Unable to extract video title' 
System spec: 
OS: Manjaro 18.0.3 Illyria
Kernel: x86_64 Linux 4.19.24-1-MANJARO
DE: KDE 5.55.0 / Plasma 5.15.1
CPU: Intel Core i5-2400S @ 4x 3.3GHz [62.0°C]
GPU: AMD TURKS (DRM 2.50.0 / 4.19.24-1-MANJARO, LLVM 7.0.1)
RAM: 1918MiB / 3920MiB

> youtube-dl -v https://www.youtube.com/watch\?v\=fruLQhn4wWg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=fruLQhn4wWg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 3.7.2 (CPython) - Linux-4.19.24-1-MANJARO-x86_64-with-arch-Manjaro-Linux
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] fruLQhn4wWg: Downloading webpage
[youtube] fruLQhn4wWg: Downloading video info webpage
WARNING: Unable to extract video title
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r1---sn-gvbxgn-tt1es.googlevideo.com/videoplayback?expire=1564909330&ei=skpGXeu5H9D8kgax0r6ABw&ip=2607%3A9880%3A1998%3A1a%3A%3A2&id=o-AFq_BGTLsv6BEsGXeu002h8OyOe6a5mVxUvCCvIjCj8G&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-gvbxgn-tt1es%2Csn-t0a7ln7d&ms=au%2Conr&mv=m&mvi=0&pl=32&initcwndbps=1512500&mime=video%2Fwebm&gir=yes&clen=92070387&dur=1056.160&lmt=1547334150443098&mt=1564887584&fvip=1&keepalive=yes&c=WEB&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRgIhALnZh0o7Wg_vXOOjr0y0o-8DjTdm1H0oyLJ2n3vGvcRPAiEAlo2J896-S26H06mOpCjGuORkTn-NqbsUahyn78kLfDU%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgXul_O6i4yhiJG3PabilxKxCEUeRW6AriTfsD-RaB3u8CIDB8bIw20wIuifCJKQiJa68cXh1eVLT7kEIXCod5U1g8&ratebypass=yes'
[download] Destination: _-fruLQhn4wWg.f248.webm
[download] 100% of 87.81MiB in 00:09
[debug] Invoking downloader on 'https://r1---sn-gvbxgn-tt1es.googlevideo.com/videoplayback?expire=1564909330&ei=skpGXeu5H9D8kgax0r6ABw&ip=2607%3A9880%3A1998%3A1a%3A%3A2&id=o-AFq_BGTLsv6BEsGXeu002h8OyOe6a5mVxUvCCvIjCj8G&itag=251&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-gvbxgn-tt1es%2Csn-t0a7ln7d&ms=au%2Conr&mv=m&mvi=0&pl=32&initcwndbps=1512500&mime=audio%2Fwebm&gir=yes&clen=16785292&dur=1056.181&lmt=1547337209116875&mt=1564887584&fvip=1&keepalive=yes&c=WEB&txp=5411222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIhAL1WfmkpdIvqKVtk0UZM37Pu9t8qnGLLEMeCHozitcmLAiAUqO4HV0w5mgiCCYEveHem22QLHm_h1WwlirLHHMpsMg%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgXul_O6i4yhiJG3PabilxKxCEUeRW6AriTfsD-RaB3u8CIDB8bIw20wIuifCJKQiJa68cXh1eVLT7kEIXCod5U1g8&ratebypass=yes'
[download] Destination: _-fruLQhn4wWg.f251.webm
[download] 100% of 16.01MiB in 00:01
[ffmpeg] Merging formats into "_-fruLQhn4wWg.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:_-fruLQhn4wWg.f248.webm -i file:_-fruLQhn4wWg.f251.webm -c copy -map 0:v:0 -map 1:a:0 file:_-fruLQhn4wWg.temp.webm
Deleting original file _-fruLQhn4wWg.f248.webm (pass -k to keep)
Deleting original file _-fruLQhn4wWg.f251.webm (pass -k to keep)
