### ISSUE TITLE
How to bypass ": Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError())"

### ISSUE THREAD

**Issue by adamwoo2444** [ytdl-org/youtube-dl#21995]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2019.08.02**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by adamwoo2444** [comment]
please help!!!!

**Comment by dstftw** [comment]
Stop posting duplicates. This is your last warning.
