### ISSUE TITLE
VideoOnDemand from ivi.ru issue

### ISSUE THREAD

**Issue by SlazE888** [ytdl-org/youtube-dl#21991]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.ivi.ru/watch/137070']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.08.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[ivi] 137070: Downloading video JSON
ERROR: Unable to download video 137070: Контент 137070 недоступен для просмотра на площадке s183
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\ivi.py", line 108, in _real_extract
youtube_dl.utils.ExtractorError: Unable to download video 137070: Контент 137070 недоступен для просмотра на площадке s183
```

## Description

The video plays fine in Google Chrome browser. But if I'm running youtube-dl I got this error: "**Content 137070 is not available for viewing on site s183**"

**Comment by SlazE888** [comment]
I have the same error on this movie:
 https://www.ivi.ru/watch/100108

**Comment by SlazE888** [comment]
@remitamine thank you I'm appreciate it! But istill can't play such videos, i got this log:

_[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.ivi.ru/watch/100108']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.11.22
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[ivi] 100108: Downloading video JSON
ERROR: This feature does not work from bundled exe. Run youtube-dl from sources.

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh
33\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh
33\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh
33\build\youtube_dl\extractor\ivi.py", line 146, in _real_extract
youtube_dl.utils.ExtractorError: This feature does not work from bundled exe. Ru
n youtube-dl from sources._

is the any way to watch through .EXE-file ?

**Comment by dstftw** [comment]
No, as clearly said in the error message.

**Comment by SlazE888** [comment]
> No, as clearly said in the error message.
@dstftw thank you for answering
