### ISSUE TITLE
Egghead not working

### ISSUE THREAD

**Issue by nikolai-mitnik** [ytdl-org/youtube-dl#22004]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

Hi guys, Egghead courses are not working, I am using cookies to retrive the videos, also tried with username/password it´s the same, the thing apparently is that now egghead it like lazy loading video fragments m4s files.

The error I 'am getting is quite old:

ERROR: An extractor error has occurred. (caused by KeyError(u'media_urls',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/egghead.py", line 98, in _real_extract
    for _, format_url in lesson['media_urls'].items():
KeyError: u'media_urls'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'media_urls',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thanks for your help!

Nikolai.

**Comment by nikolai-mitnik** [comment]
@remitamine Where is stored the verbose logs? I used --verbose, but don´t know if there are more logs than I pasted, where can I look ? Thanks.

**Comment by remitamine** [comment]
in the CMD/Terminal output.

**Comment by nikolai-mitnik** [comment]
@remitamine I updated the log.

**Comment by remitamine** [comment]
the lesson you're trying to download is Pro Lesson(require a Full Access Membership).

**Comment by nikolai-mitnik** [comment]
@remitamine This one is free in the network tab is doing the same.
https://egghead.io/lessons/gatsby-set-up-to-create-data-driven-pages-in-gatsby

**Comment by remitamine** [comment]
```
youtube-dl https://egghead.io/lessons/gatsby-set-up-to-create-data-driven-pages-in-gatsby
[egghead:lesson] gatsby-set-up-to-create-data-driven-pages-in-gatsby: Downloading JSON metadata
[egghead:lesson] 4956: Downloading m3u8 information
[egghead:lesson] 4956: Downloading MPD manifest
[dashsegments] Total fragments: 105
[download] Destination: Set up to Create Data Driven Pages in Gatsby-4956.fdash-9b44f8ab-f088-4b97-a85a-34be0dbf890d.mp4
[download]   0.3% of ~45.44MiB at 514.75KiB/s ETA 16:11
```
next time when you say something is not working, prove that it's not working with youtube-dl while it's working in the browser.

**Comment by nikolai-mitnik** [comment]
@remitamine Sorry, seems this is not working for PRO courses only, it downloads first 2 and then stops with the error I posted, can´t post login credentials becuase are not mine.
