### ISSUE TITLE
latest release isn't latest

### ISSUE THREAD

**Issue by btmurrell** [ytdl-org/youtube-dl#22006]
I am getting what seems like a common error: "token" parameter not in video info for unknown reason".  My log is below, which shows youtube-dl version 2019.01.30.1.  Your website says latest version is 2019.08.02.  When I install from your bins on your release page or from `curl -L https://yt-dl.org/downloads/latest/youtube-dl ` i get the same old january version.  so i think your "latest" bins just need to be updated.

## Checklist

- [x ] I'm reporting a broken site support issue
- [no, see above ] I've verified that I'm running youtube-dl version **2019.08.02**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl --verbose https://www.youtube.com/watch?v=ciRrrC5OS6c
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=ciRrrC5OS6c']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.30.1
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-55-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube] ciRrrC5OS6c: Downloading webpage
[youtube] ciRrrC5OS6c: Downloading video info webpage
ERROR: ciRrrC5OS6c: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/merl/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/home/merl/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/home/merl/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1689, in _real_extract
    video_id=video_id)
ExtractorError: ciRrrC5OS6c: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

the "token" error seems to be often reported. This bug is about getting the latest bins in your release page so I can upgrade.

THANKS!!

**Comment by Hrxn** [comment]
Really? Try downloading from `https://yt-dl.org/downloads/latest/youtube-dl` again and compare the checksums against the checksums files from here, for example:
https://github.com/ytdl-org/youtube-dl/releases/tag/2019.08.02/
