### ISSUE TITLE
Not make archive file.

### ISSUE THREAD

**Issue by madhavnikam** [ytdl-org/youtube-dl#22005]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by madhavnikam** [comment]
When I try to following command in that command all things are working good except --download-archive. No error and no warning show by youtube-dl. But not creating archive file. If I try with any other previous archive file then youtube-dl check and skip that URLs but same thing I try with fresh command then it can not make any file.

youtube-dl --write-description --skip-download --youtube-skip-dash-manifest --download-archive lme.txt -wcia lm.txt

**Comment by dstftw** [comment]
Download archive will not work with `--skip-download`.
