### ISSUE TITLE
URL from watch later list (but not dependent on access to that list) not working

### ISSUE THREAD

**Issue by chrisgraham** [ytdl-org/youtube-dl#22016]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.08.02**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

$ /usr/local/bin/youtube-dl --newline -i -o "/home/chrisgraham/Music/%(title)s.%(ext)s" -x --audio-format mp3 --audio-quality 0 --ignore-config --hls-prefer-native --add-metadata "https://www.youtube.com/watch?v=d5xl1uG2BTU&list=WL&index=2" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--newline', u'-i', u'-o', u'/home/chrisgraham/Music/%(title)s.%(ext)s', u'-x', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'--ignore-config', u'--hls-prefer-native', u'--add-metadata', u'https://www.youtube.com/watch?v=d5xl1uG2BTU&list=WL&index=2', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.02
[debug] Python version 2.7.16 (CPython) - Linux-5.0.0-23-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:watchlater] Downloading playlist WL - add --no-playlist to just download video d5xl1uG2BTU
[youtube:watchlater] WL: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 3141, in _real_extract
    _, playlist = self._extract_playlist('WL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2644, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist does not exist.

## Description

I think if you copy a URL to a video from your watch later, and don't give youtube-dl your authentication details, it should recognise that you just want one individual video and to ignore list=WL. For 2 reasons:
1) Doing something sensible/intuitive that works is better in general than failing, especially for this specific case where we have a reasonable idea what the user is trying to do.
2) I was using the YouTube DL GUI frontend, which hid the hints about "This playlist does not exist." and "--no-playlist". I could configure YouTube DL GUI to use "--no-playlist" (and I will), but I think it's reasonable for YouTube DL GUI to not need to pass any extra options, defaults should be smarter.

**Comment by dstftw** [comment]
No, it should not since this will break clear and consistent behavior to download playlist by default.
