### ISSUE TITLE
How to download only audio from a url list written in a text file?

### ISSUE THREAD

**Issue by milanpanin** [ytdl-org/youtube-dl#22014]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I can't find how to download only audio from a url list written in a text file. With command youtube-dl -a download.txt get video only, but I need audo only.

**Comment by dstftw** [comment]
FAQ on `--batch-file`, `--extract-audio`.
