### ISSUE TITLE
YT: PT subtitles have a lot of extra text, other langs are ok, PT sub on youtube is ok too

### ISSUE THREAD

**Issue by astraetech** [ytdl-org/youtube-dl#22010]
Hi,

This video on youtube https://www.youtube.com/watch?v=y3OzY9q8QOw has auto subs in portuguese. When downloaded, vtt for pt looks like this:
```
WEBVTT
Kind: captions
Language: pt

00:00:13.580 --> 00:00:18.970 align:start position:0%
 
ae

00:00:18.970 --> 00:00:18.980 align:start position:0%
 
 

00:00:18.980 --> 00:00:34.680 align:start position:0%
 
ano
```

In english the vtt is like this:
```
WEBVTT
Kind: captions
Language: en

00:00:13.580 --> 00:00:16.580
 ae 

00:00:18.980 --> 00:00:21.550
 year 
```
The command run is: youtube-dl --download-archive "archive.log" -i -v --add-metadata --write-info-json --write-annotations --sub-lang en,es,pt,sv,fr  --skip-download --embed-subs --write-sub  --write-auto-sub --geo-bypass --restrict-filenames  --write-all-thumbnails --embed-thumbnail --match-filter "playlist_title != 'Liked videos' & playlist_title != 'Favorites' & playlist_title!='Vlogs' " -f "(bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec=vp9.2][height>=1080][fps>30]/bestvideo[vcodec=vp9][height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec=vp9.2][height>=1080]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec=vp9.2][height>=720][fps>30]/bestvideo[vcodec=vp9][height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec=vp9.2][height>=720]/bestvideo[vcodec=vp9][height>=720]/bestvideo[height>=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best" --merge-output-format mkv -o "%(playlist_uploader)s/%(playlist)s/%(playlist)s - %(title)s - %(upload_date)s - (%(duration)ss) [%(resolution)s] - %(id)s.%(ext)s" "https://www.youtube.com/watch?v=y3OzY9q8QOw" 

When playing the final MKV all that extra text in vtt just clutters the screen. Just happens for Portuguese so far I don't know why. Doesn't seem to be the overlapped subs issue.

Would be great if somebody could look into this! Thanks for the great program!

**Comment by dstftw** [comment]
This is what served by Youtube.

**Comment by astraetech** [comment]
But when played on youtube those same subtitles are displayed correctly on the screen. So yt-dl is getting the subs from somewhere else? Maybe it's the sub format issue?
