### ISSUE TITLE
Help with "EMBEDDING YOUTUBE-DL" 

### ISSUE THREAD

**Issue by captaindavepdx** [ytdl-org/youtube-dl#22015]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

### Hello YouTube-DL team! 

**Thank you for building and sharing such an incredibly useful repository!**

I embedded the youtube-dl executable file into a Swift MacOS application. Currently, the download progress prints to the XCode console, but I want to display it in the user interface, so I need access to the actual progress values. `[K[download]  21.6% of ~801.40KiB at 45.19KiB/s ETA 00:05`

I tried to access the `stdout` value from Swift, but it only prints a few values related to download status, such as `[youtube] vGr_QQe_aAw: Downloading webpage`. The rest of the values are blank strings, `""`.

I've read through the faqs, open/closed issues, and searched online. [EMBEDDING YOUTUBE-DL](https://github.com/ytdl-org/youtube-dl#embedding-youtube-dl) from `README.md` was mentioned in a post from the issues section. So, I've been trying to figure out how to implement that from Swift for the past several hours, but I'm not making progress.

I'm a new developer. My Swift is decent, my JavaScript is ok, but I'm entirely new to Python. 

I suspect I can change something in a Python file that will send "download progress" to `stdout`. But, I don't know if it's that simple, or where or how to start doing that.

Could you please help point me in the right direction? =]

**Comment by dstftw** [comment]
Embedding guide contains clear example on how to install a progress hook.

**Comment by captaindavepdx** [comment]
Hi @dstftw ,

Are you referring to the embedding guide in the readme? If so, it wasn't clear to me, which is why I asked for help implementing it. https://github.com/ytdl-org/youtube-dl#embedding-youtube-dl

**Comment by captaindavepdx** [comment]
Hi @dstftw , I just completed the Python 3 course on Codecademy. Now, I'm familiar with the language, but it's still unclear how to implement the example.  I'll continue to research, but any direction, suggestion, or advice would be helpful.
