### ISSUE TITLE
avoid downloading videos for data-mining purposes

### ISSUE THREAD

**Issue by mathematicalmichael** [ytdl-org/youtube-dl#22024]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

It seems like youtube-dl is a great tool for the following task:
- given a channel name, 
- find all videos and playlists
- compile them into a list of hyperlinks

for use-cases such as mine (where I do not need to download the videos but do need the hyperlinks) in order to scrape data from each video (description/likes/length, etc). 

My question is, how can this be accomplished (the avoiding downloads part)? Is there already some sort of syntax pattern to accomplish this? I could not find such a thing in the documentation, and trying to parse data using tools like BeautifulSoup for python only grab the first 100 videos per playlist.

I have found syntax in youtube-dl to grab all videos from a channel, but again, I don't want to download them, just save the hyperlinks to a file.

**Comment by dstftw** [comment]
Have you even read FAQ?
```
--skip-download                  Do not download the video
```

**Comment by mathematicalmichael** [comment]
for anyone who might find it useful coming across this issue in the future:
`youtube-dl -o '%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' \ 
  https://www.youtube.com/user/USERNAME/playlists --skip-download`

**Comment by mathematicalmichael** [comment]
@dstftw skipping download is one thing, but this doesn't dump the hyperlinks anywhere, which was more to the point.
