### ISSUE TITLE
ERROR is not ignored with arg "-i" when multiple commands are concatenated

### ISSUE THREAD

**Issue by jcn50** [ytdl-org/youtube-dl#22022]
## Checklist

- [N/A] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.08.02**
- [N/A] I've checked that all provided URLs are alive and playable in a browser
- [N/A] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
Not applicable
```

## Description

**When a channel does not exists anymore, the subsequent commands (or cron) are not executed:**
```
[root@ip-172-31-47-135 ~]# youtube-dl -i https://www.youtube.com/user/TheAlexJonesChannel && youtube-dl -i https://www.youtube.com/user/GeographyNow/
[youtube:user] TheAlexJonesChannel: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] TheAlexJonesChannel: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**The next part of the command (after the "&&") is not executed, despite using the "-i" argument. Any other kind of YouTube error does the same. Soft termination is wanted (please).**

**Comment by remitamine** [comment]
read about what `&&` does(the first command fail because the URL is not available).
you might want to replace  `&&` with `;` or just pass both URLs in the same command.
