### ISSUE TITLE
Youtube: Youtube-dl fetching expire googlevideo links.

### ISSUE THREAD

**Issue by MSZ991** [ytdl-org/youtube-dl#22032]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

youtube-dl fetching expire googlevdeo linksevery time.i am using latest version.is there any way it can fetch new links every time.first time it works then after that it does not work.
Thank you.

**Comment by MSZ991** [comment]
@dstftw  question updated. I shall be very thankful if you can help me :D

**Comment by MSZ991** [comment]
@phihag any lead? Thanks in advance.

**Comment by dstftw** [comment]
Download links obtained with `-j` will work at least for some time. You must also provide the same cookies and the same headers as in JSON output.

**Comment by MSZ991** [comment]
what if i use `-g ` only? will it fetch new links or links will work for long time.

If this is only workaround can you tell me any command to send same cookies and and header in json output or can refer to any link.I just playable links in the browser every time.

Thank you so much.
