### ISSUE TITLE
Fix support for redbull.com (redbull.tv has moved to redbull.com)

### ISSUE THREAD

**Issue by gschaffner** [ytdl-org/youtube-dl#22037]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.redbull.com/int-en/films/AP-1ZSMAW8FH2111
- Single video: https://www.redbull.com/int-en/episodes/AP-1TQWK7XE11W11

## Description

RedBullTV is supported by youtube-dl. However, it appears that links to videos on [redbull.tv](https://www.redbull.com/) redirect to redbull.com rather than redbull.tv. Trying to download these videos results in an `Unsupported URL` error.

It also appears that some redbull.tv links (such as https://www.redbull.tv/video/AP-1Q6XCDTAN1W11 and https://www.redbull.tv/video/AP-1PMHKJFCW1W11 from the RedBullTV extractor's tests) now redirect to redbull.com with a different URL format.

**Comment by gschaffner** [comment]
It appears that multiple of the tests in redbulltv.py are no longer playable in browser.

**Comment by gschaffner** [comment]
Additionally, redbull.tv is now redirecting to https://www.redbull.com/int-en/discover (for my region, at least). Thus, I believe it is safe to remove support for redbull.tv URLs in favor of redbull.com ones.

**Comment by Boris-de** [comment]
Thanks! The referenced PR works for me with one exception. Sometimes the URLs do not have an "AP-..." id, but instead have a slug in that place. Can't find the in the HTML, so not sure how to get it.
Example: https://www.redbull.com/int-en/episodes/age-of-ondra-part-3

**Comment by Boris-de** [comment]
One more thing: #21781 has URLs that are also not supported yet, but as they have an AP-id they look like they could be added by changing the regex.

**Comment by gschaffner** [comment]
@Boris-de Thanks for the feedback! I've updated #22063 and slugs like that should work now.
