### ISSUE TITLE
YT playlist doesn't work

### ISSUE THREAD

**Issue by Antinatalist** [ytdl-org/youtube-dl#22033]
Hello,

youtube-dl [–ignore-errors –playlist-start 1 -audio-format mp3] [https://www.youtube.com/playlist?list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY]

Seems not to work.

Output: 
Batch file udio-can't be read?

OS: Sparky Linux

What do I do wrong?

Cheers

**Comment by dstftw** [comment]
Long options must start with double dash.

**Comment by Antinatalist** [comment]
Ok, thanks. That works.
