### ISSUE TITLE
youtube-dl is not a valid url

### ISSUE THREAD

**Issue by draconixx** [ytdl-org/youtube-dl#22059]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
ffmpeg version N-94490-g86d13e95e7 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9.1.1 (GCC) 20190807
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
libavutil      56. 33.100 / 56. 33.100
libavcodec     58. 55.100 / 58. 55.100
libavformat    58. 30.100 / 58. 30.100
libavdevice    58.  9.100 / 58.  9.100
libavfilter     7. 58.100 /  7. 58.100
libswscale      5.  6.100 /  5.  6.100
libswresample   3.  6.100 /  3.  6.100
libpostproc    55.  6.100 / 55.  6.100

For help run: ffmpeg -h
For formats run: ffmpeg -formats | more
For codecs run: ffmpeg -codecs | more

Current directory is now: "C:\PATH for executables\ffmpeg-20190809-86d13e9-win64-static\bin"
The bin directory has been added to PATH

C:\PATH for executables\ffmpeg-20190809-86d13e9-win64-static\bin
>youtube-dl -v
[debug] System config: []
[debug] User config: ['youtube-dl', '-o', 'C:\\Users\\Drago\\Downloads\\youtube-dl\\%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2019.08.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-94490-g86d13e95e7, ffprobe N-94490-g86d13e95e7
[debug] Proxy map: {}
ERROR: 'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:youtube-dl" ) to search YouTube
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwvl_v2x\build\youtube_dl\extractor\generic.py", line 2247, in _real_extract
youtube_dl.utils.ExtractorError: 'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:youtube-dl" ) to search YouTube

C:\PATH for executables\ffmpeg-20190809-86d13e9-win64-static\bin
>youtube-dl -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 https://www.youtube.com/watch?v=5-uWlFq380M
ERROR: 'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:youtube-dl" ) to search YouTube

C:\PATH for executables\ffmpeg-20190809-86d13e9-win64-static\bin
>youtube-dl "Joji Sanctuary:youtube-dl"
ERROR: 'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:youtube-dl" ) to search YouTube

## Description

WRITE DESCRIPTION HERE
I run a ffm-prompt.bat that searches for ffmpeg and ffmprobe that looks like this: @ECHO OFF
REM FF Prompt 1.2
REM Open a command prompt to run ffmpeg/ffplay/ffprobe
REM Copyright (C) 2013-2015  Kyle Schwarz
 
TITLE FF Prompt
 
IF NOT EXIST bin\ffmpeg.exe (
  CLS
  ECHO bin\ffmpeg.exe could not be found.
  GOTO:error
)
 
CD bin || GOTO:error
PROMPT $P$_$G
SET PATH=%CD%;%PATH%
CLS
ffmpeg -version
ECHO.
ECHO For help run: ffmpeg -h
ECHO For formats run: ffmpeg -formats ^| more
ECHO For codecs run: ffmpeg -codecs ^| more
ECHO.
ECHO Current directory is now: "%CD%"
ECHO The bin directory has been added to PATH
ECHO.
 
CMD /Q /K
GOTO:EOF
 
:error
ECHO.
ECHO Press any key to exit.
PAUSE >nul
GOTO:EOF

:End
cmd /k.
 Got the bat from someone else. Then I use youtube dl and multiple commands fail and return with the error "ERROR: 'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:youtube-dl" ) to search YouTube" I had the same issue in the previous version and the only way I got around this was by using youtube-dl gui from another person. But I'm trying to not be dependent on that and figure out why it keeps giving the same error. Even without the bat file and just running command prompt, I still get the same error, as shown: 
Microsoft Windows [Version 10.0.17763.615]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Drago>cd C:\PATH for executables\ffmpeg-20190809-86d13e9-win64-static\bin

C:\PATH for executables\ffmpeg-20190809-86d13e9-win64-static\bin>dir
 Volume in drive C is Windows
 Volume Serial Number is (not sure if needed, so removed)
 Directory of C:\PATH for executables\ffmpeg-20190809-86d13e9-win64-static\bin

08/10/2019  02:50 PM    <DIR>          .
08/10/2019  02:50 PM    <DIR>          ..
08/09/2019  04:56 AM        66,603,008 ffmpeg.exe
08/09/2019  04:56 AM        66,487,808 ffplay.exe
08/09/2019  04:56 AM        66,513,920 ffprobe.exe
08/10/2019  02:50 PM         8,053,960 youtube-dl.exe
               4 File(s)    207,658,696 bytes
               2 Dir(s)  21,774,610,432 bytes free

C:\PATH for executables\ffmpeg-20190809-86d13e9-win64-static\bin>youtube-dl https://www.youtube.com/watch?v=7wfUUZvybPY
ERROR: 'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:youtube-dl" ) to search YouTube

**Comment by remitamine** [comment]
invalid user config file(remove `youtube-dl` from the beginning of the config file).
