### ISSUE TITLE
youtube-dl regularly produces video files that can't be deleted, moved or renamed

### ISSUE THREAD

**Issue by JuzBeKind** [ytdl-org/youtube-dl#22052]
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '247+bestaudio', 'http://www.youtube.com
/watch?v=X0nk4HqPzrY']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.08.02
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-90425-gdb2a7c947e-sherpya, ffprobe N-90425-gdb2a7
c947e-sherpya
[debug] Proxy map: {}
[youtube] X0nk4HqPzrY: Downloading webpage
[youtube] X0nk4HqPzrY: Downloading video info webpage
[debug] Invoking downloader on 'https://r6---sn-o097znlk.googlevideo.com/videopl
ayback?expire=1565396341&ei=FblNXajZHZKZkwbngqLABw&ip=75.140.106.11&id=o-AEwNjeE
oZgoTXb4ZErn-bwUA7DBocuQNYClviX258u2V&itag=247&aitags=133%2C134%2C135%2C136%2C13
7%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mm=31%
2C29&mn=sn-o097znlk%2Csn-n4v7sney&ms=au%2Crdu&mv=m&mvi=5&pl=21&initcwndbps=21175
00&mime=video%2Fwebm&gir=yes&clen=23123335&dur=151.317&lmt=1517563823035107&mt=1
565374610&fvip=1&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Cso
urce%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRgIhANSM2mP6JsR2KX
6mXzIix_UclAl5AyeMk8a2xEFviBEpAiEA5WxiW9Moa4gXgXuB3llogrF8kySt4jCKPqp5v1nDr58%3D
&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAIdhL72xpX
hzYzt9LVYAHK2j0KosNL4oIaEOjytqmUv3AiEAkpYK0QNaLiyWW9WRi7mNvldf7gp9z48liPeVgCa_Pu
Q%3D&ratebypass=yes'
[download] Destination: Venera Gimadieva - The Golden Cockerel at Santa Fe Opera
-X0nk4HqPzrY.f247.webm
[download] 100% of 22.05MiB in 00:05
[debug] Invoking downloader on 'https://r6---sn-o097znlk.googlevideo.com/videopl
ayback?expire=1565396341&ei=FblNXajZHZKZkwbngqLABw&ip=75.140.106.11&id=o-AEwNjeE
oZgoTXb4ZErn-bwUA7DBocuQNYClviX258u2V&itag=251&source=youtube&requiressl=yes&mm=
31%2C29&mn=sn-o097znlk%2Csn-n4v7sney&ms=au%2Crdu&mv=m&mvi=5&pl=21&initcwndbps=21
17500&mime=audio%2Fwebm&gir=yes&clen=2635916&dur=151.361&lmt=1517562894906068&mt
=1565374610&fvip=1&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Cso
urce%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRgIhAKCWcA5jgD02mL
sgVlM0nrVQ9ohGz4ar3GOdeEIGjNLWAiEAn85RObUJBo4jIPOgvludaIrfbEjTy3x7gYtjY1c315s%3D
&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAIdhL72xpX
hzYzt9LVYAHK2j0KosNL4oIaEOjytqmUv3AiEAkpYK0QNaLiyWW9WRi7mNvldf7gp9z48liPeVgCa_Pu
Q%3D&ratebypass=yes'
[download] Destination: Venera Gimadieva - The Golden Cockerel at Santa Fe Opera
-X0nk4HqPzrY.f251.webm
[download] 100% of 2.51MiB in 00:00
[ffmpeg] Merging formats into "Venera Gimadieva - The Golden Cockerel at Santa F
e Opera-X0nk4HqPzrY.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Venera G
imadieva - The Golden Cockerel at Santa Fe Opera-X0nk4HqPzrY.f247.webm" -i "file
:Venera Gimadieva - The Golden Cockerel at Santa Fe Opera-X0nk4HqPzrY.f251.webm"
 -c copy -map "0:v:0" -map "1:a:0" "file:Venera Gimadieva - The Golden Cockerel
at Santa Fe Opera-X0nk4HqPzrY.temp.webm"
Deleting original file Venera Gimadieva - The Golden Cockerel at Santa Fe Opera-
X0nk4HqPzrY.f247.webm (pass -k to keep)
Deleting original file Venera Gimadieva - The Golden Cockerel at Santa Fe Opera-
X0nk4HqPzrY.f251.webm (pass -k to keep)

Q:\Program Files\Portable\YouTube-dl0\command line\a>
```

## Description

youtube-dl regularly produces video files that cannot be deleted, moved or renamed.
The files can be copied but the copy may have the same traits (undeletable, unmovable, unrenamable).
Restarting the computer can help but usually doesn't.
The files play fine in media players.
Attempting to delete or move one of these files results in a prompt that says "preparing to delete" of "moving" but the prompt never goes away. 
Sometimes the cancel button will get rid of the prompt. If not, restarting the computer or killing the explorer.exe process appears to be the only way to get rid of it. 
Attempting to rename one of these files results in the explorer window hanging, at which point the explorer.exe process needs to be killed or the computer restarted.

Sometimes, when renaming one of the files, the explorer window will just hang for a long time (rather than permanently) and the file will actually eventually be renamed.
In that case (when the file is renamed), it becomes possible to delete it.

youtube-dl is the only software that has ever produced such files on my drive.
At least two previous versions of youtube-dl also produced these files.
I still have video files (created by youtube-dl) from last year on my drive, that I still can't delete, move or rename. I even tried several pieces of software created for deleting 'undeletable' files and they were not able to delete the files.
The bug has been reproducable every time for me thus far using the following command:
YouTube-dl0\command line\a>youtube-dl -v -f 247+bestaudio http://www.youtube.com/watch?v=X0nk4HqPzrY

**Comment by dstftw** [comment]
This has nothing to do with youtube-dl. Either your disk is damaged/has bads or something locks files. Use LockHunter or similar tool for the latter.
