### ISSUE TITLE
Auto Filename for m3u8 Links

### ISSUE THREAD

**Issue by Daringbaaz** [ytdl-org/youtube-dl#22051]
Hello, i Want to know About How to Setup a cmd that will auto generate filename for m3u8 Links

i tried :
 `youtube-dl -o '%(title)s.%(ext)s' <URL-of-video>`

But output filname was` '(ext)s`' Without any Extensions

Please Help me to solve

**Comment by Daringbaaz** [comment]
Hi, Why This Thread Closed Without any Answer ??

**Comment by gschaffner** [comment]
m3u8 files don't typically contain information about the video's title. (I'm not sure if it's possible for them to contain such information.)

Do you have an example m3u8 file that contains title data?
