### ISSUE TITLE
Does all-subs download only one subtitle per language?

### ISSUE THREAD

**Issue by chogam** [ytdl-org/youtube-dl#22064]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

If a video has multiple subtitile formats for a single language, would the --all-subs retrieve just one subtitle per language or all of them?

Reason for asking:
https://www.sbs.com.au/ondemand/video/11821123796/hestons-feasts-victorian contains 2 formats:  srt and dfxp.  --list-subs confirms both are present.
However --all-subs would only download the srt.  I can override that using --sub-format dfxp, so the dfxp file is available, but I do not understand why it would not be retrieved with --all-subs.

This may be a site broken issue, but I have not found another site with more than one format per language, so I am not able to confirm whether it is a bug, a site broken issue or a by-design choice.

**Comment by dstftw** [comment]
`--all-subs` will download all languages.

**Comment by chogam** [comment]
So you are saying that it will only download one subtitle format per language, and therefore the behaviour I saw is by-design, and not a bug?
