### ISSUE TITLE
Pluralsight - Detecting youtube-dl and Banning Account with Very Cautious Settings

### ISSUE THREAD

**Issue by mrsd859** [ytdl-org/youtube-dl#22084]
Hi there.

I recently had my Pluralsight account banned TWICE. First with the message:

> We have blocked your account because our security systems have flagged your Pluralsight account for an unusual amount of activity. This means a high volume of requests have occurred every 10-30 seconds for a prolonged period of time. Please note that this high volume of activity is in violation of our terms of service [https://www.pluralsight.com/terms].

I believe my wait time was < 30 sec so changed the config to the below:

```
-u ****
-p ****
-i
-c
--no-warnings
--console-title
--batch-file='batch-file.txt'
--max-sleep-interval 145
--min-sleep-interval 120
-o '%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s'
-f 'bestvideo[height<=720]+bestaudio/best[height<=720]/worst'
-r 250k
```

I've also been using the options:
`--playlist-start=`
and
`--playlist-end=`
to catch some videos that I missed through shutdown / connection drops.

The worrying thing is that they appear to be able to detect ytdl. The latest email I got was:

> I have unblocked your account.  As the account owner, you are responsible for the activities generated by your account. Your account was generating usage tied to a youtube-dl extension. This can be prevented from making sure you are the only one using your account and/or not using third party extensions to access our content.   Please make sure you are not using any third-party applications or extensions on our site.  Let me know if you have any questions.

Any idea how they are detecting the usage of ytdl. Anything I'm missing in the settings?

I am using 2019.7.30.0 release however I don't want to update and "test" again otherwise I'll definitely get banned along with an email to management no doubt!

**Comment by dstftw** [comment]
youtube-dl does not download webpages, resources, images and other stuff irrellevant to downloading media. Based on this any downloader tool can be easily detected.
