### ISSUE TITLE
[ADN] how to add cookies and download subtitles

### ISSUE THREAD

**Issue by k3npachi** [ytdl-org/youtube-dl#22087]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, I just discovered youtube-dl, everything works fine except for the ADN site

I can easily download free 480p videos

but where it gets stuck is that I can't get the premium videos back, I don't understand how to add the cookies 

another problem, I can't download the subtitles, I saw that the key changes every day and here too I can't understand how to add it 

thanks

**Comment by k3npachi** [comment]
Hello, I just discovered youtube-dl, everything works fine except for the ADN site

I can easily download free 480p videos

but where it gets stuck is that I can't get the premium videos back, I don't understand how to add the cookies 

another problem, I can't download the subtitles, I saw that the key changes every day and here too I can't understand how to add it 

thanks

**Comment by remitamine** [comment]
> but where it gets stuck is that I can't get the premium videos back, I don't understand how to add the cookies

https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl
> I saw that the key changes every day and here too I can't understand how to add it

https://github.com/ytdl-org/youtube-dl/issues/12724#issuecomment-481673353
