### ISSUE TITLE
[YouTube] Incorrect number of videos on a playlist

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#22082]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Music> youtube-dl -v "https://www.youtube.com/watch?v=R51mV3pTuw4&list=PLDBDEDD7E1F357763"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=R51mV3pTuw4&list=PLDBDEDD7E1F357763']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.08.02
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLDBDEDD7E1F357763 - add --no-playlist to just download video R51mV3pTuw4
[youtube:playlist] PLDBDEDD7E1F357763: Downloading webpage
[download] Downloading playlist: dream trance
[youtube:playlist] playlist dream trance: Downloading 28 videos
[download] Downloading video 1 of 28
ERROR: Interrupted by user
```

## Description

Youtube-dl says that the playlist has 28 videos, but it has 30. Even if some videos are not available due to whatever reasons or the playlist contains duplicates, it should display the same number of videos as the browser does.

![](https://user-images.githubusercontent.com/54062148/62932638-cfd93580-bdc0-11e9-95f4-a3755916e57e.png)

**Comment by 2twe5ctw6jujfls9ycjqv-n5** [comment]
https://github.com/ytdl-org/youtube-dl/issues/16212

**Comment by 2twe5ctw6jujfls9ycjqv-n5** [comment]
Actually, the linked issue does not seem to be a duplicate, as this playlist does not represent default user uploads playlist, but rather a manually created playlist.

> It sounds like the only way of mitigating what clearly looks like a server side bug -- would mean we'd have to request both the playlist and the user rendition, and then take the union of all videos in both.

This workaround and the one explained in https://github.com/ytdl-org/youtube-dl/issues/16212#issuecomment-432764556 does not work in this case.

**Comment by dstftw** [comment]
2 video are duplicated in this playlist.

**Comment by sgfjsgfef** [comment]
@dstftw Yes, it has duplicates, it literally says in the issue:

> Even if some videos are not available due to whatever reasons **or the playlist contains duplicates**, it should display the same number of videos as the browser does.

I explicitly want duplicates and want the same order that I get in the browser, what is the problem? And why have you deleted two comments? The comments were usefull and correct.

**Comment by sgfjsgfef** [comment]
And the issue is perfectly valid.
