### ISSUE TITLE
Can I use client's(users) ip as a proxy ?

### ISSUE THREAD

**Issue by mattcommon991** [ytdl-org/youtube-dl#22080]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

I have collect the ip address of every user who visit my site,when the user makes a request, i will pass the users ip in youtube-dl command as 
`youtube-dl --proxy 43.23.65.45 https://youtube.com/watch?v=erwejk231r -j `

it should server as a proxy and can be a workaround for 429 error.
will it work?

**Comment by dstftw** [comment]
No, that's not how proxy work at all.
