### ISSUE TITLE
ytsearch to also display playlist

### ISSUE THREAD

**Issue by nadermx** [ytdl-org/youtube-dl#22098]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm trying to use the `ytsearch` function, but have it display the playlist url as well on.  

I've tried `youtube-dl ytsearch10:python -J --yes-playlist --skip-download` as well `youtube-dl -J -i --flat-playlist ytsearch10:python --skip-download
` as a few other varitations of `playlist`, but it doesn't show them.  Is there anyway?

**Comment by dstftw** [comment]
Currently not possible.
