### ISSUE TITLE
outtmpl syntax error

### ISSUE THREAD

**Issue by DexsLaboratory** [ytdl-org/youtube-dl#22106]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hey yall, im trying to run youtube-dl in a python shell so it can read a file with youtube links in it and extract the audio, im using the following script below:

```
from __future__ import unicode_literal
import youtube_dl
import os
from sys import argv

download_options = {
        'format': 'bestaudio/best'
        'outtmpl': '/tmp/foo_%(title)s-%(id)s.%(ext)s' 
        # Syntax Error Is The Outtmpl Line Above On The Colon
        'nocheckcertificate': True
        'postprocessors': [{
                'key': 'FFmpegExtractAudio'
                'preferredcodec': 'mp3'
                'prefferedquality': '192'
        }].
}

# Song Directory
if not os.path.exists('Songs')
        os.mkdir('Songs')
else:
        os.chidr('Songs')

# Download Songs
with youtube_dl.YoutubeDL(download_options) as dl:
        with open('../' + argv[1]. 'r') as f:
                for song_url in f:
                        dl.download([song_url])
```
The problem with the code is that the colon on the outtmpl line (knowing which file to extract links from) is getting a syntax error and i cant figure out why, im running this on python 3.7.4

**Comment by dstftw** [comment]
Nothing to do with output template. Bother to read some basic doc on python dict's syntax.
