### ISSUE TITLE
ERROR: Sorry about that occur without any more information

### ISSUE THREAD

**Issue by ArtemisZGL** [ytdl-org/youtube-dl#22102]
## Checklist

- [Y] I'm reporting a broken site support issue
- [Y] I've verified that I'm running youtube-dl version **2019.08.13**
- [Y] I've checked that all provided URLs are alive and playable in a browser
- [Y] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [Y] I've searched the bugtracker for similar bug reports including closed ones
- [Y] I've read bugs section in FAQ

## Verbose log

```
[download] Downloading video 9 of 33627
[youtube] ZbL_db16k0w: Downloading webpage
[youtube] ZbL_db16k0w: Downloading video info webpage
WARNING: video doesn't have subtitles
[info] Writing video description to: ZbL_db16k0w.description
[info] Writing video description metadata as JSON to: ZbL_db16k0w.info.json
[download] Destination: ZbL_db16k0w.webm
[download] 100% of 9.67MiB in 00:19
[ffmpeg] Destination: ZbL_db16k0w.wav
Deleting original file ZbL_db16k0w.webm (pass -k to keep)
[download] Downloading video 10 of 33627
[youtube] J-D8n4_fd6Q: Downloading webpage
[youtube] J-D8n4_fd6Q: Downloading video info webpage
WARNING: video doesn't have subtitles
[info] Writing video description to: J-D8n4_fd6Q.description
[info] Writing video description metadata as JSON to: J-D8n4_fd6Q.info.json
[download] Destination: J-D8n4_fd6Q.webm
[download] 100% of 9.72MiB in 00:09
[ffmpeg] Destination: J-D8n4_fd6Q.wav
Deleting original file J-D8n4_fd6Q.webm (pass -k to keep)
[download] Downloading video 11 of 33627
[youtube] S1C8tqyy3oc: Downloading webpage
[youtube] S1C8tqyy3oc: Downloading video info webpage
ERROR: Sorry about that.
```

## Description

i want to download audio and vvt from https://www.youtube.com/user/movieclips, but everytime it down load to 11th vedio, it broken and only reported ERROR: Sorry about that. the command i used is :
youtube-dl -o '%(id)s.%(ext)s' -f worst --write-description --write-info-json --write-sub --sub-lang en --max-downloads 100 -x --audio-format 'wav' https://www.youtube.com/user/movieclips

**Comment by remitamine** [comment]
```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
```

**Comment by nagas3000** [comment]
I want to be clear that using -i, --ignore-errors isn't a great solution as noted on some other issue threads. With that being said if thats the solution, why youtube-dl can't download some videos that other programs can download them without a hitch.
