### ISSUE TITLE
is youtube-dl python3 ready ?

### ISSUE THREAD

**Issue by shirishag75** [ytdl-org/youtube-dl#22107]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

is youtube-dl python3 ready. I am asking as Debian is getting to put the towel on python2 . 

See https://release.debian.org/transitions/html/python2-rm.html

and 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931659

Granted it's lot, but there are 2 years interim for them to make it happen, so it's a high possibility that there would be only python3 and not python2 unless there is some major roadblock. 

Also if somebody marks this as duplicate, please share link to original question as well.

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#description
