### ISSUE TITLE
Xhamster Playlist Error - Unsupported Site 

### ISSUE THREAD

**Issue by Jalawoud** [ytdl-org/youtube-dl#22100]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://xhamster.com/users/thelover2/videos']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[generic] videos: Requesting header
WARNING: Falling back on generic information extractor.
[generic] videos: Downloading webpage
[generic] videos: Extracting information
ERROR: Unsupported URL: https://xhamster.com/users/thelover2/videos
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5b8vs72_\build\youtube_dl\extractor\generic.py", line 3333, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://xhamster.com/users/thelover2/videos

## Description

WRITE DESCRIPTION HERE

I am trying to use this tool in order to download one's entire xhamster account video uploads. This tool does work for similar sites such as pornhub, however on xhamster "unsupported url error" occurs. The tool can download individual videos if linked, but when linking to a profile it fails to download the entire catalog of uploaded videos. I am using the .exe for windows 10.

**Comment by Stephan972** [comment]
See also #16330

**Comment by Stephan972** [comment]
> > See also #16330
> 
> Is this being worked on?

I don't think so...
