### ISSUE TITLE
download m4s segment with mpd mpeg-dash

### ISSUE THREAD

**Issue by foultayeb** [ytdl-org/youtube-dl#22111]
Hi,
i want to download a VOD from an mpd file but i have many problems
this is the link of mpd file 

https://neunlds1610lon.akamaized.net/nlds_vod/osn/vod/drm/nlncp/2019/06/21/0135e6f4-54d4-3de4-9189-fceb0ac87980/v1/stream/0135e6f4-54d4-3de4-9189-fceb0ac87980_1_pc.mp4.mpd

there is many segments m4s like this

https://neunlds1610lon.akamaized.net/nlds_vod/osn/vod/drm/nlncp/2019/06/21/0135e6f4-54d4-3de4-9189-fceb0ac87980/v1/stream/0135e6f4-54d4-3de4-9189-fceb0ac87980_1_3000_video/Time=2532000.m4s

and i think that the file is also encrypted

so i have used youtube-dl, dashproxy, ismdownloader and streamlink. none of them has helped me.

Thank you

**Comment by dstftw** [comment]
You can't, it's DRM protected.

**Comment by foultayeb** [comment]
i know but how to download all segments m4s ?
