### ISSUE TITLE
[Python] Trigger FFMPEG If Conditions Are Not Met?

### ISSUE THREAD

**Issue by ragov883** [ytdl-org/youtube-dl#22119]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, im playing around with the FFMPEG settings and this is my code so far here: https://pastebin.com/60zUzCRT

Currently, YouTube-Dl downloads the best filesize thats less than 50MB. I was wondering if its possible to set a command that it downloads the best MP4 version and if an MP4 version does not exist, it will download the best version then use FFMPEG to convert it to MP4 format.

Thank you!

**Comment by dstftw** [comment]
See FAQ for format selection, `--recode-video` for recoding.

**Comment by ragov883** [comment]
@dstftw Hi, sorry to bother, but where can I call it within Python? I checked the YouTubeDL module and theres no "recode-video" option (yes it exists if i call youtube-dl via the commandline but im trying to embed it within my Python app)
