### ISSUE TITLE
Is it possible to set different format options depending on source?

### ISSUE THREAD

**Issue by Samillion** [ytdl-org/youtube-dl#22124]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I would like to have a different format option depending on source, for example:

I want Youtube videos to run with:
`bestvideo[height<=?480][fps<=?30][vcodec!=?vp9]+bestaudio/best[height<=480]`

And any other source to run with:
`bestvideo[fps<=?30][vcodec!=?vp9]+bestaudio/best`

Would that be possible?

**Comment by dstftw** [comment]
You can create custom configs and pass `--config-location`.

**Comment by Samillion** [comment]
Could you direct me to any documentation on how to assign different configs based on source please?

**Comment by dstftw** [comment]
That's not possible.
