### ISSUE TITLE
Enforce prevention downloading same file

### ISSUE THREAD

**Issue by brutalcrozt** [ytdl-org/youtube-dl#22120]
## Checklist

- [x] I'm reporting a feature request
- [ ] I've verified that I'm running youtube-dl version **2019.08.13**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

I am not sure if this is feature request, it's `2019.07.30` that i use
<details><summary>this is the full info </summary>

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.30
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-58-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
```
</details>
## Description

- What the problem is
![Screenshot from 2019-08-16 14-16-11(yt change desiredoutput)](https://user-images.githubusercontent.com/3001652/63171385-ad1b7b00-c065-11e9-876c-781f69872256.png)
It already downloaded the x.webm file, but it repeats download again and unfortunately changes to x.mp4

![Screenshot from 2019-08-16 16-12-40(yt not aware on existing mp3 file)](https://user-images.githubusercontent.com/3001652/63171492-e8b64500-c065-11e9-8f55-6985c99a1991.png)
This one is youtube-dl output-ed to mp3

![Screenshot from 2019-08-16 20-22-14(yt dl mp3)](https://user-images.githubusercontent.com/3001652/63171616-1ac7a700-c066-11e9-8a61-992358ea8fc2.png)
this one is to re-confirm the youtube-dl output-ed to mp3 

- How it could be fixed
Firstly, it's my suspicion that 1. we do check with the desired vidio.extension. While i am proposing we do check existing downloaded file with only the video name, without extension.
Also, it should be the same, regardless of the desired file output.
Having said that, i never know or read about the video or output quality.
1. FYI those above behavior is not use --download-archive option
- How your proposed solution would look like
Always check existing file first, with file default video name as it's the file name and without the file extension.

Related to point 1, can we just make the default youtube-dl behavior when using `--yes-playlist` use `--download-archive` with a default file name. IE playlist_id.txt.

I think it can be tackle down with #16790
not use download archive

**Comment by dstftw** [comment]
You must use `--download-archive` for this.

**Comment by brutalcrozt** [comment]
do you think when using `--yes-playlist` also involving `--download-archive` is a bad suggestion?

**Comment by dstftw** [comment]
It's a very bad suggestion.

**Comment by brutalcrozt** [comment]
Then you owe me and explanation :wink:

**Comment by Kaos-Industries** [comment]
> 
> 
> It's a very bad suggestion.

I'm confused, why?
