### ISSUE TITLE
[Python] Calling Recode Video From Module

### ISSUE THREAD

**Issue by ragov883** [ytdl-org/youtube-dl#22126]
## Checklist

- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, I have a basic script here that is designed to download the best format under 50MB here: https://pastebin.com/9Y4z2iwk

I know about the --recode-video which allows me to recode a video if the format is not supported by the download. My goal is to download the best mp4 videos and, if the best video is not in mp4 format, recode it into mp4. However, I am not using YouTube-DL via the command line but embedded into my Python module and there is no "recode-video" listed [here](https://github.com/ytdl-org/youtube-dl/blob/3e4cedf9e8cd3157df2457df7274d0c842421945/youtube_dl/YoutubeDL.py#L137-L312) in the YouTubeDL.

One last thing (a little off topic but relevant). Options such as the downloader cannot be controlled video the YouTubeDL module since their handled by the downloader, a seperate module. How do I control this and add it into my YouTubeDL options inside my Python program?

**Comment by dstftw** [comment]
You must explicitly set `FFmpegVideoConvertor` postprocessor.
Control what? Bother to clearly explain yourself.
