### ISSUE TITLE
youtube video removed need code to manual ffmpeg to webm format so it plays

### ISSUE THREAD

**Issue by nopedd** [ytdl-org/youtube-dl#22122]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hi

the video is removed and need the manual code to mux webm youtube video so it is fixed by ffmpeg, can someone pls share the youtube dl command i need to use to manually fix the file as the video are removed i cannot do it auymore the autmatic way

what is the command thank you

**Comment by nopedd** [comment]
the video plays but has not sound, i need the command ffmpeg youtube dl call after download to fix this.

**Comment by TemporaryUsername12481** [comment]
`ffmpeg -i videofile -i audiofile -map 0:v -map 1:a -c copy merged.mkv` should do it

**Comment by nopedd** [comment]
hi

 

thank you have saved me the video on youtube was removed so i could redownload it perform this task, the first time i downloaded it i did not have ffmpeg in same folder, then when tried again youtube taken video down

 

keep the great work on youtube dl i love thank you


Sent: Friday, August 16, 2019 at 4:51 PM
