### ISSUE TITLE
Problem with downloading 1080 videos (without muxing if possible)

### ISSUE THREAD

**Issue by aidinzolghadr** [ytdl-org/youtube-dl#22134]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi,

I'm trying to download the 1080P version of videos from YouTube but they are not available as direct downloads almost always and as DASH only. I have a couple of questions about this:

(Please keep in mind that I'm using aria2c and installed ffmpeg in order to mux)

1) Why IDM Extention can do this directly? I tried switches I read about that seemed relevant like native HLS (IIRC) to get the 1080 version directly but didn't work. So it's possible to do since IDM does it, am I missing something with ydl? (Even though I understand it may not be possible with ydl)

2) If the first question fails, I'll be forced to mux with ffmpeg and the problem is the audio part does not download with aria2c and downloads very slowly (~512Mb), is there anyway to make it faster too? (If it's entirely an aria2c question, I'm sorry).

Currently my config is this:

`youtube-dl.exe --external-downloader aria2c --external-downloader-args '-c -j 16 -x 16 -s 16 -k 4M' -i -f best -a dl.txt`

and the config I used to download with muxing is

`youtube-dl.exe --external-downloader aria2c --external-downloader-args '-c -j 16 -x 16 -s 16 -k 4M' -i -f bestvideo+bestaudio --hls-prefer-native -a dl.txt`

**Comment by dstftw** [comment]
1. It can not as well as any other software since 1080p are served only as separate audio and video by Youtube.
2. Ask aria2c about that.

**Comment by aidinzolghadr** [comment]
[I asked aria2c people](https://github.com/aria2/aria2/issues/1495) and they said problem is with ydl not passing the file to aria2c or something.
