### ISSUE TITLE
Peertube torrent

### ISSUE THREAD

**Issue by Sosthene-Guedon** [ytdl-org/youtube-dl#22144]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
When using youtube-dl to download from peertube the video is downloaded as any other media.
However the main idea of peertube is to use torrent.
Adding torrenting capabilities to youtube-dl is not a great idea, as  discussed in #17368.
However, I think that adding a command line argument (--peertube-torrent-file) to make youtube-dl download the torrent file instead of the video could be useful.
For exemple :
`youtube-dl --peertube-torrent-file https://skeptikon.fr/videos/watch/aae59455-f4df-4e9b-b0f4-ee9be336464d'
would download the torrent file :
https://skeptikon.fr/download/torrents/aae59455-f4df-4e9b-b0f4-ee9be336464d-1080.torrent
and not the video itself.
Then the user can use their own torrent manager to download the video.

I'm currently trying to implement this feature myself. I know how to make the extractor fetch the torrent url, but I have trouble understanding how command-line arguments are parsed to control when it should be done (I'll probably figure it out though).

**Comment by dstftw** [comment]
Current policy is to only return links youtube-dl can handle itself.

**Comment by crocket** [comment]
You can extract torrent file from peertube videos by searching network requests for torrent on web browser.
