### ISSUE TITLE
Failed to parse JSON

### ISSUE THREAD

**Issue by eristompul** [ytdl-org/youtube-dl#22154]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
I want to download a video from site https://tv.naver.com/v/9564768 but end up with error : Failed to parse JSON ( cause by ValueError('Expecting value: line 1 column 1 (char 0)',));
I just using this command:
youtube-dl https://tv.naver.com/v/9564768
Is there anything i missed ?

**Comment by ThomasChr** [comment]
Can't replicate with Version 2019.06.27:
```
python -m youtube_dl https://tv.naver.com/v/9564768
[Naver] 9564768: Downloading webpage
[Naver] 9564768: Downloading JSON metadata
[download] Destination: EVERGLOW (에버글로우) - Adios MV-9564768.mp4
[download] 100% of 88.20MiB in 00:18
```
