### ISSUE TITLE
Add "Adding support for authentication" section in the README.md

### ISSUE THREAD

**Issue by LucBerge** [ytdl-org/youtube-dl#22153]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

It could be interesting to have a "Adding support for authentication" section in the README.md next to the ["Adding support for new site"](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) section. I would like to add a new support but I don't know how.

**Comment by dstftw** [comment]
Search `def _login`.
