### ISSUE TITLE
Virustotal says that linux version of youtube-dl needlessly contacts certain ip/domains while .exe version doesn't

### ISSUE THREAD

**Issue by MystesofEternity** [ytdl-org/youtube-dl#22151]
## Checklist
* [x] I've verified that I'm running youtube-dl version **2019.08.13**
* [x] I've checked that all provided URLs are alive and playable in a browser
* [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
* [x] I've searched the bugtracker for similar bug reports including closed ones
* [x] I've read bugs section in FAQ

## Citings and Remarks
Latest youtube-dl binary for Linux. Click Relations tab for reference on what I am saying
```
https://www.virustotal.com/gui/file/85a15c9c7394147105b3015964f975ca34770038b06e5edd40389413cac44b2d/relations
```
Malicious domain being contacted by the binary as said by VirusTotal. Note that I haven't personally tested it as I do not have a test lab in place just yet. Click Relations tab for a look at the graphs that include this domain in their analysis.
```
https://www.virustotal.com/gui/url/1254637991d7e0ef7103662d56a239deb7ac8371edf6ff64e035c35b7f6696ef/relations
```
Latest youtube-dl binary for Windows. Click Relations tab to see just how clean this is compared to the binary for Linux. 
```
https://www.virustotal.com/gui/file/afc92ad007e8101b73c2dcff8c7d54c0ad75c124d0b9cb07dfddb845b9958dfa/relations
```

## Description

While I know there is a possibility that the connections in the linux binary is just a false positive due to flawed linux binary testing of VirusTotal, I'd prefer to be really sure anyways given the fact that a supply-chain attack is certainly not an impossible feat.

**Comment by dstftw** [comment]
Bother to even read what does Execution Parents in Relations does mean.

**Comment by MystesofEternity** [comment]
@dstftw Execution parents doesn't matter because those are only files that include/execute youtube-dl for their own purposes like say packing an open-source program into a much bigger program.

What do you need from me to make this more "acceptable" for your examination? This is a serious case with a possibility that your linux binaries are poisoned.

**Comment by MystesofEternity** [comment]
This portion is the one that matters.
![Matters](https://user-images.githubusercontent.com/10123628/63238847-f09b0280-c27a-11e9-8e04-7e4f67fbf63f.png)

**Comment by dstftw** [comment]
youtube-dl does not connect to these locations on its own. These are standard macOS call homes.

**Comment by MystesofEternity** [comment]
Oh I see, upon noticing that I could view the whole report I noticed that it was indeed executed in macOS
Thanks for the heads-up, I suppose that means everything's good as it is
