### ISSUE TITLE
ERROR: Unable to log in learning.oreilly.com

### ISSUE THREAD

**Issue by vikiaiteam** [ytdl-org/youtube-dl#22161]
C:\safaribooksonline>youtube-dl -u user -p pass --verbose https://learning.oreilly.com/videos/comptia-a-core/9780135305331 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', 'https://learning.oreilly.com/videos/comptia-a-core/9780135305331', '--convert-subs', 'vtt']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.7.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-93640-ga087764847, ffprobe N-93640-ga087764847
[debug] Proxy map: {}
[safari:course] Downloading login page
[safari:course] Logging in
[safari:course] Completing login
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure
 to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\python37\lib\site-packages\youtube_dl\extractor\common.py", line 529, in extract
    self.initialize()
  File "c:\python37\lib\site-packages\youtube_dl\extractor\common.py", line 433, in initialize
    self._real_initialize()
  File "c:\python37\lib\site-packages\youtube_dl\extractor\safari.py", line 30, in _real_initialize
    self._login()
  File "c:\python37\lib\site-packages\youtube_dl\extractor\safari.py", line 82, in _login
    raise ExtractorError('Unable to log in')
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update
 on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaan143** [comment]
same here i am getting also sins yesterday

**Comment by rpmbrk** [comment]
I have tried all version from 2019.06.08 to 2019.08.13 and got the same error

$ youtube-dl -v https://www.safaribooksonline.com/videos/clean-code/9780134661742

[debug] System config: []
[debug] User config: [u'-u', u'PRIVATE', u'--all-subs', u'--socket-timeout', u'10', u'--no-warnings', u'--console-title', u'-i', u'-c', u'-w', u'-o', u'/repo/Videos/%(playlist_title)s/%(playlist_index)03d - %(title)s.%(ext)s', u'-f', u'best[tbr<=1000]/worst[[height>=720]]/best[[height<720]]']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.safaribooksonline.com/videos/clean-code/9780134661742']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.6.6 (CPython) - Linux-2.6.32-696.23.1.el6.x86_64-x86_64-with-redhat-6.9-Santiago
[debug] exe versions: ffmpeg 4.1.3-static, ffprobe 4.1.3-static
[debug] Proxy map: {}
[safari:course] Downloading login page
[safari:course] Logging in
[safari:course] Completing login
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/safari.py", line 30, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/safari.py", line 82, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by hp600** [comment]
Same problem here, it started about 2 days ago.
Login fails even with the latest version of youtube-dl installed.
