### ISSUE TITLE
youtube-dl fills wrong date for upload_date

### ISSUE THREAD

**Issue by zachary-D** [ytdl-org/youtube-dl#22173]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -o "%(upload_date)s" https://www.twitch.tv/videos/470092413 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-o', u'%(upload_date)s', u'https://www.twitch.tv/videos/470092413', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-58-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs .
[debug] Proxy map: {}
[twitch:vod] 470092413: Downloading vod info JSON
[twitch:vod] 470092413: Downloading vod access token
[twitch:vod] 470092413: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://vod-metro.twitch.tv/f47ba3fe586c0a829fe3_jschlatt_35372790656_1279473710/chunked/index-dvr.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 684
[download] Destination: 20190821
[download]  13.7% of ~4.78GiB at  7.63MiB/s ETA 10:49
```

## Description

For [this](https://www.twitch.tv/videos/470092413) the output template `upload_date` is being filled as 20190821 when the stream was started on 2019-08-20 at 9PM EST and completed on the same day.  I would expect it to fill 20190820 for `upload-date`.  The same issue happens for the [VOD before it](https://www.twitch.tv/videos/469629268), it was streamed on 8/19 but youtube-dl fills it as 20190820.  It does not however affect [this VOD](https://www.twitch.tv/videos/469019280) that was streamed earlier in the day (2PM EST iirc), which makes me think it may be a timezone issue (complete speculation on that)

**Comment by dstftw** [comment]
This is what twitch returns.
```
"created_at":"2019-08-21T01:14:21Z",
"published_at":"2019-08-21T01:14:21Z",
```

**Comment by zachary-D** [comment]
That looks like the date in UTC then, hovering over the video in chrome has a tooltip of the date in my timezone.  Shouldn't youtube-dl convert dates/times to the current machine it's running on?
