### ISSUE TITLE
ytsearch accuracy

### ISSUE THREAD

**Issue by marioortizmanero** [ytdl-org/youtube-dl#22179]
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've searched the bugtracker for similar feature requests including closed ones

Currently `ytsearch` (all the search methods are probably affected by this) only returns the most relevant youtube video. Which sometimes is completely irrelevant because the query isn't specific enough, or because a completely different thing with a similar name appears because there wasn't anything else to return. It'd be great to return a confidence % on how accurate the search result is.

**Comment by dstftw** [comment]
It returns as much results as you've requested. There is no any kind confidence or accuracy, just results returned by Youtube.
