### ISSUE TITLE
404 on existing Rutube video.

### ISSUE THREAD

**Issue by katasonov** [ytdl-org/youtube-dl#22192]
Hi,

I do following request to get Rutube video info:  youtube-dl --print-json --no-warnings --socket-timeout 5 --user-agent "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" -s "https://rutube.ru/video/9eb8c7ce52e84693f53bd87186e860fd"

It fails with error: 

ERROR: Unable to download options JSON: HTTP Error 404: NOT FOUND (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2229, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by Klink0v** [comment]
You should define URL in the form of:
https://rutube.ru/play/embed/blah-blah-blah-blah

For example:

youtube-dl -i --cookies cookies-rutube-ru.txt 'https://rutube.ru/play/embed/10914131?wmode=opaque&club_token=17640946-985888823576129830_985888823576129830-1590357128-pu1ocpedp8-e88db979c6520c54ef9754a0aa37fe03'

This way it works fine.

**Comment by BANDGAMIN** [comment]
I'm trying to download from Rutube
I have the same error: Unable to download options JSON: HTTP Error 404: Not Found (caused by HTTPError());
The program has been updated to the latest version.
Please tell me the program is working with Rutube now?

**Comment by dirkf** [comment]
It works with some links, but the problem link has expired: "Видео недоступно"

**Comment by dirkf** [comment]
Also, the site returns 404 for a geo-restriction error, as well as for expired content, with JSON including `.detail.name` having value `'blocking_rule_10656141'`.
```console
$ python -m youtube_dl --list-subs 'https://rutube.ru/video/056cb59f2836e6d0c1a137c1dbb370f8/'
[rutube] 056cb59f2836e6d0c1a137c1dbb370f8: Downloading video JSON
[rutube] 056cb59f2836e6d0c1a137c1dbb370f8: Downloading options JSON
[rutube] In addition to the below, consider --geo-verification-proxy.
ERROR: Options JSON is blocked (or may have expired)
This video is available in Russian Federation.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
$
```
