### ISSUE TITLE
[CBS.com] Change mediaset to support alternate audio tracks, e.g., Audio Description or Spanish dubbing

### ISSUE THREAD

**Issue by tmthywynn8** [ytdl-org/youtube-dl#22199]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

CBS has recently added alternate audio tracks for some of their videos, e.g., Audio Description (AD) and Spanish dubbing. However, the current mediaset(s) used by Youtube-dl do not list these tracks, probably because it uses an outdated mediaset. Potential reasons to use a more current mediaset:

1. Higher quality main audio: It looks like some of the master playlists have 5.1 audio tracks for main (EAC-3 and AC-3), so users may want to take advantage of that.
2. Allows those who want just the AD track to grab it, saving time and bandwidth.
3. Works around CBS's inaccessible player controls: As a person using assistive technologies, the current player on the web platform is impossible to use as controls are not labeled and do not have keyboard focus

Unfortunately, I do not know how to load more mediasets for CBS content, particular ones without encryption like what is used by Youtube-dl, but it would be nice if I am able to watch Audio Description on more platforms than just iOS.

Sample link: [NCIS: S16 E19 Perennial ](https://www.cbs.com/shows/ncis/video/_08sfeTJsa_lowR48SwvvdreOhAhuDa0/ncis-perennial/)  
This example above has three audio tracks: English, English AD, and Spanish.

### Problematic mediasets:

* DASH playlist as served to Windows browsers such as Chrome, Internet Explorer, etc:
	* Problem: Uses CENC encryption ???
	* Sample ThePlatform link: https://link.theplatform.com/s/dJ5BDC/QzJdvJZIhg62?format=SMIL&manifest=m3u&Tracking=true&mbr=true&callback=uvpHandleJsonpResult
	* Sample DASH playlist: https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2019/04/02/1470282307907/84395_cenc_dash/stream.mpd
	* Youtube-dl warning: Unknown MIME type application/mp4 in DASH manifest
* HLS playlist as served to iOS&mdash;whether through web browser or CBS app:
	* Problem: Uses Sample-AES encryption
	* Sample ThePlatform URL: https://link.theplatform.com/s/dJ5BDC/ueKsxLOR6an0?format=SMIL&manifest=m3u&Tracking=true&mbr=true&callback=uvpHandleJsonpResult
	* Sample HLS playlist: https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2019/04/02/1470282307907/84395_fp_hls/master.m3u8
	* Sample AD track: https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2019/04/02/1470282307907/84395_fp_hls/CBS_NCIS_373_AA_6CH_30M_84389_4_dvs_128/stream.m3u8
	* Youtube-dl warning: hlsnative has detected features it does not support, extraction will be delegated to ffmpeg

**Comment by michealespinola** [comment]
PBS is also using Audio Description tracks.  PBS appears to be adding a "_Descriptions" suffix to differentiate the track from the primary audio track, [as in this example](https://www.pbs.org/video/ken-burns-country-music-episode-1-the-rub/):

```
[info] Available formats for 3032621122:
format code                       extension  resolution note
hls-english-English               mp4        audio only [eng]
hls-english-English_Descriptions  mp4        audio only [eng]
```

Unfortunately, youtube-dl is sometimes downloading the AD track as the default track instead of the non-descriptive track.

**Comment by tmthywynn8** [comment]
For that rare case on PBS, you can get around that by using -f bestvideo+hls-english-English. I'm not sure where the best format keyword is obtaining the combined video/audio from, but that seems to do the job as well.

**Comment by distantorigin** [comment]
What is the reason that this was closed? Is this not possible due to DRM or is there a more in depth explanation?

**Comment by ctoth** [comment]
Also curious about this.
