### ISSUE TITLE
How to retrieve the list video titles from my YouTube watch history?

### ISSUE THREAD

**Issue by Symaxion** [ytdl-org/youtube-dl#22194]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I am trying to get the list of videos (ID + title) from my YouTube watch history.

I found the `--flat-playlist` option in the README, and this works as expected for regular playlists. However, for my history, I only get IDs back.

Am I missing something here, or is the only way to get the titles from the videos in my history to fetch the metadata for each ID separately using `--get-title` or similar?

**Comment by dstftw** [comment]
`--flat-playlist --get-title` should be enough.
