### ISSUE TITLE
Settings Error Or Real Incompatability

### ISSUE THREAD

**Issue by ragov883** [ytdl-org/youtube-dl#22206]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, im using the YouTube-DL python module to create an all-in-one downloader for personal use. The code of interest is here. Which basically detects if I want an audio or video copy and returns back a path in JSON format of where that file is downloaded: https://pastebin.com/NGEb7nsn

The goal with my settings is simple, find the best quality thats under 50MB, download it, then convert it to mp3 or mp4 depending on whats selected

It works as expected when passing a Youtube URL, for both audio & video conversion. However anything else throws up a "ERROR: requested format not available"

For example, this SoundCloud link falls in under the 50MB limit yet still fails: https://soundcloud.com/liltecca/ransomwrld

Or this vimeo URL: https://vimeo.com/353221482

Or this twitter video: https://twitter.com/NFL_DovKleiman/status/1165447358416609281

What is wrong with the settings im passing?

**Comment by dstftw** [comment]
1. `filesize` metadata is optional.
2. Read FAQ on format selection.

**Comment by ragov883** [comment]
Hi @dstftw 

The filesize for me is a requirement (specifically, im trying to force YTDL to find the best under 50MB). Also the FAQ doesnt seem to give me the answer. I have FFMPEG in the same directory as my python script and it detects FFMPEG and converts when I use a Youtube link.
