### ISSUE TITLE
Video Tags extractor

### ISSUE THREAD

**Issue by VarunSaiTeja** [ytdl-org/youtube-dl#22201]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Video Tags Downloader

I want to suggest you to add a feature, which will save all the tags of youtube video to a text file

**Comment by dstftw** [comment]
Extract `tags` from JSON output and do whatever you need.
