### ISSUE TITLE
request: convert times to users local timezones

### ISSUE THREAD

**Issue by zachary-D** [ytdl-org/youtube-dl#22213]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I'd like youtube-dl to convert upload dates to the users current timezone when substituting for '%(upload_date)s' in output filenames.  Twitch in particular (and presumably many more) return their timestamps in UTC, and youtube-dl does not convert them before substitution which leads to the upload date being inconsistent in different timezones.  In my case this results in evening streams being labelled as the day after, while morning streams are marked labelled properly.  I originally thought this was a bug ( #22173 ), more specific examples of this behavior are available there.  Thank you for considering my request!

**Comment by dstftw** [comment]
This will not work since you don't know the original timezone in general.

**Comment by zachary-D** [comment]
I meant the timezone of the downloader, not the recorder

**Comment by zachary-D** [comment]
To clarify, I was looking to have the date twitch reports (in UTC) to the downloader's current timezone.
