### ISSUE TITLE
 ('The read operation timed out',) trying to download video from https://www.dailymotion.com/video/x6x2fgu

### ISSUE THREAD

**Issue by markcroft1975** [ytdl-org/youtube-dl#22224]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.08.13**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by markcroft1975** [comment]
worked when i put the -v option
markcroft@user1-HP-EliteBook-8440p:~/iplayer$ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.15+ (CPython) - Linux-5.0.0-25-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
markcroft@user1-HP-EliteBook-8440p:~/iplayer$ 
markcroft@user1-HP-EliteBook-8440p:~/iplayer$ 
markcroft@user1-HP-EliteBook-8440p:~/iplayer$ 
markcroft@user1-HP-EliteBook-8440p:~/iplayer$ 
markcroft@user1-HP-EliteBook-8440p:~/iplayer$ 
markcroft@user1-HP-EliteBook-8440p:~/iplayer$ 
markcroft@user1-HP-EliteBook-8440p:~/iplayer$ 
markcroft@user1-HP-EliteBook-8440p:~/iplayer$ youtube-dl -v https://dai.ly/x6x2fgu
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://dai.ly/x6x2fgu']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 2.7.15+ (CPython) - Linux-5.0.0-25-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[generic] x6x2fgu: Requesting header
[redirect] Following redirect to https://www.dailymotion.com/video/x6x2fgu
[dailymotion] x6x2fgu: Downloading webpage
[dailymotion] x6x2fgu: Downloading metadata JSON
[dailymotion] x6x2fgu: Downloading m3u8 information
[dailymotion] x6x2fgu: Downloading m3u8 information
[dailymotion] x6x2fgu: Downloading m3u8 information
[dailymotion] x6x2fgu: Downloading m3u8 information
[dailymotion] x6x2fgu: Downloading m3u8 information
[dailymotion] x6x2fgu: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://www.dailymotion.com/cdn/H264-1280x720/video/x6x2fgu.mp4?sec=wwrFFprSyVpwiNDtHTPLt9NGpzRD_4dl2kJd5p6yHl51QYj5sSZNKilYvnKg5vhz'
[download] Resuming download at byte 913676803
[download] Destination: BBC Horizon 2018 Diagnosis on Demand-x6x2fgu.mp4
[download] 100% of 901.93MiB in 00:10
markcroft@user1-HP-EliteBook-8440p:~/iplayer$ 



did not work with -v
markcroft@user1-HP-EliteBook-8440p:~/iplayer$ youtube-dl https://dai.ly/x6x2fgu
[generic] x6x2fgu: Requesting header
[redirect] Following redirect to https://www.dailymotion.com/video/x6x2fgu
[dailymotion] x6x2fgu: Downloading webpage
[dailymotion] x6x2fgu: Downloading metadata JSON
[dailymotion] x6x2fgu: Downloading m3u8 information
[dailymotion] x6x2fgu: Downloading m3u8 information
[dailymotion] x6x2fgu: Downloading m3u8 information
[dailymotion] x6x2fgu: Downloading m3u8 information
[dailymotion] x6x2fgu: Downloading m3u8 information
[dailymotion] x6x2fgu: Downloading m3u8 information
[download] Resuming download at byte 71298788
[download] Destination: BBC Horizon 2018 Diagnosis on Demand-x6x2fgu.mp4
[download]  96.6% of 901.93MiB at 322.87KiB/s ETA 01:36ERROR: unable to download video data: ('The read operation timed out',)
markcroft@user1-HP-EliteBook-8440p:~/iplayer$ 
markcroft@user1-HP-EliteBook-8440p:~/iplayer$ 


i was hoping to get with get_iplayer but out of date found a version on https://www.dailymotion.com/video/x6x2fgu

thank you for your great app

**Comment by dstftw** [comment]
Network issue on your side.

**Comment by markcroft1975** [comment]
thank you
