### ISSUE TITLE
youtube.com 480p DASH formats

### ISSUE THREAD

**Issue by IoanPaleru** [ytdl-org/youtube-dl#22226]
When there's an available 480p quality youtube video, can you please add an option to download and convert that automatically with youtube-dl (using ffmpeg), and save it as an 854x480 AVC video with 128 kbps AAC audio MP4 file? Also, please add the option to automatically download and convert any available resolution DASH format AVC video with AAC audio as an MP4 file. Thanks.

**Comment by dstftw** [comment]
Read FAQ on format selection.
