### ISSUE TITLE
QUESTION: Is this how search works for youtube?

### ISSUE THREAD

**Issue by annoying258** [ytdl-org/youtube-dl#22234]
I'm trying to see if youtube-dl can be used to find a video on youtube. In this case, when only the exact title of the video is known.
Then getting the url of the video using `youtube-dl`. And finally querying more details using the url.

First it seems the results returned are incorrect for some reason. Even though the first query should not match the first result,
assuming the first result is the most accurate match.

```sh
youtube-dl --get-title ytsearch:"Navier-Stokes Equations - Numberphile"
Navier-Stokes Equations - Numberphile
(rogdesk-asd_123) rtara@trimskel:Downloads$ youtube-dl --get-title ytsearch:"Navier-Stokes Equations - Numberp"
Nondimensionalizing the Navier-Stokes Equation
(rogdesk-asd_123) rtara@trimskel:Downloads$ youtube-dl --get-title ytsearch:"Navier-Stokes Equations - Numberphile"
Navier-Stokes Equations - Numberphile
```

-----

Same as above but ytsearch2, which seemed like it uses version 2 of the youtube search system, but surprisingly it just returns two
results instead of one. 

```sh
(rogdesk-asd_123) rtara@trimskel:Downloads$ youtube-dl --get-title ytsearch2:"Navier-Stokes Equations - Numberp"
Nondimensionalizing the Navier-Stokes Equation
Navier-Stokes Equations - Numberphile
(rogdesk-asd_123) rtara@trimskel:Downloads$ youtube-dl --get-title ytsearch2:"Navier-Stokes Equations - Numberphile"
Navier-Stokes Equations - Numberphile
Navier-Stokes Existence and Smoothness (Million Dollar Problem!)
```

---

Also `youtube-dl --get-url ytsearch:` once again, surprisingly, returns useless results. And `youtube-dl --get-id ytsearch:` can be used to get a string, say, `hwrnmQumtPw` then append it to the string `https://www.youtube.com/watch?v=` and there's the `expected output` of `youtube-dl --get-url ytsearch:'Shell Scripting Tutorial'`

---
I'm running **youtube-dl version 2019.08.13**
**Python 3.7.4 (default, Jul 12 2019, 20:57:46)**

**Comment by annoying258** [comment]
**[placeholder]**

**Comment by annoying258** [comment]
**[placeholder]**

**Comment by dstftw** [comment]
This is what Youtube returns all blames go there.
2 is **number of results** not version of search system.
