### ISSUE TITLE
[Dailymotion] Direct URL Extractor does not seem to work

### ISSUE THREAD

**Issue by SingitBatch40** [ytdl-org/youtube-dl#22236]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

I am not sure if it is a bug or just wrong settings so im just putting it as a question. I am making a bot that when you send a dailymotion URL, it sends back the full raw URL. The code is here: https://pastebin.com/qwckWrFa

The problem is that the bot is running on one server (Heroku Hosted) and the user is on another (their home). When i run the bot, YouTubeDL sends back the raw URL but when i click it, its a white page. 

I decide to run the bot & then open URL on the same PC and it seems to work. I am confused on why this happens. On the PC that runs the bot, it redirects to a different web page ('https://proxy-02.nyc.dailymotion.com') which shows the raw URL. Copying that URL to my computer just gets me this: https://i.imgur.com/nRp1WTa.png 

What can I do to fix this? The idea was that our smart TV sucks playing Dailymotion links but can play when given a link to a direct raw video url. 

I just downloaded the YouTubeDL module from pip also so its the latest one.

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser
