### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Roki100** [ytdl-org/youtube-dl#22244]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

what does that mean in readme? https://github.com/ytdl-org/youtube-dl#http-error-429-too-many-requests-or-402-payment-required 
*These two error codes indicate that the service is blocking your IP address because of overuse. __Contact the service and ask them to unblock your IP address, or - if you have acquired a whitelisted IP address already__ - use the --proxy or --source-address options to select another IP address.*

**Comment by dstftw** [comment]
Which word is not clear?

**Comment by Roki100** [comment]
"Contact the service and ask them to unblock your IP address" what service wtf

**Comment by Hrxn** [comment]
Your hosting provider for example?

**Comment by dstftw** [comment]
Service that returns 429.

**Comment by Roki100** [comment]
youtube returns 429 for me so i dont think contacting youtube is good idea? (i dont even know where i can contact youtube tho)
