### ISSUE TITLE
Support for live TV on EinsUndEinsTV (Zattoo derivate)

### ISSUE THREAD

**Issue by EugenVau** [ytdl-org/youtube-dl#22248]
- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Would be nice to have live TV support for "EinsUndEinsTV" in the [Zattoo extractor](https://github.com/ytdl-org/youtube-dl/blob/b500955a58efb019133b3214ea81635342728f1f/youtube_dl/extractor/zattoo.py#L413). The URL structure is exactly like in [ZattooLive](https://github.com/ytdl-org/youtube-dl/blob/b500955a58efb019133b3214ea81635342728f1f/youtube_dl/extractor/zattoo.py#L269) or [QuicklineLive](https://github.com/ytdl-org/youtube-dl/blob/b500955a58efb019133b3214ea81635342728f1f/youtube_dl/extractor/zattoo.py#L224), e.g. https://www.1und1.tv/watch/zdf.

Many thanks and keep on the great work!

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by EugenVau** [comment]
Hi @dstftw ,

thanks for your quick reaction!

Unfortunately, I cannot provide my personal account credentials for obvious reasons. Neither can I set up a toolchain for building YTDL myself :-( 

But I can suggest changes in the Zattoo extractor, that pretty sure will work for 1und1.tv live TV and offer myself testing any eventual dev-builds, if needed.

As for code changes, the [EinsUndEinsTVIE class in the Zattoo extractor](https://github.com/ytdl-org/youtube-dl/blob/b500955a58efb019133b3214ea81635342728f1f/youtube_dl/extractor/zattoo.py#L413) should be replaced by the following code:

```python
class EinsUndEinsTVBaseIE(ZattooIE):
    _NETRC_MACHINE = '1und1tv'
    _HOST = '1und1.tv'
    _API_HOST = 'www.%s' % _HOST


class EinsUndEinsTVIE(EinsUndEinsTVBaseIE):
    _VALID_URL = _make_valid_url(ZattooIE._VALID_URL_TEMPLATE, _HOST)

    _TESTS = [{
        'url': 'https://www.1und1.tv/watch/abc/123-abc',
        'only_matching': True,
    }]

    def _real_extract(self, url):
        channel_name, video_id, record_id = re.match(self._VALID_URL, url).groups()
        return self._extract_video(channel_name, video_id, record_id)


class EinsUndEinsTVLiveIE(EinsUndEinsTVIE):
    _VALID_URL = r'https?://(?:www\.)?1und1\.tv/watch/(?P<id>[^/]+)'

    _TEST = {
        'url': 'https://www.1und1.tv/watch/ard',
        'only_matching': True,
    }

    @classmethod
    def suitable(cls, url):
        return False if EinsUndEinsTV.suitable(url) else super(EinsUndEinsTVLiveIE, cls).suitable(url)

    def _real_extract(self, url):
        channel_name = video_id = self._match_id(url)
        return self._extract_video(channel_name, video_id, is_live=True)
```

**Comment by dstftw** [comment]
The only options is providing credentials. I don't merge untested code.
