### ISSUE TITLE
3gp video

### ISSUE THREAD

**Issue by Analog78** [ytdl-org/youtube-dl#22250]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Why does Youtube-dl no longer discern 3gp video files? I seem to remember this was answered before with the answer Youtube no longer uses them but this is incorrect. Various Youtube plugins still access them and sites like genyoutube still make them available for download.

**Comment by Analog78** [comment]
Screenshot of ArcticFox reaching 3gp on my G3 iBook:
![Ride](https://user-images.githubusercontent.com/54666712/63932405-082e7400-ca4f-11e9-938d-3fda837494bf.jpg)

**Comment by dstftw** [comment]
Youtube does not serve 3gp. This is most likely manually muxed video.

**Comment by Analog78** [comment]
"Manually muxed video" Are suggesting I faked this??
My question was serious, I can supply various proof but if you went to www.genyt.net yourself you could see.

**Comment by TemporaryUsername12481** [comment]
The website is manually muxing the video, similar to "YouTube to mp3" sites

**Comment by Analog78** [comment]
But when I stream the video there's no delay whereas downloading there is - this behaviour is exactly the same as Youtube-dl when it still parsed 3gp files.
If genyoutube were muxing on the fly, why for 3gp only - why not for other sizes and formats that are audio or video only, why not muxe those together?

**Comment by Analog78** [comment]
Also if you check the screenshot of ArcticFox and Realplayer you can see it is playing the rtsp stream in the info dialogue - definitely not transcoding there.

**Comment by TeddyBearX** [comment]
> The website is manually muxing the video, similar to "YouTube to mp3" sites

The URL in his screenshot clearly points to googlevideo.com, not a third-party proxy site.

**Comment by rakeshdongre9** [comment]
thanks for this post [youtube thumbnail download](http://youtube-thumbnail-download.in/)
