### ISSUE TITLE
[Youtube] To know if a video is licensed or not (copyright)

### ISSUE THREAD

**Issue by titirino159** [ytdl-org/youtube-dl#22251]
## Checklist

- [* ] I'm reporting a site feature request
- [* ] I've verified that I'm running youtube-dl version **2019.08.13**
- [* ] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Is it possible to know if a youtube video is licensed and if possible to list them?

In fact, I want to use youtube-dl to create a script available to the public, but I want to prevent licensed videos from being downloaded.

Currently, when I do a youtube-dl -J https://www.youtube.com/watch?v=mvSItvjFE1c - it displays "license: null"

However, if you go into the details of the video from a web browser, you have: 

 Licensed to YouTube by
UMG (on behalf of Aftermath); UNIAO BRASILEIRA DE EDITORAS DE MUSICA - UBEM, UMPG Publishing, Sony ATV Publishing, SOLAR Music Rights Management, Broma 16, LatinAutor - UMPG, CMRRA, AMRA, LatinAutor - SonyATV, LatinAutor, Vydia (Music Publishing), Kobalt Music Publishing, BMI - Broadcast Music Inc. and ASCAP and 14 musical rights management companies

I would like to avoid coding this verification script myself because it will make an additional request to the youtube server. So would it be possible to add this feature in the future?

Thank you.

**Comment by dstftw** [comment]
If license is null then you can't.
