### ISSUE TITLE
Is there any way to reopen a feature request?

### ISSUE THREAD

**Issue by zachary-D** [ytdl-org/youtube-dl#22262]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is there any button or procedure to reopen a closed issue?  I believe my feature request (#22213) was closed as impossible to implement due to a miscommunication.

**Comment by dstftw** [comment]
I've already pointed out this is not possible in general cause you don't always know the original timezone.

**Comment by zachary-D** [comment]
From what I've seen twitch always returns time in UTC + 0 (how else would we get the timestamps?).  I'll try to find confirmation for this in the docs tomorrow.

**Comment by dstftw** [comment]
>in general

**Comment by zachary-D** [comment]
Oh, my mistake.  Could ytdl convert the timezones for sites with constant timezones and just pass through without modification on the ones we don't know?  (Or just do NA or something similar)
