### ISSUE TITLE
Let youtube-dl handle the filename of video itself

### ISSUE THREAD

**Issue by madobet** [ytdl-org/youtube-dl#22265]
## Checklist
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description
I've had the same issue with #20312

Would it be possible to let youtube-dl handle the filename and simply pass a temporary name (such as MD5 of the URL) to aria2c (or any other external downloader)?

The link of problem video: [https://www.youtube.com/watch?v=O7eZXXzLrVE](url)

**Comment by dstftw** [comment]
This will require storing temp name somewhere between runs in order to be able to support resume. But where to store it in order to be able to pick up it on next run? You're stumbling the same problem you're trying to solve. I guess it's worth fixing actual bugs instead of introducing another duct tape mess in 3rdparty software.

**Comment by madobet** [comment]
> This will require storing temp name somewhere between runs in order to be able to support resume. But where to store it in order to be able to pick it up on the next run? You stumble the same problem you're trying to solve. I guess it's worth fixing actual bugs instead of introducing another duct tape mess in 3rdparty software.

I also agree that aria2 should fix this bug, but what I mean is that we can not expect every similar bug in all possible external downloader, so reduce youtube-dl's dependence on an external downloader's function (filename processing rules) would be a possible choise.
There is no need for storing, using the same URL(filename etc.) and the same algorithm should get the same temporary name.
Of course, the best solution would be to Implement multi-threaded download function by ourselves. ;P
