### ISSUE TITLE
3gp Youtube

### ISSUE THREAD

**Issue by Analog78** [ytdl-org/youtube-dl#22266]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Please acknowledge this instead of closing thread again. In ArcticFox with a plugin and old mobile device user agent, Youtube is tricked into delivering 3gp - it then passes the rtsp stream to Realplayer. Check the screenshot you can see rtsp from Googlevideo - it is not a service transcoding and delivering 3gp on the fly.
Why does youtube-dl no longer reach these files?
![Ride](https://user-images.githubusercontent.com/54666712/64031077-a00b8b00-cb3f-11e9-97a8-51b925e38ebc.jpg)

**Comment by dstftw** [comment]
Once again: Youtube does not serve 3gp. At least not for modern User-Agents. If it serves for old mobile - use that with `--add-header`. At your own risk.
