### ISSUE TITLE
YouTube-dl download video only

### ISSUE THREAD

**Issue by Rachid90** [ytdl-org/youtube-dl#22271]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Hello,

When I try to download a YouTube video and I check the available format, I see that it only gives me "video only". How to download a video with audio?

Best regards.

**Comment by dstftw** [comment]
Read FAQ on format selection.
