### ISSUE TITLE
Pluralsight Working Settings Found

### ISSUE THREAD

**Issue by mrsd859** [ytdl-org/youtube-dl#22296]
Hi there,

This is not a support request, however I have seen many users (including myself) struggling with downloading from Pluralsight and with accounts being banned.

After experimenting (a lot), getting banned twice (and somehow talking my way out of the bans), I have found some settings which work.

My last ban was 21 days ago and I haven't had any problems since.

You may wish to include this is support documentation if appropriate.

**Considerations:**
- Log into the site from your browser and navigate to the course index page. This allows your browser to download page content and update the site's cookie. Use this as the referrer URL in the config below.
- Start playing the first video in your browser then pause it. After that, I tend to leave Pluralsight open and logged in while running youtube-dl.
- Run youtube-dl with the below settings.
- Do not download more content than you could reasonably watch in a day (8hrs or so).
- Do not leave to download overnight. Use only in regular "waking" hours for your timezone.
- Rate is intentionally limited to 100k which is slightly faster than regular playback in most cases. This means you should be able to run youtube-dl in the background.

**youtube-dl.conf**
```
-u ****

-p ****

-i

-c

--no-warnings

--console-title

--batch-file='batch-file.txt' <- [Text file in the youtube-dl root directory containing course URLs]

--max-sleep-interval 70

--min-sleep-interval 50

-o '%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s'

-f 'bestvideo[height<=720]+bestaudio/best[height<=720]/worst'

-r 100k

--referer='https://app.pluralsight.com/paths/certificate/mcsa' <- [Insert relevant referrer URL]
```

Hope this helps :)

**Comment by LouisParkin** [comment]
@mrsd859 thanks very much. I can confirm that this works. Pluralsight users of youtube-dl are in your debt.
