### ISSUE TITLE
Please add new site biggboss12tv.com

### ISSUE THREAD

**Issue by binhnx285** [ytdl-org/youtube-dl#22307]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [ ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://biggboss12tv.com/nazar-2nd-september-2019-episode-290-hotstar/
- Playlist: https://biggboss12tv.com/nazar-hd/

## Description

WRITE DESCRIPTION HERE

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free
