### ISSUE TITLE
MAKE FILENAME AS VIDEO TITLE NOT WORKING ON YOUTUBE PLAYLIST

### ISSUE THREAD

**Issue by br4dd** [ytdl-org/youtube-dl#22316]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
I run the command 
"youtube-dl -t https://www.youtube.com/playlist?list=PLBf0hzazHTGPdTHUObWn7dZtlHnSl_xFf"
the FILENAMES of the downloaded files are just RANDOM CHARACTERS.
HOW DO I MAKE THE FILENAMES SIMILAR TO CERTAIN TITLES WHEN DOWNLOADING A PLAYLIST IN YOUTUBE

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#output-template
