### ISSUE TITLE
Make Video title as filename on downloading playlist in youtube? -t command NOT WORKING

### ISSUE THREAD

**Issue by br4dd** [ytdl-org/youtube-dl#22310]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
How do I make the filename as Video Title?
Because when I download a playlist on youtube, it doesn't work.
Like this, 
youtube-dl -t https://www.youtube.com/playlist?list=PLBf0hzazHTGM8V_3OEKhvCM9Xah3qDdIx

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#output-template
