### ISSUE TITLE
Invalid duration of youtube video reported by --dump-json

### ISSUE THREAD

**Issue by wszak** [ytdl-org/youtube-dl#22314]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-j', u'-v', u'tUmWbZ2HCp4']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2019.09.01
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.19.66-1-MANJARO-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best

{
    "_filename": "live Ashra Mjalis (Z Qazi wasim abas Multan)  04 Muhrram Thallah Syedan G14 Islamabad 2019-tUmWbZ2HCp4.mp4",
    "abr": 128,
    "acodec": "mp4a.40.2",
    "age_limit": 0,
    "album": null,
    "alt_title": null,
    "annotations": null,
    "artist": null,
    "automatic_captions": {},
    "average_rating": 4.8415842,
    "categories": [
        "People & Blogs"
    ],
    "channel_id": "UCgBWyQBWQ0Lduws9sIvr6Ig",
    "channel_url": "http://www.youtube.com/channel/UCgBWyQBWQ0Lduws9sIvr6Ig",
    "chapters": null,
    "creator": null,
    "description": "official video of http://wwvw.talagangazadari.com like http://www.facebook.com/TalagangAzadari Whatsapp +923045121476 +923349457214",
    "dislike_count": 4,
    "display_id": "tUmWbZ2HCp4",
    "duration": 1,
```

## Description

WRITE DESCRIPTION HERE
The --dump-json reports duration=1 while the video is over 1 hour long.
Use this command:
youtube-dl -j 'https://www.youtube.com/watch?v=tUmWbZ2HCp4' > tUmWbZ2HCp4.json
Look into the json file and you'll see that duration is reported as 1.

If this is for some reason a 'nofix', then at least tell me how to determine when the duration field is invalid. Maybe youtube-dl should sum the formats/duration fields to calculate the final duration?

**Comment by NatalieStrong** [comment]
I tried that but the actual method worked a little differently for me

The --dump-json reports duration=12 while the video is not even an hour long.

Use this command:
youtube-dl -j 'https://www.youtube.com/watch?v=3IJYHdq36io&t=3s' > 3IJYHdq36io&t=3s.json
Look into the json file and you'll see that duration is reported.

If this is for some reason a 'nofix', then at least tell me how to determine when the duration field is invalid. Did youtube-dl should sum the formats fields to calculate the total duration?

**Comment by remitamine** [comment]
both videos report the correct duration.
```
youtube-dl -j tUmWbZ2HCp4 | jq .duration
4131
youtube-dl -j 3IJYHdq36io | jq .duration
145
```
