### ISSUE TITLE
oreilly.com learning path

### ISSUE THREAD

**Issue by jaan143** [ytdl-org/youtube-dl#22315]
## Checklist

- [x ] I'm reporting a site feature request
- [x ] I've verified that I'm running youtube-dl version **2019.09.01**
- [x ] I've searched the bugtracker for similar site feature requests including closed ones

## Description

please add this url in oreilly site script
https://www.oreilly.com/learning-paths/

this is the course url
https://www.oreilly.com/learning-paths/learning-path-sql/9781492058090/9781492058212-video326308

and what i check i think rest video lecture setting is same with other script setting
Remember filename saved in youtubedl folder is Safari.py
thanks

**Comment by jaan143** [comment]
@remitamine  will you refer me duplicate of this topic ?

**Comment by remitamine** [comment]
look for Safari(Safari Books Online) issues.
