### ISSUE TITLE
history channel site download fails

### ISSUE THREAD

**Issue by BeardedIT** [ytdl-org/youtube-dl#22321]
## Checklist

- [ x] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2019.09.01**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

youtube-dl https://www.history.com/shows/ax-men/season-1/episode-1 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.history.com/shows/ax-men/season-1/episode-1', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.01
[debug] Python version 2.7.16 (CPython) - Linux-5.0.0-21-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[aenetworks] ax-men/season-1/episode-1: Downloading webpage
WARNING: unable to extract aetn:VideoID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/aenetworks.py", line 176, in _real_extract
    webpage, 'video url', group='url')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by remitamine** [comment]
```
[aenetworks] ax-men/season-1/episode-1: Downloading webpage
[aenetworks] 21101480: Downloading JSON metadata
[aenetworks] 21101480: Downloading hls_high_ak SMIL data
[aenetworks] 21101480: Downloading m3u8 information
[aenetworks] 21101480: Downloading high_video_s3 SMIL data
[aenetworks] 21101480: Checking video URL
[aenetworks] 21101480: Checking video URL
[aenetworks] 21101480: Checking video URL
[aenetworks] 21101480: Checking video URL
[aenetworks] 21101480: Checking video URL
[aenetworks] 21101480: Checking video URL
[aenetworks] 21101480: Checking video URL
[aenetworks] 21101480: Checking video URL
[aenetworks] 21101480: Downloading hls_ingest_fastly SMIL data
[aenetworks] 21101480: Downloading m3u8 information
[download] Destination: Man vs. Mountain-21101480.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  844M    0  390k    0     0   115k      0  2:04:44  0:00:03  2:04:41  115k
```
