### ISSUE TITLE
Error downloading video from YesPornPlease.com

### ISSUE THREAD

**Issue by jun-dev** [ytdl-org/youtube-dl#22339]
C:\Users\Artem\Downloads>youtube-dl.exe -v "https://yespornplease.com/v/925304327" best
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://yespornplease.com/v/925304327', 'best']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.09.01
[debug] Python version 3.4.4 (CPython) - Windows
[debug] exe versions: ffmpeg 2.8.4
[debug] Proxy map: {'http': '127.0.0.1:1075', 'https': '127.0.0.1:1075'}
[generic] 925304327: Requesting header
WARNING: Could not send HEAD request to https://yespornplease.com/v/925304327: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>
[generic] 925304327: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 925304327: Extracting information
[download] Downloading playlist: Bunnie Hughes - Schoolgirl Hostage Training Cosplay  watch online for free
[generic] playlist Bunnie Hughes - Schoolgirl Hostage Training Cosplay  watch online for free: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[VShare] ac6bfbd: Downloading webpage
ERROR: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\YoutubeDL.py", line 2229, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\utils.py", line 2724, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open

**Comment by dstftw** [comment]
```
PS C:\Dev\youtube-dl\master> py -3.4 .\youtube_dl\__main__.py https://yespornplease.com/v/925304327
[generic] 925304327: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 925304327: Downloading webpage
[generic] 925304327: Extracting information
[download] Downloading playlist: Bunnie Hughes - Schoolgirl Hostage Training Cosplay  watch online for free
[generic] playlist Bunnie Hughes - Schoolgirl Hostage Training Cosplay  watch online for free: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[VShare] ac6bfbd: Downloading webpage
[download] Destination: hd schoolgirl hostage training cosplay-ac6bfbd.mp4
[download]   0.2% of 110.47MiB at 533.86KiB/s ETA 03:31
ERROR: Interrupted by userPS C:\Dev\youtube-dl\master> py -3.4 .\youtube_dl\__main__.py https://yespornplease.com/v/925304327
[generic] 925304327: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 925304327: Downloading webpage
[generic] 925304327: Extracting information
[download] Downloading playlist: Bunnie Hughes - Schoolgirl Hostage Training Cosplay  watch online for free
[generic] playlist Bunnie Hughes - Schoolgirl Hostage Training Cosplay  watch online for free: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[VShare] ac6bfbd: Downloading webpage
[download] Destination: hd schoolgirl hostage training cosplay-ac6bfbd.mp4
[download]   0.2% of 110.47MiB at 533.86KiB/s ETA 03:31
ERROR: Interrupted by user
```
