### ISSUE TITLE
get youtube auto-generated subtitles when no subs available

### ISSUE THREAD

**Issue by rocawhey** [ytdl-org/youtube-dl#22340]
## Checklist

- [x ] I'm reporting a site feature request
- [x ] I've verified that I'm running youtube-dl version **2019.09.01**
- [x ] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Is it possible to default the download of --all-subs to include the youtube auto-generated subtitles? Especially when no subtitles have been uploaded by the content creator (ie., when youtube-dl returns "WARNING: video doesn't have subtitles"? savesubs.com is an example of a website that can pull these autogen subs.

**Comment by dstftw** [comment]
`--write-auto-sub`.
