### ISSUE TITLE
Don`t show size of best file. 

### ISSUE THREAD

**Issue by SerhiiK** [ytdl-org/youtube-dl#22341]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

## Description

While use flag -F for select quality and type of video best variant doesn`t show the size of the file. 
![Screenshot from 2019-09-08 22-45-10](https://user-images.githubusercontent.com/6170876/64493591-9ba34880-d28a-11e9-8e89-d9e275356c45.png)

**Comment by dstftw** [comment]
It's not provided by Youtube.
