### ISSUE TITLE
bestvideo+bestaudio does not always work

### ISSUE THREAD

**Issue by Naomi010Sentzke** [ytdl-org/youtube-dl#22365]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
PS D:\My Programs\youtube-dl> youtube-dl -v https://www.youtube.com/watch?v=PFQa3dHlHSg
[debug] System config: []
[debug] User config: ['-f', '315/313/308/271/399/137/398/bestvideo+251/140/bestaudio/best', '--write-sub', '--sub-lang', 'en', '--convert-subs', 'ass', '--merge-output-format', 'mkv', '-o', '%(title)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=PFQa3dHlHSg']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2019.09.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2
[debug] Proxy map: {}
[youtube] PFQa3dHlHSg: Downloading webpage
[youtube] PFQa3dHlHSg: Downloading video info webpage
WARNING: video doesn't have subtitles
[debug] Invoking downloader on 'https://r6---sn-gwpa-ccps.googlevideo.com/videoplayback?expire=1568228813&ei=bPF4XfORN-SSz7sPrKOXwAU&ip=2409%3A4062%3A285%3A9ddb%3Ae9e3%3Ada25%3Abd56%3Af45&id=o-AIIhtdbvN7oHHivssctCaH4qFBlE5Jm8K42CxHHgpjOP&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-gwpa-ccps%2Csn-h557sns7&ms=au%2Crdu&mv=m&mvi=5&pl=36&initcwndbps=120000&mime=video%2Fmp4&gir=yes&clen=85381633&dur=738.391&lmt=1552728326966163&mt=1568207118&fvip=1&keepalive=yes&c=WEB&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIgLiFdar2d64_FKEvB8QdMfuO8Gj2Omy5PcPHDRJIxnDACIQC8vXECVv2WdMkHbNGKSgfAS06GzHVUr1OpTXHrYXDTbQ%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgZYRza9m41T1gJ4VIrsnHOVJp_weuUYSTMZ4b5PxWl_MCIQDMAH_RgXfMObmRLSRiFRbjm4-NxBSWwNQ8Bt9IuBr_rg%3D%3D&ratebypass=yes'
[download] Destination: Fan Service in Anime vs. The Monogatari Series [PART 1] – Subverting Our Biases
[download] 100% of 81.43MiB in 05:58
[ffmpeg] There aren't any subtitles to convert

## Description

WRITE DESCRIPTION HERE
I have been seeing multiple times bestvideo+251/bestaudio/best fails to get the best output. Some of them are
https://www.youtube.com/watch?v=PFQa3dHlHSg
bestvideo should be f.137, but it downloads f.248
https://www.youtube.com/watch?v=Fmdb-KmlzD8
bestvideo should be f.315, but it downloads f.399
https://www.youtube.com/watch?v=TkLIovb1qC8
bestvideo should be f.399 but it downloads f.137
So, I modified my config to "-f 315/313/308/271/399/137/398/bestvideo+251/140/bestaudio/best" and the log is posted above.
This time it downloads f.248 but does not even bother mentioning and does not download the audio. I should atleast be able to force best output with "-f 315/313/308/271/399/137/398/bestvideo+251/140/bestaudio/best".  I am now using "bestvideo+251/bestaudio/best" in my config again and just manually set the format if it does not download. But I cant use youtube-dl to download a playlist because I dont know when it will decide on a whim to download a random format, unless I could actually force it to download the best.

**Comment by dstftw** [comment]
`315/313/308/271/399/137/398/bestvideo+251/140/bestaudio/best` means download `315` or `313` or `308` or `271` or `399` or `137` or `398` or `bestvideo+251` or `140` or `bestaudio` or `best` thus correctly resulting in `137` downloaded.
