### ISSUE TITLE
youtube.com: this video is unavailable

### ISSUE THREAD

**Issue by non-Jedi** [ytdl-org/youtube-dl#22367]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
❯ youtube-dl -v 'https://www.youtube.com/watch?v=pdMnTiO__ss'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vvv', 'https://www.youtube.com/watch?v=pdMnTiO__ss']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.01
[debug] Python version 3.6.9 (CPython) - Linux-5.2.13_1-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[youtube] pdMnTiO__ss: Downloading webpage
[youtube] pdMnTiO__ss: Downloading video info webpage
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 2115, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.
```

## Description

All youtube videos I've tried to download with youtube-dl today error with "ERROR: This video is unavailable."

**Comment by stranno** [comment]
JDownloader2 doesnt recognize videos so i guess they changed something.

**Comment by 5af64758** [comment]
i am also suffering the same issue with this URL: https://www.youtube.com/watch?v=lJOLb1GSvws

**Comment by Xan-Kun** [comment]
I can also confirm this. Many (possibly all) URLs.
