### ISSUE TITLE
9now downloads now failing

### ISSUE THREAD

**Issue by BlueMM75** [ytdl-org/youtube-dl#22361]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe -F "https://www.9now.com.au/pokemon/season-22/episode-29" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.9now.com.au/pokemon/season-22/episode-29', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.09.01
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {}
[debug] Using fake IP 1.158.116.92 (AU) as X-Forwarded-For.
[9now.com.au] episode-29: Downloading webpage
ERROR: Unable to extract page data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -
U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\ninenow.py", line 48, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract page data; please report this issue on https://yt-dl.org/bug . Make sure you are using the late
st version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

9now used to work (I successfully download on 2019-08-31).
For example on the Pokemon page at: https://www.9now.com.au/pokemon (which has ~4 episodes, adding & dropping 1 each day - so the episode numbers will change over time).
Previously, I had successfully checked what formats were available for Episode 26:
`youtube-dl.exe -F "https://www.9now.com.au/pokemon/season-22/episode-26"`
And then I normally use the following command to download (based on picking the ~1.5Mbps format)
`youtube-dl.exe -f hls-1527-4 --newline -i --write-sub -o "M:\%(uploader)s\s22\e26 %(title)s.%(ext)s" --embed-subs --sub-lang en --ignore-config --hls-prefer-native --add-metadata --write-thumbnail "https://www.9now.com.au/pokemon/season-22/episode-26"`

Neither the `-F` format query, nor the download are working as of today. So something changed/broke between Aug 31st & Sept 11th.

**Comment by Gehrminator** [comment]
Yes, I'm having the same issue trying to grab the CCs for Seachange no issue with previous weeks.

D:\subs>youtube-dl --verbose https://www.9now.com.au/seachange/season-1/episode-6
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.9now.com.au/seachange/season-1/episode-6']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.09.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-87027-gd826951, ffprobe N-87027-gd826951
[debug] Proxy map: {}
[debug] Using fake IP 1.158.163.157 (AU) as X-Forwarded-For.
[9now.com.au] episode-6: Downloading webpage
ERROR: Unable to extract page data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\ninenow.py", line 48, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract page data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


D:\subs>[debug] System config: []
'[debug]' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>[debug] User config: []
'[debug]' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>[debug] Custom config: []
'[debug]' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>[debug] Command-line args: ['--verbose', 'https://www.9now.com.au/seachange/season-1/episode-6']
'[debug]' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
'[debug]' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>[debug] youtube-dl version 2019.09.01
'[debug]' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
'[debug]' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>[debug] exe versions: ffmpeg N-87027-gd826951, ffprobe N-87027-gd826951
'[debug]' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>[debug] Proxy map: {}
'[debug]' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>[debug] Using fake IP 1.157.88.175 (AU) as X-Forwarded-For.
'[debug]' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>[9now.com.au] episode-6: Downloading webpage
'[9now.com.au]' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>ERROR: Unable to extract page data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
'ERROR:' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>Traceback (most recent call last):
'Traceback' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
'File' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\common.py", line 530, in extract
'File' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\ninenow.py", line 48, in _real_extract
'File' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpbzyg5d3a\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
'File' is not recognized as an internal or external command,
operable program or batch file.

D:\subs>youtube-dl --skip-download --all-subs https://www.9now.com.au/seachange/season-1/episode-6
[9now.com.au] episode-6: Downloading webpage
ERROR: Unable to extract page data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by chogam** [comment]
Me three, 
Same error message for https://www.9now.com.au/nate-is-late/season-1/episode-14

Looks like a site-wide issue.
