### ISSUE TITLE
[site support request] yjc.ir

### ISSUE THREAD

**Issue by lyndalopez544** [ytdl-org/youtube-dl#22366]
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Description
YJC or Young Journalists Club is a news service.
Some of the posts on their website may contain a video or audio file.

They simply provide a download link themselves.

## Copyright
They allow you to use their content as long as you refer them as the intellectual owner.(as noted by a warning at the website's footer section)

## Example URLs
Here's a <a href="https://kutt.it/LMWKGH">sample post containing a video</a>

A sample download link: https://cdn.yjc.ir/files/fa/news/1398/6/20/10541513_741.mp4
<code>details: https://cdn.yjc.ir/files/fa/news/[year]/[month]/[day]/[video_id].mp4</code>

- Only the Persian section of the website contains video and audio files.(as it seems)
- They provide only a single-quality permanant non-expirable downlaod link.

**Comment by dstftw** [comment]
Have you even tried before posting request?

**Comment by yasho2101** [comment]
I have tried it on three different videos and it is working on all of them

**Comment by yasho2101** [comment]
I suppose you are thinking about downloading from the links provided but I made the extractor for the parent website containing the link in the issues. Sample website is "https://www.yjc.ir/fa/news/7310480/وقتی-لباس-شخصی%E2%80%8Cهای-هند-برای-متفرق-کردن-مردم-وارد-عمل-می%E2%80%8Cشوند-فیلم" which contains this link "https://cdn.yjc.ir/files/fa/news/1399/1/20/11683420_225.mp4" as the downloadable link.
My extractor works fine. It is more user friendly as the user can just post the parent website and download videos.
