### ISSUE TITLE
[mixcloud:playlist] Downloading 0 videos

### ISSUE THREAD

**Issue by matoro** [ytdl-org/youtube-dl#22378]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl --verbose "https://www.mixcloud.com/soulection/playlists/soulection-radio-special-guests/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.mixcloud.com/soulection/playlists/soulection-radio-special-guests/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.7.4 (CPython) - Linux-5.2.13-arch1-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[mixcloud:playlist] soulection: Downloading playlist page
[download] Downloading playlist: Soulection Radio Special Guests by Soulection
[mixcloud:playlist] soulection_soulection-radio-special-guests: Download tracklist (page 1)
[mixcloud:playlist] playlist Soulection Radio Special Guests by Soulection: Downloading 0 videos
[download] Finished downloading playlist: Soulection Radio Special Guests by Soulection
```

## Description

Seems to be parsing an empty playlist from Mixcloud, this one should have >100 items in it.  Latest build from git.

**Comment by ElucGeek** [comment]
This issue is known and open for more than one year, I don't think any body is working on it, unfortunately I have not the capability to solve this, otherwise I would have as I'm really in need for this for a long time to make my automation media center to work well with Mixcloud.
