### ISSUE TITLE
pls help me 

### ISSUE THREAD

**Issue by HIZIXHIZI** [ytdl-org/youtube-dl#22373]
Hello, I run a teamspeak server, my teamspeak runs a service with music bots that use ytdl, unfortunately I don't know what's going on I heard about the limits .....

**Comment by Nycrera** [comment]
Probably you need to update your youtube-dl
check your version with
`youtube-dl --version`
and if it's not latest. (As far as I know 2019.09.12)
`youtube-dl -U`
