### ISSUE TITLE
[tf1] Additional audio streams and subtitles (described in MPD) not detected in tf1.fr videos

### ISSUE THREAD

**Issue by JerryKane** [ytdl-org/youtube-dl#22379]
## Checklist

- [x ] I'm reporting a site feature request
- [x ] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x ] I've searched the bugtracker for similar site feature requests including closed ones

## Description

After a recent evolution of "MyTF1" (tf1.fr), some videos are now available with original audio (in addition to the French dub, which is the default), with French subtitles and hearing-impaired French subtitles.
An example of such a video is:
https://www.tf1.fr/tmc/hercule-poirot/videos/hercule-poirot-saison-02-episode-02-la-femme-voilee-57210428.html
(with geo-restrictiction and time-limited availability)
The new player enables the viewer to choose the audio language and subtitle, however youtube-dl does not currently detect the additional languages (only the French audio, identified as "dash-audio_fra=XXX") nor subtitles:

> $ youtube-dl -v -F https://www.tf1.fr/tmc/hercule-poirot/videos/hercule-poirot-saison-02-episode-02-la-femme-voilee-57210428.html

> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'-v', u'-F', u'https://www.tf1.fr/tmc/hercule-poirot/videos/hercule-poirot-saison-02-episode-02-la-femme-voilee-57210428.html']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2019.09.12.1
> [debug] Python version 2.7.13 (CPython) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.11
> [debug] exe versions: ffmpeg 4.1.1-static, ffprobe 4.1.1-static, phantomjs 2.1.1, rtmpdump 2.4
> [debug] Proxy map: {}
> [TF1] hercule-poirot-saison-02-episode-02-la-femme-voilee-57210428: Downloading webpage
> [wat.tv] 13659488: Downloading JSON metadata
> [wat.tv] 13659488: Downloading JSON metadata
> [wat.tv] 13659488: Downloading m3u8 information
> [wat.tv] 13659488: Downloading f4m manifest
> [wat.tv] 13659488: Downloading m3u8 information
> WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
> [wat.tv] 13659488: Downloading f4m manifest
> WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
> [wat.tv] 13659488: Downloading MPD manifest
> [wat.tv] 13659488: Downloading MPD manifest
> WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
> [info] Available formats for 13659488:
> format code            extension  resolution note
> dash-audio_fra=64000   m4a        audio only [fr] DASH audio   64k , m4a_dash container, mp4a.40.2 (48000Hz)
> hls-68                 mp4        audio only   68k , mp4a.40.2@ 64k
> dash-audio_fra=128000  m4a        audio only [fr] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
> hls-136                mp4        audio only  136k , mp4a.40.2@128k
> dash-video=200039      mp4        416x234    DASH video  200k , mp4_dash container, avc1.42C01E, 25fps, video only
> dash-video=400077      mp4        480x270    DASH video  400k , mp4_dash container, avc1.42C01E, 25fps, video only
> dash-video=600114      mp4        640x360    DASH video  600k , mp4_dash container, avc1.42C01E, 25fps, video only
> dash-video=1200332     mp4        1024x576   DASH video 1200k , mp4_dash container, avc1.4D401F, 25fps, video only
> dash-video=1700571     mp4        1024x576   DASH video 1700k , mp4_dash container, avc1.4D401F, 25fps, video only
> dash-video=2500983     mp4        1280x720   DASH video 2500k , mp4_dash container, avc1.4D401F, 25fps, video only
> hds-264                flv        416x234     264k 
> hls-280                mp4        416x234     280k , avc1.66.30@ 200k, 25.0fps, mp4a.40.2@ 64k
> hds-528                flv        480x270     528k 
> hls-560                mp4        480x270     560k , avc1.66.30@ 400k, 25.0fps, mp4a.40.2@128k
> hds-728                flv        640x360     728k 
> hls-772                mp4        640x360     772k , avc1.66.30@ 600k, 25.0fps, mp4a.40.2@128k
> hds-1328               flv        1024x576   1328k 
> hls-1409               mp4        1024x576   1409k , avc1.77.31@1200k, 25.0fps, mp4a.40.2@128k
> hds-1828               flv        1024x576   1828k 
> hls-1939               mp4        1024x576   1939k , avc1.77.31@1700k, 25.0fps, mp4a.40.2@128k
> hds-2628               flv        1280x720   2628k 
> hls-2787               mp4        1280x720   2787k , avc1.77.31@2500k, 25.0fps, mp4a.40.2@128k (best)

> $ youtube-dl -v --list-subs https://www.tf1.fr/tmc/hercule-poirot/videos/hercule-poirot-saison-02-episode-02-la-femme-voilee-57210428.html
> 

> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'-v', u'--list-subs', u'https://www.tf1.fr/tmc/hercule-poirot/videos/hercule-poirot-saison-02-episode-02-la-femme-voilee-57210428.html']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2019.09.12.1
> [debug] Python version 2.7.13 (CPython) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.11
> [debug] exe versions: ffmpeg 4.1.1-static, ffprobe 4.1.1-static, phantomjs 2.1.1, rtmpdump 2.4
> [debug] Proxy map: {}
> [TF1] hercule-poirot-saison-02-episode-02-la-femme-voilee-57210428: Downloading webpage
> [wat.tv] 13659488: Downloading JSON metadata
> [wat.tv] 13659488: Downloading JSON metadata
> [wat.tv] 13659488: Downloading m3u8 information
> [wat.tv] 13659488: Downloading f4m manifest
> [wat.tv] 13659488: Downloading m3u8 information
> WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
> [wat.tv] 13659488: Downloading f4m manifest
> WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
> [wat.tv] 13659488: Downloading MPD manifest
> [wat.tv] 13659488: Downloading MPD manifest
> WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
> 13659488 has no subtitles

Moreover, as shown above, youtube-dl is not able to download the MPD manifest:

> WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found

However, with the help of "Stream Detector" Firefox extension, there was no problem identifying the MPD manifest of the example video, which is:
https://das-q1-ssl.tf1.fr/2/USP-0x0/94/88/13659488/ssm/036dc9a4353cb3e7ffd68e2391505272fcf13e208ba027358f785857bb8e3077.ism/13659488.mpd?e=1568330605&max_bitrate=2800000&st=ovfrLm4zqeCI2_EBwBcIMg&vk=MTM2NTk0ODgubXBk

Using youtube-dl on this url enables detecting the additional audio streams (identified as "audio_eng=XXX" for the example video, the original audio of which is in English) and downloading them:

> $ youtube-dl -v -F "https://das-q1-ssl.tf1.fr/2/USP-0x0/94/88/13659488/ssm/036dc9a4353cb3e7ffd68e2391505272fcf13e208ba027358f785857bb8e3077.ism/13659488.mpd?e=1568330605&max_bitrate=2800000&st=ovfrLm4zqeCI2_EBwBcIMg&vk=MTM2NTk0ODgubXBk"

> [debug] System config: []

> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'-v', u'-F', u'https://das-q1-ssl.tf1.fr/2/USP-0x0/94/88/13659488/ssm/036dc9a4353cb3e7ffd68e2391505272fcf13e208ba027358f785857bb8e3077.ism/13659488.mpd?e=1568330605&max_bitrate=2800000&st=ovfrLm4zqeCI2_EBwBcIMg&vk=MTM2NTk0ODgubXBk']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2019.09.12.1
> [debug] Python version 2.7.13 (CPython) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.11
> [debug] exe versions: ffmpeg 4.1.1-static, ffprobe 4.1.1-static, phantomjs 2.1.1, rtmpdump 2.4
> [debug] Proxy map: {}
> [generic] 13659488: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] 13659488: Downloading webpage
> [generic] 13659488: Extracting information
> WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
> WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
> [info] Available formats for 13659488:
> format code       extension  resolution note
> audio_eng=64000   m4a        audio only [en] DASH audio   64k , m4a_dash container, mp4a.40.2 (48000Hz)
> audio_fra=64000   m4a        audio only [fr] DASH audio   64k , m4a_dash container, mp4a.40.2 (48000Hz)
> audio_eng=128000  m4a        audio only [en] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
> audio_fra=128000  m4a        audio only [fr] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
> video=200039      mp4        416x234    DASH video  200k , mp4_dash container, avc1.42C01E, 25fps, video only
> video=400077      mp4        480x270    DASH video  400k , mp4_dash container, avc1.42C01E, 25fps, video only
> video=600114      mp4        640x360    DASH video  600k , mp4_dash container, avc1.42C01E, 25fps, video only
> video=1200332     mp4        1024x576   DASH video 1200k , mp4_dash container, avc1.4D401F, 25fps, video only
> video=1700571     mp4        1024x576   DASH video 1700k , mp4_dash container, avc1.4D401F, 25fps, video only
> video=2500983     mp4        1280x720   DASH video 2500k , mp4_dash container, avc1.4D401F, 25fps, video only (best)

but not the subtitles:

> $ youtube-dl -v --list-subs "https://das-q1-ssl.tf1.fr/2/USP-0x0/94/88/13659488/ssm/036dc9a4353cb3e7ffd68e2391505272fcf13e208ba027358f785857bb8e3077.ism/13659488.mpd?e=1568330605&max_bitrate=2800000&st=ovfrLm4zqeCI2_EBwBcIMg&vk=MTM2NTk0ODgubXBk"

> 
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'-v', u'--list-subs', u'https://das-q1-ssl.tf1.fr/2/USP-0x0/94/88/13659488/ssm/036dc9a4353cb3e7ffd68e2391505272fcf13e208ba027358f785857bb8e3077.ism/13659488.mpd?e=1568330605&max_bitrate=2800000&st=ovfrLm4zqeCI2_EBwBcIMg&vk=MTM2NTk0ODgubXBk']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2019.09.12.1
> [debug] Python version 2.7.13 (CPython) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.11
> [debug] exe versions: ffmpeg 4.1.1-static, ffprobe 4.1.1-static, phantomjs 2.1.1, rtmpdump 2.4
> [debug] Proxy map: {}
> [generic] 13659488: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] 13659488: Downloading webpage
> [generic] 13659488: Extracting information
> WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
> WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
> 13659488 has no subtitles

However, downloading the MPD manifest and checking its content shows that the subtitles are described in the MPD manifest:

> $ wget -c "https://das-q1-ssl.tf1.fr/2/USP-0x0/94/88/13659488/ssm/036dc9a4353cb3e7ffd68e2391505272fcf13e208ba027358f785857bb8e3077.ism/13659488.mpd?e=1568330605&max_bitrate=2800000&st=ovfrLm4zqeCI2_EBwBcIMg&vk=MTM2NTk0ODgubXBk" -O 13659488.mpd.txt

Here is the downloaded MPD manifest:
[13659488.mpd.txt](https://github.com/ytdl-org/youtube-dl/files/3603230/13659488.mpd.txt)
Subtitles sections seem to be described from line 80 in this example file.

Therefore, would it be possible to add support in youtube-dl for the additional audio and subtitles of tf1.fr videos, either through an improved detection and use of the MPD manifest or through any other approach?

Thanks in advance for your help.

**Comment by JerryKane** [comment]
For the sake of completeness, I should mention that there are both DRM-(partially)-protected videos and unprotected videos on tf1.fr.
The video provided as an example in my original message is an unprotected one and the new approach suggested i.e. detecting the MPD manifest in order to download the additional streams works almost perfectly (original audio can be downloaded but not the subtitles which are not currently detected by youtube-dl although they are described in the manifest).

However, in the case of DRM-(partially)-protected videos, the MPD approach fails (youtube-dl says it could not detect any video format) and one should probably keep relying on the current approach which enables at least to download the video with the French-dubbed audio.
Here is an example with a DRM-(partially)-protected video:
https://www.tf1.fr/tf1/swat/videos/s-w-a-t-s02-e10-1000-joules-36649080.html

> youtube-dl -F -v https://www.tf1.fr/tf1/swat/videos/s-w-a-t-s02-e10-1000-joules-36649080.html
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'-F', u'-v', u'https://www.tf1.fr/tf1/swat/videos/s-w-a-t-s02-e10-1000-joules-36649080.html']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2019.09.12.1
> [debug] Python version 2.7.13 (CPython) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.11
> [debug] exe versions: ffmpeg 4.1.1-static, ffprobe 4.1.1-static, phantomjs 2.1.1, rtmpdump 2.4
> [debug] Proxy map: {}
> [TF1] s-w-a-t-s02-e10-1000-joules-36649080: Downloading webpage
> [wat.tv] 13662036: Downloading JSON metadata
> [wat.tv] 13662036: Downloading JSON metadata
> [wat.tv] 13662036: Downloading m3u8 information
> [wat.tv] 13662036: Downloading f4m manifest
> [wat.tv] 13662036: Downloading m3u8 information
> WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
> [wat.tv] 13662036: Downloading f4m manifest
> WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
> [wat.tv] 13662036: Downloading MPD manifest
> [wat.tv] 13662036: Downloading MPD manifest
> WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
> [info] Available formats for 13662036:
> format code            extension  resolution note
> dash-audio_fra=64000   m4a        audio only [fr] DASH audio   64k , m4a_dash container, mp4a.40.2 (48000Hz)
> hls-68                 mp4        audio only   68k , mp4a.40.2@ 64k
> dash-audio_fra=128000  m4a        audio only [fr] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
> hls-136                mp4        audio only  136k , mp4a.40.2@128k
> dash-video=200047      mp4        416x234    DASH video  200k , mp4_dash container, avc1.42C01E, 25fps, video only
> dash-video=400098      mp4        480x270    DASH video  400k , mp4_dash container, avc1.42C01E, 25fps, video only
> dash-video=600135      mp4        640x360    DASH video  600k , mp4_dash container, avc1.42C01E, 25fps, video only
> dash-video=1200413     mp4        1024x576   DASH video 1200k , mp4_dash container, avc1.4D401F, 25fps, video only
> dash-video=1700593     mp4        1024x576   DASH video 1700k , mp4_dash container, avc1.4D401F, 25fps, video only
> dash-video=2500856     mp4        1280x720   DASH video 2500k , mp4_dash container, avc1.4D401F, 25fps, video only
> hds-264                flv        416x234     264k 
> hls-280                mp4        416x234     280k , avc1.66.30@ 200k, 25.0fps, mp4a.40.2@ 64k
> hds-528                flv        480x270     528k 
> hls-560                mp4        480x270     560k , avc1.66.30@ 400k, 25.0fps, mp4a.40.2@128k
> hds-728                flv        640x360     728k 
> hls-772                mp4        640x360     772k , avc1.66.30@ 600k, 25.0fps, mp4a.40.2@128k
> hds-1328               flv        1024x576   1328k 
> hls-1409               mp4        1024x576   1409k , avc1.77.31@1200k, 25.0fps, mp4a.40.2@128k
> hds-1828               flv        1024x576   1828k 
> hls-1939               mp4        1024x576   1939k , avc1.77.31@1700k, 25.0fps, mp4a.40.2@128k
> hds-2628               flv        1280x720   2628k 
> hls-2787               mp4        1280x720   2787k , avc1.77.31@2500k, 25.0fps, mp4a.40.2@128k (best)

As you can see, both video and French-dubbed audio ("hls-X" and "dash-audio_fra=X") are detected and downloaded.
The corresponding MPD manifest can be found at "https://das-q1-ssl.tf1.fr/2/USP-0x0/20/36/13662036/ssm/3d95fc4e4adfe977133d28e52f44711c8bf8d8ae31c3669b9bb068493accd712.ism/13662036.mpd?e=1569581873&max_bitrate=2800000&st=1jhm6l-QG2d735AyXcr1pg&vk=MTM2NjIwMzYubXBk"

And, as mentioned, trying to use youtube-dl on this MPD manifest does not enable to detect any stream (although there are in fact streams described in the MPD file but maybe due to the DRM-protection, youtube-dl says that no stream is available?):

> youtube-dl -v -F "https://das-q1-ssl.tf1.fr/2/USP-0x0/20/36/13662036/ssm/3d95fc4e4adfe977133d28e52f44711c8bf8d8ae31c3669b9bb068493accd712.ism/13662036.mpd?e=1569581873&max_bitrate=2800000&st=1jhm6l-QG2d735AyXcr1pg&vk=MTM2NjIwMzYubXBk"
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'-v', u'-F', u'https://das-q1-ssl.tf1.fr/2/USP-0x0/20/36/13662036/ssm/3d95fc4e4adfe977133d28e52f44711c8bf8d8ae31c3669b9bb068493accd712.ism/13662036.mpd?e=1569581873&max_bitrate=2800000&st=1jhm6l-QG2d735AyXcr1pg&vk=MTM2NjIwMzYubXBk']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2019.09.12.1
> [debug] Python version 2.7.13 (CPython) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.11
> [debug] exe versions: ffmpeg 4.1.1-static, ffprobe 4.1.1-static, phantomjs 2.1.1, rtmpdump 2.4
> [debug] Proxy map: {}
> [generic] 13662036: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] 13662036: Downloading webpage
> [generic] 13662036: Extracting information
> WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
> WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
> ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
>     ie_result = ie.extract(url)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
>     ie_result = self._real_extract(url)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2395, in _real_extract
>     self._sort_formats(info_dict['formats'])
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
>     raise ExtractorError('No video formats found')
> ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.youtube-dl -v -F "https://das-q1-ssl.tf1.fr/2/USP-0x0/20/36/13662036/ssm/3d95fc4e4adfe977133d28e52f44711c8bf8d8ae31c3669b9bb068493accd712.ism/13662036.mpd?e=1569581873&max_bitrate=2800000&st=1jhm6l-QG2d735AyXcr1pg&vk=MTM2NjIwMzYubXBk"
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'-v', u'-F', u'https://das-q1-ssl.tf1.fr/2/USP-0x0/20/36/13662036/ssm/3d95fc4e4adfe977133d28e52f44711c8bf8d8ae31c3669b9bb068493accd712.ism/13662036.mpd?e=1569581873&max_bitrate=2800000&st=1jhm6l-QG2d735AyXcr1pg&vk=MTM2NjIwMzYubXBk']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2019.09.12.1
> [debug] Python version 2.7.13 (CPython) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.11
> [debug] exe versions: ffmpeg 4.1.1-static, ffprobe 4.1.1-static, phantomjs 2.1.1, rtmpdump 2.4
> [debug] Proxy map: {}
> [generic] 13662036: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] 13662036: Downloading webpage
> [generic] 13662036: Extracting information
> WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
> WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
> ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
>     ie_result = ie.extract(url)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
>     ie_result = self._real_extract(url)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2395, in _real_extract
>     self._sort_formats(info_dict['formats'])
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
>     raise ExtractorError('No video formats found')
> ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

If multiple stream detection approaches can be combined for a same website in a youtube-dl "plugin", maybe always using both approaches for all tf1.fr videos could be the easiest way to cover all cases, with no need of detecting whether there are DRM beforehand:
- in the case of an unprotected video, youtube-dl would therefore detect the streams it already detects with the current approach AND the additional streams with the MPD approach;
- in the case of a DRM-(partially)-protected videos, youtube-dl would therefore still detect the streams it already detects with the current approach AND no additional stream since it would not detect any with the MPD approach.

Hope it helps investigating the issue.

**Comment by remitamine** [comment]
both URLs are no longer accessible.
