### ISSUE TITLE
drop py2exe since py2.7 support is going to be dropped

### ISSUE THREAD

**Issue by NewUserHa** [ytdl-org/youtube-dl#22394]
## Checklist
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description
I was curious about how executable zip file of youtube-dl works then found it's using a patched py2exe. (**windows**)
The idea is awesome and useful. but it can't be used on other projects and it's pity.

python2.7 will not be supported very soon.
would you like to move the building part of youtube-dl from 2.7 to 3.x(>4)? and it'll also be great if the executable system can also be used on other projects. since the `zipapp` module feels terriable.

thanks

**Comment by dstftw** [comment]
Exe is built with python 3.4.

**Comment by NewUserHa** [comment]
then https://www.python.org/downloads/release/python-3410/ python 3.4 is already retired
