### ISSUE TITLE
Netgear cable modem/router stops working during download

### ISSUE THREAD

**Issue by scott-milano** [ytdl-org/youtube-dl#22391]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Brief: Using youtube-dl causes my router to stop working.  Is this a known issue?  Will ISPs disconnect a router to stop downloads?

I'm using the latest youtube-dl: 2019.09.01 on Ubuntu 16.04.  My router/cable modem is a Netgear C3700-100NAS with Firmware: V2.02.22.   ISP is Comcast in the eastern us.  I'm trying to download the playlist:
https://www.youtube.com/watch?v=7rc7n-okKC0&list=PLHlQmm96_F4kQ9whFoaBptIw1n38v_3Zk

As I get 8-10 downloaded, my router stops working and I am unable to access the internet.  Trying to open a web page fails with name service error, and I cannot ping the comcast name serivice 75.75.76.76 or 8.8.8.8.  To clear the failure I have to reboot the Netgear router.   Then I can get a few more downloaded before the internet goes down again.  My internet provider is Comcast.  Is this a known issue, and is there an easy fix?  Is Comcast cutting me off?

To clear the issue I need to reboot the netgear cable modem/router.

Since I'm getting partial downloads, I've switched to downloading individual videos, and my command line is:
youtube-dl -x --audio-format=mp3 --audio-quality=7 https://www.youtube.com/watch?v=W_3Jq0P1uQA

I will try downloading via a VPN to see if things improve.

**Comment by Hrxn** [comment]
Sounds strange, does this ever happen with any other downloads as well?
Customer premise equipment can be accessed by the ISP (TR-069), so this is something that's theoretically possible, although it sounds still unlikely as described here.

Trying a VPN sounds reasonable. Test with another router to rule out any hardware issue if necessary. And maybe contact your ISP to see if they know something.

**Comment by bittaurus** [comment]
If you're losing connection when sending continuous data over your cable modem, you should contact your ISP.  Comcast offers support on their forum at https://forums.xfinity.com/t5/Your-Home-Network/bd-p/YHN if you want to contact them directly.  They pull logs off your router and try to figure out why your internet is failing.

**Comment by scott-milano** [comment]
> Sounds strange, does this ever happen with any other downloads as well?

No, and my internet connection is heavily used.  This only happens with extended download session using youtube-dl.  I would guess this uncovers some obscure firmware bug in my cable modem, or Comcast's equipment really doesn't like what youtube-dl is doing, and cuts me off until I restart and get a DHCP address again.

> Customer premise equipment can be accessed by the ISP (TR-069), so this is something that's theoretically possible, although it sounds still unlikely as described here.
> 

I'm just guessing.  I have some basic understanding of IP sockets, a little knowledge is a dangerous thing levels maybe, but youtube-dl has to play some minor tricks to download from youtube, maybe comcast gets triggered with these files.  But clearly wild speculation :)

> Trying a VPN sounds reasonable. Test with another router to rule out any hardware issue if necessary. And maybe contact your ISP to see if they know something.

The VPN worked.  Also I'm really only trying to get the audio and changing options really sped things up dramatically.  The default option took 30 minutes or more a video, even with -f bestaudio.  Changing to -f 18 made the files download in about a minute each.

You can close this issue.
