### ISSUE TITLE
Some YouTube downloads failing with ERROR: Did not get any data blocks

### ISSUE THREAD

**Issue by jellybaby** [ytdl-org/youtube-dl#22407]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
melanie:youtube-dl david$ ./youtube-dl -v laTOEfGsLi8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'laTOEfGsLi8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 2.7.10 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] laTOEfGsLi8: Downloading webpage
[youtube] laTOEfGsLi8: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r7---sn-cu-auol.googlevideo.com/videoplayback?expire=1568557218&ei=QfR9XdnMNZrqVJ3GsPAE&ip=146.199.185.236&id=o-AJmhlOOrjB32ryLKU_utgHrBmBsAeNFo7pDKKWndA0sO&itag=22&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-cu-auol%2Csn-5hnekn76&ms=au%2Conr&mv=m&mvi=6&pl=25&initcwndbps=1202500&mime=video%2Fmp4&ratebypass=yes&dur=433.818&lmt=1568491439642082&mt=1568535462&fvip=1&c=WEB&txp=3516222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRAIgbuopTHfnGdQOtK_njDrD00f3-DrS99oHO3Zpaby2oN0CIHqbi7uu43sYOIS1RY8RIAIaxxedZNx8F6IJ1ceZOxo4&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAJQEOqNImpSubWKZcP3-MALN8PAgBiU_6A5fu_e-3emkAiA_3LR-4PHXJkZtFNHQH_v_GKFDJ9QY-XspLBIIouULnw%3D%3D'
[download] Resuming download at byte 148340


ERROR: Did not get any data blocks
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "./youtube-dl/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "./youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2010, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1642, in process_video_result
    self.process_info(new_info)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1917, in process_info
    success = dl(filename, info_dict)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1856, in dl
    return fd.download(name, info)
  File "./youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "./youtube-dl/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "./youtube-dl/youtube_dl/downloader/http.py", line 312, in download
    self.report_error('Did not get any data blocks')
  File "./youtube-dl/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 586, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

```

## Description

Some videos are failing to download, resulting in 'ERROR: Did not get any data blocks'. Problem is affecting me on multiple OSs in multiple regions across several videos (eg jIQmdKmtxC4 also).

**Comment by dstftw** [comment]
Server side Youtube issue.

**Comment by jellybaby** [comment]
In what way is this a server side issue when downloading is possible with other tools (eg y2mate)?

**Comment by dstftw** [comment]
Wrong. It fails with the same error on this 22 format since this is Youtube side error as was already said.

**Comment by jellybaby** [comment]
Thanks for being a little bit more specific.

You are saying that YouTube is advertising a format as available but it isn't so I need to select a different one?

**Comment by fiuzaB** [comment]
Same problem here. Any workaround  ?

**Comment by jellybaby** [comment]
Use -F to list the formats and then pick something else. For example:

~$ youtube-dl  laTOEfGsLi8 -F

[youtube] laTOEfGsLi8: Downloading webpage
[youtube] laTOEfGsLi8: Downloading video info webpage
[info] Available formats for laTOEfGsLi8:
format code  extension  resolution note
249          webm       audio only tiny   56k , opus @ 50k (48000Hz), 2.56MiB
250          webm       audio only tiny   75k , opus @ 70k (48000Hz), 3.28MiB
140          m4a        audio only tiny  130k , m4a_dash container, mp4a.40.2@128k (44100Hz), 6.70MiB
251          webm       audio only tiny  148k , opus @160k (48000Hz), 6.47MiB
160          mp4        256x144    144p  106k , avc1.4d400c, 24fps, video only, 3.00MiB
278          webm       256x144    144p  127k , webm container, vp9, 24fps, video only, 5.02MiB
242          webm       426x240    240p  214k , vp9, 24fps, video only, 5.95MiB
133          mp4        426x240    240p  310k , avc1.4d4015, 24fps, video only, 6.77MiB
243          webm       640x360    360p  388k , vp9, 24fps, video only, 10.47MiB
134          mp4        640x360    360p  560k , avc1.4d401e, 24fps, video only, 11.94MiB
244          webm       854x480    480p  589k , vp9, 24fps, video only, 16.06MiB
135          mp4        854x480    480p  750k , avc1.4d401e, 24fps, video only, 17.62MiB
247          webm       1280x720   720p 1047k , vp9, 24fps, video only, 28.84MiB
136          mp4        1280x720   720p 1150k , avc1.4d401f, 24fps, video only, 27.80MiB
248          webm       1920x1080  1080p 2641k , vp9, 24fps, video only, 94.02MiB
137          mp4        1920x1080  1080p 3930k , avc1.640028, 24fps, video only, 109.26MiB
43           webm       640x360    360p , vp8.0, vorbis@128k, 37.55MiB
18           mp4        640x360    360p  534k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 27.64MiB
22           mp4        1280x720   720p 1848k , avc1.64001F, mp4a.40.2@192k (44100Hz) (best)

~$ youtube-dl  laTOEfGsLi8 -f 43
[youtube] laTOEfGsLi8: Downloading webpage
[youtube] laTOEfGsLi8: Downloading video info webpage
[download] Destination: Old Files - Rags To Riches-laTOEfGsLi8.webm
[download] 100% of 37.55MiB in 00:00

**Comment by fiuzaB** [comment]
Awesome. It worked. Thanks @jellybaby .
