### ISSUE TITLE
can't download from youtube -f 22

### ISSUE THREAD

**Issue by tenyugayu** [ytdl-org/youtube-dl#22405]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

```

## Description

ERROR: Did not get any data blocks

https://www.youtube.com/watch?v=_mTx8BckEdA -f 22
https://www.youtube.com/watch?v=4XyWPb6E88s -f 22
https://www.youtube.com/watch?v=vzkhjWNLbys -f 22
https://www.youtube.com/watch?v=o_QT9MDEWbo -f 22

**Comment by dstftw** [comment]
Most likely server side Youtube issue.

**Comment by arclite7** [comment]
I cannot now download any YT titles. 
I have checked that my version of YT-dl is the latest
I have checked the prescribed update procedure
The title has been copied directly from the address dialogue box on Firefox for Linux Mint 19v1
sudo youtube-dl --verbose https://www.youtube.com/watch?v=-g9MQ8e93Yw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=-g9MQ8e93Yw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.8 (CPython) - Linux-4.15.0-60-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: ffmpeg 3.4.6-0ubuntu0.18.04.1, ffprobe 3.4.6-0ubuntu0.18.04.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] -g9MQ8e93Yw: Downloading webpage
[youtube] -g9MQ8e93Yw: Downloading video info webpage
WARNING: Unable to extract video title
[youtube] -g9MQ8e93Yw: Extracting video information
ERROR: Unable to extract uploader name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1704, in _real_extract
    raise ExtractorError('Unable to extract uploader name')
youtube_dl.utils.ExtractorError: Unable to extract uploader name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
END =======================================

**Comment by Hrxn** [comment]
> [debug] youtube-dl version 2018.03.14
