### ISSUE TITLE
Downloading of hls live stream stops after x fragments

### ISSUE THREAD

**Issue by duracotton** [ytdl-org/youtube-dl#22401]
Hi,

I just wanted to download a live steam (hls), but youtube-dl (latest version) found only 295 fragments in the m3u8 manifest and stops downloading after reaching the last one (~327 MB). The length of this video is 29:30 minutes

The live stream went 1h 45 minutes.

Is it because the live stream server only holds back half an hour to rewind?

I attached the m3u8 file and the youtube-dl log.

Thank you very much.

Youtube-dl log:

> D:\Tool-Sammlung\youtube-dl>youtube-dl --list-formats https://www.zdf.de/kultur/musik-und-theater/anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104.html
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading webpage
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading JSON content
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading JSON metadata
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading m3u8 information
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading m3u8 information
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading m3u8 information
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading m3u8 information
[info] Available formats for anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104:
format code  extension  resolution note
hls-578-0    mp4        480x272     578k , avc1.4d401f, 25.0fps, mp4a.40.2
hls-578-1    mp4        480x272     578k , avc1.4d401f, 25.0fps, mp4a.40.2
hls-578-2    mp4        480x272     578k , avc1.4d401f, 25.0fps, mp4a.40.2
hls-578-3    mp4        480x272     578k , avc1.4d401f, 25.0fps, mp4a.40.2
hls-578-4    mp4        480x272     578k , avc1.4d401f, 25.0fps, mp4a.40.2
hls-578-5    mp4        480x272     578k , avc1.4d401f, 25.0fps, mp4a.40.2
hls-884-0    mp4        640x360     884k , avc1.4d401f, 25.0fps, mp4a.40.2
hls-884-1    mp4        640x360     884k , avc1.4d401f, 25.0fps, mp4a.40.2
hls-884-2    mp4        640x360     884k , avc1.4d401f, 25.0fps, mp4a.40.2
hls-884-3    mp4        640x360     884k , avc1.4d401f, 25.0fps, mp4a.40.2
hls-1620-0   mp4        852x480    1620k , avc1.4d401f, 25.0fps, mp4a.40.2
hls-1620-1   mp4        852x480    1620k , avc1.4d401f, 25.0fps, mp4a.40.2
hls-1620-2   mp4        852x480    1620k , avc1.4d401f, 25.0fps, mp4a.40.2
hls-1620-3   mp4        852x480    1620k , avc1.4d401f, 25.0fps, mp4a.40.2 (best)

>  D:\Tool-Sammlung\youtube-dl>youtube-dl -f hls-1620-3 https://www.zdf.de/kultur/musik-und-theater/anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104.html
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading webpage
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading JSON content
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading JSON metadata
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading m3u8 information
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading m3u8 information
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading m3u8 information
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 295
[download] Destination: Anne-Sophie Mutter spielt Filmmusik -anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104.mp4
[download] 100% of 327.61MiB in01:13

[m3u8.zip](https://github.com/ytdl-org/youtube-dl/files/3613091/m3u8.zip)

**Comment by dstftw** [comment]
```
> py -3.4 .\youtube_dl\__main__.py https://www.zdf.de/kultur/musik-und-theater/anne-sophie-mutter-spielt-filmmusik-3
sat-sendung-miz-104.html
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading webpage
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading JSON content
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading JSON metadata
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading m3u8 information
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading m3u8 information
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading f4m manifest
[ZDF] anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104: Downloading f4m manifest
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 541
[download] Destination: Anne-Sophie Mutter spielt Filmmusik -anne-sophie-mutter-spielt-filmmusik-3sat-sendung-miz-104.mp4
[download]   9.4% of ~1.65GiB at  4.62MiB/s ETA 09:56
ERROR: Interrupted by user
```
