### ISSUE TITLE
Debian update

### ISSUE THREAD

**Issue by smokinpete** [ytdl-org/youtube-dl#22417]
- [x ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones
-----
I've tried updating via sudo youtube-dl -U

But I get:
youtube-dl: error: youtube-dl's self-update mechanism is disabled on Debian

It seems as if the Debian repository still has youtube-dl (2019.01.17-1.1)

Does anyone know how I can enable the self-update mechanism?

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dstftw** [comment]
By removing Debian version and installing official version.

**Comment by smokinpete** [comment]
Great thanks!
