### ISSUE TITLE
<urlopen error [Errno 54] Connection reset by peer>

### ISSUE THREAD

**Issue by godlockin** [ytdl-org/youtube-dl#22415]
OS: Mac Majove 10.14.5
python: 3.7
youtube-dl: 
`➜ ~ brew install youtube-dl
Warning: youtube-dl 2019.09.01 is already installed and up-to-date
To reinstall 2019.09.01, run `brew reinstall youtube-dl``

when I tried to download a video in Youtube, the following exception alerted. while I can access the youtube page and watch the video at the same time.
`➜ ~ youtube-dl "https://www.youtube.com/watch?v=wV3N-wCRL2k"
[youtube] wV3N-wCRL2k: Downloading webpage
ERROR: Unable to download webpage: <urlopen error _ssl.c:1059: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:1059: The handshake operation timed out')))
➜ ~ youtube-dl -F  "https://www.youtube.com/watch?v=wV3N-wCRL2k"
[youtube] wV3N-wCRL2k: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 60] Operation timed out> (caused by URLError(TimeoutError(60, 'Operation timed out')))`

Am I used wrong command here?

**Comment by Hrxn** [comment]
1. youtube-dl is outdated
2. Seems like a network issue, are you behind the Great Chinese Firewall and does it reliably work in the browser?

**Comment by godlockin** [comment]
well, I re-run the install cmd this morning and which should make the ytdl be the latest release right? 
The same issue happens again.

For the 2., If it's a network issue, I shouldn't be able to open the original youtube webpage at the same network env, but the fact is, I can open the original page smoothly :(

Isn't it caused by some youtube migration or anti-spider features' release? 

`
youtube-dl -v  "https://www.youtube.com/watch?v=wV3N-wCRL2k"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=wV3N-wCRL2k']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.7.2 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] wV3N-wCRL2k: Downloading webpage
xERROR: Unable to download webpage: <urlopen error [Errno 60] Operation timed out> (caused by URLError(TimeoutError(60, 'Operation timed out')))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2229, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Users/stevenchen/anaconda3/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/stevenchen/anaconda3/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Users/stevenchen/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2724, in https_open
    req, **kwargs)
  File "/Users/stevenchen/anaconda3/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
`
