### ISSUE TITLE
Trying on Raspberry Pi (Raspbian)

### ISSUE THREAD

**Issue by DexyZL2** [ytdl-org/youtube-dl#22427]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
pi@dexyspi3:~ $ youtube-dl https://www.youtube.com/watch?v=dLcGPQ2BcBY --verbose[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=dLcGPQ2BcBY', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.18.1
[debug] Python version 3.5.3 - Linux-4.19.42-v7+-armv7l-with-debian-9.9
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] dLcGPQ2BcBY: Downloading webpage
[youtube] dLcGPQ2BcBY: Downloading video info webpage
ERROR: dLcGPQ2BcBY: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1502, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: dLcGPQ2BcBY: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
Reduced to a Raspberry Pi V3B at a rest home, I've found this command-line downloader is the only one that will actually install. I'd really rather have ClipGrab at my disposal, but that's only available through a (*buntu) ppa. I don't know if this missing "token" is due to the file I'm trying to download or an artifact of the OS.

**Comment by jrowens** [comment]
> [debug] youtube-dl version 2017.05.18.1

There's your problem, right there. YouTube protocol has changed a lot in almost 2½ years. Update it if you can.

**Comment by DexyZL2** [comment]
Thanks. Suspected, but only noticed after posting. Build from source will be a task: not even sure required libraries are available in Raspbian. Here gopers, deep[ dive into unfamiliar waters ... :)
