### ISSUE TITLE
Not receiving data from a video

### ISSUE THREAD

**Issue by wellinton-capixaba** [ytdl-org/youtube-dl#22429]
Tried this command: 
[quote]youtube-dl -f 22  https://www.youtube.com/watch?v=pAQsTFy_2j8[/quote]

and received [quote][youtube] pAQsTFy_2j8: Downloading webpage
[youtube] pAQsTFy_2j8: Downloading video info webpage
[download] Resuming download at byte 738387

ERROR: Did not get any data blocks[/quote]

So, is the error is from my youtube-dl or from youtube?

**Comment by dstftw** [comment]
Youtube.
