### ISSUE TITLE
Search for playlists only

### ISSUE THREAD

**Issue by orena1** [ytdl-org/youtube-dl#22436]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, is there a way to constrain youtube search to return only playlists?
Currently, I am doing the following:

```python
import youtube_dl

ydl_opts = {
    'quiet': True,
    'skip_download': True,
    'forcetitle': True,
    'forceurl': True,
}
number_of_results = 100
search_for = 'Fun'

# Extracts information using the "ytsearch:string" method
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    infoSearched = ydl.extract_info("ytsearch{}:{}".format(number_of_results,search_for))

```
Is there something that I can add to ydl_opts so that it will return only playlists?

Thanks

**Comment by dstftw** [comment]
Use youtube search URL.

**Comment by orena1** [comment]
@dstftw  thanks, can you direct me to an example on how to do it? where do I put the url ? and can I set the number of results that I would like?
Many thanks.
