### ISSUE TITLE
Fix progress-bar when merging formats.

### ISSUE THREAD

**Issue by Elite** [ytdl-org/youtube-dl#2243]
When merging DASH audio and video (https://github.com/rg3/youtube-dl/pull/2089?source=cc), the `progress` status is shown for individual downloads (resets to zero). The ideal situation (total download size) would be to fetch the audio and video file-sizes before downloading and using the total download size as max value updating the percentage bar accordingly.

**Comment by dirkf** [comment]
I hope this is how it works now.
