### ISSUE TITLE
download video to dplay

### ISSUE THREAD

**Issue by taurus1990T** [ytdl-org/youtube-dl#22444]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\Andrea\Downloads>youtube-dl  https://it.dplay.com/nove/rubio-alla-ricerca-del-gusto-perduto/stagione-1-episodio-3-verso-la-cina/ --output \dplay\rubio_3.mp4
[DPlayIt] stagione-1-episodio-3-verso-la-cina: Downloading webpage
ERROR: Unable to extract info url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

hi, I’m trying to download the third bet but it gives me this error, for the first two no problem

**Comment by dstftw** [comment]
You must pass authenticated cookies.
