### ISSUE TITLE
HTTP Error 470 on download

### ISSUE THREAD

**Issue by Fridock** [ytdl-org/youtube-dl#22445]
## Checklist

- [ ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
[dashsegments] Total fragments: 421
[download] Destination: manifest-manifest.mp4
[download] Got server HTTP error: HTTP Error 470: . Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 470: . Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 470: . Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 470: . Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 470: . Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 470: . Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 470: . Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 470: . Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 470: . Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 470: . Retrying fragment 1 (attempt 10 of 10)...
ERROR: giving up after 10 fragment retries
'ip' is not recognized as an internal or external command,
operable program or batch file.
'hash' is not recognized as an internal or external command,
operable program or batch file.

## Description

I'm getting weird errors on trying to download a stream, couldn't find anything on it too

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
