### ISSUE TITLE
Can't search mp3 files download from YouTube with youtube-dl

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#2245]
Hi,

I have downloaded a few files to mp3 with youtube-dl using `youtube-dl --extract-audio --audio-format mp3 -l [YOUTUBE VIDEO LINK]`. The output file I get plays fine but when I try to search in the file. An example would be that I have currently listened for 15 mins and I like to skip forward 10 mins to 25 mins, then it just jumps back to where I'm currently in the file (15 mins into the file). I've been downloading the file with Ubuntu 13.10 and I'm playing the file with the standard music player on Android 4.4. The skipping works fine if I use VLC player. Any suggestions on how I can fix the file to be able to search in the file with the standard Android music player?

**Comment by dirkf** [comment]
Historical audio processing issue.
