### ISSUE TITLE
Globo Authentication

### ISSUE THREAD

**Issue by DESKTOP-RX90B689** [ytdl-org/youtube-dl#22458]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', 'https://globoplay.globo.com/v/7932248/programa/', '-F', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.6.3 (CPython) - Linux-4.15.0-30deepin-generic-x86_64-with-debian-9.0
[debug] exe versions: avconv 3.2.12-1, avprobe 3.2.12-1, ffmpeg 3.2.12-1, ffprobe 3.2.12-1, rtmpdump 2.4
[debug] Proxy map: {}
[Globo] 7932248: Downloading JSON metadata
[Globo] 7932248: Downloading security hash for 7932248_manifest_360_1080_m3u8
[Globo] 7932248_manifest_360_1080_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 7932248: Downloading security hash for 7932248_manifest_360_1080_l_m3u8
[Globo] 7932248_manifest_360_1080_l_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 7932248: Downloading security hash for 7932248_manifest_90_720_m3u8
[Globo] 7932248_manifest_90_720_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 7932248: Downloading security hash for 7932248_manifest_240_720_m3u8
[Globo] 7932248_manifest_240_720_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 7932248: Downloading security hash for 7932248_manifest_90_720_l_m3u8
[Globo] 7932248_manifest_90_720_l_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 7932248: Downloading security hash for 7932248_manifest_90_480_m3u8
[Globo] 7932248_manifest_90_480_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 7932248: Downloading security hash for 7932248_manifest_360_1080_mpd
[Globo] 7932248_manifest_360_1080_mpd: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[Globo] 7932248: Downloading security hash for 7932248_manifest_360_2160_m3u8
[Globo] 7932248_manifest_360_2160_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 7932248: Downloading security hash for 7932248_manifest_240_720_l_m3u8
[Globo] 7932248_manifest_240_720_l_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 7932248: Downloading security hash for 7932248_manifest_360_2160_l_m3u8
[Globo] 7932248_manifest_360_2160_l_m3u8: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 7932248: Downloading security hash for 7932248_manifest_360_1080_l_manifest
[Globo] 7932248_manifest_360_1080_l_manifest: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden
[Globo] 7932248: Downloading security hash for 7932248_manifest_360_1080_l_mpd
[Globo] 7932248_manifest_360_1080_l_mpd: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[Globo] 7932248: Downloading security hash for 7932248_manifest_360_2160_mpd
[Globo] 7932248_manifest_360_2160_mpd: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[Globo] 7932248: Downloading security hash for 7932248_manifest_90_720_mpd
[Globo] 7932248_manifest_90_720_mpd: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/globo.py", line 155, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
## Description

please fix this authentication issue because with public videos the extractor works normally like this:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://globoplay.globo.com/v/7891028/', '-F', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.6.3 (CPython) - Linux-4.15.0-30deepin-generic-x86_64-with-debian-9.0
[debug] exe versions: avconv 3.2.12-1, avprobe 3.2.12-1, ffmpeg 3.2.12-1, ffprobe 3.2.12-1, rtmpdump 2.4
[debug] Proxy map: {}
[Globo] 7891028: Downloading JSON metadata
[Globo] 7891028: Downloading security hash for 5d6d73c05e19a7f14392a7f9_360_1080_m3u8
[Globo] 5d6d73c05e19a7f14392a7f9_360_1080_m3u8: Downloading m3u8 information
[Globo] 7891028: Downloading security hash for 5d6d73c05e19a7f14392a7f9_360_1080_l_m3u8
[Globo] 5d6d73c05e19a7f14392a7f9_360_1080_l_m3u8: Downloading m3u8 information
[Globo] 7891028: Downloading security hash for 5d6d73c05e19a7f14392a7f9_90_720_m3u8
[Globo] 5d6d73c05e19a7f14392a7f9_90_720_m3u8: Downloading m3u8 information
[Globo] 7891028: Downloading security hash for 5d6d73c05e19a7f14392a7f9_240_720_m3u8
[Globo] 5d6d73c05e19a7f14392a7f9_240_720_m3u8: Downloading m3u8 information
[Globo] 7891028: Downloading security hash for 5d6d73c05e19a7f14392a7f9_90_720_l_m3u8
[Globo] 5d6d73c05e19a7f14392a7f9_90_720_l_m3u8: Downloading m3u8 information
[Globo] 7891028: Downloading security hash for 5d6d73c05e19a7f14392a7f9_90_480_m3u8
[Globo] 5d6d73c05e19a7f14392a7f9_90_480_m3u8: Downloading m3u8 information
[Globo] 7891028: Downloading security hash for 5d6d73c05e19a7f14392a7f9_360_1080_mpd
[Globo] 5d6d73c05e19a7f14392a7f9_360_1080_mpd: Downloading MPD manifest
[Globo] 7891028: Downloading security hash for 5d6d73c05e19a7f14392a7f9_360_2160_m3u8
[Globo] 5d6d73c05e19a7f14392a7f9_360_2160_m3u8: Downloading m3u8 information
[Globo] 7891028: Downloading security hash for 5d6d73c05e19a7f14392a7f9_240_720_l_m3u8
[Globo] 5d6d73c05e19a7f14392a7f9_240_720_l_m3u8: Downloading m3u8 information
[Globo] 7891028: Downloading security hash for 5d6d73c05e19a7f14392a7f9_360_2160_l_m3u8
[Globo] 5d6d73c05e19a7f14392a7f9_360_2160_l_m3u8: Downloading m3u8 information
[Globo] 7891028: Downloading security hash for 5d6d73c05e19a7f14392a7f9_360_1080_l_manifest
[Globo] 5d6d73c05e19a7f14392a7f9_360_1080_l_manifest: Downloading ISM manifest
[Globo] 7891028: Downloading security hash for 5d6d73c05e19a7f14392a7f9_360_1080_l_mpd
[Globo] 5d6d73c05e19a7f14392a7f9_360_1080_l_mpd: Downloading MPD manifest
[Globo] 7891028: Downloading security hash for 5d6d73c05e19a7f14392a7f9_360_2160_mpd
[Globo] 5d6d73c05e19a7f14392a7f9_360_2160_mpd: Downloading MPD manifest
[Globo] 7891028: Downloading security hash for 5d6d73c05e19a7f14392a7f9_90_720_mpd
[Globo] 5d6d73c05e19a7f14392a7f9_90_720_mpd: Downloading MPD manifest
[info] Available formats for 7891028:
format code               extension  resolution note
mss-audio_por-128         isma       audio only  128k , AACL  (44100Hz)
dash-audio_por=128039-0   m4a        audio only [pt] DASH audio  128k , m4a_dash container, mp4a.40.2 (44100Hz)
dash-audio_por=128039-1   m4a        audio only [pt] DASH audio  128k , m4a_dash container, mp4a.40.2 (44100Hz)
dash-audio_por=128039-2   m4a        audio only [pt] DASH audio  128k , m4a_dash container, mp4a.40.2 (44100Hz)
dash-audio_por=128039-3   m4a        audio only [pt] DASH audio  128k , m4a_dash container, mp4a.40.2 (44100Hz)
dash-video_por=359000     mp4        640x360    [pt] DASH video  359k , mp4_dash container, avc1.64001E, video only
mss-video_por-629         ismv       640x360     629k , AVC1, video only
dash-video_por=629000-0   mp4        640x360    [pt] DASH video  629k , mp4_dash container, avc1.64001E, video only
dash-video_por=629000-1   mp4        640x360    [pt] DASH video  629k , mp4_dash container, avc1.64001E, video only
dash-video_por=629000-2   mp4        640x360    [pt] DASH video  629k , mp4_dash container, avc1.64001E, video only
dash-video_por=629000-3   mp4        640x360    [pt] DASH video  629k , mp4_dash container, avc1.64001E, video only
mss-video_por-994         ismv       854x480     994k , AVC1, video only
dash-video_por=994000-0   mp4        854x480    [pt] DASH video  994k , mp4_dash container, avc1.64001F, video only
dash-video_por=994000-1   mp4        854x480    [pt] DASH video  994k , mp4_dash container, avc1.64001F, video only
dash-video_por=994000-2   mp4        854x480    [pt] DASH video  994k , mp4_dash container, avc1.64001F, video only
dash-video_por=994000-3   mp4        854x480    [pt] DASH video  994k , mp4_dash container, avc1.64001F, video only
mss-video_por-1962        ismv       1280x720   1962k , AVC1, video only
dash-video_por=1962000-0  mp4        1280x720   [pt] DASH video 1962k , mp4_dash container, avc1.64001F, video only
dash-video_por=1962000-1  mp4        1280x720   [pt] DASH video 1962k , mp4_dash container, avc1.64001F, video only
dash-video_por=1962000-2  mp4        1280x720   [pt] DASH video 1962k , mp4_dash container, avc1.64001F, video only
dash-video_por=1962000-3  mp4        1280x720   [pt] DASH video 1962k , mp4_dash container, avc1.64001F, video only
mss-video_por-3571        ismv       1920x1080  3571k , AVC1, video only
dash-video_por=3571000-0  mp4        1920x1080  [pt] DASH video 3571k , mp4_dash container, avc1.640028, video only
dash-video_por=3571000-1  mp4        1920x1080  [pt] DASH video 3571k , mp4_dash container, avc1.640028, video only
dash-video_por=3571000-2  mp4        1920x1080  [pt] DASH video 3571k , mp4_dash container, avc1.640028, video only
hls-517-0                 mp4        640x360     517k , avc1.64001E@ 359k, mp4a.40.2@128k
hls-517-1                 mp4        640x360     517k , avc1.64001E@ 359k, mp4a.40.2@128k
hls-517-2                 mp4        640x360     517k , avc1.64001E@ 359k, mp4a.40.2@128k
hls-517-3                 mp4        640x360     517k , avc1.64001E@ 359k, mp4a.40.2@128k
hls-517-4                 mp4        640x360     517k , avc1.64001E@ 359k, mp4a.40.2@128k
hls-803-0                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-1                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-2                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-3                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-4                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-5                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-6                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-7                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-8                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-1190-0                mp4        854x480    1190k , avc1.64001F@ 994k, mp4a.40.2@128k
hls-1190-1                mp4        854x480    1190k , avc1.64001F@ 994k, mp4a.40.2@128k
hls-1190-2                mp4        854x480    1190k , avc1.64001F@ 994k, mp4a.40.2@128k
hls-1190-3                mp4        854x480    1190k , avc1.64001F@ 994k, mp4a.40.2@128k
hls-1190-4                mp4        854x480    1190k , avc1.64001F@ 994k, mp4a.40.2@128k
hls-1190-5                mp4        854x480    1190k , avc1.64001F@ 994k, mp4a.40.2@128k
hls-1190-6                mp4        854x480    1190k , avc1.64001F@ 994k, mp4a.40.2@128k
hls-1190-7                mp4        854x480    1190k , avc1.64001F@ 994k, mp4a.40.2@128k
hls-1190-8                mp4        854x480    1190k , avc1.64001F@ 994k, mp4a.40.2@128k
hls-2216-0                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-2216-1                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-2216-2                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-2216-3                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-2216-4                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-2216-5                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-2216-6                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-2216-7                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-3921-0                mp4        1920x1080  3921k , avc1.640028@3571k, mp4a.40.2@128k
hls-3921-1                mp4        1920x1080  3921k , avc1.640028@3571k, mp4a.40.2@128k
hls-3921-2                mp4        1920x1080  3921k , avc1.640028@3571k, mp4a.40.2@128k
hls-3921-3                mp4        1920x1080  3921k , avc1.640028@3571k, mp4a.40.2@128k (best)

So, I've read all the other globe extractor related issues and this one isn't duplicated. In all links with need authentication the error is the same

[...] _WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden_ [...]
[...] _No video formats found; please report this issue on https://yt-dl.org/bug_ [...]

For Globosatplay streaming the authentication is working correctly. The problem is only with Globoplay authentication.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'sat.txt', 'https://globosatplay.globo.com/gnt/v/7926076', '-F', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.6.3 (CPython) - Linux-4.15.0-30deepin-generic-x86_64-with-debian-9.0
[debug] exe versions: avconv 3.2.12-1, avprobe 3.2.12-1, ffmpeg 3.2.12-1, ffprobe 3.2.12-1, rtmpdump 2.4
[debug] Proxy map: {}
[Globo] 7926076: Downloading JSON metadata
[Globo] 7926076: Downloading security hash for 5d7fcba05e19a734662958e5_360_1080_m3u8
[Globo] 5d7fcba05e19a734662958e5_360_1080_m3u8: Downloading m3u8 information
[Globo] 7926076: Downloading security hash for 5d7fcba05e19a734662958e5_360_1080_l_m3u8
[Globo] 5d7fcba05e19a734662958e5_360_1080_l_m3u8: Downloading m3u8 information
[Globo] 7926076: Downloading security hash for 5d7fcba05e19a734662958e5_90_720_m3u8
[Globo] 5d7fcba05e19a734662958e5_90_720_m3u8: Downloading m3u8 information
[Globo] 7926076: Downloading security hash for 5d7fcba05e19a734662958e5_240_720_m3u8
[Globo] 5d7fcba05e19a734662958e5_240_720_m3u8: Downloading m3u8 information
[Globo] 7926076: Downloading security hash for 5d7fcba05e19a734662958e5_90_720_l_m3u8
[Globo] 5d7fcba05e19a734662958e5_90_720_l_m3u8: Downloading m3u8 information
[Globo] 7926076: Downloading security hash for 5d7fcba05e19a734662958e5_90_480_m3u8
[Globo] 5d7fcba05e19a734662958e5_90_480_m3u8: Downloading m3u8 information
[Globo] 7926076: Downloading security hash for 5d7fcba05e19a734662958e5_360_1080_mpd
[Globo] 5d7fcba05e19a734662958e5_360_1080_mpd: Downloading MPD manifest
[Globo] 7926076: Downloading security hash for 5d7fcba05e19a734662958e5_360_2160_m3u8
[Globo] 5d7fcba05e19a734662958e5_360_2160_m3u8: Downloading m3u8 information
[Globo] 7926076: Downloading security hash for 5d7fcba05e19a734662958e5_240_720_l_m3u8
[Globo] 5d7fcba05e19a734662958e5_240_720_l_m3u8: Downloading m3u8 information
[Globo] 7926076: Downloading security hash for 5d7fcba05e19a734662958e5_360_2160_l_m3u8
[Globo] 5d7fcba05e19a734662958e5_360_2160_l_m3u8: Downloading m3u8 information
[Globo] 7926076: Downloading security hash for 5d7fcba05e19a734662958e5_360_1080_l_manifest
[Globo] 5d7fcba05e19a734662958e5_360_1080_l_manifest: Downloading ISM manifest
[Globo] 7926076: Downloading security hash for 5d7fcba05e19a734662958e5_360_1080_l_mpd
[Globo] 5d7fcba05e19a734662958e5_360_1080_l_mpd: Downloading MPD manifest
[Globo] 7926076: Downloading security hash for 5d7fcba05e19a734662958e5_360_2160_mpd
[Globo] 5d7fcba05e19a734662958e5_360_2160_mpd: Downloading MPD manifest
[Globo] 7926076: Downloading security hash for 5d7fcba05e19a734662958e5_90_720_mpd
[Globo] 5d7fcba05e19a734662958e5_90_720_mpd: Downloading MPD manifest
[info] Available formats for 7926076:
format code               extension  resolution note
mss-audio_por-128         isma       audio only  128k , AACL  (44100Hz)
dash-audio_por=128001-0   m4a        audio only [pt] DASH audio  128k , m4a_dash container, mp4a.40.2 (44100Hz)
dash-audio_por=128001-1   m4a        audio only [pt] DASH audio  128k , m4a_dash container, mp4a.40.2 (44100Hz)
dash-audio_por=128001-2   m4a        audio only [pt] DASH audio  128k , m4a_dash container, mp4a.40.2 (44100Hz)
dash-audio_por=128001-3   m4a        audio only [pt] DASH audio  128k , m4a_dash container, mp4a.40.2 (44100Hz)
dash-video_por=360000     mp4        640x360    [pt] DASH video  360k , mp4_dash container, avc1.64001E, video only
mss-video_por-629         ismv       640x360     629k , AVC1, video only
dash-video_por=629000-0   mp4        640x360    [pt] DASH video  629k , mp4_dash container, avc1.64001E, video only
dash-video_por=629000-1   mp4        640x360    [pt] DASH video  629k , mp4_dash container, avc1.64001E, video only
dash-video_por=629000-2   mp4        640x360    [pt] DASH video  629k , mp4_dash container, avc1.64001E, video only
dash-video_por=629000-3   mp4        640x360    [pt] DASH video  629k , mp4_dash container, avc1.64001E, video only
mss-video_por-1094        ismv       854x480    1094k , AVC1, video only
dash-video_por=1094000-0  mp4        854x480    [pt] DASH video 1094k , mp4_dash container, avc1.64001F, video only
dash-video_por=1094000-1  mp4        854x480    [pt] DASH video 1094k , mp4_dash container, avc1.64001F, video only
dash-video_por=1094000-2  mp4        854x480    [pt] DASH video 1094k , mp4_dash container, avc1.64001F, video only
dash-video_por=1094000-3  mp4        854x480    [pt] DASH video 1094k , mp4_dash container, avc1.64001F, video only
mss-video_por-1962        ismv       1280x720   1962k , AVC1, video only
dash-video_por=1962000-0  mp4        1280x720   [pt] DASH video 1962k , mp4_dash container, avc1.64001F, video only
dash-video_por=1962000-1  mp4        1280x720   [pt] DASH video 1962k , mp4_dash container, avc1.64001F, video only
dash-video_por=1962000-2  mp4        1280x720   [pt] DASH video 1962k , mp4_dash container, avc1.64001F, video only
dash-video_por=1962000-3  mp4        1280x720   [pt] DASH video 1962k , mp4_dash container, avc1.64001F, video only
mss-video_por-3039        ismv       1280x720   3039k , AVC1, video only
dash-video_por=3039000-0  mp4        1280x720   [pt] DASH video 3039k , mp4_dash container, avc1.640028, video only
dash-video_por=3039000-1  mp4        1280x720   [pt] DASH video 3039k , mp4_dash container, avc1.640028, video only
dash-video_por=3039000-2  mp4        1280x720   [pt] DASH video 3039k , mp4_dash container, avc1.640028, video only
dash-video_por=3039000-3  mp4        1280x720   [pt] DASH video 3039k , mp4_dash container, avc1.640028, video only
mss-video_por-4661        ismv       1920x1080  4661k , AVC1, video only
dash-video_por=4661000-0  mp4        1920x1080  [pt] DASH video 4661k , mp4_dash container, avc1.640028, video only
dash-video_por=4661000-1  mp4        1920x1080  [pt] DASH video 4661k , mp4_dash container, avc1.640028, video only
dash-video_por=4661000-2  mp4        1920x1080  [pt] DASH video 4661k , mp4_dash container, avc1.640028, video only
mss-video_por-7769        ismv       1920x1080  7769k , AVC1, video only
dash-video_por=7769000-0  mp4        1920x1080  [pt] DASH video 7769k , mp4_dash container, avc1.640029, video only
dash-video_por=7769000-1  mp4        1920x1080  [pt] DASH video 7769k , mp4_dash container, avc1.640029, video only
dash-video_por=7769000-2  mp4        1920x1080  [pt] DASH video 7769k , mp4_dash container, avc1.640029, video only
hls-518-0                 mp4        640x360     518k , avc1.64001E@ 360k, mp4a.40.2@128k
hls-518-1                 mp4        640x360     518k , avc1.64001E@ 360k, mp4a.40.2@128k
hls-518-2                 mp4        640x360     518k , avc1.64001E@ 360k, mp4a.40.2@128k
hls-518-3                 mp4        640x360     518k , avc1.64001E@ 360k, mp4a.40.2@128k
hls-518-4                 mp4        640x360     518k , avc1.64001E@ 360k, mp4a.40.2@128k
hls-803-0                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-1                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-2                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-3                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-4                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-5                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-6                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-7                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-803-8                 mp4        640x360     803k , avc1.64001E@ 629k, mp4a.40.2@128k
hls-1296-0                mp4        854x480    1296k , avc1.64001F@1094k, mp4a.40.2@128k
hls-1296-1                mp4        854x480    1296k , avc1.64001F@1094k, mp4a.40.2@128k
hls-1296-2                mp4        854x480    1296k , avc1.64001F@1094k, mp4a.40.2@128k
hls-1296-3                mp4        854x480    1296k , avc1.64001F@1094k, mp4a.40.2@128k
hls-1296-4                mp4        854x480    1296k , avc1.64001F@1094k, mp4a.40.2@128k
hls-1296-5                mp4        854x480    1296k , avc1.64001F@1094k, mp4a.40.2@128k
hls-1296-6                mp4        854x480    1296k , avc1.64001F@1094k, mp4a.40.2@128k
hls-1296-7                mp4        854x480    1296k , avc1.64001F@1094k, mp4a.40.2@128k
hls-1296-8                mp4        854x480    1296k , avc1.64001F@1094k, mp4a.40.2@128k
hls-2216-0                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-2216-1                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-2216-2                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-2216-3                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-2216-4                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-2216-5                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-2216-6                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-2216-7                mp4        1280x720   2216k , avc1.64001F@1962k, mp4a.40.2@128k
hls-3358-0                mp4        1280x720   3358k , avc1.640028@3039k, mp4a.40.2@128k
hls-3358-1                mp4        1280x720   3358k , avc1.640028@3039k, mp4a.40.2@128k
hls-3358-2                mp4        1280x720   3358k , avc1.640028@3039k, mp4a.40.2@128k
hls-3358-3                mp4        1280x720   3358k , avc1.640028@3039k, mp4a.40.2@128k
hls-3358-4                mp4        1280x720   3358k , avc1.640028@3039k, mp4a.40.2@128k
hls-3358-5                mp4        1280x720   3358k , avc1.640028@3039k, mp4a.40.2@128k
hls-3358-6                mp4        1280x720   3358k , avc1.640028@3039k, mp4a.40.2@128k
hls-3358-7                mp4        1280x720   3358k , avc1.640028@3039k, mp4a.40.2@128k
hls-5077-0                mp4        1920x1080  5077k , avc1.640028@4661k, mp4a.40.2@128k
hls-5077-1                mp4        1920x1080  5077k , avc1.640028@4661k, mp4a.40.2@128k
hls-5077-2                mp4        1920x1080  5077k , avc1.640028@4661k, mp4a.40.2@128k
hls-5077-3                mp4        1920x1080  5077k , avc1.640028@4661k, mp4a.40.2@128k
hls-8371-0                mp4        1920x1080  8371k , avc1.640029@7769k, mp4a.40.2@128k
hls-8371-1                mp4        1920x1080  8371k , avc1.640029@7769k, mp4a.40.2@128k
hls-8371-2                mp4        1920x1080  8371k , avc1.640029@7769k, mp4a.40.2@128k
hls-8371-3                mp4        1920x1080  8371k , avc1.640029@7769k, mp4a.40.2@128k (best)

**Comment by dstftw** [comment]
Stop posting duplicates. This is your last warning.
