### ISSUE TITLE
--write-thumbnail --skip-download dosn't work with --exec?

### ISSUE THREAD

**Issue by gk26** [ytdl-org/youtube-dl#22464]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I just want to download the thumbnail of a video and then process it. But it seems that the --exec function does not work if you use the --skip-download option. Is that correct?

christoph@srv:~$ youtube-dl --verbose --write-thumbnail --restrict-filenames https://www.youtube.com/watch?v=BaW_jenozKc --exec 'ls -lh {}'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--write-thumbnail', u'--restrict-filenames', u'https://www.youtube.com/watch?v=BaW_jenozKc', u'--exec', u'ls -lh {}']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-62-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[youtube] BaW_jenozKc: Downloading thumbnail ...
[youtube] BaW_jenozKc: Writing thumbnail to: youtube-dl_test_video_a-BaW_jenozKc.jpg
[download] youtube-dl_test_video_a-BaW_jenozKc.mp4 has already been downloaded and merged
[exec] Executing command: ls -lh youtube-dl_test_video_a-BaW_jenozKc.mp4
-rw-rw-r-- 1 christoph christoph 2,3M Dez 25  2013 youtube-dl_test_video_a-BaW_jenozKc.mp4

christoph@srv:~$ youtube-dl --verbose --write-thumbnail --skip-download --restrict-filenames https://www.youtube.com/watch?v=BaW_jenozKc --exec 'ls -lh {}'                                                        
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--write-thumbnail', u'--skip-download', u'--restrict-filenames', u'https://www.youtube.com/watch?v=BaW_jenozKc', u'--exec', u'ls -lh {}']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-62-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[youtube] BaW_jenozKc: Downloading thumbnail ...
[youtube] BaW_jenozKc: Writing thumbnail to: youtube-dl_test_video_a-BaW_jenozKc.jpg

**Comment by dstftw** [comment]
This is expected behavior. There is no file downloaded to run `--exec` on.

**Comment by gk26** [comment]
Thanks,
but: "youtube-dl_test_video_a-BaW_jenozKc.jpg" was downloadet. Is there a chance to interact with the thumbnail file?

-- Chris
