### ISSUE TITLE
Still using a gig to download 100mb even with prefer ffmpeg for hls

### ISSUE THREAD

**Issue by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [ytdl-org/youtube-dl#22478]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Something isn't right, I just lost an entire gig to a 100mb download, I then tried prefer ffmpeg and its still eating away more than double the size of the file. Just gone. 

`youtube-dl --hls-prefer-ffmpeg --print-traffic  --no-part  -w --no-cache-dir --no-mtime -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' --merge-output-format mp4 -o '%(title)s-%(resolution)s-%(fps)s-%(autonumber)s.%(ext)s' LINK --restrict-filenames --autonumber-start 1
`
Commands I usually run^

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
What is incomplete

**Comment by remitamine** [comment]
you're filling the wrong issue template, you describing what is supposed to be a bug so instead fill a proper bug report, not a question.

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
I did not feel as if I had the proper factual information regarding the actual mechanics going on that caused this, I have no error, or console output to provide. I made a question because I noticed similar issues with hls while searching, I then checked the docs and saw the prefer ffmpeg thinking this was the fix that had been implemented (which seems like it should make sense and work). I then went ahead with the question format because I wasn't sure if someone could provide a simple answer, without causing a hubbub submitting a possibly erroneous.. poorly constructed and cited.. bug report.   Can you just reopen this? Is it that big of a deal? Thanks.

**Comment by remitamine** [comment]
there is no point in keeping this open, you making a claim and didn't provide a proof(that youtube-dl download a very large file but the result is 10 times smaller), and then if you did provide a proof it should be reproducible locally so we can fix it, otherwise there is nothing that can be done.

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
I didn't know one had to provide proof of a question being a question. Perhaps next time I will make sure to include a question mark and really drive the point home, so that you will not be so eager to make things so unnecessarily difficult. Thanks for nothing, feels like reddit around here. I will look elsewhere for discussion and tips about code I guess.
