### ISSUE TITLE
.dump file can not be deleted

### ISSUE THREAD

**Issue by AdamKekow** [ytdl-org/youtube-dl#22474]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
D:\Pobrane\Youtube-dl\uszkodz>youtube-dl.exe -v --write-pages -i -f best https://www.youtube.com/channel/UCh27kz4gdCkyqjlZA412UoA/videos
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--write-pages', '-i', '-f', 'best', 'https://www.youtube.com/channel/UCh27kz4gdCkyqjlZA412UoA/videos']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[youtube:channel] UCh27kz4gdCkyqjlZA412UoA: Downloading channel page
[youtube:channel] Saving request to UCh27kz4gdCkyqjlZA412UoA_https_-_www.youtube.com_channel_UCh27kz4gdCkyqjlZA412UoA_videosview=57_disable_polymer=true.dump
[youtube:playlist] UUh27kz4gdCkyqjlZA412UoA: Downloading webpage
[youtube:playlist] Saving request to UUh27kz4gdCkyqjlZA412UoA_https_-_www.youtube.com_playlistdisable_polymer=true_list=UUh27kz4gdCkyqjlZA412UoA.dump
[download] Downloading playlist: Uploads from Liceum Leonium
[youtube:playlist] playlist Uploads from Liceum Leonium: Downloading 35 videos
[download] Downloading video 1 of 35
[youtube] k4VMf3mhfHM: Downloading webpage
[youtube] Saving request to k4VMf3mhfHM_https_-_www.youtube.com_watchdisable_polymer=true_hl=en_bpctr=9999999999_gl=US_v=k4VMf3mhfHM_has_verified=1.dump
[youtube] k4VMf3mhfHM: Downloading video info webpage
[youtube] Saving request to k4VMf3mhfHM_https_-_www.youtube.com_get_video_infoeurl=_disable_polymer=true_hl=en_gl=US_ps=default_video_id=k4VMf3mhfHM_el=embedded.dump
[youtube] {18} signature length 104, html5 player vfleGIwAA
[youtube] {22} signature length 108, html5 player vfleGIwAA
[youtube] {43} signature length 108, html5 player vfleGIwAA
[youtube] {137} signature length 108, html5 player vfleGIwAA
[youtube] {248} signature length 108, html5 player vfleGIwAA
[youtube] {136} signature length 108, html5 player vfleGIwAA
[youtube] {247} signature length 108, html5 player vfleGIwAA
[youtube] {135} signature length 104, html5 player vfleGIwAA
[youtube] {244} signature length 104, html5 player vfleGIwAA
[youtube] {134} signature length 108, html5 player vfleGIwAA
[youtube] {243} signature length 104, html5 player vfleGIwAA
[youtube] {133} signature length 108, html5 player vfleGIwAA
[youtube] {242} signature length 108, html5 player vfleGIwAA
[youtube] {160} signature length 108, html5 player vfleGIwAA
[youtube] {278} signature length 104, html5 player vfleGIwAA
[youtube] {140} signature length 104, html5 player vfleGIwAA
[youtube] {251} signature length 108, html5 player vfleGIwAA
[youtube] k4VMf3mhfHM: Downloading MPD manifest
[youtube] Saving request to k4VMf3mhfHM_https_-_manifest.googlevideo.com_api_manifest_dash_expire_1569095843_ei_QyyGXcaWEZCbyQXk66OoBA_ip_185.183.226.66_id_93854c7f79a17c73_so
urce_youtube_requiressl_yes_playback_host_r3---sn-u2oxu-f5_8219a2430114498635a1591479b0e01e.dump
[debug] Invoking downloader on 'https://r3---sn-u2oxu-f5fr.googlevideo.com/videoplayback?expire=1569095843&ei=QyyGXcaWEZCbyQXk66OoBA&ip=185.183.226.66&id=o-AG3QVWOAvpgcOjRDpdl
R6Yv5wF0uc5iAvRvXGmrCjcm3&itag=22&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-u2oxu-f5fr%2Csn-5hnekn7l&ms=au%2Conr&mv=m&mvi=2&pl=23&initcwndbps=4270000&mime=video%2Fmp4&rat
ebypass=yes&dur=283.097&lmt=1566243055285130&mt=1569074158&fvip=3&c=WEB&txp=2216222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&
lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgLXbTZFtiQDkzAaWgkl6ZHU5MpHa1Aw1AoTkjQWYU810CIQCJ2dwRy8KELdYBGifwhLk7fbjTDZdGntuYLTzfs1ZDhQ%3D%3D&sig=ALgxI
2wwRQIge1wSB-RDJtVP5M5yv9RJtNyr2waUR_UmRGLP8yzOQBkCIQCymfnYjHVCaxeaFp94fLE22TWQd6DqxiDxFWMRrArzIw=='
[download] Destination: Erasmus+ Eurofolk in Sierpc 2019-k4VMf3mhfHM.mp4
[download] 100% of 66.66MiB in 00:06
[download] Downloading video 2 of 35
[youtube] 2sSzZiYvZu0: Downloading webpage
[youtube] Saving request to 2sSzZiYvZu0_https_-_www.youtube.com_watchdisable_polymer=true_hl=en_bpctr=9999999999_gl=US_v=2sSzZiYvZu0_has_verified=1.dump
[youtube] 2sSzZiYvZu0: Downloading video info webpage
[youtube] Saving request to 2sSzZiYvZu0_https_-_www.youtube.com_get_video_infoeurl=_disable_polymer=true_hl=en_gl=US_ps=default_video_id=2sSzZiYvZu0_el=embedded.dump
[debug] Invoking downloader on 'https://r3---sn-u2oxu-f5fe6.googlevideo.com/videoplayback?expire=1569095851&ei=SyyGXeroFu7n7ATwuoewBQ&ip=185.183.226.66&id=o-AObCQeA8SuxwuGEE_v
oHJjTh9oZnNCxHtU_q1oYR5Rxi&itag=18&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-u2oxu-f5fe6%2Csn-5hnedn7s&ms=au%2Conr&mv=m&mvi=2&pl=23&initcwndbps=4865000&mime=video%2Fmp4&g
ir=yes&clen=15961575&ratebypass=yes&dur=175.821&lmt=1558991225607741&mt=1569074158&fvip=4&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2
Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIgfw0ZapzfexbyVo-8Svr5q0lPaefwxVKUCX6gyCzV7-ICIQDWV9Q4cHxDIw7nz4QrDAbD65IQ8iBPMF9dvJrXETx-Cg%3D%3D&lsparams=mm%2Cmn%2Cms%2Cm
v%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgdlMABoNiwQoGgs0o7EC3smXzYnKnymG4syBq1vtkXBECIHlZ72eQIkML0kiIGp48Ld9WY5JbbABK_Olq-toT63Od'
[download] Destination: Erasmus+ Eurofolk in Sierpc Day1-2sSzZiYvZu0.mp4
[download] 100% of 15.22MiB in 00:01
[download] Downloading video 3 of 35
[youtube] DNA7F7QJ0tk: Downloading webpage
[youtube] Saving request to DNA7F7QJ0tk_https_-_www.youtube.com_watchdisable_polymer=true_hl=en_bpctr=9999999999_gl=US_v=DNA7F7QJ0tk_has_verified=1.dump
[youtube] DNA7F7QJ0tk: Downloading video info webpage
[youtube] Saving request to DNA7F7QJ0tk_https_-_www.youtube.com_get_video_infoeurl=_disable_polymer=true_hl=en_gl=US_ps=default_video_id=DNA7F7QJ0tk_el=embedded.dump
[youtube] {18} signature length 104, html5 player vfleGIwAA
[youtube] {22} signature length 108, html5 player vfleGIwAA
[youtube] {43} signature length 104, html5 player vfleGIwAA
[youtube] {137} signature length 108, html5 player vfleGIwAA
[youtube] {248} signature length 104, html5 player vfleGIwAA
[youtube] {136} signature length 108, html5 player vfleGIwAA
[youtube] {247} signature length 108, html5 player vfleGIwAA
[youtube] {135} signature length 108, html5 player vfleGIwAA
[youtube] {244} signature length 108, html5 player vfleGIwAA
[youtube] {134} signature length 108, html5 player vfleGIwAA
[youtube] {243} signature length 108, html5 player vfleGIwAA
[youtube] {133} signature length 108, html5 player vfleGIwAA
[youtube] {242} signature length 108, html5 player vfleGIwAA
[youtube] {160} signature length 104, html5 player vfleGIwAA
[youtube] {278} signature length 108, html5 player vfleGIwAA
[youtube] {140} signature length 108, html5 player vfleGIwAA
[youtube] {251} signature length 104, html5 player vfleGIwAA
[youtube] DNA7F7QJ0tk: Downloading MPD manifest
[youtube] Saving request to DNA7F7QJ0tk_https_-_manifest.googlevideo.com_api_manifest_dash_expire_1569095854_ei_TSyGXYyrNJWA7QTY-q7gAw_ip_185.183.226.66_id_0cd03b17b409d2d9_so
urce_youtube_requiressl_yes_playback_host_r1---sn-u2oxu-f5_058c16f6a3042000d0da8d2510868240.dump
[debug] Invoking downloader on 'https://r1---sn-u2oxu-f5fed.googlevideo.com/videoplayback?expire=1569095854&ei=TSyGXYyrNJWA7QTY-q7gAw&ip=185.183.226.66&id=o-AALj7lXKfZpul2xlAf
i8dzpW1990pt-uJ8nEmQA288oY&itag=22&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-u2oxu-f5fed%2Csn-5hnedn7z&ms=au%2Conr&mv=m&mvi=0&pl=23&initcwndbps=3523750&mime=video%2Fmp4&r
atebypass=yes&dur=1476.092&lmt=1557960632612493&mt=1569074158&fvip=6&c=WEB&txp=2216222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Cl
mt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhANbdEj2dP8HUXM-Sf0zoVC9KQiwUo0gsYY3Dtf9dwmnDAiA5RyRRgzGMJBkznTmr8BtR5BHc8QlZMj2iyEzcKakkEQ%3D%3D&sig=AL
gxI2wwRgIhAPiCoXC_fjYYQfXhNZA442SgbnlHumnmJDY8dqc_MEysAiEAxokDPSba21_KSQKXHTJHKMCVYVvoq0U5RIigkoY0wcU='
[download] Destination: Niedźwiedź - Antoni Czechow Leonijny Dzień Kultury 2019-DNA7F7QJ0tk.mp4
[download] 100% of 227.54MiB in 00:23
[download] Downloading video 4 of 35
[youtube] A8gPNhZcQTE: Downloading webpage
[youtube] Saving request to A8gPNhZcQTE_https_-_www.youtube.com_watchdisable_polymer=true_hl=en_bpctr=9999999999_gl=US_v=A8gPNhZcQTE_has_verified=1.dump
[youtube] A8gPNhZcQTE: Downloading video info webpage
[youtube] Saving request to A8gPNhZcQTE_https_-_www.youtube.com_get_video_infoeurl=_disable_polymer=true_hl=en_gl=US_ps=default_video_id=A8gPNhZcQTE_el=embedded.dump
[youtube] {18} signature length 108, html5 player vfleGIwAA
[youtube] {22} signature length 108, html5 player vfleGIwAA
[youtube] {43} signature length 104, html5 player vfleGIwAA
[youtube] {137} signature length 108, html5 player vfleGIwAA
[youtube] {248} signature length 108, html5 player vfleGIwAA
[youtube] {136} signature length 108, html5 player vfleGIwAA
[youtube] {247} signature length 104, html5 player vfleGIwAA
[youtube] {135} signature length 108, html5 player vfleGIwAA
[youtube] {244} signature length 108, html5 player vfleGIwAA
[youtube] {134} signature length 104, html5 player vfleGIwAA
[youtube] {243} signature length 108, html5 player vfleGIwAA
[youtube] {133} signature length 108, html5 player vfleGIwAA
[youtube] {242} signature length 108, html5 player vfleGIwAA
[youtube] {160} signature length 108, html5 player vfleGIwAA
[youtube] {278} signature length 108, html5 player vfleGIwAA
[youtube] {140} signature length 104, html5 player vfleGIwAA
[youtube] {251} signature length 108, html5 player vfleGIwAA
[youtube] A8gPNhZcQTE: Downloading MPD manifest
[youtube] Saving request to A8gPNhZcQTE_https_-_manifest.googlevideo.com_api_manifest_dash_expire_1569095878_ei_ZiyGXfumKY6F7QTgi7eADA_ip_185.183.226.66_id_03c80f36165c4131_so
urce_youtube_requiressl_yes_playback_host_r2---sn-u2oxu-f5_a88f8eaf9d96034b41b61bd8a276d1a6.dump
[debug] Invoking downloader on 'https://r2---sn-u2oxu-f5fed.googlevideo.com/videoplayback?expire=1569095878&ei=ZiyGXfumKY6F7QTgi7eADA&ip=185.183.226.66&id=o-AHy5JAJJbM24-7o1zn
HP3NeN06rwbKduHw29fEyzRefd&itag=22&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-u2oxu-f5fed%2Csn-5hnednlk&ms=au%2Conr&mv=m&mvi=1&pl=23&initcwndbps=3523750&mime=video%2Fmp4&r
atebypass=yes&dur=321.782&lmt=1554588091936310&mt=1569074158&fvip=2&c=WEB&txp=2216222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clm
t&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAI0ZW4Fb6y92I4uLF-Y_GnmPEq-wddJmmI4d31xuasFyAiA9bJChc0gB4Bu89HS0JuNma7ePFRa466Y9C1qRcGQ4PA%3D%3D&sig=ALg
xI2wwRgIhAPwr--Sw4Menlgsw5iqJCpE9J4lC7BZWVH0Bm7K3_PL5AiEA8N45Aua-Z82n8AvWr9RXuv06qk7AFMBcFwHpHcrHQ5M='
[download] Destination: Erasmus+ EuroGebra in Greece 2019-A8gPNhZcQTE.mp4
[download] 100% of 92.70MiB in 00:09
[download] Downloading video 5 of 35
[youtube] E4ObuX6abY0: Downloading webpage
[youtube] Saving request to E4ObuX6abY0_https_-_www.youtube.com_watchdisable_polymer=true_hl=en_bpctr=9999999999_gl=US_v=E4ObuX6abY0_has_verified=1.dump
[youtube] E4ObuX6abY0: Downloading video info webpage
[youtube] Saving request to E4ObuX6abY0_https_-_www.youtube.com_get_video_infoeurl=_disable_polymer=true_hl=en_gl=US_ps=default_video_id=E4ObuX6abY0_el=embedded.dump
[youtube] E4ObuX6abY0: Downloading MPD manifest
[youtube] Saving request to E4ObuX6abY0_https_-_manifest.googlevideo.com_api_manifest_dash_expire_1569095889_ei_cSyGXcPYE8fr7QSdpqTYBQ_ip_185.183.226.66_id_13839bb97e9a6d8d_so
urce_youtube_requiressl_yes_playback_host_r2---sn-f5f7ln7z_b41b368bbd03a6d0b48a091f66929ed0.dump
[debug] Invoking downloader on 'https://r2---sn-f5f7ln7z.googlevideo.com/videoplayback?expire=1569095889&ei=cSyGXcPYE8fr7QSdpqTYBQ&ip=185.183.226.66&id=o-APtvOvhZ82nnajp13fjIR
uCWsCf50zY1UEdSUed02p5m&itag=22&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-f5f7ln7z%2Csn-5hnekn7l&ms=au%2Conr&mv=m&mvi=1&pl=23&initcwndbps=5368750&mime=video%2Fmp4&ratebyp
ass=yes&dur=149.327&lmt=1552943702085437&mt=1569074158&fvip=4&c=WEB&txp=2216222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=
ALgxI2wwRAIgLXhpJiVFMKB7NbSo3ufC3X2rW-AtYsH-FIyudoI_Zt8CIDeN3lQ5wBVOOHnPL-22ahG8SHyoNZO2aUpqJswBJ4pE&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAIBkK
IYqUgfSa91Qiucpii2X_bJTAGhqL3z8X5VlJrrwAiEA27w8ZdIiuwlTi49pw7E1WxVigclJuONqL3SV1I8EfSE%3D'
[download] Destination: Zapraszamy do Leonium-E4ObuX6abY0.mp4
[download] 100% of 37.41MiB in 00:03
[download] Downloading video 6 of 35
[youtube] _bY_8alSURs: Downloading webpage
[youtube] Saving request to bY_8alSURs_https_-_www.youtube.com_watchdisable_polymer=true_hl=en_bpctr=9999999999_gl=US_v=_bY_8alSURs_has_verified=1.dump
[youtube] _bY_8alSURs: Downloading video info webpage
[youtube] Saving request to bY_8alSURs_https_-_www.youtube.com_get_video_infoeurl=_disable_polymer=true_hl=en_gl=US_ps=default_video_id=_bY_8alSURs_el=embedded.dump
[youtube] _bY_8alSURs: Downloading MPD manifest
[youtube] Saving request to bY_8alSURs_https_-_manifest.googlevideo.com_api_manifest_dash_expire_1569095894_ei_diyGXfuRENqqyAXp9oOgDQ_ip_185.183.226.66_id_fdb63ff1a952511b_sou
rce_youtube_requiressl_yes_playback_host_r2---sn-u2oxu-f5_58e07ae5e16df171170469ed5e492460.dump
[debug] Invoking downloader on 'https://r2---sn-u2oxu-f5fez.googlevideo.com/videoplayback?expire=1569095894&ei=diyGXfuRENqqyAXp9oOgDQ&ip=185.183.226.66&id=o-AHC_ABBpAMMDlz2xxi
wZ_BJ65PMoFmGKbMR7MXVhP4UJ&itag=22&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-u2oxu-f5fez%2Csn-5hne6nsr&ms=au%2Conr&mv=m&mvi=1&pl=23&initcwndbps=7482500&mime=video%2Fmp4&r
atebypass=yes&dur=358.144&lmt=1552256959197204&mt=1569074219&fvip=5&c=WEB&txp=2216222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clm
t&sig=ALgxI2wwRQIhAORafn5AUK_iPOJelTbrg58MNA80wixQxaYTf5bb5RY7AiBwo4p1F2d18_k-qQRpiDyrXWPCWZynrzgrzYqaZp9kUg%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHy
lml4wRQIhANPJ7OHDRBPC2xzrizAGeBMJDWY-wMzi4IjlcouoNTi9AiBc7dUe9W3CcSma-tQ_WQSJR-Tm4tgQkwLMeXsEpGi9MA%3D%3D'
[download] Destination: Erasmus+ Eurogebra in Collegium Leonium-_bY_8alSURs.mp4
[download] 100% of 87.08MiB in 00:09
[download] Downloading video 7 of 35
[youtube] WvCPy8vWaCY: Downloading webpage
[youtube] Saving request to WvCPy8vWaCY_https_-_www.youtube.com_watchdisable_polymer=true_hl=en_bpctr=9999999999_gl=US_v=WvCPy8vWaCY_has_verified=1.dump
[youtube] WvCPy8vWaCY: Downloading video info webpage
[youtube] Saving request to WvCPy8vWaCY_https_-_www.youtube.com_get_video_infoeurl=_disable_polymer=true_hl=en_gl=US_ps=default_video_id=WvCPy8vWaCY_el=embedded.dump
[youtube] WvCPy8vWaCY: Downloading MPD manifest
[youtube] Saving request to WvCPy8vWaCY_https_-_manifest.googlevideo.com_api_manifest_dash_expire_1569095905_ei_gSyGXZnyC5i87QSB_4NA_ip_185.183.226.66_id_5af08fcbcbd66826_sour
ce_youtube_requiressl_yes_playback_host_r8---sn-u2oxu-f5fr_2035d3fdfdc169f4dff9bd2958b4a8e9.dump
[debug] Invoking downloader on 'https://r8---sn-u2oxu-f5fr.googlevideo.com/videoplayback?expire=1569095905&ei=gSyGXZnyC5i87QSB_4NA&ip=185.183.226.66&id=o-AHyrSRkdUAPLOF9ztwknk
zWFgGGK4zYu-ILBSQn8sU9Y&itag=18&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-u2oxu-f5fr%2Csn-5hne6nsz&ms=au%2Conr&mv=m&mvi=7&pl=23&initcwndbps=6870000&mime=video%2Fmp4&gir=y
es&clen=301580256&ratebypass=yes&dur=4021.254&lmt=1547738247827488&mt=1569074219&fvip=2&c=WEB&txp=2211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cg
ir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIgQzqEjQKuSk99CGDQHwlYciaU6K7u63g0HjaePVAKIW8CIQDMLznr6PwdMJLpB-Wr94fo-a6jsKkZUw220g45U4pERQ%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%
2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAPaCQSsnqk9Eq3IrGFhmRBb6PYz1XWCAlFD5U9IpC_nUAiB_JdwMRPWFPHWtJ_H4wEqqWTqYNo4QGe9spfU6WCQ4rQ%3D%3D'
[download] Destination: Kochać chcę, nie tylko od święta-WvCPy8vWaCY.mp4
[download] 100% of 287.61MiB in 00:30
[download] Downloading video 8 of 35
[youtube] eaJrXb76Q_Q: Downloading webpage
[youtube] Saving request to eaJrXb76Q_Q_https_-_www.youtube.com_watchdisable_polymer=true_hl=en_bpctr=9999999999_gl=US_v=eaJrXb76Q_Q_has_verified=1.dump
[youtube] eaJrXb76Q_Q: Downloading video info webpage
[youtube] Saving request to eaJrXb76Q_Q_https_-_www.youtube.com_get_video_infoeurl=_disable_polymer=true_hl=en_gl=US_ps=default_video_id=eaJrXb76Q_Q_el=embedded.dump
[youtube] {18} signature length 108, html5 player vfleGIwAA
[youtube] {22} signature length 104, html5 player vfleGIwAA
[youtube] {43} signature length 104, html5 player vfleGIwAA
[youtube] {137} signature length 104, html5 player vfleGIwAA
[youtube] {248} signature length 108, html5 player vfleGIwAA
[youtube] {136} signature length 108, html5 player vfleGIwAA
[youtube] {247} signature length 108, html5 player vfleGIwAA
[youtube] {135} signature length 108, html5 player vfleGIwAA
[youtube] {244} signature length 108, html5 player vfleGIwAA
[youtube] {134} signature length 108, html5 player vfleGIwAA
[youtube] {243} signature length 104, html5 player vfleGIwAA
[youtube] {133} signature length 108, html5 player vfleGIwAA
[youtube] {242} signature length 108, html5 player vfleGIwAA
[youtube] {160} signature length 108, html5 player vfleGIwAA
[youtube] {278} signature length 104, html5 player vfleGIwAA
[youtube] {140} signature length 108, html5 player vfleGIwAA
[youtube] {251} signature length 108, html5 player vfleGIwAA
[youtube] eaJrXb76Q_Q: Downloading MPD manifest
[youtube] Saving request to eaJrXb76Q_Q_https_-_manifest.googlevideo.com_api_manifest_dash_expire_1569095937_ei_oSyGXbrvH8jvyAXdi6HgBg_ip_185.183.226.66_id_79a26b5dbefa43f4_so
urce_youtube_requiressl_yes_playback_host_r1---sn-u2oxu-f5_b443d74c5659b2f2aceb224ece82dad5.dump
[debug] Invoking downloader on 'https://r1---sn-u2oxu-f5fe7.googlevideo.com/videoplayback?expire=1569095937&ei=oSyGXbrvH8jvyAXdi6HgBg&ip=185.183.226.66&id=o-AIFj0dOx-fJR93cEvQ
7h8--4PifKG3UjTiyap_9MMF26&itag=22&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-u2oxu-f5fe7%2Csn-5hnednlk&ms=au%2Conr&mv=m&mvi=0&pcm2cms=yes&pl=23&initcwndbps=4810000&mime=v
ideo%2Fmp4&ratebypass=yes&dur=2642.848&lmt=1545373552246658&mt=1569074278&fvip=1&c=WEB&txp=2211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypa
ss%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAOZe4Hln8Giy1T755oevsepg_yGkl6ndIw5OI3eVTWzvAiAVptoVlCaGyvDwzuK1ZVg3r_krbPEFLTo4Z
vbX1NZ9uQ%3D%3D&sig=ALgxI2wwRAIgcc4xurGFaO6OMNZWr0vUtm2-m6B7kZIhEjkmVQIlojUCICHgGm8ydSHHJXqyIYiIVLoBsw9CoUnNXJpIkI-x5O2N'
[download] Destination: Jasełka 2018 w Liceum Leonium-eaJrXb76Q_Q.mp4
[download]  25.9% of 324.27MiB at  9.00MiB/s ETA 00:26
ERROR: Interrupted by user

D:\Pobrane\Youtube-dl\uszkodz>

## Description

WRITE DESCRIPTION HERE
--write-pages  create files so long, that windows can not modify them.
I use that comand, and that movies:"youtube-dl.exe -v --write-pages -i -f best https://www.youtube.com/channel/UCh27kz4gdCkyqjlZA412UoA/videos"
I founded that https://github.com/ytdl-org/youtube-dl/pull/6442, but i do not understand, why that is not working.
Windows 7 SP1

**Comment by dstftw** [comment]
Nothing to do with youtube-dl.
