### ISSUE TITLE
Ubuntu: 19.04, -o malfunction on Bitchute

### ISSUE THREAD

**Issue by ManuelTS** [ytdl-org/youtube-dl#22481]
## Checklist
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ
## Verbose log
youtube-dl -o "%(upload_date) - %(title).%(ext)s" --restrict-filenames -v https://www.bitchute.com/video/dW5uDoyZZEt9/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-o', u'%(upload_date) - %(title).%(ext)s', u'--restrict-filenames', u'-v', u'https://www.bitchute.com/video/dW5uDoyZZEt9/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 2.7.16 (CPython) - Linux-5.0.0-29-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[BitChute] dW5uDoyZZEt9: Downloading webpage
[BitChute] dW5uDoyZZEt9: Checking video URL
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://seed32.bitchute.com/LeOgEMOhozqd/dW5uDoyZZEt9.mp4'
[download] Destination: %(title).mp4
[download] 100% of 7.52MiB in 00:04

## Description
The video gets downloaded but with the file name `%(title).mp4`, I want to download the whole channel, the channel pages are downloaded but all videos result in the same file name and are therefore skipped. `lsb_release -a` on my machine is:

```No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco```

**Comment by ManuelTS** [comment]
Here another verbose output with the same result but with single quotes:

youtube-dl -o '%(upload_date) - %(title).%(ext)s' --restrict-filenames -v https://www.bitchute.com/video/dW5uDoyZZEt9/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-o', u'%(upload_date) - %(title).%(ext)s', u'--restrict-filenames', u'-v', u'https://www.bitchute.com/video/dW5uDoyZZEt9/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 2.7.16 (CPython) - Linux-5.0.0-29-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[BitChute] dW5uDoyZZEt9: Downloading webpage
[BitChute] dW5uDoyZZEt9: Checking video URL
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://seed32.bitchute.com/LeOgEMOhozqd/dW5uDoyZZEt9.mp4'
[download] %(title).mp4 has already been downloaded
[download] 100% of 7.52MiB

**Comment by dstftw** [comment]
Invalid output template. Each sequence must have trailing conversion type like `%(ext)s`.

**Comment by ManuelTS** [comment]
Please tell me, why `'%(upload_date) - %(title).%(ext)s'` of

youtube-dl -o '%(upload_date) - %(title).%(ext)s' --restrict-filenames -v https://www.bitchute.com/video/dW5uDoyZZEt9/

is not having the trailing conversion type `%(ext)s`? It clearly has?

**Comment by dstftw** [comment]
>Each sequence must have
>Each

**Comment by ManuelTS** [comment]
Thanks for your reply on a closed issue.

Okay each sequence, to be honest I don't know what exactly you mean by that. I removed all arguments except the `-o` one, nothing changes on the output, the title of the video is not inserted but rather only the raw template string `%(title)` as described.

I just want to download (for now) only the single video in the above link with the posted arguments but it does not work.

If it is not a bug, may you please be so kind to modify my try so that it works? I played a lot with it but the result stays the same.

**Comment by dstftw** [comment]
Are you trolling or what?
Must be `%(upload_date)s` instead of `%(upload_date)`, `%(title)s` instead of `%(title)`.

**Comment by ManuelTS** [comment]
No, I did not understand what you meant, but with your example it is absolutely clear. Thank you.
