### ISSUE TITLE
Download from vk.com fails with "ERROR: Unable to extract player params"

### ISSUE THREAD

**Issue by jm-153** [ytdl-org/youtube-dl#22491]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://vk.com/video-51189706_456247608?list=bec94c34fcd38b0e02']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 2.7.15+ (CPython) - Linux-5.0.0-29-generic-x86_64-with-LinuxMint-19.2-tina
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[vk] Downloading login page
[vk] Logging in
[vk] -51189706_456247608: Downloading webpage
ERROR: Unable to extract player params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/jm/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/jm/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/jm/.local/bin/youtube-dl/youtube_dl/extractor/vk.py", line 406, in _real_extract
    'player params'),
  File "/home/jm/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

I have installed an independent version of youtube-dl (independent from Linux Mint 19.2 repository) in /home/jm/.local/bin and call youtube-dl from there within some scripts. Until 2019-09-22 the scripts and youtube-dl worked fine. Since then the above mentioned download error from vk.com exists. Have updated youtube-dl to 2019.09.12.1 but same error occurs. Probably vk.com has changed something on their website and youtube-dl runs into an error, while parsing the downloaded webpage.

Regards,
Jens

**Comment by remitamine** [comment]
```
youtube-dl -f url720 https://vk.com/video-51189706_456247608?list=bec94c34fcd38b0e02
[vk] -51189706_456247608: Downloading webpage
[vk] -51189706_456247608: Downloading m3u8 information
[download] Destination: Пастушьи собаки--51189706_456247608.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.1M  100 20.1M    0     0   428k      0  0:00:48  0:00:48 --:--:--  457k
[curl] Downloaded 21119070 bytes
[download] 100% of 20.14MiB in 00:48
```

**Comment by jm-153** [comment]
Problem still exists if adding "-f url720" option:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--format', u'url720', u'https://vk.com/video557717461_456239047']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 2.7.15+ (CPython) - Linux-5.0.0-29-generic-x86_64-with-LinuxMint-19.2-tina
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[vk] Downloading login page
[vk] Logging in
[vk] 557717461_456239047: Downloading webpage
ERROR: Unable to extract player params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/jm/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/jm/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/jm/.local/bin/youtube-dl/youtube_dl/extractor/vk.py", line 406, in _real_extract
    'player params'),
  File "/home/jm/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
