### ISSUE TITLE
"ERROR: Content Warning" on some youtube videos

### ISSUE THREAD

**Issue by witedragen** [ytdl-org/youtube-dl#22504]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Some videos I can't download from youtube.com, such as:

https://www.youtube.com/watch?v=2QDzwBy55Uk

I get:

`ERROR: Content Warning`
`This video may be inappropriate for some users.`
`       Sign in to confirm your age`

How do I download this without passing username/password info into the arguments/conf?

**Comment by remitamine** [comment]
you can't.
