### ISSUE TITLE
pbs.org issue with undesired audio track selection

### ISSUE THREAD

**Issue by dashxdr** [ytdl-org/youtube-dl#22507]
youtube-dl -F "https://www.pbs.org/video/ken-burns-country-music-episode-1-the-rub/"
produces this output:
<pre>
format code                       extension  resolution note
hls-english-English               mp4        audio only [eng] 
hls-english-English_Descriptions  mp4        audio only [eng] 
hls-391                           mp4        416x234     391k , avc1.64000d, 29.97fps, video only
hls-654                           mp4        480x270     654k , avc1.640015, 29.97fps, video only
hls-861                           mp4        640x360     861k , avc1.64001e, 29.97fps, video only
hls-1481                          mp4        640x360    1481k , avc1.64001e, 29.97fps, video only
hls-2309                          mp4        960x540    2309k , avc1.64001f, 29.97fps, video only
hls-3861                          mp4        1280x720   3861k , avc1.64001f, 29.97fps, video only
hls-5412                          mp4        1280x720   5412k , avc1.64001f, 29.97fps, video only
hls-6965                          mp4        1280x720   6965k , avc1.64001f, 29.97fps, video only
hls-9042                          mp4        1920x1080  9042k , avc1.640028, 29.97fps, video only
11                                mp4        unknown    (best)
</pre>
If I download the video youtube-dl chooses hls-english-English_Descriptions but I want the hls-english-English audio instead. If I use the -f option I can get an audio only file or a video only file, but not both. It'd be nice to be able to specify multiple -f options, or a comma separated list.

As it is I need to grab the audio file I want and the video file I want and use ffmpeg to merge them.
Thanks!

**Comment by dstftw** [comment]
Bother to read FAQ on format selection.

**Comment by dashxdr** [comment]
-f hls-3861+hls-english-English
worked. The doc that gets printed when -h is used only says this:
    -f, --format FORMAT              Video format code, see the "FORMAT SELECTION" for all the info
It wasn't at all obvious what "FORMAT SELECTION" is a reference to.
