### ISSUE TITLE
youtube_dl.utils.ExtractorError: This video is unavailable. on all videos

### ISSUE THREAD

**Issue by veritas718** [ytdl-org/youtube-dl#22506]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```

[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.7.3 (CPython) - Linux-5.0.0-1017-gcp-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {'http': 'http://127.0.0.1:24000', 'https': 'http://127.0.0.1:24000'}
[youtube] data_proces: Downloading webpage
[youtube] data_proces: Downloading video info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: This video is unavailable.
Sorry about that.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/youtube.py", line 2146, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.
Sorry about that.

```

## Description

All videos are failing to download. They are actually failing to get any metadata. 
I have confirmed the proxy is working fine and I can watch videos in the browser with it.

**Comment by dstftw** [comment]
Invalid URL.

**Comment by veritas718** [comment]
'https://www.youtube.com/watch?v=mMp4UDNII6Q' is the url being passed in - it works just fine in the browser, any idea why the this tool doesn't like it?

**Comment by veritas718** [comment]
> Invalid URL.

Yeah, it was. 
For inquiring minds, I had been using pandas - specifically, `list(df.values)` (on a df created from bigquery results) which led to the columns being in different orders, so yes, the wrong value was being passed into the url template. By manually specifying the column order -> `list(df[['col1','col2']].values) the parameters were passed in correctly. While this seems to be a difference between python3.6 and 3.7 it seems to be solely related to pandas, and df.values.
