### ISSUE TITLE
[twitch] cannot get the "title" and "fps"

### ISSUE THREAD

**Issue by DesweR** [ytdl-org/youtube-dl#22501]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

youtube-dl cannot get **real** "title" of a **live** stream and cannot get "fps".

`youtube-dl --get-filename -o "title - %(title)s, fps - %(fps)s" https://www.twitch.tv/blackufa`
`title - BlackUFA 2019-09-24 22_08, fps - NA`

I would like to
`title - The SURGE 2, fps - 60`

**Comment by dstftw** [comment]
No such info is provided by twitch.

**Comment by DesweR** [comment]
Will it approach?
https://dev.twitch.tv/docs/v5/reference/streams/#get-stream-by-user

**Comment by DesweR** [comment]
stream.get('average_fps') - returns "fps"
channel.get('status') - returns "title"
