### ISSUE TITLE
Dr.dk/tv/se/tv-avisen

### ISSUE THREAD

**Issue by ole-tange** [ytdl-org/youtube-dl#22519]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v https://www.dr.dk/tv/se/tv-avisen/tv-avisen-24/tv-avisen-2019-09-26
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.dr.dk/tv/se/tv-avisen/tv-avisen-24/tv-avisen-2019-09-26']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-58-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: avconv 3.4.6, avprobe 3.4.6, ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[drtv] tv-avisen-2019-09-26: Downloading webpage
[drtv] tv-avisen-2019-09-26: Downloading video JSON
[drtv] tv-avisen-2019-09-26: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[drtv] tv-avisen-2019-09-26: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/mnt/4tb/home/tange/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/mnt/4tb/home/tange/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/mnt/4tb/home/tange/bin/youtube-dl/youtube_dl/extractor/drtv.py", line 231, in _real_extract
    self._sort_formats(formats)
  File "/mnt/4tb/home/tange/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

The date should be changed to current date. The URL works fine for the date yesterday:
https://www.dr.dk/tv/se/tv-avisen/tv-avisen-24/tv-avisen-2019-09-25

**Comment by vejnoe** [comment]
I am experiencing the same, looks like it's time sensitive. Take a couple of hours before it works, first in a sign language edition and then later in the normal version.
The video play with out problems in the browser, and if I take the .m3u8 file from the Inspector, it still don't work.
Can be reproduced by trying to download the video after the todays video have been aired (18:30 danish time). https://www.dr.dk/drtv/serie/tv-avisen-18_30_7039

**Comment by 0HAg0** [comment]
Yes – it seems, it take some time before the files are created. Until then, the broadcast may be streamed, but not downloaded, that is, the Google Chrome/Chromium plug-in TV4ever downloads the broadcast, right away, probably because its streaming it, rather than downloading it. At this point, the resulting download is Full HD. Later when the files is created, the download is HD, no matter whether you use youtube-dl or TV4ever.
