### ISSUE TITLE
Question About Print Output

### ISSUE THREAD

**Issue by manyoyo-co** [ytdl-org/youtube-dl#22527]
Hello, I'm wondering why there are _single quotes_ used around the filename after 'Adding metadata' but _double quotes_ after 'Adding thumbnail'.

Sorry to ask again, but I'm really interested.

```
[ffmpeg] Adding metadata to 'Leonard Nimoy reads Ray Bradbury's 'There Will Come Soft Rains' from 'The Martian Chronicles'-LzhlU8rXgHc.mp3'
[ffmpeg] Adding thumbnail to "Leonard Nimoy reads Ray Bradbury's 'There Will Come Soft Rains' from 'The Martian Chronicles'-LzhlU8rXgHc.mp3"
```

Thank you in advance.

**Comment by dstftw** [comment]
Are you trolling or what?

**Comment by manyoyo-co** [comment]
No, I'm not -- really. :-/

**Comment by manyoyo-co** [comment]
I'm genuinely, 100% interested in the difference between the print output in these two lines. I'm sure there might be a completely logical reason for it, but I don't know what it is. Sorry. 

```
[ffmpeg] Adding metadata to 'Leonard Nimoy reads Ray Bradbury's 'There Will Come Soft Rains' from 'The Martian Chronicles'-LzhlU8rXgHc.mp3'
[ffmpeg] Adding thumbnail to "Leonard Nimoy reads Ray Bradbury's 'There Will Come Soft Rains' from 'The Martian Chronicles'-LzhlU8rXgHc.mp3"
```

**Comment by dstftw** [comment]
I'll repeat it 3rd time: **there is no logical reason**. First uses single quotes hardcoded in string literal, second uses double quotes.
