### ISSUE TITLE
Did not get any data blocks when using -f best

### ISSUE THREAD

**Issue by satscape** [ytdl-org/youtube-dl#22523]
```
youtube-dl -v -f best 9ltc6hOYLHs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'best', u'9ltc6hOYLHs']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 2.7.13 (CPython) - Linux-4.19.66-v7+-armv7l-with-debian-9.11
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[youtube] 9ltc6hOYLHs: Downloading webpage
[youtube] 9ltc6hOYLHs: Downloading video info webpage
[debug] Invoking downloader on u'https://r1---sn-cn3tc-o9ul.googlevideo.com/videoplayback?expire=1569600524&ei=rN-NXeiSAs66Vr3WqrgF&ip=2a02%3Ac7f%3A522f%3A1400%3A8dd%3A60ef%3A5778%3A169d&id=o-AMqxRUsSfrSC8YZFMO7wtPm44TUeNPUHy3KeXVUi3nsA&itag=22&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-cn3tc-o9ul%2Csn-aigzrney&ms=au%2Crdu&mv=m&mvi=0&pl=39&initcwndbps=1247500&mime=video%2Fmp4&ratebypass=yes&dur=1207.902&lmt=1569436300045968&mt=1569578807&fvip=1&fexp=23842630&beids=9466585&c=WEB&txp=3416222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIgfeLoBdMRUyDTJiA3wSNsFlwHX-VObaWeBZoK3BV1fPgCIQCUeIcwpB7i9lWNPw3zReW7Hp2pUh8Sm2dZIqvTEc9vWA%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgKVdqa5UaTnLPBUzZD-yJcKG920JHSb2ydQGkfK7D8LACIH7OpwHmP44dEw4zFU8h6tN7cmLp9uiKSFLcGg4A3e7J'
[download] Destination: October 2019 Bullet Journal Setup 🍂 Gingko Leaves Theme ASMR-9ltc6hOYLHs.mp4
[download]   0.2% of 183.88MiB at  2.01MiB/s ETA 01:31[download] Got server HTTP error: Downloaded 438383 bytes, expected 192815736 bytes. Retrying (attempt 1 of 10)...


ERROR: Did not get any data blocks
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2019.9.12.1-py2.7.egg/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2019.9.12.1-py2.7.egg/youtube_dl/downloader/http.py", line 320, in download
    retry(err)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2019.9.12.1-py2.7.egg/youtube_dl/downloader/http.py", line 225, in retry
    raise RetryDownload(e)
RetryDownload
```

## Description
Getting this with nearly every video but only when using -f best option. If I remove that and get whatever it gives me, the download works fine. This has been happening for about a month, I always update to the latest version on git.

**Comment by firmitatis** [comment]
I had the same issue:

> youtube-dl -f 22 https://www.youtube.com/watch?v=qXat_wYP96Q
> [youtube] qXat_wYP96Q: Downloading webpage
> [youtube] qXat_wYP96Q: Downloading video info webpage
> [download] Destination: Greta Thunberg fez discurso falso (Análise de Linguagem Corporal, Metaforando)-qXat_wYP96Q.mp4
> [download]   0.2% of 85.50MiB at 115.50KiB/s ETA 12:36[download] Got server HTTP error: Downloaded 192247 bytes, expected 89652489 bytes. Retrying (attempt 1 of 10)...
> 
> 
> ERROR: Did not get any data blocks
>

**Comment by satscape** [comment]
Just upgraded to version 2019.09.28
same issue, why has this been closed?

`ERROR: Did not get any data blocks
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2019.9.28-py2.7.egg/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2019.9.28-py2.7.egg/youtube_dl/downloader/http.py", line 320, in download
    retry(err)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2019.9.28-py2.7.egg/youtube_dl/downloader/http.py", line 225, in retry
    raise RetryDownload(e)`
