### ISSUE TITLE
How to download the translated subtitles inside the `Auto-translate` button (new feature in Youtube)?

### ISSUE THREAD

**Issue by tuanbs** [ytdl-org/youtube-dl#22529]
How can I download the translated subtitles inside the `Auto-translate` button which is the new feature in Youtube videos:
<img width="999" alt="Screenshot 2019-09-28_1" src="https://user-images.githubusercontent.com/4801395/65812699-567d9100-e20e-11e9-9a64-989a1f08bf3c.png">
<img width="986" alt="Screenshot 2019-09-28_2" src="https://user-images.githubusercontent.com/4801395/65812700-567d9100-e20e-11e9-9147-93a102aedb3a.png">

I tried the cli `--write-sub`, `--write-auto-sub` and `all-subs`, but it just downloads the subtitles outside, not the ones inside the `Auto-translate` button. The video url is: `https://www.youtube.com/watch?v=YsqoF3hqdkg`
Thanks in advance.

**Comment by tuanbs** [comment]
Could you please explain why you closed this issue? Thanks.

**Comment by remitamine** [comment]
post the command you're using and it's output.

**Comment by tuanbs** [comment]
Hi @remitamine, after playing around I solved it. Sorry this is not a new feature on Youtube. My bad. Please delete this issue as I cannot delete it by myself. Thanks.

**Comment by DrSensor** [comment]
Hi @tuanbs, would you share how you solve it?

**Comment by scut-salmon** [comment]
Hi @tuanbs @remitamine , I would like to ask how to get the 'auto-translate' subtitles given the youtube link? Thanks

**Comment by titusfx** [comment]
@tuanbs how did you solve it? I'm trying on this one https://www.youtube.com/watch?v=Wt7rR0MCYsg& with:

`youtube-dl --write-auto-sub --sub-lang es --skip-download https://youtu.be/Wt7rR0MCYsg`

and nothing, output is:

[youtube:tab] Downloading playlist PL4AuQ4N7WOYWcuMqieipZCVNxfTevy3ZF - add --no-playlist to just download video Wt7rR0MCYsg
[youtube:tab] PL4AuQ4N7WOYWcuMqieipZCVNxfTevy3ZF: Downloading webpage
[youtube] Wt7rR0MCYsg: Downloading webpage


and if I add `--write-sub` like this

`youtube-dl --write-sub --write-auto-sub --sub-lang es --skip-download https://youtu.be/Wt7rR0MCYsg`

the ouput is:

[youtube] Wt7rR0MCYsg: Downloading webpage
WARNING: es subtitles not available for Wt7rR0MCYsg


But is available on auto-translate in the gui of youtube

**Comment by tuanbs** [comment]
> 

@titusfx Seems like it doesn't work with your video using cmd: `youtube-dl --write-auto-sub --sub-lang=es --skip-download "https://www.youtube.com/watch?v=Wt7rR0MCYsg"`

It works with other video like `youtube-dl --write-auto-sub --sub-lang=es --skip-download "https://www.youtube.com/watch?v=LUBNGJZP8m4"`

Anyway, even if you get the result, it is a very bad quality translated subtitle because YouTube-dl doesn't support downloading the auto-translate sub. My alternative approach is to use the plugin called [youtube_explode_dart](https://pub.dev/packages/youtube_explode_dart/changelog) to download the auto-translation with good quality. I use this plugin to create the mobile app written in Flutter framework.
