### ISSUE TITLE
please add file-up.org

### ISSUE THREAD

**Issue by treble2019** [ytdl-org/youtube-dl#22530]
- [X] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2019.09.28**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs violate any copyrights
- [X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.file-up.org/ahgsjwtl87iv

**Comment by jhalvors-school** [comment]
It appears this site needs a captcha in order to access the file link.
