### ISSUE TITLE
Compiling it to PYC to reduce loading time.

### ISSUE THREAD

**Issue by joeschmoe40** [ytdl-org/youtube-dl#22534]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

(Running under Linux - latest version (2019.09.28))

The version of youtube-dl that I've used for many years now comes as a ZIP file with the first line being "#!/usr/bin/env python".  It works fine, but takes a while to load.  I am looking to speed that up.  I have a cron job that runs every morning (early) and does "youtube-dl -U".  I mention this just to be clear that that's how I keep it up-to-date.

Here's what I have done - and it seems to work, but I have not tested throughly.

Is this OK?  Or is there a better way to get a compiled version?

1) Make a copy of youtube-dl - remove the first line.  Save this as "foo.zip".
2) unzip foo
3) python -m compileall ./
4) zip -q youtube-dl *.pyc youtube-dl/*.pyc youtube_dl/*/*.pyc
5) { echo '#!/usr/bin/python';cat youtube-dl.zip; } > youtube-dl.py
6) chmod +x youtube-dl.py && time ./youtube-dl.py

This all seems to work, and the resulting executable, while bigger (about 2.4M vs. about 1.7M) than the original, loads and runs faster (about 1.2 seconds vs. 5.4 seconds).

**Comment by joeschmoe40** [comment]
For some reason, it seems to have removed the asterisks in the "zip" command line.

It should read {star}.pyn in each of the three places.

**Comment by dstftw** [comment]
Use lazy extractors.

**Comment by joeschmoe40** [comment]
What does "use lazy extractors" mean?

(I have no idea what you mean by that or why you closed the thread)

**Comment by joeschmoe40** [comment]
Also, how do I "un-close" the thread?

**Comment by joeschmoe40** [comment]
Hmmm.

No response.  Maybe moderators screwed up???

Anyway, how do I un-close this?

**Comment by Hrxn** [comment]
You can't.

**Comment by joeschmoe40** [comment]
OK.  So I need to start a new thread.

**Comment by Hrxn** [comment]
Probably not.

There is some code for lazy loading in `youtube-dl/devscripts`...

But this did not went ahead so far.
To be honest, the priority is not really there. That bit of loading time does not matter, download time is always the deciding factor.

**Comment by joeschmoe40** [comment]
Generally, that would be true (that load time is small compared to download time).

But my use of youtube-dl is primarily not for downloading, but only for "translating" "web-page" URL to "download" URL.  Then I play the video via a player that can play URLs directly without downloading them.

My general feeling is that the process takes about 10-15 seconds, and I think about 2/3 of that is the loading time.  If I can get the loading time down from about 10 seconds to 5 seconds, that's a significant improvement.

Stuff I've read on another support board indicates that if you install youtube-dl via "pip" instead of via direct download (and subsequent use of "-U"), you will get a pre-compiled version and that that version loads faster.

However, since I don't understand what "pip" is or why it is worth learning about it, I prefer to stick with the method(s) I'm familiar with.
