### ISSUE TITLE
Youtube - Some formats won't download or won't play.

### ISSUE THREAD

**Issue by Omaraptor** [ytdl-org/youtube-dl#22541]
Last week I start having trouble downloading certain videos from YouTube. I waited to see if later versions would help, but I am still having trouble.
 
The downloader errors on 1280x720. No file is saved.
The downloader receives data for 640x360, but VLC and xplayer won't play the file.
I have tried the downloader on a Debian 8 PC and a Windows 7 PC, they both have the same issue, as well.

Below, I have pasted in result of my command line interactions. 

Om@Gna:~/Downloads/00 - TV$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.2
DISTRIB_CODENAME=tina
DISTRIB_DESCRIPTION="Linux Mint 19.2 Tina"
Om@Gna:~/Downloads/00 - TV$ ../youtube-dl --version
2019.09.28
Om@Gna:~/Downloads/00 - TV$ ../youtube-dl -f 22  https://www.youtube.com/watch?v=C1hwx_6hvb8
[youtube] C1hwx_6hvb8: Downloading webpage
[youtube] C1hwx_6hvb8: Downloading video info webpage
[download] Destination: How a Little Paint Saves Sailors from Drowning-C1hwx_6hvb8.mp4
[download]   0.1% of 84.59MiB at 671.97KiB/s ETA 02:08[download] Got server HTTP error: Downloaded 80947 bytes, expected 88694799 bytes. Retrying (attempt 1 of 10)...

ERROR: Did not get any data blocks
Om@Gna:~/Downloads/00 - TV$ ../youtube-dl -f 18  https://www.youtube.com/watch?v=C1hwx_6hvb8
[youtube] C1hwx_6hvb8: Downloading webpage
[youtube] C1hwx_6hvb8: Downloading video info webpage
[download] Resuming download at byte 80947
[download] Destination: How a Little Paint Saves Sailors from Drowning-C1hwx_6hvb8.mp4
[download] 100% of 25.39MiB in 00:01
Om@Gna:~/Downloads/00 - TV$ vlc How\ a\ Little\ Paint\ Saves\ Sailors\ from\ Drowning-C1hwx_6hvb8.mp4 
VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)
[0000556738335570] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: no
[h264 @ 0x7f6da4c93c20] Invalid NAL unit size (1851776241 > 150840).
[h264 @ 0x7f6da4c93c20] Error splitting the input into NAL units.
[h264 @ 0x7f6da4ca58a0] Invalid NAL unit size (1907682404 > 27397).
[h264 @ 0x7f6da4ca58a0] Error splitting the input into NAL units.
[h264 @ 0x7f6da4ceb500] Invalid NAL unit size (1281236768 > 205).
[h264 @ 0x7f6da4ceb500] Error splitting the input into NAL units.
[h264 @ 0x7f6da4d07620] Invalid NAL unit size (-1081194170 > 6685).
[h264 @ 0x7f6da4d07620] Error splitting the input into NAL units.
[h264 @ 0x7f6da4d236a0] Invalid NAL unit size (1805865034 > 8014).
[h264 @ 0x7f6da4d236a0] Error splitting the input into NAL units.
[h264 @ 0x7f6da4c93c20] Invalid NAL unit size (-608614163 > 5499).
[h264 @ 0x7f6da4c93c20] Error splitting the input into NAL units.
[h264 @ 0x7f6da4ca58a0] Invalid NAL unit size (1576351262 > 25325).
[h264 @ 0x7f6da4ca58a0] Error splitting the input into NAL units.
[h264 @ 0x7f6da4ceb500] Invalid NAL unit size (-517773073 > 4429).
[h264 @ 0x7f6da4ceb500] Error splitting the input into NAL units.
[h264 @ 0x7f6da4d07620] Invalid NAL unit size (-1011877341 > 7910).
[h264 @ 0x7f6da4d07620] Error splitting the input into NAL units.
[h264 @ 0x7f6da4d236a0] Invalid NAL unit size (-1918853067 > 7747).
[h264 @ 0x7f6da4d236a0] Error splitting the input into NAL units.
[h264 @ 0x7f6da4c93c20] Invalid NAL unit size (-1096662441 > 4588).
[h264 @ 0x7f6da4c93c20] Error splitting the input into NAL units.
[h264 @ 0x7f6da4ca58a0] Invalid NAL unit size (-1660608064 > 30957).
[h264 @ 0x7f6da4ca58a0] Error splitting the input into NAL units.
[h264 @ 0x7f6da4ceb500] Invalid NAL unit size (-550818557 > 6089).
[h264 @ 0x7f6da4ceb500] Error splitting the input into NAL units.
[00007f6da4c700b0] main decoder error: buffer deadlock prevented
[h264 @ 0x7f6da4d07620] Invalid NAL unit size (-1737805542 > 9548).
[h264 @ 0x7f6da4d07620] Error splitting the input into NAL units.
[h264 @ 0x7f6da4d236a0] Invalid NAL unit size (-1885806734 > 9152).

...etc...

[h264 @ 0x7f6da4c93c20] Error splitting the input into NAL units.
^CQObject::~QObject: Timers cannot be stopped from another thread
Om@Gna:~/Downloads/00 - TV$ head How\ a\ Little\ Paint\ Saves\ Sailors\ from\ Drowning-C1hwx_6hvb8.mp4 
ftypmp42isommp428�moovlmvhdٳ]ٳ]]��RI@)3trak\tkhdٳ]ٳ]�PN@�$edtselst�PN�(�mdia mdhdٳ]ٳ]]��PNU�_hdlrvideISO Media file produced by Google Inc. Created on: 09/26/2019.

**Comment by dstftw** [comment]
Server side Youtube issue.
