### ISSUE TITLE
How to download playlist using a extrenal downloader?

### ISSUE THREAD

**Issue by wavebit** [ytdl-org/youtube-dl#22540]
Example:
youtube-dl --yes-playlist --external-downloader aria2c  --external-downloader-args "--max-connection-per-server=16 --min-split-size=1M --split=10" https://www.youtube.com/watch?v=u2MfDE-_uik&list=PLVac-xziP_7PqxXqWow4tPZVIT_e9rBpG

The external downloader aria2c is not called.

**Comment by dstftw** [comment]
External downloaders don't support fragmented protocols.
