### ISSUE TITLE
it.xvideos.com not recognized as xvideo

### ISSUE THREAD

**Issue by colemar** [ytdl-org/youtube-dl#22555]
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

https://it.xvideos.com/video31894571/vera_ragazza_amatoriale_leccare_la_figa_ubriaca_-_livefreegirl.com
https://it.xvideos.com/video31894571/

## Description

It falls back to generic information extractor:

`$ youtube-dl -v 'https://it.xvideos.com/video31894571/vera_ragazza_amatoriale_leccare_la_figa_ubriaca_-_livefreegirl.com'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://it.xvideos.com/video31894571/vera_ragazza_amatoriale_leccare_la_figa_ubriaca_-_livefreegirl.com']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-151-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] vera_ragazza_amatoriale_leccare_la_figa_ubriaca_-_livefreegirl: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vera_ragazza_amatoriale_leccare_la_figa_ubriaca_-_livefreegirl: Downloading webpage
[generic] vera_ragazza_amatoriale_leccare_la_figa_ubriaca_-_livefreegirl: Extracting information
ERROR: Unsupported URL: https://it.xvideos.com/video31894571/vera_ragazza_amatoriale_leccare_la_figa_ubriaca_-_livefreegirl.com
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2373, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3355, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://it.xvideos.com/video31894571/vera_ragazza_amatoriale_leccare_la_figa_ubriaca_-_livefreegirl.com`

This rewritten URL works as expected:

`$ youtube-dl -v 'https://xvideos.com/video31894571/'                                                                 [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://xvideos.com/video31894571/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-151-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[XVideos] 31894571: Downloading webpage
[XVideos] 31894571: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://hls2-l3.xvideos-cdn.com/0c6cc14f5cdea5b88f20d2c3d6f98a2acbfa9fce-1569859590/videos/hls/a1/d1/e8/a1d1e84112a79e467e3b65f85eca679c-1/hls-720p.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 8
[download] Destination: real amateur girl licking drunk pussy - LiveFreeGirl.com-31894571.mp4
[download] 100% of 12.12MiB in 00:01
[debug] ffmpeg command line: ffprobe -show_streams 'file:real amateur girl licking drunk pussy - LiveFreeGirl.com-31894571.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "real amateur girl licking drunk pussy - LiveFreeGirl.com-31894571.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:real amateur girl licking drunk pussy - LiveFreeGirl.com-31894571.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:real amateur girl licking drunk pussy - LiveFreeGirl.com-31894571.temp.mp4'`

**Comment by whoamikyo** [comment]
could put xvideos.red domain too btw.
