### ISSUE TITLE
Download list to null

### ISSUE THREAD

**Issue by probecomcn** [ytdl-org/youtube-dl#22562]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Team when i download a list.txt to null i get an error
youtube-dl -a /home/list.txt -o '/dev/null'

result is too many files to download 
what is the right command 

Regards

**Comment by dstftw** [comment]
You can't do that.

**Comment by probecomcn** [comment]
If i need to test the maximum speed of a link i will have to have a new list each time 
why cannot do that ? i can download one file to null easily

**Comment by probecomcn** [comment]
Sergey please can you explain why ?
