### ISSUE TITLE
FranceTV: No video formats found

### ISSUE THREAD

**Issue by manu3l** [ytdl-org/youtube-dl#22561]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2019.09.28**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$  youtube-dl --verbose https://www.france.tv/france-5/echappees-belles/echappees-belles-saison-13/1066323-l-alsace-de-village-en-village.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.france.tv/france-5/echappees-belles/echappees-belles-saison-13/1066323-l-alsace-de-village-en-village.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.16 (CPython) - Linux-5.2.16
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4
[debug] Proxy map: {}
[FranceTVSite] 1066323-l-alsace-de-village-en-village: Downloading webpage
[FranceTV] 18d23407-e217-4e76-a031-97da56c43e3f: Downloading video JSON
[FranceTV] 18d23407-e217-4e76-a031-97da56c43e3f: Downloading geo restriction info
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 209, in _real_extract
    return self._extract_video(video_id, catalog)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 169, in _extract_video
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Download is impossible while https://www.france.tv/france-5/echappees-belles/echappees-belles-saison-13/1057401-grece-etape-en-macedoine.html available on the same page works.
I'm in France with a local connexion.

**Comment by Europe57** [comment]
Now is OK

```
youtube-dl -k -R "infinite" https://www.france.tv/france-5/echappees-belles/echappees-belles-saison-13/1057401-grece-etape-en-macedoine.html -F
[FranceTVSite] 1057401-grece-etape-en-macedoine: Downloading webpage
[FranceTV] 6037868a-a872-4ba3-bed6-c71c9bce388b: Downloading video JSON
[FranceTV] 6037868a-a872-4ba3-bed6-c71c9bce388b: Downloading geo restriction info
[FranceTV] 6037868a-a872-4ba3-bed6-c71c9bce388b: Downloading signed m3u8-download manifest URL
[FranceTV] 6037868a-a872-4ba3-bed6-c71c9bce388b: Downloading m3u8 information
[FranceTV] 6037868a-a872-4ba3-bed6-c71c9bce388b: Downloading signed hls_v5_os manifest URL
[FranceTV] 6037868a-a872-4ba3-bed6-c71c9bce388b: Downloading m3u8 information
[info] Available formats for 6037868a-a872-4ba3-bed6-c71c9bce388b:
format code        extension  resolution note
hls_v5_os-205      mp4        256x144     205k , avc1.66.30, mp4a.40.2
m3u8-download-205  mp4        256x144     205k , avc1.66.30, mp4a.40.2
hls_v5_os-328      mp4        320x180     328k , avc1.66.30, mp4a.40.2
m3u8-download-328  mp4        320x180     328k , avc1.66.30, mp4a.40.2
hls_v5_os-608      mp4        512x288     608k , avc1.66.30, mp4a.40.2
m3u8-download-608  mp4        512x288     608k , avc1.66.30, mp4a.40.2
hls_v5_os-871      mp4        704x396     871k , avc1.77.30, mp4a.40.2
m3u8-download-871  mp4        704x396     871k , avc1.77.30, mp4a.40.2
hls_v5_os-1522     mp4        1024x576   1522k , avc1.77.30, mp4a.40.2 (best)
```

**Comment by Europe57** [comment]
Confirm, sownload is impossible on adress `https://www.france.tv/france-5/echappees-belles/echappees-belles-saison-13/1066323-l-alsace-de-village-en-village.html`

PS: You're link in description is false : `https://www.france.tv/france-5/echappees-belles/echappees-belles-saison-13/1057401-grece-etape-en-macedoine.html`

**Comment by rogues32** [comment]
## Checklist

- [ X] I'm reporting a broken site support issue
- [ X] I've verified that I'm running youtube-dl version **2019.10.16**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.france.tv/documentaires/histoire/1074473-la-france-d-avant-1914.html', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.16
[debug] Python version 2.7.10 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[FranceTVSite] 1074473-la-france-d-avant-1914: Downloading webpage
[FranceTV] 2196355e-78a1-427f-bc23-b45e836f4562: Downloading video JSON
[FranceTV] 2196355e-78a1-427f-bc23-b45e836f4562: Downloading geo restriction info
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 209, in _real_extract
    return self._extract_video(video_id, catalog)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 169, in _extract_video
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

I have the same issue as above but using a different URL. Added here to avoid duplicates. I am also in France with a local connection.

**Comment by louisabraham** [comment]
I encountered two bugs. The first was 

```
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/youtube_dl/extractor/francetv.py", line 103, in _extract_video
    allowed_countries = info['videos'][0].get('geoblocage')
IndexError: list index out of range
```

I think this is incorrect to assume `info['videos']` is not empty.

The second error was 

```
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

and was fixed by bad52881494c46f5790dddcd3b8ff4b7f4e959cc

Thank you very much @gdouezangrard!

**Comment by manikbh** [comment]
Same problem, it is unfortunate that the fix which works perfectly is not integrated into the release yet...

**Comment by djibux** [comment]
Hello, I can confirm that bad52881494c46f5790dddcd3b8ff4b7f4e959cc fixes the issue #26505.
It seems the commit doesn't belong to any branch.  How can it be merged into master?

**Comment by gdzx** [comment]
@djibux On the contrary, it belongs to the master branch in my fork.

**Comment by djibux** [comment]
My bad, I got confused by the message `This commit does not belong to any branch on this repository.`.
Maybe you could submit a PR in this repository?

**Comment by llacb47** [comment]
> Maybe you could submit a PR in this repository?

.... https://github.com/ytdl-org/youtube-dl/pull/23000

**Comment by djibux** [comment]
OK maybe I just need to go to bed ;)
Sorry for the trouble.  Hope the PR gets accepted.
