### ISSUE TITLE
Youtube-dl can't pull videos from subscription box anymore since 9/28 update.

### ISSUE THREAD

**Issue by Capacino** [ytdl-org/youtube-dl#22565]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2019.09.28**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
C:\Youtube-dl>youtube-dl.exe --verbose https://www.youtube.com/feed/subscriptions
[debug] System config: []
[debug] User config: ['--cookies', 'C:/Youtube-dl/cookies.txt', '-i', '--match-filter', '!is_live', '--download-archive', '~/Downloads/archive.txt', '--max-downloads', '85', '--dateafter', 'now-10days', '--yes-playlist', '-x', '--audio-format', 'mp3', '--audio-quality', '0', '-o', 'F:/Downloads/Music/Subs4/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/feed/subscriptions']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-78930-g238ddd6, ffprobe N-78930-g238ddd6
[debug] Proxy map: {}
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
[youtube:subscriptions] playlist Youtube Subscriptions: Downloading 0 videos
[download] Finished downloading playlist: Youtube Subscriptions

## Description

WRITE DESCRIPTION HERE
Exactly as the title says. Youtube-dl doesn't download from subscription feed anymore. Worked perfectly fine until the 9/28 update.

**Comment by dstftw** [comment]
Expired cookies or empty subscription list.
