### ISSUE TITLE
Site Support: Academy Hacker

### ISSUE THREAD

**Issue by diman82** [ytdl-org/youtube-dl#22570]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://academyhacker.com/courses/215041/lectures/3336242
- Single video: https://academyhacker.com/courses/215041/lectures/3336260
- Playlist: https://academyhacker.com/courses/enrolled/215041

## Description

Additional information:
**Account credentials will be provided in a private message.**

**Comment by dstftw** [comment]
Already supported,

**Comment by diman82** [comment]
> Already supported,

Please add it to [youtube-dl supported sites list](https://ytdl-org.github.io/youtube-dl/supportedsites.html)

**Comment by dstftw** [comment]
It's already added as Teachable.
