### ISSUE TITLE
ERROR: Failed to download m3u8 information: '' (caused by BadStatusLine("''",))

### ISSUE THREAD

**Issue by azteca72** [ytdl-org/youtube-dl#22573]
Hey, Folks!

I was in the middle, of downloading a series of dorumentaries, first two worked like charms, at the third I got an error.
Then I got an error on everything, that I attempted.
So, I connected to a remote machine, and got the same error there.

As you can see from the verbose protocol, Youtube-dl is up to date.
This is the verbose output:

youtube-dl --verbose https://tvthek.orf.at/profile/zeit-geschichte/13606695/zeit-geschichte-Wie-wir-wurden-Was-wir-sind-Generation-Oesterreich-6-6-1995-2008/14027254
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://tvthek.orf.at/profile/zeit-geschichte/13606695/zeit-geschichte-Wie-wir-wurden-Was-wir-sind-Generation-Oesterreich-6-6-1995-2008/14027254']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.9
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1, phantomjs 2.1.1
[debug] Proxy map: {}
[orf:tvthek] 14027254: Downloading webpage
[orf:tvthek] 14566586: Downloading m3u8 information
ERROR: Failed to download m3u8 information: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 2724, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)

As stated, the error appears with whatever you attempt to download from that site.
They must have changed something today around 19:30 CET.

These documentaries will be available only 4 more days.
I'd therefore be very grateful, if you could fix the problem swiftly.

My appreciation in advance, and yours, Claus

**Comment by dstftw** [comment]
Network issue on your side.
