### ISSUE TITLE
What to do when 'best' doesn't work on your script?

### ISSUE THREAD

**Issue by v9999** [ytdl-org/youtube-dl#22574]
- [x] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Hello there, I use youtube-dl through termux on android, using share functionality on youtube. 
To do this, I have this script set up (origin: https://www.reddit.com/r/Android/comments/66kehg/twoclick_downloads_of_youtube_videos_straight/):

`--no-mtime
-o /data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s
-f "best[height<=720]"`

However, this script won't work in videos that can't be downloaded with the "best" format.

Here's an example: https://www.youtube.com/watch?v=5a0ill945vs

The "-f best" argument returns "ERROR: Did not get any data blocks"

Without arguments, youtube-dl manages to download a file, but if I download all files without the best tag, I'll get huge files and storage is limited.

How can I make my script try no arguments only if it fails with best[height<=720]?

Thanks.

**Comment by dstftw** [comment]
You can't.
