### ISSUE TITLE
Cant run windows Exe

### ISSUE THREAD

**Issue by DaSniper12** [ytdl-org/youtube-dl#22580]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I tried using the windows exe on windows 10, and it opens the terminal, but then closes after a second. I am using Python 3.7.0b3.

**Comment by dstftw** [comment]
Google: how to run console apps.
