### ISSUE TITLE
Also not a server issue: ERROR: Failed to download m3u8 information: '' (caused by BadStatusLine("''",))

### ISSUE THREAD

**Issue by azteca72** [ytdl-org/youtube-dl#22586]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose https://tvthek.orf.at/profile/Thema/11523190/Thema/14027523
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://tvthek.orf.at/profile/Thema/11523190/Thema/14027523']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-11-amd64-x86_64-with-debian-9.11
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1, phantomjs 2.1.1
[debug] Proxy map: {}
[orf:tvthek] 14027523: Downloading webpage
[orf:tvthek] 14568199: Downloading m3u8 information
ERROR: Failed to download m3u8 information: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 2724, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)

```

## Description

Now, dear Sergey, I do understand, that you are obviously alone here, working off errors, so probably you do not have all too much time for single issues.
To me this is an issue, that is MISSION CRITICAL, since your wonderful piece of software seems to be the only available solution to download from the site in the link.

As your "customer", however I am slowly but surely becoming disgruntled by the way, you brush my concern off.
1.) you declare the issue a **network issue on MY side**, with no check and no explanation at all.
which it is clearly NOT.
As we have meanwhile established, since it does not work from three different locations.
And also for several of your customers.
2.) next you "explain", that the problem can be reproduced from time to time on a LONG PLAYLIST.
So next I explain to you, that for me **the issue does not occur from time to time, but at 100% of the time.
Or in other words, ALWAYS.**
Hence, has absolutely nothing to do with the length of the playlist. 
3.) next you **ASSUME**, that their servers are overloaded.
"Moslt likely" was your choice of words.
"Most likely" is not a FACT BASED CONCLUSION, and on top of it it is most likely a wrong conclusion.
4.) next you do not only **keep closing threads** on **pretty obviously wrong assumptions**, but then also you **ban us from responding**, thus, **ban us from CORRECTING YOUR WRONG ASSUMPTIONS**, that you have met by **JUMPING TO FACTUALLY UNSUPPORTED CONCLUSIONS**.
That is simply fascistoid.
What's next, are you gonna have me kicked off github for trying to contribute to the reliability and versatility of your software?

First of all, I am an IT Professional, I am therefore very well capable of coming up with an educated guess, whether your **ASSUMPTIONS** are actually **PLAUSIBLE**.
Which, in my humble opinion, **they are NOT**.
Each single one of them four NOT.

Second.
Despite the fact, that I am pretty certainly annoying you with my persistence,  I am not your enemy, but rather the contrary.
I am exactly that kind of customer, that makes sure, that your product remains a kick ass, cutting edge, highly effective, and very well functioning piece of software.
Which it used to be until only just yesterday.

Third.
Since orf.tv.at and youtube are the only two platforms I use it on, and one of which is currently DEFUNCT, that renders your application 2,5 Stars out of 5, since very much to my regret  to me **it is currently 50% useless**.
I would therefore kindly like to ask you to understand my repeated requests for what they are.
A CONTRIBUTION TO THE QUALITY MANAGEMENT OF YOUR PRODUCT.

Now, back to the topic.
Since your version of youtube-dl produces a completely different output than mine, I must assume, that you are using a different operating system, than me.
Hence, maybe completely differently implemented functions.
I am using two different versions of debian Linux, on this machine 9.11, and on the other one 8.something.
Both machines have begun to produce the above described error at exaclty the same time, and ever since **not from time to time, but ALWAYS**.
I keep repeating, I can watch everything, I can download NOTHING.
Not from time to time, but ALWAYS.
So, YES, your fourth ASSUMPTION is just as WRONG as your other three ASSUMPTIONS.

You can of course always tell me, that you do not care about me and my concern, or about the platform, that I am reporting youtube-dl to be broken for.
What you cannot, however is, keep on brushing me off with phoney assumptions without even trying to understand.

No, you are under no obligation to help me with my issue.
It is your decision and your decision alone, whether you want to keep the high standard of your application up.

Should you, however,  again try to mute me, and to brush my very valid concerns off, like you did in the past, so that I cannot even correct you in your wrong assuptions, then will I have github look into your modus operandi, whether it meets github's community standards.
Or in other words.
Even if time is scarce.
I wish to be taken seriously.
Please.
For that, I am ready to cooperate, and to come up with any kind of information, that I can provide.
It is also my time, that I am investing.
So, feel free to ask.

I would once more like to ask your forgiveness for my persistence, but since this software is crucial to me, to simply accept, that it will not work from now on, is a no-go for me.
Please do invest the time, to secure, that your masterpiece stays one.
Let me help you repair it.

Thank you in advance, Claus.

**Comment by dstftw** [comment]
I'm not going to read this wall of useless text and will just summarize:
1. This is an intermittent server side issue since webplayer suffers from the same error.
2. Some workarounds that may mitigate the issue have been pushed to master and will be available in the next release.
3. All further duplicates for this issue will be considered spam with all the consequences.
