### ISSUE TITLE
"Unknown ETA" and "Unknown speed" when using local fragments

### ISSUE THREAD

**Issue by spookyahell** [ytdl-org/youtube-dl#22584]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
(Removed) - would NOT help here, if required can be added

## Description
While youtube-dl is using local fragments it says "Unknown ETA" and "Unknown speed" - this is ofc because it is not actively downloading but merely rushing through local fragments (stored via `--keep-fragments` - it would be better if it could say something like "loading local segments..." to accurately report what's actually happening (which replaces both "Unknown ETA" and "Unknown speed" in that case)

Just an idea.... maybe more of a feature request but it not saying what it's doing (parsing local segments) is kindof a bug... well maybe not... but still sth that should be thought about

alternatively it could say "LocalLoading" or sth similar where it says "download" (at the beginning of the progress/current stage line)

**Comment by dstftw** [comment]
youtube-dl is not using local fragments reassembly for a long time.

**Comment by spookyahell** [comment]
Okay that's weird... it definetly is on my end... on both Linux and Windows - or how do you explain the speeding from 0 to 90% when almost all fragments are downloaded... it could only happen if youtube-dl is using fragments stored on the local hard drive....

**Comment by dstftw** [comment]
Again: youtube-dl is not using this approach for more than two years now. Such behavior is only possible if you **manually** remove main partially downloaded file and `.ytdl` metafile along with `--keep-fragments` but you must not do so.
