### ISSUE TITLE
Udemy - "Course nnnn is not free." on paid-for course, after partial download

### ISSUE THREAD

**Issue by marcvisconte** [ytdl-org/youtube-dl#22601]
## Checklist
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.09.28**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs & arguments w/ special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--restrict-filenames', '--cookies', '.\\cookies.txt', '-f', 'best', '-o', './Dload_p2/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', '--add-metadata', '--ffmpeg-location', 'F:\\xfers-progs\\ffmpeg_81462\\bin\\ffmpeg.exe', '--postprocessor-args', '-id3v2_version 3', 'https://www.udemy.com/comptia-security-certification-sy0-501-the-total-course/', '--playlist-start', '36']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.6.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81462-gbcd1153, ffprobe N-81462-gbcd1153
[debug] Proxy map: {}
[udemy:course] comptia-security-certification-sy0-501-the-total-course: Downloading webpage
ERROR: Course 1596138 is not free. You have to pay for it before you can download. Use this URL to confirm purchase: https://www.udemy.com/cart/checkout/express/course/1596138/
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\program files\python36\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\program files\python36\lib\site-packages\youtube_dl\extractor\udemy.py", line 444, in _real_extract
    self._enroll_course(url, webpage, course_id)
  File "c:\program files\python36\lib\site-packages\youtube_dl\extractor\udemy.py", line 97, in _enroll_course
    expected=True)
youtube_dl.utils.ExtractorError: Course 1596138 is not free. You have to pay for it before you can download. Use this URL to confirm purchase: https://www.udemy.com/cart/checkout/express/course/1596138/

```
## Description

I have purchased a few courses from Udemy.  I have downloaded 1 course fully, needing to restart it about 1/3 the way through.  I split that d/l into two sessions for the remaining lessons, and it finished fine.

This last course started downloading, and I got through 35 of the lessons and then the process died.
I have tried restarting the full playlist download, re-specifying using --playlist.  
I have tried using --username and --password as well as --cookies with a fresh export of all cookies.

The download errored out with the same message that I get with every new try:
Course 1596138 is not free. You have to pay for it before you can download. Use this URL to confirm purchase: https://www.udemy.com/cart/checkout/express/course/1596138/

I succeeded in downloading the first 35 lessons.
I can see the course in my account using the browser, and can play lessons from it.  
I exported cookies from the same session.

**Comment by marcvisconte** [comment]
The course view from my account:

![Udemy_001_2019_10_04-1705](https://user-images.githubusercontent.com/35472639/66181187-d6a45c00-e63d-11e9-9643-282ce4bad83e.jpg)

The lessons view, from my account:
![Udemy_002_2019_10_04-1714](https://user-images.githubusercontent.com/35472639/66181196-ddcb6a00-e63d-11e9-848b-5b3d8d3cc13e.jpg)

**Comment by dstftw** [comment]
You must provide account credentials for any work on this.

**Comment by marcvisconte** [comment]
Sergey, 
I understand.  At the same time, I would like to:

- transmit the credentials confidentially, and, 
- limit the amount of time that those credentials are valid, 

to protect my account.

How can I do that?
