### ISSUE TITLE
Quality loss when downloading from Instagram

### ISSUE THREAD

**Issue by xxxajent0range** [ytdl-org/youtube-dl#22603]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hello, I'm trying to use youtube-dl to get source-quality video downloads from Instagram, but I always get a quality reduction. Any tips on how to fix this, if it's possible?

**Comment by witedragen** [comment]
afaik you need to sign in with instagram username and password to get source-quality downloads. same goes for pics too
