### ISSUE TITLE
Soundcloud download error on some URLs

### ISSUE THREAD

**Issue by vtyutin** [ytdl-org/youtube-dl#22602]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl.exe --verbose https://soundcloud.com/nero/nero-into-the-past
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://soundcloud.com/nero/nero-into-the-past']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[soundcloud] nero/nero-into-the-past: Downloading webpage
[soundcloud] nero/nero-into-the-past: Downloading info JSON
[soundcloud] 89121986: Downloading track url
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[soundcloud] 89121986: Checking fallback video format URL
[soundcloud] 89121986: fallback video format URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you
are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the
 --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_
dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_
dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_
dl\extractor\soundcloud.py", line 449, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_
dl\extractor\soundcloud.py", line 388, in _extract_info_dict
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91grvc\build\youtube_
dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure t
o call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE

This issue exists since summer. Please fix it ASAP. URL working well in browser but failed in youtube-dl. I do need it fixed soon.

**Comment by vtyutin** [comment]
But issue still exists. It reported from summer and still not fixed. When are you going to fix it???

**Comment by vtyutin** [comment]
@dstftw  please give me a link to duplicate ticket. This issue with SoundCloud exist since summer and still no updated when it can be fixed. Can you let me know the plans for this issue?

**Comment by vtyutin** [comment]
@dstftw please give me a link to duplicate ticket. This issue with SoundCloud exist since summer and still no updated when it can be fixed. Can you let me know the plans for this issue?

**Comment by vtyutin** [comment]
@dstftw please give me a link to duplicate ticket. This issue with SoundCloud exist since summer and still no updated when it can be fixed. Can you let me know the plans for this issue?

**Comment by dstftw** [comment]
Use search already.
