### ISSUE TITLE
mp4 format not working on 1080p youtube videos

### ISSUE THREAD

**Issue by CobusJjimjilbang** [ytdl-org/youtube-dl#22608]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v --format mp4 https://www.youtube.com/watch?v=aEVb3rrooBQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--format', u'mp4', u'https://www.youtube.com/watch?v=aEVb3rrooBQ']
[debug] Command-line args: [u'-v', u'--format', u'mp4', u'https://www.youtube.com/watch?v=aEVb3rrooBQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.9 (CPython) - Linux-4.9.35-v7+-armv7l-with-debian-8.0
[debug] exe versions: avconv 11.12-6, avprobe 11.12-6, phantomjs present
[debug] Proxy map: {}
[youtube] aEVb3rrooBQ: Downloading webpage
[youtube] aEVb3rrooBQ: Downloading video info webpage
[debug] Invoking downloader on u'https://r4---sn-q4flrne6.googlevideo.com/videoplayback?expire=1570236235&ei=65KXXcGzG5GVwQGp0Z6wBw&ip=68.12.130.220&id=o-AGtG_i5zZXnM1b3ax5iNOXmO8M1UAHNqFxQ16DbmRv0V&itag=22&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-q4flrne6%2Csn-vgqs7nlk&ms=au%2Conr&mv=m&mvi=3&pl=16&initcwndbps=1730000&mime=video%2Fmp4&ratebypass=yes&dur=928.798&lmt=1569687604289103&mt=1570214540&fvip=4&fexp=23842630&c=WEB&txp=3416222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIhAI0fk4hWtPHkBAaCiTT8K8LJXvhug5N4Yfc6XfSsq-XtAiBBCbGvmkFEZjW-GBAe_Vz_yLXKSWz2rghOC2xReJKnPw%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAKD3dcdvyJgCt75QdGheOJAAzwNRpDJtbOLwIDW7z-CjAiARuTnKNMaoetLx6ZgGeE25uTV8tWzbTth1pQAVzpKolA%3D%3D'
[download] Destination: spooky_time.mp4-aEVb3rrooBQ.mp4
[download]   0.2% of 166.33MiB at  1.09MiB/s ETA 02:33[download] Got server HTTP error: Downloaded 325879 bytes, expected 174404698 bytes. Retrying (attempt 1 of 10)...


ERROR: Did not get any data blocks
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 320, in download
    retry(err)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 225, in retry
    raise RetryDownload(e)
RetryDownload
```

## Description

- The playable codecs available to me are limited, so I typically run youtube-dl with `--format mp4`
- When downloading youtube videos with 1080p, asking for mp4 causes the above failure
- I **Assume** that this is because youtube is storing 1080p as **video only**, and explicitly calling `--format mp4` doesn't handle that situation well
-- The video above has this format listed, and I assume it's what it attempts to download: `137          mp4        1920x1080  1080p 3748k , avc1.640028, 30fps, video only, 183.60MiB`
-- if I run without `--format mp4` it handles this situation very well, and the resulting mkv fits my needs, however videos without 1080 might default to a codec I cannot consume (like webm)
-- at this point I actually have a script that checks formats and runs it with `--format mp4` if the video does not have 1080p...but I figured other people might want the `--format mp4` option to do the merging and result in a mkv containing mp4 video...or somehow handle this format type smoother

**Comment by dstftw** [comment]
Server side Youtube error for format 22.
