### ISSUE TITLE
When youtube-dl runs multiple instances, cookies are overwritten

### ISSUE THREAD

**Issue by bidaian** [ytdl-org/youtube-dl#22613]
## Checklist

- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]
```
## Description

If I run more than one simultaneous youtube-dl instance on different sites, with a cookie jar (--cookie), the jars are overwritten each time. The result is that you keep just the cookies from the last write.

That is expected according to [the Python documentation on cookiejar](https://docs.python.org/3/library/http.cookiejar.html) but it does not allow for multiple simultaneous downloads from different sites, if cookies are involved.

**Comment by dstftw** [comment]
Single cookie file is not supposed to be shared across simultaneous youtube-dl instances in the first place.
