### ISSUE TITLE
The concept of "best" subtitle format is not described in the docs

### ISSUE THREAD

**Issue by lkintact** [ytdl-org/youtube-dl#22623]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

On the readme page for youtube-dl (https://github.com/ytdl-org/youtube-dl/blob/master/README.md) a `--sub-format` option is described:
```
--sub-format FORMAT              Subtitle format, accepts formats
                                 preference, for example: "srt" or
                                 "ass/srt/best"
```
It's not quite clear however what exactly the "best" subtitle format is or how what's "best" is determined. Running youtube-dl with `--list-subs` gives a list of subtitles, but none of them has a `(best)` mark like the items of video/audio formats in the lists produced with `--list-formats`.

**Comment by dstftw** [comment]
This is an implementation detail depending on a particular extractor.

**Comment by lkintact** [comment]
@dstftw Thank you, Sergey M. Maybe your answer should be reflected in the FORMAT SELECTION of the readme page to prevent questions similar to mine?
