### ISSUE TITLE
[Question] Is there a way to --embed-subs after download?

### ISSUE THREAD

**Issue by Codingale** [ytdl-org/youtube-dl#22624]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Second time writing this as Github messed up so pardon if I'm not verbose enough.

Can I add subtitles to an already downloaded video, I mistook `--write-auto-sub` thinking it'd download English (the language of my system for some reason) and didn't think about it until I checked after all the videos were done in the Playlist.

I tried to do this to add them in but it says it's already downloaded and skips it:
`youtube-dl --embed-subs --write-sub --sub-lang en videoURI`

Any ideas how to remove the existing subtitle track and add on the intended (English) one simply? This video has 31 or so submitted subtitles if it's any relevance.

P.S. Perhaps an IRC or a discord for quick questions / community support could help lessen the issue-tracker's clutter / workload? I'm sure just like many of the API discords I'm in there's people willing to volunteer spare time to help people. 

Thanks.

**Comment by dstftw** [comment]
This command will do exactly what your want.
