### ISSUE TITLE
twitch.tv past-broadcasts now includes currently broadcasting (and thus incomplete) videos

### ISSUE THREAD

**Issue by mat8913** [ytdl-org/youtube-dl#22634]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--flat-playlist', '-j', '--playlist-end=10', 'https://www.twitch.tv/dreamhackcs/videos/past-broadcasts']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Lazy loading extractors enabled
[debug] Python version 3.7.4 (CPython) - Linux-4.19.76-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
{"_type": "url", "url": "https://www.twitch.tv/videos/491374727", "ie_key": "TwitchVod", "id": "v491374727"}
{"_type": "url", "url": "https://www.twitch.tv/videos/491007950", "ie_key": "TwitchVod", "id": "v491007950"}
{"_type": "url", "url": "https://www.twitch.tv/videos/490702223", "ie_key": "TwitchVod", "id": "v490702223"}
{"_type": "url", "url": "https://www.twitch.tv/videos/490499858", "ie_key": "TwitchVod", "id": "v490499858"}
{"_type": "url", "url": "https://www.twitch.tv/videos/490274475", "ie_key": "TwitchVod", "id": "v490274475"}
{"_type": "url", "url": "https://www.twitch.tv/videos/490056215", "ie_key": "TwitchVod", "id": "v490056215"}
{"_type": "url", "url": "https://www.twitch.tv/videos/489804829", "ie_key": "TwitchVod", "id": "v489804829"}
{"_type": "url", "url": "https://www.twitch.tv/videos/489593273", "ie_key": "TwitchVod", "id": "v489593273"}
{"_type": "url", "url": "https://www.twitch.tv/videos/489323757", "ie_key": "TwitchVod", "id": "v489323757"}
{"_type": "url", "url": "https://www.twitch.tv/videos/489210050", "ie_key": "TwitchVod", "id": "v489210050"}
```

## Description

Twitch has recently changed `past-broadcasts` to now include currently broadcasting livestreams. This breaks archiving scripts such as `tubeup` because it will download an incomplete stream. Please update `twitch:videos:past-broadcasts` to filter out currently broadcasting livestreams or alternatively add an option to filter them out.

In the above log, I used the "dreamhackcs" channel as an example because at the time of writing this, they are currently broadcasting and v491374727 is incomplete. To reproduce this in the future, you can find some currently broadcasting channels on twitch.tv in the "RECOMMENDED CHANNELS" section.

**Comment by ualnwe** [comment]
You might be able to add `--match-filter '!is_live'` to skip still broadcasting vods
Windows may need double quotes: `--match-filter "!is_live"`

Hopefully this helps!

**Comment by mat8913** [comment]
Thank you @ualnwe, that worked perfectly.
