### ISSUE TITLE
[YouTube] Unable to extract video data

### ISSUE THREAD

**Issue by fischr20** [ytdl-org/youtube-dl#22641]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
 youtube-dl -v --call-home --dump-single-json https://youtu.be/4V3sN0z6kls
[debug] System config: []
[debug] User config: ['--retries', '10', '--format', 'best', '--max-filesize', '1G', '--no-warnings', '--abort-on-error', '--no-overwrites', '--no-playlist', '--no-mtime', '--no-cache-dir', '--console-title', '--no-post-overwrites', '--embed-thumbnail', '--add-metadata', '--output', '~/public/%(id)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', '--call-home', '--dump-single-json', 'https://youtu.be/4V3sN0z6kls']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-22-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[debug] Public IP address: xxxxxxxxxxxxxxxxxxxx
ERROR: 4V3sN0z6kls: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1836, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: 4V3sN0z6kls: YouTube said: Unable to extract video data
```

## Description

The error is "ERROR: Unable to extract video data" and and i cannot reproduce it from multiple countries.

Not working for several URLs/IDs like:
ERROR: pUZoDgj9iHw: YouTube said: Unable to extract video data
ERROR: pUZoDgj9iHw: YouTube said: Unable to extract video data
ERROR: JVmty59D3Co: YouTube said: Unable to extract video data
ERROR: SoCs8HGurSY: YouTube said: Unable to extract video data
ERROR: -LhtcnrZSMs: YouTube said: Unable to extract video data
ERROR: fuBG_osuqy8: YouTube said: Unable to extract video data
ERROR: 6wB7k9SopIA: YouTube said: Unable to extract video data
ERROR: 6wB7k9SopIA: YouTube said: Unable to extract video data
ERROR: wKyTjWtx4qc: YouTube said: Unable to extract video data
ERROR: t6kpZOYecAc: YouTube said: Unable to extract video data
ERROR: uDD5u43EvE4: YouTube said: Unable to extract video data

Could you please help?

Many Thanks

**Comment by srhinos** [comment]
I'm able to reproduce this locally as of 0920 PST, can pull from other websites besides youtube (being that its broken).

**Comment by DevYukine** [comment]
I can also reproduce this with youtube-dl & other libraries (with node-ytdl-core for example) and it seems that youtube increased there ratelimits, i constantly get 429 responses by having ~60 concurrent connections on my machine.

**Comment by falsechicken** [comment]
I am also having this issue

`
youtube-dl -f 18 -v "https://www.youtube.com/user/ashens/videos"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'18', u'-v', u'https://www.youtube.com/user/ashens/videos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-65-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube:user] ashens: Downloading channel page
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading webpage
[download] Downloading playlist: Uploads from ashens
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading page #1
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading page #2
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading page #3
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading page #4
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading page #5
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading page #6
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading page #7
[youtube:playlist] playlist Uploads from ashens: Downloading 792 videos
[download] Downloading video 1 of 792
[youtube] gdCNE5L5yPw: Downloading webpage
[youtube] gdCNE5L5yPw: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: gdCNE5L5yPw: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1836, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: gdCNE5L5yPw: YouTube said: Unable to extract video data
`

**Comment by falsechicken** [comment]
I am also having this issue

```
youtube-dl -f 18 -v "https://www.youtube.com/user/ashens/videos"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'18', u'-v', u'https://www.youtube.com/user/ashens/videos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-65-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube:user] ashens: Downloading channel page
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading webpage
[download] Downloading playlist: Uploads from ashens
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading page #1
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading page #2
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading page #3
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading page #4
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading page #5
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading page #6
[youtube:playlist] UUxt9Pvye-9x_AIcb1UtmF1Q: Downloading page #7
[youtube:playlist] playlist Uploads from ashens: Downloading 792 videos
[download] Downloading video 1 of 792
[youtube] gdCNE5L5yPw: Downloading webpage
[youtube] gdCNE5L5yPw: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: gdCNE5L5yPw: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1836, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: gdCNE5L5yPw: YouTube said: Unable to extract video data
```

**Comment by falsechicken** [comment]
It appears to be working with my Ubuntu 19.10 desktop install but not the 18.04 server install.

**Comment by alexelisenko** [comment]
I am getting the same error on Ubuntu 18.04.2 LTS, youtube-dl version 2019.10.16. Was this confirmed fixed? because it seems to be ongoing.

**Comment by RenFinkle** [comment]
Experiencing the same behavior on Ubuntu 18.04

**Comment by falsechicken** [comment]
Yeah I am now getting the issue on 19.10

```
youtube-dl -v https://www.youtube.com/watch?v=pNtHwWVXbDI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=pNtHwWVXbDI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.16
[debug] Python version 2.7.17rc1 (CPython) - Linux-5.3.0-18-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] pNtHwWVXbDI: Downloading webpage
[youtube] pNtHwWVXbDI: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: pNtHwWVXbDI: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1836, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: pNtHwWVXbDI: YouTube said: Unable to extract video data
```

**Comment by falsechicken** [comment]
> I am getting the same error on Ubuntu 18.04.2 LTS, youtube-dl version 2019.10.16. Was this confirmed fixed? because it seems to be ongoing.

It WAS working again for me after the latest update on 18.04 (Have a NAS running it) but now it seems to also have the issue on 19.10. NewPipe on android has also stopped working so I assume YouTube changed something.

**Comment by falsechicken** [comment]
Strange... It is working for me in 18.04.... what? Updated commend above to reflect this.

**Comment by falsechicken** [comment]
@dstftw Can this be re-opened? Obviously something going on here.

**Comment by johnnygroovy** [comment]
I have this error with 2019.10.16 on my arch (in virtualbox.)
The curious thing is that the exact same version works on the Windows host.

**Comment by ferdous-al-quraeshi** [comment]
Having the same with my **Ubuntu 19.04**... really strange!
Anyone on rescue kana?

**Comment by TheBoroer** [comment]
I'm having the same issue with 2019.10.16 on a Ubuntu 16.04

**Comment by annahung31** [comment]
Same here with 2019.10.25...

**Comment by azmras** [comment]
Had the same problem on my openwrt router, was working fine on my computer, so No IP ban problem, curl, aria2c even netcat responded with 429, for me the problem solved when I upgraded to kernel 4.14.150 ... (both 4.14.148 and 4.14.149 had the same problem)

**Comment by falsechicken** [comment]
I am having the same issue again -_-. Ubuntu Mate 19.10

```
youtube-dl -v "https://www.youtube.com/watch?v=pdmODVYPDLA"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=pdmODVYPDLA']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.17rc1 (CPython) - Linux-5.3.0-19-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] pdmODVYPDLA: Downloading webpage
[youtube] pdmODVYPDLA: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: pdmODVYPDLA: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1836, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: pdmODVYPDLA: YouTube said: Unable to extract video data

```

**Comment by falsechicken** [comment]
But it IS working again on Ubuntu Server 18.04.... What is going on!?

```
youtube-dl -v "https://www.youtube.com/watch?v=pdmODVYPDLA"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=pdmODVYPDLA']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-65-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube] pdmODVYPDLA: Downloading webpage
[youtube] pdmODVYPDLA: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r2---sn-hp57kn6l.googlevideo.com/videoplayback?expire=1572987019&ei=K4zBXc7QMJLMj-8Po9G6qA8&ip=73.42.87.4&id=o-AJ5k1czGsyyVf__NSR9THHld5QM94-tmDDNANr-KKZR0&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-hp57kn6l%2Csn-5uaeznkl&ms=au%2Conr&mv=m&mvi=1&pl=19&initcwndbps=1951250&mime=video%2Fmp4&gir=yes&clen=261046965&dur=1373.955&lmt=1572467802406669&mt=1572965308&fvip=2&keepalive=yes&fexp=23842630&c=WEB&txp=4432432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRgIhAIDnls5B29xFJaI-3otDsAswh04F-Ig8k5YDstm0TJXFAiEAw3alySiu2inRYpZz137Ve0NErx7WuI8GFPFBK7NEHsM%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAPaTwulepw7oPwBi6cstZ6PsHZ0zM2lTa7ryB0vdtDK1AiEAuAVMkY7s0LPJV5RZ5przdEhSppvSb-Y5mWyf7Cp8Idw%3D&ratebypass=yes'
[download] Resuming download at byte 12189514
[download] Destination: I Built a COMPUTER in Magic - The Gathering-pdmODVYPDLA.f137.mp4
[download]   8.6% of 248.95MiB at 20.83MiB/s ETA 00:10^C
ERROR: Interrupted by user
```

**Comment by RenFinkle** [comment]
Was fine for a couple of days then it started happening again? I just updated to the latest version too.

**Comment by TheBoroer** [comment]
Can some of you guys try to run the command with the `--write-pages` argument and see what the resulting html page looks like? (e.g. do you get a captcha, see the regular video page, or other error pages, etc)

**Comment by falsechicken** [comment]
@TheBoroer I opened the dump file in Firefox. It looks like a captcha page.

**Comment by TheRockettek** [comment]
Can reproduce aswell with the same dump as false chicken
```[youtube] _Q_47b507vg: Downloading webpage
[youtube] _Q_47b507vg: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: _Q_47b507vg: YouTube said: Unable to extract video data```

**Comment by Alakhator** [comment]
I am getting the same issue on elementary os

**Comment by falsechicken** [comment]
@TheBoroer Hmm it also fails if I try logging in. I never do this so I figured it was worth a shot. But the result is the same. I get the same captcha page. 

```
 youtube-dl --verbose --netrc https://www.youtube.com/watch?v=rnX3JwNoNgA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--netrc', u'https://www.youtube.com/watch?v=rnX3JwNoNgA']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.17rc1 (CPython) - Linux-5.3.0-19-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to extract result entry
[youtube] B44oQ4lp7HY: Downloading webpage
[youtube] B44oQ4lp7HY: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: B44oQ4lp7HY: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1836, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: B44oQ4lp7HY: YouTube said: Unable to extract video data
```

**Comment by falsechicken** [comment]
@TheBoroer But I just tested using a VPN... It DOES work if I come from a different country...

**Comment by dcdebug** [comment]
@falsechicken   这个应该是ip的限制，你可以尝试更改ip试一下. 过一段时间后，报错的服务器 就又正常了。。。

**Comment by falsechicken** [comment]
@dcdebug Is right. It appears that YT is detecting that I am using some third party client. After days of not using YT-DL I just tried again and it works. It seems to be presenting the captcha to only YT-DL though. I can still browse with a web browser (without being logged in) just fine.

**Comment by gnouts** [comment]
Hi all, I noticed this issue too. Solving captcha doesn't work as it seems to only block youtube-dl.
I asked [there](https://github.com/ytdl-org/youtube-dl/issues/18859#issuecomment-545604712) if using invidious might be a good workaround, but for now youtube-dl still use youtube to get video even if url is invidious. Maybe my comment will get more visibility here :)

**Comment by RenFinkle** [comment]
I'm having to change my proxies every couple of days because Youtube seems to be detecting this faster and faster now and as a result YouTube-DL is running into the same issue (and utilizing a proxy seems to be the only way to work around this)

**Comment by Quintenvw** [comment]
Same issue here, can't get anything anymore after just 2 days of using youtube dl. If anyone knows a fix for this that would be amazing!

**Comment by helloworldkr** [comment]
@Quintenvw I am facing similar issues

**Comment by JohnDoe44526949** [comment]
Me too, on debian buster kernel 4.19.0-6-amd64, the temporary solution is to use a proxy then?

**Comment by Haetsal-Lee** [comment]
Why are we talking about kernels? I assume it have zero relation with system kernels and think the issue is related with something like useragent.

**Comment by JohnDoe44526949** [comment]
You're right.

**Comment by falsechicken** [comment]
> Why are we talking about kernels? I assume it have zero relation with system kernels and think the issue is related with something like useragent.

This was because initially the two installs I had running here at home where two different Ubuntu versions. It worked on one and not the other. This was before we discovered it was a YouTube blocking problem.

**Comment by JohnDoe44526949** [comment]
Hey, why changing the user agent doesn't work?

user@Deskt0p:~/Desktop/USL$ youtube-dl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36" https://www.youtube.com/channel/UCcdUt-ezblFANUS3PfNZiTQ/videos
[youtube:channel] UCcdUt-ezblFANUS3PfNZiTQ: Downloading channel page
[youtube:playlist] UUcdUt-ezblFANUS3PfNZiTQ: Downloading webpage
[download] Downloading playlist: Uploads from Un Señor de Logroño
[youtube:playlist] playlist Uploads from Un Señor de Logroño: Downloading 94 videos
[download] Downloading video 1 of 94
[youtube] B4FUktVJ4Aw: Downloading webpage
[youtube] B4FUktVJ4Aw: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: B4FUktVJ4Aw: YouTube said: Unable to extract video data

**Comment by falsechicken** [comment]
> Hey, why changing the user agent doesn't work?
> 
> user@Deskt0p:~/Desktop/USL$ youtube-dl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36" https://www.youtube.com/channel/UCcdUt-ezblFANUS3PfNZiTQ/videos
> [youtube:channel] UCcdUt-ezblFANUS3PfNZiTQ: Downloading channel page
> [youtube:playlist] UUcdUt-ezblFANUS3PfNZiTQ: Downloading webpage
> [download] Downloading playlist: Uploads from Un Señor de Logroño
> [youtube:playlist] playlist Uploads from Un Señor de Logroño: Downloading 94 videos
> [download] Downloading video 1 of 94
> [youtube] B4FUktVJ4Aw: Downloading webpage
> [youtube] B4FUktVJ4Aw: Downloading video info webpage
> WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
> WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
> WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
> WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
> ERROR: B4FUktVJ4Aw: YouTube said: Unable to extract video data

I feel like it's likely because YouTube is using some kind of machine learning or some other factor to determine what computer you are using. Like I mentioned before when we thought it was a kernel thing because it worked on a different computer in my house that happened to have a different Ubuntu version but not the primary one I use YTDL on. 

Waiting like a week seemed to solve it. So I think they are using something fancy and unknown to use to identity users who use YTDL a lot. My issue I think was that I downloaded the last 5 videos from over 100 channels in a multithreaded fashion (16 channels at a time...) every hour.... they did not like this bandwidth consumption I think. So now I just do it once a day and have not seen the problem since. Or use a VPN.

**Comment by santosadrian** [comment]
Yeah, they are beggining to putting restrictions on download. VPN solves it using diferent locations.

I'm curious how they determine that is YTDL or 4kvideodownloader (this also suffer from banning), they're not just banning the ip because youtube works in the browser.

**Comment by Draphar** [comment]
I was able to bypass this for at least one video by passing `--user-agent "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"`.

**Comment by thekryz** [comment]
> I was able to bypass this for at least one video by passing `--user-agent "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"`.

Didn't work for me :( Guess I'll have to wait for a while and try again.

**Comment by UMLAUTaxl** [comment]
Maybe it's time to put some download speed restrictions into youtube-dl?
