### ISSUE TITLE
Youtube has once again changed their VR180 content storage format

### ISSUE THREAD

**Issue by FlamelightX** [ytdl-org/youtube-dl#22640]
This time, you can only grab a single eye viewport of their videos, like before you can get up to 5760x2880 videos, but now you can only get 2880x2880 which is essentially just half of the video? It seems that only newly uploaded VR180 videos are impacted, like this one:
https://www.youtube.com/watch?v=gM17Hu6_hTc

**Comment by wasolk** [comment]
I tried the solution described here https://github.com/ytdl-org/youtube-dl/issues/15267, adding --user-agent '' parameter, but it doesn't seem to work anymore. Also I tried using multiple user-agents and that seems to influence the options but I can't get 5760x2880 videos nor stereoscopic values to show in the options. Also, I can't find the user-agent used by YoutubeVR that maybe works to get the stereoscopic videos... Maybe someone can help with this one. I tried to get the value with wireshark and a proxy that my Oculus is connected to, but data seems to be encrypted.
