### ISSUE TITLE
The diffrenece between the 'extractor' and 'extractor_key' template names

### ISSUE THREAD

**Issue by lkintact** [ytdl-org/youtube-dl#22643]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

Could anyone please explain what's the difference between the template names `extractor` ("Name of the extractor") and `extractor_key` ("Key name of the extractor")?
I tried fiddling with templates, and sometimes these are the same, sometimes they differ in casing, but I never managed to get the difference.

**Comment by dstftw** [comment]
`extractor_key` is an identifier, `extractor` is readable name if provided.

**Comment by lkintact** [comment]
@dstftw thanks for the explanation, Sergey M.
