### ISSUE TITLE
Very fast downloading for VOD, slow download for streams 

### ISSUE THREAD

**Issue by Samuel-Nathanson** [ytdl-org/youtube-dl#22645]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.09.28**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '95', '-g', '--hls-prefer-native', 'https://youtu.be/L4Cr_S_SXK4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.7.3 (CPython) - Linux-5.0.0-31-generic-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}

```

## Description

Livestream downloading is very very slow - 1.9 FPS . VOD downloading is still very fast 

`ffmpeg -i $(youtube-dl -f 95 -g --hls-prefer-native https://youtu.be/L4Cr_S_SXK4) -c:v h264_nvenc -strict experimental -t 00:02:00 -f mpegts udp://localhost:8888`

**Comment by dstftw** [comment]
Address this to ffmpeg support.

**Comment by Samuel-Nathanson** [comment]
> Address this to ffmpeg support.

I should have mentioned that this issue still persists without using FFMPEG
youtube-dl -v -f 95 https://youtu.be/L4Cr_S_SXK4 

VOD downloading is very fast.
