### ISSUE TITLE
Why is the speed of downloading not consistent?

### ISSUE THREAD

**Issue by gbraad** [ytdl-org/youtube-dl#22652]
When using a browser (or any HTTP) download or watching a video on youtube, I notice the download is very consistent... mostly peaking at the bandwidth. However, when I use `youtube-dl` to grab a video, it shows a very clear roof-tiling pattern; it goes up and when it reaches peak there is a sheer drop to almost zero... after which the speed starts to raise again and repeating this process.

```
> youtube-dl --version
2019.09.28
```

**Comment by gbraad** [comment]
Why close this without some possible explaination? What other information is needed to make an assesment?

**Comment by gbraad** [comment]
Not seeing this using using Aria2 (on Windows) as an external downloader:

```
PS> choco install aria2
PS> youtube-dl --external-downloader aria2c --external-downloader-args "-j 12 -s 12 -x 12 -k 5M" https://www.youtube.com/watch?v=7IvmzEuVkSY

**Comment by dstftw** [comment]
Bother to read new issue template and provide all requested info.
