### ISSUE TITLE
How to set output template "chapter_number" to display 2 or 3 digits

### ISSUE THREAD

**Issue by MGadAllah** [ytdl-org/youtube-dl#22653]
Hi,
Please under **output template** there is a template titled:
**chapter_number (numeric): Number of the chapter the video belongs to**
How to set this to display 2 or 3 or 4 digits instead of only one?
I mean like 01 or 001 or 0001

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#output-template

**Comment by MGadAllah** [comment]
> https://github.com/ytdl-org/youtube-dl#output-template

Thanks for fast reply.
It is not duplicated and I did searched a lot here and other places but nothing found to help me.
It is displaying a one digit by default but I want it to display 2 or 3 digits like what happened with playlist_index.
Like leading zeros according to the total length of the chapters.
Thanks

**Comment by dstftw** [comment]
Are you blind or what?
https://github.com/ytdl-org/youtube-dl/issues/17841
