### ISSUE TITLE
I'm reporting a broken site support for "Tele5" - [UPDATED] October 14th 2019

### ISSUE THREAD

**Issue by detailedreport** [ytdl-org/youtube-dl#22666]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

- [x] I'm reporting a broken site support

TELE5, featured in the supported sites, modified their distribution of content and added a layer of advertisment. ( This happend within the last 12 hours)

Trying to download any videos listed on their site produces  the followingerror post 

![tele5error -](https://user-images.githubusercontent.com/56372394/66529727-d0622400-eb04-11e9-8616-b6346ebf7aed.png)

[Nexx] 1633881: Downloading JSON metadata
[Nexx] 1633881: Downloading session/init JSON
[Nexx] 1633881: Downloading videos/byid/1633881 JSON
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\YoutubeDL.py", line 2010, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\YoutubeDL.py", line 807, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\YoutubeDL.py", line 868, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\extractor\nexx.py", line 367, in _real_extract
TypeError: list indices must be integers, not str
![tele5error -](https://user-images.githubusercontent.com/56372394/66529748-f12a7980-eb04-11e9-928d-abcefe6f9a1d.png)

**The Site has been updated again and their contentdistribution changed yet again for more details please see my latest comment.**

**Comment by LameLemon** [comment]
I know you mentioned all videos are like this, can you post a sample url?
Thanks : )

**Comment by detailedreport** [comment]
Of course, thank you for your speedy reply.

Any link available under https://www.tele5.de/serien/ is affected.

Sample url: https://www.tele5.de/pink-panther/ganze-folge/rosarote-winterfreuden-ameisenbaer-sucht-ameise-rosarotes-anglerlatein/

Please note that access most likely is region blocked and only available in Austria, Switzerland and Germany.

**Comment by LameLemon** [comment]
Oh I see, I won't be able to work on it unfortunately, because of them region restrictions.

**Comment by mlgha** [comment]
Hi, 
just testing from one of them regions and I can't reproduce:

```
# youtube-dl -gv https://www.tele5.de/pink-panther/ganze-folge/rosarote-winterfreuden-ameisenbaer-sucht-ameise-rosarotes-anglerlatein/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-gv', u'https://www.tele5.de/pink-panther/ganze-folge/rosarote-winterfreuden-ameisenbaer-sucht-ameise-rosarotes-anglerlatein/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.16 (CPython) - Linux-5.3.6-050306-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
http://tele5nexx.akamaized.net/90896992-3eb3-4ac7-9869-49d95487daa8/1631920_src.ism/QualityLevels(1486265)/Manifest(video,format=m3u8-aapl)
http://tele5nexx.akamaized.net/90896992-3eb3-4ac7-9869-49d95487daa8/1631920_src.ism/QualityLevels(127999)/Manifest(aac_UND_2_127,format=m3u8-aapl)
```
Or:

```
# youtube-dl -v https://www.tele5.de/pink-panther/ganze-folge/rosarote-winterfreuden-ameisenbaer-sucht-ameise-rosarotes-anglerlatein/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.tele5.de/pink-panther/ganze-folge/rosarote-winterfreuden-ameisenbaer-sucht-ameise-rosarotes-anglerlatein/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.16 (CPython) - Linux-5.3.6-050306-generic-x86_64-with-Ubuntu-19.04-disco
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[Tele5] rosarote-winterfreuden-ameisenbaer-sucht-ameise-rosarotes-anglerlatein: Downloading webpage
[Nexx] 1631920: Downloading JSON metadata
[Nexx] 1631920: Downloading m3u8 information
[Nexx] 1631920: Downloading MPD manifest
[Nexx] 1631920: Downloading ISM manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://tele5nexx.akamaized.net/90896992-3eb3-4ac7-9869-49d95487daa8/1631920_src.ism/QualityLevels(1486265)/Manifest(video,format=m3u8-aapl)'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 193
[download] Destination: Rosarote Winterfreuden _ Ameisenbär sucht Ameise _ Rosarotes Anglerlatein-1631920.fazure-hls-1666.mp4
[download]   1.6% of ~232.97MiB at  2.87MiB/s ETA 01:35^C
ERROR: Interrupted by user
```

Maybe the original poster could try again.
cheers

**Comment by gitty42** [comment]
I get the same error for the following URLs (Episodes 5,4,3 of "Enterprise"):
https://www.tele5.de/star-trek/enterprise/ganze-folge/freund-oder-feind/
https://www.tele5.de/star-trek/enterprise/ganze-folge/geistergeschichten/
https://www.tele5.de/star-trek/enterprise/ganze-folge/in-guter-hoffnung/

But NO error for the following URLs (Episodes 1 and 2 of "Enterprise")
https://www.tele5.de/star-trek/enterprise/ganze-folge/aufbruch-ins-unbekannte-teil-1/
https://www.tele5.de/star-trek/enterprise/ganze-folge/aufbruch-ins-unbekannte-teil-2/

And NO error for the sample URL from above:
https://www.tele5.de/pink-panther/ganze-folge/rosarote-winterfreuden-ameisenbaer-sucht-ameise-rosarotes-anglerlatein/

**Comment by detailedreport** [comment]
Thank you all for your time and effort.
It seems that tele5 yet again changed their content distribution, the error has changed to a http-403.
This includes both youtube-dl versions( latest and the on already including the changes made by FliegendeWurst).

**Comment by mountbatt** [comment]
TELE5 is not working anymore. Seems the changed something again. It outputs an 403 Forbidden Error. Any chance to fix this soon? There is "A Handmaids Tale" and the files are only online until this evening. ;-(

<img width="1137" alt="Screenshot 2019-10-21 08 41 29" src="https://user-images.githubusercontent.com/2411246/67182265-05148c00-f3df-11e9-96d0-42712b4248ba.png">

THANKS!

@FliegendeWurst

**Comment by Studentenfutter** [comment]
When trying to reproduce no Error 403 gets returned, however download is exeptionally slow ( > 38 hours for 560MB).

@mountbatt As a temporary workaround, use [this gist](https://gist.github.com/tzmartin/fb1f4a8e95ef5fb79596bd4719671b5d) with the URL that got printed just before the error you had, it worked for me.
