### ISSUE TITLE
Captcha on YouTube

### ISSUE THREAD

**Issue by titirino159** [ytdl-org/youtube-dl#22668]
## Checklist

- [* ] I'm reporting a feature request
- [ *] I've verified that I'm running youtube-dl version **2019.09.28**
- [ *] I've searched the bugtracker for similar feature requests including closed ones

## Description

Hello,

Since a few days, I can no longer download youtube videos with youtube-dl because a captcha is requested by the site. I tried to fill it with my web browser, it works, but in command line, always the same problem (however I have the same IP).

Do you have a solution, tutorial on how I could bypass the captcha without change ip or proxy? I am currently blocked.

I saw on another post that it was possible to do this with a cookie file, but there are no details and it dates back to several years ago...

Thank you. 

Curl: https://pastebin.com/Jj5xXSqd

```
</div><div id="content" class="  content-alignment" role="main"><p class='largeText'>Sorry for the interruption. We have been receiving a large volume of requests from your network.</p>
 
<p>To continue with your YouTube experience, please fill out the form below.</p>
<form action="/das_captcha" method="POST">
<div class="g-recaptcha" data-sitekey="6Lf39AMTAAAAALPbLZdcrWDa8Ygmgk_fmGmrlRog"></div>
<br/>
<input type="hidden" name="next" value="/watch?v=XTO4Q8bebJ4">
<input type="hidden" name="session_token" value="QUFFLUhqa0pSSElYd1RlNW9xSVViSF9mUWZ2cmFjU0dhd3xBQ3Jtc0tuczB5bEoxeEtxdkRSTmZZa2lYOGI4Vk1oOHNIYXJHQmhIdTVPdE9Zcm5zT3VNMWUxV1BuenhjYXd0R1p6X1RlamhEMXhvSWxWZ2p6bnF1c1VkUjdQZGpDYUhmb3hXdm5TZld5MThEYUVITGY1T1ZNc2NhTUVhdlVuX0lqVVY2NVM1dkhrZjZIQXJVN0VFeE5LQlAzMVJOWWFFWUE=">
<input type="hidden" name="action_recaptcha_verify2" value="1">
<input type="submit" value="Submit">
</form>
</body>
</html>
```

Log:

 youtube-dl https://www.youtube.com/watch?v=XTO4Q8bebJ4 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=XTO4Q8bebJ4', u'--verbose']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.11
[debug] exe versions: ffmpeg 4.1.2, ffprobe 4.1.2, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] XTO4Q8bebJ4: Downloading webpage
[youtube] XTO4Q8bebJ4: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: XTO4Q8bebJ4: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1836, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: XTO4Q8bebJ4: YouTube said: Unable to extract video data

**Comment by dstftw** [comment]
Pass cookies with solved captcha.

**Comment by titirino159** [comment]
> Pass cookies with solved captcha.

Hello, thank you for your message. Do you have any idea how to retrieve the cookie with the captcha? If the cookie is retrieved from another ip address, will it work? Because for downloading youtube video, I use ip addresses of different outgoing ip (basically to avoid this blockage).

Thank you
