### ISSUE TITLE
Is it possible to support multiple threads downloading videos from a long playlist

### ISSUE THREAD

**Issue by zhanglianbo35** [ytdl-org/youtube-dl#22670]
## Checklist

- [ ] I'm reporting a site feature request
- [ ] I've verified that I'm running youtube-dl version **2019.09.28**
- [ ] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

**Comment by detailedreport** [comment]
Yes you can download a specific range of videos from a playlist eg. 1st to nth & and (n+1)th to m.
These are the commands for Video Selection:

       --playlist-start NUMBER
              Playlist video to start at (default is 1)

       --playlist-end NUMBER
              Playlist video to end at (default is last)

       --playlist-items ITEM_SPEC
              Playlist video items to download.  Specify indices of the videos  in  the  playlist
              separated by commas like: "--playlist-items 1,2,5,8" if you want to download videos
              indexed 1, 2, 5, 8 in the  playlist.   You  can  specify  range:  "--playlist-items
              1-3,7,10-13", it will download the videos at index 1, 2, 3, 7, 10, 11, 12 and 13.
