### ISSUE TITLE
'write-auto-sub' original caption (untranslated)

### ISSUE THREAD

**Issue by andradadad** [ytdl-org/youtube-dl#22678]
## Checklist

- [X ] I'm asking a question
- [ X] I've looked through the README and FAQ for similar questions
- [X ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I've come to the write-auto-sub parameter to download the caption of a video, and not the enforced translation of the original caption. A way to do that on ytdl-raw-option was to reinsert ,sub-lang= as many times as possible, but it overwrites all the previous subtitles. How do I download the ORIGINAL caption, in any language as it was available, and how do I download multiple translations of the original without overwriting with the last specified sub-lang?
Trying to separate the language codes with "," isn't working.  

`--ytdl-raw-options=write-sub=,write-auto-sub=,sub-lang=en,sub-lang=es,sub-lang=fr`

**Comment by dstftw** [comment]
1. You can't.
2. , works fine with `--sub-lang`.

**Comment by andradadad** [comment]
In -raw-options "--" isn't available, although you haven't answered what's the parameter for separating language codes which was the question itself. Not the argument "-sub-lang" which I expressed in the OP, including its defect for multiple subtitles.

The question have been closed without a proper reading comprehension.
Such a waste of time having a forum if it gets answered like this.

**Comment by dstftw** [comment]
`--ytdl-raw-options` has nothing to do with youtube-dl. Address this to support of software you use.
Such a waste of time asking questions in unrelated forums.
