### ISSUE TITLE
v ueschool.io

### ISSUE THREAD

**Issue by gi313** [ytdl-org/youtube-dl#22692]
## Checklist

- [ x] I'm reporting a new site support request
- [x ] I've verified that I'm running youtube-dl version **2019.09.28**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that none of provided URLs violate any copyrights
- [ x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://vueschool.io/lessons/how-to-lazy-load-routes-with-vue-router
- Playlist: https://vueschool.io/courses/vue-router-for-everyone

## Description

WRITE DESCRIPTION HERE

**Comment by gi313** [comment]
$ ./youtube-dl -o "./%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" --sleep-interval 222 --all-subs --cookies cookies.txt "https://vueschool.io/courses/vuex-for-everyone"
[generic] vuex-for-everyone: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vuex-for-everyone: Downloading webpage
[generic] vuex-for-everyone: Extracting information
ERROR: Unsupported URL: https://vueschool.io/courses/vuex-for-everyone

**Comment by dstftw** [comment]
You must provide credentials for any works on this.

**Comment by gi313** [comment]
hi Sergey,Here is my login: lars.devocht@gmail.com with 1Dr67W#cwkr,Lars.    On Saturday, October 12, 2019, 11:57:33 PM GMT+2, Sergey M. <notifications@github.com> wrote:  
 
 
You must provide credentials for any works on this.

**Comment by gi313** [comment]
can i send it by e-mail ?
