### ISSUE TITLE
stop replacing colon ':' with space+-

### ISSUE THREAD

**Issue by AlBannaTechno** [ytdl-org/youtube-dl#22696]
**Hi**
I notice when i download videos contains colon `:` youtube-dl auto replace it with ` -` = space + - 
i need to only replace : with - as stander not space + - 

**Why**
For Example When i download this play list  `https://www.youtube.com/watch?v=tpIctyqH29Q&list=PL8dPuuaLjXtNlUrzyH5r6jN9ulIgZBpdo`

Notice most of videos contains `:` so when i download this playlist from any site or software which use stander replacement of `:` with `-` 

i get name as `02.Early Computing- Crash Course Computer Science #1.mp4`

but when i try to get subtitles i get `02.Early Computing - Crash Course Computer Science #1.en.vtt`

Now Subtitle Does Not match video name so no-media will auto-attach it

i use ` youtube-dl.exe --write-sub --skip-download --yes-playlist --sub-lang="en,ar" -o %(autonumber)02d.%(title)s.%(ext)s https://www.youtube.com/playlist?list=PL8dPuuaLjXtNlUrzyH5r6jN9ulIgZBpdo
`
**So How To Do that and why this strange behavior**

**Comment by dstftw** [comment]
Windows does not support `:` in filenames.

**Comment by AlBannaTechno** [comment]
@dstftw i know that it's not my question i ask why the strange behavior of replacing colon with two characters `space + dash` all download-sites and even Internet Download Manager (IDM) only replace colon with one character which dash

**Comment by dstftw** [comment]
Cause this it's the only way to get idiomatic and file safe form of `Section: Subsection` as `Section - Subsection`.
