### ISSUE TITLE
How To Get Section Name In Template Name

### ISSUE THREAD

**Issue by AlBannaTechno** [ytdl-org/youtube-dl#22697]
**Hi**

i try download this series : [Film Production](https://www.youtube.com/playlist?list=PL8dPuuaLjXtPnisE6CrrLO00Qoe67TDpx)

But i can't figure how to get section name in video name template

section name like `Writing and Story` , `Camera and Sound` ... i try many things described in readme file but nothing work

**Comment by AlBannaTechno** [comment]
@dstftw I guess you closed this question because of not providing version so i provide it
So is this feature available in `/youtube-dl`

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient

**Comment by AlBannaTechno** [comment]
@dstftw I re populate the question with most required details

**Comment by dstftw** [comment]
No such info is provided by Youtube.

**Comment by AlBannaTechno** [comment]
@dstftw Thanks for reply , 
I just have a final/last question i explore the source code and i notice using html parsing operations 
so it make this problem not related to youtube it's not youtube API ? am i true ?
it's rely under `id="title-container"` in `div` so implement this not related to youtube itself ! that true or i miss-understand how ydl work

**Comment by dstftw** [comment]
youtube-dl does not use Youtube API due to obvious reasons.

**Comment by AlBannaTechno** [comment]
@dstftw  So What do you mean by saying `No such info is provided by Youtube.` ????? we pars the page then get what we want !!

**Comment by dstftw** [comment]
I mean exactly what it spells. I'm not a black magician to know what you parse.

**Comment by AlBannaTechno** [comment]
@dstftw  thanks , I am still can't understand what you mean and why this is not possible but i know this problem happend because of shortage of my knowledge so i will study the source code in the next first chance . thanks
