### ISSUE TITLE
Site-support request for https://iview.abc.net.au/[video_file]

### ISSUE THREAD

**Issue by Hermitic** [ytdl-org/youtube-dl#22703]
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.09.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URL

https://iview.abc.net.au/show/total-control

Youtube-dl report:

~$ youtube-dl --verbose https://iview.abc.net.au/show/total-control
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://iview.abc.net.au/show/total-control']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-64-generic-x86_64-with-LinuxMint-19.2-tina
[debug] exe versions: none
[debug] Proxy map: {}
[generic] total-control: Requesting header
WARNING: Falling back on generic information extractor.
[generic] total-control: Downloading webpage
[generic] total-control: Extracting information
ERROR: Unsupported URL: https://iview.abc.net.au/show/total-control
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2373, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 6, column 635
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3355, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://iview.abc.net.au/show/total-control

**Comment by Vittelius** [comment]
Iview is already supported. You have to get the video link from the share menu.
So in your example it would be https://iview.abc.net.au/show/total-control/series/1/video/IP1807H001S00 rather than https://iview.abc.net.au/show/total-control

**Comment by Hermitic** [comment]
> Iview is already supported. You have to get the video link from the share menu.
> So in your example it would be https://iview.abc.net.au/show/total-control/series/1/video/IP1807H001S00 rather than https://iview.abc.net.au/show/total-control

Thanks for that. I got some error messages which mystify me because the captured file plays well.

> ~$ youtube-dl https://iview.abc.net.au/show/total-control/series/1/video/IP1807H001S00
[abc.net.au:iview] IP1807H001S00: Downloading JSON metadata
[abc.net.au:iview] IP1807H001S00: Downloading webpage
[abc.net.au:iview] IP1807H001S00: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 301
[download] Destination: Series 1 Ep 1-IP1807H001S00.mp4
[download] 100% of 409.35MiB in 05:26
WARNING: IP1807H001S00: malformed AAC bitstream detected. Install ffmpeg or avconv to fix this automatically.

I have no idea what the total fragments are about, what "malformed AAC bitstream detected" means, and ffmpeg is installed on my computer, but as the video plays well, I am curious, but not particularly bothered.

**Comment by Hermitic** [comment]
All done. issue solved. Thanks, Vittelius. :)
