### ISSUE TITLE
[YouTube] How does best format selection work; how are the stream properties (like ABR) determined?

### ISSUE THREAD

**Issue by RevSnowfox** [ytdl-org/youtube-dl#22709]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi! I would like to ask for elaboration from the main developers on two technical questions;

1) How does the `best` and `bestvideo`/`bestaudio` format options work? What technical parameters youtube-dl considers when selecting the best formats, especially with YouTube?

2) Considering formats and their properties listed on YouTube, what sources/methods youtube-dl uses to enumerate stream properties? I'm aware of the hardcoded stream descriptions in the YouTube extractor code, but how were those values determined in the first place? For example, youtube-dl lists ABR (average bitrate) values for each video/audio stream format (which is not necessarily indicative of the subjective perceptive quality of a stream), but ultimately what is the source of those ABR values?

Thank you for any answers in advance!

**Comment by RevSnowfox** [comment]
Duplicate of what exactly? There is literally no issue or question ticket that details the technicalities of format selection in youtube-dl, aside from vague mentions about youtube-dl "preferring higher bitrates".

Bitrates from what source? How it is determined? What is the source of the hardcoded ABR values in the YouTube extractor code?

**Comment by Hrxn** [comment]
All values as provided by YouTube.

**Comment by RevSnowfox** [comment]
If the ABR values are provided at the time of scraping a given YouTube page, why are they in the extractor code? Or does this mean those ABR values were obtained previously in another way from YouTube? (Because if so, other tools might access those values if they are changed on YouTube's end. Obviously ABR values are just guidelines for the transcoding processes YouTube does in the back-end, but still.)
