### ISSUE TITLE
Youtube Error 429

### ISSUE THREAD

**Issue by devmane144** [ytdl-org/youtube-dl#22726]
## Checklist

- [ X ] I'm reporting a broken site support
- [ X ] I've verified that I'm running youtube-dl version **2019.10.16**
- [ X  ] I've checked that all provided URLs are alive and playable in a browser
- [ X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
 youtube-dl -4 -v https://www.youtube.com/watch?v=i                                                                                                                                                             o7epibtCVs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-4', u'-v', u'https://www.youtube.com/watch?v=io7e                                                                                                                                                             pibtCVs']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.16
[debug] Python version 2.7.15+ (CPython) - Linux-5.0.0-31-generic-x86_64-with-Ub                                                                                                                                                             untu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube] io7epibtCVs: Downloading webpage
[youtube] io7epibtCVs: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request                                                                                                                                                             s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request                                                                                                                                                             s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request                                                                                                                                                             s
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Request                                                                                                                                                             s
ERROR: io7epibtCVs: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract                                                                                                                                                             _info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in                                                                                                                                                              extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1836, i                                                                                                                                                             n _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: io7epibtCVs: YouTube said: Unable to extract video data

## Description

Experiencing error 429 specifically from youtube-dl. This PC allows the user to watch videos when not running them through the program.

**Comment by Zuccace** [comment]
@dstftw Could you please give us the first issue this is a dublicate of?
I'd like to follow this bug.
