### ISSUE TITLE
Youtube video filename is incorrect when its title contains certain characters

### ISSUE THREAD

**Issue by forever8938** [ytdl-org/youtube-dl#22731]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.10.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
root@localhost:~# youtube-dl -j --flat-playlist GbO82vfU4R4  | jq -r '.title'
BEST KOREAN BBQ & Ox Bone Soup in Los Angeles | Japanese CLOUD Pancakes
root@localhost:~# 
root@localhost:~# youtube-dl -i -o '%(title)s' GbO82vfU4R4 --get-filename -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-i', u'-o', u'%(title)s', u'GbO82vfU4R4', u'--get-filename', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2019.10.16
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-55-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
BEST KOREAN BBQ & Ox Bone Soup in Los Angeles _ Japanese CLOUD Pancakes
root@localhost:~#
```

## Description

Youtube video filename is incorrect when its title contains certain characters, such as '|'.
As you can see in the log above, the video title is clearly "BEST KOREAN BBQ & Ox Bone Soup in Los Angeles | Japanese CLOUD Pancakes", which contains a '|'.
But when I specified the output template as  '%(title)s' and supposed it to be the same as the title, I got "BEST KOREAN BBQ & Ox Bone Soup in Los Angeles _ Japanese CLOUD Pancakes", where '|' becomes '_'.

I have checked that there is a field in the json called "_filename" that is exactly "BEST KOREAN BBQ & Ox Bone Soup in Los Angeles _ Japanese CLOUD Pancakes". 
```
root@localhost:~# youtube-dl -j --flat-playlist GbO82vfU4R4  | jq -r '._filename'
BEST KOREAN BBQ & Ox Bone Soup in Los Angeles _ Japanese CLOUD Pancakes-GbO82vfU4R4.webm
```
Is it possible to set the filename to title correctly?

**Comment by dstftw** [comment]
Filenames are sanitized. If you wan't a title then you must request a title not a filename.

**Comment by forever8938** [comment]
> not a filename.

The filename is actually wrong.
`root@localhost:~# youtube-dl -i -o '%(title)s' GbO82vfU4R4 
[youtube] GbO82vfU4R4: Downloading webpage
[youtube] GbO82vfU4R4: Downloading video info webpage
[download] Destination: BEST KOREAN BBQ & Ox Bone Soup in Los Angeles _ Japanese CLOUD Pancakes.f313
[download]   3.1% of 1.68GiB at 53.01MiB/s ETA 00:31^C
`

**Comment by dstftw** [comment]
Again: filenames are sanitized.
