### ISSUE TITLE
Add "description" (i.e. from YouTube) as format_id identifier for output format

### ISSUE THREAD

**Issue by Gorrrg** [ytdl-org/youtube-dl#22739]
## Checklist
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.10.16**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

When using the --get-description command line, yt-dl saves it into a file with the description file extension. Using this extension is hard coded.

But it would be handy to have the description file register "description" as a format_id identifier when it's this file's turn to be saved to the file system. So that using something like **-o "%(title)s.%(format_id)s"** in combination with **--get-description** will not result in **"Funny video.313.description"** but in the much more usable **"Funny video.description"**.

Because right now, when downloading multiple formats in seperate files and using format_id as an extension, the description file will have the format id of the first audio or video file in the format list in its file name. And that can mess up things when post-processing the files with a batch/script, ie. relying on the basename to match and copy files, since the description file has a different basename than the rest of the downloaded files. Even the thumbnail will honor format_id, it won't use the format id of the first video/audio file in its name but use the actual format of the thumbnail for that, like JPG for instance.

**Comment by dstftw** [comment]
With `--get-description` nothing is save on the disk in the first place.

**Comment by Gorrrg** [comment]
duh. I meant --write-description ofc
