### ISSUE TITLE
HTTP JSON Error Failing to download mediasite video

### ISSUE THREAD

**Issue by snicklefrittz** [ytdl-org/youtube-dl#22741]
I'm having an error when trying to donwload a video from mediasite. youtube-dl is up to date, and this is what I keep getting:

C:\Users\x >youtube-dl https://mediasite.osu.edu/Mediasite/Play/e118123c0850480281bd99dba41fc1681d?catalog=f3e73093abc946978b533761e3b1fdae21&playFrom=5960&autoStart=true --verbose
[Mediasite] e118123c0850480281bd99dba41fc1681d: Downloading webpage
[Mediasite] e118123c0850480281bd99dba41fc1681d: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
'playFrom' is not recognized as an internal or external command,
operable program or batch file.
'autoStart' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dstftw** [comment]
Pass authenticated cookies.
