### ISSUE TITLE
Upload youtube-dl transcript into Google Cloud storage

### ISSUE THREAD

**Issue by nicolasmorinpomerleau** [ytdl-org/youtube-dl#22740]
I am using Youtube-dl to download transcript, it works fine on my machine (local server) where I provide the __Dirname into the Options params to upload files. But I want to use Google Cloud functions, so how can I substitute __dirname with Cloud storage ?? Thank you !!

**Comment by nicolasmorinpomerleau** [comment]
Sorry, here is my question:
I am using Youtube-dl to download transcript, it works fine on my machine (local server) where I provide the __Dirname into the Options params to upload files. But I want to use Google Cloud functions, so how can I substitute __dirname with Cloud storage ?? Thank you !!

**Comment by dstftw** [comment]
You can't.

**Comment by nicolasmorinpomerleau** [comment]
Can I replace __dirnam by an array then ?
