### ISSUE TITLE
Why Are Certain Facebook Downloads So Slow?

### ISSUE THREAD

**Issue by goldensun87** [ytdl-org/youtube-dl#22743]
Here is an example link.

https://www.facebook.com/thebirchshow/videos/2396609953999642/

The "dash_hd_src" option is 720p only, so I have to download the audio and 1080p stream separately.  The audio downloads at my full speed just fine, but the 1080p video stream is currently downloading at only 37KB/s .  I'm not sure if this is a youtube-dl problem, or a Facebook problem.

**Comment by paco15241** [comment]
you can try with "axel" 
> https://github.com/axel-download-accelerator/axel
> https://github.com/Rergis/axel-for-windows

after the installation of axel, run youtube-dl command with `--external-downloader axel` 

```
youtube-dl --external-downloader axel -f 407872029925585v https://www.facebook.com/thebirchshow/videos/2396609953999642/
```
