### ISSUE TITLE
Too many requests error

### ISSUE THREAD

**Issue by phillipkalinda** [ytdl-org/youtube-dl#22760]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

In your documentation, it says we should contact the youtube-dl service incase we experience a 429 error: Too many requests. I was testing a raspberry pi video signage solution, and it just stopped working after a while.

**Comment by remitamine** [comment]
> it says we should contact the youtube-dl service

no, it doesn't, the service mentioned in the FAQ is the website you're trying to download from(most likely its youtube.com)
