### ISSUE TITLE
Force IPv4 via the Python API

### ISSUE THREAD

**Issue by orion40** [ytdl-org/youtube-dl#22765]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.02
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-5-amd64-x86_64-with-debian-10.1
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1
[debug] Proxy map: {}

I am trying to use the youtube-dl python API. However according to the options listed [here](https://github.com/ytdl-org/youtube-dl/blob/3e4cedf9e8cd3157df2457df7274d0c842421945/youtube_dl/YoutubeDL.py#L137-L312), it is not possible to do so programmatically. A quick glance at the source code didn't help find such option.

There is however the option `--force-ipv4` available with the program itself. It should be possible to also do so with python, maybe like this:

`yt_dl_opts = {                     
        'format': 'bestaudio/best'
        'forceip':'4'
        }                          
`

And so this would work as if the option `-4` was supplied to youtube-dl. Of course it should also be possible to select IPv6 too.

If the option is indeed available with the API, then it should be listed in the documentation.

Thanks you for your time.

**Comment by dstftw** [comment]
>should be listed in the documentation

Have you even read it?
https://github.com/ytdl-org/youtube-dl/blob/824fa51165d92ceee01589bf995ebbf009df328c/youtube_dl/YoutubeDL.py#L264

**Comment by orion40** [comment]
Okay, but what is the value to set to the parameter, to force youtube-dl to use IPv4 for the download ? Using "4" output the following error:

> argument of type 'int' is not iterable

**Comment by dstftw** [comment]
Do you manage reading English at all?

>Client-side **IP address** to bind to. 
>**IP address**

**Comment by orion40** [comment]
How is it relevant to forcing youtube-dl to download only via IPv4 ? What IP am I even supposed to give for that purpose ? Maybe how I worded my message was offensive, but it is not clear at all when reading that this parameter allow any kind of control over which version of IP is used for the download.

It also doesn't work, as youtube-dl still hang, waiting for an IPv6 connection it will never get.

**Comment by noahbroyles** [comment]
@orion40 Thank you!
