### ISSUE TITLE
PornHub "Unable to extract encoded url"

### ISSUE THREAD

**Issue by mariosemes** [ytdl-org/youtube-dl#22779]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.10.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose https://www.pornhub.com/model/misslexa
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.pornhub.com/model/misslexa']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.10.16
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[PornHubPagedVideoList] model/misslexa/videos: Downloading page 1
[PornHubPagedVideoList] model/misslexa/videos: Downloading page 2
[download] Downloading playlist: model/misslexa/videos
[PornHubPagedVideoList] playlist model/misslexa/videos: Collected 80 video ids (downloading 80 of them)
[download] Downloading video 1 of 80
[PornHub] ph5da9fd6f2f0b2: Downloading pc webpage
[PornHub] ph5da9fd6f2f0b2: Downloading tv webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\sema\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\sema\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\sema\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\pornhub.py", line 235, in _real_extract
    'encoded url').split(';')
  File "c:\users\sema\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Probably something went wrong with the latest commit for the pornhub extractor :-/

**Comment by dstftw** [comment]
Paid video.

**Comment by mariosemes** [comment]
I am sorry to open it up again, but it does the error for all the videos. If the model/pornstar or whoever has 100 videos, 10 of them are PAID, it says for all of the 100 that he URL cant be encoded :-/

**Comment by mariosemes** [comment]
`youtube-dl --verbose https://www.pornhub.com/model/misslexa/videos/upload
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.pornhub.com/model/misslexa/videos/upload']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.10.16
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[PornHubUserVideosUpload] misslexa: Downloading page 1
[PornHubUserVideosUpload] misslexa: Downloading page 2
[download] Downloading playlist: misslexa
[PornHubUserVideosUpload] playlist misslexa: Collected 63 video ids (downloading 63 of them)
[download] Downloading video 1 of 63
[PornHub] ph5dab43f7c594f: Downloading pc webpage
[PornHub] ph5dab43f7c594f: Downloading tv webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\sema\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\sema\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\sema\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\pornhub.py", line 235, in _real_extract
    'encoded url').split(';')
  File "c:\users\sema\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

The given URL does not conaint the PAID videos on its page and it still gets the error :-/

**Comment by hemlok89** [comment]
Same issue here. Even for testing, I uploaded a generic video & tried to download it. Same "Unable to extract encoded url" error shows up.

**Comment by dirkf** [comment]
The HLS playlist URL is now stored in a JS variable called something like media_8. The number part may vary according to the resolutions available. In the example I checked, there were also media_0 .. media_7 so 8 was the highest: maybe this will always be true.

The URL is something like 
https://ev-h.phncdn.com/hls/videos/yyyymm/nn/num/,1080P_4000K,720P_1500K,480P_600K,240P_400K,_num.mp4.urlset/master.m3u8?validfrom=t1&validto=t2&hdl=-1&hash=hash

**Comment by dirkf** [comment]
The HLS playlist URL is now stored in a JS variable called something like media_8. The number part may vary according to the resolutions available. In the example I checked, there were also media_0 .. media_7 so 8 was the highest: maybe this will always be true.

The URL is something like
https://ev-h.phncdn.com/hls/videos/yyyymm/nn/num/,1080P_4000K,720P_1500K,480P_600K,240P_400K,_num.mp4.urlset/master.m3u8?validfrom=t1&validto=t2&hdl=-1&hash=hash where num is the data-video-id attribute of the #player element.

**Comment by dirkf** [comment]
Also, URLs of playable mp4 files have been found in variables named quality_resolution, eg quality_480p. One might check for "quality"+res being defined for each res in [ 240p, 480p, 720p, 1080p, ...].
