### ISSUE TITLE
Python not found -> fix

### ISSUE THREAD

**Issue by Its-treason** [ytdl-org/youtube-dl#22776]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.10.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Description

Hello after upgrading to Ubuntu 19.10 I encountered an issue where Python can not be executed
I got the following error: `/usr/bin/env: »python“: file or directory not found`. That's probably because there is no binary called Python only 'python3' or 'python3.7' or something like this.
This issue can be fixed by making a link from one of the existing binaries (for example 'pyhton3') to Python by executing the following command: `sudo ln /usr/bin/python3.7 /usr/bin/python`. I think this should be mentioned in the FAQ.

**Comment by dstftw** [comment]
Messing up your environment has nothing to do with youtube-dl.
