### ISSUE TITLE
new to this

### ISSUE THREAD

**Issue by shiwei87tan** [ytdl-org/youtube-dl#22784]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

I'm new to python and this youtube-dl, I'm able to use download-dl to download video only from vlive successfully, but how do i download the .srt subtitle files from vlive?
how do I include the login detail if i'm downloading from vlive+ (video that requires subscription and payment)

and when i try downloading youtube video i keep receiving warning saying too many request and error unable to extract video data(Capture2)
![Capture2](https://user-images.githubusercontent.com/56813362/67178132-36538300-f404-11e9-8830-a4270e3586c1.JPG)

lastly how do i download video and subtitle from vod.melon.com/video? when i try i receive error as shown in attached screenshot (Capture1) while on youtube-dl site it says MelonVOD is supported.
![Capture1](https://user-images.githubusercontent.com/56813362/67178133-36538300-f404-11e9-8fea-d8718a837dc1.JPG)

please help and teach me. thank you.

**Comment by remitamine** [comment]
[Does the issue involve one problem, and one problem only?](https://github.com/ytdl-org/youtube-dl#does-the-issue-involve-one-problem-and-one-problem-only)

**Comment by shiwei87tan** [comment]
What do you mean?
