### ISSUE TITLE
request help

### ISSUE THREAD

**Issue by shiwei87tan** [ytdl-org/youtube-dl#22788]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

can someone teach me how to download video from vod.melon.com please? it keeps showing the below error although I have downloaded ffmpeg. and I don't understand what it means by ['menuId' is not recognized as an internal or external command, operable program or batch file.] and how to resolve it.
![Capture](https://user-images.githubusercontent.com/56813362/67212194-8f480900-f44e-11e9-9756-fc7409d30617.JPG)

**Comment by remitamine** [comment]
- read the error message:
> m3u8 download detected but ffmpeg or avconv could not be found. Please install one.
- next time do not post a screenshot, copy and paste the command output.
- quote URLs when it's needed(read https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).

**Comment by remitamine** [comment]
add `FFmpeg` directory to Windows `PATH`, or place the `FFmpeg` and `ffprobe` executable in the same folder with `youtube-dl.exe`.
