### ISSUE TITLE
[NHK vod]No video formats found, recurrence

### ISSUE THREAD

**Issue by kitarrt1** [ytdl-org/youtube-dl#22799]
## Checklist
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.10.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log:
C:\Documents and Settings\Administrator>
youtube-dl -F https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2007390/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www3.nhk.or.jp/nhkworld/en/ondemand/v
ideo/2007390/', '--verbose']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_V
ERIFY_FAILED] certificate verify failed (_ssl.c:600)>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy
0p\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy
0p\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy
0p\build\youtube_dl\extractor\piksel.py", line 121, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy
0p\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.

## PASTE VERBOSE LOG HERE
[NhkVod] 2007-390: Downloading JSON metadata
[Piksel] sw: Downloading webpage
[Piksel] tb8rf1uc: Downloading JSON metadata
[Piksel] tb8rf1uc: Downloading m3u8 information

## Description
For the following OK-site, new ver(*) youtube-dl.exe issues "ERROR: No video formats found".

OK-site: youtube-dl ver 2019.9.12.1 or previous ones, can handle normally this site, even now.
https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2007390/

(*)new ver: newest(2019.10.22.0), including and later than 2019.10.16.0

**Comment by remitamine** [comment]
```
youtube-dl https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2007390/
[NhkVod] 2007-390: Downloading JSON metadata
[Piksel] sw: Downloading webpage
[Piksel] tb8rf1uc: Downloading JSON metadata
[Piksel] tb8rf1uc: Downloading m3u8 information
[download] Destination: Journeys in Japan - Sawara - Festival Floats Keeping Ties Alive-tb8rf1uc.mp4
ffmpeg version n4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[hls @ 0x55ed9eece340] Skip ('#EXT-X-VERSION:3')
[hls @ 0x55ed9eece340] Opening 'https://nhkw-mzvod.akamaized.net/www60/mz-nhk10/definst/mp4:mm/flvmedia/5905/o/8/2/o8240d5t_ow7oky45_h264_1244K.mp4/media_0.ts' for reading
[hls @ 0x55ed9eece340] Opening 'https://nhkw-mzvod.akamaized.net/www60/mz-nhk10/definst/mp4:mm/flvmedia/5905/o/8/2/o8240d5t_ow7oky45_h264_1244K.mp4/media_1.ts' for reading
Input #0, hls, from 'https://nhkw-mzvod.akamaized.net/www60/mz-nhk10/definst/mp4:mm/flvmedia/5905/o/8/2/o8240d5t_ow7oky45_h264_1244K.mp4/chunklist.m3u8':
  Duration: 00:27:59.11, start: 0.000000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 60 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Journeys in Japan - Sawara - Festival Floats Keeping Ties Alive-tb8rf1uc.mp4.part':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:2 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  101 fps=0.0 q=-1.0 size=     512kB time=00:00:03.33 bitrate=1258.4kbits
```
