### ISSUE TITLE
youtube_dl.utils.ExtractorError: Unable to extract uploader name

### ISSUE THREAD

**Issue by holmesrichards** [ytdl-org/youtube-dl#22808]
$ youtube-dl --verbose https://www.youtube.com/watch?v=Qi7qqDJ2TOM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=Qi7qqDJ2TOM']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.8 (CPython) - Linux-4.15.0-60-generic-x86_64-with-LinuxMint-19.2-tina
[debug] exe versions: ffmpeg 3.4.6-0ubuntu0.18.04.1, ffprobe 3.4.6-0ubuntu0.18.04.1
[debug] Proxy map: {}
[youtube] Qi7qqDJ2TOM: Downloading webpage
[youtube] Qi7qqDJ2TOM: Downloading video info webpage
WARNING: Unable to extract video title
[youtube] Qi7qqDJ2TOM: Extracting video information
ERROR: Unable to extract uploader name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1704, in _real_extract
    raise ExtractorError('Unable to extract uploader name')
youtube_dl.utils.ExtractorError: Unable to extract uploader name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by sapolion** [comment]
This was helpful to me in that I had apparently downloaded two versions and the outdated one was first in my path, somehow. So I explicitly called it from /usr/local/bin and everything worked. I would not have figured it out reading this and seeing the similarity. I believe I installed using apt in the first try and then just downloaded it directly from here to get the one that worked. I have no idea where apt was getting it from (yes I could look and figure it out). I just want to let you know that this was helpful as it explained 1. the error "Unable to extract uploader name" was from an outdated version. 2. don't use apt or you will get that outdated version.
