### ISSUE TITLE
Request to add format codes to download-archive list

### ISSUE THREAD

**Issue by michealespinola** [ytdl-org/youtube-dl#22814]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.10.22**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

This is a request to add additional fields to the download-archive file to identify the specific streams downloaded.  This would allow users to more easily download different quality streams while still not downloading true duplicates.  

Thank you for your consideration and continued great work on this project!

**Comment by MPeti1** [comment]
I just wanted to post the same, but now I see it's already there. I think you could (should?*) reference the original request if it's a duplicate.

*in other projects they do that, but it's on you. I understand that it might be hard due to the large amount of issue postings.
