### ISSUE TITLE
[vier.be] Unable to extract filename

### ISSUE THREAD

**Issue by cpeetersburg** [ytdl-org/youtube-dl#22815]
When trying to download a video from vier.be, youtube-dl returns an error "Unable to extract filename"

Check that youtube-dl is up-to-date
```$ youtube-dl -U
youtube-dl is up-to-date (2019.10.22)
```

Verbose output
```$ youtube-dl https://www.vier.be/video/callboys/callboys-s2/callboys-s2-wat-van-mij-is-is-van-wij --verbose
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.vier.be/video/callboys/callboys-s2/callboys-s2-wat-van-mij-is-is-van-wij', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.22
[debug] Python version 2.7.15 (CPython) - Linux-5.0.16-100.fc28.x86_64-x86_64-with-fedora-28-Twenty_Eight
[debug] exe versions: ffmpeg 4.0.4, ffprobe 4.0.4
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[vier] callboys-s2-wat-van-mij-is-is-van-wij: Downloading webpage
ERROR: Unable to extract filename; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vier.py", line 170, in _real_extract
    webpage, 'filename')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract filename; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Example links:
- https://www.vier.be/video/callboys/callboys-s2/callboys-s2-wat-van-mij-is-is-van-wij
- https://www.vier.be/video/de-slimste-mens-ter-wereld/de-slimste-mens-ter-wereld-s17/de-slimste-mens-ter-wereld-s17-aflevering-1
- https://www.vier.be/video/trafiek-axel/trafiek-axel-seizoen-1/trafiek-axel-s1-axel-koopt-een-identiteit

Dump file from `--write-pages`: [log.zip](https://github.com/ytdl-org/youtube-dl/files/3763010/log.zip)

**Comment by cpeetersburg** [comment]
Sorry I was using the wrong links.

**Comment by karatetra** [comment]
Hi,
Today I had the same problem.
It seems that downloading from vier.be doesn't work anymore.
The ERROR message I got:

C:\Users\Admin\Downloads\youtube-dl>youtube-dl -U
youtube-dl is up-to-date (2020.01.01)

C:\Users\Admin\Downloads\youtube-dl>youtube-dl https://www.vier.be/video/auwch/auwch-seizoen-1/auwch-s1-aflevering-1
[vier] auwch-s1-aflevering-1: Downloading webpage
ERROR: Unable to extract filename; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\Admin\Downloads\youtube-dl>
