### ISSUE TITLE
Tele 5 changed again...

### ISSUE THREAD

**Issue by Knut-HH** [ytdl-org/youtube-dl#22810]
Video plays in browser, but with youtube-dl:
`youtube-dl https://www.tele5.de/filme/stonehearst-asylum-diese-mauern-wirst-du-nie-verlassen/
[Tele5] stonehearst-asylum-diese-mauern-wirst-du-nie-verlassen: Downloading webpage
[Nexx] 1634802: Downloading JSON metadata
[Nexx] 1634802: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 500: Internal Server Error
[Nexx] 1634802: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 500: Internal Server Error
[Nexx] 1634802: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 500: Internal Server Error
ERROR: unable to download video data: HTTP Error 403: Forbidden`

**Comment by Knut-HH** [comment]
With debug info:
`` youtube-dl -v -4 --hls-prefer-native https://www.tele5.de/filme/stonehearst-asylum-diese-mauern-wirst-du-nie-verlassen/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-4', u'--hls-prefer-native', u'https://www.tele5.de/filme/stonehearst-asylum-diese-mauern-wirst-du-nie-verlassen/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.22
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-65-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[Tele5] stonehearst-asylum-diese-mauern-wirst-du-nie-verlassen: Downloading webpage
[Nexx] 1634802: Downloading JSON metadata
[Nexx] 1634802: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 500: Internal Server Error
[Nexx] 1634802: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 500: Internal Server Error
[Nexx] 1634802: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 500: Internal Server Error
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://tele5nexx.akamaized.net/d3fffdfd-4e03-4262-9b94-bc9a9ceb571e/1634802_src_1024x576_1500.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1925, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1864, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
'

**Comment by em-jay-es** [comment]
@PlaceboPRS, unfortunately, this does not work for me. I am in Germany, using Deutsche Telekom DSL, so I suppose geo-restriction should not be the issue?

**Comment by PlaceboPRS** [comment]
Which show are you specifically trying to grab? I tried a random Timeless episode off there and didn't even need to use the cookie stuff etc:

![image](https://user-images.githubusercontent.com/23120453/77854051-1fe9f880-71e8-11ea-94d6-7501a67395b4.png)

**Comment by Knut-HH** [comment]
Ok, that problem was rather old. Shows are up there for 7 days normally.
with the new version, Tele 5 is mostly working again, problems now are caused by server load, but that's no problem of youtube-dl

**Comment by geosone** [comment]
Todyy it's not working again. with the latest version. no download at all.

`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tele5.de/filme/die-folterkammer-des-dr-fu-man-chu/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.6.10 (CPython) - Linux-5.4.0-sabayon-x86_64-Intel-R-_Core-TM-_i7-3720QM_CPU_@_2.60GHz-with-gentoo-2.6
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[Tele5] die-folterkammer-des-dr-fu-man-chu: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/tele5.py", line 53, in _real_extract
    r'\bdata-id\s*=\s*["\'](\d{6,})'), webpage, 'video id')
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by Knut-HH** [comment]
Yes, I can confirm this, Tele 5 changed its webpage

**Comment by AnregendSpektakulaererNasenbaer** [comment]
They switched to HLS streaming.

**Comment by LadyMarmelade** [comment]
Wow, you guys clearly know much more than i do. With youtube-dl --version : 2020.03.24
I tried 
youtube-dl --verbose -k --ignore-config https://www.tele5.de/filme/jackie-brown/
(online up til 20.4.24) Although i can see the video online, downloading fails with:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-k', u'--ignore-config', u'https://www.tele5.de/filme/jackie-brown/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-96-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15, rtmpdump 2.4
[debug] Proxy map: {}
[Tele5] jackie-brown: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tele5.py", line 53, in _real_extract
    r'\bdata-id\s*=\s*["\'](\d{6,})'), webpage, 'video id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Neither do i understand that nor have a clue, as to how to work around this. Any help greatly appreciated!
