### ISSUE TITLE
Unable to extract ott data

### ISSUE THREAD

**Issue by angelvilu** [ytdl-org/youtube-dl#22817]
An hour ago I was able to download videos from Vimeo OTT (more specifically WoWPresentsPlus videos) but right now I can't download any, this is what happens:
```
.\youtube-dl.exe https://embed.vhx.tv/videos/594376?api=1"&"auth-user-token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0MDA1MTA5LCJleHAiOjE1NzE4NTIyMzZ9.hTWCWQdoWvSKVOgZbrGSy1CKiL1we1U0WfmuraENKSU
[vhx:embed] 594376: Downloading webpage
ERROR: Unable to extract ott data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
I have updated youtube-dl and tried forcing ipv4 but the message is the same.

**Comment by dstftw** [comment]
Does not play in browser.

**Comment by angelvilu** [comment]
Of course that link can no longer be reproduced, because the URL changes from time to time, but use the one I use does not work, it always gives me the same error and previously I could download.
