### ISSUE TITLE
EuroSportPlayer download

### ISSUE THREAD

**Issue by MichaelJOYoung** [ytdl-org/youtube-dl#22811]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.10.22**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
Please consider supporting downloads from EuroSportPlayer.
The eurosportplayer.com website has been updated and all the current download programs no longer work.
Thank you

**Comment by remitamine** [comment]
wrong issue template.
