### ISSUE TITLE
Playing links from another machine - proxy

### ISSUE THREAD

**Issue by xpiREC** [ytdl-org/youtube-dl#22822]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions

## Question

I try links (--get-url) from YouTube via proxy, they are from different countries.
I open the received link using ffmpeg, while I meet with the notes where I can't play it, I get a great page without autio (mp3).
I looked through the FAQ and found:

https://github.com/ytdl-org/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser

How do I adapt this solution to make it work properly? I am talking about using the right cookies or the right solution.

**Comment by dstftw** [comment]
Generally you can't.
