### ISSUE TITLE
abc.go.com now abc.com: Video extraction no longer working

### ISSUE THREAD

**Issue by tmthywynn8** [ytdl-org/youtube-dl#22823]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.10.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$youtube-dl -v https://abc.com/shows/the-rookie/episode-guide/season-02/03-the-bet
[debug] System config: []
[debug] User config: ['--abort-on-unavailable-fragment', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--no-geo-bypass', '--fixup', 'never', '--fragment-retries', '1', '--no-check-certificate', '--hls-prefer-native', '-f', 'bestaudio', '--prefer-ffmpeg']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://abc.com/shows/the-rookie/episode-guide/season-02/03-the-bet']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 4.1, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 03-the-bet: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 03-the-bet: Downloading webpage
[generic] 03-the-bet: Extracting information
ERROR: Unsupported URL: https://abc.com/shows/the-rookie/episode-guide/season-02/03-the-bet
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\generic.py", line 3353, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://abc.com/shows/the-rookie/episode-guide/season-02/03-the-bet
```

## Description

Between October 21 and October 23, ABC stopped using the go domain for their videos, e.g., instead of:  
https://abc.go.com/shows/the-rookie/episode-guide/season-02/03-the-bet  
the link is now:  
https://abc.com/shows/the-rookie/episode-guide/season-02/03-the-bet

Unfortunately, though there is still traffic coming from go.com as well as uplynk.com, youtube-dl is unable to retrieve ABC content&mdash;presumably because there's no regexp to account for the new domain change in the go extractor.

If possible, can the go extractor be modified to account for the  domain change from abc.go.com to just abc.com?

Update: Unfortunately, the fix is not as simple as just changing the URL regexp, as even with the modifications locally on my end, it can't find the video ID. I'll have to take a closer look at the extractor's source and see what code changes were made on ABC's end that broke the functionality.

**Comment by tmthywynn8** [comment]
## Solution

1. Modify _VALID_URL to account for the domain change from abc.go.com to just abc.com. I can't wrap my head around the regexp in order to do this, hence no code snippet.
2. Under the _real_extract section, change the regexp for video_id (line 100) to read:  
`r'"id":["\']*(VDKA\w+)', webpage, 'video id',`  
instead of:  
`r'data-video-id=["\']*(VDKA\w+)', webpage, 'video id',`

Titling and downloading seem to work without issue, though I haven't tried downloading a series to see if the other regexps are okay. I don't think they are, though, seeing that the format has changed from "KEYWORD":"VALUE" instead of KEYWORD=VALUE.

**Comment by leetistan** [comment]
appears encryption is being used now,  "drmEncoding:	WIDEVINE"

**Comment by auouymous** [comment]
Thank you! Here is a patch that makes the above change.

```
diff --git a/youtube_dl/extractor/go.py b/youtube_dl/extractor/go.py
index 03e48f4ea..2a9a130de 100644
--- a/youtube_dl/extractor/go.py
+++ b/youtube_dl/extractor/go.py
@@ -40,7 +40,7 @@ class GoIE(AdobePassIE):
             'resource_id': 'Disney',
         }
     }
-    _VALID_URL = r'https?://(?:(?:(?P<sub_domain>%s)\.)?go|(?P<sub_domain_2>disneynow))\.com/(?:(?:[^/]+/)*(?P<id>vdka\w+)|(?:[^/]+/)*(?P<display_id>[^/?#]+))'\
+    _VALID_URL = r'https?://(?:(?:(?P<sub_domain>%s)(?:\.go)?)?|(?P<sub_domain_2>disneynow))\.com/(?:(?:[^/]+/)*(?P<id>vdka\w+)|(?:[^/]+/)*(?P<display_id>[^/?#]+))'\
                  % '|'.join(list(_SITE_INFO.keys()) + ['disneynow'])
     _TESTS = [{
         'url': 'http://abc.go.com/shows/designated-survivor/video/most-recent/VDKA3807643',
@@ -97,7 +97,7 @@ class GoIE(AdobePassIE):
             video_id = self._search_regex(
                 # There may be inner quotes, e.g. data-video-id="'VDKA3609139'"
                 # from http://freeform.go.com/shows/shadowhunters/episodes/season-2/1-this-guilty-blood
-                r'data-video-id=["\']*(VDKA\w+)', webpage, 'video id',
+                r'"id":["\']*(VDKA\w+)', webpage, 'video id',
                 default=video_id)
             if not site_info:
                 brand = self._search_regex(
```

**Comment by channelmars** [comment]
> 
> 
> Thank you! Here is a patch that makes the above change.
> 
> ```
> diff --git a/youtube_dl/extractor/go.py b/youtube_dl/extractor/go.py
> index 03e48f4ea..2a9a130de 100644
> --- a/youtube_dl/extractor/go.py
> +++ b/youtube_dl/extractor/go.py
> @@ -40,7 +40,7 @@ class GoIE(AdobePassIE):
>              'resource_id': 'Disney',
>          }
>      }
> -    _VALID_URL = r'https?://(?:(?:(?P<sub_domain>%s)\.)?go|(?P<sub_domain_2>disneynow))\.com/(?:(?:[^/]+/)*(?P<id>vdka\w+)|(?:[^/]+/)*(?P<display_id>[^/?#]+))'\
> +    _VALID_URL = r'https?://(?:(?:(?P<sub_domain>%s)(?:\.go)?)?|(?P<sub_domain_2>disneynow))\.com/(?:(?:[^/]+/)*(?P<id>vdka\w+)|(?:[^/]+/)*(?P<display_id>[^/?#]+))'\
>                   % '|'.join(list(_SITE_INFO.keys()) + ['disneynow'])
>      _TESTS = [{
>          'url': 'http://abc.go.com/shows/designated-survivor/video/most-recent/VDKA3807643',
> @@ -97,7 +97,7 @@ class GoIE(AdobePassIE):
>              video_id = self._search_regex(
>                  # There may be inner quotes, e.g. data-video-id="'VDKA3609139'"
>                  # from http://freeform.go.com/shows/shadowhunters/episodes/season-2/1-this-guilty-blood
> -                r'data-video-id=["\']*(VDKA\w+)', webpage, 'video id',
> +                r'"id":["\']*(VDKA\w+)', webpage, 'video id',
>                  default=video_id)
>              if not site_info:
>                  brand = self._search_regex(
> ```

Any chance this gets updated in the exe version of YouTube-DL?

**Comment by dwalkerdon** [comment]
I hope that this gets foxed very quickly!

**Comment by kucksdorfs** [comment]
Well since the comments have been here for a while and I don't see any pull requests referencing this issue. I'll create the PR for it. Not sure what the youtube-dl teams schedule is like, but when I submitted my last PR it was in the next release or two (no more than a few days from PR accepted to in the release).
