### ISSUE TITLE
Downloading a series that is not part of a playlist.

### ISSUE THREAD

**Issue by Yomanew** [ytdl-org/youtube-dl#22827]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.10.22**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

There is a YouTube Channel that I want to download videos from. It is a series of maybe 100 videos. The creator has not added them into a playlist, so i wanted to know if there is a way to download all the videos of that series?

For example, the series has a special code name in its title, i.e "NightDTQ" in the every video of that series.

So, I wanted to know if there is some way I can download all the videos of that channel that have this code name in its title? While ignoring the rest of the videos.

If not, please add this feature into the youtube-dl program.

Thanks,
Umar

**Comment by dstftw** [comment]
```
--match-title REGEX              Download only matching titles (regex or
                                 caseless sub-string)
```
