### ISSUE TITLE
This video is not available from your location due to geo restriction - hotstar

### ISSUE THREAD

**Issue by pranjalisnow** [ytdl-org/youtube-dl#22836]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.10.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--ignore-errors', '--encoding', 'utf-8', '--get-title', 'https://www.hotstar.com/in/movies/mangalyaan-indias-mission-to-mars/1770005017/watch']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref utf-8
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-94014-g80e68ce116
[debug] Proxy map: {}
ERROR: This video is not available from your location due to geo restriction
This video is available in India.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\hotstar.py", line 158, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 940, in raise_geo_restricted
youtube_dl.utils.GeoRestrictedError: This video is not available from your location due to geo restriction
```

## Description

I'm seeing this message...
ERROR: This video is not available from your location due to geo restriction
This video is available in India.
You might want to use a VPN or a proxy server (with --proxy) to workaround.

I'm from India.
Could this be an issue with Youtube-DL or with the hotstar site?
The URL opens and plays fine on my Firefox, Chrome and Internet Explorer 11 browsers.

**Comment by lakshya-aggarwal** [comment]
Facing the same issue. For now, I have resolved it by downgrading the youtube-dl version to 2019-04-30. I think in the next version, hotstar extractor was upgraded to use api-v2 according to release information. Maybe the error is somehow related to that.
