### ISSUE TITLE
unable to extract OpenGraph title - Facebook video

### ISSUE THREAD

**Issue by pranjalisnow** [ytdl-org/youtube-dl#22834]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.10.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--ignore-errors', '--encoding', 'utf-8', '--get-title', 'https://www.facebook.com/satyaktar/videos/750364805160973/']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref utf-8
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-94014-g80e68ce116
[debug] Proxy map: {}
WARNING: unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: bestvideo+bestaudio/best
Mufti Kannada Dubbed Hindi Full Movie 2017 - ShivaRajkumar  SriiMurali -201  ...
```

## Description

unable to extract OpenGraph title - Facebook video

**Comment by duanbaosheng** [comment]
i have the same problem with you,  have you found the  method  to solve the problem ?

**Comment by pranjalisnow** [comment]
> 
> 
> i have the same problem with you, have you found the method to solve the problem ?

Not Yet!
