### ISSUE TITLE
unable to extract OpenGraph title - Facebook video

### ISSUE THREAD

**Issue by pranjalisnow** [ytdl-org/youtube-dl#22833]
Error while getting the Title of the Facebook videos.

**Comment by pranjalisnow** [comment]
Output logs below:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--ignore-errors', '--encoding', 'utf-8', '--get-title', 'https://www.facebook.com/satyaktar/videos/750364805160973/']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref utf-8
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-94014-g80e68ce116
[debug] Proxy map: {}
WARNING: unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: bestvideo+bestaudio/best
Mufti Kannada Dubbed Hindi Full Movie 2017 - ShivaRajkumar  SriiMurali -201  ...

**Comment by pranjalisnow** [comment]
Wrong method of submitting bug. Will create a new one.

**Comment by duanbaosheng** [comment]
i have the same problem with you,  have you found the  method  to solve the problem ?
