### ISSUE TITLE
Vlive %(upload_date)s

### ISSUE THREAD

**Issue by ExodusHour** [ytdl-org/youtube-dl#22830]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is it possible to get the %(upload_date)s of vlive videos? Currently it just comes up as "NA". Right now I'm using %(playlist_index)s to keep the upload order when downloading channels but videos are sometimes deleted so when I rerun the download I end up getting some duplicate numbers.

**Comment by biwubo** [comment]
@ExodusHour There doesn't seem to be an obvious way to get the upload date of a video with precision. However if all you care about is the order of the videos in a playlist you should be able to use the ID of the video itself. The IDs are numeric and sequential so should give you the same order as the upload date.

Using the playlist `https://www.vlive.tv/video/146278/playlist` as an example the IDs of the video in playlist order are:
```
146278
146279
147288
147289
147668
147680
148453
148442
148914
148917
149531
149533
149904
149905
150443
150444
151166
151168
151928
151929
152536
152538
152987
153003
153008
```
Just eyeballing the list, it looks to be in numeric order.

**Comment by ExodusHour** [comment]
Yeah that's what I found out and ended up using the IDs. Thank you for trying.
