### ISSUE TITLE
PURL for bitchute (and all other videos)

### ISSUE THREAD

**Issue by blawiz** [ytdl-org/youtube-dl#22847]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.10.22**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

When downloading bitchute.com videos (and maybe all sites) with 'youtube-dl --add-metadata' it would be nice if PURL metadata would be added, like it does for youtube videos.

**Comment by remitamine** [comment]
fill the correct issue template(bug report), and make sure that you include the full verbose log when you're using `--add-metadata` and screen or output of a tool that don't detect the `PURL` in the result file.
