### ISSUE TITLE
Failing with "WARNING: unable to extract description"

### ISSUE THREAD

**Issue by Hairybiker** [ytdl-org/youtube-dl#22856]
youtube-dl "https://www.youtube.com/watch?v=mYXenjpefNU&list=RDQMmiLNsCAXoVA&index=1" --ignore-config --verbose --proxy ""
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=mYXenjpefNU&list=RDQMmiLNsCAXoVA&index=1', u'--ignore-config', u'--verbose', u'--proxy', u'']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.22
[debug] Python version 2.7.15+ (CPython) - Linux-5.0.0-32-generic-x86_64-with-LinuxMint-19.2-tina
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist RDQMmiLNsCAXoVA - add --no-playlist to just download video mYXenjpefNU
[youtube:playlist] RDQMmiLNsCAXoVA: Downloading page 1 of Youtube mix
[youtube:playlist] RDQMmiLNsCAXoVA: Downloading page 2 of Youtube mix
[youtube:playlist] RDQMmiLNsCAXoVA: Downloading page 3 of Youtube mix
[download] Downloading playlist: Mix - Dave allen
[youtube:playlist] playlist Mix - Dave allen: Collected 39 video ids (downloading 39 of them)
[download] Downloading video 1 of 39
[youtube] miLNsCAXoVA: Downloading webpage
[youtube] miLNsCAXoVA: Downloading video info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: This video is unavailable.
Sorry about that.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2148, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.
Sorry about that.

Just updated youtube-dl to latest version. 
Url plays fine in the browser

**Comment by remitamine** [comment]
```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
```
