### ISSUE TITLE
Youtube login authentication failed

### ISSUE THREAD

**Issue by overgara2012** [ytdl-org/youtube-dl#22862]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.10.22**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE


C:\Users\overg\Downloads>youtube-dl --verbose --username "overgara@gmail.com" --password "xxxxxxxx" "https://www.youtube.com/watch?time_continue=985&v=wpWvdcHZqnk"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.youtube.com/watch?time_continue=985&v=wpWvdcHZqnk']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to extract result entry
[youtube] wpWvdcHZqnk: Downloading webpage
[youtube] wpWvdcHZqnk: Downloading embed webpage
[youtube] wpWvdcHZqnk: Refetching age-gated info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\youtube.py", line 2148, in _real_extract
youtube_dl.utils.ExtractorError: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.


C:\Users\overg\Downloads>youtybe-dl --version
'youtybe-dl' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\overg\Downloads>youtube-dl --version
2019.10.22


```

## Description

WRITE DESCRIPTION HERE

Youtube login authentication failed, not sure if command is right:
 youtube-dl --verbose --username "email" --password "xxxxxxxx" "youtube URL" 
??

**Comment by X-C0DE** [comment]
you need to login using cookies
try using this extension that will work: https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg

**Comment by sbimochan** [comment]
> ## Checklist
> * [ ]  I'm reporting a broken site support issue
> * [x] I've verified that I'm running youtube-dl version **2019.10.22**
> * [x] I've checked that all provided URLs are alive and playable in a browser
> * [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
> * [x] I've searched the bugtracker for similar bug reports including closed ones
> * [x] I've read bugs section in FAQ
> 
> ## Verbose log
> ```
> PASTE VERBOSE LOG HERE
> 
> 
> C:\Users\overg\Downloads>youtube-dl --verbose --username "overgara@gmail.com" --password "xxxxxxxx" "https://www.youtube.com/watch?time_continue=985&v=wpWvdcHZqnk"
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.youtube.com/watch?time_continue=985&v=wpWvdcHZqnk']
> [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
> [debug] youtube-dl version 2019.10.22
> [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
> [debug] exe versions: none
> [debug] Proxy map: {}
> [youtube] Downloading login page
> [youtube] Looking up account info
> [youtube] Logging in
> WARNING: Unable to extract result entry
> [youtube] wpWvdcHZqnk: Downloading webpage
> [youtube] wpWvdcHZqnk: Downloading embed webpage
> [youtube] wpWvdcHZqnk: Refetching age-gated info webpage
> WARNING: Unable to extract video title
> WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> ERROR: Content Warning
> If the owner of this video has granted you access, please sign in.
>        This video is private.
> Traceback (most recent call last):
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\common.py", line 530, in extract
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpifszpy0p\build\youtube_dl\extractor\youtube.py", line 2148, in _real_extract
> youtube_dl.utils.ExtractorError: Content Warning
> If the owner of this video has granted you access, please sign in.
>        This video is private.
> 
> 
> C:\Users\overg\Downloads>youtybe-dl --version
> 'youtybe-dl' is not recognized as an internal or external command,
> operable program or batch file.
> 
> C:\Users\overg\Downloads>youtube-dl --version
> 2019.10.22
> ```
> 
> ## Description
> WRITE DESCRIPTION HERE
> 
> Youtube login authentication failed, not sure if command is right:
> youtube-dl --verbose --username "email" --password "xxxxxxxx" "youtube URL"
> ??

**Comment by lifegivesyoulemons** [comment]
have you solved that in any way? i have an identical problem
