### ISSUE TITLE
How to pull YouTube playlist/channel total duration and file size information

### ISSUE THREAD

**Issue by beskhu3epnm** [ytdl-org/youtube-dl#22881]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi. I wish to know the total duration and total filesize of a given large YouTube channel or channel playlist. I'm wondering how this can be done using youtube-dl, and what is the easiest method to do this?

**Comment by dstftw** [comment]
Total duration and total filesize are too ambiguous notions. Extract playlist metadata as JSON and do whatever analytics you need.
