### ISSUE TITLE
Write to --download-archive file but don't download

### ISSUE THREAD

**Issue by Jeeaaasus** [ytdl-org/youtube-dl#22908]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is it possible to use `--download-archive` while also not downloading videos?

For example, say there's a very large playlist, I don't want to download any video, I only want to fill my `--download-archive` file, to be able to download every new video after this.

It feels like `--skip-download` or `--get-id` should do that, but they don't.

**Comment by dstftw** [comment]
Not possible.
