### ISSUE TITLE
Downloading stops every single time!

### ISSUE THREAD

**Issue by Yomanew** [ytdl-org/youtube-dl#22920]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.10.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

I am facing this error, and it happens every single time, either this type of error, or something else, but the download stops that is for sure.

[youtube] 2gkYr7hoBj8: Downloading webpage
[youtube] 2gkYr7hoBj8: Downloading video info webpage
[download] Destination: Juristic Maxims  - Qawaa'id Fiqhiyah (Part 1) - Shaykh Ahsan Hanif-2gkYr7hoBj8.f244.webm
[download]  71.3% of 243.03MiB at 669.13KiB/s ETA 01:46  [download] Got server HTTP error: [WinError 10054] An existing connection was forcibly closed by the remote host. Retrying (attempt 1 of 10)...
ERROR: unable to download video data: <urlopen error [Errno 11001] getaddrinfo failed>

C:\Users\M. Umar Farooq\Downloads\youtube-dl>

**Comment by dstftw** [comment]
Network/DNS issue on your side.

**Comment by Yomanew** [comment]
How can I make it resume or force continue after it happens? So that when I wake up in the morning, I don't see an ugly error, but a nice finished download message.
