### ISSUE TITLE
[Platzi] youtube-dl  raise RegexNotFoundError('Unable to extract %s' % _name)

### ISSUE THREAD

**Issue by developcreativo** [ytdl-org/youtube-dl#22939]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2019.10.29**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -o "%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" --sleep-interval 22 --all-subs --cookies cookies.txt -ciw --verbose https://platzi.com/clases/firebase-web/ --username ### --password ###
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', '--sleep-interval', '22', '--all-subs', '--cookies', 'cookies.txt', '-ciw', '--verbose', 'https://platzi.com/clases/firebase-web/', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.10.29
[debug] Python version 3.6.1 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[PlatziCourse] Downloading login page
[PlatziCourse] Logging in
[PlatziCourse] firebase-web: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\laragon\bin\python\python-3.6.1\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "c:\laragon\bin\python\python-3.6.1\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\laragon\bin\python\python-3.6.1\lib\site-packages\youtube_dl\extractor\platzi.py", line 190, in _real_extract
    self._search_regex(r'data\s*=\s*({.+?})\s*;', webpage, 'data'),
  File "c:\laragon\bin\python\python-3.6.1\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by vdjkelly** [comment]
change code 
` props = self._parse_json(
            self._search_regex(r'data\s*=\s*({.+?})\s*;', webpage, 'data'),
            course_name)['initialProps']`

by
`props = self._parse_json(
            self._search_regex(r'initialData\s*=\s*({.+?})\s*;', webpage, 'initialData'),
            course_name)['initialState']`

Fix file platzi.py

Excuse me, my English, I don't know it at all

**Comment by Strife89** [comment]
I just encountered the same error.

Output: https://pastecode.xyz/view/2b4a21b3

**Comment by dirkf** [comment]
I've updated the PR code. Please test and follow up [there](https://github.com/ytdl-org/youtube-dl/pull/30548).

**Comment by developcreativo** [comment]
> youtube-dl -o "%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" --sleep-interval 22 --all-subs --cookies cookies.txt -ciw --verbose https://platzi.com/clases/firebase-web/ --username ### --password ###

` youtube-dl -o "%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" --sleep-interval 22  --cookies cookies.txt -ciw --verbose https://platzi.com/cursos/prework-windows/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', '--sleep-interval', '22', '--cookies', 'cookies.txt', '-ciw', '--verbose', 'https://platzi.com/cursos/prework-windows/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.7.3 (CPython) - Linux-5.15.45-amd64-desktop-x86_64-with-Deepin-20.7.1-apricot
[debug] exe versions: ffmpeg 4.4.2-1, ffprobe 4.4.2-1
[debug] Proxy map: {}
[generic] prework-windows: Requesting header
WARNING: Could not send HEAD request to https://platzi.com/cursos/prework-windows/: HTTP Error 403: Forbidden
[generic] prework-windows: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] prework-windows: Extracting information
ERROR: Unsupported URL: https://platzi.com/cursos/prework-windows/
Traceback (most recent call last):
  File "/home/development/proyectos/platzi/venv/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/development/proyectos/platzi/venv/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/development/proyectos/platzi/venv/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/development/proyectos/platzi/venv/lib/python3.7/site-packages/youtube_dl/extractor/generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://platzi.com/cursos/prework-windows/
`
