### ISSUE TITLE
Unsupported URL: megamult.net

### ISSUE THREAD

**Issue by SlazE888** [ytdl-org/youtube-dl#22937]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.10.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: http://megamult.net/stuff/piraty_banda_neudachnikov/3-1-0-992
- Single video: http://megamult.net/stuff/griffiny_18_sezon/7-1-0-1891

## Description

All video examples above plays fine in Google Chrome browser.

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free
