### ISSUE TITLE
Unsupported URL: pladform.ru

### ISSUE THREAD

**Issue by SlazE888** [ytdl-org/youtube-dl#22942]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.10.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: http://out.pladform.ru/player?pl=15978&videoid=101194430
- Single video: http://out.pladform.ru/player?pl=15978&videoid=101293288

## Description

All video examples above plays fine in Google Chrome browser.

**Comment by remitamine** [comment]
already supported.
