### ISSUE TITLE
while downloading the videos i m getting this audio video merge issue

### ISSUE THREAD

**Issue by sajan1231** [ytdl-org/youtube-dl#22966]
[youtube] BZRLKDlSaAI: Downloading webpage
[youtube] BZRLKDlSaAI: Downloading video info webpage
WARNING: You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
[download] Destination: 20+ Developer YouTube Channels To Follow-BZRLKDlSaAI.f137.mp4
[download]  34.7% of 97.96MiB at 862.41KiB/s ETA 01:15\

**Comment by remitamine** [comment]
install `FFmpeg` or `avconv`.
