### ISSUE TITLE
vorbis or libvorbis on ffmpeg?

### ISSUE THREAD

**Issue by fluoroom** [ytdl-org/youtube-dl#22961]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

My simple doubt is that, youtube-dl tells ffmpeg to use vorbis or libvorbis? I read on ffmpeg website that libvorbis is the one that should be used and it's confusing that youtube-dl has only the "vorbis" option.
Thanks in advance!

**Comment by remitamine** [comment]
the user does not have to know every internal FFmpeg library(libvorbis, libopus, libmp3lame...) to use youtube-dl options.

**Comment by fluoroom** [comment]
Thank you!
