### ISSUE TITLE
vhx:embed not working

### ISSUE THREAD

**Issue by technicavivunt** [ytdl-org/youtube-dl#22976]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
C:\>youtube-dl --verbose https://embed.vhx.tv/videos/633679?api=1&auth-user-token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0NzQ2MTI0LCJleHAiOjE1NzI5MjUwMTB9.Gtj3ylf12l96vmbQqgiTC3KwK7I4-z-H-UnVBiVkDN0&autoplay=1&back=RuPaul%27s%20Drag%20Race%20UK%20-%20Season%201&color=ffffff&context=https%3A%2F%2Fwww.wowpresentsplus.com%2Frupaul-s-drag-race-uk%2Fseason%3A1&live=0&playsinline=1&referrer=https%3A%2F%2Fwww.wowpresentsplus.com%2Frupaul-s-drag-race-uk&sharing=1&title=0&vimeo=1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://embed.vhx.tv/videos/633679?api=1']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[vhx:embed] 633679: Downloading webpage
ERROR: Unable to extract ott data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\vimeo.py", line 1127, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract ott data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

I've tried several different URLs from WOW with none of them working. Any advice or workarounds would be appreciated.

**Comment by remitamine** [comment]
URL does not work in the browser:
> Sorry, you are not authorized to watch this video.
