### ISSUE TITLE
%(title)s and %(fulltitle)s are truncated at dot when field placed last in output template list

### ISSUE THREAD

**Issue by nicealias** [ytdl-org/youtube-dl#22977]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'worstvideo', u'--write-thumbnail', u'-o', u'%(title)s %(_filename)s %(fulltitle)s', u'https://www.youtube.com/watch?v=9J1jjz2ZgyE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.17rc1 (CPython) - Linux-5.3.0-19-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2
[debug] Proxy map: {}
[youtube] 9J1jjz2ZgyE: Downloading webpage
[youtube] 9J1jjz2ZgyE: Downloading video info webpage
[youtube] 9J1jjz2ZgyE: Downloading thumbnail ...
[youtube] 9J1jjz2ZgyE: Writing thumbnail to: iOS 13.2 - Follow Up NA iOS 13.jpg
[debug] Invoking downloader on u'https://r8---sn-cu-ajtez.googlevideo.com/videoplayback?expire=1572961007&ei=jybBXdeIKY6YV66eiIgD&ip=213.31.102.178&id=o-AAcNI0pdhORLfcwBMWozCGy1grMctfprLuCgC1zqG5ab&itag=160&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-cu-ajtez%2Csn-5hnekn7l&ms=au%2Conr&mv=m&mvi=7&pl=25&initcwndbps=1188750&mime=video%2Fmp4&gir=yes&clen=4222171&dur=882.014&lmt=1572766821265860&mt=1572939282&fvip=2&keepalive=yes&fexp=23842630&c=WEB&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRgIhALhJTJVn5R5aoRJHuAzpy0RYapRoXM2OvNgIFuYVrHffAiEA9QkAZf-RIIGLJho0PLOZ_TWzpEF4tuXr5pX4Ln6Q6dc%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAIxpW46iJtnoo8ntfEJfC8knWPrHyZ-xf-mH9e9cMFtmAiA0wWlov4GIFECseCaiHefQ9ND4qKm0PBZoEHkz1gO2vQ%3D%3D&ratebypass=yes'
[download] Destination: iOS 13.2 - Follow Up NA iOS 13.2 - Follow Up
[download] 100% of 4.03MiB in 00:01

```

## Description

When using the "title" or "fulltitle" name/field and they are placed as the last in the sequence for the output template, the resulting value will be truncated at the dot (if present in the actual title).
In the example provided they are in first and third (last) place and while the first results in the full actual title, the third (last) is truncated. Same happens when swapping them around first <> third.
Please note that the truncated result only shows in the thumbnail filename and not in the video filename. PS: I used worstvideo for a quick turnaround, happens with bestvideo too.
Expected thumbnail filename: iOS 13.2 - Follow Up NA iOS 13.2 - Follow Up.jpg
Actual thumbnail filename: iOS 13.2 - Follow Up NA iOS 13.jpg

**Comment by dstftw** [comment]
1. You are not allowed to use `_filename` or `fulltitle` in output template. These are internal fields.
2. You must use `%(ext)s` in output template.
