### ISSUE TITLE
Support for scte.org

### ISSUE THREAD

**Issue by frakman1** [ytdl-org/youtube-dl#22975]
## Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2019.10.29**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs violate any copyrights
- [X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video:??
- Single video: ??
- Playlist:??
 
See below description

## Description

I have an account with scte.org which provides training lessons. I wish to download the content for offline access.

The learning portal launches a browser that plays the content.
The following screenshot is the link I click. It points to:

`https://learning.scte.org/mod/scorm/view.php?id=31484`

![image](https://user-images.githubusercontent.com/5826484/68151057-febdfe00-ff0e-11e9-92a5-aad283124a4a.png)

The window that is launched has a URL of:
https://learning.scte.org/mod/scorm/player.php?a=3605&currentorg=DOCSIS_Engineering_Professional_ORG&scoid=9700&sesskey=xxxxx&display=popup

When I click 'Start' it stats playing a series of videos. Not sure what the playlist or video files are so I can't include them.

I am not sure how much you can help without an account but if you want me to run any "Inspect" source on the page, then I'll be happy to report back.

**Comment by dstftw** [comment]
You must provide account credentials. There is no other way.
