### ISSUE TITLE
Avoid downloading other file types

### ISSUE THREAD

**Issue by TaktakTaktouk** [ytdl-org/youtube-dl#22974]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Giving youtube-dl this URL http://releases.ubuntu.com/18.04.3/ubuntu-18.04.3-desktop-amd64.iso it was able to download it. It's not a video it an iso file of Ubuntu. 
My question is how to tell youtube-dl to download only videos and reject any other file types?

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#format-selection filter by `ext`.
