### ISSUE TITLE
Geo-Location Restriction

### ISSUE THREAD

**Issue by implycit** [ytdl-org/youtube-dl#22984]
youtube-dl -F https://www.hotstar.com/in/movies/women-of-impact-changing-the-world/1260013115 -v                      
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.hotstar.com/in/movies/women-of-impact-changing-the-world/1260013115', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.7.4 (CPython) - Linux-4.19.81-1-MANJARO-x86_64-with-arch-Manjaro-Linux
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[hotstar] 1260013115: Downloading webpage
[hotstar] 1260013115: Downloading JSON metadata
[hotstar] 1260013115: Downloading m3u8 information
[hotstar] 1260013115: Downloading MPD manifest
[hotstar] 1260013115: Downloading MPD manifest
[hotstar] 1260013115: Downloading MPD manifest
[hotstar] 1260013115: Downloading m3u8 information
[hotstar] 1260013115: Downloading MPD manifest
[hotstar] 1260013115: Downloading m3u8 information
[hotstar] 1260013115: Downloading MPD manifest
[hotstar] 1260013115: Downloading MPD manifest
[hotstar] 1260013115: Downloading MPD manifest
[hotstar] 1260013115: Downloading m3u8 information
[hotstar] 1260013115: Downloading MPD manifest
ERROR: This video is not available from your location due to geo restriction
This video is available in India.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/hotstar.py", line 158, in _real_extract
    self.raise_geo_restricted(countries=['IN'])
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 940, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
youtube_dl.utils.GeoRestrictedError: This video is not available from your location due to geo restriction

#My geo location is
curl https://freegeoip.app/xml/
<Response>
         <CountryCode>IN</CountryCode>
        <CountryName>India</CountryName>
        <RegionCode>MH</RegionCode>
        <RegionName>Maharashtra</RegionName>
        <City>Mumbai</City>
        <TimeZone>Asia/Kolkata</TimeZone>

**Comment by implycit** [comment]
How is it a duplicate ?
How do i solve this?

**Comment by remitamine** [comment]
> How is it a duplicate ?

this problem has been already reported before.
> How do i solve this?

wait for next release.
