### ISSUE TITLE
It seems youtube banned me with "Error 429: Too Many Requests" for downloading too much?

### ISSUE THREAD

**Issue by ZYinMD** [ytdl-org/youtube-dl#22983]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
Yesterday I was downloading several thousand songs from youtube with `--extract-audio` , by having over a hundred playlists in my url file. Today I woke up and found half was done, the second half were all blocked by `Error 429: Too Many Requests`. Then I tested with some other random non-music videos, same result. 

I have no problem watching youtube in browser though.

Is youtube known to do this? Will I get unbanned after a while?
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=nrluT5oNbsQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.2.1-0york0, ffprobe 4.2.1-0york0, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube] nrluT5oNbsQ: Downloading webpage
[youtube] nrluT5oNbsQ: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: nrluT5oNbsQ: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1836, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: nrluT5oNbsQ: YouTube said: Unable to extract video data
```

**Comment by Zuccace** [comment]
Yes. Youtube does this. I'm not sure if it's a ban really since no one has reported they've been also blocked on the www-site.
Proxying your connection also does not seem to work.

**Comment by ZYinMD** [comment]
Hi @Zuccace , thanks very much for your answer! Are they known to unban me after some time? By now it's been 4 days, still the same...

**Comment by Zuccace** [comment]
I don't know how youtube handles these internally. But I investigated more, and it seems that "greylisted" IPs need to solve catchpa. I figured this out by sandboxing a seperate browser session and using a proxy server.

There isn't much I, or youtube-dl devs can do right now. :(

This really sucks since I cannot usually watch 4k content directly on browser because my internet connection is very unstable. The obvious answer has been to use youtube-dl.

We can just hope someone comes up with a working patch.

**Comment by ZYinMD** [comment]
Oh yes! Thanks for finding that catchpa behavior! Indeed, it's very easy to reproduce. Just open an incognito window and click any youtube video, boom there's the catchpa.

I hope it'll go away on its own after some time, I'll report back when it does.

**Comment by born2net** [comment]
same issue here... no solution?

**Comment by mfierro0** [comment]
Hi @ZYinMD,

> I hope it'll go away on its own after some time, I'll report back when it does.

Have you been unbanned?

Thanks.
