### ISSUE TITLE
https://www.ixigua.com/ needed

### ISSUE THREAD

**Issue by willingheart1990** [ytdl-org/youtube-dl#22991]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Continued in #24186.
