### ISSUE TITLE
Unable to download from USA Network

### ISSUE THREAD

**Issue by merval** [ytdl-org/youtube-dl#23007]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2019.11.05**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ap-user', u'PRIVATE', u'--ap-password', u'PRIVATE', u'--ap-mso', u'Comcast_SSO', u'https://www.usanetwork.com/wwe-nxt/videos/nxt-1162019', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[USANetwork] nxt-1162019: Downloading webpage
[USANetwork] 4054396: Downloading Provider Redirect Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/usanetwork.py", line 60, in _real_extract
    url, video_id, adobe_pass.get('adobePassRequestorId', 'usa'), resource)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adobepass.py", line 1453, in _extract_mvpd_auth
    self._DOWNLOADING_LOGIN_PAGE)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adobepass.py", line 1365, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

I'm unable to download from USA Network website. I've confirmed the login creds are good.

**Comment by Mr-Jake** [comment]
I just tested USA Network and it works. What is broken is the Comcast login. The Comcast login has not worked for a long time. There is a fix posted in the pull request section by raleeper that works, but it was not merged. If you are able to compile youtube-dl yourself it should work.

**Comment by TCSFrank** [comment]
Can also confirm USA Network downloads are working perfectly. Not using Comcast though.

**Comment by merval** [comment]
I made the changes to the Comcast SSO and confirmed that ABC which wasn't working, is now working. But the above link still fails:
`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ap-user', u'debra.taylor1', u'--ap-password', u'PRIVATE', u'--ap-mso', u'Comcast_SSO', u'https://www.usanetwork.com/wwe-nxt/videos/nxt-1162019', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.01
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-72-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[USANetwork] nxt-1162019: Downloading webpage
ERROR: Unable to extract mpx-guid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/usanetwork.py", line 37, in _real_extract
    video_id = _x('mpx-guid')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/usanetwork.py", line 35, in _x
    webpage, name, default=default, group='value')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract mpx-guid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by merval** [comment]
Switching the Comcast SSO as per this PR: https://github.com/ytdl-org/youtube-dl/pull/17636 resolved this. It's a shame it hasn't been merged yet.
