### ISSUE TITLE
Disney+ site request

### ISSUE THREAD

**Issue by OgnistyPoland** [ytdl-org/youtube-dl#23005]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [ ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

Mandalorian trailer
https://www.disneyplus.com/video/73b1f5c3-cadd-496b-9c0b-89a3cddbedf7

## Description

WRITE DESCRIPTION HERE

**Comment by remitamine** [comment]
not accessible redirects to https://preview.disneyplus.com/.

**Comment by remitamine** [comment]
and BTW, the trailers can be download from Disney Video website:
https://video.disney.com/watch/the-mandalorian-official-trailer-disney-streaming-november-12-590d215492599ebd6b4f2a72
https://video.disney.com/watch/the-mandalorian-official-trailer-2-disney-streaming-nov-12-5960254e7956bebd6b4f2a72
