### ISSUE TITLE
Mediasite download both streams

### ISSUE THREAD

**Issue by Derkades** [ytdl-org/youtube-dl#23003]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

My university has 2 streams on their mediasite page: one for a camera pointed at the lecturer, and one video stream from a computer/tablet. Right now when I download using youtube-dl the video I only get the camera stream, not the other stream. I don't know what would be the best way to solve this, maybe:
* Download all video streams into separate files, allowing the user to choose which videos to play. The user can view multiple videos simultaneously.
* Add an option to choose which stream to download. If this option is not specified and the page has more than one stream, it should prompt the user.

**Comment by Derkades** [comment]
How is incomplete?

**Comment by fstirlitz** [comment]
Well, you didn’t post the URL.

But this is already supported anyway: the alternative video streams are available as extra formats and can be listed with `--list-formats`, though by default, only `video1` will be downloaded. See #20611. Forks of this project like https://github.com/yt-dlp/yt-dlp can even manage to mux all video streams into a single file.
