### ISSUE TITLE
YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by Gumiro90** [ytdl-org/youtube-dl#23017]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2019.11.05**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--get-duration', u'--get-url', u'--get-title', u'--no-progress', u'--no-warnings', u'--source-address', u'XXXXXXXXXXXX', u'-f', u'22/17/18', u'https://www.youtube.com/watch?v=A28w_SCvExc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.9 (CPython) - Linux-4.9.181-xxxx-std-ipv6-64-x86_64-with-Debian-8
[debug] exe versions: avconv 11.12-6, avprobe 11.12-6, ffmpeg 2.6.9, ffprobe 2.6.9
[debug] Proxy map: {}
ERROR: A28w_SCvExc: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1836, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: A28w_SCvExc: YouTube said: Unable to extract video data

## Description

Hi. I'am using YouTube-dl since years. Never had a problem. I have over 20 server running YouTube-dl but since 3 days i get an error "YouTube said: Unable to extract video data" but ONLY when I use "--source-address"

youtube-dl -v --get-duration --get-url --get-title --no-progress --no-warnings --source-address XXX.XXX.XXX.XXX -f 22/17/18 "https://www.youtube.com/watch?v=XXXXX" 2>&1 

When I use --proxy it works, when I use without --source-address it works. I didn't changed anything on the server and on the script. I have thousands of proxy (which I use with --proxy) and over 10 Server IP's each server. The server ip's are not blocked I checked it - it works well without --source-address. I have an autoupdate script which checks every 10 minutes for new updated YouTube-dl so that's also not the problem.

I just replaced my IP with XXXXXXXXX

Thanks for help!

**Comment by norey** [comment]
I'm facing the same issue

```
$ youtube-dl --version
2019.11.05
$ youtube-dl -v https://www.youtube.com/watch?v=w_uT3GW1ycE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=w_uT3GW1ycE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.6.8 (CPython) - Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube] w_uT3GW1ycE: Downloading webpage
[youtube] w_uT3GW1ycE: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: w_uT3GW1ycE: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/home/nore/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/nore/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/nore/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1836, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: w_uT3GW1ycE: YouTube said: Unable to extract video data
```

**Comment by grenudi** [comment]
Same

kubuntu 

```
youtube-dl -v --cookies ~/cookies/youtube.txt 'https://www.youtube.com/watch?v=ML2gncutAJQ'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', '/home/master/cookies/youtube.txt', 'https://www.youtube.com/watch?v=ML2gncutAJQ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-58-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ML2gncutAJQ: Downloading webpage
ERROR: ML2gncutAJQ: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1788, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: ML2gncutAJQ: YouTube said: Unable to extract video data
```

@dstftw , duplicate of what ? May I ask.

**Comment by llacb47** [comment]
Are you stupid? Update youtube-dl and stop spamming multiple issues. @grenudi

**Comment by grenudi** [comment]
> Are you stupid? Update youtube-dl and stop spamming multiple issues. @grenudi

It's updated, so far as I can tell.
Am I being wrong ? 

![image](https://user-images.githubusercontent.com/17498075/103000905-fffc2100-453c-11eb-8fff-7916a5abc9f1.png)

```
 ~                                                                                                                  
❯ sudo youtube-dl --update
[sudo] password for master: 
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: youtube-dl's self-update mechanism is disabled on Debian.
Please update youtube-dl using apt(8).
See https://packages.debian.org/sid/youtube-dl for the latest packaged version.

 ~                                                                                               16:35:03  master 
 2 ❯ youtube-dl --update
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: youtube-dl's self-update mechanism is disabled on Debian.
Please update youtube-dl using apt(8).
See https://packages.debian.org/sid/youtube-dl for the latest packaged version.

 ~                                                                                               16:35:10  master 
 2 ❯ sudo apt-get upgrade youtube-dl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
youtube-dl is already the newest version (2020.03.24-1).
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  liba52-0.7.4 libaribb24-0 libbasicusageenvironment1 libcddb2 libdca0 libdvbpsi10 libebml4v5 libfaad2 libgles2
  libgroupsock8 libixml10 libkate1 liblirc-client0 liblivemedia77 libmad0 libmatroska6v5 libmpcdec6 libmpeg2-4
  libnfs13 libopenmpt-modplug1 libplacebo7 libprotobuf-lite17 libproxy-tools libresid-builder0c2a libsdl-image1.2
  libsdl1.2debian libsidplay2 libspatialaudio0 libsrt1 libupnp13 libusageenvironment3 libvlc-bin libvlc5
  libvlccore9 libxcb-xv0 vlc-bin vlc-data vlc-l10n vlc-plugin-base vlc-plugin-notify vlc-plugin-qt vlc-plugin-samba
  vlc-plugin-skins2 vlc-plugin-video-output vlc-plugin-video-splitter vlc-plugin-visualization
Use 'sudo apt autoremove' to remove them.
The following packages have been kept back:
  steam:i386
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
 ~                                                                                               16:35:31  master 
❯ 
```

**Comment by grenudi** [comment]
> Are you stupid? Update youtube-dl and stop spamming multiple issues. @grenudi

I didn't saw @**norey** reply so yeah... you are probably right

**Comment by grenudi** [comment]
@Gumiro90 @norey 

duplicate of this , I guess #27457 
https://github.com/ytdl-org/youtube-dl/issues/27457

I helped me, in any way
