### ISSUE TITLE
Chaturbate issue (room currently offline)

### ISSUE THREAD

**Issue by blastphemererik** [ytdl-org/youtube-dl#23010]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://chaturbate.com/lovely_monic/']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-94953-gef50cf7b32, ffprobe N-94953-gef50cf7b32
[debug] Proxy map: {}
[Chaturbate] lovely_monic: Downloading webpage
ERROR: Room is currently offline
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a0
9v\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a0
9v\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a0
9v\build\youtube_dl\extractor\chaturbate.py", line 61, in _real_extract
youtube_dl.utils.ExtractorError: Room is currently offline

## Description

It doesn't matter if a model is online, youtube-dl always says that the room is offline. Everything was fine today, the problems started a few hours ago. It seems the site got updated.

**Comment by Ubernoob7** [comment]
Having the same issue, sucks :( Hopefully there is a fix soon

**Comment by pcjamesy** [comment]
Same

**Comment by altDark** [comment]
The same issue

**Comment by cb123321** [comment]
Hello, when will official installation be updated with this fix?

**Comment by silvermindphasar** [comment]
the same problem
the site chatrubate now reports that the room is offline but the cam is active and broadcasts

**Comment by asdasddffgthhjtreresf** [comment]
Im having the same problem. Please fix. :( Thanks.

**Comment by r33bow** [comment]
I wrote a temporary fix for anyone else who doesn't want to wait for an official patch. Just replace the file at youtube_dl/extractor/chaturbate.py
The changes are on lines 43 through 48 if you are worried about the security of the changes. 
[chaturbate.zip](https://github.com/ytdl-org/youtube-dl/files/3826008/chaturbate.zip)

**Comment by asdasddffgthhjtreresf** [comment]
> I wrote a temporary fix for anyone else who doesn't want to wait for an official patch. Just replace the file at youtube_dl/extractor/chaturbate.py
> The changes are on lines 43 through 48 if you are worried about the security of the changes.
> [chaturbate.zip](https://github.com/ytdl-org/youtube-dl/files/3826008/chaturbate.zip)

Thanks! It works!

**Comment by cb123321** [comment]
@r33bow Thank you! <3

**Comment by donmiyamar** [comment]
@r33bow and others - any thought on how to apply this change to a Windows box? I can't swap that file when using the `.exe`

**Comment by donmiyamar** [comment]
@r33bow fix works on Windows too, but you have to use source and not the binary.

1. Install Python for Windows
2. Install `git`
3. Clone this project repo `git clone https://github.com/ytdl-org/youtube-dl/`
4. `cd youtube-dl`
5. Execute to confirm the same problem as the binary `python -m youtube_dl [URL_HERE]`
6. You should get the same result as you were getting with the binary
7. Replace the `./extractor/chaturbate.py` file with the one provided by @r33bow 
8. Re-run the command `python -m youtube_dl [URL_HERE]`
9. Should work!

**Comment by jeffkerby** [comment]
I cannot seem to locate the path to replace the chaturbate.py on my Ubuntu box, where is this located?

**Comment by asdasddffgthhjtreresf** [comment]
> I cannot seem to locate the path to replace the chaturbate.py on my Ubuntu box, where is this located?

/usr/lib/python3/dist-packages/youtube_dl
or different python version folder on /usr/lib/

**Comment by jeffkerby** [comment]
Thanks, I dropped it in there and replaced the file, restarted the server and still nothing.

**Comment by asdasddffgthhjtreresf** [comment]
Oh. The full path is /usr/lib/python3/dist-packages/youtube_dl/extractor
so you need to put it in the extractor folder. And make sure it has 644 permissions (rw-r-r).

**Comment by kamikaze87** [comment]
noob here, how can i apply this temporary fix in a raspbian (raspberry pi 4 ) installation?
i tried to find the youtube-dl folder but i only find a file  named youtube-dl in /usr/local/bin/

**Comment by therixor** [comment]
i replaced it but it still wont work for some reason...

**Comment by biodrone** [comment]
@kamikaze87 if you run `pip show youtube-dl` (or use `pip3` depending on how you've installed it) it should show a location parameter.

**Comment by kamikaze87** [comment]
With both it gives me command not found, i installed it with the curl command, its the first option from here https://ytdl-org.github.io/youtube-dl/download.html

**Comment by r33bow** [comment]
This won't work if you run it from binaries (e.g. exe). You have to run it via python from source using steps described in the linked post. Similar steps should work on any operating system. 
https://github.com/ytdl-org/youtube-dl/issues/23010#issuecomment-552109045

**Comment by biodrone** [comment]
Yeah @kamikaze87, run `sudo rm /usr/local/bin/youtube-dl`and then either follow the steps in the comment above or the pip installation steps from that link if you want to be able to patch it this way.

**Comment by kamikaze87** [comment]
Thank you, installed with pip, applied the fix and its working

**Comment by jeffkerby** [comment]
Unfortunately, nothing seems to work. 

Followed everything and placed the chaturbate.py in the /usr/lib/python2.7/dist-packages/youtube_dl/extractor directory and set permissions to 644. Everything still shows offline.

**Comment by Ubernoob7** [comment]
Same here... I think we will need to wait for a real patch for a fix

**Comment by therixor** [comment]
tryed it with the fix and it worked with python3.5 but not with python3.4, no idea why...

**Comment by biodrone** [comment]
Interesting, it worked for me using 3.7.5.

**Comment by petercheat** [comment]
for those who can not apply the patch, a workaround is to insert the cookie "cb_legacy=1"

for example:
youtube-dl --add-header "Cookie:cb_legacy=1" https://chaturbate.com/model/

I am not sure how long this will work.

**Comment by brendoncdrew** [comment]
Thx... fix workes for me as well
