### ISSUE TITLE
News Corp Australia Websites

### ISSUE THREAD

**Issue by rsfinlayson** [ytdl-org/youtube-dl#23024]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

https://www.couriermail.com.au/news/queensland/full-list-of-alerts-and-evacuations-for-bushfires/news-story/ca318b6b127eec26e30c18199f1ff1ac

## Description

Plays in Firefox.  youtube-dl fails with "Not Found"

**Comment by remitamine** [comment]
URL from #23025:
https://www.news.com.au/national/queensland/bushfires-tear-through-homes-and-rage-through-to-saturday-morning-live-updates/news-story/ee562f9338946141e80b34210426c2b0
