### ISSUE TITLE
cant download techtalk video

### ISSUE THREAD

**Issue by samreenkazi** [ytdl-org/youtube-dl#23044]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

**I **am trying to download video from techtalk**** 
_http://techtalks.tv/talks/a-thorough-examination-of-the-cnndaily-mail-reading-comprehension-task/63222/_
**but i am getting following error**
(base) webscience@WS-PC:~$ youtube-dl -v http://techtalks.tv/talks/a-thorough-examination-of-the-cnndaily-mail-reading-comprehension-task/63222/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://techtalks.tv/talks/a-thorough-examination-of-the-cnndaily-mail-reading-comprehension-task/63222/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.7.3 (CPython) - Linux-4.15.0-66-generic-x86_64-with-debian-buster-sid
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[TechTalks] 63222: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'rtmp://webcast.weyond.com/vod'
[download] Destination: A Thorough Examination of the CNN_Daily Mail Reading Comprehension Task-63222.flv
[debug] rtmpdump command line: rtmpdump --verbose -r rtmp://webcast.weyond.com/vod -o 'A Thorough Examination of the CNN_Daily Mail Reading Comprehension Task-63222.flv.part' --playpath acl/2016/mp4:d4_audimax_t1.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : webcast.weyond.com
[rtmpdump] DEBUG: Parsed app     : vod
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : webcast.weyond.com
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : acl/2016/mp4:d4_audimax_t1.mp4
[rtmpdump] DEBUG: tcUrl    : rtmp://webcast.weyond.com:1935/vod
[rtmpdump] DEBUG: app      : vod
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] Downloaded 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : webcast.weyond.com
[rtmpdump] DEBUG: Parsed app     : vod
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : webcast.weyond.com
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : acl/2016/mp4:d4_audimax_t1.mp4
[rtmpdump] DEBUG: tcUrl    : rtmp://webcast.weyond.com:1935/vod
[rtmpdump] DEBUG: app      : vod
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "/home/webscience/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/webscience/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 862, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1643, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1925, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1864, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 213, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 586, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by remitamine** [comment]
can play the video in the browser, for me Flowplayer fails to make connection with the `webcast.weyond.com` domain(Timeout).

**Comment by pathansaira7** [comment]
I have tried opening it in browser but jt kept loading Forver
