### ISSUE TITLE
Small thing but can you change the documentation?

### ISSUE THREAD

**Issue by mgnica** [ytdl-org/youtube-dl#23046]
## Checklist

For the sample command can you change it from "youtube-dl [OPTIONS] URL [URL...]" to "youtube-dl [OPTIONS] [URL...]" to avoid confusion? Thank you for making this tool it's a really good work.

**Comment by dstftw** [comment]
No, cause your suggestion is invalid.

**Comment by mgnica** [comment]
hey man, it's not a big deal but it would've saved me 10min, other people may be affected, and it would take you 2 seconds to fix it?

**Comment by dstftw** [comment]
Again: bother to learn what does `[]` mean.
