### ISSUE TITLE
"Did not get any data blocks" kills the entire list download.

### ISSUE THREAD

**Issue by vinaykapadia** [ytdl-org/youtube-dl#23041]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

I've searched and found people talking about the "did not get any data blocks" error. Says it's something to do with Youtube's CDN not having that format and to try a different format. That's great, I'll do that. But my problem is that reaching this error kills the entire playlist download. I'm trying to download a Youtube playlist of 120 videos. It gets the first 23 fine, then hits the error on video 24. But then it doesn't continue with video 25, the whole thing just dies and no more videos are downloaded.

Workaround is to add "--playlist-start 25" to the command. But then when the error happens again on video 49, it dies again. It's really annoying having to restart the list every time this error pops up.

**Comment by dstftw** [comment]
```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
```

**Comment by vinaykapadia** [comment]
Ah, that worked great! I feel this should be default behavior but oh well, as long as there's an option. I'll just add it to my config. Thanks!
