### ISSUE TITLE
How can i download mp4 file from mpd manifest with youtube-dl?

### ISSUE THREAD

**Issue by zenlykoi** [ytdl-org/youtube-dl#23048]
I want to download video from a website("https://www.paravi.jp/").

I got some mpd link [https://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/bccenc/5522450841001/d817af3f-0686-4762-9b2d-5a45a20917cf/2s/manifest.mpd?fastly_token=NWRjOTZlMTFfMjQ2MDM1MmVmNjlmZWI5YjhiMGU1OTAyYmJhNzgwN2E4ZjM0MTg1YzM1OGNhZjg2MTMzOTkwZTE5ZjY1MTlkYg%3D%3D](https://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/bccenc/5522450841001/d817af3f-0686-4762-9b2d-5a45a20917cf/2s/manifest.mpd?fastly_token=NWRjOTZlMTFfMjQ2MDM1MmVmNjlmZWI5YjhiMGU1OTAyYmJhNzgwN2E4ZjM0MTg1YzM1OGNhZjg2MTMzOTkwZTE5ZjY1MTlkYg%3D%3D)

And i using youtube-dl to download mp4 from it

`youtube-dl -F -v link.mpd`

But i can't download it, and i got some log : 

`$ youtube-dl -F -v https://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/bccenc/5522450841001/d817af3f-0686-4762-9b2d-5a45a20917cf/2s/manifest.mpd?fastly_token=NWRjOTZlMTFfMjQ2MDM1MmVmNjlmZWI5YjhiMGU1OTAyYmJhNzgwN2E4ZjM0MTg1YzM1OGNhZjg2MTMzOTkwZTE5ZjY1MTlkYg%3D%3D
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/bccenc/5522450841001/d817af3f-0686-4762-9b2d-5a45a20917cf/2s/manifest.mpd?fastly_token=NWRjOTZlMTFfMjQ2MDM1MmVmNjlmZWI5YjhiMGU1OTAyYmJhNzgwN2E4ZjM0MTg1YzM1OGNhZjg2MTMzOTkwZTE5ZjY1MTlkYg%3D%3D']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2019-10-18-feaec3b, ffprobe git-2019-10-18-feaec3b
[debug] Proxy map: {'http': 'http://114.156.4.252:8080', 'ftp': 'ftp://114.156.4.252:8080', 'https': 'https://114.156.4.252:8080'}
[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\generic.py", line 2395, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

Help me pls!

**Comment by HV00007** [comment]
Hey did you get to know how to download this kind of link?

**Comment by 89z** [comment]
please post new issue
