### ISSUE TITLE
[Soundcloud] 401 Unauthorised error on SOME songs

### ISSUE THREAD

**Issue by pitsi** [ytdl-org/youtube-dl#23045]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
$ youtube-dl -v https://soundcloud.com/oneireuthslowbap/murizeixoma
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://soundcloud.com/oneireuthslowbap/murizeixoma']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.7.5 (CPython) - Linux-5.3.0-2-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[soundcloud] oneireuthslowbap/murizeixoma: Downloading info JSON
[soundcloud] 36316542: Downloading JSON metadata
[soundcloud] 36316542: Downloading JSON metadata
[soundcloud] 36316542: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://api.soundcloud.com/tracks/36316542/download?client_id=BeGVhOrGmfboy1LtiHTQF6Ejpt9ULJCI'
ERROR: unable to download video data: HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 1925, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 1864, in dl
    return fd.download(name, info)
  File "/usr/lib/python3/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3/dist-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/lib/python3/dist-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

```
## Description
As I have written on the title, some songs fail to download with the above error. More urls that return the same output, all from the same artist
```
https://soundcloud.com/oneireuthslowbap/exostis
https://soundcloud.com/oneireuthslowbap/black-rose-jam
https://soundcloud.com/oneireuthslowbap/sundy-alithia
```
Statistically, 1 out of 2 or 3 songs from him fails to download.

**Comment by romanrm** [comment]
Has this been fixed? Still getting the error in the current version 2019.11.22

**Comment by n3r0t** [comment]
> 
> 
> Has this been fixed? Still getting the error in the current version 2019.11.22

doesn't work here either, ytdl is up to date and all

```
D:\youtube_d>youtube-dl -U
youtube-dl is up-to-date (2019.11.22)

D:\youtube_d>youtube-dl -v https://soundcloud.com/prxpvne/v4nt4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://soundcloud.com/prxpvne/v4nt4']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.11.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2019-11-26-59d264b, ffprobe git-2019-11-26-59d264b
[debug] Proxy map: {}
[soundcloud] prxpvne/v4nt4: Downloading info JSON
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[soundcloud] prxpvne/v4nt4: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

**Comment by nimitdesai** [comment]
This seems to be change that SoundCloud made. I currently use SoundCloud Playlist Sync to download all songs from a playlist. It was working fine not too long ago. But I started getting 401 errors as well using that program.

**Comment by pitsi** [comment]
I confirm that too. I just had the time to test with the above songs and it seems soundcloud fails again with a similar output
```
$ youtube-dl -v https://soundcloud.com/oneireuthslowbap/murizeixoma
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://soundcloud.com/oneireuthslowbap/murizeixoma']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.22
[debug] Python version 3.7.5 (CPython) - Linux-5.3.0-2-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[soundcloud] oneireuthslowbap/murizeixoma: Downloading info JSON
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[soundcloud] oneireuthslowbap/murizeixoma: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```
I can not reopen this issue though, because it was closed by a youtube-dl dev, so please feel free to open a new one and refer to it. And yes, soundcloud seems to be making changes again.

**Comment by jterry21** [comment]
Mine is doing is the same thing. 

> I confirm that too. I just had the time to test with the above songs and it seems soundcloud fails again with a similar output
> 
> ```
> $ youtube-dl -v https://soundcloud.com/oneireuthslowbap/murizeixoma
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['-v', 'https://soundcloud.com/oneireuthslowbap/murizeixoma']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2019.11.22
> [debug] Python version 3.7.5 (CPython) - Linux-5.3.0-2-amd64-x86_64-with-debian-bullseye-sid
> [debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
> [debug] Proxy map: {}
> [soundcloud] oneireuthslowbap/murizeixoma: Downloading info JSON
> WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
> [soundcloud] oneireuthslowbap/murizeixoma: Downloading info JSON
> ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>   File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2237, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/usr/lib/python3.7/urllib/request.py", line 531, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python3.7/urllib/request.py", line 569, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> ```
> 
> I can not reopen this issue though, because it was closed by a youtube-dl dev, so please feel free to open a new one and refer to it. And yes, soundcloud seems to be making changes again.

**Comment by pitsi** [comment]
@jterry21 
What version are you on? No issues here, on youtube-dl 2019.11.28.
The above was tested 5 minutes ago here, at 10.30 am local time (gmt+2) and it works fine
```
$ youtube-dl -v https://soundcloud.com/oneireuthslowbap/murizeixoma
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://soundcloud.com/oneireuthslowbap/murizeixoma']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.7.5 (CPython) - Linux-5.3.0-3-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[soundcloud] oneireuthslowbap/murizeixoma: Downloading info JSON
[soundcloud] 36316542: Downloading JSON metadata
[soundcloud] 36316542: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://cf-media.sndcdn.com/KX8GRw6Ktrcq.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vS1g4R1J3Nkt0cmNxLjEyOC5tcDMiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NzU5NjczNDB9fX1dfQ__&Signature=WhW9xS5sN5hbI-C4VEliqO8djVrZ14dGcdcr8mVS2EzG9HsjJBQuwvJp~PIVC4HRF5k~JPurWy5cQlwAZAe~Ji52zV1h2UV2EkGFMugFioWDeRtFU7z0avNdG9JZf2Yx-U8LYawYByANPFF9MMFHNts3SRQ9Gt65PgYGfWkyvtXh9I~FQDDmrE5MDnor8mRvUC9msoPNuv~lcIo2GxkmXXm4laco8BASoQmfBEykY49ho8a6-w3Mkr0WCw6OjbN3315u0Jb2C53K7ehvKbTVIFRWMLdT19zGfnEczSdp1dgb-hFLvlvXuJJsdLq8LEWot5kw~i44QuSjipjfAsHjAw__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ'
[download] Destination: Ονειρευτής - Μυρίζει χώμα [Συμμ. SunD] (7'' vinyl)-36316542.mp3
[download] 100% of 3.41MiB in 00:16
```

**Comment by tntmod54321** [comment]
Same issue here.
`youtube-dl https://soundcloud.com/zalinki/about-my-deleted-music --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://soundcloud.com/zalinki/about-my-deleted-music', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.12.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[soundcloud] zalinki/about-my-deleted-music: Downloading info JSON
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[soundcloud] zalinki/about-my-deleted-music: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default`
