### ISSUE TITLE
Limited time streeming recording

### ISSUE THREAD

**Issue by gioreva** [ytdl-org/youtube-dl#23047]
Hi.
Use a timer to start recording from TV, from a streaming flow.
Finished the event I closed youtube-dl with kill.
I believe that by doing so the index is corrupted during playback says a total wrong time.
There is a better way to do that?

**Comment by dstftw** [comment]
Terminate it normally with sigint obviously.

**Comment by gioreva** [comment]
I use dos.
taskkill /f /im youtube-dl.exe
I don't find the sigint command on dos.
I use / f, but the player says a wrong time playng the recordings.
