### ISSUE TITLE
[PornHub] Option to also download highest video quality available: 1080p free videos

### ISSUE THREAD

**Issue by github-userx** [ytdl-org/youtube-dl#23050]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.11.05**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed 

## Description

Currently we only can get max. 720p of free Videos although pornhub provides 1080p also for free videos.

**Comment by ajj8** [comment]
fixed with this #23082
