### ISSUE TITLE
Batch to different folders

### ISSUE THREAD

**Issue by LTGM** [ytdl-org/youtube-dl#23058]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

I have few links that need to be downloaded including some links to channels, how can I input them all at once (maybe using txt file) and download them to separate folders named after their respectful channels?

**Comment by remitamine** [comment]
1. 
```
-a, --batch-file FILE            File containing URLs to download ('-' for
                                 stdin), one URL per line. Lines starting
                                 with '#', ';' or ']' are considered as
                                 comments and ignored.
```

2. https://github.com/ytdl-org/youtube-dl#output-template

all these answers can be found in the README.
so next time it would better to check there before posting here.
