### ISSUE TITLE
blob streamloverx.com urls support

### ISSUE THREAD

**Issue by hardevine** [ytdl-org/youtube-dl#23065]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

blob:streamloverx.com urls are not working, are they supported. Eg. blob:https://streamloverx.com/7e7e4ddc-0530-48ca-abef-2ed62849c0b9#VzsRWxmhVPoSXzrXfMGiu7JXB8WoVhGvtMfRWMsSY5RRtMnP8rsMVRZifLon

**Comment by hardevine** [comment]
Updated the issue, kindly mention what is required ?

**Comment by remitamine** [comment]
the URL you're trying does not exist, instead, post the original URL, not the blob URL.

**Comment by hardevine** [comment]
https://streamloverx.com/?id=Z3pPS3hpdXZ0QmQxWEljT2JMSGthbWoxVDBtMjJOM293TkFLQzVROFF2NW4rVW5DM1J2Q0NEZHRRSG1aWFhVdg==&title=Joker%20(2019)&desc=Crime,%20Drama,%20Thriller&image=https://img.streamloverx.com/upload/2019/10/poster-joker-2019.jpg&sub=%5B%5D

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free

**Comment by jforce** [comment]
My 5 cents ...
Another URL format is
https://streamloverx.com/?id=TlQ2ckpwb1FSS1dhSzUzSG15UkRVNE9DZTkzOFJoeExhaHVzUys0WXZNQT0%3D#slug=wO6wrlELjx
