### ISSUE TITLE
"Invalid response from youtube-dl."

### ISSUE THREAD

**Issue by soapstreams** [ytdl-org/youtube-dl#23070]
- [x] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2019.11.05**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

[2019-11-12 01:14:01] Starting new import 13441735
[2019-11-12 01:14:01] Starting import thread 1
[2019-11-12 01:15:01] 100% done

[Thread  1] [2019-11-12 01:14:01] Started import 13441735
[Thread  1] [2019-11-12 01:14:01] Started line #1
[Thread  1] [2019-11-12 01:14:01] Grabbing gallery https://www.youtube.com/watch?v=FSZLwFjiKvo&list=PLV-jnXv3eCNMXVyWL9SA33rDPN2GV-eaF&index=2&t=0s...
[Thread  1] [2019-11-12 01:14:01] Using grabber youtube.com
[Thread  1] [2019-11-12 01:14:40] ERROR: video page gives unexpected error:Invalid response from youtube-dl
[Thread  1] [2019-11-12 01:14:40] Finished

## Description

I am using Kernel Video Sharing script grabber plugin and when I try to import videos from youtube, I see: "ERROR: video page gives unexpected error:Invalid response from youtube-dl." I have emailed KVS support, but they say this is a bug with youtube-dl. Anybody know what this could be? Thanks.

**Comment by remitamine** [comment]
most likely:
- you're using an outdated version of youtube-dl.
- you're IP has been banned by youtube.com.
- it's a problem with KSV.
anyway you have to provide a verbose output of a youtube-dl command(using the latest version), that demonstrates the actual problem.
