### ISSUE TITLE
Problem with JSON file-creation?

### ISSUE THREAD

**Issue by jdr7181** [ytdl-org/youtube-dl#23077]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

If I am only limited to one question, here it is: can somebody please confirm for me that there are no known issues with the JSON files created by youtube-dl? According to the folks at KVS, youtube-dl is creating JSON files that are not valid and cannot be parsed. Firefox has a built-in JSON parser and when you open the JSON files created by youtube-dl (when --dump-json option is used) in Firefox, you can clearly see the JSON files are not valid.

I tried to get help for this, but my request for assistance was closed without any help at all. I have searched the issues board and I can't find any other posts related to this particular issue where the JSON files can't be parsed because they are not valid.

Am I allowed to ask more than one question. If not, please ignore this question, but if possible can someone please help me understand why the moderators for the issues board are so hostile and unhelpful?

**Comment by dstftw** [comment]
Do you read what is addressed to you at all?

**Comment by jdr7181** [comment]
You must have me confused with someone. I have received one and only one response of any substance (from remitamine). And, again, it said I was either "using an outdated version of youtube-dl," which I am clearly NOT; or that my "IP has been banned by youtube.com," which it has absolutely NOT; or "its a problem with KVS." According to KVS, the problem is the JSON youtube-dl creates when you use the --dump-json option aren't valid and can't be parsed. And you don't need KVS to show this. Open the JSON file with Firefox.

What has been addressed to me? My first post was closed by you yesterday with NO response at all. Remitamine responded to my second and I have addressed that. It was promptly closed, too. My third was you claiming "you've been already answered." The fourth one you closed without responding and banned me. And now this one, where you claim I don't read what is addressed to me. What are you talking about?

**Comment by jdr7181** [comment]
You must have me confused with someone. I have received one and only one response of any substance (from remitamine). And, again, it said I was either "using an outdated version of youtube-dl," which I am clearly NOT; or that my "IP has been banned by youtube.com," which it has absolutely NOT; or "its a problem with KVS." According to KVS, the problem is the JSON youtube-dl creates when you use the --dump-json option aren't valid and can't be parsed. And you don't need KVS to show this. Open the JSON file with Firefox.
What has been addressed to me? My first post was closed by you yesterday with NO response at all. Remitamine responded to my second and I have addressed that. It was promptly closed, too. My third was you claiming "you've been already answered." The fourth one you closed without responding and banned me. And now this one, where you claim I don't read what is addressed to me. What are you talking about?
    On Wednesday, November 13, 2019, 01:23:15 AM EST, Sergey M. <notifications@github.com> wrote:  
 
 
Do you read what is addressed to you at all?

**Comment by dstftw** [comment]
Huh?
1. #23069. You ignored new issue template though there is a clear statement IN CAPS that such issues will be closed as incomplete.
2. #23070. You ignored new issue template again and have been [pointed out](https://github.com/ytdl-org/youtube-dl/issues/23070#issuecomment-553111791) by @remitamine to provide verbose log that demonstrates the actual problem.
3. #23075. You ignored comment from previous thread and posted useless log of successful run. You have been [pointed out](https://github.com/ytdl-org/youtube-dl/issues/23075#issuecomment-553253298) again to post proper verbose log.
4. #23076. You ignored it fouth time.
5. #23077. You ignored it fifth time.

And after that you're asking why support is so unhelpful? Stop ignoring us and provide what you're requested to provide. There are no telepathists to solve problems without clear evedence of them happening. `--dump-json` produces perfectly valid JSON for each playlist item. If it does not for you then you must prove that with verbose log.
