### ISSUE TITLE
bilibli some url not support

### ISSUE THREAD

**Issue by Jason-Liu-Dream** [ytdl-org/youtube-dl#23074]
## Checklist

- [ ] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [ ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs
youtube-dl http://www.bilibili.com/video/av13954517 -J

## Description

WRITE DESCRIPTION HERE
ERROR: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Video is no longer available.
