### ISSUE TITLE
Can't download video from YouTube

### ISSUE THREAD

**Issue by WillPittenger** [ytdl-org/youtube-dl#23081]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question
I've been trying to download https://www.youtube.com/watch?v=UvQUKp07HxA.  Unfortunately, if I specify the format [mp4], I get errors downloading the entire file.  It starts and then almost immediately dies with "ERROR: Did not get any data blocks".  If I switch to [webm] (the only other option), I'm told the format isn't available.  But I browsed the list of formats in the json and found both mp4 and webm up to 1080p.

So why can't I download the video?

WRITE QUESTION HERE

**Comment by WillPittenger** [comment]
Why is it incomplete?  What am I missing?

**Comment by WillPittenger** [comment]
This is what I see:

``
PS C:\> youtube-dl.exe https://www.youtube.com/watch?v=UvQUKp07HxA -o "H:\YouTube Videos\2020 Supra Street Hunter by TJ
Hunt Part 11.%(ext)s" -f "[height<=1080][ext=mp4]"
[youtube] UvQUKp07HxA: Downloading webpage
[youtube] UvQUKp07HxA: Downloading video info webpage
[download] Destination: H:\YouTube Videos\2020 Supra Street Hunter by TJ Hunt Part 11.mp4
[download]   0.3% of 237.04MiB at  1.28MiB/s ETA 03:05 [download] Got server HTTP error: Downloaded 648596 bytes, expect
ed 248553454 bytes. Retrying (attempt 1 of 10)...
ERROR: unable to download video data: HTTP Error 404: Not Found
PS C:\> del 'H:\YouTube Videos\*11.mp4.part'
PS C:\> youtube-dl.exe https://www.youtube.com/watch?v=UvQUKp07HxA -o "H:\YouTube Videos\2020 Supra Street Hunter by TJ
Hunt Part 11.%(ext)s" -f "[ext=webm]"
[youtube] UvQUKp07HxA: Downloading webpage
[youtube] UvQUKp07HxA: Downloading video info webpage
ERROR: requested format not available
PS C:\>

**Comment by WillPittenger** [comment]
Well I got it downloading by specifying the desired format id, 248, directly.  I still don't understand why I couldn't specify the webm extension in -f.

**Comment by dstftw** [comment]
There is no `best` format with `ext=webm` as clearly stated in the error message.

**Comment by WillPittenger** [comment]
Huh?  It looks like it when I look at the json.
