### ISSUE TITLE
Youtube-dl download being blocked

### ISSUE THREAD

**Issue by sabihalam** [ytdl-org/youtube-dl#23089]
## Checklist

- [ x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I am using Youtube-dl to download a large number of videos. Is there a way for me to use my existing Google API "YouTube Data API v3" key with youtube-dl so that my ip address doesn't get blocked? If not, is there some other way to proceed?

WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests

**Comment by remitamine** [comment]
no, youtube-dl does not use `Youtube Data API`.
