### ISSUE TITLE
What did youtube-dl-server do?

### ISSUE THREAD

**Issue by ljd1996** [ytdl-org/youtube-dl#23080]
I am doing youtube cracking on my mobile phone via [Termux](https://github.com/termux/termux-app).
I refer to the practice of [#13122](https://github.com/ytdl-org/youtube-dl/issues/13122) and run the youtube-dl-server on my phone and then connect it via http, the speed of cracking is indeed faster, but on some phones is still relatively slow. (For some reason, I cannot run the youtube-dl-server on my server)
I want to know what youtube-dl-server did, because I am not good at python. Does the python module only load once in multiple cracks? 
Then through the way of the youtube-dl-server, what is the reason that affects my speed of cracking besides network and machine performance?

**Comment by remitamine** [comment]
`youtube-dl-api-server` is not part of the youtube-dl project, address your question to the relevant project.
