### ISSUE TITLE
Logging in HTTP Error 404

### ISSUE THREAD

**Issue by xCSxXenon** [ytdl-org/youtube-dl#23090]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\j.lewis>youtube-dl.exe -v -u xCSxXenon -p vip3rman https://roosterteeth.com/watch/ah-animated-2019-11-14
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://roosterteeth.com/watch/ah-animated-2019-11-14']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-93884-g96c79d4e1f
[debug] Proxy map: {}
[RoosterTeeth] Downloading login page
[RoosterTeeth] Logging in
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

If I run youtube-dl with just the URL, it works and says I need to be a FIRST member. When I use -u and -p to use my credentials, the above output is what results when forwarding the credentials. I have tried may configurations, but they all result in the 404 error on the logging in step. It does work if I extract the cookies and use that with --cookies, but I would of course prefer -u and -p.

**Comment by xCSxXenon** [comment]
Where is that fixed?

**Comment by remitamine** [comment]
e9b95167af3f9cacd16e379a40bacb27999840b9, wait for the next version.

**Comment by xCSxXenon** [comment]
Thank you! The discrepancy is age and verbose logs seemed to high to be a duplicate, apologies!
