### ISSUE TITLE
How do I extract audio and pipe it to to qaac.exe

### ISSUE THREAD

**Issue by nickbe** [ytdl-org/youtube-dl#23104]
OS is windows. 

I want to download the best audio quality available (opus over aac) and then pipe the output to qaac.exe to create an m4a.

Also I'd like to ask i there's an option to set the ffmpeg aac codec to -q:a 2

**Comment by dstftw** [comment]
You can't do that with extract audio. Download `bestaudio` directly.

**Comment by nickbe** [comment]
Can I at least set the -q:a parameter of the ffmpeg.exe or make it use .libfdk_aac ?
