### ISSUE TITLE
Bug when piping under windows

### ISSUE THREAD

**Issue by nickbe** [ytdl-org/youtube-dl#23103]
The command 
`youtube-dl.exe --ignore-errors --verbose -x "%URL%"" --extract-audio -o  - `
is supposed to send the output to stdout, but instead I always get a file.
Bug or wrong syntax?

**Comment by dstftw** [comment]
You can't use `-x` with `-o -`.

**Comment by nickbe** [comment]
So how do I extract audio and pipe it to for example qaac.exe

**Comment by nickbe** [comment]
> You can't use `-x` with `-o -`.

So how can I extract and pipe the result? I mean why would I pipe without extracting something?
