### ISSUE TITLE
New Terms from Youtube

### ISSUE THREAD

**Issue by Primatebuddy** [ytdl-org/youtube-dl#23111]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [] I've searched the bugtracker for similar questions including closed ones

## Question

Youtube is activating their new terms of service on December 10. Has any research been done as to the usage of youtube-dl as it relates to the new terms? Specifically, will there be greater risk of IP ban or account ban with use of youtube-dl? Additionally, are there features that are in the works to mask downloads as ordinary use?

**Comment by Primatebuddy** [comment]
> Additionally, are there features that are in the works to mask downloads as ordinary use?

What I should have said is; **are there features that will work to mask downloads as ordinary use, given the new terms?**

**Comment by dstftw** [comment]
What concretely? Downloading is against their ToS, nothing changed here. And there is nothing to mask as youtube-dl works the same way browser does.

**Comment by Dishwasha** [comment]
IANAL but I would actually disagree with this assessment.  Download is only not allowed except as expressly authorized by the Service.  "You may view or listen to Content for your personal, non-commercial use" is expressly authorized.  The TOS does not specify how the content can be viewed or listened to.  There is no definition in the TOS that differentiates what constitutes a "download".
