### ISSUE TITLE
error: fixed output name but more than one file to download

### ISSUE THREAD

**Issue by toppits** [ytdl-org/youtube-dl#23115]
## Checklist
- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question
Hi, using on win7 (64bit), and im no programmer by any means.

I'm trying to use this output format:

twitch %(fps)s- %(channel)s %(release_date)s - %(title)s ID %(id)s t-%(start_time)s

but it gives me the error: fixed output name but more than one file to download=time The system can't find the file. (translated).

I've tried the file without output and it downloads fine. What am i missing?

**Comment by indeedwatson** [comment]
Getting the same error on arch linux just trying to download any youtube video.

> 
> youtube-dl https://www.youtube.com/watch\?v\=BiWDsfZ3zbo                                             
> ERROR: fixed output name but more than one file to download

**Comment by toppits** [comment]
found the solution over google for whatever reason. The whole output needs to be enclosed in quotes (at least on windows)

**Comment by indeedwatson** [comment]
well that does nothing for me, i guess i'll open the same issue again?

**Comment by toppits** [comment]
well yea, you're on linux. Are you using single or double quotes?

**Comment by indeedwatson** [comment]
Okay I solved my issue, in the config file I had `-o` output set to a directory that contained spaces. I didn't realize directories in the config file should be escaped or wrapped in quotes, since this is usually not a problem with config files in most other programs.

**Comment by jimi-saarinen** [comment]
In linux systems

Escape spaces in filename like so:

youtube-dl "https://www.youtube.com/watch?v=3JHB235NJ" -o ~/Documents/This will break
youtube-dl "https://www.youtube.com/watch?v=3JHB235NJ" -o ~/Documents/This\ wont\ break
