### ISSUE TITLE
PornHub private videos, "ERROR: Unable to extract encoded url"

### ISSUE THREAD

**Issue by 0xF5F5F5** [ytdl-org/youtube-dl#23110]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose --cookies /mnt/c/Users/youtube/cookies-pornhub.txt <redacted private video URL>
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--cookies', '/mnt/c/Users/youtube/cookies-pornhub.txt', '<redacted private video URL>']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.7.3 (CPython) - Linux-4.4.0-18362-Microsoft-x86_64-with-debian-10.1
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs 5
[debug] Proxy map: {}
[PornHub] <redacted private video ID>: Downloading pc webpage
[PornHub] <redacted private video ID>: Downloading tv webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/pornhub.py", line 235, in _real_extract
    'encoded url').split(';')
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hi!
I've been having trouble lately downloading private videos from PornHub, ones from other users I am friended with.
This used to work well for me, but now it never works, and I get the same error. I have tried URLs of profile's private video pages (for example, https://www.pornhub.com/users/username/videos/private), as well as direct video URLs (like the one I used in this example, which look identical to any regular public video URL), and nothing works.
I have no reason to believe that PornHub is delivering a page that is different from the one I get in my browser, which does successfully playback the private video. I have also tried getting fresh cookies from my browser, but no change was noticed, and I have recently compared by using the old cookies file and the new one, and again, no difference.

**Comment by 0xF5F5F5** [comment]
How is it incomplete? Is it that I redacted the URL and video ID? This bug happens with any private video I have tested, so I thought it wasn't so important to post a porn video that I like on GitHub.

Should I write a URL of my own private video instead, and then anyone here on GitHub can friend me on PornHub in order to test my private videos? I'm OK with that.

**Comment by dstftw** [comment]
You must provide complete data sufficient for reproducing the problem including concrete URLs and concrete account credentials.

**Comment by 0xF5F5F5** [comment]
> concrete account credentials

I should publish account credentials on GitHub?

**Comment by 0xF5F5F5** [comment]
I looked at other issues like mine that involve access to videos that require credentials. The authors redacted their credentials and their issues were not closed due to that. Why do I get my issue closed for not publishing "concrete account credentials"?
