### ISSUE TITLE
Can't download udemy videos

### ISSUE THREAD

**Issue by Donboscow** [ytdl-org/youtube-dl#23114]
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

$youtube-dl --cookies cookie.txt https://www.udemy.com/course/asynchronous-javascript-deep-dive/
[udemy:course] course: Downloading webpage
[udemy:course] 2641732: Downloading course curriculum
[download] Downloading playlist: 2641732
[udemy:course] playlist 2641732: Collected 57 video ids (downloading 57 of them)
[download] Downloading video 1 of 57
[udemy] 16818326: Downloading webpage
[udemy] 16818326: Downloading lecture JSON
[udemy] 16818326: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Donboscow** [comment]
whats the problem? any update to fix this issues? Any eta? @dstftw

**Comment by Ex-Communicad0** [comment]
@Donboscow Have you downloaded this course? I also need this course
