### ISSUE TITLE
ERROR: No video formats found (Not geo-restricted)

### ISSUE THREAD

**Issue by tanymb1688** [ytdl-org/youtube-dl#23129]
## Checklist
- [x ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2019.11.05**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log
```
youtube-dl -v --proxy "" --sub-lang en --sub-format srt  -o "Law.of.the.Jungle.E380.1080p.WEB-DL.H264.AAC-KMX.mp4" https://www.viki.com/videos/1152589v-law-of-the-jungle-episode-380
[debug] System config: []
[debug] User config: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', '--write-sub', '--sub-lang', 'en', '--sub-format', 'srt', '--hls-prefer-native', '--fixup', 'never']
[debug] Custom config: []
[debug] Command-line args: ['-v', '--proxy', '', '--sub-lang', 'en', '--sub-format', 'srt', '-o', 'Law.of.the.Jungle.E380.1080p.WEB-DL.H264.AAC-KMX.mp4', 'https://www.viki.com/videos/1152589v-law-of-the-jungle-episode-380']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref cp65001
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2019-11-17-b741a84, ffprobe git-2019-11-17-b741a84, rtmpdump 2.4
[debug] Proxy map: {}
[viki] Logging in
[viki] 1152589v: Downloading video JSON
[viki] 1152589v: Downloading video streams JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\viki.py", line 319, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description
Previous episodes (E379 and before) may be downloaded, E380 onwards cannot be downloaded and reports "ERROR: No video formats found".

**Comment by remitamine** [comment]
getting this message in the browser:
> Sorry, this content is not available in your region.

**Comment by tanymb1688** [comment]
This resource is accessible using US and Canada IP.

**Comment by remitamine** [comment]
after using a VPN I'm getting this:
> Viki Pass Plus
This video is available only for Viki Pass Plus subscribers.

**Comment by tanymb1688** [comment]
I am using a Viki Pass Plus account.

**Comment by remitamine** [comment]
in order to fix the problem, developers have to be able to reproduce it first, so you must provide account credentials to one of the developers willing to work on this issue.

**Comment by tanymb1688** [comment]
I can provide that. Provide me the email contact of the developer.

**Comment by remitamine** [comment]
if someone is interested he can comment here, emails normally can be found in the developer's profile.

**Comment by bahboric** [comment]
I'm getting the same error message on some viki videos, but not all.  Here is the verbose output:
```
Malacandra:Doctor Detective ric$ youtube-dl -F --write-sub --sub-lang en -o "%(title)s.%(ext)s" -u MYUSERNAME -p MYPASSWORD --verbose https://www.viki.com/videos/1153014v-doctor-detective-episode-25
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'--write-sub', u'--sub-lang', u'en', u'-o', u'%(title)s.%(ext)s', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--verbose', u'https://www.viki.com/videos/1153014v-doctor-detective-episode-25']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.22
[debug] Python version 2.7.10 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-89883-gee88f31d34-tessus
[debug] Proxy map: {}
[viki] Logging in
[viki] 1153014v: Downloading video JSON
[viki] 1153014v: Downloading video streams JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/viki.py", line 319, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
I was able to download without trouble the first 14 episodes of this series, but get the error message starting at episode 25.

**Comment by bahboric** [comment]
Interestingly, I tried to download another series, and got the same message at file 25 (out of 60), just as before.  It is interesting that things would work fine and then stop working at the 25th video.

**Comment by manselmi** [comment]
I'm having what seems to be the same issue, even when downloading episode 1 of some show.  I'm using the current tip of `master` (2dbc0967f26425acc204395bc69c9446d9ebd682).

Command:

```
youtube-dl \
  --username <USERNAME> \
  --password <PASSWORD> \
  --sub-format vtt \
  --sub-langs en \
  --write-sub \
  --output 'Beautiful World, Wonderful Life - %(playlist_index)03d.%(ext)s' \
  --playlist-start 1 \
  --playlist-end 1 \
  --list-formats \
  --verbose \
  -- \
  https://www.viki.com/tv/36682c-beautiful-love-wonderful-life
```

Output:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--sub-format', 'vtt', '--sub-langs', 'en', '--write-sub', '--output', 'Beautiful World, Wonderful Life - %(playlist_index)03d.%(ext)s', '--playlist-start', '1', '--playlist-end', '1', '--list-formats', '--verbose', '--', 'https://www.viki.com/tv/36682c-beautiful-love-wonderful-life']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.7.5 (CPython) - Darwin-19.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[viki:channel] Logging in
[viki:channel] 36682c: Downloading channel JSON
[viki:channel] 36682c: Downloading episodes JSON page #1
[viki:channel] 36682c: Downloading episodes JSON page #2
[viki:channel] 36682c: Downloading clips JSON page #1
[viki:channel] 36682c: Downloading movies JSON page #1
[download] Downloading playlist: Beautiful Love, Wonderful Life
[viki:channel] playlist Beautiful Love, Wonderful Life: Collected 72 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[viki] Logging in
[viki] 1156619v: Downloading video JSON
[viki] 1156619v: Downloading video streams JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/manselmi/virtualenv/youtube-dl/lib/python3.7/site-packages/youtube_dl-2019.11.28-py3.7.egg/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/Users/manselmi/virtualenv/youtube-dl/lib/python3.7/site-packages/youtube_dl-2019.11.28-py3.7.egg/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Users/manselmi/virtualenv/youtube-dl/lib/python3.7/site-packages/youtube_dl-2019.11.28-py3.7.egg/youtube_dl/extractor/viki.py", line 319, in _real_extract
    self._sort_formats(formats)
  File "/Users/manselmi/virtualenv/youtube-dl/lib/python3.7/site-packages/youtube_dl-2019.11.28-py3.7.egg/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by manselmi** [comment]
To help developers with debugging, I've captured HTTP requests and responses of the following command using [`mitmproxy`](https://mitmproxy.org/).

Command (same as previous command except for `--proxy`):

```
youtube-dl \
  --username <USERNAME> \
  --password <PASSWORD> \
  --sub-format vtt \
  --sub-langs en \
  --write-sub \
  --output 'Beautiful World, Wonderful Life - %(playlist_index)03d.%(ext)s' \
  --playlist-start 1 \
  --playlist-end 1 \
  --list-formats \
  --verbose \
  --proxy https://localhost:8080 \
  -- \
  https://www.viki.com/tv/36682c-beautiful-love-wonderful-life
```

HTTP dump attached.  It may easily be viewed after decompressing with gzip by opening it with [`mitmweb`](https://docs.mitmproxy.org/master/tools-mitmweb/).  I redacted my Viki Pass credentials in the dump file.

[viki_mitmproxy.gz](https://github.com/ytdl-org/youtube-dl/files/3981013/viki_mitmproxy.gz)

**Comment by PranavBhattarai** [comment]
```
pranav@exam ~ [2]> youtube-dl -f bestaudio https://youtu.be/_HgzMhQTpOA
[youtube] _HgzMhQTpOA: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
pranav@exam ~ [1]> 
```
**Distro**: Ubuntu 20.04
**youtube-dl --version**: 2020.03.24

**Comment by r4z0r5** [comment]
Similar error while downloading a video with Python script. Definately not cause of law/country restrictions, downloading with German IP.
`    ydl_opts = {                                                                                                                                                                                                                              
        'verbose': True,                                                                                                                                                                                                                      
        'format': 'bestaudio/best',                                                                                                                                                                                                           
        'restrictfilenames':True,                                                                                                                                                                                                             
        'postprocessors': [{                                                                                                                                                                                                                  
            'key': 'FFmpegExtractAudio',                                                                                                                                                                                                      
            'preferredcodec': 'mp3',
            'preferredquality': '192'
}`
Traceback:
`ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include
 its complete output.
Traceback (most recent call last):
  File "/home/r4z0r5/Extract_yt_audio/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/r4z0r5/Extract_yt_audio/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/r4z0r5/Extract_yt_audio/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2364, in _real_extract
    self._sort_formats(formats)
  File "/home/r4z0r5/Extract_yt_audio/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the 
--verbose flag and include its complete output.
`

**Comment by akshatdevp** [comment]
Same error, have updated youtube-dl with pip as well. Trying to download from youtube. 
Worked a week ago, now unable to download anything, have tried 4-5 URLs
```ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "d:\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "d:\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "d:\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 2394, in _real_extract
    self._sort_formats(formats)
  File "d:\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by akshatdevp** [comment]
> 
> 
> Similar error while downloading a video with Python script. Definately not cause of law/country restrictions, downloading with German IP.
> ` ydl_opts = { 'verbose': True, 'format': 'bestaudio/best', 'restrictfilenames':True, 'postprocessors': [{ 'key': 'FFmpegExtractAudio', 'preferredcodec': 'mp3', 'preferredquality': '192' }`
> Traceback:
> `ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last): File "/home/r4z0r5/Extract_yt_audio/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info ie_result = ie.extract(url) File "/home/r4z0r5/Extract_yt_audio/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract ie_result = self._real_extract(url) File "/home/r4z0r5/Extract_yt_audio/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2364, in _real_extract self._sort_formats(formats) File "/home/r4z0r5/Extract_yt_audio/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats raise ExtractorError('No video formats found') youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. `

@r4z0r5 I had the same error, try updating youtube-dl with 
```python -m pip install youtube-dl --upgrade```
working for me.

**Comment by PranavBhattarai** [comment]
@akshatdevp Well, that too didn't work for me. As u can see it down below:
```
pranav@exam ~> python -m pip install youtube-dl --upgrade
Collecting youtube-dl
  Downloading youtube_dl-2020.6.16.1-py2.py3-none-any.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 620 kB/s 
Installing collected packages: youtube-dl
  WARNING: The script youtube-dl is installed in '/home/pranav/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed youtube-dl-2020.6.16.1
pranav@exam ~> youtube-dl -f bestaudio https://youtu.be/_HgzMhQTpOA
[youtube] _HgzMhQTpOA: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
pranav@exam ~ [1]> youtube-dl -f bestaudio https://www.youtube.com/watch?v=_HgzMhQTpOA&feature=youtu.be
fish: Unsupported use of '='. In fish, please use 'set feature youtu.be'.
pranav@exam ~ [1]> bash
pranav@exam:~$ youtube-dl -f bestaudio https://www.youtube.com/watch?v=_HgzMhQTpOA&feature=youtu.be
[1] 92542
pranav@exam:~$ [youtube] _HgzMhQTpOA: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by daniellasalle** [comment]
Not sure how/if that ever gotten fixed and the time is now July 2020 and this problem is still current.

**Comment by mlloreda** [comment]
@daniellasalle do you still run into issue if you install latest release (as prescribed in README)?

Can confirm issue still there for youtube-dl on Ubuntu 20.04 when installed via apt. But able to get around issue by downloading latest release binary.

**Comment by guest271314** [comment]
@PranavBhattarai 

`$ /home/pranav/.local/bin/youtube-dl <URL>`

**Comment by PranavBhattarai** [comment]
@guest271314 
Now I have 2 youtube-dl installed. I want to keep only the latest one. What to do?
![Screenshot from 2020-09-09 20-08-31](https://user-images.githubusercontent.com/32763112/92611394-7780aa00-f2d8-11ea-98a5-23bec8b12978.png)

**Comment by guest271314** [comment]
You should be able to uninstall the default package.

**Comment by PranavBhattarai** [comment]
@guest271314
I just did what you told using the command: `sudo apt remove --purge youtube-dl`. 
Now I have to go to **/home/pranav/.local/bin**directory every single time if I want to use youtube-dl.
Why can I just type `youtube-dl` from the default location (i.e /home/pranav)? Is there a way through which I can run youtube-dl command from default location?

**Comment by guest271314** [comment]
.@PranavBhattarai You should be able to add  `/home/pranav/.local/bin` to `PATH`.

**Comment by redactedscribe** [comment]
Seems `bandcamp.com/album/<album_name>` downloads do not work any more: `ERROR: No video formats found`.

`v2020.09.20`
