### ISSUE TITLE
Need help Downloading from Hotstar

### ISSUE THREAD

**Issue by kishan167** [ytdl-org/youtube-dl#23123]
## Checklist

- [ ] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

**- Single video:** https://www.hotstar.com/in/movies/nerukadi/1260013704/watch
**- Single Resolution 1080P:** https://hses1.akamaized.net/videos/movies/tamil/nerukadi/1260013704/1573725455858/69bf0fa13bbed7548aa1a2b7ed8a8385/media-6/index.m3u8

- **M3U8:**  https://hses1.akamaized.net/videos/movies/tamil/nerukadi/1260013704/1573725455858/69bf0fa13bbed7548aa1a2b7ed8a8385/master-phone.m3u8?ladder=phone&hdnea=st=1573957936~exp=1573961536~acl=/*~hmac=fbf6d9eb90d1266598fe7715cc8b6c5f762e5394fa56622c3833820537210e6b

## Description

**Getting Below Error WARNING: Could not send HEAD request to**
**youtube-dl -F **https://hses1.akamaized.net/videos/movies/tamil/nerukadi/1260013704/1573725455858/69bf0fa13bbed7548aa1a2b7ed8a8385/master-phone.m3u8?ladder=phone&hdnea=st=1573957936~exp=1573961536~acl=/*~hmac=fbf6d9eb90d1266598fe7715cc8b6c5f762e5394fa56622c3833820537210e6b
[generic] master-phone: Requesting header
WARNING: Could not send HEAD request to https://hses1.akamaized.net/videos/movies/tamil/nerukadi/1260013704/1573725455858/69bf0fa13bbed7548aa1a2b7ed8a8385/master-phone.m3u8?ladder=phone: HTTP Error 403: Forbidden
[generic] master-phone: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
'hdnea' is not recognized as an internal or external command,
operable program or batch file.

**youtube-dl -v** https://hses1.akamaized.net/videos/movies/tamil/nerukadi/1260013704/1573725455858/69bf0fa13bbed7548aa1a2b7ed8a8385/master-phone.m3u8?ladder=phone&hdnea=st=1573957936~exp=1573961536~acl=/*~hmac=fbf6d9eb90d1266598fe7715cc8b6c5f762e5394fa56622c3833820537210e6b
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://hses1.akamaized.net/videos/movies/tamil/nerukadi/1260013704/1573725455858/69bf0fa13bbed7548aa1a2b7ed8a8385/master-phone.m3u8?ladder=phone']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] **youtube-dl version 2019.11.05**
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[generic] master-phone: Requesting header
WARNING: Could not send HEAD request to https://hses1.akamaized.net/videos/movies/tamil/nerukadi/1260013704/1573725455858/69bf0fa13bbed7548aa1a2b7ed8a8385/master-phone.m3u8?ladder=phone: HTTP Error 403: Forbidden
[generic] master-phone: Downloading webpage
**ERROR: Unable to download webpage: HTTP Error 403: Forbidden** (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
'hdnea' is not recognized as an internal or external command,
operable program or batch file.

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
