### ISSUE TITLE
Need help:  ERROR: unable to downloa :urlopen error EOF occurred in violation of protocol (_ssl.c:600)

### ISSUE THREAD

**Issue by drsuchan** [ytdl-org/youtube-dl#23126]
I don't know where I go wrong...

> C:\Users\XXXX>youtube-dl -f bestvideo+bestaudio https://www.youtube.com/watch?v=jJ
C8AN91cUM
[youtube] jJC8AN91cUM: Downloading webpage
[youtube] jJC8AN91cUM: Downloading video info webpage
WARNING: Requested formats are incompatible for merge and will be merged into mk
v.
[download] Destination: Elsa Dress Transformation Compilation - Let It Go - Disn
ey's Frozen-jJC8AN91cUM.f137.mp4
[download]  15.0% of 63.33MiB at 302.61KiB/s ETA 03:02  ERROR: unable to downloa
d video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>

**Comment by YaoHuan123** [comment]
Dear,How did you solve the problem？
