### ISSUE TITLE
Need help: couldn't download with aria2

### ISSUE THREAD

**Issue by drsuchan** [ytdl-org/youtube-dl#23127]
I don't know where did I go wrong,But I couldn't ues youtube-dl with aria2.

Test 1
> C:\Users\XX>youtube-dl -o "H:\download\%(title)s.%(ext)s" https://www.youtube.com/watch?v=bH_v9oFvIck --external-downloader aria2c --external-downloader-args "-
x 5 -k 3M"
[youtube] bH_v9oFvIck: Downloading webpage
ERROR: Unable to download webpage: <urlopen error EOF occurred in violation of p
rotocol (_ssl.c:600)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violat
ion of protocol (_ssl.c:600)'),))

Test 2
> C:\Users\XXXX>youtube-dl https://www.youtube.com/watch?v=jJC8AN91cUM --external-do
wnloader aria2c --external-downloader-args "-x 16 -k 1M"
[youtube] jJC8AN91cUM: Downloading webpage
[youtube] jJC8AN91cUM: Downloading video info webpage
WARNING: Requested formats are incompatible for merge and will be merged into mk
v.
[download] Destination: Elsa Dress Transformation Compilation - Let It Go - Disn
ey's Frozen-jJC8AN91cUM.f137.mp4
11/17 15:13:17 [NOTICE] Downloading 1 item(s)
 *** Download Progress Summary as of Sun Nov 17 15:14:17 2019 ***
==============================================================================
[#1d29bc 0B/0B CN:1 DL:0B]
FILE: C:/Users/XXX/Elsa Dress Transformation Compilation - Let It Go - Disney's F
rozen-jJC8AN91cUM.f137.mp4.part
[#1d29bc 0B/0B CN:1 DL:0B]
11/17 15:15:02 [ERROR] CUID#7 - Download aborted. URI=https://r11---sn-axq7sn7l.
googlevideo.com/videoplayback?expire=1573996385&ei=APPQXYKlOYjh7gSX9ZzgDg&ip=185
.209.85.37&id=o-ANbgamyaTkVZLE0Ix7PvF9wh_QEiTyhJgqry9qL1mNvv&itag=137&aitags=133
%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtub
e&requiressl=yes&mm=31%2C26&mn=sn-axq7sn7l%2Csn-n8v7kn7s&ms=au%2Conr&mv=m&mvi=10
&nh=IgpwcjAxLmxlZDAzKgkxMjcuMC4wLjE%2C&pl=24&initcwndbps=1070000&mime=video%2Fmp
4&gir=yes&clen=66403027&dur=268.285&lmt=1572184659157181&mt=1573974697&fvip=11&k
eepalive=yes&fexp=23842630&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Cait
ags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRgIhAM3TvR
_CjxcxZeDCMqofpCvDcTf6FBkRhQwTbeKtnx5hAiEAmiUO4W55-P2nFIg9cGnd48y5dPVbBq77gsehxp
Zj5Ic%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cnh%2Cpl%2Cinitcwndbps&lsig=AHylml4wR
QIgXujTAq-eaMnde1WHiZu3SPToD-1-hAw10XWqRmdz0T0CIQCLxgBcHtVwoRdmtTfZH7Wxe0Z6lt9uQ
NxXZvFJK37h8g%3D%3D&ratebypass=yes
Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. ca
use:A connection attempt failed because the connected party did not properly res
pond after a period of time, or established connection failed because connected
host has failed to respond.
11/17 15:15:02 [NOTICE] Download GID#1d29bcc8aca259a1 not complete: C:/Users/XXX/
Elsa Dress Transformation Compilation - Let It Go - Disney's Frozen-jJC8AN91cUM.
f137.mp4.part
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
1d29bc|ERR |       0B/s|C:/Users/XXX/Elsa Dress Transformation Compilation - Let
It Go - Disney's Frozen-jJC8AN91cUM.f137.mp4.part
Status Legend:
(ERR):error occurred.
aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page
 for details.
ERROR: aria2c exited with code 1

**Comment by remitamine** [comment]
read the error message(it's either a network error on your side or from the server):
> Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. ca
use:A connection attempt failed because the connected party did not properly res
pond after a period of time, or established connection failed because connected
host has failed to respond.
