### ISSUE TITLE
What are the supported platforms besides youtube

### ISSUE THREAD

**Issue by sirkyuubi** [ytdl-org/youtube-dl#23134]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

I have a simple question that I couldn't find the answer for when I looked. What other platforms besides youtube does this work on? I couldn't find a supported platforms list.

**Comment by Hrxn** [comment]
https://github.com/ytdl-org/youtube-dl/blob/master/docs/supportedsites.md
