### ISSUE TITLE
drtv broken after rewrite of site

### ISSUE THREAD

**Issue by MBryde** [ytdl-org/youtube-dl#23150]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.11.05**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl https://www.dr.dk/drtv/se/mission_-eftersidning_146377 -v                                
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.dr.dk/drtv/se/mission_-eftersidning_146377', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.6.8 (CPython) - Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] mission_-eftersidning_146377: Requesting header
WARNING: Falling back on generic information extractor.
[generic] mission_-eftersidning_146377: Downloading webpage
[generic] mission_-eftersidning_146377: Extracting information
ERROR: Unsupported URL: https://www.dr.dk/drtv/se/mission_-eftersidning_146377
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/generic.py", line 3354, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.dr.dk/drtv/se/mission_-eftersidning_146377
```

## Description

https://dr.dk/tv has recently launched a rework of their streaming site. And in that rework they have broken the support for youtube-dl - so no matter what link you provide it will not download anything.

**Comment by MBryde** [comment]
NB: I know their is some closed issues marked as duplicates. But since we are still having this issue I don't understand why they get marked as duplicates. And commit / fix made here: https://github.com/ytdl-org/youtube-dl/issues/19039 don't seem to fix the newer issues people are having in regards to downloading for the site.

**Comment by MBryde** [comment]
@dstftw why do you keep closing issues like this. Their is still no fix for the bug we are having :(

**Comment by dstftw** [comment]
Stop posting duplicates and wait for the next release. Warned.
