### ISSUE TITLE
Extract one image from YouTube video with best quality

### ISSUE THREAD

**Issue by Didayolo** [ytdl-org/youtube-dl#23158]
- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

For YouTube videos containing only one picture (typically musics), it is possible to use youtube-dl to extract it with the best possible quality? How?

**Comment by dstftw** [comment]
That's default.

**Comment by Didayolo** [comment]
I don't get it... by default, ``youtube-dl`` download the target as a **video**, not an **image**.
