### ISSUE TITLE
Spectrum on demand isuue

### ISSUE THREAD

**Issue by opps123** [ytdl-org/youtube-dl#23165]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Is it possible to download video from https://watch.spectrum.net/ --on demand
If any one know how to I'll be happy to get help.

Thank you

**Comment by darkhelmet2016** [comment]
What information would you further  need to fix this error with spectrum on-demand?

**Comment by jjrice2233** [comment]
yes
