### ISSUE TITLE
bluecam support removed?

### ISSUE THREAD

**Issue by tab328** [ytdl-org/youtube-dl#23168]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
Microsoft Windows [Version 10.0.18362.476]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Utilities\youtube-dl>youtube-dl --version
2019.11.22

C:\Utilities\youtube-dl>youtube-dl -v https://bluecam.com/siswet19/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://bluecam.com/siswet19/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[generic] siswet19: Requesting header
WARNING: Falling back on generic information extractor.
[generic] siswet19: Downloading webpage
[generic] siswet19: Extracting information
ERROR: Unsupported URL: https://bluecam.com/siswet19/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\extractor\generic.py", line 3363, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://bluecam.com/siswet19/

```

## Description

bluecam.com is an ad-free derivative/copy of chaturbate.com. Used to work before recent chaturbate break https://github.com/ytdl-org/youtube-dl/commit/f0f6a7e73f55b6227c40af17c6fcab44b5a2df79 . Urls are identical to chaturbate EG https://bluecam.com/sia_siberia/ (fails) vs https://chaturbate.com/sia_siberia/ (downloads).

**Comment by dstftw** [comment]
https://bluecam.com/siswet19/ does not work. Nothing to do with commit mentioned.

**Comment by redacted1514** [comment]
Well, that said, it wasn't all that difficult to just detect and replace the domains in my script.

Perhaps I should've mentioned it's a livestream or just filed under new site support request since it seems to have been altogether removed.
