### ISSUE TITLE
HTTP Error 403

### ISSUE THREAD

**Issue by immostafa** [ytdl-org/youtube-dl#23175]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

I used this link to use this app to download Pluralsight videos, but I got an error:
https://www.quora.com/Tutorials-How-can-I-download-PluralSight-training-videos

when I run it in the Linux, I got this error:
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by candidodmv** [comment]
incomplete? What more type of information you need @dstftw ?
