### ISSUE TITLE
Request: Log the copyright-blocked error

### ISSUE THREAD

**Issue by Kubrix** [ytdl-org/youtube-dl#23178]
## Checklist

- [ X] I'm reporting a feature request
- [ X] I've verified that I'm running youtube-dl version **2019.11.22**
- [ X] I've searched the bugtracker for similar feature requests including closed ones

## Description

I am trying to download the enitire channel:

_youtube-dl  -v -i -f mp4 --yes-playlist https://www.youtube.com/playlist?list=UUep6EY7zkjn7uYSEqJktnhA > log.txt_

At some point I get the following message in the cmd

**youtube_dl.utils.ExtractorError: This video contains content from WMG, who has blocked it on copyright grounds. Sorry about that.**

I stopped the download by closing the application. Log.txt attached.
My question is: exactly what video failed to download because of the copyright block? I dont see any clues ion log.txt. Can you please add that info to Log.txt? I want to know which video I need to download manually.
[log.txt](https://github.com/ytdl-org/youtube-dl/files/3882254/log.txt)

**Comment by dstftw** [comment]
You must also redirect stderr to file.
Failed video is #3.
