### ISSUE TITLE
Is the windows compiled version supposed to be "2019.09.01" from the releases page instead of "2019.11.22" ?

### ISSUE THREAD

**Issue by am1ru1** [ytdl-org/youtube-dl#23183]
## Checklist

- [x ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Is the windows compiled version supposed to be "2019.09.01" from the releases page instead of "2019.11.22" ?

https://github.com/ytdl-org/youtube-dl/releases/download/2019.11.22/youtube-dl.exe

youtube-dl --version
2019.09.01

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          580F74BC64F2D73FB53BE2A1A1185D9426631479DCC4941B144DCA0F351FB920

**Comment by dstftw** [comment]
It's supposed to be 2019.11.22 and it is.
