### ISSUE TITLE
watch.tbn.tv add support for embed.vhx.tv vimeo 

### ISSUE THREAD

**Issue by nopedd** [ytdl-org/youtube-dl#23187]
## Checklist

- [ x] I'm reporting a new site support request
- [ x] I've verified that I'm running youtube-dl version **2019.11.22**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that none of provided URLs violate any copyrights
- [x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

C:\Users\cm>youtube-dl --no-check -v https://watch.tbn.tv/videos/huckabee-110
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check', '-v', 'https://watch.tbn.tv/videos/huc
kabee-110']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.11.22
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] huckabee-110: Requesting header
WARNING: Falling back on generic information extractor.
[generic] huckabee-110: Downloading webpage
[generic] huckabee-110: Extracting information
ERROR: Unsupported URL: https://watch.tbn.tv/videos/huckabee-110
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh
33\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh
33\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh
33\build\youtube_dl\extractor\generic.py", line 3363, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://watch.tbn.tv/videos/
huckabee-110

## Description

this site allows access with free account which provide if needed or free signup here  https://watch.tbn.tv/checkout/subscribe/signup

after signing up it provides vimeo embed link using vhx.embed

https://embed.vhx.tv/videos/656457?api=1&auth-user-token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMjA3MzI1NCwiZXhwIjoxNTc0NTM2MDc2fQ.0ICqJswbGCpFniWtg9yaEWvl0yAjgueMrQUK5WzGKxA&autoplay=1&back=Browse&buy_label=Register&color=ffffff&context=https%3A%2F%2Fwatch.tbn.tv%2Fbrowse&live=0&playsinline=1&referrer=https%3A%2F%2Fwatch.tbn.tv%2Fcheckout%2Fsubscribe%2Freceipt%3Freturn_to%3Dhttps%253A%252F%252Ftbn.vhx.tv%252Fvideos%252Fhuckabee-110&sharing=1&show_price=0&title=0&vimeo=1#

this can be got by signup for free account but when i put it youtube dl shown below i get this

C:\Users\cm>youtube-dl --no-check -v https://embed.vhx.tv/videos/656457?api=1&au
th-user-token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMjA3MzI1NCwiZXhwIjoxNTc0NTM2M
Dc2fQ.0ICqJswbGCpFniWtg9yaEWvl0yAjgueMrQUK5WzGKxA&autoplay=1&back=Browse&buy_lab
el=Register&color=ffffff&context=https%3A%2F%2Fwatch.tbn.tv%2Fbrowse&live=0&play
sinline=1&referrer=https%3A%2F%2Fwatch.tbn.tv%2Fcheckout%2Fsubscribe%2Freceipt%3
Freturn_to%3Dhttps%253A%252F%252Ftbn.vhx.tv%252Fvideos%252Fhuckabee-110&sharing=
1&show_price=0&title=0&vimeo=1#
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check', '-v', 'https://embed.vhx.tv/videos/656
457?api=1']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.11.22
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[vhx:embed] 656457: Downloading webpage
ERROR: Unable to extract ott data; please report this issue on https://yt-dl.org
/bug . Make sure you are using the latest version; type  youtube-dl -U  to updat
e. Be sure to call youtube-dl with the --verbose flag and include its complete o
utput.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh
33\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh
33\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh
33\build\youtube_dl\extractor\vimeo.py", line 1127, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh
33\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract ott data; please report t
his issue on https://yt-dl.org/bug . Make sure you are using the latest version;
 type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose f
lag and include its complete output.

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
```
youtube-dl 'https://embed.vhx.tv/videos/656457?api=1&auth-user-token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMjA3MzI1NCwiZXhwIjoxNTc0NTM2MDc2fQ.0ICqJswbGCpFniWtg9yaEWvl0yAjgueMrQUK5WzGKxA&autoplay=1&back=Browse&buy_label=Register&color=ffffff&context=https%3A%2F%2Fwatch.tbn.tv%2Fbrowse&live=0&playsinline=1&referrer=https%3A%2F%2Fwatch.tbn.tv%2Fcheckout%2Fsubscribe%2Freceipt%3Freturn_to%3Dhttps%253A%252F%252Ftbn.vhx.tv%252Fvideos%252Fhuckabee-110&sharing=1&show_price=0&title=0&vimeo=1#'
[vhx:embed] 656457: Downloading webpage
[vhx:embed] 656457: Downloading JSON metadata
[vhx:embed] 656457: Downloading akfire_interconnect_quic m3u8 information
[vhx:embed] 656457: Downloading fastly_skyfire m3u8 information
[vhx:embed] 656457: Downloading akfire_interconnect_quic MPD information
[vhx:embed] 656457: Downloading fastly_skyfire MPD information
[download] Destination: Untitled-656457.mp4
ffmpeg version n4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[hls @ 0x55d022c8d340] Skip ('#EXT-X-VERSION:3')
[hls @ 0x55d022c8d340] Opening 'https://skyfire.vimeocdn.com/1574544186-0xb6d03af06778952b13b01f44007a58881d86165b/374030609/video/1556977253/chop/segment-1.ts' for reading
[hls @ 0x55d022c8d340] Opening 'https://skyfire.vimeocdn.com/1574544186-0xb6d03af06778952b13b01f44007a58881d86165b/374030609/video/1556977253/chop/segment-2.ts' for reading
Input #0, hls, from 'https://skyfire.vimeocdn.com/1574544186-0xb6d03af06778952b13b01f44007a58881d86165b/374030609/video/1556977253/playlist.m3u8':
  Duration: 00:52:38.59, start: 0.700000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1280x720, 29.97 fps, 29.97 tbr, 90k tbn, 60k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Untitled-656457.mp4.part':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720, q=2-31, 29.97 fps, 29.97 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   28 fps=0.0 q=-1.0 size=     256kB time=00:00:00.83 bitrate=2514.5kbits
```
