### ISSUE TITLE
Better arbitrary peertube instance support

### ISSUE THREAD

**Issue by SoniEx2** [ytdl-org/youtube-dl#23189]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.11.22**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Currently the only way to play videos from arbitrary peertube instances is to convert the links to peertube: URIs. Ideally it'd work with the https form as well. But currently only the instances listed in the extractor can be used with the https form.

**Comment by dstftw** [comment]
Wrong. Bother to [check](https://github.com/ytdl-org/youtube-dl/blob/0de9fd24dc8723c78a90cb546e4a05818304521e/youtube_dl/extractor/peertube.py#L481-L484) before you open an invalid issue.
