### ISSUE TITLE
Add support for https://edgeofwonder.tv/

### ISSUE THREAD

**Issue by ob7** [ytdl-org/youtube-dl#23198]
## Checklist

- [x] I'm reporting a site feature request
- [ ] I've verified that I'm running youtube-dl version **2019.11.22**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Add ability to download videos from https://edgeofwonder.tv/ using youtube-dl command line tool.

**Comment by remitamine** [comment]
make sure that you try to use authenticated cookies with pages that require a subscription.

**Comment by ob7** [comment]
it says unsupported url

**Comment by ob7** [comment]
nvm passing the cookie makes it work, thank you.
