### ISSUE TITLE
Happy Eyeballs

### ISSUE THREAD

**Issue by SoniEx2** [ytdl-org/youtube-dl#23190]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.11.22**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I'm currently having some IPv6 connectivity issues. It'd be nice to have Happy Eyeballs so it doesn't take 30 minutes to go to the next video in the playlist.

**Comment by dstftw** [comment]
`-4`.

**Comment by SoniEx2** [comment]
That's not Happy Eyeballs.

**Comment by SoniEx2** [comment]
Also, that's a pain to use with mpv. And forget it if you're using youtube-dl as a library.

Happy Eyeballs would work better in those cases.
