### ISSUE TITLE
Download and extract to temporary directory, then move final output file

### ISSUE THREAD

**Issue by chrisgraham** [ytdl-org/youtube-dl#23206]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.11.22**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

My understanding is that youtube-dl will create temporary files (.part files), and video files (e.g. .webm files), in the current working directory - before concluding audio extraction and deleting those files.

Some music applications (e.g. RhythmBox) will listen for new media files in their music directory. This means it will pick up on a .webm file, then immediately report it missing. RhythmBox in particular then does not pick up on the .mp3, I'd guess because of it not being created atomically somehow - I have to restart, and it will then pick it up in a scan.

I suggest a new parameter that specifies that all files should be created in the system temporary directory, and then any files left over at the very end get moved into the current working directory.
This ensures no temporary files will be picked up, and that everything is atomic from the point of view of the final file path.

**Comment by dstftw** [comment]
1. Setup output template.
2. Use `--exec` to move files.
