### ISSUE TITLE
Method download unlisted videos of a channel without knowing URLs

### ISSUE THREAD

**Issue by effectively0** [ytdl-org/youtube-dl#23207]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I recall that youtube-dl was previously able to download unlisted videos when downloading everything from a youtube channel link. 
Is there currently any way to bulk download unlisted videos from channels? (either with or without the public videos)

**Comment by dstftw** [comment]
Do you read my messages at all?
