### ISSUE TITLE
Feature to list not downloaded videos because of errors  into a text file at the end

### ISSUE THREAD

**Issue by Bmt3s** [ytdl-org/youtube-dl#23208]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.11.22**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

Hi, the Feature is to list not downloaded videos or list errors, and save's them into a text file at the end of progress. thank you, beso

**Comment by dstftw** [comment]
Redirect stderr to file.

**Comment by Bmt3s** [comment]
Well I'm not a programmer (I'm a mathematician) I tried: "command > out 2>error" it's do the work :) but it's not showing the progress at the screen while progressing long work, can you kindly give a exact command line. thanks a lot
