### ISSUE TITLE
How do I apply this patch in this link? 

### ISSUE THREAD

**Issue by GeneralCaos** [ytdl-org/youtube-dl#23227]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question
How do I apply this patch?

WRITE QUESTION HERE
In the link below, one person said they fixed the issue with cookies by a patch. How do i apply that patch? I am using kali l.inux
https://github.com/ytdl-org/youtube-dl/issues/15697

**Comment by einstein95** [comment]
The patch was already merged. The patch no longer applies.
