### ISSUE TITLE
soundcloud no longer working

### ISSUE THREAD

**Issue by Wurzelmann** [ytdl-org/youtube-dl#23236]
## Checklist

- [ x ] I'm reporting a broken site support
- [ x ] I've verified that I'm running youtube-dl version **2019.11.22**
- [ x ] I've checked that all provided URLs are alive and playable in a browser
- [ x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl --verbose https://soundcloud.com/love-to-sew-podcast/episode-108-create-your-dream
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://soundcloud.com/love-to-sew-podcast/episode-108-create-your-dream']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.22
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-6-amd64-x86_64-with-debian-10.2
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] love-to-sew-podcast/episode-108-create-your-dream: Downloading info JSON
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[soundcloud] love-to-sew-podcast/episode-108-create-your-dream: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

## Description

WRITE DESCRIPTION HERE

I'm using a batch script to download new podcast episodes from soundcloud (e.g. this channel: https://soundcloud.com/love-to-sew-podcast) and since yesterday, it does not work any more. It does not matter if I choose single episodes or the whole channel, it does not work. I of course tried other Soundcloud channels/files/links, but none of them are working right now.

**Comment by Wurzelmann** [comment]
I'd love to know why this has been closed?

**Comment by gadeke** [comment]
two days passed still now working? someone please help.

**Comment by Fabian42** [comment]
@Wurzelmann Apparently they fixed it in a version that has not been released yet. Which is weird, because they did release a version long after closing this report.
