### ISSUE TITLE
YouTube Downloads Fail With  HTTP Error 429 Too Many Requests

### ISSUE THREAD

**Issue by RCcola1987** [ytdl-org/youtube-dl#23238]
## Checklist

- [X ] I'm reporting a broken site support
- [X ] I've verified that I'm running youtube-dl version **2019.11.22**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
Z:\Movies\Online Shows\YT\Markiplier>youtube-dl --verbose -wif bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 https://www.youtube.com/user/markiplierGAME
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-wif', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4', 'https://www.youtube.com/user/markiplierGAME']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.22
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2019-11-22-89aa134, ffprobe git-2019-11-22-89aa134, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube:user] markiplierGAME: Downloading channel page
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading webpage
[download] Downloading playlist: Uploads from Markiplier
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #1
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #2
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #3
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #4
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #5
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #6
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #7
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #8
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #9
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #10
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #11
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #12
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #13
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #14
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #15
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #16
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #17
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #18
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #19
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #20
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #21
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #22
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #23
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #24
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #25
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #26
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #27
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #28
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #29
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #30
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #31
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #32
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #33
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #34
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #35
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #36
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #37
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #38
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #39
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #40
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #41
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #42
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #43
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #44
[youtube:playlist] UU7_YxT-KID8kRbqZo7MyscQ: Downloading page #45
[youtube:playlist] playlist Uploads from Markiplier: Downloading 4549 videos
[download] Downloading video 1 of 4549
[youtube] UWlLuKmVH54: Downloading webpage
[youtube] UWlLuKmVH54: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: UWlLuKmVH54: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\extractor\youtube.py", line 1836, in _real_extract
youtube_dl.utils.ExtractorError: UWlLuKmVH54: YouTube said: Unable to extract video data

[download] Downloading video 2 of 4549
[youtube] C1uZodRheSs: Downloading webpage
[youtube] C1uZodRheSs: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: C1uZodRheSs: YouTube said: Unable to extract video data

## Description

WRITE DESCRIPTION HERE

I have tested this on the following systems:
1. Ubuntu 18.04
2. Windows 7 Pro 64bit
3. Windows 10 Pro 64bit

All systems present that same issue of either on first try the error will happen or on the second it will. No system can download videos from Youtube. Also 2 of the systems or on completely different PUBLIC IPs from different providers and on different networks.

**Comment by akadie4k** [comment]
I found this same problem on ubuntu 18.04.

**Comment by L0wB0b** [comment]
Same issue here at Debian 9.11, last week all worked perfect, here my verbose log:

```
youtube-dl https://www.youtube.com/watch?v=Yg_p98qvZNs --verbose
[debug] System config: [u'--force-ipv4']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=Yg_p98qvZNs', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.22
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.11
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Yg_p98qvZNs: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); 
please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version;
type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by RCcola1987** [comment]
What is this a duplicate to?

**Comment by RCcola1987** [comment]
Can you please provide the issue number to the original issue that you are sying mine is a duplicate too.
