### ISSUE TITLE
Sound Cloud Broken 401 Unauthorized

### ISSUE THREAD

**Issue by RCcola1987** [ytdl-org/youtube-dl#23239]
## Checklist

- [X ] I'm reporting a broken site support
- [X ] I've verified that I'm running youtube-dl version **2019.11.22**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
Z:\Movies\Online Shows\YT\SC\EOX-Studios>youtube-dl --verbose -wif bestaudio[ext=mp3]/mp3 https://soundcloud.com/EOX-Studios
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-wif', 'bestaudio[ext=mp3]/mp3', 'https://soundcloud.com/EOX-Studios']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.22
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2019-11-22-89aa134, ffprobe git-2019-11-22-89aa134, phantomjs 2.1.1
[debug] Proxy map: {}
[soundcloud:user] EOX-Studios: Downloading user info
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

## Description

WRITE DESCRIPTION HERE
This has been tested on the following systems
1. Windows 7 Pro 64bit
2. Windows 10 Pro 64bit
3. Ubuntu 18.04

All systems fail in the same way, no songs can be downloaded form ANY user. I have tested this with over 20 different active users on Sound Cloud and ALL fail with the same problem.

**Comment by RCcola1987** [comment]
What is this a duplicate to?

**Comment by JohnnyAtomsk** [comment]
I don't see any open issue related to this :( Please navigate me to the right issue. Thanks

**Comment by FewChar** [comment]
https://github.com/ytdl-org/youtube-dl/issues/23214
