### ISSUE TITLE
ERROR :Unsupported URL 

### ISSUE THREAD

**Issue by shanks-abhi** [ytdl-org/youtube-dl#23245]
Hi All , 

I am trying to download a specific Pluralsight video but I am getting the unsupported URL error. 

I am using the below command
youtube-dl "https://app.pluralsight.com/course-player?course=nunit-moq-mocking&author=jason-roberts&name=35b901df-4810-4f7f-abc0-4ddb8544fbba&clip=0&mode=live" --ffmpeg (Path to ffmeg.exe)

In order to Get the URL , I navigate to the course and click on the specific video.

Could someone please let me know , what I am doing wrong here? Why is the URL not being supported?

**Comment by Mattwmaster58** [comment]
The URL is not supported because nobody programmed that functionality. If you would like to [request site support](https://github.com/ytdl-org/youtube-dl/issues/new/choose), please use the proper issue format.

**Comment by shanks-abhi** [comment]
Thanks for your reply Matt. I thought Pluralsight was supported for Download. Its disappointing, I cannot use youtube.dll to download videos from that site.

**Comment by remitamine** [comment]
URL from #23311:
https://app.pluralsight.com/course-player?clipId=0d7835c4-842e-41cd-ba48-cd1162c310a2

**Comment by dirkf** [comment]
Continued in #32301.
