### ISSUE TITLE
youtube-dl version on apt repository is 2018.03.14

### ISSUE THREAD

**Issue by prabhatsoni99** [ytdl-org/youtube-dl#23248]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
prabhat@PrabhatsPC:~$ youtube-dl --version
2018.03.14
```

## Description

WRITE DESCRIPTION HERE

The latest version is 2019.11.22 while the youtube-dl on apt repository is 2018.03.14
This obviously leads to the youtube-dl downloaded via apt having many bugs.
This is a trivial error; please update it on the apt repository.

**Comment by dstftw** [comment]
Again: we do not control any 3rd party repositories. Report to corresponding maintainers.
