### ISSUE TITLE
Allow passing %(uploader) to --download-archive for batch jobs

### ISSUE THREAD

**Issue by Ste-etS** [ytdl-org/youtube-dl#23263]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I've got an automatic script on my server computer which runs every couple of days to archive YouTube channels I like to watch on-the-go without using data. It's just a single command that links to a batch file on my NAS, which I update to include any new channels I want to be archived.
However, when youtube-dl processes the batch job file, it can't use the --download-archive flag with variables. (Example: youtube-dl [rest of command] --download-archive "Z:\ytdl\%(uploader)s") Instead of filling it in with the appropriate uploader, it leaves the variable blank. I realize I could use multiple commands to accomplish this, but the whole point of setting up the batch job system for me was the simplicity of just dropping a link into a txt file and knowing it'll process. 

I'd like to request that the --download-archive flag is capable of using variables like uploader, playlist, etc. to determine the location of the archive file conditionally. I realize this could be difficult to implement, especially since varying links in a batch file can specify different types of media or even different sites altogether which may not include information like uploader or playlist, but assuming the same parser that handles where the output is going handles the archive location, both the content of the download and the archive list should end up in the same location.

Thanks!

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl/issues/7719#issuecomment-160987090

**Comment by Ste-etS** [comment]
Ah, sorry for the duplicate. That particular thread didn't pop up when I searched for it, guess I didn't hit any of the keywords. 

Thanks for the redirection!
