### ISSUE TITLE
Output file name is not what I expected

### ISSUE THREAD

**Issue by 821938089** [ytdl-org/youtube-dl#23267]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[youtube] gYO1uk7vIcc: Downloading webpage
[youtube] gYO1uk7vIcc: Downloading video info webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: D:\cloudhiback\main\hibackcloud\data\25\video.mkv.f137
[download] 100% of 85.29MiB in 02:14
[download] Destination: D:\cloudhiback\main\hibackcloud\data\25\video.mkv.f251
[download] 100% of 3.16MiB in 00:03
[ffmpeg] Merging formats into "D:\cloudhiback\main\hibackcloud\data\25\video.mkv.mkv"
Deleting original file D:\cloudhiback\main\hibackcloud\data\25\video.mkv.f137 (pass -k to keep)
Deleting original file D:\cloudhiback\main\hibackcloud\data\25\video.mkv.f251 (pass -k to keep)
```

## Description

```
def downloadvideo(vpath, proxy='',id=-1):
    ydl_opts = {
        'proxy': proxy,
        'outtmpl':getdatapath('/'+str(id)+'/video.mkv'),
        'format':'bestvideo[height<=?1080,ext=mp4]+bestaudio/best',
        'ffmpeg_location':getffmpegpath(),
    }
    # print ('test.')
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:

        ydl.download([vpath])
```
Problem:
1.when my code is `'outtmpl':getdatapath('/'+str(id)+'/video.mp4'),` ,ffmpeg merge will output video.mkv
2.I changed .mp4 to .mkv ,still cause a problem,it will output video.mkv.mkv

I hope it does not check the file suffix and writes the file name directly.

The file name change is not convenient for me to write code to handle these videos.

Hope you can fix it,thank you very much.

**Comment by dstftw** [comment]
>WARNING: Requested formats are incompatible for merge and will be merged into mkv.

**Comment by 821938089** [comment]
But I can't know if this video needs to be merged, if not then what file name will it output?
video.mp4?
video.mkv?
video.mkv.mkv?
