### ISSUE TITLE
Length Tag

### ISSUE THREAD

**Issue by thkdlflghlsdghilr** [ytdl-org/youtube-dl#23266]
- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

Add a tag for not downloading videos that are a certain length such as 10m or 1h

**Comment by dstftw** [comment]
`--match-filter`.

**Comment by thkdlflghlsdghilr** [comment]
I'm stupid, Thank you
