### ISSUE TITLE
Parameter that prints video info to json only

### ISSUE THREAD

**Issue by SwissCheese5** [ytdl-org/youtube-dl#23274]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

So basically, I've been facing issues with downloading the direct video link, the library hangs and loses connection and its probably my server's firewalls. Proxies work great for this, however proxy availability is limited. --write-info-json continues the download but prints valid direct-urls in the json file, even for licensed content. I would love to access those without actually downloading the video.

Perhaps a new parameter, something like --dont-download so that once it prints the json, it stops.

**Comment by dstftw** [comment]
Read FAQ?
```
--skip-download                  Do not download the video
```

**Comment by SwissCheese5** [comment]
Huh, odd. Thank you.
