### ISSUE TITLE
Add support for YoutubeKids(youtubekids.com)

### ISSUE THREAD

**Issue by Zorono** [ytdl-org/youtube-dl#23272]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs
https://www.youtubekids.com/watch?v=LeIm73XFN0I&hl=en-GB

**Comment by Zorono** [comment]
@remitamine really i couldn't understand why did you close this issue without at least telling me why ???
but,
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Zorono>%youtubedl% https://www.youtubekids.com/watch?v=LeIm73XFN0I&hl=en-
GB
[generic] watch?v=LeIm73XFN0I: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?v=LeIm73XFN0I: Downloading webpage
[generic] watch?v=LeIm73XFN0I: Extracting information
ERROR: Unsupported URL: https://www.youtubekids.com/watch?v=LeIm73XFN0I
'hl' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Zorono>%youtubedl% -version
[debug] System config: []
[debug] User config: ['--write-all-thumbnails', '-o', '~/Downloads/___MediaDownl
oads___/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-version']
Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: invalid rate limit specified

C:\Users\Zorono>%youtubedl% --version
2019.11.28
```
this is a proof of what do i mean(while `%youtubedl%` is an `environment variable` which is set to my `youtube-dl.exe`'s path)

**Comment by remitamine** [comment]
because it has been fixed and will be included in the next release.
