### ISSUE TITLE
"token" parameter not in video info for unknown reason

### ISSUE THREAD

**Issue by DaSniper12** [ytdl-org/youtube-dl#23275]
I installed youtube-dl a few months ago, but never had to use till now, and I got this error when I tried to run the following command: `youtube-dl -f bestaudio -o %(track).%(ext)s https://www.youtube.com/playlist?list=PL94SzHliMjheG8HCxkiilzatmsZwffOCN --verbose`

http://prntscr.com/q4dniy

what should I do?

**Comment by rautamiekka** [comment]
You should have
```
-o "%(track).%(ext)s" "https://www.youtube.com/playlist?list=PL94SzHliMjheG8HCxkiilzatmsZwffOCN"
```
to avoid the shell doing manipulation on the strings.

**Comment by DaSniper12** [comment]
I tried that and got the same error
