### ISSUE TITLE
How to update using EXE installation.

### ISSUE THREAD

**Issue by DaSniper12** [ytdl-org/youtube-dl#23276]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, I have tried looking everywhere for instructions, but I can't seem to figure how to update youtube-dl when i installed it using the exe, could someone please help?

**Comment by dstftw** [comment]
Read FAQ?
```
-U, --update                     Update this program to latest version. Make
                                 sure that you have sufficient permissions
                                 (run with sudo if needed)
```
