### ISSUE TITLE
Consistent youtube-dl error

### ISSUE THREAD

**Issue by heartles39** [ytdl-org/youtube-dl#23288]
Hello

I always get youtube-dl error on my servers. I've tried different locations I changed the rope address. After a while, I start to get this error again. Is there no definitive solution to this error?

Is it possible to extract Youtube data from another site? If this happens, maybe we won't get the youtube-dl error again.

For example : www.asd.com We will build an infrastructure for the site When we open a song from the music bot, www.asd.com will get the song from youtube and open it

VDS O.S : ubuntu 16

Youtube-dl version : 28.11.2019

Error: Yüklenemedi. (youtube-dl failed to load the resource.)

**Comment by sergey-rufanov** [comment]
Can you please provide example url's on which this error occurs, and also full output from youtube-dl in verbose mode(`-v` command line switch)?
