### ISSUE TITLE
How to update using EXE.

### ISSUE THREAD

**Issue by DaSniper12** [ytdl-org/youtube-dl#23286]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, so I have looked everywhere about how I can update, and so when I tried to do `youtube-dl -U` I ended up with the following message: `It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.` But my issue is that I installed using the EXE (since I am on windows). And I can't find the place where it is installed to delete it and start fresh, nor have I been able to update it with a new EXE. I also don't know which package manager to use as installed it using EXE.

**Comment by dstftw** [comment]
As clearly stated in the message you installed it via pip thus use that.
