### ISSUE TITLE
Unsupported URL: culture.ru

### ISSUE THREAD

**Issue by SlazE888** [ytdl-org/youtube-dl#23289]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.culture.ru/movies/792/taina-tretei-planety
- Single video: https://www.culture.ru/movies/708/tri-porosenka

## Description

All videos above plays fine in Google Chrome browser.

**Comment by sergey-rufanov** [comment]
Not needed. Generic extractor can handle downloading videos from this site without any problem..

**Comment by Esn024** [comment]
Not anymore! I just tried it with https://www.culture.ru/live/movies/15525/dom-13 and it didn't work: `ERROR: Unsupported URL`

**Comment by SlazE888** [comment]
> > Not needed. Generic extractor can handle downloading videos from this site without any problem.
> 
> Not anymore! I just tried it with https://www.culture.ru/live/movies/15525/dom-13 and it didn't work: `ERROR: Unsupported URL`. It was working a few weeks ago, so something has changed.

i'm confirm that!

**Comment by Esn024** [comment]
Still doesn't work. Can the "Invalid" tag to this ticket please be removed?
