### ISSUE TITLE
LinkedIn course Download Fail

### ISSUE THREAD

**Issue by MrKurtzmann** [ytdl-org/youtube-dl#23294]
## Checklist

- [X ] I'm reporting a broken site support
- [ X] I've verified that I'm running youtube-dl version **2019.11.28**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl -u *** -p *** https://www.linkedin.com/learning/excel-2016-essential-training/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.linkedin.com/learning/excel-2016-essential-training/', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[linkedin:learning:course] Downloading login page
[linkedin:learning:course] Logging in
[linkedin:learning:course] Downloading JSON metadata
[download] Downloading playlist: Excel 2016 Essential Training
[linkedin:learning:course] playlist Excel 2016 Essential Training: Collected 85 video ids (downloading 85 of them)
[download] Downloading video 1 of 85
[linkedin:learning] Downloading login page
[linkedin:learning] Logging in
[linkedin:learning] welcome: Downloading 360p JSON metadata
[linkedin:learning] welcome: Downloading 540p JSON metadata
[linkedin:learning] welcome: Downloading 720p JSON metadata
[linkedin:learning] welcome: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://files3.lynda.com/secure/courses/376985/VBR_MP4h264_main_HD720/376985_00_01_WX30_intro.mp4?yo44ep24HaZRQXRYq55s8a3D9P4hFS-zM_ysj4kyUFehiP3PJ7arq5AfAqeWuUDACuv3W860zaCDDEgytZ5vKFXjwvn1q27cWZx6GV7bKfyEhglrGDSIjG6CtHMorOjpCYWVfbgY96XaM07KJh0pBoqFma87md0GGssnbpD7TgcZg3qylC0f'
[download] Destination: Welcome-431592.mp4
[download] 100% of 4.61MiB in 00:01
[download] Downloading video 2 of 85
[linkedin:learning] using-the-exercise-files: Downloading 360p JSON metadata
[linkedin:learning] using-the-exercise-files: Downloading 540p JSON metadata
[linkedin:learning] using-the-exercise-files: Downloading 720p JSON metadata
[linkedin:learning] using-the-exercise-files: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://files3.lynda.com/secure/courses/376985/VBR_MP4h264_main_HD720/376985_00_02_XR15_exfiles.mp4?Qu401sLx3isYUe1WnKJFl2CD-DhPbEStE-vvrESaxicYbuHEX4OW4c3ITk_GHZ-0WlzZaDBZ_mSBVmJ9GX5U0v9gbI7rd96xJD7oOK_hNuA4Opv_FLTy4S5yrlSE63ihg5w8yDrzJeN5sVciAUj1px5IQmyWhFgp53OUGEyRPLGFSWuvYkExapY'
[download] Destination: Using the exercise files-431593.mp4
[download] 100% of 1.50MiB in 00:00
[download] Downloading video 3 of 85
[linkedin:learning] what-is-excel-used-for: Downloading 360p JSON metadata
[linkedin:learning] what-is-excel-used-for: Downloading 540p JSON metadata
[linkedin:learning] what-is-excel-used-for: Downloading 720p JSON metadata
[linkedin:learning] what-is-excel-used-for: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://files3.lynda.com/secure/courses/376985/VBR_MP4h264_main_HD720/376985_01_01_XR15_exceluses.mp4?bEL4djkeQyrbVkarC_UNdW8UgOxMVUoXaxKhGqHK6wayoVyE0RytBA2VUokRMnZJs5LTRGCXaJD4NwLXDlMXJYTtkZjz7D7skm6DCktf8FE7-qdqwZg5x2mC59GOpBtaUO1rDNdxh0Brqkv79g3wT5rJZm6-cjPg02TGLLNoBQ9iPC9kSmydqMNxyg'
[download] Destination: What is Excel used for-431595.mp4
[download] 100% of 8.51MiB in 00:02
[download] Downloading video 4 of 85
[linkedin:learning] using-the-menu-system: Downloading 360p JSON metadata
[linkedin:learning] using-the-menu-system: Downloading 540p JSON metadata
[linkedin:learning] using-the-menu-system: Downloading 720p JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/linkedin.py", line 127, in _real_extract
    self._sort_formats(formats, ('width', 'height', 'source_preference', 'tbr', 'abr'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Hi,
i try to download Linkedin Learning.
When i just use „youtube-dl https://www.linkedin.com/learning/excel-2016-essential-training/“ then its comes up with an Error.
When I use „youtube-dl -u xyz -p yxz https://www.linkedin.com/learning/excel-2016-essential-training/“ youtube-dl is downloading 3 Videos.
When i use my linked-in Account its still just downloads 3 Videos. 
I only use Copy and Past for my Password and i can log in with Safari, Chrom and the iOS app.
My Account is a old Lynda Account with i got as a Student but my login process is normale. Its my normal University email address withe i got from my University.
I hope someone can help! :):)

**Comment by remitamine** [comment]
try to use cookies.

**Comment by MrKurtzmann** [comment]
Hi,
thanks for your tip but Cookies also do not work withe linked in Learning. 
i tried my method on YouTube and it works but not on linked in Learning.
I Saved the Cookies with the Google Chrom Plugin „cookies.txt“ 
:(


`youtube-dl --cookies /Users/ln/cookies.txt  https://www.linkedin.com/learning/excel-2016-essential-training/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--cookies', u'/Users/ln/cookies.txt', u'https://www.linkedin.com/learning/excel-2016-essential-training/', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/linkedin.py", line 158, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/linkedin.py", line 36, in _call_api
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2831, in _get_cookies
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'`

**Comment by remitamine** [comment]
some of the code interacting with cookies is currently broken in python 2.x, you might want to try python 3 untill this is fixed.

**Comment by MrKurtzmann** [comment]
Thank you but also not working. 
I used "pip3 install youtube-dl" to run/get it in a different Python Version. That was new for me :) 

> youtube-dl --cookies /Users/ln/cookies.txt  https://www.linkedin.com/learning/excel-2016-essential-training/ -v
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--cookies', '/Users/ln/cookies.txt', 'https://www.linkedin.com/learning/excel-2016-essential-training/', '-v']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2019.11.28
> [debug] Python version **3.7.4** (CPython) - Darwin-18.7.0-x86_64-i386-64bit
> [debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
> [debug] Proxy map: {}
> ERROR: An extractor error has occurred. (caused by KeyError('JSESSIONID')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
>     ie_result = self._real_extract(url)
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/linkedin.py", line 158, in _real_extract
>     course_data = self._call_api(course_slug, 'chapters,description,title')
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/linkedin.py", line 36, in _call_api
>     'Csrf-Token': self._get_cookies(api_url)['JSESSIONID'].value,
> KeyError: 'JSESSIONID'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
>     ie_result = self._real_extract(url)
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/linkedin.py", line 158, in _real_extract
>     course_data = self._call_api(course_slug, 'chapters,description,title')
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/linkedin.py", line 36, in _call_api
>     'Csrf-Token': self._get_cookies(api_url)['JSESSIONID'].value,
> KeyError: 'JSESSIONID'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
>     ie_result = ie.extract(url)
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 543, in extract
>     raise ExtractorError('An extractor error has occurred.', cause=e)
> youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('JSESSIONID')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>

**Comment by remitamine** [comment]
the cookies you have exported are not complete.

**Comment by MrKurtzmann** [comment]
WOW. **THANK YOU!** Now I used the FireFox Add on "Export Cookies" to Export the Cookies and it works! Thank you!
https://addons.mozilla.org/de/firefox/addon/export-cookies-txt/?src=search

**Comment by Ramesh-X** [comment]
For me also, not working with username and password for some videos. Then I tried cookies. The result is as follows.

```bash
> youtube-dl --cookies ./cookies.txt -f progressive-360p --playlist-start 1 --playlist-end 10 -o '%(playlist)s - %(playlist_index)s - %(title)s.%(ext)s'  --download-archive downloaded.txt --prefer-ffmpeg --external-downloader aria2c --external-downloader-args -x5 -ciw https://www.linkedin.com/learning/serverless-architecture --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', './cookies.txt', '-f', 'progressive-360p', '--playlist-start', '1', '--playlist-end', '10', '-o', '%(playlist)s - %(playlist_index)s - %(title)s.%(ext)s', '--download-archive', 'downloaded.txt', '--prefer-ffmpeg', '--external-downloader', 'aria2c', '--external-downloader-args', '-x5', '-ciw', 'https://www.linkedin.com/learning/serverless-architecture', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.6.9 (CPython) - Linux-5.3.0-53-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
ERROR: An extractor error has occurred. (caused by KeyError('JSESSIONID',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ramesh/default/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/ramesh/default/lib/python3.6/site-packages/youtube_dl/extractor/linkedin.py", line 158, in _real_extract
    course_data = self._call_api(course_slug, 'chapters,description,title')
  File "/home/ramesh/default/lib/python3.6/site-packages/youtube_dl/extractor/linkedin.py", line 36, in _call_api
    'Csrf-Token': self._get_cookies(api_url)['JSESSIONID'].value,
KeyError: 'JSESSIONID'
Traceback (most recent call last):
  File "/home/ramesh/default/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/ramesh/default/lib/python3.6/site-packages/youtube_dl/extractor/linkedin.py", line 158, in _real_extract
    course_data = self._call_api(course_slug, 'chapters,description,title')
  File "/home/ramesh/default/lib/python3.6/site-packages/youtube_dl/extractor/linkedin.py", line 36, in _call_api
    'Csrf-Token': self._get_cookies(api_url)['JSESSIONID'].value,
KeyError: 'JSESSIONID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ramesh/default/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/ramesh/default/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('JSESSIONID',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Any idea how to fix it..?

**Comment by prakash47** [comment]
> 
> 
> WOW. **THANK YOU!** Now I used the FireFox Add on "Export Cookies" to Export the Cookies and it works! Thank you!
> https://addons.mozilla.org/de/firefox/addon/export-cookies-txt/?src=search

hello is it still working please inform me

**Comment by MrKurtzmann** [comment]
> 
Thank You!
still works great but right now I'm using YT-DLP
