### ISSUE TITLE
6play.fr not working (Failed to download m3u8 information: HTTP Error 404: Not Found)

### ISSUE THREAD

**Issue by dknguyengit** [ytdl-org/youtube-dl#23290]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://www.6play.fr/scenes-de-menages-p_829/episodes-du-30-novembre-a-2025-c_12553879
[6play] 12553879: Downloading JSON metadata
[6play] 12553879: Downloading webpage
[6play] 12553879: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12553879: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[6play] 12553879: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12553879: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[6play] 12553879: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12553879: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Downloading from 6play doesn't seem to work, due to "Failed to download m3u8 information: HTTP Error 404: Not Found" errors. It seems the site was recently updated, as sub-titles were not available for a while, but now they re-appear.

**Comment by dknguyengit** [comment]
May I ask why this ticket was closed? The site seems to be from the official company and is streamed for free. It also appears in the list of supported site.

It seems to me there might have been a change in their m3u8 link pattern, as seen in #15248.

**Comment by remitamine** [comment]
this has been answered [several times](https://github.com/ytdl-org/youtube-dl/issues/23060#issuecomment-552913817).
