### ISSUE TITLE
Please provide a 'legitimate' solution to "WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests"

### ISSUE THREAD

**Issue by ItsTHEAvro** [ytdl-org/youtube-dl#23298]
Here's the command I've used:
> youtube-dl -f bestaudio[ext=m4a] --embed-thumbnail --add-metadata https://youtu.be/-FlxM_0S2lA 

And here's the output:
> [youtube] -FlxM_0S2lA: Downloading webpage
> [youtube] -FlxM_0S2lA: Downloading video info webpage
> WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
> WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
> WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
> WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
> ERROR: -FlxM_0S2lA: YouTube said: Unable to extract video data

Also tried `--force-ipv4` and tried using VPN
Same result.
But opening the YouTube link in a web browser doesn't return any errors or CAPTCHA. It works just fine.

**Comment by ItsTHEAvro** [comment]
And what's the solution?
@dstftw

**Comment by Zuccace** [comment]
@ItsTHEAvro There's no offical solution yet.
Youtube has started graylisting ips until they solve catchpas and youtube-dl devs haven't found a solution.

You may want to check this: https://github.com/ytdl-org/youtube-dl/issues/22382

**Comment by born2net** [comment]
same problem here... :(
