### ISSUE TITLE
BBC iPlayer Download, WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Private61** [ytdl-org/youtube-dl#23302]
On trying to download a file, multiply warning messages are given. This is the second time it's occurred in a few days. Updated YouTube-dl.exe 2019-11-28, warnings still occur. File is then downloaded and works but looks a little smaller in file size. Debug code below.

C:\Program Files (x86)\YouTube-dl>youtube-dl -v -f "[fps<=30]" https://www.bbc.co.uk/iplayer/episode/b00y377q/pleasure-and-pain-with-michael-mosley
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '[fps<=30]', 'https://www.bbc.co.uk/iplayer/episode/b00y377q/pleasure-and-pain-with-michael-mosley']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] b00y377q: Downloading video page
[bbc.co.uk] b00y377q: Downloading playlist JSON
[bbc.co.uk] b00y3770: Downloading media selection XML
[bbc.co.uk] b00y3770: Downloading m3u8 information
[bbc.co.uk] b00y3770: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b00y3770: Downloading MPD manifest
[bbc.co.uk] b00y3770: Downloading MPD manifest
[bbc.co.uk] b00y3770: Downloading m3u8 information
[bbc.co.uk] b00y3770: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b00y3770: Downloading m3u8 information
[bbc.co.uk] b00y3770: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b00y3770: Downloading m3u8 information
[bbc.co.uk] b00y3770: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b00y3770: Downloading MPD manifest
[bbc.co.uk] b00y3770: Downloading MPD manifest
[bbc.co.uk] b00y3770: Downloading m3u8 information
[bbc.co.uk] b00y3770: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b00y3770: Downloading m3u8 information
[bbc.co.uk] b00y3770: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[debug] Invoking downloader on 'https://bbcfmt-ic-5614da00-0f173f-vodhlsuklive.s.loris.llnwd.net/usp/auth/vod/piff_abr_full_hd/d8d08d-

b00y3770/vf_b00y3770_59c7d
464-f02f-45be-b7ce-c2bcf1d1f092.ism.hlsv2.ism/vf_b00y3770_59c7d464-f02f-45be-b7ce-c2bcf1d1f092.ism.hlsv2-audio_eng_1=128000-video=827000.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 460
[download] Destination: Pleasure and Pain with Michael Mosley-b00y3770.mp4
[download] 100% of 423.92MiB in 02:49
[debug] ffmpeg command line: ffprobe -show_streams "file:Pleasure and Pain with Michael Mosley-b00y3770.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "Pleasure and Pain with Michael Mosley-b00y3770.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Pleasure and Pain with Michael Mosley-b00y3770.mp4" -c copy -f mp4 "-bsf:a" 

aac_adtstoas
c "file:Pleasure and Pain with Michael Mosley-b00y3770.temp.mp4"

**Comment by splace** [comment]
same here;

since previous episode of the same series working fine, seems a beeb change/issue but....

for me this means only low def. formats available.
