### ISSUE TITLE
youtube-dl download all .ts files from m3u8 but doesn't merge them into a single file

### ISSUE THREAD

**Issue by lapinvert** [ytdl-org/youtube-dl#23314]
I use the latest version of `youtube-dl`.
`ffmpeg` is installed and accessible in path.

I have a local `.m3u8` file. And I am trying to download the video from it with this command:

`youtube-dl --no-part -a video.m3u8`

It downloads all .ts files from the m3u8 but doesn't merge them into a single file when it is done.

Am I missing something?

**Comment by dstftw** [comment]
`-a` must provide path to a batch file not m3u8 playlist. It's not supposed to merge anything.
