### ISSUE TITLE
5.1 sound is working in 4k video downloader

### ISSUE THREAD

**Issue by ValZapod** [ytdl-org/youtube-dl#23319]
## Checklist

- [x ] I'm reporting a feature request
- [x ] I've verified that I'm running youtube-dl version **2019.11.28**
- [x ] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
https://www.youtube.com/watch?v=iTHtXgnhqfM
is using 5.1 sound (verified with mediainfo, downloaded with 4k video downloader)
Conversation on avsforum https://www.avsforum.com/forum/40-oled-technology-flat-panels-general/3057634-2019-c9a-e9-owner-s-thread-no-price-talk-340.html#post58914328
File downloaded from youtube with 4k video downloader:
[Dolby Atmos 5.1 Surround Sound Test.zip](https://github.com/ytdl-org/youtube-dl/files/3925895/Dolby.Atmos.5.1.Surround.Sound.Test.zip)

I see that issue https://github.com/ytdl-org/youtube-dl/issues/12004 which is WRONG!

**Comment by dstftw** [comment]
Post the full verbose output.

**Comment by ValZapod** [comment]
The output of what?

**Comment by ValZapod** [comment]
@dstftw What do you want from me?

**Comment by ValZapod** [comment]
@dstftw Okay. I understand, there is already 5.1 sound in -f 258. You could have just said that. 
`258          m4a        audio only tiny  389k , m4a_dash container, mp4a.40.2 (48000Hz), 2.94MiB`

**Comment by ValZapod** [comment]
Just a note, you can use pot player to have 5.1 sound! Nice!
