### ISSUE TITLE
Error 429 closed (#22839)

### ISSUE THREAD

**Issue by bathrobehero** [ytdl-org/youtube-dl#23325]
Why would you close that report? Of course we don't know how or why the issue happens, otherwise it would be solved, but there are many users with the same issue.

We know that --sleep-interval is ignored when youtube-dl is looking for a video list.

Whatever youtube-dl does when it reports 'Downloading video info webpage', it does it way too fast if I had to guess.

This issue will keep being reported over and over, it's counterintuitive to close them as you will just get more of the same questions over and over again. It's much better to have all the discussion in one report.

**Comment by dstftw** [comment]
I'll keep it closed until reproducible environment is provided.
