### ISSUE TITLE
Unable to test extractor

### ISSUE THREAD

**Issue by gabrielrspupo** [ytdl-org/youtube-dl#23329]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
Traceback (most recent call last):
  File "test/test_download.py", line 265, in <module>
    unittest.main()
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: type object 'TestDownload' has no attribute 'test_NickBr'
```

## Description

I've been trying to run a download test on the ```NickBrIE``` extractor contained in [youtube_dl/extractor/nick.py](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/nick.py), trying to fix an issue. Using the command ```python test/test_download.py TestDownload.test_NickBr``` and I'm unable to run it, although ```python test/test_download.py TestDownload.test_Nick``` works fine.

**Comment by dstftw** [comment]
`NickBr` does not have any download tests.
