### ISSUE TITLE
twitch FPS result NA?

### ISSUE THREAD

**Issue by toppits** [ytdl-org/youtube-dl#23333]
I've tried searching FPS here, but all it shows are results irrelevant to the issue.

I'm trying to use it in an output file or a quality condition "best[fps<=30]". Outputfile shows NA and requested format is not available.

**Comment by remitamine** [comment]
post an example URL were this info is provided by twitch.

**Comment by toppits** [comment]
https://www.twitch.tv/videos/488536587

**Comment by remitamine** [comment]
it won't work as you expect as the fps value is only provided for formats with 60 fps.

**Comment by toppits** [comment]
can you elaborate what that means?

**Comment by remitamine** [comment]
will be supported in the next release.

**Comment by toppits** [comment]
oh, ok, thank you.
