### ISSUE TITLE
Can youtube-dl move to python 3.8 ?

### ISSUE THREAD

**Issue by shirishag75** [ytdl-org/youtube-dl#23350]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've searched the bugtracker for similar feature requests including closed ones

In Debian, we are moving all python 2.x stuff and moving to python 3.8 . See [1] [2] . Seems even Canonical i.e. Ubuntu is moving there, see [3]

Almost 50-60% of the packages in the Debian archive have moved to python 3.8, the rest would be moving soon. While seeing a potential video download it seems we still use python 2.7, see 

https://github.com/ytdl-org/youtube-dl/issues/22360#issuecomment-562966694

I did try to see if there were any active branches which were using or considering python 3.8 but came up short. FWIW, I did look at the bugs to see if there was a bug which mentioned python3.8 but didn't find it. :(

1. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931659
2. https://release.debian.org/transitions/html/python2-rm.html
3. https://people.canonical.com/~ubuntu-archive/transitions/html/python2-rm.html
4. https://github.com/ytdl-org/youtube-dl/branches

@remitamine any comments here would also be appreciated.

**Comment by remitamine** [comment]
the code is compatible with both Python 2.6+ and Python 3.2+, there is nothing to on the youtube-dl side, it's up to the distribution to choose the default version used to run Python programs, for example, Arch Linux uses Python 3.x by default:
```
youtube-dl -v
[debug] System config: []
[debug] User config: ['-f', 'best[height<=768]/bestvideo[height<=768]+bestaudio/best', '--hls-prefer-ffmpeg', '--external-downloader', 'curl', '--sub-format', 'ass/tt/ttml/dfxp/scc/vtt/srt/sami/best']
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.8.0 (CPython) - Linux-5.4.1-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```
the issue you have with Python 2 has been already reported in #23256.

**Comment by jaddawyn** [comment]
I can relate that is working well with python3.

Thank you very much to all contributors of this project.

Have a nice day :)
