### ISSUE TITLE
AETV.com Unable to extract video url

### ISSUE THREAD

**Issue by x-lr8** [ytdl-org/youtube-dl#23363]
C:\Users\user\Downloads>youtube-dl -v https://www.aetv.com/shows/born-this-way/season-1/episode-1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.aetv.com/shows/born-this-way/season-1/episode-1']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[aenetworks] born-this-way/season-1/episode-1: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\aenetworks.py", line 176, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\user\Downloads>

**Comment by jlick** [comment]
I'm also seeing the same behavior. As mentioned, https://github.com/ytdl-org/youtube-dl/issues/23390 seems to be the same issue. A&E has moved content to a new play.aetv.com which no longer works with the youtube-dl extractor.

**Comment by jlick** [comment]
Additional information is in https://github.com/ytdl-org/youtube-dl/issues/23092 in the comments marked off-topic.

**Comment by jlick** [comment]
Workaround: (Hat tip to @tmgd-dot in https://github.com/ytdl-org/youtube-dl/issues/23092 for hints that led the way here.)

1) In Chrome, load video page e.g. https://play.aetv.com/shows/born-this-way/season-1/episode-1
2) Quickly hit Ctrl-Shit-I to open developer tools.
3) Wait until video starts playing.
4) Go to "Network" tab in developer tools panel.
5) Sort by name.
6) Find master.m3u8
7) Right click, Copy, Copy Link Address
8) Give this link address to youtube-dl. (Remember your shell quoting on Linux.)

**Comment by cyperous** [comment]
Why is no one looking at this, this effects multiple sites, currently I can't download any videos from history because of this.  This needs to be given some attention.

**Comment by tv21** [comment]
jlick's suggestion works BUT for some reason only seems to offer low quality resolutions, at least on History Channel.  For example one video was only available in these resolutions (shown when using the -F option):

format code  extension  resolution note
179          mp4        320x180     179k , avc1.42c01e, 23.976fps, mp4a.40.2
359          mp4        320x180     359k , avc1.42c01e, 23.976fps, mp4a.40.2
572          mp4        448x252     572k , avc1.42c01e, 23.976fps, mp4a.40.2
885          mp4        512x288     885k , avc1.42c01e, 23.976fps, mp4a.40.2
1187         mp4        640x360    1187k , avc1.42c01e, 23.976fps, mp4a.40.2
1491         mp4        768x432    1491k , avc1.42c01e, 23.976fps, mp4a.40.2
1994         mp4        960x540    1994k , avc1.4d401f, 23.976fps, mp4a.40.2 (best)

I noted that there were only three m3u8 files shown, the master.m3u8 and two others that were identical except they had different numbers just before the .mp4.m3u8 extension, one had 400 and the other had 1800, and the 1800 one was the one that gave the 960x540 resolution.  Last year I know you could get 720p so I am not sure why the resolution is so low this year.

**Comment by dnlzzxz** [comment]
well, i'm facing the same problem.. while appointing the manifest link manually works, the resolution on the manifest is capped at 540p. but probably it is on the server side, maybe a business decision by the channel itself once all the content is being sold on amazon... i don't know. i hope they make available higher resolutions again, as their encodes were already of a really bad taste (i mean huge filesizes/bitrates and still visible pixeleted artifacts on the scenes).. keep up the great work team!

**Comment by yemaozitw** [comment]
You can get 720p. If you get fastly m3u8 change the number before .mp4.m3u8 to 2500. So if you have the 540p m3u8 change 1800 to 2500 in the URL and it will be 720p. If you get akamai m3u8 reload until you get a fastly one. There is a method to get 1080p but I don't know it. Maybe someone will share here.

**Comment by cyperous** [comment]
@dstftw Maybe the contributors are not aware of this issue, but the supported site document lists history.com as a supported site.  This has been broken for over two months. 

Can we get some attention on this bug?

**Comment by remitamine** [comment]
read https://github.com/ytdl-org/youtube-dl#how-can-i-speed-up-work-on-my-issue, the issue will be locked if the rules are not followed.

**Comment by gohamstergo** [comment]
any news?

**Comment by nhlfarm** [comment]
@yemaozitw 720p method works fine. I tried changing 2500 to numbers up to 10000, in increments of 100, but none worked. There might not actually be a 1080p version, or maybe there is but it can't be obtained by just changing this number.

**Comment by killinj** [comment]
Issue is still present in youtube-dl version 2020.06.16.1

**Comment by goldenpipes** [comment]
> Workaround: (Hat tip to @tmgd-dot in #23092 for hints that led the way here.)
> 
> 1. In Chrome, load video page e.g. https://play.aetv.com/shows/born-this-way/season-1/episode-1
> 2. Quickly hit Ctrl-Shit-I to open developer tools.
> 3. Wait until video starts playing.
> 4. Go to "Network" tab in developer tools panel.
> 5. Sort by name.
> 6. Find master.m3u8
> 7. Right click, Copy, Copy Link Address
> 8. Give this link address to youtube-dl. (Remember your shell quoting on Linux.)

this worked perfectly on Lifetime on firefox as well!

Cheers

**Comment by yemaozitw** [comment]
> @yemaozitw 720p method works fine. I tried changing 2500 to numbers up to 10000, in increments of 100, but none worked. There might not actually be a 1080p version, or maybe there is but it can't be obtained by just changing this number.

I also tried the same thing before commenting without success. There are releases out that claim to be from AETV and are 1080p so there is a way that isn't obvious or they are using another source or the whole thing is a fake.

**Comment by danofun** [comment]
Youtube-dl documentation continues to list the aenetworks as supported. However, 9 months after initially being reported, this issue is still present in youtube-dl version 2020-07-28. How can I be of assistance in the efforts to resolve this issue?

**Comment by kevinoconnor7** [comment]
I put together #26795 that gets the extractor back into a working state. Feel free to patch it locally and test it out.

**Comment by kevinoconnor7** [comment]
Also, depending upon your MSO (specifically Spectrum), you may need #26792 patched as well.

**Comment by Mr-Jake** [comment]
@kevinoconnor7 Many thanks!

**Comment by ParadoxGBB** [comment]
> 
> 
> I put together #26795 that gets the extractor back into a working state. Feel free to patch it locally and test it out.

Thanks so much, applied this on my machine and it works great.

**Comment by jlick** [comment]
I tested #26795 with #17821 (Philo MSO) and was successfully able to use youtube-dl with play.aetv.com again. Thanks very much!
