### ISSUE TITLE
Use mutagen for embedding thumbnails

### ISSUE THREAD

**Issue by nullvideo** [ytdl-org/youtube-dl#23368]
## Checklist
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
**youtube-dl** uses external binaries to embed thumbnails into MP4/MP3 files. My question is that why use FFmpeg or AtomicParsley for embedding thumbnails.

Because, there is a library named `mutagen` which can handle ID3 tags and MP4 metadata atoms.
And does in-place manipulation without generating a temporary file. And, the biggest perk is that it is made in native Python.

Then what is the point of using `AtomicParsley` for the sole purpose of embedding thumbnails into a MP4 (MPEG-4 Part-II) file?

**Comment by dstftw** [comment]
1. Because this is what implemented.
2. Inplace manipulation is a very bad idea.

**Comment by nullvideo** [comment]
Explain, why inplace manipulation is a very bad idea?
