### ISSUE TITLE
How to download an album cover from Yandex Music as a separate file?

### ISSUE THREAD

**Issue by sojusnik** [ytdl-org/youtube-dl#23377]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

While downloading an album from Yandex Music, I also want to download the cover of this album as a separate file called `cover.jpg` and NOT embed the thumbnail in every file of this album, i.e. `--embed-thumbnail` isn't an option.

I'm using `youtube-dl --add-metadata -o "~/Downloads/%(album)s/%(track_number)s. %(artist)s - %(track)s.%(ext)s" URL`

Tried to add `--write-thumbnail`, but then a thumbnail was downloaded for every file in this album as a separate file, but I only want to have one file called `cover.jpg` inside the album folder.

It this currently possible?

**Comment by dstftw** [comment]
Not possible.
