### ISSUE TITLE
how to find the temporary cache folder?

### ISSUE THREAD

**Issue by Moriand** [ytdl-org/youtube-dl#23373]
## Question

 - I use Windows 8.1
How can I find the temporary cache folder when using **mpv player**
>**`C:\Users\Name>`mpv --ytdl link_youtube**

Well using from the **cmd**, it doesn't tell me what folder the files are in and my question is that I want to know where the caches or files are stored.

**Comment by dstftw** [comment]
Address this to mpv support.
