### ISSUE TITLE
How to use "YouTube-dl -g" to get a video others resolution real url? 

### ISSUE THREAD

**Issue by xizhaoxie** [ytdl-org/youtube-dl#23383]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

I know can use youtube-dl -F "url" to get video all resolution's id and use youtube-dl -f "id" "url" to select the other resolution and download. But i want use youtube-dl -g to get real url for a video not only the best resolution but also others resolution like 720p or  lower.

**Comment by dstftw** [comment]
Read FAQ on format selection.

**Comment by xizhaoxie** [comment]
> Read FAQ on format selection.

Format selection just only used by video download,  “youtube-dl -f 'format code' 'url'”Can be identified, but "youtube-dl -g 'format code' 'url'"can not be identified.

**Comment by dstftw** [comment]
No it's not. Again: read FAQ.
