### ISSUE TITLE
Using the output template to save to TXT

### ISSUE THREAD

**Issue by beskhu3epnm** [ytdl-org/youtube-dl#23385]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi. I simply wish to know how to use the Output template to pull video data such as the upload date and view count and save to a text document. Is this possible to do, and can you provide an example command?

`youtube-dl --get-id --get-duration --get-title https://www.youtube.com/watch?v=NEmdbcW7D3Q >> example.txt` pulls the ID, duration, and title and saves as a text document, as an example. But I am confused as to how to use the output template.

**Comment by dstftw** [comment]
```
--write-info-json                Write video metadata to a .info.json file
```
