### ISSUE TITLE
Youtube : Can't download my "liked" playlist

### ISSUE THREAD

**Issue by Simpfally** [ytdl-org/youtube-dl#23397]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--download-archive', u'downloaded_ziks.txt', u'--no-post-overwrites', u'-a', u'link_liked.txt', u'-wix', u'--embed-thumbnail', u'--audio-quality', u'0', u'-o', u'ziks/%(title)s.%(ext)s', u'-c', u'--prefer-ffmpeg', u'--geo-bypass', u'--username', u'PRIVATE']
[debug] Batch file urls: [u'https://www.youtube.com/playlist?list=LL3pJtUE_CpAMXJhyhzOhJMw']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.17 (CPython) - Linux-4.19.0-5-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.2.1-2, ffprobe 4.2.1-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Looking up account info
[youtube:playlist] Logging in
WARNING: Unable to extract result entry
[youtube:playlist] LL3pJtUE_CpAMXJhyhzOhJMw: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/home/savar/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/savar/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/savar/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 2807, in _real_extract
    has_videos, playlist = self._extract_playlist(playlist_id)
  File "/home/savar/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 2730, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist does not exist.

No difference if I enter a wrong password as well.

**Comment by Simpfally** [comment]
Yeah I'd be curious what is this a duplicate of, I've searched through issues with all the different keywords, couldn't find a thing. The liked playlist has been forced private recently, would be nice to know a work around at least..

**Comment by Joshfindit** [comment]
@Simpfally I had this too. The actual issue is that it's not logging in:

```
[youtube:playlist] Logging in
WARNING: Unable to extract result entry
```

It's related to #22862, #23482, #23544,  #23607, and so-on.
and *probably* the master issue is  #17216 

Switching to `--cookie` authentication worked for me

**Comment by Simpfally** [comment]
@Joshfindit Thank you, you're right. I've even read an issue specifically about this error message..

Cookies works fine, except you need to extract the cookies. The firefox's addon is fine but many cookies will give encoding errors, so you need to edit the file to remove all problematic cookies. Would be nice to know which cookies are needed?

Anyway it works this way, hope google can redirect people to this.
