### ISSUE TITLE
Option to skip downloading and merging audio for files that already have audio in them

### ISSUE THREAD

**Issue by numlockkey** [ytdl-org/youtube-dl#23391]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Say I want to download all videos from a YouTube channel that have a format code 22 or less.

I use a command like this:

youtube-dl -i -f 22/135+140 -o "i:/Downloads/%(uploader)s\%(title)s.%(ext)s" https://www.youtube.com/user/booksofscience/videos

Problem is, when it finds a video with the format code 22 which is a single 720p file with audio already in it, it still downloads a separate .m4a audio file and than merges it with the corresponding video file. This is redundant and there should be an option to skip it. It should ONLY download audio for files that are video only, such as the ones with the format code 135.

**Comment by dstftw** [comment]
`-f 22/135+140` will not download separate m4a audio is 22 is available.
