### ISSUE TITLE
Fails to download/merge audio stream 

### ISSUE THREAD

**Issue by numlockkey** [ytdl-org/youtube-dl#23393]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\T5400-3>youtube-dl -v -f 22/135/bestvideo+140/bestaudio https://www.youtube.com/watch?v=CBRbcpT0vwg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '22/135/bestvideo+140/bestaudio', 'https://www.youtube.com/watch?v=CBRbcpT0vwg']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[youtube] CBRbcpT0vwg: Downloading webpage
[youtube] CBRbcpT0vwg: Downloading video info webpage
[debug] Invoking downloader on 'https://r5---sn-p5qs7ned.googlevideo.com/videoplayback?expire=1576216880&ei=0NTyXYuICYvZhgb1rrKwBw&ip=216.55.242.167&id=o-ACXm4NWvqD_4YajQTQYTdz0VUwi_fff-1h6Dkd4TKbGr&itag=135&aitags=133%2C134%2C135%2C160%2C242%2C243%2C244%2C278&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-p5qs7ned%2Csn-ab5l6nsy&ms=au%2Conr&mv=m&mvi=4&pl=20&initcwndbps=3467500&mime=video%2Fmp4&gir=yes&clen=2009434&dur=343.587&lmt=1509737319702109&mt=1576195182&fvip=5&keepalive=yes&fexp=23842630%2C23860862&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRAIgQK4RDoRJ0TAkoUH-ubjQCi9Bxt5qHerM6MmpU4YKj1UCIC0G0ktj6YQXEzg_uo9o5422SiZWDuhEC32IJ5PNe9qe&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIhAPtdPSx5B2JVYPgzrn2rsxRgUL4VUV4kTphaeijkOF47Ah9dPLAbD-0he5fxwnFdmQGZx530pLTNKp0vG4VTNNNm&ratebypass=yes'
[download] Destination: Momentum (5 of 16) Impulse, Example 1-CBRbcpT0vwg.mp4
[download] 100% of 1.92MiB in 00:00
```

## Description

Downloading a video from YouTube using this command: 
youtube-dl -v -f 22/135/bestvideo+140/bestaudio https://www.youtube.com/watch?v=CBRbcpT0vwg

It correctly downloads format 135 version of the media, but it fails to download and merge format 140 audio. This results in a video file with no audio.

**Comment by dstftw** [comment]
This is expected behavior. Read FAQ on what does `/` mean in format selection.

**Comment by numlockkey** [comment]
How is this an expected behavior? It clearly fails to download and merge the audio stream.

**Comment by dstftw** [comment]
Again: if 135 is available it's not supposed to download anything apart from 135 with this syntax. Bother to read FAQ on how `/` works.
