### ISSUE TITLE
Convert output to hexadecimal stream instead of writing to file

### ISSUE THREAD

**Issue by J-Cake** [ytdl-org/youtube-dl#23406]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm wanting to include youtube-dl in a server project where a video is downloaded and instead of being written to the filesystem, it is instead converted to hexadecimal and piped through stdout. However, the `download` function of the library doesn't seem to respect this. Also I'm finding it difficult to find documentation on using the library programatically as it is primarily a CLI application. Node, I will only be dealing with mp3 formats.

**Comment by dstftw** [comment]
`-o -`.

**Comment by J-Cake** [comment]
How would I do this programmatically?
