### ISSUE TITLE
Part of Czech TV does not work

### ISSUE THREAD

**Issue by MyloshB** [ytdl-org/youtube-dl#23403]
## Checklist

- [yes] I'm reporting a broken site support
- [yes] I've verified that I'm running youtube-dl version **2019.11.28**
- [yes] I've checked that all provided URLs are alive and playable in a browser
- [yes] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [yes] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check-certificate', '--verbose', '--no-overwrites', '--restrict-filenames', '--output', 'D:\\Temp\\%(title)s_%(autonumber)s.%(ext)s', '--batch-file', 'C:\\Program Files (x86)\\YouTube-DL\\youtube-dl.lst']
[debug] Batch file urls: ['https://www.ceskatelevize.cz/ivysilani/11687510498-linka/219542150060001']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2019.11.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
Přístup byl odepřen.
Updated youtube-dl to version 2019.11.28.
[CeskaTelevize] 219542150060001: Downloading webpage
[CeskaTelevize] 219542150060001: Downloading JSON metadata
[CeskaTelevize] 219542150060001: Downloading JSON metadata
[CeskaTelevize] 219542150060001: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\extractor\ceskatelevize.py", line 201, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwnp2jh33\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Part of videos from www.ceskatelevize.cz does not work.
It was started cca 3 month ago - before this moment, YTDL worked perfectly!
Older videos work OK, but new ones are not downloadable.
Example: https://www.ceskatelevize.cz/ivysilani/11687510498-linka/219542150060001
Could you, please, help us :-)

**Comment by MyloshB** [comment]
@remitamine: Why my issue was closed without any comment or workaround?

**Comment by remitamine** [comment]
youtube-dl does not support DRM protected videos.

**Comment by MyloshB** [comment]
@remitamine: 
Thank you for that information.
So, could you, please, recommend some application which supports DRM protected videos download?
Thanks a lot in advance.

**Comment by remitamine** [comment]
I'm not aware of any public tool that does support DRM protected videos of this website.
