### ISSUE TITLE
[puhutv] partial download

### ISSUE THREAD

**Issue by mukarator** [ytdl-org/youtube-dl#23417]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -c -v https://puhutv.com/cilek-kokusu-13-bolum-izle
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-c', '-v', 'https://puhutv.com/cilek-kokusu-13-bolum-izle']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-93762-ge384f6f2f9, ffprobe N-93762-ge384f6f2f9
[debug] Proxy map: {}
[puhutv] cilek-kokusu-13-bolum: Downloading JSON metadata
[puhutv] cilek-kokusu-13-bolum: Downloading video JSON
[puhutv] 1973: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://vcdn-puhutv.akamaized.net/19/mp4/1080p.mp4?hdntl=exp=1576473050~acl=/*~data=hdntl~hmac=63e28876c20b3dcf029258179b492b5165144481837f7933fd537e4811b84a25'
[download] Destination: 13. Bölüm 1. Sezon 13. Bölüm-1973.mp4
[download] 100% of 4.79MiB in 00:02
```

## Description

Here is the list of all episodes:
https://puhutv.com/cilek-kokusu-detay
All of them are downloaded correctly (file size ~1.7 - 2 GB) except this one (episode 13) which is partially downloadеd (few MBs only).

**Comment by dstftw** [comment]
This is what they serve as best format. Select another.
