### ISSUE TITLE
Hot to pass cookies in python?

### ISSUE THREAD

**Issue by MaxiFilippov** [ytdl-org/youtube-dl#23410]
- [ ] I've verified that I'm running youtube-dl version **2019.11.28**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

I'm trying to pass cookies like this `ydl_opts = {'outtmpl': "%(id)s", "cookies": "/root/avd/f.txt"}` to avoid 429 error, but it still throws 429 because, as I suspect, it can't read cookie file, the path is right, I use the same path in terminal ` youtube-dl --cookies /home/max/Downloads/f1.txt https://www.youtube.com/watch?v=ZQpWRenGF_w
`  And it works properly. What do I do wrong in python?

**Comment by remitamine** [comment]
`cookiefile` not `cookies`:
https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L210

**Comment by MaxiFilippov** [comment]
> `cookiefile` not `cookies`:
> https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L210

What should I use instead?

**Comment by remitamine** [comment]
again the option key you're using is incorrect its: **cookiefile**
