### ISSUE TITLE
bug report as requested

### ISSUE THREAD

**Issue by franny23dmt** [ytdl-org/youtube-dl#23425]
corn231123@corn231123:~$ youtube-dl --verbose https://youtu.be/pujFt4edZN4   
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://youtu.be/pujFt4edZN4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-52-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 4.1.3-0york1, ffprobe 4.1.3-0york1
[debug] Proxy map: {}
[youtube] pujFt4edZN4: Downloading webpage
[youtube] pujFt4edZN4: Downloading embed webpage
[youtube] pujFt4edZN4: Refetching age-gated info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2148, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: Content Warning
If the owner of this video has granted you access, please sign in.
       This video is private.

**Comment by dstftw** [comment]
Read error message.
