### ISSUE TITLE
A Command line Window opens and flashes some text for a mili-second and then immediately disappears

### ISSUE THREAD

**Issue by life777eternal** [ytdl-org/youtube-dl#23424]
Hi I just downloaded the exe and when I tried to run it, it opens a Command line window and flashes some text on the screen, and then immediately disappears. Is that normal? The file version is 2019.11.28.0

Thank you.

**Comment by dstftw** [comment]
Google how to run command line apps.

**Comment by life777eternal** [comment]
> Google how to run command line apps.

Thanks,  ... I figured it out, open a CMD window, change to the directory that the exe is in, then type the name of the file without the .exe and then paste in a youtube URL. Really nice. 

[Run Command](https://sevenforums.com/tutorials/5966-run-commands-windows-7-a.html)
