### ISSUE TITLE
Rick & Morty issue downloading s04e03

### ISSUE THREAD

**Issue by jimbolaya** [ytdl-org/youtube-dl#23433]
```
[debug] System config: ['--all-subs']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-54-generic-x86_64-with-LinuxMint-19.2-tina
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]
```

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

There appears to have  a change between Rick & Morty s04e02 (https://www.adultswim.com/videos/rick-and-morty/the-old-man-and-the-seat) and Rick & Morty s04e03 (https://www.adultswim.com/videos/rick-and-morty/one-crew-over-the-crewcoos-morty) where now the video comes in multiple segments where before it seemed to be a stream. 

This seems similar to issue #16083, which was closed for inability to recreated. I hope I can perhaps contribute to this.  

At the transition between seg-0 and seg-1 in the download it appears to assume the video starts over as the last part of the numbering starts over. For instance, at the segment boundary:

```
[hls,applehttp @ 0x55f87ec4e300] Opening 'crypto+https://tve.cdn.turner.com/adultswim/3fa3ed79ea9c317c177a54129ac22d02/layer7/seg-0_00094.ts' for reading
[hls,applehttp @ 0x55f87ec4e300] Opening 'crypto+https://tve.cdn.turner.com/adultswim/3fa3ed79ea9c317c177a54129ac22d02/layer7/seg-1_00000.ts' for reading
frame=17125 fps=1422 q=-1.0 size=  343808kB time=00:09:31.39 bitrate=4929.1kbits/s speed=47.5x    ^M[mp4 @ 0x55f87f2f4860] Non-monotonous DTS in output stream 0:0; previous: 51417417, current: -6006; changing to 51417418. This may result in incorrect timestamps in the output file.
[mp4 @ 0x55f87f2f4860] Non-monotonous DTS in output stream 0:0; previous: 51417418, current: -3003; changing to 51417419. This may result in incorrect timestamps in the output file.
```
You can see that the file name goes from seg-0_00094.ts to seg-1_00000.ts and every file from seg-1_00000.ts to seg-1_00095.ts results in the output being spammed with the "Non-monotonous DTS in output stream" message. Every file after that has no errors. I suspect the time in the video stream gets reset and this confuses maybe ffmpeg?

Can each of these segments be treated as separate files like they are for "The Daily Show"? It would seem this would avoid this issue.

**Comment by remitamine** [comment]
outdated ffmpeg version.
