### ISSUE TITLE
429

### ISSUE THREAD

**Issue by coolsnow7** [ytdl-org/youtube-dl#23434]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2019.11.28**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
I don't actually know how to pull this from the command line
```

## Description

I ran into this issue last night, getting it again today - I'm just getting 429's whenever I try to pull info for several videos (ie 40) in a few minutes. Could you please unblock? Thanks!

**Comment by dstftw** [comment]
Ask Youtube.
