### ISSUE TITLE
hlsnative has detected features it does not support, extraction will be delegated to ffmpeg

### ISSUE THREAD

**Issue by thibnton** [ytdl-org/youtube-dl#23431]
when i try to download a France Tele link like this one 
`https://www.france.tv/france-5/c-dans-l-air/1117811-dans-le-piege-de-la-dette.html`

I get this :
 
`https protocol not found, recompile with openssl or gnutls enabled.
https://cloudreplayfrancetv.akamaized.net/aa3fb8dd00fd5/218664235_france-domtom_TA.ism/ZXhwPTE1NzY1MTE4MzV+YWNsPSUyZmFhM2ZiOGRkMDBmZDUlMmYyMTg2NjQyMzVfZnJhbmNlLWRvbXRvbV9UQS5pc20qfmhtYWM9YzFmZWI5ZTRjNmQ2MTMxYTE0YzkyNDJkMjg5MWQxZDA1YTZlMjAwMTVmNmI1NTI3OGFjOGYzOGYyZmJiMjkxOQ==/218664235_france-domtom_TA-video=768000.m3u8: Protocol not found`

Found previous issues about this problem which require an action on your side if i understood correctly ? Thank you very much for your help and in any case for the beautiful work.

**Comment by dstftw** [comment]
Recompile ffmpeg as requested in error message.

**Comment by thibnton** [comment]
Sorry, thanks !
