### ISSUE TITLE
IMDB falls back to generic 

### ISSUE THREAD

**Issue by RingoTheDog** [ytdl-org/youtube-dl#23443]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

>youtube-dl.py -v "https://www.imdb.com/video/vi3251092761?ref_=ttvi_vi_imdb_13"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.imdb.com/video/vi3251092761?ref_=
ttvi_vi_imdb_13']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.6.3 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[generic] vi3251092761?ref_=ttvi_vi_imdb_13: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vi3251092761?ref_=ttvi_vi_imdb_13: Downloading webpage
[generic] vi3251092761?ref_=ttvi_vi_imdb_13: Extracting information
ERROR: Unsupported URL: https://www.imdb.com/video/vi3251092761?ref_=ttvi_vi_imd
b_13
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 796, in e
xtract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 53
0, in extract
    ie_result = self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 3
347, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.imdb.com/video/v
i3251092761?ref_=ttvi_vi_imdb_13

## Description

URL: https://www.imdb.com/video/vi3251092761?ref_=ttvi_vi_imdb_13
falls back to generic and fails.

Pointing directly to the video downloads correctly using the generic extractor:

https://imdb-video.media-imdb.com/vi3251092761/1434659607842-pgv4ql-1554553497786.mp4?Expires=1576703946&Signature=rhZnOmQpqs25W6-5DtMOzbVTcpNR35fstm7Z9AXv6FlqaXKTaB07U0zhMuN4m~bx3s01VatMhcbZLekOqn5wal~UhKsuqCuUoKAeVGctP1zvQETW3cUshoLuFKI7eMumunih80UZYVO3UFyffKqFTQb6ZJ1IZttHCEJEoE25ODQVXeMpXBfclQ3cuybBlZQP8hAsiE7KcXmTnjZCnKRZ5e~Gm~l-nfs8XjFO2Cl7HiHPIFRB5wxG5xLqqEylVQEqgGj8yeAkKfBuReZcFtbOrVcTn1rBzaub8Sh1sflcghfgW1u5mhiVz4PCBDogdFcGXe6Jw9DRnZcHgWXygzDkTA__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA

Thanks
Ringo

**Comment by antdude** [comment]
I am having the same problem on two different Linux boxes (Fedora and Debian):
`$ youtube-dl -v https://www.imdb.com/video/vi150714649
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.imdb.com/video/vi150714649']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.4.2 (CPython) - Linux-3.16.0-10-amd64-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] vi150714649: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vi150714649: Downloading webpage
[generic] vi150714649: Extracting information
ERROR: Unsupported URL: https://www.imdb.com/video/vi150714649
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3350, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.imdb.com/video/vi150714649

$ youtube-dl -v https://www.imdb.com/video/vi150714649
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.imdb.com/video/vi150714649']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.17 (CPython) - Linux-5.2.18-100.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
[debug] exe versions: ffmpeg 4.0.5, ffprobe 4.0.5, rtmpdump 2.4
[debug] Proxy map: {}
[generic] vi150714649: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vi150714649: Downloading webpage
[generic] vi150714649: Extracting information
ERROR: Unsupported URL: https://www.imdb.com/video/vi150714649
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2375, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/ant/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/home/ant/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: syntax error: line 16, column 0
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3350, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.imdb.com/video/vi150714649`

**Comment by jhalvors-school** [comment]
Apparently dstftw thinks this issue should not be fixed until a more important issue on the IMDB extractor is fixed. He is also unwilling to discuss this further.

**Comment by dstftw** [comment]
The issues is already fixed. And yes I'm not willing to discuss nonsense.
