### ISSUE TITLE
Solution Prediction [HTTP Error 429: Too Many Requests]

### ISSUE THREAD

**Issue by eqenkhjin** [ytdl-org/youtube-dl#23445]
I'm predict a solution
 I've looked through the README and FAQ for similar questions
 I've searched the bugtracker for similar questions including closed ones

I have a new suggestion. We can write many options to terminal like this [youtube-dl -s --print-json video_url] from youtube. So problem is the HTTP Error 429: Too Many Requests when my programm many user's connect to my server and server ip has blacklisted. So i was changed server ip then it's blocked again. So my question is can we write to terminal any options information what can we get from client user side. For example client side can get get_video_info from youtube. Then i put this video info to terminal. So I think youtube-dl no need to connect to youtube server. Youtube-dl work is only extract proper information from client send get_video_info data.

**Comment by dstftw** [comment]
Not possible.

**Comment by eqenkhjin** [comment]
> Not possible.

Hi. Do you have link or more information about including why it's not possible. Sorry my python knowledge not good as well. So can't know about exactly what's happening in this library.
