### ISSUE TITLE
429 too many request problem

### ISSUE THREAD

**Issue by enescantas** [ytdl-org/youtube-dl#23448]
Hello,

I'm having an issue with the title. Can you help me please? I changed the IP address 5 times on the face of this error. I'm bored now. There has to be another solution. Please respond quickly!

**Comment by sunxvogy** [comment]
Read this:

https://www.reddit.com/r/youtube/comments/4cnyd6/youtube_keeps_asking_me_to_enter_captcha/

It seems if you visit the link directly without a referrer link, it might show you the captcha sometimes.
