### ISSUE TITLE
Incorrect number of files detected on YouTube

### ISSUE THREAD

**Issue by numlockkey** [ytdl-org/youtube-dl#23441]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

C:\Users\T5400-3>youtube-dl -v -i -f 22/(bestvideo+(140/bestaudio))/best -o "i:/YT Downloads/%(uploader)s\%(title)s.%(ext)s" https://www.youtube.com/user/mrpete222
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-i', '-f', '22/(bestvideo+(140/bestaudio))/best', '-o', 'i:/YT Downloads/%(uploader)s\\%(title)s.%(ext)s', 'https://www.youtube.com/user/mrpete222']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[youtube:user] mrpete222: Downloading channel page
[youtube:playlist] UUKLIIdKEpjAnn8E76KP7sQg: Downloading webpage
[download] Downloading playlist: Uploads from mrpete222
[youtube:playlist] UUKLIIdKEpjAnn8E76KP7sQg: Downloading page #1
[youtube:playlist] UUKLIIdKEpjAnn8E76KP7sQg: Downloading page #2
[youtube:playlist] UUKLIIdKEpjAnn8E76KP7sQg: Downloading page #3
[youtube:playlist] UUKLIIdKEpjAnn8E76KP7sQg: Downloading page #4
[youtube:playlist] UUKLIIdKEpjAnn8E76KP7sQg: Downloading page #5
[youtube:playlist] UUKLIIdKEpjAnn8E76KP7sQg: Downloading page #6
[youtube:playlist] UUKLIIdKEpjAnn8E76KP7sQg: Downloading page #7
[youtube:playlist] UUKLIIdKEpjAnn8E76KP7sQg: Downloading page #8
[youtube:playlist] UUKLIIdKEpjAnn8E76KP7sQg: Downloading page #9
[youtube:playlist] UUKLIIdKEpjAnn8E76KP7sQg: Downloading page #10
[youtube:playlist] UUKLIIdKEpjAnn8E76KP7sQg: Downloading page #11
[youtube:playlist] playlist Uploads from mrpete222: Downloading 1171 videos
[download] Downloading video 1 of 1171
[youtube] 9YPNXUvUQvs: Downloading webpage
[youtube] 9YPNXUvUQvs: Downloading video info webpage

When downloading this channel: https://www.youtube.com/user/mrpete222
youtube-dl reports 1171 videos available. Youtube reports 1173.

WRITE DESCRIPTION HERE

**Comment by dstftw** [comment]
https://www.youtube.com/playlist?list=UUKLIIdKEpjAnn8E76KP7sQg
