### ISSUE TITLE
YouTube livestream chat download

### ISSUE THREAD

**Issue by beskhu3epnm** [ytdl-org/youtube-dl#23440]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is youtube-dl able to download a YouTube livestream chat after it has gone offline and is fully processed as a video? In the same way that captions/transcripts are stored, is the YouTube livestream chat able to be downloaded also?

Post-livestream video example: https://youtu.be/Y5sJenjqzrs

**Comment by remitamine** [comment]
1. no.
2. no.
