### ISSUE TITLE
Slow URL resolver

### ISSUE THREAD

**Issue by Maranobarbaro** [ytdl-org/youtube-dl#23451]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi all.
Thanks in advance who want to help me.
I have kodi helix and I cannot upgrade to latest ones cause this is the last change for a x86 machine.
I've installed the yatse addon because it with the help of youtube_DL are the unique solution to see some videos on my little old media center.

The only boring thing is that sending an url from my mobile phone through yatse it spend about 20 seconds before it starts to play.
I've already contacted the author of Yatse and, after analysing the log, he says that the major contributor of this delay is due to the youtube-DL Plugin (about 17 seconds)

Sorry for the so long explanation but it is a little complicated.

After this poem... Is there anybody who want to help me please?

BTW this is the log
https://controlc.com/0c6655ec

Thanks to all
Barbaro

**Comment by dstftw** [comment]
You must provide pure youtube-dl verbose log.

**Comment by Maranobarbaro** [comment]
Sorry. Can you tell me how I can produce this log?
