### ISSUE TITLE
Download on https://player.vimeo.com don't work

### ISSUE THREAD

**Issue by mjunker61** [ytdl-org/youtube-dl#23460]
OS: Devuan ASCII 2.1
Browser: Firefox 68.3.0esr (64-Bit)

Warning and Error from the site:
youtube-dl -F https://player.vimeo.com/bcfc913d-ce60-484c-afcd-6dc9c7f0d5ab
[generic] bcfc913d-ce60-484c-afcd-6dc9c7f0d5ab: Requesting header
WARNING: Could not send HEAD request to https://player.vimeo.com/bcfc913d-ce60-484c-afcd-6dc9c7f0d5ab: HTTP Error 404: Not Found
[generic] bcfc913d-ce60-484c-afcd-6dc9c7f0d5ab: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

At the Website I am able to look the video, but no possibility to download.

**Comment by remitamine** [comment]
Incorrect URL.
