### ISSUE TITLE
YouTube error "ERROR: This video is unavailable."

### ISSUE THREAD

**Issue by superchap** [ytdl-org/youtube-dl#23465]
[1] First of all, can anyone else successfully download this YouTube video? Is it something on the YouTube's end?

command is as follows:

youtube-dl -k --output "~/Desktop/%(title)s.%(ext)s"  https://youtu.be/BPQNMsnuI8U

[2] Second, here is the response I receive when trying to run the same command.

~ $ youtube-dl -k --output "~/Desktop/%(title)s.%(ext)s"  https://youtu.be/BPQNMsnuI8U
[youtube] BPQNMsnuI8U: Downloading webpage
[youtube] BPQNMsnuI8U: Downloading video info webpage
ERROR: This video is unavailable.

[3] System details:

~ $ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.02
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-170-generic-x86_64-with-LinuxMint-18.1-serena
[debug] exe versions: ffmpeg 3.2.2-2, ffprobe 3.2.2-2, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

Thanks in advance.
Kindly,
-jc

**Comment by remitamine** [comment]
```
youtube-dl https://youtu.be/BPQNMsnuI8U
[youtube] BPQNMsnuI8U: Downloading webpage
[youtube] BPQNMsnuI8U: Downloading video info webpage
[download] Destination: The 'Instant Rufus' Pump Action Slingshot!-BPQNMsnuI8U.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  2 97.0M    2 2100k    0     0   506k      0  0:03:16  0:00:04  0:03:12  637k
```

**Comment by superchap** [comment]
Were you able to download it all (or just 2% of it)? Thank you.

**Comment by remitamine** [comment]
the output show that it can be downloaded.

**Comment by superchap** [comment]
Thank you .. ideas on why I'm experiencing intermittent difficulties?

**Comment by remitamine** [comment]
no, I have no idea what would be the problem on your side.

**Comment by bunaif** [comment]
@superchap  

> Were you able to download it all (or just 2% of it)? Thank you.

![Screenshot_٢٠١٩١٢٢٠-٢١١٢٤٧_Termux](https://user-images.githubusercontent.com/20098154/71275564-e34b6d00-236d-11ea-8b9c-494fdd618be1.jpg)

**Comment by neo-anderson** [comment]
I have this exact same issue on a ton of other videos. When I tried to download the video in OP's description, I was able to reproduce their output. I get the same error message.

**Comment by superchap** [comment]
Here's another one ... and I'm having this message show up intermittently
(with no explanation).

youtube-dl -k --output "~/Desktop/%(title)s.%(ext)s"
https://youtu.be/MAI_Mp92ZZo
[youtube] MAI_Mp92ZZo: Downloading webpage
[youtube] MAI_Mp92ZZo: Downloading video info webpage
ERROR: This video is unavailable.

**Comment by db48x** [comment]
I started having the same errors a few days back, and updating youtube-dl seems to have fixed it. I had been using version 2019.09.01 (which is not that old), and I've updated to version 2019.11.28 (which is still not as new as it could be) and the problem has gone away. All the videos that it had been saying were unavailable were downloaded on the first try.

(I'm not using the latest version only because this is the version available as a Fedora package; Fedora only picks up a release every couple of months.)

**Comment by superchap** [comment]
Tx db48x ... I'm going to try to figure out how to download 2019.11.28 specifically to see what results. Merry Christmas and/or Happy Holidays.

**Comment by superchap** [comment]
SUCCESS. Previous two example videos are now downloaded.
Thanks for the input everyone. Have a terrific rest of the decade! .. and
next.
Successfully upgraded to 2019.11.28 using this command --> sudo pip install
--upgrade youtube_dl

**Comment by aloisdg** [comment]
@superchap this problem happened for this [link](https://www.youtube.com/watch?v=RMhtCM6if6M). An updated client fix it. Thank you for your awesome work!
