### ISSUE TITLE
Extract initRange so that we can play adaptive streams directly in a player

### ISSUE THREAD

**Issue by mihaiav** [ytdl-org/youtube-dl#23463]
## Checklist

- [x ] I'm reporting a feature request
- [x ] I've verified that I'm running youtube-dl version **2019.11.28**
- [ x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I would like to play/stream the adaptive streams in a custom player without to process/ffmpeg the streams. In order to do that I need the initRange for each stream. This data seems available on the youtube.com page as it's used by the youtube player as well but unfortunately it's not returned by youtube-dl 

e.g ``` initRange\":{\"start\":\"0\",\"end\":\"265\"},\"indexRange\":{\"start\":\"266\",\"end\":\"1282\"} ```

**Comment by nickerlan** [comment]
Any updates on that?
