### ISSUE TITLE
spotify

### ISSUE THREAD

**Issue by avagraha** [ytdl-org/youtube-dl#23476]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Hi,
why it is simply unpossible to download something like this:
open.spotify.com/track/3lgj0jOfEI7A72X7LbtrqH
with any software, inclusive your YT-DL?

thanks for explanation.
merry xmas :)

**Comment by avagraha** [comment]
Hi, sorry, could you link to me the main topic, so I will be able to 
subscribe. thanks.


  ----- Original Message -----

**Comment by avagraha** [comment]
please

**Comment by maxlath** [comment]
https://github.com/ytdl-org/youtube-dl/issues/10344
