### ISSUE TITLE
Unable to login in Youtube

### ISSUE THREAD

**Issue by gabriel-vasile** [ytdl-org/youtube-dl#23482]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--download-archive', u'archive-audio.log', u'--verbose', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--ignore-errors', u'--extract-audio', u'--audio-format', u'mp3', u'--xattrs', u'--yes-playlist', u'-o', u'backup/%(playlist)s/%(title)s-%(id)s.%(ext)s', u'https://www.youtube.com/playlist?list=LL-9M-5IV4D8XwUs4ne15H-w']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Looking up account info
[youtube:playlist] Logging in
WARNING: Unable to extract result entry
[youtube:playlist] LL-9M-5IV4D8XwUs4ne15H-w: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2807, in _real_extract
    has_videos, playlist = self._extract_playlist(playlist_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2730, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist does not exist.

## Description

WRITE DESCRIPTION HERE
I'm trying to download a private youtube playlist. Both .netrc and username&password login options  fail. The playlist is "Liked videos".

**Comment by denus69** [comment]
I have same problem:

## Checklist

- [ x ] I'm reporting a broken site support
- [ x ] I've verified that I'm running youtube-dl version **2019.11.28**
- [ x ] I've checked that all provided URLs are alive and playable in a browser
- [ x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x ] I've searched the bugtracker for similar issues including closed ones


## Verbose log

```
[debug] System config: []                                                                                                                                                                      
[debug] User config: []                                                                                                                                                                        
[debug] Custom config: []                                                                                                                                                                      
[debug] Command-line args: ['-f', 'best', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v', 'https://youtu.be/J7msxRmoA5o']                                                                              
[debug] Encodings: locale cp1251, fs mbcs, out cp1251, pref cp1251                                                                                                                             
[debug] youtube-dl version 2019.11.28                                                                                                                                                          
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1                                                                                                                                
[debug] exe versions: ffmpeg N-65616-g7cdef77                                                                                                                                                  
[debug] Proxy map: {}                                                                                                                                                                          
[youtube] Downloading login page                                                                                                                                                               
[youtube] Looking up account info                                                                                                                                                              
[youtube] Logging in                                                                                                                                                                           
WARNING: Unable to login: Invalid password                                                                                                                                                     
[youtube] J7msxRmoA5o: Downloading webpage                                                                                                                                                     
[youtube] J7msxRmoA5o: Downloading embed webpage                                                                                                                                               
[youtube] J7msxRmoA5o: Refetching age-gated info webpage                                                                                                                                       
ERROR: Content Warning                                                                                                                                                                         
This video may be inappropriate for some users.                                                                                                                                                
       Sign in to confirm your age                                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                             
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info                                                   
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 530, in extract                                                 
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\youtube.py", line 2148, in _real_extract                                         
youtube_dl.utils.ExtractorError: Content Warning                                                                                                                                               
This video may be inappropriate for some users.                                                                                                                                                
       Sign in to confirm your age                                                                                                                                                             
```


## Description

I can't login on YouTube and can't download video when authorization is required.
In google profile settings "Less secure app access" is "On"

**Comment by okofish** [comment]
@dstftw Which issue is this a duplicate of?

**Comment by denus69** [comment]
@dstftw I'll also ask you: which issue is this a duplicate of? I can write bug report to your link.

**Comment by denus69** [comment]
@okofish May be dude @dstftw mean this old issue: https://github.com/ytdl-org/youtube-dl/issues/17216 ? I post my report there.
