### ISSUE TITLE
YouTube downloader won't download the best format 

### ISSUE THREAD

**Issue by eirnym** [ytdl-org/youtube-dl#23494]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
# youtube-dl -v --ignore-config -F https://www.youtube.com/watch\?v\=xQIaRSXh4ic                                                                                                                   
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '-F', 'https://www.youtube.com/watch?v=xQIaRSXh4ic']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.7.5 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] xQIaRSXh4ic: Downloading webpage
[youtube] xQIaRSXh4ic: Downloading video info webpage
[info] Available formats for xQIaRSXh4ic:
format code  extension  resolution note
249          webm       audio only tiny   56k , opus @ 50k (48000Hz), 21.87MiB
250          webm       audio only tiny   64k , opus @ 70k (48000Hz), 24.50MiB
251          webm       audio only tiny  111k , opus @160k (48000Hz), 44.58MiB
140          m4a        audio only tiny  133k , m4a_dash container, mp4a.40.2@128k (44100Hz), 57.37MiB
160          mp4        256x144    144p   76k , avc1.4d400c, 30fps, video only, 7.65MiB
133          mp4        426x240    240p  111k , avc1.4d4015, 30fps, video only, 11.94MiB
242          webm       426x240    240p  154k , vp9, 30fps, video only, 19.61MiB
278          webm       256x144    144p  155k , webm container, vp9, 30fps, video only, 18.76MiB
134          mp4        640x360    360p  172k , avc1.4d401e, 30fps, video only, 19.63MiB
135          mp4        854x480    480p  246k , avc1.4d401f, 30fps, video only, 30.09MiB
243          webm       640x360    360p  255k , vp9, 30fps, video only, 33.90MiB
244          webm       854x480    480p  429k , vp9, 30fps, video only, 49.58MiB
136          mp4        1280x720   720p  551k , avc1.4d401f, 30fps, video only, 47.85MiB
247          webm       1280x720   720p  930k , vp9, 30fps, video only, 87.63MiB
137          mp4        1920x1080  1080p 2166k , avc1.640028, 30fps, video only, 138.10MiB
248          webm       1920x1080  1080p 2233k , vp9, 30fps, video only, 302.15MiB
43           webm       640x360    360p , vp8.0, vorbis@128k, 123.69MiB
22           mp4        1280x720   720p  236k , avc1.64001F, mp4a.40.2@192k (44100Hz)
18           mp4        640x360    360p  332k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 147.31MiB (best)
```

## Description

Under some circumstances `youtube-dl` downloads not the best format, but the latest in the list of available. It could be a list returned by YouTube, but it seems not sorted. This wasn't an issue on the fast internet, but I can't change on the slow. Earlier it wasn't an issue and even on the slow internet I downloaded the best size and quality, in most cases, it was the biggest file.

If I download the format `137` or `248`, I'll have a file with about the same size and with not so small video dimensions. Probably, it's isn't the best in terms of video stream, but the best in terms of size and image quality on my screen 

What the `best` format means, how to download really the best format, instead of the latest in the list? 

Also how to tell YouTube-dl, that I don't care about file format, or prefer some after another (like I prefer webm over mp4, or the opposite)?

**Comment by dstftw** [comment]
Bother to use search.

**Comment by eirnym** [comment]
@dstftw I searched the first few pages of closed and opened issues, and there was no similar ones.

**Comment by eirnym** [comment]
There's even no such PR
