### ISSUE TITLE
Audio bitrate of downloaded files is not accurate

### ISSUE THREAD

**Issue by bennettisawesome** [ytdl-org/youtube-dl#23498]
```youtube-dl -v https://www.youtube.com/watch?v=k9mhsWKhqp0 -x -f 22
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=k9mhsWKhqp0', '-x', '-f', '22']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-88514-gd5995c531d, ffprobe N-88514-gd5995c531d
[debug] Proxy map: {}
```

I have tried to get the highest possible audio bitrate from this YouTube video, in this case format 22 being `22           mp4        1280x720   720p  359k , avc1.64001F, mp4a.40.2@192k (44100Hz) (best)` or 192k audio, and the resulting file is 128k. Same with format 251 on the same video, which is `251          webm       audio only DASH audio  102k , webm_dash container, opus @160k (48000Hz)` with the resulting file being much lower bitrate than 160k (different bitrates reported in different programs, ranging from 64k-99k, but never 160k). Can somebody please help me by telling me if I am doing something wrong? I recently redownloaded youtube-dl (weird update issue idk) from ytdl.org, so that couldn't be the problem.

**Comment by dstftw** [comment]
Blame Youtube for providing wrong bitrate metadata.
