### ISSUE TITLE
Hotstar Episode List

### ISSUE THREAD

**Issue by vinaykapadia** [ytdl-org/youtube-dl#23496]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

From Hotstar, I can download individual episodes and also seasons. However, just a full episode list doesn't work. Says "Unsupported URL". Example:
https://www.hotstar.com/us/tv/masterchef-india/s-830/list/episodes/t-1_2_830

**Comment by Joyhugo01** [comment]
i want https://www.hotstar.com/in/tv/masterchef-india/s-830/meet-the-top-15/1260014948
one of my friend DL using some user-agent change but i don't know how he do pls anyone help ?

**Comment by vinaykapadia** [comment]
@Joyhugo01 i was able to download all the master chef india episodes, but had to do it individually. The episode list page doesnt download all of them, but the individual episodes do.

**Comment by Ashish0804** [comment]
it loads only 20ep at a time so even using bs4 results in faulty data.

**Comment by ssdadu** [comment]
you can use hotstar api for this with requests library from python.

**Comment by ssdadu** [comment]
you can use hotstar api for this with requests in python.
By extracting episode ids and combing them with the generic url you can generate all urls.

**Comment by kalk17** [comment]
you can use hotstar api for this with requests in python.
By extracting episode ids and combing them with the generic url you can generate all urls.
