### ISSUE TITLE
youtube-dl failed to load the resource

### ISSUE THREAD

**Issue by JoschiTom** [ytdl-org/youtube-dl#23495]
How can i slove the problem:

12:21:26.5523| WARN|| Command Error (Could not load. (youtube: youtube-dl failed to load the resource.))
12:21:32.2532| INFO|| ::ffff:37.157.254.105 Requested: /api/settings/bot/set/1_4zOT3lTYO3tFUSUOa8KtsmN2v/events.idletime/PT15S
12:21:33.2568| INFO|| ::ffff:37.157.254.105 Requested: /api/settings/bot/set/1_4zOT3lTYO3tFUSUOa8KtsmN2v/events.onidle/%21play%20https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DdN44xpHjNxE
12:21:34.2599| INFO|| ::ffff:37.157.254.105 Requested: /api/bot/use/1/(/play/https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DdN44xpHjNxE
12:21:34.5500| WARN|1| Web error: [429] TooManyRequests
12:21:35.9903|ERROR|1| youtube-dl failed to load the resource:
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

root@skrime:~# youtube-dl -U
youtube-dl is up-to-date (2019.11.28)
root@skrime:~# youtube-dl --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.13 (CPython) - Linux-5.0.21-5-pve-x86_64-with-debian-9.11
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
root@skrime:~#

**Comment by eirnym** [comment]
@JoschiTom The YouTube returned `429`, just try again later. It's unfortunate that the Youtube-dl support can't answer anything but just close every single issue
