### ISSUE TITLE
Skip some errors, but not 429 Too Many Request errors?

### ISSUE THREAD

**Issue by danny-wu** [ytdl-org/youtube-dl#23510]
I'm using youtube-dl to archive a few YouTube channels and playlists. Some of the playlists contain unavailable videos (e.g. deleted, made private, etc). I don't want the download of the playlist to stop because of such an error.

However, I don' t want to skip all errors, because doing so will skip `429 Too Many Requests`. This is a rate limit put in place by YouTube. If I skip this error, Youtube-Dl can easily plow through 100 more videos hitting 429s right away, and in essence get my IP blocked for a long time.

Is there a way to specify skipping some errors, but not 429 too many requests?

Alternatively, can I ONLY skip video is unavailable, private, etc errors?

**Comment by sunxvogy** [comment]
So do you mean the **429 Too Many Requests** issues are caused by the "-i" parameter?

**Comment by danny-wu** [comment]
When you download too many videos, you get 429 Too Many Requests.

This is a temporary error if you wait for a few seconds, or sometimes, a couple of minutes.

However, if you pass `-i`, it continues trying to download videos immediately. Because attempts to download fail immediately and youtube-dl continues to trying the next video, this racks up a lot of downloads.

When you continue downloading despite a `429 Too Many Requests`, you will get your IP banned for hours, days, or weeks. I have an IP that is now banned even after a week, due to leaving youtube-dl racking up errors for six hours or so.

**Comment by sunxvogy** [comment]
> When you download too many videos, you get 429 Too Many Requests.
> 
> This is a temporary error if you wait for a few seconds, or sometimes, a couple of minutes.
> 
> However, if you pass `-i`, it continues trying to download videos immediately. Because attempts to download fail immediately and youtube-dl continues to trying the next video, this racks up a lot of downloads.
> 
> When you continue downloading despite a `429 Too Many Requests`, you will get your IP banned for hours, days, or weeks. I have an IP that is now banned even after a week, due to leaving youtube-dl racking up errors for six hours or so.

Thanks a lot!

**Comment by Panzer1119** [comment]
I haven't downloaded any videos with youtube-dl today from youtube, but as i wanted to start it now, it told me multiple times "HTTP Error 429: Too Many Requests", but in the Browser i'm not banned from YouTube, also YouTube App is working on my phone in my WLAN, so what is going on? (i even tried the "--force-ipv4" argument)

**Comment by GitItAgain** [comment]
I'm having a similar issue with Error 429. I am going to try something from the "Workarounds" section of the Readme.md file:

--sleep-interval SECONDS         Number of seconds to sleep before each
                                 download when used alone or a lower bound
                                 of a range for randomized sleep before each
                                 download (minimum possible number of
                                 seconds to sleep) when used along with
                                 --max-sleep-interval.
--max-sleep-interval SECONDS     Upper bound of a range for randomized sleep
                                 before each download (maximum possible
                                 number of seconds to sleep). Must only be
                                 used along with --min-sleep-interval.

**Comment by sunxvogy** [comment]
> I haven't downloaded any videos with youtube-dl today from youtube, but as i wanted to start it now, it told me multiple times "HTTP Error 429: Too Many Requests", but in the Browser i'm not banned from YouTube, also YouTube App is working on my phone in my WLAN, so what is going on? (i even tried the "--force-ipv4" argument)
> 
> Edit: Seams my IP was blocked or whatever, after i reconnected mit router (and got a new ip) everything worked fine again.
> But if my IP would be blocked, then youtube shouldn't work in the browser either?
> Hmm...

I assume it would be YouTube blocks "something" + IP. It doesn't use the IP address only. Too strange.

**Comment by danny-wu** [comment]
YouTube has updated something. I get 429s now on a known good configuration. 

I think they’re detecting YouTube-dl somehow, but still only rate limiting at a certain threshold to not trip casual use and also make counterdetection harderbb

**Comment by wakproductions** [comment]
Having the same problem. I was previously doing a weekly download of new content on certain channels I follow, then all of a sudden I started getting errors. Here's an example of what happened when I tried to download a video today:
```
$ youtube-dl https://www.youtube.com/watch?v=YtRpqRJnxT0
[youtube] YtRpqRJnxT0: Downloading webpage
[youtube] YtRpqRJnxT0: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: YtRpqRJnxT0: YouTube said: Unable to extract video data
```

I can interact with this page just fine in the browser. But then I switched to my cell phone's internet hotspot and was able to download the video using youtube-dl. I wonder if its something in the headers or something sent by youtube-dl.
