### ISSUE TITLE
Movie is not downloading from Hoichoi 

### ISSUE THREAD

**Issue by arijitbabai** [ytdl-org/youtube-dl#23515]
I have downloaded the updated the version of exe for Windows but I am getting this error -

D:\Downloads>youtube-dl.exe -i https://www.hoichoi.tv/films/title/haami
[ViewLift] haami: Downloading webpage
ERROR: Unable to extract film id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by meghanagottapu** [comment]
use command
 D:/Downloads>youtube-dl https://www.hoichoi.tv/films/title/haami
and also account-needed

**Comment by arijitbabai** [comment]
I am getting the same error

D:\Downloads>youtube-dl https://www.hoichoi.tv/films/title/haami
[ViewLift] haami: Downloading webpage
ERROR: Unable to extract film id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
For any work on this you must provide account credentials.

**Comment by arijitbabai** [comment]
Previously it was working without account credentials.
