### ISSUE TITLE
how to download all latest video from youtube channel

### ISSUE THREAD

**Issue by ramrathore** [ytdl-org/youtube-dl#23524]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
hi,
please let me know how to download all videos from any youtube channel and if i want to download latest today video only then how to download

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#video-selection-1
