### ISSUE TITLE
Download freeze on audio

### ISSUE THREAD

**Issue by demovirus** [ytdl-org/youtube-dl#23523]
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.12.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log
```
[generic] master: Requesting header
[generic] master: Downloading webpage
[generic] master: Downloading m3u8 information
[debug] Invoking downloader on 'https://strm.yandex.ru/vh-kp-converted/ott-content/515264901-4fdef7927c21af8a8c1059125f9dd533/3-video_169_576p.m3u8?chunks=1&vsid=eftj9egmta9pszv&redundant=5'
[download] master-master.f2002-5.mp4 has already been downloaded

[download] 100% of 33.46MiB
[debug] Invoking downloader on 'https://strm.yandex.ru/vh-kp-converted/ott-content/515264901-4fdef7927c21af8a8c1059125f9dd533/0-audio_rus_48000.m3u8?chunks=1&vsid=eftj9egmta9pszv'
[download] Destination: master-master.faudio-Русский.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3642.0 Safari/537.36
" -i "https://strm.yandex.ru/vh-kp-converted/ott-content/515264901-4fdef7927c21af8a8c1059125f9dd533/0-audio_rus_48000.m3u8?chunks=1&vsid=eftj9egmta9pszv" -c copy -f mp4 "file:master-master.faudio-Русский.mp4.part" 
```

## Description

I download different videos from yandex servers. I faced with this issue for 2-3 weeks. Some links were downloaded correctly but some not. Video was downloaded but audio freezes on exact segment each time. However I can download this part in browser. Moreover I can successfully download this video on another computer (and ISP), so I don't know how you can reproduce this.

Examples:
BAD links:
youtube-dl.exe -f "bestvideo[height<=576]+bestaudio/best" "https://strm.yandex.ru/vh-kp-converted/ott-content/572840447-437a05ec7c9fa79499c2caaa78362046/master.m3u8"
freezes on 0-audio_rus_48000-17.ts

youtube-dl.exe -f "bestvideo[height<=576]+bestaudio/best" "https://strm.yandex.ru/vh-kp-converted/ott-content/555748117-4691af94fb2c9159939ecaec020f7516/master.m3u8"
freezes on 0-audio_rus_48000-8.ts

youtube-dl.exe -f "bestvideo[height<=576]+bestaudio/best" "https://strm.yandex.ru/vh-kp-converted/ott-content/515264901-4fdef7927c21af8a8c1059125f9dd533/master.m3u8"
freezes on 0-audio_rus_48000-28.ts

GOOD links:
youtube-dl.exe -f "bestvideo[height<=576]+bestaudio/best" "https://strm.yandex.ru/vh-kp-converted/ott-content/555074657-43e197e14613ea629e81b12fbff662dd/master.m3u8"

youtube-dl.exe -f "bestvideo[height<=576]+bestaudio/best" "https://strm.yandex.ru/vh-kp-converted/ott-content/534464774-4acc4bd26b8682ab8377b32293456b5b/master.m3u8"

youtube-dl.exe -f "bestvideo[height<=576]+bestaudio/best" "https://strm.yandex.ru/vh-kp-converted/ott-content/564730421-4a1f3d59a345102a944106148ffa706e/master.m3u8"

![ydl](https://user-images.githubusercontent.com/25708906/71459435-43586e00-27c9-11ea-8203-7003596b162a.png)

**Comment by dstftw** [comment]
Report this to ffmpeg.

**Comment by demovirus** [comment]
Thank you very much. I've updated ffmpeg and it works now! Issue could be closed.
