### ISSUE TITLE
Download the titles of all playlists

### ISSUE THREAD

**Issue by beskhu3epnm** [ytdl-org/youtube-dl#23531]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm wondering how to write the titles of all playlists on a YouTube channel to txt file. Optionally, list the amount of videos in all playlists alongside them.

**Comment by dstftw** [comment]
Parse JSON output.
