### ISSUE TITLE
it dosen't work

### ISSUE THREAD

**Issue by thor-shuang** [ytdl-org/youtube-dl#23532]
(python3) λ youtube-dl --playlist-start 1 --playlist-end 2 -f best "https://www.youtube.com/watch?v=4-FJP1oE opM&pbjreload=10"
[youtube] 4-FJP1oEopM: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see
  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by thor-shuang** [comment]
the ture web is "https://www.youtube.com/watch?v=4-FJP1oEopM&pbjreload=10"

**Comment by dume2007** [comment]
> the ture web is "https://www.youtube.com/watch?v=4-FJP1oEopM&pbjreload=10"

It can't be solved, YouTube DL will die
