### ISSUE TITLE
显示zsh: no matches found:

### ISSUE THREAD

**Issue by QianMuXiao** [ytdl-org/youtube-dl#23540]
Last login: Fri Dec 27 23:20:56 on ttys000
xiaoqianmu@xiaoqianmudeMacBook-Pro ~ % youtube-dl https://www.youtube.com/watch?v=cm-w_7qjJnc
zsh: no matches found: https://www.youtube.com/watch?v=cm-w_7qjJnc

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
