### ISSUE TITLE
Unabled to Download JSON Metadata - HTTP Error 401 - Soundcloud.com

### ISSUE THREAD

**Issue by 3even** [ytdl-org/youtube-dl#23545]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.12.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://soundcloud.com/coldbrew-beats/hot-wheels']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.12.25
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-72-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] coldbrew-beats/hot-wheels: Downloading info JSON
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[soundcloud] coldbrew-beats/hot-wheels: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Youtube-dl is broken when trying to download audio from Soundcloud.com. This type of issue happens periodically and is usually fixed by simply updating Youtube-dl. However this time the issue persists even after update.

**Comment by Symbian9** [comment]
Duplicate https://github.com/ytdl-org/youtube-dl/issues/23529
