### ISSUE TITLE
[YouTube] Unable to sign in (invalid password)

### ISSUE THREAD

**Issue by besweeet** [ytdl-org/youtube-dl#23544]
Command:
`youtube-dl -f 136+140 --yes-playlist https://www.youtube.com/playlist?list=WL --netrc --add-header Accept-Encoding:deflate -v`

Results:
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['-f', '136+140', '--yes-playlist', 'https://www.youtube.com/playlist?list=WL', '--netrc', '--add-header', 'Accept-Encoding:deflate', '-v']
> [debug] Adding header from command line option Accept-Encoding:deflate
> [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
> [debug] youtube-dl version 2019.12.25
> [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.15063
> [debug] exe versions: ffmpeg N-92179-gc27c7b49dc, ffprobe N-92179-gc27c7b49dc
> [debug] Proxy map: {}
> [youtube:watchlater] Downloading login page
> [youtube:watchlater] Looking up account info
> [youtube:watchlater] Logging in
> WARNING: Unable to login: Invalid password
> [youtube:watchlater] WL: Downloading webpage
> ERROR: This playlist does not exist.
> Traceback (most recent call last):
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\common.py", line 530, in extract
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 3237, in _real_extract
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\youtube.py", line 2737, in _extract_playlist
> youtube_dl.utils.ExtractorError: This playlist does not exist.

I checked the username and password in .netrc dozens of times and tried various username / email / password combos. Nothing is working.

**Comment by besweeet** [comment]
I knew @dstftw would do that without posting any supporting links to other issues. I went through pages of search results and found nothing helpful or at least recent.

**Comment by m0rtal** [comment]
I have same issue, but everything was working weeks ago. I did not changed my YT password nor my download script. What's happening?

**Comment by stacalkas** [comment]
> I have same issue,  but everything was working weeks ago. I did not changed my YT password nor my download script. What's happening?

https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl

The above link helped me fix my issue. I couldn't download my "watch later" and in the log file, it kept saying invalid password.
