### ISSUE TITLE
remove useless tail of codec name for VIDEO SELECTION filter

### ISSUE THREAD

**Issue by NewUserHa** [ytdl-org/youtube-dl#23550]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.12.25**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description
`22           mp4        1280x720   720p  450k , avc1.64001F, mp4a.40.2@192k (44100Hz) (best)`
avc1 or avc should be the right name, and `avc1.64001F` seems make `-f "bestvideo[vcodec=avc1]"` fail since it fall back to vp9 in my test. https://en.wikipedia.org/wiki/Advanced_Video_Coding

Thanks for your input.

ps: would you consider https://github.com/ytdl-org/youtube-dl/issues/23549 as an enhancement for beauty and clear?
Thanks again!

**Comment by dstftw** [comment]
No, use contains operator `*=`. Again: bother to read FAQ.
