### ISSUE TITLE
TikTok request: auto rename [~.unknown_video] to [~.mp4]

### ISSUE THREAD

**Issue by yt-dddd775500** [ytdl-org/youtube-dl#23564]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.12.25**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

TikTok video files downloaded through youtube-dl always end with the file name [.unknown_video]. However, when downloading a video through the app, it downloads an [.mp4] file.

This is a request for youtube-dl to automatically rename [.unknown_video] files to [.mp4] files for TikTok.

**Comment by Zipdox** [comment]
When is that old pull request to fix the extractor getting merged?

**Comment by himouto** [comment]
It's still happening.

**Comment by bengrosser** [comment]
This is still a problem in 2020.06.06, but the issue is closed. Has it been replaced/superseded by another?

**Comment by CouponCodeSwap** [comment]
I am getting this error on numerous videos while downloading an Odysee playlist. Some get the proper .mp4 extension, others do not. Will run a rename command to correct this. After doing so, is there a way to go back and embed the thumbnails without downloading the video again for all the files that got the .unknown_video extension?
