### ISSUE TITLE
TikTok request: download using a user profile URL

### ISSUE THREAD

**Issue by yt-dddd775500** [ytdl-org/youtube-dl#23563]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2019.12.25**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

When using youtube-dl for YouTube, you can use the URL of a user's profile and it will automatically download ALL videos uploaded by that user.

It would be nice if we had that same functionality for TikTok. An example of a profile URL for TikTok would be [https://www.tiktok.com/@buzzfeed].

**Comment by skyme5** [comment]
Tiktok user page returns latest 24 videos only. Making api calls to tiktok requires generating `_signature` field, which may be difficult to implement and unable to maintain (due to frequent changes).
