### ISSUE TITLE
option for vedio quality .

### ISSUE THREAD

**Issue by ajit1310** [ytdl-org/youtube-dl#23568]
## Checklist

- [x] I'm reporting a feature request
- [ ] I've verified that I'm running youtube-dl version **2019.12.25**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE - currently which quality is downloaded cannot be control , can you add an option to download say , 1080 or 2k  or 4k   or  any type

**Comment by remitamine** [comment]
read https://github.com/ytdl-org/youtube-dl#format-selection.
