### ISSUE TITLE
"no-mtime" option missing in ydl_opts for python?

### ISSUE THREAD

**Issue by CyanSlinky** [ytdl-org/youtube-dl#23574]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I want "Date Modified" to be the time i downloaded the video and not the time it was uploaded. 
If i understand correctly then "no-mtime" is supposed to do this? 
but i'm using python and ydl_opts so i can't do --no-mtime as far as i know?

I searched through all available options [here](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L140-L322) but couldn't find "no-mtime" or anything similar.

Here's my ydl_opts, i've tried every variation i could think of for "no-mtime" separately and together, but nothing seems to change the timestamp to the time of download instead of upload. Although it does seem to be the time of download while it's downloading but as soon as it's done it changes it to the time of upload.

```
ydl_opts = {
        'ignoreerrors': True, 
        'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
        'merge-output-format': True,
        'outtmpl': output_template, #'quiet': True, 'no_warnings': True
        'nomtime': True,
        'no-mtime': True,
        'no_mtime': True
    }
```

**Comment by s104346** [comment]
What you are looking for is `updatetime`:

https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L302-L307
https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/downloader/common.py#L43
