### ISSUE TITLE
Internet Archive: Unable to extract jwplayer playlist

### ISSUE THREAD

**Issue by gitdjc** [ytdl-org/youtube-dl#23586]
youtube-dl can't download this. Nor can it even find the video on the main page from which I spawned the video window:

    https://blog.archive.org/2019/12/20/lawrence-lessig-being-a-citizen-is-a-public-office-too/

Here's the complete output.

djc

D:\Temp>youtube-dl --verbose **https://archive.org/embed/theydontrepresentus-lessig**
[debug] System config: []
[debug] User config: ['--verbose', '--ignore-errors', '-o', 'G:\\Video\\youtube-dl\\%(title)s - %(id)s.%(ext)s', '--geo-bypass', '-f', 'bestvideo[height<=1080]+bestaudio/best', '--abort-on-unavailable-fragment', '--write-info-json', '--write-description', '--write-annotations', '--write-thumbnail', '--merge-output-format', 'mkv', '--write-sub', '--write-auto-sub', '--sub-format', 'srt/best']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://archive.org/embed/theydontrepresentus-lessig']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.01.01
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2019-12-15-ed9279a, ffprobe git-2019-12-15-ed9279a
[debug] Proxy map: {}
[archive.org] theydontrepresentus-lessig: Downloading webpage
ERROR: Unable to extract jwplayer playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\archiveorg.py", line 45, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj4acy7ln\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract jwplayer playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dinosore** [comment]
@TinyToweringTree , @dstftw, I wonder what's the status of PR #23827.

I seem to bwe having a similar problem.
`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://archive.org/details/TheFirstOfTheFew']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[archive.org] TheFirstOfTheFew: Downloading webpage
ERROR: Unable to extract jwplayer playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/archiveorg.py", line 45, in _real_extract
    webpage, 'jwplayer playlist'), video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract jwplayer playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`
