### ISSUE TITLE
request to support WDR3 site

### ISSUE THREAD

**Issue by subirax** [ytdl-org/youtube-dl#23580]
Requesting YoutubeDL support for a currently unsupported site.  The site is:

https://konzertplayer.wdr3.de/klassische-musik/

## Checklist

- [x ] I'm reporting a new site support request
- [x ] I've verified that I'm running youtube-dl version **2019.12.25**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that none of provided URLs violate any copyrights
- [x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single audio: 
https://konzertplayer.wdr3.de/klassische-musik/konzert/tage-alter-musik-in-herne-2019-wege-zur-klarheit/

This next audio example expires from the web site on Jan 7 2020:
https://konzertplayer.wdr3.de/klassische-musik/konzert/live-wdr-rundfunkchor-anton-bruckner-messe-e-moll/

- Playlist: (not exactly a playlist, but a list of currently available audio streams)
https://konzertplayer.wdr3.de/klassische-musik/

## Description

This web site provides on-demand streams of various concerts broadcast by West German Radio.  

This is the verbose output from the first example page above:

C:\download\jdownloader>youtube-dl --verbose -f "best" https://konzertplayer.wdr3.de/klassische-musik/konzert/tage-alter-musik-in-herne-2019-wege-zur-klarheit/

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'best', 'https://konzertplayer.wdr3.de/klassische-musik/konzert/tage-alter-musik-in-herne-2019-wege-zur-klarheit/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.12.25
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7600-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[generic] tage-alter-musik-in-herne-2019-wege-zur-klarheit: Requesting header
WARNING: Falling back on generic information extractor.
[generic] tage-alter-musik-in-herne-2019-wege-zur-klarheit: Downloading webpage
[generic] tage-alter-musik-in-herne-2019-wege-zur-klarheit: Extracting information
ERROR: Unsupported URL: https://konzertplayer.wdr3.de/klassische-musik/konzert/tage-alter-musik-in-herne-2019-wege-zur-klarheit/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp243932xz\build\youtube_dl\extractor\generic.py", line 3347, in _real_extract youtube_dl.utils.Unsupported
Error: Unsupported URL: https://konzertplayer.wdr3.de/klassische-musik/konzert/tage-alter-musik-in-herne-2019-wege-zur-klarheit/

YoutubeDL gives the following result for the specific MP3 file that the above page refers to:

C:\download\jdownloader>youtube-dl --verbose -f "best" https://konzertplayer.wdr3.de/fileadmin/processed-import/20191226-2004/20191226-2004__wdr3konzert__256kbit.mp3
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'best', 'https://konzertplayer.wdr3.de/fileadmin/processed-import/20191226-2004/20191226-2004__wdr3konzert__256kbit.mp3']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.12.25
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7600-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 20191226-2004__wdr3konzert__256kbit: Requesting header
WARNING: Could not send HEAD request to https://konzertplayer.wdr3.de/fileadmin/processed-import/20191226-2004/20191226-2004__wdr3konzert__256kbit.mp3: HTTP Error 403: Forbidden[generic] 20191226-2004__wdr3konzert__256kbit: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on <!--

I hope this is enough to explain the problem.

Thanks for your attention and help!

**Comment by dirkf** [comment]
These URL patterns are no longer used (and the domain certificate has expired). Pages are now like https://www1.wdr.de/mediathek/audio/wdr3/konzert/audio-nrw-sommerkonzert--live-aus-aachen-100.html.

**Comment by Vangelis66** [comment]
> Pages are now like 
> https://www1.wdr.de/mediathek/audio/wdr3/konzert/audio-nrw-sommerkonzert--live-aus-aachen-100.html

Still, current `master` branch code fails to fetch _any_ audio file :cry: : 
```console
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', '.\\FFmpeg', '--external-downloader-args', '-v 8 -stats', '-vF', 'https://www1.wdr.de/mediathek/audio/wdr3/konzert/audio-nrw-sommerkonzert--live-aus-aachen-100.html']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2023.08.04.2154
[debug] Lazy loading extractors enabled
[debug] Single file build
[debug] Python 3.4.10 (CPython x86 32bit) - Windows-Vista-6.0.6003-SP2 - OpenSSL 1.0.2k  26 Jan 2017
[debug] exe versions: ffmpeg n6.1-dev-1700-N-111584-ga4e6168, ffprobe n6.1-dev-1700-N-111584-ga4e6168, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 53.52.13.219 (DE) as X-Forwarded-For.
[WDRPage] audio-nrw-sommerkonzert--live-aus-aachen-100: Downloading webpage
[download] Downloading playlist: audio-nrw-sommerkonzert--live-aus-aachen-100
[WDRPage] playlist audio-nrw-sommerkonzert--live-aus-aachen-100: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: audio-nrw-sommerkonzert--live-aus-aachen-100
```
The `WDRPage` IE is being invoked, but fails to find _any_ **downloadable id**; the audio stream on the page **plays fine in my browser** (non-deutsch IP address 😉 ); my browser's `Web Console` exposes a **direct link** to the audio file: 
```
https://wdrmedien-a.akamaihd.net/medp/ondemand/weltweit/fsk0/297/2970724/2970724_53613635.mp3
```
being served from an Akamai CDN node (and I guess `weltweit` is the reason I'm able to play that stream from my non-German location 😉 ) ...
