### ISSUE TITLE
use "youtube-dl -f .." with more complexe rule sets

### ISSUE THREAD

**Issue by PatrickJRed** [ytdl-org/youtube-dl#23584]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

currently i manually check for the final file-sizes of
webm : "youtube-dl -f 248/247/...+251/250 -o video.webm 'URL'"
mp4 : "youtube-dl -f 137/136/...+140 -o video.mp4 'URL'"
and then keep the smaller file.

for downloading muliple (from playlist or file) videos this is not efficient since it would require to first download both and then manually check+delete the less good file.
doing such is more time and storage consuming, and therefore not ideal

is there a way to directly tell youtube-dl to compare the (approx.) filesizes of the video-only formats (always comparing with same resolution) between the 'mp4'- and 'webm'-format ? (and compare merged size)

FG Patrickjred

**Comment by PatrickJRed** [comment]
and similiar rules (e.g. for resolution : low->high , high->low) ...

**Comment by dstftw** [comment]
Parse JSON output and write whatever script you need.
