### ISSUE TITLE
Some downloaded Reddit videos contain artifacts

### ISSUE THREAD

**Issue by webber-g** [ytdl-org/youtube-dl#23597]
## Checklist
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
X:\youtube-dl>youtube-dl --ignore-config -v https://www.reddit.com/r/gifsthatkeepongiving/comments/eii1av/he_just_keeps_jumping_higher_and_higher/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', 'https://www.reddit.com/r/gifsthatkeepongiving/comments/eii1av/he_just_keeps_jumping_higher_and_higher/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.01
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-92966-gd52a1be4e3, ffprobe N-92966-gd52a1be4e3
[debug] Proxy map: {}
[RedditR] eii1av: Downloading JSON metadata
[Reddit] 0c5ec3try5841: Downloading m3u8 information
[Reddit] 0c5ec3try5841: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://v.redd.it/0c5ec3try5841/HLS_576_v4.m3u8'

[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 8
[download] Destination: He just keeps jumping higher and higher-0c5ec3try5841.mp4
[download] 100% of 11.28MiB in 00:12
[debug] ffmpeg command line: ffprobe -show_streams "file:He just keeps jumping higher and higher-0c5ec3try5841.mp4"
```

## Description

When downloading some Reddit videos, the resulting file turns out to contain severe artifacts (skipping, messed up frames) making the video unwatchable.

Included Verbose log contains one such example URL. There have been many other Reddit videos that have this issue, so it is a fairly common occurrence.

In this particular case, when downloading with default format or with "-f bestvideo", youtube-dl chooses the "hls-3176" format as the best, probably due to the higher resolution of "516x768".

This results in the unwatchable video file.

Instead, downloading the "dash-VIDEO-1" format at 484x720 resolution, it results in a proper, watchable video file.

This is as far as I have analyzed the issue.

**Comment by kyleratti** [comment]
@dstftw can you please provide what this is a duplicate of? I've seen at least 3 issues relating to this that you've closed as a duplicate but there's never an explanation or example of the original.

**Comment by bitraid** [comment]
The developers can’t afford to make the searches for you and answer each issue individually. This is a very popular (60K+ star) project with many issues submitted every day (most of them duplicates) – there would be no time left for coding. If you search open issues for `reddit`, you’ll find what you are looking for (#14748).

**Comment by kyleratti** [comment]
> The developers can’t afford to make the searches for you and answer each issue individually. This is a very popular (60K+ star) project with many issues submitted every day (most of them duplicates) – there would be no time left for coding. If you search open issues for `reddit`, you’ll find what you are looking for (#14748).

Understandable, but if it's being closed as a duplicate, you know what it's a duplicate of. Also, a user is reporting that it made the problem worse in the linked issue.

**Comment by bitraid** [comment]
>Understandable, but if it's being closed as a duplicate, you know what it's a duplicate of. 

You know it's a duplicate, but still have to search to find it and spend time to reply (which is counterproductive).

>Also, a user is reporting that it made the problem worse in the linked issue.

When an issue is kept open, it means that it's not resolved yet.

>And at 2-1/2 years of age and zero activity, it's not obvious that issue is relevant to the 4 additional reported in 2019 and 2020.

It's the same thing - the time passed makes no difference.

**Comment by kyleratti** [comment]
> > Understandable, but if it's being closed as a duplicate, you know what it's a duplicate of.
> 
> You know it's a duplicate, but still have to search to find it and spend time to reply (which is counterproductive).

I have performed multiple searches over the past 4 months I've been seeing this problem and have never come across the original.

> > Also, a user is reporting that it made the problem worse in the linked issue.
> 
> When an issue is kept open, it means that it's not resolved yet.
> 
> > And at 2-1/2 years of age and zero activity, it's not obvious that issue is relevant to the 4 additional reported in 2019 and 2020.
> 
> It's the same thing - the time passed makes no difference.

Issues are regularly closed on this project for not having the current version (and rightfully so). Even if I'd come across that thread, I'd have assumed it's not the solution based on users reporting it made the problem worse and the sheer age. It's more likely that issue was forgotten about.

**Comment by bitraid** [comment]
>I have performed multiple searches over the past 4 months I've been seeing this problem and have never come across the original.

It's literally the 4th item on a 7-item list!

>Issues are regularly closed on this project for not having the current version (and rightfully so). Even if I'd come across that thread, I'd have assumed it's not the solution based on users reporting it made the problem worse and the sheer age. It's more likely that issue was forgotten about.

It's the only open issue for this problem. There is nothing to assume (other than the problem is not fixed yet).  If issues are closed as duplicates , it means that it's not forgotten.

**Comment by kyleratti** [comment]
@bitraid as expected, I implemented the `--hls-prefer-ffmpeg` option in the 3 year old thread and it replaced this artifact problem with the one detailed on #14748 (video only plays for several seconds, after which only audio is available.)

So it seems you have to choose between video artifacts or broken video.

Also, linking to an issue when marking it as a duplicate is still helpful because someone stumbling across this later on may not be able to find the "original". If you already know it's a duplicate, you may was well link it...
