### ISSUE TITLE
youtube-dl not downloading audio with --get-filename

### ISSUE THREAD

**Issue by byteshiva** [ytdl-org/youtube-dl#23598]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --verbose https://www.youtube.com/watch?v=VGYLCXJhJnI -f bestaudio --get-filename
[debug] System config: []
[debug] User config: [u'-x', u'--no-mtime', u'-o', u'~/xyz/Movies/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=VGYLCXJhJnI', u'-f', u'bestaudio', u'--get-filename']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.01
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-26-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
/home/abc/xyz/Movies/DARBAR (Tamil) - Official Jukebox _ Rajinikanth _ AR Murugadoss _ Anirudh Ravichander _ Subaskaran.webm

```

## Description

The audio extract file is not getting downloaded when `--get-filename` is mentioned.

```
➜ cat ~/.config/youtube-dl/config 
# Lines starting with # are comments

# Always extract audio
-x

# Do not copy the mtime
--no-mtime

# Save all videos under Movies directory in your home directory
-o ~/xyz/Movies/%(title)s.%(ext)s

```

**Comment by byteshiva** [comment]
reference: https://github.com/ytdl-org/youtube-dl/issues/7137

**Comment by remitamine** [comment]
this is expected behaviour.

**Comment by byteshiva** [comment]
The below command would give the filename after download.

```youtube-dl -x --quiet https://www.youtube.com/watch?v=VGYLCXJhJnI -f bestaudio --exec 'echo {}'```
