### ISSUE TITLE
How to avoid 429 on whole block of ipv6 proxies?

### ISSUE THREAD

**Issue by MaxiFilippov** [ytdl-org/youtube-dl#23602]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

I have about 4 000 request per day to Youtube.com and to avoid 429 I used to ipv4 proxies but it's too expensive so that I bought 100 ipv6 proxies and after 20 minutes of using it all 100 ipv6 proxy were banned with error "429 too many requests". When I use it to connect to youtube via browser it asks for captcha(not image but "click to verify that you are not a robot"). I completed this captcha, copied cookies then I passed cookies in youtube-dl and it worked but only for 10 minutes. How can I avoid ban of my ipv6 proxies by youtube? Maybe there some cookie generators?

P.S. If you close my issue as duplicate please give me solved issue otherwise do not close it we may find new solution of this problem

**Comment by dstftw** [comment]
There is no solution you must either solve captcha and pass authenticated cookies or use sleep interval. Neither of these are guaranteed to work.

**Comment by MaxiFilippov** [comment]
>  solve captcha and pass authenticated cookies
I passed cookies but it ban whole block of ipv6 in 20 minutes again

**Comment by erdengurkan** [comment]
I've seen some ipv6 proxies it works with no problem. when I create my own ipv6 proxy it got detects the whole subnet and bans. Even if I refresh the ipv6 ips the ban remains.. Any idea how the purchased ipv6 proxies solved this issue ?
