### ISSUE TITLE
SSD friendly file downloading

### ISSUE THREAD

**Issue by mrx23dot** [ytdl-org/youtube-dl#23606]
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description
Downloading a simple video file eg: youtube-dl -f "hls-480p" xvideos_site_56MB_vid_mp4
Creates many temp files on HDD during download:

x.mp4.part-Frag55.part
x.mp4.part-Frag56.part files of 0-1KB
x.mp4.ytdl
x.mp4.part

SSDs have limited lifespans when writing to them, so please add a feature to use more RAM instead of temporary HDD/SSD writes.  Eg. --memory 128MB, would wait for 128MB incoming data then write to the final file, without unnecessary additional writes.

Imagine an SSD in a download server, or SD in RaspberryPi, or even in HDD it causes fragmentation.
See Transmission's file cache handling as an example.

**Comment by dstftw** [comment]
Download files to RAM disk.

**Comment by reallyuniquename** [comment]
@dstftw 
>Download files to RAM disk.

That requires a lot of RAM since some files are huge, I'm talking about dozens of gigabytes per file.

Wouldn't it be possible to download current fragment to memory and then write it to file instead of abusing hardware with unnecessary writes?

**Comment by reallyuniquename** [comment]
I've been revisiting this issue, it turns out `ffmpeg` doesn't trash my drive with thousands of files so one can use `--hls-prefer-ffmpeg` although I'm not sure about the amount of writes. Maybe buffer size for `ffmpeg` could be tweaked as well.
