### ISSUE TITLE
Add client ip option while extracting url

### ISSUE THREAD

**Issue by richard87112** [ytdl-org/youtube-dl#23618]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I extracted a video URL with -g, but it does not play on another machine / in my web browser. I know In many cases, requests for the video (to download/play it) must come from the same IP . Is it possible to add an option to provide the fake ip while extracting the url, for example, youtube-dl -client-ip 192.168.0.1 -g http://www.youtube.com/...

**Comment by dstftw** [comment]
Technically impossible.
