### ISSUE TITLE
Does --download-archive work with either --dump-json or --flat-playlist?

### ISSUE THREAD

**Issue by lihuelworks** [ytdl-org/youtube-dl#23612]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm writing a Powershell script that outputs a list of titles and channels of a given playlist. The neatest way that I found was using **--dump-json or -j** on a file, then grabbing the titles (.fulltitle) and channel names (.uploader) with [jq](https://stedolan.github.io/jq/) to generate another file, like this:

`./youtube-dl.exe -i -j $url  | jq -j '.fulltitle + \" - \" + .uploader + \"\n\"' >> titles.log` which outputs something like this:

> Blowing up my house - awesomeprank65
> My house is gone, and my kickstarter - awesomeprank65

Thing is, when I'm trying to implement **--download-archive**, to skip those files I've already listed and have sent to titles.log, the command just gives the same output, reading all the files and adding them to the bottom...again. Here are more details about it: 

- I'm using the ">>" on purpose, otherwise the file would be overwritten and the content gone- This is needed in the case a video gets deleted, and I don't have access to it's title anymore.
- The problem is not related to the aforementioned script, since trying `youtube-dl -j --download-archive archive.txt  $URL` or `youtube-dl --flat-playlist --download-archive archive.txt  $URL` then adding a videos and running the command again gives the same results, listing ALL of the videos in a playlist in both cases. (In the second, with the videos added).
- In both cases, **_archive.txt was never created_**, nor in the testing folder, nor in youtube-dl's folder.
- Using latest version, (2020.01.01)
- Edit: Downloading the videos with **--download-archive** DOES creates the archive.txt file, _then_ testing `./youtube-dl.exe -i -j $url  | jq -j '.fulltitle + \" - \" + .uploader + \"\n\"' >> titles.log`  skips the first videos as initially intended.

So my questions are:

- Is --download-archive implemented in such a way that ONLY having a file of the video makes it record it's ID to archive.txt? (i.e the output of --download-archive)
- Is there any way to skip downloaded files if that was the case?
- Does order matter when using --download archive and -j or --flat-playlist? Would putting one first make the command work as intended?

**Comment by remitamine** [comment]
> Is --download-archive implemented in such a way that ONLY having a file of the video makes it record it's ID to archive.txt? (i.e the output of --download-archive)

as you can read in the option description:
Record the IDs of all **downloaded** videos in it.
> Is there any way to skip downloaded files if that was the case?

you can create the archive file the same way you're creating `titles.log`.
> Does order matter when using --download archive and -j or --flat-playlist? Would putting one first make the command work as intended?

no, it doesn't matter.

**Comment by lihuelworks** [comment]
Using the previously made titles.log doesn't skip the files, instead it throws error: `ERROR: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte`, probably related to the encoding of the file.

Changing the encoding to UTF-8 allows youtube-dl to read it, but doesn't do anything in the skipping videos department. It just all the videos again, only now with the characters all spaced out:
![Screenshot_1](https://user-images.githubusercontent.com/49965980/71716044-3dc6dd80-2df2-11ea-9dd6-f75d85d76583.png)

**Comment by remitamine** [comment]
Of course, it won't work this way, the download archive format is different from the `tiltles.log` file you're using, what I mean by the same way is that you can generate it by using the info JSON returned with `-j` option.

**Comment by lihuelworks** [comment]
That's solved. I can create an archive file that makes --download-arhive work, but I can't fix the `ERROR: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte` when youtube-dl tries to read the file Powershell just ouputted.
