### ISSUE TITLE
Youtube-dl 2020.01.01 is not working (Linux version)

### ISSUE THREAD

**Issue by ggbce** [ytdl-org/youtube-dl#23617]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v
/usr/local/bin/youtube-dl: ligne 1: erreur de syntaxe près du symbole inattendu « newline »
/usr/local/bin/youtube-dl: ligne 1: `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">'

```

## Description

Even, with or without verbose mode, with or without an URL in argument... I got always the same error like over in the LOG of verbose result.

If I use (rollback) an older version like youtube-dl 2019.10.22, it's working fine.

I'm using Debian 10 (amd64) up to date...

I followed the "standard" method to install it: Get code with curl, change permissions and run it !

**Comment by dstftw** [comment]
`/usr/local/bin/youtube-dl` is not a valid youtube-dl binary.
