### ISSUE TITLE
Support --username option for Chaturbate

### ISSUE THREAD

**Issue by HighCommander4** [ytdl-org/youtube-dl#23621]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

It would be nice if youtube-dl supported the `--username` option for Chaturbate, to download a stream that is only available to certain users (e.g. users who have purchased a ticket for a hidden show).

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by HighCommander4** [comment]
@dstftw: I am saying providing account credentials does not work. Even if I have a ticket for a hidden show, `youtube-dl --username <my-username> --password <my-password> <url>` will say "Room is currently offline".

**Comment by HighCommander4** [comment]
As far as I can tell, there is no code in `chaturbate.py` that checks for the `--username` and `--password` options and forwards them to the server in any way.

**Comment by dstftw** [comment]
Again: you must provide account credentials to developer.

**Comment by HighCommander4** [comment]
Oh, I see.

Do they need to be credentials for an account that has purchased tokens? Is there a way to provide them privately?

**Comment by dstftw** [comment]
It must be an account with access to whatever you request.

**Comment by CaptainJawZ** [comment]
In case an account has yet to be provided here is a dummy account:
user: dummy010203
password: Password010203

Since this issue happens with any stream I figured this account should do the trick

**Comment by zurand** [comment]
has this been resolved?  

I'm trying to download from chaturbate using  the username & password flags, but it doesnt seem to be working.

should i open a new ticket?

**Comment by HighCommander4** [comment]
> has this been resolved?

I don't think so.

One challenge is you generally need to spend tokens to even test this kind of scenario.
