### ISSUE TITLE
Downloading YouTube livestream VOD while still live

### ISSUE THREAD

**Issue by Minty-Meeo** [ytdl-org/youtube-dl#23620]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I've recently started using YouTube-DL to download YouTube livestreams while they are still live, but the download starts at the current live moment, ignoring the up to 3 hours of VOD history.  I was just wondering if this is possible to download as well via an option, or if no such feature exists yet.

**Comment by remitamine** [comment]
no such feature exists yet.

**Comment by ScamCast** [comment]
You can use streamlink and download the video from the beginning, then continue downloading the live parts.

https://streamlink.github.io/
