### ISSUE TITLE
NRK TV Series - Failed to parse JSON No JSON object could be decoded

### ISSUE THREAD

**Issue by davralin** [ytdl-org/youtube-dl#23625]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.01.01**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ time youtube-dl --config-location .
[debug] System config: []
[debug] User config: []
[debug] Custom config: [u'-o', u'/tmp/%(series)s/%(uploader)s/%(creator)s.%(channel)s..S%(season_number)02dE%(episode_number)02d.%(title)s.%(ext)s', u'--playlist-reverse', u'--console-title', u'--restrict-filenames', u'--batch-file=test.txt', u'--prefer-free-formats', u'--get-filename', u'--get-title', u'--add-metadata', u'--embed-subs', u'--all-subs', u'--sub-format', u'srt/best', u'--convert-subtitles', u'srt', u'--prefer-ffmpeg', u'--verbose', u'--exec', u'/etc/youtube-dl/script/cleanup.sh {}', u'--format', u'bestvideo[height<=720]+bestaudio/best[height<=720]/worst']
[debug] Command-line args: [u'--config-location', u'.']
[debug] Batch file urls: [u'https://tv.nrk.no/serie/snoefall/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.01
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-6-amd64-x86_64-with-debian-10.2
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1
[debug] Proxy map: {}
WARNING: [NRKTVSeries] snoefall: Failed to parse JSON No JSON object could be decoded

real	0m2.519s
user	0m1.649s
sys	0m0.200s
```

## Description

NRK TV Series stopped working, I don't know when it stopped.

The layout on nrk tv looks different, but I think they have an API which can/should be used for this anyway.

**Comment by sulark** [comment]
NRK tv is broken, fails to download any series (playlist), single episodes working.
Has been this way for a long time:
[NRKTVSeries] playlist xxxxxxxx: Collected 0 video ids (downloading 0 of them)
