### ISSUE TITLE
Sergey, I have wrote to you email, I would like to develop workaround limiting https://www.youtube.com/get_video_info?video_id={videoId}. call. Please stop closing this and communicate. youtube-dl needs refactoring to be able to use with youtube

### ISSUE THREAD

**Issue by janblaha** [ytdl-org/youtube-dl#23635]
Current concept of youtube download is completely useless for archiving youtube channel, which is funny, when using name youtube-dl :)

Current version 2020.01.01 downloads webpage a than sequentially downloads video info page and than by dates or name of the video file set by -o selecting, if video should be downloaded or not. This concept leads to too many request error, it is only matter of time, when your ip start to be blocked by google.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo+bestaudio', '--verbose', '--restrict-filenames', '--playlist-reverse', '-i', '--no-mtime', '-o', '%(uploader)s [%(channel_id)s]/%(upload_date)s - %(title)s [%(id)s].%(ext)s', '-ci', 'https://www.youtube.com/watch?v=VoaY8YRberk']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, pref cp1250
[debug] youtube-dl version 2020.01.01
[debug] Python version 3.7.0b4 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg git-2019-10-28-68f623d, ffprobe git-2019-10-28-68f623d
[debug] Proxy map: {}
[youtube] VoaY8YRberk: Downloading webpage
[youtube] VoaY8YRberk: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests

Using browser (chrome, firefox) same machine same time everything is OK, youtube plays video and show all information.

youtube-dl needs to refactor and use for grabbing video information JSON google API (in which case is possible to pay for increasing quota and free qouta is in ten of thousands videos information querry per day) or have to much more properly simulate real person usage and grab necessary new video info from

https://www.youtube.com/watch?v={youtube video ID}

and list of channel new videos ID grab from

https://www.youtube.com/channel/{youtube channel ID}/videos

Current version (usage of everyday checking of list of channels for new videos and archive them) is broken for youtube, or functioning only few days with luck (i am checking last 5 videos in about 40 channels once per a day and it took about 2-3 weeks to be blocked).

youtube-dl -v -f bestvideo+bestaudio --restrict-filenames --playlist-reverse --playlist-end 5 -i --no-mtime --dateafter now-7days -o "%(uploader)s [%(channel_id)s]/%(upload_date)s - %(title)s [%(id)s].%(ext)s" -ci --batch-file=download.txt

**Comment by danny-wu** [comment]
Yep can confirm youtube-dl in the present state is broken for archiving channels. You will get 429s.

I recommend suspending any archival scripts until it is fixed / a workaround is developed, as you might just get your IP blocked fro a very long time.

**Comment by koznov** [comment]
Same here, there is problem with playing with youtube-dl. 
When i'm using Firefox - it is going well - video is playing, when i'm trying to play with youtube-dl i'm getting 
`root@music:/home/user# youtube-dl https://www.youtube.com/watch?v=Y2u95GYuFUI
[youtube] Y2u95GYuFUI: Downloading webpage
[youtube] Y2u95GYuFUI: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests`
