### ISSUE TITLE
geo-bypass sbs on demand (australia) error

### ISSUE THREAD

**Issue by cwondercheck** [ytdl-org/youtube-dl#23646]
I don't know if I messed up or what
**video link**: https://www.sbs.com.au/ondemand/video/1611786307699/nbl-replay-illawarra-hawks-v-cairns-taipans

C:\Users\Chenaniah>youtube-dl --geo-bypass https://sbsvodns-vh.akamaihd.net/i/svod/SBS/managed/2019/10/15/664255_,512,1500,1000,128,K.mp4.csmil/index_1_av.m3u8?set-akamai-hls-revision=5&id=AgAr+vh6F0M555++El7tW4fcswSXJ%2fFA3w2jbbPbwjUquSZIA+J1a5dfYoZ6G4BAj3CFonq4rfatlg%3d%3d&hdntl=exp=1578373151~acl=%2fi%2fsvod%2fSBS%2fmanaged%2f2019%2f10%2f15%2f664255_*~data=hdntl~hmac=0fb58eb646da19c60ba501f54dae0af42e8dfe41a6136b5839b0fd548774d136
[generic] index_1_av: Requesting header
WARNING: Could not send HEAD request to https://sbsvodns-vh.akamaihd.net/i/svod/SBS/managed/2019/10/15/664255_,512,1500,1000,128,K.mp4.csmil/index_1_av.m3u8?set-akamai-hls-revision=5: <urlopen error [Errno 11001] getaddrinfo failed>
[generic] index_1_av: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
'id' is not recognized as an internal or external command,
operable program or batch file.
'hdntl' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dstftw** [comment]
1. You must use the original URL.
2. Geo bypass will only work it site respects X-Forwarded-For.

**Comment by Edwardwsr** [comment]
Hello, I guess you have to go for the following steps. Just go to your device’s settings, direct to ‘iTunes & App Store press on your Apple ID and choose the option that says View Apple ID. Here sign-in using your Apple ID password, on your account dashboard, click on ‘Country/Region’ and pick the option of Change Country or Region. Scroll down the options and pick your preferred country. Read more about bypassing geo restriction from https://thevpn.guru/how-bypass-geo-restrictions-location-errors/ now. Now an agreement notification comes into your screen and click on ‘Agree’ to accept Apple’s Media Services Terms and Conditions. You will be asked to fill the ‘BILLING ADDRESS’ portion on the shown page. Just fill in a billing address in your selected country, click on ‘Next’ at the top-right of the ‘ACCOUNT.’ There is no need to fill in your credit/debit card details, choose the option of ‘None’ for both PayPal and Credit card details. Introduce your iTunes applications and find your geo-restricted application you like.
