### ISSUE TITLE
Pornhub Videos download with no name

### ISSUE THREAD

**Issue by jeff-geoff** [ytdl-org/youtube-dl#23649]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

N/A

## Description

When downloading private videos using the --cookies flag, videos downloaded from pornhub save with 24 spaces, then a hyphen, then the "viewkey"

e.g., using the #1 most viewed video on the site as an example of how the title would work:

youtube-dl https://www.pornhub.com/view_video.php?viewkey=ph5df154382e4f3 --cookies ~/cookies.txt

will output a file with the name:

'                        -ph5df154382e4f3.mp4'

**Comment by caofanCPU** [comment]
What's the fuck! Watching online isn't well? What's the reason of you for downloading?

**Comment by benoon** [comment]
Also recently -g option outputs m3u8 file url instead of mp4.
Here some examples with 2020.01.01 version:

https://www.pornhub.com/view_video.php?viewkey=ph5dba442066391
https://www.pornhub.com/view_video.php?viewkey=ph5e04e908c958b
https://www.pornhub.com/view_video.php?viewkey=ph5e1481ae7a934

Any ideas how to get mp4 url ?

**Comment by jeff-geoff** [comment]
> What's the fuck! Watching online isn't well? What's the reason of you for downloading?

What repo do you think you're in?

**Comment by dstftw** [comment]
```
> py -3.7 .\youtube_dl\__main__.py https://www.pornhub.com/view_video.php?viewkey=ph5df154382e4f3 --cookies 'cookies.txt'
[PornHub] ph5df154382e4f3: Downloading pc webpage
[PornHub] ph5df154382e4f3: Downloading m3u8 information
[PornHub] ph5df154382e4f3: Downloading m3u8 information
[PornHub] ph5df154382e4f3: Downloading m3u8 information
[PornHub] ph5df154382e4f3: Downloading m3u8 information
[download] Destination: PervMom - Big Ass Step Mom Cheats With Her Huge Cock Stepson-ph5df154382e4f3.mp4
[download]   1.2% of 85.94MiB at  2.07MiB/s ETA 00:41
ERROR: Interrupted by user
```
