### ISSUE TITLE
How can I download the video with its spoken subtitle only?

### ISSUE THREAD

**Issue by tuanbs** [ytdl-org/youtube-dl#23653]
## Checklist
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've searched the bugtracker for similar feature requests including closed ones
## Description
When I download the video spoken in French language with its subtitle, it gives me the English subtitle:
```bash
youtube-dl --write-sub "https://www.youtube.com/watch?v=J8PEymuDf6A"
```
I know I can download all subtitles and change the track to French. But my app is using `youtube-dl`to download the spoken subtitle only and I have no idea which option commands of `youtube-dl` to achieve it. Any help appreciated. Thank you.

**Comment by remitamine** [comment]
read https://github.com/ytdl-org/youtube-dl#subtitle-options.

**Comment by tuanbs** [comment]
@remitamine Yes, I already read it sir and no option for that. So I think it's impossible. Anyway, thank you Sir.
