### ISSUE TITLE
unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by dieterminator** [ytdl-org/youtube-dl#23663]
D:>\youtube-dl --no-check-certificate -f 137 https://www.youtube.com/watch?v=bgH26x0fDOI
[youtube] bgH26x0fDOI: Downloading webpage
[youtube] bgH26x0fDOI: Downloading video info webpage
WARNING: unable to download video info webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by dieterminator** [comment]
I'm sorry I didn't check the notes carefully before asking.
I looked at the same problem in issues and tried to solve it.
Try to add the parameter -- no check certificate is still invalid, and also consider the network problem.
I used the shadowsocksr proxy and turned on the global proxy mode, and also confirmed that the network is stable.And I can get a list of videos.
So I need your help to solve this problem.
Software version:
D:\>youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2020.01.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {'https': 'https://127.0.0.1:1080', 'http': 'http://127.0.0.1:1080', 'ftp': 'ftp://127.0.0.1:1080'}

**Comment by RalphCorderoy** [comment]
I was getting this just now.  Running youtube-dl passing just the --rm-cache-dir option made the following commands work.
