### ISSUE TITLE
Can't Download complete video/course on learning.oreilly.com(1 min video length) 

### ISSUE THREAD

**Issue by gxxvx** [ytdl-org/youtube-dl#23679]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Hey, i am unable to download complete video from learning.oreilly.com using youtube-dl application, i am getting 1 min video only. Please suggest some solution for this issue. 

For Ex:- https://learning.oreilly.com/videos/software-architecture-fundamentals/9781491998991

**Comment by AlgusDark** [comment]
[There is a PR](https://github.com/ytdl-org/youtube-dl/pull/23670) that I'm waiting to be merged as it would solve this problem.
