### ISSUE TITLE
Aeon video download

### ISSUE THREAD

**Issue by Henrik9000** [ytdl-org/youtube-dl#23673]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://aeon.co/videos/ride-shotgun-through-mid-century-la-with-ed-ruschas-photos-and-jack-kerouacs-words
- Playlist: https://aeon.co/videos

## Description

$ youtube-dl https://aeon.co/videos/ride-shotgun-through-mid-century-la-with-ed-ruschas-photos-and-jack-kerouacs-words
[generic] ride-shotgun-through-mid-century-la-with-ed-ruschas-photos-and-jack-kerouacs-words: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ride-shotgun-through-mid-century-la-with-ed-ruschas-photos-and-jack-kerouacs-words: Downloading webpage
[generic] ride-shotgun-through-mid-century-la-with-ed-ruschas-photos-and-jack-kerouacs-words: Extracting information
ERROR: Unsupported URL: https://aeon.co/videos/ride-shotgun-through-mid-century-la-with-ed-ruschas-photos-and-jack-kerouacs-words

**Comment by kuco28** [comment]
Videos there are just embeds from Vimeo, YouTube and possible other sites.
You can just go there, copy link from embed and download that one.

**Comment by Henrik9000** [comment]
Thanks! - sorry for the trouble.
