### ISSUE TITLE
[Site-Support-Request] MrDeepFakes.com (NSFW)

### ISSUE THREAD

**Issue by github-userx** [ytdl-org/youtube-dl#23685]
## Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2020.01.01**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs violate any copyrights
- [X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://mrdeepfakes.com/video/5939/salma-hayek-lesbian-short-clip

## Description

The generic extractor unfortunately fails to extract the video.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30764

**Comment by dirkf** [comment]
Continued in #30764.
