### ISSUE TITLE
Add support for lbry.tv

### ISSUE THREAD

**Issue by ricketycricket69** [ytdl-org/youtube-dl#23695]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://lbry.tv/@christitustech:5/lbry-vs-youtube:e
- Single video: https://lbry.tv/@Lunduke:e/lbry-the-viable-youtube-alternative-in:4
- Single video: https://lbry.tv/@DesktopMonologues:b/why-windows-users-are-switching-to-linux:2

## Description

lbry.tv is a new open-source video publishing site. The site is still a bit funky, sometimes videos load on the first try sometimes not, and sometimes they fail halfway through watching them.

**Comment by vedranmiletic** [comment]
This should be fairly straightforward for someone familiar with the youtube-dl code, there is a download button with the URL: `<a target="_blank" class="button button--alt" download="lbry.mp4" href="https://player.lbry.tv/content/claims/lbry-vs-youtube/e65f097b9855701945c2da6d296177dd5615e06e/stream?download=1" rel="noopener noreferrer"><span class="button__content"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon--Download"><g><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></g></svg></span></a>`

**Comment by Soundtoxin** [comment]
Do you think it will be possible to add account support in the future as well? You get awarded LBC for watching a video a day on the site, and rewards for watching your first 10, 50, 100 and so on videos. I prefer to watch videos with mpv+youtube-dl, but I would hate to miss out on the rewards of the site.
Speaking of grander things, I believe lbry.tv is just a client to the LBRY protocol, so if the protocol itself could be supported, that would probably open up more possibilities, including watching videos that have been removed from the site, since they still remain inside the network.
That aside, just video playback support is something that I'd be grateful for. In the meantime I could manually click a video on the site while watching the actual thing my preferred way and still gain rewards that way.

**Comment by vedranmiletic** [comment]
> Do you think it will be possible to add account support in the future as well? You get awarded LBC for watching a video a day on the site, and rewards for watching your first 10, 50, 100 and so on videos. I prefer to watch videos with mpv+youtube-dl, but I would hate to miss out on the rewards of the site.

Possibly, for now I just did it the simplest way possible.

> Speaking of grander things, I believe lbry.tv is just a client to the LBRY protocol, so if the protocol itself could be supported, that would probably open up more possibilities, including watching videos that have been removed from the site, since they still remain inside the network.

Yeah, that would be nice.

> That aside, just video playback support is something that I'd be grateful for. In the meantime I could manually click a video on the site while watching the actual thing my preferred way and still gain rewards that way.

Give my pull request a shot and let me know if it works for you.

**Comment by FEFB-tech** [comment]
If you are on linux try:

`youtube-dl $(curl $1 |  grep embed | sed 's/.*embed\(.*\)">.*/\1/' | cut -d '"' -f1 | awk -v prefix="https://cdn.lbryplayer.xyz/api/v2/streams/free" '{print prefix $0}')
`
Where $1 is the URL of the lbry.tv video you want to download. For example:

`youtube-dl $(curl https://lbry.tv/@Hackernol:7/HACKITAT---9-LAYERS-OF-POLITICAL-HACKING:5?r=ATqhndQnpGqW3Sy6LhGRDxqgEMbe8Ugv |  grep embed | sed 's/.*embed\(.*\)">.*/\1/' | cut -d '"' -f1 | awk -v prefix="https://cdn.lbryplayer.xyz/api/v2/streams/free" '{print prefix $0}')`

You can put that in a bash script if you want, or use it along with mpv and ydtl for streaming.
Hope this may help, excuse my poor english, bye!

**Comment by Tamaranch** [comment]
A small bash function based on what @FEFB-tech proposed, but using `xmllint` and extracting also the title and video type:
```bash
lbryoutube-dl() {
  local -a a
  mapfile -t a < <(xmllint --html --xpath '
    concat(
      concat("https://cdn.lbryplayer.xyz/api/v2/streams/free/",
             substring-after(//meta[@property="og:video"]/@content, "/embed/"))
      , "'$'\n''"
      , string(//meta[@property="og:title"]/@content)
      , "'$'\n''"
      , substring-after(//meta[@property="og:video:type"]/@content, "video/")
    )
    ' <(curl -sS "$1"))
  youtube-dl -o "$HOME/${a[1]}-%(id)s.${a[2]}" "${a[0]}"
}
```
You can adapt the path where `youtube-dl` save the file at the last line, to suit your needs.

**Comment by kauffj** [comment]
For anyone working on this project, LBRY is happy to offer tech or cryptocurrency some support. We're generally pro open data and even make use of `youtube-dl` ourselves.

You can find me [in our chat](https://chat.lbry.com) at @kauffj or email me at jeremy@lbry.com.

**Comment by remitamine** [comment]
Supported in the latest version(2020.11.17).

**Comment by bitcoinmeetups** [comment]
@remitamine Is it possible to download the latest video on lbry with youtube-dl?

**Comment by remitamine** [comment]
@bitcoinmeetups No.
