### ISSUE TITLE
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info

### ISSUE THREAD

**Issue by dbabbitt** [ytdl-org/youtube-dl#23693]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.01.01**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Code to reproduce error

>     import youtube_dl
>     import os
> 
>     downloads_folder = r'C:\Users\577342\Downloads'
>     youtube_url_list = ['https://www.youtube.com/watch?v=E2hRUXuEhgI']
> 
>     ydl_opts = {
>         'format': 'bestaudio/best',
>         'nocheckcertificate': False,
>         'outtmpl': os.path.join(downloads_folder, youtube_dl.DEFAULT_OUTTMPL),
>         'postprocessors': [{'key': 'FFmpegExtractAudio',
>                            'preferredcodec': 'mp3',
>                            'preferredquality': '192'}],
>         'verbose': True,
>         }
>     with youtube_dl.YoutubeDL(ydl_opts) as ydl:
>         for url in youtube_url_list:
>             try:
>                 # It also downloads the videos
>                 res = ydl.extract_info(url,
>                                        force_generic_extractor=ydl.params.get('force_generic_extractor',
>                                                                               False))
>             except Exception as e:
>                 print()
>                 print('####################################################')
>                 print(e)
>                 print('####################################################')
>                 print()
> 
>         print(ydl._download_retcode)
>     print('Conversion completed.')

## Verbose output

[debug] Encodings: locale cp1252, fs utf-8, out UTF-8, pref cp1252
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.6.8 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: avconv v13_dev0-1440-g34c1133, avprobe v13_dev0-1440-g34c1133, ffmpeg git-2020-01-08-5bd0010, ffprobe git-2020-01-08-5bd0010, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] E2hRUXuEhgI: Downloading webpage
[youtube] E2hRUXuEhgI: Downloading video info webpage
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dev\Anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\dev\Anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\dev\Anaconda3\lib\site-packages\youtube_dl\extractor\youtube.py", line 2109, in _real_extract
    if codecs:
youtube_dl.utils.ExtractorError: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

####################################################
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
####################################################

0

## Description

I normally run this code on a list of simple YouTube URLs which I extract from the Notifications list. They work just fine from the browser.

**Comment by dbabbitt** [comment]
This is not an outdated version. When I run `youtube-dl --version` I get `2020.01.01`.

**Comment by dstftw** [comment]
From your log:
>[debug] youtube-dl version 2019.08.13
