### ISSUE TITLE
[PornHub] m3u8 file url instead of mp4

### ISSUE THREAD

**Issue by benoon** [ytdl-org/youtube-dl#23691]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
python youtube-dl -v -g https://www.pornhub.com/view_video.php?viewkey=ph5e1481ae7a934
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-g', u'https://www.pornhub.com/view_video.php?viewkey=ph5e1481ae7a934']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.01
[debug] Python version 2.7.5 (CPython) - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: ffmpeg 2.2.1, ffprobe 2.2.1
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
https://c1v-h.phncdn.com/hls/videos/202001/07/274640001/,480P_2000K,240P_400K,_274640001.mp4.urlset/index-f1-v1-a1.m3u8?LHVAcP3Qw5xvbUXJW0UKknj97_u4gJz5HvQC8_L2t4mMKUabuk4PlGYkSZps6HzZDe9WyHbmnd37ggcObFAblBhXqcaZLsOo1xbS5MKybIpH0d6gjO67hPSWJoiu_TV6lOyfW4hlN1oo00OaYoWmp9xjs187kM3j7sWDUhLX3TE876SarUlmT_bfYxDnzhBdfMfV0JFhVxCHke9CsAxs

```

## Description

-g option for many pornhub videos gives m3u8 file instead of mp4

some examples:

https://www.pornhub.com/view_video.php?viewkey=ph5dba442066391
https://www.pornhub.com/view_video.php?viewkey=ph5e04e908c958b
https://www.pornhub.com/view_video.php?viewkey=ph5e1481ae7a934

**Comment by benoon** [comment]
What is invalid here ?

**Comment by Hrxn** [comment]
There is no MP4 URL for selected formats?

**Comment by xXMrrpgXx** [comment]
Im having the same problem on a JS / NPM library, its a pornhub thing not a ytdl problem, But still Why mark it as invalid. If you dont know what happens just say it, dont pretend it didnt happend.
