### ISSUE TITLE
PornHub title incorrect when downloading with --cookies

### ISSUE THREAD

**Issue by jeff-geoff** [ytdl-org/youtube-dl#23694]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

NB: Let's call video ID "pervID" just in case.
## Verbose log

```
youtube-dl https://www.pornhub.com/view_video.php\?viewkey\=*pervID --cookies cookies.txt -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.pornhub.com/view_video.php?viewkey=*pervID', u'--cookies', u'cookies.txt', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.01
[debug] Python version 2.7.16 (CPython) - Darwin-19.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[PornHub] *pervID*: Downloading pc webpage
[PornHub] *pervID: Downloading m3u8 information
[PornHub] *pervID*: Downloading m3u8 information
[PornHub] *pervID*: Downloading m3u8 information
[PornHub] *pervID*: Downloading m3u8 information
[PornHub] *pervID: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u

```

## Description

When downloading private videos (i.e. using the --cookies flag), videos downloaded from pornhub save with 24 spaces, then a hyphen, then the "viewkey" (also referred to as pervID, just because...)

e.g.:
youtube-dl https://www.pornhub.com/view_video.php?viewkey=*pervID --cookies ~/cookies.txt

will output a file with the name:

'[ spaces                  ]-*pervID*.mp4'

Okay so:
One contributor ran this once, said "could not reproduce," and closed the issue unilaterally without soliciting more information.

Contributor is wrong; issue is reproducible on Ubuntu 18.04 LTS, Mac OS, and Debian Stretch with Python 3.7.

Windows, unknown.

Would be nice if whomever can't reproduce this would provide information about their platform before randomly closing an issue based on their anecdotal personal experience. (said anecdotal experience can not even be reproduced on my end, so maybe we can get someone else who is willing to _actually_ participate in tracing this bug.)  In fact, the config that does NOT reproduce this would be very useful to me in my own troubleshooting, so maybe provide that before closing my issue.

Thanks, sorry not sorry.

**Comment by dstftw** [comment]
Providing reproducible environment is your responsibility.

**Comment by jeff-geoff** [comment]
Environment is provided.  Read description.

Single user’s inability to reproduce does not close an issue.
I can't do anything with the information you provided prior to close unless you at least give me your debug from a properly functioning youtube-dl
