### ISSUE TITLE
CeskaTelevize - no video found

### ISSUE THREAD

**Issue by xmstspider** [ytdl-org/youtube-dl#23703]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.01.01**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl --verbose --add-metadata --ignore-errors --keep-video -o '%(title)s.%(ext)s' https://www.ceskatelevize.cz/ivysilani/12673563853-lidstvo-pribeh-nas-vsech/219382567420001
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--add-metadata', u'--ignore-errors', u'--keep-video', u'-o', u'%(title)s.%(ext)s', u'https://www.ceskatelevize.cz/ivysilani/12673563853-lidstvo-pribeh-nas-vsech/219382567420001']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.01
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-24-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[CeskaTelevize] 219382567420001: Downloading webpage
[CeskaTelevize] 219382567420001: Downloading JSON metadata
[CeskaTelevize] 219382567420001: Downloading JSON metadata
[CeskaTelevize] 219382567420001: Downloading JSON metadata
[CeskaTelevize] 219382567420001: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/user/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/user/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/user/.local/bin/youtube-dl/youtube_dl/extractor/ceskatelevize.py", line 201, in _real_extract
    self._sort_formats(e['formats'])
  File "/home/user/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Neither
https://www.ceskatelevize.cz/ivysilani/12673563853-lidstvo-pribeh-nas-vsech/219382567420001
or 
https://www.ceskatelevize.cz/porady/12673563853-lidstvo-pribeh-nas-vsech/219382567420001
are working.

It seems this affects only particular series, other on iVysilani are working well

**Comment by xmstspider** [comment]
OK, I found #23403 and it's exactly the same issue. Is there any way how to "emulate" enabling DRM like the browsers does?

**Comment by dstftw** [comment]
No.
