### ISSUE TITLE
Can I limit how long "%(title)s" will be?

### ISSUE THREAD

**Issue by wizzup** [ytdl-org/youtube-dl#23702]
## Checklist

- [ X] I'm asking a question
- [ X] I've looked through the README and FAQ for similar questions
- [ X] I've searched the bugtracker for similar questions including closed ones

## Question

Some youtube have very long title and I get 

```
ERROR: unable to open for writing: [Errno 36] File name too long:
```

Can string format be use with length limit?
Cant' find example in README

**Comment by dstftw** [comment]
Yes, read https://docs.python.org/2/library/stdtypes.html#string-formatting.

**Comment by sputnick-dev** [comment]
Hi,

what I does in a bash wrapper script : 

```
#!/bin/bash
  
filename=$(youtube-dl --get-filename -o '%(title)s.%(ext)s' "$@")
bytes_filename_size=$(wc -c <<< "$filename")

# cut first 200 bytes if filename is too long
if (($bytes_filename_size >= 250)); then
    filename=$(cut -c 1-250 <<< "$filename")
fi

exec youtube-dl -f best --restrict-filenames -o "$filename" "$@"
```
