### ISSUE TITLE
videobin.co

### ISSUE THREAD

**Issue by hitmanboy47** [ytdl-org/youtube-dl#23716]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://videobin.co/ybste0gc8mex
- Single video: 
- Playlist: 

## Description

Hi, I request that videobin.co be added to youtube-dl support.
Thanks for all the work you do.

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free
