### ISSUE TITLE
How to save video link in variable ?

### ISSUE THREAD

**Issue by superuser789** [ytdl-org/youtube-dl#23725]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I am using youtube-dl python library. I want to get the direct link of desired quality of youtube video.  I am using the following code which gets the direct links but prints them to stdout. I want to save it in a variable and use them to process further by ffmpeg.

```
from __future__ import unicode_literals
import youtube_dl

LINK='https://www.youtube.com/watch?v=9bZkp7q19f0'

class MyLogger(object):
    def debug(self, msg):
        msg=[]
        print('=====================')
        print(msg)

    def warning(self, msg):
        pass
    def error(self, msg):
        pass    
       
ydl_opts = {
    'format': 'bestvideo[height<=?720][fps<=?60][vcodec!=?vp9]+bestaudio/best',  
    'forceurl': True, 
     'quiet' : True,
     'skip_download' : True,
    'logger': MyLogger(),
    }


with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download([LINK])
```

**Comment by dstftw** [comment]
`extract_info`.
