### ISSUE TITLE
Url youtube-dl gives is unplayable

### ISSUE THREAD

**Issue by xzitlou** [ytdl-org/youtube-dl#23749]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2020.01.15**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Command

```
youtube-dl -vvv -g -f bestaudio https://www.youtube.com/watch?v=1V7aa9wyodw
```

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vvv', '-g', '-f', 'bestaudio', 'https://www.youtube.com/watch?v=1V7aa9wyodw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Git HEAD: 7d81ead
[debug] Python version 3.6.8 (CPython) - Linux-5.0.0-32-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
https://manifest.googlevideo.com/api/manifest/dash/expire/1579142438/ei/xngfXqePJoOAkATMjon4BA/ip/179.6.197.68/id/d55eda6bdc32a1dc/source/youtube/requiressl/yes/playback_host/r1---sn-ja5gv2x-aphs.googlevideo.com/mm/31%2C29/mn/sn-ja5gv2x-aphs%2Csn-hp57kn7e/ms/au%2Crdu/mv/m/mvi/0/pl/24/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/420000/vprv/1/mt/1579120761/fvip/1/fexp/23842630/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/ALgxI2wwRgIhAPtF_max0n-ULwI-GRBgA8IJitetk5uS3_gM-7dugj6QAiEA6uTy6ZDuDE643gF4tUbO2aCSpH23nmqd4NvRzVZcUEg%3D/lsparams/playback_host%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AHylml4wRQIhAPkjCMdkBo8kU45DP0c4W7kXoNoi_OOyqyUVtSmg0xIBAiAvKwFFC5K3JJpNHYGY7TsUsDim2S8NV0_iYpR-seXvkQ%3D%3D
```

## Description

When using the command:
```
youtube-dl -vvv -g -f bestaudio https://www.youtube.com/watch?v=1V7aa9wyodw
```
I'm getting a url that seems it wasn't parsed correctly, because it has .googlevideo twice in the url

**Comment by remitamine** [comment]
the URL is correct.

**Comment by xzitlou** [comment]
I realize that my youtube-dl was not updated in the laptop I was testing, but running the code show same issue.

**Comment by xenova** [comment]
You received a valid response. Although, I'm sure I know what you want. By passing the "--youtube-skip-dash-manifest" flag in the command, it will ensure you skip those urls beginning with "manifest.googlevideo.com".

This means your final command will be:
youtube-dl --youtube-skip-dash-manifest -vvv -g -f bestaudio https://www.youtube.com/watch?v=1V7aa9wyodw

You will then receive a "r1---sn-pn-woce.googlevideo.com" URL (Or something similar), which is playable in a browser.

Hope that helps!
