### ISSUE TITLE
FXNetworks URL falling back to generic downloader

### ISSUE THREAD

**Issue by cas4** [ytdl-org/youtube-dl#23754]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.15**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe --verbose --hls-prefer-native -o ".\Movies\The Star.mp4" --ap-mso Comcast_SSO --ap-username **** --ap-password *** http://fxnow.fxnetworks.com/movies-and-specials/the-star
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--hls-prefer-native', '-o', '.\\Movies\\The Star.mp4', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'http://fxnow.fxnetworks.com/movies-and-specials/the-star']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-61620-ge555e1b, ffprobe git-2017-12-23-d02289c
[debug] Proxy map: {}
[generic] the-star: Requesting header
[redirect] Following redirect to https://fxnow.fxnetworks.com/movies-and-specials/the-star
[generic] the-star: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-star: Downloading webpage
[generic] the-star: Extracting information
ERROR: Unsupported URL: https://fxnow.fxnetworks.com/movies-and-specials/the-star
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp43n_zyg3\build\youtube_dl\extractor\generic.py", line 3347, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://fxnow.fxnetworks.com/movies-and-specials/the-star
```

## Description

FX Networks URL must have changed since it is now falling back to the generic downloader.

**Comment by 2ShedsJackson** [comment]
FXNetworks started using DRM a few months ago. :(

**Comment by tv21** [comment]
I have also experienced this.

**Comment by JamKage** [comment]
Hi @tv21, had a look for you on the back of #22820 and it ended up being pretty trivial to add the FXNetworks brand to the Go extractor as well. Submitted a PR to fix.

**Comment by tv21** [comment]
> Hi @tv21, had a look for you on the back of #22820 and it ended up being pretty trivial to add the FXNetworks brand to the Go extractor as well. Submitted a PR to fix.

Thanks, I very much appreciate it but it doesn't seem to work for me, probably because some FX shows use a different URL format than your example URL.  Please see my comment on your PR.  I suspect it would be fairly trivial to make that format work also if you know what you are doing, but I don't.  Thank you again for taking a crack at this.
