### ISSUE TITLE
A potential way around the 429 issue?

### ISSUE THREAD

**Issue by pauldotknopf** [ytdl-org/youtube-dl#23758]
I ran into this issue with another script I was writing (not public, yet).

I discovered that I would get 429 when I do a naked GET request. However, the browser worked fine. After investigation, I discovered my script worked fine if I used the same headers that the Chrome Dev Tool was using. It turns out, it was the ```cookie``` header.

In my tool, I'm going to have a command that allows you to set what the headers will be for all requests.

```
> ./my-tool set-headers
Step 1: Open Chrome developer tools
Step 1: Open the Network tab on the developer tools
Step 2: Scroll down until a network request for "get_video" is made
Step 3: Right click the request and click "Copy -> Copy as cURL"
Step 4: Paste the contents of your clipboard below
curl command: ...
```

The tool will then store this value in the user's home directory and use it for every network request.

**Comment by thelebster** [comment]
https://github.com/ytdl-org/youtube-dl/issues/23638

**Comment by pauldotknopf** [comment]
I understand, this repo is flooded with these requests.

However, I thought I'd share a possible solution.

You'll never get a way to reproduce, but this issue is regional.

**Comment by danny-wu** [comment]
`youtube-dl --cookies cookies.txt`
