### ISSUE TITLE
Add 3rd party GUIs, apps, and utilities to README or other supplementary documentation

### ISSUE THREAD

**Issue by dantheman213** [ytdl-org/youtube-dl#23755]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.01.15**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Hi, I'd like to propose that a curated list of GUIs and/or supporting projects that use `youtube-dl` should be added to README or another supporting *.md file within the project repo.

I have been working on a GUI front-end for Windows 10 that uses automatically managed `youtube-dl` and `ffmpeg` under the hood to provide a simplified point-and-click experience of your tool for Windows 10 users. I'd like to add this project [dantheman213/JackTheVideoRipper](https://github.com/dantheman213/JackTheVideoRipper) to youtube-dl documentation along with any other notable or useful projects that use `youtube-dl` to accomplish its task.

**Comment by dstftw** [comment]
I don't see much point maintaining such list officially. There are just too many of them.
