### ISSUE TITLE
Nba League Pass error: unable to extract video id

### ISSUE THREAD

**Issue by pidiem** [ytdl-org/youtube-dl#23764]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.15**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

outube-dl --username ######## --password ######## https://watch.nba.com/game/20200116/PHXNYK --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://watch.nba.com/game/20200116/PHXNYK', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.15
[debug] Python version 2.7.17 (CPython) - Linux-5.3.11-200.fc30.x86_64-x86_64-with-fedora-30-Thirty
[debug] exe versions: none
[debug] Proxy map: {}
[NBA] PHXNYK: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/nba.py", line 137, in _real_extract
    path = remove_start(self._search_regex(r'data-videoid="([^"]+)"', webpage, 'video id'), '/')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Hi,

I try for the first time to download video from nba league pass. My Account is correct and the video are available if I check manually. I'm not sure if this is the good URL I used, I don't know how to check.

I guess you can find free video you want to check yourself.

**Comment by pidiem** [comment]
Why this issue have been closed ?

**Comment by remitamine** [comment]
it has been requested before.
