### ISSUE TITLE
[youtube] "Unable to log in: HTTP Error 400: Bad Request". thinks watchlater playlist doesn't exist.

### ISSUE THREAD

**Issue by hub2git** [ytdl-org/youtube-dl#23769]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.01.15**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v  https://www.youtube.com/playlist?list=WL 
[debug] System config: [u'-o', u'~/Video/youtube-dl/%(title)s.%(ext)s', u'--netrc']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/playlist?list=WL']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.15
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-26-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:watchlater] Downloading login page
[youtube:watchlater] Looking up account info
[youtube:watchlater] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube:watchlater] WL: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 3237, in _real_extract
    _, playlist = self._extract_playlist('WL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2737, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist does not exist.

```

## Description

I believe my netrc file is set up correctly. 
My youtube-dl.conf points to the netrc file.

I dunno why youtube-dl can't access my watchlater playlist. :(

**Comment by hub2git** [comment]
dstftw, duplicate of which? I see a 2018 one, and it says the bug has been fixed in a later  version. I have a 2020 version of youtube-dl and i have this bug.

**Comment by marcioandreyoliveira** [comment]
The same problem is happening to me.

I'm using the .exe for windows version v2020.06.06. I get the same message (_WARNING: Unable to log in: HTTP Error 400: Bad Request_) providing credentials in command line as well as in configuration file.

I agree with hub2git that it is a new bug.

Regards.

**Comment by OceanFifty** [comment]
The error persists when switching to another computer.
**Adding cookies** worked for me. 

However, I found it only working when selecting "**Http Only**" mode on the cookie extractor. 
I used https://addons.mozilla.org/en-US/firefox/addon/export-cookies-txt/?src=search on **Mozilla Firefox**.
https://i.imgur.com/IrtG7xg.png

Also, make sure you are using the **correct password**.

With this workaround **I still get the HTTP 400 - error**, but **it proceeds to download my liked videos playlist anyhow**. This means youtubedl **is** accessing my google account to get the job done despite the error.
