### ISSUE TITLE
Extract personal view details (timestamps, etc) from :ythistory (Watch History)?

### ISSUE THREAD

**Issue by kphamilton** [ytdl-org/youtube-dl#23760]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

I am mostly interested in using youtube-dl to grab information about my watch history on YT. I have been successfully able to download manifests for the videos in my history, but I as wondering if there is a way to get more personalized data returned to me? Mostly, I am interested in WHEN I watched the videos in my watch history. Is there a way to extract that from the response? The dates on present on the feed/history page so I assume it lives somewhere. Any help is appreciated! Thanks!

**Comment by dstftw** [comment]
Not possible.
