### ISSUE TITLE
Why VTT has "Kind:" and "Language:" field? VTT standard doesn't have these

### ISSUE THREAD

**Issue by 1c7** [ytdl-org/youtube-dl#23777]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Run this command
```
youtube-dl https://www.youtube.com/watch?v=T7Rv4tGRlfc --skip-download --sub-format vtt --write-sub
```

## Get a `.vtt` file
`The Future of Artificial Intelligence - Crash Course AI #20-T7Rv4tGRlfc.en.vtt`   
Which contain
```
WEBVTT
Kind: captions
Language: en

00:00:00.240 --> 00:00:05.410
Hey everyone, I’m Jabril and welcome to
the final episode of Crash Course AI.
```

## Question: Why `Kind: captions` and `Language: en` exists?

The specification [WebVTT: The Web Video Text Tracks Format](https://www.w3.org/TR/webvtt1/)  
  doesn't seem like contain `Kind:` and `Language:`
It also didn't pass this validator: [Live WebVTT Validator](https://quuz.org/webvtt/)

**Comment by dstftw** [comment]
Ask Youtube why.

**Comment by 1c7** [comment]
OK then, Thanks
