### ISSUE TITLE
youtube_dl Python class variables

### ISSUE THREAD

**Issue by anonieee** [ytdl-org/youtube-dl#23775]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

```
class ytdl_count(object):
    def debug(self, msg):
        count += 1

ydl_opts = {
    'logger': ytdl_count(),
}
    
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download([url])
```
I'm trying to count the number of lines of error youtube_dl is outputting in a Python script. But because of the limitations of local variables and the way the logging method is hardcoded, no information can escape or enter the logger class.

Is there anyway I can work around this?

**Comment by dstftw** [comment]
Obviously by not using local variables.
