### ISSUE TITLE
ERROR: This video is unavailable. (BPQNMsnuI8U)

### ISSUE THREAD

**Issue by caresrg** [ytdl-org/youtube-dl#23792]
I'm not sure why I can't download this video. It's playing fine in my browser. I've tried:

C:\Users\Care\Documents\YouTube DL>youtube-dl -o "c:\Temp\%(title)s.%(ext)s" --restrict-filenames -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 https://youtu.be/BPQNMsnuI8U
[youtube] BPQNMsnuI8U: Downloading webpage
[youtube] BPQNMsnuI8U: Downloading video info webpage
ERROR: This video is unavailable.

C:\Users\Care\Documents\YouTube DL>youtube-dl https://youtu.be/BPQNMsnuI8U
[youtube] BPQNMsnuI8U: Downloading webpage
[youtube] BPQNMsnuI8U: Downloading video info webpage
ERROR: This video is unavailable.

**Comment by sullyfischer** [comment]
I'm facing this issue right now

**Comment by caresrg** [comment]
It's working for me again. I had updated previously, but deleting the .exe and re-downloading it worked. Something must have gotten corrupted when I updated.

**Comment by sullyfischer** [comment]
Updating via `brew` fixed it for me. I guess Youtube must have changed something.

**Comment by pingsutw** [comment]
I'm facing the same issue when I try `youtube-dl https://www.youtube.com/watch\?v\=vvhC64hQZMk`
