### ISSUE TITLE
Output template variable that uses extractor info to provide website name

### ISSUE THREAD

**Issue by michealespinola** [ytdl-org/youtube-dl#23817]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.01.15**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

Looking at how `--download-archive` logs domain names that have extractors (and uses "generic" for those that don't), I would like to request an output template string that would give us the ability to use that same name for directory/file naming purposes.  This would be helpful for those of us that like to catalog/hoard our videos in a hierarchal structure.

Thank you for your consideration of this feature request!

**Comment by dstftw** [comment]
Read FAQ?
```
 - `extractor` (string): Name of the extractor
 - `extractor_key` (string): Key name of the extractor
```
