### ISSUE TITLE
Add "live_since" timestamp json key for live streams

### ISSUE THREAD

**Issue by nurupo** [ytdl-org/youtube-dl#23812]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.01.15**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

YouTube and Twitch live streams provide timestamps of when the ongoing live stream has started. It would be useful to have youtube-dl print those in its json output, e.g. so that you could see in mpv (which uses youtube-dl) how long a stream has been live for. So far youtube-dl provides only year, month and day date, but no exact time.

**Comment by dstftw** [comment]
1. `timestamp`.
2. Youtube does not provide timestamps.

**Comment by nurupo** [comment]
The "Started streaming N minutes ago" that you see on YouTube live streams is not exposed in YouTube's API?

**Comment by dstftw** [comment]
1. That's not a timestamp and it's not necessarily provided.
2. youtube-dl has nothing to do with Youtube API.
