### ISSUE TITLE
Output Template to use Original Filename

### ISSUE THREAD

**Issue by SwimmingLink** [ytdl-org/youtube-dl#23834]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is there a way to set the output template to use the original filenames as hosted (when downloading from direct video file links)? The closest that I can find is "-o %(url)s", but that includes the entire domain and directory before the filename where I only want that filename at the end of that (everything after the last "/" in the url).

**Comment by dstftw** [comment]
`-o "%(title)s.%(ext)s"`.
