### ISSUE TITLE
https://github.com/ytdl-org/youtube-dl/issues/11270

### ISSUE THREAD

**Issue by qome** [ytdl-org/youtube-dl#23832]
You have marked several bugs as duplicates of #11270. It is impossible to comment under that issue that the bug has returned because you locked it to collaborators. If you allow people to comment under that issue they can tell you the problem has come back without duplicate issues.

**Comment by dstftw** [comment]
There are at least 4 open authentication related issue #15184 #15423 #15926 #17216. This is more than enough.
