### ISSUE TITLE
Unable to use --postprocessor-args tag

### ISSUE THREAD

**Issue by brandazzle** [ytdl-org/youtube-dl#23859]
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

The command:
```
youtube-dl https://www.youtube.com/watch?v=GglsBHdKDBk -verbose —-postprocessor-args "-metadata album='x Infinity'"
```

## Verbose log

```
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: -m
```

## Description

The `--postprocessor-args` option appears to be nonfunctional and/or broken.

**Comment by dstftw** [comment]
Invalid first dash character.

**Comment by brandazzle** [comment]
I would like you to explain to me what, exactly, is "incomplete" about this.

**Comment by brandazzle** [comment]
Okay, so now I fixed that and it has a different problem. 
The new command:
```
https://www.youtube.com/watch?v=GglsBHdKDBk -verbose --postprocessor-args "-metadata album='x Infinity'"
```

The new verbose output: 
```
[debug] System config: []
[debug] User config: [u'-f', u'm4a/wav/mp3']
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=GglsBHdKDBk', u'-verbose', u'--postprocessor-args', u"-metadata album='x Infinity'"]
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: invalid rate limit specified
```

**Comment by dstftw** [comment]
Long options must start with double dash. Maybe you'll bother checking what you run?

**Comment by brandazzle** [comment]
I'm sorry, I don't understand what you mean. What is a "long option?"
