### ISSUE TITLE
Can I list Youtube playlist items without downloading?

### ISSUE THREAD

**Issue by stake2** [ytdl-org/youtube-dl#23865]
- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

Can I list Youtube Playlist Items without downloading the media or files?
I used --flat-playlist but it only shows "Downloading video X of X" and I wanted the titles of the videos to use in mps-yt.
![image](https://user-images.githubusercontent.com/39934220/73209523-221bd200-4127-11ea-8a65-06d1c4a6c9ea.png)

**Comment by section83** [comment]
Have you tried the --get-filename option ?

**Comment by keshavbhatt** [comment]
You can use `--dump-single-json --flat-playlist URL OF PLAYLIST` 
this will output only info of items in neat json format.

**Comment by S4RX** [comment]
it`s used for comand line, but how i can use it in my code?
