### ISSUE TITLE
cloud.mail.ru needed

### ISSUE THREAD

**Issue by muhammedfurkan** [ytdl-org/youtube-dl#23861]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

cloud.mail.ru site support needed

**Comment by slavakurilyak** [comment]
Requesting support for **cloud.mail.ru**
