### ISSUE TITLE
Add www.mxplayer.in

### ISSUE THREAD

**Issue by sumit-1988** [ytdl-org/youtube-dl#23881]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.mxplayer.in/movie/watch-hawa-bodol-movie-online-fb1ba803f64e2bd2c58dfa12b359d7e8?watch=true
- Single video:
- Playlist:

## Description

WRITE DESCRIPTION HERE

**Comment by Mouse753** [comment]
downloading by parsing MPD manually is possible but would live as well for full support by adding direct playback url 👍

**Comment by nimma0001** [comment]
> downloading by parsing MPD manually is possible but would live as well for full support by adding direct playback url

How to do this
