### ISSUE TITLE
404 error for fragments on youtube videos

### ISSUE THREAD

**Issue by mzso** [ytdl-org/youtube-dl#23882]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
[output.txt](https://github.com/ytdl-org/youtube-dl/files/4127486/output.txt)

## Description

For a while now (months) I get 404 errors and fragment retries. And rather slow downloads because of this.
Today I noticed that fragments are sometimes actually skipped after 10 retries. I'm not sure what that means. Will the video actually be missing parts? Ouch.
I didn't notice whole fragments being skipped and downloads failing until recently. Not sure why it started happening.

Strangely I didn't see an issue opened that seems relevant.

**Comment by dstftw** [comment]
Most likely intermittent youtube issue.

**Comment by mzso** [comment]
[**@dstftw**](https://github.com/dstftw) commented on [null](https://github.com/ytdl-org/youtube-dl/issues/23882#issuecomment-579804028 "2020-01-29T15:19:41Z - Replied by Github Reply Comments"):
> Most likely intermittent youtube issue.

Intermittent? I guess it depends how you look on it. It seems to happen rather often. The[ video I tested with](https://www.youtube.com/watch?v=abqy6F_tMhM) produced the error several times. Got interrupted several times. And it couldn't even be finished because merging failed partway through.
