### ISSUE TITLE
orf tvthek

### ISSUE THREAD

**Issue by avagraha** [ytdl-org/youtube-dl#23888]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x see description bottom] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

C:\Users>y -v --geo-bypass-country AT https://tvthek.orf.at/live/Expe
ditionen-Amerikas-Naturwunder-6-8-Im-Gebirge-der-Giganten/14050041
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--geo-bypass-country', 'AT', 'https://tv
thek.orf.at/live/Expeditionen-Amerikas-Naturwunder-6-8-Im-Gebirge-der-Gigan
ten/14050041']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-94698-g83e0b71-Reino, ffprobe N-94698-g83e0b
71-Reino, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 77.117.244.217 (AT) as X-Forwarded-For.
[orf:tvthek] 14050041: Downloading webpage
[orf:tvthek] 14050041: Downloading f4m manifest
WARNING: Unable to download f4m manifest: <urlopen error [Errno 11001] geta
ddrinfo failed>
[orf:tvthek] 14050041: Downloading f4m manifest
WARNING: [orf:tvthek] 14050041: Failed to parse XML syntax error: line 1, c
olumn 0
[orf:tvthek] 14050041: Downloading f4m manifest
WARNING: [orf:tvthek] 14050041: Failed to parse XML syntax error: line 1, c
olumn 0
[orf:tvthek] 14050041: Downloading f4m manifest
WARNING: [orf:tvthek] 14050041: Failed to parse XML syntax error: line 1, c
olumn 0
[orf:tvthek] 14050041: Downloading m3u8 information
ERROR: This video is not available from your location due to geo restrictio
n
You might want to use a VPN or a proxy server (with --proxy) to workaround.

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw
0w300z1\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw
0w300z1\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw
0w300z1\build\youtube_dl\extractor\orf.py", line 96, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw
0w300z1\build\youtube_dl\extractor\common.py", line 940, in raise_geo_restr
icted
youtube_dl.utils.GeoRestrictedError: This video is not available from your
location due to geo restriction

## Description

WRITE DESCRIPTION HERE

  #23741
  The Fix
https://github.com/ytdl-org/youtube-dl/commit/90ea83c64d904587992105fb4506e80f6abb28b5
  does not resolve geo issues on ORF tvthek. is it working on yourside?

**Comment by dstftw** [comment]
It's not supposed to work in all cases.

**Comment by avagraha** [comment]
In what other ORF cases it is working?
so I could try if your have other ORF links, thanks.


  ----- Original Message -----
