### ISSUE TITLE
toggle.sg has been renamed as mewatch.sg

### ISSUE THREAD

**Issue by hohawong** [ytdl-org/youtube-dl#23895]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.01.24**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\youtubedl>youtube-dl "https://www.mewatch.sg/en/video/series/lny-filmlets/ep2/908875" --ffmpeg-location C:\ffmpeg
[generic] 908875: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 908875: Downloading webpage
[generic] 908875: Extracting information
ERROR: Unsupported URL: https://www.mewatch.sg/en/video/series/lny-filmlets/ep2/908875

```

## Description

toggle.sg has been renamed as mewatch.sg, please correct all URLs from toogle.sg to mewatch.sg

News:

https://www.marketing-interactive.com/mediacorp-revamps-toggle-meradio-and-meclub/

**Comment by Kkabadd** [comment]
And please, if you could fix for it can download subtitles too, for toggle it could not do it.  Thanks
