### ISSUE TITLE
Broken site TV5MondePlus: TV5MONDE+

### ISSUE THREAD

**Issue by forapreder** [ytdl-org/youtube-dl#23907]
Microsoft Windows [Version 10.0.18363.592]
(c) Корпорация Майкрософт (Microsoft Corporation), 2019. Все права защищены.

C:\Users\Internet>youtube-dl -v https://revoir.tv5monde.com/toutes-les-videos/series-fictions/neuf-jours-en-hiver-neuf-jours-en-hiver
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://revoir.tv5monde.com/toutes-les-videos/series-fictions/neuf-jours-en-hiver-neuf-jours-en-hiver']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[generic] neuf-jours-en-hiver-neuf-jours-en-hiver: Requesting header
WARNING: Falling back on generic information extractor.
[generic] neuf-jours-en-hiver-neuf-jours-en-hiver: Downloading webpage
[generic] neuf-jours-en-hiver-neuf-jours-en-hiver: Extracting information
ERROR: Unsupported URL: https://revoir.tv5monde.com/toutes-les-videos/series-fictions/neuf-jours-en-hiver-neuf-jours-en-hiver
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300z1\build\youtube_dl\extractor\generic.py", line 3350, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://revoir.tv5monde.com/toutes-les-videos/series-fictions/neuf-jours-en-hiver-neuf-jours-en-hiver

WRITE DESCRIPTION HERE
Broken site TV5MondePlus: TV5MONDE+ 
This site on https://revoir.tv5monde.com now.
New interface.

**Comment by nazmifr** [comment]
Okay, they just changed the domain, I've edited the  I'll issue a pull request to change:
```
    _VALID_URL = r'https?://(?:www\.)?tv5mondeplus\.com/toutes-les-videos/[^/]+/(?P<id>[^/?#]+)'
```
to
```
    _VALID_URL = r'https?://(?:www\.)?revoir\.tv5monde\.com/toutes-les-videos/[^/]+/(?P<id>[^/?#]+)'

```
