### ISSUE TITLE
support for https://popcorntimes.tv

### ISSUE THREAD

**Issue by LAZA74** [ytdl-org/youtube-dl#23904]
popcorntimes.tv is a new free-to-use platform for Germany, Swiss and Austria

Find more infos in this article:
https://www.heise.de/newsticker/meldung/Streamingdienst-Popcorntimes-laesst-alte-Filme-wieder-aufleben-4649421.html

**Comment by frostworx** [comment]
sorry if this is obvious, but what does incomplete mean in this context?

**Comment by Surkal** [comment]
https://github.com/ytdl-org/youtube-dl#bugs

**Comment by chrysn** [comment]
That when the original author opened the issue, they did not pick "site feature request" and filled out the form that is described in the template that is shown then.

**Comment by frostworx** [comment]
ah interesting! thank you very much, chrysn!
