### ISSUE TITLE
Bot that locks issues preventing me from commenting what was wrong

### ISSUE THREAD

**Issue by nazmifr** [ytdl-org/youtube-dl#23910]
Just raised an issue thinking I had latest version, it got closed and I realised what was wrong and then commented to help other people who updated using sudo pip3 install --upgrade when **sudo shouldn't be used**.

My comment got removed and the thread blocked which will cause other people in the same situation to not find the solution. Could a human that's a contributor here comment the solution on this thread:

https://github.com/ytdl-org/youtube-dl/issues/23909

or any other one about this issue so that other peope don't have to create issues thinking 

```
Oh crap indeed, to everyone that's stupid as I am, if you update youtube-dl on linux with pip, don't use sudo or the updated version will only be available as root...

pip3 install --upgrade youtube-dl
```

**Comment by dstftw** [comment]
Again: this has nothing to do with sudo. Most likely you have multiple youtube-dl/pip instances installed and messed PATH environment.
