### ISSUE TITLE
Output release_date string variant

### ISSUE THREAD

**Issue by secme** [ytdl-org/youtube-dl#23914]
## Checklist

- [*] I'm reporting a feature request
- [*] I've verified that I'm running youtube-dl version **2020.01.24**
- [*] I've searched the bugtracker for similar feature requests including closed ones

## Description

Output release_date string variant. It would be helpful for ingesting these files into Plex to have the date formatted as YYYY-MM-DD with the hypens in the middle. For backwards compatibility could this be added as a different variant, say release_date2?

**Comment by jcharr1** [comment]
@secme If you're still looking for a solution to this, I just wrote a very simple Ruby script to replace the 'YYYYMMDD' part of the filename to 'YYYY-MM-DD.' You can save this to a file and run it with youtube-dl's `--exec` switch.

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

old_filename = ARGV[0]

if old_filename
	new_filename = old_filename.gsub(/(\d\d\d\d)(\d\d)(\d\d)/) do
		"#{Regexp.last_match(1)}-#{Regexp.last_match(2)}-#{Regexp.last_match(3)}"
	end
	puts "New filename is '#{new_filename}'"
	File.rename(old_filename, new_filename)
else
	puts 'No filename given!'
end
```
