### ISSUE TITLE
.opus files bugged unable to delete.

### ISSUE THREAD

**Issue by LiamR101** [ytdl-org/youtube-dl#23913]
So i downloaded a song from youtube with the --extract-audio part, and it made a .opus file.
This file is completly bugged, can't delete it, can't rename it, can't remove it, infact doing any of the above crashes windows explorer.

I tried Malware Bytes file deleter, FileAssassin, it literally crashed when trying to delete it, and CMD "del /f "Filename" does nothing either.

This is F'ed beyond measure...

**Comment by rautamiekka** [comment]
You might be able to delete it under a Linux, and run `CHKDSK X: /V /R` as Admin afterwards in case the filesystem is corrupted.
