### ISSUE TITLE
youtube-dl only downloading some videos of YouTube channel. How to download them all?

### ISSUE THREAD

**Issue by l0ophole** [ytdl-org/youtube-dl#23929]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I am trying to download all the videos on a channel that has 59 videos on it but youtube-dl is only detecting and downloading 11 videos from the channel. I searched through the open and closed issues but could not find one that matched my exact issue. What should I do differently? This is the command that I am using:

>$ youtube-dl -v --cookies "cookies.txt" -i -f best[height\<=360] "https://www.youtube.com/channel/UC_AkEUxYb7TvE0PPHQxQIog"

**Comment by jojoke** [comment]
When you go to your youtube channel, you can go to the tab "videos".
Here usually, you have a link "play all". Click on it.
![Capture1](https://user-images.githubusercontent.com/15250062/73597454-698dce00-452c-11ea-9c3e-8cd384cfc97e.PNG)
You'll be launched to the playlist of every video of that channel. 
You have two ways to get the link of the playlist alone.
1. You can click on the title of the playlist and get redirected to the playlist
![Capture2](https://user-images.githubusercontent.com/15250062/73597474-b4a7e100-452c-11ea-8bde-24c0fdfc6d67.PNG)
From here, you'll have the link of the playlist
![Capture3](https://user-images.githubusercontent.com/15250062/73597482-c5585700-452c-11ea-8553-3454302ba1e0.PNG)

2. You can take from the link of the page you are in, only the ID of the playlist

![Capture4](https://user-images.githubusercontent.com/15250062/73597507-f8024f80-452c-11ea-861a-11f727db574f.PNG)

After that, you just have to download the whole playlist.
Hope it helps.

**Comment by dstftw** [comment]
#16212
