### ISSUE TITLE
error: invalid rate limit specified after python update

### ISSUE THREAD

**Issue by seahorse41** [ytdl-org/youtube-dl#23923]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -version
[debug] System config: []
[debug] User config: [u'--restrict-filenames', u'-o', u'~/Downloads/%(title)s.%(uploader)s.%(id)s.%(format_id)s-%(height)sp.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'-version']
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: invalid rate limit specified

```

## Description

youtube-dl was working this morning fine, My debian 8 system popped up a notification that OS Upgrades are available, I reviewed it included python-apt and closed that window.
Half an hour later youtube-dl stopped with errors.
/var/log/unattended-upgrades says:
2020-02-01 06:32:18,366 INFO Packages that will be upgraded: firefox-esr python-apt python-apt-common python3-apt

$ python --version
Python 2.7.13
$ python3 --version
Python 3.5.3

**Comment by dstftw** [comment]
`--version` not `-version`.
