### ISSUE TITLE
"exec" option, but BEFORE downloading file

### ISSUE THREAD

**Issue by zmechu** [ytdl-org/youtube-dl#23921]
## Checklist

- [ x] I'm reporting a feature request
- [ x] I've verified that I'm running youtube-dl version **2020.01.24**
- [ x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

There is "_-exec CMD_" option, which allows to "_Execute a command on the file after downloading [...]_".

I'm trying to make workaround for "429: Too Many Requests" error with proxy changing "on the fly". Means - changing proxy every youtube-dl run.

Is there a way to run any script/command **BEFORE** file downloading? 

If no - I'm requesting for this feature.

**Comment by dstftw** [comment]
`--exec` operates on the final file and does not make any sense before download since the file does not exist. What you must do is catch 429 error and do a re-run.

**Comment by zmechu** [comment]
It makes a sense, in my opinion. In the case of 429 error I need to catch error code, write a script to re run etc.

My simplest idea is such:
1. youtube-dl runs
2. before fetching video file:
   2a. Got list 3-4 proxies (form file/list or sth like that)
   2b. Take (for example: random) one of them
   2c. Put selected proxy into youtube-dl.conf
3. fetching youtube file
4. end.

In this situation I'll get 429 error minimum 3-4x times less. Also, 3-4 IPs gives me chance to never got 429 error because of "IP distribution" (runs for example 100x youtube-dl from one IP  leads to 429 error, running 25x from 4 IPs - never).

**Comment by dstftw** [comment]
As already said you don't need any exec-before-download for such scenario.
