### ISSUE TITLE
Please fix TikTok Download

### ISSUE THREAD

**Issue by Mo-0hammed** [ytdl-org/youtube-dl#23935]
Please fix TikTok Download : 
youtube-dl 'https://www.tiktok.com/@lh_yty/video/6787326684208139526' '--no-playlist' '--ignore-config' '--write-info-json' '--format=best[ext=mp4]' '--output=6787326684208139526.%(ext)s'

The results are:
```
[generic] 6787326684208139526: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6787326684208139526: Downloading webpage
[generic] 6787326684208139526: Extracting information
[download] Downloading playlist: Hitawi   || هيتاوي🌛 on TikTok
[generic] playlist Hitawi   || هيتاوي🌛 on TikTok: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
ERROR: requested format not available
```

**Why does not support this format
Or is there a problem or any formulas that deal with it?**

**Comment by dstftw** [comment]
Stop posting duplicates.
