### ISSUE TITLE
ERROR: Unable to extract data - PLATZI ACADEMY - https://platzi.com/

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#23944]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-v', 'https://platzi.com/clases/aprender']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.7.6 (CPython) - Linux-5.4.13-201.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
[debug] exe versions: none
[debug] Proxy map: {}
[PlatziCourse] Downloading login page
[PlatziCourse] Logging in
[PlatziCourse] aprender: Downloading webpage
```

## Description

When I try to download a video from this page I always get an error that there is no data to download and this error appears:

ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
ie_result = ie.extract(url)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
ie_result = self._real_extract(url)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/platzi.py", line 190, in _real_extract
self._search_regex(r'data\s*=\s*({.+?})\s*;', webpage, 'data'),
File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
I've updated the PR code for #30548. Please test and follow up [there](https://github.com/ytdl-org/youtube-dl/pull/30548).
