### ISSUE TITLE
ERROR: No video formats found - PLATZI ACADEMY - https://platzi.com/

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#23942]
Version of youtube-dl is :  
2020.01.24

Page for download videos: 
https://platzi.com/

Code Executed from console: 
youtube-dl -v https://platzi.com/clases/1608-aprender/25974-recap-aprender-online-efectivamente-esp/

Result: 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://platzi.com/clases/1608-aprender/25974-recap-aprender-online-efectivamente-esp/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.7.6 (CPython) - Linux-5.4.13-201.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
[debug] exe versions: none
[debug] Proxy map: {}
[Platzi] 25974: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/platzi.py", line 140, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by GlowerTvg** [comment]
I am currently getting this same error again when trying to download from the Platzi platform, how can I solve it?
Thanks :)

**Comment by dirkf** [comment]
I've updated the PR code for #30548. Please test and follow up [there](https://github.com/ytdl-org/youtube-dl/pull/30548).
