### ISSUE TITLE
This Old House changed URLs again

### ISSUE THREAD

**Issue by sjthespian** [ytdl-org/youtube-dl#23951]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
> youtube-dl -v https://www.thisoldhouse.com/21113884/s41-e13-paradise-lost
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.thisoldhouse.com/21113884/s41-e13-paradise-lost']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.7.2 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[generic] s41-e13-paradise-lost: Requesting header
WARNING: Falling back on generic information extractor.
[generic] s41-e13-paradise-lost: Downloading webpage
[generic] s41-e13-paradise-lost: Extracting information
ERROR: Unsupported URL: https://www.thisoldhouse.com/21113884/s41-e13-paradise-lost
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3350, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.thisoldhouse.com/21113884/s41-e13-paradise-lost
```

## Description

This Old House has changed their URLs again, I'm assuming this will require a change similar to the one in issue #11271. I haven't had a chance to dig into the code yet to see if it's that simple of a change. However from a look at a couple of URLs, it looks like the newer urls are now in the format of https://www.thisoldhouse.com/<serial_number>/s<season>-e<episode>-<episode_title> (at least for This Old House and Ask This Old House). However, looking at older episodes, I'm seeing urls like https://www.thisoldhouse.com/<subseries_title>/<serial_number>/<episode_title>

Examples:
* https://www.thisoldhouse.com/21113884/s41-e13-paradise-lost
* https://www.thisoldhouse.com/21067015/pining-for-old-pine-the-westerly-project
* https://www.thisoldhouse.com/charleston-houses/21053714/rainbow-row-the-charleston-houses-2018

**Comment by monty124** [comment]
Hi there, 
This has fixed new links and broken the old links.
new sxx-exx links work
e.g. these work
https://www.thisoldhouse.com/21133625/s41-e15-no-pain-no-gain
https://www.thisoldhouse.com/21133650/s18-e15-indoor-garden-fireplace-hearth
but for example links like 
https://www.thisoldhouse.com/21083431/seaside-transformation-the-westerly-project 
and
https://www.thisoldhouse.com/season-18-ask-toh/21083433/ceiling-light-tool-storage-ask-toh
do not work

`>youtube-dl.exe --get-id https://www.thisoldhouse.com/21083431/seaside-transformation-the-westerly-project -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--get-id', 'https://www.thisoldhouse.com/21083431/seaside-transformation-the-westerly-project', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2019-10-31-b414cff, ffprobe git-2019-10-31-b414cff
[debug] Proxy map: {}
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\thisoldhouse.py", line 42, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

like the original issue, there are a bunch of different links from their site now..

**Comment by dmwyatt** [comment]
Yeah @remitamine, I can confirm @monty124's report.

**Comment by jsmith1299** [comment]
Issue still exists...why was issue closed?

**Comment by plk0507** [comment]
Any update to this issue?

**Comment by monty124** [comment]
@plk0507  (and anyone else who stumbles on this) I have not tried it on TOH, but you may get some luck with yt-dlp https://github.com/yt-dlp/yt-dlp
