### ISSUE TITLE
Function Request : Auto Retry on Unstable Internet Connections. [URL_OPEN_ERROR]

### ISSUE THREAD

**Issue by bboy519** [ytdl-org/youtube-dl#23967]
[youtube] oTXROIkvENs: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 0] Error> (caused by URLError(OSError(0, 'Error')))
[download] Downloading video 2045 of 2618
[youtube] KWYD5id4HtQ: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 0] Error> (caused by URLError(OSError(0, 'Error')))

Youtube-dl didn't even retry downloading the videos. The UrlOpenError is caused by unstable Internet Connection with sightly higher package loss.

**Comment by kaine1973** [comment]
I am having this problem too. Hope adding some retry method.

**Comment by dstftw** [comment]
You can't reliably detect whether it's caused by unstable connection or not.
