### ISSUE TITLE
Get duration before (or while) downloading

### ISSUE THREAD

**Issue by kr4ssi** [ytdl-org/youtube-dl#23968]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

I would like to get the duration of a file before it finished downloading, is that already somehow possible by piping, or if I put ffprobe as external downloader?
I think the best would be to get the duration from the same stream as it's downloading, since it would decrease requests to the server.

**Comment by dstftw** [comment]
Make a pre-run for metadata extraction.

**Comment by kr4ssi** [comment]
There is no duration in metadata for every hoster.
