### ISSUE TITLE
not able to download video from youtube

### ISSUE THREAD

**Issue by vidu1986** [ytdl-org/youtube-dl#23962]
Getting Error:

Youtube said: This video is unavailable.

**Comment by vidu1986** [comment]
![image](https://user-images.githubusercontent.com/19190714/73776634-1dea5700-47ae-11ea-9a70-1e1e5ad6b49c.png)

**Comment by Morpny-kun** [comment]
I've been getting the same error. :( 
![Screenshot from 2020-02-05 08-26-32](https://user-images.githubusercontent.com/44739457/73808354-75f67d00-47f1-11ea-804a-ede014235468.png)

**Comment by Morpny-kun** [comment]
> Getting Error:
> 
> Youtube said: This video is unavailable.

Mate try : `sudo pip install --upgrade youtube_dl`
It started working for me after using this command.

**Comment by np** [comment]
Same issue, version: 2019.01.17
