### ISSUE TITLE
Info if formats have to get merged after download if -f best and --merge-output-format mp4

### ISSUE THREAD

**Issue by kr4ssi** [ytdl-org/youtube-dl#23969]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I've noticed, I get a warning, if formats have to get merged into *.mkv after downloading, before the download starts, but not if I put --merge-output-format mp4.

**Comment by dstftw** [comment]
`-f best` has nothing to do with `--merge-output-format`.
In case of mergeable formats explicit `--merge-output-format` will not output any warning and will try merging into format specified.
