### ISSUE TITLE
IMDB Trailer Link Not longer working 

### ISSUE THREAD

**Issue by michael1t** [ytdl-org/youtube-dl#23961]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.01.24**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

C:\>youtube-dl.exe -v "https://www.imdb.com/video/imdb/vi997965593?ref_=cs_ov_vi" -o mike.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.imdb.com/video/imdb/vi997965593?r
ef_=cs_ov_vi', '-o', 'mike.mp4']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[imdb] 997965593: Downloading webpage
ERROR: Unable to extract video metadata; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
 update. Be sure to call youtube-dl with the --verbose flag and include its comp
lete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300
z1\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300
z1\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300
z1\build\youtube_dl\extractor\imdb.py", line 54, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpw0w300
z1\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video metadata; please re
port this issue on https://yt-dl.org/bug . Make sure you are using the latest ve
rsion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --ver
bose flag and include its complete output.



```

I downloaded IMDB Trailers 
## Description

This just stopped working a few weeks ago ... worked fine before

**Comment by michael1t** [comment]
the above 480p video link is below :+1: https://imdb-video.media-imdb.com/vi997965593/1434659607842-pgv4ql-1579014693892.mp4?Expires=1581291510&Signature=Al2ThczIthcUJqmHS9a13JcILiDusNUbh9Kl7qDzUcBUCvtHvcYs0QN02AOAJtibXUGVoaVHYoM6J0gSk2tiA6BOinam9lKTyGQo4XlY89GecAaeCcK1~w24GVrRXYxLviNIICL6gLnWKS7OwLoFsjUjebCsBfIIvNCo1Jr6XnpXRdyZqjVV4XntlEi5yz6niW0POuoG7sNUAMQiFmA2~GBj5zJM02lxQ9a-VKthldTZrBydoSg~60JOS0xLrT8Ey3629gcJ3O7JBbwzE6ELZ5lm~beNx0GNl2pAZ7Dgz-jHUI4crkJA3NYE6VN6N9s5S3g0LJ-8yOIxslqX9xxTJw__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA

**Comment by michael1t** [comment]
C:\>youtube-dl.exe -v "https://imdb-video.media-imdb.com/vi99
7965593/1434659607842-pgv4ql-1579014693892.mp4?Expires=1581291510&Signature=Al2T
hczIthcUJqmHS9a13JcILiDusNUbh9Kl7qDzUcBUCvtHvcYs0QN02AOAJtibXUGVoaVHYoM6J0gSk2ti
A6BOinam9lKTyGQo4XlY89GecAaeCcK1~w24GVrRXYxLviNIICL6gLnWKS7OwLoFsjUjebCsBfIIvNCo
1Jr6XnpXRdyZqjVV4XntlEi5yz6niW0POuoG7sNUAMQiFmA2~GBj5zJM02lxQ9a-VKthldTZrBydoSg~
60JOS0xLrT8Ey3629gcJ3O7JBbwzE6ELZ5lm~beNx0GNl2pAZ7Dgz-jHUI4crkJA3NYE6VN6N9s5S3g0
LJ-8yOIxslqX9xxTJw__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA" -o mike.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://imdb-video.media-imdb.com/vi997965593
/1434659607842-pgv4ql-1579014693892.mp4?Expires=1581291510&Signature=Al2ThczIthc
UJqmHS9a13JcILiDusNUbh9Kl7qDzUcBUCvtHvcYs0QN02AOAJtibXUGVoaVHYoM6J0gSk2tiA6BOina
m9lKTyGQo4XlY89GecAaeCcK1~w24GVrRXYxLviNIICL6gLnWKS7OwLoFsjUjebCsBfIIvNCo1Jr6Xnp
XRdyZqjVV4XntlEi5yz6niW0POuoG7sNUAMQiFmA2~GBj5zJM02lxQ9a-VKthldTZrBydoSg~60JOS0x
LrT8Ey3629gcJ3O7JBbwzE6ELZ5lm~beNx0GNl2pAZ7Dgz-jHUI4crkJA3NYE6VN6N9s5S3g0LJ-8yOI
xslqX9xxTJw__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA', '-o', 'mike.mp4']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 1434659607842-pgv4ql-1579014693892: Requesting header
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://imdb-video.media-imdb.com/vi997965593/14
34659607842-pgv4ql-1579014693892.mp4?Expires=1581291510&Signature=Al2ThczIthcUJq
mHS9a13JcILiDusNUbh9Kl7qDzUcBUCvtHvcYs0QN02AOAJtibXUGVoaVHYoM6J0gSk2tiA6BOinam9l
KTyGQo4XlY89GecAaeCcK1~w24GVrRXYxLviNIICL6gLnWKS7OwLoFsjUjebCsBfIIvNCo1Jr6XnpXRd
yZqjVV4XntlEi5yz6niW0POuoG7sNUAMQiFmA2~GBj5zJM02lxQ9a-VKthldTZrBydoSg~60JOS0xLrT
8Ey3629gcJ3O7JBbwzE6ELZ5lm~beNx0GNl2pAZ7Dgz-jHUI4crkJA3NYE6VN6N9s5S3g0LJ-8yOIxsl
qX9xxTJw__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA'
[download] Destination: mike.mp4
[download] 100% of 17.50MiB in 00:06

**Comment by michael1t** [comment]
youtube-dl is no longer returning the above link

**Comment by michael1t** [comment]
not  closed  ... still not working

**Comment by jhalvors-school** [comment]
I discovered this issue as well while trying to fix another, unrelated bug in the IMDB extractor. May try and tackle it next depending on how hard of a problem it turns out to be.

**Comment by michael1t** [comment]
Hello

I was using it and the web page had the trailer url link complete.
I looked over the NEW Page and now it just passes uri to player and
player builds url.
I hope that helps  ...
I found a webpage that can get it ok from the NEW code but I really
like youtube-dl
Is there any thing I can Help you with to Make it easier to debug ..?

Here is a sample url for a trailer page if it helps ...
I did not mean to close the issue I clicked the wrong button ... Sorry
..
https://www.imdb.com/video/imdb/vi2031927065?ref_=cs_ov_vi

Here is the url that is displayed in WIFI Shark for the 480p ...
https://imdb-video.media-imdb.com/vi2031927065/1434659454657-dx9ykf-1576539266200.mp4?Expires=1581721004&Signature=cSZar0Cw4Q7FC8hfBoXGdsA1Cms~xLDp2DppKxQWi8E6khbqKJLAhnh6MLKBF~VSfxKQjfDVsctouZzM4WKHlHSMLhBbX7NZZ2deJHjdmnKJEdomAjtJJ5opRpZFgil~XKme42sWEgAgAE~Y6~ZvZ387u1s9PTxhZ4OCM149ReygoVpFz9mCVd7uS8Ckj4BVEFxN1s9m9DEHdPS~MXTlYM9dEglMyhd0d0WyLcrrmL5A7JKJZEG0o0mUa4jpkvX5dG9JJA0-e~VJSXvLkpAdGW~OZmuPw8YyHAKTeR3JofLzEfX-2Pf7INQ1~waVrsgdJJrEmugCpAUn~YUZF4wmsQ__&Key-Pair-Id=APKAIFLZBVQZ24NQH3KA

Thanks Please let me know if I can help you test the fix

Michael T.

**Comment by michael1t** [comment]
Hello

Can you tell me what else the youtube-dl can extract from the IMDB ... I did
not find much info on it ....

thanks

Michael T.

**Comment by michael1t** [comment]
Hello

I wrote some IMDB search code to extract IMDB info(works Great).  I
just do NOT understand How the player is getting the URL from uri info
... A simple code example would be great ...if you are willing to
Share ... I would be more than happy to share my code if you are
interested ...

thanks

Michael T.

**Comment by jhalvors-school** [comment]
Oof, 3 messages asking for more info. I will be honest, I have *just* started contributing to youtube-dl, so I still have a bit of digging to do to figure out how everything works.

**Comment by michael1t** [comment]
Hello

Ok ... I have to travel for work this week ... But Will try to answer emails
as possible ...

thanks

Michael T.

**Comment by michael1t** [comment]
hey

did you have any headway with the IMDB ?

Michael T.

**Comment by michael1t** [comment]
hey

Can you tell me the parms for the imdb extractor and what it is to do
and what it is not doing

thanks

Michael T.

**Comment by jhalvors-school** [comment]
> hey did you have any headway with the IMDB ? Michael T.

Hello Michael,

I did not end up being the one to fix the IMDB extractor, that would be dstftw in this commit:
https://github.com/ytdl-org/youtube-dl/commit/5d9f6cbc5afa033b6f1cfd2abe4327e366da2ad1

From what I could tell when I was analyzing this issue, the HTML of the IMDB website had appeared to have changed, making the _real_extract() method which was parsing it invalid. The current version appears to make use of a new JSON API.

**Comment by michael1t** [comment]
Hello

can you send me a example of a youtube-dl imdb extract command that works

thanks

Michael T.
