### ISSUE TITLE
How do I know where I am for "ERROR: The uploader has not made this video available in your country."

### ISSUE THREAD

**Issue by Reapor-Yurnero** [ytdl-org/youtube-dl#23972]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have a VPS in US and another one in singapore, trying to download some specific music, like "darkness" from eminem and "bad guy" but it shows ERROR: The uploader has not made this video available in your country or this video is not available. I tried to do exactly the same thing on the local machine. But I found it works perfect no matter in singapore or us. I feel very confused and I check the ip address of my vps and confirmed that they are really located in us and singapore. But in this case how could youtube block this? Is there any possible way to show where youtube think I'm located for each request? (Use --geo-bypass does not help)

**Comment by dstftw** [comment]
Youtube does not report its guessed location.

**Comment by Reapor-Yurnero** [comment]
> Youtube does not report its guessed location.

Do you have any idea on how to solve this in that case? What might cause a server in us not be able to access a video open in us?

**Comment by dstftw** [comment]
Solve what? You does not even bother to provide any context.

**Comment by Reapor-Yurnero** [comment]
Cuz I don't want to bother readers with more than enough info.

$ youtube-dl  https://www.youtube.com/watch?v=DyDfgMOUjCI
[youtube] DyDfgMOUjCI: Downloading webpage
[youtube] DyDfgMOUjCI: Downloading video info webpage
ERROR: The uploader has not made this video available in your country.
Sorry about that.

As I have said, I do exactly the same thing on my own computer in the same country, and it works.

**Comment by dstftw** [comment]
Working on your own computer via your own outgoing IP means effectively nothing. What you must check is whether it does work from browser via VPN with clean session, if not then you can't make youtube-dl work either.
