### ISSUE TITLE
Is the --write-annotations option working as intended?

### ISSUE THREAD

**Issue by libransser** [ytdl-org/youtube-dl#23973]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, I'm downloading some YouTube videos to archive them and I'm wondering if the `--write-annotations` option is working as intended. For example, if you visit the following YouTube video in a browser using the desktop version of the site you can see an icon in the top right corner of the video, it's a letter "i" in a circle:

```
https://www.youtube.com/watch?v=l9CI6KSV560
```

If you click on that icon, a list of links appears. For this particular video it contains a link to another video of the same channel, two playlists of the same channel, and a link to another channel. If I open the Settings menu in the video (the gear icon) and turn the switch "Annotations" off then the icon disappears, telling me that those are the annotations.

However, whenever I use the `--write-annotations` option the resulting file written (extension `annotations.xml`) doesn't include any of the links that appear in that icon. I have downloaded close to 1,000 videos and none of the `annotations.xml` files include any additional links.

Is this really working as expected? Does the `--write-annotations` option actually refer to the deprecated YouTube annotations? Or I'm missing something? If so, how can I download those links?

I'm using the latest version of `youtube-dl`, the 2020.01.24 version, and for a large portion of the videos already downloaded I also used the previous version to that one.

**Comment by remitamine** [comment]
those are [video cards](https://support.google.com/youtube/answer/6140493) and not part of the annotations file.

**Comment by libransser** [comment]
I see. Is there any way to download video cards then?

**Comment by remitamine** [comment]
no, Youtube does not offer a URL to download cards, but you can extract the information about the cards from `player_response` on the video page(you have to write your own script).
