### ISSUE TITLE
bitchute Format fetch is broken

### ISSUE THREAD

**Issue by SairesArt** [ytdl-org/youtube-dl#23979]
## checks
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones
## LOG File:
[log.txt](https://github.com/ytdl-org/youtube-dl/files/4165741/log.txt)
## Description
Downloading a video from bitchute using "youtube-dl [bitchute url]", works fine. Subsequently watching bitchute via mpv works also just fine using "mpv [bitchute url]"
However, passing -F to youtube-dl makes youtube-dl quit with "unkown" as a resolution note.
Subsequently using mpv to watch bitchute, whilst having defaults set for quality (eg. in my case having set 1080p as max resolution) fails, because youtube-dl does not provide anything.
Even the bestvideo qualifier comes out empty, since I presume that checks formats as well.

**Comment by remitamine** [comment]
read https://github.com/ytdl-org/youtube-dl#format-selection.
