### ISSUE TITLE
lower resolution lower quality video chosen by default

### ISSUE THREAD

**Issue by github-account1111** [ytdl-org/youtube-dl#23989]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PS C:\Users\<username>\Downloads> youtube-dl https://www.reddit.com/r/AbruptChaos/comments/ezu8m5/the_party_didnt_look_so_boring/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.reddit.com/r/AbruptChaos/comments/ezu8m5/the_party_didnt_look_so_boring/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2020-01-31-62d92a8, ffprobe git-2020-01-31-62d92a8
[debug] Proxy map: {}
[RedditR] ezu8m5: Downloading JSON metadata
[Reddit] x49kcxq2sbf41: Downloading m3u8 information
[Reddit] x49kcxq2sbf41: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://v.redd.it/x49kcxq2sbf41/HLS_360_v4.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 11
[download] Destination: The party didn‘t look so boring 😮😮-x49kcxq2sbf41.fhls-1220.mp4
[download] 100% of 7.37MiB in 00:14
[debug] Invoking downloader on 'https://v.redd.it/x49kcxq2sbf41/audio'
[download] Destination: The party didn‘t look so boring 😮😮-x49kcxq2sbf41.fdash-AUDIO-1.m4a
[download] 100% of 1005.47KiB in 00:01
[ffmpeg] Merging formats into "The party didn‘t look so boring 😮😮-x49kcxq2sbf41.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:The party didn‘t look so boring 😮😮-x49kcxq2sbf41.fhls-1220.mp4" -i "file:The party didn‘t look so boring 😮  -x49kcxq2sbf41.fdash-AUDIO-1.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:The party didn‘t look so boring 😮😮-x49kcxq2sbf41.temp.mp4"
Deleting original file The party didn‘t look so boring 😮😮-x49kcxq2sbf41.fhls-1220.mp4 (pass -k to keep)
Deleting original file The party didn‘t look so boring 😮😮-x49kcxq2sbf41.fdash-AUDIO-1.m4a (pass -k to keep)
```

## Description

Running the above command downloads a lower res, obviously lower quality video with artifacts. It chooses `hls-1220` as opposed to `dash-VIDEO-1`. That should not happen, unless I'm missing something. Is there a way to prevent this? You say in [one of your posts](#23986 ) 

>Formats are sorted by quality.

That's not the case, as apparent from this link. I understand that it is hard to estimate the quality of the video programmatically. But I'd say the resolution can be just as telling of video quality as the bitrate, so why not give a weight to both instead of limiting it to bitrate alone?

I know this is anecdotal, but it might also be helpful to have the option to give priority to DASH videos over everything else, as those tend to have the highest quality, according to my limited experience.

**Comment by dstftw** [comment]
`hls-1220` has higher reported bitrate thus has better quality. bitrate is preferred over height.
