### ISSUE TITLE
best, bestvideo+bestaudio format selectors ambiguity

### ISSUE THREAD

**Issue by mtae** [ytdl-org/youtube-dl#23986]
The format option 'best' supposedly gets the best video and audio available in a single file. Whereas bestvideo/bestaudio get the best video or audio quality available as video only or audio only.

It's unclear what they do in the following cases:
1. When the best video quality is available only in the combined file but the best audio quality is available only as an audio only file. 
2. Similarly when the best audio quality is available only in the combined file but the best video quality is available only as a video only file.

Is it that the above situations don't arise in youtube?

**Comment by dstftw** [comment]
They do nothing about these cases.

**Comment by mtae** [comment]
I see. Is there a command to get the best possible merged or unmerged format including in those cases?

**Comment by dstftw** [comment]
No.

**Comment by mtae** [comment]
Thanks for letting me know. 

If you don't mind, can I ask how you sort the formats according to quality? (when it's the same video resolution for instance) 
Or could you point me to where it is in the code, I searched for it but I couldn't find the right spot.

**Comment by dstftw** [comment]
Formats are sorted by quality.
