### ISSUE TITLE
Recover Video

### ISSUE THREAD

**Issue by k0a1adev** [ytdl-org/youtube-dl#23996]
Hello,
i have recorded serveral hours of a youtube livestream. I pressed CTRL+C once to stop the recording process, but after waiting some time, I wasnt really sure if the program had recognized the keypress, so I pressed it again, resulting in a force quit of the program. I am now left with a 5GB mp4 which I cant play. Is there any way to fix this video file? Im quite sure all the video information is there only the metadata or something is missing. Thanks in Advance.

**Comment by dstftw** [comment]
Most likely trailing moov atom was not written. I don't think there is a simple fix but you can try [this](https://sound.stackexchange.com/questions/27182/how-to-recover-audio-from-an-incomplete-or-corrupted-aac-m4a-file/37677#37677).
