### ISSUE TITLE
AtomicParsley location

### ISSUE THREAD

**Issue by endquote** [ytdl-org/youtube-dl#23998]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I'm embedding youtube-dl into an application and would like to do thumbnail embedding. I could also embed AtomicParsely, but I can't modify the system path so that ytdl can find it.

For ffmpeg, we have `--ffmpeg-location`. It would be nice to have a similar option for AtomicParsley.

**Comment by dstftw** [comment]
You don't need to modify system `PATH`. Modifying it for a single youtube-dl run is enough.
