### ISSUE TITLE
reopen issue #23989

### ISSUE THREAD

**Issue by github-account1111** [ytdl-org/youtube-dl#23993]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PS C:\Users\<username>\Downloads> youtube-dl https://www.reddit.com/r/AbruptChaos/comments/ezu8m5/the_party_didnt_look_so_boring/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.reddit.com/r/AbruptChaos/comments/ezu8m5/the_party_didnt_look_so_boring/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2020-01-31-62d92a8, ffprobe git-2020-01-31-62d92a8
[debug] Proxy map: {}
[RedditR] ezu8m5: Downloading JSON metadata
[Reddit] x49kcxq2sbf41: Downloading m3u8 information
[Reddit] x49kcxq2sbf41: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://v.redd.it/x49kcxq2sbf41/HLS_360_v4.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 11
[download] Destination: The party didn‘t look so boring 😮😮-x49kcxq2sbf41.fhls-1220.mp4
[download] 100% of 7.37MiB in 00:14
[debug] Invoking downloader on 'https://v.redd.it/x49kcxq2sbf41/audio'
[download] Destination: The party didn‘t look so boring 😮😮-x49kcxq2sbf41.fdash-AUDIO-1.m4a
[download] 100% of 1005.47KiB in 00:01
[ffmpeg] Merging formats into "The party didn‘t look so boring 😮😮-x49kcxq2sbf41.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:The party didn‘t look so boring 😮😮-x49kcxq2sbf41.fhls-1220.mp4" -i "file:The party didn‘t look so boring 😮  -x49kcxq2sbf41.fdash-AUDIO-1.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:The party didn‘t look so boring 😮😮-x49kcxq2sbf41.temp.mp4"
Deleting original file The party didn‘t look so boring 😮😮-x49kcxq2sbf41.fhls-1220.mp4 (pass -k to keep)
Deleting original file The party didn‘t look so boring 😮😮-x49kcxq2sbf41.fdash-AUDIO-1.m4a (pass -k to keep)
```

## Description

WRITE DESCRIPTION HERE

You need to read the reports more carefully. I wasn't asking which format reported a higher bitrate. You yourself said higher **quality** not higher bitrate. Totally different things.

Second of all, priority != weight. Bitrate should get a higher rate (e.g. 0.7) than the resolution (e.g. 0.3). As is, it's given **all** the rate (i.e. 1.0). That results in subpar videos (lower quality) being downloaded when the user expects the highest one.

And don't lock threads immediately. That forces people to make these double posts and reopen requests and just adds clutter.

#23989

**Comment by dstftw** [comment]
There are already open issues. Stop posting duplicates.
