### ISSUE TITLE
Why does debugging info often repeat the 100% downloaded info ?

### ISSUE THREAD

**Issue by section83** [ytdl-org/youtube-dl#23999]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

The verbose option for printing debugging information often, but not always, repeats the download complete line.  For an 18MB download, for example, at the completion of a download (before post-processing), it often prints:

> [download] 100% of 17.90MiB in 00:10
> 
> [download] 100% of 17.90MiB in 00:10
> 

I use the 100% indicator to check that a download completed successfully.  This is fine normally but, when downloading multiple files in one process (e.g. a batch), the number of "100%" messages does not necessarily respond to the number of successful downloads.

So, my question is why is the "100%" message often repeated ?  And, why not for all downloads but only for some ?

Thanks.

**Comment by dstftw** [comment]
Post verbose log.

**Comment by section83** [comment]
Apologies, I was going to give a verbose log example but, anyway, forgot.  Here is an example:

> [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-errors', u'--prefer-ffmpeg', u'--no-overwrites', u'--verbose', u'-o', u'%(title)s.%(ext)s', u'https://iview.abc.net.au/show/alan-duffy-s-astronomy-glossary/video/IV1745H001S00']
[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2-tessus, ffprobe 4.2.2-tessus
[debug] Proxy map: {}
[debug] Using fake IP 1.153.160.235 (AU) as X-Forwarded-For.
[abc.net.au:iview] IV1745H001S00: Downloading JSON metadata
[abc.net.au:iview] IV1745H001S00: Downloading webpage
[abc.net.au:iview] IV1745H001S00: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/index_0_av.m3u8?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d'
[hlsnative] Downloading m3u8 manifest
WARNING: hlsnative has detected features it does not support, extraction will be delegated to ffmpeg
[download] Destination: Alan Duffy's Astronomy Glossary.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
X-Forwarded-For: 1.153.160.235
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.55 Safari/537.36
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: hdntl=exp=1581295249~acl=%2f*~data=hdntl~hmac=c13037fcb4bfb57119c24fd9a9bef600c56d86abd83abce1ffae8955d1f15305
' -i 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/index_0_av.m3u8?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:Alan Duffy'"'"'s Astronomy Glossary.mp4.part'
ffmpeg version 4.2.2-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.16)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[tcp @ 0x7fb992c00880] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992c00880] Successfully connected to 23.206.242.8 port 80
[hls @ 0x7fb993004400] Skip ('#EXT-X-ALLOW-CACHE:YES')
[hls @ 0x7fb993004400] Skip ('#EXT-X-VERSION:2')
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment1_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/crypt.key?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992c05f80] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992c05f80] Successfully connected to 23.206.242.8 port 80
[AVIOContext @ 0x7fb992c06080] Statistics: 16 bytes read, 0 seeks
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment1_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992c06080] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992c06080] Successfully connected to 23.206.242.8 port 80
[h264 @ 0x7fb993016800] Reinit context to 1024x576, pix_fmt: yuv420p
Input #0, hls, from 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/index_0_av.m3u8?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d':
  Duration: 00:02:41.00, start: 0.100511, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(left), 1024x576 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Alan Duffy's Astronomy Glossary.mp4.part':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (High), 1 reference frame (avc1 / 0x31637661), yuv420p(left), 1024x576 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[AVIOContext @ 0x7fb992c06640] Statistics: 1307540 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment2_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment2_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992d12d00] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992d12d00] Successfully connected to 23.206.242.8 port 80
frame=  393 fps=0.0 q=-1.0 size=    1792kB time=00:00:15.74 bitrate= 932.5kbits/s speed=31.2x    
[AVIOContext @ 0x7fb992d13680] Statistics: 1121044 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment3_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment3_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992c06e80] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992c06e80] Successfully connected to 23.206.242.8 port 80
frame=  500 fps=477 q=-1.0 size=    2048kB time=00:00:19.99 bitrate= 839.2kbits/s speed=19.1x    
frame=  601 fps=378 q=-1.0 size=    2560kB time=00:00:24.05 bitrate= 871.8kbits/s speed=15.1x    
frame=  653 fps=307 q=-1.0 size=    2816kB time=00:00:26.16 bitrate= 881.5kbits/s speed=12.3x    
frame=  713 fps=269 q=-1.0 size=    3072kB time=00:00:28.51 bitrate= 882.6kbits/s speed=10.8x    
[AVIOContext @ 0x7fb992c07840] Statistics: 1316940 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment4_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment4_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992d1b140] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992d1b140] Successfully connected to 23.206.242.8 port 80
[AVIOContext @ 0x7fb992e005c0] Statistics: 1397780 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment5_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment5_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992f0ab80] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992f0ab80] Successfully connected to 23.206.242.8 port 80
frame= 1000 fps=311 q=-1.0 size=    4608kB time=00:00:39.98 bitrate= 944.1kbits/s speed=12.4x    
[AVIOContext @ 0x7fb992c06480] Statistics: 1355668 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment6_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment6_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992d13140] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992d13140] Successfully connected to 23.206.242.8 port 80
frame= 1470 fps=395 q=-1.0 size=    6912kB time=00:00:58.79 bitrate= 963.1kbits/s speed=15.8x    
[AVIOContext @ 0x7fb992e00600] Statistics: 1295508 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment7_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment7_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992f02380] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992f02380] Successfully connected to 23.206.242.8 port 80
[AVIOContext @ 0x7fb992c06480] Statistics: 1346644 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment8_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment8_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992d12b80] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992d12b80] Successfully connected to 23.206.242.8 port 80
frame= 1820 fps=431 q=-1.0 size=    8704kB time=00:01:12.81 bitrate= 979.2kbits/s speed=17.3x    
[AVIOContext @ 0x7fb992c06480] Statistics: 1346644 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment9_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment9_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992d13180] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992d13180] Successfully connected to 23.206.242.8 port 80
[AVIOContext @ 0x7fb992d13380] Statistics: 1121044 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment10_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment10_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992d1b780] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992d1b780] Successfully connected to 23.206.242.8 port 80
frame= 2295 fps=486 q=-1.0 size=   10752kB time=00:01:31.83 bitrate= 959.1kbits/s speed=19.4x    
[AVIOContext @ 0x7fb992c06480] Statistics: 1241364 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment11_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment11_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992d1b780] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992d1b780] Successfully connected to 23.206.242.8 port 80
[AVIOContext @ 0x7fb992c06480] Statistics: 1289492 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment12_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment12_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992c064c0] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992c064c0] Successfully connected to 23.206.242.8 port 80
frame= 2750 fps=524 q=-1.0 size=   12800kB time=00:01:49.99 bitrate= 953.3kbits/s speed=20.9x    
[AVIOContext @ 0x7fb992d1ae00] Statistics: 1292500 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment13_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment13_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992d1b8c0] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992d1b8c0] Successfully connected to 23.206.242.8 port 80
frame= 3230 fps=561 q=-1.0 size=   15104kB time=00:02:09.21 bitrate= 957.5kbits/s speed=22.5x    
[AVIOContext @ 0x7fb992c06480] Statistics: 1382740 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment14_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment14_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992d1b8c0] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992d1b8c0] Successfully connected to 23.206.242.8 port 80
frame= 3365 fps=536 q=-1.0 size=   15872kB time=00:02:14.60 bitrate= 966.0kbits/s speed=21.4x    
frame= 3457 fps=508 q=-1.0 size=   16384kB time=00:02:18.32 bitrate= 970.3kbits/s speed=20.3x    
[AVIOContext @ 0x7fb992c06480] Statistics: 1557204 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment15_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment15_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992d12c00] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992d12c00] Successfully connected to 23.206.242.8 port 80
frame= 3601 fps=493 q=-1.0 size=   17152kB time=00:02:24.05 bitrate= 975.4kbits/s speed=19.7x    
[AVIOContext @ 0x7fb992d13740] Statistics: 1163532 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment16_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment16_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992d1b900] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992d1b900] Successfully connected to 23.206.242.8 port 80
[AVIOContext @ 0x7fb992c06480] Statistics: 384084 bytes read, 0 seeks
[hls @ 0x7fb993004400] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment17_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d', offset 0, playlist 0
[hls @ 0x7fb993004400] Opening 'crypto+http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment17_0_av.ts?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d' for reading
[tcp @ 0x7fb992c02840] Starting connection attempt to 23.206.242.8 port 80
[tcp @ 0x7fb992c02840] Successfully connected to 23.206.242.8 port 80
[AVIOContext @ 0x7fb992e005c0] Statistics: 9588 bytes read, 0 seeks
No more output streams to write to, finishing.
frame= 4003 fps=510 q=-1.0 Lsize=   18333kB time=00:02:40.17 bitrate= 937.7kbits/s speed=20.4x    
video:15676kB audio:2503kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.847542%
Input file #0 (http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/iv1/IV1745H001S00MA1D1_20171216122015_,1500000,1000000,650000,500000,220000,.mp4.csmil/index_0_av.m3u8?null=0&id=AgC0lkPhF87yBBFVP15QZGh1dzqI2+sSDX6uggA87Uw%2fTn8hw45EOXGjzBfDVCzeaf5KGxOGyMM5oQ%3d%3d):
  Input stream #0:0 (video): 4003 packets read (16052493 bytes); 
  Input stream #0:1 (audio): 6899 packets read (2611405 bytes); 
  Input stream #0:2 (data): 0 packets read (0 bytes); 
  Total: 10902 packets (18663898 bytes) demuxed
Output file #0 (file:Alan Duffy's Astronomy Glossary.mp4.part):
  Output stream #0:0 (video): 4003 packets muxed (16052493 bytes); 
  Output stream #0:1 (audio): 6899 packets muxed (2563112 bytes); 
  Total: 10902 packets (18615605 bytes) muxed
[AVIOContext @ 0x7fb992f035c0] Statistics: 2 seeks, 75 writeouts
[AVIOContext @ 0x7fb992c024c0] Statistics: 5028 bytes read, 0 seeks

>[ffmpeg] Downloaded 18773380 bytes

>[download] 100% of 17.90MiB in 00:13

>[download] 100% of 17.90MiB in 00:13
[debug] ffmpeg command line: ffprobe -show_streams 'file:Alan Duffy'"'"'s Astronomy Glossary.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Alan Duffy's Astronomy Glossary.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Alan Duffy'"'"'s Astronomy Glossary.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:Alan Duffy'"'"'s Astronomy Glossary.temp.mp4'
