### ISSUE TITLE
blocking people and marking duplicate without explanation

### ISSUE THREAD

**Issue by softlines** [ytdl-org/youtube-dl#23995]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.01.24**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

Seriously? Blocking people? For asking questions? How is this okay? Did I break the site guidelines? Harass you in any way? I wouldn't be posting here if the program didn't have issues, wouldn't you think?

Where are said "already open issues?" Maybe if you pointed to actual posts then there wouldn't be so much confusion and so many duplicates in the first place. All I'm finding are posts where you respond with a cryptic one-liner and mark as duplicate. Or you don't respond at all.

And maybe if you didn't lock convos as soon as you closed them you wouldn't have so many duplicates either.

#23993

**Comment by dstftw** [comment]
Don't spam with duplicates and you won't get blocked. And learn to use search. I'm not going to do that for every complainer over and over again.
