### ISSUE TITLE
How to download videos that are loading in chunks? 

### ISSUE THREAD

**Issue by jzamit** [ytdl-org/youtube-dl#24001]
## Checklist

- [X ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
There is some way to download complete video that is loading in chunks? Right now I got only first part of the video, 1 minute instead of the complete 10 minute video.

I see this in network tab when reproducing 1 video (is like lazy loading)
Part28:
https://cfvod.kaltura.com/scf/hls/p/1926081/sp/192608100/serveFlavor/entryId/0_9o2iuw1o/v/2/ev/8/flavorId/0_slm8famf/name/a.mp4/seg-28-v1-a1.ts

Part29:
https://cfvod.kaltura.com/scf/hls/p/1926081/sp/192608100/serveFlavor/entryId/0_9o2iuw1o/v/2/ev/8/flavorId/0_slm8famf/name/a.mp4/seg-29-v1-a1.ts

So I only get the first part of the video (1minute ) not full video the 35 parts merged as 1 complete video file.

Any help, comment is appreciated, thanks guys!!

**Comment by remitamine** [comment]
use the original [O’Reilly URL](https://www.oreilly.com/library/view/modern-javascript-from/9781789539509/video2_5.html).

**Comment by jzamit** [comment]
@remitamine Why is closed? Did you tested this? 

Is the exact thing I founded, using the original URL is the behavior I described:

With playlist  [here](https://learning.oreilly.com/videos/modern-javascript-from/9781789539509/) and also with the specific video [specific](https://learning.oreilly.com/videos/modern-javascript-from/9781789539509/9781789539509-video2_5)

<img width="790" alt="Screen Shot 2020-02-09 at 12 56 55" src="https://user-images.githubusercontent.com/54561287/74105363-dfe98c00-4b3b-11ea-84b5-58cd833564e1.png">

Thanks for your response.

**Comment by remitamine** [comment]
open a new issue with full details(verbose log, no screenshots).
