### ISSUE TITLE
Hotstar extractor give error

### ISSUE THREAD

**Issue by krishna-arch** [ytdl-org/youtube-dl#24005]
$ youtube-dl -F https://www.hotstar.com/in/movies/junglee/1000235906/watch?utm_source=gwa
[hotstar] 1000235906: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(ConnectionResetError(104, 'Connection reset by peer')))

**Comment by dstftw** [comment]
Network issue on your side.
