### ISSUE TITLE
Youtube playlist downlaod error

### ISSUE THREAD

**Issue by jukkatl** [ytdl-org/youtube-dl#24004]
## Checklist

- [x ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2020.01.24**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=kkcffy0iuuY&list=RDEMSc9XXM2chYt2HUT3kxVFUw&index=27']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.7.6 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist RDEMSc9XXM2chYt2HUT3kxVFUw - add --no-playlist to just download video kkcffy0iuuY
[youtube:playlist] RDEMSc9XXM2chYt2HUT3kxVFUw: Downloading page 1 of Youtube mix
[youtube:playlist] RDEMSc9XXM2chYt2HUT3kxVFUw: Downloading page 2 of Youtube mix
[youtube:playlist] RDEMSc9XXM2chYt2HUT3kxVFUw: Downloading page 3 of Youtube mix
[youtube:playlist] RDEMSc9XXM2chYt2HUT3kxVFUw: Downloading page 4 of Youtube mix
[download] Downloading playlist: Mix - Retkibanaani
[youtube:playlist] playlist Mix - Retkibanaani: Collected 50 video ids (downloading 50 of them)
[download] Downloading video 1 of 50
[youtube] 2HUT3kxVFUw: Downloading webpage
[youtube] 2HUT3kxVFUw: Downloading video info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: This video is unavailable.
Sorry about that.
Traceback (most recent call last):
  File "d:\tools\python373\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "d:\tools\python373\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "d:\tools\python373\lib\site-packages\youtube_dl\extractor\youtube.py", line 2153, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.
Sorry about that.
```

## Description

Tried to download this list from youtube, also some separated song from it, but got this errror everytime when trying. From browser everything works OK. 
Baseurl on this case is https://www.youtube.com/watch?v=ivYmwVLX8oo&list=RDEMSc9XXM2chYt2HUT3kxVFUw&index=27&ab_channel=sentenced97

**Comment by s104346** [comment]
> From browser everything works OK.

https://www.youtube.com/watch?v=2HUT3kxVFUw is indeed unavailable.
You can use `--ignore-errors` to skip those playlist entries:
```
    -i, --ignore-errors              Continue on download errors, for example to
                                     skip unavailable videos in a playlist

```

**Comment by Git-Talking** [comment]
I have the same or similar phenomena. The error is identical whether passing a single video or playlist in the URL argument. Debian buster,up to date apt install of youtube-dl.

`'youtube-dl -i --verbose "https://www.youtube.com/watch?v=gprBUIYdZvM&list=PLINm4moYjFr46vCCwuriJgET0Go_w4BcP"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-i', '--verbose', 'https://www.youtube.com/watch?v=gprBUIYdZvM&list=PLINm4moYjFr46vCCwuriJgET0Go_w4BcP']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.17
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLINm4moYjFr46vCCwuriJgET0Go_w4BcP - add --no-playlist to just download video gprBUIYdZvM
[youtube:playlist] PLINm4moYjFr46vCCwuriJgET0Go_w4BcP: Downloading webpage
[download] Downloading playlist: Horse source
[youtube:playlist] PLINm4moYjFr46vCCwuriJgET0Go_w4BcP: Downloading page #1
[youtube:playlist] playlist Horse source: Downloading 186 videos
[download] Downloading video 1 of 186
[youtube] gprBUIYdZvM: Downloading webpage
[youtube] gprBUIYdZvM: Downloading video info webpage
ERROR: gprBUIYdZvM: YouTube said: This video is unavailable.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1688, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: gprBUIYdZvM: YouTube said: This video is unavailable.`

I could post the other 185 errors.

**Comment by killmaster** [comment]
Having the same problem on a new installation.
