### ISSUE TITLE
windows installation issue

### ISSUE THREAD

**Issue by jeffthewhiz** [ytdl-org/youtube-dl#24024]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

hello

just want to ask, what are the requirements before i install youtube-dl? 

i tried installing the youtube-dl, using the windows exe file from the main site.

when i install the youtube-dl exe file, it pops up the command line and gives me an installation error message that i needed to install first the windows redistribute file. 

what are the required version of windows redistributable file to be installed?

i didnt install the installation exe again to get the error message, i'm bit sketchy when the installation tried to open the command line. 

is it normal that youtube-dl exe file opens the command line? 

thank you

**Comment by dstftw** [comment]
http://ytdl-org.github.io/youtube-dl/download.html

**Comment by jeffthewhiz** [comment]
just want to clarify that installation wasnt successful due to missing microsoft package? 
"Microsoft Visual C++ 2010 Redistributable Package (x86) "

it got an error while trying to open the command line?

**Comment by dstftw** [comment]
There are no telepathists to guess what error you even talking about.

**Comment by jeffthewhiz** [comment]
is it normal that youtube-dl exe file opens the command line?

**Comment by Hrxn** [comment]
It's a command line program, what do you expect?
