### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '--Frag1'

### ISSUE THREAD

**Issue by nadermx** [ytdl-org/youtube-dl#24029]
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--proxy', '', '-c', '-f', '140/bestaudio[ext=m4a]/bestaudio/best', '--no-cache-dir', '--restrict-filenames', '--hls-prefer-native', '-o', '-', 'https://www.youtube.com/watch?v=erqskegZLQw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.7.5 (CPython) - Linux-4.15.0-76-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.2.2-0york0, ffprobe 4.2.2-0york0
[debug] Proxy map: {}
[youtube] erqskegZLQw: Downloading webpage
[youtube] erqskegZLQw: Downloading video info webpage
[youtube] erqskegZLQw: Downloading MPD manifest
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1581509102/ei/jpVDXuCvE4amhgaQpKuACQ/ip/38.106.72.50/id/7abaac91e8192d0c/source/youtube/requiressl/yes/playback_host/r6---sn-p5qs7n76.googlevideo.com/mm/31%2C26/mn/sn-p5qs7n76%2Csn-vgqsrnez/ms/au%2Conr/mv/m/mvi/5/pl/22/tx/23813230/txs/23813225%2C23813226%2C23813227%2C23813228%2C23813229%2C23813230%2C23813231/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1170000/vprv/1/mt/1581487354/fvip/1/keepalive/yes/fexp/23842630/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/ALgxI2wwRQIgS75FV2wPondy5GM3Y0IDBZJsEX8QeN4VQHcfeE8vj9ECIQDq5zKhqsLe4GEUTCKUPMvPU4a-JkOj26mrUWYNvhiTRA%3D%3D/lsparams/playback_host%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AHylml4wRQIhAKyYKo7YlpuvRxB9Qsh5GYC1gLg-bMr71iR43ubn8oltAiA7JcwOeCNiGLX1Nf3HhZU3aVcZj8GCbZIaRhi-WaPnig%3D%3D'
[dashsegments] Total fragments: 19
[download] Destination: -
^M[download]   5.3% of ~12.17KiB at Unknown speed ETA 00:00^M[download]   5.3% of ~12.17KiB at Unknown speed ETA 00:00^M[download]   0.1% of ~1.47MiB at 550.94KiB/s ETA 00:59^M[download]   0.2% of ~1.47MiB at  1.36MiB/s ETA 00:27^M[download]   0.5% of ~1.47MiB at  2.83MiB/s ETA 00:12^M[download]   1.0% of ~1.47MiB at  5.36MiB/s ETA 00:06^M[download]   2.1% of ~1.47MiB at  3.45MiB/s ETA 00:03^M[download]   4.2% of ~1.47MiB at  4.18MiB/s ETA 00:01^M[download]   8.5% of ~1.47MiB at  5.62MiB/s ETA 00:00^M[download]  10.5% of ~1.47MiB at  6.35MiB/s ETA 00:00^M[download]  10.5% of ~1.47MiB at  6.35MiB/s ETA 00:00ERROR: unable to download video data: [Errno 2] No such file or directory: '--Frag1'
Traceback (most recent call last):
  File "/home/www/env/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1925, in process_info
    success = dl(filename, info_dict)
  File "/home/www/env/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1864, in dl
    return fd.download(name, info)
  File "/home/www/env/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/www/env/lib/python3.7/site-packages/youtube_dl/downloader/dash.py", line 51, in real_download
    self._append_fragment(ctx, frag_content)
  File "/home/www/env/lib/python3.7/site-packages/youtube_dl/downloader/fragment.py", line 120, in _append_fragment
    os.remove(encodeFilename(ctx['fragment_filename_sanitized']))
FileNotFoundError: [Errno 2] No such file or directory: '--Frag1'

## Description
I'm currently getting this error on this video https://www.youtube.com/watch?v=erqskegZLQw when outputting to stdout

**Comment by dstftw** [comment]
Something on your machine had removed youtube-dl download fragment.

**Comment by nadermx** [comment]
@dstftw I keep getting this error when running it as a subprocess and piping it.  I can't imagine the subprocess sandbox would be deleting the files randomly.  Maybe something with running concurrent youtube-dl processes is causing a conflict with ubuntu?

**Comment by nadermx** [comment]
@dstftw perhaps https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/downloader/fragment.py#L99 isn't unique when running concurrent?

**Comment by nadermx** [comment]
@dstftw I was able to fix it by putting each youtube-dl into it's own temporary directory.
