### ISSUE TITLE
Wrong dl file?

### ISSUE THREAD

**Issue by Sven1222225** [ytdl-org/youtube-dl#24036]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

I have downloaded the windows version (youtube-dl.exe) 2020.01.24 BUT when i test with "-v" i get "[debug] youtube-dl version 2020.01.15". is the download file wrong or do i do somthing wrong. Because this version has the "ERROR: Signature extraction failed: Traceback (most recent call last):" bug in it.

**Comment by dstftw** [comment]
You do something wrong.
