### ISSUE TITLE
Youtube-dl error when downloading from youtube 

### ISSUE THREAD

**Issue by nevadarain** [ytdl-org/youtube-dl#24034]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, I was hoping you can help me with some errors i am getting using youtube-dl.  I am using the templates and folder structure here ([https://github.com/1832923/ytdl-example](https://github.com/1832923/ytdl-example)).

&#x200B;

The contents of the youtube-dl.bat, Channel\_List\_NoPlaylist.txt, and Channel\_Args-NoPlaylist.conf can be found here ([https://pastebin.com/jaP2GFzD](https://pastebin.com/jaP2GFzD)).

&#x200B;

When i run the .bat file, the first video in the txt file(Marques Brownlee) downloads with no problem. But the 2nd video (Rollie Williams) does not download and gives me an error:

&#x200B;

ERROR: Cannot write metadata to JSON file Rollie Williams\\Billiards expert Dr. Dave gives Rollie a pool master class \_ From Average To Good\\20191031 - Billiards expert Dr. Dave gives Rollie a pool master class \_ From Average To Good - (3060s) \[1920x1080\] \[WHJGKPbLIwA\].info.json

&#x200B;

\[Errno 2\] No such file or directory: 'Rollie Williams\\\\Billiards expert Dr. Dave gives Rollie a pool master class \_ From Average To Good\\\\20191031 - Billiards expert Dr. Dave gives Rollie a pool master class \_ From Average To Good - (3060s) \[1920x1080\] \[WHJGKPbLIwA\].info.json.60yek71a.tmp'

&#x200B;

But when I download the Rollie Williams video using "youtube-dl --ignore-config [https://www.youtube.com/watch?v=WHJGKPbLIwA&t=](https://www.youtube.com/watch?v=WHJGKPbLIwA&t=)", it downloads with no issues.

&#x200B;

Any help in solving this problem will be greatly appreciated.

**Comment by dstftw** [comment]
Most likely too long path.
