### ISSUE TITLE
support multi thread ?

### ISSUE THREAD

**Issue by viponedream** [ytdl-org/youtube-dl#24032]
how can i use multithread to download?

like:
`youtube-dl --proxy http://127.0.0.1:8087/  https://www.youtube.com/playlist?list=PLcCtOGRM5fI1ASL6DP0WhJ37Mg8yYkkwt`

**Comment by dstftw** [comment]
--external-downloader.

**Comment by Lee-Carre** [comment]
See [Parallel youtube-dl](/ytdl-org/youtube-dl/projects/1).
