### ISSUE TITLE
Error downloading specific youtube videos. 

### ISSUE THREAD

**Issue by petran79** [ytdl-org/youtube-dl#24059]
## Checklist

- [ ] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.02.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

While youtube-dl downloads all the files from this list, from episode 41 it stops . Havent encountered it in any other video and even other downloaders have issues. Yet it plays normally within youtube player.

https://www.youtube.com/watch?v=3WiMvCL-alY&list=PL_ybo2WKvx5lxYJkms6OkDJFN0Aii9kBZ

youtube-dl https://www.youtube.com/watch?v=0cvPGVs8mIk&list=PL_ybo2WKvx5lxYJkms6OkDJFN0Aii9kBZ&index=41

[youtube] 0cvPGVs8mIk: Downloading webpage
[youtube] 0cvPGVs8mIk: Downloading video info webpage
[youtube] 0cvPGVs8mIk: Downloading MPD manifest
[download] Destination: 新メイプルタウン物語 パームタウン編1987 第41話 「けんかした二人」-0cvPGVs8mIk.mp4
[download]   0.2% of 118.44MiB at  2.25MiB/s ETA 00:52 [download] Got server HTTP error: Downloaded 298719 bytes, expected 124198104 bytes. Retrying (attempt 1 of 10)...

ERROR: Did not get any data blocks
'list' is not recognized as an internal or external command,
operable program or batch file.
'index' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dstftw** [comment]
Server side youtube error for selected format.
