### ISSUE TITLE
Automatically name and download videos from youtube-dl

### ISSUE THREAD

**Issue by JoeIsCool** [ytdl-org/youtube-dl#24058]
## Checklist

- [ x] I'm reporting a site feature request
- [ x] I've verified that I'm running youtube-dl version **2020.02.16**
- [ x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
One needs to usually needs to provide  an explicit name with the -o flag if one wants to download a video from Twitter. And that means you can't download a list of videos in a file with the -a flag.
So the feature I would like would be for youtube-dl to automatically pick a video name which short enough. It is most likely that no one wants the file name to be the entire text of the tweet anyway. A good name would uploaders twitter handle (the one that appears in the tweet's URL and the tweet id number which appears in the URL.

**Comment by dstftw** [comment]
Bother to read FAQ on `-o` option.

**Comment by JoeIsCool** [comment]
The feature request is for it to work without needing to use the -o flag.
