### ISSUE TITLE
--write-auto-sub contains time marks in subtitles

### ISSUE THREAD

**Issue by weisenhan** [ytdl-org/youtube-dl#24056]
~/watch$ youtube-dl --skip-download --write-auto-sub --verbose https://www.youtube.com/watch?v=hGxxahRvSw0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--skip-download', u'--write-auto-sub', u'--verbose', u'https://www.youtube.com/watch?v=hGxxahRvSw0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-76-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] hGxxahRvSw0: Downloading webpage
[youtube] hGxxahRvSw0: Downloading video info webpage
[youtube] hGxxahRvSw0: Looking for automatic captions
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Rage Against the Bank Machine - A Dose of Buckley-hGxxahRvSw0.en.vtt

## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
~/watch$ youtube-dl --skip-download --write-auto-sub --verbose https://www.youtube.com/watch?v=hGxxahRvSw0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--skip-download', u'--write-auto-sub', u'--verbose', u'https://www.youtube.com/watch?v=hGxxahRvSw0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-76-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] hGxxahRvSw0: Downloading webpage
[youtube] hGxxahRvSw0: Downloading video info webpage
[youtube] hGxxahRvSw0: Looking for automatic captions
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Rage Against the Bank Machine - A Dose of Buckley-hGxxahRvSw0.en.vtt
```

## Description

The subtitles display time codes as seen:

subtitle file:
WEBVTT
Kind: captions
Language: en

00:00:00.030 --> 00:00:02.750 align:start position:0%
 
not<00:00:00.870><c> enough</c><00:00:01.140><c> Buckley</c><00:00:01.589><c> in</c><00:00:01.680><c> your</c><00:00:01.800><c> life</c><00:00:01.979><c> get</c>

00:00:02.750 --> 00:00:02.760 align:start position:0%
not enough Buckley in your life get
 

00:00:02.760 --> 00:00:04.670 align:start position:0%
not enough Buckley in your life get
access<00:00:03.179><c> to</c><00:00:03.210><c> exclusive</c><00:00:03.540><c> content</c><00:00:04.049><c> you</c><00:00:04.470><c> won't</c>

00:00:04.670 --> 00:00:04.680 align:start position:0%
access to exclusive content you won't
 

00:00:04.680 --> 00:00:06.829 align:start position:0%
access to exclusive content you won't
see<00:00:04.920><c> on</c><00:00:04.950><c> YouTube</c><00:00:05.490><c> when</c><00:00:05.970><c> you</c><00:00:06.089><c> support</c><00:00:06.420><c> me</c><00:00:06.600><c> at</c>

00:00:06.829 --> 00:00:06.839 align:start position:0%
see on YouTube when you support me at

**Comment by orena1** [comment]
The automatic subtitles suppose to have time-marks, the manual subtitles usually do not have
