### ISSUE TITLE
Add Date uploaded and File duration to json --flat-playlist data

### ISSUE THREAD

**Issue by optio50** [ytdl-org/youtube-dl#24067]
## Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2020.02.16**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

Would like to have Date uploaded and File duration in json --flat-playlist data
It currently looks like this
{"url": "Oxz-n17BKVE", "_type": "url", "ie_key": "Youtube", "id": "Oxz-n17BKVE", "title": "Best Galaxy Z Flip features to try right away"}

I see there is an open and accepted request to support all get options but the upload or file date is not one of those. 
https://github.com/ytdl-org/youtube-dl/issues/22493

**Comment by dstftw** [comment]
No such metadata is available. Nothing to do with #22493.

**Comment by optio50** [comment]
Sorry, I thought because meunierd specifically addressed this request on that "Issue" it was relevant.
YMMV 
https://github.com/meunierd/youtube-dl/commit/48829c45e00793050504600cfcce97838dcb1b86
