### ISSUE TITLE
Youtube via Google Play Purchase

### ISSUE THREAD

**Issue by kyussqotsa** [ytdl-org/youtube-dl#24066]
I get the following error with v 2020.02.16 installed

> [youtube] Gg7vJJCD7yc: Downloading webpage

> [youtube] Gg7vJJCD7yc: Downloading video info webpage

> ERROR: This video is unavailable.

URL being sought is a google play purchase at this youtube URL (right-click **copy video url** in the player)
https://youtu.be/Gg7vJJCD7yc

which expands to
https://www.youtube.com/watch?v=Gg7vJJCD7yc

**Comment by dstftw** [comment]
You must authenticate.
