### ISSUE TITLE
A and E Networks (ie: A&E, Lifetime, etc) is broken

### ISSUE THREAD

**Issue by roadzy** [ytdl-org/youtube-dl#24065]
## Checklist

- [X ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2020.02.16**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

Output from lifetime
```
youtube-dl https://play.mylifetime.com/shows/surviving-r-kelly/season-2/episode-1 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://play.mylifetime.com/shows/surviving-r-kelly/season-2/episode-1', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.7.2 (CPython) - Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {}
[generic] episode-1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] episode-1: Downloading webpage
[generic] episode-1: Extracting information
ERROR: Unsupported URL: https://play.mylifetime.com/shows/surviving-r-kelly/season-2/episode-1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/generic.py", line 3350, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://play.mylifetime.com/shows/surviving-r-kelly/season-2/episode-1
```
Output from A&E
```
youtube-dl https://play.aetv.com/specials/warren-jeffs-prophet-of-evil/full-special --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://play.aetv.com/specials/warren-jeffs-prophet-of-evil/full-special', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.7.2 (CPython) - Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {}
[generic] full-special: Requesting header
WARNING: Falling back on generic information extractor.
[generic] full-special: Downloading webpage
[generic] full-special: Extracting information
ERROR: Unsupported URL: https://play.aetv.com/specials/warren-jeffs-prophet-of-evil/full-special
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/generic.py", line 3350, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://play.aetv.com/specials/warren-jeffs-prophet-of-evil/full-special
```
## Description

I'm guessing they changed the format of their url and changing it to be play.lifetime.com.  Same goes for A&E.  Just a guess.  My understanding is that you do not need creds to play the video.  If they are needed, I can provide them.

**Comment by killinj** [comment]
This affects me as well, with version 2020.05.03. I cannot find any duplicate issue so I thought I would add to this one. If there is a duplicate, could you let us know where that duplicate is?

For A&E Sites (A&E.com, History, etc) I am receiving an Unsupported URL error for all videos. The videos play within the browsers without any login credentials.

C:\>youtube-dl.exe "https://play.aetv.com/shows/billy-the-exterminator/season-1/episode-1" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://play.aetv.com/shows/billy-the-exterminator/season-1/episode-1', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[generic] episode-1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] episode-1: Downloading webpage
[generic] episode-1: Extracting information
ERROR: Unsupported URL: https://play.aetv.com/shows/billy-the-exterminator/season-1/episode-1
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\generic.py", line 3370, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://play.aetv.com/shows/billy-the-exterminator/season-1/episode-1

**Comment by roadzy** [comment]
@remitamine can you confirm that mine is a duplicate of this one? https://github.com/ytdl-org/youtube-dl/issues/23363

**Comment by roadzy** [comment]
See  https://github.com/ytdl-org/youtube-dl/issues/23363
