### ISSUE TITLE
Cant download

### ISSUE THREAD

**Issue by Rein1980** [ytdl-org/youtube-dl#24086]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi,
Is there a way to download the video from this site:
https://digistudies.nl/vmbo/geschiedenis/b-gebeurtenissen-in-nederland-en-europa-na-1900/b1-de-eerste-wereldoorlog/1-directe-en-indirecte-oorzaken-van-de-eerste-wereldoorlog

Have tried it with manifest but no luck:
https://digistudies-euwe.streaming.media.azure.net/94ea4ffb-5e3d-4b06-827a-fd7811b8a656/5f7d21fd-ddd0-4f14-a8d1-e771e67d.ism/manifest(format=mpd-time-csf,encryption=cbc)

**Comment by dstftw** [comment]
No.

**Comment by remitamine** [comment]
the HLS manifest can be download with this command(replace `[BEARER_TOKEN]` with the one used in the browser):
`youtube-dl --add-header 'Authorization: Bearer=[BEARER_TOKEN]' 'http://digistudies-euwe.streaming.media.azure.net/94ea4ffb-5e3d-4b06-827a-fd7811b8a656/5f7d21fd-ddd0-4f14-a8d1-e771e67d.ism/manifest(format=m3u8-aapl,encryption=cbc)'`

**Comment by Rein1980** [comment]
You mean this one?
![Naamloos](https://user-images.githubusercontent.com/61208208/74783007-f498f300-52a4-11ea-9a98-00bcdb4642ae.png)

But when i use the code:
youtube-dl --add-header 'Authorization: Bearer=[ey......14]' 'http://digistudies-euwe.streaming.media.azure.net/94ea4ffb-5e3d-4b06-827a-fd7811b8a656/5f7d21fd-ddd0-4f14-a8d1-e771e67d.ism/manifest(format=m3u8-aapl,encryption=cbc)'

I got an error: Bearer ........ is not a valid URL
