### ISSUE TITLE
Unable to download movies from CBS All Access

### ISSUE THREAD

**Issue by lonegeek** [ytdl-org/youtube-dl#24081]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.02.16**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line args: [u'-v', u'https://www.cbs.com/movies/star-trek-first-contact/iTGmLzm3gQN57pAqWamGAFpjatqCYgs_/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[generic] iTGmLzm3gQN57pAqWamGAFpjatqCYgs_: Requesting header
WARNING: Falling back on generic information extractor.
[generic] iTGmLzm3gQN57pAqWamGAFpjatqCYgs_: Downloading webpage
[generic] iTGmLzm3gQN57pAqWamGAFpjatqCYgs_: Extracting information
ERROR: Unsupported URL: https://www.cbs.com/movies/star-trek-first-contact/iTGmLzm3gQN57pAqWamGAFpjatqCYgs_/
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2375, in _real_extract
doc = compat_etree_fromstring(webpage.encode('utf-8'))
File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2540, in _XML
parser.feed(text)
File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
self._raiseerror(v)
File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
ie_result = ie.extract(url)
File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
ie_result = self._real_extract(url)
File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 3350, in _real_extract
raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.cbs.com/movies/star-trek-first-contact/iTGmLzm3gQN57pAqWamGAFpjatqCYgs_/
```

## Description

Have an account with CBS All Access (USA).  Passing my username and password as arguments when trying to download the movie.  The website does not require me to pass username and password as arguments when downloading TV shows.

**Comment by dare2** [comment]
I don't think it's CBS All Access per se, as I can download CBS All Access TV shows just fine, like Star Trek Picard. I think it's the new movies they have added, where the movie URLs have a different format than the TV show URLs:

https://www.cbs.com/shows/star-trek-picard/video/OByehBzRg7bOQxNbekLFzyoBLQ0Fwbv5/star-trek-picard-et-in-arcadia-ego-part-2/

https://www.cbs.com/movies/bon-voyage-charlie-brown-and-dont-come-back/vGYMDWBAZ_9R7_mW1fyMxbhtEpRA1w_h/

In the movie link, the title is in the middle of the link, while the tv show episode title is at the end of the link.

It may just need an extra check of the URL for movies and parse it differently.
