### ISSUE TITLE
facebook - ../watch?v={video_id} support

### ISSUE THREAD

**Issue by Zorono** [ytdl-org/youtube-dl#24085]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.02.16**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
`youtube-dl.exe https://www.facebook.com/watch/?ref=saved&v=157002505754521`
must download the following video `https://www.facebook.com/578750342565408/videos/157002505754521/` but it results in
```
C:\Users\Zorono>youtubedl.exe https://www.facebook.com/watch/?ref=saved&v=1570025057
54521
WARNING: Falling back on generic information extractor.
WARNING: Falling back on generic information extractor.
'v' is not recognized as an internal or external command,
operable program or batch file.
```
`/watch?v={video_id}` must be supported(while other url parameters similar to `ref=` must be ignored but they're not...)

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
