### ISSUE TITLE
[niconico] Support encrypted official videos

### ISSUE THREAD

**Issue by tsukumijima** [ytdl-org/youtube-dl#24093]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.02.16**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I did a pull requests (https://github.com/ytdl-org/youtube-dl/pull/23824) before, but I'll post it to the issue just in case.

niconico (Nico Nico Douga) is not known outside of Japan, but is the largest video sharing site in Japan.

### Problem

niconico began using HLS to encrypt the distribution of some official videos, such as anime, on March 5, 2019.
As a result, some official videos can no longer be downloaded with the previously used Extractor.
(Example of video that can be downloaded as before: https://www.nicovideo.jp/watch/sm32868846)
(Example of video that cannot be downloaded due to HLS encryption: https://www.nicovideo.jp/watch/so36189921)

### Correction and resolution

The pull requests I mentioned earlier include an improvement that allows you to download niconico's encrypted HLS videos.
Specifically, it has been modified to make a request to the (most recently published) Ping API (otherwise the download will fail).
In addition, the encrypted HLS video has been modified to send different parameters to the API for acquiring the viewing session than the HTTP video.

On niconico, if you do not send a "heartbeat" every 60 seconds, the download session will be closed and a 403 error will occur.
Short videos can complete the download before the session closes, but long videos do not.
You can "resume" videos that support HTTP, but you can't resume videos that are HLS only.
Therefore, it is necessary to implement a "heartbeat".

The pull requests also include a change that allows you to send a "heartbeat" once every 60 seconds during the download, and to download long videos to the end.
I understand that although some pull requests implementing "heartbeat" have been sent in the past, such as https://github.com/ytdl-org/youtube-dl/issues/14582, they have not been merged even now doing.
The code for "heartbeat" is based on https://github.com/archiif/youtube-dl/pull/1/commits/84995347fccc12f588efe59540418b9070a3c177.
I tried it on various video sites, but adding this feature will not hinder other sites from downloading.
Also, since February 2018, it has been improved to play videos without logging in, so you do not need an account to download.

### lastly

As a side change, we made changes to get high quality thumbnails and original titles.
In addition, support for "heartbeat" has made it easier to download normal niconico HTTP videos (especially long videos) as a side effect, eliminating the need to "resume".

I strongly hope that this change will be incorporated into the project.
Can you merge this (https://github.com/ytdl-org/youtube-dl/pull/23824) Pull requests?

Thank you.

(Sentence may be a bit strange because I am using translation)

**Comment by southrop** [comment]
Would like to see this merged as well. Perhaps worth mentioning that archiif@8499534 is actually also a PR here as #18230

**Comment by tsukumijima** [comment]
> Would like to see this merged as well. Perhaps worth mentioning that [archiif/youtube-dl@8499534](https://github.com/archiif/youtube-dl/commit/8499534) is actually also a PR here as #18230

It is OK to Merge # 18230 before my pull request. However, it has been left for over a year, I don't think it will be merged into the project in the future ...
I thought # 18230 would never be merged anymore, so I incorporated the content of the # 18230 pull request.
I'm not very used to pull requests, but if I get in the way when merging, should I close this pull request once?
