### ISSUE TITLE
Extracting Chinese subtitles from Chinese TV drama on YouTube

### ISSUE THREAD

**Issue by hg2581** [ytdl-org/youtube-dl#24106]
## Checklist

- [x ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I would like to extract the Chinese subtitles from youtube.com/watch?v=LkY0-_qW8x4 but youtube-dl only shows me English, Japanese and Portuguese subtitles. Does that mean the Chinese subtitles are hardcoded and cannot be extracted?

**Comment by dstftw** [comment]
Yes.
