### ISSUE TITLE
[Teachable] Extractor only downloading one video per url.

### ISSUE THREAD

**Issue by diagonal-creator** [ytdl-org/youtube-dl#24100]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.02.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PS E:\sort\ok> .\youtube-dl -i --cookies cookies.txt --verbose -o "local_path\%(playlist_index)s - %(title)s.%(ext)s" --all-subs https://academy.tailoredtutors.co.uk/courses/533962/lectures/12734081
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-i', '--cookies', 'cookies.txt', '--verbose', '-o', 'local_path\\%(playlist_index)s - %(title)s.%(ext)s', '--all-subs', 'https://academy.tailoredtutors.co.uk/courses/533962/lectures/12734081']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 12734081: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 12734081: Downloading webpage
[generic] 12734081: Extracting information
[Wistia] anglm94rzx: Downloading JSON metadata
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://embed.wistia.com/deliveries/ec59269652bbc7afac777a31dfc2e7b1.bin'
[download] local_path\NA - Copy of AQA AS P1 2015 Q1A (Cell Fractionation, Organelles &amp; Calculate Magnification).mp4.bin has already been downloaded
[download] 100% of 78.81MiB
```

## Description

![image](https://user-images.githubusercontent.com/61289646/74963960-7bb3ab80-540a-11ea-91b0-4d3f8b3ab863.png)

As you can see there are three videos present on the webpage so I'd expect three videos as an output. 

However, using the command shown in the log, I only get the first video on the webpage instead of all three. I have read through the documentation and I could not spot anything that would allow the downloading of more than one video per scanned url.

**This issue is present whether or not I have already got the video downloaded or not.**

I'd appreciate any help.

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by diagonal-creator** [comment]
um can I provide the cookie.txt file because it doesnt work with the -u and -p.
[cookies.txt](https://github.com/ytdl-org/youtube-dl/files/4232325/cookies.txt)
