### ISSUE TITLE
Start - end time 

### ISSUE THREAD

**Issue by S4RX** [ytdl-org/youtube-dl#24116]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
First, thanks for such a handy tool as youtube-dl.
Reading the documentation in the OUTPUT TEMPLATE section, I found allowed names such as start_time and end_time. The question is, can I use Python to somehow access them, and not just through cmd?

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl/blob/7f41a598b3fba1bcab2817de64a08941200aa3c8/youtube_dl/extractor/common.py#L94-L303

**Comment by S4RX** [comment]
do you have some function, which can download video from youtube from start_time to end_time?
