### ISSUE TITLE
Use proxy for ytdl.extract_info

### ISSUE THREAD

**Issue by IngeniousCoder** [ytdl-org/youtube-dl#24112]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello,
I would like to check, is it possible for me to specify a proxy to use in `ytdl.extract_info` ?

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L214
