### ISSUE TITLE
atv 2

### ISSUE THREAD

**Issue by avagraha** [ytdl-org/youtube-dl#24115]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2020.02.16**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x curiously closed as invalid ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

C:\Users\andreaa>y --geo-bypass-country AT
https://www.atv.at/lugner-am-opern
ball-2020/opernball-2020/d3002070/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--geo-bypass-country', 'AT', 'https://www.atv.
at/lugner-am-opernball-2020/opernball-2020/d3002070/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-94698-g83e0b71-Reino, ffprobe N-94698-g83e0b
71-Reino, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 77.119.174.182 (AT) as X-Forwarded-For.
[ATVAt] d3002070: Downloading webpage
[ATVAt] 3002154: Downloading m3u8 information
[ATVAt] 3002115: Downloading m3u8 information
[ATVAt] 3002121: Downloading m3u8 information
[ATVAt] 3002061: Downloading m3u8 information
[download] Downloading playlist: Opernball 2020
[ATVAt] playlist Opernball 2020: Collected 4 video ids (downloading 4 of th
em)
[download] Downloading video 1 of 4
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://blocked-multiscreen.atv.cdn.tvnext.
tv/2020/02/HD/6307173/6307173_layer0_5000000/6307173_index0.m3u8'
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpu
z77jgzq\build\youtube_dl\YoutubeDL.py", line 1925, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpu
z77jgzq\build\youtube_dl\YoutubeDL.py", line 1864, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpu
z77jgzq\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpu
z77jgzq\build\youtube_dl\downloader\hls.py", line 62, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpu
z77jgzq\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_respon
se
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain

  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_
default
urllib.error.HTTPError: HTTP Error 403: Forbidden

## Description

WRITE DESCRIPTION HERE
403 forbidden

**Comment by dstftw** [comment]
Video is geo restricted. Stop posting duplicates.

**Comment by avagraha** [comment]
I re-posted because you said just "invalid".
Then, since ORF and ATV do not work with anti geoblock, and you usually 
paste the reply "not all is supposed to work" I ask what is supposed to 
work.
Otherwise you should post a well readable and highlighted warning message 
like "our sw is unable to handle any geo restrictions from Austria". So do 
can waste less time in closing the 3d. Since Servus is not geoblocked and 
much of ORF and ATV (and the bavarian BR) are, after more than one year I 
still have to understand what austrian geoblocked channel is working with 
YTDL, "not all is supposed to work" sounds as a seraphic and (for me) 
mysterious reply that does not help in understanding the problem. In 
addition, other ORF logs (see my account) are clear stating to take contact 
with YTDL dev, what I did.



  ----- Original Message -----

**Comment by dstftw** [comment]
Maybe you'll finally bother to read the description of this option? It won't work if `X-Forwarded-For` is not respected by webserver. Also, usually you should not use this option on your own at all since it's applied automatically when required.
