### ISSUE TITLE
How to log and skip

### ISSUE THREAD

**Issue by Leavemynamealone** [ytdl-org/youtube-dl#24124]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Hello,
Can somebody please help me with the following questions:
1) Is it possible to list channels I subscribed to into txt file and include desired info in it? Like numbers of videos, url, etc?
2) How can I skip download of the channel if the channel has more than X-amount of videos? I see --max-downloads but It's not the same?
3) How to enable logging into txt and log errors (including urls) for videos that failed to download?

**Comment by dstftw** [comment]
1. Parse JSON output and write whatever is needed.
2. Write script.
3. Redirect stdout and stderr to file.
