### ISSUE TITLE
(merging into mkv) Unrecognized option 'disposition:s'.

### ISSUE THREAD

**Issue by mrkapqa** [ytdl-org/youtube-dl#24122]
Hello ,

i don't know if this is an ffmpeg or youtube-dl issue.

on debian wheezy 64bit 
using youtube-dl and youtube-viewer to download / file 

getting error

3.96 MB received in 22 seconds (184 KB/sec)                                 
4.02 MB received in 28 seconds (147 KB/sec)                                 
:: Merging into MKV...
Unrecognized option 'disposition:s'.
Error splitting the argument list: Option not found

-----------------------------
youtube-dl --version
2020.01.24
----------------------------
ffmpeg -version
ffmpeg version 2.1.8
built on Jul 23 2019 18:34:53 with gcc 4.7 (Debian 4.7.2-5)
configuration: --prefix=/home/rich/ffmpeg_build --extra-cflags=-I/home/rich/ffmpeg_build/include --extra-ldflags=-L/home/rich/ffmpeg_build/lib --bindir=/home/rich/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree
libavutil      52. 48.101 / 52. 48.101
libavcodec     55. 39.101 / 55. 39.101
libavformat    55. 19.104 / 55. 19.104
libavdevice    55.  5.100 / 55.  5.100
libavfilter     3. 90.100 /  3. 90.100
libswscale      2.  5.101 /  2.  5.101
libswresample   0. 17.104 /  0. 17.104
libpostproc    52.  3.100 / 52.  3.100

**Comment by mrkapqa** [comment]
thank you, please let me know what i am missing.

**Comment by dstftw** [comment]
Bother to read issue template.
