### ISSUE TITLE
after some try show me this erorr

### ISSUE THREAD

**Issue by miladrajabi2002** [ytdl-org/youtube-dl#24123]
after some try show me this

ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by miladrajabi2002** [comment]
why??

**Comment by dume2007** [comment]
> why??

inextricability
