### ISSUE TITLE
RaiPlay site update

### ISSUE THREAD

**Issue by bunbury86** [ytdl-org/youtube-dl#24125]
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.02.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

youtube-dl --version
2020.02.16
youtube-dl -v https://www.raiplay.it/programmi/bing
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.raiplay.it/programmi/bing']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Python version 2.7.17 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[RaiPlayPlaylist] bing: Downloading webpage
[download] Downloading playlist: Bing
[RaiPlayPlaylist] playlist Bing: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: Bing

## Description

The site structure has changed:
Download list is in 
https://www.raiplay.it/programmi/bing
-->
https://www.raiplay.it/programmi/bing.json
-->
https://www.raiplay.it/programmi/bing/ContentSet-c3866543-23ee-4881-a580-bcfca442755b.json
-->
finally video url is under
"video_url": "http://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=xClMKTC8KntAG3NXwcUi2geeqqEEqualeeqqEEqual"

**Comment by iamleot** [comment]
Hello @bunbury86!

https://github.com/ytdl-org/youtube-dl/pull/23040 should address that.

**Comment by darklamp** [comment]
Hello, may I know why hasn't #23040 been merged already? Have been using it for ~ 2 weeks and it's working just fine.

**Comment by iamleot** [comment]
Hello @darklamp,
I don't think there is any particular reasons: just someone with commit bits has not merged it.

(I also think that the `rai` extractor is usable only with an IP from Italy and that could be a bit more difficult to test too.)

In any case, if there is any problem with it do not hesitate to contact me and I will try to fix/keep it updated as needed!

**Comment by FraMecca** [comment]
Please merge it, it works flawlessy

**Comment by nnsense** [comment]
Apparently this would fix an issue we all have with that site, can I please please ask to merge this? Please? Please?

**Comment by nnsense** [comment]
After having installed the latest version from github and merged https://github.com/ytdl-org/youtube-dl/pull/23040 raiplay works perfectly. We're all at home at the moment, downloading stuff during the night to save bandwidth for the others by watching offline is definitely a great thing to do, we can use the dev version but I don't think merging would take much effort on your end.

**Comment by angus73** [comment]
It works perfectly for me, too. Please consider merging to help people who are not enough skilled to use the dev version, thanks

**Comment by remitamine** [comment]
will be fixed in the next version.
