### ISSUE TITLE
How to assign different title name 

### ISSUE THREAD

**Issue by Lokesh-Reddy-plvd** [ytdl-org/youtube-dl#24137]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

When I use `%(autonumber)s `  title of video Five-digit number is not increasing. Same title name is assigned to every video. 
So, how to assign different title name automatically when multiple videos downloading at a time.

**Comment by dstftw** [comment]
Provide complete verbose log clearly demonstrating the problem.
