### ISSUE TITLE
limit 2 hours ?

### ISSUE THREAD

**Issue by gioreva** [ytdl-org/youtube-dl#24145]
Hi
What mean 100% ?
I had to record three hours, stopped at 1:53
Disk is NTFS, has no this limit, i think

F:\tmp>start /B f:\youtube-dl --socket-timeout 1000 -i http://giors.ddns.net:2300/Miaio/0nHs1goSnM/10493 -o CoseQuestoMondo-s4e17e18e19

[generic] 10493: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 10493: Downloading webpage
WARNING: URL could be a direct video link, returning it as such.
[download] Destination: CoseQuestoMondo-s4e17e18e19
[download] 100% of 2.77GiB in 01:53:35

**Comment by dstftw** [comment]
Meaning that remote party sent empty data block denoting EOF.

**Comment by gioreva** [comment]
It is streaming, it has not EOF

**Comment by dstftw** [comment]
Again: remote party most likely has sent empty block regardless of whether it's streaming or not.
