### ISSUE TITLE
Remove output metadata options that do not apply

### ISSUE THREAD

**Issue by HASJ** [ytdl-org/youtube-dl#24144]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.02.16**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

This is the output argument I am using:
`-o "Downloads\Videos\%(extractor)s - %(uploader)s-%(upload_date)s-%(playlist)s #%(playlist_index)s - %(title)s [%(id)s].%(ext)s"`

I would like for youtube-dl to, instead of always using this and then later requiring me to remove all the NA-NA-NA from files without the tags, know if the downloaded video actually has the tags and do a `if` check.

For example: https://v.redd.it/ps7wzmoq02j41 outputs `Reddit - Artem10397-20200225-NA #NA - Russian cyberpunk. [ps7wzmoq02j41].mp4`.
My feature proposal would make youtube-dl automatically rename it to `Reddit - Artem10397-20200225- Russian cyberpunk. [ps7wzmoq02j41].mp4`

**Comment by dstftw** [comment]
That's technically impossible to implement what you request in your example. The max that can be is inserting empty strings instead of `NA`.

**Comment by canlang** [comment]
> That's technically impossible to implement what you request in your example. The max that can be is inserting empty strings instead of `NA`.

Are you saying that it's now possible to change to an empty string? 
I agree with the @HASJ 's intention. It would be nice to change the NA statement with **conditional** or **OR** operation.
