### ISSUE TITLE
!is_live filter no longer working?

### ISSUE THREAD

**Issue by R01NDev** [ytdl-org/youtube-dl#24146]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Here are my parameters

ydl_opts = {'match_filter': youtube_dl.utils.match_filter_func("!is_live"), 'retries':4, 'ignoreerrors': True, 'format': 'mp4', 'subtitleslangs': ['en'], 'writeautomaticsub': True, 'convertsubtitles': 'srt', 'restrictfilenames': True, 'outtmpl': fileDirectory}

This is causing my whole script to stop and download a live stream that goes on for 11 hours every day. Any idea what's wrong or why it's not skipping

**Comment by R01NDev** [comment]
???????

**Comment by R01NDev** [comment]
so you just decided to close the issue when the question is clear and instructions were followed? Very professional and helpful of you

**Comment by dstftw** [comment]
There are no telepathists here. Bother to read new issue template and provide **complete** info you must to provide. I'm not going to bother pulling it from you on my own.
