### ISSUE TITLE
Youtube Livestream-Record doesn't stop after Stream-End

### ISSUE THREAD

**Issue by Finalsharex** [ytdl-org/youtube-dl#24154]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hey Guys,

I'm working on an automated bash script to record youtube streams and save them.

```
#! /bin/bash
NOW=$( date '+%F_%H:%M:%S' )

while true;
do
dir=/
name=XXX_$NOW
name=$name
youtube-dl --exec './record.sh' -c -i -f 94 youtube.com/channel/XXX/live -o "$dir/$name.mp4";
sleep $[((400 + RANDOM % 200))]s
done;
```

Everything is working fine so far, but i'm running into an issue when the stream is supposed to end.
Instead of ending the record and saving everything in my mp4 it just loops seeming endlessly with this message:
[Image](https://i.imgur.com/f2Km854.png)
I can end this with Ctrl+C and it writes the file just fine, but since it's supposed to be automated this doesn't work.

I already tried with socket-timeout and many other variables, but seems like nothing helps.
If i replace the Stream-URL with a video it works. It downloads the video, saves it and runs that script again with a random 400-600s timer till the broadcaster starts streaming again
Is anyone familiar with this case?

**Comment by BobVul** [comment]
If you have a new enough ffmpeg version, it'll support [the `m3u8_hold_counters` option](https://ffmpeg.org/ffmpeg-formats.html#hls-1) for HLS streams, defaulting to 1000. Setting this to a lower value (10-100) can help terminate the download faster when a stream has stopped updating. This can be done by adding downloader args to ytdl:

```
--external-downloader-args "'-m3u8_hold_counters' 10"
```
