### ISSUE TITLE
How do i automatically update URL each time when a user entered a new url  

### ISSUE THREAD

**Issue by bigsandip** [ytdl-org/youtube-dl#24177]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

Iam building a simple video downloader from any website in django. Whenever a user entered a url in a url field i capture it in views.py by `URL_LIST = form.cleaned_data['url']` .Now i want to automatically update url in this line `("youtube-dl -f best --output ~/Downloads/%(title)s.%(ext)s  -ik --format mp4  --yes-playlist **URL_LIST** ")`  .I know another way is to write the user entered url to a .txt file and read from it like `os.system("youtube-dl -f best --output ~/Downloads/%(title)s.%(ext)s  -ik --format mp4  --yes-playlist -a list.txt ")` but some reason the server didnt give  read/write permission to list.txt file in production.

**Comment by dstftw** [comment]
Use python string formatting obviously.
