### ISSUE TITLE
xhamster broken Error 403, tried test link from xhamster.py

### ISSUE THREAD

**Issue by gaming-hacker** [ytdl-org/youtube-dl#24179]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.02.16**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by zouhair** [comment]
It seems like their video links now force referer to their own website

`"https://ip91164464.ahcdn.com/key=Spj7zdNDVzcxddY3uXnPGw,s=,end=1582981200,limit=3/data=142.182.76.210-dvp/state=jrZM/buffer=1250000:889568,1034.0/speed=250000/referer=force, .xhcdn.com,.xhamster.com/reftag=78545629/ssd1/21/7/200960567/013/761/363/720p.h264.mp4`

Adding `--referer="https://xhamster.com"` fixes the problem

**Comment by zouhair** [comment]
It's still needs to be fixed
