### ISSUE TITLE
ERROR: This video is unavailable.

### ISSUE THREAD

**Issue by lump72** [ytdl-org/youtube-dl#24187]
- [ ] I'm reporting a broken site support

## Verbose log
youtube-dl "https://www.youtube.com/watch?v=Qe-ehQlYL5g&list=RDEMbF4UEQROWmLzDyjQq0uL8A&start_radio=1" --verbose
[debug] System config: []
[debug] User config: [u'-x', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'-o', u'~/download/%(playlist)s/%(chapter_id)s/%(playlist_index)s_%(artist)s_%(album)s_%(track)s_%(fulltitle)s.%(ext)s', u'--yes-playlist']
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=Qe-ehQlYL5g&list=RDEMbF4UEQROWmLzDyjQq0uL8A&start_radio=1', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.02.16
[debug] Python version 2.7.16 (CPython) - Linux-4.19.75-v7l+-armv7l-with-debian-10.2
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist RDEMbF4UEQROWmLzDyjQq0uL8A - add --no-playlist to just download video Qe-ehQlYL5g
[youtube:playlist] RDEMbF4UEQROWmLzDyjQq0uL8A: Downloading page 1 of Youtube mix
[youtube:playlist] RDEMbF4UEQROWmLzDyjQq0uL8A: Downloading page 2 of Youtube mix
[youtube:playlist] RDEMbF4UEQROWmLzDyjQq0uL8A: Downloading page 3 of Youtube mix
[youtube:playlist] RDEMbF4UEQROWmLzDyjQq0uL8A: Downloading page 4 of Youtube mix
[download] Downloading playlist: Mix - Hamo & Tribute 2 Love
[youtube:playlist] playlist Mix - Hamo & Tribute 2 Love: Collected 70 video ids (downloading 70 of them)
[download] Downloading video 1 of 70
[youtube] zDyjQq0uL8A: Downloading webpage
[youtube] zDyjQq0uL8A: Downloading video info webpage
WARNING: Unable to extract video title
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: This video is unavailable.
Sorry about that.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2153, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.
Sorry about that.

Regards,
lump72

**Comment by pladaria** [comment]
same here, using latest version (2019.07.02)

```
youtube-dl --verbose https://www.youtube.com/watch?v=5DDEl7JnWvo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=5DDEl7JnWvo']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.02
[debug] Python version 2.7.16 (CPython) - Darwin-19.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg present, ffprobe present, rtmpdump Reason
[debug] Proxy map: {}
[youtube] 5DDEl7JnWvo: Downloading webpage
[youtube] 5DDEl7JnWvo: Downloading video info webpage
WARNING: Unable to extract video title
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2097, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.
```
