### ISSUE TITLE
ERROR: requested format not available

### ISSUE THREAD

**Issue by pestostohe** [ytdl-org/youtube-dl#24218]
video location:
https://ktla.com/news/coronavirus/u-s-surgeon-general-urges-public-to-stop-buying-masks-says-theyre-ineffective-in-preventing-coronavirus-spread/

list formats:
youtube-dl --list-formats "https://house-fastly.us-east-1.ooyala.com/NkdnQ4ajE69PO8SHWQmGAru4-e9kgBHq/1/dash/1.mpd"

[info] Available formats for 1:
format code           extension  resolution note
640_600K_audio_und    m4a        audio only DASH audio   97k , m4a_dash container, mp4a.40.2 (44100Hz)
1280_1000K_audio_und  m4a        audio only DASH audio  129k , m4a_dash container, mp4a.40.2 (44100Hz)
640_600K_video_1      mp4        640x360    DASH video  849k , mp4_dash container, avc1.42C01E, video only
1280_1000K_video_1    mp4        1280x720   DASH video 1492k , mp4_dash container, avc1.42C01F, video only
1280_1600K_video_1    mp4        1280x720   DASH video 2331k , mp4_dash container, avc1.42C01F, video only
1920_2600K_video_1    mp4        1920x1080  DASH video 3851k , mp4_dash container, avc1.42C028, video only
1920_3600K_video_1    mp4        1920x1080  DASH video 5056k , mp4_dash container, avc1.42C028, video only (best)

download command:
youtube-dl --format 640_600K_video_1,640_600K_audio_und "https://secure-cf-c.ooyala.com/1kOHFrZDE6SPnehSpHMGthN2dut_2uxA/1/dash/1.mpd"

result:
ERROR: requested format not available

**Comment by dstftw** [comment]
You must use format ids from exactly the same URL you used for listing formats.
