### ISSUE TITLE
[FR] Downloading links of Youtube-videos as *.url files

### ISSUE THREAD

**Issue by squromiv** [ytdl-org/youtube-dl#24225]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.01**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description
I can not find a tool to save links on all videos from a certain channel or playlist from Youtube. I prefer to store them on my local PC as *.url files. In my opinion, youtube-dl tool will be the best to do it in simulate mode. 
![screen_2020 03 03 002](https://user-images.githubusercontent.com/15985877/75774795-c36af900-5d61-11ea-977d-ad52b5fc77fb.png)

**Comment by dstftw** [comment]
This is pointless since download links expire and bound to session/IP/cookies/headers.

**Comment by squromiv** [comment]
You didn`t understand. I don`t need download links. I store static links to pages with videos on Youtube. It`s like bookmarks. So I need to extract links to all videos from channel and save them as *.url files.

**Comment by dstftw** [comment]
Then this has nothing to do with youtube-dl at all.
