### ISSUE TITLE
 Unable to download webpage: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by jeancc** [ytdl-org/youtube-dl#24238]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
 youtube-dl --verbose  https://www.youtube.com/watch?v=1316a92f-1ef7-404a-5b86-08d7c013d6db

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=1316a92f-1ef7-404a-5b86-08d7c013d6db']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.01
[debug] Python version 2.7.13 (CPython) - Linux-4.19.66-v7+-armv7l-with-debian-9.11
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 1316a92f-1e: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

## Description

I'm trying to get data and play the video in raspbian 9, omxplayer. Youtube-dl says "two many connections". But I've tried with a pure debian 9 using mpv and the video is playing without problems. Same network for the PC for all the computers and rasps.

**Comment by danfiscus** [comment]
There's a pinned issue on the repo regarding this, have you read through that?
https://github.com/ytdl-org/youtube-dl/issues/23638

**Comment by jeancc** [comment]
Yes, but it's so strange that mpv is running well streaming youtube videos (i think is using youtube-dl internally) and omxplayer+youtube-dl not.  My rasp is in the same network than the PC, so... posible bug?
