### ISSUE TITLE
Cannot extract metadata from youtube video in Raspbian 9

### ISSUE THREAD

**Issue by daniherculano84** [ytdl-org/youtube-dl#24249]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.03.01**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
 File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```

## Description

I'm trying to extract metadata from youtube videos, using two raspberry. One of them with Raspbian 9, the other with Raspbian 10. Same network configuration. All two operating systems are up to date.

Raspbian 10 works great. Raspbian 9 outputs errors in some .py code files

These are the videos showing the behavior:

Video [Raspbian 9](https://drive.google.com/open?id=1aNVHq3OX3ZrcopxqgNIoMRqikKmIP3xw)
Video [Raspbian 10](https://drive.google.com/open?id=1HkaZ4KmUAyadRDN08b_61JjjZjwYPe6Y)

I'll give remote access if needed.

Thanks

**Comment by daniherculano84** [comment]
What information is missing?

**Comment by dstftw** [comment]
Bother to read new issue template.
