### ISSUE TITLE
How to get a low-bitrate Opus from Youtube?

### ISSUE THREAD

**Issue by DynV** [ytdl-org/youtube-dl#24246]
I'm currently using
> youtube-dl --extract-audio --audio-format opus --audio-quality 8

and when looking at VLC codec info (Ctrl-J) and media statistics (other tab (from same window)) it show it's an Opus 32 bit 48 KHz and I estimate from the content bitrate fluctuation that its average is 150 Kbps (Is there a better way to get its average?) but I'd like something with a smaller file size. When I stream AAC 32 Kbps (radio), I like the (sound) quality; perhaps Opus would be a similar quality at that bitrate, or even better? I tried
> youtube-dl -f 'bestaudio' --audio-format opus --audio-quality 8

and the result is (sounds) horrible.

As the title: How to get a low-bitrate Opus from Youtube?

Thank you kindly

**Comment by dstftw** [comment]
Read FAQ on format selection.

**Comment by DynV** [comment]
I've read https://github.com/ytdl-org/youtube-dl#format-selection and I can't find what I'm looking for. I'm looking for something automated, I don't want to so _-F_ then pick an audio format using _-f [format code]_.

I'd like for the following to be done automatically:
1. download an Opus between 24 & 48 Kbps
2. download an AAC between 24 & 48 Kbps
3. download the best audio then be converted to a maximum of 32 Kbps Opus (if the original format wouldn't sound better than a lower bitrate, than the lower bitrate to be converted to).

**Comment by DynV** [comment]
If you won't assist any further on this, could you provide a resource where they could (ie: a forum URL) ?

**Comment by dstftw** [comment]
You don't need to specify format by format code you must provide format selection expression. Bother to already read it. I'm not going to assist something already answered thousand times.
