### ISSUE TITLE
How can I download latest video from a youtube channel?

### ISSUE THREAD

**Issue by trappedinspacetime** [ytdl-org/youtube-dl#24241]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I want to get the  latest youtube video from a user channel. I tried the following command

       youtube-dl --date now  -f best https://www.youtube.com/channel/UCMKiY_wDgXFaY8Xq-VG41EQ
But the user's channel has 271 pages, it attempts to download all the pages which takes too much time. I checked out the page, latest video is always  in the first page.
How can I force `youtube-dl` to check only the first page for the latest video?

**Comment by dstftw** [comment]
Read FAQ.
```
--playlist-start NUMBER          Playlist video to start at (default is 1)
--playlist-end NUMBER            Playlist video to end at (default is last)
```
