### ISSUE TITLE
[vimeo] playlist download fails with `ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError())`

### ISSUE THREAD

**Issue by aktivcorp** [ytdl-org/youtube-dl#24262]
**Verbose log**
<pre>$ youtube-dl --verbose --list-formats https://vimeo.com/392712342
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--list-formats', u'https://vimeo.com/392712342']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.01
[debug] Python version 2.7.6 (CPython) - Linux-3.13.0-85-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 392712342: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
</pre>

**Comment by remitamine** [comment]
```
youtube-dl --verbose --list-formats https://vimeo.com/392712342
[debug] System config: []
[debug] User config: ['-f', 'best[height<=768]/bestvideo[height<=768]+bestaudio/best', '--hls-prefer-ffmpeg', '--external-downloader', 'curl', '--sub-format', 'ass/tt/ttml/dfxp/scc/vtt/srt/sami/best']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--list-formats', 'https://vimeo.com/392712342']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.06
[debug] Python version 3.8.2 (CPython) - Linux-5.5.7-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 392712342: Downloading webpage
[vimeo] 392712342: Extracting information
[vimeo] 392712342: Downloading JSON metadata
[vimeo] 392712342: Downloading JSON metadata
[vimeo] 392712342: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 392712342: Downloading fastly_skyfire m3u8 information
[vimeo] 392712342: Downloading akfire_interconnect_quic MPD information
[vimeo] 392712342: Downloading fastly_skyfire MPD information
[info] Available formats for 392712342:
format code                                      extension  resolution note
dash-akfire_interconnect_quic-audio-07e642ac     m4a        audio only DASH audio   64k , m4a_dash container, mp4a.40.2 (24000Hz)
dash-fastly_skyfire-audio-07e642ac               m4a        audio only DASH audio   64k , m4a_dash container, mp4a.40.2 (24000Hz)
dash-akfire_interconnect_quic-audio-39c4bd40     m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-fastly_skyfire-audio-39c4bd40               m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-akfire_interconnect_quic-audio-05b2760f     m4a        audio only DASH audio  255k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-fastly_skyfire-audio-05b2760f               m4a        audio only DASH audio  255k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-akfire_interconnect_quic-video-07e642ac     mp4        426x180    DASH video  342k , mp4_dash container, avc1.640015, video only
dash-fastly_skyfire-video-07e642ac               mp4        426x180    DASH video  342k , mp4_dash container, avc1.640015, video only
dash-akfire_interconnect_quic-video-39c4bd40     mp4        640x270    DASH video  568k , mp4_dash container, avc1.64001E, video only
dash-fastly_skyfire-video-39c4bd40               mp4        640x270    DASH video  568k , mp4_dash container, avc1.64001E, video only
dash-akfire_interconnect_quic-video-05b2760f     mp4        720x304    DASH video 1457k , mp4_dash container, avc1.64001F, video only
dash-fastly_skyfire-video-05b2760f               mp4        720x304    DASH video 1457k , mp4_dash container, avc1.64001F, video only
hls-akfire_interconnect_quic-audio-high-audio    mp4        audio only 
hls-akfire_interconnect_quic-audio-medium-audio  mp4        audio only 
hls-fastly_skyfire-audio-high-audio              mp4        audio only 
hls-fastly_skyfire-audio-medium-audio            mp4        audio only 
http-240p                                        mp4        426x180    23fps
hls-akfire_interconnect_quic-445                 mp4        426x180     445k , avc1.640015, 23.976fps, video only
hls-fastly_skyfire-445                           mp4        426x180     445k , avc1.640015, 23.976fps, video only
http-360p-0                                      mp4        640x270    23fps
hls-akfire_interconnect_quic-665                 mp4        640x270     665k , avc1.64001E, 23.976fps, video only
hls-fastly_skyfire-665                           mp4        640x270     665k , avc1.64001E, 23.976fps, video only
http-360p-1                                      mp4        720x304    23fps
hls-akfire_interconnect_quic-1060                mp4        720x304    1060k , avc1.64001F, 23.976fps, video only
hls-fastly_skyfire-1060                          mp4        720x304    1060k , avc1.64001F, 23.976fps, video only (best)
```

**Comment by AlexR1712** [comment]
Getting the same error using youtube-dl with vimeo

[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-40-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 267040577: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by EugeneLugin** [comment]
For me the same situation was caused by country-based access blocking on vimeo side. Proxy is the solution.
