### ISSUE TITLE
How do I make ytdl prefer best fps rather than best bitrate?

### ISSUE THREAD

**Issue by epik64** [ytdl-org/youtube-dl#24275]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How do I make ytdl automatically prefer best fps+bitrate rather than just best bitrate? For example, when downloading https://www.youtube.com/watch?v=Xm8UTv6LSf0 with best video+audio, it downloads the 30fps format because it has a higher bitrate than 60fps format.

**Comment by dstftw** [comment]
It does not prefer by only bitrate in the first place. You can't manage the order of sorting criteria.
