### ISSUE TITLE
Deleted videos in a playlist (youtube) yields in errormessage and exiting -> no more downloads

### ISSUE THREAD

**Issue by klartext** [ytdl-org/youtube-dl#24274]
youtube-dl version: 2020.03.06

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.03.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

The urls with the deleted videos (which are not deleted from a playlist) can't be played with the browser. The browser skips the video and plays the next one.
youtube-dl does not skip the missing video, but stops downloading.

(It was the first video of the playlist, so nothing was downloaded.)

## Verbose log

Can't quote the verbose log completely.
I only saved the last part of it and in the meantime the deleted video was removed from the playlist (I had asked the youtube-user to do that before I decided to write this bug-report).
So I can't reproduce the problem again.

The only snippet that I have available is the last part:

```
ERROR: This video has been removed by the user
Sorry about that.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2153, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video has been removed by the user
Sorry about that.
```

## Description

Downloading a playlist stops, if a video has been deleted but has not been removed from the playlist.

The urls with the deleted videos (which are not deleted from a playlist) can't be played with the browser. The browser skips the video and plays the next one.
youtube-dl does not skip the missing video, but stops downloading.

**Comment by remitamine** [comment]
```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
```
