### ISSUE TITLE
How to give the downloaded file a custom name.

### ISSUE THREAD

**Issue by AnishLaddha** [ytdl-org/youtube-dl#24286]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi everyone.

Is it possible to give the file being downloaded a custom name? the titles i want to give them are not related to the youtube video. Thank you

**Comment by dstftw** [comment]
Read FAQ on output template.
