### ISSUE TITLE
Youtube HTTP 429 [Reproducible environment available]

### ISSUE THREAD

**Issue by JaegerMa** [ytdl-org/youtube-dl#24283]
Steps to reproduce in the provided environment:
- Download serveral videos to initally trigger the HTTP 429s
- Navigate to any Youtube video in Firefox => Plays without problems
- Export cookies (suitable extension installed)
- Call youtube-dl with the exported cookies and the opened Youtube video => Gets HTTP 429

An email with the access information to the environment has been sent to dstftw.

**Comment by dstftw** [comment]
Which Firefox add-on exactly you are using?

**Comment by JaegerMa** [comment]
I'm using https://addons.mozilla.org/en-US/firefox/addon/export-cookies-txt/

**Comment by dstftw** [comment]
Check `YSC` session cookie is exported.

**Comment by JaegerMa** [comment]
Yes, is exported as `.youtube.com	TRUE	/	TRUE	0	YSC	<VALUE>`

**Comment by dstftw** [comment]
Do you access youtube.com via the same network interface?

**Comment by JaegerMa** [comment]
Yes, the machine has only a single network interface beside `lo`.

**Comment by dstftw** [comment]
I mean do you use the same external IP? Browser uses v4 by default while youtube-dl may use v6.

**Comment by JaegerMa** [comment]
Yes, I also did the test with IPv6 disabled.

**Comment by J-Spade** [comment]
just wanna thank @JaegerMa for reproducing this reliably and @dstftw for working to address it. I know I'm not the only one who's been fighting this intermittently for ages
