### ISSUE TITLE
Whether I can call youtube-dl directly from PowerShell script?

### ISSUE THREAD

**Issue by hachi1030-Allen** [ytdl-org/youtube-dl#24298]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [] I've searched the bugtracker for similar questions including closed ones

## Question

youtube-dl.exe is quite an excellent tool for using. However, I do want to automation some work, so I wrote a powershell script to make life easier.

The thing is, currently from my PowerShell script, I need to launch `cmd.exe` to run the commands for youtube-dl, that ends with I can never do error handling.

Like yesterday, there is some random issue with one video subtitle's download, but I cannot get the error and some of my PowerShell script is not working normally.

So, I 'd like to ask below things:

1. Whether youtube-dl can be called from programming language or scripts language such as Powershell, C#, Java, etc?
2. If not, whether it's possible to get the cmd running result such as my scenario? I launch cmd.exe and run the command and when the command is done, my PowerShell script can get some result or something?

Thanks and look forward to the reply.

Allen

**Comment by dstftw** [comment]
youtube-dl can be called from anywhere as any other executable.
