### ISSUE TITLE
instgram cookies cause youtube-dl cookie file to broken

### ISSUE THREAD

**Issue by EhsanCh** [ytdl-org/youtube-dl#24299]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: [u'-4', u'--cookies', u'/home/youtube-cookie.txt']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.instagram.com/p/B9g4ilHJOv7/']
/usr/lib64/python2.7/_MozillaCookieJar.py:109: UserWarning: cookielib bug!
Traceback (most recent call last):
  File "/usr/lib64/python2.7/_MozillaCookieJar.py", line 71, in _really_load
    line.split("\t")
ValueError: too many values to unpack

  _warn_unhandled_exception()
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 441, in _real_main
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 419, in __init__
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2329, in _setup_opener
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 2762, in load
  File "/usr/lib64/python2.7/_MozillaCookieJar.py", line 111, in _really_load
    (filename, line))
cookielib.LoadError: invalid Netscape format cookies file u'/home/youtube-cookie.txt': u'.instagram.com\tTRUE\t/\tTRUE\t0\turlgen\t"{\\"45.12.3.45\\":\t24940}:1jBJ5c:yMVdw1trErKtMZlJkGK3zfvFI4U"'

```

## Description

When downloading instagram video, it sent a cookie like :
`"{\"45.12.3.45\": 24940}:1jBJ5c:yMVdw1trErKtMZlJkGK3zfvFI4U"`
and write a line in cookie file:
`.instagram.com  TRUE    /       TRUE    0       urlgen  "{\"45.12.3.45\": 24940}:1jBJ5c:yMVdw1trErKtMZlJkGK3zfvFI4U"`
causing cookie file to be invalid for next youtube-dl run.

**Comment by dstftw** [comment]
Malformed cookie file. Cookie value is not allowed to contain spaces.

**Comment by kruug** [comment]
Used this tool: https://github.com/lennonhill/cookies-txt

Now you're telling me that the tool to export a Netscape Compatible cookie file isn't exporting a Netscape cookie file?  It seems like shoddy dev work on your team...

**Comment by EhsanCh** [comment]
Cookie version 0 does not allow cookies but [v1](http://www.ietf.org/rfc/rfc2109.txt) allow cookies.
According to RFC 2109, "HTTP State Management Mechanism", white space in cookie values must be encoded or the entire value must be quoted .([source](https://knowledgebase.progress.com/articles/Article/000034412))
As we cannot ask instagram to use cookie version 0, youtube-dl should be updated.

**Comment by EhsanCh** [comment]
As a quick fix, youtube-dl can at least ignore such cookies and don't stop for such errors...
then cookie component should be fixed, if it require more time.

**Comment by dstftw** [comment]
RFC2109 is obsolete. Current RFC 6265 clearly disallows spaces inside cookie values.
