### ISSUE TITLE
Add support for option to select bestvideo quality and preserve audio track

### ISSUE THREAD

**Issue by tapika** [ytdl-org/youtube-dl#24303]
By default youtube-dl provides wide range of options to select specific format, however -
`-f best` not always downloads best quality video. I have tried quite many other alternatives, but if you specify `-f bestvideo, bestaudio` - then audio is download in separate from video, or you need to have ffmpeg toolset installed.

I would prefer that it would be possible to select best video and preserve any audio, which was originally in youtube video.

`youtube-dl.exe -f "(mp4)[width>=1920],keep" https://www.youtube.com/watch?v=O_t3w_jyrGQ`

here is an example of command line, from my perspective it should download best video, and preserve audio. External tools (ffmpeg) should not be required.

**Comment by dstftw** [comment]
Have you read format selection section at all? `bestvideo` is **video only** there is no audio to preserve.

**Comment by tapika** [comment]
What if I want to select best video based on video quality, but by preserving audio track ?
