### ISSUE TITLE
Youtube unsupported url

### ISSUE THREAD

**Issue by mdmrcglu** [ytdl-org/youtube-dl#24301]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

-bash-4.2# youtube-dl https://youtu.be/1D4G5hAWFA -v                         [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://youtu.be/1D4G5hAWFA', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.6.8 (CPython) - Linux-4.9.103-xxxx-std-ipv6-64-x86_64-with-centos-7.5.1804-Core
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[generic] 1D4G5hAWFA: Requesting header
[redirect] Following redirect to https://www.youtube.com/watch?v=1D4G5hAWFA&feature=youtu.be
[generic] watch?v=1D4G5hAWFA&feature=youtu: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?v=1D4G5hAWFA&feature=youtu: Downloading webpage
[generic] watch?v=1D4G5hAWFA&feature=youtu: Extracting information
ERROR: Unsupported URL: https://www.youtube.com/watch?v=1D4G5hAWFA&feature=youtu.be
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3351, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.youtube.com/watch?v=1D4G5hAWFA&feature=youtu.be

-bash-4.2#

```

-bash-4.2# youtube-dl https://youtu.be/1D4G5hAWFA -v                         [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://youtu.be/1D4G5hAWFA', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.6.8 (CPython) - Linux-4.9.103-xxxx-std-ipv6-64-x86_64-with-centos-7.5.1804-Core
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[generic] 1D4G5hAWFA: Requesting header
[redirect] Following redirect to https://www.youtube.com/watch?v=1D4G5hAWFA&feature=youtu.be
[generic] watch?v=1D4G5hAWFA&feature=youtu: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?v=1D4G5hAWFA&feature=youtu: Downloading webpage
[generic] watch?v=1D4G5hAWFA&feature=youtu: Extracting information
ERROR: Unsupported URL: https://www.youtube.com/watch?v=1D4G5hAWFA&feature=youtu.be
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3351, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.youtube.com/watch?v=1D4G5hAWFA&feature=youtu.be

-bash-4.2#
```

## Description

Hello
Valid youtube url but youtube-dl said unsupported url. 
Youtube-dl Version 08.03.2020

**Comment by remitamine** [comment]
most likely you didn't copy the full URL, getting this message in the browser.
```
Video unavailable
```
