### ISSUE TITLE
How to replace an expired m3u8 by a new one in order to continue downloading from the last downloaded segment?

### ISSUE THREAD

**Issue by manabeid** [ytdl-org/youtube-dl#24321]
## Checklist

- [x] I'm asking a question
- [x] I've searched the bugtracker for similar questions including closed ones

- [x] I've looked through the README and FAQ for similar questions

## Question

**Edit**: Sorry for skipping the form. Promise to never let it happen again.

Hi guys,
First of all, let me appreciate your incredible work. Been using it for a while and it's really useful.

I'm trying to download a video using Youtube-dl. Sadly the m3u8 is expired in short time (almost 20 seconds). Fortunately, I managed to find a way to renew the m3u8 link using PHP and Now the question is, possible to make something like a script in order to pass those m3u8 urls to Youtube-dl and then expect Youtube-dl to skip the expired m3u8 and use the next m3u8 I'll pass to it? 

**To be more clear, I can renew the m3u8 links but still looking for a way to ask Youtube-dl to replace the m3u8 link automatically after being expired.**

**Comment by dstftw** [comment]
Dynamic HLS livestreams are processed automatically via ffmpeg. You don't need to renew anything in the first place.

**Comment by manabeid** [comment]
> Dynamic HLS livestreams are processed automatically via ffmpeg. You don't need to renew anything in the first place.

Please check the screenshot.
https://i.imgur.com/kCacbuj.png

It can download segment 1-100 and then the m3u8 turns expired (i.e. none of its segments can be downloaded 403.forbidden) but I can renew the m3u8 and download next segments (saying 101-160) and then this one becomes expired too. 

As said before my own script can generate new m3u8 links on the fly. there any workaround to pass it to **Youtube-dl**/**ffmpeg** to keep on downloading?
