### ISSUE TITLE
[YOUTUBE] Invalid URL returned

### ISSUE THREAD

**Issue by DmytroBrovkin** [ytdl-org/youtube-dl#24339]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-g', u'-v', u'r9_Id6nsZS4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 2.7.16 (CPython) - Darwin-19.2.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
```

## Description

Hi,
VideoId = "r9_Id6nsZS4"
SDK returns URL, but it is invalid. If you try to load video with this url, 403 would be returned. As a result, player would stuck loading forever. Please assist.

Example of returned URL:
https://r2---sn-8vap5-3c2s.googlevideo.com/videoplayback?expire=1584095115&ei=KwtrXro0yu7tBNn_jNAM&ip=77.123.146.24&id=o-AEEWErWcg4gFH-4gUKaRWqzhbVmUFS_klt7YkLFpQHZU&itag=251&source=youtube&requiressl=yes&mh=g2&mm=31%2C26&mn=sn-8vap5-3c2s%2Csn-f5f7lnel&ms=au%2Conr&mv=m&mvi=1&pl=19&initcwndbps=1170000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=2930925&dur=178.461&lmt=1575005321100386&mt=1584072644&fvip=2&keepalive=yes&fexp=23842630%2C23882513&beids=9466586&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRQIhAJoKCI38_zIV1fmBIOuZKqslYLH9P5zdU0VtK2oaq3APAiAwUZ80AYtulw7hraz91LJ7KFKRDs3CmfONl7NRsaYFzg%3D%3D&sig==S1j7XjnrN3-y9MfNdsXl63W9vP85iZxmkeLMxgC3DSCQIC4IYLZAOzEtw4vM00ncMgd3A9uKDS-E2nG_Eh24Bu30fgIQRwMGkhKDADi&ratebypass=yes

**Comment by dstftw** [comment]
You must authenticate for age-gated videos.
