### ISSUE TITLE
Can I compose a format of two urls (video+audio)?

### ISSUE THREAD

**Issue by nielsrune** [ytdl-org/youtube-dl#24342]
I'm working on a fallback for the tvplay.py extractor, since some stream links are not available from the API.

I have found an alternative API. However, it uses EXT-X-MEDIA. So all videos are without audio and the audio tracks is stored separately.

Formats list is accordingly two audio-only and a couple of video-only. Without specifying a format, yt selected the highest video resolution and combining the audio.

But is it possible to, in the extractor, to "compose" joint formats for the different resolutions. So, if I want the second best resolution, I wouldn't have to add eg.: -f video[height=720]+bestaudio

**Comment by dstftw** [comment]
Extractor has nothing to do with "composing" in the first place. The goal of extractor is to provide data not to perform any processing.

**Comment by nielsrune** [comment]
I nearly feel like saying `<irony>Forgive me for asking</irony>`

Without specifying a format, YT currently combines the best audio and best video. So what I asked, YT already does! Maybe not in an extractor but then somewhere else.

I merely asked for help combining non-best video-only formats with audio to spare end users the same.

I guess I just keep the fallback solution on my own, then.
