### ISSUE TITLE
Youtube playlists

### ISSUE THREAD

**Issue by SergVG** [ytdl-org/youtube-dl#24355]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

Hello! I want feature for get the list of separate yotube video's urls from playlist. For example: 
in: https://www.youtube.com/playlist?list=PLWWVGE5JYquJTRVFI04JyQamUKk8tuPQQ
Out: 
https://www.youtube.com/watch?v=kG1dYVQSEe0
https://www.youtube.com/watch?v=eU55FWuGJRg
... etc.

**Comment by dstftw** [comment]
Extract as JSON then parse it.
