### ISSUE TITLE
Ability to pass a text file with keywords to the ytsearchall/ytsearchdateall flags

### ISSUE THREAD

**Issue by kolt54321** [ytdl-org/youtube-dl#24351]
- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

So I've recently discovered the ytsearch flags, which allows the user to specify a search query and run the subsequent youtube-dl command on the results.

Currently, the ytsearch flags seem to only take a single keyword. Could we add the ability to loop through a text file with keywords, similar to how the user can specify a text file of videos to iterate through?

**Comment by dstftw** [comment]
1. `ytsearch` does not take keywords in the first place. It's an arbitrary string search query.
2. Bother to read FAQ: `--batch-file`.
