### ISSUE TITLE
Ability to support calculations in --Match-filter

### ISSUE THREAD

**Issue by kolt54321** [ytdl-org/youtube-dl#24358]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

Can the ability be added to perform calculations on supported keys in --match-filter, where all keys are numeric? For example, if the user would like to filter videos that have a like ratio of over 95%, support for:

- ```--match-filter 'like_count/(like_count + dislike_count) > .95'```
or
- ```--match-filter 'like_count > dislike_count *95'```

**Comment by dstftw** [comment]
No. If you need more complicated logic than filtering then write a script.
