### ISSUE TITLE
Ability to pass a text file with keywords to the ytsearchall/ytsearchdateall flags

### ISSUE THREAD

**Issue by kolt54321** [ytdl-org/youtube-dl#24356]
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've searched the bugtracker for similar feature requests including closed ones

- [x] **I have read the FAQ - _thoroughly_**

## Description

@dstftw , I am sorry, but please, I would appreciate if you leave the request open long enough so I can clarify if it is not understood. The answer you wrote before closing did not answer the request, unfortunately.

- I am aware of -a, or --batch-file
- I have read the FAQ carefully, and am aware of the options presented there.

--batch-file points to a text file, and allows the user to write **specific urls** to download there. ytsearch, an "arbitrary string search query" as you explained, can allow youtube searches to take place, and youtube-dl to perform actions on the result. For example:

- ytsearchall:Piano
or
- ytsearchdate900:Dance

"Piano" and "Dance" are what I refer to as keywords - paste them after the ytsearch, and it allows a search query to be performed for them.

I am asking if it is possible to use a list of search queries to be passed to ytsearch, _similar_ to how --batch-file allows a list of URL's. Here is what an example of the list would look like -

- piano
- Dance
- Kowloon city
- laser beam

Notice that these are not URL's, **and as such will not work with --batch-file**. The goal is for youtube-dl to iterate through the list of keywords, performing a search for each of them. To first add ytsearch:piano, then, after those results are done, ytsearch:Dance, and so forth.

**Comment by dstftw** [comment]
I've already pointed out: **use batch file**. If you don't want to prefix each with search extractor prefix use also `--default-search`.

**Comment by kolt54321** [comment]
I am sorry - I see what you mean now, thank you. I wasn't aware that batch file can take anything other than URL's. Thanks for your help!
