### ISSUE TITLE
Add native cookies support with drop-in existing code

### ISSUE THREAD

**Issue by michealespinola** [ytdl-org/youtube-dl#24362]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

With recent issues regarding cookies support compliance issues with the wide variety of tools people are using, I thought it might be prudent to look into native cookies extraction.  Hopefully fewer problems for users, and fewer support requests for devs that have more important things to do!  To make it easier I looked for already completed code that should be able to drop-in supplement youtube and found browser-cookie3 which supports chrome and firefox on Linux, OSX, and Windows:

* https://pypi.org/project/browser-cookie3/0.6.0/
* https://github.com/borisbabic/browser_cookie3

Thank you for your hard work and your consideration.  I only hope that something like this can make everyone's life easier in the long run.

**Comment by dstftw** [comment]
>* ***Which browsers are supported?*** Currently Chrome and Firefox.
