### ISSUE TITLE
How to config .netrc with multiple Youtube channels linked to the same Google account

### ISSUE THREAD

**Issue by WoodpeckerBaby** [ytdl-org/youtube-dl#24369]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bug tracker for similar questions including closed ones

# How to config .netrc with multiple Youtube channels linked to one Google account.
-u, -p --> goes to the account, but what if there are more than one Youtube Channels attached to the Google Account? For example, one personal/main channel, one branded channel as a creator, possibly shared with collaborating administrators and staff. 

How do we specify which one youtube-dl will target?

**Comment by dstftw** [comment]
You can't specify that.

**Comment by WoodpeckerBaby** [comment]
@dstftw For everyone looking at this in the future. Read the manual for authenticating with Cookies, that fixed it perfectly.
