### ISSUE TITLE
subtitle from MPD with video and audio protected

### ISSUE THREAD

**Issue by X-C0DE** [ytdl-org/youtube-dl#24375]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi guys
is it possible for me to get fragmented subtitles from an MPD file? I have a mpd with audio and video protected by DRM, but in that same MPD I also have a subtitle, and my interest is only in the subtitle. I already tried youtube-dl "URL" --list-subs, but no subtitles are found

is it possible to do this in any way? to make youtube-dl capture these subtitles when reading MPD?

**Comment by dstftw** [comment]
Currently not possible.

**Comment by X-C0DE** [comment]
but is it not possible to apply an update to add this feature?
