### ISSUE TITLE
-t, --title is missing from README

### ISSUE THREAD

**Issue by stdedos** [ytdl-org/youtube-dl#24377]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.03.08**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Description

Searching `--title` (and I would assume also `-t,`) returns only one result on `origin/master` at-this-time (i.e. https://github.com/ytdl-org/youtube-dl/blob/ea782aca520ff17fbf32771bfcfd9cbd36123900/README.md#L774), and nothing on https://github.com/ytdl-org/youtube-dl/blob/ea782aca520ff17fbf32771bfcfd9cbd36123900/README.md#options pseudo-man-page

**Comment by dstftw** [comment]
It's deprecated.

**Comment by stdedos** [comment]
Well, maybe referencing `-t` at least twice in the README should be deprecated too (or marked as deprecated)?

It is annoying to search for an argument referenced in a "recently updated" page that does not exist in usage pages (and not at all).
