### ISSUE TITLE
When using --download-archive, if a playlist is updated/changed, what will be the behaviour?

### ISSUE THREAD

**Issue by WoodpeckerBaby** [ytdl-org/youtube-dl#24403]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

### When using --download-archive, if a playlist is updated/changed, what will be the behaviour?

1. Will it check the playlist and update the archive.txt accordingly?
2. What if a video is removed or set to private now?
3. What if videos are rearranged in a playlist?
4. What if videos are added in the end or in between?
5. What if the playlist is removed or renamed?
6. What if there are duplicate videos in the playlist?
7. What if a channel playlist contains videos that are included in multiple created playlists?
8. What if a playlist contains a live stream and in different states? (placeholder, streaming, offline, replay pending, replay, or replay format/version updated, etc)
9. What if a new thumbnail is available?
10. What if there are new subtitles available that may match?

**Comment by dstftw** [comment]
All entries of a playlist with ids missing from download archive file will be processed according to provided command line. All entries with ids presented in download archive file will be skipped completely.
