### ISSUE TITLE
Grand sumo highlights

### ISSUE THREAD

**Issue by LoZio** [ytdl-org/youtube-dl#24409]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www3.nhk.or.jp/nhkworld/en/tv/sumo/tournament/202003/day1.html
- Single video: https://www3.nhk.or.jp/nhkworld/en/tv/sumo/tournament/202003/day2.html
- Playlist: not a playlist, a page with links to all days (one video per day): https://www3.nhk.or.jp/nhkworld/en/tv/sumo/

## Description

Each day a digest of the day is posted in a separate page.
The tournament lasts 15 days.
They are removed after some days the tournament ends, so if you do not have time to see each day video you will loose it forever.

For day1 example above the final source is: https://nhkw-mzvod.akamaized.net/www60/mz-nhk10/_definst_/mp4:mm/flvmedia/5905/v/t/n/vtnip923_vkr31138_h264_664K.mp4/chunklist.m3u8

Found using Chrome debug features. The video player is in an IFRAME in the page, in this case the frame source is https://www3.nhk.or.jp/nhkworld/common/player/tv/vod/?lang=en&autoplay=true&movie=true&wmode=transparent&ver=19&id=p-bout__vod&key=nw_vod_v_en_2061_331_20200309013000_01_1583687034

**Comment by fearlesschicken** [comment]
Instead of using the urls for day1-15, use the urls from the ondemand portal instead.  For example, the May tourney (day 1) going on right now:
Instead of using https://www3.nhk.or.jp/nhkworld/en/tv/sumo/tournament/202105/day1.html
Use this instead and youtube-dl can parse it: https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2061421/

**Comment by LoZio** [comment]
> Instead of using the urls for day1-15, use the urls from the ondemand portal instead. For example, the May tourney (day 1) going on right now:
> Instead of using https://www3.nhk.or.jp/nhkworld/en/tv/sumo/tournament/202105/day1.html
> Use this instead and youtube-dl can parse it: https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2061421/

Thank you very much @fearlesschicken .
