### ISSUE TITLE
Pornhub Premium download isn't working

### ISSUE THREAD

**Issue by mariuslooks4answers** [ytdl-org/youtube-dl#24412]
Hi everybody, I've already seen a few post on that problem but they have been closed to quickly and the answers brought weren't enough to download Pornhub Premium videos with a free trial.

Here's what I've done with the latest version of youtube-dl, of course, the --cookies part seems to run correctly.
`sudo youtube-dl --verbose --cookies /cookies.txt  https://fr.pornhubpremium.com/view_video.php?viewkey=ph5d535e21ab059
[sudo] Mot de passe de sessionsecondaire : 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--cookies', u'/cookies.txt', u'https://fr.pornhubpremium.com/view_video.php?viewkey=ph5d535e21ab059']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-91-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[PornHub] ph5d535e21ab059: Downloading pc webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 206, in _real_extract
    webpage, 'title', group='title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

Already tried with --username and --password too, if anybody has a clue !

Thanks you very much

**Comment by amandatv** [comment]
Just a quick note about the account-needed: PornHub premium is offering (at least in SPAIN) 1month for free son you can easily setup an account for free ;-)
