### ISSUE TITLE
[bilibili]can't download for new format

### ISSUE THREAD

**Issue by kesdoputr** [ytdl-org/youtube-dl#24439]
Bilibili seems change it's video number format
The two url direct to same video
https://www.bilibili.com/video/av98307847
https://www.bilibili.com/video/BV1JE411F741

youtube-dl can't download the second link with BV start

> C:\Users\k7\Desktop>youtube-dl -F https://www.bilibili.com/video/BV1JE411F741
> [generic] BV1JE411F741: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] BV1JE411F741: Downloading webpage
> [generic] BV1JE411F741: Extracting information
> WARNING: [generic] BV1JE411F741: Failed to parse JSON Invalid control character
> at: line 1 column 106 (char 105)
> ERROR: Unsupported URL: https://www.bilibili.com/video/BV1JE411F741
> 
> C:\Users\k7\Desktop>youtube-dl -F https://www.bilibili.com/video/av98307847
> [BiliBili] 98307847: Downloading webpage
> [BiliBili] 98307847: Downloading video info page
> [info] Available formats for 98307847:
> format code  extension  resolution note
> 0            flv        unknown    2.21GiB

**Comment by zhz1237ok** [comment]
eventually av-xxxxxxxx will gone

**Comment by mwx2006** [comment]
```
_VALID_URL = r'https?://(?:www\.|bangumi\.|)bilibili\.(?:tv|com)/(?:video/av|anime/(?P<anime_id>\d+)/play#)(?P<id>\d+)'
```
```
_VALID_URL = r'https?://(?:www\.|bangumi\.|)bilibili\.(?:tv|com)/(?:video/BV|anime/(?P<anime_id>\d+)/play#)(?P<id>\d+)'
```

**Comment by GrayXu** [comment]
share an AV<->BV transformation method from [mcfx Zhihu](https://www.zhihu.com/question/381784377/answer/1099438784)

```
table='fZodR9XQDSUm21yCkr6zBqiveYah8bt4xsWpHnJE7jL5VG3guMTKNPAwcF'
tr={}
for i in range(58):
	tr[table[i]]=i
s=[11,10,3,8,4,6,2,9,5,7]
xor=177451812
add=100618342136696320

def dec(x):
	r=0
	for i in range(10):
		r+=tr[x[s[i]]]*58**i
	return (r-add)^xor

def enc(x):
	x=(x^xor)+add
	r=list('BV          ')
	for i in range(10):
		r[s[i]]=table[x//58**i%58]
	return ''.join(r)

print(dec('BV17x411w7KC'))
print(dec('BV1Q541167Qg'))
print(dec('BV1mK4y1C7Bz'))
print(enc(170001))
print(enc(455017605))
print(enc(882584971))
```

**Comment by zhz1237ok** [comment]
> share an AV<->BV transformation method from [mcfx Zhihu](https://www.zhihu.com/question/381784377/answer/1099438784)
> 
> ```
> table='fZodR9XQDSUm21yCkr6zBqiveYah8bt4xsWpHnJE7jL5VG3guMTKNPAwcF'
> tr={}
> for i in range(58):
> 	tr[table[i]]=i
> s=[11,10,3,8,4,6,2,9,5,7]
> xor=177451812
> add=100618342136696320
> 
> def dec(x):
> 	r=0
> 	for i in range(10):
> 		r+=tr[x[s[i]]]*58**i
> 	return (r-add)^xor
> 
> def enc(x):
> 	x=(x^xor)+add
> 	r=list('BV          ')
> 	for i in range(10):
> 		r[s[i]]=table[x//58**i%58]
> 	return ''.join(r)
> 
> print(dec('BV17x411w7KC'))
> print(dec('BV1Q541167Qg'))
> print(dec('BV1mK4y1C7Bz'))
> print(enc(170001))
> print(enc(455017605))
> print(enc(882584971))
> ```

no, it's not a universal solution, it only works when av number <  2^30
