### ISSUE TITLE
HTTP Error 400: Bad Request - when logging into YouTube

### ISSUE THREAD

**Issue by asoretmadolell** [ytdl-org/youtube-dl#24437]
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['--ignore-errors', '--no-mark-watched', '--yes-playlist', '--download-archive', 'download-archive.txt', '--keep-fragments', '--batch-file', 'batch-file.txt', '--output', 'output.txt', '--no-overwrites', '--no-continue', '--write-description', '--write-info-json', '--write-annotations', '--write-thumbnail', '--write-all-thumbnails', '--verbose', '--write-sub', '--write-auto-sub', '--all-subs', '--username', 'PRIVATE']
[debug] Command-line args: ['--config-location', 'youtube-dl.conf']
[debug] Batch file urls: ['https://www.youtube.com/playlist?list=PLeqIyfZm7ehqfwe_u4LlrdmbVoUZ5y_gg']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Looking up account info
[youtube:playlist] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube:playlist] PLeqIyfZm7ehqfwe_u4LlrdmbVoUZ5y_gg: Downloading webpage
ERROR: This playlist is private, use --username or --netrc to access it.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\youtube.py", line 2762, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp378onz6j\build\youtube_dl\extractor\youtube.py", line 2685, in _extract_playlist
youtube_dl.utils.ExtractorError: This playlist is private, use --username or --netrc to access it.
```

## Description

I'm trying to download a private playlist from my personal YouTube account. I've specified the username so that it prompts me for a password and after specifying it, it is unable to log in hence why the playlist still comes out as private. I've also tried putting the password in the CLI with no luck.

I don't think there's anything specifically wrong with my playlist. I think it happens with every private YouTube playlist.

This issue apparently appeared before, but I doubt there's any relation:
https://github.com/ytdl-org/youtube-dl/issues/12927

**Comment by asoretmadolell** [comment]
I don't understand. Like I said in my description, I did look at issue https://github.com/ytdl-org/youtube-dl/issues/12927 , but where is the fix there? I simply don't see it. All I see are "duplicate" and "closed" tags.
Thank you in advance.

**Comment by KJBurnett** [comment]
> 
> 
> I don't understand. Like I said in my description, I did look at issue #12927 , but where is the fix there? I simply don't see it. All I see are "duplicate" and "closed" tags.
> Thank you in advance.

Tacking onto this. There's just a rabbit hole of closed and related and duplicate issues. This seems to still be a legitimately existing issue.

https://github.com/ytdl-org/youtube-dl/issues/12927
https://github.com/ytdl-org/youtube-dl/issues/12993

![image](https://user-images.githubusercontent.com/9143189/78418381-71cbbd80-75f0-11ea-830a-7a74320efba1.png)

Cc @dstftw @asoretmadolell
