### ISSUE TITLE
365DataScience Program

### ISSUE THREAD

**Issue by welowis** [ytdl-org/youtube-dl#24443]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://365datascience.teachable.com/courses/361452/lectures/5638888
- Playlist: https://365datascience.teachable.com/courses/

## Description

This website alike udemy. It has many courses. People can register.

**Comment by dstftw** [comment]
Already supported.

**Comment by welowis** [comment]
Which extractor?

**Comment by ashishfeels** [comment]
@welowis were you able to download ?

**Comment by welowis** [comment]
@ashishfeels  I tried.Teachable extactor gave this result: [https://prntscr.com/rlmytf](url)

**Comment by ashishfeels** [comment]
@welowis i was able to download but its only downloading 5 videos use cookies.txt instead of username & password

**Comment by ashishfeels** [comment]
i dont know why its not downloading the entire playlist

**Comment by ashishfeels** [comment]
@dstftw i was able to download 5 videos only  that also it chooses randomly any way to fix this ?

**Comment by SwapnilSoni1999** [comment]
so anyone figured it out?

**Comment by SwapnilSoni1999** [comment]
it works with --add-header and copying cookies

**Comment by ashishfeels** [comment]
@SwapnilSoni1999 can you post the header format please

**Comment by SwapnilSoni1999** [comment]
visit the video page and copy cookies from Networks tab 
select cookies:  thing (with cookies keyword too) 
![image](https://user-images.githubusercontent.com/25403317/78072079-203aed00-73bc-11ea-8f8a-808408f38e45.png)

and use with `--add-header` flag to insert cookies and then just provide video url 
![image](https://user-images.githubusercontent.com/25403317/78072105-2c26af00-73bc-11ea-843e-847dc17c6c7a.png)

problem is it doesn't downloads properly once any pdf or file will come it will interrupt download with whole playlist so one by one downloading will be better option or just own py script to do

**Comment by ashishfeels** [comment]
Cool
