### ISSUE TITLE
New Site Support: Microsoft Stream

### ISSUE THREAD

**Issue by ideaman924** [ytdl-org/youtube-dl#24440]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.03.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://web.microsoftstream.com/video/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
- User page: https://web.microsoftstream.com/user/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
- Channel page: https://web.microsoftstream.com/channel/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

## Description

Microsoft Stream is a video streaming service for Office 365/SharePoint users. The videos are behind a login wall, but once logged in the videos seem to be HLS content. Supplying the cookie ID and token seems to be enough to download the video contents, as seen in this project: https://github.com/snobu/destreamer

**Comment by remitamine** [comment]
```
You can't sign in here with a personal account.
Use your work or school account instead.
```
