### ISSUE TITLE
Support for BroadwayHD

### ISSUE THREAD

**Issue by SplinterHead** [ytdl-org/youtube-dl#24454]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.broadwayhd.com/movies/AW72g2Cx-LB9wKsiI5qU/play

## Description

I would like to get some films off of broadwayHD to add to my media center so I don't have to watch in a browser.
This is a subscription service, but there is a free trial available currently on the website.

I tried with the existing extractors, but the generic one does not work

```
youtube-dl https://www.broadwayhd.com/movies/AW72g2Cx-LB9wKsiI5qU/play -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.broadwayhd.com/movies/AW72g2Cx-LB9wKsiI5qU/play', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] play: Requesting header
WARNING: Could not send HEAD request to https://www.broadwayhd.com/movies/AW72g2Cx-LB9wKsiI5qU/play: HTTP Error 500: Internal Server Error
[generic] play: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by h3lo** [comment]
I know this is closed @remitamine  but can you explain why? I see the tag DRM is added. Does that mean there is some technical reason related to DRM which makes ripping not possible?

I am a paying user of BroadwayHD, but their site and player are pretty lousy. They don't have an app for my TV (AndroidTV), so I have to watch by plugging my laptop into the TV and cloning my display. It results in a fairly poor experience overall. I would really like to be able to download the video and play them directly with kodi or plex on my TV.

**Comment by remitamine** [comment]
> Does that mean there is some technical reason related to DRM which makes ripping not possible?

yes, there is.
