### ISSUE TITLE
add --skip-watched feature

### ISSUE THREAD

**Issue by luggs-co** [ytdl-org/youtube-dl#24467]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

There is --mark-watched parameter, but I would love to have a --skip-watched as when a channel updates with new videos, I don't want it to re-download ones already obtained previously and flagged as watched.

**Comment by dstftw** [comment]
Use `--download-archive`.
