### ISSUE TITLE
Viafree.no not working in 1080p

### ISSUE THREAD

**Issue by tommyvange** [ytdl-org/youtube-dl#24473]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.03.24**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo[height=1080]+bestaudio', '--merge-output-format', 'mkv', '--prefer-ffmpeg', '--ffmpeg-location', 'C:\\Users\\Tommy Vange\\Documents\\YouTube DL\\ffmpeg.exe', '--cookies', 'C:\\Users\\Tommy Vange\\Documents\\YouTube DL\\cookies.txt', '--all-subs', '--write-sub', '--embed-subs', 'https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-11/episode-1']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2
[debug] Proxy map: {}
[Viafree] episode-1: Downloading webpage
[debug] Using fake IP 84.213.10.54 (NO) as X-Forwarded-For.
[mtg] 991993: Downloading video JSON
[mtg] 991993: Downloading streams JSON
[mtg] 991993: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 863, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 1636, in process_video_result
youtube_dl.utils.ExtractorError: requested format not available
```

## Description

When I try to download videos from **viafree.no** it only shows a maximum quality of 720p, but I know that video is available in 1080p. If I use a chrome video downloader extension, it works shows the 1080p version, but it is extremely tedious to download it from chrome and add the audio later when I could have youtube-dl do it for me.

It works fine if I choose 720p as the quality but when using 1080p it says that the format is not available.

**Comment by r2dr0dn** [comment]
As Some Other Sites , Downloading At 1080p Requires Authentication (Or Premium Subscription).
In case u have valid credentials or premium access , please supply username and password flags .

**Comment by tommyvange** [comment]
> As Some Other Sites , Downloading At 1080p Requires Authentication (Or Premium Subscription).
> In case u have valid credentials or premium access , please supply username and password flags .

I included cookies from the site, isn't that sufficient?

**Comment by vittrup88** [comment]
Can you tell me which chrome extension you are using ? I will try look at ydl implementation.

**Comment by nielsrune** [comment]
The 1080p is available if using another host for info:
`'https://viafree.mtg-api.com/stream-links/viafree/web/%s/clear-media-guids/%s/streams'
                    % (country, video['mpx_guid'])`

However, the audio is separated from videos, so it is necessary to use the `-f` flag. It had been working on a solution, but when I asked for help, the response was useless. Nevertheless, someone more skillful may be able to solve this with the hint of the above host.
