### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by DankMemeGuy** [ytdl-org/youtube-dl#24476]
https://github.com/ytdl-org/youtube-dl/issues/4816 works, BUT

How do I out this into the settings so I don't have to keep using that command of "--no-check-certificate"

**Comment by HussainMustafa** [comment]
By default for any communication from a server to/from client first validates by a SSL certificate. In youtube-dl provides a command line argument to skip it. If you dont want to use that command you may try to use some third party plugin which enables certificate checking avoiding. below is a similar tool.
**https://plugins.jenkins.io/skip-certificate-check/**
I think it will help you. But avoiding certificate checking might harm your security check.

**Comment by dstftw** [comment]
You should fix your SSL setup and not skip certificates completely if you even care about security. If don't - put it in config file.
