### ISSUE TITLE
[Screencast-o-matic] `ERROR: Unable to extract setup code; please report this issue`

### ISSUE THREAD

**Issue by owlboy** [ytdl-org/youtube-dl#24489]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.03.24**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

**NOTE:** #23512 has different verbose output. And does not even identify as attempting to use the Screencast-o-matic module. It appears that the person is attempting to download a "channel" or a "playlist." That might not be supported, period. This issue is about downloading a single video.

## Verbose log

```
$ youtube-dl -f best -v https://screencast-o-matic.com/watch/cqi6qjO2GF
[debug] System config: [u'-f', u'bestvideo+bestaudio']
[debug] User config: [u'-f', u'bestvideo[ext=mp4, height<=1100]+bestaudio', u'--write-thumbnail', u'--restrict-filenames']
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'best', u'-v', u'https://screencast-o-matic.com/watch/cqi6qjO2GF']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.17 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[ScreencastOMatic] cqi6qjO2GF: Downloading webpage
ERROR: Unable to extract setup code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/screencastomatic.py", line 29, in _real_extract
    r"(?s)jwplayer\('mp4Player'\).setup\((\{.*?\})\);", webpage, 'setup code'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract setup code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I tried to use this on a Screencast-o-Matic video and youtube-dl told me to report here that it does not work.

I also tried passing youtube-dl just the iFrame URL that the video is in.

**Comment by motorsalad** [comment]
Same (similar ?) issue here on passworded content using 2021.04.01:

`
glider:Desktop phil$ youtube-dl https://screencast-o-matic.com/watch/crew2OVVJbL --video-password XXXXXXX --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://screencast-o-matic.com/watch/crew2OVVJbL', u'--video-password', u'PRIVATE', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[ScreencastOMatic] crew2OVVJbL: Downloading webpage
ERROR: Unable to extract setup code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/screencastomatic.py", line 29, in _real_extract
    r"(?s)jwplayer\('mp4Player'\).setup\((\{.*?\})\);", webpage, 'setup code'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract setup code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

Thanks for all this work anyway :-).
