### ISSUE TITLE
pornhub's broken.

### ISSUE THREAD

**Issue by LPW00** [ytdl-org/youtube-dl#24494]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE 
youtube-dl -f bestvideo+bestaudio "https://www.pornhub.com/view_video.php\?viewkey\=ph5e725dac85209" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo+bestaudio', 'https://www.pornhub.com/view_video.php\\?viewkey\\=ph5e725dac85209', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Linux-5.5.11-zen1-1-zen-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[PornHubPagedVideoList] view_video.php\: Downloading page 1
[download] Downloading playlist: view_video.php\
[PornHubPagedVideoList] playlist view_video.php\: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: view_video.php\

```

## Description

WRITE DESCRIPTION HERE
Uh, hey, pornhub downloads seem to have been broken for a while now. I was really hoping someone else would report this, but here we are. I obviously tried it with multiple videos from different uploaders for testing purposes. Every time the same error. idk is it trying to download a playlist and there isn't one? i don't understand the output.

The link should go to the pixel squirt podcast, which is freely available without pornhub premium nor pornhub account. (dear parents/future employers/friends who might stumble across this, it's just a podcast, don't judge me!)

I'm supposed to provide suggested solution? uh... fixing it? (that reads disrespectful, doesn't it? it's not meant that way, i was just amused by the idea that someone would ask me how to fix shit, i just brick stuff) 

thx in advance

**Comment by dstftw** [comment]
You either quote URL or escape special characters not both at the same time.

**Comment by LPW00** [comment]
wow, this was super fast and while i do not know what "escaping special characters" even means, removing the quotes does the job. It also fixes that issue that i was unable to download from youtube.com, just from youtu.be. Nice!

Can i ask a short question? How can -f bestvideo+bestaudio return "ERROR: requested format not available" doesn't it literally mean that it checks for the best _available?_ it's not set up to exclude or enforce any codec or something.... I'd open a new issue but this one is 100% also just caused by me being an idiot.
