### ISSUE TITLE
Impossible to download video anymore, maybe because of the User config?

### ISSUE THREAD

**Issue by Puzzleworld** [ytdl-org/youtube-dl#24492]
- [] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

[debug] System config: []
[debug] User config: ['-o', '~/Downloads/%(title)s-%(id)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=9A-HLSvtBWc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.3 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[youtube] 9A-HLSvtBWc: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r3---sn-n4g-jqbed.googlevideo.com/videoplayback?expire=1585293574&ei=pVR9XsirPP2rmLAPi9-tqAE&ip=89.156.29.120&id=o-AIh3-wchxpLK2KPflhWrDG-ktv9WDgR7lmlmBwt9JNkH&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=3b&mm=31%2C26&mn=sn-n4g-jqbed%2Csn-5hnekn7d&ms=au%2Conr&mv=m&mvi=2&pl=21&initcwndbps=1603750&vprv=1&mime=video%2Fwebm&gir=yes&clen=68271975&dur=654.667&lmt=1545842077364755&mt=1585271910&fvip=3&keepalive=yes&fexp=23882514&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ADKhkGMwRQIhAOR7GV-8me7jF-1JG3eabPz9XyZudMw7mxt9wtFWXgvwAiAs2mgbx1vgb66Hj0N3gl5QlnFxSetUIvPVfEa4M69hFQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRQIgGi8_0j1WYz4GN8QObmhAOEgM4rTblFxb6hLVm41nS-QCIQC1NLeYoE6y3t1tM2z2pAgtjeA0vy-hSQPB2E_q_sCqlA%3D%3D&ratebypass=yes'
[download] Destination: /Users/Helene/Downloads/Downloading Videos, Music and More with Youtube DL-9A-HLSvtBWc.f248.webm
[download] 100% of 65.11MiB in 00:06
[debug] Invoking downloader on 'https://r3---sn-n4g-jqbed.googlevideo.com/videoplayback?expire=1585293574&ei=pVR9XsirPP2rmLAPi9-tqAE&ip=89.156.29.120&id=o-AIh3-wchxpLK2KPflhWrDG-ktv9WDgR7lmlmBwt9JNkH&itag=140&source=youtube&requiressl=yes&mh=3b&mm=31%2C26&mn=sn-n4g-jqbed%2Csn-5hnekn7d&ms=au%2Conr&mv=m&mvi=2&pl=21&initcwndbps=1603750&vprv=1&mime=audio%2Fmp4&gir=yes&clen=10598567&dur=654.825&lmt=1545841006294906&mt=1585271910&fvip=3&keepalive=yes&fexp=23882514&c=WEB&txp=5533432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ADKhkGMwRQIgDufpyNiuIRTWzQCirCNFHH-ShAXWRgz415XDNd0_RNMCIQDAK5j36a4F1y-l5m-FdLNVF30qTfWiAiWS50RC0KBDVQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRQIgGi8_0j1WYz4GN8QObmhAOEgM4rTblFxb6hLVm41nS-QCIQC1NLeYoE6y3t1tM2z2pAgtjeA0vy-hSQPB2E_q_sCqlA%3D%3D&ratebypass=yes'
[download] Destination: /Users/Helene/Downloads/Downloading Videos, Music and More with Youtube DL-9A-HLSvtBWc.f140.m4a
[download] 100% of 10.11MiB in 00:01
[ffmpeg] Merging formats into "/Users/Helene/Downloads/Downloading Videos, Music and More with Youtube DL-9A-HLSvtBWc.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Users/Helene/Downloads/Downloading Videos, Music and More with Youtube DL-9A-HLSvtBWc.f248.webm' -i 'file:/Users/Helene/Downloads/Downloading Videos, Music and More with Youtube DL-9A-HLSvtBWc.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:/Users/Helene/Downloads/Downloading Videos, Music and More with Youtube DL-9A-HLSvtBWc.temp.mkv'
Deleting original file /Users/Helene/Downloads/Downloading Videos, Music and More with Youtube DL-9A-HLSvtBWc.f248.webm (pass -k to keep)
Deleting original file /Users/Helene/Downloads/Downloading Videos, Music and More with Youtube DL-9A-HLSvtBWc.f140.m4a (pass -k to keep)

## Description

I think I have done something wrong with the configuration, I cannot have video anymore, actually I don't really know where the problem comes from. At the beginning, it was working well, but then I tried to configure a default download path but after that I cannot download video as before. I tried to reset all the configuration by pip uninstall then pip install but same problem. Really don't know how to remove the user configuration part: [debug] User config: ['-o', '~/Downloads/%(title)s-%(id)s.%(ext)s'], and to fix the problem.

Thank you very much for your help!

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#configuration
