### ISSUE TITLE
bestavideo+bestaudio is not available?

### ISSUE THREAD

**Issue by LPW00** [ytdl-org/youtube-dl#24501]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How can -f bestvideo+bestaudio return "ERROR: requested format not available" doesn't it literally mean that it checks for the best _available?_ it's not set up to exclude or enforce any codec or something, at least not by me. And is it even useful still? Isn't that the default setting anyways?

**Comment by Hrxn** [comment]
`bestvideo` and `bestaudio` are indeed for best available formats, delivered streams (like DASH etc.) and may actually not always be available.

So it definitely can return `"ERROR: requested format not available"`

And the default is basically `bestvideo+bestaudio/best`, which means it will fallback to `best` in such a case.

**Comment by LPW00** [comment]
> `bestvideo` and `bestaudio` are indeed for best available formats, delivered as separate streams (like DASH etc.) and may actually not always be available.
> 
> So it definitely can return `"ERROR: requested format not available"`
> 
> And the default is basically `bestvideo+bestaudio/best`, which means it will fallback to `best` in such a case.

That makes sense thx.
