### ISSUE TITLE
api.vhx.tv embed.vhx.tv

### ISSUE THREAD

**Issue by jdesl** [ytdl-org/youtube-dl#24500]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Hi,

I'm trying to download a video from a website I payed for. Tried header,referer, cookie, different URL combinations. But maybe it just doesn't work with youtube-dl or maybe i'm missing something obvious? Anyone give me some tips/pointers? 

Thank you!

youtube-dl.exe -v https://embed.vhx.tv/videos/445362 -referer "https://tomovhxtv.vhx.tv/videos/tf-lesson-002/"

--add-header referrer:"https://tomovhxtv.vhx.tv/browse&sharing=1&title=0&vimeo=1"

--cookie cookie.txt

[vhx:embed] 445362: Downloading webpage
ERROR: Unable to extract ott data;

---------

https://embed.vhx.tv/videos/737843?api=1&autoplay=1&back=Music%20Theory%20I&color=22b9b0&context=https%3A%2F%2Ftomovhxtv.vhx.tv%2Fmusic-theory-i&live=0&playsinline=1&referrer=https%3A%2F%2Ftomovhxtv.vhx.tv%2Fbrowse&sharing=1&title=0&vimeo=1

---------------------------

The above URL contains the following info:

  window.OTTData = {"api_data":{"api_host":"https://api.vhx.tv","api_token":"7d3ec910f0cf6ba64565444e54cb0cb9a2d37e3724d871e10556acc7d18","user_auth_token":{"session":"BAh7DEkiD3Nlc3Npb65454665454546iNWMwNjM3ZWY4MGNjNTdhNzYxMGZhBjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMXo2WE90dWxxZFFSeisvYVlvVzNLUEhNYmxkblRiYlBaYW5JSjdMV1o1T1E9BjsARkkiHHdhcmRlbi51c2VyLmRlZmF1bHQua2V5BjsAVGkDg/rhSSILYXV0aGVkBjsARlRJIg9leHBpcmVzX2F0BjsARmwrB96apV5JIgx2ZXJzaW9uBjsARmkGSSIVaW52YWxpZGF0aW9uX2tleQY7AEZJIik1OGEwOWI1Yy1mM2YwLTRhNGYtYTgwMS0wMDRhYzc0OTIwMzQGOwBG--10e814a7d0e439f4b3456b8c4a732a200d4"}},"buy_button":{"label":null,"url":null},"product":{"id":null},"redirect_button":{"label":"Music Theory I","url":"https://tomovhxtv.vhx.tv/music-theory-i"},"site":{"id":67785,"subdomain":"tomovhxtv","twitter_name":"backbaymusic"},"video":{"duration":728,"id":737843,"title":"Theory 04 D Major D Dorian","url":"https://tomovhxtv.vhx.tv/videos/theory-04-d-major-d-dorian"},"config_url":"https://player.vimeo.com/video/392961580/config?autoplay=1\u0026color=22b9b0\u0026token=eyJhbG45645564jE1ODUzMjMwMjcsImV4cCI6MTU4NTMyMzA4NywiY2xpcF9pZCI6MzkyOTYxNTgwLCJkcm0iOmZhbHNlfQ.bEBGpXZp4WqpKbg9zMtXC-nIvP-idV8zYxM4ASKIACg","hide_chrome":null,"initial_time":null,"js_api_enabled":true,"show_share_actions":true,"user_id":12345645}

There is also part for mobile?

  var environment = "production",
      config = {
        autoplay: false,
        debug: false,
        nativeControlsForTouch: navigator.userAgent.toLowerCase().indexOf('android') !== -1,
        credentials: {
          authorization: null,
          ticket: null,
          access_token: "09b7ac239135464564456455465471bdf48284dc3",
          authUserToken: undefined,
        },
        source: {
          href: "https://api.vhx.tv/videos/737843",
          country: "US",
          referrer: undefined
        },

**Comment by jdesl** [comment]
seems it should work
https://git.azlux.fr/Azlux/youtube-dl/commit/ca01d178844129bd4b6ed74740fbd30e7f84c1c2

**Comment by jdesl** [comment]
So much easier with the source code!

youtube-dl.exe -v https://embed.vhx.tv/videos/737843?vimeo=1 --cookies cookies.txt

"window.OTTData" is only in the html code when you add "?vimeo=1"
you need cookie.txt for the login.

Works, thanks for the great tool!

**Comment by afeef-pv** [comment]
how to specify quality?

**Comment by h4mp3l** [comment]
Hi, I am trying to get the same "sources" you downloaded. I also subscribed...
Can you tell me how exactly you did it? It has problems requesting header and the site does not reply...
