### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa8 in position 93: ordinal not in range(128)

### ISSUE THREAD

**Issue by silverhikari** [ytdl-org/youtube-dl#24516]
## Checklist

- [ x] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.03.24**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--prefer-ffmpeg', u'--ffmpeg-location', u'/usr/bin/ffmpeg', u'--encoding', u'UTF-8', u'-x', u'-f', u'bestaudio', u'--audio-quality', u'0', u'--verbose', u'https://soundcloud.com/silver-adventures-ethan-kerrick/sets/music/s-E4L65']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-42-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2
[debug] Proxy map: {}
[soundcloud:set] silver-adventures-ethan-kerrick/sets/music/s-E4L65: Downloading JSON metadata
[soundcloud:set] 339405072: Downloading tracks
[download] Downloading playlist: music
[soundcloud:set] playlist music: Collected 67 video ids (downloading 67 of them)
[download] Downloading video 1 of 67
[soundcloud] yenle/sha-la-la-ayakashi-night: Downloading info JSON
[soundcloud] 39086316: Downloading JSON metadata
[soundcloud] 39086316: Downloading JSON metadata
[soundcloud] 39086316: Downloading JSON metadata
[debug] Invoking downloader on u'https://cf-media.sndcdn.com/b32sutoxViYD.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vYjMyc3V0b3hWaVlELjEyOC5tcDMiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1ODU0MTMwMTZ9fX1dfQ__&Signature=K~uLFMitxENpSgx6ueA3uKduk-m288LuG~btOrJcn8Ou1pIxEFrJ1URjOZGCg70FE4HfK5i8fzXjAnxnJx~PJGgGaZ11IOIYUOoiIfVbX0dWmLn0ZQdV0~njUgpfw67~QTVOqj0ZxFz0o~WhYAHwyHYVpfUl1zPX8x8SzW1eMLThUSlT1GqufQWb6itzm0AHpKtiySbT0NwehnxSG9~nLcIBfGpbKBKBsObtV~V5E8yqGEe4ZQb46cgFlaPMCqUvkVZlNZt1M8W4zototRnh4ydJb-LDumF0EMfP9zIk~4rXlTtRMNuMBncIEnLOZAS0R2cijPIAsBVz8XCHtvv7JQ__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ'
[download] Sha La La - Ayakashi Night Kekkaishi OP - Uura Saeka-39086316.mp3 has already been downloaded
[download] 100% of 2.53MiB
[debug] ffmpeg command line: /usr/bin/ffprobe -show_streams 'file:Sha La La - Ayakashi Night Kekkaishi OP - Uura Saeka-39086316.mp3'
[ffmpeg] Post-process file Sha La La - Ayakashi Night Kekkaishi OP - Uura Saeka-39086316.mp3 exists, skipping
[download] Downloading video 2 of 67
[soundcloud] mahiro-guitar/perfect-area-complete-4: Downloading info JSON
[soundcloud] 144458871: Downloading JSON metadata
[soundcloud] 144458871: Downloading JSON metadata
[soundcloud] 144458871: Downloading JSON metadata
[debug] Invoking downloader on u'https://cf-media.sndcdn.com/6Xtno6lC0Ekl.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vNlh0bm82bEMwRWtsLjEyOC5tcDMiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1ODU0MTMwOTF9fX1dfQ__&Signature=P4jZdy3DsYSMiFY915OHwU6TWEVyGeGQXTNzjxmaIEdQtXAuhOxuMTCabKtFi~AdNg1KikF2w1we~2uwdkMk4zqfI~2i10C5KMivitUwFuIAFdoyGPZGwY-l5sCeFACGuW3SI233jh8qyCL0loulVtnWaXrSMq~FRkA~xordA2hCeESV8a90uZzCQbL33LmWtFvl6Ha8eO5xiir8Dt5lXaY6kFX7GE4jlOFjV64AUu9gdJPQTw7-4zVd-Bwl5TybQthNoyiyFXDD0msL4u9-0BpKcywfjpGDOMjURp2Y9~W9Nyil7CIEs1MWNt-Qc8AjW5nYcRsATwAbJvLvznDXkg__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ'
[download] Perfect-area complete! _ 麻生夏子-144458871.mp3 has already been downloaded
[download] 100% of 3.67MiB
[debug] ffmpeg command line: /usr/bin/ffprobe -show_streams 'file:Perfect-area complete! _ 麻生夏子-144458871.mp3'
[ffmpeg] Post-process file Perfect-area complete! _ 麻生夏子-144458871.mp3 exists, skipping
[download] Downloading video 3 of 67
[soundcloud] shadowridrs/hakata-tonkotsu-ramens-op-stray-kishida-kyoudan-akeboshi-rocketstabs-guitar-cover: Downloading info JSON
[soundcloud] 397393212: Downloading JSON metadata
[soundcloud] 397393212: Downloading webpage
Traceback (most recent call last):
  File "/home/silver/.local/bin/youtube-dl", line 10, in <module>
    sys.exit(main())
  File "/home/silver/.local/lib/python2.7/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/home/silver/.local/lib/python2.7/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/silver/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/silver/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/silver/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1008, in process_ie_result
    extra_info=extra)
  File "/home/silver/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 870, in process_ie_result
    extra_info=extra_info)
  File "/home/silver/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/silver/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/silver/.local/lib/python2.7/site-packages/youtube_dl/extractor/soundcloud.py", line 480, in _real_extract
    return self._extract_info_dict(info, full_title, token)
  File "/home/silver/.local/lib/python2.7/site-packages/youtube_dl/extractor/soundcloud.py", line 335, in _extract_info_dict
    'ext': urlhandle_detect_ext(urlh) or 'mp3',
  File "/home/silver/.local/lib/python2.7/site-packages/youtube_dl/utils.py", line 4164, in urlhandle_detect_ext
    e = determine_ext(m.group('filename'), default_ext=None)
  File "/home/silver/.local/lib/python2.7/site-packages/youtube_dl/utils.py", line 2915, in determine_ext
    if url is None or '.' not in url:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa8 in position 93: ordinal not in range(128)

i have tried previous solutions by other issues such as doing prefer ffmpeg, setting the encoding to unicode-8, and doing
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8.
none of the previous solutions worked.

**Comment by anisse** [comment]
This is a common python2 issue. You might want to
export PYTHONIOENCODING=utf8

or just use python3.

**Comment by silverhikari** [comment]
switching to python 3 fixed it, thank you for the help
