### ISSUE TITLE
Subtitle URL 

### ISSUE THREAD

**Issue by marium0505** [ytdl-org/youtube-dl#24524]
## Checklist

- [x] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2020.03.24**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

Would be nice to be able to insert a subtitle URL manually when downloading a video. This is useful on videos that aren't on Youtube, but there are available subtitles, that can be merged into the end result similar to how it is done on YT. 

Just ask if you got any questions. Will do my best to explain/answer.

**Comment by remitamine** [comment]
simply post-process the resulting file with a tool that you prefer.

**Comment by marium0505** [comment]
> simply post-process the resulting file with a tool that you prefer.

Oh well. Alright,, thanks for the reply.
