### ISSUE TITLE
Download videos from likee.com

### ISSUE THREAD

**Issue by GetPHP-IR** [ytdl-org/youtube-dl#24533]
## Checklist

- [ ] I'm reporting a new site support request

## Example URLs

- Single video: https://likee.com/@Inayat95/video/6792552721999608595

## Description

please support download videos from likee.com

**Comment by sudarshan-parvatikar** [comment]
I'll take this!

**Comment by sudarshan-parvatikar** [comment]
The video can be downloaded using the generic extractor:
python youtube_dl/__main__.py --verbose https://likee.com/@Inayat95/video/6792552721999608595
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://likee.com/@Inayat95/video/6792552721999608595']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Git HEAD: 049c0486b
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-42-generic-x86_64-with-Zorin-15-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[generic] 6792552721999608595: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6792552721999608595: Downloading webpage
[generic] 6792552721999608595: Extracting information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://video.like.video/in_live/2nu/18WqFM_4.mp4?crc=361017319&type=5'
[download] Destination: Mr.Aayat🐰(Inayat95) on Likee Mobile - chand bhi h dewana tera😉 #BroomChallenge #WeeklyHighlights #HiLikee #VideoTalent @Likee Official -18WqFM_4.mp4
[download]  19.2% of 4.42MiB at 97.02KiB/s ETA 00:37^C

@dstftw , should I nevertheless implement an extractor?

**Comment by GetPHP-IR** [comment]
thanks my problem is with when add -j and in json the format id is not in fomats:
```json
{"id": "18WqFM_4", "uploader": "likee.com", "title": "Mr.Aayat\ud83d\udc30(Inayat95) on Likee Mobile: chand bhi h dewana tera\ud83d\ude09 #BroomChallenge #WeeklyHighlights #HiLikee #VideoTalent @Likee Official ", "age_limit": 0, "url": "https://video.like.video/in_live/2nu/18WqFM_4.mp4?crc=361017319&type=5", "extractor": "generic", "webpage_url": "https://likee.com/@Inayat95/video/6792552721999608595", "webpage_url_basename": "6792552721999608595", "extractor_key": "Generic", "playlist": null, "playlist_index": null, "display_id": "18WqFM_4", "requested_subtitles": null, "format_id": "0", "format": "0 - unknown", "ext": "mp4", "protocol": "https", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3723.0 Safari/537.36", "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Encoding": "gzip, deflate", "Accept-Language": "en-us,en;q=0.5"}, "fulltitle": "Mr.Aayat\ud83d\udc30(Inayat95) on Likee Mobile: chand bhi h dewana tera\ud83d\ude09 #BroomChallenge #WeeklyHighlights #HiLikee #VideoTalent @Likee Official ", "_filename": "Mr.Aayat\ud83d\udc30(Inayat95) on Likee Mobile - chand bhi h dewana tera\ud83d\ude09 #BroomChallenge #WeeklyHighlights #HiLikee #VideoTalent @Likee Official -18WqFM_4.mp4"}
```
so i found out later
