### ISSUE TITLE
feature request: batch-file to continue past errors

### ISSUE THREAD

**Issue by DreadPirateShawn** [ytdl-org/youtube-dl#24532]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Currently when using `--batch-file`, if any of the sources encounter an error, the remainder of the batch file will not be attempted.

This feature request is to allow `--batch-file` to continue attempting all sources, regardless of any errors encountered for any individual sources.

**Comment by dstftw** [comment]
Read FAQ?
```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
```

**Comment by DreadPirateShawn** [comment]
Yikes -- my apologies. I read the whole section surrounding `--batch-file`, didn't see it nearby. Should've grepped entirety for "error".
