### ISSUE TITLE
--flat-playlist

### ISSUE THREAD

**Issue by S4RX** [ytdl-org/youtube-dl#24545]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

--flat-playlist - this comand used for comand line, but how i can use it in my code?

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl/blob/049c0486bbd57a9bb5fb5a6a5eeff82fd4ac03ff/youtube_dl/YoutubeDL.py#L226-L228
