### ISSUE TITLE
Add support for pwa.zdf.de

### ISSUE THREAD

**Issue by luzeagithub** [ytdl-org/youtube-dl#24543]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Very dear team,

pwa.zdf.de is a progressive web app for zdf.de, but some content is only available on pwa.zdf.de.
Is there a possibility that you can add support for pwa.zdf.de?

Best regards
luzeagithub

**Comment by divadsn** [comment]
Could you provide some example links to test?
