### ISSUE TITLE
Is there a standard already in use to smuggle season/episode information around?

### ISSUE THREAD

**Issue by mshiels** [ytdl-org/youtube-dl#24568]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Basically I am trying to figure out how to get information down into say the brightcove code from the layers above it.  Basically the ACorntv.py which I am not sure even where I got it originally now.   But it just builds a brightcove url and I added i think the smuggling of extra infomration down to brightcover - but it's not really standard behaviour.  

SO I am hoping there is something I can examine/digest that does deal with this cleanly.  

                
                    entries.append(smuggle_url( 'http://players.brightcove.net/3047407010001/default_default/index.html?videoId=%s' % video_id[0],
                                                { 'title': title[0],
                                                  'episode_number': episode[0],
                                                  'series': series[0],
                                                  'season_number': season[0] } ))

anyone with info would be appreciated greatly!!

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl/blob/049c0486bbd57a9bb5fb5a6a5eeff82fd4ac03ff/youtube_dl/extractor/common.py#L357-L362

**Comment by mshiels** [comment]
thanks!  I'll dig and see what others have used that for, appreciate the help!!
