### ISSUE TITLE
Status hook for conversion

### ISSUE THREAD

**Issue by senihtosun** [ytdl-org/youtube-dl#24578]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, I was wondering if there is anyway I can check for the status of the conversion?
if ['status'] == 'finished'  is really nice for checking the download, but I could not find anything regarding the conversion. Thanks in advance!

**Comment by dstftw** [comment]
Currently, no.
