### ISSUE TITLE
South park downloading

### ISSUE THREAD

**Issue by NavnDK** [ytdl-org/youtube-dl#24571]
i would like to beable to download a hole season at once insted of manually downloading every episode
the command would look like this
youtube-dl https://www.southparkstudios.nu/full-episodes/season-1
or
youtube-dl https://www.southparkstudios.nu/full-episodes/season-1?sort=!airdate

also could u make it not give me 4 files and insted merge then together into 1 file

**Comment by jsmith1299** [comment]
Put it in a batch script. Problem solved.
