### ISSUE TITLE
Video truncation downloading from Curiosity Stream

### ISSUE THREAD

**Issue by voidshard** [ytdl-org/youtube-dl#24589]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hey guys, 

Question; 
I'm trying to download videos from CuriosityStream so I can watch them offline at leisure

- I've double checked and it's listed as a supported website. 
- I have a valid login & a cookies.txt that includes the auth_token (among others) for the curiosity stream domain

When I point youtube-dl at a CuriosityStream URL it downloads the first 2 minutes of the video & then moves on to the next (it still follows a playlist successfully & pulls the first 2 mins of each video). Regardless of whether I give it a cookies file or not it always grabs the first 2 mins .. for some reason (I kind of expected it to fail without cookies at all).

I'm using:
```
youtube-dl -ci -o '%(title)s.%(ext)s' --cookies cookies.txt --restrict-filenames [url]
```

Curious for any tips for downloading full length videos from CuriousityStream & thoughts on what I am doing wrong!?

**Comment by voidshard** [comment]
Why incomplete? If I've missed something in the README or FAQs then please point it out 'cause I sure as hell can't see where it's mentioned ..

**Comment by R3v3rso** [comment]
Hey @voidshard I had the same problem as you, and I just figured it out : 
Instead of relying on the cookies.txt file for authentication, just add -u YOUR-USERNAME -p YOUR-PASSWORD to your parameters :)
It worked like a charm for me, I just downloaded everything I needed to watch offline.

Hope this will help you !

**Comment by voidshard** [comment]
Hey @R3v3rso thanks! I'll give that a try!

**Comment by ilazim** [comment]
@voidshard any luck downloading from there? If so could you help me with it?

**Comment by Lamieur** [comment]
Instead of adding -u -p, just put:
machine curiositystream login <your email> password <your password>
in your ~/.netrc (just like you do for YouTube etc.)

(also @ilazim)

**Comment by nathanfranke** [comment]
I can still reproduce this on `2021.04.01`. Without auth, downloads 2 minutes. With auth,
```
[curiositystream] Downloading JSON metadata
[curiositystream] 4015: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by voidshard** [comment]
Hey @nathanfranke I believe using -u and -p solved it for me

**Comment by ewtoombs** [comment]
@nathanfranke I have observed the same error. It looks like CS has changed their API slightly. Authentication no longer works. But it is a [separate issue](https://github.com/ytdl-org/youtube-dl/issues/26845).
