### ISSUE TITLE
Wants to download 480p Youtube Video with audio in it plus thumbnail as well. Command please?

### ISSUE THREAD

**Issue by JaydanCrosby2021** [ytdl-org/youtube-dl#24593]
Please comment a command which can be used to download 480p video with thumbnail.

YOUTUBE DL: https://github.com/ytdl-org/youtube-dl

Tried 👇 below command but with the video which get downloaded doesn't contain audio in it [ I don't want separate audio file]

youtube-dl -f "bestvideo[height<=480]" --write-thumbnail https://www.youtube.com/watch?v=9RTaIpVuTqE

**Comment by dstftw** [comment]
Read FAQ on format selection.
