### ISSUE TITLE
Unsupported Site - BYUtv Subtitles Only

### ISSUE THREAD

**Issue by Verminaardd** [ytdl-org/youtube-dl#24595]
## Checklist

- [ ] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2020.03.24**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

https://www.byutv.org/dwightinshiningarmor

https://www.byutv.org/player/037d9221-8799-4508-8a00-d218c6df052b/dwight-in-shining-armor-fancy-pants

## Description

Hello

I am actually trying to get the English subtitles for the show Dwight in Shining Armor but youtube-dl says it's not supported. I have seen similar posts closed with DRM tag but I am not trying to get the video, I just need the English subtitles for translation purposes.

Youtube-dl command line for download the subs: (Episode 1)
youtube-dl --all-subs --skip-download https://www.byutv.org/player/037d9221-8799-4508-8a00-d218c6df052b/dwight-in-shining-armor-fancy-pants

The result:
[BYUtv] dwight-in-shining-armor-fancy-pants: Downloading JSON metadata
[BYUtv] 037d9221-8799-4508-8a00-d218c6df052b: Downloading m3u8 information
[BYUtv] 037d9221-8799-4508-8a00-d218c6df052b: Downloading MPD manifest
WARNING: [BYUtv] Unknown MIME type application/mp4 in DASH manifest

Thanks in advance.

**Comment by dstftw** [comment]
Subtitles from manifests are not supported.
