### ISSUE TITLE
Iwant.ph [Filipino Streaming Site]

### ISSUE THREAD

**Issue by zackmark29** [ytdl-org/youtube-dl#24607]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.iwant.ph/tv/watch/make-it-with-you/009-makeasadowithyou-jan-23-2020?id=8ce69cc2-0df4-41b2-98c1-8b0c1a057fa3

## Description

www.iwant.ph is the best streaming site for drama/moves for Filipino but also can watch other country with using VPN.
I tried to see the network log and it's also using m3u8

You can also watch using free account only with HD resolution

**Comment by zackmark29** [comment]
Please have support with this great site.

**Comment by dstftw** [comment]
1. You must provide account credentials.
2. You must provide proxy/VPN.
