### ISSUE TITLE
Youtube 403 error with specific video

### ISSUE THREAD

**Issue by piyh** [ytdl-org/youtube-dl#24606]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.03.24**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Description

I'm scraping a channel and this one video is causing issues.  I can use --playlist-start to skip it and download the rest.  When trying to download the vid by the URL I still get the error.

```

ryan@DESKTOP-EUD436E:/mnt/e/kingcobrajfs$ youtube-dl -v --write-auto-sub --call-home  https://www.youtube.com/watch?v
=ueQH4s467OI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--write-auto-sub', u'--call-home', u'https://www.youtube.com/watch?v=ueQH4s467OI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Linux-4.4.0-18362-Microsoft-x86_64-with-debian-10.3
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs 5, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: 97.118.99.250
[youtube] ueQH4s467OI: Downloading webpage
[youtube] ueQH4s467OI: Downloading embed webpage
[youtube] ueQH4s467OI: Refetching age-gated info webpage
[youtube] {18} signature length 108, html5 player vflset
[youtube] {22} signature length 108, html5 player vflset
[youtube] {136} signature length 108, html5 player vflset
[youtube] {247} signature length 104, html5 player vflset
[youtube] {135} signature length 108, html5 player vflset
[youtube] {244} signature length 108, html5 player vflset
[youtube] {134} signature length 108, html5 player vflset
[youtube] {243} signature length 108, html5 player vflset
[youtube] {133} signature length 104, html5 player vflset
[youtube] {242} signature length 104, html5 player vflset
[youtube] {160} signature length 108, html5 player vflset
[youtube] {278} signature length 108, html5 player vflset
[youtube] {140} signature length 108, html5 player vflset
[youtube] {249} signature length 104, html5 player vflset
[youtube] {250} signature length 108, html5 player vflset
[youtube] {251} signature length 108, html5 player vflset
[youtube] ueQH4s467OI: Looking for automatic captions
WARNING: Couldn't find automatic captions for ueQH4s467OI
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r2---sn-qxoedn7d.googlevideo.com/videoplayback?expire=1585978773&ei=NcmHXrjONMHVwQGr-KfQDw&ip=97.118.99.250&id=o-APDEljxOLq8aE4tqpIqXSEd8RS5l8vAJpnDab43YF8CO&itag=247&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mh=Qn&mm=31%2C29&mn=sn-qxoedn7d%2Csn-qxo7rn7l&ms=au%2Crdu&mv=m&mvi=1&pl=15&initcwndbps=858750&vprv=1&mime=video%2Fwebm&gir=yes&clen=747125477&dur=8314.999&lmt=1569083489057062&mt=1585957056&fvip=2&keepalive=yes&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIhANfi1aw-nrgMszpOoIcgIDsLsg0iuUteCBamq3RVp_fCAiA1AUjVcoyDfJ8hTwmDyfOwYEddWfvfbja_NcLIikIxMA%3D%3D&sig=PAJpPlLs_RAIgfXP9IkUuyjFvmTv7B7DawweTemwKBZVMP-xzlKxSamUEIHPCRJWp5sxNTAMbLHKFMD86vFw_ciN4dcnA7uUH&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/ryan/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/home/ryan/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/home/ryan/.local/lib/python2.7/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/ryan/.local/lib/python2.7/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/home/ryan/.local/lib/python2.7/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/ryan/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

**Comment by piyh** [comment]
What is this a duplicate of?

**Comment by MSauce** [comment]
This is not a duplicate nor the usual forbidden issues dstftw is used to seeing. To be fair, it is rare for this to be the case.

I am experiencing this too from multiple locations/environments. New issue, only started noticing it this week. It is not consistent. If you attempt the same file over and over you will see successes and errors. 

`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=Vs6sWjiE9Yo']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.0 (CPython) - macOS-10.15.4-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Vs6sWjiE9Yo: Downloading webpage
[youtube] {18} signature length 112, html5 player vflset
[youtube] {137} signature length 108, html5 player vflset
[youtube] {248} signature length 108, html5 player vflset
[youtube] {136} signature length 112, html5 player vflset
[youtube] {247} signature length 108, html5 player vflset
[youtube] {135} signature length 108, html5 player vflset
[youtube] {244} signature length 112, html5 player vflset
[youtube] {134} signature length 112, html5 player vflset
[youtube] {243} signature length 112, html5 player vflset
[youtube] {133} signature length 112, html5 player vflset
[youtube] {242} signature length 112, html5 player vflset
[youtube] {160} signature length 112, html5 player vflset
[youtube] {278} signature length 112, html5 player vflset
[youtube] {140} signature length 108, html5 player vflset
[youtube] {249} signature length 112, html5 player vflset
[youtube] {250} signature length 112, html5 player vflset
[youtube] {251} signature length 112, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r5---sn-5ualdn7r.googlevideo.com/videoplayback?expire=1586502501&ei=BMePXtzHOayYkATIxK7ADQ&ip=XXXXXXXXXXX&id=o-AAH0LVoUlAR7RQ1qGwQvTPRuyctCFU5JhzcD7iKPqh6K&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=Ks&mm=31%2C29&mn=sn-5ualdn7r%2Csn-5uaeznkl&ms=au%2Crdu&mv=m&mvi=4&pl=21&gcr=us&initcwndbps=891250&vprv=1&mime=video%2Fmp4&gir=yes&clen=13539610&dur=156.840&lmt=1569617025630284&mt=1586480860&fvip=5&keepalive=yes&beids=9466585&c=WEB&txp=8311222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIhAIEA4w3kS1womr49qUNdh7X_1lgpaqrXG1UHaqBREOw0AiAzqzIdcowPg-N4dnZH_fJ8cZas3R8Lf2PHlH6Nj5TDdQ%3D%3D&sig=3E777ERE4ptxjqiscEOQz9-1bIMNfwXTJYu9tIti7Tr23jV0BICMYEARq7df8huONwV0uC4INSsqOY_Yn_o0Lkg2lb5rhNgIARwsLlPpJk&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden`

**Comment by MSauce** [comment]
Going to try again on #24713 if you want to +1
