### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 403: Forbidden for pluralsight

### ISSUE THREAD

**Issue by msn60** [ytdl-org/youtube-dl#24600]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-o', 'C:\\sample-downloader%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', '--min-sleep-interval', '30', '--max-sleep-interval', '60', 'https://app.pluralsight.com/library/courses/javascript-getting-started/', '--playlist-start', '1', '--verbose']
[debug] Encodings: locale cp1256, fs mbcs, out cp720, pref cp1256
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[pluralsight:course] javascript-getting-started: Downloading JSON metadata
[download] Downloading playlist: JavaScript: Getting Started
[pluralsight:course] playlist JavaScript: Getting Started: Collected 78 video ids (downloading 78 of them)
[download] Downloading video 1 of 78
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

I have downloaded last version with nmp. After running this following command in cmd, I got 403 Error
```
youtube-dl --username "myemail" --password "mypassword" -o "C:\sample-downloader%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" --min-sleep-interval 30 --max-sleep-interval 60 https://app.pluralsight.com/library/courses/javascript-getting-started/ --playlist-start 1 --verbose
```
Thanks for your supports

**Comment by msn60** [comment]
Where can i find the response? I can not find proper reply between issues?

**Comment by JuanIgnacioBarrranco** [comment]
@msn60 
Hi, I believe I have found the solution or a partial one at least...
It is related to the directory where you download your courses
1-Create a folder wherever you want and name it as the course you're trying to get. 
2- Inside, let's copy the "youtube-dl.exe" that you properly need to have installed before the download. 
3- Type the combination of "Windows + R" buttons on your keyboard, then type 
"cmd /K cd/d HERE THE DIRECTORY WHERE YOUR FOLDER IT'S LOCATED" (should be something like this: **cmd /K cd/d C:\Users\Pluralsight\React\Using React Hooks**)
The preview step is going to show you a Console
4-Inside the folder you've created, run as administrator the "youtube-dl.exe", it will be run and then shout down by itself. 
5-In the preview Console which is already opened  type now the command that we all know by completing with your data ( user, pass, and the link to the course you want) 
**youtube-dl --username "myemail" --password "mypassword" -o "C:\sample-downloader%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" --min-sleep-interval 30 --max-sleep-interval 60 https://app.pluralsight.com/library/courses/javascript-getting-started/ --playlist-start 1 --verbose**. 
_And that's it. 
I hope that it works for you. 
I am from Argentina, and I do not speak English, this is the best I can do without using any Translator._

**Comment by mesuttalebi** [comment]
> ## Checklist
> * [x]  I'm reporting a broken site support issue
> * [x]  I've verified that I'm running youtube-dl version **2020.03.24**
> * [x]  I've checked that all provided URLs are alive and playable in a browser
> * [x]  I've checked that all URLs and arguments with special characters are properly quoted or escaped
> * [x]  I've searched the bugtracker for similar bug reports including closed ones
> * [x]  I've read bugs section in FAQ
> 
> ## Verbose log
> ```
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-o', 'C:\\sample-downloader%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', '--min-sleep-interval', '30', '--max-sleep-interval', '60', 'https://app.pluralsight.com/library/courses/javascript-getting-started/', '--playlist-start', '1', '--verbose']
> [debug] Encodings: locale cp1256, fs mbcs, out cp720, pref cp1256
> [debug] youtube-dl version 2020.03.24
> [debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
> [debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
> [debug] Proxy map: {}
> [pluralsight:course] javascript-getting-started: Downloading JSON metadata
> [download] Downloading playlist: JavaScript: Getting Started
> [pluralsight:course] playlist JavaScript: Getting Started: Collected 78 video ids (downloading 78 of them)
> [download] Downloading video 1 of 78
> [pluralsight] Downloading login page
> [pluralsight] Logging in
> ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
>   File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
>   File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
>   File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
>   File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
>   File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
> ```
> 
> ## Description
> I have downloaded last version with nmp. After running this following command in cmd, I got 403 Error
> 
> ```
> youtube-dl --username "myemail" --password "mypassword" -o "C:\sample-downloader%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" --min-sleep-interval 30 --max-sleep-interval 60 https://app.pluralsight.com/library/courses/javascript-getting-started/ --playlist-start 1 --verbose
> ```
> 
> Thanks for your supports

have the same issue,
