### ISSUE TITLE
ytdl should merge subtitles into the output file when the output format supports subtitle streams (eg mkv)

### ISSUE THREAD

**Issue by triffid** [ytdl-org/youtube-dl#24619]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

YTDL does not currently seem to merge subtitles into mkv output files, instead leaving a separate subtitle file beside the regular output file.

I would like it to automatically merge subtitles in addition to video/audio since mkv supports subtitle streams.

Other output formats that support subtitle streams could do with the same feature.

**Comment by dstftw** [comment]
Read FAQ?
```
--embed-subs                     Embed subtitles in the video (only for mp4,
                                 webm and mkv videos)
```
