### ISSUE TITLE
Specifying thumbnail & metadata location

### ISSUE THREAD

**Issue by bpo5r5** [ytdl-org/youtube-dl#24625]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is it possible to specify the output directory of the thumbnail and metadata files in one command? Or do I have to run 2 individual `youtube-dl` commands to specify where they go?

Reason being I'd like to have the following folder naming scheme, but I don't want to run 3 command per video (video, thumb, metadata).
```
├───Channel
│   ├───metadata
│   └───thumbnails
│   video.ext
```

Thank you in advance

**Comment by dstftw** [comment]
Not possible.
