### ISSUE TITLE
Pluralsight JSON download problem

### ISSUE THREAD

**Issue by hsquared2** [ytdl-org/youtube-dl#24622]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2020.03.24**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

youtube-dl --verbose https://app.pluralsight.com/library/courses/csharp-collections-advanced/table-of-contents
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://app.pluralsight.com/library/courses/csharp-collections-advanced/table-of-contents']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.1 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] csharp-collections-advanced: Downloading JSON metadata
[pluralsight:course] csharp-collections-advanced: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
## Description

WRITE DESCRIPTION HERE

**Comment by npdelhi** [comment]
Its working if you add working username
youtube-dl --username "user@email" --password "pass " --verbose https://app.pluralsight.com/library/courses/csharp-collections-advanced/table-of-contents

**Comment by ph-py** [comment]
Correct this issue by downloading the cookies from Pluralsight

1 - Download this plugin for google chrome [cookiestxt](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg) 
2 - Access Pluralsight like a normal user and navigate to the course you want to download
3 - After navigate, click on the **cookiestxt** button and "**click here**" blue link to download the cookies.txt file
4 - Add your username, password, user-agent, sleep-interval, cookie and subtitles (optional) to your download
`youtube-dl --username "xxxx@mail.com" --password "xxxxxx" --verbose --min-sleep-interval 120 --max-sleep-interval 240 "https://app.pluralsight.com/library/courses/course-of-your-choice/table-of-contents" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0" --cookies cookies.txt --sub-lang en --sub-format srt --write-sub`
5 - Users of distros like ubuntu related problems downloading this way, I have made it all in windows 10
6 - Watch out to not be banned by Pluralsight
7 - Try Harder!
