### ISSUE TITLE
Striking Video Quality Difference in Downloaded Videos than Native Players

### ISSUE THREAD

**Issue by Xochipelli** [ytdl-org/youtube-dl#24623]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
D:\>youtube-dl -v -f original --hls-prefer-native https://fast.wistia.net/embed/iframe/1gkclxsgvr
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'original', '--hls-prefer-native', 'https://fast.wistia.net/embed/iframe/1gkclxsgvr']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-82143-gbf14393, ffprobe git-2020-04-03-52523b6
[debug] Proxy map: {}
[Wistia] 1gkclxsgvr: Downloading JSON metadata
[debug] Invoking downloader on 'http://embed.wistia.com/deliveries/bafa3069decfdf4c38a89640108dfc77.bin'
[download] Destination: 9. Viewing URLs Used by Spider.mp4-1gkclxsgvr.bin
[download] 100% of 4.07MiB in 00:00

## Description

There is a huge difference in video quality between what is seen in the browser with the native video player (wistia player, in this case) than the downloaded video. Ultimately any text displayed in the downloaded video is effectively unreadable. Text in the video played in the native wistia player is perfectly clear.

Video quality in wistia player:
https://www.screencast.com/t/SF7gNC2s

Downloaded video quality much lower than if viewed in wistia player, even when best video quality stream specified in youtube-dl options:
https://www.screencast.com/t/xYtSV2DFf

youtube-ld -F yields:
iphone-360p mp4 640x360 280k , mp4 container, h264, 2.67MiB
md_mp4-720p mp4 1280x720 532k , mp4 container, h264, 5.07MiB
original bin 1280x720 427k , 4.07MiB (best)

Both produce similar result shown in second link (downloaded sample) provided above:
youtube-dl -f original https://fast.wistia.net/embed/iframe/1gkclxsgvr
youtube-dl -f md_mp4-720p https://fast.wistia.net/embed/iframe/1gkclxsgvr

Thinking ffmeg might have been the culprit, I updated ffmpeg in my default directory D:\CLI\ffmpeg dir and tested with both native and ffmpeg flags with no change:
youtube-dl -f original --hls-prefer-native https://fast.wistia.net/embed/iframe/1gkclxsgvr
youtube-dl -f original --hls-prefer-ffmpeg https://fast.wistia.net/embed/iframe/1gkclxsgvr

Is there a way to achieve better video quality on downloads?
Or are embedded wistia and other similar videos downloaded with youtube-dl destined to be inferior quality?

**Comment by dstftw** [comment]
Both downloaded 720p formats have perfectly readable text for me.

**Comment by Xochipelli** [comment]
thank you... It was a vlc issue
Selecting vlc's menu/video/deinterlace/off has solved the issue
