### ISSUE TITLE
Best way to generate both, the best video and audio file in one go in specific output formats

### ISSUE THREAD

**Issue by frispete** [ytdl-org/youtube-dl#24628]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

What's the best way to generate both, the best video (merged with best audio) and the best audio file in one go, converting to specific output formats without leaving intermediate files behind?

First, thank you for this **awesome** program. It's been a reliable companion for quite some time now, and has proven its fitness in a lot of situations. 

I also see, that it goes to great length solve this issue, but I haven't found a good way to success without downloading the video twice, and using the --extract-audio switch once, or leaving intermediate files behind (with --keep-video).

As an example, the net result should be generating a mp4 as well as a mp3 file in one go? E.g. I would like to combine these options:
```
youtube-dl --recode-video mp4 --extract-audio --audio-format mp3 --audio-quality 0 --output '%(title)s.%(ext)s'
```
but this results in an audio stream, encoded as mp4. Hmm. 

In the README, there's an example:
```
# Download the best video format and the best audio format without merging them
$ youtube-dl -f 'bestvideo,bestaudio' -o '%(title)s.f%(format_id)s.%(ext)s'
```
that almost acts, like what I have in mind, but it should combine them, and convert the result in both requested formats. Is that possible somehow?

**Comment by dstftw** [comment]
Not possible in one pass.
