### ISSUE TITLE
sleep-interval with duration

### ISSUE THREAD

**Issue by Alterant-zz** [ytdl-org/youtube-dl#24635]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

There are options sleep-interval and max-sleep-interval to set the delay before the next download.
At the same time there are several options to format filename: duration, filesize, filesize_approx.

Is it possible to set the delay based on the duration (or if not possible then based on filesize) of the previous file?
It would be great to have a delay set like this: previous_file_duration + some seconds from interval (sleep-interval..max-sleep-interval).

**Comment by dstftw** [comment]
Not possible.
