### ISSUE TITLE
Video only for high resolution, no audio

### ISSUE THREAD

**Issue by Jackie78De** [ytdl-org/youtube-dl#24648]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Hello,

I am using youtube-dl on Windows, version 2020.03.24, and want to downlload a youtube-video, but only for low resolution videos I am able to get both autdio and video in one file. As you see in the example below, for highres-video, I can get the video, but only without audio. Why? I would like to get a high resolution file with video. 

If I watch the same video on YT directly, I get high res video with audio.

Details see below, please feel free to ask if you need further details, thank you!

C:\Programme\YoutubeDL>youtube-dl -U
youtube-dl is up-to-date (2020.03.24)

C:\Programme\YoutubeDL>youtube-dl -F https://www.youtube.com/watch?v=t_***
[youtube] t_***: Downloading webpage
[info] Available formats for t_***
format code  extension  resolution note
249          webm       audio only tiny   63k , opus @ 50k (48000Hz), 1.71MiB
250          webm       audio only tiny   76k , opus @ 70k (48000Hz), 2.18MiB
140          m4a        audio only tiny  130k , m4a_dash container, mp4a.40.2@128k (44100Hz), 4.27MiB
251          webm       audio only tiny  136k , opus @160k (48000Hz), 4.09MiB
278          webm       256x144    144p   97k , webm container, vp9, 30fps, video only, 3.12MiB
160          mp4        256x144    144p  111k , avc1.4d400c, 30fps, video only, 3.31MiB
242          webm       426x240    240p  224k , vp9, 30fps, video only, 7.26MiB
133          mp4        426x240    240p  245k , avc1.4d4015, 30fps, video only, 6.29MiB
243          webm       640x360    360p  410k , vp9, 30fps, video only, 13.35MiB
134          mp4        640x360    360p  633k , avc1.4d401e, 30fps, video only, 15.74MiB
244          webm       854x480    480p  759k , vp9, 30fps, video only, 24.76MiB
135          mp4        854x480    480p 1159k , avc1.4d401f, 30fps, video only, 30.51MiB
247          webm       1280x720   720p 1514k , vp9, 30fps, video only, 49.41MiB
136          mp4        1280x720   720p 2186k , avc1.4d401f, 30fps, video only, 55.11MiB
302          webm       1280x720   720p60 2653k , vp9, 60fps, video only, 84.60MiB
248          webm       1920x1080  1080p 2667k , vp9, 30fps, video only, 87.25MiB
298          mp4        1280x720   720p60 3473k , avc1.4d4020, 60fps, video only, 97.04MiB
137          mp4        1920x1080  1080p 3986k , avc1.640028, 30fps, video only, 104.98MiB
303          webm       1920x1080  1080p60 4431k , vp9, 60fps, video only, 144.96MiB
299          mp4        1920x1080  1080p60 5783k , avc1.64002a, 60fps, video only, 187.56MiB
18           mp4        640x360    360p  737k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 24.29MiB (best)

**Comment by Hrxn** [comment]
https://github.com/ytdl-org/youtube-dl#do-i-need-any-other-programs
