### ISSUE TITLE
Zoom.us Recorded Meetings

### ISSUE THREAD

**Issue by joshcarst** [ytdl-org/youtube-dl#24643]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://rit.zoom.us/rec/play/v5d5f-j8_W03TtXAsASDAPF9W9XsJqus0CEYrPEPnxu1ViMCZAfzZeEQZLOEF776Nu1s8EZKj5t9QWu-

## Description

While there is an open issue regarding Zoom support from 2018, I'd like to bring attention to it again on account of university courses occurring online over Zoom. I'm trying to archive all recorded Zoom lectures and meetings my professors post links to, and there's no way provided by the website to download as MP4. The streams aren't easily extractable through Chrome's network monitor, as they give 403 errors when visited.

**Comment by Battleman** [comment]
Hey. I'm not sure this is adequate here, let me know if it isn't. I wrote a quick python3 script to download such videos. Please have a look: https://github.com/Battleman/zoomdl/

This is in no way a replacement, just a temporary solution. I still encourage youtube-dl to implement support for Zoom. I'm myself looking at the code atm to try and contribute.
