### ISSUE TITLE
use --get-title while not simulating?

### ISSUE THREAD

**Issue by MarByteBeep** [ytdl-org/youtube-dl#24654]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I'm trying to download a video AND get title information displayed in the console log as well. When invoking

```
youtube-dl.exe SmanVIJ80EY --no-call-home --newline -x -o "out.$(ext)s" 2>&1
```

I see a lot of information, but neither of it contains the video title. I also tried `-v` for extra information, but here too: no video title. 

There is a way to obtain that using --get-title, but when supplying that, no actual download takes place. It merely simulates. 

To get this information, I then have to call the tool twice, which is a lot slower, since there seems to be a significant startup time.

Is there a way to get the video title in the output in the same pass as downloading it?

**Comment by dstftw** [comment]
`--print-json`.

**Comment by MarByteBeep** [comment]
`--print-json` behaves completely different. There is no progress indication anymore and it basically dumps all information to the stdout. Just compare the outputs of these two commands:

```
youtube-dl.exe SmanVIJ80EY --no-call-home --newline -x -o "out.$(ext)s" 2>&1
youtube-dl.exe SmanVIJ80EY --no-call-home --print-json --newline -x -o "out.$(ext)s" 2>&1
```

The latter cannot be used to capture any progress indication, plus the fact that I only need something trival as the video title; not ALL information.

**Comment by MarByteBeep** [comment]
@dstftw since you immediately closed this issue; I'm not sure if you get these updated, but please check my previous comment on `--print-json`

**Comment by dstftw** [comment]
No such feature exist.

**Comment by MarByteBeep** [comment]
@dstftw that I know; hence the reason for a feature request

**Comment by dstftw** [comment]
I don't think this deserves an option.

**Comment by MarByteBeep** [comment]
@dstftw you already have the option --get-title. The only thing that is missing is to display that in one go. I don't understand why it would take two runs to get something as trivial as a video title.

**Comment by dstftw** [comment]
`--get-title` is a simulate option, it's not supposed to download anything and it won't.

**Comment by MarByteBeep** [comment]
@dstftw by changing the `__forced_printings` method in YouTubeDL.py, we can have the best of both worlds. It displays `[videotitle] <title>` in non-simulation mode. And keeps the same behavior in simulation mode. If possible, can you please add this change?

```python
    def __forced_printings(self, info_dict, filename, incomplete):
        def print_title():
            if (not incomplete or info_dict.get(field) is not None):
                if (self.params.get('forcetitle', False)):
                    self.to_stdout(info_dict["title"])
                else:
                    self.to_stdout("[videotitle] %s" % info_dict["title"])
				    
        def print_mandatory(field):
            if (self.params.get('force%s' % field, False)
                    and (not incomplete or info_dict.get(field) is not None)):
                self.to_stdout(info_dict[field])

        def print_optional(field):
            if (self.params.get('force%s' % field, False)
                    and info_dict.get(field) is not None):
                self.to_stdout(info_dict[field])

        print_title()
        print_mandatory('id')
        if self.params.get('forceurl', False) and not incomplete:
            if info_dict.get('requested_formats') is not None:
                for f in info_dict['requested_formats']:
                    self.to_stdout(f['url'] + f.get('play_path', ''))
            else:
                # For RTMP URLs, also include the playpath
                self.to_stdout(info_dict['url'] + info_dict.get('play_path', ''))
        print_optional('thumbnail')
        print_optional('description')
        if self.params.get('forcefilename', False) and filename is not None:
            self.to_stdout(filename)
        if self.params.get('forceduration', False) and info_dict.get('duration') is not None:
            self.to_stdout(formatSeconds(info_dict['duration']))
        print_mandatory('format')
        if self.params.get('forcejson', False):
            self.to_stdout(json.dumps(info_dict))
```
