### ISSUE TITLE
Why is either extractor or extractor_key needed when they're virtually the same?

### ISSUE THREAD

**Issue by Glenta** [ytdl-org/youtube-dl#24656]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

From what I can tell from extracting videos from all sorts of sites, why is extractor and extractor_key necessary when they give the same output. The only site I can tell that have different outputs are YouTube which gives "Youtube" from "extractor_key" and "youtube" from "extractor."

I would also like to add can you change YouTube's "extractor_key" from Youtube to YouTube.

**Comment by dstftw** [comment]
The former is printable name, the latter is key identifier. Key won't change.
