### ISSUE TITLE
Error Downloading

### ISSUE THREAD

**Issue by BarbiBimbo** [ytdl-org/youtube-dl#24659]
'''
**I am using winddows version of youtube-dl
It seems to work fine on music videos.

Full-length movies however have errors.

Logfile:**

C:\Users\James\Downloads\Media>youtube-dl --write-info-json -f bestvideo+bestaudio  -v -o 'output'  https://www.youtube.com/watch?v=-16vKFCmylc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--write-info-json', '-f', 'bestvideo+bestaudio', '-v', '-o', "'output'", 'https://www.youtube.com/watch?v=-16vKFCmylc']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2020-04-03-52523b6, ffprobe git-2020-04-03-52523b6
[debug] Proxy map: {}
[youtube] -16vKFCmylc: Downloading webpage
[youtube] -16vKFCmylc: Downloading MPD manifest
WARNING: [youtube] -16vKFCmylc: Skipping DASH manifest: ExtractorError('Failed to download MPD manifest: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue
 on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete
output.',)
[info] Writing video description metadata as JSON to: 'output'.info.json
[debug] Invoking downloader on 'https://r8---sn-bvvbax-2iae.googlevideo.com/videoplayback?expire=1586232386&ei=4qeLXuuwLKKt8gTO4YMQ&ip=76.98.43.21&id=05ee1aa33bcf5015&itag=227&aita
gs=142%2C143%2C144%2C145%2C146%2C161%2C222%2C223%2C224%2C225%2C226%2C227%2C273%2C274%2C275%2C279%2C280%2C317%2C318%2C357%2C358%2C359%2C360&source=yt_media&requiressl=yes&mh=4V&mm=3
1%2C29&mn=sn-bvvbax-2iae%2Csn-ab5szn7d&ms=au%2Crdu&mv=m&mvi=7&pl=21&gcr=us&initcwndbps=1576250&vprv=1&mime=video%2Fmp4&aid=fb5eaf2850a6ca57&asource=youtube&gir=yes&clen=5728879588&
dur=7709.200&lmt=1548776144856627&mt=1586210641&fvip=1&keepalive=yes&beids=9466588&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Caid%2Cas
ource%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJpPlLswRAIgVwEe2JN8KGK_Guk5xpsymq4SgeavE0a5JMSG9HvQMhACIFUGhNegRYUEje0CRkzqRvAg7M08LZmNpJYEmhNO3p0C&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2
Cinitcwndbps&lsig=ALrAebAwRQIgW7L1SSxlXt6nvMkhjm8Z7wBWoGUPdaPr9ZXlEhz_1foCIQCj7VGd76f_pFTo53LCXe_5kGjz8Pwzb-ZSzZWx67rifQ%3D%3D&ratebypass=yes'
[download] Destination: 'output'.f227
[download] 100% of 5.34GiB in 26:58
[debug] Invoking downloader on 'https://r8---sn-bvvbax-2iae.googlevideo.com/videoplayback?expire=1586232386&ei=4qeLXuuwLKKt8gTO4YMQ&ip=76.98.43.21&id=05ee1aa33bcf5015&itag=329&sour
ce=yt_media&requiressl=yes&mh=4V&mm=31%2C29&mn=sn-bvvbax-2iae%2Csn-ab5szn7d&ms=au%2Crdu&mv=m&mvi=7&pl=21&gcr=us&initcwndbps=1576250&vprv=1&mime=audio%2Fmp4&aid=fb5eaf2850a6ca57&aso
urce=youtube&gir=yes&clen=372094347&dur=7709.312&lmt=1548778572810182&mt=1586210641&fvip=1&keepalive=yes&beids=9466588&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequire
ssl%2Cgcr%2Cvprv%2Cmime%2Caid%2Casource%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJpPlLswRQIgVpUmFyz6unOd8BnSfj8pd5Rd760ZlU6LNZUXoS7KyQkCIQDk6miKGo1T82REwaoJPQftlJg0Th1FN-4arZHB2zx7jg%3D%3D&ls
params=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgW7L1SSxlXt6nvMkhjm8Z7wBWoGUPdaPr9ZXlEhz_1foCIQCj7VGd76f_pFTo53LCXe_5kGjz8Pwzb-ZSzZWx67rifQ%3D%3D&ratebypass=
yes'
[download] Destination: 'output'.f329
[download] 100% of 354.86MiB in 01:46
[ffmpeg] Merging formats into "'output'.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:'output'.f227" -i "file:'output'.f329" -c copy -map "0:v:0" -map "1:a:0" "file:'output'.temp.mp4"
ERROR: Conversion failed!
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2065, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\postprocessor\ffmpeg.py", line 512, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

C:\Users\James\Downloads\Media>pause
Press any key to continue . . .

**Additionally,. attempting to join the output files manually with this command
ffmpeg -i output.f227 -i output.f329 out1.mp4
Generated hundreds of errors "Corrupt Decoded Frame in Stream 0"**
'''

**Comment by dstftw** [comment]
1. Output template must contain `ext`.
2. Windows does not support single quotes.

**Comment by BarbiBimbo** [comment]
I did not have an output template.  The docs do not say it is necessary.  Can you please type what the corrected command should be instead of just closing the ticket with no info?

**Comment by dstftw** [comment]
>youtube-dl --write-info-json -f bestvideo+bestaudio -v -o 'output' https://www.youtube.com/watch?v=-16vKFCmylc
>-o 'output'

The command is bare URL. Don't touch options if you have no idea of what you're doing.
