### ISSUE TITLE
Please add discoveryplus.com

### ISSUE THREAD

**Issue by Mouse753** [ytdl-org/youtube-dl#24698]
## Checklist

- [x ] I'm reporting a new site support request
- [x ] I've verified that I'm running youtube-dl version **2020.03.24**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that none of provided URLs violate any copyrights
- [x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.discoveryplus.com/videos/coronavirus-the-silent-killer/
- Single video: https://www.discoveryplus.com/
- Playlist: 

## Description

youtube-dl.exe -F https://www.discoveryplus.com/videos/coronavirus-the-silent-killer/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.discoveryplus.com/videos/coronavirus-the-silent-killer/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-02-18-ebee808
[debug] Proxy map: {}
[generic] coronavirus-the-silent-killer: Requesting header
WARNING: Falling back on generic information extractor.
[generic] coronavirus-the-silent-killer: Downloading webpage
[generic] coronavirus-the-silent-killer: Extracting information
ERROR: Unsupported URL: https://www.discoveryplus.com/videos/coronavirus-the-silent-killer/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\generic.py", line 3352, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.discoveryplus.com/videos/coronavirus-the-silent-killer/

**Comment by dstftw** [comment]
You must provide proxy/VPN/SSH tunnel able to access this site.

**Comment by Mouse753** [comment]
where do i send a working VPN credentials ?

**Comment by Mouse753** [comment]
VPN Details,
sent to email
dstftw@gmail.com

please follow and add :)

**Comment by felisucoibi** [comment]
This is from the same api as dplay.com discovery neteork probably same api

**Comment by Mouse753** [comment]
> This is from the same api as dplay.com discovery neteork probably same api

Hmm, then i Guess will fix soon :)
By the way @dstftw we can get premium too using cookies ?

**Comment by felisucoibi** [comment]
> > This is from the same api as dplay.com discovery neteork probably same api
> 
> Hmm, then i Guess will be fixed soon by owner :)
> By the way @dstftw we can get premium too using cookies ?

here some people succeded usign cookies, i dont.
https://github.com/ytdl-org/youtube-dl/issues/24554

**Comment by RobertusIT** [comment]
> > > This is from the same api as dplay.com discovery neteork probably same api
> > 
> > 
> > Hmm, then i Guess will be fixed soon by owner :)
> > By the way @dstftw we can get premium too using cookies ?
> 
> here some people succeded usign cookies, i dont.
> #24554

this is my issue with dplay.it and with cookies from firefox or chrome, doesn't works

how is possible that there are people that said that works?

i didn't understand, maybe doesn't specified that are another website, and not dplay.it ?

feel free for any suggestion

**Comment by Mouse753** [comment]
@dstftw When it can be updated ??

any ETA ?

and another site I asked for?

Thanks
