### ISSUE TITLE
Installing youtube-dl without the executable on windows

### ISSUE THREAD

**Issue by KirbyFan102** [ytdl-org/youtube-dl#24694]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

I don't want to use the executable to install youtube-dl on my computer. I used cmd to install gallery-dl and that worked fine. Isn't there a way to do that for youtube-dl?

**Comment by ScribbleGhost** [comment]
Why not use `pip install --upgrade youtube-dl` like it says in the documentation?...

**Comment by KirbyFan102** [comment]
Well, probably because I couldn't find said documentation. The readme file doesn't mention such a thing, and my google-fu failed me entirely. But thank you. Your advice worked. Someone really ought to update that readme.
