### ISSUE TITLE
Encountering an issue when downloading youtube playlist with youtube-dl

### ISSUE THREAD

**Issue by samwill170594** [ytdl-org/youtube-dl#24695]
Hello Team,

I encunter an issue whent trying to download a playlist on youtube with youtube-dl -i :

**ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.**

I use '**2020.03.24**' version of youtube-dl.

here are logs:

`**[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-i', 'PLjwdMgw5TTLXuY5i7RW0QqGdW0NZntqiP', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.6 (CPython) - Linux-5.5.15-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] PLjwdMgw5TTLXuY5i7RW0QqGdW0NZntqiP: Downloading webpage
[download] Downloading playlist: Formation Git
[youtube:playlist] playlist Formation Git: Downloading 16 videos
[download] Downloading video 1 of 16
[youtube] rP3T0Ee6pLU: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)**`

Thanks to help me please.

## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by fbsduser** [comment]
In my case I was using proxy and it was public, Probably that is your issue too. 
The error refers to bad IP Source ( ie spamming,phishing).
