### ISSUE TITLE
Hotstar video download

### ISSUE THREAD

**Issue by sadupol** [ytdl-org/youtube-dl#24707]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X ] I've verified that I'm running youtube-dl version **2020.03.24**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
E:\Users\Sadanand Pole\Downloads>youtube-dl.exe -v https://www.hotstar.com/in/tv/savdhaan-india-fir/s-1185/fatal-family-politics/1000249333
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.hotstar.com/in/tv/savdhaan-india-fir/s-1185/fatal-family-politics/1000249333']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-93884-g96c79d4e1f, ffprobe N-93884-g96c79d4e1f
[debug] Proxy map: {}
[hotstar] 1000249333: Downloading webpage
[hotstar] 1000249333: Downloading JSON metadata
[hotstar] 1000249333: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://hses4.akamaized.net/videos/hotstarint/forceup/1260025161/1586341016779/fcc2ab35a8cfbd1315af85b0085f1689/media-8/index.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 8
[download] Destination: Fatal Family Politics-1000249333.mp4
[download] 100% of 1.02MiB in 00:18
[debug] ffmpeg command line: ffprobe -show_streams "file:Fatal Family Politics-1000249333.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "Fatal Family Politics-1000249333.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Fatal Family Politics-1000249333.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:Fatal Family Politics-1000249333.temp.mp4"

## Description

WRITE DESCRIPTION HERE

Downloaded video file appears to suggest re-install of the Hotstar app. The video could be played in any media player such as VLC after extracting with youtube-dl until yesterday...

**Comment by Abhijit47** [comment]
**same problem faceing....need to fix this....**

**Comment by lzzy12** [comment]
Any update on this?

**Comment by xabayx** [comment]
I also just got the same error trying to download from hotstar.
It only downloads a small video with the following text in it: 
"This version of Hotstar is no longer supported.
Please download the latest version from the App Store. If you are unable to view content even after upgrading your app, please uninstall and reinstall the app.".

Any help would be appreciated!

**Comment by dstftw** [comment]
You must provide proxy/VPN.
