### ISSUE TITLE
Download the video with motion picture not the video with static image

### ISSUE THREAD

**Issue by yagyapandeya** [ytdl-org/youtube-dl#24718]
Hello 
I am a researcher and I want to download only the video with changing motion frames so that I would able to get the visual information and audio information in a timely manner.  I used the youtube-dl with various options but it also downloads the video with single frame information (i.e. static image) according to my configuration. I need the option in youtube-dl that can download only the video with changing frame information. Please let me know if there is an option in youtube-dl.

Here is my code:

  '''
#.CSV file format
Artist    Title    Link
Lys Assia    Refrain    https://youtube.com/watch?v=IyqIPvOkiRk
Jetty Paerl    De Vogels Van Holland    https://youtube.com/watch?v=u45UQVGRVPA
Fud Leclerc    Messieurs Les NoyÃ©s De La Seine    https://youtube.com/watch?v=U9O3sqlyra0
Walter Andreas Schwarz    Im Wartesaal Zum GroÃŸen GlÃ¼ck    https://youtube.com/watch?v=BDNARIDnmTc
MathÃ© AltÃ©ry    Le Temps Perdu    https://youtube.com/watch?v=dm1L0XyikKI
...

'''

import youtube_dl
import pandas as pd
import os
import traceback

CSV = "C:/Users/YASH/Desktop/MusicVideo_DB/Test.csv"

# create directory
savedir = "C:/Users/YASH/Desktop/MusicVideo_DB/mixtape"

if not os.path.exists(savedir):
    os.makedirs(savedir)

def make_savepath(title, artist, savedir=savedir):
    return os.path.join(savedir, "%s--%s.mp4" % (title, artist))

options = {
    'format': 'best/best', # choice of quality 
    'outtmpl': '%(id)s'         
    }  

ydl = youtube_dl.YoutubeDL(options)

with ydl:

    # read in videos CSV with pandas
    #df = pd.read_csv(CSV, sep=";", skipinitialspace=True)
    df = pd.read_csv(CSV,  skipinitialspace=True)
    df.Link = df.Link.map(str.strip)  # strip space from URLs

    # for each row, download
    for _, row in df.iterrows():
        print ("Downloading: %s from %s..." % (row.Title, row.Link))
        
        # download location, check for progress
        savepath = make_savepath(row.Title, row.Artist)
        try:
            os.stat(savepath)
            print ("%s already downloaded, continuing..." % savepath)
            continue

        except OSError:
            # download video
            try:
                result = ydl.extract_info(row.Link, download=True)
                os.rename(result['id'], savepath)
                print ("Downloaded and converted %s successfully!" % savepath)

            except Exception as e:
                print ("Can't download audio! %s\n" % traceback.format_exc())

**Comment by dstftw** [comment]
It's not possible to know beforehand whether it's motion or not.

**Comment by yagyapandeya** [comment]
Thank you dstftw for you quick response.
