### ISSUE TITLE
Catalina OS

### ISSUE THREAD

**Issue by msimoes99** [ytdl-org/youtube-dl#24725]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Does Youtube-dl still operate with Catalina OS or is Mojave OS the most up to date OS that can operate and support this downloader?

**Comment by dstftw** [comment]
Any OS that operates python 2.6+ or python 3.2+.
