### ISSUE TITLE
Getting 403 Forbidden error when downloading course from pluralsight

### ISSUE THREAD

**Issue by garchaaman19** [ytdl-org/youtube-dl#24746]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Command
`youtube-dl --cookies "../cookies.txt" --username "myemail" --password "mypassword"  --verbose --min-sleep-interval 60 --max-sleep-interval 120  "https://app.pluralsight.com/library/courses/python-beyond-basics"
`

`ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
`
O.S -Ubuntu
Python 3.6

This is the error I am getting, I even tried on kali linux but same result. Please help.

**Comment by garchaaman19** [comment]
@dstftw This issue is duplicate but it is still not resolved, the original issue.

**Comment by Y4kuzi** [comment]
All other issues related to this problem are either closed or labeled as duplicate. Why?
Pluralsight account is working fine, cookies are being passed, but since last night something changed and now it doesn't work anymore, and this has also been reported by some other people.

**Comment by eshack94** [comment]
Just wanted to report that this still is not working. Which is the active issue for this (so that I can follow it)?
