### ISSUE TITLE
Pluralsight not working any more

### ISSUE THREAD

**Issue by mkohlhaas** [ytdl-org/youtube-dl#24741]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
  % youtube-dl --verbose -u sliphard666@yandex.com -p 'Hallo:123' --sleep-interval 180 --add-header Referer:"https://app.pluralsight.com/library/courses/" -o '%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s' https://app.pluralsight.com/library/courses/azure-cosmos-db

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', '--sleep-interval', '180', '--add-header', 'Referer:https://app.pluralsight.com/library/courses/', '-o', '%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s', 'https://app.pluralsight.com/library/courses/azure-cosmos-db']
[debug] Adding header from command line option Referer:https://app.pluralsight.com/library/courses/
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Linux-5.4.31_1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[pluralsight:course] azure-cosmos-db: Downloading JSON metadata
[pluralsight:course] azure-cosmos-db: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description

I can login to Pluralsight with a web browser and watch all videos. But downloading does not work anymore. Did until this morning. I am using a promotion user (related to stay home due to Corona) that is valid until May 1st. You can use the user at your will, no problem. Option `--add-header` is not relevant; does not work without either.

**Comment by takashi85eg** [comment]
I got this issue too from a moment, and by the way .. remove you password my friend.

**Comment by mkohlhaas** [comment]
You can do with this user whatever you want. No problem!

**Comment by CrushCrush1954** [comment]
The same worked for me (same version, Windows variant).
Difference resides in the options --sleep-interval and/or --add-header that I did not include.

**Comment by mkohlhaas** [comment]
Did you use my user `sliphard666@yandex.com` ?

**Comment by CrushCrush1954** [comment]
The same worked ONCE for me (same version, Windows variant).
I did not include the options --sleep-interval and/or --add-header.
Used my own free user AND a paid user.
Used different countries (VPN).

**Comment by mkohlhaas** [comment]
So you want to say that it does not work anymore for you, too?

**Comment by CrushCrush1954** [comment]
> 
> 
> So you want to say that it does not work anymore for you, too?

Exactly. Tried again, using different lesson, error 403 again (same test steps as your bug report). Worked for two lessons.

**Comment by garchaaman19** [comment]
Even I am getting the same error and I have the same free temporary account, Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>), Any help please.

**Comment by tranphuquy19** [comment]
> Even I am getting the same error and I have the same free temporary account, Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>), Any help please.

Yeah, same problem
