### ISSUE TITLE
Standalone script for decrypt cipher signature ?

### ISSUE THREAD

**Issue by MegaCron** [ytdl-org/youtube-dl#24744]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi all.

I do not know how to create scripts in python, I create scripts in bash, but I did not find a solution for decrypting cipher signatures in bash. Youtube-dl has integrated signature decryption, is it possible to export it to a standalone script ? 

>./decrypt.py "here-encrypted-cipher-signature"

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl/blob/00eb865b3c8002f47e73706b54f58feaee0b0ac2/youtube_dl/extractor/youtube.py#L1369-L1394

**Comment by MegaCron** [comment]
dstftw, Is this a "plug-n-play" stand-alone script or raw code ? I do not understand python code.

**Comment by thedtvn** [comment]
same  to many def to look
