### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 403

### ISSUE THREAD

**Issue by ravirajdj** [ytdl-org/youtube-dl#24755]
Donwloading the course from pluralsight
contents"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose', '--sleep-interval', '120', 'https://app.pluralsight.com/library/courses/android-architecture-components-building-apps/table-of-contents']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] android-architecture-components-building-apps: Downloading JSON metadata
[download] Downloading playlist:  Building Apps with Android Architecture Components
[pluralsight:course] playlist  Building Apps with Android Architecture Components: Collected 44 video ids (downloading 44 of them)
[download] Downloading video 1 of 44
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by Y4kuzi** [comment]
All other issues related to this problem are either closed or labeled as duplicate.
Pluralsight account is working fine, cookies are being passed, but since last night something changed and now it doesn't work anymore, and this has also been reported by some other people.

**Comment by a-wip0** [comment]
@Y4kuzi they start to use captcha since last night

**Comment by Y4kuzi** [comment]
They started using captcha before that, it always worked fine when I pass the cookies.
Today it seems to work again. Weird, I just ran the same command as I always did.
Guess their servers spaced out for a bit yesterday.
