### ISSUE TITLE
[youtube] HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by vice** [ytdl-org/youtube-dl#24758]
For any video tried today 2020-04-13. On latest version 2020.03.24.

**Comment by Jeronimo17** [comment]
Yes, in videos with drm it is happening

**Comment by vice** [comment]
Not sure if it it related to DRM because my browser do not have DRM and previously downloaded videos are failing. Any how I close this issue because I opened issue #24760 filling the template.

**Comment by vice** [comment]
See #24760

**Comment by shuiqlazam** [comment]
I too am having the same problem - easily recreateable - recent update to youtube causing this?

Verbose error attached
[403error.txt](https://github.com/ytdl-org/youtube-dl/files/4483477/403error.txt)
