### ISSUE TITLE
What the solution

### ISSUE THREAD

**Issue by kartobecs** [ytdl-org/youtube-dl#24769]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

C:\Users\C:\youtube-dl.exe -F https://www.youtube.com/watch?v=qJ5yvOmGQuI
[youtube] qJ5yvOmGQuI: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 11004] getaddrinfo fail
ed> (caused by URLError(gaierror(11004, 'getaddrinfo failed'),))

**Comment by dstftw** [comment]
Fix your DNS.

**Comment by kartobecs** [comment]
probleme resolved by adding --proxy:
C:\Users\C:\youtube-dl.exe --proxy "" https://www.youtube.com/watch?v=qJ5yvOmGQuI

thanks
