### ISSUE TITLE
IGN Daily Fix downloads first playlist video, not the the main video

### ISSUE THREAD

**Issue by marciof** [ytdl-org/youtube-dl#24771]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ python3 -m youtube_dl -v http://www.ign.com/videos/2020/04/13/is-a-resident-evil-4-remake-on-the-way-ign-daily-fix
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.ign.com/videos/2020/04/13/is-a-resident-evil-4-remake-on-the-way-ign-daily-fix']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Git HEAD: 00eb865b3
[debug] Python version 3.5.3 (CPython) - Linux-4.9.0-12-amd64-x86_64-with-debian-9.12
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[ign.com] is-a-resident-evil-4-remake-on-the-way-ign-daily-fix: Downloading webpage
[ign.com] b363015830804eb6b42df8e7a8251675: Downloading JSON metadata
[ign.com] b363015830804eb6b42df8e7a8251675: Downloading m3u8 information
[ign.com] b363015830804eb6b42df8e7a8251675: Downloading f4m manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://assets7.ign.com/videos/zencoder/2019/02/25/1920/b363015830804eb6b42df8e7a8251675-3906000-1551138254.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 34
[download] Destination: Tons of Resident Evil Coming to Switch - IGN Daily Fix-b363015830804eb6b42df8e7a8251675.mp4
[download] 100% of 99.86MiB in 00:22
[debug] ffmpeg command line: ffprobe -show_streams 'file:Tons of Resident Evil Coming to Switch - IGN Daily Fix-b363015830804eb6b42df8e7a8251675.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Tons of Resident Evil Coming to Switch - IGN Daily Fix-b363015830804eb6b42df8e7a8251675.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Tons of Resident Evil Coming to Switch - IGN Daily Fix-b363015830804eb6b42df8e7a8251675.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:Tons of Resident Evil Coming to Switch - IGN Daily Fix-b363015830804eb6b42df8e7a8251675.temp.mp4'
```

## Description

For IGN Daily Fix videos, the first playlist video is downloaded, instead of the main video.

For example, for this URL: http://www.ign.com/videos/2020/04/13/is-a-resident-evil-4-remake-on-the-way-ign-daily-fix

It incorrectly downloads this playlist video: https://assets7.ign.com/videos/zencoder/2019/02/25/1920/b363015830804eb6b42df8e7a8251675-3906000-1551138254.m3u8

Instead of this main video: http://assets14.ign.com/videos/zencoder/2020/04/13/1920/aad8ad325d3608ff722291acddc7b230-3906000-1586818781.mp4

**Comment by VinaCaptcha** [comment]
Yes, I got the same problem :(

**Comment by ChainSwordCS** [comment]
This issue still exists. I don't know what Daily Fix is, but it also occurs with like any of their videos as far as I can tell.
https://www.ign.com/videos/2005/04/19/nintendogs-chihuahua-friends-ds-japanese-trailer
