### ISSUE TITLE
Twitch livestreams showing Commercial Break In Progress video

### ISSUE THREAD

**Issue by ctlaltdefeat** [ytdl-org/youtube-dl#24792]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Description

Due to a recent (several hours) change on Twitch's side, live streams are showing a Commercial Break In Progress video. Note that when playing through the browser I do not experience this, so at least in principle I think this should be possible to bypass.

See https://github.com/streamlink/streamlink/issues/2894

**Comment by reallyuniquename** [comment]
Whatever Twitch did it's now reverted. I no longer experience this issue.

**Comment by Aanok** [comment]
I'm experiencing this exactly like OP described with version 2020.11.19. Furthermore, the video produced has incorrect timestamps and the audio stream results heavily pitched down.

Here's a sample capture file: https://mega.nz/#!gggmVKiI!XlkPfo_EwvXEPgRDD3d2aVPAWlsd58gaFnpRF1kLUqM
And the session's log: [log.txt](https://github.com/ytdl-org/youtube-dl/files/5572641/log.txt)

**Comment by kienanstewart** [comment]
I have had some streams with the heavily pitched down audio, but others seem ok. Using youtube-dl 2020.11.21 and piping it to vlc. Streams with or without pitched down audio have the commercial break in progress video.
