### ISSUE TITLE
tying to login to Youtube so I can download my "Watch later playlist"

### ISSUE THREAD

**Issue by stephane-archer** [ytdl-org/youtube-dl#24793]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--username', u'PRIVATE', u'https://www.youtube.com/playlist?list=WL']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:watchlater] Downloading login page
[youtube:watchlater] Looking up account info
[youtube:watchlater] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube:watchlater] WL: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 3185, in _real_extract
    _, playlist = self._extract_playlist('WL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2685, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist does not exist.
```

## Description

When I run the following command:
```youtube-dl -v --username "<myid>" "https://www.youtube.com/playlist?list=WL"```
the login fail with the following message
```WARNING: Unable to log in: HTTP Error 400: Bad Request```

**Comment by stephane-archer** [comment]
I didn't see any new ticket about this issue @dstftw

**Comment by Hrxn** [comment]
Yeah, this is becoming a bit of a mess.

AFAIK, this is still not working properly, i.e. you can't login to your Google/YT account with youtube-dl at the moment. 
@dstftw correct me if I am wrong here.

This has been going for a while now. (Although, there is an option in the Google account settings: "Allow access to less-secure apps", maybe this works if you allow it temporarily).

If you want to access certain playlists on YouTube (or restricted videos, age-gated etc. pp.) you need to sign into YT in a browser, then simply use one of the good extensions to export your cookies, and finally use the resulting cookies.txt file with the `--cookies` switch from youtube-dl.
