### ISSUE TITLE
Downloading Specific Module in uDemy

### ISSUE THREAD

**Issue by alois-trancy** [ytdl-org/youtube-dl#24791]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is it possible to download a specific module of a  uDemy course ?
I've already downloaded a part of  the course that I paid way back but after a few modules, the download broke and now I want to continue it.

**Comment by dirkf** [comment]
`--playlist-start ...` might have helped.

Also see [why a dedicated tool for Udemy was abandoned](https://github.com/r0oth3x49/udemy-dl#user-content-warning).
