### ISSUE TITLE
Batch download in multiple folders, specify file names & log errors in log files

### ISSUE THREAD

**Issue by sreenadhp** [ytdl-org/youtube-dl#24802]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
I have a bunch of youtube urls, that are actually multiple playlist.

Is it possible to write a batch file (single txt)

- a set of URLs are downloaded in a specific folder
- another set in another folder and like that in various folders
- I want to modify the name of the file downloaded - append the uploaders name (`(uploader)`)
- if any of the download has an error, save that to a log file

My last resort is to write a python script & read off a json file to do it, I just want to know if something like this possible in a single txt file and a simple `youtube-dl -a list.txt`?

I know that batch file is not supposed to carry configuration, but that was [2017](https://github.com/ytdl-org/youtube-dl/issues/12935#issuecomment-298245974). Hoping to know if there is update to that.

Also, just curious to know what other ways to solve this problem.

I want to send this to a friend who is not tech savy but wants to download a bunch of tutorials. I am hope to keep this as simple as possible.

**Comment by dstftw** [comment]
Split to multiple batch files and call with whatever command line needed, redirect stderr to file.
