### ISSUE TITLE
Subs from Wiener Staatsoper

### ISSUE THREAD

**Issue by lestroyens** [ytdl-org/youtube-dl#24816]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi!
I have succesefully downloaded video from Wiener Staatsoper (https://www.staatsoperlive.com/0/3a92fdb7-ad06-44db-8f68-a51f706655e6/player, https://live.performa.intio.tv/media/06ec5732-1859-4a56-8e5d-7507758ba4cc/master-allsubs.m3u8) and want to download subtitles. I have detected throw the first link, that subtitles contains a big number of files like "subs-deu-NN.vtt" (NN - part number, about 3600 parts). How is it possible to download all this files to a one normal file?

**Comment by dstftw** [comment]
Not supported.
