### ISSUE TITLE
[youtube] video not getting video "chapters" properly

### ISSUE THREAD

**Issue by anabis** [ytdl-org/youtube-dl#24819]
The 'chapters' value from the JSON (-J parameter), is usually present on some video. But since a few days, it is not available in ANY video. My guess is that's since the new chapter UI of youtube.

Here's a verbose excerpt from youtube version 23.04.2020, not that it looks very useful

```
[ ~ ] $ youtube-dl -vJ https://www.youtube.com/watch?v=gBRKnvK1JUE 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vJ', u'https://www.youtube.com/watch?v=gBRKnvK1JUE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
[debug] exe versions: ffmpeg 4.1.5, ffprobe 4.1.5
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
{"upload_date": "20190921", "extractor": "youtube", "chapters": null, ...
```

**Comment by VolatileCable** [comment]
This seems to have broken again in 2020.06.16.1 .

The JSON chapter tag is just null with both the mentioned https://www.youtube.com/watch?v=gBRKnvK1JUE and also https://www.youtube.com/watch?v=Vr93xAFmJag . They also have different formats in the description.

I found this while investigating if youtube-dl writes these chapters to mkv files. This is not the case, even if this were working in the first place, right?

**Comment by VolatileCable** [comment]
Actually, I think this is all caused by #25937 .

**Comment by someziggyman** [comment]
Chapters are still NULL in 2020.07.28 release

**Comment by DrAutissimo** [comment]
> Actually, I think this is all caused by #25937 .

No, writing the description into a file gives the full description again, the chapters are still null however, even on f5863a3.

**Comment by DrAutissimo** [comment]
Doesn't work on current master branch, #26297 fixes this.

**Comment by sheerluck** [comment]
> #26297 fixes this.

#26297 fixes this for https://youtu.be/7LFJ7zSFUa8 and https://youtu.be/fzK79PgKITI
I wonder maybe youtube-dl could split video into chapters? (sudden feature request: to add `--split-into-chapters` so several files would be generated)

**Comment by DrAutissimo** [comment]
I think that request was already made a couple of times, don't remember what was said about it though.
There are a lot of splits that do exactly that though:
https://github.com/wattux/youtube-dl/commit/dcab7389acae63f0d2e01e13257e840e00c40518

If something breaks, you can just copy the new part of the postprocessor, and put it into a new version of ytdl.
You might need to do some tweaking though, since some youtube videos have filenames that windows normally wouldn't allow.

**Comment by sheerluck** [comment]
Thank you very very much!
Works like a charm!
https://i.imgur.com/DAiXKg6.png
My filenames tweaking is
```patch
--- a/youtube_dl/utils.py
+++ b/youtube_dl/utils.py
@@ -2091,6 +2091,12 @@ def sanitize_filename(s, restricted=False, is_id=False):
             return '' if restricted else '\''
         elif char == ':':
             return '_-' if restricted else ' -'
+        elif char == '|':
+            return chr(65372)
+        elif char == '/':
+            return chr(10744)
+        elif char == '\\':
+            return chr(10745)
         elif char in '\\/|*<>':
             return '_'
         if restricted and (char in '!&\'()[]{}$;`^,#' or char.isspace()):
```

**Comment by DrAutissimo** [comment]
That's a way more elegant solution than mine, I just changed the def _build_track_name to replace characters with a space.

**Comment by cantalupo555** [comment]
Use a current fork, like yt-dlp.
It supports Chapters.
