### ISSUE TITLE
Unable to download  - 403 error

### ISSUE THREAD

**Issue by lincoln7711** [ytdl-org/youtube-dl#24822]
Hi:

So the youtube-dl has been working - as in used it yesterday, but now I can't get it to download any playlist.  Uninstall and reinstall does not remedy.  Using pip, 2020.03.24 on Ubuntu 19.10, fully updated.  Output from a sample attempt using --verbose is below: 
`youtube-dl --verbose https://www.youtube.com/playlist\?list\=OLAK5uy_ks45-2ZsTEnWYtuwZVM0YIJQv7-lSDgdY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/playlist?list=OLAK5uy_ks45-2ZsTEnWYtuwZVM0YIJQv7-lSDgdY']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.5 (CPython) - Linux-5.3.0-46-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] OLAK5uy_ks45-2ZsTEnWYtuwZVM0YIJQv7-lSDgdY: Downloading webpage
[download] Downloading playlist: Friday the 13th
[youtube:playlist] playlist Friday the 13th: Downloading 4 videos
[download] Downloading video 1 of 4
[youtube] PNJKIPWqO9E: Downloading webpage
[youtube] {18} signature length 106, html5 player vflset
[youtube] {137} signature length 102, html5 player vflset
[youtube] {248} signature length 106, html5 player vflset
[youtube] {136} signature length 106, html5 player vflset
[youtube] {247} signature length 106, html5 player vflset
[youtube] {135} signature length 106, html5 player vflset
[youtube] {244} signature length 106, html5 player vflset
[youtube] {134} signature length 102, html5 player vflset
[youtube] {243} signature length 106, html5 player vflset
[youtube] {133} signature length 106, html5 player vflset
[youtube] {242} signature length 106, html5 player vflset
[youtube] {160} signature length 106, html5 player vflset
[youtube] {278} signature length 106, html5 player vflset
[youtube] {140} signature length 106, html5 player vflset
[youtube] {249} signature length 106, html5 player vflset
[youtube] {250} signature length 106, html5 player vflset
[youtube] {251} signature length 106, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r6---sn-ab5szn7l.googlevideo.com/videoplayback?expire=1587088345&ei=ebeYXoKoJYiEhgb84Km4Ag&ip=172.93.147.131&id=o-ACt4bKUfSSw01xEqw84fotkd6F2CdPteJP1BdBiO_pZx&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=kj&mm=31%2C29&mn=sn-ab5szn7l%2Csn-ab5l6nzd&ms=au%2Crdu&mv=m&mvi=5&pl=24&gcr=us&initcwndbps=2570000&vprv=1&mime=video%2Fwebm&gir=yes&clen=14859693&dur=288.640&lmt=1565664968298083&mt=1587066285&fvip=6&keepalive=yes&c=WEB&txp=1311222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgFBl9C6AWZw_7LAf7ARm0DLgw6psv---W1DHEXbD_IF0CIQDAezz2Lj-velx2Yri8w-CIMx2QyEFbY5RgBh4NKPDLxA%3D%3D&sig=kJAJpPlAswRQIhAPcchGA8mTBRLF8XsUGBZbG0Lqytd-nxPDE_-Y2rwZKtAiBC9GZVPfO02VmQ0=hRUw0dLKL8vYox5y2LZbVXuICqrR&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

**Comment by zackmark29** [comment]
same issue from viki.com just yesterday it's not working anymore with premium account.

**Comment by lincoln7711** [comment]
Passing `--rm-cache-dir` seems to have remedied this.  Thanks tshabs!
