### ISSUE TITLE
Facebook is broken. unable to extract video ids

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#24831]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

youtube-dl -v -F https://m.facebook.com/100037160205931/posts/223407958907876/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://m.facebook.com/100037160205931/posts/223407958907876/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 223407958907876: Downloading webpage
ERROR: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 474, in _real_extract
    webpage, 'video ids', group='ids'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output

**Comment by jaimebl** [comment]
It looks you're not using the right video url. Try:

`youtube-dl -v -F https://www.facebook.com/alex.drone.1840/videos/223407775574561/`

**Comment by vidaritos** [comment]
You have to right-click on the video, it will show a "Show URL to video" or something similar in your language, a text-field will appear with the link to use with youtube-dl. I tried this today, it works.

**Comment by someziggyman** [comment]
Appreciate your advice, guys. Yeah, you're right, those helped and I've successfully downloaded that video with a different URL. However, maybe folks maintaining youtube-dl will do some tiny optimizations and support all URL types for facebook. Anyway, thanks again for your help. Youtube-dl community is awesome.

**Comment by Natim** [comment]
Same issue today, while https://www.facebook.com/jebosseenGD/posts/3041440072603152 didn't download https://www.facebook.com/watch/?v=3402937886406323

I don't know if there is something we can do to somehow automate the translation from post containing the video to video itself.
