### ISSUE TITLE
Youtube-dl + django

### ISSUE THREAD

**Issue by harshjadon9** [ytdl-org/youtube-dl#24835]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
i have got a question with downloading transfer files with django
i have a downloader in views.py
which downloads video as per input url
but i want it to be downloaded in users directory and not in server dir
can anyone help...

**Comment by dstftw** [comment]
Read FAQ on output template.

**Comment by harshjadon9** [comment]
> Read FAQ on output template.

where is FAQ
