### ISSUE TITLE
Help Me Pleaze Youtube-Dl!!

### ISSUE THREAD

**Issue by Camy1988** [ytdl-org/youtube-dl#24838]
Hi guys, i have a problem downloading this video and i can't get over it.
Youtube-dl manages to download only part of the video and then stops.
Could you tell me how to download everything pleaseeeeee!

Thanks a lot :)

`https://ss-free.hotmovies.com/streams3/072/72605/72605.ism/72605.m3u8?ssauth=1054224!1-72605-20200417093351-cf24dbbeede2e57805c981515aa703ea`

![Ffmpeg](https://user-images.githubusercontent.com/63817705/79576200-32f33880-80c3-11ea-9c64-ec93053bc67f.JPG)
![Video_1](https://user-images.githubusercontent.com/63817705/79576209-3686bf80-80c3-11ea-9368-7382144bfd34.JPG)
![Video_2](https://user-images.githubusercontent.com/63817705/79576210-37b7ec80-80c3-11ea-886e-10dda17f9606.JPG)
![Youtube](https://user-images.githubusercontent.com/63817705/79576218-38e91980-80c3-11ea-8f5c-e20546495e32.JPG)

**Comment by dstftw** [comment]
Returns empty body.

**Comment by Camy1988** [comment]
Sorry, I don't understand

**Comment by Camy1988** [comment]
sorry, I don't understand

**Comment by Camy1988** [comment]
I have also tried with ffmpeg but I get the same result, do you have any idea how I can do it? :)
