### ISSUE TITLE
How exactly do skipped fragments work?

### ISSUE THREAD

**Issue by benjaminmesser** [ytdl-org/youtube-dl#24853]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

How exactly do skipped fragments work? Like what causes a fragment to be skipped and is there any way to retry a skipped fragment? Also if a video finishes with some skipped fragments then is it incomplete/missing segments?

**Comment by dstftw** [comment]
Fragment is retried `--fragment-retries` times then considered unavailable and skipped.

**Comment by febeling** [comment]
Two of the questions haven't been answered:
- "what causes a fragment to be skipped"?
- "if a video finishes with some skipped fragments then is it incomplete/missing segments?"

I find these questions very interesting and relevant. Can this be reopened?

**Comment by benjaminmesser** [comment]
I second the above that there still seems to be unanswered questions in the original inquiry that would be interesting to know.
