### ISSUE TITLE
sumo.tv2.no - not working or has it ever been supported?

### ISSUE THREAD

**Issue by yiveynod** [ytdl-org/youtube-dl#24856]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.03.24**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
youtube-dl -v "https://sumo.tv2.no/programmer/underholdning/truls-oppdrag-norge/sesong-1/truls-oppdrag-norge-1-episode-1-1104961.html?showPlayer=true"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://sumo.tv2.no/programmer/underholdning/truls-oppdrag-norge/sesong-1/truls-oppdrag-norge-1-episode-1-1104961.html?showPlayer=true']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.16 (CPython) - Darwin-19.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] truls-oppdrag-norge-1-episode-1-1104961: Requesting header
WARNING: Falling back on generic information extractor.
[generic] truls-oppdrag-norge-1-episode-1-1104961: Downloading webpage
[generic] truls-oppdrag-norge-1-episode-1-1104961: Extracting information
ERROR: Unsupported URL: https://sumo.tv2.no/programmer/underholdning/truls-oppdrag-norge/sesong-1/truls-oppdrag-norge-1-episode-1-1104961.html?showPlayer=true
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2375, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 1586
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3352, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://sumo.tv2.no/programmer/underholdning/truls-oppdrag-norge/sesong-1/truls-oppdrag-norge-1-episode-1-1104961.html?showPlayer=true

```

## Description

WRITE DESCRIPTION HERE
Trying to download videos from sumo.tv2.no. In the supported sites list it says TV2, but doesn't state if it's the Norwegian site TV2.no. So I'm unsure if it has ever been supported?
I'm trying to download "Truls - Oppdrag Norge" and it is, as far as I can see, not geo-restricted (I'm not located in Norway either). 
I've set up a user for solving this, please use.
User: yiveynod@gmail.com
Pass: github

**Comment by marium0505** [comment]
Most videos on TV 2 Sumo is content protected using DASH Content Protection using Microsoft PlayReady:
https://docs.microsoft.com/en-us/playready/specifications/mpeg-dash-playready

Attached the content of the MPD file for the video you're linking to (changed it to .txt as Github didn't support .mpd files):

[manifest.txt](https://github.com/ytdl-org/youtube-dl/files/4499063/manifest.txt)

**Comment by yiveynod** [comment]
> Most videos on TV 2 Sumo is content protected using DASH Content Protection using Microsoft PlayReady (from what I could find):
> https://docs.microsoft.com/en-us/playready/specifications/mpeg-dash-playready
> 
> Attached the content of the MPD file for the video you're linking to (changed it to .txt as Github didn't support .mpd files):
> [manifest.txt](https://github.com/ytdl-org/youtube-dl/files/4499063/manifest.txt)

Ok! Thank you for your reply. Does that mean that it's not possible at all to download using youtube-dl?

**Comment by marium0505** [comment]
> > Most videos on TV 2 Sumo is content protected using DASH Content Protection using Microsoft PlayReady (from what I could find):
> > https://docs.microsoft.com/en-us/playready/specifications/mpeg-dash-playready
> > Attached the content of the MPD file for the video you're linking to (changed it to .txt as Github didn't support .mpd files):
> > [manifest.txt](https://github.com/ytdl-org/youtube-dl/files/4499063/manifest.txt)
> 
> Ok! Thank you for your reply. Does that mean that it's not possible at all to download using youtube-dl?

They not going to circumvent DRM protection. So yeah, from what I understand, is it not going to be possible at all to download (at least that video) with Youtube-DL.
