### ISSUE TITLE
[Pluralsight] How can i only accept download with specific parameters ?.

### ISSUE THREAD

**Issue by nandaborneo** [ytdl-org/youtube-dl#24861]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

So, I have found that download link from pluralsight have different download speed.
Here what I found
first link : [First_link](https://vid21.pluralsight.com/clips/resolution/ed026dbb-24b7-4aa6-9d8d-cf41adde4087/current/mp4/1280x720.mp4?-Zfmb66ZAKN3V2GwyU0DXMpIg1BO3Fro_VoPorddaalrN62vqrcTH_b1kH0KZact0HdpMTUBViOg_RqnqkTckiJpj0iR680VKYYC6XjFMOKynIt5-YVmYQxV8Ez3d6wxuDpNi181vG1aH9yUSZX2KjJlAlpizYAyQtAD7lgOpiX4WnYGKL-WTyz0w90W)
With that kind download link, I have found that maks download speed is only between 10-32 kb/sec

But when I get download link like this : [second_link](https://vid5.pluralsight.com/expiretime=1587234586/d9f477bd57a4e3aba18a4547212a3972/clips/resolution/cab1c576-ca01-47be-83c7-551ebc2e39e2/current/mp4/1280x720.mp4)
The download speed is normal at 5 Mb/sec.

**Comment by zackmark29** [comment]
Actually you could try to download via idm.

Just put the command --get-url
it will catch the direct link and you can paste it to IDM

**Comment by nandaborneo** [comment]
> Actually you could try to download via idm.
> 
> Just put the command --get-url
> it will catch the direct link and you can paste it to IDM

Nice info, but then how can I get the file name, because the download link doesn't show it.
