### ISSUE TITLE
What does filsystem caching do on Youtube-dl?

### ISSUE THREAD

**Issue by YousufSSyed** [ytdl-org/youtube-dl#24867]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I noticed that the parameter `--no-cache-dir` "Disables filesystem caching." What does filesystem caching do for Yotube-dl?

**Comment by dstftw** [comment]
Unsuprisingly provides cache mechanism.
