### ISSUE TITLE
Please add support for RMC Story

### ISSUE THREAD

**Issue by skitt** [ytdl-org/youtube-dl#24862]
## Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2020.03.24**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs violate any copyrights
- [X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

Single video: https://rmcstory.bfmtv.com/titans-des-mers_2715/centrale-electrique-flottante_12262/

## Description

This is a Brightcove site, similar to RMC Découverte; the workaround described in https://github.com/ytdl-org/youtube-dl/issues/18595 works, the video in the link above is available from http://players.brightcove.net/5817780576001/default_default/index.html?videoId=6148809708001

**Comment by dirkf** [comment]
Site now replaced by https://www.rmcbfmplay.com/:
1. account needed
2. believed to serve only DRM-protected content.

If as a subscriber you can play a video at rmcbfmplay.com in the browser with DRM (EME) disabled, and are willing share your account, and would like the site to be supported, please open a new Site Support issue.
