### ISSUE TITLE
Forcing Youtube-dl to download YouTube file formats before they're officially listed by YT yields interesting results

### ISSUE THREAD

**Issue by stilett0** [ytdl-org/youtube-dl#24879]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Maybe not so much a bug as it is a feature?

I uploaded a 1440x1080@59.94 h264 mp4 to YouTube that had an AC3 audio track, stereo, 48000Hz/32-bit.

Once YouTube claimed it was done processing, I tested things by running youtube-dl.

In my first attempt, the following formats were available.
format code  extension  resolution note
139          m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
251          webm       audio only DASH audio  120k , webm_dash container, opus @160k (48000Hz)
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k (44100Hz)
278          webm       192x144    DASH video   95k , webm_dash container, vp9, 30fps, video only
160          mp4        192x144    DASH video  108k , mp4_dash container, avc1.4d400b, 30fps, video only
134          mp4        480x360    DASH video  139k , mp4_dash container, avc1.4d401e, 30fps, video only
242          webm       320x240    DASH video  220k , webm_dash container, vp9, 30fps, video only
133          mp4        320x240    DASH video  242k , mp4_dash container, avc1.4d400c, 30fps, video only
243          webm       480x360    DASH video  405k , webm_dash container, vp9, 30fps, video only
244          webm       640x480    DASH video  752k , webm_dash container, vp9, 30fps, video only
135          mp4        640x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 30fps, video only
247          webm       960x720    DASH video 1505k , webm_dash container, vp9, 30fps, video only
299          mp4        1440x1080  DASH video 2078k , mp4_dash container, avc1.64002a, 60fps, video only
136          mp4        960x720    DASH video 2310k , mp4_dash container, avc1.4d4016, 30fps, video only
302          webm       960x720    DASH video 2646k , webm_dash container, vp9, 60fps, video only
248          webm       1440x1080  DASH video 2646k , webm_dash container, vp9, 30fps, video only
298          mp4        960x720    DASH video 3465k , mp4_dash container, avc1.4d4016, 60fps, video only
137          mp4        1440x1080  DASH video 4331k , mp4_dash container, avc1.64001e, 30fps, video only
303          webm       1440x1080  DASH video 4410k , webm_dash container, vp9, 60fps, video only
18           mp4        480x360    360p  224k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 604.61KiB
22           mp4        960x720    720p  422k , avc1.64001F, mp4a.40.2@192k (44100Hz) (best)

Interesting that 299 mp4 1440x1080 was not yet listed, I tried to get it anyhow.

... and something downloaded!

After I ran youtube-dl -f 299, I got an mp4 that had a larger filesize than anything I'd tried to get thus far.
VLC claimed it was h264, 1440x1080, video-only file without a framerate listed. Filesize of 4.65 MB.

So I downloaded the best audio file I could find, and joined them together. This time VLC reported that the created file was 59.94 Hz.

About 10 minutes later, I tried again. This time, I had a 299 listed:

format code  extension  resolution note
139          m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
251          webm       audio only DASH audio  120k , webm_dash container, opus @160k (48000Hz)
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k (44100Hz)
278          webm       192x144    DASH video   95k , webm_dash container, vp9, 30fps, video only
160          mp4        192x144    DASH video  108k , mp4_dash container, avc1.4d400b, 30fps, video only
134          mp4        480x360    DASH video  207k , mp4_dash container, avc1.4d401e, 30fps, video only
242          webm       320x240    DASH video  220k , webm_dash container, vp9, 30fps, video only
133          mp4        320x240    DASH video  242k , mp4_dash container, avc1.4d400c, 30fps, video only
243          webm       480x360    DASH video  405k , webm_dash container, vp9, 30fps, video only
244          webm       640x480    DASH video  752k , webm_dash container, vp9, 30fps, video only
135          mp4        640x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 30fps, video only
247          webm       960x720    DASH video 1505k , webm_dash container, vp9, 30fps, video only
136          mp4        960x720    DASH video 2310k , mp4_dash container, avc1.4d4016, 30fps, video only
302          webm       960x720    DASH video 2646k , webm_dash container, vp9, 60fps, video only
248          webm       1440x1080  DASH video 2646k , webm_dash container, vp9, 30fps, video only
298          mp4        960x720    DASH video 3465k , mp4_dash container, avc1.4d4016, 60fps, video only
137          mp4        1440x1080  DASH video 4331k , mp4_dash container, avc1.64001e, 30fps, video only
303          webm       1440x1080  DASH video 4410k , webm_dash container, vp9, 60fps, video only
299          mp4        1440x1080  DASH video 5775k , mp4_dash container, avc1.64001e, 60fps, video only
18           mp4        480x360    360p  224k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 604.61KiB
22           mp4        960x720    720p  422k , avc1.64001F, mp4a.40.2@192k (44100Hz) (best)

So I downloaded the 299 file again.

This time I got a file that was a little less than half the size - 2.20 MB. VLC reported that it was  h264, 1440x1080, video-only file without a framerate listed - once again.

So I joined the MP4 to the best audio I could find. THIS time VLC reported the framerate as 60.029968 - unfortunately a little faster than my original source video.

Anyone have any ideas what happened here? Did I time things just right and download a Youtube-generated file here with a higher bitrate and original framerate as it was being processed? Why is it now generating a 60.029968 framerate at seemingly a lower bitrate?

**Comment by dstftw** [comment]
>Interesting that 299 mp4 1440x1080 was not yet listed, I tried to get it anyhow.

From your 1st listing:
>299 mp4 1440x1080 DASH video 2078k , mp4_dash container, avc1.64002a, 60fps, video only

In any case address all such questions to Youtube not here.
