### ISSUE TITLE
What does Youtube-dl use filesystem caching for?

### ISSUE THREAD

**Issue by YousufSSyed** [ytdl-org/youtube-dl#24888]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I noticed that the parameter --no-cache-dir "Disables filesystem caching." What does Yotube-dl use caching for?

(I had posted a question earlier but it was closed by dstftw who said "Unsuprisingly provides cache mechanism." but I want a more specific answer)

**Comment by danfiscus** [comment]
Via [the helpstring in the options file](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/options.py#L758):

> At the moment, only YouTube player files (for videos with obfuscated signatures) are cached, but that may change.

Sure enough, the cache for my youtube-dl has two 1KB .json files, each containing an array of integer values.

**Comment by dstftw** [comment]
Every extractor caches what it needs to cache. Ask more specific question and you'll get more specific answer.
