### ISSUE TITLE
Fix youtube-dl embedded options & update forbidden 403 pinned issue

### ISSUE THREAD

**Issue by elibroftw** [ytdl-org/youtube-dl#24891]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I use the embedded version of Youtube-dl and I find its options somewhat different and vague compared to command-line options. I recently had the 403 forbidden error and the [solution](https://github.com/ytdl-org/youtube-dl/issues/23638) says to use `--rm-cache-dir` but what is the corresponding embedded way? It took some time to figure it out: the "rm-cache-dir" has the alternative solution of "cachedir: False" but the language used in the [options description](https://github.com/ytdl-org/youtube-dl/blob/3e4cedf9e8cd3157df2457df7274d0c842421945/youtube_dl/YoutubeDL.py#L137-L312) says "False to disable filesystem cache." I don't know about you but the meaning of remove and disable is not the same. You should really update that post to include the embedded way of fixing the problem, it would've saved me a lot of time. It would also be beneficial to not lock the pinned post so that people don't create a new issue. That's just one problem (dual meanings/descriptions).

Also [this](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/options.py#L762) takes up 3 lines instead of 2.

What I would really appreciate is a) if each of these options descriptions specified the type of the option. E.g. `keepvideo (bool): Keep the video file after post-processing`. A developer should not have to make assumptions or infer what the type will be. It's not a thinking heavy task so I'd appreciate it. Secondly, you should also include the command line alternative in the description so a developer knows the corresponding command-line option.

**Comment by dstftw** [comment]
You don't need to include this in embedded code in the first place. Running it once from CLI is enough.

**Comment by elibroftw** [comment]
What do you mean by "You don't need to include this in embedded code in the first place. Running it once from CLI is enough"? I swear you didn't even read what I said. 
I use the embedded version youtube-dl and I included it because I shouldn't have to spend that much time to fix the issue. At least fix the options' descriptions instead of closing the issue and giving a vague answer that I don't even understand.

**Comment by dstftw** [comment]
Again: do not use `cachedir: False`, this is **not** an alternative solution as this disables caching **completely** with corresponding consequences. And again: running `--rm-cache-dir` **once from CLI is enough** to get this fixed.
