### ISSUE TITLE
Possible to download audio before video when formats are incompatible?

### ISSUE THREAD

**Issue by clampak** [ytdl-org/youtube-dl#24898]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

When youtube-dl downloads incompatible audio and video formats to be merged into a single mkv, it always downloads the video first.  Is it possible to download the audio first?

**Comment by dstftw** [comment]
No.
