### ISSUE TITLE
Fix Options Descriptions

### ISSUE THREAD

**Issue by elibroftw** [ytdl-org/youtube-dl#24892]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

What I really wanted to bring light to: The state of the embedded options descriptions. 
What I would really appreciate first off is if each of these options descriptions specified the type of the option. E.g. `keepvideo (bool): Keep the video file after post-processing`. A developer should not have to make assumptions or infer what the type will be. It's not a thinking heavy task so I'd appreciate it. Secondly, you should also include the command line alternative in the description so a developer knows the corresponding command-line option.

This next part is a criticism of you.

Please stop locking conversations left and right with an iron fist, you're wasting your own time (and the time ofo others). You locked my old thread because of the *non-important* part of it and your comments were not helpful at all! (I know what the cachedir does but obviously that's the only way for me to fix the problem). You provided the CLI solution the 403 Forbidden error but not the *embedded solution*. It's not enough because you are in charge of the youtube-dl and the README.md gives instructions to use youtube-dl in an embedded fashion. If you don't to support the embedded option, you could've said you don't care about the embedded version or that it's not a priority, that you'd work on it later, or use subprocess instead. Don't just provide a comment of no value.

**Comment by dstftw** [comment]
You can't specify the type for each option since most of them may accept different types and this is explained for each option in particular. For the rest PRs welcome I don't plan to spend time on this any soon.
Are you trolling or what? Again: you don't need the embedded solution for one-time option and there is no such option for that reason.
