### ISSUE TITLE
Crunchyroll subtitles (old format) decryption is broken

### ISSUE THREAD

**Issue by anidl** [ytdl-org/youtube-dl#24900]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello. Recently Crunchyroll changed encryption for their subtitles for RPC api, so decryption will always fail.

Code fragment:
https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/crunchyroll.py#L272

**Comment by Kcchouette** [comment]
No problem on my side, maybe verbose log will be more helpful...

**Comment by jsonn** [comment]
When getting the normal HTML frontend page, look for `"subtitles":`. It is followed by a JSON encoded array of subtitle entries with a language/title field and and an URL field. If you load the URL, you directly get the ASS version of the subtitle for that language. It doesn't seem to require anything special beyond extracting the URL and maybe logging in originally.
