### ISSUE TITLE
Add option to set Log level between: Info or debug

### ISSUE THREAD

**Issue by cfreds** [ytdl-org/youtube-dl#24911]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
Can you please add the option to set the log level between: info, debug, 
This can be usefull, because the logs can be more small, if we set only "info" and not by default actual "debug".

**Actual / Log level debug:**
`[download]  89.5% of 227.96MiB at 48.21MiB/s ETA 00:00
[download]  91.2% of 227.96MiB at 48.03MiB/s ETA 00:00
[download]  93.0% of 227.96MiB at 48.39MiB/s ETA 00:00
[download]  94.8% of 227.96MiB at 48.25MiB/s ETA 00:00
[download]  96.5% of 227.96MiB at 48.33MiB/s ETA 00:00
[download]  98.3% of 227.96MiB at 48.72MiB/s ETA 00:00
[download] 100.0% of 227.96MiB at 49.09`

**Future option, with log level info:**
`2020/04/20 14:36:08 INFO  : FileVideo.mp4: Copied (new)
2020/04/20 14:36:08 INFO  : 
Transferred:   	   96.294M / 96.294 MBytes, 100%, 20.851 MBytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         4.6s`

I hope you can add this feature in the future!

**Comment by dstftw** [comment]
This is already output on a single line. You either using `--newline` or your shell does not handle carriage return properly.
