### ISSUE TITLE
Get playlist name on Youtube

### ISSUE THREAD

**Issue by DGrv** [ytdl-org/youtube-dl#24918]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I was searching to be able to get the name of a youtube playlist.
I could get it by several lines of codes that I could share here (using grep and sed) but it would be nice to have a option for this. A bit similar to `youtube-dl -e urlplaylist`.

**Comment by dstftw** [comment]
Output as JSON & parse JSON. No grep or sed nonsense is required.
