### ISSUE TITLE
Download Pluralsight Subtitles

### ISSUE THREAD

**Issue by ATHellboy** [ytdl-org/youtube-dl#24917]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I use this command for downloading course subtitles in Pluralsight:
> youtube-dl --username USERNAME --password PASSWORD --all-subs URL --skip-download

But I receive this :
```
[pluralsight:course] unity-shader-graph-introduction: Downloading JSON metadata
[download] Downloading playlist: Introduction to Shader Graph in Unity
[pluralsight:course] playlist Introduction to Shader Graph in Unity: Collected 19 video ids (downloading 19 of them)
[download] Downloading video 1 of 19
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

But when I use this command, I can download videos:

>  youtube-dl --username USERNAME --password PASSWORD URL

What should I do to fix this problem ?

**Comment by jaimebl** [comment]
which python version you're using? We've been identified that issue happening with some particular python versions. Try using version 3.7 or 3.8.

Also `-all-subs` feature is not available on pluralsight yet, it's just downloading english subtitles.
I've opened a Pull Request for that but it hasn't been merged yet https://github.com/ytdl-org/youtube-dl/pull/24832

**Comment by ATHellboy** [comment]
@jaimebl It was 3.6.2 I just upgraded it to 3.8.2 but still the same problem.

What should I use instead of --all-subs ?

**Comment by jaimebl** [comment]
@ATHellboy With python 3.8.2 you shouldn't get that 403 error message(just tried myself same version), double check you're using that version in the logs and also that your account is not banned by logging in manually with the browser.

There's no way to get all subs currently, you can check out my pull request here if you want to try it https://github.com/ytdl-org/youtube-dl/pull/24832
However I wouldn't use `--all-subs` as it is now because you'll get `Too many requests` error message eventually and get banned, I'd better use `--write-sub --sub-lang en,es` instead and list the languages that you want to get

**Comment by ATHellboy** [comment]
@jaimebl I think you are right about the Python version which it uses.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://app.pluralsight.com/library/courses/unity-shader-graph-introduction/table-of-contents', '-u', 'PRIVATE', '-p', 'PRIVATE', '--write-sub', '--sub-lang', 'en,es', '--verbose']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref cp65001
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] unity-shader-graph-introduction: Downloading JSON metadata
[download] Downloading playlist: Introduction to Shader Graph in Unity
[pluralsight:course] playlist Introduction to Shader Graph in Unity: Collected 19 video ids (downloading 19 of them)
[download] Downloading video 1 of 19
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

How can I change it ? Although I don't know why the version is 3.4.4. (I use youtube-dl on Windows if it helps)

**Comment by jaimebl** [comment]
@ATHellboy I think for now, the easiest way to get this working is grabing the cookies as I list in this other comment:

https://github.com/ytdl-org/youtube-dl/issues/24895#issuecomment-617307358

**Comment by ATHellboy** [comment]
@jaimebl I just exported cookies by EditThisCookie which you mentioned in that comment and put it into text file and put it in the folder which I execute youtube-dl there.

Then using this commend :

> youtube-dl --cookies cookies.txt https://app.pluralsight.com/library/courses/unity-shader-graph-introduction/table-of-contents --write-sub --sub-lang en,es

But still there is an error:

```
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\__init__.py", line 441, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 419, in __init__
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2329, in _setup_opener
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\utils.py", line 2762, in load
  File "C:\Python\Python34\lib\http\cookiejar.py", line 2005, in _really_load
http.cookiejar.LoadError: 'cookies.txt' does not look like a Netscape format cookies file
```

What do I do wrong ?
It is because of this ? => 'cookies.txt' does not look like a Netscape format cookies file.

**Comment by jhondbv** [comment]
@ATHellboy  try to do this [https://github.com/ytdl-org/youtube-dl/issues/24895#issuecomment-617324141](url) , i had the same problem , if you see in your track you still use Phyton 3.4 with youtve-dl even you already installed Phyton 3.8

(your track ) 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://app.pluralsight.com/library/courses/unity-shader-graph-introduction/table-of-contents', '-u', 'PRIVATE', '-p', 'PRIVATE', '--write-sub', '--sub-lang', 'en,es', '--verbose']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref cp65001
[debug] youtube-dl version 2020.03.24
**[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362**

**Comment by jaimebl** [comment]
Ah god, yes you have to manually edit one line of those cookies, look for `_sdsat_Target` in your cookies file and add this after Subscription info: (Notice there's a tab at the beginning of the following snippet)
```
	InTerm:true|FullLibrary:true|Free:true|Trial:false|UserType:individual
```

So it will look something like this
```
app.pluralsight.com	FALSE	/	FALSE	1650564064	_sdsat_Target Subscription Info	InTerm:true|FullLibrary:true|Free:true|Trial:false|UserType:individual
```

**Comment by ATHellboy** [comment]
@jhondbv Thanks. It really helps. It works but just for the first time, I interrupted it then try it again and still get that 403 error.

@jaimebl Thanks, it works.
Just your last statement maybe confusing for some people.
Should put `InTerm:true|FullLibrary:true|Free:true|Trial:false|UserType:individual` in the next line after comma and put comma again at the end of this line.

**Comment by ATHellboy** [comment]
@jaimebl I get this error, what the hell:

```WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] 4dd0c174-ed1c-4968-b05f-72e01d1b5ed4-0: Waiting for 2 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

Although I downloaded all this course videos before.

**Comment by jaimebl** [comment]
@ATHellboy 😄 can you paste your full log?

**Comment by ATHellboy** [comment]
@jaimebl 
```
C:\Program Files (x86)\VideoDownloader>youtube-dl --cookies cookies.txt https://app.pluralsight.com/library/courses/unity-shader-graph-introduction/table-of-contents --write-sub --sub-lang en,es
[pluralsight:course] unity-shader-graph-introduction: Downloading JSON metadata
[download] Downloading playlist: Introduction to Shader Graph in Unity
[pluralsight:course] playlist Introduction to Shader Graph in Unity: Collected 19 video ids (downloading 19 of them)
[download] Downloading video 1 of 19
[pluralsight] de51c857-ca7d-49fa-8c14-4846faaee0b1-0: Downloading JSON metadata
[pluralsight] de51c857-ca7d-49fa-8c14-4846faaee0b1-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] de51c857-ca7d-49fa-8c14-4846faaee0b1-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] de51c857-ca7d-49fa-8c14-4846faaee0b1-0: Waiting for 4 seconds to avoid throttling
[pluralsight] de51c857-ca7d-49fa-8c14-4846faaee0b1-0: Downloading captions JSON
WARNING: es subtitles not available for 043bd1cb-098d-4e32-a0f8-fdafd5e66eee
[info] Writing video subtitles to: Course Overview-043bd1cb-098d-4e32-a0f8-fdafd5e66eee.en.srt
[download] Destination: Course Overview-043bd1cb-098d-4e32-a0f8-fdafd5e66eee.mp4
[download] 100% of 3.95MiB in 00:04
[download] Downloading video 2 of 19
[pluralsight] 4dd0c174-ed1c-4968-b05f-72e01d1b5ed4-0: Downloading JSON metadata
[pluralsight] 4dd0c174-ed1c-4968-b05f-72e01d1b5ed4-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 4dd0c174-ed1c-4968-b05f-72e01d1b5ed4-0: Downloading mp4-high-widescreen viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] 4dd0c174-ed1c-4968-b05f-72e01d1b5ed4-0: Waiting for 2 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jaimebl** [comment]
@ATHellboy Are you able to get to the website with your browser?

**Comment by ATHellboy** [comment]
@jaimebl Yup

**Comment by jhondbv** [comment]
@ATHellboy try adding this argument on your youtube-dl command 

> -f "best[height<=720]/worst[height>720]"

something like : >youtube-dl --cookies cookies.txt --write-sub --sub-lang en,es --verbose -f "best[height<=720]/worst[height>720]" https://app.pluralsight.com/library/courses/unity-shader-graph-introduction

**Comment by jaimebl** [comment]
@ATHellboy You're probably having some issue with your authentication, if you try without the cookies parameter I bet you will get the same log response.

`youtube-dl https://app.pluralsight.com/library/courses/unity-shader-graph-introduction/table-of-contents --write-sub --sub-lang en,es --verbose`

Try setting your cookies again 🤔
