### ISSUE TITLE
Netflix

### ISSUE THREAD

**Issue by ChildishGiant** [ytdl-org/youtube-dl#24921]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones **There is an issue but it's locked**

## Example URLs

- Single video: https://www.netflix.com/watch/60027393

## Description

#1564 Exists but is locked. Netflix appears to be using video blobs so it should be possible to add support with existing infrastructure. Credentials will be needed but cookies appear to work.

**Comment by jzbor** [comment]
Could someone please explain, why this thread as well as #1564 got closed/very heavily moderated without any hints on whether this will/can be implemented or why this topic is so highly moderated at all?

**Comment by zackmark29** [comment]
> Could someone please explain, why this thread as well as #1564 got closed/very heavily moderated without any hints on whether this will/can be implemented or why this topic is so highly moderated at all?

because they don't want to do that. It's a big company and it's DRM Protected.
Try to search about DRM Protected

**Comment by NSExceptional** [comment]
@zackmark29 accoeding to that issue, there is (or was) a working Netflix downloader. No contributors have replied to that thread in a while and that makes requests like this being closed without reason really fishy.
