### ISSUE TITLE
Status errors in Youtube-DLG

### ISSUE THREAD

**Issue by jmack789** [ytdl-org/youtube-dl#24922]
## Checklist

- [ ] I'm reporting a broken site support issue
- [y ] I've verified that I'm running youtube-dl version **2020.03.24**
- [y ] I've checked that all provided URLs are alive and playable in a browser
- [y ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ y] I've searched the bugtracker for similar bug reports including closed ones
- [y ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
I just discovered this. Everything seems to work as expected but all recent downloads give a status error. The downloads seem OK, but I can't figure out how to see the audio bitrate. Properties shows bitrate of zero. I have mp3 128 copies of these, but I was hoping to get higher rez copies.
Why am I getting these errors?

![Youtube-DLG error 2020-04-21 102034](https://user-images.githubusercontent.com/64091496/79884589-5966eb80-83c3-11ea-9046-8c8ad39abc9b.jpg)

**Comment by HewwoCraziness** [comment]
If the issue isn't reproducible from the command line `youtube-dl,` it's likely to be a defect with your frontend app. Consider reporting the issue [on the GUI's GitHub page](https://github.com/MrS0m30n3/youtube-dl-gui) instead. Good luck! :)
