### ISSUE TITLE
Pornhubpremium (and regular pornhub maybe) Pornstar page and playlist not working

### ISSUE THREAD

**Issue by Agent076537** [ytdl-org/youtube-dl#24939]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.03.24**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\M>youtube-dl.exe -f best https://www.pornhubpremium.com/pornstar/gabbie-carter -o C:/PH/Pornstar/GabbieCarter/%(uploader)s/Uploaded/%(title)s-%(id)s-%(duration)s.%(ext)s -i --restrict-filenames --write-description --write-info-json --add-metadata --embed-thumbnail --download-archive C:\archive.txt --cookies "C:\Users\M\Downloads\cookies.txt" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', 'https://www.pornhubpremium.com/pornstar/gabbie-carter', '-o', 'C:/PH/Pornstar/GabbieCarter/%(uploader)s/Uploaded/%(title)s-%(id)s-%(duration)s.%(ext)s', '-i', '--restrict-filenames', '--write-description', '--write-info-json', '--add-metadata', '--embed-thumbnail', '--download-archive', 'C:\\archive.txt', '--cookies', 'C:\\Users\\M\\Downloads\\cookies.txt', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[PornHubPagedVideoList] pornstar/gabbie-carter/videos: Downloading page 1
[download] Downloading playlist: pornstar/gabbie-carter/videos
[PornHubPagedVideoList] playlist pornstar/gabbie-carter/videos: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: pornstar/gabbie-carter/videos

```

## Description

For some reasons, some pornstars pages do not have a '/videos' page. Going to this URL comes up with an error about the page not existing. It seems that the pornstar name acts as the videos page. To see the premium videos the URL looks like 
https://www.pornhubpremium.com/pornstar/gabbie-carter?premium=1&o=mr 

Putting this into youtube-dl results in it trying to look for /videos again and then failing

I tried to work around by clciking play all as playlist then download the playlist but it just downloads the first one and not the rest even with --yes-playlist .

The output for that is 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', 'https://www.pornhubpremium.com/view_video.php?viewkey=ph5e90c1c172d99&pkey=sys%3Apornstar%3A306792%3Amr%3A1%3Apremium%3A1', '-o', 'C:/PH/Pornstar/GabbieCarter/%(uploader)s/Uploaded/%(title)s-%(id)s-%(duration)s.%(ext)s', '-i', '--restrict-filenames', '--write-description', '--write-info-json', '--add-metadata', '--embed-thumbnail', '--download-archive', 'C:\\archive.txt', '--cookies', 'C:\\Users\\M\\Downloads\\cookies.txt', '-v', '--yes-playlist']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[PornHub] ph5e90c1c172d99: Downloading pc webpage
[PornHub] ph5e90c1c172d99: Downloading m3u8 information
[PornHub] ph5e90c1c172d99: Downloading m3u8 information
[PornHub] ph5e90c1c172d99: Downloading m3u8 information
[PornHub] ph5e90c1c172d99: Downloading m3u8 information
[PornHub] ph5e90c1c172d99: Downloading m3u8 information
WARNING: There's no description to write.
[info] Writing video description metadata as JSON to: C:\PH\Pornstar\GabbieCarter\Primal_s_Edging_Handjobs_and_Blowjobs\Uploaded\2_Gorgeous_Cum_Hungry_Babes_Share_Cock_and_Cum_-_Alex_Coal_Gabbie_Carter-ph5e90c1c172d99-1368.info.json
[PornHub] ph5e90c1c172d99: Downloading thumbnail ...
[PornHub] ph5e90c1c172d99: Writing thumbnail to: C:\PH\Pornstar\GabbieCarter\Primal_s_Edging_Handjobs_and_Blowjobs\Uploaded\2_Gorgeous_Cum_Hungry_Babes_Share_Cock_and_Cum_-_Alex_Coal_Gabbie_Carter-ph5e90c1c172d99-1368.jpg
[debug] Invoking downloader on 'https://dv2.phprcdn.com/videos/202004/10/302297312/1080P_4000K_302297312.mp4?ttl=1587553227&ri=51200000&rs=400000&hash=8c5a931f4d25f450467783915b363604'
[download] Destination: C:\PH\Pornstar\GabbieCarter\Primal_s_Edging_Handjobs_and_Blowjobs\Uploaded\2_Gorgeous_Cum_Hungry_Babes_Share_Cock_and_Cum_-_Alex_Coal_Gabbie_Carter-ph5e90c1c172d99-1368.mp4
[download] 100% of 362.69MiB in 03:27
[ffmpeg] Adding metadata to 'C:\PH\Pornstar\GabbieCarter\Primal_s_Edging_Handjobs_and_Blowjobs\Uploaded\2_Gorgeous_Cum_Hungry_Babes_Share_Cock_and_Cum_-_Alex_Coal_Gabbie_Carter-ph5e90c1c172d99-1368.mp4'
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\PH\Pornstar\GabbieCarter\Primal_s_Edging_Handjobs_and_Blowjobs\Uploaded\2_Gorgeous_Cum_Hungry_Babes_Share_Cock_and_Cum_-_Alex_Coal_Gabbie_Carter-ph5e90c1c172d99-1368.mp4" -c copy -metadata "date=20200410" -metadata "title=2 Gorgeous Cum Hungry Babes Share Cock and Cum - Alex Coal & Gabbie Carter" -metadata "purl=https://www.pornhubpremium.com/view_video.php?viewkey=ph5e90c1c172d99&pkey=sys%3Apornstar%3A306792%3Amr%3A1%3Apremium%3A1" -metadata "artist=Primal's Edging Handjobs and Blowjobs" "file:C:\PH\Pornstar\GabbieCarter\Primal_s_Edging_Handjobs_and_Blowjobs\Uploaded\2_Gorgeous_Cum_Hungry_Babes_Share_Cock_and_Cum_-_Alex_Coal_Gabbie_Carter-ph5e90c1c172d99-1368.temp.mp4"
[atomicparsley] Adding thumbnail to "C:\PH\Pornstar\GabbieCarter\Primal_s_Edging_Handjobs_and_Blowjobs\Uploaded\2_Gorgeous_Cum_Hungry_Babes_Share_Cock_and_Cum_-_Alex_Coal_Gabbie_Carter-ph5e90c1c172d99-1368.mp4"
[debug] AtomicParsley command line: AtomicParsley "C:\PH\Pornstar\GabbieCarter\Primal_s_Edging_Handjobs_and_Blowjobs\Uploaded\2_Gorgeous_Cum_Hungry_Babes_Share_Cock_and_Cum_-_Alex_Coal_Gabbie_Carter-ph5e90c1c172d99-1368.mp4" --artwork "C:\PH\Pornstar\GabbieCarter\Primal_s_Edging_Handjobs_and_Blowjobs\Uploaded\2_Gorgeous_Cum_Hungry_Babes_Share_Cock_and_Cum_-_Alex_Coal_Gabbie_Carter-ph5e90c1c172d99-1368.jpg" -o "C:\PH\Pornstar\GabbieCarter\Primal_s_Edging_Handjobs_and_Blowjobs\Uploaded\2_Gorgeous_Cum_Hungry_Babes_Share_Cock_and_Cum_-_Alex_Coal_Gabbie_Carter-ph5e90c1c172d99-1368.temp.mp4"

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by Agent076537** [comment]
that wasn't an issue for the initial request to support pornhubpremium...
As this same issue (looking for /videos that doesn't exist) is applicable to pornhub.com also, no account credentials are not required.
