### ISSUE TITLE
Pluralsight.com HTTP Error 403: Forbidden (caused by HTTPError())

### ISSUE THREAD

**Issue by totallycyber** [ytdl-org/youtube-dl#24942]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--rm-cache-dir', '--sleep-interval', '45', '--format', 'mp4', 'https://app.pluralsight.com/library/courses/getting-started-microsoft-teams-office-365-groups-administration', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
Removing cache dir C:\Users\Chint/.cache\youtube-dl ..
[pluralsight:course] getting-started-microsoft-teams-office-365-groups-administration: Downloading JSON metadata
[download] Downloading playlist: Getting Started with Microsoft Teams and Office 365 Groups Administration
[pluralsight:course] playlist Getting Started with Microsoft Teams and Office 365 Groups Administration: Collected 112 video ids (downloading 112 of them)
[download] Downloading video 1 of 112
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

I am unable to download videos from Pluralsight.com. It works sometimes. And sometimes it doesn't. I've tried in Command Prompt, PowerShell, and even used Chocolately and I get the **HTTP Error 403: Forbidden (caused by HTTPError())** error. I can confirm my account is not blocked. I am running the latest version of youtube-dl. I've seen all prior posts and they all say "duplicate" but no resolution is available. Please confirm if the issue is being worked on or it's not fixable?

**Comment by victoroliveirab** [comment]
I was running into the same issue. Created a virtualenv w/ Python 3.7 as new interpreter, installed youtube-dl via pip and worked like a charm

**Comment by totallycyber** [comment]
> I was running into the same issue. Created a virtualenv w/ Python 3.7 as new interpreter, installed youtube-dl via pip and worked like a charm

Did this too. Didn't work.
