### ISSUE TITLE
Pornhub.com - pornstar with no '/videos' page not downloading

### ISSUE THREAD

**Issue by Agent076537** [ytdl-org/youtube-dl#24949]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.03.24**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', 'https://www.pornhub.com/pornstar/gabbie-carter', '-o', 'C:/PH/Pornstar/GabbieCarter/%(uploader)s/Uploaded/%(title)s-%(id)s-%(duration)s.%(ext)s', '-i', '--restrict-filenames', '--write-description', '--write-info-json', '--add-metadata', '--embed-thumbnail', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[PornHubPagedVideoList] pornstar/gabbie-carter/videos: Downloading page 1
[download] Downloading playlist: pornstar/gabbie-carter/videos
[PornHubPagedVideoList] playlist pornstar/gabbie-carter/videos: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: pornstar/gabbie-carter/videos
```

## Description

It appears some pornstars do not have a valid page at /videos therefore the videos of them are unable to be downloaded. e.g. pornhub.com/pornstar/gabbie-carter/videos does not exist but her videos are listed at pornhub.com/pornstar/gabbie-carter

**Comment by Agent076537** [comment]
@twaddington  hey, sorry to both you again...
what is this guy's problem ?

https://github.com/ytdl-org/youtube-dl/issues/24950

It's clearly a playlist....

**Comment by Hrxn** [comment]
The URL starts with `https://www.pornhub.com/view_video.php?viewkey=<key>`, so it's probably not a playlist.

**Comment by twaddington** [comment]
> what is this guy's problem ? &mdash;@ @Agent076537 

Hah, yeah. If I'm being generous, as the seemingly sole maintainer, he's overwhelmed by the amount of activity on this project and is struggling to keep up.

Then again he might just be a bit of an asshole.

**Comment by twaddington** [comment]
@Hrxn the url has a `pkey` argument in the URL, which is a playlist key.

**Comment by Hrxn** [comment]
I'm aware. But see issue #11594, for example.

Playlists, according to `https://www.pornhub.com/playlists`, have a URL format of `https://www.pornhub.com/playlist/<playlist-id>`.

I don't think that support for a `pkey` argument is supported yet..
Has to be checked for `_VALID_URL` somewhere in `pornhub.py`.

> Hah, yeah. If I'm being generous, as the seemingly sole maintainer, he's overwhelmed by the amount of activity on this project and is struggling to keep up.

Yes.

**Comment by twaddington** [comment]
> I don't think that support for a `pkey` argument is supported yet.. &mdash; @Hrxn 

Right. That would be the fix for https://github.com/ytdl-org/youtube-dl/issues/24950.

**Comment by fyjjlrf** [comment]
_操_逼_视频,你懂的  [点击进入](https://www.scc5.top/)

_操_逼_视频,你懂的  [点击进入](https://www.scc8.top/)

      
脚苫先筛继度讲回邓淄筒趟车聘珊囱嚼梢
