### ISSUE TITLE
No sound after converting YouTube site URL to mp4 with youtube-dl

### ISSUE THREAD

**Issue by pheanix-au** [ytdl-org/youtube-dl#24953]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
At Command Prompt window I typed:

youtube-dl  https://www.youtube.com/watch?v=6MyjFHd04R8

and the result was an mp4 video with NO sound.
What did I do wrong ?

**Comment by pheanix-au** [comment]
I don't understand 'closed' but no answer to my problem.

**Comment by ilike2burnthing** [comment]
```
WARNING!
IGNORING THE FOLLOWING TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE
```

**Comment by pheanix-au** [comment]
An obtuse answer with no coherent explanation is less than helpful.

**Comment by ilike2burnthing** [comment]
Not following clear instructions is less than helpful. Easily resolved though.
