### ISSUE TITLE
Funimation subtitles

### ISSUE THREAD

**Issue by joshbrown50** [ytdl-org/youtube-dl#24955]
## Checklist

- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

I've been trying to figure out how to download funimation videos with their subtitles. I've looked at other issues here saying that there are several different types of subtitle files for funimation, but I can't figure out how to download any of them. Is there a way that I can use youtube-dl to download any of the subtitle files or am I out of luck until someone adds that feature?

**Comment by Mevious** [comment]
There is an open issue for this #22027. I have a potential fix out for review, but I'm not sure what the chances are of a merge #24906. In the mean time you can either clone my branch or use the manual method mentioned in the related issue. I've only tried this in Chrome: Visit a video page, right click, inspect, network tab, refresh page, filter requests by "vtt" to find the subtitle url for download.
