### ISSUE TITLE
[youtube] Support for timestamp bookmarks

### ISSUE THREAD

**Issue by jmgomezpoveda** [ytdl-org/youtube-dl#24966]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

YouTube added last year a new functionality where if the description contains a list of timestamps, these are represented in the progress bar, as if it were a playlist within the video: https://www.coywolf.news/seo/google-video-segments/

Sample video: https://www.youtube.com/watch?v=RLWcYADoV84

Whereas it is possible to download the full video, the bookmarks information is lost. It would be great to have the possibility to download the segments as separate files as if it were downloading a playlist of separate files, maybe appending to the destination file name the description in the bookmark.

This may depend on https://github.com/ytdl-org/youtube-dl/issues/622

**Comment by dstftw** [comment]
`--add-metadata`.

**Comment by jmgomezpoveda** [comment]
That's very interesting, thanks! It doesn't split the video, but in VLC I can see the bookmarks and descriptions.

I guess if anyone is interested in splitting the segments into separate files they could do it with some postprocessing using ffmpeg.
