### ISSUE TITLE
How can I download/build the latest git version for Windows?

### ISSUE THREAD

**Issue by sofakng** [ytdl-org/youtube-dl#24979]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have Python 3.8.2 installed on my Windows 10 machine and I'm able to checkout the latest youtube-dl code from Git, but how do I run it?  Can I run __main__.py or is there a better way?

I know that Python code is typically interpreted (and not compiled) but there seems to some kind of build process used for youtube-dl?  How can I build the latest Git version for Windows?

EDIT: More specifically, I'm trying to test a pull request that might fix the TruTV problems (https://github.com/ytdl-org/youtube-dl/pull/24466).

**Comment by dstftw** [comment]
You don't need to build anything for that. Run from sources.

**Comment by sofakng** [comment]
OK - Thanks.  How do I run it from sources?  (python3 __main__.py) ?

**Comment by dstftw** [comment]
Read developer instructions.
