### ISSUE TITLE
soundcloud not working at all

### ISSUE THREAD

**Issue by singulararmchair** [ytdl-org/youtube-dl#24980]
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.03.24**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

 youtube-dl -v https://soundcloud.com/crackmagazine/crack-mix-351-sui-zhen
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://soundcloud.com/crackmagazine/crack-mix-351-sui-zhen']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.10 (CPython) - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-86910-g797c232-tessus
[debug] Proxy map: {}
[soundcloud] crackmagazine/crack-mix-351-sui-zhen: Downloading info JSON
ERROR: Unable to download JSON metadata: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2728, in https_open
    req, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)

## Description

Every Soundcloud link I've tried gives me the same error. Bandcamp links also do this. Youtube videos work fine (just successfully downloaded a random vid).

**Comment by LegitSoulja** [comment]
Apparently, Youtube is no longer working atleast for most videos  that are now giving access denied HTTP responses.

**Comment by willbeaufoy** [comment]
Is this still a problem? I'm having no issues downloading the soundcloud link you provided, or youtube videos.

**Comment by singulararmchair** [comment]
yes. i reinstalled youtube-dl, still the same problem.
i even upgraded to python2.7, no dice

another try:

##


youtube-dl -v https://soundcloud.com/the-trilogy-tapes/ttt-nts-060420-with-waswaas
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://soundcloud.com/the-trilogy-tapes/ttt-nts-060420-with-waswaas']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.12 (CPython) - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-86910-g797c232-tessus
[debug] Proxy map: {}
[soundcloud] the-trilogy-tapes/ttt-nts-060420-with-waswaas: Downloading info JSON
ERROR: Unable to download JSON metadata: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2728, in https_open
    req, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)

**Comment by willbeaufoy** [comment]
Well it looks like the error is due to your openSSL version. Which version are you running? Run this in your terminal:

`python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"`

**Comment by singulararmchair** [comment]
OpenSSL 1.1.1d  10 Sep 2019

**Comment by LegoChicken** [comment]
Same problem.
 python -c "import ssl; print(ssl.OPENSSL_VERSION)"            OpenSSL 1.1.1  11 Sep 2018
 python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"           OpenSSL 1.1.1  11 Sep 2018

I don't think it is openssl version.

**Comment by singulararmchair** [comment]
To be clear, downloading from SoundCloud worked fine for me just a few weeks ago. Could it be that something has changed on their end since then? This looks similar to the situation with .luac files constantly needing to be updated for VLC to play certain links.

**Comment by Scunkaneli** [comment]
I am having no problems downloading the soundcloud link you have provided with:
`[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362`

**Comment by willbeaufoy** [comment]
@singulararmchair are you able to run youtube-dlusing python3? Though if @LegoChicken has the same issue with the same SSL version then yes seems unlikely to be that.

**Comment by singulararmchair** [comment]
I don't think so. How would I attempt that? (or verify if it is the case?)

**Comment by willbeaufoy** [comment]
There's probably a few ways to change your default python version on mac, but I don't have one so I'm not sure. However what I do is to download the github repository using the 'clone or download' button on the main page, then `cd` into it and then run youtube-dl like this:

`python3 -m youtube_dl -v https://soundcloud.com/the-trilogy-tapes/ttt-nts-060420-with-waswaas`

And it should say Python version 3 instead of 2 in the debug log.

**Comment by singulararmchair** [comment]
I just tried that, still getting an error

##
`youtube-dl-master A$ python3 -m youtube_dl -v https://soundcloud.com/the-trilogy-tapes/ttt-nts-060420-with-waswaas
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://soundcloud.com/the-trilogy-tapes/ttt-nts-060420-with-waswaas']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - macOS-10.10.5-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-86910-g797c232-tessus
[debug] Proxy map: {}
[soundcloud] the-trilogy-tapes/ttt-nts-060420-with-waswaas: Downloading info JSON
ERROR: Unable to download JSON metadata: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))
  File "/Users/A/Downloads/youtube-dl-master/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Users/A/Downloads/youtube-dl-master/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/A/Downloads/youtube-dl-master/youtube_dl/utils.py", line 2726, in https_open
    return self.do_open(functools.partial(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1322, in do_open
    raise URLError(err)`


also tried with `--no-check-certificate ` 

##
` youtube-dl --no-check-certificate https://soundcloud.com/6amgroup/premiere-francesco-argentieri-lunacy-out-of-place
[soundcloud] 6amgroup/premiere-francesco-argentieri-lunacy-out-of-place: Downloading info JSON
ERROR: Unable to download JSON metadata: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))
`

**Comment by LegoChicken** [comment]
Still not working. Tried same as @singulararmchair :

youtube-dl -v https://soundcloud.com/the-trilogy-tapes/ttt-nts-060420-with-waswaas
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://soundcloud.com/the-trilogy-tapes/ttt-nts-060420-with-waswaas']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-96-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6-0ubuntu0.18.04.1, ffprobe 3.4.6-0ubuntu0.18.04.1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] the-trilogy-tapes/ttt-nts-060420-with-waswaas: Resolving id
[soundcloud] the-trilogy-tapes/ttt-nts-060420-with-waswaas: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 519, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2199, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by singulararmchair** [comment]
Fixed by upgrading to OS X 10.13.6. Was overdue anyway.
