### ISSUE TITLE
if output to stdout, it ignores --audio-format

### ISSUE THREAD

**Issue by CodingVoid** [ytdl-org/youtube-dl#24984]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -o "-" -v --audio-format opus "https://www.youtube.com/watch?v=6TWJaFD6R2s" > test
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '-', '-v', '--audio-format', 'opus', 'https://www.youtube.com/watch?v=6TWJaFD6R2s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Linux-5.6.6-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[youtube] 6TWJaFD6R2s: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r1---sn-h0jeln7r.googlevideo.com/videoplayback?expire=1587807133&ei=Pa-jXrPoNqqc-gbcjbygDA&ip=2a02%3A908%3A418%3A9360%3Ac74d%3Affa3%3A8113%3Ae582&id=o-ANDGcUQVBI-9gBsRWkF95zfrJvnp5zbtcWSfzfE7jFgG&itag=22&source=youtube&requiressl=yes&mh=My&mm=31%2C29&mn=sn-h0jeln7r%2Csn-h0jeener&ms=au%2Crdu&mv=m&mvi=0&pl=44&initcwndbps=1596250&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=106.231&lmt=1579249099231225&mt=1587785429&fvip=1&c=WEB&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AJpPlLswRAIgE1cLoPXocKlX4k0GwLsndiEh8whcY9TxhlUXRYLZhlkCIDrp46Cb4j1zZVbF9KUdln4l92L3FuERgWpNXxttZix_&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRgIhAK2pqlx8zrYnU-YphC3js8apkc7qyFtRz1od2v3PgpMoAiEA4uzNGY63OxsUHiG8FgZn63xvqTryUEF594EjFme3WrM%3D'
[download] Destination: -
[download] 100% of 7.61MiB in 00:01
```

## Description

If using the command above to output to stdout, I get an mpeg-4 file (no opus audio, although I specified it with --audio-format).
If I use the exact same command without: -o "-"   (so no output to stdout), it works as expected and it writes a .webm file with opus audio encoding.
I am a little confused since I thought if I output to stdout I would get the same file as if not.

**Comment by dstftw** [comment]
No single media file with opus audio exists.

**Comment by CodingVoid** [comment]
wait what???
I was expecting to get an .webm file with opus audio, which exists for that video according to youtube-dl --list-formats.
