### ISSUE TITLE
--match-filter does not work if output to stdout

### ISSUE THREAD

**Issue by CodingVoid** [ytdl-org/youtube-dl#24991]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -o "-" --match-filter "acodec = opus" "https://www.youtube.com/watch?v=6TWJaFD6R2s"
[youtube] 6TWJaFD6R2s: Downloading webpage
[download] #Stereo: Left and Right Stereo Sound Test does not pass filter acodec = opus, skipping ..
```

# The same without output to stdout:
```
youtube-dl -o "test.webm" --match-filter "acodec = opus" "https://www.youtube.com/watch?v=6TWJaFD6R2s"
[youtube] 6TWJaFD6R2s: Downloading webpage
[download] Destination: test.f313.webm
[download] 100% of 81.01MiB in 00:07
[download] Destination: test.f251.webm
[download] 100% of 1.72MiB in 00:00
[ffmpeg] Merging formats into "test.webm"
Deleting original file test.f313.webm (pass -k to keep)
Deleting original file test.f251.webm (pass -k to keep)
```

## Description

If I output to stdout, then --match-filter does not seem to work. 
But if I do the same with output to a file like shown in the second command it works as expected.

**Comment by dstftw** [comment]
There is no single file file media matching this filter.

**Comment by CodingVoid** [comment]
I really don't see how you come to this conclusion, but anyway I did what I could to report this bug (if it is even a bug, maybe it is wanted behaviour, who knows...).
