### ISSUE TITLE
Is there support for Python3.8? I have got an error because I don't have Python3.7.

### ISSUE THREAD

**Issue by SenaidaHdez** [ytdl-org/youtube-dl#24992]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

I got the error below and I wonder if there is support for Python3.8 or if I have to install 3.7. I would like to change the interpreter that youtube-dl is using. Is that possible?
```
bash: /usr/local/bin/youtube-dl: /usr/bin/python3.7: bad interpreter: No such file or directory
```

**Comment by dstftw** [comment]
Any 3.2+ python is supported.

**Comment by a-dpq** [comment]
I'm also having this problem. I have Python 3.8.10 installed, and I get the following error when I run youtube-dl:

`-bash: /opt/miniconda3/bin/youtube-dl: /opt/miniconda3/bin/python3.7: bad interpreter: No such file or directory`
