### ISSUE TITLE
Youtube - Access is denied

### ISSUE THREAD

**Issue by LegitSoulja** [ytdl-org/youtube-dl#24998]
I've made a program that plays audio from url streams, instead of downloading. It was all working fine until yesterday it stopped working, now **some** streams I cannot play . Could it be that Youtube has blocked/limited me from playing streams? I've also tried using proxies, but non of them worked.

It has been 24h since I've been denied access of streams, and doesn't seem this issue will go away. Anyone got ideas why this may be happening, or ways to prevent? Some may say "I'm not using cookies", but it worked fine without until now.

**Comment by thegreatestminer** [comment]
Find something that gives you an error, then do it again with `--verbose`.

**Comment by LegitSoulja** [comment]
@thegreatestminer Here's the thing, I get no error with youtube-dl, until I get the stream link provided and try playing from it.

However, he's one example
```
.[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'bestaudio', '-g', 'https://www.youtube.com/watch?v=R1BtQliPi7o']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
.[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {'no': '192.168.99.100'}
..
https://r2---sn-5uaeznkz.googlevideo.com/videoplayback?expire=1587872625&ei=Ea-kXr-lDqWckATjpbWIAw&ip=2600%3A8807%3Aba00%3A198e%3A599c%3Adad6%3A8d07%3A9980&id=o-AMZuKK4lp8ctTimfZ-qIKZCkir6Pu36Mg2xGKNgGBjkV&itag=251&source=youtube&requiressl=yes&mh=GV&mm=31%2C26&mn=sn-5uaeznkz%2Csn-p5qlsnz6&ms=au%2Conr&mv=m&mvi=1&pl=35&initcwndbps=1825000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=2777344&dur=170.421&lmt=1577350630075910&mt=1587850895&fvip=2&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRgIhAIO0DkD_dFLpWiJW7FwqZK-6h6fWBmGffLyxCbLUB8zQAiEAsze6CcGFzXkqFLzst9FDgkxoBK6dcJRIm0Mxt8BH9wg%3D&sig=y=wJBrTX8_cw22lfYJ_Jojlye=dKth66Fy5kMUlePcA8iCQIC85l6P4s7xeTHxD1SlhmA2ONNZ404JVlo6Tsj_rgIxeLgIQRwpLs&ratebypass=yes
```

**Comment by LegitSoulja** [comment]
Noting again, only some streams I can play, bust most of them will end up returning an Access denied from my audio client. When visiting the link in browser, this will be shown 
![er](https://user-images.githubusercontent.com/4976824/80291613-08d1f400-871d-11ea-8c9e-8408d47cd5b2.PNG)

**Comment by LegitSoulja** [comment]
After looking through other issues, I finally found a solution that fixed it!

For anyone that comes across this issue in the future, use `--rm-cache-dir`
