### ISSUE TITLE
masterclass.com / brightcove support request

### ISSUE THREAD

**Issue by whitespring** [ytdl-org/youtube-dl#24993]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

URLs most likely expired, therefore the m3u8 contents below.

- Single video: https://www.masterclass.com/classes/annie-leibovitz-teaches-photography/chapters/getting-started-c22aa2e0-3086-42b6-9050-62cd4f81f439?action=preview&controller=chapters&course_id=annie-leibovitz-teaches-photography&id=getting-started-c22aa2e0-3086-42b6-9050-62cd4f81f439&logged_in=true
- Playlist: https://www.masterclass.com/classes/annie-leibovitz-teaches-photography/enrolled

## Description

WRITE DESCRIPTION HERE

Here are the stream URLs. Audio and Video are separate and in different qualities available. 

masterManifest | 
https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/5344802162001/23138f29-454a-4440-b056-3750410a0a1b/10s/master.m3u8?fastly_token=NWVhZGFhMzBfNTRlMjI5NmYyOTUxNmNkZDVjOTgxNjg2ZTczMjcyYjFkMzJiMzBmZTczNDcyNTVjZjgwODdlNzFmNjNhY2JiOQ%3D%3D

mediaManifest | 
https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/5344802162001/23138f29-454a-4440-b056-3750410a0a1b/183bd1f6-cbf0-43be-82e9-5e4ee2f19dd0/10s/rendition.m3u8?fastly_token=NWVhYWRkYjZfYjBlMTMxNDFlZTkxMDRiNDMwN2U5MjIwY2JjMTJmYzhiNTcwOThkMjMwMGQxNzQxMzAyMTZhMmE2NjRkNjJkYQ%3D%3D

here the contents of the manifest files: 
rendition.m3u8:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:10
#EXTINF:10.000,
https://house-fastly-signed-us-east-1-prod.brightcovecdn.com/media/v1/hls/v4/clear/5344802162001/23138f29-454a-4440-b056-3750410a0a1b/183bd1f6-cbf0-43be-82e9-5e4ee2f19dd0/5x/segment0.ts?fastly_token=NWVhYTA1NDRfMTI0YmRlZDY4MWI0YTk5Y2I1NzRkNDE0Y2IxMzczYzZlZjQzOTA3Y2FkMDc4YjIyZTZmOGU2MWMwMWJiZjFhYl8vL2hvdXNlLWZhc3RseS1zaWduZWQtdXMtZWFzdC0xLXByb2QuYnJpZ2h0Y292ZWNkbi5jb20vbWVkaWEvdjEvaGxzL3Y0L2NsZWFyLzUzNDQ4MDIxNjIwMDEvMjMxMzhmMjktNDU0YS00NDQwLWIwNTYtMzc1MDQxMGEwYTFiLzE4M2JkMWY2LWNiZjAtNDNiZS04MmU5LTVlNGVlMmYxOWRkMC8%3D
#EXTINF:10.000,
https://house-fastly-signed-us-east-1-prod.brightcovecdn.com/media/v1/hls/v4/clear/5344802162001/23138f29-454a-4440-b056-3750410a0a1b/183bd1f6-cbf0-43be-82e9-5e4ee2f19dd0/5x/segment1.ts?fastly_token=NWVhYTA1NDRfMTI0YmRlZDY4MWI0YTk5Y2I1NzRkNDE0Y2IxMzczYzZlZjQzOTA3Y2FkMDc4YjIyZTZmOGU2MWMwMWJiZjFhYl8vL2hvdXNlLWZhc3RseS1zaWduZWQtdXMtZWFzdC0xLXByb2QuYnJpZ2h0Y292ZWNkbi5jb20vbWVkaWEvdjEvaGxzL3Y0L2NsZWFyLzUzNDQ4MDIxNjIwMDEvMjMxMzhmMjktNDU0YS00NDQwLWIwNTYtMzc1MDQxMGEwYTFiLzE4M2JkMWY2LWNiZjAtNDNiZS04MmU5LTVlNGVlMmYxOWRkMC8%3D
...
#EXT-X-ENDLIST

master.m3u8

#EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-0",NAME="en (Main)",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="en",URI="https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/5344802162001/23138f29-454a-4440-b056-3750410a0a1b/1d926be7-c72d-4361-b530-dcc39a002daf/10s/rendition.m3u8?fastly_token=NWVhYWRkYjZfNWVkNzI5ZjZkNTc1YWU3NzlmMDViYzU1ZjEyNmJhODg5M2NhMWE5NTdlMTlmMjFkZTFlNWY2NzBjZjE1MDU2Mg%3D%3D"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles-0",NAME="English",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="en",URI="https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/5344802162001/23138f29-454a-4440-b056-3750410a0a1b/6a152110-81c1-4362-8bd4-5fe61716bedb/rendition.m3u8?fastly_token=NWVhYWRkYjZfYjFmNDMzNGQyNmMwMDMxMDk1ZmRlNWFhZjI5YjcwZTgwZjNiOWE4ZWYwNTdmNWY1MmFlYzI5OWM4MjVkYmJmNw%3D%3D"
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=1051600,CODECS="mp4a.40.2,avc1.4d001e",RESOLUTION=640x360,AUDIO="audio-0",CLOSED-CAPTIONS=NONE,SUBTITLES="subtitles-0"
https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/5344802162001/23138f29-454a-4440-b056-3750410a0a1b/95287e07-2485-4264-8f54-88924af0b071/10s/rendition.m3u8?fastly_token=NWVhYWRkYjZfZTg1YzFkN2UwMmY3ZjkzMWNlYjBhMTRmNWJjYjJkYzVhNGUxNjQ0YTAzN2ZjODRlZDUzNWU4NjE3YjgzMDFmOQ%3D%3D
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-1",NAME="en (Main)",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="en",URI="https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/5344802162001/23138f29-454a-4440-b056-3750410a0a1b/67675504-52ba-4e80-a09c-d0489ab94633/10s/rendition.m3u8?fastly_token=NWVhYWRkYjZfNTBlMzcxMzIyNWEwMmJiM2UwYWRlODQ5YjhjZjJiNjc2ZjAwN2UzNWQyZmYzYTIyODVlNjcwMGFhODc2MjllYg%3D%3D"
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=1953600,CODECS="mp4a.40.2,avc1.4d001f",RESOLUTION=960x540,AUDIO="audio-1",CLOSED-CAPTIONS=NONE,SUBTITLES="subtitles-0"
https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/5344802162001/23138f29-454a-4440-b056-3750410a0a1b/a07e1010-3925-431a-a9d5-3af36a9e236e/10s/rendition.m3u8?fastly_token=NWVhYWRkYjZfZTJlMmM0NmY2ODEyNDg4NTAxOWVhN2ZkNjg5ZDY0Zjg0Mjk5MWUzOWRlMDk2ZTFiZGZhMmZlMjNkNmMzMmRkMw%3D%3D
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-2",NAME="en (Main)",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="en",URI="https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/5344802162001/23138f29-454a-4440-b056-3750410a0a1b/a0b690a5-de0a-4fbd-ba8c-b033029c9631/10s/rendition.m3u8?fastly_token=NWVhYWRkYjZfMjdhOTJmMzY5ZDBiMDA3MWQ4YjdmYTdlYjI1NzQwZTJmNjhjNzhmM2FjMTFkY2VkM2UwMmIyNTZlY2IyZWQwOA%3D%3D"
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=2900700,CODECS="mp4a.40.2,avc1.4d001f",RESOLUTION=1280x720,AUDIO="audio-2",CLOSED-CAPTIONS=NONE,SUBTITLES="subtitles-0"
https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/5344802162001/23138f29-454a-4440-b056-3750410a0a1b/ac78e1e4-c202-4240-ad62-34edc394ac76/10s/rendition.m3u8?fastly_token=NWVhYWRkYjZfZWYzNjEwMTRjYzgxNGE4NjRmZmQ5YWFkYjk2N2QzNDczNGNlYTlkODRjZWQ5YmJiZGY3NDNlY2YzYzBjZDAwMg%3D%3D
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=4561700,CODECS="mp4a.40.2,avc1.640028",RESOLUTION=1920x1080,AUDIO="audio-2",CLOSED-CAPTIONS=NONE,SUBTITLES="subtitles-0"
https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/5344802162001/23138f29-454a-4440-b056-3750410a0a1b/b7ca5fdc-7180-4033-bdc8-5804ec5cc798/10s/rendition.m3u8?fastly_token=NWVhYWRkYjZfMThlYWE2ODhhYmE4Y2ZmNWFkNzNlMDUzZmFmZTM0NzhjNjYwNjYzODFjYzk4ODc5YmRmZGY2Y2FkYTk0ZTc4NQ%3D%3D
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=6630800,CODECS="mp4a.40.2,avc1.640028",RESOLUTION=1920x1080,AUDIO="audio-2",CLOSED-CAPTIONS=NONE,SUBTITLES="subtitles-0"
https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/5344802162001/23138f29-454a-4440-b056-3750410a0a1b/183bd1f6-cbf0-43be-82e9-5e4ee2f19dd0/10s/rendition.m3u8?fastly_token=NWVhYWRkYjZfYjBlMTMxNDFlZTkxMDRiNDMwN2U5MjIwY2JjMTJmYzhiNTcwOThkMjMwMGQxNzQxMzAyMTZhMmE2NjRkNjJkYQ%3D%3D

**Comment by Wea1thRS** [comment]
aw why'd this close. Was looking forward to/could have really used this.
