### ISSUE TITLE
An extractor error has occurred. (caused by KeyError('playlist',))

### ISSUE THREAD

**Issue by kartobecs** [ytdl-org/youtube-dl#25018]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

C:\Users\DEMSOFT>C:\youtube-dl.exe --proxy "" "https://iview.abc.net.au/show/sch
ool-of-roars/series/0/video/ZW1790A018S00"
[abc.net.au:iview] ZW1790A018S00: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('playlist',)); pleas
e report this issue on https://yt-dl.org/bug . Make sure you are using the lates
t version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the -
-verbose flag and include its complete output.

C:\Users\DEMSOFT>C:\youtube-dl.exe --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2020-04-13-59e3a9a, ffprobe git-2020-04-13-59e3
a9a
[debug] Proxy map: {'https': ' 192.168.1.34:8888', 'http': ' 192.168.1.34:8888'}

Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

C:\Users\DEMSOFT>C:\youtube-dl.exe --proxy "" "https://iview.abc.net.au/show/sch
ool-of-roars/series/0/video/ZW1790A018S00" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', '', 'https://iview.abc.net.au/show/school
-of-roars/series/0/video/ZW1790A018S00', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2020-04-13-59e3a9a, ffprobe git-2020-04-13-59e3
a9a
[debug] Proxy map: {}
[debug] Using fake IP 1.156.97.74 (AU) as X-Forwarded-For.
[abc.net.au:iview] ZW1790A018S00: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('playlist',)); pleas
e report this issue on https://yt-dl.org/bug . Make sure you are using the lates
t version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the -
-verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqy
mm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqy
mm\build\youtube_dl\extractor\abc.py", line 135, in _real_extract
KeyError: 'playlist'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqy
mm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqy
mm\build\youtube_dl\extractor\abc.py", line 135, in _real_extract
KeyError: 'playlist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqy
mm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqy
mm\build\youtube_dl\extractor\common.py", line 543, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by Key
Error('playlist',)); please report this issue on https://yt-dl.org/bug . Make su
re you are using the latest version; type  youtube-dl -U  to update. Be sure to
call youtube-dl with the --verbose flag and include its complete output.

Someone help me please?

**Comment by remitamine** [comment]
> This episode is no longer available in iview. You might like similar programs to this, shown below. Learn more in iview Support.
