### ISSUE TITLE
How do I exactly download protected videos from Facebook?

### ISSUE THREAD

**Issue by kartagis** [ytdl-org/youtube-dl#25025]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Hi,

I have created a ~/.netrc and am passing --netrc switch while trying to download a protected video. However, I am always getting the below.
```
[facebook] Downloading login page
[facebook] Logging in
[facebook] 10158418885802509: Downloading webpage
[facebook] 10158418885802509: Downloading webpage
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials. 
```
Then I used --username and --password on cli, which throws the same error. I even passed --twofactor, since I have 2FA enabled on my Facebook account.

What else do you suggest I try?
Thanks.

UPDATE: My .netrc file looks like this:
```
machine facebook login myemail password mypassword
```

**Comment by kartagis** [comment]
Incomplete how? I thought I followed the template.

**Comment by burtek** [comment]
@kartagis Did you figure that out? Having same issue.

**Comment by burtek** [comment]
Actually, I'm not sure if youtube-dl uses 2FA for facebook at all...

**Comment by kartagis** [comment]
Nope, I tried everything I could think of. I tried username, I tried e-mail
address, I tried escaping the exclamation mark in my password; nothing
seems to work.
Tolga

**Comment by kartagis** [comment]
Any progress on this?

**Comment by kartagis** [comment]
How is this incomplete anyway?

**Comment by kartagis** [comment]
Can you please reopen this issue? It persists. Or at least tell me how this bug report is incomplete.
