### ISSUE TITLE
How to avoid Pluralsight account blocking

### ISSUE THREAD

**Issue by ATHellboy** [ytdl-org/youtube-dl#25024]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I use this command for downloading videos from Pluralsight:

> youtube-dl --cookies cookies.txt -o "C:/MyVideos/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" URL --write-sub --sub-lang en,es

But after a few times my account is blocked. Do I do something wrong ? Or how can I avoid blocking as much as possible ?

**Comment by dstftw** [comment]
```
--sleep-interval SECONDS         Number of seconds to sleep before each
                                 download when used alone or a lower bound
                                 of a range for randomized sleep before each
                                 download (minimum possible number of
                                 seconds to sleep) when used along with
                                 --max-sleep-interval.
--max-sleep-interval SECONDS     Upper bound of a range for randomized sleep
                                 before each download (maximum possible
                                 number of seconds to sleep). Must only be
                                 used along with --min-sleep-interval.
```

**Comment by RaphaelNdonga** [comment]
Yes. You violated their terms of us
