### ISSUE TITLE
udemy Error 403 Downloading popup Login

### ISSUE THREAD

**Issue by Mtea994** [ytdl-org/youtube-dl#25037]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

## Description

iam able to download a siingle video but i want to download the whole in structured directories which i have done so many time but now getting the error 403 popup login(it means that i am unable to login to my account)  even after clearing cache directory i think there is something broken in support for udemy has anyone checked or am i the only one getting the error

**Comment by zgvozden** [comment]
Same for me:
youtube-dl https://www.youtube.com/watch?v=jhgJV0Pg54Y

**Comment by triplesixman** [comment]
try youtube-dl --rm-cache-dir

**Comment by Mtea994** [comment]
as i said it has no effect on the existing error .. udemy must have changed some thing i tried every possible solution that there is

**Comment by Mtea994** [comment]
how is it incomplete guide me ?? or resolve the issue before you close this without any comment . or this issue is not to be resolved
