### ISSUE TITLE
YouTube error 400 when using username and password

### ISSUE THREAD

**Issue by shivsah** [ytdl-org/youtube-dl#25036]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
```

## Description

I'm unable to login into YouTube to download a certain YouTube premium video.

**Comment by AkgunFatih** [comment]
@dstftw show us the link to the duplicate cant find it

**Comment by aliasedv2** [comment]
https://www.youtube.com/watch?v=10WmFYiMnoI
Also got same error
