### ISSUE TITLE
hotstar extractor needs to update

### ISSUE THREAD

**Issue by Admire1231** [ytdl-org/youtube-dl#25042]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Please fix hotstar extractor its just downloading file of 1mb saying that u need to update ur app so please fix this issue

**Comment by rajucomp** [comment]
What is the status on this ? I am also facing the same issue. I am in India.

**Comment by Abhijit47** [comment]
> What is the status on this ? I am also facing the same issue. I am in India.

No update.....I'm waiting for this....
Only god knows....
