### ISSUE TITLE
Reindex when downloading a playlist

### ISSUE THREAD

**Issue by sahrawat** [ytdl-org/youtube-dl#25044]
## Checklist

- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I am using this command to download multiple playlist from a file `playlist.txt` which has some links to playlist:

    cat playlist.txt | xargs -n1 youtube-dl -o '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s'

Overtime these playlist index changes and when I run the above command again, it starts downloading the whole playlist. What I expect is that `youtube-dl` should reindex the already downloaded files when index changes.

Are there any workarounds to this?

**Comment by dstftw** [comment]
No reindexing is possible. For not downloading the same videos use `--download-archive`.
