### ISSUE TITLE
Espn+ New Authorization method 

### ISSUE THREAD

**Issue by cwondercheck** [ytdl-org/youtube-dl#25046]
There seems to be a problem with the authorization key I have never had this problem on espn+ before. Can provide login info if needed.

C:\Users\Chenaniah>youtube-dl --add-header "authorization:5=eyJhY28UUpeD9oe8QUMFbWXhbxkXmiuQJ2uNWQcMJsurHxanzM4FTWYDfYfLBz3vaJgqXeR4PGXzCGYQw7UemxRoRxCC97oX9YaY|eyJraWQiOiJ1EbAgiEHcY8WXDMZRVUppyiGhar439Aj8mJn7RfdNkJ9bnChX5d4otsNg4cr5Tkh9Vmq88KS3EuRrXKpw2S3A8yZPREJNtZSV1CTpwJ47QAQvp0.eyJpc1EbAgiEHcY8WXDMZRVUppyiGhar439Aj8mJn7RfdNkJ9bnChX5d4otsNg4cr5Tkh9Vmq88KS3EuRrXKpw2S3A8yZPREJNtZSV1CTpwJ47QAQvp.B02w9LS55JnWkVDh2dcaAjTAILgXd9Wnpvjulp-Kk5ITSSsB-G0KUJGlXkmj2mCoUBURw_c_TNL0WEOgT96wjiRSWmGR-q6r1I12g8vhdGz-btg1q2cfzfucnu4xpucvxcf6njah4rwj8uqdvl9alrzBeYIxDhBP8RHLelcf4rR-53ma0VbTDub-9s4U4yAP6hNPFQjcs2dKKMIVl-QWd9KnxNP28UUpeD9oe8QUMFbWXhbxkXmiuQJ2uNWQcMJsurHxanzM4FTWYDfYfLBz3vaJgqXeR4PGXzCGYQw7UemxRoRxCC97oX9YaY-yWPbtg1q2cfzfucnu4xpucvxcf6njah4rwj8uqdvl9alrzP2Dpu4An5BT_r4unSshn2MvQ" "https://hlsvod-l3c-clt1.media.plus.espn.com/ps01/espn/hls/4d72b223-3543-4d6d-8986-4649de1c600b/r/4b506b55-8f01-4d1d-b551-b013b43a9dff/a062-MAIN/cf092785-731e-4681-a962-eb949968b157/7000_complete.m3u8"
[generic] 7000_complete: Requesting header
[generic] 7000_complete: Downloading m3u8 information
[download] Destination: 7000_complete-7000_complete.mp4
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9.1.1 (GCC) 20190807
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
libavutil 56. 31.100 / 56. 31.100
libavcodec 58. 54.100 / 58. 54.100
libavformat 58. 29.100 / 58. 29.100
libavdevice 58. 8.100 / 58. 8.100
libavfilter 7. 57.100 / 7. 57.100
libswscale 5. 5.100 / 5. 5.100
libswresample 3. 5.100 / 3. 5.100
libpostproc 55. 5.100 / 55. 5.100
[hls @ 00000190d18a9e40] Skip ('#EXT-X-VERSION:3')
[hls @ 00000190d18a9e40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2017-08-08T00:00:00.000Z')
[hls @ 00000190d18a9e40] Opening 'https://playback.svcs.plus.espn.com/silk/v1/obtain-license/6defbd5f-ef84-4e0b-b321-8d5fae9de4c3' for reading
[hls @ 00000190d18a9e40] Unable to open key file https://playback.svcs.plus.espn.com/silk/v1/obtain-license/6defbd5f-ef84-4e0b-b321-8d5fae9de4c3
[hls @ 00000190d18a9e40] Opening 'crypto+https://hlsvod-l3c-clt1.media.plus.espn.com/ps01/espn/hls/4d72b223-3543-4d6d-8986-4649de1c600b/r/4b506b55-8f01-4d1d-b551-b013b43a9dff/a062-MAIN/cf092785-731e-4681-a962-eb949968b157/00/00/00_000.ts' for reading
[hls @ 00000190d18a9e40] Error when loading first segment 'https://hlsvod-l3c-clt1.media.plus.espn.com/ps01/espn/hls/4d72b223-3543-4d6d-8986-4649de1c600b/r/4b506b55-8f01-4d1d-b551-b013b43a9dff/a062-MAIN/cf092785-731e-4681-a962-eb949968b157/00/00/00_000.ts'
https://hlsvod-l3c-clt1.media.plus.espn.com/ps01/espn/hls/4d72b223-3543-4d6d-8986-4649de1c600b/r/4b506b55-8f01-4d1d-b551-b013b43a9dff/a062-MAIN/cf092785-731e-4681-a962-eb949968b157/7000_complete.m3u8: Invalid data found when processing input

ERROR: ffmpeg exited with code 1

**Comment by dstftw** [comment]
You must use original URL.
