### ISSUE TITLE
[Crunchyroll] Error: Unable to extract video_title

### ISSUE THREAD

**Issue by mondxp** [ytdl-org/youtube-dl#25047]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
/usr/bin/youtube-dl --write-sub --sub-lang deDE --netrc --verbose -o '%(series)s - E%(episode_number)02d - %(episode)s.%(ext)s' -f bestvideo+bestaudio/best -- https://www.crunchyrol
l.com/de/that-time-i-got-reincarnated-as-a-slime/episode-24-black-and-the-mask-780741
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--write-sub', '--sub-lang', 'deDE', '--netrc', '--verbose', '-o', '%(series)s - E%(episode_number)02d - %(episode)s.%(ext)s', '-f', 'bestvideo+bestaudio/best', '--', 'https://www.crunchyroll.com/de/that-time-i-got-reincarnated-as-a-slime/episode-24-black-and-the-mask-780741']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Linux-4.15.0-96-generic-x86_64-with
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[crunchyroll] Downloading login page
[crunchyroll] Logging in
[crunchyroll] 780741: Downloading webpage
ERROR: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/crunchyroll.py", line 444, in _real_extract
    video_title = self._html_search_regex(
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Crunchyroll has updated their website, breaking the video_title regex.
Changing the regex on line 445 of the crunchyroll extractor should fix this:

```
r'(?s)<h1[^>]*>((?:(?!<h1).)*?<span[^>]+itemprop=["\']title["\'][^>]*>(?:(?!<h1).)+?)</h1>'
```
to
```
r'(?s)<h1[^>]*>((?:(?!<h1).)*?<span[^>]+itemprop=[\"\']name[\"\'][^>]*>(?:(?!<h1).)+?)</h1>'
```

**Comment by TravisDavis-ops** [comment]
Much love thanks for the Quick fix

**Comment by marlenexxx** [comment]
wahh.. thanks for the fix :D

**Comment by werewolf004** [comment]
Thanks for the Fix, for user who using .exe file under windows, need to wait a new .exe generated by dev ?

**Comment by Kojirosan** [comment]
> 
> 
> Thanks for the Fix, for user who using .exe file under windows, need to wait a new .exe generated by dev ?

Me, ^^

**Comment by LameLemon** [comment]
The regex currently does not pass test 2. 
Expected title
```
KONOSUBA -God's blessing on this wonderful world! 2 Episode 1 – Give Me Deliverance From This Judicial Injustice!
```
Title from regex
```
KONOSUBA -God's blessing on this wonderful world! Episode 1 – Give Me Deliverance From This Judicial Injustice!
```

**Comment by VadzimTarasiuk** [comment]
Same issue. Tried fix from PR above. Works like charm so far.

**Comment by werewolf004** [comment]
> Same issue. Tried fix from PR above. Works like charm so far.
> Thanks dude :)

Cool, now just need to wait new .exe :)

**Comment by mondxp** [comment]
Thanks for the fix LameLemon :) Works great!

**Comment by mondxp** [comment]
Marking it as closed now because it seems to work now

**Comment by werewolf004** [comment]
> Marking it as closed because it seems to work now

And how to get the .exe file with the fix ? It seems .exe is the same actually

**Comment by LameLemon** [comment]
@werewolf004 My PR has the tested and merged by the maintainers of youtube-dl first then it will be added to the next release. As of yet none of them have looked at it.

**Comment by VadzimTarasiuk** [comment]
> And how to get the .exe file with the fix ?
I cloned the repo and builded my own binary from source code. I guess you can make it on win as well.
Just make sure you have updated crunchyroll extractor file when build the binary.

**Comment by DiamondMiner88** [comment]
> I cloned the repo and builded my own binary from source code.

How do you build binaries? I haven't done it before so i have no idea.
Windows preferably but I can switch to linux if that's not possible
