### ISSUE TITLE
ITV in HD?

### ISSUE THREAD

**Issue by Qiangong2** [ytdl-org/youtube-dl#25053]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Is it possible at all download videos from ITV in HD? I've seen other people able to download HD copies, but every show I try to download maxes out at 896x504. I am using `-f best` with the url. Also, you can view the videos in HD on ITV Hub.

**Comment by ilike2burnthing** [comment]
ITV Hub is SD only. Their only HD content available is through Amazon Channels ITV Hub+

**Comment by ischmidt20** [comment]
Just to add on to this, it appears that the HD ITV Hub you can view in-browser is in the dash format which is protected by DRM. So youtube-dl can only extract the unprotected HLS formats, and those max out at 504p. Wish there was a way to decrypt such dash files but there isn't as of yet.
