### ISSUE TITLE
HLS Progress Bar / Status

### ISSUE THREAD

**Issue by cjm721** [ytdl-org/youtube-dl#25055]
## Checklist

- [ X] I'm reporting a feature request
- [ X] I've verified that I'm running youtube-dl version **2020.03.24**
- [X ] I've searched the bugtracker for similar feature requests including closed ones

## Description

Youtube-DL does not give a progress bar for HLS. This I assume is because HLS is a streaming format that doesn't say how big the file will be / how many segments are left.

It would be nice to have some indicator of how far along in the stream it is. For this I had two ideas.

1. State how long the video stream currently is. Example Output: `[Streaming]  Position 15:30 at  00:04/s`
1. Use a user provided flag to estimate the length. Example Output: `[download]  10.5% of an estimated 873.88MiB at  2.44MiB/s estimated ETA 05:20`

I don't know if with the encoder have access to how long the current file is so don't know if option 1 is viable. For option 2 would assume since HLS gives quality / bitrate information could calculate an estimated total size and then just measure the segments size as they go by to determine percent.

End Goal for me personally is that I use Youtube-DL to download many HLS files using a script and it can take quite a while for some videos to finish. I was currently debating about parsing the output and looking at the ts segment number (not sure if that is part of standard or just been lucky that it seems to be an incrementing number) and guessing how many there are. Other option I was looking at was throwing the output into standard out and writing it to disk myself and attempt option 2.

**Comment by dstftw** [comment]
It does provide for native HLS.

**Comment by cjm721** [comment]
For anyone who comes across this my actual issue was the way I was printing the output was changing the order so \r was not working as intended (was getting overwritten by the ffmpeg output). So now catching the \r correctly everything works as intdended.
