### ISSUE TITLE
Is there a way to calculate pause between downloads based on the video clip duration?

### ISSUE THREAD

**Issue by ddbb2017** [ytdl-org/youtube-dl#25054]
I just started using this tool. Thank you, it's very useful. And sorry, if I'm asking something obvious.

I can see that people are complaining about banned accounts for setting the download interval too short. I see that one can specify the min and max range for the interval in the `--min-sleep-interval` and `--max-sleep-interval` parameters. that the software chooses from at random.

But I'm wondering, if there's an option to automatically calculate such interval based on the duration of the previously downloaded clip?

PS. That way the heuristic of the service will have a hard time spotting an automated downloader.

**Comment by dstftw** [comment]
No.

**Comment by ddbb2017** [comment]
@dstftw hey that's very helpful
