### ISSUE TITLE
Download audio directly via SDK

### ISSUE THREAD

**Issue by rajatjain** [ytdl-org/youtube-dl#25057]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Is there a way to download only the audio corresponding to a youtube link via the SDK? I currently use the following code to download the video file and then use other converters to convert them to audio. I couldn't find a way in the source code to directly download in audio form.

```
def download_video(video_id, target_f):
    params = {
        'nocheckcertificate': True,
        'format': 'mp4',
        'ignoreerrors': True,
        'outtmpl': target_f,
    }

    yt = YoutubeDL(params=params)
    rc = 0
    try:
        rc = yt.download([video_id])
    except Exception as e:
        print("Couldn't download file with id %s. Exception: %s" % (video_id, str(e)))

    if rc != 0:
        return False
    return True
```
I tried putting in `'format': 'mp3'` but it doesn't work.

**Comment by dstftw** [comment]
Read FAQ on format selection.

**Comment by rajatjain** [comment]
I tried the following code, but I'm unable to play it on iTunes, nor uses utilities like `mutagen` or `eyed3`. Both are unable to load the file.

```
def download_video(video_id, target_f):
    params = {
        'nocheckcertificate': True,
        'format': 'bestaudio/mpg3',
        'ignoreerrors': True,
        'outtmpl': target_f,
    }

    yt = YoutubeDL(params=params)
    rc = 0
    try:
        rc = yt.download([video_id])
    except Exception as e:
        print("Couldn't download file with id %s. Exception: %s" % (video_id, str(e)))

    if rc != 0:
        return False
    return True
```

I tried using `'format': 'bestaudio'`, `bestaudio/mp3` but none of them work. I get the following error on the terminal.

```
$ afinfo ~/tmp/test.mp3
File:           /Users/rjain/tmp/test.mp3
Fail: AudioFileOpenURL failed
```
