### ISSUE TITLE
Teachable support broken. Manual solution provided

### ISSUE THREAD

**Issue by achirkof** [ytdl-org/youtube-dl#25051]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['--output', '~/Downloads/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['https://some.teachable.com/courses/447455/lectures/15169635', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose', '--cookies', '/Users/andrey/Downloads/cookies.txt']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.7 (CPython) - Darwin-19.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 15169635: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 15169635: Downloading webpage
[generic] 15169635: Extracting information
[Teachable] Downloading some.teachable.com login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

```

## Description

Hi! Looks like Teachable support broken. Before it works but now not. Maybe because of changed captcha.
Here is my previous issue https://github.com/ytdl-org/youtube-dl/issues/23418 and using cookies solves it. But now cookies doesn't help.
Please help!

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by achirkof** [comment]
> You must provide account credentials.

Provided by email

**Comment by achirkof** [comment]
**Here is manual solution**

1.- Right click on any Wistia video, click on "Copy link and thumbnail".
2.- On a text editor, paste the link.

You should get something like this:
```
<p><a href="https://www.webpage.com/start-here/?wvideo=447455"><img src="https://embedwistia-a.akamaihd.net/deliveries/somestring.jpg?image_play_button_size=2x&amp;image_crop_resized=960x540&amp;image_play_button=1&amp;image_play_button_color=7b796ae0" width="400" height="225" style="width: 400px; height: 225px;"></a></p><p><a href="https://www.webpage.com/start-here/?wvideo=xxxxxxxxxx">Title</a></p>
```

2.1.- Note that the video identifier is after the "video=", in this case the video identifier is xxxxxxxxxx.

3.- ON CHROME, replace "**" of `view-source:https://fast.wistia.net/embed/iframe/**?videoFoam=true` with the video ID you wish to download.

In this case enter on the URL bar: `view-source:https://fast.wistia.net/embed/iframe/447455?videoFoam=true`

3.1.- Or open [this](https://fast.wistia.net/embed/iframe/447455?videoFoam=true) page and paste your code

4.- On the source code search for the first link/URL that ends in .bin

Copy and paste that link into a new tab, click on the three dots in the bottom right corner and select download.

Or use Wget to download .bin file.

5.- After the video has downloaded, replace “.bin” with “.mp4”. Enjoy

**Comment by jdeluyck** [comment]
If you're really lazy you can use the tiny dirty python script I made for teachable files.
You'll still need to get the video code yourself.

https://gist.github.com/jdeluyck/41b66a5a02e856a0e7da447ee93153e6

**Comment by khall187** [comment]
> If you're really lazy you can use the tiny dirty python script I made for teachable files.
> You'll still need to get the video code yourself.
> 
> https://gist.github.com/jdeluyck/41b66a5a02e856a0e7da447ee93153e6

I'm a newbie at python.

I'm getting errors running the script: DL: error: the following arguments are required: -v/--video, -f/--filename

I have my URL: https://EDITEDFORPRIVACY.teachable.com/courses/123456/lectures/1776337?wvideo=h03ul197jy

How do I use that URL to give your script what it wants?

**Comment by al786** [comment]
Of course this is great but I want to download my whole course since my internet sucks at home - it'd take hours to do this - anyway to speed it up? I keep getting errors after a while using YoutubeDL

**Comment by dstftw** [comment]
No longer available.
