### ISSUE TITLE
Streaming Video url Redirecting to domain

### ISSUE THREAD

**Issue by lokesh657** [ytdl-org/youtube-dl#25059]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

When I try to download using video URL, it is forcibly redirecting to the domain as shown in the log

Is there any way to avoid redirection of .m3u8 link........Can you please solve this issue to download a video
```

C:\Users\HP I5>"C:\Users\HP I5\Videos\youtube-dl.exe" -v -U https://d2fgiyp8yuap60.cloudfront.net/Geotech_GTE_Origin_of_Soil_20191226/720p.m3u8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-U', 'https://d2fgiyp8yuap60.cloudfront.net/Geotech_GTE_Origin_of_Soil_20191226/720p.m3u8']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {'https': 'https://127.0.0.1:8888', 'http': 'http://127.0.0.1:8888'}
youtube-dl is up-to-date (2020.03.24)
[generic] 720p: Requesting header
[redirect] Following redirect to https://lms.thegateacademy.com/
[generic] lms.thegateacademy: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lms.thegateacademy: Downloading webpage
[generic] lms.thegateacademy: Extracting information
ERROR: Unsupported URL: https://lms.thegateacademy.com/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\generic.py", line 3352, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://lms.thegateacademy.com/

```

Example-1:
Reference URL: https://lms.thegateacademy.com/dashboard/course/83/subject/225/chapter/1147/view/video/595/U2FsdGVkX1%2FT708sw5injyq%2FRi3VpxMhA1XY80Ju9xtV8ec3J8K80QM4QIQW1x%2Bm6ZwzPkoQYk6KKjXdhclgRUAWjbgiMcN5GBFY5nUjrWI%3D
Video URL : https://d2fgiyp8yuap60.cloudfront.net/TypesofPileMethodsforQub-Part1of11541834627960_20190126/720p.m3u8

Example-2
Reference URL : https://lms.thegateacademy.com/dashboard/course/43/subject/78/chapter/161/view/video/7749/U2FsdGVkX18wRmUNrVaHrq9qb1nrcA9I08aN1kp%2Fb5UxDVhcJh5BZQx%2BTW%2FEmwrCyZv%2BO1GPo2licLPw3zb0Mg%3D%3D
Video URL : https://d2fgiyp8yuap60.cloudfront.net/Geotech_GTE_Origin_of_Soil_20191226/720p.m3u8

**Comment by dstftw** [comment]
No, same happens in browser. No difference.

**Comment by lokesh657** [comment]
> No, same happens in browser. No difference.

So, there is no way to download a video using example URL's
