### ISSUE TITLE
youtube.com Error 403

### ISSUE THREAD

**Issue by IamLizu** [ytdl-org/youtube-dl#25069]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
```

## Description

Here's what I get when I try to download videos from youtube using `youtube-dl <video_url>`,
```
youtube-dl https://www.youtube.com/watch?v=-0-RNQeKETU
[youtube] -0-RNQeKETU: Downloading webpage
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

**Comment by Hrxn** [comment]
#23638

**Comment by IamLizu** [comment]
Thank you, i didn't know. Removing the cache dir solved the problem.
