### ISSUE TITLE
How do I access chunk information?

### ISSUE THREAD

**Issue by nickerlan** [ytdl-org/youtube-dl#25066]
#10645  Checklist
- [+] I'm asking a question
- [+] I've looked through the README and FAQ for similar questions
- [+] I've searched the bugtracker for similar questions including closed ones

## Question

How do I get SegmentBase indexRange to make .mpd file from mp4 downloaded from youtube?

In my usecase I need it to concat several periods of video into single .mpd for user to see short trailer from long video.

**Comment by dstftw** [comment]
See mpd manifest spec.

**Comment by cloudrac3r** [comment]
Hi @nickerlan, did you ever figure out how to get the initRange and indexRange data? Do you understand what dstftw specifically meant by their comment?

**Comment by cloudrac3r** [comment]
I'm sure there's a better way of doing this, but I decided to just extract it from the HTML myself. Please do still let me know if you have answers to my questions or any good ideas.

https://git.sr.ht/~cadence/Second/tree/main/index.py#L234
