### ISSUE TITLE
Unable to download unfinished live

### ISSUE THREAD

**Issue by mittorn** [ytdl-org/youtube-dl#25075]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.03.24**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Description

When downloading incomplete live, ffmpeg does not stop in the end, cycling on index.m3u8. When running it manually it is possible to stop it by pressing 'q'. I tried to stop it with ^C, but it killed ffmpeg. Why you use ffmpeg, but not let it terminate normally? No log because live is finished now. I know about mpegts or additional ffmpeg options, but why it not enabled by default if without it it is just impossible to get valid file?

**Comment by dstftw** [comment]
ffmpeg will be terminated correctly if you won't hit Ctrl+C multiple times.
