### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by avagraha** [ytdl-org/youtube-dl#25070]
C:\Users\andremales>y -v https://www.youtube.com/watch?v=ln459WmhD28
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=ln459Wmh
D28']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-94698-g83e0b71-Reino, ffprobe N-94698-g83e0b
71-Reino, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ln459WmhD28: Downloading webpage
[youtube] {18} signature length 104, html5 player vflset
[youtube] {135} signature length 104, html5 player vflset
[youtube] {244} signature length 104, html5 player vflset
[youtube] {134} signature length 100, html5 player vflset
[youtube] {243} signature length 104, html5 player vflset
[youtube] {242} signature length 104, html5 player vflset
[youtube] {278} signature length 104, html5 player vflset
[youtube] {140} signature length 100, html5 player vflset
[youtube] {249} signature length 100, html5 player vflset
[youtube] {250} signature length 104, html5 player vflset
[youtube] {251} signature length 104, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged in
to mkv.
[debug] Invoking downloader on 'https://r11---sn-8vq54voxpu-ca9e.googlevide
o.com/videoplayback?expire=1588219432&ei=yPmpXs3dIIaP-gbo-I3oAQ&ip=93.65.10
6.43&id=o-AEoQJUKkxT-HhpvfvGLciv11iOjfnYZqjNoEnJxPsRcp&itag=135&aitags=134%
2C135%2C242%2C243%2C244%2C278&source=youtube&requiressl=yes&mh=tV&mm=31%2C2
9&mn=sn-8vq54voxpu-ca9e%2Csn-hpa7kn7s&ms=au%2Crdu&mv=m&mvi=10&pl=24&usequic
=no&initcwndbps=707500&vprv=1&mime=video%2Fmp4&gir=yes&clen=41817455&dur=48
32.120&lmt=1521056016570461&mt=1588197749&fvip=5&keepalive=yes&c=WEB&sparam
s=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%
2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cusequic%2Ci
nitcwndbps&lsig=ALrAebAwRQIgVJp-LuygogPO9DkBKDkw6RGblorqYAQFApxeNnuXRjYCIQD
WoVOG6IKIwDSNC49TfWeO9MsUEJ6Qr_1fRMweGoJRng%3D%3D&sig===QS-Lvn79MwS-wrB7nb_
uZGPyk513W8sp3Qwsuo8xV8cCQICUhxlnOsPjeYICtp-lmvoA7MD--E5621Coyqbu_9vm1dgsQx
wpLg&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj
wbwqymm\build\youtube_dl\YoutubeDL.py", line 1920, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj
wbwqymm\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj
wbwqymm\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj
wbwqymm\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj
wbwqymm\build\youtube_dl\downloader\http.py", line 109, in establish_connec
tion
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj
wbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_respon
se
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain

  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_
default
urllib.error.HTTPError: HTTP Error 403: Forbidden

A lot YT videos with this issue.
Pasty: does not work
MH: works well.

C:\Users\andrej>y -v https://www.youtube.com/watch?v=Ap7r-bUvbQk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=Ap7r-bUv
bQk']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-94698-g83e0b71-Reino, ffprobe N-94698-g83e0b
71-Reino, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Ap7r-bUvbQk: Downloading webpage
[youtube] {18} signature length 104, html5 player vflset
[youtube] {135} signature length 108, html5 player vflset
[youtube] {244} signature length 104, html5 player vflset
[youtube] {134} signature length 104, html5 player vflset
[youtube] {243} signature length 108, html5 player vflset
[youtube] {133} signature length 108, html5 player vflset
[youtube] {242} signature length 108, html5 player vflset
[youtube] {160} signature length 104, html5 player vflset
[youtube] {278} signature length 104, html5 player vflset
[youtube] {140} signature length 104, html5 player vflset
[youtube] {249} signature length 108, html5 player vflset
[youtube] {250} signature length 108, html5 player vflset
[youtube] {251} signature length 104, html5 player vflset
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r8---sn-8vq54voxpu-ca9e.googlevideo
.com/videoplayback?expire=1587419563&ei=S8WdXqbAM9WYgAe786LYCw&ip=93.65.106
.125&id=o-AI-j-sN6yCFfOo_cOamYgls_jjC1xuAgC3WgjRdLawWw&itag=135&aitags=133%
2C134%2C135%2C160%2C242%2C243%2C244%2C278&source=youtube&requiressl=yes&mh=
0B&mm=31%2C29&mn=sn-8vq54voxpu-ca9e%2Csn-hpa7kn7z&ms=au%2Crdu&mv=m&mvi=7&pl
=24&usequic=no&initcwndbps=740000&vprv=1&mime=video%2Fmp4&gir=yes&clen=7717
2870&dur=710.960&lmt=1540758523943656&ns=WlhP8eNPGXik62yr0K1lMukC&mt=158739
7896&fvip=3&keepalive=yes&c=WEB&txp=5432432&n=j9bxAeBBhBo2KwKo2a&sparams=ex
pire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Ccl
en%2Cdur%2Clmt%2Cns&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cusequic%2C
initcwndbps&lsig=ALrAebAwRgIhAK6KMPKItEjdA6qy1cQxHye2KUwuXs1-yNUVr4u03MhJAi
EA-8mRpR-HBQ6yalZiS3MrC2U_lPC3TJLSo7NkHOdDrI8%3D&sig=AJpPlLswRQIgNJ7r8lPNxH
tN8VYwKZXNo0R3s-Y_8n0X=NCOk_J_vcgCIQCfIqAYd==pVBzhucEq-jblC6ocPSSGnVjta8H6S
IQh&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj
wbwqymm\build\youtube_dl\YoutubeDL.py", line 1920, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj
wbwqymm\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj
wbwqymm\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj
wbwqymm\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj
wbwqymm\build\youtube_dl\downloader\http.py", line 109, in establish_connec
tion
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpj
wbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_respon
se
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain

  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_
default
urllib.error.HTTPError: HTTP Error 403: Forbidden

In the past I downloaded this video without problems, what changed?

**Comment by mysuf** [comment]
I'm getting same 403 errors. Tried different ips. Does anyone know the reason? Thanks

env: **python2.7**
url: [youtube link](https://www.youtube.com/watch?v=8aJCK6eZH58)
youtube-dl: **2020.03.24**

filter_presets: `best[width=1280][ext!=webm][protocol!=http_dash_segments][fps<=?60.0],best[width=1920][ext!=webm][protocol!=http_dash_segments][fps<=?60.0]/bestvideo[width=1920][ext!=webm][protocol!=http_dash_segments][fps<=?60.0]+bestaudio[protocol!=http_dash_segments][ext!=webm]/best[width>1920][ext!=webm][protocol!=http_dash_segments][fps<=?60.0]/bestvideo[width=1920][ext!=webm]+bestaudio[ext!=webm]/bestvideo[width>1920][ext!=webm][protocol!=http_dash_segments][fps<=?60.0]+bestaudio[protocol!=http_dash_segments][ext!=webm]/bestvideo[width>1920][ext!=webm]+bestaudio[ext!=webm]/best[ext!=webm]`

Also I got progress hook and one failed format(1080p) from bellow log has status 'finished'. Seems like a bug. It throws error later when it tries to open given filepath which ofc doesnt exists (data/source/8aJCK6eZH58_299+140.mp4)

```
2020/04/28 12:17:32 [13699] D1: [youtube] 8aJCK6eZH58: Downloading webpage [8992d9f9] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {18} signature length 104, html5 player vflset [a95c4623] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {22} signature length 104, html5 player vflset [fd0fe8aa] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {137} signature length 100, html5 player vflset [14938844] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {248} signature length 104, html5 player vflset [5f5b1204] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {299} signature length 100, html5 player vflset [d920cb25] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {303} signature length 104, html5 player vflset [d580148a] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {136} signature length 104, html5 player vflset [2ccaf325] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {247} signature length 104, html5 player vflset [5b159f0e] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {298} signature length 104, html5 player vflset [c41eac83] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {302} signature length 104, html5 player vflset [608eceab] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {135} signature length 104, html5 player vflset [c1b4e4a1] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {244} signature length 104, html5 player vflset [f24ee342] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {134} signature length 104, html5 player vflset [4ca9e6f] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {243} signature length 100, html5 player vflset [39578cf] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {133} signature length 104, html5 player vflset [14dfcf59] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {242} signature length 100, html5 player vflset [a0382805] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {160} signature length 104, html5 player vflset [2406012] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {278} signature length 104, html5 player vflset [e3391f36] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {140} signature length 104, html5 player vflset [60d4256a] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {249} signature length 100, html5 player vflset [902dbef7] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {250} signature length 104, html5 player vflset [779580e7] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] D1: [youtube] {251} signature length 100, html5 player vflset [9c3390] {yt_unicode.py:debug():9}
2020/04/28 12:17:32 [13699] W3: "id" field is not a string - forcing string conversion, there is an error in extractor [51441871] {yt_unicode.py:warning():12}
2020/04/28 12:17:33 [13699] D1: [info] 8aJCK6eZH58: downloading video in 2 formats [2d50e5c3] {yt_unicode.py:debug():9}
2020/04/28 12:17:33 [13699] D1: [debug] Invoking downloader on u'https://r3---sn-2gb7sn7s.googlevideo.com/videoplayback?expire=1588090652&ei=vAKoXrH6GbHR8gORjpnACw&ip=XX.XX.XXX.XXX&id=o-ABjbvzZ8hSdas9JUnPy4PZXdVXnbB4NdjFwXwjbFqNmg&itag=22&source=youtube&requiressl=yes&mh=_y&mm=31%2C26&mn=sn-2gb7sn7s%2Csn-4g5e6ne6&ms=au%2Conr&mv=u&mvi=2&pl=21&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=6905.080&lmt=1587852699072687&mt=1588068978&fvip=3&c=WEB&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=ALrAebAwRgIhANRWd79xxgIa2Ap3EdtNBjKNQcaQRty6dK-hInTXtrJIAiEA76eSLSSZvnsstd4vmV2dr1yoMxWk8byHzOeGotS4QDY%3D&sig===gui2YmjLdIfP6rdBsHPPHqCqRNsVV-ZcYDhNfv6sN7eBiAdqouM0UsgApeIMHqvlzjOAPONXaWH10AgCDz4-dtswJAh4QHwpLO' [a53a157d] {yt_unicode.py:debug():9}
2020/04/28 12:17:33 [13699] F4: ERROR: unable to download video data: HTTP Error 403: Forbidden [abfe2501] {yt_unicode.py:error():15}
2020/04/28 12:17:33 [13699] F4: Traceback (most recent call last):   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1926, in process_info     success = dl(filename, info_dict)   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1865, in dl     return fd.download(name, info)   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 366, in download     return self.real_download(filename, info_dict)   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 341, in real_download     establish_connection()   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 109, in establish_connection     ctx.data = self.ydl.urlopen(request)   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen     return self._opener.open(req, timeout=self._socket_timeout)   File "/usr/lib/python2.7/urllib2.py", line 437, in open     response = meth(req, response)   File "/usr/lib/python2.7/urllib2.py", line 550, in http_response     'http', request, response, code, msg, hdrs)   File "/usr/lib/python2.7/urllib2.py", line 475, in error     return self._call_chain(*args)   File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain     result = func(*args)   File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp) HTTPError: HTTP Error 403: Forbidden [b75a5e9] {yt_unicode.py:error():15}
2020/04/28 12:17:33 [13699] D1: [debug] Invoking downloader on u'https://r3---sn-2gb7sn7s.googlevideo.com/videoplayback?expire=1588090652&ei=vAKoXrH6GbHR8gORjpnACw&ip=XX.XX.XXX.XXX&id=o-ABjbvzZ8hSdas9JUnPy4PZXdVXnbB4NdjFwXwjbFqNmg&itag=299&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C298%2C299%2C302%2C303&source=youtube&requiressl=yes&mh=_y&mm=31%2C26&mn=sn-2gb7sn7s%2Csn-4g5e6ne6&ms=au%2Conr&mv=u&mvi=2&pl=21&vprv=1&mime=video%2Fmp4&gir=yes&clen=2660205633&dur=6905.015&lmt=1587855037388577&mt=1588068978&fvip=3&keepalive=yes&c=WEB&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=ALrAebAwRgIhANRWd79xxgIa2Ap3EdtNBjKNQcaQRty6dK-hInTXtrJIAiEA76eSLSSZvnsstd4vmV2dr1yoMxWk8byHzOeGotS4QDY%3D&sig=0JpPlLswfAjgURz7-RelLvItfG7ySXrWBfAi0GoDKqKIB0FyGaxUAboCIBl9OPWDzzfH1_LazyQl60kzQe-pJliZfw9HrVR76z3E&ratebypass=yes' [e170ffbb] {yt_unicode.py:debug():9}
2020/04/28 12:17:33 [13699] F4: ERROR: unable to download video data: HTTP Error 403: Forbidden [3471455] {yt_unicode.py:error():15}
2020/04/28 12:17:33 [13699] F4: Traceback (most recent call last):   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1920, in process_info     partial_success = dl(fname, new_info)   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1865, in dl     return fd.download(name, info)   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 366, in download     return self.real_download(filename, info_dict)   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 341, in real_download     establish_connection()   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 109, in establish_connection     ctx.data = self.ydl.urlopen(request)   File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen     return self._opener.open(req, timeout=self._socket_timeout)   File "/usr/lib/python2.7/urllib2.py", line 437, in open     response = meth(req, response)   File "/usr/lib/python2.7/urllib2.py", line 550, in http_response     'http', request, response, code, msg, hdrs)   File "/usr/lib/python2.7/urllib2.py", line 475, in error     return self._call_chain(*args)   File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain     result = func(*args)   File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp) HTTPError: HTTP Error 403: Forbidden [52f20a9b] {yt_unicode.py:error():15}
```

**Comment by avagraha** [comment]
hi,
no idea why.
the dev suggested this workaround

 --rm-cache-dir

now it works well!




  ----- Original Message -----
