### ISSUE TITLE
Download videos DRM or with “mpd” (mpeg dash manifest)?

### ISSUE THREAD

**Issue by Yogioh969** [ytdl-org/youtube-dl#25071]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

I am a member of a site https://shahid.mbc.net/

It is a website similar to netflix but for arabic content

Previously, I could download from the website by taking the link for the video by internet download manager as m3u8 format ,, like this line

https://cdxmd05-ak.akamaized.net/43879ec8-c913-464e-9a2a-6938714b685f/3000060014_TXMHD...ilter=144_1080)

and download it

but now the site bring new Encrypt like netflix use (DRM) ,, and when I use internet download manager to get video download line it give me alot of line Not downloadable ,, like this one

https://cdxmd05-ak.akamaized.net/018a3bc5-5903-42b6-ae96-cdf9f8847946/3000061337_STXOP...t=mpd-time-csf)

here you are link to episode i want to download

wait for ad 1 min to finish

then episode time 39.18 min

https://shahid.mbc.net/ar/series/%D9%81%D8%B1%D8%B5%D8%A9-%D8%AB%D8%A7%D9%86%D9%8A%D8%A9-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-1-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-4/episode-413279

can any one help me how to download videos now from this site ??

i will pay for any script or way to how to download

waiting for your reply

**Comment by zackmark29** [comment]
It's not possible to download. 
It's the same with viki.com they now changed to mpd and other site as well

**Comment by mayanez** [comment]
I'm curious, is the `mpd` due to lack of current support or something more fundamental with DRM?
