### ISSUE TITLE
Suggestion: Include the exact upload time, not just upload date in the metadata. 

### ISSUE THREAD

**Issue by HT-7** [ytdl-org/youtube-dl#25078]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

When downloading a video using youtube-dl [URL] --write-info-json`, I can only find the upload **date**, but not the exact upload **time** in the video metadata.

I suggest also including the exact upload time in the metadata.

**Comment by dstftw** [comment]
`timestamp`.
