### ISSUE TITLE
how to get string License name the video is licensed under

### ISSUE THREAD

**Issue by Codelyoko2005** [ytdl-org/youtube-dl#25085]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I got stuck on how to get the License name the video is licensed under as string and return it to my another python script.
Can anyone help me with this issue? Thanks!

**Comment by dstftw** [comment]
`license` of info dict.
