### ISSUE TITLE
How to hide a warning/error?

### ISSUE THREAD

**Issue by DankMemeGuy** [ytdl-org/youtube-dl#25089]
## Checklist

- [x ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2020.03.24**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

I want the best format, thus audio and video get downloaded seperately and merged together. This is the default experience, However, I keep getting the "WARNING: Requested formats are incompatible for merge and will be merged into mkv."

Is there a way to hide this warning? At this point it's not a warning. It's telling me the expected behaviour of a default setting.

I think YouTube-dl could do well if it had the ability to hide warnings/errors etc. If each warning/error was numbered, the user could set which error and/or warning it wanted to ignore.

**Comment by dstftw** [comment]
`--no-warnings`.

**Comment by DankMemeGuy** [comment]
> `--no-warnings`.
That stops all warnings. I still want warnings, just not THAT warning.
