### ISSUE TITLE
is there any way to download video from this site with .m3u8 link

### ISSUE THREAD

**Issue by lokesh657** [ytdl-org/youtube-dl#25084]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

When I click on .m3u8 link, is redirecting to a domain.   I never have seen anywhere .m3u8 link redirection. Is there any solution for such videos.

I have given some example url. Can anyone try and help me.........Thank you in advance 

Click on Reference url and **Login as Guest** 
Example-1:
Reference URL: https://lms.thegateacademy.com/dashboard/course/83/subject/225/chapter/1147/view/video/595/U2FsdGVkX1%2FT708sw5injyq%2FRi3VpxMhA1XY80Ju9xtV8ec3J8K80QM4QIQW1x%2Bm6ZwzPkoQYk6KKjXdhclgRUAWjbgiMcN5GBFY5nUjrWI%3D
Video URL : https://d2fgiyp8yuap60.cloudfront.net/TypesofPileMethodsforQub-Part1of11541834627960_20190126/720p.m3u8

Example-2
Reference URL : https://lms.thegateacademy.com/dashboard/course/83/subject/225/chapter/1147/view/video/595/U2FsdGVkX1%2FT708sw5injyq%2FRi3VpxMhA1XY80Ju9xtV8ec3J8K80QM4QIQW1x%2Bm6ZwzPkoQYk6KKjXdhclgRUAWjbgiMcN5GBFY5nUjrWI%3D
Video URL : https://d2fgiyp8yuap60.cloudfront.net/Geotech_GTE_Origin_of_Soil_20191226/720p.m3u8

**Comment by dstftw** [comment]
Pass `Referer` and `Accept-Encoding` headers exactly as browser does.

**Comment by lokesh657** [comment]
> Pass `Referer` and `Accept-Encoding` headers exactly as browser does.

It is again redirecting to domain

can you please solve 

at least provide the format for CMD line
