### ISSUE TITLE
Can no longer download some videos from YouTube

### ISSUE THREAD

**Issue by winman3000** [ytdl-org/youtube-dl#25099]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[youtube] kqqqXrSGcKU: Downloading webpage
[youtube] {18} signature length 104, html5 player vflset
[youtube] {137} signature length 104, html5 player vflset
[youtube] {248} signature length 104, html5 player vflset
[youtube] {299} signature length 104, html5 player vflset
[youtube] {303} signature length 104, html5 player vflset
[youtube] {136} signature length 104, html5 player vflset
[youtube] {247} signature length 104, html5 player vflset
[youtube] {298} signature length 100, html5 player vflset
[youtube] {302} signature length 100, html5 player vflset
[youtube] {135} signature length 104, html5 player vflset
[youtube] {244} signature length 104, html5 player vflset
[youtube] {134} signature length 104, html5 player vflset
[youtube] {243} signature length 100, html5 player vflset
[youtube] {133} signature length 104, html5 player vflset
[youtube] {242} signature length 104, html5 player vflset
[youtube] {160} signature length 104, html5 player vflset
[youtube] {278} signature length 104, html5 player vflset
[youtube] {140} signature length 104, html5 player vflset
[youtube] {251} signature length 104, html5 player vflset
[youtube] kqqqXrSGcKU: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r2---sn-i5h7lned.googlevideo.com/videoplayback?expire=1588451476&ei=NIStXtfmF9Ko7gP8zYjIDw&ip=2003%3Ae1%3Abf14%3A9800%3A946d%3Aee94%3Aaf77%3Afcad&id=o-APRE7MIIjDXL9mlDE71I42O-dGtZKk9chv0Kie4P4Nlt&itag=18&source=youtube&requiressl=yes&mh=BD&mm=31%2C26&mn=sn-i5h7lned%2Csn-5hnekn7z&ms=au%2Conr&mv=m&mvi=1&pl=36&initcwndbps=1065000&vprv=1&mime=video%2Fmp4&gir=yes&clen=22715331&ratebypass=yes&dur=282.842&lmt=1587482428573461&mt=1588429831&fvip=2&c=WEB&txp=6216222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRAIgQKjKaZiKZhNsqfU6qAWHFu7GGBUk4N6HfizYCCyI1ggCIDoyZpQnxEiBMDniceG1-g5ua8-JAZTQkG4yix8p9UKv&sig=iJpPlLswRQIgNGEFXcyahphlDPIcvaeH_n=8Dq_uAwU2KHhtE8_lz-8CIQCx2BG3z2oKJaQGtxWKn8sdqlu65LA0LPc0tW0M6KsJNg=Z'
```

## Description

When I try to download a certain video from a YouTube page, Youtube-DL tells me that it is forbitten to download the video. But I can view this video with my browser. Strangely enough, this does not apply to all videos. Some videos can be downloaded as usual. It seems that YouTube has restricted the downloading of videos with such tools.

I get the following error when I try to download this URL:
https://www.youtube.com/watch?v=kqqqXrSGcKU

[youtube] kqqqXrSGcKU: Downloading webpage
[youtube] kqqqXrSGcKU: Downloading MPD manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by winman3000** [comment]
Unfortunately I couldn't find the bug. To which bug is mine a duplicate?

**Comment by snippins** [comment]
@winman3000 I just got the same error and found the solution here:
https://github.com/ytdl-org/youtube-dl/issues/23638

**Comment by Hrxn** [comment]
@snippins This pinned issue has been edited, and is only about YouTube 429 issues again.

@winman3000 

Please try either of these two:
```
--no-cache-dir                   Disable filesystem caching
--rm-cache-dir                   Delete all filesystem cache files
```

**Comment by winman3000** [comment]
Thank you, that solved my problem. I'm sorry for the trouble.
