### ISSUE TITLE
Problem with Crunchyroll, ERROR: Unable to extract video_title

### ISSUE THREAD

**Issue by cdmatter** [ytdl-org/youtube-dl#25096]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.crunchyroll.com/tower-of-god/episode-1-ball-794519', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-7648-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[crunchyroll] Downloading login page
[crunchyroll] Logging in
[crunchyroll] 794519: Downloading webpage
ERROR: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/crunchyroll.py", line 446, in _real_extract
    webpage, 'video_title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

When I try to find available video formats or download videos from Crunchyroll, I get the same error about extracting the video_title (ERROR: Unable to extract video_title).  I tried a couple of different videos, all of which played fine in the browser, but ended up failing to retrieve video formats or downloading videos when using youtube-dl.  I was able to get videos from Crunchyroll on April 18th without issue.

**Comment by MarkIvanowich** [comment]
Duplicate https://github.com/ytdl-org/youtube-dl/issues/25047, https://github.com/ytdl-org/youtube-dl/issues/25064, Will be fixed by PR https://github.com/ytdl-org/youtube-dl/pull/25060
If you're impatient, download and install from: https://github.com/LameLemon/youtube-dl/tree/fix_crunchyroll_title
