### ISSUE TITLE
Can't Download Twitch video from a "Subscriber only streamer" Bug

### ISSUE THREAD

**Issue by suwooyoutube** [ytdl-org/youtube-dl#25104]
My computer: C:\Users\ossia\Desktop\Downloads>youtube-dl https://www.twitch.tv/videos/600467607?filter=all&sort=time
[twitch:vod] 600467607: Downloading vod info JSON
[twitch:vod] 600467607: Downloading vod access token
[twitch:vod] 600467607: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
=timeCould not find the file.

**Comment by dstftw** [comment]
>This video is only available to subscribers. Sub now to watch and support kennybeats.

**Comment by suwooyoutube** [comment]
I'am already subscribed but it still don't want to download.

**Comment by reallyuniquename** [comment]
@suwooyoutube you need to specify your cookies, for example https://github.com/ytdl-org/youtube-dl/issues/23337#issuecomment-567768049
