### ISSUE TITLE
ERROR: Unable to extract real id;

### ISSUE THREAD

**Issue by Wlezley** [ytdl-org/youtube-dl#25138]
root@yt-dl:~# youtube-dl --version
2020.05.03

root@yt-dl:~# youtube-dl --verbose https://cnn.iprima.cz/videa/70-epizoda
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://cnn.iprima.cz/videa/70-epizoda']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2020.05.03
[debug] Python version 2.7.13 (CPython) - Linux-3.16.6-042stab141.3-x86_64-with-debian-9.9
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1, rtmpdump 2.4
[debug] Proxy map: {}
[IPrima] 70-epizoda: Downloading webpage
ERROR: Unable to extract real id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/iprima.py", line 74, in _real_extract
    webpage, 'real id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract real id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by kubalav** [comment]
[30fa5c6](https://github.com/ytdl-org/youtube-dl/commit/30fa5c6087d2e5e7a2bfe395ffbb267d92959356)
