### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by maxymczech** [ytdl-org/youtube-dl#25132]
On this video: https://www.youtube.com/watch?v=je_R3gEtDbw

I have upgraded `youtube-dl` via pip, current version is 2020.5.3. Verbose log output:

> ERROR: Signature extraction failed: Traceback (most recent call last):
>   File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\extractor\youtube.py", line 1385, in _decrypt_signature
>     video_id, player_url, s
>   File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
>     raise ExtractorError('Cannot identify player %r' % player_url)
> youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/64dddad9/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>  (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/s/player/64dddad9/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>

**Comment by maxymczech** [comment]
Lol :) Why do you put "outdated version" label on this issue, when I explicitly state that I have updated to latest version available via pip?

**Comment by dstftw** [comment]
Now, you will prove that with verbose log, "lol".

**Comment by maxymczech** [comment]
Is this a joke or something? Here is output of `pip show youtube-dl`:

```
Name: youtube-dl
Version: 2020.5.3
Summary: YouTube video downloader
Home-page: https://github.com/ytdl-org/youtube-dl
Author: Ricardo Garcia
Author-email: ytdl@yt-dl.org
License: Unlicense
Location: c:\programdata\anaconda3\lib\site-packages
Requires: 
Required-by: 
```

**Comment by dstftw** [comment]
Again: post complete verbose log as requested in the issue template.

**Comment by maxymczech** [comment]
Yeah right, you do that buddy :)
