### ISSUE TITLE
downloading from youtube-dl in io.BytesIO and playing it in realtime

### ISSUE THREAD

**Issue by brightening-eyes** [ytdl-org/youtube-dl#25131]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

hi,
I want to use youtube-dl from python and I want to download the video in a io.BytesIO object so I can play it in realtime without using any players.
my application is a client-server thing, where the client asks for the video, and the server plays it for all the clients.
is there anyway that I can use youtube-dl like this?

**Comment by dstftw** [comment]
No. But you can output to stdout.

**Comment by brightening-eyes** [comment]
is it possible to redirect the sys.stdout?
does it write to it? because I have no problem reading from that then.

**Comment by thekillgfx** [comment]
@brightening-eyes did you get a solution? I'm working on the same thing but seems like there isn't a solution over the internet!
