### ISSUE TITLE
[h264_nvenc] ERROR: Conversion failed!

### ISSUE THREAD

**Issue by steam3d** [ytdl-org/youtube-dl#25130]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.05.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Description
I try to enable  **h264_nvenc**.  First time i have tried to do it through python. [my question](https://github.com/ytdl-org/youtube-dl/issues/25072). I could not fix error and decided to make sure that conversion through the youtube-dl.exe works. I found similar problem [here](https://github.com/ytdl-org/youtube-dl/issues/25086) and tried to do the same command.
All the time i got the error:  **ERROR: Conversion failed!**.  I found a regularity.

### Render on CPU
Input:
```
 youtube-dl.exe 'https://www.youtube.com/watch?v=32ZG9WiR4wg' '--no-playlist' '--ignore-config' '--write-info-json' '--continue' '--output=%(title)s.%(ext)s' '--restrict-filenames' '--format=bestvideo+bestaudio' '--recode-video=mp4' '--verbose'
```
Output:
```
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:4K_UNDER_SEA_30_SECONDS_DEMO.f313.webm" -i "file:4K_UNDER_SEA_30_SECONDS_DEMO.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:4K_UNDER_SEA_30_SECONDS_DEMO.temp.webm"
Deleting original file 4K_UNDER_SEA_30_SECONDS_DEMO.f313.webm (pass -k to keep)
Deleting original file 4K_UNDER_SEA_30_SECONDS_DEMO.f251.webm (pass -k to keep)
[ffmpeg] Converting video from webm to mp4, Destination: 4K_UNDER_SEA_30_SECONDS_DEMO.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:4K_UNDER_SEA_30_SECONDS_DEMO.webm" "file:4K_UNDER_SEA_30_SECONDS_DEMO.mp4"
```

### Render on GPU
Input:
```
youtube-dl.exe 'https://www.youtube.com/watch?v=32ZG9WiR4wg' '--no-playlist' '--ignore-config' '--write-info-json' '--continue' '--output=%(title)s.%(ext)s' '--restrict-filenames' '--format=bestvideo+bestaudio' '--recode-video=mp4' '--postprocessor-args=-c:v h264_nvenc' '--verbose'
```
Output:
```
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:4K_UNDER_SEA_30_SECONDS_DEMO.f313.webm" -i "file:4K_UNDER_SEA_30_SECONDS_DEMO.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "-c:v" h264_nvenc "file:4K_UNDER_SEA_30_SECONDS_DEMO.temp.webm"
ERROR: Conversion failed!
```

### How to fix
As you can see the problem is the first command to ffmpeg. 
```
ffmpeg -y -loglevel "repeat+info" -i "file:4K_UNDER_SEA_30_SECONDS_DEMO.f313.webm" -i "file:4K_UNDER_SEA_30_SECONDS_DEMO.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "-c:v" h264_nvenc "file:4K_UNDER_SEA_30_SECONDS_DEMO.temp.webm"
```
If I start converting through the CPU and after the file 4K_UNDER_SEA_30_SECONDS_DEMO.webm is ready i interrupt the process. And then I’ll start the conversion through the GPU (Render on GPU command). Then the first command will be skipped, since the file is already ready and the second command will be executed without errors on the video card 
```
[download] 4K_UNDER_SEA_30_SECONDS_DEMO.webm has already been downloaded and merged
[ffmpeg] Converting video from webm to mp4, Destination: 4K_UNDER_SEA_30_SECONDS_DEMO.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:4K_UNDER_SEA_30_SECONDS_DEMO.webm" "-c:v" h264_nvenc "file:4K_UNDER_SEA_30_SECONDS_DEMO.mp4"
Deleting original file 4K_UNDER_SEA_30_SECONDS_DEMO.webm (pass -k to keep)
```

**Comment by dstftw** [comment]
Run ffmpeg command alone to see the actual error.

**Comment by steam3d** [comment]
@dstftw It is real problem.  If youtube_dl correctly transfer the commands to ffmpeg then the encoding will be without error.

Output from ffmpeg
```
Input #0, matroska,webm, from 'file:4K_UNDER_SEA_30_SECONDS_DEMO.f313.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:00:30.93, start: 0.000000, bitrate: 16072 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 3840x2160, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:4K_UNDER_SEA_30_SECONDS_DEMO.f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:00:31.00, start: -0.007000, bitrate: 137 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (vp9 (native) -> h264 (h264_nvenc))
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[webm @ 000001ca593706c0] Only VP8 or VP9 or AV1 video and Vorbis or Opus audio and WebVTT subtitles are supported for WebM.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 --
Conversion failed!
```

**Comment by jeliebig** [comment]
Hey,
I created a small patch as a workaround for this problem.
This is not a permanent solution and can be implemented in a better way. I just encountered this issue today and wrote this quick workaround to deal with it.

In case you are interested in this workaround, this is the patch file: [FFmpegMergerPP-Workaround.patch.txt](https://github.com/ytdl-org/youtube-dl/files/6252730/0001-Add-optional-parameter-to-override-custom-postproces.patch.txt) (I had to add .txt as the extension as .patch is not supported by github, but this shouldn't be a problem.)

How can you use this patch with youtube-dl?
Make sure that you cloned this repo and you're currently in the cloned directory, when using the following commands.

1. Checkout the latest youtube-dl version: `git checkout $(git tag --sort="-v:refname" | head -n 1 | tr -d "\n") -b $(git tag --sort="-v:refname" | head -n 1 | tr -d "\n")`
2. Apply the patch: `"git" am --3way <path to patchfile.patch>`
3. Install the modified version via pip: `pip3 install ./`
This should uninstall your existing version of youtube-dl and install the modified version instead. So you can you use youtube-dl the way you used it before without noticing a difference.

Finally I want to ask if I should create a pull request with a proper solution, so this issue can be fixed.

Thank you
Julian Liebig
