### ISSUE TITLE
Updating youtube-dl throws 'requirement already up-to-date', but 'youtube-dl --version' returns out of date version

### ISSUE THREAD

**Issue by psrpsrpsrpsr** [ytdl-org/youtube-dl#25136]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2020.05.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v https://www.youtube.com/watch?v=4OJDeeyHoK4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=4OJDeeyHoK4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.6.2 (CPython) - Darwin-19.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 4OJDeeyHoK4: Downloading webpage
[youtube] 4OJDeeyHoK4: Downloading video info webpage
WARNING: Unable to extract video title
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2077, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.
```

## Description

When trying to download Youtube videos, I'm getting this error: 

```
WARNING: Unable to extract video title 
ERROR: This video is unavailable.
```

I went to update Youtube-dl by executing:
`sudo pip install --upgrade youtube_dl`

Which throws:
```
WARNING: The directory '/Users/[my name]/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: youtube_dl in ./.local/lib/python3.6/site-packages (2020.5.3)
```

So even though I'm told that 'Requirement up-to-date' for version 2020.5.3, running this command tells me my version is out of date:
```
youtube-dl --version
2019.06.08
```

What am I missing here?

**Comment by dstftw** [comment]
Most likely you have multiple youtube-dl instances installed.

**Comment by psrpsrpsrpsr** [comment]
How do I remedy this? I am new to Python and package managers. Thank you.

**Comment by Nathan13888** [comment]
@dstftw

**Comment by Nathan13888** [comment]
@psrpsrpsrpsr Either uninstall youtube-dl from APT or from PIP.

Apt: `sudo apt remove youtube-dl`

You just need to remove one. Follow the instructions in the README for pip.
