### ISSUE TITLE
Download video only WITHOUT audio.

### ISSUE THREAD

**Issue by Gloryness** [ytdl-org/youtube-dl#25133]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

Okay, so I'm coding my first project and stumbled upon something quite struggling.
I want to be able to download a video **WITHOUT** audio.

I've searched everywhere but I can't find anything on it .
- plus I'm doing it in Python Code so please don't refer to the command line.

I know that I can do `bestvideo[height<={}]` but then it won't merge into the required format, but using video and audio WILL merge into the required format...

**So I was wondering if there is a way to get NO audio at all and still merge into the required format?**

**Comment by dstftw** [comment]
Merging is a process of muxing video-only and audio-only. What merge are you even talking about?

**Comment by Gloryness** [comment]
Never mind, I think I found a solution anyway.
