### ISSUE TITLE
Download of some videos from france.tv results in "No video formats found" error

### ISSUE THREAD

**Issue by djmandell** [ytdl-org/youtube-dl#25157]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl https://www.france.tv/france-4/oscar-malika-toujours-en-retard/oscar-malika-toujours-en-retard-saison-1/818501-le-concert.html -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.france.tv/france-4/oscar-malika-toujours-en-retard/oscar-malika-toujours-en-retard-saison-1/818501-le-concert.html', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.03
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-1021-aws-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[FranceTVSite] 818501-le-concert: Downloading webpage
[FranceTV] ba623662-3221-42ef-848f-3741921853e4: Downloading video JSON
[FranceTV] ba623662-3221-42ef-848f-3741921853e4: Downloading geo restriction info
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 209, in _real_extract
    return self._extract_video(video_id, catalog)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 169, in _extract_video
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I've recently tried using youtube-dl to download cartoons from france.tv.   Most videos work fine, including other episodes of the same cartoon (for example I was able to download https://www.france.tv/france-4/oscar-malika-toujours-en-retard/oscar-malika-toujours-en-retard-saison-1/1435835-le-singe-savant.html).  However a few videos, including the one mentioned in this bug report, don't work.  I confirm that I view the video in this bug report in the browser, fwiw.

I'm happy to answer any further questions you have.

**Comment by GitAdict** [comment]
youtube-dl https://www.france.tv/france-3/scooby-doo-mysteres-associes/saison-1/461927-la-finale-des-amateurs-de-mystere.html
[FranceTVSite] 461927-la-finale-des-amateurs-de-mystere: Downloading webpage
[FranceTV] 3d0a9ec9-950c-41c9-9e77-9ca89b4d4233: Downloading video JSON
[FranceTV] 3d0a9ec9-950c-41c9-9e77-9ca89b4d4233: Downloading geo restriction info
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
