### ISSUE TITLE
youtube-dl not working on Comedy Central

### ISSUE THREAD

**Issue by so-tired-now** [ytdl-org/youtube-dl#25154]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm trying to use youtube-dl to get some stuff off Comedy Central.  I keep getting the same error back, shown below.  I am using the most updated version (2000.05.03) and I've also updated Python.  I use a mac.  Command line (using verbose) along with output below:

$ youtube-dl -v http://www.cc.com/video-clips/kfpdwr/the-daily-show-with-jon-stewart-indecision-2000---2000-gop-debate
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.cc.com/video-clips/kfpdwr/the-daily-show-with-jon-stewart-indecision-2000---2000-gop-debate']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.03
[debug] Python version 2.7.2 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg present, ffprobe present, rtmpdump Reason
[debug] Proxy map: {}
[ComedyCentral] the-daily-show-with-jon-stewart-indecision-2000---2000-gop-debate: Downloading webpage
[ComedyCentral] Downloading JSON metadata
[ComedyCentral] b502b41e-ed00-11e0-aca6-0026b9414f30: Downloading info
[ComedyCentral] b502b41e-ed00-11e0-aca6-0026b9414f30: Extracting information
[ComedyCentral] b502b41e-ed00-11e0-aca6-0026b9414f30: Downloading video urls
WARNING: Unable to download XML: <urlopen error [Errno 1] _ssl.c:503: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol>
[download] Downloading playlist: Indecision 2000 - 2000 GOP Debate
[ComedyCentral] playlist Indecision 2000 - 2000 GOP Debate: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: Indecision 2000 - 2000 GOP Debate

**Comment by dstftw** [comment]
Outdated python.

**Comment by so-tired-now** [comment]
Python is up to date.  Any other ideas?

**Comment by dstftw** [comment]
No, it does not.
>Python version 2.7.2
