### ISSUE TITLE
Using --flat-playlist leads to ignoring --dateafter flag

### ISSUE THREAD

**Issue by dwil233** [ytdl-org/youtube-dl#25158]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.05.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\>youtube-dl -i -v --flat-playlist -j --dateafter 20200301 --datebefore 20200331 --skip-download https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-i', '-v', '--flat-playlist', '-j', '--dateafter', '20200301', '--datebefore', '20200331', '--skip-download', 'https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.01.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-02-06-343ccfc, ffprobe git-2020-02-06-343ccfc
[debug] Proxy map: {}
{"title": "Logarithm Fundamentals | Lockdown math ep. 6", "url": "cEvgcoyZvB4", "id": "cEvgcoyZvB4", "_type": "url", "ie_key": "Youtube"}
{"title": "Imaginary interest rates | Lockdown math ep. 5", "url": "IAEASE5GjdI", "id": "IAEASE5GjdI", "_type": "url", "ie_key": "Youtube"}
{"title": "What is Euler's formula actually saying? | Lockdown math ep. 4", "url": "ZxYOEwM6Wbk", "id": "ZxYOEwM6Wbk", "_type": "url", "ie_key": "Youtube"}
{"title": "Complex number fundamentals | Lockdown math ep. 3", "url": "5PcpBw5Hbwo", "id": "5PcpBw5Hbwo", "_type": "url", "ie_key": "Youtube"}
{"title": "Trigonometry fundamentals | Lockdown math ep. 2", "url": "yBw67Fb31Cs", "id": "yBw67Fb31Cs", "_type": "url", "ie_key": "Youtube"}
{"title": "The simpler quadratic formula | Lockdown math ep. 1", "url": "MHXO86wKeDY", "id": "MHXO86wKeDY", "_type": "url", "ie_key": "Youtube"}
{"title": "Lockdown math announcement", "url": "ppWPuXsnf1Q", "id": "ppWPuXsnf1Q", "_type": "url", "ie_key": "Youtube"}

.... and around 100 items more
```

## Description

I'm trying to get a list of video IDs (not videos themselves, --flat-playlist -j for that) from a youtube channel for a particular period of time, e.g. for March 2020 I put --dateafter 20200301 and --datebefore 20200331 parameters . But it returns the whole channel video list instead of just 3 videos.

Here is the command line:
```youtube-dl -i --flat-playlist -j --dateafter 20200301 --datebefore 20200331 --skip-download https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw```

If I substitute --date flags with --playlist-end 5 for example, it's gonna work as expected (returns only 5 items).

**Comment by dstftw** [comment]
Upload date is not available in flat playlist mode.
