### ISSUE TITLE
User and password doesn't work for Dplay.com

### ISSUE THREAD

**Issue by ijbh** [ytdl-org/youtube-dl#25150]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.05.03**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl https://www.dplay.se/videos/alla-mot-alla-med-filip-och-fredrik/112705 --username pingu72300@gmail.com --password Blast0nphase!
[DPlay] alla-mot-alla-med-filip-och-fredrik/112705: Downloading token
[DPlay] alla-mot-alla-med-filip-och-fredrik/112705: Downloading JSON metadata
[DPlay] alla-mot-alla-med-filip-och-fredrik/112705: Downloading JSON metadata
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
```

## Description

Does this error mean that the username and password workaround does not work for this particular site? Or does it simply mean that somehow I have entered the wrong code?

**Comment by ijbh** [comment]
I'm using youtube-dl through Terminal on Mac I should say

**Comment by SYSophie** [comment]
@ijbh use --netrc with the add-on cookies.txt. --username and --password is no longer enough to download premium or content that requires an account.

**Comment by ijbh** [comment]
Do you know of a good ste-by-step guide for how I do that on a Mac? Especially with the add on?

**Comment by ijbh** [comment]
> @ijbh use --netrc with the add-on cookies.txt. --username and --password is no longer enough to download premium or content that requires an account.

@SYSophie Do you happen to know of a good step-by-step guide for how I do that on a Mac? And with the add on cookies.txt explained.

**Comment by felisucoibi** [comment]
> @ijbh use --netrc with the add-on cookies.txt. --username and --password is no longer enough to download premium or content that requires an account.

It works for you doing it? what is your exact command to make it work? i used --cookie cookies.txt and it does not work. You are using one called --netrc ?

**Comment by SYSophie** [comment]
@ijbh sorry it's the --cookies flag you're supposed to use combined with referring to the txt file of the cookie created by the add-on.

@felisucoibi yes it works maybe you need to cleanup your browsers cookie/history a bit?

**Comment by felisucoibi** [comment]
> @ijbh sorry it's the --cookies flag you're supposed to use combined with referring to the txt file of the cookie created by the add-on.
> 
> @felisucoibi yes it works maybe you need to cleanup your browsers cookie/history a bit?

Can yo explain step by step what you do?

I have the cookie, so i use the -cookie cookie.txt flag, but you said you also use --netrc? what is the format of the .netrc file, and where it needs to be placed? Thanks.

**Comment by SYSophie** [comment]
@felisucoibi I mixed --netrc with --cookie. I only use --cookie together with a cookie.txt generated with the cookies.txt add-on for example FF or Chrome.

**Comment by ijbh** [comment]
@SYSophie Did I do this wrong?

> youtube-dl https://www.dplay.se/videos/alla-mot-alla-med-filip-och-fredrik/112705 --cookies
> Usage: youtube-dl [OPTIONS] URL [URL...]
> 
> youtube-dl: error: --cookies option requires an argument

I apologize. I'm a novice.

**Comment by ijbh** [comment]
I downloaded the cookies.txt file through the add on. Do I have to put the txt-file in a specific place?

**Comment by ijbh** [comment]
@SYSophie Nevermind my earlier posts! OMG I got it to work! Lol, I'm so proud of myself :)

Thank you for the help!!!

**Comment by felisucoibi** [comment]
> @SYSophie Nevermind my earlier posts! OMG I got it to work! Lol, I'm so proud of myself :)
> 
> Thank you for the help!!!

what command are you using, wich url are you testing just to try it also mys elf... i tried this:

youtube-dl --cookie cookies.txt https://es.dplay.com/dmax/el-resurgir-de-la-atlantida/la-atlantida-en-donana/

and is not working :( error asking me for user and pass

**Comment by ijbh** [comment]
No, you need to write the pathway to the cookies.txt. Like this:

> youtube-dl --cookies /Users/JohnDoe/Downloads/cookies.txt https://www.dplay.se/videos/XXXXXX/119904


You also obviously must have logged in to the site before (so that there is a username and password in the cookies.txt file).

**Comment by SYSophie** [comment]
> @SYSophie Nevermind my earlier posts! OMG I got it to work! Lol, I'm so proud of myself :)
> 
> Thank you for the help!!!

Nice work!
