### ISSUE TITLE
HELP with downloading from Shahid.net (DRM protected)

### ISSUE THREAD

**Issue by Magicard789** [ytdl-org/youtube-dl#25163]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.05.03**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Hi all,

I have been downloading from shahid.net for a while when I could find the m3u8, but now it seems like it is all fragments and can't find the video m3u8 link on the browser page inspection.

I tried youtube-dl but it doesn't seem to work i get the following error:

"C:\Users\Fatbit\Desktop\ffmpeg-20200504-5767a2e-win64-static\bin>youtube-dl https://shahid.mbc.net/ar/series/%D8%A7%D9%84%D8%A8%D8%B1%D9%86%D8%B3-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-1-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-1/episode-410152
[Shahid] 410152: Downloading JSON metadata
ERROR: This video is DRM protected.

C:\Users\Fatbit\Desktop\ffmpeg-20200504-5767a2e-win64-static\bin>"

the link I'm trying to download is 

https://shahid.mbc.net/ar/series/%D8%A7%D9%84%D8%A8%D8%B1%D9%86%D8%B3-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-1-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-1/episode-410152

I have been trying for 2 days and I couldn't reach to a solution

I would really appreciate if an expert can help with this issue :'(

Thanks

**Comment by dstftw** [comment]
You can't.

**Comment by Magicard789** [comment]
@dstftw 

why so?

**Comment by mysticaltech** [comment]
Why not, please find a way to make shahid work again, it would be great to support both arabic and english; the url schema changes from /ar/ to /en/. I know the content is know DRM'd but it can be easily decrypted with https://archive.org/details/github.com-tomer8007-widevine-l3-decryptor_-_2020-10-23_21-16-54. So we just need YT-DL to do it's work of downloading the encrypted video content; please! https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/shahid.py is now broken!
