### ISSUE TITLE
How do you put the OUTPUT into a GUI in Tkinter?

### ISSUE THREAD

**Issue by Gloryness** [ytdl-org/youtube-dl#25173]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

_**This is for Python, not the terminal.**_

I'm building a GUI for downloading videos. It's coming along really well, but I need to somehow get the downloading output that you see in the terminal/console, into a Text-GUI in tkinter.

- [x] **I have changed the stdout to the text box, but whenever I download something, it crashes - as if all of a sudden it forces the output to not be in the GUI causing it to crash and then says:**
"`Process finished with exit code 120`"

I'd appreciate any help!

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#embedding-youtube-dl, `my_hook`.

**Comment by Gloryness** [comment]
lol thanks
