### ISSUE TITLE
Random "No video formats found" ²

### ISSUE THREAD

**Issue by triplesixman** [ytdl-org/youtube-dl#25188]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.05.03**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\Admin\Downloads\test>C:\Users\Admin\Downloads\test\youtube-dl.exe https://youtu.be/nKJmJYNfiAQ --no-cache-dir --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://youtu.be/nKJmJYNfiAQ', '--no-cache-dir', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] nKJmJYNfiAQ: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\youtube.py", line 2394, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hey. This is the continuation of the following post: #25187

The problem also occurs without using a proxy, by going directly to the server's ip address.

I thought it could come from the dedicated server, but finally not, because I reproduced it on my computer with the .exe version of youtube-dl (see logs above).

I think you will also be able to reproduce it if you try to download 10 videos in a row, one after the other.

If you need details or access, we can continue by email, I'm waiting for your return for that.

Thank you

**Comment by dstftw** [comment]
Post the output of `--dump-pages`.

**Comment by triplesixman** [comment]
> Post the output of `--dump-pages`.

https://pastebin.com/m6dRwg1f
