### ISSUE TITLE
youtube-dl support arm architecture?

### ISSUE THREAD

**Issue by Stephen988** [ytdl-org/youtube-dl#25205]
Hi, I have installed container on docker but on my raspberry pi 4 won't start, I also have added port forwarding on my router but nothig.
Instead using youtube-dl container on openmediavault x86 in a virtual machine, work well.

**Comment by dstftw** [comment]
Any OS/architecture capable running python.

**Comment by Stephen988** [comment]
> Any OS/architecture capable running python.

doesn't work on my raspberry instead on pc yes

**Comment by Stephen988** [comment]
> Any OS/architecture capable running python.

I need open issue thread?

**Comment by Hrxn** [comment]
> I need open issue thread?

With the Python project maybe?

**Comment by Stephen988** [comment]
> > I need open issue thread?
> 
> With the Python project maybe?

here there are some user can test it on raspberry?
