### ISSUE TITLE
youtube-dl.exe is not downloading from Github website

### ISSUE THREAD

**Issue by pranjalisnow** [ytdl-org/youtube-dl#25203]
## Checklist

- [x] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2020.05.08**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
This is the error..

youtube-dl -U
Updating to version 2020.05.08 ...
ERROR: unable to download latest version

**Comment by pranjalisnow** [comment]
I'm trying to download from Bangalore, India.

Tried downloading from this site too...

https://github.com/ytdl-org/youtube-dl/releases

Logs:
=============================
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-U']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
Updating to version 2020.05.08 ...
ERROR: unable to download latest version
=============================

**Comment by pranjalisnow** [comment]
Please find the complete log below:

===============================
youtube-dl -v -U
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-U']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
Updating to version 2020.05.08 ...
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\update.py", line 106, in update_self
  File "C:\Python\Python34\lib\http\client.py", line 549, in read
  File "C:\Python\Python34\lib\http\client.py", line 699, in _safe_read
  File "C:\Python\Python34\lib\socket.py", line 378, in readinto
  File "C:\Python\Python34\lib\ssl.py", line 748, in recv_into
  File "C:\Python\Python34\lib\ssl.py", line 620, in read
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

ERROR: unable to download latest version
================================

**Comment by pranjalisnow** [comment]
Just tried downloading using TOR browser, from (https://github.com/ytdl-org/youtube-dl/releases).

It downloaded fine!

FYI.

**Comment by dstftw** [comment]
Network issue on your side.
