### ISSUE TITLE
ABC [GO]: Unable to retrieve required files for playback.

### ISSUE THREAD

**Issue by patdavid** [ytdl-org/youtube-dl#25207]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl --version
2020.05.08

$ youtube-dl https://abc.com/shows/the-goldbergs/episode-guide/season-07/22-the-fakeup -v
[debug] System config: []
[debug] User config: [u'--download-archive', u'/home/pat/archive-youtube-dl.txt', u'--retries', u'infinite', u'--fragment-retries', u'infinite', u'--abort-on-unavailable-fragment']
[debug] Custom config: []
[debug] Command-line args: [u'https://abc.com/shows/the-goldbergs/episode-guide/season-07/22-the-fakeup', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-96-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg N-95880-gd07d1c1, ffprobe N-95880-gd07d1c1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[Go] 22-the-fakeup: Downloading webpage
[Go] VDKA0_uixgx8ru: Downloading JSON metadata
[Go] VDKA0_uixgx8ru: Retrieving Media Token
[Go] VDKA0_uixgx8ru: Downloading JSON metadata
ERROR: Go said: 1025:Unable to retrieve required files for playback. Please try again in a few minutes.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/go.py", line 205, in _real_extract
    raise ExtractorError('%s said: %s' % (self.IE_NAME, error_message), expected=True)
ExtractorError: Go said: 1025:Unable to retrieve required files for playback. Please try again in a few minutes.
```

## Description

These URL's were working fine just a few weeks ago.  This change seems to have happened recently?

**Comment by magnum32** [comment]
I'm having the same problems with these links as well: 

https://abc.com/shows/good-morning-america/episode-guide/2020-04/14-tuesday-apr-14-2020

https://abc.com/shows/good-morning-america/episode-guide/2020-05/01-friday-may-1-2020

https://abc.com/shows/who-wants-to-be-a-millionaire/episode-guide/season-01/04-in-the-hot-seat-anthony-anderson-ike-barinholtz-and-hannibal-buress

https://abc.com/shows/good-morning-america/episode-guide/2020-05/02-saturday-may2-2020

**Comment by tmthywynn8** [comment]
This is because the method for retrieving the video ID has changed.

$$$$ Solution:

Open [/youtube_dl/extractor/go.py](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/go.py), go to line 141, and change it to read:  
```
                    r'\bvideoIdCode["\']\s*:\s*["\'](vdka\w+)'
```

**Comment by magnum32** [comment]
is this issue going to be resolved in the next Youtube-DL version?

**Comment by patdavid** [comment]
Oh, fantastic @tmthywynn8 - thank you very much for the solution!

**Comment by ryanhilton** [comment]
Thank you @tmthywynn8!

**Comment by magnum32** [comment]
i get this message after trying to download the free videos from abc ,com when i check the log: [05/18/20 09:47:29] ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.

**Comment by magnum32** [comment]
i cant locate the youtube-dl extractor on my PC

**Comment by DarF234** [comment]
Solution:

Open /youtube_dl/extractor/go.py, go to line 141, and change it to read:

                    r'\bvideoIdCode["\']\s*:\s*["\'](vdka\w+)'

**This is the exact line 141 I have in go.py and I am STILL receiving error 1025!**
**It is no longer (and hasn't been since not long after this issue was closed) a solution to this problem!**
**Please look into it soon. My contribution error data is at #26058**

**Comment by tony-izzo** [comment]
It looks like #25216 is the pull request that fixes this problem, but the PR is still open, and when I look at [that line in master](https://github.com/ytdl-org/youtube-dl/blob/a4ed50bb84658b7e77cbb37597c36fa62a9acd4b/youtube_dl/extractor/go.py#L141) it is not the same as what's in the fix, so it looks like it never got merged.

I have a local copy based on a commit from around that same time in which I applied the patch manually.  It worked in May, and I just tried it again and it still works (for me) now. It may not be the only problem, but I think #25216 needs to be merged at the very least.

**Comment by jhall39** [comment]
Any chance this will be merged soon?

**Comment by AravindhStanley** [comment]
Hope the developers merge the changes

**Comment by merval** [comment]
:-( I tried this fix, and I started getting a RegexNotFoundError:
`ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/DanWalker/PycharmProjects/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/Users/DanWalker/PycharmProjects/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Users/DanWalker/PycharmProjects/youtube-dl/youtube_dl/extractor/go.py", line 189, in _real_extract
    url, video_id, requestor_id, resource)
  File "/Users/DanWalker/PycharmProjects/youtube-dl/youtube_dl/extractor/adobepass.py", line 1453, in _extract_mvpd_auth
    self._DOWNLOADING_LOGIN_PAGE)
  File "/Users/DanWalker/PycharmProjects/youtube-dl/youtube_dl/extractor/adobepass.py", line 1365, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "/Users/DanWalker/PycharmProjects/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/Users/DanWalker/PycharmProjects/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by alma359** [comment]
This is still not fixed. Please merge the change!

**Comment by ryanhilton** [comment]
> This is still not fixed. Please merge the change!

Seriously! +1

**Comment by Aholicknight** [comment]
Please merge this!

**Comment by choc96208** [comment]
Not sure what the notion of merging of is, but I support the motion to get this issue fixed. Will save me from making the edit every time I update the software.

**Comment by Aholicknight** [comment]
> Not sure what the notion of merging of is, but I support the motion to get this issue fixed. Will save me from making the edit every time I update the software.

@choc96208 on the other version of youtube-dl it works fine.
