### ISSUE TITLE
Instagram live

### ISSUE THREAD

**Issue by avagraha** [ytdl-org/youtube-dl#25210]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

There is a way for donwload from here
http://postimg.cc/MnCj6Wp9
 Obviously after the end of the live. thanks.
PS: stories are ok.

**Comment by avagraha** [comment]
Please a reply to my question.
No log available since there is not an url.



  ----- Original Message -----

**Comment by avagraha** [comment]
Done with an app

**Comment by haleyngonadi** [comment]
> Done with an app

Hi, did you figure this out? Which app?
