### ISSUE TITLE
sfopera.com free stream until Sunday midnight (PDT)

### ISSUE THREAD

**Issue by claud9999** [ytdl-org/youtube-dl#25213]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Playlist: https://sfopera.com/opera-is-on/streaming/
- Single video: https://players.brightcove.net/2079714550001/experience_5eac6c674707d500237000af/index.html

## Description

Seems brightcove keeps updating their URL structure. While I'd like to write in the changes for this site, I'm new to youtube-dl so I'm hoping someone can get it going before the free stream is no longer available.

**Comment by claud9999** [comment]
Answering my own question with a tip: start playing the video (in this case there are 4 videos) right click and select "Player Information". Then copy the information and youtube-dl the URL http://players.brightcove.net/<acct id>/<player_id>_default/index.html?videoId=<video_id> .

**Comment by claud9999** [comment]
Note that this weekend's free stream of Salome, I'm able to download the video stream but not capture the subtitles. --list-subs reports no subtitle tracks. But clearly there are subtitles.

**Comment by llacb47** [comment]
You can get the stream URL manually with devtools and download it.

**Comment by claud9999** [comment]
> You can get the stream URL manually with devtools and download it.
> 
> `$ youtube-dl https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/2079714550001/330651db-446b-4956-8ca4-b03b9abed673/10s/master.m3u8?fastly_token=NWVlZWRkZDVfOWNlY2U1NTkwMzg3MTBlNWMyYThhMmNiZGQyMmQyYTVkNzliYTNjNWU0MGEwOGQxN2EyN2Y0YmQwMzEwMzkyMg%3D%3D`

I'm able to d/l the video no problem, just not getting the subtitles. Do you get the subtitles using this?

**Comment by llacb47** [comment]
No, i just edited my comment, I did it manually with ffmpeg.

**Comment by claud9999** [comment]
this subtitle issue is affecting the metopera.org free stream as well; closing this ticket and opening a new ticket wrt subtitles.
