### ISSUE TITLE
Why youtube-dl can't parse the url properly ?

### ISSUE THREAD

**Issue by slucks** [ytdl-org/youtube-dl#25214]
I find a strange fact that a video in youtube can't be downloaded with youtube-dl.

> url="https://www.youtube.com/watch?v=VdjCcztoRmw"
> youtube-dl $url
> 

No error info during downloading with youtube-dl,when playing the downloaded video,and compare to play the video on the url with firefox,the content in your downloaded and on the webpage are totally different,in fact youtube-dl never download it at all,i think youtube-dl can't parse the url https://www.youtube.com/watch?v=VdjCcztoRmw properly, Why?

**Comment by rautamiekka** [comment]
Looks like you're on Linux. Whenever you're referencing a variable in Bash you should double-quote the ref cuz Bash might cut the URL and place the process in the background. Just quoting the string during var assignment doesn't do.
