### ISSUE TITLE
Unable to DL from watch.cookingchannel.tv however watch.travelchannel.com works

### ISSUE THREAD

**Issue by greenxeyezz** [ytdl-org/youtube-dl#25227]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--newline', '-i', '-o', 'T:\\Youtube-DL\\%(series)s\\Season %(season_number)02d\\%(series)s - S%(season_number)02dE%(episode_number)02d - %(title)s - %(height)sp-WEBDL.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', '--cookies', 'T:\\Youtube-DL\\zFiles\\cookies.txt', '--verbose', 'https://watch.cookingchanneltv.com/tv-shows/food-paradise/full-episodes/most-valuable-plates']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[Discovery] most-valuable-plates: Downloading content JSON metadata
[Discovery] most-valuable-plates: Downloading streaming JSON metadata
ERROR: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:
```

## Description

Have been successful in downloading from watch.travelchannel.com using the --cookies flag.
Use an extension in chrome to do this. Have verified it has the netscape code at top.

Have been able to use youtubedl-gui AND youtubedl.exe to download from watch.travelchannel.com with the same cookies file.

Have been UNABLE to download from watch.cookingchanneltv.com using the same methods in ANY variation of youtubedl.

Attempted to use firefox cookie extension. Works with travelchannel, does not work with cookingchanneltv.com.

Have tried with an HLS stream finder, still no go. 

Also tried with the --ap-mso whatever flag, for DirectTV, states in the log, to use --cookies, so I used that.

Works for travelchannel, but again, does not work with cookingchannel. Have not tried the other "scrips" channels/websites. 

HGTV---Works
FoodNetwork---Works
TLC---Works
DiscoveryGo---Works
InvestigationDiscovery---Works
AnimalPlanet---Works
ScienceChannel---Works
watch.diynetwork.com--FAILED
watch.cookingchanneltv.com---FAILED

**Comment by remitamine** [comment]
the cookies should be created for the specific website(the same domain) if the cookie file does not contain the Auth Token cookie entry for diynetwork.com domain you won't be able to download videos requiring TV Provider Auth from DIY Network(same goes for Cooking Channel TV).

**Comment by greenxeyezz** [comment]
I created the cookies from EACH site. Each site worked EXCEPT for those two.

**Comment by greenxeyezz** [comment]
Do I just PM you the Direct TV login information?
