### ISSUE TITLE
abort on error, but ignore unavailable

### ISSUE THREAD

**Issue by Miosame** [ytdl-org/youtube-dl#25247]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

There's two error handling scenarios via arguments, ignore and abort. How is one supposed to ignore the much more common "unavailable videos", while still aborting on _actual_ errors like 429 and others?

```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
--abort-on-error                 Abort downloading of further videos (in the
                                 playlist or the command line) if an error
                                 occurs
```

**Comment by dstftw** [comment]
Currently you can't.
