### ISSUE TITLE
あるプレイリストだけ動画がダウンロードできない

### ISSUE THREAD

**Issue by arakawa995** [ytdl-org/youtube-dl#25258]
## Checklist

- [x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
![bandicam 2020-05-13 18-53-05-626](https://user-images.githubusercontent.com/59131164/81798565-28ee1980-954b-11ea-8c1c-b797b2550865.jpg)
E:\downloads\youtube-dl>youtube-dl --write-thumbnail -f bestvideo+bestaudio --merge-output-format mp4 https://www.youtube.com/playlist?list=PLKRhhk0lEyzPV58dAXzmfZle_wg03CLhl
[youtube:playlist] PLKRhhk0lEyzPV58dAXzmfZle_wg03CLhl: Downloading webpage
[download] Downloading playlist: 高校(数A)1【場合の数と確率】
[youtube:playlist] playlist 高校(数A)1【場合の数と確率】: Downloading 32 videos
[download] Downloading video 1 of 32
[youtube] ZNleTg25fl0: Downloading webpage
[youtube] ZNleTg25fl0: Downloading thumbnail ...
[youtube] ZNleTg25fl0: Writing thumbnail to: 【高校数学】　　数A－１　　集合①-ZNleTg25fl0.jpg
[download] 【高校数学】　　数A－１　　集合①-ZNleTg25fl0.mp4 has already been downloaded and merged
[download] Downloading video 2 of 32
[youtube] JWuGqiGUKH8: Downloading webpage
[youtube] JWuGqiGUKH8: Downloading thumbnail ...
[youtube] JWuGqiGUKH8: Writing thumbnail to: 【高校数学】　　数A－２　　集合②-JWuGqiGUKH8.jpg
[download] 【高校数学】　　数A－２　　集合②-JWuGqiGUKH8.mp4 has already been downloaded and merged
[download] Downloading video 3 of 32
[youtube] aF37RF1sLTo: Downloading webpage
[youtube] aF37RF1sLTo: Downloading thumbnail ...
[youtube] aF37RF1sLTo: Writing thumbnail to: 【高校数学】　　数A－３　　集合③-aF37RF1sLTo.jpg
[download] 【高校数学】　　数A－３　　集合③-aF37RF1sLTo.mp4 has already been downloaded and merged
[download] Downloading video 4 of 32
[youtube] R8GIIHDfcNE: Downloading webpage
[youtube] R8GIIHDfcNE: Downloading thumbnail ...
[youtube] R8GIIHDfcNE: Writing thumbnail to: 【高校数学】　　数A－４　　場合の数①　・　基本編-R8GIIHDfcNE.jpg
[download] 【高校数学】　　数A－４　　場合の数①　・　基本編-R8GIIHDfcNE.mp4 has already been downloaded and merged
[download] Downloading video 5 of 32
[youtube] FkOCL5MZ5wM: Downloading webpage

ERROR: Interrupted by user

Only a playlist can download thumbnails only
Click here for the link
https://www.youtube.com/playlist?list=PLKRhhk0lEyzPV58dAXzmfZle_wg03CLhl
I have confirmed that it can be played on a browser. I don't know how to resolve this error reaction.
You can save other similar playlists. I can only think that something is wrong. I am making an error by stopping on the way
The actual screen is also projected.
Please let me know what is wrong and what is wrong. We hope to solve the problem as soon as possible. Professor, please.

**Comment by dstftw** [comment]
Read log?
>[download] 【高校数学】　　数A－１　　集合①-ZNleTg25fl0.mp4 has already been downloaded and merged

>has already been downloaded and merged

**Comment by arakawa995** [comment]
thanks i read log
