### ISSUE TITLE
Get output name when using external downloader 

### ISSUE THREAD

**Issue by NightMachinary** [ytdl-org/youtube-dl#25250]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

By searching through the issues, I have found this script for streaming videos, and I have tried adapting it to use `aria2c`:

```
#!/usr/bin/env python3
import subprocess, sys
import youtube_dl


player_run = False
p = None


def hook(status):
    global player_run, p

    if not player_run:
        print(f"Running mpv for {status['filename']} ...")
        player_run = True
        p = subprocess.Popen(['mpv', status['filename']])


opts = {
    'format': 'best',
    'nopart': True,
    'progress_hooks': [hook],
    # 'verbose': True,
    # 'external_downloader': 'aria2c',
    'noplaylist': True,
    'writesubtitles': True,
}

with youtube_dl.YoutubeDL(opts) as ydl:
    ydl.download([sys.argv[1]])

p.wait()
```
The problem is that when using an external downloader, the progress hook won't get called. How can I work around this?

**Comment by dstftw** [comment]
You can't, progress reporting does not work with external downloaders.
