### ISSUE TITLE
How to change the pythonscript file youtube-dl?

### ISSUE THREAD

**Issue by lutzig** [ytdl-org/youtube-dl#25251]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Further to the mention: "/usr/bin/env: «python»: Aucun fichier ou dossier de ce type" and because my ticket no 25249 had been closed without any issue, I had contacted python's support. It appears that the trouble is in the scrypt file of youtube-dl in what it is writen:

#!/usr/bin/env python

instead of : #!/usr/bin/env python3

I'd like to do the change by myself but how can I do??

Thank you for your help!

**Comment by dstftw** [comment]
Again: setup your environment so that python3 is available as `python`.
