### ISSUE TITLE
Is it possible to provide html websource as argument or in ydl.extract_info??

### ISSUE THREAD

**Issue by tugceozgur** [ytdl-org/youtube-dl#25260]
It is not possible now to pass html webpage source to youtube_dl but would be great to find some workaround for that. Tried to manually pass the argument on `ydl.extract_info(website)` and related _real_extract functions and many other dependent ones, but since each file has slightly different implementation of getting page source, I stuck at some point. Is it possible to implement this option. Could help us since we are also parsing some paywalled articles?

**Comment by dstftw** [comment]
Setup local webserver and serve via local URL.

**Comment by tugceozgur** [comment]
I do not want the youtube_dl to download, request the URL. Instead just would like to pass the html dom tree. Would it prevent it or what will your suggestion actually does? Could you give me an example of implementation if possible? Thank you @dstftw

**Comment by dstftw** [comment]
Again: it's not possible to pass HTML.

**Comment by tugceozgur** [comment]
Okay, good to know that the implementation is not easy maybe not possible. Thanks
