### ISSUE TITLE
playlist-reverse NOT functioning properly!

### ISSUE THREAD

**Issue by RangaSE** [ytdl-org/youtube-dl#25269]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.05.08**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description
"--playlist-reverse" is NT reversing..!

WRITE DESCRIPTION HERE
( 12-05-2020 | 22:23:18.83 ) C:\Users\VENKAT> youtube-dl[2020.05.08] -ciw --yes-playlist -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --playlist-reverse --playlist-start 5 --playlist-end 10 --write-auto-sub --write-sub --embed-subs --embed-thumbnail -o "F:\Videos\%(playlist)s\%(title)s(u%(upload_date)s; %(duration)s; %(height)sp%(fps)s)YT '%(uploader)s'.%(ext)s" -- https://www.youtube.com/playlist?list=PLjhrDIztP9pdKJCdrPrrRxs5hasj7dm_i
[youtube:playlist] PLjhrDIztP9pdKJCdrPrrRxs5hasj7dm_i: Downloading webpage
[download] Downloading playlist: SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018
[youtube:playlist] playlist SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018: Downloading 6 videos
[download] Downloading video 1 of 6
[youtube] cKShI8QYjNI: Downloading webpage
WARNING: video doesn't have subtitles
[youtube] cKShI8QYjNI: Looking for automatic captions
WARNING: Couldn't find automatic captions for cKShI8QYjNI
[youtube] cKShI8QYjNI: Downloading MPD manifest
[youtube] cKShI8QYjNI: Downloading thumbnail ...
[youtube] cKShI8QYjNI: Writing thumbnail to: F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ EP 68 _ 17-12-18 _ SVBC TTD(u20181217; 1415; 720p30)YT 'SVBC TTD'.jpg
[dashsegments] Total fragments: 267
[download] Destination: F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ EP 68 _ 17-12-18 _ SVBC TTD(u20181217; 1415; 720p30)YT 'SVBC TTD'.f136.mp4
[download] 100% of 224.15MiB in 10:01
[dashsegments] Total fragments: 143
[download] Destination: F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ EP 68 _ 17-12-18 _ SVBC TTD(u20181217; 1415; NApNA)YT 'SVBC TTD'.f140.m4a
[download] 100% of 21.84MiB in 01:59
[ffmpeg] Merging formats into "F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ EP 68 _ 17-12-18 _ SVBC TTD(u20181217; 1415; 720p30)YT 'SVBC TTD'.mp4"
Deleting original file F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ EP 68 _ 17-12-18 _ SVBC TTD(u20181217; 1415; 720p30)YT 'SVBC TTD'.f136.mp4 (pass -k to keep)
Deleting original file F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ EP 68 _ 17-12-18 _ SVBC TTD(u20181217; 1415; NApNA)YT 'SVBC TTD'.f140.m4a (pass -k to keep)
[ffmpeg] There aren't any subtitles to embed
[atomicparsley] Adding thumbnail to "F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ EP 68 _ 17-12-18 _ SVBC TTD(u20181217; 1415; 720p30)YT 'SVBC TTD'.mp4"
[download] Downloading video 2 of 6
[youtube] jv3s9inD8h0: Downloading webpage
WARNING: video doesn't have subtitles
[youtube] jv3s9inD8h0: Looking for automatic captions
WARNING: Couldn't find automatic captions for jv3s9inD8h0
[youtube] jv3s9inD8h0: Downloading MPD manifest
[youtube] jv3s9inD8h0: Downloading thumbnail ...
[youtube] jv3s9inD8h0: Writing thumbnail to: F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ EP 69 _ 31-12-18 _ SVBC TTD(u20181231; 1353; 720p30)YT 'SVBC TTD'.jpg
[dashsegments] Total fragments: 255
[download] Destination: F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ EP 69 _ 31-12-18 _ SVBC TTD(u20181231; 1353; 720p30)YT 'SVBC TTD'.f136.mp4
[download] 100% of 221.45MiB in 06:44
[dashsegments] Total fragments: 137
[download] Destination: F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ EP 69 _ 31-12-18 _ SVBC TTD(u20181231; 1353; NApNA)YT 'SVBC TTD'.f140.m4a
[download] 100% of 20.88MiB in 01:49
[ffmpeg] Merging formats into "F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ EP 69 _ 31-12-18 _ SVBC TTD(u20181231; 1353; 720p30)YT 'SVBC TTD'.mp4"
Deleting original file F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ EP 69 _ 31-12-18 _ SVBC TTD(u20181231; 1353; 720p30)YT 'SVBC TTD'.f136.mp4 (pass -k to keep)
Deleting original file F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ EP 69 _ 31-12-18 _ SVBC TTD(u20181231; 1353; NApNA)YT 'SVBC TTD'.f140.m4a (pass -k to keep)
[ffmpeg] There aren't any subtitles to embed
[atomicparsley] Adding thumbnail to "F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ EP 69 _ 31-12-18 _ SVBC TTD(u20181231; 1353; 720p30)YT 'SVBC TTD'.mp4"
[download] Downloading video 3 of 6
[youtube] hIaPjB84fGs: Downloading webpage
WARNING: video doesn't have subtitles
[youtube] hIaPjB84fGs: Looking for automatic captions
WARNING: Couldn't find automatic captions for hIaPjB84fGs
[youtube] hIaPjB84fGs: Downloading MPD manifest
[youtube] hIaPjB84fGs: Downloading thumbnail ...
[youtube] hIaPjB84fGs: Writing thumbnail to: F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ Ep 70 _ 19-12-18 _ SVBC TTD(u20181219; 1506; 720p30)YT 'SVBC TTD'.jpg
[dashsegments] Total fragments: 284
[download] Destination: F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ Ep 70 _ 19-12-18 _ SVBC TTD(u20181219; 1506; 720p30)YT 'SVBC TTD'.f136.mp4
[download] 100% of 259.91MiB in 05:34
[dashsegments] Total fragments: 152
[download] Destination: F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ Ep 70 _ 19-12-18 _ SVBC TTD(u20181219; 1506; NApNA)YT 'SVBC TTD'.f140.m4a
[download] 100% of 23.24MiB in 01:22
[ffmpeg] Merging formats into "F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ Ep 70 _ 19-12-18 _ SVBC TTD(u20181219; 1506; 720p30)YT 'SVBC TTD'.mp4"
Deleting original file F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ Ep 70 _ 19-12-18 _ SVBC TTD(u20181219; 1506; 720p30)YT 'SVBC TTD'.f136.mp4 (pass -k to keep)
Deleting original file F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ Ep 70 _ 19-12-18 _ SVBC TTD(u20181219; 1506; NApNA)YT 'SVBC TTD'.f140.m4a (pass -k to keep)
[ffmpeg] There aren't any subtitles to embed
[atomicparsley] Adding thumbnail to "F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam Nerchukundam _ Ep 70 _ 19-12-18 _ SVBC TTD(u20181219; 1506; 720p30)YT 'SVBC TTD'.mp4"
[download] Downloading video 4 of 6
[youtube] _tsWGzi5U6o: Downloading webpage
WARNING: video doesn't have subtitles
[youtube] _tsWGzi5U6o: Looking for automatic captions
WARNING: Couldn't find automatic captions for _tsWGzi5U6o
[youtube] _tsWGzi5U6o: Downloading MPD manifest
[youtube] _tsWGzi5U6o: Downloading thumbnail ...
[youtube] _tsWGzi5U6o: Writing thumbnail to: F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam  Nerchukundam-English Subtiltles _ EP 71 _ 20-12-18 _ SVBC TTD(u20181220; 1552; 720p30)YT 'SVBC TTD'.jpg
[dashsegments] Total fragments: 292
[download] Destination: F:\Videos\SVBC TTD-Samskrutam Nerchukundam-English Subtitles-2018\సంస్కృతం నేర్చుకుందాం _ Samskrutam  Nerchukundam-English Subtiltles _ EP 71 _ 20-12-18 _ SVBC TTD(u20181220; 1552; 720p30)YT 'SVBC TTD'.f136.mp4
[download]  57.5% of ~262.22MiB at 934.08KiB/s ETA 46:31
ERROR: Interrupted by user
^C
( 12-05-2020 | 23:57:53.84 ) C:\Users\VENKAT> Exit

**Comment by dstftw** [comment]
10 through 5, as expected.
