### ISSUE TITLE
Unable to download from viki -- 400: Bad Request (caused by HTTPError())

### ISSUE THREAD

**Issue by issues101** [ytdl-org/youtube-dl#25268]
youtube-dl.exe -F --no-check-certificate --verbose https://www.viki.c
om/tv/36630c-hello-again
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--no-check-certificate', '--verbose', 'https:
//www.viki.com/tv/36630c-hello-again']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
[viki:channel] 36630c: Downloading channel JSON
[viki:channel] 36630c: Downloading episodes JSON page #1
[viki:channel] 36630c: Downloading clips JSON page #1
[viki:channel] 36630c: Downloading movies JSON page #1
[download] Downloading playlist: Hello Again!
[viki:channel] playlist Hello Again!: Collected 16 video ids (downloading 16 of
them)
[download] Downloading video 1 of 16
[viki] 1155992v: Downloading video JSON
[viki] 1155992v: Downloading video streams JSON
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by
HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you
are using the latest version; type  youtube-dl -U  to update. Be sure to call yo
utube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swg
z7\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swg
z7\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt

**Comment by franhp** [comment]
It seems to work for me, perhaps it was a temporary issue?

```
$ youtube-dl --no-check-certificate --verbose  https://www.viki.com/tv/36630c-hello-again
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check-certificate', '--verbose', 'https://www.viki.com/tv/36630c-hello-again']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Git HEAD: 987fbde7d
[debug] Python version 3.7.7 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[viki:channel] 36630c: Downloading channel JSON
[viki:channel] 36630c: Downloading episodes JSON page #1
[viki:channel] 36630c: Downloading clips JSON page #1
[viki:channel] 36630c: Downloading movies JSON page #1
[download] Downloading playlist: Hello Again!
[viki:channel] playlist Hello Again!: Collected 16 video ids (downloading 16 of them)
[download] Downloading video 1 of 16
[viki] 1155992v: Downloading video JSON
[viki] 1155992v: Downloading video streams JSON
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://v4.viki.io/1155992v/1155992v_high_480p_64a41b_1908191120.mp4?e=1589461059&h=acc02e82ae71a0e33828cebc403f5663'
[download] Resuming download at byte 4193280
[download] Destination: Hello Again! - Episode 1-1155992v.mp4
[download]   5.5% of 440.17MiB at 23.98MiB/s ETA 00:17^C
ERROR: Interrupted by user
```

**Comment by 854R** [comment]
@franhp The video in your test download needs a login account. How were you able to download the video without including the login parameters?

I'm having problems downloading videos that require a login account. Someone else reported an identical issues a few weeks ago but it was closed without any clear resolution.

I've updated to the latest version 2020.05.08.

Thanks,

**Comment by issues101** [comment]
I have verified that I was able to download this video through https://www.tubeoffline.com/download-Viki-videos.php without logging on to viki. I have no problem playing this video in a browser -- again, without logging on to viki. But if I open a Command Prompt window and enter "youtube-dl.exe --no-check-certificate --verbose https://www.viki.com/tv/36630c-hello-again", I get the above mentioned error. The error occurs under both Windows XP and Windows 7.

**Comment by issues101** [comment]
"ytdl-org deleted a comment from issues101 2 days ago"
May I ask for an explanation as to why my comment was deleted? Arbitrarily deleting a comment is, at very least, impolite.

**Comment by zackmark29** [comment]
This issue not yet fix.
I can only get 480p without account and with using credentials I got error as well

**Comment by issues101** [comment]
I left a comment before, it was deleted for no apparent reason that nobody bothered to explain to me. I'll try to leave another comment here, let's see if it will be deleted too...
It is correct that you can get only 480p without logging on. There is apparently another issue related to using credentials, but that issue is different from this one. I'd like to emphasize that in this particular issue, no logon is required to reproduce the problem.
Still waiting for an explanation why my previous comment was deleted...

**Comment by AlecHex** [comment]
Inputing normal link can show upto 480p for me, but using an account i am getting 
`[viki] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default`
