### ISSUE TITLE
Archive.org failed downloads

### ISSUE THREAD

**Issue by UglyMane** [ytdl-org/youtube-dl#25277]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.05.08**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```C:\Users\kk\Videos\-v Youtubedl>youtube-dl.exe https://ia800706.us.archive.org/14/items/Norm_Macdonald_Live/Norm%20Macdonald%20Live%20-%20S01E10%20-%20Norm%20Macdonald%20with%20Guest%20Andy%20Dick.mp4
[generic] Norm Macdonald Live - S01E10 - Norm Macdonald with Guest Andy Dick: Requesting header
WARNING: Could not send HEAD request to https://ia800706.us.archive.org/14/items/Norm_Macdonald_Live/Norm%20Macdonald%20Live%20-%20S01E10%20-%20Norm%20Macdonald%20with%20Guest%20Andy%20Dick.mp4: HTTP Error 403: Forbidden
[generic] Norm Macdonald Live - S01E10 - Norm Macdonald with Guest Andy Dick: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

WRITE DESCRIPTION HERE
On archive.org if the video is flagged and you need to log in to get access to it, I believe that is preventing the download.

**Comment by franhp** [comment]
Site now displays 

```
Item not available
The item is not available due to issues with the item's content.
```

Perhaps 403 was returned due to the content being removed?

**Comment by UglyMane** [comment]
Yes most items on the site work fine but this one has been flagged so is behind a wall where you have to log in to access it, I have logged in and tried to download but it won't work and I'm assuming the program can't get past the log in and was wondering if theres a way around this. sorry I'm not a programmer or anything.

**Comment by ripspin5** [comment]
~/
 youtube-dl -U 
youtube-dl is up-to-date (2020.07.28)
~/
 youtube-dl -F https://archive.org/details/pedo-gate-2020-mouthy-buddha
[archive.org] pedo-gate-2020-mouthy-buddha: Downloading webpage
ERROR: Unable to extract jwplayer playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
~/
 youtube-dl --verbose  -F https://archive.org/details/pedo-gate-2020-mouthy-buddha
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-F', u'https://archive.org/details/pedo-gate-2020-mouthy-buddha']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 2.7.12 (CPython) - Linux-4.9.58-x86_64-with-glibc2.7
[debug] exe versions: ffmpeg 2.8.11, ffprobe 2.8.11, rtmpdump 2.4
[debug] Proxy map: {}
[archive.org] pedo-gate-2020-mouthy-buddha: Downloading webpage
ERROR: Unable to extract jwplayer playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/archiveorg.py", line 45, in _real_extract
    webpage, 'jwplayer playlist'), video_id)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract jwplayer playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

~/
