### ISSUE TITLE
remove special characters from title when saving file

### ISSUE THREAD

**Issue by 400thecat** [ytdl-org/youtube-dl#25287]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have an alias, something like this:

```
youtube-dl --no-check-certificate -o "/mnt/media/download/$(date +%Y-%m-%d)__%(title)s-%(id)s.%(ext)s"
```

it works well, but the title usually contains unsafe characters, spaces, non-asci, and so on.

Is there a way to define some kind substitution, such as spaces are automatically converted into underscores and special characters removed ?

**Comment by dstftw** [comment]
```
--restrict-filenames             Restrict filenames to only ASCII
                                 characters, and avoid "&" and spaces in
                                 filenames
```
