### ISSUE TITLE
youtube login broken

### ISSUE THREAD

**Issue by truexfan81** [ytdl-org/youtube-dl#25288]
## Checklist

- [ x] I'm reporting a broken site support
- [ X] I've verified that I'm running youtube-dl version **2020.05.08**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl.exe https://www.youtube.com/watch?v=b2Wf7XaXsh4
[debug] System config: []
[debug] User config: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--mark-watched', '--retries', 'infinite', '--verbose', '--youtube-skip-dash-manifest', '-f', 'bestvideo[height<=1080]+bestaudio/best']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=b2Wf7XaXsh4']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-89788-g1eb7c1d49d, ffprobe N-89788-g1eb7c1d49d
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube] b2Wf7XaXsh4: Downloading webpage
[youtube] b2Wf7XaXsh4: Marking watched
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r4---sn-5ualdn7l.googlevideo.com/videoplayback?expire=1589544375&ei=VzG-XqWkHeWUj-8P4-mGkAk&ip=68.62.160.38&id=o-AIVh8cep3qCAEZWc7V-TnjBlxrnn8kgKW7TDqZ9VZLiy&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&source=youtube&requiressl=yes&mh=41&mm=31%2C26&mn=sn-5ualdn7l%2Csn-vgqsknek&ms=au%2Conr&mv=m&mvi=3&pl=20&initcwndbps=1913750&vprv=1&mime=video%2Fmp4&gir=yes&clen=202761930&dur=605.480&lmt=1589521522875271&mt=1589522726&fvip=4&keepalive=yes&beids=9466586&c=WEB&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgely3Pec9XzdZL9QvxzhULcWLNHMH59KjIsA8n-YsW_4CIQDv2zyWhB9ZGpxHDuJaCLK8UV7M8Jgr6qsvKHBiKG9tCw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPHLhhQHTW8gBPCldio49tJ-y3D6yJLl0uguIPdqSoGpAiBWTOwF5Trfyv_Pcy8nNs8ok7JQPR3JSx3h72iDUqOg0g%3D%3D&ratebypass=yes'
[download] Destination: New Car vs Old Car Battle - Which is better (BRZ VS SuperTurbo)-b2Wf7XaXsh4.f137.mp4
[download]   6.2% of 193.37MiB at  2.69MiB/s ETA 01:07

## Description

WRITE DESCRIPTION HERE
unable to login to youtube http error 400 bad request
on at least one other issue about this someone responded to use a cookie.
1. i don't know how to do this.
2. can we please fix the bug instead of using workarounds?
3. Thank you for taking the time to read this.

**Comment by AkgunFatih** [comment]
why is this mutha fucka closed
