### ISSUE TITLE
How download a MPEG Dash with DRM?

### ISSUE THREAD

**Issue by Yogioh969** [ytdl-org/youtube-dl#25289]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Is possible download a MPEG Dash content with DRM?

How can I decrypt using the MPD file?

I tried download all M4S segments (audio and video) but when I join the segments the video doesn't work properly.

The site is using Widevine platform for DRM.

I tried too youtube-dl and dash-proxy but again unsuccessfully.

I searched on Google but I didn't succeed.

**Comment by dstftw** [comment]
Not possible.
