### ISSUE TITLE
Extract YouTube-Playlist name with "--no-playlist-flag" is not working as expected

### ISSUE THREAD

**Issue by SeyRyuu** [ytdl-org/youtube-dl#25290]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

My Test Version 1 (not working as expected from me):

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '%(uploader)s;%(playlist)s;%(title)s;%(id)s.%(ext)s', '-v', '--no-playlist', 'https://www.youtube.com/watch?v=AiRFDHRJNUE&list=PLcxe8PiqoxJa8CtexjOXE18CiW4ZtI2Fd&index=2&t=0s']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] Downloading just video AiRFDHRJNUE because of --no-playlist
[youtube] AiRFDHRJNUE: Downloading webpage
[youtube] Downloading just video AiRFDHRJNUE because of --no-playlist
[youtube] {18} signature length 107, html5 player vflset
[youtube] {137} signature length 107, html5 player vflset
[youtube] {248} signature length 107, html5 player vflset
[youtube] {299} signature length 103, html5 player vflset
[youtube] {303} signature length 107, html5 player vflset
[youtube] {136} signature length 107, html5 player vflset
[youtube] {247} signature length 103, html5 player vflset
[youtube] {298} signature length 107, html5 player vflset
[youtube] {302} signature length 107, html5 player vflset
[youtube] {135} signature length 107, html5 player vflset
[youtube] {244} signature length 103, html5 player vflset
[youtube] {134} signature length 107, html5 player vflset
[youtube] {243} signature length 107, html5 player vflset
[youtube] {133} signature length 103, html5 player vflset
[youtube] {242} signature length 107, html5 player vflset
[youtube] {160} signature length 103, html5 player vflset
[youtube] {278} signature length 107, html5 player vflset
[youtube] {140} signature length 107, html5 player vflset
[youtube] {249} signature length 107, html5 player vflset
[youtube] {250} signature length 107, html5 player vflset
[youtube] {251} signature length 107, html5 player vflset
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r4---sn-4g5e6nsk.googlevideo.com/videoplayback?expire=1589592872&ei=yO6-XvOWLpCG7gOo2pTgBQ&ip=87.177.173.46&id=o-AJe4oWKBvBYqMeriVg8WVeNwnIRn1mLTUIX_cH8HePfC&itag=18&source=youtube&requiressl=yes&mh=E7&mm=31%2C26&mn=sn-4g5e6nsk%2Csn-h0jeln7l&ms=au%2Conr&mv=m&mvi=3&pl=26&initcwndbps=970000&vprv=1&mime=video%2Fmp4&gir=yes&clen=14849381&ratebypass=yes&dur=161.030&lmt=1576419273303298&mt=1589571168&fvip=4&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgBArD1ZEIDQft6gO6iCFuxQBayAYO0p9it0SN8YSqJPECIQDPXXxJJYNtIqa78zegfhHOUKOtEOrWx1gopehfPXbhXw%3D%3D&sig=AOq0QJ8wRQIgfKAWzKTOoV5cVXzgVs7GRGnMbF4Jt-PznYKrXBQ5ausCIQDouBqR6Z6xwPjBICderiUafr8S2Ox0lePkfNnjKuWo8A=='
[download] Destination: Cherry 葵;NA;Nightcore - Fake (RedHook) _ (Lyrics);AiRFDHRJNUE.mp4
[download] 100% of 14.16MiB in 00:17

My Test Version 2: (works as expected):

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '%(uploader)s;%(playlist)s;%(title)s;%(id)s.%(ext)s', '-v', '--yes-playlist', 'https://www.youtube.com/watch?v=AiRFDHRJNUE&list=PLcxe8PiqoxJa8CtexjOXE18CiW4ZtI2Fd&index=2&t=0s']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLcxe8PiqoxJa8CtexjOXE18CiW4ZtI2Fd - add --no-playlist to just download video AiRFDHRJNUE
[youtube:playlist] PLcxe8PiqoxJa8CtexjOXE18CiW4ZtI2Fd: Downloading webpage
[download] Downloading playlist: test
[youtube:playlist] playlist test: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] AiRFDHRJNUE: Downloading webpage
[youtube] {18} signature length 107, html5 player vflset
[youtube] {137} signature length 107, html5 player vflset
[youtube] {248} signature length 107, html5 player vflset
[youtube] {299} signature length 103, html5 player vflset
[youtube] {303} signature length 107, html5 player vflset
[youtube] {136} signature length 107, html5 player vflset
[youtube] {247} signature length 103, html5 player vflset
[youtube] {298} signature length 107, html5 player vflset
[youtube] {302} signature length 107, html5 player vflset
[youtube] {135} signature length 107, html5 player vflset
[youtube] {244} signature length 107, html5 player vflset
[youtube] {134} signature length 107, html5 player vflset
[youtube] {243} signature length 107, html5 player vflset
[youtube] {133} signature length 103, html5 player vflset
[youtube] {242} signature length 103, html5 player vflset
[youtube] {160} signature length 107, html5 player vflset
[youtube] {278} signature length 107, html5 player vflset
[youtube] {140} signature length 107, html5 player vflset
[youtube] {249} signature length 107, html5 player vflset
[youtube] {250} signature length 107, html5 player vflset
[youtube] {251} signature length 107, html5 player vflset
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r4---sn-4g5ednss.googlevideo.com/videoplayback?expire=1589592721&ei=Me6-XsWOA4ifgAfNgYSoBQ&ip=87.177.173.46&id=o-ABuF3NMRepQJGsDRJXO-RTcuZ4ug3BYHYdDCbZ3Li8h2&itag=18&source=youtube&requiressl=yes&mh=E7&mm=31%2C29&mn=sn-4g5ednss%2Csn-4g5e6nsk&ms=au%2Crdu&mv=m&mvi=3&pl=26&initcwndbps=960000&vprv=1&mime=video%2Fmp4&gir=yes&clen=14849381&ratebypass=yes&dur=161.030&lmt=1576419273303298&mt=1589570978&fvip=4&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANNWaRg8GD6d4nLKdmZwG_frDhCXoQdC1hZGVnlm3dkXAiAkLVUvl4VmXaDu3B2_HhW73CeTmwHRxORaYmsp1HFWoA%3D%3D&sig=AOq0QJ8wRQIhAOA_pGdMmqOjVVu4YWmogGUHmtMd7WOP7i18UoOkhpvjAiBl999l3Qku34ZU2KX6CklvZisv1uLswR1u0-tWJNnQ6A=='
[download] Destination: Cherry 葵;test;Nightcore - Fake (RedHook) _ (Lyrics);AiRFDHRJNUE.mp4
[download] 100% of 14.16MiB in 00:18
[download] Finished downloading playlist: test

## Description

WRITE DESCRIPTION HERE

Hi,

i think it is a bug that the output-Extractor with the option "%(playlist)s" is not working when using the "--no-playlist"-flag in my command.

I'm searching for a possibility to download only the provided video in a playlist YouTube-URL ("--no-playlist" does this job perfectly), and extract the playlist name to the resulting output file. 
The second part is the problem, the playlist name is not getting extracted when using "--no-playlist"-flag. 
If you use the --yes-playlist-flag it works as expected, but all other files in the playlist are also downloaded, and that's not what I want.

If this behavior above is right, is there any other way to download only the video in a playlist YouTube-URL and extract the playlist name to the output file?

Thank you for your help!

PS: Sorry for any mistakes, I'm from Germany, so English isn´t my native language.

**Comment by dstftw** [comment]
1. This is expected behavior, no playlist data is extracted with `--no-playlist`.
2. `--match-filter id=<id>`.
