### ISSUE TITLE
Youtube-dl Python manual install (not via pip)

### ISSUE THREAD

**Issue by theincognito-inc** [ytdl-org/youtube-dl#25295]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi.
I have a git clone of youtube-dl (master) and I do a pull every couple of days. I used to use the module via `python -m youtube_dl` for running the module with latest changes.
But I wanted to run it from everywhere and so I installed it manually using `python setup.py install` .

My query is: When I do a manual install, will the final installed module contain all the changes up to that git pull, or, will it only contain the changes till the last release?
I am asking this because whenever I install it, it gets installed with the last release name/number. So, I am not sure whether the commits after that release tag, which are already pulled, are included or not, in the installed module.

Apologies in advance if this is a stupid question.

**Comment by dstftw** [comment]
Obviously it will only contain changes available at the moment of running `python setup.py install`.
