### ISSUE TITLE
broken https://www.france.tv/france-2/apocalypse-la-guerre-des-mondes-1945-1991/apocalypse-la-guerre-des-mondes-1945-1991-saison-7/1099457-l-abime-1963-1991.html

### ISSUE THREAD

**Issue by aubourg** [ytdl-org/youtube-dl#25291]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.05.08**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.france.tv/france-2/apocalypse-la-guerre-des-mondes-1945-1991/apocalypse-la-guerre-des-mondes-1945-1991-saison-7/1099457-l-abime-1963-1991.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-51-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: none
[debug] Proxy map: {}
[FranceTVSite] 1099457-l-abime-1963-1991: Downloading webpage
[FranceTV] aa7e2d02-32cd-4ff3-80ef-d683f0ed3ed4: Downloading video JSON
[FranceTV] aa7e2d02-32cd-4ff3-80ef-d683f0ed3ed4: Downloading geo restriction info
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 209, in _real_extract
    return self._extract_video(video_id, catalog)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 169, in _extract_video
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Other pages in the same series work fine, only this one is broken. Thanks.

**Comment by tschmoderer** [comment]
duplicate with which other issue ?
