### ISSUE TITLE
Youtube Music

### ISSUE THREAD

**Issue by by-zarmius** [ytdl-org/youtube-dl#25299]
Hello! I would like to ask if the ability to download music from Youtube music will be added?

**Comment by LeonSolisPedro** [comment]
## Checklist



- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones


## Example URLs



- Single video: https://music.youtube.com/watch?v=Sa-dxgZt4rY
- Single video: https://music.youtube.com/watch?v=Sa-dxgZt4rY&feature=share
- Playlist: https://music.youtube.com/playlist?list=PLj_H33m_M2nA-gZUfQJWpfpEZETZ7N-nr
- Playlist: https://music.youtube.com/watch?v=Sa-dxgZt4rY&list=PLj_H33m_M2nA-gZUfQJWpfpEZETZ7N-nr



## Description



Currently you can't download high quality audio (#25263 ) nor can you download your own uploaded music (Google Play Music is about to disappear) So it would be great if you guys supported Youtube Music

I'm willing to provide credentials with an active youtube music subscription for high-quality audios, but as far as I know, you can upload music to the platform for free

Here's the verbose log for the uploaded music which fails to download:
```
PS C:\Users\zzz01\Portable\Youtube> .\youtube-dl.exe "https://music.youtube.com/watch?v=IGixyR3aZPQ" -v --cookies .\cookies.txt -6
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://music.youtube.com/watch?v=IGixyR3aZPQ', '-v', '--cookies', '.\\cookies.txt', '-6']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-05-04-5767a2e, ffprobe git-2020-05-04-5767a2e
[debug] Proxy map: {}
[youtube] IGixyR3aZPQ: Downloading webpage
ERROR: IGixyR3aZPQ: YouTube said: This video is not available.
Sorry about that.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\youtube.py", line 1820, in _real_extract
youtube_dl.utils.ExtractorError: IGixyR3aZPQ: YouTube said: This video is not available.
Sorry about that.
```

**Comment by n3f** [comment]
I'm curious about this as well. @dstftw, is there more detail we can provide to re-open this issue?
