### ISSUE TITLE
youtube-dl downloading wrong ciscolive video even though mentioned url is having different video

### ISSUE THREAD

**Issue by ciscohack** [ytdl-org/youtube-dl#25301]
Hi Team,

I am running latest youtube-dl and today I was using it to download cisco live video. I have observed whenever i put any ciscolive URL to download youtube-dl reference to wrong video for download i don't know how.

> youtube-dl -v 'https://www.ciscolive.com/global/on-demand-library.html?search=vxlan#/video/1549556561498001mCLy'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.ciscolive.com/global/on-demand-library.html?search=vxlan#/video/1549556561498001mCLy']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2020.05.03
[debug] Python version 2.7.16 (CPython) - Darwin-19.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[download] Downloading playlist: Search query
[CiscoLiveSearch] Downloading search JSON page 1
[CiscoLiveSearch] Downloading search JSON page 2
[CiscoLiveSearch] Downloading search JSON page 3
[CiscoLiveSearch] playlist Search query: Downloading 129 videos
[download] Downloading video 1 of 129
[brightcove:new] 5996480041001: Downloading JSON metadata
[brightcove:new] 5996480041001: Downloading m3u8 information
[brightcove:new] 5996480041001: Downloading m3u8 information
[brightcove:new] 5996480041001: Downloading MPD manifest
[brightcove:new] 5996480041001: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://bcbolt446c5271-a.akamaihd.net/media/v1/pmp4/static/clear/5647924234001/d581f047-8b15-43e8-aa44-3e31fd541f9e/b82667c8-5da7-471d-b959-2ddfe73a3541/main.mp4?akamai_token=exp=1592127632~acl=/media/v1/pmp4/static/clear/5647924234001/d581f047-8b15-43e8-aa44-3e31fd541f9e/b82667c8-5da7-471d-b959-2ddfe73a3541/main.mp4*~hmac=fbdf5b9304f0db6fa6bd43e810ec42113a1874c76965a150760d05e34b7e43e2'
[download] Resuming download at byte 475947008
[download] Destination: Troubleshooting VxLAN BGP EVPN-5996480041001.mp4 >>> this is wrong video based on url
[download]  52.3% of 888.93MiB at  3.56MiB/s ETA 01:59^C

**Comment by dstftw** [comment]
You must provide account credentials for any work on this.
