### ISSUE TITLE
Error 502 when trying to download channel, but not video

### ISSUE THREAD

**Issue by Fabian42** [ytdl-org/youtube-dl#25303]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[fabian@laptop Downloads]$ youtube-dl -v "https://soundcloud.com/fabian-roeling"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://soundcloud.com/fabian-roeling']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.8.2 (CPython) - Linux-5.6.11-1-MANJARO-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud:user] fabian-roeling: Downloading user info
[soundcloud:user] 57408419: Downloading track page 1
ERROR: Unable to download JSON metadata: HTTP Error 502: Bad Gateway (caused by <HTTPError 502: 'Bad Gateway'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

```

## Description

When trying to download everything from a SoundCloud channel either using the direct channel URL (like https://soundcloud.com/fabian-roeling) or specifically the "tracks" URL (like https://soundcloud.com/fabian-roeling/tracks), the 502 error seen above occurs and nothing is downloaded. Downloading any track separately works normally.

**Comment by Fabian42** [comment]
Duplicate OF WHAT? This is not helpful at all!

**Comment by Fabian42** [comment]
@dstftw There are 0 open reports with "soundcloud" and "502"! I'm not stupid, of course I searched! Blocking conversation helps absolutely nobody and as you can see in the reactions on #25313, obviously other people have that issue as well! If you know the report ID, then JUST TELL ME! It's easy, just type up to 5 digits! Writing "Search." was literally more effort!

**Comment by Fabian42** [comment]
It seems like you actively try to hinder the development of this project. If you don't know how bug trackers work, please stop closing reports in them. Duplicates are always duplicates OF SOMETHING.

**Comment by dstftw** [comment]
>There are 0 **open reports** with "soundcloud" and "502"! I'm not stupid, of course I searched!

>- [x] I've searched the bugtracker for similar issues **including closed ones**

>**including closed ones**

No comments. You didn't even bother to read issue template properly even though it provides you with [correct URL for search](http://yt-dl.org/search-issues).

Simply putting the error message clearly gives you some hits https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+Unable+to+download+JSON+metadata%3A+HTTP+Error+502.
The fifth one (#25274) is the origin that is already solved. Four previous are duplicates from another reporters like that who don't care reading issue template or bother using search.
