### ISSUE TITLE
pornhub.com uploader/channel name and tagged pornstar support in filename output template

### ISSUE THREAD

**Issue by vv211** [ytdl-org/youtube-dl#25317]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I would like to see youtube-dl support adding things to the filename such as uploader or channel name and/or name of tagged pornstars via the output template for videos downloaded from pornhub. This is good for better file sorting and grouping files from a channel together, or when searching for downloaded videos with specific people in them

thank you! :)

**Comment by dirkf** [comment]
`uploader` is supported. `cast` list is continued in #32936.
