### ISSUE TITLE
youtube-dl does not work anymore after upgrading to ubuntu 20.04

### ISSUE THREAD

**Issue by mdalch** [ytdl-org/youtube-dl#25318]
after running the command, I get the following error:
/usr/bin/env: ‘python’: No such file or directory

I removed the app then I installed it again but I still receive the same error.

![Peek 2020-05-19 02-20](https://user-images.githubusercontent.com/10380737/82271181-5f76ca80-9977-11ea-9e44-830700350302.gif)

**Comment by dstftw** [comment]
Nothing to do with youtube-dl. Fix your environment.

**Comment by mdalch** [comment]
sudo apt-get install python-is-python3 solved the problem.
