### ISSUE TITLE
[Youtube] Inferior quality is downloaded in some cases

### ISSUE THREAD

**Issue by GRTpods** [ytdl-org/youtube-dl#25329]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Youtube-dl>youtube-dl -v https://www.youtube.com/watch?v=RVNz9wi9wTY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=RVNz9wi9wTY']
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, pref cp65001
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.8.1 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg git-2020-01-10-3d894db, ffprobe git-2020-01-10-3d894db
[debug] Proxy map: {}
[youtube] RVNz9wi9wTY: Downloading webpage
[youtube] RVNz9wi9wTY: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on ''
[dashsegments] Total fragments: 30
[download] Destination: [Artcore] 繊月 - Query-RVNz9wi9wTY.f248.webm
[download] 100% of 5.87MiB in 00:16
[debug] Invoking downloader on ''
[dashsegments] Total fragments: 17
[download] Destination: [Artcore] 繊月 - Query-RVNz9wi9wTY.f251.webm
[download] 100% of 2.48MiB in 00:02
[ffmpeg] Merging formats into "[Artcore] 繊月 - Query-RVNz9wi9wTY.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:[Artcore] 繊月 - Query-RVNz9wi9wTY.f248.webm" -i "file:[Artcore] 繊月 - Query-RVNz9wi9wTY.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:[Artcore] 繊月 - Query-RVNz9wi9wTY.temp.webm"
Deleting original file [Artcore] 繊月 - Query-RVNz9wi9wTY.f248.webm (pass -k to keep)
Deleting original file [Artcore] 繊月 - Query-RVNz9wi9wTY.f251.webm (pass -k to keep)
```

## Description

137 (avc1) is significantly better than 248 (vp9) in this video, but 248 was downloaded as the default.
https://www.youtube.com/watch?v=62eli4Glk9M
https://www.youtube.com/watch?v=LFUvxDsH_Nk
https://www.youtube.com/watch?v=Duc32lcAhXA

If you play it on Youtube you will see 137 as the default (much better quality), all newer videos of this channel also seem to have this problem.
https://www.youtube.com/user/MementoJosh/videos

Would be nice if you can take a look at it, the compression artifacts are really bad in vp9.

**Comment by dstftw** [comment]
248 has higher reported bitrate.

**Comment by GRTpods** [comment]
Wow ... as much as I like your program, you really are a brick ...
I bet you didn't even visually compare it to see the difference ...

And "higher reported bitrate" are you kidding me?
 137 HAS A HIGHER BITRATE, download and compare it yourself.

458 kBit/s vp9 vs 548 kBits/s H264 (High @4.0)

**Comment by dstftw** [comment]
>I bet you didn't even visually compare it to see the difference ...

This must be done **programmatically** and **without downloading** the actual media.

>And "higher reported bitrate" are you kidding me?

Again: bitrate is reported as metadata by Youtube. You can't get actual bitrate since you'll have to download all formats in order to collect such data.
