### ISSUE TITLE
[Feature Request] allow to download streams in parts without merging 

### ISSUE THREAD

**Issue by ambhaiji** [ytdl-org/youtube-dl#25328]
Streams become unusable because there is no safe way to stop before any stream ends.
Terminating youtube-dl breaks the file complety and makes it unreadable.
Requesting option to download parts separately so they can be merged later
Also allow aria2 to download multiple parts concurrently, sometimes stream parts are just dropped if not grabbed in time, and get skipped

**Comment by dstftw** [comment]
`Ctrl+C` is the safe working way to finish stream.
