### ISSUE TITLE
On getting all videos from a single channel

### ISSUE THREAD

**Issue by TehPsychedelic** [ytdl-org/youtube-dl#25322]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, I think my question is a bit more on the technical side of things that really any issue that I'm having.
I'm aware by looking at some other issues on the tracker that it is possible to download all videos from a given channel.
My question is, how does youtube-dl manage to achieve this challenge? Isn't the youtube API token/call limited so it would make it impossible with how many users, using the same API key downloading at the same time?
So I guess youtube-dl doesn't use the API after all, what does it use then? Does it parse "uploaded videos" playlist manually as one would do in a browser?

I would just like to know the technical background on how this is performed, please.

Thanks

**Comment by dstftw** [comment]
>I guess youtube-dl doesn't use the API after all, what does it use then?

Yes.

>Does it parse "uploaded videos" playlist manually as one would do in a browser?

Yes.

>I would just like to know the technical background on how this is performed, please.

What concretely?

**Comment by TehPsychedelic** [comment]
Thank you @dstftw 
One last thing is this where it performs "the magic" (aka where it manually parses the uploaded videos playlist)
https://github.com/ytdl-org/youtube-dl/blob/52c50a10af5de16165621f8929b64dc726774276/youtube_dl/extractor/youtube.py#L326
