### ISSUE TITLE
[BUG] `--external-downloader aria2c -o -` writes a file named - instead of stdout

### ISSUE THREAD

**Issue by NightMachinary** [ytdl-org/youtube-dl#25345]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Description

`--external-downloader aria2c -o -` writes a file named - instead of stdout.

**Comment by remitamine** [comment]
[aria2c does not support outputting to stdout](https://github.com/aria2/aria2/issues/190).
