### ISSUE TITLE
[question] Since when did youtube-dl include chapters in downloaded files, and how will this change because of the new YouTube timestamp-chapters?

### ISSUE THREAD

**Issue by Bernd-L** [ytdl-org/youtube-dl#25356]
I'll provide some background info first, the question itself follows it.

# Background
I remember downloading [DBOYD - Paradise (Full EP)](https://www.youtube.com/watch?v=wA07KKRRbDk), and I was surprised after seeing chapter markers in VLC when I played back the `.mkv` file.

![image](https://user-images.githubusercontent.com/18219148/82649566-b3084300-9c19-11ea-9dec-fa6290787db9.png)

(See the tiny markings underneath the scrubbing bar; Hovering over the scrubbing bar also shows the chapter name.)

Since when did YouTube have this?

After seeing new stuff in YouTube Web-GUI, I ran a quick web search and found [this article](https://thenextweb.com/google/2020/04/14/youtube-is-testing-a-chapters-feature-to-help-you-navigate-lengthy-videos/) describing what's going on:

![image](https://user-images.githubusercontent.com/18219148/82649764-ff538300-9c19-11ea-9792-ec6f2b90ff01.png)

Notice: The video description contains timestamps. I think they were there for quite some time (even before YouTube had this feature - since you've always been able to just click on them).

Yes, I have some custom CSS which displays Nyan Cat, but the important part here is that the scrubbing bar on the YouTube website has gaps (the chapter markers) and next to the videos running time (near the play/pause button) is the chapter name.

# My question(s)

What surprised me was that youtube-dl managed to include them in the `.mkv` file as well, in a time before YouTube has this chapters-feature.

- Did youtube-dl just scan and analyze the video description?
- Did it parse it on its own from the video desctiption?
- How will youtube-dl handle this new YouTube feature?
- Did youtube-dl access an (potentially undocumented) API somewhere for this info?
- SInce when does YouTube offer this?

The [`README.md`][1] file only offers [limited info][1] on "chapters", which is why I'm asking this.

---

Thanks for reading!

[1]: https://github.com/ytdl-org/youtube-dl/blob/master/README.md#:~:text=Name%20or%20title%20of%20the%20chapter%20the%20video%20belongs%20to

**Comment by Bernd-L** [comment]
This might be relevant: #24819

**Comment by dstftw** [comment]
1. Correct.
2. Correct.
3. Handle what?
4. It does not use any API.
5. Ask Youtube.

**Comment by drelephant** [comment]
A bit OT but how did you set that dark theme for VLC?

**Comment by Bernd-L** [comment]
@drelephant 
> A bit OT but how did you set that dark theme for VLC?

I'm using [Matcha Dark Sea](https://github.com/vinceliuice/Matcha-gtk-theme#readme) as my GTK theme, and I've set Qt to use GTK2 styles.

That's how my theme gets there.
