### ISSUE TITLE
Instagram downloads are not working

### ISSUE THREAD

**Issue by RealDeviil** [ytdl-org/youtube-dl#25354]
## Checklist

- [ x] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.05.08**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
root@vmi298562:/tmp/youtube-dl/instagram# python3 /usr/bin/youtube-dl -v --write-pages https://www.instagram.com/p/8fAKWTSWa6/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--write-pages', 'https://www.instagram.com/p/8fAKWTSWa6/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.5.3 (CPython) - Linux-4.9.0-11-amd64-x86_64-with-debian-9.12
[debug] exe versions: ffmpeg 3.3.4-static
[debug] Proxy map: {}
[Instagram] 8fAKWTSWa6: Downloading webpage
[Instagram] Saving request to 8fAKWTSWa6_https_-_www.instagram.com_accounts_login_next=_p_8fAKWTSWa6_.dump
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/instagram.py", line 195, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1123, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

It appears that the download URLs are no longer directly embedded in inline JS on video page. My guess is that they are now found in one of the many external JS scripts included in the page. If I find out which one and/or where, I will update this thread.

Thank you.

**Comment by filixm** [comment]
I get the same error with Instagram when running through a proxy.  Works locally without proxy.  Proxies I use are private and work for all other sites.

**Comment by ehsan653** [comment]
we get the same error . 
the main source of trouble is the instagram new policy's.

**Comment by RealDeviil** [comment]
It looks like Instagram is forcing a login, since a request to a video URL returns an HTTP response like this:

```
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: https://www.instagram.com/accounts/login/?next=/p/8fAKWTSWa6/
Vary: Accept-Language, Cookie
Content-Language: en
Date: Sun, 24 May 2020 06:19:02 GMT
Strict-Transport-Security: max-age=31536000
Cache-Control: private, no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Sat, 01 Jan 2000 00:00:00 GMT
X-Frame-Options: SAMEORIGIN
content-security-policy: report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src https: data: blob:; font-src https: data:; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
x-aed: 15
Access-Control-Expose-Headers: X-IG-Set-WWW-Claim
Date: Sun, 24 May 2020 06:19:02 GMT
X-FB-TRIP-ID: 1679558926
Connection: keep-alive
Content-Length: 0
```

Bu you can still anonymously view a video in the browser, without logging in. So there must be a way to do this without a login. I've just not been able to reproduce this yet programmatically.

There is some kind of encryption "public_key" in the login page source code, and it looks like it is manipulated by https://www.instagram.com/static/bundles/es6/**EncryptionUtils.js**/8c78adc6dadb.js in some way.

Maybe that public key could be used to bypass the login screen? Or maybe that just adds a layer of encryption to the login process.

If anyone could contribute more to this issue, I think all of us would appreciate it.

**Comment by RealDeviil** [comment]
For anyone that's interested, I (programmatically) found a video's mp4 file in the source code of "embed" pages like https://www.instagram.com/p/8fAKWTSWa6/embed/ .

The download link is in the JavaScript code that starts with "window.__additionalDataLoaded".

I don't know python well enough to update this repo, but for someone who knows python, it should not be difficult to do.

Hope it helps.

**Comment by tinybug** [comment]
here is the fix: https://github.com/ytdl-org/youtube-dl/pull/22880/files

**Comment by iuriguilherme** [comment]
I don't have an instagram account and therefore I can't tell for sure if it's because the video is private that I get a 404 error with this URI: https://www.instagram.com/tv/CCB-aFzhunX

If I use a opengraph aware tool such as the telegram preview, that link becomes this one: https://www.instagram.com/tv/CCB-aFzhunX/?igshid=ji25r415j6hm

This IGTV link seems to work: https://www.instagram.com/tv/CB0m77Dgpmh/?igshid=80c8le3zds0l

I'm not sure what is the difference from them as I know nothing on how Instagram TV (is that how it's called)? works.

**Comment by xmha97** [comment]
![image](https://user-images.githubusercontent.com/23485114/87207979-91c2f980-c322-11ea-936a-6189dfd4b190.png)

**Comment by kfur** [comment]
For me error occurs only if i use vpn or vps
