### ISSUE TITLE
altcensored.com

### ISSUE THREAD

**Issue by penismonsters** [ytdl-org/youtube-dl#25355]
- [x ] I'm reporting a new site support request
- [x ] I've verified that I'm running youtube-dl version **2020.05.08**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that none of provided URLs violate any copyrights
- [x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.altcensored.com/watch?v=XxIbq7HkalQ
- Single video: https://www.altcensored.com/watch?v=Jo7KOZrX6hI

## Description

It is a site that hosts videos on youtube that are in a limited state.

**Comment by todduk** [comment]
In the mean time you can right click the video and 'Save As...'
