### ISSUE TITLE
Just Reporting What an App Told Me To (2)

### ISSUE THREAD

**Issue by bradsmithsite** [ytdl-org/youtube-dl#25360]
dstftw, you closed my issue as "incomplete". It took me about 30 seconds to find the video and test it with the latest "youtube-dl.exe" to see that the issue has been FIXED. I get NOTHING out of reporting this error, but you could have taken a minute or two to find the video and test if it's a bug with youtube-dl or not. The bug has obviously been fixed and I've contacted the Tubulator guy to ask him to rebuild Tubulator with the latest youtube-dl build.

If I weren't thorough and this WEREN'T fixed, you basically would have MISSED a potential bug because you so quickly marked my comment as incomplete, when it wasn't. All the information was there to find out if it were a bug or not.

I understand you get a lot of reports, but if you do a job, do a full job. Kindly, Brad Smith (software developer too). Not being sarcastic, but thank you for the work that you guys do. You're amazing. :)

![success](https://user-images.githubusercontent.com/59305256/82671595-66cff980-9c3f-11ea-9333-a5d2bbe8f230.png)
![bug](https://user-images.githubusercontent.com/59305256/82671629-72bbbb80-9c3f-11ea-9d13-bea55b1f3710.png)

**Comment by dstftw** [comment]
Bother to read new issue template.
