### ISSUE TITLE
can't download  twitch  clip

### ISSUE THREAD

**Issue by Some1body** [ytdl-org/youtube-dl#25371]
C:\Users>youtube-dl "https://clips.twitch.tv/embedclip=CharmingRoundCourgetteBudBlast&amp"

[twitch:clips] CharmingRoundCourgetteBudBlast: Downloading JSON metadata
ERROR: Unable to download JSON metadata: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
>This clip is no longer available
