### ISSUE TITLE
Audio Description Flag

### ISSUE THREAD

**Issue by jugendhacker** [ytdl-org/youtube-dl#25378]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm currently looking into how #24098 could be fixed an found a way to determinate if a audio track has audio description or not. Now I'm wondering if there is a flag or so that could be set in the extractor to tell if this track has a audio description or not? So youtube-dl could let the user select it or not without this workaround via the Format option (as described in the related issue)

**Comment by dstftw** [comment]
No such flag.

**Comment by jugendhacker** [comment]
@dstftw but wouldn't it be a good idea to ad one?

**Comment by dstftw** [comment]
Only generic meta fields can be added.

**Comment by jugendhacker** [comment]
> Only generic meta fields can be added.

@dstftw I don't understand what you want to say, sorry.

**Comment by dstftw** [comment]
I won't add another meta field just for the single extractor. All meta fields added must be carefully designed and proven to be usable across multiple extractors.

**Comment by jugendhacker** [comment]
I don't think ZDF is the only Service where you can download with and without audio description.

**Comment by dstftw** [comment]
Also I don't see much difference whether it's selected based on `format_id` on some fancy flag. In both cases this involves format selection expression.

**Comment by jugendhacker** [comment]
The problem is currently you have to manually find the best video/audio format without AD, but you don't even know what format has AD and what does not, because it doesn't tell you. So you have to try it manually several times until you find the right one. Now you have to manually set it. Maybe, if you do bulk downloads, the next video doesn't have this specific format so you start again finding the right format manually. 

Now I'm thinking about a `--enable-ad` (or `--diable-ad`) CLI flag so youtube-dl could select the best format for you with your AD preference.

**Comment by dstftw** [comment]
Wrong. `format_id` contains `Audiodeskription` that can easily be excluded with format selection expression.
As already pointed out I won't introduce new options just because of single extractor especially when it's covered by existing functionality.
