### ISSUE TITLE
1. This is expected behavior.

### ISSUE THREAD

**Issue by hiddejager** [ytdl-org/youtube-dl#25386]
1. This is expected behavior.
2. Wrong, does not happen by default if you don't touch format selection.

_Originally posted by @dstftw in https://github.com/ytdl-org/youtube-dl/issues/25385#issuecomment-633161189_

1. Can i do something so it doesn't do that, so that it chooses resolution over bitrate?
2. It does actually happen, it will choose slightly lower quality audio files.

**Comment by hiddejager** [comment]
@dstftw

**Comment by dstftw** [comment]
1. Stop posting duplicates. This is your last warning.
2. You can't manage sorting preferences.
3. If "it does actually happen" post complete report as requested in new issue template - there are no telepathists here.
