### ISSUE TITLE
Sergey, please help me out with this.. I'll donate $30

### ISSUE THREAD

**Issue by hiddejager** [ytdl-org/youtube-dl#25385]
The best audio and video quality

1. Sometimes a lower resolution is chosen because the bitrate on that lower resolution is higher.
2. Sometimes a worse quality audio is chosen because that’s the best audio that’s available in combination with the video. Meanwhile there’s a separate factually better audio file. 

Do you understand?

Hope to hear from you

Kind regards,

Hidde Jager

**Comment by hiddejager** [comment]
@dstftw

**Comment by dstftw** [comment]
1. This is expected behavior.
2. Wrong, does not happen by default if you don't touch format selection.
