### ISSUE TITLE
$30 for the person who fixes this for me - Download the literal best quality, both audio and video in on MKV file

### ISSUE THREAD

**Issue by hiddejager** [ytdl-org/youtube-dl#25384]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I want to download YouTube video's without losing any quality, both video and audio.
I know this should work automatically but it doesn't, sometimes a lower resolution is chosen because of a higher bitrate and sometimes the best audio isn't chosen. 

And yes with -F you can manually select the audio or video you want but i need to download a lot of clips and it will take ages this way.

So my goal is:

Use youtube-dl to download a YouTube video lossless.
Automatically put the literal/factual best audio and video file into one MKV container.

Best meaning: 

Highest resolution video, with the highest bitrate at that resolution.
Best audio, not the smallest or the best in combination with video... The size also doesn't matter. The best audio file that is available when you would manually select it with -F.

The best audio and video in MKV container. < Can anyone help me with that? 

If you solve it i'll pay you $30!!

**Comment by hiddejager** [comment]
@dstftw Why did you close this issue, can you please help me out? This specific question isn't answered anywhere

**Comment by dstftw** [comment]
Best quality is selected by default. Nothing should be done.
