### ISSUE TITLE
while downloading 5.1 videos from youtube it is downloading in stereo format.

### ISSUE THREAD

**Issue by Raul824** [ytdl-org/youtube-dl#25397]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by Raul824** [comment]
How to Download 5.1 videos without re-encoding?
I've found some videos on youtube that are multichannel, the pulseeffects show that they are being played as 6 channel. Upon downloading them when i check them via ffprobe i can see that they have been re-encoded as stereo. So I used -k argument and downloaded them to check if they are being downloaded in 6 channel and upon merging are being re-encoded but the audio track which was downloaded is in the stereo only.

**Comment by dstftw** [comment]
Nothing is reencoded by default.
