### ISSUE TITLE
Can you download from a private Twitter account?

### ISSUE THREAD

**Issue by goodboi69** [ytdl-org/youtube-dl#25394]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Is it possible to download from a private Twitter account that you are following? If so, how?

**Comment by RewardK** [comment]
No

**Comment by SekiBetu** [comment]
https://chrome.google.com/webstore/detail/twitter-media-downloader/cblpjenafgeohmnjknfhpdbdljfkndig

**Comment by goodboi69** [comment]
> 
> 
> https://chrome.google.com/webstore/detail/twitter-media-downloader/cblpjenafgeohmnjknfhpdbdljfkndig

Thank you but the extension is broken.

**Comment by SekiBetu** [comment]
> > [chrome.google.com/webstore/detail/twitter-media-downloader/cblpjenafgeohmnjknfhpdbdljfkndig](https://chrome.google.com/webstore/detail/twitter-media-downloader/cblpjenafgeohmnjknfhpdbdljfkndig)
> 
> Thank you but the extension is broken.

i dont know, but it works fine to me

**Comment by goodboi69** [comment]
> 
> 
> > > [chrome.google.com/webstore/detail/twitter-media-downloader/cblpjenafgeohmnjknfhpdbdljfkndig](https://chrome.google.com/webstore/detail/twitter-media-downloader/cblpjenafgeohmnjknfhpdbdljfkndig)
> > 
> > 
> > Thank you but the extension is broken.
> 
> i dont know, but it works fine to me
Read the SUPPORT page of the extension. It verifies my issue.
