### ISSUE TITLE
Daily backup of YouTube Channel (without overwriting)

### ISSUE THREAD

**Issue by dm17** [ytdl-org/youtube-dl#25392]
I've been using:
youtube-dl -f best -ciw -o "%(title)s.%(ext)s" -v URL_of_YT_channel
in order to backup YouTube channels. It does seem to rewrite the files, however. I thought the -w was not to rewrite? I'd like to run it once a day and only scrape the videos that haven't been downloaded already. What's the recommended way to do that? I also want to keep videos that were removed from the channel (I don't want them to be deleted from the backup).

Thanks!

**Comment by dstftw** [comment]
Read [FAQ](https://github.com/ytdl-org/youtube-dl#how-do-i-download-only-new-videos-from-a-playlist).
