### ISSUE TITLE
How to check if a url is valid (not private not deleted)

### ISSUE THREAD

**Issue by seyeeet** [ytdl-org/youtube-dl#25407]
Im using youtube-dl 2020.05.08 with ubuntu 16.04 and python3.
I want to know if there is a way to check if the youtube link is valid or not (e.g. "https://www.youtube.com/watch?v=5tF9Rt2uFtw"). 
using `youtube-dl -j` is too slow.
I was wondering if there is a better way/faster to do it?

**Comment by dstftw** [comment]
What do you even mean by invalid?

**Comment by seyeeet** [comment]
@dstftw you could have just clicked on the link that I provided to see what I meant.

**Comment by karimelgazar** [comment]
in a python script you can skip these videos without crashing by adding the property `ignoreerrors`
ydl = YoutubeDL({
        # this line is VERY IMPORTANT 
        "ignoreerrors": True})
