### ISSUE TITLE
Iwant.ph m3u8 link

### ISSUE THREAD

**Issue by zackmark29** [ytdl-org/youtube-dl#25419]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

## Description

Link Logs:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.iwant.ph/tv/watch/make-it-with-you/045-miwyunderthestars-mar-13-2020?id=2b6da598-27f0-4083-9a78-25ea29150a59', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-05-15-b18fd2b, ffprobe git-2020-05-15-b18fd2b
[debug] Proxy map: {}
[generic] 045-miwyunderthestars-mar-13-2020?id=2b6da598-27f0-4083-9a78-25ea29150a59: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 045-miwyunderthestars-mar-13-2020?id=2b6da598-27f0-4083-9a78-25ea29150a59: Downloading webpage
[generic] 045-miwyunderthestars-mar-13-2020?id=2b6da598-27f0-4083-9a78-25ea29150a59: Extracting information
ERROR: Unsupported URL: https://www.iwant.ph/tv/watch/make-it-with-you/045-miwyunderthestars-mar-13-2020?id=2b6da598-27f0-4083-9a78-25ea29150a59
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\generic.py", line 3370, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.iwant.ph/tv/watch/make-it-with-you/045-miwyunderthestars-mar-13-2020?id=2b6da598-27f0-4083-9a78-25ea29150a59

M3u8 logs:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://iwantnow-vh.akamaihd.net/i/PRADAVOD/makeitwithyou/20200313/20200313-makeitwithyou-hd-,180000,360000,720000,.mp4.csmil/master.m3u8?hdnea=ip=110.54.251.21~exp=1590531685~acl=/*~hmac=584577b7541c18417694327e19d5a4960fb9bc886e741fda6cd259be9fdcc0e8', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-05-15-b18fd2b, ffprobe git-2020-05-15-b18fd2b
[debug] Proxy map: {}
[generic] *~hmac=584577b7541c18417694327e19d5a4960fb9bc886e741fda6cd259be9fdcc0e8: Requesting header
WARNING: Could not send HEAD request to https://iwantnow-vh.akamaihd.net/i/PRADAVOD/makeitwithyou/20200313/20200313-makeitwithyou-hd-,180000,360000,720000,.mp4.csmil/master.m3u8?hdnea=ip=110.54.251.21~exp=1590531685~acl=/*~hmac=584577b7541c18417694327e19d5a4960fb9bc886e741fda6cd259be9fdcc0e8: HTTP Error 405: Method Not Allowed
[generic] *~hmac=584577b7541c18417694327e19d5a4960fb9bc886e741fda6cd259be9fdcc0e8: Downloading webpage
[generic] *~hmac=584577b7541c18417694327e19d5a4960fb9bc886e741fda6cd259be9fdcc0e8: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://iwantnow-vh.akamaihd.net/i/PRADAVOD/makeitwithyou/20200313/20200313-makeitwithyou-hd-,180000,360000,720000,.mp4.csmil/index_2_av.m3u8?null=0&id=AgBuNvsVaFSWqqNszV6T3GjS++bkZUoJORRm3GCvL0V4iqPf4jXcCMSDW0se8WPEQj8CPGV1ouGtEg%3d%3d&hdntl=exp=1590607395~acl=%2f*~data=hdntl~hmac=fd0a57909ac9be14798ea054213eb82e4c1d3d6ff34f4de5bcc87d8e1a86b2f9'
[download] Destination: master-_~hmac=584577b7541c18417694327e19d5a4960fb9bc886e741fda6cd259be9fdcc0e8.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: _alid_=lUQpKiMRcVL05sYBEcbyAg==; hdntl=exp=1590607395~acl=%2f*~data=hdntl~hmac=fd0a57909ac9be14798ea054213eb82e4c1d3d6ff34f4de5bcc87d8e1a86b2f9
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.66 Safari/537.36
Accept-Language: en-us,en;q=0.5
" -i "https://iwantnow-vh.akamaihd.net/i/PRADAVOD/makeitwithyou/20200313/20200313-makeitwithyou-hd-,180000,360000,720000,.mp4.csmil/index_2_av.m3u8?null=0&id=AgBuNvsVaFSWqqNszV6T3GjS++bkZUoJORRm3GCvL0V4iqPf4jXcCMSDW0se8WPEQj8CPGV1ouGtEg%3d%3d&hdntl=exp=1590607395~acl=%2f*~data=hdntl~hmac=fd0a57909ac9be14798ea054213eb82e4c1d3d6ff34f4de5bcc87d8e1a86b2f9" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:master-_~hmac=584577b7541c18417694327e19d5a4960fb9bc886e741fda6cd259be9fdcc0e8.mp4.part"
ffmpeg version git-2020-05-15-b18fd2b Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200513
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 45.100 / 56. 45.100
  libavcodec     58. 84.100 / 58. 84.100
  libavformat    58. 43.100 / 58. 43.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 81.100 /  7. 81.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[tcp @ 000001e997590480] Starting connection attempt to 104.84.150.174 port 443
[tcp @ 000001e997590480] Successfully connected to 104.84.150.174 port 443
[https @ 000001e99758e2c0] HTTP error 403 Forbidden
https://iwantnow-vh.akamaihd.net/i/PRADAVOD/makeitwithyou/20200313/20200313-makeitwithyou-hd-,180000,360000,720000,.mp4.csmil/index_2_av.m3u8?null=0&id=AgBuNvsVaFSWqqNszV6T3GjS++bkZUoJORRm3GCvL0V4iqPf4jXcCMSDW0se8WPEQj8CPGV1ouGtEg%3d%3d&hdntl=exp=1590607395~acl=%2f*~data=hdntl~hmac=fd0a57909ac9be14798ea054213eb82e4c1d3d6ff34f4de5bcc87d8e1a86b2f9: Server returned 403 Forbidden (access denied)

ERROR: ffmpeg exited with code 1

---------------------------------------------------------------------------------------------

This is an old request from here https://github.com/ytdl-org/youtube-dl/issues/24688.  
but please ignore the request before because i put the wrong link which is mpd video.  
Here's the new link with .m3u8 link

Single link: https://www.iwant.ph/tv/watch/make-it-with-you/045-miwyunderthestars-mar-13-2020?id=2b6da598-27f0-4083-9a78-25ea29150a59

and here's the credentials.
email: zackmark1993@gmail.com 
pass: zackmark123

please don't close this. just ignore the previous request for this site.
this is the correct request.

**Comment by paulwaldmann** [comment]
Any updates on that? Adding iWant.ph would be very awesome, over a 100 million Filipinos and overseas workers would surely appreciate this site-support-request 👍
