### ISSUE TITLE
animexin.xyz

### ISSUE THREAD

**Issue by penismonsters** [ytdl-org/youtube-dl#25422]
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

- Single video: https://animexin.xyz/ze-tian-ji-season-4-episode-12-subbed/
- Single video: https://animexin.xyz/ling-yuspirit-realm-episode-10-subbed-end/

## Description
A site for watching donghua (essentially chinese anime)

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
