### ISSUE TITLE
Can't download instagram videos

### ISSUE THREAD

**Issue by chenyouduan** [ytdl-org/youtube-dl#25428]
### Checklist
 I'm reporting a broken site support
 I've verified that I'm running youtube-dl version 2020.05.08
 I've checked that all provided URLs are alive and playable in a browser
 I've checked that all URLs and arguments with special characters are properly quoted or escaped
 I've searched the bugtracker for similar issues including closed ones

### Verbose log
youtube-dl https://www.instagram.com/p/CAn6-xMA2Sn -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best -o /xxx.mp4 --no-playlist --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.instagram.com/p/CAn6-xMA2Sn', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best', '-o', '/xxx.mp4', '--no-playlist', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.7.4 (CPython) - Darwin-19.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[Instagram] CAn6-xMA2Sn: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/instagram.py", line 195, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1123, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### Description
Since a few days ago, instagram videos could not be downloaded

**Comment by cpyb** [comment]
same

# youtube-dl https://www.instagram.com/p/B6OueRfnjTR/

ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug
