### ISSUE TITLE
can't fetch subscriptions

### ISSUE THREAD

**Issue by FernandoMiguel** [ytdl-org/youtube-dl#2542]
$ youtube-dl --version
2014.03.10

youtube-dl --verbose -i -u email@domain.tld :ytsubs
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-i', '-u', '', ':ytsubs']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
Type account password and press return:
[debug] youtube-dl version 2014.03.10
[debug] Python version 2.7.6 - Linux-3.13.0-16-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[youtube:subscriptions] Downloading login page
[youtube:subscriptions] Logging in
[youtube:subscriptions] subscriptions feed: Downloading page 1
[download] Downloading playlist: Youtube Subscriptions
[youtube:subscriptions] playlist Youtube Subscriptions: Collected 0 video ids (downloading 0 of them)

attaching screenshot of my youtube account subscriptions 
![screenshot from 2014-03-10 23 51 33](https://f.cloud.github.com/assets/168366/2380629/f6aa34a2-a8ae-11e3-834e-c06385fee9b7.png)

**Comment by LollenJumplan** [comment]
The problem seems to be unsolved still because for me, it still gives 0 videos if I try to download my subscriptions via youtube-dl. Also, I don't understand why it is a problem with authentication, because if I enter a wrong password it tells me that. I run "youtube-dl :ytsubs --username=...", then it asks for my password, goes on if its correct and extracts the feed: 0 videos... If I am doing something wrong here, what do I have to change to get it working?

**Comment by LollenJumplan** [comment]
I am experiencing the issue again although my 2-factor auth is turned off at the moment. Also, verbose is not showing any errors. Output:

```
user@some-host:~$ youtube-dl -i --verbose --username=user@provider.com --download-archive=~/.youtube-dl/archive.list :ytsubs 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-i', u'--verbose', u'--username=user@provider.com', u'--download-archive=~/.youtube-dl/archive.list', u':ytsubs']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.10rc1 - Linux-3.16.0-4-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[youtube:subscriptions] Downloading login page
[youtube:subscriptions] Logging in
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
[youtube:subscriptions] playlist Youtube Subscriptions: Collected 0 video ids (downloading 0 of them)
```
