### ISSUE TITLE
ABC.com marking all videos as MSO required

### ISSUE THREAD

**Issue by dellis87** [ytdl-org/youtube-dl#25436]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

Dustins-Mac-mini:youtube-dl dustin$ python3 /Users/dustin/Automation/youtube-dl/youtube-dl -o '/Volumes/Media/TV Shows/%(series)s/%(season)s/%(series)s-s%(season_number)se%(episode_number)s-%(title)s.%(ext)s' https://abc.com/shows/american-housewife/episode-guide/season-04/20-prom -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '/Volumes/Media/TV Shows/%(series)s/%(season)s/%(series)s-s%(season_number)se%(episode_number)s-%(title)s.%(ext)s', 'https://abc.com/shows/american-housewife/episode-guide/season-04/20-prom', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.7.5 (CPython) - Darwin-19.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[Go] 20-prom: Downloading webpage
[Go] VDKA0_uixgx8ru: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "/Users/dustin/Automation/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/Users/dustin/Automation/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Users/dustin/Automation/youtube-dl/youtube-dl/youtube_dl/extractor/go.py", line 187, in _real_extract
    url, video_id, requestor_id, resource)
  File "/Users/dustin/Automation/youtube-dl/youtube-dl/youtube_dl/extractor/adobepass.py", line 1414, in _extract_mvpd_auth
    raise_mvpd_required()
  File "/Users/dustin/Automation/youtube-dl/youtube-dl/youtube_dl/extractor/adobepass.py", line 1379, in raise_mvpd_required
    'and --ap-username and --ap-password or --netrc to provide account credentials.', expected=True)
youtube_dl.utils.ExtractorError: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.


Dustins-Mac-mini:youtube-dl dustin$ ./youtube-dl --version
2020.05.08

```

## Description

ABC.com appears to be working all videos as MSO required even though videos do not require a cable provider sign in when watching via browser.

Example url: https://abc.com/shows/american-housewife/episode-guide/season-04/20-prom

**Comment by jmraker** [comment]
There's a patch to fix it that isn't live yet.  I just got it working on a 2nd youtube-dl install

What I did.
. Download the source: wget https://github.com/ytdl-org/youtube-dl/archive/master.zip
. Unzip the source, 
. Edit the go.py apply the changes at https://github.com/ytdl-org/youtube-dl/pull/25216/commits/5a3e2a4fb1f7ad7e0db7df927bb20464260ad271
. Run the program as before but using youtube-dl/__main__.py (args) 
(mine was ~/youtube-dl/youtube-dl-master/youtube_dl/__main__.py )

My TV show download program finally got the ABC episodes after a month of failures.

**Comment by burkasaurusrex** [comment]
I'm getting the same error on ungated videos even with the patched version

**Comment by dellis87** [comment]
The patch resolved it for me. Make sure you do a “make” after changing the extractor.

**Comment by roadzy** [comment]
This worked for me also.  I just made a backup of the go.py and dumped the full raw code into the old go.py.  Running youtube-dl normally works for me.  I didn't have to compile anything.

**Comment by PutterPlace** [comment]
With limited documentation for Windows users regarding installation, what would one need to do to implement this patch on Windows?

**Comment by magnum32** [comment]
even with the updatw  i am still getting this message [06/12/20 07:00:11] ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.

**Comment by magnum32** [comment]
its been well over a month and the fix still hasn't been integrated into the new versions of youtube-DL.

**Comment by kucksdorfs** [comment]
Any update on this issue? This was implemented in youtube-dlc months ago and has been working fine for me. What is missing from this being merged into master?
https://github.com/blackjack4494/youtube-dlc/pull/149#event-3816849149

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29544

**Comment by 89z** [comment]
URL is not valid anymore

**Comment by 89z** [comment]
URL is dead - issue should be closed

**Comment by dirkf** [comment]
Page is gone.
Please open a new issue with a valid current URL if the issue persists, referencing this one, especially after testing PR #30649 or a new release including it.
