### ISSUE TITLE
using ffmpeg in realtime during download

### ISSUE THREAD

**Issue by brightening-eyes** [ytdl-org/youtube-dl#25449]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

hello,
I want to use pysoundfile to play the downloaded video. but, it doesn't support video, I want to convert the video into ogg and play it while downloading.
is there a way possible to do that?
thanks

**Comment by dstftw** [comment]
Not possible.
