### ISSUE TITLE
Download all unlisted videos from my account

### ISSUE THREAD

**Issue by Kornster** [ytdl-org/youtube-dl#25448]
Hi All,

Sorry if this has been posted before. Ive recently come across youtube-dl and started learning how to use the program. With a recent change with the PS4 Firmware, the ability to record and upload to Facebook was removed, on top of that i was spending a lot more time playing than the PS4 is capable of recording (Currently capped at 60mins), that and the fact sometimes the PS4 is not recording properly ive started using the broadcast option to my YouTube account and then having the video set to Unlisted when i am finished. The reason im using youtube-dl is im trying to grab the videos from my Videos/Live on YouTube Studio so i can upload them to my Cloud storage. Im in no way assuming Google will delete my videos but just wanting to back them up for my own personal reasons (Ive got videos going all the way to the Fraps days). Is there a way with youtube-dl i can grab those videos from the Live section? im about 100 videos into YouTube so im waiting to bulk download them all and then i`ll be able to download each new video singly after its processed and completed.

**Comment by Kornster** [comment]
Whats the reasoning if any for the closure? Adding an "incomplete" label takes me to another issue and doesnt answer the reasoning behind my issue being closed.

**Comment by AlexIIL** [comment]
According to the [`Issue: Ask question`](https://github.com/ytdl-org/youtube-dl/issues/new?labels=question&template=6_question.md&title=) template, from the [new issue menu](https://github.com/ytdl-org/youtube-dl/issues/new/choose):
```
######################################################################
  WARNING!
  IGNORING THE FOLLOWING TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE
######################################################################
```
(As for your original question: I'm not really sure as I only have 3 videos on my account, and I'm not sure what the live section looks like from an account's perspective, or how easy it would be to create a playlist from all of them to download).
