### ISSUE TITLE
Unable to download a web video

### ISSUE THREAD

**Issue by Joe23232** [ytdl-org/youtube-dl#25457]
I want to download a particular video from my blackboard Univeristy page using this command `youtube-dl.exe -u [USER] -p [PASSWORD] https://westernsydney.ap.panopto.com/Panopto/Pages/Viewer.aspx?id=5161353f-71a8-4135-afd2-abb30028c577` however I am getting the following errors:

```
https://westernsydney.ap.panopto.com/Panopto/Pages/Viewer.aspx?id=5161353f-71a8-4135-afd2-abb30028c577
[generic] Viewer: Requesting header
[redirect] Following redirect to https://westernsydney.ap.panopto.com/Panopto/Pages/Auth/Login.aspx?Auth=Viewer&ReturnUrl=%2fPanopto%2fPages%2fViewer.aspx%3fid%3d5161353f-71a8-4135-afd2-abb30028c577
[generic] Login.aspx?Auth=Viewer&ReturnUrl=/Panopto/Pages/Viewer: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Login.aspx?Auth=Viewer&ReturnUrl=/Panopto/Pages/Viewer: Downloading webpage
[generic] Login.aspx?Auth=Viewer&ReturnUrl=/Panopto/Pages/Viewer: Extracting information
ERROR: Unsupported URL: https://westernsydney.ap.panopto.com/Panopto/Pages/Auth/Login.aspx?Auth=Viewer&ReturnUrl=%2fPanopto%2fPages%2fViewer.aspx%3fid%3d5161353f-71a8-4135-afd2-abb30028c577
```

Is there a different flag I can use or something?

**Comment by dstftw** [comment]
You must provide account credentials.

**Comment by Joe23232** [comment]
@dstftw I did provide my account credentials as I typed out

'youtube-dl.exe -u [USER] -p [PASSWORD] https://westernsydney.ap.panopto.com/Panopto/Pages/Viewer.aspx?id=5161353f-71a8-4135-afd2-abb30028c577'

Is there some flag I am missing or something? (I obviously can't post my actual credentials on this post).
