### ISSUE TITLE
Specifying self-defined output file name using something like --batch-file

### ISSUE THREAD

**Issue by QAQOAO** [ytdl-org/youtube-dl#25468]
## Checklist

- [x ] I'm reporting a site feature request
- [x ] I've verified that I'm running youtube-dl version **2020.05.29**
- [x ] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

Hi, can youtube-dl support using own specifying output file name template like --batch-file?

--batch-file requires a text file listing URLs

so can we customize output file name the same way?

Something like -o filename.txt

where filename.txt is like the text file used behind the command--batch-file but change all URLs into respective self-defined output file name, 

For example, let's say I want to download a youtube videos and I wish the filename is 'xx.mp4', 

so I write one text file pasting its URL saving as batchfile.txt, 

then I write another text file pasting xx.mp4, which is the file name I want youtube-dl to use,

after that, saving it as filename.txt

Finally, using youtube-dl -o filename.txt --batch-file batchfile.txt resulting my desired outcome..

**Comment by dstftw** [comment]
Not possible. By design `-o` specifies an output template not a file with output templates.
