### ISSUE TITLE
Y*utube broken

### ISSUE THREAD

**Issue by tripleo11** [ytdl-org/youtube-dl#25465]
- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2020.05.29**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--extract-audio', u'--audio-format', u'm4a', u'-o', u'%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', u'-c', u'--write-pages', u'-i', u'--embed-thumbnail', u'-v', u'https://www.youtube.com/watch?v=IMOy9SsUQ7U&list=RDEMZuveQSkXrTiL_PYq-gIvAw&index=4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.29
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-51-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist RDEMZuveQSkXrTiL_PYq-gIvAw - add --no-playlist to just download video IMOy9SsUQ7U
[youtube:playlist] RDEMZuveQSkXrTiL_PYq-gIvAw: Downloading page 1 of Youtube mix
[youtube:playlist] Saving request to RDEMZuveQSkXrTiL_PYq-gIvAw_https_-_www.youtube.com_watchdisable_polymer=true_list=RDEMZuveQSkXrTiL_PYq-gIvAw_v=L_PYq-gIvAw.dump
[download] Downloading playlist: RDEMZuveQSkXrTiL_PYq-gIvAw
[youtube:playlist] playlist RDEMZuveQSkXrTiL_PYq-gIvAw: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RDEMZuveQSkXrTiL_PYq-gIvAw

```
PASTE VERBOSE LOG HERE
```

Says collected 0 video ids

**Comment by tripleo11** [comment]
Now its working partially if I take out v=....

**Comment by michealespinola** [comment]
This seems to affect both 'watch' and 'playlist' youtube URLs, with the scrape resulting in "Collected 0 video ids (downloading 0 of them)"  This is still a problem as of version 2020.06.06.

**Comment by mrkumar009** [comment]
```
youtube-dl --verbose https://www.youtube.com/playlist?list=RDCLAK5uy_kb7EBi6y3GrtJri4_ZH56Ms786DFEimbM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/playlist?list=RDCLAK5uy_kb7EBi6y3GrtJri4_ZH56Ms786DFEimbM']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.8.1 (CPython) - Windows-8.1-6.3.9600-SP0
[debug] exe versions: ffmpeg N-94377-g817235b195, ffprobe N-94377-g817235b195
[debug] Proxy map: {}
[youtube:playlist] RDCLAK5uy_kb7EBi6y3GrtJri4_ZH56Ms786DFEimbM: Downloading page 1 of Youtube mix
[download] Downloading playlist: RDCLAK5uy_kb7EBi6y3GrtJri4_ZH56Ms786DFEimbM
[youtube:playlist] playlist RDCLAK5uy_kb7EBi6y3GrtJri4_ZH56Ms786DFEimbM: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RDCLAK5uy_kb7EBi6y3GrtJri4_ZH56Ms786DFEimbM
```

This a auto generated youtube playlist from youtube Music channel. If you use link with [watch?list=](https://www.youtube.com/watch?list=RDCLAK5uy_kb7EBi6y3GrtJri4_ZH56Ms786DFEimbM) it redirects to homepage, or if you use it with [playlist?list=](https://www.youtube.com/playlist?list=RDCLAK5uy_kb7EBi6y3GrtJri4_ZH56Ms786DFEimbM) it shows playlist but youtube-dl can't scrape it with both link.

**Comment by tcrxt** [comment]
I have the exact same issue, and I suspect it is caused by a change in youtube.

**Comment by harroguk** [comment]
Same is now happening for 
`https://www.youtube.com/feed/subscriptions`

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'D:\\scripts\\Powershell\\youtube-dl\\cookies.txt', '--verbose', 'https://www.youtube.com/feed/subscriptions']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Windows-2012ServerR2-6.3.9600-SP0
[debug] exe versions: ffmpeg git-2020-06-03-b6d7c4c, ffprobe git-2020-06-03-b6d7c4c
[debug] Proxy map: {}
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
[youtube:subscriptions] playlist Youtube Subscriptions: Downloading 0 videos
[download] Finished downloading playlist: Youtube Subscriptions
```
