### ISSUE TITLE
Downloading transcripts for later reading?

### ISSUE THREAD

**Issue by junomarian** [ytdl-org/youtube-dl#25471]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Is it possible to batch download video transcripts in text format for later reading? Want to download some playlists of TedEX lectures transcripts in readable text format. how i can do this? I am only able to download those srt with text with timestamp.

**Comment by cancerousname69** [comment]
You can download only the subtitles and then convert them to plain text.
