### ISSUE TITLE
New DMAX site

### ISSUE THREAD

**Issue by Reiner1210** [ytdl-org/youtube-dl#25472]
Hello,
DMAX has changed there Web Layout. Videos now playes in place instead of a new window.
So we can not get the URL for youtube-dl. I know that links I have already downloaded are still working. So it's only how to get the URL. E.g. this
https://dmax.de/sendungen/goldrausch-in-alaska/

**Comment by TRoublemaKer0815** [comment]
i have the same problem, i dont get the URL

**Comment by mogol07** [comment]
I already created issue https://github.com/ytdl-org/youtube-dl/issues/25427
