### ISSUE TITLE
Using`local=true` and `quality=dash` query strings of Invidious instance.

### ISSUE THREAD

**Issue by roket1428** [ytdl-org/youtube-dl#25480]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.05.29**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

`local=true` will use the instance's host for proxying `*.googlevideo.com` URLs and `quality=dash` will allow to use dash format (will allow the user to use more format other than the default which are medium and 720p, IIRC).

For instance, `local=true` will use something like <span title="https://instance_canonical_name.tld/videoplayback?expire=1590988093&ei=3TjUXqCqD-qjxN8PnIi18AI&ip=80.67.169.117&id=o-AFZgLb1SzteaDhuqRixYEm5TAnJrV3W5utfIzgkip5gm&itag=303&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C298%2C299%2C302%2C303%2C308%2C313%2C315%2C394%2C395%2C396%2C397&source=youtube&requiressl=yes&mh=aP&mm=31%2C29&mn=sn-a0jpm-a0mz%2Csn-4g5e6nzs&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=318750&vprv=1&mime=video%2Fwebm&gir=yes&clen=239256121&dur=634.566&lmt=1544610219543977&mt=1590966392&fvip=2&keepalive=yes&fexp=23882513&c=WEB&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgGQwUi7C3zRduDfPgTibevfg2ZcDB-sPgSYHSXFGmt6ACIQCFArM4X9sPtn_fa_hfbHVdMpb02brO925XKZkxcRecZQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPAsjdudJfpPHJjjQHgKmafb9oWt6k22MW56l49WOBijAiAjusMavefRUatxu9f5jrM1zgWvGHU-O--FJEeG7epVkw%3D%3D&host=r2---sn-a0jpm-a0mz.googlevideo.com&title=Big+Buck+Bunny+60fps+4K+-+Official+Blender+Foundation+Short+Film-aqz-KE-bpKQ.webm" >`hover over with the mouse`</span> will be used instead of the `*.googlevideo.com` counterpart.

I already explained it a little bit and pretty sure the developers know about it but, `quality=dash` will allow the user to download DASH media. Like if the video has 1080p in webm format, the user will be able to download it and merge it with an audio counterpart.

As closing notes, I suggest that, those options to be default for Invidious instances (at least `local=true` because it can also be disabled from the configs, as you can do with many other things). Because `local=true` improves privacy and as far as I can tell, the projects cares much about privacy, and `quality=dash` allows user to select whatever they want, as with normal YouTube content.

I read all the documents on how to create a useful report. I hope everything is provided and crystal clear. Have a nice day. ^^

**Comment by dstftw** [comment]
youtube-dl does not support invidious directly.

**Comment by roket1428** [comment]
> youtube-dl does not support invidious directly.

#17613 is closed, what should I assumed? I mean, should I *first* create a request about adding *direct* support for invidious or something?
