### ISSUE TITLE
Streamable.com not working

### ISSUE THREAD

**Issue by brettalton** [ytdl-org/youtube-dl#25493]
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running youtube-dl version **2020.05.29**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Tried to download Streamable.com video, URL: https://streamable.com/26m8g0, recieved this error,

```
$ youtube-dl --verbose -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 --no-cache-dir "https://streamable.com/26m8g0"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio', u'--merge-output-format', u'mp4', u'--no-cache-dir', u'https://streamable.com/26m8g0']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.29
[debug] Python version 2.7.16 (CPython) - Darwin-19.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[Streamable] 26m8g0: Downloading JSON metadata
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1636, in process_video_result
    expected=True)
ExtractorError: requested format not available
```

Was able to find the video through webdev tools, but was surprised to see Streamable not supported (although previous closed bug posts say it is).

url: https://streamable.com/26m8g0
mp4: https://cdn-b-east.streamable.com/video/mp4/26m8g0.mp4%3Ftoken=xBhxpChSq8TZiPFA8kwubw&expires=1591076820

**Comment by dstftw** [comment]
Read error message.

**Comment by brettalton** [comment]
That wasn't a helpful response or else I wouldn't have posted it. I was able to manually find the mp4 file, so how is the format not available?

**Comment by dstftw** [comment]
Read FAQ on what does `bestvideo` and `bestaudio` mean or do not touch `-f` at all.
