### ISSUE TITLE
--match-title or --reject-title doesn't work with cyrillic (non ASCII) coded argument

### ISSUE THREAD

**Issue by greyboxgt** [ytdl-org/youtube-dl#25507]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I am trying to filter out some videos with non-latin Cyrillic characters are used in the title. The key word is also in Cyrillic. Here is my example script that doesn't work properly:

`youtube-dl -v --playlist-items 3 --match-title "Смешарики" "https://www.youtube.com/user/TVSmeshariki/videos"`

## Verbose log

> c:\bat>youtube-dl -v --playlist-items 3 --match-title "╨í╨╝╨╡╤ê╨░╤Ç╨╕╨║╨╕" "https://www.youtube.com/user/TVSmeshariki/videos"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--playlist-items', '3', '--match-title', '╨í╨╝╨╡╤ê╨░╤Ç╨╕╨║╨╕', 'https://www.youtube.com/user/TVSmeshariki/videos']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2020-05-15-b18fd2b
[debug] Proxy map: {}
[youtube:user] TVSmeshariki: Downloading channel page
[youtube:playlist] UU5A-Wp9ujcr5g9sYagAafEA: Downloading webpage
[download] Downloading playlist: Uploads from TVSmeshariki
[youtube:playlist] playlist Uploads from TVSmeshariki: Downloading 1 videos
[download] Downloading video 1 of 1
[download] "Свободный обмен - Смешарики Пинкод. Азбука финансовой грамотности |
ПРЕМЬЕРА 2020!" title did not match pattern "╨í╨╝╨╡╤ê╨░╤Ç╨╕╨║╨╕"
[download] Finished downloading playlist: Uploads from TVSmeshariki
>

What should I do to make --match-title or --reject-title working with Cyrillic characters?

**Comment by dstftw** [comment]
Again: it does work perfectly with Cyrrillic characters if you pass them properly.
You pass: `--match-title "╨í╨╝╨╡╤ê╨░╤Ç╨╕╨║╨╕"` as clearly seen from the log. Fix that.

**Comment by greyboxgt** [comment]
@dstftw:  Thanks for the tip!

In case somebody else runs into a similar problem, here is my batch file for Windows:
TVSmeshariki.bat
```
chcp 65001
youtube-dl ^
--cookies cookies.txt ^
--download-archive archive-TVSmeshariki.txt ^
--playlist-items 1-5 ^
--reject-title "трейлер|сборник|серии" ^
-f bestvideo+bestaudio ^
--merge-output-format mkv ^
-o %%(title)s.%%(ext)s ^
-i ^
"https://www.youtube.com/user/TVSmeshariki/videos"
pause
```
And also to avoid "OSError: Failed to write string" error, make sure to configure your cmd (command prompt) properties to use the font that supports Cyrillic (Consolas TTF or Lucida Console TTF).
