### ISSUE TITLE
Offline --get-id

### ISSUE THREAD

**Issue by SebiderSushi** [ytdl-org/youtube-dl#25503]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is it possible to tweak youtube-dl without too much effort so that things like the video id can be inferred from the URL whenever possible?

I am interested in this as it would open up the abilities of the parser towards scripts, so that things like the video id can still be parsed by youtube-dl even if the video is no longer available at it's original source or while the computer running youtube-dl is offline.

**Comment by dstftw** [comment]
Generic solution will require implementing this in each extractor. For partial solution you can use `_VALID_URL` regex and try capture `id` group.
