### ISSUE TITLE
How to know the size of all videos on channel/playlist in advance?

### ISSUE THREAD

**Issue by b00sher** [ytdl-org/youtube-dl#25506]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I want to download all videos from one channel, and I want to know in advance how much disk space it would take, is there a way to do so? I mean, fetch all sizes of videos on channel OR playlist and display theirs sizes. Thanks for awesome tool!

**Comment by dstftw** [comment]
Download playlist metadata as JSON and calculate.
