### ISSUE TITLE
Youtube-dl on termux

### ISSUE THREAD

**Issue by termux4me** [ytdl-org/youtube-dl#25525]
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version

**Comment by PierreKircher** [comment]
-- verbose / and full command you are running would be helping

**Comment by termux4me** [comment]
I fixed the problem

**Comment by termux4me** [comment]
if this error happend just
Restart you connection then use youtube-dl to download from youtube
operating system :5.1 lolipop
App: Termux
