### ISSUE TITLE
OnDemandKorea not working.

### ISSUE THREAD

**Issue by ericfartman** [ytdl-org/youtube-dl#25526]
ERROR: Unable to extract jw config; please report this issue on https://yt-dl.org/bug

**Comment by PierreKircher** [comment]
run the full command with --verbose and post the full results

**Comment by ericfartman** [comment]
> 
> 
> run the full command with --verbose and post the full results


C:\----\user\Downloads\Programs\youtube-dl>youtube-dl -F --verbose https://www.ondemandkorea.com/hey-ana-lets-eat-e01.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--verbose', 'https://www.ondemandkorea.com/hey-ana-lets-eat-e01.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.29
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 6.41.122.215 (US) as X-Forwarded-For.
[OnDemandKorea] hey-ana-lets-eat-e01: Downloading webpage
ERROR: Unable to extract jw config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the
--verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\----\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\----\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\----\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\ondemandkorea.py", line 52, in _real_extract
  File "C:\----\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx45\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract jw config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ericfartman** [comment]
## Checklist



- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2020.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones


## Verbose log



```
PASTE VERBOSE LOG HERE
```


## Description



WRITE DESCRIPTION HERE
asd
