### ISSUE TITLE
`no matches found` and/or certificate issue

### ISSUE THREAD

**Issue by seamusdemora** [ytdl-org/youtube-dl#25532]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

REFERENCES: #25521, #25491 

These issues (REFERENCES) are now marked "CLOSED", but the solution (if there is one) is not clear. Specifically, is this a **yt-dl** issue, or is this an issue with my OS (macOS Catalunacy)? 

I have used **yt-dl** for a couple of years, on several different systems. I have never had trouble until last night - when I installed it on a new system (macOS Catalunacy). I installed using MacPorts in the usual way - the install was successful. Then I tried to use **yt-dl**, but got the following error **immediately**: 

```
% youtube-dl -F https://www.youtube.com/watch?v=8e1ld1uGpXA
zsh: no matches found: https://www.youtube.com/watch?v=8e1ld1uGpXA
```

But clearly this file does exist because I copied from my browser & played it there before putting it in the above command. 

I suspected maybe MacPorts was "behind the times" as **yt-dl** is frequently updated, so I tried this: 

```
% youtube-dl --version
2020.05.29
```

Which looks like the current version. But **clearly** something was wrong because i still get the `no matches found` error! 

So - thinking there may be issues with the MacPorts version, I did an `uninstall` of **yt-dl** from MacPorts, and attempted to install it "directly", using the [instructions here](http://ytdl-org.github.io/youtube-dl/download.html). The result:

```
% sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

And so I have read "the webpage mentioned above", but there is nothing I can find there that is of any use. I do not understand how to fix this. It is not clear whether the problem is with the certificate at `yt-dl.org`, or if it is with my system somehow. And Apple - as is their style now - provides no help ([for example](https://support.apple.com/en-us/HT204446) - wtf is a "profile"??). All I know for certain is that **yt-dl** does not function on my macOS-Catalunacy, NOR does it function any longer on my older Mojave-equipped Macbook. 

So - I am asking that you do not close this issue until it is determined, and stated plainly that the issue is NOT with the certificate at `yt-dl.org`. Of course **any** help with resolving the **original** issue of `zsh: no matches found: https://www.youtube.com/watch?v=8e1ld1uGpXA` would be very much appreciated. Perhaps they are related???

Cheers!

**Comment by dstftw** [comment]
This has nothing to do with referenced issues. `?` is a special character in zsh and must be escaped.

**Comment by seamusdemora** [comment]
>This has nothing to do with referenced issues. ? is a special character in zsh and must be escaped.

Excuse my impertinence, but can you please explain how that has anything to do with the second part of my question? What about the `SSL certificate problem`?

**Comment by tranant2** [comment]
Actually, this helped me solved the problem. This is a coding thing where when you see "?" you need to replace it with "\?"
