### ISSUE TITLE
cant download from youtube with -best -bestaudio 

### ISSUE THREAD

**Issue by ujebehege** [ytdl-org/youtube-dl#25538]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.05.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
 
cant download from youtube with -best -bestaudio  like this code 
 `youtube-dl -best https://www.youtube.com/watch?v=gxud7UL8McM`
or `C:\Users\12345>youtube-dl.exe -bestaudio https://www.youtube.com/watch?v=gxud
7UL8McM`
works only  `C:\Users\12345>youtube-dl https://www.youtube.com/watch?v=gxud7UL8McM`
and it just donwload the video, but i want the best audio forman from the video , like i donwload it before

**Comment by dstftw** [comment]
There is no such option `-bestaudio`.
