### ISSUE TITLE
Does video quality of "video only"+audio have difference with ALREADY merged video

### ISSUE THREAD

**Issue by StaringtheStar** [ytdl-org/youtube-dl#25546]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

YouTube-dl provides multiple formats of videos.
For instance, when I download 720p video, I could select format 22(already merged), but I could select 136 and merge it with other audio formats such as 140.

I want to compare the amount of "LOSS" of videos.
- Already merged format: -f 22
- Video only format: -f 136
- post-merged video format(Video only + audio): -f 136+140

If there are any data or ways to check this, please let me know.

**Comment by dstftw** [comment]
Obviously you won't get files byte to byte equal but they will likely be somewhat close.

**Comment by StaringtheStar** [comment]
@dstftw 
Do you mean they are almost same so it is meaningless to talk about the difference of loss amount?
