### ISSUE TITLE
Slow when starting from a list, fast if resuming

### ISSUE THREAD

**Issue by krisbee** [ytdl-org/youtube-dl#2554]
I normally download a bunch of videos from friends - I put the links in a list, and download at the lowest quality setting (-f 5).  Never a problem until today when I download.  The files are coming in at 15-30k/second.  If I ctrl-c and break out of the program and the rerun, the resume speed skyrockets up to 650k/second...

Is this a youtube-dl issue or a youtube server issue?

Thanks in advance,
Kris

**Comment by dirkf** [comment]
Historical?
