### ISSUE TITLE
 I can't update because I using Windows7?

### ISSUE THREAD

**Issue by khsook69** [ytdl-org/youtube-dl#25547]
![up](https://user-images.githubusercontent.com/66362110/83885798-cf5fc000-a781-11ea-9703-58660badacb7.jpg)

## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by PierreKircher** [comment]
you most likely installed with other means / pip or straight from git update it with those tools
