### ISSUE TITLE
Youtube-DL Not Detecting 1080p Streams On Facebook

### ISSUE THREAD

**Issue by goldensun87** [ytdl-org/youtube-dl#25556]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.06.06**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
https://www.facebook.com/fivepoints/videos/996028423892697/

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/fivepoints/videos/996028423892697/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2020-06-04-7f81785, ffprobe git-2020-06-04-7f81785
[debug] Proxy map: {}
[facebook] 996028423892697: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://video-dfw5-1.xx.fbcdn.net/v/t42.9040-2/10000000_175573326461994_6669545570249474
048_n.mp4?_nc_cat=103&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjRfaHEyX2ZyYWdfMl92aWRlbyJ9&_nc_ohc=QD1nkUCRYPQAX8
X0kvE&_nc_ht=video-dfw5-1.xx&oh=3ba3b4a328fe99e6072d5082fbe2b11a&oe=5EDB598F'
[download] Destination: One story told five ways - meet CJ. After finding an eviction notice at his ho...-99602842389269
7.f175573313128662v.mp4
[download] 100% of 95.51MiB in 00:38
[debug] Invoking downloader on 'https://video-dfw5-2.xx.fbcdn.net/v/t42.1790-2/34002262_447522052361556_7540298375028015
104_n.mp4?_nc_cat=104&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjRfaHExX2ZyYWdfMl9hdWRpbyJ9&_nc_ohc=j4CAMKexg7cAX8
r6JOF&_nc_ht=video-dfw5-2.xx&oh=e02f4ae1d155b7e223764953c595c624&oe=5EDB55D0'
[download] Destination: One story told five ways - meet CJ. After finding an eviction notice at his ho...-99602842389269
7.f447522045694890a.m4a
[download] 100% of 4.76MiB in 00:02
[ffmpeg] Merging formats into "One story told five ways - meet CJ. After finding an eviction notice at his ho...-9960284
23892697.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:One story told five ways - meet CJ. After findin
g an eviction notice at his ho...-996028423892697.f175573313128662v.mp4" -i "file:One story told five ways - meet CJ. Af
ter finding an eviction notice at his ho...-996028423892697.f447522045694890a.m4a" -c copy -map "0:v:0" -map "1:a:0" "fi
le:One story told five ways - meet CJ. After finding an eviction notice at his ho...-996028423892697.temp.mp4"
Deleting original file One story told five ways - meet CJ. After finding an eviction notice at his ho...-996028423892697
.f175573313128662v.mp4 (pass -k to keep)
Deleting original file One story told five ways - meet CJ. After finding an eviction notice at his ho...-996028423892697
.f447522045694890a.m4a (pass -k to keep)
```

## Description

I always look up available formats of a video, before I attempt downloading one.  When I look up this video, and other videos of other series, the 1080p streams do not get detected.

**Comment by dstftw** [comment]
No 1080p exists for this video.

**Comment by goldensun87** [comment]
@dstftw There is a 1080p stream, but youtube-dl is unable to detect it.  That is what I was trying to say.

**Comment by dstftw** [comment]
I did and there is no 1080p as already pointed out.

**Comment by goldensun87** [comment]
@dstftw I just downloaded the 1080p stream using JDownloader.  Here is a screencap.

http://cdn-images.imagevenue.com/8c/2b/d0/ME123PCA_o.jpg

And, here is the MediaInfo.

`General
Complete name               : C:\Users\Navid\Downloads\Five Points S01E01 And Yet Here We Are.mp4
Format                      : MPEG-4
Format profile              : Base Media
Codec ID                    : isom (isom/iso2/avc1/mp41)
File size                   : 219 MiB
Duration                    : 13 min 31 s
Overall bit rate mode       : Variable
Overall bit rate            : 2 268 kb/s
Movie name                  : 996028423892697
Writing application         : Lavf56.40.101

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : Main@L4
Format settings             : CABAC / 5 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 5 frames
Format settings, GOP        : M=4, N=48
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 13 min 31 s
Bit rate                    : 2 216 kb/s
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 23.976 (23976/1000) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.045
Stream size                 : 214 MiB (98%)
Writing library             : x264 core 148
Encoding settings           : cabac=1 / ref=5 / deblock=1:0:0 / analyse=0x1:0x111 / me=hex / subme=8 / psy=0 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=34 / lookahead_threads=5 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=48 / keyint_min=25 / scenecut=0 / intra_refresh=0 / rc_lookahead=48 / rc=crf / mbtree=1 / crf=25.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=16200 / vbv_bufsize=32400 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=2:1.00
Language                    : English
Color range                 : Limited
Color primaries             : BT.709
Transfer characteristics    : BT.709
Matrix coefficients         : BT.709
Codec configuration box     : avcC

Audio
ID                          : 2
Format                      : AAC LC SBR
Format/Info                 : Advanced Audio Codec Low Complexity with Spectral Band Replication
Commercial name             : HE-AAC
Format settings             : NBC
Codec ID                    : mp4a-40-5
Duration                    : 13 min 31 s
Duration_LastFrame          : 104 ms
Bit rate mode               : Variable
Bit rate                    : 48.0 kb/s
Maximum bit rate            : 1 800 kb/s
Channel(s)                  : 2 channels
Channel layout              : L R
Sampling rate               : 48.0 kHz
Frame rate                  : 23.438 FPS (2048 SPF)
Compression mode            : Lossy
Stream size                 : 4.64 MiB (2%)
Language                    : English
Default                     : Yes
Alternate group             : 1

`
