### ISSUE TITLE
Download youtube-dl extracted links with curl

### ISSUE THREAD

**Issue by TheGr33k** [ytdl-org/youtube-dl#25558]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
I am getting an `xhamster` video direct link and then i am trying to download with curl.However i am getting 403 forbidden but youtube-dl can download the video.What am i missing?

`youtube-dl --source-address 51.81.249.34  -g -f mp4-720p  https://xhamster.com/videos/amateureuro-spanish-teen-lily-hall-rides-daddy-on-auditions-14090634`
Output: 
`https://19-14.b.cdn13.com/014/090/634/720p.h264.mp4?cdn_creation_time=1591423200&cdn_ttl=14400&cdn_bw=312k&cdn_bw_fs=484k&cdn_cv_data=51.81.249.34-dvp&cdn_hash=62180286e01b91ce2642d112b3d922cf`

Now i try to download the video with curl

`curl --interface 51.81.249.34 --user-agent "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"  -I "https://19-14.b.cdn13.com/014/090/634/720p.h264.mp4?cdn_creation_time=1591423200&cdn_ttl=14400&cdn_bw=312k&cdn_bw_fs=484k&cdn_cv_data=51.81.249.34-dvp&cdn_hash=62180286e01b91ce2642d112b3d922cf"`

> HTTP/2 403
> server: ucdn/1.16.1
> date: Sat, 06 Jun 2020 06:33:54 GMT
> content-type: text/html
> content-length: 554
> x-ureq-id: PYMqMNZBGw/LQ5t5RiAeHC3ZgXMp/SDvjpZYoec8iOyadR/7iX6gI0QPIsqfeRwA6GQV
> x-served-from: origin
> access-control-allow-origin: *
> access-control-allow-methods: HEAD, GET, OPTIONS

If you check example above , you will see that i kept the same IP address and i even tried to add a useragent but i still get 403 forbidden.

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser
