### ISSUE TITLE
YTSearch: Order results by view_count? Nothing for Pagination?

### ISSUE THREAD

**Issue by radiolondra** [ytdl-org/youtube-dl#25560]
Not an issue, just a couple of questions:

**Q1**:
Using YoutubeDL ytsearch (in python), is there a way to tell `ytsearch` to give back results ordered by descending view_count (most viewed first)?
Something like you did (in 2013) for "ytsearchdate", or some params to add to the query itself (BTW, I already did some attempts without any success).

**Q2**:
Using `ytsearch` I can add the number of results I want to get, something like
`.... "default_search": "ytsearch10", ....` to get information of the first 10 videos. The 10 videos are got from the first (unique) page `ytsearch` uses, so that, next time I ask for 10 videos, I'll get the same results.
It should be a great improvement (at least for me) to have the ability to pass the page number (pagination) from where to get the 10 videos (&page=xx using youtube.com queries, still working parameter).

Many thanks.
Rob

**Comment by dstftw** [comment]
Use Youtube search URL.

**Comment by radiolondra** [comment]
> Use Youtube search URL.

Sorry maybe I'm stupid but I didn't understand your answer.

**Comment by radiolondra** [comment]
OK, understood now. And it works fine!!! Thanks!!!
