### ISSUE TITLE
Call ffmpeg with -hide_banner for crunchyroll m3u8 download

### ISSUE THREAD

**Issue by cancerousname69** [ytdl-org/youtube-dl#25563]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Small convenience improvement: FFmpeg is currently callled without -hide_banner, which is very verbose and can fill up an entire screen. This is wasteful, as many terminal emulators have limited scrollback. The solution would be to include the -hide_banner argument for FFmpeg.

**Comment by 0ddb0d** [comment]
Why is this a desirable feature when you can already pass args to the downloader?

Something like `youtube-dl --external-downloader /your/path/not/mine/ffmpeg --external-downloader-args '-hide_banner'` or add it to your youtube-dl config file if you want to use it all the time, see https://github.com/ytdl-org/youtube-dl/blob/master/README.md#configuration

**Comment by cancerousname69** [comment]
I was just thinking that this would be desirable for any user(who doesn't like messing with arguments). I will close this issue if you think it doesn't serve any purpose.
