### ISSUE TITLE
--flat-playlist Returns 0 Entries For YouTube playlists

### ISSUE THREAD

**Issue by prestonconnors** [ytdl-org/youtube-dl#25565]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --flat-playlist "https://www.youtube.com/watch?v=4NRXx6U8ABQ&list=RDCLAK5uy_kmPRjHDECIcuVwnKsx2Ng7fyNgFKWNJFs&start_radio=1" -vvv                                                      [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--flat-playlist', 'https://www.youtube.com/watch?v=4NRXx6U8ABQ&list=RDCLAK5uy_kmPRjHDECIcuVwnKsx2Ng7fyNgFKWNJFs&start_radio=1', '-vvv']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-101-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist RDCLAK5uy_kmPRjHDECIcuVwnKsx2Ng7fyNgFKWNJFs - add --no-playlist to just download video 4NRXx6U8ABQ
[youtube:playlist] RDCLAK5uy_kmPRjHDECIcuVwnKsx2Ng7fyNgFKWNJFs: Downloading page 1 of Youtube mix
[download] Downloading playlist: RDCLAK5uy_kmPRjHDECIcuVwnKsx2Ng7fyNgFKWNJFs
[youtube:playlist] playlist RDCLAK5uy_kmPRjHDECIcuVwnKsx2Ng7fyNgFKWNJFs: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RDCLAK5uy_kmPRjHDECIcuVwnKsx2Ng7fyNgFKWNJFs

```

## Description

--flat-playlist Returns 0 Entries For YouTube playlists. Before 2020.06.06 this feature returned the proper entries for the playlist.

**Comment by tcrxt** [comment]
> --flat-playlist Returns 0 Entries For YouTube playlists. Before 2020.06.06 this feature returned the proper entries for the playlist.

I downgraded and tried with versions as old as `[2020.03.24](https://github.com/ytdl-org/youtube-dl/releases/tag/2020.03.24)`, and still had the same issue, so it's not a question of released, but of youtube changing something in their set-up.

**Comment by tcrxt** [comment]
Oh, and I guess this is a duplicate of https://github.com/ytdl-org/youtube-dl/issues/25465
