### ISSUE TITLE
--flat-playlist Returning 0 entries

### ISSUE THREAD

**Issue by prestonconnors** [ytdl-org/youtube-dl#25564]
youtube-dl --flat-playlist "https://www.youtube.com/watch?v=4NRXx6U8ABQ&list=RDCLAK5uy_kmPRjHDECIcuVwnKsx2Ng7fyNgFKWNJFs&start_radio=1" -vvv
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--flat-playlist', 'https://www.youtube.com/watch?v=4NRXx6U8ABQ&list=RDCLAK5uy_kmPRjHDECIcuVwnKsx2Ng7fyNgFKWNJFs&start_radio=1', '-vvv']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-101-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist RDCLAK5uy_kmPRjHDECIcuVwnKsx2Ng7fyNgFKWNJFs - add --no-playlist to just download video 4NRXx6U8ABQ
[youtube:playlist] RDCLAK5uy_kmPRjHDECIcuVwnKsx2Ng7fyNgFKWNJFs: Downloading page 1 of Youtube mix
[download] Downloading playlist: RDCLAK5uy_kmPRjHDECIcuVwnKsx2Ng7fyNgFKWNJFs
[youtube:playlist] playlist RDCLAK5uy_kmPRjHDECIcuVwnKsx2Ng7fyNgFKWNJFs: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RDCLAK5uy_kmPRjHDECIcuVwnKsx2Ng7fyNgFKWNJFs

**Comment by prestonconnors** [comment]
Duplicate of which Issue? I couldn't find any matching issues.

**Comment by tcrxt** [comment]
I guess it's a duplicate of 
https://github.com/ytdl-org/youtube-dl/issues/25565
and 
https://github.com/ytdl-org/youtube-dl/issues/25465
