### ISSUE TITLE
downloading movies from TVP VOD are not working anymore [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by Anonymous123456789012** [ytdl-org/youtube-dl#25571]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

C:\Users\User>C:\Users\User\Desktop\youtube-dl.exe -v https://
vod.tvp.pl/video/polskie-100-lat,odc-25-stalinizm-w-polsce,46709363
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vod.tvp.pl/video/polskie-100-lat,odc-
25-stalinizm-w-polsce,46709363']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[tvp] 46709363: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILE
D] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL
: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4
lk\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4
lk\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4
lk\build\youtube_dl\utils.py", line 2736, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open


C:\Users\User>
```

## Description

I'm unable to download movie from VOD TVP website page - https://vod.tvp.pl/video/polskie-100-lat,odc-25-stalinizm-w-polsce,46709363
Oddly it worked fine some time ago, so this website page probably changed something.

I'm also using youtube-dl-gui-0.4 with latest youtube-dl 2020.06.06 and have same error like with only youtube-dl 2020.06.06:
```
[06/07/20 16:26:12] ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
```

## Workaround

Add ```--no-check-certificate``` as command line option.

**Comment by cancerousname69** [comment]
Are you certain that your system time is correct? Either way, this is the website's fault, not youtube-dl's.

**Comment by DevKyleS** [comment]
I'm able to replicate this, and this is an issue with their website, not your system or this tool.
However, this is due to Sectigo's (aka COMODO) _AddTrust External CA Root_ certificate expiring and their cross-signed certs are not trusted in most systems (eg, Windows in this case)
After installing their cross-signed cert I confirmed I was not getting the _CERTIFICATE_VERIFY_FAILED_ error anymore

* Root certs - https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA01N000000rfBO
* Direct link - https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117LT
* https://www.ssllabs.com/ssltest/analyze.html?d=vod.tvp.pl&s=195.245.213.252&latest


## Workarounds
* Pass in the `--no-check-certificate` switch to your CLI command
* Install Sectigo's (aka COMODO) cross-signed certificate Root certificate to your system https://comodoca.my.salesforce.com/sfc/p/#1N000002Ljih/a/3l000000VZ4M/ie5Sho19m8SLjTZkH_VL8efOD1qyGFt9h5Ju1ddtbKQ

**Comment by DevKyleS** [comment]
Since this is an external issue, we can close?

**Comment by ValZapod** [comment]
> Since this is an external issue, we can close?

This is a very important issue. So IMHO, no.

**Comment by codeman101** [comment]
@DevKyleS Thanks for the workaround. I faced the same issue trying to download from animefreak which used to work before. I even installed the latest openssl to my machine (don't think I even had openssl installed before) but it didn't make a difference. Is it possible to remove the ssl check altogether or is it required for other sites to work?

**Comment by ValZapod** [comment]
Who was right? I was right. You should never delete expired root certs. Official Microsoft recommendation. https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/trusted-root-certificates-are-required

**Comment by ValZapod** [comment]
> but it didn't make a difference.

Because youtube-dl has compiled in version of openssl. 


Just you --no-check-certificate. Removal of check is insanity, it will aslo break API.
