### ISSUE TITLE
Audio stream takes up to 5 seconds to start, then catches up all at once.

### ISSUE THREAD

**Issue by sj-dan** [ytdl-org/youtube-dl#25574]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is there a fix to certain audio (streaming) from YouTube videos take some time to start (up to 5 seconds) and then catch up in Discord? What I've noticed is, this issue arises only with certain songs, and it's not random. For example, I try playing https://www.youtube.com/watch?v=zgLTzWaLtkY, and the issue happens. I try
playing https://www.youtube.com/watch?v=gk-aCL6eyGc, and the issue vanishes completely, but when I try playing https://www.youtube.com/watch?v=zgLTzWaLtkY again, the issue returns.

**Comment by dstftw** [comment]
youtube-dl has nothing to do with Discord.
