### ISSUE TITLE
JSON contains full file name (and possibly other identifying metadata) and this cannot be disabled

### ISSUE THREAD

**Issue by hunter0002** [ytdl-org/youtube-dl#25576]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Description

The generated JSON (flag --write-info-json) always includes the full directory name of the video file, which can be a privacy problem if the JSON is or has to be made public, since this leaks the user's OS and often the name of his/her home directory. For example, this affects millions of videos on the Internet Archive, for which the uploaders may not have been aware of this problem. It should be possible -- by default or upon using another flag -- to directly generate a JSON file that contains a minimal amount of identifying information. See https://github.com/bibanon/tubeup/issues/119.

**Comment by vxbinaca** [comment]
>this affects millions of videos on the Internet Archive

it's probably more like 400,000+

**Comment by dstftw** [comment]
No idea what are you even talking about, it does not include any directory names.

**Comment by brandongalbraith** [comment]
youtube-dl includes a `_filename` key with a value of the full path to an asset retrieved from the targeted video url when using the `--write-info-json` flag and rendering the JSON file for video metadata. This could leak your local workstation username, as well as other sensitive information, depending on what information is contained within the path where you're downloading to using youtube-dl if you intend to distribute the JSON file in question (in the case of https://github.com/bibanon/tubeup, we're uploading this file as part of a bundle for each video to create items in the Internet Archive).

@dstftw Would you accept a PR sanitizing this JSON key? Or should I handled sanitizing on our end (https://github.com/bibanon/tubeup/issues/119)?
