### ISSUE TITLE
Youtube Music Video Support (From distributor)

### ISSUE THREAD

**Issue by thisisawesome1994** [ytdl-org/youtube-dl#25587]
## Checklist

- [X ] I'm reporting a site feature request
- [X ] I've verified that I'm running youtube-dl version **2020.06.06**
- [X ] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
Hi. I have been using your youtube-dl for some time now and I know how to use it.
I am however not able to download Youtube Music Video's that are sent to youtube using distributor when using the artist page as the download url.
This is the url: https://www.youtube.com/channel/UCCWLtpQNoq7gbiHqssF4rPg

**Comment by dstftw** [comment]
>This channel has no videos.
