### ISSUE TITLE
Facebook Cannot parse data;

### ISSUE THREAD

**Issue by blieb** [ytdl-org/youtube-dl#25597]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.facebook.com/plusputten/videos/570450283631875/', u'--no-playlist', u'--ignore-config', u'--write-info-json', u'--skip-download', u'--format=[ext=mp4]', u'--username=PRIVATE', u'--password=PRIVATE', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.06
[debug] Python version 2.7.16 (CPython) - Darwin-19.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 570450283631875: Downloading webpage
[facebook] 570450283631875: Downloading webpage
[facebook] 570450283631875: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 481, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 380, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Since today YouTube-dl is unable to download Facebook video's. Tried this on different machines. same error. (linux/macOS)

**Comment by barsnick** [comment]
This can't be an issue with Facebook's videos in general, as they still work for me, including the named one.
It could be an issue with using credentials to log in. I tried only without "--user" and "--password", which is sufficient for the given video.

**Comment by jc-james** [comment]
Same here. I downloaded 2 FB videos but could not do one more after that.
Same command line each time. Worked two times and then no more even after updating YT-DL

`youtube-dl "https://www.facebook.com/telecamfilms/videos/10157490875222224" -u "jj@gg.com" -p "xxxxxxx" --download-archive "/.../ydl_logs.txt" --no-post-overwrites -ciw -o /.../ --verbose`

`Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 484, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 380, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by jbeker** [comment]
I am seeing the same issue using a cookie file. I successfully downloaded another video earlier today and it worked. But this one is not.
