### ISSUE TITLE
Mixer VODs won't download

### ISSUE THREAD

**Issue by ecarr1212** [ytdl-org/youtube-dl#25604]
[Mixer:vod] M0LYJMXDp02DQ4rySa-XdA: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 503: No healthy backends (caused by HTTPError()); please report this issue on https://yt-dl.org/bug

**Comment by geauxlo** [comment]
This issue is going to be closed as soon as it's seen by someone who can close it. You should close it yourself and resubmit it following the issue template.
