### ISSUE TITLE
Instagram post videos get error

### ISSUE THREAD

**Issue by muzunimax** [ytdl-org/youtube-dl#25608]
youtube-dl https://www.instagram.com/p/CBNRz3dHBa3/?utm_source=ig_web_copy_link

ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by zettich** [comment]
https://github.com/ytdl-org/youtube-dl/issues/25354
