### ISSUE TITLE
youtube-dl reject based on the length of the movie

### ISSUE THREAD

**Issue by greyboxgt** [ytdl-org/youtube-dl#25601]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I am trying to find a way to **reject** the download based on the time length of the movie. For example, if the video is longer than 20 minutes, skip it, do not even start downloading. 

Thank you.

**Comment by dstftw** [comment]
`--match-filter`.

**Comment by greyboxgt** [comment]
What will be the `--match-filter` to reject movies less than 20 minutes?

**Comment by greyboxgt** [comment]
Here is the answer in case somebody is looking for this:

`--match-filter "duration < 1200"`
