### ISSUE TITLE
python 3.4.4 in youtube-dl.exe is failing on bitchute (3.8.3 is ok)

### ISSUE THREAD

**Issue by bughit** [ytdl-org/youtube-dl#25617]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

#### [`youtube-dl.exe`](../releases/download/2020.06.06/youtube-dl.exe)`-v -F https://www.bitchute.com/video/gbOENCFP0wfP/` (python 3.4.4)
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.bitchute.com/video/gbOENCFP0wfP/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[BitChute] gbOENCFP0wfP: Downloading webpage
[BitChute] gbOENCFP0wfP: Checking video URL
[BitChute] gbOENCFP0wfP: video URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\bitchute.py", line 66, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

####  [`python.exe`](https://www.python.org/ftp/python/3.8.3/python-3.8.3-embed-amd64.zip)[`youtube-dl`](../releases/download/2020.06.06/youtube-dl)`-v -F https://www.bitchute.com/video/gbOENCFP0wfP/` (python 3.8.3)
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.bitchute.com/video/gbOENCFP0wfP/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.8.3 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[BitChute] gbOENCFP0wfP: Downloading webpage
[BitChute] gbOENCFP0wfP: Checking video URL
[info] Available formats for gbOENCFP0wfP:
format code  extension  resolution note
0            mp4        unknown
```

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl/issues/25491#issuecomment-637047754

**Comment by bughit** [comment]
@dstftw This has nothing to do with certificates, youtube-dl.exe (with python 3.4.4) is able to connect and download the page.

**Comment by dstftw** [comment]
Again: it a clear certificate check problem mentined above due to which download URL is filtered out as invalid.

**Comment by bughit** [comment]
@dstftw 

Ok, it is. The verbose output said nothing about a certificate problem, so was anything but clear. To actually make it clear, the error that caused the url to be filtered out would need to be printed.

Now that you know conclusively from both the update issue and this one, that python 3.4.4 is unable to build an alternate certificate chain when the server is serving expired certs, why do you prefer leaving youtube-dl.exe mysteriously broken for various use cases rather than update python and eliminate these problems?
