### ISSUE TITLE
How to embed subtitles and embed thumbnail when using youtube-dl as a library

### ISSUE THREAD

**Issue by ExeArco** [ytdl-org/youtube-dl#25616]
## Checklist

- [X] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

I cannot seem to be able to emulate the following command line execution of youtube-dl when using youtube-dl as a library.
`youtube-dl --write-sub --embed-subs --write-thumbnail --embed-thumbnail  --merge-output-format mp4 https://www.youtube.com/watch?v=XXXXXXXXXXXX`

I have tried the following as my ydl_opts
```
ydl_opts = {
	'format' : 'bestvideo+bestaudio',
	"writedescription" : "true",
	"writesubtitles" : True,
	"embed-subs" : True,
	'writeinfojson': True,
	"writethumbnail" : True,
	"outtmpl" : "Downloads/%(title)s.%(ext)s)",
	"logger": MyLogger(),
	'postprocessors': [{
		'key': 'FFmpegVideoConvertor',
		'preferedformat': 'mp4',  # one of avi, flv, mkv, mp4, ogg, webm
	},{
		'key': 'FFmpegMetadata'
    }
	],
}
```
This does embed subtitles or thumbnails. I can get the behaviour that I desire by running this from the command line but not using youtube-dl as a library.

**Comment by ExeArco** [comment]
Where is the duplicate issue if this is a duplicate?

**Comment by ExeArco** [comment]
just ended up using a sub process call anyway

**Comment by uyouthe** [comment]
@ExeArco me too. It seems like he closes our issues just because he can.

**Comment by ExeArco** [comment]
@uyouthe I'd have no problem with him closing it if there was either proper documentation on using youtube-dl as a library, because as it stands the current documentation could be written on an index card or if he'd link the supposed duplicate of this issue.
I ended up just using a subprocess call as this wasn't worth getting angry over.
