### ISSUE TITLE
Download from FB / IG Not Working

### ISSUE THREAD

**Issue by M3GABOY** [ytdl-org/youtube-dl#25624]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['-o', '/data/data/com.termux/files/home/storage/downloads/%(extractor_key)s/%(uploader)s/%(title)s-%(id)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--get-id', 'https://m.facebook.com/1995989113962909/posts/2764918380403308/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.8.3 (CPython) - Linux-4.4.205-18423627-aarch64-with-libc
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Proxy map: {}
ERROR: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/extractor/facebook.py", line 472, in _real_extract
    self._search_regex(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Download from Facebook / Instagram not working

**Comment by ajm339** [comment]
I noticed this too. It was working fine now it isn't.  Digging deeper I saw that Instagram Videos used to play on public profiles when you were not logged in, now they do not.  I tried passing a cookies.txt file but started getting the issue in the screenshot attached.

![Screen Shot 2020-06-11 at 9 21 28 AM](https://user-images.githubusercontent.com/4138881/84390086-122bf880-abc5-11ea-8a5c-a553fd0b91ac.png)

**Comment by ajm339** [comment]
Actually sorry I just tried working with your video @M3GABOY and your video definitely works: `youtube-dl 'https://www.facebook.com/watch/?v=1222245888122286'`

**Comment by ajm339** [comment]
What I did was copy and pasted `https://m.facebook.com/1995989113962909/posts/2764918380403308/` in the browser and it did a redirect, then I used the redirected URL `https://www.facebook.com/watch/?v=1222245888122286&_rdr` and it was fine.

**Comment by AbdullahTrees** [comment]
I have been having this issue too, where I can't download videos from Facebook, especially private ones, even when I input my credentials for logging in.

#25765 https://github.com/ytdl-org/youtube-dl/issues/25500

**Comment by dprski33** [comment]
any update on this? It's been nearly a month

**Comment by dud1337** [comment]
Also having this issue with Instagram. Perhaps due to:
>Instagram Videos used to play on public profiles when you were not logged in, now they do not.
