### ISSUE TITLE
python 3.4.4 in youtube-dl.exe should be updated to be able to work around servers sending expired intermediate certs

### ISSUE THREAD

**Issue by bughit** [ytdl-org/youtube-dl#25622]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

http client in newer python versions (3.8.3) can better handle servers sending expired intermediate certs. Like current browsers it will build an alternate chain if possible, whereas 3.4.4 (will/is more likely to) fail to validate the server cert. The following issues illustrate the problem: #25541, #25617.

**Comment by dstftw** [comment]
I've already pointed out numerous of times: py2exe does not support python >3.4. Stop posting duplicates, there is already issues opened for switching from py2exe.

**Comment by serge-sb** [comment]
@dstftw Please have a look at this branch https://github.com/albertosottile/py2exe/tree/py38 of py2exe.
