### ISSUE TITLE
Last week my youtube-dl was working perfectly, now I can't download anything and it keeps on giving me the message "is not recognized as an internal or external command, operable program or batch file". I can't even get through "Downloads" without it giving me the message

### ISSUE THREAD

**Issue by starlightmaca** [ytdl-org/youtube-dl#25634]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Why aren't my commands going through? I've noticed ever since I opened up cmd.exe that the line was in ">" form rather than the usual slash. It wasn't like that in the past week. Could that be the reason why I'm unable to download videos? 
<img width="672" alt="Capture" src="https://user-images.githubusercontent.com/66822141/84481017-09701b00-acc8-11ea-872d-7fb10737dbd3.PNG">
<img width="677" alt="2" src="https://user-images.githubusercontent.com/66822141/84481025-0b39de80-acc8-11ea-8d7e-d91c58367b4f.PNG">

**Comment by garoto** [comment]
`C:\Users\Sam> chdir Downloads`
