### ISSUE TITLE
Funimation Subtitles

### ISSUE THREAD

**Issue by joshbrown50** [ytdl-org/youtube-dl#25645]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

I know there is a pull request to update the funimation extractor to allow it to download the subtitles, but It's been almost 2 months now with no progress. I find it very tedious to manually download the vtt file every time especially when compared to the ease of use of downloading crunchyroll videos with subtitles. 

How long will it take for the pull request to be merged if it does end up being merged? 
And if it's not merged, how to I download that branch so I can stop having to manually download the subtitles?

**Comment by cancerousname69** [comment]
```
--embed-subs
```
Should work.

**Comment by joshbrown50** [comment]
> ```
> --embed-subs
> ```
> 
> Should work.

I tried this and it said there were no subtitle files to embed

**Comment by frozenpandaman** [comment]
why not use nyaa lol

**Comment by Mevious** [comment]
> How long will it take for the pull request to be merged if it does end up being merged?

This is my first pull request so I don't have a good idea. Considering how many open pull requests there are, I don't expect it getting merged any time soon if ever.

> And if it's not merged, how to I download that branch so I can stop having to manually download the subtitles?

You can git clone [my fork](https://github.com/Mevious/youtube-dl/tree/funimation-subtitles) or simply download the code from that page and run youtube-dl from the source folder.
E.g., `python "C:\path_to_downloaded_code\youtube-dl\youtube_dl\__main__.py"`
