### ISSUE TITLE
Site vraitube.com

### ISSUE THREAD

**Issue by WebMechanic** [ytdl-org/youtube-dl#25643]
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://vraitube.com/episodes/cauchemar-en-cuisine-saison-1-episode-1/
- Playlist Show/Seasons: https://vraitube.com/tvshows/cauchemar-en-cuisine/

## Description
vraitube.com is new video site and features french TV Shows. It runs on WordPress.
I was able to run `youtube-dl url-to-some/index-v1-a1.m3u8` once I found the URL in the browser's network panel. FFmpeg was called from yt-dl to merge all 575 segments into a working MP4 video file. 👍

Single Video pages use a "dooplayer" running in an embedded IFRAME (https://dood.to/**[a-z]**/**hash-value**/) using a `.m3u8` file with TS fragments served from  
"https://**some-host**.dood.video/hls/**some-hash**/**some-indexfile**.m3u8".

Useful Episode Titles are available from the `#info` element's `<H1.epih1>` + `<H3.epih3>`. 
The page head `<title>` only contains a generic "Showname Season N Episode M" title also used as the WordPress URL slug.

Below the episode's video player is a list with other episodes from the selected season.
There's also a "Video Sources" panel with a small play button that seems to be disfunctional. To actually play the video I have to click the large play button overlay inside the video player.

A Seasons page has a `#seasons ul.episodios` element for each season. 
Episodes are inside `div.episodiotitle` with a link to the single video page. The link label has the same tilte as the `<H3.epih3>` on the Video page.

**Notice**: if a browser's DevTools are open, script execution is paused in a regular timeout interval due to an active/left-over "debugger" statement -- which is very annoying.
Let the page load completely until the player and its poster image show, then open DevTools.

Thanks!

**Comment by jxu** [comment]
I've been looking into dood.video / dood.so
btw in firefox debugger breakpoints can be disabled 
I didnt find m3u8 so easily. I did find mp4 TS chunks but idk how to save them because i'm noob. I'll investigate further

**Comment by WebMechanic** [comment]
Site's be closed and domain is now for sale, so I'm closing this.
There were no uploads for a while anyway.
Thanks!
