### ISSUE TITLE
Udemy for business - supported?

### ISSUE THREAD

**Issue by petr-hybler** [ytdl-org/youtube-dl#25658]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

hello, does youtube-dl support udemy for business ?? Is it possible to download videos from "companyName".udemy.com  domain?

I tried but not luck .. just making sure it's not me but the tool itself not supporting "subdomains" in udemy.

Worth saying, regular udemy works fine for my personal account.

**Comment by petr-hybler** [comment]
could you please provide the original thread? I can't seem to find one with a resolution for udemy for business .. all are tagged as duplicates

**Comment by llacb47** [comment]
Maybe: https://github.com/ytdl-org/youtube-dl/issues/15883
