### ISSUE TITLE
search keyword bug

### ISSUE THREAD

**Issue by SooOverpowered** [ytdl-org/youtube-dl#25665]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Windows\system32>youtube-dl -v hypnodancer
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'hypnodancer']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.8.3rc1 (CPython) - Windows-10-10.0.19645-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] hypnodancer: Downloading webpage
ERROR: hypnodanceo: YouTube said: This video is unavailable.
Sorry about that.
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\program files\python38\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\program files\python38\lib\site-packages\youtube_dl\extractor\youtube.py", line 1827, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: hypnodanceo: YouTube said: This video is unavailable.
Sorry about that.
```

## Description

The extractor somehow modifies the last letter of any search keyword, thus leading to wrong search result. For example, in the verbose log, the input search keyword was "hypnodancer" but name in the error was "hypnodanceo". A possible fix is to add an empty space after the search keyword, I've tested it in Python and the search keyword remained unchanged.
![image](https://user-images.githubusercontent.com/49089778/84595996-3ddd0600-ae85-11ea-910c-0d8de93fffa5.png)

**Comment by dstftw** [comment]
You are trying to download video with id `hypnodancer` that does not exist.

**Comment by SooOverpowered** [comment]
the thing is youtube-dl actually searched for hypnodanceo instead of hypnodancer, therefore returns the error

**Comment by dstftw** [comment]
Again: you are trying to download https://www.youtube.com/watch?v=hypnodancer that is redirected to https://www.youtube.com/watch?v=hypnodanceo by Youtube.
