### ISSUE TITLE
ABC is now using HLS for it's streaming and Youtube-dl interprets this as a "locked" program.

### ISSUE THREAD

**Issue by DarF234** [ytdl-org/youtube-dl#25660]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.06.06**
- [X] I've checked that all provided URLs are alive and playable in a browser **(ones that support HLS)**
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', 'TestofJK.mp4', 'https://abc.com/shows/jimmy-kimmel-live/episode-guide/2020-06/10-jimmy-kimmel-live-610']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-95085-g525de95679, ffprobe N-95085-g525de95679, rtmpdump 2.4
[debug] Proxy map: {}
[Go] 10-jimmy-kimmel-live-610: Downloading webpage
[Go] VDKA0_uixgx8ru: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\go.py", line 187, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\adobepass.py", line 1414, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\adobepass.py", line 1379, in raise_mvpd_required
youtube_dl.utils.ExtractorError: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.

## Description

WRITE DESCRIPTION HERE

I reported this **several days ago**, but now I have more information.  It seems ABC has been switching to all HLS.  In my first report, only GMA (that I know of) produced this error. Now it appears to affect any content on the ABC site. Youtube-dl reports the following for all ABC **unlocked** content that I've tested:
"ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials."

With my current browser, on **truly locked** content I get the "log in with TV provider" page. With the URL in the log above, I get the video.

I also have an older browser and can confirm with various tests that if the browser says it doesn't handle HLS for a particular URL, then Youtube-dl will report the above error.

**Comment by dstftw** [comment]
You must provide proxy/VPN for any work on this.
