### ISSUE TITLE
SonyLIV

### ISSUE THREAD

**Issue by Mouse753** [ytdl-org/youtube-dl#25667]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.06.06**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl6 -v https://www.sonyliv.com/shows/the-kapil-sharma-show-1700000083/kapil-s-wonderful-audience-1000044877
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.sonyliv.com/shows/the-kapil-sharma-show-1700000083/kapil-s-wonderful-audience-1000044877']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-04-13-59e3a9a
[debug] Proxy map: {}
[generic] kapil-s-wonderful-audience-1000044877: Requesting header
WARNING: Falling back on generic information extractor.
[generic] kapil-s-wonderful-audience-1000044877: Downloading webpage
[generic] kapil-s-wonderful-audience-1000044877: Extracting information
WARNING: [generic] kapil-s-wonderful-audience-1000044877: Failed to parse JSON Extra data: line 15 column 19 - line 17 column 17 (char 691 - 743)
ERROR: Unsupported URL: https://www.sonyliv.com/shows/the-kapil-sharma-show-1700000083/kapil-s-wonderful-audience-1000044877
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\generic.py", line 3370, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.sonyliv.com/shows/the-kapil-sharma-show-1700000083/kapil-s-wonderful-audience-1000044877

## Description

WRITE DESCRIPTION HERE

Downloading is not working since SonyLiv updated their website
official new MPD URL
https://securetoken.sonyliv.com/show_set_thekapilsharmashow_ep127_20200327T145303.mpd

but this is working MPD url
https://streaming.sonyliv.com/show_set_thekapilsharmashow_ep127_20200327T145303.mpd

seems like, need t modify to get working MPD URLs

Please update,
Thanks

**Comment by notfirstfloor** [comment]
i am too facing a similar problem but with a different show

**Comment by HITLER-KILLER** [comment]
when will ytdl is going to update

**Comment by theincognito-inc** [comment]
Same issue, latest youtube-dl. @remitamine Please look into this, if you have time :)

**Comment by remitamine** [comment]
A working Indian VPN or proxy to work on this issue.

**Comment by Mouse753** [comment]
> A working Indian VPN or proxy to work on this issue.
How Do i send it?
By the way, send one on dstftw@gmail.com

**Comment by remitamine** [comment]
if dstftw expressed his interest in working on this issue then no need to send it to me, otherwise you can contact me on the E-Mail from [my profile](https://github.com/remitamine).

**Comment by Mouse753** [comment]
email sent, please check

**Comment by avisihag** [comment]
you need to use the following:
`youtube-dl --add-header "x-playback-session-id: THEXPLAYBACKID" "MPDLINK"`
Just replace THEXPLAYBACKID and MPDLINK by searching for the respective data in the network tab in developer mode. You can open it by pressing f12. Don't forget to reload the site after that and simply search 'mpd' and 'x-playback-session-id'

**Comment by Ashish0804** [comment]
> you need to use the following:
> `youtube-dl --add-header "x-playback-session-id: THEXPLAYBACKID" "MPDLINK"`
> Just replace THEXPLAYBACKID and MPDLINK by searching for the respective data in the network tab in developer mode. You can open it by pressing f12. Don't forget to reload the site after that and simply search 'mpd' and 'x-playback-session-id'

i am able to find the playbackid but where is the mpdlink? can u give an example?

**Comment by avisihag** [comment]
> > you need to use the following:
> > `youtube-dl --add-header "x-playback-session-id: THEXPLAYBACKID" "MPDLINK"`
> > Just replace THEXPLAYBACKID and MPDLINK by searching for the respective data in the network tab in developer mode. You can open it by pressing f12. Don't forget to reload the site after that and simply search 'mpd' and 'x-playback-session-id'
> 
> i am able to find the playbackid but where is the mpdlink? can u give an example?

Did u try searching for mpd in the search bar? This is called mpd link cuz it ends with .mpd. You can read https://www.youtube.com/watch?v=xViWU57xDk4 for more help.

**Comment by Ashish0804** [comment]
> > > you need to use the following:
> > > `youtube-dl --add-header "x-playback-session-id: THEXPLAYBACKID" "MPDLINK"`
> > > Just replace THEXPLAYBACKID and MPDLINK by searching for the respective data in the network tab in developer mode. You can open it by pressing f12. Don't forget to reload the site after that and simply search 'mpd' and 'x-playback-session-id'
> > 
> > 
> > i am able to find the playbackid but where is the mpdlink? can u give an example?
> 
> Did u try searching for mpd in the search bar? This is called mpd link cuz it ends with .mpd. You can read https://www.reddit.com/r/youtubedl/comments/jzd7ig/cant_download_from_sonyliv_website/ for more help.

thanks a lot. Got it working but hope the extractor get's fixed soon.

**Comment by Ashish0804** [comment]
@remitamine hey are you still working on this?

**Comment by remitamine** [comment]
no, the VPN provided by @Mouse753 didn't work for me(problem with OpenVPN config), and i did try later to access to the website with proxies which did allow to access the website(didn't test if access to the manifests is possible), now the website seems to require an account to access any video, i will try later to check again.
