### ISSUE TITLE
Unable to download webpage: <urlopen error [Errno 11001] getaddrinfo failed> (caused by URLError(gaierror(11001, 'getaddrinfo failed')

### ISSUE THREAD

**Issue by surfmuggle** [ytdl-org/youtube-dl#25670]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones #16324
- [x] I've read bugs section in FAQ

## Verbose log

This is what i get:

```

C:\>youtube-dl -v "https://www.youtube.com/watch?v=9A-HLSvtBWc"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=9A-HLSvtBWc']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg git-2020-06-03-b6d7c4c, ffprobe git-2020-06-03-b6d7c4c
[debug] Proxy map: {}
[youtube] 9A-HLSvtBWc: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 11001] getaddrinfo failed> (caused by URLError(gaierror(11001, 'getaddrinfo failed'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\utils.py", line 2736, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open


```

## Description

I wanted to download a video from youtube. Due to an error message u updated to version 2020-06-06 to download it. I tried

 - youtube-dl -v "https://www.youtube.com/watch?v=9A-HLSvtBWc"

But i stil get the error: `Unable to download webpage: <urlopen error [Errno 11001] getaddrinfo failed> (caused by URLError(gaierror(11001, 'getaddrinfo failed')`

**Comment by surfmuggle** [comment]
Link to #16324 added

**Comment by dstftw** [comment]
DNS issue on your side.

**Comment by surfmuggle** [comment]
I am not aware of any DNS trouble. Any hints what i can do?

**Comment by 1keyz1** [comment]
@surfmuggle  It's a network issues. Had the same prolem after a windows 10 update. Got it fixes with repairing windows 10 network tools. 
I did it with [This](https://www.tweaking.com/) application

Select :

- Windows Firewall
- Proxy settings
- Network
- Host File
