### ISSUE TITLE
Allow the user to generate an info.json file with identifying data scrubbed

### ISSUE THREAD

**Issue by hunter0002** [ytdl-org/youtube-dl#25681]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.06.16**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

The `--write-info-json` flag has the potential to include identifying data in the generated info.json file. This includes (but is potentially not limited to):
* Depending on other flags, e.g. those used by the default configuration of tubeup, the `_filename` field may contain the full path name rather than the file name, which may allow the user's home directory name and OS to be inferred (this does not happen by default)
* In most (but not all) googlevideo.com URLs, the user's IP address is included as part of the URL

It should preferably be possible to generate a JSON file with identifying data scrubbed from the file.

This is related to (but not exactly the same issue as) #25576. This is mainly because the IP address leakage issue was not identified initially.

**Comment by dstftw** [comment]
Again:
1. `_filename` does not contain any path only filename according to provided output template.
2. URLs are generated by Youtube. If you modify them in any way download URL will no longer work.

**Comment by garoto** [comment]
How can it be `youtube-dl`'s job to redact personal information like IP addresses from the generated json output? This makes no sense.

**Comment by hunter0002** [comment]
It was implied by another tubeup user that it would be better for youtube-dl to do it to avoid deliberately modifying files uploaded to the Internet Archive. I don't entirely understand this reasoning either.
