### ISSUE TITLE
Youtube subscriptions not working

### ISSUE THREAD

**Issue by AthenaAzuraea** [ytdl-org/youtube-dl#25695]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl "https://www.youtube.com/feed/subscriptions" --cookies Cookies.txt -v
[debug] System config: []
[debug] User config: ['-f', 'bestvideo[height<=1080]+bestaudio/bestvideo+bestaudio/best', '--merge-output-format', 'mkv', '--sub-lang', 'enUS', '--write-sub', '-i', '-o', '%(uploader)s - %(title)s.mkv', '--no-playlist', '--mark-watched', '--reject-title', 'English dub|Portuguese Dub|Spanish Dub|(Live)|Spawncast|(Charity stream)| Podcast | (Dub) |WAN Show']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/feed/subscriptions', '--cookies', 'Cookies.txt', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {}
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
[youtube:subscriptions] playlist Youtube Subscriptions: Downloading 0 videos
[download] Finished downloading playlist: Youtube Subscriptions
```

## Description

Downloading youtube subscriptions seems to have stopped working just recently. Youtube-dl simply reports that there are no videos available, which is not true, as browsing to the URL (for me) shows a bunch of videos.

To reproduce, export all browser cookies (I haven't tried just exporting youtube domain cookies), and try to download https://www.youtube.com/feed/subscriptions. Instead of downloading the videos in the subscriptions, it should just say there are 0 videos available.

I will also note that this exact URL and this exact config has worked a few days prior. Ignoring config (i.e. adding --ignore-config) doesn't help.

**Comment by harroguk** [comment]
Just want to add my own log to the above, started happening on the same day as the  2020.06.16 release, not saying it is this release, just that it started the same day.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'D:\\scripts\\Powershell\\youtube-dl\\cookies.txt', '--verbose', 'https://www.youtube.com/feed/subscriptions']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Windows-2012ServerR2-6.3.9600-SP0
[debug] exe versions: ffmpeg git-2020-06-03-b6d7c4c, ffprobe git-2020-06-03-b6d7c4c
[debug] Proxy map: {}
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
[youtube:subscriptions] playlist Youtube Subscriptions: Downloading 0 videos
[download] Finished downloading playlist: Youtube Subscriptions
```
