### ISSUE TITLE
Is ZDF live supported?

### ISSUE THREAD

**Issue by moridius** [ytdl-org/youtube-dl#25705]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm trying to save live video from [ZDF.de](https://www.zdf.de/sender/zdfneo/zdfneo-live-beitrag-100.html) and it doesn't work yet. Is live video even a supported use case? [This page](https://ytdl-org.github.io/youtube-dl/supportedsites.html) says "ZDF" is supported, but I'm not sure whether that's the VoD part or also live video.

Thanks!

**Comment by dstftw** [comment]
Try and see.

**Comment by moridius** [comment]
Seriously? I tried and got video without audio. I wanted to ask before I open a long bug report for that. Okay, guess I have to do that.
