### ISSUE TITLE
--restrict-filenames removes Russian words - a clear error

### ISSUE THREAD

**Issue by illuminatibit** [ytdl-org/youtube-dl#25701]
- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

Why does the --restrict-filenames option remove Russian words? The parameter is necessary for any countries and our language will not break the name of the video.

**Comment by dstftw** [comment]
Read the description of this option.
