### ISSUE TITLE
pornhub.com - Download limit

### ISSUE THREAD

**Issue by ale5000-git** [ytdl-org/youtube-dl#25708]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Sample:
`youtube-dl https://it.pornhub.com/video/search?search=test+search`

It download 86 pages and it say:
`[PornHubPagedVideoList] playlist video/search: Collected 1742 video ids (downloading 1742 of them)`

Shouldn't there be a limit (at least by default)?
One could just carelessly download more than 1000 video without noticing it.

WRITE QUESTION HERE

**Comment by dstftw** [comment]
No.

**Comment by ale5000-git** [comment]
A very explicative and detailed response :)
