### ISSUE TITLE
Still getting Adobe Pass errors on Browser-playable content

### ISSUE THREAD

**Issue by DarF234** [ytdl-org/youtube-dl#25713]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--geo-bypass', '--verbose', '--retries', '100', '--fragment-retries', '3', '--socket-timeout', '240', '--ignore-errors', '--no-overwrites', '--console-title', '--write-all-thumbnails', '--write-description', '--write-info-json', '--write-annotations', '--write-sub', '--sub-format', 'srt/best', '--all-subs', '-o', "Q:\\NetworkShows\\%2\\%(series)s\\%(series)s [S%(season_number)02d E%(episode_number)02d] ''%(title)s'' d%(upload_date)s [%(resolution)s].%(ext)s", 'https://abc.com/shows/the-bachelor-the-greatest-seasons-ever/episode-guide/season-01/01-sean-lowe']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-95085-g525de95679, ffprobe N-95085-g525de95679, rtmpdump 2.4
[debug] Proxy map: {}
[Go] 01-sean-lowe: Downloading webpage
[Go] VDKA0_uixgx8ru: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\go.py", line 187, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\adobepass.py", line 1414, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\adobepass.py", line 1379, in raise_mvpd_required
youtube_dl.utils.ExtractorError: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.

## Description

WRITE DESCRIPTION HERE
I thought this turned out to be related to issue  #25197. There was some discussion about the fix not in the build yet. I waited until version 2020.06.16.1 came out.  I tested it with two programs chosen at random on ABC.com and they downloaded successfully.  I considered the issue resolved. But this evening all unlocked content was flagged again and had Adobe Pass errors.  The error log above is from an attempt a few minutes ago to download one of the two programs that successfully downloaded after I used 2020.06.16.1. So whatever the problem is, either ABC has made some changes again or the issue was not fixed completely.
I'm, sorry I didn't do enough research before posting this issue the first time. (Ill.) But this time I've done my homework.
I noticed my last issue was flagged with geo-restricted. I have had problems with ABC not recognizing I'm in the US before. But that is not the issue here. I was just wondering why it was flagged.

**Comment by dstftw** [comment]
As already pointed out: you must provide proxy/VPN for any work on this. Stop posting duplicates.

**Comment by magnum32** [comment]
the same thing is happening to me as well.

**Comment by DarF234** [comment]
I assume you are asking if I'm going through a proxy to get to ABC and/or use a "VPN" service?  If not, please clarify.
I  thought I'd written this before.  **No proxy.  No VPN.** 
I hope you read new comments in closed issues.

**Comment by DarF234** [comment]
I would also like to politely and respectfully request that this issue be reopened and the duplicate label removed since it is based on a newer version of youtube-dl than existed at the time of my previous post. A newer edition that was fixed for another issue similar to mine ( #25197) and that issue closed. My problem has occurred after both these previous issues were considered already addressed and resolved. 
(And I already apologized for not seeing  #25197 earlier than I did.)

**Comment by dstftw** [comment]
I'm not asking whether you go through proxy or VPN or not. Do you manage reading english at all?
>you must provide proxy/VPN for any work on this

Meaning you must provide geo unrestricted proxy/VPN to the developer for any work on the issue. Issue won't even be considered until this is met.

**Comment by DarF234** [comment]
There's no need to be insulting just because I'm unfamiliar with the terminology, we each have our own areas of expertise. I am not too proud to admit that I don't know what you are asking me for, let alone how to provide it.

  Google was not my friend when reseaching _geo unrestricted proxy/VPN_. All I found was a list of VPN hosts looking for business.
I don't see any command line switch for youtube-dl pertaining to this.
I haven't seen anything in the guide to filling in the form.
I have been using the Broken Website button?  Am I in the wrong place?
I have looked at other related issues and seen no mention of the term. The only thing is some have incuded the command line, but since that information's in the log, I considered it redundant.

As you have read, I have made an effort to determine what you want.
I will be happy to provide what you want (if I can) if you would do me the courtesy of telling me what it is you want and how to provide it.
Don't get me wrong. I'm **not** technically illiterate, I've been developing in C & C++ for many years.  But when it comes to websites and video extraction, I'm a user, not a developer.
DSF

As an afterthought, between the term "geo unrestricted" and your inference of my lack of knowledge of the English language, is my IP address providing an unclear or non-existent indication of my location?  
If so, I am in the area of Tampa Bay, Florida. U.S.A.

**Comment by 2ShedsJackson** [comment]
> Meaning you must provide geo unrestricted proxy/VPN to a developer for any work on the issue. The issue won't even be considered until this is met.

Aren't any developers located in the United States??

**Comment by stinkteeth** [comment]
The changes in https://github.com/ytdl-org/youtube-dl/commit/5a3e2a4fb1f7ad7e0db7df927bb20464260ad271 seem to fix this, but it seems they weren't applied in 2020.06.16.1.  There was a change request, "Do not touch old patterns" about 15 days ago (https://github.com/ytdl-org/youtube-dl/pull/25216), but that seems to have been cleared.  If you are impatient, apply the changes manually for the time being.

**Comment by DarF234** [comment]
I'd like to do that, but I'm on a Windows machine and, IIRC, they compile it for Linux and someone else has a converter that makes into a Windows executable.
  I am rather impatient, as something I wanted to get is already gone.  In fact, I'm noticing more ABC show pages list clips but no episodes. And I mean summer shows that are running right now.

Could someone here please tell me what the developers need from me? As I said, I couldn't find any useful information.  So what does _geo unrestricted proxy/VPN_ mean in this context?

**Comment by stinkteeth** [comment]
Rather than running the windows binary, you can install the python version of youtube-dl on a windows machine and edit the go.py extractor yourself.  There is a recent post on the videohelp subforum "Video Streaming Downloading" under the topic "ABC.COM help/fix needed please".

**Comment by DarF234** [comment]
I've spent a lot of time on **Videohelp** and **doom9**. And it looks like either doom9 is gone or I don't remember it's address.
Thanks! I'll look into it.
Easy find. First post in the subforum.

**Comment by DarF234** [comment]
Two things:

I would still appreciate it if someone would define geo unrestricted proxy/VPN for my own curiousity.

The thread on VideoHelp seems to be dated compared to the latest on GitHub. I am unable to determine the staus of #25216. (I have always been a solo artist and never played in a band.)  I would think this issue would have a fairly high priority. Is #25216 the latest issue posted that addresses this?

**Comment by bamit** [comment]
> 
> I would still appreciate it if someone would define geo unrestricted proxy/VPN for my own curiousity.
> 
Good morning DarF234.  I too am in the same situation as you.  I live in Central Florida a few miles north of you and I too have been patiently waiting and hoping that the ABC.COM fix would be put in the release version, 

As for your question; A VPN is a Virtual Private Network, and a Proxy is a machine that you use to route your IP requests through. They act as the Middle Man.

What the Developer (dstftw) wants is for you to provide access to a VPN service that you pay for so he can work on the problem.  Since he does not live in the United States, he cannot work on the ABC website because ABC Restricts access based on the users location.  There are several free and easy ways for someone to use a VPN on their own to get around geo-restrcted websites, but he wants you to provide that solution for him,

I hope this helps...

**Comment by DarF234** [comment]
bamit. Thanks for the info. I do know what a proxy server is and what VPN is and was before it was co-opted into it's current meaning.  And I see the reason he doesn't care if I use them or not...as long as I can provide one.
  My problem is this would seem to be a major issue, but there seems to be no active work on it.  I think because it's not a issue of location that this would be a problem for many.  I would think that someone would have filed an issue that could provide them with what they need.  But it just seems to be stalled,
  I Googled an issue page #25917 that claims it's fixed,  But I don't know why it's not being released as a new build.  I've seen times when youtube-dl was updated 4 times a week.  There are instructions there for implementing the fix, but the entry is over a month old and the instructions don't match the contents of the zip file.
The end of that page is a link to here.
I've installed Python and taken a few guesses at what should "run," but I seem to be running into the \ vs / problem. The command prompt used to have a way to change the switch character from / to something else, but that must have been removed a long time ago and wouldn't guarantee that / would = \ as it does for most Win API calls.  Update: It was an entry in config.sys for DOS and was hardly supported then.

I guess my only option is set up a fast, quick and dirty Linux distro in VirtualBox and try from there.  With my luck, by that time the fix will be in the release version.

Thanks again for the info!

**Comment by DarF234** [comment]
From what I can tell, this issue is not one that is pending for the next release.  I don't know what's going on.

**Comment by 2ShedsJackson** [comment]
> I guess my only option is set up a fast, quick and dirty Linux distro in VirtualBox and try from there. With my luck, by that time the fix will be in the release version.

You can also enable the Windows bash subsystem then install a Linux distro via the Microsoft Store.

**Comment by 2ShedsJackson** [comment]
> From what I can tell, this issue is not one that is pending for the next release. I don't know what's going on.

I don't get it. Shouldn't there be more urgency in accessing one of the Big Three television networks?

**Comment by DarF234** [comment]
To all following this.

This page may hold a clue to the holdup.
https://github.com/ytdl-org/youtube-dl/pull/25216#pullrequestreview-425654730

Under "Changes requested" **dstftw** has a change request. And there is one pending reviewer.

To **stinkteeth**, the "Do not touch old patterns." is still written there. As is your mention that the problem still exists.  (Closed, of course.)

Maybe we are waiting for this pending review?

Maybe the fact that it seems most coders may be not in the USA is why it's not getting the priority we'd expect.

Most of the patches I've found are no longer valid due to the age of them.

To **2ShedsJackson**, thanks for the Linux in Windows info, but I'm running 7 and I believe that only applies to 10.

This is _literally_ the longest I personally have seen youtube-dl go without an update.

**Comment by 2ShedsJackson** [comment]
> Maybe the fact that it seems most coders may be not in the USA is why it's not getting the priority we'd expect.

So many extractors are for sites in the U.S. that you'd think developers would already have access to a VPN or proxy in order to keep the extractors updated.

**Comment by DarF234** [comment]
I left a comment/question here (https://github.com/ytdl-org/youtube-dl/pull/25216) 2 days ago but no response or change to the page at all.  I've been warned about duplicate requests, so I'm done.  But you'd think there would be more complaints about this issue.  You don't suppose they fixed it but forgot to update the Windows version?  Anyone here running Linux who still has the problem?

**Comment by magnum32** [comment]
Is this issue EVER going to be fixed?

**Comment by DarF234** [comment]
**Anyone still following this here, go here to issue** #26058
