### ISSUE TITLE
HTTP Error 429

### ISSUE THREAD

**Issue by djalmasi** [ytdl-org/youtube-dl#25718]
Can u help me please?
I always get this message Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Bit i cant do it anything, i blocked ipv6 only connecting ipv4 and now after a week again not working.

**Comment by Midorina** [comment]
https://github.com/ytdl-org/youtube-dl/issues/23638
