### ISSUE TITLE
ERROR: Unable to extract ooyala code

### ISSUE THREAD

**Issue by charles-0** [ytdl-org/youtube-dl#25716]
## Checklist
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Description
I was able to download videos from tastytrade.com until 6/17/2020.  Now I'm getting this error message regarding ooyala code.  When it is working, I was able to download the episode that is playing on the top of the page for that particular date (in the example below, it is the episode on 6/18/2020).
This is the URL for the page and the video that I want to be able to download:
https://www.tastytrade.com/tt/shows/market-mindset/episodes/market-mindset-06-18-2020

## Verbose log
youtube-dl.exe --verbose https://www.tastytrade.com/tt/shows/market-mindset/episodes/market-mindset-06-18-2020
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tastytrade.com/tt/shows/market-mindset/episodes/market-mindset-06-18-2020']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: avconv v11.7, avprobe v11.7, ffmpeg N-85750-ga75ef15, ffprobe N-85750-ga75ef15
[debug] Proxy map: {}
[TastyTrade] market-mindset-06-18-2020: Downloading webpage
ERROR: Unable to extract ooyala code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\tastytrade.py", line 34, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract ooyala code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by mansfiem** [comment]
I'm having the same problem. I tried a couple of different things to no avail.

**Comment by charles-0** [comment]
> 
> 
> I'm having the same problem. I tried a couple of different things to no avail. I wonder if they did something when they updated the site with the speed option. I even tried using a Chrome plugin, but there's no sound with that plugin.

If I remember correctly, I think they switched the HTML5 player from JWPlayer to Brightcove.  Hopefully they will fix this soon.
