### ISSUE TITLE
Add Feature to remove TikTok Watermark And Also Add Support to Download Instagram Photo

### ISSUE THREAD

**Issue by itsmethevkr** [ytdl-org/youtube-dl#25726]
## Checklist

- [ ] I'm reporting a feature request
- [ ] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

## Description

Hello YouTube-DL
Please Add Feature to remove TikTok Watermark From Video And Also Add Support to Download Instagram Photo So it make it Really Great ..

**Comment by runraid** [comment]
Watermarkless support added in this PR https://github.com/ytdl-org/youtube-dl/pull/25895
