### ISSUE TITLE
https://anything2mp3.cc/

### ISSUE THREAD

**Issue by kellyfrancois** [ytdl-org/youtube-dl#25736]
## Checklist

- [x] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by kellyfrancois** [comment]
Downloading Source File: ERROR! Failed to download source file. Please try again later. (Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.)

**Comment by kellyfrancois** [comment]
https://anything2mp3.cc/

Downloading Source File: ERROR! Failed to download source file. Please try again later. (Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.)

**Comment by llacb47** [comment]
Why do you want to download from a youtube downloader??

**Comment by kellyfrancois** [comment]
I normally use the sight to just download music...



Sent via the Samsung Galaxy Note10+, an AT&T 5G Evolution capable smartphone



-------- Original message --------
