### ISSUE TITLE
Need help for downloading video using mpd file

### ISSUE THREAD

**Issue by tathastu871** [ytdl-org/youtube-dl#25754]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
The url to mpd file is not accesible as it causes forbidden error 403 with youtube-dl but using chrome developer tools and curl i dowloaded mpd file. 
Now is there a way to download video using that offline mpd file

**Comment by dstftw** [comment]
No.
