### ISSUE TITLE
Cannot add thumbnail to mp3

### ISSUE THREAD

**Issue by 0xFEDERICO** [ytdl-org/youtube-dl#25750]
# Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log on debian with python 3.7
ERROR: Conversion failed!                                                                                               Traceback (most recent call last):                                                                                        File "/home/federico/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2065, in post_process              files_to_delete, info = pp.run(info)                                                                                  File "/home/federico/.local/lib/python3.7/site-packages/youtube_dl/postprocessor/embedthumbnail.py", line 51, in run      self.run_ffmpeg_multiple_files([filename, thumbnail_filename], temp_filename, options)                                File "/home/federico/.local/lib/python3.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files                                                                                                               raise FFmpegPostProcessorError(msg)                                                                                 youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

## Description

Hi, I have this version /usr/lib/python3.8/site-packages (2020.6.16.1) on my termux installation and when I run this command:
```youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 --embed-thumbnail https://youtu.be/WNeLUngb-Xg```
I get this error:
```ERROR: Conversion failed!```
The only thing I noticed is that if I remove ```--embed-thumbnail``` I no longer get this error, (obviously I need this option).

**Comment by 0xFEDERICO** [comment]
why?

**Comment by 0xFEDERICO** [comment]
@dstftw

**Comment by 0xFEDERICO** [comment]
[This](https://stackoverflow.com/questions/39665160/youtube-dl-python-script-postprocessing-error-ffmpeg-codecs-arent-being-recogn) solution doesn't work

**Comment by 0xFEDERICO** [comment]
Now the command is:
`youtube-dl -v --extract-audio --audio-format mp3 --audio-quality 0 --restrict-filename --output "%(title)s %(artist)s %(album)s.%(ext)s" --embed-thumbnail https://youtu.be/WNeLUngb-Xg`

**Comment by daniel-barrows** [comment]
This appears to be a duplicate of https://github.com/ytdl-org/youtube-dl/issues/25687
