### ISSUE TITLE
ERROR: Unsupported URL

### ISSUE THREAD

**Issue by SherryRajper** [ytdl-org/youtube-dl#25764]
unable to download video form https://www.cp24.com/video?clipId=1982548
get the following 
ERROR: Unsupported URL: https://www.cp24.com/video?clipId=1982548

command:
youtube-dl https://www.cp24.com/video?clipId=1982548

**Comment by ilike2burnthing** [comment]
MPEG-DASH with CENC, not possible using youtube-dl
