### ISSUE TITLE
How to download image / video in Instagram with youtube-dl?

### ISSUE THREAD

**Issue by d2pren** [ytdl-org/youtube-dl#25762]
How to download image or video in Instagram with this tool (youtube-dl)?

## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by remitamine** [comment]
> youtube-dl is a command-line program to download **videos** from YouTube.com and a few more sites.

https://github.com/ytdl-org/youtube-dl#description
