### ISSUE TITLE
Cannot download a Youtube list with more than 100 videos

### ISSUE THREAD

**Issue by jc-james** [ytdl-org/youtube-dl#25768]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I tried to download a youtube list of more than 100 videos (110 exactly) and had this : 
```bash
[youtube:playlist] PLtGPnOSIkvTZQni2FfbT003i6I-qGqv0t: Downloading webpage
[download] Downloading playlist: Siren 17
[youtube:playlist] PLtGPnOSIkvTZQni2FfbT003i6I-qGqv0t: Downloading page #1
ERROR: u'content_html'
```

I came across an old bug report on this https://github.com/ytdl-org/youtube-dl/issues/14076 but it is closed as duplicate.

Yet there is no link to the main ticket issue and I cannot find it.

Any advice on this or do I open an bug report + log ?

**Comment by jc-james** [comment]
incomplete ?

I clearly explained that yt-dl does not download a list that has more than 100 videos (except if one put min-max manually) and that a ticket exists on this issue since 2017 but is closed as a `duplicate` yet the oringinal issue is not to be found.

Litteraly, please reopen issue #14076 or can you please point me in the right issue for this bug ?

What else can I say ?

**Comment by falkolab** [comment]
Same issue. Can't download channel:

```
youtube-dl -f best -ciw --yes-playlist https://www.youtube.com/channel/************************/videos
[youtube:channel] ***********************: Downloading channel page
[youtube:playlist] ***********************: Downloading webpage
[download] Downloading playlist: Uploads from <Author>
[youtube:playlist] ***********************: Downloading page #1
```

**Comment by sawwd** [comment]
Same issue. Don't work if you have more than or equal to 100.

**Comment by jc-james** [comment]
@dstftw 
Please reopen #14076 so we can post logs in it.
Thanks.

**Comment by jc-james** [comment]
Issue seems to have disappeared
Still using youtube-dl 2020.06.16.1

Is it a youtube.com or youtube-dl thing ? I cannot tell.

I tried 3 lists with 100+ videos and they all worked, including the one I had issue with.

@sawwd @falkolab > Can you all confirm it is also working for you all too ?

Thanks

**Comment by falkolab** [comment]
@jc-james Yes I confirm.

**Comment by zengqiang96** [comment]
Same issue. please fix it
