### ISSUE TITLE
Why do you need to have the latest version to report issues?

### ISSUE THREAD

**Issue by anonymous7002** [ytdl-org/youtube-dl#25779]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Why do you need to have the latest version to be able to report acceptable issues?
Every week I manually have to download the file, because there's no auto-update.
It must be a nightmare for Debian user, because you have to update Debian to sid to access the latest version, which can be unstable.

**Comment by dstftw** [comment]
Cause 90% the issue is already fixed. Auto-update works just fine.

**Comment by anonymous7002** [comment]
Well then how to auto-update?

**Comment by dstftw** [comment]
Read FAQ.
