### ISSUE TITLE
ERROR: 'content_html when trying to Download playlist

### ISSUE THREAD

**Issue by kaseipds** [ytdl-org/youtube-dl#25784]
`c:\youtube-dl>youtube-dl -f ''best[height=720]/best'' --ignore-errors https://www.youtube.com/playlist?list=PL9rwutMt9hFXP4EPXYf-u7Ngs--L6NEF3

[youtube:playlist] PL9rwutMt9hFXP4EPXYf-u7Ngs--L6NEF3: Downloading webpage

[download] Downloading playlist: Amakusa Ashikida - 3

[youtube:playlist] PL9rwutMt9hFXP4EPXYf-u7Ngs--L6NEF3: Downloading page #1

ERROR: 'content_html'`

Tried multiple playlists, all ended up with this same last line `ERROR: 'content_html'`

Thanks in advance!

**Comment by tallero** [comment]
Happening on https://www.youtube.com/watch?v=list=UUt-FSaZNOmH29cKokaHoUJg, too.
