### ISSUE TITLE
Using in another python script?

### ISSUE THREAD

**Issue by redbrain** [ytdl-org/youtube-dl#25790]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

YTDL is written in Python. I was wondering if I could somehow call this (like a function) from another Python script and return the result. If this is possible, how would I do that? Thank you in advance.

**Comment by dstftw** [comment]
Read embedding section of FAQ.
