### ISSUE TITLE
Yandex Music is broken

### ISSUE THREAD

**Issue by akimdi** [ytdl-org/youtube-dl#25808]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --rm-cache-dir --extract-audio https://music.yandex.ru/album/10130567/track/63591534

Removing cache dir ~/.cache/youtube-dl ..
[yandexmusic:track] 63591534: Downloading track JSON
[yandexmusic:track] 63591534: Downloading track location url JSON
[yandexmusic:track] 63591534: Downloading track location JSON
ERROR: An extractor error has occurred. (caused by KeyError('storageDir')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by grishka** [comment]
I, too, have a likely related issue with yandex music. I tried downloading an entire album, and while it appeared to complete successfully, it only downloads the first 30 seconds of each track.

```
$ youtube-dl https://music.yandex.ru/album/417333
[yandexmusic:album] 417333: Downloading album JSON
[download] Downloading playlist: Гости из будущего - Best (2001)
[yandexmusic:album] playlist Гости из будущего - Best (2001): Collected 14 video ids (downloading 14 of them)
[download] Downloading video 1 of 14
[yandexmusic:track] 30390995: Downloading track JSON
[yandexmusic:track] 30390995: Downloading track location url JSON
[yandexmusic:track] 30390995: Downloading track location JSON
[download] Destination: Гости из будущего - Люби меня по-французски-30390995.mp3
[download] 100% of 469.84KiB in 00:00
[download] Downloading video 2 of 14
[yandexmusic:track] 30390998: Downloading track JSON
[yandexmusic:track] 30390998: Downloading track location url JSON
[yandexmusic:track] 30390998: Downloading track location JSON
[download] Destination: Гости из будущего - Так отважно-30390998.mp3
[download] 100% of 469.84KiB in 00:00
[download] Downloading video 3 of 14
[yandexmusic:track] 30391000: Downloading track JSON
[yandexmusic:track] 30391000: Downloading track location url JSON
[yandexmusic:track] 30391000: Downloading track location JSON
[download] Destination: Гости из будущего - Это сильнее меня-30391000.mp3
[download] 100% of 469.84KiB in 00:00
[download] Downloading video 4 of 14
...
[download] 100% of 469.84KiB in 00:00
[download] Finished downloading playlist: Гости из будущего - Best (2001)
```
(notice the file sizes)

I'm running youtube-dl 2020.06.16.1.

**Comment by akimdi** [comment]
I'm stupid 🤦
@grishka 
use flag [`--cookies`](https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl)


`youtube-dl --rm-cache-dir --extract-audio --cookies ~/cookies.txt https://music.yandex.ru/album/417333`

**Comment by akimdi** [comment]
It's not a bug.
How can I close issue?

**Comment by grishka** [comment]
Doesn't make a difference to me. Or do I need to dump the related cookies from my browser?

**Comment by akimdi** [comment]
@grishka 
It doesn't matter

**Comment by grishka** [comment]
Well, for me, this
```
$ youtube-dl --cookies ~/cookies.txt https://music.yandex.ru/album/417333
```
still downloads 30-second fragments.

**Comment by akimdi** [comment]
Read the documentation carefully
https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl

**Comment by akimdi** [comment]
![1593641301](https://user-images.githubusercontent.com/6793168/86296067-9a1f8400-bc00-11ea-906f-dbbee3dcb2a9.png)

**Comment by akimdi** [comment]
I downloaded this
https://send.firefox.com/download/c9c48756ad19f6c2/#gKXFFLK5jHA_COlvWDlSsQ

**Comment by grishka** [comment]
Yeah it does download complete tracks with that file filled with yandex cookies dumped from a logged in browser. That's what I meant initially and you said "it doesn't matter" so I assumed it just needed cookies to persist between requests.

**Comment by akimdi** [comment]
How can I close issue?
Because it's not a bug.

**Comment by toimine** [comment]
> I downloaded this https://send.firefox.com/download/c9c48756ad19f6c2/#gKXFFLK5jHA_COlvWDlSsQ

hi, your file's dead, can you upload it anywhere else? having the same problem here

**Comment by toimine** [comment]
@akimdi do the quotes even ping people????? not sure so i'm gonna do this

**Comment by akimdi** [comment]
@toimine  I don't quite understand what you want me to upload

**Comment by toimine** [comment]
@akimdi the cookie file, mine didn't work

**Comment by akimdi** [comment]
@toimine 
This is confidential information. You can create your own cookies-file.
Here is the instruction how to do it
https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl
