### ISSUE TITLE
Custom Thumbnail As Command Line Arguments

### ISSUE THREAD

**Issue by mimesm** [ytdl-org/youtube-dl#25812]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Hi , ThankYou For This Package i dont know python language im php developer so call your package with a function in php to download video and convert it to mp3 now i have a question how can add custom thumbnail to downloaded file with arguments in command line 

example : 

youtube-dl --extract-audio --add-metadata --embed-thumbnail [link custom thumbnail] --audio-quality 0 --id --audio-format mp3 [video url]

**Comment by dstftw** [comment]
You can't.
