### ISSUE TITLE
Youtube - Like and Dislike counters inside JSON sometimes empty

### ISSUE THREAD

**Issue by RomanEmelyanov** [ytdl-org/youtube-dl#25825]
Youtube - Like and Dislike counter inside JSON sometimes empty:

$./youtube-dl --version
2020.06.16.1

Error with videos example:

$ ./youtube-dl -J https://www.youtube.com/watch?v=XSGBVzeBUbk | json_pp | grep -i count
   "dislike_count" : null,
   "view_count" : 16774885,
   "like_count" : null,
$ ./youtube-dl -J https://www.youtube.com/watch?v=hzixp8s4pyg | json_pp | grep -i count
   "like_count" : null,
   "view_count" : 11937665,
   "dislike_count" : null,

Good with videos example:

$ ./youtube-dl -J https://www.youtube.com/watch?v=rO0yXC0oyIA | json_pp | grep -i count
   "dislike_count" : 625,
   "view_count" : 2705803,
   "like_count" : 31129,
$ ./youtube-dl -J https://www.youtube.com/watch?v=wTcNtgA6gHs | json_pp | grep -i count
   "view_count" : 36788300,
   "like_count" : 169235,
   "dislike_count" : 3880,

**Comment by RomanEmelyanov** [comment]
Workaround diff for file youtube.py

```
def _extract_count(count_name):
            return str_to_int(self._search_regex(
                -r'-%s-button[^>]+><span[^>]+class="yt-uix-button-content"[^>]*>([\d,]+)</span>'
                +r'\\"%sCount\\":([\d,]+),'
                % re.escape(count_name),
                video_webpage, count_name, default=None))
```

**Comment by vootshiclone** [comment]
> video_webpage, count_name, default=None))

$ youtube-dl https://www.youtube.com/watch?v=fqLzZ-WUrSc
Traceback (most recent call last):
  File "/home/v01/.local/lib/python3.8/site-packages/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/v01/.local/bin/youtube-dl", line 5, in <module>
    from youtube_dl import main
  File "/home/v01/.local/lib/python3.8/site-packages/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/home/v01/.local/lib/python3.8/site-packages/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/home/v01/.local/lib/python3.8/site-packages/youtube_dl/extractor/extractors.py", line 8, in <module>
    from .abcnews import (
  File "/home/v01/.local/lib/python3.8/site-packages/youtube_dl/extractor/abcnews.py", line 10, in <module>
    from .youtube import YoutubeIE
  File "/home/v01/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2379
    % re.escape(count_name),
    ^
SyntaxError: invalid syntax

**Comment by vootshiclone** [comment]
> def _extract_count(count_name):
>             return str_to_int(self._search_regex(
>                 -r'-%s-button[^>]+><span[^>]+class="yt-uix-button-content"[^>]*>([\d,]+)</span>'
>                 +r'\\"%sCount\\":([\d,]+),'
>                 % re.escape(count_name),
>                 video_webpage, count_name, default=None))

Still empty for all the videos for me. Any advice?

**Comment by RomanEmelyanov** [comment]
Use this patch:

def _extract_count(count_name):
            return str_to_int(self._search_regex(
                r'([0-9,]+) %ss"}}'
                % re.escape(count_name),
                video_webpage, count_name, default=None))

**Comment by vootshiclone** [comment]
> Use this patch:
> 
> ```
> def _extract_count(count_name):
>             return str_to_int(self._search_regex(
>                 r'([0-9,]+) %ss"}}'
>                 % re.escape(count_name),
>                 video_webpage, count_name, default=None))
> ```

It worked! Thank you!
