### ISSUE TITLE
Site Support Request: retrocrush.tv

### ISSUE THREAD

**Issue by fredflintstone124** [ytdl-org/youtube-dl#25829]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.retrocrush.tv/video/true-tears/012328v-i...gave-away-my-tears
- Single video: https://www.retrocrush.tv/video/true-tears/012329v-what...do-i-want-to-do%3F
- Playlist: https://www.retrocrush.tv/series/012355s/true-tears

## Description

This is a retro anime streaming site. It is not currently supported, but I would like to download from it. Thanks!

**Comment by rhamnousia** [comment]
It seems that there is already a request for this Web site open here: https://github.com/ytdl-org/youtube-dl/issues/25577
