### ISSUE TITLE
91porn.com Cannot extract title

### ISSUE THREAD

**Issue by CountParadox** [ytdl-org/youtube-dl#25832]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.91porn.com/view_video.php?viewkey=346411d086b719d26d99']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-106-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[91porn] 346411d086b719d26d99: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/porn91.py", line 39, in _real_extract
    r'<div id="viewvideo-title">([^<]+)</div>', webpage, 'title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

As of recently, I am unable to download from 91porn.com
I get the errors detailed above, some example videos exhibiting this are below:

- http://www.91porn.com/view_video.php?viewkey=346411d086b719d26d99&page=&viewtype=&category=
- http://www.91porn.com/view_video.php?viewkey=e69edd3eb6aaf26df783&page=&viewtype=&category=
- http://www.91porn.com/view_video.php?viewkey=7447423c62b357ac9a8a&page=&viewtype=&category=

**Comment by lzkgbld** [comment]
Hello, may I ask how did you get his address? I sent a wrong message.
![image](https://user-images.githubusercontent.com/46844055/86470052-35356c80-bd6d-11ea-93da-cfce908426cd.png)

**Comment by CountParadox** [comment]
@lzkgbld  the video was likely removed, you can use any video from 91porn

http://www.91porn.com/view_video.php?viewkey=67e4ba8d20d91c9ec3a7

**Comment by CountParadox** [comment]
fix seems to be ready and waiting...

https://github.com/ytdl-org/youtube-dl/pull/25842
