### ISSUE TITLE
Some videos from zonevideo.telequebec.tv won't work

### ISSUE THREAD

**Issue by juef17** [ytdl-org/youtube-dl#25833]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://zonevideo.telequebec.tv/media/55267/le-soleil/passe-partout']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.2 (CPython) - Linux-5.4.0-39-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[TeleQuebec] 55267: Downloading JSON metadata
ERROR: no suitable InfoExtractor for URL limelight:media:6167180337001#__youtubedl_smuggle=%7B%22geo_countries%22%3A+%5B%22CA%22%5D%7D
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
    res = self.extract_info(
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 873, in process_ie_result
    info = self.extract_info(
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 831, in extract_info
    self.report_error('no suitable InfoExtractor for URL %s' % url)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 587, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

## Description

Works: `https://zonevideo.telequebec.tv/media/54116/les-amis/passe-partout`
Doesn't work:  `https://zonevideo.telequebec.tv/media/55267/le-soleil/passe-partout`

The are other examples of videos that work and don't work in the same series that can be found [here](https://zonevideo.telequebec.tv/a-z/832/passe-partout). Basically, the newer ones (top) don't work, and the older ones (bottom) do.

**Comment by patrickdessalle** [comment]
I've noticed that the new videos are not using Limelight but Brightcove. 
I've tried to adapt the current code to Brightcove but it seems that it requires an identifier for telequebec. I'm not in Canada so maybe that explains why I can't find it but it should be looking like this : http://players.brightcove.net/%s/default_default/index.html?videoId=%s

If someone can provide the value for the first %s, I could give it another try.

**Comment by juef17** [comment]
Where can I find such an URL? Looking at the video page's source code doesn't give a hit for 'brightcove'.

Thank you for your reply!

**Comment by patrickdessalle** [comment]
I'm not sure. It's the first time I dig into this :)

It seems to be around 10 to 13 digits that is usually found within the page. It might be in the JSON related to the video itself. So this would mean for your example : https://mnmedias.api.telequebec.tv/api/v2/media/55267 and it's not 6167180337001 because that would be the video id. Maybe you can find it by looking at the network requests in Chrome's Network tab 

That id is likely shared for every telequebec page with the new type of videos as it's seems to be an identifier for telequebec itself on Brightcove's side.

**Comment by juef17** [comment]
I have looked a bit, but unsuccessfully. I have saved all the requests from Chrome's Network Tab, if you want to take a look:

https://www.dropbox.com/s/rla87gzsggamrgl/zonevideo.telequebec.tv.har.7z?dl=1

**Comment by patrickdessalle** [comment]
Thanks, it helped. The id is 6150020952001 (in case I never manage to commit my changes)

I have a working code on my local machine (but it only support Brightcove and not Limelight). I'll clean it up, make it support both the new (Brightcove) and old (Limelight) videos, commit it on my branch and then make a pull request shortly.

**Comment by juef17** [comment]
Thank you very much! Please let me know if I can be of any further help and/or access to Canada sites).

**Comment by patrickdessalle** [comment]
I created a pull request: https://github.com/ytdl-org/youtube-dl/pull/26368

In the meantime and if you're in a hurry, you can also check out my branch ( https://github.com/patrickdessalle/youtube-dl/ ) and download using
$ python -m youtube_dl https://zonevideo.telequebec.tv/media/55267/le-soleil/passe-partout

**Comment by alexislg2** [comment]
Hey @patrickdessalle , can I have access to your code please?
