### ISSUE TITLE
FORMAT specific quality with default audio

### ISSUE THREAD

**Issue by ankandrew** [ytdl-org/youtube-dl#25837]
I want to download a specific quality and with its default audio ( so I don't need to mux them thus having ffmpeg installed)

I tried this (still tries to mux them):

`youtube-dl.exe -f 'bestvideo[height<=240]+bestaudio/best' https://www.youtube.com/watch?v=3SI1E2wZ9Dc`

How can achieve it?

**Comment by dstftw** [comment]
Read FAQ on format selection.
