### ISSUE TITLE
Download m3u8 to container formats other than mp4

### ISSUE THREAD

**Issue by xloem** [ytdl-org/youtube-dl#25840]
## Checklist

- [X] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

m3u8 videos such as twitch are always stored using an mp4 container.  This prevents streaming live video to stdout, as mp4 requires a seekable output.

mkv does not need a seekable output.  Ideally the user could select the format.

I've made some changes locally to quickly customize the extension for twitch by reading a `--default-extension` option, which seems to work fine.

**Comment by dstftw** [comment]
Streaming works just fine with m3u8 videos.

**Comment by xloem** [comment]
Huh.  Not reproducing on the device I'm on now either.  Did you fix something?  I was on another system when I was dealing with this issue.  Maybe it was an ffmpeg thing.  Thanks for reviewing.  See if I bump into it again.

**Comment by JNULYD** [comment]
I have the similar problem. the output file should be a video file, but is set to be filename .m3u8. anyone can tell me how to solve it?

**Comment by JNULYD** [comment]
I have the similar problem. the output file should be a video file, but is set to be filename .m3u8. anyone can tell me how to solve it?
