### ISSUE TITLE
[www.france.tv] dash chunks video: No video formats found

### ISSUE THREAD

**Issue by vtexier** [ytdl-org/youtube-dl#25856]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --verbose https://www.france.tv/france-5/passage-des-arts/1301771-vian-par-debout-sur-le-zinc.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.france.tv/france-5/passage-des-arts/1301771-vian-par-debout-sur-le-zinc.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Git HEAD: ece59ca8
[debug] Python version 3.8.3 (CPython) - Linux-5.4.0-39-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[FranceTVSite] 1301771-vian-par-debout-sur-le-zinc: Downloading webpage
[FranceTV] c6aec772-ee86-4b5b-9728-98375eab839b: Downloading video JSON
[FranceTV] c6aec772-ee86-4b5b-9728-98375eab839b: Downloading geo restriction info
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/vit/.pyenv/versions/3.8.3/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/vit/.pyenv/versions/3.8.3/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/vit/.pyenv/versions/3.8.3/lib/python3.8/site-packages/youtube_dl/extractor/francetv.py", line 209, in _real_extract
    return self._extract_video(video_id, catalog)
  File "/home/vit/.pyenv/versions/3.8.3/lib/python3.8/site-packages/youtube_dl/extractor/francetv.py", line 169, in _extract_video
    self._sort_formats(formats)
  File "/home/vit/.pyenv/versions/3.8.3/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

It seems that the site use the dash format, using a blob url for the [MediaSource](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource):

`<video playsinline="true" style="width: 100%; height: 100%; position: absolute; background-color: black;" crossorigin="anonymous" muted="false" poster="data:image/gif;base64,R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=" preload="auto" src="blob:https://www.france.tv/dbd2091b-fde8-49b7-acd6-e207a722aee5" autoplay=""></video>`

Dash chunks seen in the developer console:

https://cloudreplayfrancetv.akamaized.net/ab3ce8d56bfe5/232920815_france-domtom_TA.ism/ZXhwPTE1OTM2MTI0MTd+YWNsPSUyZmFiM2NlOGQ1NmJmZTUlMmYyMzI5MjA4MTVfZnJhbmNlLWRvbXRvbV9UQS5pc20qfmhtYWM9YjBiY2I5YzcwYTNjZTg1MjUzOGUwMjY4NmE5MmIxMjJlODJlYTc3MmQ3ZjBiOTA4YzllY2UzZGFkM2I0MzFjYw==/dash/232920815_france-domtom_TA-video=2000000-1400.dash

https://cloudreplayfrancetv.akamaized.net/05b0ddbffd6e5/225112657_france-domtom_TA.ism/ZXhwPTE1OTM2MTE4MTV+YWNsPSUyZjA1YjBkZGJmZmQ2ZTUlMmYyMjUxMTI2NTdfZnJhbmNlLWRvbXRvbV9UQS5pc20qfmhtYWM9M2UzNmM2OTZmOWNkOThlOWVlNjJkZTE5MDE0ZTgzNzkwOTk3OTNiNjViZjAzZWQ4OWI1YzZiYWY1YzgxMzNhZQ==/dash/225112657_france-domtom_TA-audio_fre=64000-6432768.dash

**Comment by remitamine** [comment]
Will be fixed in the next version.
