### ISSUE TITLE
Can someone help here with the regex?

### ISSUE THREAD

**Issue by Crypto90** [ytdl-org/youtube-dl#25865]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

I am working on this pull request since the last 2 days:
https://github.com/ytdl-org/youtube-dl/pull/25853

Im nearly finished. Can someone help me with the last regex to get the video duration for each video in a playlist?
I have described the last step on todo here:
https://github.com/ytdl-org/youtube-dl/pull/25853#issuecomment-652567488

**Comment by dstftw** [comment]
Do not post duplicates.
