### ISSUE TITLE
couldn't recognize aria2

### ISSUE THREAD

**Issue by oscarwty** [ytdl-org/youtube-dl#25862]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
λ youtube-dl.exe   https://youtu.be/qWoQLUp8Vnw   -v --proxy 127.0.0.1:1081 -f bestvideo[ext=mp4]+bestaudio[ext=m4a] --external-downloader aria2c
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://youtu.be/qWoQLUp8Vnw', '-v', '--proxy', '127.0.0.1:1081', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]', '--external-downloader', 'aria2c']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2020.01.15
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg N-91590-geb1860e017, ffprobe N-91590-geb1860e017
[debug] Proxy map: {'http': '127.0.0.1:1081', 'https': '127.0.0.1:1081'}
[youtube] qWoQLUp8Vnw: Downloading webpage
[youtube] qWoQLUp8Vnw: Downloading video info webpage
[youtube] qWoQLUp8Vnw: Downloading MPD manifest
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1593634034/ei/kpj8Xpkpw5nCA-2_guAC/ip/161.117.14.249/id/a96a102d4a7c567c/source/youtube/requiressl/yes/playback_host/r4---sn-npoe7ney.googlevideo.com/mh/37/mm/31%2C26/mn/sn-npoe7ney%2Csn-i3beln7d/ms/au%2Conr/mv/m/mvi/3/pl/19/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/792500/vprv/1/mt/1593612330/fvip/4/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRAIgCQJ7tN1QZg5lTGz8FswXA6DEqMJSFtz_n6TDCh61B8QCIEsXcpcc6-18DK7ZnePseGQuk8gq1NgN3C8M7oJG6Qwr/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIgDNLinSf7R0is3Uum4O3mTAkbzF508FZd13ins5CG1hYCIQDdpMXrpjOICr4t0TpmC5YgiH7CrTf71C3mQPAI594MVw%3D%3D'
[dashsegments] Total fragments: 601
[download] Destination: Gravity Rush 2 - Raven's Choice Any% - 49_54-qWoQLUp8Vnw.f299.mp4
[download]   0.5% of ~736.61MiB at 533.86KiB/s ETA 20:59
ERROR: Interrupted by user

```

## Description

I want to download a youtube video via http proxy by using aria2c as the external downloader. However youtube-dl cannot recognize aria2c and still downloads by ffmpeg. I have already added my aria2 directory to PATH environment variable, and aria2c works fine on its own. 

aria2 version 1.35.0
youtube-dl version 2020.06.16.1

![Snipaste_2020-07-01_22-23-36](https://user-images.githubusercontent.com/6859653/86255488-bfed5e80-bbe9-11ea-81f5-adcd43ea66a1.png)

**Comment by dstftw** [comment]
aria2c does not support DASH.

**Comment by oscarwty** [comment]
> 
> 
> aria2c does not support DASH.

Thank you. So what kind of external downloader could I use for youtube video downloading?

**Comment by mhtvsSFrpHdE** [comment]
@oscarwty At the mean time, try https://9xbuddy.org a online downloader for a temporary alternative?

**Comment by dstftw** [comment]
None for DASH.
