### ISSUE TITLE
[ASK] Download all and merge

### ISSUE THREAD

**Issue by Mikolaj98p** [ytdl-org/youtube-dl#25879]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
Hello,
Can I download all formats and merge selected at once execution?
Thx.

PS: Sorry for my bad English

**Comment by dstftw** [comment]
Read FAQ on format selection.
