### ISSUE TITLE
Using Proxys with Password?

### ISSUE THREAD

**Issue by JonaxGames** [ytdl-org/youtube-dl#25875]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello Guys,

is there any option to use Privat Proxys (Proxys with User/Password Login)? I have tryed to use this format: PROXY:PORT:USER:PW but it doesn't work. I don't want to make my proxy server public, so that everyone can use it. 

LOG:
ERROR: Unable to download webpage: nonnumeric port: 'My Proxy Password' (caused by InvalidURL(u"nonnumeric port: 'My Proxy Password'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
https://www.google.com/search?q=proxy+username+password+format
