### ISSUE TITLE
How to Download m4a when MP4 is the best video & opus when WEBM is the best video [no MKV]

### ISSUE THREAD

**Issue by pootz10** [ytdl-org/youtube-dl#25887]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, I'm a new user of youtube-dl, I started using it this week.
I've read the FAQ and googled for the doubt I have, but didn't find an answer for it.

I wanted to set a filter to download automatically the bestvideo and the bestaudio, but when the best video (best bitrate + highest resolution) is a .mp4 the bestaudio used to be the opus audio, so when it finishes the download it becomes a .mkv . I really would like the youtube-dl download the m4a when the mp4 is the best, and the webm audio when the best video is a VP9. So, I don't want the .mkv.

As far I've read and searched about, the only possible answer for this is downloading them separated, even so I didn't found a way it could be detected. "Well this video it was mp4 the best so get the m4a and join into mp4"

The --merge-output-format and --recode-video ends up converting to mkv because of the incompatible video/audio

If I download both audios, there is any practical command I could do to merge the right audio with the best video downloaded ? Or even a better solution for what I require?
Which ffmpeg command youtube-dl uses to merge audio & video?

**EDITED**
I forgot to mention something important.
I'm downloading links on a list.txt I've created.

Thanks in advance.

**Comment by dstftw** [comment]
Read FAQ on format selection.

**Comment by pootz10** [comment]
I'm sorry to bother, I couldn't find a desirable answer for that on the FAQ.
As I told you I'm downloading a list.txt one link per line, in some of them webm is the best in another, mp4.

What are you suggesting, I should use -F command to every link and see by myself these ones webm, these others mp4 ?

The command I was using until I release the best option was not being got, but the MP4 as long it existed.

`youtube-dl -f "bestvideo[height<=2160][ext=mp4]+bestaudio[ext=m4a]/bestvideo[height<=2160][ext=webm]+bestaudio[ext=webm]/best[height<=2160]" -a LiST.txt`
