### ISSUE TITLE
Malware detected in youtube-dl Windows executable

### ISSUE THREAD

**Issue by ahm750** [ytdl-org/youtube-dl#25885]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I am trying to download the youtube-dl.exe file on my Windows machine from the [official website](https://ytdl-org.github.io/youtube-dl/download.html) and Windows Defender keeps on blocking it stating that it is a malware, more specifically it detects the executable to contain BrowserModifier:Win32/Zwangi malware. 

Why does this happen? And why is it detecting Zwangi malware in the Windows executable?

**Comment by dstftw** [comment]
False positive.
