### ISSUE TITLE
Safari Books Online Video Download Quality

### ISSUE THREAD

**Issue by SmartOinker** [ytdl-org/youtube-dl#25897]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have an active [Safari Books Online](https://learning.oreilly.com/) subscription and I tried downloading video courses(indicated by: ![Untitled](https://user-images.githubusercontent.com/67494507/86525299-e7794b00-beb7-11ea-9a4e-e2348cb5e716.png)) there for offline viewing using youtube-dl's bulk download feature. However, the videos downloaded do not have the best quality as shown below: 
![Untitled](https://user-images.githubusercontent.com/67494507/86525372-e7c61600-beb8-11ea-8544-95d6d6bc4f9b.png)
Those videos which display `length`  is of 1080p, while the videos which are empty under the `length` column is of 720p(This was checked using VLC media player's `Codec Information`). However, on Safari Books Online, all the videos are of 1080p. I tried using `youtube-dl -f 'bestvideo+bestaudio/bestvideo+bestaudio' --merge-output-format mp4` or `youtube-dl -f best`, but it did not solve the problem. Is anyone else experiencing this problem or has anyone found a solution to this? Thank you.

P.S. The above course is taken from [here](https://learning.oreilly.com/videos/beginning-php/9781789535686), but it is not the only course facing this problem.

**Comment by SmartOinker** [comment]
After a whole day of experimenting, I found a solution. While specifying `bestvideo[height<=1080]` did not work, it worked when you specify `worst[height>=1080]`. I posted this to help those who faced this problem and I will close this issue.

**Comment by mzafeer** [comment]
Hi, on unrelevant topic. How were you able to download videos from safari. I get error of unsupported link. Can you kindy share your config/command line?

**Comment by SmartOinker** [comment]
You can refer to this for more detail: https://www.quora.com/How-can-I-download-videos-from-Safari-Books-online. However, under the config, change the last line to this best[height>=1080] if u wanted 1080p videos. Take note that learning paths are not supported by Youtube-dl
