### ISSUE TITLE
''Collected 0 video ids'' on sites like crunchyroll and vrv while uısing geo-bypass-country

### ISSUE THREAD

**Issue by celloh123** [ytdl-org/youtube-dl#25907]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '--geo-bypass-country', 'US', '-f', 'best', '--write-sub', '--sub-format', 'best', '--sub-lang', 'enUS', 'https://vrv.co/series/GYVD2K1WY/THE-PROMISED-NEVERLAND']
[debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-05-22-38490cb, ffprobe git-2020-05-22-38490cb
[debug] Proxy map: {}
[debug] Using fake IP 6.167.33.225 (US) as X-Forwarded-For.
[vrv:series] None: Downloading webpage
[vrv:series] GYVD2K1WY: Downloading resource path JSON metadata
[vrv:series] GYVD2K1WY: Downloading CMS Signing JSON metadata
[vrv:series] GYVD2K1WY: Downloading seasons JSON metadata
[download] Downloading playlist: GYVD2K1WY
[vrv:series] playlist GYVD2K1WY: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: GYVD2K1WY
```

## Description

Hi, I wanted to download the Promised Neverland series from crunchyroll but it was region blocked so I first tried to use --geo-bypass-country US but I got the output: collected 0 video ids.
Then I tried to go to vrv.co and try to download from there. This site requires authentication and the Promised Neverland doesn't require a premium account so I give my account credentials if asked. I did the same --geo-bypass-country US in vrv as well but I got the same output.
I don't know why this is caused and I certainly don't know how to fix it bu it seems that problems like this happen when used the command --geo-bypass-country US

**Comment by Columbo199X** [comment]
- Get a VPN or use TOR.
- Install the cookie.txt extension in your brwoser
- Visit the main page of crunchyroll.
- Extract the cookie of the current site by clicking on the extension.

`youtube-dl [URL] --user-agent "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36" --cookies "cookies.txt"`

**Comment by remitamine** [comment]
you have to use a proxy or a VPN.
