### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by picobe** [ytdl-org/youtube-dl#25910]
<!--

######################################################################
  WARNING!
  IGNORING THE FOLLOWING TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE
######################################################################

- [x ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

When I use sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl to install I get curl: (60) SSL certificate problem: certificate has expired. What do I have to do to install it?

**Comment by picobe** [comment]
When I use sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl to install I get curl: (60) SSL certificate problem: certificate has expired . What do I have to do to install it?

**Comment by Drezzler** [comment]
You can use -k for to not check for valid certificate.

Like so `sudo curl -L -k https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl`
