### ISSUE TITLE
No video format found

### ISSUE THREAD

**Issue by InOppositiontotheNewWorldOrder** [ytdl-org/youtube-dl#25915]
[youtube] I6jSIadTrMM: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[1]+  Exit 1                  youtube-dl https://www.youtube.com/watch?v=I6jSIadTrMM

**Comment by InOppositiontotheNewWorldOrder** [comment]
After attempting to insure that I was using the very latest youtube-dl with the command youtube-dl -U, I received this message: youtube-dl -U
Updating to version 2020.06.16.1 ...
ERROR: no write permissions on /usr/local/bin/youtube-dl

**Comment by gaurav-dixitv** [comment]
Looks like you don't have sufficient permissions. Try running with sudo.
sudo youtube-dl -U
