### ISSUE TITLE
Using the "ffmpeg_location" option

### ISSUE THREAD

**Issue by Gloryness** [ytdl-org/youtube-dl#25926]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

With the "ffmpeg_location" option, it describes:
`Location of the ffmpeg/avconv binary; either the path to the binary or its containing directory.`

Will this include only ffmpeg and avconv or will it include the external downloaders too? (aria2c, axel, curl, httpie, wget)

**Comment by dstftw** [comment]
Description clearly states what will it include.
