### ISSUE TITLE
#25553 Locked

### ISSUE THREAD

**Issue by hi117** [ytdl-org/youtube-dl#25938]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, I'm wondering why issue #25553 is locked and if there are any updates on it? I can't upvote or respond to participate in the normal way.

Thank you!

**Comment by dstftw** [comment]
Because of spam/useless +1 noise.
