### ISSUE TITLE
"No video formats found" error on https://www.ceskatelevize.cz/porady/12459503161-evropsky-pribeh/220382566660001-kolebky-evropy/

### ISSUE THREAD

**Issue by B-439** [ytdl-org/youtube-dl#25936]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
'/OS X/Library/Services/Download.service//Contents/Resources/youtube-dl' --verbo
se --write-sub --all-subs --console-title --format 'mp4[height <= 720]+m4a' --merge-output-
format mp4 --prefer-ffmpeg --ffmpeg-location '/OS X/Library/Services/Download.service//Cont
ents/Resources/ffmpeg' --add-metadata --xattrs --output '~/Desktop/%(title)s/%(title)s.%(ex
t)s' 'https://www.ceskatelevize.cz/porady/12459503161-evropsky-pribeh/220382566660001-koleb
ky-evropy/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--write-sub', u'--all-subs', u'--console-title'
, u'--format', u'mp4[height <= 720]+m4a', u'--merge-output-format', u'mp4', u'--prefer-ffmp
eg', u'--ffmpeg-location', u'/OS X/Library/Services/Download.service//Contents/Resources/ff
mpeg', u'--add-metadata', u'--xattrs', u'--output', u'~/Desktop/%(title)s/%(title)s.%(ext)s
', u'https://www.ceskatelevize.cz/porady/12459503161-evropsky-pribeh/220382566660001-kolebk
y-evropy/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.10 (CPython) - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8
[debug] Proxy map: {}
[CeskaTelevizePorady] 220382566660001-kolebky-evropy: Downloading webpage
[CeskaTelevize] iFramePlayer.php: Downloading webpage
[CeskaTelevize] iFramePlayer.php: Downloading JSON metadata
[CeskaTelevize] iFramePlayer.php: Downloading JSON metadata
[CeskaTelevize] 220382566660001: Downloading subtitles
[CeskaTelevize] iFramePlayer.php: Downloading JSON metadata
[CeskaTelevize] iFramePlayer.php: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sur
e you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube
-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/OS X/Library/Services/Download.service//Contents/Resources/youtube-dl/youtube_dl/Y
outubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/OS X/Library/Services/Download.service//Contents/Resources/youtube-dl/youtube_dl/e
xtractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/OS X/Library/Services/Download.service//Contents/Resources/youtube-dl/youtube_dl/e
xtractor/ceskatelevize.py", line 201, in _real_extract
    self._sort_formats(e['formats'])
  File "/OS X/Library/Services/Download.service//Contents/Resources/youtube-dl/youtube_dl/e
xtractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug .
 Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to cal
l youtube-dl with the --verbose flag and include its complete output.

## Description

When trying to download from https://www.ceskatelevize.cz/porady/12459503161-evropsky-pribeh/220382566660001-kolebky-evropy/
I get "No video formats found" error. Other videos from the same site work OK.
WRITE DESCRIPTION HERE

**Comment by mohanvphatak** [comment]
I have same problem when downloading from youtube.
Following is the verbose log:
mohan@shamoha:~/Desktop/songsdownload/Raag Bhup$ youtube-dl https://youtu.be/bRuEg0dmbgI --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://youtu.be/bRuEg0dmbgI', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Linux-5.4.0-40-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] bRuEg0dmbgI: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 2364, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dbkaynor** [comment]
youtube-dl --verbose  https://www.youtube.com/watch?v=xR2gejPnDC8&ab_channel=trinity1416 
[1] 11080
[18:37:29][douglas@douglas-Linux:~/Downloads]$ [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=xR2gejPnDC8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.08
[debug] Python version 3.8.4 (CPython) - Linux-5.3.0-050300-generic-x86_64-with-glibc2.27
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube] xR2gejPnDC8: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl-2020.3.8-py3.8.egg/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl-2020.3.8-py3.8.egg/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl-2020.3.8-py3.8.egg/youtube_dl/extractor/youtube.py", line 2364, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl-2020.3.8-py3.8.egg/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete outpu

**Comment by petyy** [comment]
I have the same problem with **2020.09.20** version of youtube-dl and this link from **Czech Television**: [](https://www.ceskatelevize.cz/porady/13576669986-john-williams-ve-vidni) . The same happens when I do not use -f parameter.

```
$ youtube-dl -f 'bestvideo+bestaudio' https://www.ceskatelevize.cz/porady/13576669986-john-williams-ve-vidni --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'bestvideo+bestaudio', u'https://www.ceskatelevize.cz/porady/13576669986-john-williams-ve-vidni', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-48-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[CeskaTelevizePorady] 13576669986-john-williams-ve-vidni: Downloading webpage
[CeskaTelevize] iFramePlayer.php: Downloading webpage
[CeskaTelevize] iFramePlayer.php: Downloading JSON metadata
[CeskaTelevize] iFramePlayer.php: Downloading JSON metadata
[CeskaTelevize] iFramePlayer.php: Downloading JSON metadata
[CeskaTelevize] iFramePlayer.php: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ceskatelevize.py", line 201, in _real_extract
    self._sort_formats(e['formats'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1359, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
