### ISSUE TITLE
Random video I found on youtube that doesn't work in youtube-dl

### ISSUE THREAD

**Issue by NEOAethyr** [ytdl-org/youtube-dl#25941]
youtube-dl --verbose --list-formats "https://youtube.com/watch?v=m9ThyFE0V1Q"[debug] System config: []

[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--no-call-home', u'--prefer-ffmpeg', u'--verbose', u'--list-formats', u'https://youtube.com/watch?v=m9ThyFE0V1Q']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.17rc1 (CPython) - Linux-5.3.13-m2-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4
[debug] Proxy map: {}
[youtube] m9ThyFE0V1Q: Downloading webpage
ERROR: m9ThyFE0V1Q: YouTube said: Unable to extract video data

Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1893, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: m9ThyFE0V1Q: YouTube said: Unable to extract video data

You can play it back like this though:
https://www.youtube.com/embed/m9ThyFE0V1Q?feature=oembed
However youtube-dl still doesn't hook to it.
It's been a couple years but I'm not seeing the string in the src/json stuff.
And apperrently I can't force youtube to the old ver anymore to debug that.

This example video is an odd one, usually comments get restricted too I think.

**Comment by dstftw** [comment]
You must authenticate.

**Comment by sergeevabc** [comment]
I see the same “Unable to extract video data” error message while trying to download the [following video][1] on Youtube.
However, it is displayed fine without any additional requests (to authenticate, for example) via Hooktube’s [interface][2].
Why?

[1]: https://www.youtube.com/watch?v=dN50YVM4JOM
[2]: https://hooktube.com/watch?v=dN50YVM4JOM

**Comment by NEOAethyr** [comment]
dstftw, Authenticate?
Like my acct, I haven't used this thing in years..?
I put the verbose in there..

I followed the template rules essentially.

If you mean on youtube, I don't have a login, I was banned a year or 2 ago with no warning.
Hence why I'd like to use youtube-dl to pipe to mpv to bypass these things.
I can bypass logging in with the embedded ver.
But youtube-dl still doesn't catch it.

If I need to back these things up for prosperity, and perhaps make a mirror, then wth... :\

**Comment by garoto** [comment]
> If you mean on youtube, I don't have a login, I was banned a year or 2 ago with no warning.

Then you can't download this video.
