### ISSUE TITLE
[Platzi] ERROR: No video formats found;

### ISSUE THREAD

**Issue by JoSecMx** [ytdl-org/youtube-dl#25942]
I love youtube-dl, it is a wonderful project!
But with platzi I always have errors, I managed to repair the url extractor in platzi.py however now I have the "ERROR: No video formats found"

This is depressing given that this project has been so incredible but it is sad when you download videos from platzi, there are always incomplete courses given this error, I hope someone has a solution

**Comment by dirkf** [comment]
I've updated the PR code for #30548. Please test and follow up [there](https://github.com/ytdl-org/youtube-dl/pull/30548).
