### ISSUE TITLE
Error: youtube-dl: undefined method `license' for #<Class:0x00007fb1cea09c18>

### ISSUE THREAD

**Issue by fremaksim** [ytdl-org/youtube-dl#25948]
macOS Catalina  v10.15.5
MacBook Pro (15-inch,2016)
HomeBrew --version  2.4.2

when i run  $ `brew install youtube-dl`, but last error occur.
![image](https://user-images.githubusercontent.com/16516160/87107828-5f1df000-c293-11ea-8449-b38f4aa8f4e9.png)

**Comment by dstftw** [comment]
Report to homebrew.
