### ISSUE TITLE
youtube extractor fails on age-gated videos

### ISSUE THREAD

**Issue by aidalgol** [ytdl-org/youtube-dl#25954]
## Checklist
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
$ youtube-dl -v https://www.youtube.com/watch?v=kWKlmbTudD8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=kWKlmbTudD8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-9-amd64-x86_64-with-debian-10.4
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1
[debug] Proxy map: {}
[youtube] kWKlmbTudD8: Downloading webpage
ERROR: kWKlmbTudD8: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1893, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: kWKlmbTudD8: YouTube said: Unable to extract video data
```

## Description
The youtube extractor is no longer able to extract age-gated videos.  The above output happens with at least the following URLs.
- https://www.youtube.com/watch?v=kWKlmbTudD8
- https://www.youtube.com/watch?v=x94zXO02VPU

**Comment by nastia-diaphan** [comment]
Confirmed by [https://github.com/ytdl-org/youtube-dl/issues/25945#issuecomment-656302592](url)
and then probably related to [https://github.com/ytdl-org/youtube-dl/issues/25945](url)
and to [https://github.com/ytdl-org/youtube-dl/issues/25937](url)

**Comment by nastia-diaphan** [comment]
Confirmed by https://github.com/ytdl-org/youtube-dl/issues/25945#issuecomment-656302592
and then probably related to https://github.com/ytdl-org/youtube-dl/issues/25945
and to https://github.com/ytdl-org/youtube-dl/issues/25937
