### ISSUE TITLE
Latest installation instructions from readme download out of date version.

### ISSUE THREAD

**Issue by Paumanok** [ytdl-org/youtube-dl#25955]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

I was experiencing an issue due to an out of date repo version of youtube-dl so I installed "latest" via the curl command in the read me. This downloaded the 2020.3.24 version, and running ```sudo youtube-dl -U``` would report youtube-dl being up to date with no change.
 ```
➜  ~ youtube-dl --version
2020.03.24
➜  ~ sudo youtube-dl -U  
[sudo] password for matt: 
youtube-dl is up-to-date (2020.06.16.1)
➜  ~ youtube-dl --version
2020.03.24
➜  ~ 
```

I'm reporting as question as to not clog actual bug reports and also not fitting in other categories, just hoping to bring attention to this and have it closed. 

Downloading the tarball and running the binary solved my issue, which was caused by youtube-dl being out of date.

**Comment by dstftw** [comment]
Most likely you have multiple version installed and different `PATH`s for `root` and regular user. So fix your env, nothing to do with youtube-dl.
