### ISSUE TITLE
What is the value next to the resolution in the metafile indicate? Bitrate or the encoding rate?

### ISSUE THREAD

**Issue by arukshani** [ytdl-org/youtube-dl#25961]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

In the note section of the metafile of a youtube video, what's the number next to the resolution indicate? Is it the bitrate for the particular video or the encoding rate? 

For example in the following sample, whats the value 3027k and 3028k  indicate? 

format code  extension  resolution      **note**
248          webm       1920x1080  1080p 3027k , vp9, 30fps, video only, 125.07MiB
302          webm       1280x720   720p60 3028k , vp9, 60fps, video only, 113.25MiB

Thank you.

**Comment by dstftw** [comment]
Total media bitrate.
