### ISSUE TITLE
Strange behavior with default option --yes-playlist

### ISSUE THREAD

**Issue by oleksis** [ytdl-org/youtube-dl#25964]
## Checklist

- [ ] I'm reporting a feature request
- [x ] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x ] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

Strange behavior with default option --yes-playlist = False:

By default --no-playlist = False, that is, I can interpret that initially --yes-playlist = True but in the youtube-dl options option.py --yes-playlist = False by default

https://github.com/ytdl-org/youtube-dl/blob/07af16b92ef52ac29ecd7f1defdca89295fa611c/youtube_dl/options.py#L337

I suggest clarifying the option or setting by default --yes-playlist = True

Regards!

**Comment by dstftw** [comment]
There is not such option `yesplaylist` is the first place, both switches are mapped to `noplaylist` option.
