### ISSUE TITLE
Keep Spaces in File Names

### ISSUE THREAD

**Issue by holygamer** [ytdl-org/youtube-dl#25962]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

The --restrict-filenames flag restricts filenames to only ASCII characters, and avoids "&" and spaces in filenames. Is there any way to keep spaces? Also is there any way to allow any characters that Windows allows in filenames?

**Comment by dstftw** [comment]
No.

**Comment by holygamer** [comment]
Could I pay you to add that feature please?
