### ISSUE TITLE
List channel header image and user avatar on Youtube?

### ISSUE THREAD

**Issue by halcyon1234** [ytdl-org/youtube-dl#25960]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Youtube-dl can extract video-specific thumbnails, and can output format things like author name or channel id.

Could it, along the same lines, retrieve:
- a Youtube channel header image
- the Youtube user's avatar image?

Either by giving it a channel / user ID, or inferring it from the video id?

See attached image for the images I'm describing from a channel page

![movie nights youtubedl example](https://user-images.githubusercontent.com/1354174/87177259-5cc69080-c2a9-11ea-9433-6b07e1daa6a9.png)

**Comment by dstftw** [comment]
No.

**Comment by halcyon1234** [comment]
Thanks for the answer.
