### ISSUE TITLE
Podcasts from samharris.org

### ISSUE THREAD

**Issue by francescopuccettone** [ytdl-org/youtube-dl#25972]
## Checklist 

- [x ] I'm reporting a new site support request
- [ x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that none of provided URLs violate any copyrights
- [x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://samharris.org/subscriber-extras/210-logic-doomsday/
- Single video: https://samharris.org/subscriber-extras/209-a-good-life/
- Playlist: N/A

## Description

Sam Harris's podcast, "Making Sense", used to allow downloading of podcast episodes as MP3 files. Recently, the download button has been removed, and users are forced to listen to episodes through a restricted list of podcast players. This is massively inconvenient for users who prefer to work with the raw audio file. Being able to download these episodes with youtube-dl would be a very useful feature indeed.
NB: These podcasts are behind a paywall and can only be accessed in full from a paid account. I wasn't sure whether this contradicts the copyright infringement mention in the checklist above, and I am also not sure whether it is within youtube-dl's capabilities to work with such webservers!

**Comment by dstftw** [comment]
You must provide account credentials for any work on this.

**Comment by francescopuccettone** [comment]
Happy to do that. Can I PM those to you? And if/when you implement the feature, is it ok to thereafter change the account's password?

**Comment by francescopuccettone** [comment]
So what do you think Sergey?

**Comment by Salastil** [comment]
I'm not sure if the "subscriber bonus" stuff is different from what is publicly visible on the podcasting services, but the RSS feed with the mp3 can be found at https://wakingup.libsyn.com/rss what I downloaded seemed to have worked. I suspect any extractor for this site would probably have to parse the RSS feed for the mp3.
