### ISSUE TITLE
unsupported URL: https://member.pb-institute.de/mitglieder/

### ISSUE THREAD

**Issue by aix2020** [ytdl-org/youtube-dl#25971]
Hi,
please can someone help me?
Thank you
aix2020
 Here the error message:
youtube-dl -v https://member.pb-institute.de/mitglieder/courses/perform-better-online-summit-2020/functional-training/brendon-rearick-exercise-checklists/ --username  --password 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://member.pb-institute.de/mitglieder/courses/perform-better-online-summit-2020/functional-training/brendon-rearick-exercise-checklists/', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.6.9 (CPython) - Linux-5.3.0-62-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[generic] brendon-rearick-exercise-checklists: Requesting header
[redirect] Following redirect to https://member.pb-institute.de/mitglieder/
[generic] mitglieder: Requesting header
WARNING: Falling back on generic information extractor.
[generic] mitglieder: Downloading webpage
[generic] mitglieder: Extracting information
ERROR: Unsupported URL: https://member.pb-institute.de/mitglieder/
Traceback (most recent call last):
  File "/home/xxxx/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/xxxx/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/xxxx/.local/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://member.pb-institute.de/mitglieder/

######################################################################
  WARNING!
  IGNORING THE FOLLOWING TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE
######################################################################

-->

## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dstftw** [comment]
You must provide account credentials for any work on this.
