### ISSUE TITLE
I see someone sells a program included youtube dl inside

### ISSUE THREAD

**Issue by dangmanhcuong87** [ytdl-org/youtube-dl#25978]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question
Hi. I see a man named Ahmed Sattar written a program called Multi Extra, which included youtube dl inside, and now he sells it. Is it legal?
His facebook page, contains a status talks about this: <https://www.facebook.com/ahmed.sattar.5494/>
His official website contains the program: <http://www.softjewel.net/>
Sorry if he asked you before selling this. I post here just because I see youtube dl is free, and he getting money by your program.
Cuong

WRITE QUESTION HERE

**Comment by springbok01** [comment]
As per the ytdl license:

> Anyone is free to copy, modify, publish, use, compile, sell, or
> distribute this software, either in source code form or as a compiled
> binary, for any purpose, commercial or non-commercial, and by any
> means.

Which would imply that what Ahmed Sattar is doing is perfectly within the license. It does seem as if he has added other functionality, so it may not be a direct copy.
