### ISSUE TITLE
Getting the full description for a video (getting past the "Show More" prompt)

### ISSUE THREAD

**Issue by joeschmoe40** [ytdl-org/youtube-dl#25998]
I have a process (script) that has been running successfully for a long time.  One of the things it does is to uses youtube-dl to retrieve the json file for the video in question, using --write-info-json.  Then, I process that file with "jq" and extract out the Description field for further processing.  As I say, it has all been working just fine, up until about a week or two ago.

However, what I have noticed lately is that the Description field is truncated after about 100 characters.  I am sure this is because the people who upload the video decided this was a good idea.  If I access the video "normally", using a browser, it displays the truncated version of the description, with a "Show More" thingie to click.  When you click that, it shows you the full description.

What I would like is if there were a way, using youtube-dl, to get the full description into a file.

Note: I have looked in the json file manually and found that it (the Description field) is, indeed, truncated.  When I search in this file (the json file) for a word that I know is in the full description text (because I can see it in the browser, after clicking "Show More"), the word is not found.  So, I am confident that the full description is nowhere in the json file.  Is there somewhere else I need to look - or is there some other option to pass to youtube-dl, to get the full descrption?

**Comment by nastia-diaphan** [comment]
Already asked https://github.com/ytdl-org/youtube-dl/issues/25937

**Comment by joeschmoe40** [comment]
OK, thanks.  It turns out that the problem is not specific to the videos that I am talking about; it is a "YouTube thing", not a "Content Provider thing".

The obvious question becomes: When will the fix be available in the mainstream release?

I have downloaded the (fixed) version from "Random Bytes"; I may get around to playing with it at some point.
