### ISSUE TITLE
youtube - json "chapters" key value is NULL 

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#26005]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v --print-json https://www.youtube.com/watch?v=W-VInHvlrZo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--print-json', u'https://www.youtube.com/watch?v=W-VInHvlrZo']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Default format spec: best/bestvideo+bestaudio
{"upload_date": "20200714", "protocol": "https", "extractor": "youtube", "series": null, "format": "18 - 640x320 (360p)", "format_note": "360p", "chapters": null, "height": 320, "acodec": "mp4a.40.2", "like_count": null, "duration": 1138, "fulltitle": "OnePlus Nord Reveal! ...........
```

## Description

Hello guys.
Looks like extracting timestamps from youtube is broken for some reason... used to work just fine, however chapters in JSON output is currently - EMPTY. Running with Python 2.7. 
Links to try:
https://www.youtube.com/watch?v=W-VInHvlrZo
https://www.youtube.com/watch?v=GEZhD3J89ZE

**Comment by VolatileCable** [comment]
Also happens with latest master a115e07

**Comment by trialuser02** [comment]
I have same issue.

**Comment by David-Else** [comment]
Still happening with `2020.11.17`: youtube-dl --write-info-json https://www.youtube.com/watch?v=TQUy8ENesGY
```
"chapters": null
```

**Comment by someziggyman** [comment]
Thank you for you hard work! and welcome back!

Implemented your latest fix:
It fix works for https://www.youtube.com/watch?v=Q9yn1DpZkHQ

But these are still returning NULL chapters:
https://www.youtube.com/watch?v=W-VInHvlrZo
https://www.youtube.com/watch?v=GEZhD3J89ZE
https://www.youtube.com/watch?v=PSy62MExgQE
