### ISSUE TITLE
Dynamic output filename template

### ISSUE THREAD

**Issue by canlang** [ytdl-org/youtube-dl#26012]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

Currently, if the variable value of the output template does not exist, it is replaced with the **NA** value. Instead, it would be nice to have the ability to take additional candidate groups dynamically and first set the output template in the order of correspondence.

For example, the user sets multiple `-o` options in the config file and takes the setting that NA does not occur in the order listed.

**Comment by idan-tankel** [comment]
hey, I know that is really old, is there an option for that by now?

**Comment by canlang** [comment]
> hey, I know that is really old, is there an option for that by now?

Not exactly the same as what I said, but **yt-dlp** supports similar options
https://github.com/yt-dlp/yt-dlp#output-template-examples
