### ISSUE TITLE
ERROR: can't find the current version. Please try again later.

### ISSUE THREAD

**Issue by BangDroid** [ytdl-org/youtube-dl#26011]
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

PS C:\> youtube-dl -v --update
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--update']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1287, in connect
  File "C:\Python\Python34\lib\ssl.py", line 362, in wrap_socket
  File "C:\Python\Python34\lib\ssl.py", line 580, in __init__
  File "C:\Python\Python34\lib\ssl.py", line 807, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\update.py", line 46, in update_self
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\utils.py", line 2736, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>

ERROR: can't find the current version. Please try again later.

## Description
I had this same issue as this under 2020.05.29 and updated manually, the issue persists.
Same as https://github.com/ytdl-org/youtube-dl/issues/25541 but it's locked as _off topic_.

**Comment by SpiralBrad** [comment]
Getting the same error here, and it is NOT "off topic", ytdl-org.

#25541 provided the reason and correct fix; stop serving an expired cert.

**Comment by garoto** [comment]
On Windows, it shoulb be enough to navigate to https://yt-dl.org/ with Microsoft Edge/IE to Windows update its certificate storage. If it doesn't, then clicking on the padlock icon on the address bar, clicking "view certificate", exporting it and then importing the yt-dl.org cert should also work.

**Comment by fireattack** [comment]
> On Windows, it should be enough to navigate to https://yt-dl.org/ with Microsoft Edge/IE to Windows update its certificate storage. If it doesn't, then clicking on the padlock icon on the address bar, clicking "view certificate", exporting it and then importing the yt-dl.org cert should also work.

Tried this, doesn't work (I exported and imported the cert.)

**Comment by garoto** [comment]
It might be needed to click the link for the `youtube-dl.exe` binary as shown on the homepage and then simply canceling the download, since the Windows binary is hosted on Github infrasctructure, and an outdated Windows certificate storage won't have those either (certs for github.com & githubusercontent.com).

n.b.: Just tried these steps on a fresh Win7 VM yesterday, and it worked as described.

**Comment by fireattack** [comment]
Unfortunately, still doesn't work. 

Probably related: while the certificate for yt-dl.org is valid, when I click "issuer statement", it goes to https://secure.comodo.com/CPS, which shows `NET::ERR_CERT_COMMON_NAME_INVALID`.

**Comment by garoto** [comment]
> Unfortunately, still doesn't work.

Welp, too bad I guess. It worked on multiple bare-bones VMs I tested with. 

> when I click "issuer statement", it goes to https://secure.comodo.com/CPS, which shows NET::ERR_CERT_COMMON_NAME_INVALID

Most likely not related to the issue at hand, but welcome to the shitty certificates ecosystem, where not even a CA has a proper certificate setup for one of their legacy domains lol.

It's all thrash.

**Comment by fireattack** [comment]
Just checked your video. I use Win7 as well.

As you can see, I already have all the certificates in my system:

![image](https://user-images.githubusercontent.com/4130991/88753527-01f2bd00-d122-11ea-9b97-45fe5a74f9db.png)

Still shows error:

![image](https://user-images.githubusercontent.com/4130991/88753552-18991400-d122-11ea-82c2-20d1e9980c69.png)

**Comment by garoto** [comment]
Not sure if I can contribute anything more other than what I already wrote. I wish my simple method did work for you tho, but at this point I doubt there's even a single person left on Redmond who understands the awful "update CAs" mechanic on any Windows anymore.

**Comment by serge-sb** [comment]
This maybe because of the outdated python embedded. It is 3.4.4 in the windows exe-file. And it has an outdated openssl library. That's why the error. Embedded python for Windows version of youtube-dl needs to be updated.
