### ISSUE TITLE
hangs for awhile at "Downloading webpage", then downloads at slow rate

### ISSUE THREAD

**Issue by Geremia** [ytdl-org/youtube-dl#26038]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-warnings', '-if', 'bestvideo[height<=480]+bestaudio/best[height<=480]', '--write-sub', '--write-auto-sub', '--embed-subs', '--convert-subs', 'srt', '--sub-lang', 'en', '-v', 'http://www.randallterry.com/press.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Linux-5.4.42-x86_64
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[generic] press: Requesting header
[generic] press: Downloading webpage
[generic] press: Extracting information
[download] Downloading playlist: Media and Press
[generic] playlist Media and Press: Collected 3 video ids (downloading 3 of them)
[download] Downloading video 1 of 3
[youtube] hnGngDUb8P0: Downloading webpage
[download]  15.4% of ~125.56MiB at  3.07MiB/s ETA 07:24:35
```
It's been frozen at 15.4% for awhile, but it continues saying "3.07MiB/s ETA 07:24:35". The ETA seems not to be calculated correctly.

## Description

Recently, I've been having hangs or very long delays at "Downloading webpage" and, if it begins downloading, very slow download rates. I don't have any issues playing these videos on the YouTube website in a browser.

I also get the same issue with Vimeo, Bitchute, etc. Maybe a download rate / throttling issue?

Also, when I run youtube-dl through a SOCKS proxy with proxychains, I don't get this issue, so it seems to be a combo of a bug and my particular ISP?

**Comment by arun54321** [comment]
I have also noticed this since last week. It takes around 3-5 minutes to even list video formats.

**Comment by frrobert2** [comment]
I am having the same issue.
I have tried youtube-dl on two different machines one running Ubuntu 18.04 and another Ubuntu 20.04 same slow response.  Both are using the same external ip.
I tried another python based you-tube download program and had the same issue.
I tried a go based program and it worked fine.
I have AT&T Uverse dsl.

Takes 6m 34 seconds to get a url with the -g flag every time.  So I think somebody is throttling(you-tube or AT&T).  I am thinking the go program is just different enough that it is not causing the throttling to kick in.

Just a guess on my part.

**Comment by arun54321** [comment]
> I am having the same issue.
> I have tried youtube-dl on two different machines one running Ubuntu 18.04 and another Ubuntu 20.04 same slow response. Both are using the same external ip.
> I tried another python based you-tube download program and had the same issue.
> I tried a go based program and it worked fine.
> I have AT&T Uverse dsl.
> 
> Takes 6m 34 seconds to get a url with the -g flag every time. So I think somebody is throttling(you-tube or AT&T). I am thinking the go program is just different enough that it is not causing the throttling to kick in.
> 
> Just a guess on my part.

Try this flag. **--force-ipv4**

**Comment by frrobert2** [comment]
--force-ipv4 worked for me.

Thanks

**Comment by Geremia** [comment]
@frrobert2 Works for me, too.
I wonder why IPv6 causes issues?

**Comment by deepesh-agarwal** [comment]
@Geremia Were yo able to switch back to IPv6, also, can you pls share your approach to using IPv6 to prevent 429 errors with youtube.

**Comment by Mathnerd314** [comment]
I tried the webpage https://test-ipv6.com/, it showed that IPv6-only sites were timing out. After tweaking my modem/router settings I got the test working. Now youtube-dl seems fine.

Maybe there could be a FAQ entry:
```markdown

### Why are all my downloads taking a long time to start?

Your modem, router or ISP may have incorrect IPv6 settings. Try an IPv6 test site like https://test-ipv6.com/.
If you cannot configure IPv6 to work then you can use the option `--force-ipv4`.

```

**Comment by Geremia** [comment]
> @Geremia Were you able to switch back to IPv6, also, can you pls share your approach to using IPv6 to prevent 429 errors with youtube.

2020.09.20 works over IPv6 for me now.
