### ISSUE TITLE
South Park S23E10 first part corrupt

### ISSUE THREAD

**Issue by Craftmining** [ytdl-org/youtube-dl#26036]
I could not figure out how to make the output look correct in GitHub so i uploaded a text file too.

This is a bug report.

I have been having this issue for a while now and just haven't gotten around to reporting it. I just installed YTDL to test if it still has not been fixed yet so i am running the latest version

If i don't use FFMPEG i get 3 files. It is normal for South Park to be in 3-4 parts. The first being unreadable until like half way in and in wrong language. All the others are fine

If i use FFMPEG i get 2 files. Both called part 1 but one with .mp4 ext and one with .temp.mp4 ext. The temp one is unreadable but the other one is unreadable until like half way in and in wrong language

All other South Park episodes download without any issue. Its just the latest episode. 

Sorry if i did something wrong in this post. I never posted a issue before

[With FFMPEG.txt](https://github.com/ytdl-org/youtube-dl/files/4940265/With.FFMPEG.txt)
`C:\Users\username\Downloads>youtube-dl.exe --ffmpeg-location C:\ffmpeg\bin\ffmpeg.exe -v https://southpark.cc.com/full-episodes/s23e10
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', 'C:\\ffmpeg\\bin\\ffmpeg.exe', '-v', 'https://southpark.cc.com/full-episodes/s23e10']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-07-16-d11cc74, ffprobe git-2020-07-16-d11cc74
[debug] Proxy map: {}
[southpark.cc.com] s23e10: Downloading webpage
[southpark.cc.com] ac8dec94-b355-11e9-9fb2-70df2f866ace: Downloading info
[southpark.cc.com] 93bd9dcc-3e65-41ad-b8cd-e6a160733c2a: Extracting information
[southpark.cc.com] 93bd9dcc-3e65-41ad-b8cd-e6a160733c2a: Downloading video urls
[southpark.cc.com] 93bd9dcc-3e65-41ad-b8cd-e6a160733c2a: Downloading m3u8 information
[southpark.cc.com] 76a61caa-c43e-40d0-8c0d-0b624b90e0df: Extracting information
[southpark.cc.com] 76a61caa-c43e-40d0-8c0d-0b624b90e0df: Downloading video urls
[southpark.cc.com] 76a61caa-c43e-40d0-8c0d-0b624b90e0df: Downloading m3u8 information
[southpark.cc.com] 2dd86713-5670-4969-9047-972f490666e5: Extracting information
[southpark.cc.com] 2dd86713-5670-4969-9047-972f490666e5: Downloading video urls
[southpark.cc.com] 2dd86713-5670-4969-9047-972f490666e5: Downloading m3u8 information
[download] Downloading playlist: Christmas Snow
[southpark.cc.com] playlist Christmas Snow: Collected 3 video ids (downloading 3 of them)
[download] Downloading video 1 of 3
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://dlvrsvc.mtvnservices.com/api/playlist/gsp.comedystor/com/sp/season-23/2310/0/stream_1920x1080_3792260_3872990749.m3u8?tk=st=1595013586~exp=1595027986~acl=/api/playlist/gsp.comedystor/com/sp/season-23/2310/0/stream_1920x1080_3792260_3872990749.m3u8*~hmac=d53de214b6284bfe92079ea75e678c12a045530688247266a04b2829d33a199e&account=southparkstudios.com&cdn=level3'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 79
[download] Destination: South Park_December 11, 2019_23_2310_South Park 2310 - Christmas Snow - Act 1-93bd9dcc-3e65-41ad-b8cd-e6a160733c2a.mp4
[download] 100% of 220.51MiB in 00:27
[debug] ffmpeg command line: "C:\ffmpeg\bin\ffprobe" -show_streams "file:South Park_December 11, 2019_23_2310_South Park 2310 - Christmas Snow - Act 1-93bd9dcc-3e65-41ad-b8cd-e6a160733c2a.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "South Park_December 11, 2019_23_2310_South Park 2310 - Christmas Snow - Act 1-93bd9dcc-3e65-41ad-b8cd-e6a160733c2a.mp4"
[debug] ffmpeg command line: "C:\ffmpeg\bin\ffmpeg" -y -loglevel "repeat+info" -i "file:South Park_December 11, 2019_23_2310_South Park 2310 - Christmas Snow - Act 1-93bd9dcc-3e65-41ad-b8cd-e6a160733c2a.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:South Park_December 11, 2019_23_2310_South Park 2310 - Christmas Snow - Act 1-93bd9dcc-3e65-41ad-b8cd-e6a160733c2a.temp.mp4"
ERROR:   Stream #0:0 -> #0:0 (copy)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2065, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\postprocessor\ffmpeg.py", line 590, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\postprocessor\ffmpeg.py", line 239, in run_ffmpeg
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #0:0 -> #0:0 (copy)`

[Without FFMPEG.txt](https://github.com/ytdl-org/youtube-dl/files/4940306/Without.FFMPEG.txt)
`C:\Users\username\Downloads>youtube-dl.exe -v https://southpark.cc.com/full-episodes/s23e10
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://southpark.cc.com/full-episodes/s23e10']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[southpark.cc.com] s23e10: Downloading webpage
[southpark.cc.com] ac8dec94-b355-11e9-9fb2-70df2f866ace: Downloading info
[southpark.cc.com] 93bd9dcc-3e65-41ad-b8cd-e6a160733c2a: Extracting information
[southpark.cc.com] 93bd9dcc-3e65-41ad-b8cd-e6a160733c2a: Downloading video urls
[southpark.cc.com] 93bd9dcc-3e65-41ad-b8cd-e6a160733c2a: Downloading m3u8 information
[southpark.cc.com] 76a61caa-c43e-40d0-8c0d-0b624b90e0df: Extracting information
[southpark.cc.com] 76a61caa-c43e-40d0-8c0d-0b624b90e0df: Downloading video urls
[southpark.cc.com] 76a61caa-c43e-40d0-8c0d-0b624b90e0df: Downloading m3u8 information
[southpark.cc.com] 2dd86713-5670-4969-9047-972f490666e5: Extracting information
[southpark.cc.com] 2dd86713-5670-4969-9047-972f490666e5: Downloading video urls
[southpark.cc.com] 2dd86713-5670-4969-9047-972f490666e5: Downloading m3u8 information
[download] Downloading playlist: Christmas Snow
[southpark.cc.com] playlist Christmas Snow: Collected 3 video ids (downloading 3 of them)
[download] Downloading video 1 of 3
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://dlvrsvc.mtvnservices.com/api/playlist/gsp.comedystor/com/sp/season-23/2310/0/stream_1920x1080_3792260_3872990749.m3u8?tk=st=1595013586~exp=1595027986~acl=/api/playlist/gsp.comedystor/com/sp/season-23/2310/0/stream_1920x1080_3792260_3872990749.m3u8*~hmac=d53de214b6284bfe92079ea75e678c12a045530688247266a04b2829d33a199e&account=southparkstudios.com&cdn=level3'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 79
[download] Destination: South Park_December 11, 2019_23_2310_South Park 2310 - Christmas Snow - Act 1-93bd9dcc-3e65-41ad-b8cd-e6a160733c2a.mp4
[download] 100% of 220.51MiB in 00:32
WARNING: 93bd9dcc-3e65-41ad-b8cd-e6a160733c2a: malformed AAC bitstream detected. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 2 of 3
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://dlvrsvc.mtvnservices.com/api/playlist/gsp.comedystor/com/sp/season-23/2310/acts/0/stream_1920x1080_2389015_2149461872.m3u8?tk=st=1595018899~exp=1595033299~acl=/api/playlist/gsp.comedystor/com/sp/season-23/2310/acts/0/stream_1920x1080_2389015_2149461872.m3u8*~hmac=84fc1cc214de3ac4d87009ce982361390aecc134fd8b5d13e34286cafd77b81d&account=southparkstudios.com&cdn=level3'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 55
[download] Destination: South Park_December 11, 2019_23_2310_South Park 2310 - Christmas Snow - Act 2-76a61caa-c43e-40d0-8c0d-0b624b90e0df.mp4
[download] 100% of 107.13MiB in 00:16
WARNING: 76a61caa-c43e-40d0-8c0d-0b624b90e0df: malformed AAC bitstream detected. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 3 of 3
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://dlvrsvc.mtvnservices.com/api/playlist/gsp.comedystor/com/sp/season-23/2310/acts/0/stream_1920x1080_2402868_1617085905.m3u8?tk=st=1595017047~exp=1595031447~acl=/api/playlist/gsp.comedystor/com/sp/season-23/2310/acts/0/stream_1920x1080_2402868_1617085905.m3u8*~hmac=3b0164b1161491e56dd25f79c403498592dd15c5e96b1ed654ac194d25216e5e&account=southparkstudios.com&cdn=level3'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 62
[download] Destination: South Park_December 11, 2019_23_2310_South Park 2310 - Christmas Snow - Act 3-2dd86713-5670-4969-9047-972f490666e5.mp4
[download] 100% of 119.90MiB in 00:18
WARNING: 2dd86713-5670-4969-9047-972f490666e5: malformed AAC bitstream detected. Install ffmpeg or avconv to fix this automatically.
[download] Finished downloading playlist: Christmas Snow`

**Comment by dstftw** [comment]
No longer available.
