### ISSUE TITLE
PBS NOVA series ERROR: No video formats found

### ISSUE THREAD

**Issue by PacoH** [ytdl-org/youtube-dl#26049]
- [ X ] I'm reporting a broken site support
- [ X ] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ X ] I've checked that all provided URLs are alive and playable in a browser
- [ X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.pbs.org/wgbh/nova/video/molecule-made-us-pulse/']
[debug] Encodings: locale UTF-8, fs utf-8, out None, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.17 (CPython) - Darwin-12.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 6.203.166.210 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] molecule-made-us-pulse: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 661, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

WRITE DESCRIPTION HERE

Normal NOVA site––https://www.pbs.org/show/nova/episodes/season/47/––works. This special NOVA series––https://www.pbs.org/wgbh/nova/series/molecule-made-us/episodes/––does not work.

**Comment by PacoH** [comment]
- [ X ] I'm reporting a broken site support
- [ X ] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ X ] I've checked that all provided URLs are alive and playable in a browser
- [ X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X ] I've searched the bugtracker for similar issues including closed ones


## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.pbs.org/wgbh/nova/video/molecule-made-us-pulse/']
[debug] Encodings: locale UTF-8, fs utf-8, out None, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.17 (CPython) - Darwin-12.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 6.203.166.210 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] molecule-made-us-pulse: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 661, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

WRITE DESCRIPTION HERE

Normal NOVA site https://www.pbs.org/show/nova/episodes/season/47/ works. This special NOVA series https://www.pbs.org/wgbh/nova/series/molecule-made-us/episodes/ does not work.

**Comment by rfugina** [comment]
A couple other examples that demonstrate the error:

https://www.pbs.org/wgbh/nova/video/making-north-america-origins/
https://www.pbs.org/wgbh/nova/video/making-north-america-life/
https://www.pbs.org/wgbh/nova/video/making-north-america-human/

**Comment by PacoH** [comment]
At least the video plays in the browser, but I couldn't download it. The ones I cited can't be played at all. "This video is only available in ArizonaPBS Passport."

**Comment by PacoH** [comment]
OK. Try this:

[NOVA: Season 42 Episodes | PBS](https://www.pbs.org/show/nova/episodes/season/42/)

**Comment by PacoH** [comment]
OK. Solved it. You need to go to the main site [Public Broadcasting Service](https://www.pbs.org/) and search for the series and narrow it down by video length (30-60 min). Then the links are valid. 

[The Molecule That Made Us](https://www.pbs.org/search/?q=The+Molecule+That+Made+Us)

**Comment by EvilHidden** [comment]
I tried this for American Experience and I still get the same error.

**Comment by PacoH** [comment]
The bottom line is you have to go to the main PBS site I linked to above and search for the program you want and go to the Episodes page. The local PBS stations pages want your money so don't provide links to the actual videos. Try [American Experience \| PBS](https://www.pbs.org/show/american-experience/episodes/)
