### ISSUE TITLE
tell youtube-dl to use one format( -f 18 ) if another isnt available( -f 22)?

### ISSUE THREAD

**Issue by frddbbbl** [ytdl-org/youtube-dl#26045]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hi i use youtube-dl with mplayer through a binding to download videos from my browser and rss feed. i use the following command: `mplayer -fs $(youtube-dl -g -f 22 URL)` sometimes -f 22 isnt available and i need to use-f 18 instead as this is almost a universal standard for youtube videos. Is it possible to tell youtube-dl to use one format if the other is not available?

**Comment by 0x9fff00** [comment]
Use `-f 22/18`, or `-f best` to download the highest-bitrate format with both video and audio.
