### ISSUE TITLE
Unsupported URL at oe1.orf.at

### ISSUE THREAD

**Issue by sobotkac** [ytdl-org/youtube-dl#26043]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v 'https://oe1.orf.at/artikel/444507/Der-Fall-Moritz-Schlick'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://oe1.orf.at/artikel/444507/Der-Fall-Moritz-Schlick']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-9-686-pae-i686-with-debian-10.4
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[generic] Der-Fall-Moritz-Schlick: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Der-Fall-Moritz-Schlick: Downloading webpage
[generic] Der-Fall-Moritz-Schlick: Extracting information
ERROR: Unsupported URL: https://oe1.orf.at/artikel/444507/Der-Fall-Moritz-Schlick
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2387, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: mismatched tag: line 57, column 4
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://oe1.orf.at/artikel/444507/Der-Fall-Moritz-Schlick
```

## Description

"https://oe1.orf.at/player..."  --> these URLs work fine
"https://oe1.orf.at/artikel..."  --> return UnsupportedError (tried some of these)

**Comment by sobotkac** [comment]
The source of the page (https://oe1.orf.at/artikel/444507/Der-Fall-Moritz-Schlick) contains a link to the data and says autoplay=false. Downloading the data-url works fine. Is it possible to adapt youtube-dl to download directly without looking into to source of the page?

Part of the source:

...
  | <div class="audioContainer">
  |  
  |  
  | <div class="oon-audio"
  | data-url="https://apasfftp1.sf.apa.at/oe1/internat/0001D050.MP3"
  | data-autoplay="false"
  | data-width="100%"
  |  
  | ></div>
  |  
  |  
  |  
  |  
  |  
  | </div>
...

**Comment by jkirk** [comment]
JFTR: the https://oe1.orf.at/artikel... URLs come from here: https://oe1.orf.at/archiv. I also think it would be very useful to have youtube-dl support these kind of links.

The same goes for https://radiothek.orf.at/. These URLs are also not supported.
E.g. https://oe1.orf.at/player/20210415/635229 works but https://radiothek.orf.at/oe1/20210415/635229 does not. Also https://radiothek.orf.at/oe1/highlights/124047 + https://oe1.orf.at/programm/20210415/635229/Gesund-bis-ins-hohe-Alter have the same content but do not work.

**Comment by dirkf** [comment]
Superseded by #29394.
