### ISSUE TITLE
SSL certificate problem at https://yt-dl.org/

### ISSUE THREAD

**Issue by Janattar** [ytdl-org/youtube-dl#26052]
## Checklist

- [x] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

When I try to update, I get this:
"sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
Password:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
janattar@Jans-iMac ~ % 
"

**Comment by bersbersbers** [comment]
Works fine for me, check your `curl`'s certificate store.

```
C:\Users\bers\AppData\Local\Temp>curl -L https://yt-dl.org/downloads/latest/youtube-dl -o Temp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     3    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     3    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100   619  100   619    0     0    309      0  0:00:02  0:00:02 --:--:--  1366
100 1715k  100 1715k    0     0   245k      0  0:00:07  0:00:07 --:--:--  448k
```
