### ISSUE TITLE
WARNING: Unable to look up account info: HTTP Error 404: Not Found on YouTube

### ISSUE THREAD

**Issue by UnforeseenOcean** [ytdl-org/youtube-dl#26067]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[07/20/20 17:15:01] [debug] System config: []
[07/20/20 17:15:01] [debug] User config: []
[07/20/20 17:15:01] [debug] Custom config: []
[07/20/20 17:15:01] [debug] Command-line args: ['--newline', '-u', 'PRIVATE', '-p', 'PRIVATE', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0', '--all-subs', '-o', 'E:\\Videos\\%(uploader)s\\%(title)s-%(resolution)s-%(id)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', '--add-metadata', '-v', 'https://www.youtube.com/watch?v=exUnB1iGdME']
[07/20/20 17:15:01] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[07/20/20 17:15:01] [debug] youtube-dl version 2020.06.16.1
[07/20/20 17:15:01] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[07/20/20 17:15:01] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[07/20/20 17:15:01] [debug] Proxy map: {}
[07/20/20 17:15:01] WARNING: Unable to look up account info: HTTP Error 404: Not Found
[07/20/20 17:15:01] ERROR: exUnB1iGdME: YouTube said: Unable to extract video data
[07/20/20 17:15:01] Traceback (most recent call last):
[07/20/20 17:15:01]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
[07/20/20 17:15:01]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 530, in extract
[07/20/20 17:15:01]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\youtube.py", line 1893, in _real_extract
[07/20/20 17:15:01] youtube_dl.utils.ExtractorError: exUnB1iGdME: YouTube said: Unable to extract video data
[07/20/20 17:15:01] 
```

## Description

This issue occurs on age-restricted videos (in Korea you need to verify your age before you can watch these videos).
I did confirm that I *can* log into the account using those credentials I provided, and the videos are indeed watchable (after verifying the age), but it doesn't work on youtube-dl. What I'm confused about is that this issue didn't appear before YouTube silently updated their system and that it says 404 Not Found instead of something like 400 Bad Request or 403 Forbidden. If you need help verifying the issue, let me know and I will do so.

**Comment by arisboch** [comment]
Can confirm that (wanted to download age-restricted Youtube Poop from Germany and was greeted with a 404).

**Comment by arisboch** [comment]
Exporting cookies doesn't do anything, either. JDownloader works, though.

**Comment by Dimitrivolkov** [comment]
I'm having this problem as well. I've also noticed I'm having issues signing into google from my mobile device entirely. Almost every browser I use, except for a select few, do not allow me to sign in when using the desktop user agent. I am met with the message -

 "This browser or app may not be secure. Learn more

Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in."

This is not specific to my account. It occurs anytime I attempt to sign in regardless of the credentials. This even occurs on chrome browser. Switching to the mobile site seems to resolve this most of the time. Though I've tried signing in with youtube-dl using various mobile user agents, and none have worked. Can someone please chime in?

**Comment by phyr** [comment]
Getting the same warning when trying to download my Youtube watch history (which most probably contains a few age-restriced videos). 

On a side note, when I try to download the YT history data via Google Takeout, I get an empty export. Perhaps the same or a related problem?

**Comment by ginaahong** [comment]
Can confirm I am getting the same warning. Specifying cookies nor switching user agents didn't fix the issue for me either.

**Comment by dardo82** [comment]
**#metoo**
```$ youtube-dl -v -u $USER@gmail.com :ythistory
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', ':ythistory']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.7.8 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube:history] Downloading login page
[youtube:history] Looking up account info
WARNING: Unable to look up account info: HTTP Error 404: Not Found
[youtube:history] Youtube History: Downloading webpage
[download] Downloading playlist: Youtube History
[youtube:history] playlist Youtube History: Downloading 0 videos
[download] Finished downloading playlist: Youtube History
```

**Comment by dardo82** [comment]
@remitamine duplicate of what?

**Comment by celloh123** [comment]
duplicate of what? seriously

**Comment by UnforeseenOcean** [comment]
According to git issue search, this is not a duplicate. Please re-open the issue. (other issues are referring to 403 error caused by outdated code, this is something else entirely)

**Comment by michealespinola** [comment]
This is not the same issue and is unique.  This can be confirmed by trying to use -u -p or .netrc to authenticate to any Google service currently.

**Comment by garoto** [comment]
[**@UnforeseenOcean**]
```
> youtube-dl.exe --cookies C:\Users\<redacted>\backup_cookies_all_20200709153303.txt https://www.youtube.com/watch?v=exUnB1iGdME
[youtube] exUnB1iGdME: Downloading webpage
[youtube] exUnB1iGdME: Downloading MPD manifest
[dashsegments] Total fragments: 14
[download] Destination: OWL-GGuppy-exUnB1iGdME.f302.webm
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10)...
[download] 100% of 8.54MiB in 00:20
[dashsegments] Total fragments: 8
[download] Destination: OWL-GGuppy-exUnB1iGdME.f251.webm
[download] 100% of 1.04MiB in 00:03
[ffmpeg] Merging formats into "OWL-GGuppy-exUnB1iGdME.mkv"
ERROR: Conversion failed!
[ffmpeg] There aren't any subtitles to convert
[ffmpeg] There aren't any subtitles to embed
```
[**@dardo82**](https://github.com/dardo82)
```
> youtube-dl.exe --cookies C:\Users\<redacted>\backup_cookies_all_20200709153303.txt :ythistory
[youtube:history] Youtube History: Downloading webpage
[download] Downloading playlist: Youtube History
[youtube:history] Youtube History: Downloading page #1
[youtube:history] Youtube History: Downloading page #2
[youtube:history] Youtube History: Downloading page #3
[youtube:history] Youtube History: Downloading page #4
[youtube:history] Youtube History: Downloading page #5
[youtube:history] Youtube History: Downloading page #6
[youtube:history] Youtube History: Downloading page #7
[youtube:history] Youtube History: Downloading page #8
[youtube:history] Youtube History: Downloading page #9
[youtube:history] Youtube History: Downloading page #10
[youtube:history] Youtube History: Downloading page #11
[youtube:history] Youtube History: Downloading page #12
[youtube:history] playlist Youtube History: Downloading 1698 videos
[download] Downloading video 1 of 1698
[youtube] PDTCgxvmShc: Downloading webpage
[download] Destination: The_Easy_Guide_On_Seasoning_and_Restoring_Cast_Iron-Joshua_Weissman-PDTCgxvmShc.f303.webm
[download] 100% of 158.03MiB in 00:06
[download] Destination: The_Easy_Guide_On_Seasoning_and_Restoring_Cast_Iron-Joshua_Weissman-PDTCgxvmShc.f251.webm
[download] 100% of 6.35MiB in 00:00
[ffmpeg] Merging formats into "The_Easy_Guide_On_Seasoning_and_Restoring_Cast_Iron-Joshua_Weissman-PDTCgxvmShc.mkv"
Deleting original file The_Easy_Guide_On_Seasoning_and_Restoring_Cast_Iron-Joshua_Weissman-PDTCgxvmShc.f303.webm (pass -k to keep)
Deleting original file The_Easy_Guide_On_Seasoning_and_Restoring_Cast_Iron-Joshua_Weissman-PDTCgxvmShc.f251.webm (pass -k to keep)
[ffmpeg] There aren't any subtitles to convert
[ffmpeg] There aren't any subtitles to embed
[download] Downloading video 2 of 1698
[youtube] ey_NEoM2SpM: Downloading webpage

ERROR: Interrupted by user
```

**Comment by dardo82** [comment]
@garoto so it works with cookies?
How did you save them? Explain...

**Comment by michealespinola** [comment]
@dardo82 cookies to not work for \*this\* issue.

**Comment by dardo82** [comment]
> @dardo82 cookies do not work for *this* issue...
@michealespinola *Why* are you telling it to *me*?

**Comment by michealespinola** [comment]
@dardo82 it looked like you were asking a question.

**Comment by dardo82** [comment]
> @dardo82 it looked like you were asking a question.

@michealespinola  I wasn't asking you...

**Comment by michealespinola** [comment]
@dardo82 if this is the type of person you wish to be, then so be it.

**Comment by dardo82** [comment]
> @dardo82 if this is the type of person you wish to be, then so be it.

@michealspinola what is wrong with you?

**Comment by Dimitrivolkov** [comment]
Is this going to be reopened or what?

**Comment by celloh123** [comment]
I'm having the same issue but I'm trying to download youtube music premium songs

**Comment by z0z0z** [comment]
For anyone new here, this guy closes countless issues as duplicates without any duplicate issue actually existing.

He will refuse to link the so-called duplicate issue or speak.

That's just how this bug tracker goes.

**Comment by michealespinola** [comment]
> @michealspinola what is wrong with you?

I tried to offer some assistance, and you are being unnecessarily confrontational about it.  I don't understand what your problem is.  If the information I offered was not of help to you, then just move on.  But I'm not going to be badgered for trying to offer information to you.

**Comment by michealespinola** [comment]
> That's just how this bug tracker goes.

That's good to know moving forward, @z0z0z. Do you know if there is a listed project hierarchy or something to indicate who has scope of authority for this project?

**Comment by z0z0z** [comment]
`youtube-dl --user-agent="Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"`

Just run youtube-dl with this user-agent to download age restricted videos now.

Anyway I don't even know if this is a duplicate, I just know he has closes several hundred legitimate new issues as "duplicate" where no duplicate actually exists.

Guy is schizophrenic and gone crazy from moderating this bug tracker basically.

**Comment by dardo82** [comment]
Seems like he isn't the only one with problems here...

**Comment by UnforeseenOcean** [comment]
> `youtube-dl --user-agent="Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"`
> 
> Just run youtube-dl with this user-agent to download age restricted videos now.

That doesn't seem to be working well.
![IMG1595908076](https://user-images.githubusercontent.com/11834016/88617045-a64c1380-d0d0-11ea-864f-648f80e41bb2.png)

**Comment by dardo82** [comment]
### WTF?

**Comment by michealespinola** [comment]
@dardo82, for someone that is a "Social Media Manager", you have poor social skills.

**Comment by phyr** [comment]
Can we keep this on topic, please? Thanks.

@z0z0z Adding the user-agent isn't working for me. Still getting the 404 error.

**Comment by phyr** [comment]
Just wondering, is there a way to have youtube-dl skip age-restricted videos?

**Comment by UnforeseenOcean** [comment]
Yeah, I wonder about that too. Maybe it can see the metadata and find out if the video has a tag that says "Age-restricted video"?

Oh also it turns out the config was somehow corrupted and it was trying to log into an account ` [@2.c` (invalid address) with a password of ` ` (nothing). I rewrote my creds and it works fine. The login still fails with `404 Not Found`.

**Comment by buzz3rs** [comment]
> Can we keep this on topic, please? Thanks.
> 
> @z0z0z Adding the user-agent isn't working for me. Still getting the 404 error.

Hello, i have just tried the user-agent flag and it worked perfectly ( without logining or anything)
` youtube-dl --get-format https://youtube.com/watch?v=j8ZF_R_j0OY

ERROR: j8ZF_R_j0OY: YouTube said: Unable to extract video data`
**After adding the flag :**

`youtube-dl --user-agent="Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" --get-format https://youtube.com/watch?v=j8ZF_R_j0OY
136 - 1280x720 (720p)+251 - audio only (tiny)`

**Comment by dardo82** [comment]
> @dardo82, for someone that is a "Social Media Manager", you have poor social skills.

Why do you care about my job titles?
Do you want to hire me?
