### ISSUE TITLE
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### ISSUE THREAD

**Issue by jgrosmann** [ytdl-org/youtube-dl#26075]
https://www.youtube.com/watch?v=F7IHPbH0wiY

**Comment by stargazer39** [comment]
Hey there is formats and I can download it
[youtube] F7IHPbH0wiY: Downloading webpage
[info] Available formats for F7IHPbH0wiY:
format code  extension  resolution note
249          webm       audio only tiny   59k , opus @ 50k (48000Hz), 302.38KiB
250          webm       audio only tiny   74k , opus @ 70k (48000Hz), 378.80KiB
140          m4a        audio only tiny  130k , m4a_dash container, mp4a.40.2@128k (44100Hz), 748.95KiB
251          webm       audio only tiny  143k , opus @160k (48000Hz), 704.07KiB
160          mp4        66x144     144p   72k , avc1.4d500b, 29fps, video only, 237.53KiB
278          webm       118x256    144p   80k , webm container, vp9, 29fps, video only, 416.13KiB
133          mp4        110x240    144p  129k , avc1.4d400c, 29fps, video only, 436.66KiB
242          webm       196x426    240p  180k , vp9, 29fps, video only, 742.71KiB
134          mp4        166x360    240p  234k , avc1.4d400d, 29fps, video only, 779.48KiB
243          webm       296x640    360p  331k , vp9, 29fps, video only, 1.16MiB
135          mp4        222x480    240p  468k , avc1.4d4015, 29fps, video only, 1.08MiB
244          webm       394x854    480p  603k , vp9, 29fps, video only, 1.82MiB
298          mp4        332x720    360p60  713k , avc1.4d401f, 59fps, video only, 1.84MiB
136          mp4        332x720    360p  798k , avc1.4d401e, 29fps, video only, 2.37MiB
137          mp4        500x1080   480p 1235k , avc1.64001f, 29fps, video only, 3.79MiB
247          webm       592x1280   720p 1244k , vp9, 29fps, video only, 4.32MiB
299          mp4        500x1080   480p60 1245k , avc1.640020, 59fps, video only, 3.98MiB
302          webm       592x1280   720p60 1322k , vp9, 59fps, video only, 3.78MiB
18           mp4        166x360    240p  362k , avc1.42001E, 29fps, mp4a.40.2@ 96k (44100Hz), 2.04MiB
22           mp4        332x720    360p  550k , avc1.64001F, 29fps, mp4a.40.2@192k (44100Hz) (best)

[youtube] F7IHPbH0wiY: Downloading webpage
[download] Destination: Prinses Alexia van Oranje TikToks _ TikTok Compilatie 2020-F7IHPbH0wiY.mp4
[download]  16.1% of 3.10MiB at 813.09KiB/s ETA 00:03
ERROR: Interrupted by user

**Comment by stargazer39** [comment]
btw.. You have to post the verbose log.. Its a guideline

**Comment by gravity-00** [comment]
I hope this verbose log helps to answer the issue:
**my version is: youtube-dl-2020-7.28**

youtube-dl --extract-audio --verbose https://www.youtube.com/watch?some-song-link
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--extract-audio', '--verbose', 'https://www.youtube.com/watch?v=EbcdDXEPukk']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.3 (CPython) - Linux-5.4.52-1-MANJARO-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] EbcdDXEPukk: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/s/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/s/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/s/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2364, in _real_extract
    self._sort_formats(formats)
  File "/home/s/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by pyaesone1996** [comment]
> https://www.youtube.com/watch?v=F7IHPbH0wiY

fake link
