### ISSUE TITLE
Youtube description is limited by 158 symbols only?

### ISSUE THREAD

**Issue by ComradeSerg** [ytdl-org/youtube-dl#26081]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

youtube # youtube-dl  -i --get-description --skip-download --verbose  "https://www.youtube.com/watch?v=qEJwO7EsgVk"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-i', '--get-description', '--skip-download', '--verbose', 'https://www.youtube.com/watch?v=qEJwO7EsgVk']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.7.8 (CPython) - FreeBSD-12.1-RELEASE-arm64-aarch64-64bit-ELF
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
Лекции-экскурсии Егора Яковлева ✅18 июля, суббота 12:00 — «Петровский Петербург» https://vk.com/event197077915 13:30 — «Дворцы Петербурга» https://vk.com/eve...

## Description

It seems youtube description is limited by 158 symbols in youtube-dl. I tried many videos on youtube and always getting no more 158 symbols followed by three dots. I tried "--write-description", "--write-info-json", "--get-description" with the same result. How I can download complete description?

Regards,
Serg.

**Comment by tahirjalilov** [comment]
Hello, I've reproduced and got a full description. Maybe it depends on your terminal configuration?

youtube_dl -i --get-description --skip-download --verbose "https://www.youtube.com/watch?v=qEJwO7EsgVk" 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-i', '--get-description', '--skip-download', '--verbose', 'https://www.youtube.com/watch?v=qEJwO7EsgVk']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Git HEAD: a115e0759
[debug] Python version 3.8.3 (CPython) - Linux-5.7.9-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
Лекции-экскурсии Егора Яковлева 

✅18 июля, суббота
12:00 — «Петровский Петербург» https://vk.com/event197077915
13:30 — «Дворцы Петербурга» https://vk.com/event197078152
15:00 — «Пять оборон города на Неве» https://vk.com/event197078257
16:30 — «Революционный Петроград» https://vk.com/event197078370

✅19 июля, воскресенье
13:00 — «Дворцы Петербурга» https://vk.com/event197078475
15:00 — «Мистический Петербург» https://vk.com/event197078561
16:30 — «Петербург Великих людей» https://vk.com/event197078645
18:00 — «Революционный Петроград» https://vk.com/event197078761

ЧАС ПРЕЗРЕНИЯ: ТЕРРОРИСТИЧЕСКАЯ КАТАСТРОФА В БУДЁННОВСКЕ - https://warhead.su/2020/06/18/chas-prezreniya-terroristicheskaya-katastrofa-v-budyonnovske

Научный редактор портала Warhead.su Евгений Норин и историк Егор Яковлев обсудили события недавней истории — теракт в Будённовске летом 1995 года. Тогда террористы во главе с Шамилем Басаевым напали на российский город в Ставропольском крае, где заняли больницу. В результате вооружённого захвата заложников погибли более сотни человек

**Comment by ComradeSerg** [comment]
You are probably right. I didn't sorted out yet, but because you can't reproduce issue on Linux, I think there is some specific FreeBSD settings. Will dig in this direction.  Thanks for help.

**Comment by liran** [comment]
I don't think it's the terminal display, it's more like a bug.

![image](https://user-images.githubusercontent.com/22112008/88464885-e2c11900-cef0-11ea-9ea1-2d8561c80bd4.png)

![image](https://user-images.githubusercontent.com/22112008/88464865-b3121100-cef0-11ea-85b4-216fa7bcdbb4.png)

![image](https://user-images.githubusercontent.com/22112008/88464744-d092ab00-ceef-11ea-989f-1c3c1cff7375.png)

**Comment by ComradeSerg** [comment]
Thanks Liran, found this bug too later. It seems in new version will be fixed.
