### ISSUE TITLE
How do I download just the webm's from a playlist?

### ISSUE THREAD

**Issue by tripleo1** [ytdl-org/youtube-dl#26088]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How do I download just the webm's from a playlist? vlc plays webm's just fine and I am using too much download bandwith.

**Comment by Battleman** [comment]
Hi. Your question is a bit unclear. Here is my guess, let me know if that is correct:
* You are using Youtube
* You have a playlist (`https://www.youtube.com/playlist?list=...`)
* You want to download only the audio ..
* .. of all the videos in the playlist

if that's the case, first you should check what formats are available on those videos. For that:`youtub-dl` -F https://your-url-here`

It will list all format available for each video. Then, select the one that fits you (I would guess `251`, that is webm audio only or correct quality), and input `youtube-dl -f 251 https://your-url-here`. Note the lowercase _f_, compared to the uppercase from before.

Obviously, replace 251 by any other number that matches your wish, from the list that was outputed by the first command.

Hope that helps. LMK if I misunderstood your question.

**Comment by tripleo1** [comment]
I want to download a playlist in the background (it is quite large), and
only in a format which doesn't have to be recombined.  I think vlc plays
webm's just fine. So -F (assuming it works) would prompt me on every video.

**Comment by remitamine** [comment]
read https://github.com/ytdl-org/youtube-dl#format-selection.

**Comment by tripleo1** [comment]
So -f 'best[ext=webm]' ??
