### ISSUE TITLE
Add speed indicator option

### ISSUE THREAD

**Issue by Aphexus** [ytdl-org/youtube-dl#26085]
Could you add a simple speed indicator option that would give the current download speed? I seem to be downloading from youtube quite slowly but I have no idea how slow(I guess I could use an external app). Should be easy to add though and could be an option:

[DL:1MB/s]

Then when it is done it erases the line for the next download(so scrolling does not take place, I don't need to log it, just to get some idea]

Similarly could add more verbose options. While I see there is suppose to be an option to print download information I don't actually get any. In fact, I would like to output the url link too, specially when there is an error so I can log it and figure out what is going on.

The command line I use is:

youtube-dl" -q -f 137+251/137+140/137+250/248+249/248+251/248+140/248+250/248+249/136+251/136+140/136+250/136+249/247+251/247+140/247+250/247+249/135+251/135+140/135+250/135+249/244+251/244+140/244+250/244+249/best+best --merge-output-format mkv --ignore-errors --no-check-certificate --sleep-interval 2 -a ..."

ERROR: DrSsYv6fZ80: YouTube said: Unable to extract video data
ERROR: unable to download video data: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
WARNING: Unable to remove downloaded original file
ERROR: giving up after 10 retries
ERROR: unable to download video data: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
ERROR: giving up after 10 retries
ERROR: giving up after 10 retries
ERROR: giving up after 10 retries
ERROR: giving up after 10 retries
WARNING: [youtube] 5yM9sd5nxsU: Skipping DASH manifest: ExtractorError('Failed to download MPD manifest: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
ERROR: giving up after 10 retries
ERROR: giving up after 10 retries
ERROR: giving up after 10 retries
ERROR: giving up after 10 retries
ERROR: giving up after 10 retries
ERROR: giving up after 10 retries
ERROR: giving up after 10 retries
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file
WARNING: Unable to remove downloaded original file

**Comment by Battleman** [comment]
Hey. I'm not a contributor, but it seems the command you are using involves the `-q` flag, that suppresses output. If you remove it, does it do what you want?
