### ISSUE TITLE
ERROR: No video formats found (Youtube)

### ISSUE THREAD

**Issue by Aranjedeath** [ytdl-org/youtube-dl#26090]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=-S-CwVJxxug', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Linux-5.4.0-42-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] -S-CwVJxxug: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 2364, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

This is the version that ships in Ubuntu 20.04 currently.

**Comment by Battleman** [comment]
You are not using the latest version (2020.06.16.1). By experience, the version of YTDL that ships with packages managers like APT (Debian, Ubuntu,..) tend to have a lag of a few versions. Obviously, Ubuntu wants to pass any new versions of packages through a battery of tests to ensure it doesn't break or conflicts with other packages. This is usually fine, but YTDL is a highly versatile program, that constantly evolves to adapt to the latest changes of Youtube (and others). 

I tried downloading your video with v2020.06.16.1 (latest version), and it works well. I would suggest using the standalone implementation rather that the one shipping with Ubuntu. See [their website](https://ytdl-org.github.io/youtube-dl/download.html) for howto.

I agree this is not "ideal", as I myself prefer to have everything managed by APT, but in this case it's more on the Canonical's side. Can't blame it on either side.

Hope that helps.

**Comment by Aranjedeath** [comment]
Hi, thanks for your note. 

I will manually download and use it for this one video then (works for all others I have tried).

Is there a process for getting Ubuntu to update their copy? I would obviously prefer a deb, if not something directly out of apt sources.

**Comment by Battleman** [comment]
AFAIK, no, there is not. Personally, I have downloaded the executable as they instruct, and then have a crontab that updates it daily.
The main problem here is that Ubuntu have their hands tied, they can't just roll out new versions of certain packages without passing it through a testing workflow.
