### ISSUE TITLE
TikTok unsupported URL

### ISSUE THREAD

**Issue by filixm** [ytdl-org/youtube-dl#26094]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
C:\YouTubeDl>youtube-dl.exe https://www.tiktok.com/@mattzworld/video/6831372615160958213 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.tiktok.com/@mattzworld/video/6831372615160958213', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 6831372615160958213: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6831372615160958213: Downloading webpage
[generic] 6831372615160958213: Extracting information
ERROR: Unsupported URL: https://www.tiktok.com/@mattzworld/video/6831372615160958213
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.tiktok.com/@mattzworld/video/6831372615160958213
```

## Description

Trying to get TikTok video, but getting and error 
https://www.tiktok.com/@mattzworld/video/6831372615160958213

**Comment by bpenven** [comment]
Same, was working yesterday:

```
c:\yt>youtube-dl.exe --verbose https://www.tiktok.com/@scottyhubs/video/6841942942945414405
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--verbose', 'https://www.tiktok.com/@scottyhubs/video/6841942942945414405']
> [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
> [debug] youtube-dl version 2020.06.16.1
> [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
> [debug] exe versions: none
> [debug] Proxy map: {}
> [generic] 6841942942945414405: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] 6841942942945414405: Downloading webpage
> [generic] 6841942942945414405: Extracting information
> ERROR: Unsupported URL: https://www.tiktok.com/@scottyhubs/video/6841942942945414405
> Traceback (most recent call last):
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 530, in extract
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
> youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.tiktok.com/@scottyhubs/video/6841942942945414405
```

**Comment by TonyStark** [comment]
+1
cant download

**Comment by lijemutu** [comment]
Same here
`[generic] 6850602336549735685?lang=es: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6850602336549735685?lang=es: Downloading webpage
[generic] 6850602336549735685?lang=es: Extracting information
ERROR: Unsupported URL: https://www.tiktok.com/@alevvla/video/6850602336549735685?lang=es
Traceback (most recent call last):
  File "C:\Users\Erick\projects\tiktokVideoGenerator\tiktok\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Erick\projects\tiktokVideoGenerator\tiktok\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Erick\projects\tiktokVideoGenerator\tiktok\lib\site-packages\youtube_dl\extractor\generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.tiktok.com/@alevvla/video/6850602336549735685?lang=es

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/Erick/projects/tiktokVideoGenerator/workingDir/hand_pick.py", line 40, in <module>
    ytExtension(str(counter), folder, jsonInfoCheck, videoCounter)
  File "c:\Users\Erick\projects\tiktokVideoGenerator\workingDir\videoFunction.py", line 23, in ytExtension
    ydl.download([url])
  File "C:\Users\Erick\projects\tiktokVideoGenerator\tiktok\lib\site-packages\youtube_dl\YoutubeDL.py", line 2018, in download
    res = self.extract_info(
  File "C:\Users\Erick\projects\tiktokVideoGenerator\tiktok\lib\site-packages\youtube_dl\YoutubeDL.py", line 820, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Erick\projects\tiktokVideoGenerator\tiktok\lib\site-packages\youtube_dl\YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Erick\projects\tiktokVideoGenerator\tiktok\lib\site-packages\youtube_dl\YoutubeDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unsupported URL: https://www.tiktok.com/@alevvla/video/6850602336549735685?lang=es`

**Comment by lihuelworks** [comment]
Same here

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tiktok.com/@hpforgamers/video/6850493807859993861']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.1 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 4.2, ffprobe N-93293-gdb332832a1
[debug] Proxy map: {}
[generic] 6850493807859993861: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6850493807859993861: Downloading webpage
[generic] 6850493807859993861: Extracting information
ERROR: Unsupported URL: https://www.tiktok.com/@hpforgamers/video/6850493807859993861
Traceback (most recent call last):
  File "c:\users\cafe\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\cafe\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\cafe\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.tiktok.com/@hpforgamers/video/6850493807859993861
```

**Comment by sjmueller** [comment]
same problem here

**Comment by sjmueller** [comment]
Can the issue be linked here so we can all track the fix? If this is a dupe, I've looked up and down and can't find the original.

**Comment by revolter** [comment]
Maybe https://github.com/ytdl-org/youtube-dl/issues/25987?

**Comment by AmperAndSand** [comment]
> Maybe #25987?

That seems to be a different issue. That's a feature request, not a bug report. 

@remitamine Can you link the original so we can subscribe for notifications on this bug report?

**Comment by TonyStark** [comment]
> Maybe #25987?

thats not solution
issue not solved yet

**Comment by z0z0z** [comment]
For anyone new here, this guy closes countless issues as duplicates without any duplicate issue actually existing.

He will refuse to link the so-called duplicate issue or speak.

That's just how this bug tracker goes.

**Comment by bpenven** [comment]
> For anyone new here, this guy closes countless issues as duplicates without any duplicate issue actually existing.
> 
> He will refuse to link the so-called duplicate issue or speak.
> 
> That's just how this bug tracker goes.

Nothing new...

**Comment by bpenven** [comment]
Opened a new issue to get their attention. Still does not work with the version of today. https://github.com/ytdl-org/youtube-dl/issues/26138

**Comment by mralext20** [comment]
@remitamine can you please Lin other but this is a duplicate of? Otherwise can this please be reopened? Thanks 😊

**Comment by revolter** [comment]
@yan12125, are you aware of @remitamine's behavior?

**Comment by sjmueller** [comment]
@bpenven it looks like @dstftw closed your issue as a duplicate, so it appears @remitamine is not the only one?

**Comment by bpenven** [comment]
@sjmueller Yes, I still don't know the duplicate...

**Comment by revolter** [comment]
Maybe, because of the huge number of open issue and work to be done, they really don't have time to link all of the duplicates, even though they know which is which.

**Comment by sjmueller** [comment]
@revolter the issue is that there's no duplicate anywhere to be found, so nobody can track when it is being fixed or even if the issue is being worked on, priority etc.

**Comment by yan12125** [comment]
> are you aware of remitamine's behavior?

Sorry nope. I have not volunteered in youtube-dl development since 2018.

Regarding the issue itself - the duplicate appears to be #23264.

**Comment by TonyStark** [comment]
Since there is no fix available, you can try this simple bash downloading
https://github.com/rouze-d/tiktok-download/

**Comment by bpenven** [comment]
> Since there is no fix available, you can try this simple bash downloading
> https://github.com/rouze-d/tiktok-download/
> ^^no need of lolcat package

Thanks, I'll try that.

**Comment by TonyStark** [comment]
> > Since there is no fix available, you can try this simple bash downloading
> > https://github.com/rouze-d/tiktok-download/
> > ^^no need of lolcat package
> 
> Thanks, I'll try that.

its working
```

$ bash tik.sh "https://www.tiktok.com/@markoterzo/video/6762207861918420230"

--2020-07-29 22:34:16--  https://v19.tiktokcdn.com/23737aa5dc0dd483e443936b816c27a0/5f220079/video/tos/useast2a/tos-useast2a-ve-0068/449076372907418aa65c8235093bd867/?a=1233%5Cu0026br=3094%5Cu0026bt=1547%5Cu0026cr=0%5Cu0026cs=0%5Cu0026dr=0%5Cu0026ds=3%5Cu0026er=%5Cu0026l=202007291704180101150040641F380E3A%5Cu0026lr=tiktok_m%5Cu0026mime_type=video_mp4%5Cu0026qs=0%5Cu0026rc=ank1NDVyPGY2cTMzZDczM0ApNmlkO2hoOTtnNzg4ZTU6aWdoaWwzZG0tLWBfLS1eMTZzczYwLzMvNGNhLV4tMTFfMWE6Yw%3D%3D%5Cu0026vl=%5Cu0026vr=
Resolving v19.tiktokcdn.com (v19.tiktokcdn.com)... 151.101.122.113
Connecting to v19.tiktokcdn.com (v19.tiktokcdn.com)|151.101.122.113|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1430441 (1.4M) [video/mp4]
Saving to: ‘@markoterzo-6762207861918420230.mp4’

@markoterzo-6762207 100%[===================>]   1.36M  94.3KB/s    in 14s     

2020-07-29 22:34:32 (102 KB/s) - ‘@markoterzo-6762207861918420230.mp4’ saved [1430441/1430441]

```

**Comment by yan12125** [comment]
Thanks for the info. For further discussions, please move on to #23264 so that such info is more visible.
