### ISSUE TITLE
ERROR: The certificate of ‘yt-dl.org’ has expired.

### ISSUE THREAD

**Issue by freeload101** [ytdl-org/youtube-dl#26093]
## Checklist
ERROR: The certificate of ‘yt-dl.org’ has expired.

## Example URLs

ERROR: The certificate of ‘yt-dl.org’ has expired.

## Description
ERROR: The certificate of ‘yt-dl.org’ has expired.

Thanks for all the GREAT work let me know if you need anything -rmccurdyDOTcom

**Comment by freeload101** [comment]
Umm all I see on the closed ones is "works for me" let me help with this issue:

https://www.sslshopper.com/ssl-checker.html#hostname=https://yt-dl.org

![image](https://user-images.githubusercontent.com/4307863/88301664-e7a88180-ccd2-11ea-9ec1-0ac232c6fbb8.png)

https://www.sslchecker.com/sslchecker

![image](https://user-images.githubusercontent.com/4307863/88301831-1cb4d400-ccd3-11ea-8a96-275e73fb18ee.png)

Not a SSL guy but it's like depending on the  URL or  301 or 302 redirect ??? some how its pulling different cert .. like I got cert error in Chrome then later it worked with the latesturl ...

**Comment by freeload101** [comment]
https://www.e2enetworks.com/sectigo-addtrust-external-ca-root-certificate-expired-on-30th-may-2020

**Comment by garoto** [comment]
If you google further, you'll see that the "Intermediary Certificate Authority" having an expired cert is not an impeding to establish a secure connection to an affected host. You're just using an outdated CA chain. Stop being a doofus.
