### ISSUE TITLE
ERROR: Unable to download webpage: <urlopen error [Errno 0] Error> (caused by URLError(OSError(0, 'Error')))

### ISSUE THREAD

**Issue by xxsmile123** [ytdl-org/youtube-dl#26102]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
ERROR: Unable to download webpage: <urlopen error [Errno 0] Error> (caused by URLError(OSError(0, 'Error')))

report:
youtube-dl -f 137+140 https://www.youtube.com/watch?v=f9ohvZyQrmY --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '137+140', 'https://www.youtube.com/watch?v=f9ohvZyQrmY', '--verbose']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg git-2020-07-21-b5f1e05, ffprobe git-2020-07-21-b5f1e05
[debug] Proxy map: {'http': 'http://127.0.0.1:10809', 'https': 'https://127.0.0.1:10809', 'ftp': 'ftp://127.0.0.1:10809'}
[youtube] f9ohvZyQrmY: Downloading webpage
ERROR: Unable to download webpage: IncompleteRead(84189 bytes read) (caused by IncompleteRead(84189 bytes read)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "d:\python3.8\lib\site-packages\youtube_dl\extractor\common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "d:\python3.8\lib\site-packages\youtube_dl\YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "d:\python3.8\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "d:\python3.8\lib\site-packages\youtube_dl\utils.py", line 2624, in http_response
    content = resp.read()
  File "d:\python3.8\lib\http\client.py", line 461, in read
    return self._readall_chunked()
  File "d:\python3.8\lib\http\client.py", line 575, in _readall_chunked
    raise IncompleteRead(b''.join(value))

**Comment by remitamine** [comment]
most likely a problem with the proxy you're using.

**Comment by xiazeyu** [comment]
@remitamine Is it possible to let the program retry multiple times when accounting this error?
I found no solution but to download a video manually when I was downloading a list of video.
options like `-R infinite` helps try multiple times when downloader has some network problem, but this meta-data fetching process, it do not have such options.

This is the command I am using now:
`youtube-dl -i --fragment-retries infinite -R infinite --download-archive archive.txt --username <username> --password <password> --verbose <url>`

**Comment by GwamakaCharles** [comment]
In my case, I disconnected and reconnected to my wi-fi. This solved this issue. It could be due to a poor internet connection.
