### ISSUE TITLE
How to get audio+video when fetching with specific video format (not 'best')? I'd like to specify more than one argument for the -f option...

### ISSUE THREAD

**Issue by geopic** [ytdl-org/youtube-dl#26109]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello all. I download some videos off YouTube from time to time but every now and again the video is in 4k quality at 60fps (2160p60). My computer and VLC can't handle 4K at 60fps without lagging *hard* so I download the videos at 1080p60 instead. However, specifying the format with the `-f` flag only allows for one argument, so I can *only* download the video and not the audio at the same time for merging together. Is there any way to download a specific video format and audio format *together* with them being merged after download just like if I were to run the `youtube-dl` command without specifying formats at all? At the moment I download the videos as normal at 2160p60 and then convert it to 1080p60 using Handbrake, which seems like a waste of time. Thank you `youtube-dl` developers.

**Comment by remitamine** [comment]
read https://github.com/ytdl-org/youtube-dl#format-selection

**Comment by geopic** [comment]
Oh, I just needed to separate arguments with a comma. Thank you.
