### ISSUE TITLE
Youtube-dl (2020.06.16.1) is unable to extract video from youtube

### ISSUE THREAD

**Issue by jevgen** [ytdl-org/youtube-dl#26103]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X ] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X ] I've searched the bugtracker for similar bug reports including closed ones
- [X ] I've read bugs section in FAQ

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=wlNIxVshQ3Q']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.7.6 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, rtmpdump Reason
[debug] Proxy map: {}
[youtube] wlNIxVshQ3Q: Downloading webpage
ERROR: wlNIxVshQ3Q: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1893, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: wlNIxVshQ3Q: YouTube said: Unable to extract video data

## Description

Youtube-dl is unable to extract video from youtube
youtube-dl is up-to-date (2020.06.16.1)

**Comment by lmamane** [comment]
The above is an age-restricted video. I reproduced with another one, also age-restricted:

$ ytdl -v https://www.youtube.com/watch?v=9nheskbsU5g 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--prefer-ffmpeg', u'-v', u'https://www.youtube.com/watch?v=9nheskbsU5g']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-9-amd64-x86_64-with-debian-10.4
[debug] exe versions: ffmpeg 4.2.2-1, ffprobe 4.2.2-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 9nheskbsU5g: Downloading webpage
ERROR: 9nheskbsU5g: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/home/master/src/youtube-dl/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/master/src/youtube-dl/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/master/src/youtube-dl/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1893, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: 9nheskbsU5g: YouTube said: Unable to extract video data
