### ISSUE TITLE
Youtube-dl is not compatible with last mint 20.04 and probably ubuntu 20.04

### ISSUE THREAD

**Issue by jb68** [ytdl-org/youtube-dl#26126]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

I upgraded my computer and it seems that it completly remove /usr/bin/python. 
I downloaded the last version and run the installer but didn't fix it. I ended up editing the executable and changing the shbang to /usr/bin/python3 and now it is working :)

**Comment by jb68** [comment]
I understand this is a free project but why this is invalid? 
Ubuntu does not have /usr/bin/python and your code has so it is a bug. 
`/usr/bin/env python
/usr/bin/env: ‘python’: No such file or directory`

**Comment by remitamine** [comment]
youtube-dl support both python 2 and python 3, so `/usr/bin/python3` should not be hardcoded, instead in you provide the `/usr/bin/python` file in you're distribution(symlink) or install python 2(it will provide the `/usr/bin/python` file).

**Comment by axzxc1236** [comment]
Note that Ubuntu (20.04 and after) doesn't have `python` command until you install either "python-is-python2" or "python-is-python3"

The command to fix this is  
`sudo apt install python-is-python3`  
(or change python3 to python2 if you prefer Python 2 more)
