### ISSUE TITLE
trovo.live

### ISSUE THREAD

**Issue by marburger93** [ytdl-org/youtube-dl#26125]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Example Stream: https://trovo.live/RelaxBeats

## Description

Trovo is an interactive live streaming platform, you can check out the hottest games live, share your own gaming experiences, and join an amazing community created especially for gamers, creators and do-ers.... is like Twitch and also looks similar.

```
# ./youtube-dl -v https://www.trovo.live/RelaxBeats
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.trovo.live/RelaxBeats']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.13 (CPython) - Linux-4.9.182-xxxx-std-ipv6-64-x86_64-with-Debian-7
[debug] exe versions: avconv 3.2.14-1, avprobe 3.2.14-1, ffmpeg N-48007-g62f8d27ef1-static, ffprobe 3.2.14-1
[debug] Proxy map: {}
[generic] RelaxBeats: Requesting header
WARNING: Could not send HEAD request to https://www.trovo.live/RelaxBeats: HTTP Error 405: Method Not Allowed
[generic] RelaxBeats: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] RelaxBeats: Extracting information
ERROR: Unsupported URL: https://www.trovo.live/RelaxBeats
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2387, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.trovo.live/RelaxBeats
```

**Comment by DerBunteBall** [comment]
Hi,

I'm giving this a push. Would be also interested at this site.

Would like to give this additional infos:

## Example URLs

- Single video: https://trovo.live/video/ltv-100095501_100095501_1609596043?ltab=videos
- Playlist: https://trovo.live/Exsl (the video tab shows all stuff)
- Live Stream: https://trovo.live/Exsl (if channel is live)

## Description

Trovo is a gaming streaming portal. Login credentials should be not required. There are strems with age verification by a simple button. I'm really don't know much about extracting stuff. I'm able to find a URL of an .m3u8 file with Web Development tools in Firefox which can be passed to ffmpeg. It seems to have it's home in a big Nuxt.js object. Site itself looks full of JavaScript. For me it looks a bit tricky to parse out the download url. Googled a bit how to handle things but I think my knowledge is not enough to build a working extractor at this moment. Would be very thankful for an extractor which supports single video download, download of the past streams and clips and recording a livestream.

**Comment by JazzyScuffs** [comment]
Wanted to bump this as well as I would also be interested in downloading from here

**Comment by ATL-Flaneur** [comment]
Would like support for Trovo as well—creators are moving over DLive.

**Comment by UglyBoiDesu** [comment]
This would be a decent addition, Many popular creators from Dlive are moving over to Trovo due to censorship and persecution. Would be nice to be able to download vods that I've missed.
