### ISSUE TITLE
Unable to extract post url using adobe pass

### ISSUE THREAD

**Issue by sufr3ak** [ytdl-org/youtube-dl#26139]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--ap-mso', u'Comcast_SSO', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'https://www.nbc.com/the-soup/video/the-soup-722/4200738']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.06
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-112-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg N-50726-g20c5f4d835-static, ffprobe N-50726-g20c5f4d835-static
[debug] Proxy map: {}
[NBC] 4200738: Downloading JSON metadata
[NBC] 4200738: Downloading Provider Redirect Page
[NBC] 4200738: Logging in
[NBC] 4200738: Retrieving Session
ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```

## Description

I've tested this with 2 different providers.  Off provider network gives a 401 unauthenticated error. On network gives a url extraction error.

Working URL (no credentials needed)
https://disneynow.com/shows/the-rocketeer/season-01/episode-01-first-flight-pilot-error/vdka14005750

Failing URL
https://disneynow.com/shows/the-rocketeer/season-01/episode-03-ground-control-to-rocketeer-save-the-statue/vdka14224279

if credentials are required, please contact me

**Comment by johannvonperfect** [comment]
FWIW, I have the same problem. I will add that I am using Comacst_SSO; my home network is Fios; my network at work is Comcast; I am also trying to use DisneyNow. I get HTTP Error 401 on either network just using the MSO login credentials. When adding --cookies from a logged in session at either location, I get the url extraction error. If any additional information is needed I am happy to help.

**Comment by sufr3ak** [comment]
I updated youtube-dl and still am having the same issue. I've updated the verbose output to be consistent

**Comment by sufr3ak** [comment]
Issue persists with version 2020.09.20. Should I update this issue? open a new one?

**Comment by johannvonperfect** [comment]
As with the related [26558](https://github.com/ytdl-org/youtube-dl/issues/26558), I am still having this issue as well.

**Comment by sufr3ak** [comment]
Should this issue be updated to current versions, or closed and a new one created?

**Comment by johannvonperfect** [comment]
I was wondering the same thing. I know they incorporated that other ABC/extractor related change, but this issue still persists. I have tried both original youtube-dl and dlc under the most recent release versions (2020.11.17 and 2020.11.11 respectively).

**Comment by sufr3ak** [comment]
yt-dlc works ON network. this one, I haven't had any luck. I'll go ahead and open a new one, if you want to comment there.  Ill update this thread with the number for the new one.

**Comment by johannvonperfect** [comment]
FWIW, it still does not work for me even on network. I am using a Comcast (personal) login. I have Fios at home where it does not work. I have Comcast at work, where it also does not work with the same 401 error. Cookies do not help. The failing sites for me are Disneynow and Cartoon Network. I recently tried Food Network with the MSO (and cookies) and that works fine.

**Comment by sufr3ak** [comment]
most recent few versions of ytdlc did work for disneynow, on comcast, on their network.

**Comment by johannvonperfect** [comment]
I spoke too soon and thank you for making me take a second look. I still get the same 401 in both locations with the MSO credentials only. HOWEVER: BOTH locations (Work-Comcast and Home-Fios) now appear to work correctly on the most recent yt-dlc release **when using cookies**. I signed out and signed back in before generating my cookies file and I am now pulling a bunch of previously 401 videos from Disneynow and Cartoon Network. Might be worth a try for you as well.

**Comment by sufr3ak** [comment]
What syntax did you use to force cookies? when i tried to use cookies, it told me it required the use of MSO

**Comment by johannvonperfect** [comment]
youtube-dlc --ap-mso=Comcast_SSO --ap-username _[comcast username]_ --ap-password _[comcast password]_ --cookies cookies.txt --batch-file links.txt --ignore-errors

Because it has been messed up for so long I kept a running text file with the links that I passed in as a batch file but it is working for single video links as well. (Unfortunately one video from my list is no longer available which is going to drive me crazy because it is the only one missing from that season.)

**Comment by sufr3ak** [comment]
Holy crap, that worked.

**Comment by johannvonperfect** [comment]
Because I was following you (and interjecting) on your posts on both projects, I wasn't even paying attention to which project you posted this on when it popped up in my e-mail notifications this morning.

To be clear, my syntax works using youtube-dlc - whatever change was incorporated there apparently still hasn't been incorporated in youtube-dl, since it still fails with the post url error when passing cookies even after a fresh install. Notably, in response to our few messages back and forth making the issue more noticeable, this issue has been closed as a duplicate instead of someone popping in to engage and help resolve it. A duplicate of what, you might ask? I have no idea, but it certainly does not appear to be anything that is open that I can see. (Which is the kind of community engagement, or lack thereof, that led to dlc to begin with.)

I am glad you and I were able to piece things together at least. (Until it breaks again.)

**Comment by sufr3ak** [comment]
I followed. YTDLC works at the moment,  like you said.  No idea what the duplicate is

**Comment by IONECarter** [comment]
@johannvonperfect @sufr3ak Is this still working for you?  I get the 401 error using ComcastSSO on a non-comcast network even when passing cookies.

**Comment by sufr3ak** [comment]
I switched to yt-dlp instead. It works there.

**Comment by IONECarter** [comment]
> I switched to yt-dlp instead. It works there.
> […](#)
> On Apr 2, 2021, at 17:27, IONECarter ***@***.***> wrote: ﻿ @johannvonperfect @sufr3ak Is this still working for you? I get the 401 error using ComcastSSO on a non-comcast network even when passing cookies. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Interesting as I was trying that one and having the issues as well.  Will keep playing around with it.  Do you mind sharing the command you are using?

**Comment by johannvonperfect** [comment]
I too moved to yt-dlp. I use the same command referenced above just with yt-dlp at the beginning. I usually do NOT need to use cookies even as I use a Comcast login from a Fios network. I occasionally get the auth problem, what usually fixes it is signing out of the provider on whatever site you are using (for me it is almost always DisneyNow) and signing back in. From there, either the auth will work again or I then generate a fresh set of cookies and add the --cookies tag.

**Comment by IONECarter** [comment]
@sufr3ak @johannvonperfect Appreciate the help, was able to get this to work by fully logging out of all the previously used ComcastSSO sites and clearing my cookies.  Once I logged back in, I saved my full cookie file and not just the current site I was trying to access.  Those couple things seemed to make the difference.
