### ISSUE TITLE
How do I download YouTube videos that require a login?

### ISSUE THREAD

**Issue by Rekrullurker** [ytdl-org/youtube-dl#26142]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I want to download this video;

https://youtube.com/watch?v=-z9ARpndyGo

Apparently it's age restricted because YouTube-DL can't download it. Neither can any of the download sites that I normally fall back on.

I tried using the --username= option, it asked for my password and then reported an error of being unable to look up account information. So that doesn't work. Yes, I tried it multiple times to be sure the name and password were correct.

The documentation say that you can pass cookies to YouTube-DL, but they have to be in a conforming format. Unfortunately the only browser that will still load YouTube for me is Opera and none of the extensions I could find will export to anything other than a "JSON" file. I've tried three different extensions that claim they will export cookies to a text file and none of them have created anything that YouTube-DL will accept.

How do I download this video?

**Comment by Sembiance** [comment]
Ditto with this video: https://www.youtube.com/watch?v=M9Khfy4aNgo

**Comment by a-raccoon** [comment]
Need an issue number / solution number to this duplicate issue.  Can open up a new issue to collect this information if that's required.
