### ISSUE TITLE
youtube-dl no longer recognises twitch usernames

### ISSUE THREAD

**Issue by ninjachicken1** [ytdl-org/youtube-dl#26158]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser - channel names and ids have been replaced with placeholders for examples sake.
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

As of the beginning of June, youtube-dl no longer recognises twitch channel names when processing a list of urls in a separate text file, and instead now requires the user to use the ids instead. When running youtube-dl, I use this command:
`youtube-dl --download-archive downloaded.txt -i -o "%(uploader)s/%(upload_date)s - %(title)s - (%(duration)ss) [%(resolution)s].%(ext)s" --batch-file=channel_list.txt --dateafter 20190127`

channel_list.txt looks something like this:
`https://www.twitch.tv/channelname1/videos/all`
`https://www.twitch.tv/channelname2/videos/all`
`https://www.twitch.tv/channelname3/videos/all`

This now results in the following error for each channel:
`ERROR: twitch:videos:all returned error: Bad Request - Channel identifier "channelname1" is in an invalid format`

Removing "videos/all" from the end gives a more useful error. So if the url looks like this:
`https://www.twitch.tv/channelname1`

Then the error I get looks like this:

`[twitch:stream] channelname1: Downloading access token JSON`
`[twitch:stream] 12345678: Downloading stream JSON`
`ERROR: 12345678 is offline`

So now we've shown that youtube-dl can get the channel id from the channel name. From this I can get an url that works, and it looks like this:
`https://www.twitch.tv/12345678/videos/all`

So while the issue is solved for me from an engineering standpoint, I still have the following problems:

1. It took me two months to find this information - during that time a lot of the videos I wanted to download have probably expired. Plus, this info was not easy to find.
2. Typing the ids in is more prone to human error than just copy/pasting the twitch urls like I used to.
3. It's a lot of unnecessary busywork.

**Comment by ahmedtds** [comment]
This pull request fixes it: https://github.com/ytdl-org/youtube-dl/pull/25606
There are instructions on comments on how to apply it yourself.
