### ISSUE TITLE
Doesn't work "autonumber" increasing in OUTPUT TEMPLATE

### ISSUE THREAD

**Issue by Lirk88** [ytdl-org/youtube-dl#26154]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

youtube-dl -v https://www.youtube.com/watch?v=oJ2LLnAQGHI -o "%(autonumber)s-%(title)s-%(id)s.%(ext)s"
[debug] System config: []
[debug] User config: ['--no-check-certificate', '-f', 'bestvideo[height<=720][height>=360][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '-o', '%(title)s-%(id)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=oJ2LLnAQGHI', '-o', '%(autonumber)s-%(title)s-%(id)s.%(ext)s']
[debug] Encodings: locale cp1251, fs mbcs, out cp1251, pref cp1251
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2020-06-28-4cfcfb3, ffprobe git-2020-06-28-4cfcfb3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] oJ2LLnAQGHI: Downloading webpage
[debug] Invoking downloader on '...'
[download] Destination: 00001-Milk Inc. - Oceans (Live @ Vrt Summer 1999)-oJ2LLnAQGHI.f135.mp4
[download]   0.0% of 21.48MiB at 333.33KiB/s ETA 01:05
[download]   0.0% of 21.48MiB at 750.01KiB/s ETA 00:29
[download]   0.0% of 21.48MiB at  1.71MiB/s ETA 00:15 
[download]   0.1% of 21.48MiB at  2.44MiB/s ETA 00:08 
[download]   0.1% of 21.48MiB at  3.78MiB/s ETA 00:05 
[download]   0.3% of 21.48MiB at  4.39MiB/s ETA 00:04 
[download]   0.6% of 21.48MiB at  5.91MiB/s ETA 00:03 
[download]   1.2% of 21.48MiB at  5.79MiB/s ETA 00:03 
[download]   2.3% of 21.48MiB at  8.60MiB/s ETA 00:02 
[download]   4.7% of 21.48MiB at  9.16MiB/s ETA 00:02 
[download]   9.3% of 21.48MiB at  9.66MiB/s ETA 00:02 
[download]  18.6% of 21.48MiB at 10.18MiB/s ETA 00:01 
[download]  37.2% of 21.48MiB at 10.47MiB/s ETA 00:01 
[download]  44.5% of 21.48MiB at 10.60MiB/s ETA 00:01 
[download]  44.5% of 21.48MiB at 499.98KiB/s ETA 00:24
[download]  44.5% of 21.48MiB at  1.46MiB/s ETA 00:08 
[download]  44.5% of 21.48MiB at  3.42MiB/s ETA 00:03 
[download]  44.5% of 21.48MiB at  4.88MiB/s ETA 00:02 
[download]  44.6% of 21.48MiB at  3.78MiB/s ETA 00:03 
[download]  44.8% of 21.48MiB at  4.73MiB/s ETA 00:02 
[download]  45.1% of 21.48MiB at  5.91MiB/s ETA 00:01 
[download]  45.6% of 21.48MiB at  7.11MiB/s ETA 00:01 
[download]  46.8% of 21.48MiB at  7.80MiB/s ETA 00:01 
[download]  49.1% of 21.48MiB at  7.51MiB/s ETA 00:01 
[download]  53.8% of 21.48MiB at  7.81MiB/s ETA 00:01 
[download]  63.1% of 21.48MiB at  7.95MiB/s ETA 00:00 
[download]  81.7% of 21.48MiB at  8.10MiB/s ETA 00:00 
[download]  89.4% of 21.48MiB at  8.15MiB/s ETA 00:00 
[download]  89.4% of 21.48MiB at 999.83KiB/s ETA 00:02
[download]  89.4% of 21.48MiB at  1.46MiB/s ETA 00:01 
[download]  89.5% of 21.48MiB at  3.42MiB/s ETA 00:00 
[download]  89.5% of 21.48MiB at  7.32MiB/s ETA 00:00 
[download]  89.6% of 21.48MiB at  4.32MiB/s ETA 00:00 
[download]  89.7% of 21.48MiB at  4.73MiB/s ETA 00:00 
[download]  90.0% of 21.48MiB at  6.53MiB/s ETA 00:00 
[download]  90.6% of 21.48MiB at  7.78MiB/s ETA 00:00 
[download]  91.8% of 21.48MiB at  7.45MiB/s ETA 00:00 
[download]  94.1% of 21.48MiB at  8.76MiB/s ETA 00:00 
[download]  98.7% of 21.48MiB at  9.66MiB/s ETA 00:00 
[download] 100.0% of 21.48MiB at  9.79MiB/s ETA 00:00 
[download] 100% of 21.48MiB in 00:02                  
[debug] Invoking downloader on '...'
[download] Destination: 00001-Milk Inc. - Oceans (Live @ Vrt Summer 1999)-oJ2LLnAQGHI.f140.m4a
[download]   0.0% of 3.06MiB at 333.23KiB/s ETA 00:09
[download]   0.1% of 3.06MiB at 749.83KiB/s ETA 00:04
[download]   0.2% of 3.06MiB at  1.71MiB/s ETA 00:01 
[download]   0.5% of 3.06MiB at  2.44MiB/s ETA 00:01 
[download]   1.0% of 3.06MiB at  3.36MiB/s ETA 00:00 
[download]   2.0% of 3.06MiB at  4.73MiB/s ETA 00:00 
[download]   4.0% of 3.06MiB at  6.20MiB/s ETA 00:00 
[download]   8.1% of 3.06MiB at  6.92MiB/s ETA 00:00 
[download]  16.3% of 3.06MiB at  8.91MiB/s ETA 00:00 
[download]  32.6% of 3.06MiB at  8.76MiB/s ETA 00:00 
[download]  65.2% of 3.06MiB at  9.70MiB/s ETA 00:00 
[download] 100.0% of 3.06MiB at 10.11MiB/s ETA 00:00 
[download] 100% of 3.06MiB in 00:00                  
[ffmpeg] Merging formats into "00001-Milk Inc. - Oceans (Live @ Vrt Summer 1999)-oJ2LLnAQGHI.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:00001-Milk Inc. - Oceans (Live @ Vrt Summer 1999)-oJ2LLnAQGHI.f135.mp4" -i "file:00001-Milk Inc. - Oceans (Live @ Vrt Summer 1999)-oJ2LLnAQGHI.f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:00001-Milk Inc. - Oceans (Live @ Vrt Summer 1999)-oJ2LLnAQGHI.temp.mp4"
Deleting original file 00001-Milk Inc. - Oceans (Live @ Vrt Summer 1999)-oJ2LLnAQGHI.f135.mp4 (pass -k to keep)
Deleting original file 00001-Milk Inc. - Oceans (Live @ Vrt Summer 1999)-oJ2LLnAQGHI.f140.m4a (pass -k to keep)

youtube-dl -v https://www.youtube.com/watch?v=oJ2LLnAQGHI -o "%(autonumber)s-%(title)s-%(id)s.%(ext)s"
[debug] System config: []
[debug] User config: ['--no-check-certificate', '-f', 'bestvideo[height<=720][height>=360][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '-o', '%(title)s-%(id)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=oJ2LLnAQGHI', '-o', '%(autonumber)s-%(title)s-%(id)s.%(ext)s']
[debug] Encodings: locale cp1251, fs mbcs, out cp1251, pref cp1251
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2020-06-28-4cfcfb3, ffprobe git-2020-06-28-4cfcfb3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] oJ2LLnAQGHI: Downloading webpage
[download] 00001-Milk Inc. - Oceans (Live @ Vrt Summer 1999)-oJ2LLnAQGHI.mp4 has already been downloaded and merged

## Description

"Autonumber"  is added to the first video, but not to subsequent videos.

**Comment by dstftw** [comment]
It's not supposed to preserve across different runs.
