### ISSUE TITLE
Disable head request and straightforward to get request?

### ISSUE THREAD

**Issue by asgmeonerandom** [ytdl-org/youtube-dl#26165]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones - there are like 30 pages. (and more) :(

## Question

1.) I've find out why streamlocks returns 403, when I sent a GET request it works. But, more request to manifest.mpd will result in 403 error. And, the issue is ytdl send an head request and get request which cause error 403.

Does someone know how to make YTDL to not send HEAD request so that it will send get request only?

2.) (bonus)
I am using youtube-dl from homebrew, and I am not sure after cloning youtube-dl to modify it and play with it... My goal is to download videos from streamlock (MPD) for archiving so I can watch it later.

Thanks in advance

**Comment by xuzifan-github** [comment]
Has this problem been solved?
