### ISSUE TITLE
[youtube] Regular expression for finding next page of search results is outdated.

### ISSUE THREAD

**Issue by RedpointsBots** [ytdl-org/youtube-dl#26161]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'ytsearchdate50:the']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.7.5 (CPython) - Linux-4.15.0-112-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:search:date] query "the": Downloading page 1
[download] Downloading playlist: the
[youtube:search:date] playlist the: Collected 20 video ids (downloading 20 of them)
[download] Downloading video 1 of 20
```

## Description

The regular expression used to find the next page link in the results is currently not working. As a result, regardless of how many results you specify there is a limit to 20 results (the number of results on the first page). 

The regex, found [here](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L3194) should be:
`r'href="(/results\?[^"]*\b(?:sp=[^"]+)?)"[^>]*>\s*<span[^>]+class="[^"]*\byt-uix-button-content\b[^"]*"[^>]*>Next'`. I left in the incorrect part as optional, for any backwards compatibility issues.

**Comment by RedpointsBots** [comment]
I have created a pull request for this issue: https://github.com/ytdl-org/youtube-dl/pull/26163.

**Comment by dstftw** [comment]
No longer actual.
