### ISSUE TITLE
Overwriting --no-mtime in config

### ISSUE THREAD

**Issue by ntcarver0** [ytdl-org/youtube-dl#26169]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have set the --no-mtime flag in my config file, however there is one place where I do want mtime to be written. How would I go about setting this to be written for this one case?

**Comment by 0l-l0** [comment]
Just don't use the config for that one either by issuing `--ignore-config` or by specifying a custom config file with `--config-location <path-to-your-config>`.

If you need more sophisticated per-case settings, I recommend you use embedded youtube-dl.

**Comment by ntcarver0** [comment]
Thanks, @0l-l0. That'll do it.
