### ISSUE TITLE
Unrecognized Video format on ancient YouTube video

### ISSUE THREAD

**Issue by madprogramer** [ytdl-org/youtube-dl#26164]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl https://www.youtube.com/watch?v=nRA4gWYfk2s --verbose
[debug] System config: []
[debug] User config: [u'--add-metadata', u'--output', u'~/Onedrive/Mac ~ Today/Videos/YouTube Archive/%(upload_date)s~%(uploader)s~%(title)s~%(id)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=nRA4gWYfk2s', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.11 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] nRA4gWYfk2s: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2364, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

- I tried to download a YouTube video from 2007 titled, Lord of the Flies: Castle Rock.
- The editing suggests it has been exported from Windows Movie Maker.
- For wherever reason, it raises an ExtractorError. I'm not quite sure if this is the result of an incomplete install on my part, or that somehow this really is an unimplemented file format.

**Comment by ahmedtds** [comment]
[debug] youtube-dl version 2020.03.24

this is the reason

**Comment by madprogramer** [comment]
Apologies for forgetting to update, **but I'm still getting this on 2020.07.28**:

`$youtube-dl https://www.youtube.com/watch?v=nRA4gWYfk2s --verbose
[debug] System config: []
[debug] User config: [u'--add-metadata', u'--output', u'~/Onedrive/Mac ~ Today/Videos/YouTube Archive/%(upload_date)s~%(uploader)s~%(title)s~%(id)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=nRA4gWYfk2s', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.11 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] nRA4gWYfk2s: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2364, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`
