### ISSUE TITLE
Unable to open key file

### ISSUE THREAD

**Issue by cwondercheck** [ytdl-org/youtube-dl#26170]
@tml

C:\Users\Chenaniah>youtube-dl -v --add-header "authorization:eyJraWQiOiI1ODJjNjk1NC0zNDgzLTRhNTktOGQzOC04Zbtg1q2cfzfucnu4xpucvxcf6njah4rwj8uqdvl9alrz9.eyJzdWIiOiJmM28UUpeD9oe8QUMFbWXhbxkXmiuQJ2uNWQcMJsurHxanzM4FTWYDfYfLBz3vaJgqXeRfdNkJ9bnChX5d4otsNg4cr5Tkh9VjegsetZSV1C40.Fg-pKgejyit9fvJtwtrBl8-pTOK-0HxqJAnLck5RLSEjzvWUm8VBwqSanxW-KCU0s70D4127cAcsegq_kneVAw" "https://vod-l3c-na.media.plus.espn.com/ps01/espn/event/2020/07/03/Fri_73_CFL2020_20200703_1593813631021/7000K/7000_complete_aeng-trimmed.m3u8"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--add-header', 'authorization:eyJraWQiOiI1ODJjNjk1NC0zNDgzLTRhNTktOGQzOC04Zbtg1q2cfzfucnu4xpucvxcf6njah4rwj8uqdvl9alrz9.eyJzdWIiOiJmM28UUpeD9oe8QUMFbWXhbxkXmiuQJ2uNWQcMJsurHxanzM4FTWYDfYfLBz3vaJgqXeRfdNkJ9bnChX5d4otsNg4cr5Tkh9VjegsetZSV1C40.Fg-pKgejyit9fvJtwtrBl8-pTOK-0HxqJAnLck5RLSEjzvWUm8VBwqSanxW-KCU0s70D4127cAcsegq_kneVAw', 'https://vod-l3c-na.media.plus.espn.com/ps01/espn/event/2020/07/03/Fri_73_CFL2020_20200703_1593813631021/7000K/7000_complete_aeng-trimmed.m3u8']
[debug] Adding header from command line option authorization:eyJraWQiOiI1ODJjNjk1NC0zNDgzLTRhNTktOGQzOC04Zbtg1q2cfzfucnu4xpucvxcf6njah4rwj8uqdvl9alrz9.eyJzdWIiOiJmM28UUpeD9oe8QUMFbWXhbxkXmiuQJ2uNWQcMJsurHxanzM4FTWYDfYfLBz3vaJgqXeRfdNkJ9bnChX5d4otsNg4cr5Tkh9VjegsetZSV1C40.Fg-pKgejyit9fvJtwtrBl8-pTOK-0HxqJAnLck5RLSEjzvWUm8VBwqSanxW-KCU0s70D4127cAcsegq_kneVAw
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[generic] 7000_complete_aeng-trimmed: Requesting header
[generic] 7000_complete_aeng-trimmed: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://vod-l3c-na.media.plus.espn.com/ps01/espn/event/2020/07/03/Fri_73_CFL2020_20200703_1593813631021/7000K/7000_complete_aeng-trimmed.m3u8'
[download] Destination: 7000_complete_aeng-trimmed-7000_complete_aeng-trimmed.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3705.0 Safari/537.36
authorization: eyJraWQiOiI1ODJjNjk1NC0zNDgzLTRhNTktOGQzOC04Zbtg1q2cfzfucnu4xpucvxcf6njah4rwj8uqdvl9alrz9.eyJzdWIiOiJmM28UUpeD9oe8QUMFbWXhbxkXmiuQJ2uNWQcMJsurHxanzM4FTWYDfYfLBz3vaJgqXeRfdNkJ9bnChX5d4otsNg4cr5Tkh9VjegsetZSV1C40.Fg-pKgejyit9fvJtwtrBl8-pTOK-0HxqJAnLck5RLSEjzvWUm8VBwqSanxW-KCU0s70D4127cAcsegq_kneVAw
Accept-Language: en-us,en;q=0.5
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
" -i "https://vod-l3c-na.media.plus.espn.com/ps01/espn/event/2020/07/03/Fri_73_CFL2020_20200703_1593813631021/7000K/7000_complete_aeng-trimmed.m3u8" -c copy -f mp4 "file:7000_complete_aeng-trimmed-7000_complete_aeng-trimmed.mp4.part"
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[tcp @ 00000283dc8adc00] Starting connection attempt to 8.252.37.124 port 443
[tcp @ 00000283dc8adc00] Successfully connected to 8.252.37.124 port 443
[hls @ 00000283dc8aa340] Skip ('#EXT-X-VERSION:3')
[hls @ 00000283dc8aa340] Skip ('#EXT-X-PROGRAM-DATE-TIME:2020-07-03T23:30:04.697Z')
[hls @ 00000283dc8aa340] HLS request for url 'https://vod-l3c-na.media.plus.espn.com/ps01/espn/event/2020/07/03/Fri_73_CFL2020_20200703_1593813631021/7000K/185/23/30/04_703.ts', offset 0, playlist 0
[hls @ 00000283dc8aa340] Opening 'https://playback.svcs.plus.espn.com/events/7f7416ba-95de-4e08-b0ed-97e512dc586b/media/ffb25e6c-c59d-4120-95de-ef3bc3b6407b/keys/b135ef94-7e7d-4cae-9150-46b1c784c839' for reading
[tcp @ 00000283dd137a00] Starting connection attempt to 13.226.214.76 port 443
[tcp @ 00000283dd137a00] Successfully connected to 13.226.214.76 port 443
[hls @ 00000283dc8aa340] Unable to open key file https://playback.svcs.plus.espn.com/events/7f7416ba-95de-4e08-b0ed-97e512dc586b/media/ffb25e6c-c59d-4120-95de-ef3bc3b6407b/keys/b135ef94-7e7d-4cae-9150-46b1c784c839
[hls @ 00000283dc8aa340] Opening 'crypto+https://vod-l3c-na.media.plus.espn.com/ps01/espn/event/2020/07/03/Fri_73_CFL2020_20200703_1593813631021/7000K/185/23/30/04_703.ts' for reading
[tcp @ 00000283dd137ac0] Starting connection attempt to 8.252.37.124 port 443
[tcp @ 00000283dd137ac0] Successfully connected to 8.252.37.124 port 443
[hls @ 00000283dc8aa340] Error when loading first segment 'https://vod-l3c-na.media.plus.espn.com/ps01/espn/event/2020/07/03/Fri_73_CFL2020_20200703_1593813631021/7000K/185/23/30/04_703.ts'
[AVIOContext @ 00000283dd511bc0] Statistics: 1052064 bytes read, 0 seeks
[AVIOContext @ 00000283dcea9c00] Statistics: 36213 bytes read, 0 seeks
https://vod-l3c-na.media.plus.espn.com/ps01/espn/event/2020/07/03/Fri_73_CFL2020_20200703_1593813631021/7000K/7000_complete_aeng-trimmed.m3u8: Invalid data found when processing input

ERROR: ffmpeg exited with code 1
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 863, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 1644, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\external.py", line 64, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\downloader\common.py", line 165, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 625, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 587, in trouble

Description

Every time I try to download a show this is what shows. It used to work for me all the time last year but now doesn't at all.

**Comment by cwondercheck** [comment]
@tml

**Comment by tml** [comment]
Your DSS Session Key looks WAY too small - I would guess you've not managed to copy the entire thing. Mine is 2779 characters long. What you are showing here is only about 1/10th that long.
