### ISSUE TITLE
[Dropbox] ERROR: unable to download video data: HTTP Error 403: Forbidden 

### ISSUE THREAD

**Issue by jimleecoom** [ytdl-org/youtube-dl#26177]
I'm not sure if this situation goes in this area, as this is my first time using this platform. I'm not tech savvy at all. This is a challenge for those who are. Whoever can find a way to download a Dropbox video when the download button is disabled, you are a genius. Please find a way to bypass the disabled download button so people can download the original videos.

**Comment by zuntah** [comment]
I'm having the same issue :(
