### ISSUE TITLE
Can I format filename from video description? [question]

### ISSUE THREAD

**Issue by and7ey** [ytdl-org/youtube-dl#26182]
The videos I am planning to download have a description in the following format:
```
VID_20200517_171613 Something Something.mp4

2020-06-28 13:53:42
```
Their titles are like `Something Something`. 

I would like to download the video as `VID_20200517_171613 Something Something.mp4`. Is there any way to do it?

Or, `VID_20200517_171613 Something Something.mp4` is equal to original filename. Is there any way to get it from YouTube?
Probably, I can save description to json (`--write-info-json`) and rename the file once it is downloaded?

**Comment by dstftw** [comment]
Read FAQ on format selection.

**Comment by and7ey** [comment]
Surely I did it. I see no way to use the `description` field in the output. Do I miss something?
