### ISSUE TITLE
Youtube history is not working

### ISSUE THREAD

**Issue by Shulyaka** [ytdl-org/youtube-dl#26181]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
pi@speaker:~ $ youtube-dl -v --netrc :ythistory
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--netrc', ':ythistory']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.7.3 (CPython) - Linux-5.4.51-v7l+-armv7l-with-debian-10.4
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube:history] Downloading login page
[youtube:history] Looking up account info
WARNING: Unable to look up account info: HTTP Error 404: Not Found
[youtube:history] Youtube History: Downloading webpage
[download] Downloading playlist: Youtube History
[youtube:history] playlist Youtube History: Downloading 0 videos
[download] Finished downloading playlist: Youtube History
```

## Description

Youtube-dl is unable to authenticate with youtube, thus it cannot see the history.
***IMPORTANT NOTE***: This is NOT a duplicate of any open issue as you may see on the below screen shot. I've searched the exact error message:
![issues](https://user-images.githubusercontent.com/2741408/88897661-56965500-d254-11ea-9fdc-ba5f95cf3a5d.png)
There are similar closed issues, but they all are closed with neither solution nor explanation. Please not close this issue as duplicate because it is not. This is a real issue and I hope you read this message. Thank you!

**Comment by Shulyaka** [comment]
But... I had proven it is not a duplicate!

**Comment by Shulyaka** [comment]
Please reopen

**Comment by Shulyaka** [comment]
I did search for "Unable to look up account info: HTTP Error 404: Not Found".
All are issues closed as duplicates without a reference. None of them are with solutions. No open issues.
![изображение](https://user-images.githubusercontent.com/2741408/88903203-f6a3ac80-d25b-11ea-8806-2ba40b5a37c6.png)
Half of them are mine.

Also tried with Google. 2 results:
![изображение](https://user-images.githubusercontent.com/2741408/88903224-028f6e80-d25c-11ea-96a6-cfba2502e104.png)


What am I doing wrong??? I am honestly trying to help!

**Comment by dstftw** [comment]
Is it some kind of fat trolling or what? https://github.com/ytdl-org/youtube-dl/search?q=Unable+to+look+up+account+info%3A+HTTP+Error+404%3A+Not+Found&state=open&type=Issues, first hit.

**Comment by Shulyaka** [comment]
Of course not trolling!

I've seen that issue, but the error message is different, so I considered it a different issue.
Their error:
```
[youtube:user] Downloading login page
[youtube:user] Looking up account info
[youtube:user] Logging in
[youtube:user] Checking cookie
[youtube:user] welcome: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
```
My error:
```
[youtube:history] Downloading login page
[youtube:history] Looking up account info
WARNING: Unable to look up account info: HTTP Error 404: Not Found
```
Their error is on the channel page, and mine is on the login. That is at least my understanding.

Thanks for the link, I really appreciate your response!
