### ISSUE TITLE
Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))

### ISSUE THREAD

**Issue by tunsuriya** [ytdl-org/youtube-dl#26198]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/playlist?list=PLyc5xVO2uDsB_HVlVzAOf5JKfV0U-LXvz', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 2.7.16 (CPython) - Linux-5.6.0-0.bpo.2-amd64-x86_64-with-debian-10.5
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[youtube:playlist] PLyc5xVO2uDsB_HVlVzAOf5JKfV0U-LXvz: Downloading webpage
[download] Downloading playlist: How to Build and Install Gentoo Linux
[youtube:playlist] playlist How to Build and Install Gentoo Linux: Downloading 10 videos
[download] Downloading video 1 of 10
[youtube] KJ7zVUBcS4s: Downloading webpage
[youtube] KJ7zVUBcS4s: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] 1 of 9 Building and Installing Gentoo by Kernotex - Part 1-KJ7zVUBcS4s.mp4 has already been downloaded and merged
[download] Downloading video 2 of 10
[youtube] nl4Cuqwyb6s: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
  File "/home/tunsuriya/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/tunsuriya/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/tunsuriya/.local/bin/youtube-dl/youtube_dl/utils.py", line 2736, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)

**Comment by qianqianjie1** [comment]
Did you solve this problem, I ran into the same problem

**Comment by redstonulo** [comment]
How did you solve the problem?

**Comment by dirkf** [comment]
Presumably by fixing the network: in particular, DNS.
