### ISSUE TITLE
A small correction to the docs

### ISSUE THREAD

**Issue by lkintact** [ytdl-org/youtube-dl#26194]
- [x] I've verified that I'm running youtube-dl version **2020.07.28**

At https://github.com/ytdl-org/youtube-dl/blob/master/README.md#output-template the template name `playlist_index` is said to be "padded with leading zeros according to the total length of the playlist". This doesn't happen however (perhaps was the case in the past, then changed and not reflected in the documentation?)

To check execute
`youtube-dl --get-filename -o "[index %(playlist_index)d] %(title)s.%(ext)s" "https://www.youtube.com/watch?v=a0ul-BghOAs&list=OLAK5uy_kC4d8eCdL3QzEXEAoF97MMxJLP3f6M0n0"`, notice the indexes 1-9 aren't padded with zeroes.

**Comment by remitamine** [comment]
```
youtube-dl --get-filename -o "[index %(playlist_index)s] %(title)s.%(ext)s" "https://www.youtube.com/watch?v=a0ul-BghOAs&list=OLAK5uy_kC4d8eCdL3QzEXEAoF97MMxJLP3f6M0n0"
[index 01] Phantogram 'Nothing But Trouble' [Official Audio].mp4
[index 02] Phantogram - Black Out Days (Official Music Video).mp4
[index 03] Phantogram - Fall In Love (Official Music Video).mp4
[index 04] Never Going Home.mp4
[index 05] The Day You Died.mp4
[index 06] Howling At The Moon.mp4
[index 07] Bad Dreams.mp4
[index 08] Phantogram 'Bill Murray' [Official Audio].mp4
[index 09] I Don’t Blame You.mp4
[index 10] Celebrating Nothing.mp4
[index 11] My Only Friend.mp4
```

**Comment by lkintact** [comment]
@remitamine  Sorry I didn't paste the verbose log. This is how it looks for me:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--get-filename', '-o', '[index %(playlist_index)d] %(title)s.%(ext)s', 'https://www.youtube.com/watch?v=a0ul-BghOAs&list=OLAK5uy_kC4d8eCdL3QzEXEAoF97MMxJLP3f6M0n0']
[debug] Encodings: locale cp1251, fs mbcs, out cp1251, pref cp1251
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
[index 1] Phantogram 'Nothing But Trouble' [Official Audio].webm
[debug] Default format spec: bestvideo+bestaudio/best
[index 2] Phantogram - Black Out Days (Official Music Video).mp4
[debug] Default format spec: bestvideo+bestaudio/best
[index 3] Phantogram - Fall In Love (Official Music Video).mp4
[debug] Default format spec: bestvideo+bestaudio/best
[index 4] Never Going Home.mp4
[debug] Default format spec: bestvideo+bestaudio/best
[index 5] The Day You Died.webm
[debug] Default format spec: bestvideo+bestaudio/best
[index 6] Howling At The Moon.mp4
[debug] Default format spec: bestvideo+bestaudio/best
[index 7] Bad Dreams.mp4
[debug] Default format spec: bestvideo+bestaudio/best
[index 8] Phantogram 'Bill Murray' [Official Audio].webm
[debug] Default format spec: bestvideo+bestaudio/best
[index 9] I Don’t Blame You.webm
[debug] Default format spec: bestvideo+bestaudio/best
[index 10] Celebrating Nothing.webm
[debug] Default format spec: bestvideo+bestaudio/best
[index 11] My Only Friend.webm
```

**Comment by s104346** [comment]
@lkintact use `%(playlist_index)s` instead of `%(playlist_index)d`

**Comment by lkintact** [comment]
@s104346 Thank you, with `s` it worked as described.

I think it's "playlist_index _(numeric)_" in the [documentation](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#output-template) that confused me. Maybe since "playlist_index" only works as described if formatted as a string, it should given as "playlist_index _(string)_"?

**Comment by lkintact** [comment]
@remitamine What do you think about the last paragraph in my post above?

**Comment by remitamine** [comment]
no, the data type of value is an integer/numeric not a string. [all the examples](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#output-template-examples) already use the syntax that I showed you here.
