### ISSUE TITLE
YouTube Auth Fails

### ISSUE THREAD

**Issue by scorpion7-7** [ytdl-org/youtube-dl#26191]
Output:

Type account password and press [Return]: 
[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 404: Not Found

Tried both "username" and email address - both fail.

**Comment by dnascimb** [comment]
I've never gotten the authentication to work correctly, either. It would be helpful to have more explicit instructions on how to ensure success.

Here is my latest attempt, which was unsuccessful.

`MacBook-Pro:Downloads dan$ youtube-dl --config-location ~/yt/video_capture.config https://www.youtube.com/playlist?list=FL5jE-j35jnm5f8UU7FI8bgg --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: [u'--netrc', u'-f', u'bestvideo+bestaudio', u'--write-description', u'--write-info-json', u'--write-annotations', u'--write-all-thumbnails', u'--write-sub', u'--write-auto-sub', u'--all-subs', u'-o', u'%(uploader)s - %(playlist)s/%(playlist_index)s - %(uploader)s - %(title)s - %(upload_date)s.%(ext)s']
[debug] Command-line args: [u'--config-location', u'/Users/dan/yt/video_capture.config', u'https://www.youtube.com/playlist?list=FL5jE-j35jnm5f8UU7FI8bgg', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.12.25
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.2.1, ffprobe 4.2.1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Looking up account info
WARNING: Unable to look up account info: HTTP Error 404: Not Found
[youtube:playlist] FL5jE-j35jnm5f8UU7FI8bgg: Downloading webpage
ERROR: This playlist is private, use --username or --netrc to access it.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2814, in _real_extract
    has_videos, playlist = self._extract_playlist(playlist_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2737, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist is private, use --username or --netrc to access it.
`

Any assistance is greatly appreciated.

**Comment by dnascimb** [comment]
@dstftw Can you tag the duplicate issue for reference?

**Comment by scorpion7-7** [comment]
Just FYI - the version is the 2020.07.28.  Looking through previously closed (and open) - did not find another instance pertaining to this issue where the auth fails and the site is youtube.  Manually specifying parameters via CLI and it fails.  Am also curious of the duplicate so that it can be followed.

**Comment by spiralofhope** [comment]
@dstftw I also can't find an open issue on this topic.

I saw this on an age restricted video and I also couldn't get the login working via a parameter or netrc functionality.

I do see that I have an earlier version of `youtube-dl` though.


``` bash
youtube-dl -u spiralofhope@gmail.com jn007jVct0o --verbose
```

<details>
 <summary>Click to expand</summary>

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'jn007jVct0o', u'--verbose']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-9-amd64-x86_64-with-debian-10.0
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 404: Not Found
[youtube] jn007jVct0o: Downloading webpage
ERROR: jn007jVct0o: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1893, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: jn007jVct0o: YouTube said: Unable to extract video data
```
</details>

**Comment by a-raccoon** [comment]
Need an issue number / solution number to this duplicate issue.  Can open up a new issue to collect this information if that's required.
