### ISSUE TITLE
youtube-dl output

### ISSUE THREAD

**Issue by Jochen-sys** [ytdl-org/youtube-dl#26217]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I want to build my own graphical interface for the youtube-dl, so I would like to know, in which scripts the output is written and how I can put this in my own graphicl interface. It would be enough to know in which script(s) the output order (I think it's a print order) is.

**Comment by dstftw** [comment]
Output is written to standard streams. You don't need to touch any source code.
