### ISSUE TITLE
Problem downloading from BBC iPlayer 

### ISSUE THREAD

**Issue by yugarian** [ytdl-org/youtube-dl#26213]
Trying to download a video from BBC Iplayer site.
I'm using that latest version of youtube-dl v 2020.07.28

C:\work>youtube-dl --geo-bypass --verbose https://www.bbc.co.uk/iplayer/episodes/m000kxw1/the-rise-of-the-murdoch-dynasty
[debug] System config: []
[debug] User config: ['-o', 'D:\\Users\\David\\My Documents\\Downloads\\youtube-dl\\%(title)s-%(id)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--geo-bypass', '--verbose', 'https://www.bbc.co.uk/iplayer/episodes/m000kxw1/the-rise-of-the-murdoch-dynasty']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[bbc.co.uk:iplayer:playlist] m000kxw1: Downloading webpage
WARNING: unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: m000kxw1
[bbc.co.uk:iplayer:playlist] playlist m000kxw1: Downloading 0 videos
[download] Finished downloading playlist: m000kxw1

C:\work>

**Comment by ilike2burnthing** [comment]
Try the programmes page instead - https://www.bbc.co.uk/programmes/m000kxw1/episodes/player

**Comment by yugarian** [comment]
Thanks for your response.  That gives me a usable URL.

 

The BBC is Geo Blocking, and the available youtube-dl options seem to have no effect. I’m using a VPN (PIA) with a server in the UK.  Any workaround?

 

 

C:\work>youtube-dl  --geo-bypass-country GB --verbose https://www.bbc.co.uk/programmes/m000l9yp

[debug] System config: []

[debug] User config: ['-o', 'D:\\Users\\David\\My Documents\\Downloads\\youtube-dl\\%(title)s-%(id)s.%(ext)s']

[debug] Custom config: []

[debug] Command-line args: ['--geo-bypass-country', 'GB', '--verbose', 'https://www.bbc.co.uk/programmes/m000l9yp']

[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252

[debug] youtube-dl version 2020.07.28

[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362

[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2

[debug] Proxy map: {}

[debug] Using fake IP 25.254.125.113 (GB) as X-Forwarded-For.

[bbc.co.uk] m000l9yp: Downloading video page

[bbc.co.uk] m000l9yp: Downloading playlist JSON

[bbc.co.uk] m000l9yn: Downloading media selection XML

[bbc.co.uk] m000l9yn: Downloading media selection XML

ERROR: bbc.co.uk returned error: geolocation

Traceback (most recent call last):

  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 797, in extract_info

  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 530, in extract

  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\bbc.py", line 590, in _real_extract

  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\bbc.py", line 486, in _download_playlist

  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\bbc.py", line 362, in _download_media_selector

  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\bbc.py", line 349, in _raise_extractor_error

youtube_dl.utils.ExtractorError: bbc.co.uk returned error: geolocation

 

 

C:\work> 

 

Regards

**Comment by ilike2burnthing** [comment]
Use the VPN but remove --geo-bypass / --geo-bypass-country

**Comment by dirkf** [comment]
Seems that this has been answered and should be closed: @yugarian ?
