### ISSUE TITLE
youtube-dl output in graphical interface

### ISSUE THREAD

**Issue by Jochen-sys** [ytdl-org/youtube-dl#26216]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
How can I put the youtube-dl output in a graphical interface? I always get the output in a normal terminal window, but I want the output in a graphical interface. How can I do that?

**Comment by dstftw** [comment]
There is no graphical interface.
