### ISSUE TITLE
ytsearchdateall only returns the first page (20 videos) of results

### ISSUE THREAD

**Issue by ledmaster** [ytdl-org/youtube-dl#26219]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

[youtube:search:date] query "machine learning": Downloading page 1
[download] Downloading playlist: machine learning
[youtube:search:date] playlist machine learning: Collected 20 video ids (downloading 20 of them)
[download] Downloading video 1 of 20
[youtube] UhU29HoyCUk: Downloading webpage
[youtube] UhU29HoyCUk: Downloading m3u8 information
[youtube] UhU29HoyCUk: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 2 of 20
[youtube] GyI3WE5PKpY: Downloading webpage
[youtube] GyI3WE5PKpY: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 3 of 20
[youtube] fDNmxbh6prM: Downloading webpage
[youtube] fDNmxbh6prM: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 4 of 20
[youtube] 6Uv9AvFP844: Downloading webpage
[youtube] 6Uv9AvFP844: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 5 of 20
[youtube] Sh4liFq-mOo: Downloading webpage
[youtube] Sh4liFq-mOo: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 6 of 20
[youtube] 4aLAlfmBEEM: Downloading webpage
[youtube] 4aLAlfmBEEM: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 7 of 20
[youtube] M1hTjmzbza8: Downloading webpage
[youtube] M1hTjmzbza8: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 8 of 20
[youtube] aQ5lwcFprhI: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 9 of 20
[youtube] xS3_b0BsSes: Downloading webpage
[youtube] xS3_b0BsSes: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 10 of 20
[youtube] vgM16UvHbZQ: Downloading webpage
[youtube] vgM16UvHbZQ: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 11 of 20
[youtube] d7wmrnlLisw: Downloading webpage
[youtube] d7wmrnlLisw: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 12 of 20
[youtube] 7QBhBlBJzjI: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 13 of 20
[youtube] rVrhuuGKxuM: Downloading webpage
[youtube] rVrhuuGKxuM: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 14 of 20
[youtube] C8s7_FZJlrA: Downloading webpage
[youtube] C8s7_FZJlrA: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 15 of 20
[youtube] pDw_JHHvj-0: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 16 of 20
[youtube] uYqlBUfVFik: Downloading webpage
[youtube] uYqlBUfVFik: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 17 of 20
[youtube] 60c4rMq-aH0: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 18 of 20
[youtube] yoLpcelanpI: Downloading webpage
[youtube] yoLpcelanpI: Downloading m3u8 information
[youtube] yoLpcelanpI: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 19 of 20
[youtube] TmYKQZQTgjE: Downloading webpage
[youtube] TmYKQZQTgjE: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 20 of 20
[youtube] yfIOBHkS3yk: Downloading webpage
[youtube] yfIOBHkS3yk: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Finished downloading playlist: machine learning

## Description

WRITE DESCRIPTION HERE

I am trying to use "ytsearchdate" to get videos sorted by uploaded date, but it only returns the first page (20 videos) of results.

Tried "ytsearchdateall" and still have the same behavior.

The code:

ydl = youtube_dl.YoutubeDL({"ignoreerrors": False, 'verbose':True})
query="machine+learning"
ydl.extract_info("ytsearchdateall:{}".format(query), download=False) 

Youtube-dl is updated to the latest version.

Thanks for the help.

**Comment by PanderTech** [comment]
This is happening to me w/ ytsearchall as well. Please fix this!

**Comment by JpMCarrilho** [comment]
Same here!

**Comment by claudineien** [comment]
This is happening to me too. How can we use extract_info from youtube-dl to extract 30, 40, 50 or more videos on the youtube page, please ?
