### ISSUE TITLE
video fine but no sound ...

### ISSUE THREAD

**Issue by Albretch** [ytdl-org/youtube-dl#26225]
## Checklist

- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

 I think the IT people at work are messing with my silly youtube-dl script:

 time(python ./youtube-dl --user-agent "${_RNDM_UA}" --no-progress --no-call-home --continue --ignore-errors --no-overwrites  --format "bestvideo[ext=mp4]/best" --write-auto-sub  --write-sub --sub-lang "${_Ls}" --write-info-json --output "${_ODIR}/%(uploader)s/%(id)s.%(ext)s" "${_YT_URI}") >> "${_LOG_FL}" 2>&1
 
 the only minimally fancy thing in that one liner is that I am randomly timing the hits and randomly setting user agent from defined ones in order to tickle youtube a bit.

 Vidoes are fine but without audio.

 What I see when I try to watch the videos using vlc ist:
 
 [00007f2154c17ac8] core demux error: option sub-original-fps does not exist
 [00007f2154c1b338] core demux error: option sub-original-fps does not exist
 [00007f2154c1f3b8] core demux error: option sub-original-fps does not exist
 
 I think what they are doing on the proxy is messing with the connection when the browser user agent doesn't match the one installed on the laptops at work, but they could have gone way more sophiticated than that since they own and monitor those laptops 24x7
 
 How would be the script to download just the audio and merge it to the corresponding video, probably even offline? (I mostly use Debian Linux)

 Would renaming all downloaded media files as ".mp4.part" and starting the download again to complete the audio track work?
 
 Any suggestions?
 
 lbrtchx

**Comment by s104346** [comment]
`--format "bestvideo[ext=mp4]/best"` will only download the best video-only stream, but no audio stream. You should use something like
`--format "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"` instead (taken from https://github.com/ytdl-org/youtube-dl#format-selection-examples)

**Comment by Albretch** [comment]
but, as you suggest, if I use:

--format "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" 

youtube-dl will download two separate files which you may not be able to merge if you run youtube-dl in a Linux machine at work which you can't change, to which you have to admin access to.

 So, what should I do? How can I append to audio to the already downloaded videos?

 Thank you

**Comment by Albretch** [comment]
OK, I tried the --format setting you suggested on a Windows box and got two files to be then merged. Exactly the problem I am trying to avoid!

...>youtube-dl.exe --user-agent "Mozilla/5.0 (Windows NT 6.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0" --no-progress --no-call-home --continue --ignore-errors --no-overwrites --format "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --write-auto-sub --write-sub --sub-lang "de,de,es" --write-info-json --output "%(uploader)s\%(id)s.%(ext)s" "Ecd4M9GdGQU"
[youtube] Ecd4M9GdGQU: Downloading webpage
[youtube] Ecd4M9GdGQU: Downloading js player e49bfb00
[youtube] Ecd4M9GdGQU: Downloading js player e49bfb00
WARNING: video doesn't have subtitles
[youtube] Ecd4M9GdGQU: Looking for automatic captions
WARNING: Couldn't find automatic captions for Ecd4M9GdGQU
[youtube] Ecd4M9GdGQU: Downloading MPD manifest
[info] Writing video description metadata as JSON to: ...\Dawid Pisko\Ecd4M9GdGQU.info.json
WARNING: You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
[dashsegments] Total fragments: 144
[download] Destination: ...\Dawid Pisko\Ecd4M9GdGQU.f137.mp4
[download] Download completed
[dashsegments] Total fragments: 183
[download] Destination: ...\Dawid Pisko\Ecd4M9GdGQU.f140.m4a
[download] Download completed

...>dir "...\Dawid Pisko"
 Volume in drive C has no label.
 Volume Serial Number is 3EB7-0F25

 Directory of Dawid Pisko

08/05/2020  12:39 PM    <DIR>          .
08/05/2020  12:39 PM    <DIR>          ..
08/05/2020  12:36 PM        57,423,941 Ecd4M9GdGQU.f137.mp4
08/05/2020  12:39 PM        14,422,743 Ecd4M9GdGQU.f140.m4a
08/05/2020  12:35 PM           158,508 Ecd4M9GdGQU.info.json
               3 File(s)     72,005,192 bytes
               2 Dir(s)  169,623,977,984 bytes free

...>

 Again, at times I have to work on machines on which I can't install ffmpeg or avconv. So, my questions are still open.

 1) How can I download the best mp4 formated videos with the best audio to that video at once. No merging necessary.

 2) If I find a video without its corresponging audio. How can youtube-dl "continue" the download and then automatically merge the audio? Is that possible?

 thanks,
 lbrtchx

**Comment by RandomContributor** [comment]
build ffmpeg statically and get the binaries on your work pc.

**Comment by lengland** [comment]
If your machine allows you to use Docker, there is a [container for ffmpeg](https://hub.docker.com/r/opencoconut/ffmpeg) that I use at home. 
This will allow you to run the merge outside of youtube-dl, and still produce the same result
