### ISSUE TITLE
TikTok download support

### ISSUE THREAD

**Issue by HACKER-3000** [ytdl-org/youtube-dl#26229]
## Checklist

- [ x] I'm reporting a feature request
- [ x] I've verified that I'm running youtube-dl version **2020.07.28**
- [ x] I've searched the bugtracker for similar feature requests including closed ones

## Description

i think tiktok is large engouth to be featured here. extraction is not hard. just search for the <video> tag and download the src="URL Here" url.

**Comment by selfisekai** [comment]
tiktok is already supported: https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/tiktok.py

**Comment by HACKER-3000** [comment]
huh? I gave ytdl a tiktok url and id sid this:

```
$ youtube-dl "https://www.tiktok.com/@jamesfitzpatrick18/video/6755110763435691269"

[generic] 6755110763435691269: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6755110763435691269: Downloading webpage
[generic] 6755110763435691269: Extracting information
ERROR: Unsupported URL: https://www.tiktok.com/@jamesfitzpatrick18/video/6755110763435691269
```

**Comment by llacb47** [comment]
Duplicate and will be closed as such. Learn to search the issue tracker.

**Comment by selfisekai** [comment]
ok, made some research, this is an issue - tiktok changed their url scheme. still, it's a duplicate of #23264

**Comment by HACKER-3000** [comment]
thx
