### ISSUE TITLE
Downloading youtube playlist gives output "Collected 0 video ids"

### ISSUE THREAD

**Issue by alex4200** [ytdl-org/youtube-dl#26228]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-i', '-x', '--audio-format', 'mp3', 'https://www.youtube.com/watch?list=RDQM-gmCAFpnGD4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.6.9 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] RDQM-gmCAFpnGD4: Downloading page 1 of Youtube mix
[download] Downloading playlist: RDQM-gmCAFpnGD4
[youtube:playlist] playlist RDQM-gmCAFpnGD4: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RDQM-gmCAFpnGD4
```

## Description

The command does not find the videos that are part of the playlist. It still seem to work for other playlists, while it does not work for other playlists (e.g. `RDEMHSpo_Uv9STIRtF73zMywLg`).

**Comment by selfisekai** [comment]
you're trying to download a youtube mix playlist generated for your account. you need to be logged in to that account on youtube-dl with `--username` and `--password` or `--netrc` ([guide to .netrc file](https://github.com/ytdl-org/youtube-dl#authentication-with-netrc-file))

**Comment by alex4200** [comment]
@selfisekai I just checked, and I have the problem even with a 'mix' when I am not logged in to youtube. I get a `list` parameter in the URL for which the download does not work. 

I tried to add that mix as a playlist to my playlists, but I still cannot download it. I also cannot change the visibility of that new playlist, as it does not show up in Youtube Studio. 

I also can copy-and-paste the EXACT link to a new private browser window where I am not logged in (e.g. `https://www.youtube.com/watch?v=yzTuBuRdAyA&list=RDEMHSpo_Uv9STIRtF73zMywLg`) and I get the same mix!

And youtube-dl does not see to have an option to download a 'mix'. 

I tried to add that mix as a playlist to my playlists, but I still cannot download it. I also cannot change the visibility of that new playlist, as it does not show up in Youtube Studio. 

So it cannot be something connected to an account! Please re-open this ticket!
