### ISSUE TITLE
[tvp] vue sites

### ISSUE THREAD

**Issue by selfisekai** [ytdl-org/youtube-dl#26238]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
 laura@iino  ~/Videos  youtube-dl -v https://opole.tvp.pl/35308653/wiceminister-sprawiedliwosci-z-wizyta-w-swojej-szkole
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://opole.tvp.pl/35308653/wiceminister-sprawiedliwosci-z-wizyta-w-swojej-szkole']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.4 (CPython) - Linux-5.7.11_1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[tvp] 35308653: Downloading webpage
[tvp:embed] 35308653: Downloading webpage
ERROR: tvp:embed said: Transmisja została zakończona lub materiał niedostępny
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/tvp.py", line 128, in _real_extract
    raise ExtractorError('%s said: %s' % (
youtube_dl.utils.ExtractorError: tvp:embed said: Transmisja została zakończona lub materiał niedostępny
```

## Description

tvp videos often use a different id than the one in the url, it must be extracted from the webpage.

this website uses client-side js framework for rendering (vue.js specifically) and so, is not working with the current html regexes. the video id and other data must be extracted from the `window.__newsData` object defined in the document.

also, this site uses TVPlayer2 api instead of legacy TVPlayer (implemented by ytdl in TVPEmbedIE), but it seems it still works well - try `tvp:35308663` for the url above.

seems to only apply to the regional TVP3 pages - 17 subdomains, they could use a new extractor as well

**Comment by selfisekai** [comment]
@dstftw duplicate of?

**Comment by aucampia** [comment]
@selfisekai I think this is a dupe of https://github.com/ytdl-org/youtube-dl/issues/22160

**Comment by selfisekai** [comment]
that's a different case. that one is about the new player being used (new URL scheme in iframes), this one is about a specific group of sites (client-side rendered ones) that create a need to parse a JSON object.
