### ISSUE TITLE
Crunchyroll No video formats found

### ISSUE THREAD

**Issue by federicorosso1993** [ytdl-org/youtube-dl#26233]
## Checklist

- [ X] I'm reporting a broken site support
- [ X] I've verified that I'm running youtube-dl version **2020.07.28**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe https://www.crunchyroll.com/the-god-of-high-school/episode-4-marriagebonds-796231 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.crunchyroll.com/the-god-of-high-school/episode-4-marriagebonds-796231', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, rtmpdump 2.3
[debug] Proxy map: {}
[crunchyroll] 796231: Downloading webpage
[crunchyroll] 796231: Downloading adaptive_hls-audio-jaJP-hardsub-ptBR information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[crunchyroll] 796231: Downloading adaptive_hls-audio-jaJP information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[crunchyroll] 796231: Downloading adaptive_hls-audio-jaJP-hardsub-ruRU information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[crunchyroll] 796231: Downloading adaptive_hls-audio-jaJP-hardsub-frFR information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[crunchyroll] 796231: Downloading adaptive_hls-audio-jaJP-hardsub-arME information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[crunchyroll] 796231: Downloading adaptive_hls-audio-jaJP-hardsub-deDE information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[crunchyroll] 796231: Downloading adaptive_hls-audio-jaJP-hardsub-itIT information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[crunchyroll] 796231: Downloading adaptive_hls-audio-jaJP-hardsub-esLA information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[crunchyroll] 796231: Downloading adaptive_hls-audio-jaJP-hardsub-esES information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[crunchyroll] 796231: Downloading adaptive_hls-audio-jaJP-hardsub-enUS information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[crunchyroll] 796231: Downloading media info for 360p
[crunchyroll] 796231: Downloading stream info for 360p
[crunchyroll] 796231: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[crunchyroll] 796231: Downloading media info for 720p
[crunchyroll] 796231: Downloading stream info for 720p
[crunchyroll] 796231: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[crunchyroll] 796231: Downloading media info for 480p
[crunchyroll] 796231: Downloading stream info for 480p
[crunchyroll] 796231: Downloading media info for 1080p
[crunchyroll] 796231: Downloading stream info for 1080p
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\crunchyroll.py", line 574, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Cannot download anything from crunchyroll. Not even with a cookie file and user-agent. I think the problem could be the new beta that changed the video format or something like that, but that's just guessing, I'm not sure the beta does anything for the old site even the url are different (for example https://beta.crunchyroll.com/watch/GRNV437G6/marriagebonds).

**Comment by ImVantexHD** [comment]
![S1](https://user-images.githubusercontent.com/53190994/89236563-9ca73c00-d5f9-11ea-97f5-254f4d6d9a23.png)
It still works for me, seems like the exe is not working anymore
try to install from the source code

**Comment by ImVantexHD** [comment]
Also you can try to upgrade your python version from 3.4.4 to 3.8.x Maybe this is the problem?

**Comment by federicorosso1993** [comment]
> Also you can try to upgrade your python version from 3.4.4 to 3.8.x Maybe this is the problem?

On windows python is embedded into the binary.
I will try to install it from the source but I'm not sure I will be able to do it.

**Comment by federicorosso1993** [comment]
Ok this is strange but with --prefer-ffmpeg --no-check-certificate it's working for some reason (not all the times, but by tring 2-3 times I can download it), however I copied some files in the youtube-dl folder, including the updated ffmpeg static library, a not used python38.dll (the log still say python 3.4.4), and some files from the python 3.8.5 zip. Not really sure what I've done really maybe with this setup it was working before but only failed some times.
Still I think there is something wrong right now.

**Comment by ImVantexHD** [comment]
`--prefer-ffmpeg --no-check-certificate` This seems to work only with the non-premium content, for exemple if you try to log in with `-u .......@gmail.com -p ............` it will give you the same error.

**Comment by federicorosso1993** [comment]
> `--prefer-ffmpeg --no-check-certificate` This seems to work only with the non-premium content, for exemple if you try to log in with `-u .......@gmail.com -p ............` it will give you the same error.

For premium content I suggest you to use both a cookie.txt file and a user agent string. it should work this way (at least it's working for me). I always also use username and password because sometimes it's the other way around (past updates).
I created a personal frontend with a webview that do that for me but you can do it manually, just remeber to log out and log in, and create a new cookie.txt each time (it will expire after a few hours).

**Comment by ImVantexHD** [comment]
> I will try to install it from the source but I'm not sure I will be able to do it.

This also happens with the source code, so for the moment you can download only the non-premium content.
I'm not an expert but I suppose that crunchyroll made some changes to their site, so the only logical thing is that the extractor from crunchyroll.py got broken.
In fact it has not been updated since 3 months 
![1](https://user-images.githubusercontent.com/53190994/89294678-85ebfe00-d668-11ea-8bab-3ab57630b15d.png)

**Comment by federicorosso1993** [comment]
> > I will try to install it from the source but I'm not sure I will be able to do it.
> 
> This also happens with the source code, so for the moment you can download only the non-premium content.
> I'm not an expert but I suppose that crunchyroll made some changes to their site, so the only logical thing is that the extractor from crunchyroll.py got broken.
> In fact it has not been updated since 3 months
> ![1](https://user-images.githubusercontent.com/53190994/89294678-85ebfe00-d668-11ea-8bab-3ab57630b15d.png)

like I said the problem is not that you cannot download premium content (you can with the cookies and user agent instead of username password), the problem is that it fail to download with the embedded python version even for free content
