### ISSUE TITLE
Youtube videos repoted as "video only", no audio

### ISSUE THREAD

**Issue by captain-majid** [ytdl-org/youtube-dl#26235]
1st I'm sorry for not following the template rules, but I'm using v2020/7/28, and nothing weird, I promise.

When downloading this vid: https://www.youtube.com/watch?v=MCEfUVykbeI using format code:137, it has no audio !!!
The video HAS audio for this format, I've also tried IDM plugin and it works fine:
https://i.imgur.com/78jFJpS.png

[youtube] MCEfUVykbeI: Downloading webpage
[youtube] MCEfUVykbeI: Downloading MPD manifest
[info] Available formats for MCEfUVykbeI:
format code  extension  resolution note
139          m4a        audio only DASH audio   50k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
140          m4a        audio only DASH audio  129k , m4a_dash container, mp4a.40.2@128k (44100Hz)
251          webm       audio only DASH audio  150k , webm_dash container, opus @160k (48000Hz)
160          mp4        256x144    DASH video  108k , mp4_dash container, avc1.4d400b, 30fps, video only
133          mp4        426x240    DASH video  242k , mp4_dash container, avc1.4d400c, 30fps, video only
134          mp4        640x360    DASH video  288k , mp4_dash container, avc1.4d401e, 30fps, video only
135          mp4        854x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 30fps, video only
136          mp4        1280x720   DASH video 2310k , mp4_dash container, avc1.4d4016, 30fps, video only
298          mp4        1280x720   DASH video 3465k , mp4_dash container, avc1.4d4016, 60fps, video only
137          mp4        1920x1080  DASH video 4331k , mp4_dash container, avc1.64001e, 30fps, video only
299          mp4        1920x1080  DASH video 5775k , mp4_dash container, avc1.64001e, 60fps, video only
18           mp4        640x360    360p  338k , avc1.42001E, 30fps, mp4a.40.2@ 96k (44100Hz), 12.24MiB
22           mp4        1280x720   720p 1040k , avc1.64001F, 30fps, mp4a.40.2@192k (44100Hz) (best)

**Comment by s104346** [comment]
Read https://github.com/ytdl-org/youtube-dl#format-selection

**Comment by ImVantexHD** [comment]
youtube-dl -f 137+251 https://www.youtube.com/watch?v=MCEfUVykbeI
This should work

**Comment by captain-majid** [comment]
@ImVantexHD, It didn't work, just downloads separate video+audio files.
I know about the format codes, but as I've stated earlier with IDM plugin it works fine 1080p 60fps, but with Youtube-dl the max I have is:
22 mp4 1280x720 720p 1040k , avc1.64001F, 30fps, mp4a.40.2@192k (44100Hz) (best)

Which is not the (best)
