### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ce4aser** [ytdl-org/youtube-dl#26243]
`youtube-dl -U
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: youtube-dl's self-update mechanism is disabled on Debian.
Please update youtube-dl using apt(8).
See https://packages.debian.org/sid/youtube-dl for the latest packaged version.
`
1.) Ubuntu 20.04 is not Debian.
2.) Repository is old. On ubuntu repository is version from march 2020. Disabled update is bad.
3.) Debian: su -c 'curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl ' , this is no problem.

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#how-do-i-update-youtube-dl
