### ISSUE TITLE
Update and download in one .bat file

### ISSUE THREAD

**Issue by greyboxgt** [ytdl-org/youtube-dl#26258]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

I am trying to make a script that would update my youtube-dl.exe and then download some titles. Here is my .bat file:

```
youtube-dl -U --no-check-certificate
mydownload.bat
```

The problem is that mydownload.bat command starts before the update is finished and the file handle is closed. Because access to youtube-dl.exe is denied at that time, I end up with my old youtube-dl.exe and new youtube-dl.exe.new. Is there a way to force mydownload.bat in the script to wait until the update process is finished?

**Comment by dstftw** [comment]
Read doc on batch files for whatever delay capabilities it provides.

**Comment by greyboxgt** [comment]
youtube-dl -U --no-check-certificate generates a batch file that I cannot control.
I can add some delay in mydownload.bat but this would be a guessing game.
