### ISSUE TITLE
ERROR: can't find the current version. Please try again later

### ISSUE THREAD

**Issue by alecxhunter** [ytdl-org/youtube-dl#26251]
For the past week whenever I try to use youtube-dl.exe it has been failing. In the past I would just update it by running **youtube-dl -U** but now when I try to update it says it cannot find the current version and to check back later. Is there something wrong on my end?

**Comment by sxflynn** [comment]
Please instead follow my issue which does the regular template and has verbose output. Please close this ticket.

#26260
