### ISSUE TITLE
[YouTube]: Playlist download fails.

### ISSUE THREAD

**Issue by RandomContributor** [ytdl-org/youtube-dl#26259]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u"-vcif'251/bestaudio/best'", u'https://www.youtube.com/playlist?list=PL9JuFiYPkN3kOw5BDfWQ6bqI8jo9R7Odp']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.17 (CPython) - Linux-5.4.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PL9JuFiYPkN3kOw5BDfWQ6bqI8jo9R7Odp: Downloading webpage
[download] Downloading playlist: Good Chiptune
[youtube:playlist] PL9JuFiYPkN3kOw5BDfWQ6bqI8jo9R7Odp: Downloading page #1
ERROR: u'content_html'
Traceback (most recent call last):
  File "../youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "../youtube-dl/youtube_dl/YoutubeDL.py", line 969, in process_ie_result
    ie_entries, playliststart, playlistend))
  File "../youtube-dl/youtube_dl/extractor/youtube.py", line 313, in _entries
    content_html = more['content_html']
KeyError: u'content_html'
```

## Description
Playlist download fails.

**Comment by RandomContributor** [comment]
Nevermind, I just realized my stupidity.

**Comment by moom0o** [comment]
Please tell us how you fixed it...

**Comment by redpiller** [comment]
How did you fixed it ???
because i'm trying to download all videos from a certain channel @ youtube and i get:
ERROR: u'content_html' all the time and none of the videos is getting downloaded

**Comment by itsnotmyfault1** [comment]
The way I fixed it was after looking at https://github.com/ytdl-org/youtube-dl/issues/25768 I added the 

`--playlist-start 1 --playlist-end 50`

flags, and it started downloading properly. When that batch is done I'll just do 

`--playlist-start 51 --playlist-end 100`
