### ISSUE TITLE
Downloading 0 videos YouTube History Playlist

### ISSUE THREAD

**Issue by whistletoe** [ytdl-org/youtube-dl#26255]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.07.28**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/feed/history', '--cookies', '~/cookies.txt', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.7.8 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:history] Youtube History: Downloading webpage
[download] Downloading playlist: Youtube History
[youtube:history] playlist Youtube History: Downloading 0 videos
[download] Finished downloading playlist: Youtube History
```

## Description

Downloading Youtube History doesn't work even after passing cookies, removing cache dir, or -i. No Http Error 400: Bad Request warning indicates log in is successful. Also, this isn't a brand account.

**Comment by acburk** [comment]
This is an actual issue, why do you keep closing them all as duplicates? I am passing cookies correctly, my watch later and liked playlist download just fine but my history playlist stopped working about a month ago. I have examined the html that YouTube-dl gets and it is a sign in page. There is something wrong with how YouTube-dl is authenticating with the history page specifically.
