### ISSUE TITLE
ERROR: unable to open for writing: [Errno 36] File name too long

### ISSUE THREAD

**Issue by frp** [ytdl-org/youtube-dl#26262]
Basically when downloading a video with the name that is unreasonably long and exceeds the limits on the length of the name, youtube-dl fails:

```
[download] Destination: <filenamme>
ERROR: unable to open for writing: [Errno 36] File name too long: "<filename>.part-Frag0.part
```

Please consider truncating the names that are unreasonably long or something like that.

**Comment by xliiv** [comment]
can you paste the original issue link?

**Comment by Mecrisp** [comment]
One example: youtube-dl https://twitter.com/kikyophoto/status/1402427616108290051
