### ISSUE TITLE
Suggestion: use ffmpeg to bypass audio-only speed throttling

### ISSUE THREAD

**Issue by w-henderson** [ytdl-org/youtube-dl#26271]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

When you download an audio only format, YouTube throttles the speed so a 3 minute song can take up to three minutes to download. This could be avoided by adding an optional parameter which would indicate to ytdl that it should download the audio and video stream into a temporary file, then use ffmpeg to extract the audio. This would be a lot easier than having to manually do it.

**Comment by dstftw** [comment]
Throttling is bypassed natively in the first place.

**Comment by w-henderson** [comment]
Then I'd like to report a bug because it's definitely not bypassed for me on the latest version

**Comment by dstftw** [comment]
There are no telepathists. Bother to read new issue template.
