### ISSUE TITLE
Call proxy server multiple times in python program

### ISSUE THREAD

**Issue by chaocharleswang** [ytdl-org/youtube-dl#26289]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I used youtube-dl with proxy server to get json output in my python program. I found my proxy server was called 3 times.

```
def parse_url(url):
    
    ydl_options = {
        "dump_single_json": True,
        "proxy": "http://xxxxxxx:80",
        "nocheckcertificate": True }
    
    with youtube_dl.YoutubeDL(ydl_options) as ydl:
        try:
            info = ydl.extract_info(url, download=False)
            return info
        except Exception as e:
            return {'error': str(e)}
```

START RequestId: xxxxxxxxxxxx Version: $LATEST
[youtube] aFkcAH-m9W0: Downloading webpage
[youtube] aFkcAH-m9W0: Downloading js player c0a91787
[youtube] aFkcAH-m9W0: Downloading js player c0a91787
END RequestId: xxxxxxxxxxxx

However, if I call youtube-dl in my terminal like this:

`youtube-dl -J https://www.youtube.com/watch?v=aFkcAH-m9W0 --proxy http://xxxxxxx:80`

I tested that my proxy server was only called once.

How can I modify my python code to only call proxy server once? It will save much money.

**Comment by dstftw** [comment]
Do not touch youtube-dl's cache.

**Comment by chaocharleswang** [comment]
> Do not touch youtube-dl's cache.

I set `"cachedir": False` in Python. However, it still did not work. Can you please send me some details?
