### ISSUE TITLE
Youtube learning playlist segments output template

### ISSUE THREAD

**Issue by guptadd** [ytdl-org/youtube-dl#26298]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

What's the output template of playlist segments?

![www youtube com_playlist_list=PLG49S3nxzAnmpdmX7RoTOyuNJQAb-r-gd](https://user-images.githubusercontent.com/1687072/89902892-a38b0b80-dc04-11ea-9565-e1036a6cb9b2.png)

**Comment by kwapster** [comment]
Same issue, this is a youtube learning playlist which is a bit different than regular youtube playlists.

how do we get youtubedl, to arrange the sub topics in folders?
