### ISSUE TITLE
vk.com is now broken

### ISSUE THREAD

**Issue by AjvarXX** [ytdl-org/youtube-dl#26296]
## Checklist

- [ 1] I'm reporting a broken site support
- [ 2] I've verified that I'm running youtube-dl version **2020.07.28**
- [ 3] I've checked that all provided URLs are alive and playable in a browser
- [ 4] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ 5] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose "https://vk.com/video-5525046_171264140?list=cac457b0cc129e734a"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://vk.com/video-5525046_171264140
?list=cac457b0cc129e734a']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[vk] -5525046_171264140: Downloading JSON metadata
ERROR: Unable to download JSON metadata: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\utils.py", line 2736, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
```

## Description

WRITE DESCRIPTION HERE
I use youtube-dl built in SVP (few weeks older version) which provided errors. But for verbose log I had to download lstest youtube-dl and launch it which I might have done wrong as there is different error now.

**Original problems were:**

**For embedded youtube video into vk.com (https://vk.com/video-5525046_171264140) :**
02:42:15.077 [i]: Tube: py-info: [vk] -5525046_171256944: Downloading JSON metadata
02:42:15.111 [W]: DownloadError(\ERROR: Unable to download JSON metadata: HTTP Error 405: Not Allowed (caused by <HTTPError 405: 'Not Allowed'>); please report this issue on [url]https://yt-dl.org/bug[/url] . Make sure you are using the latest version; see  [url]https://yt-dl.org/update[/url]  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\)

**For internal vk.com videos (https://vk.com/video-30022666_456239460) :**
...Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on [url]https://yt-dl.org/bug[/url] . Make sure you are using the latest version; see  [url]https://yt-dl.org/update[/url]  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\)

**Comment by TheRealDude2** [comment]
Works for me with the two examples. Maybe it's because certain TLS versions are not supported by your system?
