### ISSUE TITLE
How do I get the specific format down?

### ISSUE THREAD

**Issue by Wazowski1** [ytdl-org/youtube-dl#26292]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Hello,
How do I get the specific format down?
Example: In the mustard color box

Another thing like I do to put video in line, when finishing one that begins the other.?

Already very grateful.

![imagen](https://user-images.githubusercontent.com/30112536/89775072-0b423900-dad5-11ea-8f9b-11ee8e7f37f1.png)

**Comment by lengland** [comment]
To get a specific format, use the `-f` flag, followed by the id in the first column
eg 
```bash
youtube-dl -f 299 <URL>
```

As for downloading multiple videos, you can use the `--batch-file flag` 
From the help page:
```bash 
    -a, --batch-file FILE            File containing URLs to download ('-' for
                                     stdin), one URL per line. Lines starting
                                     with '#', ';' or ']' are considered as
                                     comments and ignored.
```

**Comment by Wazowski1** [comment]
Thx men
