### ISSUE TITLE
Resume download when download is interrupted

### ISSUE THREAD

**Issue by Wazowski1** [ytdl-org/youtube-dl#26307]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Hello,
Is there a way that when the download is interrupted for whatever reason it will try again in a few seconds later?
Since already very grateful with your answer
Regards

**Comment by dstftw** [comment]
Depends on what is meant by "interrupted".

**Comment by Wazowski1** [comment]
Hi **dstftw** 
Basically any connection error some blink.
