### ISSUE TITLE
Have --sleep-interval honor the --skip-download flag

### ISSUE THREAD

**Issue by petersjt014** [ytdl-org/youtube-dl#26319]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Earlier I opened an issue ( #26287 ) mentioning that the `--skip-download` flag seems to negate the `sleep-interval` flag. I noted that I considered it unexpected behavior, since flags like `write-info-json` do indeed download something.

The manual section for `--sleep-interval` describes it as "Number of seconds to sleep before each download when used alone [...]". I consider non-video files like the result of `--write-info-json` to be a 'download'; but it seems like not everyone agrees with this.

The main use for the sleep flag is to prevent 429 errors when doing bulk/continuous network requests, yet a command like:

``
youtube-dl --sleep-interval 10 --write-info-json --skip-download https://www.youtube.com/user/TheLinuxFoundation
``

Will eventually cause one, because no sleeping happens.

For that reason, I propose that `--sleep-interval` be honored for any network activity that downloads files, so as to improve the rate-limiting/429 prevention purpose it currently serves.

**Comment by dstftw** [comment]
This is already requested stop posting duplicates.

**Comment by petersjt014** [comment]
It's not. You closed the last one as invalid, stating that it's expected behavior and not a bug. I'm suggesting that the expected behavior be changed to better reflect the reason the flag is actually used. I've noted that in the description.

If it's not a bug _or_ a feature, please tell me how to properly file it.

**Comment by petersjt014** [comment]
Also of note: I'd be happy to implement this myself.
