### ISSUE TITLE
How can I resume a download ...

### ISSUE THREAD

**Issue by Wazowski1** [ytdl-org/youtube-dl#26313]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Hi all,
How can I resume a download due to some connection blink error.
Already very grateful for your responses.
Regards

**Comment by dstftw** [comment]
It's retried automatically `-R` times.

**Comment by Wazowski1** [comment]
Thx men.
