### ISSUE TITLE
Vimeo Showcase not downloading

### ISSUE THREAD

**Issue by migben01** [ytdl-org/youtube-dl#26329]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Hi,

Trying to bulk download a Vimeo Showcase https://vimeo.com/showcase/5013672

Youtube-dl gives me this error:

ERROR: Unable to extract bootstrap data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I can not extract any Vimeo Showcase - Why is that? How do I fix this?

thanks

**Comment by migben01** [comment]
I´m using the latest version and this is the verbose log:

[debug] System config: []

[debug] User config: []

[debug] Custom config: []

[debug] Command-line args: [u'--verbose', u'https://vimeo.com/showcase/5013672']

[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8

[debug] youtube-dl version 2020.07.28

[debug] Python version 2.7.16 (CPython) - Darwin-19.2.0-x86_64-i386-64bit

[debug] exe versions: none

[debug] Proxy map: {}

[vimeo:album] 5013672: Downloading webpage

ERROR: Unable to extract bootstrap data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Traceback (most recent call last):

File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info

ie_result = ie.extract(url)

File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract

ie_result = self._real_extract(url)

File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 952, in _real_extract

webpage, 'bootstrap data'), album_id)['viewer']

File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex

raise RegexNotFoundError('Unable to extract %s' % _name)

RegexNotFoundError: Unable to extract bootstrap data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by githubroro** [comment]
Hi, old question but it still not working today. Impossible to download a showcase on Vimeo. 
example: https://vimeo.com/showcase/******* 

Any solution please?

Thanks!
