### ISSUE TITLE
Add ability to log errors to a file

### ISSUE THREAD

**Issue by ntcarver0** [ytdl-org/youtube-dl#26323]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Could a feature be added so that errors encountered while downloading (failed downloads, ETC.) are logged to a file for perusal later? This would greatly help, as I have a script that downloads a large number of URLs and it's difficult to find if any failed.

**Comment by 0l-l0** [comment]
Could you a bit elaborate on what kind of script you use? I mean, what language the script is written in, how you invoke youtube-dl etc.

**Comment by ntcarver0** [comment]
@0l-l0, the script is a Windows batch script simply out of convenience because it was the quickest way for me to do what I needed to do. The script looks like this:

@echo off
youtube-dl -i --no-continue --add-metadata --write-description -o "%%(extractor)s/%%(uploader)s/%%(uploader)s - %%(upload_date)s - %%(title)s.%%(ext)s" -a links.txt

**Comment by 0l-l0** [comment]
How about I/O redirections? Don't they do the trick?
E.g.
```batch
@echo off
youtube-dl -i --no-continue --add-metadata --write-description ^
-o "%%(extractor)s/%%(uploader)s/%%(uploader)s - %%(upload_date)s - %%(title)s.%%(ext)s" ^
-a links.txt > your_log_file.log 2>&1
```

**Comment by ntcarver0** [comment]
That could work so long as the terminal output is logged and also printed to the terminal for monitoring.

**Comment by 0l-l0** [comment]
That's where embedded youtube-dl can help. I sketched this little python script based on your settings and the youtube-dl manual. In this case the log will be written to the file `youtube_dl.log` as well as to the terminal.

```python
import logging
import youtube_dl


class TeeLogger(object):
    def debug(self, msg):
        print(msg)
        logging.debug(msg)

    def warning(self, msg):
        print(msg)
        logging.warning(msg)

    def error(self, msg):
        print(msg)
        logging.error(msg)

def get_url_list(filename):
    batch_file = open(filename, 'r')

    url_list = []
    for line in batch_file:
        l = line.strip()
        if l and not l.startswith(('#', ';', ']')):
            url_list.append(l)

    return url_list

ydl_opts = {
    'addmetadata': True,
    'continuedl': False,
    'ignoreerrors': True,
    'logger': TeeLogger(),
    'outtmpl': '%(extractor)s/%(uploader)s/%(uploader)s - %(upload_date)s - %(title)s.%(ext)s',
    'writedescription': True,
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    logging.basicConfig(filename='youtube_dl.log', level=logging.NOTSET, format='')

    try:
        ydl.download(get_url_list('links.txt'))
    except:
        logging.exception('')
        raise
```

**Comment by 0l-l0** [comment]
An even shorter one without reinventing the wheel:
```python
import logging
import youtube_dl


class TeeLogger(object):
    def debug(self, msg):
        print(msg)
        logging.debug(msg)

    def warning(self, msg):
        print(msg)
        logging.warning(msg)

    def error(self, msg):
        print(msg)
        logging.error(msg)

ydl_opts = {
    'addmetadata': True,
    'continuedl': False,
    'ignoreerrors': True,
    'logger': TeeLogger(),
    'outtmpl': '%(extractor)s/%(uploader)s/%(uploader)s - %(upload_date)s - %(title)s.%(ext)s',
    'writedescription': True,
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    logging.basicConfig(filename='youtube_dl.log', level=logging.NOTSET, format='')

    try:
        batch_file = open('links.txt', 'r')
        ydl.download(youtube_dl.read_batch_urls(batch_file))
    except:
        logging.exception('')
        raise
```

**Comment by 0l-l0** [comment]
Of course, if you don't wanna use Python for this but you have PowerShell installed, you can use the [Tee-Object](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/tee-object) utility.

**Comment by ntcarver0** [comment]
@0l-l0, thanks for the scripts. It helps a lot.

**Comment by nara20** [comment]
Hi,

I understand that is possible using youtube-dl, but it should be much more easier, if youtube-dl provide a new argument to save log in a file in addition to the screen output...

Regards,
Nara
