### ISSUE TITLE
facebook not working anymore

### ISSUE THREAD

**Issue by ircopdd** [ytdl-org/youtube-dl#26346]
[facebook] 10221157471919956: Downloading webpage
[facebook] 10221157471919956: Downloading webpage
[facebook] 10221157471919956: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Teresaw87** [comment]
I encountered similar problem
