### ISSUE TITLE
[xhamster] No video format found again with patch #26254 and possible workaround

### ISSUE THREAD

**Issue by TheRealDude2** [ytdl-org/youtube-dl#26353]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-c', '--batch-file=/media/dl/dl.txt', '-o', '/media/dl/%(title)s %(id)s.%(ext)s', '-v']
[debug] Batch file urls: ['https://de.xhamster.com/videos/jeny-smith-xhR2sPF'']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Git HEAD: a4ed50bb8
[debug] Python version 3.7.3 (CPython) - Linux-5.4.51-v7+-armv7l-with-debian-10.4
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[XHamster] xhR2sPF: Downloading webpage
WARNING: [XHamster] xhR2sPF: Failed to parse JSON Unterminated string starting at: line 1 column 18367 (char 18366)
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/apadmin/git/youtube-dl_master/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/apadmin/git/youtube-dl_master/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/apadmin/git/youtube-dl_master/youtube_dl/extractor/xhamster.py", line 242, in _real_extract
    self._sort_formats(formats)
  File "/home/apadmin/git/youtube-dl_master/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I noticed a problem again with the RegEx for the site initials. As it looks like the web server has problems to deliver the line completely. On the other hand, the character ; appears more often in the line now. Maybe just a temporary problem.

Workaround:
I changed the line 141 of the xhamster.py from:
r'window\.initials\s*=\s*({.+?})\s*;', webpage, 'initials',
to
r'window\.initials\s*=\s*({.+?})\s*;<', webpage, 'initials',

But this time it is really only a workaround. I think it would be better to adjust the regular expression to parse everything from <script id='initials-script'> to the next </script> and not to use the ; character at the end of the regex.

**Comment by hitam4450** [comment]
Hi, i checked my xhamster.py and could not find any reference of window.initials to fix the problem !
regards, hitam4450

**Comment by TheRealDude2** [comment]
> 
> 
> Hi, i checked my xhamster.py and could not find any reference of window.initials to fix the problem !
> 
> I am on UBUNTU 18.04 LTS !
> regards, hitam4450

**Comment by TheRealDude2** [comment]
Oh, that was the wrong button. Wrongly close the issue. How can I open this issue again?

Hi hitam4450. It's line 141 in the latest xhamster.py. Some changes have been made here in the last weeks. Search in the line range 130-150.

Search for the block in the def _real_extract(self, url):
        initials = self._parse_json(
            self._search_regex(
                r'window\.initials\s*=\s*({.+?})\s*;', webpage, 'initials',
                default='{}'),
            video_id, fatal=false)

Translated with www.DeepL.com/Translator (free version)

**Comment by hitam4450** [comment]
This i found on line 117

r'window\.initials\s*=\s*({.+?})\s*;\s*\n', webpage, 'initials',

**Comment by hitam4450** [comment]
line 115 to 123
11            initials = self._parse_json(
116             self._search_regex(
117                 r'window\.initials\s*=\s*({.+?})\s*;\s*\n', webpage, 'initials',
118                 default='{}'),
119             video_id, fatal=False)
120         if initials:
121             video = initials['videoModel']
122             title = video['title']
123             formats = []

**Comment by TheRealDude2** [comment]
Yes that is the line without patch #26254.

**Comment by hitam4450** [comment]
I applied the patch..but NO Success!

**Comment by TheRealDude2** [comment]
Do you have the no video format found OR the unsupported url error.
If it is the last and your url ends with letter you have to apply https://github.com/ytdl-org/youtube-dl/pull/25804 also.

**Comment by TheRealDude2** [comment]
Seems to have really been a temporary problem. I just messed up with the original xhamster.py and it's working again for now.

**Comment by hitam4450** [comment]
I applied the patch..but NO Success!

**Comment by TheRealDude2** [comment]
Maybe you have another problem. I think it will be best if you open a new issue with your own log.

**Comment by TheRealDude2** [comment]
Today the error occurs again. If there are more cases, maybe a patch should be written.
It is noticeable in the log that the line error is always at a different character position and sometimes no problem occurs. But all very arbitrary. For example:

WARNING: [XHamster] xhJqAVs: Failed to parse JSON Unterminated string starting at: line 1 column 21345 (char 21344)

Abort of the script with error. 
Next run:
WARNING: [XHamster] xhJqAVs: Failed to parse JSON Unterminated string starting at: line 1 column 22785 (char 22784)
