### ISSUE TITLE
Cannot download HD from Youtube

### ISSUE THREAD

**Issue by Shoptasim** [ytdl-org/youtube-dl#26355]
## Checklist

- [ X] I'm asking a question
- [ X] I've looked through the README and FAQ for similar questions
- [ X] I've searched the bugtracker for similar questions including closed ones

## Question
Hello, I looked around the site for answers for my problem but could not find. Perhaps this is a unique issue in my program. 
I am trying to download the following - https://www.youtube.com/watch?v=WOTHEnNzqzM or https://www.youtube.com/watch?v=bjkCJC_Soyg
I get in return a low quality, both in video (360) and audio (96bps). Am I doing something wrong? I've read that by default the downloading would be at top quality. Also, with your permission, I am a bit perplexed on how to get the english subtitles along with the videos. I did try many combinations of command, but to no avail.

I thank you. 

WRITE QUESTION HERE

**Comment by Shoptasim** [comment]
What is incomplete with my question? Should I add anything? 
Thanks.

**Comment by ToaKraka** [comment]
YouTube provides HD video in multiple formats:

- Combined video+audio in a single file

- Separate files for video and audio

If you don't have ffmpeg installed, by default youtube-dl will download only the combined video+audio file, which is lower-quality than the separate video and audio files.

To get the separate video and audio files, you need to additionally install ffmpeg on your computer. Then, youtube-dl will automatically detect that you have ffmpeg installed, and use ffmpeg to automatically combine the separate video and audio files into a single video+audio file.

**Comment by Shoptasim** [comment]
Thank you so very much!
