### ISSUE TITLE
The videos can be saved in poor quality only. What is the purpose of this app then?

### ISSUE THREAD

**Issue by ARTeomo** [ytdl-org/youtube-dl#26356]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by mut-ex** [comment]
From youtube-dl manual:

>   FORMAT SELECTION
       By default youtube-dl tries to download the best available quality, i.e.  if you want the best quality you don't need to pass any special options, youtube-dl will guess it for you by default.

**Comment by nillith** [comment]
> From youtube-dl manual:
> 
> > FORMAT SELECTION
> > By default youtube-dl tries to download the best available quality, i.e.  if you want the best quality you don't need to pass any special options, youtube-dl will guess it for you by default.

This is not true. Just try downloading a random video on youtube. Probably be the one that is choosen when viewed in the browser that is downloaded.

**Comment by ARTeomo** [comment]
Yes, it works on linux systems without problem but not on windows.
