### ISSUE TITLE
tv.nrk.no broken

### ISSUE THREAD

**Issue by rkarlsba** [ytdl-org/youtube-dl#26369]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

root@smilla:~# cd /data/Movies/Serier/Det\ store\ postranet/
root@smilla:/data/Movies/Serier/Det store postranet# youtube-dl -v 'https://tv.nrk.no/serie/det-store-postranet/sesong/1/episode/1/avspiller'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://tv.nrk.no/serie/det-store-postranet/sesong/1/episode/1/avspiller']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 2.7.16 (CPython) - Linux-5.4.0-0.bpo.3-amd64-x86_64-with-debian-10.5
[debug] exe versions: avconv 4.1.6-1, avprobe 4.1.6-1, ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[NRKTVEpisode] det-store-postranet/sesong/1/episode/1: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'@id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/nrk.py", line 430, in _real_extract
    display_id)['@id']
KeyError: u'@id'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 543, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'@id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

root@smilla:/data/Movies/Serier/Det store postranet#

## Description

WRITE DESCRIPTION HERE
I tried, like earlier, to rip from NRK. This has worked like a charm for years.

alias nrkrip="youtube-dl --write-sub --sub-format ttml --convert-subtitles srt --embed-subs $@"

I've tried without the named arguments as well and the output above is with the defaults.

**Comment by llacb47** [comment]
you obviously did not check https://github.com/ytdl-org/youtube-dl/issues/25594

**Comment by rkarlsba** [comment]
Well, nothing new there that works, at least

**Comment by TheNorwegian** [comment]
May I add this: Around June, Youtube-DLG and the then latest version of Youtube-DL started to fail in downloading single episodes of NRK's drama selection. I could still download playlists, i.e. episodes 1-6 of 6 by simply pasting the playlist URL, not the episode URL. However, in August no downloading was possible of either playlists or episodes. 

The above pertains to drama series and other region locked programmes that NRK is not showing outside Norway. I am in Sweden, hence affected by regionblocking. As of today I can download NRK's own news and other non-regionblocked programmes from NRK TV.

Can we expect a fix in Y-DL? I am very untechnical, hence loving Y-DLG and Y-DL which has worked great on NRK (and SVT) for years.
