### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by Lemon-Hacking** [ytdl-org/youtube-dl#26362]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
```
DownloadError: ERROR: query "Lemon": Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)'))
```
This error coming with all videos, format options :
```
ytdl_format_options = {
    'format': 'bestaudio/best',
    'outtmpl': '%(extractor)s-%(id)s-%(title)s.%(ext)s',
    'restrictfilenames': True,
    'noplaylist': True,
    'nocheckcertificate': True,
    'ignoreerrors': False,
    'logtostderr': False,
    'quiet': True,
    'no_warnings': True,
    'default_search': 'auto',
    'source_address': '0.0.0.0',
    'proxy': 'socks5://127.0.0.1:9050'
}
```
Proxy is Tor, it was working fine a few minutes ago, what happened?

**Comment by Lemon-Hacking** [comment]
This got automatically fixed.

**Comment by jay3332** [comment]
https://stackoverflow.com/questions/64409218/youtube-dl-failed-to-parse-json
i need an answer on how to fix this.
