### ISSUE TITLE
Wrong Config Path and Custom Path.

### ISSUE THREAD

**Issue by Maikurosofuto** [ytdl-org/youtube-dl#26361]
- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
So, i don't know if i'm missing something or if it is really wrong. As said here `https://github.com/ytdl-org/youtube-dl#configuration` the config path is `%APPDATA%\youtube-dl\config.txt` but for some reason this path never worked for me, the correct one, at least for me, is `%APPDATA%\Roaming\youtube-dl\config.txt`. And is it possible to change the default location of the config file without having to specify a command manually every time? I tried to search for both of these doubts, but I didn't find anything totally related. If there are any, I apologize in advance.

**Comment by dstftw** [comment]
`%APPDATA%` is `.../AppData/Roaming` in the first place. You technically can't change something default since it's default and incorporated into binary.
