### ISSUE TITLE
ERROR: requested format not available

### ISSUE THREAD

**Issue by tellts** [ytdl-org/youtube-dl#26374]
Hello. Filenames in Russian. I wand to download the pleylist in 1080 quality.
Error command: youtube-dl -f 137+140 https://www.youtube.com/playlist?list=PLQAt0m1f9OHvyjJNjZK_unnLwMOXPTja8

`alex@alex-Latitude-D430:~$ youtube-dl -F https://www.youtube.com/watch?v=vMS82GUSKik
[youtube] vMS82GUSKik: Downloading webpage
[youtube] vMS82GUSKik: Downloading MPD manifest
[info] Available formats for vMS82GUSKik:
format code  extension  resolution note
139          m4a        audio only DASH audio   50k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k (44100Hz)
251          webm       audio only DASH audio  148k , webm_dash container, opus @160k (48000Hz)
278          webm       256x144    DASH video   95k , webm_dash container, vp9, 30fps, video only
160          mp4        256x144    DASH video  108k , mp4_dash container, avc1.4d400b, 30fps, video only
134          mp4        640x360    DASH video  206k , mp4_dash container, avc1.4d401e, 30fps, video only
242          webm       426x240    DASH video  220k , webm_dash container, vp9, 30fps, video only
133          mp4        426x240    DASH video  242k , mp4_dash container, avc1.4d400c, 30fps, video only
243          webm       640x360    DASH video  405k , webm_dash container, vp9, 30fps, video only
244          webm       854x480    DASH video  752k , webm_dash container, vp9, 30fps, video only
137          mp4        1920x1080  DASH video  768k , mp4_dash container, avc1.640028, 30fps, video only
135          mp4        854x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 30fps, video only
247          webm       1280x720   DASH video 1505k , webm_dash container, vp9, 30fps, video only
136          mp4        1280x720   DASH video 2310k , mp4_dash container, avc1.4d400a, 30fps, video only
248          webm       1920x1080  DASH video 2646k , webm_dash container, vp9, 30fps, video only
18           mp4        640x360    360p  159k , avc1.42001E, 30fps, mp4a.40.2@ 96k (44100Hz), 11.80MiB
22           mp4        1280x720   720p  263k , avc1.64001F, 30fps, mp4a.40.2@192k (44100Hz) (best)
alex@alex-Latitude-D430:~$ cd /media/alex/3270D9E970D9B3B7/Python/ООП/Егорофф/1080
alex@alex-Latitude-D430:/media/alex/3270D9E970D9B3B7/Python/ООП/Егорофф/1080$ youtube-dl -f 137+140 https://www.youtube.com/playlist?list=PLQAt0m1f9OHvyjJNjZK_unnLwMOXPTja8
[youtube:playlist] PLQAt0m1f9OHvyjJNjZK_unnLwMOXPTja8: Downloading webpage
[download] Downloading playlist: Объектно-ориентированное программирование (ООП) Python
[youtube:playlist] playlist Объектно-ориентированное программирование (ООП) Python: Downloading 34 videos
[download] Downloading video 1 of 34
[youtube] jtIq61A1LLw: Downloading webpage
ERROR: requested format not available
alex@alex-Latitude-D430:/media/alex/3270D9E970D9B3B7/Python/ООП/Егорофф/1080$`

**Comment by tellts** [comment]
Sorry, I did not immediately figure out that different videos in the playlist require different settings. And how to download all videos from the playlist automatically in 1080 quality in this case?

**Comment by tellts** [comment]
Sorry, I did not immediately figure out that different videos in the playlist require different settings. And how to download all videos from the playlist automatically in 1080 quality in this case?

**Comment by tellts** [comment]
I mean that if some files with this quality are in the playlist, then they need to be downloaded in this way. And the rest with the other highest quality, slightly lower.

I want to do this not only in Linux, but in Windows too.

**Comment by tellts** [comment]
``C:\soft\youtube-dl>youtube-dl -f --merge-output-format mp4 bestvideo+bestaudio https://www.youtube.com/watch?v=vMS82GUSKik
ERROR: 'mp4' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:mp4" ) to search YouTube

**Comment by tellts** [comment]
https://www.cyberforum.ru/development/thread2686713-page2.html#post14789707

**Comment by tellts** [comment]
If the extension is for the mp4 audio and video parts, then they are glued together much faster than when the extension is webm. But this is not always the case with bestvideo + bestaudio.

**Comment by tellts** [comment]
This is if the final file format is needed mp4. Sorry to write new messages and not edit previous ones. I have an old version of the browser, do not allow me to do this.

**Comment by dstftw** [comment]
jtIq61A1LLw does not have 137 format.
