### ISSUE TITLE
YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by MrMudkip** [ytdl-org/youtube-dl#26389]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
Python version 3.8.5 - Windows 10 Home
youtube-dl version 2020.07.28

## Description

WRITE DESCRIPTION HERE
Whenever I try to use my play command (this is a discord.py project), it only takes one word from a video. Otherwise, it would come up with the "YouTube said: Unable to extract Video Data" error.

This is my options:
`    YTDL_OPTIONS = {
        'format': 'bestaudio',
        'extractaudio': True,
        'audioformat': 'mp3',
        'outtmpl': '%(extractor)s-%(id)s-%(title)s.%(ext)s',
        'restrictfilenames': True,
        'noplaylist': True,
        'nocheckcertificate': True,
        'ignoreerrors': True,
        'logtostderr': True,
        'quiet': True,
        'no_warnings': True,
        'default_search': 'ytsearch',
        'source_address': '0.0.0.0'
    }`

**Comment by ldexterldesign** [comment]
[Problematic] for me

[problematic]: https://www.youtube.com/watch?v=tLXYBXWUUxE

**Comment by ldexterldesign** [comment]
Yes, adding `--cookie` option fixed it

Once logged in, I used this [extension] to grab my cookies from the YouTube page

Hope this helps

Sincerely

[extension]: https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg

**Comment by MrMudkip** [comment]
I used a diffrent source, so this issue is (hopefully) fixed.
