### ISSUE TITLE
"Youtube said: unable to extract video data" on downloading a video with shock content waring notification

### ISSUE THREAD

**Issue by r00iner** [ytdl-org/youtube-dl#26384]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

youtube-dl.exe -v --extract-audio --audio-format mp3 https://youtu.be/hRow6G5wQIw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--extract-audio', '--audio-format', 'mp3', 'https://youtu.be/hRow6G5wQIw']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[youtube] hRow6G5wQIw: Downloading webpage
ERROR: hRow6G5wQIw: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\youtube.py", line 1893, in _real_extract
youtube_dl.utils.ExtractorError: hRow6G5wQIw: YouTube said: Unable to extract video data

## Description

WRITE DESCRIPTION HERE
Link https://youtu.be/hRow6G5wQIw
Tried running the program on the video with shock content notification and got this problem
ERROR: hRow6G5wQIw: YouTube said: Unable to extract video data

**Comment by cheatfreak47** [comment]
confirming this issue as well

**Comment by digbose92** [comment]
Facing the same issue

**Comment by antdude** [comment]
Thanks  nicolaasjan. I'll wait for the official binary. I hope it is very soon!

**Comment by nicolaasjan** [comment]
> Thanks nicolaasjan. I'll wait for the official binary. I hope it is very soon!

Since you are on Linux, compiling the binary is quite simple:
(of course run `make` after you applied the changes in `youtube.py`)
```
git clone https://github.com/ytdl-org/youtube-dl.git
cd youtube-dl
make
```

**Comment by antdude** [comment]
No luck on two boxes:

$ git clone https://github.com/ytdl-org/youtube-dl.git
Cloning into 'youtube-dl'...
remote: Enumerating objects: 98251, done.
remote: Total 98251 (delta 0), reused 0 (delta 0), pack-reused 98251
Receiving objects: 100% (98251/98251), 56.27 MiB | 21.13 MiB/s, done.
Resolving deltas: 100% (72379/72379), done.
Checking connectivity... done.
ant@ANTian:~/Downloads$ cd youtube-dl/
ant@ANTian:~/Downloads/youtube-dl$ ls
AUTHORS          devscripts  MANIFEST.in  test
bin              docs        README.md    tox.ini
ChangeLog        LICENSE     setup.cfg    youtube_dl
CONTRIBUTING.md  Makefile    setup.py     youtube-dl.plugin.zsh
ant@ANTian:~/Downloads/youtube-dl$ time make
mkdir -p zip
for d in youtube_dl youtube_dl/downloader youtube_dl/extractor youtube_dl/postprocessor ; do \
  mkdir -p zip/$d ;\
  cp -pPR $d/*.py zip/$d/ ;\
done
touch -t 200001010101 zip/youtube_dl/*.py zip/youtube_dl/*/*.py
mv zip/youtube_dl/__main__.py zip/
cd zip ; zip -q ../youtube-dl youtube_dl/*.py youtube_dl/*/*.py __main__.py
rm -rf zip
echo '#!/usr/bin/env python' > youtube-dl
cat youtube-dl.zip >> youtube-dl
rm youtube-dl.zip
chmod a+x youtube-dl
COLUMNS=80 /usr/bin/env python youtube_dl/__main__.py --help | /usr/bin/env python devscripts/make_readme.py
/usr/bin/env python devscripts/make_contributing.py README.md CONTRIBUTING.md
/bin/sh: 1: pandoc: not found
/bin/sh: 1: [: =: unexpected operator
pandoc -f markdown -t plain README.md -o README.txt
make: pandoc: Command not found
Makefile:92: recipe for target 'README.txt' failed
make: *** [README.txt] Error 127

real    0m2.448s
user    0m1.964s
sys     0m0.300s


$ git clone https://github.com/ytdl-org/youtube-dl.git
Cloning into 'youtube-dl'...
remote: Enumerating objects: 98251, done.
remote: Total 98251 (delta 0), reused 0 (delta 0), pack-reused 98251
Receiving objects: 100% (98251/98251), 56.28 MiB | 19.71 MiB/s, done.
Resolving deltas: 100% (72378/72378), done.
[ant@beta Downloads]$ cd youtube-dl/
[ant@beta youtube-dl]$ time make
mkdir -p zip
for d in youtube_dl youtube_dl/downloader youtube_dl/extractor youtube_dl/postprocessor ; do \
  mkdir -p zip/$d ;\
  cp -pPR $d/*.py zip/$d/ ;\
done
touch -t 200001010101 zip/youtube_dl/*.py zip/youtube_dl/*/*.py
mv zip/youtube_dl/__main__.py zip/
cd zip ; zip -q ../youtube-dl youtube_dl/*.py youtube_dl/*/*.py __main__.py
rm -rf zip
echo '#!/usr/bin/env python' > youtube-dl
cat youtube-dl.zip >> youtube-dl
rm youtube-dl.zip
chmod a+x youtube-dl
COLUMNS=80 /usr/bin/env python youtube_dl/__main__.py --help | /usr/bin/env python devscripts/make_readme.py
/usr/bin/env python devscripts/make_contributing.py README.md CONTRIBUTING.md
/bin/sh: pandoc: command not found
/bin/sh: line 0: [: =: unary operator expected
pandoc -f markdown -t plain README.md -o README.txt
make: pandoc: Command not found
make: *** [Makefile:92: README.txt] Error 127

real    0m1.382s
user    0m0.955s
sys     0m0.197s

**Comment by nicolaasjan** [comment]
> No luck on two boxes:
> 
---snip---
> I will just wait for the official binaries. ;)

`make: pandoc: Command not found`

Don't you have `pandoc` installed? ;)
(necessary for making the documentation)
