### ISSUE TITLE
Unable to extract login-form form - (see attached log)

### ISSUE THREAD

**Issue by sebytrading** [ytdl-org/youtube-dl#26388]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> youtube-dl --sleep-interval 3  --max-sleep-interval 5   --cookies u:/udemy-cookies.txt --all-subs -u QQQQQQ@GMail.com -p QQQQQQQQ -o '~U:/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s'  https://www.udemy.com/herethecoursename
[udemy:course] Downloading login popup
ERROR: Unable to extract login-form form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
PS C:\WINDOWS\system32> youtube-dl --verbose --sleep-interval 3  --max-sleep-interval 5   --cookies u:/udemy-cookies.txt --all-subs -u QQQQQQ@GMail.com -p QQQQQQQQ -o '~U:/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s'  https://www.udemy.com/herethecoursename
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--sleep-interval', '3', '--max-sleep-interval', '5', '--cookies', 'u:/udemy-cookies.txt', '--all-subs', '-u', 'PRIVATE', '-p', 'PRIVATE', '-o', '~U:/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', 'https://www.udemy.com/herethecoursename']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 3.4
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to extract login-form form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\program files\python38\lib\site-packages\youtube_dl\extractor\common.py", line 529, in extract
    self.initialize()
  File "c:\program files\python38\lib\site-packages\youtube_dl\extractor\common.py", line 433, in initialize
    self._real_initialize()
  File "c:\program files\python38\lib\site-packages\youtube_dl\extractor\udemy.py", line 172, in _real_initialize
    self._login()
  File "c:\program files\python38\lib\site-packages\youtube_dl\extractor\udemy.py", line 191, in _login
    login_form = self._form_hidden_inputs('login-form', login_popup)
  File "c:\program files\python38\lib\site-packages\youtube_dl\extractor\common.py", line 1343, in _form_hidden_inputs
    form = self._search_regex(
  File "c:\program files\python38\lib\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract login-form form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Continued in #29410.
