### ISSUE TITLE
downloading a video from a MPD file.

### ISSUE THREAD

**Issue by kolet** [ytdl-org/youtube-dl#26391]
## Checklist
 I'm asking a question
 I've verified that I'm running youtube-dl version 2020.07.28
 I've read bugs section in FAQ

hey .

i is that possible to download the video from an mpd file ?

the site i am looking at as a token enforment , and i am able to download the mpd only ones with a given token.
i would like to know if its possible for youtube-dl to download the video with a given mpd file.  
if not , would it be possible to add this feature in the future ?

thanks alot.

**Comment by zackmark29** [comment]
It's not possible. It's DRM Protected

**Comment by kolet** [comment]
> It's not possible. It's DRM Protected

hu ?

who said its DRM protected ? 

giving the mpd link to youtube-dl or streamlink works fine , they are able to download the whole videos and combine all the chunks togther, why isnt that possible to do that from the mpd but from a file ?

**Comment by kolet** [comment]
:o?

**Comment by kikuyan** [comment]
If you are talking about `file:`, no, and probably never will be. See 345f12196c9ed37094aec8c029809be888052d3a and the linked issue report.

If you run http server locally, you can make a request to it. For example,
on one terminal
`python3 -m http.server 8000` or `python -m SimpleHTTPServer 8000 # python 2`
and on another
`youtube-dl -F http://127.0.0.1:8000/manifest.mpd`

**Comment by 89z** [comment]
Issue should be closed, no URL given
