### ISSUE TITLE
Can't download from site 

### ISSUE THREAD

**Issue by terremoth** [ytdl-org/youtube-dl#26402]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
xhamster example:

```
C:\Users\Lucas\Softwares>youtube-dl.exe -v https://pt.xhamster.com/videos/where-the-magic-happens-xh2qrbl
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://pt.xhamster.com/videos/where-the-magic-happens-xh2qrbl']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: avconv 11.3, avprobe 11.3, ffmpeg N-55702-g920046a, ffprobe N-55702-g920046a
[debug] Proxy map: {}
[generic] where-the-magic-happens-xh2qrbl: Requesting header
WARNING: Falling back on generic information extractor.
[generic] where-the-magic-happens-xh2qrbl: Downloading webpage
[generic] where-the-magic-happens-xh2qrbl: Extracting information
ERROR: Unsupported URL: https://pt.xhamster.com/videos/where-the-magic-happens-xh2qrbl
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://pt.xhamster.com/videos/where-the-magic-happens-xh2qrbl
```

## Description

XHamster site can't download

**Comment by TheRealDude2** [comment]
I think this is closed with this pull request https://github.com/ytdl-org/youtube-dl/pull/25804, but not included in the recent version.

**Comment by terremoth** [comment]
@TheRealDude2 you know if there are any plans to merge this PR for next hotfix?

**Comment by TheRealDude2** [comment]
I think it is already planned for the next release. Unfortunately I have found some more problems with the extractor, so I'm not sure if the new version, with the 2 PRs already included, will work for everything again.

But for the last problem, I am apparently the only one where it appears https://github.com/ytdl-org/youtube-dl/issues/26353. But it can only be tested if you use a patched custom  version of the extractor.

**Comment by terremoth** [comment]
@TheRealDude2 
There are several online websites that uses youtube-dl on their backend and a several UI based softwares that are using youtube-dl too and they're not working anymore, probably because this PR's waiting

**Comment by TheRealDude2** [comment]
That's right. But maybe you can point out to these operators that it works again if they create their own version here from the current sources, or clone the current git repo and run it directly with python.

The problem already existed last month. But the PR did not make it into the current version. I also don't know why there is only one release per month.
