### ISSUE TITLE
tiktok.com URL changed

### ISSUE THREAD

**Issue by lonevillager** [ytdl-org/youtube-dl#26411]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

TikTok video URL changed to https://www.tiktok.com/@{uploader}/video/{id}

WRITE DESCRIPTION HERE

**Comment by MylesBorins** [comment]
Looks like it would be fixed by https://github.com/ytdl-org/youtube-dl/pull/26281/
