### ISSUE TITLE
youtube dl doesnot complete its execution just hangs ..this started happening after i migrated by server

### ISSUE THREAD

**Issue by Yashwanthd1998** [ytdl-org/youtube-dl#26413]
`WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
^Z
[2]+  Stopped                 youtube-dl -g https://youtu.be/naCCSpCliZ0
root@interestpoindi:~# youtube-dl -g https://youtu.be/naCCSpCliZ0

## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```youtube-dl -x --verbose https://www.youtube.com/watch?v=eLQ2atfqk2c
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-x', u'--verbose', u'https://www.youtube.com/watch?v=eLQ2atfqk2c']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[youtube] eLQ2atfqk2c: Downloading webpage
^Z
[3]+  Stopped                 youtube-dl -x --verbose https://www.youtube.com/watch?v=eLQ2atfqk2c



## Description

<!--
Provide an explanation of your issue in an arbitrary form. Please make sure the description is worded well enough to be understood, see https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

WRITE DESCRIPTION HERE
Youtube-dl stopped working..Iam running the latest version..atleast there are no error logs it just hangs forever

**Comment by reallyuniquename** [comment]
Have you checked your connection to Youtube servers? Try using this remote server as a proxy in your local browser.

**Comment by Yashwanthd1998** [comment]
Thanks..Actually it happend due to misconfiguration of ipv6 by my hosting provider..and cant connect to YouTube
