### ISSUE TITLE
SVT Play stopped working

### ISSUE THREAD

**Issue by ijbh** [ytdl-org/youtube-dl#26425]
Just moments ago youtube-dl stopped working for svtplay.se. It has been working all morning but suddenly stopped this afternoon. You get the following error message:

> ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

and if you type in --verbose you get this:

> 
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'https://www.svtplay.se/video/27782111/en-andra-chans', u'--verbose']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2020.07.28
> [debug] Python version 2.7.16 (CPython) - Darwin-19.4.0-x86_64-i386-64bit
> [debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
> [debug] Proxy map: {}
> [debug] Using fake IP 78.74.182.000 (SE) as X-Forwarded-For.
> [SVTPlay] 27782111: Downloading webpage
> ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
>     ie_result = ie.extract(url)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
>     ie_result = self._real_extract(url)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/svt.py", line 229, in _real_extract
>     webpage, 'video id')
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
>     raise RegexNotFoundError('Unable to extract %s' % _name)
> RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I have tried to download several links but get the same error message. Here is a sample link that stopped working:

https://www.svtplay.se/video/27782111/en-andra-chans

**Comment by Sopor** [comment]
I assume this issue will be closed because you didn't follow the issue template...

**Comment by ijbh** [comment]
Alright, I reposted it within the template format.

**Comment by Sopor** [comment]
It is possible to edit an issue. Now there are three open issues with the same error :(

**Comment by ijbh** [comment]
Sorry. But you assumed the thread would be closed, so I assumed the same.
