### ISSUE TITLE
SVTplay: Unable to extract video id

### ISSUE THREAD

**Issue by beteetzen** [ytdl-org/youtube-dl#26426]
youtube-dl seems not to work any longer on Mac OS X Catalina with SVTplay sites. youtube-dl -U says version is up to date (2020.07.28)

Looks like SVT has changed server structure again so that svt.py cannot get the video id any more. 

'''bernd@iMac Downloads % youtube-dl --verbose https://www.svtplay.se/video/27908335/babel/babel-sasong-32-jan-guillou-lydia-sandgren-mikael-niemi-loney-dear
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.svtplay.se/video/27908335/babel/babel-sasong-32-jan-guillou-lydia-sandgren-mikael-niemi-loney-dear']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2-tessus, rtmpdump Reason
[debug] Proxy map: {}
[debug] Using fake IP 78.70.116.171 (SE) as X-Forwarded-For.
[SVTPlay] 27908335: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/svt.py", line 229, in _real_extract
    webpage, 'video id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.'''

**Comment by Sopor** [comment]
I assume this issue will be closed because you didn't follow the issue template...

**Comment by beteetzen** [comment]
ok - sorry I have misunderstood the template

Anyway - same issue now opened with  #26428 by ijbh
