### ISSUE TITLE
[ThisAV] Fix problems

### ISSUE THREAD

**Issue by kongfoo5937** [ytdl-org/youtube-dl#26446]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Description

WRITE DESCRIPTION HERE

Bugs on ThisAV are not fixed still.
This issue fixes them, based on PR #19127. Sorry for not using git because I cannot use  it in my env.

uploader and uploader id are fixed. 
Work fine.
[fix_thisav.zip](https://github.com/ytdl-org/youtube-dl/files/5133712/fix_thisav.zip)

**Comment by dirkf** [comment]
Continued in #32595.
