### ISSUE TITLE
Youtube-dl only download specific codec if it has best resolution

### ISSUE THREAD

**Issue by Sci3ntia** [ytdl-org/youtube-dl#26444]
## Checklist

- [X ] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

OK so I've been using ```youtube-dl --cookies cookies.txt -f '(bestvideo[vcodec*=av01]/bestvideo[vcodec=vp9]/bestvideo)+(bestaudio[acodec=opus]/bestaudio[acodec=vorbis]/bestaudio[acodec=aac]/bestaudio)/best' --sub-lang en --embed-subs --add-metadata %video% -o '%(title)s.%(ext)s'``` to download videos and have a question, when such a video has an av1 encode that is below the best resolution (let's say it has av1 144p but vp9 1080p) how would I tell it to download the best (less preferred) codec (in the case of the previous example vp9), instead of the lower quality (more preferred) codec?

**Comment by pukkandan** [comment]
There is sadly no easy way to do this. You can either make a list of all format codes like [this guy](https://www.reddit.com/r/DataHoarder/comments/g302cg/my_youtubedl_script_the_best_formatting_i_could/), or you could use a large format selection with seperate codec check for each resolution (Something like: `((bestvideo[vcodec*=av01]/bestvideo[vcodec=vp9]/bestvideo)[height>2160]/(bestvideo[vcodec*=av01]/bestvideo[vcodec=vp9]/bestvideo)[height>1080]/**...**/(bestvideo[vcodec*=av01]/bestvideo[vcodec=vp9]/bestvideo)[height>144]/(bestvideo[vcodec*=av01]/bestvideo[vcodec=vp9]/bestvideo))+bestaudio**...**`

**Comment by Sci3ntia** [comment]
Sorry to hear that, but thanks for the workarounds

**Comment by pukkandan** [comment]
https://github.com/ytdl-org/youtube-dl/pull/25959 now automatically selects the best codec av01>vp9>avc1...
