### ISSUE TITLE
Youtube history download sees 0 videos

### ISSUE THREAD

**Issue by lightray22** [ytdl-org/youtube-dl#26452]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.07.28**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: ['-o', '%(uploader)s_%(upload_date)s_%(title)s_%(height)s_%(id)s.%(ext)s', '--continue', '--no-overwrites', '--ignore-errors', '--external-downloader', 'aria2c', '--external-downloader-args', '-x 16 -s 16 -k 1M --console-log-level=error --file-allocation=none --keep-unfinished-download-result=false --summary-interval=0']
[debug] Custom config: []
[debug] Command-line args: ['--cookies', '/home/user/.config/youtube-dl/cookies-user.txt', '--max-filesize', '10g', '--download-archive', './.downloaded.txt', '--verbose', 'https://www.youtube.com/feed/history']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.7.8 (CPython) - FreeBSD-12.1-RELEASE-p8-amd64-64bit-ELF
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:history] Youtube History: Downloading webpage
[download] Downloading playlist: Youtube History
[youtube:history] playlist Youtube History: Downloading 0 videos
[download] Finished downloading playlist: Youtube History

## Description

Trying to download from YouTube's history results in it showing zero videos and not downloading anything.  Using the same cookies and download.txt file but downloading from a playlist instead works fine, so I know those files are valid.  I also tried downloading the history from three different accounts and the same behavior of zero videos happens.  The last time this worked properly was July 22nd, so it seems to have been broken for a while.

Here is the exact command I'm using:

`/usr/local/bin/youtube-dl --cookies /home/user/.config/youtube-dl/cookies-user.txt --max-filesize 10g --download-archive ./.downloaded.txt --verbose https://www.youtube.com/feed/history`

**Comment by ahknight** [comment]
I am also seeing this.  It looks like it's successful, but neither the `:ythistory` or feed URLs report any videos.  The browser I took the cookie from can see the history just fine.  I suspect a page layout change.

**Comment by ahknight** [comment]
Related to the following blindly-closed issues:

https://github.com/ytdl-org/youtube-dl/issues/26255

https://github.com/ytdl-org/youtube-dl/issues/26181

Note that all other video downloads work, including Watched Recently.  It's specifically History that comes back with zero items and no errors.

**Comment by lightray22** [comment]
#26255 looks like the same thing, not sure why that was closed as a duplicate.  #26181 looks like something different.

**Comment by ahknight** [comment]
The description of the issue has the same pattern as this report, though the comments do indeed go elsewhere.  50/50? :) Anyhow, this is still happening to me as well.  I'm on 2020.07.28 via Homebrew on macOS FWIW.

**Comment by whistletoe** [comment]
Really looking forward to seeing this issue fixed!

**Comment by louwrentius** [comment]
I'm trying this with the latest youtube-dl and it's still broken, unfortunately. 

`[youtube:history] Youtube History: Downloading webpage
[download] Downloading playlist: Youtube History
[youtube:history] playlist Youtube History: Downloading 0 videos
[download] Finished downloading playlist: Youtube History`
