### ISSUE TITLE
10 h video shortened to 2 hours.

### ISSUE THREAD

**Issue by Bardo-Konrad** [ytdl-org/youtube-dl#26468]
I am trying to download https://www.youtube.com/watch?v=QC3YHAQrTe0

It's a 10h video.

I get a video as a result that starts somewhere in the video and lasts about 2 hours.

Replicate by using "youtube-dl https://www.youtube.com/watch?v=QC3YHAQrTe0".

**Comment by InternationalYamAgain** [comment]
See https://github.com/ytdl-org/youtube-dl/issues/26330. There is a work-around there or you can wait for YouTube to finish processing.

**Comment by Bardo-Konrad** [comment]
> you can wait for YouTube to finish processing.

Is it finished once it has autogenerated subtitles or how do I see that?

**Comment by rn83** [comment]
> Is it finished once it has autogenerated subtitles or how do I see that?

When it's finished, there should be a `format 22` when you try `youtube-dl -F`.
```
22           mp4        1280x720   720p 1768k , avc1.64001F, 30fps, mp4a.40.2@192k (44100Hz) (best)
```
The problem is that it takes days for some videos.
I have been waiting for a live stream ended three days ago.
For most cases it should be done in a few hours.
