### ISSUE TITLE
Youtube-dl is dying?

### ISSUE THREAD

**Issue by blackjack4494** [ytdl-org/youtube-dl#26462]
Had to choose this dramatic title to get some attention. For some reason almost no PR is getting merged anymore and those that did get merged were quite some time ago.  
So far @dstftw is the core maintainer (since 2016+) next to @remitamine 
But if you have a look at their profiles 
https://github.com/dstftw
https://github.com/remitamine
You can see there was barely any activity recently.  
So what I am asking for is giving more people access to merge PRs. Otherwise new sites and especially fixes cannot be applied and lead to even more issues asking the same issues since its not fixed when there is already a PR with a fix for it for quite some time.
Also pinging @phihag here since he was quite active some time ago.

Edit:
Never thought this will skyrocket that fast.
I really hope they will add more maintainers. Alternatively I found this [GitConsensus](https://github.com/gitconsensus) also available as an app. From my understanding you can set a threshold of votes for a PR and then vote with reactions. Resulting in either merging the PR or closing it.
As a last resort there is still the option of forking and starting a new project (I noticed that got mentioned sometimes).

**Comment by fenopa** [comment]
I was gonna ask same thing with the "is youtube-dl dead" title but thought dstftw would probably lock it in seconds and then ban me so didn't post.

They might be burned out after years of work or lost interest, which is understandable but I don't know why they don't bring new maintainers then.

**Comment by Gloryness** [comment]
I agree with this post, I cant download anything of YouTube atm and they havent updated in a month...

**Comment by llacb47** [comment]
https://github.com/ytdl-org/youtube-dl/graphs/contributors?from=2020-02-28&to=2020-08-28&type=c

**Comment by andrewzah** [comment]
@Gloryness can you link an example video? I am using an older version of youtube-dl (2020.05.29) and I can download videos just fine at this moment.

**Comment by ealgase** [comment]
> 
> 
> Had to choose this dramatic title to get some attention. For some reason almost no PR is getting merged anymore and those that did get merged were quite some time ago.
> So far @dstftw is the core maintainer (since 2015+) next to @remitamine
> But if you have a look at their profiles
> https://github.com/dstftw
> https://github.com/remitamine
> You can see there was barely any activity recently.
> So what I am asking for is giving more people access to merge PRs. Otherwise new sites and especially fixes cannot be applied and lead to even more issues asking the same issues since its not fixed when there is already a PR with a fix for it for quite some time.
> Also pinging @phihag here since he was quite active some time ago.

I surely hope it isn't - I do think the project could use more active maintainers.

**Comment by chnl** [comment]
youtube-dl version 2020.06.16.1 is working just fine for me

**Comment by aklys** [comment]
I've found it working fine for manual once off downloads. but the WL bit I used to use has been broken for months and months. Needing you to manually introduce a cookie as a workaround.

**Comment by blackjack4494** [comment]
@yan12125 also pinging you as you are listed as core maintainer and seem active on github at least.

**Comment by Gloryness** [comment]
> 
> 
> @Gloryness can you link an example video? I am using an older version of youtube-dl (`2020.05.29`) and I can download videos just fine at this moment.
> 
> edit: the latest version on freebsd is `2020.07.28`, just updated to that and was able to download a video from youtube.

Oh, must be something on my end then? But at first I tried to download a music video, and that gave me an error. So I tried downloading a normal video, same error occured.. I just assumed that youtube must of updated their system or something.

**Comment by johnmccabe** [comment]
youtube-dl 2020.07.28 working fine for me.

If you're having problems updating your version try using docker.

**Comment by JordanWeatherby** [comment]
It would be a shame for this project to die out due to inactive maintainers, its a great tool that clearly has a lot of community support.

Hopefully something can get sorted out some time soon

**Comment by Albert9999** [comment]
I also agree. 

I would be interested in participating but I have limited knowledge of Python at the moment. 

What would I need to learn and do to become a maintainer on this project?

If anyone could point me towards some ressources so I can learn more, I would greatly appreciate it.

Thank you.

**Comment by zackmark29** [comment]
It looks like they are just resting for a while? or maybe there's just important things to do with their life. 
Or maybe they are working now at Google =D

**Comment by lgrn** [comment]
This is free software, why don't you just fork it?

**Comment by Tumultuous-RGR-SiM** [comment]
> This is free software, why don't you just fork it?

Probably because it's more efficient to get any extra patches integrated into a main release. Expecting users to search out different forks to collect the various patches and features that other people have written and then trying to add this to their own installations of the program is exactly the kind of inefficiency that sites like github seem to have been made to put a stop to.

**Comment by chengengliu** [comment]
It's working but not quite stable. I guess youtube has more restrictions on downloading.

**Comment by NickyNiclas** [comment]
If you are dns filtering to try to block youtube ads, that might be your issue. I turned off my pi-hole and it started working. Just saying.

**Comment by magnum32** [comment]
to this day the fix for downloading from abc.com has still not been merged into youtube-dl. i wonder whats taking so long.

**Comment by yan12125** [comment]
> What would I need to learn and do to become a maintainer on this project?

In my memory most previous maintainers contribute lots of pull requests (like, more than 10) and polishing their pull requests according to coding conventions [1] before becoming a maintainer. They also helped on responding to many others' issues. I believe contribution and participation are important factors.

[1] https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions

**Comment by theincognito-inc** [comment]
I created a fork with many non merged PRs for my need. Thanks to all who did the PRs. 💯

**Comment by happysmash27** [comment]
I decided to see what pull requests there were... and there are 723‽‽ Holy cow! I expected there to be a lot, but 723 pull requests is an order of magnitude larger than I imagined as a massive amount!

**Comment by GETandSELECT** [comment]
Maybe Google sabotaged the project? The Kodi Youtube plugin was also a thorn in the side of Google. Google destroyed it. We will probably never know.

**Comment by GETandSELECT** [comment]
Maybe Google sabotaged the project? The Kodi Youtube plugin was also a thorn in the side of Google. Google destroyed it. We will probably never know.

**Comment by reallyuniquename** [comment]
@GETandSELECT 
Support for Google services is probably the most maintained part of youtube-dl, if anything related is broken we get updates in a matter of hours. Can't really complain about that.

**Comment by nicolaasjan** [comment]
> Support for Google services is probably the most maintained part of youtube-dl, if anything related is broken we get updates in a matter of hours. Can't really complain about that.

That used to be the case, but lately I have seen some issues regarding YouTube...
Examples:
https://github.com/ytdl-org/youtube-dl/issues/26152
There's a proposed fix, committed more than a month ago (https://github.com/ytdl-org/youtube-dl/pull/26100/commits/cae18ef8f2795e5f584fe450b9619de176e72e02), but it's still not implemented.
and:
https://github.com/ytdl-org/youtube-dl/pull/25717
Proposed fix:
https://github.com/ytdl-org/youtube-dl/pull/25717/commits/777d5a45be81fb1f274c8c558ba1eb24855c66fc

I had to apply these fixes (and another one, not related to YouTube) locally and compile youtube-dl myself, to get things working again...

**Comment by reallyuniquename** [comment]
Well I stand corrected, I wasn't aware of those.

**Comment by blackjack4494** [comment]
I updated the main post.
You can start submitting your PRs here https://github.com/blackjack4494/youtube-dlc
I will try to merge valid PRs every few days and may set up daily cron job to release newest version on pypi or on request :)

**Comment by dstftw** [comment]
All collaborators with enough expertise already have access to merging PRs and write access to the repo. Apart from them I see no other appropriate candidates yet. Merging PRs is not just about merging in the first place.
Currently I don't have time for youtube-dl but will probably have some later.

**Comment by blackjack4494** [comment]
There is no doubt about that. Sure it's not only about clicking the button merge. But there have been fixes for various extractors for several weeks with people reporting that it works. 
We are glad to hear something back. Some were just frustrated since there was not even any sign of communication by maintainers.

**Comment by todduk** [comment]
Prioritizing the youtube fixes would be appreciated at least. The age-gated downloads not working is a real problem.

**Comment by blackjack4494** [comment]
@todduk check my fork. should work there.

**Comment by vxbinaca** [comment]
> All collaborators with enough expertise already have access to merging PRs and write access to the repo. Apart from them I see no other appropriate candidates yet. Merging PRs is not just about merging in the first place.
> Currently I don't have time for youtube-dl but will probably have some later.

Unsatisfactory response. I know well people do bad commits, and you don't just merge anyones commit, but you have PRs right now where they've been tested by multiple people ex #25606 and everyones saying they work. The community did the testing for you. It remains unmerged.

The consequences of you not clicking your mouse twice was internet history has been lost for months, not just for my bots but for numerous users of my script that depends on youtube-dl.

Youtube-dl is in fact dying. Theres already another project that literally just mirrors your codebase, and merges all the working PRs you just sit on. Goodbye, I plan on ensuring Tubeup has comparability with both, and if the situation doesn't improve soon I'll force depend youtube-dlc over youtube-dl.

**Comment by reallyuniquename** [comment]
>you have PRs right now where they've been tested by multiple people and everyones saying they work

My guess is the fact that PR works is probably the last thing youtube-dl maintainers check.

What really devastating is a lack of proper communication.

**Comment by todduk** [comment]
It's an open-source project, I'm not sure it's really fair to make demands of the maintainers or act so outraged that progress has slowed. Sometimes real-life stuff just has to take precedence. An update would be appreciated but I can understand that with such a backlog even logging in and checking emails can be depressing.

**Comment by vxbinaca** [comment]
> > you have PRs right now where they've been tested by multiple people and everyones saying they work
> 
> My guess is the fact that PR works is probably the last thing youtube-dl maintainers check.
> 
> What really devastating is a lack of proper communication.

#25606 works. It doesn't conflict with anything in the codebase because that extractor hasn't been updated in a while. The coding style is good. I looked at what was changed, it's updating to the new API Twitch has for channel extraction, allows channel URLs to work again.

What could possibly in your mind hold this PR up? I'd like to know.

> It's an open-source project, I'm not sure it's really fair to make demands of the maintainers or act so outraged that progress has slowed. Sometimes real-life stuff just has to take precedence. An update would be appreciated but I can understand that with such a backlog even logging in and checking emails can be depressing.

Click your mouse button twice and describe to me the effort that went into that. We're not asking to code a fix for us, someone already did that. We're not aking it be tested since multiple people have tested this and it works in youtube-dlc, the fork of his project. 

We're asking a working fix be merged with two little mouse clicks. And it's not just Twitch. Theres a ton of buggy extractors with fixes in the que RIGHT NOW.

This project is dying. I'm going to route around this project and use a forked project that is now over 100 commits ahead, and working great. I'm even going to offer my time to help it in what ways I can. I'm putting my time after good purposes where bugs actually get fixed and features implimented
