### ISSUE TITLE
How to download a live video from a previous point in time?

### ISSUE THREAD

**Issue by dd-pardal** [ytdl-org/youtube-dl#26474]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

When I download a live stream, youtube-dl starts downloading it from the present, but I would like to download it from as far back in time as possible, or to specify a timestamp from which the download will start.

**Comment by dstftw** [comment]
Not possible.

**Comment by dd-pardal** [comment]
It is (technically) possible. With <https://github.com/fent/node-ytdl>, I can download live videos up to 4 hours back.
