### ISSUE TITLE
Force mp4 and max resolution (1920x1080p) at the same time ...?

### ISSUE THREAD

**Issue by Wogol** [ytdl-org/youtube-dl#26470]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Im trying to create a bash script for youtube-dl and one of the issues is I cant get youtube-dl to force mp4 download AND limit it to max 1080p videos.
https://stackoverflow.com/questions/63336809/youtube-dl-download-script-debug

Works, force mp4:
```
-f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best --merge-output-format mp4
```

Have tested all this and more and dont work
```
-f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 -f 'bestvideo[height<=1080]+bestaudio/best[height<=1080]'
-f 'bestvideo[ext=mp4,height<=1080]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4
-f 'bestvideo[ext=mp4,height<=1080p]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4
-f 'bestvideo[ext=mp4:height<=1080]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4
```
....

Do youtube-dl support force mp4 and max resolution of video to download?

**Comment by reallyuniquename** [comment]
https://github.com/ytdl-org/youtube-dl#format-selection

**Comment by Wogol** [comment]
> https://github.com/ytdl-org/youtube-dl#format-selection

Thanks. After some reading and testing back and forth this works.
```
-f bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/best[ext=mp4]/best --merge-output-format mp4
```
