### ISSUE TITLE
Can't download youtube video.

### ISSUE THREAD

**Issue by ArtistJay** [ytdl-org/youtube-dl#26472]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[youtube] 04-NURxskQY: Downloading webpage
ERROR: 04-NURxskQY: YouTube said: Unable to extract video data
```

## Description

Error shown below,
[youtube] 04-NURxskQY: Downloading webpage
ERROR: 04-NURxskQY: YouTube said: Unable to extract video data

**Comment by oqibidipo** [comment]
>  I've checked that all provided URLs are alive and playable in a browser

Really? I get "This video has been removed by the uploader"

https://www.youtube.com/watch?v=04-NURxskQY
