### ISSUE TITLE
Python embedding: return raw video?

### ISSUE THREAD

**Issue by redbrain** [ytdl-org/youtube-dl#26481]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm embedding youtube-dl in a Python program, and I'd like to create a function that returns the raw video data (as if i was passing `-o -` from the command line). Is there a way to do this?

**Comment by dstftw** [comment]
No.
