### ISSUE TITLE
Add playlist urls to --download-archive

### ISSUE THREAD

**Issue by james28909** [ytdl-org/youtube-dl#26487]
I recently just deleted my entire library by mistake. I must have hit a key when I went to get up to use the bathroom somehow. I didn't even notice till I got back and went to download another playlist. I went to the folder and there was nothing there (ohhell.jpg).

I was recently told about the -a option, and while that would work to get my files back, it will not preserve the folder structure I had before, and instead puts everything in a "NA" folder.

I was using format specifiers to create folders and filenames - /%(playlist)s/%(title)s.%(ext)s - and using the -a option with this output specifier, it does not work and just slaps all the videos in a "NA" folder. As opposed to the %(playlist)s "baseball" being the folder name and all videos in the playlist getting put in the "baseball" folder.

There has got to be a way we can add playlist urls to the download-archive file, or is there a way I can reverse search the individual url and get the playlist name?

Actually, come to think about it, why not just put individual urls and playlists urls in the download archive?

When I download my favorites, the playlist will be "favorites", which /%(playlist)s/%(title)s.%(ext)s would create a folder named "favorites" and put all your songs in there. And if you need to put a individual video somewhere else, just specify it in -o.

I guess what I'm trying to say is that putting individual urls for videos that are in playlists is kind of punching yourself in the face when you use format specifiers to create folder structures

**Comment by james28909** [comment]
Sorry for spamming my own comment here but, could you just change all instance that have to do with parm-download archive that assert "vid_id" to "playlist_id" or "playlist_title". 

Would it really be that easy? And I can download this code as is and run it right? I use the compiled executable but don't mind installing python to make these few changes, would be cool if the official youtube-dl exe had the functionality I talk about in my original post.

**Comment by dstftw** [comment]
The purpose of download archive is to track already downloaded media by id. This has nothing to do with playlist URLs or what ever.

**Comment by james28909** [comment]
> The purpose of download archive is to track already downloaded media by id. This has nothing to do with playlist URLs or what ever.

OK but don't you think it would still be a good idea to do as the title of this thread says and add actual playlists urls to the archive file? The rest can be handled without youtube-dl but ADDING PLAYLIST URLS to the archive file just makes sense. Because even then you won't have to skip video by video, you can also skip playlists as well
