### ISSUE TITLE
Allow conditional embedding of subtitles

### ISSUE THREAD

**Issue by HalosGhost** [ytdl-org/youtube-dl#26504]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I have setup my configuration so that `youtube-dl` very helpfully downloads videos with all my preferred default options. However, one thing I would love to do is add ``--embed-subs`` to that configuration. I cannot though because, if videos do not have subtitles, then it will fail during post-processing.

So, I can imagine three solutions to this:

- change ``--embed-subs`` to not fail if no subtitles were downloaded
- either add an option like ``--embed-subs-if-available`` or ``--no-sub-embed-errors`` to allow this functionality to be enabled conditionally as a user might desire
- add a more extensible system to allow for logic in applying options based on information about the video

Personally, given the above options, the simplest solution seems very clearly to be the first choice; and, conversely, the third option is clearly the most involved (and may well make `youtube-dl` turing-complete).

Do any of these options sound reasonable? Is there a way to achieve embedding subs only if they were actually downloaded, and to skip ``--embed-subs`` if not (I couldn't find anything in the documentation to suggest so)?

**Comment by reallyuniquename** [comment]
> if videos do not have subtitles, then it will fail during post-processing

No? It just says `There aren't any subtitles to embed` and then exits gracefully.

**Comment by HalosGhost** [comment]
@reallyuniquename, there must have been something else wrong with the videos I was downloading as when I ran a test just now, it indeed exited gracefully.

If I figure out that something about the subtitles was indeed related, I'll reopen with more information. Sorry for the noise!
