### ISSUE TITLE
Youtube downloads retry when on "forcibly closed" error, but Twitch downloads fail and close

### ISSUE THREAD

**Issue by cerenovog** [ytdl-org/youtube-dl#26503]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
When downloading videos in a batch file, videos from YouTube will automatically retry (10 times) if the connection is forcibly closed, but Twitch vods do not retry at all which terminates the whole batch process.  Is there an argument that will cause the same behavior in both sites, so that a Twitch download that is forcibly closed doesn't terminate my whole scheduled batch process (and hopefully can just keep retrying until the video is downloaded without having to manually babysit it as with the Youtube behavior)?

**Comment by reallyuniquename** [comment]
#10935?

Try using `--hls-prefer-ffmpeg` instead of native HLS downloader, maybe ffmpeg handles errors better than youtube-dl.
