### ISSUE TITLE
Manifest too large

### ISSUE THREAD

**Issue by justanothernoob4648** [ytdl-org/youtube-dl#26502]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
https://manifest.googlevideo.com/api/manifest/dash/expire/1599007996/ei/nJhOX6bjKcW5D_3Su4gC/ip/69.14.251.30/id/9adda126be2e94b5/source/youtube/requiressl/yes/playback_host/r7---sn-fvf-qufe.googlevideo.com/mh/5g/mm/31%2C29/mn/sn-fvf-qufe%2Csn-p5qs7nee/ms/au%2Crdu/mv/m/mvi/7/pl/21/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/2228750/vprv/1/mt/1598986242/fvip/2/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRAIgA5duFRdA51Gxw1FyZvkEpjDb4B5dR-e-uar0ASxc-AACIA6Xxz9R2NI3lSLYhUvKVqifGYBdXm-kHopcMFbPDtOZ/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIhALnULOrLQ6KGtM2WuTt2nPxL1C4qJ0ucjCFpT5en-RAKAiBGpFncCE9nRAnA0Zm_NGlvMfCu6WezrdOIeWZOyrZcSw%3D%3D: Invalid data found when processing input

That is the error I'm getting. No clue why. Maybe the video size is too large?

**Comment by dstftw** [comment]
403.

**Comment by ashroyxi** [comment]
how did you solve that?
