### ISSUE TITLE
France.tv broken on some videos

### ISSUE THREAD

**Issue by djibux** [ytdl-org/youtube-dl#26505]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'Ninjago S02E04', 'https://www.france.tv/france-3/lego-ninjago/saison-2/242131-la-course-ninjaball.html', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.5 (CPython) - Linux-5.7.0-3-amd64-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.3.1-2, ffprobe 4.3.1-2
[debug] Proxy map: {}
[FranceTVSite] 242131-la-course-ninjaball: Downloading webpage
[FranceTV] dd1f1669-a5fb-479b-999c-31323f85f3f0: Downloading video JSON
[FranceTV] dd1f1669-a5fb-479b-999c-31323f85f3f0: Downloading geo restriction info
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/djib/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/djib/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/djib/.local/lib/python3.8/site-packages/youtube_dl/extractor/francetv.py", line 209, in _real_extract
    return self._extract_video(video_id, catalog)
  File "/home/djib/.local/lib/python3.8/site-packages/youtube_dl/extractor/francetv.py", line 169, in _extract_video
    self._sort_formats(formats)
  File "/home/djib/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Some episodes of Lego Ninjago are not downloadable but are playable within the browser:
* S02E03 can be downloaded: https://www.france.tv/france-3/lego-ninjago/saison-2/1119701-les-ennuis-n-arrivent-jamais-seuls.html
* S02E04 cannot be downloaded: https://www.france.tv/france-3/lego-ninjago/saison-2/242131-la-course-ninjaball.html

I dug into the code of `francetv.py` and indeed there is a difference between the two in the JSON file fetched:
* S02E03 has a `url` for each video: https://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=cede1820-bdbb-4571-9673-5be4e97df458
* S02E04 has no `url` (null value): https://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=dd1f1669-a5fb-479b-999c-31323f85f3f0

The second video is playable within the browser though, so there should be a way to download it.

**Comment by oilarabla** [comment]
I've been digging a bit and it looks like youtube-dl is using the `https://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/` API to get the video information but as of now, the player page is using `https://player.webservices.francetelevisions.fr/v1/videos/`.

The latter returns a JSON with a `video` attribute (instead of `videos`) : [https://player.webservices.francetelevisions.fr/v1/videos/cede1820-bdbb-4571-9673-5be4e97df458?country_code=FR&w=720&h=405&player_version=5.41.2&domain=www.france.tv&device_type=desktop&browser=firefox&browser_version=77&os=linux&diffusion_mode=tunnel_first](url)
which contains a `url` attribute.

I might fix it but I've never contributed to OSS so it may take some time for me to get it right.

**Comment by taokann** [comment]
Bonjour, j'ai eu le même problème, cela semble aléatoire selon les vidéos. Dans la même série, seul le premier épisode a résisté à youtube-dl (https://www.france.tv/france-5/apocalypse-la-2e-guerre-mondiale/saison-1/328777-l-agression-1933-1939.html). Tous les autres ont fonctionné.
Pouvez-vous m'indiquer comment corriger l'erreur, faut-il remplacer l'URL de l'API dans un fichier python ? Où se trouve-t-il sur un système unix ?

----

Hi, I have the same problem. On a given show, only the first episode won't be downloaded.
Can you tell me how to quick-fix this locally? A python file to edit? Where is it on a unix-like system?
thanks.

**Comment by djibux** [comment]
@dstftw, could you please provide the bug number?  I didn’t find it and I would like to follow it.

**Comment by oilarabla** [comment]
@djibux #22561
