### ISSUE TITLE
Forward the download location to another (grep) program?

### ISSUE THREAD

**Issue by Wogol** [ytdl-org/youtube-dl#26515]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Trying to make a easy to use script to download YouTube videos easy and also create a info file with Title, Channel, channel URL, upload date, tags, url to video and also description. I found that the information is in the JSON file that youtube-dl download. What Im struggling with is how to get the folder location information from youtube-dl to grep that then can access JSON file and copy that information to a dedicated text file.

$folder'/%(title)s/%(title)s - (%(id)s) - %(uploader)s - %(upload_date)s.%(ext)s'

$folder is a location the user choose earlier in the script. I have added ID, uploader and upload date to the files because that is the only way I know to get that information saved in a "easy" way to access it.

Is there a way to do this?

More information about the script here https://stackoverflow.com/questions/63336809/youtube-dl-download-script-debug

**Comment by reallyuniquename** [comment]
Just get it from the youtube-dl output?

**Comment by Wogol** [comment]
Can you explain more?

I have read youtube-dl manual and dont find anything about how to get it there.

**Comment by reallyuniquename** [comment]
You want to get the value of `$folder'/%(title)s/%(title)s - (%(id)s) - %(uploader)s - %(upload_date)s.%(ext)s'` when youtube-dl finishes the job, is that correct?

**Comment by Wogol** [comment]
Yes, and get that to grep. Specially the json file. As said before, I already have $folder so only youtube-dl value of `'/%(title)s/%(title)s - (%(id)s) - %(uploader)s - %(upload_date)s.%(ext)s'` is needed.

**Comment by reallyuniquename** [comment]
Youtube-dl prints complete name of a file

> `[download] Destination: Video-12345-abc-2020.mp4`

You could extract that by grepping its output. 

You could also use `--get-filename` option that requires running youtube-dl once again but it doesn't download anything, or you could use `--exec` that passes filename to whatever command you specify.

**Comment by Wogol** [comment]
Thanks for your help. Have completely missed that part that youtube-dl prints the name and path of the video file.

Have just got information about a program called xidel and with that no need to download description or json file. I do not know how to do this but some how get the path and filename of from youtube-dl, replace the extension (mp4) with txt and dump the xidel output there to that text file. I do not want to run youtube-dl two times. 

youtube-dl output
> [download] Destination: /location/of/video/Video-12345-abc-2020.mp4

txt file for xidel to dump the output from the script below.
> /location/of/video/Video-12345-abc-2020.txt

```
xidel -s https://www.youtube.com/watch?v=dQw4w9WgXcQ -e '
  let $json:=json(
        //script/extract(.,"ytplayer.config = (.+?\});",1)[.]
      )/args,
      $a:=json($json/player_response)/videoDetails,
      $b:=json($json/player_response)/microformat
  return (
    "- TITLE -",
    $a/title,"",
    "- CHANNEL -",
    $a/author,"",
    "- CHANNEL URL -",
    $b//ownerProfileUrl,"",
    "- UPLOAD DATE -",
    $b//publishDate,"",
    "- URL -",
    $json/loaderUrl,"",
    "- TAGS -",
    $a/keywords,"",
    "- DESCRIPTION -",
    $a/shortDescription
  )
' --printed-json-format=compact
```

**Comment by reallyuniquename** [comment]
At this point it's not a youtube-dl issue, you just need to figure bash basics.

Also I'm not sure why you would prefer running `xidel` to `youtube-dl` when it does exactly the same thing 
```bash
filename=$(youtube-dl --get-filename -o '%(upload_date)s.%(ext)s' https://www.youtube.com/watch?v=dQw4w9WgXcQ)
echo $filename
```
That would output just the filename without downloading anything.
