### ISSUE TITLE
403 while accessing a certain m3u8 url.

### ISSUE THREAD

**Issue by laxuscullen** [ytdl-org/youtube-dl#26510]
Hello, this is my first time on GitHub opening an issue so please forgive me if I made any mistake. 

I am trying to download a m3u8 link which gives an 403 and says access denied. I am sure they are using some kind of a thing that requires user agent headers and what not and I am very lost, I don't know where else to ask about this. I would be in your kind debt if you could tell me what to do in this case. 

Example link: https://streaming02.cloud9xx.com/videos/hls/4f_bbSrDJL8ztf4K3YmEnQ/1598874479/99386/69266846c4dfc57c84fa699207c06bf3/ep.1.1598402927.m3u8

**Comment by zackmark29** [comment]
You should include the url of the website. Maybe it's not supported with youtube-dl. 

or try this command: youtube-dl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36" -f best "YOUR URL"

**Comment by PlaceboPRS** [comment]
Depending what browser you use a very nice little extension to help you get the full command with headers etc is https://addons.mozilla.org/en-GB/firefox/addon/hls-stream-detector/?src=search

**Comment by laxuscullen** [comment]
Hi! Actually I am using this command in my ubuntu server so I can't actually you know open a browser and use an extension.

**Comment by laxuscullen** [comment]
> You should include the url of the website. Maybe it's not supported with youtube-dl.
> 
> or try this command: youtube-dl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36" -f best "YOUR URL"
> 
> also you could add, headers like origin and referer

Thank you so much for your reply, how does one add headers like orgin and referer? Because I tried your suggestion and it's the same issue :(


Full thing that is shown:
youtube-dl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36" -f best "https://streaming07.cloud9xx.com/videos/hls/VFoLR3Q9vH6Hvpw0xmOlWw/1599140715/15249/04a1bdc0d5c4d4260b47b73ac2ec7aaf/sub.51.m3u8"
[generic] sub.51: Requesting header
WARNING: Could not send HEAD request to https://streaming07.cloud9xx.com/videos/hls/VFoLR3Q9vH6Hvpw0xmOlWw/1599140715/15249/04a1bdc0d5c4d4260b47b73ac2ec7aaf/sub.51.m3u8: HTTP Error 403: Forbidden
[generic] sub.51: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by PlaceboPRS** [comment]
> 
> 
> Hi! Actually I am using this command in my ubuntu server so I can't actually you know open a browser and use an extension.

Ok sorry :)

**Comment by laxuscullen** [comment]
Please can anyone help?

**Comment by zackmark29** [comment]
> Please can anyone help?

try to use proxy

**Comment by sclsj** [comment]
When I opened the link, it returned HTTP Error 410 Gone.

**Comment by laxuscullen** [comment]
> When I opened the link, it returned HTTP Error 410 Gone.

Because it's an old link. It expired. The actual New link shows 403. 

https://streaming07.cloud9xx.com/videos/hls/x5fUgwwfFf2JLoftc8EhFQ/1599324706/49227/cd76e43c07dd62dda6d1a1d2bc08eae3/sub.1.m3u8: Server returned 403 Forbidden (access denied)

**Comment by laxuscullen** [comment]
> > Please can anyone help?
> 
> try to use proxy

I have tried with two different ip addresses and same result. You can try it yourself and it will give 403. Can you please guide on how to use headers or referers?

**Comment by sclsj** [comment]
Give the url of the page that is requesting this m3u8. If you know the headers, use --add-header FIELD:VALUE to add headers. You will have to find out the header yourself if you don't post the url of the original page.

**Comment by laxuscullen** [comment]
> Give the url of the page that is requesting this m3u8. If you know the headers, use --add-header FIELD:VALUE to add headers. You will have to find out the header yourself if you don't post the url of the original page.

Hi! So this is the website https://gogoanime.to and their videos use the m3u8 link to play the videos. I am sending the m3u8 link here but when you guys will see it it will expire. Is this complete information?

**Comment by laxuscullen** [comment]
Why the hell was my issue closed??? I am trying my best here to provide information why was it closed when I didn't even get any answer to my issue?
