### ISSUE TITLE
Audiomack: can't download songs

### ISSUE THREAD

**Issue by phxgg** [ytdl-org/youtube-dl#26523]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://audiomack.com/Sinfuul/song/flossy']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-82966-g6993bb4
[debug] Proxy map: {}
[generic] flossy: Requesting header
WARNING: Falling back on generic information extractor.
[generic] flossy: Downloading webpage
[generic] flossy: Extracting information
ERROR: Unsupported URL: https://audiomack.com/Sinfuul/song/flossy
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://audiomack.com/Sinfuul/song/flossy
```

## Description

Just trying to download a song from audiomack.
The URL is this one: https://audiomack.com/Sinfuul/song/flossy
What I ran: ```youtube-dl https://audiomack.com/Sinfuul/song/flossy```
I've been downloading tracks the same way from audiomack before. I've only had this issue now.

Edit: forgot to write a proper title. Sorry about that.

**Comment by moonmuaaz000** [comment]
try using Video DownloaderHelper Extension

**Comment by moonmuaaz000** [comment]
use Video DownloadHelper Extension temporarily
