### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by dension0** [ytdl-org/youtube-dl#26528]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=JCyuXhou9_0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-9-amd64-x86_64-with-debian-10.4
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] JCyuXhou9_0: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "./youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```

## Description

Debian 10 64bit  system. More than 1 weaks get this. I tried to wait some days but the results same.

**Comment by blackjack4494** [comment]
> PS D:\gitkraken\youtube-dl> python3 -m youtube_dlc https://www.youtube.com/watch?v=JCyuXhou9_0 -F -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=JCyuXhou9_0', '-F', '-v']    
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.09.03.1
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[youtube] JCyuXhou9_0: Downloading webpage
[youtube] {136} signature length 107, html5 player bcf2977e
[youtube] JCyuXhou9_0: Downloading player https://www.youtube.com/s/player/bcf2977e/player_ias.vflset/en_US/base.js
[youtube] {135} signature length 107, html5 player bcf2977e
[youtube] {134} signature length 103, html5 player bcf2977e
[youtube] JCyuXhou9_0: Downloading player https://www.youtube.com/s/player/bcf2977e/player_ias.vflset/en_US/base.js
[youtube] {133} signature length 103, html5 player bcf2977e
[youtube] {160} signature length 107, html5 player bcf2977e
[youtube] {140} signature length 107, html5 player bcf2977e
[youtube] JCyuXhou9_0: Downloading MPD manifest
[info] Available formats for JCyuXhou9_0:
format code  extension  resolution note
139          m4a        audio only DASH audio   64k , m4a_dash container, mp4a.40.5@ 48k (24000Hz)
140          m4a        audio only DASH audio  144k , m4a_dash container, mp4a.40.2@128k (48000Hz)
160          mp4        256x144    DASH video  121k , mp4_dash container, avc1.4d400c, 30fps, video only
133          mp4        426x240    DASH video  255k , mp4_dash container, avc1.4d4015, 30fps, video only
134          mp4        640x360    DASH video  625k , mp4_dash container, avc1.4d401e, 30fps, video only
135          mp4        854x480    DASH video  803k , mp4_dash container, avc1.4d401f, 30fps, video only
136          mp4        1280x720   DASH video 1275k , mp4_dash container, avc1.4d401f, 30fps, video only (best)

No problems here. Is that a server or your home computer?

**Comment by ilike2burnthing** [comment]
https://github.com/ytdl-org/youtube-dl/issues/23638

**Comment by dension0** [comment]
It is server, it is VPS.

**Comment by ilike2burnthing** [comment]
https://github.com/ytdl-org/youtube-dl#network-options
