### ISSUE TITLE
Can't download video from youtube: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by blueacker** [ytdl-org/youtube-dl#26520]
The error occurs when I try to download this link: https://www.youtube.com/watch?v=SFK3giQxVYg

[youtube] SFK3giQxVYg: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by CuriousCod** [comment]
I'm also running into this issue at the moment. However you can workaround it by including cookies with the option:
"youtubedl.exe [URL] --cookies cookies.txt"

https://askubuntu.com/questions/1220266/youtube-dl-do-not-working-http-error-429-too-many-requests-how-can-i-solve-this
