### ISSUE TITLE
Reruns on Twitch are no longer recognized

### ISSUE THREAD

**Issue by reallyuniquename** [ytdl-org/youtube-dl#26535]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\>youtube-dl -v https://www.twitch.tv/reckful
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.twitch.tv/reckful']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.09.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Proxy map: {}
[twitch:stream] reckful: Downloading access token JSON
[twitch:stream] 9072112: Downloading stream JSON
ERROR: 9072112 is offline
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\twitch.py", line 789, in _real_extract
youtube_dl.utils.ExtractorError: 9072112 is offline
```

## Description

Rerun is a stream that is not live but active. Obviously, you can watch it. 

Reruns on Twitch are no longer recognized by youtube-dl. Youtube-dl immediately exits after flagging such channels as offline while they aren't.

I don't think it has anything to do with the last update, I tried previous version `2020.07.28` that worked like a week ago but now it fails as well.

**Channel from the log might become live or offline any time now.** To find a channel that has a rerun on you have to scroll through this page - https://www.twitch.tv/search?term=rerun&type=channels

That's how it looks on Twitch, rerun vs live - 
![image](https://user-images.githubusercontent.com/10516120/92333678-1bc3e000-f090-11ea-9d86-32b62f86f4bb.png)

**Comment by reallyuniquename** [comment]
I manually checked `https://api.twitch.tv/kraken/streams/123456` endpoint and it seems it no longer lists rerun streans at all?

**Comment by marchom** [comment]
I'm hitting the same issue.

**Comment by reallyuniquename** [comment]
Has anyone tried streamlink? Does it suffer from the same issue?

**Comment by predakanga** [comment]
Streamlink doesn't have the same issue - I used it yesterday to record a rerun that yt-dl wouldn't grab.

For the record, I used streamlink v1.5.0, and I did notice a slight bit of weirdness; there was no "source" quality available. Not sure if that's relevant.

> predakanga@z-space:~$ youtube-dl https://www.twitch.tv/criticalrole
> [twitch:stream] criticalrole: Downloading access token JSON
> [twitch:stream] 229729353: Downloading stream JSON
> ERROR: 229729353 is offline
> 
> predakanga@z-space:~$ streamlink https://www.twitch.tv/criticalrole best -o cr.ts
> [cli][info] Found matching plugin twitch for URL https://www.twitch.tv/criticalrole
> [cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p_alt, 720p (best)
> [cli][info] Opening stream: 720p (hls)
