### ISSUE TITLE
"This video is not available" trying to download "auto-generated by Youtube" videos (which are country restricted)

### ISSUE THREAD

**Issue by hiccup372005** [ytdl-org/youtube-dl#26531]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
D:\>youtube-dl -v OLAK5uy_lR5x4ju7E-UUnMDTgpRFqC1RXoQ5w7CT0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'OLAK5uy_lR5x4ju7E-UUnMDTgpRFqC1RXoQ5w7CT0']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.09.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-08-24-3477feb
[debug] Proxy map: {}
[youtube:playlist] OLAK5uy_lR5x4ju7E-UUnMDTgpRFqC1RXoQ5w7CT0: Downloading webpage
[download] Downloading playlist: How To Train Your Dragon (Music From The Motion Picture)
[youtube:playlist] playlist How To Train Your Dragon (Music From The Motion Picture): Downloading 25 videos
[download] Downloading video 1 of 25
[youtube] hNFM2f4BvAo: Downloading webpage
[youtube] hNFM2f4BvAo: Downloading embed webpage
[youtube] hNFM2f4BvAo: Refetching age-gated info webpage
ERROR: This video is not available.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpquf06fea\build\youtube_dl\extractor\youtube.py", line 2213, in _real_extract
youtube_dl.utils.ExtractorError: This video is not available.
```

## Description

Playlist used for demonstration: https://www.youtube.com/playlist?list=OLAK5uy_lR5x4ju7E-UUnMDTgpRFqC1RXoQ5w7CT0
*You might need to use a VPN to view the playlist because I cannot view it unless my VPN's country is US*

It seems that youtube-dl cannot download "auto generated by YouTube" videos, my guess is because these videos are country restricted, because I cannot view the playlist unless I change my VPN country to US.

I checked 2020.09.06's (just release, newest) change log and found a similar closed issue with age restricted videos in version 2020.07.28. I tried to download a random age restricted video with version 2020.07.28, first without cookie (it doesnt work), then with cookie (it work). I also tried to download that video with version 2020.09.06 with and without the cookie and both work. 

Unlike the age restricted videos, I tried using 2020.07.28 and 2020.09.06 with and without cookie (using the cookie.txt extension to download the cookie of the playlist tab, then add `--cookie D:\cookie.txt ` before the playlist url) and **all 4** of them **does not work**. This separate the "auto generated by YouTube" videos issue (or country restricted, i dont know) and the age restricted videos issue (which is fixed) completely.

I don't really know how to fix this or any work around, since I use a VPN to bypass country restricted videos, but it looks like youtube-dl cannot.

**Comment by HeySteets** [comment]
This looks like it might be a one-off on your end - I'm able to download the linked playlist using the latest version of youtube-dl _(2020.07.28, Win10 2004, 64bit)_ with no problem, even when using a VPN.

**Comment by hiccup372005** [comment]
@HeySteets 
The problem is where are you now? I need to use a VPN to bypass country restriction, since I'm in Vietnam at the moment.
The VPN is **not** the problem here, the problem is **youtube-dl does not bypass country restriction**.

**Comment by HeySteets** [comment]
I'm in the US - but I think I might've misinterpreted your issue.
You're saying that, when using a VPN, everything is fine. But when you attempt to use youtube-dl without it, you can't download country-restricted videos because of your location?
Unfortunately, I don't believe there _is_ a way to bypass that - if YouTube is blocking the content based on the IP from which the traffic is originating, there isn't much that a third-party program will be able to do in terms of getting around that.

**Comment by hiccup372005** [comment]
Just in case you misinterpreted, browser / youtube-dl = unable to watch / download
browser + VPN extension = able to watch
youtube-dl unable to download
I guess you're right, there isn't a way to bypass that...
I'm gonna close this issue I guess
