### ISSUE TITLE
https://videa.hu - Broken site support

### ISSUE THREAD

**Issue by pcroland** [ytdl-org/youtube-dl#26542]
Hi!

Videa.hu doesn't work, output:

```ERROR: Unable to download XML: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

**Comment by adrianheine** [comment]
Might be fixed by #26301. Can you give a link?

**Comment by pcroland** [comment]
https://videa.hu/videok/film-animacio/the-reliant-a-bizakodo-2019-rXUJsHwKHd1Q0HTN

**Comment by blackjack4494** [comment]
> $ youtube-dlc https://videa.hu/videok/film-animacio/the-reliant-a-bizakodo-2019-rXUJsHwKHd1Q0HTN -F -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://videa.hu/videok/film-animacio/the-reliant-a-bizakodo-2019-rXUJsHwKHd1Q0HTN', '-F', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.09.03
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.17, ffprobe 2.8.17
[debug] Proxy map: {}
[Videa] rXUJsHwKHd1Q0HTN: Downloading webpage
[Videa] rXUJsHwKHd1Q0HTN: Downloading webpage
[Videa] rXUJsHwKHd1Q0HTN: Downloading webpage
[info] Available formats for rXUJsHwKHd1Q0HTN:
format code  extension  resolution note
240p         mp4        568x240    avc1.42c015, mp4a.40.2
360p         mp4        852x360    avc1.4d401e, mp4a.40.2
480p         mp4        1136x480   avc1.4d401f, mp4a.40.2 (best)

The PR definitely works @adrianheine @pcroland
