### ISSUE TITLE
SRF (Swiss Televison) broke site

### ISSUE THREAD

**Issue by habi** [ytdl-org/youtube-dl#26556]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

```
youtube-dl -v https://www.srf.ch/play/tv/dok/video/alkohol---der-globale-rausch\?urn\=urn:srf:video:a763f288-c32a-4352-a33d-ffe5ce114ad2
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.srf.ch/play/tv/dok/video/alkohol---der-globale-rausch?urn=urn:srf:video:a763f288-c32a-4352-a33d-ffe5ce114ad2']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.06
[debug] Python version 3.7.7 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] alkohol---der-globale-rausch?urn=urn:srf:video:a763f288-c32a-4352-a33d-ffe5ce114ad2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] alkohol---der-globale-rausch?urn=urn:srf:video:a763f288-c32a-4352-a33d-ffe5ce114ad2: Downloading webpage
[generic] alkohol---der-globale-rausch?urn=urn:srf:video:a763f288-c32a-4352-a33d-ffe5ce114ad2: Extracting information
ERROR: Unsupported URL: https://www.srf.ch/play/tv/dok/video/alkohol---der-globale-rausch?urn=urn:srf:video:a763f288-c32a-4352-a33d-ffe5ce114ad2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.srf.ch/play/tv/dok/video/alkohol---der-globale-rausch?urn=urn:srf:video:a763f288-c32a-4352-a33d-ffe5ce114ad2

```

## Description

I've used `youtube-dl` before for downloading DOKs from SRF (to watch in the train).
The linked DOK cannot be downloaded with a recent version.

**Comment by habi** [comment]
Interestingly, the URL pasted from the address window (https://www.srf.ch/play/tv/dok/video/alkohol---der-globale-rausch\?urn\=urn:srf:video:a763f288-c32a-4352-a33d-ffe5ce114ad2) *does not* work when pasted back in the browser.
The URL from the `Command-line args` (https://www.srf.ch/play/tv/dok/video/alkohol---der-globale-rausch?urn=urn:srf:video:a763f288-c32a-4352-a33d-ffe5ce114ad2) *does* work when pasted back in the browser.

**Comment by habi** [comment]
`youtube-dl https://srf.ch/play/tv/redirect/detail/a763f288-c32a-4352-a33d-ffe5ce114ad2` also does not work.

**Comment by habi** [comment]
Related to https://github.com/ytdl-org/youtube-dl/issues/26555 :)

**Comment by Surkal** [comment]
It's georestricted to Switzerland, but try https://www.srf.ch/play/tv/dok/video/alkohol?id=a763f288-c32a-4352-a33d-ffe5ce114ad2

**Comment by github-com-bqm** [comment]
I have the same issue. youtube-dl Worked until yesterday for srf.ch URLs, and it's not working anymore today. I am located in Switzerland. Anything I can do to help debug this issue?

**Comment by github-com-bqm** [comment]
I can also confirm, that the file habi is trying to download still worked earlier, sind I successfully downloaded the same video some days back...

**Comment by habi** [comment]
> It's georestricted to Switzerland, but try https://www.srf.ch/play/tv/dok/video/alkohol?id=a763f288-c32a-4352-a33d-ffe5ce114ad2 <https://www.srf.ch/play/tv/dok/video/alkohol?id=a763f288-c32a-4352-a33d-ffe5ce114ad2>I *am* located in Switzerland with a Swiss ISP.
How did can I directly get this URL?

**Comment by habi** [comment]
> It's georestricted to Switzerland, but try https://www.srf.ch/play/tv/dok/video/alkohol?id=a763f288-c32a-4352-a33d-ffe5ce114ad2

I *am* located in Switzerland with a Swiss ISP.
How did can I directly get this URL?

**Comment by github-com-bqm** [comment]
You get this URL by taking the id from your original URL (everything after video: ) and then adding this to this:  https://www.srf.ch/play/tv/dok/video/alkohol?id=

I just tried this with another video, and it works!

**Comment by github-com-bqm** [comment]
You actually don't have to give the whole keyword "alkohol" in the base part of the URL. One letter is enough. So you can take this as base:

https://www.srf.ch/play/tv/dok/video/a?id=

And then add the id to it, giving you:

https://www.srf.ch/play/tv/dok/video/a?id=a763f288-c32a-4352-a33d-ffe5ce114ad2

**Comment by Surkal** [comment]
in `extractor/srgssr.py`, line 109 :
```python
_VALID_URL = r'''(?x)
                    https?://
                        (?:(?:www|play)\.)?
                        (?P<bu>srf|rts|rsi|rtr|swissinfo)\.ch/play/(?:tv|radio)/
                        (?:
                            [^/]+/(?P<type>video|audio)/[^?]+|
                            popup(?P<type_2>video|audio)player
                        )
                        \?id=(?P<id>[0-9a-f\-]{36}|\d+)
                    '''
```
This regular expression must be updated to capture new URLs.

**Comment by habi** [comment]
Sorry to have been imprecise:

> ﻿You get this URL by taking the id from your original URL (everything after video: ) and then adding this to this: https://www.srf.ch/play/tv/dok/video/alkohol?id=

So without manual intervention and manipulation of the URL it‘s not possible?

**Comment by TheRealDude2** [comment]
Maybe first workaround. Change the line (line 117 +/- 10) in srgssr.py extractor.
                       `\?id=(?P<id>[0-9a-f\-]{36}|\d+)`
to
                       `\?.*(?P<id>[0-9a-f\-]{36})`

Tested with the Tagesschau link. I think there will be problems with other links. I will try to add the old style as fallback too.

**Comment by github-com-bqm** [comment]
> Sorry to have been imprecise:
> ﻿You get this URL by taking the id from your original URL (everything after video: ) and then adding this to this: https://www.srf.ch/play/tv/dok/video/alkohol?id=
> So without manual intervention and manipulation of the URL it‘s not possible?

For the time being you have to manipulate the URL yourself. Or fix the source code as given above, and compile youtube-dl yourself. But since it's now clear what the issue is, and the resolution is straight forward, a fixed version should be released soon...

**Comment by github-com-bqm** [comment]
And it's actually even simpler to change the URL, so that the current regex will pars it: Simply add ?id= after video: in an existing URL. So

https://www.srf.ch/play/tv/dok/video/alkohol---der-globale-rausch?urn=urn:srf:video:a763f288-c32a-4352-a33d-ffe5ce114ad2

becomes

https://www.srf.ch/play/tv/dok/video/alkohol---der-globale-rausch?urn=urn:srf:video:?id=a763f288-c32a-4352-a33d-ffe5ce114ad

This URL is not syntactically correct, but this doesn't matter, since youtube-dl only has to extract the id at the end. So for the time being this is a simple workaround.

**Comment by TheRealDude2** [comment]
I think we have to add an URL to _TESTS for the new URL pattern also. Maybe someone can provide a long living URL accessible from outside CH? I just tested it with the tagesschau URLs and these just living for a few days.

**Comment by github-com-bqm** [comment]
Try this one (It's from June. I just tested in on a server in Germany. Doesn't seem to be geo-restricted, and it still works):

https://www.srf.ch/play/tv/meteo/video/abendausgabe?urn=urn:srf:video:c93094be-96a0-43f8-a438-26d128a68805

**Comment by TheRealDude2** [comment]
Thx. Local test works. I add a lazzy testline to the PR. Hope this will enough.
