### ISSUE TITLE
Unable to download a list of videos from an xhamster account

### ISSUE THREAD

**Issue by silvermindphasar** [ytdl-org/youtube-dl#26550]
## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://it.xhamster.com/users/XYZ/videos', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.06
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-10-amd64-x86_64-with-debian-10.5
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[download] Downloading playlist: XYZ
[download] Downloading video 122 of 194
[XHamster] 15003607: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

## Description

Unable to download a list of videos from an xhamster user:  the following message is shown on the screenUnable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError())

**Comment by TheRealDude2** [comment]
You make it hard if you do not give the real link.

However, the video in question is only visible to friends of the user. If you are on his friends list, you have to give the script your account information.

**Comment by silvermindphasar** [comment]
I can't give the account link, I saw that some videos are downloaded and others are not, but all are visible in the clear without friend list

**Comment by TheRealDude2** [comment]
I checked your video from the log again (Video ID 15003607).

The video is only available for friends of the user. When I look at all videos of the user profile, almost half of the oldest videos are only available for friends.

If you can see these videos it is most likely that you are on his friends list and this explains the problem if you don't give youtube-dl your credentials and the behave normally.

If not, the problem is not understandable for me. Maybe someone else has an idea.

**Comment by silvermindphasar** [comment]
perfect, now I understand  was thinking about a software problem but it is not so. thanks again for your message.
