### ISSUE TITLE
TV5 Monde Plus

### ISSUE THREAD

**Issue by Europe57** [ytdl-org/youtube-dl#26559]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.09.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

https://www.tv5mondeplus.com/player/106447362_74079A
https://www.tv5mondeplus.com/player/106255667_74079A

## Description

Hello,

New website catch-up on TV5 Monde, service French TV available in worldwide (no geoblocked).

Adress: https://www.tv5mondeplus.com

Tanks.

**Comment by naszdom** [comment]
Yes I'm getting ERROR: Unsupported URL: https://www.tv5mondeplus.com/fr/player/105031915_74079A
