### ISSUE TITLE
Non-latin channel names does not supported.

### ISSUE THREAD

**Issue by 5x3** [ytdl-org/youtube-dl#26567]
Non-latin channel names does not supported.
in example, I can't download all videos from channel:
'https://www.youtube.com/c/%D0%9C%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C%D0%94%D0%BB%D1%8F%D0%A1%D0%B1%D0%BE%D1%80%D0%BA%D0%B8/videos'

**Comment by 5x3** [comment]
update solve it

**Comment by 5x3** [comment]
update solve it

**Comment by 5x3** [comment]
but downloads only the first video (latest) from list.

**Comment by 5x3** [comment]
but downloads only the first video (latest) from list.

**Comment by adrianheine** [comment]
Works fine for me and downloads all videos (at least in simulation mode)
