### ISSUE TITLE
How can i put the url on cmd for the login?

### ISSUE THREAD

**Issue by smule98** [ytdl-org/youtube-dl#26568]
## Checklist

- [X ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, i don't understand how can i login on a website, how can i put the url on cmd for the login? Thanks

**Comment by sesh** [comment]
See the [Authentication Options](https://github.com/ytdl-org/youtube-dl#authentication-options) section of the README.

If that doesn't work you will need to provide more information, including the site that you're attempting to download from.
