### ISSUE TITLE
ERROR: Unable to extract JS player URL (https://www.youtube.com/watch?v=VIeEbMGKxS4)

### ISSUE THREAD

**Issue by overcranky** [ytdl-org/youtube-dl#26560]
D:\>youtube-dl -f best https://www.youtube.com/watch?v=VIeEbMGKxS4
[youtube] VIeEbMGKxS4: Downloading webpage
[youtube] VIeEbMGKxS4: Downloading embed webpage
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are
using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag a
nd include its complete output.

D:\>youtube-dl -U
youtube-dl is up-to-date (2020.09.06)

D:\>

**Comment by blackjack4494** [comment]
No issues here. Also did you actually read the text you were copy and pasting?

> Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by EricRa** [comment]
I could not reproduce this issue.  I used your exact command, the video started downloading immediately without errors.
