### ISSUE TITLE
svtplay.se

### ISSUE THREAD

**Issue by tligen** [ytdl-org/youtube-dl#26576]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.09.06**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
tle@tl64:~$ youtube-dl -i --verbose https://www.svtplay.se/video/28101832/det-finns-sa-manga-vagar-en-film-om-john-holm
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-i', u'--verbose', u'https://www.svtplay.se/video/28101832/det-finns-sa-manga-vagar-en-film-om-john-holm']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.06
[debug] Python version 2.7.17 (CPython) - Linux-4.4.227-x86_64-Intel-R-_Core-TM-_i3-2120_CPU_@_3.30GHz-with-slackware-14.2
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 78.68.214.114 (SE) as X-Forwarded-For.
[SVTPlay] 28101832: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/tle/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/tle/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/tle/bin/youtube-dl/youtube_dl/extractor/svt.py", line 235, in _real_extract
    webpage, 'video id')

**Comment by 0x9fff00** [comment]
See https://github.com/ytdl-org/youtube-dl/issues/26428#issuecomment-689823144 for a fix
