### ISSUE TITLE
ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

### ISSUE THREAD

**Issue by concons** [ytdl-org/youtube-dl#26585]
ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

**Comment by leedoyle** [comment]
@dstftw  you literally have 2 issues with this problem, and you keep closing them. Very productive indeed.

**Comment by leedoyle** [comment]
@concons  which video you were having this problem with?
