### ISSUE TITLE
Print JSON and show progress

### ISSUE THREAD

**Issue by abvbv** [ytdl-org/youtube-dl#26596]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.09.14**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I would like to download a video and get the JSON with full info about it and see the progress within one `youtube-dl` session.

There're these lines in [`__init__.py`](https://github.com/ytdl-org/youtube-dl/blob/826dcff99cd0a44ec5fa94f0e0201f5115d097ef/youtube_dl/__init__.py#L247) that prevent printing of progress:

    any_printing = opts.print_json
    ...
        'quiet': (opts.quiet or any_getting or any_printing),

Probably a new option would help. There's `--no-progress` option, so maybe an enforcing option might help, something like `youtube-dl --print-json --progess $url `.

**Comment by dstftw** [comment]
This will introduce ambiguity since both JSON and progress are written to stdout and it would be impossible to safely classify whether new line is JSON or progress data.
What you can do is to use `--console-title` to show progress in title bar.

**Comment by abvbv** [comment]
> What you can do is to use `--console-title` to show progress in title bar.

Do you think there are any other approaches? I need this to automate some workflow, so there are no title bars in my case.

What if we add a `[json]` prefix before JSON output, similar to `[download]` and others?

**Comment by dstftw** [comment]
You can just embed it in python code and receiving progress via a hook.
No prefixes can be added since this will break existing clients.

**Comment by abvbv** [comment]
Thanks for your quick replies!

I'm using youtube-dl from a different programming language, and it will make things a bit harder I think. But anyway, thanks for the suggestion. I'll add a new comment if I come up with a good solution. Until then I'll just call youtube-dl twice: 1) to get a JSON and 2) to download a video.

**Comment by 0xpr03** [comment]
Would be really helpful to print download progress on stderr and json on stdout or vice versa. This way you can extract download progress but also know for example the original title afterwards. (Or to print the original video title additionally to the progress, I can regex that anyway.)
