### ISSUE TITLE
Incomplete oreilly video downloading

### ISSUE THREAD

**Issue by pooryamoh** [ytdl-org/youtube-dl#26597]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '--cookies', 'cookies.txt', 'https://learning.oreilly.com/videos/node-js-the/9781838826864/9781838826864-video1_2']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.14
[debug] Python version 3.9.0rc1 (CPython) - Linux-4.15.0-117-generic-x86_64-with-glibc2.27
[debug] exe versions: none
[debug] Proxy map: {}
[Kaltura] 9781838826864-video1_2: Downloading webpage
[Kaltura] 0_064gmt5e: Downloading video info JSON
[Kaltura] 0_064gmt5e: Checking mp4-523 URL
[Kaltura] 0_064gmt5e: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1926081/sp/192608100/playManifest/entryId/0_064gmt5e/format/url/protocol/http/flavorId/0_sdgossl5'
[download] Destination: What is Node.js-0_064gmt5e.mp4
[download] 100% of 4.41MiB in 00:00
```

## Description

Downloaded video is first 1 min of whole video that is 4m 42s.

**Comment by dstftw** [comment]
You must provide account credentials for any work on this.

**Comment by pooryamoh** [comment]
Sent through mail

> 
> 
> You must provide account credentials for any work on this.

Sent through mail

**Comment by dstftw** [comment]
For safari you must authenticate with credentials not cookies.
