### ISSUE TITLE
option to get playlist title only

### ISSUE THREAD

**Issue by AlwaysBeCalm** [ytdl-org/youtube-dl#26609]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.09.14**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

Hi, why don't add an option to get the playlist title?
like '-e' but for playlists

because I'm working on a script for automatically recognizing either the input url is a playlist or a normal video, and I need to get the playlist title before start working with the playlist url.

Thanks :+1: :+1:

**Comment by dstftw** [comment]
Parse JSON output.
