### ISSUE TITLE
Unable to download private videos of my youtube channel

### ISSUE THREAD

**Issue by zyadomer999** [ytdl-org/youtube-dl#26606]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bug tracker for similar questions including closed ones

## Question

Hello
I have been trying for a long time to download private videos on my youtube channel but I could find nothing and tries everything nothing worked. I found some resources that say it is related to the newer versions of youtube-dl, is it right? Please someone help me
<img width="1189" alt="Screen Shot 2020-09-17 at 12 34 36 AM" src="https://user-images.githubusercontent.com/66646536/93394900-9b666180-f87d-11ea-9a46-0b2095f2ec2e.png">

**Comment by dstftw** [comment]
Report to support of software you're using. youtube-dl has nothing to do with JavsScript.
