### ISSUE TITLE
downloaded files from YT are uneditable. hard crashing upon editing file. 

### ISSUE THREAD

**Issue by robbiedobbie1** [ytdl-org/youtube-dl#26605]
## Checklist

- [ X ] I'm reporting a broken site support
- [ X ] I've verified that I'm running youtube-dl version **2020.09.14**
- [ X  ] I've checked that all provided URLs are alive and playable in a browser
- [ X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [  X ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
C:\Users\ME\Desktop\Rjnresources> youtube-dl.exe -v -k https://www.youtube.com/watch?v=Bo9Vu_X6lKw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-k', 'https://www.youtube.com/watch?v=Bo9Vu_X6lKw']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.09.06
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-94597-g74e6800381, ffprobe N-94597-g74e6800381
[debug] Proxy map: {}
[youtube] Bo9Vu_X6lKw: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r4---sn-8pgbpohxqp5-aig6.googlevideo.com/videoplayback?expire=1600309862&ei=BXZiX9SJO
LvAsAKtjJf4Bw&ip=80.7.82.241&id=o-ANQXMzpTJ5-O_YRc95gXPSxjFUodrKtx2OlCqigmPy_B&itag=299&aitags=133%2C134%2C135%2C136%2C137%2C
160%2C242%2C243%2C244%2C247%2C248%2C278%2C298%2C299%2C302%2C303%2C394%2C395%2C396%2C397&source=youtube&requiressl=yes&mh=xA&m
m=31%2C26&mn=sn-8pgbpohxqp5-aig6%2Csn-5hne6nsr&ms=au%2Conr&mv=m&mvi=4&pl=24&initcwndbps=1205000&vprv=1&mime=video%2Fmp4&gir=y
es&clen=34497904&dur=598.133&lmt=1576415867227652&mt=1600288122&fvip=4&keepalive=yes&fexp=23915655&c=WEB&txp=5535432&sparams=
expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAI3SRN1S4HktG7vNv
lDhqYwU4yu2bHAgpIOO1eq3BDTpAiByOVtZ0Vx-te4V-y3deg3pQ90KdRBM_Fo6vQ2Ju6Sbyg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2C
initcwndbps&lsig=AG3C_xAwRAIgcQgLx62RovUu0zcNGAI0o1oe2VxjthSJ2lKjjOVFrVICIBCBxXOzGoTkWCUOVDtUhKRsocLAvPUI1JyiMb5MkdxN&ratebyp
ass=yes'
[download] Destination: KILLDOZER - How a Man Made His Own Tank _ Tales From the Bottle-Bo9Vu_X6lKw.f299.mp4
[download] 100% of 32.90MiB in 00:04
[debug] Invoking downloader on 'https://r4---sn-8pgbpohxqp5-aig6.googlevideo.com/videoplayback?expire=1600309862&ei=BXZiX9SJO
LvAsAKtjJf4Bw&ip=80.7.82.241&id=o-ANQXMzpTJ5-O_YRc95gXPSxjFUodrKtx2OlCqigmPy_B&itag=251&source=youtube&requiressl=yes&mh=xA&m
m=31%2C26&mn=sn-8pgbpohxqp5-aig6%2Csn-5hne6nsr&ms=au%2Conr&mv=m&mvi=4&pl=24&initcwndbps=1205000&vprv=1&mime=audio%2Fwebm&gir=
yes&clen=10063921&dur=598.161&lmt=1576415358595777&mt=1600288122&fvip=4&keepalive=yes&fexp=23915655&c=WEB&txp=5531432&sparams
=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgc_0Ip1rQ_BY2sKoNLf
Y-8R5eYyzRQ-y8C4jra8PihYQCIQDxjVanmARt6jQqB3Q1GUERnGc6ESUCGnDPRGnzZkv0rQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Ci
nitcwndbps&lsig=AG3C_xAwRAIgcQgLx62RovUu0zcNGAI0o1oe2VxjthSJ2lKjjOVFrVICIBCBxXOzGoTkWCUOVDtUhKRsocLAvPUI1JyiMb5MkdxN&ratebypa
ss=yes'
[download] Destination: KILLDOZER - How a Man Made His Own Tank _ Tales From the Bottle-Bo9Vu_X6lKw.f251.webm
[download] 100% of 9.60MiB in 00:01
[ffmpeg] Merging formats into "KILLDOZER - How a Man Made His Own Tank _ Tales From the Bottle-Bo9Vu_X6lKw.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:KILLDOZER - How a Man Made His Own Tank _ Tales From
the Bottle-Bo9Vu_X6lKw.f299.mp4" -i "file:KILLDOZER - How a Man Made His Own Tank _ Tales From the Bottle-Bo9Vu_X6lKw.f251.we
bm" -c copy -map "0:v:0" -map "1:a:0" "file:KILLDOZER - How a Man Made His Own Tank _ Tales From the Bottle-Bo9Vu_X6lKw.temp.
mkv"

## Description

WRITE DESCRIPTION HERE
The downloaded files (numerous, in fact all that are merged in to mkv) that are "incompatible for merge" always end up wrapped in an .mkv.  This is fine and the file will play in VLC media player.  The issue is when ever trying to convert, or edit the .mkv file results in an almost instanteous hard crash of the PC (Win 7, 64bit, 16GB Ram, Nvidia 1080 TI (founders edition)
I have tried all the common softwares, the best analysis i can get is by latest version of Handbrake log, that reports part of the file the file in memory is 6 bytes instead of the expected 4.  I attach that log below.  Even direct attempt at conversion by FFMPEG using  "ffmpeg -i input.mkv output.mp4" directly crashes the PC a few moments in.  
Please see the Handbrake Log below. 
"
"________HANDBRAKE VERBOSE LOG_______"
HandBrake 1.3.3 (2020061300)
OS: Microsoft Windows NT 6.1.7601 Service Pack 1
CPU: AMD FX(tm)-9590 Eight-Core Processor           
Ram: 16346 MB, 
GPU Information:
  NVIDIA GeForce GTX 1080 Ti - 27.21.14.5206
Screen: 2048x1152
Temp Dir: C:\Users\Rob\AppData\Local\Temp\
Install Dir: C:\Program Files\HandBrake133
Data Dir: C:\Users\Rob\AppData\Roaming\HandBrake

-------------------------------------------

[21:52:40] Compile-time hardening features are enabled
[21:52:41] Nvenc version 10.0
[21:53:47] hb_init: starting libhb thread
[21:53:47] thread 2 started ("libhb")

 # Starting Scan ...

[21:53:47] CPU:
[21:53:47]  - logical processor count: 8
[21:53:47] Intel Quick Sync Video support: no
[21:53:47] hb_scan: path=C:\Users\Rob\Desktop\KILLDOZER.mkv, title_index=0
[21:53:47] thread 3 started ("scan")
udfread ERROR: ECMA 167 Volume Recognition failed
src/libbluray/disc/disc.c:323: failed opening UDF image C:\Users\Rob\Desktop\KILLDOZER.mkv
src/libbluray/disc/disc.c:424: error opening file BDMV\index.bdmv
src/libbluray/disc/disc.c:424: error opening file BDMV\BACKUP\index.bdmv
src/libbluray/bluray.c:2585: nav_get_title_list(C:\Users\Rob\Desktop\KILLDOZER.mkv\) failed
[21:53:47] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 6.0.1
libdvdread: Encrypted DVD support unavailable.
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[21:53:47] dvd: not a dvd - trying as a stream/file instead
[matroska,webm @ 00000000008bb880] Length 6 indicated by an EBML number's first byte 0x04 at pos 883 (0x373) exceeds max length 4.
[matroska,webm @ 00000000008bb880] Duplicate element
[matroska,webm @ 00000000008bb880] 0x00 at pos 178 (0xb2) invalid as first byte of an EBML number
[matroska,webm @ 00000000008bb880] Duplicate element
[matroska,webm @ 00000000008bb880] Element at 0x59 ending at 0x354dbb8c53abe6 exceeds containing master element ending at 0x1405
[matroska,webm @ 00000000008bb880] Duplicate element
[matroska,webm @ 00000000008bb880] Element at 0x68 ending at 0x374dbb8e541b exceeds containing master element ending at 0x1414
[matroska,webm @ 00000000008bb880] Element at 0x77 ending at 0xa49340ec017f exceeds containing master element ending at 0x1423
[matroska,webm @ 00000000008bb880] Length 6 indicated by an EBML number's first byte 0x04 at pos 883 (0x373) exceeds max length 4.
Input #0, matroska,webm, from 'C:\Users\Rob\Desktop\KILLDOZER.mkv':
  Metadata:
    MINOR_VERSION   : 0
    COMPATIBLE_BRANDS: iso6avc1mp41
    MAJOR_BRAND     : dash
    ENCODER         : Lavf58.31.101
  Duration: 00:09:58.16, start: -0.007000, bitrate: 593 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 1k tbn, 120 tbc (default)
    Metadata:
      HANDLER_NAME    : ISO Media file produced by ROB ?
    Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
    Stream #0:2: Video: h264, none(tv, bt709, progressive), 1920x1080, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 1k tbn, 2k tbc (default)
    Metadata:
      HANDLER_NAME    : ISO Media file produced by ROB ?
    Stream #0:3(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
[21:53:47] Found ffmpeg 0 chapters, container=matroska,webm
[21:53:47] scan: decoding previews for title 1
[matroska,webm @ 000000001e694b80] Length 6 indicated by an EBML number's first byte 0x04 at pos 883 (0x373) exceeds max length 4.
[matroska,webm @ 000000001e694b80] Duplicate element
[matroska,webm @ 000000001e694b80] 0x00 at pos 178 (0xb2) invalid as first byte of an EBML number
[matroska,webm @ 000000001e694b80] Duplicate element
[matroska,webm @ 000000001e694b80] Element at 0x59 ending at 0x354dbb8c53abe6 exceeds containing master element ending at 0x1405
[matroska,webm @ 000000001e694b80] Duplicate element
[matroska,webm @ 000000001e694b80] Element at 0x68 ending at 0x374dbb8e541b exceeds containing master element ending at 0x1414
[matroska,webm @ 000000001e694b80] Element at 0x77 ending at 0xa49340ec017f exceeds containing master element ending at 0x1423
[matroska,webm @ 000000001e694b80] Length 6 indicated by an EBML number's first byte 0x04 at pos 883 (0x373) exceeds max length 4.
[21:53:47] scan: preview 1
[21:53:47] fifo_close: trashing 0 buffer(s)
[21:53:47] scan: audio 0x1: opus, rate=48000Hz, bitrate=1 English (Opus) (2.0 ch)
[21:53:48] scan: preview 2
[21:53:48] scan: preview 3
[21:53:48] scan: preview 4
[21:53:48] scan: preview 5
[21:53:48] scan: preview 6
[21:53:48] scan: preview 7
[21:53:48] scan: preview 8
[21:53:48] scan: preview 9
[21:53:48] scan: preview 10
[21:53:48] scan: preview 11
[21:53:48] scan: preview 12
[21:53:48] scan: preview 13
[21:53:48] scan: preview 14
[21:53:48] scan: preview 15
[21:53:48] scan: preview 16
[21:53:48] scan: preview 17
[21:53:48] scan: preview 18
[21:53:48] scan: preview 19
[21:53:49] scan: preview 20
[21:53:49] scan: 20 previews, 1920x1080, 60.000 fps, autocrop = 0/0/0/0, aspect 16:9, PAR 1:1
[21:53:49] scan: supported video decoders: avcodec qsv
[21:53:49] scan: removing audio 0x3 because no bitrate found
[21:53:49] Freed 1 buffers of size 1024
[21:53:49] Freed 1 buffers of size 2048
[21:53:49] Freed 1 buffers of size 4096
[21:53:49] Freed 1 buffers of size 8192
[21:53:49] Freed 1 buffers of size 16384
[21:53:49] Freed 1 buffers of size 32768
[21:53:49] Freed 1 buffers of size 65536
[21:53:49] Freed 1 buffers of size 131072
[21:53:49] Freed 1 buffers of size 262144
[21:53:49] Freed 2 buffers of size 4194304
[21:53:49] Allocated 8911872 bytes of buffers on this pass and Freed 8911872 bytes, 0 bytes leaked
[21:53:49] thread 3 exited ("scan")
[21:53:49] thread 3 joined ("scan")
[21:53:49] libhb: scan thread found 1 valid title(s)

 # Processing Scan Information ...

 # Scan Finished ...
"
Please help. I just want to take a snippet of a video by editing in Vegas 16 platinum, or shotcut or anything, but NOTHING can edit the downloaded and 'merged' video/audio nor convert it again to something else.

**Comment by robbiedobbie1** [comment]
Please let me know if you need more information or if i have done something wrong.  
Many thanks
Rob

**Comment by dstftw** [comment]
Report to video editing software used. ffmpeg has no problems editing or cutting such videos.

**Comment by robbiedobbie1** [comment]
ALL fail. else i would not report it.  see the handbreak log.

**Comment by robbiedobbie1** [comment]
this is BS. dont close stuff that you've not tested. if you have tested, download the video i have used as example,  edit it, then upload it to a private audience on YT and send me the link.  YOU CAN'T EDIT IT.
