### ISSUE TITLE
NO RATE SPECIFIED - error: invalid rate limit specified with --all-subs

### ISSUE THREAD

**Issue by dbareis** [ytdl-org/youtube-dl#26611]
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

```
> youtube-dl.exe -verbose --console-title --write-description -write-info-json --write-annotations --all-subs "https://www.youtube.com/watch?v=Gc701wXxctw"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-verbose', '--console-title', '--write-description', '-write-info-json', '--write-annotations', '--all-subs', 'https://www.youtube.com/watch?v=Gc701wXxctw']
Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: invalid rate limit specified
>
```

The error message doesn't match watever the problem is as none of the parameters adjust the rate limit.  It seems to involve '--all-subs' in combination with another of the parameters as using it on it's own works and using all other parameters on the own works.

**Comment by dstftw** [comment]
Missing dash in `-write-info-json`.

**Comment by dbareis** [comment]
Sorry missed that but if it thought it was a "-w" that is still not rate related so the error message is still wrong.

**Comment by dstftw** [comment]
`-write-info-json` means `-w -r ite-info-json` where `ite-info-json` is clearly an invalid rate limit.
