### ISSUE TITLE
Unable to download videos although I am using latest version of youtube-dl

### ISSUE THREAD

**Issue by bhawanaprasain** [ytdl-org/youtube-dl#26625]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[youtube] jD7FnbI76Hg: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I am using ubuntu 20.04 and the version of youtube-dl is 2020.09.14. Everything is upto date and I am unable to download videos from youtube .

**Comment by llacb47** [comment]
https://github.com/ytdl-org/youtube-dl/issues/23638
