### ISSUE TITLE
Kodik.cc (Балансер Kodik)

### ISSUE THREAD

**Issue by Nyanpasu2020** [ytdl-org/youtube-dl#26624]
Нужно выпрямить ссылку с балансера Kodik
https://doramy.club/10015-adzin-poluchelovek.html

Error response:
youtube-dl "https://doramy.club/10015-adzin-poluchelovek.html"
[generic] 10015-adzin-poluchelovek: Requesting header
WARNING: Could not send HEAD request to https://doramy.club/10015-adzin-poluchelovek.html: HTTP Error 403: Forbidden
[generic] 10015-adzin-poluchelovek: Downloading webpage
ERROR: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:748)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:748)'),))

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).

**Comment by Nyanpasu2020** [comment]
> youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).

Если я или кто-то другой создаст extractor для этого сайта, что вы будете делать?
