### ISSUE TITLE
some questions on downloading videos by the playlist of somone channel  

### ISSUE THREAD

**Issue by wansuiye09** [ytdl-org/youtube-dl#26627]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

1. When I have downloaded some videos of one channel and I just download the videos by the time which is released reversely. How can I just download the newest video which I have not downloaded by the playlist and if the program checked the next video has been downloaded, and I want to exit the procedure of downloading.
2. The similar question of the question 1, if I want to download the time range from sometime to sometime but I dont want to check the whole playlist ,if the time is before my timerange ,I want to exit the procedure of downloading.

Best wishes!!

**Comment by dstftw** [comment]
1. Download archive.
2. You have no guarantee playlist is even sorted by date at all.
