### ISSUE TITLE
Please help - how to download using youtube-dl <<getting error message>>

### ISSUE THREAD

**Issue by manishjha143** [ytdl-org/youtube-dl#26635]
youtube-dl  https://www.hotstar.com/in/tv/ek-veer-ki-ardaas-veera/316/gunjan-lies-to-ratan/1000004851
[hotstar] 1000004851: Downloading webpage
[hotstar] 1000004851: Downloading JSON metadata
[hotstar] 1000004851: Downloading m3u8 information
ERROR: This video is not available from your location due to geo restriction
This video is available in India.
You might want to use a VPN or a proxy server (with --proxy) to workaround.

**Comment by remitamine** [comment]
```
You might want to use a VPN or a proxy server (with --proxy) to workaround.
```
