### ISSUE TITLE
The application was unable to start correctly 0xc00007b

### ISSUE THREAD

**Issue by benninkcorien** [ytdl-org/youtube-dl#26649]
I can't install youtube-dl2020.09.20 on windows 10.

## Checklist

- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

I can't generate this

## Description

Python 3.8.5
Downloaded youtube-dl 2020.09.20 to C:\YouTubeDL
Added C:\YouTubeDL to PATH
Installed Microsoft Visual C++ 2010 Redistributable Package (x86)
Rebooted laptop

I can't get it to work.
Every time I try to cal youtube-dl (for example youtube-dl --version), I get a windows error 

    The application was unable to start correctly 0xc00007b

I think this has to do with dependencies, but I've got both Python and Microsoft Visual C++ installed

**Comment by benninkcorien** [comment]
Fixed it: Cause was Windows Smart Screen. (double clicking the .exe file finally gave a blue popup. Disabled Windows Smart Screen and everything is finally running)

**Comment by Kataphractoi** [comment]
weird. when i tried to run it on computer, it opened and closed immediately. I tried opening it in visual studio and it was gibberish and the only whole words was "cannot be run in DOS mode" everything else was rando characters

**Comment by Kataphractoi** [comment]
even with smart screen disabled it had the same behaviour
