### ISSUE TITLE
Age-gated AND Youtube-only playback videos support broken 

### ISSUE THREAD

**Issue by leedoyle** [ytdl-org/youtube-dl#26652]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v MxCRYXg6hLs                                                                                                                                              [1]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'MxCRYXg6hLs']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.5 (CPython) - Linux-5.8.8-4-MANJARO-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] MxCRYXg6hLs: Downloading webpage
[youtube] MxCRYXg6hLs: Downloading embed webpage
[youtube] MxCRYXg6hLs: Refetching age-gated info webpage
ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2231, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.
```

## Description

Apparently, videos that are BOTH Age-gated and Youtube-only e.g. https://www.youtube.com/watch?v=MxCRYXg6hLs  ("author had disabled playback on other websites"), wouldn't download. I've checked another video that is Youtube-only but not age gated (e.g. this one https://www.youtube.com/watch?v=NL1hkIU_e8E ) , and it worked fine.

**Comment by pukkandan** [comment]
@blackjack4494 seems to have a solution on his fork. https://github.com/blackjack4494/youtube-dlc/pull/171

Would you mind if I made a pull request of the same? @blackjack4494
