### ISSUE TITLE
ERROR: No video formats found: Linkedin Learning

### ISSUE THREAD

**Issue by ahmadkakarr** [ytdl-org/youtube-dl#26655]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\ahmad\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\ahmad\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\ahmad\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\linkedin.py", line 127, in _real_extract
    self._sort_formats(formats, ('width', 'height', 'source_preference', 'tbr', 'abr'))
  File "c:\users\ahmad\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\common.py", line 1359, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

**Comment by sheilnaik** [comment]
Use the [cookies.txt](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/) add-on with Firefox and try using it with the `--cookies` flag. That worked for me:

`youtube-dl --cookies "cookies.txt" https://www.linkedin.com/learning/python-essential-training-2/hello-world`

For more complete info, check out [this comment](https://github.com/ytdl-org/youtube-dl/issues/20326#issuecomment-586537418). martin54 explains how to use cookies and also how to use a header in case you're trying to use Linkedin Learning with single sign-on (like I was).

**Comment by rissvann** [comment]
I am getting the same error & it resolved it after just adding the cookies part.
