### ISSUE TITLE
format list not the same as advertised

### ISSUE THREAD

**Issue by jimlynnjulian** [ytdl-org/youtube-dl#26663]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
when I use the -F or --list-formats options, I don't get the same list format I find in posts and general web articles. The format I see is a list with a series of numbers in the first and leftmost column. The list I get has several variables in the first column. The table header is the same.
The variables I get represent two or three versions of the file and begin with 'mpd-' or 'hls-' plus 'unknown, 'full', 'low', 'hd', 'sd', 'lowest', 'mobile, 'quad', and 'ultra'
Samples are
'mpd-7' and 'hls-9750'.
I tried using these in a doownload with the '-F' option but get nowhere.
How do I get the list with numbers in the first column? or use the existing list format?
Thank you,
jlj

**Comment by jimlynnjulian** [comment]
Addendum
Using Windows and ffmpeg is installed in the same directory as ytdl.
Also using latest version of ytdl.

**Comment by dstftw** [comment]
format id is extractor specific.

**Comment by jimlynnjulian** [comment]
Addendum
Using Windows and ffmpeg is installed in the same directory as ytdl.
Also using latest version of ytdl.

**Comment by jimlynnjulian** [comment]
Accepted.
