### ISSUE TITLE
Facebook music videos

### ISSUE THREAD

**Issue by LittleDeng1** [ytdl-org/youtube-dl#26667]
## Checklist

- [x ] I'm reporting a site feature request
- [x ] I've verified that I'm running youtube-dl version **2020.09.20**
- [x ] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

youtube-dl https://www.facebook.com/wearegalantis/videos/620245985559031 -F
[facebook] 620245985559031: Downloading webpage
[facebook] 620245985559031: Downloading webpage
[facebook] 620245985559031: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Only music videos cannot parse, but regular videos can.
I found this link on F12, and it's download-able, in 1080p vp9 ("&bytestart" and "&byteend" argument deleted)
https://video-sjc3-1.xx.fbcdn.net/v/t39.25447-2/10000000_977910769302046_1646886353079979204_n.webm?_nc_cat=101&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdnA5XzVzZWNnb3BfbWlucmVzX2hhbG9fMjYwMGtfZnJhZ18yX3ZpZGVvIn0%3D&_nc_ohc=JCX7T-7baAkAX_3-psc&_nc_ht=video-sjc3-1.xx&oh=22a3e97a3b6d4e15a011a1993204835c&oe=5F8EA6CA

**Comment by dstftw** [comment]
Pass cookies.

**Comment by LittleDeng1** [comment]
@dstftw I can watch w/o login in browser, and both ways are still not working
![image](https://user-images.githubusercontent.com/62782358/93880293-d3532600-fd0f-11ea-8f2c-c57012cb2623.png)
