### ISSUE TITLE
Youtube http 500 error

### ISSUE THREAD

**Issue by rend3r** [ytdl-org/youtube-dl#26677]
youtube-dl 2020.09.20
Trying use this spell:
youtube-dl -i -f best/best https://www.youtube.com/watch?v=4qkz22N3xTI https://www.youtube.com/watch?v=V8NXENqoZH8 https://www.youtube.com/watch?v=dXGiVpJz_do https://www.youtube.com/watch?v=oiPlZHnlVs8 https://www.youtube.com/watch?v=pKK5lNztw5M https://www.youtube.com/watch?v=1i9FOFVS55c https://www.youtube.com/watch?v=_OuXAEmYdmU https://www.youtube.com/watch?v=IS8NVWRLCco
Got server HTTP error: HTTP Error 500: Internal Server Error
Windows 10.

**Comment by rend3r** [comment]
Reopen, please.

**Comment by dstftw** [comment]
Server side Youtube error.

**Comment by rend3r** [comment]
Very strange.
-f 137+140 complete downloads without any problem.
