### ISSUE TITLE
PH blocked in Philippines using Firefox Browsec add-on for browsing the site. Can't DL anymore

### ISSUE THREAD

**Issue by HLesterT** [ytdl-org/youtube-dl#26674]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

ERROR: Unable to download webpage: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it> (caused by URLError(ConnectionRefusedError(10061, 'No connection could be made because the target machine actively refused it', None, 10061, None),))

Not sure on how this work, new here and Youtube-dl has been okay for me for the last month. I have no idea what happened but from what I can search, I'm being block by my ISP directly. Download from other sites works so tried searching  forums/readme/faqs but haven't seen a situation similar to mine

**Comment by zackmark29** [comment]
Anong link yan kababayan? =D
Include mo pati link ng may problema
