### ISSUE TITLE
ERROR: Unsupported URL: https://www.youtube.com/

### ISSUE THREAD

**Issue by blikoor** [ytdl-org/youtube-dl#26682]
**Description**
Youtube-dl is unable to download any videos or live stream videos from YouTube.

**To Reproduce**
1. Create batch file (dlstream.bat) containing the following:
for /f "delims=" %%a in ('youtube-dl -v -f best --hls-prefer-ffmpeg -g https://www.youtube.com/watch?v=9Auq9mYxFEE')  do (ffmpeg -i %%a -c copy download.ts)

2.  Run batch file from console in Windows 10.

**Expected behavior**
Download live stream video from YouTube and saving data to download.ts. This has been tested on Twitch live streams videos and works there as expected, but youtube-dl is unable to download from https:///www.youtube.com. This doesn't work reliably on Facebook either, there are a lot of time code errors during download, resulting in video freezes and the video/audio are out of sync.

**Additional context** 
I have enabled verbose logging to provide some debug information below:
C:\Users\username\Videos>dlstream

C:\Users\username\Videos>for /F "delims=" %a in ('youtube-dl -v -f best --hls-prefer-ffmpeg -g https://www.youtube.com/watch?v 9Auq9mYxFEE') do (ffmpeg -i %a -c copy download.ts )
[debug] System config: []
[debug] User config: ['-o', '%userprofile%Videos']
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'best', '--hls-prefer-ffmpeg', '-g', 'https://www.youtube.com/watch?v', '9Auq9mYxFEE']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2020-09-20-git-ef29e5bf42-full_build-www.gyan.dev, ffprobe 2020-09-20-git-ef29e5bf42-full_build-www.gyan.dev
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: https://www.youtube.com/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.youtube.com/

**Comment by dstftw** [comment]
>[debug] Command-line args: ['-v', '-f', 'best', '--hls-prefer-ffmpeg', '-g', 'https://www.youtube.com/watch?v', '9Auq9mYxFEE']
>https://www.youtube.com/watch?v

`=` in batch must be escaped with `^`.

**Comment by blikoor** [comment]
Escaping does not work, this error is the result:  "delims^= was unexpected at this time"

So I simply used youtube-dl without the batch (youtube-dl -v https://www.youtube.com/watch?v=9Auq9mYxFEE) and it worked.  I'm unsure how to fix the batch file for a little automation later on, but that is okay.

Thank you for the reply 
Kind regards

**Comment by slinkayy** [comment]
@blikoor Hi, I think you misunderstood.

The caret should go before the equals in the youtube URL, not the delims statement.

> for /f "delims=" %%a in ('youtube-dl -v -f best --hls-prefer-ffmpeg -g https://www.youtube.com/watch?v^=9Auq9mYxFEE') do (ffmpeg -i %%a -c copy download.ts)

You can also just put the URL in quotes.

I found this through Google so I'm posting the solution even if you figured it out on your own.
