### ISSUE TITLE
Using postprocessor, progress hook post initialisation

### ISSUE THREAD

**Issue by Deshdeepak1** [ytdl-org/youtube-dl#26697]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is there any way to add postprocessor and progress_hooks after initialising an YoutubeDL object?

**Comment by dstftw** [comment]
`YoutubeDL.add_post_processor`
`YoutubeDL.add_progress_hook`
