### ISSUE TITLE
https://www.youtube.com/watch?v=oaOQZlaqtm4  can not download

### ISSUE THREAD

**Issue by 121786404** [ytdl-org/youtube-dl#26704]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.09.20**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

D:\Program Files\youtube-dl>youtube-dl.exe https://www.youtube.com/watch?v=oaOQZlaqtm4 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=oaOQZlaqtm4', '--verbose']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {'https': 'https://127.0.0.1:10809', 'ftp': 'ftp://127.0.0.1:10809', 'http': 'http://127.0.0.1:10809'}
[youtube] oaOQZlaqtm4: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\youtube.py", line 2364, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 1327, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ozburo** [comment]
Works for me :/

**Comment by okh-mzny** [comment]
You are using version 2020.03.24 as your log shows, which is pretty outdated. The latest version is 2020.09.20.
YouTube changes things around constantly, thus breaking youtube-dl. 
Please launch a command prompt with admin rights by right clicking and selecting "Run as Administrator".
Then update youtube-dl by running "youtube-dl -U", or if you installed trough pip: "pip install --upgrade youtube-dl"
