### ISSUE TITLE
bug download of crunchyroll

### ISSUE THREAD

**Issue by victor-freitas1494** [ytdl-org/youtube-dl#26710]
youtube-dl https://www.crunchyroll.com/pt-br/monster-girl-doctor/episode-10-the-self-deprecating-cyclops-796136 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.crunchyroll.com/pt-br/monster-girl-doctor/episode-10-the-self-deprecating-cyclops-796136', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.18rc1 (CPython) - Linux-5.4.0-26-generic-x86_64-with-LinuxMint-20-ulyana
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[crunchyroll] 796136: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by gandeladri** [comment]
Same here. For this link: https://www.crunchyroll.com/es/dr-stone/episode-1-stone-world-786941
I'm getting this error when I try to get subs. Only way I can do this is to download with --all-subs command.

**Comment by Goten87** [comment]
same with me for sword art online
Command used
```
youtube-dl --no-check-certificate --recode-video mp4 --cookies crunchyroll.com_cookies.txt --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36" --all-subs https://www.crunchyroll.com/sword-art-online/episode-1-the-world-of-swords-606739
```

my error
```
$ youtube-dl --no-check-certificate --recode-video mp4 --cookies crunchyroll.com_cookies.txt --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36" --all-subs https://www.crunchyroll.com/sword-art-online/episode-1-the-world-of-swords-606739 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--no-check-certificate', u'--recode-video', u'mp4', u'--cookies', u'crunchyroll.com_cookies.txt', u'--user-agent', u'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36', u'--all-subs', u'https://www.crunchyroll.com/sword-art-online/episode-1-the-world-of-swords-606739', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-11-amd64-x86_64-with-debian-10.6
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[crunchyroll] 606739: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by Strife89** [comment]
Bumping this, having just experienced the issue as well while trying to download from Crunchyroll. My log looks pretty identical to those above.

**Comment by FastedCoyote** [comment]
This bug happens when using an old Python version, you need to use a recent one. Many Linux distros symlink the main `python` executable to `python2` for compatibility reasons, so you need to tell `youtube-dl` to use `python3` instead. This can be accomplished in at least three different ways:

- Change the interpreter from `python` to `python3` in the source code (I think you only need to modify the Makefile, but I'm not sure), recompile and reinstall.

- Remove the current symlink and create a new one that points to `python3`.

- Add a symlink to `python3` in a new directory and append that directory to the PATH environment variable everytime you run `youtube-dl` or make the change permanent if you are ok with that.

I went for the third option as I don't really know how to recompile the whole thing and I don't want to mess with the files my package manager installs.

With `python` pointing to `python2`:

    $ youtube-dl --simulate --verbose 'https://www.crunchyroll.com/rezero-starting-life-in-another-world-/rezero-starting-life-in-another-world-the-end-of-the-beginning-and-the-beginning-of-the-end-part-1-702401'
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: [u'--simulate', u'--verbose', u'https://www.crunchyroll.com/rezero-starting-life-in-another-world-/rezero-starting-life-in-another-world-the-end-of-the-beginning-and-the-beginning-of-the-end-part-1-702401']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2020.12.09
    [debug] Python version 2.7.18 (CPython) - Linux-5.4.0-53-generic-x86_64-with-Ubuntu-20.04-focal
    [debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
    [debug] Proxy map: {}
    [crunchyroll] 702401: Downloading webpage
    ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
        return self._downloader.urlopen(url_or_request)
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2248, in urlopen
        return self._opener.open(req, timeout=self._socket_timeout)
      File "/usr/lib/python2.7/urllib2.py", line 435, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 467, in error
        result = self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
        return self.parent.open(new, timeout=req.timeout)
      File "/usr/lib/python2.7/urllib2.py", line 435, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 473, in error
        return self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

With `python` pointing to `python3`:

    $ youtube-dl --simulate --verbose 'https://www.crunchyroll.com/rezero-starting-life-in-another-world-/rezero-starting-life-in-another-world-the-end-of-the-beginning-and-the-beginning-of-the-end-part-1-702401'
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: ['--simulate', '--verbose', 'https://www.crunchyroll.com/rezero-starting-life-in-another-world-/rezero-starting-life-in-another-world-the-end-of-the-beginning-and-the-beginning-of-the-end-part-1-702401']
    [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
    [debug] youtube-dl version 2020.12.09
    [debug] Python version 3.8.5 (CPython) - Linux-5.4.0-53-generic-x86_64-with-glibc2.29
    [debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
    [debug] Proxy map: {}
    [crunchyroll] 702401: Downloading webpage
    [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-ptBR information
    [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP information
    [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-itIT information
    [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-arME information
    [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-enUS information
    [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-deDE information
    [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-frFR information
    [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-esES information
    [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-esLA information
    [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-ruRU information
    [crunchyroll] 702401: Downloading media info
    [debug] Default format spec: bestvideo+bestaudio/best

**Comment by victor-freitas1494** [comment]
> Este bug acontece ao usar uma versão antiga do Python, você precisa usar uma versão recente. Muitas distros do Linux possuem links simbólicos para o `python`executável principal `python2`por motivos de compatibilidade, então você precisa informar `youtube-dl`para usá-lo `python3`. Isso pode ser feito de pelo menos três maneiras diferentes:
> 
> * Altere o interpretador de `python`para `python3`no código-fonte (acho que você só precisa modificar o Makefile, mas não tenho certeza), recompile e reinstale.
> * Remova o link simbólico atual e crie um novo que aponte para `python3`.
> * Adicione um link simbólico `python3`em um novo diretório e anexe esse diretório à variável de ambiente PATH toda vez que você executar `youtube-dl`ou torne a mudança permanente se você estiver ok com isso.
> 
> Escolhi a terceira opção porque não sei como recompilar tudo e não quero mexer com os arquivos que meu gerenciador de pacotes instala.
> 
> Com `python`apontando para `python2`:
> 
> ```
> $ youtube-dl --simulate --verbose 'https://www.crunchyroll.com/rezero-starting-life-in-another-world-/rezero-starting-life-in-another-world-the-end-of-the-beginning-and-the-beginning-of-the-end-part-1-702401'
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'--simulate', u'--verbose', u'https://www.crunchyroll.com/rezero-starting-life-in-another-world-/rezero-starting-life-in-another-world-the-end-of-the-beginning-and-the-beginning-of-the-end-part-1-702401']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2020.12.09
> [debug] Python version 2.7.18 (CPython) - Linux-5.4.0-53-generic-x86_64-with-Ubuntu-20.04-focal
> [debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
> [debug] Proxy map: {}
> [crunchyroll] 702401: Downloading webpage
> ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2248, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 435, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python2.7/urllib2.py", line 467, in error
>     result = self._call_chain(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 435, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python2.7/urllib2.py", line 473, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
> ```
> 
> Com `python`apontando para `python3`:
> 
> ```
> $ youtube-dl --simulate --verbose 'https://www.crunchyroll.com/rezero-starting-life-in-another-world-/rezero-starting-life-in-another-world-the-end-of-the-beginning-and-the-beginning-of-the-end-part-1-702401'
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--simulate', '--verbose', 'https://www.crunchyroll.com/rezero-starting-life-in-another-world-/rezero-starting-life-in-another-world-the-end-of-the-beginning-and-the-beginning-of-the-end-part-1-702401']
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
> [debug] youtube-dl version 2020.12.09
> [debug] Python version 3.8.5 (CPython) - Linux-5.4.0-53-generic-x86_64-with-glibc2.29
> [debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
> [debug] Proxy map: {}
> [crunchyroll] 702401: Downloading webpage
> [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-ptBR information
> [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP information
> [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-itIT information
> [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-arME information
> [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-enUS information
> [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-deDE information
> [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-frFR information
> [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-esES information
> [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-esLA information
> [crunchyroll] 702401: Downloading adaptive_hls-audio-jaJP-hardsub-ruRU information
> [crunchyroll] 702401: Downloading media info
> [debug] Default format spec: bestvideo+bestaudio/best
> ```

thank you i will try here
