### ISSUE TITLE
Fails to download Youtube video: Video contains content from Mosfilm

### ISSUE THREAD

**Issue by woochica** [ytdl-org/youtube-dl#26712]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=fh2cDKyFdyU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.0 (CPython) - macOS-10.14.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] fh2cDKyFdyU: Downloading webpage
[youtube] fh2cDKyFdyU: Downloading embed webpage
[youtube] fh2cDKyFdyU: Refetching age-gated info webpage
ERROR: This video contains content from Mosfilm, who has blocked it from display on this website or application. Watch on YouTube
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2231, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video contains content from Mosfilm, who has blocked it from display on this website or application. Watch on YouTube
```

## Description

The latest youtube-dl fails to download the Youtube video fh2cDKyFdyU because the "video contains content from Mosfilm, who has blocked it from display on this website or application".

**Comment by starkfire** [comment]
Probably because it is copyrighted material.

https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free

> As a matter of policy (as well as legality), youtube-dl does not include support for services that specialize in infringing copyright.

**Comment by pukkandan** [comment]
The underlying issue is the same as https://github.com/ytdl-org/youtube-dl/issues/26652
