### ISSUE TITLE
add %(timestamp)s variable to --write-info-json

### ISSUE THREAD

**Issue by Qriist** [ytdl-org/youtube-dl#26716]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
related issue, ytdl not finding timestamp: https://github.com/ytdl-org/youtube-dl/issues/26715#issue-709519612

Once my related timestamp issue gets resolved, please add that same variable as a key in the info json. Thank you!

**Comment by remitamine** [comment]
already supported when the timestamp is available.
