### ISSUE TITLE
%(timestamp)s template option only returns NA

### ISSUE THREAD

**Issue by Qriist** [ytdl-org/youtube-dl#26715]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
```youtube-dl  https://www.youtube.com/watch?v=wan5tojr8ug   -o %(upload_date)s-%(timestamp)s.%(ext)s --write-info-json -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=wan5tojr8ug', '-o', '%(upload_date)s-%(timestamp)s.%(ext)s', '--write-info-json', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.2 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-96910-gcfd9a65903-COMPILED_BY_JohnWarburton, ffprobe N-96910-gcfd9a65903-COMPILED_BY_JohnWarburton, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] wan5tojr8ug: Downloading webpage
[youtube] wan5tojr8ug: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video description metadata as JSON to: 20200921-NA.info.json
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 20200921-NA.mkv has already been downloaded and merged
```

## Description

WRITE DESCRIPTION HERE
No videos give me the ``timestamp`` variable in the naming template, I've tried with youtube and bitchute. Seems to be a broken variable. Please fix, thank you! :)

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#does-the-issue-involve-one-problem-and-one-problem-only
