### ISSUE TITLE
I tried to link this av, but an error is displayed

### ISSUE THREAD

**Issue by arakawa995** [ytdl-org/youtube-dl#26724]
## Checklist

- [ check] I'm reporting a broken site support
- [check ] I've verified that I'm running youtube-dl version **2020.09.20**
- [ check] I've checked that all provided URLs are alive and playable in a browser
- [ check] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [check ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

G:\downloads\youtube-dl>youtube-dl https://m.thisav.com/c802bab3-14ed-4ecc-ba00-a199c5f56a6d
[generic] c802bab3-14ed-4ecc-ba00-a199c5f56a6d: Requesting header
[redirect] Following redirect to https://m.thisav.com/error404
[generic] error404: Requesting header
WARNING: Falling back on generic information extractor.
[generic] error404: Downloading webpage
[generic] error404: Extracting information
ERROR: Unsupported URL: https://m.thisav.com/error404

-->

```
https://m.thisav.com/video/510323/　
I checked the version of the above URL, but I couldn't download it.
```

## Description

WRITE DESCRIPTION HERE
I confirmed that the THIS AV site could be downloaded from the list in the support column, but I could not execute it successfully. I want you to improve and fix it somehow.

**Comment by dirkf** [comment]
Continued in #32595.

**Comment by dirkf** [comment]
-
