### ISSUE TITLE
Eternal Download

### ISSUE THREAD

**Issue by vilarinux** [ytdl-org/youtube-dl#26726]
- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.09.20**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [] I've read bugs section in FAQ

```
davi@davi-desktop:~/music/aurora$ youtube-dl "https://www.youtube.com/watch?v=hCRLr9JCLT0" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=hCRLr9JCLT0', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.18rc1 (CPython) - Linux-5.4.0-48-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] hCRLr9JCLT0: Downloading webpage
^C
ERROR: Interrupted by user

```

I tried to install both apt-versions (that I didn't suggest, at all, because had issues months ago) and website versions (which I'm now).

I've tried to use those: " and without, just ID... And i'm having this issue with other players (Checked right now the peerturbe doesn't seem to work too).

I've noticed too that I don't have any config (which could have been generated by those reinstallations if there was one, so...

**Comment by takase1121** [comment]
To OP: You might want to change your issue title, it is confusing. 
I also have this issue and it is just incredibly slow, around 5-10m for it to advance to the next stage.

**Comment by vilarinux** [comment]
Fine, will try to wait...
This is strange, I'm wired connected

**Comment by takase1121** [comment]
I suspected that YouTube is pulling off a slow-sloth like attack by sending packets right before TCP disconnects. I don't know if trying a different user agent works.

**Comment by takase1121** [comment]
Unfortunately, I was unable to replicate this issue... this is some weird stuff. Maybe OP still has it, but sorry I am unable to help with this.

**Comment by vilarinux** [comment]
Still Having the same problem...

I don't think that even geolocation could make so damn long downloading time...

**Comment by vilarinux** [comment]
SOLVED

I don't why, I don't know how, and I even don't have I done to get here, but I tried going forcing every different connection with different paraments and the solution was just:

``` \\ some stuff of youtube-dl // -6 ```
