### ISSUE TITLE
If you choose the best resolution instead of the best file size

### ISSUE THREAD

**Issue by woainiyilin** [ytdl-org/youtube-dl#26735]
If you choose the best resolution instead of the best file size

**Comment by pukkandan** [comment]
There is sadly no easy way to do this. 

1. You can either make a list of all format codes like [this guy](https://www.reddit.com/r/DataHoarder/comments/g302cg/my_youtubedl_script_the_best_formatting_i_could/)
or
1. You could use a large format selection with seperate check for each resolution. Something like:
`(bestvideo[height>2160]/bestvideo[height>1080]/`**...**`/bestvideo[height>144]/bestvideo)+bestaudio`**...**
or
1. You can use  https://github.com/ytdl-org/youtube-dl/pull/25959 and use `--format-sort height`

**Comment by rautamiekka** [comment]
Plus even if you could do that, you shouldn't simply try to correlate resolution to quality, nor simply filesize to quality cuz the file could have a massive resolution but still be all shit (OBS Studio's default settings make for very shit-quality vids, I learnt that in my 'Arma 3' gaming), and even a massive filesize could mean the quality is all shit, I've seen both happen at least twice.

A better way would be to correlate resolution, filesize, and the format to quality, it's more likely to work, but still not a guarantee.

**Comment by pukkandan** [comment]
@rautamiekka You are correct in that there is no fool proof way to find the best quality automatically. This is why youtube-dl already provides a way for the extractors to override the default quality sorting. However, imo, this is not enough. There are many situations (like OP's question) where it is beneficial for the **user** to be able to specify the sorting method. My pull request is one way of doing that. I am sure there are superior ways for achieving the same, but until someone implements such a way, `--format-sort` is the easiest way to solve OP's issue.
