### ISSUE TITLE
mpd to m3u8

### ISSUE THREAD

**Issue by felipesantos989** [ytdl-org/youtube-dl#26733]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Hi, i have a stream source coming in mpd, i have youtube-dl installed, how can i download this mpd stream in m3u8 format with youtube-dl?

**Comment by X-C0DE** [comment]
mpd is a mpd, and m3u8 is a m3u8
or you download as m3u8 or as mpd
