### ISSUE TITLE
Aparat.com is not supported!

### ISSUE THREAD

**Issue by KomeilParseh** [ytdl-org/youtube-dl#26738]
Aparat.com is not supported!

**Comment by Dullaz** [comment]
Aparat is supported but it seems like their website has gone through an update recently.

I've coded in some changes so the tests work. Issuing a pull request now and we'll see how it goes

**Comment by Dullaz** [comment]
RIP should've checked the PR list first.

There is already a PR with a fix [here](https://github.com/ytdl-org/youtube-dl/pull/24354)

Just got to wait till it merges I suppose

**Comment by KomeilParseh** [comment]
Hello Again.
This time it gives Error 32 ([Errno 32] Broken pipe).

**Comment by Bayany** [comment]
it seems they aren't going to merge, soon 🙄
if you encounter this issue, you can fix it easily by just editing [one line](https://github.com/ytdl-org/youtube-dl/pull/26350/files)🙂😉

**Comment by Bayany** [comment]
> it seems they aren't going to merge, soon 🙄
> if you encounter this issue, you can fix it easily by just editing [one line](https://github.com/ytdl-org/youtube-dl/pull/26350/files)🙂😉

I can't get what u mean by your reactions... it doesn't work?!
