### ISSUE TITLE
Problem downloading channels with accented characters

### ISSUE THREAD

**Issue by leonard-limon** [ytdl-org/youtube-dl#26746]
I found out that youtube-dl would throw an error every-time I try to download a video from a channel that has an accented character in its URL. For example this would throw an error :

youtube-dl -j --playlist-items 1 -- "https://www.youtube.com/c/LeRèglement"

Regards.

**Comment by Foncekar** [comment]
Same error for me, no one would have an idea to overcome this problem?

**Comment by october262** [comment]
replace the accented e in LeReglement with a regular e
and then retry the download

**Comment by leonard-limon** [comment]
That worked, thanks for the workaround!
