### ISSUE TITLE
Can't download video Facebook

### ISSUE THREAD

**Issue by boygiandi** [ytdl-org/youtube-dl#26783]
Please check Facebook plugin, I tried this link : https://www.facebook.com/xuongchuyensiaothuncantho/videos/868434430317437/ ( it's public video )

```
[root@ns571445 ~]# youtube-dl -J "https://www.facebook.com/xuongchuyensiaothuncantho/videos/868434430317437/"
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
```

It's public video but youtube-dl still show "This video is only available for registered users"

**Comment by october262** [comment]
i had no issue downloading the video

**Comment by boygiandi** [comment]
For some country ( or IP server, I'm not sure ) Facebook force user to login before watch video. I fixed it by using proxy
