### ISSUE TITLE
How to set aria2c as external downloader in ytdl_opts

### ISSUE THREAD

**Issue by TheKaram** [ytdl-org/youtube-dl#26793]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, How can i set aria2c to download videos
Here is my options:
```
ydl_opts = {
	'format': 'bestvideo+bestaudio',
	'logger': MyLogger(),
	'progress_hooks': [my_hook],
	'external-downloader':'aria2c'
}
```
But, that seems nothing has improved (I am not able to understand if it is correct or not)

**Comment by Lamieur** [comment]
Works for me by adding --external-downloader aria2c and --external-downloader-args to ~/.config/youtube-dl/config, but there are types of content that will make youtube-dl force ffmpeg, so it may depend on the site you're downloading from.

Anyways, "nothing has improved" may be right even if it IS in fact using aria2c - for me, actual YouTube download with aria2c (I've tried -c -j 3 -x 3 -s 3 -k 1M for args) is WAY slower (over 20x, not kidding!) than normal. Either YouTube detects those connections and rate-limits me, or I'm too conservative with them, or youtube-dl itself does things differently with external downloaders.

Easy to test - just youtube-dl -v and it will show you "[debug] aria2c command line:" somewhere there, not to mention aria2c's colorful progress bar showing up :)

**Comment by kikuyan** [comment]
not `'external-downloader'`
but `'external_downloader'`

**Comment by zyzl1** [comment]
I want to know how to set 'external-downloader-args' in ydl_opts
