### ISSUE TITLE
dropbox video HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by mdmasih2k2** [ytdl-org/youtube-dl#26790]
C:\Users\mdmas\Downloads\youtube dl>youtube-dl -U
youtube-dl is up-to-date (2020.09.20)

C:\Users\mdmas\Downloads\youtube dl>youtube-dl.exe https://www.dropbox.com/sh/016qjmg8b7w97pc/AABRZhR2x0-gmGH014kQkBACa?dl=0&preview=HANA+Admin+200625.mp4
ERROR: unable to download video data: HTTP Error 403: Forbidden
'preview' is not recognized as an internal or external command,
operable program or batch file.

**Comment by zackmark29** [comment]
add double quote in the url.

youtube-dl.exe "https://www.dropbox.com/sh/016qjmg8b7w97pc/AABRZhR2x0-gmGH014kQkBACa?dl=0&preview=HANA+Admin+200625.mp4"

**Comment by mdmasih2k2** [comment]
C:\Users\mdmas\Downloads\youtube dl>youtube-dl.exe "https://www.dropbox.com/sh/016qjmg8b7w97pc/AABRZhR2x0-gmGH014kQkBACa?dl=0&preview=HANA+Admin+200625.mp4"
ERROR: unable to download video data: HTTP Error 404: Not Found

C:\Users\mdmas\Downloads\youtube dl>

**Comment by zackmark29** [comment]
> C:\Users\mdmas\Downloads\youtube dl>youtube-dl.exe "https://www.dropbox.com/sh/016qjmg8b7w97pc/AABRZhR2x0-gmGH014kQkBACa?dl=0&preview=HANA+Admin+200625.mp4"
> ERROR: unable to download video data: HTTP Error 404: Not Found
> 
> C:\Users\mdmas\Downloads\youtube dl>

It's already expired. try to get a new link

**Comment by mdmasih2k2** [comment]
The link works for me and I can watch the video but cannot download

**Comment by october262** [comment]
install the firefox addon called the stream detector
use it to downlad the m3u8 file.

**Comment by drewbitt** [comment]
> install the firefox addon called the stream detector
> use it to downlad the m3u8 file.

Why would the solution to this be to not use youtube-dl? I also came upon this issue with a Dropbox video today. Can access in browser but not download, clearing cache / updating does not help.

**Comment by remitamine** [comment]
the link posted here has expired.

**Comment by Darius200220** [comment]
> install the firefox addon called the stream detector use it to downlad the m3u8 file.

Thank you man, this one solved my issue.
