### ISSUE TITLE
odysee.com support request

### ISSUE THREAD

**Issue by bubul01** [ytdl-org/youtube-dl#26806]
## Checklist

- [x ] I'm reporting a new site support request
- [x ] I've verified that I'm running youtube-dl version **2020.09.20**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that none of provided URLs violate any copyrights
- [ x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://odysee.com/@DigitizedPixels:9/how-to-get-human-mr-p-badge-mr-p-human:1
- Playlist: https://odysee.com/@SilvanoTrotta:f

## Description

A lot of censored youtube channels (french) now go to odysee , it can be a good thing to download video from it for backup

Log:
[debug] System config: []
 [debug] User config: []
 [debug] Custom config: []
 [debug] Command-line args: ['https://odysee.com/@DigitizedPixels:9/how-to-get-human-mr-p-badge-mr-p-human:1', '--ffmpeg-location', 'ffmpeg/bin/', '--verbose', '-r', '3M', '--no-playlist', '-f', ' bestvideo+bestaudio/best', '-o', 'G:/Videos/test/%(title)s.%(ext)s', '--min-sleep-interval', '60', '--max-sleep-interval', '120']
 [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
 [debug] youtube-dl version 2020.09.20
 [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
 [debug] exe versions: ffmpeg git-2020-03-15-c467328, ffprobe git-2020-03-15-c467328
 [debug] Proxy map: {}
 [generic] how-to-get-human-mr-p-badge-mr-p-human:1: Requesting header
 WARNING: Falling back on generic information extractor.
 [generic] how-to-get-human-mr-p-badge-mr-p-human:1: Downloading webpage
 [generic] how-to-get-human-mr-p-badge-mr-p-human:1: Extracting information
 [generic] 1e59a09d59b7bf4edd6c661e1231c0cba6d8d498: Requesting header
 WARNING: Falling back on generic information extractor.
 [generic] 1e59a09d59b7bf4edd6c661e1231c0cba6d8d498: Downloading webpage
 [generic] 1e59a09d59b7bf4edd6c661e1231c0cba6d8d498: Extracting information
 ERROR: Unsupported URL: https://odysee.com/$/embed/how-to-get-human-mr-p-badge-mr-p-human/1e59a09d59b7bf4edd6c661e1231c0cba6d8d498
 Traceback (most recent call last):
   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
 youtube_dl.utils.UnsupportedError: Unsupported URL: https://odysee.com/$/embed/how-to-get-human-mr-p-badge-mr-p-human/1e59a09d59b7bf4edd6c661e1231c0cba6d8d498

**Comment by Lamieur** [comment]
There's https://github.com/ytdl-org/youtube-dl/pull/24284

I've patched the above with the fix posted in that PR's comments, then added odysee.com to the url (also posted a comment there) and it works.

**Comment by krypciak** [comment]
I would like this feature, since files look much better with spaces, but those special characters are very annoying and ugly.
