### ISSUE TITLE
Allow wildcards or regex on format_id

### ISSUE THREAD

**Issue by jesus2099** [ytdl-org/youtube-dl#26808]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I would like to download a list of videos contained in a batch file with a specific format.
The `format_id` in my example is like `m3u8-download-10xx` but the last two `xx` digits vary.

It would be nice to be able to use either:

### Wildcards

Syntax like: `--format m3u8-download-10??` or `--format m3u8-download-10*`

### Regular expressions

Syntax like: `--format /^m3u8-download-10/`

## Workaround

So, I have to use a **tedious two step work-around**:

    youtube-dl --list-formats --batch-file liste.txt | grep m3u8-download-10 | sort --unique

To list all the possible format variations for my list and note them down to then run:

    youtube-dl --format m3u8-download-1074/m3u8-download-1076/m3u8-download-1077/m3u8-download-1078/m3u8-download-1079/m3u8-download-1080 --batch-file liste.txt

**Comment by jesus2099** [comment]
For another set of videos, I was able to use another workaround, another good feature: `[tbr>=1000][tbr<1100]`.
But it does not work in this case as there are several formats that match but the one that I want has `download` in its name.

**Comment by pukkandan** [comment]
If you are willing to merge https://github.com/ytdl-org/youtube-dl/pull/26910, you can use `-f best[format_id^=m3u8-download]`

There may be another workaround for the issue, but for me to check that, give me an example url that you are trying to download

**Comment by jesus2099** [comment]
Take https://www.france.tv/france-4/la-legende-de-korra/saison-1/1794151-bienvenue-dans-la-cite-de-la-republique.html for instance where I would like `--format best[format_id^=m3u8-download-10]` for example.

Because I have a --batch-file with all videos in this series and the two last digits are not always the same.
