### ISSUE TITLE
External Downloader Does not Work with mpd urls

### ISSUE THREAD

**Issue by 0xrabin** [ytdl-org/youtube-dl#26802]
- [ ] I'm running youtube-dl version **2020.06.16.1**
- [ ] External downloader does not work while downloading from an mpd url.

Example:
```youtube-dl --verbose -f bestvideo -c -i --external-downloader-args '-n 10' --external-downloader axel -o 'test.mp4' https://dash.akamaized.net/akamai/bbb_30fps/bbb_30fps.mpd```

## Verbose log

[debug] System config: []
[debug] User config: ['-o', '[%(upload_date)s][%(id)s] %(title)s (by %(uploader)s).%(ext)s', '--external-downloader', 'aria2c', '--external-downloader-args', '-c -j 3 -x 3 -s 3 -k 1M']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'bestvideo', '-c', '-i', '--external-downloader-args', '-n 50', '--external-downloader', 'axel', '-o', 'test.mp4', 'https://dash.akamaized.net/akamai/bbb_30fps/bbb_30fps.mpd']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.5 (CPython) - Linux-5.7.0-2parrot2-amd64-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.3-3, ffprobe 4.3-3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] bbb_30fps: Requesting header
WARNING: Falling back on generic information extractor.
[generic] bbb_30fps: Downloading webpage
[generic] bbb_30fps: Extracting information
[debug] Invoking downloader on 'https://dash.akamaized.net/akamai/bbb_30fps/bbb_30fps.mpd'
[dashsegments] Total fragments: 160

## Description

It seems that using an external downloader does not work while downloading from an mpd url. Tested with axel and aria2c.
Did not work on both.

**Comment by zackmark29** [comment]
Well, maybe that's not the correct stream source. Because there's no url inside that mpd.
Try to look for another url instead. or m3u8

**Comment by remitamine** [comment]
both `axel` and `aria2c` do not support downloading DASH formats so there is nothing to be done.
