### ISSUE TITLE
get URL from the "-F" list.

### ISSUE THREAD

**Issue by 5c0tt-b0t** [ytdl-org/youtube-dl#26812]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

First, **THANK YOU!** this is amazing & its really appreciated!

I stream music daily using the `-g` option, e.g:
```bash
mpv --no-video $(youtube-dl -f bestaudio "ytsearch: --match-title 'ArtistName SongName'" -g)
```
Its great, thank you! 👍 

**Personal problem:**
I live in an area with terrible internet connection and I am unable to do anything about it, no matter what provider I use, its the area.

When I stream, its a shame that sometimes the track can be 20mb+ when I all I want is the audio, no video.
So instead, I started to use `-F worstvideo` which can sometimes help out alot, others times... not really, I lose audio-quality and it still uses way too much bandwidth for an audio track.

Then I found `-F`, used with `grep` like so:
```bash
youtube-dl -F "ytsearch: --match-title 'ArtistName SongName'" | grep 'audio only'
```
This is great! it shows me the audio-only files, they are all **tiny** and 99% of the time, the audio-quality is higher than `-f worstvideo` produces... I am closer to bliss!

**Problem:**
I am unable to stream these as they do not return a link like the `-g` option does, I have tried to use them together with no luck, it seems that either `-F` & `-g` do not work together. 

# The actual question... finally!
Is it possible to return the URL of one of the entries listed with `-F` ?
If not, please consider this a feature-request!
It would allow users to stream and/or get the URL from the `-F` list, allowing users to stream audio-only files!, saving bandwidth and still getting great audio-quality too.

**BLISS!**

Once again, thank you.

**Comment by JChris246** [comment]
Try using -f instead ... youtube-dl -gf format-code url

**Comment by 5c0tt-b0t** [comment]
> Try using -f instead ... youtube-dl -gf format-code url
Thanks for the suggestion, but as I stated earlier, I have already done this and also stated:
> bandwidth
> worse audio quality
> non interactive (options not listed)

I need to `youtube-dl -F | grep 'no video'` or just get a URL from any entry using `-F`

**Comment by JChris246** [comment]
-f and -F are different. -F will list the available formats, whereas -f will take a param (format-code). So for example

youtube-dl -gf 140 https://www.youtube.com/watch?v=l9nh1l8ZIJQ 

would return the url for m4a audio

**Comment by pukkandan** [comment]
What is the issue with `-f bestaudio`? It only downloads the audio.

But if you really want to get the urls of each format, you can use `-j` to get the json extract the relevent info using `jq`

**Comment by dstftw** [comment]
`-f all -g`.

**Comment by biy37273** [comment]
I think the question is miss-understood :) 

If i understand the situation correctly, this what I'd do :
`-f 249/250/139/251/140 -g` 

it grabs one track only, starting from known to be lowest `in-size` but `quality in mind`,
if track x not available it go with the next on.. etc, just in case.

Also you could use `-f worstaudio -g` 
but i prefer specifying opus formats first.
