### ISSUE TITLE
ardmediathek downloads not working

### ISSUE THREAD

**Issue by uns-uwe** [ytdl-org/youtube-dl#26825]
Trying to download a movie. 

URL of webpage is:
https://www.ardmediathek.de/daserste/video/babylon-berlin-filmklassiker-der-20er/metropolis-1927/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2JhYnlsb24tYmVybGluLWZpbG1rbGFzc2lrZXItZGVyLTIwZXIvYzRhNWRiMDItYzM4YS00N2NmLWE0ZWEtMjYyYjNjYzg1YTBi/

Before the attempt to download the movie I update youtube-dl

~$ sudo youtube-dl -U
[sudo] Passwort für xxxxxx: 
youtube-dl is up-to-date (2020.09.20)

xxxxxx@kubuntu-18:~$ youtube-dl --verbose https://www.ardmediathek.de/daserste/video/babylon-berlin-filmklassiker-der-20er/metropolis-1927/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2JhYnlsb24tYmVybGluLWZpbG1rbGFzc2lrZXItZGVyLTIwZXIvYzRhNWRiMDItYzM4YS00N2NmLWE0ZWEtMjYyYjNjYzg1YTBi/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.ardmediathek.de/daserste/video/babylon-berlin-filmklassiker-der-20er/metropolis-1927/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2JhYnlsb24tYmVybGluLWZpbG1rbGFzc2lrZXItZGVyLTIwZXIvYzRhNWRiMDItYzM4YS00N2NmLWE0ZWEtMjYyYjNjYzg1YTBi/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-118-generic-i686-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[debug] Using fake IP 53.85.163.131 (DE) as X-Forwarded-For.
[ARD:mediathek] Y3JpZDovL2Rhc2Vyc3RlLmRlL2JhYnlsb24tYmVybGluLWZpbG1rbGFzc2lrZXItZGVyLTIwZXIvYzRhNWRiMDItYzM4YS00N2NmLWE0ZWEtMjYyYjNjYzg1YTBi: Downloading webpage
ERROR: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/jasoco/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/jasoco/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/jasoco/.local/lib/python2.7/site-packages/youtube_dl/extractor/ard.py", line 236, in _real_extract
    r'/play/(?:config|media)/(\d+)', webpage, 'media id')
  File "/home/jasoco/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

What irritates me is that the update call returns a version date of 2020.09.20 while in the verbose output I read "youtube-dl version 2020.05.08"

**Comment by remitamine** [comment]
you have multiple version installed, remove the old version.
