### ISSUE TITLE
New issue with youtube-dl on urplay.se

### ISSUE THREAD

**Issue by EmmW** [ytdl-org/youtube-dl#26828]
Hi, I have just updated youtube-dl to version 2020.09.20 but the new problem I ran into still persists even after this update (I have restarted Terminal, but not the whole Mac OS):

youtube-dl https://urplay.se/program/214606-kanaler-batar-och-karlek-brittiska-och-irlandska-strapatser --all-subs --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://urplay.se/program/214606-kanaler-batar-och-karlek-brittiska-och-irlandska-strapatser', u'--all-subs', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.17 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[URPlay] 214606: Downloading webpage
ERROR: Unable to extract urplayer data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/urplay.py", line 41, in _real_extract
    r'urPlayer\.init\(({.+?})\);', webpage, 'urplayer data'), video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract urplayer data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Is this something you might be able to look into? That would be very much appreciated -- thanks,

Mark

**Comment by Minherre** [comment]
This has already been Reported!

https://github.com/ytdl-org/youtube-dl/issues/26815

**Comment by amigatomte** [comment]
> 
> 
> This has already been Reported!
> 
> #26815
> 
> Always use SEARCH before entering a new issue.
> 
> Like "https://github.com/ytdl-org/youtube-dl/search?q=urplay&type=issues".

Actually, this is a separate issue with the same site. I posted a link to a proposed solution for this issue here: https://github.com/ytdl-org/youtube-dl/issues/26815#issuecomment-706611023

**Comment by EmmW** [comment]
I see that Minherre has already reported same/similar issue with youtube-dl on urplay.se, but I haven't been able to find any proper solution to this problem yet (only a custom solution kindly proposed by amigatomte in Minherres thread at #26815). At the moment, neither youtube-dl version 2020.09.20 nor svtplay-dl version 2.7+3.ga550bd1 works with urplay.se, so it seems the developers still need to look into this issue.

On a side-note, if anyone is interested, I have managed to come up with a manual work-around that allows me to still download from urplay.se, and that is:

1) Start playing content on the urplay.se site in Firefox (e.g. "https://urplay.se/program/214583-kanaler-batar-och-karlek-aventyr-over-hela-varlden")
2) Using the extension Video DownloadHelper 7.3.9 in Firefox, I then use the command "Detaljer" for the corresponding HLS-strömning 1280x720 in order to get the masterManifest link ("https://streaming10.ur.se/urplay/_definst_/mp4:se/214000-214999/214583-5.mp4/playlist.m3u8?pid=zre0r&cid=urplay")
3) I then use Wondershare UniConverter to download this particular series episode as an mp4 file
4) In order to also get hold of the subtitles, I use the command "Visa sidans resurser" in Safari and search for the string ".tt"
5) Unfortunately there are a whole bunch of .tt files even though I have only chosen one particular episode, so when I find the first link (e.g. "https://undertexter.ur.se/214000-214999/214584-11.tt"), I simply put this link in a new window, replace the suffix ".tt" with ".srt", and then review the srt formatted text to see if it is the proper subtitle; if it is I just save the text file, if it is for another episode however, I just continue to the next .tt file link and repeat the process, until I have found the correct subtitles... :-)

A lot of work, but at least I'm able to download from urplay.se until youtube-dl (and svtplay-dl) has been updated to support the modified urplay.se site.

**Comment by amigatomte** [comment]
>     5. Unfortunately there are a whole bunch of .tt files even though I have only chosen one particular episode, so when I find the first link (e.g. "https://undertexter.ur.se/214000-214999/214584-11.tt"), I simply put this link in a new window, replace the suffix ".tt" with ".srt", and then review the srt formatted text to see if it is the proper subtitle; if it is I just save the text file, if it is for another episode however, I just continue to the next .tt file link and repeat the process, until I have found the correct subtitles... :-)

The correct subtitles would be the one with the same number (video id) as the video you are downloading, in this case 214583.
[https://urplay.se/program/**_214583_**-kanaler-batar-och-karlek-aventyr-over-hela-varlden]( https://urplay.se/program/214583-kanaler-batar-och-karlek-aventyr-over-hela-varlden)
[https://streaming10.ur.se/urplay/_definst_/mp4:se/214000-214999/**_214583_**-5.mp4/playlist.m3u8?pid=zre0r&cid=urplay](https://streaming10.ur.se/urplay/_definst_/mp4:se/214000-214999/214583-5.mp4/playlist.m3u8?pid=zre0r&cid=urplay)

Thus, the correct .tt subtitles file is:
[https://undertexter.ur.se/214000-214999/**_214583_**-11.tt](https://undertexter.ur.se/214000-214999/214583-11.tt)

I have submitted a pull request of a revised version of my code today. Hopefully it will be accepted soon.

Cheers

**Comment by EmmW** [comment]
Oh boy, silly me that didn't see this obvious correlation... Thanks for pointing that out! :-)
