### ISSUE TITLE
How to NOT Remove Special Characters from Filenames

### ISSUE THREAD

**Issue by syberknight** [ytdl-org/youtube-dl#26824]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE...

i'm using youtube-dl in the Terminal on a Mac (Catalina) to download all my videos from YouTube.

seems to be working fine, except...
for ? question marks, it removes them,
for " quotes, it changes them to apostrophes.

i get changing : colons to - dashes, but the rest of them, the Mac file system can totally handle.

so is there a way to make it keep these as-is? 

note: i have NOT set the "--restrict-filenames" option.
note: it keeps ! exclamation points (yay!) and it keeps & ampersands (yay!).

and for reference, in case i'm doing something wrong, here is the line i'm putting in the Terminal to make this happen...
`youtube-dl --ignore-errors --write-thumbnail -f '(bestvideo[width>=1920][ext=mp4])+bestaudio[ext=m4a]/best[ext=mp4]/best' -o '/Volumes/LaCie/DUMPSTER/%(upload_date)s %(title)s.%(ext)s' https://www.youtube.com/playlist?list=XXXXXXXXXXXXXXX
`

**Comment by pukkandan** [comment]
They are removed because other operating systems do not allow them. Afaik, there is no option in youtube-dl to change this behavior.

**Comment by syberknight** [comment]
thank you @pukkandan
