### ISSUE TITLE
cant download from bandcamp

### ISSUE THREAD

**Issue by boatsr** [ytdl-org/youtube-dl#26848]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by nicolaasjan** [comment]
You're not the only one. ;)
https://github.com/ytdl-org/youtube-dl/issues?q=bandcamp
