### ISSUE TITLE
[mtv] MTV site changed

### ISSUE THREAD

**Issue by StevenDTX** [ytdl-org/youtube-dl#26841]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.09.20**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
c:\support\youtube-dl.exe https://www.mtv.com/episodes/4iqsts/revenge-prank-the-prank-that-hits-the-jackpot-season-1-ep-16 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.mtv.com/episodes/4iqsts/revenge-prank-the-prank-that-hits-the-jackpot-season-1-ep-16', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-92986-gaceb9131c1, ffprobe N-92986-gaceb9131c1, rtmpdump 2.4
[debug] Proxy map: {}
[mtv] revenge-prank-the-prank-that-hits-the-jackpot-season-1-ep-16: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\mtv.py", line 287, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\mtv.py", line 213, in _get_videos_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\mtv.py", line 39, in _id_from_uri
AttributeError: 'NoneType' object has no attribute 'split'

```

## Description

MTV changed their website recently. URLs are different and so is streaming format.

**Comment by vinimk** [comment]
Can confirm is not working on windows.

**Comment by october262** [comment]
have you tried logging in with your TV provider and then
try downloading the episode ??

**Comment by thedreamfinder** [comment]
I have, logging in still doesn't work.

**Comment by StevenDTX** [comment]
> 
> 
> have you tried logging in with your TV provider and then
> try downloading the episode ??

Yes

**Comment by october262** [comment]
might try using the cookies file addon for firefox

**Comment by thedreamfinder** [comment]
One step ahead of you. That didn't work either. I'm pretty sure MTV changed and youtube-dl needs to be updated

**Comment by october262** [comment]
there's 2 more firefox addons to try  - one is called the stream detector and the other
is called videodownload helper try both and see of they'll pick up the video stream

**Comment by StevenDTX** [comment]
> there's 2 more firefox addons to try - one is called the stream detector and the other
> is called videodownload helper try both and see of they'll pick up the video stream

Quit throwing out random suggestions!  MTV changed their site. Period! YouTube-dL must be updated for it to wok..

**Comment by nonspin** [comment]
mtv.com is going DRM (> 9c9media) ..

**Comment by StevenDTX** [comment]
> 
> 
> mtv.com is going DRM (> 9c9media) ..

Its already been fixed by youtube-dlc.

**Comment by TurnItOffAndOnAgain** [comment]
> mtv.com is going DRM (> 9c9media) .. 

Maybe, but not yet. As mentioned above, MTV has changed their website and the YouTube-dL extractor for MTV needs to be updated to include the new web addresses for everything behind-the-scenes. They're not using DRM yet. I can use the Developer Tools in Chrome and pull the .m3u8 file addresses and then use ffmpeg to grab the streams successfully from there. It's messy and incredibly time consuming though. Thats why this project is such a lifesaver. I wish I knew more about python so I could contribute more to the project. A big thanks to all who maintain it!

**Comment by thedreamfinder** [comment]
Just so you all know it has been fixed now. The new youtube-dl was just fixed/updated a few hours ago. This should probably be closed.

**Comment by okh-mzny** [comment]
This is the same problem as with #26763 .
Seems like interally all of their sites got changed into one template.
