### ISSUE TITLE
Two six-digit numbers got outputted randomly

### ISSUE THREAD

**Issue by ShockedCoder** [ytdl-org/youtube-dl#26847]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I was downloading some music and yt-dl out putted this:

>[1] 523123
[2] 523124

Are these *magic* numbers or are these error numbers?

The input and output:
```
void@thevoid:~/Desktop/Muzik$ audio -o "The Living Tombstone - What I Want.%(ext)s" https://www.youtube.com/watch?v=Bhaot-BchF8&list=TLPQMDUxMDIwMjA1qSoztYyoXA&index=3
[1] 523123
[2] 523124
void@thevoid:~/Desktop/Muzik$ [youtube] Bhaot-BchF8: Downloading webpage
[youtube] Downloading just video Bhaot-BchF8 because of --no-playlist
[youtube] Bhaot-BchF8: Downloading embed webpage
[download] Destination: The Living Tombstone - What I Want.webm
[download] 100% of 3.11MiB in 00:00
[ffmpeg] Destination: The Living Tombstone - What I Want.mp3
Deleting original file The Living Tombstone - What I Want.webm (pass -k to keep)
```

**Comment by s104346** [comment]
https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
