### ISSUE TITLE
[Subtitles] stop on very long video

### ISSUE THREAD

**Issue by mbd-shift** [ytdl-org/youtube-dl#26856]
I downloaded a 6 hour python course from YT and after a 5:05 hour mark, the subtitle file ended.

Reproduce it:
``` youtube-dl --write-sub --write-auto-sub --skip-download --id _uQrJ0TkZlc```
the generated VTT file will end, even though there is 1 more hour of video

the vtt file has 13594 lines and is 406438B

**Comment by Feathered-Serpent** [comment]
If playing the video in the browser, the subtitles also end at the same time. So I guess the subtitle isn't complete on YT side either. Not much ytdl could to there I guess.

https://youtu.be/_uQrJ0TkZlc?t=18290

**Comment by mbd-shift** [comment]
> If playing the video in the browser, the subtitles also end at the same time. So I guess the subtitle isn't complete on YT side either. Not much ytdl could to there I guess.
> 
> https://youtu.be/_uQrJ0TkZlc?t=18290

Closed
