### ISSUE TITLE
Videos unavailable due to copyright returned from --flat-playlist

### ISSUE THREAD

**Issue by chriszilla1123** [ytdl-org/youtube-dl#26862]
version: ``2020.09.20``

flat-playlist command: 
``youtube-dl --flat-playlist -j https://www.youtube.com/channel/UCW1me3Ahh9M1KFImtZAfbNA``

returns the following row

``{"url": "MQ1mBSgLXfw", "_type": "url", "ie_key": "Youtube", "id": "MQ1mBSgLXfw", "title": "Call of duty black ops 3 killing zombies and the first mission"}``

trying to download the actual video from the id using: 
    ``youtube-dl https://www.youtube.com/watch?v=MQ1mBSgLXfw
    [youtube] MQ1mBSgLXfw: Downloading webpage
    [youtube] MQ1mBSgLXfw: Downloading embed webpage
    [youtube] MQ1mBSgLXfw: Refetching age-gated info webpage
    ERROR: This video contains content from Activision Publishing, Inc., who has blocked it on copyright grounds.``

Is this an error with the Youtube API or can it be fixed in youtube-dl?

**Comment by october262** [comment]
your 1st link - https://www.youtube.com/channel/UCW1me3Ahh9M1KFImtZAfbNA
says something about super mario maker 2

the 2nd one - https://www.youtube.com/watch?v=MQ1mBSgLXfw 
is more then likely been removed for copyright violations

**Comment by chriszilla1123** [comment]
Yeah, the issue is that flat-playlist is returning these videos at all if
they can't be downloaded. Is there a setting to disable this or is it a
bug?

**Comment by pukkandan** [comment]
This is the intended behaviour. `--flat-playlist -j` simply returns all the video data that can be extracted from the playlist. It doesn't matter if the video is blocked/deleted.

Afaik, there is no way to disable this behaviour. Can you elaborate on WHY you want it to behave differently? Then maybe we can help
