### ISSUE TITLE
[YouTube]youtube-dl sometimes redirects youtube.com/user/channelName/live to the wrong video

### ISSUE THREAD

**Issue by sebma** [ytdl-org/youtube-dl#26865]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```python
$ youtube-dl -j https://www.youtube.com/user/NewCreationChurch/live --playlist-items 1 -v | jq -r '.title, .id, .is_live'
[debug] System config: []
[debug] User config: ['--ignore-errors', '--prefer-ffmpeg', '--no-warnings', '--restrict-filenames', '--add-metadata', '--write-auto-sub', '--embed-subs', '--sub-lang=en,fr,es,de', '--format=mp4[height<=480]/mp4/best', '--output=%(title)s__%(format_id)s__%(id)s__%(extractor)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-j', 'https://www.youtube.com/user/NewCreationChurch/live', '--playlist-items', '1', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.0 (CPython) - Linux-4.15.0-118-generic-x86_64-with-glibc2.27
[debug] exe versions: ffmpeg 4.3-2, ffprobe 4.3-2, rtmpdump 2.4
[debug] Proxy map: {}
华文崇拜（2020年10月10日至12日）| 新造教会 ・ Mandarin Service (10–12 Oct 2020) | New Creation Church
YL8WCTghMsg
null
```

## Description

youtube-dl redirects youtube.com/user/channel/live to the wrong video which is not even a live broadcast (`is_live` is `null` instead of `true`) : 
```
$ youtube-dl -j https://www.youtube.com/user/NewCreationChurch/live --playlist-items 1 | jq -r '.title, .id, .is_live'
华文崇拜（2020年10月10日至12日）| 新造教会 ・ Mandarin Service (10–12 Oct 2020) | New Creation Church
YL8WCTghMsg
null
```
instead of pointing to where the browser points that is to say https://www.youtube.com/watch?v=xRHIySE7S6Y :  
```
$ youtube-dl -j https://www.youtube.com/watch?v=xRHIySE7S6Y --playlist-items 1 | jq -r '.title, .id, .is_live'
Joseph Prince at New Creation Church | 2.30pm
xRHIySE7S6Y
true
```

Please note that the URL https://www.youtube.com/user/NewCreationChurch/live is only available once a week.

If the links I provided are unavailable, you can try on any other channel that has a live video : https://www.youtube.com/results?sp=EgJAAQ%253D%253D&search_query=video

**Comment by shinctl** [comment]
I'm having the same issues. 
It's not detecting the correct stream ID using the channel name /live

**Comment by mushroomslove** [comment]
I'm having the same issues too from 2 days ago.
It seems youtube-dl cannot fetch the live stream but get the whole playlist that the channel has in their video.

**Comment by sebma** [comment]
@dstftw Can you please give the commit number ?

**Comment by sebma** [comment]
@dstftw If I don't add the `--playlist-items 1` in the `youtube-dl`, it extracts all the videos just like it would in "https://www.youtube.com/user/NewCreationChurch/videos" but then I guess maybe I should create a different issue.

**Comment by sebma** [comment]
@dstftw Moreover, if I had the `--playlist-items 1`, youtube-dl v2020.11.18 doesn't always pick the right video when the url is a live broadcast, example : 

```bash
$ youtube-dl -j https://www.youtube.com/channel/${channelID}/live --playlist-items 1 -v | jq -r '.title, .id, .is_live'
[debug] System config: []
[debug] User config: ['--ignore-errors', '--prefer-ffmpeg', '--no-warnings', '--restrict-filenames', '--add-metadata', '--write-auto-sub', '--embed-subs', '--sub-lang=en,fr,es,de', '--format=mp4[height<=480]/mp4/best', '--output=%(title)s__%(format_id)s__%(id)s__%(extractor)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-j', 'https://www.youtube.com/channel/UCdFVjFYEnesMh-5fC1_fzmg/live', '--playlist-items', '1', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.18
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-122-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
Qui De Nous Deux 👵👴 On se voit où dans 20 ans ??!
25zs2Ny-Egk
null
$ youtube-dl -j https://www.youtube.com/channel/${channelID}/live --playlist-items 1 -v | jq -r '.title, .id, .is_live'
[debug] System config: []
[debug] User config: ['--ignore-errors', '--prefer-ffmpeg', '--no-warnings', '--restrict-filenames', '--add-metadata', '--write-auto-sub', '--embed-subs', '--sub-lang=en,fr,es,de', '--format=mp4[height<=480]/mp4/best', '--output=%(title)s__%(format_id)s__%(id)s__%(extractor)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-j', 'https://www.youtube.com/channel/UCdFVjFYEnesMh-5fC1_fzmg/live', '--playlist-items', '1', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.18
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-122-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
VOS PRÉJUGÉS SUR NOUS 🙊 Épisode 2 à ne pas manquer
SzTSbBmrA7k
null
```

**Comment by sebma** [comment]
@dstftw BTW : As you have noticed, the `.is_live` returned is `null` instead of `true`

**Comment by sebma** [comment]
@dstftw I think I get it :smile: This happens because `.is_live`  is `null` instead of `true` that `youtube-dl` parses `https://www.youtube.com/channel/${channelID}/videos`, just like the web browser redirects when there no live broadcasting.

**Comment by sebma** [comment]
@dstftw I think I get (part of it) :smile: 
`youtube-dl` parses `https://www.youtube.com/channel/${channelID}/videos` because the `.is_live` returned by `https://www.youtube.com/channel/${channelID}/live` is `null` instead of `true`, just like the web browser redirects when there no live broadcasting.
But still, I don't understand why I doesn't always return the same `.id`

**Comment by dstftw** [comment]
https://www.youtube.com/channel/UCdFVjFYEnesMh-5fC1_fzmg/live returns to the home tab which is downloaded as expected.
