### ISSUE TITLE
Extend log

### ISSUE THREAD

**Issue by mbnoimi** [ytdl-org/youtube-dl#26866]
## Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2020.09.20**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

During downloading a full YouTube channel some videos give `The uploader has not made this video available in your country` but the log doesn't mention which video generated the error message.

I suggest to add the link of the video in addition to the error message.

**Comment by pukkandan** [comment]
I don't understand your issue. The log clearly gives the id of the video:

`
[download] Downloading video 1 of 13
[youtube] QlFRoUMkUDw: Downloading webpage
[youtube] QlFRoUMkUDw: Downloading embed webpage
[youtube] QlFRoUMkUDw: Refetching age-gated info webpage
ERROR: The uploader has not made this video available in your country.
`
