### ISSUE TITLE
servustv is broken for some urls

### ISSUE THREAD

**Issue by puchu** [ytdl-org/youtube-dl#26872]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['-f', 'bestvideo[height<=?1080][fps<=?30]+bestaudio/best', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.servustv.com/videos/aa-24h32f1411w12/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.7.8 (CPython)
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[Servus] AA-24H32F1411W12: Downloading webpage
[Servus] AA-24H32F1411W12: Downloading m3u8 information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/servus.py", line 61, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1359, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Most urls still work fine, but https://www.servustv.com/videos/aa-24h32f1411w12/ is broken

**Comment by puchu** [comment]
seems the video is located at:

https://cs.liiift.io/v1/STV/pd/37/13/B8/30/FO-25GUA77KDBH11/master.m3u8

**Comment by ronny80** [comment]
same problem with
https://www.servustv.com/videos/aa-2575dep351w12

**Comment by mittern-8** [comment]
Same problem here:

https://www.servustv.com/videos/aa-1yqgz6v452112/
https://www.servustv.com/videos/aa-24dsn9qvn1w12/

Works clueless with jDownloader2 but youtube-dl_v2020.09.20 reports:

> ERROR: No video formats found; please report this issue on https://yt-dl.org/bug

Going back to older versions of youtube-dl didn't solve the issue :( 


@puchu 
> seems the video is located at:
> 
> https://cs.liiift.io/v1/STV/pd/37/13/B8/30/FO-25GUA77KDBH11/master.m3u8

How did you find that m3u8-link without "youtube-dl -g"?
