### ISSUE TITLE
Some YouTube videos won't download at all

### ISSUE THREAD

**Issue by HalvorRaknes** [ytdl-org/youtube-dl#26880]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Sometimes YouTube videos which have been recently posted won't download. the '-F' output typically reads like this:

```
$ youtube-dl -F https://www.youtube.com/watch?v=sL8ExGs6hww 
[youtube] sL8ExGs6hww: Downloading webpage
[youtube] sL8ExGs6hww: Downloading MPD manifest
[info] Available formats for sL8ExGs6hww:
format code  extension  resolution note
139          m4a        audio only DASH audio   64k , m4a_dash container, mp4a.40.5@ 48k (24000Hz)
140          m4a        audio only DASH audio  144k , m4a_dash container, mp4a.40.2@128k (48000Hz)
160          mp4        256x144    DASH video  124k , mp4_dash container, avc1.42c00b, 30fps, video only
133          mp4        426x240    DASH video  258k , mp4_dash container, avc1.4d4015, 30fps, video only
134          mp4        640x360    DASH video  646k , mp4_dash container, avc1.4d401e, 30fps, video only
135          mp4        854x480    DASH video 1171k , mp4_dash container, avc1.4d401f, 30fps, video only
136          mp4        1280x720   DASH video 2326k , mp4_dash container, avc1.4d401f, 30fps, video only
386          mp4        unknown    tiny 
387          mp4        unknown    tiny  (best)
```
I have attempted applying the '--merge-output-format FORMAT' option but the result only becomes a corrupted file.

Obviously, this issue can be resolved by simply waiting a few hours. YouTube will then assemble the usual downloadable files. My problem, however, is that I download media files and then watch them when I am offline, which I usually am.

This issue touches on the question of how can video version with higher resolution be downloaded, i.e. 1080p and higher? Obviously, when I am able to watch a video when I'm watching it directly off of the YouTube page, there should be some way of capturing the stream, any stream. If youtube-dl cannot always do that, can someone suggest to me how that can be done using some other app or perhaps the 'wget' command?

**Comment by anantdark** [comment]
Were you downloading it while it was streaming? Because i can't replicate the issue.
Tried downloading - 
`youtube-dl https://www.youtube.com/watch?v=sL8ExGs6hww
[youtube] sL8ExGs6hww: Downloading webpage
[download] Destination: DocTalk Episode #69 - Diet, Nutrition, Healing - Monday LIVE Q&A-sL8ExGs6hww.f136.mp4
[download]   0.1% of 1.25GiB at 864.56KiB/s ETA 25:12^C
ERROR: Interrupted by user`
Got no error.

**Comment by HalvorRaknes** [comment]
> Were you downloading it while it was streaming? Because i can't replicate the issue.
> Tried downloading

Well, as I wrote, the problem only lasts a few hours usually, then the video will download as usual. I also explained why that still remains a challenge for me.

**Comment by anantdark** [comment]
Well the issue is closed now.

**Comment by HalvorRaknes** [comment]
> Well the issue is closed now.

So, do I have to duplicate my initial post and ask the question anew in order to get a proper response to either of my questions? Or will that get me sanctioned?

I'm rather confused by this closing.
