### ISSUE TITLE
Please update the readme - Cookies.txt is no longer available

### ISSUE THREAD

**Issue by ScribbleGhost** [ytdl-org/youtube-dl#26885]
Line 882 in the [readme](https://github.com/ytdl-org/youtube-dl/edit/master/README.md) suggests to use cookies.txt for Chrome. This extension seems to be removed.

**Comment by october262** [comment]
shows here it's still available - https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid?hl=en

**Comment by ScribbleGhost** [comment]
The initial link was for [cookies.txt](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg) which seems deprecated, but [Get cookies.txt](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid/related?hl=en) worked for me.
Updating either the name or link should suffice 😉

**Comment by marco97pa** [comment]
@ScribbleGhost I edited the README.md and proposed the change. Waiting a response by the project maintainer to be merged and fixed.

**Comment by rlaPHOENiX** [comment]
Do note that this extension is not by the original Creator (at least of the Chrome Web Store repo).

It was previously managed by `Genuinous™`. I don't have any immediate reasons to worry about anything malicious but just letting everyone know.

**Comment by devnoname120** [comment]
@rlaphoenix This comment didn't age very well :(
https://www.reddit.com/r/youtubedl/comments/11i5vyq/psa_the_get_cookiestxt_extension_is_now_actively/

**Comment by rlaphoenix** [comment]
> @rlaphoenix This comment didn't age well :( https://www.reddit.com/r/youtubedl/comments/11i5vyq/psa_the_get_cookiestxt_extension_is_now_actively_malware/

How so? What I stated is still true. The extension is still not managed by the same creator as originally. It just took the same name. `cookies.txt` vs. `get cookies.txt`.

**Comment by hopeseekr** [comment]
Neither are available now.

**Comment by dirkf** [comment]
But the extensions recommended for use here **are** available.
