### ISSUE TITLE
404 Error downloading from Vimeo

### ISSUE THREAD

**Issue by darb78** [ytdl-org/youtube-dl#26891]
I'm receiving the following error when attempting to download a video from Vimeo. 

ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I have confirmed that I'm running the latest version of youtube-dl. I confirmed the video is live at the location. As locations sometimes matter I also tested this running a vpn to the US (as I'm not in the US at the moment). The full output is attached. 
[youtube-dl_Vimeo Error.txt](https://github.com/ytdl-org/youtube-dl/files/5382032/youtube-dl_Vimeo.Error.txt)

**Comment by darb78** [comment]
Why was this labeled incomplete and closed, did I fail to include something?

**Comment by Melonadev** [comment]
You probably ignored/removed the template which is automatically generated whenever a user add a new issue (and the user has to fill in the template).
See this issue for example (it's from 2019 and is probably outdated, but you get my point):
https://github.com/ytdl-org/youtube-dl/issues/20326
