### ISSUE TITLE
Funimation Extractor, Unable to extract al:web:url Error

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [ytdl-org/youtube-dl#26905]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: ['--netrc']
[debug] Custom config: []
[debug] Command-line args: ['-n', '--no-check-certificate', '--user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36', '--audio-quality', '0', '--audio-format', 'aac', '-f', 'best', '--verbose', 'https://www.funimation.com/shows/assault-lily-bouquet/lily-of-the-valley-return-of-happiness/?qid=']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.5 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[Funimation] Logging in
[Funimation] lily-of-the-valley-return-of-happiness: Downloading webpage
WARNING: [Funimation] lily-of-the-valley-return-of-happiness: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/funimation.py", line 96, in _real_extract
    player_url = self._html_search_meta([
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1138, in _html_search_meta
    return self._html_search_regex(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1019, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

Command: 
```
youtube-dl -n --no-check-certificate --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" --audio-quality 0 --audio-format aac -f best --verbose "https://www.funimation.com/shows/assault-lily-bouquet/lily-of-the-valley-return-of-happiness/?qid="
```

## Description

it seems Funimation has added session keys to their m3u8 playlist files, Mentioned here: https://github.com/anidl/funimation-downloader-nx/issues/32#issuecomment-709698256

FFmpeg also has issues downloading as well

![Screen Shot 2020-10-17 at 1 04 55 am](https://user-images.githubusercontent.com/2242880/96270063-e4ddd400-1016-11eb-8d86-0775fa56009d.jpg)
![Screen Shot 2020-10-17 at 1 05 17 am](https://user-images.githubusercontent.com/2242880/96270075-e7402e00-1016-11eb-8429-f63897594c40.jpg)

**Comment by october262** [comment]
retry this link > youtube-dl --no-part --restrict-filenames "https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/2281735/Japanese/2281735_Japanese_3ba1e8d2-910a-eb11-82a8-dd291e252010.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8yMjgxNzM1L0phcGFuZXNlLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MDI4ODQ1Njh9fX1dfQ__&Signature=v~U8iAQHVH1hRl-PCEA~YgEzNWg~wjdVLwHIznWb5KhT~8Z-KCLrtF7hFtbvnseAKVtm8mf4AB6jsAHfqcLLEGan~5~p1hMr5owM7EiBG1WSO1VnVK-lCPkwilTsP5a98Wl7OStgLgi34rDxboVqphHdt77neBuOCwcfxcK6EIUsKhakK1J1VRtr2vPk2h-M4xrQqioA-WJASrjvToQzecmFIVVy-p9x-fpOe6WC5PVqJrNRmi4jR9bqmcDsH3Q69C6SSwFqCSXIirg9Fxy5K5WI1CIbqf1Yf9rfiI9Eup8majC~ViAEYsml0ucCY4VH25a7NU4ZhUfxO4MhWuw~OQ__&Key-Pair-Id=APKAIHNXECY27H4O6NIA&rt=1456991" withe the Firefox addon called "the stream detector'" set it to youyube-dl command and just copy & paste the m3u8 URL.
