### ISSUE TITLE
youtube-dl downloading description, subtitle, etc for skipped files

### ISSUE THREAD

**Issue by chumma12** [ytdl-org/youtube-dl#26908]
Hi,
I give the following options while downloading videos from a channel...
--write-sub
--write-description
--write-info-json
--max-filesize 50m

Now, due to the size filter, many videos are skipped and not downloaded.
But the description and subtitles for those skipped files are still downloaded.
I think additional files should also be skipped for skipped videos.

**Comment by dstftw** [comment]
This is expected behavior.

**Comment by chumma12** [comment]
is it expected behavior, or just the current behavior.
I am skipping the video because I am not interested in that video.  In that case why the other associated files?
