### ISSUE TITLE
Upcoming livestreams in channel result in error message when archiving

### ISSUE THREAD

**Issue by mortisj** [ytdl-org/youtube-dl#26916]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--no-cache-dir', u'-i', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]', u'--download-archive', u'000-index', u'https://www.youtube.com/channel/UCqs4i33cQluv8B1ijLuLiIA']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-101-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[youtube:channel] UCqs4i33cQluv8B1ijLuLiIA: Downloading channel page
[youtube:playlist] UUqs4i33cQluv8B1ijLuLiIA: Downloading webpage
[download] Downloading playlist: Uploads from Hillhurst United Church
[youtube:playlist] UUqs4i33cQluv8B1ijLuLiIA: Downloading page #1
[youtube:playlist] playlist Uploads from Hillhurst United Church: Downloading 154 videos
[download] Downloading video 1 of 154
[youtube] ZO8gIFzLZdg: Downloading webpage
ERROR: Premieres in 23 hours
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2231, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: Premieres in 23 hours

[download] Downloading video 2 of 154
[download] Thanksgiving Outdoors! October 11, 2020 | Hillhurst United Church has already been recorded in archive
[download] Downloading video 3 of 154
[download] Livestream October 11, 2020 | Hillhurst United Church has already been recorded in archive
[download] Downloading video 4 of 154
...
[download] Downloading video 153 of 154
[download] Danielle Ayana James on "Spotlight" (2016-02-21) has already been recorded in archive
[download] Downloading video 154 of 154
[download] Bill Phipps on Climate Change (2016-03-02) has already been recorded in archive
[download] Finished downloading playlist: Uploads from Hillhurst United Church

## Description

When archiving a channel, upcoming livestreams result in an error message and a return code of 1.  Not a showstopper because other videos in the channel seem to download OK.   By the time you look at this bug report the livestream probably will have started, so let me know if you need a test case set up somewhere.

**Comment by dstftw** [comment]
This is expected behavior.

**Comment by thibaultmol** [comment]
@dstftw This also means that thumbnails aren't able to be downloaded though? Even though those can be attached to a scheduled livestream.
