### ISSUE TITLE
Now Can't Download Private Video (From Private Group)

### ISSUE THREAD

**Issue by webzone-vn** [ytdl-org/youtube-dl#26913]
![001 17-10-2020](https://user-images.githubusercontent.com/8991804/96338564-42c2f800-10b9-11eb-95d1-a12cd013781a.png)

## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -F "https://www.facebook.com/hotkidsvnvietnam/videos/4531304346910963" --add-header 'cookie: sb=XXXXXXXXXXXXXXX; wd=XXXXXXXXXXXXXXX; datr=XXXXXXXXXXXXXXX; c_user=XXXXXXXXXXXXXXX; spin=XXXXXXXXXXXXXXX; xs=XXXXXXXXXXXXXXX; fr=XXXXXXXXXXXXXXX' --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.facebook.com/hotkidsvnvietnam/videos/4531304346910963', '--add-header', 'cookie: sb=XXXXXXXXXXXXXXX; wd=XXXXXXXXXXXXXXX; datr=XXXXXXXXXXXXXXX; c_user=XXXXXXXXXXXXXXX; spin=XXXXXXXXXXXXXXX; xs=XXXXXXXXXXXXXXX; fr=XXXXXXXXXXXXXXX', '--verbose']
[debug] Adding header from command line option cookie: sb=XXXXXXXXXXXXXXX; wd=XXXXXXXXXXXXXXX; datr=XXXXXXXXXXXXXXX; c_user=XXXXXXXXXXXXXXX; spin=XXXXXXXXXXXXXXX; xs=XXXXXXXXXXXXXXX; fr=XXXXXXXXXXXXXXX
![001 17-10-2020](https://user-images.githubusercontent.com/8991804/96338542-04c5d400-10b9-11eb-9157-6ca660188ca9.png)

[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.7.9 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-04-03-52523b6, ffprobe git-2020-04-03-52523b6
[debug] Proxy map: {}
[facebook] 4531304346910963: Downloading webpage
[facebook] 4531304346910963: Downloading webpage
[facebook] 4531304346910963: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\python37\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\python37\lib\site-packages\youtube_dl\extractor\facebook.py", line 484, in _real_extract
    video_id, fatal_if_no_video=True)
  File "c:\python37\lib\site-packages\youtube_dl\extractor\facebook.py", line 380, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I usually download private video from Facebook (Using --add-header cookie), but now I can not.

**Comment by dstftw** [comment]
You must provide access to the video for any work on this.

**Comment by magoafono** [comment]
I have the same problem when downloading private video.
I tried to use username and password to provide access but the error persists:

python /usr/local/bin/youtube-dl --verbose -u USERNAME -p PASSWORD   https://www.facebook.com/filippo.ceccotti/videos/10223386280556190/ 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.facebook.com/filippo.ceccotti/videos/10223386280556190/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-52-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 10223386280556190: Downloading webpage
[facebook] 10223386280556190: Downloading webpage
[facebook] 10223386280556190: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 484, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 380, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
