### ISSUE TITLE
Downloaded videos do not open on IPhone

### ISSUE THREAD

**Issue by artarba** [ytdl-org/youtube-dl#26928]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Git HEAD: bb29d74
[debug] Python version 3.8.3 (CPython) - macOS-10.13.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
```

## Description

Hi!

Forgive me in advance for my mistakes, I do it the first time.

I wrote a telegram to a bot that uses your library to download videos from YouTube and send them to the user.

Everything works fine on any PC OS, but on the iPhone - sound is present, but there is no image in the video.

I use these settings:

ydl_opts = {
        "format": "bestvideo[vcodec^=avc1,vcodec*=mp4]+bestaudio[vcodec*=aac,vcodec*=mp3]/best[ext=mp4]",
        'outtmpl': outtmpl,
        'verbose': True,
        "postprocessors": [{
            "key": "FFmpegVideoConvertor",
            "preferedformat": "mp4"
        }]}

I have also tried it:

#ydl_opts = {'format': '18', 'outtmpl': outtmpl, 'verbose': True}

But it didn't get better, always the same problem.
If it helps somehow, below is the information about the downloaded video and verified by the Mediainfo program:

![Снимок экрана 2020-10-19 в 10 39 03](https://user-images.githubusercontent.com/65290026/96396089-e1a23e00-11f8-11eb-92b5-f9cf124b4ee2.png)

Attached are 2 videos that do not open on the iPhone (but there are much more than 2).

https://www.youtube.com/watch?v=n8iXFk_JsjU
https://www.youtube.com/watch?v=2AMRBUQ-NbM

UPD: 

this is what "youtube-dl -F <url>" shows me:

Not working links:
18 | mp4 | 640x360 | 360p | 717k | avc1.42001E, 30fps, mp4a.40.2@ 96k (44100Hz), 19.65MiB | https://www.youtube.com/watch?v=n8iXFk_JsjU.
18 | mp4 | 640x360 | 360p | 685k | avc1.42001E, 30fps, mp4a.40.2@ 96k (44100Hz), 45.66MiB | https://www.youtube.com/watch?v=2AMRBUQ-NbM.

The working video that is played on iPhones
18 | mp4 | 480x360 | 360p | 740k | avc1.42001E, 25fps, mp4a.40.2@ 96k (44100Hz), 925.03KiB (best) | https://www.youtube.com/watch?v=rROAJ2B8FCQ.

It does not depend on the iPhone model.
I tried it on:
Iphone X
Iphone XR
Iphone 8
Iphone 11

The result is the same everywhere.
I would be very grateful if you could help me.

**Comment by october262** [comment]
what model iphone  is it that you are trying to watch the video on ??

**Comment by artarba** [comment]
> what model iphone is it that you are trying to watch the video on ??

It does not depend on the iPhone model.
I tried it on:
Iphone X
Iphone XR
Iphone 8
Iphone 11

The result is the same everywhere.
I would be very grateful if you could help me.

**Comment by october262** [comment]
try changing the resolution from 640x360 to 640x480 - https://7labs.io/mobile/play-mkv-avi-1080p-and-other-formats-ios.html

**Comment by artarba** [comment]
> try changing the resolution from 640x360 to 640x480 - https://7labs.io/mobile/play-mkv-avi-1080p-and-other-formats-ios.html

Almost as you wrote, but it led me to the right idea. 

I solved this problem by changing the video output window to 1280x720 standards, without changing the video itself and its codecs/extensions.

Thank's!
