### ISSUE TITLE
unable to extract/download embedded Facebook video

### ISSUE THREAD

**Issue by mlschuh52** [ytdl-org/youtube-dl#26921]
>>>>> Thank you for youtube-dl - I use it several times a week!

# /usr/local/bin/youtube-dl --verbose -f best 'https://www.facebook.com/carla.akkaoui/posts/10156251903035811'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'best', 'https://www.facebook.com/carla.akkaoui/posts/10156251903035811']
[debug] Encodings: locale ISO-8859-1, fs iso8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.7.7 (CPython) - Linux-5.6.13-100.fc30.x86_64-x86_64-with-fedora-30-Thirty
[debug] exe versions: avconv 12.2, avprobe 12.2, ffmpeg 4.1.5, ffprobe 4.1.5
[debug] Proxy map: {}
[facebook] 10156251903035811: Downloading webpage
ERROR: Unable to extract single video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/facebook.py", line 479, in _real_extract
    video_id = self._search_regex(r'video_id:\s*"([0-9]+)"', webpage, 'single video id')
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract single video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by october262** [comment]
play the video and see if there's  3 dots ...  in the upper right hand corner of the video
it should say copy URL , once copied, feed the URL into youtube-dl to
download the video

**Comment by mlschuh52** [comment]
> play the video and see if there's 3 dots ... in the upper right hand corner of the video
> it should say copy URL , once copied, feed the URL into youtube-dl to
> download the video

That worked!  Thanks.  (How did I not know this???)
