### ISSUE TITLE
HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>). My IP has been blocked again, please read the comment for clarification.

### ISSUE THREAD

**Issue by Ares-Code** [ytdl-org/youtube-dl#26931]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by Ares-Code** [comment]
My IP has been blocked again. This is the second time this issue is happening. I wish to specify that I am working on a research project where we are trying to understand the impact of technology on Bollywood music. This requires me to extract and analyze audio files for a number of songs (more than 1k). I would love to get my request limits increased as this issue may occur again. Youtube-dl is an amazing service and it would be great if I could continue using it.

**Comment by davdroman** [comment]
@Ares-Code youtube-dl is not a service, it's an open source tool that connects directly to YouTube to download videos. It's up to YouTube to rate limit your IP if they deem it necessary. I'm guessing a workaround would probably be to not download anything for a few days and try again.
