### ISSUE TITLE
Fails to extract video from a (public) Facebook post

### ISSUE THREAD

**Issue by michael-myers** [ytdl-org/youtube-dl#26941]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

Similar to issue #26823 but in _this_ case, the verbose log does _not_ mention `only available for registered users`

## Verbose log

```
% youtube-dl --verbose "https://www.facebook.com/GymMeme/posts/3025431024227465"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/GymMeme/posts/3025431024227465']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 3025431024227465: Downloading webpage
ERROR: Unable to extract single video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 479, in _real_extract
    video_id = self._search_regex(r'video_id:\s*"([0-9]+)"', webpage, 'single video id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract single video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I confirmed using a private browsing tab that this Facebook post is available in a browser without any authentication, and should be available to youtube-dl. The video is in a public post in a public group.

If the regex here is `self._search_regex(r'video_id:\s*"([0-9]+)"'` then it might've broken on a new naming scheme. See the screenshot below.

<img width="1133" alt="Screen Shot 2020-10-19 at 9 27 06 PM" src="https://user-images.githubusercontent.com/5177188/96540331-450c8a00-1252-11eb-89fe-09e5d77755d4.png">

**Comment by october262** [comment]
try this >   youtube-dl --force-generic-extractor https://www.facebook.com/GymMeme/posts/3025431024227465
