### ISSUE TITLE
[Question] Enable an extractor at runtime to embed youtube-dl

### ISSUE THREAD

**Issue by C0D3D3V** [ytdl-org/youtube-dl#26948]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I use youtube-dl in one of my projects (moodle-dl). I can understand that with so many PR requests and so few team members, it can take a long time until an extractor gets merged.

I wonder if I can simply add extractors in an embedded youtube-dl instance externally? 
For example, if I want to add the Extractor for zoom.us (https://github.com/ytdl-org/youtube-dl/pull/24751) at runtime, is that possible?

**Comment by dstftw** [comment]
Read developer instructions.

**Comment by C0D3D3V** [comment]
If someone tries to do the same, I suppose it works like this:
```
ydl.add_info_extractor(YourExternalExtractor(ydl))
```

**Comment by C0D3D3V** [comment]
Nope, this does not work, because Generic Extractor will raise an error as soon as it is tested... Generic Extractor is last in the Extractor list so you have to add your external extractor before the generic one, like this:

```
    additional_extractors = [
        OpencastIE(ydl),
        OpencastPlaylistIE(ydl),
    ]

    for extractor in additional_extractors:
        ydl._ies.insert(0, extractor)
        ydl._ies_instances[extractor.ie_key()] = extractor

```
