### ISSUE TITLE
youtube_dl.utils.ExtractorError: Cannot parse data for Facebook video

### ISSUE THREAD

**Issue by GoMeister** [ytdl-org/youtube-dl#26958]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
eric@eric-Latitude-E5510:~/tmp$ youtube-dl --recode-video mkv -k https://www.facebook.com/alice.offley/videos/10164224184305084/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--recode-video', 'mkv', '-k', 'https://www.facebook.com/alice.offley/videos/10164224184305084/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-52-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 10164224184305084: Downloading webpage
[facebook] 10164224184305084: Downloading webpage
[facebook] 10164224184305084: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 482, in _real_extract
    _, info_dict = self._extract_from_url(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 380, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE

youtube_dl.utils.ExtractorError: Cannot parse data for Facebook video, url in log above.

**Comment by october262** [comment]
this link - https://www.facebook.com/alice.offley/videos/10164224184305084/ 
says content not available right now.

**Comment by GoMeister** [comment]
Video was playing at time of error.  I'll check again.

**Comment by GoMeister** [comment]
For me, video is playable through FB, but error persists.

**Comment by october262** [comment]
still not playable for me. is the video a private video ??
if you can play the video click the 3 dots ...  in the upper right hand 
corner of the video and see if there's an option to download/copy the URL of the video.

**Comment by GoMeister** [comment]
There's a "Copy link" (Firefox of Ubuntu) which gives:

https://www.facebook.com/510785083/videos/10164224184305084/

it's not private AFAIK, but I am friends with the person who posted it.  
I tried youtube_dl with the URL above, still the same error.

**Comment by october262** [comment]
try youtube-dl --force-generic-extractor  URL
or youtube-dl --username (your user name)  --password (your password) URL

**Comment by Mattwmaster58** [comment]
Wow, interestingly the generic extractor works just fine! Used `--cookies` to download a private video successfully.

**Comment by GoMeister** [comment]
eric@eric-Latitude-E5510:~/tmp$ youtube-dl --recode-video mkv -k 
https://www.facebook.com/510785083/videos/10164224184305084/ 
--force-generic-extractor
[generic] 10164224184305084: Requesting header
WARNING: Forcing on generic information extractor.
[generic] 10164224184305084: Downloading webpage
[generic] 10164224184305084: Extracting information
[redirect] Following redirect to 
https://www.facebook.com/510785083/videos/10164224184305084/?_fb_noscript=1
[facebook] 10164224184305084: Downloading webpage
[facebook] 10164224184305084: Downloading webpage
[facebook] 10164224184305084: Downloading webpage
ERROR: Cannot parse data; please report this issue on 
https://yt-dl.org/bug . Make sure you are using the latest version; 
type  youtube-dl -U  to update. Be sure to call youtube-dl with the 
--verbose flag and include its complete output.

**Comment by GoMeister** [comment]
Is there a way of specifying the username/password securely? I've tried 
that before and had to reset the ID on several devices afterwards....

**Comment by GoMeister** [comment]
Thanks - what file do you specify with that option?

**Comment by Mattwmaster58** [comment]
@GoMeister I suspect the generic extractor won't work with `--username` and `--password` but haven't tried. I have also run into being forced to change my Facebook password when using the aforementioned options. I found success using `--cookies` to specify a cookies.txt file that I generated by logging into Facebook in a browser. I also used `--add-header` to add the UA of the browser I used to login but I'm unsure if that was necessary. 

Interestingly, using `--username` + `--password` failed not using `--force-default-extractor` and made it so I had to change my facebook password. But if I used `--add-header` to specify a browser UA then I didn't have to change my facebook password.

**Comment by Nex4rius** [comment]
I have another video that isn't working. I tried it with and without credentials and with the --force-generic-extractor and everything failed with the "cannot parse data" error
https://www.facebook.com/andrea.bondi.50/videos/4903472349693254

I tried --force-default-extractor but it says "error: no such option"
