### ISSUE TITLE
Youtube channel playlists are not downloading

### ISSUE THREAD

**Issue by Tokariew** [ytdl-org/youtube-dl#26952]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
➜ youtube-dl  https://www.youtube.com/c/Coreyms/playlists --verbose
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/c/Coreyms/playlists', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.6 (CPython) - Linux-5.8.15-201.fc32.x86_64-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube:playlists] Coreyms: Downloading webpage
[download] Downloading playlist: Corey Schafer
[youtube:playlists] playlist Corey Schafer: Downloading 0 videos
[download] Finished downloading playlist: Corey Schafer
```

## Description

After version 2020.06.16.1 download using channel playlist page url is not possible
Reverting this patch https://github.com/ytdl-org/youtube-dl/commit/e942cfd1a74cea3a3a53231800bbf5a002eed85e seems to fix downloading from such url, but this issue will no longer be fixed https://github.com/ytdl-org/youtube-dl/issues/25810 

I tried youtube-dl from release page and from Fedora repository, both don't work

**Comment by oobitydoo** [comment]
I had the same thing start happening in the last few days, but until recently I'd been successfully downloading playlists using version 2020.09.20 (downloaded and sig verified from here on github). Did youtube change their response to something that youtube-dl doesn't understand? I've attached the file I got from running the same command with `--write-pages` here, in case it helps.

```
youtube-dl https://www.youtube.com/c/Coreyms/playlists --verbose --write-pages
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/c/Coreyms/playlists', '--verbose', '--write-pages']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.7.5 (CPython) - Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlists] Coreyms: Downloading webpage
[youtube:playlists] Saving request to Coreyms_https_-_www.youtube.com_c_Coreyms_playlistsdisable_polymer=true.dump
[download] Downloading playlist: Corey Schafer
[youtube:playlists] playlist Corey Schafer: Downloading 0 videos
[download] Finished downloading playlist: Corey Schafer
```


[youtube-dl_write-pages_result.txt](https://github.com/ytdl-org/youtube-dl/files/5423636/youtube-dl_write-pages_result.txt)

**Comment by alexkuc** [comment]
Got the issue on Mac with binary version `2020.09.20` (installed using `Homebrew`):

```
youtube-dl https://www.youtube.com/channel/UCt6vkpfl-kNj6vUletDgMGA/playlists
[debug] System config: []
[debug] User config: [u'-o', u'~/Music/Youtube/%(playlist)s/%(title)s_%(epoch)s.%(ext)s', u'--download-archive', u'~/.config/youtube-dl/archive.txt', u'--ignore-errors', u'--yes-playlist', u'--restrict-filenames', u'-x', u'--audio-format', u'mp3', u'--embed-thumbnail', u'--audio-quality', u'0', u'--verbose']
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/channel/UCt6vkpfl-kNj6vUletDgMGA/playlists']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.16 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlists] UCt6vkpfl-kNj6vUletDgMGA: Downloading webpage
[download] Downloading playlist: Alexander Kucheryuk
[youtube:playlists] playlist Alexander Kucheryuk: Downloading 0 videos
[download] Finished downloading playlist: Alexander Kucheryuk
```

If I point to a specific playlist (as opposed to downloading all playlists), I get this:

```
youtube-dl https://www.youtube.com/watch?v=WddpRmmAYkg&list=PLUIGTHchKm7EYUxldxnASmrfarSGV7gKG
[1] 25793
Downloads $ [debug] System config: []
[debug] User config: [u'-o', u'~/Music/Youtube/%(playlist)s/%(title)s_%(epoch)s.%(ext)s', u'--download-archive', u'~/.config/youtube-dl/archive.txt', u'--ignore-errors', u'--yes-playlist', u'--restrict-filenames', u'-x', u'--audio-format', u'mp3', u'--embed-thumbnail', u'--audio-quality', u'0', u'--verbose']
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=WddpRmmAYkg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.16 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] WddpRmmAYkg: Downloading webpage
[download] Boris Brejcha Style @ Art of Minimal Techno Tripping - The Mad Doctor by RTTWLR has already been recorded in archive
```

In this case, the process is hanging indefinitely without any warnings or errors.

Downloading a video directly works as expected, seems only playlists are affected.

**Comment by numlockkey** [comment]
Same problem here. It will not download any playlist:

youtube-dl -o "d:\YT Downloads\%%(uploader)s\%%(playlist)s\%%(playlist_index)s - %%(title)s.%%(ext)s" https://www.youtube.com/c/Kevindarrah/playlists
[youtube:playlists] Kevindarrah: Downloading webpage
[download] Downloading playlist: Kevin Darrah
[youtube:playlists] playlist Kevin Darrah: Downloading 0 videos
[download] Finished downloading playlist: Kevin Darrah

**Comment by llacb47** [comment]
It's because `disable_polymer` no longer works on channel pages.

**Comment by numlockkey** [comment]
What does it mean that  disable_polymer no longer works on channel pages? Does it mean that there is no way to get this to work
as it used to?

**Comment by alexkuc** [comment]
@numlockkey 

So `disable_polymer` appears to revert YouTube to its "classical" layout but looks like Google is phasing it out (see [this](https://support.google.com/youtube/thread/33039898?hl=en&msgid=36418080) and [this](https://support.google.com/youtube/thread/27596769)).

> Does it mean that there is no way to get this to work as it used to?

Looks like a PR is needed to update the script to work with new YouTube layout (I think).

**Comment by HershyL** [comment]
I am having the same issue

**Comment by remitamine** [comment]
Works with the latest release.
