### ISSUE TITLE
2 different Questions

### ISSUE THREAD

**Issue by svenson26** [ytdl-org/youtube-dl#26968]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, I would like to achieve the following with a start

1. issue of *.mkv AND *.mp4
     At the moment I use the parameter: --merge-output-format mkv is there any way to "append" the *.mp4 to it?

2. If I use the parameter -x the videos will be deleted and audio will be left over. If I now use the parameter -k then I keep all video formats. Is it possible to select the video format that I want to keep. For example: *.mkv

3. output of the different files to different folders (mp3 to the /mp3 folder - mkv to the /mkv folder).

I'm not sure if I have to start youtube-dl several times for this or if it is possible to run it once.
Thanks a lot.

Translated with www.DeepL.com/Translator (free version)

**Comment by dstftw** [comment]
1. Indecipherable.
2. Read FAQ on format selection.
3. Read FAQ on output template.
