### ISSUE TITLE
Some YouTube videos won't download at all (2nd try)

### ISSUE THREAD

**Issue by HalvorRaknes** [ytdl-org/youtube-dl#26969]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.09.20**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

This is a reposting of ISSUE [#26880](https://github.com/ytdl-org/youtube-dl/issues/26880) which was closed without the issue I raised being substantially addressed.

Before I repost I emphasize that the issue cannot be duplicated with the data I provide below as it issue only exists for at most several hours. That does NOT mean this isn't an issue. Also, I ask another related question which is independent but relevant to the described issue:

Sometimes YouTube videos which have been recently posted won't download. the '-F' output typically reads like this:

```
$ youtube-dl -F https://www.youtube.com/watch?v=sL8ExGs6hww 
[youtube] sL8ExGs6hww: Downloading webpage
[youtube] sL8ExGs6hww: Downloading MPD manifest
[info] Available formats for sL8ExGs6hww:
format code  extension  resolution note
139          m4a        audio only DASH audio   64k , m4a_dash container, mp4a.40.5@ 48k (24000Hz)
140          m4a        audio only DASH audio  144k , m4a_dash container, mp4a.40.2@128k (48000Hz)
160          mp4        256x144    DASH video  124k , mp4_dash container, avc1.42c00b, 30fps, video only
133          mp4        426x240    DASH video  258k , mp4_dash container, avc1.4d4015, 30fps, video only
134          mp4        640x360    DASH video  646k , mp4_dash container, avc1.4d401e, 30fps, video only
135          mp4        854x480    DASH video 1171k , mp4_dash container, avc1.4d401f, 30fps, video only
136          mp4        1280x720   DASH video 2326k , mp4_dash container, avc1.4d401f, 30fps, video only
386          mp4        unknown    tiny 
387          mp4        unknown    tiny  (best)
```
I have attempted applying the '--merge-output-format FORMAT' option but the result only becomes a corrupted file.

Obviously, this issue can be resolved by simply waiting a few hours. YouTube will then assemble the usual downloadable files. My problem, however, is that I download media files and then watch them when I am offline, which I usually am.

This issue touches on the question of how can video version with higher resolution be downloaded, i.e. 1080p and higher? Obviously, when I am able to watch a video when I'm watching it directly off of the YouTube page, there should be some way of capturing the stream, any stream. If youtube-dl cannot always do that, can someone suggest to me how that can be done using some other app or perhaps the 'wget' command?

**Comment by dstftw** [comment]
You must provide complete verbose log clearly demonstrating the problem.
