### ISSUE TITLE
Error downloading video files from servustv.com

### ISSUE THREAD

**Issue by johunb** [ytdl-org/youtube-dl#26967]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Program Files (x86)\youtube-dl>youtube-dl -v https://www.servustv.com/videos/aa-24h32f4jd1w12/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.servustv.com/videos/aa-24h32f4jd1w12/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.3.1
[debug] Proxy map: {}
[Servus] AA-24H32F4JD1W12: Downloading webpage
[Servus] AA-24H32F4JD1W12: Downloading m3u8 information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\servus.py", line 61, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 1359, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE
Downloading video files from servustv.com is not possible with latest version. E.g.: https://www.servustv.com/videos/aa-24h32f4jd1w12/

**Comment by mittern-8** [comment]
me too!
[verbose.log](https://github.com/ytdl-org/youtube-dl/files/5422839/verbose.log)

Roll back to older versions of youtube-dl doesn't help

Issues with e.g.
https://www.servustv.com/videos/aa-1yqgz6v452112/
https://www.servustv.com/videos/1393234154884-612144188/
https://www.servustv.com/videos/aa-24dsn9qvn1w12/
https://www.servustv.com/videos/aa-251rfpu411w12/
https://www.servustv.com/videos/aa-21tptw7nh2112/
https://www.servustv.com/videos/aa-22hj97qsn2112/

Other files work flawless, e.g.
https://www.servustv.com/videos/aa-1v5tzf3nh1w12/
https://www.servustv.com/videos/aa-1qg79tj9n2112/
https://www.servustv.com/videos/aa-24n7yac352112/

**Comment by johunb** [comment]
Workaround: Install Video DownloadHelper for your Browser, grab path to the right m3u8-file and use youtube-dl to download mp4 ... works fine!

**Comment by mittern-8** [comment]
****

> [...] grab path to the right m3u8-file and use youtube-dl to download mp4 ... works fine!
> It seems youtube-dl doesn't find the right m3u8-file.

But how to find the path to the right m3u8 than? That's one of the main reasons why I use youtube-dl: because it _usually_ can extract the right path to the m3u8-file from the given website using the cmd-line-arg "-g"- even though (for whatever reason) the player-interface is missing on the ServusTV-site.

**Comment by johunb** [comment]
Yea, that's the question? If you look at the source code of the ServusTV-site the video is embedded you can only find the path to the fake m3u8-file ...
But JDowloader 2 or Video DownloadHelper does the trick ...
