### ISSUE TITLE
Twitch clips download range

### ISSUE THREAD

**Issue by patrys666** [ytdl-org/youtube-dl#26976]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I try to download best clips from twitch channel with following command:
`youtube-dl https://www.twitch.tv/username/clips?filter=clips&range=all`
Downloading starting but only for clips that are 7 days old.
[download] Downloading playlist: username- Clips Top 7D

How to download best without 7 days range?

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
