### ISSUE TITLE
Get.iPlayer.Automator.v1.19.2.b20201018001 doesn't download

### ISSUE THREAD

**Issue by ManolisGledsodakis** [ytdl-org/youtube-dl#26971]
Apologies for the vague title. As you might guess, I'm not a coder, just a user. (Yes, I can hear you groan, but I'm doing my best.)

I'm using Gia v1.18.2 on a mid 2012 MacBook Pro (El Capitan) with a UK VPN (in Greece) and it downloads programmes OK. I'm fairly sure that the VPN is not the issue.
I installed 1.19.2 on an early 2011 MacBook Pro (El Capitan), using exactly the same VPN and it produces "unknown error".

I'll carry on using the earlier version but I'm including the log (below) in case it's helpful to you. Although the log states "downloaded", nothing was downloaded. It simply flipped to Timer countdown mode.

I chose a random BBC programme and a random ITV programme to test. (I wouldn't want you to think that I actually watch this sh;t. I'm trying to sort this out for my beloved wife, to minimise the nagging.)

Here's the log. (I have no idea what any of it means. I'm 69, retired engineer - give me a break.):
__

Get iPlayer Automator 1.19.2 Initialized.
GetITVShows: ITV Cache Update Starting 
<AppController: 0x7ff7c968a120>: Updating Programme Index Feeds...

/Users/fredflin/Downloads/Get iPlayer Automator.app/Contents/Resources/get_iplayer/perl/bin/get_iplayer
-e14400
--type=tv,radio
--refresh
--nopurge
--profile-dir=/Users/fredflin/Library/Application Support/Get iPlayer Automator
.*
INFO: Indexing tv programmes (concurrent)
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/carry-on-dont-lose-your-head/CFD0120a0001, NSErrorFailingURLKey=https://www.itv.com/hub/carry-on-dont-lose-your-head/CFD0120a0001, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/carry-on-dont-lose-your-head/CFD0120
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/carry-on-doctor/CFD0110a0001, NSErrorFailingURLKey=https://www.itv.com/hub/carry-on-doctor/CFD0110a0001, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/carry-on-doctor/CFD0110
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-good-karma-hospital/2a4663, NSErrorFailingURLKey=https://www.itv.com/hub/the-good-karma-hospital/2a4663, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-good-karma-hospital/2a4663
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-hive/1a9014, NSErrorFailingURLKey=https://www.itv.com/hub/the-hive/1a9014, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-hive/1a9014
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-jonathan-ross-show/2a1166, NSErrorFailingURLKey=https://www.itv.com/hub/the-jonathan-ross-show/2a1166, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-jonathan-ross-show/2a1166
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-life-times-of-captain-sir-tom/10a0447, NSErrorFailingURLKey=https://www.itv.com/hub/the-life-times-of-captain-sir-tom/10a0447, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-life-times-of-captain-sir-tom/10a0447
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-martin-lewis-money-show-live/2a1827, NSErrorFailingURLKey=https://www.itv.com/hub/the-martin-lewis-money-show-live/2a1827, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-martin-lewis-money-show-live/2a1827
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-masked-singer-us/10a0402, NSErrorFailingURLKey=https://www.itv.com/hub/the-masked-singer-us/10a0402, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-masked-singer-us/10a0402
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-metro-a-rail-life-story/2a6320, NSErrorFailingURLKey=https://www.itv.com/hub/the-metro-a-rail-life-story/2a6320, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-metro-a-rail-life-story/2a6320
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-million-pound-cube/10a0580, NSErrorFailingURLKey=https://www.itv.com/hub/the-million-pound-cube/10a0580, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-million-pound-cube/10a0580
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-mountain/2a5770, NSErrorFailingURLKey=https://www.itv.com/hub/the-mountain/2a5770, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-mountain/2a5770
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-murder-of-stephen-lawrence/1a2788, NSErrorFailingURLKey=https://www.itv.com/hub/the-murder-of-stephen-lawrence/1a2788, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-murder-of-stephen-lawrence/1a2788
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-only-way-is-essex/1a9310, NSErrorFailingURLKey=https://www.itv.com/hub/the-only-way-is-essex/1a9310, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-only-way-is-essex/1a9310
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-professionals/L0845, NSErrorFailingURLKey=https://www.itv.com/hub/the-professionals/L0845, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-professionals/L0845
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-protectors/PROTECTORS, NSErrorFailingURLKey=https://www.itv.com/hub/the-protectors/PROTECTORS, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-protectors/PROTECTORS
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-queens-green-planet/2a5383, NSErrorFailingURLKey=https://www.itv.com/hub/the-queens-green-planet/2a5383, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-queens-green-planet/2a5383
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-real-housewives-of-cheshire/2a3398, NSErrorFailingURLKey=https://www.itv.com/hub/the-real-housewives-of-cheshire/2a3398, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-real-housewives-of-cheshire/2a3398
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-rubbish-world-of-dave-spud/2a6321, NSErrorFailingURLKey=https://www.itv.com/hub/the-rubbish-world-of-dave-spud/2a6321, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-rubbish-world-of-dave-spud/2a6321
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-saint/SAINT, NSErrorFailingURLKey=https://www.itv.com/hub/the-saint/SAINT, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-saint/SAINT
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-savoy/2a7996, NSErrorFailingURLKey=https://www.itv.com/hub/the-savoy/2a7996, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-savoy/2a7996
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-singapore-grip/2a7035, NSErrorFailingURLKey=https://www.itv.com/hub/the-singapore-grip/2a7035, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-singapore-grip/2a7035
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-stand-up-sketch-show/2a5923, NSErrorFailingURLKey=https://www.itv.com/hub/the-stand-up-sketch-show/2a5923, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-stand-up-sketch-show/2a5923
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-sweeney/28208, NSErrorFailingURLKey=https://www.itv.com/hub/the-sweeney/28208, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-sweeney/28208
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-towie-years/10a0495, NSErrorFailingURLKey=https://www.itv.com/hub/the-towie-years/10a0495, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-towie-years/10a0495
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-tom-jerry-show/2a3591, NSErrorFailingURLKey=https://www.itv.com/hub/the-tom-jerry-show/2a3591, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-tom-jerry-show/2a3591
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-trouble-with-maggie-cole/2a5883, NSErrorFailingURLKey=https://www.itv.com/hub/the-trouble-with-maggie-cole/2a5883, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-trouble-with-maggie-cole/2a5883
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-ty-and-ky-show/2a4198, NSErrorFailingURLKey=https://www.itv.com/hub/the-ty-and-ky-show/2a4198, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-ty-and-ky-show/2a4198
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-village/2a6185, NSErrorFailingURLKey=https://www.itv.com/hub/the-village/2a6185, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-village/2a6185
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/the-voice/2a4394, NSErrorFailingURLKey=https://www.itv.com/hub/the-voice/2a4394, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/the-voice/2a4394
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/this-morning/1a1960, NSErrorFailingURLKey=https://www.itv.com/hub/this-morning/1a1960, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/this-morning/1a1960
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/thunderbirds-are-go/2a2131, NSErrorFailingURLKey=https://www.itv.com/hub/thunderbirds-are-go/2a2131, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/thunderbirds-are-go/2a2131
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/timewasters/2a4370, NSErrorFailingURLKey=https://www.itv.com/hub/timewasters/2a4370, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/timewasters/2a4370
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/tina-bobby/2a3958, NSErrorFailingURLKey=https://www.itv.com/hub/tina-bobby/2a3958, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/tina-bobby/2a3958
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/tipping-point/2a1875, NSErrorFailingURLKey=https://www.itv.com/hub/tipping-point/2a1875, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/tipping-point/2a1875
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/tipping-point-lucky-stars/2a2533, NSErrorFailingURLKey=https://www.itv.com/hub/tipping-point-lucky-stars/2a2533, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/tipping-point-lucky-stars/2a2533
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/tonight/1a2803, NSErrorFailingURLKey=https://www.itv.com/hub/tonight/1a2803, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/tonight/1a2803
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/totally-bonkers-guinness-world-records/2a1670, NSErrorFailingURLKey=https://www.itv.com/hub/totally-bonkers-guinness-world-records/2a1670, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/totally-bonkers-guinness-world-records/2a1670
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/totally-unbelievable/2a6105, NSErrorFailingURLKey=https://www.itv.com/hub/totally-unbelievable/2a6105, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/totally-unbelievable/2a6105
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/transformers-robots-in-disguise/2a4318, NSErrorFailingURLKey=https://www.itv.com/hub/transformers-robots-in-disguise/2a4318, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/transformers-robots-in-disguise/2a4318
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/uefa-nations-league-highlights/2a5677, NSErrorFailingURLKey=https://www.itv.com/hub/uefa-nations-league-highlights/2a5677, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/uefa-nations-league-highlights/2a5677
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/unboxed/7a0261, NSErrorFailingURLKey=https://www.itv.com/hub/unboxed/7a0261, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/unboxed/7a0261
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/unforgettable-world-cups/10a0093, NSErrorFailingURLKey=https://www.itv.com/hub/unforgettable-world-cups/10a0093, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/unforgettable-world-cups/10a0093
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/unsaid-stories/10a0562, NSErrorFailingURLKey=https://www.itv.com/hub/unsaid-stories/10a0562, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/unsaid-stories/10a0562
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/van-der-valk/2a7219, NSErrorFailingURLKey=https://www.itv.com/hub/van-der-valk/2a7219, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/van-der-valk/2a7219
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/vanderpump-rules/2a3474, NSErrorFailingURLKey=https://www.itv.com/hub/vanderpump-rules/2a3474, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/vanderpump-rules/2a3474
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/vera/1a7314, NSErrorFailingURLKey=https://www.itv.com/hub/vera/1a7314, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/vera/1a7314
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/whats-the-facts/2a4794, NSErrorFailingURLKey=https://www.itv.com/hub/whats-the-facts/2a4794, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/whats-the-facts/2a4794
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/white-house-farm/2a5719, NSErrorFailingURLKey=https://www.itv.com/hub/white-house-farm/2a5719, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/white-house-farm/2a5719
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/wishfart/2a5335, NSErrorFailingURLKey=https://www.itv.com/hub/wishfart/2a5335, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/wishfart/2a5335
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/wonders-of-the-coast-path/2a6969, NSErrorFailingURLKey=https://www.itv.com/hub/wonders-of-the-coast-path/2a6969, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/wonders-of-the-coast-path/2a6969
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/world-superbike-highlights/2a4431, NSErrorFailingURLKey=https://www.itv.com/hub/world-superbike-highlights/2a4431, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/world-superbike-highlights/2a4431
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/youve-been-framed/1a1658, NSErrorFailingURLKey=https://www.itv.com/hub/youve-been-framed/1a1658, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/youve-been-framed/1a1658
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/ziggy-and-the-zoo-tram/2a7543, NSErrorFailingURLKey=https://www.itv.com/hub/ziggy-and-the-zoo-tram/2a7543, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/ziggy-and-the-zoo-tram/2a7543
GetITVShows (Info): Episodes: 1806 Today Programmes: 287 
GetITVShows: Update Finished
INFO: Added 8627 tv programmes to cache
INFO: Indexing radio programmes (concurrent)
INFO: Added 15374 radio programmes to cache
<AppController: 0x7ff7c968a120>: Index Updated.
/Users/fredflin/Downloads/Get iPlayer Automator.app/Contents/Resources/get_iplayer/perl/bin/get_iplayer
--nocopyright
-e60480000000000000
--type=tv,itv,radio
--listformat=SearchResult|<pid>|<available>|<type>|<name>|<episode>|<channel>|<seriesnum>|<episodenum>|<desc>|<thumbnail>|<web>|<available>
--long
--nopurge
--search
 
--profile-dir=/Users/fredflin/Library/Application Support/Get iPlayer Automator
--hide

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads

Downloading Show 1/2:

BBC Download (ID=m000c799): Downloading Villages by the Sea - Clovelly

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads

Downloading Show 1/2:

BBC Download (ID=m000c799): Downloading Villages by the Sea - Clovelly

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads

Downloading Show 1/2:

ITV Download (ID=2a7332a0035): Downloading Craig of the Creek - Wed Oct 21
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 200
INFO: Metadata processed.
DEBUG: youtube-dl args:["https://www.itv.com/hub/craig-of-the-creek/2a7332a0035", "-f", "mp4/best", "-o", "/Volumes/3TB TV copy/GetiPlayer/Craig of the Creek/Craig of the Creek.s01e35.The Shortcut.%(ext)s", "--verbose"]
DEBUG: youtube-dl environment: ["PATH": "/Users/fredflin/Downloads/Get iPlayer Automator.app/Contents/MacOS:/Users/fredflin/Downloads/Get iPlayer Automator.app/Contents/Resources/get_iplayer/utils/bin:/usr/bin", "PYTHONPATH": "/Users/fredflin/Downloads/Get iPlayer Automator.app/Contents/Resources"]
[debug] System config: []

[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.itv.com/hub/craig-of-the-creek/2a7332a0035', u'-f', u'mp4/best', u'-o', u'/Volumes/3TB TV copy/GetiPlayer/Craig of the Creek/Craig of the Creek.s01e35.The Shortcut.%(ext)s', u'--verbose']

[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII

[debug] youtube-dl version 2020.07.28

[debug] Python version 2.7.10 (CPython) - Darwin-15.6.0-x86_64-i386-64bit

[debug] exe versions: ffmpeg 4.3, rtmpdump 2.4-102-ga3a600d-get_iplayer

[debug] Proxy map: {}

[debug] Using fake IP 25.0.179.61 (GB) as X-Forwarded-For.

[ITV] 2a7332a0035: Downloading webpage

[ITV] 2a7332a0035: Downloading XML

WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out

[ITV] 2a7332a0035: Downloading JSON metadata

[ITV] 2a7332a0035: Downloading m3u8 information

WARNING: Failed to download m3u8 information: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>

ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Traceback (most recent call last):
  File "/Users/fredflin/Downloads/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/Users/fredflin/Downloads/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Users/fredflin/Downloads/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/extractor/itv.py", line 260, in _real_extract
    self._sort_formats(formats)
  File "/Users/fredflin/Downloads/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

ITV Download (ID=2a7332a0035): youtube-dl finished downloading

Downloading Show 2/2:

BBC Download (ID=m000c799): Downloading Villages by the Sea - Clovelly
AppController: Downloads Finished

**Comment by dstftw** [comment]
This is youtube-dl issue tracker. Address this to support of software you are using.

**Comment by ManolisGledsodakis** [comment]
Sorry, but I don't understand "This is youtube-dl issue tracker. " Anyway, I don't ever use YouTube. Is the solution explained somewhere in REALLY simple steps? (For a beginner, this website is a nightmare to navigate. I have no idea what I'm looking for.)
"Address this to support of software you are using." Address it to whom?
