### ISSUE TITLE
Retrieve title while downloading with progress report via CLI

### ISSUE THREAD

**Issue by 0xpr03** [ytdl-org/youtube-dl#26980]
## Checklist

- [x] I'm reporting a site feature request
- [X] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've searched the bugtracker for similar site feature requests including closed ones
Others got closed without much of a glimpse of the problem.

## Description

It's currently not possible to my knowledge to do the following in one go:
- download a video
- get realtime progress output
- get title information
all in one run without having to run ytdl multiple times, creating additional roundtrips to the source server.

I can run ytdl multiple times for this to run --print-json and then run it normally. But it's a waste of possible youtube DoS blocks and can take additional multiple seconds to complete.

**Comment by dstftw** [comment]
Embed as python, add progress hooks, return data in whatever form you need.
