### ISSUE TITLE
Cannot download from banned.video

### ISSUE THREAD

**Issue by ThorstenWetzig** [ytdl-org/youtube-dl#26989]
Hello,

I tried to download: ydl-mp4 https://banned.video/watch?id=5f4d56c5838dfb0597dd8187
And I get:

[generic] watch?id=5f4d56c5838dfb0597dd8187: Requesting header
WARNING: Could not send HEAD request to https://banned.video/watch?id=5f4d56c5838dfb0597dd8187: HTTP Error 403: Forbidden
[generic] watch?id=5f4d56c5838dfb0597dd8187: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**youtube-dl -U**
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: youtube-dl's self-update mechanism is disabled on Debian.
Please update youtube-dl using apt(8).
See https://packages.debian.org/sid/youtube-dl for the latest packaged version.

**sudo apt install youtube-dl**
[sudo] password for thorsten: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
youtube-dl is already the newest version (2020.03.24-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Thank you and lots of LOVE!

**Comment by vpereira** [comment]
> . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

You are trying a down-streamed version, you should get the last version from upstream and test it: https://github.com/ytdl-org/youtube-dl/releases/tag/2020.09.20

**Comment by caioalonso** [comment]
Using the current `master`:
```
youtube-dl on  master via 🐍 v3.8.6 
$ git log -1
commit 1737ea69b978f7ebe0f52c526d3dda5ba5c196b6 (HEAD -> master, origin/master, origin/HEAD)
Author: Remita Amine <remitamine@gmail.com>
Date:   Mon Nov 16 15:55:07 2020 +0100

    [cnbc] fix extraction

youtube-dl on  master via 🐍 v3.8.6 
$ bin/youtube-dl --verbose "https://banned.video/watch?id=5f4d56c5838dfb0597dd8187"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://banned.video/watch?id=5f4d56c5838dfb0597dd8187']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.01.1
[debug] Python version 3.8.6 (CPython) - Linux-5.9.8-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] watch?id=5f4d56c5838dfb0597dd8187: Requesting header
WARNING: Could not send HEAD request to https://banned.video/watch?id=5f4d56c5838dfb0597dd8187: HTTP Error 403: Forbidden
[generic] watch?id=5f4d56c5838dfb0597dd8187: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by asgmeonerandom** [comment]
Looks like the website is using Cloudflare which is a security and content delivery product.
