### ISSUE TITLE
Lifetime Movie Club [aenetworks]

### ISSUE THREAD

**Issue by Saberleo456** [ytdl-org/youtube-dl#26985]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.09.20**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
G:\YoutubeDL>youtube-dl -v https://watch.lifetimemovieclub.com/movies/swim-at-her-own-risk/full-movie
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://watch.lifetimemovieclub.com/movies/swim-at-her-own-risk/full-movie']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-05-28-c0f01ea, ffprobe git-2020-05-28-c0f01ea
[debug] Proxy map: {}
[generic] full-movie: Requesting header
WARNING: Falling back on generic information extractor.
[generic] full-movie: Downloading webpage
[generic] full-movie: Extracting information
ERROR: Unsupported URL: https://watch.lifetimemovieclub.com/movies/swim-at-her-own-risk/full-movie
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://watch.lifetimemovieclub.com/movies/swim-at-her-own-risk/full-movie

## Description

WRITE DESCRIPTION HERE
Lifetime Movie Club seems to have moved their subdomain to watch.lifetimemovieclub.com and previously it was supported with the www domain and using Developer tools to use the .m3u8 workaround returns an HTTP 403 forbidden error. Credentials were not needed originally, using the Youtube-dl commands to enter credentials did not work either. #26795 references this problem, but the play subdomain is not what Lifetime Movie Club is using.

**Comment by october262** [comment]
try signing in and then try using the cookies file option.

**Comment by StevenDTX** [comment]
> 
> 
> try signing in and then try using the cookies file option.

The aenetworks extractor hasn't worked in ages, even with cookies or ap-mso.

**Comment by Saberleo456** [comment]
> > try signing in and then try using the cookies file option.
> 
> The aenetworks extractor hasn't worked in ages, even with cookies or ap-mso.

I had been using the aenetworks extractor for months, it broke when Lifetime Movie Club moved to the subdomain watch.lifetimemovieclub.com. My latest solution is to sniff out the m3u8 file using the Network filter and using the --referer and --user-agent flags on Youtube-dl.

referer is the url in the address bar in this case the movie player page
User Agent can be found by Google

Example:

youtube-dl --referer "https://watch.lifetimemovieclub.com/movie/...." --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.195 Safari/537.36" [URL OF THE MOVIE M3U8 GOES HERE]
