### ISSUE TITLE
Downloading Playlist: 'entries' is empty

### ISSUE THREAD

**Issue by yunolawliet** [ytdl-org/youtube-dl#27001]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.12**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
{'_type': 'playlist', 'entries': [], 'id': 'PL_VXiEHRfGbzK3yejA8PaBtL2Bb4dtv2K', 'uploader': None, 'uploader_id': None, 'uploader_url': None, 'extractor': 'youtube:playlist', 'webpage_url': 'https://www.youtube.com/playlist?list=PL_VXiEHRfGbzK3yejA8PaBtL2Bb4dtv2K', 'webpage_url_basename': 'playlist', 'extractor_key': 'YoutubePlaylist'}

```

## Description

I'm trying to fetch info from a playlist and the 'entries' generator is empty.
The code has been working well for over a year, this is the first time I encountered this issue.

```
import youtube_dl

ytdl_params = {
    'quiet': True,
    'cookies': True,
    'extract_flat': True,
}

ydl = youtube_dl.YoutubeDL(ytdl_params)
with ydl:
    r = ydl.extract_info("https://www.youtube.com/playlist?list=PL_VXiEHRfGbzK3yejA8PaBtL2Bb4dtv2K", download=False)  # don't download, much faster

print(r)

```

**Comment by inmbolmie** [comment]
I think I have the same issue, suspect it stopped working after November 9.

**Comment by remitamine** [comment]
Most likely you're using an outdated version.
