### ISSUE TITLE
Gravar live com tempo

### ISSUE THREAD

**Issue by ataubruno** [ytdl-org/youtube-dl#27024]
Queria gravar uma live com cortes automaticos, a cada 10 minutos ou 5 minutos, e a gravação continuar de forma automatica! No ffmpeg, utilizo o comando "-f segment -segment_time 600", mas não YOUTUBE-DL  não quais seriam.

**Comment by Fusseldieb** [comment]
Please ask in english, so people can help you!

**Comment by remitamine** [comment]
use `ffmpeg` external downloader.
```
--external-downloader COMMAND    Use the specified external downloader.
                                 Currently supports
                                 aria2c,avconv,axel,curl,ffmpeg,httpie,wget
--external-downloader-args ARGS  Give these arguments to the external
                                 downloader
```

**Comment by ataubruno** [comment]
> Por favor, pergunte em inglês para que as pessoas possam te ajudar!

I wanted to record a live with automatic cuts, every 10 minutes or 5 minutes, and the recording automatically! In ffmpeg, I use the command "-f segment -segment_time 600", but not YOUTUBE-DL which ones would be.
