### ISSUE TITLE
what about change repo name?

### ISSUE THREAD

**Issue by tinybug** [ytdl-org/youtube-dl#27027]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

What about change repo name? Get rid of youtube from name, like you-dl?

**Comment by alx-xlx** [comment]
yep, we don't want youtube or google coming after the trademark. I think **ytdl** is ok

**Comment by pcislocked** [comment]
youtube doesn't even deserve being in the name of that tool

**Comment by Croydon** [comment]
If the tool supports more than YouTube, then it probably shouldn't be in the name indeed

**Comment by milasudril** [comment]
Well, you cannot change the name of the script now, since this is an API. People might use it in their scripts...

**Comment by fffelix-jan** [comment]
I guess you could change the documentation to remove references to YouTube (or other companies).

**Comment by theAkito** [comment]
> Well, you cannot change the name of the script now, since this is an API. People might use it in their scripts...

I think it's more important to care about the project's health, than some people's scripts (including my own).
