### ISSUE TITLE
SSL cert expired

### ISSUE THREAD

**Issue by barakbd** [ytdl-org/youtube-dl#27031]
## Checklist

- [X ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2020.11.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
```

## Description

SSL cert needs updating

**Comment by kennell** [comment]
This is not the verbose log. Run `youtube-dl` using the `-v` flag, also provide example URL.
