### ISSUE TITLE
Playlist extractor error, or user error?

### ISSUE THREAD

**Issue by Xechran** [ytdl-org/youtube-dl#27030]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

I am new to YT-dl and have run into an issue downloading this playlist. Individual items in the playlist can be downloaded separately. The links are active and working in my browser. Am using --download-archive, have tried --yes-playlist and --playlist-start 1, -i, and using only the RD6Vb_uA0Xvn8 portion of the address. All are coming back with errors at the same lines in extractor code. Since no one else is reporting an issue at these lines I presume I am passing the wrong cmd options. 

```
b:\xxx\Music>youtube-dl.exe --download-archive archive.txt --verbose "https://www.youtube.com/watch?v=6Vb_uA0Xvn8&list=RD6Vb_uA0Xvn8"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--download-archive', 'archive.txt', '--verbose', 'https://www.youtube.com/watch?v=6Vb_uA0Xvn8&list=RD6Vb_uA0Xvn8']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2020.11.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] RD6Vb_uA0Xvn8: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('contents',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\youtube.py", line 2843, in _real_extract
KeyError: 'contents'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\youtube.py", line 2843, in _real_extract
KeyError: 'contents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\common.py", line 545, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('contents',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
````

**Comment by october262** [comment]
play this video - https://www.youtube.com/watch?v=6Vb_uA0Xvn8&list=RD6Vb_uA0Xvn8
click on the badge next to the videos name, click playlist - view full playlist, copy the link
and paste into a terminal

**Comment by tinybug** [comment]
this is a mix playlist, https://github.com/blackjack4494/yt-dlc can extract all the videos in playlist

**Comment by Xechran** [comment]
YT-dlc worked for this with the given cmd line options. Thank you. YT-dl does work on other playlists, just not the Mix list. +1 to merge.

@october262 I don't see a "badge" next to the name of a video?

**Comment by october262** [comment]
> 
> 
> YT-dlc worked for this with the given cmd line options. Thank you. YT-dl does work on other playlists, just not the Mix list. +1 to merge.
> 
> @october262 I don't see a "badge" next to the name of a video?

it's the little picture with a pair of headphones & controller inside of it
click on it to get to the playlist page.

**Comment by Xechran** [comment]
AH I see. You mean go into the uploader's profile to get the playlist. This mix is auto generated by youtube, not by the creator/uploader, so there is no playlist under the user profiles. Thanks though.
