### ISSUE TITLE
[QUESTION] Download file streaming for programmatic use by another application immediately

### ISSUE THREAD

**Issue by Rubydesic** [ytdl-org/youtube-dl#27043]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Say I have a program that wants to play audio from YouTube videos. I do not want to make users wait until the whole video is downloaded in order for my application to begin playing.

Ideally I'd like something like `youtube-dl https://youtube.com/watch?v=whatever --local-http-server`

And it would be like

`Downloading... Your file is available at http://localhost:3000/whatever.mp4`, so my application could get to the file immediately rather than waiting for the whole download to complete. Is there any way to currently do something like this or otherwise solve my problem?

**Comment by remitamine** [comment]
Extract the media URL(`-g` or `--get-url` option) and use it directly, you might need to also use the same cookies, headers as youtube-dl.
