### ISSUE TITLE
Nothing is downloading. Python

### ISSUE THREAD

**Issue by maxiujin** [ytdl-org/youtube-dl#27049]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hi everyone, I am trying to figure out why nothing is downloading. Is there a new way to use  ydl.download?

def yt_download(keyterm: str, lang: str):
    print("This is what I am searching", lang, keyterm)
    # user_input_terms = [user_input_terms for t in keyterm for user_input_terms in t] #for array
    user_input_terms = keyterm
    print("variable type", type(user_input_terms), user_input_terms)
    ydl_opts = {
        "download_archive": "./data/en-downloaded.txt",
        "restrictfilenames": True,
        "nooverwrites": True,
        "socket_timeout": 1,
        "youtube_include_dash_manifest": True,
        "writeinfojson": True,
        "writesubtitles": True,
        "format": "bestaudio/best",
        # "allsubtitles": True,
        "subtitlesformat": "ttml",
        "progress_hooks": [my_hook],
        "subtitlelangs": lang,
        # "writeautosub": True,
        "keepvideo:": True,
        # "--write-srt": True,
        "postprocessors": [{"key": "FFmpegExtractAudio", "preferredcodec": "wav", "preferredquality": "192", }],
        "prefer_ffmpeg": True,
        # "format": "bestvideo[ext=mp4]+bestaudio",
        "outtmpl": "data/raw_files/%(title)s.%(ext)s",
    }
    # for x in range(0, 100):  # Specify how many videos do you want to download/crawl
    logger.msg(user_input_terms)
    try:
        with youtube_dl.YoutubeDL(ydl_opts) as ydl:
            term = user_input_terms
            term = ''.join(term)
         

            ydl.download([f"https://www.youtube.com/results?search_query={term}"])

    except download_error:
        logger.msg("Youtube outputs a mp4 error.")

**Comment by dstftw** [comment]
Post complete verbose log.

**Comment by maxiujin** [comment]
[youtube:search_url] playlist china: Downloading 0 videos
[download] Finished downloading playlist: china
