### ISSUE TITLE
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug

### ISSUE THREAD

**Issue by slschneider252** [ytdl-org/youtube-dl#27055]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2020.11.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log - NOTE 2 Logs with identical errors from FACEBOOK site

2nd FAILURE

D:\bin>youtube-dl -U
youtube-dl is up-to-date (2020.11.17)

D:\bin>youtube-dl --verbose https://www.facebook.com/michael.lovasco/videos/4162518427096876
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.facebook.com/michael.lovasco/videos/4162518427096876']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.11.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 4162518427096876: Downloading webpage
[facebook] 4162518427096876: Downloading webpage
[facebook] 4162518427096876: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\facebook.py", line 484, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\facebook.py", line 380, in _extract_from_url
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
PASTE VERBOSE LOG HERE
```

## Description

Attempted to download 2 different  videos using a FACEBOOK URL which both failed due to "Cannot parse data".  Requested that I post the attached information.

WRITE DESCRIPTION HERE
 Failed to download video from FACEBOOK site.

**Comment by slschneider252** [comment]
1st FAILURE was dropped, so adding it here:

D:\bin>youtube-dl --verbose https://www.facebook.com/thomas.w.robinson.3/videos/10224632130171629
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.facebook.com/thomas.w.robinson.3/videos/10224632130171629']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.11.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 10224632130171629: Downloading webpage
[facebook] 10224632130171629: Downloading webpage
[facebook] 10224632130171629: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\facebook.py", line 484, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\facebook.py", line 380, in _extract_from_url
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by alecgirman** [comment]
Facebook requires you to be logged in to view the video.  Youtube-DL does not use saved browser credentials.

**Comment by remitamine** [comment]
try with `--username` and `--password` or `--cookies` options and report back.

**Comment by october262** [comment]
> try with `--username` and `--password` or `--cookies` options and report back.

use caution with using --cookies with facebook because i just had to unlock
my account due to suspicious activity

**Comment by ReeganExE** [comment]
> > try with `--username` and `--password` or `--cookies` options and report back.
> 
> use caution with using --cookies with facebook because i just had to unlock
> my account due to suspicious activity

I can confirm this. My account got locked everytime I tried youtube-dl to get fb video recently.
