### ISSUE TITLE
Suggestion: Using a decentralized repository

### ISSUE THREAD

**Issue by OfficeGeek888** [ytdl-org/youtube-dl#27056]
It was a pretty bad ordeal that the RIAA came after this repo. If I might suggest, I would recommend using Zeronet's site Git Center: http://127.0.0.1:43110/1GitLiXB6t5r8vuU2zC6a8GYj9ME6HMQ4t
(Zeronet is needed to access the link)

Because it's decentralized, it's uncensorable and immune to takedowns. I hope you at least consider this.

**Comment by rautamiekka** [comment]
Are you **sure** you got the link right ?

**Comment by sakibarifin** [comment]
The returns a dead page.

![image](https://user-images.githubusercontent.com/33556544/99456312-29d18f00-2964-11eb-8589-e8a714759a85.png)

**Comment by OfficeGeek888** [comment]
> The link returns a dead page.
> 
> ![image](https://user-images.githubusercontent.com/33556544/99456312-29d18f00-2964-11eb-8589-e8a714759a85.png)

(Zeronet is needed to access the link)

**Comment by OfficeGeek888** [comment]
> Are you **sure** you got the link right ?

(Zeronet is needed to access the link)

**Comment by rautamiekka** [comment]
> > Are you **sure** you got the link right ?
> 
> (Zeronet is needed to access the link)

Ok, that makes sense. Cuz that's a localhost IP.

**Comment by asaphe** [comment]
Git is by definition decentralized. they can take down this public repo but they can't actually do anything to all the other repos everyone who cloned this repo has on their computer.

**Comment by rautamiekka** [comment]
> Git is by definition decentralized.

Maybe, but they're usually manually synced (a scheduled sync wouldn't be too much better), and they don't sync up with the other mirrors unless all of them are specifically pointed to each other, which'll be a stupidly hard task.

**Comment by underhandedness** [comment]
A better mechanism would be to school the victim of the **Digitally Malevolent Censorship Act** to initiate a challenge [within the process] to every claim allowing the content to remain up while the wheels churn against the burden of proof.
