### ISSUE TITLE
[Broken] Facebook extractor broken: wrong title being extracted #197

### ISSUE THREAD

**Issue by chrisr11** [ytdl-org/youtube-dl#27054]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-J', u'https://www.facebook.com/AFV/videos/3868462086560598']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.17
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-99-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
```

## Description

Hi,

When extracting the JSON info of a Facebook video, the title that it gets is "Log into Facebook to start sharing..." rather than the video's actual title. The command I used is: youtube-dl -J https://www.facebook.com/AFV/videos/3868462086560598

Sometimes it gets the correct title but most of the time it gets the wrong one. Please look into this issue.

**Comment by october262** [comment]
did you try clicking on the 3 dots ...  and select copy link and then feed it to youtube-dl

**Comment by chrisr11** [comment]
Yes, the example link I've given was copied using the 3 dots menu.

**Comment by remitamine** [comment]
```
youtube-dl --get-title https://www.facebook.com/AFV/videos/3868462086560598
These fails are EPIC 😂😂
```

**Comment by chrisr11** [comment]
Here's the response that I get:
`youtube-dl --get-title https://www.facebook.com/AFV/videos/3868462086560598
Log into Facebook to start sharing and connecting with your friends, family, ...`
