### ISSUE TITLE
--ignore-errors not working for youtube:tab playlists

### ISSUE THREAD

**Issue by ergosteur** [ytdl-org/youtube-dl#27064]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.18**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
/usr/local/bin/youtube-dl --ignore-errors -v -c -w -f 'bestvideo[height >=? 1
920]+bestaudio' --merge-output-format mkv https://www.youtube.com/playlist?list=UUE6acMV3m35znLcf0JGNn7Q
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-errors', '-v', '-c', '-w', '-f', 'bestvideo[height >=? 1920]+bestaudio', '--merge-output-format', 'mkv', 'https://www.youtube.com/playlist?list=UUE6acMV3m35znLcf0JGNn7Q']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.18
[debug] Python version 3.6.9 (CPython) - Linux-5.4.65-1-pve-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[youtube:tab] UUE6acMV3m35znLcf0JGNn7Q: Downloading webpage
[download] Downloading playlist: Uploads from Gibi ASMR
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] Downloading page 3
[youtube:tab] Downloading page 4
[youtube:tab] Downloading page 5
[youtube:tab] Downloading page 6
[youtube:tab] playlist Uploads from Gibi ASMR: Downloading 675 videos
[download] Downloading video 1 of 675
[youtube] cqyXspduf_I: Downloading webpage
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 1008, in process_ie_result
    extra_info=extra)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 901, in process_ie_result
    new_result, download=download, extra_info=extra_info)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 1636, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available
```

## Description

Option for --ignore-errors/-i fails on youtube:tab / playlists only. I am attempting to download 4K videos by specifying `height >= 1920`. However as seen in the output above, youtube-dl exists on the first error, since the first video in the playlist does not have a 4K/2160p version available.  

The exact same command line used to work in previous versions of youtube-dl (I suspect prior to implementation of youtube:tab but not sure), and works with playlists on other sites. I tested Vimeo using same command line `youtube-dl --ignore-errors -c -w -f 'bestvideo[height >=? 1920]+bestaudio' --merge-output-format mkv https://vimeo.com/keithloutit/videos`, and youtube-dl correctly continues to the next video in the playlist on error.

**Comment by vatel** [comment]
--ignore-errors/-i fails also on usual (named) playlists
youtube-dl version 2020.11.19

Command line is:
youtube-dl --cookies=... -f "bestvideo[height<=?1080][height>=?720]+bestaudio" --ignore-errors --max-filesize 512m --socket-timeout 600 --download-archive ... <plailistName>
