### ISSUE TITLE
arte.tv m3u8 download results in mp4 file with m3u8 extension

### ISSUE THREAD

**Issue by alexlehm** [ytdl-org/youtube-dl#27061]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.18**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.arte.tv/de/videos/100605-013-A/united-we-stream-november-lockdown-edition-13/', '-f', 'HLS_XQ_1']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2020.11.18
[debug] Python version 3.8.6 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[arte.tv:+7] 100605-013-A: Downloading JSON metadata
[arte.tv:+7] 100605-013-A: Checking HTTPS_MQ_1 video format URL
[arte.tv:+7] 100605-013-A: Checking HTTPS_EQ_1 video format URL
[arte.tv:+7] 100605-013-A: Checking HTTPS_HQ_1 video format URL
[arte.tv:+7] 100605-013-A: Checking HTTPS_SQ_1 video format URL
[arte.tv:+7] 100605-013-A: Checking HLS_XQ_1 video format URL
[debug] Invoking downloader on 'https://arteconcert-vh.akamaihd.net/i/am/concert/100000/100600/100605-013-A_0_VO_AMM-CONCERT-NEXT_XQ.1RS1K1DXZ34.smil/master.m3u8'
[download] Destination: United we Stream November Lockdown Edition #13-100605-013-A.m3u8
ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.
```
(the download is not starting because i have omitted the ffmpeg option, however the resulting filename is shown

## Description

WRITE DESCRIPTION HERE

When downloading from arte.tv with m3u8 urls using the HLS_XQ_1 option, the resulting filename is set to be filename.m3u8 which is incorrect, it should be mp4.

**Comment by JNULYD** [comment]
I have the same problem. the output file should be a video file, but is set to be filename .m3u8. anyone can tell me how to solve it?

**Comment by alexlehm** [comment]
@JNULYD i believe the issue was fixed with a commit in November, maybe you can update your client and check again
it should be possible to rename the file to .mp4 if is saved as m3u8 and is in fact the full file
