### ISSUE TITLE
Youtube channel not extract original title

### ISSUE THREAD

**Issue by Rudbekia** [ytdl-org/youtube-dl#27075]
## Checklist

- [ ] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.18**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\user\Downloads>youtube-dl https://www.youtube.com/c/%D0%95%D0%B3%D0%BE%D1%80%D0%9F%D1%83%D0%BF%D1%8B%D0%BD%D0%B8%D0%BD/videos -e -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/c/%D0%95%D0%B3%D0%BE%D1%80%D0%9F%D1%83%D0%BF%D1%8B%D0%BD%D0%B8%D0%BD/videos', '-e', '-v']
[debug] Encodings: locale cp949, fs utf-8, out utf-8, pref cp949
[debug] youtube-dl version 2020.11.18
[debug] Python version 3.7.3 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
First Person Volleyball Tournament Amateur | Full Championship «Bright Fit» | 4 Games | #96 episode
```

## Description

If I try to download a youtube channel after youtube-dl 2020.11.01.1 version, the title based on en-us is extracted.

As you can see in the log above, For example, https://www.youtube.com/watch?v=zM9r_ssl5eA the extracted title is 
```First Person Volleyball Tournament Amateur | Full Championship «Bright Fit» | 4 Games | #96 episode```
but original title is
```Волейбол от первого лица весь турнир | Чемпионат «Bright Fit» целиком | #96 эпизод```.

Can change it to extract the original title?

**Comment by Ashdemai** [comment]
First of all you're not running on the latest version of youtube-dl, you're using 2020.11.01.1 and the latest is 2020.11.18
Secondly, can't you just rename the title of the video to the original, by hand or are you doing something automated?

**Comment by Rudbekia** [comment]
I using 2020.11.18. look the log.
I was saying "after" 2020.11.01.1, not that I was using it.

And I'm not good at programming or scripts. so I want fix it.

**Comment by Ashdemai** [comment]
I see my bad.

Ah so it's not just a one off, hmm, are you sure there isn't an option in the variables to save the original title instead?

**Comment by Rudbekia** [comment]
As far as I know, there are no options.
not working cookies, %(alt_title)s, etc...

The %(title)s variable itself seems to have changed.

**Comment by october262** [comment]
> As far as I know, there are no options.
> not working cookies, %(alt_title)s, etc...
> 
> The %(title)s variable itself seems to have changed.

try it like this>   youtube-dl https://www.youtube.com/watch?v=zM9r_ssl5eA   --output "First Person Volleyball Tournament Amateur | Full Championship «Bright Fit» | 4 Games | #96 episode.%(ext)s" mp4

**Comment by Rudbekia** [comment]
This situation happens when I download a YouTube channel. Not a single video download.
(ex. https://youtube.com/c/channel)

And I want to replace English translated title to non translated title.
This happened because the channel manager set up to show English titles to English users. This feature seems to be called 'alternative title'.
I’am not English user. So not needed this.

I know use --output(-o) option. but there are many videos on each channel. So I want automatly extract original title.
