### ISSUE TITLE
CBS.com ripping is broken for new videos

### ISSUE THREAD

**Issue by ryvec** [ytdl-org/youtube-dl#27089]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.11.19**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\Molly>D:\youtube-dl.exe -v https://www.cbs.com/shows/the-neighborhood/video/hybfwzvq_TWhJJSE4FXfT_vQB9Ky3Sr_/the-neighborhood-welcome-to-the-movement/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.cbs.com/shows/the-neighborhood/video/hybfwzvq_TWhJJSE4FXfT_vQB9Ky3Sr_/the-neighborhood-welcome-to-the-movement/']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.11.19
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2020-06-28-4cfcfb3, ffprobe git-2020-06-28-4cfcfb3
[debug] Proxy map: {}
[CBS] hybfwzvq_TWhJJSE4FXfT_vQB9Ky3Sr_: Downloading XML
ERROR: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1_szunss\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1_szunss\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1_szunss\build\youtube_dl\extractor\cbs.py", line 112, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1_szunss\build\youtube_dl\extractor\cbs.py", line 62, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1_szunss\build\youtube_dl\utils.py", line 1910, in xpath_text
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1_szunss\build\youtube_dl\utils.py", line 1903, in xpath_element
youtube_dl.utils.ExtractorError: Could not find XML element title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Can't rip newer videos from CBS.com

It seems this change to the site is very recent, since i can rip episode from november 5 with no issues: https://www.cbs.com/shows/young-sheldon/video/7rBATzVHCG2g0eF8g2MlHRRz7mQ4WpPI/young-sheldon-graduation/

But anything new, like https://www.cbs.com/shows/ncis/video/656bTfET07GnL8vgDviQnyaOwGKdaF2W/ncis-sturgeon-season/ gives an error.

Tracing https requests with FIddler shows that first URL called by youtube-dl results in a very different XML page
http://can.cbs.com/thunder/player/videoPlayerService.php?partner=cbs&contentId=ZlEfHIHOKkLTDAOQb5YSz8m_wdiKiCZw
compared to those of older videos 
http://can.cbs.com/thunder/player/videoPlayerService.php?partner=cbs&contentId=7rBATzVHCG2g0eF8g2MlHRRz7mQ4WpPI

**Comment by october262** [comment]
see this thread here - https://github.com/ytdl-org/youtube-dl/issues/27028
