### ISSUE TITLE
Freezes at "Downloading webpage" unless I force ipv4

### ISSUE THREAD

**Issue by notevenaperson** [ytdl-org/youtube-dl#27082]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.11.18**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=aqz-KE-bpKQ', '-v', '--print-traffic']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.18
[debug] Python version 3.8.6 (CPython) - Linux-5.9.8-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] aqz-KE-bpKQ: Downloading webpage
(freezes)
```

## Description

Youtube-dl freezes at "Downloading webpage" step without any kind of error messages or abnormal logs. Passing the option `--force-ipv4` makes it download like normal. This reddit thread seems to talk about the same issue: https://www.reddit.com/r/youtubedl/comments/i7gqhu/youtubedl_stuck_at_downloading_webpage/

**Comment by dstftw** [comment]
Fix your IPv6.

**Comment by notevenaperson** [comment]
Sorry the re-open the issue, but shouldn't youtube-dl, by default, try ipv4 if ipv6 fails?
