### ISSUE TITLE
Three youtube-dl websites

### ISSUE THREAD

**Issue by techboyg5** [ytdl-org/youtube-dl#27098]
Why are there three youtube-dl websites:

* https://yt-dl.org/
* https://youtube-dl.org/
* https://ytdl-org.github.io/youtube-dl/

The first two are exactly the same. The third one is slightly different.

**Comment by sonicrules11** [comment]
More than likely so no one steals them and uses them for malicious purposes

The 3rd one is the youtube-dl github pages website

**Comment by dstftw** [comment]
Why not?
