### ISSUE TITLE
Youtube-dl isn't ignoring when video format isn't available

### ISSUE THREAD

**Issue by Rafiquzzaman420** [ytdl-org/youtube-dl#27095]
I'm using youtube-dl for about almost a year. But today I faced a problem which wasn't there before. As I said, I can't download a full playlist of HD videos. I used **-i** and also used **--ignore** later but problem is still up. I used like this:
>>**youtube-dl -f 136+251 -i --skip-unavailable-fragments "My_preferred_Link"**
The result is:
**[download] Downloading video 32 of 154
[youtube] 0ZOmylyFZQQ: Downloading webpage
ERROR: requested format not available**
I tried to download with different OS but the result is still same. If you wanna try, my link was use this:
**youtube-dl -f 136+251 -i --skip-unavailable-fragments "https://www.youtube.com/playlist?list=PLgH5QX0i9K3oAZUB2QXR-dZac0c9HNyRa"**

Please help me out......Thanks in advance.......Rafi

**Comment by vatel** [comment]
I have the same problem - at least since last week. "-i" flag does not work. Please fix!
