### ISSUE TITLE
bitchute cert issue

### ISSUE THREAD

**Issue by winkelr** [ytdl-org/youtube-dl#27090]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.19**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
./youtube-dl -v --ignore-config -x --audio-format mp3 -o what."%(ext)s" https://www.bitchute.com/video/fdxgKIWvdOYp
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ignore-config', u'-x', u'--audio-format', u'mp3', u'-o', u'what.%(ext)s', u'https://www.bitchute.com/video/fdxgKIWvdOYp']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.19
[debug] Python version 2.7.16 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[BitChute] fdxgKIWvdOYp: Downloading webpage
[BitChute] fdxgKIWvdOYp: Checking video URL
[BitChute] fdxgKIWvdOYp: video URL is invalid, skipping: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/bitchute.py", line 66, in _real_extract
    self._sort_formats(formats)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1359, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
The page works in current version of brave, which says the cert is fine.   Using "--no-check-certificate" works.

**Comment by winkelr** [comment]
I should mention that the audio extraction is irrelevant to the issue.   The same thing happens for 
./youtube-dl -v --ignore-config -o what https://www.bitchute.com/video/fdxgKIWvdOYp
It only works if I include --no-check-certificate

**Comment by remitamine** [comment]
```
youtube-dl https://www.bitchute.com/video/fdxgKIWvdOYp
[BitChute] fdxgKIWvdOYp: Downloading webpage
[BitChute] fdxgKIWvdOYp: Checking video URL
[download] Destination: Primary, Secondary and Tertiary Brainwashing-fdxgKIWvdOYp.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

**Comment by winkelr** [comment]
What platform are you using?

**Comment by remitamine** [comment]
Linux, as the issue is not reproducible across platforms than it's an issue in your OS(ex: expired certificate in the Keychain, outdated openssl version, etc...).

**Comment by winkelr** [comment]
Thanks for your help!
