### ISSUE TITLE
How to download whole yt channel without foreign videos?

### ISSUE THREAD

**Issue by pawelmuszynski** [ytdl-org/youtube-dl#27101]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Previously (before 2020.11.12 version) when I'd like to download all videos from channel I just used `youtube-dl <channel_url>` syntax. It downloaded all videos that was owned by channel owner.  Currently when channel has a playlist that contains videos from other owners they are downloaded as well. Was something changed in this area? I cannot use older version because there's a "0 videos downloaded" warning and nothing happens. How can I download a whole channel without foreign videos?

**Comment by october262** [comment]
youtube-dl --playlist-items_spec
more info - https://askubuntu.com/questions/857265/how-to-download-playalist-except-certain-videos-in-youtube-dl

**Comment by remitamine** [comment]
use the videos tab URL.
