### ISSUE TITLE
archive.org video stream 'Unable to extract' vs pull/23827

### ISSUE THREAD

**Issue by underhandedness** [ytdl-org/youtube-dl#27109]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2020.11.19**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://archive.org/details/CSPAN2_20200621_133000_Douglas_Murray_The_Madness_of_Crowds']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.11.19
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19042.541
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[archive.org] CSPAN2_20200621_133000_Douglas_Murray_The_Madness_of_Crowds: Downloading webpage
ERROR: Unable to extract jwplayer playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1_szunss\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1_szunss\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1_szunss\build\youtube_dl\extractor\archiveorg.py", line 45, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1_szunss\build\youtube_dl\extractor\common.py", line 1010, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract jwplayer playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Content is playable in the browser.  Download fails from base URL as provided, or segment ranged URLs such as

`https://archive.org/details/CSPAN2_20200621_133000_Douglas_Murray_The_Madness_of_Crowds/start/1320/end/1380`

This is not a web server permissions problem as some of the other posted issues.

Related issues

https://github.com/ytdl-org/youtube-dl/pull/23827
https://github.com/ytdl-org/youtube-dl/issues/25277
https://github.com/ytdl-org/youtube-dl/issues/23586

**Comment by october262** [comment]
try youtube-dl --force-generic-extractor https://archive.org/details/CSPAN2_20200621_133000_Douglas_Murray_The_Madness_of_Crowds/start/1320/end/1380

**Comment by undeadrattler** [comment]
I am also having this issue, on a separate platform, both with the debian maintainer version 2021-01-08, and the downloaded youtube-dl version 2021.01.24.1

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://archive.org/details/12AngryMen1957', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 2.7.18 (CPython) - Linux-5.9.0-5-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.3.1-5, ffprobe 4.3.1-5, rtmpdump 2.4
[debug] Proxy map: {}
[archive.org] 12AngryMen1957: Downloading webpage
ERROR: Unable to extract jwplayer playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/archiveorg.py", line 45, in _real_extract
    webpage, 'jwplayer playlist'), video_id)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract jwplayer playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
