### ISSUE TITLE
Bump to python3

### ISSUE THREAD

**Issue by SJang1** [ytdl-org/youtube-dl#27102]
## Checklist

- [x] I'm reporting a feature request - It could be a feature request, but it also can be a bug if python2 not installed.
- [x] I've verified that I'm running youtube-dl version **2020.11.19**
- [x] I've searched the bugtracker for similar feature requests including closed ones - there is #25129 and #16503 , all saying “your configuration is broken” or invaid, but actually just installing python3 like apt(ubuntu) does not set python to run python3. 

## Description

At least on Ubuntu, command python is available when installing python2.7 [(ubuntu wiki)](https://wiki.ubuntu.com/Python/3) ,When you want to use python3 need to use command python3.
**python2 is going to EOL soon**, and also ubuntu has default install with python3.
It looks like building with python3 is also successful with CI, So that, How about bumping into python3?

And though, python3 couldn’t be run using “python” command.

**Comment by rautamiekka** [comment]
Python 2 has been dead for a while by now.

**Comment by remitamine** [comment]
youtube-dl support both versions(Python 2.6+ and 3.2+), it's up to distributions to select the default version used system-wide.
