### ISSUE TITLE
How to use getformat to get custom output?

### ISSUE THREAD

**Issue by mujtabaxd** [ytdl-org/youtube-dl#27110]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I am trying to get a specific format which outputs 1080p videos with the `avc1...` video codec but it's not working for me.
This is the command I'm using:

```
youtube-dl --get-format -f bestvideo[height >= 1080][vcodec ^= avc1] cJKQdzopuco
ERROR: '=' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:=" ) to search YouTube
```
I have tried to use in python but it doesn't work there as well.
```
from youtube_dl import YoutubeDL

url = 'https://www.youtube.com/watch?v=b7RhbRujjUA'

ydl_opts = {
    'format': 'bestvideo[height <= 1080][vcodec ^= avc1]',
    'getformat': True,
    'verbose': True
}

with YoutubeDL(ydl_opts) as ydl:
  ydl.extract_info(url, download=False)
---------------------------------------------------------------------------
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.11.18
[debug] Python version 3.8.1 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2020-11-04-git-cfdddec0c8-full_build
[debug] Proxy map: {}
[youtube] b7RhbRujjUA: Downloading webpage
[Finished in 6.7s]
```
What am I doing wrong?

**Comment by remitamine** [comment]
> it's not working for me.

none of the formats available for this video match your specification(check with `youtube-dl -F cJKQdzopuco`).
for the command line either escape special charachters or quote the the value.
for the script extract the format from the info dict.
