### ISSUE TITLE
how to use --username --password???????? 

### ISSUE THREAD

**Issue by Xyeenie** [ytdl-org/youtube-dl#27117]
HOW DO YOU FUCKING DOWNLOAD YOUTUBE MOVIES WITH A BROKEN DOWNLOADER THAT GIVES A HTTP 400
PASSWORD AND USERNAME ARE FINE, THIS DOES NOT WORK.

**Comment by coletonodonnell** [comment]
Calm down, this project is made by people at no profit to themselves. They are doing this at time that you haven't paid for, you haven't paid for the application nor are you supporting the devs. Your last issue was a duplicate, another person already had the same issue. You haven't given us any system settings, nor have you highlighted any environmental details. It most likely isn't "broken," you most likely are missing something.
1.) If you have two-factor authentication on your YouTube, you will need to append `--twofactor` after your username and password command and insert your two-factor code. 
2.) If all else fails, you can extract your cookies and point to them using the `--cookies` argument. [You can read about this here.](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-pass-cookies-to-youtube-dl)

For future reference, if a GitHub question has been closed as a "duplicate" on a project, that most likely means that you have asked something someone else already has asked and received an answer to that question. If you can't find a solution inside of the closed issues or elsewhere online, you should reach out to the person that closed your issue, **not raging in a new issue.**

**Comment by remitamine** [comment]
Youtube Movies are not supported because they are DRM protected.
again, the login issue has been already reported before.
