### ISSUE TITLE
[BROKEN:YOUTUBE] Got server HTTP error: HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by chrisr11** [ytdl-org/youtube-dl#27119]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.19**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'22', u'https://youtu.be/PKVRTh5lCJU', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.19
[debug] Python version 2.7.16 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] PKVRTh5lCJU: Downloading webpage
[youtube] PKVRTh5lCJU: Downloading MPD manifest
[debug] Invoking downloader on u'https://r2---sn-cxaaj5o5q5-tt1el.googlevideo.com/videoplayback?expire=1605927067&ei=Oyy4X-X4A4iQiwTKp6HIBw&ip=207.35.98.9&id=o-AAiVltfZjMiUdv-OhFyg-B1ZDBwQj3RlyZiGwjbtSodW&itag=22&source=youtube&requiressl=yes&mh=S0&mm=31%2C26&mn=sn-cxaaj5o5q5-tt1el%2Csn-t0a7ln7d&ms=au%2Conr&mv=m&mvi=2&pl=17&initcwndbps=1328750&vprv=1&mime=video%2Fmp4&ns=kTvdsRcAMfg9-ZAyJ8MTb9IF&ratebypass=yes&dur=6298.203&lmt=1581726031307802&mt=1605905318&fvip=2&c=WEB&n=r6G4uwkmAl9Ql1V&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALxK5hIKkXCwuFHX_ua9Kj8K-FndL-Gup-4OGxw89v3RAiASo-4lnSe3vPJHgYTwpxYpXQUbfP4KHAJ6UaUMSRMA5g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMFGKkX4GkjAQAhPoRMVt7Hoj9R_0dY49Xs5182MejchAiEAvBFU0DZL0mJxASyizbOVYljxYP3XZMG8RLBjwekA_Hs%3D'
[download] Resuming download at byte 637143
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 349, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 187, in establish_connection
    raise RetryDownload(err)
RetryDownload
```

## Description

For some reason, youtube-dl is throwing an HTTP Error 500 for a few videos such as the following:

https://youtu.be/PKVRTh5lCJU
https://youtu.be/DQSfSH4KmU0
https://youtu.be/sIdxd-wbPgE
https://youtu.be/oAYNWPiBHO8

This happens ONLY when the "-f" argument is used along with the itag value of the format that I want to download. For instance, this will throw HTTP Error 500:

youtube-dl -f 22 https://youtu.be/PKVRTh5lCJU

If I use "-f bestvideo", then it works fine. Any idea what the issue is?

**Comment by dstftw** [comment]
Server side Youtube error.

**Comment by Provemj** [comment]
> ## Checklist
> * [x]  I'm reporting a broken site support
> * [x]  I've verified that I'm running youtube-dl version **2020.11.19**
> * [x]  I've checked that all provided URLs are alive and playable in a browser
> * [x]  I've checked that all URLs and arguments with special characters are properly quoted or escaped
> * [x]  I've searched the bugtracker for similar issues including closed ones
> 
> ## Verbose log
> ```
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'-f', u'22', u'https://youtu.be/PKVRTh5lCJU', u'--verbose']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2020.11.19
> [debug] Python version 2.7.16 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
> [debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
> [debug] Proxy map: {}
> [youtube] PKVRTh5lCJU: Downloading webpage
> [youtube] PKVRTh5lCJU: Downloading MPD manifest
> [debug] Invoking downloader on u'https://r2---sn-cxaaj5o5q5-tt1el.googlevideo.com/videoplayback?expire=1605927067&ei=Oyy4X-X4A4iQiwTKp6HIBw&ip=207.35.98.9&id=o-AAiVltfZjMiUdv-OhFyg-B1ZDBwQj3RlyZiGwjbtSodW&itag=22&source=youtube&requiressl=yes&mh=S0&mm=31%2C26&mn=sn-cxaaj5o5q5-tt1el%2Csn-t0a7ln7d&ms=au%2Conr&mv=m&mvi=2&pl=17&initcwndbps=1328750&vprv=1&mime=video%2Fmp4&ns=kTvdsRcAMfg9-ZAyJ8MTb9IF&ratebypass=yes&dur=6298.203&lmt=1581726031307802&mt=1605905318&fvip=2&c=WEB&n=r6G4uwkmAl9Ql1V&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALxK5hIKkXCwuFHX_ua9Kj8K-FndL-Gup-4OGxw89v3RAiASo-4lnSe3vPJHgYTwpxYpXQUbfP4KHAJ6UaUMSRMA5g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMFGKkX4GkjAQAhPoRMVt7Hoj9R_0dY49Xs5182MejchAiEAvBFU0DZL0mJxASyizbOVYljxYP3XZMG8RLBjwekA_Hs%3D'
> [download] Resuming download at byte 637143
> [download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 1 of 10)...
> [download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 2 of 10)...
> [download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 3 of 10)...
> [download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 4 of 10)...
> [download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 5 of 10)...
> [download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 6 of 10)...
> [download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 7 of 10)...
> [download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 8 of 10)...
> [download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 9 of 10)...
> [download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 10 of 10)...
> ERROR: giving up after 10 retries
> Traceback (most recent call last):
>   File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 349, in real_download
>     establish_connection()
>   File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 187, in establish_connection
>     raise RetryDownload(err)
> RetryDownload
> ```
> 
> ## Description
> For some reason, youtube-dl is throwing an HTTP Error 500 for a few videos such as the following:
> 
> https://youtu.be/PKVRTh5lCJU https://youtu.be/DQSfSH4KmU0 https://youtu.be/sIdxd-wbPgE https://youtu.be/oAYNWPiBHO8
> 
> This happens ONLY when the "-f" argument is used along with the itag value of the format that I want to download. For instance, this will throw HTTP Error 500:
> 
> youtube-dl -f 22 https://youtu.be/PKVRTh5lCJU
> 
> If I use "-f bestvideo", then it works fine. Any idea what the issue is?

maybe you can try './youtube-dl' or simply 'youtube-dl', it's caused by the different version of python
