### ISSUE TITLE
Buildpack error

### ISSUE THREAD

**Issue by reejit** [ytdl-org/youtube-dl#27111]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I can't make a bot for telegram because of it says error youtube_dl.utils.DownloadError: ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.

Please help me with it is hosted on heroku

**Comment by remitamine** [comment]
this is an issue tacker for youtube-dl, not a support forum.

**Comment by reejit** [comment]
Please help me with it
