### ISSUE TITLE
[vlive] does not support new url type.

### ISSUE THREAD

**Issue by kyuyeunk** [ytdl-org/youtube-dl#27122]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.19**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.vlive.tv/post/0-18257176', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.19
[debug] Git HEAD: a1c88c481
[debug] Python version 3.8.5 (CPython) - Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[generic] 0-18257176: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 0-18257176: Downloading webpage
[generic] 0-18257176: Extracting information
ERROR: Unsupported URL: https://www.vlive.tv/post/0-18257176
Traceback (most recent call last):
  File "/home/kyu/dev/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kyu/dev/youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/home/kyu/dev/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/kyu/dev/youtube-dl/youtube_dl/extractor/generic.py", line 3381, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.vlive.tv/post/0-18257176
```

## Description

https://www.vlive.tv starting using two types of urls: `https://www.vlive.tv/video/<videoId>` (old) and `https://www.vlive.tv/post/<postId>` (new).

For example, http://www.vlive.tv/video/16937 and https://www.vlive.tv/post/0-18257176 both points to the same video.

While current version of yotube-dl supports old type, it returns `Unsupported URL` error when using new type.

**Comment by october262** [comment]
this link - https://www.vlive.tv/post/0-18257176 will work with youtube-dlc

**Comment by kyuyeunk** [comment]
Pull request #27123 allows youtube-dl to support new url type.
