### ISSUE TITLE
am i using the --cookies option wrong

### ISSUE THREAD

**Issue by johnlong21** [ytdl-org/youtube-dl#27127]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

i tried the --cookies option since i had trouble downloading a file, i used the cookies.txt extension to get the cookies file for the video i was having trouble with and got a 3.3 kb file. when i ran the extractor the file changed to 1.6 kb file.

before \<snip\>
after \<snip\>

(here is some system info)
[debug] System config: []

[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', '/media/veracrypt2/downloads/cookies-f.txt', '--download-archive', 'downloaded.txt', '--embed-thumbnail', '-o', '%(title)s-%(uploader)s.%(ext)s', '-x', '-f', 'bestaudio[ext=m4a]/bestaudio[ext=opus]', '--audio-quality', '0', 'https://www.youtube.com/user/SpongieGal', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.19
[debug] Python version 3.8.6 (CPython) - Linux-5.8.0-26-lowlatency-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1

**Comment by dstftw** [comment]
Do not ever post your cookies in public since it contains your session.
If you have any issues fill complete issue template demonstrating the problem.
