### ISSUE TITLE
Add option to download in-progress livestream from the beginning, or from specified time offset.

### ISSUE THREAD

**Issue by 01y** [ytdl-org/youtube-dl#27121]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.11.19**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Add option to download in-progress livestream from the beginning, or from specified time offset. Particularly useful for Youtube, which allows this in its web player. Doing this in faster than realtime would also be nice, in order to catch up to the present.

**Comment by Napoleon-BlownApart** [comment]
This being a duplicate, can a link to the original request be posted here?
