### ISSUE TITLE
How do you get youtube-dl to get the title of a channel's current livestream

### ISSUE THREAD

**Issue by FortuneSeller** [ytdl-org/youtube-dl#27126]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

I tried this: 
youtube-dl --get-filename -o "%(title)s" "https://www.youtube.com/channel/UCoMdktPbSTixAyNGwb-UYkQ/live" 
but instead of getting the currently live stream it tries to check all the videos on the channel instead. 
What can i do to get the title of a livestream with the channel's URL/ID?

**Comment by nudnyzjeb** [comment]
https://www.youtube.com/feeds/videos.xml?channel_id=UCCvVGkm5eCgvYWazrMDLoSg
An entry will appear when a livestream is online or is set to be online (planned), disappear if that livestream ends without leaving an archive.
