### ISSUE TITLE
Yandex Dish it does not work

### ISSUE THREAD

**Issue by dreyky** [ytdl-org/youtube-dl#27131]
youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
$ youtube-dl https://yadi.sk/i/VdOeDou8eZs6Y
[YandexDisk] VdOeDou8eZs6Y: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Sality777** [comment]
$ ydl -v https://yadi.sk/i/VdOeDou8eZs6Y

> [debug] System config: []
> [debug] User config: ['--external-downloader', 'aria2c']
> [debug] Custom config: []
> [debug] Command-line args: ['-v', 'https://yadi.sk/i/VdOeDou8eZs6Y']
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
> [debug] youtube-dl version 2020.11.21.1
> [debug] Git HEAD: cb6e24f94
> [debug] Python version 3.8.6 (CPython) - Linux-5.9.9-arch1-1-x86_64-with-glibc2.2.5
> [debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
> [debug] Proxy map: {}
> [YandexDisk] VdOeDou8eZs6Y: Downloading webpage
> ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>   File "/home/path/.src/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "/home/path/.src/youtube-dl/youtube_dl/YoutubeDL.py", line 2248, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/usr/lib/python3.8/urllib/request.py", line 531, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
>     response = self.parent.error(
>   File "/usr/lib/python3.8/urllib/request.py", line 569, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
