### ISSUE TITLE
Travis CI is possibly broken

### ISSUE THREAD

**Issue by nao20010128nao** [ytdl-org/youtube-dl#27152]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.11.21.1**
    - **this is unrelated to youtube-dl program**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ flake8 .
./youtube_dl/extractor/youtube.py:2613:5: E122 continuation line missing indentation or outdented
./youtube_dl/extractor/youtube.py:2614:5: E122 continuation line missing indentation or outdented
./youtube_dl/extractor/youtube.py:2615:5: E122 continuation line missing indentation or outdented
./youtube_dl/extractor/youtube.py:2616:5: E122 continuation line missing indentation or outdented
./youtube_dl/extractor/youtube.py:2617:5: E122 continuation line missing indentation or outdented
```

## Description

While merging the code to my fork, I noticed that flake8 fails after this change: https://github.com/ytdl-org/youtube-dl/commit/82abc13aedb42d77afcb0ca9c1d7982955826b66

This itself is still serious, but I notificed email from Travis says "Welcome to Travis CI" "You have 10,000 credits left".
I found out that Travis CI's pricing has changed, and ytdl-org is in trouble.

And it brought a more serious problem: No flake8 test on any PRs after the pricing change. Tests in PRs are not working at all.

Reconfiguring Travis CI may be needed.

**Comment by dstftw** [comment]
We're out of credits and already requested more OSS credits.
