### ISSUE TITLE
[YouTube] Liked Music / Your Likes playlist (playlist?list=LM) only downloading first page / 100 videos

### ISSUE THREAD

**Issue by survirtual** [ytdl-org/youtube-dl#27157]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.21.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
~$:youtube-dl --version
2020.11.21.1
~$: youtube-dl --cookies [OMITTED]/cookies.txt --output '[OMITTED]/%(title)s.%(ext)s' --no-overwrites --no-post-overwrites --ignore-errors --yes-playlist 'https://www.youtube.com/playlist?list=LM' --extract-audio --audio-quality 0 --embed-thumbnail --recode-video mp4 --rm-cache-dir --no-cache-dir --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', '[OMITTED]/cookies.txt', '--output', '[OMITTED]/%(title)s.%(ext)s', '--no-overwrites', '--no-post-overwrites', '--ignore-errors', '--yes-playlist', 'https://www.youtube.com/playlist?list=LM', '--extract-audio', '--audio-quality', '0', '--embed-thumbnail', '--recode-video', 'mp4', '--rm-cache-dir', '--no-cache-dir', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.21.1
[debug] Python version 3.9.0 (CPython) - Linux-5.4.0-54-generic-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
Cache is disabled (Did you combine --no-cache-dir and --rm-cache-dir?)
[youtube:tab] LM: Downloading webpage
[download] Downloading playlist: Your Likes
[youtube:tab] Downloading page 1
[youtube:tab] playlist Your Likes: Downloading 100 videos
[download] Downloading video 1 of 100
[youtube] N0sKWsHVz1s: Downloading webpage
```

## Description

When downloading the Liked Music playlist (playlist_id=LM) containing more than 100 videos, only the first page / 100 are detected and downloaded.  --playlist_start 101 returns 0 results.  Tested on a Liked Music playlist with 707 videos.

Note: this requires authentication to duplicate, because the LM playlist is private and bound to accounts.

**Comment by survirtual** [comment]
Commit [b973982](https://github.com/blackjack4494/yt-dlc/pull/245/commits/b9739824a509e17010171ab52a23ec8db72fac2f) in PR [blackjack4494/yt-dlc/pull/245](https://github.com/blackjack4494/yt-dlc/pull/245) on [blackjack4494/yt-dlc](https://github.com/blackjack4494/yt-dlc) fixes this issue.

**Comment by HTMLbyJoe** [comment]
This is happening for me in 2021.06.06. Should I open a new issue or can this one be re-opened? Thanks!

**Comment by halbrd** [comment]
It's happening to me on 2021.12.17 too.
