### ISSUE TITLE
How to skip downloading 360° videos when downloading a channel?

### ISSUE THREAD

**Issue by 54m4d** [ytdl-org/youtube-dl#27172]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi 👋

I don't want to download 360° videos when downloading a channel, is there a way to skip these types of videos?

[This ](https://www.youtube.com/channel/UCnO5ygba3vsJG9IeZLndaTQ)channel for example has videos that are not 360°, i want to download those and skip all 360° videos.

**Comment by e-d-n-a** [comment]
There are two ways to achieve this:

**1. With already available functionality:**

Use the *"--match-filter"-switch* to skip videos, which _"format_note"_ ends with a "s" (for sperical!?):
```
youtube-dl -i -f "[height=720][ext=mp4]" --match-filter "format_note!='720s'" https://www.youtube.com/c/3DVR360/videos
```
(you can simulate the process by adding the _"-s"-switch_, which let's you check which videos will be downloaded!)

This, of cause, can be adapted to allow other or further filtering of the desired videos and formats!


**2. With modified source code to allow easier filtering (maybe as a fix for future releases):**

The easiest fix would be to allow _"format_note"_ as a key for string operators in format filters.
So one quick hack is to replace [this line in YoutubeDL.py](https://github.com/ytdl-org/youtube-dl/blob/75972e200d033429bf9d34793ad3ffc813042347/youtube_dl/YoutubeDL.py#L1086) with:
```
\s*(?P<key>ext|acodec|vcodec|container|protocol|format_id|language|format_note)
```

Then use a command like this to only download non-360° videos with a certain format:
```
youtube-dl -i -f "22[format_note$=p]" https://www.youtube.com/c/3DVR360/videos
```
(you can simulate the process by adding the _"-s"-switch_, which let's you check which videos will be downloaded!)

**Both methods would download the following list of videos:**

1. https://www.youtube.com/watch?v=LpQYs54IY5Q
2. https://www.youtube.com/watch?v=RVY5JtwrG1Y
3. https://www.youtube.com/watch?v=gMVprb6m4-k
4. https://www.youtube.com/watch?v=ZLzfkIrALXk
5. https://www.youtube.com/watch?v=hDKJUdwYgLw
6. https://www.youtube.com/watch?v=ocvuEI0w0g8
7. https://www.youtube.com/watch?v=my0p7COlvek
8. https://www.youtube.com/watch?v=fJo5c4TCmKU
9. https://www.youtube.com/watch?v=5-1J9k0iLDc
10. https://www.youtube.com/watch?v=LFZ7Zn7r5-c
11. https://www.youtube.com/watch?v=_FX6QKcmZQw
12. https://www.youtube.com/watch?v=0vVRIJ3dI_8
13. https://www.youtube.com/watch?v=tea3Nw9evKI
14. https://www.youtube.com/watch?v=z_ADS5pH8sM
15. https://www.youtube.com/watch?v=F2yvWDj5JLo
16. https://www.youtube.com/watch?v=mvrvxGrk7Qw
17. https://www.youtube.com/watch?v=w_wKBowljOM
18. https://www.youtube.com/watch?v=2KAyN_14sZo
19. https://www.youtube.com/watch?v=neEGZwRnxgk
20. https://www.youtube.com/watch?v=ko5dZxDaoe8
21. https://www.youtube.com/watch?v=IGZ3dtf--Ns
22. https://www.youtube.com/watch?v=P4leVAL3ojg
23. https://www.youtube.com/watch?v=anfd-LuJqDI
24. https://www.youtube.com/watch?v=ff693IW6O4w
25. https://www.youtube.com/watch?v=DtUXXIUY-1k
