### ISSUE TITLE
I have updated youtube-dl, but still show urlopen error 0, how to fix it ?

### ISSUE THREAD

**Issue by 1236897** [ytdl-org/youtube-dl#27175]
![image](https://user-images.githubusercontent.com/4466376/100068697-d20aba80-2e72-11eb-98a5-d47df1296812.png)

## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by remitamine** [comment]
do not run `youtube-dl` for normal use as `root`.
