### ISSUE TITLE
Youtube-DL downloading a creator's linked channels and favorites after updating.

### ISSUE THREAD

**Issue by XOIIO** [ytdl-org/youtube-dl#27186]
- [ ] I'm reporting a broken site support issue
- [X ] I've verified that I'm running youtube-dl version **2020.11.24**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

[download] Downloading playlist: Household Hacker - Home
[youtube:tab] playlist Household Hacker - Home: Downloading 6 videos
[download] Downloading video 1 of 6
[youtube:tab] HouseholdhackerTv: Downloading webpage
[download] Downloading playlist: Household Hacker - Videos
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] Downloading page 3
[youtube:tab] Downloading page 4
[youtube:tab] Downloading page 5
[youtube:tab] Downloading page 6
[youtube:tab] Downloading page 7
[youtube:tab] Downloading page 8
[youtube:tab] Downloading page 9
[youtube:tab] Downloading page 10
[youtube:tab] Downloading page 11
[youtube:tab] Downloading page 12
[youtube:tab] Downloading page 13
[youtube:tab] Downloading page 14
[youtube:tab] Downloading page 15
[youtube:tab] Downloading page 16
[youtube:tab] playlist Household Hacker - Videos: Downloading 503 videos
[download] Downloading video 1 of 503

So, I noticed a whole crapload of random channels that I didn't recognize being downloaded, and turned out that it was downloading a favorites playlist, I removed that channel from being scanned since it's no longer active and deleted the over 1200 different new folders however I noticed another issue.

-------------------------------
Youtube-dl is now downloading channels from the "channels" tab on a specific youtube creator's page. Basically if they added channels they like in that section on youtube, it's now scraping all those other channel's content. How do I stop this?

The output seems to indicate that youtube is treating the channels tab as it's own playlist which is why it's getting picked up, so perhaps there's a setting to blacklist a playlist with the names of "Channels" or "Favorites"?

Can't get my settings to post as code, adding a picture.
![screenshot 109](https://user-images.githubusercontent.com/12793421/100162918-37ae7500-2e7a-11eb-9c0e-61cfda45bfa1.jpg)

**Comment by remitamine** [comment]
> How do I stop this?
use the Videos Tab URL.

**Comment by XOIIO** [comment]
> > How do I stop this?
> 
> use the Videos Tab URL.

What if we want to download the other playlists a creator made, just not their favorites or suggested channels? Is the only way to manually add all of those, and also update it every time they add one?

**Comment by remitamine** [comment]
> What if we want to download the other playlists a creator made, just not their favorites or suggested channels?

use the Created playlists Tab URL.

**Comment by makeworld-the-better-one** [comment]
This is highly unexpected behaviour and will break existing scripts. Could this behaviour be undone in youtube-dl's code by default?

**Comment by remitamine** [comment]
I don't think so, it is expected that websites might make breaking changes and that youtube-dl and its users would need to adapt to those changes.

**Comment by makeworld-the-better-one** [comment]
There is no indication of this in the changelog or anything else. The only way users would find this out is through something breaking in a large way.

**Comment by XOIIO** [comment]
> There is no indication of this in the changelog or anything else. The only way users would find this out is through something breaking in a large way.

Exactly, I only noticed this after 350+gb of extra stuff downloaded from over 1200 different videos in a playlist, with no mention of any change that I could find. Thankfully I don't have a data cap, but I have a feeling this is going to affect a pretty large number of people.

**Comment by makeworld-the-better-one** [comment]
This is also what happened to me. And we are [not the only ones](https://old.reddit.com/r/DataHoarder/comments/k114wq/youtubedl_will_now_download_all_linked_channels/). Please reopen this issue.

**Comment by makeworld-the-better-one** [comment]
This has been fixed in version 2020.12.02. The commit of the fix is 132aece1ed824aafd849ef63dcb44c835eab6ee9.
