### ISSUE TITLE
How to prevent downloading partner/other/featured YT channels?

### ISSUE THREAD

**Issue by TheFirsh** [ytdl-org/youtube-dl#27180]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm downloading a channel a regularly (it's set to run every day to catch new uploads). It worked fine for months. Now it's downloading all the partner/other/featured channel's videos too, which I don't need. These: https://www.youtube.com/c/athleanx/channels

It logs them in the archive in the folder of the main channel, so I can just wait then delete them, but still...

My .bat file:
```
cd /D "%~dp0"
youtube-dl https://www.youtube.com/c/athleanx ^
--config-location config.txt ^
--download-archive ATHLEAN-X/archive.txt
PAUSE
```

My config file:
```
--format ("bestvideo[width>=1920]"/bestvideo)+bestaudio/best
--download-archive archive.txt
--output %(uploader)s/%(uploader)s.%(upload_date)s.%(title)s.%(id)s.%(ext)s
--restrict-filenames
--merge-output-format mkv
--ignore-errors
--verbose
--write-sub
--sub-lang es,en
```

My youtube-dl is also set to auto-update itself, and since this started happening today, it must be something in the new version or a change on YT itself.

**Comment by pukkandan** [comment]
Use https://www.youtube.com/c/athleanx/videos . This is a change made in the youtube extractor recently
