### ISSUE TITLE
Downloading HOTSTAR returns this version of hotstar is not supported

### ISSUE THREAD

**Issue by cseandro** [ytdl-org/youtube-dl#27181]
![image](https://user-images.githubusercontent.com/49765763/100134008-86c1cd80-2ead-11eb-8fdc-a844e14c2f4e.png)

youtube dl returns this:

youtube-dl https://www.hotstar.com/in/movies/mookuthi-amman/1260047825/watch
[hotstar] 1260047825: Downloading webpage
[hotstar] 1260047825: Downloading JSON metadata
[hotstar] 1260047825: Downloading m3u8 information
[download] Mookuthi Amman-1260047825.mp4 has already been downloaded
[download] 100% of 740.02KiB
[ffmpeg] Fixing malformed AAC bitstream in "Mookuthi Amman-1260047825.mp4"

**Comment by remitamine** [comment]
a working Indian VPN or proxy is needed to work on this issue.

**Comment by cseandro** [comment]
> a working Indian VPN or proxy is needed to work on this issue.

iam using indian ip only, iam from india
