### ISSUE TITLE
Can't download viki video

### ISSUE THREAD

**Issue by fursiol0800** [ytdl-org/youtube-dl#27184]
> `youtube-dl --version`

> 2020.11.24

----------------------------------

> `youtube-dl "https://www.viki.com/tv/33338c-the-king-loves" --verbose`

> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'https://www.viki.com/tv/33338c-the-king-loves', u'--verbose']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2020.11.24
> [debug] Python version 2.7.16 (CPython) - Linux-5.4.72-v8+-aarch64-with-debian-10.6
> [debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
> [debug] Proxy map: {}
> [viki:channel] 33338c: Downloading channel JSON
> [viki:channel] 33338c: Downloading episodes JSON page #1
> [viki:channel] 33338c: Downloading clips JSON page #1
> [viki:channel] 33338c: Downloading movies JSON page #1
> [download] Downloading playlist: The King Loves
> [viki:channel] playlist The King Loves: Collected 23 video ids (downloading 23 of them)
> [download] Downloading video 1 of 23
> [viki] 1118774v: Downloading video JSON
> ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2248, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 435, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python2.7/urllib2.py", line 473, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

----------------------------------------------------------------------------------------------------

> `python3 $(which youtube-dl) "https://www.viki.com/tv/33338c-the-king-loves" --verbose`

> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['https://www.viki.com/tv/33338c-the-king-loves', '--verbose']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2020.11.24
> [debug] Python version 3.7.3 (CPython) - Linux-5.4.72-v8+-aarch64-with-debian-10.6
> [debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
> [debug] Proxy map: {}
> [viki:channel] 33338c: Downloading channel JSON
> [viki:channel] 33338c: Downloading episodes JSON page #1
> [viki:channel] 33338c: Downloading clips JSON page #1
> [viki:channel] 33338c: Downloading movies JSON page #1
> [download] Downloading playlist: The King Loves
> [viki:channel] playlist The King Loves: Collected 23 video ids (downloading 23 of them)
> [download] Downloading video 1 of 23
> [viki] 1118774v: Downloading video JSON
> ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2248, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/usr/lib/python3.7/urllib/request.py", line 531, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python3.7/urllib/request.py", line 569, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)

-------------------------------------------------------------------------
What is the problem?

**Comment by remitamine** [comment]
Viki API change, will be fixed in the next version.
