### ISSUE TITLE
[Question] How to save video titles or URLs alongside the IDs when using (download archive)?

### ISSUE THREAD

**Issue by fosam** [ytdl-org/youtube-dl#27198]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi! 👋

When using `--download-archive` function youtube-dl saves the video `IDs` to a .txt file. How can i add video `titles`/`URLs` to it so that it becomes something like this:

```
Ducks having a conversation
youtube xJVwvq5z3MI
```

OR:

```
Ducks having a conversation
https://www.youtube.com/watch?v=xJVwvq5z3MI
```
Or if there's any other way to save the `title`+`IDs`/`URLs` together in a text file with no more info than that?

**Comment by dstftw** [comment]
Download archive is not intended to store anything apart from video identifier. You have to store metadata separately.

**Comment by fosam** [comment]
> Download archive is not intended to store anything apart from video identifier. You have to store metadata separately.

@dstftw Thanks!

Is there any other way to save the `title`+`IDs`/`URLs` together in a text file? only these two.

The metadata file has more info than needed in my case and creates a text file for each video instead of having all the info in one single text file
