### ISSUE TITLE
linux download "https://livestream.com/accounts/6115179/events/6764928/videos/144815213" fail

### ISSUE THREAD

**Issue by mengguiyouziyi** [ytdl-org/youtube-dl#27193]
## Checklist

- [ ] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[livestream] 144815213: Downloading JSON metadata
ERROR: Unable to download JSON metadata: <urlopen error [Errno 101] Network is unreachable> (caused by URLError(OSError(101, 'Network is unreachable')))
```

## Description

i use linux  `youtube-dl "https://livestream.com/accounts/6115179/events/6764928/videos/144815213"`，and i fail, but when i use windows, i success.
where is the difference between those?
how can i resolve this error in linux?
thanks

**Comment by october262** [comment]
before i tried this link - https://livestream.com/accounts/6115179/events/6764928/videos/144815213
it seemed to be stuck on downloading, but once i played the video and then retried
the link, it started downloading. tested using LINUX.
