### ISSUE TITLE
Is best quality download correct?

### ISSUE THREAD

**Issue by qo4on** [ytdl-org/youtube-dl#27204]
> By default youtube-dl tries to download the best available quality, i.e. if you want the best quality you don't need to pass any special options, youtube-dl will guess it for you by default.

> 303          webm       1920x1080  1080p60  599k , vp9, 60fps, video only, 19.60MiB
> 299          mp4        1920x1080  1080p60  742k , avc1.64002a, 60fps, video only, 15.67MiB

`youtube-dl` downloaded `299.mp4`. Are you sure that it is the best quality? `webm` file is bigger.

**Comment by JordanWeatherby** [comment]
The 599k vs 742k comparison shows that the bitrate of 299 is higher.

Higher bitrates result in a higher quality at the same resolution - you can see a quick comparison here https://www.youtube.com/watch?v=o1szYdabxag

**Comment by qo4on** [comment]
It's impossible;) If bitrate is higher than file size must be bigger. You have incorrect bitrates. `webm` bitrate 222 kb/s, `mp4` bitrate 177 kb/s.
```
ffprobe "9PSITHCF6sM.webm"
Input #0, matroska,webm, from '9PSITHCF6sM.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:12:19.35, start: 0.000000, bitrate: 222 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)

ffprobe "9PSITHCF6sM.f299.mp4"
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '9PSITHCF6sM.f299.mp4':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6avc1mp41
    creation_time   : 2020-11-23T18:17:38.000000Z
  Duration: 00:12:19.35, start: 0.000000, bitrate: 177 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 2 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)
    Metadata:
      creation_time   : 2020-11-23T18:17:38.000000Z
      handler_name    : ISO Media file produced by Google Inc.
```
