### ISSUE TITLE
Uninstalling YouTube-dl from Big Sur Mac OS X

### ISSUE THREAD

**Issue by AudibleImagery** [ytdl-org/youtube-dl#27203]
## Checklist
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, I'm not computer-savvy and so I had no idea how to install this in the first place and now I need a fresh start. I tried installing YouTube-dl through curl, HomeBrew, and Wget (which I also installed). Installing YouTube-dl through so many channels was a mistake and so I want to completely uninstall it and just install through Homebrew. Could someone please direct me on how to uninstall/remove curl, HomeBrew, Wget, and YouTube-dl from my computer so I can properly install it? Thank you for your help in advance.

**Comment by amitjethani** [comment]
@AudibleImagery 
Can you point to the installation process you followed? If you followed the [INSTALLATION section](https://github.com/ytdl-org/youtube-dl#installation) of the README.md, `curl` and `wget` should yield the same results with one effectively overwriting the other. In either case, invoke `rm /usr/local/bin/youtube-dl` to remove the application.  

What is the output of `which youtube-dl` on your machine?

**Comment by AudibleImagery** [comment]
> @AudibleImagery
> Can you point to the installation process you followed? If you followed the [INSTALLATION section](https://github.com/ytdl-org/youtube-dl#installation) of the README.md, `curl` and `wget` should yield the same results with one effectively overwriting the other. In either case, invoke `rm /usr/local/bin/youtube-dl` to remove the application.
> 
> What is the output of `which youtube-dl` on your machine?

Hi Amit,

Here are the guides I followed/places I copied code from and pasted into Terminal:
https://formulae.brew.sh/formula/youtube-dl
https://techwiser.com/how-to-install-youtube-dl-on-mac/
http://ytdl-org.github.io/youtube-dl/download.html

I also followed your instructions and invoked "rm /usr/local/bin/youtube-dl".

When I enter "which youtube-dl" in Terminal I get the following message: youtube-dl not found

Regards,
John

**Comment by remitamine** [comment]
```
http://ytdl-org.github.io/youtube-dl/download.html
https://techwiser.com/how-to-install-youtube-dl-on-mac/
```
as @amitjethani explained.
```
https://formulae.brew.sh/formula/youtube-dl
```
you can online on how to uninstall homebrew packages.

**Comment by AudibleImagery** [comment]
> ```
> http://ytdl-org.github.io/youtube-dl/download.html
> https://techwiser.com/how-to-install-youtube-dl-on-mac/
> ```
> 
> 
> as @amitjethani explained.
> 
> 
> ```
> https://formulae.brew.sh/formula/youtube-dl
> ```
> 
> 
> you can search online on how to uninstall homebrew packages.

Okay, I'm going to follow the installation steps on the Homebrew website that you linked. I'll let you know how it goes.

**Comment by AudibleImagery** [comment]
> ```
> http://ytdl-org.github.io/youtube-dl/download.html
> https://techwiser.com/how-to-install-youtube-dl-on-mac/
> ```
> 
> 
> as @amitjethani explained.
> 
> 
> ```
> https://formulae.brew.sh/formula/youtube-dl
> ```
> 
> 
> you can search online on how to uninstall homebrew packages.

I uninstalled the YouTube-dl Homebrew and now I'm going to reinstall it. I'll let you know if I have any trouble.

**Comment by AudibleImagery** [comment]
> ```
> http://ytdl-org.github.io/youtube-dl/download.html
> https://techwiser.com/how-to-install-youtube-dl-on-mac/
> ```
> 
> 
> as @amitjethani explained.
> 
> 
> ```
> https://formulae.brew.sh/formula/youtube-dl
> ```
> 
> 
> you can search online on how to uninstall homebrew packages.

I installed via Homebrew and am trying to download a video. I'm getting the following error message

@MacBook-Pro ~ % youtube-dl https://www.youtube.com/watch?v=1UREfJfUm5Q
zsh: no matches found: https://www.youtube.com/watch?v=1UREfJfUm5Q
