### ISSUE TITLE
[youtube] 4GufI9pKWFI: Failed to parse JSON Unterminated string starting at: line 1 column 86462 (char 86461)

### ISSUE THREAD

**Issue by nadermx** [ytdl-org/youtube-dl#27216]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -vvv 4GufI9pKWFI -J
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vvv', '4GufI9pKWFI', '-J']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.26
[debug] Python version 3.7.5 (CPython) - Linux-4.15.0-76-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.3.1-0york0, ffprobe 4.3.1-0york0
[debug] Proxy map: {}
WARNING: [youtube] 4GufI9pKWFI: Failed to parse JSON Unterminated string starting at: line 1 column 83366 (char 83365)
ERROR: 4GufI9pKWFI: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/home/www/env/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/home/www/env/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/home/www/env/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/www/env/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1709, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: 4GufI9pKWFI: YouTube said: Unable to extract video data

```

## Description

WRITE DESCRIPTION HERE

This seems to happen on every third or fourth try, sometimes the first.

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by VADemon** [comment]
This bug is very *elusive*, I've been encountering it for a few days on and off, here's a `--write-pages` from yesterday, I guess it's the same?

It's definitely at least cookies-dependant, based on yesterday's try. Today, I've just got it again, but no error whatsoever on retries.

`youtube-dl version 2020.11.24` - encountered with that release, doubt you changed anything relevant in the latest. I will run more ydl tomorrow if fresh retest needed.
[json extract error.zip](https://github.com/ytdl-org/youtube-dl/files/5609919/json.extract.error.zip)

**Comment by nadermx** [comment]
Here is the pagedump https://gist.github.com/nadermx/cc019ce92ed48b237f6d0cbe998c25e8

**Comment by nadermx** [comment]
After reading VDemon, I realize probably meant the `--write-pages` and that's below

https://gist.github.com/nadermx/61f8bff2ef4877f1ccce4c662b059bf7

**Comment by nadermx** [comment]
Tested, and working, thank you
