### ISSUE TITLE
Support python3 executable (e.g., on minimal Ubuntu)

### ISSUE THREAD

**Issue by scottkosty** [ytdl-org/youtube-dl#27219]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.11.26**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

A fresh minimal installation of Ubuntu 20.10 does not ship with a "python" executable in PATH. It is possible to manually create this executable to point to `python2` or `python3` or to install apt packages that do this, but there are reasons why it would be nice to avoid doing this, and in fact youtube-dl is the only application I use which requires the presence of a `python` executable (although I'm sure there are many that I don't use that have not been adapted yet).

When I run `make` for youtube-dl, it fails because it searches for `python`. It would be great if it could find `python3` and use that. I don't think it's necessary to also search for `python2` because I don't imagine it's common to have neither `python` nor `python3` but to have `python2`.

Thank you for all of your work on youtube-dl!

**Comment by scottkosty** [comment]
Would a patch for this be considered?

**Comment by rautamiekka** [comment]
**This is simply technically unfeasible.** This was asked before/after, and I explained having multiple shebangs per shell script is an unsupported feature.

The only real way would be to drop Python 2.x support altogether cuz releasing multiple separate binaries targeting Python 2.x and 3.x just ain't worth it.

**Comment by scottkosty** [comment]
@rautamiekka Thank you for taking the time to make that detailed reply. I appreciate it!

What I have in mind is that the shebang could be set by "make". True, this would not fix things for users who would like the convenience of running youtube-dl directly after git-cloning it. But for users like myself who run into this, and typically "make" and then "make install" the program, this would be a way to add support for `python3`-only systems without breaking anything else.

**Comment by rautamiekka** [comment]
Maybe, but a Makefile takes a pretty long time to create.

**Comment by scottkosty** [comment]
> Maybe, but a Makefile takes a pretty long time to create.

@rautamiekka True, but there is already a Makefile: https://github.com/ytdl-org/youtube-dl/blob/master/Makefile

**Comment by rautamiekka** [comment]
Ugh, I checked the root listing and still missed it ...

**Comment by dirkf** [comment]
Continued in #30129.
