### ISSUE TITLE
Youtube Throttles ytdl?

### ISSUE THREAD

**Issue by madgabz** [ytdl-org/youtube-dl#27212]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.11.26**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl "https://www.youtube.com/watch?v=RZznSHzEF2Q&list=PLbCLzFKeiWkMisGC6DJLSfsRHpmI-p911" --playlist-start 6 -o '%(uploader)s/Per Aspera/%(playlist_index)03d-%(title)s' -f 137+bestaudio -v
[debug] System config: ['-o', '/mnt/downloads/youtube/%(uploader)s/%(playlist)s/%(playlist_index)03d-%(title)s-%(id)s.%(ext)s', '-f', 'bestvideo[height<=1080][fps!=60][tbr<4500]+bestaudio']
[debug] User config: ['-o', '/mnt/backup/youtube/%(uploader)s/%(playlist)s/%(playlist_index)03d-%(title)s-%(id)s.%(ext)s', '-f', 'bestvideo[height>=1080][tbr<5500]+bestaudio']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=RZznSHzEF2Q&list=PLbCLzFKeiWkMisGC6DJLSfsRHpmI-p911', '--playlist-start', '6', '-o', '%(uploader)s/Per Aspera/%(playlist_index)03d-%(title)s', '-f', '137+bestaudio', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.26
[debug] Python version 3.7.9 (CPython) - FreeBSD-12.1-RELEASE-amd64-64bit-ELF
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.1, ffprobe 4.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] Downloading playlist PLbCLzFKeiWkMisGC6DJLSfsRHpmI-p911 - add --no-playlist to just download video RZznSHzEF2Q
[youtube:tab] PLbCLzFKeiWkMisGC6DJLSfsRHpmI-p911: Downloading webpage
[download] Downloading playlist: Per Aspera
[youtube:tab] playlist Per Aspera: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] m0b1PQTk4lI: Downloading webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r7---sn-uqj-j2ik.googlevideo.com/videoplayback?expire=1606437955&ei=4_e_X7jCE6GS8wKl3qXoCg&ip=176.23.61.85&id=o-AJOI_s1RyuoK3ubtJFSMtHrrHp0Y98xIZPWTc3hX87D9&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%
2C248%2C278&source=youtube&requiressl=yes&mh=bs&mm=31%2C29&mn=sn-uqj-j2ik%2Csn-5goeen7r&ms=au%2Crdu&mv=m&mvi=7&pl=24&initcwndbps=1742500&vprv=1&mime=video%2Fmp4&ns=_QRJqhs7t5j3Kw8EkcUF2QkF&gir=yes&clen=955763444&dur=2258.055&lmt=1606332779591503&mt=1606416037&fvip=3&keep
alive=yes&c=WEB&txp=6316222&n=FKKEbxddrqgzcVuW8fw&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALgh9BK_QC0WOqmfuM90EpQfXB8zpCYqq5Kafpmpzzo_AiEAwkL19PFPA_WyD7iTIdeRrBixUl7H2A_3YW7phGQWoh4%3D&lspar
ams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgNo4nCTIS-xgWpcJ0-jccLRMvmJyXmmmAsjLya2FwdSkCIF4gwSIlgvd6zEIpto1lFpbqFaIUdg3oOyIu6zIET9RL&ratebypass=yes'
[download] Resuming download at byte 295095847
[download] Destination: Skye Storme/Per Aspera/006-LAUNCH THE ASSAULT DRONES! COMBAT SYSTEM REVEALED! - Ep 6 - PER ASPERA Campaign Playthrough.f137
[download]  33.5% of 911.49MiB at 545.94KiB/s ETA 18:57

```

## Description

I have problems with getting specific formats throttled when downloading, specifically -f 137
, which is MP4 1080P! downloading is throttling back to under 10 KB/s and periodically spike to 1-2MB/s for very brief moments, then 'freezes', reupdates after several seconds to show ~20-400 KB/s. If i choose a webm format, like 1080P (-f 248), downloads work flawlessly, maxing my connection out at 6-8 MB/sec.

I usually download to my xigmanas, freebsd based box, but also tried this on my windows desktop, same story!
Anyone experiencing this as well, and/or know how to fix this, if possible?

**Comment by amitjethani** [comment]
@madgabz 

I tried the same link and got results consistent with any other videos on YT with no signs of throttling: 
```zsh
$ youtube-dl "https://www.youtube.com/watch?v=RZznSHzEF2Q&list=PLbCLzFKeiWkMisGC6DJLSfsRHpmI-p911" --playlist-start 6 -o '%(uploader)s/Per Aspera/%(playlist_index)03d-%(title)s' -f 137+bestaudio -v
<snip>
[download] 100% of 911.49MiB in 00:20
[download] 100% of 33.04MiB in 00:00
```

Were you able to reproduce with other videos?

**Comment by dstftw** [comment]
All video-only and audio-only formats are throttled by Youtube after about 10MiB of data transferred. This is bypassed by [reopening connection after each 10MiB](https://github.com/ytdl-org/youtube-dl/blob/f9f9699f2fa87ec54d59b1834cc56adb6147fec6/youtube_dl/extractor/youtube.py#L1995). If you did not touch this everything should work fine.

**Comment by madgabz** [comment]
> I tried the same link and got results consistent with most other videos on YT with no signs of throttling:
tried same videofile with _--http-chunk-size 10185760_ , same thing: file is throttled after a short period/amount (probably the 10MB ur talking about)

`youtube-dl "https://www.youtube.com/watch?v=RZznSHzEF2Q&list=PLbCLzFKeiWkMisGC6DJLSfsRHpmI-p911" --playlist-start 6 -o '%(uploader)s/Per Aspera test/%(playlist_index)03d-%(title)s' -f 137+bestaudio -v --http-chunk-size 10185760`

Other files in same playlist downloads fine, but the specified file up there is very recent, not more than 6 hours old, could this mean something?


> 
> 
> All video-only and audio-only formats are throttled by Youtube after about 10MiB of data transferred. This is bypassed by [reopening connection after each 10MiB](https://github.com/ytdl-org/youtube-dl/blob/f9f9699f2fa87ec54d59b1834cc56adb6147fec6/youtube_dl/extractor/youtube.py#L1995). If you did not touch this everything should work fine.
