### ISSUE TITLE
weibo video can't be downloaded

### ISSUE THREAD

**Issue by yxd0018** [ytdl-org/youtube-dl#27225]
URL https://m.weibo.cn/status/JvROU0aWl
get video URL from chrome dev tool as
https://f.video.weibocdn.com/000I0012gx07IkLpoiKb0104120232As0E010.mp4?label=mp4_ld&template=640  
x360.25.0&trans_finger=6006a648d0db83b7d9951b3cee381a9c&ori=0&ps=1BThihd3VLAY5R&Expires=1606507212&ssig=to  cyQ3MKEk&KID=unistore,video

Tried several URLs and nothing worked. 

ytdl -v https://f.video.weibocdn.com/000I0012gx07IkLpoiKb0104120232As0E010.mp4?label=mp4_ld&template=640  
x360.25.0&trans_finger=6006a648d0db83b7d9951b3cee381a9c&ori=0&ps=1BThihd3VLAY5R&Expires=1606507212&ssig=to  cyQ3MKEk&KID=unistore,video                                                                                 
[debug] System config: []                                                                                   
[debug] User config: ['--no-mtime', '-o', 'd:/temp/download/%(title)s.%(ext)s']                             
[debug] Custom config: []                                                                                   
[debug] Command-line args: ['-v', 'https://f.video.weibocdn.com/000I0012gx07IkLpoiKb0104120232As0E010.mp4?  
label=mp4_ld']                                                                                              
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252                                          
[debug] youtube-dl version 2020.11.19                                                                       
[debug] Python version 3.7.0 (CPython) - Windows-10-10.0.19041-SP0                                          
[debug] exe versions: ffmpeg git-2019-10-06-66d45af, ffprobe git-2019-10-06-66d45af                         
[debug] Proxy map: {}                                                                                       
[generic] 000I0012gx07IkLpoiKb0104120232As0E010: Requesting header                                          
WARNING: Could not send HEAD request to https://f.video.weibocdn.com/000I0012gx07IkLpoiKb0104120232As0E010  
.mp4?label=mp4_ld: HTTP Error 403: Forbidden                                                                
[generic] 000I0012gx07IkLpoiKb0104120232As0E010: Downloading webpage                                        
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); ple  
ase report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://  
yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its com  
plete output.                                                                                               
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 632, in _request_  
webpage                                                                                                     
    return self._downloader.urlopen(url_or_request)                                                         
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 2238, in urlopen          
    return self._opener.open(req, timeout=self._socket_timeout)                                             
  File "c:\programdata\anaconda3\lib\urllib\request.py", line 531, in open                                  
    response = meth(req, response)                                                                          
  File "c:\programdata\anaconda3\lib\urllib\request.py", line 641, in http_response                         
    'http', request, response, code, msg, hdrs)                                                             
  File "c:\programdata\anaconda3\lib\urllib\request.py", line 569, in error                                 
    return self._call_chain(*args)                                                                          
  File "c:\programdata\anaconda3\lib\urllib\request.py", line 503, in _call_chain                           
    result = func(*args)                                                                                    
  File "c:\programdata\anaconda3\lib\urllib\request.py", line 649, in http_error_default                    
    raise HTTPError(req.full_url, code, msg, hdrs, fp)                                                      
                                                                                                            
'template' is not recognized as an internal or external command,                                            
operable program or batch file.                                                                             
'trans_finger' is not recognized as an internal or external command,                                        
operable program or batch file.                                                                             
'ori' is not recognized as an internal or external command,                                                 
operable program or batch file.                                                                             
      PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND                                     
    10108       1   10108      10108  cons0     197610 14:00:36 /usr/bin/ps                                 
'Expires' is not recognized as an internal or external command,                                             
operable program or batch file.                                                                             
'ssig' is not recognized as an internal or external command,                                                
operable program or batch file.                                                                             
'KID' is not recognized as an internal or external command,                                                 
operable program or batch file.

**Comment by october262** [comment]
i used Firefox for this video - https://m.weibo.cn/status/JvROU0aWl
just play the video and right click and select save video as and you can download the video.

**Comment by s104346** [comment]
https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command

``` bash
$ youtube-dl "http://f.video.weibocdn.com/004oCpefgx07IkLpCqk801041203oPrL0E020.mp4?label=mp4_hd&template=852x480.25.0&trans_finger=d8257cc71422c9ad30fe69ce9523c87b&ori=0&ps=1BThihd3VLAY5R&Expires=1606524059&ssig=8ZKbJIYbeL&KID=unistore,video"
[generic] 004oCpefgx07IkLpCqk801041203oPrL0E020.mp4?label=mp4_hd&template=852x480.25: Requesting header
WARNING: Could not send HEAD request to http://f.video.weibocdn.com/004oCpefgx07IkLpCqk801041203oPrL0E020.mp4?label=mp4_hd&template=852x480.25.0&trans_finger=d8257cc71422c9ad30fe69ce9523c87b&ori=0&ps=1BThihd3VLAY5R&Expires=1606524059&ssig=8ZKbJIYbeL&KID=unistore,video: HTTP Error 403: Forbidden
[generic] 004oCpefgx07IkLpCqk801041203oPrL0E020.mp4?label=mp4_hd&template=852x480.25: Downloading webpage
[download] Destination: 004oCpefgx07IkLpCqk801041203oPrL0E020-004oCpefgx07IkLpCqk801041203oPrL0E020.mp4label=mp4_hd&template=852x480.25.mp4
[download]  29.7% of 47.92MiB at  2.04MiB/s ETA 00:16^C
ERROR: Interrupted by user
```

**Comment by yxd0018** [comment]
> https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
> 
> ```shell
> $ youtube-dl "http://f.video.weibocdn.com/004oCpefgx07IkLpCqk801041203oPrL0E020.mp4?label=mp4_hd&template=852x480.25.0&trans_finger=d8257cc71422c9ad30fe69ce9523c87b&ori=0&ps=1BThihd3VLAY5R&Expires=1606524059&ssig=8ZKbJIYbeL&KID=unistore,video"
> [generic] 004oCpefgx07IkLpCqk801041203oPrL0E020.mp4?label=mp4_hd&template=852x480.25: Requesting header
> WARNING: Could not send HEAD request to http://f.video.weibocdn.com/004oCpefgx07IkLpCqk801041203oPrL0E020.mp4?label=mp4_hd&template=852x480.25.0&trans_finger=d8257cc71422c9ad30fe69ce9523c87b&ori=0&ps=1BThihd3VLAY5R&Expires=1606524059&ssig=8ZKbJIYbeL&KID=unistore,video: HTTP Error 403: Forbidden
> [generic] 004oCpefgx07IkLpCqk801041203oPrL0E020.mp4?label=mp4_hd&template=852x480.25: Downloading webpage
> [download] Destination: 004oCpefgx07IkLpCqk801041203oPrL0E020-004oCpefgx07IkLpCqk801041203oPrL0E020.mp4label=mp4_hd&template=852x480.25.mp4
> [download]  29.7% of 47.92MiB at  2.04MiB/s ETA 00:16^C
> ERROR: Interrupted by user
> ```

Thank you very much.
