### ISSUE TITLE
Make an Android version of YouTube-dl

### ISSUE THREAD

**Issue by jidanni** [ytdl-org/youtube-dl#27222]
Here's a long-term wish list item: make an Android version of YouTube-dl.

**Comment by jidanni** [comment]
(Dentex's no longer works.)

**Comment by jidanni** [comment]
You know, just like there was originally only a desktop version of the Chrome browser. And then they made an Android version to!

**Comment by dstftw** [comment]
It works just fine on android.

**Comment by jidanni** [comment]
I mean an .APK!

**Comment by rautamiekka** [comment]
> I mean an .APK!
> Like VLC, available for both desktop and mobile.

I wouldn't hold high hopes, at least for Play Store: I checked, there're exactly 0 downloaders that claim to support YT, but there's numerous downloaders.

**Comment by jidanni** [comment]
Yes, it would never be allowed on Play Store. Because Play Store is owned by Google which owns YouTube.
But that shouldn't stop hopes for a future .APK.
