### ISSUE TITLE
Asking about YouTube's term of service when using this library

### ISSUE THREAD

**Issue by daikisuyama** [ytdl-org/youtube-dl#27221]
I want to use this library for my graduate research, because I need a lot of wave or mp3 datas.
However, there is following description in YouTube's term of service.

---

Permissions and Restrictions
You may access and use the Service as made available to you, as long as you comply with this Agreement and applicable law. You may view or listen to Content for your personal, non-commercial use. You may also show YouTube videos through the embeddable YouTube player.

The following restrictions apply to your use of the Service. You are not allowed to:

(abr.)

3. access the Service using any automated means (such as robots, botnets or scrapers) except (a) in the case of public search engines, in accordance with YouTube’s robots.txt file; or (b) with YouTube’s prior written permission;

---

So, could someone teach me whether downloading many datas is to infringe the term or not ?

**Comment by daikisuyama** [comment]
Can I ask which one is the same question ?

**Comment by Lytexx** [comment]
> @dstftw
> Can I ask which one is the same question ?

i think he means this https://github.com/ytdl-org/youtube-dl/issues/23111

**Comment by daikisuyama** [comment]
@Lytexx 
Thanks a lot!
That is what I want to see.
