### ISSUE TITLE
Problem with [SRGSSR] extractor on newer videos; older (approx 1-month old) videos are OK

### ISSUE THREAD

**Issue by marcozh71** [ytdl-org/youtube-dl#27231]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl --verbose -F "https://tp.srgssr.ch/p/rsi/embed?urn=urn:rsi:video:13639072"

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'https://tp.srgssr.ch/p/rsi/embed?urn=urn:rsi:video:13639072']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.11.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[SRGSSR] 13639072: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 502: Bad Gateway (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8xa81xl2\build\youtube_dl\YoutubeDL.py", line 2248, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

## Description

WRITE DESCRIPTION HERE

Please note that older videos posted on the same website are fine; see example below:

youtube-dl --verbose -F "https://tp.srgssr.ch/p/rsi/embed?urn=urn:rsi:video:13405488"

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'https://tp.srgssr.ch/p/rsi/embed?urn=urn:rsi:video:13405488']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.11.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[SRGSSR] 13405488: Downloading JSON metadata
[SRGSSR] 13405488: Downloading HTTP-HDS-HD token
[SRGSSR] 13405488: Downloading f4m manifest
[SRGSSR] 13405488: Downloading HTTP-HDS-SD token
[SRGSSR] 13405488: Downloading f4m manifest
[SRGSSR] 13405488: Downloading HTTP-HLS-HD token
[SRGSSR] 13405488: Downloading m3u8 information
[SRGSSR] 13405488: Downloading HTTP-HLS-SD token
[SRGSSR] 13405488: Downloading m3u8 information
[info] Available formats for 13405488:
format code       extension  resolution note
HTTP-HLS-HD-351   mp4        480x272     351k , avc1.66.30, mp4a.40.2
HTTP-HLS-SD-351   mp4        480x272     351k , avc1.66.30, mp4a.40.2
HTTP-HLS-HD-931   mp4        640x360     931k , avc1.66.30, mp4a.40.2
HTTP-HLS-SD-931   mp4        640x360     931k , avc1.66.30, mp4a.40.2
HTTP-HLS-HD-3777  mp4        1280x720   3777k , avc1.64001f, mp4a.40.2
HTTP-HLS-SD-3777  mp4        1280x720   3777k , avc1.64001f, mp4a.40.2 (best)

**Comment by october262** [comment]
for this link - https://tp.srgssr.ch/p/rsi/embed?urn=urn:rsi:video:13639072
play the video and press  F12 on your keyboard the debug menu opens, 
select Network and type m3u8 in the search box, copy the file with the m3u8 in the file
and paste the link into youtube-dl.

**Comment by marcozh71** [comment]
It works! Thx!

youtube-dl --verbose -F "https://codww-vh.akamaihd.net/i/rsi/unrestricted/2020/11/27/b08cdc5ba4cffb98ba97737a753d2afa_20201127_212412_,360,272,.mp4.csmil/index_1_av.m3u8?start=0.0&end=4132.046"

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'https://codww-vh.akamaihd.net/i/rsi/unrestricted/2020/11/27/b08cdc5ba4cffb98ba97737a753d2afa_20201127_212412_,360,272,.mp4.csmil/index_1_av.m3u8?start=0.0&end=4132.046']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.11.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[generic] index_1_av.m3u8?start=0.0&end=4132: Requesting header
WARNING: Could not send HEAD request to https://codww-vh.akamaihd.net/i/rsi/unrestricted/2020/11/27/b08cdc5ba4cffb98ba97737a753d2afa_20201127_212412_,360,272,.mp4.csmil/index_1_av.m3u8?start=0.0&end=4132.046: HTTP Error 405: Method Not Allowed
[generic] index_1_av.m3u8?start=0.0&end=4132: Downloading webpage
[generic] index_1_av.m3u8?start=0.0&end=4132: Downloading m3u8 information
[info] Available formats for index_1_av.m3u8?start=0.0&end=4132:
format code  extension  resolution note
0            mp4        unknown
