### ISSUE TITLE
When inner extractor is used, the metadata provided by the main extractor is discarded

### ISSUE THREAD

**Issue by mvolfik** [ytdl-org/youtube-dl#27239]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```bash
git clone https://github.com/mvolfik/youtube-dl.git
cd youtube-dl
git checkout c5ced90f1 # based on latest version 2020.11.26
python3.8 -m youtube_dl "http://www.seznamzpravy.cz/clanek/38489" -vj
```

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.seznamzpravy.cz/clanek/38489', '-vj']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.26
[debug] Git HEAD: c5ced90f1
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-54-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
{
   "_filename" : "Unknown-59e468fe454f8472a96af9fa.mp4",
   "display_id" : "59e468fe454f8472a96af9fa",
   "ext" : "mp4",
   "extractor" : "SDN",
   "extractor_key" : "SDN",
   "format" : "0 - unknown",
   "format_id" : "0",
   "fulltitle" : "Unknown",
   "http_headers" : {
      "Accept" : "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Accept-Charset" : "ISO-8859-1,utf-8;q=0.7,*;q=0.7",
      "Accept-Encoding" : "gzip, deflate",
      "Accept-Language" : "en-us,en;q=0.5",
      "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3696.1 Safari/537.36"
   },
   "id" : "59e468fe454f8472a96af9fa",
   "n_entries" : 1,
   "playlist" : null,
   "playlist_id" : null,
   "playlist_index" : 1,
   "playlist_title" : null,
   "playlist_uploader" : null,
   "playlist_uploader_id" : null,
   "protocol" : "https",
   "requested_subtitles" : null,
   "title" : "Unknown",
   "url" : "https://v39-ng.sdn.cz/~SEC1~expire-1606626631~scope-video~IIse4iF0d-C/v_39/vd_ng_59e468fe454f8472a96af9fa_1508141310/h264_aac_480p_mp4/5c1e2840.mp4",
   "webpage_url" : "https://v39-ng.sdn.cz/~SEC1~expire-1606626631~scope-video~IIse4iF0d-C/v_39/vmd/ng_59e468fe454f8472a96af9fa?fl=mdk,5c1e2840|spl2,3,VOD",
   "webpage_url_basename" : "ng_59e468fe454f8472a96af9fa"
}
```

## Description

I'm developing a new extractor for seznamzpravy.cz, but it includes two parts: first, you extract the metadata from a JSON api. You also get a link to a CDN JSON api, which contains the actual data about the video (mp4 video, stream links, subtitles, but not the metadata). And because this CDN is also used for other services made by Seznam.cz (televizeseznam.cz; novinky.cz; sport.cz), I decided to split this so that the CDN data parsing can be reused. For that, I found in `extractors/common.js` that I can use `"_type": "url"` and provide any already found metadata. So I [do exactly that](https://github.com/mvolfik/youtube-dl/blob/c5ced90f1be44aeafbadb6cb96c284d5b950ad91/youtube_dl/extractor/seznamzpravy.py#L87), but as you can see in the output above, the metadata are completely discarded and only [what is returned from the inner extractor](https://github.com/mvolfik/youtube-dl/blob/c5ced90f1be44aeafbadb6cb96c284d5b950ad91/youtube_dl/extractor/seznamzpravy.py#L16) is used.

An obvious way to work around this would be to make `class SDNBaseIE(InfoExtractor)` which has a function `_extract_video_data(self, sdn_url, video_id)`, and then the extractors using this would inherit from this class and use that, but when the docs say the above is possible, I wanted to use that.

**Comment by dstftw** [comment]
This is expected behavior of `url` type. `url_transparent` should be used instead.

**Comment by mvolfik** [comment]
@dstftw thank you, I now see that `url_transparent` is for that. But what does the third paragraph in `_type = url` mean then? That's what confused me
