### ISSUE TITLE
facebook - ERROR: Unable to extract single video id

### ISSUE THREAD

**Issue by Janevski** [ytdl-org/youtube-dl#27246]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.11.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [~] I've read bugs section in FAQ

## Verbose log

```
jovan@j-janevski:~/Videos$ sudo youtube-dl -U
[sudo] password for jovan: 
Updating to version 2020.11.26 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
jovan@j-janevski:~/Videos$ youtube-dl --verbose https://www.facebook.com/jason.deangelo.9/posts/10219992705741769
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/jason.deangelo.9/posts/10219992705741769']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.26
[debug] Python version 2.7.17 (CPython) - Linux-5.4.0-53-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[facebook] 10219992705741769: Downloading webpage
ERROR: Unable to extract single video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 479, in _real_extract
    video_id = self._search_regex(r'video_id:\s*"([0-9]+)"', webpage, 'single video id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract single video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
jovan@j-janevski:~/Videos$ 

jovan@j-janevski:~/Videos$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
jovan@j-janevski:~/Videos$ 
```

## Description

**OS:** Ubuntu 18.04.4 LTS
**youtube-dl version:** 2020.11.26
**URL:** https://www.facebook.com/jason.deangelo.9/posts/10219992705741769
**Description:** `ERROR: Unable to extract single video id error` on facebook video download.
**Expected behaviour:** Video successfully downloaded.
**Actual behaviour:** Error instead of video download.

**Comment by october262** [comment]
click the 3 dots ... in the upper right hand corner of the video
and select copy link, paste the link into youtube-dl to download the video.

**Comment by scottbernstein** [comment]
I am experiencing the same behavior (only in the last week) with videos such as this one (with the correct formatted link -- I have used youtube-dl for videos of this sort a lot in the past); something has recently changed:
https://www.facebook.com/AndersOsborne/videos/2822708501298940

C:\>youtube-dl -v https://www.facebook.com/AndersOsborne/videos/2822708501298940
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/AndersOsborne/videos/2822708501298940']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.11.29
[debug] Python version 3.7.7 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-82759-g1f5630a, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 2822708501298940: Downloading webpage
[facebook] 2822708501298940: Downloading webpage
[facebook] 2822708501298940: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "c:\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "c:\python37\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\python37\lib\site-packages\youtube_dl\extractor\facebook.py", line 484, in _real_extract
    video_id, fatal_if_no_video=True)
  File "c:\python37\lib\site-packages\youtube_dl\extractor\facebook.py", line 380, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by iamspecial** [comment]
I'm also receiving this error on some vods.

```
PS C:\> youtube-dl -v https://www.facebook.com/arigameplays/videos/2724338047804952/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/arigameplays/videos/2724338047804952/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.12.02
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[facebook] 2724338047804952: Downloading webpage
[facebook] 2724338047804952: Downloading webpage
[facebook] 2724338047804952: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\perso\scoop\apps\python\current\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\perso\scoop\apps\python\current\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\perso\scoop\apps\python\current\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\perso\scoop\apps\python\current\lib\site-packages\youtube_dl\extractor\facebook.py", line 482, in _real_extract
    _, info_dict = self._extract_from_url(
  File "c:\users\perso\scoop\apps\python\current\lib\site-packages\youtube_dl\extractor\facebook.py", line 380, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
