### ISSUE TITLE
Pluralsight WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by DigitalNotebook** [ytdl-org/youtube-dl#27249]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

I have been using youtube-dl to downloading Pluralsight courses. Pluralsight have blocked my account from downloading JSON. 

Can I still use youtube-dl to download Pluralsight courses with no JSON?

if not, what browser extension can I use to grab the JSON file to point it to youtube-dl?

ERROR - WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden

**Comment by sparx2020** [comment]
@dstftw , why it is marked as duplicate ? how to resolve this issue ?

**Comment by MGadAllah** [comment]
@PowerShellScriptRepository Did you solve the problem? as I've the exact problem but do not found any solution at all.
