### ISSUE TITLE
Site revamp MeWatch

### ISSUE THREAD

**Issue by wkweksl** [ytdl-org/youtube-dl#27256]
Site revamp. Current 11.29 version no longer working

C:\Users\Guest\Desktop>youtube-dl https://www.mewatch.sg/watch/Recipe-Of-Life-E1-179371
[generic] Recipe-Of-Life-E1-179371: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Recipe-Of-Life-E1-179371: Downloading webpage
[generic] Recipe-Of-Life-E1-179371: Extracting information
ERROR: Unsupported URL: https://www.mewatch.sg/watch/Recipe-Of-Life-E1-179371

**Comment by october262** [comment]
for this link - https://www.mewatch.sg/watch/Recipe-Of-Life-E1-179371
youtube-dl --no-part --restrict-filenames "https://k-toggle.akamaized.net/dash/p/2082311/sp/208231100/serveFlavor/entryId/1_5fns45uq/v/21/pv/1/ev/34/flavorId/1_,3c6hkelc,tr9ccopm,vot631rk,s8dsc52k,2ahbuf8z,/forceproxy/true/name/a.mp4.urlset/manifest.mpd"

**Comment by wkweksl** [comment]
@october262 thank you. Will temporarily use this workaround.

**Comment by sissyw7** [comment]
@october262 Thanks for the workaround, but how to I get that new url?
