### ISSUE TITLE
"Filename too long" error with default -o format on twitter.com

### ISSUE THREAD

**Issue by afcady** [ytdl-org/youtube-dl#27258]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.11.29**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

The default -o format does not work correctly with `twitter.com`.

It uses the tweet text by default, which is usually longer than the typical `FILENAME_MAX`.

The default output format for `twitter.com` should be changed to something that is always shorter than `FILENAME_MAX`.

**Comment by afcady** [comment]
E.g. this would be a better default:

`youtube-dl -o '%(title).200s-%(id)s.%(ext)s'`

(Hardcoding `200` isn't ideal, but is better.)

**Comment by ntcarver0** [comment]
Another way around this issue would be to implement issue #23192, which asks that support for Win32 long paths be added.

**Comment by afcady** [comment]
This is a duplicate of what other issue number?

#23192 isn't going to fix this issue. That is a filesystem dependent way to _increase_ `FILENAME_MAX`. It won't work e.g. on my Linux btrfs partitions.
