### ISSUE TITLE
YouTube: many related channels being searched, leading to recursion error

### ISSUE THREAD

**Issue by reddragonguy** [ytdl-org/youtube-dl#27266]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2020.11.29**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Recently i noticed that additional channels were being downloaded that were not specified in my configuration file.  the time to processed my file also increased 5x.  I added the `--playlist-end 30` to my file to try to help with this, and now i get a recursion error.  Has something changed where yt-dl now crawls related channels too?  Is there a setting to change this?
[youtube recursion.txt](https://github.com/ytdl-org/youtube-dl/files/5618594/youtube.recursion.txt)

**Comment by dstftw** [comment]
In new Youtube UI channel links point to Home tab that is downloaded. If you need to download another tab - pass the URL of that tab.

**Comment by reddragonguy** [comment]
shouldn't the recursion error still be looked at and addressed?  If i wanted to keep the links i have and the new behavior, then there is still a problem with the looping between friends/channels and the eventual recursion error.

**Comment by ZizzyDizzyMC** [comment]
I was just coming here to check if this type of issue was reported.

I have a script that uses the latest version of YouTube-DL and noticed earlier today that one of my channel directories were filled with garbage and realized it was downloading things other than *just* the channel URL provided.  

Unless there's something here that I'm missing.  I'm using the latest version, but it's the one installed with `pip3`

**Comment by reddragonguy** [comment]
@ZizzyDizzyMC yes, i looked at the code after the comment and it seems you now have to add a suffix of `/videos`, or `/playlists`, or even `/featured` to limit the urls searched on the page.

IMHO, it should, by default, limit itself to mimic the old behavior and add `/videos` and then add a new option to be more greedy if desired.  But at least now i can get back to the old way.

**Comment by reddragonguy** [comment]
@dstftw thank you for the quick fix.

on a tangent, but related matter about time?  i've poured over the output file settings many times and have tried various options.  How does one use the `playlist-index` successfully without yt-dl searching all the videos of a channel.  I use `playlist-reverse`, `dateafter now-30days`, and it still has to look at every single video on the channel and decide to download or not.  I tried using `playlist-end 30`, but then the ids start at 30 (or whatever number used).  

Is there a parameter i've missed to use?  I'm using this with Plex and always trying to guarantee a unique episode number in the filename:  `--output '/workdir/%(uploader)s [%(channel_id)s]/%(playlist_index)s - %(title)s [%(id)s].%(ext)s'`
