### ISSUE TITLE
No stdout streaming for reddit, writes to file instead (-.mp4)

### ISSUE THREAD

**Issue by darvesh** [ytdl-org/youtube-dl#27265]
## Checklist

- [x] I've verified that I'm running youtube-dl version **2020.11.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v  https://www.reddit.com/r/watchpeoplesurvive/comments/k3aoyn/f1_driver_romain_grosjean_coming_out_out_of_the   -o - > i.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.reddit.com/r/watchpeoplesurvive/comments/k3aoyn/f1_driver_romain_grosjean_coming_out_out_of_the', u'-o', u'-']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2020.11.29
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-52-generic-x86_64-with-LinuxMint-20-ulyana
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[RedditR] k3aoyn: Downloading JSON metadata
[Reddit] onbvmhlc17261: Downloading m3u8 information
[Reddit] onbvmhlc17261: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://v.redd.it/onbvmhlc17261/DASH_720.mp4'
[download] Destination: -.fdash-video_2329911
[download] 100% of 3.48MiB in 00:05
[debug] Invoking downloader on u'https://v.redd.it/onbvmhlc17261/DASH_audio.mp4'
[download] Destination: -.fdash-audio_0_132011
[download] 100% of 202.46KiB in 00:01
[ffmpeg] Merging formats into "-.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:-.fdash-video_2329911' -i 'file:-.fdash-audio_0_132011' -c copy -map '0:v:0' -map '1:a:0' 'file:-.temp.mp4'
Deleting original file -.fdash-video_2329911 (pass -k to keep)
Deleting original file -.fdash-audio_0_132011 (pass -k to keep)
```

## Description

`-o -` doesn't redirect to stdout for reddit but creates a file instead (-.mp4)
You can run this command to reproduce 
```youtube-dl https://www.reddit.com/r/watchpeoplesurvive/comments/k3aoyn/f1_driver_romain_grosjean_coming_out_out_of_the -o - > hello.mp4```

**Comment by dstftw** [comment]
There are no video+audio formats served as single fil for this video.

**Comment by trgwii** [comment]
Isn't it reasonable to still let youtube-dl output this to stdout, even if it needs to create temp files to merge?

**Comment by dstftw** [comment]
No, since this defeats the whole point of streaming to stdout.

**Comment by trgwii** [comment]
The point is up to the user imo, it might be to consume it from another program or to pipe it reliably to a media player, it makes more sense for the application to honor that contract if it can than to break it. I'd rather have it emit a warning that it can't purely stream, and is reverting to streaming after merge.

**Comment by MKRhere** [comment]
ffmpeg just errors if you try to stream mp4 to stdout, so that might be a more useful behaviour than silently writing to `-.mp4`
