### ISSUE TITLE
6play - adding 720p for download

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#27278]
## Checklist

- [x ] I'm reporting a site feature request
- [x ] I've verified that I'm running youtube-dl version **2020.12.02**
- [x ] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Hi,
I'm not a developper so I don't know if it's a simple request but 👍 

When i'm downloading a 6play video, I have this : 
(example with a no-drm random video) : https://www.6play.fr/un-diner-presque-parfait-p_820/j2-quimper-c_12211381
The maximum available quality is : 720x406, which is very low..

if I grab a direct download link, i have :
"https://6play.vod.6cloud.fr/usp/mb_sd3/8/0/2/Un-diner-presque-pa_c12211381_Quimper-Journee/Un-diner-presque-pa_c12211381_Quimper-Journee_unpnp.ism/Manifest.mpd", the best quality is indeed 720x406.

BUT, if i change a line in URL :
"https://6play.vod.6cloud.fr/usp/mb_hd1/8/0/2/Un-diner-presque-pa_c12211381_Quimper-Journee/Un-diner-presque-pa_c12211381_Quimper-Journee_unpnp.ism/Manifest.mpd" (so I changed "mb_sd3" to "mb_hd1"), i can download in 1280x720 !

How is it possible to make this possible in youtube-dl ?

Thanks for reading !

**Comment by abaca25** [comment]
Maybe it's better with a screenshot :

![Sans titre 1](https://user-images.githubusercontent.com/75341305/100806944-b171d000-3431-11eb-8de0-1eee1b33782d.png)

**Comment by dzadzen** [comment]
Hello. Now the links have changed to https://6play.vod.6cloud.fr/m6web/output/d/d/5/dd5232314ef756378c665c3c5f7fbe43ee9b2cbb0c02ce686c2a040cfbb92beb/static/web_drm_540p_dash_v1.mpd a different option. 

How to find mpd with hd now?

**Comment by pierre-fribourg-context** [comment]
> Hello. Now the links have changed to a different option: https://6play.vod.6cloud.fr/m6web/output/d/d/5/dd5232314ef756378c665c3c5f7fbe43ee9b2cbb0c02ce686c2a040cfbb92beb/static/web_drm_540p_dash_v1.mpd .
> 
> How to find mpd with hd now?

hi @dzadzen 
how did you get https://6play.vod.6cloud.fr/m6web/output/d/d/5/dd5232314ef756378c665c3c5f7fbe43ee9b2cbb0c02ce686c2a040cfbb92beb/static/web_drm_540p_dash_v1.mpd url from ?

**Comment by dzadzen** [comment]
> > Hello. Now the links have changed to a different option: https://6play.vod.6cloud.fr/m6web/output/d/d/5/dd5232314ef756378c665c3c5f7fbe43ee9b2cbb0c02ce686c2a040cfbb92beb/static/web_drm_540p_dash_v1.mpd .
> > How to find mpd with hd now?
> 
> hi @dzadzen
> how did you get https://6play.vod.6cloud.fr/m6web/output/d/d/5/dd5232314ef756378c665c3c5f7fbe43ee9b2cbb0c02ce686c2a040cfbb92beb/static/web_drm_540p_dash_v1.mpd url from ?

Hi! http://www.6play.fr/les-20-chansons-de-jean-jacques-goldman-prefe-p_19897/les-20-chansons-de-jean-jacques-goldman-preferees-des-francais-c_12871182

**Comment by pierre-fribourg-context** [comment]
> > > Hello. Now the links have changed to a different option: https://6play.vod.6cloud.fr/m6web/output/d/d/5/dd5232314ef756378c665c3c5f7fbe43ee9b2cbb0c02ce686c2a040cfbb92beb/static/web_drm_540p_dash_v1.mpd .
> > > How to find mpd with hd now?
> > 
> > 
> > hi @dzadzen
> > how did you get https://6play.vod.6cloud.fr/m6web/output/d/d/5/dd5232314ef756378c665c3c5f7fbe43ee9b2cbb0c02ce686c2a040cfbb92beb/static/web_drm_540p_dash_v1.mpd url from ?
> 
> Hi! http://www.6play.fr/les-20-chansons-de-jean-jacques-goldman-prefe-p_19897/les-20-chansons-de-jean-jacques-goldman-preferees-des-francais-c_12871182

Hi again @dzadzen 
sorry if my question was not clear enough, I was asking by which youtube-dl command do you get this output url?

On my side I have:

```
youtube-dl http://www.6play.fr/les-20-chansons-de-jean-jacques-goldman-prefe-p_19897/les-20-chansons-de-jean-jacques-goldman-preferees-des-francais-c_12871182
[6play] 12871182: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

or 

```
youtube-dl --get-url http://www.6play.fr/les-20-chansons-de-jean-jacques-goldman-prefe-p_19897/les-20-chansons-de-jean-jacques-goldman-preferees-des-francais-c_12871182
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

so I can't figure out how you extract this https://6play.vod.6cloud.fr/m6web/output/d/d/5/dd5232314ef756378c665c3c5f7fbe43ee9b2cbb0c02ce686c2a040cfbb92beb/static/web_drm_540p_dash_v1.mpd url

**Comment by dzadzen** [comment]
> > > > Привет. Теперь ссылки изменились на другой вариант: https://6play.vod.6cloud.fr/m6web/output/d/d/5/dd5232314ef756378c665c3c5f7fbe43ee9b2cbb0c02ce686c2a040cfbb92beb/static/web_drm_540p_dash_v1.mpd . 
> > > > Как теперь найти mpd с hd?
> > > 
> > > 
> > > привет @dzadzen 
> > > Как вы получили https://6play.vod.6cloud.fr/m6web/output/d/d/5/dd5232314ef756378c665c3c5f7fbe43ee9b2cbb0c02ce686c2a040cfbb92beb/static/web_drm_540p_dash_v1.mpd URL из?
> > 
> > 
> > Привет! http://www.6play.fr/les-20-chansons-de-jean-jacques-goldman-prefe-p_19897/les-20-chansons-de-jean-jacques-goldman-preferees-des-francais-c_12871182
> 
> Еще раз привет @dzadzen,
> извините, если мой вопрос был недостаточно ясным, я спрашивал, с помощью какой команды youtube-dl вы получаете этот выходной URL?
> 
> На моей стороне:
> 
> ```
> youtube-dl http://www.6play.fr/les-20-chansons-de-jean-jacques-goldman-prefe-p_19897/les-20-chansons-de-jean-jacques-goldman-preferees-des-francais-c_12871182
> [6play] 12871182: Downloading JSON metadata
> ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> ```
> 
> или же
> 
> ```
> youtube-dl --get-url http://www.6play.fr/les-20-chansons-de-jean-jacques-goldman-prefe-p_19897/les-20-chansons-de-jean-jacques-goldman-preferees-des-francais-c_12871182
> ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> ```
> 
> так что я не могу понять, как извлечь этот https://6play.vod.6cloud.fr/m6web/output/d/d/5/dd5232314ef756378c665c3c5f7fbe43ee9b2cbb0c02ce686c2a040cfbb92beb/static/web_drm_540p_dash_v1.mpd URL

"The Stream Detector" for firefox [https://user-images.githubusercontent.com/18005470/119900903-d3b25980-bf4d-11eb-8761-97fe1d5e9e8b.png](url)

**Comment by dzadzen** [comment]
> > > > Hello. Now the links have changed to a different option: https://6play.vod.6cloud.fr/m6web/output/d/d/5/dd5232314ef756378c665c3c5f7fbe43ee9b2cbb0c02ce686c2a040cfbb92beb/static/web_drm_540p_dash_v1.mpd .
> > > > How to find mpd with hd now?
> > > 
> > > 
> > > hi @dzadzen
> > > how did you get https://6play.vod.6cloud.fr/m6web/output/d/d/5/dd5232314ef756378c665c3c5f7fbe43ee9b2cbb0c02ce686c2a040cfbb92beb/static/web_drm_540p_dash_v1.mpd url from ?
> > 
> > 
> > Hi! http://www.6play.fr/les-20-chansons-de-jean-jacques-goldman-prefe-p_19897/les-20-chansons-de-jean-jacques-goldman-preferees-des-francais-c_12871182
> 
> Hi again @dzadzen
> sorry if my question was not clear enough, I was asking by which youtube-dl command do you get this output url?
> 
> On my side I have:
> 
> ```
> youtube-dl http://www.6play.fr/les-20-chansons-de-jean-jacques-goldman-prefe-p_19897/les-20-chansons-de-jean-jacques-goldman-preferees-des-francais-c_12871182
> [6play] 12871182: Downloading JSON metadata
> ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> ```
> 
> or
> 
> ```
> youtube-dl --get-url http://www.6play.fr/les-20-chansons-de-jean-jacques-goldman-prefe-p_19897/les-20-chansons-de-jean-jacques-goldman-preferees-des-francais-c_12871182
> ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> ```
> 
> so I can't figure out how you extract this https://6play.vod.6cloud.fr/m6web/output/d/d/5/dd5232314ef756378c665c3c5f7fbe43ee9b2cbb0c02ce686c2a040cfbb92beb/static/web_drm_540p_dash_v1.mpd url

"The Stream Detector" for firefox

**Comment by 89z** [comment]
geo blocking:

> Sorry, this video is not available in your country.
