### ISSUE TITLE
Flag for excluding playlists from channel extractors 

### ISSUE THREAD

**Issue by kolt54321** [ytdl-org/youtube-dl#27277]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.12.02**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

When passing in a Youtube channel link, youtube-dl will download both the channel's videos and playlists. This can be quite lengthy as the channel may not have many videos but lots of user playlists.

There is a ```--no-playlist``` flag - but this excludes all playlists, even from playlists links (not channel links) passed to youtube-dl. If a batch file has both channels and playlists, there is no way to exclude playlists from a user's channel while still downloading playlists from specific playlist links passed in the same file. Can we get a flag to exclude playlist links from the channel extractor?

**Comment by dstftw** [comment]
When passing channel link if will not download both videos and playlists it will rather download exactly what's located on this page in browser. If you need to download videos - pass videos tab URL, if you need to download playlists - pass playlists tab URL. There is no need in any unclear exclusions.
`--no-playlist` has nothing to do with that.

**Comment by kolt54321** [comment]
I see - so instead of passing ```https://www.youtube.com/c/KajtenBestAMV/```, I would pass ```https://www.youtube.com/c/KajtenBestAMV/videos```? That seems to work, thank you.
