### ISSUE TITLE
Linkedin "posts" link result in ERROR: Unsupported URL

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#27270]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.11.29**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Test link:
https://www.linkedin.com/posts/mrpreventive_amazing-drone-footage-activity-6738422973809602561-icet

Should be a simple task to improve the existing extractor, since I was able to get direct video link (even without starting playback) in Firefox > Page Info.
I assume, it might have an expiration on it, so might be not playable in browser by the time to try it:
https://dms.licdn.com/playlist/C4D05AQFaANXcyEPjsw/feedshare-ambry-analyzed_servable_progressive_video/0?e=1606892400&v=beta&t=VbXaT40SxsgYQ0wfksoBAyFdhlD56HxPxSWAd7awQns

Hope this info helps.

**Comment by silpol** [comment]
I have it reproduced with fresh cut release from github, i.e. installed in separate environment by pip like
`pip install -e git+https://github.com/ytdl-org/youtube-dl/#egg=youtube_dl` and 

> $ youtube-dl --version
2021.06.06

same problem from system distribution
> $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

> $ youtube-dl --version
2021.05.16


so I got next trace

> $ youtube-dl --netrc -vv https://www.linkedin.com/posts/corywarfield_joyowl-happybirthday-ugcPost-6872725571420377088-PuHe/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--netrc', '-vvvv', 'https://www.linkedin.com/posts/corywarfield_joyowl-happybirthday-ugcPost-6872725571420377088-PuHe/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Git HEAD: a80358271
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-90-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] corywarfield_joyowl-happybirthday-ugcPost-6872725571420377088-PuHe: Requesting header
WARNING: Falling back on generic information extractor.
[generic] corywarfield_joyowl-happybirthday-ugcPost-6872725571420377088-PuHe: Downloading webpage
[generic] corywarfield_joyowl-happybirthday-ugcPost-6872725571420377088-PuHe: Extracting information
[generic] urn:li:activity:6872725582791139328?compact=true: Requesting header
WARNING: Falling back on generic information extractor.
[generic] urn:li:activity:6872725582791139328?compact=true: Downloading webpage
[generic] urn:li:activity:6872725582791139328?compact=true: Extracting information
ERROR: Unsupported URL: https://www.linkedin.com/embed/feed/update/urn:li:activity:6872725582791139328?compact=true
Traceback (most recent call last):
  File "/tmp/ytdl/.venv/src/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/tmp/ytdl/.venv/src/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/tmp/ytdl/.venv/src/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/tmp/ytdl/.venv/src/youtube-dl/youtube_dl/extractor/generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.linkedin.com/embed/feed/update/urn:li:activity:6872725582791139328?compact=true

**Comment by dirkf** [comment]
Continued in #31501.
