### ISSUE TITLE
[Youtube] Videos are downloaded that were not specified.

### ISSUE THREAD

**Issue by cpz3501** [ytdl-org/youtube-dl#27279]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I run youtube-dl with --batch-file, all urls look like this `https://www.youtube.com/channel/UCNIuvl7V8zACPpTmmNIqP2A`

Until recently, this has perfectly downloaded every upload on channels from their respective URLs. Now I've found that I've downloaded a ton of junk videos from seemingly random channels. The first incorrect download was on 2020-11-12.

---
youtube-dl 2020.11.12

@dstftw dstftw released this 15 days ago · 123 commits to master since this release

Extractors

    [youtube] Rework extractors
---

What do I have to change to make this work again? (Is that some kind of new feature?)
I was thinking about changing all of my urls to `https://www.youtube.com/channel/UCNIuvl7V8zACPpTmmNIqP2A/videos` but wasn't sure if this was the problem. I just want to download all the uploads from the respective channels and nothing else.

**Comment by depesz** [comment]
I got hit by the same problem. In my case, the channel I was downloading was https://www.youtube.com/user/LastWeekTonight, which has vides from 2014. I have it cronned, and recently it started downloading some sesame street videos from 2008 and later. No idea how it found these videos, but something looks seriously wrong.

**Comment by depesz** [comment]
@dstftw While I understand it might be a duplicate - can you please provide link to which issue this issue is a duplicate of? Based on glance of issues list - I don't see it.

**Comment by cpz3501** [comment]
@dstftw Why did you close this??
At least link which issue this is a duplicate of as the other guy said.

Just a side note im on the latest version of youtube-dl and still having this problem...
