### ISSUE TITLE
Support generic streaming video download with .ts partials

### ISSUE THREAD

**Issue by o1dnik** [ytdl-org/youtube-dl#27272]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.11.29**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I am facing an issue downloading a "streaming" video from a website with required authentication. This is an educational website which is holding video-courses and I am willing to download video only for educational purposes and individual usage, as it is intended by the course and without violation of any law. I want to be able to watch those videos on the way in a train or on airplane since I travel a lot.

The website provides "streaming" video player which is downloading plenty of partials in `.ts` file format (blobs) which are then combined into a sequence of chunks of same video inside the video-player. The video can be seen only by providing an authentication token in URL parameters (of course, since it is a paid resource!). So technically nothing should stop me from downloading the whole set of partials and combine them into single file.

### Questions / feature request:

 - Does youtube-dl support this kind of cases? I didn't find anything in the open issues.
 - There is a generic.py extractor, but it only supports a complete single URL on an end video file. Is it possible to pass some attributes to download a set of videos and combine them into single one?

**Comment by remitamine** [comment]
pass the HLS(`.m3u8`) manifest URL to `youtube-dl`.
