### ISSUE TITLE
Cannot read property 'playerMicroformatRenderer' of undefined

### ISSUE THREAD

**Issue by Romick2005** [ytdl-org/youtube-dl#27273]
## Checklist
- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **4.1.1**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log
```
Cannot read property 'playerMicroformatRenderer' of undefined
```

## Description
I was trying to download multiples videos with at same time (10 at a time) and for some loading videos I got error:
`Cannot read property 'playerMicroformatRenderer' of undefined`
Next time, when I stated redownloading process for not loaded videos from previous step, that error dissapear and was never shown.

**Comment by remitamine** [comment]
the problem has to reproducible, and you have to provide the URL causing this problem.
