### ISSUE TITLE
Youtube Dash manifest video downloads are broken HTTP Error 404

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#27285]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
-v -f 137 https://www.youtube.com/watch?v=aXobNQArW64
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'137', u'https://www.youtube.com/watch?v=aXobNQArW64']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.02
[debug] Python version 2.7.16 (CPython) - Darwin-20.1.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] aXobNQArW64: Downloading webpage
[youtube] aXobNQArW64: Downloading MPD manifest
[debug] Invoking downloader on u'https://manifest.googlevideo.com/api/manifest/dash/expire/1606939351/ei/d57HX9WmEIWGv_IPg8yu0Ao/ip/193.0.220.14/id/697a1b35002b5bae/source/youtube/requiressl/yes/playback_host/r8---sn-bpb5oxu-3c2z.googlevideo.com/mh/4_/mm/31%2C29/mn/sn-bpb5oxu-3c2z%2Csn-3c27sne7/ms/au%2Crdu/mv/m/mvi/8/pl/23/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1610000/vprv/1/mt/1606917396/fvip/12/keepalive/yes/beids/23886214/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRAIgCAxNxg3Oj6aET2Y7fVToup3nH1haDROuNnDpPEKt_CICIF9GdDQ7s9WDO-HJII-QiZwqMgSg0kcxWaCgTci3fH77/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhAKzDScV-BcDMVNdgbsxYGH9kcjetRTaK6Uc0oemkWgwoAiEAl1WT3rVqkmZKkKv-atpVkIcFXiArEmHubgL2jhosaOE%3D'
[dashsegments] Total fragments: 71
[download] Destination: Discrete Math - 1.3.2 Key Logical Equivalences Including De Morgan’s Laws-aXobNQArW64.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10)...
ERROR: giving up after 10 fragment retries
Traceback (most recent call last):
  File "./vydl1/youtube_dl/downloader/dash.py", line 48, in real_download
    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
  File "./vydl1/youtube_dl/downloader/fragment.py", line 104, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "./vydl1/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "./vydl1/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "./vydl1/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
HTTPError: HTTP Error 404: Not Found
```

## Description

**Test link:**
https://www.youtube.com/watch?v=aXobNQArW64

**Formats available:**
youtube] aXobNQArW64: Downloading webpage
[youtube] aXobNQArW64: Downloading MPD manifest
[info] Available formats for aXobNQArW64:
format code  extension  resolution note
139          m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
251          webm       audio only DASH audio  130k , webm_dash container, opus @160k (48000Hz)
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k (44100Hz)
278          webm       256x144    DASH video   95k , webm_dash container, vp9, 30fps, video only
160          mp4        256x144    DASH video  108k , mp4_dash container, avc1.4d400b, 30fps, video only
134          mp4        640x360    DASH video  188k , mp4_dash container, avc1.4d401e, 30fps, video only
242          webm       426x240    DASH video  220k , webm_dash container, vp9, 30fps, video only
133          mp4        426x240    DASH video  242k , mp4_dash container, avc1.4d400c, 30fps, video only
243          webm       640x360    DASH video  405k , webm_dash container, vp9, 30fps, video only
244          webm       854x480    DASH video  752k , webm_dash container, vp9, 30fps, video only
135          mp4        854x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 30fps, video only
247          webm       1280x720   DASH video 1505k , webm_dash container, vp9, 30fps, video only
136          mp4        1280x720   DASH video 2310k , mp4_dash container, avc1.4d4016, 30fps, video only
248          webm       1920x1080  DASH video 2646k , webm_dash container, vp9, 30fps, video only
137          mp4        1920x1080  DASH video 4331k , mp4_dash container, avc1.64001e, 30fps, video only
18           mp4        640x360    360p  160k , avc1.42001E, 30fps, mp4a.40.2@ 96k (44100Hz), 7.03MiB
22           mp4        1280x720   720p  346k , avc1.64001F, 30fps, mp4a.40.2@192k (44100Hz) (best)

**Problem:**
Downloading 18, 22 videos and 139, 251, 140 audio are fine. Other DASH video formats downloads are just stuck and then fail with 10 attempts ending with error 404.

**Comment by dstftw** [comment]
Server side Youtube error.

**Comment by someziggyman** [comment]
> Server side Youtube error.
Ok, so, I've tested some other DASH manifest videos and they seem to work fine. for example this one:
http://www.youtube.com/watch?v=ioXI8LfNdlY

I agree, it seems like, it's just that initially reported one fails. Still, good to have this issue listed in "history" in case it comes up for more videos like that. Thanks for looking into it.
