### ISSUE TITLE
Site Support Request for Tver.jp

### ISSUE THREAD

**Issue by Paun** [ytdl-org/youtube-dl#27284]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.12.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

Program is not able to successfully parse site.  Returns message that site is not supported.
- Example video: https://tver.jp/corner/f0062037

Video is fully playable in a browser

## Description

Tver.jp is a website that provides playback of the past week's worth of the more popular show's on Japanese broadcast TV before they expire and are replace with the newly aired.

This would be a _GREAT_ help to the entire expat community that is in Japan, as well as any or all people interested in Japan as a whole.   The website isn't a well optimized experience for many, and it tends to be very slow when most people have time to access it making the overall experience very poor.   Being able to download the video and watch at a later convenience would provide many people (and communities) a true delight.  

Please provide site support for tver.jp if it is at all possible. 

Thank you for your time.

**Comment by joker-8989** [comment]
This request has been closed, but I would like to advise you just in case.
This request may be in violation of Tver's terms.
I will report this request to the Tver team and the Github team.
https://tver.jp/info/terms.html
