### ISSUE TITLE
TeachableCourse: WARNING: unable to extract course title

### ISSUE THREAD

**Issue by amatolf** [ytdl-org/youtube-dl#27286]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

[amato@MBP-de-Luciano]$ youtube-dl --verbose --cookies kodekloud.com_cookies.txt -o "./%(chapter_number)s-%(chapter)s/%(autonumber)03d-%(title)s.%(ext)s" https://kodekloud.com/courses/413743/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--cookies', u'kodekloud.com_cookies.txt', u'-o', u'./%(chapter_number)s-%(chapter)s/%(autonumber)03d-%(title)s.%(ext)s', u'https://kodekloud.com/courses/413743/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.02
[debug] Python version 2.7.16 (CPython) - Darwin-19.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 413743: Requesting header
[redirect] Following redirect to https://kodekloud.com/p/openshift-for-the-absolute-beginners
[generic] openshift-for-the-absolute-beginners: Requesting header
WARNING: Falling back on generic information extractor.
[generic] openshift-for-the-absolute-beginners: Downloading webpage
[generic] openshift-for-the-absolute-beginners: Extracting information
[TeachableCourse] openshift-for-the-absolute-beginners: Downloading webpage
WARNING: unable to extract course title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: openshift-for-the-absolute-beginners
[TeachableCourse] playlist openshift-for-the-absolute-beginners: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: openshift-for-the-absolute-beginners

**Comment by gravitas-dev** [comment]
Having the same issue on stackskills
