### ISSUE TITLE
Broken install

### ISSUE THREAD

**Issue by Juliaria08** [ytdl-org/youtube-dl#27282]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.12.02** ( Im using the **latest** version on pacman ) 
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[julian@art ~]$ youtube-dl
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2020.11.29', 'console_scripts', 'youtube-dl')())
  File "/usr/bin/youtube-dl", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: youtube-dl
```

## Description

Whatever i pass to youtube-dl just splits out the error code

**Comment by Juliaria08** [comment]
Solved by using the latest aur version `youtube-dl-git` is there a need to update the pacman version `youtube-dl` ?

**Comment by AriaMoradi** [comment]
For anyone else facing this issue on arch, its because your python installed version and the one youtube-dl expect is different, make sure your python packages are up to date(or the same version if a downgrade is required)

**Comment by Juliaria08** [comment]
> For anyone else facing this issue on arch, its because your python installed version and the one youtube-dl expects is different, make sure your python packages are up to date(or the same version if a downgrade is required)

Thanks
