### ISSUE TITLE
auto generated subtitle downloading along with video doesnt work

### ISSUE THREAD

**Issue by iNoSec2** [ytdl-org/youtube-dl#27292]
## Checklist

- [x] I've verified that I'm running youtube-dl version **2020.12.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v -f bestvideo+bestaudio --write-auto-sub https://www.youtube.com/watch\?v\=CNNCCgDkt5k
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo+bestaudio', '--write-auto-sub', 'https://www.youtube.com/watch?v=CNNCCgDkt5k']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.02
[debug] Python version 3.8.6 (CPython) - Linux-5.9.10-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, phantomjs 1.9.7, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] CNNCCgDkt5k: Downloading webpage
[youtube] CNNCCgDkt5k: Looking for automatic captions
WARNING: Couldn't find automatic captions for CNNCCgDkt5k
[youtube] CNNCCgDkt5k: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1607014443/ei/y8PIX_LLDdukxN8PwZuO0AY/ip/86.210.105.26/id/08d3420a00e4b799/source/youtube/requiressl/yes/playback_host/r1---sn-hgn7rn7y.googlevideo.com/mh/R8/mm/31%2C26/mn/sn-hgn7rn7y%2Csn-4g5ednsy/ms/au%2Conr/mv/m/mvi/1/pl/17/tx/23947682/txs/23947679%2C23947680%2C23947681%2C23947682%2C23947683/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1065000/vprv/1/mt/1606992525/fvip/1/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgbPVWWm-EaokpIzAg0auzRrTnuX1pv0PG_QNESDGnO24CIQCpf7xIKSd-8D9nbVkrQFEoeJA2qR6rQgQDFeHlHysTag%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIhAICio0KTZP8rBLiyDrkKamwJX0QTu6TDycqdgs8aaF-eAiB2PgnjJRtS4ISMFyRDDaNMeFrgBw9AgtULlDCJla4Mvg%3D%3D'
[dashsegments] Total fragments: 49
[download] Destination: Finding DOMXSS with DevTools _ Untrusted Types Chrome Extension-CNNCCgDkt5k.f303.webm
[download] 100% of 12.89MiB in 00:12
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1607014443/ei/y8PIX_LLDdukxN8PwZuO0AY/ip/86.210.105.26/id/08d3420a00e4b799/source/youtube/requiressl/yes/playback_host/r1---sn-hgn7rn7y.googlevideo.com/mh/R8/mm/31%2C26/mn/sn-hgn7rn7y%2Csn-4g5ednsy/ms/au%2Conr/mv/m/mvi/1/pl/17/tx/23947682/txs/23947679%2C23947680%2C23947681%2C23947682%2C23947683/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1065000/vprv/1/mt/1606992525/fvip/1/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgbPVWWm-EaokpIzAg0auzRrTnuX1pv0PG_QNESDGnO24CIQCpf7xIKSd-8D9nbVkrQFEoeJA2qR6rQgQDFeHlHysTag%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIhAICio0KTZP8rBLiyDrkKamwJX0QTu6TDycqdgs8aaF-eAiB2PgnjJRtS4ISMFyRDDaNMeFrgBw9AgtULlDCJla4Mvg%3D%3D'
[dashsegments] Total fragments: 26
[download] Destination: Finding DOMXSS with DevTools _ Untrusted Types Chrome Extension-CNNCCgDkt5k.f140.m4a
[download] 100% of 3.70MiB in 00:04
[ffmpeg] Merging formats into "Finding DOMXSS with DevTools _ Untrusted Types Chrome Extension-CNNCCgDkt5k.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Finding DOMXSS with DevTools _ Untrusted Types Chrome Extension-CNNCCgDkt5k.f303.webm' -i 'file:Finding DOMXSS with DevTools _ Untrusted Types Chrome Extension-CNNCCgDkt5k.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Finding DOMXSS with DevTools _ Untrusted Types Chrome Extension-CNNCCgDkt5k.temp.mkv'
Deleting original file Finding DOMXSS with DevTools _ Untrusted Types Chrome Extension-CNNCCgDkt5k.f303.webm (pass -k to keep)
Deleting original file Finding DOMXSS with DevTools _ Untrusted Types Chrome Extension-CNNCCgDkt5k.f140.m4a (pass -k to keep)
```

## Description

Hello, the problem is when trying to download subtitle auto generated with the video.And when downloading them separately, the result is random, sometimes it will download them and sometimes it doesnt find them, i used the same videos for testing. i tried 4 times on this video [https://www.youtube.com/watch?v=CNNCCgDkt5k](video) and it works at the 4th try. 
Im not sure but it seems that the problem occured not in this update but in the previous, because i looked previous videos i dl and some auto generated subtitle, which exist in youtube, werent downloaded.

Thanks in advanced, if more info needed, im here.

**Comment by iNoSec2** [comment]
To add more info, here the log when i dl only the auto generated subtitles
```
youtube-dl -v --skip-download https://www.youtube.com/watch\?v\=CNNCCgDkt5k --write-auto-sub
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--skip-download', 'https://www.youtube.com/watch?v=CNNCCgDkt5k', '--write-auto-sub']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.02
[debug] Python version 3.8.6 (CPython) - Linux-5.9.10-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, phantomjs 1.9.7, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] CNNCCgDkt5k: Downloading webpage
[youtube] CNNCCgDkt5k: Looking for automatic captions
[youtube] CNNCCgDkt5k: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Finding DOMXSS with DevTools _ Untrusted Types Chrome Extension-CNNCCgDkt5k.en.vtt
```

**Comment by pipizhang** [comment]
> To add more info, here the log when i dl only the auto generated subtitles and it works
> 
> ```
> youtube-dl -v --skip-download https://www.youtube.com/watch\?v\=CNNCCgDkt5k --write-auto-sub
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['-v', '--skip-download', 'https://www.youtube.com/watch?v=CNNCCgDkt5k', '--write-auto-sub']
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
> [debug] youtube-dl version 2020.12.02
> [debug] Python version 3.8.6 (CPython) - Linux-5.9.10-arch1-1-x86_64-with-glibc2.2.5
> [debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, phantomjs 1.9.7, rtmpdump 2.4
> [debug] Proxy map: {}
> [youtube] CNNCCgDkt5k: Downloading webpage
> [youtube] CNNCCgDkt5k: Looking for automatic captions
> [youtube] CNNCCgDkt5k: Downloading MPD manifest
> [debug] Default format spec: bestvideo+bestaudio/best
> [info] Writing video subtitles to: Finding DOMXSS with DevTools _ Untrusted Types Chrome Extension-CNNCCgDkt5k.en.vtt
> ```

No, it doesn't work, from my test.

> youtube-dl -v --skip-download https://www.youtube.com/watch\?v\=CNNCCgDkt5k --write-auto-sub
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--skip-download', 'https://www.youtube.com/watch?v=CNNCCgDkt5k', '--write-auto-sub']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.02
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-54-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] CNNCCgDkt5k: Downloading webpage
[youtube] CNNCCgDkt5k: Looking for automatic captions
**WARNING: Couldn't find automatic captions for CNNCCgDkt5k**
[youtube] CNNCCgDkt5k: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best

**Comment by iNoSec2** [comment]
> > To add more info, here the log when i dl only the auto generated subtitles and it works
> > ```
> > youtube-dl -v --skip-download https://www.youtube.com/watch\?v\=CNNCCgDkt5k --write-auto-sub
> > [debug] System config: []
> > [debug] User config: []
> > [debug] Custom config: []
> > [debug] Command-line args: ['-v', '--skip-download', 'https://www.youtube.com/watch?v=CNNCCgDkt5k', '--write-auto-sub']
> > [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
> > [debug] youtube-dl version 2020.12.02
> > [debug] Python version 3.8.6 (CPython) - Linux-5.9.10-arch1-1-x86_64-with-glibc2.2.5
> > [debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, phantomjs 1.9.7, rtmpdump 2.4
> > [debug] Proxy map: {}
> > [youtube] CNNCCgDkt5k: Downloading webpage
> > [youtube] CNNCCgDkt5k: Looking for automatic captions
> > [youtube] CNNCCgDkt5k: Downloading MPD manifest
> > [debug] Default format spec: bestvideo+bestaudio/best
> > **_[info] Writing video subtitles to: Finding DOMXSS with DevTools _ Untrusted Types Chrome Extension-CNNCCgDkt5k.en.vtt_**
> > ```
> 
> No, it doesn't work, from my test.

LoL it works and you can see it in the log... anyway

**Comment by vasamaximov** [comment]
Hey, fellows!

Any chance to get this fixed? Downloading clips with subtitles has been broken for the last month! Do you, guys need some additional logs/diagnostics?

**Comment by JamesTheAwesomeDude** [comment]
@vasamaximov I don't think it's a dupe; that issue was closed _successfully_; but this issue is still present:

```
$ youtube-dl -v PqbB07n_uQ4 --write-auto-sub
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'PqbB07n_uQ4', '--write-auto-sub']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.22
[debug] Python version 3.8.6 (CPython) - Linux-5.9.11-100.fc32.x86_64-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] PqbB07n_uQ4: Downloading webpage
[youtube] PqbB07n_uQ4: Looking for automatic captions
WARNING: Couldn't find automatic captions for PqbB07n_uQ4
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r6---sn-qxoedn7z.googlevideo.com/videoplayback?expire=1608643136&ei=4J3hX9C1OdvHkga6xJiIBg&ip=2601%3A8c1%3A17f%3A79f0%3A0%3A0%3A0%3Ad824&id=o-AHo346W3CyzSO1G3bUuKzwdemqijwGIPR7mG49s0qCvW&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=y7&mm=31%2C26&mn=sn-qxoedn7z%2Csn-q4f7sn76&ms=au%2Conr&mv=m&mvi=6&pl=26&initcwndbps=2058750&vprv=1&mime=video%2Fmp4&ns=wdINXW0DK7K7QRItMR8LAG8F&gir=yes&clen=435908111&dur=976.880&lmt=1604790432519894&mt=1608621157&fvip=6&keepalive=yes&c=WEB&txp=5432432&n=CXsz1mYI0kzsJK4O&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAIFrina4Z1kTvrErElROn6oMrS2T0_xDKoiH3a-xSKQjAiEA9bkPiJBX4alQ3ByMhp9UJzrl5MuMF5DKvn9Ue5CJ2LA%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgZjncq2qk30B0muqnpwcvhJ2T3DF13JAHGbmlYTwCjMECICLIa63EqI6P8Q9T7GyuUvSV_tas4rqrE_U80iI4kI3I&ratebypass=yes'
…
```

**Comment by JamesTheAwesomeDude** [comment]
*and, running `youtube-dl -v PqbB07n_uQ4 --write-auto-sub --skip-download` as many as four times did not work at any point.

**Comment by saxingz** [comment]
> *and, running `youtube-dl -v PqbB07n_uQ4 --write-auto-sub --skip-download` as many as four times did not work at any point; it _always_ yielded `WARNING: Couldn't find automatic captions for PqbB07n_uQ4`.

same situation

**Comment by remitamine** [comment]
same issue as #27315, this has been already fixed and a fix will be included in the next version.
```
youtube-dl --ignore-config --write-auto-sub --sub-lang no https://www.youtube.com/watch?v=CNNCCgDkt5k
[youtube] CNNCCgDkt5k: Downloading webpage
[youtube] CNNCCgDkt5k: Looking for automatic captions
[youtube] CNNCCgDkt5k: Downloading MPD manifest
[info] Writing video subtitles to: Finding DOMXSS with DevTools _ Untrusted Types Chrome Extension-CNNCCgDkt5k.no.vtt
...
```
```
youtube-dl --ignore-config --write-auto-sub --sub-lang no https://www.youtube.com/watch?v=PqbB07n_uQ4
[youtube] PqbB07n_uQ4: Downloading webpage
[youtube] PqbB07n_uQ4: Looking for automatic captions
[info] Writing video subtitles to: What It's Like To be a Computer - An Interview with GPT-3-PqbB07n_uQ4.no.vtt
...
```
