### ISSUE TITLE
Gracefully handle failures caused by a YouTube video that requires access to be granted by its owner 

### ISSUE THREAD

**Issue by TZeeGithub** [ytdl-org/youtube-dl#27301]
- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.12.05**

% youtube-dl --version
2020.12.05
% 

- [x] I've searched the bugtracker for similar site feature requests including closed ones

The closest matches I see are:

- #25635 ('Invalid' for unrelated reasons), which actually shows the behavior I am requesting.  That behavior appears to have been lost.
- #23788 which is about not aborting a playlist after failing on a private video.

## Description

The following is from a private video.  When accessing the URL from a web
browser, not logged into YouTube, the site says "If the owner of this video has
granted you access, please sign in."

Per issue # 25635 it appears that in such cases 'youtube-dl' used to report,

>  "ExtractorError: Content Warning
     If the owner of this video has granted you access, please sign in.
           This video is private."

which gives the user an indication of why the download failed.

But that no longer occurs; an ExtractorError is still raised but with no information as to why:

% cat /etc/mx-version 
MX-19.3_x64 patito feo October 21, 2019
% /usr/bin/python3 --version
Python 3.7.3
% 
% youtube-dl --verbose https://www.youtube.com/watch?v=cyJHA_jrzaI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=cyJHA_jrzaI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.02
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-6-amd64-x86_64-with-MX-19.3-patito_feo
[debug] exe versions: ffmpeg 4.1.6, ffprobe 4.1.6
[debug] Proxy map: {}
[youtube] cyJHA_jrzaI: Downloading webpage
[youtube] cyJHA_jrzaI: Downloading embed webpage
[youtube] cyJHA_jrzaI: Refetching age-gated info webpage
WARNING: Unable to extract video title
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 2060, in _real_extract
    raise ExtractorError('no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info')
youtube_dl.utils.ExtractorError: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
% 

TIA for looking at this.

**Comment by TZeeGithub** [comment]
Oops, I just noticed that while I had updated youtube-dl to 2020.12.05 before submitting the issue, the transcript of its invocation that I included was from before then, using 2020.12.02.  Apologies for that.

I am now at 2020.12.07 and its behavior is the same as above:

% youtube-dl --verbose https://www.youtube.com/watch?v=cyJHA_jrzaI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=cyJHA_jrzaI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.07
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-6-amd64-x86_64-with-MX-19.3-patito_feo
[debug] exe versions: ffmpeg 4.1.6, ffprobe 4.1.6
[debug] Proxy map: {}
[youtube] cyJHA_jrzaI: Downloading webpage
[youtube] cyJHA_jrzaI: Downloading embed webpage
[youtube] cyJHA_jrzaI: Refetching age-gated info webpage
WARNING: Unable to extract video title
ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 2060, in _real_extract
    raise ExtractorError('no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info')
youtube_dl.utils.ExtractorError: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

%

**Comment by dirkf** [comment]
Now, not private and handled OK.
