### ISSUE TITLE
Attempting Biography show from A&E networks like Doc says supported. Am i doing something wrong?

### ISSUE THREAD

**Issue by dovedescent7** [ytdl-org/youtube-dl#27309]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

I've been a heavy user of ytdl for about a year now but first post
 Today i updated to the most recent version, so downloads are working correctly again.

My question is:
I see that A&E networks are supported from the documentation, but i am not able to download the specific videos i want which are from a series called Biography, examples below:
https://www.aetv.com/specials/the-nine-lives-of-ozzy-osbourne
https://www.aetv.com/specials/biography-i-want-my-mtv-2
https://www.aetv.com/specials/biography-dolly
I cannot pay for these videos or else i would, and i do not have a cable provider to get past the paywall, even though that hasnt stopped me before with ytdl.

Could someone shed some light on why i cannot download videos from A&E networks though it is clearly supported?

Grateful

**Comment by remitamine** [comment]
website changes, youtube-dl need to be updated to adapt to these changes, there already a request for this.

**Comment by dovedescent7** [comment]
Thank you, Could you possibly provide URL of the request for this so i can follow please? I'm rather new to github Thank you
