### ISSUE TITLE
Error in Youtube DL "Did not get any data blocks" and "Got server HTTP error"

### ISSUE THREAD

**Issue by jlmalone** [ytdl-org/youtube-dl#27300]
Command:  youtube-dl --verbose https://www.youtube.com/watch?v=i_AQLqASoeU

youtube-dl --verbose https://www.youtube.com/watch?v=i_AQLqASoeU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=i_AQLqASoeU']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.02
[debug] Python version 2.7.16 (CPython) - Darwin-19.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] i_AQLqASoeU: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r5---sn-ab5l6nzk.googlevideo.com/videoplayback?expire=1607130100&ei=lIfKX67yBsmE8wTl07vICw&ip=104.37.31.32&id=8bf0102ea012a1e5&itag=22&source=youtube&requiressl=yes&mh=KZ&mm=31%2C26&mn=sn-ab5l6nzk%2Csn-vgqskned&ms=au%2Conr&mv=m&mvi=5&pl=24&initcwndbps=481250&vprv=1&mime=video%2Fmp4&ns=p7XkCuH4Lkw1TmcJrOIougkF&ratebypass=yes&dur=9646.567&lmt=1600003453876242&mt=1607107960&fvip=5&c=WEB&txp=5432432&n=8ACuh0EgzAarXZPff&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIqQyNw-TM3xXO8IhNv8BzZjce3GwLLPm_u_rkBDbS_gAiBBL06laO9DwP3dfO6UgKRxU1mLMH_EihMtslnjcNcyZg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgRczzmUg2Rj-d5W9r6PGxw8mV2sPQ7TbMZz_WQUz4yjoCIHSuP6wZ76EtdcEUYSwaF8e1U_F3Bj9tnYFYIOpS8nJt'
[download] Destination: Unity Campfire #9 - Bret Weinstein with Matt Welch and Bridget Phetasy 09_09_20-i_AQLqASoeU.mp4
[download]   0.8% of 601.65MiB at  4.00MiB/s ETA 02:29[download] Got server HTTP error: Downloaded 5051496 bytes, expected 630877713 bytes. Retrying (attempt 1 of 10)...

ERROR: Did not get any data blocks
Traceback (most recent call last):
  File "/Users/user/Downloads/youtube-dl2/youtube-dl/youtube_dl/downloader/http.py", line 352, in real_download
    return download()
  File "/Users/user/Downloads/youtube-dl2/youtube-dl/youtube_dl/downloader/http.py", line 330, in download
    retry(err)
  File "/Users/user/Downloads/youtube-dl2/youtube-dl/youtube_dl/downloader/http.py", line 233, in retry
    raise RetryDownload(e)
RetryDownload

**Comment by october262** [comment]
this https://www.youtube.com/watch?v=i_AQLqASoeU works ok for me

**Comment by dstftw** [comment]
Server side Youtube error for format 22

**Comment by conkerts** [comment]
Ok, as I followed the bug report filing I searched for this bug (incl. closed ones) and found this report.

> 
> 
> Server side Youtube error for format 22

I guess I have a similar problem with 
youtube-dl.exe --verbose "https://www.youtube.com/watch?v=77wBecc5LbA"

So, how do I diagnose that ?
Is it always something like 
> [download] Resuming download at byte ...

And is there a way to fix that ? 
Or get at least a list of failed IDs, which I could then force to dl with some other format ?
