### ISSUE TITLE
can't download private facebook videos

### ISSUE THREAD

**Issue by krol33** [ytdl-org/youtube-dl#27307]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I get the following results, even if i'm sure of my login password and to be in the facebook group.

'https://www.facebook.com/1609783893/videos/10221474508524677/', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.02
[debug] Python version 3.7.4 (CPython) - Darwin-20.1.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 10221474508524677: Downloading webpage
[facebook] 10221474508524677: Downloading webpage
[facebook] 10221474508524677: Downloading webpage
ERROR: Cannot parse data; ; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/anaconda3/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/opt/anaconda3/lib/python3.7/site-packages/youtube_dl/extractor/facebook.py", line 484, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/opt/anaconda3/lib/python3.7/site-packages/youtube_dl/extractor/facebook.py", line 380, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by october262** [comment]
play the video, and see if there's 3 dots ... in the upper right hand corner of the video,
there should be an option to copy the URL, use that and see if it'll download the video
with youtube-dl.

**Comment by krol33** [comment]
Thanks a lot for your answer. But it's exactly what I did before writting my question and seeing this answer in other comments before. Facebook ask me after to change my password because of intrusion, so my logins are good. I still do not understand the Numbers of errors which come in lines  line 803, line 824, line 532, line 484, and line 380, ('Cannot parse data')

**Comment by remitamine** [comment]
test with the latest version(2020.12.12), if it still doesn't work, then we would need to have access to the video to be able to fix the problem.

**Comment by Write** [comment]
> 
> 
> play the video, and see if there's 3 dots ... in the upper right hand corner of the video,
> there should be an option to copy the URL, use that and see if it'll download the video
> with youtube-dl.

Thanks. This solution indeed work. Link from fb.watch work.
