### ISSUE TITLE
youtube-dl failure to work

### ISSUE THREAD

**Issue by dhotrum** [ytdl-org/youtube-dl#27314]
/usr/bin/env: ‘python’: No such file or directory
That is what I get each time I try to use youtube-dl. I have installed Python to latest twice and youtube-dl latest twice. Where did I go wrong? I use python-3.9.0 through a source and compiled and make then make test then install. As per the directions. Is usr/bin/env: a directory or file? what is it looking for?

**Comment by remitamine** [comment]
install `python 2` or symlink `python3` to `python`.
