### ISSUE TITLE
Option --progress (only if -quit option set)

### ISSUE THREAD

**Issue by Praetor1200** [ytdl-org/youtube-dl#27327]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.11.29**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Would it be possible to add an option --progress for showing progress line when option --quit set? I don't want to see lines like those:
[youtube] dIEHRYlcgRY: Downloading webpage
[youtube] dIEHRYlcgRY: Downloading video info webpage
[download] Destination: ***

But I need to see progress line (not only in console title as with --console-title option).

**Comment by dstftw** [comment]
No as this will not be quiet.
