### ISSUE TITLE
Site support for TV2me.net

### ISSUE THREAD

**Issue by StevenShepa** [ytdl-org/youtube-dl#27326]
## Checklist

- [ x] I'm reporting a new site support request
- [ x] I've verified that I'm running youtube-dl version **2020.12.05**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that none of provided URLs violate any copyrights
- [x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.tv2me.net/90-day-fiance-the-other-way-season-2-episode-1/
- Single video: https://www.tv2me.net/behind-every-man-season-1-episode-5/

## Description

Hi everyone, 

I have tried to download videos from "tv2me.net", but I only receive the following error message, making me and other users think that this site is unsupported so far. No accounts are available and no credentials are required for the download.

> `youtube-dl.exe --verbose --write-sub https://www.tv2me.net/90-day-fiance-the-other-way-season-2-episode-1/
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--verbose', '--write-sub', 'https://www.tv2me.net/90-day-fiance-the-other-way-season-2-episode-1/']
> [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
> [debug] youtube-dl version 2020.12.05
> [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
> [debug] exe versions: ffmpeg N-100203-g2aab42bc40, ffprobe N-100203-g2aab42bc40
> [debug] Proxy map: {}
> [generic] 90-day-fiance-the-other-way-season-2-episode-1: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] 90-day-fiance-the-other-way-season-2-episode-1: Downloading webpage
> [generic] 90-day-fiance-the-other-way-season-2-episode-1: Extracting information
> [download] Downloading playlist: Watch 90 Day Fiance: The Other Way Season 2 Episode 1 HD - Tv2Me
> [generic] playlist Watch 90 Day Fiance: The Other Way Season 2 Episode 1 HD - Tv2Me: Collected 1 video ids (downloading 1 of them)
> [download] Downloading video 1 of 1
> [debug] Default format spec: bestvideo+bestaudio/best
> [debug] Invoking downloader on 'https://www.tv2me.net/newsiteonly/wp-content/uploads/2020/02/Countdown-2637-1.mp4'
> ERROR: unable to download video data: HTTP Error 404: Not Found
> Traceback (most recent call last):
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\YoutubeDL.py", line 1936, in process_info
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\YoutubeDL.py", line 1875, in dl
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\downloader\common.py", line 366, in download
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\downloader\http.py", line 351, in real_download
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\downloader\http.py", line 116, in establish_connection
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\downloader\http.py", line 110, in establish_connection
>   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmplsu1wp4r\build\youtube_dl\YoutubeDL.py", line 2248, in urlopen
>   File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
>   File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
>   File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
>   File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
>   File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
> urllib.error.HTTPError: HTTP Error 404: Not Found`
>

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free
