### ISSUE TITLE
Instagram is not working any more

### ISSUE THREAD

**Issue by thodison** [ytdl-org/youtube-dl#27337]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Since it is not possible to download Instagram image or video with youtube-dl directly anymore, may I ask is it possible to do it with cookies, can someone post an example? Thanks.

**Comment by remitamine** [comment]
```
youtube-dl https://instagram.com/p/aye83DjauH/
[Instagram] aye83DjauH: Downloading webpage
[download] Destination: Video by naomipq-aye83DjauH.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1186k  100 1186k    0     0   287k      0  0:00:04  0:00:04 --:--:--  293k
[curl] Downloaded 1215377 bytes
[download] 100% of 1.16MiB in 00:04
```

**Comment by thodison** [comment]
Thank you.
