### ISSUE TITLE
Unable to download 0

### ISSUE THREAD

**Issue by pyhuee** [ytdl-org/youtube-dl#27346]
I have an issue when I try downloading a video,

ERROR: JGwWNGJdvx8: YouTube said: Unable to extract video data
youtube-dl https://www.youtube.com/watch?v=2zNSgSzhBfM --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=2zNSgSzhBfM', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.14
[debug] Python version 3.8.6 (CPython) - Linux-5.8.0-31-generic-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 2zNSgSzhBfM: Downloading webpage
ERROR: 2zNSgSzhBfM: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1909, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: 2zNSgSzhBfM: YouTube said: Unable to extract video data

[3]+  Exit 1                  youtube-dl https://www.youtube.com/watch?v=JGwWNGJdvx8

**Comment by doggonator** [comment]
I'm getting this now, I have no clue what's going on.

**Comment by 0xh3LL0** [comment]
no problem here?
![utube](https://user-images.githubusercontent.com/23132217/101442895-c927e780-394e-11eb-9d71-38be0365126b.png)

**Comment by doggonator** [comment]
Here's what I get:

Command: 
youtube-dl -v -x --audio-format flac https://www.youtube.com/watch?v=7OwFgS6DrYQ

Output:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-x', '--audio-format', 'flac', 'https://www.youtube.com/watch?v=7OwFgS6DrYQ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.14
[debug] Python version 3.8.6 (CPython) - Linux-5.8.0-31-generic-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 7OwFgS6DrYQ: Downloading webpage
ERROR: 7OwFgS6DrYQ: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1909, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: 7OwFgS6DrYQ: YouTube said: Unable to extract video data

**Comment by wwdok** [comment]
I still have the issue of `YouTube said: Unable to extract video data` for all videos, for this video, its logs are :

```
(base) weidawang@weidawang-TUF-Gaming-FX506LU-FX506LU:~$ sudo -H pip3 install --upgrade youtube-dl
Collecting youtube-dl
  Downloading https://files.pythonhosted.org/packages/87/5e/fddd736a5ded17db328b0157508d935980c07d0fc2c5b5c6105519c5fb6f/youtube_dl-2020.12.7-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.9MB 526kB/s 
Installing collected packages: youtube-dl
Successfully installed youtube-dl-2020.12.7
(base) weidawang@weidawang-TUF-Gaming-FX506LU-FX506LU:~$ youtube-dl https://www.youtube.com/watch?v=2zNSgSzhBfM --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=2zNSgSzhBfM', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.01.1
[debug] Python version 3.7.7 (CPython) - Linux-5.4.0-56-generic-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg N-99911-g8f4aec719e, ffprobe N-99911-g8f4aec719e
[debug] Proxy map: {'http': 'http://127.0.0.1:8889/', 'ftp': 'http://127.0.0.1:8889/', 'https': 'http://127.0.0.1:8889/', 'all': 'socks://127.0.0.1:1089/', 'no': 'localhost,127.0.0.0/8,::1'}
[youtube] 2zNSgSzhBfM: Downloading webpage
ERROR: 2zNSgSzhBfM: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/home/weidawang/miniconda3/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/weidawang/miniconda3/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/weidawang/miniconda3/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1910, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: 2zNSgSzhBfM: YouTube said: Unable to extract video data
```
