### ISSUE TITLE
[question][music.youtube.com] Downloading the high quality stream?

### ISSUE THREAD

**Issue by 0xAB51NTH** [ytdl-org/youtube-dl#27348]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, I have tried finding answer for this one but with no luck, I wanted to get my youtube premium subscription (Besides removing ads while supporting creators I have seen no use to it)to get the 256 aac tracks out of music videos. Doing some basic research I found that I could login to youtube thru yt-dl, soo i decided to give it a shot but it gave `WARNING: Unable to look up account info: HTTP Error 400: Bad Request ` I decided to ditch it at it seemed as not working properly in this usecase, Next I found the cookies method, I got the cookies and made sure everything is fine with them. Dropped them into youtube-dl and tried again, got the standard stream like before but without the error. Though that maybe I have to mix them two but it didnt helped much. The command I was using is 
``` 
youtube-dl --hls-prefer-ffmpeg --extract-audio --audio-quality 0 --audio-format best --embed-thumbnail --cookies C:\Users\MyUsername\Desktop\ytcookies.txt -u blankemail@gmail.com -p P4ssw0rd  https://music.youtube.com/watch?v=X53ft0ySySY&list=RDAMVMX53ft0ySySY
 ```

Sorry if this issue was somehow in the bugtracker but I was unable to find it. Im just a human and I could make a mistake not being able to find it.

Note: Yes Im using the most recent build of youtube-dl.

**Comment by october262** [comment]
may not be possible yet - https://www.reddit.com/r/4kdownloadapps/comments/hbcb28/youtube_myth_busted_320kbps_audio_availability/  read under How to Download YouTube Audio with Highest Possible Bitrate

**Comment by dstftw** [comment]
You must provide premium credentials for any work on this.

**Comment by 0xAB51NTH** [comment]
> You must provide premium credentials for any work on this.

I am providing credintials to my account that has Youtube Premium subscription.
