### ISSUE TITLE
Question about the youtube_dl library with discord.py

### ISSUE THREAD

**Issue by maxim563328** [ytdl-org/youtube-dl#27349]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Good day, I apologize for the trouble. I have a question, how can I use the library to play live stream audio on YouTube. For example, it is tedious for me to pass the audio stream to the bot, but I get an error when I try to do this
![unnamed (1)](https://user-images.githubusercontent.com/56736526/101508569-6c5a1a80-39aa-11eb-8732-98de041f66ab.png)
![unnamed (2)](https://user-images.githubusercontent.com/56736526/101508581-6f550b00-39aa-11eb-8712-6434299228c3.png)
![unnamed (3)](https://user-images.githubusercontent.com/56736526/101508590-711ece80-39aa-11eb-9d1a-a795b2d503dd.png)
![unnamed](https://user-images.githubusercontent.com/56736526/101508596-724ffb80-39aa-11eb-9859-cb0a17e637fd.png)

**Comment by dstftw** [comment]
`'format': 'bestaudio/best'`, `info['url']`.

**Comment by maxim563328** [comment]
> `'format': 'bestaudio/best'`, `info['url']`.

Do I understand correctly that I should add info['url'] to the dictionary?
Can you tell me what it is "info['url']"

**Comment by dstftw** [comment]
No. You should use it as URL for the format you've requested.
