### ISSUE TITLE
error trying to download YouTube video

### ISSUE THREAD

**Issue by mk34** [ytdl-org/youtube-dl#27364]
youtube-dl 'https://www.youtube.com/watch\?v\=eKQGFmIjDgg'
[generic] watch\?v\=eKQGFmIjDgg: Requesting header
WARNING: Could not send HEAD request to https://www.youtube.com/watch\?v\=eKQGFmIjDgg: HTTP Error 404: Not Found
[generic] watch\?v\=eKQGFmIjDgg: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by oddstr13** [comment]
Looks like you're specifying the URL improperly, remove the escapes when wrapping in single quotes.
Try `youtube-dl 'https://www.youtube.com/watch?v=eKQGFmIjDgg'` instead

**Comment by mk34** [comment]
Thank you, that resolves the issue
