### ISSUE TITLE
Please allow Opus audio in mp4 container

### ISSUE THREAD

**Issue by jech** [ytdl-org/youtube-dl#27366]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.12.09**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

When downloading AVC video with Opus audio, youtube-dl prints the following warning:
```
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
```
then puts the merged video in a MKV file.  Opus is allowed in MP4 files, and putting the merged video in an MP4 container is preferable, since the resulting file can be played directly in most browsers.

Fixing this would require making the function `compatible_formats` at https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L1889 a little bit smarter, as this function doesn't currently distinguish between audio and video extensions.

**Comment by theonlypwner** [comment]
@dstftw, is this issue a duplicate of another issue? If so, which one?

I'd suggest something like this for `compatible_formats`:
```py
def compatible_formats(ext, vcodec, acodec):
    codecs = ({
        'mp4': (...),
        'webm': (...),
        # ...
    }).get(ext, ())
    return vcodec in codecs and acodec in codecs

# replace call with compatible_formats(info_dict['ext'], info_dict['vcodec'], info_dict['acodec'])
```
