### ISSUE TITLE
unable to extract xsrf token and FileNotFoundError: [WinError 2] The system cannot find the file specified:

### ISSUE THREAD

**Issue by Pretzelek** [ytdl-org/youtube-dl#27372]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.12.09**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
F:\YT>youtube-dl --format "(bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec=vp9.2][height>=1080][fps>30]/bestvideo[vcodec=vp9][height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec=vp9.2][height>=1080]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec=vp9.2][height>=720][fps>30]/bestvideo[vcodec=vp9][height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec=vp9.2][height>=720]/bestvideo[vcodec=vp9][height>=720]/bestvideo[height>=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best" --verbose --geo-bypass --force-ipv4 --ignore-errors --no-continue --no-overwrites --download-archive archive.log --add-metadata --write-description --write-info-json --write-annotations --write-thumbnail --embed-thumbnail --all-subs --sub-format "srt" --embed-subs --output "%(uploader)s/%(uploader)s - %(upload_date)s - %(title)s.%(ext)s" --merge-output-format "mkv" --batch-file "Source - Channels.txt" --cookies cookies.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--format', '(bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec=vp9.2][height>=1080][fps>30]/bestvideo[vcodec=vp9][height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec=vp9.2][height>=1080]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec=vp9.2][height>=720][fps>30]/bestvideo[vcodec=vp9][height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec=vp9.2][height>=720]/bestvideo[vcodec=vp9][height>=720]/bestvideo[height>=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best', '--verbose', '--geo-bypass', '--force-ipv4', '--ignore-errors', '--no-continue', '--no-overwrites', '--download-archive', 'archive.log', '--add-metadata', '--write-description', '--write-info-json', '--write-annotations', '--write-thumbnail', '--embed-thumbnail', '--all-subs', '--sub-format', 'srt', '--embed-subs', '--output', '%(uploader)s/%(uploader)s - %(upload_date)s - %(title)s.%(ext)s', '--merge-output-format', 'mkv', '--batch-file', 'Source - Channels.txt', '--cookies', 'cookies.txt', '--verbose']
[debug] Batch file urls: ['https://www.youtube.com/user/sambowne/videos']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.09
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe git-2020-06-12-38737b3
[debug] Proxy map: {}
[youtube:tab] sambowne: Downloading webpage
[download] Downloading playlist: Sam Bowne - Videos
[youtube:tab] Downloading page 1
{removing uninteresting log entries about ~700 videos that were downloaded successfully}
[youtube:tab] Downloading page 31
[youtube:tab] playlist Sam Bowne - Videos: Downloading 953 videos
[download] Downloading video 1 of 953
[download] CNIT 126. 15: Anti-Disassembly has already been recorded in archive
{removing uninteresting log entries about ~700 videos that were downloaded successfully}
[download] Downloading video 715 of 953
[download] CNIT 123 13: Network Protection Systems (Part 2) has already been recorded in archive
[download] Downloading video 716 of 953
[youtube] nW6pc2N4b7U: Downloading webpage
WARNING: video doesn't have subtitles
WARNING: unable to extract xsrf token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] nW6pc2N4b7U: Downloading MPD manifest
[info] Video description is already present
WARNING: There are no annotations to write.
[info] Video description metadata is already present
[youtube] nW6pc2N4b7U: Thumbnail is already present
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1607639500/ei/bE3SX7KrI8KZ8gP96IfoDA/ip/80.49.130.28/id/9d6ea97363786fb5/source/youtube/requiressl/yes/playback_host/r1---sn-u2oxu-fgvl.googlevideo.com/mh/ez/mm/31%2C29/mn/sn-u2oxu-fgvl%2Csn-u2oxu-f5fe7/ms/au%2Crdu/mv/m/mvi/1/pl/24/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1136250/vprv/1/mt/1607617715/fvip/4/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgXZLJuhOzQqixcUs3XQ7lx6Eh1BUgbQ8-NRAcY1xz7vYCIQC0_VrH1es7NUmzJTiViVchK8tHWcdLy3LEjD7PL4Wp3A%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhAMkwbXHaBkz397AipQwhUgdd_2WCFqHM4YduFOcq0eW2AiEA1Ku0eELtRwZy7CyQKZmZrXKBkNB2nLRt4R5A1X0b4sQ%3D'
[download] Sam Bowne\Sam Bowne - 20170425 - CNIT 126 12 - Covert Malware Launching.f302.webm has already been downloaded
[download] 100% of 39.25MiB
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1607639500/ei/bE3SX7KrI8KZ8gP96IfoDA/ip/80.49.130.28/id/9d6ea97363786fb5/source/youtube/requiressl/yes/playback_host/r1---sn-u2oxu-fgvl.googlevideo.com/mh/ez/mm/31%2C29/mn/sn-u2oxu-fgvl%2Csn-u2oxu-f5fe7/ms/au%2Crdu/mv/m/mvi/1/pl/24/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1136250/vprv/1/mt/1607617715/fvip/4/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgXZLJuhOzQqixcUs3XQ7lx6Eh1BUgbQ8-NRAcY1xz7vYCIQC0_VrH1es7NUmzJTiViVchK8tHWcdLy3LEjD7PL4Wp3A%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhAMkwbXHaBkz397AipQwhUgdd_2WCFqHM4YduFOcq0eW2AiEA1Ku0eELtRwZy7CyQKZmZrXKBkNB2nLRt4R5A1X0b4sQ%3D'
[download] Sam Bowne\Sam Bowne - 20170425 - CNIT 126 12 - Covert Malware Launching.f251.webm has already been downloaded
[download] 100% of 19.67MiB
[ffmpeg] Merging formats into "Sam Bowne\Sam Bowne - 20170425 - CNIT 126 12 - Covert Malware Launching.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Sam Bowne\Sam Bowne - 20170425 - CNIT 126 12 - Covert Malware Launching.f302.webm" -i "file:Sam Bowne\Sam Bowne - 20170425 - CNIT 126 12 - Covert Malware Launching.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:Sam Bowne\Sam Bowne - 20170425 - CNIT 126 12 - Covert Malware Launching.temp.mkv"
ERROR: Conversion failed!
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 2075, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\postprocessor\ffmpeg.py", line 523, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

[ffmpeg] Adding metadata to 'Sam Bowne\Sam Bowne - 20170425 - CNIT 126 12 - Covert Malware Launching.mkv'
ERROR: [WinError 2] The system cannot find the file specified: 'Sam Bowne\\Sam Bowne - 20170425 - CNIT 126 12 - Covert Malware Launching.mkv'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 1045, in __process_iterable_entry
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 907, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 869, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 1654, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 2010, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\YoutubeDL.py", line 2075, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\postprocessor\ffmpeg.py", line 509, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\postprocessor\ffmpeg.py", line 210, in run_ffmpeg_multiple_files
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpmwcir7fk\build\youtube_dl\postprocessor\ffmpeg.py", line 210, in <genexpr>
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Sam Bowne\\Sam Bowne - 20170425 - CNIT 126 12 - Covert Malware Launching.mkv'

## Description

WRITE DESCRIPTION HERE
Hello. For some YouTube videos on some channels, both parts of the video are downloaded fine, but there's an issue during merging.
I am also getting an error about xsrf token.

**Comment by CEOGavin** [comment]
Same error.

**Comment by kikuyan** [comment]
_xsrf token extraction was improved with version 2020.12.22, so I write about ffmpeg error._

Selected video format 302 seems to be broken. You need to try another format. (Audio format 251 might be broken, too.)

This is where the error reported:

> [ffmpeg] Merging formats into "Sam Bowne\Sam Bowne - 20170425 - CNIT 126 12 - Covert Malware Launching.mkv"
> [debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Sam Bowne\Sam Bowne - 20170425 - CNIT 126 12 - Covert Malware Launching.f302.webm" -i "file:Sam Bowne\Sam Bowne - 20170425 - CNIT 126 12 - Covert Malware Launching.f251.webm" -c copy -map "0:<span></span>v:0" -map "1:<span></span>a:0" "file:Sam Bowne\Sam Bowne - 20170425 - CNIT 126 12 - Covert Malware Launching.temp.mkv"
> ERROR: Conversion failed!

If you run above ffmpeg manually, you'll see the error like this:

> [webm @ 0x7ffad3800c00] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5350 >= 5333

If you directly run ffmpeg with the mpd url like `ffmpeg -i mpd-url -map 0:v:11 -an -c copy f302.webm`, you'll see the error like this: (`-map 0:v:11` corrensponds to video format 302 with that mpd url)

> [dash @ 0x7fdad8000000] DTS 5333 < 5350 out of order
> [webm @ 0x7fdad915cc00] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5357 >= 5340
