### ISSUE TITLE
ERROR: 9A5m4OiF6jE: YouTube said

### ISSUE THREAD

**Issue by Villelmo** [ytdl-org/youtube-dl#27387]
## Checklist

- [x ] I've verified that I'm running youtube-dl version **2020.12.12**
- [x] I'm reporting a broken site support issue
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --audio-format mp3  -x https://youtu.be/9A5m4OiF6jE
[youtube] 9A5m4OiF6jE: Downloading webpage
ERROR: 9A5m4OiF6jE: YouTube said: Unable to extract video data
```

## Description

WRITE DESCRIPTION HERE

Unable to extract video data

**Comment by Silent-Hunter** [comment]
I am having this issue as well, same version, same URL. I checked and it does work in Vivaldi browser, in a private browsing window so I'm not logged into YouTube.

**Comment by KaustubhRai** [comment]
I was having the same issue, but I upgraded the youtube-dl version and it started working. in my case _pip install --upgrade youtube-dl_

**Comment by Villelmo** [comment]
Ready!
