### ISSUE TITLE
General git question, git pull, please commit your changes or stash them ...

### ISSUE THREAD

**Issue by SweDennis** [ytdl-org/youtube-dl#27394]
Hi,

in using youtube-dl, I update via git, as in git pull -C <directory>

At times I get an:

error: Your local changes to the following files would be overwritten by merge:
	README.md
	docs/supportedsites.md
Please commit your changes or stash them before you merge.
Aborting

I usually just rm -rf <directory> when this happens, followed by a new git clone, but I realize there's a better way, I just don't know how git works, so am asking a general question.

Regards and many thanks for your help,
/Dennis

**Comment by dstftw** [comment]
This is youtube-dl issue tracker not a general programming forum. Read some doc on git.
