### ISSUE TITLE
Add option to pull partial playlist.

### ISSUE THREAD

**Issue by jonyg80** [ytdl-org/youtube-dl#27415]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2020.12.12**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

When pulling large playlist it takes huge time to pull whole playlist and sometimes server get into error. So, please add option to pull only some page of playlist not the whole playlist.

**Comment by remitamine** [comment]
Already supported(support depends on the website, ex: DailyMotion Playlists, VK User Videos, etc...).

**Comment by jonyg80** [comment]
@remitamine is this supported on pornhub ? If yes how to use it ?
