### ISSUE TITLE
feature request: support downloading subtitles on zdf mediathek

### ISSUE THREAD

**Issue by warichnict** [ytdl-org/youtube-dl#27414]
hi,

this is a feature request so i ignore your bug template, if i miss something please let me know and i  add it.

Your software makes a grate job downloading video and audio (even with multiple audio streams) and merging them to mkv files, but even if i add options like --all-subs its ignoring them.

for example 

https://www.zdf.de/kinder/eine-lausige-hexe/drei-unmoeglichkeiten-100.html

downloads the video, and if i open it in browser i am able to see some XHR requestfor the subs:

https://utstreaming.zdf.de/mtt/tivi/20/09/200908_staffel4_drei_unmoeglichkeiten_elh/3/F1027391_hoh_deu_Eine_lausige_Hexe_Die_drei_Unmoeglichkeiten_261020.xml

but it is not done by the python thingy, so please add support for downloading and embedding them to the mkv.

thanks in advance and keep up the good work

**Comment by dstftw** [comment]
```
> py -3.7 .\youtube_dl\__main__.py https://www.zdf.de/kinder/eine-lausige-hexe/drei-unmoeglichkeiten-100.html --list-su
[ZDF] drei-unmoeglichkeiten-100: Downloading webpage
[ZDF] drei-unmoeglichkeiten-100: Downloading JSON content
[ZDF] drei-unmoeglichkeiten-100: Downloading JSON metadata
[ZDF] drei-unmoeglichkeiten-100: Downloading m3u8 information
[ZDF] drei-unmoeglichkeiten-100: Downloading m3u8 information
[ZDF] drei-unmoeglichkeiten-100: Downloading f4m manifest
[ZDF] drei-unmoeglichkeiten-100: Downloading f4m manifest
Available subtitles for drei-unmoeglichkeiten-100:
Language formats
deu      vtt, xml
```

**Comment by warichnict** [comment]
hey it works, but why dosnt it work with my ytdl file containing:

```youtube-dl --all-subs --write-auto-sub --write-info-json --hls-use-mpegts "$@"```

in bash to spare me entering all this, i thought --write-auto-sub is a addition and not a substraction of things to load and using youtube urls it is, its either unclear documented or a bug together with zdf extractor, so please fix this.

thanks in advance and keep up the good work
