### ISSUE TITLE
option --keep-video / -k should not imply --keep-fragments

### ISSUE THREAD

**Issue by smujohnson** [ytdl-org/youtube-dl#27424]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
C:\tmp\youtube-dl>youtube-dl -v -k -x kdOD9N_gsN8 --audio-format mp3
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-k', '-x', 'kdOD9N_gsN8', '--audio-format', 'mp3']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[youtube] kdOD9N_gsN8: Downloading webpage
[youtube] {18} signature length 102, html5 player 03226028
[youtube] kdOD9N_gsN8: Downloading player https://www.youtube.com/s/player/03226028/player_ias.vflset/en_US/base.js
[youtube] {137} signature length 102, html5 player 03226028
[youtube] {248} signature length 106, html5 player 03226028
[youtube] kdOD9N_gsN8: Downloading player https://www.youtube.com/s/player/03226028/player_ias.vflset/en_US/base.js
[youtube] {136} signature length 106, html5 player 03226028
[youtube] {247} signature length 102, html5 player 03226028
[youtube] {135} signature length 106, html5 player 03226028
[youtube] {244} signature length 106, html5 player 03226028
[youtube] {134} signature length 102, html5 player 03226028
[youtube] {243} signature length 106, html5 player 03226028
[youtube] {133} signature length 102, html5 player 03226028
[youtube] {242} signature length 106, html5 player 03226028
[youtube] {160} signature length 102, html5 player 03226028
[youtube] {278} signature length 102, html5 player 03226028
[youtube] {140} signature length 102, html5 player 03226028
[youtube] {249} signature length 106, html5 player 03226028
[youtube] {250} signature length 106, html5 player 03226028
[youtube] {251} signature length 102, html5 player 03226028
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r6---sn-nx5e6nez.googlevideo.com/videoplayback?expire=1607934083&ei=I8zWX8POHcGskgbl9bzACQ&ip=208.78.42.28&id=91d383f4dfe0b0df&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=2I&mm=31%2C26&mn=sn-nx5e6nez%2Csn-n4v7knl6&ms=au%2Conr&mv=m&mvi=6&pl=24&gcr=ca&initcwndbps=1551250&vprv=1&mime=video%2Fwebm&ns=YFU2hHkTEbchsmrZ69oiTskF&gir=yes&clen=12600013&dur=254.160&lmt=1592384863335715&mt=1607911975&fvip=3&keepalive=yes&beids=9466585&c=WEB&txp=1311222&n=S7vsjGLzGGQzH3yxq&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMPWE_W4FV5QSz0zvXOcMryuOX-IM_zQk0ESI86ukq0GAiAf8W37wTjtf9ApvcURzNyIpDSWAU_BULuYqax-VCwxpg%3D%3D&sig=AOq0QJ8wRQIgQG9hqKfiPcMSKQr9PWrS-ZV10zuwxHxSJyaYi9U4mgoCIQDgArrz8MYMTi-NkJfIFUBeiWs4QKF3ggO5yeUN8SSsSw==&ratebypass=yes'
[download] Destination: Shadilay (Italian Version)-kdOD9N_gsN8.f248.webm
[download] 100% of 12.02MiB in 00:02
[debug] Invoking downloader on 'https://r6---sn-nx5e6nez.googlevideo.com/videoplayback?expire=1607934083&ei=I8zWX8POHcGskgbl9bzACQ&ip=208.78.42.28&id=91d383f4dfe0b0df&itag=251&source=youtube&requiressl=yes&mh=2I&mm=31%2C26&mn=sn-nx5e6nez%2Csn-n4v7knl6&ms=au%2Conr&mv=m&mvi=6&pl=24&gcr=ca&initcwndbps=1551250&vprv=1&mime=audio%2Fwebm&ns=YFU2hHkTEbchsmrZ69oiTskF&gir=yes&clen=4095652&dur=254.201&lmt=1592384840115648&mt=1607911975&fvip=3&keepalive=yes&beids=9466585&c=WEB&txp=1311222&n=S7vsjGLzGGQzH3yxq&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKWFpITGZZMCIO5WCu5Rko6lt9i19A1c6yEyClve66jIAiEA1LusSKJdFq_Sa55vCH5dK_FsH42QG14aCLDNUYe4dkI%3D&sig=AOq0QJ8wRAIgOr6nZ10vERCDw1vBtBZED5KmB7OgJj3ySvGnzQg68BkCIE2CRGwWO3l9LZ9zo21RnERiLRfwWJfH8BUN9_I_lFxo&ratebypass=yes'
[download] Destination: Shadilay (Italian Version)-kdOD9N_gsN8.f251.webm
[download] 100% of 3.91MiB in 00:00
[ffmpeg] Merging formats into "Shadilay (Italian Version)-kdOD9N_gsN8.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Shadilay (Italian Version)-kdOD9N_gsN8.f248.webm" -i "file:Shadilay (Italian Version)-kdOD9N_gsN8.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:Shadilay (Italian Version)-kdOD9N_gsN8.temp.webm"
[debug] ffmpeg command line: ffprobe -show_streams "file:Shadilay (Italian Version)-kdOD9N_gsN8.webm"
[ffmpeg] Destination: Shadilay (Italian Version)-kdOD9N_gsN8.mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Shadilay (Italian Version)-kdOD9N_gsN8.webm" -vn -acodec libmp3lame "-q:a" 5 "file:Shadilay (Italian Version)-kdOD9N_gsN8.mp3"

## Description

WRITE DESCRIPTION HERE

youtube-dl's -k or --keep-video automatically behaves as if --keep-fragments were set, whereas IMO it should not keep fragments because you didn't tell it to.

In practical English if I want to keep the video *and* convert to an audio file with -x -k, it automatically keeps the fragments of the video (that I do not want) when I believe it should simply output 2 files instead of >= 4 with the fragments.

<pre>
C:\tmp\youtube-dl>dir
 Volume in drive C has no label.
 Volume Serial Number is 821E-C60C

 Directory of C:\tmp\youtube-dl

12/13/2020  06:21 PM    <DIR>          .
12/13/2020  06:21 PM    <DIR>          ..
06/17/2020  01:07 AM        12,600,013 Shadilay (Italian Version)-kdOD9N_gsN8.f248.webm
06/17/2020  01:07 AM         4,095,652 Shadilay (Italian Version)-kdOD9N_gsN8.f251.webm
06/17/2020  01:07 AM         4,140,261 Shadilay (Italian Version)-kdOD9N_gsN8.mp3
06/17/2020  01:07 AM        16,695,929 Shadilay (Italian Version)-kdOD9N_gsN8.webm
               4 File(s)     37,531,855 bytes
               2 Dir(s)  63,628,914,688 bytes free
</pre>

4 files, not 2.

**Comment by dstftw** [comment]
These are not fragments in the first place.

**Comment by smujohnson** [comment]
Well is there a way to stop it from doing that?  Those f* files are not needed.  Need I wrote another suggestion / issue?
