### ISSUE TITLE
Mediaset - Mediasetplay not working on movies

### ISSUE THREAD

**Issue by glucini** [ytdl-org/youtube-dl#27439]
## Checklist

- [ X] I'm reporting a broken site support
- [ X] I've verified that I'm running youtube-dl version **2020.12.14**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.mediasetplay.mediaset.it/movie/ilaureati/i-laureati_F006683801000101', '--verbose', '--ignore-config']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.12
[debug] Python version 3.7.3 (CPython) - Linux-5.9.14-rockchip64-aarch64-with-debian-10.7
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[Mediaset] F006683801000101: Downloading JSON metadata
[Mediaset] F006683801000101: Downloading MPEG4 SD SMIL data
[Mediaset] F006683801000101: Downloading MPEG4 HD SMIL data
ERROR: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/mediaset.py", line 157, in _real_extract
    raise first_e
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/mediaset.py", line 147, in _real_extract
    }), guid, 'Downloading %s %s SMIL data' % (f.split('+')[0], asset_type))
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/theplatform.py", line 52, in _extract_theplatform_smil
    error_element.attrib['abstract'], expected=True)
youtube_dl.utils.ExtractorError: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences

```

## Description

In the last days, all movies from Mediaset/Mediasetplay do not download. They play properly in the browser.

**Comment by nixxo** [comment]
DRM protected

**Comment by AntsyBoi** [comment]
I know I'm late to this thread but I was able to fix it by calling to the youtube-dl servers.
 `youtube-dl https://www.crunchyroll.com/rent-a-girlfriend/episode-1-rent-a-girlfriend-796247 --all-subs --call-home`
It takes a little long to download but it downloads it perfectly.
Sorry if this isn't what you're looking for.

**Comment by ale5000-git** [comment]
I'm not sure if it possible but in cases youtube-dl is used by a player (like MPC-HC or VLC) isn't possible to pass all info needed for DRM and leave the task of decryption to the player?

**Comment by dirkf** [comment]
Making such info available would rather defeat the security-by-obscurity principle on which DRM operates.
