### ISSUE TITLE
Urplay.se not working since Sept 2020

### ISSUE THREAD

**Issue by Minherre** [ytdl-org/youtube-dl#27430]
- [x] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.12.14**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

URPlay.se har been broken since at least September 2020.

https://urplay.se/program/219630-historia-forklarad-franska-revolutionen

"[12/14/20 07:16:02] ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))"

Before Youtube-DL was shut down here, there were some suggestions by Amigatomte, like these two:

=== 2020-10-10 ===

This was fun.. It seems urplay.se changed quite a bit. I made this new version of youtube_dl/extractor/urplay.py that works for me:
https://pastebin.com/crUVtEJS

However, I'm new here and I've never even programmed in Python before, so code suggestions are welcome. :-)

=== 2020-10-11 ===

The "urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed" error you get above is not helped by my change, but you can work around that by using the "--no-check-certificate" option until it gets fixed.

=================

Perhaps someone with the the knowledge could try to get Urplay.se to work again ?!

/Thanx!

**Comment by Minherre** [comment]
Perhaps it would HELP if you told me WHAT is wrong with my issue, before you just close it...
 
Just adding ‘Incomplete’ doesn’t exactly HELP, does it ...

**Comment by bluebirch** [comment]
I posted an issue with urplay.se as well (#28292), which was promptly closed, no explanation why.
