### ISSUE TITLE
"unable to extract xsrf token" Issue

### ISSUE THREAD

**Issue by lefoumalade451** [ytdl-org/youtube-dl#27442]
- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.12.14**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
➜  ~ youtube-dl --config-location /etc/custom.conf https://www.youtube.com/watch\?v\=Vqc_VVlLhbw
[debug] System config: []
[debug] User config: []
[debug] Custom config: [u'-U', u'--ignore-errors', u'--mark-watched', u'--geo-bypass', u'--yes-playlist', u'--output', u'/mnt/YouTube/%(uploader)%', u'--continue', u'--write-description', u'--write-info-json', u'--write-annotations', u'--cookies', u'/root/cookies.txt', u'--write-thumbnail', u'--verbose', u'--format', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', u'-s']
[debug] Command-line args: [u'--config-location', u'/etc/custom.conf', u'https://www.youtube.com/watch?v=Vqc_VVlLhbw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-13-amd64-x86_64-with-debian-10.7
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
youtube-dl is up-to-date (2020.12.14)
[youtube] Vqc_VVlLhbw: Downloading webpage
WARNING: unable to extract xsrf token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] Vqc_VVlLhbw: Marking watched
➜  ~


```

## Description

Hello!

I have a "unable to extract xsrf token" issue
Do I need to do something to fix it? Or should I wait for an update that will fix that?

Let me know if you want more details.

Many thanks!

**Comment by october262** [comment]
this link - https://www.youtube.com/watch?v=Vqc_VVlLhbw works ok for me

**Comment by Lynxy** [comment]
This happens on every single video for me. Tested from over 100 videos downloaded today with most recent version.
