### ISSUE TITLE
Spotify Video Support

### ISSUE THREAD

**Issue by Resolver210** [ytdl-org/youtube-dl#27443]
## Checklist

- [ maybe, new feature for spotify] I'm reporting a new site support request
- [ x] I've verified that I'm running youtube-dl version **2020.12.14**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ ?maybe] I've checked that none of provided URLs violate any copyrights
- [x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

https://open.spotify.com/episode/4k7JHPCLoCmSlZY9tvme0s

## Description

I believe with a certain piece of media now being solely available on Spotify this will be a very requested issue.
I am specifically asking about the Joe Rogan Podcast which is being hosted through Spotify as a video.

**Comment by selfisekai** [comment]
uses DRM protection
![image](https://user-images.githubusercontent.com/11798442/104120097-8170f300-5334-11eb-88f7-9c9040d28f8e.png)

**Comment by Vangelis66** [comment]
> uses DRM protection

... as well as **everything else** streamable on _Spotify_ 😠

**Comment by Thinkscape** [comment]
I don't believe 55a3ca1 added support for this, so this issue should not be closed yet.

**Comment by Rubbesh** [comment]
❤️

**Comment by TomArrow** [comment]
Any updates on this? I'm getting a getaddrinfo failed. Do I need to use cookies?

**Comment by ewtoombs** [comment]
This implementation has broken almost immediately. `anon-podcast.scdn.co` no longer exists according to DNS. That can't be solved with cookies, @TomArrow . Either this needs reopening or a new issue.

**Comment by TomArrow** [comment]
Ah, thanks for the info. Can we reopen it then? Unless it's better for the devs to make a new one? I don't know what's best.

**Comment by ewtoombs** [comment]
Well, it worked, and now it doesn't, so maybe it should be a new issue...

**Comment by ewtoombs** [comment]
@remitamine implemented it. Maybe they have a preference lol

**Comment by ewtoombs** [comment]
Actually, it looks like the entire scdn.co domain is gone.
```

; <<>> DiG 9.16.18 <<>> scdn.co
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52901
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;scdn.co.			IN	A

;; AUTHORITY SECTION:
scdn.co.		300	IN	SOA	ns2.spotify.com. dns-admin.spotify.com. 2019120053 3600 900 3628800 300

;; Query time: 20 msec
;; SERVER: 10.4.0.1#53(10.4.0.1)
;; WHEN: Wed Jul 07 13:18:19 EDT 2021
;; MSG SIZE  rcvd: 97
```

**Comment by fossdd** [comment]
Did you guys opened a new issue or is nothing new happend?

**Comment by TomArrow** [comment]
Yeah sorry, I didn't pursue this any further. Always have 1000 things on my mind. Be happy if anyone else takes it from here.
