### ISSUE TITLE
BBC YouTube-DL Issue

### ISSUE THREAD

**Issue by WCityMike** [ytdl-org/youtube-dl#27448]
[debug] System config: [u'-o', u'~/Desktop/%(title)s.%(ext)s']
[debug] User config: [u'-f', u'best', u'-i']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.bbc.com/news/av/world-us-canada-55153976']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3, rtmpdump 2.4
[debug] Proxy map: {}
[bbc] world-us-canada-55153976: Downloading webpage
[bbc] p090695w: Downloading media selection XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 1161, in _real_extract
    parse_media(try_get(resp, lambda x: x['data']['initialItem']['mediaItem'], dict))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 1150, in parse_media
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by october262** [comment]
youtube-dl https://vod-dash-ww-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/39274b-p090695w/vf_p090695w_506ac3f7-384f-48e3-bef9-9ea1ca36c43b.ism/pc_hd_abr_v2_dash_master.mpd?__gda__=1608122018_bec9eb9693f6e0e56402623f4f00fbaa

**Comment by WCityMike** [comment]
If I paste that in, 'requested format not available'.  Additionally, the original verbose output that I pasted in seems to indicate that youtube-dl has a 'bbc' extractor that is not working in this case.

**Comment by october262** [comment]
retry with youtube-dl --no-part --restrict-filenames https://vod-dash-ww-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/39274b-p090695w/vf_p090695w_506ac3f7-384f-48e3-bef9-9ea1ca36c43b.ism/pc_hd_abr_v2_dash_master.mpd?__gda__=1608122018_bec9eb9693f6e0e56402623f4f00fbaa  see if this works.

**Comment by WCityMike** [comment]
This doesn't seem to be a duplicate of anything, nor does the solution seem to have been resolved.

**Comment by WCityMike** [comment]
https://github.com/ytdl-org/youtube-dl/pull/23415
https://github.com/ytdl-org/youtube-dl/issues/27125
https://github.com/ytdl-org/youtube-dl/issues/23232
