### ISSUE TITLE
Does youtube-dl support to download videos from Kwai(快手)？

### ISSUE THREAD

**Issue by zengqingfu1442** [ytdl-org/youtube-dl#27441]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Does youtube-dl support to download videos from Kwai(https://kwai.com 快手)？

**Comment by therealvkr** [comment]
Yes it does .. 
http://dlvnow.ga
