### ISSUE TITLE
DownloadError: YouTube

### ISSUE THREAD

**Issue by CamCub** [ytdl-org/youtube-dl#27444]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.12.14**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

DownloadError: ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

My video URL is:  https://youtu.be/sidalc8fQc8

I am following the instructions in the above error message and am a new user.    Thanks

**Comment by remitamine** [comment]
Private video, [use authenticated cookies](https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl).
