### ISSUE TITLE
-o option not working properly for thumbnails download

### ISSUE THREAD

**Issue by InigoGutierrez** [ytdl-org/youtube-dl#27459]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[taamas@Quercus]~$ youtube-dl -v --skip-download --write-thumbnail -o - https://www.youtube.com/watch?v=ucn2KzCDnOY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--skip-download', '--write-thumbnail', '-o', '-', 'https://www.youtube.com/watch?v=ucn2KzCDnOY']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.9.1 (CPython) - Linux-5.4.80-2-lts-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] ucn2KzCDnOY: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[youtube] ucn2KzCDnOY: Downloading thumbnail ...
[youtube] ucn2KzCDnOY: Writing thumbnail to: -.webp
```

## Description

First, the manual says that specifying `-` as the output template makes youtube-dl output to stdout instead of writing to a file. This works for videos (I suppose it is the only thing this option exists for) but not for images.

Second, the output file has the extension as part of its name, when it should only have the output template. This happens for other output templates, too:

```
[taamas@Quercus]~$ youtube-dl -o yay -v --skip-download --write-thumbnail https://www.youtube.com/watch?v=ucn2KzCDnOY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'yay', '-v', '--skip-download', '--write-thumbnail', 'https://www.youtube.com/watch?v=ucn2KzCDnOY']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.9.1 (CPython) - Linux-5.4.80-2-lts-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] ucn2KzCDnOY: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[youtube] ucn2KzCDnOY: Downloading thumbnail ...
[youtube] ucn2KzCDnOY: Writing thumbnail to: yay.webp
```

I wrote all this and now I realize it must be because the output template is still applied to the video that is skipped by `--skip-download` and the image is always saved to a file with the same name of the "downloaded" video + the extension so they don't collide. Even if this is intended, it would be nice if the output template was applied to the image if the download is skipped.

**Comment by dstftw** [comment]
Both are expected behavior.
