### ISSUE TITLE
WARNING: video doesn't have subtitles (Videos with auto subs)

### ISSUE THREAD

**Issue by EthanSK** [ytdl-org/youtube-dl#27454]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--skip-download', '--write-auto-sub', 'https://www.youtube.com/watch?v=qfJthDvcZ08']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.9.1 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] qfJthDvcZ08: Downloading webpage
[youtube] qfJthDvcZ08: Looking for automatic captions
WARNING: Couldn't find automatic captions for qfJthDvcZ08
[debug] Default format spec: bestvideo+bestaudio/best
```

## Description

Subs cannot be downloaded at all on videos with auto generated subs. I just get the error `WARNING: Couldn't find automatic captions for qfJthDvcZ08`. I have tried with multiple videos that have auto subs, but it doesn't work.

**Comment by HakkaTjakka** [comment]
Same

**Comment by MagTun** [comment]
Same for this video 

```
youtube-dl "https://www.youtube.com/watch?v=6esfS4lrz5I" --write-sub --write-auto-sub   --skip-download
[youtube] 6esfS4lrz5I: Downloading webpage
WARNING: video doesn't have subtitles
[youtube] 6esfS4lrz5I: Looking for automatic captions
WARNING: Couldn't find automatic captions for 6esfS4lrz5I
```

https://downsub.com/ is able to find the subtitle
