### ISSUE TITLE
Is it possible to use local HTML file as an argument (instead of providing URL)?

### ISSUE THREAD

**Issue by mnalevanko** [ytdl-org/youtube-dl#27458]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

I am wondering if I could run youtube-dl using a path to a local HTML file instead of providing the URL.
Thank you.

**Comment by remitamine** [comment]
no, it's not supported.
