### ISSUE TITLE
ITV Hub " HTTP Error 403: Forbidden" / "No video formats found"

### ISSUE THREAD

**Issue by TCCalvin** [ytdl-org/youtube-dl#27453]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

youtube-dl.exe -f best -a list.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '-a', 'list.txt', '--verbose']
[debug] Batch file urls: ['https://www.itv.com/hub/classic-coronation-street/1a0694a4196', 'https://www.itv.com/hub/classic-coronation-street/1a0694a4197', 'https://www.itv.com/hub/classic-emmerdale/Ya0524a2344', 'https://www.itv.com/hub/classic-emmerdale/Ya0524a2345']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 3.1.5, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 25.189.10.60 (GB) as X-Forwarded-For.
[ITV] 1a0694a4196: Downloading webpage
[ITV] 1a0694a4196: Downloading JSON metadata
[ITV] 1a0694a4196: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\extractor\itv.py", line 115, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\extractor\common.py", line 1367, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
PASTE VERBOSE LOG HERE
```

## Description

Videos sometimes download but often fail with " HTTP Error 403: Forbidden" and "No video formats found"

**Comment by dstftw** [comment]
Does not play in browser.

**Comment by TCCalvin** [comment]
This plays fine for me in Chrome and Firefox.  Also if you repeatedly run the youtube-dl command, it EVENTUALLY works.

**Comment by TCCalvin** [comment]
Can you re-open this, as it's not invalid and shouldn't be closed.

Tested on multiple machines.  Same thing, sometimes downloads, sometimes fails.

Always open fine first time in Chrome and Firefox.
