### ISSUE TITLE
NRK support broken

### ISSUE THREAD

**Issue by TheNorwegian** [ytdl-org/youtube-dl#27456]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.12.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

Beginning download, this box will output progress
Youtube-DL has been found and set
Generating output directory structure
The output was generated and will be used
The quality and format has been set
Looking for ffmpeg
ffmpeg was found
Arguments have been generated and are readonly in the textbox
Creating download thread
Created, starting download thread
[NRKTVEpisode] atlantic-crossing/sesong/1/episode/1: Downloading webpage
[NRK] KMTE40007115: Downloading manifest JSON
Error:
ERROR: NRK said: Ikke tilgjengelig utenfor Norge

An error occured
```
PASTE VERBOSE LOG HERE
```

## Description

I am trying to download from NRK.no but since the summer this has not been possible. I have used youtube-dl from within Youtube-DLG as well as Youtube-DL-GUI and always updated to the latest youtube-dl file, for example today. Neither GUIs work to grab files from NRK, though they do work to grab MP4 files from SVT.se which is the other site I download from. So the softwares work but it seems the engine, youtube-dl is not able anymore with NRK.no

In the error message it says: Ikke tilgjengelig utenfor Norge - which means not available outside Norway. This was always the case before in theory; they had geoblocked content all the time but Youtube-DLG and Youtube-DL-GUI could always fetch content as long as the youtube-dl exe was updated. Not anymore. I am in Sweden which is why I need the softwares to get NRK content.

Using Win7. The problem started aprox. august. 

WRITE DESCRIPTION HERE

**Comment by TheNorwegian** [comment]
Example of  a video/file I am trying to get:

https://tv.nrk.no/serie/atlantic-crossing/sesong/1/episode/1/avspiller

**Comment by remitamine** [comment]
```
youtube-dl https://tv.nrk.no/serie/atlantic-crossing/sesong/1/episode/1/avspiller
[NRKTVEpisode] atlantic-crossing/sesong/1/episode/1: Downloading webpage
[NRK] KMTE40007115: Downloading manifest JSON
[NRK] KMTE40007115: Downloading m3u8 information
[NRK] KMTE40007115: Downloading metadata JSON
[download] Destination: 1. Angrepet-KMTE40007115.mp4
...
```

**Comment by remitamine** [comment]
> Ikke tilgjengelig utenfor Norge

use a VPN or proxy.

**Comment by TheNorwegian** [comment]
Rremitamine, are you using a GUI to get that file?

**Comment by remitamine** [comment]
no, using the command line.

> In the error message it says: Ikke tilgjengelig utenfor Norge - which means not available outside Norway. This was always the case before in theory; they had geoblocked content all the time but Youtube-DLG and Youtube-DL-GUI could always fetch content as long as the youtube-dl exe was updated. Not anymore. I am in Sweden which is why I need the softwares to get NRK content.

it's a workaround that can stop working at any time.

**Comment by TheNorwegian** [comment]
Ok. Well, I never figured out how to use the command line. Trying to run youtube-dl from the exe just flashes a dos-like window and half a second later it's gone. Any quick comment to get me in the right direction?

**Comment by remitamine** [comment]
as i said, you have to a VPN or proxy to be able to download this video, it doesn't matter if you're using the command line or a GUI.

**Comment by TheNorwegian** [comment]
Right, thanks for that suggestion. I got a vpn and tried again, and it now works. I didn't seriously consider that option because the softwares always worked without a vpn in the past.
