### ISSUE TITLE
Youtube-dl seems to report wrong version

### ISSUE THREAD

**Issue by london111** [ytdl-org/youtube-dl#27457]
I just wanted to report a bug (that youtube-dl reports "Unable to extract video data" on youtube), but when I tried to follow the bug report checklist, I noticed that pip reports another version of youtube-dl than youtube-dl itself:

```
sudo pip3 install youtube-dl 
Collecting youtube-dl
  Using cached youtube_dl-2020.12.14-py2.py3-none-any.whl (1.8 MB)
Installing collected packages: youtube-dl
Successfully installed youtube-dl-2020.12.14
```

```
youtube-dl -v --version
2020.06.16.1
```

What's wrong here? If I have indeed the wrong version how could I fix it?

**Comment by remitamine** [comment]
you have other versions installed, remove them.

**Comment by london111** [comment]
No, I don't think so: Did the following to check it: 

```
sudo pip3 uninstall youtube-dl
cd /
fdfind  youtube-dl
```
The last command results in no output.

```
sudo pip3 install youtube-dl 
Collecting youtube-dl
  Using cached youtube_dl-2020.12.14-py2.py3-none-any.whl (1.8 MB)
Installing collected packages: youtube-dl
Successfully installed youtube-dl-2020.12.14
```

```
fdfind youtube-dl
usr/local/bin/youtube-dl
usr/local/etc/bash_completion.d/youtube-dl.bash-completion
usr/local/share/man/man1/youtube-dl.1
usr/local/etc/fish/completions/youtube-dl.fish

```

```
which youtube-dl
/usr/local/bin/youtube-dl
```

```
youtube-dl --version
2020.06.16.1
```

```
/usr/local/bin/youtube-dl --version
2020.06.16.1
```

**Comment by remitamine** [comment]
when i'm saying other versions, i mean installed with other methods(system package manager, direct install, etc...) accessible from the system `PATH`.

**Comment by london111** [comment]
I don't remember that I installed other versions. Do you have any suggestions of how I could check if there are any other versions and where they are (except what I already tried above)?

**Comment by remitamine** [comment]
there are lots of methods to install youtube-dl depending on the system, if you installed youtube-dl using the method described in https://github.com/ytdl-org/youtube-dl#installation, then you can just delete the file `/usr/local/bin/youtube-dl`.

**Comment by london111** [comment]
Thanks, that gives me a workaround:

```
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```
This overwrites the version installed by pip with the current version. 

However I don't think that the issue is invalid. I still think, that pip installs another version than it reports.

**Comment by remitamine** [comment]
i don't know what distribution you're using, but in my system(ArchLinux) pip does not install youtube-dl binary to `/usr/local/bin/youtube-dl` instead it's installed to `/usr/bin/youtube-dl`.

**Comment by london111** [comment]
I am using ubuntu 20.04
