### ISSUE TITLE
ITVHUB

### ISSUE THREAD

**Issue by KiaN2020** [ytdl-org/youtube-dl#27463]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

is there anyway to grab higher video than 504p from ITVHUB?

Thank You.

**Comment by emdubya77** [comment]
@KiaN2020 no there isn't. Apparently HD versions are protected by DRM.
