### ISSUE TITLE
YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by msimoes99** [ytdl-org/youtube-dl#27477]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Have tried downloading audio file from YouTube and presented with the error "YouTube said: Unable to extract video data"
Have noticed no update or FAQ on this. Run on Mac utilizing HomeBrew, everything is up to date -- what should be done to resolve issue?

This is the command I have been using "youtube-dl -x --audio-format mp3 URL" 

or can you please link me to the issue that was already resolved that I didn't happen to find?

**Comment by grenudi** [comment]
Same here..
@msimoes99 , have you been able to find solution to the problem ? 

I've used youtube-dl in my scripts, now they just don't work:
```
youtube-dl --cookies ~/cookies/youtube.txt https://www.youtube.com/watch?v=ML2gncutAJQ 
[youtube] ML2gncutAJQ: Downloading webpage
ERROR: ML2gncutAJQ: YouTube said: Unable to extract video data
```
I even used cookie..

**Comment by grenudi** [comment]
@dstftw , Can you please point out what issue this one is duplicating ?

**Comment by grenudi** [comment]
> @dstftw , Can you please point out what issue this one is duplicating ?

@dstftw @msimoes99 

duplicate of this , I guess #27457

It helped me, in any way
