### ISSUE TITLE
YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by msimoes99** [ytdl-org/youtube-dl#27474]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Have tried downloading audio file from YouTube and presented with the error "YouTube said: Unable to extract video data"
Have noticed no update or FAQ on this. Run on Mac utilizing HomeBrew, everything is up to date -- what should be done to resolve issue?

This is the command I have been using "youtube-dl -x --audio-format mp3 URL"

**Comment by grenudi** [comment]
@msimoes99  #27457
