### ISSUE TITLE
[ADN] How to get the subtitle encryption key now that the site has been modified?

### ISSUE THREAD

**Issue by Gaby13627** [ytdl-org/youtube-dl#27472]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi there,

I would like to download the subtitles of the videos from the ADN site
To download the subtitles of Adn videos it was necessary to retrieve the encryption key of the subtitles which changes every day. To do this we use the following command in the console of our browser:

`window.videojs.players["adn-video-js"].onChromecastCustomData().key`

But recently ADN has had to change part of its code because this technique no longer works. I would like to know if someone has another method to obtain this key. Or a method to download the subtitles.

Thank you.

**Comment by remitamine** [comment]
for now, obtaining the key is not the main problem, even if you get the key, you won't be able to use it with youtube-dl, ADN made changes that broke the extraction of the subtiles and video URLs, this need to fixed first.
