### ISSUE TITLE
youtube-dl cookies doesn't recognize account for downloading members only videos

### ISSUE THREAD

**Issue by DatPlumpBoi** [ytdl-org/youtube-dl#27480]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\AhuraMazda>youtube-dl -v --cookies youtubecookies.txt https://www.youtube.com/watch?v=ZJ8UtgY0GWc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'youtubecookies.txt', 'https://www.youtube.com/watch?v=ZJ8UtgY0GWc']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] ZJ8UtgY0GWc: Downloading webpage
ERROR: This video is available to this channel's members on level: MemberShrimp! (or any higher level). Join this channel to get access to members-only content and other exclusive perks.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\extractor\youtube.py", line 2062, in _real_extract
youtube_dl.utils.ExtractorError: This video is available to this channel's members on level: MemberShrimp! (or any higher level). Join this channel to get access to members-only content and other exclusive perks.
```

## Description

Hi so i used to can download members only videos with no issues, but suddenly today the command didnt seem to recognize the account in the cookies that i put in, using --username and --password doesnt do anything, is there something wrong in the cookies i use, i always useget cookies.txt for this and it works the last time hopefully someone can help me on this....

**Comment by Lytexx** [comment]
Still works for me

> [youtube] ZJ8UtgY0GWc: Downloading webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: [The Emperor's New Groove] Watch with me!-ZJ8UtgY0GWc.f299.mp4
[download] 100% of 1.05GiB in 02:41
[download] Destination: [The Emperor's New Groove] Watch with me!-ZJ8UtgY0GWc.f251.webm
[download] 100% of 64.78MiB in 00:10
[ffmpeg] Merging formats into "[The Emperor's New Groove] Watch with me!-ZJ8UtgY0GWc.mkv"

make sure you are using youtube-dl in the folder your cookies file is in

**Comment by DatPlumpBoi** [comment]
OH I GOT IT! i didnt specify the location of the cookies file!when i specifiy in the command line like this : >youtube-dl --cookies D:\DONLOT\dammit.txt it works! i thought youtube-dl can find the cookies file by itself but i guess there's a problem with it thank you very much!!!

**Comment by Dominatorrrr** [comment]
please show a tutorial about how to download youtube members only content in youtube dl,step by step

**Comment by Dominatorrrr** [comment]
> Still works for me
> 
> > [youtube] ZJ8UtgY0GWc: Downloading webpage
> > WARNING: Requested formats are incompatible for merge and will be merged into mkv.
> > [download] Destination: [The Emperor's New Groove] Watch with me!-ZJ8UtgY0GWc.f299.mp4
> > [download] 100% of 1.05GiB in 02:41
> > [download] Destination: [The Emperor's New Groove] Watch with me!-ZJ8UtgY0GWc.f251.webm
> > [download] 100% of 64.78MiB in 00:10
> > [ffmpeg] Merging formats into "[The Emperor's New Groove] Watch with me!-ZJ8UtgY0GWc.mkv"
> 
> make sure you are using youtube-dl in the folder your cookies file is in

please show a tutorial step by step how to download youtube members only content
