### ISSUE TITLE
Youtube DL Python Youtube Music

### ISSUE THREAD

**Issue by Seregon-TheLich** [ytdl-org/youtube-dl#27509]
Good afternoon,
I have encountered a little problem;
When I try to download all the videos of an artist on youtube music (url such as: https://music.youtube.com/channel/{id}),
youtube dl starts looping without ending;
it downloads all the videos and then download it again... infinitely...
Any suggestions ?
It has not been fixed during the last 3 release.
However, Youtube Music is not in the list of supported websites so it is may be why it does not work.
I am at your disposal for more information.
Thanks for reading me.
I am using youtube dl 2020.12.22

**Comment by Seregon-TheLich** [comment]
What is missing ?

**Comment by Seregon-TheLich** [comment]
@dstftw,tanks for having read me I am sorry to mention you but I just want to know what is missing; if you try with a youtube music channel url it will not work that 's why i did not put any debugging informations.

**Comment by dstftw** [comment]
Read new issue template.

**Comment by Seregon-TheLich** [comment]
Ok, thanks for your answer, i thought i had read it carefully...
