### ISSUE TITLE
[YT] Mix playlists --yes-playlist or direct download link to mix playlist result in ERROR: This playlist type is unviewable.

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#27502]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v https://www.youtube.com/playlist?list=RDaUCGSW6SaWs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/playlist?list=RDaUCGSW6SaWs']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.9.1 (CPython) - macOS-11.1-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] RDaUCGSW6SaWs: Downloading webpage
ERROR: This playlist type is unviewable.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2020.12.14/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2020.12.14/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2020.12.14/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2020.12.14/libexec/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 3179, in _real_extract
    raise ExtractorError(alert, expected=True)
youtube_dl.utils.ExtractorError: This playlist type is unviewable.
```

## Description

Ok, so, here's a Mix playlist from YT:
**Link1:** 
https://www.youtube.com/watch?v=aUCGSW6SaWs&list=RDaUCGSW6SaWs&start_radio=1

Direct mix playlist like would be:
**Link2:**
https://www.youtube.com/playlist?list=RDaUCGSW6SaWs
And yes, it's not playable in browser by this link but playable by Link1.
Using this link results in ERROR: This playlist type is unviewable. which is correct according to current ytdl logic. 

But, if I use --yes-playlist on Link 1, I'm just getting just the first video on the playlist.

I assume, mix playlists can somehow be identified by their ID. They seem to all start with RD

A couple other links to test:
https://www.youtube.com/watch?v=m9H4kmrrDa0&list=RDm9H4kmrrDa0
https://www.youtube.com/watch?v=26nsBfLXwSQ&list=RD26nsBfLXwSQ
 
It'd be great, if Link1 worked with --yes-playlist and Link2 could be identified as playlist and extracted properly.

**Comment by dstftw** [comment]
1. Works fine.
```
>  py -3.7 .\youtube_dl\__main__.py 'https://www.youtube.com/watch?v=aUCGSW6SaWs&list=RDaUCGSW6SaWs&start_radio=1' -F --yes-pla
[youtube:tab] Downloading playlist RDaUCGSW6SaWs - add --no-playlist to just download video aUCGSW6SaWs
[youtube:tab] RDaUCGSW6SaWs: Downloading webpage
[download] Downloading playlist: Mix - Post Malone - Maintain (Unreleased)
[youtube:tab] playlist Mix - Post Malone - Maintain (Unreleased): Downloading 25 videos
[download] Downloading video 1 of 25
[youtube] aUCGSW6SaWs: Downloading webpage
[info] Available formats for aUCGSW6SaWs:
format code  extension  resolution note
249          webm       audio only tiny   58k , opus @ 50k (48000Hz), 1.49MiB
250          webm       audio only tiny   76k , opus @ 70k (48000Hz), 1.96MiB
140          m4a        audio only tiny  130k , m4a_dash container, mp4a.40.2@128k (44100Hz), 3.63MiB
251          webm       audio only tiny  145k , opus @160k (48000Hz), 3.77MiB
160          mp4        256x144    144p   25k , avc1.4d400c, 30fps, video only, 667.61KiB
278          webm       256x144    144p   25k , webm container, vp9, 30fps, video only, 697.44KiB
242          webm       426x240    240p   33k , vp9, 30fps, video only, 923.03KiB
133          mp4        426x240    240p   43k , avc1.4d4015, 30fps, video only, 1.16MiB
243          webm       640x360    360p   50k , vp9, 30fps, video only, 1.37MiB
134          mp4        640x360    360p   78k , avc1.4d401e, 30fps, video only, 2.16MiB
244          webm       854x480    480p   80k , vp9, 30fps, video only, 2.23MiB
135          mp4        854x480    480p  149k , avc1.4d401f, 30fps, video only, 4.12MiB
247          webm       1280x720   720p  263k , vp9, 30fps, video only, 7.35MiB
136          mp4        1280x720   720p  335k , avc1.64001f, 30fps, video only, 9.35MiB
248          webm       1920x1080  1080p  511k , vp9, 30fps, video only, 13.52MiB
137          mp4        1920x1080  1080p  692k , avc1.640028, 30fps, video only, 19.36MiB
18           mp4        640x360    360p  189k , avc1.42001E, 30fps, mp4a.40.2@ 96k (44100Hz), 5.30MiB (best)
[download] Downloading video 2 of 25
[youtube] ng-tPX_LdcM: Downloading webpage

ERROR: Interrupted by user
```
2. Not possible.

**Comment by someziggyman** [comment]
Wow... It turns out that if I use:
./youtube-dl -v -F --yes-playlist https://www.youtube.com/watch?v=aUCGSW6SaWs&list=RDaUCGSW6SaWs
the output is just the first video, as if --yes-playlist is ignored, **BUT** if I put the link in between double or single quotes  '' "" everything works fine line in your example. 
./youtube-dl -v -F --yes-playlist "https://www.youtube.com/watch?v=aUCGSW6SaWs&list=RDaUCGSW6SaWs"

I'm on MacOS BigSur, launching with Terminal. Same behavior on Python 2.7 and 3.9. Never happened to me before.
Do you have any idea why this may be the case? Maybe --yes-playlist somewhere requires the link to be in quotes?

**Comment by sgeklorer** [comment]
Just replicated this and yes, it works as someziggyman explained. I am on Linux Mint, date is 2024-01-12 and I have the latest yt-dlp from Dec 2023.

This fails to work, and only downloads the video file:

yt-dlp --yes-playlist --audio-format best https://www.youtube.com/watch?v=PEwLC5jZmkI&list=RDEMolkaW8R2TAZKWmYX5D5A0Q

This does work, and downloads the entire playlist:

yt-dlp --yes-playlist --audio-format best "https://www.youtube.com/watch?v=PEwLC5jZmkI&list=RDEMolkaW8R2TAZKWmYX5D5A0Q"

Only difference is the quotes. This is quite jarring as all other yt-dlp options appear to work regardless of whether the URL is quoted. Note also, that a URL cannot contain spaces (by definition) and so the quotes are completely redundant for the purposes of string and argument parsing.
