### ISSUE TITLE
[feature_request][music.youtube.com] High stream download option.

### ISSUE THREAD

**Issue by 0xAB51NTH** [ytdl-org/youtube-dl#27512]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.12.22**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Hi, Im requesting feature of downloading the AAC 256 kbps high quality youtube music stream. Im ready to provide an account with youtube premium trial that expires 22 Feb 2021.
As it was explained to me here: https://github.com/ytdl-org/youtube-dl/issues/27348
I dont know how to provide account details as I dont see that github has any in built messaging and posting them here publicly would be dumb.

**Comment by dstftw** [comment]
By mail in my profile.

**Comment by 0xAB51NTH** [comment]
> By mail in my profile.

Email with login and password has been sent. If you have any issues with account dont hesitiate to reply to the email.
(Should be fine tho, account created today and trial started also today)

**Comment by dstftw** [comment]
You must provide clear instructions on how to obtain a HQ stream with clear evidence it's actually the HQ. Link provided does not offer HQ streams.

**Comment by llacb47** [comment]
> You must provide clear instructions on how to obtain a HQ stream with clear evidence it's actually the HQ. Link provided does not offer HQ streams.

`https://support.google.com/youtubemusic/answer/9076559?hl=en`

**Comment by 0xAB51NTH** [comment]
> You must provide clear instructions on how to obtain a HQ stream with clear evidence it's actually the HQ. Link provided does not offer HQ streams.

llacb47 already provided the instruction how to turn on the HQ stream aswell as evidence that its the HQ stream (As I dont think that google would base their marketing on lies)
As for me I wanted to mess around the youtube offline download but its some weird .exo format that is encrypted for no reason (because its not like there is shit ton of tools that allow downloading from youtube)
