### ISSUE TITLE
Can't download videos from youtube

### ISSUE THREAD

**Issue by Rafiquzzaman420** [ytdl-org/youtube-dl#27517]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

I can't download youtube videos. But it is working while I was downloading videos from Vimeo. 
I got this error : 
~$ youtube-dl "https://www.youtube.com/watch?v=tLqtnGLfm4Q"
[youtube] tLqtnGLfm4Q: Downloading webpage
ERROR: tLqtnGLfm4Q: YouTube said: Unable to extract video data

I tried with different url but result is the same. My youtube-dl version is also uptodate..
Thanks in advance.

**Comment by grenudi** [comment]
@Rafiquzzaman420 

duplicate of this , I guess #27457

It helped me, in any way
