### ISSUE TITLE
Failing to download a specific file from YouTube

### ISSUE THREAD

**Issue by gballabio** [ytdl-org/youtube-dl#27513]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=wmaCl8QNWgI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.22
[debug] Python version 2.7.18 (CPython) - Linux-5.9.0-4-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.3.1-5, ffprobe 4.3.1-5, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] wmaCl8QNWgI: Downloading webpage
[youtube] {18} signature length 106, html5 player 5dd3f3b2
[youtube] {137} signature length 110, html5 player 5dd3f3b2
[youtube] {248} signature length 106, html5 player 5dd3f3b2
[youtube] {136} signature length 110, html5 player 5dd3f3b2
[youtube] {247} signature length 110, html5 player 5dd3f3b2
[youtube] {135} signature length 110, html5 player 5dd3f3b2
[youtube] {244} signature length 106, html5 player 5dd3f3b2
[youtube] {134} signature length 110, html5 player 5dd3f3b2
[youtube] {243} signature length 110, html5 player 5dd3f3b2
[youtube] {133} signature length 110, html5 player 5dd3f3b2
[youtube] {242} signature length 106, html5 player 5dd3f3b2
[youtube] {160} signature length 106, html5 player 5dd3f3b2
[youtube] {278} signature length 106, html5 player 5dd3f3b2
[youtube] {140} signature length 110, html5 player 5dd3f3b2
[youtube] {251} signature length 110, html5 player 5dd3f3b2
[youtube] wmaCl8QNWgI: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://manifest.googlevideo.com/api/manifest/dash/expire/1608691812/ei/BFziX7D3Dc_N1gK-xoqIBA/ip/79.50.206.183/id/c2668297c40d5a02/source/youtube/requiressl/yes/playback_host/r2---sn-uxaxpu5ap5-apoe.googlevideo.com/mh/fZ/mm/31%2C29/mn/sn-uxaxpu5ap5-apoe%2Csn-hpa7zned/ms/au%2Crdu/mv/m/mvi/2/pl/24/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1000000/vprv/1/mt/1608669876/fvip/4/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIhAOjwzEgq34-zM8I4elXws8PnYr6CPWYA3HgvlKMVo1HCAiA791DROxVp0-8CZnzH9QLsG5sbVq6r2ZRsEo_QfUNdfA%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhAPqAu5v0rWdFeikil5XE0g0KT3IFkCr8Zt27wL98P7veAiEAlIs--hRmjyjcVXPk6gGQa__W49m95C1axbX2FQFe0IA%3D'
[dashsegments] Total fragments: 83
[download] Destination: Corpo Musicale di Villasanta - Oberto, Conte di San Bonifacio - ouverture (Giuseppe Verdi)-wmaCl8QNWgI.f137.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10)...
ERROR: giving up after 10 fragment retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 48, in real_download
    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/fragment.py", line 104, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
HTTPError: HTTP Error 404: Not Found

## Description

I've been downloading many files from YouTube with youtube-dl, but this single one fails. I've retried several times and always get "404: Not Found" errors.
This is the link: https://www.youtube.com/watch?v=wmaCl8QNWgI

**Comment by dstftw** [comment]
Server side Youtube issue.

**Comment by gballabio** [comment]
Is there a workaround please?
