### ISSUE TITLE
Download & convert a file without storage on the server through php

### ISSUE THREAD

**Issue by triplesixman** [ytdl-org/youtube-dl#27511]
## Checklist

- [* ] I'm asking a question
- [ *] I've looked through the README and FAQ for similar questions
- [ *] I've searched the bugtracker for similar questions including closed ones

## Question

Hello,

I try through php on a remote server to download a video through youtube-dl and convert it with ffmpeg without storing the file on the server. So far, I've succeeded when the format is the default one, but if I want to do a conversion with ffmpeg, I download an unreadable empty file.

I don't have any nginx or php errors

Does anyone know if there's something I'm missing or that I'm doing the wrong way?

```
$youtubeUrl = "https://www.youtube.com/watch?v=G7StfbQcxDU";

header('Content-Description: File Transfer');
header('Cache-Control: must-revalidate');
header('Pragma: public');
header("Content-Disposition: attachment; filename=\"video.mp3\"" );
header("Content-Type: application/octet-stream");
	
passthru("youtube-dl -f bestaudio[ext=m4a] -x --ffmpeg-location /usr/local/bin/ffmpeg -o '-.%(ext)s' $youtubeUrl");
```

**Comment by dstftw** [comment]
You can't do that without storing the file on disk.

**Comment by triplesixman** [comment]
@dstftw Is it possible to reopen the subject so that others can see it?

Because it is quite possible to do that. I found a way that consists in retrieving the url ["url"] from the template output, and then in php :

passthru("ffmpeg -i '$url["url"]' -f mp3 -ab 192000 -vn -");

In this case, the file is not uploaded to the server.

The problem with this method is that I can't put youtube-dl parameters because ffmpeg downloads the file directly. I haven't found a workaround yet but there is certainly one.
