### ISSUE TITLE
YouTube - 1080p with Audio

### ISSUE THREAD

**Issue by Xiper-Starchild** [ytdl-org/youtube-dl#27522]
Every time I try to download a video with the argument '-f best', and the video has a horizontal resolution of 1080p, the output is 720p. I decided to take a look at the best available formats using `youtube-dl -F %link` and took notice that every single one has a 1080p format option but they are all video-only.

Someone else said that the program merges the audio and video source automatically for videos of that specific quality but I haven't found that to be the case.

Is there anything I can do actually make that happen? I'd love to have the ability to download 1080p videos _with_ the audio track merged into the video file.

**Comment by dstftw** [comment]
Install ffmpeg.
