### ISSUE TITLE
Feature-set Qns

### ISSUE THREAD

**Issue by jalyst** [ytdl-org/youtube-dl#27528]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

does youtube-dl also have a play list extraction / export component?
Have a tonne of play lists, want to grab all or a subset of my playlists urls & their sub urls.
So can then import into some other sw...

**Comment by Saul-JedHL** [comment]
what, exactly, is "incomplete" about my query?
