### ISSUE TITLE
Unable to download from BBC iPlayer: Coco https://www.bbc.co.uk/iplayer/episode/m000qq5v/coco 

### ISSUE THREAD

**Issue by putridp** [ytdl-org/youtube-dl#27538]
output:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.bbc.co.uk/iplayer/episode/m000qq5v', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.22
[debug] Python version 2.7.16 (CPython) - Linux-5.4.72-v7+-armv7l-with-debian-10.6
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[bbc.co.uk] m000qq5v: Downloading video page
[bbc.co.uk] m000qq5v: Downloading playlist JSON
[bbc.co.uk] m000qq5s: Downloading media selection XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 592, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
This is a known issue which is fixed by at least two Pull Requests that have yet to be merged into the distributed product: my basic https://github.com/ytdl-org/youtube-dl/pull/23415 and the more general https://github.com/ytdl-org/youtube-dl/pull/26821.
