### ISSUE TITLE
how does "--download-archive" work?

### ISSUE THREAD

**Issue by blueray453** [ytdl-org/youtube-dl#27531]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How does `--download-archive` work? I mean if I download suppose ~500 courses (~40,000 videos) from lets say pluralsight, then is there any possibility that two different video will have the same ID, resulting in the second video not being downloaded? Is there any guarantee that each unique video will always have an unique ID?

**Comment by dstftw** [comment]
Video id is supposed to be unique. Does pluralsight guarantees this? Ask them.

**Comment by blueray453** [comment]
@dstftw I think you are talking about `video_id` in https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/pluralsight.py

I mean the value of `video_id` in the files is supposed to be unique given pluralsight makes it unique.

Is it the variable or am I looking at the wrong place?

To be more clear:

pluralsight ef85ae40-9ac0-46e6-b186-ed93bb32bea9
pluralsight 61f3ed5f-edf6-4e1a-bdf3-1a4db7d489822

Where is these `ef85ae40-9ac0-46e6-b186-ed93bb32bea9` & `61f3ed5f-edf6-4e1a-bdf3-1a4db7d489822` coming from. Can you please refer us to the code.
