### ISSUE TITLE
(Deprecated) Wistia playlist support is not working.

### ISSUE THREAD

**Issue by laenan8466** [ytdl-org/youtube-dl#27533]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --verbose https://fast.wistia.com/embed/medias/aodt9etokc.jsonp
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://fast.wistia.com/embed/medias/aodt9etokc.jsonp']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.12.22
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[Wistia] aodt9etokc: Downloading JSON metadata
ERROR: Error while getting the playlist
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\wistia.py", line 77, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Error while getting the playlist
```

```
youtube-dl --verbose https://fast.wistia.net/embed/playlists/aodt9etokc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://fast.wistia.net/embed/playlists/aodt9etokc']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.12.22
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[generic] aodt9etokc: Requesting header
WARNING: Falling back on generic information extractor.
[generic] aodt9etokc: Downloading webpage
[generic] aodt9etokc: Extracting information
ERROR: Unsupported URL: https://fast.wistia.net/embed/playlists/aodt9etokc
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\generic.py", line 3446, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://fast.wistia.net/embed/playlists/aodt9etokc
```

## Description

`youtube-dl` is raising an error when used to download a playlist video. Maybe this only applies to the deprecated playlist function of Wistia, but is still out there in the wild.
All examples were given from the [Wistia Playlist page](https://wistia.com/support/embed-and-share/playlists) and the there included playlist.

- Using the page directly doesn't work (I guess that is OK.) -> Unsupported URL, maybe add generic support?
- Download of the single video (`cmst5825to` in this case) is working properly. 
- The method used in #22931, using the jsonp or raw playlist referrer from source (`aodt9etokc`) with `youtube-dl https://fast.wistia.com/embed/medias/aodt9etokc.jsonp` doesn't work. -> Error while getting playlist.
   - Using `youtube-dl wistia:aodt9etokc` is raising identical error.
- Using the embedded link from source https://fast.wistia.net/embed/playlists/aodt9etokc doesn't work. -> Unsupported URL (same if adding `.jsonp`)

From my understanding one of the last two methods (`[...].com/embed/medias` or `[...].net/embed/playlists/` should work and I included logs for both cases. Missing piece is here, how to download the complete playlist, instead of each single video.

Could be connected to #5587, but there is more the question for the case with multiple (different) videos.

**Comment by laenan8466** [comment]
Hey @remitamine!
Wow, that was a quick fix. It fixed it for the first case. Thank you so much!

Your fix didn't fixed the usage of `youtube-dl wistia:aodt9etokc`. For me it is not clear, how to fix this. One would have to check for different cases and try them.

But still, you are incredible and tremendously fast!

**Comment by remitamine** [comment]
> Your fix didn't fixed the usage of youtube-dl wistia:aodt9etokc. For me it is not clear, how to fix this. One would have to check for different cases and try them.

this short form is used for single videos, so it doesn't make sense to use it for playlists as well(it's not clear if a playlist and a video can have the same ID).

**Comment by laenan8466** [comment]
Oh ok, didn't knew that. Thank you for explaining!
