### ISSUE TITLE
how does the restrict-filenames works?

### ISSUE THREAD

**Issue by Shuvi-Hub** [ytdl-org/youtube-dl#27532]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have an skript using youtube_dl but sometimes i get an Unicode encode error and i know there is something to work around (restrict-filenames) but i don't know how to use it inside my code...
so my actual question is how to use it inside the ydl_opts?

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl/blob/7f3c90ab252e212c67c8aa80d2e83fb9b686ee6d/youtube_dl/YoutubeDL.py#L166
