### ISSUE TITLE
 CNN subtitles cannot be detected or  downloaded

### ISSUE THREAD

**Issue by jiangjiangflies** [ytdl-org/youtube-dl#27541]
## Checklist
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```
youtube-dl https://www.cnn.com/2020/12/17/cnn10/ten-content-fri/index.html --list-subs -v
[debug] System config: ['-o', '%(title)s.%(ext)s', '--sub-lang', 'en,zh-CN,zh-TW,zh-Hans', '--write-sub', '--convert-subs', 'srt', '--embed-subs', '--ap-mso', 'DTV', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--ignore-errors', '--write-auto-sub', '--add-metadata', '--playlist-items', '1-5', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.cnn.com/2020/12/17/cnn10/ten-content-fri/index.html', '--list-subs', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.22
[debug] Python version 3.7.6 (CPython) - Linux-4.9.0-4-amd64-x86_64-with-debian-9.11
[debug] exe versions: ffmpeg 4.3.1-static, ffprobe 4.3.1-static, rtmpdump 2.4
[debug] Proxy map: {}
[CNNArticle] index.html: Downloading webpage
[CNN] ten-1218: Downloading XML
[CNN] cnn10/2020/12/11/ten-1218.cnn: Downloading m3u8 information
[CNN] cnn10/2020/12/11/ten-1218.cnn: Downloading m3u8 information
[CNN] cnn10/2020/12/11/ten-1218.cnn: Downloading m3u8 information
[CNN] cnn10/2020/12/11/ten-1218.cnn: Downloading m3u8 information
cnn10/2020/12/11/ten-1218.cnn has no subtitles
```

## Description

This program has subtitles, but recently youtube-dl cannot download them anymore.
Example Link: https://www.cnn.com/2020/12/17/cnn10/ten-content-fri/index.html

**Comment by remitamine** [comment]
there is not seperate subtitle for the video, the subtitles are included in video files(can be displayed with a media player that supports CEA 608/708 subtitles such as VLC and MPV).
