### ISSUE TITLE
Youtube is broken

### ISSUE THREAD

**Issue by williamsAu4a83** [ytdl-org/youtube-dl#27559]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'https://www.youtube.com/watch_popup?v=63RmMXCd_bQ', u'-v']
[debug] Encodings: locale None, fs None, out None, pref UTF-8
[debug] youtube-dl version 2020.12.26
[debug] Python version 2.7.12 (CPython) - Linux-3.10.0-aarch64-with-libc
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] watch_popup: Downloading webpage
ERROR: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python2.7/youtube_dl/extractor/youtube.py", line 3178, in _real_extract
    data = self._extract_yt_initial_data(item_id, webpage)
  File "/usr/lib/python2.7/youtube_dl/extractor/youtube.py", line 300, in _extract_yt_initial_data
    self._YT_INITIAL_DATA_RE), webpage, 'yt initial data'),
  File "/usr/lib/python2.7/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by october262** [comment]
retry with this link - https://www.youtube.com/embed/63RmMXCd_bQ

**Comment by remitamine** [comment]
```
youtube-dl --ignore-config -v -F https://www.youtube.com/watch_popup?v=63RmMXCd_bQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', '-F', 'https://www.youtube.com/watch_popup?v=63RmMXCd_bQ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.26
[debug] Python version 3.9.1 (CPython) - Linux-5.10.2-arch1-1-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 63RmMXCd_bQ: Downloading webpage
[youtube] 63RmMXCd_bQ: Downloading m3u8 information
[youtube] 63RmMXCd_bQ: Downloading MPD manifest
[info] Available formats for 63RmMXCd_bQ:
format code  extension  resolution note
91           mp4        256x144    HLS  269k , avc1.4d400c, 30.0fps, mp4a.40.5@ 48k
92           mp4        426x240    HLS  507k , avc1.4d4015, 30.0fps, mp4a.40.5@ 48k
93           mp4        640x360    HLS  962k , avc1.4d401e, 30.0fps, mp4a.40.2@128k
94           mp4        854x480    HLS 1282k , avc1.4d401f, 30.0fps, mp4a.40.2@128k
95           mp4        1280x720   HLS 2447k , avc1.4d401f, 30.0fps, mp4a.40.2@256k
96           mp4        1920x1080  HLS 4561k , avc1.4d4028, 30.0fps, mp4a.40.2@256k (best)
```

**Comment by williamsAu4a83** [comment]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch_popup?v=63RmMXCd_bQ', u'-g', u'--get-format', u'-f', u'best', u'-v']
[debug] Encodings: locale None, fs None, out None, pref UTF-8
[debug] youtube-dl version 2020.12.26
[debug] Python version 2.7.12 (CPython) - Linux-3.10.0-aarch64-with-libc
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python2.7/youtube_dl/extractor/youtube.py", line 3178, in _real_extract
    data = self._extract_yt_initial_data(item_id, webpage)
  File "/usr/lib/python2.7/youtube_dl/extractor/youtube.py", line 300, in _extract_yt_initial_data
    self._YT_INITIAL_DATA_RE), webpage, 'yt initial data'),
  File "/usr/lib/python2.7/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by someziggyman** [comment]
For me -F format extraction also works fine. Tried from different countries with a VPN. But the download only works if --ffmpeg-location is specified since it's an m3u live stream.
