### ISSUE TITLE
Youtube-dl downloads channels that are not in batch-file

### ISSUE THREAD

**Issue by tkrauze** [ytdl-org/youtube-dl#27557]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', '/home/pi/Downloads/yt_cookies.txt', '--netrc', '-R', '3', '--fragment-retries', '3', '--download-archive', '/media/downloaded.txt', '-v', '-i', '-c', '-U', '-o', '%(uploader)s/%(title)s - (%(id)s) [%(upload_date)s] (%(duration)ss) [%(resolution)s].%(ext)s', '-f', 'bestvideo[ext=mp4]+bestaudio', '--batch-file=/media/channel_list.txt']
[debug] Batch file urls: ['https://www.youtube.com/channel/UC7ZzLs0ZlJgLqxHfWbprcdQ', 'https://www.youtube.com/user/kolonkos1', 'https://www.youtube.com/user/TorenoPL', 'https://www.youtube.com/channel/UCw5ovkK41-KvKVVc-80Gz5A', 'https://www.youtube.com/channel/UCXf8RmFdAgpIU1kUk5xoCfg', 'https://www.youtube.com/channel/UCdG9sWvWdOagPZ5Q8JZBniA', 'https://www.youtube.com/channel/UCGkINNrutydRGh1tBr-tQmg', 'https://www.youtube.com/user/mrmucha', 'https://www.youtube.com/channel/UCRs6hCspqZxzP1thQztIjzw', 'https://www.youtube.com/channel/UCWjWWmaxZd20NhGDXJ4kC9g', 'https://www.youtube.com/channel/UChEUL2_HRvp7c0mWxVOAlEQ', 'https://www.youtube.com/channel/UCjhiPrYg5TsyD7TAQBtsauQ', 'https://www.youtube.com/channel/UCM-BZ9j4teovVnz1R8WIOWQ', 'https://www.youtube.com/channel/UC48FG7RgXInXS8-pfuI5lhA', 'https://www.youtube.com/channel/UCSUeeP5ToSFTmZNUc19b4dA', 'https://www.youtube.com/channel/UCT5OOawidchs7v8mRSEf_ag', 'https://www.youtube.com/channel/UCs5zIHj6Bx4I40FsmgGCCSw', 'https://www.youtube.com/channel/UCtzP8a7yqQw_MF2opslLrVA', 'https://www.youtube.com/channel/UCs5ADGFK1PfQqgarpXA2-qw', 'https://www.youtube.com/channel/UCbLoHo-bduWol7W0qQLgQRg', 'https://www.youtube.com/channel/UCJfOylMY-Mp1f-K-ZLW1UeA', 'https://www.youtube.com/channel/UCU7ZXfsit0TKrBO_5PaC5kw', 'https://www.youtube.com/channel/UCnfz1QIqLlVvXjIkqNNKePg', 'https://www.youtube.com/channel/UC8e8Ag9Or9ra4J6jl4qjfEg', 'https://www.youtube.com/channel/UCKLqf6aKzaZAa_QlGkX4gVQ', 'https://www.youtube.com/channel/UCjcTiD-z9q9gInkkTZzTVeQ', 'https://www.youtube.com/channel/UCbS8vsbx1MSl1aGrja2-4kg', 'https:/[youtube:tab] Downloading login page
[youtube:tab] Looking up account info
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[youtube:tab] UC8e8Ag9Or9ra4J6jl4qjfEg: Downloading webpage

## Description

Im unsing youtube-dl to download several channel from youtube, chanell list is stored in batch file. I noticed that during running youtube-dl witch batch-file many random channels are downloaded which are not in batch file.

Example:

this channel is not in batch file ! 

[youtube:tab] PLrtN-f7hnIEPqK_uE7QmXltCLDsDA_dz6: Downloading webpage
[download] Downloading playlist: Bo
[youtube:tab] playlist Bo: Downloading 31 videos
[download] Downloading video 1 of 31
[download] [FREE] SZA x H.E.R x Sabrina Claudio Type Beat - Think Bout You | R&B Instrumental has already been recorded in archive
[download] Downloading video 2 of 31
[youtube] ZiKEoe7cvy8: Downloading webpage
WARNING: Unable to extract video title
ERROR: This video has been removed for violating YouTube's Terms of Service.
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/home/pi/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/pi/.local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2068, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video has been removed for violating YouTube's Terms of Service.

[download] Downloading video 3 of 31
[download] (FREE) | "COCO" | Jhus x Wizkid x Not3s Type Beat | Free Beat | Afrobeats Instrumental | 2018 has already been recorded in archive
[download] Downloading video 4 of 31
[download] "Resilient" | Bryson Tiller x DVSN x Mabel x Octavian x Knucks Type Beat | 2018 has already been recorded in archive
[download] Downloading video 5 of 31
[download] "African thing"Jhus X Young B ft Belly Squad Afroswing type beat- Prod Ransom beatz has already been recorded in archive
[download] Downloading video 6 of 31
[download] (FREE) | JAKARTA | Wizkid x Yxng Bane x Not3s Type Beat | Free Beat | Afrobeats Instrumental | 2018 has already been recorded in archive
[download] Downloading video 7 of 31
[download] (FREE) "MOTTO" | Jhene Aiko x Queen Naija x SZA Type Beat | Free Beat | R&B Soul Instrumental | 2018 has already been recorded in archive
[download] Downloading video 8 of 31
[download] (FREE) | "RITZ" | 23 x Nines x Hardy Caprio Type Beat | Free Beat | UK Rap Instrumental 2018 has already been recorded in archive
[download]   0.5% of 25.77MiB at 1007.88KiB/s ETA 00:26

**Comment by dstftw** [comment]
Post complete verbose log.
