### ISSUE TITLE
MeWatch site unable to download

### ISSUE THREAD

**Issue by david1github** [ytdl-org/youtube-dl#27555]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[generic] Recipe-Of-Life-E41-189759: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Recipe-Of-Life-E41-189759: Downloading webpage
[generic] Recipe-Of-Life-E41-189759: Extracting information
ERROR: Unsupported URL: https://live.mewatch.sg/watch/Recipe-Of-Life-E41-189759
```

## Description

Unable to download from the site MeWatch
https://live.mewatch.sg/watch/Recipe-Of-Life-E41-189759

**Comment by 904584082** [comment]
欢迎新人加入QQ群:972802757免费看新剧！电脑和手机都能下载新剧，除了加密视频外。密码：meWATCH。
