### ISSUE TITLE
What is the right way to set header in the config file

### ISSUE THREAD

**Issue by blueray453** [ytdl-org/youtube-dl#27569]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I checked the documentation:

```
--add-header FIELD:VALUE         Specify a custom HTTP header and its value,
                                 separated by a colon ':'. You can use this
                                 option multiple times
```

However, it is not clear to me. What is the right way to set header in the `youtube-dl.conf` file:

`--add-header Accept-Encoding: identity;q=1, *;q=0`

or,

`--add-header Accept-Encoding:"identity;q=1, *;q=0"`

or,

`--add-header 'Accept-Encoding: identity;q=1, *;q=0'`

**Comment by dstftw** [comment]
The latter. Read FAQ on your shell.

**Comment by blueray453** [comment]
What does latter mean? The second one or the third one.
