### ISSUE TITLE
Handling multiple embeds of same video from different sources.

### ISSUE THREAD

**Issue by jsbali** [ytdl-org/youtube-dl#27576]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello,
I am writing an extractor for a site that has multiple embeds of the same video in different resolutions from different sites. 

As an example consider embeds from site A (360p, 720p) and site B(720p). The extractors for both site A and B already exist 

Then what is the correct thing to return from the extractor.

1. One case can be doing all the filtering within my extractor and then split out an array that has all direct URLs.
2. Other can be (if youtube-dl supports it) return two extractor objects of A and B and let youtube-dl figure out the urls.

Not sure if the solution in case 2 exists in the current code. I tried looking for it couldn't find it.

**Comment by remitamine** [comment]
it depends, without having enough information, i can only point you to [an example](https://github.com/ytdl-org/youtube-dl/blob/9c1e164e0cd77331ea4f0b474b32fd06f84bad71/youtube_dl/extractor/nba.py#L321-L326), this is from the NBA extractor that combines the information from two sources.
