### ISSUE TITLE
Downloading youtube playlist does not work, gives output "Downloading 0 videos"

### ISSUE THREAD

**Issue by alex4200** [ytdl-org/youtube-dl#27581]
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--yes-playlist', '-i', '-x', '--audio-format', 'mp3', 'https://www.youtube.com/watch?list=PLDtB0hg5RjyP8P8hLpiOiMVKGz4S5bdZr']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.29
[debug] Python version 3.6.9 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] PLDtB0hg5RjyP8P8hLpiOiMVKGz4S5bdZr: Downloading webpage
[download] Downloading playlist: None
[youtube:tab] playlist None: Downloading 0 videos
[download] Finished downloading playlist: None
```

## Description

Trying to download a playlist with the most recent version of `youtube-dl` (2020.12.29) on MacOS (10.14.6) results in an message:

`Downloading 0 videos` 

and no videos are being downloaded. 

Full command used:

`youtube-dl -v --yes-playlist -i -x --audio-format mp3    "https://www.youtube.com/watch?list=PLDtB0hg5RjyP8P8hLpiOiMVKGz4S5bdZr"`

**Comment by remitamine** [comment]
the playlist URL redirects to https://www.youtube.com/.

**Comment by alex4200** [comment]
@remitamine So how does this solve the problem regarding 0 videos?

**Comment by remitamine** [comment]
can you access the playlist in the browser, if so, then most likely it requires logging, if it's the case then you should pass authenticated cookies to youtube-dl.

**Comment by alex4200** [comment]
@remitamine Ah ok. It seems to be a playlist only visible for users "logged in". I did not know that such playlist exists. Thanks.

**Comment by alex4200** [comment]
@remitamine Here is an example of a page I can load in a private window (no auth required), for which only the first video is downloaded, but not the playlist (although I specify it on the command line):

`youtube-dl --yes-playlist -i -x --audio-format mp3 https://www.youtube.com/watch?v=PinBVYKQGeM&list=PLv8FQnG3jdW_vUvLBLJZnGa3v6c8FA_lJ`

**Comment by alex4200** [comment]
@remitamine Ok, I need to remember to 

- always use a private tab to search for playlists. 
- use the complete URL
- Use the option `yes-playlist`
- And put the URL into quotes. 

I will write that down. Thanks
