### ISSUE TITLE
BBC Sounds - Upgrade to V6 of BBC Open Live API (open.live.bbc.co.uk) and Fix Timeouts During Extraction and Eliminate Port 80 Requests

### ISSUE THREAD

**Issue by orbitwide** [ytdl-org/youtube-dl#27587]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.12.29**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
ytdl --verbose https://www.bbc.co.uk/sounds/play/m000qlyg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.bbc.co.uk/sounds/play/m000qlyg']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.29
[debug] Python version 3.9.1 (CPython) - Linux
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[bbc.co.uk] m000qlyg: Downloading video page
[bbc.co.uk] m000qlyg: Downloading playlist JSON
[bbc.co.uk] m000qlyf: Downloading media selection XML
[bbc.co.uk] m000qlyf: Downloading MPD manifest
[bbc.co.uk] m000qlyf: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 60] Operation timed out>
[bbc.co.uk] m000qlyf: Downloading m3u8 information
...
```

## Description

BBC Sounds (including programme and sounds urls) get stuck at the "Downloading m3u8 information" stage (at least here outside the UK) and loops on "Operation timed out" until eventually (sometimes) extracting (this is after making requests to aod-dash-ww-live.akamaized.net or aod-hls-ww.live.bbcfmt.hs.llnwd.net). I note that youtube-dl still uses v5 of the Open Live MediaSelector API (open.live.bbc.co.uk) as opposed to v6 which returns in JSON. 

Something seems to be going wrong regarding extraction of the media URLs (href in the API output from https://open.live.bbc.co.uk/mediaselector/6/select/version/2.0/mediaset/iptv-all/vpid/VPID where the corresponding VPID is found using https://bbc.co.uk/programmes/PID/playlist.json). I have managed to make a simple shell script call the APIs manually and play/extract instantly, so surely this should not be that difficult to implement... 

I also noted that the extractor was making requests on port 80 at times as well as 443 to all the relevant APIs (open.live.bbc.co.uk, bbc.co.uk, aod-hls-ww.live.bbcfmt.hs.llnwd.net, etc...) which seems unnecessary and something which should be eliminated since all the endpoints support TLS.

**Comment by Vangelis66** [comment]
> I note that youtube-dl still uses v5 of the Open Live MediaSelector API (open.live.bbc.co.uk) as opposed to v6 which returns in JSON.

You are wrong! This is no longer the case since https://github.com/ytdl-org/youtube-dl/commit/c32a059f52ccb76703785dccdd91ae9ce947a824, which already landed in v**2020.12.26**

> I also noted that the extractor was making requests on port 80 at times as well as 443 to all the relevant APIs (open.live.bbc.co.uk, bbc.co.uk, aod-hls-ww.live.bbcfmt.hs.llnwd.net, etc...) which seems unnecessary and something which should be eliminated since all the endpoints support TLS.

Well, I'm opposed to that proposed change, since I frequently use **plain HTTP** proxies to access geo-fenced audio/video BBC content; if **only secure** BBC connections were supported by `yt-dl`, then HTTP**S** proxies are much harder to come across and use... 

Also, because of the overhead of HTTPS connections, these consume somewhat higher resources (CPU cycles), which might be an issue for users on old/underpowered hardware... Not to mention `yt-dl` users on old Python installations (with possibly broken cert chains), these would be also affected by that change... 

As long as the Beeb keep both options available (HTTP+HTTPS), I'm OK with that!

**Comment by jmburges** [comment]
Just putting a +1 that this seems to be the case in the US, and the UK via VPN as well. I'm running `2021.01.08`. Here is the log. It's a slightly different problem but feels similar? not sure

```
 youtube-dl -f 'bestaudio[ext=m4a]' --add-metadata -v https://www.bbc.co.uk/sounds/play/m000r3jn

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'bestaudio[ext=m4a]', u'--add-metadata', u'-v', u'https://www.bbc.co.uk/sounds/play/m000r3jn']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 2.7.16 (CPython) - Linux-3.16.85-62-aarch64-with-debian-10.7
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] m000r3jn: Downloading video page
[bbc.co.uk] m000r3jn: Downloading playlist JSON
[bbc.co.uk] m000r3jm: Downloading media selection JSON
[bbc.co.uk] m000r3jm: Downloading m3u8 information
[bbc.co.uk] m000r3jm: Downloading m3u8 information
[bbc.co.uk] m000r3jm: Downloading MPD manifest
[bbc.co.uk] m000r3jm: Downloading m3u8 information
[bbc.co.uk] m000r3jm: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[bbc.co.uk] m000r3jm: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] m000r3jm: Downloading MPD manifest
[bbc.co.uk] m000r3jm: Downloading m3u8 information
[bbc.co.uk] m000r3jm: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[bbc.co.uk] m000r3jm: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[debug] Invoking downloader on u'https://aod-dash-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_audio/a3b00e-m000r3jm/vf_m000r3jm_8e49469f-1eb9-4be6-b757-c3f9e19d1926.ism.hlsv2.ism/iptv_hd_abr_v1_uk_dash_master.mpd?__gda__=1610564776_2c0b9e5cbd65143e66550bed14fab35b'
[dashsegments] Total fragments: 564
```

`

**Comment by jmburges** [comment]
And I'll also get this error when downloading sometimes:

```
7ERROR: unable to download video data: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1936, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1875, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 48, in real_download
    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/fragment.py", line 104, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)>
```

I restart the DL once or twice and it eventually finishes without erroring out

**Comment by Vangelis66** [comment]
@jmburges 

Using the **official win32 binary**;

`youtube-dl -f "bestaudio[ext=m4a]" "https://www.bbc.co.uk/sounds/play/m000r3jn" -v`

1. **DIRECT** from a South-European location: **limelight** CDN is auto-chosen:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestaudio[ext=m4a]', 'https://www.bbc.co.uk/s
ounds/play/m000r3jn', '-v']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] m000r3jn: Downloading video page
[bbc.co.uk] m000r3jn: Downloading playlist JSON
[bbc.co.uk] m000r3jm: Downloading media selection JSON
[bbc.co.uk] m000r3jm: Downloading MPD manifest
[bbc.co.uk] m000r3jm: Downloading m3u8 information
[bbc.co.uk] m000r3jm: Downloading MPD manifest
[bbc.co.uk] m000r3jm: Downloading m3u8 information
[bbc.co.uk] m000r3jm: Downloading MPD manifest
[bbc.co.uk] m000r3jm: Downloading m3u8 information
[bbc.co.uk] m000r3jm: Downloading MPD manifest
[bbc.co.uk] m000r3jm: Downloading m3u8 information
[debug] Invoking downloader on 'https://aod-dash-ww-live.bbcfmt.s.llnwi.net/usp/
auth/vod/piff_abr_full_audio/a3b00e-m000r3jm/vf_m000r3jm_8e49469f-1eb9-4be6-b757
-c3f9e19d1926.ism.hlsv2.ism/iptv_hd_abr_v1_nonuk_dash_master.mpd?s=1610545207&e=
1610588407&h=afd3dd0a1fafffd49150a08836b1fcab'
[dashsegments] Total fragments: 564
[download] Destination: Diplo and Friends, Damian Lazarus in the Mix-m000r3jm.m4
a
[download] 100% of 41.58MiB in 08:03
[ffmpeg] Correcting container in "Diplo and Friends, Damian Lazarus in the Mix-m
000r3jm.m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Diplo an
d Friends, Damian Lazarus in the Mix-m000r3jm.m4a" -c copy -f mp4 "file:Diplo an
d Friends, Damian Lazarus in the Mix-m000r3jm.temp.m4a"
```
Result is a **96**kbpsABR HE-AAC encode (41.5 MiB)

2. Using a whitelisted UK VPN: **limelight** CDN is auto-chosen:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestaudio[ext=m4a]', 'https://www.bbc.co.uk/s
ounds/play/m000r3jn', '-v']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] m000r3jn: Downloading video page
[bbc.co.uk] m000r3jn: Downloading playlist JSON
[bbc.co.uk] m000r3jm: Downloading media selection JSON
[bbc.co.uk] m000r3jm: Downloading MPD manifest
[bbc.co.uk] m000r3jm: Downloading m3u8 information
[bbc.co.uk] m000r3jm: Downloading MPD manifest
[bbc.co.uk] m000r3jm: Downloading m3u8 information
[bbc.co.uk] m000r3jm: Downloading MPD manifest
[bbc.co.uk] m000r3jm: Downloading m3u8 information
[bbc.co.uk] m000r3jm: Downloading MPD manifest
[bbc.co.uk] m000r3jm: Downloading m3u8 information
[bbc.co.uk] m000r3jm: Downloading m3u8 information
[bbc.co.uk] m000r3jm: Downloading m3u8 information
[debug] Invoking downloader on 'https://aod-dash-uk-live.bbcfmt.s.llnwi.net/usp/
auth/vod/piff_abr_full_audio/a3b00e-m000r3jm/vf_m000r3jm_8e49469f-1eb9-4be6-b757
-c3f9e19d1926.ism.hlsv2.ism/iptv_hd_abr_v1_uk_dash_master.mpd?s=1610545982&e=161
0589182&h=675dffcaea12f41b3bb8ca61e0a44125'
[dashsegments] Total fragments: 564
[download] Destination: Diplo and Friends, Damian Lazarus in the Mix-m000r3jm.m4
a
[download] 100% of 136.91MiB in 17:46
[ffmpeg] Correcting container in "Diplo and Friends, Damian Lazarus in the Mix-m
000r3jm.m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Diplo an
d Friends, Damian Lazarus in the Mix-m000r3jm.m4a" -c copy -f mp4 "file:Diplo an
d Friends, Damian Lazarus in the Mix-m000r3jm.temp.m4a"
```
Result is a **320**kbpsABR AAC-LC encode (137 MiB)

As you can see, `yt-dl` is **nowhere at fault** here...

If I may comment on parts of your logs: 

> [debug] Python version 2.7.**16** (CPython)

You should update at least to 2.7.**18**, which is the **EOL** version of py2.7; better yet, consider updating to the latest py3.x version for your distro and make sure `yt-dl` is using that!

> WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
(snipped)
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
(snipped)
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
(snipped)
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden

Your **commercial VPN**'s UK IP address **has been blacklisted** on _some_ of the available CDN nodes...

> URLError: <urlopen error [**SSL: SSLV3_ALERT_HANDSHAKE_FAILURE**] sslv3 alert handshake failure (_ssl.c:727)>

This is a TLS-related **secure connection error** in either
a) your client (python modules), or 
b) your VPN's server, or 
c) both
when trying to establish secure (HTTPS) connections with various endpoints in the BBC Sounds/iPlayer infrastucture...

None of the above "issues" can be managed by `yt-dl` itself... 😉 

And...
People should remember this is a `yt-dl` **bugs tracker**, NOT a support forum... 
The two main devs have only got definite amounts of development time to invest on _actually fixing broken things_/implementing new features; non-coder volunteers (such as I), I believe, are _welcome_ by the devs (?) to manage other aspects here, but...

**Comment by dirkf** [comment]
None of the quoted test URIs/URLs are active now (404) because the BBC has forgotten the point of them.

Also, I agree with [the comment above](https://github.com/ytdl-org/youtube-dl/issues/27587#issuecomment-753246023).

Unless an active test URL is provided, I think this issue could be closed.

**Comment by Vangelis66** [comment]
@dirkf wrote:

> None of the quoted test URIs/URLs are active now (404) 
> because **the BBC has forgotten the point of them**.

When a BBC radio/audio programme has expired and is no longer available on **BBC Sounds** as **AOD**, the `*/sounds/play/*` URIs will **404**, or at least that's my understanding of this... 😉 ; however, because every radio/audio programme (on Sounds) has been assigned a **unique** PID string (which lasts, practically, for ever), the `*/programmes/pid` URIs remain valid, e.g. 

`https://www.bbc.co.uk/sounds/play/m000r3jn` => `https://www.bbc.co.uk/programmes/m000r3jn` => 
```
BBC Radio 1 - Diplo and Friends - Damian Lazarus in the Mix
First broadcast:  Sun 10 Jan 2021 00:00 
Sorry, this episode is not currently available
```
... so, actually, the **BBC hasn't forgotten the details of that particular programme** ...
Of course, trying now 

`youtube-dl https://www.bbc.co.uk/programmes/m000r3jn` 

you'll simply get: 
```
[bbc.co.uk] m000r3jn: Downloading video page
ERROR: Sorry, this episode is not currently available
```
BTW, thanks for the vote of confidence! 😃
