### ISSUE TITLE
Does "--limit-rate" work when extraction is delegated to FFmpeg ?

### ISSUE THREAD

**Issue by section83** [ytdl-org/youtube-dl#27583]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

I have found that when extraction is delegated to FFmpeg, the "--limit-rate" setting does not function.  Downloads are not slowed.  I have attached the verbose log for an example.

[youtube-dl_response-Gracepoint_-_S1_Ep._1-Wednesday_30_December_2020_at_9_37_48_pm.txt](https://github.com/ytdl-org/youtube-dl/files/5753908/youtube-dl_response-Gracepoint_-_S1_Ep._1-Wednesday_30_December_2020_at_9_37_48_pm.txt)

I think the relevant part is the report from FFmpeg that it downloaded 449.87MiB in 1:44 – which is about the maximum my broadband provides at present.  I confirmed that by watching download speed reported by a macOS tool LittleSnitch which showed download in the 4-5MB/s range.  The audio component following was downloaded at around 1MB/sec which is the limit set in the call to youtube-dl.

So, it looks like "--limit-rate" does not work when extraction is delegated to FFmpeg.  Is that correct ?  Are there other situations in which "--limit-rate" does not function ?

The log is very long so, here are the highlights:

> [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-errors', u'--newline', u'--no-overwrites', u'--limit-rate', u'1.0m', u'--verbose', u'-o', u'%(title)s.%(ext)s', u'https://10play.com.au/gracepoint/episodes/season-1/episode-1/tpv201115lygfc']
[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
[debug] youtube-dl version 2020.12.29
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1-tessus, ffprobe 4.3.1-tessus
[debug] Proxy map: {}
[TenPlay] tpv201115lygfc: Downloading JSON metadata
[debug] Using fake IP 1.146.243.159 (AU) as X-Forwarded-For.
[brightcove:new] 6206806786001: Downloading JSON metadata
[brightcove:new] 6206806786001: Downloading m3u8 information
[brightcove:new] 6206806786001: Downloading m3u8 information
[brightcove:new] 6206806786001: Downloading m3u8 information
[brightcove:new] 6206806786001: Downloading m3u8 information
[brightcove:new] 6206806786001: Downloading MPD manifest
[brightcove:new] 6206806786001: Downloading MPD manifest
[brightcove:new] 6206806786001: Downloading MPD manifest
[brightcove:new] 6206806786001: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/2199827728001/3787c027-575b-4d96-ab03-2f1de7c25179/4d6eb7e2-af93-4efb-a3d1-e26723e2fd15/10s/rendition.m3u8?fastly_token=NWZlY2IxNjJfNWU5YTg1MWJjYWU5NjFiZjYyMThjYzVjZDk4OTc0MDlkZTI1NGJlN2E2MWUwYTEyNDJhN2YxZmE0YWI0NzgxYw%3D%3D'
[hlsnative] Downloading m3u8 manifest
WARNING: hlsnative has detected features it does not support, extraction will be delegated to ffmpeg
[download] Destination: Gracepoint - S1 Ep. 1.fhls-1710-1.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
X-Forwarded-For: 1.146.243.159
Accept: application/json;pk=BCpkADawqM3LrTsmy4tDkB6PwE5QiKnkQF0gsdyOVDmJNyCmpHG8FbEekN-V2-y5KmH5nyVJ-8HVv9rMX37nUed-zfUhOFiHwA3XhW35sjvr_qk92T8f2dbdA9vLN-wzvdaChZeUqcj3wQOf
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3563.0 Safari/537.36
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
' -i 'https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/2199827728001/3787c027-575b-4d96-ab03-2f1de7c25179/4d6eb7e2-af93-4efb-a3d1-e26723e2fd15/10s/rendition.m3u8?fastly_token=NWZlY2IxNjJfNWU5YTg1MWJjYWU5NjFiZjYyMThjYzVjZDk4OTc0MDlkZTI1NGJlN2E2MWUwYTEyNDJhN2YxZmE0YWI0NzgxYw%3D%3D' -c copy -f mp4 'file:Gracepoint - S1 Ep. 1.fhls-1710-1.mp4.part'
ffmpeg version 4.3.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[tcp @ 0x7f868a604740] Starting connection attempt to 151.101.30.27 port 443
[tcp @ 0x7f868a604740] Successfully connected to 151.101.30.27 port 443
[hls @ 0x7f868c008a00] Skip ('#EXT-X-VERSION:3')
[hls @ 0x7f868c008a00] HLS request for url 'https://bcboltnet10tp.global.ssl.fastly.net/media/v1/hls/v4/aes128/2199827728001/3787c027-575b-4d96-ab03-2f1de7c25179/4d6eb7e2-af93-4efb-a3d1-e26723e2fd15/19dd4404-6de2-4233-a083-7e599cffcaf7/5x/segment0.ts', offset 0, playlist 0
[hls @ 0x7f868c008a00] Opening 'https://manifest.prod.boltdns.net/license/v1/aes128/2199827728001/3787c027-575b-4d96-ab03-2f1de7c25179/19dd4404-6de2-4233-a083-7e599cffcaf7?fastly_token=NWZlY2IxNjdfOTYzM2IwYWQ0NzE1M2ExNDRlYjlhNGJkM2E2ZGJlOTg3NmQwNGFjODE3ODE0ZjUxZTE3MTM1YWNkNjBlNTgxZg%3D%3D' for reading
[tcp @ 0x7f868a610780] Starting connection attempt to 151.101.30.27 port 443
[tcp @ 0x7f868a610780] Successfully connected to 151.101.30.27 port 443
[AVIOContext @ 0x7f868a534f00] Statistics: 16 bytes read, 0 seeks
[hls @ 0x7f868c008a00] Opening 'crypto+https://bcboltnet10tp.global.ssl.fastly.net/media/v1/hls/v4/aes128/2199827728001/3787c027-575b-4d96-ab03-2f1de7c25179/4d6eb7e2-af93-4efb-a3d1-e26723e2fd15/19dd4404-6de2-4233-a083-7e599cffcaf7/5x/segment0.ts' for reading
[tcp @ 0x7f868a610940] Starting connection attempt to 151.101.29.194 port 443
[tcp @ 0x7f868a610940] Successfully connected to 151.101.29.194 port 443
[h264 @ 0x7f868b01d200] Reinit context to 1024x576, pix_fmt: yuv420p
[hls @ 0x7f868c008a00] max_analyze_duration 5000000 reached at 5000000 microseconds st:0
Input #0, hls, from 'https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/2199827728001/3787c027-575b-4d96-ab03-2f1de7c25179/4d6eb7e2-af93-4efb-a3d1-e26723e2fd15/10s/rendition.m3u8?fastly_token=NWZlY2IxNjJfNWU5YTg1MWJjYWU5NjFiZjYyMThjYzVjZDk4OTc0MDlkZTI1NGJlN2E2MWUwYTEyNDJhN2YxZmE0YWI0NzgxYw%3D%3D':
  Duration: 00:42:05.32, start: 0.000000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(left), 1024x576 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Gracepoint - S1 Ep. 1.fhls-1710-1.mp4.part':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (Main), 1 reference frame (avc1 / 0x31637661), yuv420p(left), 1024x576 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
[AVIOContext @ 0x7f868a530bc0] Statistics: 1417144 bytes read, 0 seeks
[hls @ 0x7f868c008a00] HLS request for url 'https://bcboltnet10tp.global.ssl.fastly.net/media/v1/hls/v4/aes128/2199827728001/3787c027-575b-4d96-ab03-2f1de7c25179/4d6eb7e2-af93-4efb-a3d1-e26723e2fd15/19dd4404-6de2-4233-a083-7e599cffcaf7/5x/segment1.ts', offset 0, playlist 0
[hls @ 0x7f868c008a00] Opening 'crypto+https://bcboltnet10tp.global.ssl.fastly.net/media/v1/hls/v4/aes128/2199827728001/3787c027-575b-4d96-ab03-2f1de7c25179/4d6eb7e2-af93-4efb-a3d1-e26723e2fd15/19dd4404-6de2-4233-a083-7e599cffcaf7/5x/segment1.ts' for reading

......

>tcp @ 0x7f868a546c40] Starting connection attempt to 151.101.29.194 port 443
[tcp @ 0x7f868a546c40] Successfully connected to 151.101.29.194 port 443
frame=63069 fps=611 q=-1.0 size=  459776kB time=00:42:02.72 bitrate=1493.0kbits/s speed=24.4x    
[AVIOContext @ 0x7f868a41ba00] Statistics: 1116344 bytes read, 0 seeks
No more output streams to write to, finishing.
Not writing 'clli' atom. No content light level info.
Not writing 'mdcv' atom. Missing mastering metadata.
frame=63133 fps=611 q=-1.0 Lsize=  460670kB time=00:42:05.28 bitrate=1494.4kbits/s speed=24.5x    
video:460339kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.071883%
Input file #0 (https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/2199827728001/3787c027-575b-4d96-ab03-2f1de7c25179/4d6eb7e2-af93-4efb-a3d1-e26723e2fd15/10s/rendition.m3u8?fastly_token=NWZlY2IxNjJfNWU5YTg1MWJjYWU5NjFiZjYyMThjYzVjZDk4OTc0MDlkZTI1NGJlN2E2MWUwYTEyNDJhN2YxZmE0YWI0NzgxYw%3D%3D):
  Input stream #0:0 (video): 63133 packets read (471387207 bytes); 
  Total: 63133 packets (471387207 bytes) demuxed
Output file #0 (file:Gracepoint - S1 Ep. 1.fhls-1710-1.mp4.part):
  Output stream #0:0 (video): 63133 packets muxed (471387207 bytes); 
  Total: 63133 packets (471387207 bytes) muxed
[AVIOContext @ 0x7f868a40fcc0] Statistics: 14 seeks, 1811 writeouts
[AVIOContext @ 0x7f868a70a7c0] Statistics: 57256 bytes read, 0 seeks

>[ffmpeg] Downloaded 471726054 bytes
[download] 100% of 449.87MiB in 01:44
[download] 100% of 449.87MiB in 01:44
[debug] Invoking downloader on u'https://manifest.prod.boltdns.net/manifest/v1/dash/live-hbbtv15/clear/2199827728001/3787c027-575b-4d96-ab03-2f1de7c25179/6s/manifest.mpd?fastly_token=NWZlY2IxNjJfZGViZWIyMWQzNzg4NTg2MjZmZTIzMWZlM2RjMDBlZmNjNTUwZDMxNjQzZDU4YTJkYmVhNTUzYmNiMWU1OTA0ZQ%3D%3D'
[dashsegments] Total fragments: 423
[download] Destination: Gracepoint - S1 Ep. 1.fdash-32582342-4ebd-4bfb-8b84-c90fc3981b79-3.m4a

.....

>[download] 100.0% of ~39.38MiB at 939.51KiB/s ETA 00:00
[download] 100% of 39.38MiB in 01:08
[ffmpeg] Merging formats into "Gracepoint - S1 Ep. 1.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Gracepoint - S1 Ep. 1.fhls-1710-1.mp4' -i 'file:Gracepoint - S1 Ep. 1.fdash-32582342-4ebd-4bfb-8b84-c90fc3981b79-3.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Gracepoint - S1 Ep. 1.temp.mp4'
Deleting original file Gracepoint - S1 Ep. 1.fhls-1710-1.mp4 (pass -k to keep)
Deleting original file Gracepoint - S1 Ep. 1.fdash-32582342-4ebd-4bfb-8b84-c90fc3981b79-3.m4a (pass -k to keep)

**Comment by remitamine** [comment]
as far as i know FFmpeg does not have an option to specify, the rate limit, you may want to use `--hls-prefer-native` option(you may need to install PyCrypto/PyCryptodome) to use youtube-dl own downloader that does support rate limit option.

**Comment by section83** [comment]
Thanks, I couldn't find anything in the FFmpeg docs but hoped I had missed it.

Many thanks for YTDL and Happy New Year.
