### ISSUE TITLE
Vimeo w/ Password Not Working

### ISSUE THREAD

**Issue by kooshywoosh** [ytdl-org/youtube-dl#27591]
```
youtube-dl -v --video-password "BarreLove1" "https://vimeo.com/user109873352/review/428572575/dd0024554a"
```

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--video-password', 'PRIVATE', 'https://vimeo.com/user109873352/review/428572575/dd0024554a', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.12
[debug] Python version 3.9.0 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo:review] 428572575: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('clipData')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2020.11.12/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2020.11.12/libexec/lib/python3.9/site-packages/youtube_dl/extractor/vimeo.py", line 1050, in _real_extract
    clip_data = self._download_json(
KeyError: 'clipData'
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2020.11.12/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2020.11.12/libexec/lib/python3.9/site-packages/youtube_dl/extractor/vimeo.py", line 1050, in _real_extract
    clip_data = self._download_json(
KeyError: 'clipData'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2020.11.12/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2020.11.12/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 545, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('clipData')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by october262** [comment]
play the video and press F12 to bring up the debug menu, go to Network, type master
in the search box, you'll see one called master.json, copy the link 
and paste into youtube-dl > https://139vod-adaptive.akamaized.net/exp=1609466024~acl=%2F6392c144-6102-4379-ab8b-d464a4aa1652%2F%2A~hmac=5c2a9cc1799eb2be66d5cd7eb41edb8eeada0c930c8bddca45949475aa3e99c9/6392c144-6102-4379-ab8b-d464a4aa1652/sep/video/0999f70b,6e0b68f1,5cf92e40,5d60d70a,241fc4b1/master.json?base64_init=1  now delete the json?base64_init=1 and replace with .mpd the video
will now download.

**Comment by kooshywoosh** [comment]
Hm, I'm not seeing a `master.json` show up in the network tab after playing the video. It looks like Vimeo is sending the video in segments while it plays (segment-1.m4s, segment 2.m4s, etc) 

<img width="1349" alt="Screen Shot 2020-12-31 at 2 53 16 PM" src="https://user-images.githubusercontent.com/5790010/103428500-07907b00-4b78-11eb-8b19-747e41dc1be2.png">

**Comment by october262** [comment]
> Hm, I'm not seeing a `master.json` show up in the network tab after playing the video. It looks like Vimeo is sending the video in segments while it plays (segment-1.m4s, segment 2.m4s, etc)
> 
> <img alt="Screen Shot 2020-12-31 at 2 53 16 PM" width="1349" src="https://user-images.githubusercontent.com/5790010/103428500-07907b00-4b78-11eb-8b19-747e41dc1be2.png">

type the word master in the little search box in the upper left corner of the debug menu.

**Comment by kooshywoosh** [comment]
I use chrome debugging tools everyday... it's not there. You can try it yourself:

Video (which will expire at the EOY): 
https://vimeo.com/user109873352/review/428572575/dd0024554a

Password:
BarreLove1

<img width="1341" alt="Screen Shot 2020-12-31 at 3 57 21 PM" src="https://user-images.githubusercontent.com/5790010/103431166-e1230d80-4b80-11eb-8ee6-1f4b5ca5109c.png">

**Comment by october262** [comment]
> I use chrome debugging tools everyday... it's not there. You can try it yourself:
> 
> Video (which will expire at the EOY):
> https://vimeo.com/user109873352/review/428572575/dd0024554a
> 
> Password:
> BarreLove1
> 
> <img alt="Screen Shot 2020-12-31 at 3 57 21 PM" width="1341" src="https://user-images.githubusercontent.com/5790010/103431166-e1230d80-4b80-11eb-8ee6-1f4b5ca5109c.png">

try reloading the page

**Comment by kooshywoosh** [comment]
Argh, I swear I tried that 🤕 . Thanks for the info, seems to be downloading now
