### ISSUE TITLE
YouTube fails with ERROR: unable to download video data: <urlopen error [Errno 111] Connection refused>

### ISSUE THREAD

**Issue by samehboraie** [ytdl-org/youtube-dl#27608]
## Checklist

- [x ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

YouTube fails with ERROR: unable to download video data: <urlopen error [Errno 111] Connection refused>

sudo youtube-dl -v  https://www.youtube.com/watch?v=OkidaZmnADw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=OkidaZmnADw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.31
[debug] Python version 2.7.16 (CPython) - Linux-5.4.79-v7+-armv7l-with-debian-10.7
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] OkidaZmnADw: Downloading webpage
[youtube] {18} signature length 106, html5 player 5dd3f3b2
[youtube] {22} signature length 110, html5 player 5dd3f3b2
[youtube] {137} signature length 106, html5 player 5dd3f3b2
[youtube] {248} signature length 110, html5 player 5dd3f3b2
[youtube] {136} signature length 110, html5 player 5dd3f3b2
[youtube] {247} signature length 110, html5 player 5dd3f3b2
[youtube] {135} signature length 106, html5 player 5dd3f3b2
[youtube] {244} signature length 110, html5 player 5dd3f3b2
[youtube] {134} signature length 110, html5 player 5dd3f3b2
[youtube] {243} signature length 110, html5 player 5dd3f3b2
[youtube] {133} signature length 106, html5 player 5dd3f3b2
[youtube] {242} signature length 110, html5 player 5dd3f3b2
[youtube] {160} signature length 110, html5 player 5dd3f3b2
[youtube] {278} signature length 106, html5 player 5dd3f3b2
[youtube] {140} signature length 110, html5 player 5dd3f3b2
[youtube] {249} signature length 110, html5 player 5dd3f3b2
[youtube] {250} signature length 106, html5 player 5dd3f3b2
[youtube] {251} signature length 110, html5 player 5dd3f3b2
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r2---sn-uxaxjvhxbt2u-5at6.googlevideo.com/videoplayback?expire=1609454839&ei=lwDuX4G1N-m-xN8P-pC66Ac&ip=154.179.10.127&id=o-AMn9rvLtQmuc-AFXijZX1Q9lN-feklEGWDQE18Tg6Ip9&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=zg&mm=31%2C29&mn=sn-uxaxjvhxbt2u-5at6%2Csn-hgn7yn7z&ms=au%2Crdu&mv=m&mvi=2&pl=18&initcwndbps=276250&vprv=1&mime=video%2Fwebm&ns=2abIEHX47l7qCpTEPLhlPagF&gir=yes&clen=68877612&dur=1759.033&lmt=1597438225519120&mt=1609433083&fvip=2&keepalive=yes&beids=23886219&c=WEB&txp=5432432&n=I07Zy1kthwsACR_6&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgcgnd8pBk6xMMA1TFT_pmmbf9XYZrXoqXeQ_gSV9h-AkCIBVxEruEuVZ7f0JrTxKs7PbESHaNh-GkLog6Aqn6zoWB&sig=AOq0QJ8wRQIhAIjMSgyZVYstY1R9c7XHlresuEXQmF5pqsR0N_Uf0U9NAiBbn19x-LvryTsmtrzyvok1gS7aRJNQvFN9O7WanphFYw==&ratebypass=yes'
ERROR: unable to download video data: <urlopen error [Errno 111] Connection refused>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1930, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1875, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
URLError: <urlopen error [Errno 111] Connection refused>

**Comment by october262** [comment]
this link  - https://www.youtube.com/watch?v=OkidaZmnADw
works ok for me.

**Comment by samehboraie** [comment]
when I download by youtube-dl  show this error why and what is problem
have a solution

**Comment by samehboraie** [comment]
I have Raspberry pi 3 use it as pihole and download  playlist courses from youtube by youtube-dl

**Comment by dstftw** [comment]
Network issue on your side.

**Comment by Chainedge** [comment]
Some custom (or default) blocklists on pihole seem to trash *.googlevideo.com queries, so adding the address as a wildcard to the whitelist should fix it completely. Sorry for kinda necro'ing the issue thread, but I haven't seen this written anywhere. Kind of a gesture for the next person.

**Comment by Batwam** [comment]
> Some custom (or default) blocklists on pihole seem to trash *.googlevideo.com queries, so adding the address as a wildcard to the whitelist should fix it completely. Sorry for kinda necro'ing the issue thread, but I haven't seen this written anywhere. Kind of a gesture for the next person. 

That was it, thanks!
