### ISSUE TITLE
[Stitcher] Updated Site Broke Support (Version: 2020.12.31)

### ISSUE THREAD

**Issue by markmals** [ytdl-org/youtube-dl#27606]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.stitcher.com/show/threedom/episode/circles-on-a-stick-200212584', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.31
[debug] Python version 3.9.1 (CPython) - macOS-11.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] circles-on-a-stick-200212584: Requesting header
WARNING: Falling back on generic information extractor.
[generic] circles-on-a-stick-200212584: Downloading webpage
[generic] circles-on-a-stick-200212584: Extracting information
[generic] 200212584: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 200212584: Downloading webpage
[generic] 200212584: Extracting information
ERROR: Unsupported URL: https://www.stitcher.com/embed/1001422/200212584
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2020.12.31/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2020.12.31/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2020.12.31/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2020.12.31/libexec/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 3448, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.stitcher.com/embed/1001422/200212584
```

## Description

Stitcher recently updated their website and web player and [the existing Stitcher extractor](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/stitcher.py) no longer works.

**Comment by october262** [comment]
try youtube-dl https://21963.mc.tritondigital.com/OMNY_THREEDOM_PODCAST_P/media-session/c4088d30-f797-4bbf-bbde-0062de5e592e/d/clips/aaea4e69-af51-495e-afc9-a9760146922b/5d8484bf-c5d2-4d0d-9e8b-aa8601684c42/9d01842d-5860-404f-99f2-aca200392911/audio/direct/t1609434072/Circles_On_A_Stick.mp3?t=1609434072&in_playlist=8f2027c0-0cef-4f82-8dd6-aa8601684c4b&utm_source=Podcast

**Comment by markmals** [comment]
Don't even need youtube-dl to download that link; that's a direct link to the content. Youtube-dl is meant to extract the content from the canonical link and then download it.
