### ISSUE TITLE
How to search for an exact phrase with ytsearch

### ISSUE THREAD

**Issue by pygeonburger** [ytdl-org/youtube-dl#27607]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Sometimes when you search things in YouTube, it will show a button saying "Showing results for:" and then a slightly different phrase than what I actually wanted to search. Next to that, they have a button saying "Search instead for:" and the actual phrase I wanted to search.

When using ytsearch in youtube-dl, how can I be sure that it's searching for the _exact_ phrase I want, and not some slightly modified phrase YouTube suggests?

Thanks in advance for any help.

**Comment by dstftw** [comment]
Put the query in quotes obviously.
