### ISSUE TITLE
SBS "Unsupported URL"

### ISSUE THREAD

**Issue by falcorr** [ytdl-org/youtube-dl#27629]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.sbs.com.au/ondemand/program/inside-windsor-castle?play=1278558787526', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.12.31
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-essentials_build-www.gyan.dev, ffprobe 4.3.1-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[generic] inside-windsor-castle?play=1278558787526: Requesting header
WARNING: Falling back on generic information extractor.
[generic] inside-windsor-castle?play=1278558787526: Downloading webpage
[generic] inside-windsor-castle?play=1278558787526: Extracting information
ERROR: Unsupported URL: https://www.sbs.com.au/ondemand/program/inside-windsor-castle?play=1278558787526
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpabf7r3hs\build\youtube_dl\extractor\generic.py", line 3448, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.sbs.com.au/ondemand/program/inside-windsor-castle?play=1278558787526
```

## Description
SBS, previously supported, appears to be no longer. 

Links I'm attempting without success: 

- https://www.sbs.com.au/ondemand/program/inside-windsor-castle?play=1278558787526
- https://www.sbs.com.au/ondemand/program/inside-windsor-castle?play=1283505731842
- https://www.sbs.com.au/ondemand/program/inside-windsor-castle?play=1289278531557
- https://www.sbs.com.au/ondemand/program/inside-windsor-castle?play=1293198403790

**Comment by fossdd** [comment]
The Supported URLs are here:

https://github.com/ytdl-org/youtube-dl/blob/75972e200d033429bf9d34793ad3ffc813042347/youtube_dl/extractor/sbs.py#L13

I guess that's the point which needs to be fixed
