### ISSUE TITLE
Is there a way to use --download-archive while also use --skip-download 

### ISSUE THREAD

**Issue by Tydoki** [ytdl-org/youtube-dl#27622]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

So my goal is to be able to download twitch vod information (in the form of a -o templated file)
To clarify I want to write a file using -o which writes a file while using --skip-download
To get any file written using the -o template, while using --skip-download, I chose to use --write-thumbnail 

The problem is that everytime I run the command on a users twitch vod list it has to go through all of the vods and not just the most recent one. If downloading a video the solution would be to use --download-archive. But that doesn't work with --skip-download.  

Is there any way to get vod information (uploader, url, title, etc) written to a file while also using --download-archive?

**Comment by dstftw** [comment]
No.
