### ISSUE TITLE
Add support on apple music

### ISSUE THREAD

**Issue by jefferson018200306** [ytdl-org/youtube-dl#27624]
I tried to download music on apple music and it says unsupported URL, please add a support on apple music so we can download higher quality music using your app

**Comment by jefferson018200306** [comment]
This is the command failed outputs:







WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: https://music.apple.com/ph/album/1544839500?uo=4&app=music&at=1000lNNy&lId=22707162&cId=none&sr=1&src=Linkfire&itscg=30440&itsct=catchall_p1&ct=LFV_fd825e696d55e7ee0a322a2e145e14f4

**Comment by duchenpaul** [comment]
You must be joking

**Comment by jefferson018200306** [comment]
> You must be joking

No, it's real

**Comment by derjp** [comment]
youtube-dl doesn't support any sites which require DRM circumvention, if they would, this project couldn't exist publicly

**Comment by jefferson018200306** [comment]
> youtube-dl can't support any services which would require DRM circumvention

Okay thanks 💞 I just thought there was no DRM circumvention on apple music that's why I posted this ...
