### ISSUE TITLE
Is it possible to download the latest uploaded video all categories from YouTube with yt-dl?

### ISSUE THREAD

**Issue by bitcoinmeetups** [ytdl-org/youtube-dl#27628]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

Is it possible to download the latest uploaded video all categories from YouTube with yt-dl?

So a lot of people upload videos to YouTube. Probably thousands or tens of thousands of videos every minute.

Would it be possible with youtube-dl to download the latest one, all categories?

I have always wanted to watch random YouTube-videos. 

If anyone has a short one-liner that would work out of the box and just downloads the latest YouTube-video from all categories, then that would be much appreciated.

BM

OS: Linux

**Comment by remitamine** [comment]
No(not offered by `youtube.com` anyway).
