### ISSUE TITLE
Video (a Trailer) was downloaded from IMDb; couldn't find it!

### ISSUE THREAD

**Issue by RangaSE** [ytdl-org/youtube-dl#27632]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
Video (a Trailer) was downloaded from IMDb; couldn't find it!

WRITE QUESTION HERE
Greetings!
Since, YT-DL supports IMDb, I want download a Russian Trailer and also experiment the same. with IMDb,, for first time. As I can't see the downloaded video, I took the log for the same. These following are the findings / Log:
===
Microsoft Windows [Version 10.0.18363.1256]
(c) 2019 Microsoft Corporation. All rights reserved.

( 01-01-2021 & 16:54:23.44 | C:\Users\Notebook> YouTube-DL[2020.12.31] -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -ciw --no-playlist --write-auto-sub --write-sub --embed-thumbnail -o "~\Videos\%(title)s (u%(upload_date)s; 0,2,19; %(height)sp%(fps)s)YT '%(uploader)s'.%(ext)s" -- https://www.imdb.com/video/vi2708846873?playlistId=nm6615975
[imdb] 2708846873: Downloading JSON metadata
[imdb] 2708846873: Downloading m3u8 information
[imdb] 2708846873: Downloading webpage
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 14
[download] Destination: C:\Users\Notebook\Videos\The Guardians (uNA; 0,2,19; 816pNA)YT 'NA'.mp4
[download] 100% of 143.49MiB in 03:48
[ffmpeg] Fixing malformed AAC bitstream in "C:\Users\Notebook\Videos\The Guardians (uNA; 0,2,19; 816pNA)YT 'NA'.mp4"
[embedthumbnail] There aren't any thumbnails to embed

( 01-01-2021 & 16:58:20.96 | C:\Users\Notebook> Cls		' ; # Where is 'this' Video file? ** Missing! ** We'll Check with with '-v' (--verbose) option.
( 01-01-2021 & 17:01:59.74 | C:\Users\Notebook> YouTube-DL[2020.12.31] -v -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -ciw --no-playlist --write-auto-sub --write-sub --embed-thumbnail -o "~\Videos\%(title)s (u%(upload_date)s; 0,2,19; %(height)sp%(fps)s)YT '%(uploader)s'.%(ext)s" -- https://www.imdb.com/video/vi2708846873?playlistId=nm6615975
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '-ciw', '--no-playlist', '--write-auto-sub', '--write-sub', '--embed-thumbnail', '-o', "~\\Videos\\%(title)s (u%(upload_date)s; 0,2,19; %(height)sp%(fps)s)YT '%(uploader)s'.%(ext)s", '--', 'https://www.imdb.com/video/vi2708846873?playlistId=nm6615975']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.31
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[imdb] 2708846873: Downloading JSON metadata
[imdb] 2708846873: Downloading m3u8 information
[imdb] 2708846873: Downloading webpage
[debug] Invoking downloader on 'https://imdb-video.media-imdb.com/vi2708846873/1428962085883-7pkt3g-1563571529511.m3u8'
[download] C:\Users\Notebook\Videos\The Guardians (uNA; 0,2,19; 816pNA)YT 'NA'.mp4 has already been downloaded
[download] 100% of 132.72MiB
[debug] ffmpeg command line: ffprobe -show_streams "file:C:\Users\Notebook\Videos\The Guardians (uNA; 0,2,19; 816pNA)YT 'NA'.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "C:\Users\Notebook\Videos\The Guardians (uNA; 0,2,19; 816pNA)YT 'NA'.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\Notebook\Videos\The Guardians (uNA; 0,2,19; 816pNA)YT 'NA'.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:C:\Users\Notebook\Videos\The Guardians (uNA; 0,2,19; 816pNA)YT 'NA'.temp.mp4"
[embedthumbnail] There aren't any thumbnails to embed

( 01-01-2021 & 18:19:10.15 | C:\Users\Notebook> Cls		' ; # Can not Find 'this' Video file. Let me try other methods, such as 'Multiformst Video Downloader'.
' ; # YES! 'Video Downloader Multiformst', DID download the file, only resolution, '854x362' pixel resolution.
' ; # Let me see! The Last chance, before reporting as a 'bug'; use %(resolution)s , instead of %(height)sp ...
YouTube-DL[2020.12.31] -v -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -ciw --no-playlist --write-auto-sub --write-sub --embed-thumbnail -o "~\Videos\%(title)s (u%(upload_date)s; 0,2,19; %(resolution)s%(fps)s)YT '%(uploader)s'.%(ext)s" -- https://www.imdb.com/video/vi2708846873?playlistId=nm6615975

( 01-01-2021 & 19:17:08.67 | C:\Users\Notebook> YouTube-DL[2020.12.31] -v -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -ciw --no-playlist --write-auto-sub --write-sub --embed-thumbnail -o "~\Videos\%(title)s (u%(upload_date)s; 0,2,19; %(resolution)s%(fps)s)YT '%(uploader)s'.%(ext)s" -- https://www.imdb.com/video/vi2708846873?playlistId=nm6615975
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '-ciw', '--no-playlist', '--write-auto-sub', '--write-sub', '--embed-thumbnail', '-o', "~\\Videos\\%(title)s (u%(upload_date)s; 0,2,19; %(resolution)s%(fps)s)YT '%(uploader)s'.%(ext)s", '--', 'https://www.imdb.com/video/vi2708846873?playlistId=nm6615975']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.12.31
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[imdb] 2708846873: Downloading JSON metadata
[imdb] 2708846873: Downloading m3u8 information
[imdb] 2708846873: Downloading webpage
[debug] Invoking downloader on 'https://imdb-video.media-imdb.com/vi2708846873/1428962085883-7pkt3g-1563571529511.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 14
[download] Destination: C:\Users\Notebook\Videos\The Guardians (uNA; 0,2,19; 1920x816NA)YT 'NA'.mp4
[download] 100% of 143.49MiB in 03:49
[debug] ffmpeg command line: ffprobe -show_streams "file:C:\Users\Notebook\Videos\The Guardians (uNA; 0,2,19; 1920x816NA)YT 'NA'.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "C:\Users\Notebook\Videos\The Guardians (uNA; 0,2,19; 1920x816NA)YT 'NA'.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\Notebook\Videos\The Guardians (uNA; 0,2,19; 1920x816NA)YT 'NA'.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:C:\Users\Notebook\Videos\The Guardians (uNA; 0,2,19; 1920x816NA)YT 'NA'.temp.mp4"
[embedthumbnail] There aren't any thumbnails to embed

( 01-01-2021 & 19:21:13.42 | C:\Users\Notebook> Cls		' ; # 'This one ALSO' Missing! Any Help?!
===
P.S.: At last! I DO find the files, but, they are downloaded and dated as 'July 20, 2019'. Why (How did this happen?) and any remedy?
Regards, RS.
P.P.S.: This is a Wonderful program and all of you, I'm proud of you all !
I'm "too saturated with programming" to help! OOPS!! Sorry !!!

**Comment by dstftw** [comment]
```
--no-mtime                       Do not use the Last-modified header to set
                                 the file modification time
```
