### ISSUE TITLE
HUGE FUCKING BUG

### ISSUE THREAD

**Issue by connuh** [ytdl-org/youtube-dl#27631]
it's in python

**Comment by fossdd** [comment]
Plese report to Python: https://bugs.python.org/

I think this issue can be closed.

**Comment by connuh** [comment]
NO. NO IT CAN NOT.

**Comment by connuh** [comment]
Listen here, mate, this is a pretty damn big issue.

Why the fuck have you closed it? The program is still python.
I am outraged, enjoy the e-mails.

**Comment by llacb47** [comment]
Are you trolling? What's wrong with python?

**Comment by connuh** [comment]
WHATS WRONG WITH PYTHON?

ANSWER: PYTHON.
