### ISSUE TITLE
Resuming / partial download when outputting to stdout?

### ISSUE THREAD

**Issue by masklinn** [ytdl-org/youtube-dl#27647]
## Checklist
- [X] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2021.01.03**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

youtube-download can resume downloads (by default and / or by using `-c`), but this logically only works when outputting to a proper file. When using `-o -` and outputting to stdout (e.g. scripting around ydl) there seems to be no way to provide ydl with a "resume offset".

**Comment by dstftw** [comment]
It's not supposed to support resume when outputting to stdout.
