### ISSUE TITLE
NRK inconsistent file name of downloaded subtext (using -o option)

### ISSUE THREAD

**Issue by VikingKing** [ytdl-org/youtube-dl#27648]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

youtube-dl -v --no-warnings --write-sub --convert-subs srt -k https://tv.nrk.no/serie/dyrlegen/sesong/1/episode/1/avspiller -o foo.mp4
[debug] System config: []
[debug] User config: ['-f', 'best[height<=720]', '--no-call-home']
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-warnings', '--write-sub', '--convert-subs', 'srt', '-k', 'https://tv.nrk.no/serie/dyrlegen/sesong/1/episode/1/avspiller', '-o', 'foo.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.03
[debug] Git HEAD: ac71fd591
[debug] Python version 3.6.9 (CPython) - Linux-5.4.0-58-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[NRKTVEpisode] dyrlegen/sesong/1/episode/1: Downloading webpage
[debug] Using fake IP 84.215.43.139 (NO) as X-Forwarded-For.
[NRK] KOIF20000120: Downloading manifest JSON
[NRK] KOIF20000120: Downloading m3u8 information
[NRK] KOIF20000120: Downloading metadata JSON
[NRK] KOIF20000120: Downloading programs JSON
[info] Writing video subtitles to: foo.nb-nor.vtt

File is named  "foo.nb-nor.vtt"

youtube-dl -v --no-warnings --write-sub --convert-subs srt -k https://tv.nrk.no/serie/team-bachstad/sesong/8/episode/4/avspiller -o foo.mp4
[debug] System config: []
[debug] User config: ['-f', 'best[height<=720]', '--no-call-home']
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-warnings', '--write-sub', '--convert-subs', 'srt', '-k', 'https://tv.nrk.no/serie/team-bachstad/sesong/8/episode/4/avspiller', '-o', 'foo.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.03
[debug] Git HEAD: ac71fd591
[debug] Python version 3.6.9 (CPython) - Linux-5.4.0-58-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[NRKTVEpisode] team-bachstad/sesong/8/episode/4: Downloading webpage
[debug] Using fake IP 84.211.85.9 (NO) as X-Forwarded-For.
[NRK] MUHU13000420: Downloading manifest JSON
[NRK] MUHU13000420: Downloading m3u8 information
[NRK] MUHU13000420: Downloading metadata JSON
[NRK] MUHU13000420: Downloading programs JSON
[info] Writing video subtitles to: foo.nb-ttv.vtt

File is named "foo.nb-ttv.vtt"

## Description

Downloaded sub text file are named "**foo.nb-nor.vtt**" on some downloads and "**foo.nb-ttv.vtt**" on others.

See examples above

**Comment by dstftw** [comment]
This is what's provided by nrk.
