### ISSUE TITLE
ffmpeg Merging Issue

### ISSUE THREAD

**Issue by leroadrunner** [ytdl-org/youtube-dl#27658]
Unable to merging files which have been downloaded from vimeo. Looks like **ffmpeg** problem 
youtube-dl https://vimeo.com/393118240

`youtube-dl --version`
2021.01.03

`ls -ltra`
-rwxrwxrwx   1 ro  staff   116M  4 jan 17:13 In Pursuit of Ghosts - Max Cooper & Tom Hodge-393118240.fdash-fastly_skyfire_sep-video-7cf60e13.mp4
-rwxrwxrwx   1 ro  staff   5,7M  4 jan 17:13 In Pursuit of Ghosts - Max Cooper & Tom Hodge-393118240.fdash-fastly_skyfire_sep-audio-24c57424.m4a
drwxr-xr-x   6 ro  staff   192B  4 jan 17:13 .
-rwxrwxrwx   1 ro  staff     0B  4 jan 18:28 In Pursuit of Ghosts - Max Cooper & Tom Hodge-393118240.temp.mp4

`youtube-dl https://vimeo.com/393118240 -v`
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://vimeo.com/393118240', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.03
[debug] Python version 2.7.10 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-91298-g07d1c4ae3f-tessus, ffprobe N-91298-g07d1c4ae3f-tessus
[debug] Proxy map: {}
[vimeo] 393118240: Downloading webpage
[vimeo] 393118240: Extracting information
[vimeo] 393118240: Downloading JSON metadata
[vimeo] 393118240: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 393118240: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 393118240: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 393118240: Downloading fastly_skyfire m3u8 information
[vimeo] 393118240: Downloading fastly_skyfire m3u8 information
[vimeo] 393118240: Downloading akfire_interconnect_quic MPD information
[vimeo] 393118240: Downloading akfire_interconnect_quic MPD information
[vimeo] 393118240: Downloading fastly_skyfire MPD information
[vimeo] 393118240: Downloading fastly_skyfire MPD information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1609786060-0xac3aee61e8dde30f40e18173d6804c575401153d/1b6fec98-e8ce-4435-b799-c4de330ad051/sep/video/24c57424,80d78c8b,d8bd727f,7cf60e13,2e83c0a7/master.mpd?base64_init=1'
[download] In Pursuit of Ghosts - Max Cooper & Tom Hodge-393118240.fdash-fastly_skyfire_sep-video-7cf60e13.mp4 has already been downloaded
[download] 100% of 116.37MiB
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1609786060-0xac3aee61e8dde30f40e18173d6804c575401153d/1b6fec98-e8ce-4435-b799-c4de330ad051/sep/video/24c57424,80d78c8b,d8bd727f,7cf60e13,2e83c0a7/master.mpd?base64_init=1'
[download] In Pursuit of Ghosts - Max Cooper & Tom Hodge-393118240.fdash-fastly_skyfire_sep-audio-24c57424.m4a has already been downloaded
[download] 100% of 5.66MiB
[ffmpeg] Merging formats into "In Pursuit of Ghosts - Max Cooper & Tom Hodge-393118240.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:In Pursuit of Ghosts - Max Cooper & Tom Hodge-393118240.fdash-fastly_skyfire_sep-video-7cf60e13.mp4' -i 'file:In Pursuit of Ghosts - Max Cooper & Tom Hodge-393118240.fdash-fastly_skyfire_sep-audio-24c57424.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:In Pursuit of Ghosts - Max Cooper & Tom Hodge-393118240.temp.mp4'
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2075, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 523, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
**FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)**

`ffmpeg -y -loglevel 'repeat+info' -i 'file:In Pursuit of Ghosts - Max Cooper & Tom Hodge-393118240.fdash-fastly_skyfire_sep-video-7cf60e13.mp4' -i 'file:In Pursuit of Ghosts - Max Cooper & Tom Hodge-393118240.fdash-fastly_skyfire_sep-audio-24c57424.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:In Pursuit of Ghosts - Max Cooper & Tom Hodge-393118240.temp.mp4'`
ffmpeg version N-91298-g07d1c4ae3f-tessus Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.1.0 (clang-902.0.39.2)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 18.102 / 56. 18.102
  libavcodec     58. 20.102 / 58. 20.102
  libavformat    58. 17.100 / 58. 17.100
  libavdevice    58.  4.101 / 58.  4.101
  libavfilter     7. 25.100 /  7. 25.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
[libaom-av1 @ 0x7fbcab010c00] 0.1.0-9800-g3d08714ad
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:In Pursuit of Ghosts - Max Cooper & Tom Hodge-393118240.fdash-fastly_skyfire_sep-video-7cf60e13.mp4':
  Metadata:
    major_brand     : iso5
    minor_version   : 512
    compatible_brands: iso5iso6av01mp41
    encoder         : Lavf58.64.100
  Duration: 00:03:06.00, start: 0.000000, bitrate: 5248 kb/s
    Stream #0:0(und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 1920x1080, 5246 kb/s, SAR 1:1 DAR 16:9, 24 fps, 24 tbr, 12288 tbn, 12288 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'file:In Pursuit of Ghosts - Max Cooper & Tom Hodge-393118240.fdash-fastly_skyfire_sep-audio-24c57424.m4a':
  Metadata:
    major_brand     : iso5
    minor_version   : 512
    compatible_brands: iso5iso6mp41
    encoder         : Lavf58.64.100
  Duration: 00:03:06.01, start: 0.000000, bitrate: 255 kb/s
    Stream #1:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 246 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[mp4 @ 0x7fbca9006800] AV1 muxing is currently not supported.
Could not write header for output file #0 (incorrect codec parameters ?): Not yet implemented in FFmpeg, patches welcome
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)

**Comment by dstftw** [comment]
Update ffmpeg and try again.
