### ISSUE TITLE
Gnomon workshop sudcription personal back up

### ISSUE THREAD

**Issue by sessa2** [ytdl-org/youtube-dl#27667]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hello there,
I got a subscription to a E-learn platform, The Gnomon Workshop (https://www.thegnomonworkshop.com/). It's similar to Pluralsight, the one that you already have in your list. I would like to do some personal back up of some tutorials that I'm following. 
It's using .m4f videos... Even with my login password, I have a ERROR: Unable to download webpage: HTTP Error 403:
Do I need to use an authentication data or something else?

Many thanks.

Here are some info from the Dev tools:
Host: bcbolt446c5271-a.akamaihd.net
Origin: https://www.thegnomonworkshop.com
Referer: https://www.thegnomonworkshop.com/

GET: https://bcbolt446c5271-a.akamaihd.net/media/v1/dash/live/cenc/4276901731001/af5d1a09-adfe-4621-be1f-48f4eff9022b/b7adab3b-ef60-4cab-97a5-48736885d4ea/fa947334-21b6-4d8f-b2e8-4b8c92515201/3x/segment12.m4f?akamai_token=exp=1609822709~acl=/media/v1/dash/live/cenc/4276901731001/af5d1a09-adfe-4621-be1f-48f4eff9022b/b7adab3b-ef60-4cab-97a5-48736885d4ea/*~hmac=52fd49006355a54f4336f7babab0b5ee4e578420bf7614042ec8cd274191415

**Comment by dstftw** [comment]
Unsupported.
