### ISSUE TITLE
[Pluralsight] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError())

### ISSUE THREAD

**Issue by Somoud** [ytdl-org/youtube-dl#27663]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--username', 'PRIVATE', '--password', 'PRIVATE', '-o', '~/C:\\Users\\PalCobra\\Desktop\\New folder (3)/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', '--min-sleep-interval', '60', '--max-sleep-interval', '80', 'https://app.pluralsight.com/library/courses/ethical-hacking-understanding/table-of-contents', '--playlist-start', '1']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-01-01-git-63505fc60a-full_build-www.gyan.dev, ffprobe 2021-01-01-git-63505fc60a-full_build-www.gyan.dev
[debug] Proxy map: {}
[pluralsight:course] ethical-hacking-understanding: Downloading JSON metadata
[download] Downloading playlist: Ethical Hacking: Understanding Ethical Hacking
[pluralsight:course] playlist Ethical Hacking: Understanding Ethical Hacking: Collected 86 video ids (downloading 86 of them)
[download] Downloading video 1 of 86
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\YoutubeDL.py", line 2248, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default


C:\Windows\system32>
```

## Description
This is the parameter I use:
``` youtube-dl --username "XXX@gmail.com" --password "XXX" -o "~/C:\Users\XXX\Desktop\New folder (3)/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" --min-sleep-interval 60 --max-sleep-interval 80 https://app.pluralsight.com/library/courses/ethical-hacking-understanding/table-of-contents --playlist-start 1```

**The main error:**

1. 
As the below image shows, I have begun downloading a course from Pluralsight. Unfortunately, after the first video of the third module, I have gotten this error. I searched for issues like this, but I did not get any plain solution.

![Unable to download webpage HTTP Error 403 Forbidden (caused by HTTPError](https://user-images.githubusercontent.com/33291925/103573430-e496fb80-4ed6-11eb-84ba-acb3171c7e96.jpg)

2. URLs are alive and playable in a browser:
![provided URLs are alive and playable in a browser](https://user-images.githubusercontent.com/33291925/103573513-0bedc880-4ed7-11eb-841d-f30518775e70.jpg)

3. Courses downloaded:
![6](https://user-images.githubusercontent.com/33291925/103576406-c1227f80-4edb-11eb-8e17-837bfa6d7c7b.jpg)

4. For the account credentials, you can get free subscription for one year via this link:
[https://www.pluralsightone.org/product/education/code-org-redemption-3m](url)

5. After completing registration, you can get the courses via this link:
[https://app.pluralsight.com/paths](url)

**Note:** It's better to delete the website cookies, cashed and your former credentials, because If you don't do this, the website will redirect you to your former accounts when you complete filling the subscription form. 
On completing registration check your email inbox.

**Comment by Somoud** [comment]
SHOW me where it's duplicated??!

**Comment by egrinant** [comment]
@Somoud This is the same as [that one](https://github.com/ytdl-org/youtube-dl/issues/26331) and [if you do some research](https://github.com/ytdl-org/youtube-dl/issues?q=pluralsight) you will find a lot more duplicates.
