### ISSUE TITLE
[YouTube] Unsupported JS expression '[1146652591,'

### ISSUE THREAD

**Issue by mmimeault** [ytdl-org/youtube-dl#27664]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
fatal_error: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1273, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1186, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1250, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 91, in interpret_expression
    right_val = self.interpret_expression(
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 188, in interpret_expression
    x, abort = self.interpret_statement(
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '[1146652591,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '[1146652591,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I have been using YouTube DL for Youtube extraction via Python for a long time.
I am doing a lot of extractions by days as it is used as a service.

Since December 1st I am seeing a huge drop in success extractions. We already categorized most of the "error". But now 95%+ of our extractions are failing with that same error.
I have seen a drop from 90% success extraction to 5%. For no specific video as we allow extraction for almost every YouTube video.

But when I run those extractions from my computer everything is normal.
I think it does that after a "while" (or a lot of extractions for the same video)... 
I emit that conclusion because I see a lot of success for that video, and suddenly they all fail. And then it succeeds again and fails...

Do you guys think of anything? I rely on YouTube-Dl, so I hope we can find a tweak or anything to help the situation.

**Comment by mmimeault** [comment]
What can I provide?

**Comment by dstftw** [comment]
Read new issue template.

**Comment by mmimeault** [comment]
@dstftw I updated the bug report with the verbose log.

**Comment by mmimeault** [comment]
Just wanted to say the issue has been fixed, we found the "problem".
It was using a mobile user-agent. Resulting in a different `base.js` obviously not supported by the project.
Probably YouTube has released something in December because it was working before.

Thanks anyway.
