### ISSUE TITLE
[Question] Can I download wav file (not mp3 file) from youtube link?

### ISSUE THREAD

**Issue by sooftware** [ytdl-org/youtube-dl#27676]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

As mentioned title, Can I download wav file (not mp3 file) from youtube link??  
I wanna download wav file (and 16k sample rate) from youtube link. Can I?  
Thank You!!

**Comment by dstftw** [comment]
Youtube does not provide wav.
