### ISSUE TITLE
Is there any difference between none and null in JSON dump?

### ISSUE THREAD

**Issue by PRESFIL** [ytdl-org/youtube-dl#27679]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

I use `youtube-dl -j` to *dump JSON metadata*, and some extractors return `none`s, some `null`s in place of empty fields, which breaks handling in custom scripts. Specifically, I'm comparing `youtube` and `gerenic` extractors. `vcodec` property for `youtube` extractor can be `none`, `generic` extractor returns `null`.

**Comment by remitamine** [comment]
vcodec == "none" -> the file does not have a video track.
vcodec == null -> video codec not known.
