### ISSUE TITLE
SSL certificate - unable to verify _ssl.c:600  - Youtube  

### ISSUE THREAD

**Issue by robbiedobbie1** [ytdl-org/youtube-dl#27688]
## Checklist

- [x ] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.03**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
C:\Users\Rob\Desktop\RjnResources>youtube-dl.exe -v youtube.com/watch?v=WjQ7UalDpLE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'youtube.com/watch?v=WjQ7UalDpLE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.01.03
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.3.1-2020-09-21-full_build-www.gyan.dev, ffprobe 4.3.1-2020-09-21-full_build-www.gyan.dev
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[youtube] WjQ7UalDpLE: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600
)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\extractor\common.py"
, line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\YoutubeDL.py", line
2248, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\utils.py", line 2736
, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open

```

## Description

result. no video. immediate closure of command prompt. 
expected. video with audio.  no special parameters applied. just default.  youtube-dl.exe  youtube-dl.exe -v youtube.com/watch?v=WjQ7UalDpLE

**Comment by robbiedobbie1** [comment]
"result. no video. immediate closure of command prompt.
expected. video with audio. no special parameters applied. just default. youtube-dl.exe youtube-dl.exe -v youtube.com/watch?v=WjQ7UalDpLE" should be 

result. no video. immediate closure of command prompt.
expected. video with audio. no special parameters applied. just default youtube-dl.exe **call. eg.**  _youtube-dl.exe -v youtube.com/watch?v=WjQ7UalDpLE_

**Comment by robbiedobbie1** [comment]
sorry for duplication.  damn this moves fast!  in a good way :) sorry again.

**Comment by robbiedobbie1** [comment]
am none the wiser.  still having the issue. Sergey marked as a duplicate and closed but not explained or redirected to solution or indeed the reason. 
Can somebody please advise?

**Comment by robbiedobbie1** [comment]
ok. well clearly i've come to the wrong place.  so the answer.. sorry i mean "workaround", is to deny ssl checking..  this is a really bad solution... it's not an option. how did ssl checking fail in ytdl yet browser work fine. ???  there is no official answer. just marked as duplicate.  To me, this is a "canary".  youtuble-dl is NOT safe and is compromised by government agencies.  you decide.  if you persist and ignore the safety ssl provides.. then here is the workaround:  **--no-check-certificate**

**Comment by CatPlanet** [comment]
This issue continues to haunt youtube-dl and all I see is "duplicate" this "duplicate" that, unsafe hacks and no real solution.
