### ISSUE TITLE
How can I download .json for an unaired live stream who's link is live

### ISSUE THREAD

**Issue by FortuneSeller** [ytdl-org/youtube-dl#27687]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

I'm trying to download the .json and thumbnail of a not yet aired live stream who's link is already live
The command I used is:  
youtube-dl --write-info-json --write-thumbnail  --skip-download https://www.youtube.com/watch?v=dvZITERT7Rw

I get the following error message: 
ERROR: This live event will begin in 53 days.

Is there anyway I can make youtube-dl download the data that is already there before the stream goes live?

**Comment by dstftw** [comment]
Not possible.
