### ISSUE TITLE
[RaiPlay] Subtitle extraction?

### ISSUE THREAD

**Issue by rusemode** [ytdl-org/youtube-dl#27698]
Asking someone that is familiar with downloading from RaiPlay, is it possible to extract a subtitle file? If so, is it an .srt? How do they get extracted? I looked up other threads about this but I'm not very familar with the coding so I was hoping someone could lend me a hand. This is the video with the subtitles in question. https://www.raiplay.it/video/2020/12/Report---04-01-2021-2e90f1de-8eee-4de4-ac0e-78d21db5b600.html
Thank you.

**Comment by Kenan-Kamel** [comment]
I'm not sure if this would help but, I did some search and I hope this could help.
https://www.tuneskit.com/freeware-tips/extract-subtitles-from-videos-for-free.html

**Comment by remitamine** [comment]
> is it possible to extract a subtitle file?

currently the subtitle is not detected by youtube-dl.

> is it an .srt?

yes.

**Comment by nixxo** [comment]
the website has changed (at least in the page provided as example)

the subtitle url is no longer at the "subtitles" key in the json but in the "subtitlesArray" key and, as the name suggests, is a list of subtitles in variuos languages (in theory). The provided url only has an italian subtitle.

here the json of the page where the info as are extracted: https://www.raiplay.it/video/2020/12/Report---04-01-2021-2e90f1de-8eee-4de4-ac0e-78d21db5b600.json

but, for example the url in the TESTS, the "subtitles" key is still used.

I'll modify the function that extracts the subtitles to handle both cases and do a PR.

**Comment by rusemode** [comment]
Wow, thank you for the thorough response
(I will take this Italian subtitles and actually make an English file if you are interested in watching that report by any chance)

**Comment by nixxo** [comment]
sono italiano... ;-)

**Comment by rusemode** [comment]
> sono italiano... ;-)

Grazie mille per il tuo aiuto, ho visto che github ha rimosso il direct message, potresti contattarmi? Ho lasciato la mia mail sul mio profilo! Volevo chiedere un paio di cose ma non voglio fare spam qui...
