### ISSUE TITLE
run youtube-dl in foreground

### ISSUE THREAD

**Issue by monsrud** [ytdl-org/youtube-dl#27695]
## Checklist

- [ X] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Is there any way to get youtube-dl to not release back to the prompt until all parts of the download and processing are complete? Like, a run in foreground option. When I run the script, I would like the terminal to not return to a prompt until all downloading and processing has completed. Currently, the shell prompt returns long before everything else is done. I am guessing there is an option for this but I was unable to find it.

I am using 2021.01.03 on alpine linux.

Thank you.

**Comment by dstftw** [comment]
It will not until told to do so.
