### ISSUE TITLE
ARNING: Requested formats are incompatible for merge and will be merged into mkv.

### ISSUE THREAD

**Issue by hongyi-zhao** [ytdl-org/youtube-dl#27693]
On Ubuntu 20.10, I use the latest version of youtube-dl to download the vedio from youtube as shown below:

```
$ youtube-dl --proxy socks5://127.0.0.1:18889 'https://www.youtube.com/watch?v=jr0UtCKZ6vI'
[youtube] jr0UtCKZ6vI: Downloading webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] 曾仕强-尋廬講壇《易經的智慧》下-jr0UtCKZ6vI.mkv has already been downloaded and merged
```

As you can see, it gives the following warning:

`WARNING: Requested formats are incompatible for merge and will be merged into mkv.`

How to fix it?

Regards,
HY

**Comment by dstftw** [comment]
Select formats compatible to merge in whatever container you need.
