### ISSUE TITLE
Download video always with Uploader as Artist 

### ISSUE THREAD

**Issue by fuchinoko** [ytdl-org/youtube-dl#27697]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Concerning , https://github.com/ytdl-org/youtube-dl/issues/27617 is there a way, to download with Uploader as Artist always though? --add-metadata do this thing only when "Artist" in yotube video is not provided, so we get Uploader as Artist, but if provided, like in picture 
![image](https://user-images.githubusercontent.com/25351724/103788745-4038c480-5050-11eb-9afa-03c54d1c0173.png)
then Uploader will not be written in metadata.

**Comment by dstftw** [comment]
No.

**Comment by fuchinoko** [comment]
справедливо
