### ISSUE TITLE
download videos from Bitchute.com

### ISSUE THREAD

**Issue by jd1008** [ytdl-org/youtube-dl#27694]
I tried to download video from
https://www.bitchute.com/video/LYVfcTS7RVoT

and youtube-dl was not able to get it.
Hope you can add support to that website.
Other friends told me it can download from the site, 
but only the audio-less video file.

Hope you can make it work just like on youtube.

Thanx!!!

## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
# ~/bin/youtube-dl -v -F https://www.bitchute.com/video/LYVfcTS7RVoT/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.bitchute.com/video/LYVfcTS7RVoT/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.03
[debug] Python version 3.9.1 (CPython) - Linux-5.8.15-301.fc33.x86_64-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe N-51556-ge278500
[debug] Proxy map: {}
[BitChute] LYVfcTS7RVoT: Downloading webpage
[BitChute] LYVfcTS7RVoT: Checking video URL
[info] Available formats for LYVfcTS7RVoT:
format code  extension  resolution note
0            mp4        unknown 
```

## Description

WRITE DESCRIPTION HERE
The downloaded mp4 file has the video, but no audio.

**Comment by jd1008** [comment]
Sorry, it is not fixed. I just downloaded the very latest
by running youtube-dl -U.
It is much worse than my first report.
mplayer CANNOT play the downloaded mp4 video from

https://www.bitchute.com/video/LYVfcTS7RVoT/

See the attached file.

**Comment by Mennaruuk** [comment]
Bitchute downloads should work as of v2021.02.04.1.
