### ISSUE TITLE
How do "--Frag" files work?

### ISSUE THREAD

**Issue by triplesixman** [ytdl-org/youtube-dl#27702]
## Checklist

- [ *] I'm asking a question
- [* ] I've looked through the README and FAQ for similar questions
- [ *] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, I have a simple question but I didn't find the answer in the readme. It concerns frag files. For some videos, I find "--Frag" files followed by a number that disappears after a few seconds.

Is it possible to know what the number corresponds to? 

Actually, I wonder if in case I download several files at the same time, there is a risk that there is a confusion with the "--Frag" files, or if the number that follows is there to avoid that.

Also, it is not possible to define a directory for these frag files even if they are only there temporarily?

Thank you

**Comment by dstftw** [comment]
This is an implementation detail, you should not bother with that. Everything will be fine until you are not trying to intentionally break it by creating files with clashing names.
