### ISSUE TITLE
Build executable file locally

### ISSUE THREAD

**Issue by fuchinoko** [ytdl-org/youtube-dl#27700]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I cloned repository, made some changes, and I want to build locally youtube-dl.exe, to test it on Windows. Is there special command for it?

**Comment by fossdd** [comment]
I guess you just have to run the Makefile. I don't know how to on windows..

**Comment by nicolaasjan** [comment]
To build it on Windows:

1. Install the most recent Python version: 
   https://www.python.org/downloads/  
   (check the option to instal `pip` as well and the option to add Python to your `$PATH`)  
   I have it installed in `C:\Program Files` and for all users (if I remember well; I'm on Linux most of the time).
  
2. In an elevated command prompt run:  
   `python -m pip install --upgrade pyinstaller`  
  
3. Download the youtube-dl source code: https://github.com/ytdl-org/youtube-dl/archive/master.zip
  
4. Extract to the folder `youtube-dl-master`.  
  
5. Open a command prompt in the folder `youtube-dl-master` and run:  
  
   `pyinstaller.exe youtube_dl\__main__.py --onefile --name youtube-dl`  

  
6. youtube-dl.exe can then be found in the newly created `dist` subdirectory.

**Comment by fuchinoko** [comment]
@nicolaasjan Thank you very much. Maybe this instruction is worth adding to README.md
