### ISSUE TITLE
I have decryption key / command to add it

### ISSUE THREAD

**Issue by d3ibis** [ytdl-org/youtube-dl#27716]
## Checklist

- [ ] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.01.03**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

1st of all, ThanQ for this awesome tool/app

As title said, I have the decryption key (for widevine) but I'm facing 2 issues:

1. if I have the mpd link and put it in command, I get (no video format)...etc, I can obtain the m3u8 link BUT its with apple fairplay, don't know if same key will work (if so, how to add it).
2. Can't locate the encrypted file (for example ismv or wvm file) in order to convert/decrypt with ffmpeg or mp4decrypt. (this is my issue i guess).

Trust me, I found a way how to obtain the decryption key for the KID (encrypted stream) and I can share in DM (the way I got it). BUT I need a way to find ismv/wvm or how to download DRM files with youtube-dl (even if encrypted).

Awaiting your reply

**Comment by dstftw** [comment]
youtube-dl does not support DRM videos.

**Comment by d3ibis** [comment]
I know that, I didn't ask to support DRMed videos, I meant that I want to download even the encrypted file. Also if there is a possibility to add the (decryption key) in command at any chances. ThanQ
