### ISSUE TITLE
How do I avoid duplicates from Soundcloud?

### ISSUE THREAD

**Issue by Feathered-Serpent** [ytdl-org/youtube-dl#27717]
## Checklist
- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question
I couldn't find this in issues or pull requests with "soundcloud duplicates".

I'm downloading https://soundcloud.com/arenanet/ as a playlist with ytdl.
Command line:
ydl.exe --embed-thumbnail --extract-audio --audio-format flac --audio-quality 0 --ignore-errors --socket-timeout 30 --skip-unavailable-fragments --hls-prefer-native --cache-dir "C:\apps\network\Youtube Downloader\cache" --yes-playlist --no-check-certificate --add-metadata --ffmpeg-location "C:\apps\video\ffmpeg\bin" --output "M:\Internet\soundcloud\%%(uploader)s/%%(playlist)s/[%%(upload_date)s] %%(title)s.%%(ext)s" https://soundcloud.com/arenanet/
(I know some options don't fit soundcloud, but I just used the same command line at first I used for videos as well)

Now upon download, there will be a subfolder created named ArenaNet (All). And there will be other subfolders created for albums, like Festivals and Holidays.

Now... the problem is, in the ArenaNet (All) there will be 271 songs, and from these 271 songs, 237 songs are downloaded twice, once into ArenaNet (All) and once into a subfolder for an album.

E.g.:
ArenaNet\ArenaNet (All)\[20181026] Buried Treasure.flac
ArenaNet\Festivals and Holidays\[20181026] Buried Treasure.flac

Both files are crc-identical. How can I prevent this? The problem is, there are still 33 files not placed into any album and therefore are placed in ArenaNet (All), so I can't just skip downloading the (All) part of it.

**Comment by dstftw** [comment]
Download archive.

**Comment by Feathered-Serpent** [comment]
So the solution is, that there is no solution and I have to download twice first, then add all duplicates to the archive file so when I update the folder again, it only downloads new duplicates.
