### ISSUE TITLE
sslv3 alert handshake failure when running under expressvpn routing (see body for routing output)

### ISSUE THREAD

**Issue by federerfanatic** [ytdl-org/youtube-dl#27720]
## Verbose log

```
youtube-dl     --output /tmp/'%(title)s_%(extractor)s_%(id)s.%(ext)s' https://www.youtube.com/watch?v=sPkkrzr8bqY --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--output', u'/tmp/%(title)s_%(extractor)s_%(id)s.%(ext)s', u'https://www.youtube.com/watch?v=sPkkrzr8bqY', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.03
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-59-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] sPkkrzr8bqY: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r1---sn-cx5o4aqj5-tt1e.googlevideo.com/videoplayback?expire=1610081842&ei=0pH3X7D_DIu2igT_34ToAw&ip=199.66.91.11&id=o-AHN5U5nORaAHzvRenonekI5wznQA0Sf9F0bBh9CQHgao&itag=299&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303&source=youtube&requiressl=yes&mh=Tb&mm=31%2C29&mn=sn-cx5o4aqj5-tt1e%2Csn-tt1eln7l&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=5150000&vprv=1&mime=video%2Fmp4&ns=Z6sY4m6XtTj5AEz_y928iA4F&gir=yes&clen=535023507&dur=1341.066&lmt=1597890776209864&mt=1610060193&fvip=6&keepalive=yes&beids=23886202&c=WEB&txp=5432432&n=TdqNGny9Qk29r9pBe&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgcRgLkDHxlN2lVzmIk-jW7pbbOwLyh7n-wM46VzjIT1ACIQCSrw6cRkIMjbIlLerqIYhUT873UCAPFrXAPGs0x5CWyw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgJBPc41MOBatdUUBC-jv48siCol4IT4JHSEGbe-s2QpkCIBfrttT5SvsjySzDzzjvyANcVpXDLtCy6x3CWfSQyY4u&ratebypass=yes'
ERROR: unable to download video data: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)>
Traceback (most recent call last):
  File "/home/nafdef/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1930, in process_info
    partial_success = dl(fname, new_info)
  File "/home/nafdef/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1875, in dl
    return fd.download(name, info)
  File "/home/nafdef/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/nafdef/bin/youtube-dl/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/home/nafdef/bin/youtube-dl/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)>


## Description
The FAILURE to DOWNLOAD occurs when we have the following routing (Ubuntu 20.04) (using expressvpn connect)

NO ERROR EXISTS when no VPN routing is active.

VPN Routing settings when error occurs is:
===================================

ip r
0.0.0.0/1 via 10.156.1.13 dev tun0 
default via 192.168.2.1 dev enp5s0 proto static metric 100 
10.0.0.0/8 via 192.168.2.1 dev enp5s0 
10.156.0.1 via 10.156.1.13 dev tun0 
10.156.1.13 dev tun0 proto kernel scope link src 10.156.1.14 
128.0.0.0/1 via 10.156.1.13 dev tun0 
169.254.0.0/16 dev enp5s0 scope link metric 1000 
172.16.0.0/12 via 192.168.2.1 dev enp5s0 
192.168.0.0/16 via 192.168.2.1 dev enp5s0 
192.168.2.0/24 dev enp5s0 proto kernel scope link src 192.168.2.55 metric 100 
199.66.91.8 via 192.168.2.1 dev enp5s0 

Routing WITHOUT expressvpn is 
default via 192.168.2.1 dev enp5s0 proto static metric 100 
169.254.0.0/16 dev enp5s0 scope link metric 1000 
192.168.2.0/24 dev enp5s0 proto kernel scope link src 192.168.2.55 metric 100 


Possible solution: Pick a route? Not sure.

**Comment by federerfanatic** [comment]
Perhaps logging in as myself would get around this?

**Comment by federerfanatic** [comment]
No, -u -p option does not work under expressvpn routing

**Comment by october262** [comment]
same issue ?? - https://github.com/ytdl-org/youtube-dl/issues/9666

**Comment by federerfanatic** [comment]
No. I did
a pip3 install youtube-dl and tried running:

youtube-dl      https://www.youtube.com/watch?v=sPkkrzr8bqY --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=sPkkrzr8bqY',
'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.03
[debug] Python version 3.8.5 (CPython) -
Linux-5.4.0-59-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, phantomjs 2.1.1,
rtmpdump 2.4
[debug] Proxy map: {}
[youtube] sPkkrzr8bqY: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on '
https://r1---sn-cx5o4aqj5-tt1e.googlevideo.com/videoplayback?expire=1610099391&ei=X9b3X_OOC4TMNsfcrLAC&ip=198.144.145.31&id=o-AKWU8owlcIp_qF4o3KnoLPb9GW6p_inFtjPiQvh-50uo&itag=299&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303&source=youtube&requiressl=yes&mh=Tb&mm=31%2C29&mn=sn-cx5o4aqj5-tt1e%2Csn-tt1e7n7l&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=215000&vprv=1&mime=video%2Fmp4&ns=GVAWpYQP_tkeLqphvnZuxukF&gir=yes&clen=535023507&dur=1341.066&lmt=1597890776209864&mt=1610077473&fvip=6&keepalive=yes&c=WEB&txp=5432432&n=4TNYAo8OzgkOs8&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMfjt9vwknUIpg5Uf83K7QZExVKeS7XcOP_gbTQlJqYiAiEA59DdcKn5XrWEnoku5VWtckA097n3Uic-WqrEVvTF96g%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgY-JN_KNEGlRc6eNYAl-4Q7tAQlVeyTKzKA60eyH0xikCIDJvK4QElDj5WKmak44p9ZIwp1wsVuXpifSuJjOW_d90&ratebypass=yes
'
[download] Resuming download at byte 14370607
ERROR: unable to download video data: <urlopen error [SSL:
SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake
failure (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
"/home/nafdef/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py",
line 1930, in process_info
    partial_success = dl(fname, new_info)
  File
"/home/nafdef/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py",
line 1875, in dl
    return fd.download(name, info)
  File
"/home/nafdef/.local/lib/python3.8/site-packages/youtube_dl/downloader/common.py",
line 366, in download
    return self.real_download(filename, info_dict)
  File
"/home/nafdef/.local/lib/python3.8/site-packages/youtube_dl/downloader/http.py",
line 351, in real_download
    establish_connection()
  File
"/home/nafdef/.local/lib/python3.8/site-packages/youtube_dl/downloader/http.py",
line 116, in establish_connection
    raise err
  File
"/home/nafdef/.local/lib/python3.8/site-packages/youtube_dl/downloader/http.py",
line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File
"/home/nafdef/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py",
line 2248, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File
"/home/nafdef/.local/lib/python3.8/site-packages/youtube_dl/utils.py", line
2734, in https_open
    return self.do_open(functools.partial(
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE]
sslv3 alert handshake failure (_ssl.c:1123)>

**Comment by jromero2k** [comment]
So, no progress on this? When the VPN is disconnected everything works, as soon as it's connected most video downloads stop working (at least all YouTube ones fail)

**Comment by federerfanatic** [comment]
I haven't tested it. Mostly I don't really use a VPN much these days.



--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)
