### ISSUE TITLE
What is wrong, i can't use avconv

### ISSUE THREAD

**Issue by jefferson018200306** [ytdl-org/youtube-dl#27722]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I tried to download a video from YouTube, instead of using ffmpeg I prefer avconv. But upon downloading this video, the ffmpeg is still working on post processing. How can I use avconv, because I'm newbie to this. Please guide me.

Here's the output summary:

~ $ youtube-dl --prefer-avconv -f bestvideo[height=480]+bestaudio https://www.youtube.com/watch?v=10wvig2oKPA
[youtube] 10wvig2oKPA: Downloading webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: /data/data/com.termux/files/home/storage/shared/Youtube/Do NOT Enter This SCARY SCHOOL in Minecraft....f135.mp4
[download] 100% of 68.80MiB in 01:12
[download] Destination: /data/data/com.termux/files/home/storage/shared/Youtube/Do NOT Enter This SCARY SCHOOL in Minecraft....f251.webm
[download] 100% of 11.97MiB in 00:13
[ffmpeg] Merging formats into "/data/data/com.termux/files/home/storage/shared/Youtube/Do NOT Enter This SCARY SCHOOL in Minecraft....mkv"
WARNING: Cannot update utime of file
Deleting original file /data/data/com.termux/files/home/storage/shared/Youtube/Do NOT Enter This SCARY SCHOOL in Minecraft....f135.mp4 (pass -k to keep)
Deleting original file /data/data/com.termux/files/home/storage/shared/Youtube/Do NOT Enter This SCARY SCHOOL in Minecraft....f251.webm (pass -k to keep)
~ $

**Comment by dstftw** [comment]
Post verbose log.

**Comment by jefferson018200306** [comment]
> Post verbose log.

How can I do that ,please

**Comment by jefferson018200306** [comment]
> Post verbose log.

Here is the verbose




~ $ youtube-dl --verbose
[debug] System config: []
[debug] User config: ['--no-mtime', '-o', '/data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1280][ext=mp4]+bestaudio[ext=m4a]']
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.9.1 (CPython) - Linux-3.10.65-gd1ee5ec-armv7l-with-libc
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

**Comment by dstftw** [comment]
No avconv is installed.

**Comment by jefferson018200306** [comment]
> No avconv is installed.

How can I install it

**Comment by rautamiekka** [comment]
> > No avconv is installed.
> 
> How can I install it

Just let it use FFmpeg you already've, there's no need/point to use avconv when you already got FFmpeg.

If you wanna install avconv you need to use whatever package management your distro uses. It's not told, so I can't help with that unless it's a Debian-type or Ubuntu-type.

**Comment by jefferson018200306** [comment]
> > > No avconv is installed.
> > 
> > 
> > How can I install it
> 
> Just let it use FFmpeg you already've, there's no need/point to use avconv when you already got FFmpeg.
> 
> If you wanna install avconv you need to use whatever package management your distro uses. It's not told, so I can't help with that unless it's a Debian-type or Ubuntu-type.

Ubuntu

**Comment by rautamiekka** [comment]
> > > > No avconv is installed.
> > > 
> > > 
> > > How can I install it
> > 
> > 
> > Just let it use FFmpeg you already've, there's no need/point to use avconv when you already got FFmpeg.
> > If you wanna install avconv you need to use whatever package management your distro uses. It's not told, so I can't help with that unless it's a Debian-type or Ubuntu-type.
> 
> Ubuntu

Ok, I verified through packages.ubuntu.com that
1) avconv had been replaced by FFmpeg in *buntu by the time of Ubuntu 16.04 LTS
2) `libav-tools`, the package which brought avconv, is now containing symlinks to FFmpeg; it's a transitional package
, which means avconv doesn't exist in Ubuntu, hasn't for a long time.

**Comment by jefferson018200306** [comment]
Ok thanks
