### ISSUE TITLE
RTE Support

### ISSUE THREAD

**Issue by HalfMadDad** [ytdl-org/youtube-dl#27733]
Hello!

It looks like RTE Ireland is supported:

https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/rte.py#L109

But I can't down load from the site:

https://www.rte.ie/player/series/siar-sna-80id%C3%AD/TG4_104164?epguid=146701

If this helps:

youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-128-generic-x86_64-with-Trisquel-9.0-etiona
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

**Comment by selfisekai** [comment]
The URL scheme seems to have changed, which is what breaks it at first.
However, it seems on my side that RTE has changed their ID scheme (the IPTV APIs don't seem to work with that), and added DRM protection to their videos on the web frontend (at least in PL, where I checked it), which likely leaves no way to download them.
![image](https://user-images.githubusercontent.com/11798442/104083150-95392e00-523c-11eb-907f-709bdb68ed20.png)

**Comment by HalfMadDad** [comment]
oh, okay, thanks selfisekai! This makes sense. TG4 is another website that RTE takes content from and they have DRM so that makes a lot of sense that RTE would adopt that too. Thanks for looking into this

**Comment by selfisekai** [comment]
actually, any content linked on https://rte.ie/player won't work. this one seems to be typically RTE content:
![image](https://user-images.githubusercontent.com/11798442/104105946-3adab480-52b2-11eb-82b0-b28dc5ba81f4.png)

as I said, the IDs are different between the web player and IPTV APIs, so the IPTV API cannot be used for that. maybe there are some others for some weird devices, just like https://player.pl still exposes some non-DRM API for Panasonic TVs, but I don't have such device to check out. it seems that there's no RTE Player Android app as well.

there's a TG4 Player app though, so I guess I'll look into that.

**Comment by Vangelis66** [comment]
... A search in the **Issue Tracker** would've revealed a lot: 

https://github.com/ytdl-org/youtube-dl/search?o=desc&q=RTE&s=updated&type=issues

i.e., as said, widevine **DRM** 💢 

... And the "workaround" no longer works...

This is another **duplicate**, please @HalfMadDad kindly close, to save precious time for the two remaining devs... 😜
