### ISSUE TITLE
Twitch Subscriber-only VODs not downloading with cookies in new version of youtube-dl

### ISSUE THREAD

**Issue by SamuraiThomas** [ytdl-org/youtube-dl#27743]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'C:\\OK\\Twitch\\test.txt', '--list-formats', 'https://www.twitch.tv/videos/861358772']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-07-30-134a48a, ffprobe git-2020-07-30-134a48a
[debug] Proxy map: {}
[twitch:vod] 861358772: Downloading stream metadata GraphQL
[twitch:vod] 861358772: Downloading video access token GraphQL
[twitch:vod] 861358772: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\YoutubeDL.py", line 2248, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

I'm trying to download a subscriber-only vod from a twitch channel than I am subscribed to. I'm using the cookies on the webpage to allow youtube-dl to extract all the information. This method worked before updating to the latest version, but no longer works and gives a HTTP error.

"ytdl" is the renamed youtube-dl exe and is what i have used for some time now and it has worked. 

this is my command below
ytdl --cookies C:\OK\Twitch\cookies.txt --list-formats TWITCH URL

**Comment by dstftw** [comment]
You must provide account credentials for any work on this.

**Comment by SamuraiThomas** [comment]
> 
> 
> You must provide account credentials for any work on this.

do you mean like this? i tried logging in with username and password but didn't work which is why i use cookie method.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--username', 'PRIVATE', '--list-formats', 'https://www.twitch.tv/videos/861358772']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-07-30-134a48a, ffprobe git-2020-07-30-134a48a
[debug] Proxy map: {}
[twitch:vod] Downloading login page
[twitch:vod] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpe72mu9fe\build\youtube_dl\YoutubeDL.py", line 2248, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by dstftw** [comment]
I mean to the developer.

**Comment by TennisMexican** [comment]
I'm having this same issue. It was working fine with my 2020.9.20 version earlier today but then suddenly stopped so I updated to the latest and it's giving me the same 403 error. I've tried using cookies and sending in my username/password/2FA but nothing works.

**Comment by andrew1-1** [comment]
> I mean to the developer.

Hi, I saw you labeled my post as duplicate. Do you mean we should send our Twitch credentials to yt-dl developer in order for them to be able to fix the issue?

**Comment by david-wm-sanders** [comment]
works fine for me on youtube-dl 2021.01.16 using my current cookies via [twitchget.py](https://github.com/david-wm-sanders/twitchget/blob/master/twitchget.py)

**Comment by TennisMexican** [comment]
Same, once I got the latest version and an updated cookies.txt file, it worked for me
