### ISSUE TITLE
no download from telecinco.es altough video is not georestricted

### ISSUE THREAD

**Issue by contemascetti80** [ytdl-org/youtube-dl#27748]
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2020.05.08**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose Log```
youtube-dl -v https://www.telecinco.es/volverteaver/ana-mena-sorpresa-amiga_18_3072045112.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.telecinco.es/volverteaver/ana-mena-sorpresa-amiga_18_3072045112.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-05-04-5767a2e, ffprobe git-2020-05-04-5767a2e
[debug] Proxy map: {}
[Telecinco] ana-mena-sorpresa-amiga_18_3072045112: Downloading webpage
[Telecinco] a2444ae2-093a-41cd-977f-917cd2798fd9: Downloading config JSON
[Telecinco] a2444ae2-093a-41cd-977f-917cd2798fd9: Downloading flash mmc JSON
WARNING: Unable to download JSON metadata: <urlopen error [Errno 11001] getaddrinfo failed>
[Telecinco] a2444ae2-093a-41cd-977f-917cd2798fd9: Downloading html5 mmc JSON
WARNING: Unable to download JSON metadata: <urlopen error [Errno 11001] getaddrinfo failed>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\telecinco.py", line 180, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\telecinco.py", line 145, in _parse_content
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Video is easily streamed in HD quality but not downloaded. I tried many times to update to latest version from yt-dl.org but only able to get the May 2020 as latest version for windows (https://github.com/ytdl-org/youtube-dl/releases/download/2021.01.08/youtube-dl.exe)
I also tried the .m3u8 direct link (https://vod.telecinco.es/hls/vod/a2444ae2-093a-41cd-977f-917cd2798fd9/a2444ae2-093a-41cd-977f-917cd2798fd9.,270,490,885,1595,2915,.mp4.csmil/index-f1-v1-a1.m3u8) but I get "Acces Denied" on browser and no downolad either from youtube-dl.
Thank you for your help

**Comment by remitamine** [comment]
works with the latest version.

**Comment by contemascetti80** [comment]
How do I get that? https://github.com/ytdl-org/youtube-dl/releases/download/2021.01.08/youtube-dl.exe always gets me the 2020 one
