### ISSUE TITLE
Add Dish to MSO List

### ISSUE THREAD

**Issue by hansgerig** [ytdl-org/youtube-dl#27753]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

What is currently the status and roadmap of adding Dish to the supported MSOs? I realise this is a duplicate of issue #11886 but it doesn't seem to be leading anywhere. I tried adding the suggested code in that issue and recompiling youtube-dl from source but it still doesn't recognise Dish as a supported MSO. Are there plans to add it to the main branch? If so, is there an estimated time frame? If not, how can I implement the proposed code? I'm not knowledgeable enough to get it to work.

**Comment by dstftw** [comment]
No status. Nobody even bothered to provide credentials.

**Comment by hansgerig** [comment]
If I knew how to help I would.
