### ISSUE TITLE
Can we add a new feature to download videos from https://gtv.org  There are a lot of good videos on https://gtv.org  thanks!

### ISSUE THREAD

**Issue by gtalentcommunity** [ytdl-org/youtube-dl#27756]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.01.08**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
https://gtv.org is a new social media video hosting service provider. There are tons of valuable videos. 
Can we add a new feature to download videos from https://gtv.org  There are a lot of good videos on https://gtv.org  thanks!

**Comment by gtalentcommunity** [comment]
Hi remitamine,

Can you tell me why this is imcomplete? Which part I need to put more content? Thanks. 

https://github.com/ytdl-org/youtube-dl/issues/27756

**Comment by remitamine** [comment]
you have selected the wrong issue template, this is a site support request, you should fill the proper template.

**Comment by gtalentcommunity** [comment]
Thanks remitamine,

Can you please tell me which template I should use? link? Thanks!

**Comment by remitamine** [comment]
`Site support request`
