### ISSUE TITLE
Please add login support on cbs.com

### ISSUE THREAD

**Issue by CHJ85** [ytdl-org/youtube-dl#27765]
Hi there. This is not so much a site request but rather an improvement as the site itself is already supported. I just clicked the wrong one by mistake. Sorry.
Anyway. A lot of videos on cbs.com are available only for CBS All Access users and therefor locked behind username and password.
So if you could add the ability to login, that'd be great.
Thanks in advance!

**Comment by october262** [comment]
youtube-dl already supports the  username & password option.

**Comment by remitamine** [comment]
post a non DRM protected video URL that doesn't work with the current version.

**Comment by CHJ85** [comment]
@october262 For CBS.com?
See, I already tried logging in but still got an error:
`ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by CHJ85** [comment]
@remitamine How come you marked it incomplete?
Do you mean the feature is incomplete, as in hasn't been added yet?
Either way, it would be nice if I could download videos from cbs.com that require login.

**Comment by remitamine** [comment]
> post a non DRM protected video URL that doesn't work with the current version.

**Comment by CHJ85** [comment]
https://www.cbs.com/shows/inspector-gadget/video/Ny7N7WDV9F1XKmZM5GOELQorKd5lsicF/inspector-gadget-monster-lake/

**Comment by CHJ85** [comment]
The rest of the episodes are not behind the paywall and therefor download just fine.

**Comment by remitamine** [comment]
DRM protected.

**Comment by CHJ85** [comment]
Ah I see. So the other videos for some reason do not.
Very interesting.
So you're saying that username and password will work so long as the videos have a drm-free format?

**Comment by remitamine** [comment]
>  So you're saying that username and password will work so long as the videos have a drm-free format?

not exactly, youtube-dl will try the best to download videos and would fail mostly for DRM protected videos.

**Comment by CHJ85** [comment]
@remitamine So technically you could look into this DRM in order to try and get around it?
Because if you could do that, that'd be fantastic.
In fact. I'd donate money for that to happen.

**Comment by CHJ85** [comment]
@remitamine  So... Have you looked into the DRM?
The file that youtube-dl is trying to decode is https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2019/10/23/1629244995997/147738_cenc_dash/stream.mpd

**Comment by remitamine** [comment]
no, i'm not going to check, youtube-dl does not support DRM protected videos.

**Comment by CHJ85** [comment]
It does though.
All the other videos are DRM protected, and youtube-dl is able to handle them just fine.
But whatever.
Do you know of any software that do?
