### ISSUE TITLE
Youtube tracklist 

### ISSUE THREAD

**Issue by Stefunga** [ytdl-org/youtube-dl#27766]
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running youtube-dl version **2021.01.08**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Looking to add functionality for track and artist info for videos with multiple songs in 1 video, currently it is my understanding this functionality only works when there is one song in a video. 
![image](https://user-images.githubusercontent.com/40221419/104135123-f7d51b80-535b-11eb-9f91-54d716d42a12.png)

**Comment by remitamine** [comment]
youtube does not provide the time range when the song is used, so it can't be used as chapters.
and for adding metadata to file, this not going to help, you can only specify single artist the whole media file.
in what way this information will be used?
you should provide enough info on what is expected.

**Comment by Stefunga** [comment]
No problem understood, currently for the `extract_info` call it has the possibility to return the following information (this is from the ReadMe). 
   ```
    track (string): Title of the track
    track_number (numeric): Number of the track within an album or a disc
    track_id (string): Id of the track
    artist (string): Artist(s) of the track
    genre (string): Genre(s) of the track
    album (string): Title of the album the track belongs to
    album_type (string): Type of the album
    album_artist (string): List of all artists appeared on the album
    disc_number (numeric): Number of the disc or other physical medium the track belongs to
    release_year (numeric): Year (YYYY) when the album was released
```
Some YouTube videos have multiple songs associated with them like in the image I provided earlier, which doesn't work with the standard `extract_info` call. I dug into the code a bit and found the info does exist in the `video_webpage` value, but still requires some RegEx to pull it out (`re.findall(r'{"simpleText":.*?}', video_webpage)` can be used to see some of these examples but still working on making it more specific to not catch false positives) and then adding that info to the dictionary and returning to the caller. 

Overall goal of this is to be able to be able to see which songs Youtube has identified are in the video (which is not currently supported through the YouTube API) -> another example of this in Youtube **https://www.youtube.com/watch?v=mNASC3txZHw&t=2119s**

**Comment by remitamine** [comment]
> No problem understood, currently for the extract_info call it has the possibility to return the following information (this is from the ReadMe).
 track (string): Title of the track
 track_number (numeric): Number of the track within an album or a disc
 track_id (string): Id of the track
 artist (string): Artist(s) of the track
 genre (string): Genre(s) of the track
 album (string): Title of the album the track belongs to
 album_type (string): Type of the album
 album_artist (string): List of all artists appeared on the album
 disc_number (numeric): Number of the disc or other physical medium the track belongs to
 release_year (numeric): Year (YYYY) when the album was released

this would work only for single songs(the information is unambiguous, it apply to the full media file), how would you make it work with multiple songs in a single video without having time ranges?
without having unambiguous way to assign the information, i don't see this as something to included in youtube-dl.
