### ISSUE TITLE
CI failing in fork

### ISSUE THREAD

**Issue by pukkandan** [ytdl-org/youtube-dl#27764]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have a [fork of youtube-dl](https://github.com/pukkandan/youtube-dl-1) intended for creating PRs here. The master branch is currently in sync with this repo. When I try to run [CI github action](https://github.com/pukkandan/youtube-dl-1/runs/1677335486?check_suite_focus=true) in that fork, the run fails for python 3.3 and 3.4 with the error `Error: Version 3.3 with arch x64 not found`. 

Considering the same tests run here, I assume I have to do something additional to get it to run properly. But I have no idea what it is. Does anyone know how to get the tests working in the fork?

**Comment by Vangelis66** [comment]
> Considering the same tests run here, I assume I have to do something additional to get it to run properly. 
> But I have no idea what it is. Does anyone know how to get the tests working in the fork?

I have 0 knowledge on this, but from a quick comparison between 
https://github.com/pukkandan/youtube-dl-1/runs/1677335486?check_suite_focus=true

![p33-0](https://user-images.githubusercontent.com/9669492/104131302-354aa080-537e-11eb-8e78-03bd6099f03a.JPG)

and 

https://github.com/ytdl-org/youtube-dl/runs/1674982378?check_suite_focus=true

![p33-1](https://user-images.githubusercontent.com/9669492/104131354-82c70d80-537e-11eb-8614-be64a5cedfe6.JPG)

... I can see that the workflow **here** has been  instructed to download (and then properly set up) the **py3.3** version (and, likewise, other failing py versions) that's missing in your own fork... _Why_ it's not doing the same in your own set up, well, someone else will have to chime in... 😉

**Comment by remitamine** [comment]
the test works fine in my fork(https://github.com/remitamine/youtube-dl-1/runs/1677473513), so i don't think there is anything to be done here.

**Comment by dstftw** [comment]
This may be some A/B test on [switching `ubuntu-latest` to `ubuntu-20.04`](https://github.blog/changelog/2020-10-29-github-actions-ubuntu-latest-workflows-will-use-ubuntu-20-04/), note that there is no `3.3.*` and `3.4.*` builds for `linux-20.04` [available](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json).

**Comment by pukkandan** [comment]
@dstftw Seems you were right. Changing it to `ubuntu-18.04` fixed the issue. Should the same change be made here so that it can work consistently across forks?

**Comment by dstftw** [comment]
It's already [done](d0fc289f45763ab556936c2ce3d76fc1c3dd7c69).
