### ISSUE TITLE
start downloading from the nth video of the first playlist in a batch file and then completely download rest of the playlists

### ISSUE THREAD

**Issue by blueray453** [ytdl-org/youtube-dl#27774]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Suppose I have 10 playlist in a batch file. I want to start downloading from the 16th video of the first playlist and then completely download rest of the playlists. 

If I use `--playlist-start 16` then all video in the playlist start from 16th. But I only want the first playlist to start from 16th and then completely download rest of the videos. I can just use `youtube-dl`, but in that case it will iterate through the first 15 videos fast, causing me to be blocked which I do not want.

What can I do?

**Comment by dstftw** [comment]
Download first playlist in one run with `--playlist-start` provided and download the rest of playlists in another run.
