### ISSUE TITLE
youtube-dl doesn't run in Ubuntu 20.04.1-LTS

### ISSUE THREAD

**Issue by Scooby-2** [ytdl-org/youtube-dl#27778]
I download with
`sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl`
Then I run
`sudo youtube-dl -U`
Says:
/usr/bin/env: «python»: No existe el archivo o el directorio (Directory or file does not exist) 
`which youtube-dl`
/usr/local/bin/youtube-dl
`python -V`
Python 3.8.5
`bash --version`
GNU bash, versión 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
Licencia GPLv3+: GPL de GNU versión 3 o posterior <http://gnu.org/licenses/gpl.html>

Esto es software libre, es libre para modificar y redistribuirlo.
No hay NINGUNA GARANTÍA, a la extensión permitida por la ley.
`uname -a`
Linux Aspire-A315-53 5.8.0-36-generic #40~20.04.1-Ubuntu SMP Wed Jan 6 10:15:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dstftw** [comment]
You must make `python` alias available on your system.

**Comment by rautamiekka** [comment]
What's the response to
```bash
which python python3 python3.8
```
?

**Comment by Scooby-2** [comment]
which python python3 python3.8
/usr/bin/python3
/usr/bin/python3.8

**Comment by rautamiekka** [comment]
Presumably your Python 3.8 is a stock installation with the DE itself, and since `python` doesn't show up you should just be able to fix the problem by installing `python-is-python3`:
```bash
sudo apt install python-is-python3
```

**Comment by Scooby-2** [comment]
Thank you so much Jouni, running that command solved the problem.

Kind regards

Scooby

**Comment by rautamiekka** [comment]
Great :D
