### ISSUE TITLE
Viki Login 

### ISSUE THREAD

**Issue by Angu0083** [ytdl-org/youtube-dl#27782]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.01.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

   I've getting the error while using the -u parameter for viki premium and debug code was below,

  Fix the bug as soon.

**root@wanlab:~/demo# youtube-dl -F  https://www.viki.com/videos/1026409v-my-love-from-the-star-episode-1 -v**
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'https://www.viki.com/videos/1026409v-my-love-from-the-star-episode-1', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-13-amd64-x86_64-with-debian-10.7
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[viki] 1026409v: Downloading video JSON
[viki] 1026409v: Downloading MPD manifest
WARNING: [viki] Unknown MIME type image/jpeg in DASH manifest
[info] Available formats for 1026409v:
format code  extension  resolution note
mpd-http-6   m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.2 (48000Hz)
mpd-http-7   m4a        audio only DASH audio   65k , m4a_dash container, mp4a.40.2 (48000Hz)
mpd-http-5   m4a        audio only DASH audio   81k , m4a_dash container, mp4a.40.2 (48000Hz)
mpd-http-8   m4a        audio only DASH audio  193k , m4a_dash container, mp4a.40.2 (48000Hz)
mpd-http-9   m4a        audio only DASH audio  193k , m4a_dash container, mp4a.40.2 (48000Hz)
mpd-http-1   mp4        426x238    DASH video  203k , mp4_dash container, avc1.640015, 24fps, video only
mpd-http-2   mp4        640x360    DASH video  405k , mp4_dash container, avc1.64001E, 24fps, video only
mpd-http-3   mp4        852x480    DASH video  628k , mp4_dash container, avc1.64001E, 24fps, video only (best)

**root@wanlab:~/demo# youtube-dl -F  https://www.viki.com/videos/1026409v-my-love-from-the-star-episode-1 -u** angu0083@hotmail.com -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'https://www.viki.com/videos/1026409v-my-love-from-the-star-episode-1', u'-u', u'PRIVATE', u'-v']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.08
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-13-amd64-x86_64-with-debian-10.7
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[viki] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2248, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by zackmark29** [comment]
x-viki-app-ver : 6.0.0
x-client-user-agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
