### ISSUE TITLE
Commandline Option to include YT Thumbnail in downloaded mp3.

### ISSUE THREAD

**Issue by WarpWing** [ytdl-org/youtube-dl#27806]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Hello all! So I've recently made a simple bash script to download YT videos using youtube-dl. Before that , I used a site called "loader.to to do it. I've just noticed that Loader.to has some sort of way to include the youtube thumbnail into the mp3 file. 
![img](https://cdn.discordapp.com/attachments/734545389340065837/798964863975161876/Screen_Shot_2021-01-13_at_12.19.27_PM.png)
Is there some sort of command-line option that can also that can do the same for YT-DL?
My current commandline options are 
```bash
--geo-bypass --add-metadata -f 37/22/18/best -x --audio-format "mp3" -o %(title)s.%(ext)s
```

**Comment by dstftw** [comment]
```
--embed-thumbnail                Embed thumbnail in the audio as cover art
```
Read FAQ.
