### ISSUE TITLE
[TwitCasting] Unable to extract movie playlist error(RegexNotFoundError)

### ISSUE THREAD

**Issue by Spicadox** [ytdl-org/youtube-dl#27823]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.01.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
I:\>youtube-dl -v https://twitcasting.tv/natsuiromatsuri/movie/661406762
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://twitcasting.tv/natsuiromatsuri/movie/661406762']
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, pref cp65001
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.9.1 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-essentials_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[TwitCasting] 661406762: Downloading webpage
ERROR: Unable to extract movie playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\samph\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\samph\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\samph\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\samph\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\twitcasting.py", line 79, in _real_extract
    video_js_data = self._parse_json(self._search_regex(
  File "c:\users\samph\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract movie playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I was just downloading videos on Twitcasting and it was working fine yesterday until it stopped working today. I'm getting the unable to extract movie playlist error. Their weekly site maintenance ended 1/12/2021 per their post on Twitter. I've tried using a vpn and connecting to different countries and still had no luck.

**Comment by october262** [comment]
play the video and press F12 on your keyboard to bring up the debug menu,
go to network - all - type index in the search box  - index.m3u8 will show, just copy the URL
and paste it into youtube-dl to download the video.

**Comment by Spicadox** [comment]
Twitcasting livestream videos are in segments of .m4s so I need to grab all of it and so there are no .m3u8 resources where I can copy the URL.

**Comment by itsnoteasy** [comment]
I have the same issue, no .m3u8 resources. i have never used twitcasting before today though.

**Comment by Spicadox** [comment]
Ah I found the index.m3u8 resource and this reddit thread on r/youtubedl provided some insight on this problem https://www.reddit.com/r/youtubedl/comments/l0oxgv/twitcasting_problems/
