### ISSUE TITLE
Please add Rumble support

### ISSUE THREAD

**Issue by holygamer** [ytdl-org/youtube-dl#27828]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.01.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

## Description

WRITE DESCRIPTION HERE

Video example: https://rumble.com/vct27p-video-they-dont-want-you-to-see-leftists-destroy-dc-after-2017-inauguration.html

**Comment by october262** [comment]
for this link -  https://rumble.com/vct27p-video-they-dont-want-you-to-see-leftists-destroy-dc-after-2017-inauguration.html play the video and press F12 on your keyboard to bring up the debug menu, select network - type mp4 in the search box, copy the first 1Xdsb.caa mp4 file
and pate into youtube-dl to download the video
