### ISSUE TITLE
ERROR: This video is DRM protected

### ISSUE THREAD

**Issue by Melonadev** [ytdl-org/youtube-dl#27837]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
Microsoft Windows [Version 10.0.19041.746]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\yewhe\OneDrive\Desktop\bin>youtube-dl -v https://www.youtube.com/watch?v=WGTlO_GO29I
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=WGTlO_GO29I']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-04-22-2e38c63, ffprobe git-2020-04-22-2e38c63
[debug] Proxy map: {}
[youtube] WGTlO_GO29I: Downloading webpage
[youtube] WGTlO_GO29I: Downloading embed webpage
[youtube] WGTlO_GO29I: Refetching age-gated info webpage
[youtube] WGTlO_GO29I: Downloading MPD manifest
ERROR: This video is DRM protected.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 805, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 826, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\youtube.py", line 2427, in _real_extract
youtube_dl.utils.ExtractorError: This video is DRM protected.

```

## Description

As far as I know, [YouTube Movies](https://www.youtube.com/channel/UClgRkhTL3_hImCAmdLfDE4g) is an official channel allowing films to be watched with payment or free with ads. This service was previously only available in the U.S., but since yesterday, the free-to-watch-with-ads films are available to watch outside of U.S. as well.

I was trying to download one of such films with youtube-dl (in this case the 1980 film '[Raging Bull](https://www.youtube.com/watch?v=WGTlO_GO29I)'), but the results say that the video's DRM-protected.

**Comment by FlaminHat** [comment]
If the video is in fact encrypted, why doesn't it download any of it? I would see for myself if it was encrypted if I could download it
