### ISSUE TITLE
Installing yt-dl on a Website

### ISSUE THREAD

**Issue by Freaky2002** [ytdl-org/youtube-dl#27843]
## Checklist

- [x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Hey,
Is there a way to install yt-dl on a Website, to access it through a Domain?
is there mabye already some kind of Gui you can use?

I have searched but couldnr found what I‘m looking for.
The plan is to have some kind of „own“ YouTube downloader tool online.

thanks for any help!

**Comment by dstftw** [comment]
youtube-dl is an application not a web frontend.
