### ISSUE TITLE
[ADN] Can't download premium video after extractor fix

### ISSUE THREAD

**Issue by Gaby13627** [ytdl-org/youtube-dl#27841]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

First of all I would like to thank the person who fixed the ADN extractor.

Everything works perfectly to download the free videos in 480p. But to download videos requiring a premium account or to download better quality I can't do it.

Before I used to use the command :

`youtube-dl.exe --cookies ./cookies.txt https://animedigitalnetwork.fr/video/my-hero-academia-saison-4/10271-episode-2-overhaul`

And it worked perfectly but after the extractor fix it doesn't work anymore I tried to re-download the cookies as indicated in the doc but it doesn't change anything I also tried to use `--username` and `--password` but it doesn't do anything either and it shows me in the both case:

`ERROR: This video is only available for paying users`

I think the problem comes from the cookies that don't have the same shape as before, there were 4 lines in my file but now there is only one.

Could someone help me?

Thank you.

**Comment by adrianheine** [comment]
Thanks for your bug report and sorry for the bug :) Just to clarify: Did this work until my recent changes, or did it stop working a few months ago when ADN changed the site?

**Comment by Gaby13627** [comment]
HI,
Thank you for your answer.
I think it stop working when ADN changed the site, but I'm not sure since I haven't been able to really try it since then.

As I said in my previous message I think that ADN has changed the cookie structure at the same time as the site, which I think is causing this problem.

Attached are two screenshot showing the old cookie file and the new one both extracted from the site.
![OLD](https://user-images.githubusercontent.com/31627232/105607637-27dede80-5da0-11eb-8c3d-c8416dcc2711.png)
![New](https://user-images.githubusercontent.com/31627232/105607636-27464800-5da0-11eb-8835-46630afc233c.png)

For the logins I can send them to you by email.

**Comment by toniohc** [comment]
Try your commit. Work like a charm 👍

**Comment by Azzuray** [comment]
As i mention on the request side, Download works flawless but subs doesnt decrypt on "paid vids", only on free ones 😢

**Comment by toniohc** [comment]
No pbl with paid one. I just try it today with this commit ( must modify
adn.py and compile it with the modification of this commit ).
