### ISSUE TITLE
Youtube-dl has 3200 open issues and is too big and popular for the current size of the team.

### ISSUE THREAD

**Issue by ibex-are-goats** [ytdl-org/youtube-dl#27855]
Youtube-dl need to recruit new leaders to the project to split the work. You will burn out trying to maintain a project of this size and popularity. You will literally never close those 3200 issues without help.

Recruit new leaders to the project and trust them to do a good enough job.

**Comment by flleeppyy** [comment]
I second this

Its like trying to maintain every position at a fast food restaurant.
Bad comparison, but you know what I mean.
