### ISSUE TITLE
[Pornhub Premium] - Not verfied pornstar page not working

### ISSUE THREAD

**Issue by draconis10** [ytdl-org/youtube-dl#27853]
Non verified pornstars pages for premium videos don't not have a '/videos' page, instead they have '?premium=1&o=mr' page. For example https://www.pornhubpremium.com/pornstar/sienna-west?premium=1&o=mr

If you try to replace the link with https://www.pornhubpremium.com/pornstar/sienna-west/videos you get an 'Error Page Not Found' message.

Taking this into account, if you try and run the follow it won't download any premium videos (cookies.txt holds the Premium login details):

C:\Users\Example>youtube-dl --cookies cookies.txt --download-archive Test.txt --no-post-overwrites -o "Z:\Videos\Sienna West\%%(title)s.%%(ext)s" -f bestvideo[ext=mp4]+bestaudio/best[ext=mp4]/best --merge-output-format mp4 -ciw https://www.pornhubpremium.com/pornstar/sienna-west

[PornHubPagedVideoList] pornstar/sienna-west/videos: Downloading page 1
[download] Downloading playlist: pornstar/sienna-west/videos
[PornHubPagedVideoList] playlist pornstar/sienna-west/videos: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: pornstar/sienna-west/videos

Even adding --yes-playlist to the command won't work.

Any ideas if or when there will be a fix for this?

**Comment by dstftw** [comment]
You must provide premium account for any work on this.

**Comment by draconis10** [comment]
> 
> 
> You must provide premium account for any work on this.

As discussed I've sent you the login details via Email, let me know how it goes!

**Comment by draconis10** [comment]
Updated to the latest youtube-dl, just tried but still getting the same error..

C:\!Scripts>youtube-dl --cookies cookies.txt --download-archive !PornhubDownloaded.txt --no-post-overwrites --yes-playlist -o "Z:\Videos\Sienna West%(title)s.%(ext)s" -f bestvideo[ext=mp4]+bestaudio/best[ext=mp4]/best --merge-output-format mp4 -ciw https://www.pornhubpremium.com/pornstar/sienna-west
[PornHubPagedVideoList] pornstar/sienna-west/videos: Downloading page 1
[download] Downloading playlist: pornstar/sienna-west/videos
[PornHubPagedVideoList] playlist pornstar/sienna-west/videos: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: pornstar/sienna-west/videos
