### ISSUE TITLE
ExtractorError: no video format found; for a video of the site 6Play.fr 

### ISSUE THREAD

**Issue by dash-77** [ytdl-org/youtube-dl#27868]
## Checklist

- [x ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log
 youtube-dl -v https://www.6play.fr/la-princesse-des-fleurs-p_19019/la-princesse-des-fleurs-c_12824525
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.6play.fr/la-princesse-des-fleurs-p_19019/la-princesse-des-fleurs-c_12824525']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-132-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[6play] 12824525: Downloading JSON metadata
[6play] 12824525: Downloading webpage
[6play] 12824525: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12824525: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[6play] 12824525: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12824525: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[6play] 12824525: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[6play] 12824525: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 826, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/sixplay.py", line 113, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description
I have a message:
ExtractorError: No video formats found;

but if i use an other address: 
 youtube-dl -F https://www.6play.fr/un-hiver-de-princesse-p_12513/romance-c_12248171
[6play] 12248171: Downloading JSON metadata
[6play] 12248171: Downloading webpage
[6play] 12248171: Downloading m3u8 information
[6play] 12248171: Downloading MPD manifest
[info] Available formats for 12248171:
format code             extension  resolution note
dash-audio1=93468       m4a        audio only [fr] DASH audio   93k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-video_eng=301000   mp4        400x226    [en] DASH video  301k , mp4_dash container, avc1.42001E, 25fps, video only
dash-video_eng=800000   mp4        640x360    [en] DASH video  800k , mp4_dash container, avc1.42001E, 25fps, video only
dash-video_eng=1500000  mp4        720x406    [en] DASH video 1500k , mp4_dash container, avc1.42001E, 25fps, video only
hls-419                 mp4        400x226     419k , avc1.42001E@ 301k, 25.0fps, mp4a.40.2@ 93k
hls-948                 mp4        640x360     948k , avc1.42001E@ 800k, 25.0fps, mp4a.40.2@ 93k
hls-1690                mp4        720x406    1690k , avc1.42001E@1500k, 25.0fps, mp4a.40.2@ 93k (best)

it's work fine.
Please help me

**Comment by dirkf** [comment]
See #24967.
