### ISSUE TITLE
[Twitch] downloading a live Twitch stream - fails to get the source format stream

### ISSUE THREAD

**Issue by CairnsByTheSea** [ytdl-org/youtube-dl#27873]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

(using version 2021.01.16)
Downloading a live Twitch stream less than 30 seconds from the start I would like to get the best video, however, I'm getting inconsistent results. Sometimes at source (1920x1080) else getting 1280x720.

I'm expecting that it would default to "source"

Has anyone seen this before?

**Comment by CairnsByTheSea** [comment]
Hey @remitamine,
I don't understand why you labelled this as incomplete?

**Comment by remitamine** [comment]
provide examples.

**Comment by CairnsByTheSea** [comment]
The problem is that this seems to be a random occurrence. I use some code to start the recording when the twitch streamer goes live so I'm not there to observe.

I think that the question "Has anyone seen this before?" is still valid.

**Comment by TaoziDB** [comment]
source quality means the original resolution twitch streamer choose to stream on, some times higher than 1080p, some times lower than 1080p, some times is 1080p, so 720p for source quality is perfect normal result

**Comment by CairnsByTheSea** [comment]
OK, I understand that. However, I have watched a stream where it was originally streamed at 1080p, yet recorded at 720p.

I'm wondering if what I'm seeing is somehow connected to the use of the cookies option. Could the youtube-dl recording be getting the quality initialised from what I had set manually from my last browser-watched stream instead of defaulting to source quality?
