### ISSUE TITLE
Support for dramacool.be

### ISSUE THREAD

**Issue by jefferson018200306** [ytdl-org/youtube-dl#27870]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://dramacool.be/watch/true-beauty-episode-10/
- Single video: https://dramacool.be/watch/true-beauty-2020-episode-11/

## Description

Please add support for dramacool.be as it is also a good site for watching our favorite kdrama. Not as good as on viu:Ott extractor error, but this site will also turn out to be a good alternative on viu.... It also supports selecting server to stream so I think it is much easier for youtube-dl developers to extract the video on that server. I'm a huge fan of kdrama so please do everything you can. Thank you 💞

**Comment by october262** [comment]
for this link - https://dramacool.be/watch/true-beauty-episode-10/
just press F12 on your keyboard to bring up the debug menu, go to network,
type m3u8 in the search box, play the video, copy the m3u8 link and feed it into youtube-dl to download the episode.

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free

**Comment by jefferson018200306** [comment]
> for this link - https://dramacool.be/watch/true-beauty-episode-10/
> just press F12 on your keyboard to bring up the debug menu, go to network,
> type m3u8 in the search box, play the video, copy the m3u8 link and feed it into youtube-dl to download the episode.

Thank you! It works
