### ISSUE TITLE
Odysee / Lbry Download Problem : Unable to download video data: HTTP Error 308: Permanent Redirect

### ISSUE THREAD

**Issue by bubul01** [ytdl-org/youtube-dl#27877]
## Checklist

- [x ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

Output is for this url:
https://odysee.com/@SilvanoTrotta:f

 [debug] System config: []
 [debug] User config: []
 [debug] Custom config: []
 [debug] Command-line args: ['https://odysee.com/@SilvanoTrotta:f', '--ffmpeg-location', 'ffmpeg/bin/', '--playlist-start', '1', '--verbose', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,fr', '-r', '1M', '--write-thumbnail', '--yes-playlist', '--max-downloads', '10', '--write-description', '-o', 'F:/Videos/Youtube/Silvanno Trotta/Odysee/%(title)s.%(ext)s', '--min-sleep-interval', '240', '--max-sleep-interval', '360']
 [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
 [debug] youtube-dl version 2021.01.16
 [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
 [debug] exe versions: ffmpeg git-2020-03-15-c467328, ffprobe git-2020-03-15-c467328
 [debug] Proxy map: {}
 [lbry:channel] @SilvanoTrotta#f: Downloading channel JSON metadata
 [download] Downloading playlist: Silvano TROTTA
 [lbry:channel] f16e438efc5600c85b13a666ea63bd9a8dde4695: Downloading page 1 JSON metadata
 [lbry:channel] playlist Silvano TROTTA: Downloading 49 videos
 [download] Downloading video 1 of 49
 [lbry] Annonce#89393ac8e32a3d5e3c633fd2ebc7838fca663401: Downloading stream JSON metadata
 [lbry] 89393ac8e32a3d5e3c633fd2ebc7838fca663401: Downloading streaming url JSON metadata
 [debug] Default format spec: bestvideo+bestaudio/best
 [info] Writing video description to: F:\Videos\Youtube\Silvanno Trotta\Odysee\Annonce.description
 [lbry] 89393ac8e32a3d5e3c633fd2ebc7838fca663401: Downloading thumbnail ...
 [lbry] 89393ac8e32a3d5e3c633fd2ebc7838fca663401: Writing thumbnail to: F:\Videos\Youtube\Silvanno Trotta\Odysee\Annonce.png
 [debug] Invoking downloader on 'https://cdn.lbryplayer.xyz/api/v4/streams/free/Annonce/89393ac8e32a3d5e3c633fd2ebc7838fca663401/9fff7c'
 [download] F:\Videos\Youtube\Silvanno Trotta\Odysee\Annonce.mp4 has already been downloaded
 [download] 100% of 5.89MiB
 [download] Downloading video 2 of 49
 [lbry] Dictature-Sanitaire-#cf945e895e1845cfa601dde5f4124314d4cfd007: Downloading stream JSON metadata
 [lbry] cf945e895e1845cfa601dde5f4124314d4cfd007: Downloading streaming url JSON metadata
 [debug] Default format spec: bestvideo+bestaudio/best
 [info] Writing video description to: F:\Videos\Youtube\Silvanno Trotta\Odysee\Dictature Sanitaire .description
 [lbry] cf945e895e1845cfa601dde5f4124314d4cfd007: Downloading thumbnail ...
 [lbry] cf945e895e1845cfa601dde5f4124314d4cfd007: Writing thumbnail to: F:\Videos\Youtube\Silvanno Trotta\Odysee\Dictature Sanitaire .png
 [debug] Invoking downloader on 'https://cdn.lbryplayer.xyz/api/v4/streams/free/Dictature-Sanitaire-/cf945e895e1845cfa601dde5f4124314d4cfd007/8bbe8d'
 [download] F:\Videos\Youtube\Silvanno Trotta\Odysee\Dictature Sanitaire .mp4 has already been downloaded
 [download] 100% of 360.20MiB
 [download] Downloading video 3 of 49
 [lbry] Marseille-punit-!#fc9502e425d4dfa46c9180a27b09c94e6d2cae9c: Downloading stream JSON metadata
 [lbry] fc9502e425d4dfa46c9180a27b09c94e6d2cae9c: Downloading streaming url JSON metadata
 [debug] Default format spec: bestvideo+bestaudio/best
 [info] Writing video description to: F:\Videos\Youtube\Silvanno Trotta\Odysee\Marseille punit ! .description
 [lbry] fc9502e425d4dfa46c9180a27b09c94e6d2cae9c: Downloading thumbnail ...
 [lbry] fc9502e425d4dfa46c9180a27b09c94e6d2cae9c: Writing thumbnail to: F:\Videos\Youtube\Silvanno Trotta\Odysee\Marseille punit ! .png
 [debug] Invoking downloader on 'https://cdn.lbryplayer.xyz/api/v4/streams/free/Marseille-punit-!/fc9502e425d4dfa46c9180a27b09c94e6d2cae9c/242a38'
 [download] F:\Videos\Youtube\Silvanno Trotta\Odysee\Marseille punit ! .mp4 has already been downloaded
 [download] 100% of 349.31MiB
 [download] Downloading video 4 of 49
 [lbry] Confinement#760630f28598599bc0e3ac90aaea0154a5787a76: Downloading stream JSON metadata
 [lbry] 760630f28598599bc0e3ac90aaea0154a5787a76: Downloading streaming url JSON metadata
 [debug] Default format spec: bestvideo+bestaudio/best
 [info] Writing video description to: F:\Videos\Youtube\Silvanno Trotta\Odysee\Le Confinement Tue ! - L'épidémie est finie ! .description
 [lbry] 760630f28598599bc0e3ac90aaea0154a5787a76: Downloading thumbnail ...
 [lbry] 760630f28598599bc0e3ac90aaea0154a5787a76: Writing thumbnail to: F:\Videos\Youtube\Silvanno Trotta\Odysee\Le Confinement Tue ! - L'épidémie est finie ! .png
 [debug] Invoking downloader on 'https://cdn.lbryplayer.xyz/api/v4/streams/free/Confinement/760630f28598599bc0e3ac90aaea0154a5787a76/da97c1'
 [download] Sleeping 265.55 seconds...
 ERROR: unable to download video data: HTTP Error 308: Permanent Redirect
 Traceback (most recent call last):
   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 1962, in process_info
   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 1901, in dl
   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\downloader\common.py", line 366, in download
   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\downloader\http.py", line 351, in real_download
 END :    File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\downloader\http.py", line 351, in real_download

Output for this url:
https://odysee.com/@SilvanoTrotta:f/1711:f

 [debug] System config: []
 [debug] User config: []
 [debug] Custom config: []
 [debug] Command-line args: ['https://odysee.com/@SilvanoTrotta:f/1711:f', '--ffmpeg-location', 'ffmpeg/bin/', '--playlist-start', '1', '--verbose', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,fr', '-r', '1M', '--write-thumbnail', '--yes-playlist', '--max-downloads', '10', '--write-description', '-o', 'F:/Videos/test/%(title)s.%(ext)s', '--min-sleep-interval', '240', '--max-sleep-interval', '360']
 [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
 [debug] youtube-dl version 2021.01.16
 [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
 [debug] exe versions: ffmpeg git-2020-03-15-c467328, ffprobe git-2020-03-15-c467328
 [debug] Proxy map: {}
 [lbry] @SilvanoTrotta#f/1711#f: Downloading stream JSON metadata
 [lbry] f9b99c3d0f3b986b1ed863a16235eb6c32a69e03: Downloading streaming url JSON metadata
 [debug] Default format spec: bestvideo+bestaudio/best
 [info] Writing video description to: F:\Videos\test\Leurs Mensonges au grand jour ! .description
 [lbry] f9b99c3d0f3b986b1ed863a16235eb6c32a69e03: Downloading thumbnail ...
 [lbry] f9b99c3d0f3b986b1ed863a16235eb6c32a69e03: Writing thumbnail to: F:\Videos\test\Leurs Mensonges au grand jour ! .png
 [debug] Invoking downloader on 'https://cdn.lbryplayer.xyz/api/v4/streams/free/1711/f9b99c3d0f3b986b1ed863a16235eb6c32a69e03/e0f80e'
 [download] Sleeping 304.32 seconds...
 ERROR: unable to download video data: HTTP Error 308: Permanent Redirect
 Traceback (most recent call last):
   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 1962, in process_info
   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 1901, in dl
   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\downloader\common.py", line 366, in download
   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\downloader\http.py", line 351, in real_download
   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\downloader\http.py", line 116, in establish_connection
   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\downloader\http.py", line 110, in establish_connection
   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 2274, in urlopen
   File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
   File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
   File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
   File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
   File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
 urllib.error.HTTPError: HTTP Error 308: Permanent Redirect
 END :  urllib.error.HTTPError: HTTP Error 308: Permanent Redirect

## Description

I've tried to download video from odysee.com / lbry (odysee is marked as lbry in youtubedl output) and  it often return me this error: "HTTP Error 308: Permanent Redirect"

I don't know why, sometimes it download videos, sometimes not. If i retry the same video, it can download or not i don't know why.

**Comment by october262** [comment]
play the video and press F12 on your keyboard to bring up the debug menu,
go to network - type m3u8 in the search box, copy the master.m3u8 link
and feed it into youtube-dl to download the video.
