### ISSUE TITLE
Unclear explanation

### ISSUE THREAD

**Issue by ttodua** [ytdl-org/youtube-dl#27878]
While opening the issue, I couldn't spot to which category does this issue relate, so, opening in Bug Report.

So, under [this line,](https://github.com/ytdl-org/youtube-dl/#post-processing-options) readme says:

`... (requires ffmpeg or avconv and ffprobe or avprobe) ...`

I think the spelling is not perfect. 
I was struggling to find out, if that "require" can be read as :

A) ( ffmpeg ) or ( avconv and ffprobe ) or ( avrpobe )
B) ( ffmpeg or avconv )  and ( ffprobe or avprobe )

Would be good to make a that part clearer. 
Thanks

**Comment by rautamiekka** [comment]
You're not completely without a point, but if you read the filenames it should be clear. That makes it the B one.

**Comment by mainak-debnath** [comment]
Hey! I would like to take on this issue.
