### ISSUE TITLE
Support for kissasian.sh

### ISSUE THREAD

**Issue by jefferson018200306** [ytdl-org/youtube-dl#27871]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://kissasian.sh/Drama/Mr-Queen/Episode-12?id=61958
- Single video: https://kissasian.sh/Drama/Mr-Queen/Episode-11?id=61928

## Description

Kissasian is also known as a site that has updated episodes of Korean drama and they just watch it for us for free. It also has servers to choose from so you can watch in kissasian the episode of the Korean drama you want. If possible, also add a feature to download subtitles from here. Thanks

**Comment by october262** [comment]
this link - https://kissasian.sh/Drama/Mr-Queen/Episode-12?id=61958
can be done the same way.

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free
