### ISSUE TITLE
youtube dl playlist bug

### ISSUE THREAD

**Issue by TENTHARSOS** [ytdl-org/youtube-dl#27882]
## Checklist

- [X ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.01.16**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
C:\Users\MR\Downloads\youtube dl 2>youtube-dl --verbose [download] Downloading video 25 of 37
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '[download]', 'Downloading', 'video', '25', 'of', '37']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Proxy map: {}
ERROR: '[download]' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:[download]" ) to search YouTube
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 805, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 826, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\generic.py", line 2359, in _real_extract
youtube_dl.utils.ExtractorError: '[download]' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:[download]" ) to search YouTube

C:\Users\MR\Downloads\youtube dl 2>[youtube] uylaGEzCk-0: Downloading webpage
'[youtube]' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\MR\Downloads\youtube dl 2>[download] U.S. C-RAM Shooting Down Fighter Plane - Combat Footage - Phalanx CIWS - ArmA 3-uylaGEzCk-0.webm has already been downloaded and merged
'[download]' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\MR\Downloads\youtube dl 2>[download] Downloading video 26 of 37
'[download]' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\MR\Downloads\youtube dl 2>[youtube] rnNW72ioTKg: Downloading webpage
'[youtube]' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\MR\Downloads\youtube dl 2>[youtube] rnNW72ioTKg: Downloading embed webpage
'[youtube]' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\MR\Downloads\youtube dl 2>[youtube] rnNW72ioTKg: Refetching age-gated info webpage
'[youtube]' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\MR\Downloads\youtube dl 2>WARNING: Unable to extract video title
'WARNING:' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\MR\Downloads\youtube dl 2>ERROR: no conn, hlsvp, hlsManifestUrl or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
'ERROR:' is not recognized as an internal or external command,
operable program or batch file.

## Description

WRITE DESCRIPTION HERE

I have no clue where i am or what i am doing here and that should be an indicator for why i only checked 3 of the 6 boxes above.
I don't know what an "argument" is , what a bugtracker is, or where the FAQ page is.
I'm just doing what YTDL told me to do by coming here to report this issue.

If there is missing information above, reach back to me i guess, and i will try to copy the code that came up after this issue happened.

As for the issue itself, I'll just stop trying to use YTDL to download playlists larger than 25 videos, it always stops the playlist download right after a 25th video.

I'm not very informed about all this and am just learning, so no sense in me making any complaint.
Again, I'm just doing the program told me to do.

**Comment by remitamine** [comment]
you should search online on how to use command line tools.

**Comment by TENTHARSOS** [comment]
> you should search online on how to use command line tools.

Like i said, I'm just doing what the program asked me to do i.e. report this issue.

If no wants to hear it, i guess just close it then.
