### ISSUE TITLE
how to  get comment_count in youtube ?

### ISSUE THREAD

**Issue by asd3427** [ytdl-org/youtube-dl#27881]
## Checklist

- [v ] I'm asking a question
- [ v] I've looked through the README and FAQ for similar questions
- [ v] I've searched the bugtracker for similar questions including closed ones
- [ v]I've verified that I'm running youtube-dl version 2021.01.16

## Question

im try to get the videos info it worked but i can't get comment_count im try so many times 

## part info 
{
  "id": "qWWQmDnKQcQ",
  "uploader": "Joeman",
  "uploader_id": "JoemanStarCraft",
  "uploader_url": "http://www.youtube.com/user/JoemanStarCraft",
  "channel_id": "UCPRWWKG0VkBA0Pqa4Jr5j0Q",
  "channel_url": "http://www.youtube.com/channel/UCPRWWKG0VkBA0Pqa4Jr5j0Q",
  "upload_date": "20150213",
  "license": null,
  "creator": null,
  "title": "\u300aDying Light \u5782\u6b7b\u4e4b\u5149 \u300b\u5be6\u6cc1\u7cbe\u83ef \u6700\u7d42\u8dd1\u9177\u96e3\u95dc final Parkour",
  "alt_title": null,
  "thumbnails": [
    {
      "url": "https://i.ytimg.com/vi/qWWQmDnKQcQ/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLAEVmuPmSTauTFtBUClViPgi41Bog",
      "width": 168,
      "height": 94,
      "resolution": "168x94",
      "id": "0"
    },
    {
      "url": "https://i.ytimg.com/vi/qWWQmDnKQcQ/hqdefault.jpg?sqp=-oaymwEYCMQBEG5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLCpEXJXRFWeFT1XihgpvABBJOH8MA",
      "width": 196,
      "height": 110,
      "resolution": "196x110",
      "id": "1"
    },
    {
      "url": "https://i.ytimg.com/vi/qWWQmDnKQcQ/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDpEOLjULmxZAT8NSbsy8CnZZAPwQ",
      "width": 246,
      "height": 138,
      "resolution": "246x138",
      "id": "2"
    },
    {
      "url": "https://i.ytimg.com/vi/qWWQmDnKQcQ/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBVpvSB5RB2U15tREUD0cfLJXyb4A",
      "width": 336,
      "height": 188,
      "resolution": "336x188",
      "id": "3"
    }
  ],
  "description": "Subscribe now  / \u8a02\u95b1Joeman\u7684\u983b\u9053 \uff1ahttp://goo.gl/H5hUk7\nFacebook / FB\u5c08\u9801: https://www.facebook.com/JoemanStation",
  "categories": [
    "Travel & Events"
  ],
  "tags": [
    "twitch",
    "games"
  ],
  "subtitles": {},
  "automatic_captions": {},
  "duration": 1851,
  "age_limit": 0,
  "annotations": null,
  "chapters": null,
  "webpage_url": "https://www.youtube.com/watch?v=qWWQmDnKQcQ",
  "view_count": 7286,
  "like_count": 25,
  "dislike_count": 13,
  "average_rating": 3.6315789,

## python code 
`import youtube_dl

class tests:
    def __init__(self):
        pass

    def extract_info(self, webpage_url, extract_flat=True, collaborate=True):
        """
        Extracting the webpage by youtube-dl without downloading
        :param webpage_url:
        :param collaborate: IGNORE THIS (seems to be useless at this point)
        :return:
        """
        args = {
            "nocheckcertificate": True,
            "ignoreerrors": True,
            "quiet": True,
            "nopart": True,
            # "download_archive": "record.txt",
            "no_warnings": True,
            "youtube_include_dash_manifest": False,
            'simulate': True,
            'user-agent': '',
            "proxy": None,
            "extract_flat": extract_flat
        }
        with youtube_dl.YoutubeDL(args) as ydl:
            try:
                VideoJson = ydl.extract_info(webpage_url, extra_info={"comment_count": ''})
                print(VideoJson)

            except Exception as e:
                print(e)

if __name__ == '__main__':
    tt = tests()
    tt.extract_info("http://youtube.com/watch?v=qWWQmDnKQcQ", extract_flat=False)
`

**Comment by remitamine** [comment]
not provided by youtube.
