### ISSUE TITLE
Downloading a specific YT channel's videos, total incorrect videos are downloading

### ISSUE THREAD

**Issue by richardARPANET** [ytdl-org/youtube-dl#27889]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
There is no special output in the logs
```

## Description

I'm using youtube-dl to backup some ENTIRE youtube channels using this tool https://github.com/VeemsHQ/yt-channels-archive/blob/master/yt_archive/cli.py#L44

This works well except after some time youtube-dl will begin downloading random other videos, (some in German?!), even though there is no relation between the target download channel and them.

Has anyone else ran into this issue or can see anything missing in the above code which could cause this to happen?

Example target channel URL which causes this https://www.youtube.com/c/SargonofAkkad

**Comment by remitamine** [comment]
you have to use the channel videos URL(https://www.youtube.com/c/SargonofAkkad/videos).
