### ISSUE TITLE
Youtube-dl not downloading watch later playlist

### ISSUE THREAD

**Issue by DilanRona** [ytdl-org/youtube-dl#27884]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.01.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dlc -v -u r_xxx.o_xxx@gmail.com -j https://www.youtube.com/playlist?list=WL --playlist-start 1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-j', 'https://www.youtube.com/playlist?list=WL', '--playlist-start', '1']
Type account password and press [Return]: 
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.7.5 (CPython) - Linux-5.3.11-100.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
[debug] exe versions: ffmpeg 4.0.5, ffprobe 4.0.5
[debug] Proxy map: {}
WARNING: Unable to look up account info: HTTP Error 400: Bad Request

## Description

WRITE DESCRIPTION HERE
Trying to download the watch later playlist. Entered credidentials as requested, and it keeps giving the same error. Tried youtube-dl, and youtube-dlc. Same result.

**Comment by dstftw** [comment]
You have to use authenticated cookies.
