### ISSUE TITLE
Snapchat stories

### ISSUE THREAD

**Issue by BlueBurgersTDD** [ytdl-org/youtube-dl#27886]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://story.snapchat.com/o/W7_EDlXWTBiXAEEniNoMPwAAY-z2zNJOefcEyAXcB9SuxAXcB9SsTAO1OAA

## Description

It does not require any app and is playable in a browser without any authentication

**Comment by october262** [comment]
just press F12 on your keyboard to bring up the debug menu, select network, type mp4
in the search box, copy the media.mp4 link and feed it into youtube-dl to download the video.
