### ISSUE TITLE
FranceCulture is broken

### ISSUE THREAD

**Issue by aurelg** [ytdl-org/youtube-dl#27891]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.01.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['--restrict-filenames']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.franceculture.fr/emissions/la-methode-scientifique/la-methode-scientifique-emission-du-mercredi-20-janvier-2021']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.9.1 (CPython) - Linux-5.10.7-arch1-1-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[FranceCulture] la-methode-scientifique-emission-du-mercredi-20-janvier-2021: Downloading webpage
ERROR: Unable to extract video data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/aurelien/nosave/./youtube-dl/youtube_dl/YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aurelien/nosave/./youtube-dl/youtube_dl/YoutubeDL.py", line 826, in __extract_info
    ie_result = ie.extract(url)
  File "/home/aurelien/nosave/./youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/aurelien/nosave/./youtube-dl/youtube_dl/extractor/franceculture.py", line 33, in _real_extract
    video_data = extract_attributes(self._search_regex(
  File "/home/aurelien/nosave/./youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I think the verbose output says it all. Thanks for this awesome work!

**Comment by october262** [comment]
for this link - https://www.franceculture.fr/emissions/la-methode-scientifique/la-methode-scientifique-emission-du-mercredi-20-janvier-2021  just press F12 on you keyboard to bring up the debug menu, select network - media - play the podcast and you should see the mp3 link,
copy the link and feed it into youtube-dl to download the podcast.

**Comment by aurelg** [comment]
Thanks @october262 

That's only a workaround though, since having to open the URL in a web browser defeats the very purpose of CLI-based downloading which is what youtube-dl is all about. The FranceCulture extractor was working perfectly until a few days ago. I hope/guess it's "just" a matter of rewriting [the previous regexp](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/franceculture.py#L34-L40).
