### ISSUE TITLE
TF1 wat.tv  "HTTP Error 403: Forbidden" No video found

### ISSUE THREAD

**Issue by Atrebate** [ytdl-org/youtube-dl#27901]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
~ $ youtube-dl --format best  -o '/media/lgb/Linux/%(title)s.%(ext)s' https://www.tf1.fr/tf1/doc/videos/doc-s01-e01-memoire-enfouie-10495093.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--format', u'best', u'-o', u'/media/lgb/Linux/%(title)s.%(ext)s', u'https://www.tf1.fr/tf1/doc/videos/doc-s01-e01-memoire-enfouie-10495093.html', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 2.7.12 (CPython) - Linux-4.10.0-38-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: ffmpeg 2.8.17, ffprobe 2.8.17
[debug] Proxy map: {}
[TF1] doc-s01-e01-memoire-enfouie-10495093: Downloading webpage
[wat.tv] 13758789: Downloading JSON metadata
[wat.tv] 13758789: Downloading JSON metadata
[wat.tv] 13758789: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[wat.tv] 13758789: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[wat.tv] 13758789: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[wat.tv] 13758789: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[wat.tv] 13758789: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno -2] Name or service not known>
[wat.tv] 13758789: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno -2] Name or service not known>
[wat.tv] 13758789: Checking http-264 URL
[wat.tv] 13758789: http-264 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
[wat.tv] 13758789: Checking http-464 URL
[wat.tv] 13758789: http-464 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
[wat.tv] 13758789: Checking http-664 URL
[wat.tv] 13758789: http-664 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
[wat.tv] 13758789: Checking http-1264 URL
[wat.tv] 13758789: http-1264 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
[wat.tv] 13758789: Checking http-1864 URL
[wat.tv] 13758789: http-1864 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
[wat.tv] 13758789: Checking http-2564 URL
[wat.tv] 13758789: http-2564 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 837, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 871, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1559, in process_video_result
    raise ExtractorError('No video formats found!')
ExtractorError: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
I use the same request 2 day ago without any error.
To day any request on any file on TF1 site (wat.tv) stop with an error

**Comment by pingu1** [comment]
Same here, even after updating to the latest version (2021.01.16).

**Comment by Atrebate** [comment]
Why request closed ???? 
Problem is always pending to day!!!

**Comment by tampa-bay** [comment]
Appears to only pull SD videos.  Maybe the 720p stream URLs are moved, as I can pull them when logged in (georestricted), but not from the fixes.  It appears that I can find the 720p mpd URL by accessing https://delivery.tf1.fr/mytf1-wrd/{video_id} and 720p hls at https://delivery.tf1.fr/mytf1-wrd/{video_id}?format=hls, but those are georestricted.

**Comment by Atrebate** [comment]
update with last release today : release **2021.01.24**.... and.... **I can Download TF1 (wat.tv)  again**
Thanks a lot
