### ISSUE TITLE
ERROR: You don't have permission to access this video.

### ISSUE THREAD

**Issue by Nishit-Dua** [ytdl-org/youtube-dl#27907]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
sudo youtube-dl -v -u f20180620@goa.bits-pilani.ac.in -p $MYPASSWORD https://drive.google.com/file/d/1bl2iBUDkkfcA3I8ffE8S11VrDiwwW3Kk/view
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://drive.google.com/file/d/1bl2iBUDkkfcA3I8ffE8S11VrDiwwW3Kk/view']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.8.5 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[GoogleDrive] 1bl2iBUDkkfcA3I8ffE8S11VrDiwwW3Kk: Downloading webpage
ERROR: You don't have permission to access this video.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 826, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/googledrive.py", line 175, in _real_extract
    raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: You don't have permission to access this video.
```

## Description

Hi I tried to Download lectures from Gdrive where my Uni uploads it. It Threw `ERROR: You don't have permission to access this video.` at me i have no damn clue, Sorry i can't provide my uni credentials and i have no work around this but i assure you the password i entered is the correct password and i can view the video is browser.

**Comment by Harshkumar77** [comment]
any update i have to download from private drive ?

**Comment by 89z** [comment]
Please provide example URL

**Comment by dirkf** [comment]
Use the extension shown in the FAQ. Unfortunately site login procedures are prone to change and be broken by Captcha (etc) protection, making it unlikely that passing username+password to yt-dl will work, but cookies will generally succeed. It may be necessary to send headers that match the browser where the cookies were set (eg User-agent), but not with YouTube AFAIK.
