### ISSUE TITLE
Why does youtube-dl always modify cookies file

### ISSUE THREAD

**Issue by kietheros** [ytdl-org/youtube-dl#27908]
I write an app to manage cookies files and use youtube-dl to download from youtube. When pass the cookies,  youtube-dl always modifies this file, so I have some following problems:
1. Is it safe if I call 2 youtube-dl using the same cookies file (Or another process updates this file)
2. Can I ask youtube-dl not to modify the cookies file directly ?

Thank you !

**Comment by dstftw** [comment]
1. No.
2. No, since it has to modify cookies to reflect potential changes by remote party during extraction process.
