### ISSUE TITLE
Add support for Facebook Workplace videos

### ISSUE THREAD

**Issue by DaBomby** [ytdl-org/youtube-dl#27909]
## Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2021.01.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs violate any copyrights
- [X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://abc.workplace.com/100028380075587/videos/336048507351199/

## Diagnostics Output

`youtube-dl.exe -f "bestvideo+bestaudio" --write-thumbnail --write-description --console-title --merge-output-format "mp4" --all-subs --embed-thumbnail --add-metadata --add-header "Cookie: datr______" https://abc.workplace.com/100028380075587/videos/336048507351199/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-100592-g42ee3898c8, ffprobe N-100592-g42ee3898c8
[debug] Proxy map: {}
[generic] 336048507351149: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 336048507351149: Downloading webpage
[generic] 336048507351149: Extracting information
ERROR: Unsupported URL: https://abc.workplace.com/100028380075587/videos/336048507351199/
Traceback (most recent call last):
  File "C:\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 805, in wrapper
  File "C:\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\YoutubeDL.py", line 826, in __extract_info
  File "C:\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\youtube-dl\ytdl-org\tmpfnvjp7pc\build\youtube_dl\extractor\generic.py", line 3467, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://abc.workplace.com/100028380075587/videos/336048507351199/`

## Description

Please add support for Facebook Workplace videos. This would be similar to the support that currently exists for private Facebook videos.

**Comment by remitamine** [comment]
not accessible in the browser.
> Sorry, this page isn't available
The link you followed may be broken, or the page may have been removed.

**Comment by DaBomby** [comment]
> 
> 
> not accessible in the browser.
> 
> > Sorry, this page isn't available
> > The link you followed may be broken, or the page may have been removed.

Is there a reason that you are so eager to close issues? This is in the format that you wanted.
