### ISSUE TITLE
download from raiplay

### ISSUE THREAD

**Issue by jodathewise1969** [ytdl-org/youtube-dl#27902]
## Checklist

- [x ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
i've tried to download the video from link:
https://www.raiplay.it/video/2021/01/Che-Dio-ci-aiuti-S6E1-E-tu-sei-pronto-b4b77f3a-0496-4c99-95ab-097034450b02.html
but the result is without audio
the only stream downloaded is video
my config parameters are:
-o "I:\downloads\youtube-dl\%(title)s-%(id)s.%(ext)s"
where i'm wrong?
thanks

**Comment by nixxo** [comment]
in some tv shows the audio and video streams are separated so do 
-f "bestvideo+bestaudio"

**Comment by jodathewise1969** [comment]
not working...
