### ISSUE TITLE
Download in TF1.fr / WAT.tv is no more available

### ISSUE THREAD

**Issue by guy-teube** [ytdl-org/youtube-dl#27924]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

$ sudo youtube-dl -U
[sudo] Mot de passe de me : 
youtube-dl is up-to-date (2021.01.16)

$ youtube-dl -F https://www.tf1.fr/tf1/barbapapa/videos/barbapapa-lempire-orange-18906322.html
[TF1] barbapapa-lempire-orange-18906322: Downloading webpage
[wat.tv] 13762382: Downloading JSON metadata
[wat.tv] 13762382: Downloading JSON metadata
[wat.tv] 13762382: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[wat.tv] 13762382: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[wat.tv] 13762382: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[wat.tv] 13762382: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[wat.tv] 13762382: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno -2] Name or service not known>
[wat.tv] 13762382: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno -2] Name or service not known>
[wat.tv] 13762382: Checking http-264 URL
[wat.tv] 13762382: http-264 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
[wat.tv] 13762382: Checking http-464 URL
[wat.tv] 13762382: http-464 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
[wat.tv] 13762382: Checking http-664 URL
[wat.tv] 13762382: http-664 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
[wat.tv] 13762382: Checking http-1264 URL
[wat.tv] 13762382: http-1264 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
[wat.tv] 13762382: Checking http-1864 URL
[wat.tv] 13762382: http-1864 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
[wat.tv] 13762382: Checking http-2564 URL
[wat.tv] 13762382: http-2564 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

youtube-dl worked fine to download videos on TF1.fr (french TV channel), until january 21st.
Since this date, download is no more possible, with the logs posted before.

I didn't find any m3u8 file in the F12 tool > Network tab.

**Comment by october262** [comment]
is an account needed in order to watch the videos ??

**Comment by guy-teube** [comment]
Yes an account in needed. I can passe my logins, how to do this in private?

**Comment by guy-teube** [comment]
Sorry I didn't understand why it's closed, and fixed ? I have searched but didn't find the same issue, so duplicate of what ?
