### ISSUE TITLE
"This video is not available" error

### ISSUE THREAD

**Issue by refactory-max** [ytdl-org/youtube-dl#27926]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

% youtube-dl -v -F 'https://www.youtube.com/watch?v=cI6hGpBo0sc'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.youtube.com/watch?v=cI6hGpBo0sc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.9.1 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] cI6hGpBo0sc: Downloading webpage
ERROR: This video is not available.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 826, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.16/libexec/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 2105, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is not available.

## Description

https://www.youtube.com/watch?v=cI6hGpBo0sc
https://www.youtube.com/watch?v=mWQ_x2ltWD8

The above 2 videos are both viewable on YouTube website using Chrome browser. However, when I tried youtube-dl with `cI6hGpBo0sc` I saw the `This video is not avaiable` error but `mWQ_x2ltWD8` works fine.

**Comment by refactory-max** [comment]
I have tried several more videos, it looks like new viedos (posted within few days) will show the above error.

**Comment by remitamine** [comment]
the same message is displayed in the browser.
