### ISSUE TITLE
Random string after downloaded file name.

### ISSUE THREAD

**Issue by nitish770** [ytdl-org/youtube-dl#27928]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

I have downloaded a bunch of videos using youtube-dl but in all file names there's a random string (like hash) at last. What is that for. How can i make youtube-dl not to put it.

**Comment by remitamine** [comment]
read [OUTPUT TEMPLATE](https://github.com/ytdl-org/youtube-dl#output-template) documentation.
