### ISSUE TITLE
tf1/wat.tv now enforces a login to play videos

### ISSUE THREAD

**Issue by theocrite** [ytdl-org/youtube-dl#27925]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

> $ export user='ytdl_debug@mailinator.com'
> $ export pass='123456Aa!'
> 
> $ youtube-dl -v -u "$user" -p "$pass" https://www.tf1.fr/tmc/quotidien-avec-yann-barthes/videos/quotidien-deuxieme-partie-du-22-janvier-2021-29157215.html
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.tf1.fr/tmc/quotidien-avec-yann-barthes /videos/quotidien-deuxieme-partie-du-22-janvier-2021-29157215.html']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2021.01.16
> [debug] Python version 2.7.16 (CPython) - Linux-4.19.0-13-amd64-x86_64-with-debian-10.7
> [debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 2.1.1, rtmpdump 2.4
> [debug] Proxy map: {}
> [TF1] quotidien-deuxieme-partie-du-22-janvier-2021-29157215: Downloading webpage
> [wat.tv] 13761877: Downloading JSON metadata
> [wat.tv] 13761877: Downloading JSON metadata
> [wat.tv] 13761877: Downloading m3u8 information
> WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
> [wat.tv] 13761877: Downloading f4m manifest
> WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
> [wat.tv] 13761877: Downloading m3u8 information
> WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
> [wat.tv] 13761877: Downloading f4m manifest
> WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
> [wat.tv] 13761877: Downloading MPD manifest
> WARNING: Failed to download MPD manifest: <urlopen error [Errno -2] Name or service not known>
> [wat.tv] 13761877: Downloading MPD manifest
> WARNING: Failed to download MPD manifest: <urlopen error [Errno -2] Name or service not known>
> [wat.tv] 13761877: Checking http-264 URL
> [wat.tv] 13761877: http-264 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
> [wat.tv] 13761877: Checking http-464 URL
> [wat.tv] 13761877: http-464 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
> [wat.tv] 13761877: Checking http-664 URL
> [wat.tv] 13761877: http-664 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
> [wat.tv] 13761877: Checking http-1264 URL
> [wat.tv] 13761877: http-1264 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
> [wat.tv] 13761877: Checking http-1864 URL
> [wat.tv] 13761877: http-1864 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
> [wat.tv] 13761877: Checking http-2564 URL
> [wat.tv] 13761877: http-2564 URL is invalid, skipping: <urlopen error [Errno -2] Name or service not known>
> ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "/home/theo/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 805, in wrapper
>     return func(self, *args, **kwargs)
>   File "/home/theo/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 837, in __extract_info
>     return self.process_ie_result(ie_result, download, extra_info)
>   File "/home/theo/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 871, in process_ie_result
>     return self.process_video_result(ie_result, download=download)
>   File "/home/theo/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1559, in process_video_result
>     raise ExtractorError('No video formats found!')
> ExtractorError: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

For few days, tf1 disabled the ability to play videos without being logged in.

We're now unable to watch anything without credential (website or ytdl).

ytdl's login options (-u and -p) seems to have no effect.

Sample credentials:
- export user='ytdl_debug@mailinator.com'
- export pass='123456Aa!'

**Comment by tampa-bay** [comment]
Not exactly fully fixed.  But maybe as far as you are willing/wanting/able to go.  The method as fixed pulls SD streams only.  Once logged in, one can get m3u and mpd data for a 720p stream, but the fixes as implemented don't utilize login and password.  I found that passing the video ID to https://delivery.tf1.fr/mytf1-wrd/{video_id}?format gets the max_bitrate=28000000 mpd and https://delivery.tf1.fr/mytf1-wrd/{video_id}?format=hls does find the max_bitrate=28000000 hls.  Though, that URL is georestricted, but no login needed.
