### ISSUE TITLE
Unsupported URL error in single article page in 3sat mediathek

### ISSUE THREAD

**Issue by mendberg** [ytdl-org/youtube-dl#27930]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.01.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -r 5M "https://www.3sat.de/wissen/nano/210120-radschnellwege-nano-104.html" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-r', '5M', 'https://www.3sat.de/wissen/nano/210120-radschnellwege-nano-104.html', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.9.1 (CPython) - Linux-5.9.16-1-MANJARO-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 210120-radschnellwege-nano-104: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 210120-radschnellwege-nano-104: Downloading webpage
[generic] 210120-radschnellwege-nano-104: Extracting information
WARNING: [generic] 210120-radschnellwege-nano-104: Failed to parse JSON Expecting ',' delimiter: line 23 column 26 (char 580)
WARNING: [generic] 210120-radschnellwege-nano-104: Failed to parse JSON Expecting property name enclosed in double quotes: line 11 column 9 (char 284)
ERROR: Unsupported URL: https://www.3sat.de/wissen/nano/210120-radschnellwege-nano-104.html
Traceback (most recent call last):
  File "/NUeB/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "/NUeB/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 826, in __extract_info
    ie_result = ie.extract(url)
  File "/NUeB/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/NUeB/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3467, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.3sat.de/wissen/nano/210120-radschnellwege-nano-104.html

$ youtube-dl -U
youtube-dl is up-to-date (2021.01.16)

```

## Description

When trying do download the video from the single article page https://www.3sat.de/wissen/nano/210120-radschnellwege-nano-104.html I get that "Unsupported URL" error as shown in the command line log above.

**Comment by october262** [comment]
play the video and press F12 to bring up the debug menu, 
go to network - media, the first file that shows, copy the link,
and feed it into youtube-dl to download the video. please note that the video
will be in webm format so you may want to use ffmpeg to convert the video from
webm to mp4.

**Comment by Negativland** [comment]
> play the video and press F12 to bring up the debug menu,
> go to network - media, the first file that shows, copy the link,
> and feed it into youtube-dl to download the video.

Thanks, that works for me.
