### ISSUE TITLE
Get the links of subtitles instead of downloading them

### ISSUE THREAD

**Issue by E-Mans-Application** [ytdl-org/youtube-dl#27933]
Hello,

I would like to get the links of the videos and of the subtitles without downloading them.
The purpose is to call youtube-dl from a server and to pass the links to a remote client. The server must not download the videos or the subtitles upon every request. (But the server could call youtube-dl multiple times for each request if the video and the subtitles cannot be obtained together. As there will not be many requests, this will not generate heavy traffic.)

The "-g" option does what I want with the videos, but this gives no link for the subtitles, even when adding "--write-auto-sub".

`youtube-dl --write-auto-sub -g https://www.youtube.com/watch?v=...`
-> Returns a link for the video, and a link for the audio, but no link for the subtitles.

If I remove the "-g" option (and I add "--skip-download"), the video is not downloaded but the subtitles are.

`youtube-dl --write-auto-sub --skip-download https://www.youtube.com/watch?v=...`
-> Downloads the subtitles in the working directory.

Am I missing an option to get only the link of the subtitles or is this option not implemented yet?

Sincerely,
E__Man.

**Comment by dstftw** [comment]
`--dump-json` and parse.
