### ISSUE TITLE
SSLCertVerificationError

### ISSUE THREAD

**Issue by peterwillcn** [ytdl-org/youtube-dl#27931]
[youtube] ylOc6TBL1tA: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

**Comment by peterwillcn** [comment]
brew remove openssl and brew install openssl Fixed.

**Comment by kxxc** [comment]
> brew install openssl

thank you! you are a life saver!
