### ISSUE TITLE
-f best = low

### ISSUE THREAD

**Issue by mashkov55** [ytdl-org/youtube-dl#27935]
Why i set for youtube link -f best
But my video always downloaded with worst quality, always.

![image](https://user-images.githubusercontent.com/77289781/105607987-49e15c80-5db2-11eb-92e3-814ea3354894.png)

![image](https://user-images.githubusercontent.com/77289781/105607999-5e255980-5db2-11eb-865d-656ba981e35e.png)

**Comment by remitamine** [comment]
read [FORMAT SELECTION](https://github.com/ytdl-org/youtube-dl#format-selection) documentation.

**Comment by mashkov55** [comment]
> read [FORMAT SELECTION](https://github.com/ytdl-org/youtube-dl#format-selection) documentation.

if i set -f best[height=1080], i downloaded video 1080 quality but without audio, i understand why
do you can help me pls?

**Comment by remitamine** [comment]
use `-f bestvideo+bestaudio`, install ffmpeg if you don't have it.

**Comment by rautamiekka** [comment]
https://www.gyan.dev/ffmpeg/builds/ is where to get FFmpeg for Window$.

Scroll down to the `release` section (section name in green) and take the link https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z

I recommend extracting the contents (without the root folder) to `C:\Users\Public\Downloads\ffmpeg\`, then add
```cmd
--ffmpeg-location "C:\Users\Public\Downloads\ffmpeg\bin"
```
to your command or rc file.
