### ISSUE TITLE
Requesting support for ktkkt.top

### ISSUE THREAD

**Issue by kmak031** [ytdl-org/youtube-dl#27938]
## Checklist

- [x ] I'm reporting a new site support request
- [x ] I've verified that I'm running youtube-dl version **2021.01.16**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that none of provided URLs violate any copyrights
- [x ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.ktkkt.top/play/13315-1-114.html
- Single video: https://www.ktkkt.top/play/13315-1-116.html
- Playlist: https://www.ktkkt.top/movie/index13315.html

## Description

WRITE DESCRIPTION HERE
No credentials required.
They provide two source of cloud streaming

**Comment by october262** [comment]
play the video and press F12 on your keyboard to bring up the debug menu,
go to network - type m3u8 in the search box, copy the first index.m3u8 link
and feed it into youtube-dl to download the video.

**Comment by kmak031** [comment]
![image](https://user-images.githubusercontent.com/73553831/105637268-9f614c00-5e3a-11eb-97f9-a3a26d53da06.png)
I am lost on where to find the index.m3u8 link.
I found some links like ttps://v4.monidai.com/20200627/CBJ0wyDs/1000kb/hls/XT5vwH63471016.ts under header
but youtube-dl only captured like 5 seconds of the video

**Comment by october262** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/73553831/105637268-9f614c00-5e3a-11eb-97f9-a3a26d53da06.png)
> I am lost on where to find the index.m3u8 link.
> I found some links like ttps://v4.monidai.com/20200627/CBJ0wyDs/1000kb/hls/XT5vwH63471016.ts under header
> but youtube-dl only captured like 5 seconds of the video

did you try refreshing the webpage ??

**Comment by kmak031** [comment]
Nice, that worked! I found the index.m3u8 url, and with ffmpeg i am able to download it.
I wonder if there is a way to do it in batch or I will need to find each link one by one.
Thanks a lot for your great tips!
