### ISSUE TITLE
XHamster new URLs return “no video formats found”

### ISSUE THREAD

**Issue by ThrowAway4235** [ytdl-org/youtube-dl#27942]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

[user@Arch]$ youtube-dl -v https://xhamster.com/videos/blowing-closeted-sailor-on-us-navy-ship-fully-amateur-xhwoxfM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://xhamster.com/videos/blowing-closeted-sailor-on-us-navy-ship-fully-amateur-xhwoxfM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 3.9.1 (CPython) - Linux-5.10.5-aarch64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[XHamster] xhwoxfM: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 826, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/xhamster.py", line 178, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

It seems xHamster changed it’s video URL scheme. Any videos ending in a random string (Numbers and Letters) end up with the error above, while videos ending in random numbers work (Example URL: https://xhamster.com/videos/a-friend-fuck-and-cum-inside-my-boyfriend-bareback-12790329) and download just fine.

I tried to do some further investigation (using other converting software), and it seems they’re only able to find the 480p version and lower, which leads me to believe their HD content is moving towards a newer format maybe? Either way this is something thats gonna become worse if not looked at soon.

**Comment by october262** [comment]
for this video - https://xhamster.com/videos/blowing-closeted-sailor-on-us-navy-ship-fully-amateur-xhwoxfM, just play the video and press F12 on your keyboard to bring up the debug menu.
go to network - type m3u8 in the search box, copy the master.m3u8 link and feed it into youtube-dl to download the video

**Comment by acc-testerino** [comment]
I'm also having this issue. How come you can't reproduce?

**Comment by taxhelp101** [comment]
I'm having the same exact issue. I believe that youtube-dl needs to have their extractor for xhamster updated.
