### ISSUE TITLE
TF1 Séries Fillms [wat] "ExtractorError: No video formats found" with YT-DL

### ISSUE THREAD

**Issue by St-Galaad** [ytdl-org/youtube-dl#27958]
- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés.

C:\Users\xxxxxx>youtube-dl --version
2021.01.24.1

C:\Users\xxxxxx>youtube-dl -U
youtube-dl is up-to-date (2021.01.24.1)

C:\Users\xxxxxx>youtube-dl -v -F https://www.tf1.fr/tf1-series-films/killing-eve/videos/killing-eve-s02-e04-aux-grands-maux-les-grands-remedes-98232783.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.tf1.fr/tf1-series-films/killing-eve/videos/killing-eve-s02-e04-aux-grands-maux-les-grands-remedes-98232783.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[TF1] killing-eve-s02-e04-aux-grands-maux-les-grands-remedes-98232783: Downloading webpage
[wat.tv] 13760979: Downloading JSON metadata
[wat.tv] 13760979: Downloading JSON metadata
[wat.tv] 13760979: Downloading m3u8 information
[wat.tv] 13760979: Downloading MPD manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\extractor\wat.py", line 101, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_eeieglg\build\youtube_dl\extractor\common.py", line 1367, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

With the latest version '2021.01.24.1' of 'youtube-dl', it works for TF1 Group (TF1, TMC, TFX) except for "TF1 Séries Films" which occurs an error,.
For example with "Killing Eve":
https://www.tf1.fr/tf1-series-films/killing-eve/videos/killing-eve-s02-e04-aux-grands-maux-les-grands-remedes-98232783.html
this video works perfectly on Firefox, can be downaload using "Capvty (http://captvty.fr/)" but failed with latest 'youtube-dl v.2021.01.24.1'.

Too be complete, see images:
![log_ youtube-dl](https://user-images.githubusercontent.com/40656385/105660972-8bfec100-5ecc-11eb-9644-d0e2c39d706b.jpg)
![firefox_ Killing Eve](https://user-images.githubusercontent.com/40656385/105661021-ae90da00-5ecc-11eb-886e-88aadbf0ff6c.jpg)
![Captvty_ KillingEve](https://user-images.githubusercontent.com/40656385/105661029-b3ee2480-5ecc-11eb-8707-50ffcdb0c326.jpg)

Thanks.

**Comment by Azzuray** [comment]
its a IISM MPEG DASH  like : `https://das-q1-ssl.tf1.fr/2/USP-0x0/09/79/13760979/ssm/d01932f3f14daa1e6e266ab7ff5ef0544a8ed6c9c323947e1f2eb6a943d8e860.ism/13760979.mpd?e=1611930638&max_bitrate=2800000&st=XXtxTN76D7f6kDnJxra1PQ`

**Comment by remitamine** [comment]
No longer accessible, Most likely DRM protected.

**Comment by St-Galaad** [comment]
Hello,
I don't think it's a "DRM" issue cause 'youtube-dl' give us the 'wat-id' and the most important is that the French freeware "Captvty" can download the tv shows of TF1 company: TF1/TMX/TFX/TF1 Séries Films. And "Captvty" will not download any program with "DRM". So something changed in the way of accessing TF1 company tv shows.
Note that the difference is that "Captvty" DL a '.ts' and 'youtube-dl' DK a '.mp4'.
You (team) have always found a solution so I hope these informatipns will help you !
Have a good day.

**Comment by remitamine** [comment]
either way, the URL posted here is no longer accessible, if there is a particular URL that still does not work with latest changes(295860ff00c5d8caf94badd4f04671f6a631fcae) you can post it here or on a new issue.

**Comment by St-Galaad** [comment]
Yep, the url is no longer valid.
Here's for example one valid: https://www.tf1.fr/tf1/esprits-criminels/videos/esprits-criminels-s06-e15-paroles-et-musique-52564944.html
It's valid from 21-02-2021 @ 23h15 to 28-02-2021 @ 23h15.
:)
