### ISSUE TITLE
I need youtube-dl to work with stickytape

### ISSUE THREAD

**Issue by lborgman** [ytdl-org/youtube-dl#27954]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
I need stickytape to work for youtube-dl. (I am working on an accessibility problem.)

I have reported an issue over at stickytape (https://github.com/mwilliamson/stickytape/issues/20, please ignore that it is currently closed, that is just a communication problem).

As I said there I do not normally use python. So it is quite a big step for me to step in to solve the problem. Though if someone here has relevant input that would be very nice. (And then I can perhaps step in to solve the problem.)

**Comment by mwilliamson** [comment]
Hello! I'm the author of stickytape. I don't think there's anything for youtube-dl to address: the issue is in stickytape.

**Comment by lborgman** [comment]
I am not saying there is something wrong with youtube-dl. I am just asking for help with this. (I need this for an accessibility project, if someone is interested in such questions.)
