### ISSUE TITLE
some NHK Vods are currupt (?) or not fully downloading.

### ISSUE THREAD

**Issue by soulflexin81** [ytdl-org/youtube-dl#27953]
Have a folder of around 10 or so various random episodes that for some reason do not decide to play in anything, despite having returned no errors whilst downloading. Have repeated the downloads many times and always the same, they just don't play or open in anything, even various video tools apps. 

What's strange is the Vods play as expected on the website, so the source is fine. It's also random, maybe 1 out of a season will not play.

Here's an example (which also downloads only half the file size)

https://www3.nhk.or.jp/nhkworld/en/ondemand/program/video/10yearshayaomiyazaki

episodes 2 and 4 do not play after downloading, and only downloads around 1.4GB, despite showing that the 'best' is around 3.6GB. 

Episodes 1 and 3 do download fully and _are_ around 3.6GB.

also note the odd random numbers at the end of the filenename...

http-10262   mp4        1920x1080  10262k video@9765k, audio@497k, **3.60GiB (best)**

youtube-dl -f best https://www3.nhk.or.jp/nhkworld/en/ondemand/video/3004581/

[download] Destination: 10 Years with Hayao Miyazaki - Ep. 2 Drawing What's Real **-eb67a418**.mp4
[download] **100% of 1.43GiB** in 06:38

if anyone can figure this out or have any pointers let me know! thx

**Comment by mcdamo** [comment]
Tested Ep. 2:
```
youtube-dl -v https://www3.nhk.or.jp/nhkworld/en/ondemand/video/3004581/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www3.nhk.or.jp/nhkworld/en/ondemand/video/3004581/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, rtmpdump 2.4
[debug] Proxy map: {}
[NhkVod] 3004-581: Downloading JSON metadata
[Piksel] p0MjdqaDE6aSAVsRCNY5hpOxhjkcE3Wx: Downloading webpage
[Piksel] p0MjdqaDE6aSAVsRCNY5hpOxhjkcE3Wx: Downloading JSON metadata
[Piksel] p0MjdqaDE6aSAVsRCNY5hpOxhjkcE3Wx: Downloading JSON metadata
[Piksel] eb67a418: Downloading m3u8 information
[Piksel] eb67a418: Downloading SMIL file
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://mz-nhk10.mzpf.webcdn.stream.ne.jp/www60/mz-nhk10/media/mm/flvmedia/5905/m/F/m/mF_mp4file10249964-3714035.mp4?cid=5905&aid=3714035&afid=7841762&assetid=3714035'
[download] Destination: 10 Years with Hayao Miyazaki - Ep. 2 Drawing What's Real-eb67a418.mp4
[download]   1.1% of 1.43GiB at  1.72MiB/s ETA 14:00^C
```

```
curl -v 'http://mz-nhk10.mzpf.webcdn.stream.ne.jp/www60/mz-nhk10/media/mm/flvmedia/5905/m/F/m/mF_mp4file10
249964-3714035.mp4?cid=5905&aid=3714035&afid=7841762&assetid=3714035'
*   Trying 202.247.51.62...
* TCP_NODELAY set
* Connected to mz-nhk10.mzpf.webcdn.stream.ne.jp (202.247.51.62) port 80 (#0)
> GET /www60/mz-nhk10/media/mm/flvmedia/5905/m/F/m/mF_mp4file10249964-3714035.mp4?cid=5905&aid=3714035&afid=7841762&assetid=3714035 HTTP/1.1
> Host: mz-nhk10.mzpf.webcdn.stream.ne.jp
>
< HTTP/1.1 200 OK
< Date: Mon, 01 Feb 2021 12:33:31 GMT
< Content-Type: video/mp4
< Content-Length: 1530609664
< Connection: keep-alive
< Keep-Alive: timeout=3
< Last-Modified: Thu, 15 Aug 2019 06:12:11 GMT
< Via: JSTCDN
< X-Cache: HIT/S
< X-Cache-Age: 10/300
< X-Origin-Date: Mon, 01 Feb 2021 12:33:21 GMT
< Accept-Ranges: bytes
```

Given that the CDN is giving **Content-Length: 1530609664** I suspect some of the videos uploaded to there are corrupt. Hence not an issue with youtube-dl per se.

**Comment by fearlesschicken** [comment]
Hi, I recently ran into this and used this workaround.
It's very likely the best quality VOD is corrupt.  Instead, find out the next lower quality file with the -F flag and download after with the -f command.
In my case, the 1080p (best) quality was corrupt so I settled for the 720p file instead.

**Comment by kikuyan** [comment]
I happened to notice an update to this issue report, so I thought I'd mention it.

> also note the odd random numbers at the end of the filenename...

It's a video id and if you don't like the default filename, use `-o` option. Read [OUTPUT TEMPLATE](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#output-template).

**Comment by dirkf** [comment]
Continued in #30931.
