### ISSUE TITLE
how is it possible that video can be watched form the browser but can not be downloaded using youtube-dl

### ISSUE THREAD

**Issue by blueray453** [ytdl-org/youtube-dl#27991]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Trust me, just by looking at the sheer volume of issues, I would not create another one. 

But something is puzzling me for a long time now.

I am following [Tutorials: How can I download PluralSight training videos?](https://qr.ae/T9xdZJ)  to download videos from pluralsight. It works fine for sometime. But after a while it shows:

```
% youtube-dl --verbose --playlist-start 3
[debug] System config: ['--abort-on-error', '--no-warnings', '--console-title', '--batch-file=batch-file.txt', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.7113.93 Safari/537.36', '--cookies', '/home/blueray/Downloads/cookies.txt', '--socket-timeout', '20', '--retries', '10', '--continue', '--fragment-retries', '10', '--min-sleep-interval', '60', '--max-sleep-interval', '310', '--max-downloads', '350', '-f', 'best[height<=720]/worst[height>720]', '-o', '%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)d-%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--playlist-start', '3']
[debug] Batch file urls: ['https://app.pluralsight.com/library/courses/microsoft-azure-administrator-configure-name-resolution']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.8.5 (CPython) - Linux-5.8.0-40-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[pluralsight:course] running-business-information-security: Downloading JSON metadata
[download] Downloading playlist: Running the Business of Information Security
[pluralsight:course] playlist Running the Business of Information Security: Collected 33 video ids (downloading 17 of them)
[download] Downloading video 1 of 17
[pluralsight] 90d366fa-ae47-45cf-b04c-8a04f29d31c8-2: Downloading JSON metadata
[pluralsight] 90d366fa-ae47-45cf-b04c-8a04f29d31c8-2: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 90d366fa-ae47-45cf-b04c-8a04f29d31c8-2: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 90d366fa-ae47-45cf-b04c-8a04f29d31c8-2: Waiting for 4 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 421, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
When this error shows, I can still watch videos from the web browser, but I can no longer download video from that IP address. If I change my IP address using vpn, I can again start downloading the video.

So, they are somehow managing to stop downloading video from a particular IP though you can watch the video using the web browser. How is it possible? What can be done about that?

**Comment by blueray453** [comment]
I am attaching three firefox debugger tool output files. 

[console-export-when-not-blocked.txt](https://github.com/ytdl-org/youtube-dl/files/5887255/console-export-when-not-blocked.txt) is when I can both view using browser and download using youtube-dl.

[console-export-when-not-blocked-downloading.txt](https://github.com/ytdl-org/youtube-dl/files/5887256/console-export-when-not-blocked-downloading.txt) is when I can both view using browser and download using youtube-dl. But `Cross-Origin Request Blocked` shows up when the browser is open and I am downloading using `youtube-dl` in the terminal.

[console-export-when-blocked.txt](https://github.com/ytdl-org/youtube-dl/files/5887253/console-export-when-blocked.txt) is when the IP has been blocked. I can only view the video from web browser but can not download it.

**Comment by blueray453** [comment]
If any of the core contributors want, I can provide the following via email:

1. my VPN details &name of the server that is creating the problem
2. My login and password of pluralsight

**Comment by blueray453** [comment]
Try downloading using proton-vpn's NL-FREE#1 / NL-FREE#2. These are free servers.

**Comment by dirkf** [comment]
`[pluralsight] 90d366fa-ae47-45cf-b04c-8a04f29d31c8-2: Downloading mp4-high-widescreen viewclip graphql`
This failed, but this fallback succeeded:
`[pluralsight] 90d366fa-ae47-45cf-b04c-8a04f29d31c8-2: Downloading mp4-high-widescreen viewclip JSON`
Unfortunately it returned no video metadata, so you got `ERROR: No video formats found`.

Possibly the browser was sending extra HTTP headers that yt-dl doesn't, or using HTTP/2.

See #28384.
