### ISSUE TITLE
ERROR: Unable to download webpage: <urlopen error [WinError 10060] 

### ISSUE THREAD

**Issue by Angelique8023** [ytdl-org/youtube-dl#28000]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

error occurs when downloading videos from youtube ...
C:\Users\xxxxx>youtube-dl -i https://www.youtube.com/watch?v=QTOsfhPckYo&t=313s
[youtube] QTOsfhPckYo: Downloading webpage

**ERROR: Unable to download webpage: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond> (caused by URLError(TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None)))**

**Comment by dstftw** [comment]
Network issue on your side.

**Comment by Angelique8023** [comment]
> Network issue on your side.

I have vpn on, working fine. I can get access to youtube website. but cannot download video via pip command "youtube-dl"
