### ISSUE TITLE
record live streams with title and artist name metadata if available

### ISSUE THREAD

**Issue by Marc248** [ytdl-org/youtube-dl#28012]
## Description
There are channels with live streaming that indicate the metadata of currently playing song and artists. Example here:
https://www.youtube.com/watch?v=5yx6BWlEVcY
Can support be added so that this metadata can be used to save the live stream into separataed tracks using artista - track name suntax, instead a one large mixed track?

**Comment by remitamine** [comment]
no.

**Comment by Marc248** [comment]
Can you at least tell why not?

**Comment by remitamine** [comment]
the title and artist are shown only on the video stream/frames, not as textual metadata, this is not something that can be easily done, and it's out of the scope for youtube-dl.

**Comment by Marc248** [comment]
Ohh understood, thnaks for explaining.
