### ISSUE TITLE
Sound is distorted when downloading from twitch

### ISSUE THREAD

**Issue by kotyareg** [ytdl-org/youtube-dl#28044]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Sound is distorted when downloading live stream from twitch. There is no such problem when downloading a video from a twitch.

**Comment by EchoDev** [comment]
Duplicate https://github.com/ytdl-org/youtube-dl/issues/27296
