### ISSUE TITLE
[TF1] Broken support for some URLs

### ISSUE THREAD

**Issue by lizardrey** [ytdl-org/youtube-dl#28040]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tf1.fr/tf1/ninja-warrior/videos/ninja-warrior-le-parcours-des-heros-du-30-janvier-2021-partie-1-96067822.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.9.1 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[TF1] ninja-warrior-le-parcours-des-heros-du-30-janvier-2021-partie-1-96067822: Downloading webpage
[wat.tv] 13763567: Downloading JSON metadata
WARNING: [wat.tv] wat.tv returned error: Ce contenu n'est pas disponible pour l'instant.
[wat.tv] 13763567: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Unauthorized access. (caused by <HTTPError 403: 'Unauthorized access.'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2275, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description

Downloading from wat.tv [TF1] is broken for some URLs. The example shows `HTTP Error 403: Unauthorized acces`. The problem seems to affect only some URLs ([this one](https://www.tf1.fr/tf1/les-touristes/videos/les-touristes-mission-cascadeurs-56266325.html), for example works well).

**Comment by djmandell** [comment]
FWIW I've seen this error on several videos in the last week or two. I can post links to videos if you like.

**Comment by djmandell** [comment]
I've decided to leave another comment with one of the URLs that return this error:

https://www.tf1.fr/tf1/loup/videos/loup-le-loup-qui-voulait-offrir-une-pluie-detoiles-filantes-71248431.html

Please note, that video is only available for 1 week.  I'll come back and update with a new URL when that one expires.

**Comment by djmandell** [comment]
Still broken.  The url I posted last week is no longer available. Here's one that demonstrates the problem this week: https://www.tf1.fr/tf1/loup/videos/loup-le-loup-qui-voulait-faire-du-patin-a-glace-36442395.html

**Comment by adauguet** [comment]
Still have the same problem with the following url: https://www.tf1.fr/tf1/la-promesse/videos/la-promesse-episode-3-85079094.html
