### ISSUE TITLE
Support for full-length YouTube URLs

### ISSUE THREAD

**Issue by hussein-esmail7** [ytdl-org/youtube-dl#28055]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I was wondering if youtube-dl could support full YouTube URLs. For example, it supports `youtube-dl https://youtu.be/limrI_1IQBk` and `youtube-dl limrI_1IQBk`, but I was wondering if it's possible to support `youtube-dl https://www.youtube.com/watch?v=limrI_1IQBk`. In my opinion, I think it would be easier if people could copy the URL right from the URL bar of their browser to download a YouTube video. If there is a fix for this, please let me know. Thank you!

**Comment by dstftw** [comment]
youtube-dl supports any kind of input form mentioned.

**Comment by hussein-esmail7** [comment]
I am running the latest version and youtube-dl does not support `youtube-dl https://www.youtube.com/watch?v=limrI_1IQBk`. It tells me `zsh: no matches found: https://www.youtube.com/watch?v=limrI_1IQBk`

**Comment by dstftw** [comment]
`?` is a special character in `zsh` and mumst be escaped. Read doc on your shell.
