### ISSUE TITLE
svtplay.se no longer working!

### ISSUE THREAD

**Issue by EmmW** [ytdl-org/youtube-dl#28058]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.svtplay.se/video/29854214/hur-ar-hampus-i-sangen', '--all-subs', '--verbose', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.9.1 (CPython) - macOS-10.14.6-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 78.75.181.142 (SE) as X-Forwarded-For.
[SVTPlay] 29854214: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/svt.py", line 255, in _real_extract
    svt_id = self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2021.1.24.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
youtube-dl no longer works on svtplay-dl. I used it just the other day without problems, so the site must have been updated very recently to introduce new hurdles of some sort.

/Emm

**Comment by ijbh** [comment]
So three people have raised issues with this same site and all three have been closed. True, one was incomplete. But why was this closed? And why was mine closed because it was a duplicate if there are no other threads that are open?

**Comment by regagain** [comment]
This one's closed because it's fixed. :upside_down_face:

**Comment by ijbh** [comment]
> This one's closed because it's fixed. 🙃

Are you sure? I still get the same error message. How could it be fixed if either a) no one has written what parts of the code that needs to be changed or b) youtube-dl being updated with a new version?

**Comment by ijbh** [comment]
Apologies, I saw the link now. I will try that :)

**Comment by ijbh** [comment]
Oh I found the solution now. Thank you so much! That was so quick! :D

**Comment by EmmW** [comment]
Hi, I just ran the following Terminal command:

   sudo pip install --upgrade youtube_dl

...with the following result:

   Successfully installed youtube-dl-2021.2.4

However, when I then run the following (to check the version):

   youtube-dl --version

...I got the following result:

   2021.01.24.1

It seems that the update doesn't install properly and I'm still somehow stuck with the old version. Any tips on how to fix this? I am running Mac OSX 10.14.6 and have previously installed youtube-dl via homebrew -- thanks!

/Emm

Edit: I followed the general install instructions as per below (with the necessary adding of "-k" due to some issue with the certificate!) instead of using brew, and now it works! :-)

   sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl -k
   sudo chmod a+rx /usr/local/bin/youtube-dl

Thanks!

**Comment by rautamiekka** [comment]
You need to uninstall either one to avoid conflicts like this. I imagine Mac also has `which` command which'll tell what file `youtube-dl` points to.

I'd use the `pip` version since it's far easier to update, but of course you can create an `alias` or a script which'll run the
```bash
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl -k
```
command.

**Comment by paulspignon** [comment]
Had the same problem (with svtplay) Sorted with the pip-executed update, thanks
