### ISSUE TITLE
FFMPEG error when merging to webm

### ISSUE THREAD

**Issue by Timber1900** [ytdl-org/youtube-dl#28061]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.02.04**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo+bestaudio', '--merge-output-format', 'webm', '-o', './test.webm', 'https://www.youtube.com/watch?v=BaW_jenozKc', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.02.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 2021-02-02-git-2367affc2c-full_build-www.gyan.dev, ffprobe 2021-02-02-git-2367affc2c-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] BaW_jenozKc: Downloading webpage
[debug] Invoking downloader on 'https://r3---sn-2vgu0b5auxaxjvh-v2ve.googlevideo.com/videoplayback?expire=1612412852&ei=VCMbYMWDGcSNxN8PluG0gA8&ip=2001%3A8a0%3Ab96e%3A5301%3A79fd%3Ab3a%3Abe70%3Aa070&id=o-ADWiLVnvsGlbxlHiB4mrXPQgsLk8zvX0JqX8oikyko1X&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-2vgu0b5auxaxjvh-v2ve%2Csn-apn7en7e&ms=au%2Crdu&mv=m&mvi=3&pl=40&initcwndbps=955000&vprv=1&mime=video%2Fmp4&ns=zgOx27MjjQZqypYnxV_v7qcF&gir=yes&clen=2208750&dur=9.800&lmt=1387961822987808&mt=1612391091&fvip=3&keepalive=yes&c=WEB&n=y5plG45M7DjTf4Wvt&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgKi1-JyI4-wYSfzcnR1tFhiSqr22SjrA_j8xQtKu1IH0CIQC-jMZf9PtSEJCGATeDg3Wwv5CsaW2bx7-Dvvl56jNdPA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgTwTLSOUIGyPbsjmQfwqlwnqaMRAnCcZmb3QnjGhIRdYCIFKeNGNNffFoZDmi4btkKsRy_H-u2_1jy1XG8eclAJVt'
[download] Destination: test.webm.f137
[download] 100% of 2.11MiB in 00:00
[debug] Invoking downloader on 'https://r3---sn-2vgu0b5auxaxjvh-v2ve.googlevideo.com/videoplayback?expire=1612412852&ei=VCMbYMWDGcSNxN8PluG0gA8&ip=2001%3A8a0%3Ab96e%3A5301%3A79fd%3Ab3a%3Abe70%3Aa070&id=o-ADWiLVnvsGlbxlHiB4mrXPQgsLk8zvX0JqX8oikyko1X&itag=140&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-2vgu0b5auxaxjvh-v2ve%2Csn-apn7en7e&ms=au%2Crdu&mv=m&mvi=3&pl=40&initcwndbps=955000&vprv=1&mime=audio%2Fmp4&ns=zgOx27MjjQZqypYnxV_v7qcF&gir=yes&clen=157753&dur=9.891&lmt=1387961817989105&mt=1612391091&fvip=3&keepalive=yes&c=WEB&n=y5plG45M7DjTf4Wvt&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKl7Kc4M40Ehnrbt9K-XsMeZ0tyzq5gHXL145CW-i6RpAiEAisUT3rnn6yc0dbwWlmr9_RjOgIh0QlA8wf3zeIlAHzo%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgTwTLSOUIGyPbsjmQfwqlwnqaMRAnCcZmb3QnjGhIRdYCIFKeNGNNffFoZDmi4btkKsRy_H-u2_1jy1XG8eclAJVt'
[download] Destination: test.webm.f140
[download] 100% of 154.06KiB in 00:00
[ffmpeg] Merging formats into "test.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:test.webm.f137" -i "file:test.webm.f140" -c copy -map "0:v:0" -map "1:a:0" "file:test.temp.webm"
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2xgtxgc\build\youtube_dl\YoutubeDL.py", line 2102, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2xgtxgc\build\youtube_dl\postprocessor\ffmpeg.py", line 523, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2xgtxgc\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
```

## Description

Youtube-dl is erroring when attempting to merge video+audio to webm, I've tried different formats, updating ffmpeg/youtube-dl and the issue persists. <br /> I am aware that this might be a issue with ffmpeg and not youtube-dl however since I'm not sure I place this issue here. <br />This seems to be consistent with different videos as all that I've tried reproduce the same error

**Comment by joelmaxuel** [comment]
Not just webm, I've been experiencing the same problem with mp4. Please excuse the content name - I can redact - but this was the example that was logged for me via feed2exec.

> [ffmpeg] Merging formats into "/home/joel/Videos/Casts/Inbox/Cartoon Renewal Studios/20210313-The Mad Doctor Mickey Mouse 1933 restoration, remaster, COLORIZATION Cartoon Renewal Studios 2021-Dyq_TpvZLXM.mp4"
> ERROR:   Stream #1:0 -> #0:1 (copy)
> plugin generated exception: Command '['/home/joel/Videos/Casts/Inbox/.bin/youtube-dl', '--no-mtime', '-f', 'bestvideo[height<=1080]+bestaudio/best[height<=1080]', '--merge-output-format', 'mp4', '-o', '/home/joel/Videos/Casts/Inbox/Cartoon Renewal Studios/%(upload_date)s-%(title)s-%(id)s.%(ext)s', 'https://www.youtube.com/watch?v=Dyq_TpvZLXM']' returned non-zero exit status 1., skipping
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/feed2exec/plugins/__init__.py", line 105, in output
>     return plugin.output(*args, feed=feed, item=item, lock=lock)
>   File "/usr/lib/python3/dist-packages/feed2exec/plugins/exec.py", line 42, in output
>     return subprocess.check_call([command] + list(args))
>   File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['/home/joel/Videos/Casts/Inbox/.bin/youtube-dl', '--no-mtime', '-f', 'bestvideo[height<=1080]+bestaudio/best[height<=1080]', '--merge-output-format', 'mp4', '-o', '/home/joel/Videos/Casts/Inbox/Cartoon Renewal Studios/%(upload_date)s-%(title)s-%(id)s.%(ext)s', 'https://www.youtube.com/watch?v=Dyq_TpvZLXM']' returned non-zero exit status 1.
> 

Like the other times this occourred, I have been able to merge them directly with `ffmpeg`:

> $ffmpeg -i 20210313-The\ Mad\ Doctor\ Mickey\ Mouse\ 1933\ restoration\,\ remaster\,\ COLORIZATION\ Cartoo
> n\ Renewal\ Studios\ 2021-Dyq_TpvZLXM.f137.mp4 -i 20210313-The\ Mad\ Doctor\ Mickey\ Mouse\ 1933\ restoration\,\ remaster\,\ COLORIZATION\ Cartoon\ Renewal\ Studios\ 2021-Dyq_TpvZLXM.f251.we
> bm  -c:v copy -c:a aac 20210313-The\ Mad\ Doctor\ Mickey\ Mouse\ 1933\ restoration\,\ remaster\,\ COLORIZATION\ Cartoon\ Renewal\ Studios\ 2021-Dyq_TpvZLXM.mp4                              
> ffmpeg version 3.2.15-0+deb9u2 Copyright (c) 2000-2020 the FFmpeg developers
>   built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
>   configuration: --prefix=/usr --extra-version=0+deb9u2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enab
> le-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --
> enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse
> --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --ena
> ble-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libi
> ec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
>   libavutil      55. 34.101 / 55. 34.101
>   libavcodec     57. 64.101 / 57. 64.101
>   libavformat    57. 56.101 / 57. 56.101
>   libavdevice    57.  1.100 / 57.  1.100
>   libavfilter     6. 65.100 /  6. 65.100
>   libavresample   3.  1.  0 /  3.  1.  0
>   libswscale      4.  2.100 /  4.  2.100
>   libswresample   2.  3.100 /  2.  3.100
>   libpostproc    54.  1.100 / 54.  1.100
> 

... for some brevity ...

> Stream mapping:
>   Stream #0:0 -> #0:0 (copy)
>   Stream #1:0 -> #0:1 (opus (native) -> aac (native))
> Press [q] to stop, [?] for help
> frame= 9947 fps=203 q=-1.0 Lsize=  231086kB time=00:06:54.89 bitrate=4562.8kbits/s speed=8.47x                                                                                               
> video:224282kB audio:6571kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.101333%
> [aac @ 0x55d07cbd3ee0] Qavg: 964.518

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl/issues/27799#issuecomment-759361854

**Comment by joelmaxuel** [comment]
Does this mean that `--merge-output-format` is deprecated (or not to be used with `ffmpeg`)?

I have started using it because some YouTube videos were merging as webm with a codec that `omxplayer` will refuse. Looking at the current documentation (./youtube-dl --update; ./youtube-dl --help), there are no caveats regarding this option.

**Comment by pukkandan** [comment]
he's saying that you should use something like `-o ./test.%(ext)s` and not hardcode the filename as `test.webm`

**Comment by rautamiekka** [comment]
> he's saying that you should use something like `-o ./test.%(ext)s` and not hardcode the filename as `test.webm`

Yeah, never do that when supported.

**Comment by joelmaxuel** [comment]
...like I have, in my own detail of the issue I'm facing.

> -%(title)s-%(id)s.%(ext)s

I guess I'm confusing the situation by latching onto someone else's issue, when Timber and I did different things.

**Comment by pukkandan** [comment]
@remitamine was probably only replying to OP. You may want to open a new issue if this doesn't apply to you
