### ISSUE TITLE
[YouTube] Downloading Fail HTTP Error 404 - v2021.02.04

### ISSUE THREAD

**Issue by AJ-AllTheMods** [ytdl-org/youtube-dl#28070]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.02.04**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
D:\>youtube-dl.exe --verbose https://www.youtube.com/watch?v=yEKhl7qpDhE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=yEKhl7qpDhE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.02.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-02-02-git-2367affc2c-full_build-www.gyan.dev, ffprobe 2021-02-02-git-2367affc2c-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] yEKhl7qpDhE: Downloading webpage
[youtube] yEKhl7qpDhE: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r3---sn-aigl6nek.googlevideo.com/videoplayback?expire=1612425339&ei=G1QbYP7WJNGBmQbRyp6YCw&ip=195.206.183.132&id=o-AOZjMnUz27OAHzoXe2clZaBa8S5e4VvSM3LAMZxW3eqO&itag=247&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=yt_otf&requiressl=yes&mh=rq&mm=31%2C29&mn=sn-aigl6nek%2Csn-aigzrn7e&ms=au%2Crdu&mv=m&mvi=3&pl=22&initcwndbps=1966250&vprv=1&mime=video%2Fwebm&ns=q0jSWyWCBj3JNVF_BGt_H-IF&otf=1&otfp=1&dur=0.000&lmt=1612402792437892&mt=1612403115&fvip=3&keepalive=yes&c=WEB&txp=6210222&n=jnAGg7mJxh0Dq5GjS&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cotf%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRAIgN94CSarxmmXNskAy1QTQND3_Fqs1Fx_Cc8q6R3rDD08CIDfLtCNXCyhnTpq2B4KSoQX_19WeZzlstjuOUrwlzPX9&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAO05mCJjoyEBnDTK77maccWKTLM8JxZGtEwLg-L8wDMuAiAf7ol5Qp5EIsNoYCj993XrHwMluy3mKGgzKMLdbYHQ0A%3D%3D'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2xgtxgc\build\youtube_dl\YoutubeDL.py", line 1957, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2xgtxgc\build\youtube_dl\YoutubeDL.py", line 1902, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2xgtxgc\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2xgtxgc\build\youtube_dl\downloader\http.py", line 351, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2xgtxgc\build\youtube_dl\downloader\http.py", line 116, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2xgtxgc\build\youtube_dl\downloader\http.py", line 110, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2xgtxgc\build\youtube_dl\YoutubeDL.py", line 2275, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

## Description

This error seems to occur more often on newly uploaded videos, for example:

This works:
https://www.youtube.com/watch?v=DS3zCN4NsQY

This does not - (uploaded 12mins ago, randomly chosen):
https://www.youtube.com/watch?v=yEKhl7qpDhE

If I retrieve the formats for the "broken" video, I see the following:

########################################
[info] Available formats for yEKhl7qpDhE:
format code  extension  resolution note
139          m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.5 (22050Hz), 766.14KiB
251          webm       audio only tiny  104k , opus  (48000Hz), 1.60MiB
140          m4a        audio only tiny  129k , mp4a.40.2 (44100Hz), 1.98MiB
278          webm       256x144    144p   95k , vp9, 30fps, video only
160          mp4        256x144    144p  108k , avc1.4d400b, 30fps, video only
242          webm       426x240    240p  220k , vp9, 30fps, video only
133          mp4        426x240    240p  242k , avc1.4d400c, 30fps, video only
134          mp4        640x360    360p  313k , avc1.4d401e, 30fps, video only, 4.80MiB
243          webm       640x360    360p  405k , vp9, 30fps, video only
244          webm       854x480    480p  752k , vp9, 30fps, video only
135          mp4        854x480    480p 1155k , avc1.4d400b, 30fps, video only
136          mp4        1280x720   720p  900k , avc1.64001f, 30fps, video only, 13.78MiB
247          webm       1280x720   720p 1505k , vp9, 30fps, video only
18           mp4        640x360    360p  447k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 6.86MiB
22           mp4        1280x720   720p 1028k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
########################################

I have checked this issue is not present with version 2021.01.24.1

Here is the debug for v2021.01.24.1 when running against the "broken" video above:

########################################
D:\>youtube-dl.exe --verbose https://www.youtube.com/watch?v=yEKhl7qpDhE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=yEKhl7qpDhE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-02-02-git-2367affc2c-full_build-www.gyan.dev, ffprobe 2021-02-02-git-2367affc2c-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] yEKhl7qpDhE: Downloading webpage
[youtube] yEKhl7qpDhE: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1612427711/ei/X10bYOWtKMzB1wb4_4fQBw/ip/195.206.183.132/id/c842a197baa90e11/source/youtube/requiressl/yes/playback_host/r3---sn-aigl6nek.googlevideo.com/mh/rq/mm/31%2C29/mn/sn-aigl6nek%2Csn-aigzrn7e/ms/au%2Crdu/mv/m/mvi/3/pl/22/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/2070000/vprv/1/mt/1612404299/fvip/3/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRAIga99Pu9bK1zHMLvD_zudZJHbrU7aQRZyIxmmIeR5X2KsCIDB3kZFLemYDuTlxP8ARP9aOEapUa4eXRJchMkKcsm88/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIhAMc3j1LmR8sm1UgSAM8JSqr6---IBeaPxDyRokDXj1UUAiAGK9n0WyYSV7fuSvp7JlBUQWe8z_4zsfgJZZfxLvHi0Q%3D%3D'
[dashsegments] Total fragments: 25
[download] Destination: Asus Dual-GTX1060-O6G Gaming Nvidia GeForce Grafikkarte (PCIe 3.0, 6GB GDDR5 Speicher, HDMI, DV...-yEKhl7qpDhE.f136.mp4
[download]  48.0% of ~16.85MiB at  6.84MiB/s ETA 00:03
ERROR: Interrupted by user
########################################

The download URLs are different between the 2 ytdl versions

**Comment by chrisr11** [comment]
I can confirm that I'm having this issue, especially with playlists. It works fine with 2021.01.24.1 but not with the latest release.

**Comment by october262** [comment]
for this video - https://www.youtube.com/watch?v=yEKhl7qpDhE 
retry with youtube-dl -f mp4 https://www.youtube.com/watch?v=yEKhl7qpDhE

**Comment by antdude** [comment]
Thank you fixing and releasing this! I was wondering why https://www.youtube.com/watch?v=FfnEoVoW64s was giving me 404 error.

**Comment by chrisr11** [comment]
> Thank you fixing and releasing this! I was wondering why https://www.youtube.com/watch?v=FfnEoVoW64s was giving me 404 error.

The new release fixes it?

**Comment by antdude** [comment]
@chrisr11 It did for me!

**Comment by Metichi** [comment]
Im having a similar issue on a vimeo playlist with version 2021.02.10 on Ubuntu
