### ISSUE TITLE
Youtube-dl not allowing download of any videos on youtube, even educational videos

### ISSUE THREAD

**Issue by JPI-Tech** [ytdl-org/youtube-dl#28077]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.02.04.1**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by adrianheine** [comment]
Please read up on how to report bugs in general and specifically for youtube-dl! You should at least post exactly what you ran (with `-v` for verbose output) and the complete output.
