### ISSUE TITLE
how to download from olympus great learning

### ISSUE THREAD

**Issue by sandyshrv24** [ytdl-org/youtube-dl#28082]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
https://www.mygreatlearning.com/us/?arz=1

how to download from the above site using youtube-dl?

**Comment by remitamine** [comment]
fill the proper issue template.
