### ISSUE TITLE
Discovery+ credentials needed for devs?

### ISSUE THREAD

**Issue by EliteAppleHacks** [ytdl-org/youtube-dl#28081]
## Checklist

- [X ] I'm reporting a site feature request
- [ X] I've verified that I'm running youtube-dl version **2021.02.04.1**
- [X ] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Does any dev need credentials to support Discovery+? I would like support for it since i have the 7 day free trial. Ends in 5 days

**Comment by remitamine** [comment]
if it's about support for discoveryplus.com then you should comment on the already open issue.
