### ISSUE TITLE
ERROR: No video formats found in https://www.ceskatelevize.cz/porady/899553-vysila-studio-a/26653132075/ 

### ISSUE THREAD

**Issue by barbuch** [ytdl-org/youtube-dl#28085]
Video url: "https://www.ceskatelevize.cz/porady/899553-vysila-studio-a/26653132075/" 
The video is possible to playback, but not to download. When trying to download, ERROR: "No video formats found" occurs.
The same problem detected recent time quite frequently on the web "https://www.ceskatelevize.cz/", but not always.

**Comment by Mennaruuk** [comment]
Even after opening the embedded video's iFrame in a new tab, and copying that URL, the same error shows up.
