### ISSUE TITLE
File Naming issues

### ISSUE THREAD

**Issue by mangus580** [ytdl-org/youtube-dl#28098]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Having an issue downloading a youtube playlist.

Trying to name the files so that the directory they reside in is named via the playlist_title - and I still get the playlist_id as the name.

Is this a known issue, I didnt see anything about it when I searched for it.

**Comment by mangus580** [comment]
Gee, thanks for the help.  So welcoming when a new user comes and asks a question, to just close it as incomplete.  What more information do you want?  I am trying to download a playlist into a directory using the play list title for the directory name.

When I use the playlist_title for the naming option, it still uses playlist_id.  This is using youtube.  It is either a bug, a flaw with youtube, or I am doing something wrong.  Ignoring my issue does not solve anything for anyone.

**Comment by dstftw** [comment]
Read new issue template and fill in the correct section.

**Comment by mangus580** [comment]
So helpful - I used the 'template' for asking a question - I checked off the checklist, I asked my question where it said to ask a question.  So glad that we can waste time arguing about using a stupid template instead of answering my qeustion.

Such a useful waste of everyone's time.  I have NEVER in all my years of asking for help on the internet, been treated so poorly.  

What a welcoming group this is.....

**Comment by mangus580** [comment]
Below is the template that came up when I chose 'ask a question' - how am I not following it?????

> ## Checklist



- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones


## Question



WRITE QUESTION HERE
