### ISSUE TITLE
batch downloading not working

### ISSUE THREAD

**Issue by snorkack71** [ytdl-org/youtube-dl#28108]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.02.04.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
fred@ragnok:~/watch$ ./batch-dl
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--restrict-filenames', '--batch-file', './watch_list']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=v0E92lYbr9Qcd']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.17
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-12-686-pae-i686-with-debian-10.0
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] v0E92lYbr9Q: Downloading webpage
[youtube] v0E92lYbr9Q: Downloading video info webpage
ERROR: v0E92lYbr9Q: YouTube said: Invalid parameters.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1688, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: v0E92lYbr9Q: YouTube said: Invalid parameters.



```

## Description

WRITE DESCRIPTION HERE
Because of slow internet connection I need to download with at -f ./batch-dl 2:00am.
The download fails with youtube reporting invalid parameters.  I ran the script manually to get the provided debug output.
If youtube-dl is run from the command line with the provided URL it downloads ok.
Devuan Beowulf AMD64 Linux

The script:  batch-dl
#!/bin/sh
/usr/bin/youtube-dl -v --restrict-filenames --batch-file ./watch_list

The batch file:  watch_list
https://www.youtube.com/watch?v=v0E92lYbr9Qcd
#and maybe more URLs here

**Comment by snorkack71** [comment]
It isn't an outdated version.  It is the version 2021.02.04.1 listed in your checklist as the current version.  Don't I at least get an explanation?

**Comment by rautamiekka** [comment]
> It isn't an outdated version. It is the version 2021.02.04.1 listed in your checklist as the current version. Don't I at least get an explanation?

Hint: try reading the lines starting with `[debug]`. Yours is very old.

**Comment by snorkack71** [comment]
It turns out that there are two versions installed.
fred@ragnok:~$ youtube-dl --version
2021.02.04.1
fred@ragnok:~$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/games
fred@ragnok:~$ ls /usr/local/bin/youtube-dl
/usr/local/bin/youtube-dl
fred@ragnok:~$ /usr/local/bin/youtube-dl --version
2021.02.04.1

fred@ragnok:~$ whereis youtube-dl
youtube-dl: /usr/bin/youtube-dl /usr/local/bin/youtube-dl /usr/share/man/man1/youtube-dl.1.gz
fred@ragnok:~$ /usr/bin/youtube-dl --version
2019.01.17

I don't know why the script picked the old one but I will remove it.

Thanks for the help.
