### ISSUE TITLE
Is there any way to bypass the correcting container?

### ISSUE THREAD

**Issue by mrl24730** [ytdl-org/youtube-dl#28107]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm using `youtube-dl` to download a `m4a` audio, the playlist format is `manifest.mpd`, everything is working properly, expect once the download process is completed and going to the **_correcting container_** process, the file size change from `36MB` to `1KB`. 

I've tried copy the download file at 80% and rename the file extension to `m4a`, it 's playable and not corrupted. Is there any way to bypass the correcting container, so that I can have a 100% file?

**Comment by dstftw** [comment]
Post verbose log.
