### ISSUE TITLE
Issue with -f bestvideo[ext!=webm]+bestaudio[ext!=webm]

### ISSUE THREAD

**Issue by Dyr-Fenrir** [ytdl-org/youtube-dl#28103]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Greetings,

I was trying to get the following video from YouTube: "https://www.youtube.com/watch?v=7-bkJ2ZoW6k" and I used the command "youtube-dl.exe -F https://www.youtube.com/watch?v=7-bkJ2ZoW6k" to get what formats were available.

Here are the results:

[info] Available formats for 7-bkJ2ZoW6k:
format code  extension  resolution note
249          webm       audio only tiny   49k , opus @ 50k (48000Hz), 1.01MiB
250          webm       audio only tiny   65k , opus @ 70k (48000Hz), 1.33MiB
251          webm       audio only tiny  127k , opus @160k (48000Hz), 2.65MiB
140          m4a        audio only tiny  130k , m4a_dash container, mp4a.40.2@128k (44100Hz), 2.86MiB
160          mp4        256x144    144p  134k , avc1.4d400c, 30fps, video only, 2.19MiB
278          webm       256x144    144p  143k , webm container, vp9, 30fps, video only, 2.04MiB
242          webm       426x240    240p  284k , vp9, 30fps, video only, 4.19MiB
133          mp4        426x240    240p  294k , avc1.4d4015, 30fps, video only, 4.89MiB
243          webm       640x360    360p  556k , vp9, 30fps, video only, 7.53MiB
134          mp4        640x360    360p  633k , avc1.4d401e, 30fps, video only, 10.44MiB
244          webm       854x480    480p  961k , vp9, 30fps, video only, 13.54MiB
135          mp4        854x480    480p 1183k , avc1.4d401f, 30fps, video only, 19.95MiB
247          webm       1280x720   720p 2228k , vp9, 30fps, video only, 27.21MiB
136          mp4        1280x720   720p 2287k , avc1.64001f, 30fps, video only, 39.86MiB
248          webm       1920x1080  1080p 3521k , vp9, 30fps, video only, 44.34MiB
137          mp4        1920x1080  1080p 4913k , avc1.640028, 30fps, video only, 82.28MiB
271          webm       2560x1440  1440p 8588k , vp9, 30fps, video only, 134.02MiB
18           mp4        640x360    360p  592k , avc1.42001E, 30fps, mp4a.40.2@ 96k (44100Hz), 13.08MiB
22           mp4        1280x720   720p 1934k , avc1.64001F, 30fps, mp4a.40.2@192k (44100Hz) (best)

I always aim to get the best video and audio and then merge them, so I use the following command to download the video: "youtube-dl.exe https://www.youtube.com/watch?v=7-bkJ2ZoW6k -f bestvideo[ext!=webm]+bestaudio[ext!=webm]"

The video was download 1920x1080 instead of 2560x1440 and I am confused as to why...

The only reason I could think of was that the download was made using the highest .MP4 format, which seems to fit with file size even if I asked for .WEBM.

May someone help me out with this problem/issue please?

Thank you for your time and help, it is greatly appreciated.

**Comment by s104346** [comment]
`[ext!=webm]` selects formats where the filename extension does **not** equal `webm`.
You probably want `[ext=webm]`.

**Comment by Dyr-Fenrir** [comment]
Thanks a lot, this is my mistake, really sorry about that, I should have noticed it.
