### ISSUE TITLE
Produces a broken mpeg file: [ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found

### ISSUE THREAD

**Issue by yurivict** [ytdl-org/youtube-dl#28111]
## Checklist

youtube-dl-2021.02.04.1
FreeBSD 12.2

## Description

```
$ youtube-dl https://www.youtube.com/watch?v=QOjmvL3e7Lc
```
Ctrl-C once sufficient amount of video is downloaded
```

$ mpv Tokyo\ Live\ Camera\ Ch1\ \[4K\]\ 東京\ 汐留\ 鉄道\ ライブカメラ\ 2021-02-07\ 15_22-QOjmvL3e7Lc.mp4 
Warning: option --sub-paths was replaced with --sub-file-paths and might be removed in the future.
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
[lavf] avformat_open_input() failed
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
[lavf] avformat_open_input() failed
Failed to recognize file format.
```

mpv says that this is youtube-dl's fault: https://github.com/mpv-player/mpv/issues/8540

**Comment by yurivict** [comment]
youtube-dl is broken.

**Comment by bitraid** [comment]
Try updating ffmpeg.

**Comment by yurivict** [comment]
My ffmpeg is at 4.3.1 - the latest released version. https://ffmpeg.org/download.html#releases

**Comment by bitraid** [comment]
You should provide the full logs as requested (that's why your issues are closed), otherwise we can only guess.
When you break with `CTRL-C`, does the program end with something like:
```
Exiting normally, received signal 2.
[ffmpeg] Interrupted by user
[ffmpeg] Downloaded 3736748 bytes
[download] 100% of 3.56MiB in 00:08
```
