### ISSUE TITLE
--get-channel similar to --get-id and --get-duration

### ISSUE THREAD

**Issue by hussein-esmail7** [ytdl-org/youtube-dl#28122]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2021.02.04.1**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I'm wondering if it's possible to add this feature:
There already exists --get-id and --get-duration command, but would it be possible to add --get-channel to get the channel name? And even after, maybe --get-channel-id for the (you guessed it) channel ID.

**Comment by dstftw** [comment]
Parse `--dump-json`.
