### ISSUE TITLE
using -s -a option can lead to "indefinite" output

### ISSUE THREAD

**Issue by churoll** [ytdl-org/youtube-dl#28120]
- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.02.04.1**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
C:\Users\emcodem>"C:\dev\FFAStrans\FFAStrans\processors\FFmpeg\youtube-dl.exe" -v -s -a c:\temp\yt.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-s', '-a', 'c:\\temp\\yt.txt']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=iGh6ONUhyec&list=UUD-4g5w1h8xQpLaNS_ghU4g&index=10']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] Downloading playlist UUD-4g5w1h8xQpLaNS_ghU4g - add --no-playlist to just download video iGh6ONUhyec
[youtube:tab] UUD-4g5w1h8xQpLaNS_ghU4g: Downloading webpage
[youtube:tab] UUD-4g5w1h8xQpLaNS_ghU4g: Downloading webpage
[download] Downloading playlist: Uploads from NewRetroWave
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] Downloading page 3
[youtube:tab] Downloading page 4
[youtube:tab] Downloading page 5
[youtube:tab] Downloading page 6
[youtube:tab] Downloading page 7
[youtube:tab] Downloading page 8

## Description
Above will run forever. When specifying the input URL directly and therefore omitting -a we get the expected result

**Comment by dstftw** [comment]
And won't run forever, it will run until it browses all pages of this 2378 videos playlist.

**Comment by churoll** [comment]
Uhm ok but why does it make such a huge difference between providing the url on comandline VS using -a

**Comment by dstftw** [comment]
It does not make any difference.

**Comment by churoll** [comment]
Sorry, maybe i didnt make myself clear enough
This works:
"C:\dev\FFAStrans\FFAStrans\processors\FFmpeg\youtube-dl.exe" -v -s https://www.youtube.com/watch?v=iGh6ONUhyec&list=UUD-4g5w1h8xQpLaNS_ghU4g&index=10

While writint the exact url into a txt file an use -a option parses the whole playlist

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command

**Comment by churoll** [comment]
Uff, ok i understand that the commandline ignores the & parameter and that i should have recognized that. But why the hell does &index=10 imply for youtueb-dl that it needs to download the full playlist while the same video plays regardless of the &index parmeter? 
Is there some kind of usage guide for this?
