### ISSUE TITLE
Extracting direct download url from video URL in python script ?

### ISSUE THREAD

**Issue by phantom2152** [ytdl-org/youtube-dl#28133]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

YouTube-dl gives the direct download link of a given url by including --get-url parameter in the command line interface. But I wanted to know that is there a way to get the download link in a python script without using os modle (not only for youtube but for the all the sites supported by youtube-dl)

**Comment by dstftw** [comment]
`YoutubeDL.extract_info`, parse formats from JSON.
