### ISSUE TITLE
Some format disappeared with the last update v2021.02.10

### ISSUE THREAD

**Issue by nastia-diaphan** [ytdl-org/youtube-dl#28136]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.02.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
a sample

2020-08-31 12:49:50
139 - audio only (DASH audio) m4a None
251 - audio only (DASH audio) webm None
140 - audio only (DASH audio) m4a None
278 - 192x144 (DASH video) webm None
160 - 192x144 (DASH video) mp4 None
242 - 320x240 (DASH video) webm None
133 - 320x240 (DASH video) mp4 None
243 - 480x360 (DASH video) webm None
134 - 480x360 (DASH video) mp4 None
244 - 640x480 (DASH video) webm None
135 - 640x480 (DASH video) mp4 None
18 - 480x360 (360p) mp4 2266046

and now
2021-02-11 00:04:13
251 - audio only (tiny) webm 509474
140 - audio only (tiny) m4a 602709
134 - 480x360 (360p) mp4 1324271
18 - 480x360 (360p) mp4 2266046

```

## Description

Is there an easy wait to downgrade with pip ?

**Comment by rautamiekka** [comment]
> Is there an easy wait to downgrade with pip ?

Nope. You need the earlier version, then run:
```
pip install "youtube_dl==2021.2.4.1"
```
