### ISSUE TITLE
YouTube Channel extraction isn't working

### ISSUE THREAD

**Issue by sdan41517** [ytdl-org/youtube-dl#28137]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.02.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-J', u'--flat-playlist', u'https://www.youtube.com/c/TechLead']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.02.10
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-132-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
{"extractor": "youtube:tab", "_type": "playlist", "description": "Ex-Google/ex-Facebook tech lead, multi-millionaire app entrepreneur, digital nomad traveler, software engineer. \u2615\ufe0f \ud83d\udc4c\n\nIf you're looking for help landing a job as a software engineer, resume critique, and mentorship, join me at:\nhttp://techinterviewpro.com/\nhttp://coderpro.com/\n\nLearn the secrets of YouTube success with me here:\nhttp://youtubebackstage.com/\n\nAdd me here:\nhttp://instagram.com/techleadhd\nhttp://twitter.com/techleadhd\nhttps://www.linkedin.com/in/patrickshyu/\n\nBusiness Inquiries: techleadhd@gmail.com", "title": "TechLead - Home", "extractor_key": "YoutubeTab", "webpage_url": "https://www.youtube.com/c/TechLead", "entries": [{"url": "https://www.youtube.com/c/TechLead/videos?view=0&sort=dd&shelf_id=1", "_type": "url", "ie_key": null, "title": "Uploads"}, {"url": "https://www.youtube.com/c/TechLead/videos?view=0&sort=p&shelf_id=2", "_type": "url", "ie_key": null, "title": "Popular uploads"}], "id": "UC4xKdmAXFh4ACyhpiQ_3qBw", "webpage_url_basename": "TechLead"}
```

## Description

Hi, youtube-dl is not getting the JSON info for channels. This used to work before but now it just gets the playlists of the channel and not the list of videos. Here's a sample link:

https://www.youtube.com/c/TechLead

It only fetches the 2 playlists in the channel and not the entire videos list. It used to work using --flat-playlist but now it doesn't. Has something changed?

**Comment by llacb47** [comment]
Use `youtube.com/c/TechLead/videos` and close the issue.

**Comment by seanpm2001** [comment]
I would like to jump on this before it is closed: I have been having a similar issue for several months. Ever since YouTube-dl got restored from the RIAA takedown, I have been able to download videos again, but I can't seem to download playlists or channels anymore, for playlists, it will just download the first video and stop, and for channels it won't do anything at all. I am also using version 2021.02.10.

**Comment by dstftw** [comment]
It downloads exactly what's located on the link's webpage. As already noted above, to download all videos pass videos URL.

**Comment by seanpm2001** [comment]
This didn't help at all
