### ISSUE TITLE
No entries in the playlist

### ISSUE THREAD

**Issue by maxim563328** [ytdl-org/youtube-dl#28140]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Good time of day, I ran into a problem, using the search I find an empty playlist called 'корова' (I'm from Russia), which is why I can't get a link to the video.
`YDL_OPTIONS = {'format': 'worstaudio/worst',
               'simulate': 'True',
               'preferredquality': '192',
               'preferredcodec': 'mp3',
               'extractor_key': 'FFmpegExtractAudio',
               'default_search': 'auto',
               'no_warnings': True,
               'ignoreerrors': False,
               # 'flat-playlist': True,
               'nocheckcertificate': True,
               'noplaylist': True
               }`

`with YoutubeDL(YDL_OPTIONS) as ydl:
    info = ydl.extract_info(f"ytsearch:{arg}", download=False)['entries'][0]` #Next, I need to get a link to the video, but I can't do it, because [entries] contains 0 elements

`[download] Downloading playlist: корова
[youtube:search] query "корова": Downloading page 1
[youtube:search] playlist корова: Downloading 0 videos
[download] Finished downloading playlist: корова
Ignoring exception in command msPlay:
Traceback (most recent call last):
  File "C:\Users\Maxim\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Maxim\Desktop\Umaru Боты\UmaruBotDiscord\helper.py", line 756, in msPlay
    info = ydl.extract_info(f"ytsearch:{arg}", download=False)[
IndexError: list index out of range`

**Comment by dstftw** [comment]
Post verbose output.

**Comment by maxim563328** [comment]
![image](https://user-images.githubusercontent.com/56736526/107654320-232d8c00-6cb5-11eb-9825-05570c6133e9.png)
![image](https://user-images.githubusercontent.com/56736526/107654413-39d3e300-6cb5-11eb-9fdb-4b3a48b25289.png)
