### ISSUE TITLE
What is the video quality selected when use option -x --audio-format mp3 ?

### ISSUE THREAD

**Issue by AYMEN-DEV** [ytdl-org/youtube-dl#28167]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
-
What is the video quality selected when i use option -x --audio-format mp3 ?

and if i want the same video that downloaded in -x --audio-format mp3 , option without converting it to mp3 what command i should use ? .

**Comment by remitamine** [comment]
`-x --audio-format mp3` does not affect format selection.
