### ISSUE TITLE
Passing directory separator in -o value causes error "Error in output template: unsupported format character"

### ISSUE THREAD

**Issue by jtmoon79** [ytdl-org/youtube-dl#28164]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.02.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PS C:\Users\User1> youtube-dl.exe --version
2021.02.10

PS C:\Users\User1> youtube-dl.exe -v -f 134 "https://www.youtube.com/watch?v=L_xrDAtykMI" -o "%(playlist_title)\\%(uploader)s - %(upload_date)s - %(title).200s.%(ext)s"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '134', 'https://www.youtube.com/watch?v=L_xrDAtykMI', '-o', '%(playlist_title)\\\\%(uploader)s - %(upload_date)s - %(title).200s.%(ext)s']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref cp65001
[debug] youtube-dl version 2021.02.10
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-03-11-36aaee2, ffprobe git-2020-03-11-36aaee2
[debug] Proxy map: {}
[youtube] L_xrDAtykMI: Downloading webpage
ERROR: Error in output template: unsupported format character '\' (0x5c) at index 17 (encoding: 'cp65001')
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym44\build\youtube_dl\YoutubeDL.py", line 714, in prepare_filename
ValueError: unsupported format character '\' (0x5c) at index 17
```

The same error occurs for `-o` values `"a/b"`, `"a//b"`, `"a\b"`, `"a\\b"`.

Using Powershell 7 on Windows 10 Pro.

Also, path `C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym44\build\youtube_dl\YoutubeDL.py` does not exist on the host. This is probably benign.

## Description

[The `README.md` reads](https://github.com/ytdl-org/youtube-dl/blob/2021.02.10/README.md)

> Output templates can also contain arbitrary hierarchical path, e.g. `-o '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s'` which will result in downloading each video in a directory corresponding to this path template. Any missing directory will be automatically created for you.

This fails with error message `ERROR: Error in output template: unsupported format character ...`.

**Comment by dstftw** [comment]
Missing `s` in `%(playlist_title)`.

**Comment by jtmoon79** [comment]
Yep.  🤦
