### ISSUE TITLE
Installition error - The path in manual installation is wrong

### ISSUE THREAD

**Issue by bakharzy** [ytdl-org/youtube-dl#28179]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.02.10**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
Description would be enough. It happens when installing. 
```

## Description

WRITE DESCRIPTION HERE
The issue is with the link of the installation. I used the curl command for installation as below:
`sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl`
`sudo chmod a+rx /usr/local/bin/youtube-dl`

When using the youtube-dl like:
`youtube-dl https://www.youtube.com/watch?v=something`
I received this message: 

> -bash: **/usr/bin/youtube-dl:** No such file or directory

So I changed the curl path to below and it works now:
`sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/bin/youtube-dl`

Curl should download the latest code to this path "/usr/local/bin/youtube-dl".

**Comment by rautamiekka** [comment]
Diff distro types and even distros within the type want their shit in diff places. IIRC 1 of the devs use Arch Linux, which wants its shit elsewhere than Ubuntu.

**Comment by bakharzy** [comment]
Thanks for the comment. So did I do right by changing the path? 
Btw, I should have mentioned this before. My distro is: Ubuntu 20.04.2 LTS
