### ISSUE TITLE
[Feature Request] Flag To Automatically Place Files In Subfolders

### ISSUE THREAD

**Issue by grravity** [ytdl-org/youtube-dl#28186]
Requesting the ability for Youtube-dl to automatically place files in subfolders.
For example, if I download a playlist of 300 videos, it downloads video.mkv and thumbnail, then goes onto the next. Instead of just moving on, it would create then move the file to a subdirectory titled the same as the file itself root/video/video.mkv, thumb.jpg.

Otherwise it just dumps all 300 videos + thumbnails (so 600 files) into the root directory (where you download). You then have to manually go make the subfolders which is EXTREMELY tedious manually. Maybe there's an automated way to do it, or a shell script, but it would be amazing to have this built in as a simple flag.

**Comment by dstftw** [comment]
Read FAQ on output template.
