### ISSUE TITLE
How can i disable error logging?

### ISSUE THREAD

**Issue by Laky-64** [ytdl-org/youtube-dl#28180]
I'm using the python import version, i need to disable this messages like no-warnings parametres
![image](https://user-images.githubusercontent.com/35636667/108106093-cb649b80-708d-11eb-9313-a18a994c99f1.png)

**Comment by pukkandan** [comment]
If you want to disable both warnings and errors, you can just not write `stderr` to terminal. I don't think there is an inbuilt way to block just the errors
