### ISSUE TITLE
no matroska file despite --merge-output-format mkv

### ISSUE THREAD

**Issue by tomasmueller** [ytdl-org/youtube-dl#28191]
i use this command line to download videos from a playlist

`/home/pi/bin/youtube-dl -o '%(channel_id)s--%(upload_date)s--%(title)s.%(ext)s' --download-archive archive.txt url`

this is the config file i use in ~/.config/youtube-dl/config

```
-f 'bestvideo[height<=720,ext=av01]+bestaudio[ext=m4a]/best'
--merge-output-format mkv
#--restrict-filenames
```

as you can see i've commented out --restrict-filenames because this deletes the german umlauts in the video title. Now the videos are saved as mp4 and not as mkv. What is the problem here? when i delete the # it works.

**Comment by dstftw** [comment]
Invalid format selection expression resulting in fallback to `best` that does not involve merging.
