### ISSUE TITLE
which parameters should be used to avoid skipping?

### ISSUE THREAD

**Issue by Albretch** [ytdl-org/youtube-dl#28222]
## Checklist

- [x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

 github.com/rg3/youtube-dl/issues:lbrtchx:lbrtchx@gmail.com:pAxW0rdZ:

 I have found in my youtube-dl logs one liners such as:
 
 "[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment"
 "[download] Skipping fragment ..."
 
 It would be best if no fragments are skipped. If for whatever reason the media file can't be downloaded, then the download at once should be skipped and I would try some other time. So, there should be a maximum number of trials otherwise the download should be abborted altogether.

 How do you do that?
 
 lbrtchx

**Comment by remitamine** [comment]
```
--abort-on-unavailable-fragment      Abort downloading when some fragment is
                                     not available
```
