### ISSUE TITLE
Soundboard, 101Soundboards, Myinstants support

### ISSUE THREAD

**Issue by BrandonKMLee** [ytdl-org/youtube-dl#28224]
## Checklist
- [v] I'm reporting a new site support request
- [v] I've verified that I'm running youtube-dl version **2021.02.10**
- [v] I've checked that all provided URLs are alive and playable in a browser
- [v] I've checked that none of provided URLs violate any copyrights
- [v] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs
- Soundboard https://www.soundboard.com/sb/Deer_Sounds_audio
- 101 Soundboards https://www.101soundboards.com/boards/21617-ultimate-fart-soundboard
- MyInstants https://www.myinstants.com

## Description

These are websites that contain short audio clips for sound effect purposes

Usable applications include
- https://github.com/gamebooster/soundboard
- https://github.com/Soundux/Soundux/issues/47
- https://github.com/ruohki/lunchpad

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#does-the-issue-involve-one-problem-and-one-problem-only
