### ISSUE TITLE
issues ith fragments ...

### ISSUE THREAD

**Issue by Albretch** [ytdl-org/youtube-dl#28232]
## Checklist

- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

 I couldn't find my previous question about fragments. It as suggested to me to use: --abort-on-unavailable-fragment
but this is not exactly hat my question as about. shouldn't there be an option accompanying that one specifying after how many unsuccessful attempts?
 You, could drop the download after, say, 5 attempts. How could you do that?

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#download-options

**Comment by Albretch** [comment]
OK, then, it should be: --abort-on-unavailable-fragment-after-retries
