### ISSUE TITLE
Multiple videos downloaded parallelly?

### ISSUE THREAD

**Issue by Sinha-Ujjawal** [ytdl-org/youtube-dl#28236]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Are multiple videos downloaded parallelly?

**Comment by remitamine** [comment]
no.

**Comment by Sinha-Ujjawal** [comment]
Will it be better if we download files in parallel. Will it be any faster/ better? Sorry, I appologize for my incomplete knowledge.

**Comment by remitamine** [comment]
> Will it be any faster/ better?

depends on whether the bandwidth is saturated or not.

**Comment by Sinha-Ujjawal** [comment]
Interesting... thx
