### ISSUE TITLE
srv3 to .ass

### ISSUE THREAD

**Issue by gimmeAll** [ytdl-org/youtube-dl#28242]
there is a software that does this, but it would be nice if youtube-dl had support for converting srv3 to .ass, as .ass is supported by most video container players. Here is the software:
https://github.com/arcusmaximus/YTSubConverter

**Comment by dstftw** [comment]
Youtube serves vtt that can be converted to ass.

**Comment by bagusnl** [comment]
Some styling format is not displayed on VTT like font size and subtitle window coloring. It only available in srv3, which that software can convert it to ass almost perfectly.

**Comment by bagusnl** [comment]
Managed to get it working with a batch file
my script looks like this
`youtube-dl -f bestvideo[vcodec!*=av01]+bestaudio --console-title --socket-timeout 20 --buffer-size 16K -R infinite --proxy "" --mark-watched --geo-bypass --no-playlist --write-sub --all-subs --sub-format vtt --embed-subs --write-thumbnail --add-metadata --merge-output-format mkv -v %url%

youtube-dl -v --proxy "" --geo-bypass --skip-download --no-playlist --write-sub --sub-lang en,en-US,en-GB,ja,jp,id --sub-format srv3 %url%
for /r %%v in (*.srv) do YTSubConverter "%%v" --visual`

The first line is to download the video while embedding vtt subtitle as redundancy while the second and third line download the srv3 subtitle files (languages is your choice) and then convert it
