### ISSUE TITLE
Problem with Francetv 

### ISSUE THREAD

**Issue by campones** [ytdl-org/youtube-dl#28248]
Hello

Since today I m facing an issue when trying to dl from francetv website.

youtube-dl -vv https://www.france.tv/france-5/c-dans-l-air/2264763-emission-du-samedi-20-fevrier-2021.html -F
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vv', u'https://www.france.tv/france-5/c-dans-l-air/2264763-emission-du-samedi-20-fevrier-2021.html', u'-F']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.02.22
[debug] Python version 2.7.6 (CPython) - Linux-3.13.0-170-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-76159-gda43e9e, ffprobe N-76159-gda43e9e, rtmpdump 2.4
[debug] Proxy map: {}
[FranceTVSite] 2264763-emission-du-samedi-20-fevrier-2021: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error> (caused by URLError(SSLError(1, '_ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2275, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2736, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)

it's working fine on my windows despite the youtube-dl is older than on my server. On the other hand my server install is pretty old now, ubuntu 14.04 trusty from 2015

**Comment by dstftw** [comment]
Update python.

**Comment by campones** [comment]
Ok. not so easy actually to do .

weird think is it still works using streamlink

streamlink  -o cdanslair.mp4 https://www.france.tv/france-5/c-dans-l-air/2264763-emission-du-samedi-20-fevrier-2021.html best
/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,
/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. The next version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin pluzz for URL https://www.france.tv/france-5/c-dans-l-air/2264763-emission-du-samedi-20-fevrier-2021.html
[cli][info] Available streams: 216p_hls, 540p_hls, 360p_hls, 720p_hls, 216p (worst), 360p, 540p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[download][cdanslair.mp4] Written 1014.3 MB (1m56s @ 5.7 MB/s)
[cli][info] Stream ended
[cli][info] Closing currently open stream...
