### ISSUE TITLE
convert srv3 to vtt

### ISSUE THREAD

**Issue by gimmeAll** [ytdl-org/youtube-dl#28241]
I dont know if this is a bug, but when I put in "--all-subs --sub-format srv3 --convert-subs vtt" in attempts to convert these subtitles, it says that the video doesnt have subtitles. Is there really not a way to convert srv3 because of the fact that it is YouTube's own subtitle format?

**Comment by gimmeAll** [comment]
and yes the video i am downloading does have subtitles

**Comment by dstftw** [comment]
Such conversion is not supported.
