### ISSUE TITLE
Update 2021.02.22 so that it doesn't trigger a (false positive) virus alert?

### ISSUE THREAD

**Issue by newbiemate** [ytdl-org/youtube-dl#28259]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.02.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Description

Latest youtube-dl (2021.02.22) Windows exe triggers an alert on virus total:
https://www.virustotal.com/gui/file/e7b244aac8bc92668456d24dcef63fbbe7d6f73653bfa339d15ad571cbc9f5bc/detection

Detected as `W32.AIDetectGBM.malware.02` by Bkav Pro antivirus.

While I understand this may be a false positive, **is it possible to fix it so that it does not trigger a virus warning?** Or if we can attach a reference to the offending code in this thread just so we can verify that it's not a virus with 100% confidence? What has changed since the last version(s) that it now triggers the virus alert?

Last known clean state was `youtube-dl 2021.02.04.1`
https://www.virustotal.com/gui/file/9aea246ee9655f9818dd3c4a389273118898b2ece39f6e0adf703213e1a5c074/detection

**Comment by dstftw** [comment]
Nothing changed. Report to Bkav Pro.

**Comment by rautamiekka** [comment]
Man, that's one old and obsolete, not to mention akin to a scam, antivirus. Like, it was reportedly good back in the 90s, but its Engine hasn't been touched since 2007, and stuff.

So yeah, get rid of that shit.
