### ISSUE TITLE
Playlist functionality, save JSON data to individual files.

### ISSUE THREAD

**Issue by tsingi** [ytdl-org/youtube-dl#28254]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.02.22**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

I'm working with BitChute playlists, they can be very large.  Dumping the whole
playlist to a single file could involve scanning 1000 videos'.  Cancelling
that gets you nothing.

I would like to be able to have youtube-dl to scan the playlist and save individual
JSON files as the pages are scanned using a unique ID, probably the 'id' field,
this would be unique at BitChute.

This would also give you an idea of your progress, just by looking at what has
been downloaded so far.

I CAN PROBABLY DO THIS MYSELF if someone can point me at the relevant code,
recommend a command line switch and give me some pointers.

Looking at creating some level of implementation for editing the download
files instead of hoovering the whole thing or specifying by manual analysis
which files to get.  The JSON metadata is perfect for this.

**Comment by dstftw** [comment]
Read FAQ.
```
--write-info-json                    Write video metadata to a .info.json
                                     file
```

**Comment by tsingi** [comment]
Yes, and that also downloads the video.
Not what I want.
However using --skip-download with that does do what I want.
So I have what I want.
