### ISSUE TITLE
Request new site: peacocktv.com

### ISSUE THREAD

**Issue by rgiuffre** [ytdl-org/youtube-dl#28257]
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.02.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs
- Single video: https://www.peacocktv.com/watch/asset/tv/the-office/4902514835143843112
- Single video: https://www.peacocktv.com/watch/playback/vod/GMO_00000000059625_01/58fabbf4-9291-3575-bcdc-bd25eee192c8

If work on your issue requires account credentials please provide them or explain how one can obtain them.
--> PeacockTV.com is free, with an account login.

WRITE DESCRIPTION HERE
Looking for youtube-dl support for PeacockTV.com using legit login credentials.

**Comment by nonspin** [comment]
DRM

**Comment by Hadibeydoun8** [comment]
Bump
