### ISSUE TITLE
[Youtube Music] `album_artist` always undefined, `year` is wrong for reeditions

### ISSUE THREAD

**Issue by ClementNerma** [ytdl-org/youtube-dl#28265]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.02.22**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f bestaudio', u'--add-metadata', u'https://music.youtube.com/playlist?list=OLAK5uy_kC__gzMYhyRvNjxz1AggNJuuyajdE54CA', u'-v', u'--playlist-start', u'5', u'--playlist-end', u'5', u'-o', u'%(album_artist)s - %(release_year)s - %(album)s/%(playlist_index)s.%(release_year)s.%(id)s. %(track)s.%(ext)s', u'--exec', u'zsh xxxxxxxxxxx.zsh', u'--cookies', u'xxxxxxxxxxxxx.cookies.txt']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.02.22
[debug] Python version 2.7.16 (CPython) - Linux-4.19.104-microsoft-standard-x86_64-with-debian-10.8
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[youtube:tab] OLAK5uy_kC__gzMYhyRvNjxz1AggNJuuyajdE54CA: Downloading webpage
[download] Downloading playlist: Album – Passione
[youtube:tab] playlist Album – Passione: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] PwXBA6XTAUY: Downloading webpage
[debug] Invoking downloader on u'<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<URL>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>'
[download] Destination: NA - 2012 - Passione/5.2012.PwXBA6XTAUY. Quizás, Quizás, Quizás.webm
[download] 100% of 3.15MiB in 00:00
[ffmpeg] Adding metadata to 'NA - 2012 - Passione/5.2012.PwXBA6XTAUY. Quizás, Quizás, Quizás.webm'
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:NA - 2012 - Passione/5.2012.PwXBA6XTAUY. Quizás, Quizás, Quizás.webm' -c copy -metadata 'comment=Provided to YouTube by Universal Music Group

Quizás, Quizás, Quizás · Andrea Bocelli · Jennifer Lopez

Passione

℗ 2012 Sugar Srl, under exclusive license to Universal International Music B.V.

Released on: 2013-01-01

Producer: Kuk Harrell
Associated  Performer, Orchestra  Leader: Nathan Kelly
Associated  Performer, Keyboards, Producer: David Foster
Associated  Performer, Acoustic  Guitar: Daniele Bonaviri
Associated  Performer, Electric  Guitar: Michael Thompson
Associated  Performer, Bass (vocal): Nathan East
Associated  Performer, Drums: John Robinson
Associated  Performer, Percussion: Rafael Padilla
Associated  Performer, Violin: Juan Carlos Albelo
Associated  Performer, Synthesizer: Jochem van der Saag
Composer  Lyricist: Osvaldo Farrés
Arranger, Work  Arranger: David Foster
Arranger, Orchestrator: Nathan Kelly

Auto-generated by YouTube.' -metadata 'album=Passione' -metadata 'description=Provided to YouTube by Universal Music Group

Quizás, Quizás, Quizás · Andrea Bocelli · Jennifer Lopez

Passione

℗ 2012 Sugar Srl, under exclusive license to Universal International Music B.V.

Released on: 2013-01-01

Producer: Kuk Harrell
Associated  Performer, Orchestra  Leader: Nathan Kelly
Associated  Performer, Keyboards, Producer: David Foster
Associated  Performer, Acoustic  Guitar: Daniele Bonaviri
Associated  Performer, Electric  Guitar: Michael Thompson
Associated  Performer, Bass (vocal): Nathan East
Associated  Performer, Drums: John Robinson
Associated  Performer, Percussion: Rafael Padilla
Associated  Performer, Violin: Juan Carlos Albelo
Associated  Performer, Synthesizer: Jochem van der Saag
Composer  Lyricist: Osvaldo Farrés
Arranger, Work  Arranger: David Foster
Arranger, Orchestrator: Nathan Kelly

Auto-generated by YouTube.' -metadata 'artist=Andrea Bocelli, Jennifer Lopez' -metadata 'title=Quizás, Quizás, Quizás' -metadata 'date=20180725' -metadata 'purl=https://www.youtube.com/watch?v=PwXBA6XTAUY' 'file:NA - 2012 - Passione/5.2012.PwXBA6XTAUY. Quizás, Quizás, Quizás.temp.webm'
[exec] Executing command: xxxxxxxxxxxxxxxxxxx.zsh 'NA - 2012 - Passione/5.2012.PwXBA6XTAUY. Quizás, Quizás, Quizás.webm'
```

(I've hidden the URLs since I use my Google account to access these tracks, and I don't know if they contain access tokens or anything)

## Description

The `%(album_artist)s` field is always undefined (`NA`). This is problematic since using `%(artist)s` will always lead to albums split into multiple albums when tagged, as many albums have featurings.

The `%(artist)s` field is fine though.

Also, the `%(year)s` field often shows wrong values for reeditions, for instance the `Blackout` album for `Scorpions`, which is correctly shown as being from 1982 on Youtube Music, is tagged as 2015 by Youtube-DL, which is the date of its reedition.

**Comment by remitamine** [comment]
> The %(album_artist)s field is always undefined (NA). This is problematic since using %(artist)s will always lead to albums split into multiple albums when tagged, as many albums have featurings.

not provided by youtube.
> Also, the %(year)s field often shows wrong values for reeditions, for instance the Blackout album for Scorpions, which is correctly shown as being from 1982 on Youtube Music, is tagged as 2015 by Youtube-DL, which is the date of its reedition.

it's `release_year` not `year`.
```
youtube-dl -j https://music.youtube.com/watch?v=akuNAFpZvxs | jq .release_year
1982
```

**Comment by ClementNerma** [comment]
> > The %(album_artist)s field is always undefined (NA). This is problematic since using %(artist)s will always lead to albums split into multiple albums when tagged, as many albums have featurings.
> 
> not provided by youtube.
> 
> > Also, the %(year)s field often shows wrong values for reeditions, for instance the Blackout album for Scorpions, which is correctly shown as being from 1982 on Youtube Music, is tagged as 2015 by Youtube-DL, which is the date of its reedition.
> 
> it's `release_year` not `year`.
> 
> ```
> youtube-dl -j https://music.youtube.com/watch?v=akuNAFpZvxs | jq .release_year
> 1982
> ```

Sorry I indeed meant `release_year`.

Isn't there a way to extract the album's name and true year from the album's web page itself? (which is usually the URL downloaded from)

**Comment by remitamine** [comment]
> Isn't there a way to extract the album's name and true year from the album's web page itself? (which is usually the URL downloaded from)

it's already extracted from the video webpage when available, if you have an example where this does not work while the information actually can be extracted, you can post it here or create a new issue.

**Comment by ClementNerma** [comment]
```
youtube-dl "https://music.youtube.com/playlist?list=OLAK5uy_n3e_4DI9SFi7l3dfBm7avLc-t0oQFdHeE" -o "%(release_year)s" --get-filename
2015
2015
2015
2015
...
```

![image](https://user-images.githubusercontent.com/9782521/109388757-54d76180-7909-11eb-9c2b-8b4b875d8c8c.png)

**Comment by remitamine** [comment]
I can't access the URL that you're sharing, in the browser I'm getting `Oops, something went wrong.`, and the URL that I'm getting for this album is https://music.youtube.com/playlist?list=OLAK5uy_k2M-UMwZ0dqhFhdjerh4TQErqZw5ZMkn8, which does work as expected:
```
youtube-dl --proxy localhost:8080 https://music.youtube.com/playlist?list=OLAK5uy_k2M-UMwZ0dqhFhdjerh4TQErqZw5ZMkn8 -o '%(release_year)s' --get-filename
1982
...
```

**Comment by ClementNerma** [comment]
Well on my browser the URL you give gives me `Oops, something went wrong.`

Maybe the URL depends on the country settings?

**Comment by remitamine** [comment]
> Maybe the URL depends on the country settings?

maybe, i'm using US VPN/proxy to access Youtube Music.

**Comment by benggc** [comment]
@ClementNerma Did you manage to find any fix for the folder splitting because of multiple artist/release years issue?

**Comment by ClementNerma** [comment]
> @ClementNerma Did you manage to find any fix for the folder splitting because of multiple artist/release years issue?

Unfortunately not, I always edit the release hear by hang using Mp3Tag :/
