### ISSUE TITLE
Python or What?

### ISSUE THREAD

**Issue by R-Garry** [ytdl-org/youtube-dl#28277]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

Greetings from Bali.  I've been using Youtube-dl for years, but after installing it on a new Linux distro
every attempt to use it, update it, whatever, returns this:  /usr/bin/env: ‘python’: No such file or directory. 
Is this a python problem or what ?
Been trying to fix it for days,. Head's spinning, I'm no programmer.  Can anyone help ?

**Comment by jomyer** [comment]
I have the same question:

How to correct: /usr/bin/env: ‘python’: No such file or directory. ?

**Comment by rautamiekka** [comment]
https://github.com/ytdl-org/youtube-dl/issues/28640#issuecomment-812774031
