### ISSUE TITLE
Viu is still not working

### ISSUE THREAD

**Issue by jefferson018200306** [ytdl-org/youtube-dl#28287]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

May I ask if Viu:ott is now fixed?

**Comment by jefferson018200306** [comment]
Please fix it ASAP, so that we can enjoy our favorite Drama.. and watch it offline

**Comment by remitamine** [comment]
no.

**Comment by jefferson018200306** [comment]
> > May I ask if Viu:ott is now fixed?
> 
> no.

I hope they fix that in the next update.
