### ISSUE TITLE
[orf] please support --no-playlist for segmented features

### ISSUE THREAD

**Issue by Flexperte** [ytdl-org/youtube-dl#28284]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2021.02.22**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Many features on tvthek.orf.at are divided in segments (news, magazines, opera and theater, sports events, etc.). Nearly all of those have an alternative video for the full feature. ytdl currently only detects the segments as a playlist, but not the full video. 

**Feature request**: please detect the full video, so it can be downloaded instead of the segments using `--no-playlist`
**Implementation wish**: segmented features take the extractor a lot of time to get all formats of all segments. So an optimisation would be great to skip analysing the segments when [a full video exists] and [`--no-playlist` is given]. 

## Additional Info

The mediathekview crawler already detects the full videos. On the site http://mediathekviewweb.de they are shown among the segments, recognisable by the length and (most of the times) by the name. 

**Example** (most current, available worldwide, will be online 7 days): 
     https://tvthek.orf.at/profile/AKTUELL-nach-fuenf/13887571/AKTUELL-nach-fuenf/14083355
Best [hls-Q8C-Sehr hoch] URL of full video (from the page, before redirection): 
     https://apasfiis.sf.apa.at/ipad/cms-worldwide_episodes/14083355_0013_Q8C.mp4/playlist.m3u8
Best [hls-Q8C-Sehr hoch] URL of first segment (from the page, before redirection): 
     https://apasfiis.sf.apa.at/ipad/cms-worldwide/2021-02-26_1708_tl_02_AKTUELL-nach-fu_Signation__14083355__o__1066098380__s14867944_4__BCK2HD_17085703P_17090911P_Q8C.mp4/playlist.m3u8

**Comment by abbanatic** [comment]
👍🏿

Unfortunately, all broadcasts with chapters are only available for 7 days. But to test, you can try this URL, always pointing to the last episode:

https://tvthek.orf.at/profile/Willkommen-Oesterreich/1309549

Or, open https://tvthek.orf.at/profiles/letter/W and scroll down to "Willkommen Österreich" and you should also find the latest episode for testing.

Thanks,
Thomas

**Comment by eudinaesis** [comment]
This would be really, really great.

**Comment by dirkf** [comment]
Superseded by #32798.
