### ISSUE TITLE
Youtube - title includes datetime

### ISSUE THREAD

**Issue by lekoOwO** [ytdl-org/youtube-dl#28293]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.02.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Description

Run the following command
```
 youtube-dl --print-json --skip-download "ANY_YOUTUBE_LIVE_URL"
```
gets a `YYYY-MM-DD HH:mm` datetime in the title field (result in `"${TITLE} ${DATETIME}"`), affects `_filename` field and any other fields related with title.
while the 2020-11 version doesn't have it. Is that on purpose?

for example:
```
> youtube-dl --skip-download --print-json --referer "https://www.youtube.com/feed/subscriptions" "https://www.youtube.com/watch?v=w8sedls02ks" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--skip-download', '--print-json', '--referer', 'https://www.youtube.com/feed/subscriptions', 'https://www.youtube.com/watch?v=w8sedls02ks', '-v']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2021.02.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-essentials_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[debug] Default format spec: best/bestvideo+bestaudio
{"extractor": "youtube", ....
"title": "\u3010 90\u4e07\u4eba\u6b4c\u67a0 \u3011\uff19\uff10\u4e07\u4eba\u898b\u5c4a\u3051\u305f\u3044\u306b\u3047\uff5e\uff5e\uff5e\uff5e\uff01\uff01\uff01\u3010\u30db\u30ed\u30e9\u30a4\u30d6/\u3055\u304f\u3089\u307f\u3053\u3011 2021-02-28 19:19",
```
there's a `2021-02-28 19:19` after original title.

**Comment by dstftw** [comment]
This is expected behavior for live streams.
