### ISSUE TITLE
[Twitch] Selecting lower video resolution does not remux with best audio

### ISSUE THREAD

**Issue by glubsy** [ytdl-org/youtube-dl#28305]
- [x] I'm reporting a site feature request
- [x] I've searched the bugtracker for similar site feature requests including closed ones
- [x] I've verified that I'm running youtube-dl version **2021.02.22**

## Description
I want to download Twitch VODs in lower video resolution, but keep the best audio quality possible. 
On Twitch, lower video resolution also means lower audio quality. So I want to have the audio track from the source.

Currently, Youtube-DL does not properly select the user desired streams for remuxing (like it does for Youtube for example).
```
> youtube-dl -F URL
[info] Available formats for URL:
format code  extension  resolution note
Audio_Only   mp4        audio only  202k , mp4a.40.2
160p         mp4        284x160     260k , avc1.4D400C, 29.998fps, mp4a.40.2
360p         mp4        640x360     634k , avc1.4D401E, 29.998fps, mp4a.40.2
480p         mp4        852x480    1157k , avc1.4D401E, 29.998fps, mp4a.40.2
720p         mp4        1280x720   1849k , avc1.4D401F, 29.998fps, mp4a.40.2
720p60-0     mp4        1280x720   2479k , avc1.4D401F, 59.996fps, mp4a.40.2
720p60-1     mp4        1280x720   Source 2293k , avc1.640020, 59.996fps, mp4a.40.2 (best)
```
What I want is the 360p video, with either Audio_Only or Source audio muxed in the final file.
`youtube-dl -f 'bestvideo[height<=360]+bestaudio/best'` only downloads the appointed best, ie. the Source video in 720p.

## What I was expecting:
yt-dl should download the 360p video, then the Audio_Only, then remux the two together.

Am I missing something, or is this indeed a shortcoming of the Twitch extractor?

## My current workaround:
Currently, I have to do this process manually by:
1. Downloading either the `Audio_Only` stream or the "Source" video stream (apparently both have the same audio quality): `youtube-dl -f 'Audio_Only' -o best_audio.mp4 URL`
2. Downloading the lower video resolution file: `youtube-dl -f '360p' -o 360p_video.mp4 URL` 
3. Remuxing the two files by mapping the audio track from the first file onto the second: 
`ffmpeg -i 360p_video.mp4 -i best_audio.mp4 -c copy -map 0:v:0 -map 1:a:0 360p_with_best_audio.mp4`

Another topic that is slightly related: #15910

**Comment by dstftw** [comment]
This is expected behavior. Read format selection FAQ on what does `bestvideo`, `bestaudio` and `best` mean.

**Comment by glubsy** [comment]
Thanks! Despite having read the Readme a few times already, It was not obvious to me how to achieve that.

Here is the command that worked as expected: `youtube-dl -f 'best[height<=360]+Audio_Only'`
