### ISSUE TITLE
Youtube Hashtag Support

### ISSUE THREAD

**Issue by 7UR7L3** [ytdl-org/youtube-dl#28308]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2021.03.02**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

youtube-dl should be able to handle Youtube hashtag pages such as https://www.youtube.com/hashtag/rice . I can not find any information on converting these types of pages into proper playlists or even mix playlists to make this trivially doable.

Ideally I want to be able to grab a list of or download all videos with the hashtag, but also useful would be grabbing the top-n results displayed on the page (or in the batches that youtube loads as you scroll down).

This is the current output (no recognition of the list of videos):
```
PS C:\Users\7UR7L3> youtube-dl -v https://www.youtube.com/hashtag/rice
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/hashtag/rice']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.03.02
[debug] Python version 3.8.2 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[youtube:tab] hashtag: Downloading webpage
[download] Downloading playlist: None
[youtube:tab] playlist None: Downloading 0 videos
[download] Finished downloading playlist: None
```

**Comment by afe2c3** [comment]
+1, this seems like an addition thats worth it.

**Comment by 7UR7L3** [comment]
Wonderful! Thanks @remitamine!
