### ISSUE TITLE
Downloading from unsupported website, some failed downloads aren't treated as having failed

### ISSUE THREAD

**Issue by matoi974** [ytdl-org/youtube-dl#28310]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm trying to bulk download from an unsupported website, vrporn.com. Most videos are available in 4K, but some are only available in 1080p or 540p. Youtube-dl detects 3 quality options with the `-F` option: 0 (540p), 1 (1080p), and 2 (4K). The issue is, all videos advertise 4K as an option, but some don't actually have it (1080p and 4K both link to the same video file when downloading with a web browser), and when trying to download 4K with youtube-dl, it downloads a broken 2.5 KB file and reports successful download. 
Is there a way I could tell youtube-dl to treat files under a certain size as a failed download and either automatically attempt to download a lower quality, or at least let me know which videos failed so I can run it again?

In case you're trying to reproduce my issue, you'll most likely need to make a vrporn.com account, and to use a cookies.txt file. Also, new accounts seem to be limited to 10 downloads per day (stacks retroactively for previous days).

**Comment by dstftw** [comment]
>In case you're trying to reproduce my issue, you'll most likely need to make a vrporn.com account, and to use a cookies.txt file. Also, new accounts seem to be limited to 10 downloads per day (stacks retroactively for previous days).

It's your responsibility to provide such data.
