### ISSUE TITLE
Is this mpeg DASH (.mpd) not downloadable due to DRM ?

### ISSUE THREAD

**Issue by slrslr** [ytdl-org/youtube-dl#28322]
- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello,
[similar issue](https://github.com/ytdl-org/youtube-dl/issues/25380) was closed with a DRM flag.
i want to ask if that mean that such media can not be downloaded?

`youtube-dl -u myusername -p mypassword -f bestvideo+bestaudio "https://***.ssl.cdn.cra.cz/vod_cmesk/_definst_/***/***/***.smil/manifest.mpd" --verbose`
output [is here](https://bin.disroot.org/?70282c017681d8f1#EZYm9oKWBAeAVNREjjYWDqEbxLWaiVJZir5iGLiAhckp) (passw0rd: yd)

mpd file [looks like this](https://bin.disroot.org/?f8c8cb82ed31dabd#EyCyZmvEYwhCxAvskZpH4P6Wb3popAuJk3GHffk9sWJh)

`ffmpeg -i https://***.ssl.cdn.cra.cz/vod_cmesk/_definst_/***/***/***.smil/manifest.mpd -codec copy out.mp4`
downloaded around 1.2GB file but the image is damaged.

no way to download it except some browser extension or a screen recording software/hardware?

**Comment by llacb47** [comment]
Yes, it has DRM.
