### ISSUE TITLE
Is the json output of  formats.abr now going to be a float or should it be an int?

### ISSUE THREAD

**Issue by FingerlessGlov3s** [ytdl-org/youtube-dl#28321]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Hi,

In the past running the following command gave json info output return formats.abr as a int but now its returning as a float. Is the change a bug or will it say?

How to reproduce

Latest version
youtube-dl --write-info-json https://www.youtube.com/watch?v=Rr6qXASQrz4
Output of the json: https://gist.github.com/FingerlessGlov3s/7107a3281a37ce3a6e483c3e2ce15f2a

version backdated to 2021-01-16
youtube-dl --write-info-json https://www.youtube.com/watch?v=Rr6qXASQrz4
Output of the json: https://gist.github.com/FingerlessGlov3s/f64cca94e2036c1914461df382e7736f

Both commands ran today, within 2 minutes of each other.

**Comment by dstftw** [comment]
`abr` is allowed to be of any numeric type apart from complex.

**Comment by FingerlessGlov3s** [comment]
Cool so it can be int or float. Thanks for letting me know I'll pass this on.
