### ISSUE TITLE
Unable to use  youtube-dl in https://bflix.to site.

### ISSUE THREAD

**Issue by vince-666** [ytdl-org/youtube-dl#28337]
lubuntu@lubuntu:~/Documents$ youtube-dl -v https://www3.bflix.to/series/ancient-aliens-mvwlx/jvxn652
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www3.bflix.to/series/ancient-aliens-mvwlx/jvxn652']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 3.8.2 (CPython) - Linux-5.4.0-42-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] jvxn652: Requesting header
WARNING: Falling back on generic information extractor.
[generic] jvxn652: Downloading webpage
[generic] jvxn652: Extracting information
ERROR: Unsupported URL: https://www3.bflix.to/series/ancient-aliens-mvwlx/jvxn652
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3506, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www3.bflix.to/series/ancient-aliens-mvwlx/jvxn652

lubuntu@lubuntu:~/Documents$ $ uname -a
Linux lubuntu 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
