### ISSUE TITLE
Youtube playlists: ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by KingAbyx** [ytdl-org/youtube-dl#28331]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

``` 
$ youtube-dl -v https://www.youtube.com/playlist?list=PLqtO2KAJ9LYwxoGw16TKEDQNYS3FpBpAd
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/playlist?list=PLqtO2KAJ9LYwxoGw16TKEDQNYS3FpBpAd']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.02
[debug] Python version 3.9.2 (CPython) - Linux-5.11.1-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube:tab] PLqtO2KAJ9LYwxoGw16TKEDQNYS3FpBpAd: Downloading webpage
[download] Downloading playlist: All Bangers
[youtube:tab] Downloading page 1
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2275, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp) 
```

## Description

I tried to play my music playlist with mpv as I do most every day and it suddenly stopped working. I changed nothing. The link works perfectly fine in the browser and requesting each video individually with youtube-dl also works. Other playlists also don't work

**Comment by fuchinoko** [comment]
I also encountered this error.

**Comment by llacb47** [comment]
Update youtube-dl and search the open issues... are you serious

**Comment by KingAbyx** [comment]
> Update youtube-dl and search the open issues... are you serious

I did not find any open issues that got the 404: not found error and I updated my system right before I used the command you see in the log I posted. 
You might have just missed me acknowledging at the top that I have updated youtube-dl and that I searched the open issues, but please read the post next time

**Comment by BjarneDMat** [comment]
It's somewhat intermittent. If you do this :
youtube-dl \
                --yes-playlist \
                --playlist-end 20 \
                "${YoutubePlaylist}"
and --playlist-end is within the 1st page of videos, it's working.

Additionally, these playlists _do_ download :
https://www.youtube.com/channel/UCL-aQReu50qQ1q-djIHA0DA/videos
https://www.youtube.com/c/AcademicLesson/videos 
These two are working, because they have less than one page of videos
