### ISSUE TITLE
Unable to download videos from the website Bilibili

### ISSUE THREAD

**Issue by pengguodong12** [ytdl-org/youtube-dl#28341]
youtube-dl.exe -F https://www.bilibili.com/video/av86917375 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.bilibili.com/video/av86917375', '--verbose']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2021.03.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.3
[debug] Proxy map: {}
[BiliBili] 86917375: Downloading webpage
[BiliBili] 86917375: Downloading video info page
WARNING: Unable to download JSON metadata: HTTP Error 412: Precondition Failed
[BiliBili] 86917375: Downloading video info page
ERROR: Unable to download JSON metadata: HTTP Error 412: Precondition Failed (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\YoutubeDL.py", line 2275, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by Jane42070** [comment]
I get the same issue on Artix Linux while tryring to download Bilibili videos

**Comment by Dioxaz** [comment]
For info, logging in (with -u username) doesn't make any difference. My last successful download was on March 1st.

**Comment by xinyazhang** [comment]
It seems the standard header `'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'` (at `utils.py:1673`) prevents the server replying something useful.

Temporary workaround: add `--add-header 'Accept:*/*` to the command line.

**Comment by Dioxaz** [comment]
> 
> 
> It seems the standard header `'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'` (at `utils.py:1673`) prevents the server from replying something useful.
> 
> Temporary workaround: add `--add-header 'Accept:*/*` to the command line.

For some reason, it doesn't seem to work in my case. I still have the exact same 412 error, logged in or not. I might be doing something wrong. Also, there seems to by a typo in your text (is the single single-quote normal?).

**Comment by TeachCourse** [comment]
resolved add : 

--add-header Accept:'*/*'

**Comment by WhoR3born** [comment]
_**https://www.bilibili.com/video/BV1XY4114753**?from=search&seid=9349536755186620436&spm_id_from=333.337.0.0_

use bold part of link and add `--add-header 'Accept:*/*'`
