### ISSUE TITLE
Making the errors include the video ID

### ISSUE THREAD

**Issue by DankMemeGuy** [ytdl-org/youtube-dl#28348]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

When I do bulk rips, the errors are "ERROR: video unavailable" "this video is private"
 "this video has been removed for ...." So in the end I have thousands of these errors without much knowledge of what is actually having the problem.

It would be nice to include the ID for the video instead of saying "this video" it would be "<VIDEO ID> is private" etc.

**Comment by afe2c3** [comment]
The lines above and below include it.

**Comment by DankMemeGuy** [comment]
> The lines above and below include it.

That's if you use youtube-dl itself and not part of an integration of something larger. If you have it being the backend to anything, it will report the error without the ID

**Comment by DankMemeGuy** [comment]
@dstftw what's the duplicate issue for this so I can follow along progress
