### ISSUE TITLE
Error when downloading a video from vimeo

### ISSUE THREAD

**Issue by idelkysq** [ytdl-org/youtube-dl#28354]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://vimeo.com/519959487/a8859b5ad5', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-66-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 519959487: Downloading webpage
[vimeo] 519959487: Extracting information
ERROR: Unable to extract info section (caused by ValueError('Extra data: line 1 column 3 - line 1 column 104 (char 2 - 103)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 665, in _real_extract
    config = json.loads(config)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 3 - line 1 column 104 (char 2 - 103)
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 678, in _real_extract
    cause=e)
ExtractorError: Unable to extract info section (caused by ValueError('Extra data: line 1 column 3 - line 1 column 104 (char 2 - 103)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE

I'm trying to download a video from video. It was working perfectly fine on Wednesday March 3rd, 2021

**Comment by CHJ85** [comment]
I updated the extractor using this pull request, and it worked fine:
https://github.com/ytdl-org/youtube-dl/pull/27992/commits/5959cc11f1aa7893ea54934691f045cc07dc7f52

**Comment by idelkysq** [comment]
Hi @CHJ85 thanks for your reply. How i can update the extractor? Sorry, I'm quite new and I don't know what to do in order to make this to work. 
Thanks in advance.

**Comment by idelkysq** [comment]
Thanks @CHJ85. I'm using Ubuntu 20.04.2 LTS.
I installed **_youtube-dl_**  following https://snapcraft.io/install/youtube-dl/ubuntu

$ whereis youtube-dl
youtube-dl: /snap/bin/youtube-dl

I can't find the youtube-dl directory :(

any idea where to find it? Thanks

**Comment by CHJ85** [comment]
@idelkysq Right. I believe snap packages are stored under /snap.
I'm using Ubuntu 20.10 myself. But I didn't install it using Snap. I used pip3 (the python installer).
❯ sudo pip3 install youtube-dl          
So for me, youtube-dl is located under /usr/local/lib/python3.8/dist-packages/youtube_dl
Either way, for you, the file should be located under /snap/youtube_dl/extractor

**Comment by remitamine** [comment]
the URL is no longer available.

**Comment by pt321** [comment]
I tried the patch and it didn't work on unlisted videos, until two days ago youtube-dl was working on unlisted vimeo videos. So when it failed I tried this patch and still giving a similar error.  **Extra data: line 1 column 3 (char 2)**

[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-58-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
ERROR: Unable to extract info section (caused by JSONDecodeError('Extra data: line 1 column 3 (char 2)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.8/site-packages/youtube_dl/extractor/vimeo.py", line 693, in _real_extract
    page_config = self._parse_json(self._search_regex(
  File "/home/me/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract page config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/.local/lib/python3.8/site-packages/youtube_dl/extractor/vimeo.py", line 716, in _real_extract
    config = json.loads(config)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.8/site-packages/youtube_dl/extractor/vimeo.py", line 693, in _real_extract
    page_config = self._parse_json(self._search_regex(
  File "/home/me/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

**Comment by idelkysq** [comment]
Hi, it didn't work for me either @pt321! 

@CHJ85 thanks for your help.

I tried all you have suggested and still getting the same error... :(

Any other idea? As I said on my first post, it was working fine on the 3rd March, then, it stopped working!

**Comment by pukkandan** [comment]
@pt321 the log is incomplete. Give the full output you got in the console including the `Command-line config` part

**Comment by pt321** [comment]
Sorry I tried another unlisted video and it was fine. After going back to the video that didn't work,  when I changed it to use the player URL and used the referrer argument it worked

https://player.vimeo.com/video/videoID --referer  https://www.somedomain.com/

So you can ignore my original input

**Comment by pt321** [comment]
It's a private video and  I am not the creator of the video so I took out any links to the video from the verbose log.

**Comment by idelkysq** [comment]
@pukkandan @CHJ85 

I tried with the patch and it didn't work! :(

user@ubuntu$ youtube-dl https://vimeo.com/521855331/84ef609aea --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vimeo.com/521855331/84ef609aea', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-66-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 521855331: Downloading webpage
[vimeo] 521855331: Extracting information
ERROR: Unable to extract info section (caused by JSONDecodeError('Extra data: line 1 column 3 (char 2)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/vimeo.py", line 642, in _real_extract
    page_config = self._parse_json(self._search_regex(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract page config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/vimeo.py", line 665, in _real_extract
    config = json.loads(config)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/vimeo.py", line 642, in _real_extract
    page_config = self._parse_json(self._search_regex(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract page config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/vimeo.py", line 665, in _real_extract
    config = json.loads(config)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/vimeo.py", line 677, in _real_extract
    raise ExtractorError('Unable to extract info section',
youtube_dl.utils.ExtractorError: Unable to extract info section (caused by JSONDecodeError('Extra data: line 1 column 3 (char 2)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by pt321** [comment]
**idelkysq** That video can only be used using the player url 

you need to put the domain of the page where you found the link for the referer param

youtube-dl https://player.vimeo.com/video/521855331 --verbose --referer https://www.somedomain.com/
