### ISSUE TITLE
All downloads taking 15+ minutes

### ISSUE THREAD

**Issue by JakeGuy11** [ytdl-org/youtube-dl#28359]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[jake@Jakes-T530 Downloads]$ youtube-dl -v https://www.youtube.com/watch?v=SUtNO4UrW_4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=SUtNO4UrW_4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 3.9.1 (CPython) - Linux-5.11.1-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] SUtNO4UrW_4: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r1---sn-gvbxgn-t34e.googlevideo.com/videoplayback?expire=1615003620&ei=hKtCYLOsHJGztQfbvJ7QAQ&ip=99.250.186.3&id=o-AHPCddSyliZ-sW821e5yhujqUqgL1oJqHzUPPklqFG5e&itag=247&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C394%2C395%2C396%2C397%2C398&source=youtube&requiressl=yes&mh=P3&mm=31%2C29&mn=sn-gvbxgn-t34e%2Csn-gvbxgn-tt1es&ms=au%2Crdu&mv=m&mvi=1&pl=18&initcwndbps=2088750&vprv=1&mime=video%2Fwebm&ns=pZn3VseBMK0OzoXTH489ol8F&gir=yes&clen=15171775&dur=207.040&lmt=1577374168282618&mt=1614981638&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5431432&n=xv4EvSvdA6xldVzcd4&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAIR5xXK4RRBiJEfBii9Y2iuCAMXX7fTDmc9ALLGJEPRCAiEA-JOWfIWaXM1gdMpfpglxYecHMZ5ibZsCV07OL8w0vrM%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgTe_j96aeI_m0HUWoUHcvR0St_TnqGvqSP2Ijw39AJn0CIDT87TzdLcFIaOxVROQDjtY9GiiMvSA6RgPcVrc3arXs'
[download] Destination: Childish Insults-SUtNO4UrW_4.f247.webm
[download] 100% of 14.47MiB in 04:21
[debug] Invoking downloader on 'https://r1---sn-gvbxgn-t34e.googlevideo.com/videoplayback?expire=1615003620&ei=hKtCYLOsHJGztQfbvJ7QAQ&ip=99.250.186.3&id=o-AHPCddSyliZ-sW821e5yhujqUqgL1oJqHzUPPklqFG5e&itag=140&source=youtube&requiressl=yes&mh=P3&mm=31%2C29&mn=sn-gvbxgn-t34e%2Csn-gvbxgn-tt1es&ms=au%2Crdu&mv=m&mvi=1&pl=18&initcwndbps=2088750&vprv=1&mime=audio%2Fmp4&ns=pZn3VseBMK0OzoXTH489ol8F&gir=yes&clen=3353120&dur=207.145&lmt=1577373750214280&mt=1614981638&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5431432&n=xv4EvSvdA6xldVzcd4&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAP-MF6z_50NQ-qobmzpMDdEHBuHAZB3_z0-sgd2kA75sAiEA6agA5CbZ4ZcA8pQPvQ4O7eD3b7DusY05qyVIBV51Rp0%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgTe_j96aeI_m0HUWoUHcvR0St_TnqGvqSP2Ijw39AJn0CIDT87TzdLcFIaOxVROQDjtY9GiiMvSA6RgPcVrc3arXs'
[download] Destination: Childish Insults-SUtNO4UrW_4.f140.m4a
[download] 100% of 3.20MiB in 04:19
[ffmpeg] Merging formats into "Childish Insults-SUtNO4UrW_4.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Childish Insults-SUtNO4UrW_4.f247.webm' -i 'file:Childish Insults-SUtNO4UrW_4.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Childish Insults-SUtNO4UrW_4.temp.mkv'
Deleting original file Childish Insults-SUtNO4UrW_4.f247.webm (pass -k to keep)
Deleting original file Childish Insults-SUtNO4UrW_4.f140.m4a (pass -k to keep)
[jake@Jakes-T530 Downloads]$
```

## Description

Earlier today, youtube-dl was working fine (version 2021.02.28). Just a couple of hours ago, it stopped working. I was using youtube-dl from the arch package manager (I'm on manjaro), so the latest version was still 2021.02.28. I've updated to 2021.03.03 using the curl instructions, and the same thing happened. I let it run for about 20 minutes, and it finally downloaded. Nothing weird happened in the verbose log, since it just took a long time but ultimately worked. The wait happened after line 11 was printed, `[youtube] SUtNO4UrW_4: Downloading webpage`. \
So far, I've tried with and without a VPN with both the arch pacman version and the newer curl version, both before and after a restart. I also tried a twitter video, and the same thing happened (It was pretty much the same log as above, just with twitter. I exited the terminal before copying the log, and I don't think it's worth sitting through that again to put the log up. If you think I should do it again and upload the log, just let me know and I'll do it).\
It shouldn't be my wifi speed or ffmpeg speed, I've been able to download a 10 minute video in seconds consistently, and I tested out ffmpeg again and it was as fast as ever.\
I'm assuming this is an issue unique to me because of the lack of issues here in the past few hours, what could be causing this? I plan on trying it again on a live ubuntu and on a different computer soon, I'll update with my results once I do.

**Comment by dstftw** [comment]
Most likely a network issue on your side.
