### ISSUE TITLE
Error 403 dowloading  from https://platzi.com/

### ISSUE THREAD

**Issue by jeancarlosrecio** [ytdl-org/youtube-dl#28368]
last month I was able to download without problems from this page to support my courses, and it no longer allows me it gives me an error HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>)

**Comment by dirkf** [comment]
I've updated the PR code for #30548. Please test and follow up [there](https://github.com/ytdl-org/youtube-dl/pull/30548).
