### ISSUE TITLE
Funimation

### ISSUE THREAD

**Issue by BaseCrunch** [ytdl-org/youtube-dl#28371]
[Funimation] Logging in
[Funimation] diva: Downloading webpage
[Funimation] 120577: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('items',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

*************I TRIED THESE METHODS****************
youtube-dl -f best --cookies cookies.txt animeurl

youtube-dl -u email -p password -f best --cookies cookies.txt animeurl

and yes I reset my cookies

**Comment by BaseCrunch** [comment]
just now starts working wtf

**Comment by CHJ85** [comment]
How did you get it working?
