### ISSUE TITLE
clicknupload.net

### ISSUE THREAD

**Issue by ReverseClone** [ytdl-org/youtube-dl#28376]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://olive01.clicknupload.net:8080/d/uo57gbv7lryd7tr757g5tjqkdzmrhxhzdzhdx63iw52ouyplze5rw5xyr7hdiqxtwjl3d2zm/Love.Potion.No..9.1992.720p.WEBRip.x264.AAC-[YTS.MX].www.RapidMovieZ.com.mp4
- single video: https://magenta01.clicknupload.net:8080/d/xs5qkz57lryd7tr75hg5v4aibhvemwe2qiih6hd5urcgc2se5bplgf3cdqa3jwroisdeeicc/Capital.In.The.Twenty-First.Century.2019.720p.BluRay.x264.AAC-[YTS.MX].www.RapidMovieZ.com.mp4
- single video: https://dark01.clicknupload.net:8080/d/zk5we757lryd7tr753g4jncklybvr32e27ewmmlomur5gqb7qyogkdmiyen67vwyul7gati5/rent.boys.2011.subbed.720p.bluray.hevc.x265.rmteam.mkv
- single video: https://pearl01.clicknupload.net:8080/d/3w5vgb57lryd7tr757g4lkapdm2ht46dyxsanflt7tdzank7sjv27drsb3uko2nt7yh3hpes/the.pollinators.2019.720p.web.hevc.x265.rmteam.mkv

## Description

Clicknupload is a file hosting cloud. Most of the files are movies, series, applications. 4 example url is given. There are others too difference is olive01 part in url, it may be black01, violet01, pink01, red01 etc... And these generated links will expire 12hr after the link generation.

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).

**Comment by ReverseClone** [comment]
Oh.k.
By the way thanks.
