### ISSUE TITLE
Option to download the newest video from a YouTube channel

### ISSUE THREAD

**Issue by OraBB1t** [ytdl-org/youtube-dl#28388]
## Checklist

- [ x] I'm reporting a feature request
- [ x] I've verified that I'm running youtube-dl version **2021.03.03**
- [ x] I've searched the bugtracker for similar feature requests including closed ones

## Description

The only way as of now(AFAIK) to download **the newest video** from a youtube channel is to use the ```--date``` or the ```--dateafter``` option, which goes through all the videos on that channel and look for the ones that match the given date/range. More videos a channel has, more time it takes to go through all of them.

I think there should be a faster way to download the newest video from a channel. In youtube we can ``` Sort by -> Date added(newest)``` to find the newest video. Maybe download the first video from that filtered list? That should make the whole process much faster since youtube itself is doing the filtering.

We could add an option like ```--newest``` under 'Video Selection' section.

Thanks.

**Comment by christoph-heinrich** [comment]
That can be achieved with `youtube-dl --max-downloads 1 <url to youtube channel>/videos`

**Comment by OraBB1t** [comment]
> That can be achieved with `youtube-dl --max-downloads 1 <url to youtube channel>/videos`

Works. But still goes through all the pages before downloading. Faster than ```--date``` or ```--dateafter``` I think.

**Comment by OraBB1t** [comment]
@dstftw Sorry but duplicate of what exactly?
