### ISSUE TITLE
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.

### ISSUE THREAD

**Issue by mrhaha80** [ytdl-org/youtube-dl#28387]
Hi there,

I am a Windows user , i downloaded the program from https://yt-dl.org/latest/youtube-dl.exe, when i have tried to commands below:
`youtube-dl --username <myemail@gmail.com> --password <mypassword> https://www.facebook.com/financialfreedom001/videos/400765281183859`

`youtube-dl https://www.facebook.com/financialfreedom001/videos/400765281183859 --username <myemail@gmail.com> --password <mypassword>`

`youtube-dl --u <myemail@gmail.com> --p <mypassword> https://www.facebook.com/financialfreedom001/videos/400765281183859`

`youtube-dl https://www.facebook.com/financialfreedom001/videos/400765281183859 --u <myemail@gmail.com> --p <mypassword>`

and i always get the message below:
`k.com/financialfreedom001/videos/400765281183859
[facebook] Downloading login page
[facebook] Logging in
[facebook] 400765281183859: Downloading webpage
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.`

May i know what is the issue?

Thanks
Ant

**Comment by october262** [comment]
1st - are you signed in to facebook ??
2nd - is the video a private video ??
you can try using the cookies option, but use caution because facebook will lockout
your account for unusual activity.

**Comment by mrhaha80** [comment]
> 1st - are you signed in to facebook ??
> 2nd - is the video a private video ??
> you can try using the cookies option, but use caution because facebook will lockout
> your account for unusual activity.

Hi October262,
1. yes. but does not matter right? because I have put the username and password in the command.
2. it is a private video, that is why I put the username and password in the command.(i have access to the video)
3. I tried with the cookies option, as well but it gives another error below,  i tried to google, i saw some of them got the same issue but cannot find any solutions
`error: unable to extract lsd; please report this issue on https://yt-dl.org/bug . m....`


Thanks
Ant

**Comment by october262** [comment]
> > 1st - are you signed in to facebook ??
> > 2nd - is the video a private video ??
> > you can try using the cookies option, but use caution because facebook will lockout
> > your account for unusual activity.
> 
> Hi October262,
> 
> 1. yes. but does not matter right? because I have put the username and password in the command.
> 2. it is a private video, that is why I put the username and password in the command.(i have access to the video)
> 3. I tried with the cookies option, as well but it gives another error below,  i tried to google, i saw some of them got the same issue but cannot find any solutions
>    `error: unable to extract lsd; please report this issue on https://yt-dl.org/bug . m....`
> 
> Thanks
> Ant

play the video, and see if there's 3 dots ... in the upper right hand corner of the 
video, does it give an option to download & save the video ??

**Comment by remitamine** [comment]
use authenticated cookies, don't combine the `--cookies` option with `--username` and `--password` option.

**Comment by mrhaha80** [comment]
> use authenticated cookies, don't combine the `--cookies` option with `--username` and `--password` option.

@remitamine 
MAAAAAAY Thanks!!! it is working!!
