### ISSUE TITLE
[AfreecaTV] Single video is downloaded as "playlist" of segments

### ISSUE THREAD

**Issue by msikma** [ytdl-org/youtube-dl#28396]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones
- [x] I'm using version `2021.03.03`

## Question

Hi everyone. I'm using youtube-dl to archive some videos from AfreecaTV. On Afreeca, videos are implemented in such a way that they're chunks of 1 hour long, and each chunk is split into small segment files.

When downloading, the smaller segments get merged into the hour-long segments correctly, but the hour-long segments are not merged into a single video as it should be. In fact, youtube-dl seems to think that single videos are "playlists" of multiple videos.

For example, downloading [this 4:08:14 long video](https://vod.afreecatv.com/PLAYER/STATION/46171437) results in the following files:

<img width="550" alt="image" src="https://user-images.githubusercontent.com/1507745/110533683-8b3d8980-811e-11eb-9a50-1e83ad73151a.png">

My question: is there something I can do to ensure these videos are merged automatically? I wasn't able to find anything in the readme about this. I suppose it makes sense since you wouldn't normally merge a playlist into a single video, but I think in this case it's not really a "playlist" but a technical implementation detail.

Thanks for any help 🙂

**Comment by remitamine** [comment]
not currently supported.
