### ISSUE TITLE
Bug extractor [Linux server]

### ISSUE THREAD

**Issue by X-C0DE** [ytdl-org/youtube-dl#28399]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.instagram.com/reel/CMFPWSCHTqT/?igshid=1sbeffbbc4mif', '-F', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-128-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[Instagram] CMFPWSCHTqT: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/extractor/instagram.py", line 216, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1128, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1019, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

This same video i can get in my computer OK. But when i put in my linux server I can't get it

**Comment by FiskFan1999** [comment]
Having similar issue downloading instagram.com/tv video, works on macos but not on linux, both 2021-03-03.

Using `18.04.5 LTS (GNU/Linux 5.4.0-1038-aws x86_64)`

```[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.instagram.com/tv/B_y1Kf_DPKH/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 2.7.17 (CPython) - Linux-5.4.0-1038-aws-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[Instagram] B_y1Kf_DPKH: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/instagram.py", line 216, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1128, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1019, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

**Comment by X-C0DE** [comment]
> Having similar issue downloading instagram.com/tv video, works on macos but not on linux, both 2021-03-03.
> 
> Using `18.04.5 LTS (GNU/Linux 5.4.0-1038-aws x86_64)`
> 
> ```
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'--verbose', u'https://www.instagram.com/tv/B_y1Kf_DPKH/']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2021.03.03
> [debug] Python version 2.7.17 (CPython) - Linux-5.4.0-1038-aws-x86_64-with-Ubuntu-18.04-bionic
> [debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
> [debug] Proxy map: {}
> [Instagram] B_y1Kf_DPKH: Downloading webpage
> ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
>     return func(self, *args, **kwargs)
>   File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
>     ie_result = ie.extract(url)
>   File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
>     ie_result = self._real_extract(url)
>   File "/usr/bin/youtube-dl/youtube_dl/extractor/instagram.py", line 216, in _real_extract
>     video_url = self._og_search_video_url(webpage, secure=False)
>   File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1128, in _og_search_video_url
>     return self._html_search_regex(regexes, html, name, **kargs)
>   File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1019, in _html_search_regex
>     res = self._search_regex(pattern, string, name, default, fatal, flags, group)
>   File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
>     raise RegexNotFoundError('Unable to extract %s' % _name)
> RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```
> ```

in my debian 10 works fine
is weird lol
