### ISSUE TITLE
www.southparkstudios.com is not supported by 2021.03.03

### ISSUE THREAD

**Issue by aleksejrs** [ytdl-org/youtube-dl#28413]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.southparkstudios.com/episodes/h4o269/south-park-stunning-and-brave-season-19-ep-1
- Single video: https://www.southparkstudios.com/video-clips/oomplh/south-park-watch-your-microaggressions-bro
- Playlist: https://www.southparkstudios.com/seasons/south-park/bl4xrv/season-19

## Description

ERROR: Unsupported URL: https://www.southparkstudios.com/episodes/h4o269/south-park-stunning-and-brave-season-19-ep-1

```
$ youtube-dl --list-extractors|grep -i south
southpark.cc.com
southpark.cc.com:español
southpark.de
southpark.nl
southparkstudios.dk
```

**Comment by IPeluchito** [comment]
Please add support for https://www.southpark.lat/
here the audio is Latin Spanish directly....
