### ISSUE TITLE
Getting Error 404 downloading a youtube video that is playable in browser

### ISSUE THREAD

**Issue by rgiuffre** [ytdl-org/youtube-dl#28412]
## Checklist

- [ x] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.03.03**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[youtube] 24mgrFQmju8: Downloading webpage
[youtube] 24mgrFQmju8: Downloading MPD manifest
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1615523479/ei/N5pKYJXPG_GJsfIPgI-E-Ag/ip/2603%3A8000%3Ac602%3A8944%3A74be%3Ad5c9%3Ab5bb%3Ae637/id/db89a0ac54268eef/source/youtube/requiressl/yes/playback_host/r5---sn-a5mlrn7s.googlevideo.com/mh/E8/mm/31%2C29/mn/sn-a5mlrn7s%2Csn-a5meknzk/ms/au%2Crdu/mv/m/mvi/5/pl/28/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1955000/vprv/1/mt/1615501724/fvip/5/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIhAL2CYsbStAWkTfTwEib6pTTouswX_QFfyXdm6VPkCv_SAiAG8f1oJqzARsSaaX7OMGSF2BWXRkt_ZiYWUQ6P4cQr1A%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRAIgNvtsgUPa365oAGmNcjXlZCiloxl1dUMwrpJlLkQ0CAYCIG_NAg94aq9MqIgx2pNDPAcoOUbEQKiU1TLjxxSsI7mo'
[dashsegments] Total fragments: 19
[download] Destination: Stargate Universe - Don't Encourage Him _ Kino Webisode 06-24mgrFQmju8.f243.webm
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10)...
[debug] Invoking downloader on 'https://r5---sn-a5mlrn7s.googlevideo.com/videoplayback?expire=1615523479&ei=N5pKYJXPG_GJsfIPgI-E-Ag&ip=2603%3A8000%3Ac602%3A8944%3A74be%3Ad5c9%3Ab5bb%3Ae637&id=o-AGupuzNQ0VbJz91LZtt420XOHhHD-Bduh1whUIsOgyEt&itag=140&source=youtube&requiressl=yes&mh=E8&mm=31%2C29&mn=sn-a5mlrn7s%2Csn-a5meknzk&ms=au%2Crdu&mv=m&mvi=5&pl=28&initcwndbps=1955000&vprv=1&mime=audio%2Fmp4&ns=BpON9BPHUYd_wPpDkqiTTSAF&gir=yes&clen=1505027&otfp=1&dur=92.949&lmt=1601969284922812&mt=1615501724&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=1211222&n=7DGt4-KRiyFIG3cgM&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRAIgRAUaTvvzS9TtZ_l23Er7weqCnhJBa-vO5aLYXAcitUgCIDTUe_k-d4vgI2W4W1Gf5wPprh2kAlRCgDqO-FQw5flK&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgV0Fq6BRfyEOeFLoWabbIMlM2grKSWk8qrL2XnQo9fkwCIQCdchWIv_ZB-QoXdtjIHK11rXE9zD66rDn0WC5JuDLr8w%3D%3D'
[download] Stargate Universe - Don't Encourage Him _ Kino Webisode 06-24mgrFQmju8.f140.m4a has already been downloaded

[download] 100% of 1.44MiB

## Description

WRITE DESCRIPTION HERE

I've tried using -i and --ignore-errors, and I've also tried upping the retries and fragment retries but I still get the errors. I'm using the latest youtube-dl and ffmpeg.

**Comment by pukkandan** [comment]
Seems to be youtube's issue. You'll have to download a format other than 243
![image](https://user-images.githubusercontent.com/6623388/111017957-62e2b300-83dc-11eb-9ee2-c92ef299786d.png)
