### ISSUE TITLE
Recent changes to Vimeo break yt-dl support with unlisted videos

### ISSUE THREAD

**Issue by jshir** [ytdl-org/youtube-dl#28414]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl https://vimeo.com/304887422/34c51f7a09 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vimeo.com/304887422/34c51f7a09', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.03.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[vimeo] 304887422: Downloading webpage
[vimeo] 304887422: Extracting information
ERROR: Unable to extract info section (caused by ValueError('Extra data: line 1 column 3 - line 1 column 104 (char 2 - 103)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\vimeo.py", line 644, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\common.py", line 1010, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract page config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\vimeo.py", line 665, in _real_extract
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 346, in decode
ValueError: Extra data: line 1 column 3 - line 1 column 104 (char 2 - 103)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\vimeo.py", line 644, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\common.py", line 1010, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract page config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\vimeo.py", line 665, in _real_extract
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 346, in decode
ValueError: Extra data: line 1 column 3 - line 1 column 104 (char 2 - 103)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\vimeo.py", line 678, in _real_extract
youtube_dl.utils.ExtractorError: Unable to extract info section (caused by ValueError('Extra data: line 1 column 3 - line 1 column 104 (char 2 - 103)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

Example (this isn't the video I wanted to download but my video is Patreon aka paysite content, this video reproduces the problem I have): https://vimeo.com/304887422/34c51f7a09

These types of videos are "unlisted" videos with the extra hash segment after the last forward-slash in the URL. It's different from password-protected videos. They worked fine as recently as a week ago, so I guess something changed on vimeo. With that said, the workaround from #27591 works in this situation, but that still isn't an ideal way to timeshift more than one or two videos, is there a way this can be corrected in the vimeo plugin?

**Comment by october262** [comment]
for this video - https://vimeo.com/304887422/34c51f7a09
use https://player.vimeo.com/video/304887422?autoplay=1
to download the video.

**Comment by andrino-meli** [comment]
> for this video - https://vimeo.com/304887422/34c51f7a09
> use https://player.vimeo.com/video/304887422?autoplay=1
> to download the video.

Funny. I head the same problem but changing the url to the embeded version did not fix it for me. But what did is using the url generated when **clicking the "review" button on the vimeo site**. The resulting url is of the form:
[https://vimeo.com/asvz/review/304887422/?????](https://vimeo.com/asvz/review/304887422/?????)

Note this is for the above example not working. I do not wonna provide my link that is working for me as I signed to not share it.
The **????** are a placeholder. I could not figure out how they are generated from the original link, sorry.

Maybee this experimentation helps someone.

I do not run the dev. version or have much experience with this tool. I use this occasion to thank the developers for their effort and time to create this amazing tool. Thaks.

**Comment by superian** [comment]
> for this video - https://vimeo.com/304887422/34c51f7a09
> use https://player.vimeo.com/video/304887422?autoplay=1
> to download the video.

Doesn't work for me (video number changed)

```
$ youtube-dl "https://player.vimeo.com/video/1234567890?autoplay=1"
[vimeo] 1234567890: Downloading webpage
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
```

**Comment by superian** [comment]
> Funny. I head the same problem but changing the url to the embeded version did not fix it for me. But what did is using the url generated when **clicking the "review" button on the vimeo site**. The resulting url is of the form:
> https://vimeo.com/asvz/review/304887422/?????

This is working for me too.

> I use this occasion to thank the developers for their effort and time to create this amazing tool. Thaks.

Indeed, everything but my level of disc free space thanks you!

**Comment by october262** [comment]
> > for this video - https://vimeo.com/304887422/34c51f7a09
> > use https://player.vimeo.com/video/304887422?autoplay=1
> > to download the video.
> 
> Doesn't work for me (video number changed)
> 
> ```
> $ youtube-dl "https://player.vimeo.com/video/1234567890?autoplay=1"
> [vimeo] 1234567890: Downloading webpage
> ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
> ```
did you try manually changing the 1234567890 number to 304887422 and then retry the download ??

**Comment by superian** [comment]
I didn't try with that one - which may well have worked for you - but turning a series of other

vimeo.com/123456789/0abcdef123

URLs into

player.vimeo.com/video/123456789?autoplay=1

all got that error message.

**Comment by october262** [comment]
> I didn't try with that one - which may well have worked for you - but turning a series of other
> 
> vimeo.com/123456789/0abcdef123
> 
> URLs into
> 
> player.vimeo.com/video/123456789?autoplay=1
> 
> all got that error message.

the way i was able to download this - https://player.vimeo.com/video/304887422?autoplay=1
was to play this -  https://vimeo.com/304887422/34c51f7a09 and add view-source: in front of
the https and found the video.

**Comment by superian** [comment]
I don't know why, but for me with this list of videos looking at the source for the URL - and it does end up being

player.vimeo.com/video/123456789

with obviously different 123etcs - and trying those doesn't work.

**Comment by october262** [comment]
> player.vimeo.com/video/123456789

with this link - player.vimeo.com/video/123456789
and this one - player.vimeo.com/video/123456789?autoplay=1
i get video does not exist.

**Comment by csillag** [comment]
Are there any developments around this? I am seeing this problem with more and more videos.
