### ISSUE TITLE
Add support for Youtube search results links

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#28422]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Guess this could be a nice addition to support search results links with the same behaviour pattern as for Mix playlists. Maybe just extract first 20-50.
I get it, that search result could be almost endless for some search cases.

Test link:
https://www.youtube.com/results?search_query=4k+gaming+clips

Currently resulting with this error: 
Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by afe2c3** [comment]
I am currently using a shell script to do this. This opens up potential for word splitting. This is a worthwhile addition.
