### ISSUE TITLE
Embedding subtitles --embed-subs converts .ass subtitle to srt?

### ISSUE THREAD

**Issue by erickyun** [ytdl-org/youtube-dl#28423]
Hi,

When I try to download a video with .ass subtitle yt-dl does convert it to .srt ?

How can I keep .ass subtitle format?

This is the command I did use and
[Here is the output verbose.](https://pastebin.com/raw/PvTUvVVR)

youtube-dl "URL" --cookies "cookies.txt" -f best --all-subs --write-sub --embed-subs

**Comment by remitamine** [comment]
use `--keep-video` option.

**Comment by erickyun** [comment]
> use `--keep-video` option.


İt doesn't work the embed subtitles are .srt again it still converts .ass files to .srt but the only difference is that .ass subtitles aren't deleted this time?

**Comment by remitamine** [comment]
mp4 format does not support embeding ssa/ass subtitles, so the subtitle needs to be converted before embedding in the mp4 file.

**Comment by erickyun** [comment]
> mp4 format does not support embedding ssa/ass subtitles, so the subtitle needs to be converted before embedding in the mp4 file.

So what command do I need to remux fast to mkv?
--merge-output-format mkv doesn't work?

**Comment by remitamine** [comment]
> So what command do I need to remux fast to mkv?

not currently supported, this problem has been already reported.

**Comment by erickyun** [comment]
> > So what command do I need to remux fast to mkv?
> 
> not currently supported, this problem has been already reported.

Ok I understand thank you for your help could you post the links of the topic this issue has been reported so that I can follow the problem?

**Comment by remitamine** [comment]
#17968

**Comment by erickyun** [comment]
I found solution `yt-dlp` does have `--remux mkv`🙂👍

https://github.com/yt-dlp/yt-dlp

**Comment by Marco-9456** [comment]
> I found solution [yt-dlp](https://github.com/yt-dlp/yt-dlp#:~:text=--remux-video%20FORMAT) does have `--remux mkv`🙂👍

`yt-dlp --remux-video mkv --sub-lang enUS --write-sub --embed-subs` this will work
