### ISSUE TITLE
Embedding subtitles converts .ass subtitle to srt?

### ISSUE THREAD

**Issue by erickyun** [ytdl-org/youtube-dl#28420]
Hi,

When I try to download a video with .ass subtitle yt-dl does convert it to .srt ?

How can I keep .ass subtitle format?

**Comment by erickyun** [comment]
> Hi,
> 
> When I try to download a video with .ass subtitle yt-dl does convert it to .srt ?

How can I keep .ass subtitle format?

**Comment by remitamine** [comment]
provide verbose output of the command that you're using.

**Comment by erickyun** [comment]
> provide verbose output of the command that you're using.

This is the command I did use and I had log.txt file but did delete it. I will download again and post it here.

I am noob so I will ask I need to use 2> log.txt for output verbose right?

youtube-dl "URL" --cookies "cookies.txt" -f best --all-subs --write-sub --embed-subs

**Comment by erickyun** [comment]
> provide verbose output of the command that you're using.

### Edit:
This is the command I did use and
[Here the output verbose.](https://pastebin.com/raw/PvTUvVVR)


youtube-dl "URL" --cookies "cookies.txt" -f best --all-subs --write-sub --embed-subs
