### ISSUE TITLE
archive what it doesn't download so that it doesn't have to read them each time it's ran?

### ISSUE THREAD

**Issue by Springs87** [ytdl-org/youtube-dl#28427]
so im using the following to download from YT and i'm wondering if there is a way to archive what it doesn't download so that the next time it runs it knows what it's missed and can hopefully run through quicker?

youtube-dl -i -o *destination* --format best --download-archive *path to file* --dateafter 20210301 *url to download*

**Comment by dstftw** [comment]
`--download-archive` archives only successful downloads by definition.
