### ISSUE TITLE
Audio is only available for the first 18 seconds - then audio is mute

### ISSUE THREAD

**Issue by franzgl** [ytdl-org/youtube-dl#28429]
Checklist

- [ x] I've verified that I'm running youtube-dl version 2021.03.03
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

I did find a similar bug #28410 but my ffmpeg works fine. So maybe Youtube has changed.

Verbose log
$ /usr/local/bin/youtube-dl --version
2021.03.03

$ /usr/local/bin/youtube-dl -v https://www.youtube.com/watch?v=v1ARjXpAWO0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=v1ARjXpAWO0']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 3.9.2 (CPython) - Linux-5.11.2-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] v1ARjXpAWO0: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r1---sn-uv2pm-ugoe.googlevideo.com/videoplayback?expire=1615590205&ei=3Z5LYPKLMYingQeA-pco&ip=212.77.51.183&id=o-ADT2PUamVfHq_lLMoXAh19y4AIJLPxNwLw5tOjj1jWCb&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=Cu&mm=31%2C29&mn=sn-uv2pm-ugoe%2Csn-1gieen7e&ms=au%2Crdu&mv=m&mvi=1&pl=20&initcwndbps=1280000&vprv=1&mime=video%2Fmp4&ns=bbr9qtqsAQhbGr6DrXAhAGgF&gir=yes&clen=641255076&dur=4947.141&lmt=1582701063410958&mt=1615568450&fvip=3&keepalive=yes&fexp=24001374%2C24007246&c=WEB&txp=5432432&n=9Impka0IgWoO26&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgJk77F6WXk32U3dXU0yzSt9icZ8N3owCQDqN8R-pI1-ACIQCffrs2xZNBxLNt-K1mce3fo-Hr344Lh2JmtvpexyHGng%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMvJ1DtcR4A-QVe0NiSOsBuMZ11Db-PhkAcgqIcE01RuAiBw7mMk3ayTTzLM6cc0Hz_7g7HqJxGDCdZQbfwUAlTpfQ%3D%3D'
[download] Destination: Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.f137.mp4
[download] 100% of 611.55MiB in 01:39
[debug] Invoking downloader on 'https://r1---sn-uv2pm-ugoe.googlevideo.com/videoplayback?expire=1615590205&ei=3Z5LYPKLMYingQeA-pco&ip=212.77.51.183&id=o-ADT2PUamVfHq_lLMoXAh19y4AIJLPxNwLw5tOjj1jWCb&itag=258&source=youtube&requiressl=yes&mh=Cu&mm=31%2C29&mn=sn-uv2pm-ugoe%2Csn-1gieen7e&ms=au%2Crdu&mv=m&mvi=1&pl=20&initcwndbps=1280000&vprv=1&mime=audio%2Fmp4&ns=bbr9qtqsAQhbGr6DrXAhAGgF&gir=yes&clen=238922980&dur=4947.242&lmt=1582745900646981&mt=1615568450&fvip=3&keepalive=yes&fexp=24001374%2C24007246&c=WEB&txp=5411222&n=9Impka0IgWoO26&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgdrniXhtf8yTPBuD6SLdWkwlLdO93h8Jls0oszR4l-lkCIFeMBhT-gACDr5Hr41ooacD70SHOCzE6qFvR_tSGQLbQ&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMvJ1DtcR4A-QVe0NiSOsBuMZ11Db-PhkAcgqIcE01RuAiBw7mMk3ayTTzLM6cc0Hz_7g7HqJxGDCdZQbfwUAlTpfQ%3D%3D'
[download] Destination: Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.f258.m4a
[download] 100% of 227.85MiB in 00:41
[ffmpeg] Merging formats into "Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.f137.mp4' -i 'file:Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.f258.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.temp.mp4'
Deleting original file Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.f137.mp4 (pass -k to keep)
Deleting original file Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.f258.m4a (pass -k to keep)

-----------------
The audio m4a is downloaded,  but you can only hear the first 18 seconds, than audio is muted.

Other Youtube videos are fine and you can hear audio.  But not with this one.

On Youtube you hear audio all the time - so something has changed.
You can easy test it on Youtube https://www.youtube.com/watch?v=v1ARjXpAWO0

**Comment by remitamine** [comment]
not a problem caused by youtube-dl, you can choose other audio formats other than `256` and `258`.

**Comment by franzgl** [comment]
$ /usr/local/bin/youtube-dl -v -F https://www.youtube.com/watch?v=v1ARjXpAWO0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.youtube.com/watch?v=v1ARjXpAWO0']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 3.9.2 (CPython) - Linux-5.11.2-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] v1ARjXpAWO0: Downloading webpage
[info] Available formats for v1ARjXpAWO0:
format code  extension  resolution note
249          webm       audio only tiny   50k , webm_dash container, opus @ 50k (48000Hz), 29.65MiB
250          webm       audio only tiny   65k , webm_dash container, opus @ 65k (48000Hz), 38.49MiB
251          webm       audio only tiny  128k , webm_dash container, opus @128k (48000Hz), 75.81MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 76.36MiB
256          m4a        audio only tiny  194k , m4a_dash container, mp4a.40.5@194k (24000Hz), 114.62MiB
258          m4a        audio only tiny  386k , m4a_dash container, mp4a.40.2@386k (48000Hz), 227.85MiB
160          mp4        256x144    144p   33k , mp4_dash container, avc1.4d400c@  33k, 30fps, video only, 19.77MiB
278          webm       256x144    144p   75k , webm_dash container, vp9@  75k, 30fps, video only, 44.73MiB
133          mp4        426x240    240p   60k , mp4_dash container, avc1.4d4015@  60k, 30fps, video only, 35.57MiB
242          webm       426x240    240p   80k , webm_dash container, vp9@  80k, 30fps, video only, 47.69MiB
243          webm       640x360    360p  146k , webm_dash container, vp9@ 146k, 30fps, video only, 86.62MiB
134          mp4        640x360    360p  150k , mp4_dash container, avc1.4d401e@ 150k, 30fps, video only, 88.51MiB
244          webm       854x480    480p  239k , webm_dash container, vp9@ 239k, 30fps, video only, 141.14MiB
135          mp4        854x480    480p  289k , mp4_dash container, avc1.4d401f@ 289k, 30fps, video only, 170.44MiB
247          webm       1280x720   720p  458k , webm_dash container, vp9@ 458k, 30fps, video only, 270.16MiB
136          mp4        1280x720   720p  544k , mp4_dash container, avc1.4d401f@ 544k, 30fps, video only, 320.85MiB
248          webm       1920x1080  1080p  885k , webm_dash container, vp9@ 885k, 30fps, video only, 522.15MiB
137          mp4        1920x1080  1080p 1036k , mp4_dash container, avc1.640028@1036k, 30fps, video only, 611.55MiB
18           mp4        640x360    360p  414k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 244.55MiB
22           mp4        1280x720   720p  673k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
---------------------------------
$ /usr/local/bin/youtube-dl -v -f 140 -f 137 https://www.youtube.com/watch?v=v1ARjXpAWO0 
--> did not work to get audio - will try different settings

**Comment by franzgl** [comment]
Download works fine on Windows 10 but does not work on Linux
--  Windows Log - File is smaller then on Linux
youtube-dl.exe --verbose  https://www.youtube.com/watch?v=v1ARjXpAWO0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=v1ARjXpAWO0']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] v1ARjXpAWO0: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r1---sn-uv2pm-ugoe.googlevideo.com/videoplayback?expire=1616426589&ei=_WFYYPnuJsOWgQfP2KqgBA&ip=212.77.51.183&id=o-AI36Y8quAwGetndJRNDrqjxktw50bEqpGitErubfUOcU&itag=22&source=youtube&requiressl=yes&mh=Cu&mm=31%2C29&mn=sn-uv2pm-ugoe%2Csn-1gieen7e&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=2202500&vprv=1&mime=video%2Fmp4&ns=n_k8a5cRKWPq38N50vdxhFAF&cnr=14&ratebypass=yes&dur=4947.197&lmt=1582701845399983&mt=1616404598&fvip=3&fexp=24001373%2C24007246&c=WEB&txp=5432432&n=_Bdy_kJTC_36ho35ac&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgYYdlJaNPWbxv9itShGcpUc6399Cg1JQ0OPvUGsBy96cCIQCP-87V5Ci-CzcWCJDEet5z61gfx4ZK-2tmJYrlRlSwWA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgZsH4c2XjFbZMD0-XZqiizvJ5YK_tBkXi0uPI1LIyms8CIQDFOrPo_L_dZ-G95Uj9-s6nVbB97Wg3slzB94DzuocJcQ%3D%3D'
[download] Destination: Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.mp4
[download] 100% of 396.90MiB in 02:54
------------  Linux log - 
$ youtube-dl --verbose https://www.youtube.com/watch?v=v1ARjXpAWO0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=v1ARjXpAWO0']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.9.2 (CPython) - Linux-5.11.6-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] v1ARjXpAWO0: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r1---sn-uv2pm-ugoe.googlevideo.com/videoplayback?expire=1616427846&ei=5mZYYOO5OdbrgAetk5aoBA&ip=212.77.51.183&id=o-AJf0wn0ZwhQh41FYsz4b0p_Ges0J_L1IM1YIq2BtU_wa&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=Cu&mm=31%2C29&mn=sn-uv2pm-ugoe%2Csn-1gieen7e&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=2142500&vprv=1&mime=video%2Fmp4&ns=1bF4G6wUBrxcLzYWhrUHxHsF&gir=yes&clen=641255076&dur=4947.141&lmt=1582701063410958&mt=1616406063&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5432432&n=aMLovyo2d713WUgod7&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOiSH8IvoyFfzHMQzF9k69JGIbhhi5s-IVy9o0q7tnOwAiEAmUCr3tqdjIRUvhoK3xFJR0lK5FfaKALqWM-ei5Lxj6Y%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgaJarxKFnU94NvIda4JpLHNG7e33QCKA959f1u8lZK2MCIDD7MA2Iq1xNm6Ckg5XO1Y3ZbsMntj9Os1Ad5-6VKGsr'
[download] Destination: Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.f137.mp4
[download] 100% of 611.55MiB in 01:38
[debug] Invoking downloader on 'https://r1---sn-uv2pm-ugoe.googlevideo.com/videoplayback?expire=1616427846&ei=5mZYYOO5OdbrgAetk5aoBA&ip=212.77.51.183&id=o-AJf0wn0ZwhQh41FYsz4b0p_Ges0J_L1IM1YIq2BtU_wa&itag=258&source=youtube&requiressl=yes&mh=Cu&mm=31%2C29&mn=sn-uv2pm-ugoe%2Csn-1gieen7e&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=2142500&vprv=1&mime=audio%2Fmp4&ns=1bF4G6wUBrxcLzYWhrUHxHsF&gir=yes&clen=238922980&dur=4947.242&lmt=1582745900646981&mt=1616406063&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5411222&n=aMLovyo2d713WUgod7&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJi22IQmiRldo42tRlfifmALVQTZH73AF-hXf0G2CC6IAiEAsUCL766wLTR5XFAWp89P2OOlqavCT9zy3mSmX9gfpbI%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgaJarxKFnU94NvIda4JpLHNG7e33QCKA959f1u8lZK2MCIDD7MA2Iq1xNm6Ckg5XO1Y3ZbsMntj9Os1Ad5-6VKGsr'
[download] Destination: Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.f258.m4a
[download] 100% of 227.85MiB in 00:35
[ffmpeg] Merging formats into "Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.f137.mp4' -i 'file:Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.f258.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.temp.mp4'
Deleting original file Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.f137.mp4 (pass -k to keep)
Deleting original file Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.f258.m4a (pass -k to keep)

**Comment by franzgl** [comment]
Downloading with lower resolution on Linux worked: Audio does not stop after 18 seconds.
------------------
$  /usr/local/bin/youtube-dl -v -f 22 https://www.youtube.com/watch?v=v1ARjXpAWO0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '22', 'https://www.youtube.com/watch?v=v1ARjXpAWO0']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.9.2 (CPython) - Linux-5.11.6-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] v1ARjXpAWO0: Downloading webpage
[debug] Invoking downloader on 'https://r1---sn-uv2pm-ugoe.googlevideo.com/videoplayback?expire=1616429279&ei=f2xYYLqGF82VgQenu6HYCw&ip=212.77.51.183&id=o-APn0IC14VuS984DW7ExwH5_kYhV9CgXLzrV6BPLqj-gX&itag=22&source=youtube&requiressl=yes&mh=Cu&mm=31%2C29&mn=sn-uv2pm-ugoe%2Csn-1gieen7e&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=1821250&vprv=1&mime=video%2Fmp4&ns=ol1kxv3CBjiQ2FWhsQr4iaUF&cnr=14&ratebypass=yes&dur=4947.197&lmt=1582701845399983&mt=1616407251&fvip=3&fexp=24001373%2C24007246&beids=23886213&c=WEB&txp=5432432&n=ziiEflRf-X5PcvewkZ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgYyL8ECKRJ_WrJ4TAkuCKH0RZUn6jWzBNFFwe4u__ZjUCIGn3ne2f0Jf7-Ggbr3pFHsI3Qq0gvkPB3likb0TDXkyq&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgB8b_FjpVtSlM9a0WrB6eBCU9fuq6_gP3c8JJ4gECnh8CIQDD6u8ZGj2T79nagpgP3n5j9r_HHMuImRqVLr4LTGodLw%3D%3D'
[download] Destination: Remote Viewing The Code Of Hammurabi  ( FULL DOCUMENTARY )-v1ARjXpAWO0.mp4
[download] 100% of 396.90MiB in 00:44
