### ISSUE TITLE
videodelivery.net - HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by prky** [ytdl-org/youtube-dl#28433]
Site used to work, but now doesn't.

Using youtube-dl version 2021.03.03, video plays fine in the browser, no special characters, can't see a similar issue listed.

youtube-dl reports 403 errors:

WARNING: Could not send HEAD request HTTP Error 403: Forbidden
and
ERROR: Unable to download webpage: HTTP Error 403: Forbidden

Full debug output attempting to download:

youtube-dl --verbose -r 1M -f 'bestvideo+bestaudio' -o 'videodelivery.%(ext)s' https://iframe.videodelivery.net/a184bc77dd28a5e27f13ffcccbffb48a
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-r', u'1M', u'-f', u'bestvideo+bestaudio', u'-o', u'videodelivery.%(ext)s', u'https://iframe.videodelivery.net/a184bc77dd28a5e27f13ffcccbffb48a']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-129-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[generic] a184bc77dd28a5e27f13ffcccbffb48a: Requesting header
WARNING: Could not send HEAD request to https://iframe.videodelivery.net/a184bc77dd28a5e27f13ffcccbffb48a: HTTP Error 403: Forbidden
[generic] a184bc77dd28a5e27f13ffcccbffb48a: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2275, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by remitamine** [comment]
post the original URL.

**Comment by prky** [comment]
Sent original URL and password via email.

**Comment by prky** [comment]
Issue resolved by using --add-header 'Referer: https://<original site URL>' no code change needed.

Thank you!
