### ISSUE TITLE
Youtube-Dl not correctly selecting best resolution mp4 video from YouTube video manifest

### ISSUE THREAD

**Issue by Videogamer555** [ytdl-org/youtube-dl#28432]
By default, when trying to download https://www.youtube.com/watch?v=X7kMP24N2UI it selects the best resolution video, but unfortunately it defaults to selecting the best resolution webm video (not mp4), so I try to force it to download the mp4 video with the "-f mp4" option. Now unfortunately it doesn't download the best resolution mp4 video, but rather the last one in the manifest (which it assumes will be the best resolution, but is not in this case).

Here's how to fix the issue. Make the program actually read the metadata in the manifest, and automatically select the video stream with highest resolution.

**Comment by remitamine** [comment]
read [FORMAT SELECTION](https://github.com/ytdl-org/youtube-dl#format-selection) documentation.
