### ISSUE TITLE
Rare 404 on Dailymotion

### ISSUE THREAD

**Issue by WDBell** [ytdl-org/youtube-dl#28444]
Video plays on Dailymotion. However, my attempt to download it had this result (repeatedly). I've used youtube-dl for this purpose many times.

`G:\Watch\The Gene Code (59)>youtube-dl --version
2021.03.14

G:\Watch\The Gene Code (59)>youtube-dl https://www.dailymotion.com/video/x14wrke --recode-video mp4
[dailymotion] Downloading Access Token
[dailymotion] x14wrke: Downloading media JSON metadata
[dailymotion] x14wrke: Downloading metadata JSON
[dailymotion] x14wrke: Downloading m3u8 information
ERROR: unable to download video data: HTTP Error 404: Not Found
`

**Comment by remitamine** [comment]
the best quality(608x336) is not playable in browser either, [select another format](https://github.com/ytdl-org/youtube-dl#format-selection).
