### ISSUE TITLE
ceskatelevize.cz - No video formats found ERROR 

### ISSUE THREAD

**Issue by nerusit** [ytdl-org/youtube-dl#28452]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
>>youtube-dl -v -F https://www.ceskatelevize.cz/ivysilani/11405990463-zlociny-velke-prahy/217512120200007-lepsi-zivot/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.ceskatelevize.cz/ivysilani/11405990463-zlociny-velke-prahy/217512120200007-lepsi-zivot/']
[debug] Encodings: locale cp1250, fs mbcs, out cp1250, pref cp1250
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffprobe 2021-01-27-git-149bfc2445-full_build-www.gyan.dev
[debug] Proxy map: {}
[CeskaTelevize] 217512120200007-lepsi-zivot: Downloading webpage
[CeskaTelevize] 217512120200007-lepsi-zivot: Downloading JSON metadata
[CeskaTelevize] 217512120200007-lepsi-zivot: Downloading JSON metadata
[CeskaTelevize] 217512120200007-lepsi-zivot: Downloading JSON metadata
[CeskaTelevize] 217512120200007-lepsi-zivot: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\ceskatelevize.py", line 201, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\common.py", line 1369, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update.
Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

This case seems to be similar or looks like to be maybe on the same basis as the issue reported couple of hours earlier here - the same error but just for different service / TV (iprima.cz) - for both valid -> same country -> .cz - maybe could be a clue... 
As I have just a general overall idea about this stuff - so take the following info so...
- actually I have no idea if the site 'ceskatelevize.cz' was knowingly targeted to work with ytdl or if it is and was just coincidence that it can be used with...
- I found that the video I downloaded last week can still be downloaded with no problem, but just newer ones seem to be like these are provided under some new service which is incompatible (concretely I am speaking about TV serial - new part broadcasted every Sunday and after that it become available on the web...)
- Firefox (otherwise using Chrome) asked me to allow (switch ON) DRM which I know I switched OFF before when I tried to play it with it to see if I can grab it from its cash as it was easily possible at former times (unlike with Chrome at the same), however I can not tell you if the 'DRM' was anyhow involved before, i.e. in case of the 'not so new' videos which is still possible to download today as I am not fan of DRM at all... 
- this is the link showed by (Nirsoft's) VideoCachViewer from where the 'fragments/chunks' of stream were downloaded to its cash (I have no idea why there is the part before the 'https://...')
- https%2Cceskatelevize.cz%29,a,:https://ivys-vst07-6.o2tv.cz/aa/576f3ea411beb1871c30381ba800078c/1615814455189/ad0f27264e557417e3ed6c4bfc888302e/dwv-61924494877857993-pc/1001-1506/IS.mp4
- and last note - web "ceskatelevize.cz" apply territory restriction sometimes- as the above issued link is for the stuff they produced themselves than maybe OK,  otherwise needless to say - perhaps VPN service could solve that...

**Comment by xmstspider** [comment]
>     * Firefox (otherwise using Chrome) asked me to allow (switch ON) DRM which I know I switched OFF before when I tried to play it with it to see if I can grab it from its cash as it was easily possible at former times (unlike with Chrome at the same), however I can not tell you if the 'DRM' was anyhow involved before, i.e. in case of the 'not so new' videos which is still possible to download today as I am not fan of DRM at all...

Good catch, I tested on my FF and it shows DRM icon for part 7 but not for part 6 and below. The icon says 'Some audio or video parts may use DRM...'
In that case is the error could be misleading and it should show the DRM error instead of 'No video formats found' error.

**Comment by mihula** [comment]
Have similar issue with very current version 2021.03.14 and strange is that same series one episode is targetable by youtube-dl and another one not (both episodes are currently playable via web page)

this works as charm
`youtube-dl.exe --verbose https://www.ceskatelevize.cz/ivysilani/11405990463-zlociny-velke-prahy/217512120200006`

```
c:\Tools\youtube-dl>youtube-dl.exe --verbose https://www.ceskatelevize.cz/ivysilani/11405990463-zlociny-velke-prahy/217512120200006
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.ceskatelevize.cz/ivysilani/11405990463-zlociny-velke-prahy/217512120200006']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[CeskaTelevize] 217512120200006: Downloading webpage
[CeskaTelevize] 217512120200006: Downloading JSON metadata
[CeskaTelevize] 217512120200006: Downloading JSON metadata
[CeskaTelevize] 217512120200006: Downloading MPD manifest
[CeskaTelevize] 217512120200006: Downloading MPD manifest
[CeskaTelevize] 217512120200006: Downloading JSON metadata
[CeskaTelevize] 217512120200006: Downloading JSON metadata
[CeskaTelevize] 217512120200006: Downloading m3u8 information
[CeskaTelevize] 217512120200006: Downloading m3u8 information
[download] Downloading playlist: Zločiny Velké Prahy: Zmizelá
[CeskaTelevize] playlist Zločiny Velké Prahy: Zmizelá: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://ivys-vst14-2.o2tv.cz/af/34156fa40d16ae37eda2d659a8e7724c/1615899799767/a312928fbb33efe6643c87df641838a15/dna-61924494877853541-pc/61924494877853349/1506v1002.k.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 393
[download] Destination: Zločiny Velké Prahy - Zmizelá-61924494877853541.mp4
[download]   0.4% of ~2.89GiB at  7.20MiB/s ETA 06:05
ERROR: Interrupted by user
```


this fails on `youtube_dl.utils.ExtractorError: No video formats found`
`youtube-dl.exe --verbose https://www.ceskatelevize.cz/ivysilani/11405990463-zlociny-velke-prahy/217512120200007`

```
c:\Tools\youtube-dl>youtube-dl.exe --verbose https://www.ceskatelevize.cz/ivysilani/11405990463-zlociny-velke-prahy/217512120200007
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.ceskatelevize.cz/ivysilani/11405990463-zlociny-velke-prahy/217512120200007']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[CeskaTelevize] 217512120200007: Downloading webpage
[CeskaTelevize] 217512120200007: Downloading JSON metadata
[CeskaTelevize] 217512120200007: Downloading JSON metadata
[CeskaTelevize] 217512120200007: Downloading JSON metadata
[CeskaTelevize] 217512120200007: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\ceskatelevize.py", line 201, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\common.py", line 1369, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
>CeskaTelevize] 217512120200007-lepsi-zivot: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl

Typical playlist item:
```
https://ivys-cdn.o2tv.cz/cdn/uri/get/?token=873a7eeddd110784c6f830c91e1dddb567060ab4&contentType=vod&drmOnly=true&expiry=1646416538&id=61924494877857993&playerType=dash&quality=web&region=1&skipIpAddressCheck=false&userId=35aed439-2ead-4f88-aa32-ec037043a7bc&encryption=wv
```
Note `drmOnly=true`.
