### ISSUE TITLE
torsocks error

### ISSUE THREAD

**Issue by gl86** [ytdl-org/youtube-dl#28451]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hi, i am trying to use youtube-dl with torsocks to allow myself to download videos anonymously.  However i can not get it to work. What is the correct way to do so? thanks

**Comment by dstftw** [comment]
`--proxy socks5://...`

**Comment by gl86** [comment]
thanks it works using installed tor service, but hangs in case of tails OS. Is that normal?

**Comment by gl86** [comment]
I used ip address and port provided in torrc file
