### ISSUE TITLE
Please add a switch to trim filename to specific character count

### ISSUE THREAD

**Issue by ns-studios** [ytdl-org/youtube-dl#28465]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.03.14**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
If you try to download a file that's over 250 characters, the download will fail, so can you please add a switch that would trim the file name (excluding the extension) to a specific amount of characters to prevent this from happening?
E.g., --trim-filename 7 to trim, e.g., this is the original filename.mp4 to this is.mp4
Certain forks have already done this
(https://github.com/blackjack4494/youtube-dlc/issues/85), so maybe it can even be carried over, but it would mean a loooot.

**Comment by garoto** [comment]
`--output "%(title).7s.%(ext)s"`

**Comment by ns-studios** [comment]
@garoto Thank you so so so much! I've always wanted this, but didn't realize it was there all along.

**Comment by garoto** [comment]
It's part of Python's string manipulation arsenal btw, not a yt-dl specific functionality. Not straightforward to stumble upon.

**Comment by ns-studios** [comment]
Good to know. :)
Can you explain what the “.” does in .7s?
Does it tell it to match until it sees a “.” character and to match only upto x number of characters?
I did look at the Python string formatting page, but it was kind of confusing (and I do know a bit of Python, but I've never used formatting like that).
Are there any other examples you can think of that could be useful?
I know you can pad numbers like %(number)03d, etc.

**Comment by rautamiekka** [comment]
> Good to know. :)
> Can you explain what the “.” does in .7s?
> Does it tell it to match until it sees a “.” character and to match only upto x number of characters?
> I did look at the Python string formatting page, but it was kind of confusing (and I do know a bit of Python, but I've never used formatting like that).
> Are there any other examples you can think of that could be useful?
> I know you can pad numbers like %(number)03d, etc.

https://docs.python.org/3/library/stdtypes.html#old-string-formatting explains the dot as
```
5. Precision (optional), given as a '.' (dot) followed by the precision. If specified as '*' (an asterisk), the actual precision is read from the next element of the tuple in values, and the value to convert comes after the precision.
```
So yeah, the `.7s` means the incoming value is **convert**ed **into string max 7 chars long**.

**Comment by ns-studios** [comment]
Thank you @rautamiekka for the clarification and examples.
