### ISSUE TITLE
[youtube] Unable to download age-gated videos.

### ISSUE THREAD

**Issue by Rudbekia** [ytdl-org/youtube-dl#28468]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

non Cookies set.
```
C:\Users\PC\Downloads>youtube-dl iMJ6BNYipv0 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['iMJ6BNYipv0', '-v']
[debug] Encodings: locale cp949, fs utf-8, out utf-8, pref cp949
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.9.2 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] iMJ6BNYipv0: Downloading webpage
[youtube] iMJ6BNYipv0: Refetching age-gated info webpage
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
Traceback (most recent call last):
  File "c:\private\python3.9.2\lib\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "c:\private\python3.9.2\lib\site-packages\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "c:\private\python3.9.2\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\private\python3.9.2\lib\site-packages\youtube_dl\extractor\youtube.py", line 1658, in _real_extract
    raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: Sign in to confirm your age
This video may be inappropriate for some users.
```

Cookies set.
```
C:\Users\PC\Downloads>youtube-dl --cookies cookies.txt iMJ6BNYipv0 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', 'iMJ6BNYipv0', '-v']
[debug] Encodings: locale cp949, fs utf-8, out utf-8, pref cp949
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.9.2 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] iMJ6BNYipv0: Downloading webpage
ERROR: This video may be inappropriate for some users.
Traceback (most recent call last):
  File "c:\private\python3.9.2\lib\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "c:\private\python3.9.2\lib\site-packages\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "c:\private\python3.9.2\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\private\python3.9.2\lib\site-packages\youtube_dl\extractor\youtube.py", line 1658, in _real_extract
    raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: This video may be inappropriate for some users.
```

## Description

If set cookies or not, will get this error.

**Comment by nicolaasjan** [comment]
Do you live in the European Union?
I got this issue as well and cookies didn't work either...
YouTube now [demands](https://blog.youtube/news-and-events/using-technology-more-consistently-apply-age-restrictions) that you verify your age with a credit card or ID.

See also:
https://reddit.com/r/privacy/comments/kl3j1o/what_the_actual_hell_youtube_now_wants_id_or/

I got around it with a [user script](https://greasyfork.org/nl/scripts/407977-yt-redirect-to-invidious-on-login-request/code) that redirects me to [Invideous](https://invidious.snopyta.org) and use that [URL](https://invidious.snopyta.org/watch?v=iMJ6BNYipv0) to download the video.

**Comment by Rudbekia** [comment]
No, I live in Asia.
As I try now, There are also a few age-restricted videos available for download.
So it probably isn't a problem on the YouTube side.

**Comment by october262** [comment]
> No, I live in Asia.
> As I try now, There are also a few age-restricted videos available for download.
> So it probably isn't a problem on the YouTube side.

if you're signed in to your youtube acount, then the cookies txt file should work

**Comment by Rudbekia** [comment]
> if you're signed in to your youtube acount, then the cookies txt file should work
Looking at the log. I already did it. and not work.

**Comment by Rudbekia** [comment]
Anyone can download the video from the log? 
If there is, it would be my environmental problem.

**Comment by october262** [comment]
> Anyone can download the video from the log?
> If there is, it would be my environmental problem.

had no issues downloading - https://www.youtube.com/watch?v=iMJ6BNYipv0

**Comment by Rudbekia** [comment]
> had no issues downloading - https://www.youtube.com/watch?v=iMJ6BNYipv0

That's weird.  I still can't download it.

**Comment by angentanewbe** [comment]
> > had no issues downloading - https://www.youtube.com/watch?v=iMJ6BNYipv0
> 
> That's weird.  I still can't download it.

try downloading without cookies also try with a new account cookies maybe there is some problem with old account.

**Comment by Rudbekia** [comment]
> try downloading without cookies also try with a new account cookies maybe there is some problem with old account.

Not working. but works on youtube-dl 2021.01.24.1.
and also not working on 2021.02.04
I don't know the difference between the two.

**Comment by dstftw** [comment]
Most likely expired cookies.

**Comment by nicolaasjan** [comment]
I _can_ reproduce (location: The Netherlands) with a fresh `cookies.txt`

```
ytd -v https://www.youtube.com/watch?v=iMJ6BNYipv0
[debug] System config: []
[debug] User config: ['-i', '-o', '/dev/shm/test-ytd/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--no-mtime', '--add-metadata', '--embed-thumbnail', '--force-ipv4', '--cookies', '/home/nico/.config/youtube-dl/cookies.txt', '--external-downloader', 'aria2c', '--external-downloader-args', '-x 10 -s 10 -j 10 -k 1M --log-level=info --file-allocation=none']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=iMJ6BNYipv0']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.6.9 (CPython) - Linux-5.4.0-67-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg N-101396-ga272f38-Nico-20210306, ffprobe N-101396-ga272f38-Nico-20210306
[debug] Proxy map: {}
[youtube] iMJ6BNYipv0: Downloading webpage
ERROR: Je leeftijd verifiëren
Voer een korte controle uit om aan te tonen dat u oud genoeg bent om deze video te bekijken. Meer informatie
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl.orig/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl.orig/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl.orig/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl.orig/youtube_dl/extractor/youtube.py", line 1658, in _real_extract
    raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: Je leeftijd verifiëren
Voer een korte controle uit om aan te tonen dat u oud genoeg bent om deze video te bekijken. Meer informatie

```
Translated:

`youtube_dl.utils.ExtractorError: Verify your age Please do a quick check to show that you are old enough to watch this video. More information`

See also:
https://support.google.com/accounts/answer/1333913?hl=en

**Comment by angentanewbe** [comment]
> 
> 
> I _can_ reproduce (location: The Netherlands) with a fresh `cookies.txt`
> 
> ```
> ytd -v https://www.youtube.com/watch?v=iMJ6BNYipv0
> [debug] System config: []
> [debug] User config: ['-i', '-o', '/dev/shm/test-ytd/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--no-mtime', '--add-metadata', '--embed-thumbnail', '--force-ipv4', '--cookies', '/home/nico/.config/youtube-dl/cookies.txt', '--external-downloader', 'aria2c', '--external-downloader-args', '-x 10 -s 10 -j 10 -k 1M --log-level=info --file-allocation=none']
> [debug] Custom config: []
> [debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=iMJ6BNYipv0']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2021.03.14
> [debug] Python version 3.6.9 (CPython) - Linux-5.4.0-67-generic-x86_64-with-LinuxMint-19.3-tricia
> [debug] exe versions: ffmpeg N-101396-ga272f38-Nico-20210306, ffprobe N-101396-ga272f38-Nico-20210306
> [debug] Proxy map: {}
> [youtube] iMJ6BNYipv0: Downloading webpage
> ERROR: Je leeftijd verifiëren
> Voer een korte controle uit om aan te tonen dat u oud genoeg bent om deze video te bekijken. Meer informatie
> Traceback (most recent call last):
>   File "/usr/local/bin/youtube-dl.orig/youtube_dl/YoutubeDL.py", line 806, in wrapper
>     return func(self, *args, **kwargs)
>   File "/usr/local/bin/youtube-dl.orig/youtube_dl/YoutubeDL.py", line 827, in __extract_info
>     ie_result = ie.extract(url)
>   File "/usr/local/bin/youtube-dl.orig/youtube_dl/extractor/common.py", line 534, in extract
>     ie_result = self._real_extract(url)
>   File "/usr/local/bin/youtube-dl.orig/youtube_dl/extractor/youtube.py", line 1658, in _real_extract
>     raise ExtractorError(reason, expected=True)
> youtube_dl.utils.ExtractorError: Je leeftijd verifiëren
> Voer een korte controle uit om aan te tonen dat u oud genoeg bent om deze video te bekijken. Meer informatie
> ```
> 
> Translated:
> 
> `youtube_dl.utils.ExtractorError: Verify your age Please do a quick check to show that you are old enough to watch this video. More information`
> 
> See also:
> https://support.google.com/accounts/answer/1333913?hl=en

youtube-dl --cookies="1.txt" https://www.youtube.com/watch?v=iMJ6BNYipv0
[youtube] iMJ6BNYipv0: Downloading webpage
WARNING: video doesn't have subtitles
WARNING: unable to extract xsrf token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[info] Writing video description to: Saas Bina Sasuraal - Episode 372 - 2nd July 2012-iMJ6BNYipv0-656x480-25-20120702-135+140-SET India-UCpEhnqL0y41EpW2TvWAHD7Q.description
WARNING: There are no annotations to write.
[info] Writing video description metadata as JSON to: Saas Bina Sasuraal - Episode 372 - 2nd July 2012-iMJ6BNYipv0-656x480-25-20120702-135+140-SET India-UCpEhnqL0y41EpW2TvWAHD7Q.info.json
[youtube] iMJ6BNYipv0: Downloading thumbnail ...
[youtube] iMJ6BNYipv0: Writing thumbnail to: Saas Bina Sasuraal - Episode 372 - 2nd July 2012-iMJ6BNYipv0-656x480-25-20120702-135+140-SET India-UCpEhnqL0y41EpW2TvWAHD7Q.jpg
[download] Destination: Saas Bina Sasuraal - Episode 372 - 2nd July 2012-iMJ6BNYipv0-656x480-25-20120702-135-SET India-UCpEhnqL0y41EpW2TvWAHD7Q.f135.mp4
[download]   3.8% of 80.84MiB at 470.84KiB/s ETA 02:49

**Comment by angentanewbe** [comment]
It seems your youtube account birth date makes it under 18 years age. Thats why error "Verify your age Please do a quick check to show that you are old enough to watch this video" is shown. Try using another youtube account with 18+ age (choose birth date accordingly).

**Comment by nicolaasjan** [comment]
> It seems your youtube account birth date makes it under 18 years age. Thats why error "Verify your age Please do a quick check to show that you are old enough to watch this video" is shown. Try using another youtube account with 18+ age (choose birth date accordingly).

My account birth date is already in 1955 (not a lie)...
I guess that makes me old enough. Haha.

**Comment by angentanewbe** [comment]
> 
> 
> > It seems your youtube account birth date makes it under 18 years age. Thats why error "Verify your age Please do a quick check to show that you are old enough to watch this video" is shown. Try using another youtube account with 18+ age (choose birth date accordingly).
> 
> My account birth date is already in 1955 (not a lie)...
> I guess that makes me old enough. Haha.
> 
> And I think - since I'm in the EU - I'll have to prove my age for a new account with my ID or credit card info. Not gonna do that of course.

Lol. 
The video that you are trying to download is of an Indian channel and It is possible that they set the video only for some countries like India and its neighbours. I live in India and so I can download the video. you can try to change country to India in your youtube account and download the video by new cookies.

**Comment by nicolaasjan** [comment]
> Lol.
> The video that you are trying to download is of an Indian channel and It is possible that they set the video only for some countries like India and its neighbours. I live in India and so I can download the video. you can try to change country to India in your youtube account and download the video by new cookies.

I don't really need this video; it's a test case.
But in the past I was able to bypass this by downloading via [Tor](https://www.torproject.org/) with this option:

`--proxy socks5://127.0.0.1:9150/`

and setting my exit node to India and putting this in the `torrc` file:

```
# ExitNodes {IN}
# StrictNodes 1

```
