### ISSUE TITLE
Put origin URL in file metadata

### ISSUE THREAD

**Issue by blackbit42** [ytdl-org/youtube-dl#28478]
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.03.14**
- [x] I've searched the bugtracker for similar feature requests including closed ones

Feature-request:

Please consider to put the origin URL of a video into the metadata of the resulting file.
This is useful for back-reference a video that is on local storage to its origin.

**Comment by pukkandan** [comment]
It is embedded in the `purl` field in mkv
mp4 however does not support this field
