### ISSUE TITLE
Youtube too many requests

### ISSUE THREAD

**Issue by austinsoft** [ytdl-org/youtube-dl#28472]
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.03.14**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://youtu.be/KFvZg7KCSUY']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-67-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

## Description

WRITE DESCRIPTION HERE
Fails on all youtube videos with too many requests. I have tried closing the video page before trying to download, but it makes no difference

**Comment by bhushankumarl** [comment]
Facing the same...

**Comment by shoxie007** [comment]
My explanation: If you download too many videos from Youtube in any single day, or rather send too many webpage requests, let's say around 3,000 requests, Youtube issues you an IP ban which lasts for about 4 days if I remember correctly. I think your browser might still work, but not Youtube-DL. How many videos did you download before getting this message? You have to stay below a certain daily threshold in order to avoid an IP ban. Or alternatively, split your downloads between IPV6 and IPV4 with options --force-ipv4 and the default IPV6.

**Comment by pukkandan** [comment]
https://github.com/ytdl-org/youtube-dl/issues/23638
