### ISSUE TITLE
Support Twitter subtitle

### ISSUE THREAD

**Issue by xmha97** [ytdl-org/youtube-dl#28476]
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running youtube-dl version **2021.03.14**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Please support Twitter subtitle.
I can't download subtitle of below video:
https://twitter.com/NikkiMcR/status/1371620830015332355

**Comment by remitamine** [comment]
the subtitle is part of the stream(video file), and it can be enabled on any player that supports this type of subtitles(ex: vlc/mpv).

**Comment by xmha97** [comment]
No, the subtitle isn't part of the stream.
![Twitter](https://user-images.githubusercontent.com/23485114/111894954-68677b00-8a24-11eb-9e2b-727f8a07dea5.png)

**Comment by remitamine** [comment]
i didn't mean it's hardsubbed, it's embeded in every format, you can look online about this type of subtitles and the players that support it(CEA-608/708).
