### ISSUE TITLE
[not working] livestorm.co Download

### ISSUE THREAD

**Issue by aviationsteve** [ytdl-org/youtube-dl#28487]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.03.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://app.livestorm.co/jahr-top-special-verlag-gmbh-co-kg/fliegermagazin-winterakademie-iv-fliegen-auf-kurzen-und-unbefestigten-pisten/
- Single video: ---
- Playlist: ---

## Description

Video download not possible, content provider just told me to use a "video downloader" tool...
Error Message:
WARNING: Could not send HEAD request to https://app.livestorm.co/jahr-top-special-verlag-gmbh-co-kg/fliegermagazin-winterakademie-iv-fliegen-auf-kurzen-und-unbefestigten-pisten: HTTP Error 404: Not Found
[generic] fliegermagazin-winterakademie-iv-fliegen-auf-kurzen-und-unbefestigten-pisten: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Error Message Verbose mode:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://app.livestorm.co/jahr-top-special-verlag-gmbh-co-kg/fliegermagazin-winterakademie-iv-fliegen-auf-kurzen-und-unbefestigten-pisten', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-03-03-git-4dc039b4c7-essentials_build-www.gyan.dev, ffprobe 2021-03-03-git-4dc039b4c7-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[generic] fliegermagazin-winterakademie-iv-fliegen-auf-kurzen-und-unbefestigten-pisten: Requesting header
WARNING: Could not send HEAD request to https://app.livestorm.co/jahr-top-special-verlag-gmbh-co-kg/fliegermagazin-winterakademie-iv-fliegen-auf-kurzen-und-unbefestigten-pisten: HTTP Error 404: Not Found
[generic] fliegermagazin-winterakademie-iv-fliegen-auf-kurzen-und-unbefestigten-pisten: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp8z3w9mz6\build\youtube_dl\YoutubeDL.py", line 2279, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

I hope this helps!

Checked with Chrome browser, video link can be found in code as far as I was able to check it.

Thanks!

Best,
Steve

**Comment by dstftw** [comment]
>HTTP Error 404: Not Found
