### ISSUE TITLE
Youtube-DL error with Vimeo Showcase downloads

### ISSUE THREAD

**Issue by SleepyHollowKM** [ytdl-org/youtube-dl#28486]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.03.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v https://vimeo.com/showcase/3717822

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://vimeo.com/showcase/3717822']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.14
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo:album] 3717822: Downloading JSON metadata
[vimeo:album] 3717822: Downloading JSON metadata
[download] Downloading playlist: 2018
[vimeo:album] 3717822: Downloading page 1
[vimeo:album] 3717822: Downloading page 2
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

## Description

Hi, I've been using Youtube-Dl to download Vimeo showcases (playlists) just fine. But suddenly after doing about 20 big batches, it no longer works. I am using the 3.14 latest version. Thanks for any help!

**Comment by SleepyHollowKM** [comment]
Help! I don't know what any of this means, so the linked references aren't helping me decipher this. I'm not a coder, just trying to download videos... Thanks

**Comment by Vangelis66** [comment]
... If you're not a coder then, **you should just wait for the next **official** release** of `yt-dl`, which should be imminent (but an exact date isn't set, of course...). 

BTW, posting a [support comment](https://github.com/ytdl-org/youtube-dl/commit/7e79ba7dd6e6649dd2ce3a74004b2044f2182881#commitcomment-48497016) under **code commits** is a big **faux-pas**, unless you are yourself an experienced Python coder (which you ain't, by your own admission) and have meaningful content/remarks to add with regard to that specific code committed... **Don't do it ever again**!

I can't help you myself, I am on Windows with close to 0 experience on Macs, but it should be possible to **run** `yt-dl` **from latest source** on a Mac; just ask on an Apple community/search on-line how to... Else, be patient for a few days; is that vimeo content you're so keen on about to vanish, say, tomorrow?

**Comment by SleepyHollowKM** [comment]
excuse me, thought I was just commenting under my own Issue I posted. I'll wait for a new release.
