### ISSUE TITLE
cant download dash stream from this site

### ISSUE THREAD

**Issue by u4113057** [ytdl-org/youtube-dl#28498]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.03.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

## Description

WRITE DESCRIPTION HERE

https://load1.v2h-cdn.com/redirect/prod_mvhub_v2/_definst_/path1/V2H_TVBCS0099/mp4:V2H_TVBCS0099_ep1_3.mp4?type=dash
 result always like this
[generic] mp4:V2H_TVBCS0099_ep15_3: Requesting header
[redirect] Following redirect to https://edge2a.v2h-cdn.com/prod_mvhub_v2/_definst_/path1/V2H_TVBCS0099/mp4:V2H_TVBCS0099_ep15_3.mp4/manifest.mpd
[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

if i download this manifest.mpd inside it tellls the video and audio stream but youtube-dl couldn't detect it.
the link can be played correctly on VLC.

youtube-dl version is 2021.03.14

**Comment by dstftw** [comment]
>HTTP ERROR 403
