### ISSUE TITLE
output-na-placeholder with templates

### ISSUE THREAD

**Issue by TWART016** [ytdl-org/youtube-dl#28502]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.03.14**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I have the following output template:
-o "%(playlist_title)s/%(track)s (%(artist)s).%(ext)s"

Somethimes the track or artist is "NA". 

With --output-na-placeholder it is possible to replace the string but not with a template e.g. %(title)s.

If multiple videos inside a playlist have "NA" they will be overwritten

**Comment by dstftw** [comment]
This is expected behavior. If you need some template sequence you must include it in output template itself not in NA placeholder.

**Comment by TWART016** [comment]
Some have the track and artist tags, some do not.

If there is more than 1 video with NA in the playlist, they will be overwritten. 

If I take the title in the template, there is too much info in the title.

Therefore template variables in NA placeholder would be helpful.
