### ISSUE TITLE
Playlist is not recognized

### ISSUE THREAD

**Issue by Naivek** [ytdl-org/youtube-dl#28504]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

--

I am tying to download the playlist - youtube-dl "https://www.youtube.com/playlist?list=PLVqBLRhC9UzGc3nhiI6EwVphbzU5JKGaz" but it is not recognizing. Is there a particular option that I should provide?

Thanks

**Comment by Naivek** [comment]
Hello @remitamine - could you please share what information that would need to look at this? I am basically new to this tool and trying my way to figure out how to download a playlist like the one above? Appreciate your help! Thanks!

**Comment by remitamine** [comment]
fill the proper issue template([Broken site support](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=)).
