### ISSUE TITLE
New option to not use the provided proxy when downloading video

### ISSUE THREAD

**Issue by masoudkazemi** [ytdl-org/youtube-dl#28519]
## Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2021.03.14**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

As you know, downloading large videos over proxy is slow.
Also, sometimes we needed the proxy when downloading webpages to avoid issues like "429 Too Many Requests".
So I suggest a new option to not use the provided proxy when downloading the video.

**Comment by dstftw** [comment]
`--proxy ""`.

**Comment by masoudkazemi** [comment]
Ok. but I meant like passing the proxy which should just be used for URL extracting (downloading webpage) and not when downloading the video.
I described one situation that the option is needed. situation: frist we need to use proxy to avoid 429 error, second we do not want actual video get downloaded over proxy because of slowness.

FYI: already I'm doing it manually. I extract download URLs with youtube-dl using proxy, and then I run myself some downloader to download them.
