### ISSUE TITLE
Download Videos from UK division of Discovery+?

### ISSUE THREAD

**Issue by Danker1990** [ytdl-org/youtube-dl#28511]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

The US division of discovery+ makes you have a paid license and links are easily grabbable from the url however the UK division has a free section however the URL relating to the vids are hidden away in the coding of the website. how can you grab them plus critically can these be downloaded if grabbed correctly.

**Comment by dirkf** [comment]
You might like to suggest some test URLs ...
