### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Giuseh** [ytdl-org/youtube-dl#28525]
## Checklist

- [+ ] I'm asking a question
- [ +] I've looked through the README and FAQ for similar questions
- [ +] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, in this [site](https://ytdl-org.github.io/youtube-dl/supportedsites.html) it's written that spotify is supported but when i try to download the song it gives me that error:
![image](https://user-images.githubusercontent.com/42472165/112221018-3b36ea80-8c27-11eb-8bb3-0863349a738a.png)

**Comment by dstftw** [comment]
Only episodes are supported.

**Comment by Giuseh** [comment]
what do you mean with spotify episodes?
