### ISSUE TITLE
With wget and curl downloaded versions of  2021.03.25 don't work, compiled version works

### ISSUE THREAD

**Issue by jk-ytdl** [ytdl-org/youtube-dl#28539]
I'm reporting a broken site support
I've verified that I'm running youtube-dl version 2021.03.25
I've checked that all provided URLs are alive and playable in a browser
I've checked that all URLs and arguments with special characters are properly quoted or escaped
I've searched the bugtracker for similar issues including closed ones

I have downloaded Version 2021.03.25 with curl and with wget. Both versions have the 256sum 9334117f86308b8659bbecda6ab06955da8734f975d28c39f3f2fed3f60354aa.

With both versions I get:
"/usr/local/bin/youtube-dl.curl --verbose https://www.ardmediathek.de/video/serien/hr-fernsehen/Y3JpZDovL2hyLW9ubGluZS8xMzA5OTg/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.ardmediathek.de/video/serien/hr-fernsehen/Y3JpZDovL2hyLW9ubGluZS8xMzA5OTg/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.25
[debug] Python version 2.7.16 (CPython) - Linux-4.9.0-13-amd64-x86_64-with-debian-10.8
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 53.86.169.55 (DE) as X-Forwarded-For.
[ARD:mediathek] Y3JpZDovL2hyLW9ubGluZS8xMzA5OTg: Downloading webpage
ERROR: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl.curl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl.curl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl.curl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl.curl/youtube_dl/extractor/ard.py", line 236, in _real_extract
    r'/play/(?:config|media)/(\d+)', webpage, 'media id')
  File "/usr/local/bin/youtube-dl.curl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

youtube-dl.wget -U
youtube-dl is up-to-date (2021.03.25)

youtube-dl.curl -U
youtube-dl is up-to-date (2021.03.25)

I have compiled youtube-dl from,
2,0M -rw-r--r--  1 kn kn 2,0M Mär 24 20:53  youtube-dl-master.zip
this compiled version gives me:

youtube-dl -U
youtube-dl is up-to-date (2021.03.25)

/usr/local/bin/youtube-dl --verbose https://www.ardmediathek.de/video/serien/hr-fernsehen/Y3JpZDovL2hyLW9ubGluZS8xMzA5OTg/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.ardmediathek.de/video/serien/hr-fernsehen/Y3JpZDovL2hyLW9ubGluZS8xMzA5OTg/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.25
[debug] Python version 2.7.16 (CPython) - Linux-4.9.0-13-amd64-x86_64-with-debian-10.8
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 53.223.144.99 (DE) as X-Forwarded-For.
[ARDBetaMediathek] Y3JpZDovL2hyLW9ubGluZS8xMzA5OTg: Downloading JSON metadata
[ARDBetaMediathek] 87609206: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://hrardmediathek-vh.akamaihd.net/i/video/as/allgemein/2021_03/hrLogo_210324111505_144503_13832732_,960x540-50p-1800,1920x1080-50p-8000,1280x720-50p-5000,640x360-25p-1000,512x288-25p-500,480x270-25p-250,320x180-12p-125,kbit.mp4.csmil/index_1_av.m3u8?null=0'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 152
[download] Destination: Privatdetektiv Frank Kross (13)-87609206.mp4
[download] 100% of 1.31GiB in 06:06
[debug] ffmpeg command line: ffprobe -show_streams 'file:Privatdetektiv Frank Kross (13)-87609206.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Privatdetektiv Frank Kross (13)-87609206.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Privatdetektiv Frank Kross (13)-87609206.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:Privatdetektiv Frank Kross (13)-87609206.temp.mp4'

**Comment by dirkf** [comment]
Have you tried 2021.04.07? The version that you built is using a different ARD extractor that may not have been in the 2021.03.25 version.

**Comment by remitamine** [comment]
example URLs are no longer accessible, new videos are working fine with the latest version.
