### ISSUE TITLE
ERROR: YouTube said: This video is unavailable.

### ISSUE THREAD

**Issue by with0out** [ytdl-org/youtube-dl#2853]
"youtube-dl https://www.youtube.com/watch?v=nGtLgKjFRKc
[youtube] Setting language
[youtube] nGtLgKjFRKc: Downloading webpage
[youtube] nGtLgKjFRKc: Downloading video info webpage
ERROR: YouTube said: This video is unavailable."

I have no problem streaming this particular video in browser, but youtube-dl keep on telling me that error. Very strange, a fix maybe?
Thanks!

**Comment by dufferzafar** [comment]
Having same error on this video too: https://www.youtube.com/watch?v=M7GfN3KU_S4

**Comment by yan12125** [comment]
The original video posted by @with0out can be downloaded now.

@dufferzafar This video is available in India only. Are you in India? And did you use any proxy or VPN?

**Comment by dufferzafar** [comment]
Yes, I am from India, and didn't use any VPN or proxy while running youtube-dl. I can download the video from the keepvid.com site but not youtube-dl.

**Comment by wenxinxu** [comment]
Had the same issue with https://www.youtube.com/watch?v=cYkUl8MrXgA

**Comment by austux** [comment]
same error with https://www.youtube.com/watch?v=ic9AV4mMbOQ yet it downloads OK using "Video Downloadhelper" browser plugin.

https://en.savefrom.net/ also seems to baulk at it.
