### ISSUE TITLE
Add support for any direct link

### ISSUE THREAD

**Issue by i2324561w2** [ytdl-org/youtube-dl#28534]
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.03.14**
- [x] I've searched the bugtracker for similar feature requests including closed ones

It would be great if you could add a way to download any direct link to any resource, for example with
`youtube "https://github.com/ytdl-org/youtube-dl/releases/download/2021.03.14/youtube-dl.exe"`
I get
`ERROR: unable to open for writing: [Errno 2] No such file or directory: '3052bc00-84a9-11eb-9a4e-90a482fdb469-3052bc00-84a9-11eb-9a4e-90a482fdb469X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A_20210324_us-east-1_s3_aws4_request&X-Amz-Date=20210324T163951Z&X-Amz-Expires=300&X-Amz-Signature=2b247f3a22723aa3496c81c8dd0465173a28f167a309cc45a6e577439fa1f2ab&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=1039520&response-content-disposition=attachment; filename=youtube-dl.unknown_video.part'`.
I get this isn't exactly what y-dl is for, but if it's simple to implement it, it wouldn't harm! (I really like the option to limit the download speed, and I see there are a lot of other useful options I still have to try!)
Thanks for your attention.

**Comment by pukkandan** [comment]
Use `aria2c` or similar tools for general downloads. youtube-dl code is structured specifically for video downloads

**Comment by HGStyle** [comment]
yes but it could be really usefull in some cases like in a programm where the user enter an url to download audio or video from, and ytdl is used to download them in background task: the user may put a direct dl link, it would be dumb to say the link is invalid...

**Comment by dirkf** [comment]
Use `--force-generic`, or a generic downloader as recommended above.

**Comment by dirkf** [comment]
If anyone comes up with a video URL that yt-dl ought to handle and doesn't, please open a new issue. This wouldn't include URLs that are found, or should be, in site extraction, nor if a basic command option like `--force-generic --referer ...` succeeds in fetching the media.

**Comment by i2324561w2** [comment]
I'm ok with this as "won't fix", I just want to clarify that --force-generic or --referer won't help downloading, for example, the link in OP, nor this is a #29912 problem since my full path here is < 20 chars.

**Comment by dirkf** [comment]
Longer than 20 characters:

>`3052bc00-84a9-11eb-9a4e-90a482fdb469-3052bc00-84a9-11eb-9a4e-90a482fdb469X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A_20210324_us-east-1_s3_aws4_request&X-Amz-Date=20210324T163951Z&X-Amz-Expires=300&X-Amz-Signature=2b247f3a22723aa3496c81c8dd0465173a28f167a309cc45a6e577439fa1f2ab&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=1039520&response-content-disposition=attachment; filename=youtube-dl.unknown_video.part`
