### ISSUE TITLE
Youtube-dl is down?

### ISSUE THREAD

**Issue by TaktakTaktouk** [ytdl-org/youtube-dl#28548]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

The site https://youtube-dl.org/ is down? impossible to update youtube-dl

**Comment by dstftw** [comment]
`aries.uberspace.de` is being moved to Uberspace 7. This will take some hours of downtime.

From https://is.uberspace.online/:
>aries.uberspace.de Host aries is being migrated to Uberspace 7
6 hours ago
This host will move to U7, causing a downtime of multiple hours today.

**Comment by TaktakTaktouk** [comment]
Good luck guys! love you all 
Thank you
