### ISSUE TITLE
New Crunchyroll Beta Broke Youtube-dl on classic and beta not supported

### ISSUE THREAD

**Issue by Nicknakin** [ytdl-org/youtube-dl#28545]
## Checklist

- [ X] I'm reporting a broken site support
- [ X] I've verified that I'm running youtube-dl version **2021.03.25**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', '/home/nick/Downloads/cookies.txt', '--write-sub', '--sub-lang', 'enUS', 'https://www.crunchyroll.com/dr-stone/episode-11-prologue-of-dr-stone-801916', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.9.2 (CPython) - Linux-5.10.23-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[crunchyroll] 801916: Downloading webpage
WARNING: unable to extract OpenGraph description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/usr/lib/python3.9/site-packages/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2059, in download
    res = self.extract_info(
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/crunchyroll.py", line 456, in _real_extract
    video_title = re.sub(r'^Watch\s+', '', self._og_search_description(webpage))
  File "/usr/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

```

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', '/home/nick/Downloads/cookies.txt', '--write-sub', '--sub-lang', 'enUS', 'https://beta.crunchyroll.com/watch/GN7UDZ3VQ/PROLOGUE-OF-Dr-STONE', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.9.2 (CPython) - Linux-5.10.23-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] PROLOGUE-OF-Dr-STONE: Requesting header
WARNING: Falling back on generic information extractor.
[generic] PROLOGUE-OF-Dr-STONE: Downloading webpage
[generic] PROLOGUE-OF-Dr-STONE: Extracting information
ERROR: Unsupported URL: https://beta.crunchyroll.com/watch/GN7UDZ3VQ/PROLOGUE-OF-Dr-STONE
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 3506, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://beta.crunchyroll.com/watch/GN7UDZ3VQ/PROLOGUE-OF-Dr-STONE
```

## Description

Update to the crunchyroll site has broken support. No longer works with the old format links, and does not have implementation to support beta.crunchyroll.com.

**Comment by FoxMcloud5655** [comment]
I am able to run the old links and they still work.
`https://www.crunchyroll.com/dr-stone/episode-11-prologue-of-dr-stone-801916`
My arguments for context:
```
youtube-dl.exe
 --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
 --merge-output-format mkv
 --ffmpeg-location ffmpeg\bin
 --cache-dir "cache"
 --download-archive downloaded.txt
 --fixup warn
 --add-metadata
 --no-call-home
 --sub-lang enUS
 --write-sub
 --cookies cookies.txt
 -a download.txt
 -o "%%(uploader)s/%%(title)s.%%(ext)s"
```

**Comment by Nicknakin** [comment]
I also am getting no results with those arguments. Same error as initially posted. Can we get a verbose log of it working for you?

**Comment by FoxMcloud5655** [comment]
Sure.  I've already downloaded the file in question, but here it is below:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36', '--merge-output-format', 'mkv', '--ffmpeg-location', 'ffmpeg\\bin', '--cache-dir', 'cache', '--download-archive', 'downloaded.txt', '--fixup', 'warn', '--add-metadata', '--no-call-home', '--sub-lang', 'enUS', '--write-sub', '--cookies', 'cookies.txt', '-a', 'download.txt', '-o', '%%(uploader)s/%%(title)s.%%(ext)s', '--verbose']
[debug] Batch file urls: ['https://www.crunchyroll.com/dr-stone/episode-11-prologue-of-dr-stone-801916']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, rtmpdump 2.3
[debug] Proxy map: {}
[crunchyroll] 801916: Downloading webpage
[crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-enUS information
[crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-ptBR information
[crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-arME information
[crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP information
[crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-esLA information
[crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-itIT information
[crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-frFR information
[crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-deDE information
[crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-esES information
[crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-ruRU information
[crunchyroll] 801916: Downloading media info
WARNING: Unable to download XML: HTTP Error 403: Forbidden
[debug] Default format spec: bestvideo+bestaudio/best
[download] Dr. STONE Season 2 Episode 11 – PROLOGUE OF Dr. STONE has already been recorded in archive
```
It would have errored out before this if it was going to fail.

**Comment by Nicknakin** [comment]
> Sure. I've already downloaded the file in question, but here it is below:
> 
> ```
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36', '--merge-output-format', 'mkv', '--ffmpeg-location', 'ffmpeg\\bin', '--cache-dir', 'cache', '--download-archive', 'downloaded.txt', '--fixup', 'warn', '--add-metadata', '--no-call-home', '--sub-lang', 'enUS', '--write-sub', '--cookies', 'cookies.txt', '-a', 'download.txt', '-o', '%%(uploader)s/%%(title)s.%%(ext)s', '--verbose']
> [debug] Batch file urls: ['https://www.crunchyroll.com/dr-stone/episode-11-prologue-of-dr-stone-801916']
> [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
> [debug] youtube-dl version 2021.03.25
> [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
> [debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, rtmpdump 2.3
> [debug] Proxy map: {}
> [crunchyroll] 801916: Downloading webpage
> [crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-enUS information
> [crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-ptBR information
> [crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-arME information
> [crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP information
> [crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-esLA information
> [crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-itIT information
> [crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-frFR information
> [crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-deDE information
> [crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-esES information
> [crunchyroll] 801916: Downloading adaptive_hls-audio-jaJP-hardsub-ruRU information
> [crunchyroll] 801916: Downloading media info
> WARNING: Unable to download XML: HTTP Error 403: Forbidden
> [debug] Default format spec: bestvideo+bestaudio/best
> [download] Dr. STONE Season 2 Episode 11 – PROLOGUE OF Dr. STONE has already been recorded in archive
> ```
> 
> It would have errored out before this if it was going to fail.

Is that not a failed run :sweat: I'm struggling to pin down the issue and it doesn't seem to have any traction.

**Comment by Nicknakin** [comment]
Passing cookies or your user is the problem if you have the beta enabled. I was getting links from an un-signed in window and then using my beta-enabled account to get the episodes. This does not work because those links redirect to the beta version automatically.
