### ISSUE TITLE
--max-downloads  include previous downloads in count for exit

### ISSUE THREAD

**Issue by downtime0** [ytdl-org/youtube-dl#28541]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.03.25**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

RE: --max-downloads n
If a file is found to be previously downloaded can it also be counted as "downloaded" and therefore exit after n downloads are found?
example; my script runs on a schedule once a week, each week it may actually download 1-3 new files before it finds the files that were downloaded in previous weeks. Because it only downloaded 3 new files and not my limit of 5 it continues to run and I don't need it to cycle through the remaining 500+ videos in the account, I just want it to exit if 5 files were download (previous + new).

**Comment by pukkandan** [comment]
why not just use `--playlist-end` then?

**Comment by downtime0** [comment]
OMG! I swear I read through the list of options looking for something and that just didn't stand out.
Closing.
