### ISSUE TITLE
Is it possible to only save the titles of all videos in my Watch Later playlist? Helpful in case some video goes unlisted/private

### ISSUE THREAD

**Issue by GorvGoyl** [ytdl-org/youtube-dl#28557]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Many a times YT videos in my playlist like `Watch Later` go private or unlisted for one reason or another and I've no way of knowing what that video exactly was. maybe if it was a strike-down or something and I should be able to find similar one if I know the title.

So, Is it a possible to just get the title of videos using this library.. whenever I run this library it should create text file or something with all the video titles (from playlists). Just, the titles, I am not looking to save any videos as it'd take lot of bandwidth and space.

**Comment by dstftw** [comment]
```
-e, --get-title                      Simulate, quiet but print title
```

**Comment by GorvGoyl** [comment]
thanks @dstftw ✌️
