### ISSUE TITLE
Disneynow - Unable to extract post url, --ap-mso=Comcast_SSO does not work

### ISSUE THREAD

**Issue by DranzerX13** [ytdl-org/youtube-dl#28564]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

![disneynow_ytdl_cmd_error](https://user-images.githubusercontent.com/81488279/112732831-97389200-8ef9-11eb-87b0-4bd1901b2ea2.png)

Everytime I try pasting the script url in the cmd prompt, it says unable to extract post url. Btw, I'm using Python 2.6.

**Comment by october262** [comment]
once you are signed in with your TV provider, try using the cookies command.

**Comment by DranzerX13** [comment]
I tried that, and it still won't let me.

**Comment by IONECarter** [comment]
There seems to be an issue using ComcastSSO when you are not on a Comcast IP address.
