### ISSUE TITLE
[rmcdecouverte] ERROR: Unsupported URL:

### ISSUE THREAD

**Issue by DavidHenryThoreau** [ytdl-org/youtube-dl#28569]
All RMC Découverte URL are ERROR: Unsupported URL:

`youtube-dl --version
2021.03.25`

`youtube-dl -F "https://rmcdecouverte.bfmtv.com/seuls-face-a-lalaska_17548/profits-en-vue_23760/"
[generic] profits-en-vue_23760: Requesting header
WARNING: Falling back on generic information extractor.
[generic] profits-en-vue_23760: Downloading webpage
[generic] profits-en-vue_23760: Extracting information
ERROR: Unsupported URL: https://rmcdecouverte.bfmtv.com/seuls-face-a-lalaska_17548/profits-en-vue_23760/`

**Comment by macr2hoyipbjtn** [comment]
I don't think youtube-dl currently supports that service.

**Comment by jeromedecoster** [comment]
Open the terminal console (F12) then paste the code :

```js
var account = document.querySelector('[data-account]').getAttribute('data-account')
console.log('account:', account)

var video = document.querySelector('[data-video-id]').getAttribute('data-video-id')
console.log('video:', video)

var url = `http://players.brightcove.net/${account}/default_default/index.html?videoId=${video}`
console.log('url:', url)

console.log(`youtube-dl --no-mtime ${url}`)
```

Then copy in your terminal the last output :

```bash
youtube-dl --no-mtime http://players.brightcove.net/1969646226001/default_default/index.html?videoId=6245479903001
```

Reference : https://github.com/ytdl-org/youtube-dl/issues/18595#issuecomment-755375192

**Comment by brenard** [comment]
> Open the terminal console (F12) then paste the code :
The website seem changed and it's not works now. Their is another work-around ? I tried to identify something call `account` and `video-id` but I didn't find anything.

**Comment by cappert** [comment]
https://rmcdecouverte.bfmtv.com/seuls-face-a-lalaska_17548/profits-en-vue_23760/
redirects to https://www.rmcbfmplay.com/chaine/rmc-decouverte?subMenuId=RefMenuItem::rmcgo_home_rmcdecouverte

**Comment by BZHDeveloper** [comment]
New API, all replays are protected by DRM (except trailers of course)

**Comment by DavidHenryThoreau** [comment]
> Open the terminal console (F12) then paste the code :
> 
> ```js
> var account = document.querySelector('[data-account]').getAttribute('data-account')
> console.log('account:', account)
> 
> var video = document.querySelector('[data-video-id]').getAttribute('data-video-id')
> console.log('video:', video)
> 
> var url = `http://players.brightcove.net/${account}/default_default/index.html?videoId=${video}`
> console.log('url:', url)
> 
> console.log(`youtube-dl --no-mtime ${url}`)
> ```
> 
> Then copy in your terminal the last output :
> 
> ```shell
> youtube-dl --no-mtime http://players.brightcove.net/1969646226001/default_default/index.html?videoId=6245479903001
> ```
> 
> Reference : [#18595 (comment)](https://github.com/ytdl-org/youtube-dl/issues/18595#issuecomment-755375192)

Nice feature which does not seems to work at the moment.
Do you have another suggestion ?

**Comment by dirkf** [comment]
The site uses a JS application. It needs you to subscribe before it will send the media links, except possibly for trailers, labelled as non-DRM.

To progress this, please find one or more example shows that can be played in the browser with DRM   open a new site support request and provide a HAR archive

**Comment by dirkf** [comment]
See also #24862.
