### ISSUE TITLE
Any way to customise the -j output?

### ISSUE THREAD

**Issue by XiovV** [ytdl-org/youtube-dl#28563]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm running this command: youtube-dl [youtube_channel_url] -j 
I'd like the -j flag to output stuff like the video url, title and description but I can't figure out how (at the moment it's returning a massive json output and I don't need 90%+ of the stuff it returns).

**Comment by XiovV** [comment]
PS: to give a little bit more context. The reason why I'm running this command on a youtube channel is because I want a list of all videos that channel has uploaded. I noticed that -j gives me the stuff I need (video url, title, description) but it's way too messy, that's why I want to see if there's a way to tell youtube-dl which values to give me.

**Comment by kikuyan** [comment]
How about using jq command?
youtube-dl [youtube_channel_url] -j | jq "{webpage_url, title, description}"

**Comment by XiovV** [comment]
> How about using jq command?
> youtube-dl [youtube_channel_url] -j | jq "{webpage_url, title, description}"

This works like a charm! Thank you.
