### ISSUE TITLE
Use of "add-header" during test of extractor

### ISSUE THREAD

**Issue by nixklai** [ytdl-org/youtube-dl#28568]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

I am augmenting an existing extractor with some minor changes. But while implementing a new test for the extractor, I am not able to pass an `add-header` parameter into the test. I have tried the following:

```
{
        'url': 'https://view.vzaar.com/22681166/player',
        'add_header': ['Referer: https://example.com'],
        'info_dict': {
            'id': '22681166',
            'title': 'C_mp3_p3a.mp4',
            'ext': 'mp4',
}
```

```
{
        'url': 'https://view.vzaar.com/22681166/player',
        'info_dict': {
            'id': '22681166',
            'title': 'C_mp3_p3a.mp4',
            'ext': 'mp4',
        },
        'params': {
            'add_header': ['Referer: https://example.com'],
        }
}
```

**Comment by pukkandan** [comment]
The headers are added by `youtube_dl/__init__.py`. So it doesn't look like headers can be added for tests 🤔

**Comment by nixklai** [comment]
It is not possible, I guess I will have to remove the test instead. Thanks to @pukkandan for your help!
