### ISSUE TITLE
[YouTube] Age verification issues - Can't download video.

### ISSUE THREAD

**Issue by fosam** [ytdl-org/youtube-dl#28578]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.03.25**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones
_**(i found one similar but my** `--cookies` **are not expired as stated in this issue #28468)**_

## Verbose log

<pre>
youtube-dl --verbose https://www.youtube.com/watch?v=rR8s72aouNE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=rR8s72aouNE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-03-28-git-8b2bde0494-full_build, ffprobe 2021-03-28-git-8b2bde0494-full_build
[debug] Proxy map: {}
[youtube] rR8s72aouNE: Downloading webpage
[youtube] rR8s72aouNE: Refetching age-gated info webpage
<b>ERROR: Sign in to confirm your age
This video may be inappropriate for some users.</b>
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\extractor\youtube.py", line 1658, in _real_extract
youtube_dl.utils.ExtractorError: Sign in to confirm your age
This video may be inappropriate for some users.
</pre>

## Description

- Hello

- I tried to download an age-gated video and i got some age-verification errors as you can see in the Verbose log above.
<br />

- When i tried to provide the `--cookies` then i got the error below:

<pre>
youtube-dl --verbose --cookies C:/Users/account/Desktop/cookies.txt https://www.youtube.com/watch?v=rR8s72aouNE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--cookies', 'C:/Users/account/Desktop/cookies.txt', 'https://www.youtube.com/watch?v=rR8s72aouNE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-03-28-git-8b2bde0494-full_build, ffprobe 2021-03-28-git-8b2bde0494-full_build
[debug] Proxy map: {}
[youtube] rR8s72aouNE: Downloading webpage
<b>ERROR: Verify your age
Complete a brief check to show you're old enough to watch this video. Learn more</b>
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5nc448kk\build\youtube_dl\extractor\youtube.py", line 1658, in _real_extract
youtube_dl.utils.ExtractorError: Verify your age
Complete a brief check to show you're old enough to watch this video. Learn more
</pre>

- I'm signed in to my account and i verified that the `--cookies` are not expired. and of course my date of birth is over 18 years.

- I know that there is an age-restriction in the EU region, but i also can't download using just the normal command as with all other age-gated videos. 

- What gives?

![Capture 28_03_2021_19_55_29](https://user-images.githubusercontent.com/52612348/112764179-a9a0f180-9007-11eb-9f6d-2013f8a857d7.png)

**Comment by Suika** [comment]
You are probably connecting from EU, right?
A change to YT was announced ~4 month that there will be extra steps for age verification in EU, iirc.
If you connect from outside of EU, it should work.

**Comment by fosam** [comment]
Have you tried to download the video?

**Comment by Rudbekia** [comment]
My issue(#28468) ended by @dstftw because the cookie seems to be expired. but as I wrote in the issue, it was the fresh cookies.txt.
This is not going to happen in the United States, so this is unlikely to be fixed.

**Comment by remitamine** [comment]
there is nothing to be done on the youtube-dl side.
either use a proxy/VPN from a country outside the EU, or complete the age verification process.

**Comment by fosam** [comment]
> My issue(#28468) ended by @dstftw because the cookie seems to be expired. but as I wrote in the issue, it was the fresh cookies.txt.
> This is not going to happen in the United States, so this is unlikely to be fixed.

- My cookies are not expired too.

- Does that mean the contrubutors are unlikely to fix any issues that occure outside the US

**Comment by remitamine** [comment]
> Does that mean the contrubutors are unlikely to fix any issues that occure outside the US

it's not about the issue not related to the US, it's that youtube won't allow access to the video when you're accessing a non-embedable age-restricted video from the EU with passing the new age verification requirement, youtube-dl can't simply bypass this condition.
> I just connected to a US server using VPN, and this is the report i got:

you didn't pass the cookies.

**Comment by Rudbekia** [comment]
@remitamine Then in the EU or countries using new age verification, Does that mean there is no way to download videos without a VPN connection? Even though I use the cookie of the ID whose age has been verified.

**Comment by remitamine** [comment]
> @remitamine Then in the EU or countries using new age verification, Does that mean there is no way to download videos without a VPN connection? Even though I use the cookie of the ID whose age has been verified.

no, if you can't download an age-restricted video using non-expired cookies for an account that has the ability to watch the video in the browser then this would be considered an issue, however, there won't much that can be done unless a developer can reproduce the same problem.

**Comment by fosam** [comment]
@Rudbekia 

- If you connect from the EU and have not verified, theres is now way without the VPN.

- If you have already verified your account you can just pass the cookies and download.

Try for yourself and report back.

**Comment by Rudbekia** [comment]
@remitamine Please check your email.

**Comment by jaker-dotcom** [comment]
I just experienced a similar issue (also EU). I was able to stream the video with mpv though, no age confirmation required. I don't know nothing about how a bypass would work but perhaps this indicates a possibility to do so?

**Comment by watchinofoye** [comment]
I have exactly the same problem.
About one week ago, I've tried to download a personal playlist containing at least one video 18+. youtube-dl refused to download it, so I've provides cookie file and it worked. 

Now, I'm trying to redownload the playlist - because I've added videos since the last week - but youtube-dl complains about age-verification again. I've recreated a cookie file but it still complains.
When I'm trying to access to the video from Firefox, no problem at all. I've event tried to recreate the cookie file while visiting the video in question.

Furthermore, the video is already downloaded so why youtube-dl does not just pass it ?!

**Comment by iFUCKINGHATEcomputers** [comment]
Something strangely fortuitous happens to me (I'm using the Youtube-DLG interface if that matters). When daddy Google and mummy EU ask for my papers on a video like [this](https://www.youtube.com/watch?v=3gKwo9Kgf3w) and I try youtube-dl, I get the typical `Sign in to confirm your age` error. 

However, if I wait a few minutes and try to download the same video with youtube-dl again, it just werks™...

**Comment by iFUCKINGHATEcomputers** [comment]
Nevermind, age-restricted videos aren't working again as of recently... apparently YouTube just patched out something called the `/get_video_info` endpoint.

**Comment by fosam** [comment]
https://stackoverflow.com/questions/67615278/get-video-info-youtube-endpoint-suddenly-returning-404-not-found/67629882#67629882

**Comment by reallyuniquename** [comment]
Possible fixes.

Fixing requests to `get_video_info`.
https://github.com/ytdl-org/youtube-dl/issues/29333#issuecomment-864049544

Switching to some internal Youtube API.
https://github.com/ytdl-org/youtube-dl/issues/29086#issuecomment-864091265

**Comment by fosam** [comment]
This issue was originally related to the age restriction in the EU even after you are logged into your account and your age is over 18.

First, you would get this:

**`ERROR: Sign in to confirm your age`**
**`This video may be inappropriate for some users.`**

After you sign in, you'd get this:

**`ERROR: Verify your age`**
**`Complete a brief check to show you're old enough to watch this video. Learn more`**

And the solution was to pass the cookie, problem solved.

**Comment by iFUCKINGHATEcomputers** [comment]
> And the solution was to pass the cookie, problem solved.

Then why was youtube-dl working for me before, without needing to give Google my ID or pass any cookies? I think this problem goes deeper, the lab boys still seem to be working on it.

**Comment by fosam** [comment]
yt-dl worked also for me but for the video above it didn't work, that's why i opened this issue, so some videos work and some not.

**Comment by hacxman** [comment]
It doesn't play age restricted videos again, look:

$ youtube-dl --verbose https://www.youtube.com/watch?v=rR8s72aouNE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=rR8s72aouNE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-74-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] rR8s72aouNE: Downloading webpage
[youtube] rR8s72aouNE: Refetching age-gated info webpage
WARNING: unable to download video info webpage: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 475, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2069, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1503, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2644, in compat_parse_qs
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2614, in _parse_qsl
AttributeError: 'bool' object has no attribute 'split'

**Comment by 0x00Jeff** [comment]
Hi, I have the same issue with age verification, and I am not connected from EU

my understanding according to [this](https://www.youtube.com/watch?v=tvs9IGTe9ZA), is that I can chain mpv with youtube-dl, to watch youtube videos without ads / age verification / ... without any cookies whatsoever
I've been using it for a while now, for videos that are not age restricted, but when I tried it on a age restricted I got the same error OP got, is my assumption about watching age-restriction videos without cookies or signing is still correct in the current version (I'm using youtube-dl 2021.06.06)? 

please correct me so I can post more details

**Comment by reallyuniquename** [comment]
@0x00Jeff you have to wait for the next youtube-dl release. Current version `2021.06.06` doesn't work well with age restricted videos.

**Comment by krukhlis** [comment]
By the way guys, it doesn't work in Canada as well:
![image](https://user-images.githubusercontent.com/18131621/126858952-e4ab74a5-7251-425d-a33e-d68cfaef0b11.png)

**Comment by reallyuniquename** [comment]
It looks like YouTube deprecated `/get_video_info` endpoint or changed required set of params once again.

**Comment by reallyuniquename** [comment]
Another possible fix https://github.com/yt-dlp/yt-dlp/issues/574#issuecomment-887171136

**Comment by nicolaasjan** [comment]
> Another possible fix [yt-dlp/yt-dlp#574 (comment)](https://github.com/yt-dlp/yt-dlp/issues/574#issuecomment-887171136)

Tried that (I'm from the EU) with [c0bc527](https://github.com/yt-dlp/yt-dlp/commit/c0bc527bca735ee8a8b32857466d75f7d47aa22a) implemented.
It works for some video's (e.g. [3gKwo9Kgf3w](https://www.youtube.com/watch?v=3gKwo9Kgf3w)), but not for others (e.g. [rR8s72aouNE](https://www.youtube.com/watch?v=rR8s72aouNE
))

**Comment by reallyuniquename** [comment]
There is no fix for videos that can't be embedded.

**Comment by kenorb** [comment]
Doesn't work with [`IFjle80na1A`](https://www.youtube.com/watch?v=IFjle80na1A) using `2021.06.06` version.

**Comment by krrrr0** [comment]
Does not work in South Korea.
`ERROR: Sign in to confirm your age`
Here we have our own age-check systems like the EU.  
I tried `--proxy` option to proxy to Japan, also didn't work. I can't figure out why.  
  
Should I wait until the next release?

**Comment by nicolaasjan** [comment]
> Should I wait until the next release?

Hmm...
You may have to wait a long time.
See this:
https://github.com/ytdl-org/youtube-dl/issues/29753

In the mean time, you could try with the fork [yt-dlp](https://github.com/yt-dlp/yt-dlp).
It can download [IFjle80na1A](https://www.youtube.com/watch?v=IFjle80na1A) just fine and without providing cookies.

**Comment by chrcoluk** [comment]
[**@fosam**](https://github.com/fosam) commented on [30 Mar 2021, 18:39 BST](https://github.com/ytdl-org/youtube-dl/issues/28578#issuecomment-810449508 "2021-03-30T17:39:09Z - Replied by Github Reply Comments"):
> [@Rudbekia](https://github.com/Rudbekia)
> 
> *   If you connect from the EU and have not verified, theres is now way without the VPN.
>     
> *   If you have already verified your account you can just pass the cookies and download.
>     
> 
> Try for yourself and report back.

How does one pass the cookies from browser to youtube-dl ?

**Comment by j3pic** [comment]
YouTube has added more restrictions. Now you can't download age-restricted videos even with the cookie. When viewing in the browser you have to click on two prompts every time you watch the video.

**Comment by luctrudel** [comment]
> YouTube has added more restrictions. Now you can't download age-restricted videos from the US even with the cookie. When viewing in the browser you have to click on two prompts every time you watch the video.


facing same issue...
