### ISSUE TITLE
Downloads 1080p video (I think) in 360p

### ISSUE THREAD

**Issue by UtkuGARIP** [ytdl-org/youtube-dl#28572]
Hello

I want to download the broadcast of the publisher I follow on the Facebook site. It downloads via Youtube-DL, but the video quality is very bad. Pixel by pixel. :(

Link: https://www.facebook.com/eastergamers/videos/805781920150411

I can't watch it on Facebook, because facebook developers add too much code, RAM consumption is too high. Please help me download in 1080p quality.

## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.03.25**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by remitamine** [comment]
most likely you didn't install ffmpeg.
