### ISSUE TITLE
Redtube extractor broken: Failed to parse JSON Expecting ',' delimiter:

### ISSUE THREAD

**Issue by tredondo** [ytdl-org/youtube-dl#28573]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.24** (not .25; I've just curl'ed https://yt-dl.org/downloads/latest/youtube-dl and that's what I got.
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.redtube.com/38522511']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-70-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[RedTube] 38522511: Downloading webpage
WARNING: [RedTube] 38522511: Failed to parse JSON Expecting ',' delimiter: line 1 column 1975 (char 1974)
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7'
[download] Destination: Deeper. Voluptuous September & Sofi have twisted threesome-38522511.unknown_video
[download] 100% of 42.00B in 00:00
```

## Description

Download any Redtube video and you'll get a 42-byte GIF file that seems empty (tracking pixel?) Here:
[[![redtube](https://user-images.githubusercontent.com/10043369/112751063-a0604800-8f67-11eb-8a2e-da71686018de.gif)]]

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.
