### ISSUE TITLE
Noovo.ca stopped working today

### ISSUE THREAD

**Issue by airbete** [ytdl-org/youtube-dl#28587]
## Checklist

- [ X] I'm reporting a broken site support
- [ X] I've verified that I'm running youtube-dl version **2021.03.25**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar issues including closed ones

## Verbose log
youtube-dl --verbose https://www.noovo.ca/emissions/entre-deux-draps/le-cycle-de-la-vie-s1e10

```
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.noovo.ca/emissions/entre-deux-draps/le-cycle-de-la-vie-s1e10']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.8.7 (CPython) - Linux-5.11.7-100.fc32.x86_64-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] le-cycle-de-la-vie-s1e10: Requesting header
WARNING: Falling back on generic information extractor.
[generic] le-cycle-de-la-vie-s1e10: Downloading webpage
[generic] le-cycle-de-la-vie-s1e10: Extracting information
ERROR: Unsupported URL: https://www.noovo.ca/emissions/entre-deux-draps/le-cycle-de-la-vie-s1e10
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3506, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.noovo.ca/emissions/entre-deux-draps/le-cycle-de-la-vie-s1e10
```

## Description

The site noovo.ca changed its layout today. The extractor noovo.py stopped working (it has been working flawlessly for months). The URL doesn't pass the _VALID_URL test anymore. I tried to bypass the test but then the "brightcove id" of the video is not found.

**Comment by malotru007** [comment]
Sorry for the duplicate post. I have the same issue.

**Comment by RingoTheDog** [comment]
FWIW...
I believe Noovo is a BellMedia property, meaning it likely should be added to the 9c9media extractor.

**Comment by paramore2k** [comment]
> FWIW...
> I believe Noovo is now a BellMedia property, meaning it likely should be added to the 9c9media extractor.

Yeah, as we can see in the footer of Noovo new webiste, © 2021 Bell Média Tous droits réservés.

Everything has been changed to follow the new tv show "Le fil".

**Comment by FlaminHat** [comment]
Is there a way around it? Like ignoring the DRM flag and just downloading it anyway?

**Comment by DrMitoo** [comment]
why is it DRM now but it wasnt last week?

**Comment by malotru007** [comment]
Any update?

**Comment by paramore2k** [comment]
According to the manifest.mpd file we get while playing a video, it's protected by PLZ-KEEP-RAW.

 <BaseURL>https://pe-ak-vp06a-9c9media.akamaized.net/playlist/4135337/63393301/dash/20010001/a25f8573a05b2771/</BaseURL>

    <AdaptationSet contentType="video" segmentAlignment="true" startWithSAP="1">
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main">
      </Role>
      <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc">
      </ContentProtection>
      <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" value="widevine">
      </ContentProtection>

**Comment by FlaminHat** [comment]
Can't it be made to ignore those flags and try to download anyway?

**Comment by pukkandan** [comment]
@FlaminHat I don't think you understand how DRM works. The video file is encrypted and so even if you were to download it, you wont be able to play it in any player

**Comment by FlaminHat** [comment]
I understand alright. What I don't understand is why no attempt is even made to even _try_ to download it. It just cops out with an error message "DRM protected" instead of _trying_ to download it.

**Comment by malotru007** [comment]
Update, anyone? Couldn't we just use the 9c9media extractor with a minor modification?

**Comment by 89z** [comment]
Issue should be closed, URL is dead
