### ISSUE TITLE
Downloads from francetvinfo.fr not working

### ISSUE THREAD

**Issue by sdan41517** [ytdl-org/youtube-dl#28584]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl --verbose https://france3-regions.francetvinfo.fr/nouvelle-aquitaine/gironde/ampute-apres-un-accident-un-viticulteur-du-medoc-en-litige-contre-un-assureur-pour-sauver-son-domaine-1982857.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://france3-regions.francetvinfo.fr/nouvelle-aquitaine/gironde/ampute-apres-un-accident-un-viticulteur-du-medoc-en-litige-contre-un-assureur-pour-sauver-son-domaine-1982857.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.25
[debug] Python version 2.7.16 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[francetvinfo.fr] ampute-apres-un-accident-un-viticulteur-du-medoc-en-litige-contre-un-assureur-pour-sauver-son-domaine-1982857: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 403, in _real_extract
    webpage, 'video id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hi, I am trying to download a video from the link below and it throws an error stating "Unable to extract video id". I would appreciate if someone could fix it.

https://france3-regions.francetvinfo.fr/nouvelle-aquitaine/gironde/ampute-apres-un-accident-un-viticulteur-du-medoc-en-litige-contre-un-assureur-pour-sauver-son-domaine-1982857.html

Many thanks!

**Comment by someziggyman** [comment]
Thank you so much for this fix. 
Indeed it works for https://github.com/ytdl-org/youtube-dl/issues/28584
and this link: https://france3-regions.francetvinfo.fr/nouvelle-aquitaine/gironde/ampute-apres-un-accident-un-viticulteur-du-medoc-en-litige-contre-un-assureur-pour-sauver-son-domaine-1982857.html

But if still fails with ERROR: Unable to extract video id for this one: 
https://www.francetvinfo.fr/monde/afrique/mali/guerre-au-mali/barkhane-au-mali-l-onu-accuse-la-france-d-avoir-tue-des-civils_4353485.html

Here's the log:

youtube-dl -v -F https://www.francetvinfo.fr/monde/afrique/mali/guerre-au-mali/barkhane-au-mali-l-onu-accuse-la-france-d-avoir-tue-des-civils_4353485.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.francetvinfo.fr/monde/afrique/mali/guerre-au-mali/barkhane-au-mali-l-onu-accuse-la-france-d-avoir-tue-des-civils_4353485.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.03.31
[debug] Python version 2.7.16 (CPython) - Darwin-20.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[francetvinfo.fr] barkhane-au-mali-l-onu-accuse-la-france-d-avoir-tue-des-civils_4353485: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 404, in _real_extract
    webpage, 'video id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by someziggyman** [comment]
The latest improvement https://github.com/leshasmlesha/youtube-dl/commit/b384649a3994d3d0d93af831822239aa21873384
still does not seem to work for https://www.francetvinfo.fr/monde/islande-l-eruption-d-un-volcan-attire-lesfoules_4359657.html

Getting ERROR: Unable to extract video id
