### ISSUE TITLE
Is youtube displaying a video in worse quality than a youtube-dl version?

### ISSUE THREAD

**Issue by 18iteration** [ytdl-org/youtube-dl#28582]
- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

Question:
Wondering when you play a video on _youtube_ on the highest available resolution@fps e.g 1080p@60fps, will **youtube-dl's** highest available option be better or the same as youtube's video?
It sounds confusing at first since it should be the same but then again, youtube could just be storing a higher bitrate version on their servers but play a lower quality/bitrate version in the player.

Any idea?

**Comment by DeusoftheWired** [comment]
It downloads the highest available version by default. You can view all available resolutions, container, bitrates etc. by adding the parameter **-F** before the URL of the video so the call looks like this:

    youtube-dl -F https://www.youtube.com/watch?v=O7hgjuFfn3A


The three digit number on the left side tells you an ID / itag value (see all which were available 2017 listed [here](https://web.archive.org/web/20170208095409/https://en.wikipedia.org/wiki/YouTube)). You can use these to combine the video and audio track of your choice. Let’s say you want the 1920 × 1080 video part encoded in AVC1/H2.64 and 60 FPS. That’s ID 299 then. For audio you want simple AAC encoded 128 kbps m4a. That’s ID 140 then. To tell youtube-dl you want to use IDs, you have to put the parameter **-f**. After this, combine both IDs with a **+**:


    youtube-dl -f 299+140 https://www.youtube.com/watch?v=O7hgjuFfn3A


Be wary of the codecs. 1920 × 1080 is available in AVC1 (H.264), VP9, and AV1.


Therefore, YouTube has a fuckton of different versions in different qualitites lying around on their servers and requires massive storage space. However, you will never be able to download the version which the uploader uploaded to YouTube. YouTube always reencodes, even if you fulfill to their encoding recommendations to the point.

**Comment by 18iteration** [comment]
@DeusoftheWired  thanks for the explanation, I didnt know you could add multiple ids (v+a) in one command. Thanks.

Though my question was related to quality, yt own player vs youtube-dl download.

**Comment by dstftw** [comment]
Also note that Youtube may switch quality depending on some metrics like quality of your connection, bandwidth available, etc. So that start playing at max quality does not mean you won't be switched to lower resolution.
