### ISSUE TITLE
How do I tell Youtube-dl that I want it to download in the highest resolution available?

### ISSUE THREAD

**Issue by instaloadererror** [ytdl-org/youtube-dl#28598]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

My previous issue request was closed before I could ask for clarification. I have pasted my question below. I was told to install ffmpeg. I am not sure how that is supposed to help me make youtube-dl download videos in the highest resolution rather than 720p or 360p as it is currently doing. It seems to be a separate thing.

I am not very knowledgeable about coding or anything computer related so I apologize if I am missing something obvious. Youtube-dl is not automatically downloading the highest resolution of the videos that are available. The videos I am trying to download are available in 1080p (and can be downloaded in that resolution with other downloaders), but will only download in 720p with Youtube-dl (and sometimes even lower resolution).

I am using a .bat file to use Youtube-dl. The text in that .bat file is copied below. I tried using the "-f" command that was recommended in the faq, but that just caused everything to fail completely.

youtube-dl.exe -i --download-archive downloaded.txt -f best --add-metadata --embed-subs --embed-thumbnail --all-subs -o "Downloads%%(uploader)s%%(upload_date)s-%%(title)s-%%(id)s.%%(ext)s" -a VideosToDownload.txt

**Comment by rautamiekka** [comment]
You're missing the slash to indicate a subfolder (better to use "`/`" for it since ytdl is a Python app and thus will internally process the path) which I noticed only now, and yes they closed it, but didn't lock, so you can still reply.
