### ISSUE TITLE
--embed-thumbnail image quality option

### ISSUE THREAD

**Issue by Xiper-Starchild** [ytdl-org/youtube-dl#28614]
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.03.31**
- [x] I've searched the bugtracker for similar feature requests including closed ones

It would be nice if one could choose the quality of the image embedded as a thumbnail into the audio track of the video one downloads. At the moment the thumbnail is of the lowest quality.
![rc1oWJT](https://user-images.githubusercontent.com/40021984/113213714-d27bed80-9278-11eb-897c-0c6747f7041a.png)

**Comment by macr2hoyipbjtn** [comment]
Have you checked whether the downloaded thumbnail file is of higher quality than the embedded one? If not, you might need to use ffmpegthumbnailer on the video.

**Comment by nicolaasjan** [comment]
To get higher quality jpeg thumbnail, [line 70](https://github.com/ytdl-org/youtube-dl/blob/ca304beb1538e54c5a18fdd50846ed2259d63b8c/youtube_dl/postprocessor/embedthumbnail.py#L70) in `embedthumbnail.py`  needs to be changed to:

`            self.run_ffmpeg(escaped_thumbnail_filename, escaped_thumbnail_jpg_filename, ['-q:v', '1', '-bsf:v', 'mjpeg2jpeg'])`

(added `'-q:v', '1'` to convert the `webp` to `jpg` with the least compression)

**Comment by Xiper-Starchild** [comment]
Cheers. I Will try that, though I've worked with the command-line version up to now. But I'll see how I can incorporate that.

**Comment by nicolaasjan** [comment]
> Cheers. I Will try that, though I've worked with the command-line version up to now. But I'll see how I can incorporate that.

Well, you can compile the command-line executable from the source, with the change implemented, or run:
`python youtube_dl\__main__.py <arguments>` directly from within the source directory (Python must be installed).

**Comment by Xiper-Starchild** [comment]
Honestly, you are the single-most helpful person I've talked with this whole year so far. Thanks a lot, I will do so!

**Comment by nicolaasjan** [comment]
> Thanks a lot, I will do so!

Thanks!
Let me know if you've got better `jpg` thumbnails now.

**Comment by Xiper-Starchild** [comment]
I've just tested it and I am afraid it did not produce any notable change. Not sure why. But as mentioned, it's nothing serious. I will one day incorporate another program more dedicated to the task.

**Comment by nicolaasjan** [comment]
> I've just tested it and I am afraid it did not produce any notable change. Not sure why. But as mentioned, it's nothing serious. I will one day incorporate another program more dedicated to the task.

Strange, because when I tested it before opening an issue [here](https://github.com/yt-dlp/yt-dlp/issues/102) (with examples), I saw the difference...

**Comment by Xiper-Starchild** [comment]
I just learned that it has been embedding the highest image all along. This is embarrassing. I don't know how I missed that. Sorry, but thanks for your time. Have a good one.

**Comment by pukkandan** [comment]
youtube-dl downloads jpeg thumbnails for some videos and webp for others. The quality loss is only applicable when a webp is downloaded and then converted to jpeg.
