### ISSUE TITLE
[youtube] Error: video unavailable for some videos

### ISSUE THREAD

**Issue by varma02** [ytdl-org/youtube-dl#28613]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.03.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.31
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-70-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] l7yfEcWwink: Downloading webpage
[youtube] Downloading just video l7yfEcWwink because of --no-playlist
ERROR: Video unavailable
This video is not available
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1659, in _real_extract
    raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: Video unavailable
This video is not available
```

## Description

I'm writing a `discord.py` music bot that uses `youtube-dl` to extract video's streaming urls and found this strange issue, where on some videos It just says the video is unavailable, when I can play it in the browser just fine.
I'm running my bot in a `Linode` cloud machine with `Ubuntu 20.04 LTS` located in Newark, NJ.
Here is a sample of my code:
```
ytdl_opts = {
            'format': 'bestaudio/best',
            'noplaylist': True,
            'verbose':True,
            'source_address': '0.0.0.0',
}

source = youtube_dl.YoutubeDL(ytdl_opts).extract_info(url, download=False)['formats'][0]['url']
...
```

**Comment by dstftw** [comment]
Video is not available from your cloud machine.
