### ISSUE TITLE
[youtube] reject YouTube History tracking

### ISSUE THREAD

**Issue by B0pol** [ytdl-org/youtube-dl#28628]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.04.01**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description
With the new CONSENT cookie https://github.com/ytdl-org/youtube-dl/issues/28604, you accept ALL google tracking, including YouTube history!

on youtube.com, you are now redirected to consent.youtube.com. On this screen, you can "customise" and **disable tracking**, including **YouTube History**.

<img src="https://user-images.githubusercontent.com/58657617/113325814-30601200-9319-11eb-823e-6714ecfceffe.png" width="300"> <img src="https://user-images.githubusercontent.com/58657617/113325823-3229d580-9319-11eb-9974-df2a9f93b1ae.png" width="300">

after some tests, it looks like Accept all is YES+cb.20210328-17-p0.`<INSERT LANGUAGE>`+FX+`<RANDOM NUMBER???>`
reject all: YES+cb.20210328-17-p0.`<INSERT LANGUAGE>`+F+`<RANDOM NUMBER???>`
reject all but YouTube History YES+cb.20210328-17-p0.`<INSERT LANGUAGE>`+F+`<RANDOM NUMBER???>`

You can notice FX = accept all but F may not say reject youtube history…

In the code code you set cookie to 'YES+cb.20210328-17-p0.en+FX+%s' %s = consent id, that means accept all.

It would be great youtube-dl not to allow YouTube to track their users by accepting **All tracking**.

**Comment by B0pol** [comment]
I think it registers server side as accepting / rejecting does not change the random? Number nor other parts of the CONSENT cookie.

The only difference are set_ytc (youtube history), set_sc (search customisation), set_apw (youtube ad personalisation), set_aps (Google ad personalisation)

**Comment by dstftw** [comment]
I don't see any problem here since no actual account is associated. At the same time when authenticated cookies are used with real account one is free to accept tracking whatever way is preferred.

**Comment by B0pol** [comment]
You don't need an account to be tracked… If you accept (youtube-dl) it will log your history, match to your device, show customised content, search based on that…

**Comment by rautamiekka** [comment]
> I don't see any problem here since no actual account is associated. At the same time when authenticated cookies are used with real account one is free to accept tracking whatever way is preferred.

1 way around this is registering a dummy hidden acc (with everything disabled) which can be used with ytdl.
