### ISSUE TITLE
List all URLs in a playlist

### ISSUE THREAD

**Issue by Atemu** [ytdl-org/youtube-dl#28633]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.04.01**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

It'd be very useful if youtube-dl could print a list of the URLs of all videos in a playlist. URL as in, the link to the video itself that could be passed to youtube-dl to fetch it, not extracted stream URLs.

The main use case would be scripting on top of youtube-dl, i.e. downloading a full playlist with n parallel threads by calling youtube-dl on those.

The docs string for the `--flat-playlist` flag reads like it's supposed to do that already but all it does is print something like this:

```
[youtube:tab] <ID>: Downloading webpage
[download] Downloading playlist: <Name>
[youtube:tab] playlist <Name>: Downloading 2 videos
[download] Downloading video 1 of 2
[download] Downloading video 2 of 2
[download] Finished downloading playlist: <Name>
```

Not sure that's intended actually.

**Comment by kikuyan** [comment]
Maybe you need `-j` output, or like this: `youtube-dl <playlist url> -j | jq -r .webpage_url`

**Comment by Atemu** [comment]
@kikuyan that does indeed work but it's really slow because it has to fetch *all* metadata for every video individually in the playlist.

Not feasible to use on larger playlists and might even get you rate-limited.

The playlist extractor should have access to basic metadata like the URLs all in one go.

The flag can be combined with the `--flat-playlist` however and that prints a sequence of JSON objects as expected (though not an actual JSON list weirdly).

It'd still be nice if `--flat-playlist` could print the URLs as regular strings too to allow a more unix-y approach to scripting.

**Comment by kikuyan** [comment]
Did you try `... --flat-playlist -j | jq -r .url`, then?
For YouTube's playlists, you will get video ids not urls, but since youtube-dl treats video ids as those of YouTube's, you can simply use them (or you can make urls if you need).
For other playlists, you will get urls.

**Comment by Atemu** [comment]
Yeah, that's what I was talking about in the secord part of my comment.
