### ISSUE TITLE
New donation link? Donation link is 404 File Not Found https://ytdl-org.github.io/youtube-dl/donations.html

### ISSUE THREAD

**Issue by Sidicas** [ytdl-org/youtube-dl#28644]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

Is there a new donation link?

**Comment by remitamine** [comment]
it has been intentially removed for legal concerns.
