### ISSUE TITLE
"403 Forbidden" error

### ISSUE THREAD

**Issue by FlaminHat** [ytdl-org/youtube-dl#28641]
Why does it say "Forbidden" here?

Output of "verbose" option follows:

---------------------

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://10play.com.au/news/sydney/sydney-news-01-apr-2021/tpv210401nupbd', '-o', 'Ten News Sydney, April 1.mp4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Python version 3.5.2 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[TenPlay] tpv210401nupbd: Downloading JSON metadata
[TenPlay] 9000000000020661: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/Users/imac/miniconda3/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Users/imac/miniconda3/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Users/imac/miniconda3/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/Users/imac/miniconda3/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/imac/miniconda3/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/Users/imac/miniconda3/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/Users/imac/miniconda3/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

---------------------

**Comment by macr2hoyipbjtn** [comment]
`403 Forbidden` means the webserver doesn't want you there, maybe because you're a downloader. try adding browser cookies or additional headers.

**Comment by macr2hoyipbjtn** [comment]
This HTTP request seems to work:
```
GET /news/sydney/sydney-news-01-apr-2021/tpv210401nupbd HTTP/1.0
Host: 10play.com.au

HTTP/1.1 200 OK
Server: Varnish
Retry-After: 0
Cache-Control: no-cache, no-store
Content-Length: 1469
Accept-Ranges: bytes
Date: Fri, 02 Apr 2021 19:31:21 GMT
Via: 1.1 varnish
Connection: close
X-Served-By: cache-hhn4025-HHN
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1617391882.762699,VS0,VE0
Strict-Transport-Security: max-age=900
```

**Comment by FlaminHat** [comment]
How do I add cookies or headers with youtube-dl?

**Comment by Genesisfury** [comment]
Getting the same error on 10play for a different show. Would really appreciate a fix.

**Comment by mist8kengas** [comment]
I get a similar error on Crunchyroll, rolling back to an older version of youtube-dl should fix it.

**Comment by Genesisfury** [comment]
Older versions get the same error.

**Comment by Alrefai** [comment]
> I get a similar error on Crunchyroll, rolling back to an older version of youtube-dl should fix it.

Thanks! Rolling back to version "2021.4.1" fixed the problem with Crunchyroll.

**Comment by bnw42** [comment]
A yt-dl version from Dec 2020 gives the same error.

**Comment by bnw42** [comment]
For what it's worth, trying "youtube-dl --username=##### https://10play.com.au/...." gives the same error as noted before, although I do get prompted for a 10Play password before getting the error.

**Comment by aarubui** [comment]
Welcome to programming, @bnw42. `youtube-dl` prompts you when you use `--username`, no matter what the URL is. No one's written the code for actually using your credentials with 10Play before. You'll have to wait for my pull request to be approved.

**Comment by bnw42** [comment]
Sorry .. I didn't know the user/pwd option only worked with sites that yt-dl is coded to work with. I thought the user/pwd option was more generic. Life is about constantly learning new things. :)  My coding experience is a bit prehistoric (think punch card programming!).

**Comment by aarubui** [comment]
There's some complicated simulation of filling in the actual login form for some of the sites. 10Play's quite straightforward, though.

**Comment by bnw42** [comment]
Except --username doesn't yet work for 10play. Mind you, even logging onto the website & using an out of the box install of chrome, I can't play videos on the 10play site since they broke yt-dl. But that's not an issue for here.

**Comment by HARTIX** [comment]
**Here's the final fix for Crunchyroll.**
First of all, check if you can actually access Crunchyroll with your machine.
If you enabled Beta Crunchyroll, disable it from the options of your account

Now, if you need to download a Premium video, follow these steps:
- Login in your Crunchyroll account using Chrome or Firefox
- Extract Crunchyroll cookies with any extension (best one is _cookies.txt_)
- Edit the cookie file and leave only the session_id, just like this:
![image](https://user-images.githubusercontent.com/53018261/114310014-7d966d80-9ae9-11eb-82b6-e9757f51cb52.png)

**Since you using session_id, you don't need to pass account username and password in the options (as login its even broken)**

Here's an example script in Python:
![image](https://user-images.githubusercontent.com/53018261/114310102-e978d600-9ae9-11eb-928e-5a4c905966f8.png)

Hope this will help

**Comment by stefanodvx** [comment]
**Here's the final fix for Crunchyroll.**
First of all, check if you can actually access Crunchyroll with your machine.
If you enabled Beta Crunchyroll, disable it from the options of your account

Now, if you need to download a Premium video, follow these steps:
- Login in your Crunchyroll account using Chrome or Firefox
- Extract Crunchyroll cookies with any extension (best one is _cookies.txt_)
- Edit the cookie file and leave only the session_id, just like this:
![image](https://user-images.githubusercontent.com/53018261/114310014-7d966d80-9ae9-11eb-82b6-e9757f51cb52.png)

**Since you using session_id, you don't need to pass account username and password in the options (as login its even broken)**

Here's an example script in Python:
![image](https://user-images.githubusercontent.com/53018261/114310102-e978d600-9ae9-11eb-928e-5a4c905966f8.png)

Hope this will help

**Comment by Columbo199X** [comment]
@stefanodvx Can this fix also be used for non premium / free videos? The 403 error on crunchyroll seems to be related to cloudflares [bot protection](https://github.com/ytdl-org/youtube-dl/issues/28398#issuecomment-813095891).

**Comment by bnw42** [comment]
Now for the OPs issue with 10Play ...

**Comment by FlaminHat** [comment]
Just to reiterate, here is the output in verbose mode:

------------

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://10play.com.au/news/sydney/sydney-news-01-apr-2021/tpv210401nupbd', '-o', 'Ten News Sydney, April 1.mp4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Python version 3.5.2 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[TenPlay] tpv210401nupbd: Downloading JSON metadata
[TenPlay] 9000000000020661: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
File "/Users/imac/miniconda3/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
return self._downloader.urlopen(url_or_request)
File "/Users/imac/miniconda3/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2279, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "/Users/imac/miniconda3/lib/python3.5/urllib/request.py", line 472, in open
response = meth(req, response)
File "/Users/imac/miniconda3/lib/python3.5/urllib/request.py", line 582, in http_response
'http', request, response, code, msg, hdrs)
File "/Users/imac/miniconda3/lib/python3.5/urllib/request.py", line 510, in error
return self._call_chain(*args)
File "/Users/imac/miniconda3/lib/python3.5/urllib/request.py", line 444, in _call_chain
result = func(*args)
File "/Users/imac/miniconda3/lib/python3.5/urllib/request.py", line 590, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by aarubui** [comment]
You seem anxious so here's a build of #28728 for *nix while you wait: [youtube-dl_28728.zip](https://github.com/ytdl-org/youtube-dl/files/6294278/youtube-dl_28728.zip)

**Comment by FlaminHat** [comment]
Not anxious so much, just keen with the encouragement of @bnw42 (thanks)

Output of what happens when I try the new youtube-dl you sent me (I have censored out the information that doesn't need to be made public)

/youtube-dl --username=*******@******.com --password=*************
 https://10play.com.au/news/sydney/sydney-news-01-apr-2021/tpv210401nupbd -o "Ten News Sydney, April 1.mp4" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username=PRIVATE', '--password=PRIVATE', 'https://10play.com.au/news/sydney/sydney-news-01-apr-2021/tpv210401nupbd', '-o', 'Ten News Sydney, April 1.mp4', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.5.2 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/Users/imac/miniconda3/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/imac/miniconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Items saved from being locked here/youtube-dl/__main__.py", line 19, in <module>
  File "/Items saved from being locked here/youtube-dl/youtube_dl/__init__.py", line 475, in main
  File "/Items saved from being locked here/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
  File "/Items saved from being locked here/youtube-dl/youtube_dl/YoutubeDL.py", line 2060, in download
  File "/Items saved from being locked here/youtube-dl/youtube_dl/YoutubeDL.py", line 799, in extract_info
  File "/Items saved from being locked here/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
  File "/Items saved from being locked here/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
  File "/Items saved from being locked here/youtube-dl/youtube_dl/extractor/common.py", line 533, in extract
  File "/Items saved from being locked here/youtube-dl/youtube_dl/extractor/common.py", line 437, in initialize
  File "/Items saved from being locked here/youtube-dl/youtube_dl/extractor/tenplay.py", line 62, in _real_initialize
  File "/Items saved from being locked here/youtube-dl/youtube_dl/extractor/tenplay.py", line 56, in _login
  File "/Users/imac/miniconda3/lib/python3.5/base64.py", line 59, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: a bytes-like object is required, not 'str'

**Comment by aarubui** [comment]
Thanks for testing for me. My changes only supported Python2.7. I've made the necessary changes for Python3.5. [youtube-dl_28728_1.zip](https://github.com/ytdl-org/youtube-dl/files/6294380/youtube-dl_28728_1.zip)

**Comment by bnw42** [comment]
Obviously not the windows executable, but there's no filetype, so unlike FlaminHat I have no idea what to do with the file. :(

**Comment by jmagic** [comment]
Tested this on python3.7 -- it works for me..

**Comment by Genesisfury** [comment]
> 
> 
> Thanks for testing for me. My changes only supported Python2.7. I've made the necessary changes for Python3.5. [youtube-dl_28728_1.zip](https://github.com/ytdl-org/youtube-dl/files/6294380/youtube-dl_28728_1.zip)

How do you use this fix?

**Comment by FlaminHat** [comment]
@jmagic YES! This version works!

@Genesisfury In Terminal, drag and drop the file "youtube-dl" you unzipped from the zip, and enter the parameters like you normally use the "youtube-dl" command. It should come out in the Terminal as

`/directory/containing/file/youtube-dl --username=....... etc. etc. --password=.......etc. etc. http://web.address.of.video -o "Video file.mp4"`

**Comment by aarubui** [comment]
Probably just another person looking for the Windows build. If I had a heart, I would. Best they wait for the formal process of review, merge and release. May take extra long with being both `geo-restricted` and `account-needed`.

**Comment by Genesisfury** [comment]
Doesn't work. It gives me the password prompt "Type account password and pres [Return]". When doing so, it returns with "ERROR" fixed output name but more than one file to download"

**Comment by bnw42** [comment]
Running in terminal implies linux or maybe MacOS. Being a windows user, not much use. Still, the issue is in the works so I'm content to wait for the windoze exec to come out with the fix.

**Comment by Ronnnny** [comment]
I made the necessary edits thanks to aarubui, complied for windows and it's working for me.

**Comment by callatech2018** [comment]
Hi Ronnnny, could you please upload your Windows version for those of us who use the Windows one until this problem has been resolved.
Thanks

**Comment by Ronnnny** [comment]
use with -u "username" -p "password"
[youtube-dl-10play-fix.zip](https://github.com/ytdl-org/youtube-dl/files/6326284/youtube-dl-10play-fix.zip)

**Comment by bnw42** [comment]
Almost .. but on Win7 this gives the dreaded "missing api-ms-win-core-path-l1-1-0.dll" error, which is an unresolvable error with win7 since the dll in question only works with Win8+. For Win7 it needs to be compiled with python 3.8.6 or earlier or as a 32-bit executable. :(

**Comment by Genesisfury** [comment]
Getting a Error 400: Bad request after it says "logging in". Any idea?

**Comment by bnw42** [comment]
Worked fine for me on a Win10 pc. I assume you have a 10Play account?

The command line format is:
youtube-dl-10play-fix -u username -p password https://10play.com.au...

No quotes etc around username & password. When I created my 10play account, I had to put in an email address as the username. I did rename the exec patch as 10p.exe so there's less typing. :)

**Comment by Genesisfury** [comment]
Oh, I was putting a = after the -u and -p. It's working now. Thank you! I appreciate it.

**Comment by bnw42** [comment]
I've found websites describing how to use the command line switches for youtube-dl to be somewhat contradictory. Some sites say to put in ='s before the username & password, others don't. I found by trial & error that the ='s are a no-no .. at least with windows.

**Comment by Ronnnny** [comment]
try this one on win7, no guarantees as I don't have win7 to test on.
[youtube-dl-10plsy-fix-p3.6.zip](https://github.com/ytdl-org/youtube-dl/files/6329425/youtube-dl-10plsy-fix-p3.6.zip)

**Comment by bnw42** [comment]
If you'll pardon a pun, it works a peach! Peach being one of the 10Play channels.
Thanks!!

**Comment by ringofyre** [comment]
The ver. provided by @Ronnnny does indeed work - could we get it pushed into master please?

**Comment by neilaja** [comment]
> use with -u "username" -p "password"
> [youtube-dl-10play-fix.zip](https://github.com/ytdl-org/youtube-dl/files/6326284/youtube-dl-10play-fix.zip)

This is brilliant.  Worked beautifully.  Thanks!

**Comment by 2wenty2wo** [comment]
> Thanks for testing for me. My changes only supported Python2.7. I've made the necessary changes for Python3.5. [youtube-dl_28728_1.zip](https://github.com/ytdl-org/youtube-dl/files/6294380/youtube-dl_28728_1.zip)

Thank you! Works on macOS.

**Comment by Nick-Barron** [comment]
To update - this is still an issue on the latest version of youtube-dl so still using tis modified version

**Comment by bnw42** [comment]
According to the changelog for the recent release, there were only a few issues addresses and those were attempted workarounds to get ty-dl working with youtube & porn hub. There were no fixes for 10play and no generic fixes (ie fixes that would apply to all sites).

Given the long queue of issues waiting to be dealt with and that 10play viewers are a small minority, it'll be a long time before this issue is addressed. I'd strongly recommend switching to a yt-dl fork such as yt-dlp. yt-dlp does work with the webpage urls for 10play, as long as you input a user name & password (which the modified version of yt-dl also requires).

**Comment by Nick-Barron** [comment]
Thank you @bnw42 I wasn't aware of yt-dlp

I will give it a go - really appreciate the help

**Comment by bnw42** [comment]
I've been using yt-dlp for 6 months now. It's updated regularly. It does have additional features, but in the basic mode it works the same as yt-dl. So much so if you use a GUI, you can rename yt-dlp.exe as youtube-dl.exe and replace the obsolete yt-dl file in the GUI install. I know of a few users who tried that and it worked.

To get yt-dlp, go to this site (also on github): https://github.com/yt-dlp/yt-dlp

Scroll down to the "installation" section and download the relevant binary for your os. Like youtube-dl, once you have it on your computer, running "yt-dlp -u" will check for any updates & download the latest version, as with yt-dl.

**Comment by FlaminHat** [comment]
I'm closing this thread because the question has been answered (user/pass required) and and yt-dlp provides additional answers to the problems.

Thankyou for your help with this issue.
