### ISSUE TITLE
Merging fail

### ISSUE THREAD

**Issue by ybbuc** [ytdl-org/youtube-dl#28645]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Why does merging fail? It says error, but gives no description of the error.
![CleanShot 2021-04-03 at 12 31 01](https://user-images.githubusercontent.com/15838/113468398-7da6c580-9478-11eb-9e98-d80c520ba21b.png)

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#bugs
