### ISSUE TITLE
Globo HTTP Error 406: Not Acceptable

### ISSUE THREAD

**Issue by renatobusatto** [ytdl-org/youtube-dl#28661]
# Description
This very same command used to work until a few months ago, but it suddenly stopped working.
`youtube-dl -f 'bestvideo+bestaudio' -u myemail -p 'mypassword' --verbose http://globoplay.globo.com/v/8698905/programa/`

# Checklist
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version 2021.04.01
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

# Error output
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'bestvideo+bestaudio', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--verbose', u'http://globoplay.globo.com/v/8698905/programa/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Python version 2.7.16 (CPython) - Darwin-20.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1-tessus
[debug] Proxy map: {}
[Globo] Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 406: Not Acceptable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/Users/me/Scripts/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Users/me/Scripts/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by fserb** [comment]
Same here.

**Comment by mgibert-bmat** [comment]
Same here! Is there any timeline when this will be solved?
Thanks!

**Comment by allanf181** [comment]
This error is on login, the captcha result is not being passed.

**Comment by renatobusatto** [comment]
Thank you very much, that explains a lot. Please, would you have an idea on how to make it possible to see/enter the captcha?

**Comment by allanf181** [comment]
Cookies should do it, but it looks like the way to get the video hash has changed, so it just changes the error.

**Comment by adamstraube** [comment]
Well the Android app does not ask for a Captcha so I wonder if its possible to use it's method of auth?

**Comment by renatobusatto** [comment]
This issue has been corrected by the [yt-dlp](https://github.com/yt-dlp/yt-dlp) team, you might want to have a look on [their solution](https://github.com/yt-dlp/yt-dlp/issues/991).
