### ISSUE TITLE
Need help with a batch file

### ISSUE THREAD

**Issue by MooseOnTheLoose1** [ytdl-org/youtube-dl#28663]
## Checklist

- [* ] I'm asking a question
- [* ] I've looked through the README and FAQ for similar questions
- [* ] I've searched the bugtracker for similar questions including closed ones

## Question

I am attempting to create a batch file using the output of Streamdetector, it outputs in a great format, and pasting the output directly into the youtube-dl CMD window works perfectly, but putting those command lines into a file and using -a to add them gives and invalid URL error. 
If this is something I could get help with, I would greatly appreciate your time.

Thanks!

**Comment by remitamine** [comment]
```
-a, --batch-file FILE                File containing URLs to download ('-'
                                     for stdin), one URL per line. Lines
                                     starting with '#', ';' or ']' are
                                     considered as comments and ignored.
```
> but putting those command lines into a file and using -a to add them gives and invalid URL error.
the file should contain URLs not command lines.
