### ISSUE TITLE
video wont download

### ISSUE THREAD

**Issue by danderson400** [ytdl-org/youtube-dl#28670]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.04.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by danderson400** [comment]
I was trying to download a video and it keeps saying video URL is invalid, skipping: HTTP Error 401: Unauthorized

**Comment by janwrobel111** [comment]
Run your command with additional `--verbose` flag and paste its output.

**Comment by janwrobel111** [comment]
Or paste command You are using, because it's probably Your fault.
