### ISSUE TITLE
Maximum number of pages of a channel to download

### ISSUE THREAD

**Issue by Mte90** [ytdl-org/youtube-dl#28701]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.04.07**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

So I have a script that downlaod the last video from a youtube channel, the issue is that if I ask for `--max-download 3` will check all the pages and maybe there are like a thousand. So I was thinking something like `--max-pages` where you can configure a number of the page to check in this way is more fast and ignore old stuff.

This can combined with --date-after because will check all the pages also if it is clear that there aren't to check there.

Example as it is now:
```
[download] 2017-11-22 upload date is not in range 2021-03-29 - 9999-12-31
[download] Downloading video 542 of 1473
[youtube] D_mjay1GZxY: Downloading webpage
[download] 2017-11-20 upload date is not in range 2021-03-29 - 9999-12-31
[download] Downloading video 543 of 1473
[youtube] PuR26pSxAeo: Downloading webpage
[download] 2017-11-17 upload date is not in range 2021-03-29 - 9999-12-31
[download] Downloading video 544 of 1473
[youtube] SvGsLhnU9cY: Downloading webpage
[download] 2017-11-15 upload date is not in range 2021-03-29 - 9999-12-31
[download] Downloading video 545 of 1473
[youtube] 2qsH2lw0OYs: Downloading webpage
[download] 2017-11-13 upload date is not in range 2021-03-29 - 9999-12-31
[download] Downloading video 546 of 1473
[youtube] fGvs_uXznD8: Downloading webpage
[download] 2017-11-10 upload date is not in range 2021-03-29 - 9999-12-31
[download] Downloading video 547 of 1473
[youtube] 8QOCIjIhjr4: Downloading webpage
[download] 2017-11-08 upload date is not in range 2021-03-29 - 9999-12-31
[download] Downloading video 548 of 1473
[youtube] r0a13HNKV8M: Downloading webpage
[download] 2017-11-06 upload date is not in range 2021-03-29 - 9999-12-31
[download] Downloading video 549 of 1473
[youtube] -D-sMWAzODw: Downloading webpage
```

**Comment by Mte90** [comment]
Hi @dstftw I searched but I didn't find another ticket for this, can you help me?

**Comment by joeeasterly** [comment]
I also wrote a ticket for this exact thing: I also called the feature --max-pages. I wanted the metadata for the most recent 10 videos on a YouTube channel, and because there were 47,000 videos on that channel, the pagination work alone took quite a few hours.

**Comment by Mte90** [comment]
The feature is still pending? I am not able to find something
