### ISSUE TITLE
Difference between `fulltitle` and `title`?

### ISSUE THREAD

**Issue by emlai** [ytdl-org/youtube-dl#28700]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

 I couldn't find any documentation on the video info JSON fields.

What is the difference between the `fulltitle` and `title` fields returned in the video info JSON (via --print-json or --write-info-json)? For the videos that I tried with, the values are the same for both fields.

**Comment by dstftw** [comment]
`fulltitle` is deprecated and should not be used.
