### ISSUE TITLE
Work around 403 forbidden on some videos

### ISSUE THREAD

**Issue by SuperCuber** [ytdl-org/youtube-dl#28713]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm trying to make a custom youtube audio player. I set up an api endpoint on my server that runs `--get-url -f best_audio`, and get a url to put in a `<audio src=` that way. However, for some songs, youtube returns a `403 forbidden`. I suspect those videos are configured to only be playable through the youtube page itself. My question is, is there a workaround? I tried removing the "referrer" header manually but it doesn't look like it did anything, so it must be something else that's triggering the protection.

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser

**Comment by SuperCuber** [comment]
@dstftw thanks for the reply, do you know what details need to match specifically for youtube? I could experiment and find this out myself but I'd rather be told so I don't miss anything.
