### ISSUE TITLE
[Vlive] No Upload Date in [ --output '%(upload_date)s' ]

### ISSUE THREAD

**Issue by Wilann** [ytdl-org/youtube-dl#28719]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.04.07**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I'm trying to write the upload data in the file name when downloading all videos from a creator on Vlive. Currently, `%(upload_date)s` gives "NA", and I'm using `%(playlist_index)s` to keep the order so I can input the upload dates manually. 

The only relevant issue I could find was #22830, which didn't lead to much.

**Comment by Wilann** [comment]
Could I ask why was this issue closed as incomplete? 
I thought I filled in everything I needed to. Please let me know which part is incomplete and I'll complete it.

**Comment by rautamiekka** [comment]
> Could I ask why was this issue closed as incomplete?
> I thought I filled in everything I needed to. Please let me know which part is incomplete and I'll complete it.

You left out like 2/3 or 3/4 of the template, like the verbose log and the used command that proves something's wrong and gives a much better idea what's wrong.

**Comment by Wilann** [comment]
This is a feature request, not a bug... 
I believe the template only asks for that if you're reporting a bug.

**Comment by dstftw** [comment]
You must provide concrete example URLs.
