### ISSUE TITLE
Followup issue

### ISSUE THREAD

**Issue by akandhari** [ytdl-org/youtube-dl#28721]
https://github.com/ytdl-org/youtube-dl/issues/28718

I am not sure why dev required the credentials for the defect.

**Comment by dstftw** [comment]
1. Cause it's your responsibility to provide reproducible environment.
2. There is already issue opened, stop posting duplicates.

**Comment by akandhari** [comment]
> 1. Cause it's your responsibility to provide reproducible environment.
> 2. There is already issue opened, stop posting duplicates.

‐-‐---'xxx

So you want production environment credentials. Not sure you can expect that from users.
Enjoy maintaining useless non working app.

**Comment by rautamiekka** [comment]
> > 1. Cause it's your responsibility to provide reproducible environment.
> > 2. There is already issue opened, stop posting duplicates.
> 
> ‐-‐---'xxx
> 
> So you want production environment credentials. Not sure you can expect that from users.
> Enjoy maintaining useless non working app.

The point's that since you already have access you can help by changing your pw and PM'ing or emailing the dev in question.
