### ISSUE TITLE
sound cuts out at exactly 1:50 on each video downloaded through youtube-dl command line on discord bot

### ISSUE THREAD

**Issue by FlashlightET** [ytdl-org/youtube-dl#28738]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Why is it that every time i download a video through youtube-dl through the command line on a python discord bot, it cuts out the audio at exactly 1:50 every single time? nobody else has ever seemed to have this issue, and videos download fine when run through the normal command line. Only through a discord.py bot command line function thingy whatever python uses
 Example: https://cdn.discordapp.com/attachments/829216521959768065/830619105324695562/2148787881_1618105193210_-_Copy.mp4

this is causing me to pull my hair out and making it turn gray why is it just not working properly in this specific case

the only arguments are "--no-playlist", "-g", "--cookies cookies.txt" and the url

**Comment by dstftw** [comment]
Address this question to your python discord bot support.
