### ISSUE TITLE
YouTube links obtained via "copy link location" result in "Downloading 0 videos"

### ISSUE THREAD

**Issue by bluenote10** [ytdl-org/youtube-dl#28734]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl --verbose 'https://www.youtube.com/watch\?v\=7wfUUZvybPY'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch\\?v\\=7wfUUZvybPY']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-140-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] watch\?v\=7wfUUZvybPY: Requesting header
[redirect] Following redirect to https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fwatch%255C%3Fv%255C%3D7wfUUZvybPY&gl=DE&m=0&pc=yt&uxe=23983172&hl=en&src=1
[youtube:tab] m: Downloading webpage
[download] Downloading playlist: m - Home
[youtube:tab] playlist m - Home: Downloading 0 videos
[download] Finished downloading playlist: m - Home
```

## Description

I typically obtain YouTube URLs via right-clicking on search results and using `Copy Link Location`.

In this example I have search on YouTube for "youtube-dl" and I'm using the link to the first search result as an example, which is `https://www.youtube.com/watch\?v\=7wfUUZvybPY`. These kind of links currently always result lead to `Downloading 0 videos` in youtube-dl, i.e., nothing gets downloaded. Manually changing the link to it short form `https://youtu.be/7wfUUZvybPY` works in youtube-dl. So it looks like it somehow fails to properly unwrap the video from the first kind of URL.

**Comment by dstftw** [comment]
You either escape special characters or quote the whole URL not both at the same time.

**Comment by bluenote10** [comment]
:+1: Stupid me, thanks for clarifying!

FYI for zsh users: Watch out for zsh's "url-quote-magic" plugin.

It turns out that a recent change to my zsh config had activated the "url-quote-magic" plugin. This plugin automatically escapes pasted URLs (but only for certain URL schemes like `https:` or `http:`, but not `file:` or URLs without a proper scheme). However, I had acquired the strict habit of using single quotes for pasting URLs to be safe. The "smart" plugin caught me off guard :roll_eyes: (unfortunately it isn't smart enough to see that you're pasting in a quoted context...)
