### ISSUE TITLE
No config files

### ISSUE THREAD

**Issue by zylmurbafi** [ytdl-org/youtube-dl#28730]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Discovered youtube-dl installed with Ubuntu-Mate 21.04 [BETA] but I am unable to locate either of the config files, ie. /etc/youtube-dl.conf
~/.config/youtube-dl/config

Should I remove it completely and manually install in order to get config files ??

**Comment by rautamiekka** [comment]
The configs aren't auto-created under any circumstance, so you won't find them unless the distro ships some kinda defaults, which they most likely won't.

If ytdl is installed through APT, then you need to purge it with `sudo apt purge youtube-dl` (if installed outside APT through a .deb: `sudo dpkg --remove youtube-dl`) and preferably use the PyPi one like so (assuming `python3-pip` (Python 3) or `python-pip` (Python 2; must be separately installed from Multiverse) is installed):
```
sudo pip install youtube-dl
```
and update with
```
sudo pip install --upgrade youtube-dl
```
This is simply cuz the DEB is ancient, the packager ain't involved with the project and seems to be extremely lazy as far as updating goes. The PyPi one fixes all this, and makes updating fairly easy, although you'll need to use `sudo` unless you're making a per-user or a per-venv installation.
