### ISSUE TITLE
Reported download speed is utterly wrong

### ISSUE THREAD

**Issue by zsugabubus** [ytdl-org/youtube-dl#28735]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ yt -v https://youtu.be/jFa5ssSAXZA
[debug] System config: []
[debug] User config: ['--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4280.66 Safari/537.36', '--add-header', 'DNT: 1', '--output', '%(title)s.%(ext)s', '--force-ipv4', '--add-metadata']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtu.be/jFa5ssSAXZA']
[debug] Adding header from command line option DNT: 1
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.9.1 (CPython) - Linux-5.10.16-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] jFa5ssSAXZA: Downloading webpage
[youtube] jFa5ssSAXZA: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/...'
[dashsegments] Total fragments: 702
[download] Destination: WTC7 Evaluation Progress Report - 06SEP2017 - UAF.f247.webm
[download]  54.8% of ~140.77MiB at 12.49MiB/s ETA 05:40
```

## Description

Every time I download something (I mostly use YouTube) and I look at the reported download speed I start feeling really bad.

Speed is constantly reported to be in the range (10-)15-20MiB/s, periodically jumps down to 700KiB/s-2MiB/s. However these numbers cannot be good since when I look at the interface transfer speed, I see about 150KiB/s real traffic.

(I was a little surprised that I have not found any related issues, so maybe it has something to do with my configuration?)

**Comment by dirkf** [comment]
The code for this has been updated. If the latest nightly release shows similar behaviour, please open a new issue.
