### ISSUE TITLE
ABC (Australia) site not working

### ISSUE THREAD

**Issue by lukejohnjones** [ytdl-org/youtube-dl#28751]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2021.04.07**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I am unable to extract the video off the following ABC site: youtube-dl --verbose https://www.abc.net.au/news/programs/the-business/2020-05-13/extended-interview-with-matt-comyn/12245340

My log from extraction is as follows:
```
>> youtube-dl --verbose https://www.abc.net.au/news/programs/the-business/2020-05-13/extended-interview-with-matt-comyn/12245340
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.abc.net.au/news/programs/the-business/2020-05-13/extended-interview-with-matt-comyn/12245340']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.3, ffprobe 2021-01-01-git-63505fc60a-full_build-www.gyan.dev
[debug] Proxy map: {}
[abc.net.au] 2020: Downloading webpage
ERROR: Unable to extract video urls; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\abc.py", line 74, in _real_extract
youtube_dl.utils.ExtractorError: Unable to extract video urls; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

**Comment by Vangelis66** [comment]
Using ` --force-generic-extractor` gets me a **576p25**, progressive-download, MP4 file: 

`youtube-dl --force-generic-extractor "https://www.abc.net.au/news/programs/the-business/2020-05-13/extended-interview-with-matt-comyn/12245340"` => 

```
[generic] 12245340: Requesting header
WARNING: Forcing on generic information extractor.
[generic] 12245340: Downloading webpage
[generic] 12245340: Extracting information
[download] Downloading playlist: Extended interview with Matt Comyn
[generic] playlist Extended interview with Matt Comyn: Collected 1 video ids (do
wnloading 1 of them)
[download] Downloading video 1 of 1
[download] Destination: Extended interview with Matt Comyn-12245340.mp4
[download] 100% of 64.46MiB in 01:01
[download] Finished downloading playlist: Extended interview with Matt Comyn
```
FWIW, this specific content isn't restricted to **Down Under** only IPs... :wink:

**Comment by lukejohnjones** [comment]
Thanks!

**Comment by Vangelis66** [comment]
**Closing** this issue (prematurely, IMHO) wasn't the most _wise_ thing to do... 
Forcing the "generic" extractor was just a _workaround_ (that worked in this case), since `yt-dl` has a _dedicated_ "**abc.net.au**" plugin (file `abc.py`), the ideal solution that would warrant closing is that the abcIE be "fixed"/patched, so that the link 

https://www.abc.net.au/news/programs/the-business/2020-05-13/extended-interview-with-matt-comyn/12245340

in OP could be successfully processed by it... 
I know the devs are actually overwhelmed with a plethora of things to fix/implement, still **the reported bug remains an unresolved one** (simply swept under the rug!) ...

Best regards

**Comment by dirkf** [comment]
Continuing in #30887.
