### ISSUE TITLE
Audio extraction to standard output doesn't work

### ISSUE THREAD

**Issue by csillag** [ytdl-org/youtube-dl#28760]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl https://vimeo.com/527965546/08a67148ea --extract-audio  -o -
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: Cannot download a video and extract audio into the same file! Use "-.%(ext)s" instead of "-" as the output template
csillag@unit10:/tmp$ ~/goi/ves/meteor_server/private/extract-audio/youtube-dl -v https://vimeo.com/527965546/08a67148ea --extract-audio  -o -
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vimeo.com/527965546/08a67148ea', '--extract-audio', '-o', '-']
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: Cannot download a video and extract audio into the same file! Use "-.%(ext)s" instead of "-" as the output template
```

## Description

I would like to download the audio only, and I need it on the standard output. Both features work separately, but apparently not together.
So getting the video data on stdout works, also downloading the audio works, but downloading the audio data and getting it on stdout doesn't seem to work.

The error message "Cannot download a video and extract audio into the same file! " doesn't make sense, because I don't need to save the video file, only the audio file. 

The suggested solution ( Use "-.%(ext)s" instead of "-" as the output template ) doesn't work, because I don't need multiple files starting with -, I need the output on the standard output.

**Comment by s104346** [comment]
Use `-f bestaudio` (or any other audio-only format) instead of `--extract-audio`:
``` bash
$ youtube-dl https://vimeo.com/527965546/08a67148ea -f bestaudio  -o -
```

**Comment by csillag** [comment]
Indeed! That solves my problem. So as far as I am concerned, this could be closed.

**Comment by csillag** [comment]
Thanks for the tip, @s104346
