### ISSUE TITLE
What it mean when download always stop with "Unknown speed"

### ISSUE THREAD

**Issue by TaktakTaktouk** [ytdl-org/youtube-dl#28765]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have the same issue in my VPS each time I run youtube-dl. the download stop with: `[download]   1.1% of ~75.47KiB at Unknown speed ETA 00:59`
Is it mean that there is an issue in my bandwidth? is there a way to ignore this error and continue the download?
thank you

**Comment by dstftw** [comment]
Most likely a network issue on your side.
