### ISSUE TITLE
Mediaset [ITALY] issues

### ISSUE THREAD

**Issue by botolo** [ytdl-org/youtube-dl#28773]
I have always been able to download videos from this page, setting my VPN to Italy:

https://isola.mediaset.it/video/full/

It looks like Mediaset has changed something, as YouTube-dl does not work anymore. I tested several VPNs and I have also installed a cloud server in Italy and tried directly from Italy, but I always get this message:

[generic] nona-puntata_7329: Requesting header
WARNING: Falling back on generic information extractor.
[generic] nona-puntata_7329: Downloading webpage
[generic] nona-puntata_7329: Extracting information
[Mediaset] F308788201000901: Downloading JSON metadata
[Mediaset] F308788201000901: Downloading MPEG4 SD SMIL data
[Mediaset] F308788201000901: Downloading MPEG4 HD SMIL data
ERROR: This content is not available in your location.
You might want to use a VPN or a proxy server (with --proxy) to workaround.

**Comment by dstftw** [comment]
Can you watch it in browser via the same VPNs in the first place?
In any case you must provide proxy/VPN capable to access it from browser for any work on this.

**Comment by ale5000-git** [comment]
I'm from Italy and I confirm that doesn't work in youtube-dl but works in browser.

youtube-dl say `ERROR: This content is not available in your location.` also from Italy.

**Comment by ale5000-git** [comment]
@dstftw: Why is this closed?

Page source from Italy: [Page.zip](https://github.com/ytdl-org/youtube-dl/files/6363369/Page.zip)

**Comment by winoni71** [comment]
I can confirm this issue, I'm also from Italy.

**Comment by botolo** [comment]
Happy to know I am not the only one. This thing was driving me crazy! How can we reopen this ticket?

**Comment by winoni71** [comment]
> 
> 
> Happy to know I am not the only one. This thing was driving me crazy! How can we reopen this ticket?

I have no idea, but in the mean time it is still possible to download from them, you just have to feed yt-dl with the mpd address.

**Comment by botolo** [comment]
How do I find the mpd address? I am currently using pasty.link to download videos from Mediaset.

**Comment by winoni71** [comment]
> 
> 
> How do I find the mpd address? I am currently using pasty.link to download videos from Mediaset.

Go to the video page, click F12, go to network and type mpd in the url filter, start the video, right click-->copy url.

Unless you want the highest quality, you will have to download the video and audio separately and then merge them.

**Comment by winoni71** [comment]
The issue seems to be resolved.

**Comment by ale5000-git** [comment]
Partially.

This doesn't work: https://isola.mediaset.it/video/full/tredicesima-puntata_7757.shtml

**Comment by winoni71** [comment]
> 
> 
> Partially.
> 
> This doesn't work: https://isola.mediaset.it/video/full/tredicesima-puntata_7757.shtml

The issue has indeed not been resolved, sometimes it works, sometimes it doesn't.
