### ISSUE TITLE
[Shahid.mbc.net] ERROR: Unsupported URL.

### ISSUE THREAD

**Issue by fosam** [ytdl-org/youtube-dl#28772]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.04.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

<pre>
youtube-dl -verbose https://shahid.mbc.net/en/shows/Ramez-Fi-Al-Shallal-season-1-episode-1/episode-359319
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://shahid.mbc.net/en/shows/Ramez-Fi-Al-Shallal-season-1-episode-1/episode-359319']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version <b>2021.04.17</b>
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-04-14-git-c5ca18fd1b-full_build, ffprobe 2021-04-14-git-c5ca18fd1b-full_build
[debug] Proxy map: {}
[generic] episode-359319: Requesting header
WARNING: Falling back on generic information extractor.
[generic] episode-359319: Downloading webpage
[generic] episode-359319: Extracting information
<b>ERROR: Unsupported URL:</b> https://shahid.mbc.net/en/shows/Ramez-Fi-Al-Shallal-season-1-episode-1/episode-359319
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_5l7wxqx\build\youtube_dl\extractor\generic.py", line 3506, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://shahid.mbc.net/en/shows/Ramez-Fi-Al-Shallal-season-1-episode-1/episode-359319
</pre>

## Description

- Unable to download video from Shahid, requests return Unsupported URL, it must be a bug/issue because this site is already supported.

**Comment by mbassiouny33** [comment]
I second this request to fix it  please.

Support for Shahid broke, it used to work...

**Comment by mtnshadid** [comment]
I even tried mpd file directly and start saying there is no video

`youtube-dl --no-part --restrict-filenames --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0" --referer "https://shahid.mbc.net/" "https://cdxaws-ak.akamaized.net/out/v1/3cf6cf700016494ea46936c576e5afad/0a4241a1284e400793532dde98bd59e2/f89741fa8a32481e98eb32f8731adb36/manifest.mpd?aws.manifestfilter=video_height:144-1080"`

I tried to remove the manifest at the end too and same issue

CMD Output:

C:\Users\TheShadow\Desktop\zz>youtube-dl --no-part --restrict-filenames --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0" --referer "https://shahid.mbc.net/" "https://cdxaws-ak.akamaized.net/out/v1/3cf6cf700016494ea46936c576e5afad/0a4241a1284e400793532dde98bd59e2/f89741fa8a32481e98eb32f8731adb36/manifest.mpd?aws.manifestfilter=video_height:144-1080"
[generic] manifest.mpd?aws: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest.mpd?aws: Downloading webpage
[generic] manifest.mpd?aws: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
