### ISSUE TITLE
İnstagram reel video not downloading?

### ISSUE THREAD

**Issue by erickyun** [ytdl-org/youtube-dl#28785]
[Verbose Log](https://pastebin.com/raw/KUXduzuP)

I'm trying to download a instagram reel video but it isn't downloading the video?

getting this error:
`
youtube-dl 'https://www.instagram.com/p/CMw9F9kB6AI/?igshid=xxuho3kwdpew'
[Instagram] CMw9F9kB6AI: Downloading webpage            ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by kikuyan** [comment]
You shoudn't ignore the issue template.

Seems to be working. I don't know the difference, though.
```
$ youtube-dl --ignore-config --version
2021.04.17
$ youtube-dl --ignore-config https://www.instagram.com/p/CMw9F9kB6AI/?igshid=xxuho3kwdpew
[Instagram] CMw9F9kB6AI: Downloading webpage
[download] Destination: Video by doesartwork-CMw9F9kB6AI.mp4
[download] 100% of 3.71MiB in 00:00
```

**Comment by erickyun** [comment]
> You shoudn't ignore the issue template.
> 
> Seems to be working. I don't know the difference, though. May or may not be the same as #28753.
> 
> ```
> $ youtube-dl --ignore-config --version
> 2021.04.17
> $ youtube-dl --ignore-config https://www.instagram.com/p/CMw9F9kB6AI/?igshid=xxuho3kwdpew
> [Instagram] CMw9F9kB6AI: Downloading webpage
> [download] Destination: Video by doesartwork-CMw9F9kB6AI.mp4
> [download] 100% of 3.71MiB in 00:00
> ```

Yes thank you it did work using cookies.
```
--cookies "instagram.com_cookies.txt"
```
