### ISSUE TITLE
Youtube-dl and player.stv.tv

### ISSUE THREAD

**Issue by Fred127** [ytdl-org/youtube-dl#28787]
% youtube-dl -F "https://player.stv.tv/episode/424n/sony-panam" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'https://player.stv.tv/episode/424n/sony-panam', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.17
[debug] Python version 2.7.16 (CPython) - Darwin-20.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-100444-g2749e20d04-tessus, ffprobe N-100444-g2749e20d04-tessus
[debug] Proxy map: {}
[stv:player] 424n: Downloading webpage
[stv:player] 424n: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Unable to d'load this file

**Comment by Vangelis66** [comment]
@Fred127: 

Most sadly, **STV** are offering the whole **Pan Am** series solely behind a **DRM** fence 😭 ; **desktop** browsers are being served **MPEG-DASH** streams with Common Encryption (**cenc**); a working implementation of the (Google-owned) **Widevine CDM** (Content Decryption Module) is required in your browser for decryption and playback: 

![STV-DRM](https://user-images.githubusercontent.com/9669492/115167501-904c0c00-a0c0-11eb-8c2b-995c272bad78.JPG)

URL sniffing will get you a URI to the DRM'ed **manifest.mpd** playlist: 
```
(with short-lived auth-token)
https://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/bccenc/6204867266001/bc2d27b6-8970-4e1c-87b9-3c1b09e04715/6s/manifest.mpd?fastly_token=NjA3ZDMwNmNfM2Q4MGMwN2YyM2UwNDJjOWYzZGRlYTY3YTI0ZTBhMGFkOWUxNDdkNjdmNTYwYjRkOGRmNTBiNTg1YmI1NWQ2OQ%3D%3D
```
which I'm attaching for inspection: [manifest.mpd.txt](https://github.com/ytdl-org/youtube-dl/files/6332563/manifest.mpd.txt)

Since `yt-dl` **does not support DRM circumvention**, (probably) nothing can be done about your issue 😭 ; let us hope **STV** do not generalise **DRM** on the rest of their offerings... 😒

**Comment by Fred127** [comment]
Thanks for that. I suspected as much. Yes STV has been really good as you I
hope they don’t drm everything

**Comment by Vangelis66** [comment]
> I hope they don’t **drm** everything

... If more users started opposing the **forced implementation** of DRM on the vast majority of **rich media** (video/audio) currently offered on the net, then the proliferation of the Google-owned CDM monopoly :-1:  would have been curtailed... 
But users, especially of younger age, haven't experienced the **DRM-free internet of yesteryear** and have grown to be apathetic about it; as long as they are on whatever _latest version of the app_ sanctioned by one of the very few "Big Players", no care in "their" world... :disappointed: 

It's simply disheartening how articles like 

https://www.gnu.org/philosophy/opposing-drm.html.en

have limited appeal nowadays... :cry:

**Comment by 89z** [comment]
Issue should be closed, URL is dead
