### ISSUE TITLE
youtube-dl Python: file name/extension after post-processing?

### ISSUE THREAD

**Issue by jasonhan-vassar** [ytdl-org/youtube-dl#28799]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, I'm looking for a reliable way to get the file name and extension of a merged video after post-processing. I've tried something like
```Python
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    info_dict = ydl.extract_info(video_url)
    filename = ydl.prepare_filename(info_dict)
    ext = info_dict.get("ext")
```

but this once got me `.webm` when the final extension was `.mkv`. I know `youtube-dl` on the command line has the `--exec` flag, which can reliably get the resulting file name. Is this currently possible? Thanks for reading!

**Comment by jefferson018200306** [comment]
Have you tried output name as `%(title)s.%(ext)s` ???


Example is 
`youtube-dl "LINK" -f bestvideo+bestaudio -o %(title)s.%(ext)s`

**Comment by jasonhan-vassar** [comment]
@jefferson018200306 Thanks for the response. I'm not sure how relevant that is to my question, since I'm talking about the Python module. The output name isn't the issue — it's being able to get that output name reliably.

Fortunately, I found a solution [here](https://www.reddit.com/r/youtubedl/comments/jq1pm7/custom_post_processor/gbn5yug?utm_source=share&utm_medium=web2x&context=3). This uses a custom post-processor which contains an `information` dict with all the info I could ever need (output name, extension, video ID, etc.).
