### ISSUE TITLE
Add Auto Updater

### ISSUE THREAD

**Issue by Alpha-404** [ytdl-org/youtube-dl#28795]
## Checklist

- [yes ] I'm reporting a feature request
- [ yes] I've verified that I'm running youtube-dl version **2021.04.17**
- [yes] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

Its annoying to keep looking at the github for updates so I'm suggesting instead of constantly checking add a auto updater something like this :

`import requests, os, time
from bs4 import BeautifulSoup

print("fetching download...")

downloadpage = requests.get('https://github.com/ytdl-org/youtube-dl/releases')
sp = BeautifulSoup(downloadpage.content, 'html.parser')

latest = sp.find('span', text = 'youtube-dl.exe')

for link in latest.find_parents('a'):
    url = link.get('href')

print("download fetched do u want to update (y/n)")
res = input()

if res.lower() == 'y' or res.lower() == 'yes':
    download = requests.get('https://github.com' + url, stream = True)
    print("downloaded thingy writing to file...")
    
    if not os.path.exists('C:/youtube/youtube-dl.exe'):
        e = os.system('cls')
        print("file to write to not found creating file...")
        time.sleep(1)
        open("C:/youtube/youtube-dl.exe", "w")
        print("file created continuing with download")
        time.sleep(1)
        e = os.system('cls')
        print("fetching download...")
        print("download fecthed do u want to update (y/n)")
        print(res)
        print("downloaded thingy writing to file...")
    
    with open("C:/youtube/youtube-dl.exe", "wb") as e:
        for chunk in download.iter_content(chunk_size=1025):
            if chunk:
                e.write(chunk)
        
    print("downloaded")
    input()
else:
    print("then why u run update?")
    input()`

**Comment by rautamiekka** [comment]
Even when the code's adapted for platform indepdence, you should do either of these instead:
1) Install the PyPi version using PIP (`pip install youtube-dl`), then run `pip install --upgrade youtube-dl` using the Task Scheduler once a week to auto-upgrade. You'll be plagued by sudden Command Prompt windows opening when you least expect it, though.
2) Subscribe to the repo's new releases using the custom mode, then run the command above manually to upgrade.

**Comment by s104346** [comment]
```
$ youtube-dl --help

    -U, --update                         Update this program to latest version.
                                         Make sure that you have sufficient
                                         permissions (run with sudo if needed)
```

**Comment by rautamiekka** [comment]
> ```
> $ youtube-dl --help
> 
>     -U, --update                         Update this program to latest version.
>                                          Make sure that you have sufficient
>                                          permissions (run with sudo if needed)
> ```

Not sure how ytdl-org.github.io works on GH's end, but it's been down when GH and PyPi weren't even having problems, and failures to detect an updated version has been rather common by the looks of it, so I'm not sure if it's a good idea. The replacing of the file works very well on NIX systems due to the lack of "in use" flags, though.

**Comment by 3xploitch3ats** [comment]
so i had make it for always download the last release after i turn off a bool and list all other
### std::string gplzip1;
std::string gplzip22;
std::string dlyoutube::youtubedl;
int ReadLinegplzip22()
{
    std::istringstream file(gplzip1);

    std::string gpl = "youtube-dl.exe";
    std::string lpg = "releases/download";
    std::regex e("\\b(" + lpg + ")([^ ]*)" + "\\b(" + gpl + ")([& ]*)");
    std::string gpll;
    while (std::getline(file, gpll))
    {
        if (regex_search(gpll, e))
            gplzip22 = gpll + "\n";
    }
    return 0;
}
bool checkfordownload = 1;
int ReadLinegplzip1()
{
    std::string doublequote = "\"";
    std::ifstream file(Directory::get_current_dir() + "\\youtubedl.txt");
    std::string gpl = "youtube-dl.exe" + doublequote;
    std::string lpg = "releases/download";
    std::regex e("\\b(" + lpg + ")([^ ]*)" + "\\b(" + gpl + ")([& ]*)");
    std::string gpll;
    std::smatch m;
    std::string result;
    while (std::getline(file, gpll))
    {
        /*if (regex_search(gpll, e))
            gplzip1 = gpll + "\n";*/
        std::sregex_iterator next(gpll.begin(), gpll.end(), e);
        std::sregex_iterator end;
        while (next != end) {
                std::smatch match = *next;
                std::cout << match.str() << "\n";
                if (checkfordownload)
                {
                gplzip1 = gpll;
                checkfordownload = 0;
                }
                next++;
            }
    }
    file.close();
    return 0;
}

int ReadLinegplzip33()
{
    std::istringstream file(dlyoutube::youtubedl);
    std::string lpg = "youtube-dl.exe";
    std::regex e{ "\\b" + lpg + "\\b" };
    /*std::regex e("\\b(" + lpg + ")([^ ]*)");*/
    std::string gpll;
    while (std::getline(file, gpll))
    {
        if (regex_search(gpll, e))
            dlyoutube::youtubedl = gpll + "\n";
    }
    return 0;
}

int downloading2()
{
    std::ifstream ffmpeg;
    ffmpeg.open(Directory::get_current_dir() + "\\ffmpeg.zip");
    if (!ffmpeg)
    {
        /*std::string dwnld_URL = "https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-04-09-12-38/ffmpeg-N-101901-gb593abda6c-win64-gpl.zip";*/
        std::string dwnld_URL = "https://github.com/BtbN/FFmpeg-Builds/releases";
        /*std::string savepath = Directory::get_current_dir() + "\\ffmpeg.zip";*/
        std::string savepath = Directory::get_current_dir() + "\\ffmpeg.txt";
        std::wstring downloadfile = functions::s2ws(dwnld_URL);
        LPCWSTR downloadingfile = downloadfile.c_str();
        std::wstring savefile = functions::s2ws(savepath);
        LPCWSTR savingfile = savefile.c_str();
        /*URLDownloadToFile(NULL, dwnld_URL.c_str(), savepath.c_str(), 0, NULL);*/
        URLDownloadToFileW(NULL, downloadingfile, savingfile, 0, NULL);
        ReadLinegplzip();
        std::string taskdirectory2 = Directory::get_current_dir() + "\\ffmpegurl.txt";
        std::ofstream repbegtext(taskdirectory2);
        if (repbegtext.is_open())
        {
            std::string doublequote = "\"";
            std::string ahref = "<a href=" + doublequote;
            std::string https = " https";
            std::string githubcom = https + "://github.com";
            std::string::size_type rep = gplzip.find(ahref);
            if (rep != std::string::npos)
                gplzip.replace(rep, ahref.length(), githubcom);
            std::string newline = "\n";
            size_t pos = gplzip.find(doublequote);
            while (pos != std::string::npos)
            {
                gplzip.replace(pos, doublequote.size(), newline);
                pos = gplzip.find(doublequote, pos + newline.size());
            }
            ReadLinegplzip2();
            repbegtext << gplzip2;
        }
        repbegtext.close();
        std::string dwnld_URL2 = gplzip2;
        /*std::string savepath = Directory::get_current_dir() + "\\ffmpeg.zip";*/
        std::string savepath2 = Directory::get_current_dir() + "\\ffmpeg.zip";
        std::wstring downloadfile2 = functions::s2ws(dwnld_URL2);
        LPCWSTR downloadingfile2 = downloadfile2.c_str();
        std::wstring savefile2 = functions::s2ws(savepath2);
        LPCWSTR savingfile2 = savefile2.c_str();
        /*URLDownloadToFile(NULL, dwnld_URL.c_str(), savepath.c_str(), 0, NULL);*/
        URLDownloadToFileW(NULL, downloadingfile2, savingfile2, 0, NULL);
        std::string line = "\n";
        std::string ffmpegn = "ffmpeg-N";
        std::string ffmpegnew = line + "ffmpeg-N";
        std::string wingpl = "-win64-gpl" + line;
        std::string wingplzip = "-win64-gpl.zip";
        ffmpeg::gplzip3 = gplzip2;
            std::string::size_type rep1 = ffmpeg::gplzip3.find(ffmpegn);
        if (rep1 != std::string::npos)
            ffmpeg::gplzip3.replace(rep1, ffmpegn.length(), ffmpegnew);

        std::string::size_type rep2 = ffmpeg::gplzip3.find(wingplzip);
        if (rep2 != std::string::npos)
            ffmpeg::gplzip3.replace(rep2, wingplzip.length(), wingpl);
        std::string taskdirectory3 = Directory::get_current_dir() + "\\ffmpegfolder.txt";
        std::ofstream repbegtext2(taskdirectory3);
        if (repbegtext2.is_open())
        {
            ReadLinegplzip3();
            repbegtext2 << ffmpeg::gplzip3;
        }
        repbegtext2.close();
    }
    moveffprog();
    return 0;
}

int downloading()
{
    std::ifstream youtubedll;
    youtubedll.open(Directory::get_current_dir() + "\\youtube-dl.exe");
    if (!youtubedll)
    {
        ////https://github.com/ytdl-org/youtube-dl/releases/download/2021.04.17/youtube-dl.exe
        //std::string dwnld_URL = "https://github.com/ytdl-org/youtube-dl/releases/download/2021.02.10/youtube-dl.exe";
        std::string dwnld_URL = "https://github.com/ytdl-org/youtube-dl/releases/";
        /*std::string savepath = Directory::get_current_dir() + "\\ffmpeg.zip";*/
        std::string savepath = Directory::get_current_dir() + "\\youtubedl.txt";
        std::wstring downloadfile = functions::s2ws(dwnld_URL);
        LPCWSTR downloadingfile = downloadfile.c_str();
        std::wstring savefile = functions::s2ws(savepath);
        LPCWSTR savingfile = savefile.c_str();
        /*URLDownloadToFile(NULL, dwnld_URL.c_str(), savepath.c_str(), 0, NULL);*/
        URLDownloadToFileW(NULL, downloadingfile, savingfile, 0, NULL);
        ReadLinegplzip1();
        std::string taskdirectory2 = Directory::get_current_dir() + "\\youtubedlurl.txt";
        std::ofstream repbegtext(taskdirectory2);
        if (repbegtext.is_open())
        {
            std::string doublequote = "\"";
            std::string ahref = "<a href=" + doublequote;
            std::string https = " https";
            std::string githubcom = https + "://github.com";
            std::string::size_type rep = gplzip1.find(ahref);
            if (rep != std::string::npos)
                gplzip1.replace(rep, ahref.length(), githubcom);
            std::string newline = "\n";
            size_t pos = gplzip1.find(doublequote);
            while (pos != std::string::npos)
            {
                gplzip1.replace(pos, doublequote.size(), newline);
                pos = gplzip1.find(doublequote, pos + newline.size());
            }
            ReadLinegplzip22();
            repbegtext << gplzip22;
        }
        repbegtext.close();
        std::string dwnld_URL2 = gplzip22;
        /*std::string savepath = Directory::get_current_dir() + "\\ffmpeg.zip";*/
        std::string savepath2 = Directory::get_current_dir() + "\\youtube-dl.exe";
        std::wstring downloadfile2 = functions::s2ws(dwnld_URL2);
        LPCWSTR downloadingfile2 = downloadfile2.c_str();
        std::wstring savefile2 = functions::s2ws(savepath2);
        LPCWSTR savingfile2 = savefile2.c_str();
        /*URLDownloadToFile(NULL, dwnld_URL.c_str(), savepath.c_str(), 0, NULL);*/
        URLDownloadToFileW(NULL, downloadingfile2, savingfile2, 0, NULL);
    }
    return 0;
}
