### ISSUE TITLE
How to download .ismv file and convert in .mp4

### ISSUE THREAD

**Issue by PhoramParmar** [ytdl-org/youtube-dl#28798]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

How to download .ismv file in any video format?

C:\Users\parma\Downloads\youtube-dl>youtube-dl -v https://cdn.cloud.altbalaji.com/content/2021-03/7745-604e73f60c3c8/BEKAABOO_S02_EP_02_ALT_MIX_MASTER_R1_bd5b9e31_BR1200.ismv
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://cdn.cloud.altbalaji.com/content/2021-03/7745-604e73f60c3c8/BEKAABOO_S02_EP_02_ALT_MIX_MASTER_R1_bd5b9e31_BR1200.ismv']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 2021-04-14-git-c5ca18fd1b-full_build-www.gyan.dev, ffprobe 2021-04-14-git-c5ca18fd1b-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] BEKAABOO_S02_EP_02_ALT_MIX_MASTER_R1_bd5b9e31_BR1200: Requesting header
WARNING: Falling back on generic information extractor.
[generic] BEKAABOO_S02_EP_02_ALT_MIX_MASTER_R1_bd5b9e31_BR1200: Downloading webpage
WARNING: URL could be a direct video link, returning it as such.
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://cdn.cloud.altbalaji.com/content/2021-03/7745-604e73f60c3c8/BEKAABOO_S02_EP_02_ALT_MIX_MASTER_R1_bd5b9e31_BR1200.ismv'
[download] Destination: BEKAABOO_S02_EP_02_ALT_MIX_MASTER_R1_bd5b9e31_BR1200-BEKAABOO_S02_EP_02_ALT_MIX_MASTER_R1_bd5b9e31_BR1200.ismv
[download] 100% of 161.14MiB in 00:32

**Comment by october262** [comment]
try with ffmpeg - ffmpeg -i somevideo.ismv -c codec copy -f mp4 -y output.mp4

**Comment by dirkf** [comment]
Also check the `--recode-video` yt-dl option (which will invoke something similar to the above).
