### ISSUE TITLE
Not able to download PluralSight Course

### ISSUE THREAD

**Issue by sanjeev-unomok** [ytdl-org/youtube-dl#28791]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
ThinkPad-E14:~$ pluralsight-dl https://app.pluralsight.com/library/courses/react-js-getting-started/table-of-contents
[pluralsight:course] react-js-getting-started: Downloading JSON metadata
[download] Downloading playlist: React: Getting Started
[pluralsight:course] playlist React: Getting Started: Collected 42 video ids (downloading 42 of them)
[download] Downloading video 1 of 42
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

ThinkPad-E14:~$ youtube-dl -U
youtube-dl is up-to-date (2021.04.17)

## Description

WRITE DESCRIPTION HERE
I am trying to download a Pluralsight course but it throwing this error. I am using latest version of youtube-dl and using this script

#!/bin/bash
for i in "$@";
do

youtube-dl \
--username YOUR-USERNAME-HERE \
--password YOUR-PASSWORD-HERE \
"$i" \
-o "/home/YOUR-USERNAME-HERE/Videos/%(playlist)s/%(chapter_number)02d - %(chapter)s/%(playlist_index)02d - %(title)s.%(ext)s" \
--sleep-interval 35 \
--max-sleep-interval 120 \
--sub-lang en \
--sub-format srt \
--write-sub

done

**Comment by benbudds** [comment]
Same here :/
Workaround for me was to:

- Login to pluralsight using my web browser (chrome) 
- Export the cookie as txt file (using get cookie txt extension)
- Execute youtube-dl command using --cookie switch instead of --username and --password

**Comment by sanjeev-unomok** [comment]
Can you please send me the link to the cookie extension you are talking about?

also share the script file so that I can understand how we can pass a cookie to youtube-dl

**Comment by benbudds** [comment]
Sure: https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid?hl=en

**Comment by jschin** [comment]
same issue having problem using --username and --password. 

Can confirm that using cookie file is working as well.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
My findings are that you can download their videos using the following steps.
* Log into PluralSight's website in Chrome
* Use [this tool](https://github.com/0x7FFFFFFFFFFFFFFF/Chrome_Cookies_Exporter/releases/tag/4%2F23%2F2021) to export it's cookies into a cookies.txt file
* Use this command to download the video
```
youtube-dl.exe --sleep-interval 300 --max-sleep-interval 500 --cookies "cookies.txt" -f best -o "%(autonumber)s_%(title)s.%(ext)s" --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36" --referer https://app.pluralsight.com/library/courses/jquery-building-dynamic-websites https://app.pluralsight.com/library/courses/jquery-building-dynamic-websites
```

You can download videos using the above method. But, there is a problem! I seriously doubt that when you are using PluralSight's website or client watching videos, they will randomly sending probe messages back to their server. When you are using youtube-dl, there are no these kind of probe messages, which will results in an account ban. My account has already been permanently locked. They give you two courtesy warning before a permanent ban. If you really want the video, software recording may be the last resort.

**Comment by huzaynbolt** [comment]
Is anyone able to fix this? I'm still having the same issue. on two different accounts. The cookie option or username and password doesn't work.
