### ISSUE TITLE
Homebrew install fails due to 404 errors for GDBM install

### ISSUE THREAD

**Issue by Astalda** [ytdl-org/youtube-dl#28804]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
==> Downloading https://homebrew.bintray.com/gdbm-1.19.big_sur.bottle.tar.gz
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://ghcr.io/v2/homebrew/core/gdbm-1.19.big_sur.bottle.tar.gz
==> Downloading from https://github.com/-/v2/packages/container/package/homebrew
##O=#  #                                                                      
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "gdbm"
Download failed: https://ghcr.io/v2/homebrew/core/gdbm-1.19.big_sur.bottle.tar.gz

```

## Description
I tried installing Youtube-dl via the homebrew command and found that the GDBM bottle cannot be downloaded currently due to 404 errors.

**Comment by kikuyan** [comment]
You must report it to Homebrew. Not a youtube-dl problem.

**Comment by Astalda** [comment]
Do you happen to know which Homebrew repository to report it in? There's 30
on their github page.

**Comment by kikuyan** [comment]
I'm not using Homebrew and no. Are you missing this I appended afterwords?
> Or read this https://github.com/Genymobile/scrcpy/issues/2247#issuecomment-818202605, you may find a solution.
In anyways, please close your issue report here.
