### ISSUE TITLE
Some queries to consider: YouTube-DL

### ISSUE THREAD

**Issue by RangaSE** [ytdl-org/youtube-dl#28803]
Greetings!
YouTube-DL is doing good, some minor things to consider to make it Perfect, namely, using "--format_note". Downloading is fine, but, merging the audio to video becomes deviating from the "format_note". Example (just an example) is:
( 19-04-2021 & 16:27:32.27 | C:\Users\Notebook> YouTube-DL[2021.04.17] -f "bestvideo+bestaudio[ext=m4a]/best[ext=mp4]/best" -ciw --recode-video mp4 --no-playlist --write-auto-sub --write-sub --embed-thumbnail -o "~\Videos\%(title)s (u%(upload_date)s; 0,4,26_161; %(format_note)s%(fps)s)YT '%(uploader)s'.%(ext)s" -- of3QeYle-Qk
[youtube] of3QeYle-Qk: Downloading webpage
[youtube] Downloading just video of3QeYle-Qk because of --no-playlist
[youtube] of3QeYle-Qk: Thumbnail is already present
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Resuming download at byte 100630404
[download] Destination: C:\Users\Notebook\Videos\Liu Tai Yang Beauty Fitness Model (u20210328; 0,4,26_161; 2160p30)YT 'Liu Tai Yang'.f272.webm
[download] 100% of 175.26MiB in 16:52
[download] Destination: C:\Users\Notebook\Videos\Liu Tai Yang Beauty Fitness Model (u20210328; 0,4,26_161; tinyNA)YT 'Liu Tai Yang'.f140.m4a
[download] 100% of 4.11MiB in 00:07
[ffmpeg] Merging formats into "C:\Users\Notebook\Videos\Liu Tai Yang Beauty Fitness Model (u20210328; 0,4,26_161; NA30)YT 'Liu Tai Yang'.mkv"
Deleting original file C:\Users\Notebook\Videos\Liu Tai Yang Beauty Fitness Model (u20210328; 0,4,26_161; 2160p30)YT 'Liu Tai Yang'.f272.webm (pass -k to keep)
Deleting original file C:\Users\Notebook\Videos\Liu Tai Yang Beauty Fitness Model (u20210328; 0,4,26_161; tinyNA)YT 'Liu Tai Yang'.f140.m4a (pass -k to keep)
[ffmpeg] Converting video from mkv to mp4, Destination: C:\Users\Notebook\Videos\Liu Tai Yang Beauty Fitness Model (u20210328; 0,4,26_161; NA30)YT 'Liu Tai Yang'.mp4
Deleting original file C:\Users\Notebook\Videos\Liu Tai Yang Beauty Fitness Model (u20210328; 0,4,26_161; NA30)YT 'Liu Tai Yang'.mkv (pass -k to keep)
[atomicparsley] Adding thumbnail to "C:\Users\Notebook\Videos\Liu Tai Yang Beauty Fitness Model (u20210328; 0,4,26_161; NA30)YT 'Liu Tai Yang'.mp4"

( 19-04-2021 & 17:23:41.65 | C:\Users\Notebook> Cls
The video, ".webm", uses the file name with correct Quality, but, while merging, it becomes 'NA30'; as all others do not contain, Video quality. I think, you can do the needful.
Also, I presently using "Debug Info" to get duration in "second and fraction"; the same is used in PowerShell ISE ( [timespan]::FromSeconds("266.161").ToString("h\,m\,s\_fff") ) to get the "h,m,s_fff" format, as, ":" is NOT permitted. If, you can do something to make it easier, I can use it my playlist as well.
Regards,
RS.
P.S.: Some more minor things, I forgot while writing. I can give them later.

**Comment by dirkf** [comment]
`format_note` is an output template variable (not a `--format_note` option).

If the download's metadata doesn't include a note field for the selected format, the string `NA` is used.

You can change this default using the option  `--output-na-placeholder`.

Your issue seems to be that the video and audio are being downloaded separately with different format notes, so the video gets `%(format_note)` set as "2160p" while the audio gets "NA" and then in merging the format data the original video note is being lost.

"Requested formats are incompatible for merge" means that the video is .webm. Although it's essentially MKV, the WEBM container format only supports VP8/9 video with Vorbis or Opus audio.

When the merge format data is prepared the `format_note` field is not used (unlike `fps`, which you see being preserved). You might try `resolution` instead, or add this line after youtube_dl/YoutubeDL.py:1377 to preserve any `format_note`s from the formats being merged:
```
                        'format_note': '+'.join(fn.get('format_note') for fn in formats_info if fn.get('format_note')),
 ```

**Comment by RangaSE** [comment]
Greetings and Thanks for the quick reply.
I already took some of the videos with 'verbose' option, '-v'. I think, the issue is, when we are giving the instruction for the merging, we use 'NA' in the output file name. One of the Trailers I downloaded earlier, with '-v'; forget the version and see what give in the input line.
Here is how:
' ; # 'Air Force One Trailer' 'TheTrailerSiteDOTcom' '0:2:38_499' '360p' ("optimal_format": "360p")
YouTube-DL[2021.03.14] -v -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -cikw --no-playlist --write-auto-sub --write-sub --embed-thumbnail -o "~\Videos\%(title)s (u%(upload_date)s; 0,2,38_499; %(format_note)s%(fps)s)YT '%(uploader)s'.%(ext)s" -- jPYnVOIfNiU
Microsoft Windows [Version 10.0.19042.867]
(c) 2020 Microsoft Corporation. All rights reserved.

( 22-03-2021 & 11:54:20.86 | C:\Users\Notebook> YouTube-DL[2021.03.14] -v -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -cikw --no-playlist --write-auto-sub --write-sub --embed-thumbnail -o "~\Videos\%(title)s (u%(upload_date)s; 0,2,38_499; %(format_note)s%(fps)s)YT '%(uploader)s'.%(ext)s" -- jPYnVOIfNiU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '-cikw', '--no-playlist', '--write-auto-sub', '--write-sub', '--embed-thumbnail', '-o', "~\\Videos\\%(title)s (u%(upload_date)s; 0,2,38_499; %(format_note)s%(fps)s)YT '%(uploader)s'.%(ext)s", '--', 'jPYnVOIfNiU']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.03.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] jPYnVOIfNiU: Downloading webpage
[youtube] Downloading just video jPYnVOIfNiU because of --no-playlist
[info] Writing video subtitles to: C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.en.vtt
[youtube] jPYnVOIfNiU: Downloading thumbnail ...
[youtube] jPYnVOIfNiU: Writing thumbnail to: C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.jpg
[debug] Invoking downloader on 'https://r2---sn-gwpa-pmhl.googlevideo.com/videoplayback?expire=1616415868&ei=HDhYYIyuF8OU3LUP4t2kQA&ip=2409%3A4072%3A6d08%3Aca66%3Aac8b%3Adef8%3A4deb%3Ad5c9&id=o-AI2p-iaHD-qCtekDzCZOa1DI8VZxpvhbMvVYUey0wJ4P&itag=134&aitags=133%2C134%2C160%2C242%2C243%2C278&source=youtube&requiressl=yes&mh=Ew&mm=31%2C29&mn=sn-gwpa-pmhl%2Csn-gwpa-h55r&ms=au%2Crdu&mv=m&mvi=2&pl=41&initcwndbps=190000&vprv=1&mime=video%2Fmp4&ns=aGLvj3caUtsVaKcC4ztuZoQF&gir=yes&clen=6235047&dur=158.458&lmt=1440205639665988&mt=1616394061&fvip=2&keepalive=yes&fexp=24001374%2C24007246&c=WEB&n=IAVF__zr3X-HL6feJ3&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgIlKczMFIHkGgh4xQJ7DhQ9_0HQBNxXKs1jPNeBtD-gYCIQD2Sqq24HVB8yc8Xu8J0d-Ub4-nm9Kr-ykHwMFh9qQpFg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALwF9duE7T-Xlte-Jy-41ly46d_FpSyBuWXRBjYxL8J-AiACMZer4GJSJJicWvwRm_RFGJLG4WcCn-iKlWFHB68IFg%3D%3D'
[download] Destination: C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; 360p24)YT 'TheTrailerSiteDOTcom'.f134.mp4
[download] 100% of 5.95MiB in 00:08
[debug] Invoking downloader on 'https://r2---sn-gwpa-pmhl.googlevideo.com/videoplayback?expire=1616415868&ei=HDhYYIyuF8OU3LUP4t2kQA&ip=2409%3A4072%3A6d08%3Aca66%3Aac8b%3Adef8%3A4deb%3Ad5c9&id=o-AI2p-iaHD-qCtekDzCZOa1DI8VZxpvhbMvVYUey0wJ4P&itag=140&source=youtube&requiressl=yes&mh=Ew&mm=31%2C29&mn=sn-gwpa-pmhl%2Csn-gwpa-h55r&ms=au%2Crdu&mv=m&mvi=2&pl=41&initcwndbps=190000&vprv=1&mime=audio%2Fmp4&ns=aGLvj3caUtsVaKcC4ztuZoQF&gir=yes&clen=2518665&dur=158.545&lmt=1440202745614505&mt=1616394061&fvip=2&keepalive=yes&fexp=24001374%2C24007246&c=WEB&n=IAVF__zr3X-HL6feJ3&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIq1d5yC44xmsmAckNgg7GJRg9Htcny_s8bNQlVFtyxyAiB29-0yHRuO3enNyJo72Leff5X_twNTX-r06Bdf7US6UA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALwF9duE7T-Xlte-Jy-41ly46d_FpSyBuWXRBjYxL8J-AiACMZer4GJSJJicWvwRm_RFGJLG4WcCn-iKlWFHB68IFg%3D%3D'
[download] Destination: C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; tinyNA)YT 'TheTrailerSiteDOTcom'.f140.m4a
[download] 100% of 2.40MiB in 00:06
[ffmpeg] Merging formats into "C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; 360p24)YT 'TheTrailerSiteDOTcom'.f134.mp4" -i "file:C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; tinyNA)YT 'TheTrailerSiteDOTcom'.f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.temp.mp4"
[ffmpeg] Correcting extension to webp and escaping path for thumbnail "C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.jpg"
[ffmpeg] Converting thumbnail "C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.webp" to JPEG
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.webp" "-bsf:v" mjpeg2jpeg "file:C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.jpg"
[atomicparsley] Adding thumbnail to "C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.mp4"
[debug] AtomicParsley command line: AtomicParsley "C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.mp4" --artwork "C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.jpg" -o "C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.temp.mp4"

( 22-03-2021 & 11:54:46.93 | C:\Users\Notebook> Cls
Can you enlighten me, please?
Regards, RS.

**Comment by RangaSE** [comment]
Sorry; I couldn't understand that, the colon becomes emojis. This the debug line:
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; 360p24)YT 'TheTrailerSiteDOTcom'.f134.mp4" -i "file:C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; tinyNA)YT 'TheTrailerSiteDOTcom'.f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.temp.mp4"

Regards, RS.

**Comment by RangaSE** [comment]
NOT again! I think, "0: v :0" (I deliberately put space before and after v) -map "1: a :0" transform in to emojis.

Regards, RS.

**Comment by rautamiekka** [comment]
2 words: code tag.

**Comment by dirkf** [comment]
Dr Samuel Johnson, an 18th century literary figure from the English midlands who is often credited with having created the first English dictionary, was fond of debating. On an occasion when he felt that his point had gone over the head of his partner, he [expostulated](https://www.samueljohnson.com/argument.html#308) "Sir, I have found you an argument; but I am not obliged to find you an understanding". 

I am afraid that we may have a similar problem, but to summarise: 
* "NA" ("not available", I assume) is the default value used to fill in a filename output template when a specified output template variable is not set, but can be changed with a command-line parameter;
* the `format_note` variable may not always be set and is specifically not set when the output file is the result of a merge;
* a patch, as shown, would cause the `format_note` variable to be set for a merged output file if it was set for either the video or audio components;
* this would still not help with a single (non-merged) download where `format_note` happened not to be set;
* the `resolution` output template variable is more likely to be set and **is** set for a merged output file if it was set for the video component of the download.

For example, in the last case;
```
...
[ffmpeg] Merging formats into "C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; 360p24)YT 'TheTrailerSiteDOTcom'.f134.mp4" -i "file:C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; tinyNA)YT 'TheTrailerSiteDOTcom'.f140.m4a" -c copy -map "0v0" -map "1a0" "file:C:\Users\Notebook\Videos\Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.temp.mp4"
...
```
Input filenames:
```
Air Force One Trailer (u20090825; 0,2,38_499; 360p24)YT 'TheTrailerSiteDOTcom'.f134.mp4
Air Force One Trailer (u20090825; 0,2,38_499; tinyNA)YT 'TheTrailerSiteDOTcom'.f140.m4a
```
Output filename (before renaming):
```
Air Force One Trailer (u20090825; 0,2,38_499; NA24)YT 'TheTrailerSiteDOTcom'.temp.mp4
```
With the patch suggested, that would be:
```
Air Force One Trailer (u20090825; 0,2,38_499; 360p+tiny24)YT 'TheTrailerSiteDOTcom'.temp.mp4
```
If you used `%(resolution)s_` in the output template instead of `%(format_note)s`:
```
Air Force One Trailer (u20090825; 0,2,38_499; 640x360_24)YT 'TheTrailerSiteDOTcom'.temp.mp4
```

**Comment by RangaSE** [comment]
Greetings, My Friend!
I downloaded "The Bullet Train", the Japanese film about 8 years ago with a quality of DVD Rip. 2 years ago, the same film came up with "720p" Quality; now, with "1080p" quality. Audio being the same, only video quality differs. Again, when a video being downloaded, only its video quality is mentioned. You see, all YouTube Videos talk about "video quality" only. So, I am interested in %(video_quality)s which is NOT available; next thing is %(format_note)s.
Can you do anything about it?
Regards, RS.
P.S.: How to you do the font change? Teach me, please!

**Comment by rautamiekka** [comment]
> P.S.: How to you do the font change? Teach me, please!

GitHub uses Markdown for formatting, so go read https://www.markdownguide.org/basic-syntax/#code for the code tags.

**Comment by RangaSE** [comment]
P.S: I forgot mention that, %(resolution)s did not do the desired results; whatever video quality is, resolution remains the same.
- Rgds, RS.
@rautamiekka: Thanks-A-lot for the Formatting Tip!

**Comment by dirkf** [comment]
You may like to provide some test URLs showing what resolution is being offered and what value is being used for the `resolution` output variable, eg using first the `-F` parameter (and other parameters such as `--no-playlist` if needed) and then using `--get-filename --skip-download -o ` with your output filename template, compared with what you expected it to be.

Also, although it may be too verbose, try `%(format)s".

**Comment by RangaSE** [comment]
Hello, Greetings!
It's a tough job to do, namely, "youtube-dl_2018_09_26" to "YouTube-DL[2021.04.17]"; like %(height)s, %(resolution)s, %(format_id)s, %(format)s and almost all. %(format_note)s is closest one ever, but, in the final output, it becomes NA<fps>. That's bad. May be I'll do some home work, how to get the video quality in our videos. Thanks!
Regards, RS.

**Comment by dirkf** [comment]
The original response contained the one-line change needed to preserve the values of `format_note` in a merged filename ...

**Comment by RangaSE** [comment]
Hello, Greetings!
I'm So Sorry to say, I lost my touch now; I used to do programming in BASIC (many variations), TURBO PASCAL (many versions), AutoLISP (many versions), Java, C# among others. Too saturated, I stopped programming altogether, in 2012. OOPS! BTW, can you help me:

( 09-06-2021 & 17:23:14.42 | C:\Users\Notebook> YouTube-DL[2021.06.06] -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -ciw --no-playlist --output-na-placeholder format_note --write-auto-sub --write-sub --embed-thumbnail -o "~\Videos\%(title)s (u%(upload_date)s; 0,4,14_441; %(format_note)s%(fps)s)YT '%(uploader)s'.%(ext)s" -- dGgkDBbKqVs
[youtube] dGgkDBbKqVs: Downloading webpage
[youtube] Downloading just video dGgkDBbKqVs because of --no-playlist
[youtube] dGgkDBbKqVs: Downloading player 68cc98b3
[youtube] dGgkDBbKqVs: Downloading MPD manifest
[youtube] dGgkDBbKqVs: Downloading thumbnail ...
[youtube] dGgkDBbKqVs: Writing thumbnail to: C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; format_note30)YT 'Sivasri Skandaprasad'.webp
[download] Destination: C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; 1080p30)YT 'Sivasri Skandaprasad'.f137.mp4
[download] 100% of 15.45MiB in 00:33
[download] Destination: C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; tinyformat_note)YT 'Sivasri Skandaprasad'.f140.m4a
[download] 100% of 3.93MiB in 00:08
[ffmpeg] Merging formats into "C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; format_note30)YT 'Sivasri Skandaprasad'.mp4"
Deleting original file C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; 1080p30)YT 'Sivasri Skandaprasad'.f137.mp4 (pass -k to keep)
Deleting original file C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; tinyformat_note)YT 'Sivasri Skandaprasad'.f140.m4a (pass -k to keep)
[ffmpeg] Converting thumbnail "C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; format_note30)YT 'Sivasri Skandaprasad'.webp" to JPEG
[atomicparsley] Adding thumbnail to "C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; format_note30)YT 'Sivasri Skandaprasad'.mp4"

( 09-06-2021 & 17:24:17.49 | C:\Users\Notebook> YouTube-DL[2021.06.06] -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -ciw --no-playlist --output-na-placeholder %(format_note)s --write-auto-sub --write-sub --embed-thumbnail -o "~\Videos\%(title)s (u%(upload_date)s; 0,4,14_441; %(format_note)s%(fps)s)YT '%(uploader)s'.%(ext)s" -- dGgkDBbKqVs
[youtube] dGgkDBbKqVs: Downloading webpage
[youtube] Downloading just video dGgkDBbKqVs because of --no-playlist
[youtube] dGgkDBbKqVs: Downloading MPD manifest
[youtube] dGgkDBbKqVs: Downloading thumbnail ...
[youtube] dGgkDBbKqVs: Writing thumbnail to: C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; %(format_note)s30)YT 'Sivasri Skandaprasad'.webp
[download] Destination: C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; 1080p30)YT 'Sivasri Skandaprasad'.f137.mp4
[download] 100% of 15.45MiB in 00:44
[download] Destination: C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; tiny%(format_note)s)YT 'Sivasri Skandaprasad'.f140.m4a
[download] 100% of 3.93MiB in 00:08
[ffmpeg] Merging formats into "C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; %(format_note)s30)YT 'Sivasri Skandaprasad'.mp4"
Deleting original file C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; 1080p30)YT 'Sivasri Skandaprasad'.f137.mp4 (pass -k to keep)
Deleting original file C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; tiny%(format_note)s)YT 'Sivasri Skandaprasad'.f140.m4a (pass -k to keep)
[ffmpeg] Converting thumbnail "C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; #(format_note)s30)YT 'Sivasri Skandaprasad'.webp" to JPEG
[atomicparsley] Adding thumbnail to "C:\Users\Notebook\Videos\Sivasri Skandaprasad - at age 9 singing thiruppugazh - with lyrics (u20200517; 0,4,14_441; %(format_note)s30)YT 'Sivasri Skandaprasad'.mp4"

( 09-06-2021 & 17:25:59.00 | C:\Users\Notebook> Cls
Thanks once again, ATB! Regards, RS.

**Comment by RangaSE** [comment]
Hi, Greetings! I wanted to help you, in 'Quality' option, among others. Since, learning a new language, now, difficult, I did the same in PowerShell, which I am comfortable. Only one option took severe head-ache for days; means one thing: My Prg. days are Over. Anyway, I wish show the same to you:

# ' ; File Name: C:\Users\...\YT-DL TestFiles\GetDuration.ps1 '
# GetDuration.ps1
# [YouTube API V3] New simple PowerShell script to get the duration of a YouTube video

#Powershell 4+
# It took a lot of time to find and get 'GoogleApiKey',...

function Get-Duration ([string]$VideoID){
$gdata_uri = "https://www.googleapis.com/youtube/v3/videos?id=$VideoID&key=$GoogleApiKey&part=contentDetails" #Replace <APIKEY>
$metadata = irm $gdata_uri		# <Remember> irm = Invoke-RestMethod
$duration = $metadata.items.contentDetails.duration

$td = [Xml.XmlConvert]::ToTimeSpan("$duration").TotalSeconds
[TimeSpan]::FromSeconds($td).ToString("h\,m\,s\_f")		# $td = time duration
}

# Checking 'Get-Duration' Function...
Get-Duration -VideoID dQw4w9WgXcQ	# or
Get-Duration dQw4w9WgXcQ			# Both are Working!

# Get-vQuality is to get the video Quality based on 'contentDetails.definition'; 'hd' has Different Aspect Ratio than 'sd'.
# Too much of Head-ache during these tiny prg. chunks. Better Leave it to Others. ** CAUTION: THIS Fn IS NOT TESTED!! **
function Get-vQuality ([string]$VideoID){
$gdata_uri = "https://www.googleapis.com/youtube/v3/videos?id=$VideoID&key=$GoogleApiKey&part=snippet,contentDetails" #Replace <APIKEY>
# $width shall be from (...?#?)
$metadata = irm $gdata_uri
$IsHD = $metadata.items.contentDetails.definition
$vQuality = $width * ($IsHD -eq "hd" ? 0.5625 : 0.75) + "p"
$vQuality
}
# ... To be tested! Here is the Test chunk:
Get-vQuality -VideoID dQw4w9WgXcQ

Too bad, I couldn't help in any way. My Only with is a video file shall have Video Quality than anything else.
Thanks for Your Patience. May be 'Bye for A While', as I still recover from the head ache.
Regards, RS.
