### ISSUE TITLE
Please provide support for rumble.com

### ISSUE THREAD

**Issue by ToddAndMargo** [ytdl-org/youtube-dl#28814]
Please provide support for rumble.com:

\# youtube-dl --update
Updating to version 2021.04.17 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
\# exit
exit

$ youtube-dl https://rumble.com/vepb2p-yann-tiersen-comptine-dun-autre-t-guitar-cover-amelie-movie-soundtrack.html
[generic] vepb2p-yann-tiersen-comptine-dun-autre-t-guitar-cover-amelie-movie-soundtrack: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vepb2p-yann-tiersen-comptine-dun-autre-t-guitar-cover-amelie-movie-soundtrack: Downloading webpage
[generic] vepb2p-yann-tiersen-comptine-dun-autre-t-guitar-cover-amelie-movie-soundtrack: Extracting information
ERROR: Unsupported URL: https://rumble.com/vepb2p-yann-tiersen-comptine-dun-autre-t-guitar-cover-amelie-movie-soundtrack.html

**Comment by ToddAndMargo** [comment]
How do I find the duplicate so I can watch it?

**Comment by ToddAndMargo** [comment]
Just out of curiosity, how is this a duplicate?   Doing a search of issues with"rumble" in it only comes up with this one.  Maybe you guys were thinking of something else?

**Comment by rautamiekka** [comment]
> Just out of curiosity, how is this a duplicate? Doing a search of issues with"rumble" in it only comes up with this one. Maybe you guys were thinking of something else?

When you use the `is:issue rumble` sentence in the tickets section you'll see #10785 which is the 1st request for rumble.com, 5yo no less. I tried and it didn't matter surrounding the latter with `*`, but it won't hurt adding them.

**Comment by ToddAndMargo** [comment]
$ youtube-dl https://sp.rmbl.ws/s8/2/r/j/n/E/rjnEb.caa.1.mp4?u=3&b=0

Worked.  But I had to ask a friend to dig out the address from the web page.

**Comment by ToddAndMargo** [comment]
On 4/21/21 11:38 AM, Jouni Järvinen wrote:
>     Just out of curiosity, how is this a duplicate? Doing a search of
>     issues with"rumble" in it only comes up with this one. Maybe you
>     guys were thinking of something else?
> 
> When you use the |is:issue rumble| sentence in the tickets section 
> you'll see #10785 <https://github.com/ytdl-org/youtube-dl/issues/10785> 
> which is the 1st request for rumble.com, 5yo no less. I tried and it 
> didn't matter surrounding the latter with |*|, but it won't hurt adding 
> them.

Found it.  Thank you!
