### ISSUE TITLE
unable to rename file, access denied when running as SYSTEM

### ISSUE THREAD

**Issue by mittster** [ytdl-org/youtube-dl#28812]
## Checklist

- [] I'm reporting a broken site support issue
- [] I've verified that I'm running youtube-dl version **2021.04.17**  running **2021.04.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
 [debug] System config: [] 
 [debug] User config: [] 
 [debug] Custom config: [] 
 [debug] Command-line args: ['video-to-download', '-v', '-o', 'C:\\Users\\john\\Documents\\Downloaded Videos/tmp-video 07-19-22 4-17-2021.%(ext)s', '--restrict-filenames', '--no-mtime', '--ffmpeg-location', '..\\..\\ext'] 
 [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252 
 [debug] youtube-dl version 2021.04.07 
 [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041 
 [debug] exe versions: ffmpeg git-2020-05-25-6268034 
 [debug] Proxy map: {} 
 [debug] Default format spec: bestvideo+bestaudio/best 
 ERROR: unable to rename file: [WinError 5] Access is denied: 'C:\\Users\\john\\Documents\\Downloaded Videos\\tmp-video 07-19-22 4-17-2021.mp4.part' -> 'C:\\Users\\jogn\\Documents\\Downloaded Videos\\tmp-video 07-19-22 4-17-2021.mp4' 
 Traceback (most recent call last): 
   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\downloader\common.py", line 202, in try_rename 
 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\john\\Documents\\Downloaded Videos\\tmp-video 07-19-22 4-17-2021.mp4.part' -> 'C:\\Users\\john\\Documents\\Downloaded Videos\\tmp-video 07-19-22 4-17-2021.mp4'
```

## Description

I've made a wrapper around youtube-dl and one of the users reported an error above.

youtube-dl is started from a windows service, therefore youtube-dl is running as a SYSTEM. I can verify this locally by opening Task Manager and inspecting the process.. `Downloaded Videos` is created at install time as an administrator.

The error given by youtube-dl is clear: unable to rename file due to access being denied. How is this possible if youtube-dl is running as SYSTEM? I can't reproduce the error on my own machines.

**Comment by dstftw** [comment]
You must provide reproducible environment.
