### ISSUE TITLE
How can i delete it? 

### ISSUE THREAD

**Issue by hoshiine** [ytdl-org/youtube-dl#28816]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Please how can i delete it?

**Comment by dstftw** [comment]
Depends on how you installed it in the first place.

**Comment by hoshiine** [comment]
> Depends on how you installed it in the first place.
ive downloaded from the link on the site written as :
 Windows users can download an .exe file and place it in any location on their PATH except for %SYSTEMROOT%\System32 (e.g. do not put in C:\Windows\System32).

and just double clicked on it then a command table flashed , thats all i know.

**Comment by pukkandan** [comment]
just delete the file you double-clicked on
