### ISSUE TITLE
[scatbook] Requesting extraction for new site

### ISSUE THREAD

**Issue by rusemode** [ytdl-org/youtube-dl#28821]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.04.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://scatbook.com/posts/10010072

## Description

I've tried other methods of downloading but no luck so far, I was hoping you could help me.

**Comment by TakeOFFF** [comment]
I was hoping you could help me too: How do I download it?

**Comment by loveyoupuke** [comment]
can somebody download these videos for me please https://scatbook.com/posts/10096525 https://scatbook.com/posts/10116843 https://scatbook.com/posts/10118866 https://scatbook.com/posts/10121965
https://scatbook.com/posts/10200379
