### ISSUE TITLE
--fragment-retries "infinite" and -R "infinite" do not function properly

### ISSUE THREAD

**Issue by Midnoclose** [ytdl-org/youtube-dl#28828]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

I have attached the log separately due to the fact that it is over 4,000 lines long. [log.txt](https://github.com/ytdl-org/youtube-dl/files/6354465/log.txt)

## Description

When I attempt to download a video from crunchyroll.com, it will occasionally skip segments without attempting to retry, even with --fragment-retries "infinite" and -R "infinite" enabled. This could be fixed by making the program actually attempt to retry downloading a segment when it fails instead of skipping over it when these arguments are present.

**Comment by dstftw** [comment]
ffmpeg does not support fragment retry.

**Comment by Midnoclose** [comment]
should I use --hls-prefer-native to be able to download a complete video then?

**Comment by Midnoclose** [comment]
Just to follow up, using the argument `--hls-prefer-native` did solve my problem.
