### ISSUE TITLE
I cant download a full playlist on pornhub

### ISSUE THREAD

**Issue by justafuckingweeb** [ytdl-org/youtube-dl#28820]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: ['-f', 'mp4', '-f', 'best', '-o', 'C:/youtube-dl-downloads/%(title)s.%(ext)s', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['https://de.pornhub.com/playlist/137323281', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.04.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[download] Downloading playlist: playlist/137323281
[PornHubPagedVideoList] playlist/137323281: Downloading page 1
[PornHubPagedVideoList] playlist playlist/137323281: Downloading 36 videos
[download] Downloading video 1 of 36
[PornHub] ph5e31e05951255: Downloading pc webpage
[PornHub] ph5e31e05951255: Downloading JSON metadata
[PornHub] ph5e31e05951255: Downloading m3u8 information
[PornHub] ph5e31e05951255: Downloading m3u8 information
[PornHub] ph5e31e05951255: Downloading m3u8 information
[PornHub] ph5e31e05951255: Downloading m3u8 information
[PornHub] ph5e31e05951255: Downloading m3u8 information
[debug] Invoking downloader on 'https://ev.phncdn.com/videos/202001/29/280407851/720P_4000K_280407851.mp4?validfrom=1618978492&validto=1618985692&rate=500k&burst=1200k&ipa=84.175.80.83&hash=7BtIPIoUBrY1Uh5wFgoETp%2FVA44%3D'
[download] Destination: C:\youtube-dl-downloads\Gymshark girl getting fucked after a workout - Amateur Saerosoh.mp4
[download] 100% of 36.02MiB in 01:11
[download] Downloading video 2 of 36
[PornHub] ph5c843f690b7c1: Downloading pc webpage
[PornHub] ph5c843f690b7c1: Downloading JSON metadata
[PornHub] ph5c843f690b7c1: Downloading m3u8 information
[PornHub] ph5c843f690b7c1: Downloading m3u8 information
[PornHub] ph5c843f690b7c1: Downloading m3u8 information
[debug] Invoking downloader on 'https://ev.phncdn.com/videos/201903/09/212186612/480P_2000K_212186612.mp4?validfrom=1618978564&validto=1618985764&rate=500k&burst=1000k&ipa=84.175.80.83&hash=BLOfCCj3Mlqvx6NmoUT0ez4SUFY%3D'
[download] Destination: C:\youtube-dl-downloads\TIGHT ASIAN SLUT WITH GLASSES FUCKED DOGGY ON A CHAIR.mp4
[download] 100% of 12.66MiB in 00:23
[download] Downloading video 3 of 36
[PornHub] ph5e32344ba0505: Downloading pc webpage
[PornHub] ph5e32344ba0505: Downloading JSON metadata
[PornHub] ph5e32344ba0505: Downloading m3u8 information
[PornHub] ph5e32344ba0505: Downloading m3u8 information
[PornHub] ph5e32344ba0505: Downloading m3u8 information
[PornHub] ph5e32344ba0505: Downloading m3u8 information
[debug] Invoking downloader on 'https://ev.phncdn.com/videos/202001/30/280449181/720P_4000K_280449181.mp4?validfrom=1618978588&validto=1618985788&rate=500k&burst=1400k&ipa=84.175.80.83&hash=UC%2Fg7qaZOke7pSzzMrn%2F9ZgZlJc%3D'
[download] Destination: C:\youtube-dl-downloads\ASIAN GIRL GETS DICKED DOWN ON CARNIVAL CRUISE.mp4
[download] 100% of 75.24MiB in 02:31
[download] Downloading video 4 of 36
[PornHub] ph5db08ae4df6e4: Downloading pc webpage
[PornHub] ph5db08ae4df6e4: Downloading JSON metadata
[PornHub] ph5db08ae4df6e4: Downloading m3u8 information
[PornHub] ph5db08ae4df6e4: Downloading m3u8 information
[PornHub] ph5db08ae4df6e4: Downloading m3u8 information
[PornHub] ph5db08ae4df6e4: Downloading m3u8 information
[PornHub] ph5db08ae4df6e4: Downloading m3u8 information
[debug] Invoking downloader on 'https://ev.phncdn.com/videos/201910/23/256759992/720P_4000K_256759992.mp4?validfrom=1618978742&validto=1618985942&rate=500k&burst=1000k&ipa=84.175.80.83&hash=T1SpSC7KvnjrOSYiuKBO4ASK25g%3D'
[download] Destination: C:\youtube-dl-downloads\this blowjob has no chill 1.mp4
[download] 100% of 6.90MiB in 00:12
[download] Downloading video 5 of 36
[PornHub] ph5c3f04ebdcba2: Downloading pc webpage
[PornHub] ph5c3f04ebdcba2: Downloading JSON metadata
[PornHub] ph5c3f04ebdcba2: Downloading m3u8 information
[PornHub] ph5c3f04ebdcba2: Downloading m3u8 information
[PornHub] ph5c3f04ebdcba2: Downloading m3u8 information
[PornHub] ph5c3f04ebdcba2: Downloading m3u8 information
[debug] Invoking downloader on 'https://dv.phncdn.com/videos/201901/16/202072592/720P_4000K_202072592.mp4?ttl=1618985955&ri=1024000&rs=4000&ipa=84.175.80.83&hash=c2fd2509d15c8ea601eab17057b073c4'
[download] Destination: C:\youtube-dl-downloads\Hot guy pounds me from behind.mp4
[download] 100% of 15.84MiB in 00:28
[download] Downloading video 6 of 36
[PornHub] ph5ca04d4a4c27a: Downloading pc webpage
[PornHub] ph5ca04d4a4c27a: Downloading JSON metadata
[PornHub] ph5ca04d4a4c27a: Downloading m3u8 information
[PornHub] ph5ca04d4a4c27a: Downloading m3u8 information
[PornHub] ph5ca04d4a4c27a: Downloading m3u8 information
[PornHub] ph5ca04d4a4c27a: Downloading m3u8 information
[debug] Invoking downloader on 'https://ev.phncdn.com/videos/201903/31/215842371/720P_4000K_215842371.mp4?validfrom=1618978785&validto=1618985985&rate=500k&burst=1000k&ipa=84.175.80.83&hash=hh6fdg%2FwRgzedbSZoHCuhPtrEEg%3D'
[download] Destination: C:\youtube-dl-downloads\Tight Asian Pussy Takes White Dick.mp4
[download] 100% of 31.16MiB in 01:01
[download] Downloading video 7 of 36
[PornHub] ph5def947f78f06: Downloading pc webpage
[PornHub] ph5def947f78f06: Downloading JSON metadata
[PornHub] ph5def947f78f06: Downloading m3u8 information
[PornHub] ph5def947f78f06: Downloading m3u8 information
[PornHub] ph5def947f78f06: Downloading m3u8 information
[PornHub] ph5def947f78f06: Downloading m3u8 information
[PornHub] ph5def947f78f06: Downloading m3u8 information
[debug] Invoking downloader on 'https://ev.phncdn.com/videos/201912/10/267618252/720P_4000K_267618252.mp4?validfrom=1618978848&validto=1618986048&rate=500k&burst=1800k&ipa=84.175.80.83&hash=OdJjelpnaijswUswp8%2Bayc5c%2FJ4%3D'
[download] Destination: C:\youtube-dl-downloads\You made ME WAIT! I better cum A LOT before you creampie my pussy!.mp4
[download]  26.7% of 156.58MiB at 517.63KiB/s ETA 03:47
(im just gonna cut it here because i dont want to wait until 36 videos are downloaded)

## Description

WRITE DESCRIPTION HERE
i am not able to download a full playlist on pornhub.com. i have seen multiple other posts with the same problem but all the solutions that were given there didnt work for me. I always had this problem. It wasnt after a specific update as far as i know. I can download youtube playlists no problem. Pornhub is the only site (that i use) where i have this problem.

**Comment by dstftw** [comment]
You must pass credentials or authenticated cookies.

**Comment by justafuckingweeb** [comment]
> 
> 
> You must pass credentials or authenticated cookies.

i dont know how to do any of that. i assume that you mean the --username and --passoword thingy. that didnt work for me. idk what authenticated cookies are tho
