### ISSUE TITLE
Is the download supposed to be pausable using the .exe on Windows when clicking into the cmd?

### ISSUE THREAD

**Issue by Myrthian** [ytdl-org/youtube-dl#28826]
## Checklist
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
My knowledge regarding shells in general is almost non-existent, but is youtube-dl supposed to pause its current download when 
I left-click into the cmd?

I can unpause with seemingly any key + right-click into the cmd.

**Comment by ehoogeveen-medweb** [comment]
I could be wrong but I think this is the effect of QuickEdit mode, which you can turn off in the properties of the command window. I think it prevents console output from running applications to let you copy/paste text from inside the window, and this has the effect of pausing programs when they try to update a progress bar or something similar. Then when you leave QuickEdit mode, the print call finally goes through and the program resumes.
