### ISSUE TITLE
[FanCode.com] Sports videos and streaming site geo-restricted to India

### ISSUE THREAD

**Issue by m3jorri** [ytdl-org/youtube-dl#28839]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.04.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://fancode.com/video/15043/match-preview-pbks-vs-mi
- Live streams: Static URL not available

## Description

FanCode is an official video and live streaming site for multiple sporting events. Uses Brightcove player with Akamai CDN. It is geo-restricted to India. Many videos do not require an account. Livestreams do require an account, which can be created using Google credentials. Some livestreams are free while others are paid.

It would be nice to have a support for both, video and livestreams in youtube-dl. Thank you.

 @remitamine @dstftw

**Comment by gotlougit** [comment]
I'm a first time contributor and would like to work on adding support for this site.

**Comment by gotlougit** [comment]
This website appears to use an external player called Brightcove player, and the webpage youtube-dl downloads doesn't contain the <video> tag at all. In fact, I saved the webpage that youtube-dl gets to disk and that webpage doesn't have the video at all.

**Comment by gotlougit** [comment]
The <video> tag isn't even present in the webpage that youtube-dl downloads.

**Comment by m3jorri** [comment]
Can someone suggest an already implemented extractor with Brightcove+Akamai? It might be a good reference point.

**Comment by gotlougit** [comment]
I'm afraid I've bit off more than I can chew; I simply do not know enough about youtube-dl in order to add a new extractor. That is also why I've added another issue #29040 so that in the future this situation does not occur again.
