### ISSUE TITLE
[Feature request / enhancement] ERROR: Unsupported URL: xyz | Please provide more useful information to the end-user on the commandline about this error

### ISSUE THREAD

**Issue by rubyFeedback** [ytdl-org/youtube-dl#28830]
- [X] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2021.04.17**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

Recently I had to recompile openssl, and youtube-dl, because whenever I tried to
use it, I got a segfault. I am quite sure this is due to my openssl installation being
semi-borked. Anyway.

I tried to download from redtube :P

And got this:

    ERROR: Unsupported URL: https://www.redtube.com/?search=DONT_ASK

My problem is: it does not tell me WHY it failed. I am 100% certain the URL is fine;
because it worked before. So I think something is wrong with my openssl installation.

I'll fix that eventually, but could youtube-dl also show an additional line, or a hint?
To tell the user what an "unsupported URL" really means? Because I can tell you
that the URL is supported - it just CURRENTLY does not work, but it is 100%
supported, so that message is, strictly speaking, misleading.

I can't come up with a better description but perhaps something that tells us,
as a user, what the error may be, such as "incomplete openssl support
(function bla unavailable)" or something like this. Right now I am clueless
as to how to resolve this. I suppose I'll recompile both openssl and python,
but in the event that recompiling is not necessary, it would be nice if the
message could be more useful.

**Comment by dstftw** [comment]
It means exactly what it spells.
