### ISSUE TITLE
ManyVids

### ISSUE THREAD

**Issue by IcedLime2001** [ytdl-org/youtube-dl#28837]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I read that **ManyVids** is listed in the list of [supported sites](https://github.com/ytdl-org/youtube-dl/blob/master/docs/supportedsites.md).
Excuse me if you find my question stupid but I've no programming knowledge and I've made several unsuccessful attempts: how do you download _entirely_ the videos from ManyVids? I've the latest version of youtube-dl, I've read the past Issues about this websites, here I post a screenshot showing what happens when I try to download a vid from ManyVids after logging in with my account.
![115692032-e63ddf80-a35e-11eb-97a8-f63fd26d8fb2](https://user-images.githubusercontent.com/82949568/115724758-886ebf00-a381-11eb-8888-3b312515aa3e.png)
Generally, I can download the **10 seconds preview** of the video as said in #28758  (except for some who have a _lock_ and I don't know how to download them), but never the _whole_ video uploaded by the performers. 
I really don't understand😢.

**Comment by rautamiekka** [comment]
Don't censor the links, and give the links in the post too, not just a screenshot.

**Comment by dstftw** [comment]
Full videos are not supported.

**Comment by chill-otter** [comment]
> Full videos are not supported.

**Comment by dirkf** [comment]
Duplicate of #28758.
