### ISSUE TITLE
How to skip the first sleep settings?

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [ytdl-org/youtube-dl#28847]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm downloading a series of videos and I can use `--sleep-interval 420 --max-sleep-interval 600` to make `youtube-dl` sleep some random periods before downloading the video. However, when it started to download the first video in the series, it also sleeps some time, which is unnecessary. How can I disable sleeping for the first video in the download of a series videos?

**Comment by dstftw** [comment]
You can't.

**Comment by dirkf** [comment]
Currently, the only solution is to have started the download earlier.

The delay logic is independent of which item in the list (implicit or explicit) is being downloaded.

A developer could try replacing line 1901 of `YoutubeDL.py` as follows:
```
-                    fd = get_suitable_downloader(info, self.params)(self, self.params)
+                    params = self.params
+                    if self._num_downloads == 1:
+                        try:
+                            if params.get('sleep_interval') >= 0:
+                                params.update({'sleep_interval': None})
+                        except:
+                            pass
+                    fd = get_suitable_downloader(info, self.params)(self, params)
```
Also, the developer might find the following issues:
* specifying `--min-sleep-interval 0` or `--sleep-interval 0` apparently causes the delay logic to be skipped (parameter tested for truthy at `downloader/common.py:357`, should test for number >= 0), which would not be expected when a positive value for `--max-sleep-interval` is given;
* the  `--min-sleep-interval` option is not separately specified in `README.md` and is misspelled when references under `--max-sleep-interval`.
