### ISSUE TITLE
[Missing Dependency]  Microsoft Visual C++ 2010 Redistributable Package (x86) is no longer available on the microsoft website. 

### ISSUE THREAD

**Issue by vellaG** [ytdl-org/youtube-dl#28845]
Microsoft Visual C++ 2010 Redistributable Package (x86) is no longer available on the microsoft website. 

Future Windows uses cannot use youtube-dl if they do not have the redistributable package already installed.

**Comment by rautamiekka** [comment]
I think https://www.microsoft.com/en-us/download/details.aspx?id=26999 is the successor; I think M$ realized having the old package available is only confusing. The installers are bigger, so they must be the real deal.

But if that goes too,
- https://download.cnet.com/Microsoft-Visual-C-2010-Redistributable-Package-x86/3000-2383_4-75451146.html
- and https://drive.google.com/drive/folders/0B6Z3ucpyN1X2eHdqX2llTS05OWs

has it.

**Comment by okand** [comment]
Just ran into this when trying to run youtube-dl for the first time on my work computer (after having placed it together with a windows build of mpv several weeks ago). Installing that x86 redistributable made it work so the link on the youtube-dl website should probably be updated.

**Comment by Xiseous** [comment]
As rautamiekka commented I just wanted to add some more info that all the C++ Redistributables can be downloaded from techpowerup. They provide a all in one zip with even a batch script to silent install all of them.

Link: https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

**Comment by rautamiekka** [comment]
Good. Now here's hoping M$ won't abuse the DMCA. Pretty sure free and runtimes aren't covered, but only a court could say for certain.
