### ISSUE TITLE
[Upgrading problem] Fail to upgrade from 2021.4.7 to 2021.4.17

### ISSUE THREAD

**Issue by EmmW** [ytdl-org/youtube-dl#28856]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

System environment: Mac OS X 10.14.6

So in Terminal I have just run "brew update && brew upgrade" for a general upgrade of all brew components/extensions. After that I ran "youtube-dl --version" to double-check and surprisingly got back "2021.4.07". When I checked the parser it clearly appears that youtube-dl was indeed successfully upgraded:

==> Upgrading youtube-dl 2021.4.7 -> 2021.4.17 
==> Downloading https://ghcr.io/v2/homebrew/core/youtube-dl/manifests/2021.4.17
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/youtube-dl/blobs/sha256:5bb2b85c53a5519077df1a9d2efd2bed1a4b52259e5ffc4aa6054de2f8383b73
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:5bb2b85c53a5519077df1a9d2efd2bed1a4b52259e5ffc4aa6054de2f8383b73?se=2021-04-24T12%3A55%3A00Z&sig=BhxH
######################################################################## 100.0%
==> Pouring youtube-dl--2021.4.17.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/youtube-dl/2021.4.17: 1,395 files, 13.5MB
Removing: /usr/local/Cellar/youtube-dl/2021.4.7... (1,394 files, 15.2MB)
Removing: /Users/myname/Library/Caches/Homebrew/youtube-dl--2021.4.7... (3.5MB)

I therefore tried again with "brew upgrade youtube-dl" and then got back "Warning: youtube-dl 2021.4.17 already installed". Another "youtube-dl --version" gave the same result: "2021.04.07"

Hence my question: What is wrong in my brew/youtube-dl configuration, and how do I go about to sort this out via Terminal commands..?

**Comment by dstftw** [comment]
Address this to homebrew support.
