### ISSUE TITLE
Question about some warning I got while trying pip3 install youtube-dl

### ISSUE THREAD

**Issue by tanja84dk** [ytdl-org/youtube-dl#28867]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Host alpine Docker container

I have a question does the script try to run something with sudo within the package when I do a pip3 install youtube-dl?

Noticed this warning for the first time when I tried to build my new Docker container and have never seen it before so thats why I thought perhaps it were some warning from the package.

And the weird thing is that I have used the same docker setup to build containers for months without that error and also other containers doesnt give that warning even that they are building the same way.

+ pip3 install youtube-dl
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/include/python3.9/UNKNOWN
sysconfig: /usr/local/include/python3.9
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Collecting youtube-dl
  Downloading youtube_dl-2021.4.26-py2.py3-none-any.whl (1.9 MB)
Installing collected packages: youtube-dl
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/include/python3.9/UNKNOWN
sysconfig: /usr/local/include/python3.9
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Successfully installed youtube-dl-2021.4.26
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv

**Comment by dstftw** [comment]
Nothing to do with youtube-dl. Both warnings come from pip, follow the issue linked for info.
