### ISSUE TITLE
Funimation fails to parse JSON

### ISSUE THREAD

**Issue by en1gma713** [ytdl-org/youtube-dl#28879]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.funimation.com/shows/talentless-nana/healing/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.9.4 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Funimation] healing: Downloading webpage
WARNING: [Funimation] healing: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/youtube_dl/extractor/funimation.py", line 96, in _real_extract
    player_url = self._html_search_meta([
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1140, in _html_search_meta
    return self._html_search_regex(
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Funimation extractor fails to parse JSON.

**Comment by jparnell8839** [comment]
Same thing happening on the Windows side as well:

`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--cookies', 'cookies.txt', 'https://www.funimation.com/shows/dr-stone/secret-mission', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.21364
[debug] exe versions: ffmpeg 2021-04-14-git-c5ca18fd1b-full_build-www.gyan.dev, ffprobe 2021-04-14-git-c5ca18fd1b-full_build-www.gyan.dev
[debug] Proxy map: {}
[Funimation] Logging in
[Funimation] secret-mission: Downloading webpage
WARNING: [Funimation] secret-mission: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\funimation.py", line 100, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 1142, in _html_search_meta
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by en1gma713** [comment]
Regex is not matching the URL for the video player to be used in finding the video ID. I think the extractor is outdated and needs to be updated.

**Comment by en1gma713** [comment]
The URL for the video player is stored in the src attribute of the iframe element with the id "player". Updating the Regex to match this could fix the issue.

**Comment by meap98** [comment]
the new video player is very buggy right now I don't know how long it will be for someone of figure out what to do to be able to download from Funimation I want to know when this will start to work again because I can't stand funimations video player

**Comment by en1gma713** [comment]
The unit test for the Funimation extractor fails, I think the extractor needs to be updated.

**Comment by meap98** [comment]
how long do you think it will take for Funimation to work again

**Comment by en1gma713** [comment]
I'm not sure; it'll be after someone fixes the extractor. After that the updated extractor will be included in the next release.

**Comment by True-King** [comment]
I am having the same issue. Hope it gets fixed soon

**Comment by joshbrown50** [comment]
From what I can tell, funimation switched over to using brightcove as a hosting service for their videos. I looked and there is an extractor for brightcove already in youtube-dl so hopefully it's as simple as making a few tweaks to the brightcove extractor and using it for funimation. But I don't know how to do that. So I hope someone can look into this soon.

**Comment by en1gma713** [comment]
The file is less outdated than I thought; I believe the only problems are the HTML metadata searches and bad Regex.

**Comment by True-King** [comment]
So we will have a patch pretty soon than we thought right

**Comment by Sipherdrakon** [comment]
Eh probably not, as the entire layout of the website has changed. The urls are now wrong and it just says that the website is unsupported as the urls the extractor used to look for are now gone.

**Comment by en1gma713** [comment]
Not everything has changed, KANE and TITLE_DATA (the major parts) will still work once the regex is fixed.

**Comment by Sipherdrakon** [comment]
Well I think the new layout is going to be something like this look "https://www.funimation.com/shows/magikano/?qid=None" but it doesn't look like they have done this to all shows yet. I don't know how much everything else has changed just noticed a layout change.

**Comment by Sipherdrakon** [comment]
but it does seem that for now the actual episode pages don't seem to have changed, so hopefully you are right and it just needs some updating to the regex. :-)

**Comment by meap98** [comment]
there are changes to the episode page but the changes are with how the video is laid out like you can't pick dubbed or subbed when you pick the episode it would edit the url of the to be applied and the way youtube-dl downloaded it was through the url of the episode meaning you can't make the switch from dubbed or subbed anymore

**Comment by en1gma713** [comment]
I'm pretty sure you will be able to pick dubbed/subbed through youtube-dl's -f flag. Most likely dubbed vs. subbed is also in the metadata.

**Comment by Mobius-String** [comment]
A temp fix is changing line 20 in the extractor to

**Comment by Mobius-String** [comment]
A temporary fix is changing line 20 in funimation.py to:

_VALID_URL = r'https?://(?:www\.)?funimation(?:\.com|now\.uk)/(?:en|jp)/shows/[^/]+/(?P<id>[^/?#&]+)'

I'm sure there's a more comprehensive way to do this but I'm no python expert.

**Comment by en1gma713** [comment]
That will definitely fix the problem of valid URLs.

**Comment by joshbrown50** [comment]
@dstftw What is this a duplicate of? Can you link it so I can follow that one? Because to me it looks like you just closed all of the issues pertaining to this problem without any fixes being issued
