### ISSUE TITLE
Facebook has recently updated the pages and extractor can not find the URL to download

### ISSUE THREAD

**Issue by Quanbui1988** [ytdl-org/youtube-dl#28878]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
youtube-dl --verbose https://www.facebook.com/aldycole18/videos/363552715037871/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.facebook.com/aldycole18/videos/363552715037871/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Git HEAD: 9108a26
[debug] Python version 3.6.9 (CPython) - Linux-5.4.0-72-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg N-98588-gcbb6ba2, ffprobe N-98588-gcbb6ba2, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 363552715037871: Downloading webpage
[facebook] 363552715037871: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/home/binh/video-analysis/venv/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
return func(self, args, *kwargs)
File "/home/binh/video-analysis/venv/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
ie_result = ie.extract(url)
File "/home/binh/video-analysis/venv/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 534, in extract
ie_result = self._real_extract(url)
File "/home/binh/video-analysis/venv/lib/python3.6/site-packages/youtube_dl/extractor/facebook.py", line 677, in _real_extract
return self._extract_from_url(real_url, video_id)
File "/home/binh/video-analysis/venv/lib/python3.6/site-packages/youtube_dl/extractor/facebook.py", line 591, in _extract_from_url
raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
PASTE VERBOSE LOG HERE
```

## Description

I found that recently Facebook has updated their pages, it seems that the current FB extractors can not find the URL from the facebook pages.
I tried with many videos and all failed to download.

This is example video link : https://www.facebook.com/aldycole18/videos/363552715037871/
 With new structure, there are no: onPageletArrive. 
Then this code can not extract video
`        if not video_data:
            server_js_data = self._parse_json(self._search_regex([
                r'bigPipe\.onPageletArrive\(({.+?})\)\s*;\s*}\s*\)\s*,\s*["\']onPageletArrive\s+' + self._SUPPORTED_PAGLETS_REGEX,
                r'bigPipe\.onPageletArrive\(({.*?id\s*:\s*"%s".*?})\);' % self._SUPPORTED_PAGLETS_REGEX
            ], webpage, 'js data', default='{}'), video_id, js_to_json, False)
            video_data = extract_from_jsmods_instances(server_js_data)`

**Comment by binhnd102** [comment]
I have the same problem as you.

**Comment by RealStickman** [comment]
Same problem though I tried it with a link like this: [https://www.facebook.com/watch/?v=1588765314515302](https://www.facebook.com/watch/?v=1588765314515302)  
I also tried it with the short link facebook creates when sharing the video. Like this: [https://fb.watch/5DKmMp4hW4/](https://fb.watch/5DKmMp4hW4/)

**Comment by aws23su** [comment]
same here

**Comment by dstftw** [comment]
You must authenticate with credentials or cookies.
