### ISSUE TITLE
--dump-json not returning valid JSON when being used with a YouTube playlist

### ISSUE THREAD

**Issue by ainsey11** [ytdl-org/youtube-dl#28875]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.04.26**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--no-call-home', u'--dump-json', u'https://www.youtube.com/playlist?list=PLVJa0bdiLG6H9zOYoNEt_J-PtQFrp22wx']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2021.04.17
[debug] Python version 2.7.18 (CPython) - Linux-5.8.0-50-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Default format spec: bestvideo+bestaudio/best
```

## Description

When running youtube-dl as follows: 
```
youtube-dl --verbose --no-call-home --dump-json https://www.youtube.com/playlist?list=PLVJa0bdiLG6H9zOYoNEt_J-PtQFrp22wx 
```

The output created does not appear to be valid json.

For example the result returned by the command above : https://gist.github.com/ainsey11/194d475b925341497ed7f998d52d89e2

if you run this through a simple JSON parser, it errors, example code:

```
❯ node
Welcome to Node.js v16.0.0.
Type ".help" for more information.
> JSON.parse(fs.readFileSync('./debug.log').toString())
Uncaught SyntaxError: Unexpected token { in JSON at position 37665
```

you can see on the end of the rows in the gist, that there is no , seperator and that the bottom row appears to be missing a closing object char `}` 

Please can you advise if this is a bug or expected behaviour?

**Comment by ainsey11** [comment]
Output from a common online JSON validator too:

![image](https://user-images.githubusercontent.com/6608275/116066279-c7518d00-a67f-11eb-9ce0-77d940499869.png)

**Comment by dirkf** [comment]
The `info_dict` for each playlist item is separately dumped. Try `--dump-single-json` for your application: the items are in a list that is the value of the `entries` element of the JSON object returned.

**Comment by ainsey11** [comment]
That's perfect and worked for my use case,

it's a slightly different to the format I was expecting but I can still work with the output, that was very useful and thank you!

**Comment by ainsey11** [comment]
Marking as closed as expected behaviour
