### ISSUE TITLE
Unable to extract

### ISSUE THREAD

**Issue by pepebc** [ytdl-org/youtube-dl#28873]
**Unable to extract**
youtube-dl version: 2021.04.26
Traceback:
_youtube-dl -v -o - "https://www.skylinewebcams.com/es/webcam/italia/lazio/latina/sperlonga-piazza-fontana.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-o', '-', 'https://www.skylinewebcams.com/es/webcam/italia/lazio/latina/sperlonga-piazza-fontana.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-66-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[SkylineWebcams] sperlonga-piazza-fontana: Downloading webpage
ERROR: Unable to extract stream url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/skylinewebcams.py", line 28, in _real_extract
    stream_url = self._search_regex(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract stream url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output._

**Comment by mesosbrodleto** [comment]
same issue here, and same version of youtube.dl

**Comment by PieroMacaluso** [comment]
Hello there!
I implemented the fix to make it work again. Hope that soon it will be reviewed and integrated into the next version.
It was caused by some changes in the SkylineWebcams website.

**Comment by pepebc** [comment]
All is OK now, THANKS !!
