### ISSUE TITLE
[abc.net.au:iview] extractor update required

### ISSUE THREAD

**Issue by ProgrammerAKL** [ytdl-org/youtube-dl#28874]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe -o "C:/Video/%(title)s.%(ext)s" "https://iview.abc.net.au/video/NU2101H098S00" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:/Video/%(title)s.%(ext)s', 'https://iview.abc.net.au/video/NU2101H098S00', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 1.134.133.170 (AU) as X-Forwarded-For.
[abc.net.au:iview] NU2101H098S00: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('playlist',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\abc.py", line 135, in _real_extract
KeyError: 'playlist'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\abc.py", line 135, in _real_extract
KeyError: 'playlist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpvjygsik_\build\youtube_dl\extractor\common.py", line 545, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('playlist',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Please figure out why the existing extractor suddenly stopped working.

**Comment by section83** [comment]
Very odd.  That URL works in YTDL for me.  In my test YTDL passed the DL to FFmpeg.  Have you installed FFmpeg ?

Here's an extract of the verbose response I got:

> [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-errors', u'--newline', u'--recode-video', u'mp4', u'--postprocessor-args', u'-codec copy', u'--no-overwrites', u'--verbose', u'-o', u'%(series)s-%(title)s.%(ext)s', u'https://iview.abc.net.au/video/NU2101H098S00']
[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
[debug] youtube-dl version 2021.04.26
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2-tessus, ffprobe 4.3.2-tessus
[debug] Proxy map: {}
[debug] Using fake IP 1.159.12.72 (AU) as X-Forwarded-For.
[abc.net.au:iview] NU2101H098S00: Downloading JSON metadata
[abc.net.au:iview] NU2101H098S00: Downloading webpage
[abc.net.au:iview] NU2101H098S00: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/nu2/NU2101H098S00MA1D1_20210424193900_,1500000,1000000,650000,500000,220000,.mp4.csmil/index_0_av.m3u8?null=0&id=AgCfxHUUuFSlXXlnh2B0PWtwR4oTw4rAYuA5K48lKtWxbXNrcdn2pFpyAlqXlkA06jl0FckYR4Av3g%3d%3d'
[hlsnative] Downloading m3u8 manifest
WARNING: hlsnative has detected features it does not support, extraction will be delegated to ffmpeg
[download] Destination: ABC News NSW-24_4_2021.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
X-Forwarded-For: 1.159.12.72
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.126 Safari/537.36
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: hdntl=exp=1619572985~acl=%2f*~data=hdntl~hmac=72e954e0675a13b5f7492a5109738e58a549017cb7643d83567832f83b47a3fa
' -i 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/nu2/NU2101H098S00MA1D1_20210424193900_,1500000,1000000,650000,500000,220000,.mp4.csmil/index_0_av.m3u8?null=0&id=AgCfxHUUuFSlXXlnh2B0PWtwR4oTw4rAYuA5K48lKtWxbXNrcdn2pFpyAlqXlkA06jl0FckYR4Av3g%3d%3d' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:ABC News NSW-24_4_2021.mp4.part'
ffmpeg version 4.3.2-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[tcp @ 0x7fea06e04500] Starting connection attempt to 184.84.165.97 port 80
[tcp @ 0x7fea06e04500] Successfully connected to 184.84.165.97 port 80
[hls @ 0x7fea07009000] Skip ('#EXT-X-ALLOW-CACHE:YES')
[hls @ 0x7fea07009000] Skip ('#EXT-X-VERSION:2')
[hls @ 0x7fea07009000] HLS request for url 'http://iviewhls-i.akamaihd.net/i/playback/_definst_/_video/nu2/NU2101H098S00MA1D1_20210424193900_,1500000,1000000,650000,500000,220000,.mp4.csmil/segment1_0_av.ts?null=0&id=AgCfxHUUuFSlXXlnh2B0PWtwR4oTw4rAYuA5K48lKtWxbXNrcdn2pFpyAlqXlkA06jl0FckYR4Av3g%3d%3d', offset 0, playlist 0

**Comment by bnw42** [comment]
Works fine for me too. Note that iview reinstated geoblocking within the past week, as commented on with a similar issue report re iview made last week. That post also flagged an extractor issue. The OP then used a VPN connection to Australia and yt-dl worked fine.

**Comment by dirkf** [comment]
Now out of date.
