### ISSUE TITLE
Kanopy

### ISSUE THREAD

**Issue by crumhirnd** [ytdl-org/youtube-dl#28887]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How can I download a video from kanopy.com using youtube-dl?

**Comment by CHJ85** [comment]
Kanopy is not supported.

**Comment by crumhirnd** [comment]
Is it possible to add support? This is the mpd manifest I extracted from inspect element on Chrome.
[master.txt](https://github.com/ytdl-org/youtube-dl/files/6384912/master.txt)

**Comment by CHJ85** [comment]
Submit a request ticket.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/20423
