### ISSUE TITLE
Instagram: Unable to extract video url 

### ISSUE THREAD

**Issue by TaktakTaktouk** [ytdl-org/youtube-dl#28890]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl "https://www.instagram.com/tv/COJ1EIAlHtP/?igshid=dedqjbzkngqq" --force-ipv4 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.instagram.com/tv/COJ1EIAlHtP/?igshid=dedqjbzkngqq', u'--force-ipv4', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.27
[debug] Python version 2.7.13 (CPython) - Linux-5.4.19-x86_64-with-debian-9.13
[debug] exe versions: ffmpeg 3.2.15-0, ffprobe 3.2.15-0
[debug] Proxy map: {}
[Instagram] COJ1EIAlHtP: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/instagram.py", line 240, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1130, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

But When I try the same command from an other IP address it works well.

**Comment by crumhirnd** [comment]
you can use inspect element to get the video link

**Comment by TaktakTaktouk** [comment]
Thank you for your answer, but I want to download the video automatically

**Comment by RingoTheDog** [comment]
#28753 
https://github.com/ytdl-org/youtube-dl/issues/28753#issuecomment-820578971

**Comment by mayeaux** [comment]
Having the same experience. Certain ips are blocked.

**Comment by TaktakTaktouk** [comment]
after checking with --write-pages I found out that it redirect me to the login page. So the only way is to force using cookies

**Comment by mayeaux** [comment]
Perhaps you could proxy the request as well?

**Comment by someziggyman** [comment]
Same thing here.. worked like 2 or 3 times times and then always redirects to login page (even in browser)... 
Earlier this behaviour was explained to me as "Instagram detecting VPNs" and I've been downvoted and laughed at  https://github.com/ytdl-org/youtube-dl/issues/28753#issuecomment-819875084
Now this is happening without VPNs.

Test link:
https://www.instagram.com/p/BRi-nkOgZld/?taken-by=nba 

Log:

youtube-dl -v -F https://www.instagram.com/p/BRi-nkOgZld/?taken-by=nba 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.instagram.com/p/BRi-nkOgZld/?taken-by=nba']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 2.7.16 (CPython) - Darwin-20.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Instagram] BRi-nkOgZld: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/instagram.py", line 240, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1130, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by rajatvermaiam** [comment]
same issue , youtube dl should change the way of extraction.. (may be from embed html source)..
