### ISSUE TITLE
Support for crunchyroll and Funimation

### ISSUE THREAD

**Issue by TheGreatT20** [ytdl-org/youtube-dl#28893]
Can Crunchyroll and Funimation be added to the list of sites on youtube-dl. Both of these are legal anime streaming sites.

**Comment by october262** [comment]
according to this list - https://ytdl-org.github.io/youtube-dl/supportedsites.html
both funimatiion & chrunchyroll are already supported.

**Comment by meap98** [comment]
Crunchyroll is just trial and error so keep trying

**Comment by TheGreatT20** [comment]
ohh ok
