### ISSUE TITLE
Can i use youtube-dl to download youtube songs in my own Software?

### ISSUE THREAD

**Issue by Kaze961** [ytdl-org/youtube-dl#28904]
Hey,
Im writing an Media-Player with many tools. For downloading the videos from yt i use youtube-dl. In the Installation process the youtube-dl.exe gets downloaded. When the user is copying the youtube url in my software, youtube-dl gets launched and the youtube video will be downloaded. Im planning to release my program next month. Am i allowed to release this? I give credits in my readme. 
![image](https://user-images.githubusercontent.com/83350146/116405590-1dfdc900-a830-11eb-8ceb-679f1bcc2871.png)

best wishes Marcel

**Comment by pukkandan** [comment]
Yes. This project is under UNLICENCE
See https://github.com/ytdl-org/youtube-dl/blob/master/LICENSE

**Comment by rautamiekka** [comment]
In other words: absolutely nothing prevents or even limits what you can do with the code.

**Comment by Kaze961** [comment]
okay thanks :)
