### ISSUE TITLE
Regex not matching?

### ISSUE THREAD

**Issue by en1gma713** [ytdl-org/youtube-dl#28907]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

In attempting to fix the Funimation extractor, I keep getting RegexNotFoundError: "Unable to extract". I checked in an external program and the Regex matches the HTML string just fine. How do you fix this error?

**Comment by dirkf** [comment]
Plainly either the string that you think is being matched is not the string that yt-dl is trying to match, or the regex that yt-dl is using is not operating as you expect (the "external program" may not be good model).

Some ideas that may help:
* enable debugging options of yt-dl (eg `--write-pages`);
* run the program in a debugger or insert `print()` statements around the area where the extractor is failing;
* post actual examples showing the HTML fragment that the extractor should find and the pattern being used.

**Comment by en1gma713** [comment]
Thank you! Is it possible to use `--write-pages` while running a unit test?
