### ISSUE TITLE
Cannot download video from CBS.com ('No video formats found')

### ISSUE THREAD

**Issue by rgiuffre** [ytdl-org/youtube-dl#28915]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.04.26**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose https://www.cbs.com/shows/seal-team/video/q0A85GiBKv8zCn5OBJqcsgnn_YFFWndl/seal-team-forever-war/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.cbs.com/shows/seal-team/video/q0A85GiBKv8zCn5OBJqcsgnn_YFFWndl/seal-team-forever-war/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 2.7.18 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[CBS] q0A85GiBKv8zCn5OBJqcsgnn_YFFWndl: Downloading XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cbs.py", line 115, in _real_extract
    return self._extract_video_info(content_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cbs.py", line 97, in _extract_video_info
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

This video was originally "part 2" of a combined S4E01 and S4E02. The site has since separated the two-parter into 2 separate videos.  The S4E01 downloads correctly, but not the second half, now being called S4E02. Both S4E01 and S4E02 are not locked, and are freely playable in my browser.  I've tried the following link on Windows 10, Debian, and Ubuntu, and all return the same error.

https://www.cbs.com/shows/seal-team/video/q0A85GiBKv8zCn5OBJqcsgnn_YFFWndl/seal-team-forever-war/

Thank you!

**Comment by ryandesign** [comment]
> Both S4E01 and S4E02 are not locked, and are freely playable in my browser.

Nope, episode 1 is free, episode 2 is locked and shows this message when viewed in a browser: "You must connect to your TV Provider to watch this video."

**Comment by rgiuffre** [comment]
When I originally posted the "issue", the 2nd episode was playable in a browser. I watched it.  About a week later, they locked it. Unfortunately, the issue wasn't addressed in time.  I have a legit login/password to use the Adobe Pass with Comcast_SSO, but I get errors every time I try to use it. I've tried ap_mso, I've tried cookies, nothing works.  Oh well...
