### ISSUE TITLE
Issue with ESPN

### ISSUE THREAD

**Issue by Ptikrazy** [ytdl-org/youtube-dl#28919]
## Checklist

- [ X] I'm reporting a broken site support issue
- [ X] I've verified that I'm running youtube-dl version **2021.04.26**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--geo-bypass-country', u'US', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.espn.com/watch/player/_/id/62c8c9cc-c76a-422a-a73c-d4ff9083bffb', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-142-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[debug] Using fake IP 6.56.125.98 (US) as X-Forwarded-For.
[ESPN] 62: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

## Description

Hello ! It seems youtube-dl doesn't work on EPSN. This video requires a subscription (which I paid), and I added the correct login informations. I'm running it from a Debian 18.04 from France, which is why I'm using the geo-bypass option. Some people had the same issue a while back (2018), but I found no answer. Any help please ? :)

**Comment by mikewesten** [comment]
Hello I have similar issue. Without being too verbose, this is the error 

> ERROR: Unable to extract video id

**Comment by rautamiekka** [comment]
> Hello I have similar issue. Without being too verbose, this is the error
> 
> > ERROR: Unable to extract video id

Better to make your own ticket, and you must give the whole verbose log anyways, as specified in the ticket template.
