### ISSUE TITLE
Cookie Consent

### ISSUE THREAD

**Issue by kaaax0815** [ytdl-org/youtube-dl#28911]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I cant download Music from Youtube.
Parameters:
`youtube-dl https://www.youtube.com/watch?v=DArzZ3RvejU --extract-audio --audio-format mp3 --no-mtime --cookies "ytdlcookies.txt"`
Log:
```
[generic] watch?v: Requesting header
[redirect] Following redirect to https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv&gl=DE&m=0&pc=yt&uxe=23983172&hl=en&src=1
[youtube:tab] m: Downloading webpage
[download] Downloading playlist: m - Home
[youtube:tab] playlist m - Home: Downloading 0 videos
[download] Finished downloading playlist: m - Home
``` 
ytdlcookies.txt
```netscape
# Netscape HTTP Cookie File
.youtube.com	TRUE	/	FALSE	2146723199	CONSENT	YES+cb.20210427-08-p0.de+FX+800
.youtube.com	TRUE	/	TRUE	1619701468	GPS	1
.youtube.com	TRUE	/	FALSE	1682771961	PREF	tz=Europe.Berlin
.youtube.com	TRUE	/	TRUE	1635251668	VISITOR_INFO1_LIVE	MUnUAWsYStY
.youtube.com	TRUE	/	TRUE	NaN	YSC	1b6KzdUN2ug
```

Its redirecting me to a cookie consent page, because of this i try using cookies I got when accepting the consent. I dont know if I did something wrong with the Cookie File or if i missed any parameter or similar already answered issue.

**Comment by kaaax0815** [comment]
Works perfectly fine with python, but not with the windows executable

**Comment by kikuyan** [comment]
Verbose log would be helpful.

>[generic] watch?v: Requesting header

I'm not sure but the url seems to have passed as `https://www.youtube.com/watch?v` not `https://www.youtube.com/watch?v=DArzZ3RvejU`.

**Comment by kaaax0815** [comment]
I just wrapped the url in quotes to make it work. I dont know if its because i use a batch file so i dont to type arguments or whatever...
