### ISSUE TITLE
How to redirect STDOUT for bug reporting in Windows 10

### ISSUE THREAD

**Issue by rgiuffre** [ytdl-org/youtube-dl#28916]
## Checklist

- [x ] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I typically use the Windows version of youtube-dl.exe and when I want to report a bug, the normal redirect for STDOUT is to add a >filename.txt to the command line.  The errors still go to the command prompt screen instead of redirecting to the file.
Is there a way to have the --verbose output of youtube-dl go to a text file instead of the command window?

Thank you!

**Comment by dstftw** [comment]
Errors are written to stderr, you must redirect it as well.

**Comment by rgiuffre** [comment]
Other than adding the >filename.txt to the end of the command line, how else would I redirect the screen output to a text file?

**Comment by rgiuffre** [comment]
I think I got it...

youtube-dl --verbose https://www.xxx.com > error.txt 2>&1
