### ISSUE TITLE
lower quality on twitch live streams

### ISSUE THREAD

**Issue by nocoel** [ytdl-org/youtube-dl#28922]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
hello,
is it possible to download a twitch live stream with a lower quality than the best
i'm trying to get this live stream and as you can see there are multiple formats when i run -F but no codes for them

> youtube-dl -F URL
> [twitch:stream] eo58: Downloading stream GraphQL
> [twitch:stream] eo58: Downloading stream access token GraphQL
> [twitch:stream] 41633398141: Downloading m3u8 information
> [info] Available formats for 41633398141:
> format code       extension  resolution note
> audio_only        mp4        audio only    2k , mp4a.40.2
> 160p              mp4        284x160     230k , avc1.4D401F, 30.0fps, mp4a.40.2
> 360p              mp4        640x360     630k , avc1.4D401F, 30.0fps, mp4a.40.2
> 480p              mp4        852x480    1262k , avc1.4D401F, 30.0fps, mp4a.40.2
> 720p60            mp4        1280x720   3257k , avc1.4D401F, 60.0fps, mp4a.40.2
> 1080p60__source_  mp4        1920x1080  3484k , avc1.64002A, 60.0fps, mp4a.40.2(best)

i've tried many commands from the read me such as
`youtube-dl -f "best[height<=720]" URL`
`youtube-dl -f "bestvideo[height<=720]+bestaudio/best[height<=720]" URL`
`youtube-dl -f "[height <=? 720][tbr>2000]" URL`
`youtube-dl -f "[height <=? 720]" URL`

but i always end up with the source quality (1080p)

**Comment by dstftw** [comment]
Mentioned format selectors work just fine.

**Comment by nocoel** [comment]
sorry for re-opening this,
yes you are right, i just tested the same commands but changed the quality to 480p, and it does work as intended, but when i set it to 720p (1080p is the highest) it does not work, the output is 1080p
this is the example i am trying, i case you are here while he's still live: `youtube-dl -f "best[height<=720]" https://www.twitch.tv/eo58`
