### ISSUE TITLE
Selenium Webdriver functionality without additional dependencies?

### ISSUE THREAD

**Issue by en1gma713** [ytdl-org/youtube-dl#28921]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

In trying to fix an extractor I noticed that the HTML the extractor was downloading and the HTML displayed in the browser were different. Looking further into this, I discovered it was because the initial HTML downloaded is different from the HTML in the browser due to Javascript function calls and XHR. Is it possible to download the final webpage similar to Selenium's `webdriver` functionality without installing additional dependencies?

**Comment by dstftw** [comment]
No.
