### ISSUE TITLE
download youtube subtitle

### ISSUE THREAD

**Issue by salah-beep** [ytdl-org/youtube-dl#28920]
## Checklist

- [X ] I'm asking a question
- [X ] I've looked through the README and FAQ for similar questions
- [X ] I've searched the bugtracker for similar questions including closed ones

## Question

hello I want to download YouTube subtitles but i need to do it in a function, can you please clarify how i can do it without CLI is there a function? and if yes can i do it automatically to get all the available subs ! 
than kyou

**Comment by dstftw** [comment]
```
ydl = youtube_dl.YoutubeDL({
    'writesubtitles': True,
    'allsubtitles': True,
    'skip_download': True,
})
with ydl:
    r = ydl.extract_info(url)
```

**Comment by salah-beep** [comment]
thankyou @dstftw
