### ISSUE TITLE
Cannot download newer shows from itv.com/hub - Unable to download JSON metadata: HTTP Error 500

### ISSUE THREAD

**Issue by skihermit** [ytdl-org/youtube-dl#28939]
Received following error message in Any Video Converter (latest version 7.1.1) using Add URL function trying to download various shows after 28th April 2021

"Unable to download JSON metadata: HTTP Error 500: Internal Server Error: please report this issue on https://yt-dl.org/bug"

Example URL - https://www.itv.com/hub/endeavour/2a1229a0012 
(program loaded to site on Wed 28th April)
Previous episode (https://www.itv.com/hub/endeavour/2a1229a0011) added to site on Wed 21st April downloaded perfectly at that time and can still be accessed after this apparent cut-off date.

I assume this application is calling yt-dl as it's download engine (it is regularly updated) and sadly I do not have access to any code for checking.

As advised in the error message, issue reported hoping someone may be able to help - grateful thanks.

**Comment by torbs723** [comment]
https://github.com/ytdl-org/youtube-dl/issues/28906

**Comment by october262** [comment]
> Received following error message in Any Video Converter (latest version 7.1.1) using Add URL function trying to download various shows after 28th April 2021
> 
> "Unable to download JSON metadata: HTTP Error 500: Internal Server Error: please report this issue on https://yt-dl.org/bug"
> 
> Example URL - https://www.itv.com/hub/endeavour/2a1229a0012
> (program loaded to site on Wed 28th April)
> Previous episode (https://www.itv.com/hub/endeavour/2a1229a0011) added to site on Wed 21st April downloaded perfectly at that time and can still be accessed after this apparent cut-off date.
> 
> I assume this application is calling yt-dl as it's download engine (it is regularly updated) and sadly I do not have access to any code for checking.
> 
> As advised in the error message, issue reported hoping someone may be able to help - grateful thanks.

if you are logged in and can play the video, try using the addon video download helper 
and see if it'll download the video. because it did detect a mp4 video.
