### ISSUE TITLE
Newer shows on Shahid.net are not working

### ISSUE THREAD

**Issue by ramboCoder965** [ytdl-org/youtube-dl#28930]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
C:\Users\Warbringer\Desktop\Nana Manga>youtube-dl --verbose -f best -u XXX -p XXX --cookies cookies.txt https://shahid.mbc.net/en/series/Shlaywi-Nash-season-1-episode-1/episode-874743
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'best', '-u', 'PRIVATE', '-p', 'PRIVATE', '--cookies', 'cookies.txt', 'https://shahid.mbc.net/en/series/Shlaywi-Nash-season-1-episode-1/episode-874743']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2020-11-04-git-cfdddec0c8-full_build-www.gyan.dev, ffprobe 2020-11-04-git-cfdddec0c8-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] episode-874743: Requesting header
WARNING: Falling back on generic information extractor.
[generic] episode-874743: Downloading webpage
[generic] episode-874743: Extracting information
ERROR: Unsupported URL: https://shahid.mbc.net/en/series/Shlaywi-Nash-season-1-episode-1/episode-874743
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\generic.py", line 3506, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://shahid.mbc.net/en/series/Shlaywi-Nash-season-1-episode-1/episode-874743

## Description

WRITE DESCRIPTION HERE

Website was working, except for new videos (even free ones that are attempted to be downloaded without providing user/pass and/or cookies).

**Comment by mtnshadid** [comment]
I even tried mpd file directly and start saying there is no video

`youtube-dl --no-part --restrict-filenames --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0" --referer "https://shahid.mbc.net/" "https://cdxaws-ak.akamaized.net/out/v1/3cf6cf700016494ea46936c576e5afad/0a4241a1284e400793532dde98bd59e2/f89741fa8a32481e98eb32f8731adb36/manifest.mpd?aws.manifestfilter=video_height:144-1080"`

CMD Output:

C:\Users\TheShadow\Desktop\zz>youtube-dl --no-part --restrict-filenames --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0" --referer "https://shahid.mbc.net/" "https://cdxaws-ak.akamaized.net/out/v1/3cf6cf700016494ea46936c576e5afad/0a4241a1284e400793532dde98bd59e2/f89741fa8a32481e98eb32f8731adb36/manifest.mpd?aws.manifestfilter=video_height:144-1080"
[generic] manifest.mpd?aws: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest.mpd?aws: Downloading webpage
[generic] manifest.mpd?aws: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
