### ISSUE TITLE
Downloading from GET IPLAYER AUTOMATER Version 1.21.9 (20210423001)

### ISSUE THREAD

**Issue by TedPolo** [ytdl-org/youtube-dl#28934]
INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads
Downloading Show 1/1:
Downloading Coronation Street
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 200
INFO: Metadata processed.
DEBUG: youtube-dl args:["https://www.itv.com/hub/coronation-street/1a0694a10313", "-f", "mp4/best", "-o", "/Users/JamesHoskins/Desktop/BBC/Coronation Street/Coronation Street.s01e10313.30 Apr 2021.%(ext)s", "--verbose"]
DEBUG: youtube-dl environment: ["PYTHONPATH": "/Users/JamesHoskins/Desktop/Get iPlayer Automator.app/Contents/Resources", "PATH": "/Users/JamesHoskins/Desktop/Get iPlayer Automator.app/Contents/MacOS:/Users/JamesHoskins/Desktop/Get iPlayer Automator.app/Contents/Resources/get_iplayer/utils/bin:/usr/bin"]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.itv.com/hub/coronation-street/1a0694a10313', u'-f', u'mp4/best', u'-o', u'/Users/JamesHoskins/Desktop/BBC/Coronation Street/Coronation Street.s01e10313.30 Apr 2021.%(ext)s', u'--verbose']
[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
[debug] youtube-dl version 2020.12.12
[debug] Python version 2.7.16 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2-tessus
[debug] Proxy map: {}
[debug] Using fake IP 25.121.69.253 (GB) as X-Forwarded-For.
[ITV] 1a0694a10313: Downloading webpage
[ITV] 1a0694a10313: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/Users/JamesHoskins/Desktop/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Users/JamesHoskins/Desktop/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/YoutubeDL.py", line 2248, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
youtube-dl finished downloading
AppController: Downloads Finished

**Comment by kikuyan** [comment]
>[debug] youtube-dl version 2020.12.12

Too old. You must update youtube-dl to the latest version first.
Or maybe you should ask https://github.com/Ascoware/get-iplayer-automator/issues

**Comment by TedPolo** [comment]
I have updated youtube-dl to the latest version and I still get the error, which issue is the a duplicate of as I can't find it.

**Comment by gewyvoso** [comment]
the various recent issues opened about error 500 fetching the playlist JSON
