### ISSUE TITLE
Youtube download yields corrupt mkv file

### ISSUE THREAD

**Issue by keynlotepan** [ytdl-org/youtube-dl#28942]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

$ youtube-dl https://www.youtube.com/watch?v=CETIdLkJM4k -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=CETIdLkJM4k', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 2.7.17 (CPython) - Linux-5.4.0-72-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[youtube] CETIdLkJM4k: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r1---sn-hoxu-h0js.googlevideo.com/videoplayback?expire=1619959629&ei=7EqOYKCtPNaKgQfCz7nYDg&ip=2001%3Aa61%3A131a%3A501%3A95bc%3Ac02a%3Aafb0%3Af0d8&id=o-AFG7dm1rchBFyrxjAcsIgmsfZTCKAeE1SHpDlpB9tTDs&itag=398&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C394%2C395%2C396%2C397%2C398&source=youtube&requiressl=yes&mh=WT&mm=31%2C29&mn=sn-hoxu-h0js%2Csn-h0jeln7r&ms=au%2Crdu&mv=m&mvi=1&pl=40&initcwndbps=1490000&vprv=1&mime=video%2Fmp4&ns=Cg18dtOEX3qiPOnR_HAfnrYF&gir=yes&clen=275649716&dur=1843.233&lmt=1609623050736470&mt=1619937876&fvip=6&keepalive=yes&fexp=24001373%2C24007246&beids=9466586&c=WEB&txp=5531432&n=3ljLWembSpL2ENVCBbz&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgE5zI24I2ax9TVR0Rw8NkNvEjxBhk274htIQwiEHFBGACIQCoap2cm_DV9SvldQI55yRupmHs8SKJ7KvXQDufzDtsWw%3D%3D&sig=AOq0QJ8wRQIgILZmvay1Ab6wBYKwa7uh62sOheCjR9oSBN5XGsUaSKMCIQCbU6hR-IgnlF_HfT-Nkk7EeEETSq8DbkSvkkgU3JJGqA=='
[download] Destination: Leipzig 1931 in Farbe (Mit der Straßenbahn durch Leipzig, Deutschland)-CETIdLkJM4k.f398.mp4
[download] 100% of 262.88MiB in 01:21
[debug] Invoking downloader on u'https://r1---sn-hoxu-h0js.googlevideo.com/videoplayback?expire=1619959629&ei=7EqOYKCtPNaKgQfCz7nYDg&ip=2001%3Aa61%3A131a%3A501%3A95bc%3Ac02a%3Aafb0%3Af0d8&id=o-AFG7dm1rchBFyrxjAcsIgmsfZTCKAeE1SHpDlpB9tTDs&itag=251&source=youtube&requiressl=yes&mh=WT&mm=31%2C29&mn=sn-hoxu-h0js%2Csn-h0jeln7r&ms=au%2Crdu&mv=m&mvi=1&pl=40&initcwndbps=1490000&vprv=1&mime=audio%2Fwebm&ns=Cg18dtOEX3qiPOnR_HAfnrYF&gir=yes&clen=33450098&dur=1843.261&lmt=1609597565090285&mt=1619937876&fvip=6&keepalive=yes&fexp=24001373%2C24007246&beids=9466586&c=WEB&txp=5531432&n=3ljLWembSpL2ENVCBbz&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgX2Xyeg6bOy_hapeTt2HgK3TVkkXf84cBXTNMBOE6h-wCIE9eYWVq4NwG6Wp2dpJwy3GhuP7CPASxpogElCrRHiVY&sig=AOq0QJ8wRQIhAPNCh4aIMc1Vpa85bzrkq7X5aAn5ZN3dOQWRetD_DePQAiAoWdYeqyzLmgaQHM5Q2owR4KlNOiboJxD3bM6wKoknXw=='
[download] Destination: Leipzig 1931 in Farbe (Mit der Straßenbahn durch Leipzig, Deutschland)-CETIdLkJM4k.f251.webm
[download] 100% of 31.90MiB in 00:09
[ffmpeg] Merging formats into "Leipzig 1931 in Farbe (Mit der Straßenbahn durch Leipzig, Deutschland)-CETIdLkJM4k.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Leipzig 1931 in Farbe (Mit der Straßenbahn durch Leipzig, Deutschland)-CETIdLkJM4k.f398.mp4' -i 'file:Leipzig 1931 in Farbe (Mit der Straßenbahn durch Leipzig, Deutschland)-CETIdLkJM4k.f251.webm' -c copy -map '0:v:0' -map '1:a:0' 'file:Leipzig 1931 in Farbe (Mit der Straßenbahn durch Leipzig, Deutschland)-CETIdLkJM4k.temp.mkv'
Deleting original file Leipzig 1931 in Farbe (Mit der Straßenbahn durch Leipzig, Deutschland)-CETIdLkJM4k.f398.mp4 (pass -k to keep)
Deleting original file Leipzig 1931 in Farbe (Mit der Straßenbahn durch Leipzig, Deutschland)-CETIdLkJM4k.f251.webm (pass -k to keep)

## Description

The generated file "Leipzig 1931 in Farbe (Mit der Straßenbahn durch Leipzig, Deutschland)-CETIdLkJM4k.mkv" seems to be corrupt, playback is not possible on my Linux system (Mint's standard video player Celluloid crashes, VLC reports: "Codec not supported: VLC could not decode the format "av01" (AOMedia's AV1 Video)"

**Comment by kikuyan** [comment]
No problem with VLC 3.0.12 and mpv 0.33.1. I'm not using Linux, though.

**Comment by keynlotepan** [comment]
VLC on my Linux system is the latest available in my distribution (3.0.8). But I think it is not a player issue since it occurs on the default player of the system (which is up to date), too and it is the only video captured with youtube-dl (and the only video on my system at all) which shows this behavour. 

MD5 of my video is: b3a9432c6f6f0b6a9eaa9cf0be48d4ed (same as yours?)

mediainfo reports:
General
Count                                    : 329
Count of stream of this kind             : 1
Kind of stream                           : General
Kind of stream                           : General
Stream identifier                        : 0
Unique ID                                : 181686253295149234846756194091533692817
Unique ID                                : 181686253295149234846756194091533692817 (0x88AF7FE3D99A1640E63CBF3106D56F91)
Count of video streams                   : 1
Count of audio streams                   : 1
Video_Format_List                        : V_AV1
Video_Format_WithHint_List               : V_AV1
Codecs Video                             : V_AV1
Audio_Format_List                        : Opus
Audio_Format_WithHint_List               : Opus
Audio codecs                             : Opus
Audio_Language_List                      : English
Complete name                            : Leipzig 1931 in Farbe (Mit der Straßenbahn durch Leipzig, Deutschland)-CETIdLkJM4k.mkv
File name                                : Leipzig 1931 in Farbe (Mit der Straßenbahn durch Leipzig, Deutschland)-CETIdLkJM4k
File extension                           : mkv
Format                                   : Matroska
Format                                   : Matroska
Format/Url                               : https://matroska.org/downloads/windows.html
Format/Extensions usually used           : mkv mk3d mka mks
Commercial name                          : Matroska
Format version                           : Version 4 / Version 2
Codec                                    : Matroska
Codec                                    : Matroska
Codec/Url                                : https://matroska.org/downloads/windows.html
Codec/Extensions usually used            : mkv mk3d mka mks
File size                                : 308986536
File size                                : 295 MiB
File size                                : 295 MiB
File size                                : 295 MiB
File size                                : 295 MiB
File size                                : 294.7 MiB
Duration                                 : 1843261
Duration                                 : 30 min 43 s
Duration                                 : 30 min 43 s 261 ms
Duration                                 : 30 min 43 s
Duration                                 : 00:30:43.261
Duration                                 : 00:30:43:07
Duration                                 : 00:30:43.261 (00:30:43:07)
Overall bit rate                         : 1341043
Overall bit rate                         : 1 341 kb/s
Frame rate                               : 30.000
Frame rate                               : 30.000 FPS
Frame count                              : 55297
IsStreamable                             : Yes
File last modification date              : UTC 2021-01-02 14:26:05
File last modification date (local)      : 2021-01-02 15:26:05
Writing application                      : Lavf57.83.100
Writing application                      : Lavf57.83.100
Writing library                          : Lavf57.83.100
Writing library                          : Lavf57.83.100
ErrorDetectionType                       : Per level 1

Video
Count                                    : 342
Count of stream of this kind             : 1
Kind of stream                           : Video
Kind of stream                           : Video
Stream identifier                        : 0
StreamOrder                              : 0
ID                                       : 1
ID                                       : 1
Unique ID                                : 1
Format                                   : V_AV1
Commercial name                          : V_AV1
Codec ID                                 : V_AV1
Codec                                    : V_AV1
Codec                                    : V_AV1
Duration                                 : 1843233.000000
Duration                                 : 30 min 43 s
Duration                                 : 30 min 43 s 233 ms
Duration                                 : 30 min 43 s
Duration                                 : 00:30:43.233
Duration                                 : 00:30:43:07
Duration                                 : 00:30:43.233 (00:30:43:07)
Width                                    : 1280
Width                                    : 1 280 pixels
Height                                   : 720
Height                                   : 720 pixels
Pixel aspect ratio                       : 1.000
Display aspect ratio                     : 1.778
Display aspect ratio                     : 16:9
Frame rate mode                          : CFR
Frame rate mode                          : Constant
Frame rate                               : 30.000
Frame rate                               : 30.000 FPS
Frame count                              : 55297
Color space                              : YUV
Title                                    : ISO Media file produced by Google Inc.
Default                                  : Yes
Default                                  : Yes
Forced                                   : No
Forced                                   : No
Color range                              : Limited
colour_description_present               : Yes
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
Count                                    : 275
Count of stream of this kind             : 1
Kind of stream                           : Audio
Kind of stream                           : Audio
Stream identifier                        : 0
StreamOrder                              : 1
ID                                       : 2
ID                                       : 2
Unique ID                                : 2
Format                                   : Opus
Format/Url                               : http://opus-codec.org/
Commercial name                          : Opus
Internet media type                      : audio/opus
Codec ID                                 : A_OPUS
Codec ID/Url                             : http://opus-codec.org
Codec                                    : Opus
Codec                                    : Opus
Codec/Family                             : PCM
Duration                                 : 1843261.000000
Duration                                 : 30 min 43 s
Duration                                 : 30 min 43 s 261 ms
Duration                                 : 30 min 43 s
Duration                                 : 00:30:43.261
Duration                                 : 00:30:43.261
Channel(s)                               : 2
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Channel positions                        : 2/0/0
Sampling rate                            : 48000
Sampling rate                            : 48.0 kHz
Samples count                            : 88476528
Resolution                               : 32
Resolution                               : 32 bits
Bit depth                                : 32
Bit depth                                : 32 bits
Compression mode                         : Lossy
Compression mode                         : Lossy
Delay                                    : 0
Delay                                    : 00:00:00.000
Delay, origin                            : Container
Delay, origin                            : Container
Language                                 : en
Language                                 : English
Language                                 : English
Language                                 : en
Language                                 : eng
Language                                 : en
Default                                  : Yes
Default                                  : Yes
Forced                                   : No
Forced                                   : No

**Comment by kikuyan** [comment]
I've found many pages for 'VLC could not decode the format "av01" (AOMedia's AV1 Video)'. Among them, this comment might help you.
https://forums.linuxmint.com/viewtopic.php?p=1818818#p1818818

**Comment by keynlotepan** [comment]
So it looks like both of my players are not capable playing the video codec AV1. Thanks for your hints.
