### ISSUE TITLE
Getting error of "unsupported 16 bit application"

### ISSUE THREAD

**Issue by archz2** [ytdl-org/youtube-dl#28954]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I am unable to use Youtube dl. I have been using this software for probably more than a year without any issue. Today when I tried to download a youtube video, I got this error. 

![image](https://user-images.githubusercontent.com/66735186/116889602-60694080-ac4a-11eb-8e59-ac1aefa9c451.png)

After pressing "OK" I get this notification saying " This version of youtube-dl.EXE is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher."

![image](https://user-images.githubusercontent.com/66735186/116889634-695a1200-ac4a-11eb-92a3-7c0996b15e4e.png)

I also downloaded the v2021.04.26 but still I am getting the same issue. 

I am running windows 10 - 64 bit version 20H2 (OS Build 19042.928)

Please help me in resolving this issue.

**Comment by dstftw** [comment]
Post the output of `certUtil -hashfile "youtube-dl.exe" SHA256`.

**Comment by archz2** [comment]
SHA256 hash of youtube-dl.exe:
0034c72da0d9fde46d03fa2c91a0a3182970f473e7687379e1b4ed7a47620e35
CertUtil: -hashfile command completed successfully.

**Comment by dstftw** [comment]
The hash is invalid. It's not a `youtube-dl.exe` version 2021.04.26 executable.

**Comment by archz2** [comment]
Thanks. I redownloaded the exe and everything is working fine now. 👍🏼
