### ISSUE TITLE
How to format a multi-line config?

### ISSUE THREAD

**Issue by pvonmoradi** [ytdl-org/youtube-dl#28958]
## Checklist
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones
## Question
What is the format of the config file? I'm using the following config:
```
--format bestvideo[vcodec!*=av01]+bestaudio\
/best[vcodec!*=av01]\
/best
--add-metadata
```
I'm not sure about how to format the `--format` option. Should the whole thing be quoted? Should there be `\` at the end of each line?

**Comment by dstftw** [comment]
Either way works.
