### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError());

### ISSUE THREAD

**Issue by HorselessName** [ytdl-org/youtube-dl#28966]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
C:\Users\Raulp\Downloads\Download SRT>youtube-dl --skip-download --write-sub --sub-lang ptBR --sub-format "ass" "https://www.crunchyroll.com/pt-br/food-wars-shokugeki-no-soma/episode-3-the-generation-of-prodigies-715213"
[crunchyroll] 715213: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I am trying to download a subtitle from a episode but i cant.
Please help. Thank you

**Comment by D0LLYNH0** [comment]
- **Exporte os cookies da sua sessão Crunchyroll, é necessário!**
Para isso, use uma extensão apropriada. Recomendo o: [Get cookies.txt](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid)

- **Adicione na sua linha de comando**
`--cookies cookies.txt`

**Obs:** Caso tente utilizar os cookies numa máquina com IP diferente, irá falhar, continuará retornando 403!
