### ISSUE TITLE
ARDMediathek HTTP Error 412: Precondition Failed for some videos

### ISSUE THREAD

**Issue by dadosch** [ytdl-org/youtube-dl#28960]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', 'https://ardmediathek.de/video/feuer-und-flamme/feuer-und-flamme-s01-e01/wdr-fernsehen/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTM1Y2IwM2VkLTNkOTgtNDBkZC1iZjIxLTU1ZjFjODE4MmFlNw/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.9.4 (CPython) - Linux-5.12.0-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 53.50.219.112 (DE) as X-Forwarded-For.
[ARDBetaMediathek] Y3JpZDovL3dkci5kZS9CZWl0cmFnLTM1Y2IwM2VkLTNkOTgtNDBkZC1iZjIxLTU1ZjFjODE4MmFlNw: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 412: Precondition Failed (caused by <HTTPError 412: 'Precondition Failed'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description

Youtube-dl fails for some videos of the ARDMediathek. An example video is https://ardmediathek.de/video/feuer-und-flamme/feuer-und-flamme-s01-e01/wdr-fernsehen/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTM1Y2IwM2VkLTNkOTgtNDBkZC1iZjIxLTU1ZjFjODE4MmFlNw/

**Comment by malteger** [comment]
I get the same error using a virtual server (Ubuntu with youtube_dl 2021.04.26), but it works locally on my computer (Arch with same youtube_dl version). Might be related to the IP or something like that.

**Comment by dadosch** [comment]
Ah! If you force ipv4 with --force-ipv4 it works, if you force ipv6 it doesn't; so IPv6 is broken at ARD's side.

**Comment by malteger** [comment]
> Ah! If you force ipv4 with --force-ipv4 it works, if you force ipv6 it doesn't; so IPv6 is broken at ARD's side.

I just tested it and it does not work in my case

**Comment by malteger** [comment]
I tried some more computers and videos, sometimes it works on all computers, sometimes not. I have managed to trigger the error from my home internet connection by setting `--geo-bypass-ip-block 53.50.219.112/32`, after that it also appeared without this setting, but not always.

The server has IPv6 and it works with https://www.ardmediathek.de/video/feuer-und-flamme/schwerer-verkehrsunfall-oder-mit-gifttieren-ueben-fuer-den-ernstfall-s04-e02/wdr-fernsehen/Y3JpZDovL3dkci5kZS9CZWl0cmFnLWViOTVkN2ExLTY4ODctNDIwMy1iYjMwLTY1MDU1NTljYmYyZg/ but not https://www.ardmediathek.de/video/feuer-u
nd-flamme/grossfeuer-in-bochum-s04-e01/wdr-fernsehen/Y3JpZDovL3dkci5kZS9CZWl0cmFnLWU0MTE5MDZiLTcxOWUtNDk1ZS04M
jVkLTM4NGI1ZDMyNWFjMQ/ even without `--force-ipv4`

**Comment by dadosch** [comment]
> I have managed to trigger the error from my home internet connection by setting `--geo-bypass-ip-block 53.50.219.112/32`,

Not the case here, it worked even with that setting, while before it hadn't. Even from the same source IPv4 it works only sporadically. I suppose it is some kind of traffic handling/ "abuse" handling at ARD's.

**Comment by lemmerk** [comment]
i am experiencing the same issues. i've tried both suggestions mentioned above individually:
--force-ipv4
--geo-bypass-ip-block 53.50.219.112/32

and neither of the options helped in my case. i've also tried a selection of IP addresses using VPN in addition to my regular one without any improvement. also, i was able to download a couple of videos from a batch but this did not make downloading the blocked ones available for download.

**Comment by wieland-s** [comment]
Same problem on macOS Big Sur Version 11.3: some videos work, some not. No difference while choosing the options `--force-ipv4` or `--geo-bypass-ip-block`. 
It feels like the most videos work, only some selected not. But I haven't prove it exactly. 

Example not working Video: https://wdrmedien-a.akamaihd.net/medp/ondemand/de/fsk12/242/2421090/2421090_34501594.mp4 

@dstftw Maybe reopen? Same here: https://github.com/ytdl-org/youtube-dl/issues/28965

**Comment by yawkat** [comment]
This issue is caused by the `player_page` graphql query ( https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/ard.py#L379 ). Removing the `tracking` block from the query appears to fix the issue in my local testing:

```diff
===================================================================
diff --git a/youtube_dl/extractor/ard.py b/youtube_dl/extractor/ard.py
--- a/youtube_dl/extractor/ard.py	(revision a0df8a06178e530a1097f177a1faf1d2c609ac99)
+++ b/youtube_dl/extractor/ard.py	(date 1620143870131)
@@ -404,11 +404,6 @@
     }
     synopsis
     title
-    tracking {
-      atiCustomVars {
-        contentId
-      }
-    }
   }
 }''' % video_id,
             }).encode(), headers={
```

I don't know if this fix works for all videos that have this issue, or why it works, so I am not going to PR this.

**Comment by 5nafu** [comment]
@dstftw , please reopen this issue as it appears to be affecting multiple users (including myself on https://www.ardmediathek.de/video/feuer-und-flamme/schwerer-verkehrsunfall-oder-mit-gifttieren-ueben-fuer-den-ernstfall-s04-e02/wdr-fernsehen/Y3JpZDovL3dkci5kZS9CZWl0cmFnLWViOTVkN2ExLTY4ODctNDIwMy1iYjMwLTY1MDU1NTljYmYyZg/)

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.ardmediathek.de/video/feuer-und-flamme/schwerer-verkehrsunfall-oder-mit-gifttieren-ueben-fuer-den-ernstfall-s04-e02/wdr-fernsehen/Y3JpZDovL3dkci5kZS9CZWl0cmFnLWViOTVkN2ExLTY4ODctNDIwMy1iYjMwLTY1MDU1NTljYmYyZg/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.7.5 (CPython) - Linux-5.3.0-64-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2
[debug] Proxy map: {}
[debug] Using fake IP 53.23.236.143 (DE) as X-Forwarded-For.
[ARDBetaMediathek] Y3JpZDovL3dkci5kZS9CZWl0cmFnLWViOTVkN2ExLTY4ODctNDIwMy1iYjMwLTY1MDU1NTljYmYyZg: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 412: Precondition Failed (caused by <HTTPError 412: 'Precondition Failed'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/tobias/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/tobias/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

And I can confirm that @yawkat fix solves the issue for the above video.

**Comment by mfroeb** [comment]
I can confirm that @yawkat 's fix works also for https://www.ardmediathek.de/video/Y3JpZDovL2Rhc2Vyc3RlLmRlL3RhdG9ydC8wNTQxYTQwZS1iNzcxLTRhYmYtYWUzYi02MDRhOTdlMDkzOTk/ , which failed before. Please reopen @dstftw , thanks!

**Comment by SamusAranX** [comment]
FWIW, here's another confirmation from me that the above fix works.

And stop fucking closing issues you can't reproduce after less than 24 hours.

**Comment by Axel-Erfurt** [comment]
@yawkat fix solves the issue for all ARD Mediathek, thanks.

**Comment by calestyo** [comment]
It's pretty unlikely that this is a problem with the ISP, cause in every case where youtube-dl fails playback via browser works just fine.

**Comment by calestyo** [comment]
Oh an btw: @yawkat's  [workaround from above](https://github.com/ytdl-org/youtube-dl/issues/28960#issuecomment-832055878) seems to have the side effect, that videos are downloaded with a new ID/filename,...
e.g.
`https://www.ardmediathek.de/video/erlebnis-erde/sambia-koenigreich-der-leopardin/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2VybGVibmlzIGVyZGUvMTc0MmFiNDUtOGYzMi00ZGNlLTk5YWQtZWZiMTQ1NzllNTlm/`
without the workaround becomes:
`Sambia - Königreich der Leopardin-89095074.mp4`
but with it:
`Sambia - Königreich der Leopardin-Y3JpZDovL2Rhc2Vyc3RlLmRlL2VybGVibmlzIGVyZGUvMTc0MmFiNDUtOGYzMi00ZGNlLTk5YWQtZWZiMTQ1NzllNTlm.mp4`
