### ISSUE TITLE
Approve youtube dl so that Facebook doesn't detect it as suspicious

### ISSUE THREAD

**Issue by archz2** [ytdl-org/youtube-dl#28968]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Whenever I use youtubedl to download private facebook videos, the videos get downloaded fine. However, Facebook detects it as unusual activity and asks me to verify my account and change the password. Is there anyway to mark youtubedl as safe within Facebook so that it doesn't detect it as "suspicious activity"?

**Comment by october262** [comment]
did you happen to use a cookies.txt file to download the video ??

**Comment by archz2** [comment]
No I used the following command in the cmd prompt to download the video. 

youtube-dl.exe https://www.facebook.com/theremainingportionofthevideolink/ --username myusername --password mypassword

**Comment by dstftw** [comment]
Use authenticated cookies instead of credentials.

**Comment by archz2** [comment]
> Use authenticated cookies instead of credentials.

Please provide a step-by-step method to do this.

**Comment by napgiver** [comment]
You can use a browser extension to export your cookies to a "cookies.txt" file.

Chrome: chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid?hl=en
Firefox: addons.mozilla.org/en-US/firefox/addon/cookies-txt/

Save the "cookies.txt" file in the same folder as youtube-dl.

Replace "--username myusername --password mypassword" with "--cookies cookies.txt", in your Batch (.bat) file.

**Comment by archz2** [comment]
Thanks! I'll try this and get back to you. 👍🏼
