### ISSUE TITLE
Select video to download from a videolectures.net playlist

### ISSUE THREAD

**Issue by soumdtt** [ytdl-org/youtube-dl#28976]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by soumdtt** [comment]
I am trying to download videos from this playlist [http://videolectures.net/mlss03_bousquet_slt/](url). However, when I check the available formats through youtube-dl -v -F "http://videolectures.net/mlss03_bousquet_slt/", I am not able to select a particular file since many files have duplicate http streams. Below is the log:

[info] Available formats for 704_part1:
format code  extension  resolution note
rtmp-374     flv        384x288     374k , 124.72MiB
http-374     flv        384x288     374k , 124.72MiB
http-1321    wmv        320x240    1321k , 440.28MiB (best)
[download] Downloading video 2 of 7
[info] Available formats for 704_part2:
format code  extension  resolution note
rtmp-374     flv        384x288     374k , 125.02MiB
http-374     flv        384x288     374k , 125.02MiB
http-1321    wmv        320x240    1321k , 441.16MiB (best)
[download] Downloading video 3 of 7
[info] Available formats for 704_part3:
format code  extension  resolution note
rtmp-371     flv        384x288     371k , 125.34MiB
http-371     flv        384x288     371k , 125.34MiB
http-1321    wmv        320x240    1321k , 445.61MiB (best)
[download] Downloading video 4 of 7
[info] Available formats for 704_part4:
format code  extension  resolution note
rtmp-372     flv        384x288     372k , 129.44MiB
http-372     flv        384x288     372k , 129.44MiB
http-1321    wmv        320x240    1321k , 459.06MiB (best)
[download] Downloading video 5 of 7
[info] Available formats for 704_part5:
format code  extension  resolution note
rtmp-374     flv        384x288     374k , 136.48MiB
http-374     flv        384x288     374k , 136.48MiB
http-1321    wmv        320x240    1321k , 481.25MiB (best)
[download] Downloading video 6 of 7
[info] Available formats for 704_part6:
format code  extension  resolution note
rtmp-379     flv        384x288     379k , 123.41MiB
http-379     flv        384x288     379k , 123.41MiB
http-1321    wmv        320x240    1321k , 429.15MiB (best)
[download] Downloading video 7 of 7
[info] Available formats for 704_part7:
format code  extension  resolution note
rtmp-374     flv        384x288     374k , 108.37MiB
http-374     flv        384x288     374k , 108.37MiB
http-1321    wmv        320x240    1321k , 382.54MiB (best)
[download] Finished downloading playlist: Statistical Learning Theory

As you can see that different parts are mapped to the same http stream, How do I select the different parts for download ?

**Comment by dstftw** [comment]
```
--playlist-start NUMBER              Playlist video to start at (default is
                                     1)
--playlist-end NUMBER                Playlist video to end at (default is
                                     last)
--playlist-items ITEM_SPEC           Playlist video items to download.
                                     Specify indices of the videos in the
                                     playlist separated by commas like: "--
                                     playlist-items 1,2,5,8" if you want to
                                     download videos indexed 1, 2, 5, 8 in
                                     the playlist. You can specify range: "
                                     --playlist-items 1-3,7,10-13", it will
                                     download the videos at index 1, 2, 3,
                                     7, 10, 11, 12 and 13.
```
