### ISSUE TITLE
About downloading high quality videos

### ISSUE THREAD

**Issue by Ryuyxx** [ytdl-org/youtube-dl#28978]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

If I choose `best` as the download format, I get a low-quality video.  
Does this happen because it makes a single file?
If I want to get high quality and audio, does that mean I need to DL `bestvideo` and `bestaudio` twice and fuse them together?

**Comment by dstftw** [comment]
This depends. Read FAQ on format selection.
