### ISSUE TITLE
--get-duration does not work for liveleak

### ISSUE THREAD

**Issue by mjwurth** [ytdl-org/youtube-dl#28973]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v  --get-duration https://www.liveleak.com/view?t=l7b9_1620048190
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--get-duration', 'https://www.liveleak.com/view?t=l7b9_1620048190']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-100592-g42ee3898c8, ffprobe N-100592-g42ee3898c8
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
```

## Description

The --get-duration option has no output for liveleak videos.
The command I used was:
youtube-dl --get-duration https://www.liveleak.com/view?t=l7b9_1620048190

The output should be 45.

**Comment by dstftw** [comment]
No such metadata is available.
