### ISSUE TITLE
Youtube-dl fails randomly to download Youtube channels with JSON metadata  Remote end closed connection without response error

### ISSUE THREAD

**Issue by alosslessdev** [ytdl-org/youtube-dl#28984]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
F:\Users\<username>>youtube-dl "https://www.youtube.com/user/RTHK/videos?view=0&sort=da&flow=grid" --datebefore 20140107 --ignore-errors --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/user/RTHK/videos?view=0&sort=da&flow=grid', '--datebefore', '20140107', '--ignore-errors', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.9.2 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2020-11-18-git-e3081d6f4f-full_build-www.gyan.dev, ffprobe 2020-11-18-git-e3081d6f4f-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube:tab] RTHK: Downloading webpage
[download] Downloading playlist: RTHK 香港電台 - Videos
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] Downloading page 3
[youtube:tab] Downloading page 4
[youtube:tab] Downloading page 5
[youtube:tab] Downloading page 6
[youtube:tab] Downloading page 7
[youtube:tab] Downloading page 8
[youtube:tab] Downloading page 9
[youtube:tab] Downloading page 10
[youtube:tab] Downloading page 11
[youtube:tab] Downloading page 12
[youtube:tab] Downloading page 13
[youtube:tab] Downloading page 14
[youtube:tab] Downloading page 15
[youtube:tab] Downloading page 16
[youtube:tab] Downloading page 17
[youtube:tab] Downloading page 18
[youtube:tab] Downloading page 19
[youtube:tab] Downloading page 20
[youtube:tab] Downloading page 21
[youtube:tab] Downloading page 22
[youtube:tab] Downloading page 23
[youtube:tab] Downloading page 24
[youtube:tab] Downloading page 25
[youtube:tab] Downloading page 26
[youtube:tab] Downloading page 27
[youtube:tab] Downloading page 28
[youtube:tab] Downloading page 29
[youtube:tab] Downloading page 30
[youtube:tab] Downloading page 31
[youtube:tab] Downloading page 32
[youtube:tab] Downloading page 33
[youtube:tab] Downloading page 34
[youtube:tab] Downloading page 35
[youtube:tab] Downloading page 36
[youtube:tab] Downloading page 37
[youtube:tab] Downloading page 38
[youtube:tab] Downloading page 39
[youtube:tab] Downloading page 40
[youtube:tab] Downloading page 41
[youtube:tab] Downloading page 42
[youtube:tab] Downloading page 43
[youtube:tab] Downloading page 44
[youtube:tab] Downloading page 45
[youtube:tab] Downloading page 46
[youtube:tab] Downloading page 47
[youtube:tab] Downloading page 48
[youtube:tab] Downloading page 49
[youtube:tab] Downloading page 50
[youtube:tab] Downloading page 51
[youtube:tab] Downloading page 52
[youtube:tab] Downloading page 53
[youtube:tab] Downloading page 54
[youtube:tab] Downloading page 55
[youtube:tab] Downloading page 56
[youtube:tab] Downloading page 57
[youtube:tab] Downloading page 58
[youtube:tab] Downloading page 59
[youtube:tab] Downloading page 60
[youtube:tab] Downloading page 61
[youtube:tab] Downloading page 62
[youtube:tab] Downloading page 63
[youtube:tab] Downloading page 64
[youtube:tab] Downloading page 65
[youtube:tab] Downloading page 66
[youtube:tab] Downloading page 67
[youtube:tab] Downloading page 68
[youtube:tab] Downloading page 69
[youtube:tab] Downloading page 70
[youtube:tab] Downloading page 71
[youtube:tab] Downloading page 72
[youtube:tab] Downloading page 73
[youtube:tab] Downloading page 74
[youtube:tab] Downloading page 75
[youtube:tab] Downloading page 76
[youtube:tab] Downloading page 77
[youtube:tab] Downloading page 78
[youtube:tab] Downloading page 79
[youtube:tab] Downloading page 80
[youtube:tab] Downloading page 81
[youtube:tab] Downloading page 82
[youtube:tab] Downloading page 83
[youtube:tab] Downloading page 84
[youtube:tab] Downloading page 85
[youtube:tab] Downloading page 86
[youtube:tab] Downloading page 87
[youtube:tab] Downloading page 88
[youtube:tab] Downloading page 89
[youtube:tab] Downloading page 90
[youtube:tab] Downloading page 91
[youtube:tab] Downloading page 92
[youtube:tab] Downloading page 93
[youtube:tab] Downloading page 94
[youtube:tab] Downloading page 95
[youtube:tab] Downloading page 96
[youtube:tab] Downloading page 97
[youtube:tab] Downloading page 98
[youtube:tab] Downloading page 99
[youtube:tab] Downloading page 100
[youtube:tab] Downloading page 101
[youtube:tab] Downloading page 102
[youtube:tab] Downloading page 103
[youtube:tab] Downloading page 104
[youtube:tab] Downloading page 105
[youtube:tab] Downloading page 106
[youtube:tab] Downloading page 107
[youtube:tab] Downloading page 108
[youtube:tab] Downloading page 109
[youtube:tab] Downloading page 110
[youtube:tab] Downloading page 111
[youtube:tab] Downloading page 112
[youtube:tab] Downloading page 113
[youtube:tab] Downloading page 114
[youtube:tab] Downloading page 115
[youtube:tab] Downloading page 116
[youtube:tab] Downloading page 117
[youtube:tab] Downloading page 118
[youtube:tab] Downloading page 119
[youtube:tab] Downloading page 120
[youtube:tab] Downloading page 121
[youtube:tab] Downloading page 122
[youtube:tab] Downloading page 123
[youtube:tab] Downloading page 124
[youtube:tab] Downloading page 125
[youtube:tab] Downloading page 126
[youtube:tab] Downloading page 127
[youtube:tab] Downloading page 128
[youtube:tab] Downloading page 129
[youtube:tab] Downloading page 130
[youtube:tab] Downloading page 131
[youtube:tab] Downloading page 132
[youtube:tab] Downloading page 133
[youtube:tab] Downloading page 134
[youtube:tab] Downloading page 135
[youtube:tab] Downloading page 136
[youtube:tab] Downloading page 137
[youtube:tab] Downloading page 138
[youtube:tab] Downloading page 139
[youtube:tab] Downloading page 140
[youtube:tab] Downloading page 141
[youtube:tab] Downloading page 142
[youtube:tab] Downloading page 143
[youtube:tab] Downloading page 144
[youtube:tab] Downloading page 145
[youtube:tab] Downloading page 146
[youtube:tab] Downloading page 147
[youtube:tab] Downloading page 148
[youtube:tab] Downloading page 149
[youtube:tab] Downloading page 150
[youtube:tab] Downloading page 151
[youtube:tab] Downloading page 152
[youtube:tab] Downloading page 153
[youtube:tab] Downloading page 154
[youtube:tab] Downloading page 155
[youtube:tab] Downloading page 156
[youtube:tab] Downloading page 157
[youtube:tab] Downloading page 158
[youtube:tab] Downloading page 159
[youtube:tab] Downloading page 160
[youtube:tab] Downloading page 161
[youtube:tab] Downloading page 162
[youtube:tab] Downloading page 163
[youtube:tab] Downloading page 164
ERROR: Unable to download JSON metadata: Remote end closed connection without response (caused by RemoteDisconnected('Remote end closed connection without response')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\<username>\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\<username>\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\program files\python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "c:\program files\python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "c:\program files\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\<username>\AppData\Roaming\Python\Python39\site-packages\youtube_dl\utils.py", line 2735, in https_open
    return self.do_open(functools.partial(
  File "c:\program files\python39\lib\urllib\request.py", line 1350, in do_open
    r = h.getresponse()
  File "c:\program files\python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "c:\program files\python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "c:\program files\python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
```

## Description

Youtube-dl randomly fails with this error, even after rebooting Windows. (Maybe because i don't have ECC RAM?) Sometimes it will run for hours without errors, while other times it will stop somewhere before "downloading page" reaches 400. I don't remember if it fails in between. I'm downloading from RTHK's Youtube channel, which is actively deleting content (https://hongkongfp.com/2021/05/03/hong-kong-broadcaster-rthk-to-delete-shows-over-a-year-old-from-internet-as-viewers-scramble-to-save-backups/) so i set the --ignore-errors flag to ignore videos that are suddenly deleted. 

Edit: here's another example:
Microsoft Windows [Versión 10.0.19041.928]
(c) Microsoft Corporation. Todos los derechos reservados.

F:\Users\<username>>youtube-dl "https://www.youtube.com/user/RTHK/videos?view=0&sort=da&flow=grid" --datebefore 20140107 --ignore-errors --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/user/RTHK/videos?view=0&sort=da&flow=grid', '--datebefore', '20140107', '--ignore-errors', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.9.2 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2020-11-18-git-e3081d6f4f-full_build-www.gyan.dev, ffprobe 2020-11-18-git-e3081d6f4f-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube:tab] RTHK: Downloading webpage
[download] Downloading playlist: RTHK 香港電台 - Videos
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] Downloading page 3
[youtube:tab] Downloading page 4
[youtube:tab] Downloading page 5
[youtube:tab] Downloading page 6
[youtube:tab] Downloading page 7
[youtube:tab] Downloading page 8
[youtube:tab] Downloading page 9
[youtube:tab] Downloading page 10
[youtube:tab] Downloading page 11
[youtube:tab] Downloading page 12
[youtube:tab] Downloading page 13
[youtube:tab] Downloading page 14
[youtube:tab] Downloading page 15
[youtube:tab] Downloading page 16
[youtube:tab] Downloading page 17
[youtube:tab] Downloading page 18
[youtube:tab] Downloading page 19
[youtube:tab] Downloading page 20
[youtube:tab] Downloading page 21
[youtube:tab] Downloading page 22
[youtube:tab] Downloading page 23
[youtube:tab] Downloading page 24
[youtube:tab] Downloading page 25
[youtube:tab] Downloading page 26
[youtube:tab] Downloading page 27
[youtube:tab] Downloading page 28
[youtube:tab] Downloading page 29
[youtube:tab] Downloading page 30
[youtube:tab] Downloading page 31
[youtube:tab] Downloading page 32
[youtube:tab] Downloading page 33
[youtube:tab] Downloading page 34
[youtube:tab] Downloading page 35
[youtube:tab] Downloading page 36
[youtube:tab] Downloading page 37
[youtube:tab] Downloading page 38
[youtube:tab] Downloading page 39
[youtube:tab] Downloading page 40
[youtube:tab] Downloading page 41
[youtube:tab] Downloading page 42
[youtube:tab] Downloading page 43
[youtube:tab] Downloading page 44
[youtube:tab] Downloading page 45
[youtube:tab] Downloading page 46
[youtube:tab] Downloading page 47
[youtube:tab] Downloading page 48
[youtube:tab] Downloading page 49
[youtube:tab] Downloading page 50
[youtube:tab] Downloading page 51
[youtube:tab] Downloading page 52
[youtube:tab] Downloading page 53
[youtube:tab] Downloading page 54
[youtube:tab] Downloading page 55
[youtube:tab] Downloading page 56
[youtube:tab] Downloading page 57
[youtube:tab] Downloading page 58
[youtube:tab] Downloading page 59
[youtube:tab] Downloading page 60
[youtube:tab] Downloading page 61
[youtube:tab] Downloading page 62
[youtube:tab] Downloading page 63
[youtube:tab] Downloading page 64
[youtube:tab] Downloading page 65
[youtube:tab] Downloading page 66
[youtube:tab] Downloading page 67
[youtube:tab] Downloading page 68
[youtube:tab] Downloading page 69
[youtube:tab] Downloading page 70
[youtube:tab] Downloading page 71
[youtube:tab] Downloading page 72
[youtube:tab] Downloading page 73
[youtube:tab] Downloading page 74
[youtube:tab] Downloading page 75
[youtube:tab] Downloading page 76
[youtube:tab] Downloading page 77
[youtube:tab] Downloading page 78
[youtube:tab] Downloading page 79
[youtube:tab] Downloading page 80
[youtube:tab] Downloading page 81
[youtube:tab] Downloading page 82
[youtube:tab] Downloading page 83
[youtube:tab] Downloading page 84
[youtube:tab] Downloading page 85
[youtube:tab] Downloading page 86
[youtube:tab] Downloading page 87
[youtube:tab] Downloading page 88
[youtube:tab] Downloading page 89
[youtube:tab] Downloading page 90
[youtube:tab] Downloading page 91
[youtube:tab] Downloading page 92
[youtube:tab] Downloading page 93
[youtube:tab] Downloading page 94
[youtube:tab] Downloading page 95
[youtube:tab] Downloading page 96
[youtube:tab] Downloading page 97
[youtube:tab] Downloading page 98
[youtube:tab] Downloading page 99
[youtube:tab] Downloading page 100
[youtube:tab] Downloading page 101
[youtube:tab] Downloading page 102
[youtube:tab] Downloading page 103
[youtube:tab] Downloading page 104
[youtube:tab] Downloading page 105
[youtube:tab] Downloading page 106
[youtube:tab] Downloading page 107
[youtube:tab] Downloading page 108
[youtube:tab] Downloading page 109
[youtube:tab] Downloading page 110
[youtube:tab] Downloading page 111
[youtube:tab] Downloading page 112
[youtube:tab] Downloading page 113
[youtube:tab] Downloading page 114
[youtube:tab] Downloading page 115
[youtube:tab] Downloading page 116
[youtube:tab] Downloading page 117
[youtube:tab] Downloading page 118
[youtube:tab] Downloading page 119
[youtube:tab] Downloading page 120
[youtube:tab] Downloading page 121
[youtube:tab] Downloading page 122
[youtube:tab] Downloading page 123
[youtube:tab] Downloading page 124
[youtube:tab] Downloading page 125
[youtube:tab] Downloading page 126
[youtube:tab] Downloading page 127
[youtube:tab] Downloading page 128
[youtube:tab] Downloading page 129
[youtube:tab] Downloading page 130
[youtube:tab] Downloading page 131
[youtube:tab] Downloading page 132
[youtube:tab] Downloading page 133
[youtube:tab] Downloading page 134
[youtube:tab] Downloading page 135
[youtube:tab] Downloading page 136
ERROR: Unable to download JSON metadata: Remote end closed connection without response (caused by RemoteDisconnected('Remote end closed connection without response')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\<username>\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\<username>\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\program files\python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "c:\program files\python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "c:\program files\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\<username>\AppData\Roaming\Python\Python39\site-packages\youtube_dl\utils.py", line 2735, in https_open
    return self.do_open(functools.partial(
  File "c:\program files\python39\lib\urllib\request.py", line 1350, in do_open
    r = h.getresponse()
  File "c:\program files\python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "c:\program files\python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "c:\program files\python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"

F:\Users\<username>>
Edit: https://www.youtube.com/user/RTHK/videos?view=0&sort=da&flow=grid now redirects to https://www.youtube.com/channel/UC6of7UYhctnYmqABjUqzuxw/videos?view=0&sort=da, replacing /user/RTHK with /channel/UC6of7UYhctnYmqABjUqzuxw does not solve the issue

**Comment by dstftw** [comment]
Network issue on your side.
