### ISSUE TITLE
Get m3u8 hls link for 1080p Youtube videos

### ISSUE THREAD

**Issue by k3ns1n** [ytdl-org/youtube-dl#28991]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Hi!
I just found ios app [Web Video Cast](https://apps.apple.com/ua/app/web-video-cast-browser-to-tv/id1400866497) that can get m3u8 links for any supported resolutions even adaptive.
Resulting links looks like:

https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1620398299/ei/e_yUYKvUM6aQ-gav5LjgBA/ip/x.x.x.x/id/79088602e3509075/itag/96/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/sgoap/clen%3D43349893%3Bdur%3D2678.537%3Bgir%3Dyes%3Bitag%3D140%3Blmt%3D1585794801244984/sgovp/clen%3D1096458931%3Bdur%3D2678.480%3Bgir%3Dyes%3Bitag%3D137%3Blmt%3D1585810868075542/hls_chunk_host/r2---sn-n5uoxunxg8pjx03g-qv3e.googlevideo.com/mh/9-/mm/31,29/mn/sn-n5uoxunxg8pjx03g-qv3e,sn-3c27sn7e/ms/au,rdu/mv/m/mvi/2/pl/20/force_finished/1/gcr/ua/initcwndbps/1250000/vprv/1/playlist_type/DVR/dover/11/txp/5535432/mt/1620376373/fvip/14/keepalive/yes/fexp/24001373,24007246/c/WEB/cver/2.20210504.05.00/ptk/youtube_single/oid/nonBKEcZh7ILWIZCPwltzg/ptchn/dIp4tcWOGihEQKYxzSlFaQ/pltype/content/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,sgoap,sgovp,force_finished,gcr,vprv,playlist_type/sig/AOq0QJ8wRQIgAaDmAKeXFYbxnYCVdSVfgDmL8sliSVnsY185cKOElIYCIQD75WbMH6KhZ65mYaznLXjlwqXQzbKSJCO2lZ1wce06xQ%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRQIhAJolZaTqYfFjVp6Zj3oQsHPz8jWQLdnNE9yJurBZkti5AiBWbFY8Q_F3NTvR8C5YR02ZaqMk_UdiTSj22OjXTKvQXQ%3D%3D/playlist/index.m3u8?cpn=NHOi3sIxjwUlhfRM

So the proposal is to implement this feature for youtube-dl because it's more convenient then have two separated links to video and audio

**Comment by dstftw** [comment]
This is the default behavior.

**Comment by k3ns1n** [comment]
But how ?
I can get m3u8 links only for live streams while this app can do it for every link.
Youtube-dl only give me mp4 or dash links

**Comment by k3ns1n** [comment]
As i can see app do call like `curl -X $'GET' $'https://www.youtube.com/get_video_info?video_id=Usqi5xpIDXU&asv=3&el=detailpage&gl=UA&hl=eng'`

**Comment by k3ns1n** [comment]
Ok,  thanks!
You are right, i just changed user-agent that app use and received all m3u8 links.

**Comment by Reino17** [comment]
> _i just changed user-agent that app use_

Could you share?
