### ISSUE TITLE
Help with figuring out naming scheme

### ISSUE THREAD

**Issue by Bearmancer** [ytdl-org/youtube-dl#29018]
OK so I don't know programming or Python syntax and have spent more than the past hour going through online help and I am getting a headache trying to figure it out so I would appreciate if people could help me.

I am downloading audio files with their description from YouTube channels.

1) How do I make youtube-dl.exe be recognized automatically by cmd without needing to open the folder every time? On [this guide](url=https://www.youtube.com/watch?v=5axVgHHDBvU), he says that you need to add the folder to environmental variable which I did. My youtube-dl folder is on my external hard disk but when I open admin cmd, it doesn't recognize the command. The exe _is_ detected automatically if the youtube-dl folder is on C drive.
2) I want my output description file to be .txt not .description. I tried writing in my appdata's config folder 
```
--write-description
-o %title%s.txt
```
but that didn't work.
3) I want YouTube-dl to automatically put channels playlists in new folders that are named after the channel. So if I download from [Wellesz Theatre](url=https://www.youtube.com/user/TheWelleszTheatre), youtube-dl should automatically create a new folder in G:\Classical\YouTube called 'Wellesz Theatre.'
4) The audio files should follow the naming pattern of `*VIDEO_NAME* (*AUDIO_BITRATE*kbit_*AUDIO_CODEC*).*EXT*`

I tried `%title%s - %abr%s.%ext%s` but that didn't work.

**Comment by rautamiekka** [comment]
You'll need to create a dedicated folder where your ytdl exe is, and add that to the `PATH` environment variable. This guide shows how to modify `PATH`: https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

You should reboot the machine after so Command Prompt will notice it. You could place the ytdl path to the start of `PATH` to make the boot up of ytdl as fast as possible.

**Comment by harieamjari** [comment]
> You should reboot the machine after so Command Prompt will notice it.

I didn't have to reboot my machine. I just closed cmd and reopen it.
