### ISSUE TITLE
How to add login credentials in the config file?

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [ytdl-org/youtube-dl#29029]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'd like to add login credentials to the config file for vk.com so that I don't have to manually enter them every time I attempt to download a video from vk. But, how can I add the credentials to the config file only for vk, so that YouTube videos don't attempt to login too?

**Comment by kikuyan** [comment]
Try this https://github.com/ytdl-org/youtube-dl#authentication-with-netrc-file .
