### ISSUE TITLE
Skylinewebcams: Unable to extract stream url

### ISSUE THREAD

**Issue by pepebc** [ytdl-org/youtube-dl#29020]
### **Skylinewebcams: Unable to extract stream url**

It works ok from **Youtube**, but when I try to collect data from **Skylinewebcams** it gives me this error:

youtube-dl --verbose https://www.skylinewebcams.com/es/webcam/espana/andalucia/cadiz/grazalema.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.skylinewebcams.com/es/webcam/espana/andalucia/cadiz/grazalema.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.9.4 (CPython) - Linux-5.10.0-14-generic-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, rtmpdump 2.4
[debug] Proxy map: {}
[SkylineWebcams] grazalema: Downloading webpage
ERROR: Unable to extract stream url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/skylinewebcams.py", line 28, in _real_extract
    stream_url = self._search_regex(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract stream url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by mesosbrodleto** [comment]
Same error here. It seems that skylinewebcams is avoiding the connection
