### ISSUE TITLE
Won't work on any video at all

### ISSUE THREAD

**Issue by 343GuiltySpark-04** [ytdl-org/youtube-dl#29021]
Whenever i try to download from youtube i keep getting the same issue seen in the picture
![image](https://user-images.githubusercontent.com/69496138/117815364-63a89180-b233-11eb-9e86-ec96786d368f.png)

**Comment by kikuyan** [comment]
Please don't post just a screenshot. Make sure you're using the latest version first. If error persists, run with -v option, and copy & past the verbose log as text, please.

**Comment by 343GuiltySpark-04** [comment]
ok no problem i'll  get you the log when i get home :)

**Comment by Cristinasj** [comment]
I'm having the exact same issue

**Comment by 343GuiltySpark-04** [comment]
@Cristinasj are you on Debian or Ubuntu because I'm on Debian and i found the issue its because the Debian stable version is 2 years out of date, just use the install instructions here instead.

**Comment by Cristinasj** [comment]
You were right. Now it works. Thanks!
