### ISSUE TITLE
how to select specific audio when there are multiple audios ?

### ISSUE THREAD

**Issue by MinhajBoss** [ytdl-org/youtube-dl#29025]
how to select specific audios when there are multiple audios ? like curiosity stream in some site they have multi audio options, so i want to know how to download with multi audios or any specific audio ?

**Comment by dirkf** [comment]
Try using some audio parameters in the `-f` parameter string, such as `acodec` or `abr`: see FORMAT SELECTION in the manual.

**Comment by MinhajBoss** [comment]
can you tell what string will for for different and different audio ? here is the log,

`hls-audio_group-Audio_media_FMP4__audio_preview_en  mp4        audio only [en]
hls-audio_group-Audio_media_FMP4__audio_preview_es  mp4        audio only [es]
dash-d286aa05-e5bd-4230-820e-d2f64c0f8f64           m4a        audio only [Español] DASH audio  160k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-de29ad97-b193-4f9f-864d-97f1a151ab18           m4a        audio only [English] DASH audio  160k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-9d49bead-51c0-4c45-b6c3-8ec8a6d8bf26           mp4        640x360    DASH video  145k , mp4_dash container, avc1.64001E, video only
dash-24c609d6-83c0-4638-93dc-8a09403224b0           mp4        640x360    DASH video  253k , mp4_dash container, avc1.64001E, video only
hls-308                                             mp4        640x360     308k , avc1.64001E, video only
hls-415                                             mp4        640x360     415k , avc1.64001E, video only
dash-1e0891ea-de46-4652-a7c0-b5cd822a2dba           mp4        960x540    DASH video  468k , mp4_dash container, avc1.64001F, video only
hls-633                                             mp4        960x540     633k , avc1.64001F, video only
dash-d801d607-3aaf-42b2-bade-22bfbd0fc717           mp4        1280x720   DASH video  890k , mp4_dash container, avc1.64001F, video only
hls-1026                                            mp4        1280x720   1026k , avc1.64001F, video only
dash-c2b36b3a-1b74-4166-bb1a-1ca82fb117da           mp4        1920x1080  DASH video 1691k , mp4_dash container, avc1.640032, video only
hls-1888                                            mp4        1920x1080  1888k , avc1.640032, video only
dash-57491a53-9f51-47c6-871b-e5a18eed4dc3           mp4        1920x1080  DASH video 2825k , mp4_dash container, avc1.640032, video only
hls-3026                                            mp4        1920x1080  3026k , avc1.640032, video only
dash-58da607d-715a-4598-9b97-488cb5c601bf           mp4        2560x1440  DASH video 4929k , mp4_dash container, avc1.640032, video only
hls-5202                                            mp4        2560x1440  5202k , avc1.640032, video only
dash-e234d7fd-432e-4751-b8dd-1bd60fb9d838           mp4        2560x1440  DASH video 8598k , mp4_dash container, avc1.640032, video only
hls-9080                                            mp4        2560x1440  9080k , avc1.640032, video only
dash-27c82869-93e4-4a12-8791-5f7f9678c5b3           mp4        3840x2160  DASH video 15000k , mp4_dash container, avc1.640033, video only
hls-15674                                           mp4        3840x2160  15674k , avc1.640033, video only (best)`

**Comment by dirkf** [comment]
So the question is a good one: how do you select one out of several alternative audio tracks, when the tracks are not just different versions (quality, encoding, eg) of the same audio?

The manual is silent on selecting by language but a general solution is to run yt-dl with `-F` first to get a list like the one you posted and find the `format_id`s for the video and audio that you want, then run yt-dl with`-f video_id+audio_id` (supposing you want a combined media file with video and audio). In the above case:
 `-f hls-3026+dash-de29ad97-b193-4f9f-864d-97f1a151ab18`

If the selection criterion between the two runs could be codified, there could be a script to do the whole thing.

By all means provide a test URL.

It would seem to be a reasonable feature request to add `lang` to the set of audio parameters that can be filtered on for format selection like `acodec`) -- if it's not supported already.
