### ISSUE TITLE
Feature request: --create-playlists option

### ISSUE THREAD

**Issue by nanderer** [ytdl-org/youtube-dl#29024]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description
hi folks,

downloading whole playlists is a grate feature, also downloading multiple playlists with one command, but getting them played back in the right order is a bit harder, so an option like --create-playlists would be nice. It could create for each playlist item found in the download process a simple plaintext file (with .m3u or .pls extention, i dont really care cause i use --playlist option of mpv for playlists) with one relative (dosnt matter cause youtube-dl dosnt create folders) filename each line in the correct order. 

For example, when downloading 

https://music.youtube.com/playlist?list=OLAK5uy_nE2Zo9rHx_0Sykr9ahROZ9WIiwpOZw0gU
using 

youtube-dl -x --create-playlists

you would get not only 15 files (like with just the -x option) but also a 

Götter auf Abruf - OLAK5uy_nE2Zo9rHx_0Sykr9ahROZ9WIiwpOZw0gU.m3u

file referencing all 15 playable files in the correct order.

This way it would be possible to simply playback videos (like a whole music album as playlist) in the intended order ...

Thanks a lot in advance and keep up the good work
-- nanderer

**Comment by kikuyan** [comment]
If file names order is important, there's output template playlist_index. See https://github.com/ytdl-org/youtube-dl#output-template-examples .
Or, if you want a playlist file, maybe you could write a script to use the output of --flat-playlist -J .
