### ISSUE TITLE
Safari (O`reilly) downloads only one minuted video

### ISSUE THREAD

**Issue by anishkgt** [ytdl-org/youtube-dl#29022]
Hello,
I am trying the youtube-dl.exe on windows. I use SSO to sign in so i've used the Cookies.txt. i download the cookies.txt from firefox after logging in. The download starts and limits to 1 minute when the actual video is much more than an minute.
log is as below.
`C:\Users\George\Downloads\CISSP>%ytdl% -v
[debug] System config: []
[debug] User config: ['-i', '-c', '-U', '--no-warnings', '--console-title', '--batch-file=batch-file.txt', '--cookies', 'cookies.txt', '-o', '%(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Batch file urls: ['https://learning.oreilly.com/videos/cissp-3rd-edition/9780137442089/', 'https://learning.oreilly.com/videos/cissp-second-edition/9780135180488/', 'https://learning.oreilly.com/videos/the-complete-cybersecurity/9780136173717', 'https://learning.oreilly.com/videos/from-zero-to/9780136898641', 'https://learning.oreilly.com/videos/learn-ethical-hacking/9781801072991/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
youtube-dl is up-to-date (2021.04.26)
[safari:course] 9780137442089: Downloading course JSON
[download] Downloading playlist: CISSP, 3rd Edition
[safari:course] playlist CISSP, 3rd Edition: Collected 57 video ids (downloading 57 of them)
[download] Downloading video 1 of 57
[safari:api] 9780137442089/CIS3_01_01_01: Downloading part JSON
[safari] 9780137442089-CIS3_01_01_01: Downloading webpage
[Kaltura] 9780137442089-CIS3_01_01_01: Downloading webpage
[Kaltura] 1_5zq3mzdw: Downloading video info JSON
[Kaltura] 1_5zq3mzdw: Checking mp4-4323 URL
[Kaltura] 1_5zq3mzdw: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1926081/sp/192608100/playManifest/entryId/1_5zq3mzdw/format/url/protocol/http/flavorId/1_590gqwqt'
[download] Destination: CISSP, 3rd Edition\01-1.1 Organizational and Professional Ethics.mp4
[download] 100% of 38.99MiB in 00:07
[download] Downloading video 2 of 57
[safari:api] 9780137442089/CIS3_01_02_01: Downloading part JSON
[safari] 9780137442089-CIS3_01_02_01: Downloading webpage
[Kaltura] 9780137442089-CIS3_01_02_01: Downloading webpage
[Kaltura] 1_odw98g1e: Downloading video info JSON
[Kaltura] 1_odw98g1e: Checking mp4-4323 URL
[Kaltura] 1_odw98g1e: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1926081/sp/192608100/playManifest/entryId/1_odw98g1e/format/url/protocol/http/flavorId/1_m8xhxl79'
[download] Destination: CISSP, 3rd Edition\02-2.1 Information Security Fundamentals.mp4
[download] 100% of 30.51MiB in 00:05
[download] Downloading video 3 of 57
[safari:api] 9780137442089/CIS3_01_03_01: Downloading part JSON
[safari] 9780137442089-CIS3_01_03_01: Downloading webpage
[Kaltura] 9780137442089-CIS3_01_03_01: Downloading webpage
[Kaltura] 1_wji7yack: Downloading video info JSON
[Kaltura] 1_wji7yack: Checking mp4-4323 URL
[Kaltura] 1_wji7yack: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1926081/sp/192608100/playManifest/entryId/1_wji7yack/format/url/protocol/http/flavorId/1_mavhm21f'
[download] Destination: CISSP, 3rd Edition\03-3.1 Strategic Alignment.mp4
[download] 100% of 27.62MiB in 00:06
[download] Downloading video 4 of 57
[safari:api] 9780137442089/CIS3_01_03_02: Downloading part JSON
[safari] 9780137442089-CIS3_01_03_02: Downloading webpage
[Kaltura] 9780137442089-CIS3_01_03_02: Downloading webpage
[Kaltura] 1_olcm7feo: Downloading video info JSON
[Kaltura] 1_olcm7feo: Checking mp4-4323 URL
[Kaltura] 1_olcm7feo: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1926081/sp/192608100/playManifest/entryId/1_olcm7feo/format/url/protocol/http/flavorId/1_skmd3lh9'
[download] Destination: CISSP, 3rd Edition\04-3.2 Organizational Roles and Responsibilties.mp4
[download] 100% of 30.89MiB in 00:04
[download] Downloading video 5 of 57
[safari:api] 9780137442089/CIS3_01_03_03: Downloading part JSON

ERROR: Interrupted by user

C:\Users\George\Downloads\CISSP>`

**Comment by abdullahal25** [comment]
In my case using username and password instead of cookies file solved the problem
`youtube-dl -u "YOUR-MAIL" -p "PASS"`

**Comment by dstftw** [comment]
You must authenticate via credentials.

**Comment by moto-ctrl** [comment]
for SSO it's not an option, unfortunately - as authentication goes via federated identification. I'm just wondering if there's reason cookies don't work and direct uname/pass does, is that a complete blocker or it potentially could work with cookies but just requires dev and investigation time?
