### ISSUE TITLE
Paramount plus movies 

### ISSUE THREAD

**Issue by Nottoknow2** [ytdl-org/youtube-dl#29038]
for examples this wont download https://www.paramountplus.com/movies/spongebob-movie-sponge-on-the-run/tQk_Qooh5wUlxQqzj_4LiBO2m4iMrcPD/

**Comment by Nottoknow2** [comment]
[yt.txt](https://github.com/ytdl-org/youtube-dl/files/6476184/yt.txt)

**Comment by harieamjari** [comment]
Likely a violation of DMCA

**Comment by Nottoknow2** [comment]
> Likely a violation of DMCA and so youtube-dl will not support it.

Paramount shows work like spongebob

**Comment by ryandesign** [comment]
Duplicate of #17870.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30491

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/pull/30085

**Comment by 89z** [comment]
this one is DRM
