### ISSUE TITLE
Youtube-DL-GUI json error

### ISSUE THREAD

**Issue by D666N** [ytdl-org/youtube-dl#29034]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

This is the issue i am receiving and will not downoad anything.

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
Beginning download, this box will output progress
Youtube-DL has been found and set
Generating output directory structure
The output was generated and will be used
The quality and format has been set
Looking for ffmpeg
ffmpeg path is null, downloading may be affected
Arguments have been generated and are readonly in the textbox
Creating download thread
Created, starting download thread
[ITV] 10a0770a0003: Downloading webpage
[ITV] 10a0770a0003: Downloading JSON metadata
Error:
ERROR: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

An error occured

**Comment by dirkf** [comment]
Please review issue #28906 which appears to show the same problem, and has an interim solution.
