### ISSUE TITLE
blockdit.com

### ISSUE THREAD

**Issue by gridkr** [ytdl-org/youtube-dl#29030]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.blockdit.com/posts/60856e0c75abf30c50c654e7 

## Description

:~$ youtube-dl https://www.blockdit.com/posts/60856e0c75abf30c50c654e7
[generic] 60856e0c75abf30c50c654e7: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 60856e0c75abf30c50c654e7: Downloading webpage
[generic] 60856e0c75abf30c50c654e7: Extracting information
ERROR: Unsupported URL: https://www.blockdit.com/posts/60856e0c75abf30c50c654e7

Plays OK in Firefox and Chrome. youtube-dl returns "Unsupported URL".

**Comment by dstftw** [comment]
>This page is not available.
