### ISSUE TITLE
Introducing a new feature to YouTubeDL CLI

### ISSUE THREAD

**Issue by shortthirdman** [ytdl-org/youtube-dl#29041]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello there @dstftw , 

I want to develop a new feature in command-line interface by introducing a new option argument for formatting date for the output template.

This is to clarify/inquire whether a new branch needs to be checked out (after forking the repo) by naming it as my extractor.

But since the feature will be introduced irrespective of the extractor, should it be followed as written in the **Developer Instructions** section of the README. 

Please suggest.

Thanks
Swetank (@shortthirdman)

**Comment by dstftw** [comment]
If the feature is not related to adding a new extractor then obviously you should not exactly follow adding new site extractor tutorial.

**Comment by shortthirdman** [comment]
@dstftw Thanks buddy. I am on my plan to develop that feature included in the future releases of the tool.
