### ISSUE TITLE
Azure Media Service Videos are NOT downloading

### ISSUE THREAD

**Issue by letscodewithsriram** [ytdl-org/youtube-dl#29050]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

C:\Users\xxxxxx\Downloads>.\youtube-dl.exe -U
youtube-dl is up-to-date (2021.04.26)

C:\Users\xxxxxx\Downloads>.\youtube-dl.exe -F --verbose "https://ebgwblsradjhenwczae6ooknmb.streaming.mediaservices.windows.net/cfc485ff-2f64-44bc-9241-240419c04caf/1-5uzexnjuqyxqrzmo2qxxv7ngoc.ism/manifest(format=mpd-time-csf)"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--verbose', 'https://ebgwblsradjhenwczae6ooknmb.streaming.mediaservices.windows.net/cfc485ff-2f64-44bc-9241-240419c04caf/1-5uzexnjuqyxqrzmo2qxxv7ngoc.ism/manifest(format=mpd-time-csf)']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[generic] manifest(format=mpd-time-csf): Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest(format=mpd-time-csf): Downloading webpage
[generic] manifest(format=mpd-time-csf): Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\generic.py", line 2519, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

## Description

I am planning to download videos from Microsoft streams (hosted as Azure Media). It is not downloading videos from Azure Media's. 

Reference URL: 
https://blog.yannickreekmans.be/download-videos-from-azure-media-services/

**Comment by kikuyan** [comment]
Maybe DRM protected. There's a ContentProtection tag in the manifest.

**Comment by letscodewithsriram** [comment]
Is there any way to download DRM protected video using youtube-dl???

**Comment by kikuyan** [comment]
No, not supported.

**Comment by letscodewithsriram** [comment]
Can you suggest any other ways of downloading these DRM protected videos?

**Comment by kikuyan** [comment]
I have no knowledge, you better ask https://forum.videohelp.com/forums/48-Video-Streaming-Downloading .
