### ISSUE TITLE
use proxy when fetch metadata but not when download

### ISSUE THREAD

**Issue by tugrul** [ytdl-org/youtube-dl#29066]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.05.16**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

--proxy option is solving 429 issue but some proxies throttling bandwidth after a few downloads. can we define which steps are going to use proxy connection? 

For example use proxy to fetch metadata to obtain mp4 file links then download this links without proxy.

**Comment by Vangelis66** [comment]
@tugrul 

Is your request a general/**global** one that should encompass all `yt-dl` InfoExtractors or one that should be applied to just **specific IE**s?
Are you absolutely sure the stream CDN(s) **DOES NOT geo-block**?

The playlist APIs can
1) not enforce any geo-blocks at all 
2) enforce "soft" geo-block for non-sanctioned IPs; that soft block can be usually circumvented via an `X-Forwarded-For` request header, implemented automatically (for selected IEs) or manually, via `--geo-bypass` and/or `--geo-bypass-country CODE` and/or ` --add-header X-Forwarded-For:IP`
3) enforce a "hard" geo-block for non-sanctioned IPs (that can't be "fooled" with what is posted under "2"); you need to access the API from a whitelisted IP, through the use of proxy (HTTP/HTTPS/SOCKS), VPN, SmartDNS etc...
For **selected supported IE**s, you can also use the `--geo-verification-proxy` switch, to **just proxy requests to the Playlist API**...

OTOH, the stream CDN(s) can
1) not enforce any geo-block at all, regardless of what the Playlist API does (all the more **rarer** these days, rich content providers go the extra mile to geo-secure their streams, too 😠 )
2) enforce a "soft" geo-block on streams (see "2" in the playlist section above); that scheme was common in the "older" days, but is now very rare, too...
3) enforce a "hard" geo-block on ALL streams - the most common implementation!

To sum up, what you ask for can ONLY involve case "3" of Playlist API + case "1"**/**"2" of stream CDN... 

What I posted thus far relates to **geo-blocking on the IE's side**, I realise people also have to resort to using proxies in locations where **regime censorship** is in effect... 😞 Probably a different approach is needed in that last case...

If you are somehow more tech-savvy, you can use the browser's **Netwok Console** and identify exact hostnames for both the **Playlist API** and **Stream CDN** requests; then please take a look at a **still open** issue of mine from back in 2018 😞 , https://github.com/ytdl-org/youtube-dl/issues/16809 ...

Sadly, `yt-dl` doesn't support **proxy PAC scripts** (where you can dictate proxy use per hostname/url), but perhaps you can still use the **global proxy** flag, 
`--proxy="https://proxyhost:proxyport"` for `yt-dl` invocations, prepended in the command line by the `SET NO_PROXY="stream CDN hostname"` command 😉 ; use your favourite search engine for more details...

Hope I've helped...

**Comment by kikuyan** [comment]
Can be achieved on user's side.
- 1st run: write info.json file using proxy and skip download
- 2nd run: load info.json and download

However, for YouTube, you may not be able to download videos because video urls which are extracted from the first response data contain IP address.

A working example. `104.244.77.235` is not mine.
```
$ youtube-dl https://www.youtube.com/watch?v=SHcw_kh5tTA \
--write-info-json -o '%(id)s.%(ext)s' --proxy socks5://127.0.0.1:9050 --skip-download
[youtube] SHcw_kh5tTA: Downloading webpage
[info] Writing video description metadata as JSON to: SHcw_kh5tTA.info.json
$ youtube-dl --load-info-json SHcw_kh5tTA.info.json -o '%(id)s.%(ext)s' -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--load-info-json', u'SHcw_kh5tTA.info.json', u'-o', u'%(id)s.%(ext)s', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.10 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r4---sn-a5mlrnek.googlevideo.com/videoplayback?expire=1624523077&ei=5ezTYNfNNIWD6dsP85q0gAo&ip=104.244.77.235&id=o-AITNc9QJpkVSsL2rMBAahbtQcziGM6cv3PkzNvqtvg2b&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=bE&mm=31%2C29&mn=sn-a5mlrnek%2Csn-a5meknzr&ms=au%2Crdu&mv=m&mvi=4&pl=26&initcwndbps=95000&vprv=1&mime=video%2Fmp4&ns=z7jLF41ftRdZyNQWzqe0glAF&gir=yes&clen=137412866&dur=607.840&lmt=1620474660834229&mt=1624500996&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5535434&n=2zZnYugWbWs9M88527&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMjpUsgLSEb-k0qzIJW850SjRXxzLIHc9KtCQl5DEdqFAiAO_h1Z1nCtgLo7T6njkZCrrvfGc7_MEJ_ju1suKpG-qg%3D%3D&sig=AOq0QJ8wRAIgJN_6-jF0BdL6joFVbvn24hUPxNr-tocotSo2vPFGF4gCIFWMYrsg3lYNkIc_Hhix9NPy0P9NeM1EtnuuRCLtQwrP'
[download] Destination: SHcw_kh5tTA.f137.mp4
[download]   1.5% of 131.05MiB at  4.68MiB/s ETA 00:27^C
ERROR: Interrupted by user
```

**Comment by Vangelis66** [comment]
@kikuyan 

... Some stream manifests have **authentication tokens** which will expire very quickly 😠  (I've seen cases with tokens expiring **in less than 5sec** since first generation) ... 
Not the norm, of course 😄 , but one should definitely consider these edge cases when a **two-step method** is to be applied... 😜

**Comment by dirkf** [comment]
This procedure solved a similar issue:
https://github.com/ytdl-org/youtube-dl/issues/30032#issuecomment-930277655
