### ISSUE TITLE
Youtube: Hangs on deleting file after conversion

### ISSUE THREAD

**Issue by XaverStiensmeier** [ytdl-org/youtube-dl#29061]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.05.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [/] I've searched the bugtracker for similar issues including closed ones

```
youtube-dl --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=-XP-GnOhICs&list=PL5dY_A13NMFs2NLrcX_hHT57HDy4HHw_L --playlist-items 1 -v
[2] 10665
--playlist-items: command not found
[1]   Done                    youtube-dl --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=-XP-GnOhICs
(base) $ [youtube] -XP-GnOhICs: Downloading webpage
[download] Destination: Praise you - Jimmy Sax  (Tenor live Rework )--XP-GnOhICs.webm
[download] 100% of 5.05MiB in 00:01
[ffmpeg] Destination: Praise you - Jimmy Sax  (Tenor live Rework )--XP-GnOhICs.mp3
Deleting original file Praise you - Jimmy Sax  (Tenor live Rework )--XP-GnOhICs.webm (pass -k to keep)
```

## Description

File doesn't get deleted and it just takes forever.

**Comment by dstftw** [comment]
https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
