### ISSUE TITLE
Bitchute Not Downloading (HTTP Error 403)

### ISSUE THREAD

**Issue by harrington59802** [ytdl-org/youtube-dl#29060]
root1@Thomass-MacBook-Pro ~ % youtube-dl -U
youtube-dl is up-to-date (2021.04.26)

Video plays in browser. Proper quotes in place. One similar issue found but it has just been closed as a duplicate. Please read before marking as duplicate. 

- [ x] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.04.26**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log
root1@Thomass-MacBook-Pro ~ % youtube-dl -v 'https://www.bitchute.com/video/video_id/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.bitchute.com/video/video_id/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 2.7.16 (CPython) - Darwin-20.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-101541-g5282147d0c-tessus
[debug] Proxy map: {}
[BitChute] <video_id>: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

## Description
I am attempting to download a video from Bitchute using youtube-dl and have placed the webpage link in quotes as described in documentation.  This has worked reliably in the past but now results in HTTP Error 403. I am on Mac OS X which has Python 2.7 installed by default but I have also installed Python3.  It appears youtube-dl is using Python 2.7.

**Comment by dstftw** [comment]
You must provide reproducible environment. Stop posting duplicates.

**Comment by kikuyan** [comment]
> I am on Mac OS X which has Python 2.7 installed by default but I have also installed Python3. It appears youtube-dl is using Python 2.7.

If you want to run youtube-dl with python3, it must be found as the name `python` in your PATH.
Or try to run like: /*path-to*/python3 /*path-to*/youtube-dl ...

**Comment by rautamiekka** [comment]
Since Mac comes with Py2.7, replacing the binary/link with Py3 would likely break the system, at least partially.

The best way would be creating a shell `alias`.
