### ISSUE TITLE
[ATV.at] RegexNotFoundError on Bauer sucht Frau - Die zweite Chance

### ISSUE THREAD

**Issue by NeroBurner** [ytdl-org/youtube-dl#29079]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.05.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v "https://www.atv.at/bauer-sucht-frau-die-zweite-chance/folge-1/d3390693/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.atv.at/bauer-sucht-frau-die-zweite-chance/folge-1/d3390693/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Python version 3.9.5 (CPython) - Linux-5.12.3-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[ATVAt] d3390693: Downloading webpage
ERROR: Unable to extract player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/atvat.py", line 30, in _real_extract
    video_data = self._parse_json(unescapeHTML(self._search_regex(
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

- no credentials needed
- maybe geoblocked, I think you need an Austrian IP, but I'm not sure

I manually extracted links to the mp4 files and downloading them with `youtube-dl` is working

```sh
youtube-dl https://blocked-multiscreen.atv.cdn.tvnext.tv/2021/04/HD/hbbtv/6392863.mp4 \
https://blocked-multiscreen.atv.cdn.tvnext.tv/2021/04/HD/hbbtv/6392863_2.mp4 \
https://blocked-multiscreen.atv.cdn.tvnext.tv/2021/04/HD/hbbtv/6392863_3.mp4 \
https://blocked-multiscreen.atv.cdn.tvnext.tv/2021/04/HD/hbbtv/6392863_4.mp4
```

Attached see the script section extracted from the provided atv.at URL

[bauer_sucht_frau_die_zweite_chance_script_section.txt](https://github.com/ytdl-org/youtube-dl/files/6510583/bauer_sucht_frau_die_zweite_chance_script_section.txt)

**Comment by NeroBurner** [comment]
also tested on https://www.atv.at/bauer-sucht-frau-staffel-17/fuenfte-eventfolge/d3339537/ which definitely was working earlier, they seem to have changed the format

**Comment by annomatik** [comment]
Happens for me as well.

`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.atv.at/das-geschaeft-mit-der-liebe-2021/folge-1/d3346470/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.16 (CPython) - Linux-4.19.75-v7l+-armv7l-with-debian-10.2
[debug] exe versions: avconv 4.1.4-1, avprobe 4.1.4-1, ffmpeg 4.1.4-1, ffprobe 4.1.4-1
[debug] Proxy map: {}
[ATVAt] d3346470: Downloading webpage
ERROR: Unable to extract player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/servant/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/servant/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/servant/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/servant/.local/lib/python2.7/site-packages/youtube_dl/extractor/atvat.py", line 33, in _real_extract
    webpage, 'player data', group='json')),
  File "/home/servant/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by mortomanos** [comment]
Unfortunately ATV changed the URL of episodes completely in the last days so the extractor does not work anymore

Example: https://www.atv.at/tv/bauer-sucht-frau/staffel-18/bauer-sucht-frau-staffel-18-folge-3-die-hofwochen/bauer-sucht-frau-staffel-18-folge-3-die-hofwochen
There you have "tv" as element, the season information, and episode information.

**Comment by NeroBurner** [comment]
indeed. I opened an issue over at yt-dlp: https://github.com/yt-dlp/yt-dlp/issues/988

And I've created a branch with a working prototype implementation: https://github.com/NeroBurner/yt-dlp/tree/atvat_jwt_extract

**Comment by NeroBurner** [comment]
This PR is outdated, for the currently working version see https://github.com/yt-dlp/yt-dlp/pull/1012
