### ISSUE TITLE
unable to extract player URL

### ISSUE THREAD

**Issue by cracuxi** [ytdl-org/youtube-dl#29073]
This URL is the problem:  "https://www.youtube.com/watch?v=mat8ssW0ruI"

I can extract other videos like:
https://www.youtube.com/watch?v=q9E1CjO6A9g

**Comment by kikuyan** [comment]
You need to show the verbose log.

**Comment by kikuyan** [comment]
> [debug] youtube-dl version 2021.02.10

Update to the latest version 2021.05.16.

**Comment by cracuxi** [comment]
Thanks,
It is working on  2021.05.16.
