### ISSUE TITLE
Error downloading videos marked explicit

### ISSUE THREAD

**Issue by mcandre** [ytdl-org/youtube-dl#29084]
## Checklist

- [x] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.05.16** (Using 2020.03.24, the latest stable in Ubuntu 20.04)
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -vx "https://www.youtube.com/watch?v=HRfkqBfiLuM"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vx', 'https://www.youtube.com/watch?v=HRfkqBfiLuM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.5 (CPython) - Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] HRfkqBfiLuM: Downloading webpage
ERROR: HRfkqBfiLuM: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1788, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: HRfkqBfiLuM: YouTube said: Unable to extract video data
```

## Description

youtube-dl is encountering some glitch with explicit YouTube videos.

**Comment by xioren** [comment]
For what it's worth, what I noticed with my own youtube downloader, the bypass url that was working up until a little while ago is now returning 404 Not Found errors. I don't know it youtube-dl uses the same bypass approach but that might be the reason.

**Comment by kikuyan** [comment]
Works with the latest version 2021.05.16 if you pass cookies.

**Comment by mene311** [comment]
> Works with the latest version 2021.05.16 if cookies passed.

How do you that?

**Comment by kikuyan** [comment]
[How do I pass cookies to youtube-dl?](https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl)
