### ISSUE TITLE
Download a list of videos stored in a text file

### ISSUE THREAD

**Issue by aindriu80** [ytdl-org/youtube-dl#29101]
Understood.

## Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2021.05.16**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

Hi!

Youtube-dl is working well for me on Linux - I have one feature request, I would like to download a number of videos (from say the YouTube website) by placing the URL's of the videos into a .txt file, one URL per line, then run youtube-dl with the name of the text file and let youtube-dl work through the list as its ready.  It would save me a lot of time instead of having to do this for each video.

**Comment by 42-tardis** [comment]
youtube-dl -a <filename>
:)

**Comment by aindriu80** [comment]
It's working perfectly! Thanks very much :)
