### ISSUE TITLE
Cant download this youtube playlist

### ISSUE THREAD

**Issue by askfriends** [ytdl-org/youtube-dl#29110]
## Checklist

- [ *] I'm reporting a broken site support issue
- [ *] I've verified that I'm running youtube-dl version **2021.05.16**
- [ *] I've checked that all provided URLs are alive and playable in a browser
- [ *] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ *] I've searched the bugtracker for similar bug reports including closed ones
- [ *] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
Im using youtube-dl in tg bot, it works fine with almost all other playlists i have tried so far but it gives error with this playlist which im sharing here

https://www.youtube.com/playlist?list=PLgirwYDDPtS1fWzj8IBUxjN07pF9Y9wdg

Its may be bcoz due to number of videos may be larger than supported, if this is the case can we tell youtube-dl to download first lets say 50 videos and than from 51 to 100 and so on?

**Comment by dirkf** [comment]
It appears to find 90 videos for me. Perhaps you could follow the reporting guidelines and PASTE VERBOSE LOG HERE to show what's actually failing for you.

If your yt-dl is running inside a Telegram bot ("tg bot"?), perhaps that context is the problem.

**Comment by askfriends** [comment]
> It appears to find 90 videos for me. Perhaps you could follow the reporting guidelines and PASTE VERBOSE LOG HERE to show what's actually failing for you.
> 
> If your yt-dl is running inside a Telegram bot ("tg bot"?), perhaps that context is the problem.

Yes im using in telegram bot, btw how to find verbose log? can i find it in tg bot?
