### ISSUE TITLE
youtube-dl problem in bat file

### ISSUE THREAD

**Issue by neozbr** [ytdl-org/youtube-dl#29119]
if I open the console in the directory and type in the cmd: youtube-dl -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=PXZB-YiYIaks everything runs ok.

but if I create a bat download.bat and put the exactly same thing inside of this bat this happens when I click in this bat:

the cmd opens and execute like this:
youtube-dl -o "(ext)s" https://www.youtube.com/watch?v=PXZB-YiYIaks
[download] Destination: (ext)s
result it just generate a file named: (ext)s

why this is happening?!

**Comment by kikuyan** [comment]
[Output template and Windows batch files](https://github.com/ytdl-org/youtube-dl#output-template-and-windows-batch-files)

**Comment by neozbr** [comment]
thank you! it works! thanks a lot!
