### ISSUE TITLE
HTTP Error 404

### ISSUE THREAD

**Issue by GitAdict** [ytdl-org/youtube-dl#29111]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.05.16**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
terminal :
youtube-dl https://www.france.tv/france-3/scooby-doo-et-compagnie/scooby-doo-et-compagnie-saison-1/2489259-une-enquete-en-patins-a-glace.html
[FranceTVSite] 2489259-une-enquete-en-patins-a-glace: Downloading webpage
[FranceTV] 3be1981a-a408-48a6-a087-91c543c8abbe: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
>La vidéo n'est pas disponible
