### ISSUE TITLE
http404 recently on macos

### ISSUE THREAD

**Issue by axiaoxin** [ytdl-org/youtube-dl#29127]
## Checklist

not working recently on macos

version:
```
 brew upgrade youtube-dl
Warning: youtube-dl 2021.2.22 already installed
```

## Verbose log

```
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

video and playlist both 404, It's working fine before, but it's not recently

**Comment by rubyFeedback** [comment]
I assume Google changed a few things. You could try with the May release of youtube-dl, which may
work for some people; I also did not have any luck so far though, at the least with age-gate restricted
sites. If only we'd have a youtube without Google ...
