### ISSUE TITLE
Fragment don't get retried on certain errors

### ISSUE THREAD

**Issue by Atemu** [ytdl-org/youtube-dl#29129]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.05.16**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.crunchyroll.com/not-relevant-see-below', '--download-archive', 'not-relevant-see-below.archive', '-f', 'best', '--all-subs', '--write-sub', '--write-info-json', '--geo-bypass-country', 'US', '--retries', 'infinite', '--fragment-retries', 'infinite', '--hls-prefer-native', '--continue', '--ignore-errors', '--socket-timeout', '2', '--verbose', '--cookie', '/tmp/cookies-crunchyroll-com.txt', '--user-agent', 'Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Lazy loading extractors enabled
[debug] Python version 3.8.9 (CPython) - Linux-5.11.21-lqx2-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 6.159.13.117 (US) as X-Forwarded-For.
```

## Description

There is an intermittent issue with the crunchyroll downloader which happens ever dozen videos or so (`ERROR: unable to download video data: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1125)>`).  
I can't reproduce it reliably but no matter what causes this, the fragment it occurs on should be retried. Instead, ytdl aborts the video and moves on to the next video in the playlist.

Running the same command again works around this and it'll even pick up where it failed but this shouldn't be necessary with retries set to "infinite" and there's a chance it might fail again.

```
                   --retries "infinite"
                   --fragment-retries "infinite"
                   --hls-prefer-native
                   --continue
                   --ignore-errors
```

**Comment by didotb** [comment]
Everyone seems to be randomly experiencing this SSL error. All I could think of is one of YouTube's video servers are incorrectly configured. According to a [post from stackoverflow](https://stackoverflow.com/questions/51785882/youtube-dl-gave-me-an-error-about-ssl) passing `--no-check-certificate` might fix it, although definitely not recommended, for this is susceptible to MITM attacks

**Comment by dirkf** [comment]
If this persists, open a new issue using the broken site template, linking this one and including the **full verbose log**.
