### ISSUE TITLE
Downloading DASH segments and saving with custom filename

### ISSUE THREAD

**Issue by Puyodead1** [ytdl-org/youtube-dl#29128]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have a DASH manifest that I would like to download in a python program, I want to download the audio and video and keep them separate, I have achieved the desired results with youtube-dl via the command line but when I try to download in my program I don't get the desired effect.

The command that worked nicely for me: ``youtube-dl -k -o %(title)s-%(format_id)s.%(ext)s --force-generic-extractor --fixup never -f "bestvideo,bestaudio" "https://example.com/index.mpd?token=asasaad"``
The above command saves the files with the correct names.
- ``index-10.mp4``
- ``index-6.m4a``

When I try in my program using the following code:
```py
ytdl_opts = {'outtmpl': '%(title)s-%(format_id)s.%(ext)s', 'format': '6,10',  'fixup': 'never', 'verbose': True, 'force_generic_extractor': True, 'restrict-filenames': True, 'keepvideo': True}
ytdl = YoutubeDL(ytdl_opts)
ytdl.download(["https://example.com/index.mpd?token=asasaad"])
```
the files are downloaded as:
- ``index.mpdtoken=asasaad.mp4``
- ``index.mpdtoken=asasaad.m4a``

What am I doing wrong and what can I do to fix this?

**Comment by dstftw** [comment]
Provide complete verbose log.
