### ISSUE TITLE
HTTP Error 404: not found

### ISSUE THREAD

**Issue by mrfoxie** [ytdl-org/youtube-dl#29124]
I installed youtube-dl by the following instruction in `README.md` 
```
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```
with the latest version `2019.01.17` and when I tried to find out the resolution to download the video from youtube by following command `youtube-dl -F 'https://www.youtube.com/watch?v=ehtUb55Rmmg'` I got this error.
```
WARNING: unable to download video info webpage: HTTP Error 404: Not Found
WARNING: unable to download video info webpage: HTTP Error 404: Not Found
WARNING: unable to download video info webpage: HTTP Error 404: Not Found
WARNING: unable to download video info webpage: HTTP Error 404: Not Found
WARNING: unable to download video info webpage: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 11, in <module>
    load_entry_point('youtube-dl==2019.1.17', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3/dist-packages/youtube_dl/__init__.py", line 477, in main
    _real_main(argv)
  File "/usr/lib/python3/dist-packages/youtube_dl/__init__.py", line 467, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2002, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1672, in _real_extract
    token = video_info.get('token') or video_info.get('account_playback_token')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by SeraphSephiroth** [comment]
Try updating to the latest version with youtube-dl --update

**Comment by rubyFeedback** [comment]
> Try updating to the latest version with youtube-dl --update

I don't quite have the same error as the original threadstarter, but all 
age-gate restricted videos at youtube, since some days, no longer
work, even with the current git checkout of youtube-dl. It seems to me
as if Google changed a few things to make it harder to download 
videos directly.

**Comment by mrfoxie** [comment]
> Try updating to the latest version with youtube-dl --update

```
youtube-dl --update
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: youtube-dl's self-update mechanism is disabled on Debian.
Please update youtube-dl using apt(8).
See https://packages.debian.org/sid/youtube-dl for the latest packaged version.
```

**Comment by remitamine** [comment]
> youtube-dl: error: youtube-dl's self-update mechanism is disabled on Debian.

you have multiple versions installed in the system.

**Comment by mrfoxie** [comment]
no, i have installed i have just installed through apt-get command

**Comment by remitamine** [comment]
> youtube-dl is already the newest version (2019.01.17-1.1).
> ...
> youtube-dl --version  
> 2021.05.16 

obviously you have two versions installed(2019.01.17 and 2021.05.16), remove the old version.

**Comment by mrfoxie** [comment]
> > youtube-dl is already the newest version (2019.01.17-1.1).
> > ...
> > youtube-dl --version
> > 2021.05.16
> 
> obviously you have two versions installed(2019.01.17 and 2021.05.16), remove the old version.

thank you I have removed and installed it again and my problem is been solved
