### ISSUE TITLE
[REQUEST] Don't redownload video if ID is the same but title different

### ISSUE THREAD

**Issue by superbonaci** [ytdl-org/youtube-dl#29134]
## Checklist

- [x ] I'm reporting a feature request
- [x ] I've verified that I'm running youtube-dl version **2021.05.16**
- [x ] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
If I download a playlist, and the title is changes but ID is the same, it will re-download the video. My requrest is that there's some option like `--ignore-title-change` so the file `newcar-nepf8cMXRUs.mp4`, already downloaded, won't be download as a separate file with `newvideo-nepf8cMXRUs.mp4`

**Comment by baffled-mart** [comment]
Isn't this covered by --download-archive <your-text-file-name.txt> ?
e.g.
--download-archive youtube-dl-history.txt

line from file...
youtube Ve8h5EQ9cFY

**Comment by superbonaci** [comment]
@baffled-mart no idea didn't try. But that implies I have to export the playlist to a text file and update it accordingly as the playlist adds new items. On the other hand it's much easier to send the playlist URL to youtube-dl.exe directly. Unless the youtube-dl can also create such text file and allow me to update it easily...

**Comment by baffled-mart** [comment]
Isn't this covered by --download-archive <your-text-file-name.txt> ?
e.g.
youtube-dl  "https://www.youtube.com/watch?v=Ve8h5EQ9cFY"  --download-archive youtube-dl-history.txt

line in youtube-dl-history.txt ...>
youtube Ve8h5EQ9cFY

Resulting in...
>youtube-dl  "https://www.youtube.com/watch?v=Ve8h5EQ9cFY"  --download-archive youtube-dl-history.
txt
[youtube] Ve8h5EQ9cFY: Downloading webpage
[download] Setting up Vonets VAP11N Wi-Fi Bridge & Triple-Dragon USB adaptor has already been recorded in archive

**Comment by baffled-mart** [comment]
@superbonaci
If your text file doesn't exist the youtube-dl will create it, if the file does exist then each download is appended.
some examples...
brightcovenew 6243930839001
generic a8399956455a8839f38a0e0b3065fe52
dailymotion x810zjl

This works for both individual downloads and playlists (e.g. one line per video download, not one line for playlist).

While it may be a pita, you will have to retrospectively create your own history for all past downloads, but will be fine for anything in future.

I've found it very helpful, especially when the same video occurs in different playlists.

**Comment by baffled-mart** [comment]
Here is a command I use regularly

youtube-dl -f mp4 --no-check-certificate --ignore-errors --restrict-filenames --download-archive youtube-dl-history.txt --add-metadata  --batch-file playlist.txt -o "%(uploader)s/%(upload_date)s-%(title)s_%(id)s.%(ext)s"

History is contained in youtube-dl-history.txt
List of playlists in playlist.txt

I hope this makes sense.

**Comment by rautamiekka** [comment]
OP, you should always have the site-specific ID in the filenames to be able to find dupes without having to check literally every file.

My format for YT:
```
TITLE RESOLUTION #ID#.EXT
```
`RESOLUTION` could become `NA`, which is the case with audio, or if the data can't be fetched.

For ex:
```
Call of Duty - Black Ops 4 - All Weapon Reload Animations in 9 Minutes 854x480 #so_vULkIZFQ#.mkv
```

This way I can just search for `#so_vULkIZFQ#.` to find dupes of that.

**Comment by superbonaci** [comment]
Yeah but where do you insert the playlist url, say `https://www.youtube.com/playlist?list=PLcetZ6gSk968l1s4WuxwyhiyEUmg5GOZC`

**Comment by superbonaci** [comment]
@rautamiekka how do you get to use ID and check for it with a simple download command, say 
````
youtube-dl.exe https://www.youtube.com/playlist?list=PLcetZ6gSk968l1s4WuxwyhiyEUmg5GOZC
````

**Comment by baffled-mart** [comment]
@superbonaci
Even if I am downloading only one playlist I still use  --batch-file playlist.txt  (with just a single entry)
Example contents for one or more playlists,
The first line is all the playlists created on one channel.
The second and third lines are single playlists.
playlist.txt
----------
https://www.youtube.com/channel/UC1KYlOjI34ob_hicXVBuukA/playlists
https://www.youtube.com/playlist?list=PLWKjhJtqVAbnqBxcdjVGgT3uVR10bzTEB
https://www.youtube.com/playlist?list=PLcetZ6gSk968l1s4WuxwyhiyEUmg5GOZC

**Comment by superbonaci** [comment]
@baffled-mart I see so you can put playlists inside the batch file. I though you could only put single video URLS. Could help if you explain better dude you give lots of things for granted.

**Comment by baffled-mart** [comment]
Apologies for the formatting.  I also don't seem to be able to edit my posts!  Grrr.

"how do you get to use ID and check for it with a simple download command, say"

youtube-dl --get-id  https://www.youtube.com/playlist?list=PLcetZ6gSk968l1s4WuxwyhiyEUmg5GOZC > this-list-id.txt
youtube-dl --get-title  https://www.youtube.com/playlist?list=PLcetZ6gSk968l1s4WuxwyhiyEUmg5GOZC > this-list-title.txt

I do not know how to get one file with a nicely formatted id,title so I do it with two runs and merge the files.
The following gives a single line for each id and each title, which doubles file length and isn't so easy to read;
youtube-dl --get-id --get-title https://www.youtube.com/playlist?list=PLcetZ6gSk968l1s4WuxwyhiyEUmg5GOZC > this-list.txt

**Comment by superbonaci** [comment]
Very useful thanks.

**Comment by baffled-mart** [comment]
@superbonaci
I see so you can put playlists inside the batch file. I though you could only put single video URLS. Could help if you explain better dude you give lots of things for granted.

Sorry chap.

Also, I think I misread this (so ignor previous post?)
"how do you get to use ID and check for it with a simple download command, say"

Not sure what you mean.

**Comment by superbonaci** [comment]
@baffled-mart basically you are doing that with the file `youtube-dl-history.txt`. I wanted to have an option to not redownload files with same id, like I said in the example:
````
youtube-dl.exe --no-duplicates https://www.youtube.com/playlist?list=PLcetZ6gSk968l1s4WuxwyhiyEUmg5GOZC
````
Except that that option doesn't exist, so the way you do it works the same.

**Comment by baffled-mart** [comment]
Inside a batch file you can put...
a single video
https://www.youtube.com/watch?v=gdIskHlqRwc
a whole channel (obviously beware, could be thosuands...)
https://www.youtube.com/user/bbclearningenglish/videos
a single playlist
https://www.youtube.com/playlist?list=PLcetZ6gSk968eYHxKIIMe0N1yDQUfZx-G
all playlists for a channel
https://www.youtube.com/user/bbclearningenglish/playlists

Any combination of the above.

For what could be a very large number of videos like, https://www.youtube.com/user/bbclearningenglish/videos , I would always run the --get-title option to a text file first to find out how many videos I might be downloading and see if I do not want any.

Also be aware, as I am sure you are, that one video can be in more than one playlist on the same site and if you use the option --download-archive youtube-dl-history.txt (or whatever you want to call your history file) the video will only be downloaded once and placed from the first playlist it is found in.

I use the following output commands to keep playlists together, either
-o "%(playlist)s/%(playlist_index)s-%(title)s_%(id)s.%(ext)s"
or 
-o "%(playlist)s/%(upload_date)s-%(title)s_%(id)s.%(ext)s"

I hope this helps and is a little clearer.  It is past my bedtime! :-)

**Comment by baffled-mart** [comment]
The date options can be useful too (as only the video title has changed, the upload date should be the same).
 
Videos can be filtered by their upload date using the options --date, --datebefore or --dateafter. They accept dates in two formats:

    Absolute dates: Dates in the format YYYYMMDD.
    Relative dates: Dates in the format (now|today)[+-][0-9](day|week|month|year)(s)?

Examples:

# Download only the videos uploaded in the last 6 months
$ youtube-dl --dateafter now-6months

# Download only the videos uploaded on January 1, 1970
$ youtube-dl --date 19700101

$ # Download only the videos uploaded in the 200x decade
$ youtube-dl --dateafter 20000101 --datebefore 20091231

**Comment by superbonaci** [comment]
> 
> 
> Here is a command I use regularly
> 
> ````
> youtube-dl -f mp4 --no-check-certificate --ignore-errors --restrict-filenames --download-archive youtube-dl-history.txt --add-metadata --batch-file playlist.txt -o "%(uploader)s/%(upload_date)s-%(title)s_%(id)s.%(ext)s"
> ````
> 
> History is contained in youtube-dl-history.txt
> List of playlists in playlist.txt
> 
> I hope this makes sense.

If a video is removed from the playlist you still keep it on your computer right?
Also, is possible to put comments inside `playlist.txt`?
````
#List of music
https://www.youtube.com/channel/UC1KYlOjI34ob_hicXVBuukA/playlists
#List of movies
https://www.youtube.com/playlist?list=PLWKjhJtqVAbnqBxcdjVGgT3uVR10bzTEB
#List of shorts
https://www.youtube.com/playlist?list=PLcetZ6gSk968l1s4WuxwyhiyEUmg5GOZC
````

**Comment by rautamiekka** [comment]
> @baffled-mart I see so you can put playlists inside the batch file. I though you could only put single video URLS. Could help if you explain better dude you give lots of things for granted.

As far as ytdl (and by extension Python) is concerned you can give an infinite list of links at once. You'll only be limited by
- RAM.
- whatever bugs in Python or ...
- underlying problems in the C lib[rarie]s you might find

, and if you're giving all the links in the command instead of a download list file (or a `for` loop), whatever the char[acter] limit the shell/terminal (in Window$ case the Command Prompt or PowerShell) has. I think you're only limited by RAM on non-Window$ if you force a diff[erent] limit, but in any case there's a pre-existing RAM-unrelated limit.

^ So, it's a good idea to use those list files, or at least in the case of YT give only the vid/playlist ID unless it's absolutely necessary for the goal, since ytdl defaults to YT if the link is incomplete, and creating entire commands to download something will make long strings of text (I know from 1st-hand experience since I've a long Batch file for the purpose).

**Comment by rautamiekka** [comment]
> If a video is removed from the playlist you still keep it on your computer right?
> Also, is possible to put comments inside `playlist.txt`?
> 
> ```
> #List of music
> https://www.youtube.com/channel/UC1KYlOjI34ob_hicXVBuukA/playlists
> #List of movies
> https://www.youtube.com/playlist?list=PLWKjhJtqVAbnqBxcdjVGgT3uVR10bzTEB
> #List of shorts
> https://www.youtube.com/playlist?list=PLcetZ6gSk968l1s4WuxwyhiyEUmg5GOZC
> ```

The status of a vid on the website doesn't matter as far as the already downloaded ones are concerned.

Yes, that's how the comments work.

**Comment by superbonaci** [comment]
> 
> 
> Also be aware, as I am sure you are, that one video can be in more than one playlist on the same site and if you use the option --download-archive youtube-dl-history.txt (or whatever you want to call your history file) the video will only be downloaded once and placed from the first playlist it is found in.
With the option you provided you just sort videos by Author (channel), so is pointless to speak about sorting them by playlists. I think that's the best idea since there can't be more than one author for the same video ID.
