### ISSUE TITLE
fragment-retries flag doesn't retry on CrunchyRoll HLS Segments

### ISSUE THREAD

**Issue by bruhaha1313** [ytdl-org/youtube-dl#29130]
Using the latest version of youtube-dl (2021.05.16 as of this writing).

Steps to reproduce:
1. Download a video of your choice from CrunchyRoll (other sites may also be affected, but this is the one where I noticed the issue).
2. An individual segment of the download will often (but not always) fail with the following:

[hls @ 0x8060a5000] HLS request for url 'https://a-vrv.akamaized.net/evs1/f0e889b8a6588b9b5715defa82cff6fa/assets/f3myk6ye7g607ad_860963.mp4/seg-91-v1-a1.ts?t=exp=1622141793~acl=/evs1/f0e889b8a6588b9b5715defa82cff6fa/assets/f3myk6ye7g607ad_860963.mp4/*~hmac=46d60c4d8f9ac4fdb6d854e0284e8b59ef2de641f84e211f1dbb4265964b94c7', offset 0, playlist 0
[hls @ 0x8060a5000] Opening 'crypto+https://a-vrv.akamaized.net/evs1/f0e889b8a6588b9b5715defa82cff6fa/assets/f3myk6ye7g607ad_860963.mp4/seg-91-v1-a1.ts?t=exp=1622141793~acl=/evs1/f0e889b8a6588b9b5715defa82cff6fa/assets/f3myk6ye7g607ad_860963.mp4/*~hmac=46d60c4d8f9ac4fdb6d854e0284e8b59ef2de641f84e211f1dbb4265964b94c7' for reading
[tcp @ 0x806d89d00] Starting connection attempt to 2600:1408:7400::17c7:3f92 port 443
[tcp @ 0x806d89d00] Connected attempt failed: No route to host
[tcp @ 0x806d89d00] Starting connection attempt to 2600:1408:7400::17c7:3fb0 port 443
[tcp @ 0x806d89d00] Connected attempt failed: No route to host
[tcp @ 0x806d89d00] Connection to tcp://a-vrv.akamaized.net:443 failed: No route to host
[crypto @ 0x8068c0340] Unable to open resource: https://a-vrv.akamaized.net/evs1/f0e889b8a6588b9b5715defa82cff6fa/assets/f3myk6ye7g607ad_860963.mp4/seg-91-v1-a1.ts?t=exp=1622141793~acl=/evs1/f0e889b8a6588b9b5715defa82cff6fa/assets/f3myk6ye7g607ad_860963.mp4/*~hmac=46d60c4d8f9ac4fdb6d854e0284e8b59ef2de641f84e211f1dbb4265964b94c7
[hls @ 0x8060a5000] Failed to open segment 91 of playlist 0

When this happens, the video is corrupted (pauses where the missing segment should have been). You won't know that you have a corrupt file unless you happened to catch the red text scrolling by (or when you watch the video and it skips).

And for the life of me, I cannot change this behavior. In varying combinations, I've tried:

--retries infinite
--retries 99999
--fragment-retries infinite
--fragment-retries 99999
--abort-on-unavailable-fragment (so at least I can stop watching like a hawk for red text)
--hls-prefer-native
--hls-prefer-ffmpeg
--socket-timeout 999

"--fragment-retries infinite" in tandem with "--hls-prefer-native", in particular, should cause youtube-dl to retry the failed segment (at least the way the documentation reads). It's because of this and the resulting corruption that I am filing this as a bug, but after spending the past hour+ tearing my hair out over this behavior, any help would be appreciated (the issue occurs on about 75% of my download attempts, these take a good 10 minutes each to download in full, and my only workaround so far is Ctrl+C and start over again after the first error scrolls past).

**Comment by remitamine** [comment]
not supported by ffmpeg, you can use the native HLS downloader instead.

**Comment by bruhaha1313** [comment]
> not supported by ffmpeg, you can use the native HLS downloader instead.

Isn't that what --hls-prefer-native is supposed to do? The combination of "--fragment-retries infinite" and "--hls-prefer-native" was probably my biggest hope for changing this behavior, and it had no effect in my testing.

**Comment by remitamine** [comment]
> Isn't that what --hls-prefer-native is supposed to do? The combination of "--fragment-retries infinite" and "--hls-prefer-native" was probably my biggest hope for changing this behavior, and it had no effect in my testing.

it should, but based on the incomplete output that you've posted, ffmpeg is been used to download the video, so either the HLS manifest is not support by HLS native downloader or you don't have pycrypto/pycryptodome if the fragments are AES-128 encrypted.

**Comment by bruhaha1313** [comment]
It was the missing pycryptodome. I have youtube-dl installed in a FreeBSD Jail and freshports doesn't list optional dependencies, so I had no idea I needed it for anything. :-/

Thanks for the help!
