### ISSUE TITLE
My bot isn't working it says that error no video formats found

### ISSUE THREAD

**Issue by ashianna** [ytdl-org/youtube-dl#29143]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
How do i fix it?

**Comment by smihai** [comment]
I have the same error message.
I suppose it's due to the redirection to https://consent.youtube.com as youtube-dl opens a new web session each time.

**Comment by colethedj** [comment]
you need to provide some sort of logs (and make sure you are on the latest version)

**Comment by smihai** [comment]
Hi,

Well, with le last version there are no problems.
Thank you. The issue can be closed, I guess.
