### ISSUE TITLE
Unable to download YouTube Watch Later playlist

### ISSUE THREAD

**Issue by superbonaci** [ytdl-org/youtube-dl#29159]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.05.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -u account@gmail.com -j --flat-playlist "https://www.youtube.com/playlist?list=WL"
Type account password and press [Return]: 
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
ERROR: The playlist does not exist.
```

**Comment by colethedj** [comment]
you need to use cookies, logging in with user/password currently does not work.

**Comment by superbonaci** [comment]
Where/how do I get the cookie?

**Comment by colethedj** [comment]
https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl

**Comment by superbonaci** [comment]
Isn't there any way to automatically fetch cookies from Firefox/Chrome? I think I'll just move all videos to a public playlist and use that from now on...

**Comment by colethedj** [comment]
From the link:
> In order to extract cookies from browser use any conforming browser extension for exporting cookies. For example, Get cookies.txt (for Chrome) or cookies.txt (for Firefox).

These extensions will create a cookies.txt file you pass with `--cookies` param

Though, if you have >100 videos in the playlist, youtube-dl won't be able to grab them all anyways (https://github.com/ytdl-org/youtube-dl/issues/28362), so making it public (or unlisted) might be the easier way to go.
