### ISSUE TITLE
Monetization for video creators?

### ISSUE THREAD

**Issue by Heath123** [ytdl-org/youtube-dl#29156]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions 
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Do video creators make money from youtube-dl? Also, does it count as a view with full watch time? I'm using --include-ads, but it doesn't seem to work. I'm making an offline YouTube viewer and I want to make sure it doesn't harm the creator in any way compared to watching the video normally, either by not making them money, not adding views, making the algorithm think the video isn't being watched all the way through because it isn't interesting, messing up analytics or anything like that.
Sorry if this has been asked before, but I can't find anything in the GiutHub issues search and Googling `youtube-dl monetization` just gives me info about the RIAA takedown (I'd be surprised if no-one has ever been worried about this though).

**Comment by Heath123** [comment]
Full command line options: `--mark-watched --include-ads --write-info-json --write-thumbnail --write-sub --write-auto-sub``

**Comment by dstftw** [comment]
youtube-dl only partially emulates browser's behavior, whether this affects monetization is up to Youtube. youtube-dl does not provide (and actually can't) any guarantees on that.

**Comment by Heath123** [comment]
OK, I did a test on my own unlisted video and it doesn't seem to add a view, but then neither does a signed-out view from the same PC... Maybe I should test from another IP

**Comment by Heath123** [comment]
I know it might be hard to keep up with YouTube's API changes and also it could be abused as view bot, but it would be nice if it could count as a view... That might be a job for a browser automation library though

**Comment by Heath123** [comment]
Doesn't seem to be going up to 2, so for anyone finding the issue through search, no, it doesn't seem to add a view
