### ISSUE TITLE
HTTP download error + MKV merge error

### ISSUE THREAD

**Issue by vvglyy** [ytdl-org/youtube-dl#29168]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, 
What does it mean `[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 104 (attempt 8 of 10)...` ?
And why : 
`youtube-dl -v -f bestvideo+bestaudio/best --download-archive archive.txt --merge-output-format MKV -i --all-subs --embed-subs --add-metadata --write-info-json --write-description -o "%(uploader)s/%(upload_date)s - %(title)s %(id)s.%(ext)s" --yes-playlist `
have some (for example) webm.part + m4a --> `--merge-output-format MKV ` then failed?

**Comment by dstftw** [comment]
Post complete verbose log.
