### ISSUE TITLE
Youtube update..

### ISSUE THREAD

**Issue by BurnerGR** [ytdl-org/youtube-dl#29179]
It seems like youtube have updated their website, youetube-dl seems to fail on any youtube video.

**Comment by guillerpsanchez** [comment]
> It seems like youtube have updated their website, youetube-dl seems to fail on any youtube video.

Hello, youtube is working from my lab, can you please explain more the error you are getting, or if is possible the url or urls of the videos you are trying to get?

Please include the output of "youtube-dl -v" to see if something is wrong.

Thank you in advance.

**Comment by cxr6548** [comment]
not OP but I'm having issues using youtube-dl by itself, through MPV and through VLC

`$ youtube-dl -v https://www.youtube.com/watch?v=ltfl8hS8QB0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=ltfl8hS8QB0']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.5 (CPython) - Linux-5.8.0-53-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ltfl8hS8QB0: Downloading webpage
ERROR: ltfl8hS8QB0: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1788, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: ltfl8hS8QB0: YouTube said: Unable to extract video data`

This appears to happen with any video

**Comment by tinybug** [comment]
your version is too old, you should have a update

**Comment by guillerpsanchez** [comment]
> not OP but I'm having issues using youtube-dl by itself, through MPV and through VLC
> 
> `$ youtube-dl -v https://www.youtube.com/watch?v=ltfl8hS8QB0 [debug] System config: [] [debug] User config: [] [debug] Custom config: [] [debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=ltfl8hS8QB0'] [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8 [debug] youtube-dl version 2020.03.24 [debug] Python version 3.8.5 (CPython) - Linux-5.8.0-53-generic-x86_64-with-glibc2.29 [debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4 [debug] Proxy map: {} [youtube] ltfl8hS8QB0: Downloading webpage ERROR: ltfl8hS8QB0: YouTube said: Unable to extract video data Traceback (most recent call last): File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info ie_result = ie.extract(url) File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 530, in extract ie_result = self._real_extract(url) File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1788, in _real_extract raise ExtractorError( youtube_dl.utils.ExtractorError: ltfl8hS8QB0: YouTube said: Unable to extract video data`
> 
> This appears to happen with any video

As @tinybug commented your version is 2020.03.24 and the actual one is 2021.05.16 i recommend you to update it to get it working again.
