### ISSUE TITLE
Trying to download age-restricted video using -u and -p but it won't authenticate

### ISSUE THREAD

**Issue by LORI32768** [ytdl-org/youtube-dl#29171]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

I am trying to download an age-restricted video so I used the -u and -p options to enable the application
to log-in first however this fails to work producing the output

[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[youtube] dl-wCB6hbxY: Downloading webpage
[youtube] dl-wCB6hbxY: Refetching age-gated info webpage
WARNING: Unable to download video info webpage: HTTP Error 404: Not Found
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.

My Username/Password is certainly correct, I am using the windows command line version of youtube-dl

Can you tell me what the problem could be here?

Regards from Lori F

**Comment by dstftw** [comment]
Use cookies.

**Comment by LORI32768** [comment]
Dear Sergey,

I always accept cookies on a website and this was no exception I looked at
the site data
just now and there are cookies from Github on my machine, the site should
be allowed.

Do I have to repost this question? I was rather hoping for a more positive
response than
just having someone close my question off with not any explanation. It did
take effort
and consideration to copy out the informatio accurately. I am a computer
programmer myself
and believed that another similarly technical person as might exist on your
site could
assist me, probably without much difficulty. I read the FAQ and the
documentation in it's
entirety but it just implies exactly what I am doing.

Regards Lori F

**Comment by kikuyan** [comment]
Try this: [How do I pass cookies to youtube-dl?](https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl)
