### ISSUE TITLE
'bool' object has no attribute 'split'

### ISSUE THREAD

**Issue by dmitrypisanko** [ytdl-org/youtube-dl#29185]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.05.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://youtube.com/watch?v=xh1xsHpZlvs', u'--dump-json', u'--no-warnings', u'--no-call-home', u'--no-check-certificate', u'--socket-timeout', u'10', u'--flat-playlist', u'--skip-download', u'--ignore-errors', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
[debug] exe versions: ffmpeg 4.4-static, ffprobe 4.4-static
[debug] Proxy map: {}
ERROR: 'bool' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1502, in _real_extract
    }, fatal=False)),
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2644, in compat_parse_qs
    encoding=encoding, errors=errors)
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2614, in _parse_qsl
    pairs = [s2 for s1 in qs.split('&') for s2 in s1.split(';')]
AttributeError: 'bool' object has no attribute 'split'
```

## Description

Can't get data for specific youtube video

**Comment by dirkf** [comment]
Apparently this only appears with Python 2, but the `_download_webpage()` extractor method can return `False` rather than a string (or actually `compat_str`) and so the result of the call needs to be or-ed with an empty string at l.1502 of `youtube_dl/extractor/youtube.py` to avoid a boolean value being passed as the first argument of `compat_parse_qs()`, which should be a string.

Here are ll.1495 on of `youtube_dl/extractor/youtube.py` with the change applied:
```
            pr = self._parse_json(try_get(compat_parse_qs(                     
                self._download_webpage(                                        
                    base_url + 'get_video_info', video_id,                     
                    'Refetching age-gated info webpage',                       
                    'unable to download video info webpage', query={           
                        'video_id': video_id,                                  
                        'eurl': 'https://youtube.googleapis.com/v/' + video_id,
                    }, fatal=False) or ''),                                     
                lambda x: x['player_response'][0],                              
                compat_str) or '{}', video_id)                                  
```
However the command still fails with this change, and with Python 3, unless you provide age-appropriate login details:
```
ExtractorError: Sign in to confirm your age
This video may be inappropriate for some users.
```

**Comment by EdoRoshi** [comment]
I'm having this same problem, but am unable to understand how to fix it. It is fixed? Should I try to upgrade my python?

**Comment by 89z** [comment]
Post new issue if its still a problem

**Comment by kikuyan** [comment]
@EdoRoshi 
Try yt-dlp instead. See https://github.com/ytdl-org/youtube-dl/issues/30255#issuecomment-974783474.
There's no fix for youtube-dl at the moment. If you are using Python 2.x and upgrade to 3.x, you'll get better error message at best.
