### ISSUE TITLE
闪退崩溃（我已安装必要组件）

### ISSUE THREAD

**Issue by CFX1234567890** [ytdl-org/youtube-dl#29193]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.05.16**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

https://user-images.githubusercontent.com/85213740/120428699-babf0380-c3a6-11eb-8e3c-59027f210cf0.mp4

**Comment by kikuyan** [comment]
youtube-dl is a command line program. https://github.com/ytdl-org/youtube-dl#description
I guess you are trying to open the application icon.

**Comment by CFX1234567890** [comment]
Windows版本的exe应用程序，但是打不开，有错误提示（图片）








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月2日(星期三) 下午3:14
收件人: ***@***.***&gt;; 
抄送: "HUC ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ytdl-org/youtube-dl] 闪退崩溃（我已安装必要组件） (#29193)






Youtube - dl 是一个命令行程序。https://github.com/ytdl-org/youtube-dl#描述
我猜你是想打开应用程序图标。

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.

**Comment by rautamiekka** [comment]
That is not how youtube-dl works. You must use the Command Prompt or PowerShell to enter a command with parameters and flags. The documentation on the front page at https://github.com/ytdl-org/youtube-dl shows everything you need to know.

**Comment by rautamiekka** [comment]
The vast majority of the old M$-DO$ commands are still equally valid in Command Prompt, which is a subset of M$-DO$ 7, with later Window$ versions introducing some new things. So, the comparison is something like 98.99999% valid.

PowerShell, on the other hand, is like Bash in that you can do so much with the integral stuff, but is a completely diff thing from Command Prompt, and Bash, as far as syntax goes.

**Comment by xinhuang327** [comment]
老铁，你需要从命令行执行这个程序，基本就是youtube-dl 空格 跟上你要下载的视频网页地址。
