### ISSUE TITLE
.mpd file download

### ISSUE THREAD

**Issue by vishalhoc** [ytdl-org/youtube-dl#29203]
https://cf5.madeeasy.in/out/v1/5f5ec55b1d204c2f860f4c79e68395f8/71a6e94978004f3d87a1c5dc42087096/bba156f81a894e0f87912846b250943f/index.mpd

its download a file index.mpd and when i open it in notepad it show some xml / html coding

![2021-06-03 (2)](https://user-images.githubusercontent.com/13188309/120583652-4a6abd80-c44c-11eb-9c5f-f7b55bef545a.png)

**Comment by kikuyan** [comment]
DRM protected.

**Comment by vishalhoc** [comment]
> DRM protected.

yes

**Comment by vishalhoc** [comment]
> DRM protected.

but i have licence link
