### ISSUE TITLE
Can not download facebook video

### ISSUE THREAD

**Issue by softsingh** [ytdl-org/youtube-dl#29210]
Hello

I can not download the following facebook video
https://www.facebook.com/100053253602742/videos/2674502702878784

Please update the software.

Thanks

**Comment by dirkf** [comment]
It would have been helpful to follow the bug reporting guidelines.

As with some other recent FB-related issues, the quoted URL reports (UK):
```
youtube_dl.utils.ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
```
