### ISSUE TITLE
Adding number to playlist_index (counter)

### ISSUE THREAD

**Issue by LuKaN1u** [ytdl-org/youtube-dl#29220]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have got just one question. It it possilble for youtube-dl to start counter from specific number?

Command I use (command prompt):
youtube-dl -i -f m4a -o "%(playlist)s\%(playlist_index)s.%(title)s.%(ext)s" LinkToPlaylist

I wanna be able to add 100 to playlist index instead of starting from 1 so:
101, 102, 103....

**Comment by dstftw** [comment]
No, use autonumber.
