### ISSUE TITLE
Why cant i download?

### ISSUE THREAD

**Issue by Abdullah-Bhutta** [ytdl-org/youtube-dl#29238]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
python azure_downloader.py -i https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism
[generic] manifest(format=mpd-time-csf): Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest(format=mpd-time-csf): Downloading webpage
[generic] manifest(format=mpd-time-csf): Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\generic.py", line 2525, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Abdullah\Downloads\azure_video_downloader\azure_downloader.py", line 260, in <module>
    ydl.download([inputs])
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output

AND the --verbose is:-

PS C:\Users\Abdullah\Downloads\azure_video_downloader> python -m youtube_dl -F https://videoengine.punjabcollege.net/6c8bdf75-c6bf-4c1c-80ef-477cc59fd3a9/chem1ch1lect1-new.ism/manifest --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://videoengine.punjabcollege.net/6c8bdf75-c6bf-4c1c-80ef-477cc59fd3a9/chem1ch1lect1-new.ism/manifest', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.5 (CPython) - Windows-10-10.0.19043-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\generic.py", line 2508, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
## Description

WRITE DESCRIPTION HERE

Cant download, say that No supported formats found.
why python -m youtube_dl -F 'https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/manifest(format=mpd-time-csf)' is not working but python -m youtube_dl -F "https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/manifest(format=mpd-time-csf)" is working just fine??

Help PLZ

**Comment by Abdullah-Bhutta** [comment]
I need help

**Comment by didotb** [comment]
it says "403 - forbidden" for me. are you sure you're supposed to have access to it? The app might not be able to see any formats because it can't access the website itself

**Comment by dmzoneill** [comment]
same here, just download the latest version

`youtube-dl --verbose  "https://www.youtube.com/watch?v=y6120QOlsfU"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=y6120QOlsfU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.02.10
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-5-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] y6120QOlsfU: Downloading webpage
[youtube] y6120QOlsfU: Downloading API JSON
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1632, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by dmzoneill** [comment]
trying an older version....

**Comment by dmzoneill** [comment]
incognito in the browser i get 
![image](https://user-images.githubusercontent.com/15192260/121246340-fa9b5480-c898-11eb-950f-12de9fd9a181.png)

**Comment by Abdullah-Bhutta** [comment]
> it says "403 - forbidden" for me. are you sure you're supposed to have access to it? The app might not be able to see any formats because it can't access the website itself

I think its Geotagged to my country

**Comment by Abdullah-Bhutta** [comment]
> incognito in the browser i get
> ![image](https://user-images.githubusercontent.com/15192260/121246340-fa9b5480-c898-11eb-950f-12de9fd9a181.png)

Yes, because when you open incognito, none of your history passwords, cookies etc. are not present, and when you close the window, it deletes all the information from your computer about the activity.

**Comment by didotb** [comment]
> > it says "403 - forbidden" for me. are you sure you're supposed to have access to it? The app might not be able to see any formats because it can't access the website itself
> 
> I think its Geotagged to my country

if it is geotagged you might need to specify the [--geo-bypass](https://github.com/ytdl-org/youtube-dl#geo-restriction) argument. click the link for help. it leads to [README.md](https://github.com/ytdl-org/youtube-dl/blob/master/README.md)

**Comment by didotb** [comment]
> same here, just download the latest version
> 
> youtube-dl --verbose "https://www.youtube.com/watch?v=y6120QOlsfU"
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=y6120QOlsfU']
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
> [debug] youtube-dl version 2021.02.10
> [debug] Python version 3.9.2 (CPython) - Linux-5.10.0-5-amd64-x86_64-with-glibc2.31
> [debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, rtmpdump 2.4
> [debug] Proxy map: {}
> [youtube] y6120QOlsfU: Downloading webpage
> [youtube] y6120QOlsfU: Downloading API JSON
> WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
> File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
> return func(self, *args, **kwargs)
> File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
> ie_result = ie.extract(url)
> File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
> ie_result = self._real_extract(url)
> File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1632, in _real_extract
> self._sort_formats(formats)
> File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1367, in _sort_formats
> raise ExtractorError('No video formats found')
> youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

the dump says your app version is `2021.02.10`. try updating first via `youtube-dl --update`

**Comment by dmzoneill** [comment]
Not sure if it was some stupidity on my side or geo-bypass.

Either way its working... thanks


dave@dave-pc:~/Desktop/dnb/dance$ ~/Downloads/youtube-dl --geo-bypass --verbose "https://www.youtube.com/watch?v=y6120QOlsfU"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--geo-bypass', u'--verbose', u'https://www.youtube.com/watch?v=y6120QOlsfU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Linux-5.10.0-5-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] y6120QOlsfU: Downloading webpage
[youtube] y6120QOlsfU: Downloading player 68cc98b3
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r3---sn-q0c7rn76.googlevideo.com/videoplayback?expire=1623246515&ei=U3LAYJWOG8H6xN8P0qSEiA8&ip=2a02%3A8084%3A983e%3Ad380%3Ab8fe%3Abcee%3A463%3A39d4&id=o-AHgTNsYSeiK3lUrXwSBQssb9HMsywbg3oy7lO-nEMVNB&itag=134&aitags=133%2C134%2C160%2C242%2C243%2C278%2C394%2C395%2C396&source=youtube&requiressl=yes&mh=Yy&mm=31%2C26&mn=sn-q0c7rn76%2Csn-aigzrne7&ms=au%2Conr&mv=m&mvi=3&pl=30&initcwndbps=1782500&vprv=1&mime=video%2Fmp4&ns=Q3MZG9e7WjWgjSYwXqIYJ7kF&gir=yes&clen=14579306&dur=232.280&lmt=1575013127368986&mt=1623224679&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5532432&n=2OmufHbbD42F0ip_&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKzb7u9HMgJQn-5IRSBzK79X2lx3sTfFr0cg05FxznfvAiBAsr_W_uqx82qPZiKQIU0Jv-hhxyTSlYETNIMaLa3fNw%3D%3D&sig=AOq0QJ8wRAIhALlk9_M0Xwq1wyqwN02qjfC0X8iHY_bZsqxB4MqaBo47Ah8XH4hwkOBWExrcr63vLq8sXTg2iVkSQk-Wta1tf-jO'
[download] Destination: Darude - Sandstorm-y6120QOlsfU.f134.mp4
[download] 100% of 13.90MiB in 00:00
[debug] Invoking downloader on u'https://r3---sn-q0c7rn76.googlevideo.com/videoplayback?expire=1623246515&ei=U3LAYJWOG8H6xN8P0qSEiA8&ip=2a02%3A8084%3A983e%3Ad380%3Ab8fe%3Abcee%3A463%3A39d4&id=o-AHgTNsYSeiK3lUrXwSBQssb9HMsywbg3oy7lO-nEMVNB&itag=140&source=youtube&requiressl=yes&mh=Yy&mm=31%2C26&mn=sn-q0c7rn76%2Csn-aigzrne7&ms=au%2Conr&mv=m&mvi=3&pl=30&initcwndbps=1782500&vprv=1&mime=audio%2Fmp4&ns=Q3MZG9e7WjWgjSYwXqIYJ7kF&gir=yes&clen=3760893&dur=232.338&lmt=1575013035271523&mt=1623224679&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5531432&n=2OmufHbbD42F0ip_&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgFkIBJNB9dHbg1SZFc6KNjklqKxzNnEU0IXFeoMuS8CICIQDuD_Pp1Czbi6jword1um2lU-YTM8WIYcBp9Nc-nESFKw%3D%3D&sig=AOq0QJ8wRQIgTO7TzRoImDtGx7eLIJqRhInF_tI9hmlUROfLOIXy19YCIQC_GbwVeu-waLVZ9PBs_a6HERbG42Ts4Ocq2veeAULrHQ=='
[download] Destination: Darude - Sandstorm-y6120QOlsfU.f140.m4a
[download] 100% of 3.59MiB in 00:00
[ffmpeg] Merging formats into "Darude - Sandstorm-y6120QOlsfU.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Darude - Sandstorm-y6120QOlsfU.f134.mp4' -i 'file:Darude - Sandstorm-y6120QOlsfU.f140.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Darude - Sandstorm-y6120QOlsfU.temp.mp4'
Deleting original file Darude - Sandstorm-y6120QOlsfU.f134.mp4 (pass -k to keep)
Deleting original file Darude - Sandstorm-y6120QOlsfU.f140.m4a (pass -k to keep)

**Comment by rautamiekka** [comment]
It's seriously weird that packagers aren't using automatic fetching of source code to auto-compile.

**Comment by dmzoneill** [comment]
@rautamiekka Rogério Brito has passed away due to corona virus.  I talked with his wife via email. i will look into picking up the package

**Comment by Abdullah-Bhutta** [comment]
> > > it says "403 - forbidden" for me. are you sure you're supposed to have access to it? The app might not be able to see any formats because it can't access the website itself
> > 
> > 
> > I think its Geotagged to my country
> 
> if it is geotagged you might need to specify the [--geo-bypass](https://github.com/ytdl-org/youtube-dl#geo-restriction) argument. click the link for help. it leads to [README.md](https://github.com/ytdl-org/youtube-dl/blob/master/README.md)

 @didotb  Its doesnot show 404 error, as you are expeirenceinng, because its geotagged to my country. So, rather you have to use that comand and check whether it can be downloaded or not.

On my side it first processes Manifest, and then say No supported formats are found. and the file is .ism (Azure Service)

why python -m youtube_dl -F 'https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/manifest(format=mpd-time-csf)' is not working but python -m youtube_dl -F "https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/manifest(format=mpd-time-csf)" is working just fine??

**Comment by didotb** [comment]
> > > > it says "403 - forbidden" for me. are you sure you're supposed to have access to it? The app might not be able to see any formats because it can't access the website itself
> > > 
> > > 
> > > I think its Geotagged to my country
> > 
> > 
> > if it is geotagged you might need to specify the [--geo-bypass](https://github.com/ytdl-org/youtube-dl#geo-restriction) argument. click the link for help. it leads to [README.md](https://github.com/ytdl-org/youtube-dl/blob/master/README.md)
> 
> @didotb Its doesn't show 403 error on my side; as you are experiencing, because its geotagged to my country. So, rather you have to use that command and check whether it can be downloaded or not.
> 
> On my side it first processes Manifest, and then say No supported formats are found. and the file is .ism (Azure Service)
> 
> why python -m youtube_dl -F 'https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/manifest(format=mpd-time-csf)' is not working but python -m youtube_dl -F "https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/manifest(format=mpd-time-csf)" is working just fine??

What is your country code? so I could try it on my end

**Comment by Abdullah-Bhutta** [comment]
> What is your country code? so I could try it on my end

If you are talking about the country dialing code, then that's +92 other wise the code is 92

**Comment by 89z** [comment]
Issue should be closed, URL is dead
