### ISSUE TITLE
Viki giving HTTP Error 422 for few videos in between

### ISSUE THREAD

**Issue by Anutrix** [ytdl-org/youtube-dl#29243]
```
.....
[download] Attention, Love! - Episode 3-1120166v.mp4 has already been downloaded and merged
[download] Downloading video 4 of 17
[viki] 1120167v: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 422: Unprocessable Entity (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
I get the above error in the middle with the command `youtube-dl --sub-lang en --sub-format vtt --write-sub https://www.viki.com/tv/35551c-attention-love`.
Adding `-i` to above(to ignore errors) downloads that video number without issues.

Only that video(Episode 4) had the issue so far but considering that the download worked for it with by just ignoring errors could mean there is some thing that can be fixed.

Version: (Installed from git release few hours ago)
```
:~$ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-Kali-kali-rolling-kali-rolling
[debug] exe versions: ffmpeg 4.3.1-5, ffprobe 4.3.1-5, rtmpdump 2.4
[debug] Proxy map: {}
```

**Comment by zackmark29** [comment]
Viki contents already DRM Protected. :)

**Comment by MarcelCoding** [comment]
Im my case also the first video:
``````

**Comment by BenTalagan** [comment]
Same for me on macos. After investigating, the json content of the 422 error is the following : 

```
{"error":{"status":422,"body":{"vcode":6422,"error":"Unprocessable entity","details":"invalid app ver"}}}
```

Looks like things have changed on viki's server side and this part is impacted : 

https://github.com/ytdl-org/youtube-dl/blob/c2350cac243ba1ec1586fe85b0d62d1b700047a2/youtube_dl/extractor/viki.py#L247-L252

Replacing the version by '4.0.74' (latest observed on the website) fixes the 422 error, but the download fails afterwards when retrieving the streams json with : 

```
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>)

Detail : 
{"error":"invalid signature","vcode":8003}
````

I'm stuck on this and we probably need help from someone who knows better the viki extractor :)

**Comment by MarcelCoding** [comment]
Oh yes, Viki recently updated they app.

**Comment by zackmark29** [comment]
> Same for me on macos (actually I cannot download any video anymore). After investigating, the json content of the 422 error is the following :
> 
> ```
> {"error":{"status":422,"body":{"vcode":6422,"error":"Unprocessable entity","details":"invalid app ver"}}}
> ```
> 
> Looks like things have changed on viki's server side and this part is impacted :
> 
> https://github.com/ytdl-org/youtube-dl/blob/c2350cac243ba1ec1586fe85b0d62d1b700047a2/youtube_dl/extractor/viki.py#L247-L252
> 
> Replacing the version by '4.0.74' (latest observed on the website) fixes the 422 error, but the download fails afterwards when retrieving the streams json with :
> 
> ```
> ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>)
> 
> Detail : 
> {"error":"invalid signature","vcode":8003}
> ```
> 
> I'm stuck on this and we probably need help from someone who knows better the viki extractor :)

They will not gonna update this because viki contents already DRM protected.
Or maybe on some selected countries not yet.

**Comment by zackmark29** [comment]
> 1120166v

So I just found something. non drm content still exist.

Try to download this:
VIDEO: 
https://m-content6-viki.s.llnwi.net/1120166v/dash/1120166v_dash_high_1080p_fde889_1710162321_track1_dashinit.mp4

AUDIO:
https://m-content6-viki.s.llnwi.net/1120166v_dash_high_1080p_fde889_1710162321_track2_dashinit.mp4

just need to mux it.

**Comment by MarcelCoding** [comment]
@zackmark29 Did you use a account to gather the url, because this video is in full hd (without authentication)?

**Comment by zackmark29** [comment]
> @zackmark29 Did you use a account to gather the url, because this video is in full hd (without authentication)?

Yes. It's required token when singing the params

**Comment by zackmark29** [comment]
fix is in progress
https://github.com/yt-dlp/yt-dlp/pull/473

**Comment by dirkf** [comment]
In PR #30596, 'https://www.viki.com/tv/35551c-attention-love' has 19 videos that all give 403 on the mpd except 12-15. Same with yt-dlp.
