### ISSUE TITLE
Bitchute python issue again (same as 23 days ago)

### ISSUE THREAD

**Issue by BurgInThailand** [ytdl-org/youtube-dl#29246]
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
bitchute download problem. 403. youtube.com no problems.

Same as 23 days ago (Bitchute reporting 403 errors #29063). Python issue?

/tmp $ sudo youtube-dl -U
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
youtube-dl is up-to-date (2021.06.06)
/tmp $ youtube-dl --verbose https://www.bitchute.com/video/AknrMjqQtwG7
[debug] System config: []
[debug] User config: [u'-f', u'mp4', u'-i', u'-w', u'-c', u'--restrict-filenames', u'-o', u'%(upload_date)s.%(title)s_%(id)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.bitchute.com/video/AknrMjqQtwG7']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Linux-5.8.0-55-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[BitChute] AknrMjqQtwG7: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

/tmp $

**Comment by rautamiekka** [comment]
For the future, put the log in the correct section, not into the description.

Works fine for me in both instances on an NTFS partition on Window$ 10 x64, with Python 2.7.18 like you:

With my command line:
```
# C:\ProgramData\Anaconda3\envs\python2.7\Scripts\youtube-dl.exe --ignore-config --verbose --verbose --ignore-errors --no-mark-watched --format "bestvideo+bestaudio/best" --audio-format best --audio-quality 0 --ffmpeg-location "C:\Users\Public\Downloads\ffmpeg\bin" --no-playlist --output "%(uploader_id)s/%(title)s %(resolution)s #%(id)s#.%(ext)s" --console-title --no-mtime --retries infinite --continue --no-overwrites --fragment-retries infinite "https://www.bitchute.com/video/AknrMjqQtwG7"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-config', u'--verbose', u'--verbose', u'--ignore-errors', u'--no-mark-watched', u'--format', u'bestvideo+bestaudio/best', u'--audio-format', u'best', u'--audio-quality', u'0', u'--ffmpeg-location', u'C:\\Users\\Public\\Downloads\\ffmpeg\\bin', u'--no-playlist', u'--output', u'%(uploader_id)s/%(title)s %(resolution)s #%(id)s#.%(ext)s', u'--console-title', u'--no-mtime', u'--retries', u'infinite', u'--continue', u'--no-overwrites', u'--fragment-retries', u'infinite', u'https://www.bitchute.com/video/AknrMjqQtwG7']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-04-14-git-c5ca18fd1b-full_build-www.gyan.dev, ffprobe 2021-04-14-git-c5ca18fd1b-full_build-www.gyan.dev
[debug] Proxy map: {}
[BitChute] AknrMjqQtwG7: Downloading webpage
[BitChute] AknrMjqQtwG7: Checking video URL
[debug] Invoking downloader on u'https://zbbb278hfll091.bitchute.com/1uDxpDogKMs9/AknrMjqQtwG7.mp4'
[download] Destination: NA\JUNE Trade Genius - With Nervous comes Volatility...which leads to PROFIT NA #AknrMjqQtwG7#.mp4
[download] 100% of 24.62MiB in 00:57
```
Yours:
```
# C:\ProgramData\Anaconda3\envs\python2.7\Scripts\youtube-dl.exe --verbose -f mp4 -i -w -c --restrict-filenames -o "%(upload_date)s.%(title)s_%(id)s.%(ext)s" "https://www.bitchute.com/video/AknrMjqQtwG7"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-f', u'mp4', u'-i', u'-w', u'-c', u'--restrict-filenames', u'-o', u'%(upload_date)s.%(title)s_%(id)s.%(ext)s', u'https://www.bitchute.com/video/AknrMjqQtwG7']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[BitChute] AknrMjqQtwG7: Downloading webpage
[BitChute] AknrMjqQtwG7: Checking video URL
[debug] Invoking downloader on u'https://zbbb278hfll091.bitchute.com/1uDxpDogKMs9/AknrMjqQtwG7.mp4'
[download] Destination: 20210609.JUNE_Trade_Genius_-_With_Nervous_comes_Volatility...which_leads_to_PROFIT_AknrMjqQtwG7.mp4
[download]   3.8% of 24.62MiB at 449.71KiB/s ETA 00:53
ERROR: Interrupted by user
```

I think this line's the problem:
```
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
```
which is
```
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
```
for me. Which is weird, considering you're on Ubuntu.

**Comment by kikuyan** [comment]
JFYI, it didn't work hours ago with python 2.7 (curl didn't work either without options), worked with python 3.9.
Now it works again with python 2.7 (and curl).

**Comment by BurgInThailand** [comment]
yes, working here now (24h later) as well. 

[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Linux-5.8.0-55-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4

So far, so good.
