### ISSUE TITLE
how to get channel name with channel url

### ISSUE THREAD

**Issue by whoizit** [ytdl-org/youtube-dl#29250]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
I need only print in console channel name by channel url
For example this url https://www.youtube.com/channel/UC5UwzkI8NlcDHgrRkVBkR5Q
It seems to be trying to download all the playlists. I tried to get JSON but it starts printing a lot of JSON without stopping

WRITE QUESTION HERE

**Comment by kikuyan** [comment]
Try `--flat-playlist -J | jq .title`, and drop ' - Home' part.

**Comment by whoizit** [comment]
It works well
`youtube-dl $1 --flat-playlist -J | jq .title | sed 's/ - Home//'`
thank you
