### ISSUE TITLE
Funimation extractor error

### ISSUE THREAD

**Issue by nmills3** [ytdl-org/youtube-dl#29251]
## Checklist

- [x] I'm reporting a broken site support
- [ x I've verified that I'm running youtube-dl version **2021.06.06**
- [ x I've checked that all provided URLs are alive and playable in a browser
- [ x I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

C:\Users\nicho\AppData\Roaming\nm-yt-downloader>youtube-dl.exe --cookies funimation.com_cookies.txt https://www.funimation.com/en/shows/mushoku-tensei-jobless-reincarnation/jobless-reincarnation/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'funimation.com_cookies.txt', 'https://www.funimation.com/en/shows/mushoku-tensei-jobless-reincarnation/jobless-reincarnation/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[Funimation] jobless-reincarnation: Downloading webpage
[Funimation] 1376136: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('items',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\funimation.py", line 121, in _real_extract
KeyError: 'items'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\funimation.py", line 121, in _real_extract
KeyError: 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 547, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('items',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Funimation site support is still not working

**Comment by october262** [comment]
does the video play in the browser ??
did you try using without cookies ?

**Comment by Vangelis66** [comment]
The service is reserved to **US** IP addresses...
**Age-gated** videos, like the one referenced by OP, 

https://www.funimation.com/en/shows/mushoku-tensei-jobless-reincarnation/jobless-reincarnation/

require a **logi**n (i.e. account) - I don't have one, so couldn't check whether that video played in my browser... 

When I chose a **TV-14** show, 

https://www.funimation.com/en/shows/hacklegend-of-the-twilight/the-legendary-hero/

that **doesn't require a login**, I URL-sniffed a HLSe master playlist in my browser, 
```
https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/1329680/English/1329680_English_88836536-5772-e711-8175-020165574d09.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8xMzI5NjgwL0VuZ2xpc2gvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYyMzI5NzAzOX19fV19&Signature=vnSh3KpOHXKRuDPrGmOxxpb39A9FOmGz2nkf00rR~-ywQdqSPG9K3YSND-xUFoyw25ZGod3Wky9rGQYFYtGhv5RiiKAQ-B9aHIC1nTlkH3-mmjmOlmloev3jkgCN173ttWSIhDAzeP8no67ZRnnjgf13mWjx1nRiOABIY8W~XYyKA4UxCPgrCkFxv5vc8g0ksp4168u995wqwC3uK3xpTfoxVlla9q-g5U-dX35Sny7sy87HRztUL0a7ywlUlvOIn8DppbX-0F1vkrgPuFUJfvq7XnnAnHjImgj9NnR0EMBdMvciapKuiq9r6bVsgdN7~a2g5ElvYh7OmX7t5cFSQQ__&Key-Pair-Id=APKAIHNXECY27H4O6NIA&rt=1425460
```
and, apparently, `youtube-dl` has no issues with these types of shows: 
```
youtube-dl -F "https://www.funimation.com/en/shows/hacklegend-of-the-twilight/the-legendary-hero/" => 

[Funimation] the-legendary-hero: Downloading webpage
[Funimation] 42647: Downloading JSON metadata
[Funimation] 42647: Downloading m3u8 information
[info] Available formats for 42647:
format code  extension  resolution note
mp4          mp4        unknown
hls-549      mp4        416x234     549k , avc1.66.30, mp4a.40.2
hls-788      mp4        480x270     788k , avc1.66.30, mp4a.40.2
hls-1025     mp4        512x288    1025k , avc1.66.30, mp4a.40.2
hls-1765     mp4        512x288    1765k , avc1.42001f, mp4a.40.2
hls-2460     mp4        640x360    2460k , avc1.4d001f, mp4a.40.2
hls-3125     mp4        640x360    3125k , avc1.4d001f, mp4a.40.2
hls-4522     mp4        640x360    4522k , avc1.4d001f, mp4a.40.2
hls-6203     mp4        848x480    6203k , avc1.4d001f, mp4a.40.2
hls-7961     mp4        848x480    7961k , avc1.4d001f, mp4a.40.2
hls-9699     mp4        848x480    9699k , avc1.4d001f, mp4a.40.2 (best)
```

**Comment by nmills3** [comment]
Yes the video played in the browser and yes i did try without cookies and it still did not work

**Comment by nmills3** [comment]
duplicate of what?

**Comment by pukkandan** [comment]
https://github.com/ytdl-org/youtube-dl/issues/21787
