### ISSUE TITLE
Python script and equivalent command do not run the same

### ISSUE THREAD

**Issue by awa5114** [ytdl-org/youtube-dl#29255]
I would like to use youtubedl to download the audio from a youtube video into an mp3 file. I came up with the following command to do so:

`youtube-dl -x --audio-format mp3 https://www.youtube.com/watch?v=SF8DGbfOFig&ab_channel=derang`

 When I run the above command through my command line, it seems that I successfully manage to download the file in mp3 format:

```
[youtube] SF8DGbfOFig: Downloading webpage
[download] Destination: Total Science & S.P.Y - Piano Funk (Ft. Riya & DāM FunK) [320k]-SF8DGbfOFig.webm
[download] 100% of 5.57MiB in 00:03
[ffmpeg] Destination: Total Science & S.P.Y - Piano Funk (Ft. Riya & DāM FunK) [320k]-SF8DGbfOFig.mp3
Deleting original file Total Science & S.P.Y - Piano Funk (Ft. Riya & DāM FunK) [320k]-SF8DGbfOFig.webm (pass -k to keep)
```

I then tried to convert the above command to an equivalent python script as follows:

```
import youtube_dl
links = ["https://www.youtube.com/watch?v=SF8DGbfOFig&ab_channel=derang"]
ydl_args = {
        'audioformat': 'mp3',
        'outtmpl': '%(title)s.%(ext)s',
        'extractaudio': True
    }
with youtube_dl.YoutubeDL(ydl_args) as ydl:
    results = ydl.download(links)
```

However, this does not succeed in generating an mp3 file of the audio. These are the logs I am getting:

```
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: Total Science & S.P.Y - Piano Funk (Ft. Riya & DāM FunK) [320k].f135.mp4
[download] 100% of 4.42MiB in 00:02
[download] Destination: Total Science & S.P.Y - Piano Funk (Ft. Riya & DāM FunK) [320k].f251.webm
[download] 100% of 5.57MiB in 00:03
[ffmpeg] Merging formats into "Total Science & S.P.Y - Piano Funk (Ft. Riya & DāM FunK) [320k].mkv"
Deleting original file Total Science & S.P.Y - Piano Funk (Ft. Riya & DāM FunK) [320k].f135.mp4 (pass -k to keep)
Deleting original file Total Science & S.P.Y - Piano Funk (Ft. Riya & DāM FunK) [320k].f251.webm (pass -k to keep)
```

What am I doing wrong here. Aren't my command and python script equivalent?

Thanks

**Comment by dstftw** [comment]
Read FAQ on embedding.

**Comment by awa5114** [comment]
@dstftw I just had a look on the FAQ page under `EMBEDDING YOUTUBE-DL` . It only provides a very basic example on how to embed the command line utility into a python script. It also describes how python's built in `logging` module to log output.

This does not answer my question, which pertains more specifically to use of parameters. Why is it that when I use identical parameters, the results are different?

I believe this issue should be reopened, as I do not have a satisfactory response to what I think is a legitimate question.

**Comment by kikuyan** [comment]
After many tries and fails,
```
ydl_args = {
        'outtmpl': '%(title)s.%(ext)s',
        'extractaudio': True,
	'format': 'bestaudio',
        'postprocessors': [
            {
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
            }
        ],
    }
```
