### ISSUE TITLE
how do I tell if a format is available

### ISSUE THREAD

**Issue by tim-moody** [ytdl-org/youtube-dl#29252]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

If I retrieve info on a youtube video id using info = ydl.extract_info('http://www.youtube.com/watch?v=' + video_id, download=False), that info can include audio formats 249, 250, 251. But if I issue youtube-dl -f 249 it can yield an error ERROR: requested format not available. How can I tell that a format reported in info is not available? youtube-dl -f 249/250/251 finds the one that is available, so there must be something in the info data structure that shows that a reported format is not actually available.

**Comment by october262** [comment]
use youtube-dl -F https://www.youtube.com/watch?v=l1hthEZugZo
to see all available formats the video has.
