### ISSUE TITLE
Download from YouTube is throttled to about 1.16 MByte/s

### ISSUE THREAD

**Issue by KyodaiKen** [ytdl-org/youtube-dl#29263]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\Kyo>youtube-dl -v -f 313 https://www.youtube.com/watch?v=IhhNvuwAunw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '313', 'https://www.youtube.com/watch?v=IhhNvuwAunw']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] IhhNvuwAunw: Downloading webpage
[debug] Invoking downloader on 'https://r5---sn-4g5ednsz.googlevideo.com/videoplayback?expire=1623384872&ei=yI7CYODfKtbogAfblZ7QCQ&ip=2a02%3A908%3A89c%3Aa80%3A1c08%3A123d%3A6ac6%3Af3c9&id=o-AA99qv3OY2uTZ7THI0Q0RLRku2uidNB5aiAhzid055mO&itag=313&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&source=youtube&requiressl=yes&mh=BY&mm=31%2C29&mn=sn-4g5ednsz%2Csn-4g5e6nss&ms=au%2Crdu&mv=m&mvi=5&pl=45&initcwndbps=1650000&vprv=1&mime=video%2Fwebm&ns=_uuBZ0ktAdGbRIEUhQ4qeaYF&gir=yes&clen=905912436&dur=880.245&lmt=1623354179488479&mt=1623362924&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=6416222&n=4NAmADn3DWn4lExL&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgEIiM0BQ6gohfp-cxvh7fPq9sIIui3C3XxqFUEtcFmF8CIQCj07QSfkqCgXfBFYB6CHF92FdtI54uUucQzhMN0ozEGw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANO0Rq59EVJwaMgqWYjzwN8BJkpsZV0ib-lI3qck-VHnAiEAvai0_AmzgceUr1_8eoQNWp_JU7CFJ85iWuACMhthWp0%3D'
[download] Destination: Even if you COULD buy an RTX 3070 Ti, I wouldn't.-IhhNvuwAunw.webm
[download]   0.9% of 863.95MiB at  1.14MiB/s ETA 12:32
```

## Description

In Germany, NRW using provider Unitymedia (Liberty Global) / Vodafone, I could not watch YT-Videos in 4K in Firefox. Since the latest Firefox update, this issue seems to have been resolved.

What does it have to do with youtube-dl? Well, Firefox was throttled to 9500 kbps and youtube-dl is as well. Firefox is fixed, but youtube-dl is still slow as you can see above.

My speedtest is the maximum download speed of Gitabit Ethernet (940 MBit/s).

Here are the stats for nerds from YouTube from Firefox:

![firefox_DHtbqfnFpP](https://user-images.githubusercontent.com/32415256/121604061-2873cb00-ca4a-11eb-8aef-47b03373ed8c.png)

I've stated the state I am living in in case this is a CDN problem that needs to be circumvented for my special case. I am aware that this might not be reproducible in other countries or in other States or ISPs of Germany. But since it got fixed by Mozilla, there might be something to look out for when requesting the video.

Thank you!

**Comment by dstftw** [comment]
youtube-dl does not impose any throttling or limitations on its own.
For Firefox it technically could not "got fixed" by Mozilla since video requesting is handled by Youtube webplayer not Firefox.
Browser may use different machine's network interface and/or IP version to connect to youtube that may result in different ISP limitations. If this is the case you must manually specify which version of IP to use `-4`/`-6` or specify exact IP with `--source-address` if you have multiple network interfaces.

**Comment by KyodaiKen** [comment]
Okay this is really weird. When I use IPv4 it works fast! Will call my ISP tomorrow to investigate what is going on with my IPv6 connection. Thanks for the quick help!
