### ISSUE TITLE
HTTP Error 400: Bad Request - on RTP Play (https://www.rtp.pt/play/)

### ISSUE THREAD

**Issue by mmgithubs** [ytdl-org/youtube-dl#29271]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', 'Pedro e Inês-2021-06-04.mp4', 'https://streaming-ondemand.rtp.pt/nas2.share/h264/512x384/p7347/p7347_1_20210604161007e000t4235d/master.mpd']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.5 (CPython) - Linux-5.8.0-55-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[generic] master: Requesting header
WARNING: Could not send HEAD request to https://streaming-ondemand.rtp.pt/nas2.share/h264/512x384/p7347/p7347_1_20210604161007e000t4235d/master.mpd: HTTP Error 400: Bad Request
[generic] master: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

```

## Description

Since a couple of weeks ago I can't download videos from RTP Play website.
I'm using the latest Firefox and a plugin which gives me the line to insert on the terminal to download the video with youtube-dl.
For example, for this video on https://www.rtp.pt/play/p7347/e549150/pedro-e-ines when I click on the plugin it gives me this:

Python youtube-dl -o "Pedro e Inês-2021-06-04.mp4" "https://streaming-ondemand.rtp.pt/nas2.share/h264/512x384/p7347/p7347_1_20210604161007e000t4235d/master.mpd"

then I just remove 'Python' from that string and execute it on the terminal. This was working a couple of weeks ago, like I said.
My system is:

lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

Can you see the problem please?
Thank you

**Comment by kikuyan** [comment]
For mpd url, try with `--referer https://www.rtp.pt/`. Similar to #29068.

**Comment by mmgithubs** [comment]
Yes it works!
Thank you!
