### ISSUE TITLE
"Unknown error: -536870212" When Attempting to Download from YouTube

### ISSUE THREAD

**Issue by walterhanley** [ytdl-org/youtube-dl#29273]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://youtu.be/Ynq32y2k2bU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.5 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Ynq32y2k2bU: Downloading webpage
WARNING: Unable to download webpage: <urlopen error [Errno -536870212] Unknown error: -536870212>
[youtube] Ynq32y2k2bU: Downloading API JSON
ERROR: Unable to download API page: <urlopen error [Errno -536870212] Unknown error: -536870212> (caused by URLError(OSError(-536870212, 'Unknown error: -536870212')))
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/utils.py", line 2735, in https_open
    return self.do_open(functools.partial(
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
```

## Description

Ran into this video when trying to download a video from Youtube. Reliably reproducible with arbitrary URL (tried with https://www.youtube.com/watch?v=kSv6LHkH0ao and https://youtu.be/Ynq32y2k2bU), and appears to present on both macOS and Windows. Unsure if it's a software issue or something on my end, but happy to help troubleshoot as needed. youtube-dl and dependencies are installed using Homebrew. Please don't hesitate to let me know if you have any other questions, and I appreciate your time.

**Comment by rautamiekka** [comment]
Works perfectly fine on my Win10 with Python 3.8.10 and 3.9.1.

How did you install ytdl on Window$ ?

**Comment by kikuyan** [comment]
It looks like an IOKit error to me. [QA1075](https://developer.apple.com/library/archive/qa/qa1075/_index.html)
`-536870212` is `0xe00002bc` in hex and `0x2bc` is the error code, but unfortunately it doesn't give any hints: `#define kIOReturnError iokit_common_err(0x2bc) // general error`

I guess there is a network problem on your side.

**Comment by nershman** [comment]
If anyone comes across this issue, it seems there are a handful of errors associated with this code that are somewhat unrelated (unless you have a deep technical knowledge of macOS maybe). 

In the context of youtube-dl or any python script which is spitting a URLError, don't forget to check your firewall (e.g. LuLu, Little Snitch, or another program like those). In my case this was the solution I needed. Quite silly.
