### ISSUE TITLE
[Youtube] First ~30m of video is left out

### ISSUE THREAD

**Issue by horusra** [ytdl-org/youtube-dl#29288]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
>youtube-dl -v https://youtu.be/QdV_e-U7_pQ
[debug] System config: []
[debug] User config: ['--no-mtime', '--add-metadata', '--merge-output-format', 'mkv', '--output', 'U:\\Youtube\\%(title)s.%(ext)s', '--force-ipv4']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtu.be/QdV_e-U7_pQ']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.4-essentials_build-www.gyan.dev, ffprobe git-2020-04-13-59e3a9a
[debug] Proxy map: {}
[youtube] QdV_e-U7_pQ: Downloading webpage
[youtube] QdV_e-U7_pQ: Downloading m3u8 information
[youtube] QdV_e-U7_pQ: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1623612366/ei/bgfGYIDuGZqh1gLT44TQAw/ip/31.161.194.91/id/QdV_e-U7_pQ.1/source/yt_live_broadcast/requiressl/yes/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/force_finished/1/vprv/1/keepalive/yes/fexp/24001373%2C24007246/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cforce_finished%2Cvprv%2Citag%2Cplaylist_type/sig/AOq0QJ8wRQIgLiIc92qKmrQUUUpsCYS28VwoZLVekvPNaBls9F6deDoCIQCnG4KKzsmWuA12xAf0WwZgerFnpIdM5BSDPNoYqy20ww%3D%3D'
[dashsegments] Total fragments: 7200
[download] Destination: U:\Youtube\Lumen _ Inside Unreal.f299.mp4
[download]   1.0% of ~453.60MiB at  2.09MiB/s ETA 15:27

```

## Description

https://youtu.be/QdV_e-U7_pQ
Opening this link with yt-dl and mpv, or just downloading it with yt-dl, starts the video at around 34 minutes for some reason.
Downloading the "entire" video, starts the video still at 34m, and the video is then conveniently exactly 2 hours long.
As if it's being trimmed from the end to fit 2 hours

![2050](https://user-images.githubusercontent.com/17074394/121809146-f33ec700-cc5b-11eb-9d26-6410c79f3bec.jpg)

Is Youtube maybe using two different sources for some reason, and the first one is ignored by ytdl?

**Comment by horusra** [comment]
Now hours later, I tried again using the same exact config/option and the video is now fully downloaded, but for some reason only 360p....

**Comment by horusra** [comment]
Now even the video on youtube is 360p...
this seems to be a youtube issue rather than yt-dl so I'll close it

**Comment by Igetin** [comment]
You were experiencing the problem described here: https://github.com/ytdl-org/youtube-dl/issues/26330. The problem occurs on all recently finished livestreams that were longer than 2 hours.
