### ISSUE TITLE
Is there possible to download a segment of whole video and sound? For example a video of 10 minutes, I only download from 1:29s to 3:34s. It's good for people with a poor internet connection and speed.

### ISSUE THREAD

**Issue by Lioncat-M** [ytdl-org/youtube-dl#29295]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

**Comment by AlphaCentauri** [comment]
The easiest way I know if to do this is using a combination of youtube-dl and ffmpeg directly. See [this](https://unix.stackexchange.com/questions/230481/how-to-download-portion-of-video-with-youtube-dl-command) stackexchange answer. Adjust commands as necessary if you don't use a *nix environment.

**Comment by HighCommander4** [comment]
Dupe of #622?

**Comment by Lioncat-M** [comment]
@HighCommander4  Thanks for the link, it's very helpful to solve the problem
