### ISSUE TITLE
channel uploaded videos url print json

### ISSUE THREAD

**Issue by MVDW-Java** [ytdl-org/youtube-dl#29307]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello,

Is it possible to make youtube-dl print a json with only all the channel uploaded video urls(no playlist videos or other data)?

Thank you in advance.

**Comment by dstftw** [comment]
No. Parse JSON or use `jq` or similar.

**Comment by wajhk** [comment]
- [ ] طيييط ولي🪡⚔️

**Comment by MVDW-Java** [comment]
Sorry, my English is not very good.

I know I need to parse the data but I was wondering on how do I get the data of all the channels uploaded videos.
already tried using "youtube-dl -j https://www.youtube.com/channel/UCO0roQ_5hELHGUQk-dBRscQ/videos" but this includes also the playlist and downloads a lot of data.

I hope this will clarify it a bit more what I meant
Thank you in advance.

**Comment by rautamiekka** [comment]
You need to do it like this:
```
youtube-dl --verbose --skip-download -j --format "bestvideo+bestaudio/best" "https://www.youtube.com/channel/UCO0roQ_5hELHGUQk-dBRscQ/videos" > json.json
```
^ Writes (overwrites) a file called `json.json` to the current folder, and `--format "bestvideo+bestaudio/best"` is used to prevent the
```
[debug] Default format spec: bestvideo+bestaudio/best
```
spam for every vid.
