### ISSUE TITLE
YouTube Age Restriction issue reappeared in the latest version (2021.06.06)

### ISSUE THREAD

**Issue by Animan8000** [ytdl-org/youtube-dl#29317]
`C:\Users\Username\Videos\new>youtube-dl https://www.youtube.com/watch?v=812LFaEZlkg
[youtube] 812LFaEZlkg: Downloading webpage
[youtube] 812LFaEZlkg: Refetching age-gated info webpage
WARNING: unable to download video info webpage: HTTP Error 404: Not Found
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.`

This wasn't an issue two days ago with the latest version and used to work fine before (like two days ago it could handle age restricted videos properly). I suppose maybe YouTube did again a change behind the scenes and it broke it again?

**Comment by colethedj** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/29086

**Comment by jimmy-1000** [comment]
I confirm this. The problem is back.

**Comment by IoanPaleru** [comment]
Youtube-dl definitely doesn't download age-restricted videos from youtube like this one "https://www.youtube.com/watch?v=xcRUPMf6scs" (NSFW) anymore. Is there any way to get youtube-dl to download those videos properly, especially for people who don't know how to do advanced computer programming and simply want a program like youtube-dl they can just use that works properly? Thanks.

**Comment by jimmy-1000** [comment]
> 
> 
> Youtube-dl definitely doesn't download age-restricted videos from youtube like this one "https://www.youtube.com/watch?v=xcRUPMf6scs" (NSFW) anymore. Is there any way to get youtube-dl to download those videos properly, especially for people who don't know how to do advanced computer programming and simply want a program like youtube-dl they can just use that works properly? Thanks.

No only youtube-dl, I have other programs and I get in all _"confirm your age"_. 
@dstftw You closed an issue that is still unsolved.
