### ISSUE TITLE
Can't login. Error 400

### ISSUE THREAD

**Issue by Koteeque** [ytdl-org/youtube-dl#29315]
This is .bat file for arhive videos from channels:

`"C:\Youtube-dl\youtube-dl.exe" --skip-download --username example@gmail.com --password example --cookies "D:\Desktop\Apps\Youtube-dl\youtube.com_cookies.txt" --ignore-errors --no-continue --no-overwrites --download-archive "D:\Desktop\Apps\Youtube-dl\archive.txt" --output "D:\Downloads\Youtube\%(title)s.%(ext)s" --format "bestvideo[height<=1080]+bestaudio/[height<=1080]" --batch-file "D:\Desktop\Apps\Youtube-dl\Channels.txt" > D:\Desktop\Apps\Youtube-dl\log.txt 2>&1`

But i can't login.
This is first 3 lines in log.txt:
`[youtube:tab] Downloading login page`
`[youtube:tab] Looking up account info`
`WARNING: Unable to look up account info: HTTP Error 400: Bad Request`
But all is work, new videos are downloading and logged in archive.txt

What's wrong?

**Comment by dstftw** [comment]
Use cookies.
