### ISSUE TITLE
Pdisk

### ISSUE THREAD

**Issue by FayasNoushad** [ytdl-org/youtube-dl#29313]
Please add the pdisk.net site support

**Comment by SuperSonicHub1** [comment]
This is a poorly formatted site support request. Close this one and create a new one using this template: https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=site-support-request&template=2_site_support_request.md&title=

**Comment by FayasNoushad** [comment]
I am a Telegram Bot Developer, My channel subscribers asking a pdisk telegram bot.
