### ISSUE TITLE
question: android

### ISSUE THREAD

**Issue by arcade-legend** [ytdl-org/youtube-dl#29329]
Is it possible to run youtube-dl on android?
If yes, what I need to install and how to run it.
I'm a beginner, also for python.

thx

**Comment by qespr** [comment]
You can use [Termux](https://f-droid.org/en/packages/com.termux/) and then download and use youtube-dl from there as you would from any other terminal

**Comment by SuperSonicHub1** [comment]
Adding on, [dvd](https://github.com/yausername/dvd) is another excellent way to use youtube-dl on the Droid.
