### ISSUE TITLE
[youtube] Age gated video fail with 404 error

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#29333]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v -F https://www.youtube.com/watch?v=XgnwCQzjau8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.youtube.com/watch?v=XgnwCQzjau8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.16 (CPython) - Darwin-20.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] XgnwCQzjau8: Downloading webpage
[youtube] XgnwCQzjau8: Refetching age-gated info webpage
WARNING: unable to download video info webpage: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 475, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2069, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1503, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2644, in compat_parse_qs
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2614, in _parse_qsl
AttributeError: 'bool' object has no attribute 'split'
```

## Description

Test link:
https://www.youtube.com/watch?v=XgnwCQzjau8

maybe adding these params:
https://stackoverflow.com/questions/67615278/get-video-info-youtube-endpoint-suddenly-returning-404-not-found/67629882#67629882
here: 
https://github.com/ytdl-org/youtube-dl/commit/24297a42efc52862cb9510d32b28efd7faf49af6
helps or at least gives a hint.

**Comment by someziggyman** [comment]
Ok ,so I added params below:
                        'html5': '1',
                        'c': 'TVHTML5',
                        'cver': '6.20180913',
   
Here: https://github.com/ytdl-org/youtube-dl/commit/24297a42efc52862cb9510d32b28efd7faf49af6
and the issue seems to be gone... Not sire how solid of a solution that is..

**Comment by pukkandan** [comment]
> Ok ,so I added params below:
> 'html5': '1',
> 'c': 'TVHTML5',
> 'cver': '6.20180913',
> 
> Here: [24297a4](https://github.com/ytdl-org/youtube-dl/commit/24297a42efc52862cb9510d32b28efd7faf49af6)
> and the issue seems to be gone... Not sire how solid of a solution that is..

This seems to work for now. But this will break eventually too

**Comment by E-Mans-Application** [comment]
Thank you very much!
I have been looking for a solution for hours. How did you find it so fast?

YouTube really seems committed to blocking any third-party tool that alters its restrictions...

**Comment by nao20010128nao** [comment]
> Ok ,so I added params below:
> 'html5': '1',
> 'c': 'TVHTML5',
> 'cver': '6.20180913',
> 
> Here: [24297a4](https://github.com/ytdl-org/youtube-dl/commit/24297a42efc52862cb9510d32b28efd7faf49af6)
> and the issue seems to be gone... Not sire how solid of a solution that is..

lol, I found out that this is mimicking TV client like this
![Screenshot from 2021-06-19 12-45-41](https://user-images.githubusercontent.com/10355528/122630109-85cbe400-d0fc-11eb-842a-792ee0e04dd8.png)
![Screenshot from 2021-06-19 12-45-44](https://user-images.githubusercontent.com/10355528/122630110-8795a780-d0fc-11eb-98a5-937eda360edd.png)

UA: `Mozilla/5.0 (Linux; U; Android 4.1.1; nl-nl; POV_TV-HDMI-200BT Build/JRO03H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30`
(second image is saying "Log in to Google account" and "To watch this video, age verification is required")

**Comment by rjdg14** [comment]
> > Ok ,so I added params below:
> > 'html5': '1',
> > 'c': 'TVHTML5',
> > 'cver': '6.20180913',
> > Here: [24297a4](https://github.com/ytdl-org/youtube-dl/commit/24297a42efc52862cb9510d32b28efd7faf49af6)
> > and the issue seems to be gone... Not sire how solid of a solution that is..
> 
> lol, I found out that this is mimicking TV client like this
> ![Screenshot from 2021-06-19 12-45-41](https://user-images.githubusercontent.com/10355528/122630109-85cbe400-d0fc-11eb-842a-792ee0e04dd8.png)
> ![Screenshot from 2021-06-19 12-45-44](https://user-images.githubusercontent.com/10355528/122630110-8795a780-d0fc-11eb-98a5-937eda360edd.png)
> 
> UA: `Mozilla/5.0 (Linux; U; Android 4.1.1; nl-nl; POV_TV-HDMI-200BT Build/JRO03H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30`
> (second image is saying "Log in to Google account" and "To watch this video, age verification is required")

Is that octopus image exclusive to the Japanese version of YouTube, considering that the Japanese like to give everything a mascot? I haven't seen it on any European or American versions of the site.

**Comment by nao20010128nao** [comment]
@rjdg14 

> Is that octopus image exclusive to the Japanese version of YouTube, considering that the Japanese like to give everything a mascot? I haven't seen it on any European or American versions of the site.

I don't know. Check it yourself if you wish.

**Comment by ezhikus** [comment]
It doesn't work anymore: 
![image](https://user-images.githubusercontent.com/1929332/122990668-e719de80-d3ac-11eb-8d55-93f45bbabab8.png)

**Comment by 89z** [comment]
@ezhikus thats not even a valid video: https://www.youtube.com/watch?v=XgnwCQzjau8

**Comment by nao20010128nao** [comment]
@89z No, it's recently deleted. It existed as of @ezhikus's commented.
