### ISSUE TITLE
Chaturbate.com is broken

### ISSUE THREAD

**Issue by jhonnyalphas** [ytdl-org/youtube-dl#29334]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://chaturbate.com/mmmamericancrempie', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Linux-5.8.0-55-generic-x86_64-with-Ubuntu-20.10-groovy
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[Chaturbate] mmmamericancrempie: Downloading webpage
[Chaturbate] mmmamericancrempie: Downloading m3u8 information
WARNING: Failed to download m3u8 information: No status line received - the server has closed the connection
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/chaturbate.py", line 100, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

Error with any link of chaturbate.com

![image](https://user-images.githubusercontent.com/75342360/122571468-60fb4200-d012-11eb-80a0-900e95ae9417.png)

**Comment by daddywarchief** [comment]
I can confirm that something appears to have changed on this site.  It looks like as of this morning, you must be logged in with an account to gain access to the video streams. If you're not logged in, the streams are actually appearing as a series of jpeg images, delivered in the following format:

https://cbjpeg.stream.highwebmedia.com/stream?room=[username]&f=0.47462747063872945

Where the "0.xxxx" at the end is some kind of random number, that changes multiple times a second and references the next frame.

Once you are logged in with an account, you can get the full mp4 stream.  Unfortunately, I haven't been able to pass through account credential info with yt-dl.

**Comment by maillis** [comment]
Here is something I have to add: while I can't download CB streams via youtube-dl ( #29240 ), I can still download them by visiting CB mirror, taking m3u8 link from page source and using ffmpeg. From now on, if stream link is "edge[number].whatever", download fails, but if it is "edge[number]-alb.whatever", it succeeds

This issue looks related to #29264

**Comment by BaronLuo** [comment]
> I can confirm that something appears to have changed on this site. It looks like as of this morning, you must be logged in with an account to gain access to the video streams. If you're not logged in, the streams are actually appearing as a series of jpeg images, delivered in the following format:
> 
> [https://cbjpeg.stream.highwebmedia.com/stream?room=[username]&f=0.47462747063872945](https://cbjpeg.stream.highwebmedia.com/stream?room=%5Busername%5D&f=0.47462747063872945)
> 
> Where the "0.xxxx" at the end is some kind of random number, that changes multiple times a second and references the next frame.
> 
> Once you are logged in with an account, you can get the full mp4 stream. Unfortunately, I haven't been able to pass through account credential info with yt-dl.

1、Login your account
2、Download your cookies see https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-pass-cookies-to-youtube-dl
3、youtube-dl --cookies /xxx/xxx.txt

**Comment by jhonnyalphas** [comment]
@BaronLuo doesn't work properly 

```
[tls @ 0x55b4ef541a80] The specified session has been invalidated for some reason.
[hls @ 0x55b4ef479300] keepalive request failed for 'https://edge251.stream.highwebmedia.com/live-edge/amlst:gabbienbruce-sd-32893cc6d5eecac35e4d1f03172a78ec1e5ed4112309bd0336a504c9262a67e9_trns_h264/media_w18604122_b13192000_t64RlBTOjMwLjA=_5653.ts' with error: 'Input/output error' when opening url, retrying with new connection
[hls @ 0x55b4ef479300] Opening 'https://edge251.stream.highwebmedia.com/live-edge/amlst:gabbienbruce-sd-32893cc6d5eecac35e4d1f03172a78ec1e5ed4112309bd0336a504c9262a67e9_trns_h264/media_w18604122_b13192000_t64RlBTOjMwLjA=_5653.ts' for reading
[mpegts @ 0x55b4ef753040] PES packet size mismatch:01:49.52 bitrate=1244.6kbits/s speed=1.11x    
[mpegts @ 0x55b4ef753040] Packet corrupt (stream = 1, dts = 762896970).
[tls @ 0x55b4efa1bf80] Error in the pull function.

```

**Comment by daddywarchief** [comment]
It looks like as of now, whatever experiment they were trying has ended, at least for the moment.  I'm once again able to use yt-dl on chaturbate streams, using the same version as earlier.
