### ISSUE TITLE
Postprocessor not called when using `-f bestaudio` and `--postprocessor-args`

### ISSUE THREAD

**Issue by brunetton** [ytdl-org/youtube-dl#29364]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -f bestaudio --postprocessor-args "-c:a mp3 -filter:a loudnorm=i=-18:lra=17 -qscale:a 2" 'https://www.youtube.com/watch?v=JKfmTJoW2kc' -v -o test.webm

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'bestaudio', u'--postprocessor-args', u'-c:a mp3 -filter:a loudnorm=i=-18:lra=17 -qscale:a 2', u'https://www.youtube.com/watch?v=JKfmTJoW2kc', u'-v', u'-o', u'test.webm']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18rc1 (CPython) - Linux-5.4.0-26-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] JKfmTJoW2kc: Downloading webpage
[youtube] JKfmTJoW2kc: Downloading MPD manifest
[debug] Invoking downloader on u'https://r16---sn-4gxx-25gel.googlevideo.com/videoplayback?expire=1624404254&ei=vhzSYKyBI5f3xN8Ps4aluA8&ip=2a01%3Ae0a%3A100%3Ae190%3Acd95%3Adc1c%3A2e10%3A6a11&id=o-ALN1Re2gfqeyOQx8IR11Q_IGX_Lzl_6USbqCDwFs1SFo&itag=251&source=youtube&requiressl=yes&mh=Qd&mm=31%2C29&mn=sn-4gxx-25gel%2Csn-4gxx-25gy&ms=au%2Crdu&mv=m&mvi=16&nh=EAE%2CEAE&pl=52&initcwndbps=751250&vprv=1&mime=audio%2Fwebm&ns=kUY3poQ3dmhAeOD1Yq7P12MF&gir=yes&clen=5901131&otfp=1&dur=358.681&lmt=1564508839399265&mt=1624382462&fvip=16&keepalive=yes&fexp=24001373%2C24007246&c=WEB&n=eGxkNNDX6Ojhfzuyt&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAP3oHXJ5FekU66_RyQZgQg5dIbAQAzPwg07_5yIVlpcWAiEAzsNt1YTrVOgUq7q4Em7O021eof5RuT02vb2Zzd1v0AY%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cnh%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAId_jZhfm0sDxx4VIHb1sKMALp9YdLMPhlFiE9hLFiu2AiEA2ahCkwMWnqGv49Aa4F58wUpR93eNMFsRfYPheQamsVw%3D'
[download] Destination: test.webm
[download] 100% of 5.63MiB in 00:01
```

### Goal

I want to download **audio only** from a Youtube video and run `ffmpeg` for some post processing (mainly [audio loudness](https://ffmpeg.org/ffmpeg-filters.html#loudnorm) normalization)

### Problem

The postprocessor is **not called**

I'm using this combination of command line arguments:

- `--postprocessor-args` to pass some options to `ffmpeg` postprocessor
- `-f bestaudio` to only download audio stream (and save the planet :earth_africa:)

### Workaround

The workaround is to download audio + video (not using `-f bestaudio` argument): 

    youtube-dl --postprocessor-args "-c:a mp3 -filter:a loudnorm=i=-18:lra=17 -qscale:a 2" 'https://www.youtube.com/watch?v=JKfmTJoW2kc'

But this is not satisfactory as this uses a lot of bandwidth to download video stream and not using it (I do not have a good internet connection)

## Edit

**edit**: after opening this issue I found this way of doing what I want using `--exec` option. I don't know if this is the "official" way of doing this but it works. It's not super-satisfactory manually remove the file (`&& rm {}`) but it's okay as it works :) 

    youtube-dl -f bestaudio 'https://www.youtube.com/watch?v=JKfmTJoW2kc' --exec "ffmpeg -i {} -c:a mp3 -filter:a loudnorm=i=-18:lra=17 -qscale:a 2 {}.mp3 && rm {} "

Thanks a lot to the team !

PS: I'm absolutely sorry if I missed something in the doc !

**Comment by dirkf** [comment]
The Fine Manual is accurate but not very enlightening on the operation of postprocessing.

The postprocessor isn't run unless yt-dl thinks it's needed. It's needed if a merge is required, or if a fix-up is needed and possible when `--fixup detect_or_warn` (the default), or if one of these options is given (in order of running):
* `--metadata-from-title` (this just extracts additional metadata, without adding it)
* `--extract-audio`
* `--recode-video`
* `--add-metadata`
* `--convert-subs`
* `--embed-subs`
* `--embed-thumbnail`
* `--xattrs`.

If any of these postprocessing steps is run, the `--postprocessor-args` are added to each command.

`--exec` forces a sort of custom final postprocessor, but without managing the deletion of any unwanted input files (as you found).

With this logic in mind, you could try using `--extract-audio --audio-format mp3` with your original command, less the `-c:a mp3`.

In your example, this should work: the downloaded file will be .mp4 or .webm containing the audio, which will be extracted and converted with your options to a .mp3, and the original file discarded, unless `-k`/`--keep-video`.

The postprocessor command will be something like this:

`ffmpeg -y -loglevel repeat+info -i 'file:audio.webm' -vn -acodec libmp3lame -q:a 5 -filter:a loudnorm=i=-18:lra=17 -qscale:a 2 'file:audio.mp3'`
 
If the originally downloaded file was .mp3 and you wanted to postprocess it in this way, the postprocessor would complain about overwriting the original.

**Comment by brunetton** [comment]
Thanks for your answer.

> With this logic in mind, you could try using --extract-audio --audio-format mp3 with your original command, less the -c:a mp3.

Yes but (I'm not sure to be correct here) I thought that `--audio-format mp3` would lead to a quality loss compared to the default `-f bestaudio`. But in my particular case this is probably not important as I convert audio to mp3 at the end anyway.

> In your example, this should work: the downloaded file will be .mp4 or .webm containing the audio, which will be extracted and converted with your options to a .mp3, and the original file discarded, unless -k/--keep-video.

Indeed this works:

```
[youtube] JKfmTJoW2kc: Downloading webpage
[youtube] JKfmTJoW2kc: Downloading MPD manifest
[download] Destination: Rosetta  - Jeff and Joel's House Party #8, October, 2017-JKfmTJoW2kc.webm
[download] 100% of 5.63MiB in 00:01
[ffmpeg] Destination: Rosetta  - Jeff and Joel's House Party #8, October, 2017-JKfmTJoW2kc.mp3
Deleting original file Rosetta  - Jeff and Joel's House Party #8, October, 2017-JKfmTJoW2kc.webm (pass -k to keep)
[exec] Executing command: ffmpeg -i 'Rosetta  - Jeff and Joel'"'"'s House Party #8, October, 2017-JKfmTJoW2kc.mp3' -filter:a loudnorm=i=-18:lra=17 -qscale:a 2 'Rosetta  - Jeff and Joel'"'"'s House Party #8, October, 2017-JKfmTJoW2kc.mp3'.mp3 && rm 'Rosetta  - Jeff and Joel'"'"'s House Party #8, October, 2017-JKfmTJoW2kc.mp3' 
ffmpeg version 4.2.2-1ubuntu1 Copyright (c) 2000-2019 the FFmpeg developers
```

But `ffmpeg` is called twice on the same file here (one for converting webm to mp3, and another for my custom postprocessing).  I'm not sure if I'm loosing a lot of quality here :thinking: 

## Proposed solution

What the team thinks about a `--force-postprocessing` option ? This sounds clear to me. No needs to understand youtube-dl's internals and cases where the postprocessor is called or not.

What do you think about that ?

**Comment by dirkf** [comment]
No, like this (I've added `-v` to show what's happening):
```
$ youtube-dl -v -f bestaudio --extract-audio --audio-format mp3 --postprocessor-args '-filter:a loudnorm=i=-18:lra=17 -qscale:a 2' 'https://www.youtube.com/watch?v=JKfmTJoW2kc'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestaudio', '--extract-audio', '--audio-format', 'mp3', '--postprocessor-args', '-filter:a loudnorm=i=-18:lra=17 -qscale:a 2', 'https://www.youtube.com/watch?v=JKfmTJoW2kc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] JKfmTJoW2kc: Downloading webpage
[youtube] JKfmTJoW2kc: Downloading MPD manifest
[debug] Invoking downloader on 'https://r5---sn-cu-aigsl.googlevideo.com/videoplayback?expire=1624587496&ei=iOjUYOizK8mDp-oPxJWc4Ao&ip=51.6.89.233&id=o-AB1IFfuxiQwvEMtnxqo3YzHHwFJpMHRPB7XPzJs83zTE&itag=251&source=youtube&requiressl=yes&mh=Qd&mm=31%2C29&mn=sn-cu-aigsl%2Csn-cu-c9ie&ms=au%2Crdu&mv=m&mvi=5&pcm2cms=yes&pl=25&initcwndbps=1158750&vprv=1&mime=audio%2Fwebm&ns=AujhtM5Tb_bBXIbBlMabh78F&gir=yes&clen=5901131&otfp=1&dur=358.681&lmt=1564508839399265&mt=1624479162&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&n=EST1aLYKsdlcDmXFfY&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAIBgQqf9DSh3_HVxkZFJtVBsN3uPUbkopNI5GqGxfqYuAiEAhyfagWvH8KefgsHcs7IXlOl9o8_CjfOdibKhzZ3IXCk%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgXhVJfCH2ZyyJJHNcCUw8sFt19vCbJq4n4InmIp2gpoUCIB5K7TGUR38uueLwlCr49Jqrgf1GWkrPOruc2ckLD50i'
[download] Destination: Rosetta  - Jeff and Joel's House Party #8, October, 2017-JKfmTJoW2kc.webm
[download] 100% of 5.63MiB in 00:05
[debug] ffmpeg command line: ffprobe -show_streams 'file:Rosetta  - Jeff and Joel'"'"'s House Party #8, October, 2017-JKfmTJoW2kc.webm'
[ffmpeg] Destination: Rosetta  - Jeff and Joel's House Party #8, October, 2017-JKfmTJoW2kc.mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Rosetta  - Jeff and Joel'"'"'s House Party #8, October, 2017-JKfmTJoW2kc.webm' -vn -acodec libmp3lame -q:a 5 -filter:a loudnorm=i=-18:lra=17 -qscale:a 2 'file:Rosetta  - Jeff and Joel'"'"'s House Party #8, October, 2017-JKfmTJoW2kc.mp3'
Deleting original file Rosetta  - Jeff and Joel's House Party #8, October, 2017-JKfmTJoW2kc.webm (pass -k to keep)
$ ls -sh *.mp3
7.7M Rosetta  - Jeff and Joel's House Party #8, October, 2017-JKfmTJoW2kc.mp3
$
```
After downloading, yt-dl runs `ffprobe` to check what's in the .webm. Then it runs `ffmpeg` to extract the audio and normalise it into a .mp3. That's about as efficient as it could be, and there's no excess encoding. For some downloads, with the setting `--hls-prefer-ffmpeg`, `ffmpeg` might also be invoked to download media that is served using HLS but it doesn't re-encode.

**Comment by brunetton** [comment]
Thanks ! This does the trick :)
