### ISSUE TITLE
My downloadspeed of my Youtube Downloads are being reduced/limited. What is the Problem?

### ISSUE THREAD

**Issue by Why155** [ytdl-org/youtube-dl#29361]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v -i -f bestvideo+bestaudio https://www.youtube.com/playlist?list=UUUllb83Lugbka-rvF6Nutxg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-i', '-f', 'bestvideo+bestaudio', 'https://www.youtube.com/playlist?list=UUUllb83Lugbka-rvF6Nutxg']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-05-15-b18fd2b
[debug] Proxy map: {}
```

## Description

WRITE DESCRIPTION HERE

![Screenshot (1)](https://user-images.githubusercontent.com/86298452/122916216-f2451e00-d35c-11eb-996e-69ebe0b8cee1.png)
![Screenshot (5)](https://user-images.githubusercontent.com/86298452/122916220-f2ddb480-d35c-11eb-9066-81cc7762dc83.png)

`youtube-dl -i -f bestvideo+bestaudio https://www.youtube.com/playlist?list=UUUllb83Lugbka-rvF6Nutxg`

Try for yourself. At the beginning, downloadspeed is not reduced, but after some time it gets down to 80 or 50 kbs.
It is not my connection. I am suffering with this for a few weeks now, since i used youtube-dl again. Does anybody know something about that issue? If you have further questions ask me. I couldn't fix it. Currently I'm downloading something and it's reduced again. I always have to restart cmd.

I have another question. When youtube was taken down on github, you couldn't download youtube-dl anymore. I had a few youtube-dl.exe file stored and tried to use them anyways. I was really surprised, when i wanted to download youtube files. Youtube-dl was blocked completely. It didn't work. How is this possible? Can youtube block youtube-dl? Did it someone else? Who could and did block youtube-dl during this time? I need to know wether youtube-dl is under control or independend.

**Comment by ByteTemplar** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29326

**Comment by matkoniecz** [comment]
> PASTE VERBOSE LOG HERE

Your log is missing. Run `youtube-dl --verbose whatever_other_parameters` and copy its text - rather than image of a screen.

**Comment by matkoniecz** [comment]
> I have another question.

See https://github.com/ytdl-org/youtube-dl#does-the-issue-involve-one-problem-and-one-problem-only

**Comment by mongolsteppe** [comment]
The only solution I've found so far is using [yt-dlp](https://github.com/yt-dlp/yt-dlp/releases/tag/2021.07.07) and adding the following at the end of the call 
`--extractor-args youtube:player_client=android --throttled-rate 100K`
like so:
`yt-dlp "https://www.youtube.com/watch?v=exampleURL" --extractor-args youtube:player_client=android --throttled-rate 100K`

It works with complex queries as well, for example: 
` yt-dlp -o "e:\TMC\%(autonumber)s.%(title)s.%(ext)s" https://www.youtube.com/channel/XYZ -f mp4 -i  --extractor-args youtube:player_client=android --throttled-rate 100K`
(only difference being replacing youtube-dl for yt-dlp)

Credit to https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-879256177

**Comment by mongolsteppe** [comment]
The only solution I've found so far is using [yt-dlp](https://github.com/yt-dlp/yt-dlp/releases/tag/2021.07.07), which uses the same syntax as youtube-dl. An example:
`yt-dlp https://www.youtube.com/watch?v=exampleURL`

It works with complex queries as well e.g.: 
` yt-dlp -o "e:\TMC\%(autonumber)s.%(title)s.%(ext)s" https://www.youtube.com/channel/XYZ -f mp4 -i `

So the only thing you need to change is youtube-dl for yt-dlp at the beginning of your command.

Credit to https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-879256177

PS: In the rare occasion, where you still find throttling issues (hasn't happened to me yet), add the following at the end of the call `--throttled-rate 100K`

**Comment by Muffo** [comment]
Thanks @mongolsteppe for pointing me to yt-dlp. I am a first time user of youtube-dl and had the same issue. yt-dlp worked much faster and is downloading at 10+MB/s instead of 50kB/s.

**Comment by HalvorRaknes** [comment]
I am using yt-dlp and am being throttled terribly. Yesterday I got download rates around 80 kB/s for most attempts. Restarting the download would result in normal speeds (3-8 MB/s) in about 1 of 5 tries. But today it started out with ubiquitous speeds of about 80 kB/s but now they're all down below 30 kB/s.

**Comment by dirkf** [comment]
Fixed in https://github.com/ytdl-org/youtube-dl/commit/af9e72507ea38e5ab3fa2751ed09ec88021260cb; use the nightly release.
