### ISSUE TITLE
"ERROR: Sign in to confirm your age" on YouTube

### ISSUE THREAD

**Issue by rg3** [ytdl-org/youtube-dl#29365]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v 'https://www.youtube.com/watch?v=zgqz8Je7P0s'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=zgqz8Je7P0s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.5 (CPython) - Linux-5.12.11-300.fc34.x86_64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[youtube] zgqz8Je7P0s: Downloading webpage
[youtube] zgqz8Je7P0s: Refetching age-gated info webpage
WARNING: unable to download video info webpage: HTTP Error 404: Not Found
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
Traceback (most recent call last):
  File "/home/rg3/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rg3/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/rg3/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/rg3/.local/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1713, in _real_extract
    raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: Sign in to confirm your age
This video may be inappropriate for some users.

```

## Description

It seems like the "ERROR: Sign in to confirm your age" problem is unfortunately happening again with the latest version. However, using tools like NSFW YouTube in the browser the video is playable without signing in. Thanks in advance.

**Comment by llacb47** [comment]
Fixed in master branch, but a new release was not made yet.

**Comment by rg3** [comment]
> Fixed in master branch, but a new release was not made yet.

Ah, sorry. I should have tried that first. Just checked and it works, indeed. Thanks a lot for the tip.

**Comment by Kodiologist** [comment]
Did it just break again? I installed the current master, a8035827177d6b59aca03bd717acb6a9bdd75ada, and I'm getting the same error.

**Comment by J1327** [comment]
Even am using VPN and able to see video (without filling forms) ,
Youtube-Dl can't download it (no matter i use in addition --geo-bypass)

D:\ffmpeg>youtube-dl https://www.youtube.com/watch?v=mFZc3GE830w
[youtube] mFZc3GE830w: Downloading webpage
[youtube] mFZc3GE830w: Refetching age-gated info webpage
WARNING: unable to download video info webpage: HTTP Error 404: Not Found
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.

**Comment by iFUCKINGHATEcomputers** [comment]
When can a new release (that fixes this) be expected? Last one was a month ago.

**Comment by wrtorrent** [comment]
v2021.06.06

`youtube-dl.exe -F QvvE0fvned0
[youtube] QvvE0fvned0: Downloading webpage
[youtube] QvvE0fvned0: Refetching age-gated info webpage
WARNING: unable to download video info webpage: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 475, in main
  File "youtube_dl\__init__.pyo", line 465, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 2070, in download
  File "youtube_dl\YoutubeDL.pyo", line 809, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 816, in wrapper
  File "youtube_dl\YoutubeDL.pyo", line 837, in __extract_info
  File "youtube_dl\extractor\common.pyo", line 534, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1503, in _real_extract
  File "youtube_dl\compat.pyo", line 2644, in compat_parse_qs
  File "youtube_dl\compat.pyo", line 2614, in _parse_qsl
AttributeError: 'bool' object has no attribute 'split'`

2020.11.17

`ydl.exe -F QvvE0fvned0
[youtube] QvvE0fvned0: Downloading webpage
[youtube] QvvE0fvned0: Downloading embed webpage
[youtube] QvvE0fvned0: Refetching age-gated info webpage
[ERROR] ERROR: Sign in to confirm your age
ERROR: Sign in to confirm your age`

**Comment by ramones1982** [comment]
just got that error

**Comment by Kodiologist** [comment]
I'd recommend switching to [yt-dlp](https://github.com/yt-dlp/yt-dlp), which seems to generally be in better shape.

**Comment by ramones1982** [comment]
> I'd recommend switching to [yt-dlp](https://github.com/yt-dlp/yt-dlp), which seems to generally be in better shape.

Thanks ... I didn't knew about the fork ... it works perfectly at first try and it's way much faster !!!
