### ISSUE TITLE
Youtube-dl ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); 

### ISSUE THREAD

**Issue by damon4811** [ytdl-org/youtube-dl#29388]
I have the latest version for Youtube-dl running ie 2021.06.06 but still it gives me error:
Trying to download Udemy video
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>);

I am using URL as:
youtube-dl --cookies cookie.txt https://xxxxxxxxxxx/xxxxxxxxx/

Also:

youtube-dl --cookies path to file\cookies.txt -o "path to download folder/%(playlist)s/%(chapter_number)s – %(chapter)s/%(playlist_index)s – %(title)s.%(ext)s" "URL for course"

Even tried to remove cahce:

youtube-dl --rm-cache-dir

Please assist

**Comment by nisamo** [comment]
i have this problem for oreilly.com

ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>);

every time open issues closed here without fix problem

**Comment by dirkf** [comment]
Duplicate of #29386
