### ISSUE TITLE
Why youtube dl speed is decrease i am not able to download songs

### ISSUE THREAD

**Issue by Hunter-Opp** [ytdl-org/youtube-dl#29384]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by Technical-Hunter** [comment]
I am not able to download songs properly please fix youtube dl speed issue asap

**Comment by B0pol** [comment]
Duplicate of https://github.com/ytdl-org/youtube-dl/issues/29326

**Comment by rautamiekka** [comment]
Also, don't skip the template.

**Comment by dirkf** [comment]
Closed in af9e72507.
