### ISSUE TITLE
"No video formats found" when downloading CBS Video

### ISSUE THREAD

**Issue by bradleykorn** [ytdl-org/youtube-dl#29393]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--newline', '-i', '--all-subs', '-o', 'C:\\Users\\blah\\Videos\\%(uploader)s\\%(title)s [%(id)s].%(ext)s', '--ignore-config', '--hls-prefer-native', '--add-metadata', 'https://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/60icOhMb9NcjbcWnF_gub9XXHdeBcNk2/the-late-show-6-23-21-christine-baranski-joy-oladokun-/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-04-03-52523b6, ffprobe git-2020-04-03-52523b6
[debug] Proxy map: {}
[CBS] 60icOhMb9NcjbcWnF_gub9XXHdeBcNk2: Downloading XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\cbs.py", line 115, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\cbs.py", line 97, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

There is an existing open issue with a similar title, but the issue is incomplete with no detail.

Command line:
youtube-dl.exe --newline -i --all-subs -o "C:\Users\blah\Videos\%(uploader)s\%(title)s [%(id)s].%(ext)s" --ignore-config --hls-prefer-native --add-metadata "https://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/60icOhMb9NcjbcWnF_gub9XXHdeBcNk2/the-late-show-6-23-21-christine-baranski-joy-oladokun-/"

Using Windows exe.
Other videos from same site download without issue.
The video plays fine from the site.
In the verbose output, the entry just before the error and stack trace says its downloading XML. I'm assuming that something in or about this XML is causing the error to occur.

**Comment by dirkf** [comment]
In particular, the XML doesn't include details of the actual media :-(.

**Comment by bradleykorn** [comment]
So, then CBS has a problem with this specific piece of media.

________________________________

**Comment by dirkf** [comment]
The extractor expects the media details to be in that XML downloaded from another site. If they're not, it's either an error or because the provider is handling the show differently.
