### ISSUE TITLE
Download video from ixigua.com?

### ISSUE THREAD

**Issue by hoangduyloc** [ytdl-org/youtube-dl#29391]
Hello,
Does anyone know how to download the video from ixigua.com? 
Thank you.

**Comment by kikuyan** [comment]
Go #24186

**Comment by hoangduyloc** [comment]
> Go #24186

This issue is too old, and website update monthly

**Comment by someziggyman** [comment]
maybe this will be helpful for future extractor:
https://github.com/feilongfl/script.module.you_get/blob/f8f0a6df6a43b029b29afa29482b520d504172b7/lib/you_get/extractors/ixigua.py

**Comment by ghithub** [comment]
Although it'll be great to add support to ixigua.com, for now if you can simply use FireFox to download ixigua videos:  1) Play any ixigua video in FireFox; 2) Press ctrl-i, and the Page Info popup will open up. At the top o the popup, there are 4 tabs: General, Media, Permission, Security. Click on Media. Click on the video you want to download, note that the Type column will tell you the media type, and click on Save As. If the system-given file name is of type htm, just change it to MP4, you can double quote the file name like this: "my-lovely-video.mp4". That's it.

**Comment by kocoman2** [comment]
> Although it'll be great to add support to ixigua.com, for now you can simply use FireFox to download ixigua videos:
> 
> 1. Play any ixigua video in FireFox
> 2. Press ctrl-i, and the Page Info popup will open up.
> 3. At the top o the popup, there are 4 tabs: General, Media, Permission, Security. Click on Media.
> 4. Click on the video you want to download, note that the Type column will tell you the media type.
> 5. Click on Save As. If the system-given file name is of type htm, just change it to MP4. You can double quote the file name like this: "my-lovely-video.mp4".

I am getting blob:https://www.ixigua.com/GUID# 
for the video but it can't download it its grayed out, pasting the http says sorry something

using the command line version says
ERROR: [Ixigua] IDXXXXX: Cookies (not necessarily logged in) are needed

Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: e25611c11ca369645b8fdbdd5c57de8230867b62bec16ec98b8c37d692d1e756
yt-dlp is up to date (stable@2023.07.06)

**Comment by dirkf** [comment]
>yt-dlp is up to date (stable@2023.07.06) ??

**Comment by parkblink** [comment]
https://www.ixigua.com/7379261949106160163?logTag=b80c5738a55081dc9016
