### ISSUE TITLE
Request for downloading from pornship.com

### ISSUE THREAD

**Issue by a0v0** [ytdl-org/youtube-dl#29396]
## Example URLs

- Single video: https://www.pornship.com/video/1161628136?to=YTo1OntzOjg6InZpZGVvX2lkIjtpOjExNjE2MjgxMzY7czo0OiJsaW5rIjtzOjg2OiJodHRwczovL3d3dy5wb3JuZmxpcC5jb20vazdHSHBrV2xJeW0vc2V4bWV4LWdhbGktZGl2YS1ob3QtdGlrLXRva2VyLW1vbS1sZXRzLXN1Y2stZGljayI7czoyOiJpZCI7aToxMTE7czo0OiJ0eXBlIjtzOjEwOiJjYXRlZ29yaWVzIjtzOjk6ImRvbWFpbl9pZCI7aToyO30%3D

## Description

I think this site deserves to be in the list of youtube-dl so please add it.

**Comment by 8chanAnon** [comment]
Special note in case support is added for this site:

It implements a bot detector.  Use sparingly else your IP address will be blocked for some hours or a day (not sure). 

Other than that, it is very easy to hack.
