### ISSUE TITLE
[Twitter] Unable to use long filenames in 64-bit W10 Pro.

### ISSUE THREAD

**Issue by antdude** [ytdl-org/youtube-dl#29407]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\ant\Downloads\videos>c:\winstuff\youtube-dl -v https://twitter.com/NASAPersevere/status/1408468279669051407
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://twitter.com/NASAPersevere/status/1408468279669051407']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[twitter] 1408468279669051407: Downloading guest token
[twitter] 1408468279669051407: Downloading JSON metadata
[twitter] 1408468279669051407: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://video.twimg.com/amplify_video/1408458180644937732/vid/1280x720/YM-nO8ySdKBFdwXZ.mp4?tag=14'
ERROR: unable to open for writing: [Errno 2] No such file or directory: "NASA's Perseverance Mars Rover - Lots of people ask - how do rovers like me and @MarsCuriosity take our own selfies It’s not as easy as a quick smartphone snap. See how it’s done with the help of my team back on Earth --1408468279669051407.mp4.part"
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\downloader\http.py", line 260, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\utils.py", line 2055, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: "NASA's Perseverance Mars Rover - Lots of people ask - how do rovers like me and @MarsCuriosity take our own selfies It’s not as easy as a quick smartphone snap. See how it’s done with the help of my team back on Earth --1408468279669051407.mp4.part"
```

## Description

WRITE DESCRIPTION HERE
I was unable to download this Twitter video in my 64-bit W10 PC, but I had no problems in my friend's Fedora v33 PC.  Thank you for reading and hopefully answering. :)

**Comment by kikuyan** [comment]
Maybe generated filename is too long for your system. Try setting short output filename like `-o "%(id)s.%(ext)s"` or `-o "%(title).100s.%(ext)s"` and rename the file after download.

**Comment by antdude** [comment]
-o "%(id)s.%(ext)s" worked. Maybe youtube-dl needs to check for this and tell user?

**Comment by antdude** [comment]
Also, thanks. :)

**Comment by dirkf** [comment]
The Twitter extractor uses the same text for `description` and the same (or longer) text for `title`. This seems unsatisfactory: shouldn't the title be abbreviated if it exceeds some length? Eg, 
```
    title_max = 68
    if len(title) > title_max:
        title, changed = re.subn(r'(^.{%d,}?)(\s?.*$)' % (title_max-4), r'\1 ...', title)
        if changed == 0:
            title = re.sub(r'(^.{%d,}?)(.*$)' % (title_max-3), r'\1...', title)
```
```
>>> title = "NASA's Perseverance Mars Rover - Lots of people ask - how do rovers like me and @MarsCuriosity take our own selfies It’s not as easy as a quick smartphone snap. See how it’s done with the help of my team back on Earth"
>>> re.sub(r'(^.{%d,}?)(\s.*$)' % (68-4), r'\1 ...', title)
"NASA's Perseverance Mars Rover - Lots of people ask - how do rovers ..."
>>>
```
Or with the `textwrap` library class: Python 2 lacks the `shorten()` method, so:
```
    import textwrap
    title_max = 68
    if len(title) > title_max:
        title = textwrap.wrap(title, title_max)[0] + ' ...'
```
```
>>> import textwrap
>>> textwrap.wrap(title, 68)[0]+' ...'
"NASA's Perseverance Mars Rover - Lots of people ask - how do rovers ..."
>>>
```

**Comment by sur0g** [comment]
I use an ext4 filesystem and having this problem. This looks odd: using a tweet text as a filename although tweet length is limited to 280 which exceeds the POSIX max filename of 255 characters. Maybe we should shrink that to 255 bytes or generate an UUID or something?

**Comment by funnym0nk3y** [comment]
It is odd that I'm having the same issue, but copying the file to the same destination with the same name works just fine.

**Comment by dirkf** [comment]
Maybe the `.part` temporarily added during download takes the filename over the limit?

Also, see PR #29989.

**Comment by dirkf** [comment]
Continued in #30361.
