### ISSUE TITLE
Allowed to stream music to discord channel?

### ISSUE THREAD

**Issue by PlaceblockHD** [ytdl-org/youtube-dl#29411]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

I already searched about that topic, but i didnt find anything. I already found out that it is allowed to download videos for personal use, but i want to **stream** only **music** and this on **discord** ... is this allowed?

There are many other discord bots out there, which all doing the same... so it should be allowed, or not?

Have a great day :D

**Comment by phdoerfler** [comment]
Good question! Here's a few thoughts:

- Legal advice, is a Github issue tracker the right place for this?
- What country is the Discord server located in?
- What country is Discord, the company, located in?
- What country is the server administrator located in?
- What is the copyright status and license of the music?
- Did the content creator mark it as public domain or copyleft?
- Does this qualify as fair use?
- Is the term "fair use" or, in fact, any of what I mentioned even applicable to the
  - server administrator?
  - Discord?
  - the content creator?

I'm no lawyer. I'm just someone who is also curious whether streaming music to a discord channel is "allowed".
It might be an answer that depends on many variables. E.g., in Germany there's the infamous GEMA which is notorious for getting in the way of people who seek to play music for an audience and this would likely qualify. Fwiw here are their [radio broadcast regulations](https://www.gema.de/musiknutzer/musik-lizenzieren/hoerfunk/).

**Comment by PlaceblockHD** [comment]
Thanks for you response, it helped me a lot!
