### ISSUE TITLE
How do I limit the number of videos for the extract_info function?

### ISSUE THREAD

**Issue by maksam07** [ytdl-org/youtube-dl#29424]
## Checklist
- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question
Hello! I am using extract_info function to get video from channel (https://www.youtube.com/channel/.../)
But the channel has a lot of 500+ videos. And I would like to receive information only about the first 50, so as not to wait a few minutes for unloading. Can I somehow limit the number of videos?

The code I am using
```python
ydl_opts = {
    'ignoreerrors': True,
    'outtmpl': filename,
    'logger': MyLogger(),
    'progress_hooks': [progress_hooks_empty],
    'writesubtitles': True,
    'format': 'mp4',
    'writethumbnail': True,
}

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    result = ydl.extract_info('URL', False)
```

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl/blob/7fb9564420d43252c8f8c453d4dc54bf3ff9f8ee/youtube_dl/YoutubeDL.py#L172
