### ISSUE TITLE
help in understanding why some mp4 files plays in <video> but not after downloaded

### ISSUE THREAD

**Issue by colourful-land** [ytdl-org/youtube-dl#29428]
## Checklist

- [ x ] I'm asking a question
- [ x ] I've looked through the README and FAQ for similar questions
- [ x ] I've searched the bugtracker for similar questions including closed ones

## Question

This isn't really about using youtub-dl but a old youtube-dl user trying to manually download from a website unsupported by youtube-dl. What I did is to examine the runtime dom tree and got this:

    <video controls="" controlslist="nodownload noremote" disablepictureinpicture="" autoplay="" style="border:5px solid lightgrey;width:100%;height:auto;" id="myVideo">
    <source src="DF/1de4892b42fa3db35fc4cf058a02acb057a8df02d0d3cdc96e686551aee25a39.mp4" type="video/mp4">
     </video>

And used Firefox's developer tool to copy the download cURL command, therefore obtained the file in `<source>`.

````
 curl … -H 'Cookie: _ga=GA1.2.390696365.1624933815; _gid=GA1.2.185623249.1624933815; ASPSESSIONIDSUATRTTS=OLOLIDJAINKHKEPOANNPEIMN'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  734M  100  734M    0     0   769k      0  0:16:17  0:16:17 --:--:--  812k
````

It is of the expected size, however none of my player can open it and `file(1)` command can't tell the format either:

````
$ file 1de4892b42fa3db35fc4cf058a02acb057a8df02d0d3cdc96e686551aee25a39.mp4
1de4892b42fa3db35fc4cf058a02acb057a8df02d0d3cdc96e686551aee25a39.mp4: data
$ od -x 1de4892b42fa3db35fc4cf058a02acb057a8df02d0d3cdc96e686551aee25a39.mp4  | head
0000000 cfa5 7bd9 34f8 6630 2f04 3d4f af8b ab00
0000020 3b10 8b16 7442 07fc 102f a778 0a57 19e9
0000040 4e19 9d2d 2dfd 8b73 7743 dd7d 58e3 7e9b
0000060 1411 37ce dc34 e50c 9414 3f68 8d18 c29a
0000100 e7d4 66f5 fe54 e237 2887 18c4 c4ac d5e9
0000120 803f 4729 abfd 8ecd 0f4a 9165 902a d4b2
0000140 86e8 0dae c0d7 7052 ff3e 2323 6e94 e441
0000160 0cad d275 8bfe 7b48 0f75 98eb 1b2c 1a7e
0000200 d892 9668 fb4a 4610 c17b 5238 1d73 94c6
0000220 97d6 fc63 ac5a 0155 e0fc 5377 aa3b 7203

````

What magic could have transformed the unplayable mp4 file to be playable in the webpage? Asking for ideas, since I'm sure youtube-dl developers meet such problems often. Thanks!

**Comment by kikuyan** [comment]
Wrong place. Go [VideoHelp Forum](https://forum.videohelp.com/forums/48-Video-Streaming-Downloading) or else.

**Comment by llacb47** [comment]
which site? @colourful-land
