### ISSUE TITLE
Limit max download option with embedded call

### ISSUE THREAD

**Issue by EthanFitzpatrick0** [ytdl-org/youtube-dl#29427]
## Checklist

- [x]  I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm using youtube-dl embedded in python and trying to put a limit on the number of downloads a request makes. There doesn't seem to be an [option](https://github.com/ytdl-org/youtube-dl/blob/3e4cedf9e8cd3157df2457df7274d0c842421945/youtube_dl/YoutubeDL.py#L137-L312) for it. I know there's `--max-downloads NUMBER` , but that can only be used through the command line, right? Is my best option to call it through a subprocess? I guess I could also use `playliststart` and `playlistend`, but that's not exactly what I'm looking for.

Thanks for any help.

**Comment by dirkf** [comment]
The corresponding option is just `max_downloads`, as in `self.params.get('max_downloads')` where `self` is a `YoutubeDL` object, but it hasn't made it into the class documentation.

**Comment by EthanFitzpatrick0** [comment]
> The corresponding option is just `max_downloads`, as in `self.params.get('max_downloads')` where `self` is a `YoutubeDL` object, but it hasn't made it into the class documentation.

Ah, thanks! Exactly what I was looking for.
