### ISSUE TITLE
ERROR: An extractor error has occurred

### ISSUE THREAD

**Issue by pfred1** [ytdl-org/youtube-dl#29446]
It says report it so here you go.

$  youtube-dl  --verbose "https://odysee.com/@TheQuartering:1/bill-released-on-technicality!-a-free:4"
 youtube-dl  --verbose "https://odysee.com/@TheQuartering:1/bill-released-on-technicalityaproposefree:4"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://odysee.com/@TheQuartering:1/bill-released-on-technicalityaproposefree:4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-15-amd64-x86_64-with-debian-9.13
[debug] exe versions: ffmpeg N-92964-g9217ded, ffprobe N-92964-g9217ded
[debug] Proxy map: {}
[lbry] @TheQuartering#1/bill-released-on-technicalityaproposefree#4: Downloading stream JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'value',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/pfred1/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/pfred1/bin/youtube-dl/youtube_dl/extractor/lbry.py", line 178, in _real_extract
    result_value = result['value']
KeyError: u'value'
Traceback (most recent call last):
  File "/home/pfred1/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pfred1/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/pfred1/bin/youtube-dl/youtube_dl/extractor/common.py", line 547, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'value',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by kikuyan** [comment]
First url you've shown contains `!`, shell history expansion.
Second url you've passed to youtube-dl doesn't contain that character. Maybe this url is invalid.

Use single quotes to not `!` interpreted by shell.

**Comment by pfred1** [comment]
Doh! I got screwed by a special character! Thanks my bad.
