### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by KaelaHenkel** [ytdl-org/youtube-dl#29441]
OS:
Linux Fedora (VM)

Command used:
sudo apt-get purge --remove youtube-dl-2021.06.06.tar.gz

Result:
E: couldn't find any package by glob 'youtube-dl-2021.06.06.tar.gz'
E: couldn't find any package by regex 'youtube-dl-2021.06.06.tar.gz'

Yet the program still exists in /home/user1 as a write protected file.

I'm new to Linux, this may be a problem all on me being inexperienced but any help is greatly appreciated!

Edit:
I entered:
pip uninstall youtube-dl
and got the following:
WARNING: Skipping youtube-dl as it is not installed
How can it not be installed when I was using the program yesterday?

**Comment by alerikaisattera** [comment]
What did you use to install it?

**Comment by rautamiekka** [comment]
Ya, how did you install it ?

You don't use the APT commands to [un]install things installed outside the repos.

In the context of a Python software such as ytdl on GitHub or something you always do 1 of in this order:
- install from PyPi using `pip` or from Anaconda repos using `conda`. Easy to update and to keep the dependencies up-to-date. ytdl is officially auto-released on PyPi.
- take the released executable binary.  It can be updated in place with `youtube-dl --update`, but it can still fail to find an update, which seems to be more likely with GitHub than with PyPi.
- take the source code, either straight from the repo (or the 'Source code (zip)' or `Source code (gz)`) or the released package like that tgz. Being a Python app (and explicitly coded for running without being packaged) it can be started by `python __main__.py`.

**Comment by remitamine** [comment]
- if you installed using Fedora builtin package manager(dnf) then search for how uninstall fedora packages.
- if you [installed the package directly](https://github.com/ytdl-org/youtube-dl#installation) then just remove the file.

**Comment by Aman-Singh-Kushwaha** [comment]
use  `sudo pip uninstall youtube-dl`
you might have pip installed as root user
![image](https://github.com/ytdl-org/youtube-dl/assets/96011814/1ae5f193-5dbe-47d5-a398-5ec3c6028051)
