### ISSUE TITLE
vod.afreecatv.com ERROR: Unable to extract station

### ISSUE THREAD

**Issue by bruce20190119** [ytdl-org/youtube-dl#29468]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hello，I used youtube-dl to download vod from afreecatv.com（link：https://vod.afreecatv.com/PLAYER/STATION/74665406），this is a age restricted vod，I am signed in on the website as the videos are age restricted，terminal display：Unable to extract station。 （My computer is Imac，youtube-dl --version 2021.06.06），thank you。
[log.txt](https://github.com/ytdl-org/youtube-dl/files/6759986/log.txt)

**Comment by kikuyan** [comment]
Please search and read other issue reports [is:issue is:open afreecatv](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+is%3Aopen+afreecatv)

**Comment by bruce20190119** [comment]
> 请搜索并阅读其他问题报告[是：问题是：打开afreecatv](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+is%3Aopen+afreecatv)



> 请搜索并阅读其他问题报告[是：问题是：打开afreecatv](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+is%3Aopen+afreecatv)

But i don't find the Useful answers，can you help me？

**Comment by zwolf13** [comment]
Did you try adding `--cookies FILE` parameter?
You can get the cookie file by installing `cookies.txt` plugin in Chrome and Mozilla, then login to the website and export the cookies to be used by your command, like:
```
youtube-dl --cookies your-file.txt https://vod.afreecatv.com/PLAYER/STATION/74665406
```

**Comment by zyz-1998** [comment]
> 您是否尝试添加`--cookies FILE`参数？ 您可以通过在 Chrome 和 Mozilla 中安装`cookies.txt`插件来获取 cookie 文件，然后登录网站并导出 cookie 以供您的命令使用，例如：
> 
> ```
> youtube-dl --cookies your-file.txt https://vod.afreecatv.com/PLAYER/STATION/74665406
> ```

youtube-dl.exe -u XXX-p XXXXXX@ -R 999 --ffmpeg-location "ffmpeg/bin" ^
--hls-prefer-native "http://vod.afreecatv.com/PLAYER/STATION/98648999"
is not work

**Comment by dirkf** [comment]
Continued in #31858.
