### ISSUE TITLE
Why is the downloads audio quality way lowered in the last weeks?

### ISSUE THREAD

**Issue by CiprianDinca9** [ytdl-org/youtube-dl#29466]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I 
I did a lot of things to solve it and, no fix. It seems that even with 320 kbps settings on various services, it sounds... Not really like 320 kbps. Please give an answer to me as soon as possible and, if possible, fix it.
Thanks and best regards!

**Comment by StormProductionsMusic** [comment]
Same issue here. Every site or extractor I use has a lowered quality.

**Comment by llacb47** [comment]
Which extractors? Learn how to provide the needed info

**Comment by CiprianDinca9** [comment]
First, i was not able to check boxes there because my screen reader didn't
show them to me.
Here!
My favourite fully featured YouTube client, over at www.ymusic.io has
dropped audio quality. My friend's converters. Ytmp3.eu and 320ytmp3.com,
both did the same. Please forgive me and understand that I am blind and I
ran into an issue.

**Comment by dirkf** [comment]
Unfortunately you seem to be asking about a generic problem with services that download and/or convert audio from the YT site, and not about anything to do with the `youtube-dl` program.

**Comment by CiprianDinca9** [comment]
Ok. But I tried installing it on my machine and... The same. Also, how can
these services, if possible, Fix this?
