### ISSUE TITLE
mp4 files don't work on Quicktime Player without yuv480p chroma subsampling  

### ISSUE THREAD

**Issue by doulosiesous** [ytdl-org/youtube-dl#29476]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.16 (CPython) - Darwin-20.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}

```

## Description

I've been attempting to use youtube-dl on my 2019 Macbook Pro. I've tried to download multiple youtube videos using the following command as an example:

youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' 'https://www.youtube.com/watch?v=bON-KPiiNCk'

When I attempt to open it in Quicktime, I get the following error message: "This file contains some media which isn’t compatible with QuickTime Player."
![image](https://user-images.githubusercontent.com/19418878/124501175-4e0c9f80-dd7e-11eb-92d0-c25653458405.png)

After further research, I found this superuser post: https://superuser.com/questions/1372702/ffmpeg-yuv420p-pixel-format-missing

After using the command listed on there the video worked: ffmpeg -i input.mp4 -vf format=yuv420p output.mp4

Is there a way to set this as a default pixel format for the process or do I need to run this command each time?

**Comment by xenova** [comment]
You should be able to do what you want using one of the following arguments:

`--merge-output-format FORMAT` If a merge is required (e.g. bestvideo+bestaudio), output to given container format. One of mkv, mp4, ogg, webm, flv. Ignored if no merge is required




`--recode-video FORMAT`                Encode the video to another format if necessary (currently supported: mp4|flv|ogg|webm|mkv|avi)


`--postprocessor-args ARGS` Give these arguments to the postprocessor

---

I think just adding `--merge-output-format mp4` should fix it.

**Comment by kikuyan** [comment]
> youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' 'h<span></span>ttps://www.youtube.com/watch?v=bON-KPiiNCk'

If you've run above, format code 401 should have been selected for video, which is AV1.

> 401          mp4        3840x2160  2160p60 HDR 11541k , mp4_dash container, av01.0.13M.08.0.110.09.16.09.0@11541k, 60fps, video only, 139.33MiB

I guess QuickTime Player doesn't support AV1 yet. It would be better to try VLC or mpv or IINA player instead.

**Comment by doulosiesous** [comment]
> You should be able to do what you want using one of the following arguments:
> 
> `--merge-output-format FORMAT` If a merge is required (e.g. bestvideo+bestaudio), output to given container format. One of mkv, mp4, ogg, webm, flv. Ignored if no merge is required
> 
> `--recode-video FORMAT` Encode the video to another format if necessary (currently supported: mp4|flv|ogg|webm|mkv|avi)
> 
> `--postprocessor-args ARGS` Give these arguments to the postprocessor (this is where you would choose the pixel format)
> 
> I think just adding `--merge-output-format mp4` should fix it.

Tried these 3. First two didn't change it. Format is still mp4, but doesn't work with Quicktime. Not sure I understand --postprocessor practically in this case so I'll look into that.

**Comment by doulosiesous** [comment]
> > youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' 'https://www.youtube.com/watch?v=bON-KPiiNCk'
> 
> If you've run above, format code 401 should have been selected for video, which is AV1.
> 
> > 401          mp4        3840x2160  2160p60 HDR 11541k , mp4_dash container, av01.0.13M.08.0.110.09.16.09.0@11541k, 60fps, video only, 139.33MiB
> 
> I guess QuickTime Player doesn't support AV1 yet. It would be better to try VLC or mpv or IINA player instead.

VLC worked fine. Guess QuickTime is behind the times. Too bad it's the default on all the office Apple devices.

**Comment by dirkf** [comment]
Or add a filter against the av1 codec:
```
youtube-dl -f '(bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best)[vcodec!^=?av01]' 'https://www.youtube.com/watch?v=bON-KPiiNCk'
```
With the same effect:
```
youtube-dl -f '((bestvideo+bestaudio/best)[ext^=m]/best)[vcodec!^=?av01]' 'https://www.youtube.com/watch?v=bON-KPiiNCk'
```
One could append `/best` to be sure of getting something even if it doesn't play in the default QuickTime configuration.

**Comment by DanielCrompton123** [comment]
<img width="276" alt="Screenshot 2024-11-11 at 10 08 21 PM" src="https://github.com/user-attachments/assets/f759ba75-f1d2-47f7-9e9c-bbf04f9e4d31">
I still get the same error

**Comment by dirkf** [comment]
I noticed that QuickTime Player on a recent macOS is happy with AV1 and can even save an AV1 video as H.264: no need for Handbrake.

For older OS/QT Player combos, just use VLC.
