### ISSUE TITLE
unsupported url 

### ISSUE THREAD

**Issue by xerexcoded** [ytdl-org/youtube-dl#29482]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.06.06**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

https://yare3.yare.wtf/vidstreaming/animefrenzy/ODgwOTI=
[ytdl_hook] ERROR: Unsupported URL: https://yare3.yare.wtf/vidstreaming/animefrenzy/ODgwOTI=
[ytdl_hook] youtube-dl failed: unexpected error occurred
Failed to recognize file format.
```

## Description

url not supported from site yare3.yare.wtf

**Comment by kikuyan** [comment]
The site doesn't look legal.

**Comment by remitamine** [comment]
https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free
