### ISSUE TITLE
Youtube-dl not working with pycharm

### ISSUE THREAD

**Issue by xSpiderz** [ytdl-org/youtube-dl#29480]
## Checklist

- [X ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

I'm using Pycharm and when I installed youtube-dl it doesn't work with pycharm. It gives the error as if I didn't have it installed.
![image](https://user-images.githubusercontent.com/40403314/124571032-08e37e80-de0d-11eb-8ddf-118e08dd022f.png)

![image](https://user-images.githubusercontent.com/40403314/124571101-1d277b80-de0d-11eb-9efd-0034a9df3fe8.png)

**Comment by rautamiekka** [comment]
Did you `import` ? You aren't showing the full code.

**Comment by xSpiderz** [comment]
Ohh no that's probably it.

**Comment by rautamiekka** [comment]
PyCharm should give you the option to import ytdl, though, but I dunno if it's disabled by default.

**Comment by xSpiderz** [comment]
Yeah it worked thank you but I still have this error with a url

`py
import discord
from discord.ext import commands
import youtube_dl

class music(commands.Cog):
        def __init__(self, client):
            self.client = client

        @commands.command()
        async def join(self,ctx):
            if ctx.author.voice is None:
                await ctx.send("You're not in a voice channel!")
            voice_channel = ctx.author.voice.channel
            if ctx.voice_client is None:
                await voice_channel()
            else:
                    await ctx.voice_client.move_to(voice_channel)

        @commands.command()
        async def leave(self,ctx):
            await ctx.voice_client.dissconnect()

        @commands.command()
        async def play(self,ctx):
            if ctx.author.voice is None:
                await ctx.send("You're not in a voice channel!")
            voice_channel = ctx.author.voice.channel
            if ctx.voice_client is None:
                await voice_channel()
            else:
                    await ctx.voice_client.move_to(voice_channel)
            ctx.voice_vlient.stop()
            FFMPEG_OPTIONS = {'before_options': '-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5', 'options': '-vn'}
            YDL_OPTIONS = {'format':"bestaudio"}
            vc = ctx.voice_client

            with youtube_dl.YoutubeDL(YDL_OPTIONS) as ydl:
                info = ydl.extract_info(url, download=False)
                url2 = info['formats'][0]['url']
                source = await discord.FFmpegOpusAudio.from_probe(url2,**FFMPEG_OPTIONS)
                vc.play(source)

        @commands.command()
        async def pause(self, ctx):
            await ctx.voice_client.pause()
            await ctx.send("Paused :pause_button:")

        @commands.command()
        async def resume(self, ctx):
            await ctx.voice_client.resume()
            await ctx.send("Resume :play_pause:")

        def setup(client):
            client.add_cog(music(client))`

**Comment by xSpiderz** [comment]
![image](https://user-images.githubusercontent.com/40403314/124664907-b1c3c500-de71-11eb-8f05-d0a39cfa61b1.png)

**Comment by rautamiekka** [comment]
If that's all the code, you're indeed missing the definition of `url` which it's complaining about. Judging by the code, you're meant to pass the URL to the script which passes it to ytdl, but the code ain't expecting one in the 1st place. You already got the `__init__` method in the class, so you'll need to assign the URL to it too, then ref it through `self.url` or such.

**On a side note:** your code tag's broken, it's meant to be 3 backticks, then the word `python` with[out] `2` or `3` on the same line without a space, then a newline, the code, and the same 3 on another line.

^ Like this:
````
```python3
def _a():
    pass
```
````

**Comment by AstroTyler** [comment]
I'm having a similar issues also, i tried to execute and it gives the module not found error.
