### ISSUE TITLE
Ask youtube-dl to only use proxy for getting list of formats, not using proxy to download file.

### ISSUE THREAD

**Issue by kietheros** [ytdl-org/youtube-dl#29492]
## Checklist

- [X ] I'm asking a question
- [ X] I've looked through the README and FAQ for similar questions
- [ X] I've searched the bugtracker for similar questions including closed ones

## Question

I'm using this command:
**youtube-dl --proxy ... --external-downloader aria2c ... URL**

Youtube-dl use proxy to get list of formats from youtube. And it also force aria2c to use proxy to download file. Could I ask youtube-dl to only use proxy for getting list of formats.

**Comment by dirkf** [comment]
What happens if you add `--external-downloader-args '--all-proxy=""'` before the URL in your command?

Use of aria2c suggests a POSIX-ish shell. Otherwise (eg, Windows), some different exotic quoting would be needed to pass the empty string `""` to the `--all-proxy` option.

**Comment by kietheros** [comment]
@dirkf 
--external-downloader aria2c --external-downloader-args '--all-proxy=''" -j 16 -x 16 -s 16'
It still use proxy to download file (check by wireshark).

**Comment by kikuyan** [comment]
don't use --proxy option for youtube-dl.
set http_proxy or https_proxy environment variable and run youtube-dl --external-downloader-args '--http-proxy= --https-proxy='

**Comment by kietheros** [comment]
@kikuyan I need use proxy for youtube-dl to bypass some limits.

**Comment by kikuyan** [comment]
> set http_proxy or https_proxy environment variable and run youtube-dl

**Comment by kietheros** [comment]
> > set http_proxy or https_proxy environment variable and run youtube-dl
> 
> Edit: I forgot to mention. Currently, when only http_proxy environment variable is set youtube-dl also uses proxy for https connection. When only https_proxy environment variable is set, http connections are direct.

Your solution works. Thank you very much !
