### ISSUE TITLE
Limit YouTube playlist size

### ISSUE THREAD

**Issue by Inesicen** [ytdl-org/youtube-dl#29514]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Retrieving titles that have been uploaded in the last x days apparently necessitates downloading all playlist data before they can be operated on; this is problematic where a playlist has thousands of titles or one wants to retrieve multiple playlists' data.

**Comment by colethedj** [comment]
`--playlist-end 123` maybe what you are looking for?

**Comment by marium0505** [comment]
Isn't that already possible using one or more of these options:
--playlist-start NUMBER
--playlist-end NUMBER
--playlist-items ITEM_SPEC

And one or more of these:
--date DATE
--datebefore DATE
--dateafter DATE

You can see all options related to video selection here:
https://github.com/ytdl-org/youtube-dl/blob/master/README.md#video-selection

**Comment by Inesicen** [comment]
`--playlist-end` seems to do the trick; thank you!
