### ISSUE TITLE
Integration to HomeBrew Repos?

### ISSUE THREAD

**Issue by BobHood** [ytdl-org/youtube-dl#29536]
## Checklist

- [ X ] I'm reporting a feature request
- [ X ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ X ] I've searched the bugtracker for similar feature requests including closed ones

## Description

Are you going to be integrating with Homebrew? There is already a package there "youtube-downloader". But I don't think it's the same project...

**Comment by llacb47** [comment]
???? https://formulae.brew.sh/formula/youtube-dl

**Comment by pukkandan** [comment]
https://github.com/ytdl-org/youtube-dl#installation

**Comment by FlorianWendelborn** [comment]
I think this issue is actually relevant again as it doesn’t seem to be properly integrated. The last version homebrew knows is from 2021:

![image](https://user-images.githubusercontent.com/1133858/220637542-f69b602a-3182-40a7-a22d-ff5d9a2364b0.png)
