### ISSUE TITLE
Downloads fail from SBS

### ISSUE THREAD

**Issue by ayubowan2u** [ytdl-org/youtube-dl#29541]
## Checklist

- [ x] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by ayubowan2u** [comment]
Issue resolved. The new url format was slightly different to what it used to be. A few days ago the url had the following format

https://www.sbs.com.au/ondemand/video/1911251011518/believe

The new format is
https://www.sbs.com.au/ondemand/movie/believe/1911251011518 - this url does NOT work with youtube-dl and produces the error mentioned above

However, if I use this old format, youtube-dl downloads successfully.

Also, this one works too.

https://www.sbs.com.au/ondemand/watch/1911251011518 which is which is the url that gets displayed when one presses the play button.


Thanks

**Comment by captsens** [comment]
I think I have a fix for this.  I'm about to work out how to submit a pull request - I'll post the link when I've done it.

For those who want to try it in the meantime, and who are comfortable changing a line in a Python file, here's what's required:

- NOTE: I'm doing this on the latest source version from Github. If you're on an earlier version, the line number below may be different
- Find the file youtube_dl/extractor/sbs.py, and open it in a text editor
- Go to line 13 (?) where _VALID_URL is defined
- Change the definition from:
>    _VALID_URL = r'https?://(?:www\.)?sbs\.com\.au/(?:ondemand(?:/video/(?:single/)?|.*?\bplay=|/watch/)|news/(?:embeds/)?video/)(?P<id>[0-9]+)'
- to:
>    _VALID_URL = r'https?://(?:www\.)?sbs\.com\.au/(?:ondemand(?:/movie/.*?/|/video/(?:single/)?|.*?\bplay=|/watch/)|news/(?:embeds/)?video/)(?P<id>[0-9]+)'

**Comment by captsens** [comment]
Pull request submitted.  See #29644

**Comment by ayubowan2u** [comment]
@captsens - thanks very much. I am using the binary so will have to wait for the next update. Thanks again.
