### ISSUE TITLE
ABC Failing

### ISSUE THREAD

**Issue by jriker1** [ytdl-org/youtube-dl#29544]
Always download specific soap operas from ABC and today they won't download.  No change in my process.  Any thoughts?  

Error is:

ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Obviously sounds like it makes sense but that would in theory mean SSO isn't working?

youtube-dl.exe --audio-quality 0 --add-metadata --ap-mso Comcast_SSO --ap-username mylogin --ap-password mypassword https://abc.com/shows/general-hospital/episode-guide/2021-07/13-general-hospital-71321 -o "General Hospital S58E197.mp4"

Here's the verbose info:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--audio-quality', '0', '--add-metadata', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://abc.com/shows/general-hospital/episode-guide/2021-07/13-general-hospital-71321', '-o', 'General Hospital S58E197.mp4', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[Go] 13-general-hospital-71321: Downloading webpage
[Go] VDKA23864036: Downloading JSON metadata
[Go] VDKA23864036: Downloading Provider Redirect Page
[Go] VDKA23864036: Logging in
[Go] VDKA23864036: Retrieving Session
ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\users\jriker.iceo\appdata\local\programs\python\python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by jriker1** [comment]
Not I just updated to the latest version and same deal.  Was able to login with my xfinity account on the website manually.

**Comment by tv21** [comment]
Same issue occurs on Disney Channel shows.

**Comment by tv21** [comment]
Question, is this issue only being seen by Comcast_SSO users or is this affecting everyone?

**Comment by jriker1** [comment]
I can't answer that completely but can say that visually nothing has changed for me.  If I go to ABC and try watching a show it pulls up that matrix of service providers, I click on XFinity, and then have to enter my credentials.

**Comment by WoodpeckerBaby** [comment]
Double check to verify this is not an IP ban issue, e.g., are you using an US IP address? Can you play the video okay in the browser? 

Try this and see if it works
```
youtube-dl --ignore-config "abc.com/shows/2020/episode-guide/2019-11/15-undercover-girlfriend"

```

**Comment by jriker1** [comment]
Not an IP ban.  In the US and can play it thru the browser.

**Comment by 89z** [comment]
@jriker1 looks like the original URL is not longer valid. Do you have a valid example URL?

**Comment by dirkf** [comment]
Page is gone.
Please open a new issue with a valid current URL if the issue persists, referencing this one.
