### ISSUE TITLE
Add support for https://orf.at/

### ISSUE THREAD

**Issue by rubyFeedback** [ytdl-org/youtube-dl#29543]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

Wow guys ... tons of template stuff. Is all of that necessary? 

I mean all I would like to suggest is to add support for an URL such as:

    youtube-dl https://orf.at/stories/zib100?episode=20210714

Right now the error I get is:

    [generic] zib100?episode=20210714: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] zib100?episode=20210714: Downloading webpage
    [generic] zib100?episode=20210714: Extracting information

The website players super-slowly in my palemoon browser which
is why I'd rather want to download it and watch it completely
without jittering. Right now if I try to play it on the website
it jitters.

**Comment by dirkf** [comment]
Video is no longer verfügbar. Please open a new issue for any similar page if required after solving #32789.
