### ISSUE TITLE
Support for 6play.fr is broken

### ISSUE THREAD

**Issue by Jaaa01** [ytdl-org/youtube-dl#29549]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.06.06**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

$ youtube-dl --verbose https://www.6play.fr/enquete-exclusive-p_831/haiti-la-loi-des-gangs-c_12870820
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.6play.fr/enquete-exclusive-p_831/haiti-la-loi-des-gangs-c_12870820']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - SNIPPED
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[6play] 12870820: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/sixplay.py", line 113, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Support for 6play.fr is not working anymore for months.

Same issue reported here:
https://github.com/ytdl-org/youtube-dl/issues/28722

An upgrade to fix support for this site would be very welcome.

Thank you!

**Comment by dirkf** [comment]
The 4 media links provided for the reported URL are DRM-protected: see http://pc.middleware.6play.fr/6play/v2/platforms/m6group_web/services/6play/videos/clip_12870820?csa=5&with=clips. The extractor ignores them but finds no unprotected links and so reports "No video formats found".

DASH: CENC PlayReady

HLS: SampleAES

**Comment by illydone** [comment]
Is there any solution?

I tried to download some series and sometime by checking the source of the page, I can find a working link for an episode but it won't work for next episode. However, when viewing it in a browser it always work, I can watch the whole season...

**Comment by dirkf** [comment]
If you can supply details of an episode for which you can find a working link, someone may be able to investigate how that page is processed and improve the extractor accordingly.

**Comment by dirkf** [comment]
See #24967.
