### ISSUE TITLE
'is_live' in the json dump

### ISSUE THREAD

**Issue by hbtalha** [ytdl-org/youtube-dl#29547]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Why websites like facebook and instagram don't have a 'is_live' info you dump the json file. Is there any specific reason? Because twitter and yotube both have it and they are really handy.

**Comment by dirkf** [comment]
Out of some 775 extractors, 73 mention `is_live`. If Facebook or Instagram use some feature in the web page to indicate live content, someone who cared could extract an `is_live` parameter from that feature.

For instance, it appears that a Facebook live video has this 
```
  'publication': [
    {
      '@type': 'BroadcastEvent',
      'isLiveBroadcast': true,
    ...}
```
in JSON inside a `<script type="application/ld+json" ...>...</script>` element.

**Comment by hbtalha** [comment]
Thanks for the info.

As a side effect question, do you know how one can extract the content of the JSON inside a <script type="application/ld+json" ...>...</script> element.

**Comment by dirkf** [comment]
In a yt-dl extractor, the `_search_json_ld()` and `_json_ld()` methods of `InfoExtractor` are available (`extractor/common.py`).

In a POSIX shell script, you could use `wget` or `curl` together with `grep` or `awk`, and possibly `jq` to parse the JSON.

**Comment by hbtalha** [comment]
I don't speak Python, I am a C++ guy,  I read the code but it was a little too much as it calls a lot of other function that I couldn't quite understand what they were doing.

I would like to use wget, what would be command?

**Comment by dirkf** [comment]
Template:
`wget -O- ...other params... $url | sed -e '...commands to extract the JSON...' | jq '...JSON filter command...'
To work out how to complete the template:
* `man sh`
* `man wget`
* `man sed`
* `man jq`

**Comment by hbtalha** [comment]
I've g searched `sed` and `jq` as I never used them, found a lot of examples with `curl` and `wget` but none for this specific case.
What would be the `sed` commands to extract `<script type="application/ld+json" ...>...</script>` element?
Could you provide one full working example? This is very new to me.
