### ISSUE TITLE
Youtube video time stamps to go to specific topic

### ISSUE THREAD

**Issue by diyaa59** [ytdl-org/youtube-dl#29559]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I just wish if there is a way to download time stamps in a text file. They are something that Youtube added recently so that a user can go to a specific topic in the Video right away.
![image](https://user-images.githubusercontent.com/26883110/125910480-68c1c8db-5e6d-413f-b580-e36ed2628c61.png)
![image](https://user-images.githubusercontent.com/26883110/125910533-c6379a16-2baf-46fc-a2f5-41664c5eba64.png)

As you can see in the picture there are those stamps which lets the user go to a specific topic in the video just by viewing that list. They have been added recently so not every single video on youtube has them.

This would be a nice thing to have if possible.

Thank you kindly and I really appreciate all the hard work that you guys do to make youtube-dl better.

**Comment by e-d-n-a** [comment]
Even better would be to support the creation of MP4s with added chapters.
Common media players like VLC and SMplayer support these chapters!

To add chapter metadata to the downloaded video **ffmpeg can be used**[1][2] with its [metadata file format](https://ffmpeg.org/ffmpeg-formats.html#Metadata-1):
```
;FFMETADATA1
title=bike\\shed
;this is a comment
artist=FFmpeg troll team

[CHAPTER]
TIMEBASE=1/1000
START=0
#chapter ends at 0:01:00
END=60000
title=chapter \#1
[STREAM]
title=multi\
line
```

So YouTube-DL could try to retrieve the timestamps and titles for all available chapters to create such a metadata file.
And ideally you could support adding an optional post-processing step, that adds this data to the output file with:
```
ffmpeg -i INPUT -i FFMETADATAFILE -map_metadata 1 -map_chapters 1 -codec copy OUTPUT
```
([see this](https://superuser.com/questions/1320389/updating-mp4-chapter-times-and-names-with-ffmpeg) for an explanation on the added "-map_chapters" switch)

For manually checking and editing tags and chapters of MP4s there is also a tool called [Drax](https://github.com/stevie910/drax).


[1] https://ikyle.me/blog/2020/add-mp4-chapters-ffmpeg
[2] https://medium.com/@dathanbennett/adding-chapters-to-an-mp4-file-using-ffmpeg-5e43df269687

**Comment by e-d-n-a** [comment]
**YouTube-DL already supports chapters.**

If you just want to be able to see the chapters and jump to the locations in the video just add "--add-metadata" to your command, assuming you're saving the video as an MP4 file.

If you really want to get the info as a separate text file you could extract it from the downloaded video with:
```
ffmpeg -i INPUT -f ffmetadata FFMETADATAFILE
```

In the FFMETADATAFILE you will find a summary of the chapters in the keys "description" or "comment" like this:
```
description=Don't know what its actual name is, so I just threw every word into this video's title and hoped that something stuck.\
0:00 - The new feature\
0:17 - Slow roll-out\
1:16 - How it works\
2:04 - Problems / suggestions for the future
```
(example for [this video](https://www.youtube.com/watch?v=HZTStHzWRxM))

Or you can use **ffprobe** to extract the text you're interested in from the video:
```
ffprobe -v error -hide_banner -of default=noprint_wrappers=1:nokey=1 -sexagesimal -select_streams v:0 -show_entries chapter=start_time:chapter_tags=title VIDEO_FILE
```
which outputs:
```
0:00:00.000000
The new feature
0:00:17.000000
Slow roll-out
0:01:16.000000
How it works
0:02:04.000000
Problems / suggestions for the future
```

or just:
```
ffprobe -v error -hide_banner -of default=noprint_wrappers=1:nokey=1 -sexagesimal -select_streams v:0 -show_entries format_tags=description VIDEO_FILE
```
which outputs:
```
Don't know what its actual name is, so I just threw every word into this video's title and hoped that something stuck.
0:00 - The new feature
0:17 - Slow roll-out
1:16 - How it works
2:04 - Problems / suggestions for the future
```

If you don't want to download the video, you can also only retrieve and save the info-json:
```
youtube-dl --write-info-json --skip-download YOUTUBE_LINK
```
,which includes the chapter information like this:
```
    "chapters": [
        {
            "start_time": 0.0,
            "end_time": 17.0,
            "title": "The new feature"
        },
        {
            "start_time": 17.0,
            "end_time": 76.0,
            "title": "Slow roll-out"
        },
        {
            "start_time": 76.0,
            "end_time": 124.0,
            "title": "How it works"
        },
        {
            "start_time": 124.0,
            "end_time": 180,
            "title": "Problems / suggestions for the future"
        }
```

**Comment by diyaa59** [comment]
Thank you @e-d-n-a
