### ISSUE TITLE
XHamster webpage 403

### ISSUE THREAD

**Issue by Briefkasten24** [ytdl-org/youtube-dl#29560]
- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', 'C:\\FFmpeg for Audacity', '--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://de.xhamster.com/videos/may-20-xhP64Ip']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2.2.2
[debug] Proxy map: {}
[XHamster] xhP64Ip: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\users\X\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\X\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\X\appdata\local\programs\python\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\users\X\appdata\local\programs\python\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\users\X\appdata\local\programs\python\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\users\X\appdata\local\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\users\X\appdata\local\programs\python\python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

## Description
Hi, i am currently using youtube-dl 2021.06.06.. As i've tried downloading a video, that is only available to "friends" of a particular account, i've naturally tried using the -u and -p arguments when calling youtube-dl, but i've not had any luck with any video so far. 
Publicly available Videos are no problem and download just fine. 
To my knowledge there's no comparable ticket open at the time - i hope my search of an open issue was thorough.
Please let me know if i can provide you with more information or if i can be of any more help. Thanks for your effort!

**Comment by october262** [comment]
try using the cookies.txt file command.

**Comment by Briefkasten24** [comment]
> try using the cookies.txt file command.

That solved it. I used the "get cookies.txt" extension for chrome. 

Thanks buddy!
