### ISSUE TITLE
SBS download error

### ISSUE THREAD

**Issue by Brissyite** [ytdl-org/youtube-dl#29587]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PS C:\ytdl> ./youtube-dl -v https://www.sbs.com.au/ondemand/video/1914668099606/grand-tours-of-scotlands-lochs-s4-ep1-where-myths-are-made -o "C:\Users\Greg Lindner\Videos\YTDLFiles\%(title)s-%(id)s.%(ext)s"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.sbs.com.au/ondemand/video/1914668099606/grand-tours-of-scotlands-lochs-s4-ep1-where-myths-are-made', '-o', 'C:\\Users\\Greg Lindner\\Videos\\YTDLFiles\\%(title)s-%(id)s.%(ext)s']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2021-01-26-essentials_build-www.gyan.dev, ffprobe 4.3.1-2021-01-26-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[SBS] 1914668099606: Downloading JSON metadata
[ThePlatform] v_HVUpodQ_p1: Downloading SMIL data
[ThePlatform] v_HVUpodQ_p1: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\theplatform.py", line 309, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## SBS download error

I'm new here and as far as I can tell I have completed all the items on the check list correctly.
I have downloaded files from SBS before without issue but now can no longer do so. The output says to report this as a bug and so that is what I am doing.

**Comment by bnw42** [comment]
Confirming the issue. SBS appear to have reorganised their server. Video Download Helper reports a typical working url as: 
https://dai.google.com/ondemand/hls/content/2488267/vid/1914668099574/SIN/streams/db2a9f1f-57e4-4752-b6bd-b9f40a7b0262/media/281dd385dae3d96cede76042fd7753ab.m3u8
The resulting url has a lower resolution than what was available as recently as sunday, includes adverts in the downloaded video, but the download plays without glitches.

**Comment by ayubowan2u** [comment]
I thought I got this sorted out a couple of days ago - see https://github.com/ytdl-org/youtube-dl/issues/29541 but it looks like they have made more changes.

My output on Linux is

youtube-dl -u my-user-id -p my-passwd https://www.sbs.com.au/ondemand/video/1482360899943/maudie
[SBS] 1482360899943: Downloading JSON metadata
[ThePlatform] JZskJKkgxz0D: Downloading SMIL data
[ThePlatform] JZskJKkgxz0D: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
guptila@stream:~$ youtube-dl -u gdesilva -p 23S56S23S --verbose https://www.sbs.com.au/ondemand/video/1482360899943/maudie
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--verbose', u'https://www.sbs.com.au/ondemand/video/1482360899943/maudie']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-77-lowlatency-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[SBS] 1482360899943: Downloading JSON metadata
[ThePlatform] JZskJKkgxz0D: Downloading SMIL data
[ThePlatform] JZskJKkgxz0D: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 309, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by phiali** [comment]
From what I can tell SBS now require you to login to view and download videos. I wanted to add in login support to extractor/sbs.py, but wasn't too sure how to ensure that the bearer token is passed down to other parts.

To login one has to POST to https://www.sbs.com.au/api/v3/janrain/auth_native_traditional?context=odwebsite with form-data of user, pass, and express set to 1. From there we need ["user_state"]["sessiontoken"].

By the looks of it this sessiontoken needs to be sent as a HTTP Bearer when requesting videos. The request to download the JSON from http://www.sbs.com.au/api/video_pdkvars/id/%s?form=json doesn't seem to require the bearer token. I imagine that the extracted URLs need it though.

**Comment by bnw42** [comment]
The need to login may be required, but I suspect there's more to it. Even logging in, the video frame no longer shows up on the page, rather you have to click a link to play it. YT-DL would need to be able to get the show identifier and convert that into a downloadable URL and the format of those have changed.

I've been able to get a video URL from the website (after logging in) using VDH and successfully using that URL without a login/pwd in yt-DL. The resulting file has a lower resolution, but the same file size as a copy d/l last week, and when I run it thru' a video editor, it comes out as 1280x720 without having to specify the output framesize. So possibly yet something else going on in addition to the login creds & video URL change, else SBS has been faking the 1280x720 resolution all along.

A similar thing happened with 10-play earlier this year, although they did the change to the URL format and then a few months later added login requirements. SBS has done it all at once.

**Comment by bnw42** [comment]
The lack of a yt-dl update in well over a month is concerning, so I had a look for yt-dl forks that are still being maintained. You can try this one: https://github.com/yt-dlp/yt-dlp. It combines fixes, updates etc published for youtube-dl, youtube-dlc (now abandoned), plus their own. Available as the uncompiled code, also as binaries (here https://github.com/yt-dlp/yt-dlp/releases/tag/2021.07.07).

I tossed a url from SBS ondemand at yt-dlp.exe and it worked perfectly WITHOUT the need for logging in either on the browser to get the url or in yt-dlp.exe. It also works with the old format url's. So it appears the current issue with YT-DL is not one of needing to log in, rather it's due to changes in the actual video URLs.

**Comment by phiali** [comment]
You're right, I just tried a download in https://github.com/yt-dlp/yt-dlp/releases/tag/2021.07.07 and it worked fine. Apologies for confusing things with the login requirement. So much change all at once.

**Comment by bnw42** [comment]
No worries. yt-dlp is based on the 6/6 release of yt-dl, which is failing with SBS, and there's no recent issue posted for SBS with yt-dlc, so no idea why yt-dlc is working and yt-dl isn't since the SBS changes were after the 6/6. Just grateful it works!

**Comment by losuler** [comment]
I actually think something changed on their end again because `youtube-dl` is working now, when it wasn't last night.

**Comment by Sal-Ammonite** [comment]
Just stumbled across this issue. Some additional info which may provide clues:

- Without logging in to SBS OD, I copied the URL from the "Play" button of a single episode of a fairly newly-released series (no names, but it's about a hard-bitten LA detective). URL is in the usual format "https://www.sbs.com.au/ondemand/video/[UNIQUE_ID_#]/[SERIESNAME_NUM_EP_EPTITLE]"
- Using current yt-dl 2021.06.06 with that URL, it failed
- In browser, clicked the Play button in browser. Login overlay appeared, but could close that & get to episode page. Clicked play button again, got login overlay again, closed overlay.
- Trying yt-dl again using the same URL, it now works.
- Subsequent episodes now download too without the whole 'click past login' thing...

A possibly-relevant point: browser & yt-dl are running on 2 different machines (browser on macbook, yt-dl on a debian fileserver). Both are on the same LAN, but double-NAT'd to the internet (local NAT in router, CG-NAT at ISP).

Thoughts: is it possible that either SBS has rolled back some changes in the last hour or so & yt-dl now works when it didn't earlier this morning, or maybe they're caching 'allowed' IP's?

**Comment by bnw42** [comment]
Strange, strange and stranger. I tried a url that did NOT work last night (http://www.sbs.com.au/ondemand/video/1914668099606) and it works now, so it may have just been a glitch with SBS.

**Comment by Brissyite** [comment]
Thanks everyone. I saw that some were saying the downloads from SBS were now working, so I just tried again and voila!, the episode downloaded. I am in no way an expert in these things, I learn these things by example, so once something goes wrong, I have no idea how to fix it. Thanks again.

**Comment by ayubowan2u** [comment]
Yes, confirming my download works now. Appears some problem at their end. Thanks everyone!
