### ISSUE TITLE
[YouTube] subtitle format inconsistent

### ISSUE THREAD

**Issue by drorpa** [ytdl-org/youtube-dl#29582]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
~  youtube-dl -v --skip-download --write-auto-sub https://www.youtube.com/watch\?v\=-bt_y4Loofg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--skip-download', '--write-auto-sub', 'https://www.youtube.com/watch?v=-bt_y4Loofg']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Linux-5.8.0-59-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] -bt_y4Loofg: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: MongoDB in 100 Seconds--bt_y4Loofg.en.vtt

```

### The Video
https://www.youtube.com/watch?v=-bt_y4Loofg

### The Problem
Each time i try to download the subtitles for this video, i get one of two differently formatted files. I added examples for the results in the attached file.
not sure if related to the issue, the video only has Russian auto-generated subtitles, but the content looks mostly in English (and unrelated to the video)

[subtitles.zip](https://github.com/ytdl-org/youtube-dl/files/6835773/subtitles.zip)

**Comment by kikuyan** [comment]
This seems to be a problem of YouTube, not youtube-dl.

I opened your video URL in Firefox and from the video Settings, selected Russian (auto-generated) and then Auto-translate English. Subtitles shown is the same as your '2-MongoDB in 100 Seconds--bt_y4Loofg.en.vtt' and --write-auto-sub.

**Comment by drorpa** [comment]
ok, thanks
