### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#29597]
Hi. My name is Peter and I write to say that I have used your programme for a while now and LOVE it. I do thing that I contributed originally, but I honestly can't remember. If I paid for it, I can't remember. I feel that I should donate upon moral, usage and admiration grounds.
Is there a requirement and path for this?
Cheers,
Peter Kelly (Australia)

**Comment by hockdudu** [comment]
They had a donate page, but it was apparently removed for legal concerns. See https://github.com/ytdl-org/youtube-dl/commit/ed3623e79461eb7a2ba23c6d51c9a7b14f8a7166.

**Comment by dirkf** [comment]
Duplicate of #5945.
