### ISSUE TITLE
TikTok not more working / Name or service not known 

### ISSUE THREAD

**Issue by Hafevevhe** [ytdl-org/youtube-dl#29591]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.06.06**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://vt.tiktok.caom/ZGJBw6W9t/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.9 (CPython) - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8
[debug] exe versions: none
[debug] Proxy map: {}
[generic] ZGJBw6W9t: Requesting header
WARNING: Could not send HEAD request to https://vt.tiktok.caom/ZGJBw6W9t/: <urlopen error [Errno -2] Name or service not known>
[generic] ZGJBw6W9t: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2737, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)

Hi! Since today I got over 35.000 Errors while Downloading TikTok Videos. Almost every video is not working. But only with vt.tiktok.com or vm.tiktok.com url. Urls which starts with (https://www.tiktok.com/@p1zzakarton1/video/6986192558028262662?sender_device=pc&sender_web_id=6986497916870870533&is_from_webapp=v1&is_copy_url=0) works perfectly.
I checked already - this type of shortuls is provided by the TikTok apps (Android, iOS) when you click copy link)
Can somebody help?

**Comment by kikuyan** [comment]
Re-check your url.

**Comment by Hafevevhe** [comment]
> Re-check your url.

Sorry, here is another one. I have now over 50k errors within 2 days at my TikTok downloader. And it worked before over 1 year. So there must be something new. 


[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://vt.tiktok.com/ZGJBEUNcK/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.9 (CPython) - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8
[debug] exe versions: none
[debug] Proxy map: {}
[generic] ZGJBEUNcK: Requesting header
[redirect] Following redirect to https://www.tiktok.com/
[generic] www.tiktok: Requesting header
WARNING: Falling back on generic information extractor.
[generic] www.tiktok: Downloading webpage
[generic] www.tiktok: Extracting information
ERROR: Unsupported URL: https://www.tiktok.com/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2503, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2571, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2560, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 6, column 10188
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.tiktok.com/

**Comment by kikuyan** [comment]
The url https://vt.tiktok.com/ZGJBEUNcK/ is just redirected to https://www.tiktok.com/. Nothing can be done, not related to youtube-dl.
I advise you to close this issue once.

**Comment by kikuyan** [comment]
The url https://vt.tiktok.com/ZGJBEUNcK/ is just redirected to https://www.tiktok.com/. Nothing can be done, not related to youtube-dl.

**Comment by llacb47** [comment]
Yes, tiktok deletes short urls from its database when a year or around that time has passed since they were created. Bad for archival, but nothing can be done about it.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/23264
https://github.com/ytdl-org/youtube-dl/issues/28741

https://github.com/ytdl-org/youtube-dl/issues/29591
https://github.com/ytdl-org/youtube-dl/issues/29849

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30251
