### ISSUE TITLE
Getting the error: "ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

### ISSUE THREAD

**Issue by MoaadLala** [ytdl-org/youtube-dl#29607]
I have been trying to setup a python server, that uses youtube-dl, the script on my machine (on localhost) is working, but on the server, it doesn't, i made sure that am using the same versions as in my linux machine (youtube-dl 2021.6.6, flask 2.0.1, flask-cors 3.0.10, python 3.8), is there a way to solve this issue?
Thanks to anyone who helps to solve this annoying bug..

**Comment by dirkf** [comment]
Even though you put the instructions in the issue title, we don't see the "complete output" requested.

No doubt the environment in which the server is running yt-dl is different from that on your Linux machine. The verbose log from the server instance will likely make this clear.

**Comment by MoaadLala** [comment]
So like I said, am using it with python, how can I add the verbose flag there?
Thank you for answering

**Comment by kikuyan** [comment]
If you are using [EMBEDDING YOUTUBE-DL](https://github.com/ytdl-org/youtube-dl#embedding-youtube-dl), add `'verbose': True,` to the options. 
And please show the whole options, urls and the logs.

**Comment by MoaadLala** [comment]
For some reason, after adding the `'verbose': True` to my options, it work now works...
Thank you so much for helping, i really appreciate it.

This is what i got back from my linux machine (localhost), which works fine: 

 * Serving Flask app 'main' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [22/Jul/2021 14:31:32] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [22/Jul/2021 14:31:32] "GET /favicon.ico HTTP/1.1" 404 -
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Linux-5.8.0-59-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] orJSJGHjBLI: Downloading webpage
[youtube] orJSJGHjBLI: Downloading player 3804dce2
127.0.0.1 - - [22/Jul/2021 14:31:59] "GET /audio?link=https://www.youtube.com/watch?v=orJSJGHjBLI HTTP/1.1" 200 -


This is what i got back from my Flask server (python): 

2021-07-22 12:35:25,701: [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
2021-07-22 12:35:25,701: [debug] youtube-dl version 2021.06.06
2021-07-22 12:35:25,761: [debug] Python version 3.8.5 (CPython) - Linux-5.4.0-1038-aws-x86_64-with-glibc2.29
2021-07-22 12:35:26,370: [debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
2021-07-22 12:35:26,371: [debug] Proxy map: {'http': 'http://proxy.server:3128', 'https': 'http://proxy.server:3128', 'no': 'localhost,127.0.0.1,localaddress,.localdomain.com,/var/run/docker.sock'}

**Comment by MoaadLala** [comment]
So, apparently it works with some videos while it doesn't with others, is there a way around this?

**Comment by dirkf** [comment]
Show the full verbose output from a successful and a failing video.
