### ISSUE TITLE
[YouTube] Different dates for some videos

### ISSUE THREAD

**Issue by MichalSuchy** [ytdl-org/youtube-dl#29606]
Hello. When I download videos from Youtube, so some videos have different dates. It is date of change in computer and creation date on Youtube. Dates of change in computer are other, than creation dates on Youtube. Can you correct this issue, please? Thanks, Michal.

**Comment by kikuyan** [comment]
Please provide the verbose logs and dates.

**Comment by MichalSuchy** [comment]
How can I create required logs and dates, please?

**Comment by kikuyan** [comment]
`-v` option for verbose logs, and please explain date _abc_ should be _xyz_, etc.

**Comment by rautamiekka** [comment]
There's a template with precise instructions when you create a new one.
