### ISSUE TITLE
Motherless ERROR: Unable to extract uploader_id

### ISSUE THREAD

**Issue by amidis-atria** [ytdl-org/youtube-dl#29626]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '-ciw', '--verbose', 'https://motherless.com/0EBC4FA']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-05-22-38490cb, ffprobe git-2020-05-22-38490cb
[debug] Proxy map: {}
[Motherless] 0EBC4FA: Downloading webpage
ERROR: Unable to extract uploader_id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\motherless.py", line 131, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader_id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

I ran the command:
youtube-dl -f best -ciw --verbose "https://motherless.com/0EBC4FA"
And got the error as written above.

**Comment by dirkf** [comment]
At lines 129ff. of `extractor/motherless.py`
```
        uploader_id = self._html_search_regex(
            r'"thumb-member-username">\s+<a href="/m/([^"]+)"',                 
            webpage, 'uploader_id')                                      
```
the final line should be
```
            webpage, 'uploader_id', fatal=False)
```
to prevent this, while still retrieving the requested video.

For an improved version, we could also look for the `uploader_id` in page fragment `<span class="username">...</span>` and get resolution from the `data-quality` attribute of the `<video>` tag. Possibly use the `_parse_html5_media_entries()` method.

**Comment by Jorge9811** [comment]
> 
> ## Checklist
> 
>     * [x]  I'm reporting a broken site support
> 
>     * [x]  I've verified that I'm running youtube-dl version **2021.06.06**
> 
>     * [x]  I've checked that all provided URLs are alive and playable in a browser
> 
>     * [x]  I've checked that all URLs and arguments with special characters are properly quoted or escaped
> 
>     * [x]  I've searched the bugtracker for similar issues including closed ones
> 
> 
> ## Verbose log
> 
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['-f', 'best', '-ciw', '--verbose', 'https://motherless.com/0EBC4FA']
> [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
> [debug] youtube-dl version 2021.06.06
> [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
> [debug] exe versions: ffmpeg git-2020-05-22-38490cb, ffprobe git-2020-05-22-38490cb
> [debug] Proxy map: {}
> [Motherless] 0EBC4FA: Downloading webpage
> ERROR: Unable to extract uploader_id; please report this issue on [yt-dl.org/bug](https://yt-dl.org/bug) . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
> File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
> File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
> File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
> File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\motherless.py", line 131, in _real_extract
> File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
> File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
> youtube_dl.utils.RegexNotFoundError: Unable to extract uploader_id; please report this issue on [yt-dl.org/bug](https://yt-dl.org/bug) . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> ## Description
> 
> I ran the command:
> youtube-dl -f best -ciw --verbose "[motherless.com/0EBC4FA](https://motherless.com/0EBC4FA)"
> And got the error as written above.

same

**Comment by daaav-id** [comment]
@dirkf `username` is a good idea.

This patch works for me

```
diff --git a/youtube_dl/extractor/motherless.py b/youtube_dl/extractor/motherless.py
index ef1e081f2..3e244caf1 100644
--- a/youtube_dl/extractor/motherless.py
+++ b/youtube_dl/extractor/motherless.py
@@ -127,7 +127,7 @@ class MotherlessIE(InfoExtractor):

         comment_count = webpage.count('class="media-comment-contents"')
         uploader_id = self._html_search_regex(
-            r'"thumb-member-username">\s+<a href="/m/([^"]+)"',
+            r'<span class=\"username\">([^"]+)<\/span>',
             webpage, 'uploader_id')

         categories = self._html_search_meta('keywords', webpage, default=None)
```

**Comment by Vangelis66** [comment]
Should be closed, as completed by 82e4eca711 : 
```
youtube-dl -v "https://motherless.com/0EBC4FA" => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://motherless.com/0EBC4FA']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2022.10.11.1919
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 5.0, ffprobe 5.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[Motherless] 0EBC4FA: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://cdn5-videos.motherlessmedia.com/videos/0EBC4FA.mp4'
[download] Destination: Dos sementales follan con potencia a la joven rusa Felecia.mp4-0EBC4FA.mp4
[download]   5.9% of 100.29MiB at 254.50KiB/s ETA 06:19
ERROR: Interrupted by user
```

**Comment by evrial** [comment]
Could you please fix the DL speed of 80kbps reported YEAR ago instead of this pathetic trash

**Comment by dirkf** [comment]
Fixed every time...
```
  youtube_dl/jsinterp.py
commit 7009bb9f3182449ae8cc05cc28b768b63030a485
Author: pukkandan <pukkandan.ytdlp@gmail.com>
Date:   Fri Sep 2 20:41:39 2022 +0530

    [jsinterp] Workaround operator associativity issue
    * temporary fix for player 5a3b6271 [1]
    
    1. https://github.com/yt-dlp/yt-dlp/issues/4635#issuecomment-1235384480

commit 55c823634db890a328ffc23588fcd6f35d9b3ddf
Author: dirkf <fieldhouse@gmx.net>
Date:   Wed Aug 31 23:22:48 2022 +0100

    [jsinterp] Handle new YT players 113ca41c, c57c113c
    * add NaN
    * allow any white-space character for `after_op`
    * align with yt-dlp f26af78a8ac11d9d617ed31ea5282cfaa5bcbcfa (charcodeAt and bitwise overflow)
    * allow escaping in regex, fixing player c57c113c

commit 4c6fba37650d60acbd32a9f2d6e2468a730d0f1c
Author: dirkf <fieldhouse@gmx.net>
Date:   Fri Aug 26 08:17:54 2022 +0100

    [jsinterp] Improve try/catch/finally support

commit d619dd712f63aab1964f8fdde9ceea514a5e581d
Author: dirkf <fieldhouse@gmx.net>
Date:   Thu Aug 25 12:16:10 2022 +0100

    [jsinterp] Fix bug in operator precedence
    * from https://github.com/yt-dlp/yt-dlp/commit/164b03c4864b0d44cfee5e7702f7c2317164a6cf
    * added tests

commit 573b13410e5c2f939676116e2700ec8efd9cf97b
Author: dirkf <fieldhouse@gmx.net>
Date:   Thu Aug 25 12:14:59 2022 +0100

    [YouTube] Improve error check for n-sig processing

commit 46b8ae2f520c17aaa756082676788c6287b6809e (masterGHdf/dlp-jsinterp-ovrhaul, dlp-jsinterp-ovrhaul)
Author: dirkf <fieldhouse@gmx.net>
Date:   Fri Aug 19 15:34:33 2022 +0100

    [jsinterp] Clean up and pull yt-dlp style
    * add compat_re_Pattern
    * improve compat_collections_chain_map
    * use class JS_Undefined
    * remove unused code

commit 538ec65ba7634bb9ad9f8eb4ce72713c673969dc
Author: dirkf <fieldhouse@gmx.net>
Date:   Fri Aug 19 11:45:04 2022 +0100

    [jsinterp] Handle regexp literals and throw/catch execution (#31182)
    
    * based on https://github.com/yt-dlp/yt-dlp/commit/f6ca640b122239d5ab215f8c2564efb7ac3e8c65, thanks pukkandan
    * adds parse support for regexp flags

commit b0a60ce2032172aeaaf27fe3866ab72768f10cb2
Author: dirkf <fieldhouse@gmx.net>
Date:   Wed Aug 17 14:22:02 2022 +0100

    [jsinterp] Improve JS language support (#31175)
    
    * operator ??
    * operator ?.
    * operator **
    * accurate operator functions
    * `undefined` handling
    * object literals {a: 1, "b": expr}
    * more tests for weird JS comparisons: see https://github.com/ytdl-org/youtube-dl/issues/31173#issuecomment-1217854397.

commit d231b56717c73ee597d2e077d11b69ed48a1b02d
Author: dirkf <fieldhouse@gmx.net>
Date:   Sun Aug 14 18:45:45 2022 +0100

    [jsinterp] Overhaul JSInterp to handle new YT players 4c3f79c5, 324f67b9 (#31170)
    
    * back-port from yt-dlp 8f53dc44a0cc1c2d98c35740b9293462c080f5d0, thanks pukkandan
    * also support void, improve <</>> precedence, improve expressions in comma-list
    * add more tests

commit 187a48aee29847664e0c4cd80fe90c32e1fb334b
Author: dirkf <fieldhouse@gmx.net>
Date:   Tue May 24 15:33:00 2022 +0100

    [YouTube] Handle player c5a4daa1 with indirect n-function definition
    
    * resolves #30976

commit a0068bd6bec16008bda7a39caecccbf84881c603
Author: dirkf <fieldhouse@gmx.net>
Date:   Fri Apr 15 16:07:09 2022 +0100

    [Youtube] Fix "n" descrambling for player fae06c11
    
    Resolves #30856.

commit 78ce962f4fe020994c216dd2671546fbe58a5c67
Author: pukkandan <pukkandan.ytdlp@gmail.com>
Date:   Sun Jan 30 01:24:09 2022 +0530

    [youtube] Support channel search
    
    Code from https://github.com/yt-dlp/yt-dlp/commit/cd684175adbe663bbdf6a6c72d8b99b617b6ff2e

commit 41f0043983c831b7c0c3614340d2f66ec153087b
Author: dirkf <fieldhouse@gmx.net>
Date:   Tue Feb 1 23:22:57 2022 +0000

    Avoid crashing if n-sig decode fails

commit 1e677567cd083d43f55daef0cc74e5fa24575ae3
Author: dirkf <fieldhouse@gmx.net>
Date:   Tue Feb 1 14:39:03 2022 +0000

    [YouTube] Fix n-sig for player e06dea74 (#30582)
    
    From yt-dl commit 48416bc

commit af9e72507ea38e5ab3fa2751ed09ec88021260cb
Author: df <fieldhouse@gmx.net>
Date:   Mon Nov 1 04:45:42 2021 +0000

    Implement n-param descrambling using JSInterp
    
    Fixes #29326, closes #29790, closes #30004, closes #30024, closes #30052,
    closes #30088, closes #30097, closes #30102, closes #30109, closes #30119,
    closes #30125, closes #30128, closes #30162, closes #30173, closes #30186,
    closes #30192, closes #30221, closes #30239, closes #30539, closes #30552.

commit 6ca7b776965ed1e9220690edc4ee22de8c8587f5
Author: dirkf <fieldhouse@gmx.net>
Date:   Fri Dec 10 19:14:54 2021 +0000

    Refactor JSInterpreter._separate
    
    yt-dlp/yt-dlp/@06dfe0a, improve _MATCHING_PARENS

commit 9d142109f445ea247e476cfc0e0ca134f6ebb802
Author: dirkf <fieldhouse@gmx.net>
Date:   Sat Nov 27 03:18:29 2021 +0000

    Back-port test_youtube_signature.py from yt-dlp and fix JSInterp accordingly

commit 1ca673bd98cc5bbfa76d00ac84ad5f6c1376db01
Author: dirkf <fieldhouse@gmx.net>
Date:   Sat Nov 27 02:06:13 2021 +0000

    Fix splice to handle float
    
    Needed for new youtube js player f1ca6900
    Add https://github.com/yt-dlp/yt-dlp/commit/57dbe8077f8d00e0fffac53669f40cd7d584474f#diff-729b57caa8d006426f6a8960c061f519a8b6658682284015e069745af52ffb07

commit e1eae16b56b5c57e341b000167c0a92e67095e6e
Author: df <fieldhouse@gmx.net>
Date:   Thu Nov 4 12:48:06 2021 +0000

    Handle default in switch better
    
    Add https://github.com/yt-dlp/yt-dlp/commit/a1fc7ca0743c8df06416e68ee74b64e07dfe7135
    Thanks coletdjnz

commit 96f87aaa3b34d80bc72097a7475d8093849091fc
Author: df <fieldhouse@gmx.net>
Date:   Tue Nov 2 11:18:39 2021 +0000

    Back-port JS interpreter upgrade from yt-dlp PR #1437
```

**Comment by evrial** [comment]
It's fixed in yt-dlp but not backported

**Comment by evrial** [comment]
Or maybe you need to make a release?

**Comment by dirkf** [comment]
No, those are the back-porting commits that I listed. The files in yt-dlp are `.../yt_dlp/...`. Eg, https://github.com/ytdl-org/youtube-dl/issues/30363#issuecomment-996226518. Maybe read around https://github.com/ytdl-org/youtube-dl/issues/31032#issuecomment-1158490846 ?

**Comment by evrial** [comment]
Latest release is youtube-dl 2021.12.17
Only small number of people using git HEAD
