### ISSUE TITLE
Support for sexycandidgirls.com

### ISSUE THREAD

**Issue by earthyrock** [ytdl-org/youtube-dl#29628]
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

```
Color me stupid, once run in verbose mode -v, where do the youtube-dl logs save to??? Sorry.
```
Longtime user of the application; works beautifully across any number of sites. Don't believe sexycandidgirls.com (SCG) is supported (yet). Any attempt at any related SCG link fails. example:
https://sexycandidgirls.com/hot-legs-girl-on-the-train-finally-busted

Thanks for any reply/assistance. ;)

**Comment by ottersarecool** [comment]
The problem is, the file is not hosted on sexycandidgirls.com but instead on dood.la and they require a captcha

**Comment by rochdi-fatcom** [comment]
## [👉👉Directly from here](https://securecd-smrtnd.com/s?a=256440&sm=46517&co=316585&mt=5)
## [👉👉Directly from here](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## Directly
