### ISSUE TITLE
Questioning the hypocrisy of youtube-dl's policy.

### ISSUE THREAD

**Issue by ArjixWasTaken** [ytdl-org/youtube-dl#29631]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Um, according to this
![image](https://user-images.githubusercontent.com/53124886/126795826-7366aa44-d058-43f1-9d35-54c1d1bc2316.png)

youtube-dl doesn't allow copyright infringing websites.

What a load of bullshit.
Take a look at the porn sites that youtube-dl supports.
90% of them are copyright infringing.

You should either remove support for those sites, or get rid of that rule.
Else you are just spewing a bunch of bullshit.

**Comment by ArjixWasTaken** [comment]
It's entirely possible that those sites were added before that policy came out.
But my question still stands, why are you keeping illegal sites when the policy says not to?

**Comment by triplesixman** [comment]
What the hell is this? On the one hand, who says that 100% of the videos on these platforms are copyrighted?

Also, are you aware that there is "private copy" in some countries that allow downloading protected content?

I think you've wasted time playing lawyer. Delete your post.

**Comment by ArjixWasTaken** [comment]
> who says that 100% of the videos on these platforms are copyrighted OR that the platforms are illegal

I didn't say that, don't twist my words, indeed not all the videos on those platforms are copyrighted, thats true.
But it doesn't change the fact that those platforms serve copyrighted material that they don't own.
And let's not even mention the illegal porn that can be found there as well.
Like child abuse, rape and stuff.

> Do you have any relevant evidence before you spew your hate here??

I have eyes and a common sense, something you don't seem to possess, it doesn't take long to find illegal/copyrighted material on most of the porn sites that youtube-dl supports. (notice how I did not say that all of those sites are like this)

> I think you've wasted time playing lawyer.

First of all, I never intended to talk on legal terms, as the title says, I'm questioning the hypocritic behavior of having such a policy and not following it (pun intended).

> Delete your post.

And no, I won't take down this issue, this is an important topic that shouldn't be ignored.

**Comment by 07416** [comment]
The adult sites supported presumably obey legal takedown requests, the infringing videos are uploaded by the users, not necessarily different from Youtube.

**Comment by ArjixWasTaken** [comment]
> The adult sites supported presumably obey legal takedown requests, the infringing videos are uploaded by the users, not necessarily different from Youtube.

The difference between youtube and those porn sites is that youtube either takes down the video or gives the financial earnings that video made to the copyright holder.

Those porn sites don't do that.

**Comment by mechalincoln** [comment]
Reverend Lovejoy's wife called.

Nice rant.

**Comment by marium0505** [comment]
So... with that logic the same should be said about a lot of other sites.... basically all sites where users can upload stuff such as, but not limited to YouTube, Dailymotion etc. 

There are a lot of copyrighted content on both YouTube and Dailymotion that has been there for years (and are completely available to everyone). Yes, some videos are restricted by region, but far from all videos with copyrighted content. 
As you said yourself, you just have to look. 

To be honest, it's a bit insane that both YouTube and Dailymotion has so much copyrighted content that never gets removed.

**Comment by marium0505** [comment]
So... with that logic the same should be said about a lot of other sites.... basically all sites where users can upload stuff such as, but not limited to YouTube, Dailymotion etc. 

There are a lot of copyrighted content on both YouTube and Dailymotion that has been there for years (and are completely available to everyone). Yes, some videos are restricted by region, but far from all videos with copyrighted content. 
As you said yourself, you just have to look. 

And yes, some videos with copyrighted contents gets removed (quickly), but far from all. Some stuff gets removed years after it was uploaded, and some never. Does that mean we should remove the site from Youtube-DL? Just because the site has content that is copyrighted and that hasn't been removed yet? 

To be honest, it's a bit insane that both YouTube and Dailymotion has so much copyrighted content that never gets removed. 
I've personally watched quite a lot of shows on both sites that are copyrighted but still fully available.

**Comment by ArjixWasTaken** [comment]
> So... with that logic the same should be said about a lot of other sites.... basically all sites where users can upload stuff such as, but not limited to YouTube, Dailymotion etc.
> 
> There are a lot of copyrighted content on both YouTube and Dailymotion that has been there for years (and are completely available to everyone). Yes, some videos are restricted by region, but far from all videos with copyrighted content.
> As you said yourself, you just have to look.
> 
> And yes, some videos with copyrighted contents gets removed (quickly), but far from all. Some stuff gets removed years after it was uploaded, and some never. Does that mean we should remove the site from Youtube-DL? Just because the site has content that is copyrighted and that hasn't been removed yet?
> 
> To be honest, it's a bit insane that both YouTube and Dailymotion has so much copyrighted content that never gets removed.
> I've personally watched quite a lot of shows on both sites that are copyrighted but still fully available.

Yes, my initial claim is not that strong, but on my reply to @triplesixman I addressed another issue, illegal content, not copyright infringing, child abuse and such.
But oh well, this is irrelevant to my argument.

**Comment by ArjixWasTaken** [comment]
> I've personally watched quite a lot of shows on both sites that are copyrighted but still fully available. A lot of it was uploaded more years ago. So no, neither Dailymotion nor YouTube removes (all) videos with copyrighted content.

But the copyright holder can still take down those videos or send a copyright strike to get money out of the videos.
Yes, youtube on its own doesn't do it, but it leaves the window of opportunity open for the copyright holder.

**Comment by ArjixWasTaken** [comment]
Anyways, this whole repo is hypocritic if you look at the policy, this was intended to be a joke but I guess I was too serious.

**Comment by marium0505** [comment]
> > So... with that logic the same should be said about a lot of other sites.... basically all sites where users can upload stuff such as, but not limited to YouTube, Dailymotion etc.
> > There are a lot of copyrighted content on both YouTube and Dailymotion that has been there for years (and are completely available to everyone). Yes, some videos are restricted by region, but far from all videos with copyrighted content.
> > As you said yourself, you just have to look.
> > And yes, some videos with copyrighted contents gets removed (quickly), but far from all. Some stuff gets removed years after it was uploaded, and some never. Does that mean we should remove the site from Youtube-DL? Just because the site has content that is copyrighted and that hasn't been removed yet?
> > To be honest, it's a bit insane that both YouTube and Dailymotion has so much copyrighted content that never gets removed.
> > I've personally watched quite a lot of shows on both sites that are copyrighted but still fully available.
> 
> Yes, my initial claim is not that strong, but on my reply to @triplesixman I addressed another issue, illegal content, not copyright infringing, child abuse and such.
> But oh well, this is irrelevant to my argument.

- But is it Youtube-dl's job to prevent people from downloading illegal content? 
- How would Youtube-dl figure out if content someone tries to download is illegal? 
- And illegal where? Something may be illegal in one country but fully illegal in another country.

**Comment by marium0505** [comment]
> > I've personally watched quite a lot of shows on both sites that are copyrighted but still fully available. A lot of it was uploaded more years ago. So no, neither Dailymotion nor YouTube removes (all) videos with copyrighted content.
> 
> But the copyright holder can still take down those videos or send a copyright strike to get money out of the videos.
> Yes, youtube on its own doesn't do it, but it leaves the window of opportunity open for the copyright holder.

That applies for any site on the web, including porn sites.

**Comment by ArjixWasTaken** [comment]
> That applies for any site on the web, including porn sites.

Does it? Cause the last time I checked those porn sites keep reuploading anything that goes down, and also they don't use a descriptive name, so its hard for the copyright holders to find what is theirs on those sites.

**Comment by marium0505** [comment]
> > That applies for any site on the web, including porn sites.
> 
> Does it? Cause the last time I checked those porn sites keep reuploading anything that goes down, and also they don't use a descriptive name, so its hard for the copyright holders to find what is theirs on those sites.

https://copyrightalliance.org/faqs/what-is-dmca-takedown-notice-process

**Comment by ArjixWasTaken** [comment]
> > > That applies for any site on the web, including porn sites.
> > 
> > 
> > Does it? Cause the last time I checked those porn sites keep reuploading anything that goes down, and also they don't use a descriptive name, so its hard for the copyright holders to find what is theirs on those sites.
> 
> https://copyrightalliance.org/faqs/what-is-dmca-takedown-notice-process
> 
> https://www.google.com/webmasters/tools/legal-removal-request?hl=en&pid=0&complaint_type=1

How is that a reply to my reply?

**Comment by ArjixWasTaken** [comment]
> * And illegal where? Something may be illegal in one country but fully illegal in another country.

In this case by "illegal" I'm referring to things that society has forbidden, society doesn't make laws, it makes common sense.

**Comment by ArjixWasTaken** [comment]
> * Is it Youtube-dl's job to prevent people from downloading illegal content?

Totally not.


> * How would Youtube-dl figure out if content someone tries to download is illegal?

There is no need to.

All I said was that youtube-dl should either changes its hypocritic policy, or remove copyright infringing sites.

**Comment by 0xAB51NTH** [comment]
> > * And illegal where? Something may be illegal in one country but fully illegal in another country.
> 
> In this case by "illegal" I'm referring to things that society has forbidden, society doesn't make laws, it makes common sense.

There is nothing like "forbidden by society" the big fish that have biggest influence create the most of rules and you can see with your "common sense" over what "commone sense" things religions make. You are refeering to a model of rules that changes not even per country but per local communities. Post soviet countries have bigger moral allowance towards pirating games and stuff and if we were to go by their "things that society forbidden" it would not be to enforce anti piracy.

**Comment by ArjixWasTaken** [comment]
> There is nothing like "forbidden by society" the big fish that have biggest influence create the most of rules and you can see with your "common sense" over what "commone sense" things religions make. You are refeering to a model of rules that changes not even per country but per local communities. Post soviet countries have bigger moral allowance towards pirating games and stuff and if we were to go by their "things that society forbidden" it would not be to enforce anti piracy. Also it would be nice to provide some examples aswell as evidence that following sites are in fact infringing copyright.

So you are saying you are ok with child abuse?
Cause that's what you are saying right now.

You want copyrighted video examples?
Easy, just search for any brazzers video on xnxx and xvideos.

**Comment by 0xAB51NTH** [comment]
> So you are saying you are ok with child abuse?
> Cause that's what you are saying right now.

Where have i said that im for child aboose? Im just saying that using society driven rules is not something that is either law or always respectful, there are cases where someone did local communities where he was using "community driven laws" as excuse for his wrongdoings.

> You want copyrighted video examples?
> Easy, just search for any brazzers video on xnxx and xvideos.

After doing search on XVideos and XNXX (that is a mirror site of XVideos) for keyword "brazzers" first page is full of videos from account called "brazzers" im assuming that its official account as it was quite obnoxious with their branding on the short clips from full videos.

**Comment by ArjixWasTaken** [comment]
> Where have i said that im for child aboose? Im just saying that using society driven rules is not something that is either law or always respectful, there are cases where someone did local communities where he was using "community driven laws" as excuse for his wrongdoings.

What does that have to do with what I said?
At this point you are just finding anything to get back at me, even if that makes no sense?
Like, don't tell me you didn't understand that I was talking about ethics.
Ethics were created by society, no, not local society, but by all the world.

> After doing search on XVideos and XNXX (that is a mirror site of XVideos) for keyword "brazzers" first page is full of videos from account called "brazzers" im assuming that its official account as it was quite obnoxious with their branding on the short clips from full videos.

Brazzers is a paid service, pornhub might have a lot of clips from it for free.
But thats because pornhub is in a partnership with such companies.

xnxx/xvideos don't have permissions to post that content.
Users post it, yes, the site might not be at fault, but the content is still there.

**Comment by mechalincoln** [comment]
> > Where have i said that im for child aboose? Im just saying that using society driven rules is not something that is either law or always respectful, there are cases where someone did local communities where he was using "community driven laws" as excuse for his wrongdoings.
> 
> What does that have to do with what I said?
> At this point you are just finding anything to get back at me, even if that makes no sense?
> Like, don't tell me you didn't understand that I was talking about ethics.
> Ethics were created by society, no, not local society, but by all the world.
> 
> > After doing search on XVideos and XNXX (that is a mirror site of XVideos) for keyword "brazzers" first page is full of videos from account called "brazzers" im assuming that its official account as it was quite obnoxious with their branding on the short clips from full videos.
> 
> Brazzers is a paid service, pornhub might have a lot of clips from it for free.
> But thats because pornhub is in a partnership with such companies.
> 
> xnxx/xvideos don't have permissions to post that content.
> Users post it, yes, the site might not be at fault, but the content is still there.

No one cares. If you don't like it, don't use this repo. Your profile says you contribute to development for nyaa, an anime torrent site, which makes this whole thread even more quixotic.

What are you trying to accomplish here?

**Comment by ArjixWasTaken** [comment]
> > > Where have i said that im for child aboose? Im just saying that using society driven rules is not something that is either law or always respectful, there are cases where someone did local communities where he was using "community driven laws" as excuse for his wrongdoings.
> > 
> > 
> > What does that have to do with what I said?
> > At this point you are just finding anything to get back at me, even if that makes no sense?
> > Like, don't tell me you didn't understand that I was talking about ethics.
> > Ethics were created by society, no, not local society, but by all the world.
> > > After doing search on XVideos and XNXX (that is a mirror site of XVideos) for keyword "brazzers" first page is full of videos from account called "brazzers" im assuming that its official account as it was quite obnoxious with their branding on the short clips from full videos.
> > 
> > 
> > Brazzers is a paid service, pornhub might have a lot of clips from it for free.
> > But thats because pornhub is in a partnership with such companies.
> > xnxx/xvideos don't have permissions to post that content.
> > Users post it, yes, the site might not be at fault, but the content is still there.
> 
> No one cares. If you don't like it, don't use this repo. Your profile says you contribute to development for nyaa, an anime torrent site, which makes this whole thread even more quixotic.
> 
> What are you trying to accomplish here?

How did you come to that conclusion?
Now, I don't develop for the site nyaa.
I made an extension, yes, but that's all.

I'm not affiliated with nyaa.

**Comment by ArjixWasTaken** [comment]
I have a question for you all that talk here.
What are you even doing here?
You have nothing to do with this repo in any way.....

Are you all drama queens or smth?

**Comment by mechalincoln** [comment]
> I have a question for you all that talk here.
> What are you even doing here?
> You have nothing to do with this repo in any way.....
> 
> Are you all drama queens or smth?
> smh

no

**Comment by rautamiekka** [comment]
> You have nothing to do with this repo in any way.....

Guess being an user of the software doesn't have anything to do with whether one will use the software.
smh indeed with invalid argument.

**Comment by ArjixWasTaken** [comment]
> > You have nothing to do with this repo in any way.....
> 
> Guess being an user of the software doesn't have anything to do with whether one will use the software.
> smh indeed with invalid argument.

That's not the point, you are acting as if you made this software...

**Comment by rautamiekka** [comment]
The way I see it, the policy's point is when the site was designed for it.

**Comment by ArjixWasTaken** [comment]
> The way I see it, the policy's point is when the site was designed for it.

That's a really valid point, that only just now you (plural) brought up.
At least specifically this.

**Comment by ArjixWasTaken** [comment]
> No one cares. If you don't like it, don't use this repo. *Your profile says you contribute to development for nyaa, an anime torrent site*, which makes this whole thread even more quixotic.

You know what, I hate you (this kind of people), you judge the other based on their profile.
If I had an "anime pfp" you would say my point is invalid since I have an "anime pfp", no?

**Comment by ArjixWasTaken** [comment]
> Anyways, this whole repo is hypocritic if you look at the policy, this was intended to be a joke but I guess I was too serious.

Guess nobody likes joking about ironic things....
So I'll close this issue, it dragged on long enough.
