### ISSUE TITLE
[REQUEST] Filename check

### ISSUE THREAD

**Issue by User-green** [ytdl-org/youtube-dl#29635]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

The issue is:
When downloads video, title of witch contains ",", youtube-dl will try to write "," in filename, that will cause error no. 2 "unable to open file".
I ssugest to add feature, to prevent this kind of errors:
Filename check. If forbidden symbol is present, than owerrite it with "_".

**Comment by kikuyan** [comment]
Please provide the verbose log. It's hard to understand your situation without it.

**Comment by dirkf** [comment]
The feature exists: it's `--restrict-filenames`. If that doesn't help (I don't think it will), the problem is with how you're quoting the filename, so you'll need to show us some console output and provide information on the OS. For both Windows or Unix-like OS, put the filename like so: `"media, whose title contains a comma.mp4"`

**Comment by rautamiekka** [comment]
Ya, the comma ain't the problem by itself.

Don't skip the template, like the verbose log.

**Comment by User-green** [comment]
> 
> 
> The feature exists: it's `--restrict-filenames`. If that doesn't help (I don't think it will, because "," is generally a valid filename character), the problem is with how you're quoting the filename, so you'll need to show us some console output and provide information on the OS. For both Windows or Unix-like OS, put the filename like so: `"media, whose title contains a comma.mp4"`

Got it. Sorry for disturbing.
