### ISSUE TITLE
NHK sports url not supported

### ISSUE THREAD

**Issue by wntrsl** [ytdl-org/youtube-dl#29645]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://sports.nhk.or.jp/olympic/highlights/content/dadd1ba3-97c9-4a56-98e2-3d5a27657914/
- Single video: https://sports.nhk.or.jp/olympic/highlights/content/1d7d133d-ce2c-4892-b4ab-bdaf3ab4db79/

## Description

ERROR: Unsupported URL: https://sports.nhk.or.jp/olympic/highlights/content/1d7d133d-ce2c-4892-b4ab-bdaf3ab4db79/

**Comment by kikuyan** [comment]
They are DRM protected.

**Comment by 89z** [comment]
Issue should be closed, URL is dead
