### ISSUE TITLE
[extractor/arte]: switch from api/v1 to api/v2

### ISSUE THREAD

**Issue by casaper** [ytdl-org/youtube-dl#29640]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I've noticed the [Arte.tv extractor](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/arte.py) uses the older API to grab the extraction data.  
For example:

https://api.arte.tv/api/player/v1/config/de/086124-001-A

Currently, this works just fine. But their website uses their newer V2 API:

https://api.arte.tv/api/player/v2/config/de/086124-001-A

This one however is requiring a bearer token authentication in order to get the data.

As long as the old API V1 is still up and running, there is actually no need to change anything. 

But I'm afraid some day the folks at arte.tv will kill the old API, and then the extractor will turn dysfunctional.

## Refactor the [Arte.tv extractor](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/arte.py) to API V2

I already found out where and how the browser gathers the token for the authentication, though.  
It is only a little hidden behind some next.js lazy loading script. So the level of obfuscation is minor. I presume other sites will try to do way worse than that.

So will I get the sanctioning for such a refactor of the extractor?

I'm asking, because I do not want to invest time in it to create a PR, that then is ignored or rejected for whatever reason.

**Comment by casaper** [comment]
```sh
curl -s 'https://static-cdn.arte.tv/guide/manifest.js?ver=210715143858' | egrep -oh '"default":{"token":"[a-zA-Z0-9_-]*"'
```

**Comment by dirkf** [comment]
Continued in #30878.
