### ISSUE TITLE
what is average_rating in youtube?

### ISSUE THREAD

**Issue by lottopotato** [ytdl-org/youtube-dl#29663]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi everyone.
In extract information, 'average_rating' is exists for youtube video. 
where i find average_rating documentation or metric?

**Comment by kikuyan** [comment]
https://github.com/ytdl-org/youtube-dl/search?q=average_rating

**Comment by lottopotato** [comment]
@kikuyan 
Yeah.. I already checked this. 
`
'average_rating': float_or_none(video_details.get('averageRating')),`
But, I  wonder about how to **calculate** the 'average rating' of YouTube videos and the **meaning** of 'average rating'.

**Comment by jemand771** [comment]
just as a wild guess, could `averageRating` have something to do with the like/dislike ratio?
@lottopotato can you go ahead and check if `averageRating` is equivalent to `likes/dislikes` or `likes/(likes+dislikes)` or something related?

**Comment by lottopotato** [comment]
@jemand771 Unfortunately, that doesn't seem.
For example, in the video for [VPZD_aij8H0](https://www.youtube.com/watch?v=VPZD_aij8H0).
like and dislike counts were 12905, 334.
however, `averageRating` was 4.8990~.
`like/dislike` is 38.63~.
and `like/(like+dislike)` is 0.97~

Perhaps as described in README,
'`average_rating (numeric)`: Average rating give by users, the scale used depends on the webpage'
I think it is probably related to YouTube's own policy.

I sense like my question not related youtube-dl issue, but I just question if anyone knows.

**Comment by tfdahlin** [comment]
@lottopotato 

The average rating can be calculated with the following:
```
(like * 5) + (dislike)
----------------------  * 5
 (like + dislike) * 5
```
Historically, you used to be able to rate videos with a [scale of 1-5 stars](https://1.bp.blogspot.com/_bu0zMK51jOY/STfB7G8zQeI/AAAAAAAAABA/L8cvAsrd1kA/s400/screenshot2.JPG), which is where the value originally came from. This was later changed in favor of the like/dislike system.

Now, a like counts as a 5-star rating, and a dislike counts a as a 1-star rating, so youtube calculates the averageRating by taking the total number of stars received (5 per like, 1 per dislike), dividing that by the total number of stars possible (if everybody gave it a 5-star rating) to get a percentage of stars earned, then multiplying that by 5 stars.

**Comment by lottopotato** [comment]
@tfdahlin wow! You gave me the perfect answer. Thank you very much!
