### ISSUE TITLE
Unable to download Bitchute Playlist

### ISSUE THREAD

**Issue by BioBox** [ytdl-org/youtube-dl#29660]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
I'm not sure if this is a bug or simply a feature that isn't implemented, but when trying to download a playlist from Bitchute -- specifically a link of the form `https://www.bitchute.com/playlist/XXXXXXXXXX` I get an Unsupported URL error, even though downloading individual videos works fine. If anyone could add the capability to use `--yes-playlist` on these links that would be awesome and would save us some time.

**Comment by rautamiekka** [comment]
Don't skip the template, it's there for a reason and this is prime material for it.

**Comment by BioBox** [comment]
I'm not sure what you mean. Am I supposed to delete the markdown comments in the textbox?

**Comment by dirkf** [comment]
You created the issue as a "Site feature request", but the template for a "Broken site support" issue would have been more helpful. It asks you to check more things and to provide a verbose log for a problem URL.

**Comment by BioBox** [comment]
Okay I'll reopen it as a bug.
