### ISSUE TITLE
One CBS episode errors "No video formats found" while all others work

### ISSUE THREAD

**Issue by cameronetchart** [ytdl-org/youtube-dl#29662]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PS C:\Users\cameronetchart> youtube-dl https://www.cbs.com/shows/love-island/video/B6FGP5B5HNRLhAvwb92aFzSZwxC1_aNV/love-island-usa-episode-12/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.cbs.com/shows/love-island/video/B6FGP5B5HNRLhAvwb92aFzSZwxC1_aNV/love-island-usa-episode-12/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.2-2021-02-27-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-27-full_build-www.gyan.dev
[debug] Proxy map: {}
[CBS] B6FGP5B5HNRLhAvwb92aFzSZwxC1_aNV: Downloading XML
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\cbs.py", line 115, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\cbs.py", line 97, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

There is one CBS episode of Love Island that fails to download, but I have no issues playing in Firefox. Love Island s3e12, [link here](https://www.cbs.com/shows/love-island/video/B6FGP5B5HNRLhAvwb92aFzSZwxC1_aNV/love-island-usa-episode-12/), results in "No video formats found" but every other episode works fine (examples: [e10](https://www.cbs.com/shows/love-island/video/6BGGwfCmmxeTOPeYlEb9sUDScrdxP96t/love-island-usa-episode-10/) [e11](https://www.cbs.com/shows/love-island/video/YFXB6gTkrwuiGEqmB_RYfTGjPGR4gGlB/love-island-usa-episode-11/) [e13](https://www.cbs.com/shows/love-island/video/NXR9W4SAdtRpi4eJqKukkqC_6Abfu9gi/love-island-usa-episode-13/) [e14](https://www.cbs.com/shows/love-island/video/4YzbJkW2o7lcvjeePYxUbqh1b5HQZmHp/love-island-usa-episode-14/). I'm located in USA, no VPN, and this episode is free for all, so no issues with geolocation or login (but cable login works perfectly with --ap-mso on other locked episodes). I have tested both with Windows 10 x64 and arm32v7, same results.

**Comment by kikuyan** [comment]
Please test if the video is playable after disabling "Play DRM-controlled content" (the words may differ) in Firefox settings.

**Comment by cameronetchart** [comment]
So all episodes fail to play once I disable the Play DRM content setting in Firefox, including both the episodes that yt-dl can download and can't download. I know yt-dl doesn't support bypassing DRM, but the inconsistency makes me assume something different is happening?

**Comment by TheGrimKeeper** [comment]
Pretty sure this is DRM.  For many series I noticed CBS applying DRM to the newest episode available, and then typically removing it once the next episode airs.  But it seems they sometimes mess this up, leaving it applied to an old episode, or never disabling it on the season/series finale.  I believe the final episode of MacGyver is still DRM'ed even though the show is now canceled.

**Comment by cameronetchart** [comment]
The episode randomly downloaded for me today, and every episode since has worked, so agree this definitely appears to be weird application of DRM. Closing & thanks all.
