### ISSUE TITLE
Twitch Clips: Is there an option to use the human readable ID as part of the Output Template?

### ISSUE THREAD

**Issue by suvis1** [ytdl-org/youtube-dl#29666]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

Hi!

Im in the progress of archiving a huge amount of twitch clips, but i would require the human readable ID (e.g. `GleamingGentleGarageJebaited-fapOh70bAsfNoU3C`) to be saved in the filename. Youtube-dl itself considers the ID to be `1235515999` which wont work with what i need it to do. Ive tried all of the output `%(NAME)s` substitutions i could think of and nothing seems to be what im searching for.

Im not sure whether this is a new feature request or just me NOT seeing something that is possible, so i placed this under "question".

Thanks for any help :)

**Comment by dirkf** [comment]
Looking at your example, which I assume is https://clips.twitch.tv/embed?clip=GleamingGentleGarageJebaited-fapOh70bAsfNoU3C&parent=cyberpost.co, the ID is initially recognised as `GleamingGentleGarageJebaited-fapOh70bAsfNoU3C` and then replaced by the ID returned from the GraphQL lookup.

The extractor could extract the original ID as `display_id` and it would then be available to you in the filename template, as below:
```
# youtube-dl -v --get-filename -o '%(display_id)s.%(ext)s' 'https://clips.twitch.tv/embed?clip=GleamingGentleGarageJebaited-fapOh70bAsfNoU3C&parent=cyberpost.co' 
[debug] System config: [u'--restrict-filenames', u'--prefer-ffmpeg', u'-f', u'best[height<=?1080][fps<=?60]', u'-o', u'/media/drive1/Video/%(title)s.%(ext)s']
[debug] User config: [u'-f', u'(best/bestvideo+bestaudio)[height<=?1080][fps<=?60][tbr<=?1900]']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--get-filename', u'-o', u'%(display_id)s.%(ext)s', u'https://clips.twitch.tv/embed?clip=GleamingGentleGarageJebaited-fapOh70bAsfNoU3C&parent=cyberpost.co']
[debug] Encodings: locale ASCII, fs ASCII, out ASCII, pref ASCII
[debug] youtube-dl version 2021.06.06.1
[debug] Python version 2.7.1 (CPython) - Linux-2.6.18-7.1-7405b0-smp-with-libc0
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
GleamingGentleGarageJebaited-fapOh70bAsfNoU3C.mp4
#
```
For this, this line 
```
            'display_id': video_id,
```
has to be added to the `dict` returned from the `_real_extract()` method of `TwitchClipsIE`, `extractor/twitch.py` line 976ff. Other extractors in the file do set `display_id`.

**Comment by suvis1** [comment]
Oh thanks so much for this! I already resorted to just putting the entire youtube-dl output to a variable and grepping the required lines out of it to change the filenames afterwards, but this is a much better solution that wont break as soon as even a single character gets added to the output lines haha :)
