### ISSUE TITLE
[RaiPlay] - ERROR: No video formats found

### ISSUE THREAD

**Issue by rjdangelo** [ytdl-org/youtube-dl#29671]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--format', 'hls-2400+hls-aac-Italiano', '--sub-lang', 'IT', '--write-sub', 'https://www.raiplay.it/video/2021/04/La-fuggitiva-S1E2-62315597-b644-4dc1-95ce-1ac310fd8a3e.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[RaiPlay] 62315597-b644-4dc1-95ce-1ac310fd8a3e: Downloading video JSON
[RaiPlay] 62315597-b644-4dc1-95ce-1ac310fd8a3e: Downloading XML metadata for platform mon
[RaiPlay] 62315597-b644-4dc1-95ce-1ac310fd8a3e: Downloading XML metadata for platform flash
[RaiPlay] 62315597-b644-4dc1-95ce-1ac310fd8a3e: Downloading XML metadata for platform native
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/rai.py", line 174, in _real_extract
    self._sort_formats(relinker_info['formats'])
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I am using a NordVPN connection in Italy to access the site. I tried a number of gateways with the same result. 

I can play any of the episodes without problem using the browser.

I was able to download the first episode of this series on Monday, but on Tuesday I started getting this error, when trying to download the second episode. I tried to download again the first episode that I successfully downloaded the day before, but also failed.

**Comment by dirkf** [comment]
`Per vedere questo video
devi essere registrato a RaiPlay`

Are you registered with RaiPlay? What happens if you send the browser cookies in your yt-dl command?

Or do you not get this message using your in-country proxy?

**Comment by rjdangelo** [comment]
Thank you for your answer.

I am registered already, and I can watch any movie in the browser without
any problem.

In the past I have downloaded many series episodes without any issue.

The odd thing is that it has stopped working yesterday. Maybe they were not
enforcing the credentials before.

I'll look into sending browser cookies. Is there any documentation on how
to do that?

**Comment by dirkf** [comment]
`How do I pass cookies to youtube-dl?` in the fine manual.

**Comment by rjdangelo** [comment]
Thanks.

I tried sending the cookies from the firefox browser where I was watching the episode, but I am getting the same error.

**Comment by Sipherdrakon** [comment]
I just used ExpressVPN Italy and it worked just fine. It does tend to timeout if the download speed is super low as I had that problem when I was downloading from 10play in Australia, but it does work, which means your VPN provider is the issue.

![Screenshot_20210729-110105_Termux.jpg](https://user-images.githubusercontent.com/64430430/127516689-0c0c4b5b-e8d9-4d5f-a739-fb5a015010f3.jpg)

**Comment by rjdangelo** [comment]
Interesting. 
I am still trying to reconcile not being able to download it, with being able to watch in the browser. This would suggest that the VPN is not the problem.

**Comment by Sipherdrakon** [comment]
Yeah VPNs are tricky little things, like I can download from 10play with the Melbourne Australia VPN but if I choose Sydney it will tell me it can't download the files but I can stream using either.

**Comment by rjdangelo** [comment]
I have changed ISP and everything started working as usual. Probably some misconfiguration or unwanted filtering on the previous ISP
