### ISSUE TITLE
'pp' is not recognized 

### ISSUE THREAD

**Issue by Wazeminator** [ytdl-org/youtube-dl#29697]
Yesterday an issue with youtube-dl showed up. when I use multiple links for download  I get "'pp' is not recognized as an internal or external command,
operable program or batch file.  "  after youtube-dl downloads the first video. director location is right, command is also right. I tried changing the path with no result. 
usually astfer I choose the director in windows 10 cmd, I use youtube-dl.exe and then i paste the urls. 
how can I fix this issue?

**Comment by kikuyan** [comment]
Read [FAQ](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).

**Comment by nicolaasjan** [comment]
YouTube recently added `&pp=sAQA` at the end of the links on e.g. the homepage.
So put the whole URL between quotes. :)

youtube-dl OPTIONS "https://www.youtube.com/watch?v=4aXi3lOmICI&pp=sAQA"

**Comment by dirkf** [comment]
https://github.com/ytdl-org/youtube-dl#user-content-video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
