### ISSUE TITLE
Missing VC-runtime for youtube-dl.exe needs to be placed in the same folder [solved]

### ISSUE THREAD

**Issue by eladkarako** [ytdl-org/youtube-dl#29694]
![2021-07-31_074133](https://user-images.githubusercontent.com/415238/127728813-b34ea5cb-8301-4353-8b71-80056a8e59f9.jpg)
you'll need to place `msvcr100.dll` in the same folder as the exe.  
I've found that it specifically requires the x86 version (although I have a x64 machines, and anyway I already have both x86 and x64 already installed on the system but for some reason it didn't worked).  

a zip with the missing VC runtime is attached here for you convenience.  
[msvcr100.dll - Microsoft C Runtime Library v10.00.40219.1 (x86).zip](https://github.com/ytdl-org/youtube-dl/files/6910691/msvcr100.dll.-.Microsoft.C.Runtime.Library.v10.00.40219.1.x86.zip)

unzip and place it at the same folder as the exe.  

![2021-07-31_074624](https://user-images.githubusercontent.com/415238/127728905-5c99a7e2-73ac-4894-893c-5db79857e162.jpg)

**Comment by kikuyan** [comment]
Read [FAQ](https://github.com/ytdl-org/youtube-dl#the-exe-throws-an-error-due-to-missing-msvcr100dll).

**Comment by eladkarako** [comment]
thanks, that is a useful link to have,  
since now days every Google search for VC runtimes gives the unified download page that requires MS login  
https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0  
before the actual links (and the link to VC2010SP1 is broken in there anyway).  

👌
