### ISSUE TITLE
Rokfin site support request

### ISSUE THREAD

**Issue by myfirstnameispaul** [ytdl-org/youtube-dl#29699]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://rokfin.com/stream/7765/TYT-and-LA-vs-Homelessness-Blizzard-vs-Unions-Millions-Kicked-Out
- Single podcast: https://rokfin.com/post/47790/The-CIA-and-The-Finders-with-Elizabeth-Vos
- Playlist: Rokfin does not have a playlist feature.

## Description

Rokfin requires users to be logged in to view content.

Here is their about us page:

https://rokfin.com/about

**Comment by P-reducible** [comment]
Here is a [pull request](https://github.com/yt-dlp/yt-dlp/pull/1534) with an extractor for Rokfin. [yt-dlp](https://github.com/yt-dlp) is a descendant of youtube-dl since youtube-dl is no longer in development.
