### ISSUE TITLE
mp4 only extract

### ISSUE THREAD

**Issue by AbhijithNT** [ytdl-org/youtube-dl#29711]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How can I extract mp4 JSON only

**Comment by rautamiekka** [comment]
Readme:
```
-j, --dump-json                      Simulate, quiet but print JSON
                                     information. See the "OUTPUT TEMPLATE"
                                     for a description of available keys.
-J, --dump-single-json               Simulate, quiet but print JSON
                                     information for each command-line
                                     argument. If the URL refers to a
                                     playlist, dump the whole playlist
                                     information in a single line.
--print-json                         Be quiet and print the video
                                     information as JSON (video is still
                                     being downloaded).
```
`--print-json` will need either of these though:
```
-s, --simulate                       Do not download the video and do not
                                     write anything to disk
--skip-download                      Do not download the video
```

**Comment by AbhijithNT** [comment]
> Readme:
> 
> ```
> -j, --dump-json                      Simulate, quiet but print JSON
>                                      information. See the "OUTPUT TEMPLATE"
>                                      for a description of available keys.
> -J, --dump-single-json               Simulate, quiet but print JSON
>                                      information for each command-line
>                                      argument. If the URL refers to a
>                                      playlist, dump the whole playlist
>                                      information in a single line.
> --print-json                         Be quiet and print the video
>                                      information as JSON (video is still
>                                      being downloaded).
> ```
> 
> `--print-json` will need either of these though:
> 
> ```
> -s, --simulate                       Do not download the video and do not
>                                      write anything to disk
> --skip-download                      Do not download the video
> ```

```python
info = ydl.extract_info('http://www.youtube.com/watch?v=BaW_jenozKc', download=False,extra_info={})```

**Comment by rautamiekka** [comment]
That works, too, if you're willing to code Python by yourself.
