### ISSUE TITLE
nzonscreen content

### ISSUE THREAD

**Issue by petaflot** [ytdl-org/youtube-dl#29712]
- [X ] I'm reporting a new site support request
- [X ] I've verified that I'm running youtube-dl version **2021.06.06**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that none of provided URLs violate any copyrights
- [ X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.nzonscreen.com/title/the-last-man-of-mahana-2017

## Description

for humanity's sake. we need to live.

**Comment by Richienb** [comment]
Duplicate of https://github.com/ytdl-org/youtube-dl/issues/29385
