### ISSUE TITLE
 Can't play live streams anymore 

### ISSUE THREAD

**Issue by Macanalista** [ytdl-org/youtube-dl#29717]
## Checklist

- [ ] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by Macanalista** [comment]
Youtube-dl is not playing live streams from YouTube anymore. Using Powermacs Systems 10.5 and 10.4 and the PPCMC as interface. The terminal wont open the movie in VLC as used to, and it plays an alert sound continuously while writing strange characters.

**Comment by Macanalista** [comment]
The PPCMC application I am using has the 2021.06.06 version installed

**Comment by Evernow** [comment]
> ## Verbose log
> 
> ```
> PASTE VERBOSE LOG HERE
> ```

Where is the log??

**Comment by Macanalista** [comment]
It happens when I try to play any YouTube live stream.
Part of the log:

Streaming Youtube Live Stream @360p...


miguel-toscanos-powerbook-g4-17:~ migueltoscano$ export REQUESTS_CA_BUNDLE=/Applications/PPCMC.app/certs/cacert.pem
miguel-toscanos-powerbook-g4-17:~ migueltoscano$ /Applications/PPCMC.app/bin/python2.7 /Applications/PPCMC.app/bin/youtube-dl  --prefer-ffmpeg --ffmpeg-location=/Applications/PPCMC.app/bin/ffmpeg -f 93 -o - https://m.youtube.com/watch?v=sPgqEHsONK8&pp=sAQA | /Applications/VLC.app/Contents/MacOS/VLC --fullscreen -
[1] 858
VLC media player 2.0.10 Twoflower (revision 2.0.9-43-g2912d78)
[0x301888] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
2021-08-02 15:08:44.673 VLC[860:10b] ERROR: Attempt to set unknown item as dropItem=<SideBarItem: 0x9c5cb90>.
[0x9ccef48] main stream error: cannot pre fill buffer
[youtube] sPgqEHsONK8: Downloading webpage
[youtube] sPgqEHsONK8: Downloading m3u8 information
[youtube] sPgqEHsONK8: Downloading MPD manifest
[download] Destination: -
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 4.0.1 (GCC) (Apple Computer, Inc. build 5363)
  configuration: --prefix=/Applications/PPCMC.app --enable-altivec --extra-libs=-L/Applications/PPCMC.app/lib --extra-ldflags=-L/Applications/PPCMC.app/lib --extra-cflags='-arch ppc7450 -I/Applications/PPCMC.app/include/SDL2 -D_THREAD_SAFE -I/Applications/PPCMC.app/include' --enable-libmp3lame --enable-zlib --disable-iconv --enable-openssl --enable-static --enable-sdl --enable-outdev=sdl2 --disable-htmlpages
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
[hls @ 0x2804200] Skip ('#EXT-X-VERSION:3')
[hls @ 0x2804200] Skip ('#EXT-X-DISCONTINUITY-SEQUENCE:100')
[hls @ 0x2804200] Skip ('#EXT-X-PROGRAM-DATE-TIME:2021-08-02T18:09:04.987+00:00')
[hls @ 0x2804200] Opening 'https://r3---sn-uxax4vopj55gb-hq1l.googlevideo.com/videoplayback/id/sPgqEHsONK8.3/itag/93/source/yt_live_broadcast/expire/1627949342/ei/vjQIYYYkj4XWxA-nuYagDw/ip/191.82.103.239/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D134/hls_chunk_host/r3---sn-uxax4vopj55gb-hq1l.googlevideo.com/playlist_duration/30/manifest_duration/30/gcr/ar/vprv/1/playlist_type/DVR/initcwndbps/3100/mh/nD/mm/44/mn/sn-uxax4vopj55gb-hq1l/ms/lva/mv/m/mvi/3/pl/20/keepalive/yes/fexp/24001373,24007246/mt/1627927482/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,gcr,vprv,playlist_type/sig/AOq0QJ8wRgIhAKayZJyvdBvFFWT2SBD_FeAkkfe7vTMsF95KOnwWTV4zAiEAsyw8L0XOvApq5ll9DPr2jj9rU5hhvTBHKYkTqLuGga0%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIhAN67pgA7IxRnvP8f1abtevAWyGr9fT23soIz4IIl1bCPAiBp138mJaXXOlubvAuaxjRqC_xeSxO8J5_128UKpujQAA%3D%3D/playlist/index.m3u8/sq/889750/goap/clen%3D81942%3Blmt%3D1627837976406710/govp/clen%3D208671%3Blmt%3D1627837976406706/dur/4.933/file/seg.ts' for reading
[hls @ 0x2804200] Opening 'https://r3---sn-uxax4vopj55gb-hq1l.googlevideo.com/videoplayback/id/sPgqEHsONK8.3/itag/93/source/yt_live_broadcast/expire/1627949342/ei/vjQIYYYkj4XWxA-nuYagDw/ip/191.82.103.239/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D134/hls_chunk_host/r3---sn-uxax4vopj55gb-hq1l.googlevideo.com/playlist_duration/30/manifest_duration/30/gcr/ar/vprv/1/playlist_type/DVR/initcwndbps/3100/mh/nD/mm/44/mn/sn-uxax4vopj55gb-hq1l/ms/lva/mv/m/mvi/3/pl/20/keepalive/yes/fexp/24001373,24007246/mt/1627927482/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,gcr,vprv,playlist_type/sig/AOq0QJ8wRgIhAKayZJyvdBvFFWT2SBD_FeAkkfe7vTMsF95KOnwWTV4zAiEAsyw8L0XOvApq5ll9DPr2jj9rU5hhvTBHKYkTqLuGga0%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIhAN67pgA7IxRnvP8f1abtevAWyGr9fT23soIz4IIl1bCPAiBp138mJaXXOlubvAuaxjRqC_xeSxO8J5_128UKpujQAA%3D%3D/playlist/index.m3u8/sq/889751/goap/clen%3D84374%3Blmt%3D1627837976406725/govp/clen%3D167656%3Blmt%3D1627837976406721/dur/5.067/file/seg.ts' for reading
Input #0, hls, from 'https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1627949342/ei/vjQIYYYkj4XWxA-nuYagDw/ip/191.82.103.239/id/sPgqEHsONK8.3/itag/93/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D134/hls_chunk_host/r3---sn-uxax4vopj55gb-hq1l.googlevideo.com/playlist_duration/30/manifest_duration/30/gcr/ar/vprv/1/playlist_type/DVR/initcwndbps/3100/mh/nD/mm/44/mn/sn-uxax4vopj55gb-hq1l/ms/lva/mv/m/mvi/3/pl/20/dover/11/keepalive/yes/fexp/24001373,24007246/mt/1627927482/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,gcr,vprv,playlist_type/sig/AOq0QJ8wRgIhAKayZJyvdBvFFWT2SBD_FeAkkfe7vTMsF95KOnwWTV4zAiEAsyw8L0XOvApq5ll9DPr2jj9rU5hhvTBHKYkTqLuGga0%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIhAN67pgA7IxRnvP8f1abtevAWyGr9fT23soIz4IIl1bCPAiBp138mJaXXOlubvAuaxjRqC_xeSxO8J5_128UKpujQAA%3D%3D/playlist/index.m3u8':
  Duration: N/A, start: 58201.829700, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 640x360 [SAR 1:1 DAR 16:9], 30 tbr, 90k tbn, 60 tbc
    Metadata:
      variant_bitrate : 0
Output #0, mpegts, to 'pipe:':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 640x360 [SAR 1:1 DAR 16:9], q=2-31, 30 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
G@B?%?????HFFmpeg	Service01w|C??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????*?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????GP???????/D???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????GA0P{
                           ~???!?a	?gM@?????Z???? ????h?<?%?????Z?*5???J?{ ?}?L~i?Μi?L?(xgr?H?}ɴ=_)?G??/P??T^??)?c?(?*?@??_???~\??m??%:??+?]??IdN?u??"
?GP??#??ʧF??=?+??9????ʄ?7[C??5q??Kq$ň?łB???3?S|??+???N?.r'D?d܁@??S?K?$?os??^?zz??M?m6d?@h???*=\?Yr??K&??^?(?????7??ТE2?=L?jƿ?d
                                              ??
f???	?
         ^?
??F??_s?d?-??iY??{??|!??e??d??????f?5J??6?b???QM???N??VH?8"??.
                                                              ?!?[9?z?''?R?j ???@?SY??B??A;d(?]??A;??S˟?R?
znG-??ʉ?b??ށ??z?oK?쬘???
          ??????_=??;??]r??b??
                              qh???XrR??c????c?Y?⌳kh??FE'??32???'?=x?-???!???9|??P?	_??w?Lc??c?)9?!D9??Ϝ?ؚ?\k?u?CIjO?`a???? ??pO??F?BMa??賝#?Bֵ??A ^1j?ح~?
jG?^S?s40?`????y%zt???Q??s6?G%v??D_???>??;Z??p(:???H?ED)?0??;
                                                             ?#\?l??	?T<???	??e?.???Ѭ???5??;???+;?(??:???ʲ=l?TOh?
f                                   ??}_
 ?u?P?H?9????L%??v&NtP???\????odOg?.?/[?Q?]?G ;낡?帵l?}?	eop3巻U????{a?f"??|)Td???˻???"i?Q
ު??               R9?????R?? ??	(?TL#??7氚b6???hԽ?z?G?
  ?(??-1?lG~j??h????JL?v?r?~?x??ʱ?~?o?7ƴ??	??f????>????p!c,??x???G?[????I?W
                                                                               kH??뺯?t?|??????]yK???|(8!h?9??ͅb?j???4B???e?Y6;mk*$???:!?G?-~ʥ??y$r?&'珫???^?5o?????)???ٙ;[D??D?m??????9?}(?9uB+|;?|}??7?cg6?&O?K럯jI%s@???n\GX\l
                                                                ???Ų?:%??"??l,}?0l<S??%???A??   ????$?!"???$P??#??5???????mM=??i	???Z?ƭbA?^Y?C˓?ݓK???
                                                                            ?g??F???}?!*>?6vN)#??M?'???;?=??U?.ϛE;~?W???G???R?b????Y2T҄y?t'Z??U??:}?c?:"??J?CP0#?e"???z??h??
           ?B?qKwD%{???,x1?U)?z????9㓊?]ƈ{?Ok??????F}cO?!R??.?
K???U\ ?[A???k?l?A
                  l??/vR?Gt???????̤?ƹ????|?ae?_??!??t?E\3???~>?:???HTit??|?
                                                                          ???izjBg,h`?????g,$?F??`X?XI?*?Bb>??Ε?|?0?uW`d??~??
                                             ??{?B?[o???)?!$?J???n?n?ǖ???&?=?^xE=n?%n噈(????G״Ĺ??'????恏???1??3?f
?߬?qU:	?=???;l?d??x?#?????ڥ??_J)?a?!s???0?Je??خ???x??o??8?Y<3
                                                              ?
                                                               ?p???6?2|#?
                                                                          Ța?w??7&??h???S?i?
???0?x3?y??,>KwZ?bx~??/??%??Z?Y4??~?G:?@0??@??؆?z?+????G?(Mݻ~??J5?Ǳc7??ܹŦ$?HQ?$?0
                                                                               >0??!??
      ??
        p????PzD???iH(G??/)??>??g?{{?5?j)ȇ?ŀL???????v?*S/([??j???gך?v?^A~M?Z҉??MGՉ??~?n#J????HI????e%PmG???}?O{??z`D_!?	%2!Hy??r?d?B ֫Է??/??.????hW?????????&H?7&???X?!I?
        ;Mj?F?r8X??|}??\?R)xx?0T)?-?SҞ?ܻg-6??ǃb?w ???	?
?5?lJ?T[!??[%P?
i?ت?DJ??t?????^??Ǿ3OG,'8!?n???Lh?@???^?Ig???,$[KoGJQ??|~??@??6?z????AHՉhU?v?M????g??B?j???W?&@??*?!??8??х??2?m?e?ϢxR?4????GRI6???.?w?(dJ?.??Bx$;???ޛ?????9[?+??y??@?هU]??	l?
?                 7/?????n?{7'=
 %???bW	i?'?M?E?s3???c_?b????J??G??????g????+??f??!?eJ?k???H??ǽGx?

**Comment by kikuyan** [comment]
> 2021-08-02 15:08:44.673 VLC[860:10b] ERROR: Attempt to set unknown item as dropItem=<SideBarItem: 0x9c5cb90>.
> [0x9ccef48] main stream error: cannot pre fill buffer
> 
VLC complains something. Not youtube-dl problem.

**Comment by Evernow** [comment]
I cannot reproduce this issue. I am right now downloading this on-going live stream and it works fine: 

```
youtube-dl https://www.youtube.com/watch?v=d9sDXBmTxTY
```

**Comment by srsutherland** [comment]
Getting a similar problem trying to download https://www.youtube.com/watch?v=8AJErTj92VI, though that video may be member-restricted by the time anyone sees this (it is not currently member-restricted though, I confirmed that).

```youtube-dl -v https://www.youtube.com/watch?v=8AJErTj92VI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=8AJErTj92VI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[youtube] 8AJErTj92VI: Downloading webpage
[youtube] 8AJErTj92VI: Downloading m3u8 information
[youtube] 8AJErTj92VI: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1628558122/ei/yn4RYdG3AZankwbStL1g/ip/184.187.181.122/id/8AJErTj92VI.1/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr5---sn-a5msen7l.googlevideo.com/vprv/1/playlist_type/LIVE/initcwndbps/13620/mh/ne/mm/44/mn/sn-a5msen7l/ms/lva/mv/m/mvi/5/pl/19/dover/11/keepalive/yes/fexp/24001373,24007246/mt/1628536347/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,vprv,playlist_type/sig/AOq0QJ8wRQIgGaeLnp21fmymxZFyjrGNHmW9odGnE-1ZoOtG-ED_vh0CIQDn-zN1lObPue72A9vTDbHsDbnfWlY0qCc9bFP7O0plMg%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRgIhALZje7YYS11ZanrsdVOu9qm5IihcdZaCE7z5yjZBj6wsAiEAzKyFuxgCvyjxogj2eWR0xhys4yZgSj2Rr_WsiD99C0k%3D/playlist/index.m3u8'
[download] Destination: LIVE NOW!  Behind the Scenes of 💖 The Tale of Tiffany 💖 2021-08-09 12_15-8AJErTj92VI.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3699.0 Safari/537.36
' -i 'https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1628558122/ei/yn4RYdG3AZankwbStL1g/ip/184.187.181.122/id/8AJErTj92VI.1/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr5---sn-a5msen7l.googlevideo.com/vprv/1/playlist_type/LIVE/initcwndbps/13620/mh/ne/mm/44/mn/sn-a5msen7l/ms/lva/mv/m/mvi/5/pl/19/dover/11/keepalive/yes/fexp/24001373,24007246/mt/1628536347/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,vprv,playlist_type/sig/AOq0QJ8wRQIgGaeLnp21fmymxZFyjrGNHmW9odGnE-1ZoOtG-ED_vh0CIQDn-zN1lObPue72A9vTDbHsDbnfWlY0qCc9bFP7O0plMg%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRgIhALZje7YYS11ZanrsdVOu9qm5IihcdZaCE7z5yjZBj6wsAiEAzKyFuxgCvyjxogj2eWR0xhys4yZgSj2Rr_WsiD99C0k%3D/playlist/index.m3u8' -c copy -f mp4 'file:LIVE NOW!  Behind the Scenes of 💖 The Tale of Tiffany 💖 2021-08-09 12_15-8AJErTj92VI.mp4.part'
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1628558122/ei/yn4RYdG3AZankwbStL1g/ip/184.187.181.122/id/8AJErTj92VI.1/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr5---sn-a5msen7l.googlevideo.com/vprv/1/playlist_type/LIVE/initcwndbps/13620/mh/ne/mm/44/mn/sn-a5msen7l/ms/lva/mv/m/mvi/5/pl/19/dover/11/keepalive/yes/fexp/24001373,24007246/mt/1628536347/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,vprv,playlist_type/sig/AOq0QJ8wRQIgGaeLnp21fmymxZFyjrGNHmW9odGnE-1ZoOtG-ED_vh0CIQDn-zN1lObPue72A9vTDbHsDbnfWlY0qCc9bFP7O0plMg%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRgIhALZje7YYS11ZanrsdVOu9qm5IihcdZaCE7z5yjZBj6wsAiEAzKyFuxgCvyjxogj2eWR0xhys4yZgSj2Rr_WsiD99C0k%3D/playlist/index.m3u8: Input/output error


ERROR: ffmpeg exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2069, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1692, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1976, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/external.py", line 64, in real_download
    self.get_basename(), retval))
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 590, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())```

**Comment by dirkf** [comment]
Now:
```
[youtube] 8AJErTj92VI: Downloading webpage
ERROR: This video is available to this channel's members on level: 🐝 🎁 Bonus Videos! 🎁 🐝 (or any higher level). Join this channel to get access to members-only content and other exclusive perks.
```
