### ISSUE TITLE
Support for spotify videos and songs

### ISSUE THREAD

**Issue by ProgrammingMyLife** [ytdl-org/youtube-dl#29722]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
It would be cool to download MP3s or videos from spotify via youtube-dl

Example songs without videos such as [https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT?si=1372c193b1744d3e](url) could be downloaded as an mp3

But others with a video such as [https://open.spotify.com/track/2BITQ360Knh6qNAOqR7Dyq?si=10adc01f5a684b42](url) can be downloaded as an mp4 or any other video format

**Comment by llacb47** [comment]
DRM

**Comment by Evernow** [comment]
Feel free to reverse engineer and bypass the DRM to make this possible. And then feel free to fund the team of lawyers you'll need to keep this project in existence.

**Comment by ProgrammingMyLife** [comment]
> Feel free to reverse engineer and bypass the DRM to make this possible. And then feel free to fund the team of lawyers you'll need to keep this project in existence.

Didn't know it was like that haha. My bad

**Comment by 89z** [comment]
Issue should be closed. According to initial report, both links can be downloaded, so no action needed

**Comment by 4cq2** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31037

**Comment by eflister** [comment]
spotify is listed as supported.  is it supported or should it be removed from the list indicating it is?  i'd like to use it on a spotify playlist if it is supported, but i'm getting 403 forbidden.  https://open.spotify.com/playlist/5TV9s2YkVJNkFEh3EUhiiV

**Comment by dirkf** [comment]
As in [downstream](https://github.com/yt-dlp/yt-dlp/issues/3415#issuecomment-1097682890):
>The extractor only supports podcasts. Music on spotify is DRM protected and cannot be supported.

**Comment by 3052** [comment]
@eflister if you are interested in individual tracks, I would be willing to implement that. post an issue to my `media` repo
