### ISSUE TITLE
Unable to download video from Udemy

### ISSUE THREAD

**Issue by Yash7200** [ytdl-org/youtube-dl#29733]

**Comment by kikuyan** [comment]
Read [other issue reports about udemy](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+is%3Aopen+udemy).
And please remove your username and password from the log.

**Comment by jemand771** [comment]
@Yash7200 note that github issues have an edit history, so make sure to clear that too. though I'd change the password anyway, you don't know how many people have seen and/or used it already
