### ISSUE TITLE
An error in a specific format

### ISSUE THREAD

**Issue by caiyouzai** [ytdl-org/youtube-dl#29746]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

I use youtube-dl to download videos. Download the best video and audio in webm format, and then use FFmpeg to merge them.
The parameter I use is youtube-dl.exe -f'bestvideo[ext=webm],bestaudio[ext=webm]' --merge-output-format webm https://www.youtube.com/watch?v=XXXXXXX
But there was an accident, because the downloaded video and audio are both with the same file name (xxxx.webm), when the video is downloaded and the audio is downloaded, youtube-dl recognizes xxxx.webm (actually a video file) already exists.
The program will prompt xxxx.webm has already been downloaded.
Finally output a silent video file. What should I do? (I know that choosing other formats can solve it, but I hope that the downloaded sound and video are all webm)

**Comment by kikuyan** [comment]
> bestvideo[ext=webm],bestaudio[ext=webm]

Try with `+` not `,`

**Comment by caiyouzai** [comment]
oh ,I made a stupid mistake
