### ISSUE TITLE
plesase add download_date(YYYYMMDD) to OUTPUT TEMPLATE

### ISSUE THREAD

**Issue by pscj** [ytdl-org/youtube-dl#29752]
- [X] I'm reporting a feature request
- [X ] I've verified that I'm running youtube-dl version **2021.06.06**
- [X ] I've searched the bugtracker for similar feature requests including closed ones

## Description
I want to rename the output filename to  %(download_date)s_%(title)s,  I found a param called "timestamp" , it's hard to read.  any suggestion?
Thank you.

**Comment by kikuyan** [comment]
I think it's the job of the shell. In bash, `-o "$(date +%Y%m%d)_%(title)s.%(ext)s"`

**Comment by pscj** [comment]
Thank you. It's work fine
