### ISSUE TITLE
Python embedded with opts 'write-sub':True, 'skip-download':True downloads video file

### ISSUE THREAD

**Issue by clemwo** [ytdl-org/youtube-dl#29760]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I want to download just the subtitles of ARD Mediathek videos with youtube-dl embedded in python. Using the command-line this works fine and outputs just the subtitle file: 
```shell
youtube-dl --write-sub --skip-download "https://www.ardmediathek.de/video/tagesschau/tagesschau-20-00-uhr/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL3RhZ2Vzc2NoYXUvZTAwMDczMTEtNThmNy00YjVjLWFjZTEtY2JhOWIxOTI5YmM4/"
```

Now my python program, starts downloading the video file which I obviously want to avoid. It looks like this:
```py
from __future__ import unicode_literals
import youtube_dl

ydl_opts = {
    'write-sub':True,
    'skip-download':True,
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://www.ardmediathek.de/video/tagesschau/tagesschau-12-00-uhr/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL3RhZ2Vzc2NoYXUvM2QwZDFiYWQtNDJmNS00OTA2LWJkNmMtYzljYzQ3NWYxMzlj/'])
```
What am I doing wrong?

**Comment by s104346** [comment]
It's `writesubtitles` and `skip_download` when using embedded youtube-dl, according to the [options list in YoutubeDL.py](https://github.com/ytdl-org/youtube-dl/blob/a8035827177d6b59aca03bd717acb6a9bdd75ada/youtube_dl/YoutubeDL.py#L141).

**Comment by clemwo** [comment]
> It's `writesubtitles` and `skip_download` when using embedded youtube-dl, according to the [options list in YoutubeDL.py](https://github.com/ytdl-org/youtube-dl/blob/a8035827177d6b59aca03bd717acb6a9bdd75ada/youtube_dl/YoutubeDL.py#L141).

This works. Thank you so much, this really makes my day!
