### ISSUE TITLE
youtube-dl error [CvBfHwUxHIk] video unavailable

### ISSUE THREAD

**Issue by FMA1986** [ytdl-org/youtube-dl#29775]
youtube-dl -f 137+140 https://www.youtube.com/watch?v= [url code at bottom]
**[youtube] CvBfHwUxHlk: Downloading webpage
ERROR: Video unavailable**

Hi! The youtube-dl version is the last 2021.06.06. Why I can't download this video? Thanks!

**Comment by rautamiekka** [comment]
Don't skip the template, it's there for a reason.

**Comment by FMA1986** [comment]
> Don't skip the template, it's there for a reason.

What?

**Comment by rautamiekka** [comment]
When you create a new ticket (an issue; I prefer calling the issue posts a ticket instead) there's text in the box, with instructions how to acquire what you need to show, 1 being the verbose log.

**Comment by october262** [comment]
has the video been removed ??

**Comment by FMA1986** [comment]
No, the video does exist! It's youtube-dl who can't download in HD!

**Comment by rautamiekka** [comment]
Doesn't work in browser (Google Chrome Stable) either.

**Comment by FMA1986** [comment]
For a letter I have mistake, it's I not L. That's a link! https://www.youtube.com/watch?v=CvBfHwUxHIk

**Comment by FMA1986** [comment]
Fix it, it's my link error! Sorry!
