### ISSUE TITLE
Bypass System Proxy Settings

### ISSUE THREAD

**Issue by faxotherapy** [ytdl-org/youtube-dl#29786]
## Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

Running MacOS with following proxy settings, both for HTTP and HTTPS:
```
127.0.0.1:8118
127.0.0.1:8079
```

Is it possible to ask youtube-dl bypass those proxy settings? Thank you.

**Comment by kikuyan** [comment]
Read the doc https://github.com/ytdl-org/youtube-dl#network-options

**Comment by faxotherapy** [comment]
OK. I failed to read the doc properly. I missed the section “Pass in empty string (--proxy "") for connection”

Thank you.

**Comment by kikuyan** [comment]
Close this, please.
