### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by AbiAkash** [ytdl-org/youtube-dl#29798]
Actually i need to download videos from a DRM video protection website but don't know how to can you help me with that I would be more helpful for that??? Coz these videos helps in higher studies 

## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by LewdyCoder** [comment]
A good reminder, don't ask to ask, just ask. People might ignore you otherwise

**Comment by 89z** [comment]
Issue should be closed, no URL given
