### ISSUE TITLE
abort download if download rate is less than X (100KB) , --abort-dl-rate <100KB

### ISSUE THREAD

**Issue by McErroneous** [ytdl-org/youtube-dl#29790]
## Checklist

- [x ] I'm reporting a feature request
- [ x] I've verified that I'm running youtube-dl version **2021.04.07**
- [o ] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

aborting the download , if the download rate is less than 100KB  would enable me to resume high speed downloads, by restarting youtube-dl..., using a bash script

**Comment by rautamiekka** [comment]
Yes, but it ain't yt-dl's fault. Dunno what site you're reffing to, but I'm had the same problem with YT for a few days by now, but most likely cuz of the mass-downloading cuz I'm behind.

**Comment by jack-perter-333** [comment]
403 is an access error, maybe you need an account and password or cookies

**Comment by tameTNT** [comment]
I too have been having this issue quite frequently when downloading YouTube playlists where speeds suddenly appear to be throttled to very low values (e.g. ~60KiB/s vs. upwards of 3MiB/s normally).

**Currently** I `Ctrl+C` the terminal command and then edit the `--playlist-items` flag to continuously re-resume the download process until the speed starts of quickly again. It will usually remain high for the next 2-3 videos before abruptly falling off again, often in the middle of videos.

**Using this proposed feature,** I assume the initial poster would assume that youtube-dl would detect the slower download speed, break execution and then automatically re-attempt a connection+download a set number of times until a faster speed is once again reached. If not, an error message could be produced.

**Comment by gatecrasher777** [comment]
Same issue as #29326.  The solution is to encode the n parameter in the streams the same way that youtube/embed players do it.  Clearly, the throttle is to discourage downloads.
