### ISSUE TITLE
CONTRIBUTING test_download.py not working

### ISSUE THREAD

**Issue by LewdyCoder** [ytdl-org/youtube-dl#29792]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
test_MiTeleIE (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_MiTeleIE (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: type object 'TestDownload' has no attribute 'test_MiTeleIE'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

## Description

Running `python test/test_download.py -v TestDownload.test_YourExtractor`, (in my case both an extractor I was trying to develop and MiTeleIE), returns an error, raw guess is that the test script can't reach the appropriate test class

**Comment by kikuyan** [comment]
`test_MiTele`

**Comment by LewdyCoder** [comment]
Thank you, how did it work? I've not been able to find such string

**Comment by llacb47** [comment]
Critical thinking?

**Comment by LewdyCoder** [comment]
> Critical thinking?

Critical thinking doesn't highlight strings for you in grep -R, sorry

**Comment by LewdyCoder** [comment]
Realized the mistake and added a description accordingly, made a PR according to my problem #29799
