### ISSUE TITLE
Please add the TV provider "DirecTV"

### ISSUE THREAD

**Issue by CHJ85** [ytdl-org/youtube-dl#29802]
Hi there. I'm trying to download from tbs.com. But when I check `-ap-list-mso`, I can't find DirecTV.
Do you think you could add DirecTV
Thanks in advance.

**Comment by zombiewizard45** [comment]
DirecTV is at the very top of the list. The ID is DTV.

**Comment by CHJ85** [comment]
Than you @zombiewizard45
