### ISSUE TITLE
youtube视频下载失败，[WinError 10061] 由于目标计算机积极拒绝，无法连接。求助

### ISSUE THREAD

**Issue by Cry-stal** [ytdl-org/youtube-dl#29836]
C:\Users\Alexander\Desktop\^\VideoLoad>youtube-dl https://www.youtube.com/watch?v=q2zj74iK1MI
[youtube] q2zj74iK1MI: Downloading webpage WARNING: Unable to download webpage: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
[youtube] q2zj74iK1MI: Downloading API JSON
ERROR: Unable to download API page: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。> (caused by URLError(ConnectionRefusedError(10061, '由于目标计算机积极拒绝，无法连接。', None, 10061, None),))
全局全局代理已开。

**Comment by dirkf** [comment]
With version 2021.06.06, you should see:
```...
[youtube] q2zj74iK1MI: Downloading webpage
[youtube] q2zj74iK1MI: Downloading player b555ee94
[info] Available formats for q2zj74iK1MI:
...
```
Maybe some network error between you and YT, or an old version, but we can't tell because **you didn't follow the template**.

**Comment by Cry-stal** [comment]
C:\Users\Alexander\Desktop\^\VideoLoad>youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {'https': 'https://127.0.0.1:7890', 'ftp': 'ftp://127.0.0.1:7890', 'http': 'http://127.0.0.1:7890'}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

C:\Users\Alexander\Desktop\^\VideoLoad>youtube-dl -U
youtube-dl is up-to-date (2021.06.06)

**Comment by dirkf** [comment]
Presumably the issue is with the proxying.

What happens with `youtube-dl -v https://www.youtube.com/watch?v=q2zj74iK1MI`?

**Comment by Cry-stal** [comment]
C:\Users\Alexander\Desktop\^\VideoLoad>youtube-dl -v https://www.youtube.com/watch?v=q2zj74iK1MI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=q2zj74iK1MI']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {'ftp': 'ftp://127.0.0.1:7890', 'http': 'http://127.0.0.1:7890', 'https': 'https://127.0.0.1:7890'}
[youtube] q2zj74iK1MI: Downloading webpage
WARNING: Unable to download webpage: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
[youtube] q2zj74iK1MI: Downloading API JSON
ERROR: Unable to download API page: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。> (caused by URLError(ConnectionRefusedError(10061, '由于目标计算机积极拒绝，无法连接。', None, 10061, None),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\utils.py", line 2737, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open

**Comment by kikuyan** [comment]
Add `--proxy ""`

**Comment by eveloki** [comment]
### English
you must  use --proxy  to download youtube video in china.
you can use clash or v2ray to bypass GFW,
for example,i use clash.net ，is like
`youtube-dl -v https://www.youtube.com/watch?v=q2zj74iK1MI --proxy "socks5://127.0.0.1:11223"`

### Chinese

如果你在中国使用youtubedl下载youtube视频你必须使用 --proxy 选项
你需要指定他为一个可用的http 或者socket5代理服务器
你可以使用clash或者v2rayN来绕过GFW
以下为这些项目的url
https://github.com/Fndroid/clash_for_windows_pkg   （clash）
https://github.com/ClashDotNetFramework/ClashDotNetFramework （clash.net）
https://github.com/2dust/v2rayN  (v2rayN )

例如，我使用了 clash.net，接下来你可以使用类似于下面这条指令来下载视频了
`youtube-dl -v https://www.youtube.com/watch?v=q2zj74iK1MI --proxy "socks5://127.0.0.1:11223"`

**Comment by dirkf** [comment]
I understand that GFW admin Xí is prone to block popular or effective VPNs. Might that be OP's problem?

**Comment by Cry-stal** [comment]
非常感谢各位的真诚帮助，我现在已经能够成功下载YouTube视频了。因为GFW，通过添加--proxy ""得以实现，好开心。非常感谢 eveloki的实例参考,dirkf, kikuyan的指导和帮助！
Thanks a million, I have been able to successfully download YouTube videos now.  Because GFW, by adding --proxy "". I rejoice in solving the problem that was bothering me.  Thank you very much  instance reference by Eveloki,  guidance and help by Dirkf and Kikuyan!

**Comment by Louis24** [comment]
WARNING: Unable to download webpage: <urlopen error [Errno 0] Invalid response version from server. Expected 05 got 48>
ERROR: Unable to download API page: <urlopen error [Errno 0] Invalid response version from server. Expected 05 got 48> (caused by URLError(InvalidVersionError(0, 'Invalid response version from server. Expected 05 got 48'),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\utils.py", line 2737, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open


也在国内
