### ISSUE TITLE
Failed to parse JSON on www.rtp.pt

### ISSUE THREAD

**Issue by nosuchuser** [ytdl-org/youtube-dl#29835]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

iMac:~ bruno$ youtube-dl --verbose https://www.rtp.pt/play/p9165/e562949/por-do-sol
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.rtp.pt/play/p9165/e562949/por-do-sol']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.16 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[RTP] e562949: Downloading webpage
ERROR: e562949: Failed to parse JSON  (caused by ValueError("Expecting ',' delimiter: line 2 column 36 (char 37)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 2 column 36 (char 37)
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/rtp.py", line 37, in _real_extract
    'player config'), video_id, js_to_json)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 910, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: e562949: Failed to parse JSON  (caused by ValueError("Expecting ',' delimiter: line 2 column 36 (char 37)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

youtube-dl has always been working for rtp.pt videos but in the past few days it stopped working.

**Comment by dirkf** [comment]
>  ... in the past few days ...

Only now? See #29458.

I have some fixes prepared but not yet in a PR; in any case no PRs have been committed to the released version for some weeks.

**Comment by nosuchuser** [comment]
Well, for some reason I was unable to search the open issue list for this behavior and thought it was new - I see it's duplicated, already reported, much more well documented than I could ever document it and incorrect as - and I've checked it - the last time I used youtube-dl on the site was on June 2020. Seemed like it was yesterday.

Should I close it as a duplicate, @dirkf ?

**Comment by dirkf** [comment]
By all means. PR #29824, when it gets merged, will fix the problem.

**Comment by nosuchuser** [comment]
Duplicate of #29458
