### ISSUE TITLE
Cannot download some PornHub pages

### ISSUE THREAD

**Issue by BandageWorm** [ytdl-org/youtube-dl#29843]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

youtube-dl --proxy "socks5://localhost:23333" https://cn.pornhub.com/model/rolakiki/videos --verbose -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', 'socks5://localhost:23333', 'https://cn.pornhub.com/model/rolakiki/videos', '--verbose', '-v']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-essentials_build-www.gyan.dev, ffprobe 4.4-essentials_build-www.gyan.dev
[debug] Proxy map: {'http': 'socks5://localhost:23333', 'https': 'socks5://localhost:23333'}
[download] Downloading playlist: model/rolakiki/videos
[PornHubPagedVideoList] model/rolakiki/videos: Downloading page 1
[PornHubPagedVideoList] playlist model/rolakiki/videos: Downloading 8 videos
[download] Downloading video 1 of 8
[PornHub] ph5f256ffd9f5a1: Downloading pc webpage
[PornHub] ph5f256ffd9f5a1: Downloading tv webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\python39\lib\site-packages\youtube_dl\extractor\pornhub.py", line 385, in _real_extract
    js_vars = extract_js_vars(
  File "c:\python39\lib\site-packages\youtube_dl\extractor\pornhub.py", line 322, in extract_js_vars
    assignments = self._search_regex(
  File "c:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Cannot download this model's video list. Also happend in this page:https://cn.pornhub.com/model/loliiiiipop99.

**Comment by dirkf** [comment]
Aren't these subscription videos?

**Comment by nicothin** [comment]
> Some page like https://cn.pornhub.com/channels/real-gangbangs works though.

No ))

PS E:\download> .\youtube-dl.exe https://cn.pornhub.com/channels/real-gangbangs
[download] Downloading playlist: channels/real-gangbangs/videos
[PornHubPagedVideoList] channels/real-gangbangs/videos: Downloading page 1
[PornHubPagedVideoList] playlist channels/real-gangbangs/videos: Downloading 0 videos
[download] Finished downloading playlist: channels/real-gangbangs/videos

**Comment by dirkf** [comment]
Continued in #32448, if applicable.
