### ISSUE TITLE
Active youtube-dl forks?

### ISSUE THREAD

**Issue by ahm750** [ytdl-org/youtube-dl#29842]
Since youtube-dl is currently not being maintained, what are the most active forks? [yt-dlp](https://github.com/yt-dlp/yt-dlp) seems to be a good alternative, anything else?

**Comment by rautamiekka** [comment]
Best to have only 1 active replacement.

**Comment by triplesixman** [comment]
I switched to yt-dlp as well. It is more than enough

**Comment by 89z** [comment]
I have one here:

https://github.com/89z/mech

**Comment by mahanstreamer** [comment]
> Best to have only 1 active replacement.

Not all the time.

But youtube-dlp is great, I think that's what everyone is using for now.

**Comment by moom0o** [comment]
I'd stick with yt-dlp.

**Comment by noembryo** [comment]
Are there any that support Python 2.7?

**Comment by moom0o** [comment]
Why can't you use python 3?

**Comment by noembryo** [comment]
A lot of reasons, but mainly because some of my most complicated and big applications of mine, use libraries that are not compatible with it.
I can't even update Pyside, since there are things missing from Pyside2/6 (like Phonon etc.)

But even if I could do it, I would still remove compatibility for x86 systems (Pyside6)..
Its a big mess :cry:

**Comment by simteraplications** [comment]
just out of interest, does anyone know whats up with the youtube dl developers? I am developing a youtube client and it's exhausting that i literarely have to push updates every week becasuse something breaks and the youtube-dl doesn't get recompiled.

**Comment by fastily** [comment]
> just out of interest, does anyone know whats up with the youtube dl developers?

Nobody knows for sure.  For a bit of context:
* #29753
* [discussion on reddit](https://redd.it/p9riey)

**Comment by dirkf** [comment]
#30568.
