### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by frt550** [ytdl-org/youtube-dl#29859]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'bestaudio', u'--extract-audio', u'--audio-format', u'mp3', u'--audio-quality', u'0', u'https://www.youtube.com/playlist?list=PLSr_oFUba1jtP9x5ZFs5Y0GJkb8fmC161']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Linux-5.11.0-27-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
```

## Description

Im on ubuntu 20.04.3 LTS and latest youtube-dl.
The command i run: 
`youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 https://www.youtube.com/playlist?list=PLSr_oFUba1jtP9x5ZFs5Y0GJkb8fmC161`
The error i get:
`ERROR: unable to download video data: HTTP Error 403: Forbidden`
Every command run error may appear on different songs. I cant download full playlist.

`youtube-dl --rm-cache-dir` and `sudo youtube-dl --rm-cache-dir` didnt help.

**Comment by dirkf** [comment]
Try using `--download-archive` and retry until done.
