### ISSUE TITLE
Question about manipulating strings in the output template

### ISSUE THREAD

**Issue by JohnKFisher** [ytdl-org/youtube-dl#29857]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm afraid this probably isn't specifically a YouTube-dl question, but a general shell one (maybe?) but I couldn't figure out how to google it and it involves setting up the output template in YouTube-dl so hoping someone can help me.

I am able to use %(upload_date).4s to get the YEAR (the first four digits of upload_date) into my output template -- is there a similar way to the .4 trick to get the LAST four (the MMDD) part?
Thanks!

(lastly, is there a name for what this kind of notation is called so I know what to google in the future? thanks)

**Comment by dirkf** [comment]
It's [Python printf style String Formatting](https://docs.python.org/3/library/stdtypes.html#old-string-formatting) and I don't believe it can do what you want.

**Comment by JohnKFisher** [comment]
Darn. Thank you, and thanks for the link so I can read more about it :-)
