### ISSUE TITLE
Youtube-dl Produces |Error on use of well-formed youtube URLs starting with simple hyphen

### ISSUE THREAD

**Issue by Ramana3031** [ytdl-org/youtube-dl#29865]
Using latest YouTube-dl 2021.06.06 (and also earlier versions, before this occasion), with well-formed YouTube URLs such as this one = -YjDc8aY9MA, which starts with the simple (short) hyphen, (not the long dash), produces = youtube-dl.exe: error: no such option: -Y, obviously interpreting the hyphen as the special character introducing an option "option".

The full URL is rejected in the command line as = ERROR: Unsupported URL, but accepted if is it is part of a list given at the command line with -a list.txt.
I have tried all the escape characters I know and googled, including ", ', ^, \, ,, ~, !, #, $, ... but none of these worked.

I have met this error before, and couldn't be brave enough to report it. Even this time I am not sure I am following exact protocol. If so, sorry!!! If you can help with a fix, thanx a million, is that correct English ? 
Also, Sorry, I couldn't place this in any of the categories listed. Also, an issue was raised about a title containing an underscore, but this is an URL and the hyphen is at the beginning

**Comment by Ramana3031** [comment]
Hi. I am sorry. I have just seen your comment and emails, as I had not logged in since my last comment above. Also, I was not aware I had to close the issue. But first, I can say that I have just checked again the solution offered and it works when I use $ youtube-dl -- -xyzabwvncd ; but when I use this = $ ytb1v -- -xyzabwvncd , where ytb1v runs a dos batch (ytb1v.bat) script as follows =
(
@echo off
@echo on
youtube-dl.exe ^
-i ^
-c ^
-o "%%(title)s.%%(ext)s" ^
-f "best" ^
%1
@echo off
:: pause
goto :EOF

 ) , the command fails, producing the same error as before, (without --). 

I do not know if this is within the scope of youtube-dl issues or my own issue. If it is not within your mission to resolve it, then please consider this issue closed. And I will close it after your reply or comment. Otherwise, I would be curious to know how the '-' can be escaped by the DOS batch command, while keeping the inside of the batch file applicable to both the URLs starting with a '-' or without. 

Once again, sorry for the delay, Sometimes, my already slow connection is also limited by a metered data-enabled scheme, and/or cellular providers (I live in a remote rural area of the island of Djerba, Tunisia, an area severely constrained in places by an aging 3G network, just now being very slowly revamped with fiber optics, etc.. Thank you for your kindness and patience.

**Comment by rautamiekka** [comment]
Use the code tags around code cuz the `@` turns into an at-mention, among other things becoming something unwanted, which is basically spam to the victim.

**Comment by Ramana3031** [comment]
Thank you. Could you please briefly explain by example what you mean by "code tags",  "around code" "the @ turns into",  "at-mention" ... Where to use these tags? where does "@ turn into an at-mention". (1. I am a beginner in this. 2. I just coped the above Windows DOS batch script to my pc , as I did not know, despite several attempts, to include it in a configuration,, and this started my system hanging?_ ). If you mean in these comment boxes, I assumed they are simple text boxes, and will not execute inside the issues format
