### ISSUE TITLE
[feature] Keep track a live stream on youtube and download right after it ends

### ISSUE THREAD

**Issue by amadheus95** [ytdl-org/youtube-dl#29869]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Can we have this feature? The program will be running until the video is not in live anymore. Aftr that, ytd-dl will start the download of a simple video, the entire youtube video.

**Comment by dirkf** [comment]
In a script you could run a loop sleeping for (eg) 5 minutes and calling yt-dl on the target URL with `--get-filename -o '%(is_live)d'` (Windows: '' -> ""). If the output is not "1", break the loop and run the yt-dl download.

**Comment by amadheus95** [comment]
> In a script you could run a loop sleeping for (eg) 5 minutes and calling yt-dl on the target URL with `--get-filename -o '%(is_live)d'` (Windows: '' -> ""). If the output is not "1", break the loop and run the yt-dl download.
> 
> Or you (or someone who cares) could write a Python program embedding yt-dl with the same logic.

Hey! Thanks, it helped a lot
So... I never had programmed before, but the code is functional! xD

I hope never need to do that things again

this is the code

`import subprocess
import time
from argparse import ArgumentParser
from timeit import default_timer as timer
from datetime import timedelta

#Argument Parser to receive URL
parser = ArgumentParser()
parser.add_argument('url', type=str, help="url of the live youtube video ")
args = parser.parse_args()

def testlive(url):
    command = "ytd --get-filename -o %(is_live)d " + str(args.url)

    animation  = [
        "Waiting live ends [=     ]",
        "Waiting live ends [ =    ]",
        "Waiting live ends [  =   ]",
        "Waiting live ends [   =  ]",
        "Waiting live ends [    = ]",# animation waiting 
        "Waiting live ends [     =]",# the live ends
        "Waiting live ends [    = ]",
        "Waiting live ends [   =  ]",
        "Waiting live ends [  =   ]",
        "Waiting live ends [ =    ]",
    ]
    i=0

    #first check to see if the video is in live now // THIS CODE RETURN 1 IF IS LIVE AND NOTHING ELSE
    p1 = subprocess.run(command, capture_output=True, text=True)


    #While is live, try again
    while p1.stdout:
        print(animation[i % len(animation)], end='\r')
        i += 1
        time.sleep(120)

        #trying again
        p1 = subprocess.run(command, capture_output=True, text=True)
    else: 
        print("BAIXANDO!")
        subprocess.run('ytd ' + str(args.url))

if __name__ == '__main__':
    testlive(args.url)
`

**Comment by dirkf** [comment]
That's great!

For your second programming lesson, you could read the development stuff in the Fine Manual and you'll see that you can achieve the same thing without running the yt-dl program itself (`subprocess()`, etc), because you can import the yt-dl core into your Python program and call it directly. The yt-dl program is an example of this.
