### ISSUE TITLE
Facebook Audio

### ISSUE THREAD

**Issue by jtagcat** [ytdl-org/youtube-dl#29881]
## Checklist
- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description
Support Facebook 'fbaudio', fb.audio

https://www.facebook.com/events/s/linux-then-now-future/371572961149896

redirects to https://www.facebook.com/fbaudio/?link_hash=exlyxwlmmkpu

points to https://fb.audio/live/exlyxwlmmkpu

![image](https://user-images.githubusercontent.com/38327267/131224219-8e64723a-d5e9-4fd9-bf1e-5cfc8d91234c.png)

**Comment by kikuyan** [comment]
The link you provided is for fb apps only and cannot be opened in a web browser.
Site support request template says this:
> - [ ] I've checked that all provided URLs are alive and playable in a browser

It's not in Site feature request template, but it would also need to be satisfied.

**Comment by jtagcat** [comment]
Hmmm, indded.

Though, it's 'Facebook Podcasts' or something, supposedly it also includes 'past' audio feeds as well. People have ripped, and posted to soundcloud, so it should be non-drm.

I'd say to close it as wontfix, as this pretty much is a new platform, and I don't see it being maintainable with little work.
