### ISSUE TITLE
Twitch Vod 403

### ISSUE THREAD

**Issue by omegahack0** [ytdl-org/youtube-dl#29883]
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

Hey guys I was trying to download a twitch vod https://www.twitch.tv/videos/1130931076?filter=all&sort=time, I tried 
"youtube-dl https://www.twitch.tv/videos/1130931076?filter=all&sort=time" then when I saw it was erroring out I updated tried again and added the -v param. Here is the results.

 youtube-dl -v https://www.twitch.tv/videos/1130931076?filter=all&sort=time
[1] 2160
ubuntu@ubuntu:/mnt/Weeb$ [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.twitch.tv/videos/1130931076?filter=all']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.5 (CPython) - Linux-5.11.0-1016-raspi-aarch64-with-glibc2.33
[debug] exe versions: none
[debug] Proxy map: {}
[twitch:vod] 1130931076: Downloading stream metadata GraphQL
[twitch:vod] 1130931076: Downloading video access token GraphQL
[twitch:vod] 1130931076: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

[1]+  Exit 1                  youtube-dl -v https://www.twitch.tv/videos/1130931076?filter=all

Idk if amazon is adopting cloudflare as well or what

**Comment by kikuyan** [comment]
In browser, the page says: This video is only available to subscribers. Sub now to watch and support lastmiles.
You may need to try --cookies option.

**Comment by dirkf** [comment]
Now: "Video 1130931076 does not exist"
