### ISSUE TITLE
if it is DRM Widevine V1 is there any way to extract?

### ISSUE THREAD

**Issue by yy0901** [ytdl-org/youtube-dl#29890]
## Checklist

- [ x ] I'm asking a question
- [ x ] I've looked through the README and FAQ for similar questions
- [ x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

if it is DRM Widevine V1 is there any way to extract?
using either youtube-dl or ffmpeg?

or if there's any program which decodes or extract drm protected vid to ts?

**Comment by kikuyan** [comment]
Go ask [VideoHelp Forum](https://forum.videohelp.com/forums/48-Video-Streaming-Downloading).
