### ISSUE TITLE
How to change codec?

### ISSUE THREAD

**Issue by notthefoxx** [ytdl-org/youtube-dl#29899]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm using 2015 Premiere Pro and codec is too new for this old version. Is there anyway to change codec? I can use handbrake to change it I guess but I prefer to do it somewhat easier.

**Comment by rautamiekka** [comment]
What codecs ?

**Comment by section83** [comment]
FFmpeg has a number of codec settings.  You can pass those thru from YTDL in post-processing args.
