### ISSUE TITLE
ERROR: unable to download video info webpage: HTTP Error 410: Gone

### ISSUE THREAD

**Issue by wonderer007** [ytdl-org/youtube-dl#29909]
## Verbose log

```
ERROR: unable to download video info webpage: HTTP Error 410: Gone (caused by <HTTPError 410: 'Gone'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
/app/vendor/bundle/ruby/2.6.0/gems/youtube-dl.rb-0.3.1.2016.09.11.1/vendor/bin/youtube-dl/youtube_dl/extractor/douyutv.py:115: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/app/vendor/bundle/ruby/2.6.0/gems/youtube-dl.rb-0.3.1.2016.09.11.1/vendor/bin/youtube-dl/youtube_dl/extractor/douyutv.py:115: SyntaxWarning: "is not" with a literal. Did you mean "!="?

```

## Description

Unable to download video on server. Using [youtube-dl.rb](https://github.com/layer8x/youtube-dl.rb). Everything seems working fine in the local environment.

### Server Information
```
Linux 7b5af8abd86e 4.15.0-153-generic #160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by kikuyan** [comment]
> Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Don't ignore what the message says.
I don't know about youtube-dl.rb, but maybe invoked youtube-dl is too old. Update to the latest version.

**Comment by mtreuberg** [comment]
First check the version:
```
youtube-dl --version
```

To update:
```
brew upgrade youtube-dl
```

In my case, I had already installed an old version, so I had to update the path with the newly installed version in brew:
```
brew link --overwrite youtube-dl
```
