### ISSUE TITLE
ERROR: Unable to download JSON metadata

### ISSUE THREAD

**Issue by macmoh92** [ytdl-org/youtube-dl#29903]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
ERROR: Unable to download JSON metadata: Remote end closed connection without response (caused by RemoteDisconnected('Remote end closed connection without response')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
if I download one video he download normally but if the playlist he show that message

**Comment by dirkf** [comment]
Please fulfil the checklist requirements if you would like anyone to help you.

**Comment by macmoh92** [comment]
works Perfectly thanx.

**Comment by kikuyan** [comment]
Then close this, please.

**Comment by macmoh92** [comment]
> Then close this, please.

first time
