### ISSUE TITLE
youtube-dlg

### ISSUE THREAD

**Issue by user6262** [ytdl-org/youtube-dl#29902]
Hello to everybody

Knows anybody how can I install youtube-dlg on Linus Mint 20.x?

## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by rautamiekka** [comment]
Unrelated to ytdl.

**Comment by jpenguin** [comment]
Never used that one, `pip install youtube-dlg` is what they say though, use pip3 if pip isn't there; https://github.com/jely2002/youtube-dl-gui is available as an appimage though.

**Comment by MuenchenSued** [comment]
You can also use the following commands:
```
sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
sudo chmod a+rx /usr/local/bin/yt-dlp

```
I normally install it in my home directory and therefore don't need sudo:
```
wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O yt-dlp
sudo chmod u+x yt-dlp
```

**Comment by chemputer** [comment]
While the people here are helpful, that's a different project. 

You can find the most up to date fork here: https://github.com/oleksis/youtube-dl-gui

Simply follow the instructions in the README.md file from this point down:
https://github.com/oleksis/youtube-dl-gui#using-pip3-on-debian-10

Note: Don't be worried it's instructions for Debian. Linux Mint is based on Ubuntu, which is based on Debian, so the instructions will work. 

You'll need to install pip3 on your Linux Mint system, so ensure you've done `sudo apt update` then do `sudo apt install software-properties-common python3 python3-pip` to install python 3 and pip, so you can use pip3. If you get stuck, here's [a guide](https://techviewleo.com/install-latest-python-on-ubuntu-linux-mint/), though it doesn't cover installing pip, just ensure you do `sudo apt install python3.9-pip` if you do it that way. 

If you run into any issues, while people here seem more than willing to help, feel free to ask at the repo for the package you're having issues with, as they have definitely used the package and can give you the most up to date and most accurate answers. Either [here, with the most up to date python fork](https://github.com/oleksis/youtube-dl-gui/issues) or [here, the original repo.](https://github.com/MrS0m30n3/youtube-dl-gui/issues)

Best of luck!
