### ISSUE TITLE
youtube-dl Throwing 410 Errors

### ISSUE THREAD

**Issue by Wrecked256** [ytdl-org/youtube-dl#29900]
[youtube] OTLUzIB4QHw: Downloading webpage
[youtube] OTLUzIB4QHw: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 410: Gone
WARNING: unable to download video info webpage: HTTP Error 410: Gone
WARNING: unable to download video info webpage: HTTP Error 410: Gone
WARNING: unable to download video info webpage: HTTP Error 410: Gone
WARNING: unable to download video info webpage: HTTP Error 410: Gone
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 11, in <module>
    load_entry_point('youtube-dl==2019.1.17', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3/dist-packages/youtube_dl/__init__.py", line 477, in main
    _real_main(argv)
  File "/usr/lib/python3/dist-packages/youtube_dl/__init__.py", line 467, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2002, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1672, in _real_extract
    token = video_info.get('token') or video_info.get('account_playback_token')
AttributeError: 'NoneType' object has no attribute 'get'

Trying to download YT videos but i am greeted with this ^
Sorry if this has been posted somewhere else i could not find it
Please help

**Comment by Wrecked256** [comment]
This was after running:

youtube-dl -f bestvideo+bestaudio --merge-output-format mkv --all-subs --cookies youtube_com.txt https://www.youtube.com/watch?v=OTLUzIB4QHw

**Comment by kikuyan** [comment]
> load_entry_point('youtube-dl==2019.1.17', 'console_scripts', 'youtube-dl')()

Too old. Update to the latest version first.

**Comment by nicolaasjan** [comment]
Works with latest vesion:

```
youtube-dl -v -f bestvideo+bestaudio --merge-output-format mkv OTLUzIB4QHw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo+bestaudio', '--merge-output-format', 'mkv', 'OTLUzIB4QHw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.6.9 (CPython) - Linux-5.4.0-81-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg N-103120-gc8b1f2bcc4-Nico-20210808, ffprobe N-103120-gc8b1f2bcc4-Nico-20210808
[debug] Proxy map: {}
[youtube] OTLUzIB4QHw: Downloading webpage
[debug] Invoking downloader on 'https://r4---sn-5hnekn76.googlevideo.com/videoplayback?expire=1630592436&ei=VIkwYf2FGdCQ1gKIs7ToCg&ip=<REDACTED>&id=o-AAf1VrwfJvimybQSHmpHur7C0NyBsefq6lQmWBMdkmb-&itag=247&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mh=gP&mm=31%2C29&mn=sn-5hnekn76%2Csn-5hne6nsr&ms=au%2Crdu&mv=m&mvi=4&pl=18&initcwndbps=2138750&vprv=1&mime=video%2Fwebm&ns=2g230ZoVEun-y0VnWRX39OMG&gir=yes&clen=4726208&dur=337.337&lmt=1542503609907962&mt=1630570613&fvip=4&keepalive=yes&fexp=24001373%2C24007246&beids=9466588&c=WEB&txp=5432432&n=H00qrKhynLno7Xx_&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgG-jieYCXBGKacDrPq3BPHhTWM1r3k8phmnWAHpLg6-4CICmhV5cx1PZ9fc74tOfsIA5QnB00Wesvx9R7b7r6Q9Kz&sig=AOq0QJ8wRAIgTz8IMxGSgtok_QyclacL-hBKZI315YigRVahgXV4iWgCIGiT2eQU5eglMDTmpprJNGDs0iu6dzv-BM2w7nCc4Xie'
[download] Destination: Black Atlass - Paris-OTLUzIB4QHw.f247.webm
[download] 100% of 4.51MiB in 00:00
[debug] Invoking downloader on 'https://r4---sn-5hnekn76.googlevideo.com/videoplayback?expire=1630592436&ei=VIkwYf2FGdCQ1gKIs7ToCg&ip=<REDACTED>&id=o-AAf1VrwfJvimybQSHmpHur7C0NyBsefq6lQmWBMdkmb-&itag=251&source=youtube&requiressl=yes&mh=gP&mm=31%2C29&mn=sn-5hnekn76%2Csn-5hne6nsr&ms=au%2Crdu&mv=m&mvi=4&pl=18&initcwndbps=2138750&vprv=1&mime=audio%2Fwebm&ns=2g230ZoVEun-y0VnWRX39OMG&gir=yes&clen=5817466&dur=337.341&lmt=1496622329710835&mt=1630570613&fvip=4&keepalive=yes&fexp=24001373%2C24007246&beids=9466588&c=WEB&n=H00qrKhynLno7Xx_&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgdHeuUYtBtnGBSubvdZHIvyv_nfhJYiaYAZjAK0sIB8ACIFVfpmKv9iRFfbPMYPcZDYxXg8LdYboFgNosvTQ3njHk&sig=AOq0QJ8wRAIgY4sDj9pZu0ESE9q22Odc0IagAYBJjKD_Xf8GiTpT0HwCIE06n0yFUcdhRT7DhwJ_NhNcouf_VR7mIe_k_cCtVzBB'
[download] Destination: Black Atlass - Paris-OTLUzIB4QHw.f251.webm
[download] 100% of 5.55MiB in 00:00
[ffmpeg] Merging formats into "Black Atlass - Paris-OTLUzIB4QHw.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Black Atlass - Paris-OTLUzIB4QHw.f247.webm' -i 'file:Black Atlass - Paris-OTLUzIB4QHw.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Black Atlass - Paris-OTLUzIB4QHw.temp.mkv'
Deleting original file Black Atlass - Paris-OTLUzIB4QHw.f247.webm (pass -k to keep)
Deleting original file Black Atlass - Paris-OTLUzIB4QHw.f251.webm (pass -k to keep)
```

**Comment by darwins-sugar-baby** [comment]
I have the same problem, and I have the same line that says 
load_entry_point('youtube-dl==2019.1.17', 'console_scripts', 'youtube-dl')()
but when I run
sudo youtube-dl -U
it says I'm up to date.
