### ISSUE TITLE
error message "this app cannot run on your pc "

### ISSUE THREAD

**Issue by JP3400** [ytdl-org/youtube-dl#29904]
Hello.
Sorry i don't speach english.
Sometimes, when i run youtube-dl, i have this error message : "this app cannot run on your pc "
Not all time, just sometimes. When i restart my PC, its work, but sometimes :)
I dont no how make.
Its just youtube-dl. Nothing else.
I have windows 10 pro 64 bits.
Youtube-dl version last (youtube-dl is up-to-date (2021.06.06))
Can you help me ?
Thank

**Comment by kikuyan** [comment]
[This reddit comment](https://www.reddit.com/r/youtubedl/comments/jfr43h/this_app_cant_run_on_your_pc_windows_10_error/ghrcagt/?utm_source=reddit&utm_medium=web2x&context=3
) might help. 

> Windows 10 can display this message if your youtube-dl executable is incomplete. Please double check your download of youtube-dl is completing successfully by verifying the correct size and signature.
