### ISSUE TITLE
403 Forbidden from YOUTUBE

### ISSUE THREAD

**Issue by stefanodvx** [ytdl-org/youtube-dl#29911]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
Removing cache dir /home/stefano/.cache/youtube-dl ..
[youtube] EWUbq35E4Q0: Downloading webpage
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.5 (CPython) - Linux-4.19.0-17-amd64-x86_64-with-glibc2.28
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {'http': 'socks5://eIWpWMowii:Bm3XlmOl8@lin.socks.ipvanish.com:1080', 'https': 'socks5://eIWpWMowii:Bm3XlmOl8@lin.socks.ipvanish.com:1080'}
Removing cache dir /home/stefano/.cache/youtube-dl ..
[youtube] EWUbq35E4Q0: Downloading webpage
[debug] Invoking downloader on 'https://r1---sn-hpa7zns6.googlevideo.com/videoplayback?expire=1630885507&ei=IwI1YbaMD-C_mLAP2cyk-Aw&ip=69.16.157.42&id=o-ADSYQRSD0BLQC7wrLYvu0JB6OGk_vKS_-DvSTu337wwa&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=e7&mm=31%2C29&mn=sn-hpa7zns6%2Csn-hpa7kn76&ms=au%2Crdu&mv=m&mvi=1&pl=24&gcr=it&initcwndbps=170000&vprv=1&mime=video%2Fmp4&ns=Z6GS61nRGwC_aLNBnJSRXeAG&gir=yes&clen=294979442&dur=1440.021&lmt=1630849507746373&mt=1630863405&fvip=1&keepalive=yes&fexp=24001373%2C24007246&beids=9466588&c=WEB&txp=5432434&n=O33GtKhf5XRH7WD&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgZHq1j4TtqoVcMlqQqsIj1KonbPWmk-1tY8vgzP-wmIkCIC4r5nVvXT9C0VJVEbA4HlaDNL8m3hP0Ws6E6JbVDqWR&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIBiviR9sYPPS18C3si4epwg4yTXDQLwOfDaB8kEJs4IAiASwGaeXj_zNW_Y2JqzIUuIWS_9T-PV2DEna5W-5gR1AQ%3D%3D'
[download] Destination: 243_EWUbq35E4Q0.f137
[download]   7.0% of 281.31MiB at 17.05MiB/s ETA 00:15ERROR: unable to download video data: HTTP Error 403: Forbidden
```

## Description

Download initially starting then stopping, soemtimes on 60%, sometimes on 3%, im using proxy (credentials on verbose), im removing cache too, these are my options:

```
opts = {
  "verbose": True,
  "proxy": PROXY,
  "format": "bestvideo[vcodec*=avc]+bestaudio",
  "outtmpl": file_name,
  "merge_output_format": "mkv",
}
```

**Comment by kikuyan** [comment]
Suspect a proxy problem, try others.

**Comment by stefanodvx** [comment]
> Suspect a proxy problem, try others.

can't use another proxy. looks like the connection with the proxy randomly end while downloading. is there a way to keep reconnecting? i must use this proxy

**Comment by kikuyan** [comment]
Then just rerun the same command. youtube-dl usually continues downloading where it last stopped.

**Comment by stefanodvx** [comment]
> Then just rerun the same command. youtube-dl usually continues downloading where it last stopped.

i mean a dynamic solution, not me just restarting the script until its done :/

**Comment by dirkf** [comment]
For example:
```
until youtube-dl -v --proxy PROXY -f 'bestvideo[vcodec*=avc]+bestaudio' -o file_name --merge_output_format mkv; do sleep 5; done
```

**Comment by 89z** [comment]
video is only available from Italy:

https://unblockvideos.com/youtube-video-restriction-checker#url=EWUbq35E4Q0

**Comment by dmak** [comment]
I have a similar issue. I execute `youtube-dl` with several URLs in the arguments and I get the similar error when N-th URL is retrieved (not the first one):
```
[youtube] _jqj7TBg5X8: Downloading webpage
ERROR: unable to download video data: HTTP Error 403: Forbidden
```
It looks like youtube starts to limit the client this way. Is it possible to implement the retrieve strategy with incremented delay between attempts for this case? `-R` argument does not affect the recovery for this case.

**Comment by dirkf** [comment]
Does this apply if yt-dl is run with the failing URL just after the multiple d/l failed?

What happens if you apply `--sleep-interval 20` or similar?

Are you using a proxy or VPN?

**Comment by dmak** [comment]
> Does this apply if yt-dl is run with the failing URL just after the multiple d/l failed?

Most of the times `youtube-dl` is able to download the URL which has previously failed with HTTP 403 after a short time (I have updated by post above), but I know some corner cases when the issue persisted.

> What happens if you apply `--sleep-interval 20` or similar?

I will certainly check this, thanks for the hint!
 
> Are you using a proxy or VPN?

I am running under proxy, however this should not be proxy limiting the access at least I don't see any issue in proxy logs. Nevertheless good point to check, needs some time for experiments and observations.

**Comment by dirkf** [comment]
Now: "Video unavailable"
