### ISSUE TITLE
ERROR: Unsupported URL:

### ISSUE THREAD

**Issue by Sailet03** [ytdl-org/youtube-dl#29910]
I am trying to download a video conferance for my mother but i get this error:

ERROR: Unsupported URL: https://api.screen9.com/preview/oumvmITQAovYsN1Hau8dexyXsdfUtCB6iK8DIvkiMW87r1SqGJEaMCAoaytx02lK

Is there a way around this or am i stuck?

**Comment by kikuyan** [comment]
For that video, you can find m3u8 playlist url in browser's dev tools. Pass the m3u8 playlist url to youtube-dl.
