### ISSUE TITLE
Song

### ISSUE THREAD

**Issue by Amaanackerman** [ytdl-org/youtube-dl#29913]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
The.song command didn't work on my user bot it's says pls report this issue everytime i try to use this command pls fix this problem

**Comment by Amaanackerman** [comment]
Hmm

**Comment by kikuyan** [comment]
I don't think it's possible. You're totally ignoring issue template and what the message says.
