### ISSUE TITLE
youtube_dl.utils.ExtractorError: This video is available to this channel's members on level: MemberShrimp! (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

### ISSUE THREAD

**Issue by Dominatorrrr** [ytdl-org/youtube-dl#29928]
C:\Users\JACK>youtube-dl -v --cookies C:\Users\JACK\AppData\Roaming\youtube-dl\youtube.com_cookies https://www.youtube.com/watch?v=zia8WGSmwB
[debug] System config: []
[debug] User config: ['-f', 'mp4', '-f', 'best', '-o', 'C:/User/JACK/Downloads/%(title)s.%(ext)s', '--no-mtime', '-U', '-v', '--update', '--continue', '--cookies']
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'C:\\Users\\JACK\\AppData\\Roaming\\youtube-dl\\youtube.com_cookies', 'https://www.youtube.com/watch?v=zia8WGSmwBo']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
youtube-dl is up-to-date (2021.06.06)
[youtube] zia8WGSmwBo: Downloading webpage
ERROR: Join this channel to get access to members-only content like this video, and other exclusive perks.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1713, in _real_extract
youtube_dl.utils.ExtractorError: Join this channel to get access to members-only content like this video, and other exclusive perks.

please help anyone

**Comment by dirkf** [comment]
Are you saying that you are a member of the channel and have [passed the cookies associated with your login in the file](https://github.com/ytdl-org/youtube-dl#user-content-how-do-i-pass-cookies-to-youtube-dl) `youtube.com_cookies`?

Your 'user config' `'-f', 'mp4', '-f', 'best', '-o', 'C:/User/JACK/Downloads/%(title)s.%(ext)s', '--no-mtime', '-U', '-v', '--update', '--continue', '--cookies'` is confused.
* you shouldn't have two `-f` options, as only the last will be seen. Perhaps you wanted `-f best[ext=mp4]`;
* you probably shouldn't put `-U` or `--update` in the configuration file, and certainly not both;
* you're making `--verbose` the default, which is fine if that's what you want;
* `--cookies` needs a parameter value (filename), as in your command line.

**Comment by Dominatorrrr** [comment]
No I'm not a member,is that possible to download, could you tell which command i needed to download videos, what command should i put in config file, could you show a tutorial please

**Comment by dirkf** [comment]
>No I'm not a member...

So that's your problem right there.

* Join the user's channel.
* Open the video page in your browser using your login with which you joined the channel.
* Gather the cookies as described in the link above and put them in the file, say `youtube.com_cookies` as in your original attempt.
* Try your original command again.

**Comment by Dominatorrrr** [comment]
Is there anyway to download or watch members only content without joining, Because twitch paid videos can watch from some sites like pogu.live,and youtube vanced breached premium content,I think nobody research that area

**Comment by Baa14453** [comment]
Your options are:

- Become a member
- Use someone else's account that is a member
- Watch the videos uploaded elsewhere by someone who is a member.

Youtube-DL can't bypass paid features, that's not possible.

**Comment by shaminh384-del** [comment]
This video is available to this channel's members on level: FREE (or any higher level). Join this YouTube channel from your computer or Android app.
