### ISSUE TITLE
youtube_dl.utils.DownloadError: ERROR: No video formats found

### ISSUE THREAD

**Issue by devilroogan** [ytdl-org/youtube-dl#29923]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by Vickyftw** [comment]
how to fix this error

**Comment by rautamiekka** [comment]
The template is 100% untouched, so there's no way to help either of you.

**Comment by weirdalsuperfan** [comment]
Lately I've been getting a LOT of errors like this. Half of this playlist gave them. At first I thought it was something to do with encryption on videos from official channels, but I'm not sure anymore. Could also just be hitting the website too much.

`[debug] System config: []

[debug] User config: []

[debug] Custom config: []

[debug] Command-line args: ['-ciw', '-x', '--audio-format', 'mp3', '-o', '%(title)s.%(ext)s', '--playlist-items', '15-128', 'https://www.youtube.com/playlist?list=PLT9cfjU1ykbM8dzxgifFEN7qZJtQNpEBJ', '--verbose']

[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932

[debug] youtube-dl version 2021.06.06

[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362

[debug] exe versions: ffmpeg 2.8.4

[debug] Proxy map: {}

[youtube:tab] PLT9cfjU1ykbM8dzxgifFEN7qZJtQNpEBJ: Downloading webpage

[download] Downloading playlist: 邦楽

[youtube:tab] Downloading page 1

[youtube:tab] playlist 邦楽: Downloading 114 videos

[download] Downloading video 1 of 114

[youtube] la35ph4gpuA: Downloading webpage

WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests

[youtube] la35ph4gpuA: Downloading API JSON

ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Traceback (most recent call last):

  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1715, in _real_extract
  
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
  
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by dirkf** [comment]
See #23638.
