### ISSUE TITLE
Youtube-dl downloads two formats of same video

### ISSUE THREAD

**Issue by aindriu80** [ytdl-org/youtube-dl#29936]
## Checklist

- [X ] I'm reporting a broken site support issue
- [X ] I've verified that I'm running youtube-dl version **2021.06.06**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X ] I've searched the bugtracker for similar bug reports including closed ones
- [X ] I've read bugs section in FAQ

## Verbose log

Below is the command I run when I want to download a few videos, 

```
while ! youtube-dl --verbose -a 11ú\ Méan\ Fómhair.txt -c --socket-timeout 5; do echo DISCONNECTED; sleep 5; done                                               

```
Usually, I go to my YT subscriptions & copy the URLs of the videos I want to watch and save them in a text file, then I execute the above command that reconnects if I get disconnected until all videos are downloaded. 

Below is a verbose log of a download

```
 

 ~/Íosluchtuithe  while ! youtube-dl --verbose -a 11ú\ Méan\ Fómhair.txt -c --socket-timeout 5; do echo DISCONNECTED; sleep 5; done                             INT х  took 14s  at 14:23:43 
[debug] System config: []
[debug] User config: ['-o', '~/Físeáin/Íosluchtuithe/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080]+bestaudio/best[height<=1080]']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-a', '11ú Méan Fómhair.txt', '-c', '--socket-timeout', '5']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=M576WGiDBdQ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.5 (CPython) - Linux-5.14.2-051402-generic-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] M576WGiDBdQ: Downloading webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r3---sn-xpgjvh-q0cd.googlevideo.com/videoplayback?expire=1631388257&ei=Aa48YY6jGM3N0wXq96TICQ&ip=212.129.73.154&id=o-AFuzzycGCjhFnTckAwhY94b-2x6ynjOvT538f-_K5iwP&itag=299&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303&source=youtube&requiressl=yes&mh=_P&mm=31%2C29&mn=sn-xpgjvh-q0cd%2Csn-q0c7rn76&ms=au%2Crdu&mv=m&mvi=3&pl=21&initcwndbps=427500&vprv=1&mime=video%2Fmp4&ns=NumSxER5_Rmo8vsJm0QL9iQG&gir=yes&clen=4578203069&dur=58931.058&lmt=1631088374895899&mt=1631366234&fvip=3&keepalive=yes&fexp=24001373%2C24007246&beids=9466587&c=WEB&txp=6316222&n=pwmb1J-n0NrToZqN&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgElonSXu7JRakC_C2F_CinRGvNna6U1kC2XVCgWQLsX8CIBq76qVmKtXTdbz8LZGwfV5QhBTBudp4mnvx7jKzzLTR&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAM28EVV2D8kL-PjpVXOx5KPx_KGI9vVlPnkCakZ5L_RtAiEArpyhwAP3_YrtRl8rSuZkxtwRgIhFw5jevMCwagUEEXI%3D'
[download] Destination: /home/aindriu/Físeáin/Íosluchtuithe/Solidity, Blockchain, and Smart Contract Course – Beginner to Expert Python Tutorial.f299.mp4
[download]   0.0% of 4.26GiB at 79.51KiB/s ETA 15:37:13^C
ERROR: Interrupted by user
DISCONNECTED
^C%                                                                                                                                                                                            ~/Íosluchtuithe  

```
The following is the config file of youtube-dl

```
# Always extract audio
# -x

# Do not copy the mtime
# --no-mtime

# Use this proxy
# --proxy 127.0.0.1:3128

# Save all videos under Movies directory in your home directory
 -o ~/Físeáin/Íosluchtuithe/%(title)s.%(ext)s

# Specifiying the quality of video
-f 'bestvideo[height<=1080]+bestaudio/best[height<=1080]'
```

## Description

I am having an issue with youtube-dl downloading both .MP4 and .MKV formats of the same video.  See the image below :

https://i.imgur.com/DrKPvaK.png

How can I force youtube-dl to either download either .MP4 OR .MKV? You can see with big files it's really frustrating

Is there somehow I can specify to download either MP4 or MKV?

**Comment by dirkf** [comment]
Do feel free to 

>PASTE VERBOSE LOG HERE

if you would like assistance.

**Comment by kikuyan** [comment]
https://github.com/ytdl-org/youtube-dl#bugs
> Do not post screenshots of verbose logs; only plain text is acceptable.

**Comment by avinashgbhosale** [comment]
I also faced same issue.

(ytd_venv) avinash@mahadev:~/mysqqq$ youtube-dl -ciw PL_RGaFnxSHWr_6xTfF2FrIw-NAOo3iWMy
[youtube:tab] PL_RGaFnxSHWr_6xTfF2FrIw-NAOo3iWMy: Downloading webpage
[download] Downloading playlist: SQL Tutorials
[youtube:tab] playlist SQL Tutorials: Downloading 56 videos
[download] Downloading video 1 of 56
[youtube] -thOn1NKJew: Downloading webpage
[download] Destination: SQL Tutorial - 1 - Introduction--thOn1NKJew.f247.webm
[download] 100% of 3.38MiB in 00:11
[download] Destination: SQL Tutorial - 1 - Introduction--thOn1NKJew.f251.webm
[download] 100% of 6.78MiB in 00:10
[ffmpeg] Merging formats into "SQL Tutorial - 1 - Introduction--thOn1NKJew.webm"
Deleting original file SQL Tutorial - 1 - Introduction--thOn1NKJew.f247.webm (pass -k to keep)
Deleting original file SQL Tutorial - 1 - Introduction--thOn1NKJew.f251.webm (pass -k to keep)
[download] Downloading video 2 of 56
[youtube] RHYLOdscpZI: Downloading webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: SQL Tutorial - 2 - Installing MySQL-RHYLOdscpZI.f247.webm
[download] 100% of 15.77MiB in 00:37
[download] Destination: SQL Tutorial - 2 - Installing MySQL-RHYLOdscpZI.f140.m4a
[download] 100% of 11.81MiB in 00:23
[ffmpeg] Merging formats into "SQL Tutorial - 2 - Installing MySQL-RHYLOdscpZI.mkv"
Deleting original file SQL Tutorial - 2 - Installing MySQL-RHYLOdscpZI.f247.webm (pass -k to keep)
Deleting original file SQL Tutorial - 2 - Installing MySQL-RHYLOdscpZI.f140.m4a (pass -k to keep)
[download] Downloading video 3 of 56
[youtube] 3EeYuDvM3zg: Downloading webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: SQL Tutorial - 3 - MySQL Workbench  and Command Line Client-3EeYuDvM3zg.f247.webm
[download] 100% of 6.54MiB in 00:14
[download] Destination: SQL Tutorial - 3 - MySQL Workbench  and Command Line Client-3EeYuDvM3zg.f140.m4a
[download] 100% of 5.43MiB in 00:09
[ffmpeg] Merging formats into "SQL Tutorial - 3 - MySQL Workbench  and Command Line Client-3EeYuDvM3zg.mkv"
Deleting original file SQL Tutorial - 3 - MySQL Workbench  and Command Line Client-3EeYuDvM3zg.f247.webm (pass -k to keep)
Deleting original file SQL Tutorial - 3 - MySQL Workbench  and Command Line Client-3EeYuDvM3zg.f140.m4a (pass -k to keep)
[download] Downloading video 4 of 56
[youtube] 7Yp2NtcjahM: Downloading webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.

**Comment by dirkf** [comment]
Please read the Fine Manual regarding Format Selection.

The default format selector is `bestvideo+bestaudio/best`.

Video 1: `bestvideo` was webm/VP9, `bestaudio` was webm/Opus; the two formats could be merged in a webm container.

Video 2:  `bestvideo` was webm/VP9, `bestaudio` was m4a/AAC: the two formats could only be merged in a mkv container.

Similarly for videos 3, 4.

yt-dl is doing what you asked it to do.

See [this issue](https://github.com/ytdl-org/youtube-dl/issues/29794#issuecomment-902140034) for more explanation and examples.

**Comment by aindriu80** [comment]
But some YouTube videos have better sound than video, would you not be lowering the quality?

I will try `bestvideo+bestaudio/best`
the config file.

**Comment by dirkf** [comment]
It's all about what codec combinations are valid in each type of container.

`-f best` will indeed typically select a combined format of lower quality (or at least, lower bit-rate) than the best separate video combined with the best separate audio. The linked issue gives examples of format selection to get media of the best available quality with a specific container type and/or with specific AV codecs.
