### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by pf0t0k9** [ytdl-org/youtube-dl#29935]
https://vod-secure.twitch.tv/0d5291b425e51bb9be1d_yhs0502_1140680427_1630967160/chunked/index-dvr.m3u8

youtube-dl is up-to-date (2021.06.06)
USER:~ USER$ youtube-dl https://vod-secure.twitch.tv/0d5291b425e51bb9be1d_yhs0502_1140680427_1630967160/chunked/index-dvr.m3u8
[generic] index-dvr: Requesting header
WARNING: Could not send HEAD request to https://vod-secure.twitch.tv/0d5291b425e51bb9be1d_yhs0502_1140680427_1630967160/chunked/index-dvr.m3u8: HTTP Error 403: Forbidden
[generic] index-dvr: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by kikuyan** [comment]
Do not make duplicate report. https://github.com/ytdl-org/youtube-dl/issues/29927#issuecomment-915689798
