### ISSUE TITLE
Question about verifying video integrity

### ISSUE THREAD

**Issue by nevereveneverreally** [ytdl-org/youtube-dl#29940]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I mainly use youtube-dl.exe (in combination with ffmpeg and ffprobe) to download videos from twitch.tv. To make sure no part of the video is corrupt after downloading it, I download the same video a second time and compare the checksum values of both downloads. If they match, I assume that no part of the video is corrupt. However, it occurred to me that both videos may still have unnoticed corruption, and downloading it a second time recreates that specific corruption, resulting in both videos having matching checksum values even though they're both corrupt. Could this scenario happen, for example, if the version of youtube-dl.exe I'm using gets partly corrupted on my end, causing a bug that corrupts downloads in a consistent way?

**Comment by dirkf** [comment]
If the video is being downloaded with HTTPS (and it almost always is nowadays), it's extremely unlikely that the saved video will be different from the source video on the site (unless you specifically modify the download, eg with a post-processing option). Even `--recode-video` doesn't affect the (audio/)video content, but just repackages it.

However that the format of the source video may itself be corrupt in some way (as the standards are so complex, it's possible for the format to be invalid and yet playable, and vice versa, depending on the player), or the video content may be corrupt (eg, telecine artefacts, wrong aspect ratio). Accurate transfer can only preserve such issues.

If you don't trust the yt-dl downloading code (which just uses Python library functions), you may be able (depending on the site) to use one of the supported external downloaders: then you only have to trust yt-dl to extract the download link, and of course the external downloader itself.
