### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 1: invalid start byte

### ISSUE THREAD

**Issue by dirk-1** [ytdl-org/youtube-dl#29946]
Downloads from youtube-channel TeletubbiesaufDeutsch are not possible, either single files, nor playlists nor the whole videos-list.
I used the latest version of youtube-dl. Another channel I tried to download from worked as expected, so it seems there is a difference.

root@user-vm2:/media/user/yt/Teletubbies# youtube-dl -v https://www.youtube.com/c/TeletubbiesaufDeutsch/videos
[debug] System config: []
[debug] User config: ['-i', '-f', 'best', '--write-thumbnail', '--all-subs', '--download-archive', '_ids.txt', '--abort-on-unavailable-fragment', '--write-description', '--no-overwrites', '--retries', '24']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/c/TeletubbiesaufDeutsch/videos']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Linux-5.11.0-34-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] TeletubbiesaufDeutsch: Downloading webpage
[download] Downloading playlist: Teletubbies auf Deutsch - WildBrain - Videos
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] Downloading page 3
[youtube:tab] Downloading page 4
[youtube:tab] Downloading page 5
[youtube:tab] Downloading page 6
[youtube:tab] Downloading page 7
[youtube:tab] Downloading page 8
[youtube:tab] Downloading page 9
[youtube:tab] Downloading page 10
[youtube:tab] Downloading page 11
[youtube:tab] Downloading page 12
[youtube:tab] Downloading page 13
[youtube:tab] Downloading page 14
[youtube:tab] Downloading page 15
[youtube:tab] Downloading page 16
[youtube:tab] Downloading page 17
[youtube:tab] Downloading page 18
[youtube:tab] Downloading page 19
[youtube:tab] Downloading page 20
[youtube:tab] Downloading page 21
[youtube:tab] Downloading page 22
[youtube:tab] Downloading page 23
[youtube:tab] Downloading page 24
[youtube:tab] Downloading page 25
[youtube:tab] Downloading page 26
[youtube:tab] Downloading page 27
[youtube:tab] Downloading page 28
[youtube:tab] playlist Teletubbies auf Deutsch - WildBrain - Videos: Downloading 863 videos
[download] Downloading video 1 of 863
ERROR: 'utf-8' codec can't decode byte 0xf6 in position 1: invalid start byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 933, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 1062, in __process_playlist
    reason = self._match_entry(entry, incomplete=True)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 756, in _match_entry
    if self.in_download_archive(info_dict):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 2157, in in_download_archive
    for line in archive_file:
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 1: invalid start byte

**Comment by dirkf** [comment]
The download archive is meant to be UTF-8 but contains a 0xf6 byte (presumably Latin-1 ö). In UTF-8, that should be [0xc3 0xb6](https://www.utf8-chartable.de/). This is quite irritating when all the character set encodings on your system are UTF-8.

Either some yt-dl code wrote data to the file without making it UTF-8 first, or some other tool did so.

You could try converting the archive file to UTF-8 using a suitable text or (advanced) hex editor or the [_iconv_ utility](https://linux.die.net/man/1/iconv).

Perhaps lines that can't be read should be skipped with a warning.
