### ISSUE TITLE
Weird behaviour with `exec` argument

### ISSUE THREAD

**Issue by AxoCode** [ytdl-org/youtube-dl#29959]
## Checklist

- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

```
[debug] System config: []
[debug] User config: ['-o', 'C:/Users/barra/Videos/youtube-dl/%(playlist_title)s (%(playlist_id)s)/%(playlist_index)s - %(title)s (%(id)s).%(ext)s', '-f', 'bestvideo[height<=?1080][ext=mp4]+bestaudio/best', '--no-mtime', '--write-sub', '--mark-watched', '--embed-thumbnail', '--embed-subs', '--exec', 'bash -c C:/Users/barra/Videos/youtube-dl/script.sh']
[debug] Custom config: []
[debug] Command-line args: ['bON-KPiiNCk', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
```

## Description

So I pass in `--exec "wsl --exec /mnt/c/Users/barra/Videos/youtube-dl/script.sh"` argument into youtube-dl, but after downloading, there is an error
```
'wsl' is not recognized as an internal or external command,
operable program or batch file.
```
So, I just run `wsl --exec /mnt/c/Users/barra/Videos/youtube-dl/script.sh` in Command Prompt, PowerShell, Git Bash. But all worked.

Then, I try another method, I use `--exec "bash C:/Users/barra/Videos/youtube-dl/script.sh"`, But there is an error
```
C:/Users/barra/Videos/youtube-dl/script.sh: line 6: rename: command not found
```
I already install `rename` (So it doesn't recognize non-bash command line). In fact, I can run `bash C:/Users/barra/Videos/youtube-dl/script.sh` in the Command Prompt, PowerShell, Git Bash. But all worked.

Last, I try using `-c` so it will be `--exec "bash -c C:/Users/barra/Videos/youtube-dl/script.sh"`. But it's the same error without the `-c`.

**Comment by dirkf** [comment]
If you didn't manage to get this working, you should have just used the shell `&&` operator instead of `--exec ...` (since you didn't need the `{}` substitution).

There was plainly some difference in the executable search path in the `--exec ...` context.
