### ISSUE TITLE
Hashtags only pull 400/500ish videos

### ISSUE THREAD

**Issue by Miosame** [ytdl-org/youtube-dl#29952]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Take for example `#happydog`:
https://www.youtube.com/hashtag/happydog

The page says `9.7K videos • 3K channels`, but youtube-dl will only pull 438 of them, other hashtags are similar, it's always around 430-550 videos no matter how many videos a hashtag may have.

Is this a known limitation of sorts? or is it a bug.

**Comment by coletdjnz** [comment]
Appears to be a limitation (unknowingly if on purpose) YouTube side. If you scroll down ~7 pages on the web, you'll notice it doesn't load any more pages.

May have some relation to how,  to name a few,  YouTube search, mixes & comments (sorted by top) never return all results and the amount that is returned is not always the same.

**Comment by dirkf** [comment]
The G search algorithm may not know how many results there are until it's tried to fetch them. It probably uses some parallel opportunistic strategy rather than the equivalent of `select count(*) from TBL_VIDEOS where ...`.

You can see this also in plain web searches.

**Comment by Miosame** [comment]
@coletdjnz @dirkf 
> If you scroll down ~7 pages
> You can see this also in plain web searches.

indeed I can replicate that and didn't notice the first time, I guess the only other alternative is using youtube's API to prefetch the URLs and then youtube-dl them, thanks!

If someone in the future knows another way to e.g. fetch more for a hashtag or search, please feel free to add to this issue, but I'll close it for now.

**Comment by Lee-Carre** [comment]
Could just brute-force it; keep polling the same URL (with a suitable delay, between), and collect the videos in the response into a list, then run `uniq` on said list.

Keep polling until you've got as many unique videos as you desire.
