### ISSUE TITLE
Always error

### ISSUE THREAD

**Issue by SAJALMAURYA** [ytdl-org/youtube-dl#29953]
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by kikuyan** [comment]
Do not ignore the message.

**Comment by rautamiekka** [comment]
That error by itself is worthless and skipping the template even more so in particular. Don't skip the template.
