### ISSUE TITLE
Hello My bot is not working due to old version please support bot and help in commands on new version please

### ISSUE THREAD

**Issue by Darshudacchu** [ytdl-org/youtube-dl#29979]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by oskiwii** [comment]
lol u need to fill it out

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29984
