### ISSUE TITLE
https://ocw.mit.edu/courses

### ISSUE THREAD

**Issue by RandyMcMillan** [ytdl-org/youtube-dl#29977]
- [X] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
![Screen Shot 2021-09-16 at 9 50 01 AM](https://user-images.githubusercontent.com/152159/133624479-d9bbed45-663e-47b3-8731-54a29973dd44.png)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs violate any copyrights
- [X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs
https://ocw.mit.edu/courses/media-arts-and-sciences/mas-s62-cryptocurrency-engineering-and-design-spring-2018/lecture-videos/index.htm

**Comment by dirkf** [comment]
You have to download from each of the lecture pages individually, eg, for lecture 1, https://ocw.mit.edu/courses/media-arts-and-sciences/mas-s62-cryptocurrency-engineering-and-design-spring-2018/lecture-videos/lec1-signatures-hashing-hash-chains-e-cash-and-motivation/
