### ISSUE TITLE
Can't download 1 hour 42min video

### ISSUE THREAD

**Issue by gin9980** [ytdl-org/youtube-dl#29985]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '18', 'https://www.youtube.com/watch?v=OJWbI2qw6nU']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2020-05-01-39fb1e9, ffprobe git-2020-05-01-39fb1e9
[debug] Proxy map: {'no': '192.168.99.100'}
[youtube] OJWbI2qw6nU: Downloading webpage
[debug] Invoking downloader on 'https://r5---sn-8pgbpohxqp5-ajtl.googlevideo.com/videoplayback?expire=1631977176&ei=eKpFYcusL6GCp-oPkfmNoA8&ip=82.34.6
7.16&id=o-AMT0YHkpuqUHr2YoB6pKM1hOecMmGOlcq3ZUL1yVhw4U&itag=18&source=youtube&requiressl=yes&mh=H7&mm=31%2C29&mn=sn-8pgbpohxqp5-ajtl%2Csn-8pgbpohxqp5-aigy&ms=au%2Crdu&mv=m&mvi=5&pl=21&initcwndbps=2131250&vprv=1&mime=video%2Fmp4&ns=_sKl_n30OJFYXk1EJFH17XIG&gir=yes&clen=258313848&ratebypass=yes&dur=6140.818&lmt=1575364564771289&mt=1631955180&fvip=4&fexp=24001373%2C24007246&c=WEB&txp=2311222&n=o67B331c1E8Osx&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhA
N6cxeipD7K-CatJrKX8QTU2NdoYQ7mWVhJcbJpmFV_nAiEAhbMsBsCPE1ajbEjI-NnI-7RIn58yA_mMmobFrxXN8BI%3D&sig=AOq0QJ8wRQIhAImZ1ZOYnnmx-eQiUXBo04prWACE_3-u7-tQ2O1bvwYUAiBaI2hzrNmwVrp5dSK_EeqtIj4mbgXnphyP-jPkD8W9kg=='
ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1279, in connect
  File "C:\Python\Python34\lib\http\client.py", line 871, in connect
  File "C:\Python\Python34\lib\socket.py", line 516, in create_connection
  File "C:\Python\Python34\lib\socket.py", line 507, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 1976, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 1915, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\downloader\http.py", line 351, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\downloader\http.py", line 116, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\downloader\http.py", line 110, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\utils.py", line 2737, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```

## Description

WRITE DESCRIPTION HERE
trying to download this specific video but it does not work. https://www.youtube.com/watch?v=OJWbI2qw6nU
I've used youtube-dl -f 18 https://www.youtube.com/watch?v=OJWbI2qw6nU and youtube-dl -f https://www.youtube.com/watch?v=OJWbI2qw6nU and it comes up as this error "ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>"

**Comment by 89z** [comment]
Since its just audio, you can get the audio format:

~~~
youtube -v -1 -a 251 OJWbI2qw6nU
~~~

https://github.com/89z/mech

**Comment by gin9980** [comment]
> 
> 
> Since its just audio, you can get the audio format:
> 
> ```
> youtube -v -1 -a 251 OJWbI2qw6nU
> ```
> 
> https://github.com/89z/mech

Do I have to use the one in your link or does youtube-dl not work at all for downloading this?

**Comment by 89z** [comment]
You tell me, does it look like YouTube-DL works?

**Comment by october262** [comment]
for this video -  https://www.youtube.com/watch?v=OJWbI2qw6nU
add  -o "%(id)s.%(ext)s"   so  it looks like this  youtube-dl -o "%(id)s.%(ext)s"  https://www.youtube.com/watch?v=OJWbI2qw6nU
the video will now download.

**Comment by gin9980** [comment]
> 
> 
> for this video - https://www.youtube.com/watch?v=OJWbI2qw6nU i don't get the
> error above, i just get error file name too long. so i
> add -o "%(id)s.%(ext)s" so it looks like this youtube-dl -o "%(id)s.%(ext)s" https://www.youtube.com/watch?v=OJWbI2qw6nU
> the video will now download.

still getting the same error message using this command

**Comment by dirkf** [comment]
So does this format play in the browser?

And if so, is any required proxy configuration being passed to yt-dl?

It appears that something is blocking your connection. (WorksForMe)

**Comment by gin9980** [comment]
> 
> 
> So does this format play in the browser?
> 
> And if so, is any required proxy configuration being passed to yt-dl?
> 
> It appears that something is blocking your connection. (WorksForMe)

I can download any other youtube video but not this one. How can I troubleshoot why it blocks the connection when downloading this video? I've tried downloading 5 hour long videos and it works fine

**Comment by october262** [comment]
> > for this video - https://www.youtube.com/watch?v=OJWbI2qw6nU i don't get the
> > error above, i just get error file name too long. so i
> > add -o "%(id)s.%(ext)s" so it looks like this youtube-dl -o "%(id)s.%(ext)s" https://www.youtube.com/watch?v=OJWbI2qw6nU
> > the video will now download.
> 
> still getting the same error message using this command

found at least 2 more posts with the same error
and it is an issue with your network connection.

**Comment by dirkf** [comment]
Also, try `-f 134+140`.

**Comment by gin9980** [comment]
> 
> 
> > > for this video - https://www.youtube.com/watch?v=OJWbI2qw6nU i don't get the
> > > error above, i just get error file name too long. so i
> > > add -o "%(id)s.%(ext)s" so it looks like this youtube-dl -o "%(id)s.%(ext)s" https://www.youtube.com/watch?v=OJWbI2qw6nU
> > > the video will now download.
> > 
> > 
> > still getting the same error message using this command
> 
> found at least 2 more posts with the same error
> and it is an issue with your network connection.

I can play the video in my browser with no problems. I can download any other youtube video without errors but not this one why is that?

**Comment by october262** [comment]
> > > > for this video - https://www.youtube.com/watch?v=OJWbI2qw6nU i don't get the
> > > > error above, i just get error file name too long. so i
> > > > add -o "%(id)s.%(ext)s" so it looks like this youtube-dl -o "%(id)s.%(ext)s" https://www.youtube.com/watch?v=OJWbI2qw6nU
> > > > the video will now download.
> > > 
> > > 
> > > still getting the same error message using this command
> > 
> > 
> > found at least 2 more posts with the same error
> > and it is an issue with your network connection.
> 
> I can play the video in my browser with no problems. I can download any other youtube video without errors but not this one why is that?

while signed in to youtube, try using the authenticated cookies option
and see if the video will download.

**Comment by gin9980** [comment]
> 
> 
> > > > > for this video - https://www.youtube.com/watch?v=OJWbI2qw6nU i don't get the
> > > > > error above, i just get error file name too long. so i
> > > > > add -o "%(id)s.%(ext)s" so it looks like this youtube-dl -o "%(id)s.%(ext)s" https://www.youtube.com/watch?v=OJWbI2qw6nU
> > > > > the video will now download.
> > > > 
> > > > 
> > > > still getting the same error message using this command
> > > 
> > > 
> > > found at least 2 more posts with the same error
> > > and it is an issue with your network connection.
> > 
> > 
> > I can play the video in my browser with no problems. I can download any other youtube video without errors but not this one why is that?
> 
> while signed in to youtube, try using the authenticated cookies option
> and see if the video will download.

what is the authenticated cookies option?

**Comment by dirkf** [comment]
Run this command:
```
youtube-dl -g -f 18  "https://www.youtube.com/watch?v=OJWbI2qw6nU"
```
(where `-g` is a synonym for `--get-url`)
It should print a long URL like the one listed above in the line beginning `[debug] Invoking downloader on ...`. Copy the URL, paste it into the browser's address bar, and go to the URL. You should see either a video player in the browser, or a 'Save link as... dialog. If so, the browser has some network setting, like a proxy, that isn't set up for yt-dl.

**Comment by gin9980** [comment]
> 
> 
> Run this command:
> 
> ```
> youtube-dl -g -f 18  "https://www.youtube.com/watch?v=OJWbI2qw6nU"
> ```
> 
> (where `-g` is a synonym for `--get-url`)
> It should print a long URL like the one listed above in the line beginning `[debug] Invoking downloader on ...`. Copy the URL, paste it into the browser's address bar, and go to the URL. You should see either a video player in the browser, or a 'Save link as... dialog. If so, the browser has some network setting, like a proxy, that isn't set up for yt-dl.

says The connection has timed out

**Comment by october262** [comment]
> > > > > > for this video - https://www.youtube.com/watch?v=OJWbI2qw6nU i don't get the
> > > > > > error above, i just get error file name too long. so i
> > > > > > add -o "%(id)s.%(ext)s" so it looks like this youtube-dl -o "%(id)s.%(ext)s" https://www.youtube.com/watch?v=OJWbI2qw6nU
> > > > > > the video will now download.
> > > > > 
> > > > > 
> > > > > still getting the same error message using this command
> > > > 
> > > > 
> > > > found at least 2 more posts with the same error
> > > > and it is an issue with your network connection.
> > > 
> > > 
> > > I can play the video in my browser with no problems. I can download any other youtube video without errors but not this one why is that?
> > 
> > 
> > while signed in to youtube, try using the authenticated cookies option
> > and see if the video will download.
> 
> what is the authenticated cookies option?

if you use firefox, install the addon cookies.txt 
for chrome, it's get cookies.txt
go back to youtube while signed in and back to this video  https://www.youtube.com/watch?v=OJWbI2qw6nU click on get cookies.txt and select export it will save a cookie file
now, run youtube-dl -o "%(id)s.%(ext)s" https://www.youtube.com/watch?v=OJWbI2qw6nU --cookies "paste the cookie file.txt" here without the quotes. now see if the video will download.

**Comment by dirkf** [comment]
> says The connection has timed out when pasting the link into the browser

At least that's consistent. Your network is blocking the URL. Try the same thing with `-f 140` instead of `-f 18`, to get just the mp4/AAC audio.

Cookies couldn't cause the connection attempt to time out, because the server needs to make the connection first before checking your cookie.

**Comment by gin9980** [comment]
> 
> 
> > says The connection has timed out when pasting the link into the browser
> 
> At least that's consistent. Your network is blocking the URL. Try the same thing with `-f 140` instead of `-f 18`, to get just the mp4/AAC audio.
> 
> Cookies couldn't cause the connection attempt to time out, because the server needs to make the connection first before checking your cookie.

still the same error with "-f 140"

**Comment by dirkf** [comment]
And you can still play the same video in the browser using the YT site?

**Comment by gin9980** [comment]
> 
> 
> And you can still play the same video in the browser using the YT site?

yes
