### ISSUE TITLE
libsyn.com is not anymore supported

### ISSUE THREAD

**Issue by eexexiexit** [ytdl-org/youtube-dl#29981]
libsyn is listed on https://github.com/ytdl-org/youtube-dl/blob/master/docs/supportedsites.md, but the site content does not actually download anymore. Here is an example trace:

<pre>
youtube-dl --verbose  https://dhenage.libsyn.com/crypto-gram-may-15-2021
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://dhenage.libsyn.com/crypto-gram-may-15-2021']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-12-amd64-x86_64-with-debian-10.0
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] crypto-gram-may-15-2021: Requesting header
WARNING: Falling back on generic information extractor.
[generic] crypto-gram-may-15-2021: Downloading webpage
[generic] crypto-gram-may-15-2021: Extracting information
ERROR: Unsupported URL: https://dhenage.libsyn.com/crypto-gram-may-15-2021
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2503, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2571, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2560, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: mismatched tag: line 211, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://dhenage.libsyn.com/crypto-gram-may-15-2021
</pre>

**Comment by october262** [comment]
for this link - https://dhenage.libsyn.com/crypto-gram-may-15-2021
click where it says POD next to Crypto-Gram May 15, 2021
then copy the new link to download the podcast.

**Comment by eexexiexit** [comment]
youtube-dl http://traffic.libsyn.com/dhenage/crypto-gram-2021-05.mp3?dest-id=19374

yields:

[generic] crypto-gram-2021-05: Requesting header
WARNING: Could not send HEAD request to http://traffic.libsyn.com/dhenage/crypto-gram-2021-05.mp3?dest-id=19374: <urlopen error [Errno 110] Connection timed out>

Download with firefox works...

**Comment by dirkf** [comment]
Works in git master and also in releases back to 2021.06.06.
```ShellSession
$ python -m youtube_dl -v -F 'http://traffic.libsyn.com/dhenage/crypto-gram-2021-05.mp3?dest-id=19374'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'http://traffic.libsyn.com/dhenage/crypto-gram-2021-05.mp3?dest-id=19374']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 675e4ca6d
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[generic] crypto-gram-2021-05: Requesting header
[redirect] Following redirect to https://content.libsyn.com/p/7/8/e/78e1345e5655a751/crypto-gram-2021-05.mp3?c_id=105447689&cs_id=105447689&destination_id=19374&response-content-type=audio%2Fmpeg&Expires=1650287137&Signature=J5uANt4VSFlVA1UYo9b1Y4zRhrSDIO2Bn2tL8pUwoNZpOmImu9WR1A6-j5Z1xcGN6NYZWUgU-L-i7KwmC0CfrHTszjr0KwXdxsrUJs3J6qRikz3L7NkJVLnqnT-OH-HgVrBATxzCXGPbHiGi9y1K3NPKHwsOX7Uk0Y63m0YFLUS4ZlYg43pvX4RrJHx8XIlKnIu0miMPKyPZyKbQfggjr~knxqonVPOxIDjEPLC0SmauXSJ8lnYbx~6pmfBMTmEGGb8h87O3AuxqZMCETO9oT9rGr5qMFpOFhE4n~IVk3GtiBiK-y9mRIhLzWij1fZwmU9olhfxg~nqpUmlOvUFGzg__&Key-Pair-Id=K1YS7LZGUP96OI
[generic] crypto-gram-2021-05: Requesting header
[info] Available formats for crypto-gram-2021-05:
format code  extension  resolution note
mpeg         mp3        audio only 
$
```
