### ISSUE TITLE
7News Sydney bulletin gets a "DRM protected" error

### ISSUE THREAD

**Issue by FlaminHat** [ytdl-org/youtube-dl#29994]
When I download the bulletin of 7NEWS Sydney for Saturday, all is fine:

```
youtube-dl https://7plus.com.au/seven-news-sydney?episode-id=7NNS21-261 -o "7NEWS Sydney, 2021 September 18.mp4" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://7plus.com.au/seven-news-sydney?episode-id=7NNS21-261', '-o', '7NEWS Sydney, 2021 September 18.mp4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Python version 3.5.2 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[7plus] 7NNS21-261: Downloading JSON metadata
[7plus] 7NNS21-261: Downloading m3u8 information
[7plus] 7NNS21-261: Downloading MPD manifest
[7plus] 7NNS21-261: Downloading MPD manifest
[7plus] 7NNS21-261: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://manifest.prod.boltdns.net/manifest/v1/hls/v5/aes128/5303576322001/d778d999-3722-4c8c-80a5-8622bfa6a18a/1ff5c744-0ec7-4867-992b-48fefebb37bb/10s/rendition.m3u8?fastly_token=NjE0NzkyN2RfYjEwNDA3OWU4YjkzZjA4NjFhOTI5YjA3MmFiYzc0MjJlZTNlMjQ2YzU5ZGI2NGQyZDliM2YwMTMxODNkYWYxOA%3D%3D'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 268
[download] Destination: 7NEWS Sydney, 2021 September 18.fhls-1897.mp4
[download]   1.2% of ~525.38MiB at  1.39MiB/s ETA 06:20.....

```

But when I try to download last night's bulletin, it cops out immediately with an error message saying it's "DRM protected"

```
youtube-dl https://7plus.com.au/seven-news-sydney?episode-id=7NNS21-262 -o "7NEWS Sydney, 2021 September 19.mp4" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://7plus.com.au/seven-news-sydney?episode-id=7NNS21-262', '-o', '7NEWS Sydney, 2021 September 19.mp4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Python version 3.5.2 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[7plus] 7NNS21-262: Downloading JSON metadata
ERROR: This video is DRM protected.
Traceback (most recent call last):
  File "/Users/imac/miniconda3/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/imac/miniconda3/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/imac/miniconda3/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Users/imac/miniconda3/lib/python3.5/site-packages/youtube_dl/extractor/sevenplus.py", line 71, in _real_extract
    info = self._parse_brightcove_metadata(media, episode_id)
  File "/Users/imac/miniconda3/lib/python3.5/site-packages/youtube_dl/extractor/brightcove.py", line 550, in _parse_brightcove_metadata
    raise ExtractorError('This video is DRM protected.', expected=True)
youtube_dl.utils.ExtractorError: This video is DRM protected.
```

I have brought the "DRM Protected" error up in other threads here, but people seem to think I am trying to "open an encrypted file", which is not the same as trying to download it. How does it know if it's encrypted before even downloading it?

**Comment by codehound-00** [comment]
You've answered your own question, youtube-dl have never supported DRM - move to yt-dlp

**Comment by dirkf** [comment]
It looks at the metadata that says it is. It counts the number of sources and the number that are flagged as protected. If those numbers are equal and > 0, there are no unprotected sources.

**Comment by bnw42** [comment]
7+ DRM's most of their videos and those shows that are not DRM'd have random episodes DRM'd for good measure. Even things like the news have random episodes DRM'd.

If you get a DRM error message the video is DRM protected and youtube-dl (& yt-dlp as well for that matter) will NOT download a DRM protected file. Or open it, depending on the semantics you wish to use. In order to download a file, you have to open it. :)

And as dirkf noted, DRM encryption is in the metadata, which is downloaded BEFORE any attempt is made to download the video itself. When yt-dl sees DRM in the metadata, it exits with the DRM message. The media industry has drawn it's line in the sand with DRM. They'll turn a blind eye to downloaders that break brightcove etc, but any that break DRM are instantly drowned in an avalanche of lawyers.

If you need to download DRM protected files you'll need to invest in one of the handful of commercial downloaders and one that not only breaks DRM but will break DRM on 7+. They also tend to come from jurisdictions that have a rather more casual approach to copyright compared to western countries, so caveat emptor!

**Comment by codehound-00** [comment]
> 7+ DRM's most of their videos and those shows that are not DRM'd have random episodes DRM'd for good measure. Even things like the news have random episodes DRM'd.
> 
> If you get a DRM error message the video is DRM protected and youtube-dl (& yt-dlp as well for that matter) will NOT download a DRM protected file. Or open it, depending on the semantics you wish to use. In order to download a file, you have to open it. :)
> 
> And as dirkf noted, DRM encryption is in the metadata, which is downloaded BEFORE any attempt is made to download the video itself. When yt-dl sees DRM in the metadata, it exits with the DRM message. The media industry has drawn it's line in the sand with DRM. They'll turn a blind eye to downloaders that break brightcove etc, but any that break DRM are instantly drowned in an avalanche of lawyers.
> 
> If you need to download DRM protected files you'll need to invest in one of the handful of commercial downloaders and one that not only breaks DRM but will break DRM on 7+. They also tend to come from jurisdictions that have a rather more casual approach to copyright compared to western countries, so caveat emptor!

Not true. Unlike youtube-dl which will not DL drm; yt-dlp does. I use it daily for this purpose.

**Comment by bnw42** [comment]
It must be very site specific then since I've had no success getting yt-dlp work with 7+. Not that I've tried very hard.

**Comment by codehound-00** [comment]
PM me some details and I'll look.

yt-dlp --allow-unplayable-formats --no-check-certificate -F "url"

....to see Formats

**Comment by dirkf** [comment]
> > ...
> > And as dirkf noted, DRM encryption is in the metadata, which is downloaded BEFORE any attempt is made to download the video itself. When yt-dl sees DRM in the metadata, it exits with the DRM message. ...
> Not true. Unlike youtube-dl which will not DL drm and the devps claim it never will in the future either; yt-dlp does. I use it daily for this purpose.
>...
Are you saying that some 7+ videos with a DRM flag are not actually encrypted? As that is plainly not an "effective technical mechanism", there should be no problem in ignoring the flag, unless the only way to discover the playability of a flagged video is to download and try to play it.

**Comment by codehound-00** [comment]
No I'm not saying that. What I am saying (repeat) is that unlike yt-dl, yt-dlp [b]can[/b] DL encrypted files.

**Comment by dirkf** [comment]
What should OP do with the DRM encrypted download? Wouldn't it be easier to generate such a file by a command beginning `dd if=/dev/random ...`?

**Comment by codehound-00** [comment]
If its a dash stream, controlled normally from an mpd (or m3u8), to DL the required video quality stream seaparately to the required audio stream. Decrypt both. Then mux both together with ffmpeg.

ffmpeg -i video.mp4 -i audio.m4a -c copy output.mp4

**Comment by codehound-00** [comment]
No problem. But not for discussion in public...PM or DM.
