### ISSUE TITLE
Drag & drop URL from address bar into folder = automagically convert + download

### ISSUE THREAD

**Issue by grand-lotus-iroh** [ytdl-org/youtube-dl#30000]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How would I go about finding out how to drag & drop shortcut URL from browser address bar into folder to auto download / convert to audio mp3? It would work something like this: 

![8t9-514](https://user-images.githubusercontent.com/1291364/134059471-028a7be9-c1f2-4c5f-a179-5a9430cd304a.gif)

**Comment by zulc22** [comment]
that would be very complex to make possible, but I don't quite think this question belongs here

**Comment by AyrA** [comment]
URL links are simple text files in INI file format. A simple powershell script could be used to extract the link and feed into youtube-dl
