### ISSUE TITLE
youtube_dl.utils.DownloadError

### ISSUE THREAD

**Issue by rakeshyt** [ytdl-org/youtube-dl#30006]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by nicolaasjan** [comment]
What are we supposed to do with this little information?
Please provide a verbose log.
`youtube-dl -v "URL"`

**Comment by rakeshyt** [comment]
Close
