### ISSUE TITLE
Nicovideo; Unable to find URL

### ISSUE THREAD

**Issue by vastcast** [ytdl-org/youtube-dl#30003]
`[niconico] sm17195023: Downloading webpage
[niconico] sm17195023: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`
Here is a full screenshot, and proof that i am in the latest version as of now.
![Image](https://file.coffee/u/f9IZgqREOXlEY3.png)

**Comment by kikuyan** [comment]
Search before making a new issue. Read #29974, #29225.
Do not post screenshot. Read https://github.com/ytdl-org/youtube-dl#bugs

**Comment by vastcast** [comment]
> 
> 
> Search before making a new issue. Read #29974, #29225.
> Do not post screenshot. Read https://github.com/ytdl-org/youtube-dl#bugs

oh sorry
