### ISSUE TITLE
Can not download youtube.exe from release

### ISSUE THREAD

**Issue by masirof** [ytdl-org/youtube-dl#30001]
Click
![20210921_144858](https://user-images.githubusercontent.com/41544743/134118659-65e14c2f-da48-434c-ac61-bd53f8dcd5a2.jpg)

Displayed
![Screenshot_20210921-144354_Chrome](https://user-images.githubusercontent.com/41544743/134118702-936de378-1595-4aa6-aa9c-1c68f9bc879d.jpg)

**Comment by zulc22** [comment]
[this is a site-wide issue.](https://github.community/t/signaturedoesnotmatch-error-downloading-release/202138/9)

**Comment by masirof** [comment]
Bug fixed
