### ISSUE TITLE
Slow downloading

### ISSUE THREAD

**Issue by qo4on** [ytdl-org/youtube-dl#30004]
I start downloading `youtube-dl -f 313 https://www.youtube.com/watch?v=i7YnsPVnrv0` and see that the speed is `67.53KiB/s`. Then I cancel downloading and run it again at `11.17MiB/s`. I have a very good internet connection. Why do I sometimes see such a slow speed?

**Comment by coletdjnz** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29326

**Comment by 89z** [comment]
Do you have a device that can display 4K?

**Comment by qo4on** [comment]
> #29326

Thank you. It looks like we have to use https://github.com/yt-dlp/yt-dlp to fix this problem.

> Do you have a device that can display 4K?

No

**Comment by 89z** [comment]
The format you are trying to download is 4K. Unless you have a device that can display 4K, then thats a pointless download. You can reduce the download size by up to 80% by just downloading 1080p instead.

**Comment by qo4on** [comment]
I do not talk about playing this video. I'm just downloading it.

**Comment by triplesixman** [comment]
> Sorry, but its a fair question. If you have no justification for needing 4K, then dont be surprised if no one wants to help you.

Wtf are you saying. If what you have to say is not relevant to the author of this topic, then refrain from responding.
