### ISSUE TITLE
Extractor-specific options?

### ISSUE THREAD

**Issue by iwsfg** [ytdl-org/youtube-dl#30018]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is it possible to declare extractor-specific output names in a config file somehow? 

From what I understand the answer is no. Config file is rather simple and it's just being merged with the command line arguments. 

I would like to apply different name formats when archiving videos from different services. I can probably do this in two passes with a wrapper script that would first fetch link details with `-g` argument, parse extractor name from the output and then based on that apply a desired pattern for the second call, but it's rather cumbersome and I would love to be able to list those in a youtube-dl config file directly with something like that:

```ini
[youtube]
-o "%(channel)s/%(title)s - %(id)s.%(ext)s"

[twitch:clips]
-o "[%(creator)s] %(title)s - %(id)s.%(ext)s"

[default]
-o "%(title)s - %(id)s.%(ext)s"
```

Then it all could be done in one pass, after correct extractor is determined but nothing is written to disk yet.

I was not able to find mentions of anything simillar in the existing issues (and in google as well) but mayhaps I was searching by wrong keywords,  
Thank you.

**Comment by dirkf** [comment]
You aren't the first person to ask this: see #29523 for the last time and further discussion.

You might also find the extractor value `ie_key` useful to assign downloads to names or folders according to the extractor.

**Comment by iwsfg** [comment]
Ah, my bad, I thought I looked well enough. I'm closing the issue in favor of that one.
Thank you!
