### ISSUE TITLE
YouTube video - invalid URL

### ISSUE THREAD

**Issue by grubeli** [ytdl-org/youtube-dl#30012]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

Via Python API
```
data = ydl.extract_info(video_url, download=False)
```

## Description

`data` return by the instruction above returns details about the `video_url` including "url" field which points to a playable url for the video (direct video link), it's works for most of cases but I found a video `https://www.youtube.com/watch?v=Hi0zbU3DW6o` and when I provide this url, then data["url"] contains path but it's not playable, even though `formats` contain all kind of video urls and they are playable.
So, my issue is that `url` extracted from the command is not valid.
For other videos it works well

**Comment by dirkf** [comment]
It would have been helpful to show the problem URL and explain how it didn't play.

You should have got a result like this:
```
$ youtube-dl -v -g 'https://www.youtube.com/watch?v=Hi0zbU3DW6o'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-g', 'https://www.youtube.com/watch?v=Hi0zbU3DW6o']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
https://r1---sn-cu-aigsl.googlevideo.com/videoplayback?expire=1632499261&ei=3aFNYfOPN8vSxwLg-4vgBA&ip=51.6.64.237&id=o-AHXHtYRE4fZqot1nDA4UYPcP8_XJOk3HldqHkY9fm2PZ&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=1G&mm=31%2C29&mn=sn-cu-aigsl%2Csn-cu-c9ie&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=25&initcwndbps=870000&vprv=1&mime=video%2Fmp4&ns=DHMix2ovqmyxjIijBC6stgoG&gir=yes&clen=88453793&dur=456.164&lmt=1632411776758895&mt=1632477423&fvip=10&keepalive=yes&fexp=24001373%2C24007246&beids=9466586&c=WEB&txp=6432434&n=S38A6yFXGzFrhj7&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALtazZHZ9vpDOHqv29SgwhGTT3Ks4HjBoVpy_HkqN3bbAiEAiJ3NCzOnLvD4VQyQ6fQ7jhAS4mBjv87z6K7BH79RdOY%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgLv1hctnsdD0vrfUkA5VALLs2AttS3qVbHg9O8mvcB5gCIFGTcn5cLUMY9HhkEfGpRDwyFmLJg9NfLinL-XjqEDkQ
https://r1---sn-cu-aigsl.googlevideo.com/videoplayback?expire=1632499261&ei=3aFNYfOPN8vSxwLg-4vgBA&ip=51.6.64.237&id=o-AHXHtYRE4fZqot1nDA4UYPcP8_XJOk3HldqHkY9fm2PZ&itag=140&source=youtube&requiressl=yes&mh=1G&mm=31%2C29&mn=sn-cu-aigsl%2Csn-cu-c9ie&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=25&initcwndbps=870000&vprv=1&mime=audio%2Fmp4&ns=DHMix2ovqmyxjIijBC6stgoG&gir=yes&clen=7384202&dur=456.225&lmt=1632409454413201&mt=1632477423&fvip=10&keepalive=yes&fexp=24001373%2C24007246&beids=9466586&c=WEB&txp=6432434&n=S38A6yFXGzFrhj7&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgYbVyhhW5A4DoTHL2DSLZqHK-ENkU-qTaReSFK1yITHYCIARbbnGmKPZoIDHBZC60GlNSdjT55gI5xdje7dThMrff&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgLv1hctnsdD0vrfUkA5VALLs2AttS3qVbHg9O8mvcB5gCIFGTcn5cLUMY9HhkEfGpRDwyFmLJg9NfLinL-XjqEDkQ
```
These are the separate video and audio for the page and play fine for me in mpv.

If you want a single file with both video and audio you either have to remux the separate streams into a suitable new container (as with yt-dl postprocessing) or pass the equivalent of `-f best` in `ydl.params` (and hope that a combined format is available).

**Comment by grubeli** [comment]
It worked now, it think it was some weird random issue
