### ISSUE TITLE
output template in Windows ...

### ISSUE THREAD

**Issue by Albretch** [ytdl-org/youtube-dl#30015]
## Checklist

- [*] I'm reporting a broken site support issue
- [*] I've verified that I'm running youtube-dl version **2021.06.06**
- [*] I've checked that all provided URLs are alive and playable in a browser
- [*] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [*] I've searched the bugtracker for similar bug reports including closed ones
- [*] I've read bugs section in FAQ

## Verbose log

```
[youtube] zwwi2bcl1Lg: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best

```

## Description

 On windows I am trying to log one liners with the uploader title id and extension. I copy the text from a file and paste it on the command prompt. The same procedure works when I download files, but not when I try to get some metadata.

set IBATCHFL=cashless_society00_yt.txt
set LOGFL=%IBATCHFL%_2021092411234.log
echo %LOGFL%

youtube-dl.exe --simulate --output "%%(uploader)s\%%(title)s_%%(id)s.%%(ext)s" --batch-file %IBATCHFL% >> %LOGFL% 2>&1

**Comment by Albretch** [comment]
On WIndows 10 and I have tried using single quotes as well

**Comment by dirkf** [comment]
In the batch file, `%%(var)s`.

On the command line, just `%(var)s`

https://ss64.com/nt/syntax-percent.html

**Comment by rautamiekka** [comment]
> set IBATCHFL=cashless_society00_yt.txt
> set LOGFL=%IBATCHFL%_2021092411234.log
> echo %LOGFL%
> 
> youtube-dl.exe --simulate --output "%%(uploader)s%%(title)s_%%(id)s.%%(ext)s" --batch-file %IBATCHFL% >> %LOGFL% 2>&1

Remember that Command Prompt is a bigger bitch than Bash when it comes to vars:
1) always double-quote var refs: `"%IBATCHFL%"`.
2) and when assigning a var (Command Prompt doesn't implicitly quote var assignments):
```batch
set "IBATCHFL=cashless_society00_yt.txt"
```
(not `set IBATCHFL="cashless_society00_yt.txt"`)
