### ISSUE TITLE
Every 3 videos causes the 4th video downloaded from a playlist to download at extremely slow speed

### ISSUE THREAD

**Issue by shejan0** [ytdl-org/youtube-dl#30024]
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

```
E:\SleepyNightCore>youtube-dl -v --cookies="youtubecookies.txt" --no-overwrites --ignore-errors -w --yes-playlist "https://www.youtube.com/playlist?list=UU2GBv0o0CbSj68lSbr5EUrQ"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies=youtubecookies.txt', '--no-overwrites', '--ignore-errors', '-w', '--yes-playlist', 'https://www.youtube.com/playlist?list=UU2GBv0o0CbSj68lSbr5EUrQ']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2020-10-28-git-e5be4c5a88-full_build-www.gyan.dev, ffprobe 2020-10-28-git-e5be4c5a88-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube:tab] UU2GBv0o0CbSj68lSbr5EUrQ: Downloading webpage
[download] Downloading playlist: Uploads from Sleepy
[youtube:tab] Downloading page 1
[youtube:tab] playlist Uploads from Sleepy: Downloading 158 videos
[download] Downloading video 1 of 158
[youtube] wD0nDDyxYQ4: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Nightcore - So Good (Lyrics)-wD0nDDyxYQ4.mkv has already been downloaded and merged
[download] Downloading video 2 of 158
.
.
. (A whole bunch of already downloaded and merged warnings for other videos in the playlist)
.
.
[download] Downloading video 47 of 158
[youtube] D2Ekp3m3IQk: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] Best Nightcore Mix 2019 ✪ 1 Hour Special ✪ Ultimate Nightcore Gaming Mix #3-D2Ekp3m3IQk.webm has already been downloaded and merged
[download] Downloading video 48 of 158
[youtube] SaiGvIMGaGc: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] Nightcore - Burning Room (Lyrics)-SaiGvIMGaGc.mp4 has already been downloaded and merged
[download] Downloading video 49 of 158
[youtube] yOnOM56iUH8: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r1---sn-q4fl6nlz.googlevideo.com/videoplayback?expire=1632716590&ei=zvJQYZu0ArSnir4P8_qEoAo&ip=66.69.72.90&id=o-AG7tKL1zwma_rIgp6Xv8NILHHk-7M1LeMuCRtgxlObTa&itag=303&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303&source=youtube&requiressl=yes&mh=Zh&mm=31%2C29&mn=sn-q4fl6nlz%2Csn-q4flrne6&ms=au%2Crdu&mv=m&mvi=1&pl=17&initcwndbps=1818750&vprv=1&mime=video%2Fwebm&ns=IRUq4q7Sjhni_Y21RSO0SUsG&gir=yes&clen=87843326&dur=182.732&lmt=1551896834611746&mt=1632694612&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5431432&n=6fdE9F-C9iNxGg-&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgE1Y7uTAyn4AZvfLgiYk_dsys1lGL7pV9Ai4fv4PXTM8CIQCT_FHs7KtRDUURa3oG6WuOUlnfVR7HmEIr2FD3rm6wvQ%3D%3D&sig=AOq0QJ8wRQIgQRHSHG9phDDahvtyfyqGDtStLcTf1j_M0YDU-qTFgesCIQD0KLVUCN_0J5yYAFt996ntLRF_oCuvhL3LVsWn-OuNyg=='
[download] Resuming download at byte 3532195
[download] Destination: Nightcore - Follow You (Lyrics)-yOnOM56iUH8.f303.webm
[download]   4.6% of 83.77MiB at 82.52KiB/s ETA 16:32
```

This video is downloading at **82.52KiB/s**, estimated to take 16 minutes, where other videos will complete in less than 10 seconds (both video and audio at best available quality). 

YouTube-DL has a very odd issue where after about 3 or 4 videos downloading at full rate in a playlist download, the following video will download at a very slow rate, in orders of 100 times slower. It probably is caused by YouTube's servers receiving GET requests from YouTube-DL on the same IP in quick succession, causing overhead. 

This could be mitigated by having YouTube-DL have waited between download operations, or sending out new GET calls for every single download operation as if it is a new browser connecting every time. There could a be sensing requirement (try again if the download speed is below a certain value) or a command-line argument for if a download is suddenly slower than the previous downloads, attempt to reconnect as a new client. 

While downloading a playlist, the entire playlist there should be no changes in speed due to downloading videos rapidly in order.

**Comment by dirkf** [comment]
Presumably the current version of the YT nonsense as identified in #29326?

**Comment by Bekon241** [comment]
Yes i have same problem :( even if i limit download speed using -r not help i must manualy end download ctrl+C in terminal then again paste playlist link to download and somtime start same slow speed or just fix and speed is normal but only for fiew or just one download then slow again... Meybe will be good add something like this:

**If Speed is lower then 1 MB more then 20s reconnect.**

Thanks cheers from Poland :)

**Comment by Bekon241** [comment]
Hi its me again. I download big playlist and i see somehing.

Example i use for download parametr **youtube-dl --playlist-start 346**
but if my download from 346 end +7 download
like here.
**[download] Downloading video 7 of 39
[youtube] -I1a96IswgE: Downloading webpage
[download] Destination: /root/my-documents/Wideo/soome url.mp4**

Speed is alweys slow 50Kb/s but if i change playlist-start number for higher example +6 **youtube-dl --playlist-start 356 from 346** and start again then YT not block speed for next fiew download.

Yes looks wierd but thats how work now.

**Comment by pbaykalov** [comment]
Actually, I have this issue on any ISP even when I view a single video in MPV. But I never have it when I download one video with command line.
