### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by brugni** [ytdl-org/youtube-dl#30029]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hello guys,
I am not able to download a m3u8 file cause of this error (HTTP Error 403: Forbidden (caused by HTTPError()) . Any suggestions?
Thank you in advance!

**Comment by MuenchenSued** [comment]
You don't expect an answer without any useful information in your question, or? Please read (and check) the checklist and add all requested information, especially the verbose log.

**Comment by brugni** [comment]
Sorry man, my english is not so good.
I used to download normal m3u8 files but since some days i cannot.
The link only works with VLC media player but due to the error i wrote
youtube-dl is not able to do it.
If you can help me i can send you a link to try yourself.


Il giorno mer 29 set 2021 alle ore 03:14 MuenchenSued <
***@***.***> ha scritto:

**Comment by MuenchenSued** [comment]
Without a link and your verbose log (youtube-dl --verbose https://.....m3u8) nobody could help.

**Comment by brugni** [comment]
youtube-dl https://skyfire.vimeocdn.com/1633041688-0x84e8fa0c2b62d408055a1a62beccdd0f9469ae09/589619037/video/2816841829,2816841824,2816841821,2816841560,2816841554/subtitles/13915260-English-eng/master.m3u8
[generic] master: Requesting header
WARNING: Could not send HEAD request to https://skyfire.vimeocdn.com/1633041688-0x84e8fa0c2b62d408055a1a62beccdd0f9469ae09/589619037/video/2816841829,2816841824,2816841821,2816841560,2816841554/subtitles/13915260-English-eng/master.m3u8: HTTP Error 403: Forbidden
[generic] master: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


I always was able to download this kind of link before of 3 days, but now i can't.

**Comment by dirkf** [comment]
These look like temporary links that might be extracted from some page. There may be cookies required or the links may have expired. Where did the links come from?

**Comment by brugni** [comment]
Yes it's a temporary link, it changes every 15 minutes i guess.
I don't understand if required cookies what i have to do eventually ....

**Comment by nicolaasjan** [comment]
>  I don't understand if required cookies what i have to do eventually ....

It's all in the Readme:
[How do I pass cookies to youtube-dl?](https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl)

**Comment by brugni** [comment]
i never understand that. And i am sorry. I try a lot of times, i don't understand how should be the command line :-(

**Comment by dirkf** [comment]
Let's go step by step:
1. install a suitable browser extension to export cookies, if required (it is for FF and Chrome, although an expert user should be able to use the browser's development tools to extract cookies)
2. play the target media in the browser
3. save the cookies to a file using the extension installed in the first step, or a native browser function if available
4. use your yt-dl command with the addition of the `--cookies` option whose value should be the filename from the previous step.

All the background information that you need to achieve this is in the Fine Manual, especially the linked section that you've never understood.

**Comment by brugni** [comment]
Actually I try following those steps, but the result was not good.
But maybe i made some mistakes.
I put the txt file in the same folder where youtube-dl is, and the command
line should be like this?: youtube-dl --cookies/file name of the
cookies.txt "
https://skyfire.vimeocdn.com/1633041688-0x84e8fa0c2b62d408055a1a62beccdd0f9469ae09/589619037/video/2816841829,2816841824,2816841821,2816841560,2816841554/subtitles/13915260-English-eng/master.m3u8
"
Tell me if I am wrong....!

Il giorno ven 1 ott 2021 alle ore 12:35 dirkf ***@***.***> ha
scritto:

**Comment by dirkf** [comment]
If the cookie file is `cookies.txt`:
```
youtube-dl --cookies cookies.txt "https://skyfire.vimeocdn.com/1633041688-0x84e8fa0c2b62d408055a1a62beccdd0f9469ae09/589619037/video/2816841829,2816841824,2816841821,2816841560,2816841554/subtitles/13915260-English-eng/master.m3u8"
```

Put the cookie file in the current working directory from which you're running yt-dl (or use its full path, like `c:\Users\Brugni\cookies.txt`, or `/home/brugni/cookies.txt`). In Windows with `cmd` shell, use the `cd` command to show it, or in a POSIX shell, use `pwd` (and change the "" in the command line to '').

**Comment by brugni** [comment]
[generic] master: Requesting header
WARNING: Could not send HEAD request to https://skyfire.vimeocdn.com/1733242677-0x4c5e0f639bb1aa823a587745abae5aa0d3ff2834/617857814/video/2868449456,2868449455,2868449445,2868448059,2868448052/master.m3u8: HTTP Error 403: Forbidden
[generic] master: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by brugni** [comment]
I can get the file!!!!
Thank you , thank you a lot for your support and help!!!!!!
