### ISSUE TITLE
Unknown MIME type application/mp4 in DASH manifest

### ISSUE THREAD

**Issue by arsbegars** [ytdl-org/youtube-dl#30020]
I think this may just need to be a new site supported, but trying to download a stream with the following results:

youtube-dl https://dash.hoopladigital.com/fri_barnabyandme/Manifest.mpd
[generic] Manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Manifest: Downloading webpage
[generic] Manifest: Extracting information
WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I tried to trouble shoot on my own but couldn't find any solutions.  Thoughts?

**Comment by dirkf** [comment]
`<!--com.castlabs.drmtoday.encrypter dashencrypter 3.0.100-->`

**Comment by FareedAlBandar** [comment]
Hi, I'm facing the same issue, and I have no idea what to do with @dirkf 's comment, any help would be appreciated.
