### ISSUE TITLE
Configuration via config file does not work for Linux Snap installations on Ubuntu 20.04

### ISSUE THREAD

**Issue by BLuedtke** [ytdl-org/youtube-dl#30030]
## Checklist

- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ
- [ ] I'm reporting a broken site support issue

## Verbose log

Log *after* defining a config file with some entries (see below) at `/etc/youtube-dl.conf` and rebooting:
```
youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.6.9 (CPython) - Linux-5.11.0-36-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]
```

## Description

System is Ubuntu 20.04. I have the snap store installed and working (`/snap/bin` is on my path).     
I installed youtube-dl via `snap install youtube-dl` and rebooted (also tried `sudo snap install ...`, same behavior).      
I've created a config file at /etc/youtube-dl.conf and entered a few things:    
```
-x
-o "~/Music/youtubedl/%(title)s.%(ext)s"
--audio-format mp3
--audio-quality 0
--no-mtime
```

However, as the verbose log above shows, the configuration is not being picked up. `[debug] System config: []` should show entries in the `[]` part.     
I tried to place the file with the appropriate name at the user-location too (`~/.config/youtube-dl/config`). Again, no options were picked up. I removed the parantheses around the -o path, and I also tried to specifically set the config-location with the appropriate parameter (`--config-location /etc/youtube-dl.conf`, also tried to enclose the path in parantheses). Still, no configuration options were picked up.

Youtube-dl itself works, I can download videos, but the config is ignored. I rebooted my system, behavior stayed the same. Executing youtube-dl as sudo also does not change the missing config.  When entering the configuration parameters in the command line call directly, they are respected.

I then uninstalled the snap installation and installed it as described in the readme in this git repo. Rebooted, then, without changing anything else, the config options were picked up:
```
youtube-dl -v
[debug] System config: ['-x', '-o', '~/Music/youtubedl/%(title)s.%(ext)s', '--audio-format', 'mp3', '--audio-quality', '0', '--no-mtime']
[debug] User config: ['-x', '-o', '~/Music/youtubedl/%(title)s.%(ext)s', '--audio-format', 'mp3', '--audio-quality', '0', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Linux-5.11.0-36-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]
```

As far as I can see, when installing via snap, the config files are not found, even when `--config-location` is used. Interestingly, different ffmpeg and python versions are detected (user installation vs system installation I guess) by youtube-dl when installed via snap or like the readme specifies. But I don't think that should be an issue.

My suspicion: Either my $PATH and/or snap installation is problematic, or the snap-installed version searches at different locations. However, neither would explain exactly why even --config-location does not work.     
I have not created snap-distributed applications/tools/etc. myself, so I have very little knowledge about where things could go wrong with snap.

**Comment by MuenchenSued** [comment]
Snap applications run in a sandbox and will not have access to all locations. As far as I know, the settings for snap are stored somewhere below ~/snap/appname. I would always use any other method but snap.

**Comment by BLuedtke** [comment]
Thank you for letting me know. As the installation from the readme works, I've stopped using the snap version anyway. However, I did not find any issue entry regarding this (here or elsewhere), so hopefully this issue can be found by other users encountering that problem, convincing them to switch to the normal installation.

Maybe a short warning could be added to the faq/readme, as in, "There are other ways of installing it on Linux, but these may mess with the configuration file location. Please use the instructions above if at all possible."     
Not 100% necessary, but may help some people. Alternatively, this could also be added to the snap package description, as it is managed by someone who is also contributing to youtube-dl anyway, and not some unknown external - I think.

**Comment by dirkf** [comment]
I'm with @MuenchenSued.

However apparently `~/snap` may be where you should look.

[This](https://www.freecodecamp.org/news/managing-ubuntu-snaps/) gives some background.

**Comment by rautamiekka** [comment]
> `~/snap/youtube-dl/current/.config/youtube-dl/`

`mkdir -pv ~/snap/youtube-dl/current/.config/youtube-dl/`
