### ISSUE TITLE
DateAfter and DateBefore flags

### ISSUE THREAD

**Issue by DairyWeb3638077** [ytdl-org/youtube-dl#30036]
So I am trying to use he `--datebefore` and `--dateafter` flags with youtube-dl but I don't know how to set the dates. I have tried setting the dates manually Jan 28, 2013 but it says it wants this format `'%Y%m%d'`, so I did `%13%1%28` and that didn't work and I tried others but didn't work. Please help me fix this so I can get back to work.

**Comment by MuenchenSued** [comment]
%Y is the year with four digits, %m the month with two digits and %d the day with two digits. So today is 20211001 and Jan 28, 2013 is 20130128.

**Comment by kikuyan** [comment]
https://github.com/ytdl-org/youtube-dl#video-selection-1
