### ISSUE TITLE
TF1 / WAT.TV - Erreur dans le delivery

### ISSUE THREAD

**Issue by filoozom** [ytdl-org/youtube-dl#30031]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl "https://www.tf1.fr/tf1/koh-lanta/videos/koh-lanta-la-legende-du-28-septembre-2021-episode-5-62589967.html" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.tf1.fr/tf1/koh-lanta/videos/koh-lanta-la-legende-du-28-septembre-2021-episode-5-62589967.html', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[TF1] koh-lanta-la-legende-du-28-septembre-2021-episode-5-62589967: Downloading JSON metadata
[wat.tv] 13814230: Downloading JSON metadata
ERROR: Erreur dans le delivery
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/wat.py", line 67, in _real_extract
    raise ExtractorError(error_desc, expected=True)
youtube_dl.utils.ExtractorError: Erreur dans le delivery
```

## Description

Worked perfectly last week and suddenly stopped worked. Tried in France as well as outside the country in case it's geoblocked.

The right mpd file is located here: https://das-q1-ssl.tf1.fr/2/USP-0x0/42/30/13814230/ssm/d3be28aaad22966c0a48bc46575d8ab712eda102ef34c74b75e9e388112f3e86.ism/13814230.mpd?e=1632936568&max_bitrate=2700000&st=-Xz3PVjnaty1FBMkt1O-lg, and downloading it with `youtube-dl` works as expected.

**Comment by dirkf** [comment]
It **is** geo-blocked but obviously that's not what you're seeing.
```
ERROR: Ce contenu n'est pas disponible dans votre zone géographique
```

**Comment by Xilokar** [comment]
I had the same issue yesterday, but it is working fine now.

**Comment by filoozom** [comment]
> I had the same issue yesterday, but it is working fine now.

You're right, thank you. Closing.
