### ISSUE TITLE
Use Proxy only for retrieving urls path

### ISSUE THREAD

**Issue by cyberpunkbln** [ytdl-org/youtube-dl#30032]
## Checklist

- [x ] I'm reporting a feature request
- [x ] I've verified that I'm running youtube-dl version **2021.06.06**
- [x ] I've searched the bugtracker for similar feature requests including closed ones

## Description

Hello,
it will be cool, when youtube-dl can only use the proxys for retrieving the url path. An option like this: --proxy-only-urls or so.
This feature will be primarly for youtube.
thx

**Comment by dirkf** [comment]
There is already a `--geo-verification-proxy` option that specifies a proxy to be used by certain extractors for operations that are known to be geo-blocked.

If what you want is always to download the media link directly after running the extraction via the proxy, a way of doing that exists already:

* configure yt-dl to use your proxy with `--proxy ...`;
* use `--external_downloader ...` (say with ffmpeg);
* don't specify a proxy for the external downloader (you may have to unset some environment variable);
* go.

Perhaps we should allow yt-dl to be its own external downloader.

**Comment by cyberpunkbln** [comment]
Hello @dirkf ,

its a very good tip, thx. It's functioned. 

The geo-blocker-proxy is unfotunaly only for retrieve urls when its's geo-blocked-url. I have the problem that the isp-youtube-proxy is very slow, why my isp-youtube-proxy only cache first downloaded videos and i must retry a few time for getting high speed. Thats why is use --proxy when i use mpv<->youtube-dl and the given url has much more speed and mpv don't use a proxy. Here in my country most isp slow down youtube:).

At this moment, when i want to download and not only viewing with mpv, i use your solution.
thx
