### ISSUE TITLE
ERROR: ffprobe/avprobe and ffmpeg/avconv not found. please install one. 

### ISSUE THREAD

**Issue by The-Quaint** [ytdl-org/youtube-dl#30045]
I am using ytdl to download music through my telegram bot. I am always getting: "error: ffprobe/avprobe and ffmpeg/avconv not found. please install one. ". How to fix this error? 
The logs I am getting 👇

2021-10-03 08:21:28.489 | INFO     | apscheduler.executors.base_py3:run_coroutine_job:41 - Job "check_rss (trigger: interval[0:10:00], next run at: 2021-10-03 08:31:28 UTC)" executed successfully
 On my way
2021-10-03 08:27:40.329 | DEBUG    | DaisyX.modules.users:update_user:154 - Users: User 1289524421 updated
2021-10-03 08:27:40.420 | DEBUG    | DaisyX.decorator:new_func:118 - [*] wrapped_1 Time: 0.08999991416931152 sec.
[youtube] fm-nXA-K0Dg: Downloading webpage
[youtube] fm-nXA-K0Dg: Downloading player 9fd4fd09
[youtube] fm-nXA-K0Dg: Downloading thumbnail ...
[youtube] fm-nXA-K0Dg: Writing thumbnail to: Alan Walker, Sabrina Carpenter & Farruko - On My Way (Lyrics)-fm-nXA-K0Dg.webp
[download] Destination: Alan Walker, Sabrina Carpenter & Farruko - On My Way (Lyrics)-fm-nXA-K0Dg.webm

[download]   0.0% of 3.13MiB at 189.06KiB/s ETA 00:17
[download]   0.1% of 3.13MiB at 549.28KiB/s ETA 00:05
[download]   0.2% of 3.13MiB at  1.22MiB/s ETA 00:02
[download]   0.5% of 3.13MiB at  2.55MiB/s ETA 00:01
[download]   1.0% of 3.13MiB at  1.11MiB/s ETA 00:02
[download]   2.0% of 3.13MiB at  1.27MiB/s ETA 00:02
[download]   4.0% of 3.13MiB at  1.74MiB/s ETA 00:01
[download]   8.0% of 3.13MiB at  2.61MiB/s ETA 00:01
[download]  15.9% of 3.13MiB at  4.19MiB/s ETA 00:00
[download]  31.9% of 3.13MiB at  6.97MiB/s ETA 00:00
[download]  63.9% of 3.13MiB at 11.95MiB/s ETA 00:00
[download] 100.0% of 3.13MiB at 17.11MiB/s ETA 00:00
[download] 100% of 3.13MiB in 00:00
ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.
2021-10-03 08:27:44.953 | DEBUG    | DaisyX.modules.users:update_user:154 - Users: User 1289524421 updated
2021-10-03 08:27:44.954 | DEBUG    | DaisyX.modules.filters:check_msg:78 - Running check msg for filters function.
ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.

**Comment by MuenchenSued** [comment]
Just install ffmpeg (https://ffmpeg.org/). ffprobe should be included in this installation.

**Comment by dirkf** [comment]
That is, in the environment where yt-dl is running.

**Comment by mara004** [comment]
youtube-dl relies on ffmpeg for audio post-processing. For windows, there are [setup instructions](https://github.com/ytdl-org/youtube-dl#on-windows-how-should-i-set-up-ffmpeg-and-youtube-dl-where-should-i-put-the-exe-files) in the readme, and on a Debian-based Linux you can do `sudo apt install ffmpeg`.

**Comment by The-Quaint** [comment]
Thanks now it works
