### ISSUE TITLE
Auto-generated subtitles for very long videos are truncated

### ISSUE THREAD

**Issue by synthead** [ytdl-org/youtube-dl#30049]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -v --skip-download --write-auto-sub 'https://www.youtube.com/watch?v=nh-VcsVrvVw&t=1h'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--skip-download', '--write-auto-sub', 'https://www.youtube.com/watch?v=nh-VcsVrvVw&t=1h']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.7 (CPython) - Linux-5.14.7-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] nh-VcsVrvVw: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: The Snow Plow Show Episode 722 - Pound Some Sand-nh-VcsVrvVw.en.vtt
```

## Description

Auto-generated subtitles for very long videos are truncated.  When I run this command...

```shell
youtube-dl --skip-download --write-auto-sub 'https://www.youtube.com/watch?v=nh-VcsVrvVw&t=1h'
```

I get this VTT file (.txt appended so GitHub accepts the file):

[The Snow Plow Show Episode 722 - Pound Some Sand-nh-VcsVrvVw.en.vtt.txt](https://github.com/ytdl-org/youtube-dl/files/7274555/The.Snow.Plow.Show.Episode.722.-.Pound.Some.Sand-nh-VcsVrvVw.en.vtt.txt)

It seems like there should be some sort of pagination in place to acquire the entire subtitle track.  In the example above, it doesn't get past a rounded 0% of the videos progress.

**Comment by kikuyan** [comment]
I've tried VLC and mpv, and the subtitles seem to display fine in both players. Also, the content of the subtitles seems to match the "timedtext" used in browser (format is different, though).
