### ISSUE TITLE
https://dollarvigilante.tv

### ISSUE THREAD

**Issue by Apep-the-snek** [ytdl-org/youtube-dl#30040]
## Checklist

- Tested on version 2021.06.06
- i tested that my URLs work in a Browser, i tested it on Librewolf 92.0.1 (Mozilla Firefox fork), tested URLs include
[https://dollarvigilante.tv/w/akb1bMfpecjHL9GWNbxFbA](https://dollarvigilante.tv/w/akb1bMfpecjHL9GWNbxFbA) and [https://dollarvigilante.tv/w/eSCG4uV2JBo5YW4iF3c6nw](https://dollarvigilante.tv/w/eSCG4uV2JBo5YW4iF3c6nw)
- The site I am requesting is not dedicated to any form of copyright infringement. The example URLs do not violate any copyright, but are within fair use law.
- I searched "is:issue vigilante" in http://yt-dl.org/search-issues the only issue I got is unrelated.

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: [https://dollarvigilante.tv/w/akb1bMfpecjHL9GWNbxFbA](https://dollarvigilante.tv/w/akb1bMfpecjHL9GWNbxFbA)
- Single video: (no shortened URLs that i know of)
- Playlist: (there doesn't exist playlists on this site)

## Description

This is a website based on Peertube dedicated to uncensored truths, ideas and opinions, the channels are selected centrally by the site owner(s), and re generally uploaded elsewhere as well, some videos are uploaded with a higher quality on this site compared to Youtube.com, LBRY (odysee.com) or BitChute.com. However, this is a site where if you do open it within a browser you can download it from there, but so does Odysee.com yet it has youtube-dl support. I particulary want this as a feature due to the fact that I don't like using browsers, when I could just open the links straight from my command line RSS client and open it with mpv or using my youtube-dl download then open with mpv script.

**Comment by dirkf** [comment]
PeerTube is already supported and it should only be necessary to add (eg at l.21) this line
```
                            dollarvigilante\.tv|
```
to the pattern for the list of instances in `youtube_dl/extractor/peertube.py`.

Later, instead of using a list, it would be better to handle PeerTube like Invidious in PR #29942, detecting this element of the `<HEAD>` in the generic extractor:
```
<meta property="og:platform" content="PeerTube">
```
