### ISSUE TITLE
How to suppress "ExtractorError"?

### ISSUE THREAD

**Issue by analyserdmz** [ytdl-org/youtube-dl#30055]
## Checklist

- [ X] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, I am trying to suppress all errors raised by "ExtractorError" and actually print only successfully extracted URLs, but I cannot find any method of suppressing these errors.

I already tried `'quiet': True`, `'ignoreerrors': True` and `'no_warnings': True` with no success.

Thank you.

**Comment by october262** [comment]
try this here - https://stackoverflow.com/questions/64957480/is-there-a-way-to-keep-youtube-dl-from-printing-its-status-to-the-console

**Comment by analyserdmz** [comment]
> try this here - https://stackoverflow.com/questions/64957480/is-there-a-way-to-keep-youtube-dl-from-printing-its-status-to-the-console

I did, actually. I already have the "quite" option in there, but the errors are still visible.

**Comment by analyserdmz** [comment]
> '`quite`' or '`quiet`' ?

Sorry, I meant `'**quiet**': True` but i mistyped it.

**Comment by october262** [comment]
> > '`quite`' or '`quiet`' ?
> 
> Sorry, I meant `'quiet': True` but i mistyped it.

try this one here - https://stackoverflow.com/questions/63025605/how-to-show-only-progress-information-with-youtube-dl

**Comment by analyserdmz** [comment]
> > > '`quite`' or '`quiet`' ?
> > 
> > 
> > Sorry, I meant `'quiet': True` but i mistyped it.
> 
> try this one here - https://stackoverflow.com/questions/63025605/how-to-show-only-progress-information-with-youtube-dl

![image](https://user-images.githubusercontent.com/61113942/136107921-c6c70b0d-7b0e-4de2-85d6-de18ac7e76bb.png)

**Comment by dirkf** [comment]
Two options, neither tested by me:
* sub-class `YoutubeDL` and specialise its `report_error()` method (or perhaps `trouble()`) to discard the error messages;
* more complicated: make a specialised instance of `logging.Logger` that displays the log messages submitted with the `debug()` method but not other messages, and pass it as the value of the `logger` option to the embedded `YoutubeDL`.

Contrary to what the poster here suggested (though it might have been true at the time)
> try this here - https://stackoverflow.com/questions/64957480/is-there-a-way-to-keep-youtube-dl-from-printing-its-status-to-the-console

yt-dl does support logging, as is documented in the definition of the `YoutubeDL` class.
