### ISSUE TITLE
Ytdl isn't working...

### ISSUE THREAD

**Issue by Dare-Devill** [ytdl-org/youtube-dl#30058]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

YouTube Download Error ❌
Error:- ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the verbose flag and include its complete output.
## Description

WRITE DESCRIPTION HERE

**Comment by Dare-Devill** [comment]
Please fix it as soon as possible...🥺

**Comment by Dare-Devill** [comment]
I'm waiting for your reply

**Comment by Happyfeet01** [comment]
What is your command when you to try to download an Video? 

For me it works fine.

**Comment by zackmark29** [comment]
> I'm waiting for your reply

Man do you think they are magician to know what is your problem? 
You should put the verbose logs
