### ISSUE TITLE
 [TVP] Youtube-dl doesn't work with some videos

### ISSUE THREAD

**Issue by mohegan** [ytdl-org/youtube-dl#30060]
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v "https://vod.tvp.pl/video/kolo-fortuny,odc-1091,55830950"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vod.tvp.pl/video/kolo-fortuny,odc-1091,55830950']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.7 (CPython) - Linux-5.13.0-16-generic-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[tvp] 55830950: Downloading webpage
[tvp:embed] 55830950: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r.dcs.redcdn.pl/dash/o2/TVP/embeddrm/out/kolo-fortuny-odc-1091-20211003_f4b3e06e5b07fb052ff8bb8aae5984e0.mp4/Manifest.ism'
[download] Destination: Koło fortuny, odc. 1091-55830950.ism
[download] 100% of 22.34KiB in 00:00
```

## Description

Youtube-dl doesn't work for some videos with tvp.pl.

For example :
- https://vod.tvp.pl/video/kolo-fortuny,odc-1091,55830950 : doesn't work
- https://vod.tvp.pl/video/czar-par,odc-6,44702479 : work

**Comment by mohegan** [comment]
It fails on https://vod.tvp.pl/video/kolo-fortuny,odc-1091,55830950
There isn't an error message but the downloaded file's size is only 22,9 Ko (instead of hundred Mo).

The log with a video wich I can download :
`youtube-dl -v https://vod.tvp.pl/video/czar-par,odc-6,44702479
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vod.tvp.pl/video/czar-par,odc-6,44702479']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.7 (CPython) - Linux-5.13.0-16-generic-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[tvp] 44702479: Downloading webpage
[tvp:embed] 44702479: Downloading webpage
[tvp:embed] 44702479: Downloading ISM manifest
[tvp:embed] 44702479: Downloading f4m manifest
[tvp:embed] 44702479: Downloading m3u8 information
[tvp:embed] 44702479: Checking video URL
[tvp:embed] 44702479: Checking video URL
[tvp:embed] 44702479: Checking video URL
[tvp:embed] 44702479: Checking video URL
[tvp:embed] 44702479: Checking video URL
[tvp:embed] 44702479: Checking video URL
[tvp:embed] 44702479: Checking video URL
[tvp:embed] 44702479: video URL is invalid, skipping: HTTP Error 404: Not Found
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://sdt-thinx10-170.tvp.pl/token/video/vod/44702479/20211006/3119960247/5b202cd0-2f31-442f-9cba-e82586adbfc6/video.ism/Manifest'
[ism] Total fragments: 885
[download] Destination: Czar par, odc. 6-44702479.fmss-4598.ismv
[download]  45.9% of ~1.93GiB at  6.76MiB/s ETA 04:23^C
ERROR: Interrupted by user`

With firefox network inspector :
- https://vod.tvp.pl/video/kolo-fortuny,odc-1091,55830950 : doesn't work
The video links are like : 
https://n-16-7.dcs.redcdn.pl/dash/o2/TVP/embeddrm/out/kolo-fortuny-odc-1091-20211003_f4b3e06e5b07fb052ff8bb8aae5984e0.mp4/Manifest.ism?type=audio&bitrate=128000&id=6
...
https://n-16-7.dcs.redcdn.pl/dash/o2/TVP/embeddrm/out/kolo-fortuny-odc-1091-20211003_f4b3e06e5b07fb052ff8bb8aae5984e0.mp4/Manifest.ism?type=video&bitrate=2800000&id=3&start=161600000


- https://vod.tvp.pl/video/czar-par,odc-6,44702479 : work
The video links contain m3u8 playlist : 
https://sdt-thinx10-170.tvp.pl/token/video/vod/44702479/20211006/3119960247/5cd8a57c-9433-4fbb-815b-0c386f04ce45/video.ism/video.m3u8

And the video link are like : 
https://sdt-thinx10-170.tvp.pl/token/video/vod/44702479/20211006/3119960247/5cd8a57c-9433-4fbb-815b-0c386f04ce45/video.ism/nv-hls-seg-62-f6-v1-a1.ts
https://sdt-thinx10-170.tvp.pl/token/video/vod/44702479/20211006/3119960247/5cd8a57c-9433-4fbb-815b-0c386f04ce45/video.ism/nv-hls-seg-68-f6-v1-a1.ts

**Comment by ivan-kulikov-dev** [comment]
try https://github.com/yt-dlp/yt-dlp, fork of youtube-dl

**Comment by mohegan** [comment]
Same problem with yt-dlp : 

```
/home/jack/Téléchargements/yt-dlp/yt-dlp -v https://vod.tvp.pl/video/kolo-fortuny,odc-1091,55830950
[debug] Command-line config: ['-v', 'https://vod.tvp.pl/video/kolo-fortuny,odc-1091,55830950']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.25 (zip)
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.13.0-16-generic-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite
[debug] Proxy map: {}
[debug] [tvp] Extracting URL: https://vod.tvp.pl/video/kolo-fortuny,odc-1091,55830950
[tvp] 55830950: Downloading webpage
[debug] [tvp:embed] Extracting URL: tvp:55830950
[tvp:embed] 55830950: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 55830950: Downloading 1 format(s): direct
[debug] Invoking downloader on "https://r.dcs.redcdn.pl/dash/o2/TVP/embeddrm/out/kolo-fortuny-odc-1091-20211003_f4b3e06e5b07fb052ff8bb8aae5984e0.mp4/Manifest.ism"
[download] Koło fortuny, odc. 1091 [55830950].ism has already been downloaded
[download] 100% of 22.34KiB
```

**Comment by dirkf** [comment]
Maybe there's a hard geo-block on the failing video, as in the UK it always fails according to the log and diagnosis that I posted. If TVP is protecting the video in that way it might also explain why it's handled differently from the succeeding videos in PL.

What can be seen is that the failing videos are hosted at redcdn.pl rather than tvp.pl. The extractor and the browser agree on the URL
```
https://r.dcs.redcdn.pl/dash/o2/TVP/embeddrm/out/kolo-fortuny-odc-1091-20211003_f4b3e06e5b07fb052ff8bb8aae5984e0.mp4/Manifest.ism
```
but the browser is adding query parameters. The manifest at that URL shows CENC Playready DRM which isn't be supported by yt-dl.

The result of `youtube-dl -F` and `youtube-dl --get-format` for the failing URL would be helpful.

I guess that yt-dl is skipping all the DRM formats and somehow finding a `best` format that isn't actually a video, or not the wanted video (what's actually in the failed 23kB result?).

yt-dlp has a (?) `--include-unplayable-formats` option which doesn't skip DRM formats, allowing it to download a DRM-protected video in case the user can magically make it play.


In your FF Network Inspector log, is there a fetch of something JSON with the video id in the URL, like `https://www.tvp.pl/pub/stat/videofileinfo?video_id=55830950` (will be marked type `JSON` and probably flagged `XHR`)? If so, it would be useful to see the details, such as the request headers and query parameters, and the response.

**Comment by mohegan** [comment]
The option with yt-dlp is --allow-unplayable-formats but same relsult :  
```
/home/jack/Téléchargements/yt-dlp/yt-dlp --allow-unplayable-formats -v https://vod.tvp.pl/video/kolo-fortuny,odc-1091,55830950
[debug] Command-line config: ['--allow-unplayable-formats', '-v', 'https://vod.tvp.pl/video/kolo-fortuny,odc-1091,55830950']
WARNING: You have asked for unplayable formats to be listed/downloaded. This is a developer option intended for debugging. If you experience any issues while using this option, DO NOT open a bug report
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.25 (zip)
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.13.0-16-generic-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite
[debug] Proxy map: {}
[debug] [tvp] Extracting URL: https://vod.tvp.pl/video/kolo-fortuny,odc-1091,55830950
[tvp] 55830950: Downloading webpage
[debug] [tvp:embed] Extracting URL: tvp:55830950
[tvp:embed] 55830950: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 55830950: Downloading 1 format(s): direct
[debug] Invoking downloader on "https://r.dcs.redcdn.pl/dash/o2/TVP/embeddrm/out/kolo-fortuny-odc-1091-20211003_f4b3e06e5b07fb052ff8bb8aae5984e0.mp4/Manifest.ism"
[download] Destination: Koło fortuny, odc. 1091 [55830950].ism
[download] 100% of 22.34KiB in 00:00
```

```
/home/jack/Téléchargements/yt-dlp/yt-dlp --allow-unplayable-formats -F https://vod.tvp.pl/video/kolo-fortuny,odc-1091,55830950
WARNING: You have asked for unplayable formats to be listed/downloaded. This is a developer option intended for debugging. If you experience any issues while using this option, DO NOT open a bug report
[tvp] 55830950: Downloading webpage
[tvp:embed] 55830950: Downloading webpage
[info] Available formats for 55830950:
ID     EXT RESOLUTION | PROTO | VCODEC  ACODEC
------ --- ---------- - ----- - ------- -------
direct ism unknown    | https | unknown unknown
jack@jack-XPS-L322X:~$ 
```

**Comment by dirkf** [comment]
The extractor expects the manifest link to end in `/video.`ext or `/video-`digits`.mp4`, which doesn't match the failing manifest. Unfortunately, changing the extractor (`extractor/tvp.py` ll.152 ff.) to handle this just leads to "No formats found":
```
         formats = []                                                           
         video_url_base = self._search_regex(                                   
-            r'(https?://.+?/video)(?:\.(?:ism|f4m|m3u8)|-\d+\.mp4)',
+            r'(https?://.+?/(video|Manifest))(?:\.(?:ism|f4m|m3u8)|-\d+\.mp4)',
             video_url, 'video base url', default=None)
-        if video_url_base:                                                   
+        if (video_url_base or '').endswith('/Manifest'):
+            formats.extend(self._extract_mpd_formats(               
+                 video_url,                                               
+                 video_id, mpd_id='dash', fatal=False))                        
+        elif video_url_base:                                                   
            # TODO: <Group> found instead of <AdaptationSet> in MPD manifest.  
            # It's not mentioned in MPEG-DASH standard. Figure that out.       
```
This is because the manifest has two `AdaptationSet`s (audio, video) and both have a `<ContentProtection>` element, leading yt-dl to ignore them as DRM formats. If a patch as above was applied together with an `--allow-unplayable-formats` option, yt-dl would list the formats from the manifest (this from some live patching in the debugger):
```
[info] Available formats for 55830950:
format code  extension  resolution note
dash-6       m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-4       mp4        320x180    DASH video  240k , mp4_dash container, avc1.64000c, 25fps, video only
dash-2       mp4        640x360    DASH video  500k , mp4_dash container, avc1.64001e, 25fps, video only
dash-1       mp4        960x540    DASH video  800k , mp4_dash container, avc1.64001f, 25fps, video only
dash-5       mp4        960x540    DASH video 1800k , mp4_dash container, avc1.64001f, 25fps, video only
dash-3       mp4        1280x720   DASH video 2800k , mp4_dash container, avc1.64001f, 25fps, video only (best)
```

**Comment by dirkf** [comment]
On the hand it's satisfying that the expected result occurred. On the other hand it doesn't help with finding a way of pulling a playable video for such pages.

Generally it's unsatisfactory that a video with only DRM formats result in "No formats found" rather than "Only DRM formats found", but the DRM skipping logic is either extractor-specific, or buried inside library routines.

**Comment by 89z** [comment]
Geo block

> For licensing reasons the material is not available in your country
