### ISSUE TITLE
Please answer

### ISSUE THREAD

**Issue by jammam20** [ytdl-org/youtube-dl#30064]
<?php

header('Content-Type: application/json', false);
        $youtubeUrl =  $_GET['url'];
        $content = json_decode(shell_exec("youtube-dl -j $youtubeUrl "), true); 
       
echo json_encode($content, 128|256);
I want make this code echo url from youtube-dl -f bestvideo+bestaudio url
Please answer

**Comment by TheScreechingBagel** [comment]
no

**Comment by rautamiekka** [comment]
Stop opening something like this, you'll get your answers when possible.
