### ISSUE TITLE
ffmpeg console windows briefly appearing

### ISSUE THREAD

**Issue by benshep** [ytdl-org/youtube-dl#30069]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
Not applicable
```

## Description

On Windows. I'm running a [Python script](https://github.com/benshep/scripts/blob/master/get_youtube_playlists.py) from the Task Scheduler, which calls youtube-dl. When it does the post-processing using ffmpeg, I get brief flashes of console windows which steal the focus. This seems to go away if I add the `creationflags = subprocess.CREATE_NO_WINDOW` argument to the `subprocess.Popen` calls of [ffmpeg.py](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/postprocessor/ffmpeg.py) (lines 180 and 230).

**Comment by benshep** [comment]
Oops, sorry - I guess I missed that. Thanks!

**Comment by dirkf** [comment]
Continued in #22627.
