### ISSUE TITLE
Missing Files in a playlist

### ISSUE THREAD

**Issue by luwa1234** [ytdl-org/youtube-dl#30079]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by luwa1234** [comment]
Since several weeks playlist (or CDs) from youtube  leave sometimes some elements undownloaded. Download the missing files with Parameter "start" and "end" works correctley. That happens randomly, so no specifig URL is involved.
Can you help?

**Comment by dirkf** [comment]
Well, yes.

First, read the [issue checklist](#issue-1022002966) and verify all the items that you didn't yet verify: so for instance, when you've identified a failing URL, is the missing item playable in the browser?

If it is then 
>**PASTE VERBOSE LOG HERE**

for the failing case.
