### ISSUE TITLE
YouTubeDl-UPDATE

### ISSUE THREAD

**Issue by ABHINETWORK1** [ytdl-org/youtube-dl#30071]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
youtube_dl.utils.DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by nicolaasjan** [comment]
There is no update after 2021.06.06...
See: https://github.com/ytdl-org/youtube-dl/issues/29965.

You might try the fork [yt-dlp](https://github.com/yt-dlp/yt-dlp) for now.
