### ISSUE TITLE
Specify the directory(s) that youtube-dl search to check if a vid exists

### ISSUE THREAD

**Issue by humanitiesclinic** [ytdl-org/youtube-dl#30083]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

By default,  youtube-dl checks whether a video exists in the current directory first before it downloads it. If it exists, it will skip. Can I specify the directory(s) that youtube-dl search to check if a vid exists?

**Comment by dirkf** [comment]
Isn't the check for a file with the pathname that would be created if the item was downloaded?

The directory where that check is performed obviously depends on the `-o`/`--output` option which determines that pathname (and which by default doesn't include any directory and so references the current directory).

There is also the `--download-archive` option which, if used consistently, will recognise a previously downloaded item by ID regardless of where it was saved.

**Comment by rautamiekka** [comment]
Understandable, even for my Python experience it was a bit hard at 1st.
