### ISSUE TITLE
youtube-dl alternatives

### ISSUE THREAD

**Issue by sebma** [ytdl-org/youtube-dl#30098]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

What are the viable alternatives to `youtube-dl` if `youtube-dl` is dead ?

**Comment by sebma** [comment]
@89z Thanks
I have just renamed this issue hoping this won't be filed as a duplicate.

**Comment by dirkf** [comment]
#30568
