### ISSUE TITLE
YouTube-DL is very slow, of late. How improve the speed?

### ISSUE THREAD

**Issue by RangaSE** [ytdl-org/youtube-dl#30102]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hi, Greetings!
YouTube-DL used to be one of the best internet speed, averaging **190 kbps**, peaking at times ***1.2mbps to 1.4mbps***. Now, it is **35kbps** average and peaking ***83 kbps***. Due to that, I am downloading 3 days per video of 40 minutes of video. Some times, speed drops to single digit. I just want know the Internet Speed can be improved, as I am having, tons of Divine videos, for downloading and watching them repeatedly. ATB!
Keep (s)mailing, RS.

**Comment by VVD** [comment]
> Use a current fork, like yt-dlp.

Same slow speed for both - recent yt-dlp and youtube-dl: some videos ~50KiB/s, some ~80KiB/s.
Before it was ~5-10MiB/s.

**Comment by VVD** [comment]
> > > Use a current fork, like yt-dlp.
> > 
> > 
> > Same slow speed for both - recent yt-dlp and youtube-dl: some videos ~50KiB/s, some ~80KiB/s. Before it was ~5-10MiB/s.
> 
> Make sure you are running the most recent dlp version. If it's still not working, open an issue over there.

```
$ yt-dlp --version
2021.10.10
```

**Comment by VVD** [comment]
As I said before I already tried both - recent yt-dlp and recent youtube-dl with same result - 50-80KiB/s:
> Same slow speed for both - recent yt-dlp and youtube-dl: some videos ~50KiB/s, some ~80KiB/s.

**Comment by hh-lohmann** [comment]
After a week with ~60 KiB and blaming my ISP / my children to steal bandwith, I [dowloaded yt-dlp](https://github.com/yt-dlp/yt-dlp#installation) and had immediately ~ 1.7 MiB. Just to report, not to criticize anyone.

**Comment by digitaltrashlabs** [comment]
Additional/side comment: Seems like my downloads are in Mono not Stereo. Is anyone else seeing this? (Win10)

**Comment by IRus** [comment]
I thought it's python hiccup on mac m1, but yt-dlp works much better, downloading 20 MiB from youtube

**Comment by gtwy** [comment]
Switching from youtube-dl to yt-dlp fixed my issues as well. I could not download anything on Youtube faster than 60KB/sec prior to this.

youtube-dl is up-to-date (2021.06.06)
yt-dlp is up to date (2021.11.10.1)

**Comment by dirkf** [comment]
yt-dlp works fine if it's compatible in your environment.

Otherwise, for the moment, see the patch in PR #30184 and the discussion in the main issue #29326 (which is where you should have been posting) if you need help applying it.

**Comment by velespr0** [comment]
Any updates about current speed? 
It is no more than 80KiB/s

**Comment by dirkf** [comment]
Read and action the [previous comment](https://github.com/ytdl-org/youtube-dl/issues/30102#issuecomment-966584826).

**Comment by GrantBirki** [comment]
I have a project that I just swapped from `youtube-dl` to `yt-dlp` to test performance and I am really impressed. `yt-dlp` was nearly 3x times faster and hits fewer timeouts. Great suggestion! 🎉

**Comment by tesar-tech** [comment]
Yes, yt-dlp works. And it has colorful status too: 
<img width="396" alt="image" src="https://user-images.githubusercontent.com/33880579/144385430-5e025cf0-51d1-4519-8200-dac70f1cb8b8.png">

**Comment by oshanz** [comment]
`youtube-dl` 66.05KiB/s
`yt-dlp` 10.49MiB/s

**Comment by dirkf** [comment]
Have you read and actioned the [previous comment](https://github.com/ytdl-org/youtube-dl/issues/30102#issuecomment-966584826)? If not, you could consider reading through the issue and the linked material and then deleting your pointless comment, which is in a duplicate issue anyway.

If your yt-dl is patched as above, please provide a verbose log to show how the unthrottling patch is failing.

**Comment by aaronk1** [comment]
+1 
yt-dlp works fine

**Comment by 89z** [comment]
I would avoid any suggestion of PR such as this one: https://github.com/ytdl-org/youtube-dl/issues/30102#issuecomment-966584826

As this person is a known copyright violator: https://github.com/ytdl-org/youtube-dl/pull/30184#issuecomment-958689745

**Comment by dirkf** [comment]
Instead of [libel](https://www.collinsdictionary.com/dictionary/english/libel), why not read https://github.com/ytdl-org/youtube-dl/pull/30184#issuecomment-959870082?

**Comment by 89z** [comment]
Instead of linking to your own comment, maybe you can link to where the original author granted you permission to relicense your derived work?

**Comment by hasecilu** [comment]
Just for if it is any doubt, at least for me, `yt-dlp` downloaded a `177.68MiB` video in just 31 seconds meanwhile `youtube-dl` already have in 20 minutes 37 seconds just downloaded 35.7% of the same `177.68MiB` video at `73.35KiB/s`.

**Comment by dirkf** [comment]
The current release still needs patching against YT throttling. With luck, there will be a new release to fix this properly soon.

**Comment by PrivateGER** [comment]
> The current release still needs patching against YT throttling. With luck, there will be a new release to fix this properly soon.

There are zero active contributors in this project left. I wouldn't hold by breath.

**Comment by 89z** [comment]
> There are zero active contributors in this project left. I wouldn't hold my breath.

I have to agree with this. I contacted Remita, but they didnt respond. I also contacted Ricardo, who said:

> I know the current status of the project is fragile due to the main maintainer having resigned and the other remaining one not active currently, so I'm trying to reach out to some people to see what can be done.

**Comment by ajlewis2** [comment]
Yes!! Huge improvement for me on Mint 20.3 with yt-dlp which was in the repository. Thanks!!

**Comment by sseodate** [comment]
to me. yt-dlp still have the same speed as youtube-dl , only at 80kbps :(

**Comment by dirkf** [comment]
How are your other downloads? If they go faster, consider raising an issue at yt-dlp.

Any of these three
* recent yt-dlp release,
* yt-dl 2021.06.01 or 2021.12.17 patched with the replacement version of `extractor/youtube.py`,
* yt-dl 2021.06.01 or 2021.12.17 patched with PR #30184,

will not be throttled.

**Comment by cantalupo555** [comment]
> `youtube-dl` 66.05KiB/s `yt-dlp` 10.49MiB/s

Here
`youtube-dl` 66.05KiB/s
`yt-dlp` 10MiB/s - 30MiB/s

**Comment by computerguy26** [comment]
Looks like 'youtube-dl' could be having a format issue. 'yt-dlp' outputs in '.webm' format by default. 'youtube-dl' outputs in '.mp4' by default. When: 
`youtube-dl -f .webm url`

returns: `ERROR: unable to download video data: HTTP Error 403: Forbidden`

Maybe theres a way to delete error code and download as .webm.

**Comment by Muhammad-Ahmad-Jutt** [comment]
yt-dlp works excellent

**Comment by dirkf** [comment]
>Maybe theres a way to delete error code and download as .webm.
`-f '[ext=webm]'`

**Comment by williamokano** [comment]
Amazing tip regarding `yt-dlp`. Was downloading at ~80kb/s with `youtube-dl` and I'm download at full speed with `yt-dlp`, which is around 50mb/s. Yes, first one kilobytes per second, other one, megabytes per second.
