### ISSUE TITLE
Slow speed download /maby is a youtube restriction due the fact they bann all the videos regards youtube-dl ?

### ISSUE THREAD

**Issue by AurelFR** [ytdl-org/youtube-dl#30119]
i just test the youtube-dl on Mx linux /66kb/sec 
the same on windows 10 pro /70kb /sec

So i just install on win 10 Replay Media  Catcher 7 -speed on the same videofile 11Mb/sec

**Comment by PikuZheng** [comment]
same problem here, since about end of September...

**Comment by xiaose** [comment]
If I use youtube-dl for downloading it is slow. And looks like it begins in last 1-2 month. Speed is very different if I download through youtube-dl or using direct URL. Difference in more than 5 times.

So, if I do this:
```
PS ...\Desktop> youtube-dl.exe -g -f 22 ryAIbTLTidw
```
I will get direct URL like this:
```
https://r9---sn-quxapm-3c2e.googlevideo.com/videoplayback...
```
than just open it in browser, for example in Chrome, where video starts playing. After that, in an options I choose "download" and video downloads in 30-35 sec.

But if I gonna do this (normal, default way):
```
PS ...\Desktop> Measure-Command { youtube-dl.exe -v -f 22 ryAIbTLTidw }
...
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
...
TotalMinutes : 6.29760365666667
```

As you can see, it downloads more than 9 (nine) times slower in this case, and at least 5 times slower in another cases.

BTW, if I do smth. like this:
```
PS ...\Desktop> youtube-dl.exe https://r9---sn-quxapm-3c2e.googlevideo.com/videoplayback...
```
it also takes huge amount of time. Never so quick as if open in browser and 'download' from there.

PS. I tried to use wget to download, but it generally gives me this:
```
.\wget.exe -O res.mp4 'https://r9---sn-quxapm-3c2e.googlevideo.com/videoplayback...
--2021-10-18 20:27:04--  https://r9---sn-quxapm-3c2e.googlevideo.com/videoplayback...
Resolving r9---sn-quxapm-3c2e.googlevideo.com (r9---sn-quxapm-3c2e.googlevideo.com)... 185.192.249.22
Connecting to r9---sn-quxapm-3c2e.googlevideo.com (r9---sn-quxapm-3c2e.googlevideo.com)|185.192.249.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27666760 (26M) [video/mp4]
Saving to: 'res.mp4'

res.mp4    100%[==================================>]  26.38M 74.3KB/s in 6m 14s

2021-10-18 20:33:18 (72.3 KB/s) - 'res.mp4' saved [27666760/27666760]
```

**Comment by TrevCan** [comment]
Downloads for youtube also have slowed down drastically for me. Before, I had about 10 MB/s and now I get a speed cap of around 80-100 KB/s ! [`yt-dlp`, "*A youtube-dl fork with additional features and fixes*"](https://github.com/yt-dlp/yt-dlp) **definitely fixes** the issue for me (Before, I used to just restart the download but now the speed cap is always there!).
[source](https://github.com/LukeSmithxyz/voidrice/issues/1018)

**Comment by PikuZheng** [comment]
> Does this application with the most bugs work for anyone?
> 
> ```
> ducho@DSs-MacBook-Pro Downloads % youtube-dl https://youtu.be/TVEpF1ekuyg               
> [youtube] TVEpF1ekuyg: Downloading webpage
> [youtube] TVEpF1ekuyg: Downloading video info webpage
> WARNING: unable to download video info webpage: HTTP Error 410: Gone
> WARNING: unable to download video info webpage: HTTP Error 410: Gone
> WARNING: unable to download video info webpage: HTTP Error 410: Gone
> WARNING: unable to download video info webpage: HTTP Error 410: Gone
> ERROR: TVEpF1ekuyg: YouTube said: Unable to extract video data
> ```

nope.
It looks like this video is prohibited in your area
