### ISSUE TITLE
Is it available to get the channel url by search words?

### ISSUE THREAD

**Issue by jcn199729** [ytdl-org/youtube-dl#30138]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

For example, the channel I am looking for is: https://www.youtube.com/channel/UC9zY_E8mcAo_Oq772LEZq8Q
The search I used is: the first take
The url of channel does not contain the search word, is there any features I can use in youtube-dl to get it?

**Comment by dirkf** [comment]
Try with the current master and reopen if it's not solved, with verbose log.
