### ISSUE TITLE
RTVE not supported

### ISSUE THREAD

**Issue by nggfng** [ytdl-org/youtube-dl#30148]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

C:\ffmpeg-2020-09-24-git-14d6838638-full_build\bin>youtube-dl --verbose https://
www.rtve.es/alacarta/videos/la-caza/caza-monteperdido-capitulo-1-deshielo/509225
9/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.rtve.es/alacarta/videos/la
-caza/caza-monteperdido-capitulo-1-deshielo/5092259/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 2020-09-24-git-14d6838638-full_build-www.gyan.dev,
ffprobe 2020-09-24-git-14d6838638-full_build-www.gyan.dev
[debug] Proxy map: {}
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] 5092259: Downloading JSON metadata
[rtve.es:alacarta] 5092259: Downloading url information
ERROR: Unable to download webpage: HTTP Error 402: Payment Required (caused by H
TTPError()); please report this issue on https://yt-dl.org/bug . Make sure you a
re using the latest version; type  youtube-dl -U  to update. Be sure to call you
tube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl
31\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl
31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

```

## Description

The video's URL is https://www.rtve.es/play/videos/la-caza/caza-monteperdido-capitulo-1-deshielo/5092259/
I change play for alacarta as suggested in another issue, but now I get the Payment Required error. Can it be solved?
Thank you

**Comment by kikuyan** [comment]
Works with your url.
```
$ youtube-dl --ignore-config https://www.rtve.es/alacarta/videos/la-caza/caza-monteperdido-capitulo-1-deshielo/5092259/ 
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] 5092259: Downloading JSON metadata
[rtve.es:alacarta] 5092259: Downloading url information
[rtve.es:alacarta] 5092259: Downloading m3u8 information
[rtve.es:alacarta] 5092259: Downloading MPD manifest
[rtve.es:alacarta] 5092259: Downloading m3u8 information
[rtve.es:alacarta] 5092259: Downloading MPD manifest
[rtve.es:alacarta] 5092259: Downloading m3u8 information
[rtve.es:alacarta] 5092259: Downloading MPD manifest
[dashsegments] Total fragments: 891
[download] Destination: La caza. Monteperdido - Capítulo 1 - El deshielo-5092259.fdash-video=802000.mp4
[download]   0.2% of ~156.14MiB at  2.45MiB/s ETA 07:34^C
ERROR: Interrupted by user
```

**Comment by nggfng** [comment]
Thanks for your response, but unfortunately it doesn't work here:

C:\ffmpeg-2020-09-24-git-14d6838638-full_build\bin>youtube-dl --ignore-config ht
tps://www.rtve.es/alacarta/videos/la-caza/caza-monteperdido-capitulo-1-deshielo/
5092259/
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] 5092259: Downloading JSON metadata
[rtve.es:alacarta] 5092259: Downloading url information
ERROR: Unable to download webpage: HTTP Error 402: Payment Required (caused by H
TTPError()); please report this issue on https://yt-dl.org/bug . Make sure you a
re using the latest version; type  youtube-dl -U  to update. Be sure to call you
tube-dl with the --verbose flag and include its complete output.

**Comment by kikuyan** [comment]
I reproduced through Mexico vpn. Adding `--geo-bypass-country es` to it didn't resolve the situation completely.

It seems that you need to use a vpn or proxy that goes through a different area from yours. Spanish one should go well.

**Comment by alexanderadam** [comment]
Apart from the `play` vs `alacarta` issue, it's also not possible to fetch/embed the subtitles.
Is this related or should I create a new issue for this?

**Comment by dirkf** [comment]
@alexanderadam: yes.
