### ISSUE TITLE
[udemy] can't download: course: ERROR: Unable to download webpage: HTTP Error 403

### ISSUE THREAD

**Issue by TahaMaher106** [ytdl-org/youtube-dl#30141]
[udemy:course] course: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by kikuyan** [comment]
> Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Do not ignore.

**Comment by TahaMaher106** [comment]
i sure
