### ISSUE TITLE
ERROR: No video formats found;

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#30157]
## Checklist

- [x] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by Zinbo20** [comment]
Yes, I checked the instructions above. The error occurs when I get multiple URLs at the same time in this case I'm taking it from a playlist.
