### ISSUE TITLE
Please implement ytdl for https://www.brighteon.com

### ISSUE THREAD

**Issue by astrometrics** [ytdl-org/youtube-dl#30168]
Has many interesting videos, I'd like to ask you guys to implement download videos (the list in the page, just like youtube videos tab). Thanks for ytdl.

**Comment by astrometrics** [comment]
Hi... @dirkf 

" -o - option and redirect to NUL or /dev/null as appropriate" by that you mean send the content to /dev/null?
"To find playlists and then ignore them"  
I just can't make any positive sense of this 2 phrases... care to explain?

regards

**Comment by dirkf** [comment]
You need to consider the nature of the typical site content to understand why I suggested ignoring, discarding or deleting it.

**Comment by flashdagger** [comment]
Yeah. Worse than porn: https://pypi.org/project/ytdlp-brighteon/

**Comment by astrometrics** [comment]
so youtube-dl is a left leaning team/platform that will only support porn? Be trully democratic please. thanks

**Comment by flashdagger** [comment]
This is getting off-topic, but nevertheless. I don't think the team is biased. 
youtube-dl implements extractors for all kinds off sites. I just pointed out a solution to your request.

**Comment by dirkf** [comment]
Some devs don't work on extractors for NSFW sites. Some may not work on extractors for nonsense propaganda sites. Speaking as the author of the PR for the extractor for GBNews, a site not often considered pinko, I think explaining how someone who cared could extract brighteon playlists is about my limit, but @flashdagger has saved that person the trouble.

The yt-dlp extractor would be a simple back-port if the yt-dlp `traverse_obj()` utility function could be provided.

**Comment by astrometrics** [comment]
Hi, yes @flashdagger I understood your msg when you wrote it, thanks for the infos, already pip3ed.

@dirkf you shouldn't as a dev pass judgement on a content (as long as it is legal), what you call a disinfo or propaganda website may actually have bona fide scientists telling what they actually found... despite of what Orwell's MiniTruth agent central thinks. Also don't play games with pretentious pseudo cryptic messages, time is precious.

If you mean Brighteon is NSFW, I would have to disagree. Free speech shoundn't be considered dangerous.

Anyway I want to thank the team again for youtube-dl, as a project and as an idea.

**Comment by rautamiekka** [comment]
a dev pass judgement on a content (as long as it is legal), what you call a disinfo or propaganda website may actually have bona fide scientists telling what they actually found... despite of what Orwell's MiniTruth agent central thinks. Also don't play games with pretentious pseudo cryptic messages, time is precious.

Besides, if you're making a general vid/audio downloader, what the User uses the downloaded content for ain't the dev's business. As long as it exists and is legal, it doesn't matter.
