### ISSUE TITLE
unable to download from Youtube

### ISSUE THREAD

**Issue by hcary** [ytdl-org/youtube-dl#30167]
youtube-dl  'https://www.youtube.com/watch\?v\=FeLO8yVrVx4' 
[generic] watch\?v\=FeLO8yVrVx4: Requesting header
WARNING: Could not send HEAD request to https://www.youtube.com/watch\?v\=FeLO8yVrVx4: HTTP Error 404: Not Found
[generic] watch\?v\=FeLO8yVrVx4: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by rmstock2** [comment]
Here's my errors with youtube-dl on youtube.  Maybe consider a name change just like facebook :

ubuntu@ubuntu:~$ youtube-dl -v -f 22 https://www.youtube.com/watch?v=ZR3X40kOPk8  
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'22', u'https://www.youtube.com/watch?v=ZR3X40kOPk8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-42-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] ZR3X40kOPk8: Downloading webpage
[debug] Invoking downloader on u'https://r2---sn-mn4vg5aa-5hn6.googlevideo.com/videoplayback?expire=1635553748&ei=dD18YZqiApHN1gK5mqiYBw&ip=2001%3A981%3A6c7d%3A1%3Aca0a%3Aa9ff%3Afe65%3A5159&id=o-AGUUwagrAReLMFtuE8HBY3s4k9f8WeDrGhP5Kxj__li3&itag=22&source=youtube&requiressl=yes&mh=fh&mm=31%2C29&mn=sn-mn4vg5aa-5hn6%2Csn-5hnekn7s&ms=au%2Crdu&mv=m&mvi=2&pl=36&initcwndbps=1521250&vprv=1&mime=video%2Fmp4&ns=CeXYlF330h_VmgqCCbEsLBwG&cnr=14&ratebypass=yes&dur=1105.734&lmt=1635493539033647&mt=1635531900&fvip=5&fexp=24001373%2C24007246&c=WEB&txp=5432432&n=BUtQEcmc1Wc8cuIE&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOPkuDQd73iWPGrwL7grIQO8-hoWKlHdknk6pQXHUPtvAiEA760U3wxpzQDUgDa7cBosSHPJ4v18TzYQFa-Tp5i61IM%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOlng-XZFXzMUqm3-_rxXNKED9nkvZioiaMBo_oz7_p5AiEAt6o-2JBtGIzpq8Mejo5LFMP0cBNmjpS2-1JHVABTRW0%3D'
[download] Destination: Mount 1 Report Premier Entertainment Reset news 10_28_21-ZR3X40kOPk8.mp4
[download]   1.0% of 55.04MiB at 73.77KiB/s ETA 12:36[download] Got server HTTP error: Downloaded 550148 bytes, expected 57715383 bytes. Retrying (attempt 1 of 10)...


ERROR: Did not get any data blocks
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 352, in real_download
    return download()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 330, in download
    retry(err)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 233, in retry
    raise RetryDownload(e)
RetryDownload

ubuntu@ubuntu:~$

**Comment by dirkf** [comment]
Confirmed with format 22 and 18. However the default format selection (prefers separate video and audio works. As long as you have _ffmpeg_ installed, `-f 136+140` should work instead of `-f 22` (for the moment, at the throttled rate).

**Comment by jmf1988** [comment]
The video now says "This video has been removed for violating YouTube's Community Guidelines" so maybe was that.
