### ISSUE TITLE
How can I get the thumbnail of a video?

### ISSUE THREAD

**Issue by 3022249729** [ytdl-org/youtube-dl#30179]
I extracted the youtube video and made it`thumbnail = meta.get('thumbnails')[0]['url']` , but its only a frame in the video, not the actual thumbnail

**Comment by dirkf** [comment]
Or, not the thumbnail that you wanted.

Maybe other thumbnails are in the `thumbnails` list, or in `meta['thumbnail']`? No other images are being extracted.

For further analysis, you'd need to post the details.
