### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by OrionRandD** [ytdl-org/youtube-dl#30176]
Seems not to be working any more after YouTube was discontinued :(
At least in my emacs.
The bellow setup used to work.
But, Emacs complains now.

(add-to-list 'load-path "~/.emacs.d/local-repo/youtube-d#
 (require 'youtube-dl)

**Comment by kikuyan** [comment]
Wrong place to ask, I guess.
There are other 8 pages in this repository containing the word [emacs](https://github.com/ytdl-org/youtube-dl/search?q=emacs&type=issues) but none of them relates to how users use youtube-dl on emacs.

**Comment by OrionRandD** [comment]
> Wrong place to ask, I guess. There are other 8 pages in this repository containing the word [emacs](https://github.com/ytdl-org/youtube-dl/search?q=emacs&type=issues) but none of them relates to how users use youtube-dl on emacs.

Ok. Sorry

**Comment by kikuyan** [comment]
Please close this.
