### ISSUE TITLE
Super slow downloads & other problems

### ISSUE THREAD

**Issue by TENTHARSOS** [ytdl-org/youtube-dl#30173]
## Checklist

- [ x] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
C:\Users\MR\Downloads\youtube dl 2>youtube-dl --update
ERROR: can't find the current version. Please try again later.

C:\Users\MR\Downloads\youtube dl 2>youtube-dl --verbose --update
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--update']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Proxy map: {}
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1287, in connect
  File "C:\Python\Python34\lib\ssl.py", line 362, in wrap_socket
  File "C:\Python\Python34\lib\ssl.py", line 580, in __init__
  File "C:\Python\Python34\lib\ssl.py", line 807, in do_handshake
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\update.py", line 46, in update_self
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\utils.py", line 2737, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

ERROR: can't find the current version. Please try again later.

C:\Users\MR\Downloads\youtube dl 2>

## Description

WRITE DESCRIPTION HERE

I can not update and i have other problems as well but can't even see if updating might fix them.

**Comment by 89z** [comment]
This issue has been posted many times. Please do not post duplicate issues.

**Comment by uunnxx** [comment]
I've the same issue, and I'd checked all closed 'slow download' issues

**Comment by a2468834** [comment]
Personally, I use the following two ways to mitigate the situation (have still not found the solution)
(1) [Manually] observe the speed and re-download when needed, [Auto] run the python script to detect the speed and re-download.
(2) Use the flag `--http-chunk-size 10M` (see [here](https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-864218464)), the size would vary and could combine with python script to randomly choose a number from 1M to 10M.

**Comment by ImOsaym** [comment]
> Personally, I use the following two ways to mitigate the situation (have still not found the solution)
> (1) [Manually] observe the speed and re-download when needed, [Auto] run the python script to detect the speed and re-download.
> (2) Use the flag `--http-chunk-size 10M` (see [here](https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-864218464)), the size would vary and could combine with python script to randomly choose a number from 1M to 10M.

doesn't work

**Comment by pcoopergit** [comment]
> Personally, I use the following two ways to mitigate the situation (have still not found the solution) (1) [Manually] observe the speed and re-download when needed, [Auto] run the python script to detect the speed and re-download. (2) Use the flag `--http-chunk-size 10M` (see [here](https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-864218464)), the size would vary and could combine with python script to randomly choose a number from 1M to 10M.

Sir. Many people who open issues here are not terminal  friendly & tech savvy as you. If there's a way to fix this, devs could already done it. If not, why don't they just update the documentation manual & put a note that the download speeds are currently slow, & wait for the fixes ?

**Comment by dirkf** [comment]
>put a note that the download speeds are currently slow, & wait for the fixes ?

That much should be clear from the original issue that OP @TENTHARSOS should have found by searching open issues about Youtube.

However OP and possibly @uunnxx have the additional problem that the built-in update function isn't working. The relevant URLs are all working but it's possible that a certificate issue is blocking the connection.

Not that it would fix the main problem in the issue title, but the latest version can be obtained at http://ytdl-org.github.io/youtube- dl/download.html (OP should use the link 'Windows exe'). OP should try that and report back whether it works.

**Comment by tooncitydl** [comment]
youtube-dl is abandoned. Use yt-dlp instead: https://github.com/yt-dlp/yt-dlp

**Comment by uunnxx** [comment]
@TENTHARSOS look at this one:
This [yt-dlp](https://github.com/yt-dlp/yt-dlp) fork works just fine.


![focused_window_2021-10-31_09-20-21_900x450](https://user-images.githubusercontent.com/6236057/139570801-98cf4950-630d-4701-8bbf-50cf2fef080b.png)

**Comment by Det87** [comment]
Is youtube-dl dead now? The fork's where it's at now?

**Comment by uunnxx** [comment]
> Is youtube-dl dead now? The fork's where it's at?

Of course, not dead. You can 'for now' just replace it with [yt-dlp](https://github.com/yt-dlp/yt-dlp) fork.

As says fork's about page:
> A youtube-dl fork with additional features and fixes
> The main focus of this project is adding new features and patches while also keeping up to date with the original project.

**Comment by Det87** [comment]
> Of course, not dead. You can 'for now' just replace it with [yt-dlp](https://github.com/yt-dlp/yt-dlp) fork.

How long's for now gonna be, if last commit was 4 months ago?

**Comment by yonderbread** [comment]
Try combining `aria2` with youtube-dl:
```bash
alias ytdl-fast="youtube-dl -f best --external-downloader aria2c --external-downloader-args \"-j 16 -s 16 -x 16 -k 1M\" $1"
```

**Comment by noahbroyles** [comment]
You can try my [hella fast version](https://github.com/noahbroyles/fast-youtube-dl)

All credit to @dirkf for his PR which I implemented. I have no problems with licensing.
