### ISSUE TITLE
[YouTube] Video is not possible to download [Only 360p & 720p Available]

### ISSUE THREAD

**Issue by pootz10** [ytdl-org/youtube-dl#30178]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm very experienced user with youtube-dl all links I download used to work just fine, except today with the link below.
[https://youtu.be/-iZio70bd-M](https://youtu.be/-iZio70bd-M)
I've tried to download it (any quality format fails), check available formats 
It ends up telling HTTP 404 error

I require confirmation,
is it a youtube-dl bug or youtube side problem?

Thanks in advance.

**Comment by dirkf** [comment]
Try playing it in the browser (fails for me, media URL gets 404 in Developer Tools).

Apparently combined formats are giving 404 (eg, #30167). This video has no separate video and audio formats, only 18 and 22.

No-one seems to have reported this issue for yt-dlp yet: maybe the throttling fix also by-passes this. It would be interesting if the video played in the Android app but not in a PC browser.

**Comment by pootz10** [comment]
dirkf, thank you for your reply.
I've tried in the browser sometimes, the video is running fine.
I've tried jdownloader and 3 youtube download sites, none was capable to download it.

**Comment by dirkf** [comment]
Is it really playing in FF now? If so, are you logged in to a G account?

You should be able to use the Network tab of the [Developer Tools](https://developer.mozilla.org/en-US/docs/Tools) to see the media URL that is being used, and the request header that was used to fetch it, in case some special header was required.

**Comment by pootz10** [comment]
Strangely the video is not running now, at the moment I created the topic it was,
I remember watching it part of it on the browser. (Yes I was logged in)
All the preview frames on the timing bar are visible and I achieved the download of the video subtitle.

Well, I'm going to try it later, thanks for the tip.

Yesterday I downloaded all english subtitles of the entire playlist (this video too), but when I downloaded all the videos only this one failed, then I released the formats missing.

**Comment by 89z** [comment]
If you look at the comments on the video, at least 10 people cant view it either. So I dont think its anything specific to YouTube-DL.

**Comment by pukkandan** [comment]
Defenitely not a youtube-dl issue. The video isnt available in any client
```
➤ yt-dlp --extractor-args youtube:player-client=all -vF --no-sim -f all --check-formats -- -iZio70bd-M
[debug] Command-line config: ['--extractor-args', 'youtube:player-client=all', '-vF', '--no-sim', '-f', 'all', '--check-formats', '--', '-iZio70bd-M']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.10.22 (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 0930b11fd
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-103892-g71f2a9a2e5-20210927, ffprobe N-103892-g71f2a9a2e5-20210927, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: -iZio70bd-M
[youtube] -iZio70bd-M: Downloading webpage
[youtube] -iZio70bd-M: Downloading android player API JSON
[youtube] -iZio70bd-M: Downloading android agegate player API JSON
[youtube] -iZio70bd-M: Downloading android embedded player API JSON
[youtube] -iZio70bd-M: Downloading android music player API JSON
[youtube] -iZio70bd-M: Downloading android creator player API JSON
[youtube] -iZio70bd-M: Downloading web agegate player API JSON
[youtube] -iZio70bd-M: Downloading web_embedded config
[youtube] -iZio70bd-M: Downloading player 9216d1f7
[youtube] -iZio70bd-M: Downloading web embedded player API JSON
[youtube] -iZio70bd-M: Downloading web_music config
[youtube] -iZio70bd-M: Downloading web music player API JSON
[youtube] -iZio70bd-M: Downloading web creator player API JSON
[youtube] -iZio70bd-M: Downloading ios player API JSON
[youtube] -iZio70bd-M: Downloading ios agegate player API JSON
[youtube] -iZio70bd-M: Downloading ios embedded player API JSON
[youtube] -iZio70bd-M: Downloading ios music player API JSON
[youtube] -iZio70bd-M: Downloading ios creator player API JSON
[youtube] -iZio70bd-M: Downloading mweb player API JSON
[youtube] -iZio70bd-M: Downloading mweb agegate player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[info] Available formats for -iZio70bd-M:
ID EXT RESOLUTION │ PROTO │ VCODEC      ACODEC    MORE INFO
────────────────────────────────────────────────────────────
17 3gp 256x144    │ https │ mp4v.20.3   mp4a.40.2 144p
18 mp4 640x360    │ https │ avc1.42001E mp4a.40.2 360p
22 mp4 1280x720   │ https │ avc1.64001F mp4a.40.2 720p
[info] Testing format 17
[info] Unable to download format 17. Skipping...
[info] Testing format 18
[info] Unable to download format 18. Skipping...
[info] Testing format 22
[info] Unable to download format 22. Skipping...
ERROR: [youtube] -iZio70bd-M: Requested format is not available
```

**Comment by dirkf** [comment]
Even the 144p format that yt-dl disdains is offline!

> [edited] I've check out the newest comments on the video and people from 9 hours ago couldn't play it, but 3 days ago could. What a unusual issue.

That's the same timescale as issue #30167.

Given that YT's own players are affected, apparently someone at YT has [done a Facebook](https://engineering.fb.com/2021/10/04/networking-traffic/outage/), rather than combined formats being withdrawn because they were too useful.

**Comment by pootz10** [comment]
Thank you guys.
