### ISSUE TITLE
TikTok - Possible to download artist's entire video gallery??

### ISSUE THREAD

**Issue by earthyrock** [ytdl-org/youtube-dl#30174]
- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

***TIKTOK***

I know the below is *busted*, but here goes (embarrassed),... using the most recent Youtube-DL, goal is to download an entire TikTok artist's gallery of videos.

My .bat file
`"C:\Program Files (x86)\youtube-dl\youtube-dl.exe" --config-location "C:\Program Files (x86)\youtube-dl\youtube-dl.conf" https://www.tiktok.com/@aymieandgracie?lang=en`

My .conf file

`--ffmpeg-location "C:\Program Files\ffmpeg\bin\ffmpeg.exe"
--audio-format "mp3"
--format 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4'
--output "X:\10Video\Podcasts\tmp (In)\12Downloadz\%(uploader)s\%(title)s%(view_count)s.%(ext)s"`

How can the .bat file be changed to allow download of the entire gallery?

Thanks in advance.

**Comment by u-spec-png** [comment]
[Yt-dlp](https://github.com/yt-dlp/yt-dlp) has already implemented that feature.

**Comment by earthyrock** [comment]
Just learned about that branch 2 days ago. Will check it out. Thanks! ; )
