### ISSUE TITLE
Archive Project

### ISSUE THREAD

**Issue by EvanCarroll** [ytdl-org/youtube-dl#30183]
Following in the same vein of #30104 and #29965

It would be nice if the project was archived (GitHub functionality) so immediately we'd know that it's dead (officially), and even better if [yt-dlp](https://github.com/yt-dlp/yt-dlp) was pointed out as the successor.

**Comment by 89z** [comment]
This issue has been posted many times. Please do not post duplicate issues.

**Comment by SwapnilSoni1999** [comment]
> This issue has been posted many times. Please do not post duplicate issues.

need reference

**Comment by 89z** [comment]
> need reference

Just look at the original comment. Author already knows issues surrounding the status of this project have been discussed already many times recently. You can tell this, because they even linked to two other issues.

So given the obvious lack of recent updates, its rather pointless to post yet another issue with slightly different wording. Please dont, and please stop. Its just creating noise for people who have actual issues with the software.

**Comment by EvanCarroll** [comment]
Asking if the project is dead isn't an action item. This is an action item. I don't presume everyone knows about GitHub Project Archival, and it's very easy to do because it shuts down the conversation that the author is clearly not wanting to participate in.

**Comment by 89z** [comment]
> I don't presume everyone knows about GitHub Project Archival, and it's very easy to do because it shuts down the conversation that the author is clearly not wanting to participate in.

This project has over one hundred thousand stars. Do you really think that the maintainers dont already know about this? They know about it. It hasnt been done, because of reasons we dont know about. You might not like that the project is inactive, but hasnt been archived. But guess what? You dont get to decide what projects are archived.

So just please accept that the world doesnt always work the way we want it to, and move on.

**Comment by 89z** [comment]
> How'd I do?

Go ahead bro, post all the pointless issues you want. But while youre doing that, maybe your time would be better spent looking at other YouTube projects. I see you mention YT-DLP already, thats a good option, and several others are available too. I dont know why people get in their head that they can only use one project ever. Oh well.

**Comment by EvanCarroll** [comment]
I already found my solution. You're going to tell me how to better spend my time? You make a habit of being a dufus on GitHub bug trackers and gets their issues closed and tagged for "stupid"? Lol

https://github.com/LSPosed/LSPosed/issues/1318

And this one asking for a style change,

https://github.com/tpope/vim-markdown/issues/174

And here you are policing a dead projects GitHub tracker. Hilarious.

**Comment by 89z** [comment]
> I already found my solution. Again, it's just a friendly notice. ;) You're going to tell me how to better spend my time? You make a habit of being a dufus on GitHub bug trackers and gets their issues closed and tagged for "stupid"? Lol

You are weird dude. Its not normal to go trawling through other users posted issues in order to find some "sick burn". You should get some help.

**Comment by EvanCarroll** [comment]
I am not out to get you. I just know _of_ you. You're an [jerk on StackOverflow too (and suspended there too)](https://stackoverflow.com/users/1002260/steven-penny). SMALL WORLD. Amirite? Don't go kicking a hornets in EVERY COMMUNITY. This is my topic, you came here on a high horse to police it and got burned.

PS I found your post a few months ago https://meta.stackoverflow.com/questions/400760/moderator-deleting-answers-without-marking-duplicate-questions

[I posted similarly,](https://web.archive.org/web/20211019025613/https://meta.stackoverflow.com/questions/412352/lets-re-evaluate-the-duplicate-answer-policy-and-find-a-better-solution)

**Comment by 89z** [comment]
> SMALL WORLD. Amirite? Don't go kicking a hornets in EVERY COMMUNITY. This is my topic, you came here on a high horse to police it and got burned.

Not really. I have my [own implementation][1] of YouTube API, so I suggest it to people when appropriate. I am here to help people that used to use the YouTube-DL, and now maybe are having trouble with certain extractors.

Im not really here to deal with dipshit edgelords that want to pick a fight with anyone who disagrees with them. The simple fact of the matter is that the maintainers of this project arent active, and havent been for some months. So for you to post essentially the same issue thats been posted again [1] and again [2][3][4][5] is not only pointless, but its annoying to people who might be here actually trying to help with broken extractors and such. So in summary: fuck off.



1. https://github.com/ytdl-org/youtube-dl/issues/29753
2. https://github.com/ytdl-org/youtube-dl/issues/29965
3. https://github.com/ytdl-org/youtube-dl/issues/30022
4. https://github.com/ytdl-org/youtube-dl/issues/30098
5. https://github.com/ytdl-org/youtube-dl/issues/30104

[1]://github.com/89z/mech

**Comment by EvanCarroll** [comment]
> [_"I have always lived by the rule that if you are in a hole, keep digging!"_ - 89z](https://meta.stackoverflow.com/a/400798/124486)


So you're here self-promoting on the off-chance someone doesn't know of your fishy package (which you've already gotten yourself suspended for spamming StackOverflow with) -- presumably you think it may be of assistance to the person you're spamming.

And little old me comes to post **once** requesting archiving of the package, and you basically jump on my ass and tell me I'm wasting my time, that the author already knows how GitHub archiving works, and that there other issues (which never mention GitHub archiving that should dissuade my good-faith attempt to communicate and otherwise unique suggestion).


> Im not really here to deal with people that want to pick a fight with anyone who disagrees with them. 

You literally came here and dropped messages so absurdly combative that you shame-deleted them. You **CERTAINLY** came here to pick a fight.

**Comment by 89z** [comment]
> "I have always lived by the rule that if you are in a hole, keep digging!"

You keep quoting me from other sites like its some cool tactic, but its just creepy. Also it shows that you dont really have an argument, as youre just reaching for ad-hominem attacks.

> You literally came here and dropped messages so absurdly combative that you shame-deleted them. You **CERTAINLY** came here to pick a fight.

I am here for reason previously stated. To help users who might have trouble with different extractors. Also I make a habit of informing users when they have posted duplicate issues, as in this case.

**Comment by EvanCarroll** [comment]
I think it's creepy to troll some dead project's issue tracker like it's your own dark alley telling off people that can't serve your motive of creating a fan base for your very fishy alternative.

**Comment by 89z** [comment]
> I think it's creepy to troll some dead project's issue tracker

Isnt that what youre doing?

> telling off people that can't serve your motive

My motive is to help people having problems with different extractors. If you have a problem with that, I dont care.

> of creating a fan base

I am here to help people. I have my own tool that works. YouTube-DL still works in some cases, but some extractors are currently messed up. I dont see anything wrong with suggesting an alternative, even if its one I wrote myself.

**Comment by EvanCarroll** [comment]
* I'm responding to you, not trolling the tracker for users to redirect or policing it against issues that I don't like.
* _"My motive is to help people having problems with different extractors. If you have a problem with that, I dont care."_ that's not your motive. This issue has nothing to do with that and you came here to be a jerk (shame deleted all your messages, but all the same).
* _"I dont see anything wrong with suggesting an alternative, even if its one I wrote myself."_ Neither do I have at it. But still the information you offer is an advertisement for your project. The information I offer is about GitHub's archive functionality (to no benefit of me).

**Comment by 89z** [comment]
> I'm responding to you, not trolling the tracker for users to redirect or policing it against issues that I don't like.

These are just more pointless attacks, so I will refer back to my original point. This issue has been posted many times. Please do not post duplicate issues.

> that's not your motive. This issue has nothing to do with that and you came here to be a jerk (shame deleted all your messages, but all the same).

I think I am in a better position to decide what my motives are. Perhaps you should not make a habit of telling people what their motives are, especially if youve never even met them.

> the information you offer is an advertisement for your project. The information I offer is about GitHub's archive functionality (to no benefit of me).

If it helps the user, and it helps me too, who cares? I didnt suggest any tool in this thread, so why do you care what I do in other threads? That sounds like you are the one policing now.

**Comment by aiotter** [comment]
Who are you talking to? Does anyone keep deleting their original posts?

**Comment by EvanCarroll** [comment]
@aiotter this guy https://github.com/89z seems to be gone now though.

**Comment by SwapnilSoni1999** [comment]
> Who are you talking to? Does anyone keep deleting their original posts?

Yeah the person deleted his comments

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@aiotter https://archive.md/RTwMS

**Comment by fstirlitz** [comment]
Has anyone tried reaching out to GitHub to have them do it administratively? The maintainers are apparently asleep at the wheel.

**Comment by rusty-snake** [comment]
This issues can be closed IMHO, #30568.
