### ISSUE TITLE
Slow download speeds.

### ISSUE THREAD

**Issue by Just-another-pleb** [ytdl-org/youtube-dl#30192]
I'm asking this to check if it is a known problem.

I am running Ubuntu 21.04 and have this version:
`youtube-dl --version
2021.06.06
`

When I am downloading videos the speed does seem to be limited to about 56KiB/s

I've heard youtube detect downloads and speed limit them.

**Comment by dirkf** [comment]
Wow. If only you'd searched the issues you might have found from one of the at least *14* related issues that it is.

**Comment by luagugus** [comment]
Me too I have same problem

**Comment by 89z** [comment]
Please provide example video

**Comment by dazemc** [comment]
Not sure when @dirkf PR will be merged but here is a build for people that don't know how to cherry pick commits, https://github.com/dazemc/youtube-dl/releases/tag/2021.06.06-CherryPicked

**Comment by joootdooot** [comment]
just use yt-dlp, youtube-dl is slow to update anything

**Comment by Just-another-pleb** [comment]
> Not sure when @dirkf PR will be merged but here is a build for people that don't know how to cherry pick commits, https://github.com/dazemc/youtube-dl/releases/tag/2021.06.06-CherryPicked

my dumb question:  Looking at that link, I am not sure there is a version for ubuntu.

**Comment by rautamiekka** [comment]
> > Not sure when @dirkf PR will be merged but here is a build for people that don't know how to cherry pick commits, https://github.com/dazemc/youtube-dl/releases/tag/2021.06.06-CherryPicked
> 
> my dumb question: Looking at that link, I am not sure there is a version for ubuntu.

You use the file named `youtube-dl`, just execute it:

```bash
##Add the permission to execute:
chmod u+x youtube-dl

##Use the app:
./youtube-dl PARAMETERS
```

**Comment by Just-another-pleb** [comment]
Thank you very much.
