### ISSUE TITLE
Youtube-dl stopped working when I upgraded to MacOS Monterey 12.0.1

### ISSUE THREAD

**Issue by ovvldc** [ytdl-org/youtube-dl#30195]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
> youtube-dl -f '(mp4)[height=720]' -v https://www.youtube.com/watch?v=jE9ruBknk3Y
zsh: no matches found: https://www.youtube.com/watch?v=jE9ruBknk3Y

(I realise that this does not look like the output you are looking for. I don't know why.)
```

## Description

I installed youtube-dl via Homebrew on MacOS 10.5 Monterey (I newly updated to Monterey weekend). I am trying to download a youtube video for watching offline. I am sure that the URL works, and the syntax used to work and doesn't give an error.  In fact, the error appears with all URLs I tried on youtube at least.

I have no idea why MacOS 12.0.1 broke youtube-dl. Or maybe it is the switch to Zsh as default. Apple seems to have screwed up rather badly with this one.

**Comment by 89z** [comment]
Looks to be region restricted:

https://unblockvideos.com/youtube-video-restriction-checker#url=jE9ruBknk3Y

**Comment by ovvldc** [comment]
I am in a country that is green for this video and I am not using a VPN.

And I get the same output for this video, which is not region restricted anywhere: https://www.youtube.com/watch?v=_QvaiA8FI5A

**Comment by 89z** [comment]
`_QvaiA8FI5A` works fine for me, maybe its a Zsh issue. Have you tried any other shells?

**Comment by michealespinola** [comment]
Try putting the URL in quotes. This is a recurring issue in the zsh shell.

**Comment by ovvldc** [comment]
I just tried on Bash, that works. I will try with quotes on Zsh. Thanks!

**Comment by ovvldc** [comment]
Youtube-dl works on Zsh on MacOS if you put the URL in quotes.

Note that Zsh is the default shell on MacOS now, so maybe someone can add that to the install notes on Homebrew?

**Comment by michealespinola** [comment]
I wish someone woud, but tbf, it's a common recommendation to /always/ have your URL in quotes (for multiple reasons). I'm a Windows guy, and the only reason I know this is an issue with zsh is because of how many times it has been asked about by Mac people on youtubedl subreddit.

**Comment by michealespinola** [comment]
Oh, no waste at all. There are just different circles of information out there. Just glad it is an easy resolution for you.

**Comment by noahbroyles** [comment]
Yes, always quote URLs in your shells. I'm a Mac guy, it's just what you do.

**Comment by rautamiekka** [comment]
Unless the URL looks like 
`https://www.example.com/pages/page1.html`
it must always be quoted no matter the shell/terminal (unless the shell/terminal is smart enough to do it automatically on paste).

Double-quotes work on nearly every shell/terminal (the method on Command Prompt on Window$), while most (all ?) NIX and POSIX ones (including PowerShell) accept single quotes as a raw string indicator (equivalent to Python's `r"..."`).

**Comment by SnowComfortable6726** [comment]
Alternatively, you could add the following lines to `~/.zshrc`:
```
autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic

autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic
```

**Comment by dirkf** [comment]
That was a different issue, now fixed.
