### ISSUE TITLE
How to force download files through youtube-dl in Django webapp

### ISSUE THREAD

**Issue by mahmutgundogan** [ytdl-org/youtube-dl#30206]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have made a youtube video downloader app with django and youtube-dl.

The problem in the final link which I am getting is something like https://r5---sn-gwpa-jj0z-... and goes.

These links are opening files in the browser how to make them downloadable on clients machine?

This must be technologically possible. How to get final url downloadable.

Thanks

**Comment by rautamiekka** [comment]
IIUC, you want the link start downloading by the viewer's machine, and the Django app is running on a remote machine ?

**Comment by mahmutgundogan** [comment]
yes. For example when i input https://www.youtube.com/watch?v=IUN664s7N-c youtube-dl gives me:

https://r2---sn-p5qlsnzd.googlevideo.com/videoplayback?expire=1636164086&ei=lo2FYez8Do2P8gTEnbPgBw&ip=3.223.195.111&id=o-ABZGOvGkdee_BgyKCbMDjBJIPacn1a48HqB7NN19jYoQ&itag=18&source=youtube&requiressl=yes&mh=tb&mm=31%2C29&mn=sn-p5qlsnzd%2Csn-p5qs7ned&ms=au%2Crdu&mv=m&mvi=2&pl=15&initcwndbps=897500&vprv=1&mime=video%2Fmp4&ns=e1BvZhDpEgKV-cCnsK7RHdAG&gir=yes&clen=11913115&ratebypass=yes&dur=158.499&lmt=1626299149493627&mt=1636142219&fvip=2&fexp=24001373%2C24007246&c=WEB&txp=5530434&n=p0DyWkRja7N7wswy&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgETEYEZh4JHWfKwnZD9CN20CM-jHfa2wcSXwEuvcHNLICIQC_HjQCVJJ299_T11ONxLZ_XR8g6WKVT46xUgrTZj5eXw%3D%3D&sig=AOq0QJ8wRQIgSBy2qvXOSyS6o5c_CFW9g9MhC8Hsvv0rFRbIGy3KIaYCIQDHtID5sKF_CYKflNzC4AOK6Ndxzm9hiKMVI9CtDdbmgQ==

But this link opens new tab and starts playing the video. You can download from there but what i want is downloadable link. I have spend days for that a lot of people asked but nothing seems working.

**Comment by rautamiekka** [comment]
In which case you need to tell ytdl the output format, which is the easiest way to DL the thing. Pretty sure that's possible when importing ytdl.

If all else fails, you can use the normal HTTP downloading, throwing the DL dialog so the User can decide.

**Comment by mahmutgundogan** [comment]
Apparently, only people who doesn't know the answer of this problem aware of this problem. This question asked many times on stackoverflow, it should be obvious one. Some other sites are doing it. like y2mate. One possible workaround is alt + click on download links. I have tried using js. Ctrlkey is working, shiftkey is working but altkey is not working.

**Comment by dirkf** [comment]
Modern browsers have had the configuration option that would allow you to choose how to handle media content stripped. Anything that looks like HTML5 video will be played in the browser.

You may be able to force, or at least suggest, a download using the [`download` attribute in the link](https://svarden.se/post/right-click-and-save-as).

**Comment by mahmutgundogan** [comment]
"Download" attribute only works when requested file hosted on same domain. If you right click and "save as" thats downloads the file. Or alt + click also works. I want just one click to download button. This must be simple but i can't find it.

**Comment by dirkf** [comment]
No. it's not simple. Get your users to install an old version of Firefox ... Or install a browser extension ... Or turn off HTML5 autoplay so that they can SaveAs without playing ... Or proxy the linked stream and set the Content-type (IIRC you can't just redirect because the browser believes the last Content-type it received).

You can wrap the URL up in a playlist and serve a link to that instead, but then your users have to associate a downloader program or script with that playlist type.

**Comment by pukkandan** [comment]
why is this issue in youtube-dl issue tracker? 🤔

**Comment by dirkf** [comment]
It is a **question** and there's no-one who can close it as off-topic?

**Comment by pukkandan** [comment]
my question was aimed at OP, sorry for not being clear

**Comment by mahmutgundogan** [comment]
> my question was aimed at OP, sorry for not being clear

Because github only allows you to ask question from issue tracker. What choice do i have?
