### ISSUE TITLE
Issue with "Confluent"

### ISSUE THREAD

**Issue by helperman** [ytdl-org/youtube-dl#30203]
## Checklist
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```
C:\Users\temp1\Downloads>youtube-dl -v -f best https://videos.confluent.io/watch/dizWs7BRkxRo5heZvEQn9F
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'best', 'https://videos.confluent.io/wat
ch/dizWs7BRkxRo5heZvEQn9F']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.4 (CPython) - Windows-8.1-6.3.9600-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[generic] dizWs7BRkxRo5heZvEQn9F: Requesting header
WARNING: Falling back on generic information extractor.
[generic] dizWs7BRkxRo5heZvEQn9F: Downloading webpage
[generic] dizWs7BRkxRo5heZvEQn9F: Extracting information
[debug] Invoking downloader on 'https://cdn.vidyard.com/videos/pgl2gyf1PuRakGaBb
RiQFA/sd.mp4?DLDKFeYje5Z2LKnzVyKfjJZN9ec4YlqL1KpvKGSx20aFa3V6MznLyrd92hu4wxDVCp9
bKokpTy5FThnsH2Iii4jKkoPB_tOtZewWTiclg31ncjZiB_ALg0hgHRoztEcoQ0I5zdB_Pm-0'
[download] Destination: Kafka Tutorials - Window Final Result with Loic Divad _
Stockholm Apache KafkaR Meetup by Confluent-sd.mp4
[download] 100% of 284.20MiB in 00:49
```

## Description
I try to download this video: https://videos.confluent.io/watch/dizWs7BRkxRo5heZvEQn9F
Youtube-dl downloads it with bad quality (640x360) when a better quality exists (1080).

**Comment by dirkf** [comment]
confluent.io isn't an explicitly supported site, but yt-dl manages to find `https://cdn.vidyard.com/videos/pgl2gyf1PuRakGaBbRiQFA/sd.mp4?lmI9aps0UASBZaU4REDZq9FIXlotPFyMf1tsfm4X2zTO8Jy67NJ4FmQJFYxZWEkrURMQDTPenPvk-gPrz6yyYPxCunJkzrtgxvgIShjQZLWZqPMzA08tGdSReMjthyO1uTQmunW1CA` in the static HTML of the page linked by OP.

If other formats are available, it would be necessary to support either confluent.io, or perhaps vidyard.com, with a new extractor to find them. Meanwhile, someone who really wanted to archive the 1080 version might be able to find its URL using the browser's Development Tools.

**Comment by helperman** [comment]
Hope someday it will be added to a long list of supported sites.

**Comment by kikuyan** [comment]
There is a "Site Support Request" template. Please use it to make new request and close this.
