### ISSUE TITLE
Youtube download channel pages for all eternity

### ISSUE THREAD

**Issue by ballsystemlord** [ytdl-org/youtube-dl#30219]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
[yt-dl2.log](https://github.com/ytdl-org/youtube-dl/files/7509497/yt-dl2.log)

## Description

This URL, when accessed by youtube-dl, or a browser, loops it's list of videos. That is to say, the list of videos becomes infinite because the same videos keep getting re-added to the list.
https://www.youtube.com/user/Teslaundmehr/videos
There are only about 500 videos on this channel page.

This is not really youtube-dl's fault. It's youtube.com's fault. The channel page shouldn't be looped. As this may prove to be a problem for more and more channels, I'm reporting this in hopes that a work around is added to youtube-dl.
In the meantime, I can just add --playlist-items arg.

Thanks!

**Comment by ballsystemlord** [comment]
Update, it's more than one user. This just started today. Here's another one. https://www.youtube.com/c/LucyLFitness/videos

**Comment by ballsystemlord** [comment]
Update: it's more than one channel. It's looking like they're all affected.
Ok, you'll only get 1 video if you set an items limit of 1000. You need to use the playlist option. There are 169 videos in the first channel.

**Comment by dirkf** [comment]
Reported as fixed in #30220.

**Comment by dirkf** [comment]
@ballsystemlord, this appears to have been a problem with the YT site that is now fixed. Please feel free to close the issue.

**Comment by ballsystemlord** [comment]
Oh! Sorry, I thought it would have been closed with the other similar problems.
