### ISSUE TITLE
HTTP Error 404: Not Found (caused by HTTPError());

### ISSUE THREAD

**Issue by latrine-lizard138** [ytdl-org/youtube-dl#30211]
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: ['--no-check-certificate']
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://study-for-fe-electrical.usefedora.com/courses/743489/lectures/13558322', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[generic] 13558322: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 13558322: Downloading webpage
[generic] 13558322: Extracting information
[Teachable] Downloading study-for-fe-electrical.usefedora.com login page
[Teachable] Logging in to study-for-fe-electrical.usefedora.com
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

Trying to download videos from a course and receiving this error:
 ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I've tried:
-clearing cache, 
-passing a cookies.txt file 
-attaching header
-forcing ipv4
youtube-dl works fine if I try it on the videos that do not require a login by the way, it is JUST the paid videos that will not work even though I am passing the correct user account info.

Thanks

**Comment by dirkf** [comment]
The Teachable login using username and pw is failing, and that breaks the extraction. Omit the username and pw and just pass a cookies file for a logged in session.

Someone with valid authentication details could try to debug the login. It's trying post the login form to a URL and it's being rejected. Maybe it's not finding the right URL in the page; maybe the login protocol has changed. `--print-traffic` could clarify the failure.

**Comment by latrine-lizard138** [comment]
> The Teachable login using username and pw is failing, and that breaks the extraction. Omit the username and pw and just pass a cookies file for a logged in session.

This worked - I thought I tried this previously but must've made a mistake somehow
Thank you
