### ISSUE TITLE
download from youtube using id start with '-'

### ISSUE THREAD

**Issue by forestchen1224** [ytdl-org/youtube-dl#30215]
## Checklist

- [x ] I'm reporting a site feature request
- [x ] I've verified that I'm running youtube-dl version **2021.06.06**
- [x ] I've searched the bugtracker for similar site feature requests including closed ones

## Description

1. I use the option '--get-id' to get the id of the video from youtube  
2. I download the video with that 'id'.
3. however, when the 'id' starts with '-'(-EIg5ZXlvww, for example), the app will parse it as a option. and  raise error "no such option -E"
4. I am not sure  how to make it. maybe adding a special character in front of the id before parsing the args
5. a  temp solution: substitute
  ```shell
  youtube-dl --id "-EIg5ZXlvww"
```
with 
```shell
youtube-dl  'https://www.youtube.com/watch?v=-EIg5ZXlvww'  
```

**Comment by kikuyan** [comment]
[How do I download a video starting with a -?](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-download-a-video-starting-with-a--)

**Comment by forestchen1224** [comment]
sorry
