### ISSUE TITLE
Redacted

### ISSUE THREAD

**Issue by Richy-Z** [ytdl-org/youtube-dl#30214]
The contents have been redacted

**Comment by 89z** [comment]
YouTube-DL definitely breaks YouTube ToS. Whether each person cares about that is their own decision to make. While it might not be within YouTube ToS, some might say you have a moral right to download any publicly available video, and I do include myself within that class. Your best bet is to just be honest and submit the screencast as it truly is.

Instructing people on how to get around YouTube ToS shouldnt really be discussed here, given past history.

**Comment by Richy-Z** [comment]
> YouTube-DL definitely breaks YouTube ToS. Whether each person cares about that is their own decision to make. While it might not be within YouTube ToS, some might say you have a moral right to download any publicly available video, and I do include myself within that class. Your best bet is to just be honest and submit the screencast as it truly is.
> 
> Instructing people on how to get around YouTube ToS shouldnt really be discussed here, given past history.

Thanks. I guess we'll see how it goes with the API team.
