### ISSUE TITLE
embeded youtube-dl usage

### ISSUE THREAD

**Issue by songsh** [ytdl-org/youtube-dl#30231]
## Checklist

- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

i use youtube-dl in python,  run the code, bug is ffmepg not found, need install ffmpeg ? i use youtube-dl.exe, can download the video

**Comment by rautamiekka** [comment]
Extract `ffmpeg-git-full.7z` from https://www.gyan.dev/ffmpeg/builds/ and point `--ffmpeg-location` to the folder. Or place the EXE's to the same folder as ytdl.

**Comment by songsh** [comment]
thanks, begin, i use the exe file,  bug is MFlat.dll is missing, then i use the git.7z file, the program can run. 
now i do not know, 
`ydl_opts = {

        'download_archive':'c:/images/'
        'logger': MyLogger(),
        'progress_hooks': [my_hook],
    }`
how to set download folder, and the file name.

**Comment by songsh** [comment]
anyone and help me, thanks,

**Comment by dirkf** [comment]
The filename is in the info_dict returned by the `extract_info()` method of `YoutubeDL`.
