### ISSUE TITLE
 Watch youtube copyright music video original artist

### ISSUE THREAD

**Issue by ebrahimhoseini433433** [ytdl-org/youtube-dl#30232]
Hello, I am an Iranian. My English is not good Why YouTube_dl does not download copyrighted works such as deleted YouTube videos in the playlist, except that the software does downloads copyrighted works such as copyrighted music videos but can not be downloaded So how to go to YouTube through Firefox Chrome Edge browsers that we can also see them and then download them through YouTube_dl

**Comment by rautamiekka** [comment]
You can't view the ones that read 'removed' (or 'hidden', for that matter, unless you've been added to the allowed ppl) in the browser, and you can't DL ones YT doesn't let you access in the 1st place, so there's nothing unusual there.

But if you've a link which works just fine in the browser but fails with ytdl, then answer all the things in the bug report template.

Btw, you should be using https://github.com/yt-dlp/yt-dlp to continue downloading. You'll need Python 3.6+, though.

**Comment by ebrahimhoseini433433** [comment]
Is there a way I can see copyrighted works on YouTube ? 😐

**Comment by rautamiekka** [comment]
Show a link to work on.

**Comment by ebrahimhoseini433433** [comment]
https://m.youtube.com/watch?v=UM517H4RqGQ&list=PLqb41RD9ooQNDiVOgzqlTbcPORfnHO8hb&index=6

https://m.youtube.com/watch?v=OAifzyTw0e8&list=PL2FD3818BE3EEEBC9&index=6

https://m.youtube.com/watch?v=oyDxa1IBfVU&list=PL2FD3818BE3EEEBC9&index=13

https://m.youtube.com/watch?v=OAifzyTw0e8&list=PLDDB83567D11CEA26&index=6

https://m.youtube.com/watch?v=YLCfGwdi_2Y&list=PLDDB83567D11CEA26&index=10
https://m.youtube.com/watch?v=e-RqoESp-BU&list=PL77737E11CF6B3F77&index=4

**Comment by rautamiekka** [comment]
Like I said, if you can't watch it through YT, you can't DL it either. I just tried and they all failed to DL, even with an USA VPN.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30293
