### ISSUE TITLE
No video formats found; please report this issue on...

### ISSUE THREAD

**Issue by juoake** [ytdl-org/youtube-dl#30254]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, when I try command youtube-dl https://www.youtube.com/watch?v=ImyU654znR8,
I'm getting warning: **WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests**,
and error: **ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.**
Youtube-dl has worked before on this machine, today it stopped working. I tried removing youtube-dl with APT package manager and installed it with pip, no change.
I'm using Linux Mint 20.2 with KDE Plasma desktop environment

**Comment by juoake** [comment]
[https://imgur.com/a/Y7MU1rT](url)

**Comment by 89z** [comment]
https://i.imgur.com/4eWjPs8.png
