### ISSUE TITLE
No SSE2 Youtube-DL verison?

### ISSUE THREAD

**Issue by YoshiKill** [ytdl-org/youtube-dl#30261]
Greeting. I try to find working version of Yt-dl that work with old CPU(like P3 Athlon Xp) without SSE2 instruction. Its posible?

**Comment by dirkf** [comment]
If you have a Python 2.6+ installation for that platform, then yt-dl should run (though maybe not the packaged single file version). You should ask the question in a forum for Python on old computers.

**Comment by october262** [comment]
> 



> Greeting. I try to find working version of Yt-dl that work with old CPU(like P3 Athlon Xp) without SSE2 instruction. Its posible?

should work from windows xp on up - https://www.wikihow.com/Use-Youtube%E2%80%90dl

**Comment by YoshiKill** [comment]
> If you have a Python 2.6+ installation for that platform, then yt-dl should run (though maybe not the packaged single file version). You should ask the question in a forum for Python on old computers.

thanks its WORKING! i install last ver of Python 2.7.18 for No SSE2 and  Microsoft Visual C++ 2010 Redistributable Package. And it's helps. 



> > Greeting. I try to find working version of Yt-dl that work with old CPU(like P3 Athlon Xp) without SSE2 instruction. Its posible?
> 
> should work from windows xp on up - https://www.wikihow.com/Use-Youtube%E2%80%90dl

yep, thanks
