### ISSUE TITLE
ERROR: No video formats found; please report this issue

### ISSUE THREAD

**Issue by DiyRex** [ytdl-org/youtube-dl#30260]
OSError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Use the [template](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=)!
