### ISSUE TITLE
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 2021-11-24T08:54:18.660747+00:00 app[worker.1]: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 2021-11-24T08:54:18.664458+00:00 app[worker.1]: local variable 'audio_file' referenced before assignment

### ISSUE THREAD

**Issue by mrkicks** [ytdl-org/youtube-dl#30264]
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2021-11-24T08:54:18.660747+00:00 app[worker.1]: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2021-11-24T08:54:18.664458+00:00 app[worker.1]: local variable 'audio_file' referenced before assignment

WHAT TO DO

**Comment by glthm** [comment]
> Be sure to call youtube-dl with the --verbose flag and include its complete output.

Is that the complete output after calling youtube-dl with the --verbose flag? Does not seem like it.

Also, what version are you using?

I'm not related to the project at all but I couldn't see a raised issue this incomplete without reacting

**Comment by dirkf** [comment]
OP's problem appears to be in a script or utility program that uses yt-dl: PR #30142 applies.

Otherwise, OP is trying to use a corrupt version of the Simplecast extractor.

**Comment by Vangelis66** [comment]
@mrkicks : 

PLEASE **edit** the original title of your issue; what you wrote there should've been posted in the **body** of the issue itself (in the context of a verbose log), NOT as title; title should be short, condensed and descriptive of the nature of the issue (e.g. Failure while trying to fetch xxxx), so it could be easily searched and identified via an "issues search" (a pre-requisite to submitting a new issue...). 

Thanks!

**Comment by wankio** [comment]
2days ago is the first time i know about youtube throttling and when searching related issues i found first issue is about 1month ago
use fork fixed youtube-dl in 10days ago still not working hmm
