### ISSUE TITLE
Where does the `timestamp` value come from?

### ISSUE THREAD

**Issue by zbrasseaux** [ytdl-org/youtube-dl#30263]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

I am attempting to obtain the timestamp value via python for youtube videos. I have seen that it can be done when using youtube_dl through the command line with youtube videos. However, the python snippet bellow (specifically, `extract_info()`) only returns upload_date, and note a timestamp value.

Any insight is appreciated

```python
import youtube_dl

ydl = youtube_dl.YoutubeDL()

extracted_data = ydl.extract_info('https://www.youtube.com/watch?v=euf-EQ8udYw', download=False)
```

**Comment by dirkf** [comment]
`timestamp` is not set in the example above, nor with the command-line invocation `youtube-dl -j 'https://www.youtube.com/watch?v=euf-EQ8udYw'`; the YT extractor doesn't set `timestamp`, as you can see by inspecting the `TESTS` in the extractor: if `timestamp` were being extracted, a test case that didn't include it would fail.

So you can do this instead:
```
import youtube_dl
from youtube_dl.utils import unified_timestamp, hyphenate_date

ydl = youtube_dl.YoutubeDL()

extracted_data = ydl.extract_info('https://www.youtube.com/watch?v=euf-EQ8udYw', download=False)
if 'timestamp' not in extracted_data:
    timestamp = unified_timestamp(hyphenate_date(extracted_data.get('upload_date', '')))
    if timestamp:
        extracted_data['timestamp'] = timestamp
```

**Comment by zbrasseaux** [comment]
Thank you so much!

**Comment by dirkf** [comment]
The `upload_date` has no time, so it defaults to midnight UTC in the conversion. I suppose you may see 18:00 in your local time: eg, after running the modified code posted above,
```
>>> import datetime
>>> datetime.datetime.utcfromtimestamp(extracted_data['timestamp']).isoformat()
'2021-11-23T00:00:00'
>>> 
```
