### ISSUE TITLE
xvideos resulting in 404

### ISSUE THREAD

**Issue by sirEgghead** [ytdl-org/youtube-dl#30271]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.xvideos.com/video64651723/18yo_youtuber_gets_horny_watching_hentai_during_the_stream_and_masturbates_-_emma_fiore']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-6parrot1-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[XVideos] 64651723: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description

Tried downloading several different videos from this site over the course of the past week.  All have resulted in 404, whereas previously, videos have been able to be downloaded from this site without error in the recent past. Confirmed that URLs used are able to be viewed in a web browser without error. Verified youtube-dl version. Updated to 2021.06.06. Tried again with no change in results. Searched github issues for similar posts. Found only one that was locked as off topic. I do not understand the nature of that particular topic being locked, so if I am making a mistake by posting this issue, please forgive me. The site is listed in the sites supported by youtube-dl at [https://github.com/ytdl-org/youtube-dl/blob/master/docs/supportedsites.md](https://github.com/ytdl-org/youtube-dl/blob/master/docs/supportedsites.md)

**Comment by chrecinos** [comment]
Same here, all the same checks:
```
youtube-dl "https://www.xvideos.com/video64651723/18yo_youtuber_gets_horny_watching_hentai_during_the_stream_and_masturbates_-_emma_fiore" --verbose
[debug] System config: []
[debug] User config: ['-f', 'bestvideo[ext=mp4][vcodec*=avc1.640]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--restrict-filenames', '--continue']
[debug] Custom config: []
[debug] Command-line args: ['https://www.xvideos.com/video64651723/18yo_youtuber_gets_horny_watching_hentai_during_the_stream_and_masturbates_-_emma_fiore', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.9 (CPython) - macOS-12.0.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1
[debug] Proxy map: {}
[XVideos] 64651723: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by dirkf** [comment]
The site no longer understands URLs ending in `video{video_id}/`. Apparently we just have to add some final component:
```
--- old/youtube-dl/youtube_dl/extractor/xvideos.py
+++ new/youtube-dl/youtube_dl/extractor/xvideos.py
@@ -82,7 +82,7 @@
         video_id = self._match_id(url)
 
         webpage = self._download_webpage(
-            'https://www.xvideos.com/video%s/' % video_id, video_id)
+            'https://www.xvideos.com/video%s/0' % video_id, video_id)
 
         mobj = re.search(r'<h1 class="inlineError">(.+?)</h1>', webpage)
         if mobj:
```

**Comment by Kano97** [comment]
I don't mean to reopen this issue, but I'm having the same issue. How may I patch this for the executable on Windows?

**Comment by dirkf** [comment]
See https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-972929975
 and/or https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-965425680.

**Comment by open99182** [comment]
> The site no longer understands URLs ending in `video{video_id}/`. Apparently we just have to add some final component:
> 
> ```
> --- old/youtube-dl/youtube_dl/extractor/xvideos.py
> +++ new/youtube-dl/youtube_dl/extractor/xvideos.py
> @@ -82,7 +82,7 @@
>          video_id = self._match_id(url)
>  
>          webpage = self._download_webpage(
> -            'https://www.xvideos.com/video%s/' % video_id, video_id)
> +            'https://www.xvideos.com/video%s/0' % video_id, video_id)
>  
>          mobj = re.search(r'<h1 class="inlineError">(.+?)</h1>', webpage)
>          if mobj:
> ```
> 
> [Update] Patch instructions for Unix-like systems not using a single file self-extracting archive (ie `ls -l $(which youtube-dl)` shows a file <1kB, not >1.5MB):
> 
> * find the installation directory where the file `YoutubeDL.py` is;
> * save the patch from this post (from the first `---` including the last `:`), say `30271.patch`;
> * become admin (eg, `sudo -i`);
> * then:
> 
> ```
> cat 30271.patch | (cd /path/to/ytdl/installation && patch -p 2)
> youtube-dl --version
> ```
> 
> Very careful patchers whose `patch` supports these options may like to run the command adding `--dry-run --verbose` first to verify the patch.

Hello,

I tried to do as you said but still having the same problem. Please check if this fix still works.

I do it on Centos.

1. download source https://yt-dl.org/downloads/2021.06.06/youtube-dl-2021.06.06.tar.gz and extract and chmod 777 on /root/youtube-dl

2. copy your code patch and save on /root/30271.patch

3. run command = cat 30271.patch | (cd /root/youtube-dl && patch -p 2)
result :
(Stripping trailing CRs from patch; use --binary to disable.)
patching file youtube_dl/extractor/xvideos.py

4. run command = /root/youtube-dl/youtube-dl --version
result:
2021.06.06

5. run command = /root/youtube-dl/youtube-dl -F https://www.xvideos.com/video65739603/
result:
[XVideos] 65739603: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

What i wrong ?

Please help me.

**Comment by TonyTony999** [comment]
Hi, I just verified and the most recent version already includes this patch in xvideos.py extractor but Im still getting this error when trying to download from xvideos:

`$ youtube-dl https://www.xvideos.com/video66455845/
[XVideos] 66455845: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`
Any ideas about why this is happening? Thanks

**Comment by dirkf** [comment]
The patch is not actually running. Please verify your patch against the instructions above. Especially note:
* different procedures depending on whether your yt-dl is a single file or unpacked, and Windows vs Unix-like;
* if your yt-dl installation is unpacked in a system directory, you need to run yt-dl as admin to update the cached compiled bytecode version;
* if it's a single file, make sure to delete any `extractor/xvideos.pyc` (or `.pyo`) as well as updating or adding the patched `extractor/xvideos.py`.

If the problem persists, please post a verbose (`-v`) log.

**Comment by scramblr** [comment]
Fixed via [https://github.com/ytdl-org/youtube-dl/pull/30393](https://github.com/ytdl-org/youtube-dl/pull/30393) - Awaiting approval.

**Comment by chrecinos** [comment]
> recin

# Fix in macOS installed with Homebrew

Edit the file
```
/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor
```

Find the line with the following code:
```py
            'https://www.xvideos.com/video%s/' % video_id, video_id)
```

Replace it with this
```py
            'https://www.xvideos.com/video%s/0' % video_id, video_id)
```

**Comment by jdrowell** [comment]
> Replace it with this
> 
> ```python
>             'https://www.xvideos.com/video%s/0' % video_id, video_id)
> ```

Thanks, this works for me on Arch Linux. The full path is:

  /usr/lib/python3.10/site-packages/youtube_dl/extractor/xvideos.py

and the line is 84.

**Comment by dirkf** [comment]
In fact, just as proposed in https://github.com/ytdl-org/youtube-dl/issues/30271#issuecomment-979212016 and PR #30278.
