### ISSUE TITLE
Twitch - MPC-BE

### ISSUE THREAD

**Issue by RequiemXN** [ytdl-org/youtube-dl#30277]
How can I fix this? MPC-BE stopped playing Twitch streams. Refers to youtube-dl. There is the latest version.
MPC BE - 1.5.8
![Снимок](https://user-images.githubusercontent.com/66484393/143570738-8db94c83-58a3-4e16-aedf-bbb60b004048.PNG)
.

**Comment by kikuyan** [comment]
Read [BUGS section in the doc](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#bugs).
