### ISSUE TITLE
Rumble.com not supported

### ISSUE THREAD

**Issue by fabioganga** [ytdl-org/youtube-dl#30274]
## Checklist

- [ X] I'm reporting a new site support request
- [X ] I've verified that I'm running youtube-dl version **2021.06.06**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that none of provided URLs violate any copyrights
- [D ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://rumble.com/vponb5-they-falsified-data-pfizer-whistleblower-slams-vaccine-trials.html
- Single video: https://rumble.com/vnmklr-i-got-the-pfizer-vaccine-trump.html

## Description

RUMBLE.COM NOT YET SUPPORTED

**Comment by kikuyan** [comment]
There's a PR #29758.

**Comment by mrwicks** [comment]
I have a workaround for this with wget:

if you do something like:

`wget -O - https://rumble.com/vpr123-this-is-beyong-a-joke-now-how-are-these-our-leaders.html | grep embedUrl`

You'll see a line like:

`embedUrl":"https://rumble.com/embed/vn2oua/"`

You can use:

`youtube-dl https://rumble.com/embed/vn2oua/`

To get it.

**Comment by fabioganga** [comment]
Thanks to both of you @kikuyan @mrwicks !

**Comment by SimonEast** [comment]
As ghost mentioned, there's a pull request for this feature at PR #29758. I think it needed a bit of cleanup before it could be accepted. I'm a developer but my Python is very poor. Is there anyone else who can help get this across the line? I'd be very grateful.

**Comment by SimonEast** [comment]
Or maybe I'll switch to `yt-dlp` instead which I think has fixed this issue.
