### ISSUE TITLE
how to extract channle id name subscriber number

### ISSUE THREAD

**Issue by wanghaisheng** [ytdl-org/youtube-dl#30288]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

https://www.youtube.com/results?search_query=%E5%85%BB%E7%94%9F&sp=EgIQAg%253D%253D

if you type this,you can see channel list, how can I get name,id,subscriber count of all channels in this list

**Comment by kikuyan** [comment]
Doesn't look like a question about youtube-dl.
