### ISSUE TITLE
Fox Nation

### ISSUE THREAD

**Issue by Jambre** [ytdl-org/youtube-dl#30285]
## Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs violate any copyrights
- [X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://nation.foxnews.com/watch/72bffce9f75b730a50e58658679c2985/
- Single video: https://nation.foxnews.com/watch/241b4f966cc9cbb90ad9828d5bafae3f/
- Playlist: https://nation.foxnews.com/cops-nation/season-32/
   ^ Not necessary, would be nice

## Description

Fox Nation is where you can watch Fox's live news and replay full episodes, including their selection of Fox produced shows such as the well known reality Cops show. Fox consistently maintains the highest viewership across basic cable networks.

Would require a Fox Nation subscription, trials are available. https://nation.foxnews.com/

**Comment by kikuyan** [comment]
Duplicate of #24313.

**Comment by Jambre** [comment]
> Duplicate of #24313.

Didn't find that when searching "Fox Nation", my bad. Thanks for referencing.
