### ISSUE TITLE
Can not download a video through an "embeddable" url

### ISSUE THREAD

**Issue by Circiter** [ytdl-org/youtube-dl#30286]
Upon supplying a youtube's "embeddable" url the youtube-dl can not download a corresponding video while it can be downloaded through a usual "watch" links. So it's possible to work around such an issue by replacing a url of the form "www.youtube.com/embed/<id>" by the "www.youtube.com/watch?v=<id>". It certaintly must be automated (by regex, maybe).

**Comment by 89z** [comment]
Please provide example URL

**Comment by kikuyan** [comment]
Seems to have support. Please provide the verbose log to show what's not working.
https://github.com/ytdl-org/youtube-dl/blob/a8035827177d6b59aca03bd717acb6a9bdd75ada/youtube_dl/extractor/youtube.py#L417

**Comment by soheil** [comment]
How long before issues without a response are closed?

**Comment by rautamiekka** [comment]
Never.

**Comment by dirkf** [comment]
Now.
