### ISSUE TITLE
Virustotal detecting file as bitcoinminer

### ISSUE THREAD

**Issue by usernamebutexists** [ytdl-org/youtube-dl#30282]
recently all youtube-dl related files are getting detected as bitcoin miner in virustotal (Trojan.Win32.BitCoinMiner.la)- https://www.virustotal.com/gui/file/78c009f4cf8ae56db150800d55faaac97c127c76c89715b23fe406d85c3c0628
Older version too are getting detected as bitcoin miner , please clarify whats the issue & why. I have used many apps incl open source app but never got this detection (bitcoin miner) unless its illegal crack or kmspico like apps.
all youtube-dl related apps, forks like youtube dl gui also is getting detected as bitcoinminer https://www.virustotal.com/gui/file/4fed7cb6aa66e48b3344620e627c5fa4e8e92716db81e13683ea09dabf049b08
please clarify why

**Comment by hejhopsa** [comment]
beacause it's stuffed with viruses
