### ISSUE TITLE
Add Extractor for music.amazon.com

### ISSUE THREAD

**Issue by hubdows** [ytdl-org/youtube-dl#30283]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Please add an extractor for https://music.amazon.com

**Comment by 89z** [comment]
Please add example

**Comment by hubdows** [comment]
Here is a sample request:

$ youtube-dl --cookies cookies.txt -f bestaudio --extract-audio --audio-format mp3 --audio-quality 320k --add-metadata --no-mtime **https://music.amazon.com/albums/B0034KFK**
QM
[generic] B0034KFKQM: Requesting header
[redirect] Following redirect to https://www.amazon.com/ap/signin?clientContext=133-8672689-3757553&openid.return_to=https%3A%2F%2Fmusic.amazon.com%2Falbums%2FB0034KFKQM&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_webamp_us&openid.mode=checkid_setup&marketPlaceId=ATVPDKIKX0DER&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_cpweb&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=0&siteState=clientContext%3D146-4585753-2139251%2CsourceUrl%3Dhttp%253A%252F%252Fmusic.amazon.com%252Falbums%252FB0034KFKQM%2Csignature%3Dnull
[generic] signin?clientContext=133-8672689-3757553&openid.return_to=https://music.amazon.com/albums/B0034KFKQM&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.assoc_handle=amzn_webamp_us&openid.mode=checkid_setup&marketPlaceId=ATVPDKIKX0DER&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_cpweb&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&siteState=clientContext=146-4585753-2139251,sourceUrl=http%3A%2F%2Fmusic.amazon: Requesting header
WARNING: Falling back on generic information extractor.
[generic] signin?clientContext=133-8672689-3757553&openid.return_to=https://music.amazon.com/albums/B0034KFKQM&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.assoc_handle=amzn_webamp_us&openid.mode=checkid_setup&marketPlaceId=ATVPDKIKX0DER&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_cpweb&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&siteState=clientContext=146-4585753-2139251,sourceUrl=http%3A%2F%2Fmusic.amazon: Downloading webpage
[generic] signin?clientContext=133-8672689-3757553&openid.return_to=https://music.amazon.com/albums/B0034KFKQM&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.assoc_handle=amzn_webamp_us&openid.mode=checkid_setup&marketPlaceId=ATVPDKIKX0DER&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_cpweb&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&siteState=clientContext=146-4585753-2139251,sourceUrl=http%3A%2F%2Fmusic.amazon: Extracting information
ERROR: Unsupported URL: https://www.amazon.com/ap/signin?clientContext=133-8672689-3757553&openid.return_to=https%3A%2F%2Fmusic.amazon.com%2Falbums%2FB0034KFKQM&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_webamp_us&openid.mode=checkid_setup&marketPlaceId=ATVPDKIKX0DER&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_cpweb&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=0&siteState=clientContext%3D146-4585753-2139251%2CsourceUrl%3Dhttp%253A%252F%252Fmusic.amazon.com%252Falbums%252FB0034KFKQM%2Csignature%3Dnull

**Comment by 89z** [comment]
That example redirects to the main page:

~~~
PS C:\> curl -I https://music.amazon.com/albums/B0034KFK
HTTP/2 307
location: https://music.amazon.com/
~~~

So you will either need to provide another link, or if you want to provide credentials, run the following command and comment back with the output:

~~~
echo USER:PASS | age -a -r age1zkz9g0kld97vs826j0r7p3ghvz3zcyd4tcqr2vrxpt0uux7mkycsl77hy6
~~~

https://github.com/FiloSottile/age

**Comment by 89z** [comment]
Page requires sign in. If you want to provide credentials, run the following command and comment back with the output:

~~~
echo USER:PASS | age -a -r age1zkz9g0kld97vs826j0r7p3ghvz3zcyd4tcqr2vrxpt0uux7mkycsl77hy6
~~~

https://github.com/FiloSottile/age

**Comment by llacb47** [comment]
amazon music uses drm, you would not be able to play anything you download.

**Comment by hubdows** [comment]
> amazon music uses drm, you would not be able to play anything you download.

Well, that settles it. :)

**Comment by hubdows** [comment]
llacb47 resolved the issue.
