### ISSUE TITLE
Unable to extract yt initial data (and how to solve)

### ISSUE THREAD

**Issue by an3k** [ytdl-org/youtube-dl#30295]
## Checklist

- [x] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
C:\Program Files\youtube-dl>"%PROGRAMFILES%\youtube-dl\youtube-dl.exe" --cookies "%PROGRAMFILES%\youtube-dl\youtube.com_cookies.txt" --download-archive "%USERPROFILE%\Downloads\My Music3\youtube-dl_archive.txt" --verbose -o "%USERPROFILE%/Downloads/My Music3/%%(album_artist)s/%%(album)s (%%(release_year)s)/%%(disc_number)s-%%(track_number)02d - %%(artist)s - %%(track)s -- [%%(id)s] %%(title)s.%%(ext)s" -i -f "bestaudio" -x --audio-format "m4a" --audio-quality 256K https://music.youtube.com/playlist?list=PL1CiZP5wdD9lrmwfHr9OqijLM3eD6086Q
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'C:\\Program Files\\youtube-dl\\youtube.com_cookies.txt', '--download-archive', 'C:\\Users\\Ben\\Downloads\\My Music3\\youtube-dl_archive.txt', '--verbose', '-o', 'C:\\Users\\Ben/Downloads/My Music3/%%(album_artist)s/%%(album)s (%%(release_year)s)/%%(disc_number)s-%%(track_number)02d - %%(artist)s - %%(track)s -- [%%(id)s] %%(title)s.%%(ext)s', '-i', '-f', 'bestaudio', '-x', '--audio-format', 'm4a', '--audio-quality', '256K', 'https://music.youtube.com/playlist?list=PL1CiZP5wdD9lrmwfHr9OqijLM3eD6086Q']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: avconv v11.7, avprobe v11.7, ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube:tab] PL1CiZP5wdD9lrmwfHr9OqijLM3eD6086Q: Downloading webpage
ERROR: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 2823, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 301, in _extract_yt_initial_data
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract yt initial data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

After updating to the most recent version I got this error, the older version I used before worked properly. The error message could be more descriptive.

The problem was: old cookies. After I created a new youtube.com_cookies.txt file the problem was gone.

**Comment by IfTrueReturnTrue** [comment]
So this issue can be closed right?

**Comment by an3k** [comment]
Turned into a feature request if you will so, because of the "could be better" error message.

**Comment by kikuyan** [comment]
Applications can't cover all users stupid mistakes.

**Comment by dirkf** [comment]
Probably what's happening here is that, when the old cookies are invalid, YT redirects to a login page that doesn't contain the actual video nor the `yt_initial_data` that is being sought. However the extractor doesn't check for a login page and only reports the lack of `yt_initial_data`.

**Comment by an3k** [comment]
The cookies aren't required to access the playlist, they're just there for a few "age restricted" videos but the whole playlist and all the videos are directly accessible.
I doubt ytdl is force-feeding youtube.com with the cookies so that youtube.com feels obligated to redirect ytdl ... but what do I know, maybe (probably) ytdl accesses youtube.com differently than "a browser".

**Comment by dirkf** [comment]
If you provide cookies they're always used. There could be a check on the page returned the first time cookies are sent.

You may have an improved cookie-free experience with [this patch](https://github.com/ytdl-org/youtube-dl/issues/30255#issuecomment-974822885). I got to listing item 122 of the playlist before I cancelled (including eg 72 that otherwise wanted authentication).
