### ISSUE TITLE
On audiomack downloading don’t start

### ISSUE THREAD

**Issue by freedom4JA** [ytdl-org/youtube-dl#30290]
I got the latest version on my Mint( 2021.04.26) and on audiomack.com I can’t initiate downloads.
I saw a similar post a few months ago but sadly no answers were available for me.

**Comment by 89z** [comment]
Please provide example URL

**Comment by kikuyan** [comment]
You say you saw a similar post, then please make a comment or question there. No need to open new issue report.
In any case, update youtube-dl to version 2021.06.06 first.

**Comment by freedom4JA** [comment]
> $ youtube-dl https://audiomack.com/joeboy/song/alcohol
[generic] alcohol: Requesting header
WARNING: Falling back on generic information extractor.
[generic] alcohol: Downloading webpage
[generic] alcohol: Extracting information
ERROR: Unsupported URL: https://audiomack.com/joeboy/song/alcohol

**Comment by dirkf** [comment]
Duplicate of #29800, for which an existing unmerged PR exists to fix the issue.

Or just use https://audiomack.com/song/joeboy/alcohol

**Comment by freedom4JA** [comment]
Thanks, very kind I was to stupid to see

**Comment by dirkf** [comment]
See [here](https://github.com/ytdl-org/youtube-dl/pull/29810#issuecomment-983088046).
