### ISSUE TITLE
Fails with www.newtube.app

### ISSUE THREAD

**Issue by mrwicks** [ytdl-org/youtube-dl#30296]
**EDIT: Importantly, the website supports downloading the files directly, so this is a very low priority if not entirely unnecessary.**

Probably something with the headers.  The link is just a random example, I've not gotten it to work with any link but I did make some progress with wget.

First:

```
$ youtube-dl --version
2021.06.06
```

```
$ youtube-dl -v  https://www.newtube.app/phiroc/4QMgQZl

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.newtube.app/phiroc/4QMgQZl']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-163-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[generic] 4QMgQZl: Requesting header
WARNING: Could not send HEAD request to https://www.newtube.app/phiroc/4QMgQZl: HTTP Error 403: Forbidden
[generic] 4QMgQZl: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```

Pretty certain this is a problem with headers because I did make a little progress screwing around with wget but just using plain wget, I get this error:

```
$ wget  https://www.newtube.app/phiroc/4QMgQZl
--2021-11-30 18:56:05--  https://www.newtube.app/phiroc/4QMgQZl
Resolving www.newtube.app (www.newtube.app)... 104.27.194.88, 104.27.195.88, 2606:4700:21::681b:c258, ...
Connecting to www.newtube.app (www.newtube.app)|104.27.194.88|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-11-30 18:56:06 ERROR 403: Forbidden.
```

If I mess around enough to make it IDENTICAL to my own browser, I can start to get data.

**Comment by 89z** [comment]
Is the site just laggy or something? I can get a video to play, even in a browser.

**Comment by mrwicks** [comment]
> Is the site just laggy or something? I cant get a video to play, even in a browser.

It DOES work, it's a pretty crappy site.  Truth be told, just tried 4 videos and they all hang.

**So another thing**, is that there is a download link in each (at least I think) video.  If you open up (I think) any one of the videos, there's a download link on the right.

So - maybe you don't want to bother to fix this.  I'm certain it's a header issue in which  the site is rejecting the request to prevent automated downloads.

If you want, I can screw around with wget and get you a procedure to get to that point of the DL link and then really, it's just using wget again.

**Comment by 89z** [comment]
This seems to work fine:

~~~
curl -O uploads1.newtube.app/uploads/phiroc/4QMgQZl.mp4
~~~

**Comment by 89z** [comment]
I am able to get a `200 OK` using the below program. That website is using TLS fingerprinting, so only extractors that have that support are going to work.

~~~go
package newtube

import (
   "github.com/89z/parse/crypto"
   "net/http"
)

const androidJA3 =
   "769,49195-49196-52393-49199-49200-52392-158-159-49161-49162-49171-49172-" +
   "51-57-156-157-47-53,65281-0-23-35-13-16-11-10,23,0"

func head(addr string) (*http.Response, error) {
   req, err := http.NewRequest("HEAD", addr, nil)
   if err != nil {
      return nil, err
   }
   req.Header.Set("User-Agent", "Mozilla")
   hello, err := crypto.ParseJA3(androidJA3)
   if err != nil {
      return nil, err
   }
   return crypto.NewTransport(hello.ClientHelloSpec).RoundTrip(req)
}
~~~

**Comment by mrwicks** [comment]
> That website is using TLS fingerprinting, so only extractors that have that support are going to work.

I have to confess, although I know TLS, I don't know what fingerprinting means in that context.

It's not a huge issue for me (or probably anybody) because the site itself supports direct downloads.  I was helping out a website owner to embed videos and that was the one that had me stumped.  While I did this, I added support to download the files as well.

Guess I ought to learn Go...

I'll update my original post to indicate this is very low priority since it supports direct downloads from the browser.  I just implemented a dozen sites, and I probably forgot that.  Nobody uses newtube.app on the site that I've seen anyhow, I was just being anal retentive.

**Comment by 89z** [comment]
> I have to confess, although I know TLS, I don't know what fingerprinting means in that context.

Even if you make the exact request as a browser, with regard to request headers, the request will fail. The reason is because, before you send any headers, your client (`wget` or whatever) sends a TLS handshake. Some servers (`android.clients.google.com` and CloudFlare) will look at the bytes of this handshake, and compare it to what a browser or phone might send. If it doesnt match, then request is rejected.

Its a really shitty thing to do, because most modern tools dont give you information about TLS handshake at all, so you really have to either write your own (what I did), or look pretty hard for an existing library.

**Comment by mrwicks** [comment]
> The reason is because, before you send any headers, your client (`wget` or whatever) sends a TLS handshake. Some servers (`android.clients.google.com` and CloudFlare) will look at the bytes of this handshake, and compare it to what a browser or phone might send. If it doesnt match, then request is rejected.

I can't be certain, but I bet wget supports this.  Curl as well.  I don't know how familiar you are with Linux, but the philosophy is to make a tool, and make it work well.  I would be surprised if it doesn't mimic a browser as needed.

> Its a really shitty thing to do, because most modern tools dont give you information about TLS handshake at all

Shitty things are what big tech does.  Remember when Google's motto was "do not evil"?  Then somehow a weird company created in 2015 called "Alphabet" (like in alphabet agency as in FBI, NSA, CIA, etc) somehow became their "parent" company...

Oh, and they dropped their "don't be evil" motto at the same time.  Google has more money than god, but they're the next Yahoo!  Remember Yahoo!?  They engaged in similar fxxkery.

This kind of BS is not new, back in the late 1990's, if I tried to connect to websites using Microsoft's IIS (crappy Apache implementation), any web-browser besides IE would fail to connect.  Just changing the browser to identify itself as "Internet Explorer" fixed it.  Microsoft used to bribe companies to use IIS - if was an attempt to make the HTTP (and later HTTPS) accessible ONLY if you had Windows.

I kind of miss those days because it was before every Tom Dick and Harry was on the web, and when companies pulled this crap, they were boycotted.  If Google, Facebook, and/or Twitter were pulling the BS they are now, they would have been abandoned by now but now we have sheep on the Internet that just put up with it.  Those companies will still descend into irrelevancy, but it's going to take YEARS not 3-4 weeks.

**Comment by 89z** [comment]
> I can't be certain, but I bet wget supports this. Curl as well.

I dont use Wget, but I am certain that current cURL **cannot** do this. You can control the version [1] and ciphers [2], but no control over TLS extensions.

1. https://curl.se/docs/manpage.html#--tlsv13
2. https://curl.se/docs/manpage.html#--ciphers

**Comment by mrwicks** [comment]
> I dont use Wget, but I am certain that current cURL **cannot** do this.

I can believe you're right, because I rarely use curl.  Wget is quite low level although it lacks a lot of more advanced features which don't matter to me.

Both programs can be used to archive an entire website, and I'm not surprised there's efforts to block them.  Both can be used to rapidly deplete bandwidth allotments by a malicious 3rd party.

It's probably not worth the time figuring out newtube.app.  I was just trying to be complete in a task, and really, I don't think anybody really cares how complete I am.  I'm 99% there anyhow.

Honestly, I don't think any of this ultimately matters, because the next stage of the Internet will be complete decentralization, with no Big Tech.  Your "website" will be a 5 watt box sitting next to your router, or a program running on your phone.  It's going to be something like IPFS or something.

I'm playing with qTox - it's a GREAT idea, and a terrible terrible implementation.  P2P E2E communication protocol - you can run SSHS or even a VPN over it and 0 setup on your router but it's not well implemented, but a very very good idea.  Connections are made via an ECC public key, so there's no need for 3rd party authentication either, because your ECC key IS your identification.  Architects were pretty good, but they didn't do a great job at implementation.

**Comment by dirkf** [comment]
You just need to set the UA (as in the Go program); yt-dl sends a confected UA that gets rejected by (probably) Cloudflare, who have broken the Web (in this case):
```
$ youtube-dl -v -F 'https://www.newtube.app/phiroc/4QMgQZl' --user-agent Mozilla
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.newtube.app/phiroc/4QMgQZl', '--user-agent', 'Mozilla']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[generic] 4QMgQZl: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 4QMgQZl: Downloading webpage
[generic] 4QMgQZl: Extracting information
[download] Downloading playlist: Earth spinning in two different directions 
[generic] playlist Earth spinning in two different directions : Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[info] Available formats for 4QMgQZl:
format code  extension  resolution note
0            mp4        unknown    
[download] Finished downloading playlist: Earth spinning in two different directions 
$
```

**Comment by mrwicks** [comment]
> You just need to set the UA (as in the Go program); yt-dl sends a confected UA that gets rejected by (probably) Cloudflare, who have broken the Web (in this case):
> 
> ```
> $ youtube-dl -v -F 'https://www.newtube.app/phiroc/4QMgQZl' --user-agent Mozilla
> ```

Hmm, I tried that:

```
$ sudo youtube-dl -U
[sudo] password for XXXX: 
youtube-dl is up-to-date (2021.06.06)

$ youtube-dl -v -F 'https://www.newtube.app/phiroc/4QMgQZl' --user-agent Mozilla
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.newtube.app/phiroc/4QMgQZl', u'--user-agent', u'Mozilla']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-163-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[generic] 4QMgQZl: Requesting header
WARNING: Could not send HEAD request to https://www.newtube.app/phiroc/4QMgQZl: HTTP Error 403: Forbidden
[generic] 4QMgQZl: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```
It's not a big deal.  This might be something for the developers to do if they have nothing else to do.  I'd make this low priority.

**Comment by 89z** [comment]
@dirkf command works for me, I suspect it is an issue of Python 3 vs Python 2. At any rate, his suggestion is not robust, as it assumes that whatever backend YouTube-DL happens to be using at the time, will have the correct TLS fingerprint, instead of ensuring that is the case. See here for another example of the same problem:

https://github.com/urllib3/urllib3/issues/2101

**Comment by dirkf** [comment]
Further tests:
* installed yt-dl (Py 3.5): works as-is
* dev directory run with `python3.9 -m youtube_dl ...`: works as-is
* dev directory run with `python2.7 -m youtube_dl ...`: fails, works with `--user-agent Mozilla`
* for good measure, yt-dlp run in dev directory with `python3.9 -m yt_dlp ...`: works as-is.

It almost seems as if Py3's `urllib` is making the difference.
