### ISSUE TITLE
get image

### ISSUE THREAD

**Issue by alicera** [ytdl-org/youtube-dl#30305]
How to get the youtube images？
like opencv get the frame

**Comment by Prasantacharya** [comment]
as in get the thumbnail, or get the frames of the video?
For the thumbnail, you could do something like `youtube-dl --write-thumbnail <video-link>`
For getting all the frames, after you download the video, I would use something like ffmpeg to extract the frames, the command would look something like: `ffmpeg -i <video-file> -ss <video-length> -vframes 1 out.png`

**Comment by alicera** [comment]
Do you have the sample code for python?

For example 
```
# Opens the Video file
cap= cv2.VideoCapture('C:/New/Videos/Play.mp4')
i=0
while(cap.isOpened()):
    ret, frame = cap.read()
    if ret == False:
        break
    cv2.imwrite('kang'+str(i)+'.jpg',frame)
    i+=1
 
cap.release()
cv2.destroyAllWindows() 
```

**Comment by kikuyan** [comment]
Not related to youtube-dl. Go find other forums.
