### ISSUE TITLE
Unable to Download One Specific Album on Bandcamp (other albums still work)

### ISSUE THREAD

**Issue by TPO100Cofficial** [ytdl-org/youtube-dl#30306]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
Possibly similar to #26727?
I can't download this very specific album,  Velocity​:​Design​:​Comfort  by Sweet Trip, but it does work in the browser and other albums work fine.

```
pbar~/Music/Sweet Trip - velocity : design : comfort.:$youtube-dl https://sweettrip.bandcamp.com/album/velocity-design-comfort
[Bandcamp:album] velocity-design-comfort: Downloading webpage
[download] Downloading playlist: Velocity:Design:Comfort.
[Bandcamp:album] playlist Velocity:Design:Comfort.: Collected 12 video ids (downloading 12 of them)
[download] Downloading video 1 of 12
[Bandcamp] tekka: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by 89z** [comment]
No, its not the same issue. The album youve linked, doesnt have any streaming media:

https://sweettrip.bandcamp.com/album/velocity-design-comfort

so it cant be downloaded, if it doesnt exist. If you have some way of getting the media without using YouTube-DL (like with a browser or something), then it might be possible.

**Comment by TPO100Cofficial** [comment]
oh, i'm dumb
yeah, it seems like the play button in browser is disabled, thus preventing streaming media
thank you! i'll just look for the album on a youtube playlist instead
