### ISSUE TITLE
Not getting 1080p...

### ISSUE THREAD

**Issue by PaulNevada** [ytdl-org/youtube-dl#30312]
## Checklist

- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hi! Why doesn't it get the available 1080p for the yt video?

**Comment by kikuyan** [comment]
Please provide the verbose log.

**Comment by PaulNevada** [comment]
Sorry, what exactly does this mean?

**Comment by dirkf** [comment]
Read the [Fine Manual](https://github.com/ytdl-org/youtube-dl#user-content-bugs). Once you understand the linked guidance, open a [Broken site support issue](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md), if your problem persists.

Also, close this issue.

**Comment by PaulNevada** [comment]
Ok, but what exactly log do I need to provide to you here? I'd love to...

**Comment by dirkf** [comment]
Does 'Ok' mean 'Never mind all those words one after the other that I can't be bothered to try understanding' nowadays? Hint: think of a video URL that you had hoped would be delivered as 1080p but apparently wasn't; then apply the [linked guidance] with that in mind. The `--list-formats` option of the yt-dl program will show what resolutions were found and the `--get-format` option will show which would be downloaded without actually downloading.

**Comment by PaulNevada** [comment]
Hi!
I've checked these two parameters. They do say there is the needed FullHD source. Started to download. A new question - how to try to speed up the process of getting the file to my PC?

**Comment by dirkf** [comment]
See issue #29326 and the linked pull request #30184.
