### ISSUE TITLE
Youtube-dl playlist and calcculating how big download will be

### ISSUE THREAD

**Issue by stillpointx** [ytdl-org/youtube-dl#30318]
## Checklist

- [x ] I'm asking a question
- x[ x] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Youtube-dl playlist and calculating how big download will be

I'm trying to download a playlist in 480p or 720p using youtube-dl but I would like to know how much space will be required before I do so.  How can this be done?

Example: 

    youtube-dl --newline -i -o "/tmp just to watch/%(upload_date)s_%(title)s_%(resolution)s.%(ext)s" -f 22 -v --ignore-config --hls-prefer-native --add-metadata "https://www.youtube.com/watch?v=b26ZBgspv7M&list=PLLYQF5WvJdJXE-aP7oF5ucXcCfHmub34A"

**Comment by dirkf** [comment]
This isn't as easy as it should be, since the information may be known but not available where it can be used:
* the `filesize` parameter for a media item is only set by the YT extractor when the site itself supplies a suitable value;
* yt-dl doesn't automatically set the `filesize_approx` parameter even when no `filesize` is set but `duration` and `tbr` are set;
* YT format 22 is one case where the site doesn't provide an explicit `filesize`;
* not all items in OP's example playlist have a format 22 anyway.

Apart from the above (!), you should be able to use a command line like this (Windows quoting to match OP's):
```
youtube-dl --get-filename -o "File size for %(id)s: %(filesize)s" -f 22 --ignore-config  "https://www.youtube.com/watch?v=b26ZBgspv7M&list=PLLYQF5WvJdJXE-aP7oF5ucXcCfHmub34A"
```
This is a best effort (note 125 = 1000/8 converts from kbit to byte):
```
$ youtube-dl --get-filename -o "File size for %(id)s: %(filesize)s = 125*%(duration)s*%(tbr)s" -f "22/best" --ignore-config  "https://www.youtube.com/watch?v=b26ZBgspv7M&list=PLLYQF5WvJdJXE-aP7oF5ucXcCfHmub34A"
File size for b26ZBgspv7M: NA = 125*1512*3.344
File size for nPr3qtZ5FVE: NA = 125*1994*190.884
File size for 8FCsS6s1Z0k: NA = 125*2871*188.892
File size for TZANoOWFX1M: 62402644 = 125*2054*243.013
File size for XA5eobevGv8: NA = 125*1186*795.686
File size for lDplUpPoCcI: NA = 125*1801*780.35
File size for a7TUIkn3qjY: NA = 125*2779*861.867
File size for HFPObieGamg: NA = 125*4141*523.075
File size for PiiDs8dzSXk: NA = 125*1119*399.974
File size for tth0p7nK18A: NA = 125*284*881.16
File size for Z_xj9ZTV8ak: NA = 125*3854*262.308
File size for Y_YHqM5nTHA: NA = 125*887*381.768
File size for BjV-fRCPgAM: NA = 125*563*600.009
$ 
```
In a POSIX environment with the _bc_ command-line calculator:
```
$ youtube-dl --get-filename -o "File size for %(id)s (%(format_id)s): %(filesize)s = 125*%(duration)s*%(tbr)s" -f "22/best" --ignore-config  "https://www.youtube.com/watch?v=b26ZBgspv7M&list=PLLYQF5WvJdJXE-aP7oF5ucXcCfHmub34A" | (IFS='='; while read -r a b; do echo "$a = $(echo "$b" | bc)"; done)
File size for b26ZBgspv7M (22): NA  = 632016.000
File size for nPr3qtZ5FVE (18): NA  = 47577837.000
File size for 8FCsS6s1Z0k (18): NA  = 67788616.500
File size for TZANoOWFX1M (18): 62402644  = 62393587.750
File size for XA5eobevGv8 (22): NA  = 117960449.500
File size for lDplUpPoCcI (22): NA  = 175676293.75
File size for a7TUIkn3qjY (22): NA  = 299391049.125
File size for HFPObieGamg (22): NA  = 270756696.875
File size for PiiDs8dzSXk (22): NA  = 55946363.250
File size for tth0p7nK18A (22): NA  = 31281180.00
File size for Z_xj9ZTV8ak (22): NA  = 126366879.000
File size for Y_YHqM5nTHA (22): NA  = 42328527.000
File size for BjV-fRCPgAM (22): NA  = 42225633.375
$
```

**Comment by stillpointx** [comment]
Thanks!!

Includes the individual filesizes with the sum at the end.

youtube-dl --get-filename -o "File size for %(id)s (%(format_id)s): %(filesize)s = 125*%(duration)s*%(tbr)s" -f "22/best" --ignore-config  "https://www.youtube.com/watch?v=b26ZBgspv7M&list=PLLYQF5WvJdJXE-aP7oF5ucXcCfHmub34A" | (
       sum=0
       while IFS='=' read -r a b; do
           echo "$a = $(echo "$b" | bc)"
           sum=$(echo "$sum + $b" | bc)
       done
       echo "The sum: $sum"
    )

Output:

File size for b26ZBgspv7M (22): NA  = 632016.000
File size for nPr3qtZ5FVE (18): NA  = 47577837.000
File size for 8FCsS6s1Z0k (18): NA  = 67788616.500
File size for TZANoOWFX1M (18): 62402644  = 62393587.750
File size for XA5eobevGv8 (22): NA  = 117960449.500
File size for lDplUpPoCcI (22): NA  = 175676293.75
File size for a7TUIkn3qjY (22): NA  = 299391049.125
File size for HFPObieGamg (22): NA  = 270756696.875
File size for PiiDs8dzSXk (22): NA  = 55946363.250
File size for tth0p7nK18A (22): NA  = 31281180.00
File size for Z_xj9ZTV8ak (22): NA  = 126366879.000
File size for Y_YHqM5nTHA (22): NA  = 42328527.000
File size for BjV-fRCPgAM (22): NA  = 42225633.375
The sum: 1340325129.125
