### ISSUE TITLE
can't install mpd file

### ISSUE THREAD

**Issue by nammminn2** [ytdl-org/youtube-dl#30310]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/64177573/144551232-1b19c7e4-f0c2-4c67-afd2-5293c29472c6.png">

**Comment by dirkf** [comment]
Probably the mpd specifies DRM-protected media that yt-dl doesn't download because you couldn't play it without magical powers, but **because you didn't follow the template** no-one will bother to test your problem URL.

Also, try using _ffmpeg_ directly instead.
