### ISSUE TITLE
Site Support Request movie.trueid.net

### ISSUE THREAD

**Issue by Kuju29** [ytdl-org/youtube-dl#30322]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://movie.trueid.net/th-en
- Single video: https://movie.trueid.net/th-th/series/owaP8qZ4Xd8R/yWR6ZMPpXyZW/OQJA9j5o799V/2mOQbOvKkGeg
- Playlist: https://movie.trueid.net/th-th/series/owaP8qZ4Xd8R

## Description

- To use it, you must be a member. It's entirely free.
- Is a website for Thai people. If there's anything you can add or suggest to me, I'd appreciate.

**Comment by 89z** [comment]
region restricted:

> This content is unavailable in this country (20007)

**Comment by Kuju29** [comment]
> region restricted:
> 
> > This content is unavailable in this country (20007)

Thanks!
