### ISSUE TITLE
Download archive max limits on very big channels

### ISSUE THREAD

**Issue by k0d3g3ar** [ytdl-org/youtube-dl#30326]
## Checklist

- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

I am attempting to download from a channel that has thousands of YT videos in it, but it seems to have hit some limit in the download-archive option for the max number of videos an individual channel can detect as downloaded - consequently nothing is now being detected by youtube-dl.

Does anyone know of any imposed limits on the max number of files per user/channel, etc. here and how to get past any limitations?

Thanks

**Comment by dirkf** [comment]
There doesn't seem to be a limit in the code. All the error defaults are favour

Maybe your archive is broken?

**Comment by rautamiekka** [comment]
Don't leave the verbose log out, this is a prime example why it's mandatory.
