### ISSUE TITLE
Spankbang HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by thichxxsp** [ytdl-org/youtube-dl#30327]
Now can not get spankbang video.
Spankbang HTTP Error 403: Forbidden

**Comment by dirkf** [comment]
Why would you not have **completed the [Broken site support](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=) template**?

**Comment by Ashish0804** [comment]
> Why would you not have **completed the [Broken site support](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=) template**?

coomers don't have brains or patience
