### ISSUE TITLE
File size output problem

### ISSUE THREAD

**Issue by yyms3275** [ytdl-org/youtube-dl#30323]
Below is the output of the result. Always the same 720p video file size is 0.

VideoInfo streamInfo = YoutubeDL.getInstance().getInfo("youtube url");

streamInfo(getExt) : mp4
streamInfo(getFormatNoteitem) : 720p
streamInfo(getWidth) : 1280
streamInfo(getHeight) : 720
streamInfo(getFilesize) : 0
streamInfo(getFormatId) : 22
streamInfo(getFormat) : 22 - 1280x720 (720p)
streamInfo(getAcodec) : mp4a.40.2
streamInfo(getVcodec) : avc1.64001F
streamInfo(getFps) : 30
streamInfo(getAbr) : 0
streamInfo(getTbr) : 346

**Comment by dirkf** [comment]
See also #30318.
