### ISSUE TITLE
Record at Constant Frame Rate

### ISSUE THREAD

**Issue by AlphaMerch** [ytdl-org/youtube-dl#30347]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

Is there any way to record at a constant frame rate, instead of variable? Files are in variable frame rates, making them impossible to work with in editing software. Transcoding videos to constant takes far too long, wondering if there's a way to just capture them at constant in the first place, even if it sacrifices quality or whatever. Thanks.

FYI - I'm using sparanoid's live-dl but I was told to raise the issue here as that program uses youtube-dl.

**Comment by kikuyan** [comment]
Find out what ffmpeg args are needed, then try
<code>--external-downloader ffmpeg --external-downloader-args "<i>args you found out</i>"</code>

**Comment by dirkf** [comment]
You might find that some part of the format description displayed using the `-F`/`--list-formats` option gives a clue as to whether the frame rate is constant, and if so you might be able to formulate a selection criterion that automatically picks the CFR videos on that site, or at least manually select one of those formats. This doesn't seem to be a useful approach for YT itself.

In the context of the live-dl tool, see [here](https://github.com/sparanoid/live-dl/issues/30#issuecomment-989850836).
