### ISSUE TITLE
adobe connect 

### ISSUE THREAD

**Issue by aliafshany** [ytdl-org/youtube-dl#30349]
## Checklist

- [x] I'm reporting a new site support request
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [ ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs
https://vc1.tabrizu.ac.ir/p2kiia97gbco/?session=breezbreezwxk52g67sny79dfx

WRITE DESCRIPTION HERE

youtube-dl -v https://vc1.tabrizu.ac.ir/p2kiia97gbco/\?session\=breezbreezwxk52g67sny79dfx
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vc1.tabrizu.ac.ir/p2kiia97gbco/?session=breezbreezwxk52g67sny79dfx']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.9 (CPython) - macOS-12.0.1-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.4.1, ffprobe 4.4.1
[debug] Proxy map: {}
[generic] ?session=breezbreezwxk52g67sny79dfx: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?session=breezbreezwxk52g67sny79dfx: Downloading webpage
[generic] ?session=breezbreezwxk52g67sny79dfx: Extracting information
ERROR: Unsupported URL: https://vc1.tabrizu.ac.ir/p2kiia97gbco/?session=breezbreezwxk52g67sny79dfx
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://vc1.tabrizu.ac.ir/p2kiia97gbco/?session=breezbreezwxk52g67sny79dfx

**Comment by dirkf** [comment]
Two problems here. First, yt-dl doesn't know that the page has an AdobeConnect item in it; second, even when it does, the extraction fails because the page format is not what the AdobeConnect extractor expects.

This patch enables yt-dl to find some rtmp content on the page:
```
--- old/youtube-dl/youtube_dl/extractor/adobeconnect.py
+++ new/youtube-dl/youtube_dl/extractor/adobeconnect.py
@@ -4,24 +4,36 @@
 from .common import InfoExtractor
 from ..compat import (
     compat_parse_qs,
-    compat_urlparse,
+    compat_urllib_parse_unquote,
+    compat_urllib_parse,
 )
 
 
 class AdobeConnectIE(InfoExtractor):
-    _VALID_URL = r'https?://\w+\.adobeconnect\.com/(?P<id>[\w-]+)'
+    # custom pattern for issue #30349
+    _VALID_URL = r'''(?x)
+            https?://
+            (?:
+                \w+\.adobeconnect\.com|
+                vc1.tabrizu.ac.ir
+            )
+            /(?P<id>[\w-]+)
+    '''
 
     def _real_extract(self, url):
         video_id = self._match_id(url)
         webpage = self._download_webpage(url, video_id)
         title = self._html_search_regex(r'<title>(.+?)</title>', webpage, 'title')
-        qs = compat_parse_qs(self._search_regex(r"swfUrl\s*=\s*'([^']+)'", webpage, 'swf url').split('?')[1])
+        qs = self._search_regex(r"(?:'{swfUrl}|{swfUrl}')([^']+)'".format(swfUrl=r'swfUrl\s*=\s*'), webpage, 'swf url')
+        if '%3A%2F%2F' in qs:
+            qs = compat_urllib_parse_unquote(qs)
+        qs = compat_parse_qs(qs.split('?')[1])
         is_live = qs.get('isLive', ['false'])[0] == 'true'
         formats = []
         for con_string in qs['conStrings'][0].split(','):
             formats.append({
                 'format_id': con_string.split('://')[0],
-                'app': compat_urlparse.quote('?' + con_string.split('?')[1] + 'flvplayerapp/' + qs['appInstance'][0]),
+                'app': compat_urllib_parse.quote('?' + con_string.split('?')[1] + 'flvplayerapp/' + qs['appInstance'][0]),
                 'ext': 'flv',
                 'play_path': 'mp4:' + qs['streamName'][0],
                 'rtmp_conn': 'S:' + qs['ticket'][0],
```
In a permanent fix, to avoid filling the `_VALID_URL` pattern with a list of sites, possible AdobeConnect content should be detected in the generic extractor as for many other embedded media types, but that is also an area that needs cleaning up.

**Comment by aliafshany** [comment]
i appreciate your time and and thorough reply
