### ISSUE TITLE
Cookies flag issues ( not reading my file )

### ISSUE THREAD

**Issue by CrAzyScreamx** [ytdl-org/youtube-dl#30355]
## Checklist

- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

I'm trying to download age-restricted videos ( this is the link for the vid if you want to check it yourselves: https://www.youtube.com/watch?v=Z-JZmgOCPrE )
So I have something really really odd, I'm trying to add my cookies file to youtube-dl options, however, it doesn't seem to work. It's like it's ignoring the cookies file.
Now, when I type it in the terminal like that it's working: 
![image](https://user-images.githubusercontent.com/34142944/145693920-194ca6f2-9f91-49bd-963e-f72874b7cc81.png)
But, when I code it and tell it to use the cookies file it doesn't seem to work ( still giving me the age-restriction error ):
My options: 
![image](https://user-images.githubusercontent.com/34142944/145693939-c2c2de7c-5eeb-4700-a187-7ca1f4b7a47e.png)
My path: 
![image](https://user-images.githubusercontent.com/34142944/145693950-a10920cb-101e-493f-86a0-ec15456e9e79.png)

This is the error I get from the debugger:
![image](https://user-images.githubusercontent.com/34142944/145694069-ac334c5d-b5d7-4125-816e-46a62e860439.png)

**Comment by CrAzyScreamx** [comment]
Found another post related to this: https://github.com/ytdl-org/youtube-dl/issues/30019

**Comment by dirkf** [comment]
The option is called `cookiefile` in the code (`YoutubeDL.py` l.212).

Feel free to paste **text** output rather than screenshots, especially not unreadable ones.

The referenced issue doesn't appear to be your problem.
