### ISSUE TITLE
Discovery ES not video found

### ISSUE THREAD

**Issue by cryptontgn** [ytdl-org/youtube-dl#30350]
The website is:

https://www.discoveryplus.com/es/video/asi-se-hace/temporada-15-pinceles-para-artistas

C:\video>youtube-dl -U -v "https://dplus-es-google-v2.prod-vod.h264.io/a7bc/c92c/33a5/b4c1ae4f-114e-434d-ad57-9640f54eada7/fmp4-playready-widevine/x-goog-token=Expires=1639154598&KeyName=prod-sign-url-key-eu&Signature=SEWOnoD50a7RF6ildB3aDkhF4X4/master.mpd"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-U', '-v', 'https://dplus-es-google-v2.prod-vod.h264.io/a7bc/c92c/33a5/b4c1ae4f-114e-434d-ad57-9640f54eada7/fmp4-playready-widevine/x-goog-token=Expires=1639154598&KeyName=prod-sign-url-key-eu&Signature=SEWOnoD50a7RF6ildB3aDkhF4X4/master.mpd']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-12-09-git-b9f4c1231f-full_build-www.gyan.dev
[debug] Proxy map: {}
youtube-dl is up-to-date (2021.06.06)
[generic] master: Requesting header
WARNING: Falling back on generic information extractor.
[generic] master: Downloading webpage
[generic] master: Extracting information
WARNING: [generic] Unknown MIME type image/jpeg in DASH manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\generic.py", line 2525, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by kikuyan** [comment]
DRM PlayReady protected.
