### ISSUE TITLE
Error Vimeo

### ISSUE THREAD

**Issue by GuzMan2019** [ytdl-org/youtube-dl#30358]
`[debug] System config: [ ]
[debug] User config: [ ]
[debug] Custom config: [ ]
[debug] Command-line args: [u'-F', u'http://vimeo.com/94379431', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.17 (CPython) - Linux-5.4.0-91-generic-i686-athlon-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 5, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 94379431: Downloading webpage
[vimeo] 94379431: Downloading JSON metadata
[vimeo] 94379431: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
`

**Comment by kikuyan** [comment]
Is that URL really alive? Can you play the video in the browser?
I only get this: Sorry, we couldn’t find that page

**Comment by GuzMan2019** [comment]
> Is that URL really alive? Can you play the video in the browser? I only get this: Sorry, we couldn’t find that page

Is that URL really alive? 

Yes

Can you play the video in the browser?

Yes

I only get this: Sorry, we couldn’t find that page

It was a video lesson. The course has now ended and the video has already been removed

**Comment by kikuyan** [comment]
> It was a video lesson. The course has now ended and the video has already been removed
 
Then close this for now.
If you encounter the same problem, open a new issue. And please use the proper issue template.
