### ISSUE TITLE
Unable to find video URL; please report this issue on https://yt-dl.org/b                                   ug . Make sure you are using the latest version; type  youtube-dl -U  to update.                                    Be sure to call youtube-dl with the --verbose flag and include its complete out

### ISSUE THREAD

**Issue by luxint66** [ytdl-org/youtube-dl#30353]
## Checklist

- [x] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by TickleMeElmo79-8** [comment]
i have a music bot on discord coded in py and yesterday it was working and now its not. could you help me fix this please
