### ISSUE TITLE
Youtube-dl dependency banned by Railway

### ISSUE THREAD

**Issue by The-Quaint** [ytdl-org/youtube-dl#30368]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have a telegram bot which uses youtube-dl to download videos. I host my bot in railway.app. But recently railway.app banned youtube-dl. so i am not able to use my bot. Is there any better alternatives to youtube-dl that hasn't been banned by railway.

**Comment by kikuyan** [comment]
Ask railway.

**Comment by MaurerKrisztian** [comment]
@The-Quaint I had the same problem, just upload the binary file and use that (or download at runtime).

**Comment by VoiceOfSoftware** [comment]
> @The-Quaint I had the same problem, just upload the binary file and use that (or download at runtime).

@MaurerKrisztian how do you upload the binary file? I'm not sure which binary you mean. I'm hosting on railway.app, and got the same 'banned' error message
