### ISSUE TITLE
Error in download https://www.youtube.com/watch?v=Nis8dwTUc8M

### ISSUE THREAD

**Issue by rogeriotadim** [ytdl-org/youtube-dl#30388]
[Nis8dwTUc8M.log](https://github.com/ytdl-org/youtube-dl/files/7727975/Nis8dwTUc8M.log)

**Comment by dirkf** [comment]
Duplicate of [#30363](https://github.com/ytdl-org/youtube-dl/issues/30363#issuecomment-994731986), with fix.

Also, **follow the instructions for posting a [Broken site support issue](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=)** which would have led you to review the existing issue and not create a new one. As it is, @rogeriotadim, kindly close this issue.

**Comment by Jmackay82** [comment]
> Duplicate of [#30363](https://github.com/ytdl-org/youtube-dl/issues/30363#issuecomment-994731986), with fix.
> 
> Also, **follow the instructions for posting a [Broken site support issue](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=)** which would have led you to review the existing issue and not create a new one. As it is, @rogeriotadim, kindly close this issue.

There is no Windows Fix, when can we expect a windows fix to this issue please?

**Comment by Julien-Peeters** [comment]
> Duplicate of [#30363](https://github.com/ytdl-org/youtube-dl/issues/30363#issuecomment-994731986), with fix.
> 
> Also, **follow the instructions for posting a [Broken site support issue](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=)** which would have led you to review the existing issue and not create a new one. As it is, @rogeriotadim, kindly close this issue.

Unfortunately, this fix doesn't work on windows, I've checked all the issue threads and nothing worked so far... I've been getting the problem out of the blue and my custom music bot has stopped working ever since.

I know you've already had to deal with this, and I'm not here to put more pressure on you for something you didn't cause.

**Comment by dirkf** [comment]
Please [review the master issue](https://github.com/ytdl-org/youtube-dl/issues/30363#issuecomment-994731986) instead of trolling here.

**Comment by rogeriotadim** [comment]
duplicated :(
