### ISSUE TITLE
Issue with Windows version YouTube-DL.exe (Cannot see windows Fix)

### ISSUE THREAD

**Issue by Jmackay82** [ytdl-org/youtube-dl#30389]
## Checklist

- [ x ] I'm reporting a broken site support
- [ x ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ x ] I've checked that all provided URLs are alive and playable in a browser
- [ x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
c:\SYS586>youtube-dl "ytsearch10:Elton John Dua Lipa" --get-id --get-title --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['ytsearch10:Elton John Dua Lipa', '--get-id', '--get-title', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-04-26-1128aa8, ffprobe git-2020-04-26-1128aa8
[debug] Proxy map: {}
ERROR: query "Elton John Dua Lipa": Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 871, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 871, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 2860, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\youtube.py", line 2684, in _get_n_results
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 864, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 848, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 875, in _parse_json
youtube_dl.utils.ExtractorError: query "Elton John Dua Lipa": Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hi, please see issue on windows, there is a fix for other platforms but I cannot see any fix for windows.

**Comment by dirkf** [comment]
The same code runs on all platforms. The difficulty is packaging because the Windows version includes a version of Python (that's why it's ~8MB instead of <2MB) and special tools are used to make it. Having said that, if you have Python installed on Windows, it should be possible to use _pip_ as suggested by posters in #30363 just as with [any other Python installation](https://xkcd.com/1987/).

Fortunately you can upgrade to the new 2021.12.21 version.

**Comment by 89z** [comment]
I am on Windows, and I can confirm that one of these should work as expected:

~~~
pip install youtube-dl
pip install git+https://github.com/ytdl-org/youtube-dl
~~~

Also if youre using embedded Python, see my answer here:

https://stackoverflow.com/a/65226460

**Comment by lvqcl** [comment]
> [ x ] I've verified that I'm running youtube-dl version 2021.06.06
> ...
> [debug] youtube-dl version 2018.09.26

lol

**Comment by Jmackay82** [comment]
> The same code runs on all platforms. The difficulty is packaging because the Windows version includes a version of Python (that's why it's ~8MB instead of <2MB) and special tools are used to make it. Having said that, if you have Python installed on Windows, it should be possible to use _pip_ as suggested by posters in #30363 just as with [any other Python installation](https://xkcd.com/1987/).
> 
> Fortunately you can upgrade to the new 2021.12.21 version.

Thank you, I will install python and attempt this fix, idiot question I know, but how do you run the youtube-dl from python in windows to actually use it?

**Comment by dirkf** [comment]
Your options in order of simplicity:
* install [yt-dlp](https://github.com/yt-dlp/yt-dlp/releases) instead if your Windows version supports it;
* install the new yt-dl version 2021.12.17 (why did I put 21?), and put up with the throttled YT download rate;
* install Python; download https://github.com/ytdl-org/youtube-dl/archive/905d1d281ddfa5d183fc445010d350cefc6a58ec.zip; expand it and in a command-line (cmd/'DOS', PowerShell, Windows Terminal) session, change directory into the expanded archive (the directory that contains `README.md`) and run `pip install .`; make a file `youtube-dl.bat` containing the line `@python -m youtube_dl %*` (replace `python` by whatever you have to type at the command line to run Python); put that file in your executable search path (see also [the not entirely helpful Python FAQ item](https://docs.python.org/3/faq/windows.html)).

**Comment by pukkandan** [comment]
> install Python; download 905d1d281ddfa5d183fc445010d350cefc6a58ec.zip; expand it and in a command-line (cmd/'DOS', PowerShell, Windows Terminal) session, change directory into the expanded archive (the directory that contains README.md) and run pip install .; make a file youtube-dl.bat containing the line @python -m youtube_dl %* (replace python by whatever you have to type at the command line to run Python); put that file in your executable search path (see also the not entirely helpful Python FAQ item).

Once python is installed, you can also just directly run `pip install https://github.com/ytdl-org/youtube-dl/archive/905d1d281ddfa5d183fc445010d350cefc6a58ec.zip`

**Comment by dirkf** [comment]
OK, does that install some `youtube-dl` alias that runs the installed module? Great if so. As you imagine, I don't have a Windows Python to check with.

**Comment by pukkandan** [comment]
Yes
```
➤ where youtube-dl
D:\Programs\Terminal\youtube-dl.exe

➤ pip install https://github.com/ytdl-org/youtube-dl/archive/905d1d281ddfa5d183fc445010d350cefc6a58ec.zip
Collecting https://github.com/ytdl-org/youtube-dl/archive/905d1d281ddfa5d183fc445010d350cefc6a58ec.zip
  Downloading https://github.com/ytdl-org/youtube-dl/archive/905d1d281ddfa5d183fc445010d350cefc6a58ec.zip
     / 2.2 MB 544 kB/s
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: youtube-dl
  Building wheel for youtube-dl (setup.py) ... done
  Created wheel for youtube-dl: filename=youtube_dl-2021.12.17-py2.py3-none-any.whl size=1840680 sha256=6a43ca78aa3d0b4916bb627125fd4bbe24e87d9747ee98bda826b56c4dbbcaad
  Stored in directory: C:\Users\Anandakrishnan\AppData\Local\Temp\pip-ephem-wheel-cache-9xbno022\wheels\9e\d1\8a\0fcad388f4d0c999cc72cb401f70970903996ec883ad9d2d07
Successfully built youtube-dl
Installing collected packages: youtube-dl
Successfully installed youtube-dl-2021.12.17

➤ where youtube-dl
D:\Programs\Portable\Python\Python10\Scripts\youtube-dl.exe
D:\Programs\Terminal\youtube-dl.exe
```

ofc, assuming "add to path" was ticked when installing python

**Comment by rautamiekka** [comment]
If you didn't check the 'Add to path' option, you can add it manually: https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

No need to install yt-dl (or yt-dlp) using the Git master, it's auto-published on PyPi for that purpose anyway. Unless there's a commit you need right away instead of waiting for a release.

**Comment by dirkf** [comment]
The [third option](https://github.com/ytdl-org/youtube-dl/issues/30389#issuecomment-997979764) specifically requires installing a version that isn't a release.
