### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last):

### ISSUE THREAD

**Issue by sebacho9** [ytdl-org/youtube-dl#30392]
## Checklist

Confirmed I am running version 2021.06.06 on Windows 11

- [ X ] I'm reporting a new site support request
- [ X ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ X ] I've checked that all provided URLs are alive and playable in a browser
- [ X ] I've checked that none of provided URLs violate any copyrights
- [ X ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

Playlist: https://www.youtube.com/watch?v=-egpEoxpIaE&list=PL-UWPlRIl68qybTmllksOPllIq_GT71i6
Single: https://www.youtube.com/watch?v=2QWQVm9J5DM

## Description

I am getting the following error when trying to download any video:

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1349, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1331, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\jsinterp.py", line 245, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
cd : Cannot process argument because the value of argument "path" is null. Change the value of argument "path" to a
non-null value.
At C:\Users\sebas\Documents\Developer\YouTubeDownloader\YouTubeDownloaderScript.ps1:71 char:13
+             cd $folderName
+             ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], PSArgumentNullException
    + FullyQualifiedErrorId : ArgumentNull,Microsoft.PowerShell.Commands.SetLocationCommand

**Comment by racalfaro** [comment]
I am having the exact same error since a few days ago

**Comment by kikuyan** [comment]
This problem has been fixed in version 2021.12.17.
Please close this.

**Comment by racalfaro** [comment]
I just tested it and it works. Thank you so much. I don't seem to have an option to close the issue. But it is solved.
