### ISSUE TITLE
--get-playlist: consider add new flag to get more information about the playlist: duration, count, visibility, etc.

### ISSUE THREAD

**Issue by Dentrax** [ytdl-org/youtube-dl#30396]
## Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

Similar to `--yes-playlist` but for getting information about the specified playlist:

```
$ youtube-dl --get-playlist 'https://www.youtube.com/playlist?list=RDCMUCCezIgC97PvUuR4_gbFUs5g'
```

It would be great to get detail about the playlist. The following above command should output such information:

* total duration of the playlist
* total size of videos
* download ETA
* total video count of the playlist
* create date of playlist
* update date of the playlist
* latest added video
* visibility: public, private, etc.
* which videos a liked/disliked
* which videos I have watched
* ...

What do you think?

**Comment by dirkf** [comment]
You can use the `-J` option and learn about the _[jq](https://stedolan.github.io/jq/)_ program to achieve this result.

**Comment by Dentrax** [comment]
Thanks. Actually, the `-J` flag is not what I am looking for. It prints JSON output format for entire playlist. Which is kind of hard workaround to achieve this. You probably could write tons of lines of queries to achieve this, which is not so good from the UX perspective.

It would be great to collect all data and evaluate them to output a beatified summary for the given playlist. This idea would help us about getting great information just before downloading an entire playlist.

**Comment by dirkf** [comment]
Maybe try `-J --flat-playlist` to avoid all the nested details (though the whole data structure that's dumped with plain `-J` is always constructed internally by yt-dl).

Your example playlist is "unviewable" so I used another one.

```
$ js-beautify --help | head -8
jsbeautifier.py@1.13.5

Javascript beautifier (https://beautifier.io/)

Usage: jsbeautifier.py [options] <infile>

    <infile> can be "-", which means stdin.

$ youtube-dl --flat-playlist -J PL8BCB4981DD1A0108 | js-beautify
{
    "_type": "playlist",
    "entries": [{
        "_type": "url",
        "duration": 5837.0,
        "ie_key": "Youtube",
        "id": "Igl8hE3Eac0",
        "title": "Lecture 1 | New Revolutions in Particle Physics: Standard Model",
        "uploader": "Stanford",
        "view_count": null,
        "description": null,
        "url": "Igl8hE3Eac0"
    }, {
        "_type": "url",
        "duration": 5909.0,
        "ie_key": "Youtube",
        "id": "yy989li6xgY",
        "title": "Lecture 2 | New Revolutions in Particle Physics: Standard Model",
        "uploader": "Stanford",
        "view_count": null,
        "description": null,
        "url": "yy989li6xgY"
    }, {
        "_type": "url",
        "duration": 6092.0,
        "ie_key": "Youtube",
        "id": "n88Qe-aAAYE",
        "title": "Lecture 4 | New Revolutions in Particle Physics: Standard Model",
        "uploader": "Stanford",
        "view_count": null,
        "description": null,
        "url": "n88Qe-aAAYE"
    }, {
        "_type": "url",
        "duration": 5682.0,
        "ie_key": "Youtube",
        "id": "3g6RtyGjX3o",
        "title": "Lecture 5 | New Revolutions in Particle Physics: Standard Model",
        "uploader": "Stanford",
        "view_count": null,
        "description": null,
        "url": "3g6RtyGjX3o"
    }, {
        "_type": "url",
        "duration": 5558.0,
        "ie_key": "Youtube",
        "id": "5rytN74EOi0",
        "title": "Lecture 6 | New Revolutions in Particle Physics: Standard Model",
        "uploader": "Stanford",
        "view_count": null,
        "description": null,
        "url": "5rytN74EOi0"
    }, {
        "_type": "url",
        "duration": 6488.0,
        "ie_key": "Youtube",
        "id": "7cKvhkFhXDk",
        "title": "Lecture 7 | New Revolutions in Particle Physics: Standard Model",
        "uploader": "Stanford",
        "view_count": null,
        "description": null,
        "url": "7cKvhkFhXDk"
    }, {
        "_type": "url",
        "duration": 5040.0,
        "ie_key": "Youtube",
        "id": "fw4K3sgza04",
        "title": "Lecture 8 | New Revolutions in Particle Physics: Standard Model",
        "uploader": "Stanford",
        "view_count": null,
        "description": null,
        "url": "fw4K3sgza04"
    }, {
        "_type": "url",
        "duration": 5734.0,
        "ie_key": "Youtube",
        "id": "qzGY-BrCUgA",
        "title": "Lecture 9 | New Revolutions in Particle Physics: Standard Model",
        "uploader": "Stanford",
        "view_count": null,
        "description": null,
        "url": "qzGY-BrCUgA"
    }, {
        "_type": "url",
        "duration": 5900.0,
        "ie_key": "Youtube",
        "id": "QD8SEcoFyAw",
        "title": "Lecture 10 | New Revolutions in Particle Physics: Standard Model",
        "uploader": "Stanford",
        "view_count": null,
        "description": null,
        "url": "QD8SEcoFyAw"
    }],
    "webpage_url_basename": "playlist",
    "id": "PL8BCB4981DD1A0108",
    "uploader_id": "UC-EnprmCZ3OXyAoG7vjVNCA",
    "uploader_url": "https://www.youtube.com/c/stanford",
    "uploader": "Stanford",
    "extractor_key": "YoutubeTab",
    "webpage_url": "https://www.youtube.com/playlist?list=PL8BCB4981DD1A0108",
    "title": "Lecture Collection | Particle Physics: Standard Model",
    "extractor": "youtube:tab"
$
```
The data above is what's available for the playlist itself without analysing all the playlist items. By removing `--flat-playlist` you get the per-item metadata but it's still not necessarily possible whether by internal coding changes or by writing _jq_ scripts to collect some of the data you would like. For instance, the size of an item depends on the selected format and even the approximate size of an item may not be available for some formats (here I am just talking about YT itself but other extractors probably have similar issues).

**Comment by AndreWillomitzer** [comment]
Hi there, new person stopping by the repo hope that's okay! I am not sure about Python but I'm pretty familiar with CLI tools using Node.  I only had a peek I hope you don't mind haha.

I wonder if a good solution for your troubles would be to use some kind of CLI text coloring tool for now just so that it's easy to read the output from -J --flat-playlist.  @dirkf 

What is an example of the data you would want to amalgamate together? Would it be like "We have X number of videos by Stanford in this playlist"?

All the best,

Andre :)
