### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last):

### ISSUE THREAD

**Issue by erogluegemen** [ytdl-org/youtube-dl#30390]

**Comment by erogluegemen** [comment]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\...\youtube_dl\extractor\youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "C:\Users\...\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\...\youtube_dl\extractor\youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Users\...\youtube_dl\jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by kikuyan** [comment]
This problem has been fixed in version 2021.12.17.
Please close this.
