### ISSUE TITLE
youtube_dl.utils.ExtractorError: Youku server reported error -3007: 观看此节目，请先登录！

### ISSUE THREAD

**Issue by Forstok93** [ytdl-org/youtube-dl#30403]
PS A:\Новая папка (3)> youtube-dl -f "bestvideo[height<=720]" -v "https://v.youku.com/v_show/id_XNTIwMjAxMDcyNA==.html?spm=a2hbt.13141534.1_2.3&s=dbbf54bdee9c4c5bbbd7"
>>
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo[height<=720]', '-v', 'https://v.youku.com/v_show/id_XNTIwMjAxMDcyNA==.html?spm=a2hbt.13141534.1_2.3&s=dbbf54bdee9c4c5bbbd7']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg n4.4.1-2-gcc33e73618-20211207, ffprobe n4.4.1-2-gcc33e73618-20211207
[debug] Proxy map: {}
[youku] XNTIwMjAxMDcyNA: Retrieving cna info
[youku] XNTIwMjAxMDcyNA: Downloading JSON metadata
ERROR: Youku server reported error -3007: 观看此节目，请先登录！; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\forst\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\forst\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\forst\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\users\forst\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\youku.py", line 189, in _real_extract
    raise ExtractorError(msg)
youtube_dl.utils.ExtractorError: Youku server reported error -3007: 观看此节目，请先登录！; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Although you didn't complete the Broken site support template which would have clarified the problem that you are reporting, I notice that G thinks the Chinese characters `观看此节目，请先登录` spell "Watch this program, please log in first." Presumably, you should try passing cookies from a logged -in browser session to yt-dl, as described in the manual.
