### ISSUE TITLE
Twitch bulk download all vods from channel

### ISSUE THREAD

**Issue by hasnogaems** [ytdl-org/youtube-dl#30410]
Currently I put in vods urls 1 by 1 by hand. It is tedious. Is there a way, a command to just download all available with no duplicates like with youtube playlists?

**Comment by kikuyan** [comment]
Twitch extractor seems to support playlists or collections. See what types of URLs are valid in the [code](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/twitch.py). `_VALID_URL` and `_TESTS`

**Comment by hasnogaems** [comment]
Im having trouble compreheding this:
` _VALID_URL = r'''(?x)
                    https?://
                        (?:
                            (?:(?:www|go|m)\.)?twitch\.tv/(?:[^/]+/v(?:ideo)?|videos)/|
                            player\.twitch\.tv/\?.*?\bvideo=v?
                        )
                        (?P<id>\d+)
                    '''`

There is a way to just tell it to download all available vods from the channel?
