### ISSUE TITLE
Capolavori dell'ingegneria romana puntate 2-6

### ISSUE THREAD

**Issue by graizzaro** [ytdl-org/youtube-dl#30419]
I downloaded episode 1 with this URL
https://www.mediasetplay.mediaset.it/video/capolavoridellingegneriaromana/ep-1-i-semi-dellimpero-i-parte_F311095701000104
but was'nt able to download episodes 2-6. Here are the URLs:
https://www.mediasetplay.mediaset.it/video/capolavoridellingegneriaromana/ep-2-le-citta-i-semi-dellimpero-ii-parte_F311095701000204
https://www.mediasetplay.mediaset.it/video/capolavoridellingegneriaromana/ep-3-gli-acquedotti-la-fonte-della-vita-i-parte_F311095701000304
https://www.mediasetplay.mediaset.it/video/capolavoridellingegneriaromana/ep-4-gli-acquedotti-la-fonte-della-vita-ii-parte_F311095701000404
https://www.mediasetplay.mediaset.it/video/capolavoridellingegneriaromana/ep-5-le-miniere-le-risorse-nascoste_F311095701000504
https://www.mediasetplay.mediaset.it/video/capolavoridellingegneriaromana/ep-6-le-strade-la-rete-dellimpero_F311095701000604

For example this is youtube-dl --verbose output:

youtube-dl --verbose https://www.mediasetplay.mediaset.it/video/capolavoridellingegneriaromana/ep-2-le-citta-i-semi-dellimpero-ii-parte_F311095701000204
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.mediasetplay.mediaset.it/video/capolavoridellingegneriaromana/ep-2-le-citta-i-semi-dellimpero-ii-parte_F311095701000204']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[Mediaset] F311095701000204: Downloading JSON metadata
[Mediaset] F311095701000204: Downloading MPEG4 SD SMIL data
[Mediaset] F311095701000204: Downloading MPEG-DASH SD SMIL data
[Mediaset] F311095701000204: Downloading M3U SD SMIL data
[Mediaset] F311095701000204: Downloading MPEG4 HD SMIL data
[Mediaset] F311095701000204: Downloading MPEG-DASH HD SMIL data
[Mediaset] F311095701000204: Downloading M3U HD SMIL data
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\mediaset.py", line 158, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Surely this is the same issue as #30411 and the original issues of which that was a duplicate? (ie, DRM => no formats)
