### ISSUE TITLE
I'm encountering the same problem. If downloading with `--all-formats`, formats `0` (360p), `2` (720p) and `3` (1080p) result in the same 360p file, whereas format `h3` yields a 540p file. This is with both direct video URLs as well as playlist URLs. I'm running `youtube-dl` with `--cookies` and a `cookies.txt` with an active Youku subscription.

### ISSUE THREAD

**Issue by jhriyaz** [ytdl-org/youtube-dl#30424]
I'm encountering the same problem. If downloading with `--all-formats`, formats `0` (360p), `2` (720p) and `3` (1080p) result in the same 360p file, whereas format `h3` yields a 540p file. This is with both direct video URLs as well as playlist URLs. I'm running `youtube-dl` with `--cookies` and a `cookies.txt` with an active Youku subscription.

_Originally posted by @JenniferPadilla in https://github.com/ytdl-org/youtube-dl/issues/28471#issuecomment-821875501_

**Comment by jhriyaz** [comment]
![Capture](https://user-images.githubusercontent.com/71035971/147369598-57b56e31-d110-446f-b148-402b5c995758.PNG)
i have active suscription there.

**Comment by 89z** [comment]
Why do you think its acceptable to post an obvious duplicate issue?
