### ISSUE TITLE
Will DRM encryption be overcome?

### ISSUE THREAD

**Issue by Mr-Personality** [ytdl-org/youtube-dl#30425]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I wanted to download from www.channel5.com but apparently it's not supported as it's DRM encrypted.

How likely is it that DRM encryption will be overcome?

And why is encryption is even used. These are shows that British viewers have paid a license to watch, so we should be entitled to download it. The BBC doesn't use encryption and we can freely download their shows. What's the difference?

**Comment by kikuyan** [comment]
If you want to ask about DRM, go [Video Streaming Downloading](https://forum.videohelp.com/forums/48-Video-Streaming-Downloading), and please close this.

**Comment by 89z** [comment]
region restriction:

> We're sorry, you must be located in the UK to view this content.

**Comment by Mr-Personality** [comment]
> region restriction:
> 
> > We're sorry, you must be located in the UK to view this content.

Yes, I am British. These TV shows are free to watch here in the UK.

> If you want to ask about DRM, go [Video Streaming Downloading](https://forum.videohelp.com/forums/48-Video-Streaming-Downloading), and please close this.

OK, I won't ask about DRM here.
