### ISSUE TITLE
Sproutvideo giving Error 403

### ISSUE THREAD

**Issue by NewKidOnTheBlok** [ytdl-org/youtube-dl#30422]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --cookies cookies.txt -v https://hls2.videos.sproutvideo.com/de696a4751b91aad259a8509731c6c07/3d08047f6b9e09eb163a7416e9e8297b/video/index.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9obHMyLnZpZGVvcy5zcHJvdXR2aWRlby5jb20vZGU2OTZhNDc1MWI5MWFhZDI1OWE4NTA5NzMxYzZjMDcvM2QwODA0N2Y2YjllMDllYjE2M2E3NDE2ZTllODI5N2IvKi5tM3U4P3Nlc3Npb25JRD03M2I5NzcwNC01YzI5LTQ0ZDUtYmJhNy0zNDk0YzcyZDdkOGQiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDAzNzYxMjZ9fX1dfQ__&Signature=WhggDSjxbTrQIk52iKVcSRDg~sRdgSXm1l3Kpgf469g6zKxLi258dUCXH7XmPwwHXdhFx4SrbmClpYWaN3j1tIOr-vTW6fdYruVIP2mj9MSsfl474lsDO5CX-NSYI-oEm~7Gq0yrmntiC~J7g2HjbLrOnk2~HdpGd8xsJ7gHR5pD~rE4ShMyuJo0qILCyk5pfuAPIGwQCp4i-5dqD~LHawZiaEkgiU-ehGn0yFhWplihWc47BATC3TOHe7xytuira2QN15BtAmF~l3lz4OlCjh5aAZ23QwvyV-8NG0-Q6EKzhLvjXC2BuYR3SfWclVbHb3~uH4HK2SWirvyE3Nc66Q__&Key-Pair-Id=APKAIB5DGCGAQJ4GGIUQ&sessionID=73b97704-5c29-44d5-bba7-3494c72d7d8d
[1] 17337
[2] 17338
[3] 17339
[2]-  Done                    Signature=WhggDSjxbTrQIk52iKVcSRDg~sRdgSXm1l3Kpgf469g6zKxLi258dUCXH7XmPwwHXdhFx4SrbmClpYWaN3j1tIOr-vTW6fdYruVIP2mj9MSsfl474lsDO5CX-NSYI-oEm~7Gq0yrmntiC~J7g2HjbLrOnk2~HdpGd8xsJ7gHR5pD~rE4ShMyuJo0qILCyk5pfuAPIGwQCp4i-5dqD~LHawZiaEkgiU-ehGn0yFhWplihWc47BATC3TOHe7xytuira2QN15BtAmF~l3lz4OlCjh5aAZ23QwvyV-8NG0-Q6EKzhLvjXC2BuYR3SfWclVbHb3~uH4HK2SWirvyE3Nc66Q__
User's-MacBook-Air:~ User1$ -bash: Key-Pair-Id=APKAIB5DGCGAQJ4GGIUQ: command not found
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', '-v', 'https://hls2.videos.sproutvideo.com/de696a4751b91aad259a8509731c6c07/3d08047f6b9e09eb163a7416e9e8297b/video/index.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9obHMyLnZpZGVvcy5zcHJvdXR2aWRlby5jb20vZGU2OTZhNDc1MWI5MWFhZDI1OWE4NTA5NzMxYzZjMDcvM2QwODA0N2Y2YjllMDllYjE2M2E3NDE2ZTllODI5N2IvKi5tM3U4P3Nlc3Npb25JRD03M2I5NzcwNC01YzI5LTQ0ZDUtYmJhNy0zNDk0YzcyZDdkOGQiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDAzNzYxMjZ9fX1dfQ__']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.0 (CPython) - Darwin-21.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] index: Requesting header
WARNING: Could not send HEAD request to https://hls2.videos.sproutvideo.com/de696a4751b91aad259a8509731c6c07/3d08047f6b9e09eb163a7416e9e8297b/video/index.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9obHMyLnZpZGVvcy5zcHJvdXR2aWRlby5jb20vZGU2OTZhNDc1MWI5MWFhZDI1OWE4NTA5NzMxYzZjMDcvM2QwODA0N2Y2YjllMDllYjE2M2E3NDE2ZTllODI5N2IvKi5tM3U4P3Nlc3Npb25JRD03M2I5NzcwNC01YzI5LTQ0ZDUtYmJhNy0zNDk0YzcyZDdkOGQiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDAzNzYxMjZ9fX1dfQ__: HTTP Error 403: Forbidden
[generic] index: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/Users/User1/anaconda/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Users/User1/anaconda/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Users/User1/anaconda/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Users/User1/anaconda/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/User1/anaconda/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/Users/User1/anaconda/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Users/User1/anaconda/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description

Getting 403 error with Sproutvideo .m3u8 file. Tried cookies, didn't work. This is URL link: https://videos.sproutvideo.com/embed/709dd7b81713e4c0f9/7ff4d74371486b9d?referrer=https%3A%2F%2Fwww.patreon.com%2F

**Comment by kikuyan** [comment]
Read this: [Video URL contains an ampersand and I'm getting some strange output [1] 2839 or 'v' is not recognized as an internal or external command](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)

**Comment by NewKidOnTheBlok** [comment]
Tried both the backlash:

`youtube-dl --cookies cookies.txt https://hls2.videos.sproutvideo.com/de696a4751b91aad259a8509731c6c07/3d08047f6b9e09eb163a7416e9e8297b/video/index.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9obHMyLnZpZGVvcy5zcHJvdXR2aWRlby5jb20vZGU2OTZhNDc1MWI5MWFhZDI1OWE4NTA5NzMxYzZjMDcvM2QwODA0N2Y2YjllMDllYjE2M2E3NDE2ZTllODI5N2IvKi5tM3U4P3Nlc3Npb25JRD0xNGQzYmExZS1hYzhlLTQyNWMtOWZiZi03NmJlZmRkZjJjNmYiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDAzODI2NzR9fX1dfQ__\&Signature=Sz5v-Yx2m-eOTQhrf58NmcD4qN9XBC7DiFF2-PyML4GcoXubzUuC7WDWFO9ciQ35em7bQsOfHDBX6ct34v1IABJqCNQ2sXb5Jigc3fgdCtAX-qi3iLqHGka2cQxxTcbj1BsFiEIektY6EoilKFHavqTRnbak1Ea6k7~H08bDalQP3uXwquS9A2mSnnEZioDtW1KIv2qPIs5ZUL9El2gaT4YYXLTD8nPj4TnLmY7eJCYMXmSJzmYJtH6HSEaqtfu3ry~9pjCxxupetVII8ozLal~z715XIa3Aa6tRWkOueC2RU~olqQNAwpQcf6UKU1E7m8I24WipQFgCfTmvJYKFwQ__\&Key-Pair-Id=APKAIB5DGCGAQJ4GGIUQ\&sessionID=14d3ba1e-ac8e-425c-9fbf-76befddf2c6f
`

And single quote:

`youtube-dl --cookies cookies.txt 'https://hls2.videos.sproutvideo.com/de696a4751b91aad259a8509731c6c07/3d08047f6b9e09eb163a7416e9e8297b/video/index.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9obHMyLnZpZGVvcy5zcHJvdXR2aWRlby5jb20vZGU2OTZhNDc1MWI5MWFhZDI1OWE4NTA5NzMxYzZjMDcvM2QwODA0N2Y2YjllMDllYjE2M2E3NDE2ZTllODI5N2IvKi5tM3U4P3Nlc3Npb25JRD0xNGQzYmExZS1hYzhlLTQyNWMtOWZiZi03NmJlZmRkZjJjNmYiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDAzODI2NzR9fX1dfQ__&Signature=Sz5v-Yx2m-eOTQhrf58NmcD4qN9XBC7DiFF2-PyML4GcoXubzUuC7WDWFO9ciQ35em7bQsOfHDBX6ct34v1IABJqCNQ2sXb5Jigc3fgdCtAX-qi3iLqHGka2cQxxTcbj1BsFiEIektY6EoilKFHavqTRnbak1Ea6k7~H08bDalQP3uXwquS9A2mSnnEZioDtW1KIv2qPIs5ZUL9El2gaT4YYXLTD8nPj4TnLmY7eJCYMXmSJzmYJtH6HSEaqtfu3ry~9pjCxxupetVII8ozLal~z715XIa3Aa6tRWkOueC2RU~olqQNAwpQcf6UKU1E7m8I24WipQFgCfTmvJYKFwQ__&Key-Pair-Id=APKAIB5DGCGAQJ4GGIUQ&sessionID=14d3ba1e-ac8e-425c-9fbf-76befddf2c6f'
`
And still got the same 403 error

**Comment by dirkf** [comment]
* In the first log you had unescaped `&`s causing background jobs to be spawned by the POSIX shell, each using that part of the URL as the command.
* In all the posted commands, you have a different URL from the one you quoted in  the issue description.
* None of these URLs refer to pages containing media but appear to be actual media URLs, so yt-dl is not the tool you want.
* sproutvideo.com is not a supported site.

**Comment by kikuyan** [comment]
Add correct User-Agent and Referer headers. Other headers might be needed. Pick them up from your browser's dev tools.
