### ISSUE TITLE
 Connection to tcp://manifest.googlevideo.com:443 failed: Error number -138 occurred

### ISSUE THREAD

**Issue by HackerBoy856** [ytdl-org/youtube-dl#30429]
youtube-dl  -f  best  https://www.youtube.com/watch?v=D4_G9DMwMzA
[youtube] D4_G9DMwMzA: Downloading webpage
[youtube] D4_G9DMwMzA: Downloading m3u8 information
[youtube] D4_G9DMwMzA: Downloading MPD manifest
[download] Destination: Billboard hot 100 This Week�ADELE, Maroon 5, Bilie Eilish, Taylor Swift, Sam Smith, Rihana�Pop Hits 2021-12-26 10_58-D4_G9DMwMzA.mp4
ffmpeg version 2021-12-23-git-60ead5cd68-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11.2.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 13.100 / 57. 13.100
  libavcodec     59. 15.100 / 59. 15.100
  libavformat    59. 10.100 / 59. 10.100
  libavdevice    59.  0.101 / 59.  0.101
  libavfilter     8. 20.100 /  8. 20.100
  libswscale      6.  1.102 /  6.  1.102
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
[tcp @ 0000022bfcc81c40] Connection to tcp://manifest.googlevideo.com:443 failed: Error number -138 occurred
https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1640509111/ei/V9rHYcZNiZuBA86-hdAB/ip/52.68.230.224/id/D4_G9DMwMzA.1/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr1---sn-oguelnle.googlevideo.com/playlist_duration/30/manifest_duration/30/gcr/jp/vprv/1/playlist_type/DVR/initcwndbps/7550/mh/fY/mip/54.150.222.57/mm/44/mn/sn-oguelnle/ms/lva/mv/m/mvi/1/pl/22/dover/11/keepalive/yes/fexp/24001373,24007246/mt/1640487160/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,gcr,vprv,playlist_type/sig/AOq0QJ8wRAIgU1ceOATgW4TLOdkfDphUfu50B7vrmupYqhWHlu7tyH8CIF1DCAW2ht_9zvWA6ejB3aiswsDa4FG699ajYcwKB-gh/lsparams/hls_chunk_host,initcwndbps,mh,mip,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIhAJcul0ph_xiTCvmZlypxX0Ezd3UZdkU-7f8GUDz1EjFDAiBpUT_oBQnV-1ETPWtip7PeTOS-zuV1W1na8KYD0dARWw%3D%3D/playlist/index.m3u8: Unknown error

Why can't I download it？Please help me thanks

**Comment by kikuyan** [comment]
Doesn't reproduce here. Maybe your network or temporary server problem.
Try Google.
