### ISSUE TITLE
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>)

### ISSUE THREAD

**Issue by heyhappyfuntime** [ytdl-org/youtube-dl#30437]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
/usr/src/app # youtube-dl --version
2021.12.17
/usr/src/app # youtube-dl https://vrv.co/watch/G6793XG1Y/HarmonQuest:The-Virtuous-Harmony -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vrv.co/watch/G6793XG1Y/HarmonQuest:The-Virtuous-Harmony', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.6 (CPython) - Linux-5.10.28-Unraid-x86_64-with
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[vrv] None: Downloading webpage
[vrv] G6793XG1Y: Downloading resource path JSON metadata
[vrv] G6793XG1Y: Downloading CMS Signing JSON metadata
[vrv] G6793XG1Y: Downloading object JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description

Attempting to download from vrv.co is failing. I'm using Chrome and was able to view the video in my browser using the URL. I searched the issues and didn't see an issue related to vrv.co anywhere. A username and password is required, but using the --username and --password flags still lead to the same 404 error.

**Comment by 89z** [comment]
If you can provide credential, I can work on this. Run the following command and reply back with the output:

~~~
echo USER:PASS | age -a -r age1zkz9g0kld97vs826j0r7p3ghvz3zcyd4tcqr2vrxpt0uux7mkycsl77hy6
~~~

https://github.com/FiloSottile/age

**Comment by heyhappyfuntime** [comment]
/usr/src/app # echo USER:PASS | age -a -r
age1zkz9g0kld97vs826j0r7p3ghvz3zcyd4tcqr2vrxpt0uux7mkycsl77h
y6
sh: age: not found

I'm on Unraid 6.9.2

**Comment by 89z** [comment]
I dont know what the hell Unraid is, but install instruction here:

https://github.com/FiloSottile/age#installation

**Comment by heyhappyfuntime** [comment]
Thanks for sharing that page with me. I have heard of some of those words
before but am unsure what you expect me to do with that page. Also, why did
you use the word 'hell'? Are you going to be difficult to work with? If so,
is there someone else who can help?

Unraid is an OS and I installed youtube-dl via a docker container.

**Comment by 89z** [comment]
Good luck to you.

**Comment by heyhappyfuntime** [comment]
Thanks!

Should I create a new ticket?

**Comment by 89z** [comment]
Good idea, create yet another duplicate issue. I fully support that idea.

**Comment by heyhappyfuntime** [comment]
Can you put your emotions aside for one moment? What next steps should I
take?

**Comment by 89z** [comment]
I made very clear what you should do. The site requires credentials, I offered my help for free, I only asked that you provide credentials. I even gave instruction on how to provide credential in a secure way. If you are not able to pass credential to me, then I cannot help. I am not providing any more details, I gave clear instruction already on what tool to use, how to install it, and how to use it.

**Comment by heyhappyfuntime** [comment]
Ok, I'll create a duplicate request per your advice.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30438
