### ISSUE TITLE
https://www.youtube.com/watch?v=hZnuc-Fv_Tc

### ISSUE THREAD

**Issue by GeoHaber** [ytdl-org/youtube-dl#30431]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by GeoHaber** [comment]
The following and other videos don't download :(

https://www.youtube.com/watch?v=hZnuc-Fv_Tc

**Comment by GeoHaber** [comment]
using the latest :)

**Comment by 89z** [comment]
Not possible, its DRM.

**Comment by sapycola** [comment]
it's blocked in your region, use VPN

**Comment by nicolaasjan** [comment]
> Not possible, its DRM.

I think @sapycola is right:

> ERROR: [youtube] hZnuc-Fv_Tc: The uploader has not made this video available in your country.
> You might want to use a VPN or a proxy server (with --proxy) to workaround.

**Comment by october262** [comment]
this link - https://www.youtube.com/watch?v=hZnuc-Fv_Tc
is a youtube movie which is DRM protected
