### ISSUE TITLE
HTTP Error 504: Gateway Timeout (caused by <HTTPError 504: 'Gateway Timeout'>); 

### ISSUE THREAD

**Issue by JingLi513** [ytdl-org/youtube-dl#30435]
youtube-dl --verbose http://media.mtvnservices.com/embed/mgid:arc:video:comedycentral.com:e18533da-4f4e-4e1e-93d3-b1fdfbf89e2a
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://media.mtvnservices.com/embed/mgid:arc:video:comedycentral.com:e18533da-4f4e-4e1e-93d3-b1fdfbf89e2a']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.22000-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[mtvservices:embedded] e18533da-4f4e-4e1e-93d3-b1fdfbf89e2a: Downloading JSON metadata
[mtvservices:embedded] e18533da-4f4e-4e1e-93d3-b1fdfbf89e2a: Downloading info
ERROR: Unable to download XML: HTTP Error 504: Gateway Timeout (caused by <HTTPError 504: 'Gateway Timeout'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\lijin\Miniconda3\lib\site-packages\youtube_dl\extractor\common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\lijin\Miniconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\lijin\Miniconda3\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\lijin\Miniconda3\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\lijin\Miniconda3\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\lijin\Miniconda3\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\lijin\Miniconda3\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by 89z** [comment]
Please provide the original source URL

**Comment by JingLi513** [comment]
original source URL: http://media.mtvnservices.com/embed/mgid:arc:video:comedycentral.com:e18533da-4f4e-4e1e-93d3-b1fdfbf89e2a

**Comment by 89z** [comment]
Please provide the non-embed URL, the original source URL.

**Comment by kikuyan** [comment]
Doesn't reproduce here, version 2021.12.17. 
```
$ youtube-dl --ignore-config http://media.mtvnservices.com/embed/mgid:arc:video:comedycentral.com:e18533da-4f4e-4e1e-93d3-b1fdfbf89e2a
[mtvservices:embedded] e18533da-4f4e-4e1e-93d3-b1fdfbf89e2a: Downloading JSON metadata
[mtvservices:embedded] e18533da-4f4e-4e1e-93d3-b1fdfbf89e2a: Downloading info
[mtvservices:embedded] e18533da-4f4e-4e1e-93d3-b1fdfbf89e2a: Extracting information
[mtvservices:embedded] e18533da-4f4e-4e1e-93d3-b1fdfbf89e2a: Downloading video urls
[mtvservices:embedded] e18533da-4f4e-4e1e-93d3-b1fdfbf89e2a: Downloading m3u8 information
[download] Downloading playlist: A Love Supreme - Profanity & Nudity on TV
[mtvservices:embedded] playlist A Love Supreme - Profanity & Nudity on TV: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 73
[download] Destination: The Daily Show with Jon Stewart_January 26, 2012_17_NO-EPISODE#_A Love Supreme - Profanity & Nudity on TV-e18533da-4f4e-4e1e-93d3-b1fdfbf89e2a.mp4
[download]   4.1% of ~90.55MiB at  2.24MiB/s ETA 01:47^C
```

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/14724
