### ISSUE TITLE
[VRV] ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>) 

### ISSUE THREAD

**Issue by heyhappyfuntime** [ytdl-org/youtube-dl#30438]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
/usr/src/app # youtube-dl --version
2021.12.17
/usr/src/app # youtube-dl https://vrv.co/watch/G6793XG1Y/HarmonQuest:The-Virtuous-Harmony -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vrv.co/watch/G6793XG1Y/HarmonQuest:The-Virtuous-Harmony', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.6 (CPython) - Linux-5.10.28-Unraid-x86_64-with
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[vrv] None: Downloading webpage
[vrv] G6793XG1Y: Downloading resource path JSON metadata
[vrv] G6793XG1Y: Downloading CMS Signing JSON metadata
[vrv] G6793XG1Y: Downloading object JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description

Attempting to download from vrv.co is failing. I'm using Chrome and was able to view the video in my browser using the URL. I searched the issues and didn't see an issue related to vrv.co anywhere. A username and password is required, but using the --username and --password flags still lead to the same 404 error.

My OS is Unraid 6.9.2 and I installed via docker.

**Comment by 89z** [comment]
If you can provide credential, I can work on this. Run the following command and reply back with the output:

~~~
echo USER:PASS | age -a -r age1zkz9g0kld97vs826j0r7p3ghvz3zcyd4tcqr2vrxpt0uux7mkycsl77hy6
~~~

 https://github.com/FiloSottile/age

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30437

**Comment by heyhappyfuntime** [comment]
/usr/src/app # echo USER:PASS | age -a -r
age1zkz9g0kld97vs826j0r7p3ghvz3zcyd4tcqr2vrxpt0uux7mkycsl77h
y6
sh: age: not found

My guess is that I need to install Age, but have no idea how to do it - I
didn't see anything in the link you shared. I'm using a docker on Unraid
6.9.2. Does that help?

**Comment by 89z** [comment]
The page I linked has install instruction, or you might be able to get a build here:

https://github.com/FiloSottile/age/releases/tag/v1.0.0

However I find it hard to believe that you know how to install Docker, but you can install a simple command line tool. Its a single executable file, no dependencies. It has possibly the simplest install process of any tool I have ever used in 20 years. So if you cant figure out how to install it, then maybe you shouldnt be trying to use YouTube-DL in the first place.

**Comment by dirkf** [comment]
In case the login procedure implemented in the extractor is no longer valid, try passing a [cookie file extracted from a current login session in your browser using `--cookies`](https://github.com/ytdl-org/youtube-dl#user-content-how-do-i-pass-cookies-to-youtube-dl), **instead of** the username and password.
