### ISSUE TITLE
HTTP - 403 Acces Denied for generating Token for Servus TV videos

### ISSUE THREAD

**Issue by kfersch** [ytdl-org/youtube-dl#30436]
## Checklist

- [ x ] I'm reporting a broken site support issue
- [ x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x ] I've checked that all provided URLs are alive and playable in a browser
- [ x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

```
youtube-dl --no-call-home -v --proxy ""  https://www.servustv.com/videos/aa-28zh3u3dn2111/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-call-home', '-v', '--proxy', '', 'https://www.servustv.com/videos/aa-28zh3u3dn2111/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 5014bd67c
[debug] Python version 3.8.10 (CPython) - Linux-5.11.0-43-generic-x86_64-with-glibc2.29
[debug] exe versions: none
[debug] Proxy map: {}
[Servus] AA-28ZH3U3DN2111: Downloading token
https://auth.redbullmediahouse.com/token
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/kfersch/youtube-dl/youtube_dl/extractor/common.py", line 636, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/kfersch/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

(venv)
```

## Description

Seems that Servus TV has changed the authorization Bearer for generating Tokens. I get a 403 Acces Denied when you try to create a Token from https://redbullmeadiahosue.com/token. 
You can check it with the following curl request:
```curl -i -v -L --noproxy "*" -X POST "https://auth.redbullmediahouse.com/token" -d"grant_type=client_credentials" -H 'Authorization: Basic SVgtMjJYNEhBNFdEM1cxMTpEdDRVSkFLd2ZOMG5IMjB1NGFBWTBmUFpDNlpoQ1EzNA==' -H 'Content-Type: application/x-www-form-urlencoded'``` 
Bearer was taken from the code. Tried to use the new Bearer from `https://player.redbull.com/1.3.35-stv-release-3177/rbup-datamanager.js` which should be actual version used, but did not work. Since I do not know where you got that Bearer I will let you search for the new one. 

### How did I get the current version ?
Just inspect the code of the url (https://www.servustv.com/videos/aa-28zh3u3dn2111/)  and there is the following file loaded: https://player.redbull.com/stv/stv-wrapper-init.js in this file there is the current tag located of the js version. 
```
const getBuildTag = () => {
  return '1.3.35-stv-release-3177';
};
```

### Local Modifies: 
I checkout the master branch and did the following changes: https://github.com/ytdl-org/youtube-dl/pull/29556 to get rid of the unsupported URL problem.

**Comment by flashdagger** [comment]
You might wanna try the [servustv plugin](https://pypi.org/project/ytdlp-servustv/) for yt-dlp...

**Comment by kfersch** [comment]
@flashdagger Thx mate this plugin worked as expected. Was not aware of that plugin.

**Comment by kikuyan** [comment]
> I checkout the master branch and did the following changes: #29556 to get rid of the unsupported URL problem.

All changes have not been applied correctly. That PR works.
