### ISSUE TITLE
this happen when i try to download from nsfw site

### ISSUE THREAD

**Issue by ehsansayrafi** [ytdl-org/youtube-dl#30441]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

![image](https://user-images.githubusercontent.com/76585512/147645724-127056b8-8542-4b84-8ce1-b6b0f1500cf5.png)

**Comment by kikuyan** [comment]
Make a decent issue report.
I can't see anything.
