### ISSUE TITLE
Unable to download API page

### ISSUE THREAD

**Issue by Railkimi** [ytdl-org/youtube-dl#30446]
D:\personal\film>yt-dlp -F https://www.youtube.com/watch?v=7wHJ3M8_XSE
[youtube] 7wHJ3M8_XSE: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urlopen error [WinError 10013] 以一种访问权限不允许的方式做了一个访问套 接字的尝试。>
[youtube] 7wHJ3M8_XSE: Downloading android player API JSON
WARNING: [youtube] <urlopen error [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。>. Retrying ...
[youtube] 7wHJ3M8_XSE: Downloading android player API JSON (retry #1)
WARNING: [youtube] <urlopen error [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。>. Retrying ...
[youtube] 7wHJ3M8_XSE: Downloading android player API JSON (retry #2)
WARNING: [youtube] <urlopen error [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。>. Retrying ...
[youtube] 7wHJ3M8_XSE: Downloading android player API JSON (retry #3)
[youtube] 7wHJ3M8_XSE: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: <urlopen error [WinError 10013] 以一种访问权限不允许的方式做了一个访问套 接字的尝试。>
[youtube] 7wHJ3M8_XSE: Downloading web player API JSON
WARNING: [youtube] <urlopen error [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。>. Retrying ...
[youtube] 7wHJ3M8_XSE: Downloading web player API JSON (retry #1)
WARNING: [youtube] <urlopen error [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。>. Retrying ...
[youtube] 7wHJ3M8_XSE: Downloading web player API JSON (retry #2)
WARNING: [youtube] <urlopen error [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。>. Retrying ...
[youtube] 7wHJ3M8_XSE: Downloading web player API JSON (retry #3)
WARNING: [youtube] Unable to download API page: <urlopen error [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。> (caused by URLError(OSError(10013, '以一种访问权限不允许的方式做了一个访问套接字的尝试。', None, 10013, None)))
ERROR: [youtube] 7wHJ3M8_XSE: Unable to download API page: <urlopen error [WinError 10013] 以一种访问权限不允许的方式做 了一个访问套接字的尝试。> (caused by URLError(OSError(10013, '以一种访问权限不允许的方式做了一个访问套接字的尝试。', None, 10013, None))) (caused by URLError(OSError(10013, '以一种访问权限不允许的方式做了一个访问套接字的尝试。', None, 10013, None)))

**Comment by dirkf** [comment]
There's a problem with your host's network configuration. [Here](https://www.reddit.com/r/learnpython/comments/lqpk8f/python_socket_winerror_10013/) it was down to a VPN service blocking socket access.

**Comment by kikuyan** [comment]
Wrong place. This is **youtube-dl** repository, **not yt-dlp**.
