### ISSUE TITLE
mp3s not available

### ISSUE THREAD

**Issue by inventor1214** [ytdl-org/youtube-dl#30463]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

How do you do all, I'm using this for the first time and using it with mp3s does not seem to want to work. Is there a separate thing I need to download to get mp3s? I know some other programs need that due to the mp3 file format being copyright or similar. Attached is the error I receive. Thanks!

![image](https://user-images.githubusercontent.com/54367442/147975399-0160edc8-4a0a-4999-8cc7-99718f4ed3ac.png)

**Comment by 89z** [comment]
YouTube has not served MP3 files for many years. For audio, currently it serves WebA files and M4A files. After you download these, you can transcode them to MP3 if you want, but most players support WebA and M4A, so I would just leave them as is.

**Comment by kikuyan** [comment]
> Attached is the error I receive. 

I cannot see anything. If you mean you posted a screenshot, please don't. Copy and paste the verbose log in plain text.
https://github.com/ytdl-org/youtube-dl/blob/master/README.md#bugs

**Comment by 89z** [comment]
The message from @kikuyan is pointless, as the question and answer are both simple. They have fallen into the trap of having rigid requirements, regardless of how arbitrary and useless they might be. If this was a more involved issue then sure, its a bad idea to just throw up a screenshot.

Sometimes you just need to read the room.

**Comment by dirkf** [comment]
OP should know from reading the Manual that the available formats for a particular URL can be listed with the `--list-formats` (or just `-F`) option. Thus:
```
$ youtube-dl -F 4zfHjtqqbEM
[youtube] 4zfHjtqqbEM: Downloading webpage
[youtube] 4zfHjtqqbEM: Downloading player 8da38e9a
[info] Available formats for 4zfHjtqqbEM:
format code  extension  resolution note
249          webm       audio only tiny   52k , webm_dash container, opus @ 52k (48000Hz), 1.01MiB
250          webm       audio only tiny   68k , webm_dash container, opus @ 68k (48000Hz), 1.31MiB
140          m4a        audio only tiny  127k , m4a_dash container, mp4a.40.2@127k (44100Hz), 2.45MiB
251          webm       audio only tiny  136k , webm_dash container, opus @136k (48000Hz), 2.63MiB
278          webm       256x144    144p   31k , webm_dash container, vp9@  31k, 6fps, video only, 617.00KiB
160          mp4        256x144    144p   50k , mp4_dash container, avc1.42c00c@  50k, 6fps, video only, 995.64KiB
242          webm       426x240    240p   34k , webm_dash container, vp9@  34k, 6fps, video only, 686.46KiB
133          mp4        426x240    240p   96k , mp4_dash container, avc1.4d4015@  96k, 6fps, video only, 1.85MiB
243          webm       640x360    360p   54k , webm_dash container, vp9@  54k, 6fps, video only, 1.04MiB
134          mp4        640x360    360p  102k , mp4_dash container, avc1.4d4016@ 102k, 6fps, video only, 1.96MiB
244          webm       854x480    480p   73k , webm_dash container, vp9@  73k, 6fps, video only, 1.40MiB
135          mp4        854x480    480p  171k , mp4_dash container, avc1.4d4016@ 171k, 6fps, video only, 3.29MiB
247          webm       1280x720   720p  112k , webm_dash container, vp9@ 112k, 6fps, video only, 2.17MiB
136          mp4        1280x720   720p  280k , mp4_dash container, avc1.4d401f@ 280k, 6fps, video only, 5.38MiB
248          webm       1920x1080  1080p  195k , webm_dash container, vp9@ 195k, 6fps, video only, 3.75MiB
137          mp4        1920x1080  1080p  466k , mp4_dash container, avc1.640028@ 466k, 6fps, video only, 8.96MiB
18           mp4        640x360    360p  167k , avc1.42001E, 6fps, mp4a.40.2 (44100Hz), 3.23MiB (best)
$
```
And plainly no MP3 formats are offered.

If OP has _ffmpeg_ installed, the options `--extract-audio --audio-format mp3` would automatically convert the selected audio format (eg `-f 251`).
