### ISSUE TITLE
mpd: No video formats found

### ISSUE THREAD

**Issue by kannerke** [ytdl-org/youtube-dl#30464]
Yesterday, downloading e.g. https://www.vrt.be/vrtnu/a-z/killing-escobar/ worked (by using the underlying m3u or mpd link)
Now, this no longer works. I've updated youtube-dl but the issue remains.

I'm running Ubuntu 20.04.

python3 ./youtube-dl -ciw https://remix-cf.lwc.vrtcdn.be/remix/b6507c9e-97c8-4a9b-aba7-447c0d742488/remix.ism/.mpd --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-ciw', 'https://remix-cf.lwc.vrtcdn.be/remix/b6507c9e-97c8-4a9b-aba7-447c0d742488/remix.ism/.mpd', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-91-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[generic] .mpd: Requesting header
WARNING: Falling back on generic information extractor.
[generic] .mpd: Downloading webpage
[generic] .mpd: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "../youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "../youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "../youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "../youtube-dl/youtube_dl/extractor/generic.py", line 2499, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "../youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

PS: in the past, I could use the 'public' url (https://www.vrt.be/vrtnu/a-z/killing-escobar/) instead of the m3u/mpd link in order to download the media.

**Comment by flashdagger** [comment]
The manifest says it's DRM protected:

```xml
<!-- Common Encryption -->
<ContentProtection
  xmlns="urn:mpeg:dash:schema:mpd:2011"
  xmlns:cenc="urn:mpeg:cenc:2013"
  schemeIdUri="urn:mpeg:dash:mp4protection:2011"
  value="cenc"
  cenc:default_KID="4232EBAE-9898-75C6-01DC-F149A26C72FC">
</ContentProtection>
```

**Comment by kannerke** [comment]
Thank you for the fast reply. Where can I find/see this manifest?

For DRM there is likely no fix available?

**Comment by flashdagger** [comment]
> Thank you for the fast reply. Where can I find/see this manifest?
Your link is the MPD XML manifest. You can download ist with `curl `or `wget`

> For DRM there is likely no fix available?
Somehow you need the keys, then you could feed it to `ffmpeg`.

**Comment by kikuyan** [comment]
Go [VideoHelp Forum](https://forum.videohelp.com/forums/48-Video-Streaming-Downloading) and close this.

**Comment by hansworzt** [comment]
Change
https://remix-cf.lwc.vrtcdn.be/remix/b6507c9e-97c8-4a9b-aba7-447c0d742488/remix.ism/.mpd
into
https://remix-cf.lwc.vrtcdn.be/remix/b6507c9e-97c8-4a9b-aba7-447c0d742488/remix_aes.ism/.m3u8
etc.

**Comment by dirkf** [comment]
Possibly the real issue is that the VRT extractor only knows about news and sports pages, leading  OP extract links manually. The URL rewrite could be a useful tactic if someone wanted to extend the extractor.

**Comment by matgott** [comment]
can we specify a license server? I have this issue with an .mpd but I have access to the license server.

**Comment by 89z** [comment]
It wouldn't just be the server, as some license servers also require request headers. So a function accepting URL and Headers argument would probably be enough. Or you could probably accept a request object [1], which the function then modifies by adding a request body.

https://docs.python.org/library/urllib.request.html#urllib.request.Request
