### ISSUE TITLE
Downloaded videos (PornHub) freeze for a second when seeking

### ISSUE THREAD

**Issue by avekifes** [ytdl-org/youtube-dl#30468]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is anyone experiencing this? I use MPC-BE, but it's not a player issue, as I don't encounter this problem with any other type of video. What's the fix?

**Comment by flashdagger** [comment]
Sometimes the timestamps are messed up. You could fix the video container with ffmpeg:
`ffmpeg -i <infile> -c copy <outfile>`

**Comment by avekifes** [comment]
> Sometimes the timestamps are messed up. You could fix the video container with ffmpeg: `ffmpeg -i <infile> -c copy <outfile>`

Interesting. I can try to figure it out on my own, but is there a way to configure youtube-dl to have ffmpeg run this automatically after every download?

**Comment by flashdagger** [comment]
> Interesting. I can try to figure it out on my own, but is there a way to configure youtube-dl to have ffmpeg run this automatically after every download?

use option `--external-downloader ffmpeg`
