### ISSUE TITLE
gagaoolala.com not working

### ISSUE THREAD

**Issue by misoborovsky** [ytdl-org/youtube-dl#30461]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://gol-ns-videos.akamaized.net/videos/57/57a7e8ce-1820738084/61143.cc.mpd?hdnts=exp=1641237739~acl=/videos/57/57a7e8ce-1820738084/*~hmac=0c1da08bf8507904e72d92a46352edb2815ff2ac95eb6158f496e984bd3b5c68', '--verbose']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-03-03-git-4dc039b4c7-full_build-www.gyan.dev, ffprobe 2021-03-03-git-4dc039b4c7-full_build-www.gyan.dev
[debug] Proxy map: {}

```
[generic] *~hmac=0c1da08bf8507904e72d92a46352edb2815ff2ac95eb6158f496e984bd3b5c68: Requesting header
WARNING: Falling back on generic information extractor.
[generic] *~hmac=0c1da08bf8507904e72d92a46352edb2815ff2ac95eb6158f496e984bd3b5c68: Downloading webpage
[generic] *~hmac=0c1da08bf8507904e72d92a46352edb2815ff2ac95eb6158f496e984bd3b5c68: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 2499, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description
hey, I was able to download from this site before, but currently it looks like it cant find any videos, any ideas whats wrong? 
Thanks in advance.

Edit: URL: https://www.gagaoolala.com/en/videos/1655/private-lessons-2019

**Comment by 89z** [comment]
Please provide example URL

**Comment by dirkf** [comment]
The site (www.gagaoolala.com) is not supported, but seems to need a login. The mpd URL fails for me in the browser with an Akamai 403, as well as in yt-dl.

**Comment by misoborovsky** [comment]
Okay, I do have a login, but it is not downlaoding anyway. The error in description is that it can't find any video "No video formats found". Any ideas ?

**Comment by kikuyan** [comment]
"No video formats found" might be the result that all streams in the mpd are DRM protected thus skipped.
