### ISSUE TITLE
Youtube-dl premium login

### ISSUE THREAD

**Issue by DevangerTM** [ytdl-org/youtube-dl#30471]
And it would not be possible to do some option, that some YouTube login was in yt-dl and if someone has a premium account, nothing is blocking him? Because youtube wants to do, and if youtube-dl processes without advertising, they do not earn, and if someone had a premium account there, you would do some login and then they would earn premium from someone.

Because I have music bots on the teamspeak application that use youtube-dl to play music and I would like there to be an option as mentioned above and then I will not need a proxy.

**Comment by dirkf** [comment]
`--cookies` may work. I believe the login procedure that was implemented in YT extractor is currently broken: perhaps YT started to need a CAPTCHA or similar: so don't try to use `--username`/`--password` -- it will just stop the cookies from being used.

**Comment by DevangerTM** [comment]
There is only a problem, because you need to log in to the account and confirm your age.

Sign in to confirm your age

![Screenshot_38](https://user-images.githubusercontent.com/41342020/148333332-196a83a2-11dd-4e2f-877f-1fc43043028f.png)

**Comment by dirkf** [comment]
So **as I said** the login procedure doesn't work. Don't provide `--username`/`--password`.

Use the `--cookies` option as described in the Manual.

Also, the age-gate can be bypassed with [this patch](https://github.com/ytdl-org/youtube-dl/issues/30255#issuecomment-974822885), or use yt-dlp.

**Comment by 89z** [comment]
I have an alternate tool that works, no cookies or login needed:

~~~
PS C:\> youtube -e -i b8LQiAQ6wyQ
POST https://www.youtube.com/youtubei/v1/player
Itag:133 Height:240 Bitrate:184009 ContentLength:256394 MimeType:video/mp4
Itag:160 Height:144 Bitrate:108000 ContentLength:0 MimeType:video/mp4
Itag:139 Bitrate:49130 ContentLength:82011 MimeType:audio/mp4
Itag:140 Bitrate:128172 ContentLength:216555 MimeType:audio/mp4
Itag:251 Bitrate:110193 ContentLength:183073 MimeType:audio/webm
~~~

https://github.com/89z/mech

**Comment by DevangerTM** [comment]
The only problem is that our app uses Youtube-DL, not YTDLP. How are they different from each other when they are the same? And I need to confirm the age in our bot somehow on youtube. And the confirmation works only when youtube connects to the account using the ssh command.

**Comment by dirkf** [comment]
yt-dlp is a version of yt-dl that was forked and forked again but still has a lot of code in common.

Apparently you should either apply the patch that I linked (which implements an age-gate bypass, at least when I last checked, like that in yt-dlp) or read up on yt-dlp, which is easy since the project, including its [differences from yt-dl](https://github.com/yt-dlp/yt-dlp#user-content-differences-in-default-behavior), is well documented.

**Comment by dirkf** [comment]
Read https://github.com/ytdl-org/youtube-dl/issues/30471#issuecomment-1006469308 again.
