### ISSUE TITLE
CBS "Adele One Night Only" Unsupported URL

### ISSUE THREAD

**Issue by paul-coder-646** [ytdl-org/youtube-dl#30477]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.cbs.com/shows/adele-one-night-only/video/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.1 (CPython) - macOS-12.2-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video: Downloading webpage
[generic] video: Extracting information
ERROR: Unsupported URL: https://www.cbs.com/shows/adele-one-night-only/video/
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.cbs.com/shows/adele-one-night-only/video/

## Description

Hi, I hope, I provided enough info to help resolving this issue, if not please don't be mad, I just read the How to submit bugs section and followed the checklist. In case somethings missing, just hmu ok :) 

Allright, the issue that I am facing is trying to download Adeles "One Night Only" from CBS. It is restricted to the US and I thought a VPN would be sufficient for unblocking, but I also already tried the `--geo-bypass` flag which didn't yield any different result than I am getting. It always says "Unsupported URL"
I have heard different things in other issues: Is it because cbs uses drm that the site is not supported? 
Thanks a ton for your time and help
Sincerely Paul

**Comment by raleeper** [comment]
This URL works for me, but I am in the US. 

https://www.cbs.com/shows/adele-one-night-only/video/BoW36T84lPNYyOfJv7a0UK064wALi3Of/adele-one-night-only/

**Comment by dirkf** [comment]
Apparently a VPN that isn't blocked by the site is needed to access the content from outside the US.

**Comment by 89z** [comment]
@raleeper what do you mean it "works for you"? From what I can tell, the video is protected by Widevine DRM.

**Comment by raleeper** [comment]
Sorry. Should have left evidence.
```
youtube-dl "https://www.cbs.com/shows/adele-one-night-only/video/BoW36T84lPNYyOfJv7a0UK064wALi3Of/adele-one-night-only/" --ignore-config --hls-prefer-native --verbose

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.cbs.com/shows/adele-one-night-only/video/BoW36T84lPNYyOfJv7a0UK064wALi3Of/adele-one-night-only/', '--ignore-config', '--hls-prefer-native', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.7 (CPython) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[CBS] BoW36T84lPNYyOfJv7a0UK064wALi3Of: Downloading XML
[CBS] BoW36T84lPNYyOfJv7a0UK064wALi3Of: Downloading StreamPack SMIL data
[CBS] BoW36T84lPNYyOfJv7a0UK064wALi3Of: Downloading m3u8 information
[CBS] BoW36T84lPNYyOfJv7a0UK064wALi3Of: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/11/02/1970232387807/ADELE_ONE_NIGHT_111221_2398_1920x1080_1031379_,2228,4628,3128,1628,848,503,000.mp4.csmil/index_1_av.m3u8?null=0&id=AgBJqZR9F8NpT4GG12E0HmQrdGGdIWIglfZXkobN6yLlRMJV3mX5UL%2f8C8kDRYGQ1gy3A3Vc4MLLpQ%3d%3d&hdntl=exp=1641601025~acl=%2fi%2ftemp_hd_gallery_video%2fCBS_Production_Outlet_VMS%2fvideo_robot%2fCBS_Production_Entertainment%2f2021%2f11%2f02%2f1970232387807%2fADELE_ONE_NIGHT_111221_2398_1920x1080_1031379_*~data=hdntl~hmac=4ba56c33b92a79f083142e9b921d3e5e924b0c6b47efc9d2c7d2ade611a3e27b'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 527
[download] Destination: Adele One Night Only-BoW36T84lPNYyOfJv7a0UK064wALi3Of.mp4
[download]   1.5% of ~2.99GiB at  2.19MiB/s ETA 04:27
ERROR: Interrupted by user
```
