### ISSUE TITLE
[Windows] [Errno 13] Downloading to folder

### ISSUE THREAD

**Issue by decafade** [ytdl-org/youtube-dl#30475]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

Hey, sorry if this sounds like a noob question- I don't use command line functions or Python that much.
When I try to download to a folder using youtube-dl and command line arguments, or use the config.txt file to download to a folder I get [errno 13]
Specifically,

> C:\WINDOWS\system32>youtube-dl -o "B:\Documents\Pictures\holo\laplus" https://twitter.com/i/status/1477135489513967621
[twitter] 1477135489513967621: Downloading guest token
[twitter] 1477135489513967621: Downloading JSON metadata
[twitter] 1477135489513967621: Downloading m3u8 information
ERROR: unable to open for writing: [Errno 13] Permission denied: 'B:\\Documents\\Pictures\\holo\\laplus'

I searched the web to be able to find out how to get Python or a Python function to have permissions to download to a folder- but have no such luck- they say to just give Python o r the program I'm running relevant permissions. I've given Python the relevant Security Permissions and still get [Errno 13].

If anyone is able to help me out- thank you for your time!

**Comment by dirkf** [comment]
Your command is trying to write a file with the same name as the directory (which must already exist). Read the Manual concerning the [`-o` option](https://github.com/ytdl-org/youtube-dl#user-content-filesystem-options) and [OUTPUT TEMPLATES](https://github.com/ytdl-org/youtube-dl#user-content-output-template).

Basically, you need to add some actual filename template to the option value, eg `-o "B:\Documents\Pictures\holo\laplus\%(title)s-%(id)s.%(ext)s"`.

**Comment by 89z** [comment]
I have an alternate tool that works:

~~~
PS C:\> twitter -o C:\Users\Steven\Pictures 1477135489513967621
POST https://api.twitter.com/1.1/guest/activate.json
GET https://api.twitter.com/1.1/statuses/show/1477135489513967621.json?tweet_mode=extended
GET https://video.twimg.com/amplify_video/1477128888115691523/vid/320x320/tHHbLIY29-Gho2fL.mp4
~~~

https://github.com/89z/mech

**Comment by decafade** [comment]
Thank you! Yep- the problem was not adding the value for the filename and extension.

**Comment by dirkf** [comment]
Feel free to close the issue, then.

Also, 
>I have an alternate tool that works:

[That's nice.](https://github.com/ytdl-org/youtube-dl/issues/30398#issuecomment-1001226243)

**Comment by 89z** [comment]
@dirkf you can shitpost all you want, I am not stopping my commenting.
