### ISSUE TITLE
youtube-dl just opens a cmd then closes immediatly 

### ISSUE THREAD

**Issue by crusherXF** [ytdl-org/youtube-dl#30476]
whenever I try to open youtube-dl.exe it just opens a cmd and then closes immediatly, I am on windows 10

**Comment by 89z** [comment]
Its a command line program. You dont just click on it, you need to run it from a terminal.

**Comment by nicolaasjan** [comment]
If you're uncomfortable with the command line (CMD), you can try a [GUI program](https://old.reddit.com/r/youtubedl/wiki/info-guis). 🙂
E.g. [yt-dlg](https://github.com/oleksis/youtube-dl-gui).

**Comment by andyncake** [comment]
Regarding your problem, you can move the youtube-dl.exe to your **Desktop**, then open Command Prompt,
type
`cd Desktop`
then
`youtube-dl.exe https://www.youtube.com/watch?v=oI-BoEca2bE`

And see if it works.

Try installing youtube-dl via Python's **pip** library.
1. Install [Python](https://www.python.org/downloads/)  and don't forget to tick "Add to **PATH**."
2. Open **Command Prompt** and type 
`pip install youtube-dl`
`pip install ffmpeg`
3. Close Command Prompt and reopen it.
4. Type 
`youtube-dl https://www.youtube.com/watch?v=oI-BoEca2bE`
and it may work.

I hope this will help you to get through this issue.

There's an alternative with GUI using youtube-dl and yt-dlp, 
just go to [FireDM](https://github.com/firedm/FireDM) and follow its instructions.

**Comment by L30m4nc3r** [comment]
same problem. Here is the log from your provided run option


C:\Users\L30m4nc3r>cd Desktop

C:\Users\L30m4nc3r\Desktop>youtube-dl.exe https://www.youtube.com/watch?v=oI-BoEca2bE
[youtube] oI-BoEca2bE: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
