### ISSUE TITLE
Unable to download Facebook videos

### ISSUE THREAD

**Issue by NotErikUden** [ytdl-org/youtube-dl#30473]
I am on Windows 10, but also checked on Windows 11 with Python version 3.9.9 and 3.7.1 respectively. 

## Checklist

- ☑ I'm reporting a broken site support issue
- ☑ I've verified that I'm running youtube-dl version **2021.12.17**
- ☑ I've checked that all provided URLs are alive and playable in a browser
- ☑ I've checked that all URLs and arguments with special characters are properly quoted or escaped
- ☑ I've searched the bugtracker for similar bug reports including closed ones
- ☑ I've read bugs section in FAQ

## Verbose log
On Windows 10 with Python 3.9.9:
```
youtube-dl --verbose --newline -i --hls-prefer-native --write-description --write-info-json --write-annotations --cookies W:/~-archive-~/[~-video-channels-~]/cookies.txt --write-thumbnail --output W:/~-archive-~/[~-video-channels-~]/Directory/%(title)s.%(ext)s https://www.facebook.com/Account/videos/PlayingVideo/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--newline', '-i', '--hls-prefer-native', '--write-description', '--write-info-json', '--write-annotations', '--cookies', 'W:/~-archive-~/[~-video-channels-~]/cookies.txt', '--write-thumbnail', '--output', 'W:/~-archive-~/[~-video-channels-~]/Directory/%(title)s.%(ext)s', 'https://www.facebook.com/Account/videos/PlayingVideo/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.9 (CPython) - Windows-10-10.0.19043-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] VideoID: Downloading webpage
[facebook] VideoID: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\eriku\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\eriku\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\eriku\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\eriku\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\facebook.py", line 680, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "C:\Users\eriku\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\facebook.py", line 594, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

On Windows 11 with Python 3.7.9:
```
youtube-dl --verbose --newline -i --hls-prefer-native --write-description --write-info-json --write-annotations --cookies D:/~-archive-~/[~-video-channels-~]/cookies.txt --write-thumbnail --output D:/~-archive-~/[~-video-channels-~]/Directory/%(title)s.%(ext)s https://www.facebook.com/Account/videos/PlayingVideo/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--newline', '-i', '--hls-prefer-native', '--write-description', '--write-info-json', '--write-annotations', '--cookies', 'D:/~-archive-~/[~-video-channels-~]/cookies.txt', '--write-thumbnail', '--output', 'D:/~-archive-~/[~-video-channels-~]/Directory/%(title)s.%(ext)s', 'https://www.facebook.com/Account/videos/PlayingVideo/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.7.1 (CPython) - Windows-10-10.0.22000-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] VideoID: Downloading webpage
[facebook] VideoID: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\eriku\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\eriku\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\eriku\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\users\eriku\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\facebook.py", line 680, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "c:\users\eriku\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\facebook.py", line 594, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
(I have also tried the same commands with proper quotations around the URL which yielded the same result)

I have replaced:
- The directory name with "Directory"
- The account name with "Account"
- The video ID with "PlayingVideo" or "VideoID"

For anonymity purposes. 

If you think it is necessary for you to test out the videos I have downloaded and require the link, I will happily oblige and give it to you. 

## Description

I typed in the youtube-dl command and received this error message. This started occuring yesterday, on the 5th of January 2022 at around 10 PM UTC. Before this, the same command perfectly worked and yielded no errors. I first realized the issue with youtube-dl in Tartube, and then also in yt-dlp which has the same error. Considering I am also using multiple different environments/Windows versions as well as versions of Python, I am assuming it has something to do with the fact that Facebook changed something about the way they stream videos. 

I have tried to run the same commands with login credentials, yet it failed there too! Also, no metadata has been downloaded for the past two days, but there is already an [issue open about that ](https://github.com/ytdl-org/youtube-dl/issues/30472)

If there is a simple solution to the problem I am running into, please let me know and I will apologize about opening an issue when the issue was really me, however, as I was told by the output to report this error, I much rather wanted to do that!

Thank you in advance for any responses or help!

**Comment by dirkf** [comment]
Your best chance of a fix is to report this in the yt-dlp tracker, as no-one else has yet done so. If you can show a case that doesn't need to be redacted, so much the better.

**Comment by 89z** [comment]
This doesnt seem to be a valid URL:

https://www.facebook.com/Account/videos/PlayingVideo/

> This page isn't available

**Comment by NotErikUden** [comment]
> This doesnt seem to be a valid URL:
> 
> https://www.facebook.com/Account/videos/PlayingVideo/
> 
> > This page isn't available

I've replaced aspects of this link for anonymity purposes but can confirm that the original link still perfectly works and plays a video!

**Comment by 89z** [comment]
I you want help, youre more likely to get it by providing a URL that actually works. It doesnt necessarily have to be the true page that you are wanting, but it needs to be at least some kind of valid, public URL.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30650

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30681

**Comment by 89z** [comment]
Issue should be closed. Valid URL has not been provided, OP has ignored template and explicit request.

**Comment by dirkf** [comment]
Fair enough. I expect that PR #30700 will fix whatever problem was observed.
