### ISSUE TITLE
[Vimeo] Unable to download webpage: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by Tom2Terrific** [ytdl-org/youtube-dl#30497]
'$ youtube-dl --verbose -F https://player.vimeo.com/video/664495314
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'https://player.vimeo.com/video/664495314']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-91-lowlatency-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 664495314: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

'

Using the latest version, 'youtube-dl is up-to-date (2021.12.17)'

Also tried with the complete URL, from '?' to the end.

**Comment by 89z** [comment]
Its not a valid URL:

~~~
PS C:\> curl -I https://player.vimeo.com/video/664495314
HTTP/1.1 404 Not Found
~~~

**Comment by Tom2Terrific** [comment]
There were 2 URLs in the page source, and I copied/pasted as I always do.  Both came up with Error 404.

**Comment by Tom2Terrific** [comment]
Hmmmm - when I paste that URL into a browser tab, I get the intended Vimeo video.  When I grab the URL from THAT page, youtube-dl WILL find it (when I leave off the trailing backslash):
https://player.vimeo.com/video/664429574?h=0c86d78c90\

**Comment by 89z** [comment]
No need for YouTube-DL, this page has links to download:

https://vimeo.com/664429574/0c86d78c90

**Comment by Tom2Terrific** [comment]
Yup.  I've just been spoiled by copying the vimeo.com link from page source, and using youtube-dl to download in the desired format.  Thanks for your input.  
It does appear that the link is valid, but youtube-dl gives the 404 Error.  So I followed the instructions to post the debug output here.

**Comment by kikuyan** [comment]
Please use issue template next time. You can choose the one when you click the New issue button if you log in first then (re)open the page.

There's this checklist item at the top of the template, so you can make sure first that the URL is valid.
> - [ ] I've checked that all provided URLs are alive and playable in a browser

And please close this. No point in keeping this open anymore, I think.
