### ISSUE TITLE
Symbol ':' is replaced by '#'.

### ISSUE THREAD

**Issue by Daoprotoss** [ytdl-org/youtube-dl#30494]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello! I think you can help me with this problem. Is it possible to remove symbol replacement? When I use --output, the symbol ':' is replaced by '#'. It's inconvenient
![image](https://user-images.githubusercontent.com/61596681/148769041-5d7ed6ec-cf84-4523-87a8-df9af97fb593.png)

**Comment by Feathered-Serpent** [comment]
Certain charactes cannot be used in a filename in Windows. The following are restricted:
    < (less than)
    > (greater than)
    : (colon)
    " (double quote)
    / (forward slash)
    \ (backslash)
    | (vertical bar or pipe)
    ? (question mark)
    * (asterisk)

Source: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

You can try to use certain unicode characters which look similiar. For example for a : you can use ∶ for a filename. Seems identical, but is different, and can be used in a filename.

**Comment by Daoprotoss** [comment]
Thanks!
