### ISSUE TITLE
What is the purpose of "part" files ?

### ISSUE THREAD

**Issue by section83** [ytdl-org/youtube-dl#30503]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

I can't find a difference in behaviour between having or not having the "--no-part" setting – except that without that setting there are part files left if the download is interrupted. With or without that setting, downloads are resumed.

So, what is the purpose the part files ?

Thanks.

**Comment by rautamiekka** [comment]
I'm surprised someone would ask something like this.

Simple: the file prevents someone using an incomplete file by saving into the temporary one before renaming it on completion.

**Comment by kikuyan** [comment]
You will see the difference if you start without "--no-part", interrupt, then run with "--no-part" (or vice versa).
Read #48 for the reason of the option.

**Comment by section83** [comment]
OK, thanks. You might guess that I have very little trouble with incomplete downloads. Anyway, just as long as there is no difference in the content of the files.

I plan to add "--no-part" an as option in my applet and need to explain to my users why they might use/not use it. People with high quality internet access might prefer "--no-part".

Cheers.
