### ISSUE TITLE
[FranceTV] Error DL this channel

### ISSUE THREAD

**Issue by gdu2r** [ytdl-org/youtube-dl#30515]
URL  : https://france3-regions.francetvinfo.fr/provence-alpes-cote-d-azur/nais-et-son-pere-sont-partis-sur-les-traces-des-loups-du-parc-du-mercantour-pour-tourner-un-documentaire-2291710.html?utm_medium=Social&utm_source=Facebook&fbclid=IwAR0tAfW6HrddIUXY9NwEXV1tHLKCPauOwM01rl_L9-R1xAqQ3MTfKkyvyNc#Echobox=1642178932

**Comment by kikuyan** [comment]
Read this: https://github.com/ytdl-org/youtube-dl/blob/master/README.md#bugs
