### ISSUE TITLE
Trying to fix some links support aljazeera.py for Python 2.7

### ISSUE THREAD

**Issue by someziggyman** [ytdl-org/youtube-dl#30517]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
./youtube-dl -v 'https://www.aljazeera.net/programs/scenarios/2022/1/14/تونس-ما-سيناريوهات-المواجهة-بين'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.aljazeera.net/programs/scenarios/2022/1/14/\u062a\u0648\u0646\u0633-\u0645\u0627-\u0633\u064a\u0646\u0627\u0631\u064a\u0648\u0647\u0627\u062a-\u0627\u0644\u0645\u0648\u0627\u062c\u0647\u0629-\u0628\u064a\u0646']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.16 (CPython) - Darwin-20.6.0-arm64-arm-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[AlJazeera] تونس-ما-سيناريوهات-المواجهة-بين: Downloading JSON metadata
[AlJazeera] تونس-ما-سيناريوهات-المواجهة-بين: Downloading webpage
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 475, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2069, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 546, in extract
  File "./youtube-dl/youtube_dl/extractor/aljazeera.py", line 73, in _real_extract
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1025, in _search_regex
IndexError: no such group
```

## Description

Trying to make this ytdlp fix https://github.com/yt-dlp/yt-dlp/pull/1577 compatible with Python 2.7 for links like this:
https://www.aljazeera.net/programs/scenarios/2022/1/14/تونس-ما-سيناريوهات-المواجهة-بين

regular "non-Arabic" links work fine:
https://www.aljazeera.com/indepth/features/2017/08/turning-buses-art-pakistan-170821121439045.html

but, always getting IndexError: no such group

If someone could help me understand what am I doing wrong, I'd be very grateful!
Here's my python 2.7 optimised file
[aljazeeraUpdated.zip](https://github.com/ytdl-org/youtube-dl/files/7875498/aljazeeraUpdated.zip)

**Comment by dirkf** [comment]
In yt-dl you can't ask for several groups to be returned from `_search_regex()`. The code sees your tuple `(1, 2, 3, 4)` and uses that as a key.

yt-dl:
```
            else:
                return mobj.group(group)
```
yt-dlp
```
            elif isinstance(group, (list, tuple)):
                return tuple(mobj.group(g) for g in group)
            else:
                return mobj.group(group)
```
But apparently this would have done:
```
            else:
                return mobj.group(*group if isinstance(group, (list, tuple)) else group)
```
As a work-around, until the entirely reasonable extension above is back-ported, try this:
```
             account, player_id, embed, video_id = (None, None, None, None)
             if self._search_regex(self.BRIGHTCOVE_URL_RE, webpage, 'video id',
                                                                     group=0, default=None):
                 account, player_id, embed, video_id = re.search(self.BRIGHTCOVE_URL_RE, webpage).group(1, 2, 3, 4)
```
Apparently this happens with the non-Latin URL because `video_id` is falsy, and this in turn is because the URL-encoded `id` extracted from the URL doesn't return `video` JSON:
```
'%D8%AA%D9%88%D9%86%D8%B3-%D9%85%D8%A7-%D8%B3%D9%8A%D9%86%D8%A7%D8%B1%D9%8A%D9%88%D9%87%D8%A7%D8%AA-%D8%A7%D9%84%D9%85%D9%88%D8%A7%D8%AC%D9%87%D8%A9-%D8%A8%D9%8A%D9%86'
```
However passing `compat_urllib_parse_unquote(id)` to the download call doesn't help. Perhaps the search block that was failing is the correct fall-back for non-Latin IDs.

**Comment by someziggyman** [comment]
what can I say @dirkf? You are a magician! Your suggested work-around worked.
Really appreciate your help!
