### ISSUE TITLE
Can't recognize youtube short url

### ISSUE THREAD

**Issue by StefSate** [ytdl-org/youtube-dl#30525]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [ ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://youtube.com/shorts/o9I6hYxwmzM?feature=share

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Duplicate of #30269, where a trivial fix is provided.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30550
