### ISSUE TITLE
cookies : cookies.txt doesnt work with python code!

### ISSUE THREAD

**Issue by quciny** [ytdl-org/youtube-dl#30526]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
It seems youtube-dl.extract_info doesn`t recognize cookies.txt as a payload option.
a simple example:

```
#!/usr/bin/env python3.9
# -*- coding: utf-8 -*-

from youtube_dl import YoutubeDL as ytdl 

ydl_Opts = { 'cookies': 'cookies.txt',}
link='https://a youtube video require sign in ' 

with ytdl(ydl_Opts) as ydl:

    result = ydl.extract_info(link, download=False)
```
result : **DownloadError: ERROR: Sign in to confirm your age
This video may be inappropriate for some users.**

cookies works fine  when i use command line like :
`
youtube-dl -F --cookies=cookies.txt 'https://a youtube video require sign in'`

any clue / suggestion to this issue ?? thanks!

**Comment by dirkf** [comment]
According to the [class documentation for `YoutubeDL`](https://github.com/ytdl-org/youtube-dl/blob/5014bd67c22b421207b2650d4dc874b95b36dda1/youtube_dl/YoutubeDL.py#L212), the option is named `cookiefile` as a property passed to the class constructor

So:
```
ydl_Opts = { 'cookiefile': 'cookies.txt',}
```
.
