### ISSUE TITLE
velocidad de descarga limitada

### ISSUE THREAD

**Issue by maikelasc** [ytdl-org/youtube-dl#30539]
## Checklist

- [ yes] I'm asking a question
- [ yes] I've looked through the README and FAQ for similar questions
- [yes ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

hola .. hace unos dias estoy experimento una baja en la velocidad de descarga desde la pagina de youtube usando youtube-dl .. lo pueden resolver? probe bajando videos desde otros sitios webs y descarga a toda velocidad .. solo me pasa desde la pagina de youtube .. para mi hicieron algun cambio en su plataforma

**Comment by dirkf** [comment]
Menos "unos dias" que **muchos** dias: por favor ver [acqui](https://github.com/ytdl-org/youtube-dl/issues/29326) y el PR #30184.

For the last few days, OP found the download speed from YT, only, reduced, having changed nothing locally.

Without evidence to the contrary, this must be the well known throttling issue for which the PR linked above offers a patch and a pending fix.

**Comment by maikelasc** [comment]
reemplaze el archivo youtube.py en la carpeta extractor y me soluciono el problema .. muchas gracias !
