### ISSUE TITLE
Same JSON response for all websites.

### ISSUE THREAD

**Issue by waqasmughal** [ytdl-org/youtube-dl#30535]
Would be it possible to get the same response for all websites, for example YouTube, Facebook, Instagram. I mean if we have parser  which convert all response  in same JSON format.

**Comment by dirkf** [comment]
The `info_dict` that yt-dl creates is that thing, as defined in the class documentation for `InfoExtractor in `extractor/common.py`. But yt-dl can't control which metadata items are available from each site, so the defined schema will be populated in different ways by different extractors, except that the media or playlist ID and the media URL or format list or playlist entries must be present and the title is conventionally required for a media item.
