### ISSUE TITLE
"Requested format not available" error when the format exists

### ISSUE THREAD

**Issue by FT129** [ytdl-org/youtube-dl#30551]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PS C:\Users\user\dv\test> ./youtube-dl -v https://v.redd.it/gslumru4bid81 --format "bestvideo[ext=mp4][vcodec=h264]+bestaudio[ext=m4a]/best[ext=mp4][vcodec=h264]/best"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://v.redd.it/gslumru4bid81', '--format', 'bestvideo[ext=mp4][vcodec=h264]+bestaudio[ext=m4a]/best[ext=mp4][vcodec=h264]/best']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22538
[debug] exe versions: ffmpeg n4.4-ffmpeg-windows-build-helpers, ffprobe n4.4-ffmpeg-windows-build-helpers
[debug] Proxy map: {}
[Reddit] gslumru4bid81: Downloading m3u8 information
[Reddit] gslumru4bid81: Downloading MPD manifest
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 847, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 881, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 1684, in process_video_result
youtube_dl.utils.ExtractorError: requested format not available
```

## Description

Format selection fails even when the requested video exists in the specified format.  Even if it doesn't by the order of precedence the final option 'best' is supposed to download the video in its best available format from what I understand, but it doesn't. Without the format selection option the download works fine and downloads an mp4.

**Comment by 89z** [comment]
YouTube-DL already chooses the best format by default, so why cant you just use this:

~~~
youtube-dl v.redd.it/gslumru4bid81 
~~~

**Comment by FT129** [comment]
> YouTube-DL already chooses the best format by default, so why cant you just use this:
> 
> ```
> youtube-dl v.redd.it/gslumru4bid81 
> ```

I don't always need the best format, I want an mp4 with the video codec h264. I choose best only when this is not available. And I use this as part of a larger script that downloads videos from other sites as well. One of them being tiktok, and tiktok sometimes downloads the video encoded in h265 when it's left at the default option.

**Comment by 89z** [comment]
> I want an mp4 with the video codec h264

I think thats literally the only option Reddit has, so whats the problem?

**Comment by dirkf** [comment]
OP may know that what Reddit calls the `avc1.4d001f` video codec (as listed with `-F`) is really H.264 but yt-dl doesn't.

Use `[vcodec^=avc1]` instead of `[vcodec=h264]`, but as that's all the video formats there's really no point, to second @89z.

If someone wanted to get H.264 instead of WebM video as a default configuration setting, the way to do that would be to say so, eg `[vcodec!^=?vp9]`.

**Comment by FT129** [comment]
> OP may know that what Reddit calls the `avc1.4d001f` video codec (as listed with `-F`) is really H.264 but yt-dl doesn't.
> 
> Use `[vcodec^=avc1]` instead of `[vcodec=h264]`, but as that's all the video formats there's really no point, to second @89z.
> 
> If someone wanted to get H.264 instead of WebM video as a default configuration setting, the way to do that would be to say so, eg `[vcodec!^=?vp9]`, or (as I now see) to avoid H.265 `[vcodec!^=?h265]`. But be aware that H.265 may also appear as `hevc...`.

Thank you, this is helpful.

**Comment by dirkf** [comment]
Finally, `.../best` didn't help because for this Reddit page the extracted formats are all either audio-only or video-only. Try `.../best/bestvideo+bestaudio` or `.../bestvideo+bestaudio/best` according to preference.

**Comment by FT129** [comment]
> Finally, `.../best` didn't help because for this Reddit page the extracted formats are all either audio-only or video-only. Try `.../best/bestvideo+bestaudio` or `.../bestvideo+bestaudio/best` according to preference.

Thank you!
