### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by thibauta2** [ytdl-org/youtube-dl#30569]
hello 
i got this error when started youtube-dl
"[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

**Comment by 89z** [comment]
please provide example URL

**Comment by thibauta2** [comment]
youtube-dl -u user@ -p @@@@@@@  https://www.udemy.com/udemy.com/burp-suite-in-depth-survival-guide

**Comment by 89z** [comment]
Invalid URL:

> We can’t find the page you’re looking for
