### ISSUE TITLE
output template with format information on complex --format selector

### ISSUE THREAD

**Issue by PatrickJRed** [ytdl-org/youtube-dl#30562]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello everyone,

I am using complex format options like
youtube-dl -f 248/247/244/243/242/278+251/250/249,278/242/243/244/247/248+251/250/249,... -o "$HOME/Media/yt/%(title)s_%(id)s_format-%(format_id)s.%(ext)s" URL
So i figured out that %(format_id)s only gives the video (248/247/244/243/242/278) but not which audio (251/250/249) was downloaded, so how would i get that information ?
Or rephrase how would I get something like format_ids for the downloaded video as well as for the downloaded audio in my output-template?

Thanks in advcance
PatrickJ

**Comment by dirkf** [comment]
If the download is a video+audio merger, the `format_id`s for the two components are combined with `+`, as you might hope (similarly for the `format`s):
```
$ youtube-dl --verbose -o '%(format_id)s' --get-filename 'https://www.youtube.com/watch?v=m7i7HPjaUiY'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', '%(format_id)s', '--get-filename', 'https://www.youtube.com/watch?v=m7i7HPjaUiY']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
135+140
$
```

**Comment by PatrickJRed** [comment]
Yeah figured - my format-selection was wrong

this is what i need : 

-f (248/247/244/243/242/278)+(251/250/249),(278/242/243/244/247/248)+(251/250/249),(VIDEO)+(AUDIO)

i did not check the files themself until now - and oh surprise : no audio was downloaded and therefore nothing was merged

_                   _
   \_ ( ^_^ ) _/

i should have checked for that earlier :)

**Comment by PatrickJRed** [comment]
So to be clear : it now works as expected.
