### ISSUE TITLE
Is it possible to use ytdl to backup the titles of videos in a playlist?

### ISSUE THREAD

**Issue by LOKSTED** [ytdl-org/youtube-dl#30567]
## Checklist

- [ yes ] I'm asking a question
- [yis ] I've looked through the README and FAQ for similar questions
- [ yep although it might have search term I didn't expect, in that case I apologize] I've searched the bugtracker for similar questions including closed ones

## Question

I have a few hundred music saved in a playlist but when it gets removed on YouTube, the title gets removed as well making it impossible to recover by searching for a reupload

Is it possible to backup the title of each video into a text file?

**Comment by dirkf** [comment]
Use `-e`/`--get-title` option and redirect to the text file (`>titles.txt` in Windows `cmd` or POSIX shell):
```
youtube-dl -e PL8BCB4981DD1A0108
Lecture 1 | New Revolutions in Particle Physics: Standard Model
Lecture 2 | New Revolutions in Particle Physics: Standard Model
Lecture 4 | New Revolutions in Particle Physics: Standard Model
Lecture 5 | New Revolutions in Particle Physics: Standard Model
Lecture 6 | New Revolutions in Particle Physics: Standard Model
Lecture 7 | New Revolutions in Particle Physics: Standard Model
Lecture 8 | New Revolutions in Particle Physics: Standard Model
Lecture 9 | New Revolutions in Particle Physics: Standard Model
Lecture 10 | New Revolutions in Particle Physics: Standard Model
$ 
```

**Comment by LOKSTED** [comment]
@dirkf Sorry but what exactly would you type to redirect it to the text file? I would copy paste it but I about 50 playlists. Thank you

I tried youtube-dl -e PL8BCB4981DD1A0108 -o titles.txt but the file never generated

**Comment by dirkf** [comment]
`-o` is just for the media file. Instead:
```
youtube-dl -e PL8BCB4981DD1A0108 > titles.txt
```
The redirect operator `>` is nothing to do with yt-dl; instead it's a feature of the command-line shell that you're using, whether [Windows `cmd`](https://ss64.com/nt/syntax-redirection.html) or a [POSIX shell](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_07). Other command-line shells may use a different syntax, eg Windows [PowerShell](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_07).

**Comment by LOKSTED** [comment]
@dirkf That worked. Thank you very much
This is not related to ytdl anymore but the output txt doesn't display foreign languages either. I'm just asking incase you know the fix on top of your head but if you don't, don't worry about it I'll try my luck on Google

**Comment by pukkandan** [comment]
Assuming windows cmd, running `chcp 65001` before the youtube-dl command will partially fix it

**Comment by dirkf** [comment]
That enables UTF-8 in `cmd` which would indeed be helpful. How long until it's the default?

**Comment by pukkandan** [comment]
codepage 65001 is not exactly UTF-8, but is the closest one to it. I doubt it will ever be the default for cmd due to compatibility issues. But Windows Terminal defaults to utf-8 afaik

**Comment by pukkandan** [comment]
Apparently, it can be enabled globally now: https://superuser.com/a/1435645/693700
