### ISSUE TITLE
Continue downloading the playlist, where it stopped downloading last time for whatever reason.

### ISSUE THREAD

**Issue by dmiraj** [ytdl-org/youtube-dl#30584]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

## Description

When downloading music from youtube. Ffmpeg will convert the videos to audio if asked. It would be better, if youtube-dl skipped the audio files converted, in a next attempt to download from the playlist.

**Comment by dirkf** [comment]
Use either `-k`/`--keep-video` to leave the downloaded item from which the audio was extracted, or `--download-archive` to record the extractor/id combinations that have been downloaded and skip them in future.

In either case use something like `-f  'bestaudio/best'` to avoid downloading video-only media from which no audio could ever be extracted.

**Comment by Lee-Carre** [comment]
Use the `--download-archive FILE` option (as described in the [ReadMe](ytdl-org/youtube-dl/blob/master/README.md)), which is intended for the desired behaviour described by the OP. Nothing will be downloaded, even if the original (media) files have since been deleted.

**Comment by dmiraj** [comment]
Thank you.
