### ISSUE TITLE
How to contribute towards documentation?

### ISSUE THREAD

**Issue by NathanDen** [ytdl-org/youtube-dl#30586]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I am a recent youtube-dl user, and in my (short) experience so far, I have found the documentation to be extensive, comprehensive and overwhelming. I read around the internet for various guides and tried out a few of them, but individually, none of them were perfect. Only collectively were they even close to helping me do what I needed. 

Thus, I'd like to write a quick start guide for youtube-dl so that other new and/or impatient users (who may be not be tech-savvy) will have a quicker and easier time than me. If approved, the guide will start with basics of downloading a single vid, then from a playlist, then file conversions. It will also inform users of how to install ffmpeg and ytdl for a quick-start experience.

**Comment by garoto** [comment]
No one ever reads official docs and/or FAQs whatsoever, more peculiarly so for CLI programs.

**Comment by 89z** [comment]
Please dont listen to @garoto. He seems to think he speaks for everyone, when really he only speaks for himself.

**Comment by NathanDen** [comment]
While probably more true than not, I'm sure there's at least a few people who'd attempt to ctrl f things, which is where i hope to come in. For me personally, I am not yet at a stage whereby I need ytdl's more powerful features so a quick start guide would have been the limited extent of what i needed. 

Thus, I hope that I can create a quick start guide that would be placed somewhere accessible for people who are like me, so they don't need to read documentation, especially on a CLI app, that is not relevant to their usage.

**Comment by garoto** [comment]
> He seems to think he speaks for everyone, when really he only speaks for himself.

No shit Sherlock. Do I look like the official account for some org?

**Comment by 89z** [comment]
> No shit Sherlock. Does it look like I write on behalf of anyone else?

@garoto let me go ahead and quote you back to you:

> No one ever reads official docs and/or FAQs whatsoever, more peculiarly so for CLI programs.

When you say stuff like "No one ever...", thats you speaking for everyone. Maybe dont do that.

**Comment by garoto** [comment]
> When you say stuff like "No one ever..." [...]

You sound very pedantic.

**Comment by dirkf** [comment]
The aim should be that the program does the right thing for new users while allowing experienced users to tweak its behaviour. I can't help thinking that there is already quite a lot of documentation as OP says, and we should devote effort to making it more cogent or less necessary rather than adding to it.

@NathanDen, would you like to explain the problems you had with the program that caused you to need the documentation? That might point to possible improvements.

**Comment by rautamiekka** [comment]
> > When you say stuff like "No one ever..." [...]
> 
> You sound very pedantic.

Trolls have no rights.

**Comment by Lee-Carre** [comment]
@NathanDen

The simplest answer is to fork the repository and submit a pull request with your changes.

Though, as @dirkf advises; since this is a usability / user-experience matter, discussion of the difficulties encountered, to determine how to remedy them, would be wise.

**Comment by pspiagicw** [comment]
Is the documentation done ? @NathanDen
