### ISSUE TITLE
any solution for tiktok

### ISSUE THREAD

**Issue by heyhowRyou** [ytdl-org/youtube-dl#30580]
any solution for tiktok?

**Comment by dirkf** [comment]
[This](https://github.com/ytdl-org/youtube-dl/issues/30454#issuecomment-1020274674), even if it works isn't a proper solution.

For the moment, PR #30479 and [this](https://github.com/ytdl-org/youtube-dl/issues/30251#issuecomment-1026177294) should work.

**Comment by OracleToes** [comment]
> [This](https://github.com/ytdl-org/youtube-dl/issues/30454#issuecomment-1020274674), even if it works, isn't a proper solution.
> 
> For the moment, PR #30479 and [this](https://github.com/ytdl-org/youtube-dl/issues/30251#issuecomment-1026177294) should work.

I installed your patch and used the iphone user-agent, but I still get an Unable to Extract data
[tmp.txt](https://github.com/ytdl-org/youtube-dl/files/8010093/tmp.txt)
attached is the verbose output

**Comment by 89z** [comment]
I have an alternate tool that works:

~~~
PS C:\> tiktok 7060620820569394478
GET http://api2.musical.ly/aweme/v1/aweme/detail/?aweme_id=7060620820569394478
GET http://v16m-default.akamaized.net/be28ab040a7ad4b307a11ff2fc0efbea/6200256e/video/tos/maliva/tos-maliva-ve-0068c799-us/c6a984259e1445bbb04d3671ed68f67a/
~~~

https://github.com/89z/mech

**Comment by dirkf** [comment]
yt-dlp succeeds using its 'video feed' tactic after failing 5 times to get the 'video details'.

More research needed.

**Comment by protrolium** [comment]
it works after four attempts using [this](https://github.com/ytdl-org/youtube-dl/issues/30251#issuecomment-1026177294) link which spoofs the agent via @OracleToes. very strange.

**Comment by 89z** [comment]
If you use the `api2.musical.ly` instead of the main site, then you dont have to worry about parsing HTML or JavaScript.

https://github.com/89z/mech/blob/v1.46.7/tiktok/tiktok.go#L32-L38

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30470

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30546

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30439

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30445

**Comment by MinePlayersPE** [comment]
For some reason, the API host yt-dlp uses now has the same non-restrictions as `api2.musical.ly` (no more retries, and this seems to also affect every API host TikTok has?), so using it is now a viable (albeit fairly unstable) option

**Comment by dirkf** [comment]
Does anyone understand the status of the various TT APIs?

Is it the case the the musical.ly API, or any other, is baked into some never-to-be-updated mobile app and so can't easily be withdrawn in the short-term (see YT Android client)?

**Comment by MinePlayersPE** [comment]
@dirkf Kinda? For -dlp, we were definitely not using the "right" method so it didn't matter, but the real version we found to work with without more tinkering (i.e. device registration and request signing) was a really old version

**Comment by 0xAhmad** [comment]
The problem with Tiktok is when you use the address that is generated from the app. If you copy the address and open it in the browser, it will redirect you to another address that contains the username and the video ID. YT-DL will succeed if you used this address without even fiddling with user agent. If you are using the python YT-DL library, you can do the same thing by using the requests library to get the final address as follows:
```python
import requests
tturl = 'https://vm.tiktok.com/TTPdBHM9qH/'
new_tturl = requests.head(tturl, allow_redirects=True).url
result = ydl.extract_info(new_tturl, download=False)
```

**Comment by heyhowRyou** [comment]
> The problem with Tiktok is when you use the address that is generated from the app. If you copy the address and open it in the browser, it will redirect you to another address that contains the username and the video id. YT-DL will succeed if you used this address without even fiddling with user agent. If you are using the python YT-DL library, you can do the same thing by using the requests library to get the final address as follows:
> 
> ```python
> import requests
> tturl = 'https://vm.tiktok.com/TTPdBHM9qH/'
> new_tturl = requests.head(tturl, allow_redirects=True).url
> result = ydl.extract_info(new_tturl, download=False)
> ```
> 
> BTW I'm using [Youtube-DLP](https://github.com/yt-dlp/yt-dlp)

Youtube-DLP works very well, the only problem is Youtube-DLP downloads the videos in HEVC format but not h264.

**Comment by dirkf** [comment]
> YT-DL will succeed if you used this address without even fiddling with user agent.

I don't find that.

@heyhowRyou, please raise your problem on the yt-dlp issue tracker, if you can't fix it by excluding the unwanted formats (`-f '(bestvideo+bestaudio/best)[vcodec?!*=hevc]` or similar).
