### ISSUE TITLE
Select low bitrate plus file extension and destination folder for CTS

### ISSUE THREAD

**Issue by Bluebuster116** [ytdl-org/youtube-dl#30591]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

Hello I am trying to record the following stream from CTS News from Taiwan

The only line which I could understand from the documentation is

youtube.dl https://www.youtube.com/watch?v=yUTy1U1wTwE

But how do I tell youtube-dl to select not the best quality but instead let's say 240p and to save it in my directory i.e.

C:\Users\Mycomputer\Documents\record

Is it possible that the file extension for this recording to be mp4?. It seems that the file extension might be .ts but can this be encoded or changed to mp4 or maybe mkv instead?. Can you savvy guys help me here please?. I'm on a Windows 7 laptop so it would be nice to type a windows command for that youtube-dl.

**Comment by dirkf** [comment]
youtube-dl is a command-line program so you need to be in, eg, a `cmd` session (eg Start>Run and type `cmd.exe`). For this page you will probably also need the program _ffmpeg_ to be installed too.

Set the current directory (nothing to do with yt-dl, but saves having to specify the output directory):
```
cd C:\Users\Mycomputer\Documents\record
```
List the available formats (240p, say):
```
youtube-dl -F "https://www.youtube.com/watch?v=yUTy1U1wTwE"
```
You'll see output including this, which shows that the available formats combine video and audio:
```
[info] Available formats for yUTy1U1wTwE:
format code  extension  resolution note
91           mp4        256x144     290k , avc1.42c00b, 15.0fps, mp4a.40.5
92           mp4        426x240     546k , avc1.4d4015, 30.0fps, mp4a.40.5
93           mp4        640x360    1209k , avc1.4d401e, 30.0fps, mp4a.40.2
94           mp4        854x480    1568k , avc1.4d401f, 30.0fps, mp4a.40.2
95           mp4        1280x720   2969k , avc1.4d401f, 30.0fps, mp4a.40.2
96           mp4        1920x1080  5420k , avc1.640028, 30.0fps, mp4a.40.2 (best)
```
Select the format you want (say `92` = 240p):
```
youtube-dl -f 92 "https://www.youtube.com/watch?v=yUTy1U1wTwE"
```
Enjoy your archived media file `華視新聞 24 小時直播 _ Taiwan CTS News Live _ 台湾 CTS ニュース 生放送   @華視新聞 CH52 2022-02-02 23_04-yUTy1U1wTwE.mp4`.

Once you're happy with that, here are some more complicated examples.

To get a 240p or smaller version of a media item that may be provided as either separate or combined video and audio streams:
```
youtube-dl -f "bestvideo[height<=240]+bestaudio/best[height<=240]" "https://www.youtube.com/watch?v=yUTy1U1wTwE"
```
To get a 240p or smaller version of a media item that may be provided as either separate or combined video and audio streams, or the best other separate or combined format if that isn't available:
```
youtube-dl -f "bestvideo[height<=240]+bestaudio/best[height<=240]/bestvideo+bestaudio/best" "https://www.youtube.com/watch?v=yUTy1U1wTwE"
```
The [Format Selection section of the Fine Manual](https://github.com/ytdl-org/youtube-dl#users-content-format-selection) explains this.

For use on non-Windows systems (or POSIX command-line shells in general), change "..." to '...'.

**Comment by rautamiekka** [comment]
Usually you don't need to bother with the format codes, as the other format options should be good enough for most.

**Comment by Bluebuster116** [comment]
@dirkf

I am still confused, how do I tell youtube-dl that I want my recording to be saved on the directory of my choice (which I mentioned above)? This part it isn't very clear, can you write down an example for this please?.

The second part which I can see a file with a mp4 extension it isn't very clear as well.
I mean, from what I understood reading your answer is that youtube-dl will automatically generate a file as mp4 and will label it with the default name given by youtube. Am I understanding this part correctly?.

Then what If I want to change that name because is too long?, let's say example.mp4?

Again, I am just confused on how to specify the output directory. Why did you said it has nothing to do with yt-dl?. Does that mean that it isn't required to be part of the code?. Can you show an example?.

Btw, thank you for your first response. I do also use ffmpeg so its intalled on my laptop, not sure if its the latest version though. Will that matter?.

By the way, what's the latest portable version of yt-dl for a Windows 7 computer?. Can you share the link?.

I appreciate you do reply to my questions. Sorry but I am still a novice in these things.

**Comment by dirkf** [comment]
To manipulate the output filename, use the `-o`/`--output` option.

Read about it [here](https://github.com/ytdl-org/youtube-dl#user-content-output-template).

The parameter of the option is a template like this (in Windows _cmd_, enclose it in ""):
```
%(title)s-%(id)s.%(ext)s
```
The template contains plain text (like "-") and template fields ("%(field_name)s"). Above is the default. `ext` is the field that gets set to `mp4`, or whatever is suitable for the extracted file.

So instead of just running the program in your chosen  directory, you could use this option:
```
-o "C:\Users\Mycomputer\Documents\record\%(title)s-%(id)s.%(ext)s"
```
The program will complain about some versions of _ffmpeg_ but any recent one should be fine. Run `ffmpeg -version` to find out which you have.

Check the [release page](https://github.com/ytdl-org/youtube-dl/releases) for a new yt-dl version that should appear soon; I believe that the Windows `youtube-dl.exe` works on at least Windows 7.
