### ISSUE TITLE
Some tv2lorry.dk links fail to extract kaltura id

### ISSUE THREAD

**Issue by owiecc** [ytdl-org/youtube-dl#30593]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.tv2lorry.dk/gadekamp/gadekamp-6-hoejhuse-i-koebenhavn']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.1 (CPython) - macOS-12.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[TV2DK] gadekamp: Downloading webpage
ERROR: Unable to extract kaltura id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/tv2dk.py", line 93, in _real_extract
    kaltura_id = self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract kaltura id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
## Description
Some of the www.tv2lorry.dk links fail to download with this error message: 
```
ERROR: Unable to extract kaltura id;
```

https://www.tv2lorry.dk/gadekamp/gadekamp-oerestad works ok
https://www.tv2lorry.dk/gadekamp/gadekamp-6-hoejhuse-i-koebenhavn does not work

**Comment by dirkf** [comment]
The problem page has apparently been produced using the Nuxt.js framework, and the JS that is assigned to `window.__NUXT__` has to be analysed to extract any media.

**But**, as in the [problem NZZ page here](https://github.com/ytdl-org/youtube-dl/issues/30466#issuecomment-1005470371), the JS has this form, where N is a large number ~ 100s:
```
function (arg1, ...,. argN) { /*assignments */; return {/* possibly useful data but including variable references*/ };}(binding1, ..., bindingN));
```
This breaks the `js_to_json()` transformation as currently implemented.

An initial strategy for this could be, as I considered for the NZZ page:
* new version of `js_to_json()` that finds the variable references and tags them in some way
* make a binding dict with keys arg1...argN and values binding1...bindingN
* traverse the Pythonified JSON, finding and replacing each tagged arg with its binding.

This could work so long as there aren't expressions and local vars in the function body (there aren't).

Another approach could be to improve JSInterp to be able to evaluate the assigned value.

Or, as with the NZZ page, it may be possible to bypass the evaluation using assumptions and secret knowledge.

Here, a fragment of interest is `kaltura:{entry_id:bU,carrier_id:a,partner_id:bs,reference_id:bV,parent_reference_id:a,stream_url:bW,playlist_url:bX}`, which is in the `data[0].page.resource.video` member of the object returned by the JS.

The extractor needs the Kaltura ID and the Partner ID. The JS can be evaluated using browser tools, to reveal that these are bU = '1_7iwll9n0'  and bs = '2045321'. So, as long as the page structure stays the same:
* the Kaltura ID can be found in the binding list by matching `r'"kaltura"\s*,\s*"(\w+)"'`
* the Partner ID can be found in the binding list by matching `r'"uploaded"\s*,\s*"(\w+)"'`.

Or this target might give both after suitable escaping:
"http:\u002F\u002Fcdnapi.kaltura.com\u002Fp\u002F2045321\u002Fsp\u002F204532100\u002FplayManifest\u002FentryId\u002F1_7iwll9n0\u002Fformat\u002Furl\u002Fprotocol\u002Fhttp"

In fact the extractor is already getting the Partner ID from a string like this, so join the club:
```
--- new/youtube-dl/youtube_dl/extractor/tv2dk.py
+++ new/youtube-dl/youtube_dl/extractor/tv2dk.py
@@ -91,7 +91,8 @@
             add_entry(partner_id, kaltura_id)
         if not entries:
             kaltura_id = self._search_regex(
-                r'entry_id\s*:\s*["\']([0-9a-z_]+)', webpage, 'kaltura id')
+                (r'entry_id\s*:\s*["\']([0-9a-z_]+)',
+                 r'\\u002FentryId\\u002F(\w+)\\u002F'), webpage, 'kaltura id')
             partner_id = self._search_regex(
                 (r'\\u002Fp\\u002F(\d+)\\u002F', r'/p/(\d+)/'), webpage,
                 'partner id')
```
Bingo:
```
$ python -m youtube_dl --ignore-config -F -v 'https://www.tv2lorry.dk/gadekamp/gadekamp-6-hoejhuse-i-koebenhavn'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-config', u'-F', u'-v', u'https://www.tv2lorry.dk/gadekamp/gadekamp-6-hoejhuse-i-koebenhavn']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: a3373da70
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[TV2DK] gadekamp: Downloading webpage
[download] Downloading playlist: None
[TV2DK] playlist None: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[Kaltura] 1_7iwll9n0: Downloading video info JSON
[Kaltura] 1_7iwll9n0: Checking mp4-6150 URL
[Kaltura] 1_7iwll9n0: Downloading m3u8 information
[info] Available formats for 1_7iwll9n0:
format code  extension  resolution note
mp4-467      mp4        640x360     467k , isom container, avc1, 25fps, ~50.14MiB
hls-507      mp4        640x360     507k 
webm-825     webm       640x360     825k , mp42 container, v_vp8, 25fps, ~88.59MiB
mp4-942      mp4        960x540     942k , isom container, avc1, 25fps, ~101.17MiB
hls-1004     mp4        960x540    1004k 
mp4-1501     mp4        1280x720   1501k , isom container, avc1, 25fps, ~161.11MiB
hls-1589     mp4        1280x720   1589k 
mp4-2118     mp4        1280x720   2118k , isom container, avc1, 25fps, ~227.27MiB
mp4-3921     mp4        1920x1080  3921k , isom container, avc1, 25fps, ~420.78MiB
mp4-6150     mp4        1920x1080  6150k , mp42 container, avc1, 25fps, ~659.92MiB (best)
[download] Finished downloading playlist: None
$
```
The extractor could also acquire the typical logic that returns a 1-item playlist as a single video, so getting rid of the playlist-related diagnostics.

**Comment by dirkf** [comment]
Also, I'm fascinated to know about "Lorryland" (as well as [Copenhagen's new "skyscrapers"](https://www.carlsbergbyen.dk/tilsalg/ejendomme/pasteurs-tarn)).

**Comment by owiecc** [comment]
That was fast, thanks a lot! What about Lorryland would you like to know? Hit me up on twitter.

**Comment by dirkf** [comment]
Where, what, etc. The name only seems to come up in connection with this branch of TV2DK. Obvs not a car park outside Esbjerg for trucks waiting for the ferry.

**Comment by dirkf** [comment]
Mange tak!

I've certainly been to F.berg but never heard of det gamle Lorry.
