### ISSUE TITLE
Viki.com not working

### ISSUE THREAD

**Issue by Danilo016** [ytdl-org/youtube-dl#30592]
Youtube-DL (and -DLP) used to work for Viki.com until a few days ago.

Verbose log from Youtube-DL:
[debug] System config: [][debug] User config: [][debug] Custom config: [][debug] Command-line args: ['--verbose', '--cookies', 'viki.txt', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.viki.com/videos/1127339v'][debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252[debug] youtube-dl version 2021.12.17[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041[debug] exe versions: ffmpeg 2022-01-13-git-c936c319bd-essentials_build-www.gyan.dev[debug] Proxy map: {}[viki] Logging inERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpageFile "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopenFile "C:\Python\Python34\lib\urllib\request.py", line 470, in openFile "C:\Python\Python34\lib\urllib\request.py", line 580, in http_responseFile "C:\Python\Python34\lib\urllib\request.py", line 508, in errorFile "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chainFile "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

Verbose log from Youtube-DLP:
[debug] Command-line config: ['--verbose', '--cookies', 'viki.txt', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.viki.com/videos/1127339v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2022-01-13-git-c936c319bd-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[viki] Logging in
WARNING: [viki] Unable to download JSON metadata: HTTP Error 404: Not Found
WARNING: [viki] Login Failed: Unable to get session token
[debug] [viki] Extracting URL: https://www.viki.com/videos/1127339v
[viki] 1127339v: Downloading video JSON
[viki] 1127339v: Downloading video streams JSON
ERROR: [viki] 1127339v: viki said: Bad request
File "yt_dlp\extractor\common.py", line 612, in extract
File "yt_dlp\extractor\viki.py", line 255, in _real_extract
File "yt_dlp\extractor\viki.py", line 78, in _call_api
File "yt_dlp\extractor\viki.py", line 86, in _raise_error

**Comment by nyuszika7h** [comment]
This is already fixed in yt-dlp 2021.02.03 (yt-dlp/yt-dlp#2540). The code here is a bit different so the rest of the changes would probably have to be backported as well to fix it.
