### ISSUE TITLE
YouTubeDL not found

### ISSUE THREAD

**Issue by NeutronSun** [ytdl-org/youtube-dl#30590]
## Checklist
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
I just cant understand what is happening, i tried to uninstall and reinstalling it and it didnt work.
It cant find the attributes YouTubeDL in youtube_dl
![image](https://user-images.githubusercontent.com/72988879/152228511-300af19a-ba68-4678-b272-4da4ba6dc170.png)

**Comment by dirkf** [comment]
`YoutubeDL`, not `YouTubeDL`

That should have been your first guess.
