### ISSUE TITLE
youtube-dl option to check on running download

### ISSUE THREAD

**Issue by gl86** [ytdl-org/youtube-dl#30597]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hi, i am looking for the correct option if exist to check on running downloads. I use youtube-dl on headless machine that is accessed via terminal window.  When it is accidently closed i can not see the current running download status.
thanks

**Comment by dirkf** [comment]
If you typed a yt-dl command into the terminal window and then closed the window while the command was running, yt-dl was probably closed as well.

[This](https://danmackinlay.name/notebook/terminal_session_management.html) may be helpful.

**Comment by gl86** [comment]
i understand thanks

**Comment by dirkf** [comment]
If you have a follow-up question, re-open the issue.

**Comment by Lee-Carre** [comment]
@gl86

You could redirect youtube-dl's `stdout` to a file, and then run `tail` on that file.

Else, build (or find) a wrapper around youtube-dl to handle the remote status interrogation you seek.
