### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by nIKsL** [ytdl-org/youtube-dl#30605]
Debian 10

I make file (~/.config/youtube-dl/config) with my configuration - and yt-dlp don`t use it :( (yt-dlp "youtubeURL")
After that I make file (/etc/youtube-dl.conf) with same configuration - yt-dlp don`t use it again :(

when i use yt-dlp with key "yt-dlp youtubeURL --config-location ~/.config/youtube-dl/config" - all going ok
Is it some error ? Should yt-dlp work with config on default path ??? or I should use it everytime with key --config-location???

**Comment by MuenchenSued** [comment]
The correct path for yt-dlp is ~/.config/yt-dlp/config

**Comment by nIKsL** [comment]
> The correct path for yt-dlp is ~/.config/yt-dlp/config

thanks a lot - that's worked.
[https://github.com/ytdl-org/youtube-dl#configuration](https://github.com/ytdl-org/youtube-dl#configuration) - in this section of readme we have wrong information...

**Comment by MuenchenSued** [comment]
You are looking in the description of the wrong program, youtube-dl is not yt-dlp.
See https://github.com/yt-dlp/yt-dlp#configuration
