### ISSUE TITLE
www.alsace20.tv site support

### ISSUE THREAD

**Issue by Shnoulle** [ytdl-org/youtube-dl#30603]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.alsace20.tv/VOD/Actu/JT/Votre-JT-jeudi-3-fevrier-lyNHCXpYJh.html
- Single video (embedded): https://www.alsace20.tv/emb/lyNHCXpYJh

## Description
Just testing 

```
$ youtube-dl https://www.alsace20.tv/VOD/Actu/JT/Votre-JT-jeudi-3-fevrier-lyNHCXpYJh.html
[generic] Votre-JT-jeudi-3-fevrier-lyNHCXpYJh: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Votre-JT-jeudi-3-fevrier-lyNHCXpYJh: Downloading webpage
[generic] Votre-JT-jeudi-3-fevrier-lyNHCXpYJh: Extracting information
ERROR: Unsupported URL: https://www.alsace20.tv/VOD/Actu/JT/Votre-JT-jeudi-3-fevrier-lyNHCXpYJh.html
$ youtube-dl https://www.alsace20.tv/emb/lyNHCXpYJh
[generic] lyNHCXpYJh: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lyNHCXpYJh: Downloading webpage
[generic] lyNHCXpYJh: Extracting information
ERROR: Unsupported URL: https://www.alsace20.tv/emb/lyNHCXpYJh
```

Lot of link like this in console: 

```
https://alsace20.vod-kd.com/vod/alsace20/smil:220203_JT/default.smil/segment_ctvideo_ridp0va0br985062_cs1890000_w1998644956_mpd.m4s
https://alsace20.vod-kd.com/vod/alsace20/smil:220203_JT/default.smil/segment_ctvideo_ridp0va0br985062_cs1890000_w1998644956_mpd.m4s
…
```

Thank you :)

**Comment by dirkf** [comment]
So the main thing is that JSON metadata including media links is found at `https://www.alsace20.tv/visionneuse/visio_v9_js.php?key=%s&habillage=0&mode=html' % video_id`. Unfortunately some interesting additional metadata (description, duration) is only in the web page itself and not in the embed page, so these fields aren't extracted for an embed page:

Then the example page, video_id `lyNHCXpYJh`:
```
$ python -m youtube_dl -v -F 'https://www.alsace20.tv/VOD/Actu/JT/Votre-JT-jeudi-3-fevrier-lyNHCXpYJh.html'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.alsace20.tv/VOD/Actu/JT/Votre-JT-jeudi-3-fevrier-lyNHCXpYJh.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 734dfbb4e
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[Alsace20TV] lyNHCXpYJh: Downloading JSON metadata
[Alsace20TV] lyNHCXpYJh: Downloading MPD manifest
[Alsace20TV] lyNHCXpYJh: Downloading MPD manifest
[Alsace20TV] lyNHCXpYJh: Downloading MPD manifest
[Alsace20TV] lyNHCXpYJh: Downloading webpage
[info] Available formats for lyNHCXpYJh:
format code         extension  resolution note
auto-p0aa0br64001   m4a        audio only [eng] DASH audio   64k , m4a_dash container, mp4a.40.5 (48000Hz)
low-p0aa0br64001    m4a        audio only [eng] DASH audio   64k , m4a_dash container, mp4a.40.5 (48000Hz)
med-p0aa0br64001    m4a        audio only [eng] DASH audio   64k , m4a_dash container, mp4a.40.5 (48000Hz)
auto-p0aa0br96004   m4a        audio only [eng] DASH audio   96k , m4a_dash container, mp4a.40.2 (48000Hz)
auto-p0va0br269644  mp4        480x270    DASH video  269k , mp4_dash container, avc1.42c015, 25fps, video only
low-p0va0br269644   mp4        480x270    DASH video  269k , mp4_dash container, avc1.42c015, 25fps, video only
auto-p0va0br610270  mp4        640x360    DASH video  610k , mp4_dash container, avc1.42c01e, 25fps, video only
med-p0va0br610270   mp4        640x360    DASH video  610k , mp4_dash container, avc1.42c01e, 25fps, video only
auto-p0va0br985062  mp4        1280x720   DASH video  985k , mp4_dash container, avc1.4d401f, 25fps, video only (best)
$
```
If I make a draft PR for the Alsace20TV extractors, would you be able to test them on some other pages?

**Comment by Shnoulle** [comment]
> If I make a draft PR for the Alsace20TV extractors, would you be able to test them on some other pages?

yes :)

**Comment by dirkf** [comment]
As linked above.

**Comment by Shnoulle** [comment]
> As linked above.

checked : 

- [x]  https://www.alsace20.tv/VOD/Actu/JT/Votre-JT-jeudi-3-fevrier-lyNHCXpYJh.html
- [x]  https://www.alsace20.tv/VOD/Actu/Choix-de-la-redac/Alors-que-deploiement-reseau-5G-poursuit-effets-cette-technologie-sur-sante-soulevent-encore-inquietudes-questionnements-ISA6DyXwdy.html
- [x]  https://www.alsace20.tv/VOD/Actu/M2A/Un-vaccibus-sillonne-agglomeration-mulhousienne-Ls5ez8QoQv.html
- [x] https://www.alsace20.tv/VOD/Magazines/Club-1906/CLUB1906-Match-nul-Racing-Club-Strasbourg-face-Monaco-1-1-20YGTQfCM3.html

**Comment by dirkf** [comment]
Great, I'll call that good to go, then
