### ISSUE TITLE
Is youtube-dl capable of scraping 360/VR video posted to YouTube?

### ISSUE THREAD

**Issue by brianperlman** [ytdl-org/youtube-dl#30600]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is youtube-dl capable of scraping all the data from a 360/VR video posted on YouTube? I tried but was only able to download the forward-looking angle that is originally viewed on YouTube before panning around. Thanks in advance!

**Comment by 89z** [comment]
please provide example URL

**Comment by brianperlman** [comment]
> please provide example URL

https://www.youtube.com/watch?v=Vet7DyfozJA

**Comment by 89z** [comment]
As an example, is this what you are wanting?

https://rr2---sn-q4flrn7y.googlevideo.com/videoplayback?expire=1644036515&ei=Q639Yd3-Nsyylu8PhtS04Aw&ip=72.181.23.38&id=o-APvzAoEosZTPxU5BleGciNv1D2ma-SCcxhfrheYAD582&itag=247&source=youtube&requiressl=yes&mh=b2&mm=31%2C26&mn=sn-q4flrn7y%2Csn-5ualdn76&ms=au%2Conr&mv=m&mvi=2&pl=15&initcwndbps=2095000&vprv=1&mime=video%2Fwebm&gir=yes&clen=10764327&dur=80.579&lmt=1641061474855935&mt=1644014222&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6216224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgXR20OwmCopll9Fwz35YLP_QszVA1rYOR_9qZJYGfO10CIQDPEykWXEnH1IwgUA73IBEgR0tvF7yB5Yz7WFRvpMZBUg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgTKzeOOs6l1X-k3_LHY-uxHm0mgnktbn8ihTsOsopEQECICstIweZsL-0rvkrUoO44nSF2cnqJ1EBb3oFfRrY7Ew1

**Comment by brianperlman** [comment]
Yes, how did you do that?

**Comment by 89z** [comment]
Thats just `adaptiveFormat` 247, you should be able to request it with YouTube-DL

**Comment by brianperlman** [comment]
Works like a charm. Thanks for your quick response!
