### ISSUE TITLE
streamsb.com

### ISSUE THREAD

**Issue by 3xploitzer0** [ytdl-org/youtube-dl#30607]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

https://streamsb.com/

**Comment by dirkf** [comment]
You need to provide URLs of actual site pages from which media file(s) might be retrieved.

**Comment by bubundas17** [comment]
https://sbplay2.com/e/busr4f6rkxpz
Here you go.
@dirkf

**Comment by dirkf** [comment]
This site deploys anti-debugging hacks and it needs a bit of work to bypass them.

**Comment by bubundas17** [comment]
Here are some known domains for streamsb
sbplay2.com
viewsb.com

Will add more known domains.

**Comment by ismozz** [comment]
Streamsb search engine & finder: https://www.ismoz.com/video-upload-sites/streamsb/

**Comment by 89z** [comment]
@dirkf what do you mean by that? I may have a workaround

**Comment by dirkf** [comment]
Off-hand I don't recall, but something like including `debugger;` in a watchdog function that breaks when dev tools are open; not unbreakable, but irritating.

**Comment by 89z** [comment]
Looks like the HLS is in the response from this:

https://viewsb.com/sources43/46486a7632546b66516232617c7c647866766c753471616e6a787c7c6634324277787530516f794e7c7c73747265616d7362/31644c454e777534755530787c7c373634623635363337353661333837323738353435373332376337633731343334323666333337393436333735383533373833393763376333393330343437353639363533363431353633363636346137633763373337343732363536313664373336327c7c7632686f44305042555333537c7c73747265616d7362

but it seems you may have already discovered, that the URL is generated by JavaScript.

**Comment by 89z** [comment]
I think I figured it out. Here is an implementation:

~~~go
package streamsb

import (
   "bytes"
   "encoding/hex"
)

func Address(id string) string {
   var (
      in bytes.Buffer
      out bytes.Buffer
   )
   in.WriteString("||")
   in.WriteString(id)
   in.WriteString("||||streamsb")
   out.WriteString("https://viewsb.com/sources43/")
   out.WriteString(hex.EncodeToString(in.Bytes()))
   out.WriteByte('/')
   return out.String()
}
~~~

With this URL:

https://viewsb.com/e/dxfvlu4qanjx

if you give the function this input:

~~~
dxfvlu4qanjx
~~~

you get this output:

https://viewsb.com/sources43/7c7c647866766c753471616e6a787c7c7c7c73747265616d7362/

**Comment by vallerydelexy** [comment]
another streamsb domain https://sbanh.com/

**Comment by MeteorsLiu** [comment]
> Off-hand I don't recall, but something like including `debugger;` in a watchdog function that breaks when dev tools are open; not unbreakable, but irritating.

There is a trick to skip that debugger.

1. Stop the breakpoint when "debugger;" is triggered, and click continue to execute.
2. If it's no working, start the breakpoint and stop it again.
It may helps.

And I really want that ytdl could support streamsb.com, which is a useful video website.

**Comment by fonkap** [comment]
I cannot find a sbplay2 example. If someone has some links to this or other sites it should be easy to add support for them.

**Comment by fonkap** [comment]
Reversing this site was a blast, if you know of similar obfuscated sites I'd love to try them.

**Comment by ayunami2000** [comment]
> Reversing this site was a blast, if you know of similar obfuscated sites I'd love to try them.

I got one but unfortunately I already reversed it, see what I've done: https://glitch.com/edit/#!/vidcloud-dl

**Comment by dirkf** [comment]
If you're offering code that yt-dl could use under Unlicense, please post it with a release statement. The linked page shows blank for me. Perhaps one has to enable JS for www.google.com?

**Comment by ayunami2000** [comment]
Unfortunately, it's node-specific code, but it's not too complex. It's basically obfuscated CryptoJS. I'll open source this version and the one I made years ago for an older version of the site when I get a chance.

**Comment by MeteorsLiu** [comment]
> Unfortunately, it's node-specific code, but it's not too complex. It's basically obfuscated CryptoJS. I'll open source this version and the one I made years ago for an older version of the site when I get a chance.

As far as I'm concerned, if you don't want to make it open source, don't comment here.Because it will notice all the people who took part in the issues.

**Comment by ayunami2000** [comment]
> > Unfortunately, it's node-specific code, but it's not too complex. It's basically obfuscated CryptoJS. I'll open source this version and the one I made years ago for an older version of the site when I get a chance.
> 
> As far as I'm concerned, if you don't want to make it open source, don't comment here.Because it will notice all the people who took part in the issues.
> 
> And fonkcap has already finished this job. This issue has already been closed. There's nothing to do.

I just said I would open source it. But, good point about the closed issue, I won't comment after this. For the source check my GitHub acc, I'll get to posting it eventually (hopefully within 24hrs) and it'll show up there. I'll use Unlicense.

**Comment by yogesh3700** [comment]
do anyone know streamsb current domain

**Comment by yogesh3700** [comment]
> another streamsb domain https://sbanh.com/ [nsfw](https://sbanh.com/e/s3er0kpuyldr)

do anyone know streamsb current domain
