### ISSUE TITLE
youtube-dl doesnt respect index parameter in the URL -PLAYLIST Download support

### ISSUE THREAD

**Issue by darvin** [ytdl-org/youtube-dl#30610]
https://www.youtube.com/watch?v=qHh09DnVUaQ&list=PLyiDf91_bTEgnBN0jAvzNbqzrlMGID5WA&index=1
https://www.youtube.com/watch?v=qHh09DnVUaQ&list=PLyiDf91_bTEgnBN0jAvzNbqzrlMGID5WA&index=54

```
for i in $(seq 1 54); do https://www.youtube.com/watch?v=rR8Six9qpcA&list=PLyiDf91_bTEgnBN0jAvzNbqzrlMGID5WA&index=$i ; done
```

doesnt work

**Comment by darvin** [comment]
```
 youtube-dl https://www.youtube.com/watch?v=rR8Six9qpcA&list=PLyiDf91_bTEgnBN0jAvzNbqzrlMGID5WA
```
downloads just first video and quits

**Comment by darvin** [comment]
youtube-dl doesnt respect index parameter in the URL

**Comment by dirkf** [comment]
Duplicate of #30611.
