### ISSUE TITLE
Vimeo 404 error

### ISSUE THREAD

**Issue by ajsb84** [ytdl-org/youtube-dl#30622]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vimeo.com/477957994/2282452868']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22000
[debug] exe versions: ffmpeg N-105323-gdd17c86aa1-20220120, ffprobe N-105323-gdd17c86aa1-20220120
[debug] Proxy map: {}
[vimeo] 2282452868: Downloading webpage
[vimeo] 2282452868: Downloading JSON metadata
[vimeo] 2282452868: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

This video is part of a series of Vimeo videos, all the other videos have downloaded absolutely fine, only this one fails with the 404 error.

**Comment by ajsb84** [comment]
Right so the issue is both the ID/Hash are numeric. I'm not really following what they did to fix it? The whole greedy/not/greedy stuff is going over my head...

**Comment by 89z** [comment]
I have a fix for this now with JWT:

https://github.com/89z/mech/tree/b48dda1d/research/vimeo

However by accident, I also found that you can use a Bearer token instead of JWT, which I think lasts much longer. So I am trying to code that up now.

**Comment by lourou** [comment]
Using the `--cookies` options, I managed to circumvent this bug.

A chrome extension to extract cookies in the correct format:
https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid

**Comment by 89z** [comment]
> Using the `--cookies` options, I managed to circumvent this bug.

@lourou please dont recommend stuff like this, especially when its not needed:

~~~
GET /_rv/jwt HTTP/1.1
Host: vimeo.com
X-Requested-With: XMLHttpRequest

GET /videos/581039021:9603038895?fields=download HTTP/1.1
Host: api.vimeo.com
Authorization: jwt eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQ0MzM5MjAsInVzZXJfaWQiOm51bGwsImFwcF9pZCI6NTg0NzksInNjb3BlcyI6InB1YmxpYyIsInRlYW1fdXNlcl9pZCI6bnVsbH0.Pw0ICsoZOuvvL75K5mI6PbuJAa5YNMg-1NhlPBNtbTM

Name:Original Size:151.549 MB Link:https://player.vimeo.com/progressive_redirect/download/581039021/container/f2b2d19e-44d5-4907-94b7-c69c9db2af1d/f1ee12d3/thursday,_july_29,_2021_bma_evening_video_update%20%28Original%29?expires=1644440255&loc=external&signature=ae7e56541a1caef94026c4bf076a602913e52b294f9900c38fe5c48f5d27b675
Name:HD 1080p Size:183.670 MB Link:https://player.vimeo.com/progressive_redirect/download/581039021/container/f2b2d19e-44d5-4907-94b7-c69c9db2af1d/dd3d0639/thursday,_july_29,_2021_bma_evening_video_update%20%281080p%29.mp4?expires=1644440255&loc=external&signature=12774e1bf7d1f1b4420685804d04cbac6466727f844b3e9c405e8b7616e3101c
Name:SD 540p Size:81.230 MB Link:https://player.vimeo.com/progressive_redirect/download/581039021/container/f2b2d19e-44d5-4907-94b7-c69c9db2af1d/7248713b/thursday,_july_29,_2021_bma_evening_video_update%20%28540p%29.mp4?expires=1644440255&loc=external&signature=461de64ce9d28c26aa749510d829724d4463b4c5a3e57fc3d7c4784b20c27aea
Name:SD 360p Size:41.610 MB Link:https://player.vimeo.com/progressive_redirect/download/581039021/container/f2b2d19e-44d5-4907-94b7-c69c9db2af1d/ded7a2c1/thursday,_july_29,_2021_bma_evening_video_update%20%28360p%29.mp4?expires=1644440255&loc=external&signature=d6b995eb895e7dce986910f21c953c29fed25d704037d78b6b40a5be71cb7e47
Name:HD 720p Size:112.326 MB Link:https://player.vimeo.com/progressive_redirect/download/581039021/container/f2b2d19e-44d5-4907-94b7-c69c9db2af1d/36b397cb/thursday,_july_29,_2021_bma_evening_video_update%20%28720p%29.mp4?expires=1644440255&loc=external&signature=b3f00ce5cb62a2d91a561c3ea83fbc02b2d11eb9269b8533c78c7cd570bc2adb
~~~

**Comment by dirkf** [comment]
Looks like the problem fixed by PR #29698, which I'm sure will get merged as soon as someone get around to it ...

**Comment by 89z** [comment]
I dont think the PR goes far enough, as this is a valid URL as well for the original post:

https://vimeo.com/477957994?embedded=false&source=vimeo_logo&owner=21256249

I think the only robust approach is to add another request to resolve:

http://vimeo.com/api/oembed.json?url=//vimeo.com/477957994/2282452868

then you dont have to parse anything.

**Comment by dirkf** [comment]
On 10/02/2022 02:34, Zombo wrote:
> I dont think the PR goes far enough, as this is a valid URL as well for the
> original post:
>
> https://vimeo.com/477957994?embedded=false&source=vimeo_logo&owner=21256249

"Sorry, we couldn’t find that page"

If you have any valid test URLs that fail with yt-dl because the actual
video id isn't in the URL, please post them in the PR (#29698).

thx
/df

--
London SW6
UK

**Comment by 89z** [comment]
Its weird, it only works if you start from the other URL:

~~~
PS C:\> curl -I -e https://vimeo.com/477957994/2282452868 `
'https://vimeo.com/477957994?owner=21256249&embedded=false&source=vimeo_logo'
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 199768
Server: nginx
Content-Type: text/html; charset=UTF-8
Expires: Thu, 10 Feb 2022 14:02:08 GMT
~~~
