### ISSUE TITLE
Twich vod. Choose format problem

### ISSUE THREAD

**Issue by magorko** [ytdl-org/youtube-dl#30639]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Hello. How can I choose twitch vod quality when downloading ? I can only see the list  but not an option how to choose one. If somebody know the command please let me know the how to download the 720p 60 fps one. Thanks
![image](https://user-images.githubusercontent.com/99360931/153780501-8e120bb2-98db-433f-b640-1816c8d6e51f.png)

**Comment by 89z** [comment]
Use `-f` ...

**Comment by magorko** [comment]
-f anddd ? I want to choose the 720p60 option how to do it ?

**Comment by 89z** [comment]
@magorko read the manual.

**Comment by magorko** [comment]
@89z I already did but on youtube it put a number next to format. But if its twitch vod it doesnt. So I cant choose one.

**Comment by 89z** [comment]
Why do you assume the format must be a number?

**Comment by magorko** [comment]
thats how its works
![image](https://user-images.githubusercontent.com/99360931/153781527-2280ab95-5003-49a7-b66a-a2838b0b0cf1.png)

**Comment by 89z** [comment]
Youve been presented format codes that arent numbers, so why would you still assume that format code must be numbers?

**Comment by magorko** [comment]
Just please answer what the command should look like if I want to download 720p60 . Thats all

**Comment by dirkf** [comment]
Indeed, `-f 720p60` is what's needed.

Format codes (`format_id`) are generally set by the extractor, often from a value used by the site, as with YT above, or if not, or if duplicated, are generated by yt-dl itself when processing the extracted data (`info_dict`).

**Comment by magorko** [comment]
Sooo just: youtube-dl.exe -f 720p60 https://www.twitch.tv/videos/1297056505 ?

**Comment by dirkf** [comment]
Sure.

**Comment by magorko** [comment]
And can i download only dedicated period of the VOD? If so whats the
command ?

Dňa po 14. 2. 2022 o 2:05 dirkf ***@***.***> napísala(a):

**Comment by dirkf** [comment]
Possibly use `-g --get-filename` to get the download link (url) and output filename and then `ffmpeg -ss nn -i url filename`, where nn is the desired start time in the stream (736 or 12:16 or 0:12:16 to start 736s in); eg
```
ffmpeg -ss 736 -i "https://d2vjef5jvl6bfs.cloudfront.net/76b7152560853baa86ef_resttpowered_45515852941_1644774470/720p60/index-dvr.m3u8" "UFC NIGHTTTTTTTTTTTTTTTTTTT-v1297056505.mp4"
```
Add options `-hide_banner -v 24` after `ffmpeg` to make the output quieter.

**Comment by pukkandan** [comment]
Just doing `--external-downloader ffmpeg --external-downloader-args "-ss 736"` should work

**Comment by dirkf** [comment]
I can't recall where in the _ffmpeg_ command line yt-dl puts the options from `--external-downloader-args`. It needs to be before `-i` [to avoid saving and then skipping the 736, or whatever, seconds](https://unix.stackexchange.com/a/388148), although I agree that your suggested options should work too.

**Comment by Lee-Carre** [comment]
> I've looked through the README

Are you *sure*? There's a whole section about it.
