### ISSUE TITLE
module 'youtube_dl' has no attribute 'YoutubeDL'

### ISSUE THREAD

**Issue by XTang685** [ytdl-org/youtube-dl#30636]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I accidentally deleted some related files and now when I run "youtube_dl.YoutubeDL(ydl_opts)", it returns "module 'youtube_dl' has no attribute 'YoutubeDL'". Are there any way to reinstall youtube_dl so I can have every file I need?

**Comment by dirkf** [comment]
Just reinstall the program as you originally did, or otherwise.

**Comment by AndNovAtor** [comment]
As dirkf sayed. If it was installed by python with pip (`python -m pip install ...` / `pip instal ...`) , then run pip again with "extra" flag `--force-reinstall` (from pip "manual": _Before installing a package, will **uninstall it first** if already installed._) or simply
`--ignore-installed` (from pip "manual": _Ignores whether the package and its deps are already installed, **overwriting** installed files_)
