### ISSUE TITLE
Cannot write video metadata to JSON file

### ISSUE THREAD

**Issue by zenom141** [ytdl-org/youtube-dl#30630]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Cannot write video metadata to JSON file. how to handle this? im on ubuntu server. Also i just need video links , i dont want to download video. So in this case how to ignore this?

**Comment by dirkf** [comment]
Please provide verbose (`-v`) log to show what you're doing and how it failed.

The output has to be sent to a directory where the user that yt-dl is running as has write permission.

**Comment by zenom141** [comment]
Hello, I got the logs. It is saying file name too long error. Is there a way that we can ignore title name:

:~$ youtube-dl --write-info-json -v --skip-download https://www.youtube.com/watch?v=id
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--write-info-json', '-v', '--skip-download', 'https://www.youtube.com/watch?v=id']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython)
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] id Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[info] Writing video description metadata as JSON to: तेरा मुझसे है पहले का नाता कोई - teraa mujhase hai pahale kaa naataa koii 6_15PM-id.info.json
ERROR: Cannot write metadata to JSON file तेरा मुझसे है पहले का नाता कोई - teraa mujhase hai pahale kaa naataa koii 6_15PM-id.info.json
Traceback (most recent call last):
  File "/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1900, in process_info
    write_json_file(self.filter_requested_info(info_dict), infofn)
  File "/.local/lib/python3.8/site-packages/youtube_dl/utils.py", line 1829, in write_json_file
    tf = tempfile.NamedTemporaryFile(**compat_kwargs(args))
  File "/usr/lib/python3.8/tempfile.py", line 679, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.8/tempfile.py", line 389, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 36] File name too long: 'तेरा मुझसे है पहले का नाता कोई - teraa mujhase hai pahale kaa naataa koii 6_15PM-id.info.json.3rtfd9i2.tmp'

**Comment by dirkf** [comment]
Test if it's really too long:
```
touch 'तेरा मुझसे है पहले का नाता कोई - teraa mujhase hai pahale kaa naataa koii 6_15PM-id.info.json.3rtfd9i2.tmp'
```
If that works, we have a bigger problem.

Otherwise, try something like `-o '%(title).4s - %(id).4s.%(ext)s'`. If that works, rename the output file to whatever you like that isn't too long, or, if you'll be doing this again, up the `4`s until you get a length that's both adequate and not too long.

**Comment by dirkf** [comment]
Closing as [related yt-dlp issue](https://github.com/yt-dlp/yt-dlp/issues/2737) was solved with the same response.
