### ISSUE TITLE
I have a problem calling aria2

### ISSUE THREAD

**Issue by Tkeng-tefs** [ytdl-org/youtube-dl#30637]
Hello!
I have a problem calling aria2. everything works fine when run using the command line, But there is always a problem when using it in python, it doesn't seem to be executed and there is no prompt.
This is the code I added, where do you see the problem?
 y_opts = {
     'external-downloader': 'aria2c',
     'external-downloader-args': '-x 16 -k 1M',
     'proxy': proxies,
     'outtmpl': outtmpls,
     'format': formats
}
I see that this similar question has also been consulted, but it has not been answered, nor can I find such an answer on google. Hope to get your help, thanks!

**Comment by pukkandan** [comment]
It's `external_downloader`. Read https://github.com/ytdl-org/youtube-dl#embedding-youtube-dl

**Comment by Tkeng-tefs** [comment]
I read this, I can use it in the command line, but there is always an exception when I use it in Python, which does not run Aria2 normally. I am very difficult to know, I hope you can tell me, thank you very much.

**Comment by pukkandan** [comment]
I just told you! It is `external_downloader`, not `external-downloader`

> I read this

From docs:

> Most likely, you'll want to use various options. For a list of options available, have a look at [youtube_dl/YoutubeDL.py](https://github.com/ytdl-org/youtube-dl/blob/3e4cedf9e8cd3157df2457df7274d0c842421945/youtube_dl/YoutubeDL.py#L137-L312).

**Comment by dirkf** [comment]
If only there were some sort of command-line genie that would auto-correct `-` to `_` and vice-versa as one typed, the legend on the Delete key could last a lot longer.

**Comment by Tkeng-tefs** [comment]
Sorry, I am Very Careless. Thank you very much for your answer! My question has been solved.

**Comment by dirkf** [comment]
Also see https://github.com/ytdl-org/youtube-dl/issues/31448#issuecomment-1379700151.
