### ISSUE TITLE
C

### ISSUE THREAD

**Issue by surmish** [ytdl-org/youtube-dl#30657]

**Comment by surmish** [comment]
files in error, please delete

**Comment by rautamiekka** [comment]
At least you realized it.

**Comment by garoto** [comment]
OP thought `pycryptodome` mentions everywhere on the source code were evidence enough that ytdl-org was shipping shitcoin miners.

Too funny.

**Comment by surmish** [comment]
Well yes, but also yanking lines in my computer was showing 'downloading package pycryptodomex' when i never downloaded it myself. Turned out my distro upgrade was botched leading to all sorts of strange behavior.
