### ISSUE TITLE
--all-subs --skip-download not working for a playlist

### ISSUE THREAD

**Issue by Abdelrahman-del** [ytdl-org/youtube-dl#30658]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by dirkf** [comment]
Follow [this template](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=4_bug_report.md&title=).
