### ISSUE TITLE
Windows 7 - CMD Prompt closes immediately after starting up the EXE file

### ISSUE THREAD

**Issue by overanyterrain** [ytdl-org/youtube-dl#30660]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

Using Windows 7 and the CMD window closes immediately after opening up the exe file. What can I do to get this working? Thanks.

**Comment by garoto** [comment]
`youtube-dl` must be operated from within the CLI environment, as in open `cmd.exe`, change to the dir where `youtube-dl.exe` resides and issue the command.

**Comment by overanyterrain** [comment]
Thank you, I will look into this.

**Comment by garoto** [comment]
C:\>where youtube-dl.exe
	C:\youtube-dl.exe

	C:\>youtube-dl.exe --help
	Usage: youtube-dl.exe [OPTIONS] URL [URL...]

	Options:
	  General Options:
		-h, --help                           Print this help text and exit
		--version                            Print program version and exit
		-U, --update                         Update this program to latest version. Make sure that you have sufficient permissions (run with
											 sudo if needed)
		-i, --ignore-errors                  Continue on download errors, for example to skip unavailable videos in a playlist
		--abort-on-error                     Abort downloading of further videos (in the playlist or the command line) if an error occurs
    [...]

**Comment by Lee-Carre** [comment]
@overanyterrain

[Introduction to the Command Line](//archive.flossmanuals.net/command-line/)
