### ISSUE TITLE
Cannot download from RTVE 

### ISSUE THREAD

**Issue by andin53** [ytdl-org/youtube-dl#30671]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\Portable\youtube-dl-gui-2.262>youtube-dl https://ztnr.rtve.es/ztnr/6375606.mpd -o "D:\Portable\ztnr.rtve.es\Video\(id)s.\Portable\youtube-dl-gui-2.262\ffmpeg.exe" --hls-prefer-ffmpeg -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://ztnr.rtve.es/ztnr/6375606.mpd', '-o', 'D:\\Portable\\ztnr.rtve.es\\Video\\(id)s.\\Portable\\youtube-dl-gui-2.262\\ffmpeg.exe', '--hls-prefer-ffmpeg', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] 6375606: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6375606: Downloading webpage
[generic] 6375606: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 2499, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


D:\Portable\youtube-dl-gui-2.262>pause
Presione una tecla para continuar . . .
```

## Description

It is my first time. I use Seamonkey and Palemoon.

It seem github does not support those browsers and now I'm using Friefox ESR .

This is the original URL https://www.rtve.es/play/videos/somos-documentales/espana-la-primera-globalizacion-el-camino-espanol/6375606/

**Comment by 89z** [comment]
Please stop doing whatever youre doing. Also, please provide example URL.

**Comment by andin53** [comment]
It is my first time. I use Seamonkey and Palemoon.

It seem github does not support those browsers and now I'm using Friefox ESR .

**Comment by andin53** [comment]
This is the original URL https://www.rtve.es/play/videos/somos-documentales/espana-la-primera-globalizacion-el-camino-espanol/6375606/

**Comment by dirkf** [comment]
First of all, regarding SM/PM you need this: https://github.com/JustOff/github-wc-polyfill

**Comment by dirkf** [comment]
The problem URL at www.rtve.es is a new format not handled by the RTVE extractors. Looking at the page the video won't play and it seems to be DRM-protected.

The DASH manifest confirms that:
```
<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="6A870B94-65AE-454F-AD1B-511AAEE0C878">
```
The extractor tests aren't all failing, so this isn't being applied retrospectively, or not yet.

**Comment by andin53** [comment]
> The problem URL at [www.rtve.es](http://www.rtve.es) is a new format not handled by the RTVE extractors. Looking at the page the video won't play and it seems to be DRM-protected.
> 
> The DASH manifest confirms that:
> 
> ```
> <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="6A870B94-65AE-454F-AD1B-511AAEE0C878">
> ```
> 
> The extractor tests aren't all failing, so this isn't being applied retrospectively, or not yet.

Thank you.

I will test in the future the website every time youtube-dl is updated-
