### ISSUE TITLE
Actors extractor field

### ISSUE THREAD

**Issue by DarkFighterLuke** [ytdl-org/youtube-dl#30672]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is there an extractor field about actors in a movie?
Based on [this](https://github.com/ytdl-org/youtube-dl/blob/7f41a598b3fba1bcab2817de64a08941200aa3c8/youtube_dl/extractor/common.py#L188-L303) I see no option to do it.

**Comment by dirkf** [comment]
If an extractor was going to extract this metadata, it could create its own field, or use `artist` or `album_artist`. Currently only music-oriented extractors use `artist`.

**Comment by DarkFighterLuke** [comment]
> If an extractor was going to extract this metadata, it could create its own field, or use `artist` or `album_artist`. Currently only music-oriented extractors use `artist`.

In your opinion, what is the best way: custom field or a music one?

**Comment by dirkf** [comment]
Perhaps look at https://schema.org/Movie and related schema items. A `Movie` can have one or more `actor` : `Person` properties. In Python it would have to be a list/tuple-valued property.

**Comment by DarkFighterLuke** [comment]
> Perhaps look at https://schema.org/Movie and related schema items. A `Movie` can have one or more `actor` : `Person` properties. In Python it would have to be a list/tuple-valued property.

Thank you, I'll go this way.
