### ISSUE TITLE
grabbing audio from a videodelivery.net link

### ISSUE THREAD

**Issue by weasel18** [ytdl-org/youtube-dl#30673]
## Checklist

- [x ] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

I'm attempting to download some videos from videodelivery.net I can get the video but struggling to get the audio stream.some of these videos are extremely long live streams, 12hr+ on a couple. so I'd like to try to get it figured out so I don't have to waste time downloading multiple times. here's the URLs in question if someone would be so kind to help me, I'm somewhat new to using cmd and the like..

https://iframe.videodelivery.net/ce8cdd22330bc136fb939f29129b8ff3
https://iframe.videodelivery.net/001e3417b542780d1f9fd60dc6814ab0
https://iframe.videodelivery.net/431aee7a48c4d11355e4b42971b348ef
https://iframe.videodelivery.net/7e9185b95e5d7eecd36c6bfdd9825f5d

https://iframe.videodelivery.net/$f3fe91c450d1bec7be445bd3ae0edda1 

i did "-F" and got the stream IDs and am able to download the video HLS (best) but trying the audio streams i just get the video again at a lower resolution.

**Comment by dirkf** [comment]
I think you must be doing something wrong.

Looking at the first stream, `-F` shows that it offers one audio stream and several video-only streams in each of HLS and DASH.

The HLS audio stream `hls-group_audio-und`:
```
    Stream #0:0: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 320 kb/s
```
The DASH audio stream `dash-145402389`:
```
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 308 kb/s (default)
```
You can ask yt-dl to get two formats in one command by using `-f format1,format2`, or `-f format1+format2` if they are a video and an audio stream to be merged.

Probably best to post your command line here.

**Comment by weasel18** [comment]
> 

.\youtube-dl.exe -f "hls-11264" "https://iframe.videodelivery.net/ce8cdd22330bc136fb939f29129b8ff3/manifest/seg.mp4"

**Comment by weasel18** [comment]
when i try do ,or + add or download just the audio "hls-group-audio" i get ERROR: requested stream not available"

**Comment by weasel18** [comment]
i may have figured it out, i was doing "hls-group-audio-und" and shouldve had "_" underscore between group and audio.. lets see how this works out now.. thanks so far @dirkf

**Comment by dirkf** [comment]
You're specifically asking for the HLS video and trying to get it from a URL that wasn't originally listed (but is effectively the same).

If you want one AV file, either of these would do (since bestvideo+bestaudio is preferred in the default format selection):
```
.\youtube-dl.exe -f "bestvideo+bestaudio" "https://iframe.videodelivery.net/ce8cdd22330bc136fb939f29129b8ff3/manifest/seg.mp4"


.\youtube-dl.exe "https://iframe.videodelivery.net/ce8cdd22330bc136fb939f29129b8ff3/manifest/seg.mp4"
```
If you want separate video and audio files:
```
.\youtube-dl.exe -f "bestvideo,bestaudio" "https://iframe.videodelivery.net/ce8cdd22330bc136fb939f29129b8ff3/manifest/seg.mp4"
```

**Comment by dirkf** [comment]
There's the benefit of using the default options or the virtual formats: no `_` in `bestaudio`, eg.

**Comment by weasel18** [comment]
so i notice in the beginning, the streams its going to download it only mentioned video, and is only downloading video at the moment, once the video is done will the audio track follow automatically. I'm guessing since video was first in the command thats what it will download first
