### ISSUE TITLE
How to Install in Windows

### ISSUE THREAD

**Issue by jsdpr15** [ytdl-org/youtube-dl#30674]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Sir,

Please Provide Detailed process to use it on Windows, Because when i click on Exe file, an command pom-pat open and close automatically

**Comment by dirkf** [comment]
You need to [open a Command Prompt window](https://www.digitalcitizen.life/open-cmd/) where you can type commands such as `youtube-dl --version` and others illustrated in the [Manual](https://github.com/ytdl-org/youtube-dl#readme).

**Comment by Lee-Carre** [comment]
@jsdpr15

[Introduction to the Command Line](//archive.flossmanuals.net/command-line/)
