### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>

### ISSUE THREAD

**Issue by arabesc** [ytdl-org/youtube-dl#30684]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
# youtube-dl --version
2021.12.17

# youtube-dl --download-archive archive.txt -v -f 'bestvideo[ext=mp4]+bestaudio/best[ext=mp4]/best' https://www.youtube.com/playlist\?list\=PLHTh1InhhwT4TJaHBVWzvBOYhp27UO7mI
[debug] System config: ['--force-ipv4', '--prefer-insecure', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--download-archive', 'archive.txt', '-v', '-f\xa0bestvideo[ext=mp4]+bestaudio/best[ext=mp4]/best', 'https://www.youtube.com/playlist?list=PLHTh1InhhwT4TJaHBVWzvBOYhp27UO7mI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.9 (CPython) - FreeBSD-13.0-RELEASE-p4-amd64-64bit-ELF
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] PLHTh1InhhwT4TJaHBVWzvBOYhp27UO7mI: Downloading webpage
[download] Downloading playlist: CppCon 2021 - Back To Basics
[youtube:tab] playlist CppCon 2021 - Back To Basics: Downloading 17 videos
...
[download] Downloading video 7 of 17
[youtube] cpkDQaYttR4: Downloading webpage
...
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2735, in https_open
    return self.do_open(functools.partial(
  File "/usr/local/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
```

## Description

There is an unhandled timeout exception.

**Comment by 89z** [comment]
This appears to be a duplicate. Did you try the Python patch in the other issue?

**Comment by arabesc** [comment]
It doesn't seem to be a duplicate. It's another error.

**Comment by 89z** [comment]
Also this:

~~~
[debug] Command-line args: ['--download-archive', 'archive.txt', '-v',
'-f\xa0bestvideo[ext=mp4]+bestaudio/best[ext=mp4]/best',
'https://www.youtube.com/playlist?list=PLHTh1InhhwT4TJaHBVWzvBOYhp27UO7mI']
~~~

`\xa0` is better known as U+00A0, or No-Break Space. Why are you using that instead of regular space character?

**Comment by arabesc** [comment]
> _\xa0 is better known as U+00A0, or No-Break Space. Why are you using that instead of regular space character?_

As you can in see in the command line:
`# youtube-dl --download-archive archive.txt -v -f 'bestvideo[ext=mp4]+bestaudio/best[ext=mp4]/best' https://www.youtube.com/playlist\?list\=PLHTh1InhhwT4TJaHBVWzvBOYhp27UO7mI`
there is a regular space character between the `-f` flag and the argument.

**Comment by 89z** [comment]
> As you can in see in the command line

Is this a joke? Visually, Space (U+0020) and no break space (U+00A0) are identical.

**Comment by arabesc** [comment]
Sorry, you are right, that is the result of copy-paste from the `man youtube-dl`:
```
# Download best mp4 format available or any other best if no mp4 available
$ youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'
```
There is that special character used instead of regular spaces.

**Comment by 89z** [comment]
Yes, thats fine for documentation, but not fine for actual use. I would suggest try again with actual space character. In addition, despite different error message, it appears to me to be same problem as other issue. So I would recommend install patch from other issue, and try command again.

**Comment by arabesc** [comment]
I thought the youtube-dl should handle connection timeout issues, it has some special parameters for that. Am I wrong?

**Comment by 89z** [comment]
Here is a quote, from you, from the other issue:

~~~
panic: Head "https://rr6---sn-gvnuxaxjvh-c35z.googlevideo.com/videoplayback?expire=...": net/http: TLS handshake timeout
~~~

So regardless of any current timeout handling, I think its reasonable to request apply patch from other issue, given the circumstance.

**Comment by arabesc** [comment]
Ok, I'll try the patch.

Anyway, the first issue is happened due to invalid TLS handshake, there is no valid connection. Here is a valid connection but at some point a request is failed with the connection timeout error:
```
/usr/local/lib/python3.9/urllib/request.py:
            try:
                h.request(req.get_method(), req.selector, req.data, headers,
                          encode_chunked=req.has_header('Transfer-encoding'))
            except OSError as err: # timeout error
                raise URLError(err)
```

**Comment by arabesc** [comment]
I've moved to the [yt-dlp](https://github.com/yt-dlp/yt-dlp) fork, it works better for me. Thank you for your help.

**Comment by dirkf** [comment]
>... youtube-dl should handle connection timeout issues, it has some special parameters for that. Am I wrong?

The timeout for connecting to a URL is meant to be 10 minutes or whatever you specify in `--socket-timeout`. IMO if your system is taking 10 minutes to reach a website you have worse problems than yt-dl, but there are always special cases.
