### ISSUE TITLE
Please add a function to somehow pull subs option override and according to their timing

### ISSUE THREAD

**Issue by 00Creamy** [ytdl-org/youtube-dl#30708]
https://www.youtube.com/watch?v=Py21QCndbxc
From this video, we can see in some part the subs, there's a white bg while others don't, this is video override option and it changes according to the timing
The available subs format currently doesn't seems to provide the video override settings, as if the subs and the video override is two different thing
So would it be possible to get video override?
Also is it possible to get playlist video ids without downloading every single information of the video in the playlist?(I just want the ids thats all)

**Comment by dirkf** [comment]
> The available subs format currently doesn't seems to provide the video override settings, as if the subs and the video override is two different thing
> So would it be possible to get video override?

Good question. Maybe it's available as a separate .vtt that is currently ignored? No-one ever seems to have looked at this. Further information/study/advice needed.

> Also is it possible to get playlist video ids without downloading every single information of the video in the playlist?(I just want the ids thats all)

`--get-id` (RTFM)

**Comment by 00Creamy** [comment]
[timedtext.txt](https://github.com/ytdl-org/youtube-dl/files/8318068/timedtext.txt)
Should look somewhat like this in json format

**Comment by 00Creamy** [comment]
@dirkf Idk if you see this but can I know whether the plain timed text is possible or not?

**Comment by dirkf** [comment]
Utilities exist to [strip HTML](https://www.nirsoft.net/utils/htmlastext.html) [from a file](https://www.w3.org/Tools/html2things.html), so you could try that.

The encoding in your timedtext.txt looks a bit weird, an issue with CP1252 vs UTF8, I guess.

**Comment by 00Creamy** [comment]
No the problem came when trying to download it
When looking around, I found out when you try to play a vid with subtitles, it sent a file named timedtext?v=[video_id]&[whatever_variables_they_put_here]&expire=[expire_id]&[more_stuff]
I used chrome, and look through the network inspection tab, but I do not if the timed text can be obtained by ytdl
I mean it's kinda tedious to go to every vid just to download subs

**Comment by 00Creamy** [comment]
@dirkf I know this is an old stuff but can you check on if it's possible? I just do not know how to automate since it require expire_id and the timedtext is sent with the video making getting it from url with just video id is hard

**Comment by 00Creamy** [comment]
Also last time you said strip HTML from a file?
Here it's more like strip a file from a page

**Comment by 00Creamy** [comment]
Nvm I found how to do it

**Comment by dirkf** [comment]
By all means let everyone else know what your solution was.
