### ISSUE TITLE
When will the next release be available in PyPI?

### ISSUE THREAD

**Issue by dopstar** [ytdl-org/youtube-dl#30704]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

At the time of writing the last[ PyPI release](https://pypi.org/project/youtube_dl/#history) for `youtube-dl` is dated at December 2021 and there hasnt been any release yet this year so far. 

Is there an ETA of when would the first release of the year be available as there a quite a number of cool commits contributed ever since?

**Comment by 89z** [comment]
The official blog recently stated that the 2021.12.17 version would be the last release, and that users should migrate to "Stu's Really Fast YouTube Downloader".

**Comment by dopstar** [comment]
@89z ooh, thanks for that information, can you please link the official blog here for my benefit or whover is reading this.

**Comment by 89z** [comment]
Sorry I didnt link it before, here you go:


[http://ytdl-org.github.io/blog](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by dopstar** [comment]
hehehe, that link plays 80's music in youtube

**Comment by Lee-Carre** [comment]
@dopstar

See #30625.

**Comment by dopstar** [comment]
@Lee-Carre  how could you say i should see a closed ticket where the answer was not provided? 

what is the problem, maybe the community can help, are maintainers busy or need a hand? then a call for help should be announced instead of replying sarcastically and close a ticket like it has been addressed.

**Comment by Lee-Carre** [comment]
> [butthurt]

Then see #30568, instead.
