### ISSUE TITLE
The whole script exits using youtube_dl module on network error

### ISSUE THREAD

**Issue by DarkFighterLuke** [ytdl-org/youtube-dl#30705]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I noticed that a script using `youtube_dl` module completely stops when a network error occurs while downloading videos.
Analyzing the script, it uses `extract_info()` to both download files and extract their information, all surrounded in a try-except block. No instruction to exit the script are present, so I suppose that is a `youtube_dl` issue.

In particular, the error that occurs is like "HTTP Error 401: Unauthorized" and when it happens the whole script exits.
Searching in code I saw there are a lot of `sys.exit()`, but why breaking everything instead of throwing an exception that can be handled is some way? I am sure I am missing something.

**Comment by 89z** [comment]
I think you need to provide some more context here. Even if you take a video that requires login, and omit authorization:

~~~
POST /youtubei/v1/player HTTP/1.1
Host: www.youtube.com

{
 "context": {
  "client": {
   "clientName": "ANDROID",
   "clientVersion": "17.06.32"
  }
 },
 "videoId": "Cr381pDsSsA"
}
~~~

No error is produced:

~~~
HTTP/2.0 200 OK
Content-Type: application/json; charset=UTF-8
Date: Tue, 01 Mar 2022 16:45:26 GMT
Server: scaffolding on HTTPServer2
Vary: Origin
~~~

**Comment by DarkFighterLuke** [comment]
Sites from where I am downloading do not require authentication, so that message is really weird...

**Comment by 89z** [comment]
You need to provide an example URL.

**Comment by dirkf** [comment]
`sys.exit()` is only called when the yt-dl main program is returning to the invoking process with an error.

In a Python script, you instantiate a `YoutubeDL` object
```py
with YoutubeDL(ydl_opts) as ydl:
    ...
```
so you can control what happens if there's an unhandled exception.

If yt-dl is being called from, eg, a shell script, the same sort of error handling could be done there, but with less granularity.

401 may be some sort of gate-keeping response "Your browser smells funny, you're not getting in".

**Comment by DarkFighterLuke** [comment]
> You need to provide an example URL.

https://sxyprn.com/post/57ffcb2e1179b.html




> `sys.exit()` is only called when the yt-dl main program is returning to the invoking process with an error.
> 
> In a Python script, you instantiate a `YoutubeDL` object
> 
> ```python
> with YoutubeDL(ydl_opts) as ydl:
>     ...
> ```
> 
> so you can control what happens if there's an unhandled exception. Also, you can pass the programmatic equivalent of `--ignore-errors`.

Yeah sure, it is what I am doing. Take a look at this snippet of code: https://pastebin.com/Ga8y3t4r



> 401 may be some sort of gate-keeping response "Your browser smells funny, you're not getting in".

Yeah, I think so, but why to kill the entire script?

**Comment by dirkf** [comment]
Are you saying that somehow `ydl.extract_info()` can cause the program to exit without hitting your `except:` block?

Otherwise, since it can't fetch whatever data it needed because of the 401, it has to raise the error. Maybe trap that and try again?

**Comment by DarkFighterLuke** [comment]
> Are you saying that somehow `ydl.extract_info()` can cause the program to exit without hitting your `except:` block?

Yeah, I'm saying it. It seems that the `except:` block does not prevent exiting from the script.

**Comment by dirkf** [comment]
Well, no, but it does log the exception? Then you need to wrap the `extract_info()` call to trap whatever error is being raised and decide what to do about it, retry, skip, give up ...

Otherwise your Python must be crashing weirdly - out of memory, maybe, if it's getting a giant playlist.

**Comment by DarkFighterLuke** [comment]
The log in the `except:` block is not executed.

> Otherwise your Python must be crashing weirdly - out of memory, maybe, if it's getting a giant playlist.

This is my case, I'am actually downloading a giant playlist, I didn't think of memory problems. However, I am running on raspberry pi 3, but memory seems to be stable around 495 MB out of 922 MB. I'll monitor it and i will let you know.
Thank you.

**Comment by DarkFighterLuke** [comment]
Ok, it appears not to be a memory problem.

**Comment by dirkf** [comment]
... when 429 "too many requests" would have been the better response?

401 means "I want to know who you are" vs.
403 "I know who you are and you're not having any"

**Comment by dirkf** [comment]
> Ok, it appears not to be a memory problem.

Do you have a different Python version that you could try?

Is there a non-zero exit code (and which OS)?

**Comment by DarkFighterLuke** [comment]
Thank you @coletdjnz , but I'm not downloading in parallel, just sequentially.

> 401 means "I want to know who you are"

Yeah, you're right, but I don't know why I get this error at some point in time.

I tried to edit the `except:` block in the snippet I've sent yesterday replacing `Exception` with `BaseException`, but nothing changed.
I'll try to check if this issue happens on a regular time interval.

> Is there a non-zero exit code (and which OS)?

I am in an alpine docker container with Python 3, the script I am working on is a plugin for [stash](https://github.com/stashapp/stash) and you can find it [here](https://github.com/DarkFighterLuke/StashPlugins/blob/ytdl-options/py_plugins/yt-dl_downloader.py). The exit code I am getting in logs is `1`.

> Do you have a different Python version that you could try?

The script requires Python 3, but no specific minor version is specified. I'm currently running Python 3.9.7.

**Comment by DarkFighterLuke** [comment]
I run the script on my computer (not as a stash plugin, I modified it a bit) and it seems to be working.
There are these differences:
- Python 3.10 instead of 3.9 on the container
- 100 Mbit/s Ethernet instead of 2.4 GHz WiFi
- Intel x86_64 instead of ARM

So I can't really figure out what goes wrong...
