### ISSUE TITLE
Disney Now Unable to extract post url - DirecTV

### ISSUE THREAD

**Issue by czesardine** [ytdl-org/youtube-dl#30706]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22000
[debug] exe versions: ffmpeg git-2020-06-28-4cfcfb3, ffprobe git-2020-06-28-4cfcfb3
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```

## Description

Free videos work fine. It's with the "premium" videos where I got issues. Right now I'm not logged in with my TV provider at youtube-dl, and it asks me for my user, and when I enter it...
```
G:\Downloads\Youtube\youtube-dl>youtube-dl --list-formats https://disneynow.com/shows/roman-to-the-rescue/season-01/episode-07-asher/vdka26623601 --ap-mso DTV --ap-username xxxx@yyyy --ap-password aaaa
[Go] vdka26623601: Downloading JSON metadata
[Go] VDKA26623601: Downloading Provider Redirect Page
[Go] VDKA26623601: Downloading Provider Login Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
I read a very old ticket with the same issue, and apparently the problem was the TV provider didn't have support, but DirecTV was working fine.
Pus: During writing this, I used a laptop where I was logged in, and it works fine, so I guess I just can't log in.

**Comment by dirkf** [comment]
Superseded by #30726
