### ISSUE TITLE
[vrt.nu] ERROR: No video formats found

### ISSUE THREAD

**Issue by kleajmp** [ytdl-org/youtube-dl#30716]
I tried: 
`youtube-dl -F https://remix-cf-vrt.akamaized.net/remix/3111afd8-037f-4804-a6b3-04b893416d4b/remix.ism/.mpd`

It comes from drm protected: www.vrt.nu which uses mpeg-dash

error:
`[generic] .mpd: Requesting header
WARNING: Falling back on generic information extractor.
[generic] .mpd: Downloading webpage
[generic] .mpd: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

this is the mpd-file: 
[BettyDavis.mpd.TXT](https://github.com/ytdl-org/youtube-dl/files/8191511/BettyDavis.mpd.TXT)

anything I can do?

**Comment by 89z** [comment]
I dont think YouTube-DL supports any of these:

~~~xml
<!-- Common Encryption -->
<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="58187171-08C0-1F92-ED5A-7FD0048C54A2"> </ContentProtection>
<!-- PlayReady -->
<ContentProtection schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95" value="MSPR 2.0"> </ContentProtection>
<!-- Widevine -->
<ContentProtection schemeIdUri="urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED"> </ContentProtection>
<!-- Marlin -->
<ContentProtection schemeIdUri="urn:uuid:5E629AF5-38DA-4063-8977-97FFBD9902D4">
</ContentProtection>
~~~

**Comment by kleajmp** [comment]
ok so if I understand well (I'm a newbe to mpeg-dash), every streaming website can use a unique encryption/decryption algorithm that needs to be deciphered first before it can be supported by mpeg-dash decoding tools as ytdl?

**Comment by 89z** [comment]
No, some websites don't even use encryption. For example, most YouTube videos are not encrypted.

**Comment by kleajmp** [comment]
but for this case.. what can I do to download content from this website? It is our national television station so it had a lot of unique and interesting content I like to save for later.

**Comment by 89z** [comment]
> but for this case.. what can I do to download content from this website?

I dont think its possible, unless you can convince some really smart person to help you. To get the content, you need to make a request to a license server, sending a ProtoBuf request body with some details. Example request [1].

But, even if you send a good request, and you get a response, it seems the response key itself is encrypted, and that only the CDM module in web browser or similar can decrypt it [2]. I am not an expert in this, so someone else can maybe add more information.


1. https://github.com/89z/mech/blob/e0720985/research/paramount/widevine.go
2. https://forum.videohelp.com/threads/402360-How-do-I-get-the-decryption-key

**Comment by kleajmp** [comment]
ok interesting!
Thanks to your information I will deepen my knowledge about this (for people interested I share this basic info which is new for me):
[CDM](https://www.vdocipher.com/blog/widevine-cdm-content-decryption-module/#NeedOfDRM)
[Encrypted Media Extensions](https://www.w3.org/TR/encrypted-media/)

When someone has more practical information for my journey to accomplish this, be free to let me know.

**Comment by 89z** [comment]
@kleajmp some new information has come to light, so this might now be possible. Can you provide the page where this MPD came from?
