### ISSUE TITLE
{YouTube] Playlist download with intermittent 403 Error - Forbidden

### ISSUE THREAD

**Issue by MrCodingFanboy** [ytdl-org/youtube-dl#30729]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Why do i get 403 errors after some time of downloading a playlist? 
I've checked if the video it gets the error is with an age verfication, but it's not and if i restart the download at that point, it is working fine for some time again.
Please help me, it's very annoying when you want to download a playlist with nearly 1000 songs.

**Comment by dirkf** [comment]
Site details, examples please.

**Comment by MrCodingFanboy** [comment]
This is the playlist I'm trying to download:
https://www.youtube.com/playlist?list=PLQv0Eg-cmdh8BuoeyjXH3FenIF1rtxtMG

And that's what i get in Ubuntu Terminal:
![image](https://user-images.githubusercontent.com/45085679/157525950-d6bbc4ed-f70f-45ee-9c02-58222e054a0d.png)

**Comment by dirkf** [comment]
Might you have some network proxy or firewall between you and YT?

Confusingly, the video TEBUmPz1_CQ is the first one in the list that I get, not the 29th.

Also, it's easier to help if you paste any log as text (inside triple back-quotes on separate lines to format as code, with the word ShellSession directly after the first ``` for even better formatting).

For example, what's in the compose field:
<pre>
```ShellSession
$ youtube-dl -v --test TEBUmPz1_CQ[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--test', 'TEBUmPz1_CQ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] TEBUmPz1_CQ: Downloading webpage
[youtube] TEBUmPz1_CQ: Downloading player 2fd2ad45
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader ...
... snip ...
[download] Destination: Kontra K - Power (Official Video)-TEBUmPz1_CQ.f140.m4a
[download] 100% of 10.00KiB in 00:00
[ffmpeg] Merging formats into "Kontra K - Power (Official Video)-TEBUmPz1_CQ.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Kontra K - Power (Official Video)-TEBUmPz1_CQ.f137.mp4' -i 'file:Kontra K - Power (Official Video)-TEBUmPz1_CQ.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Kontra K - Power (Official Video)-TEBUmPz1_CQ.temp.mp4'
Deleting original file Kontra K - Power (Official Video)-TEBUmPz1_CQ.f137.mp4 (pass -k to keep)
Deleting original file Kontra K - Power (Official Video)-TEBUmPz1_CQ.f140.m4a (pass -k to keep)
df@Spiridion:~/Documents/src/youtube-dl$ 
```
</pre>
How that appears in a post:
```ShellSession
$ youtube-dl -v --test TEBUmPz1_CQ[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--test', 'TEBUmPz1_CQ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] TEBUmPz1_CQ: Downloading webpage
[youtube] TEBUmPz1_CQ: Downloading player 2fd2ad45
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://rr2---sn-cu-aigss.googlevideo.com/videoplayback?expire=1646880125&ei=HREpYtT9CpSgvdIPjdeNuAY&ip=51.6.64.232&id=o-AGbBRjUIM4LJU1edAyNUU7Rztd2ALRrpW2HBzR3krlM_&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=07&mm=31%2C29&mn=sn-cu-aigss%2Csn-cu-c9iz&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=25&initcwndbps=1241250&vprv=1&mime=video%2Fmp4&ns=THWsAq8OxWrPgWspcWXX4kAG&gir=yes&clen=79517492&dur=212.583&lmt=1586081446966894&mt=1646858221&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5535432&n=7u9dUcHCyU3BEnu_BM4S&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOwTrJ33wssSRowKt6fNjQHha2Q8jnbP884z52usXt8TAiEAzOdSTWRKhtwmw2VltB6Vve5pWUPhevZqy7AfX8XKQGc%3D&sig=AOq0QJ8wRgIhAMcXZogWv4R-UpQo6g-42pqsOBz5D2VrA1zIXz1zA9HiAiEAw1IicMTo3nw4dY7-Yc4mkkw1t5LuU6C-0c7Zfsxfa8c='
[download] Destination: Kontra K - Power (Official Video)-TEBUmPz1_CQ.f137.mp4
[download] 100% of 10.00KiB in 00:00
[debug] Invoking downloader on 'https://rr2---sn-cu-aigss.googlevideo.com/videoplayback?expire=1646880125&ei=HREpYtT9CpSgvdIPjdeNuAY&ip=51.6.64.232&id=o-AGbBRjUIM4LJU1edAyNUU7Rztd2ALRrpW2HBzR3krlM_&itag=140&source=youtube&requiressl=yes&mh=07&mm=31%2C29&mn=sn-cu-aigss%2Csn-cu-c9iz&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=25&initcwndbps=1241250&vprv=1&mime=audio%2Fmp4&ns=THWsAq8OxWrPgWspcWXX4kAG&gir=yes&clen=3442221&dur=212.648&lmt=1586080587414399&mt=1646858221&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5531432&n=7u9dUcHCyU3BEnu_BM4S&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgR_miUX8MxhJlt7L1W5wyp8Hx4pmcXWoBjq8NtXoQlZYCIBOL-ED4UHcYVkS1QElMvfbn1hO_asWqPcIGqUbccR9u&sig=AOq0QJ8wRQIgUErytaEewOjJltmGMoHnW92k4TnjYxLV8r1i6-gjblQCIQC5tx2Vc5NKmio3K1sGED3V9K7Xpb2cJvTq1DPqghLdTA=='
[download] Destination: Kontra K - Power (Official Video)-TEBUmPz1_CQ.f140.m4a
[download] 100% of 10.00KiB in 00:00
[ffmpeg] Merging formats into "Kontra K - Power (Official Video)-TEBUmPz1_CQ.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Kontra K - Power (Official Video)-TEBUmPz1_CQ.f137.mp4' -i 'file:Kontra K - Power (Official Video)-TEBUmPz1_CQ.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Kontra K - Power (Official Video)-TEBUmPz1_CQ.temp.mp4'
Deleting original file Kontra K - Power (Official Video)-TEBUmPz1_CQ.f137.mp4 (pass -k to keep)
Deleting original file Kontra K - Power (Official Video)-TEBUmPz1_CQ.f140.m4a (pass -k to keep)
$ 
```

**Comment by MrCodingFanboy** [comment]
No, at least no Proxy and no firewall on my home network at least and I don't think my internet provides has one, but who knows.

Well, that's because I'm simultaneously deleting the songs I've downloaded, I'm sorry I didn't mention that.

So I stopped my deleting script and that's the whole debug text when the error occurs. As I mentioned in the beginning, it doesn't happen every time.

´´´ShellSession
[download] Downloading video 11 of 890
[youtube] aeVBQP_pWCk: Downloading webpage
[debug] Invoking downloader on u'https://rr2---sn-poxmpv-njoe.googlevideo.com/videoplayback?expire=1646881621&ei=9RYpYuDBCo3vgAek84WAAw&ip=131.117.152.101&id=o-ANP23J6hG1FszFjbX3McLAVT0io2er6FSCjh70i8Z95l&itag=140&source=youtube&requiressl=yes&mh=WY&mm=31%2C29&mn=sn-poxmpv-njoe%2Csn-4g5e6ns7&ms=au%2Crdu&mv=m&mvi=2&pl=21&initcwndbps=1401250&vprv=1&mime=audio%2Fmp4&ns=f7O5p0KJKmm9QLZ_OnGraA8G&gir=yes&clen=3390973&dur=213.461&lmt=1507937009265742&mt=1646859426&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&n=gItOphym3Km8KGAwp4OY&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPqJjysOGh1IqJsUNKVLwMrAGwmIfrJUPHtwseovmENIAiB_6uLtYqeZPJAF9v9XPZBqxdZ9nsF_PQDZBFnPQyfp6w%3D%3D&sig=AOq0QJ8wRgIhAPQjsoIIyEhwyehhouYTd52TglLjy-N1mMT7I7w7TiuPAiEAqJnZAuckmQpW9qUHya3jBCWj7dlKvMYmRNIVOHB_QAY='
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1976, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
HTTPError: HTTP Error 403: Forbidden
´´´

**Comment by fiordiconio** [comment]
Could it be from some limitations from the servers of youtube?

**Comment by 89z** [comment]
Did we ever implement the host fallback?

**Comment by dirkf** [comment]
Not yet, but that was 404, wasn't it?

With 403, I generally suspect some non-YT networking issue but who can tell?

**Comment by 89z** [comment]
It was an SSL error instead, but I thought it might be worth trying

**Comment by dirkf** [comment]
Continued in #31247.
