### ISSUE TITLE
pip install git master

### ISSUE THREAD

**Issue by 89z** [ytdl-org/youtube-dl#30721]
It seems this comment is often given:

> Duplicate, fixed in git master

but new users might have no idea what to do with that type of comment. I think it would be helpful if we could instruct users on how to actually install that. I see this [1]:

~~~
sudo -H pip install --upgrade youtube-dl
~~~

but that does not install Git master, only the last release. I think the correct command is this:

~~~
pip install https://github.com/ytdl-org/youtube-dl/archive/master.zip
~~~

1. https://github.com/ytdl-org/youtube-dl#installation

**Comment by dirkf** [comment]
I guess it is, but I would rather get a new release out. Someone who wants to install the program with _pip_ or _pip3_ should be able to find plenty of guidance with a web search. Because of the [xkcd python installation issue](https://xkcd.com/1987/) it's tricky to recommend installation techniques.

**Comment by 89z** [comment]
> it's tricky to recommend installation techniques.

Counter: YT-DLP is already doing this:

https://github.com/yt-dlp/yt-dlp#with-pip

**Comment by ionenwks** [comment]
> I guess it is, but I would rather get a new release out.

As a distro packager that preferably stick to actual releases rather than do snapshots, I'd like to see both projects see more frequent releases as necessary -- so I can only agree with that.

**Comment by 89z** [comment]
> I'd like to see both projects see more frequent releases as necessary -- so I can only agree with that.

I disagree with this. Users ideally are going to want a release every single commit, so that whatever fix they are interested in, can be easily installed. However obviously thats not a good idea. The maintainers should only make release when it makes sense, not to cater to the users. So in between releases, it makes sense to make it as easy as possible for users to install current master, which my suggestion about documentation is aimed toward.

**Comment by 89z** [comment]
closing for lack of interest
