### ISSUE TITLE
(Spankbang) Channels download possible?

### ISSUE THREAD

**Issue by vvglyy** [ytdl-org/youtube-dl#30728]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions, including closed ones

## Question

Can I use a specific website extractor?
Or I misunderstood something.
Example : **Spankbang** is present in extractor link, but a channel download isn't possible though.
Tried to download as playlist with no luck.
Can't see any playlist on this site too.
How can I bulk download a channel?
Thanks

**Comment by dirkf** [comment]
Example URLs needed, please.

**Comment by dirkf** [comment]
Haha, but it would be difficult to respond to this issue without knowing what page OP wants yt-dl to handle.

By convention maintainers don't judge the content of a supported site that meets the criteria on the Site Support template, though any maintainer is free to ignore issues related to a site without having to justify so doing.

**Comment by afterdelight** [comment]
What do you need? a playlist url or a channel url?

**Comment by vvglyy** [comment]
I can give what I said a URL of a guys/gurlz **channel** --> Videos like in YouTube... I go to a channel and then to its videos and add playlist in my command line

[A channel of a guy](https://fr.spankbang.com/profile/daniellarthurr131/videos)

**Comment by vvglyy** [comment]
> What do you need? a playlist url or a channel url?

Here i can say there's no playlist on Spankbang? Am I wrong?

Then,  `Example URLs needed, please.` I'm interested 😂

**Comment by afterdelight** [comment]
https://spankbang.com/6zoi/playlist/asian+dance
https://spankbang.com/51wxk/playlist/dance
https://spankbang.com/9c8v/playlist/xcw
https://spankbang.com/3scw7/playlist/asian+dance
https://spankbang.com/5cgbb/playlist/chn+dance

**Comment by afterdelight** [comment]
hey

**Comment by vvglyy** [comment]
It works but for a more than 78 videos playlists, it downloads only 78 videos.

`WARNING: [SpankBangPlaylist] unable to extract playlist title; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U`

**Comment by vvglyy** [comment]
Example for [the 3rd playlist]( https://spankbang.com/9c8v/playlist/xcw )which contain 140 videos from @afterdelight list : 

`yt-dlp -Uv -f "(mp4)[height<=?720][tbr>500]" --no-check-certificate --yes-playlist --cookies-from-browser firefox "https://fr.spankbang.com/9c8v/playlist/xcw"
[debug] Command-line config: ['-Uv', '-f', '(mp4)[height<=?720][tbr>500]', '--no-check-certificate', '--yes-playlist', '--cookies-from-browser', 'firefox', 'https://fr.spankbang.com/9c8v/playlist/xcw']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.10.4 (CPython 64bit) - macOS-12.4-x86_64-i386-64bit
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: certifi-2022.05.18.1, sqlite3-2.6.0
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/Users/vvglyywzxit/Library/Application Support/Firefox/Profiles/vt78fq64.default-release-1-1650662348786/cookies.sqlite"
[Cookies] Extracted 2551 cookies from firefox
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [SpankBangPlaylist] Extracting URL: https://fr.spankbang.com/9c8v/playlist/xcw
[SpankBangPlaylist] 9c8v: Downloading webpage
WARNING: [SpankBangPlaylist] unable to extract playlist title; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[download] Downloading playlist: 9c8v
[SpankBangPlaylist] playlist 9c8v: Collected 78 videos; downloading 78 of them
[download] Downloading video 1 of 78
[debug] [SpankBang] Extracting URL: https://fr.spankbang.com/9c8v-g3qyqz/playlist/xcw
[SpankBang] g3qyqz: Downloading webpage
[SpankBang] g3qyqz: Downloading stream JSON
[SpankBang] g3qyqz: Downloading m3u8 information
[SpankBang] g3qyqz: Downloading m3u8 information
[SpankBang] g3qyqz: Downloading m3u8 information
[SpankBang] g3qyqz: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] g3qyqz: Downloading 1 format(s): hls-2530-1
[debug] Invoking hlsnative downloader on "https://hls-uranus.sb-cd.com/hls/1/1/11581153-720p.mp4/index-v1-a1.m3u8?_tid=11581153&d=2&m=9&secure=QSLN_-EMPKCH1IZLFNlmCg,1654535193"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 346
[download] Destination: Lesbian Bikini Raslin [g3qyqz].mp4
[download]   2.9% of ~303.21MiB at  2.12MiB/s ETA 02:32 (frag 10/346)^C
ERROR: Interrupted by user
`

**Comment by afterdelight** [comment]
maybe it only downloaded 1st page?

**Comment by afterdelight** [comment]
why did u close this?

**Comment by afterdelight** [comment]
what about channel download?

**Comment by dirkf** [comment]
OP closed the issue. The example URLs listed above appear to work in PR #31010.

**Comment by vvglyy** [comment]
> what about channel download?

Channels aren't playlists, there's no way to download a channel AFAIK :/

> why did u close this?

Because there is an answer to this issue : “The extractor has no pagination: it only finds the items linked in the first playlist page.”

It's more a request, then, right?

It works, but only for the 1st page. Should reopen for that? I can, let me know.

Or feel free to open a request, I guess.

**Comment by dirkf** [comment]
PR #31010 does the pagination. If you re-open the issue it'll be closed automatically when the PR is merged.

As the provided examples were of playlists and not channels, those are what gets paginated.

Without examples of channels the issue could equally be closed as Incomplete.

**Comment by dirkf** [comment]
All these pages have a similar structure to playlist pages
* category
* tag
* search
* channel
* star
* profile.

All very similar to the listing pages in XVideos, and now handled in #31010.

**Comment by afterdelight** [comment]
@dirkf could you fix and merge PR https://github.com/ytdl-org/youtube-dl/pull/30774?

**Comment by vvglyy** [comment]
> All very similar to the listing pages in XVideos, and now handled in #31010.

Just have to update an `-Uv -f "(mp4)[height<=?720][tbr>500]" --no-check-certificate --yes-playlist --cookies-from-browser firefox "https://fr.spankbang.com/9c8v/playlist/xcw"` will download all videos from the playlist?

Same for channels?

Thanks.

**Comment by dirkf** [comment]
The new spankbang.py might work with yt-dlp but hasn't been tested.

To test the PR, [use _pip_ to install it](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/); you'll also get fixes from the git master level (04fd3289d30de3c99c7d2de34d555b050bc96d4d) from which the branch was cloned.

Apparently the URL to pass to _pip_ for this is https://github.com/ytdl-org/youtube-dl/tarball/pull/31010/head.

**Comment by vvglyy** [comment]
I use youtube-dl now. What's the difference between youtube-dl and yt-dlp?

**Comment by vvglyy** [comment]
> To test the PR, [use _pip_ to install it](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/); you'll also get fixes from the git master level ([04fd328](https://github.com/ytdl-org/youtube-dl/commit/04fd3289d30de3c99c7d2de34d555b050bc96d4d)) from which the branch was cloned.
> 
> Apparently the URL to pass to _pip_ for this is https://github.com/ytdl-org/youtube-dl/tarball/pull/31010/head.

I've got this error (macOS, installed via macports : python, pip, git)

python -m pip install git+https://github.com/ytdl-org/youtube-dl/tarball/pull/31010/head 
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/ytdl-org/youtube-dl/tarball/pull/31010/head
  Cloning https://github.com/ytdl-org/youtube-dl/tarball/pull/31010/head to /private/var/folders/1q/qb_v7bnn3zn0d42zm4n0x5dh0000gn/T/pip-req-build-o1q2vb6_
  Running command git clone --filter=blob:none --quiet https://github.com/ytdl-org/youtube-dl/tarball/pull/31010/head /private/var/folders/1q/qb_v7bnn3zn0d42zm4n0x5dh0000gn/T/pip-req-build-o1q2vb6_
  remote: 404: Not Found
  fatal: dépôt 'https://github.com/ytdl-org/youtube-dl/tarball/pull/31010/head/' non trouvé
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/ytdl-org/youtube-dl/tarball/pull/31010/head /private/var/folders/1q/qb_v7bnn3zn0d42zm4n0x5dh0000gn/T/pip-req-build-o1q2vb6_ did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/ytdl-org/youtube-dl/tarball/pull/31010/head /private/var/folders/1q/qb_v7bnn3zn0d42zm4n0x5dh0000gn/T/pip-req-build-o1q2vb6_ did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

'Defaulting to user installation because normal site-packages is not writeable'

I think it's this, that cause the error, right? How to force install in the normal site-packages folder?
