### ISSUE TITLE
Conversion failed

### ISSUE THREAD

**Issue by vvglyy** [ytdl-org/youtube-dl#30727]
## Checklist

- [x] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

download] Downloading video 145 of 145
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=HU15EOFbHSI
[youtube] HU15EOFbHSI: Downloading webpage
[youtube] HU15EOFbHSI: Downloading android player API JSON
[youtube] HU15EOFbHSI: Downloading MPD manifest
[youtube] HU15EOFbHSI: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] HU15EOFbHSI: Downloading 1 format(s): 303+251
[info] Writing video description to: SundayAfternoonModular/20190318 - 2HP Pluck Jam HU15EOFbHSI.description
[info] Writing video metadata as JSON to: SundayAfternoonModular/20190318 - 2HP Pluck Jam HU15EOFbHSI.info.json
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1646797048/ei/mMwnYunqDJLGgAf-1KaABw/ip/2a01%3Acb18%3A83ca%3Adc00%3Ae949%3A1112%3A52f0%3A642c/id/1d4d7910e15b1d22/source/youtube/requiressl/yes/playback_host/rr3---sn-25glenes.googlevideo.com/mh/fQ/mm/31%2C29/mn/sn-25glenes%2Csn-25ge7ns7/ms/au%2Crdu/mv/m/mvi/3/pl/41/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1040000/vprv/1/mt/1646774954/fvip/6/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIhAJX74D8ZOqSidqEcWVUIJnatjQGgYiKo-XhcJXei5TaAAiBcoymTMBm6Mks6i6YXxxMnuhsEILfQnmzIzbQ2F1r0jQ%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIhAPvRiawq5NZEGn9wlyE3F9s4tpiq6ivqziJJYQOIZpT7AiAP3K23Vy_f7eLoMyMD00mlYN6YDhC1EKbS4rsxK9o05A%3D%3D"
[dashsegments] Total fragments: 17
[download] Destination: SundayAfternoonModular/20190318 - 2HP Pluck Jam HU15EOFbHSI.f303.webm
[download] 100% of 26.54MiB in 00:04
[debug] Invoking downloader on "https://rr3---sn-25glenes.googlevideo.com/videoplayback?expire=1646797048&ei=mMwnYquhKODVx_APgpCamAY&ip=2a01%3Acb18%3A83ca%3Adc00%3Ae949%3A1112%3A52f0%3A642c&id=o-AGm6o6q0h3ACEPO5UjsO8AQeNVnUYIkxsJvpQ6CpcryI&itag=251&source=youtube&requiressl=yes&mh=fQ&mm=31%2C26&mn=sn-25glenes%2Csn-4g5lzner&ms=au%2Conr&mv=m&mvi=3&pl=41&initcwndbps=1040000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=1563291&otfp=1&dur=79.841&lmt=1565486684417662&mt=1646774954&fvip=3&keepalive=yes&fexp=24001373%2C24007246&beids=23886214&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKmn6YHb4l23wUJCO3WpwhJkmdsCmuh8qXKtTe_-YgSQAiEA-N0nsBdqXnAi10f-wiCUbnYpERGDOjWFY4OsSxI8Ih8%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAOhUuqC0zB28gPgzgZPlelKTSXyQt7W14Z5YyGFxRberAiAys7_Sraovyn6Newvbf8xC0ksAGRnvbDGUTyph1qT4iQ%3D%3D"
[download] Destination: SundayAfternoonModular/20190318 - 2HP Pluck Jam HU15EOFbHSI.f251.webm
[download] 100% of 1.49MiB in 00:00
[Merger] Merging formats into "SundayAfternoonModular/20190318 - 2HP Pluck Jam HU15EOFbHSI.MKV"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:SundayAfternoonModular/20190318 - 2HP Pluck Jam HU15EOFbHSI.f303.webm' -i 'file:SundayAfternoonModular/20190318 - 2HP Pluck Jam HU15EOFbHSI.f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:SundayAfternoonModular/20190318 - 2HP Pluck Jam HU15EOFbHSI.temp.MKV'
[debug] ffmpeg version 4.4.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, matroska,webm, from 'file:SundayAfternoonModular/20190318 - 2HP Pluck Jam HU15EOFbHSI.f303.webm':
  Metadata:
    encoder         : google/video-file
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 16 
                    : Segment-Durations-Ms: 5072,5071,5072(r=2),5071,5072(r=2),5071,5072(r=2),5071,5072,3687, 
                    :  
                    : 
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 59.94 fps, 59.94 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:SundayAfternoonModular/20190318 - 2HP Pluck Jam HU15EOFbHSI.f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:01:19.84, start: -0.007000, bitrate: 156 kb/s
  Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Output #0, matroska, to 'file:SundayAfternoonModular/20190318 - 2HP Pluck Jam HU15EOFbHSI.temp.MKV':
  Metadata:
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 16 
                    : Segment-Durations-Ms: 5072,5071,5072(r=2),5071,5072(r=2),5071,5072(r=2),5071,5072,3687, 
                    :  
                    : 
    encoder         : Lavf58.76.100
  Stream #0:0(eng): Video: vp9 (Profile 0) (VP90 / 0x30395056), yuv420p(tv, bt709/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 59.94 fps, 59.94 tbr, 1k tbn, 1k tbc (default)
  Stream #0:1(eng): Audio: opus ([255][255][255][255] / 0xFFFFFFFF), 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=    1 fps=0.0 q=-1.0 size=       1kB time=00:00:00.00 bitrate=6712.0kbits/[matroska @ 0x7f90b1831200] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5088 >= 5072
av_interleaved_write_frame(): Invalid argument
frame=  307 fps=0.0 q=-1.0 Lsize=    1856kB time=00:00:05.10 bitrate=2981.1kbits/s speed= 610x    
video:1817kB audio:94kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
ERROR: Conversion failed!
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3329, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 119, in wrapper
    return func(self, info)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 828, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 294, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 333, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

[EmbedSubtitle] Subtitles can only be embedded in mp4, webm or mkv files
[Metadata] Adding metadata to "SundayAfternoonModular/20190318 - 2HP Pluck Jam HU15EOFbHSI.MKV"
ERROR: [Errno 2] No such file or directory: 'SundayAfternoonModular/20190318 - 2HP Pluck Jam HU15EOFbHSI.MKV'
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1473, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1529, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2638, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3201, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3369, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3356, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3329, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 119, in wrapper
    return func(self, info)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 709, in run
    self.run_ffmpeg_multiple_files(
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 294, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 301, in real_run_ffmpeg
    oldest_mtime = min(
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 302, in <genexpr>
    os.stat(encodeFilename(path)).st_mtime for path, _ in input_path_opts if path)
FileNotFoundError: [Errno 2] No such file or directory: 'SundayAfternoonModular/20190318 - 2HP Pluck Jam HU15EOFbHSI.MKV'

[info] Writing updated playlist metadata as JSON to: SundayAfternoonModular/NA - SundayAfternoonModular - Videos UCmcZbHDosVbq-hk0wiilEZg.info.json
[download] Finished downloading playlist: SundayAfternoonModular - Videos

## Description

My command line  terminal macOS (Monterey) : 
(sudo) yt-dlp -Uv -f bestvideo+bestaudio/best --no-check-certificate --download-archive archive.txt --merge-output-format MKV -i --all-subs --embed-subs --add-metadata --write-info-json --write-description -o "%(uploader)s/%(upload_date)s - %(title)s %(id)s.%(ext)s" --yes-playlist  "https://www.youtube.com/c/SundayAfternoonModular/videos"

Conversion webm --> MKV failed.

Tried ffmpeg 5 and 4.4.1
Tried with/without "sudo"
I use Python 3.9.9 as advised
I use youtube-dl 2021.12.17

**Comment by NanaMizukiAnother7** [comment]
Can you please use [the YT-DLP version of FFmpeg](https://github.com/yt-dlp/FFmpeg-Builds)?

**Comment by vvglyy** [comment]
> Can you please use [the YT-DLP version of FFmpeg](https://github.com/yt-dlp/FFmpeg-Builds)?

No... Binaries not existing for macOS

**Comment by dirkf** [comment]
More to the point, please raise the issue at https://github.com/yt-dlp/yt-dlp/issues!

**Comment by vvglyy** [comment]
Sorry wrong github)
