### ISSUE TITLE
Chapter Extraction Support

### ISSUE THREAD

**Issue by CharlesCanlom** [ytdl-org/youtube-dl#30739]
## Checklist

- Extract chapters from YouTube and turn them into a .chapters file.

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I've wanted to put chapters from YouTube videos so I can easily jump from one chapter to another.

**Comment by pukkandan** [comment]
Chapters are already extracted and made available in the info.json. With `--add-metadata`, you can embed the chapter info in the video file

**Comment by dirkf** [comment]
@CharlesCanlom, it looks like that matches what you're looking for?

**Comment by CharlesCanlom** [comment]
Yep

**Comment by gerori** [comment]
已经收到您的来信，谢谢
