### ISSUE TITLE
Audio from youtube playlist not converted to mp3

### ISSUE THREAD

**Issue by alex4200** [ytdl-org/youtube-dl#30734]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

Part of the verbose log: 

```
$ youtube-dl -v --yes-playlist --audio-format mp3 https://www.youtube.com/playlist?list=PLgtfSiKjx3eDcbBThQPYJt8Mw1Bvs2Poa
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--yes-playlist', '--audio-format', 'mp3', 'https://www.youtube.com/playlist?list=PLgtfSiKjx3eDcbBThQPYJt8Mw1Bvs2Poa']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.9 (CPython) - Darwin-21.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.0, ffprobe 5.0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] PLgtfSiKjx3eDcbBThQPYJt8Mw1Bvs2Poa: Downloading webpage
[download] Downloading playlist: Station Eleven Soundtrack
[youtube:tab] playlist Station Eleven Soundtrack: Downloading 33 videos
[download] Downloading video 1 of 33
[youtube] -XHqXhET5rQ: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] Turn Around, Look At Me (Remastered 2003)--XHqXhET5rQ.webm has already been downloaded and merged
[download] Downloading video 2 of 33
[youtube] zsmoBe8sEOk: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] Jingle Bells-zsmoBe8sEOk.webm has already been downloaded and merged
[download] Downloading video 3 of 33
[youtube] pv1wSDoV9U4: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[download] Toccata in D Minor, BWV 913 - II. Fuga - Presto-pv1wSDoV9U4.webm has already been downloaded and merged
[download] Downloading video 4 of 33
[youtube] ClGZsqwhckA: Downloading webpage
```

## Description

I am trying to download a youtube playlist and to convert the audios to mp3, but all of the files are either `mkv`, `mp4` or `webm`. None of the files have been converted to `mp3`, and there were no errors or warnings. 

Command used:

```
youtube-dl -v --yes-playlist --audio-format mp3 https://www.youtube.com/playlist?list=PLgtfSiKjx3eDcbBThQPYJt8Mw1Bvs2Poa
```

OS: MacOS Monterey 12.2.1

**Comment by october262** [comment]
try again with --extract-audio, youtube-dl -v --yes-playlist --extract-audio --audio-format mp3 https://www.youtube.com/playlist?list=PLgtfSiKjx3eDcbBThQPYJt8Mw1Bvs2Poa

**Comment by dirkf** [comment]
You have to tell yt-dl to extract the audio (`-x`/`--extract-audio`) as well as what format you want:
```
       --audio-format FORMAT
              Specify  audio  format:  "best",  "aac",  "flac",  "mp3", "m4a",
              "opus", "vorbis", or "wav"; "best" by default; No effect without
              -x
```
I have no idea what terrible consequence might have followed if `--audio-format ...` had implied `--extract-audio`, but we can't change it now.

**Comment by rautamiekka** [comment]
It wouldn't be a good idea to make it implicative cuz you'd have to keep even more commands/configs handy for when you actually wanna extract, which is why my commands/configs are always as complete like that as possible.

**Comment by alex4200** [comment]
Ah yes, sure, I just forgot that command line option. Sorry for the confusion. I will leave the ticket open regarding the comment from @rautamiekka

**Comment by dirkf** [comment]
I think it's settled.
