### ISSUE TITLE
Build youtube-dl for Python3 – no longer works in macOS 12

### ISSUE THREAD

**Issue by section83** [ytdl-org/youtube-dl#30746]
## Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

This is more of advice to macOS users.  As promised some time ago, Apple has removed Python2.7 from macOS.  That was done in macOS 12.3 released on 14 March 2022. Running youtube-dl causes an error: "env: python: No such file or directory".  macOS 12.3 users will need to use an alternate e.g. YT-DLP.

Can youtube-dl be built for Python3 ?

**Comment by dirkf** [comment]
Just make `/usr/local/bin/python` a link to wherever Apple put Python3. Or try something like [this advice](https://opensource.com/article/19/5/python-3-default-mac).

If your system has no Python, how would (carefully written version-independent) Python programs be able to run? yt-dl just wants your Python version >=2.6.

See also, in Debian systems, the _python-is-python3_ package.

**Comment by section83** [comment]
Easy for some but, macOS 12.3+ does not have a Python install at all.

Apple has advised developers to include a Python runtime with their Python apps.  Apple's approach has the benefit of ensuring the correct version of Python is available for every app.  But, some macOS users might end up with a lot of Python installs.

The macOS version of YT-DLP has Python3.8 included.

**Comment by rautamiekka** [comment]
Just install Python 2.7.

^ Hell, even better: install Miniconda and create conda envs for every version.
Close to the bottom in https://repo.anaconda.com/miniconda/ you'll find files, for Python 3.9.x version of Miniconda, named:
```bash
Miniconda3-py39_4.11.0-MacOSX-x86_64.pkg
Miniconda3-py39_4.11.0-MacOSX-x86_64.sh
```
As one who doesn't have a Mac but aware it has its equivalent to `DEB`ian packages (maybe more like Snap, dunno), I presume the `pkg` one is the one you'd want.

**Comment by dirkf** [comment]
Installing Py2.7 probably isn't the best answer.

Apart from Miniconda:

https://www.python.org/downloads/macos/

or

https://github.com/macadmins/python/releases/download/v3.9.10.02082022223633/python_recommended_signed-3.9.10.02082022223633.pkg

We need to update the installation instructions for macOS at least, so I'd like to hear from Mac users what is their preferred way to install Python.

**Comment by rautamiekka** [comment]
> Installing Py2.7 probably isn't the best answer.

I can agree, and AFAIK ytdl works fine with 3.10 (I replaced with yt-dlp); install 2.7.x only if absolutely necessary, or if you use conda.

**Comment by section83** [comment]
>I'd like to hear from Mac users what is their preferred way to install Python.

Mac developers will make their own arrangements.  Mac users will avoid getting into the weeds.  It's easier for users if app  builds can include Python3.8+.  That would be consistent with Apple's advice.  It would also be easier for developers who would otherwise have to add a Python install/uninstall process to their apps.  [This build script would be fine](https://github.com/yt-dlp/yt-dlp/blob/master/.github/workflows/build.yml) – but, would be more backwards compatible if built on a macOS 10.15 runner instead of macOS 11.

**Comment by alcayaga** [comment]
For the moment you can execute it as `python3 /usr/local/bin/youtube-dl`

It will prompt you to download the developer tools if you don't have them already installed

**Comment by section83** [comment]
>It will prompt you to download the developer tools if you don't have them already installed

Yes, but, this is not best for users of my applet who don't want/need developer tools as well as the apps they are using.

Anyway. I have the impression that _youtube-dl_ is not being maintained.

**Comment by rautamiekka** [comment]
> _youtube-dl_ is not being maintained.

https://github.com/ytdl-org/youtube-dl/commits/master disagrees.

**Comment by section83** [comment]
Sorry.  Good to see.

**Comment by rautamiekka** [comment]
You do still have a point, though.

**Comment by dirkf** [comment]
>It will prompt you to download the developer tools if you don't have them already installed

Some number of GB later ...
