### ISSUE TITLE
Hello, please implement such websites

### ISSUE THREAD

**Issue by tvnewsrtp** [ytdl-org/youtube-dl#30741]
Hello, please implement such websites
https://rutube.ru/
https://www.bbc.co.uk/
https://www.tf1.fr/
https://www.tvnow.ch/
https://www.tf1info.fr/
https://zen.yandex.ru

## Checklist

- [ ] I'm reporting a feature request
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Except for the last, these sites are already supported. If there is a problem with that support, please open an issue for the problem site using the [Broken site support template](https://github.com/ytdl-org/youtube-dl/issues/new?template=1_broken_site.md).

Regarding zen.yandex.ru, please open a new issue using the [Site support request template](https://github.com/ytdl-org/youtube-dl/issues/new?labels=site-support-request&template=2_site_support_request.md).
