### ISSUE TITLE
Can I specify the video protocol for the -g option？

### ISSUE THREAD

**Issue by TXYH1** [ytdl-org/youtube-dl#30749]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Hello, I would like to know if it is possible to control the stream format obtained by the -g option. At present, the youtube live broadcasts I pull back seem to be in m3u8. Is there a way for me to obtain other formats of the video, such as flv? Also, is the resolution of the video controllable? thanks

**Comment by MuenchenSued** [comment]
you can use the -F option to see all formats and you can use -f {format] -g to get the link of a special resolution/format

**Comment by pukkandan** [comment]
Youtube livestreams are offered in dash and m3u8, but youtube-dl can't download live dash videos. So only the m3u8 formats are shown in `-F`

**Comment by TXYH1** [comment]
> you can use the -F option to see all formats and you can use `-f [format] -g` to get the link of a special resolution/format

@MuenchenSued Thank you for your answer, but I tried the -F option, but nothing is output, like in this picture

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/30724518/158722903-5f48511e-c576-49a6-9f27-cdaec6dbb72f.png">

**Comment by TXYH1** [comment]
> Youtube livestreams are offered in dash and m3u8, but youtube-dl can't download live dash videos. So only the m3u8 formats are shown in `-F`

@pukkandan Thank you, so the stream address of what protocol can be obtained is related to the merchant, right? For example, if twitch provides it, then the -F option may be able to obtain addresses in multiple formats.

**Comment by TXYH1** [comment]
Also, can the -g option get addresses in batches? I may want to pull multiple addresses at one time in the code. Or is it recommended to encapsulate it for batch operations, will the performance be poor?

**Comment by pukkandan** [comment]
`-f f1,f2,f3 -g`

**Comment by TXYH1** [comment]
> `-f f1,f2,f3 -g`

@pukkandan This seems to pull multiple formats of the same video, right? I hope different URLs can be pulled, such as

**Comment by pukkandan** [comment]
`youtube-dl -g "URL1" "URL2"`
