### ISSUE TITLE
Special character support and problems with output folder

### ISSUE THREAD

**Issue by AstronomicalLandscape** [ytdl-org/youtube-dl#30758]
I've got an issue with the software. Actually, the path where my output folder is contains special characters like "é", "è" and "à", and when I specify In the configuration file the path, youtube-dl creates a new folder.

So, I decided to put the path in command line, as such : youtube-dl <link> -o <path> 
But, even this, it doesn't work, the software put the video file in the root folder of youtube-dl.

**Comment by 89z** [comment]
Please provide full path to this "output folder", as well as full example YouTube-DL command.

**Comment by AstronomicalLandscape** [comment]
Ok I understand.

Actually the path is : -o E:\<User>\Vidéos\Téléchargement\<config line fur Youtube-DL>, but even if I type this, it doesn't work.

I'll update youtube-dl and I'll see

**Comment by 89z** [comment]
Please provide full example YouTube-DL command.

**Comment by AstronomicalLandscape** [comment]
Sorry i didn't understand in fact ^^
Here is the command line : 
youtube-dl https://www.youtube.com/watch?v=VgD93an8rR4&t=1709s -o E:\Vidéos\Youtube\%(title)s.%(ext)s

**Comment by AstronomicalLandscape** [comment]
Ok so i found my first issues ( "\" missingafter "Youtube")

**Comment by 89z** [comment]
this is not a correct command in most shells:

~~~
youtube-dl https://www.youtube.com/watch?v=VgD93an8rR4&t=1709s
-o E:\Vidéos\Youtube%(title)s.%(ext)s
~~~

as `&` is a meta character, that needs to be quoted or escaped. Please address that, and if problem continues, comment again with updated command.

**Comment by AstronomicalLandscape** [comment]
Ok, if I correctly understand, the " & " in the link creates the issue ?

**Comment by 89z** [comment]
Im sorry, but I think its beyond the scope of this issue tracker, to teach you how to use your own shell.

**Comment by AstronomicalLandscape** [comment]
No problem, the problem is solved :
youtube-dl https://www.youtube.com/watch?v=60mf61gITsw -o E:\Vidéos\Youtube\%(title)s.%(ext)s
When I type this, it downloads in the right folder with the right path.

but with the last command (-o E:\Vidéos\Youtube\%(title)s.%(ext)s) I wanted to type this in the configuration file, but when I do this, it creates a new folder, without the special caracters, and it is really weird

**Comment by dirkf** [comment]
Put the URL inside `""`.

Or escape shell characters (`(`, `&`, ...) with `^`

Although
>... it's beyond the scope of this issue tracker, to teach you how to use your own shell,

this:
https://ss64.com/nt/

**Comment by AstronomicalLandscape** [comment]
Ok Thank you for taking the time to answer and help me, I’ll do my best to solve the problem 

Regards
