### ISSUE TITLE
Virtually Every Utube video i download d/ls at approx 50kb/s 

### ISSUE THREAD

**Issue by franny23dmt** [ytdl-org/youtube-dl#30752]
but when i try a mainstream supported utube video i get full speed.  this has been the same after every update since early 2020.     what is going on?  am i doing something incorrect?  d/l full quality better than 480p is a thing of my past.

**Comment by franny23dmt** [comment]
about to swap to teleG youtube downloader

**Comment by redweller** [comment]
Try suggestions from this post https://github.com/ytdl-org/youtube-dl/issues/30715
Using the latest version from repo worked for me
