### ISSUE TITLE
yt-dlp视频使用方法

### ISSUE THREAD

**Issue by Clay23142** [ytdl-org/youtube-dl#30778]
能做一个视频的详细使用方法吗？我看不懂

**Comment by pickfire** [comment]
https://github-com.translate.goog/ytdl-org/youtube-dl?_x_tr_sl=en&_x_tr_tl=zh-CN&_x_tr_hl=en&_x_tr_pto=wapp

**Comment by dirkf** [comment]
翻译手册页面是否有帮助？

否则，张贴您问题的更多细节。

不幸的是，我必须依靠谷歌翻译。 

(This is what Google does to ...

>Does the translated manual page help?

>Otherwise, post more details of your problem.

>Unfortunately, I must rely on Google Translate.
)

**Comment by 89z** [comment]
DeepL better:

> Can you make a video with details on how to use it? I can't see it.

**Comment by pickfire** [comment]
此外，可以用 https://github.com/soimort/you-get，这有中文翻译。

**Comment by dirkf** [comment]
I hope that solves your problem. We don't have translations for yt-dl.

Or, according to Google:

我希望解决你的问题。 我们没有YT-DL的翻译。
