### ISSUE TITLE
Youtube-dl still very slow download despite other bug reports marked as resolved.

### ISSUE THREAD

**Issue by Behinder** [ytdl-org/youtube-dl#30773]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
debug] System config: []
[debug] User config: [u'-o', u'~/youtube/%(title)s_%(resolution)s.%(ext)s', u'--prefer-ffmpeg', u'--max-sleep-interval', u'25', u'--socket-timeout', u'20', u'--min-sleep-interval', u'10', u'--batch-file', u'$HOME/ytdl-batch.txt', u'--download-archive', u'$HOME/ytdl-archive.txt']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=Ai36tIPQgI8']
[debug] Batch file urls: [u'https://www.youtube.com/watch?v=Ai36tIPQgI8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-135-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg N-100895-g633e344d96, ffprobe N-100895-g633e344d96
[debug] Proxy map: {}
[youtube] Ai36tIPQgI8: Downloading webpage
[youtube] Ai36tIPQgI8: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://manifest.googlevideo.com/api/manifest/dash/expire/1648227860/ei/tKE9Yp7TM9uigAeYt5TACw/ip/173.249.23.92/id/022dfab483d0808f/source/youtube/requiressl/yes/playback_host/rr5---sn-4g5e6nzz.googlevideo.com/mh/WL/mm/31%2C26/mn/sn-4g5e6nzz%2Csn-5hneknee/ms/au%2Conr/mv/u/mvi/5/pl/24/tx/24044261/txs/24044258%2C24044259%2C24044260%2C24044261/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/vprv/1/mt/1648205976/fvip/4/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgfqGpMKsySJwMC3QNxlgvGEQlnRWfjWJMkkcsm94nsOoCIQDrgSeABu9_194070M1nsfR_9Q04Ide8f2FQdJc_Suv3A%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl/lsig/AG3C_xAwRQIhAIQJhCwuNxEBuJrErPBQFTerU3waqHX7J6WeeRN6Cxw8AiAHK0NJVRY-mB2HGpXI7j-5zyzLwP7q3LbEc5uiFRgMiQ%3D%3D'
[download] Sleeping 24.13 seconds...
[dashsegments] Total fragments: 442
[download] Destination: /home/sebastian/youtube/AUM Basics - Looping (Using AUM for Live Looping)_1920x1080.f303.webm
[download] 100% of 91.98MiB in 00:46
[debug] Invoking downloader on u'https://rr5---sn-4g5e6nzz.googlevideo.com/videoplayback?expire=1648227860&ei=tKE9Yp7TM9uigAeYt5TACw&ip=173.249.23.92&id=o-AFaPxlpKxH0kveCrkySmrgt2d7QqcmvN6GzlFY_JaKa1&itag=140&source=youtube&requiressl=yes&mh=WL&mm=31%2C26&mn=sn-4g5e6nzz%2Csn-5hneknee&ms=au%2Conr&mv=u&mvi=5&pl=24&vprv=1&mime=audio%2Fmp4&ns=SpBG1n1pfyIXpFJmhQsUUj4G&gir=yes&clen=36523714&otfp=1&dur=2256.747&lmt=1596753911349168&mt=1648205976&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=6211222&n=CA_om5MefvvzmQ1yt-s&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAKTVrn-16Y082s6BxPdJqsADS-u6jPuRgHnS4mXw-xQbAiBicXN6zOCg3zu8z1DzgGEny38NEtryBdpFbwIHPqZgzw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRgIhALJ2CMi4OlZbTKnJ-O3leH3h11hNfk4IH97eBNK7lcYGAiEAklW--0WrmegEc6o2Z7pCyvySgWdA2qJ8Gn55KSI-kFU%3D'
[download] Sleeping 22.97 seconds...
[download] Destination: /home/sebastian/youtube/AUM Basics - Looping (Using AUM for Live Looping)_NA.f140.m4a
[download]  41.4% of 34.83MiB at 43.44KiB/s ETA 08:01
```

## Description

WRITE DESCRIPTION HERE

Youtube-dl is still painfully slow to download with speed like 50-80KiB/s. I saw other issue closed as resolved but in reality it's not resolved. Suggestion for switching to `yt-dlp` gives better results but still slow. Sometimes video is faster like 17,82 MiB/s but audio is downloaded at very low KiB/s.  It doesn't matter if URL is processed from command-line or from batch file.

**Comment by Behinder** [comment]
Also worth mentioning that other software lilke Wondershare Uni Covnerter has no problem at all downloading videos from YouTube.

**Comment by dirkf** [comment]
Fixed yt-dl is the same speed as yt-dlp, depending on how you choose the downloader options.

Pending a new release, please consult issues of which this is a duplicate for advice on installing from the git master. You could start with the linked PR #30582.

**Comment by suntong** [comment]
> Pending a new release

Any ETA for the new release please?

```
Updating to version 2021.12.17 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
2021.12.17
```

I've already updated my youtube-dl to the newsiest version, but this 7min video, https://www.youtube.com/watch?v=mao6bPg3uQs, took nearly 30min to download.

**Comment by 89z** [comment]
No one owes you a release, and you don't get to decide when a release happens. If you want `master`, then just install it like everyone else:

```
pip install https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip
```

**Comment by suntong** [comment]
Easy, easy, I was just querying about ETA, not demanding a release.

I guess patience is necessary on *both* side.

Thanks for the `pip install` tip though. will try...

**Comment by GHO5TMEDO** [comment]
> No one owes you a release, and you don't get to decide when a release happens. If you want `master`, then just install it like everyone else:
> 
> ```
> pip install https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip
> ```

Easy , calm down, why so rude?

**Comment by 89z** [comment]
> Easy , calm down, why so rude?

I am going to quote my friend Howard [1], who I have much respect for:

> Some folks may think responses like this are uncalled for. Think again.
>
> You would not walk into the kitchen of a gourmet restaurant and ask the head chef to teach you how to boil a pot of water. The question itself is rude; it's inconsiderate of you to waste people's time with such questions that you should have found the answer to long before.
>
> Every thing that I put out on the web is the result of intense thought. I expect the same of all of you. Think before you post.

1. http://lists.mplayerhq.hu/pipermail/rtmpdump/2011-September/001618.html

**Comment by suntong** [comment]
> You would not walk into the kitchen of a gourmet restaurant and ask the head chef to teach you how to boil a pot of water.

May someone tell me how that metaphor can have any relation with this situation please?

I don't know how many people build their youtube-dl from git, but I believe the majority of us depend on the release build and auto update; and youtube-dl is supposed to work for youtube after all, any other sites is more or less bells and whistles. 

Here is a better metaphor in my view -- the road into town have a big sink hole and the responsible people of the town inquired about such sink hole, yet they get chided for just asking.

**Comment by 89z** [comment]
> I don't know how many people build their youtube-dl from git, but I believe the majority of us depend on the release build and auto update; and youtube-dl is supposed to work for youtube after all, any other sites is more or less bells and whistles.

@suntong this repository and the maintainers, don't owe you anything at all. In fact, they could disable the issue tracker entirely, should they choose to, or even charge for solving any issues. Many people forget the simple fact that YouTube-DL, along with many other packages on GitHub, **is free software**, and includes not warranty at all [1]:

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

So if you don't like the software, don't use it. If you don't like the release schedule, find some other software with a better schedule. What you definitely *should not do*, is come on the issue tracker and become the 999th person to complain about no recent release. If you had done even the most cursory search, you would notice that people have been asking for this over [2], and over [3] and over [4] again. So hopefully the following quote can now make more sense to you:

> The question itself is rude; it's inconsiderate of you to waste people's time with such questions that you should have found the answer to long before.

1. https://github.com/ytdl-org/youtube-dl/blob/2021.12.17/LICENSE#L16-L22
2. https://github.com/ytdl-org/youtube-dl/issues/31190
3. https://github.com/ytdl-org/youtube-dl/issues/31067
4. https://github.com/ytdl-org/youtube-dl/issues/29753

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31253

**Comment by distresscode** [comment]
Any update on this?

**Comment by 89z** [comment]
> Here is a better metaphor in my view -- the road into town have a big sink hole and the responsible people of the town inquired about such sink hole, yet they get chided for just asking, by some bystanders.

@suntong OK then, here is what a well-adjusting person *should* do in your situation. First realize no recent release for YouTube-DL. Then check if anyone else has reported the problem [1]. Then realize the issue has been posted again [2] and again [3] and again [4] and again [5] and again [6].

1. https://github.com/ytdl-org/youtube-dl/search?q=release&type=issues
2. https://github.com/ytdl-org/youtube-dl/issues/29753
3. https://github.com/ytdl-org/youtube-dl/issues/31067
4. https://github.com/ytdl-org/youtube-dl/issues/31190
5. https://github.com/ytdl-org/youtube-dl/issues/31234
6. https://github.com/ytdl-org/youtube-dl/issues/31251
