### ISSUE TITLE
Is this an issue? Will it still produce valid video file?

### ISSUE THREAD

**Issue by hasnogaems** [ytdl-org/youtube-dl#30781]
And maybe there is a way to fix?
https://i.imgur.com/KuH1Pa2.png
Edit:
Now I have this https://i.imgur.com/WNVZCQe.png It is the same twitch livestream I downloading.

**Comment by m42km** [comment]
I don't think it's a problem, usually youtube-dl downloads second by second which is why ffmpeg output looks like that

**Comment by QuickHare** [comment]
This is not an issue and you shouldn't be alarmed.

Basically, some videos are stored as nice, whole files. Others are stored as small pieces of video, each roughly up to five seconds in length. Pieces are also very common when streaming live video as it's not known how long the video will last.

What you're seeing are the notifications for each piece downloading, plus more output for ffmpeg putting them back together again. The coloured parts are information concerning pieces that could be retrieved, that don't apply to the quality settings or other things that happen over the internet.

I hope this helps!

**Comment by dirkf** [comment]
If OP posted the verbose log, or at a pinch attached the screenshot, the issue would be clearer.
