### ISSUE TITLE
ITV -  BadStatusLine

### ISSUE THREAD

**Issue by uckthis** [ytdl-org/youtube-dl#30789]
--all-subs --skip-download https://www.itv.com/hub/love-island/2a3697a0231

[ITV] 2a3697a0231: Downloading webpage
ERROR: Unable to download webpage: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
>... Be sure to call youtube-dl with the --verbose flag and include its complete output.

Yes, please.

**Comment by uckthis** [comment]
C:\Users\Waqas>youtube-dl --verbose https://www.itv.com/hub/love-island/2a3697a0231
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.itv.com/hub/love-island/2a3697a0231']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 25.160.196.218 (GB) as X-Forwarded-For.
[ITV] 2a3697a0231: Downloading webpage
ERROR: Unable to download webpage: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\utils.py", line 2737, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1186, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1227, in getresponse
  File "C:\Python\Python34\lib\http\client.py", line 386, in begin
  File "C:\Python\Python34\lib\http\client.py", line 356, in _read_status

  File "C:\Python\Python34\lib\http\client.py", line 356, in _read_status


C:\Users\W>

**Comment by dirkf** [comment]
And this is playable in your browser?

With yt-dl 2021.12.17, extraction fails in the usual way, not as above:
```
[ITV] 2a3697a0231: Downloading webpage
[ITV] 2a3697a0231: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError())...
```

With the pending PR #30266:
```
$ python -m youtube_dl -v -F 'https://www.itv.com/hub/love-island/2a3697a0231' 
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.itv.com/hub/love-island/2a3697a0231']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Git HEAD: 0945174fa
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[debug] Using fake IP 25.80.219.79 (GB) as X-Forwarded-For.
[ITV] 2a3697a0231: Downloading webpage
[ITV] 2a3697a0231: Downloading JSON metadata
[ITV] 2a3697a0231: Downloading m3u8 information
[info] Available formats for 2a3697a0231:
format code  extension  resolution note
hls-104      mp4        audio only  104k , mp4a.40.2@ 97k
hls-286      mp4        512x288     286k , avc1.4D401F@ 172k, 25.0fps, mp4a.40.2@ 97k
hls-565      mp4        512x288     565k , avc1.4D401F@ 435k, 25.0fps, mp4a.40.2@ 97k
hls-769      mp4        512x288     769k , avc1.4D401F@ 628k, 25.0fps, mp4a.40.2@ 97k
hls-1072     mp4        896x504    1072k , avc1.4D401F@ 914k, 25.0fps, mp4a.40.2@ 97k
hls-1662     mp4        896x504    1662k , avc1.4D401F@1470k, 25.0fps, mp4a.40.2@ 97k (best)
```

The message `BadStatusLine` typically means that an empty response was returned to the Python HTTP library.

**Comment by uckthis** [comment]
Yes, it runs in the browser and the show plays; which means that proxy is working. I need to download subtitles in the batch, that's why I need it; otherwise it's working in the browser and other downloading apps (who don't do batch).

**Comment by dirkf** [comment]
Please try again. If the error persists, try `--user-agent 'Mozilla/5.0'`, or perhaps simulate an old iPhone `--user-agent ' Mozilla/5.0 (iPhone; U; CPU like Mac OS X; en) AppleWebKit/420+ (KHTML, like Gecko) Version/3.0 Mobile/1A543a Safari/419.3'`.

See also #30544, which you and I should have noted earlier.
