### ISSUE TITLE
Unable to resolve host address ‘yt-dl.org’

### ISSUE THREAD

**Issue by Lefia** [ytdl-org/youtube-dl#30797]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

When I tried to install youtube-dl in WSL through wget, it gave me the error as follow :
```
>  sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
--2022-03-31 22:47:05--  https://yt-dl.org/downloads/latest/youtube-dl
Resolving yt-dl.org (yt-dl.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘yt-dl.org’
``` 
Hope someone can help me with this.

**Comment by 89z** [comment]
Just use `pip install youtube-dl`...

**Comment by 89z** [comment]
Looks like your problem:

~~~
PS C:\> pip install youtube-dl
Collecting youtube-dl
  Using cached youtube_dl-2021.12.17-py2.py3-none-any.whl (1.9 MB)
Installing collected packages: youtube-dl
Successfully installed youtube-dl-2021.12.17
~~~

I would suggesting trying outside of WSL. For example, download this file:

https://nuget.org/api/v2/package/python/3.10.4

rename to `python.zip` and extract. Then run:

~~~
python -m pip install youtube-dl
~~~

**Comment by Lefia** [comment]
It works well outside the WSL. Maybe there's somthing wrong with it. Thanks you for your help!

**Comment by gamer191** [comment]
@Lefia Are you sure that your WSL installation is connected to the internet? Try running `ping google.com` inside it

**Comment by Lefia** [comment]
@gamer191 I found the problem was that WSL would auto regenerate the resolv.conf and reset the nameserver IP address, which caused the network connection issue. So it's all right now after I changed the nameserver to 1.1.1.1
