### ISSUE TITLE
[Bitchute] ERROR: No video formats found; 

### ISSUE THREAD

**Issue by ripspin5** [ytdl-org/youtube-dl#30799]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```ShellSession
youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

youtube-dl --verbose https://www.bitchute.com/video/35RdEJNoFDgR/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.bitchute.com/video/35RdEJNoFDgR/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.12 (CPython) - Linux-4.9.58-x86_64-with-glibc2.7
[debug] exe versions: ffmpeg 2.8.11, ffprobe 2.8.11, rtmpdump 2.4
[debug] Proxy map: {}
[BitChute] 35RdEJNoFDgR: Downloading webpage
[BitChute] 35RdEJNoFDgR: Checking video URL
[BitChute] 35RdEJNoFDgR: video URL is invalid, skipping: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/bitchute.py", line 66, in _real_extract
    self._sort_formats(formats)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Confirmed. The URL in the `<video>` element gives 404.

As you didn't use the right template I applied it for you. Please complete the missing parts.

**Comment by ripspin5** [comment]
I don't know how to use the right template, please help
What missing parts should I complete?

The error requested me to report the problem, I didn't find any similar problems, so I reported what happened

Regards ripspin


     On Friday, 1 April 2022, 09:50:53 pm AEDT, dirkf ***@***.***> wrote:  
 
 


Confirmed. The URL in the <video> element gives 404.

As you didn't use the right template I applied it for you. Please complete the missing parts.

**Comment by dirkf** [comment]
Sorry, the update to your original post somehow disappeared. All good now. As you can see there are two further steps to make a valid bug report.

Regarding content, I would just say that if a headline or programme title ends in a question-mark, that's almost always because the answer to the question is "No". Medical breakthroughs typically appear in scholarly journals rather than internet videos.

**Comment by 89z** [comment]
https://wikipedia.org/wiki/Betteridge%27s_law_of_headlines

**Comment by ripspin5** [comment]
Thank you for the information regarding question marks in title
I did not know that
Not sure how it relates to my bug report
I see another similar report now by KexoTV
I am not able to get bitchute videos to play (on palemoon & seamonkey) I get: https://www.bitchute.com/ fine but when I click on a video I just get the wavy vertical lines

There is no need for "I've searched the bugtracker" now as there is a similar report

Regards ripspin

**Comment by dirkf** [comment]
> I am not able to get bitchute videos to play (on ... seamonkey)

Likewise.

Apparently the yt-dlp extractor works:
```
$ python3.9 -m yt_dlp -v -F 'https://www.bitchute.com/video/35RdEJNoFDgR/' 
[debug] Command-line config: ['-v', '-F', 'https://www.bitchute.com/video/35RdEJNoFDgR/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: ad210f4fd
[debug] Python version 3.9.7 (CPython 32bit) - Linux-4.4.0-210-generic-i686-with-glibc2.23
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Optional libraries: certifi, sqlite
[debug] Proxy map: {}
[debug] [BitChute] Extracting URL: https://www.bitchute.com/video/35RdEJNoFDgR/
[BitChute] 35RdEJNoFDgR: Downloading webpage
[BitChute] 35RdEJNoFDgR: Checking video URL
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 35RdEJNoFDgR:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 unknown    │ https │ unknown unknown
$
```

A back-port is needed.
