### ISSUE TITLE
Cannot download from Tver.jp

### ISSUE THREAD

**Issue by gsool9988** [ytdl-org/youtube-dl#30804]
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl https://tver.jp/episodes/ep6cfxjqw7 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://tver.jp/episodes/ep6cfxjqw7', '-v']
[debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 2022-01-19-git-dd17c86aa1-full_build-www.gyan.dev, ffprobe 2022-01-19-git-dd17c86aa1-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] ep6cfxjqw7: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ep6cfxjqw7: Downloading webpage
[generic] ep6cfxjqw7: Extracting information
ERROR: Unsupported URL: https://tver.jp/episodes/ep6cfxjqw7
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 3489, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://tver.jp/episodes/ep6cfxjqw7
```

## Description

Yesterday & today, the site "Tver.jp" has been renewed, and the site appearance & URL systems are all changed.
So now, we cannot download videos from tver.jp by the latest version 2021.12.17 of youtube-dl.

**Comment by skypeleft** [comment]
Yes, tver.jp has been changing the code more thing... I think the anti download code has been changed too.

**Comment by dirkf** [comment]
If you'd bothered to check
>- [ ] I've searched the bugtracker for similar issues including closed ones

you'd have found issue #30798 and not needed to open this duplicate.

**Comment by gsool9988** [comment]
Sorry for not paying attention to search similar issue, and thank you for taking care of it
