### ISSUE TITLE
Apple TV

### ISSUE THREAD

**Issue by 89z** [ytdl-org/youtube-dl#30808]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

~~~
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '275-0', 'https://tv.apple.com/us/show/ted-lasso/umc.cmc.vtoh0mn0xn7t3c643xqonfzy']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.4 (CPython) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 2021-06-30-git-de8e6e67e7-essentials_build-www.gyan.dev, ffprobe 5.0-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[generic] umc.cmc: Requesting header
WARNING: Falling back on generic information extractor.
[generic] umc.cmc: Downloading webpage
[generic] umc.cmc: Extracting information
[generic] playlist.m3u8?cc=US&svcId=tvs.vds.4105&a=1571413984&isExternal=true&brandId=tvs.sbd: Downloading m3u8 information
WARNING: Unknown codec dvh1.05.01
WARNING: Unknown codec dvh1.05.01
WARNING: Unknown codec dvh1.05.03
WARNING: Unknown codec dvh1.05.06
[debug] Invoking downloader on 'https://vod-ak-aoc.tv.apple.com/itunes-assets/VideoPreview125/v4/23/0b/d2/230bd2d6-6185-9c7c-c49e-0aa45ab0acb5/P343768070_A1571413984_video_gr505_sdr_508x254_-.m3u8'
~~~

## Description

https://tv.apple.com/us/show/ted-lasso/umc.cmc.vtoh0mn0xn7t3c643xqonfzy

YouTube-DL just downloads preview, instead of full episode. Site requires login, free trial is available.

**Comment by dirkf** [comment]
>YouTube-DL just downloads preview, instead of full episode

I expect that the reason for this that the full content is afflicted with DRM.

Let us know if you have evidence to the contrary.

**Comment by october262** [comment]
> 



> ## Checklist
> * [x]  I'm reporting a broken site support
> * [x]  I've verified that I'm running youtube-dl version **2021.12.17**
> * [x]  I've checked that all provided URLs are alive and playable in a browser
> * [x]  I've checked that all URLs and arguments with special characters are properly quoted or escaped
> * [x]  I've searched the bugtracker for similar issues including closed ones
> 
> ## Verbose log
> ```
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['-v', '-f', '275-0', 'https://tv.apple.com/us/show/ted-lasso/umc.cmc.vtoh0mn0xn7t3c643xqonfzy']
> [debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
> [debug] youtube-dl version 2021.12.17
> [debug] Python version 3.10.4 (CPython) - Windows-10-10.0.18363-SP0
> [debug] exe versions: ffmpeg 2021-06-30-git-de8e6e67e7-essentials_build-www.gyan.dev, ffprobe 5.0-essentials_build-www.gyan.dev
> [debug] Proxy map: {}
> [generic] umc.cmc: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] umc.cmc: Downloading webpage
> [generic] umc.cmc: Extracting information
> [generic] playlist.m3u8?cc=US&svcId=tvs.vds.4105&a=1571413984&isExternal=true&brandId=tvs.sbd: Downloading m3u8 information
> WARNING: Unknown codec dvh1.05.01
> WARNING: Unknown codec dvh1.05.01
> WARNING: Unknown codec dvh1.05.03
> WARNING: Unknown codec dvh1.05.06
> [debug] Invoking downloader on 'https://vod-ak-aoc.tv.apple.com/itunes-assets/VideoPreview125/v4/23/0b/d2/230bd2d6-6185-9c7c-c49e-0aa45ab0acb5/P343768070_A1571413984_video_gr505_sdr_508x254_-.m3u8'
> ```
> 
> ## Description
> https://tv.apple.com/us/show/ted-lasso/umc.cmc.vtoh0mn0xn7t3c643xqonfzy
> 
> YouTube-DL just downloads preview, instead of full episode. Site requires login, free trial is available.

Apple TV uses DRM, there is a product that does remove  the DRM protection

**Comment by 89z** [comment]
@october262 you're probably right, but do you have any evidence?

**Comment by october262** [comment]
> @october262 you're probably right, but do you have any evidence?

see here - https://en.wikipedia.org/wiki/FairPlay

**Comment by 89z** [comment]
I know what FairPlay is, but you've yet to provide any evidence that its actually used on Apple TV. Again, you are probably right, but if the issue is going to be closed, I would rather have something concrete to point to, rather than one unsourced comment.

**Comment by october262** [comment]
> I know what FairPlay is, but you've yet to provide any evidence that its actually used on Apple TV. Again, you are probably right, but if the issue is going to be closed, I would rather have something concrete to point to, rather than one unsourced comment.

is this good enough ?? - https://www.reddit.com/r/appletv/comments/sl1d11/how_do_i_remove_drm_from_my_purchased_apple_tv/

**Comment by 89z** [comment]
Evidence wise, ideally what we want is something like this:

<https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2021/08/31/1940767811923/993595_fp_precon_hls/THE_HARPER_HOUSE_101_8CH_clean_993576_2100/stream.m3u8>

If you open that, you see this:

~~~
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://cbsi.live.ott.irdeto.com/streaming/getckc?CrmId=cbsi&AccountId=cbsi&ContentId=eyT_RYkqNuH_6ZYrepLtxkiPO1HA7dIU&KeyId=3be8be93-7c98-4831-84b2-94173f9152af",KEYFORMATVERSIONS="1",KEYFORMAT="com.apple.streamingkeydelivery"
~~~

which is incontrovertible proof that the stream is using DRM. Now even with the link above, sometimes people can get creative and find non-DRM methods of extracting from a site. For example with ABC extractor, if you just access the HLS URL by itself, you get DRM. But if you add on a special query parameter, then DRM is removed.

This is why its important that someone saying "but DRM!" make a strong case for that. In my mind, DRM is the end of the conversation. So if I am going to "close the book" on a site, I want to make damn sure that DRM is the only option. With all due respect, I don't think you've done that yet.

**Comment by october262** [comment]
> Evidence wise, ideally what we want is something like this (from a Paramount video):
> 
> https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2021/08/31/1940767811923/993595_fp_precon_hls/THE_HARPER_HOUSE_101_8CH_clean_993576_2100/stream.m3u8
> 
> If you open that, you see this:
> 
> ```
> #EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://cbsi.live.ott.irdeto.com/streaming/getckc?CrmId=cbsi&AccountId=cbsi&ContentId=eyT_RYkqNuH_6ZYrepLtxkiPO1HA7dIU&KeyId=3be8be93-7c98-4831-84b2-94173f9152af",KEYFORMATVERSIONS="1",KEYFORMAT="com.apple.streamingkeydelivery"
> ```
> 
> which is incontrovertible proof that the stream is using DRM. Now even with the link above, sometimes people can get creative and find non-DRM methods of extracting from a site. For example with ABC extractor, if you just access the HLS URL by itself, you get DRM. But if you add on a special query parameter, then DRM is removed.
> 
> This is why its important that someone saying "but DRM!" make a strong case for that. In my mind, DRM is the end of the conversation. So if I am going to "close the book" on a site, I want to make damn sure that DRM is the only option. With all due respect, I don't think you've done that yet.

this here is a internal log file from another user that has streamfab drm downloader for apple TV -
[StreamFab.log](https://github.com/ytdl-org/youtube-dl/files/8411570/StreamFab.log)

**Comment by 89z** [comment]
> this here is a internal log file from another user that has streamfab drm downloader for apple TV - https://forum.dvdfab.cn/forum/software-support-english/youtube-to-mp3-youtube-video-downloader/404683-5-0-1-3-apple-tv post #7 there's mention of DRM local server

I have blocked @october262, they wont be able to comment further on this issue. Im sorry, but doing an internet search for "Apple TV DRM", is not the right way to answer this question. Also, the file in question is behind a login:

https://forum.dvdfab.cn/filedata/fetch?id=404741

If someone has actual evidence in the manner I have described, I will say no more and the issue can be closed. Until then, I think its fair for the issue to remain.

**Comment by dirkf** [comment]
Surely the onus is on you, as the OP, to find some AppleTV full content that plays with EME disabled. Obvs great if someone else has an example. That's why the site support template asks for example content.

**Comment by 89z** [comment]
> Surely the onus is on you, as the OP, to find some AppleTV full content that plays with EME disabled.

My goal with this issue, was to provide a place for people wanting Apple TV content, to discussion the issue. That goal has been accomplished, as the issue now exists. Ideally the end result will be, either an extractor is implemented, or the issue is closed because of DRM. Looking at the template, I dont see an issue with my post:

> - First of, make sure you are using the latest version of youtube-dl. Run `youtube-dl --version` and ensure your version is 2021.12.17. If it's not, see https://yt-dl.org/update on how to update. Issues with outdated version will be REJECTED.
> - Make sure that all provided video/audio/playlist URLs (if any) are alive and playable in a browser.
> - Make sure that site you are requesting is not dedicated to copyright infringement, see https://yt-dl.org/copyright-infringement. youtube-dl does not support such sites. In order for site support request to be accepted all provided example URLs should not violate any copyrights.
> - Search the bugtracker for similar site support requests: http://yt-dl.org/search-issues. DO NOT post duplicates.

Are you saying that, with any site support request, that the poster must prove that the site can serve non-DRM content? I think that is a large ask, as some sites offer DRM by default, but also offer the same content using non DRM methods. Examples of this include ABC and Paramount, and perhaps others. So putting that requirement on the poster would be bad I think, as the poster might not have the skill to find the secret methods of getting the content without DRM, where some other user might be able to find a way. By putting that requirement on the poster, some sites might never get implemented. Regardless, if that is the requirement, I think it should be expressed in the template, as I dont think it is currently:

> - Make sure that all provided video/audio/playlist URLs (if any) are alive and playable in a browser.

The link I gave satisfies that.

> - Make sure that site you are requesting is not dedicated to copyright infringement, see https://yt-dl.org/copyright-infringement. youtube-dl does not support such sites. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

The link I gave satisfies that.

**Comment by dirkf** [comment]
The question is, does the example link pass the non-EME test? No doubt the template was developed to help users of all ability levels to suggest sites, with the assumption that yt-dl devs would be able to weed out DRM'ed sites. As you are highly skilled in the art, it isn't unreasonable to expect you to find the answer.

**Comment by 89z** [comment]
> The question is, does the example link pass the non-EME test?

If you use the URL in a browser, the video plays via EME. However, you can say the same thing about this link:

https://abc.com/shows/greys-anatomy/episode-guide/season-18/12-the-makings-of-you

and yet, YouTube-DL has no problem with it:

~~~
PS D:\Desktop> youtube-dl.exe youtube-dl https://abc.com/shows/greys-anatomy/episode-guide/season-18/12-the-makings-of-you
ERROR: 'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:youtube-dl" ) to search YouTube
PS D:\Desktop> ^C
PS D:\Desktop> youtube-dl https://abc.com/shows/greys-anatomy/episode-guide/season-18/12-the-makings-of-you
[Go] 12-the-makings-of-you: Downloading webpage
[Go] VDKA26847512: Downloading JSON metadata
[Go] VDKA26847512: Downloading JSON metadata
[Go] VDKA26847512: Downloading m3u8 information
[download] Destination: The Makings of You-VDKA26847512.mp4
~~~

So I don't think the "EME test" is a good indicator of whats sites are valid to request.

> No doubt the template was developed to help users of all ability levels to suggest sites, with the assumption that yt-dl devs would be able to weed out DRM'ed sites. As you are highly skilled in the art, it isn't unreasonable to expect you to find the answer.

Yes I have some skill in this area, but I am humble enough to admit that I rely heavily on the skill and work of others, including yourself. If people can work together, the end result will usually be better, than if one person try to do everything themself.

**Comment by dirkf** [comment]
If the link plays with a browser that either has no EME support (SeaMonkey, say) or has it disabled, we know it wasn't DRMed (since EME is the API to WideVine or whatever). If it doesn't, there may still be some hidden non-DRM version, but we know we're working with the odds stacked against that. And despite your suspicion of internet searches to resolve the point, posts on other forums might help to identify such alternatives, or back doors if you will.

>If people can work together, the end result will usually be better, than if one person try to do everything themself.

Preaching to the choir, brother.

**Comment by 89z** [comment]
> If the link plays with a browser that either has no EME support (SeaMonkey, say) or has it disabled, we know it wasn't DRMed (since EME is the API to WideVine or whatever). If it doesn't, there may still be some hidden non-DRM version, but we know we're working with the odds stacked against that.

That's an interesting idea. However, it didn't seem to make a difference in this case. With EME enabled, both the AppleTV and ABC links played. With EME disabled, both AppleTV and ABC linked failed to play. So as you said, the EME test alone is not proof of anything, but I agree that its usually a bad sign. I just don't want to see people saying "oh it failed EME test, close issue", as that's not always the case.

**Comment by 89z** [comment]
I think I have a way to get these, but my free trial expired. So I am closing until someone can share an account

**Comment by 89z** [comment]
I am going to reopen this, as I found the root of trust today:

https://amp-account.tv.apple.com/account/web/config

will see if I can make an implementation
