### ISSUE TITLE
Bug issues.

### ISSUE THREAD

**Issue by kakshi0962z** [ytdl-org/youtube-dl#30807]
## Checklist

- [x] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by kakshi0962z** [comment]
Bug issues.

**Comment by jonathancross** [comment]
This should be closed.

**Comment by dirkf** [comment]
How true.
