### ISSUE TITLE
Setting output directory on Synology DSM 7 [YoutubeDL-Material]

### ISSUE THREAD

**Issue by bolshukhin** [ytdl-org/youtube-dl#30819]
Hello. It's my first time of use Youtube-dl started by Docker*.How I can change default folder ( Path: subscriptions  ) to my Downloads? And how I can change audio formats from .mp3 to flac? Thanks

Device based on DSM 7.0.1-42218 Update 2 

* https://registry.hub.docker.com/r/tzahi12345/youtubedl-material/
![image](https://user-images.githubusercontent.com/61148703/161703673-9eb32d62-959e-4f33-ab74-4abac7e199be.jpeg)

**Comment by rautamiekka** [comment]
Seemingly the GUI doesn't offer that option, so you need to edit the config, read the Linux parts of the readme here on GitHub.

**Comment by dirkf** [comment]
Otherwise, ask at https://github.com/Tzahi12345/YoutubeDL-Material/issues.

**Comment by dirkf** [comment]
If you need more help, reopen the issue.
