### ISSUE TITLE
DRM Protected

### ISSUE THREAD

**Issue by notgarrettt** [ytdl-org/youtube-dl#30814]
Is there away to get around drm protection? trying to download a movie I bought from youtube

**Comment by 89z** [comment]
If you have Firefox, it might be possible:

~~~
github.com/WaterfoxCo/Waterfox/issues/1895
~~~

note I just discovered this method yesterday, so I have not had time to full test it.

**Comment by dirkf** [comment]
Normally the easiest solution is to look for an alternative source that has not vandalised the content, especially compared with rebuilding a Firefox variant.

**Comment by baptx** [comment]
To bypass DRM, you can have a look at this issue where I shared the code that would need to be removed if you rebuild Firefox (I did not test it yet). Some scripts were also shared to bypass DRM:
https://github.com/WaterfoxCo/Waterfox/issues/1895
