### ISSUE TITLE
the app's args string parser has a very serious bug

### ISSUE THREAD

**Issue by mohsentux** [ytdl-org/youtube-dl#30817]
## Checklist

- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```ShellSession
PS C:\Users\Administrator> youtube-dl.exe https://youtu.be/VyWAvY2CF9c -v
[debug] System config: []
[debug] User config: ['--ignore-errors', '--continue', '--no-overwrites', '--download-archive', '-f', 'bestvideo[ext=mp4][width<2000][height<=1200]+bestaudio[ext=m4a]/bestvideo[ext=webm][width<2000][height<=1200]+bestaudio[ext=webm]/bestvideo[width<2000][height<=1200]+bestaudio/best[width<2000][height<=1200]/best', '--add-metadata', '--embed-thumbnail', '--external-downloader', 'aria2c', '--external-downloader-args', '-c -j 8 -x 8 -s 8 -k 1M', '-o', 'F:\\youtube_videos\\%(playlist_index)s-%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['https://youtu.be/VyWAvY2CF9c', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22000
[debug] exe versions: ffmpeg 2022-03-31-git-e301a24fa1-full_build-www.gyan.dev, ffprobe 2022-03-31-git-e301a24fa1-full_build-www.gyan.dev
[debug] Proxy map: {}
ERROR: 'bestvideo[ext=mp4][width<2000][height<=1200]+bestaudio[ext=m4a]/bestvideo[ext=webm][width<2000][height<=1200]+bestaudio[ext=webm]/bestvideo[width<2000][height<=1200]+bestaudio/best[width<2000][height<=1200]/best' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:bestvideo[ext=mp4][width<2000][height<=1200]+bestaudio[ext=m4a]/bestvideo[ext=webm][width<2000][height<=1200]+bestaudio[ext=webm]/bestvideo[width<2000][height<=1200]+bestaudio/best[width<2000][height<=1200]/best" ) to search YouTube
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 2364, in _real_extract
youtube_dl.utils.ExtractorError: 'bestvideo[ext=mp4][width<2000][height<=1200]+bestaudio[ext=m4a]/bestvideo[ext=webm][width<2000][height<=1200]+bestaudio[ext=webm]/bestvideo[width<2000][height<=1200]+bestaudio/best[width<2000][height<=1200]/best' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:bestvideo[ext=mp4][width<2000][height<=1200]+bestaudio[ext=m4a]/bestvideo[ext=webm][width<2000][height<=1200]+bestaudio[ext=webm]/bestvideo[width<2000][height<=1200]+bestaudio/best[width<2000][height<=1200]/best" ) to search YouTube

[youtube] VyWAvY2CF9c: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[youtube] VyWAvY2CF9c: Thumbnail is already present
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://rr4---sn-hpa7kn76.googlevideo.com/videoplayback?expire=1649102219&ei=K_lKYsTxHMKm8gPenoTgAw&ip=8.20.126.115&id=o-AEr7efj_yVkvgdfm4bpREoJLllydFbdyNM83niPDTv2d&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=fM&mm=31%2C26&mn=sn-hpa7kn76%2Csn-4g5ednds&ms=au%2Conr&mv=m&mvi=4&pl=24&initcwndbps=530000&spc=4ocVC-eoSq_BD6EZrNkOh5_uhPVP&vprv=1&mime=video%2Fwebm&ns=TojVDQad0x2ncsQyOWHrXtUG&gir=yes&clen=113996202&dur=5138.333&lmt=1596263790399043&mt=1649080155&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5432432&n=Bg4y8jbevD2H8p6gc&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgWbMbtNlw55-vt90uYUow26g4S6S_-PAsAKk_4Cy2jAoCIQDTMsqP-jYZ6cKr-TkjH2GA-N4koI8kczPg-WFgNzJ2FA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALVxUhUhjygIRx4R8Fbf-XrTJ1aZm7QtPT4QgDu2pf5XAiB2QHIrjd38uoBqaMbyRhig4cCZOar1fYCr4uRn9gJQGg%3D%3D'
[download] Destination: F:\youtube_videos\NA-Deep Learning Crash Course for Beginners.f248.webm
[debug] aria2c command line: aria2c -c -c -j 8 -x 8 -s 8 -k 1M --dir "F:\youtube_videos" --out "NA-Deep Learning Crash Course for Beginners.f248.webm.part" --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3665.3 Safari/537.36" --header "Accept-Encoding: gzip, deflate" --header "Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7" --header "Accept-Language: en-us,en;q=0.5" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" "--check-certificate=true" "--remote-time=true" -- "https://rr4---sn-hpa7kn76.googlevideo.com/videoplayback?expire=1649102219&ei=K_lKYsTxHMKm8gPenoTgAw&ip=8.20.126.115&id=o-AEr7efj_yVkvgdfm4bpREoJLllydFbdyNM83niPDTv2d&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=fM&mm=31%2C26&mn=sn-hpa7kn76%2Csn-4g5ednds&ms=au%2Conr&mv=m&mvi=4&pl=24&initcwndbps=530000&spc=4ocVC-eoSq_BD6EZrNkOh5_uhPVP&vprv=1&mime=video%2Fwebm&ns=TojVDQad0x2ncsQyOWHrXtUG&gir=yes&clen=113996202&dur=5138.333&lmt=1596263790399043&mt=1649080155&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5432432&n=Bg4y8jbevD2H8p6gc&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgWbMbtNlw55-vt90uYUow26g4S6S_-PAsAKk_4Cy2jAoCIQDTMsqP-jYZ6cKr-TkjH2GA-N4koI8kczPg-WFgNzJ2FA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALVxUhUhjygIRx4R8Fbf-XrTJ1aZm7QtPT4QgDu2pf5XAiB2QHIrjd38uoBqaMbyRhig4cCZOar1fYCr4uRn9gJQGg%3D%3D"
```

## Description

this bug has been around since I've been using youtube-dl. the problem is this: when I write the list of arguments, for some reasons if they are randomly (not logically significant) at a place in line that the app can't parse them I get error. for example this config at %APPDATA%\youtube-dl\config.txt has no error: https://pastebin.com/DBxFUjsH -- but if I so much as change a line disaster happens take a look and test for yourselves: https://pastebin.com/4FNHrTyt.
keep in mind this is not an issue with the os but the youtube-dl's buggy args parser. I've also had this problem on variety of linux-distors such as Ubuntu, OpenSuSe, Fedora and so on...
again it's obvious that the args parser is buggy it can't parse the passed strings correctly. in this example (among many) the -f option is processed independent of its following options. but if the order of the arguments are changed through the process of trial and error the bug disappears

**Comment by garoto** [comment]
`--download-archive` needs a filename.

**Comment by mohsentux** [comment]
> 

I get what you're getting at, That was obviously a mistake on my part. But experiment with it (besides `--download-archive`). I've had this problem for a very long time. I'm sure there's something to it.
Besides, technically the app itself should point these things out, not people's comments.
Think about it. It's simply not robust enough. I'm saying this because I too am a programmer and this behavior is very new and odd to me

**Comment by garoto** [comment]
I get what you're getting at as well. But remember that `youtube-dl` started as a hobby project and is in hard-maintenance mode for quite a while now. "PRs to improve the config parser are welcome" yada yada I guess.

p.s.: don't forget to delete all the leftover `-f` files the program have been generating with the wrong config args.

**Comment by mohsentux** [comment]
May I make commits to the project. I'm pretty good

**Comment by garoto** [comment]
You may submit Pull Requests, yes. If they get merged eventually depends on many things.

**Comment by dirkf** [comment]
Unfortunately `-f` is a valid, if unusual, filename. If you don't want that to be the name of your download archive file, better put the one you want.

Arguably a GNU-style CLI with `--arg_name=arg_value` could be less prone to such confusion, but then [Windows users would have to write `"--arg_name=arg_value"`](https://ss64.com/nt/syntax-esc.html). Plainly the CLI syntax is not going to change now.

**Comment by dirkf** [comment]
What is true is that a config file is not separately parsed but just replaced by the arguments in the file.

You might hope, and the examples in the manual support the idea, that each line should contain a full set of options and values, where applicable.

In case people rely on that not being so, a keen PR author could propose a `--strict-config` option that, when used in a config file, would cause each further line in the file to be validated as full set of options and values, where applicable (ie, if `--arg_name` needs a value, then it should be followed by its value on the same line); it might also restrict each line to at most one option. This would, as far as I can see, mean improving the parser in `_readOptions()`: perhaps read each line, apply `compat_shlex_split()` (allow a `\` at the end of the line to continue the line?), validate the line; return the accumulated results.

**Comment by mohsentux** [comment]
You don't like to read the part of  "working with strings" in programming books, do you? plz tell me you didn't learn programming from youtube too.
FINE I APOLOGIZE AND I'LL FIX IT FOR YOU BUT NOT TODAY. I'm not giving up 10k fixing a qemu bug request from IBM on the account of your ******* fill the blank using strings.
