### ISSUE TITLE
Allow downloading to buffer

### ISSUE THREAD

**Issue by iuriguilherme** [ytdl-org/youtube-dl#30815]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Although for the command line interface, almost all the time it is desirable to save the file to a local path. However when using ytdl as a module using the [io library](https://docs.python.org/3/library/io.html) to save files to buffers may be desirable.

My use case is a bunch of chatbots which download a video from an URL and then uploads the file back to the user, allowing a interface for people with no access to a CLI or in an environment where it would be difficult to use (such as a locked smartphone).

It would be more efficient if the script can download the file to a io.BufferIO object then upload it without having to make a temporary file in the disk, as it already does with other kind of media (for example with a qr code generator).

**Comment by iuriguilherme** [comment]
@dirkf Indeed it is one of the solutions, probably more efficient than the other solution I'm implementing (temporary files).

Still, supporting file-like objects would expand the usability of the software.

**Comment by 89z** [comment]
I agree with OP, I think this would be useful. I have similar support in my module:

~~~go
package main

import (
   "bytes"
   "fmt"
   "github.com/89z/mech/youtube"
)

func main() {
   play, err := youtube.Android.Player("va1oiojnGrA")
   if err != nil {
      panic(err)
   }
   var buf bytes.Buffer
   play.StreamingData.Formats[0].Write(&buf)
   fmt.Printf("%q", buf.Bytes()[:99])
}
~~~

Result:

~~~
"\x00\x00\x00\x18ftypmp42\x00\x00\x00\x00isommp42\x00\x00\xb8amoov\x00\x00\x00
lmvhd\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\xe8\x00\x04
\xbe\xb2\x00\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00
\x00\x00\x00"
~~~

**Comment by iuriguilherme** [comment]
While I agree it's a minority of third party scripts using it as a module comparing to the userbase, I can see that the discord/telegram chatbots using it in such a way are increasing. Not sure if most bot mantainers care about their host storage though

If my burden gets heavy enough I'll draft a PR after extending the library and testing a lot, but don't wait for it

**Comment by rautamiekka** [comment]
> Thus `stdout` is your friend.

Questionable in Command Prompt, maybe in PowerShell.

> Or write the file to a RAM disk

Indeed, RAM disk would be an option on most computers today.

On NIX it's pretty simple to setup, and on Window$ one can use [ImDisk Toolkit](https://sourceforge.net/projects/imdisk-toolkit/) (both graphical and command line) which doesn't have any limits on the RAM disk, judging by their website.

**Comment by garoto** [comment]
> Questionable in Command Prompt, maybe in PowerShell.

`stdout` in a conhost environment should behave like a POSIX system for the longest time.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31252
