### ISSUE TITLE
YTDL cannot extract video data

### ISSUE THREAD

**Issue by kingtastic** [ytdl-org/youtube-dl#30828]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
 export PATH="$PWD/node_modules/ffmpeg-static:$PATH"
python main.py

 * Serving Flask app "" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5777/ (Press CTRL+C to quit)
172.18.0.1 - - [07/Apr/2022 01:40:00] "GET / HTTP/1.1" 200 -
Logged in as:
TheTasticBot
[TOKEN]
ERROR: dQw4w9WgXcQ: YouTube said: Unable to extract video data

```

## Description

WRITE DESCRIPTION HERE

Code for my bot: https://replit.com/@kingtastic/ListeningMachine (fork the repl to edit it)
Bot test server: https://discord.gg/gP9WaDffT4

I've been trying to work on my own Discord bot that includes music support from YTDL but I cannot get a video to play it due to apparent issues with the system. 

My bot comes with this error: "An error occurred: Command raised an exception: DownloadError: [0;31mERROR:[0m dQw4w9WgXcQ: YouTube said: Unable to extract video data"

Does anyone know what is going on and to help?

**Comment by 89z** [comment]
Its a pretty shitty move to rick roll people trying to help you...

**Comment by kingtastic** [comment]
Wasn't intentional, I just tested it with that one in particular because I actually like that song

**Comment by october262** [comment]
is the youtube video age restricted ??

**Comment by kingtastic** [comment]
> is the youtube video age restricted ??

It is not.

**Comment by dirkf** [comment]
You'll have to debug your application, find the yt-dl command and run it separately, or get the application to gather and print the verbose yt-dl output.

When we ask for a Verbose Log, we didn't mean a log of some other application, as the instructions in the issue template say:
>Provide the complete verbose output of youtube-dl that clearly demonstrates the problem.
>Add the `-v` flag to your command line you run youtube-dl with (`youtube-dl -v <your command line>`), copy the WHOLE output and insert it below. I...

**Comment by darachm** [comment]
FWIW, I had a similar error message but found help in this issue and reply: https://github.com/ytdl-org/youtube-dl/issues/26152#issuecomment-743959535
I updated my youtube-dl (remove ubuntu rep version and use pip) and added a cookies file and it worked for me. Maybe it'd work for you?
