### ISSUE TITLE
What happened to version 2021.12.17

### ISSUE THREAD

**Issue by gamer191** [ytdl-org/youtube-dl#30825]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

What happened to Youtube-dl 2021.12.17. It's no longer available in https://github.com/ytdl-org/youtube-dl/releases (but it is still available in https://github.com/ytdl-org/youtube-dl/tags)?

**Comment by 89z** [comment]
~~~
pip install youtube-dl
~~~

**Comment by dirkf** [comment]
Maybe dstfw didn't do the few clicks needed to mirror the new tag into the list of releases? I've [done it now](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.12.17), anyway.
