### ISSUE TITLE
[youtube] The download had started then was broken and can not be retried.

### ISSUE THREAD

**Issue by dima4p** [ytdl-org/youtube-dl#30830]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -wxv https://www.youtube.com/watch?v=0rizuhUhLtI
[debug] System config: []
[debug] User config: ['--audio-format', 'mp3', '--format', 'mp4', '-o', '~/dl/youtube/%(upload_date)s-%(title)s~%(extractor)s.%(id)s.%(ext)s', '--download-archive', '~/.config/youtube-dl/archive.txt', '--ignore-errors', '--write-info-json', '--write-annotations', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Custom config: []
[debug] Command-line args: ['-wxv', 'https://www.youtube.com/watch?v=0rizuhUhLtI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.12 (CPython) - Linux-5.15.28-x86_64-Intel-R-_Core-TM-_i7-9750H_CPU_@_2.60GHz-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, phantomjs 0.10.
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[youtube] 0rizuhUhLtI: Downloading webpage
WARNING: There are no annotations to write.
[info] Video description metadata is already present
[debug] Invoking downloader on 'https://rr1---sn-h0jeenle.googlevideo.com/videoplayback?expire=1649389130&ei=6llPYoL8IN6G8gP79IzgDw&ip=95.90.199.222&id=o-ANGsYfcLc1SOhqjKbjT0Xy9tFUqWK51qjMmhoyjYxI1l&itag=22&source=youtube&requiressl=yes&mh=nE&mm=31%2C29&mn=sn-h0jeenle%2Csn-h0jeln7e&ms=au%2Crdu&mv=m&mvi=1&pl=23&initcwndbps=1703750&spc=4ocVCyQxmlQI3L7XSFMqD-J_XIyE&vprv=1&mime=video%2Fmp4&ns=S-s7e-6BrGKmcClUvgZ0A3oG&ratebypass=yes&dur=3725.061&lmt=1649362592300254&mt=1649367184&fvip=1&fexp=24001373%2C24007246&c=WEB&txp=3319222&n=BTJ0s12lqEX-Cunmy&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgLh6MVqWEy5HNm0I-js-6pQ3Ton5wDjPOxz2INf0WKpwCIDc5UNkG9jTD_U5oUuFZ48HHM6whtTOVk_K7_9BEZH9W&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJ_kW0_SdbP_i9Ae1C8cpze7cuOfVS-nzJG9TM102p70AiEA5snFn8xnK_h34SVU2jG522vXyrkPavIXlMjjMWJnZj8%3D'
[download] Resuming download at byte 1554012
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1976, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib64/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/lib64/python3.9/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib64/python3.9/site-packages/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/lib64/python3.9/site-packages/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/usr/lib64/python3.9/site-packages/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib64/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib64/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

## Description

Initially I have got the following messages: 
```
[youtube:tab] playlist Сергей Пархоменко - Videos: Downloading 74 videos
[download] Downloading video 1 of 74
[youtube] 0rizuhUhLtI: Downloading webpage
WARNING: There are no annotations to write.
[info] Writing video description metadata as JSON to: /home/dima/dl/youtube/20220407-Сергей Пархоменко на канале “Живой Гвоздь” в программме “Персонально ваш”. 06.04.2022~youtube.0rizuhUhLtI.info.json
[download] Destination: /home/dima/dl/youtube/20220407-Сергей Пархоменко на канале “Живой Гвоздь” в программме “Персонально ваш”. 06.04.2022~youtube.0rizuhUhLtI.mp4
[download]   0.4% of 402.10MiB at  5.28MiB/s ETA 01:15[download] Got server HTTP error: Downloaded 1554012 bytes, expected 421637446 bytes. Retrying (attempt 1 of 10)...


ERROR: Did not get any data blocks
[download] Downloading video 2 of 74

```

**Comment by dima4p** [comment]
With the firefox add-on "Video Downloader professional" I managed to download this video

**Comment by dirkf** [comment]
You have these options configured:
```
--audio-format mp3
--format mp4
-o ~/dl/youtube/%(upload_date)s-%(title)s~%(extractor)s.%(id)s.%(ext)s
--download-archive ~/.config/youtube-dl/archive.txt
--ignore-errors
--write-info-json
--write-annotations
--username PRIVATE
--password PRIVATE
```
You seem to have an issue with logging in, which is forced by specifying  `--username ...` and `--password ...`, but this isn't needed for this video. 

If logging in with `--username ...` and `--password ...` doesn't work, try using `--cookies ...` with a cookies file extracted from your logged-in YT browser session.

Possibly something is interfering with your network connection?

**Comment by dima4p** [comment]
> You have these options configured:
> 
> ```
> --audio-format mp3
> --format mp4
> -o ~/dl/youtube/%(upload_date)s-%(title)s~%(extractor)s.%(id)s.%(ext)s
> --download-archive ~/.config/youtube-dl/archive.txt
> --ignore-errors
> --write-info-json
> --write-annotations
> --username PRIVATE
> --password PRIVATE
> ```
> 
> You seem to have an issue with logging in, which is forced by specifying `--username ...` and `--password ...`, but this isn't needed for this video.

  The issue with logging I have noted long ago also. Despite the credentials are correct, it seems the real login does not happen. It would be great if youtube-dl could report if the login failed at least with `-v` option.

  Immediately before the attmpt with credentials I tried without them. The effect was the same.

> If logging in with `--username ...` and `--password ...` doesn't work, try using `--cookies ...` with a cookies file extracted from your logged-in YT browser session.

  What makes the difference between the two approaches?

> Possibly something is interfering with your network connection?

  No the network connection was perfect.

  Now, I think since some changes with the source the download works with and without credentials. So, it is too late to try to investigate this issue. I close it. But expect the further comment.

**Comment by dirkf** [comment]
> What makes the difference between the two approaches?

With `--username ...` and `--password ...`, yt-dl tries to enter your details in the relevant login page. This is vulnerable to changes in the login page format and unexpected additional steps, such as Captcha prompts.

With `--cookies ...`, the relevant cookie(s) are supplied instead of trying to log in. This is vulnerable to client discrimination by the site (eg, the cookie(s) might only be accepted with the same User-Agent header) and to expiration.
