### ISSUE TITLE
youtube-dl update

### ISSUE THREAD

**Issue by IoanPaleru** [ytdl-org/youtube-dl#30837]
Hi,

Youtube-dl is a great program, but it doesn't work and won't update properly.

I have youtube-dl version 2021.06.06 installed (verified using "youtube-dl --version"), however when I use "youtube-dl --update" to try and update it, it says "ERROR: can't find the current version. Please try again later.". (See attached screenshot.)

![youtube-dl screenshot](https://user-images.githubusercontent.com/35790889/162594143-55b96549-1b80-4636-bb70-390fb5ec7455.jpg)

Is there any way to fix that? Thanks and have a great day.

I'm using microsoft windows 7 home premium service pack 1 64 bit, and have enabled all permissions for youtube-dl's installation directory.

I P

**Comment by dirkf** [comment]
For now, uninstall the existing yt-dl and install [Python](https://www.python.org/downloads/release/python-386/).

Then this should install the release version (you may have to say `py -3` instead of `python`):
```
python -m pip install youtube-dl
```
But what you actually want is a version that downloads from YT at full speed, so get the latest version from here:
```
python -m pip install https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip
```

**Comment by garoto** [comment]
Most likely due to the outdated Windows7 "Certificate Authority (CA)" chain database. See: https://github.com/ytdl-org/youtube-dl/issues/26011

**Comment by gamer191** [comment]
I saw someone post it on a similar issue, that running this command works: `yt-dlp --update --no-check-certificate`

**Comment by gamer191** [comment]
Warning: ignore my previous solution, it's a security risk

**Comment by gamer191** [comment]
> For now, uninstall the existing yt-dl and install [Python](https://www.python.org/downloads/release/python-386/).
> 
> Then this should install the release version (you may have to say `python3` instead of `python`):
> 
> ```
> python -m pip install youtube-dl
> ```

Or, a much easier solution: just download the latest [youtube-dl.exe](https://yt-dl.org/downloads/2021.12.17/youtube-dl.exe) and manually replace your outdated youtube-dl.exe file :)

**Comment by rautamiekka** [comment]
> Or, a much easier solution: just download the latest [youtube-dl.exe](https://yt-dl.org/downloads/2021.12.17/youtube-dl.exe) and manually replace your outdated youtube-dl.exe file :)

It's far too tedious to make it easier. Sure, ytdl doesn't update exactly often, but ytdlp does, and having to manually get to the website many times a week besides many other updates to run gets tedious, which is where a script comes handy.

**Comment by garoto** [comment]
> Or, a much easier solution: just download the latest [youtube-dl.exe](https://yt-dl.org/downloads/2021.12.17/youtube-dl.exe) and manually replace your outdated youtube-dl.exe file :)

That won't work either with an outdated Windows 7 certificate storage.

**Comment by gamer191** [comment]
@rautamiekka yt-dlp isn't affected by this issue 🙂

> That won't work either with an outdated Windows 7 certificate storage.

Why? Unlike yt-dlp, most web browsers don't rely on the system certificates

**Comment by garoto** [comment]
> Why? Unlike youtube-dl, most web browsers don't rely on the system certificates

Pre-compiled `youtube-dl` Windows binaries link against the `schannel` Windows API. This mechanic alone generated a very busy issue when a certain google-related certificate had expired, it was waaay before your day I assume.

**Comment by Stargateur** [comment]
BTW https://pypi.org/project/youtube_dl/#history is completely outdated.

**Comment by dirkf** [comment]
It's accurate about the versions offered there. It will be updated when a new release is pushed to PyPi.

**Comment by dirkf** [comment]
Continued in #31585.
