### ISSUE TITLE
youtube-dl hanging on both Fedora 35 and Ubuntu 20.04

### ISSUE THREAD

**Issue by teddybairs1** [ytdl-org/youtube-dl#30858]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
[allen@localhost-live ~]$ youtube-dl -v https://www.youtube.com/watch?v=QvNKXgINTxM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=QvNKXgINTxM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.4 (CPython) - Linux-5.16.19-200.fc35.x86_64-x86_64-with-glibc2.34
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] QvNKXgINTxM: Downloading webpage

```

## Description

For about three or four weeks now I have been unable to download videos from YouTube at all. Furthermore, when I attempt to check for updates using youtube-dl -U it just hangs and sits there. The verbose output I listed above is all I get. It gets to "Downloading Webpage" and then it stops and doesn't go any further. I have left it going for up to ten or fifteen minutes, and it never continues or exits. It just hangs. This is the case on both Fedora 35 which I am running on my laptop, and Ubuntu 20.04 Mate, which I am running on a desktop. It makes no difference which video I attempt to download from YouTube. youtube-dl hangs regardless. Could it be a Linux specific issue?

**Comment by 89z** [comment]
Windows here, works fine:

~~~
PS D:\Desktop> youtube-dl.exe QvNKXgINTxM
[youtube] QvNKXgINTxM: Downloading webpage
[download] Destination: MAVKA. THE FOREST SONG - Official Trailer (2022) Animagrad Studio-QvNKXgINTxM.f137.mp4
[download]   2.8% of 30.18MiB at 55.73KiB/s ETA 08:59
~~~

**Comment by dirkf** [comment]
To be clear, you can play the same YT videos in your browser?

I suspect a network issue between your PCs and YT, probably closer to you. Perhaps there is a proxy server that the browser sets up automatically but which needs to be specified for yt-dl.

**Comment by dirkf** [comment]
Closing for lack of response.
