### ISSUE TITLE
Code 1 Error from npm installation.

### ISSUE THREAD

**Issue by Conspecuous** [ytdl-org/youtube-dl#30859]
- [x] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'i',
0 verbose cli   'youtube-dl-exec'
0 verbose cli ]
1 info using npm@8.5.0
2 info using node@v16.14.2
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:C:\Users\consp\Desktop\smokeshack\.npmrc Completed in 1ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:C:\Users\consp\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\consp\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 timing npm:load:configload Completed in 10ms
20 timing npm:load:setTitle Completed in 0ms
21 timing config:load:flatten Completed in 2ms
22 timing npm:load:display Completed in 3ms
23 verbose logfile C:\Users\consp\AppData\Local\npm-cache\_logs\2022-04-16T22_12_02_878Z-debug-0.log
24 timing npm:load:logFile Completed in 6ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 20ms
28 timing arborist:ctor Completed in 1ms
29 silly logfile start cleaning logs, removing 2 files
30 timing idealTree:init Completed in 48ms
31 timing idealTree:userRequests Completed in 1ms
32 silly idealTree buildDeps
33 silly fetch manifest youtube-dl-exec@*
34 timing arborist:ctor Completed in 0ms
35 http fetch GET 200 https://registry.npmjs.org/youtube-dl-exec 182ms (cache miss)
36 silly placeDep ROOT youtube-dl-exec@2.0.11 OK for: discord-bot-maker-bot@2.1.1 want: *
37 silly fetch manifest dargs@~7.0.0
38 silly fetch manifest execa@~5.1.0
39 silly fetch manifest is-unix@~2.0.1
40 silly fetch manifest mkdirp@~1.0.4
41 http fetch GET 200 https://registry.npmjs.org/mkdirp 12ms (cache hit)
42 http fetch GET 200 https://registry.npmjs.org/dargs 64ms (cache miss)
43 http fetch GET 200 https://registry.npmjs.org/execa 147ms (cache miss)
44 http fetch GET 200 https://registry.npmjs.org/is-unix 417ms (cache miss)
45 timing idealTree:#root Completed in 605ms
46 silly placeDep ROOT dargs@7.0.0 OK for: youtube-dl-exec@2.0.11 want: ~7.0.0
47 silly placeDep ROOT execa@5.1.1 OK for: youtube-dl-exec@2.0.11 want: ~5.1.0
48 silly placeDep ROOT is-unix@2.0.6 OK for: youtube-dl-exec@2.0.11 want: ~2.0.1
49 silly placeDep node_modules/youtube-dl-exec mkdirp@1.0.4 OK for: youtube-dl-exec@2.0.11 want: ~1.0.4
50 silly fetch manifest cross-spawn@^7.0.3
51 silly fetch manifest get-stream@^6.0.0
52 silly fetch manifest human-signals@^2.1.0
53 silly fetch manifest is-stream@^2.0.0
54 silly fetch manifest merge-stream@^2.0.0
55 silly fetch manifest npm-run-path@^4.0.1
56 silly fetch manifest onetime@^5.1.2
57 silly fetch manifest signal-exit@^3.0.3
58 silly fetch manifest strip-final-newline@^2.0.0
59 http fetch GET 200 https://registry.npmjs.org/cross-spawn 58ms (cache miss)
60 http fetch GET 200 https://registry.npmjs.org/get-stream 59ms (cache miss)
61 http fetch GET 200 https://registry.npmjs.org/human-signals 62ms (cache miss)
62 http fetch GET 200 https://registry.npmjs.org/strip-final-newline 151ms (cache miss)
63 http fetch GET 200 https://registry.npmjs.org/onetime 179ms (cache miss)
64 http fetch GET 200 https://registry.npmjs.org/is-stream 181ms (cache miss)
65 http fetch GET 200 https://registry.npmjs.org/merge-stream 181ms (cache miss)
66 http fetch GET 200 https://registry.npmjs.org/signal-exit 181ms (cache miss)
67 http fetch GET 200 https://registry.npmjs.org/npm-run-path 182ms (cache miss)
68 timing idealTree:node_modules/youtube-dl-exec Completed in 187ms
69 timing idealTree:node_modules/dargs Completed in 0ms
70 silly placeDep ROOT cross-spawn@7.0.3 OK for: execa@5.1.1 want: ^7.0.3
71 silly placeDep ROOT get-stream@6.0.1 OK for: execa@5.1.1 want: ^6.0.0
72 silly placeDep ROOT human-signals@2.1.0 OK for: execa@5.1.1 want: ^2.1.0
73 silly placeDep ROOT is-stream@2.0.1 OK for: execa@5.1.1 want: ^2.0.0
74 silly placeDep ROOT merge-stream@2.0.0 OK for: execa@5.1.1 want: ^2.0.0
75 silly placeDep ROOT npm-run-path@4.0.1 OK for: execa@5.1.1 want: ^4.0.1
76 silly placeDep ROOT onetime@5.1.2 OK for: execa@5.1.1 want: ^5.1.2
77 silly placeDep ROOT signal-exit@3.0.7 OK for: execa@5.1.1 want: ^3.0.3
78 silly placeDep ROOT strip-final-newline@2.0.0 OK for: execa@5.1.1 want: ^2.0.0
79 silly fetch manifest path-key@^3.1.0
80 silly fetch manifest shebang-command@^2.0.0
81 silly fetch manifest which@^2.0.1
82 silly fetch manifest path-key@^3.0.0
83 silly fetch manifest mimic-fn@^2.1.0
84 http fetch GET 200 https://registry.npmjs.org/which 53ms (cache miss)
85 http fetch GET 200 https://registry.npmjs.org/mimic-fn 54ms (cache miss)
86 http fetch GET 200 https://registry.npmjs.org/shebang-command 59ms (cache miss)
87 http fetch GET 200 https://registry.npmjs.org/path-key 61ms (cache miss)
88 timing idealTree:node_modules/execa Completed in 67ms
89 silly placeDep ROOT path-key@3.1.1 OK for: cross-spawn@7.0.3 want: ^3.1.0
90 silly placeDep ROOT shebang-command@2.0.0 OK for: cross-spawn@7.0.3 want: ^2.0.0
91 silly placeDep ROOT which@2.0.2 OK for: cross-spawn@7.0.3 want: ^2.0.1
92 silly fetch manifest shebang-regex@^3.0.0
93 silly fetch manifest isexe@^2.0.0
94 http fetch GET 200 https://registry.npmjs.org/isexe 62ms (cache miss)
95 http fetch GET 200 https://registry.npmjs.org/shebang-regex 75ms (cache miss)
96 timing idealTree:node_modules/cross-spawn Completed in 78ms
97 timing idealTree:node_modules/get-stream Completed in 0ms
98 timing idealTree:node_modules/human-signals Completed in 0ms
99 timing idealTree:node_modules/is-stream Completed in 0ms
100 timing idealTree:node_modules/is-unix Completed in 0ms
101 timing idealTree:node_modules/merge-stream Completed in 0ms
102 timing idealTree:node_modules/npm-run-path Completed in 0ms
103 silly placeDep ROOT mimic-fn@2.1.0 OK for: onetime@5.1.2 want: ^2.1.0
104 timing idealTree:node_modules/onetime Completed in 2ms
105 timing idealTree:node_modules/mimic-fn Completed in 0ms
106 timing idealTree:node_modules/path-key Completed in 0ms
107 silly placeDep ROOT shebang-regex@3.0.0 OK for: shebang-command@2.0.0 want: ^3.0.0
108 timing idealTree:node_modules/shebang-command Completed in 1ms
109 timing idealTree:node_modules/shebang-regex Completed in 0ms
110 timing idealTree:node_modules/signal-exit Completed in 0ms
111 timing idealTree:node_modules/strip-final-newline Completed in 0ms
112 silly placeDep ROOT isexe@2.0.0 OK for: which@2.0.2 want: ^2.0.0
113 timing idealTree:node_modules/which Completed in 1ms
114 timing idealTree:node_modules/isexe Completed in 0ms
115 timing idealTree:node_modules/youtube-dl-exec/node_modules/mkdirp Completed in 0ms
116 timing idealTree:buildDeps Completed in 945ms
117 timing idealTree:fixDepFlags Completed in 1ms
118 timing idealTree Completed in 996ms
119 timing reify:loadTrees Completed in 996ms
120 timing reify:diffTrees Completed in 3ms
121 silly reify moves {}
122 timing reify:retireShallow Completed in 1ms
123 timing reify:createSparse Completed in 4ms
124 timing reify:loadBundles Completed in 0ms
125 silly audit bulk request {
125 silly audit   '@babel/runtime': [ '7.16.7' ],
125 silly audit   '@discordjs/builders': [ '0.11.0' ],
125 silly audit   '@discordjs/collection': [ '0.4.0' ],
125 silly audit   '@jimp/bmp': [ '0.16.1' ],
125 silly audit   '@jimp/core': [ '0.16.1' ],
125 silly audit   '@jimp/custom': [ '0.16.1' ],
125 silly audit   '@jimp/gif': [ '0.16.1' ],
125 silly audit   '@jimp/jpeg': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-blit': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-blur': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-circle': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-color': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-contain': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-cover': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-crop': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-displace': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-dither': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-fisheye': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-flip': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-gaussian': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-invert': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-mask': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-normalize': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-print': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-resize': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-rotate': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-scale': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-shadow': [ '0.16.1' ],
125 silly audit   '@jimp/plugin-threshold': [ '0.16.1' ],
125 silly audit   '@jimp/plugins': [ '0.16.1' ],
125 silly audit   '@jimp/png': [ '0.16.1' ],
125 silly audit   '@jimp/tiff': [ '0.16.1' ],
125 silly audit   '@jimp/types': [ '0.16.1' ],
125 silly audit   '@jimp/utils': [ '0.16.1' ],
125 silly audit   '@sapphire/async-queue': [ '1.1.9' ],
125 silly audit   '@sindresorhus/is': [ '4.2.1' ],
125 silly audit   '@types/node': [ '17.0.8' ],
125 silly audit   '@types/node-fetch': [ '2.5.12' ],
125 silly audit   'form-data': [ '3.0.1', '4.0.0' ],
125 silly audit   '@types/ws': [ '8.2.2' ],
125 silly audit   'any-base': [ '1.1.0' ],
125 silly audit   asynckit: [ '0.4.0' ],
125 silly audit   'base64-js': [ '1.5.1' ],
125 silly audit   'bmp-js': [ '0.1.0' ],
125 silly audit   buffer: [ '5.7.1' ],
125 silly audit   'buffer-equal': [ '0.0.1' ],
125 silly audit   'combined-stream': [ '1.0.8' ],
125 silly audit   'delayed-stream': [ '1.0.0' ],
125 silly audit   'discord-api-types': [ '0.26.1' ],
125 silly audit   'discord.js': [ '13.6.0' ],
125 silly audit   'dom-walk': [ '0.1.2' ],
125 silly audit   eventemitter3: [ '1.2.0' ],
125 silly audit   'exif-parser': [ '0.1.12' ],
125 silly audit   'file-type': [ '9.0.0' ],
125 silly audit   fstorm: [ '0.1.3' ],
125 silly audit   gifwrap: [ '0.9.2' ],
125 silly audit   global: [ '4.4.0' ],
125 silly audit   ieee754: [ '1.2.1' ],
125 silly audit   'image-q': [ '1.1.1' ],
125 silly audit   'is-function': [ '1.0.2' ],
125 silly audit   jimp: [ '0.16.1' ],
125 silly audit   'jpeg-js': [ '0.4.2' ],
125 silly audit   'load-bmfont': [ '1.4.1' ],
125 silly audit   mime: [ '1.6.0' ],
125 silly audit   'mime-db': [ '1.51.0' ],
125 silly audit   'mime-types': [ '2.1.34' ],
125 silly audit   'min-document': [ '2.19.0' ],
125 silly audit   minimist: [ '1.2.5' ],
125 silly audit   mkdirp: [ '0.5.5', '1.0.4' ],
125 silly audit   moment: [ '2.29.2' ],
125 silly audit   'moment-timezone': [ '0.5.34' ],
125 silly audit   'node-cron': [ '3.0.0' ],
125 silly audit   'node-fetch': [ '2.6.7' ],
125 silly audit   omggif: [ '1.0.10' ],
125 silly audit   pako: [ '1.0.11' ],
125 silly audit   'parse-bmfont-ascii': [ '1.0.6' ],
125 silly audit   'parse-bmfont-binary': [ '1.0.6' ],
125 silly audit   'parse-bmfont-xml': [ '1.1.4' ],
125 silly audit   'parse-headers': [ '2.0.4' ],
125 silly audit   phin: [ '2.9.3' ],
125 silly audit   pixelmatch: [ '4.0.2' ],
125 silly audit   pngjs: [ '3.4.0' ],
125 silly audit   process: [ '0.11.10' ],
125 silly audit   'regenerator-runtime': [ '0.13.9' ],
125 silly audit   sax: [ '1.2.4' ],
125 silly audit   timm: [ '1.7.1' ],
125 silly audit   tinycolor2: [ '1.4.2' ],
125 silly audit   tr46: [ '0.0.3' ],
125 silly audit   'ts-mixer': [ '6.0.0' ],
125 silly audit   tslib: [ '2.3.1' ],
125 silly audit   utif: [ '2.0.1' ],
125 silly audit   'webidl-conversions': [ '3.0.1' ],
125 silly audit   'whatwg-url': [ '5.0.0' ],
125 silly audit   ws: [ '8.4.2' ],
125 silly audit   xhr: [ '2.6.0' ],
125 silly audit   'xml-parse-from-string': [ '1.0.1' ],
125 silly audit   xml2js: [ '0.4.23' ],
125 silly audit   xmlbuilder: [ '11.0.1' ],
125 silly audit   xtend: [ '4.0.2' ],
125 silly audit   zod: [ '3.11.6' ],
125 silly audit   'youtube-dl-exec': [ '2.0.11' ],
125 silly audit   dargs: [ '7.0.0' ],
125 silly audit   execa: [ '5.1.1' ],
125 silly audit   'is-unix': [ '2.0.6' ],
125 silly audit   'cross-spawn': [ '7.0.3' ],
125 silly audit   'get-stream': [ '6.0.1' ],
125 silly audit   'human-signals': [ '2.1.0' ],
125 silly audit   'is-stream': [ '2.0.1' ],
125 silly audit   'merge-stream': [ '2.0.0' ],
125 silly audit   'npm-run-path': [ '4.0.1' ],
125 silly audit   onetime: [ '5.1.2' ],
125 silly audit   'signal-exit': [ '3.0.7' ],
125 silly audit   'strip-final-newline': [ '2.0.0' ],
125 silly audit   'path-key': [ '3.1.1' ],
125 silly audit   'shebang-command': [ '2.0.0' ],
125 silly audit   which: [ '2.0.2' ],
125 silly audit   'mimic-fn': [ '2.1.0' ],
125 silly audit   'shebang-regex': [ '3.0.0' ],
125 silly audit   isexe: [ '2.0.0' ]
125 silly audit }
126 silly tarball no local data for shebang-regex@https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz. Extracting by manifest.
127 silly tarball no local data for mimic-fn@https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz. Extracting by manifest.
128 silly tarball no local data for isexe@https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz. Extracting by manifest.
129 silly tarball no local data for which@https://registry.npmjs.org/which/-/which-2.0.2.tgz. Extracting by manifest.
130 silly tarball no local data for shebang-command@https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz. Extracting by manifest.
131 silly tarball no local data for path-key@https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz. Extracting by manifest.
132 silly tarball no local data for strip-final-newline@https://registry.npmjs.org/strip-final-newline/-/strip-final-newline-2.0.0.tgz. Extracting by manifest.
133 silly tarball no local data for onetime@https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz. Extracting by manifest.
134 silly tarball no local data for signal-exit@https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz. Extracting by manifest.
135 silly tarball no local data for is-stream@https://registry.npmjs.org/is-stream/-/is-stream-2.0.1.tgz. Extracting by manifest.
136 silly tarball no local data for npm-run-path@https://registry.npmjs.org/npm-run-path/-/npm-run-path-4.0.1.tgz. Extracting by manifest.
137 silly tarball no local data for human-signals@https://registry.npmjs.org/human-signals/-/human-signals-2.1.0.tgz. Extracting by manifest.
138 silly tarball no local data for merge-stream@https://registry.npmjs.org/merge-stream/-/merge-stream-2.0.0.tgz. Extracting by manifest.
139 silly tarball no local data for cross-spawn@https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz. Extracting by manifest.
140 silly tarball no local data for get-stream@https://registry.npmjs.org/get-stream/-/get-stream-6.0.1.tgz. Extracting by manifest.
141 silly tarball no local data for is-unix@https://registry.npmjs.org/is-unix/-/is-unix-2.0.6.tgz. Extracting by manifest.
142 silly tarball no local data for execa@https://registry.npmjs.org/execa/-/execa-5.1.1.tgz. Extracting by manifest.
143 silly tarball no local data for dargs@https://registry.npmjs.org/dargs/-/dargs-7.0.0.tgz. Extracting by manifest.
144 silly tarball no local data for mkdirp@https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz. Extracting by manifest.
145 silly tarball no local data for youtube-dl-exec@https://registry.npmjs.org/youtube-dl-exec/-/youtube-dl-exec-2.0.11.tgz. Extracting by manifest.
146 http fetch GET 200 https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz 112ms (cache miss)
147 timing reifyNode:node_modules/shebang-regex Completed in 122ms
148 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 123ms
149 timing auditReport:getReport Completed in 126ms
150 silly audit report {
150 silly audit report   minimist: [
150 silly audit report     {
150 silly audit report       id: 1067342,
150 silly audit report       url: 'https://github.com/advisories/GHSA-xvch-5gv4-984h',
150 silly audit report       title: 'Prototype Pollution in minimist',
150 silly audit report       severity: 'critical',
150 silly audit report       vulnerable_versions: '<1.2.6',
150 silly audit report       cwe: [Array],
150 silly audit report       cvss: [Object]
150 silly audit report     }
150 silly audit report   ]
150 silly audit report }
151 timing metavuln:cache:get:security-advisory:minimist:nZkhUdPEpKwzIx1nekYW4B7BHQyF2nm6J0JsgeP2HfA0DRMT5hhByRU71A4RPgtBbQPYEzVBozv8/mBZCafaGw== Completed in 10ms
152 http fetch GET 200 https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz 117ms (cache miss)
153 timing reifyNode:node_modules/path-key Completed in 140ms
154 http fetch GET 200 https://registry.npmjs.org/minimist 17ms (cache hit)
155 timing metavuln:packument:minimist Completed in 18ms
156 timing metavuln:load:security-advisory:minimist:1067342 Completed in 0ms
157 timing metavuln:calculate:security-advisory:minimist:1067342 Completed in 19ms
158 timing metavuln:packument:mkdirp Completed in 0ms
159 http fetch GET 200 https://registry.npmjs.org/strip-final-newline/-/strip-final-newline-2.0.0.tgz 120ms (cache miss)
160 timing reifyNode:node_modules/strip-final-newline Completed in 144ms
161 timing metavuln:cache:get:security-advisory:mkdirp:CE+8U4ZPtjiJPdI/iyhBm/J/6iJ6W46YsdmRUqqyg6mDC09+mfWZqqAHYSzlnfbGA992zvUCP+SrVPVrG01dvA== Completed in 4ms
162 timing metavuln:load:security-advisory:mkdirp:nZkhUdPEpKwzIx1nekYW4B7BHQyF2nm6J0JsgeP2HfA0DRMT5hhByRU71A4RPgtBbQPYEzVBozv8/mBZCafaGw== Completed in 0ms
163 timing metavuln:calculate:security-advisory:mkdirp:nZkhUdPEpKwzIx1nekYW4B7BHQyF2nm6J0JsgeP2HfA0DRMT5hhByRU71A4RPgtBbQPYEzVBozv8/mBZCafaGw== Completed in 5ms
164 timing auditReport:init Completed in 24ms
165 timing reify:audit Completed in 151ms
166 http fetch GET 200 https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz 130ms (cache miss)
167 timing reifyNode:node_modules/shebang-command Completed in 151ms
168 http fetch GET 200 https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz 127ms (cache miss)
169 timing reifyNode:node_modules/onetime Completed in 154ms
170 http fetch GET 200 https://registry.npmjs.org/which/-/which-2.0.2.tgz 139ms (cache miss)
171 timing reifyNode:node_modules/which Completed in 157ms
172 http fetch GET 200 https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz 149ms (cache miss)
173 timing reifyNode:node_modules/mimic-fn Completed in 162ms
174 http fetch GET 200 https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz 155ms (cache miss)
175 timing reifyNode:node_modules/isexe Completed in 170ms
176 http fetch GET 200 https://registry.npmjs.org/is-unix/-/is-unix-2.0.6.tgz 129ms (cache miss)
177 timing reifyNode:node_modules/is-unix Completed in 180ms
178 http fetch GET 200 https://registry.npmjs.org/get-stream/-/get-stream-6.0.1.tgz 142ms (cache miss)
179 timing reifyNode:node_modules/get-stream Completed in 188ms
180 http fetch GET 200 https://registry.npmjs.org/dargs/-/dargs-7.0.0.tgz 142ms (cache miss)
181 timing reifyNode:node_modules/dargs Completed in 197ms
182 http fetch GET 200 https://registry.npmjs.org/merge-stream/-/merge-stream-2.0.0.tgz 169ms (cache miss)
183 timing reifyNode:node_modules/merge-stream Completed in 210ms
184 http fetch GET 200 https://registry.npmjs.org/npm-run-path/-/npm-run-path-4.0.1.tgz 182ms (cache miss)
185 timing reifyNode:node_modules/npm-run-path Completed in 216ms
186 http fetch GET 200 https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz 161ms (cache miss)
187 timing reifyNode:node_modules/youtube-dl-exec/node_modules/mkdirp Completed in 219ms
188 http fetch GET 200 https://registry.npmjs.org/execa/-/execa-5.1.1.tgz 168ms (cache miss)
189 timing reifyNode:node_modules/execa Completed in 222ms
190 http fetch GET 200 https://registry.npmjs.org/is-stream/-/is-stream-2.0.1.tgz 193ms (cache miss)
191 timing reifyNode:node_modules/is-stream Completed in 224ms
192 http fetch GET 200 https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz 197ms (cache miss)
193 timing reifyNode:node_modules/signal-exit Completed in 226ms
194 http fetch GET 200 https://registry.npmjs.org/youtube-dl-exec/-/youtube-dl-exec-2.0.11.tgz 165ms (cache miss)
195 timing reifyNode:node_modules/youtube-dl-exec Completed in 230ms
196 http fetch GET 200 https://registry.npmjs.org/human-signals/-/human-signals-2.1.0.tgz 201ms (cache miss)
197 timing reifyNode:node_modules/human-signals Completed in 237ms
198 http fetch GET 200 https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz 196ms (cache miss)
199 timing reifyNode:node_modules/cross-spawn Completed in 240ms
200 timing reify:unpack Completed in 241ms
201 timing reify:unretire Completed in 0ms
202 timing build:queue Completed in 3ms
203 info run youtube-dl-exec@2.0.11 preinstall node_modules/youtube-dl-exec npx bin-version-check-cli python ">=2"
204 info run youtube-dl-exec@2.0.11 preinstall { code: 1, signal: null }
205 timing reify:rollback:createSparse Completed in 12ms
206 timing reify:rollback:retireShallow Completed in 0ms
207 timing command:i Completed in 2768ms
208 verbose stack Error: command failed
208 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
208 verbose stack     at ChildProcess.emit (node:events:526:28)
208 verbose stack     at maybeClose (node:internal/child_process:1092:16)
208 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
209 verbose pkgid youtube-dl-exec@2.0.11
210 verbose cwd C:\Users\consp\Desktop\smokeshack
211 verbose Windows_NT 10.0.19042
212 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "youtube-dl-exec"
213 verbose node v16.14.2
214 verbose npm  v8.5.0
215 error code 1
216 error path C:\Users\consp\Desktop\smokeshack\node_modules\youtube-dl-exec
217 error command failed
218 error command C:\Windows\system32\cmd.exe /d /s /c npx bin-version-check-cli python ">=2"
219 error Error: Couldn't find version of `python`
219 error     at binaryVersion (file:///C:/Users/consp/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version/index.js:55:8)
219 error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
219 error     at async binaryVersionCheck (file:///C:/Users/consp/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:14:18)
220 verbose exit 1
221 timing npm Completed in 2989ms
222 verbose unfinished npm timer reify 1650147123094
223 verbose unfinished npm timer reify:build 1650147124351
224 verbose unfinished npm timer build 1650147124352
225 verbose unfinished npm timer build:deps 1650147124352
226 verbose unfinished npm timer build:run:preinstall 1650147124355
227 verbose unfinished npm timer build:run:preinstall:node_modules/youtube-dl-exec 1650147124355
228 verbose code 1
229 error A complete log of this run can be found in:
229 error     C:\Users\consp\AppData\Local\npm-cache\_logs\2022-04-16T22_12_02_878Z-debug-0.log

## Description

Edit: Fixed description not showing.

Attempting to install the module as it is a required dependency for a discord bot application I am working on, however I am unable to install it due to Code 1 Error. I've attempted to install it via python as well but no luck there.

**Comment by dirkf** [comment]
Node/NPM isn't supported. You should ask somewhere else, probably https://github.com/microlinkhq/youtube-dl-exec/issues.

Having said that, the log implies that it expects to run Python and can't find it.
