### ISSUE TITLE
Setup YouTube DL on phone

### ISSUE THREAD

**Issue by caniplay** [ytdl-org/youtube-dl#30860]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Can you setup YouTube DL on Mobile like Phone? And if you can how to do it?

**Comment by dirkf** [comment]
Does your phone satisfy these requirements?
>[yt-dl] requires the Python interpreter, version 2.6, 2.7, or 3.2+, and it is not platform specific. It should work on your Unix box, on Windows or on macOS.

**Comment by AndNovAtor** [comment]
As @dirkf sayed. For example, install python and then install youtube-dl with pip (even from git branch) "INCIDE", for example, Termux (installed from it GitHub release page or FDroid, _not_ GooglePlay). Or ANY another "terminal" "emulator". Or even "portable" Linux. With python.

Again:
>requires the Python interpreter
>is not platform specific

**Comment by QuickHare** [comment]
I think you might have noticed Python is needed.

In general, you can use youtube-dl on any device as long as you can somehow run a command and it has Python installed. On a desktop, laptop, cloud-base or virtual machine, that will usually mean running Command Prompt, Terminal or a console.

However for a phone you have to think how you'll do this. Do you have an app that will run commands? Are you planning to write or use an app that uses youtube-dl as part of its program? How are you going to tell it what videos to download?

Whichever method you use, you then have to make sure it has Python and you can download or install youtube-dl to run with it.

**Comment by Lee-Carre** [comment]
> phone

There are apps available via [F-Droid](//www.f-droid.org/) which make youtube-dl available on Android(-compatible) devices.

**Comment by pukkandan** [comment]
On Android:
1. install [termux](https://f-droid.org/en/packages/com.termux/)
2. Run these commands one by one:
```sh
termux-setup-storage
pkg update
pkg upgrade
pkg install ffmpeg python
pip install -U youtube-dl
```
