### ISSUE TITLE
BBC video download not working  (not an iplayer video)

### ISSUE THREAD

**Issue by Erik-Per** [ytdl-org/youtube-dl#30863]
I am trying to download a BBC-video (about fungi), but is does not work.
https://www.bbc.co.uk/ideas/videos/the-fascinating-world-of-fungi/p0bhvrrt

I used the following command
C:\ytdl\youtube-dl.exe https://www.bbc.co.uk/ideas/videos/the-fascinating-world-of-fungi/p0bhvrrt

Thx

**Comment by dirkf** [comment]
The URL pattern `https://www.bbc.co.uk/ideas/videos/...` is a new thing that the BBC extractor doesn't handle. Luckily they've included the programme ID `p0bhvrrt` and you can pull the video (I assume it's what you want, not having viewed it) using the standard programme URL  'https://www.bbc.co.uk/programmes/p0bhvrrt'.

**Comment by Erik-Per** [comment]
That worked like a charm.
