### ISSUE TITLE
pornhub.com can't parse arguments currectly mistaking ffmpeg's for aria2c's

### ISSUE THREAD

**Issue by mohsentux** [ytdl-org/youtube-dl#30877]
this error can be prevented by using --hls-prefer-native in your config.txt file but since the youtube-dl's internal download manager to put it mildly is work of travesty. it is in no way an immediate solution and your download will suffer great downspeed impacts
_--external-downloader aria2c_  gets away Scott free BUT if in your **CLI Arguments** or **config.txt** or **youtube-dl.conf** you have the: _--external-downloader-args_ such as:
**--external-downloader-args '-c -j 3 -x 3 -s 3 -k 1M'**
It will be passed as ffmpeg argument for example if the hypothetical case the:
_ERROR: There is no **c** argument_. since -c is the first in argument in: **--external-downloader-args '-c -j 3 -x 3 -s 3 -k 1M'**

youtube-dl's verbose mode clearly proves this bug exists for pornhub.com. _maybe because it doesn't use aria2c._

but constantly changing your arguments file as I have is clearly a big inconvenience.

I'm sorry for not being able to show you a produced verbose output. but I'm using a different machine that is not mine and It's discourtesy to add files to path make change and visit phonograph material websites right now.

I though I should inform you immediately but I will edit it to youtube-dl git repository standard bug report style as soon as possible. Apologies 🙏

**Comment by dirkf** [comment]
There is already a fix in the git master for the previously observed issue* that `--external-downloader-args` are used even if yt-dl ignores the specified `--external-downloader`

As you would have found by complsearching the issue tracker.

**Comment by mohsentux** [comment]
but i did!!!!!!

**Comment by mohsentux** [comment]
wait how far is the git master from the latest exe release???

**Comment by mohsentux** [comment]
then we've decided. the project continue as an original with no mention of dirt 💩 whatsoever

**Comment by 89z** [comment]
If you want to install master, just do:

~~~
pip install https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip
~~~

maintainer will decide when to do a release, not you.
