### ISSUE TITLE
I think I can help with your LEGAL issues by simply changing the code

### ISSUE THREAD

**Issue by mohsentux** [ytdl-org/youtube-dl#30876]
I'm currently a bughunter (mainly qemu and IBM)
I can comile a doc explaining whys and hows or just do it or both. well I choose getting it done. and I'll try my best to compile that doc but don't use that one file in the commit it's not wise to show it.
I've given a lot of thought on this (I became a fan after your app helped me organize my harvard online math courses in one go)
we can download channels , playlists, videos. extremely customizable. it can't go to waste and we no longer can afford losse-ends and compromises 
If I do this IT NEEDS TO BE IN **RUST**.
that's all I can say for now. I'll make the commit you become the judge (or if you have a lawyer at your disposal to go through it)
trust me it'll be fool proof
MY BIGGEST NIGHTMARE? becoming a mere fork uhhhhhhh 🤮🤮🤮🤮
we'll meet back with the commit. 
listen do you even have a way of contacting you?

**Comment by 89z** [comment]
I approve this request. Please post bthe Rust patch, and I will merge it right away. Thank you!

**Comment by mohsentux** [comment]
dirkf, may I ask why?

**Comment by mohsentux** [comment]
apparently those with valid reasonable questions against immediate unwarranted actions are subject to solitary confinement followed by subjection to summery destruction by pre-morten mutilation around here.
AT LEAST I CAN SPELL COURTESY

**Comment by mohsentux** [comment]
apparently those with valid reasonable questions against immediate unwarranted actions are subject to solitary confinement followed by subjection to summery destruction by pre-morten mutilation around here.
AT LEAST I CAN SPELL COURTESY

**Comment by mohsentux** [comment]
apparently those with valid reasonable questions against immediate unwarranted actions are subject to solitary confinement followed by subjection to summery destruction by pre-morten mutilation around here.
AT LEAST I CAN SPELL COURTESY

**Comment by dirkf** [comment]
To the extent that your issue text was comprehensible, it was not related to the yt-dl project.
