### ISSUE TITLE
Windows attempted to flag Youtube_dl.exe as a virus , New DRM?

### ISSUE THREAD

**Issue by Dentordev** [ytdl-org/youtube-dl#30889]
I am having a new issue that I haven't had with youtube dl before where my system has tried to flag it as a virus Once and keeps preventing me from using it, I have tried on multiple occasions to run the code but it told me that I needed to reinstall the code because MSVCR100.dll wasn't available, sure enough I found the file but It was lowercased and I am wondering if windows is trying some form of DRM  or something else that might need further investigation. if anyone knows how to fix it please help me do so. I have the exe file saved in my flashdrive directory. as E:/YT/yt_dl.exe and I am using Windows 10. Version: OS Builds 19042.1645, 19043.1645, and 19044.1645.

**Comment by dirkf** [comment]
Check this: https://github.com/ytdl-org/youtube-dl#users-content-the-exe-throws-an-error-due-to-missing-msvcr100dll

If that doesn't help, please post the text error messages that you see, or a screenshot if that's not possible.

**Comment by Dentordev** [comment]
@dirkf Thanks for the help, I appreciate it :) I Got it to work now
![It_works](https://user-images.githubusercontent.com/92227212/164934256-e9317e13-2295-406a-8707-58406e59df79.PNG)
