### ISSUE TITLE
Can't download Facebook Private Video, ERROR: Unable to extract lsd.

### ISSUE THREAD

**Issue by frakman1** [ytdl-org/youtube-dl#30891]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
**NOTE:This is not possible since it's a private video, try out your own private video on Facebook**
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones.
I found an identical issue [here](https://github.com/ytdl-org/youtube-dl/issues/25500) but was asked to open a new issue when posting anupdate to it. 
- [x] I've read bugs section in FAQ

## Verbose log

Logs (parts redacted with xxxxx):

```
$youtube-dl --verbose --username xxxxx@xxxxx.com --cookies fbcookies.txt  https://www.facebook.com/xxxxx/videos/xxxxx/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--cookies', 'fbcookies.txt', 'https://www.facebook.com/xxxxx/videos/xxxxx/']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.1 (CPython) - macOS-10.13.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] Downloading login page
ERROR: Unable to extract lsd; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 533, in extract
    self.initialize()
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 437, in initialize
    self._real_initialize()
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/facebook.py", line 378, in _real_initialize
    self._login()
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/facebook.py", line 324, in _login
    lsd = self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract lsd; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I am getting this error using the same command that used to work for me in the past. All I changed was the URL and updated the cookies file.

I am using the latest version of youtube-dl on MacOS High Sierra.

**Comment by 89z** [comment]
please post a full, valid URL. It doesn't have to be the exact one you are wanting, just same behavior.

**Comment by frakman1** [comment]
It's a private video. You would have to try out your own private video on Facebook. I don't know how to get you one that will work for your facebook account.

**Comment by 89z** [comment]
You'll need to create a dummy account, then grant that dummy account access to some private video, then share the login of that account. If you don't wish to do that, I understand. Just know that issues similar to this have gone years without being fixed, because user did not provide a way for people to access the video.

**Comment by frakman1** [comment]
Why not just locate a video on your own feed and use that one?

**Comment by 89z** [comment]
It is the posters responsibility, to provide an easy to reproduce problem. Since you are unwilling to do that, I am unsubscribing from this issue. Good luck to you.

**Comment by dirkf** [comment]
In any case, don't use `--username ...` **together with** `--cookies ...`. If the extractor sees a username, it will try to log in whereas the point of passing cookies is to bypass a possibly broken login procedure.

**Comment by frakman1** [comment]
Thank you @dirkf . That was it. I was wondering about that too. I guess my historical command didn't work the way I thought it did.
To recap, the fix was to remove the `--username` option and parameter:

```
$youtube-dl --verbose --cookies fbcookies.txt https://www.facebook.com/xxxxx/videos/xxxxx/
```
For anyone who is wondering where I got the cookies from, I use the Chrome extension cookies.txt:

![image](https://user-images.githubusercontent.com/5826484/164950734-cf981004-3eaf-47b3-934b-0e730d0c91a9.png)
