### ISSUE TITLE
Cannot download a particular bitchute-link

### ISSUE THREAD

**Issue by karagiannis** [ytdl-org/youtube-dl#30895]
## Checklist

- [x ] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
$ youtube-dl -v https://www.bitchute.com/video/Krqp3JXDq3Uu/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bitchute.com/video/Krqp3JXDq3Uu/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.9 (CPython) - Linux-5.4.0-109-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[BitChute] Krqp3JXDq3Uu: Downloading webpage
[BitChute] Krqp3JXDq3Uu: Checking video URL
[BitChute] Krqp3JXDq3Uu: video URL is invalid, skipping: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/bitchute.py", line 66, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
I used youtube-dl over 100 times on bitchute and it always worked, but not on that particular link.
Did the update but it didn't help.

**Comment by 89z** [comment]
Attention maintainers, linked video appears to be about Holocaust denial. Please close this issue.

**Comment by karagiannis** [comment]
Same problem with
https://www.bitchute.com/video/OzULDeRZ0vBn/
https://www.bitchute.com/video/oUiHFd7Sjiqs/

**Comment by karagiannis** [comment]
Videos don't play. My mistake.
