### ISSUE TITLE
How to launch test unit ?

### ISSUE THREAD

**Issue by axel584** [ytdl-org/youtube-dl#30898]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I try to write an extractor and I read in the doc : 
"Run python test/test_download.py TestDownload.test_YourExtractor. This should fail at first, but you can continually re-run it until you're done."
But when I try to launch the test of another extractor, I've got the same error : 
```axel@axel:~/youtube-dl$ python test/test_download.py TestDownload.test_DWIE
E
======================================================================
ERROR: test_DWIE (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: type object 'TestDownload' has no attribute 'test_DWIE'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

My question is : how to launch the unit test ? 

Thank you for your help,

Axel

**Comment by dirkf** [comment]
Leave the 'IE' off the extractor name:
```ShellSession
$ python test/test_download.py TestDownload.test_TikTokUser
[tiktok:user] Setting up session
[tiktok:user] zureeal: Downloading webpage
[download] Downloading playlist: 188294915489964032
[tiktok:user] playlist 188294915489964032: Collected 30 video ids (downloading 30 of them)
[download] Downloading video 1 of 30
[download] Downloading video 2 of 30
...
[download] Downloading video 30 of 30
[download] Finished downloading playlist: 188294915489964032
.
----------------------------------------------------------------------
Ran 1 test in 2.335s

OK
$
```

**Comment by pukkandan** [comment]
Since this is a very common mistake, yt-dlp the docs was updated to explicitly state this. Would be usefull to copy that change here:

> 1. Run `python test/test_download.py TestDownload.test_YourExtractor` (note that `YourExtractor` doesn't end with `IE`).

**Comment by dirkf** [comment]
Agreed.

This line in `extractor/common.py` (`get_testcases()`) explains it:
```py
            t['name'] = type(self).__name__[:-len('IE')]
```
