### ISSUE TITLE
Instagram - Unable to extract video url

### ISSUE THREAD

**Issue by 12dasad** [ytdl-org/youtube-dl#30920]
Any one find soulation for download from instagram on server!!
When iam run the script local on my ip it worked fine 
But on aws it failed..
I know that is related for instgram block ip
But i want i soulation without cookies

**Comment by dirkf** [comment]
See #28021 and #30851.

**Comment by 12dasad** [comment]
> See #28021 and #30851.

Ok i will close it 
But how to use --cookies youtube-dl in python??
Just type ydl.download([u]) --cookies(puth)?

**Comment by dirkf** [comment]
https://github.com/ytdl-org/youtube-dl#user-content-how-do-i-pass-cookies-to-youtube-dl

**Comment by dirkf** [comment]
Look at the `cookiefile` parameter in the doc of the `YoutubeDL` class in `youtubedl.py`. Also see https://github.com/yt-dlp/yt-dlp/issues/3674#issuecomment-1120341358.
