### ISSUE TITLE
It is possible to download videos from voe.sx link with youtube-dl?

### ISSUE THREAD

**Issue by van087** [ytdl-org/youtube-dl#30939]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I apologize in advance to everyone, if perhaps I propose again a question already discussed, but I have not been able to find a solution.

I would like to download videos that can only be viewed in streaming
some examples:

https://voe.sx/03xoyeown5u8
https://voe.sx/r2adivch4fat

is it possible to do this with youtube-dl?

I have tried with other premium lik generator sites, the file is downloaded but it is not visible.

Thanks again for your support.

**Comment by ismozz** [comment]
thanks for sharing.

[voe search engine](https://www.ismoz.com/video-upload-sites/voe/)
