### ISSUE TITLE
`'youtube-dl' is not recognized as an internal or external command` in Batch file.

### ISSUE THREAD

**Issue by fosam** [ytdl-org/youtube-dl#30950]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Description

I created a very small batch file on Windows where i can put the link of the video and the path where it will be downloaded.

I'm 100% sure that it worked as it should when i created it, but now after i put the path where to download the video, i get his:

```
'youtube-dl' is not recognized as an internal or external command,
operable program or batch file.
```

And of course i have my youtube-dl folder added to the path, and it works from anywhere on my machine when tried with a simple command.

<details>
<summary>These are the commands in the <b>.bat</b> file. </summary>

```
@echo off
set /p URL="Video Link "
set /p Path="Where to download "
youtube-dl -o "%Path%\%%(title)s %%(id)s.%%(ext)s" "%URL%"
```
</details>

Could you please try it?

Help is appreciated!

<br />

**It's not possible to generate any verbose log when running this batch.**

**Comment by garoto** [comment]
`set /p Path="Where to download "`

Just rename your `Path` named enviromental variable above to something else; as it is, you're overriding the system's previously defined `%PATH%` env. var.

**Comment by fosam** [comment]
> `set /p Path="Where to download "`
> 
> Just rename your `Path` named enviromental variable above to something else; as it is, you're overriding the system's previously defined `%PATH%` env. var.

Ah, that's right, that's a name conflict. Thanks!
