### ISSUE TITLE
raise ExtractorError in oreilly video download

### ISSUE THREAD

**Issue by nisamo** [ytdl-org/youtube-dl#30954]
I tried for download video from oreilly.com but get this error

    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('next')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Use the [Site Support](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=site-support-request&template=2_site_support_request.md) issue template. Why wouldn't you?
