### ISSUE TITLE
pythoncode error

### ISSUE THREAD

**Issue by nitep** [ytdl-org/youtube-dl#30968]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
 [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1514, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1487, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1470, in _extract_n_function_name
    jscode, 'Initial JS player n function name')
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
[debug] Invoking downloader on 'https://rr1---sn-no52-jijl.googlevideo.com/videoplayback?expire=1653116811&ei=KzuIYqnFDoCeg8UPx-qs-AM&ip=2406%3Ae003%3A1dd7%3A2901%3Af391%3A2856%3A33da%3Ac6ad&id=o-AHRaebcEPeCYBfjT9CGIkweMXK0vdPbaOX5U9LMrAtSd&itag=18&source=youtube&requiressl=yes&mh=UK&mm=31%2C29&mn=sn-no52-jijl%2Csn-ntqe6nes&ms=au%2Crdu&mv=m&mvi=1&pl=38&initcwndbps=1723750&spc=4ocVC0A8ae13ZHRWIOU5id0LDV6Q&vprv=1&mime=video%2Fmp4&ns=ignvYL8GQRg3FneJQqGi9xcG&gir=yes&clen=29047573&ratebypass=yes&dur=592.944&lmt=1652578498480530&mt=1653094858&fvip=1&fexp=24001373%2C24007246&c=WEB&txp=5319224&n=FeZ8TnMyHEkoJDdl&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAP49jVexNQW-xfSuwfGK3WQTcGxtyDWMplAU8YzG_WlmAiAn0VdTMsVxZrh3a1d9E5PnpLUcdKqkrcyijChOMsRNmA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgHf82Poyvr9im0PNp4OlB-baABd-jBZiK7ShbP0fe1gsCIBEqGGreqtDcaFZND_iVAtBQEeUPMojWlsRajWu7240q'

**Comment by dirkf** [comment]
Post the **entire** transcript. What you provided doesn't show the actual URL passed to yt-dl. For extra credit, actually place the transcript inside the triple back-quotes to get the right formatting.

Nonetheless, there's enough to show that your problem is [this](https://github.com/ytdl-org/youtube-dl/issues/30958#issuecomment-1129858822).
