### ISSUE TITLE
Using arte.tv fetcher

### ISSUE THREAD

**Issue by mc11255** [ytdl-org/youtube-dl#30963]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
xxx@yyy:~$ youtube-dl https://www.arte.tv/fr/videos/107479-000-A/elle/
[ArteTV] 107479-000-A: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

xxx@yyy:~$ youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

So what !!!

**Comment by dirkf** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30927#issuecomment-1121174218

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30980
