### ISSUE TITLE
download is extremly slow

### ISSUE THREAD

**Issue by TheInfamousToTo** [ytdl-org/youtube-dl#30960]
## Description

i noticed that the download speed is extremely slow (max:63.2 kbit/s)
is there is a solution for this
note: used different ISP and different machine but the same results

**Comment by dirkf** [comment]
If the site is youtube.com (or some alias of it), see #30773. Otherwise open a [broken site support issue](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md) for the site.
