### ISSUE TITLE
After migrating to a new server, 95% of my archive is redownloaded, even though the archive file hasn't changed.

### ISSUE THREAD

**Issue by tanevanwifferen** [ytdl-org/youtube-dl#30977]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hey, can someone help me debug this? I have migrated from one arch linux box to another, and when I run youtube-dl, it tells me "downloading 975 files". I have however only added a few files to my youtube playlist, and I expect it to be at most 10 downloads. I have no idea what is going wrong. On the old box everything worked fine.

**Comment by afterdelight** [comment]
where did you keep your archive file? show your verbose log

**Comment by tanevanwifferen** [comment]
```youtube-dl -v --rm-cache-dir --restrict-filenames  --download-archive /mnt/sdb1/music/script/archive.txt --output "/mnt/sdb1/music/output/%(title)s.%(ext)s" --exec "ffmpeg -i {}  -codec:a libmp3lame -filter:a loudnorm -qscale:a 0 {}.mp3 && rm {} ; npm run-script upload "{}.mp3"" https://www.youtube.com/playlist?list=PLAuqlJkfDwNdu6DNm98FKAMPacDEbI2Dj
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--rm-cache-dir', '--restrict-filenames', '--download-archive', '/mnt/sdb1/music/script/archive.txt', '--output', '/mnt/sdb1/music/output/%(title)s.%(ext)s', '--exec', 'ffmpeg -i {}  -codec:a libmp3lame -filter:a loudnorm -qscale:a 0 {}.mp3 && rm {} ; npm run-script upload {}.mp3', 'https://www.youtube.com/playlist?list=PLAuqlJkfDwNdu6DNm98FKAMPacDEbI2Dj']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.4 (CPython) - Linux-5.16.16-arch1-1-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0, ffprobe 5.0
[debug] Proxy map: {}
Removing cache dir /home/tane/.cache/youtube-dl ..
[youtube:tab] PLAuqlJkfDwNdu6DNm98FKAMPacDEbI2Dj: Downloading webpage
[download] Downloading playlist: musics
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] Downloading page 3
[youtube:tab] Downloading page 4
[youtube:tab] Downloading page 5
[youtube:tab] Downloading page 6
[youtube:tab] Downloading page 7
[youtube:tab] Downloading page 8
[youtube:tab] Downloading page 9
[youtube:tab] playlist musics: Downloading 975 videos
[download] Downloading video 1 of 975
```

this is my archive: https://pastebin.com/2dzZ1bhX

**Comment by afterdelight** [comment]
if the archive file is next to the script, you don't need to specify the download archive path i guess? I only use windows so i dont know whats the format on your OS. just write it like '--download-archive archive.txt' ?

**Comment by tanevanwifferen** [comment]
I tried both. Both didn't work.. can I print the urls it tries to download? Maybe I'm too fast with calling a bug and it will skip videos once it reaches them? My playlist is new->old, so the ones to download are at the top..

**Comment by afterdelight** [comment]
have you try with the latest commit or yt-dlp? post your full verbose log until it reached downloading progress part

**Comment by tanevanwifferen** [comment]
okay, never mind. It skips the songs that are already in archive. It  tries to download one song, then checks the archive and skips it. Then it tries the next song until a song is found that is not in the archive.
