### ISSUE TITLE
Using nodejs on linux, cannot find the youtube-dl program

### ISSUE THREAD

**Issue by GuntherCS** [ytdl-org/youtube-dl#30982]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, I am making something using nodejs with your wrapper but my system is linux and it cannot find the youtube-dl file that I downloaded in the releases, I was wondering if there is any fix for that, I have tried everything and still nothing works.

**Comment by dirkf** [comment]
We can't guess how your weird setup is failing. Provide more details, such as:
* where is yt-dl installed?
* what is the value of your `PATH` environment variable?
* what NodeJS function is used to execute the program?
* code excerpts.

**Comment by dirkf** [comment]
@GuntherCS ?
