### ISSUE TITLE
Please include YouTube's heatmap data (and chapters and info cards)

### ISSUE THREAD

**Issue by niklas-englert** [ytdl-org/youtube-dl#30983]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

youtube-dl already provides elaborate metadata about a YouTube video beyond just title and available formats.The JSON file usually includes the entire description text, tags and categories, current view count and likes, details about copyright and music, details about channel, the age limit in years, etc.  
However, I couldn't help but notice that newer features of YouTube are completely missing in the docs: The chapters displayed as a spitted progress bar, info cards and the below explained new "most replayed" graph. I would be very happy if these features could be added some day.

Since Mai 18 YouTube started to finally roll out a feature adding a "most replayed" graph (internal name "heatmap") to the progress bar after experimenting with it for at least two years. (see [this tweet](https://twitter.com/TeamYouTube/status/1527024322359005189))
![FTEUf - WQAIHXTd](https://user-images.githubusercontent.com/24723486/170784958-5a2ad72c-7f84-47e5-b132-f7cf40be54ae.jpeg)

I'm currently helping myself laboriously with a self-written web extension. I hope what I found out so far is somehow helpful:  
YouTube's implementation on the web page is relatively straight forward and easy to extract (using an extension inject). A SVG tag on the page (`svg.ytp-heat-map-svg` 1000x100) contains a path defined with [cubic Bézier curves](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#cubic_b%C3%A9zier_curve) (a `C` followed by three `x,y` pairs).  
Every third `x,y` parameter after a `C`, where `x` ends with `5.0`, is a usable data point:   
`x` is the time stamp in percent. Just compute `(x-5)/1000` for a value from 0 to 1.  
`y` is the heat value for this time period. Just compute  `(100-y)/100`  for a value from 0 to 1. 

**Example:** 

Here's the SVG tag for [this video](https://www.youtube.com/watch?v=Z8Z51no1TD0):
```html
<svg class="ytp-heat-map-svg" height="100%" preserveAspectRatio="none" version="1.1" viewBox="0 0 1000 100" width="100%" style="height: 40px;">
  <defs>
    <clipPath id="hm_1_0">
      <path class="ytp-heat-map-path" d="M 0.0,100.0 C 1.0,80.0 2.0,5.6 5.0,0.0 C 8.0,-5.6 11.0,57.4 15.0,71.8 C 19.0,86.1 21.0,71.3 25.0,71.8 C 29.0,72.2 31.0,73.0 35.0,74.0 C 39.0,75.1 41.0,76.3 45.0,77.0 C 49.0,77.7 51.0,77.0 55.0,77.5 C 59.0,78.0 61.0,79.0 65.0,79.7 C 69.0,80.4 71.0,80.9 75.0,81.0 C 79.0,81.1 81.0,80.3 85.0,80.2 C 89.0,80.1 91.0,80.3 95.0,80.7 C 99.0,81.0 101.0,81.5 105.0,81.8 C 109.0,82.2 111.0,82.1 115.0,82.4 C 119.0,82.6 121.0,82.7 125.0,82.9 C 129.0,83.1 131.0,83.5 135.0,83.4 C 139.0,83.4 141.0,82.7 145.0,82.4 C 149.0,82.2 151.0,82.3 155.0,82.3 C 159.0,82.2 161.0,82.7 165.0,82.1 C 169.0,81.4 171.0,79.3 175.0,78.9 C 179.0,78.6 181.0,80.2 185.0,80.4 C 189.0,80.5 191.0,79.7 195.0,79.7 C 199.0,79.6 201.0,80.4 205.0,80.1 C 209.0,79.8 211.0,78.5 215.0,78.2 C 219.0,77.9 221.0,78.5 225.0,78.8 C 229.0,79.0 231.0,79.6 235.0,79.6 C 239.0,79.6 241.0,78.6 245.0,78.7 C 249.0,78.8 251.0,79.8 255.0,80.0 C 259.0,80.2 261.0,79.8 265.0,79.8 C 269.0,79.8 271.0,79.9 275.0,80.1 C 279.0,80.2 281.0,80.7 285.0,80.6 C 289.0,80.5 291.0,79.7 295.0,79.5 C 299.0,79.3 301.0,79.9 305.0,79.8 C 309.0,79.7 311.0,78.9 315.0,78.8 C 319.0,78.8 321.0,79.2 325.0,79.5 C 329.0,79.8 331.0,80.2 335.0,80.2 C 339.0,80.3 341.0,80.0 345.0,79.8 C 349.0,79.6 351.0,79.4 355.0,79.3 C 359.0,79.2 361.0,79.3 365.0,79.2 C 369.0,79.2 371.0,79.1 375.0,79.0 C 379.0,79.0 381.0,79.1 385.0,79.1 C 389.0,79.1 391.0,79.3 395.0,79.0 C 399.0,78.7 401.0,78.0 405.0,77.7 C 409.0,77.5 411.0,77.7 415.0,77.8 C 419.0,77.9 421.0,78.3 425.0,78.3 C 429.0,78.3 431.0,78.1 435.0,77.9 C 439.0,77.6 441.0,77.3 445.0,77.1 C 449.0,76.8 451.0,77.0 455.0,76.7 C 459.0,76.4 461.0,75.7 465.0,75.5 C 469.0,75.4 471.0,76.3 475.0,76.1 C 479.0,75.9 481.0,74.9 485.0,74.4 C 489.0,73.8 491.0,73.6 495.0,73.3 C 499.0,73.0 501.0,72.8 505.0,72.6 C 509.0,72.5 511.0,72.8 515.0,72.5 C 519.0,72.1 521.0,71.2 525.0,70.9 C 529.0,70.6 531.0,70.7 535.0,70.8 C 539.0,70.9 541.0,71.3 545.0,71.2 C 549.0,71.1 551.0,70.2 555.0,70.3 C 559.0,70.3 561.0,71.3 565.0,71.6 C 569.0,71.8 571.0,71.5 575.0,71.5 C 579.0,71.6 581.0,71.7 585.0,71.8 C 589.0,71.9 591.0,72.0 595.0,71.9 C 599.0,71.8 601.0,71.2 605.0,71.1 C 609.0,70.9 611.0,71.0 615.0,71.1 C 619.0,71.1 621.0,71.3 625.0,71.4 C 629.0,71.5 631.0,71.7 635.0,71.7 C 639.0,71.7 641.0,71.6 645.0,71.4 C 649.0,71.3 651.0,71.1 655.0,71.1 C 659.0,71.1 661.0,71.2 665.0,71.4 C 669.0,71.6 671.0,72.1 675.0,72.0 C 679.0,71.9 681.0,71.1 685.0,70.9 C 689.0,70.7 691.0,71.2 695.0,71.0 C 699.0,70.9 701.0,70.4 705.0,70.2 C 709.0,70.0 711.0,70.1 715.0,70.0 C 719.0,70.0 721.0,70.1 725.0,70.0 C 729.0,69.9 731.0,69.6 735.0,69.7 C 739.0,69.7 741.0,70.2 745.0,70.5 C 749.0,70.8 751.0,71.0 755.0,71.0 C 759.0,71.0 761.0,70.5 765.0,70.6 C 769.0,70.7 771.0,71.4 775.0,71.6 C 779.0,71.7 781.0,71.3 785.0,71.4 C 789.0,71.4 791.0,71.6 795.0,71.9 C 799.0,72.1 801.0,72.7 805.0,72.8 C 809.0,73.0 811.0,72.7 815.0,72.8 C 819.0,72.8 821.0,72.7 825.0,73.1 C 829.0,73.5 831.0,74.0 835.0,74.8 C 839.0,75.7 841.0,76.5 845.0,77.1 C 849.0,77.8 851.0,77.7 855.0,78.1 C 859.0,78.5 861.0,78.7 865.0,79.0 C 869.0,79.4 871.0,79.6 875.0,79.8 C 879.0,80.0 881.0,80.0 885.0,80.2 C 889.0,80.3 891.0,80.2 895.0,80.5 C 899.0,80.9 901.0,81.1 905.0,81.8 C 909.0,82.5 911.0,83.1 915.0,84.1 C 919.0,85.1 921.0,85.9 925.0,87.1 C 929.0,88.2 931.0,89.4 935.0,90.0 C 939.0,90.6 941.0,90.0 945.0,90.0 C 949.0,90.0 951.0,90.0 955.0,90.0 C 959.0,90.0 961.0,90.0 965.0,90.0 C 969.0,90.0 971.0,90.0 975.0,90.0 C 979.0,90.0 981.0,90.0 985.0,90.0 C 989.0,90.0 992.0,90.0 995.0,90.0 C 998.0,90.0 999.0,88.0 1000.0,90.0 C 1001.0,92.0 1000.0,98.0 1000.0,100.0" fill="white" fill-opacity="0.6"></path>
    </clipPath>
  </defs>
  <rect class="ytp-heat-map-graph" clip-path="url(#hm_1_0)" fill="white" fill-opacity="0.2" height="100%" width="100%" x="0" y="0"></rect>
  <rect class="ytp-heat-map-hover" clip-path="url(#hm_1_0)" height="100%" x="0" y="0"></rect>
  <rect class="ytp-heat-map-play" clip-path="url(#hm_1_0)" height="100%" x="0" y="0"></rect>
</svg>
```
...and boiled down data:
```js
"heatmap":[[0,1],[0.01,0.282],[0.02,0.282],[0.03,0.26],[0.04,0.23],[0.05,0.225],[0.06,0.203],[0.07,0.19],[0.08,0.198],[0.09,0.193],[0.1,0.182],[0.11,0.176],[0.12,0.171],[0.13,0.166],[0.14,0.176],[0.15,0.177],[0.16,0.179],[0.17,0.211],[0.18,0.196],[0.19,0.203],[0.2,0.199],[0.21,0.218],[0.22,0.212],[0.23,0.204],[0.24,0.213],[0.25,0.2],[0.26,0.202],[0.27,0.199],[0.28,0.194],[0.29,0.205],[0.3,0.202],[0.31,0.212],[0.32,0.205],[0.33,0.198],[0.34,0.202],[0.35,0.207],[0.36,0.208],[0.37,0.21],[0.38,0.209],[0.39,0.21],[0.4,0.223],[0.41,0.222],[0.42,0.217],[0.43,0.221],[0.44,0.229],[0.45,0.233],[0.46,0.245],[0.47,0.239],[0.48,0.256],[0.49,0.267],[0.5,0.274],[0.51,0.275],[0.52,0.291],[0.53,0.292],[0.54,0.288],[0.55,0.297],[0.56,0.284],[0.57,0.285],[0.58,0.282],[0.59,0.281],[0.6,0.289],[0.61,0.289],[0.62,0.286],[0.63,0.283],[0.64,0.286],[0.65,0.289],[0.66,0.286],[0.67,0.28],[0.68,0.291],[0.69,0.29],[0.7,0.298],[0.71,0.3],[0.72,0.3],[0.73,0.303],[0.74,0.295],[0.75,0.29],[0.76,0.294],[0.77,0.284],[0.78,0.286],[0.79,0.281],[0.8,0.272],[0.81,0.272],[0.82,0.269],[0.83,0.252],[0.84,0.229],[0.85,0.219],[0.86,0.21],[0.87,0.202],[0.88,0.198],[0.89,0.195],[0.9,0.182],[0.91,0.159],[0.92,0.129],[0.93,0.1],[0.94,0.1],[0.95,0.1],[0.96,0.1],[0.97,0.1],[0.98,0.1],[0.99,0.1]]
```

**Comment by 89z** [comment]
Can you please just post an image of what this is, instead of forcing people off site to try to figure it out?

**Comment by niklas-englert** [comment]
@89z There's already an image, but I can edit it to make it more obvious.

**Comment by 89z** [comment]
Yeah I see it now, but its pretty subtle. Up to you.

**Comment by 89z** [comment]
Are you certain the data is only available via SVG? We can parse that if need be, but I suspect it might be in the JSON somewhere

**Comment by niklas-englert** [comment]
> inside an SVG file

I extracted that "on the web page" as an SVG tag inside the DOM using chrome dev tools. You most definitely don't need an "XML parser", just what ever technique use for the other data as well. As you said, "it might be in the JSON somewhere".

>  Are you certain the data is only available via SVG?

No, not at all. I know nothing how youtube-dl works internally and how it grabs its data.

**Comment by 89z** [comment]
> I extracted that "on the web page" as an SVG tag inside the DOM using chrome dev tools. You most definitely don't need an "XML parser", just what ever technique use for the other data as well. As you said, "it might be in the JSON somewhere".

You seem to really be downplaying the complexity of whats involved here. Do you have an implementation you can present for consideration?

> No, not at all. I know nothing how youtube-dl works internally and how it grabs its data.

Right. So it might be best to not make assumptions of how difficult something is, in regards to this project.

**Comment by niklas-englert** [comment]
@89z I think this is a misunderstanding. I'm not "make assumptions" or "downplaying" anything. I'm sorry you're getting hung up on "YouTube's implementation on the web page is relatively straight forward and easy to extract.".
 
I wrote this thinking about my current solution of using a self-written web extension to grab this data. It was as easy for *me* to crawl this graph data as everything else (title, tags, description, ...). Therefore I wrote "on the web page [...] easy to extract", as I meant being *literally on the web page* with a browser. 

I just wanted to present what I have already found, without going to much into detail on my private extension solution, cause I assumed that would be unnecessarily distracting. This mindset combined with the stress of having to correctly translate this from German into English. You just lack so much more sensitivity how statements come across in context and what details are missing, when it's not your mother tongue. I'll try to fix that...

**Comment by 89z** [comment]
> I wrote this thinking about my current solution of using a self-written web extension to grab this data. It was as easy for _me_ to crawl this graph data as everything else (title, tags, description, ...). Therefore I wrote "on the web page [...] easy to extract", as I meant being _literally on the web page_ with a browser.

YouTube-DL is not a web browser. Its a wholly different client, written in Python. So something that might be quite simple with a browser, might be quite difficult or impossible to do with YouTube-DL. For some examples, just look at CAPTCHA [1], or Widevine [2], or even throttle implementation [3]. Hopefully you can now understand that what might be easy with a WebExtension, might not be easy with Python or YouTube-DL.

1. https://wikipedia.org/wiki/CAPTCHA
2. https://wikipedia.org/wiki/Widevine
3. https://github.com/ytdl-org/youtube-dl/issues/29326

**Comment by dirkf** [comment]
In particular, we get the YT page as it's sent before any client-side JS has run. Any other metadata has to be available through some web API.

Having said that, yt-dlp has implemented a lot more metadata extraction, so you should investigate whether that meets your needs better. The devs may be more receptive to complex enhancements of the Yt extractor. I know that I'm not likely to have time to implement such things myself, though of course plausible pull requests are always welcome.

**Comment by niklas-englert** [comment]
@dirkf Thanks, I didn't know about yt-dlp. They got the chapter data, but (currently) missing the heatmap data. I'll open this issue [there](https://github.com/yt-dlp/yt-dlp/issues).
