### ISSUE TITLE
Updated version on Windows 

### ISSUE THREAD

**Issue by wusong73** [ytdl-org/youtube-dl#30986]
## Checklist

- [x ] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Windows .exe file created on  Dec 2021 . I need to run on windows most updated version with bug fixes related to youtube subtitle downloads. What is the most simple way to do this ? Thanks

**Comment by dirkf** [comment]
Install Python 3 (eg 3.10). Use _pip_ to install from the master branch here. Eg:
```
python -m pip install "https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip"
```
See https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/.

**Comment by wusong73** [comment]
Thanks ! Seems like package installed (can see in the package list)  . How to run the youtube-dl now ?
Sorry , not really a sw guy

**Comment by wusong73** [comment]
PS C:\Users\WS> python -m pip install "https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip"
Defaulting to user installation because normal site-packages is not writeable
Collecting https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip
  Downloading https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip
     \ 2.1 MB 4.2 MB/s 0:00:00
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for youtube-dl, since package 'wheel' is not installed.
Installing collected packages: youtube-dl
  Running setup.py install for youtube-dl ... done
Successfully installed youtube-dl-2021.12.17
WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
You should consider upgrading via the 'E:\Program Files\Python310\python.exe -m pip install --upgrade pip' command.
--------------------------------------------------------------------------------------------------
PS E:\Program Files\Python310> python.exe -m pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in e:\program files\python310\lib\site-packages (22.0.4)
Collecting pip
  Downloading pip-22.1.1-py3-none-any.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 5.5 MB/s eta 0:00:00
Installing collected packages: pip
  WARNING: The scripts pip.exe, pip3.10.exe and pip3.exe are installed in 'C:\Users\WS\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-22.1.1
WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
You should consider upgrading via the 'E:\Program Files\Python310\python.exe -m pip install --upgrade pip' command.

**Comment by dirkf** [comment]
Possibly a `youtube-dl` script or executable has been installed in `C:\Users\WS\AppData\Roaming\Python\Python310\Scripts`, which, as the warning says, you could add to your PATH. If you don't find it, you can use `python -m youtube_dl` as the `youtube-dl` command.

**Comment by wusong73** [comment]
Thank you ! Its working
