### ISSUE TITLE
Youtube list-formats the process freezes

### ISSUE THREAD

**Issue by Be1zebub** [ytdl-org/youtube-dl#30999]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=-tnfvrKZn-A', '-F', '-4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-14-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] -tnfvrKZn-A: Downloading webpage
```

## Description
It just freezes sometimes.
im sure its not related to the youtube rate-limit.
I think that youTube-dl should do retry if youtube does not respond for more than X seconds.
ive test it with this command: `timeout 15 youtube-dl 'https://www.youtube.com/watch?v=-tnfvrKZn-A' -F -4 -v`

**Comment by dirkf** [comment]
Please try this elsewhere (ie, not on your normal LAN or phone internet). Eg: if this happens using mobile data on your phone, try using a WiFi link; if it happens on your home PC, try connecting the PC via your mobile phone set up as a WiFi hotspot.

It's most likely that the problem is in the network between the yt-dl host and YT. There may also be state-level interference in the path, especially in PRC but possibly in .ru too.

**Comment by Be1zebub** [comment]
yes, indeed, this problem is observed only on my vps.
ive tested it on my pc and on another vps & everything works fine there. but still, this does not negate the fact that youtube-dl must do retry if the request fails.

**Comment by dirkf** [comment]
I would say fix the choice of VPS or its networking setup, or write a script for the problem server that performs the retry.

**Comment by Be1zebub** [comment]
how can i check is youtube-dl freezes?
Idk how to "write a script for the problem server that performs the retry."

**Comment by pukkandan** [comment]
The amount of time "stuck" can be reduced by decreasing `--socket-timeout`. Then you can check for error code and retry

**Comment by dirkf** [comment]
The words from my fingers on the keyboard!

As far as I can see, yt-dl returns 1 for almost any error but a script could trap a specific error by parsing the text sent to the standard error output.

Whether there should be some more specific set of error return values is a topic for further study.
