### ISSUE TITLE
YouTube-dl setup on Linux

### ISSUE THREAD

**Issue by bobpop54** [ytdl-org/youtube-dl#30995]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Hi!

I'm using youtube-dl on MS Window and it works fine.  Any suggestions on how to set it up on Linux?  Any sample docs that you can share will greatly be appreciated.

Thanks!

BK

**Comment by UmpquaRiver** [comment]
To quote the main page, type these commands in terminal:
```

sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```

**Comment by gamer191** [comment]
Use `pip install --upgrade youtube-dl`

That said, youtube-dl is made for old computers. If you have a computer compatible with it, use [yt-dlp](https://github.com/yt-dlp/yt-dlp) (after first reviewing https://github.com/yt-dlp/yt-dlp/#differences-in-default-behavior)

**Comment by rautamiekka** [comment]
> youtube-dl is made for old computers.

Not the age of the computer but the age of the distro that hasn't brought Py3 into its repos (or can't be compiled on, which would be top on the weird list).

**Comment by dirkf** [comment]
Whichever way you go @bobpop54, did you find the installation instructions for Linux unclear? Or were they difficult to find? Help us to improve.

**Comment by bobpop54** [comment]
Hello!

Thanks for the advice.  Let me look into it.

And my system actually is an old one.  It's an old desktop that stopped
working.  I converted it from MS Windows to Umbuntu.  So youtube-dl should
work fine on it.

**Comment by bobpop54** [comment]
Let me play with it again.  I tried previously to use curl but it did not
work. System could not find it.

**Comment by bobpop54** [comment]
Hello!

Thanks for getting back to me.

I only saw the commands to install, curl and then the chmod.  Did you
happen to have any more detailed instructions?

**Comment by dirkf** [comment]
The instructions here https://github.com/ytdl-org/youtube-dl#user-content-installation should work, even or especially on an old Ubuntu.

What happened to _curl_? If necessary, `sudo apt-get install curl` or some such, or use `wget` (or download with your browser and copy the resulting file).

**However**, the release version is a bit out of date. Currently a good solution is to install from this repository instead, if the _pip_ installed with your Python is [sufficiently recent](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/):
```
python3 -m pip install https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.tar.gz
```
If the system is so old that it doesn't have Python3, use Python (2.7) instead.

**Comment by bobpop54** [comment]
Hello!

I did not use curl.  I used the other install because when I tried to
execute it, it did not see curl.  let me play with it again.

Thanks!
