### ISSUE TITLE
Please Help! youtube-dl refusing commands

### ISSUE THREAD

**Issue by elliotconnor** [ytdl-org/youtube-dl#30991]
Hi there folks,

Hoping someone can jump in with a quick fix. I last used youtube-dl about a year ago and it worked great. Today I've been trying to use it again and am being met with either of the following error messages:

[youtube] 7vf1RHvbIQw: Downloading webpage
WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests
[youtube] 7vf1RHvbIQw: Downloading API JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

'--youtube-dl' is not recognized as an internal or external command,
operable program or batch file.

What should I do to get it working? I've already tried removing the youtube-dl programme and completely reinstalling.

Thanks in advance!

**Comment by rautamiekka** [comment]
Don't skip the ticket (aka issue) template, there's no way to help you with this info.
