### ISSUE TITLE
[ITV] SSLError: read timeout (from #30992)

### ISSUE THREAD

**Issue by IsaacG96** [ytdl-org/youtube-dl#30994]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-f', u'bestvideo+bestaudio/best', u'-o', u'%(title)s.%(ext)s', u'-ciw', u'--write-sub', u'--convert-subs', u'srt', u'https://www.itv.com/hub/isle-of-man-tt/1a7918a0188https://www.itv.com/hub/isle-of-man-tt/1a7918a0188']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[debug] Using fake IP 25.80.8.219 (GB) as X-Forwarded-For.
[ITV] 1a7918a0188https: Downloading webpage

ERROR: Unable to download webpage: ('The read operation timed out',) (caused by SSLError('The read operation timed out',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2737, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1208, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1178, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 452, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 408, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 754, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 641, in read
    v = self._sslobj.read(len)
```

## Description

Was trying to download ITV Hub programme, unsure if this is support as I have used ytdl before for ITV content.

**Comment by dirkf** [comment]
Known issue: #30578
Specify a weird user agent to break in.

**Comment by dirkf** [comment]
@IsaacG96 ?

**Comment by IsaacG96** [comment]
> @IsaacG96 ?

Sorry, I succeeded using a different tool (yt-dlp.exe) in the end as I was presented with further errors using ytdl, the error is below if interested:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--user-agent', 'Chrome/200', '-F', 'https://www.itv.com/hub/isle-of-man-tt/1a7918a0188']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[debug] Using fake IP 25.23.13.150 (GB) as X-Forwarded-For.
[ITV] 1a7918a0188: Downloading webpage
[ITV] 1a7918a0188: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by dirkf** [comment]
Same error with yt-dlp and with yt-dl PR #30266 and `--user-agent 'Mozilla/5.0`.

The page says:
>Episode not available
>
>We're sorry, the episode you're looking for is either coming soon or is no longer available.

**Comment by dirkf** [comment]
I finally noticed that the original failure log also had an invalid URL in the command (`https://www.itv.com/hub/isle-of-man-tt/1a7918a0188https://www.itv.com/hub/isle-of-man-tt/1a7918a0188`). However the correct URL would also have failed in 2021.12.17:
```ShellSession
$ youtube-dl -v -F 'https://www.itv.com/hub/isle-of-man-tt/1a7918a018'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.itv.com/hub/isle-of-man-tt/1a7918a018']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[debug] Using fake IP 25.254.21.175 (GB) as X-Forwarded-For.
[ITV] 1a7918a018: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

$
```
Now with the latest PR #30266:
```ShellSession
$ python -m youtube_dl -v -F 'https://www.itv.com/hub/isle-of-man-tt/1a7918a018'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.itv.com/hub/isle-of-man-tt/1a7918a018']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Git HEAD: 7e147a7ae
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[debug] Using fake IP 25.97.212.28 (GB) as X-Forwarded-For.
[ITV] 1a7918a018: Downloading webpage
ERROR: 1a7918a018: Episode not available - Isle of Man TT
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl/extractor/itv.py", line 161, in _real_extract
    raise ExtractorError(title, expected=True, video_id=video_id)
ExtractorError: 1a7918a018: Episode not available - Isle of Man TT

$
```

**Comment by IsaacG96** [comment]
> I finally noticed that the original failure log also had an invalid URL in the command (`https://www.itv.com/hub/isle-of-man-tt/1a7918a0188https://www.itv.com/hub/isle-of-man-tt/1a7918a0188`). However the correct URL would also have failed in 2021.12.17:

Apologies, that was a silly mistake (double-paste).

The correct url is: https://www.itv.com/hub/isle-of-man-tt/1a7918a0188 but this is now not available in ITV, the next available one is: https://www.itv.com/hub/isle-of-man-tt/1a7918a0190 as the ../1a7918a01889 is also no longer available.

Noted I will try with the pull request method for an alternative solution, for next time

Appreciate your time and assistance with this.

I will now close this issue.
