### ISSUE TITLE
TypeError: Not Enough Arguements To Format A String 

### ISSUE THREAD

**Issue by Joekhanh** [ytdl-org/youtube-dl#31005]
I've looked around but can't find a solution to this problem.

So every time i try to download a video or playlist it comes up with "TypeError: Not Enough Arguements To Format A String", I don't know why it's coming up or anything.

**Comment by dirkf** [comment]
The question I am going to answer is "How should I report an issue with a supported site so that someone who is not a mind-reader can help with it?" and the answer is "Start here: https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md".
