### ISSUE TITLE
Youtube-dl configuration file with playlist

### ISSUE THREAD

**Issue by gl86** [ytdl-org/youtube-dl#31002]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, i am trying to use a config file along with a playlist to download.  I have created a file named config.txt (and later tried with youtube-dl.conf) with the following line

[--output "/mnt/network_HDD/YoutubeDL_Downloads"](url)
I have also created a txt file containing urls to download named list.txt.
Both file is located in ~/
Then i have entered the following into terminal window

`sudo youtube-dl --config-location ~/config.txt -f best -a ~/`list.txt
So i have got an error of "fixed output name but multiple files to download".
If i enter only
[sudo youtube-dl -f best -a ~/list.txt](url)
everything works fine.
What do i do wrong, i.e. how can i use a config for multiple downloads?
thanks

**Comment by dirkf** [comment]
You're asking for multiple downloads and one download filename.

The `--output` parameter needs to contain template fields that will be filled in with metadata from each downloaded file, such as `%(title)s`. Read the OUTPUT TEMPLATES section in the manual.

**Comment by gl86** [comment]
thanks! I will follow your suggestion

**Comment by gl86** [comment]
It works perfectly, thank you. Somehow i have missed this important fact by reading through the documentation
