### ISSUE TITLE
[solved]

### ISSUE THREAD

**Issue by bunnywonyo** [ytdl-org/youtube-dl#31001]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

env: python: No such file or directory 
this is what i get when i use youtube-dl 
and i tried all reinstalling, but it still not helping me, and show that. 
how can i solve this? 
and sometimes i get down below thing too 
zsh: parse error near `&'

**Comment by dirkf** [comment]
>env: python: No such file or directory
this is what i get when i use youtube-dl
and i tried all reinstalling, but it still not helping me, and show that.

If you are installing on a Mac with a recent MacOS, you need to install Python: see #30746. Otherwise, post details of your OS with a terminal log of the error.

>and sometimes i get down below thing too
zsh: parse error near `&'

Use single quotes around the URL (see #30195): `youtube-dl 'https://some.example.com/video'`

**Comment by bunnywonyo** [comment]
I just tried what you gave me. but it did not help. Can you see this and tell me what is wrong? 
@dirkf 
> Last login: Sat Jun  4 05:45:28 on ttys000
celina@malinaucBookPro ~ % youtube-dl WARNING: [youtube] MCy7s-c5xAw: Failed to parse JSON Unterminated string starting at: line 1 column 60361 (char 60360)
zsh: no matches found: [youtube]
celina@malinaucBookPro ~ % youtube-dl "https://www.youtube.com/watch?v=CDHwBqogoXk&list=RDMMCDHwBqogoXk&start_radio=1" -F
env: python: No such file or directory
celina@malinaucBookPro ~ % python -m youtube_dl -v -F https://www.youtube.com/watch?v=CDHwBqogoXk&list=RDMMCDHwBqogoXk&start_radio=1
zsh: parse error near `&'
celina@malinaucBookPro ~ % python -m youtube_dl -v -F 'https://vk.com/video/tourisme?z=video-98811431_456239905%2Fpl_cat_trends'
zsh: command not found: python
celina@malinaucBookPro ~ % atom ~/.bash_profile;
zsh: command not found: atom
celina@malinaucBookPro ~ % python ~/.bash_profile;
zsh: command not found: python
celina@malinaucBookPro ~ % python3 ~/.bash_profile;
/usr/local/bin/python3: can't open file '/Users/celina/.bash_profile': [Errno 2] No such file or directory
celina@malinaucBookPro ~ % echo “alias python=/usr/bin/python3” >> ~/.zshrc
celina@malinaucBookPro ~ % echo “alias python=/usr/bin/python3”            
“alias python=/usr/bin/python3”
celina@malinaucBookPro ~ % youtube-dl "https://www.youtube.com/watch?v=CDHwBqogoXk&list=RDMMCDHwBqogoXk&start_radio=1" -F           
env: python: No such file or directory
celina@malinaucBookPro ~ % python -m youtube_dl -v -F 'https://vk.com/video/tourisme?z=video-98811431_456239905%2Fpl_cat_trends'
zsh: command not found: python
celina@malinaucBookPro ~ % youtube-dl -ciw "https://www.youtube.com/watch?v=CDHwBqogoXk&list=RDMMCDHwBqogoXk&start_radio=1"
env: python: No such file or directory
celina@malinaucBookPro ~ % yt-dlp -ciw https://www.youtube.com/watch?v=CDHwBqogoXk&list=RDMMCDHwBqogoXk&start_radio=1
zsh: parse error near `&'
celina@malinaucBookPro ~ % /usr/local/bin/python
zsh: no such file or directory: /usr/local/bin/python
celina@malinaucBookPro ~ % brew install pyenv 
Running `brew update --preinstall`...
==> Downloading https://ghcr.io/v2/homebrew/core/autoconf/manifests/2.71
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/autoconf/blobs/sha256:de8f4aa41
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pyenv/manifests/2.3.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pyenv/blobs/sha256:78fe667fd17d
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Installing dependencies for pyenv: autoconf
==> Installing pyenv dependency: autoconf
==> Pouring autoconf--2.71.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/autoconf/2.71: 71 files, 3.2MB
==> Installing pyenv
==> Pouring pyenv--2.3.1.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/pyenv/2.3.1: 925 files, 3.0MB
==> Running `brew cleanup pyenv`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
celina@malinaucBookPro ~ % pyenv install 3.7.3
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.3.tar.xz...
-> https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz
Installing Python-3.7.3...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 12.4 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/3m/q2gw6d7d5qg326lk1r23464h0000gn/T/python-build.20220604062526.21124
Results logged to /var/folders/3m/q2gw6d7d5qg326lk1r23464h0000gn/T/python-build.20220604062526.21124.log

Last 10 log lines:
                                                     ^
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include   -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration   -I. -I./Include -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/Users/celina/.pyenv/versions/3.7.3/include  -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/Users/celina/.pyenv/versions/3.7.3/include   -DPy_BUILD_CORE_BUILTIN  -c ./Modules/errnomodule.c -o Modules/errnomodule.o
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include   -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration   -I. -I./Include -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/Users/celina/.pyenv/versions/3.7.3/include  -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/Users/celina/.pyenv/versions/3.7.3/include   -DPy_BUILD_CORE_BUILTIN  -c ./Modules/pwdmodule.c -o Modules/pwdmodule.o
./Modules/posixmodule.c:8431:15: error: implicit declaration of function 'sendfile' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ret = sendfile(in, out, offset, &sbytes, &sf, flags);
              ^
1 error generated.
make: *** [Modules/posixmodule.o] Error 1
make: *** Waiting for unfinished jobs....
1 warning generated.
celina@malinaucBookPro ~ % pyenv global 3.7.3
pyenv: version `3.7.3' not installed
celina@malinaucBookPro ~ % pyenv global install  3.7.3
pyenv: version `install' not installed
celina@malinaucBookPro ~ % install pyenv global 3.7.3  
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
celina@malinaucBookPro ~ % pyenv install  global 3.7.3
Usage: pyenv install [-f] [-kvp] <version>
       pyenv install [-f] [-kvp] <definition-file>
       pyenv install -l|--list
       pyenv install --version

  -l/--list          List all available versions
  -f/--force         Install even if the version appears to be installed already
  -s/--skip-existing Skip if the version appears to be installed already

  python-build options:

  -k/--keep          Keep source tree in $PYENV_BUILD_ROOT after installation
                     (defaults to $PYENV_ROOT/sources)
  -p/--patch         Apply a patch from stdin before building
  -v/--verbose       Verbose mode: print compilation status to stdout
  --version          Show version of python-build
  -g/--debug         Build a debug version

For detailed information on installing Python versions with
python-build, including a list of environment variables for adjusting
compilation, see: https://github.com/pyenv/pyenv#readme

celina@malinaucBookPro ~ % pyenv version
system (set by /Users/celina/.pyenv/version)
celina@malinaucBookPro ~ % $ echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.zshrc
zsh: command not found: $
celina@malinaucBookPro ~ % echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.zshrc
celina@malinaucBookPro ~ % command -v pyenv 1>/dev/null 2>&1
celina@malinaucBookPro ~ % -v pyenv 1>/dev/null 2>&1
celina@malinaucBookPro ~ % -v pyenv 1>/dev/null 2>&1;
celina@malinaucBookPro ~ % eval "$(pyenv init -)"
celina@malinaucBookPro ~ % -v pyenv 1>/dev/null 2>&1\\\\\\  
celina@malinaucBookPro ~ % youtube-dl https://www.youtube.com/watch?v=CDHwBqogoXk&list=RDMMCDHwBqogoXk&start_radio=1
zsh: parse error near `&'
celina@malinaucBookPro ~ % youtube-dl https://youtu.be/CDHwBqogoXk
env: python: No such file or directory
celina@malinaucBookPro ~ % youtube-dl 'https://youtu.be/CDHwBqogoXk'
env: python: No such file or directory
celina@malinaucBookPro ~ % 'https://www.youtube.com/watch?v=CDHwBqogoXk&list=RDMMCDHwBqogoXk&start_radio=1'
zsh: no such file or directory: https://www.youtube.com/watch?v=CDHwBqogoXk&list=RDMMCDHwBqogoXk&start_radio=1
celina@malinaucBookPro ~ % echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.zshrc
celina@malinaucBookPro ~ % if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
celina@malinaucBookPro ~ % python3 /usr/local/bin/youtube-dl
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
celina@malinaucBookPro ~ % youtube-dl 'https://youtu.be/CDHwBqogoXk'
env: python: No such file or directory
celina@malinaucBookPro ~ %

**Comment by bunnywonyo** [comment]
i have an another issue. 
% sudo brew install python3
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

**Comment by dirkf** [comment]
By all means let us know how you fixed the problem while closing the issue.
