### ISSUE TITLE
Support for youtube json3 subtitles format

### ISSUE THREAD

**Issue by 00Creamy** [ytdl-org/youtube-dl#31012]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

by changing the fmt param when downloading a subtitles to json3, you can get a json format which despite me not understanding  fully what it contains, it feels like it's more complete compared to the other subtitles
Please add a support for it (I got a workaround for myself but I think it should be in the main module/library)

**Comment by pukkandan** [comment]
`--subtitle-format json3`

**Comment by dirkf** [comment]
It presumably does in yt-dlp. With any luck we just need this (diff from yt-dl to yt-dlp):
```diff
-    _SUBTITLE_FORMATS = ('srv1', 'srv2', 'srv3', 'ttml', 'vtt')
+    _SUBTITLE_FORMATS = ('json3', 'srv1', 'srv2', 'srv3', 'ttml', 'vtt')
```

**Comment by pukkandan** [comment]
huh, I didn't realize it doesn't work in youtube-dl. Searching through history, this is the commit that added the feature in yt-dlc/p 7e1cf1a48d7b3ad2810dd0c870d3cd7dbcb4906a

**Comment by dirkf** [comment]
Just adding the format as above was enough:
```
$ python -m youtube_dl --write-sub --sub-format json3 --skip-download QRS8MkLhQmM
[youtube] QRS8MkLhQmM: Downloading webpage
[info] Writing video subtitles to: YouTube Captions and Subtitles-QRS8MkLhQmM.en.json3
$
```

**Comment by dirkf** [comment]
Resolved by https://github.com/ytdl-org/youtube-dl/commit/811c480f7b6c25ca510a033e6365d00174135392.
