### ISSUE TITLE
[REQUEST] support xhamster.com alternative domain

### ISSUE THREAD

**Issue by afterdelight** [ytdl-org/youtube-dl#31023]
## Checklist
- [x ] I'm reporting a new site support request
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that none of provided URLs violate any copyrights
- [ x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs
single link:
https://xhday.com/videos/strapless-threesome-xhh7yVf
channle link:
https://xhday.com/users/mobhunter

## Description
Add support for xhmaster alternative domain https://xhday.com/

**Comment by dirkf** [comment]
This trivial patch does the job:
```diff
--- old/youtube_dl/extractor/xhamster.py
+++ new/youtube_dl/extractor/xhamster.py
@@ -23,7 +24,7 @@
 
 
 class XHamsterIE(InfoExtractor):
-    _DOMAINS = r'(?:xhamster\.(?:com|one|desi)|xhms\.pro|xhamster\d+\.com)'
+    _DOMAINS = r'(?:xhamster\.(?:com|one|desi)|xhms\.pro|xhamster\d+\.com|xhday\.com)'
     _VALID_URL = r'''(?x)
                     https?://
                         (?:.+?\.)?%s/
```

**Comment by afterdelight** [comment]
ty man
