### ISSUE TITLE
Constant 403 forbidden error.

### ISSUE THREAD

**Issue by WeaselGuns** [ytdl-org/youtube-dl#31031]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
No matter what I try I will randomly get the 403 forbidden error. It isn't related to the video I'm attempting to download because I can just restart the script at the video it broke at and it will continue on just fine until it seemingly happens again. I've updated and removed the cache, read the FAQ, etc. Nothing I have tried seems to help. Any ideas?

**Comment by WeaselGuns** [comment]
> please provide example URL

https://www.youtube.com/watch?v=4qjr7dW84Jg&list=PLmskRLLrTj3e-dJmDeiG8cJhjeCuEzcfm&index=105

**Comment by 89z** [comment]
Works fine:

~~~
> youtube-dl 4qjr7dW84Jg
[youtube] 4qjr7dW84Jg: Downloading webpage
[youtube] 4qjr7dW84Jg: Downloading player df5197e2
[download] Destination: Dax - 'VIBEZ' Freestyle [One Take Video]-4qjr7dW84Jg.f137.mp4
[download]   0.4% of 45.17MiB at 60.85KiB/s ETA 12:37
~~~

**Comment by WeaselGuns** [comment]
> Works fine:
> 
> ```
> > youtube-dl 4qjr7dW84Jg
> [youtube] 4qjr7dW84Jg: Downloading webpage
> [youtube] 4qjr7dW84Jg: Downloading player df5197e2
> [download] Destination: Dax - 'VIBEZ' Freestyle [One Take Video]-4qjr7dW84Jg.f137.mp4
> [download]   0.4% of 45.17MiB at 60.85KiB/s ETA 12:37
> ```

That is part of my problem. It does work. But while going through the playlist it will randomly throw the error and stop. I just restart it where it stopped and it works again. This is only an issue cause for a playlist of 200 videos I have to do it a ton to get through the whole playlist.

**Comment by q00u** [comment]
I am also experiencing this intermittent 403 error on a long playlist. It just seems to happen at random (7 times out of 110 videos). It's not a dealbreaker, because as stated, one can restart and it will likely be fine on the second attempt. It feels like a networking error that's showing up as a 403, when it isn't.
