### ISSUE TITLE
[VK.com] "ERROR: Unable to login, incorrect username and/or password" (My username and password is correct)

### ISSUE THREAD

**Issue by novikalexy** [ytdl-org/youtube-dl#31041]
The authentication algorithm on the site vk.com changed. Now on the start page in the input form you need to specify only the login, after clicking on the button in the next form you need to enter only the password. Please correct the authentication for vk.com in your module vk.py

**Comment by dirkf** [comment]
Yes, as in #31035. Meanwhile use the [`--cookies ...` procedure](https://github.com/ytdl-org/youtube-dl#user-content-how-do-i-pass-cookies-to-youtube-dl) to login instead of `--username ...`

**Comment by fonclub** [comment]
> Yes, as in #31035. Meanwhile use the [`--cookies ...` procedure](https://github.com/ytdl-org/youtube-dl#user-content-how-do-i-pass-cookies-to-youtube-dl) to login instead of `--username ...`

 /var/www/git/yt-dlp/yt-dlp -vvv --cookies /var/www/prod/vk_cookies.txt https://vk.com/video-68488417_456241704
[debug] Command-line config: ['-vvv', '--cookies', '/var/www/prod/vk_cookies.txt', 'https://vk.com/video-68488417_456241704']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.8.10 (CPython 64bit) - Linux-3.10.0-1160.66.1.el7.x86_64-x86_64-with
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.3, ffprobe 4.3.3
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [vk] Extracting URL: https://vk.com/video-68488417_456241704
[vk] -68488417_456241704: Downloading JSON metadata
ERROR: [vk] This video is only available for registered users. Use --cookies, --cookies-from-browser, --username and --password, or --netrc (vk) to provide account credentials
  File "/var/www/git/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/var/www/git/yt-dlp/yt-dlp/yt_dlp/extractor/vk.py", line 328, in _real_extract
    payload = self._download_payload('al_video', video_id, data)
  File "/var/www/git/yt-dlp/yt-dlp/yt_dlp/extractor/vk.py", line 60, in _download_payload
    self.raise_login_required()
  File "/var/www/git/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 1100, in raise_login_required
    raise ExtractorError(msg, expected=True)
