### ISSUE TITLE
[tele5.de] Error - no video download respectively no audio found

### ISSUE THREAD

**Issue by televischn** [ytdl-org/youtube-dl#31054]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Recently there have been some issues with tele5.de with ytdl-downloads functioning no longer for a few months.
Now I found that videos can be downloaded by using a manifest-URL. Up to now I only found the video-stream (manifest.mpd), but I wasn't able to find the audio-stream resp. the audio-URL.
Does anybody have the knowledge where the audio-URL can be found?
Is it possible to enable tele5-downloads again with ytdl?

For examples:
https://tele5.de/mediathek/last-hitman/
https://tele5.de/filme/

**Comment by dirkf** [comment]
The 2021.12.17 version fails as recorded in many previous issues, but the extractor has been fixed and the git master works for me, at least this far:
```shellsession
python3 -m youtube_dl -g 'https://tele5.de/mediathek/last-hitman/'
https://dplaynordics-vod-69.akamaized.net/dplaydni/242451/0/hls/10739353004/exp=1656268276~acl=%2f*~data=hdntl~hmac=d8e362bf92b379530ad5569c91b7a44816db8715c122a5dddf3f82e6362d3698/1024744653-prog_index.m3u8?hdntl=exp=1656268276~acl=/*~data=hdntl~hmac=d8e362bf92b379530ad5569c91b7a44816db8715c122a5dddf3f82e6362d3698&version_hash=89323c11
https://dplaynordics-vod-40.akamaized.net/dplaydni/242451/1/dash/10739353004/manifest.mpd?hdnts=st=1656181876~exp=1656268276~acl=/dplaydni/242451/1/dash/10739353004/*~hmac=eddd2be2989a8cc4d76eb1013b3670b2369bc0d6c9e81c4140d5f5479a1f7e2f&bw_start=800
$
```

**Comment by 89z** [comment]
FYI you can bypass the geo block like this:

~~~
POST https://eu1-prod.disco-api.com/playback/v3/videoPlaybackInfo HTTP/2.0
content-type: application/json
X-Forwarded-For: 53.0.0.0
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU0VSSUQ6ZG1heGRlOjViM2UyNDJkLWM3NTktNGQ2Mi1iNjQxLTk4YWEzNjQ3ZTgyZSIsImp0aSI6InRva2VuLTFhNWJjOWFjLTRjNTQtNGI1Mi05OTZiLTllZjA4OWNmYjEwMCIsImFub255bW91cyI6dHJ1ZSwiaWF0IjoxNjU2MTgzODc3fQ.EEPETmyJd8UkMvXJKfHPAjWAT8NTNP1euJ69agjr0w8

{
  "deviceInfo": {"adBlocker": false}, "videoId": "2609521"
}
~~~

**Comment by dirkf** [comment]
>FYI you can bypass the geo block like this:

Presuming that some block might occur when actually downloading from a link...

>```
>POST https://eu1-prod.disco-api.com/playback/v3/videoPlaybackInfo HTTP/2.0
>content-type: application/json
>X-Forwarded-For: 53.0.0.0
>authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU0VSSU...`
>
>{
>  "deviceInfo": {"adBlocker": false}, "videoId": "2609521"
>}
>```

Is this bearer token something we have to guess?

**Comment by 89z** [comment]
I captured it using MITM Proxy. I would guess you can script it, but I am not personally interested in the site, so I am not motivated to pursue it further. Good luck
