### ISSUE TITLE
Download from specific position in playlist

### ISSUE THREAD

**Issue by anondev-sudo** [ytdl-org/youtube-dl#31050]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is it possible to start downloading from YouTube playlist from specific video (position)? I have downloaded yesterday just like half of playlist and turned the pc off. Today I want to continue downloading new videos and I don't want to have duplicate videos.

**Comment by Carsillas** [comment]
You can achieve this by using the --download-archive argument. It will store which videos have already been downloaded and not redownload them. To answer your original question it is possible to specify the start and end index of the playlist using the --playlist-start and --playlist-end arguments.

https://github.com/ytdl-org/youtube-dl#how-do-i-download-only-new-videos-from-a-playlist
https://github.com/ytdl-org/youtube-dl#video-selection

**Comment by dirkf** [comment]
Read about [`--playlist-start ...` and related options](https://github.com/ytdl-org/youtube-dl#user-content-video-selection).

**Comment by anondev-sudo** [comment]
Thanks

**Comment by anondev-sudo** [comment]
Which file extension should I use for --download-archive option? Or you don't need to provide file name? Does it auto create the file and save IDs of downloaded songs to it?

**Comment by dirkf** [comment]
If you actually read what the `--help` output says:
```
    --download-archive FILE              Download only videos not listed in the
                                         archive file. Record the IDs of all
                                         downloaded videos in it.
```
you'll see that you have to supply the filename. No-one else cares what you call it.
