### ISSUE TITLE
RELEASE PLEASE

### ISSUE THREAD

**Issue by rofl0r** [ytdl-org/youtube-dl#31067]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

last release was in december last year, and that was before the code to circumvent the yt bandwidth throttling was merged. a release is direly needed so distros can update to the current codebase.

**Comment by dirkf** [comment]
https://github.com/ytdl-org/youtube-dl/issues/28859#issuecomment-1158188788 applies.

**Comment by afterdelight** [comment]
use this
https://github.com/ytdl-patched/youtube-dl/releases

**Comment by aquino-a** [comment]
use [yt-dlp](https://github.com/yt-dlp/yt-dlp). They released 9 days ago.

**Comment by rofl0r** [comment]
> use [yt-dlp](https://github.com/yt-dlp/yt-dlp). They released 9 days ago.

i'm aware of yt-dlp, but i prefer youtube-dl because it works with python2.

**Comment by rautamiekka** [comment]
> > use [yt-dlp](https://github.com/yt-dlp/yt-dlp). They released 9 days ago.
> 
> because it works with python2.

What's the point ? You can install Py3 easily.

**Comment by rofl0r** [comment]
> You can install Py3 easily.

not everyone uses ubuntu. when you have to compile python3 from source, it's no longer that easy. also the question is whether you want to waste your resources for 2 different python installs, when everything else you need works with python2. (hint: i don't want that). anyway, this is not the place to advertise yt-dlp.

**Comment by afterdelight** [comment]
this has latest release 
https://github.com/ytdl-patched/youtube-dl/releases

**Comment by rautamiekka** [comment]
> > You can install Py3 easily.
> 
> not everyone uses ubuntu. when you have to compile python3 from source, it's no longer that easy. also the question is whether you want to waste your resources for 2 different python installs, when everything else you need works with python2. (hint: i don't want that). anyway, this is not the place to advertise yt-dlp.

Shouldn't use a distro you can't be bothered to use. There's Miniconda3, which makes envs with specific Python versions pretty easy, doing all the work for you.

**Comment by rofl0r** [comment]
> Shouldn't use a distro you can't be bothered to use.

check my profile, i make my own linux distro - and you forgot to look into the main point i raised, mainly that i dont want to waste precious hdd space to install python3 just for a single app. before you continue arguing in favor of "just use python3 dude" you probably also should read [my essay](https://sabotage-linux.neocities.org/blog/8/) related to it.
anyway, again, this is youtube-dl issue tracker which explicitly supports python2; so any argumentation in favor of using a fork which drops python2 support is not on topic.

**Comment by afterdelight** [comment]
this has latest release
https://github.com/ytdl-patched/youtube-dl/releases

**Comment by gamer191** [comment]
> when you have to compile python3 from source, it's no longer that easy

Use the [standalone binary](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux), and then you don't have to install Python 3

**Comment by afterdelight** [comment]
this has latest daily release but no linux

https://github.com/ytdl-patched/youtube-dl/releases

**Comment by gamer191** [comment]
@afterdelight I was talking about yt-dlp's standalone binary, sorry for not being clear enough, I have edited my original message.

**Comment by rofl0r** [comment]
@afterdelight thanks for the ytdl-patched linked, it took me a while to scrutinize the repo in order to figure out whether it can be trusted. this is also the main issue with it: it's not official, and it would be highly preferable if @dirkf can be bothered to finally roll a release, or at least copy/paste the github action that does it manually from that link.

@ anyone else: could you please finally stop with your "just use yt-dlp bro" talk ? thanks.

**Comment by afterdelight** [comment]
i used this version for a long time and it doesnt have any problem, so you may try it

https://github.com/ytdl-patched/ytdl-patched

**Comment by gamer191** [comment]
@afterdelight [ytdl-patched/ytdl-patched](https://github.com/ytdl-patched/ytdl-patched) is a fork of yt-dlp, and @rofl0r doesn't want to use yt-dlp. [ytdl-patched/youtube-dl](https://github.com/ytdl-patched/youtube-dl/releases), which you sent before, seems to be what OP was looking for.



> it took me a while to scrutinize the repo in order to figure out whether it can be trusted

The ytdl-patched repo is [created by Lesmiscore](https://github.com/yt-dlp/yt-dlp/issues/1839#issuecomment-1000966828), who is a [yt-dlp collaborator](https://github.com/yt-dlp/yt-dlp/blob/master/Collaborators.md). Because of that, I personally do trust the daily builds. Obviously, it's your call what to install on your computer.

> or at least copy/paste the github action that does it automatically from that link

see https://github.com/ytdl-org/youtube-dl/pull/30644

**Comment by Lesmiscore** [comment]
@dirkf Sorry for ping but I strongly advise you to block [afterdelight](https://github.com/afterdelight). Reason is obvious.

**Comment by dirkf** [comment]
> Use the [standalone binary](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux), and then you can run yt-dlp without installing/compiling Python 3 :)

Provided that a binary is available for your machine architecture ...

**Comment by afterdelight** [comment]
???

**Comment by afterdelight** [comment]
> @dirkf Sorry for ping but I strongly advise you to block [afterdelight](https://github.com/afterdelight). Reason is obvious.

???

**Comment by rofl0r** [comment]
> Provided that a binary is available for your machine architecture ...

not only that, even a libc difference makes a precompiled binary unusable (unless everything is statically linked). in my case i use musl libc, not glibc.

**Comment by afterdelight** [comment]
ok

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31190

**Comment by Rekrullurker** [comment]
I just tried the latest release from that ytdl-patched page and it doesn't work. It runs, it'll print the help or the version info, but when I try to actually use it with an URL, it just dumps an unending stream of what looks like source code to the window. 

Here's a sample;

"Kva=function(a,b,c){return b=b.filter(function(d){if(d.video.j<=a.zc)return!0;c[d.itag]="maxquality";return!1})};IB=function(a){return Pk(a,function(b,c){return Math.max(b,c.video.j)},0)};Wva=function(a){a=void 0===a?{}:a;var b=void 0===a.Om?!1:a.Om,c=void 0===a.defraggedFromSubfragments?!1:"

That went on for about 30 pages before I canceled it. I tried a few others from August and got the same result. I then went back to July 1st, and that one technically worked. It printed a paragraph of crap at the start, but it did function. Unfortunately, it had no advantage that I could see over the last official release from Dec. 17th, 2021. It downloaded at a glacial speed and wouldn't download age-restricted videos.

Am I doing something wrong, or have these patched versions not been patched to bypass YouTube's throttling and the age restrictions? And why do the latest versions just print garbage?

**Comment by dirkf** [comment]
Try the version that includes https://github.com/ytdl-org/youtube-dl/commit/55c823634db890a328ffc23588fcd6f35d9b3ddf.

For age-restricted, you need PR #31043.

**Comment by Vangelis66** [comment]
> I just tried the latest release from that **ytdl-patched** page and it doesn't work.

> Try the version that includes https://github.com/ytdl-org/youtube-dl/commit/55c823634db890a328ffc23588fcd6f35d9b3ddf.

Unfortunately, the latest release [there](https://github.com/ytdl-patched/youtube-dl/releases/tag/2022.09.01.19419) hasn't got that [merged](https://github.com/ytdl-patched/youtube-dl/commits/2022.09.01.19419)... 
@Rekrullurker should exercise some patience until the new release `2022.09.02.x` has been produced - should be a matter of  a few hours... 😄

**Comment by Rekrullurker** [comment]
Just tried version 2022.09.02.810. OK, it works...

Doesn't download any faster, doesn't download age restricted videos.

I don't mean to sound ungrateful, but what's being patched, if not these issues?

**Comment by afterdelight** [comment]
> I just tried the latest release from that ytdl-patched page and it doesn't work. It runs, it'll print the help or the version info, but when I try to actually use it with an URL, it just dumps an unending stream of what looks like source code to the window.
> 
> Here's a sample;
> 
> "Kva=function(a,b,c){return b=b.filter(function(d){if(d.video.j<=a.zc)return!0;c[d.itag]="maxquality";return!1})};IB=function(a){return Pk(a,function(b,c){return Math.max(b,c.video.j)},0)};Wva=function(a){a=void 0===a?{}:a;var b=void 0===a.Om?!1:a.Om,c=void 0===a.defraggedFromSubfragments?!1:"
> 
> That went on for about 30 pages before I canceled it. I tried a few others from August and got the same result. I then went back to July 1st, and that one technically worked. It printed a paragraph of crap at the start, but it did function. Unfortunately, it had no advantage that I could see over the last official release from Dec. 17th, 2021. It downloaded at a glacial speed and wouldn't download age-restricted videos.
> 
> Am I doing something wrong, or have these patched versions not been patched to bypass YouTube's throttling and the age restrictions? And why do the latest versions just print garbage?

try earlier version, sometimes newest commit bugged the program.

**Comment by dirkf** [comment]
If anyone has an issue with the latest master, please open an issue with the usual supporting information. However in this case it looks like YT is sending new player 5a3b6271 and yt-dl is confused.

**Comment by nicolaasjan** [comment]
> If anyone has an issue with the latest master, please open an issue with the usual supporting information. However in this case it looks like YT is sending new player 5a3b6271 and yt-dl is confused.

This seems indeed the case with the latest youtube-dl `master`, as well as yt-dlp...
See:
https://github.com/yt-dlp/yt-dlp/issues/4635#issuecomment-1235203263

**Comment by Rekrullurker** [comment]
>have you try yt-dlp version?
>https://github.com/ytdl-patched/ytdl-patched/releases

I didn't want to get into this, but I have an OLD computer, running an OLD version of Windows, and yt-dlp doesn't work, because Python 3 doesn't work on it. Until I can afford to get a newer system, YouTube-DL is the only thing I can use.

**Comment by gamer191** [comment]
> I don't mean to sound ungrateful, but what's being patched, if not these issues?

Nothing, it just shares a Github account with another program named ytdl-patched

**Comment by gamer191** [comment]
> have you try yt-dlp version?
> https://github.com/ytdl-patched/ytdl-patched/releases

that's not yt-dlp. https://github.com/yt-dlp/yt-dlp and https://github.com/ytdl-patched/yt-dlp are yt-dlp

**Comment by gamer191** [comment]
> I have an OLD computer, running an OLD version of Windows

Out of interest, which version of Windows is it?

**Comment by Lesmiscore** [comment]
@dirkf PLEAAAAAAAAAAAAAAAAAAAAASE BLOCK AFTERDELIGHT FROM THIS ISSUE
They're getting an extreme noise to my hobby project

**Comment by rofl0r** [comment]
PLEAAAAASE provide official releases so this can be closed finally.

**Comment by dirkf** [comment]
Continued in #31585.
