### ISSUE TITLE
Twitch new option (skip rerun)

### ISSUE THREAD

**Issue by sx66627** [ytdl-org/youtube-dl#31064]
## Checklist

- [ x ] I'm reporting a site feature request
- [ x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x ] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I often use download streams (twitch).
I have written a script for this, so that it starts automatically.
But sometimes it happens that the streams are restarted (recording). And this video is uploading a second time.
**Example:**
any_streamer_name (live) 2022-05-05 16_27-v1475682702.mp4
any_streamer_name (rerun) 2022-05-06 19_27-v1475682742.mp4

Please add option **--skip-rerun**

**Comment by pukkandan** [comment]
Examples?

**Comment by dirkf** [comment]
Please provide example URLs for a stream and its re-run.

If the re-run title includes the text ` (rerun) `, try `--reject-title ' \(rerun\) '` (try `" \(rerun\) "` for Windows _cmd_, not tested).

Undocumented is that the option value for `--match-title ...` and `--reject-title ...`, described as `(regex or caseless sub-string)` in the Fine Manual is **always** interpreted as a regex, so any special regex characters must be escaped; special characters are `\()[]{}.*+|`.

If you pass `' (rerun) '`, the match will effectively be against `' rerun '`. The UI should have required something like `'re: \(rerun\) '` for the regex interpretation and `' (rerun) '` for the substring interpretation, but it's too late now, though we could add new option names, or extend the `--match-filter ...` option in line with yt-dlp.

**Comment by sx66627** [comment]
Thanks for the answer.
I won't be able to provide a link because it will only run for the duration of the recorded stream. The replay is the same as a regular stream.
For this reason, it is difficult to understand that now there is not a real broadcast. And only after the download is completed, you can see in the file name that it was a repeat.
I'll try what you suggested. And I'll be back later.

**Comment by sx66627** [comment]
https://prnt.sc/5kN7L8EWW2Al worked
