### ISSUE TITLE
DoodStream 403  Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError());

### ISSUE THREAD

**Issue by laven9696** [ytdl-org/youtube-dl#31062]
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Requires PR #31003, not yet merged.

Also the report does actually need to be completed.
