### ISSUE TITLE
youtube-dl can't get automatic_captions

### ISSUE THREAD

**Issue by HyeonSeong-P** [ytdl-org/youtube-dl#31076]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

i tried to get autoamatic_captions with 'writeautomaticsub' option in python.
```python
    ydl_opts = {'format': 'best[height=720,ext=mp4]',
                'writesubtitles': True,
                'writeautomaticsub': True,
                'outtmpl': 'dummy.mp4'
                }  # download options
```
there is no "automatic_captions" value in response body(json format)..
but i could get automatic captions when i run a same code ago 4 days. 
but today  i can't...
I want to know why i can't get automatic captions despite running a same code.

**Comment by dirkf** [comment]
Presumably it depends on whether the YT page that you're fetching has that feature enabled. I believe that's a user setting when uploading the content.

**Comment by dirkf** [comment]
@HyeonSeong-P ?
