### ISSUE TITLE
Help with issue "#30269"

### ISSUE THREAD

**Issue by Shbeebo** [ytdl-org/youtube-dl#31071]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, I have very very little experience with coding (infact I just made a github account 10 min ago), I have had plenty of fun with ytdl, but I'm having an issue that I know you guys have solved, but I can't decipher how you solved it. It took me like 2 days to install ytdl, so I'm worried I'll break it, when all I want is to download is a silly video of that guy saying "wake up Joe Biden", but it's a "YouTube Short" so I can't.

So what I'm asking is, can someone please explain how you made it so you could download youtube shorts like you did in #30269?

Thank you so much. Sorry to bother.

**Comment by gamer191** [comment]
~~The easiest way is to just switch to https://github.com/yt-dlp/yt-dlp. If you want you can read the [differences in default behavior](https://github.com/yt-dlp/yt-dlp#differences-in-default-behavior), but that probably won't be necessary for you, apart from moving your config file if you created one~~

Actually, just edit the url from `https://youtube.com/shorts/XXXXXXX` to `https://youtube.com/watch?v=XXXXXXX`

**Comment by pukkandan** [comment]
Or even easier, just remove `https://youtube.com/shorts/` leaving only `youtube-dl XXXXXXXXX`

**Comment by gamer191** [comment]
Oh yeah, I forgot about that :rofl:
