### ISSUE TITLE
Is there a way to pass parameters to progress hooks callbacks in yt-dl?

### ISSUE THREAD

**Issue by gmunumel** [ytdl-org/youtube-dl#31070]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

Is there a way to pass parameters to progress hooks callbacks in yt-dl?
Any alternative? 

Edited: added clarification.

**Comment by dirkf** [comment]
You really need to provide more context.

However, if you mean progress hooks that you are passing to yt-dl embedded in a Python application, a scheme like this might work:
1. create your `YoutubeDL` instance
2. `def` your progress hook, containing a binding to the instance
2. add the function to the `params['progress_hooks]` of the instance
2. stash your parameters somewhere that can be accessed from the `YoutubeDL` instance
2. access the parameters using the binding to the YoutubeDL that you lexically scoped in step 2.

**Comment by gmunumel** [comment]
Hello @dirkf , thanks for your response. Could you be more precise? I have this implementation:


    def my_hook(d):
       if d['status'] == 'finished':
          print("Done downloading")
      
    class Downloader(object):
      # ...
	
      def download(self, song):
         ydl = youtube_dl.YoutubeDL(
            {
                'progress_hooks': [my_hook],
	        }
	      )
         ydl.download([song.url])

**Comment by dirkf** [comment]
So, something like:
```py
import functools

def my_hook(ytdl, d):
   if d['status'] == 'finished':
      print("Done downloading with " + ytdl.thing_)
  
class Downloader(object):
  # ...
  def download(self, song):
     ydl = youtube_dl.YoutubeDL()
     ydl.thing_ = "parameter I passed"
     my_hookah = functools.partial(my_hook, ydl)
     ydl.params['progress_hooks'] = [my_hook]
     ydl.download([song.url])
```
Currently, the progress hooks aren't touched until the download is being set up, so this scheme should be OK. This could possibly change in the future, though I doubt it. Also, you can use an instance variable name ending in `_` to ensure that it doesn't clash with an existing one.

**Comment by pukkandan** [comment]
Afaik, the behavior of changing the params after instance creation is undefined. Also, injecting arbitrary attributes to third party objects should be discouraged imo. Why not just do this?

```py
import functools

def my_hook(thing, d):
   if d['status'] == 'finished':
      print("Done downloading with " + thing)
  
class Downloader(object):
  # ...
  def download(self, song):
     my_hookah = functools.partial(my_hook, "parameter I passed")
     ydl = youtube_dl.YoutubeDL({'progress_hooks': [my_hookah]})
     ydl.download([song.url])
```

**Comment by dirkf** [comment]
I expect that OP wants to manipulate some state in the fancy progress hook, or read from `ydl.params`, etc.

**Comment by gmunumel** [comment]
Thanks guys, both answers help me to achieve my goal.
