### ISSUE TITLE
Youtube-dl error download playlist

### ISSUE THREAD

**Issue by imadaboulhouda** [ytdl-org/youtube-dl#31079]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[youtube:tab] playlist\: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description
Error youtube-dl -i "link_playlist" 

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
>PASTE VERBOSE LOG HERE

Why not do that?

**Comment by imadaboulhouda** [comment]
> > PASTE VERBOSE LOG HERE
> 
> Why not do that?

[youtube:tab] playlist\: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Like [this](https://github.com/ytdl-org/youtube-dl/issues/31068#issuecomment-1173002398)!
