### ISSUE TITLE
How to this convert cli command to python command

### ISSUE THREAD

**Issue by nikhil96widhani** [ytdl-org/youtube-dl#31086]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

How to convert this command to python command with options. I have tried and checked docs but failing to understand. Any help will be appreciated 
```
youtube-dl --postprocessor-args "-ss 5" -o "e01s01 - title of video" 
            -f 3+bestaudio --add-header "x-playback-session-id: 
            xxxxxxxxxxxxx-xxxxxxxxxx" "https://urll_of_download_video.com" 
```

**Comment by nikhil96widhani** [comment]
I dont seem to find arguments to add for --add-header value and postprocessor arg to trim video. If you can convert this to a sample options dict. It would be a good starting point for me

**Comment by dirkf** [comment]
Look at `YoutubeDL.py`, in particular https://github.com/ytdl-org/youtube-dl/blob/5f5c127ece74e52aa5b49b6d2941cc0f848d3c36/youtube_dl/YoutubeDL.py#L317, for `postprocessor_args`.

Exceptionally, headers are passed in a global `dict`, `std_headers`, that you can import from `utils.py` https://github.com/ytdl-org/youtube-dl/blob/5f5c127ece74e52aa5b49b6d2941cc0f848d3c36/youtube_dl/utils.py#L1672.

**Comment by nikhil96widhani** [comment]
> Look at `YoutubeDL.py`, in particular
> 
> https://github.com/ytdl-org/youtube-dl/blob/5f5c127ece74e52aa5b49b6d2941cc0f848d3c36/youtube_dl/YoutubeDL.py#L317
> 
> , for `postprocessor_args`.
> Exceptionally, headers are passed in a global `dict`, `std_headers`, that you can import from `utils.py`
> 
> https://github.com/ytdl-org/youtube-dl/blob/5f5c127ece74e52aa5b49b6d2941cc0f848d3c36/youtube_dl/utils.py#L1672
> 
> .

Thank you for your reply, I was able to add the headers with 'http_headers" key but i am failing to add post processor args which will trim first 5 seconds of the video.

I am trying to use   'postprocessor_args': ["-ss 5"]. in the options. but i get error:
 'yt_dlp.utils.DownloadError: ERROR: Postprocessing: Error splitting the argument list: Option not found'

Secondly I am also trying to figure out the option key which i can use to set custom title name and set custom download video path. 

Thanks

**Comment by dirkf** [comment]
In that case, ask at https://github.com/yt-dlp/yt-dlp/issues. These things may be different in yt_dlp.

**Comment by 0xAhmad** [comment]
> postprocessor_args

'postprocessor_args': ['-ss', '5']

**Comment by 0xAhmad** [comment]
> I am trying to use 'postprocessor_args': ["-ss 5"]. in the options. but i get error: 'yt_dlp.utils.DownloadError: ERROR: Postprocessing: Error splitting the argument list: Option not found'

'postprocessor_args': ['-ss', '5']
