### ISSUE TITLE
Changing youtube_dl's SSL certificate path

### ISSUE THREAD

**Issue by Hammad-hab** [ytdl-org/youtube-dl#31089]
I am making a Youtube_DL application using tkinter and Python, I have the SSL certificate in the root folder and I want to link it to Youtube_dl, unfortunately youtube_dl doesn't detect it there, is there a way I can change where youtube_Dl detects for the certificate?

**Comment by dirkf** [comment]
How are you expecting yt-dl to use the certificate?

Normally, certificates are configured in the Python platform or its underlying OS.

**Comment by coletdjnz** [comment]
> Ive had luck with these:
> 
> ```
> $env:REQUESTS_CA_BUNDLE = 'something.pem'
> $env:SSL_CERT_FILE = 'something.pem'
> ```

REQUESTS_CA_BUNDLE won't work as youtube-dl doesn't use requests.

However I can confirm using SSL_CERT_FILE appears to work with youtube-dl (and yt-dlp if certifi is disabled).

**Comment by dirkf** [comment]
Presumably the [OpenSSL function SSL_CTX_set_default_verify_paths()](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_default_verify_paths.html) is being called under the Python hood. If your Python implementation doesn't rely on OpenSSL, it may not work, but good luck finding one of those.

`SSL_CERT_DIR` (with the obviously different semantics) may also be understood.

**Comment by Hammad-hab** [comment]
> How are you expecting yt-dl to use the certificate?
> 
> Normally, certificates are configured in the Python platform or its underlying OS.

Yes I am expecting yt-dl to locate the certificate automatically but it does not work as expected, can I some how change where youtube_dl is checking for the certificate?

**Comment by dirkf** [comment]
In general certificates can be stored as part of an OS feature (Windows, eg) or as part of a library package (OpenSSL, eg) or by the application itself (Firefox, eg).

CPython is normally built with OpenSSL but contains [code that incorporates OS certificates when run on Windows](https://github.com/python/cpython/blob/8d21aa21f2cbc6d50aab3f420bb23be1d081dac4/Lib/ssl.py#L407).

Any other Python implementation is more than likely to use OpenSSL, though Jython instead uses the certificates installed in the underlying Java VM.

Thus, as suggested above, you can generally, depending on your Python implementation, use the documentation for OpenSSL (linked above) for guidance, with various options:
1. install the certificate in the OpenSSL certificate store;
2. set the environment variable `SSL_CERT_FILE` in your shell before or when running your program;
3. set the environment variable `SSL_CERT_FILE` in your program before performing any web accesses;
4. or do something similar by putting your certificate in the directory named by `SSL_CERT_DIR`, at the cost of ignoring certificates in the default location.

In case your Python used the LibreSSL fork of OpenSSL, the `SSL_CERT_*` variables don't apply.
