### ISSUE TITLE
Get cookies.txt has been removed from the chrome extension store

### ISSUE THREAD

**Issue by xotikorukx** [ytdl-org/youtube-dl#31082]
...which means you have no way to install it now - though in edge you can manually re-enable it.

Otherwise, maybe update the readme.md to this extension? https://chrome.google.com/webstore/detail/open-cookiestxt/gdocmgbfkjnnpapoeobnolbbkoibbcif - It's marked as features and looks like it was just released. Complies with policy better, too? I'll install it and report back.

Screenshot of doom;
![image](https://user-images.githubusercontent.com/54357300/178138814-b652d6e6-cd8a-4592-8004-e0dc2b43053c.png)

(Am I allowed to post the extension file if I saved a copy? Not sure why it got taken down, or what format it is in, but it seems to have gone down in the last 48 hours.)

**Comment by 89z** [comment]
I don't see how this has anything to do with YouTube-DL

**Comment by dirkf** [comment]
In a FAQ answer we suggest using the extension to generate the cookies.txt file to be used with `--cookies`.

If we don't just change it to remove any specific recommendation other than using Firefox, I'd rather reference https://github.com/nyuszika7h/cookies.txt, belonging to a respected yt-dl/yt-dlp contributor, who might be prepared to add a release to the archive if the zipped code can't be installed as-is.

**Comment by october262** [comment]
fyi, get cookies.txt is back in the chrome extension store.

**Comment by dirkf** [comment]
The fickle wind of Google ...
