### ISSUE TITLE
Problem with Arabic script title in youtube-dl and downloading subtitle

### ISSUE THREAD

**Issue by MammadTavakoli** [ytdl-org/youtube-dl#31093]
I want download YouTube video that have Arabic title. I use `youtube-dl` package to download that sites; like:

    https://www.youtube.com/watch?v=pF5SdFWNhTc
My youtube-dl options is :

    ```python
        youtube_dl_options = {
                    "format": "(bestvideo+bestaudio/best)", 
                    "outtmpl":"%(autonumber)s_%(title)s.%(ext)s",  
                    "autonumber_start": playlist_start,
                    "playliststart": playlist_start,    
                    "restrictfilenames": False,
                    "nooverwrites": True,
                    "writedescription": True,
                    "writeinfojson": False,
                    "writeannotations": True,
                    "writethumbnail": False,
                    'writesubtitles': True,
                    'writeautomaticsub': True,
                    'subtitlesformat': "srt/ass/best"
                }
    ```

When I set `restrictfilenames` as `False` their is not any problem with saving videos with actually name, but when I set it `True` `youtub-dl` delete the Arabic scripts from title.
How can I save files with actual name and set `restrictfilenames` as `True`?

Also it only download `.vtt` format for English video subtitle that all the context is only in on line:
[![enter image description here][1]][1]

How can solve this problem?

  [1]: https://i.stack.imgur.com/Yuy8W.png

**Comment by dirkf** [comment]
To include non-ASCII characters in the filename, don't use `restrictfilenames`, which deliberately removes non-ASCII non-alphanumeric characters, except `-_`; actually, any sequence of such "insane" (according to the code) characters in an output field that isn't an ID becomes `_` and then any leading and trailing `_` are stripped, so your title with "ASCII _ Arabic - Arabic" becomes "ASCII_-".
```shellsession
$ python -m youtube_dl -v -o '%(autonumber)s_%(title)s.%(ext)s' --get-filename 'https://www.youtube.com/watch?v=pF5SdFWNhTc'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-o', u'%(autonumber)s_%(title)s.%(ext)s', u'--get-filename', u'https://www.youtube.com/watch?v=pF5SdFWNhTc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 1ff18694c
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
00001_Understanding Arrays _ هياكل البيانات - المصفوفات.webm
$ python -m youtube_dl -o '%(autonumber)s_%(title)s.%(ext)s' --restrict-filenames --get-filename 'https://www.youtube.com/watch?v=pF5SdFWNhTc'
00001_Understanding_Arrays_-.webm
$ 
```

What are you hoping to achieve with this option?

Regarding the subtitle issue, see #30710.

**Comment by 89z** [comment]
> To include non-ASCII characters in the filename, don't use `restrictfilenames`, which deliberately removes non-ASCII non-alphanumeric characters, except `-_`; 

Just to be clear, even with this turned off, YouTube-DL still strips other problematic characters (as it should):

<https://github.com/ytdl-org/youtube-dl/blob/cc179df346abf34c8f77dbb221b839092007f20c/youtube_dl/utils.py#L2086-L2101>
