### ISSUE TITLE
CLI option to DUMP [VideosPage/ChannelPage/Playlist] URL-Lists to text file using standalone/inclusive option

### ISSUE THREAD

**Issue by unityconstruct** [ytdl-org/youtube-dl#31096]
## Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've searched the bugtracker for similar feature requests including closed ones
Search the config page & CLI help for any clues feature might already exist.

### Feature Request:
- Would like to have a CLI option to DUMP these URLS to text file that can be used as standalone option or along with the other options.
- This is helpful for incremental 'fetches' to video/channel pages where there are 900+ videos.

### 'Problem'
- When scraping videos-page/channel, youtube-dl pulls ALL pages & apparently scrapes them to create a list of urls to download before iterating through them.
- For each URL, youtube-dl appears to pull the url, parse metadata, then run analysis on date-range & archive-file-check (previously downloaded?).
- The date-range assuredly helps in targeting content, but youtube-dl will still produce an obscene number of GET requests to the host.
- A URL dump would allow end-user to fetch the url-list with only a few GETS ( one per pagination ) and then manually adjust the url list.

### Use Case:
- I have a shell script that reads text file and iteratively calls youtube-dl to fetch single vid
- This allows me to aggregate videos when I see something interesting, then run a script to fetch them all at once.
- Having youtube-dl dump ALL urls of a videos-page/channel to text/console ( & before iterating them ), would all me to both archive the full URL address for later use ( such as referencing in social media posts or online articles ) and tailor the list to reduce traffic to the 'videos host'.
- Part of me winces when I see 900 GETS to YT as it just seems a little less then 'low key'. I can't help but think this type of traffic makes youtube-dl a target, where mechanisms start showing up to frustrate this type of scraper engine.
- Seems this type of traffic would also flag VPN IPs much faster than otherwise might occur.

### Syntax: dump urls AND PROCESS
--dump-urls "PATH"
--dump-urls "/media/media3/ytu/archive-urls.txt"
Scrape URLS, then dump to text file & continue processing

### Syntax: dump urls ONLY AND DO NOT PROCESS
--dump-urls-only "PATH"
--dump-urls-only "/media/media3/ytu/archive-urls.txt"
Scrape URLS, then dump to text file & exit

### CLI Session

NOT using BATCHFILE, using https://www.youtube.com/c/xxxxxxxx/videos
COMMAND STRING: /media/media3/ytu/youtube-dl -v --console-title --verbose -f best[height<=?1080]/bestvideo[height<=?1080]+bestaudio --merge-output-format mp4  --write-thumbnail --write-description --write-info-json --ignore-errors --max-downloads 50 --no-overwrites --restrict-filenames --download-archive /media/media3/ytu/archive-video.txt --no-playlist  --output /home/uc/Videos/ytu/%(uploader)s/%(title)s-%(id)s.%(ext)s --dateafter 20200101 https://www.youtube.com/c/xxxxxxxx/videos
Timestamp: 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--console-title', u'--verbose', u'-f', u'best[height<=?1080]/bestvideo[height<=?1080]+bestaudio', u'--merge-output-format', u'mp4', u'--write-thumbnail', u'--write-description', u'--write-info-json', u'--ignore-errors', u'--max-downloads', u'50', u'--no-overwrites', u'--restrict-filenames', u'--download-archive', u'/media/media3/ytu/archive-video.txt', u'--no-playlist', u'--output', u'/home/uc/Videos/ytu/%(uploader)s/%(title)s-%(id)s.%(ext)s', u'--dateafter', u'20200101', u'https://www.youtube.com/c/xxxxxxxx/videos']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-20-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11
[debug] Proxy map: {}
[youtube:tab] DavidVose: Downloading webpage
[download] Downloading playlist: xxxxxxxx - Videos
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] Downloading page 3
[youtube:tab] Downloading page 4
[youtube:tab] Downloading page 5
[youtube:tab] Downloading page 6
[youtube:tab] Downloading page 7
[youtube:tab] Downloading page 8
[youtube:tab] Downloading page 9
[youtube:tab] Downloading page 10
[youtube:tab] Downloading page 11
[youtube:tab] Downloading page 12
[youtube:tab] Downloading page 13
[youtube:tab] Downloading page 14
[youtube:tab] Downloading page 15
[youtube:tab] Downloading page 16
[youtube:tab] Downloading page 17
[youtube:tab] Downloading page 18
[youtube:tab] Downloading page 19
[youtube:tab] Downloading page 20
[youtube:tab] Downloading page 21
[youtube:tab] Downloading page 22
[youtube:tab] Downloading page 23

< DUMP URLS HERE, BEFORE ITERATING THEM >

### Example of [wince-stimuli]
[download] Downloading video __818 of 938__
[youtube] YlKd4YysVMA: Downloading webpage
[youtube] Downloading just video YlKd4YysVMA because of --no-playlist
[youtube] YlKd4YysVMA: Downloading MPD manifest
[debug] [youtube] Decrypted nsig ugGYu0WVAK7v5c9d => cP9vgB1UX5u_Lg
[debug] [youtube] Decrypted nsig EPn10_rOqmaCOzKP => -iXaKXk1eQoNZg
[download] 2016-04-10 upload date is not in range 2020-01-01 - 9999-12-31
[download] Downloading video _819 of 938_
[youtube] 7XiarrY3CXM: Downloading webpage
[youtube] Downloading just video 7XiarrY3CXM because of --no-playlist
[youtube] 7XiarrY3CXM: Downloading MPD manifest
[debug] [youtube] Decrypted nsig uNGKQi_VOQPwTewK => nw2ROBiUJuA2aA
[debug] [youtube] Decrypted nsig h8YlvZffzSK2qL8x => B2Crz0RmxeGukA
[download] 2016-03-24 upload date is not in range 2020-01-01 - 9999-12-31
[download] Downloading video _820 of 938_

**Comment by dirkf** [comment]
The page/API data/whatever has to be parsed to get the available download URLs and pick the format(s) to match your selection.

For YT, the download links are volatile, so storing a list of them would be fairly useless.

Some optimisation could be possible:
* yt-dlp does an early check for download_archive, before running the extractor itself;
* some new option could be added to tell yt-dl that the download links aren't needed (as opposed to `--skip-download` which just means that the links shouldn't be downloaded now); each extractor that needed to respect the new setting would have to be modified.

If what you want is just a list of IDs (equivalent to URLs for YT according to yt-dl), you can list all the IDs from a channel (etc) using `--flat-playlist` but the metadata needed to filter URLs isn't available when that output is produced. A program like _jq_ makes it easy to pull the id field out of the JSON. The download_archive check isn't applied to the playlist output but possibly could be an option.

**Comment by unityconstruct** [comment]
@dirkf yeah... it just dawned on my that the pagination stuff is likely 'site specifc'... if I wasn't one of those 'anything but python' chumps.. I'd probaby could've checked the code already... 

... which I will do....

_...that said, I'm now thinking of a [commonly available 'public' method] that could be called with some sort of List<String> object - to be optionally called by extractors... ( of which I'd likely be inclined to implement in the yt extractor )_

feel free to sh*tcan this one ( from my perspective )... I 1/2way follow this conversation, but really ought to dig in the codebase to understand it fully - given I run it incessantly.... **and I mean incessantly....** 

thx 4 response brother!

**Comment by unityconstruct** [comment]
#you can list all the IDs from a channel (etc) using --flat-playlist

I'll check that out... script I'm using employs named arrays for storing [jobs] ( aka channel-page/videospage ), so I can just add a url key/value pair and if I follow the [--flat-playlist] thing, I can transform the [id list] outside the ytdl exec... I'll checkout that option

**Comment by pukkandan** [comment]
I am a bit lost in the requirement. Can you explain why --flat-playlist is insufficient for your usecase?
