### ISSUE TITLE
can't download subtitle with youtubedl

### ISSUE THREAD

**Issue by pammseyy** [ytdl-org/youtube-dl#31103]
I can't download subtitle with youtubedl.. This is the command I used:

youtube-dl --write-sub --sub-lang en  https://www.youtube.com/watch?v=8TkdrjFJNS4

When I ran the command this is what it said:

 unable to download video subtitles: 8TkdrjFJNS4: Failed to parse XML  (caused by ParseError(ExpatError('no element found: line 1, column 0',),)); please report this issue on https://yt-dl.org/bug .

Please help

**Comment by pammseyy** [comment]
What seems to be the problem from my end? :(

**Comment by maximmai** [comment]
what version is your youtube-dl? Perhaps update to the latest?

**Comment by pammseyy** [comment]
when I tried to update this comes up:

youtube-dl -U
ERROR: can't find the current version. Please try again later.

**Comment by pammseyy** [comment]
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--write-sub', u'--sub-lang', u'en', u'https://www.youtube.com/watch?v=XIY0bpApJyI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-101053-g0a7c648e2d-tessus, ffprobe N-101053-g0a7c648e2d-tessus
[debug] Proxy map: {}

**Comment by dirkf** [comment]
Use the nightly build (#30839).

Then s/t like this:
```console
$ python -m youtube_dl -v --write-sub --sub-lang en --skip-download 'https://www.youtube.com/watch?v=XIY0bpApJyI'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--write-sub', u'--sub-lang', u'en', u'--skip-download', u'https://www.youtube.com/watch?v=XIY0bpApJyI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 5e51cb0aa
[debug] Python 2.7.15 (CPython i686 32bit) - Linux-6.1.0-17-686-pae-i686-with-debian-12.4 - OpenSSL 1.1.1a  20 Nov 2018 - glibc 2.1.3
[debug] exe versions: ffmpeg 5.1.4-0, ffprobe 5.1.4-0
[debug] Proxy map: {}
[youtube] XIY0bpApJyI: Downloading webpage
[debug] [youtube] Decrypted nsig s0cG1p3MxS9asi-Kt-i => 45wlvnM0FaIPzQ
[debug] [youtube] Decrypted nsig e1ctcNYVlf93mTJX9EU => ASWRB3Mm3BsDAQ
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: The cast spill their real feelings about the show _ Nineteen to Twenty Reunion Special [ENG]-XIY0bpApJyI.en.vtt
$
```
