### ISSUE TITLE
several process for command ( address parsing)

### ISSUE THREAD

**Issue by Lagunaxx** [ytdl-org/youtube-dl#31106]
when entering line with list like 
`youtube-dl https://www.youtube.com/watch?v=CVa5omE9hYM&list=RDMMCVa5omE9hYM&index=2`
then it creates several processes (somehow it determine some simbols as seperating) that runs in background and all of them try to download one source in same time.

**Comment by 89z** [comment]
you need quote escape the `&`, or quote the argument:

~~~
 youtube-dl 'https://www.youtube.com/watch?v=CVa5omE9hYM&list=RDMMCVa5omE9hYM&index=2'
~~~

**Comment by rautamiekka** [comment]
**_Always_** quote a web address, or a filesystem path !

**Comment by dirkf** [comment]
See [FAQ](https://github.com/ytdl-org/youtube-dl#user-content-video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).
