### ISSUE TITLE
youtube-dl couldn't find version of 'python3'

### ISSUE THREAD

**Issue by capeguy63** [ytdl-org/youtube-dl#31112]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
npm install -g freyr
npm ERR! code 1
npm ERR! path C:\Users\\AppData\Roaming\npm\node_modules\freyr\node_modules\youtube-dl-exec
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c C:\Users\\AppData\Local\Temp\preinstall-30357edf.cmd
npm ERR! Error: Couldn't find version of `python3`
npm ERR!     at binaryVersion (file:///C:/Users//AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version/index.js:55:8)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async binaryVersionCheck (file:///C:/Users//AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:14:18)
```

## Description

youtube-dl cannot find the version of python3. I am using v3.10.5 of python. Not sure if this is because it is looking for "python3" while my python is in "python".

**Comment by codementor726** [comment]
I also can see same bug
