### ISSUE TITLE
[strategy] lts ytdlp for older ytdlp and split youtube-dl versions

### ISSUE THREAD

**Issue by pirate486743186** [ytdl-org/youtube-dl#31117]
Maybe your strategy is flawed?

The current yt-dlp release will be the last supporting python 3.6, that may indicate a different approach. Instead of trying to backport everything to youtube-dl, you could collaborate with yt-dlp by maintaining lts yt-dlp versions. The current version of yt-dlp could become the first lts version.

That version will be far easier to backport stuff to, and you'll get far more help from interested devs. Once something is backported there, you can more easily backport it here.

Actually, you could just abandon the whole idea of supporting multiple versions of python in a single executable. It always seamed to me too masochistic of an approach. You could split youtube-dl in versions that support a certain python version. Backporting versions step by step. You could go dig an older yt-dlp and make that an lts version between youtube-dl and yt-dlp 3.6

So the quality will progressively worsen the older the lts, instead of an abrupt cut off.

You could also just merge youtube-dl with yt-dlp, by becoming the very long term lts versions. Maybe renaming everything to youtube-dl and having a single site, github account and other stuff(maybe even, choosing a better name) . So we have a single project again but with trailing lts versions.

**Comment by 89z** [comment]
This is not YT-DLP repo.

**Comment by pirate486743186** [comment]
read what i'm saying.

**Comment by 89z** [comment]
I was pretty sure this had been discussed before, and indeed it has. Searching the issues, it seems the one I linked has been given several times. In that issue, the current maintainer seems to make it pretty clear that they aren't interested in killing YouTube-DL, or even merging it with YT-DLP.

So I would do yourself a favor and just drop it. However if you insist on wasting your time, you could make a comment on that thread in support of your position.

**Comment by dirkf** [comment]
> ... current maintainer seems to make it pretty clear that they aren't interested in killing YouTube-DL, or even merging it with YT-DLP

and vice versa. Thanks for your suggestion, but it's not the way things will go for now.
