### ISSUE TITLE
https://filemoon.sx/

### ISSUE THREAD

**Issue by Testacda** [ytdl-org/youtube-dl#31126]
## Checklist

- [ ✅] I'm reporting a new site support request
- [ ✅] I've verified that I'm running youtube-dl version **2021.12.17**
- [✅ ] I've checked that all provided URLs are alive and playable in a browser
- [ ✅] I've checked that none of provided URLs violate any copyrights
- [ ✅] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://filemoon.sx/d/dzaq6p8yrvmm/Rick_Astley_-_Never_Gonna_Give_You_Up__Official_Music_Video___dQw4w9WgXcQ_.webm

## Description

Doesn't need an account I believe.

**Comment by dirkf** [comment]
Example gone.

**Comment by Testacda** [comment]
> Example gone.

updated link in original post
