### ISSUE TITLE
cannot download videos from teachable

### ISSUE THREAD

**Issue by brking** [ytdl-org/youtube-dl#31133]
Removed original content... fellow not helpful, feels all worthy,

**Comment by 89z** [comment]
please provide example URL

**Comment by brking** [comment]
https://learn.cantrill.io/courses/enrolled/730712

**Comment by 89z** [comment]
For me, I only see preview videos. Is that what you are talking about?

If not, then are you able to share an account for testing?

**Comment by brking** [comment]
I am trying to download the videos at that site using youtube0-dl following instructions that had been provided, but I am not able to... so I am seeking advice on how to go about it
This is the command I am running

youtube-dl --cookies cookies.txt -o \
"./%(chapter_number)s-%(chapter)s/%(autonumber)03d-%(title)s.%(ext)s" \
https://learn.cantrill.io/courses/enrolled/730712

**Comment by brking** [comment]
The instructions are found here

https://www.rockyourcode.com/how-to-download-courses-from-teachable/

**Comment by 89z** [comment]
Yes, I am happy to help you, but I cannot afford to pay for whatever this website cost. So if you have an account to share, then I should be able to fix the problem. Otherwise good luck to you.

**Comment by brking** [comment]
So, I have downloaded the get cookies file and that is the name you see there as cookies.txt

**Comment by 89z** [comment]
sorry, it seems you don't understand what I am asking. I am choosing to not comment further. If you get a stronger grasp of the communications here, then we can continue. Otherwise good luck.

**Comment by brking** [comment]
The site says once the cookies is downloaded, then there is no need for the password.  When I run the code, I get the error I mentioned and it says I report the issue to this site.

So just to confirm, you are not able to assist without me giving you my log in details?

If so, then fine...

And there is no need being rude.  Sorry for disturbing you, but definitely, I cannot give you the log in details, especially after this interaction

I don't need luck.  I will get a way without your tool.  I just thought you would be more helpful, 


Good luck

**Comment by 89z** [comment]
The website you linked:

https://learn.cantrill.io/p/aws-certified-solutions-architect-associate-saa-c02

Cost 40 USD. So by refusing to share credentials, you are limiting the people that can help you to:

- people that are willing to spend 40 USD, just for the sole purpose of helping you
- people that have already purchased from `cantrill.io`

If you wish to limit yourself in this way, of course its your choice to do so. However I would advise against it, as your issue could spend months or years without getting an answer. If you still wish to do that, good luck to you.

**Comment by dirkf** [comment]
Looking at https://learn.cantrill.io/courses/aws-certified-solutions-architect-associate-saa-c02/lectures/13876041, this site suffers the same problem as in #30929.
