### ISSUE TITLE
HTTP 500 Error on BBC

### ISSUE THREAD

**Issue by ygathgoch** [ytdl-org/youtube-dl#31139]
Here is the verbose results on this web address https://www.bbc.co.uk/iplayer/episode/b0658f2s/new-tricks-series-12-1-last-man-standing-part-one
```
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```
Using most recent version in Ubtuntu 2021.12.17.

Thanks.

**Comment by dirkf** [comment]
The full log, please, not just the traceback!

**Comment by ygathgoch** [comment]
Has resolved itself.  Went back to the webpage to the play the video, and had to answer some questions before it would play.  Ran the -F command and all the data downloaded as previously.

**Comment by dirkf** [comment]
If you can be more specific, that would be helpful in case other have the same problem. Eg, your location, what questions, command-line arguments. 500 error could be thrown by some web censorship device or by the BBC's CDN partners if they decide your web face doesn't fit.

**Comment by ygathgoch** [comment]
First question was around TV licensing, second about setting up parental controls. I think these answers get stored against the user account, and have to be refreshed periodically.
Have only been using this account on this device for a few weeks, so hadn't been asked them previously.

**Comment by dirkf** [comment]
I don't think that can be related. yt-dl's BBC extractor operates on the layer that you reach after answering the licensing, etc, questions, whose answers are just stored in the iPlayer host's cookie jar. yt-dl won't send those cookies, even if it's actually run on the same machine.
