### ISSUE TITLE
Print Parent URL for searching

### ISSUE THREAD

**Issue by kungfubeaner** [ytdl-org/youtube-dl#31132]
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Please add an option to print out full parent URL similar to the --get-id option.  Useful for search scripts without having to use awk as a middle man.  (or parse with jq for that matter) Example:

youtube-dl --get-id --default-search ytsearch "Big Buck Bunny" |  awk '{ print "https://www.youtube.com/watch?v=" $0 }' | mpv --playlist=-

If we had an option like  --get-parent-url  we could skip having to use awk or other text manipulation program like sed etc.

**Comment by dirkf** [comment]
Use _mpv_'s `ytdl:` syntax with `--get-filename` (until yt-dl gets a `--print` option):
```
youtube-dl --get-filename -o 'ytdl:%(id)s' --default-search ytsearch "Big Buck Bunny" | mpv --playlist=-
```

**Comment by kungfubeaner** [comment]
Oh cool thanks a lot for that tip =)

**Comment by kungfubeaner** [comment]
In case you're interested.   I settled on a final solution and added this to my .bashrc
turns out using awk to generate an M3U playlist and jq to parse was the better option after all.
1 result by default and more if specified when called.  xdo is used to hide terminal while mpv runs.

ytmpv() { id=$(xdo id); xdo hide; mpv <(youtube-dl -j --flat-playlist --default-search ytsearch$2 "$1" | jq '{ title, webpage_url }' | awk -F\" 'BEGIN { print "[#EXTM3U](https://www.youtube.com/hashtag/extm3u)\n" } / +"title":/ { print "[#EXTINF](https://www.youtube.com/hashtag/extinf):," $4; getline; print $4 "\n" }'); xdo show "$id"; }

**Comment by filpman** [comment]
Why am I get these emails?

**Comment by kungfubeaner** [comment]
--print option solves evertying aka -O  dunno how i missed that.

**Comment by dirkf** [comment]
But only available in yt-dlp for now.

**Comment by kungfubeaner** [comment]
I'm sorry I'm out of it meant the output templates I'm just working on too many things at once but your tip solved everything

**Comment by dirkf** [comment]
In this case the `-o ...` hack is OK as a substitute.

If you use _jq_, you can avoid using _awk_ as well:
```
ytmpv() { youtube-dl -j --flat-playlist --default-search ytsearch$2 "$1" | { printf "#EXTM3U <https://www.youtube.com/hashtag/extm3u>\n"; jq -r '@text "#EXTINF <https://www.youtube.com/hashtag/extinf>:,\(.title)\nhttps://www.youtube.com/watch?=\(.url)\n"'; } }
```

**Comment by kungfubeaner** [comment]
oh cool. I had settled on solution using jq and awk but with this info I
can make some improvements
I added this function to my bash rc file but will use this new info to see
if I can get rid of using aw and just use jq.

ytmpv() { id=$(xdo id); xdo hide; mpv <(youtube-dl -j --flat-playlist
--default-search ytsearch$2 "$1" | jq '{ title, webpage_url }' | awk -F\"
'BEGIN { print "#EXTM3U\n" } / +"title":/ { print "#EXTINF:," $4; getline;
print $4 "\n" }'); xdo show "$id"; }
