### ISSUE TITLE
zoom.py desktop to mobile user agent  changing

### ISSUE THREAD

**Issue by ananth-28** [ytdl-org/youtube-dl#31130]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
in zoom youtube-dl uses desktop mode user-agent but when mobile user agent are used on zoom both Screen share stream and Camera stream are show as one video but in desktop user agent (used by youtube-dl) it shows them differently and i need both as one video
so i edited zoom.py but it didnt work out insted gave error

 _ERROR: [zoom] 8dbJxGJHAhQhoVMV73pGFTAcRFCxbjOgt_rLbdhb4PH9VUO1feUEtoL91o-9QyOW.MyezmvHOIciMpBso: Unable to extract data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U_ 

my edited code below
![image](https://user-images.githubusercontent.com/106482929/182447240-e1acc655-1425-4861-af8e-0c81503cf694.png)
then i reslised that some thing needs to be changed here also (ref below image)
![image](https://user-images.githubusercontent.com/106482929/182447426-73629f7f-ca2d-4ab3-91a7-09dcf67b2955.png)
i need help regarding it
i dont know what should come in place of 'shareMp4Url' here if we are using mobile user agent
        if data.get('shareMp4Url')

Thank you

**Comment by 89z** [comment]
https://urbandictionary.com/define.php?term=Dextop

**Comment by dirkf** [comment]
> ... please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= ...
