### ISSUE TITLE
python related issue

### ISSUE THREAD

**Issue by Fl3xX** [ytdl-org/youtube-dl#31135]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -v https://www.youtube.com/watch?v=O5B_nYulA7E
python3: can't open file '/path/to/youtube-dl': [Errno 2] No such file or directory

```

## Description

I tried all the solution in the #31107 post since it looked very similar to my problem. But i get the same error every time.

OS : Linux Mint 21 Cinnamon
Python : 3.10.4

Edit : I install python-is-python3 and did [this](https://askubuntu.com/questions/1242139/youtube-dl-usr-bin-env-python-no-such-file-or-directory/1242145#1242145). It seems that the problem is solved..!

**Comment by dirkf** [comment]
> Edit : I install python-is-python3 and did this ...

Which "this" from the linked SO page? Installing the package should have been enough.
