### ISSUE TITLE
Url Have Ssl verification issues

### ISSUE THREAD

**Issue by niranjantechofficial** [ytdl-org/youtube-dl#31148]
![Screenshot_2022-08-08-14-06-58-428_org telegram messenger](https://user-images.githubusercontent.com/61946705/183376899-6c0a3c44-a570-48b0-a83e-c351de579e92.jpg)

## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I am creating bot for tg... But the issue was show like this say what to do

**Comment by dirkf** [comment]
This is an issue with the certificate configuration on the server that is running yt-dl. If you can force it to use the `--no-check-certificate` option, the error will be bypassed, but of course you won't know that the remote host is the one it claims to be.

**Comment by niranjantechofficial** [comment]
Can you say how to do... And Where to do

**Comment by dirkf** [comment]
Wherever you specify the command line options for yt-dl. Beyond that is a matter for you. Or, update the certificate configuration on the server that runs yt-dl in your bot: generally this means updating the _openssl_ package on the server and any certificate package that it uses. My laptop had no problem making HTTPS connections to videos.classplusapp.com.

**Comment by niranjantechofficial** [comment]
https://github.com/CyniteOfficial/Uploader-Bot

This source i used for making bot using heroku.... 

I am struggling from many days i can't fix it... Please check once that source and say it need to add source or on GitHub

**Comment by dirkf** [comment]
According to https://github.com/CyniteOfficial/Uploader-Bot/blob/V2.0/plugins/youtube_dl_button.py, that source is using yt-dlp, not yt-dl. Anyhow, raise your issue at https://github.com/CyniteOfficial/Uploader-Bot/issues or with whoever is providing the server for your bot. You could try the yt-dlp issue tracker but most likely you'll get this answer again.
