### ISSUE TITLE
How to download subtitles from arte.tv?

### ISSUE THREAD

**Issue by DDBE12** [ytdl-org/youtube-dl#31140]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm trying to download subtitles from arte.tv. I've used --list-subs to identify the subtitle files available. In the log, it keeps claiming to be writing a vtt file, but afterwards, I can't find a vtt anywhere on my HDD, while I can locate the video files that it's downloaded just fine. How to solve this problem?

I've read the FAQ, the readme, and all prior issues about subtitles. Nobody else seems to be having this problem. Even in this thread: https://github.com/ytdl-org/youtube-dl/issues/30816 , it's only about youtube-dl not finding any subtitles at the specified URL at all, which is not the problem I have.

Also, I seem to be entirely incapable of making youtube-dl find ffmpeg in cmd. In the GUI, I can simply point it to the right path, but in cmd, it just keeps claiming that ffmpeg wouldn't be installed on my system.

## Verbose log

`$ python -m yt_dlp --downloader ffmpeg --hls-use-mpegts --write-subs --sub-lang de https://arte-cmafhls.akamaized.net/am/cmaf/095000/095100/095125-000-A/220214181609/095125-000-A_VO-STA_XQ.m3u8
>[generic] 095125-000-A_VO-STA_XQ: Downloading webpage
>[generic] 095125-000-A_VO-STA_XQ: Downloading m3u8 information
>[info] 095125-000-A_VO-STA_XQ: Downloading 1 format(s): 2325+program_audio_0-VO
>Deleting existing file 095125-000-A_VO-STA_XQ [095125-000-A_VO-STA_XQ].de.vtt
>[info] Writing video subtitles to: 095125-000-A_VO-STA_XQ [095125-000-A_VO-STA_XQ].de.vtt
>[hlsnative] Downloading m3u8 manifest
>[hlsnative] Total fragments: 1
>[download] Destination: 095125-000-A_VO-STA_XQ [095125-000-A_VO-STA_XQ].de.vtt
>[download] 100% of 28.03KiB in 00:00
>WARNING: You have requested merging of multiple formats but ffmpeg is not installed. The formats won't be merged
>[download] 095125-000-A_VO-STA_XQ [095125-000-A_VO-STA_XQ].f2325.mp4 has already been downloaded
>[download] 100% of 1023.35MiB
>[download] 095125-000-A_VO-STA_XQ [095125-000-A_VO-STA_XQ].fprogram_audio_0-VO.mp4 has already been >downloaded
>[download] 100% of 60.85MiB`

**Comment by DDBE12** [comment]
Okay, I've finally found the vtt file. For some weird reason, it was automatically set to invisible.

**Comment by dirkf** [comment]
This should work automatically from the Arte URL (no need to find the m3u8 manually) once the new yt-dlp version is back-ported, together with improvements to the underlying m3u8 processing.
