### ISSUE TITLE
HTTP error code as exit code

### ISSUE THREAD

**Issue by light-and-ray** [ytdl-org/youtube-dl#31167]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

It would be nice if youtube-dl returned an HTTP error code as an exit code. I want to handle HTTP 403 error in my bash script, but error code is 1 in this case

You can add it by flag (e.g. `--http-exit-code`) if you think it would broke any logic

**Comment by 89z** [comment]
this is a bad idea, for what should be obvious reasons. A typical "good" value is 200:

https://developer.mozilla.org/docs/Web/HTTP/Status/200

but using your suggestion, even a response like this would fail your script.

**Comment by dirkf** [comment]
Probably the best solution is to make [an embedded `YoutubeDL` application where you can inspect errors in a custom logger](https://github.com/ytdl-org/youtube-dl#user-content-embedding-youtube-dl).

You could also catch and inspect the `stderr` output in your shell script.

Generally, there's a whole lot of error handling code in yt-dl. It would be a big project to review it all and re-design error-reporting and return-codes, on the level of never-gonna-happen. But see also https://github.com/yt-dlp/yt-dlp/issues/457.

**Comment by light-and-ray** [comment]
I just want to restart youtube-dl on HTTP 403 error. It is a strange error
which becames randomly, and fixes by restarting

вс, 14 авг. 2022 г., 21:43 dirkf ***@***.***>:

**Comment by dirkf** [comment]
Yes, understood. I've suggested how you might trap such an error.

403 means access denied ("I'm sorry, my man, but your credentials ain't no good"). It might occur unexpectedly if you are using cookies for authentication and the auth cookie expires while downloading a playlist.

If it's happening on one particular site, you might do better to raise an issue for that site, with the required log, etc.

**Comment by light-and-ray** [comment]
> It might occur unexpectedly if you are using cookies for authentication
> while downloading a playlist.

No, I'm not. It often happens when download along single video from youtube, e.g. stream

**Comment by light-and-ray** [comment]
Not logined

**Comment by dirkf** [comment]
Probably your internet connection is being compromised by a state actor, such as your government, although 403 wouldn't normally be associated with that. But then **normally** governments don't invade neighbouring friendly countries whose security they guaranteed, so who can say. 

In any case, if so, it's no real help to you, though you could try other network connections, VPN, etc. A poor "antivirus" or network security package might also be at fault, and easier to change.

**Comment by light-and-ray** [comment]
I wrote this script, which fixes it

`youtube-dl:`
```bash
#!/bin/bash

ERROR="HTTP Error 403"
RED="\e[31m"
GREEN="\e[32m"
ENDCOLOR="\e[0m"
g_ret=0


download()
{
    out=$(youtube-dl_ "$@" |& tee /dev/tty | tail -n 5)
    g_ret=${PIPESTATUS[0]}

    if echo "$out" | grep -q "$ERROR"
    then
        return 1
    fi

    return 0
}


while ! download "$@"
do
    echo -e "${RED}$ERROR${ENDCOLOR}"
done

exit $g_ret
```

`youtube-dl_` - is the renamed original `youtube-dl`

**Comment by dirkf** [comment]
So this, then
>You could also catch and inspect the stderr output in your shell script.

Glad you're sorted.

**Comment by light-and-ray** [comment]
Yes, I posted my temporary solution for any pilgrims with the same problem )
