### ISSUE TITLE
[YouTube] TypeError: '>' not supported between instances of 'int' and 'NoneType' 

### ISSUE THREAD

**Issue by mk-pmb** [ytdl-org/youtube-dl#31173]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: […]
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: e52e8b811
[debug] Python version 3.8.10 (CPython) - Linux-5.8.0-44-lowlatency-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {…}
[youtube] t-hR-TZJT2U: Downloading webpage
[youtube] t-hR-TZJT2U: Downloading MPD manifest
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Failed to evaluate 0 > None (caused by TypeError("'>' not supported between instances of 'int' and 'NoneType'")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/mnt/…/youtube_dl/jsinterp.py", line 203, in _operator
    return opfunc(left_val, right_val)
TypeError: '>' not supported between instances of 'int' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
…
  File "/mnt/…/youtube_dl/jsinterp.py", line 590, in interpret_expression
    ret, should_return = self.interpret_statement(expr, local_vars, allow_recursion)
  File "/mnt/…/youtube_dl/jsinterp.py", line 454, in interpret_statement
    return self._operator(op, 0 if left_val is None else left_val,
  File "/mnt/…/youtube_dl/jsinterp.py", line 205, in _operator
    raise self.Exception('Failed to evaluate {left_val!r} {op} {right_val!r}'.format(**locals()), expr, cause=e)
youtube_dl.jsinterp.JSInterpreter.Exception: Failed to evaluate 0 > None (caused by TypeError("'>' not supported between instances of 'int' and 'NoneType'")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
```

## Description
Download seems to work nonetheless.

**Comment by dirkf** [comment]
Apparently you just need to reinstall Python 2.7!

Python 3.5 has this message:
```
...
  File "/home/df/Documents/src/youtube-dl/youtube_dl/jsinterp.py", line 205, in _operator
    raise self.Exception('Failed to evaluate {left_val!r} {op} {right_val!r}'.format(**locals()), expr, cause=e)
youtube_dl.jsinterp.JSInterpreter.Exception: Failed to evaluate 0 > None (caused by TypeError('unorderable types: int() > NoneType()',));  ...
```
However today's dev version fixes whatever problem there was:
```shellsession
$ python3.9 -m youtube_dl -F -v 'https://www.youtube.com/watch?v=t-hR-TZJT2U'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://www.youtube.com/watch?v=t-hR-TZJT2U']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: e52e8b811
[debug] Python version 3.9.13 (CPython) - Linux-4.4.0-210-generic-i686-with-glibc2.23
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] t-hR-TZJT2U: Downloading webpage
[youtube] t-hR-TZJT2U: Downloading MPD manifest
[debug] [youtube] Decrypted nsig BnLAR5umBf9R48MhQ => y5mzqXT4vmPGow
[debug] [youtube] Decrypted nsig oxC0xXr4o8rSUj1L9 => mfQBGpVcJ9-_fQ
[info] Available formats for t-hR-TZJT2U:
format code  extension  resolution note
139          m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.5 (22050Hz), 513.68KiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 1.33MiB
251          webm       audio only tiny  141k , webm_dash container, opus @141k (48000Hz), 1.45MiB
278          webm       256x144    DASH video   95k , webm_dash container, vp9, 30fps, video only
160          mp4        256x144    DASH video  108k , mp4_dash container, avc1.4d400b, 30fps, video only
242          webm       426x240    DASH video  220k , webm_dash container, vp9, 30fps, video only
133          mp4        426x240    DASH video  242k , mp4_dash container, avc1.4d400c, 30fps, video only
134          mp4        640x360    360p  315k , mp4_dash container, avc1.4d401e@ 315k, 30fps, video only, 3.23MiB
243          webm       640x360    DASH video  405k , webm_dash container, vp9, 30fps, video only
244          webm       854x480    DASH video  752k , webm_dash container, vp9, 30fps, video only
135          mp4        854x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 30fps, video only
136          mp4        1280x720   720p 1092k , mp4_dash container, avc1.64001f@1092k, 30fps, video only, 11.20MiB
247          webm       1280x720   DASH video 1505k , webm_dash container, vp9, 30fps, video only
302          webm       1280x720   DASH video 2646k , webm_dash container, vp9, 60fps, video only
298          mp4        1280x720   DASH video 3465k , mp4_dash container, avc1.4d400d, 60fps, video only
299          mp4        1920x1080  1080p60 3021k , mp4_dash container, avc1.64002a@3021k, 60fps, video only, 30.98MiB
303          webm       1920x1080  DASH video 4410k , webm_dash container, vp9, 60fps, video only
18           mp4        640x360    360p  443k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz)
22           mp4        1280x720   720p 1220k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
$
``` 
Coming in  this version:
* operator `??`
* operator `?.`
* operator `**`
* accurate operator functions ([Douglas Crockford special](https://devclass.com/2022/08/04/retire_javascript_says-json-creator-douglas-crockford/): `undefined ** 0 === 1`)
* `undefined` handling
* object literals `{a: 1, "b": expr}`

**Comment by dirkf** [comment]
The problem is with this line 264 of the pretty-printed nsig code:
```
      6 >= c[104] ? (0, c[22]) ((0, c[1]) ((0, c[5]) (c[13], c[44]), c[76], c[12], c[75]), c[2], (0, c[0]) (((0, c[82]) (c[12]), (0, c[98]) (c[72], c[12])), c[106], (0, c[31]) (c[63], c[35]) > (0, c[102]) (c[ - 120 * Math.pow(7, 2) + 5969], c[82]), c[12], c[10]), c[29], c[21])  : (0, c[81]) ((0, c[40]) (c[10], c[11], (0, c[20]) ()), c[53], (0, c[new Date('31 December 1969 13:15:53 -1045') / 1000]) ((0, c[53]) ((0, c[12]) (c[26]), c[35], c[10], c[275 % Math.pow(new Date('1969-12-31T17:00:02.000-07:00') / 1000, 5) + 9]), c[40], c[67], c[74], (0, c[21]) ()), (0, c[53]) ((0, c[35]) (c[42], c[104]), c[35], c[67], c[48]), (0, c[86]) (c[Math.pow(5, 5) + 17176 + - 20291], c[51]), c[49], c[64], c[42]),
```
yt-dl is trying to evaluate this part of the line, and the RHS of the '>' is evaluating to `None`: 
```
(0,c[0])(((0,c[82])(c[12]),(0,c[98])(c[72],c[12])),c[106],(0,c[31])(c[63],c[35])>(0,c[102])(c[-120*Math.pow(7,2)+5969],c[82]),c[12],c[10])
```
Here `c[102]` is a number, so something went wrong way back.

**Comment by mk-pmb** [comment]
> Apparently you just need to reinstall Python 2.7!

I tried it, but the error persists. Maybe Ubuntu mirrors didn't get the update yet.

**Comment by dirkf** [comment]
Sorry, that wasn't a serious suggestion. You'd have to go through more hoops to get Python 2.7 running your yt-dl, anyway.

Please wait for the new version.

**Comment by mk-pmb** [comment]
> You'd have to go through more hoops to get Python 2.7 running your yt-dl, anyway.

Indeed, I had to edit the shebang line of my wrapper script. I didn't remember I had upgraded it to use python3 yet. Now the warning seems gone and download speed seems to be back to normal. So thanks for reminding me of that extra step!

**Comment by zensubz** [comment]
As such there is no issue with Python 2.7, it works without throwing any errors.

This 'TypeError...' stuff occurs in my Linux OS with Python 3.6, and it could be mitigated with this patch:
```
--- a/youtube_dl/jsinterp.py
+++ b/youtube_dl/jsinterp.py
@@ -200,7 +200,7 @@
             return right_val
 
         try:
-            return opfunc(left_val, right_val)
+            return opfunc(left_val, 0 if right_val is None else right_val)
         except Exception as e:
             raise self.Exception('Failed to evaluate {left_val!r} {op} {right_val!r}'.format(**locals()), expr, cause=e)
 ```
Courtesy: Tip from https://stackoverflow.com/a/3930320]

**Comment by dirkf** [comment]
The key message from SO:
>If it's your code, figure out how you're getting None when you expect a number and stop that from happening.
>
>If it's someone else's code, find out the conditions under which it gives None and determine a sensible value to use for that, ...

JS is happy to compare `null` against numeric values, so Python's `x < 0` is not the same as JS's. Mapping JS `null` to `None` and `<` to `<` (aka `operator.lt`) naively causes this runtime error if the interpreter is given such an expression.

Here are some JS comparisons with their results:
```js
[null > 0, null < 0, null == 0, null === 0]
/*
false,false,false,false
*/

[undefined > 0, undefined < 0, undefined == 0, undefined === 0]
/*
false,false,false,false
*/

[undefined > null, undefined < null, undefined == null, undefined === null]
/*
false,false,true,false
*/

/* BEST OF ALL */
[null >= 0, null <= 0]
/*
true,true
*/
```
 So `null` is not 0, nor less than 0 nor greater than 0, yet it's greater than or equal to 0 *and* less than or equal to 0: perhaps not the best part of [Brendan Eich's busy week in 1995](https://zenodo.org/record/3707008).

_Luckily_ the same devil-may-care attitude to consistency is maintained even today, as evidenced by the recent addition of a `**` operator with `undefined ** 0 == 1`: how could it not be `undefined`? (The answer is that the much older `Math.pow(x, 0)` does this too, when `x` is undefined and in fact for any `x`.)

Anyhow, these things are all working in the weird way JS expects in PR #31175.

**Comment by dirkf** [comment]
>... [Python 2.7] download speed seems to be back to normal.

Good to know, though the descrambling code sent by YT is so tightly self-referential that it's difficult to imagine the interpreter producing a wrong answer rather than crashing.

**Comment by zensubz** [comment]
@dirkf Thanks for your detailed explanation. Mine was just a dirty method from a layman-point-of-view to temporarily get rid of those error-msgs flooding the terminal...

I have picked-up your commits b80413b and 41631a3 from #31175, rebuilt youtube-dl (both py2.7 and py3.6 versions). No errors, and download speeds are quite good.

Thanks for your incredible work.

**Comment by dirkf** [comment]
@pukkandan does the incredible stuff: I just nick it!

**Comment by pukkandan** [comment]
This is what I meant that Youtube can make it much harder for us if the signature function starts to rely on JS's type coersion. Luckily it wasn't that bad this time. But if they double down on this, we will be forced to define equivalent classes for each JS object rather than approximating with Python builtins. Add some try-catch blocks to the mix, and only a proper intrpretter can handle all the edge cases

**Comment by dirkf** [comment]
Ofc, what comes to mind is the process by which this nonsense (here I mean n-sig rather than JS in general) is developed. Is there an obfuscated JS department in YT with a calendar reminder to turn out a new version every so often, or do they get each lot of interns/new grads to work up a set of challenges that can be rolled out randomly through the year, or ...?

**Comment by zensubz** [comment]
@dirkf, thanks for the commit b0a60ce.

@pukkandan and @dirkf, the amount of hard-work you people put-in to keep youtube-dl/yt-dlp alive is simply awesome..!

**Comment by mk-pmb** [comment]
In case someone is wondering why `(null != 0)` but `(null >= 0) && (null <= 0)`, it's because when `<=` or `>=` is evaluated on values with an unordered and an ordered type, the unordered type value is converted to the ordered type. `Number(null) === 0`

**Comment by dirkf** [comment]
As I said 
>... perhaps not the best part of Brendan Eich's busy week in 1995.

Maybe [this](https://www.biwascheme.org/) is what he was hoping for, no weird type coercion in Scheme:
```
BiwaScheme Interpreter version 0.7.5
biwascheme> (> 0 0)
=> #f
biwascheme> (> 0 '())
number required, but got () [>]
biwascheme>
```

**Comment by mk-pmb** [comment]
The workaround of downgrading Python to 2.7 no longer works:
* `Unsupported JS expression ' + (expr[:40] if expr != stmt else ''), expr=stmt)`
* `Unsupported JS expression in: u'throw d';`

While someone is at it, it might be useful to always include the player ID in the error messages about JS parsing.

**Comment by dirkf** [comment]
Hence PR #31182, though without
>... the player ID in the error messages about JS parsing
