### ISSUE TITLE
Not able to download some of the seasons from Pokemon website www.pokemon.com

### ISSUE THREAD

**Issue by jjayaraman** [ytdl-org/youtube-dl#31177]
## Checklist

- [ X] I'm reporting a broken site support
- [ X] I've verified that I'm running youtube-dl version **2021.12.17**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
  season18 youtube-dl --verbose 'https://www.pokemon.com/us/pokemon-episodes/09_01-fear-factor-phony/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.pokemon.com/us/pokemon-episodes/09_01-fear-factor-phony/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - macOS-12.5-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Pokemon] 09_01-fear-factor-phony: Downloading webpage
ERROR: Unable to extract video data element; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/pokemon.py", line 52, in _real_extract
    video_data = extract_attributes(self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video data element; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

Hello you have a wonderful tool that is really very useful
I am trying to download pokemon videos from https://www.pokemon.com/us/pokemon-episodes/pokemon-tv-seasons/
And I am able to successfully download all videos in season1, 2, 20, 21, 22
But I not able to download other seasons and get same errors for all other seasons
Please kindly help

**Comment by dirkf** [comment]
The page that yt-dl sees has no video element, so the extraction fails. Same result in yt-dlp.

> [X] I've checked that all provided URLs are alive and playable in a browser

Can you also provide an episode URL that works for comparison?
Login required?

Or depending on location some content may be licensed to other sites, eg in UK Pop! children's TV channel.

**Comment by jjayaraman** [comment]
> The page that yt-dl sees has no video element, so the extraction fails. Same result in yt-dlp.
> 
> > [X] I've checked that all provided URLs are alive and playable in a browser
> 
> Can you also provide an episode URL that works for comparison? Login required?
> 
> Or depending on location some content may be licensed to other sites, eg in UK Pop! children's TV channel.

Thanks,

This Season 8 URL works fine:  https://www.pokemon.com/us/pokemon-episodes/08_10-wheres-armaldo/

I am downloading  from the same UK location.
It allows to download for some season and not for others. 

Logs

season8 youtube-dl https://www.pokemon.com/us/pokemon-episodes/08_10-wheres-armaldo/
[Pokemon] 08_10-wheres-armaldo: Downloading webpage
[limelight] f14693ac8fa24e089a94826080dcdd77: Downloading PlaylistService getPlaylistByMediaId JSON
[limelight] f14693ac8fa24e089a94826080dcdd77: Downloading PlaylistService getMobilePlaylistByMediaId JSON
[limelight] f14693ac8fa24e089a94826080dcdd77: Checking http-1072 URL
[limelight] f14693ac8fa24e089a94826080dcdd77: Checking http URL
[limelight] f14693ac8fa24e089a94826080dcdd77: Checking http-1328 URL
[limelight] f14693ac8fa24e089a94826080dcdd77: Checking http-128 URL
[limelight] f14693ac8fa24e089a94826080dcdd77: Checking http-1600 URL
[limelight] f14693ac8fa24e089a94826080dcdd77: Checking http-832 URL
[limelight] f14693ac8fa24e089a94826080dcdd77: Checking http URL
[limelight] f14693ac8fa24e089a94826080dcdd77: Checking http-472 URL
[limelight] f14693ac8fa24e089a94826080dcdd77: Checking http-322 URL
[limelight] f14693ac8fa24e089a94826080dcdd77: Downloading m3u8 information
[limelight] f14693ac8fa24e089a94826080dcdd77: Downloading PlaylistService getClosedCaptionsDetailsByMediaId JSON
[download] Destination: Where's Armaldo-f14693ac8fa24e089a94826080dcdd77.mp4
[download] 100% of 264.18MiB in 01:04

**Comment by dirkf** [comment]
That confirms my original point. There is a video element in the working case, and it plays in the browser. In the failing case there's no video and in the browser I get a whirling icon that resolves to a static image.

>[X] I've checked that all provided URLs are alive and playable in a browser

Are you sure?

However, [this](https://www.pokeflix.tv/v/09-fear-factor-phony) seems to be the content you're after and appears to be handled by yt-dl's generic extractor.
