### ISSUE TITLE
Have SSL issue how to fix that? 

### ISSUE THREAD

**Issue by niranjantechofficial** [ytdl-org/youtube-dl#31171]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

![Screenshot_2022-08-10-00-34-20-153_org telegram messenger](https://user-images.githubusercontent.com/61946705/184652722-eee465dc-e74a-4f2e-acdd-f35e7818cd5d.jpg)

How to Fix this Issue can you help

**Comment by niranjantechofficial** [comment]
I tried but no one helped

**Comment by dirkf** [comment]
Why would you think that just zsking the same question with no further information will elicit a different answer? Duplicate of #31148.
