### ISSUE TITLE
HTTP Error 403 - Patreon

### ISSUE THREAD

**Issue by AlisonDesignit** [ytdl-org/youtube-dl#31180]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}

Trying to download a video from Patreon - have downloaded correct cookies file, and set up as 'youtube-dl --cookies [cookies.txt]  https://www.patreon.com/posts/[numbers]'. 

When running it I get this error:
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I don't think it's actually a bug and I'm not setting things up properly, so have included the bug checklist and -v also. I checked the FAQ and other issues but think I still must be missing something.

**Comment by 89z** [comment]
please provide example URL that has not been edited

**Comment by Safox1** [comment]
Please post the whole error. Also if you don't think that you have done everything correctly and this is just a JSON error then maybe make sure that your authentication is completed correctly with the Patreon API #28786 has a good example of how to do this if you haven't already done so yourself.

**Comment by dirkf** [comment]
If the site won't authenticate using your cookies it might be checking for some other browser characteristic(s). Try passing the User Agent of your browser too.

**Comment by 1337ever** [comment]
just wanted to add that i've been having the same issue

**Comment by coletdjnz** [comment]
https://github.com/yt-dlp/yt-dlp/pull/4398

**Comment by dirkf** [comment]
So: `--user-agent 'Patreon/7.6.28 (Android; Android 11; Scale/2.10)'`
