### ISSUE TITLE
NHK: any way to obtain the video id in filename instead of the Piksel code?

### ISSUE THREAD

**Issue by ke352802081770314** [ytdl-org/youtube-dl#31185]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I use the config option `-o ~/Downloads/%(title)s-%(extractor)s-%(id)s.%(ext)s`
for NHK videos it will use Piksel as extractor and some characters e.g. jvym0dqk as id. 
During download, I noticed that it first logs something like `[NhkVod] 2007-474: Downloading JSON metadata` and then switches to Piksel.

Is there way to obtain the NhkVod ID instead (e.g. 2007-474) because it contains the program/series number (2007) and the episode number (474) which makes it much easier to keep track of the episodes?

Many thanks.

**Comment by dirkf** [comment]
This value is split out of the original URL, eg:
https://www3.nhk.or.jp/nhkworld/en/ondemand/video/**2007474**/

Other than knowing that, currently the best you can do is the `webpage_url_basename` metadata item, which in your example would be `2007474`

We could pass the value as `display_id` with a small change:
```diff
--- old/youtube_dl/extractor/nhk.py
+++ new/youtube_dl/extractor/nhk.py
@@ -65,6 +65,7 @@
                 'ie_key': 'Piksel',
                 'url': 'https://player.piksel.com/v/refid/nhkworld/prefid/' + vod_id,
                 'id': vod_id,
+                'display_id': episode_id,
             })
         else:
             if fetch_episode:
```
Then you'd get the `display_id` metadata item as `2007-474`.

**Comment by ke352802081770314** [comment]
Many thanks for the quick response. webpage_url_basename works perfectly for me!

**Comment by dirkf** [comment]
Great!
