### ISSUE TITLE
After upgrade macOS Catalina (10.15.x) to Monterey(12.4)，the youtube-dl 2021.12.17 not work

### ISSUE THREAD

**Issue by isxylands** [ytdl-org/youtube-dl#31189]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
% /usr/local/bin/youtube-dl --version
env: python: No such file or directory

% python3 /usr/local/bin/youtube-dl --version
2021.12.17

% python3 /usr/local/bin/youtube-dl --proxy socks5://127.0.0.1:1081/ -f 'best[ext=mp4][height<=360]' -o '%(title)s_%(upload_date)s_%(resolution)s.%(ext)s' 'https://www.youtube.com/watch?v=ZggTCJJroyU'
[youtube] ZggTCJJroyU: Downloading webpage
WARNING: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
[youtube] ZggTCJJroyU: Downloading API JSON
ERROR: Unable to download API page: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))
```

## Description

Recently upgraded the operating system from macOS 10.15.x (ie Catalina) to 12.4 (ie Monterey), before the upgrade, youtube-dl has been working well (version 2021.12.17); but after the upgrade, it can't run……  After adding python3, it can be run, but it cannot be downloaded, and an SSL certificate error is reported. 
Help please, thanks.

**Comment by 89z** [comment]
works fine here:

~~~
> youtube-dl -f 'best[ext=mp4][height<=360]' -o '%(title)s_%(upload_date)s_%(resolution)s.%(ext)s' 'https://www.youtube.com/watch?v=ZggTCJJroyU'
[youtube] ZggTCJJroyU: Downloading webpage
[download] Destination: 不愧是天后，王菲翻唱《上海滩》简直好听到炸，开口就被惊艳到
！_20210901_640x360.mp4
[download]   3.2% of 7.92MiB at 65.70KiB/s ETA 01:59
~~~

looks like issue is your proxy, or specific to your system.

**Comment by dirkf** [comment]
In #30746 we read that Python isn't installed by default in macOS 12.3+. You should probably explain how your Python was installed, as that could affect how your cert issue occurs.

Also, you should probably install the git master from this repo which is much more current:
```
python3 -m pip install https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.tar.gz
```
(if _pip_ isn't working: https://github.com/ytdl-org/youtube-dl/issues/30788#issuecomment-1107926525).

**Comment by isxylands** [comment]
@dirkf
Thanks，I will try the git master later.
BTW:  I didn't install Python in any way, I just updated the OS from 10.15.x to 12.4, so this Python3 should be built into macOS 12.4. It just doesn't have Python 2.x built in anymore.

**Comment by dirkf** [comment]
Perhaps that's the problem: the old Python3 installation is still there but it doesn't know about the certs in the new system files.

#30746 suggests some ways of installing Python3 on new macOSes.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31257

**Comment by dirkf** [comment]
May this https://apple.stackexchange.com/a/446197 be relevant? (tldr; reinstall Homebrew)

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31258

**Comment by Cerveus** [comment]
> May this https://apple.stackexchange.com/a/446197 be relevant? (tldr; reinstall Homebrew)

Tried this and no luck

**Comment by Cerveus** [comment]
> May this https://apple.stackexchange.com/a/446197 be relevant? (tldr; reinstall Homebrew)

Tried reinstalling, no luck

**Comment by dirkf** [comment]
@Cerveus, if you are still having trouble, please open a new issue with the required details.
