### ISSUE TITLE
Latest update/release (2021.12.17) is over 8 months old

### ISSUE THREAD

**Issue by cousteaulecommandant** [ytdl-org/youtube-dl#31190]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ sudo youtube-dl -v -U
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-U']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-191-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
youtube-dl is up-to-date (2021.12.17)
```

## Description

Last available [release](https://github.com/ytdl-org/youtube-dl/releases) (2021.12.17) is over 8 months old now, and running `youtube-dl -U` says it's up to date (to that version), but there has been a significant amount of work done in the project since then (about one hundred commits).  Is a new release planned?  I think the project is due for a new release.

One year ago, youtube-dl used to get weekly updates, then it suddenly slowed down and seemingly stopped in June last year, with one extra update in December.

I don't know how much work creating a new release is.  Is it not just a matter of creating and pushing an annotated tag to GitHub, and then have an automated process do all the work?  Or is there some manual work involved (polishing things, checking that everything works fine, writing a changelog...)?  Could the update process be automated so that it simply tracks the `master` branch?  (Or even better, could there simply be an "update to pre-release version" option that updates to the latest `master` commit instead of the latest manually tagged release?)

**Comment by 89z** [comment]
No one owes you a release, and you don't get to decide when a release happens. If you want `master`, then just install it like everyone else:

~~~
pip install https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip
~~~

**Comment by rautamiekka** [comment]
> No one owes you a release, and you don't get to decide when a release happens. If you want `master`, then just install it like everyone else:
> 
> ~~~
> pip install https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip
> ~~~

Toxic (or at least rude) for nothing, and a
```
pip install "git+https://github.com/ytdl-org/youtube-dl"
```
would be simpler, especially to remember.

**Comment by cousteaulecommandant** [comment]
> No one owes you a release, and you don't get to decide when a release happens. If you want `master`, then just install it like everyone else:

I was merely stating that it may be time for a new release, not demanding anything from the developers; I'm sorry you took it that way.

**Comment by 89z** [comment]
> Toxic (or at least rude) for nothing, and a
> 
> ```
> pip install "git+https://github.com/ytdl-org/youtube-dl"
> ```
> 
> would be simpler, especially to remember.

you clearly don't know what you're talking about. Those two commands don't do the same thing. Notably, one requires a working Git installation.

**Comment by cousteaulecommandant** [comment]
> Those two commands don't do the same thing. Notably, one requires a working Git installation.

Good to know, thanks.

**Comment by cousteaulecommandant** [comment]
It has come to my attention that a similar issue was reported (#31067), which went unnoticed when I searched for similar issues (my search fu is not good enough and that issue didn't have many keywords to search for anyway), and where the maintainer suggests that they're aware of this.

**Comment by 89z** [comment]
> well i ok when i go to court and show this to my lawyer u bitch and i'm going to try and sue u fuckin guys

oh no, please don't 😂

**Comment by rautamiekka** [comment]
> > Toxic (or at least rude) for nothing, and a
> > ```
> > pip install "git+https://github.com/ytdl-org/youtube-dl"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > would be simpler, especially to remember.
> 
> you clearly don't know what you're talking about. Those two commands don't do the same thing. Notably, one requires a working Git installation.

Fair enough, I did have a working Git setup.

**Comment by dirkf** [comment]
From https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/
>... installing from tarball URLs is the most common piece of advice I find myself giving ...

+1

And `python -m ensurepip --upgrade`.

**Comment by rodrigograca31** [comment]
I agree that there is a need for a release.

using the default installation instructions or the github releases pages or even the version released to ubuntu/debian repos gives us `2021.12.17`

```bash
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```

**Comment by nicolaasjan** [comment]
Alternative:
https://github.com/ytdl-patched/youtube-dl
(Unofficial daily builds for youtube-dl)

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31234

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31251
