### ISSUE TITLE
Option to check if file already exists before downloading

### ISSUE THREAD

**Issue by defini-tiv** [ytdl-org/youtube-dl#31191]
Such an option would check if a file with the name the outputfile would have, before starting to download.

It would be useful for playlist downloading. Especially because the download of some files fails sometimes.
With this feature you could just run the same command multiple times to be sure all files got downloaded.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl#how-do-i-download-only-new-videos-from-a-playlist
