### ISSUE TITLE
yt-dlp doesn't get all video formats

### ISSUE THREAD

**Issue by KastriotH** [ytdl-org/youtube-dl#31197]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Hello, when i want to download from this live stream 4K quality, yt-dlp doesn't report/detects additional 1440p&2160p, also this happens on other 4K live streams, for normal videos ie non streaming everything is OK.

C:\Windows>yt-dlp.exe -f - https://www.youtube.com/watch?v=HpZAez2oYsA
[youtube] HpZAez2oYsA: Downloading webpage
[youtube] HpZAez2oYsA: Downloading android player API JSON
[youtube] HpZAez2oYsA: Downloading m3u8 information
[youtube] HpZAez2oYsA: Downloading m3u8 information
[info] Available formats for HpZAez2oYsA:
ID EXT RESOLUTION FPS │   TBR PROTO │ VCODEC        VBR ACODEC    ABR
─────────────────────────────────────────────────────────────────────
91 mp4 256x144     15 │  290k m3u8  │ avc1.42c00b  290k mp4a.40.5  0k
92 mp4 426x240     30 │  546k m3u8  │ avc1.4d4015  546k mp4a.40.5  0k
93 mp4 640x360     30 │ 1210k m3u8  │ avc1.4d401e 1210k mp4a.40.2  0k
94 mp4 854x480     30 │ 1569k m3u8  │ avc1.4d401f 1569k mp4a.40.2  0k
95 mp4 1280x720    30 │ 2969k m3u8  │ avc1.4d401f 2969k mp4a.40.2  0k
96 mp4 1920x1080   30 │ 5421k m3u8  │ avc1.640028 5421k mp4a.40.2  0k

**Comment by afterdelight** [comment]
this git is for youtube-dl not yt-dlp

**Comment by afterdelight** [comment]
use bestvideo+bestaudio

**Comment by pukkandan** [comment]
For yt-dlp, the solution is to use `--live-from-start` (https://github.com/yt-dlp/yt-dlp/issues/4959). Technically, (though OP is using yt-dlp), the reported issue does exist for youtube-dl since there is no live-from-start support

**Comment by dirkf** [comment]
The solution for yt-dl is to download a lower resolution and stand further away from the screen, wear mucky glasses, or whatever, so that you can't see the difference.
