### ISSUE TITLE
Prevent downloading 2 coppies of a stream at once

### ISSUE THREAD

**Issue by Hfinnell** [ytdl-org/youtube-dl#31199]
- [•ิ.•ั] I'm asking a question
- [•ิ.•ั] I've looked through the README and FAQ for similar questions
- [•ิ.•ั] I've searched the bugtracker for similar questions including closed ones

I wrote a .bat to automatically download all of the twitch channels listed in a file but if I have it scheduled to run every 10min it will open several copies of youtube-dl to download the same stream. My first thought was to check if a window with the stream name in it exists before opening youtube-dl but it turns out when you call youtube-dl from another cmd.exe window with: start cmd.exe /c yt-dlp.exe it doesn't show the stream url in the cmd window. I also considered checking for .part files but that seems to be unreliable because if youtube-dl exits incorrectly it can leave .part files. If there is a way to solve this within youtube-dl I sure can't find it and I can't think of a way to do it externally so any help would be much appreciated :)

**Comment by dirkf** [comment]
Invent a flag file (can be zero-length).

In your batch file:
* check whether that file exists and exit if it does
* otherwise create the file and continue to run one instance of yt-dl, using the `-a ...`/`--batch-file ...` option
* finally delete the flag file.

**Comment by dirkf** [comment]
@Hfinnell, did that help?
