### ISSUE TITLE
Different results when used with kivy and youtube-dl on android

### ISSUE THREAD

**Issue by apacelus** [ytdl-org/youtube-dl#31194]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
Not needed
```

## Description

I am trying to extract the mp4 link(s) for a video. When run via python and kivy(Python GUI framework) on Linux(Ubuntu 22.04) I get both mp4 and m3u8/hls links, from which I only use the mp4 links. However when the same code is run on android, youtube-dl will not extract mp4 links and only provides m3u8/hls links.
Here is the relevant code:
```
with YoutubeDL({'no_warnings': True, "simulate": True}) as ydl:
    video_headers = ydl.extract_info(url)
```

**Comment by 89z** [comment]
please provide example URL

**Comment by apacelus** [comment]
Nevermind, yt-dlp doesnt have this issue.

**Comment by 89z** [comment]
good riddance
