### ISSUE TITLE
unable to download youtube shorts

### ISSUE THREAD

**Issue by linuser6** [ytdl-org/youtube-dl#31202]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by 89z** [comment]
Your issue is bad, and you should feel bad.

**Comment by dirkf** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31166#issuecomment-1213632596 applies.
