### ISSUE TITLE
How to fix crashing on opening? (windows exe)

### ISSUE THREAD

**Issue by WolfenLynx** [ytdl-org/youtube-dl#31204]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I got this a long time ago on my windows 10 computer and it works fine. I have a laptop using win 11 and i'd like to download some videos in bulk and wanted to try this again.

I followed the instructions on the website for windows, I downloaded the C++ package. When I open it, it shows an empty command prompt and then closes. I am unable to type a thing. 
I tried a few different things and I can't seem to get it to work. (no it is not blocked by any firewall/win defender)
I am sorry I cannot send some kind of error message. 

Is this a windows 11 issue? Am I just doing it wrong? I am not super familiar with coding at all.

**Comment by dirkf** [comment]
From the [Description](https://github.com/ytdl-org/youtube-dl#user-content-description):
>youtube-dl is a command-line program ...

[Open a command prompt window](https://ss64.com/nt/run.html). You should see some text like this:
```shellsession
C:\whatever\directory>
```
Click in the window after `>`; type `youtube-dl --version` and Return/Enter. Your window should now look like this:
```shellsession
C:\whatever\directory>youtube-dl --version
2021.12.17
C:\whatever\directory>
```
If it does, re-read the [Manual](https://github.com/ytdl-org/youtube-dl#readme) to remind yourself how to use the program.

If not, select the text from the window (you may have to use the Edit>Mark menu command), copy it and paste it here.

**Comment by WolfenLynx** [comment]
the command prompt says that is not recognized as an internal/external command

**Comment by WolfenLynx** [comment]
im gonna just move the files from my PC to my laptop manually
