### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by Shrutigupta03** [ytdl-org/youtube-dl#31219]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
 raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I was working on project to play youtube video using opencv. 
![Screenshot (86)](https://user-images.githubusercontent.com/105665662/188100483-544cd3e0-9182-4848-a794-122ae6ae4af6.png)
This error occured after fixing Dislike_ count error. I have made some changes in backend_youtube_dl and then this unknown error has occured. I don't know how to fix it.

**Comment by dirkf** [comment]
Your problem is with _pafy_ and not yt-dl, as far as I can see. If you raise the issue on the pafy tracker, I'm sure they'd prefer the actual text output to a screenshot.
