### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError())

### ISSUE THREAD

**Issue by Disbride** [ytdl-org/youtube-dl#31220]
## Checklist

- [* ] I'm reporting a broken site support
- [* ] I've verified that I'm running youtube-dl version **2021.12.17**
- [* ] I've checked that all provided URLs are alive and playable in a browser
- [* ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [* ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
c:\Users\Rebec\Downloads>youtube-dl.exe -v --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0" --username rebeccafbennett@hotmail.com --password Ellie160418! https://10play.com.au/luxury-escapes/episodes/2022/episode-8/tpv220901jhpce
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://10play.com.au/luxury-escapes/episodes/2022/episode-8/tpv220901jhpce']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.2-2021-02-27-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-27-full_build-www.gyan.dev
[debug] Proxy map: {}
[TenPlay] tpv220901jhpce: Downloading JSON metadata
[TenPlay] 9000000000053151: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

I've made several attempts to download the video here https://10play.com.au/luxury-escapes/episodes/2022/episode-8/tpv220901jhpce it works fine through my browser but it is most likely geo blocked in countries other than Australia.

I have tried using cookies for the username and password. I've tried it with and without the user agent. I'm not sure what I should try next. Apologies if I'm missing information, I'm pretty new to this.

Edited to add - it's just one video, however on the website it's cut up with advertisements, which is why I want to download it, so I don't have to sit through the ads.

**Comment by Disbride** [comment]
Good news! I discovered that I was using a top URL, and by using the addon video downloadhelper I was able to find the direct URL and was able to download it that way!

**Comment by dirkf** [comment]
Credentials: --username rebeccafbennett@hotmail.com --password Ellie160418!
