### ISSUE TITLE
WARNING: Could not send HEAD request/HTTP Error 503: Service Temporarily Unavailable 

### ISSUE THREAD

**Issue by BitshakerTC** [ytdl-org/youtube-dl#31226]
Any one any ideas about this?

**Comment by 89z** [comment]
Try again with the `--head` option

**Comment by BitshakerTC** [comment]
How exactly does that go....I'm writing in terminal....youtube-dl....then webpage?

**Comment by 89z** [comment]
~~~
youtube-dl --head
~~~

**Comment by BitshakerTC** [comment]
Tried that and got this...
Usage: youtube-dl [OPTIONS] URL  [URL...]
youtube-dl: error: no such option: --head

**Comment by 89z** [comment]
# 😂

**Comment by BitshakerTC** [comment]
thanks anyway 89z :)

**Comment by dirkf** [comment]
Open a [new issue with the required supporting information](https://github.com/ytdl-org/youtube-dl/issues/30839) if you still have a problem.
