### ISSUE TITLE
Temporary error should be retried: urlopen error [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by mikkovedru** [ytdl-org/youtube-dl#31228]
## Checklist
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```
[~/Desktop/Training-videos, 1, 2s]: youtube-dl https://www.youtube.com/watch\?v\=jJZv3z7FOt0 --write-sub --ignore-errors -v                    
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=jJZv3z7FOt0', '--write-sub', '--ignore-errors', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.4 (CPython) - Linux-5.13.0-41-generic-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] jJZv3z7FOt0: Downloading webpage
WARNING: Unable to download webpage: <urlopen error [Errno -3] Temporary failure in name resolution>
[youtube] jJZv3z7FOt0: Downloading API JSON
[youtube] jJZv3z7FOt0: Downloading API JSON
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://rr1---sn-qo5-2vgs.googlevideo.com/videoplayback?expire=1662692105&ei=qVYaY-KoIICUv_IPrNuskA0&ip=2001%3A14ba%3A1afe%3Ae600%3Adb26%3A866f%3Acd8d%3Ad0c1&id=o-ADBFGActUOInKMxJlQKxK1d5BdR3fO9zcdHzdOus2IVg&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=5t&mm=31%2C29&mn=sn-qo5-2vgs%2Csn-5goeen7k&ms=au%2Crdu&mv=m&mvi=1&pl=40&initcwndbps=1293750&spc=lT-KhnTQvx0aOK4MlvhFa71BjkzpBDE&vprv=1&mime=video%2Fmp4&ns=DdPuvaRVDRPNyuqRZU4y-awH&gir=yes&clen=282887224&dur=2006.366&lmt=1662608047213125&mt=1662669898&fvip=4&keepalive=yes&fexp=24001373%2C24007246&beids=24277539&c=WEB&rbqsm=fr&txp=3316224&n=d3Xts8H3geBcdROqdDI4s&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgfDUEMmxE2eFN5CmDqgci0i2uoCxLlEA64yebu5NGZ_cCIECNzhIboBlUmyI8gYF693ZrPIMWsJ6ElDwpB7gdeptv&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAM7xNaC0im1dRMBXuexKdX-U_DgHg8xkbF9gYwbwvGotAiEAjVB4Zyjv9ZaJP_BqCc_lYZVZeWebYhlcRN-c3NCSjx0%3D'
[download] Resuming download at byte 163028644
[download] Destination: The Interrogation of Col. Russell Williams-jJZv3z7FOt0.f137.mp4
[download]  75.7% of 269.78MiB at 57.06KiB/s ETA 19:36ERROR: unable to download video data: <urlopen error [Errno -3] Temporary failure in name resolution>
Traceback (most recent call last):
  File "/home/mikko/.pyenv/versions/3.6.4/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/mikko/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/mikko/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/mikko/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/mikko/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/mikko/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/mikko/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/home/mikko/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/mikko/.pyenv/versions/3.6.4/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/mikko/.pyenv/versions/3.6.4/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1970, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/home/mikko/.pyenv/versions/3.6.4/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/mikko/.pyenv/versions/3.6.4/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/mikko/.pyenv/versions/3.6.4/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 2737, in https_open
    req, **kwargs)
  File "/home/mikko/.pyenv/versions/3.6.4/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
```

## Description
Temporary errors should not automatically exit the process, but keep on trying like with other ignorable errors.

I have very bad Internet (I can't do anything about it, sadly), which constantly causes me to have "DNS not found"/"failure in name resolution" errors in the browser, ping, youtube-dl... In the latter, the error is: `urlopen error [Errno -3] Temporary failure in name resolution`.

Like youtube-dl correctly says, it is temporary. And sure enough, that's how it is - it goes away in a bit, only to return and go away again. The problem is that:
- at that point, youtube-dl has already exited, which is sad, especially if I left a big batch of files to download (one error and the whole process stops)
- **Using `--ignore-errors`, `-R infinite`, or `-R 9000` options does not help.**

## Suggestion
- `--ignore-errors` should ignore the DNS errors as well
- `-R` should apply to errors like described
- implement a cool-down time. The recommendation is to have it, and to make the retry time random - in this case a float number between 1s and 10s sounds fitting.
- maybe there is an opportunity to improve the explanations/error messages?
	- distinguish and clearly tell between normal errors and fatal errors (that **force** the program to exit)
	- show when an error has been encountered and if it is being ignored
	- additionally show the progress on ignored errors (how many) and the repeat process (how many have been tried; out of how many max; is there a cool-down time and a counter showing that)

**Comment by dirkf** [comment]
You need a local caching DNS proxy, or to configure it better, or to choose some different external DNS provider.

The retry policy in yt-dl is limited, as you have found. It would be easy to catch your error as well as timeout in the HTTP downloader. It might also be possible to do this globally for a certain set of error diagnostics.

**Comment by mikkovedru** [comment]
My issue is with my terrible internet connection provider. Unfortunately, there is nothing that can I do about it at this moment.

Since I have big problems with youtube-dl, I started testing the `yt-dlp`. I have only limited experience, but it seems to be working much better - both the error rate (haven't encountered once so far) and a drastic (x50) difference in download speed (even without the in-software concurrency option).

**Comment by dirkf** [comment]
Well, if the problem the ISP has is related to DNS, as in your example, I already suggested several things that you could do to work around whatever it's not doing properly.

You need a recent installation from the yt-dl git master to download from YouTube at full speed (and not to have a "terrible internet connection provider").

yt-dlp does have different network retry logic, so you may indeed find it works better for you. If you can show what temporary errors other than the one in your original log are causing problems, it may be possible to improve the program so that such errors don't initially crash the download.

**Comment by dirkf** [comment]
You seem to have resolved the problem using yt-dlp. I'll take that as a suggestion to investigate back-porting the retry logic.
