### ISSUE TITLE
This app can*t run on your PC

### ISSUE THREAD

**Issue by fl4kez** [ytdl-org/youtube-dl#31229]
I once executed youtube-dl successfully but I just tried and now i get this error.
![image](https://user-images.githubusercontent.com/37409166/189411698-df741798-7b56-470b-892f-65975f3eca0d.png)

**Comment by dirkf** [comment]
Download the correct version of the program for your OS (a Windows version, I deduce). Open a command prompt window and paste the path of the yt-dl program (it doesn't need to be installed) after the prompt, inside "" if it has spaces. Add the `--verbose` option and `[Enter]`. Copy and paste the resulting output here.

**Comment by dirkf** [comment]
@fl4kez ?

**Comment by fl4kez** [comment]
Oh sorry, I had already downloaded the correct version. Else it wouldnt
have worked the first time. I just replaced the exe with the file from when
I first downloaded it .

Am Fr., 16. Sept. 2022 um 17:19 Uhr schrieb dirkf ***@***.***
