### ISSUE TITLE
How to stop a download in-progress?

### ISSUE THREAD

**Issue by Obliman** [ytdl-org/youtube-dl#31225]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

Is there a clean way to stop/cancel a download in-progress, or does the process just have to be "killed"?

**Comment by dirkf** [comment]
Use the interrupt signal for your environment, typically Ctrl+C. yt-dl will clear up as it exits, but some download artefacts may be left that you can delete.

**Comment by Obliman** [comment]
> Use the interrupt signal for your environment, typically Ctrl+C. yt-dl will clear up as it exits, but some download artefacts may be left that you can delete.

Thanks for the info. I'm trying to set up a python UI with downloads in a separate thread, but as far as I can tell there's no easy way to send the keyboard interrupt to only the thread containing youtube-dl. Maybe I just have to catch the keyboard interrupt in the main thread and allow the downloader thread to be stopped.

**Comment by dirkf** [comment]
In that scenario, you can use a cooperative approach to kill a DL thread (eg, check for a flag or event in your custom progress function), or use the appropriate API call to kill a DL process. 

See https://stackoverflow.com/questions/323972/is-there-any-way-to-kill-a-thread.

**Comment by Obliman** [comment]
> In that scenario, you can use a cooperative approach to kill a DL thread (eg, check for a flag or event in your custom progress function), or use the appropriate API call to kill a DL process.
> 
> See https://stackoverflow.com/questions/323972/is-there-any-way-to-kill-a-thread.

Hah, I was actually about to post a comment saying that the post you linked worked for me:

This was tricky to figure out, but since a worker thread doesn't receive the KeyboardInterrupt (only the main thread), the only way I found to make it work was with an augmented Thread class from [this stackoverflow answer](https://stackoverflow.com/a/325528/14345989). Note that for later versions of python the line `if not self.isAlive():` becomes `if not self.is_alive():`.
