### ISSUE TITLE
Add support for downloading audio from Callin

### ISSUE THREAD

**Issue by HighCommander4** [ytdl-org/youtube-dl#31230]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single audio file: https://www.callin.com/episode/fcc-commissioner-brendan-carr-on-elons-PrumRdSQJW
- Single audio file: https://www.callin.com/episode/episode-81-elites-melt-down-over-student-debt-lzxMidUnjA

## Description

Pretty self-explanatory, the site hosts audio tracks of call-in shows that you can listen to after the fact. Compare Soundcloud as another example of an extractor for audio-only content.

**Comment by dirkf** [comment]
The page uses NextJS. Metadata and what appears to be a valid m3u8 (although the URL contains the word `preview`) can be found in the hydration JSON.

**Comment by JohnnySunUmich** [comment]
Hey there! I'm currently a student in college and as part of my final project, I'm required to make contributions to an open-source project and write a report on my experiences (and inform the maintainers) . Could I take this issue?

**Comment by HighCommander4** [comment]
@JohnnySunUmich I can't speak for the project, but I can't imagine any reason why you couldn't take this issue -- it was filed a while ago and there's no sign of anyone else working on it.

As the issue reporter, I would certainly appreciate it!

**Comment by dirkf** [comment]
So is this all the same class "volunteering" to solve open-source issues?

@JohnnySunUmich, please go ahead. Do note the general points in the advice I gave [here](https://github.com/ytdl-org/youtube-dl/issues/31336#issuecomment-1306389725).

For this specific issue, what I'd suggest is to back-port the method `InfoExtractor._search_nextjs_data()` from yt-dlp, which is under the same licence: you'll have to adjust the signature to make it work in Python 2, as I'll discuss below. Then you can navigate the JSON returned by that method to populate the `info_dict` that the extractor has to return.
* The mandatory and optional elements are listed in the class documentation comments in `InfoExtractor`.
* There are various utility functions that you should use to ensure the correct sort of value (`xxx_or_none()`) and to get values that may sometimes be absent (`try_get()` and now `traverse_obj()`).
* Look at existing extractor code for examples.

[Python 3](https://docs.python.org/3/whatsnew/3.0.html) introduced the [dummy argument `*`](https://peps.python.org/pep-3102/) to mean that subsequent arguments can only be passed by keyword, or equivalently that there are no more positional parameters.

A cross-version equivalent is like this:
```py
# Python 3 only
def foo(arg1, arg2, *, kwonly1=val1, kwonly2=val2, **kwargs):
    ...

#Python 2+3
def foo(arg1, arg2, **kwargs):
    # instantiate keyword-only args
    kwonly1 = kwargs.pop('kwonly1', val1)
    # or if kwonly2 is going to be read and passed down
    # in kwargs to another function (eg `fatal` in the mentioned method) 
    if 'kwonly2' in kwargs:
        kwonly2 = kwargs.get('kwonly2')
    else:
        kwargs['kwonly2'] = kwonly2 = val2
        kwargs = compat_kwargs(kwargs)
    ...
```
You can see the benefit of the new syntax, but that doesn't make it backward-compatible. Also, the one (?) person trying to run yt-dl on Python 2.6 will thank you for passing an updated `kwargs` using `compat_kwargs()`!

**Comment by pukkandan** [comment]
> A cross-version equivalent is like this:

I use `*` isn yt-dlp because I can - it's in no way essential to the working of the code. Rather than the hack with `kwargs`, I'd recommend to just remove the `*` and mention in docstring that it is a keyword only argument (see `_download_webpage_handle`)

**Comment by JohnnySunUmich** [comment]
@dirkf Thank you so much for your detailed advice! Will keep you updated if there's any progress

**Comment by dirkf** [comment]
What are you saying, "hack"?

There may also be this issue:
```
def foo(arg1, arg2, kwonly1='val1', kwonly2='val2', **kwargs):
    pass
    
foo(1, 2, 'val1_a', kwonly1='val1_b')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: foo() got multiple values for keyword argument 'kwonly1'
```

**Comment by JohnnySunUmich** [comment]
Hi @dirkf ! I have a PR ready, and the tests pass locally. Could you please review it? Our course policy states that if my change is accepted into the code base before 11:59pm 12/12/2022 (GMT-5), I can receive extra credit. So if you could merge it before this time, I would really appreciate that :))) Thank you for your great help! I will follow up immediately if there's any change requested.
