### ISSUE TITLE
ERROR: Join this channel to get access to members-only content like this video, and other exclusive perks.

### ISSUE THREAD

**Issue by vishwajeet4real** [ytdl-org/youtube-dl#31238]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

**Comment by 89z** [comment]
Thanks for the report, we will resolve this right away

# 👍

**Comment by vishwajeet4real** [comment]
I am not able to download members only videos..

**Comment by gamer191** [comment]
Do you have access to those videos? If yes, try logging into youtube-dl using `youtube-dl URL --username USERNAME --password PASSWORD` 

If your account is protected by two-factor authentication, use `youtube-dl URL --username USERNAME --password PASSWORD --twofactor CODE`

**Comment by dirkf** [comment]
Also, show details of the failure(s) encountered including *full verbose log*.

**Comment by pukkandan** [comment]
> Do you have access to those videos? If yes, try logging into youtube-dl using `youtube-dl URL --username USERNAME --password PASSWORD`
> 
> If your account is protected by two-factor authentication, use `youtube-dl URL --username USERNAME --password PASSWORD --twofactor CODE`

From the title, I think they are asking about youtube. In which case, only `--cookies` will work, not username+password

**Comment by dirkf** [comment]
@vishwajeet4real ?

**Comment by cansurmeli** [comment]
Due to Google, username/pass combo doesn't work. Use `--cookies` option instead with youtube-dl. Look into README for more.
