### ISSUE TITLE
Will this app release new version?

### ISSUE THREAD

**Issue by KiYugadgeter** [ytdl-org/youtube-dl#31234]
There is no new release since December 2021.  
Will this release stable version in the future?

**Comment by 89z** [comment]
bad dog, no bone

# 🐕

**Comment by Rourke101** [comment]
Seems like the author gave up after they went after him

**Comment by 89z** [comment]
@Rourke101 did you not see, where the maintainer closed the issue:

https://github.com/ytdl-org/youtube-dl/issues/31190#issuecomment-1221631493

the concern presented on this page, https://github.com/ytdl-org/youtube-dl/issues/31234, **is well known**. For whatever reason, the current maintainer has decided not to act on this suggestion (repeatedly). **It is their right to do so**. If you are not happy with this outcome, you are welcome to use other software.

**Comment by dirkf** [comment]
Duplicate of #30167.

**Comment by Vangelis66** [comment]
... Rather, duplicate of #31067 😄 ...
