### ISSUE TITLE
Writing custom "comment" metadata field fails with --ppa

### ISSUE THREAD

**Issue by gevhaz** [ytdl-org/youtube-dl#31245]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, thanks for your efforts with this excellent tool.

I have an issue that may be the result normal functionality so I'll ask a question (please relabel as bug if it is not expected).

I'm trying to add a "comment" tag to a download from Youtube. I do this with the option `--postprocessor-args "ffmpeg:-metadata comment=Test"`. 

This works with the command:

```
yt-dlp --ignore-config -x --ppa "ffmpeg:-metadata comment=Test" https://www.youtube.com/watch?v=9tLglpFAyIg -v
```

but not with the command:

```
yt-dlp --ignore-config -x --ppa "ffmpeg:-metadata comment=Test" https://www.youtube.com/watch?v=9tLglpFAyIg -v --add-metadata
```

I can see in the second case that the `--add-metadata` option makes another comment tag be added (the URL of the video). In the end though, the Youtube description is added as the comment tag (very weird, since the log only shows the URL and my "Test" comment being sent to ffmpeg).

### Main question

How can I overwrite the final `comment` metadata field with a custom value?

### Side question

With both commands, I see the comment tag as "comment" with ffprobe, but my music player shows it as a "description" tag. My music player usually doesn't hide the actual values. Any idea what this is about?

Reading the documentation, it makes sense that the Youtube description should be in the "description" tag, but not for my custom value that I explicitly say should go in the "comment" tag.

**Comment by dirkf** [comment]
Try https://github.com/yt-dlp/yt-dlp/issues?q=is%3Aopen+is%3Aissue !
