### ISSUE TITLE
快速访问Youtube的方法

### ISSUE THREAD

**Issue by starvin8** [ytdl-org/youtube-dl#31255]
快速访问Youtube的方法：[科学上网方法](https://github.com/starvin8/FreePAC)

**Comment by dirkf** [comment]
G Translate: "How to quickly visit YouTube: [Scientific Internet method](https://github-com.translate.goog/starvin8/FreePAC?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en)"

The translation (when I read it) failed to convert the metaphor "invited to drink tea" adequately. I believe that "was asked to help the police with their inquiries" catches the sense in British English, where that wording may carry the implication that the person being interviewed may in fact be banged around the interrogation room a bit ("Support your local constabulary: beat yourself up..."). Of course this never happens in the era of the Police and Criminal Evidence Act 1984.
