### ISSUE TITLE
NBA url ?

### ISSUE THREAD

**Issue by JamesDAdams** [ytdl-org/youtube-dl#31256]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, i check all issues about NBA and i don't find who i find (😅) the url for game match ?

thanks for the help

**Comment by dirkf** [comment]
If you don't know the URL that plays some video, yt-dl won't find it for you. On the other hand, if you have a page (and its URL) with a video that you'd like to capture, and yt-dl doesn't do that, please open an issue with the details: a site support request if the URL falls back to the Generic Extractor; a broken site support request if an exiting extractor for that site fails.

For info on how to watch (I assume) basketball online, try a forum dedicated to the sport.
