### ISSUE TITLE
Output downloaded bytes to BytesIO

### ISSUE THREAD

**Issue by Rilm2525** [ytdl-org/youtube-dl#31252]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is it possible to use a io.BytesIO as a download destination when using youtube_dl from Python?

**Comment by Rilm2525** [comment]
How do I get progress from Python if I use stdout for file output?

**Comment by dirkf** [comment]
Progress messages are written with the `to_screen()` method. When the download output is stdout, the method writes to stderr instead.

**Comment by dirkf** [comment]
Or you can use a logger, if you are creating a program that calls yt-dl. See the manual.

Duplicate of #30815.
