### ISSUE TITLE
Unable to download from UDEMY

### ISSUE THREAD

**Issue by eyal1983** [ytdl-org/youtube-dl#31263]
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
No log (see [here](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md)).

Duplicate of #29410, or open a new issue correctly using the link above if your verbose log doesn't correspond to the one posted in that issue.
