### ISSUE TITLE
Trouble downloading just the captions for a playlist?

### ISSUE THREAD

**Issue by Luke-L** [ytdl-org/youtube-dl#31278]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

I want to download a whole playlist's transcriptions for each video and have the title of the file be shown in the filename. Also i would ~like~ to have them be enumerated properly, where the oldest video in the playlist starts at 57 and so on. Here is what i have tried: 
`youtube-dl --verbose --write-auto-sub --skip-download --autonumber-start 57 -o "P:\FFPod Subs\#%(autonumber)% - (title)s.%(ext)s" https://youtube.com/playlist?list=PL0YaZqNO5Z3eX1XOvlyiF9FfYdCCs0jjE`

here is the output:
```
[info] Writing video subtitles to: P:\FFPod Subs\#% - (title)s.en.vtt
[download] Downloading video 16 of 65
[youtube] WSpz5Lpp-BA: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[info] Writing video subtitles to: P:\FFPod Subs\#% - (title)s.en.vtt
[download] Downloading video 17 of 65
[youtube] V3-CwU0su9A: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[info] Writing video subtitles to: P:\FFPod Subs\#% - (title)s.en.vtt
[download] Downloading video 18 of 65
[youtube] VkhBVfOXiOA: Downloading webpage
```

after going through the whole playlist, it has output one vtt file and even that has fucked up formatting. What do i need to change in my command? any help is appreciated :)

**Comment by dirkf** [comment]
Try this
```diff
+youtube-dl --verbose --write-auto-sub --skip-download --autonumber-start 57 -o "P:\FFPod Subs\#%(autonumber)s - %(title)s.%(ext)s" "https://youtube.com/playlist?list=PL0YaZqNO5Z3eX1XOvlyiF9FfYdCCs0jjE"
-youtube-dl --verbose --write-auto-sub --skip-download --autonumber-start 57 -o "P:\FFPod Subs\#%(autonumber)% - (title)s.%(ext)s" https://youtube.com/playlist?list=PL0YaZqNO5Z3eX1XOvlyiF9FfYdCCs0jjE
```
The differences should be apparent.

**Comment by Luke-L** [comment]
> ```diff
> +youtube-dl --verbose --write-auto-sub --skip-download --autonumber-start 57 -o "P:\FFPod Subs\#%(autonumber)s - %(title)s.%(ext)s" "https://youtube.com/playlist?list=PL0YaZqNO5Z3eX1XOvlyiF9FfYdCCs0jjE"
> ```

thanks a ton! is there any way to change the subtitles to not be so poorly formatted? a txt file might be even better.

**Comment by Vangelis66** [comment]
> it has output one vtt file and **even that has f*cked up formatting**.

Confirmed 😞 ; you may have stumbled upon a `youtube-dl` bug here... 
Test: 
```
youtube-dl -v --skip-download "EGgKijcgWcs" --write-auto-sub => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--skip-download', 'EGgKijcgWcs', '--write-auto-sub']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2022.10.04.40298
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 5.0, ffprobe 5.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] EGgKijcgWcs: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: What Flavors are We _ Salt, Pepper, & Bullshit-EGgKijcgWcs.en.vtt
```
Attaching output as [yt-autosubs-test.vtt.txt](https://github.com/ytdl-org/youtube-dl/files/9711398/yt-autosubs-test.vtt.txt)

A whole video's worth of subs are found in line 7...

OTOH, with `yt-dlp`: 
```
yt-dlp -v --skip-download "EGgKijcgWcs" --write-auto-sub => 

[debug] Command-line config: ['--ffmpeg-location', '..', '--downloader-args', 'ffmpeg:-v 8 -stats', '-v', '--skip-download', 'EGgKijcgWcs', '--write-auto-sub']
[debug] Encodings: locale cp1253, fs utf-8, pref cp1253, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version 2022.10.04.061235 [1305b65] (win32_exe)
[debug] Python 3.7.9 (CPython 32bit) - Windows-Vista-6.0.6003-SP2
[debug] Checking exe version: "..\ffmpeg" -bsfs
[debug] Checking exe version: "..\ffprobe" -bsfs
[debug] exe versions: ffmpeg 5.0 (fdk,setts), ffprobe 5.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] [youtube] Extracting URL: EGgKijcgWcs
[youtube] EGgKijcgWcs: Downloading webpage
[youtube] EGgKijcgWcs: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] EGgKijcgWcs: Downloading subtitles: en
[debug] Default format spec: bestvideo*+bestaudio/best
[info] EGgKijcgWcs: Downloading 1 format(s): 248+251
[info] Writing video subtitles to: What Flavors are We? ?? Salt, Pepper, & Bullshit [EGgKijcgWcs].en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=EGgKijcgWcs&caps=asr&xoaf=4&hl=en&ip=0.0.0.0&ipbits=0&expire=1664950055&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=AFCCFCAEF703CAA6BF80843DF9E7F77DE42A729F.282557E0D8A0F6B6F9682E71512908625C7DE32E&key=yt8&kind=asr&lang=en&fmt=vtt"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: What Flavors are We? ?? Salt, Pepper, & Bullshit [EGgKijcgWcs].en.vtt
[download] 100% of  534.83KiB in 00:00:01 at 471.64KiB/s
```
Attaching output as [yt-dlp-autosubs-test.vtt.txt](https://github.com/ytdl-org/youtube-dl/files/9711408/yt-dlp-autosubs-test.vtt.txt)

Better formatting!

**Comment by dirkf** [comment]
Is it the problem from #30710? If not, post an example.

**Comment by Vangelis66** [comment]
I'm not certain whether **I** was the one asked 😉 , but, in all probability, it is indeed #30710; example  (with attached subs) has been already posted...

**Comment by Luke-L** [comment]
> 

so is yt-dlp a more featured version of ytdl? meaning ytdl is out of date or something?

**Comment by dirkf** [comment]
yt-dlp is derived from a yt-dl fork so there is substantial commonality especially with extractor modules. Here we are more conservative (some say antediluvian) on platform and dependency requirements, whereas yt-dlp runs closer to the bleeding edge. Good stuff from yt-dlp should be pulled back, but it's not a drop-in process. We are certainly out of date on this subtitle issue which should be fixed in the next update to the YT extractor.
