### ISSUE TITLE
[animationdigitalnetwork.fr] How to download an ADN video

### ISSUE THREAD

**Issue by 002-sans** [ytdl-org/youtube-dl#31272]
## Checklist

- [✔] I'm asking a question
- [✔] I've looked through the README and FAQ for similar questions
- [✔] I've searched the bugtracker for similar questions including closed ones

## Question

I have a question, I try to do: `ytb download https://animationdigitalnetwork.fr/video/fire-force-saison-2/11779-episode-1-combat-de-pompiers-combat-d-hommes` but it doesn't work, how to download a ADN video ? I fount lot of issues but don't work for me.. I already try this too: `ytb download -vv https://animationdigitalnetwork.fr/video/fire-force-saison-2/11779-episode-1-combat-de-pompiers-combat-d-hommes` but same

**Comment by dirkf** [comment]
The site isn't supported. Use [this template](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=site-support-request&template=2_site_support_request.md): you can paste the template text here.

**Comment by dirkf** [comment]
Superseded by #31273
