### ISSUE TITLE
Download [https://animationdigitalnetwork.fr] Videos

### ISSUE THREAD

**Issue by 002-sans** [ytdl-org/youtube-dl#31273]
## Checklist

- [✔] I'm reporting a new site support request
- [✔] I've verified that I'm running youtube-dl version **2021.12.17**
- [✔] I've checked that all provided URLs are alive and playable in a browser
- [✔] I've checked that none of provided URLs violate any copyrights
- [✔] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://animationdigitalnetwork.fr/video/deadlysins_tv/10667-episode-1-les-sept-peches-capitaux- Single video: 
- Playlist: https://animationdigitalnetwork.fr/video/deadlysins_tv

## Description

I want to download video from [ADN](https://animedigitalnetwork.fr) (animedigitalnetwork), only for free videos.

**Comment by 002-sans** [comment]
*you closed all two issues*

**Comment by Vangelis66** [comment]
FWIW, the service is reserved for **French** IPs (`geoblocked` label): 
```
For legal reasons, you are not allowed to watch our videos from this territory. Your country: [.....] (IP: a.b.c.d)
```
; additionally, yet another **Javascript-generated** site, which appears to be the norm these days 😡 ...

**Comment by arobase-che** [comment]
It's works.

> I want to download video from [ADN](https://animedigitalnetwork.fr/) (**animedigitalnetwork**), only for free videos.

Not anymore, ADN now means Animation Digital Network. 
I'm on 4G abroad so I will not check that the download completes but I was able to download the first percentages.

adn renames itself from animedigitalnetwork to animationdigitalnetwork. I just rename the URL in my personal installation months ago but didn't do it on the Github repository. Sorry about this, now I'm doing it.

If it doesn't, please provide an example.

The quick fix is to use the old URL.

For example : 
https://animationdigitalnetwork.fr/video/deadlysins_tv/10667-episode-1-les-sept-peches-capitaux-

Use : 
https://animedigitalnetwork.fr/video/deadlysins_tv/10667-episode-1-les-sept-peches-capitaux-

**Comment by Vangelis66** [comment]
With #31275 applied locally and the use of a whitelisted **French IP** address (via VPN), I now get: 
```
youtube-dl -v -F "https://animationdigitalnetwork.fr/video/deadlysins_tv/10667-episode-1-les-sept-peches-capitaux-" => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://animationdigitalnetwork.fr/video/deadlysins_tv/10667-episode-1-les-sept-peches-capitaux-']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2022.10.02.810
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 5.0, ffprobe 5.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[ADN] 10667: Downloading player config JSON metadata
[ADN] 10667: Downloading access token
[ADN] 10667: Downloading links JSON metadata
[ADN] 10667: Downloading vostf sd JSON metadata
[ADN] 10667: Downloading m3u8 information
[ADN] 10667: Downloading vostf mobile JSON metadata
[ADN] 10667: Downloading m3u8 information
[ADN] 10667: Downloading additional video metadata
[info] Available formats for 10667:
format code  extension  resolution note
vostf-816    mp4        640x360     816k , avc1.4d001f, mp4a.40.2
vostf-1389   mp4        853x480    1389k , avc1.640028, mp4a.40.2 (best)
```
A note on **geo-blocking**: 
The API that generates the JSON metadata and HLS playlists can't be fooled by ` --geo-bypass-country FR` 😞 ; issuing the ` -g` flag while on VPN will get you: 
```
https://free1b.animedigitalnetwork.fr/1664785370697-0-1e68c1886a73a3a7fe5c654ba6f8d6d6/video0_free_480p/playlist.m3u8
```
Further applications of the ` -g` flag showed that the HLS stream is being served from CDN nodes with hostnames 
`freeXb.animedigitalnetwork.fr`, where X can be **1** or **3**; however, none of these two CDN nodes implement geo-blocking, thus the **adnIE** is eligible for the ` --geo-verification-proxy` treatment 😜 ...

**Comment by arobase-che** [comment]
You dig it a lot !

I will try to fix the test and verify everything about coding convention.

**Comment by arobase-che** [comment]
Thank you @dirkf ! 
I just finished everything, hope it will be merged.
