### ISSUE TITLE
Unable to launch the .exe on Windows

### ISSUE THREAD

**Issue by koopa990** [ytdl-org/youtube-dl#31287]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

So I finally made a Path Variable for the .exe file in this PC\User\document\youtube-dl. I double click on the .exe, but the command window shortly closed on its own. Am I missing something or an error within the tool itself?

**Comment by october262** [comment]
> ## Checklist
> * [x]  I'm asking a question
> * [x]  I've looked through the README and FAQ for similar questions
> * [x]  I've searched the bugtracker for similar questions including closed ones
> 
> ## Question
> WRITE QUESTION HERE
> 
> So I finally made a Path Variable for the .exe file in this PC\User\document\youtube-dl. I double click on the .exe, but the command window shortly closed on its own. Am I missing something or an error within the tool itself?

what windows version are you running ??

**Comment by koopa990** [comment]
> > ## Checklist
> > * [x]  I'm asking a question
> > * [x]  I've looked through the README and FAQ for similar questions
> > * [x]  I've searched the bugtracker for similar questions including closed ones
> > 
> > ## Question
> > WRITE QUESTION HERE
> > 
> > So I finally made a Path Variable for the .exe file in this PC\User\document\youtube-dl. I double click on the .exe, but the command window shortly closed on its own. Am I missing something or an error within the tool itself?
> 
> what windows version are you running ??

Windows 10

**Comment by october262** [comment]
> > > ## Checklist
> > > 
> > > * [x]   I'm asking a question
> > > * [x]   I've looked through the README and FAQ for similar questions
> > > * [x]   I've searched the bugtracker for similar questions including closed ones
> > > 
> > > ## Question
> > > WRITE QUESTION HERE
> > > So I finally made a Path Variable for the .exe file in this PC\User\document\youtube-dl. I double click on the .exe, but the command window shortly closed on its own. Am I missing something or an error within the tool itself?
> > 
> > 
> > what windows version are you running ??
> 
> Windows 10

try pressing the windows key & R key at the same time and then type cmd
to bring up the command window

**Comment by october262** [comment]
> > > > > ## Checklist
> > > > > 
> > > > > * [x]    I'm asking a question
> > > > > * [x]    I've looked through the README and FAQ for similar questions
> > > > > * [x]    I've searched the bugtracker for similar questions including closed ones
> > > > > 
> > > > > ## Question
> > > > > WRITE QUESTION HERE
> > > > > So I finally made a Path Variable for the .exe file in this PC\User\document\youtube-dl. I double click on the .exe, but the command window shortly closed on its own. Am I missing something or an error within the tool itself?
> > > > 
> > > > 
> > > > what windows version are you running ??
> > > 
> > > 
> > > Windows 10
> > 
> > 
> > try pressing the windows key & R key at the same time and then type cmd
> > to bring up the command window
> 
> And what's next?

did the command window not show up ??

**Comment by koopa990** [comment]
Still nothing. The same goes for CMD 
![Screenshot 2022-10-11 214429](https://user-images.githubusercontent.com/63154730/195237840-635a599c-2398-428c-952f-3f8a9392f83b.png)

**Comment by koopa990** [comment]
> > > > > > ## Checklist
> > > > > > 
> > > > > > * [x]     I'm asking a question
> > > > > > * [x]     I've looked through the README and FAQ for similar questions
> > > > > > * [x]     I've searched the bugtracker for similar questions including closed ones
> > > > > > 
> > > > > > ## Question
> > > > > > WRITE QUESTION HERE
> > > > > > So I finally made a Path Variable for the .exe file in this PC\User\document\youtube-dl. I double click on the .exe, but the command window shortly closed on its own. Am I missing something or an error within the tool itself?
> > > > > 
> > > > > 
> > > > > what windows version are you running ??
> > > > 
> > > > 
> > > > Windows 10
> > > 
> > > 
> > > try pressing the windows key & R key at the same time and then type cmd
> > > to bring up the command window
> > 
> > 
> > And what's next?
> 
> did the command window not show up ?? see this guide for more info - https://www.wikihow.com/Use-Youtube%E2%80%90dl

Still does not work, same goes to CMD
![Screenshot 2022-10-11 214429](https://user-images.githubusercontent.com/63154730/195238024-fd1f7a31-825e-4f8c-b3b6-c329236e783b.png)

**Comment by october262** [comment]
> > > > > > > ## Checklist
> > > > > > > 
> > > > > > > * [x]      I'm asking a question
> > > > > > > * [x]      I've looked through the README and FAQ for similar questions
> > > > > > > * [x]      I've searched the bugtracker for similar questions including closed ones
> > > > > > > 
> > > > > > > ## Question
> > > > > > > WRITE QUESTION HERE
> > > > > > > So I finally made a Path Variable for the .exe file in this PC\User\document\youtube-dl. I double click on the .exe, but the command window shortly closed on its own. Am I missing something or an error within the tool itself?
> > > > > > 
> > > > > > 
> > > > > > what windows version are you running ??
> > > > > 
> > > > > 
> > > > > Windows 10
> > > > 
> > > > 
> > > > try pressing the windows key & R key at the same time and then type cmd
> > > > to bring up the command window
> > > 
> > > 
> > > And what's next?
> > 
> > 
> > did the command window not show up ?? see this guide for more info - https://www.wikihow.com/Use-Youtube%E2%80%90dl
> 
> Still does not work, same goes to CMD ![Screenshot 2022-10-11 214429](https://user-images.githubusercontent.com/63154730/195238024-fd1f7a31-825e-4f8c-b3b6-c329236e783b.png)

did you follow the instructions in method 2 in the link i gave you ??

**Comment by koopa990** [comment]
> > > > > > > > ## Checklist
> > > > > > > > 
> > > > > > > > * [x]       I'm asking a question
> > > > > > > > * [x]       I've looked through the README and FAQ for similar questions
> > > > > > > > * [x]       I've searched the bugtracker for similar questions including closed ones
> > > > > > > > 
> > > > > > > > ## Question
> > > > > > > > WRITE QUESTION HERE
> > > > > > > > So I finally made a Path Variable for the .exe file in this PC\User\document\youtube-dl. I double click on the .exe, but the command window shortly closed on its own. Am I missing something or an error within the tool itself?
> > > > > > > 
> > > > > > > 
> > > > > > > what windows version are you running ??
> > > > > > 
> > > > > > 
> > > > > > Windows 10
> > > > > 
> > > > > 
> > > > > try pressing the windows key & R key at the same time and then type cmd
> > > > > to bring up the command window
> > > > 
> > > > 
> > > > And what's next?
> > > 
> > > 
> > > did the command window not show up ?? see this guide for more info - https://www.wikihow.com/Use-Youtube%E2%80%90dl
> > 
> > 
> > Still does not work, same goes to CMD ![Screenshot 2022-10-11 214429](https://user-images.githubusercontent.com/63154730/195238024-fd1f7a31-825e-4f8c-b3b6-c329236e783b.png)
> 
> did you follow the instructions in method 2 in the link i gave you ??

YES, I followed exactly what the steps said!!

**Comment by october262** [comment]
> > > > > > > > > ## Checklist
> > > > > > > > > 
> > > > > > > > > * [x]        I'm asking a question
> > > > > > > > > * [x]        I've looked through the README and FAQ for similar questions
> > > > > > > > > * [x]        I've searched the bugtracker for similar questions including closed ones
> > > > > > > > > 
> > > > > > > > > ## Question
> > > > > > > > > WRITE QUESTION HERE
> > > > > > > > > So I finally made a Path Variable for the .exe file in this PC\User\document\youtube-dl. I double click on the .exe, but the command window shortly closed on its own. Am I missing something or an error within the tool itself?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > what windows version are you running ??
> > > > > > > 
> > > > > > > 
> > > > > > > Windows 10
> > > > > > 
> > > > > > 
> > > > > > try pressing the windows key & R key at the same time and then type cmd
> > > > > > to bring up the command window
> > > > > 
> > > > > 
> > > > > And what's next?
> > > > 
> > > > 
> > > > did the command window not show up ?? see this guide for more info - https://www.wikihow.com/Use-Youtube%E2%80%90dl
> > > 
> > > 
> > > Still does not work, same goes to CMD ![Screenshot 2022-10-11 214429](https://user-images.githubusercontent.com/63154730/195238024-fd1f7a31-825e-4f8c-b3b6-c329236e783b.png)
> > 
> > 
> > did you follow the instructions in method 2 in the link i gave you ??
> 
> YES, I followed exactly what the steps said!!

try following these instructions - https://danclowry.com/blog/youtube-dl-windows-install/

**Comment by dirkf** [comment]
That's a good instructional page but the text is hidden unless JavaScript is enabled.

**Comment by koopa990** [comment]
> That's a good instructional page but the text is hidden unless JavaScript is enabled.

enabled text reveal?

**Comment by rautamiekka** [comment]
Technically you can, but it's unsafe.

**Comment by rautamiekka** [comment]
Thanks !

Remember to quote the URL in all cases to avoid the shell/terminal doing unwanted stuff. Since you're on PowerShell, you can use single quotes to tell PS to take the string as is (a _raw string_), but you can safely use double quotes, too.
