### ISSUE TITLE
Question: Does youtube-dl re-encode bitstreams upon download?

### ISSUE THREAD

**Issue by kyhcj21** [ytdl-org/youtube-dl#31289]
Hi all,

I'd like to know if youtoube-dl keeps the original bitstream upon download, or re-encodes it to a specified format. Would anyone be able to clarify this?

Thanks,
Y

**Comment by dirkf** [comment]
It depends. Generally the audio and video bitstreams are not re-encoded.

Certain options can provoke re-encoding, by invoking _ffmpeg_ (or some other helper program) with options that cause re-encoding:
* `--recode-video ...` may specify a container format that requires the audio or video to be re-encoded: for an AVI yt-dl forces _ffmpeg_ to re-encode the video as xvid; in other cases the [_ffmpeg_ default processing applies](https://ffmpeg.org/ffmpeg.html#toc-Stream-handling);
* `--postprocessor-args ...` or `--external-downloader-args ...` could specify encoding options for _ffmpeg_ or some other helper program;
* subtitles are re-encoded according to `--convert-subs ...`.

**Comment by dirkf** [comment]
@kyhcj21 ?

**Comment by kyhcj21** [comment]
Thanks so much for the information! It was really helpful.
