### ISSUE TITLE
Facebook download port

### ISSUE THREAD

**Issue by Brotherred** [ytdl-org/youtube-dl#31284]
## Checklist

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--referer', 'URL', '--fixup', 'POLICY', '-k', '--username', 'PRIVATE', '-p,', '--password', 'PRIVATE', 'https://fb.watch/g24YZ0cemw/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-72-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Proxy map: {}
[generic] g24YZ0cemw: Requesting header
[redirect] Following redirect to https://www.facebook.com/watch/?v=1153710882224904&ref=sharing
[facebook] Downloading login page
[facebook] Logging in
[facebook] 1153710882224904: Downloading webpage
[facebook] 1153710882224904: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/facebook.py", line 680, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/facebook.py", line 594, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
I normally use Youtube-dl in the Facebook argument mode. Always doing so with user login credentials. It almost always works well, this time it suggested submitting this report. I am on a Ubuntu Diriv, Bohdi 
Inxi oupput:
CPU: Quad Core AMD A10-5745M APU with Radeon HD Graphics (-MCP-) speed/min/max: 1205/1100/2100 MHz
Kernel: 5.4.0-72-generic x86_64 Up: 8h 29m Mem: 3981.6/5150.3 MiB (22.0% used) Procs: 244
Shell: bash 5.0.17 inxi: 3.0.38
$ inxi -S
System:    Host: **** Kernel: 5.4.0-72-generic x86_64 bits: 64 Desktop: Moksha 0.3.4.17346
           Distro: Ubuntu 20.04.5 LTS (Focal Fossa)

**Comment by dirkf** [comment]
Please review duplicate issue #31205 and continue discussion at PR #30700.
