### ISSUE TITLE
NRK: Crashes when downloading series

### ISSUE THREAD

**Issue by VikingKing** [ytdl-org/youtube-dl#31285]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```shellsession
$ youtube-dl --ignore-config --verbose https://tv.nrk.no/serie/broedrene-dal-og-spektralsteinene
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '--verbose', 'https://tv.nrk.no/serie/broedrene-dal-og-spektralsteinene']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-126-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {}
[debug] Using fake IP 84.215.118.247 (NO) as X-Forwarded-For.
[NRKTVSeries] broedrene-dal-og-spektralsteinene: Downloading serie JSON
0;31mERROR:0m broedrene-dal-og-spektralsteinene: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/git/youtube-dl/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/git/youtube-dl/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/git/youtube-dl/youtube_dl/YoutubeDL.py", line 816, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/git/youtube-dl/youtube_dl/YoutubeDL.py", line 837, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/git/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/git/youtube-dl/youtube_dl/extractor/nrk.py", line 700, in _real_extract
    series = self._call_api(
  File "/opt/git/youtube-dl/youtube_dl/extractor/nrk.py", line 60, in _call_api
    return self._download_json(
  File "/opt/git/youtube-dl/youtube_dl/extractor/common.py", line 895, in _download_json
    res = self._download_json_handle(
  File "/opt/git/youtube-dl/youtube_dl/extractor/common.py", line 881, in _download_json_handle
    return self._parse_json(
  File "/opt/git/youtube-dl/youtube_dl/extractor/common.py", line 910, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: broedrene-dal-og-spektralsteinene: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Started a few weeks ago. Seems it's not able to download series metadata.
Manually downloading one episode at a time works ok.

The series in the example is marked as globally available.

**Comment by october262** [comment]
> ## Checklist
> * [x]  I'm reporting a broken site support
> * [x]  I've verified that I'm running youtube-dl version **2021.12.17**
> * [x]  I've checked that all provided URLs are alive and playable in a browser
> * [x]  I've checked that all URLs and arguments with special characters are properly quoted or escaped
> * [x]  I've searched the bugtracker for similar issues including closed ones
> 
> ## Verbose log
> $ youtube-dl --ignore-config --verbose https://tv.nrk.no/serie/broedrene-dal-og-spektralsteinene [debug] System config: [] [debug] User config: [] [debug] Custom config: [] [debug] Command-line args: ['--ignore-config', '--verbose', 'https://tv.nrk.no/serie/broedrene-dal-og-spektralsteinene'] [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8 [debug] youtube-dl version 2021.12.17 [debug] Python version 3.8.10 (CPython) - Linux-5.4.0-126-generic-x86_64-with-glibc2.29 [debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7 [debug] Proxy map: {} [debug] Using fake IP 84.215.118.247 (NO) as X-Forwarded-For. [NRKTVSeries] broedrene-dal-og-spektralsteinene: Downloading serie JSON 0;31mERROR:0m broedrene-dal-og-spektralsteinene: Failed to parse JSON (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last): File "/opt/git/youtube-dl/youtube_dl/extractor/common.py", line 906, in _parse_json return json.loads(json_string) File "/usr/lib/python3.8/json/**init**.py", line 357, in loads return _default_decoder.decode(s) File "/usr/lib/python3.8/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last): File "/opt/git/youtube-dl/youtube_dl/extractor/common.py", line 906, in _parse_json return json.loads(json_string) File "/usr/lib/python3.8/json/**init**.py", line 357, in loads return _default_decoder.decode(s) File "/usr/lib/python3.8/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/opt/git/youtube-dl/youtube_dl/YoutubeDL.py", line 816, in wrapper return func(self, *args, **kwargs) File "/opt/git/youtube-dl/youtube_dl/YoutubeDL.py", line 837, in __extract_info ie_result = ie.extract(url) File "/opt/git/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract ie_result = self._real_extract(url) File "/opt/git/youtube-dl/youtube_dl/extractor/nrk.py", line 700, in _real_extract series = self._call_api( File "/opt/git/youtube-dl/youtube_dl/extractor/nrk.py", line 60, in _call_api return self._download_json( File "/opt/git/youtube-dl/youtube_dl/extractor/common.py", line 895, in _download_json res = self._download_json_handle( File "/opt/git/youtube-dl/youtube_dl/extractor/common.py", line 881, in _download_json_handle return self._parse_json( File "/opt/git/youtube-dl/youtube_dl/extractor/common.py", line 910, in _parse_json raise ExtractorError(errmsg, cause=ve) youtube_dl.utils.ExtractorError: broedrene-dal-og-spektralsteinene: Failed to parse JSON (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> 
> ## Description
> Started a few weeks ago. Seems it's not able to download series metadata. Manually downloading one episode at a time works ok.
> 
> The series in the example is marked as globally available.

click on the bottom right arrow below the video and copy that URL
and feed that into youtube-dl, the video will now download.

**Comment by dirkf** [comment]
Is that a series URL? If so what is it and how does it differ from the original problem URL?

Anyhow, the problem is that the extractor unnecessarily and wrongly claims to be able to handle Brotli-encoded responses when calling the psapi.nrk.no API. Now, as NRK is taking it at its word, yt-dl doesn't understand the API responses:
```diff
--- old/youtube_dl/extractor/nrk.py
+++ new/youtube_dl/extractor/nrk.py
@@ -60,8 +60,7 @@
         return self._download_json(
             urljoin('https://psapi.nrk.no/', path),
             video_id, note or 'Downloading %s JSON' % item,
-            fatal=fatal, query=query,
-            headers={'Accept-Encoding': 'gzip, deflate, br'})
+            fatal=fatal, query=query)
 
 
 class NRKIE(NRKBaseIE):
```

**Comment by VikingKing** [comment]
I used your patch on my machine and it now works as it should.
Waiting for the patch to enter the git respository.

Thank you for your quick response!
