### ISSUE TITLE
[Arte] Video download fails. Am i doing it wrong? Why does it error out?

### ISSUE THREAD

**Issue by LadyMarmelade** [ytdl-org/youtube-dl#31292]
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ
Could not find FAQ, as https://github.com/ytdl-org/youtube-dl#faq was not working

I do not understand intricacies of web communication, thus could not investigate further.
BTW: I do connect via a VPN regularly, generally, this does not cause problems, also not with youtube-dl.

## Verbose log
```
$ youtube-dl --verbose -k --ignore-config -c https://www.arte.tv/de/videos/096315-000-A/asbest-eine-unendliche-geschichte/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-k', '--ignore-config', '-c', 'https://www.arte.tv/de/videos/096315-000-A/asbest-eine-unendliche-geschichte/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-18-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0
[debug] Proxy map: {}
[ArteTV] 096315-000-A: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

WRITE DESCRIPTION HERE
After watching this, i wanted to grab it (download), but youtube-dl could not. Usually, it does. i cannot tell the difference.

**Comment by dirkf** [comment]
If you don't have GitHub's JS enabled, the FAQ link needs to be https://github.com/ytdl-org/youtube-dl#user-content-faq. However the FAQ can be found from https://github.com/ytdl-org/youtube-dl by searching in the page, if the anchor link fails for any reason.

>I've searched the bugtracker for similar bug reports including closed ones

And yet not found any of the ~10 issues mentioning Arte that are duplicates of this, such as #30919.

>... Usually, it does. ...

Do you mean, say, 9 months ago? Or now, but with other sites?

**Comment by LadyMarmelade** [comment]
Thank you, friend dirkf, for your hints.
Yes, i forgot to reenable JS on github. And yes, after providing the links to video+audio files, i could download them and have ffmpeg make a single file from them. => successfully worked around the issue.

Thx again.
