### ISSUE TITLE
merge thumbnail and video after download

### ISSUE THREAD

**Issue by tsingi** [ytdl-org/youtube-dl#31293]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Is it possible to embed a thumbnail in the video AFTER is has been downloaded?
I have just started using this feature and have many many fixups to do.

**Comment by dirkf** [comment]
Repeat the command you used to download the video, but add `--embed-thumbnail` to the options, and, if you've moved or renamed the video, adjust `-o ...` to match the new path.

**Comment by tsingi** [comment]
I have renamed them, thank you for being thorough.
I can automate that
