### ISSUE TITLE
Received 403 Forbidden on Udemy

### ISSUE THREAD

**Issue by bascom** [ytdl-org/youtube-dl#31299]
Hi, before execution, youtube-dl was updated with youtube-dl -U. The cookie file I used was generated using "cookies.txt" from https://github.com/lennonhill/cookies-txt. The command I ran is as follows:

youtube-dl --cookies ./cookies.firefox-private.txt -o '%(playlist)s/%(chapter_number)s - %(chapter)S/%(playlist_index)s. %(title)s.%(ext)s' https://www.udemy.com/course/coursename --verbose

The debugging data and error are as follows:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', './cookies.firefox-private.txt', '-o', '%(playlist)s/%(chapter_number)s - %(chapter)S/%(playlist_index)s. %(title)s.%(ext)s', 'https://www.udemy.com/course/coursename', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-50-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[udemy:course] course: Downloading webpage
[udemy:course] 1456464: Downloading course curriculum
[download] Downloading playlist: 1456464
[udemy:course] playlist 1456464: Collected 301 video ids (downloading 301 of them)
[download] Downloading video 1 of 301
[udemy] 21082126: Downloading webpage
[udemy] 21082126: Downloading lecture JSON
[udemy] 21082126: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

Thank you for viewing and have a good day.

**Comment by dirkf** [comment]
1. Use the site support template
2. Follow the instructions
3. Find the existing matching issue #30802
4. Follow that issue.
