### ISSUE TITLE
10Play Error

### ISSUE THREAD

**Issue by Brissyite** [ytdl-org/youtube-dl#31302]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17** Done
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones Done
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

PS C:\ytdl> ./youtube-dl https://10play.com.au/the-real-love-boat/episodes/season-1/episode-6/tpv221018hnkus -o "E:\Videos\YTDLFiles\%(title)s-%(id)s.%(ext)s"
[TenPlay] tpv221018hnkus: Downloading JSON metadata
[TenPlay] 9000000000056026: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
The point of the checkboxes is to put `x` inside the `[ ]` 

> I've searched the bugtracker for similar bug reports including closed ones Done

If you actually had done this you would have found #28641, which has the same error, and its recent follow-up #31236.
