### ISSUE TITLE
Unable to extract info section

### ISSUE THREAD

**Issue by Xt0f** [ytdl-org/youtube-dl#31319]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Not able to download a vimeo video with an adress https://player.vimeo.com/video/xxxxxxxxx returning the error **Unable to extract info section**
Thanks for the help.

**Comment by dirkf** [comment]
You didn't search for the (fixed) issue. Closing as incomplete.
