### ISSUE TITLE
youtube-dl archive: ID recorded but not visible

### ISSUE THREAD

**Issue by NguyenVV13** [ytdl-org/youtube-dl#31316]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
> youtube-dl -v --config-location "C:/Program Files/youtube-dl/config.txt" https://www.youtube.com/watch?v=9YjFjaiEEbs
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['--prefer-free-formats', '--no-playlist', '--embed-thumbnail', '--add-metadata', '--postprocessor-args', '-id3v2_version 3', '-x', '--audio-format', 'mp3', '-f', 'bestaudio', '--download-archive', 'C:/Program Files/youtube-dl/archive.txt', '--restrict-filenames', '-o', 'G:/My Drive/Sound/%(playlist)s/%(title)s_%(id)s.%(ext)s', '--sleep-interval', '1']
[debug] Command-line args: ['-v', '--config-location', 'C:/Program Files/youtube-dl/config.txt', 'https://www.youtube.com/watch?v=9YjFjaiEEbs']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: ffmpeg N-107736-g9e029dc265-20220809, ffprobe N-107736-g9e029dc265-20220809
[debug] Proxy map: {}
[youtube] 9YjFjaiEEbs: Downloading webpage
[youtube] Downloading just video 9YjFjaiEEbs because of --no-playlist
[download] Luv U has already been recorded in archive
```

![image](https://user-images.githubusercontent.com/29609356/198788278-415b191a-3819-434d-85d4-4beb21b21a81.png)

## Description

Note: I am running this on a Windows 11 machine with Python 3.10.7. I'm not sure why the debug system information is not consistent with my actual system.

While the verbose output is relevant, the main bug I want to report is the strange interaction with the archive.txt file I have. As you can see from the verbose output, the video was already properly downloaded and recorded in the archive. The odd part is that the actual archive.txt file doesn't have that URL (9YjFjaiEEbs) in it. I attempted to confirmed with a simple search using the find function, as is shown in the provided image.

The noticed that the archive.txt file stopped showing any new video IDs after 600 videos, yet the program says that this video has already been recorded in the archive. I have tried deleting 2-3 lines and downloading new videos to see if the program would try to fill the file back up to 600 videos, but the file doesn't update anymore at all. I've also attempted to write similar Python code to take the file as an argument, open it up, and read and print the entire file contents, and close it, but it doesn't show me anymore than what I could see simply opening the file from the filesystem explorer using Windows Notepad or Notepad++.

As a result of this problem, I can't interact with much of the archive, simply because I don't see all the information in the file, while the program code is apparently able to read and match recorded YouTube IDs that don't seem to exist in the archive.txt file. Is there any way for me to resolve this on my end and be able to see everything? At the very least get new video IDs to properly be appended to the visible archive.txt file contents?

**Comment by dirkf** [comment]
It almost seems that the archive.txt you're looking at isn't the one that yt-dl is using. Might you be looking at an archive.txt.txt file?

Try `find "9YjFjaiEEbs" "C:\Program Files\youtube-dl\archive.txt"`.

**Comment by NguyenVV13** [comment]
My apologies, I forgot to mention this earlier, but I'm using a Windows 11 machine, and I've tried using both this command in Powershell and the same command with the equivalent path on WSL shell and don't think it's running as you intend. I just get an output that is able to find the path of the archive.txt file, but not the ID, as it is not a directory or file.

I believe I'm just using the find command wrong here. Could you clarify with what, where, or how I should use that command?

**Comment by dirkf** [comment]
https://ss64.com/nt/find.html

In WSL (bash?), I suppose `grep 9YjFjaiEEbs 'mnt/c/Program Files/youtube-dl/archive.txt'` but as I only have "Linux Subsystem for Linux" to hand I'm relying on net.examples of how the Windows file name should be represented in WSL.

You do have write permission in this directory? I see that the archive file hasn't been updated since 6 October.

**Comment by NguyenVV13** [comment]
Unfortunately, even the grep output was completely empty. I double checked the write permission in the directory, and saw that I allows admins and users control to read, write, modify, execute in this specific directory, but app packages were lacking write permissions, so I tried giving app packages more permissions and downloading a few more videos, but the file size of archive.txt has not changed at all. Nothing has been appended to the end of the file.

**Comment by dirkf** [comment]
To generate a minimal test case, you could set up a test directory under your home directory and copy the contents of the `archive.txt` into a new `archive.txt` there. Then try basic yt-dl commands using that archive and with only simple options on the command-line (use `--ignore-config` and no `--config-location`).

**Comment by rautamiekka** [comment]
> Unfortunately, even the grep output was completely empty. I double checked the write permission in the directory, and saw that I allowed admins and users control to read, write, modify, execute in this specific directory, but app packages were lacking write permissions. So, I tried giving app packages more permissions and downloading a few more videos, but the file size of archive.txt has not changed at all. Nothing has been appended to the end of the file.

Try
```bash
cat archive.txt | grep '9YjFjaiEEbs'
```
Normally you wouldn't abuse `cat` like this, but it rules out `grep` having a problem trying to read the file: if `cat` by itself reads it just fine and piped into `grep` allows `grep` to read it, it means `grep` has some weird problem reading the file but not reading the stdin.

^ But if `grep` still doesn't show it properly or `cat` fails, it's either at least 1 of those (depending on which fails 1st) or WSL.

**Comment by NguyenVV13** [comment]
This comment will be to address both of the previous feedback comments at once.

I tried using that cat piped to grep command, and it resulted in nothing being returned, so I went to doing the small test cases.
```
cat archive.txt | grep '9YjFjaiEEbs'
```

So what I did is make a new test_archive.txt file in `C:\Users\Cyan\Documents`, where every listed role has full control in the directory by default. I then ran the following command to verbosely download a single video without configs, and record the video ID to the test_archive.txt file I created in Documents:

```
> youtube-dl -v --ignore-config --download-archive "C:\Users\Cyan\Documents\test_archive.txt" -o "C:\Users\Cyan\Documents\%(id)s.%(ext)s" https://www.youtube.com/watch?v=CzEO7pw7oOY
```

This actually worked completely as was intended, downloading the video and appending the new video ID to the archive. I'm not sure what the difference is, since the directory I originally used also allowed all users full control permissions over the directory. So, To test that, I tried making another test_archive.txt file in that directory (i.e. `C:\Program Files\youtube-dl\test_archive.txt). Both files had the same permissions, and were now located in the same directory.

Using that new archive file with simple commands, the program was able to download a video and properly append a new ID to that new archive file.

```
> youtube-dl -v --ignore-config --download-archive "C:\Program Files\youtube-dl\test_archive.txt" -o "C:\Program Files\youtube-dl\%(id)s.%(ext)s" https://www.youtube.com/watch?v=IHq0axdz17Q
```

When I tried using the same command but with a different, new video ID on the old archive, everything properly downloaded, but the archive was not updated.

```
> youtube-dl -v --ignore-config --download-archive "C:\Program Files\youtube-dl\test_archive.txt" -o "C:\Program Files\youtube-dl\%(id)s.%(ext)s" https://www.youtube.com/watch?v=kFAEjRwfjWk
```

As a result of this, I believe this might just be a file issue and I may simply need to use a new file to continue updating the archive. I'm no longer sure how valid this bug ticket is.

**Comment by rautamiekka** [comment]
> I tried using that cat piped to grep command, and it resulted in nothing being returned, so I went to doing the small test cases.

So the pipeline is broken altogether. Typical Micro$hit.

**Comment by NguyenVV13** [comment]
Well, I used WSL to run that line specifically, so I'm not sure how different that would be.

**Comment by NguyenVV13** [comment]
I just attempted to run the original line from the initial ticket issue comment (tested with both a single video URL as well as a playlist URL), and the program seems to work completely fine with the newly created archive file.

Since the bug can't be reproduced with a new archive file. I'm just going to close the issue. I apologize that this ended up being more of a testing session than debugging, but I appreciate all the help, regardless.

**Comment by dirkf** [comment]
The Unix-y bit is Ubuntu, so it would be sCatogical rather than Micro$hit. I think it was just the WTF-ish character of OP's environment in this case.

**Comment by rautamiekka** [comment]
Might be an env problem. If M$ repurposed Ubuntu, it's more likely M$' problem than Canonical's, but then again I wouldn't use WSL when I can use Cygwin or the like, or a VM.
