### ISSUE TITLE
Cant dl a video on youtube

### ISSUE THREAD

**Issue by jonyjones** [ytdl-org/youtube-dl#31310]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -f 134+140 --verbose https://www.youtube.com/w5atch?v=yD3tGQvlAI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '134+140', '--verbose', 'https://www.youtube.com/w5atch?v=yD3tGQvlAI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.72-xanmod1-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] w5atch: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
```

## Description

Have downloaded many video on youtube but this one trigger error, i would tell you how to fix if i know, i writing this because https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient say to include 
    What the problem is
    How it could be fixed
    How your proposed solution would look like
and If your report is shorter than two lines, it is almost certainly missing some of these
But its a few word problem, sorry

**Comment by dirkf** [comment]
> I've checked that all provided URLs are alive and playable in a browser

Really? You appear to have a `5` in the `watch` part of the URL. It should be removed.

**Comment by dirkf** [comment]
I assume you wanted `5yD3tGQvlAI`, titled "JANUS 2 : Pedro Nunes, Tycho Brahe, Johannes Kepler".

**Comment by jonyjones** [comment]
sorry for taking your time for such mistake :{
