### ISSUE TITLE
Build Issue after last commit

### ISSUE THREAD

**Issue by atvcaptain** [ytdl-org/youtube-dl#31324]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
|   File "/home/oe1/atv64/build-enviroment/builds/openatv/release/et10000/tmp/work/mips32el-oe-linux/python-youtube-dl/gitAUTOINC+087ddc2371-r0/git/youtube_dl/casefold.py", line 1642, in <lambda>
|     _parse_unichr = lambda s: compat_chr(int(s, 16))
| ValueError: unichr() arg not in range(0x10000) (narrow Python build)
|     _parse_unichr = lambda s: compat_chr(int(s, 16))
| ValueError: unichr() arg not in range(0x10000) (narrow Python build)
| make: *** [Makefile:100: youtube-dl.bash-completion] Error 1
```

## Description

with commit https://github.com/ytdl-org/youtube-dl/commit/a874871801b8b05d06e8ffe52bed94fdfc26611e
youtube-dl.bash-completion stop build

**Comment by dirkf** [comment]
I wonder which Python build you have.

This is probably happening because your Python is built without wide character support. I wondered if that would still be a problem and it appears that you have helpfully provided the answer. There is a known solution, though:
```diff
--- old/youtube_dl/casefold.py
+++ new/youtube_dl/casefold.py
@@ -1639,7 +1639,11 @@
 1E921; C; 1E943; # ADLAM CAPITAL LETTER SHA
 '''
 
-_parse_unichr = lambda s: compat_chr(int(s, 16))
+def _parse_unichr(s):
+    try:
+        return compat_chr(int(s, 16))
+    except ValueError:
+        return ('\\U' + ('0000000' + s)[-8:]).decode('unicode-escape')
 
 _map = dict(
     (_parse_unichr(from_), ''.join(map(_parse_unichr, to_.split(' '))))
```

**Comment by atvcaptain** [comment]
this is my legacy build python 2.7 i use openembedded build System zeus, my build with py3.9/3.10 and 3.11 have np
thx for  quick fix

**Comment by dirkf** [comment]
The original version worked on my embedded 2.7.1 Python that was built 10+ years ago, so I hoped to get away without a work-around!

Actually there doesn't seem to be any significant performance difference between these three as measured by running `time python test/test_compat.py`:
* the original wide char code
* the patch above with `raise ValueError` forced in the `try` suite
* the final commit using `'\\U%08x' % int(s, 16)`, again with forced `ValueError`.
