### ISSUE TITLE
Please add support for bunkr.is

### ISSUE THREAD

**Issue by vallerydelexy** [ytdl-org/youtube-dl#31334]
## Checklist
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs
- Single video: https://stream.bunkr.is/v/miera2000-(18)-xXmlmXQU.mp4
- Playlist: https://bunkr.is/a/69cAqfw0

**Comment by dirkf** [comment]
Media parameters are found in the Next.js hydration JSON. In this case, and probably all the others, the media link is https://media-files.bunkr.is/miera2000-(18)-xXmlmXQU.mp4 which is a straightforward transformation of the problem URL.

**Comment by dirkf** [comment]
The page structure no longer uses Next.js and there seems to be no metadata that could be extracted. The Generic extractor works fine for individual pages, or you can just download from the button.

The album (playlist) page would be easy to handle but a separate URL-based extractor seems overkill and I'd like to hold off on adding random additional sites to the Generic extractor. The only metadata here is thumbnails.

**Comment by mostafahanafi** [comment]
@dirkf I just realized the individual pages have a download button so there really is no point for an extractor, I saw the issue as a good first issue so I thought I'd try working on it but now I've realized it's unnecessary really

**Comment by dirkf** [comment]
Indeed, it was a GFI when created but the site has changed.

**Comment by dirkf** [comment]
All 404 now?
