### ISSUE TITLE
please add support for shooshtime.com

### ISSUE THREAD

**Issue by vallerydelexy** [ytdl-org/youtube-dl#31332]
## Checklist
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://shooshtime.com/videos/284002/just-out-of-the-shower-joi/
- Playlist: https://shooshtime.com/pornstars/banaqwa/

**Comment by dirkf** [comment]
The media details are in a JSON assigned like so `var flashvars = {...}`. The media link is like `https://shooshtime.com{flashvars['video_url']}?rnd={flashvars['rnd']}` which can be fetched using the original URL as `Referer`. Additional metadata can be scraped from the page.

**Comment by dirkf** [comment]
Needs a small update to the new KVS player extraction in the generic extractor.

**Comment by dirkf** [comment]
If support for playlists is needed, please reopen.
