### ISSUE TITLE
Can't download rom 

### ISSUE THREAD

**Issue by hcgrove** [ytdl-org/youtube-dl#31346]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [xI've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tv2ostjylland.dk/nyhedsudsendelser?clip=326b07d8-b4fc-4e4e-be3a-c807ba5832e9']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-18-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0
[debug] Proxy map: {}
[TV2DK] nyhedsudsendelser: Downloading webpage
ERROR: Unable to extract kaltura id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/grove/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/grove/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/grove/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/grove/bin/youtube-dl/youtube_dl/extractor/tv2dk.py", line 93, in _real_extract
    kaltura_id = self._search_regex(
  File "/home/grove/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract kaltura id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I tried to download 'https://www.tv2ostjylland.dk/nyhedsudsendelser?clip=326b07d8-b4fc-4e4e-be3a-c807ba5832e9' ((a part of) a news broadcast in danish), it didn't work, and youtube-dl said to report it, so I'm doing so.

When I clicked the "New issue" button on the github page that I was redirected to from the link youtube-dl had outputted, I was asked to choose between 6 categories, as I've succesfully used this version of youtube-dl many times to download from other sites, I guess that the issue is related to the support of this particular site, and hope I've chosen the right category by that. If not you can move this issue or close it as you see fit.

**Comment by hcgrove** [comment]
This had gotten a stupid title through some copy-paste error. I'll make a new issue with a better title.

**Comment by 89z** [comment]
you can just edit the title...

**Comment by dirkf** [comment]
You should have been able to edit the title, anyway.
