### ISSUE TITLE
Youtube directlink does not work

### ISSUE THREAD

**Issue by HeroHann** [ytdl-org/youtube-dl#31341]
Hello,
I have tried different sub options but never got it to run properly.
Youtube-dl -g (URL)
I am getting links like:
https://rr3---sn-5hne6ns6.googlevideo.com/videoplayback?expire=1668118744&ei=eCRtY7yAE6WJ6dsPidS2-AI&ip=81.209.189.70&id=o-APoqV2lngEXIaeTL4OdftNnBE2QFaVmFluCFPhia2mbF&ita
g=251&source=youtube&requiressl=yes&mh=Bh&mm=31%2C29&mn=sn-5hne6ns6%2Csn-5hneknee&ms=au%2Crdu&mv=m&mvi=3&pl=22&initcwndbps=793750&spc=SFxXNngyHKQ2iZLdBxnnussEtnJ-AZo&vprv=
1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=21803127&dur=1292.481&lmt=1650693138260344&mt=1668096796&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&spara
ms=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALE8E3rHoaMgfgSV0yuI0k_2Sg2Fvbn1P2a7QzoNgOtcAiBI
a5XRN8FgOb6-6RbsQ-i0AaWcZl1gcgiAcHLKMathGw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgQBVdK05gZHqWmsSauoP05UO1gJu-Qqqznvb30ofbL7gCIHhb
n5a7Q_x8Io1ds2h_7cxVIow22MNmvE0TnQQdcBTT

Problem: I cannot copy this link to my browser or other downloaders. It just reports a blank page.

Question: How can I use youtube-dl to get a direct link to any youtube video?
Thanks!

**Comment by october262** [comment]
> direct link to any youtube video



> Hello, I have tried different sub options but never got it to run properly. Youtube-dl -g (URL) I am getting links like: https://rr3---sn-5hne6ns6.googlevideo.com/videoplayback?expire=1668118744&ei=eCRtY7yAE6WJ6dsPidS2-AI&ip=81.209.189.70&id=o-APoqV2lngEXIaeTL4OdftNnBE2QFaVmFluCFPhia2mbF&ita g=251&source=youtube&requiressl=yes&mh=Bh&mm=31%2C29&mn=sn-5hne6ns6%2Csn-5hneknee&ms=au%2Crdu&mv=m&mvi=3&pl=22&initcwndbps=793750&spc=SFxXNngyHKQ2iZLdBxnnussEtnJ-AZo&vprv= 1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=21803127&dur=1292.481&lmt=1650693138260344&mt=1668096796&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&spara ms=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALE8E3rHoaMgfgSV0yuI0k_2Sg2Fvbn1P2a7QzoNgOtcAiBI a5XRN8FgOb6-6RbsQ-i0AaWcZl1gcgiAcHLKMathGw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgQBVdK05gZHqWmsSauoP05UO1gJu-Qqqznvb30ofbL7gCIHhb n5a7Q_x8Io1ds2h_7cxVIow22MNmvE0TnQQdcBTT
> 
> Problem: I cannot copy this link to my browser or other downloaders. It just reports a blank page.
> 
> Question: How can I use youtube-dl to get a direct link to any youtube video? Thanks!

try with youtube-dl --get-url "https://www.youtube.com/watch?v=ZuRLOlB4N8U"

**Comment by dirkf** [comment]
That looks like what OP did. But the links expire. If you select a format with separate video and audio streams, you get two URLs.

When passing the URL(s) to other command-line applications, ensure the URL is quoted to avoid the embedded `&` being interpreted by the shell (Windows cmd: "URL"; POSIX: 'URL').

**Comment by dirkf** [comment]
Closing for lack of response. Re-open with new info.
