### ISSUE TITLE
enable color in bash output redirection mode

### ISSUE THREAD

**Issue by light-and-ray** [ytdl-org/youtube-dl#31344]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I use this command to pass stderr throught tee ([link](https://github.com/ytdl-org/youtube-dl/issues/31167#issuecomment-1310469894))
`youtube-dl "$@" 2> >(tee "$tmp" >&2)`

But for this mode youtube-dl disables color, and there is not any flag to enable it. Can you add a flag opposite of `--no-color`. E.g. just `--color` or like grep's `--color=always`

**Comment by dirkf** [comment]
Coloured warning and error diagnostics are only included when the output is to a device that yt-dl thinks will understand them. This currently means a non-Windows TTY device.

yt-dlp now supports coloured output with a sufficiently recent Windows shell.

Unless someone makes a PR for this yt-dl is unlikely to be changed, but your desire is not new: maybe one of the more plausible suggestions [here](https://unix.stackexchange.com/questions/249723/how-to-trick-a-command-into-thinking-its-output-is-going-to-a-terminal) will help.

**Comment by light-and-ray** [comment]
> yt-dlp now supports coloured output with a sufficiently recent Windows shell.

No, I do not need windows. I think it is good idea to add a flag for manual selection of color mode

Why exists yt-dlp? Is it superstructure of youtube-dl, or fork?

> Unless someone makes a PR for this yt-dl is unlikely to be changed

Hmm. You commit almost everyday, but the last release is 2021.12.17 🤔

Sorry if I misunderstand something

**Comment by light-and-ray** [comment]
> maybe one of the more plausible suggestions [here](https://unix.stackexchange.com/questions/249723/how-to-trick-a-command-into-thinking-its-output-is-going-to-a-terminal) will help.

Unfortunately in the case with `unbuffer` is problem, the process isn't terminated when my script is nested, and I kill it. For other tools, I don't know. Maybe I will try them, thanks

**Comment by rautamiekka** [comment]
> Why exists yt-dlp? Is it superstructure of youtube-dl, or fork?

A Python 3 fork superior in every way.

**Comment by dirkf** [comment]
Now it's a Python 3.7 fork ...

Perhaps I should have written "someone **else**"?

**Comment by pukkandan** [comment]
Related https://github.com/yt-dlp/yt-dlp/issues/3643

**Comment by pukkandan** [comment]
@dirkf Could you elaborate why this is "wont-fix"? Did you only mean that you would not work on this, or that such a feature will not be merged at all? In the latter case, I would like to know the reasoning

**Comment by dirkf** [comment]
I thought https://github.com/ytdl-org/youtube-dl/issues/31344#issuecomment-1311634998 covered it, ie that I wasn't interested myself, and there are external workarounds. As to merging a PR it would depend on how much complexity was added.
