### ISSUE TITLE
I can't download the video with maximum resolution in bilibili.

### ISSUE THREAD

**Issue by teddy171** [ytdl-org/youtube-dl#31345]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

When I use youtube-dl to download videos on bilibili (https://www.bilibili.com/video/BV1Hg411B7iR/), and I also logged in(the command is ```youtube-dl -u <my username> -p <my password> "https://www.bilibili.com/video/BV1Hg411B7iR/")```, but it still download in 360P . How to solve it?

**Comment by dirkf** [comment]
The yt-dlp extractor finds the avc, av01 and aac formats at video including 480p and possibly 1080p if you're logged in. Here's a quick back-port of that extractor doing the same in yt-dl:
```shellsession
$ python -m youtube_dl -v -F 'https://www.bilibili.com/video/BV1Hg411B7iR/'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.bilibili.com/video/BV1Hg411B7iR/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: fdb16c0d6
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[BiliBili] 1Hg411B7iR: Downloading webpage
[BiliBili] BV1Hg411B7iR: Extracting videos in anthology
[BiliBili] Formats 1080P 高清, 720P 高清 are missing; you have to login or become premium member to download them
[BiliBili] 517297060: Extracting chapters
[info] Available formats for BV1Hg411B7iR:
format code  extension  resolution note
0            m4a        audio only   67k , mp4a.40.2
1            m4a        audio only  129k , mp4a.40.2
2            m4a        audio only  129k , mp4a.40.2
3            mp4        640x360      42k , avc1.64001E, 25.0fps, video only
4            mp4        640x360      53k , av01.0.08M.08.0.110.01.01.01.0, 25.039fps, video only
5            mp4        852x480      68k , avc1.64001F, 25.0fps, video only
6            mp4        852x480      74k , av01.0.08M.08.0.110.01.01.01.0, 25.039fps, video only (best)
$
```
However I can't push this without a few changes to the underlying framework that would need to be properly implemented and validated.

**Comment by teddy171** [comment]
Why I don't have the same output as you?
```zsh
% python -m youtube_dl -v -F 'https://www.bilibili.com/video/BV1Hg411B7iR/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.bilibili.com/video/BV1Hg411B7iR/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.11 (CPython) - macOS-12.6-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, phantomjs 2.1.1
[debug] Proxy map: {}
[BiliBili] 1Hg411B7iR: Downloading webpage
[BiliBili] 1Hg411B7iR: Downloading video info page
[info] Available formats for 1Hg411B7iR:
format code  extension  resolution note
0            mp4        unknown    18.24MiB
```

**Comment by dirkf** [comment]
You aren't using my modified extractor code, since I didn't publish it!

**Comment by xkszltl** [comment]
@dirkf 
Just for curiosity, do you happen to know the key difference in yt-dlp and youtube-dl's way of extraction?
Did it get the info via another protocol or API?

**Comment by dirkf** [comment]
Fundamentally, yt-dl used different (presumably historic) API URLs and did a lot less around them. yt-dlp gets JSON from the page and then uses https://api.bilibili.com/x/player/pagelist. yt-dl relies on http://bangumi.bilibili.com/web_api/get_source and http://interface.bilibili.com/v2/playurl.

**Comment by dirkf** [comment]
According to https://github.com/yt-dlp/yt-dlp/issues/5655, 1080p formats may be available in a browser session but not found by yt-dlp from the browser cookies. We also need to include whatever is the resolution of that issue.

**Comment by dirkf** [comment]
https://github.com/yt-dlp/yt-dlp/issues/5655#issuecomment-1329898952.

**Comment by dirkf** [comment]
Apparently this will be the result after back-porting from yt-dlp: https://github.com/yt-dlp/yt-dlp/issues/5655#issuecomment-1329942574.

The yt-dlp extraction doesn't appear to find the low res combined mp4 that the yt-dl extractor finds.
