### ISSUE TITLE
sportdeutschland.tv unable to download JSON metadata

### ISSUE THREAD

**Issue by matthiasliermann** [ytdl-org/youtube-dl#31351]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
python -m youtube_dl --verbose  https://sportdeutschland.tv/dtb/bundesfinale-rendezvous-besten-2022
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://sportdeutschland.tv/dtb/bundesfinale-rendezvous-besten-2022']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 195f22f67
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-52-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[SportDeutschland] dtb/bundesfinale-rendezvous-besten-2022: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/matthias/Videos/YouTube/youtube-dl/youtube_dl/extractor/common.py", line 635, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/matthias/Videos/YouTube/youtube-dl/youtube_dl/YoutubeDL.py", line 2300, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

```

## Description

I would like to download a video from sportdeutschland.tv, for which an extractor exists, but it doesn't work. There seem to be similar issues with other sites, like this one: https://github.com/ytdl-org/youtube-dl/issues/28906, but I wouldn't know how to fix that.

**Comment by dirkf** [comment]
Well, no, #28906 hasn't got anything to do with Sportdeutschland. Many extractors try to download JSON as part of the extraction process and any of those attempts may end up with a 404 error, meaning that the JSON we wanted isn't there, but the reason will be specific to the site (unless some sort of censorship proxy is involved).

But #30348 **is** the same issue, and I posted a patch for it that no-one, including me, has bothered to progress.

**Comment by matthiasliermann** [comment]
Hi  @dirkf . I tried to use your fork, but it didn't work either. You said that it wasn't progressed by neither yourself or anyone else. Thank you for your work, anyhow. I would be glad to know once this works.
