### ISSUE TITLE
Problem to merge video and audio file - I get a m4a file instead of a mp4 file

### ISSUE THREAD

**Issue by nico9480** [ytdl-org/youtube-dl#31359]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I want to download a private vimeo video but with the standard command I have no sound in the downloaded file.
I only get the m4a file instead of having a mp4 file.
I read a lot of posts to be able to solve that without total success.

I tried to use the "bestvideo[ext=mp4]+bestaudio[ext=mp4]" option in order to download both video and audio then to
merge it together.
As you can see in the logs below, the files are downloaded but the destination file is an m4a file (audio only) regardless of the bestvideo and bestaudio format choosen.

Thinking being able to force the destination format to mp4 I tried with the "--merge-output-format mp4" command but I faced the same result.

I can see in the logs that the video files on disk are erased after the post-processing, even the mp4 one I want to keep. 
So I decided to use the "-k" option as mentioned in the log to skip this erase. In that way I succeed in getting the mp4 merged file with both the video and audio in the same file.

here are the files I get with and without the "-k" option :
![youtube-dl](https://user-images.githubusercontent.com/118371843/202230619-ba845682-2306-4580-a134-9bcad3a56c7a.png)

I don't understand why and how ffmpeg set this format (m4a) for the destination file and deletes the others, especially that the two fomats video and audio are dowloaded in mp4 format.

I could do it like that and manually remove the useless files but the url is a vimeo showcase with many videos and dynamically updated (videos are often added to the showcase).
I would like to avoid doing this every time.

Do you know how I can fix this behavior ?

Thank you

## Verbose log
```shell
[debug] System config: []
[debug] User config: ['-x', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:\\Users\\NBR\\Downloads\\test\\%(title)s.%(ext)s', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=mp4]', '--video-password', 'PRIVATE', '-v', 'https://vimeo.com/showcase/9905670']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-91693-g3aacb0d196, ffprobe N-91693-g3aacb0d196
[debug] Proxy map: {}
[vimeo:album] 9905670: Downloading JSON metadata
[vimeo:album] 9905670: Downloading JSON metadata
[vimeo:album] 9905670: Verifying the password
[download] Downloading playlist: NOVEMBER 2022 FOLDER
[vimeo:album] 9905670: Downloading page 1
[vimeo:album] playlist NOVEMBER 2022 FOLDER: Downloading 9 videos
[download] Downloading video 1 of 9
[vimeo] 771375749: Downloading webpage
[vimeo] 771375749: Downloading JSON metadata
[vimeo] 771375749: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 771375749: Downloading fastly_skyfire m3u8 information
[vimeo] 771375749: Downloading fastly_skyfire m3u8 information
[vimeo] 771375749: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 771375749: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 771375749: Downloading fastly_skyfire MPD information
[vimeo] 771375749: Downloading fastly_skyfire MPD information
[vimeo] 771375749: Downloading akfire_interconnect_quic MPD information
[vimeo] 771375749: Downloading akfire_interconnect_quic MPD information
[debug] Invoking downloader on 'https://skyfire.vimeocdn.com/1668618811-0x7fe3424fd9a1afbf59910183ecd38a7854640c29/25dd3dc4-22d6-47ac-9039-d005ae2be26e/sep/video/09baab66,02b31208,f339a23e,4bab6b0e/audio/3c8e7e57,9be72696,df38dc83/master.mpd?query_string_ranges=1&base64_init=1'
[dashsegments] Total fragments: 330

[download] Destination: C:\Users\NBR\Downloads\test\VIDEOTEST 11_15.fdash-fastly_skyfire_sep-video-4bab6b0e.mp4
[download] 100% of 173.32MiB in 00:25
[debug] Invoking downloader on 'https://skyfire.vimeocdn.com/1668618811-0x7fe3424fd9a1afbf59910183ecd38a7854640c29/25dd3dc4-22d6-47ac-9039-d005ae2be26e/sep/audio/df38dc83/playlist.m3u8?query_string_ranges=1'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 330

[download] Destination: C:\Users\NBR\Downloads\test\VIDEOTEST  11_15.fhls-fastly_skyfire_sep-audio-high-audio.mp4
[download] 100% of 46.94MiB in 00:17

[ffmpeg] Merging formats into "C:\Users\NBR\Downloads\test\VIDEOTEST 11_15.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\NBR\Downloads\test\VIDEOTEST 11_15.fdash-fastly_skyfire_sep-video-4bab6b0e.mp4" -i "file:C:\Users\NBR\Downloads\test\VIDEOTEST 11_15.fhls-fastly_skyfire_sep-audio-high-audio.mp4" -c copy -map "0:v:0" -map "1:a:0" "file:C:\Users\NBR\Downloads\test\VIDEOTEST 11_15.temp.mp4"
**Deleting original file C:\Users\NBR\Downloads\test\VIDEOTEST 11_15.fdash-fastly_skyfire_sep-video-4bab6b0e.mp4 (pass -k to keep)
Deleting original file C:\Users\NBR\Downloads\test\VIDEOTEST 11_15.fhls-fastly_skyfire_sep-audio-high-audio.mp4 (pass -k to keep)**
[debug] ffmpeg command line: ffprobe -show_streams "file:C:\Users\NBR\Downloads\test\VIDEOTEST 11_15.mp4"

[ffmpeg] Destination: C:\Users\NBR\Downloads\test\VIDEOTEST 11_15.m4a
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\NBR\Downloads\test\VIDEOTEST 11_15.mp4" -vn -acodec copy "-bsf:a" aac_adtstoasc "file:C:\Users\NBR\Downloads\test\VIDEOTEST 11_15.m4a"
**Deleting original file C:\Users\NBR\Downloads\test\VIDEOTEST 11_15.mp4 (pass -k to keep)**
```

**Comment by dirkf** [comment]
1. `bestaudio` and `[ext=mp4]` are contradictory in principle, but yt-dl treats mp4 as m4a in this case.
2. The real issue is that you have `-x` = `--extract-audio` in your config. Remove it or use `--ignore-config`.

**Comment by nico9480** [comment]
Hello,
Thank you, I will try by removing the "-x" option. 
For the first point I did it because when I listed all the available format I saw that audio was in m4a and mp4. But ok, I understand your point.
Thank you.

**Comment by dirkf** [comment]
Let us know if that solves your problem: I do expect it will.

**Comment by nico9480** [comment]
It's working! Thank you very much.
Finnaly I have removed the config file as it is useless for now in my usages.
And I changed the bestaudio to [ext=m4a].
