### ISSUE TITLE
fifa.com/fifaplus

### ISSUE THREAD

**Issue by yossibiton** [ytdl-org/youtube-dl#31365]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.fifa.com/fifaplus/en/watch/6AjOEGNzaU8A7zVv4gE8hL

## Description

World cup highlights

**Comment by dirkf** [comment]
yt-dlp has a FIFA extractor that appears to do what is needed. I made a test back-port from that module. In yt-dl and yt-dlp, tests 1 and 2 pass, but test 3 and your example URL give this:
```
...
[Fifa] 3C6gQH9C2DLwzNx7BMRQdp: Downloading Content Data
ERROR: [Fifa] 3C6gQH9C2DLwzNx7BMRQdp: Unable to download JSON metadata: HTTP Error 403: Forbidden ...
```
This also happens with (eg) yesterday's Spain v Germany highlights.

Possibly cookies from a logged-in browser session need to be passed for these (newer?) pages.

**Comment by dirkf** [comment]
No, the order of the query parameters has to be exactly as the site expects:
```shell
$ pytest -k Fifa
============================= test session starts ==============================
platform linux2 -- Python 2.7.18, pytest-4.6.11, py-1.11.0, pluggy-0.13.1
rootdir: /home/df/Documents/src/youtube-dl
collected 2647 items / 2644 deselected / 3 selected                            

test/test_download.py ...                                                [100%]

================== 3 passed, 2644 deselected in 25.04 seconds ==================
$
```
