### ISSUE TITLE
Error 404 JSON Download of bible.tv

### ISSUE THREAD

**Issue by OWC-zer0de** [ytdl-org/youtube-dl#31378]
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

Provide the complete verbose output of youtube-dl that clearly demonstrates the problem.
Add the `-v` flag to your command line you run youtube-dl with (`youtube-dl -v <your command line>`), copy the WHOLE output and insert it below. It should look similar to this:
[debug] System config: []
[debug] User config: ['-o', './tubes/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '-v', 'https://www.bibeltv.de/mediathek/videos/305315-pilot-1-2']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-132-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Proxy map: {}

@Odin ~ $ youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' -v "https://www.bibeltv.de/mediathek/videos/305315-pilot-1-2" 

[brightcove:new] ref:305315: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

## Description

youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' -v "https://www.bibeltv.de/mediathek/videos/305315-pilot-1-2"

**Comment by dirkf** [comment]
The hydration JSON metadata says `'drm': true`. Please check whether you can play the video in your [browser with DRM disabled](https://www.google.com/search?q=Chrome+disable+DRM&tbs=li:1&num=10&gl=us&hl=en&ucbcb=1).

**Comment by Vangelis66** [comment]
The service is geo-locked to **German** IPs; they check your IP address via 
https://www.bibeltv.de/mediathek/api/geo
and if `!=DE`, you get:
```
Video nicht verfügbar
Dieses Video ist leider aus lizenzrechtlichen Gründen in Ihrem Land nicht verfügbar
```
If that hurdle is bypassed (whitelisted DE IP), you get below result if **EME/DRM** has been temporarily **disabled**: 

![bibeltv](https://user-images.githubusercontent.com/9669492/204070531-c8f556ef-479a-4a00-83f2-2aad952253a5.PNG)

If EME/DRM is **enabled**, you get served a MPEG-DASH manifest with **cenc**: 
```
https://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/bccenc/6415507950001/6920d62d-d995-46d8-8c86-318a0fe90cb7/6s/manifest.mpd?fastly_token=NjM4MWMzZWFfYjYyMzU2YTk4MjdjYjM4MmE4MDNjZWE5MDVhYzY2ZTk2MDMxMWJjMTM5N2ZhMzE3MzJhMmY2NjFkMzhkMjlmNQ%3D%3D
```
(supposedly, `bccenc` stands for **B**right**C**ove **C**ommon **E**ncryption); as I have said in other "similar" issues, we have already entered the era of "DRM-everywhere" 😠 😡 ...
Unless some way is found to retrieve streams with softer encryption (ClearKey/AES128), this is another **dead end** as far as `yt-dl` is concerned...
OT: I used to be a fan of that series (Highway to Heaven) when it was current (mid to late 1980s) 😉 ...

**Comment by dirkf** [comment]
Less OT, currently S1E16 on "Great!TV" (nothing newer than 2000 channel, formerly "Sony Channel") in the UK, possibly accessible from Central Europe: https://www.lyngsat.com/tvchannels/uk/Great-TV.html. Only "encrypted" by having no DE audio or subtitles.

OP may experience dissatisfaction with a search for the show auf Deutsch as the title matches a 2001 porno.

But apparently bibeltv.de is a no-go unless someone finds otherwise.
