### ISSUE TITLE
IPV6 proxy does not work

### ISSUE THREAD

**Issue by bjut-hz** [ytdl-org/youtube-dl#31388]
I have a IPV6 proxy, command as follow:

youtube-dl --proxy **user_name:password@[IPV6 addr]:port** --skip-download --no-playlist --print-json --no-check-certificate https://www.youtube.com/watch?v=zPwnYItGeLQ --verbose

but it seemed to does not work. How should I do? 
I guess whether youtube-dl does not support ipv6 address or I do not get a correct command format?

**Comment by october262** [comment]
try adding --force-ipv6 to your command and see if that works.

**Comment by bjut-hz** [comment]
> 

no, still does not work..

**Comment by october262** [comment]
try the tips here - https://askubuntu.com/questions/210410/how-to-run-youtube-dl-through-proxy-server

**Comment by dirkf** [comment]
>       --proxy URL
>              Use  the  specified  HTTP/HTTPS/SOCKS  proxy.   To  enable SOCKS
>              proxy,    specify    a    proper    scheme.      For     example
>              socks5://127.0.0.1:1080/. ...

Eg,
```diff
-youtube-dl --proxy user_name:password@[IPV6 addr]:port --skip-download --no-playlist --print-json --no-check-certificate https://www.youtube.com/watch?v=zPwnYItGeLQ --verbose
+youtube-dl --proxy 'http://user_name:password@IPV6_addr:port' --skip-download --no-playlist --print-json --no-check-certificate 'https://www.youtube.com/watch?v=zPwnYItGeLQ' --verbose
```
Paste an actual complete log of the error (redacted as desired) for further help.

The askubuntu page is a bit out of date but as I understand it (not using a proxy) basically accurate; I guess that what was `--cn-verification-proxy` is now `--geo-verification-proxy`:
>       --geo-verification-proxy URL
>              Use this proxy to verify the IP address for some  geo-restricted
>              sites.   The default proxy specified by --proxy (or none, if the
>              option is not present) is used for the actual downloading.

**Comment by dirkf** [comment]
Use `--verbose` and include the *actual command line*: redact authentication and/or IPv6 address as desired, but ideally without masking the structure of the command and parameters. Also, put your log inside a pair of triple backquotes to avoid random line wrapping.

**Comment by bjut-hz** [comment]
the real command is:

**Comment by dirkf** [comment]
That's an option when building the interpreter. You can run this to see the value:
```
python -c 'import socket;print(socket.has_ipv6)'
```

The format of your proxy URL seems OK. Do you have another application that uses the proxy successfully? Try accessing YouTube with your browser via the IPv5 proxy. 502 means "Bad gateway", so there may be a problem in the proxy.

The verbose log should include the whole output, not just the error and backtrace.

**Comment by bjut-hz** [comment]
value of `python` -c 'import socket;print(socket.has_ipv6)'  is `True`

The proxy worked well in curl command..

the whole output is:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--proxy', u'http://xxxx:xxxxx@[xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:xxxx', u'--skip-download', u'--no-playlist', u'--print-json', u'--verbose', u'--no-check-certificate', u'http://www.youtube.com/watch?v=zPwnYItGeLQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.9 (CPython) - Linux-5.4.143.bsk.5-sign-amd64-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1
[debug] Proxy map: {u'http': u'http://xxxx:xxxxx@[xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:xxxx', u'https': u'http://xxxx:xxxxx@[xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:xxxx'}
ERROR: Unable to download API page: HTTP Error 502: No video id found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by october262** [comment]
in your command, try adding s to http - https, see what that does

**Comment by bjut-hz** [comment]
> That's an option when building the interpreter. You can run this to see the value:
> 
> ```
> python -c 'import socket;print(socket.has_ipv6)'
> ```
> 
> The format of your proxy URL seems OK. Do you have another application that uses the proxy successfully? Try accessing YouTube with your browser via the IPv5 proxy. 502 means "Bad gateway", so there may be a problem in the proxy.
> 
> The verbose log should include the whole output, not just the error and backtrace.

I have solved the question.. There is another proxy called A behind my specific proxy, and the error occured when the specific proxy connected proxy A. When I changed another ipv6 proxy, youtue-dl worked fine. Thanks a lot, best wishes !!!

**Comment by dirkf** [comment]
[It's proxies all the way down](https://quoteinvestigator.com/2021/08/22/turtles-down/).
