### ISSUE TITLE
How can I download what seems to be closed captions with this video?

### ISSUE THREAD

**Issue by PaddyDHurley** [ytdl-org/youtube-dl#31399]
## Checklist

- [X ] I'm asking a question
- [X ] I've looked through the README and FAQ for similar questions
- [X ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

How can I download what seems to be closed captions with this video?    I have tried to use other's suggestions but can't seem to make it work.

https://www.youtube.com/watch?v=bCkL5gHn3_k&t=30s

**Comment by dirkf** [comment]
The video has these subtitles according to `--list-subs` (json3 won't be seen by yt-dl current release):
```
en       vtt, ttml, srv3, srv2, srv1, json3
```
Use `--write-sub --sub-lang en --sub-format vtt` (or whichever format you want); add (eg) `--convert-subs srt` if you want yt-dl to convert the subtitle file to `srt` format.

If you can't make it work, post your (text format) command and output for further help.

**Comment by dirkf** [comment]
>If you can't make it work, post your (text format) command and output for further help.

Last chance.

**Comment by dirkf** [comment]
See #32102.
