### ISSUE TITLE
Video title causes "[Errno 92] Illegal byte sequence"

### ISSUE THREAD

**Issue by exboreas** [ytdl-org/youtube-dl#31395]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vU', 'https://www.youtube.com/watch?v=27rKhzGG1dM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.15 (CPython) - macOS-12.2.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
[debug] Proxy map: {}
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
[youtube] 27rKhzGG1dM: Downloading webpage
[youtube] 27rKhzGG1dM: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://rr7---sn-cn3tc-aigr.googlevideo.com/videoplayback?expire=1670083484&ei=PB-LY-LWC-zwsALDl7mQCg&ip=2a02%3Ac7c%3A5c48%3Ab800%3Ac432%3A64b6%3Ade11%3Ad9e7&id=o-AMtvLoiHyvPdccsjJ1R_sstRUUYRB3cI3FhvYgK3JJ9_&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=Nd&mm=31%2C29&mn=sn-cn3tc-aigr%2Csn-aigzrnze&ms=au%2Crdu&mv=m&mvi=7&pl=44&initcwndbps=1791250&vprv=1&mime=video%2Fmp4&ns=M28LquBZ_RAyVqGkqF4AeNEJ&gir=yes&clen=2847457650&otfp=1&dur=8009.998&lmt=1670009204992203&mt=1670061422&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=7216224&n=IYDSJcGBA3uspye5&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOqjLRU2jWpsaZ8eq3Csvf6s18zplQhuehFbrqHv7fg9AiEA8iJeivzC4vIU9-cGRPemd_B3f4XjGVQ5sQjcI288Vmg%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgPd7Mp0EJjHxn87Xt8hGvrKfhgnkmhGB_bnMkHTcWfl0CIQCp-kgvJXzWMNKBawhYq_I_OYLWLAUamDcafrY4x1pHQw%3D%3D'
ERROR: unable to open for writing: [Errno 92] Illegal byte sequence: 'Two Point Campus SPACE ACADEMY - Jane Trains Astronauts in New Two Point Campus DLC 🚀\U0001fae1-27rKhzGG1dM.f137.mp4.part'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/downloader/http.py", line 259, in download
    ctx.stream, ctx.tmpfilename = sanitize_open(
  File "/usr/local/lib/python3.9/site-packages/youtube_dl/utils.py", line 2055, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
OSError: [Errno 92] Illegal byte sequence: 'Two Point Campus SPACE ACADEMY - Jane Trains Astronauts in New Two Point Campus DLC 🚀\U0001fae1-27rKhzGG1dM.f137.mp4.part'
```

## Description

YouTube video with strange/illegal character in video title prevents download with "ERROR: unable to download video data: [Errno 92] Illegal byte sequence".

`yt-dlp "https://www.youtube.com/watch?v=27rKhzGG1dM"`

The same video is downloaded correctly if the title is omitted from the output in this way:

`yt-dlp -o "%(id)s.%(ext)s" "https://www.youtube.com/watch?v=27rKhzGG1dM"`

**Comment by dirkf** [comment]
Let's assume that you did `alias yt-dlp=youtube-dl`. I can't reproduce in Linux but will try in MacOS later.
```shell
$ python3.9 -m youtube_dl -v --test 'https://www.youtube.com/watch?v=27rKhzGG1dM'[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--test', 'https://www.youtube.com/watch?v=27rKhzGG1dM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 774b346f9
[debug] Python version 3.9.15 (CPython) - Linux-4.4.0-210-generic-i686-with-glibc2.23
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] 27rKhzGG1dM: Downloading webpage
[youtube] 27rKhzGG1dM: Downloading MPD manifest
[debug] [youtube] Decrypted nsig 3oPWtfXgQv-0LAfl => XW23Uy9OC0AcpQ
[debug] [youtube] Decrypted nsig YhHTbHAUwo10uiNG => 49W3DC2HCKAE-w
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://rr1---sn-cu-aigss.googlevideo.com/videoplayback?expire=1670089546&ei=6jaLY4-fDa6ixN8Phv-J8A8&ip=46.208.6.121&id=o-ADis7npx0FIYyKxugrnx2k7FUirHZZtBr9ULx4F_28Vl&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=Nd&mm=31%2C29&mn=sn-cu-aigss%2Csn-cu-c9id&ms=au%2Crdu&mv=m&mvi=1&pl=25&initcwndbps=1586250&vprv=1&mime=video%2Fmp4&ns=iKY54CAAWz6-qYrtwTrHPwUJ&gir=yes&clen=2847457650&otfp=1&dur=8009.998&lmt=1670009204992203&mt=1670067670&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=7216224&n=XW23Uy9OC0AcpQ&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMSObWqM4FHueEQSbdYZf-9aqHWD7JVnYlamcMG6j04OAiEAyj_RtkyQ0qg08Jsk4dG1GCs1_yFvjH7_nJp4ZCGJ0mE%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgGn4IUb-e4_4IEVjCaO97rurlvRq33G-jffr9zS3F5qMCIAyWmqGb9lWcPsa1r73UCzbPjID5TXQTLsPCcTqDVUNg'
[download] Destination: Two Point Campus SPACE ACADEMY - Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡-27rKhzGG1dM.f137.mp4
[download] 100% of 10.00KiB in 00:00
[debug] Invoking downloader on 'https://rr1---sn-cu-aigss.googlevideo.com/videoplayback?expire=1670089546&ei=6jaLY4-fDa6ixN8Phv-J8A8&ip=46.208.6.121&id=o-ADis7npx0FIYyKxugrnx2k7FUirHZZtBr9ULx4F_28Vl&itag=140&source=youtube&requiressl=yes&mh=Nd&mm=31%2C29&mn=sn-cu-aigss%2Csn-cu-c9id&ms=au%2Crdu&mv=m&mvi=1&pl=25&initcwndbps=1586250&vprv=1&mime=audio%2Fmp4&ns=iKY54CAAWz6-qYrtwTrHPwUJ&gir=yes&clen=129634733&otfp=1&dur=8010.048&lmt=1670007993745998&mt=1670067670&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=7211224&n=XW23Uy9OC0AcpQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOPR0i5gqGYztv7D-6l1V0j7SjZC9j2FrHzhQ8Mgb_0FAiBLjA4LvXOyVjTGGMhNgiV5WfFLM2RtrWgo_6CaSGK0Ag%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgGn4IUb-e4_4IEVjCaO97rurlvRq33G-jffr9zS3F5qMCIAyWmqGb9lWcPsa1r73UCzbPjID5TXQTLsPCcTqDVUNg'
[download] Destination: Two Point Campus SPACE ACADEMY - Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡-27rKhzGG1dM.f140.m4a
[download] 100% of 10.00KiB in 00:00
[ffmpeg] Merging formats into "Two Point Campus SPACE ACADEMY - Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡-27rKhzGG1dM.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Two Point Campus SPACE ACADEMY - Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡-27rKhzGG1dM.f137.mp4' -i 'file:Two Point Campus SPACE ACADEMY - Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡-27rKhzGG1dM.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Two Point Campus SPACE ACADEMY - Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡-27rKhzGG1dM.temp.mp4'
Deleting original file Two Point Campus SPACE ACADEMY - Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡-27rKhzGG1dM.f137.mp4 (pass -k to keep)
Deleting original file Two Point Campus SPACE ACADEMY - Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡-27rKhzGG1dM.f140.m4a (pass -k to keep)
df@Spiridion:~/Documents/src/youtube-dl$ rm Two\ Point\ Campus\ SPACE\ ACADEMY\ -\ Jane\ Trains\ Astronauts\ in\ New\ Two\ Point\ Campus\ DLC\ 🚀🫡-27rKhzGG1dM.mp4 
$
```
Meanwhile, `--restrict-filenames` will give you an acceptable filename.
```shell
$ python3.9 -m youtube_dl --get-filename --restrict-filenames 'https://www.youtube.com/watch?v=27rKhzGG1dM'
Two_Point_Campus_SPACE_ACADEMY_-_Jane_Trains_Astronauts_in_New_Two_Point_Campus_DLC-27rKhzGG1dM.mp4
$
```

**Comment by exboreas** [comment]
Sorry, I reported the same bug on the yt-dlp repo and accidentally copied my description here without changing the command. The commands I actually used were:
`youtube-dl  "https://www.youtube.com/watch?v=27rKhzGG1dM"`
and
`youtube-dl  -o "%(id)s.%(ext)s" "https://www.youtube.com/watch?v=27rKhzGG1dM"`
The same bug is found on both repositories.

**Comment by dirkf** [comment]
Indeed. I don't have MacOS at hand ATM, but it's not reproducible on iPad with LibTerm.

I think the problem is that the Python on your system has been built with some strange or old character set option.

In the failing code `stream = open(encodeFilename(filename), open_mode)`, the `encodeFilename()` function does nothing (identity) so the problem is that whatever has been passed to `open()` is unexpected. The rocket and "too small to identify" emoticons are obviously the unexpected characters, and as the "too small to identify" emoticon isn't rendered it's probably what's causing the error. Maybe something is checking that Unicode encodings match known code-points and complaining if not?

In Gnome Character Map based on Unicode 8.0, there is no code-point 1FAE1 ("too small to identify"). The Saluting Face emoticon with that code-point appeared in Unicode 14.0.

**Comment by dirkf** [comment]
Please run `python3.9 -c 'import unicodedata; print(unicodedata.unidata_version)` and report the output.

**Comment by exboreas** [comment]
I have run
`python3.9 -c 'import unicodedata; print(unicodedata.unidata_version)'`
`13.0.0`

**Comment by dirkf** [comment]
Thanks. I think that's standard for Py3.9. Although the Saluting Face emoticon isn't in v13, that doesn't seem to affect other Pythons that I tried.

Let's see if the issue is in your Python or more generally in your OS.

This will fail if Python can't create a file with Saluting Face emoticon in its name:
```
python3.9 -c 'import os; import tempfile; os.unlink(tempfile.mkstemp(".tmp", "\U0001fea1", ".")[1])'
```
I expect it to fail because the error looks like https://bugs.python.org/issue31380, and so the issue is a "feature" of your filesystem (Apple, the company that keeps on giving):
>... APFS doesn’t allow files to be created with filenames that contain unassigned codepoints in the Unicode 9.0 standard, whereas HFS+ does ...
>... with the current macOS 10.13 (High Sierra), root file systems on certain devices, such as SSDs, are automatically migrated from HFS+ to APFS so are much more likely to be seen starting in 10.13.

I can't believe that (even) Apple would freeze a particular Unicode version into its filesystem specification but I read that 10.12 was the first macOS to have APFS and this may be one of its limitations.

If so, the immediate solution is `--restrict-filenames`, or use a destination filesystem that isn't APFS, or *possibly* a newer macOS.

yt-dl has a `sanitize_path()` function that is called to make a more compatible filename if the original name can't be opened (other than because of permissions). Currently it only does anything on Windows, but perhaps it could scan for and substitute bad APFS characters on macOS where the filesystem is APFS. A difficulty is knowing which might be bad. Python doesn't have a built-in way of telling which Unicode version first recognised a particular code-point, but it does have a standardised Unicode 3.2 database: anything in that should be OK, but [many emoticons from Unicode 4.0 to 9.0](https://emojipedia.org/unicode-3.2/) would be replaced. Also, there may be reluctance among users to extend the behaviour of `sanitize_path()` beyond the pathname punctuation tidy-up that it does for Windows to change text in a key output template field such as `title`.

**Comment by exboreas** [comment]
Yes, it fails:
```
python3.9 -c 'import os; import tempfile; os.unlink(tempfile.mkstemp(".tmp", "\U0001fea1", ".")[1])'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tempfile.py", line 336, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tempfile.py", line 255, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 92] Illegal byte sequence: './\U0001fea1qahhdbn_.tmp'
```
I'll update to the latest macOS later today and report my findings here.

**Comment by exboreas** [comment]
Upgrading to latest macOS (13.0.1), which includes upgrade to Python 3.11.0, solved it.
Python 3.11 has Unicode v14 support.

**Comment by dirkf** [comment]
It's the OS version, in particular the APFS module, that made the difference, I think.

Tests on other platforms didn't require Python's Unicode to be v14: indeed I don't have a Python with v14.

...unless CPython does something weirdly different on macOS.
