### ISSUE TITLE
Reset retry counter upon success

### ISSUE THREAD

**Issue by Black-Platypus** [ytdl-org/youtube-dl#31390]
I keep experiencing errors with what I assume to be rate/volume limiting by providers. Intermittently, downloads will not resume until more time has passed to prevent overuse of resources (reason is conjecture on my part)
This results in YTDL behavior like this:

> "https://www1387.ff-03.com/token=aMLZHcDkkBSk8q4urr1JEg/1669844355/2a02:908::/43/6/b6/6f9f58f42d6d3896661b4436ebfa2b66-720p.mp4"
> [generic] 6f9f58f42d6d3896661b4436ebfa2b66-720p: Downloading webpage
> [info] 6f9f58f42d6d3896661b4436ebfa2b66-720p: Downloading 1 format(s): mp4
> [download] Resuming download at byte 29818544
> [download] Destination: K:\[Series]\# new\The Three Caballeros [1945].mp4
> [download]   2.4% of 1.19GiB at  524.29KiB/s ETA 38:43[download] Got error: Downloaded 30571872 bytes, expected 1278157164 bytes. Retrying (1/10)...
> [download] Got error: Remote end closed connection without response. Retrying (2/10)...
> [download] Got error: Remote end closed connection without response. Retrying (3/10)...
> [download] Destination: K:\[Series]\# new\The Three Caballeros [1945].mp4
> [download]   2.4% of 1.19GiB at  458.76KiB/s ETA 44:15[download] Got error: Downloaded 30751760 bytes, expected 1278157164 bytes. Retrying (4/10)...
> [download] Got error: Remote end closed connection without response. Retrying (5/10)...
> [download] Destination: K:\[Series]\# new\The Three Caballeros [1945].mp4
> [download]   2.5% of 1.19GiB at  242.47KiB/s ETA 01:23:40[download] Got error: Downloaded 31668928 bytes, expected 1278157164 bytes. Retrying (6/10)...
> [download] Destination: K:\[Series]\# new\The Three Caballeros [1945].mp4
> [download]   2.5% of 1.19GiB at  254.94KiB/s ETA 01:19:34[download] Got error: Downloaded 31734128 bytes, expected 1278157164 bytes. Retrying (8/10)...
> [download] Got error: Remote end closed connection without response. Retrying (9/10)...
> [download] Got error: Remote end closed connection without response. Retrying (10/10)...
> [download] Destination: K:\[Series]\# new\The Three Caballeros [1945].mp4
> [download] Got error: Downloaded 31864528 bytes, expected 1278157164 bytes. Giving up after 10 retries

IMO, when ever there is a working connection re-established, the fail counter should reset to 0.
Maybe this is a highly contested point; here are my arguments:
- We know it's not an absolute denial when we keep getting more data
- Behavior indicates a sort of temporary reset server-side too
- The point of a retry limit is, as far as I understand it, to exit out of a non-working task. IMO, just waiting for the earliest opportunity to continue downloading is a perfectly fine working task

The link above looks like it's unlikely to help with reproduction :/
FWIW, here are links illustrating how I got there:
https://kimcartoon.li/Cartoon/The-Three-Caballeros/Movie?id=20830
-> Server: FE
-> iframe: https://www.luxubu.review/v/7yvw002n8xo
-> video: https://fvs.io/redirector?token=dE1NMVZGdFdHaWlEbkhab2xFTUN1QzdzdDBablFOa0U0RWtUc1BGLy9WR2pud2dHUHhUY0pQOXhZR2FKbE5KV0pWZW5mTHhaMVJCbmVVdThWaStwQ3RuQ1ZKMHo5Y1FwbTMvQkJSV3VmbEVTVGZGTWdIZjNFZUFzdzYvc01JMDNnbWpkTExPR3A3c1BrZG56aEhmbFcyVEJPd2ZGOlRTQURSYmhYeHRUVWt3NVNRSWdBemc9PQsMVM
-> video redirect: https://www1387.ff-03.com/token=Z0YMFFlV4Ob_cBKE23w53g/1669845996/2a02:908::/43/6/b6/6f9f58f42d6d3896661b4436ebfa2b66-720p.mp4

**Comment by dirkf** [comment]
For the moment consider setting `--retries ...` or `--fragment-retries ...`, as appropriate. Given some intuition about the file size and the fragility of the remote server, you should be able to achieve the effect that you're requesting.

Maybe #30014 would make this better?

**Comment by Black-Platypus** [comment]
Completed where? 😮

**Comment by dirkf** [comment]
Because you approved the answer and didn't supply any other feedback for more than a month. If your satisfaction requires #30014, feel free to "me too" there.

**Comment by dirkf** [comment]
Because you approved the answer and didn't supply any other feedback for more than a month. If your satisfaction requires #30014, feel free to "me too" there.

**Comment by Black-Platypus** [comment]
Oh, the thumbs up was meant as a "thank you for the hint to a work-around in the mean time" 😅

**Comment by dirkf** [comment]
I could mark it `wontfix`?

But the retry logic would benefit from reworking and yt-dlp has made some changes that could be considered for back-porting.

The interim solution is all that's on offer immediately.

**Comment by Black-Platypus** [comment]
That would be more accurate. and with this clarification it's now a bit more understandable why
