### ISSUE TITLE
Format Microsoft Sway?

### ISSUE THREAD

**Issue by alex911kz** [ytdl-org/youtube-dl#31404]
Launch

.\youtube-dl.exe --merge-output-format mp4 "https://osizpeusburlywood000.streaming.mediaservices.windows.net/30bb06eb-3bb0-436b-9b90-43289cd7cd90/DefaultMediaFileName.ism/Manifest(format=mpd-time-csf)"

URL: https://osizpeusburlywood000.streaming.mediaservices.windows.net/30bb06eb-3bb0-436b-9b90-43289cd7cd90/DefaultMediaFileName.ism/Manifest(format=mpd-time-csf)

Error: 
C:\FFMPEG>.\youtube-dl.exe --merge-output-format flv "https://osizpeusburlywood000.streaming.mediaservices.windows.net/30bb06eb-3bb0-436b-9b90-43289cd7cd90/DefaultMediaFileName.ism/Manifest(format=mpd-time-csf)"
[generic] Manifest(format=mpd-time-csf): Requesting header
WARNING: Falling back on generic information extractor.
[generic] Manifest(format=mpd-time-csf): Downloading webpage
[generic] Manifest(format=mpd-time-csf): Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**What should I do? I understand that he cannot download and determine the Sway format?**

**Comment by alex911kz** [comment]
as I understand it, this format is MPEG-DASH format

**Comment by dirkf** [comment]
The manifest is like that in #15273 with the same result.
