### ISSUE TITLE
Cannot download sample youtube video (Homebrew, macOS 11.4)

### ISSUE THREAD

**Issue by abstraktio** [ytdl-org/youtube-dl#31402]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -v https://www.youtube.com/watch?v=K4TOrB7at0Y
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=K4TOrB7at0Y']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17

[debug] Python version 3.10.8 (CPython) - macOS-11.4-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube] K4TOrB7at0Y: Downloading webpage
WARNING: Unable to download webpage: <urlopen error [Errno 8] nodename nor servname provided, or not known>
[youtube] K4TOrB7at0Y: Downloading API JSON
ERROR: Unable to download API page: <urlopen error [Errno 8] nodename nor servname provided, or not known> (caused by URLError(gaierror(8, 'nodename nor servname provided, or not known')))
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/utils.py", line 2735, in https_open
    return self.do_open(functools.partial(
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
```

## Description

Have not been able to download anything using youtube-dl ever since I updated to the latest version. Before that, it worked just fine. Example uses a clearly-available sample video from youtube to prove the point.

**Comment by dirkf** [comment]
This is your ##31313, no?

It looks like your network is broken somewhere under Python. Show us some other program, especially some other Homebrew program, successfully resolving hostnames and communicating over the Internet.

If this is actually so,
>[x] I've checked that all provided URLs are alive and playable in a browser

is the browser using some proxy that you haven't told yt-dl about?

**Comment by dirkf** [comment]
So IPv6 works. Perhaps yt-dl is defaulting to IPv4 in some way "under the hood". Maybe try the `-6` option to force yt-dl to use IPv6?

Also retype the YT URL (actually you only need `K4TOrB7at0Y`) in case there is some invisible or clone character in the domain name.

**Comment by abstraktio** [comment]
> So IPv6 works. Perhaps yt-dl is defaulting to IPv4 in some way "under the hood". Maybe try the `-6` option to force yt-dl to use IPv6?
> 
> Also retype the YT URL (actually you only need `K4TOrB7at0Y`) in case there is some invisible or clone character in the domain name.

Before even trying -6, it just started working tonight out of the blue, without my having done any changes to it nor any updates whatsoever to my Mac.

Thank you for the help. I have no idea what caused this, but it works now.
