### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by saiyamarlon** [ytdl-org/youtube-dl#31415]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by rflexor** [comment]
Had the same issue today, Downloading the latest version from https://yt-dl.org/ solved it. Make sure to download the right executable for your platform.

Cheers!

**Comment by dirkf** [comment]
Regardless, the issue template was ignored. If anyone sees a similar problem, please open a new issue with the required information.
