### ISSUE TITLE
how to overwrite existing downloaded file?

### ISSUE THREAD

**Issue by asklow** [ytdl-org/youtube-dl#31419]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
How to overwrite already existing file ? I can't find overwrite flag for output file in readme.
(For now, I delete older one & then download which is two step)

**Comment by dirkf** [comment]
There isn't an option.

You could add a temporary directory to the output filename template and force-move the new file over any previous one with a command in `--exec ...`.

**Comment by dirkf** [comment]
There's an option for **not** overwriting but not for overwriting. The yt-dlp fork added `--force-overwrites` as below:
```
-w, --no-overwrites             Do not overwrite any files
--force-overwrites              Overwrite all video and metadata files. This
                                option includes --no-continue
--no-force-overwrites           Do not overwrite the video, but overwrite
                                related files (default)
```
This shows that there isn't fundamental reason why yt-dl doesn't have the option. I wouldn't reject a viable PR to back-port the feature.

**Comment by dirkf** [comment]
It applies to the related files, not the video itself.
