### ISSUE TITLE
How to download the entire YouTube channel videos ?

### ISSUE THREAD

**Issue by Angu0083** [ytdl-org/youtube-dl#31422]
## Checklist

- [✓] I'm asking a question
- [✓] I've looked through the README and FAQ for similar questions
- [✓] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

How to download the entire YouTube channel videos without using the videos or playlist links?

**Comment by dirkf** [comment]
Read #31209. Then, if that doesn't help, show an example of what you're trying to do, what you did to achieve it, and what actually happened (full Verbose log).

**Comment by Angu0083** [comment]
Thanks @dirkf it worked it...

rajr@MacBook-Pro yt-dlp --no-check-certificate -v -f 315+521 --merge-output-format mkv https://www.youtube.com/@onceforever_twice/videos
[debug] Command-line config: ['--no-check-certificate', '-v', '-f', '315+521', '--merge-output-format', 'mkv', 'https://www.youtube.com/@onceforever_twice/videos']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] API
[debug] Python 3.10.8 (CPython 64bit) - macOS-12.6.1-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Crypto-3.15.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/@onceforever_twice/videos
[youtube:tab] @onceforever_twice: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/@onceforever_twice/videos
[download] Downloading playlist: ONCE Forever 원스 영원히 - Videos
[youtube:tab] UCTRBTg1XU48Gc6wAD4QBmEQ page 1: Downloading API JSON
[youtube:tab] UCTRBTg1XU48Gc6wAD4QBmEQ page 2: Downloading API JSON
[youtube:tab] UCTRBTg1XU48Gc6wAD4QBmEQ page 3: Downloading API JSON
[youtube:tab] UCTRBTg1XU48Gc6wAD4QBmEQ page 4: Downloading API JSON
[youtube:tab] Playlist ONCE Forever 원스 영원히 - Videos: Downloading 137 videos of 137
[download] Downloading video 1 of 137
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=JO3meaPKmaA
[youtube] JO3meaPKmaA: Downloading webpage
[youtube] JO3meaPKmaA: Downloading android player API JSON
[debug] [youtube] Extracting signature function js_a0703e0f_109
[youtube] JO3meaPKmaA: Downloading player a0703e0f

**Comment by dirkf** [comment]
Actually you're using yt-dlp so you should have asked [here](https://github.com/yt-dlp/yt-dlp/issues). Glad it worked.

**Comment by Angu0083** [comment]
> Actually, you're using yt-dlp so you should have asked [here](https://github.com/yt-dlp/yt-dlp/issues). Glad it worked.

No, I tried YouTube-dl & yt-dlp  simultaneously. But I shared the wrong verbose output.
