### ISSUE TITLE
[antonproductions.net] Could you make this site available? Pls

### ISSUE THREAD

**Issue by tickbro** [ytdl-org/youtube-dl#31424]
## Checklist

- [ ] I'm reporting a new site support request
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [ ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

## Description

WRITE DESCRIPTION HERE

This is the site (http://www.antonproductions.net/[X]) I hope it can become available

**Comment by dirkf** [comment]
Why wouldn't you complete the template?

Why would you leave the template YT examples?

Does the site offer any content that doesn't require an account? The sample videos are probably not relevant.

What happens (verbose log) if you use yt-dl passing site cookies from a logged-in browser session with `--cookies ...` ?

**Comment by CHJ85** [comment]
Include the site name in the ticket title. Don't make generic titles like "could you make this site available"

**Comment by dirkf** [comment]
That seems reasonable.
