### ISSUE TITLE
missing example in documentation on github

### ISSUE THREAD

**Issue by Matthew-Bradley** [ytdl-org/youtube-dl#31425]
## Checklist
- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log
N/A

## Description
At https://github.com/ytdl-org/youtube-dl/blob/master/README.md#output-template-examples there is a missing example following:
``` In these cases, add the --restrict-filenames flag to get a shorter title:```

**Comment by dirkf** [comment]
Thanks. Actually the colon should be a full stop.

The example is shown [below, the second example in the list](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#user-content-output-template-examples).
