### ISSUE TITLE
tiktok

### ISSUE THREAD

**Issue by marii89** [ytdl-org/youtube-dl#31447]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

hi,

i looking new tiktok endpoint for video without watermark, before used this endpoint:
https://api-t2.tiktokv.com/aweme/v1/aweme/detail/?aweme_id=<id>

this was work for some time but recently stop work, anyone have new endpoint?

**Comment by dirkf** [comment]
Was this actually a question about the yt-dl TikTok extractor module? If so, feel free to open a new question with supporting information.
