### ISSUE TITLE
Unable to play MP4 video while downloading

### ISSUE THREAD

**Issue by uBadRequest** [ytdl-org/youtube-dl#31443]
## Checklist

- [X] I've looked through the README and FAQ for similar questions
- [x] I'm asking a question
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

I'm trying to watch an MP4 video while downloading it from a video sharing website. 

I've attempted to use the flags "-o -" and pipe it to "vlc -", but doesn't start playing. PS: It works just fine with YouTube videos.

It also needs to download the video in one session, so it can't create multiple parts, unless it doesn't break the connection, as the link only works for a few minutes before it displays a 401 Gone error. I can't fix that without paying $$$. You can download the entire video as long as your connection doesn't stop.

I assume the metadata required to play the video might be at the end of the video? Is there a flag that i'm missing that could download the beginning and end of the video first, so that it could start playing?

**Comment by dirkf** [comment]
>I assume the metadata required to play the video might be at the end of the video?

Good guess.

As long as the MP4 has both audio and video and you have _ffmpeg_ installed, try using _ffmpeg_ to download: `--external-downloader ffmpeg`.

**Comment by dirkf** [comment]
Feel free to let us know how your problem was solved.
