### ISSUE TITLE
Fresh Windows 11 x64 install MSVCR100.DLL missing program will not load

### ISSUE THREAD

**Issue by mrg9999** [ytdl-org/youtube-dl#31440]
yt-dlp works as expected
yt-dlp --version
2022.11.11

youtube-dl --version  reports MSVCR100.DLL missing
tried 2012 and 2015 vcredist,exe without success

app runs on windows 10
youtube-dl --version
2021.12.17

WRITE DESCRIPTION HERE
I can't post a log as it doesn't execute

**Comment by dirkf** [comment]
Read [the manual](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#user-content-the-exe-throws-an-error-due-to-missing-msvcr100dll), and also https://github.com/ytdl-org/youtube-dl/issues/30143#issuecomment-1022686470.

Duplicate of #10874.
