### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by SardarML** [ytdl-org/youtube-dl#31450]
for i in range(len(urls)):
  try:
    infos_array = np.array(video_info(urls[i]))
  except:
    print(('skip'))

output:
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
skip

**Comment by dirkf** [comment]
Read pinned issue #23638.

If that doesn't cause you to close the issue:
1. Show the sites involved.
2. Use the `verbose` flag.
3. Use backquotes \`code\` to show code and triple backquotes to show code blocks.

3. Consider

**Comment by dirkf** [comment]
Closing for lack of response.
