### ISSUE TITLE
Additional features to extend the functionality of youtube-dl

### ISSUE THREAD

**Issue by rahulrengesh** [ytdl-org/youtube-dl#31459]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
1) There are various useful options available whendownloading content from playlist.Based on maximum views and inimum views.I would like to add a feature with most liked video and least liked video of  playlist. which makes it easy for the users to select a video based on their interest.
2) Also i would like to add a feature where user must specify the country/region of interest and could get the trending videos of the particular country/region.
3) The final feature which i would like to add is the feature of frame capture.By specifying a specific timeline user must able to save the frame of the video.
These are the features i would like to add in this youtube-dl

**Comment by dirkf** [comment]
For 1 and 2, use the YT (or Invidious or PeerTube or whatever) web interface to select your desired video or playlist; then pass the resulting URL to yt-dl. You can use existing options (RTFM) to select only the first n items of a playlist, or to reverse the playlist order.

Alternatively, process the output of `--write-info-json` using a tool like _jq_ to extract and sort your desired playlist items and then use `--load-info-json` to download.

As a built-in feature of yt-dl, you could imagine an option that specifies a sort order for playlist items based on one or a list of metadata parameters, somewhat similar to `--match-filter ...`. Such a feature is unlikely to be implemented although anyone is free to offer a PR or fork that does implement one or the other.

For 3, use an _ffmpeg_ command in `--exec ...` (or it may be possible to use `-f bestvideo --external-downloader ffmpeg --external-downloader-args ...`). An internet search will reveal the necessary _ffmpeg_ options.

When proposing features or reporting issues, feel free to open a separate issue for each one.
