### ISSUE TITLE
Music not found/ stream

### ISSUE THREAD

**Issue by Soulivan71** [ytdl-org/youtube-dl#31452]
## Checklist
[ ] I've verified that I'm running youtube-dl version **2021.12.17**

## Description
Hi since few day my bot isn't working Im having the following issue :
![image](https://user-images.githubusercontent.com/36502190/210900328-e2411774-4fb1-4c30-836f-c315869ac8dc.png)
Im searching music with words or link and I result to the following screen
My bot don't dl/stream the music, and happened with all music I try like more than 10 most popular songs

**Comment by dirkf** [comment]
Your bot is not running the release version of yt-dl (that you didn't verify).

The release version 2021.12.17 handles YT video `gdZLi9oWNZg` fine.

Also, post the **text** log and use the **--verbose** option.

**Comment by dirkf** [comment]
Learn how to use the computers involved.

It should be like this, which shows that the yt-dl instance in your screenshot isn't 2021.12.17. Here I'm running yt-dl release in a Linux terminal.
```shellsession
$ youtube-dl -v -F 'gdZLi9oWNZg'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'gdZLi9oWNZg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] gdZLi9oWNZg: Downloading webpage
[youtube] gdZLi9oWNZg: Downloading player e5f6cbd5
[info] Available formats for gdZLi9oWNZg:
format code  extension  resolution note
249          webm       audio only tiny   51k , webm_dash container, opus @ 51k (48000Hz), 1.38MiB
250          webm       audio only tiny   68k , webm_dash container, opus @ 68k (48000Hz), 1.81MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 3.45MiB
251          webm       audio only tiny  133k , webm_dash container, opus @133k (48000Hz), 3.56MiB
160          mp4        256x144    144p   61k , mp4_dash container, avc1.4d400c@  61k, 24fps, video only, 1.65MiB
394          mp4        256x144    144p   69k , mp4_dash container, av01.0.00M.08@  69k, 24fps, video only, 1.86MiB
278          webm       256x144    144p   77k , webm_dash container, vp9@  77k, 24fps, video only, 2.05MiB
133          mp4        426x240    240p  103k , mp4_dash container, avc1.4d4015@ 103k, 24fps, video only, 2.75MiB
395          mp4        426x240    240p  125k , mp4_dash container, av01.0.00M.08@ 125k, 24fps, video only, 3.35MiB
242          webm       426x240    240p  134k , webm_dash container, vp9@ 134k, 24fps, video only, 3.58MiB
134          mp4        640x360    360p  179k , mp4_dash container, avc1.4d401e@ 179k, 24fps, video only, 4.78MiB
396          mp4        640x360    360p  240k , mp4_dash container, av01.0.01M.08@ 240k, 24fps, video only, 6.41MiB
243          webm       640x360    360p  245k , webm_dash container, vp9@ 245k, 24fps, video only, 6.55MiB
135          mp4        854x480    480p  272k , mp4_dash container, avc1.4d401e@ 272k, 24fps, video only, 7.25MiB
244          webm       854x480    480p  367k , webm_dash container, vp9@ 367k, 24fps, video only, 9.77MiB
397          mp4        854x480    480p  420k , mp4_dash container, av01.0.04M.08@ 420k, 24fps, video only, 11.20MiB
136          mp4        1280x720   720p  482k , mp4_dash container, avc1.4d401f@ 482k, 24fps, video only, 12.85MiB
247          webm       1280x720   720p  605k , webm_dash container, vp9@ 605k, 24fps, video only, 16.12MiB
398          mp4        1280x720   720p  793k , mp4_dash container, av01.0.05M.08@ 793k, 24fps, video only, 21.11MiB
399          mp4        1920x1080  1080p 1353k , mp4_dash container, av01.0.08M.08@1353k, 24fps, video only, 36.03MiB
248          webm       1920x1080  1080p 1549k , webm_dash container, vp9@1549k, 24fps, video only, 41.25MiB
137          mp4        1920x1080  1080p 1663k , mp4_dash container, avc1.640028@1663k, 24fps, video only, 44.30MiB
18           mp4        640x360    360p  308k , avc1.42001E, 24fps, mp4a.40.2 (44100Hz) (best)
$
```

**Comment by Soulivan71** [comment]
I don't understand what do you mean. My code works well and since just few days no so I don't know what's wrong

**Comment by dirkf** [comment]
Something has happened to your bot configuration causing an earlier yt-dl version to be invoked. This isn't a yt-dl issue. Or at least, you need to supply or link full details of the configuration to get further help here.

**Comment by Soulivan71** [comment]
> Something has happened to your bot configuration causing an earlier yt-dl version to be invoked. This isn't a yt-dl issue. Or at least, you need to supply or link full details of the configuration to get further help here.

Ok can u send me some commands u want to have what u need

**Comment by dirkf** [comment]
In the same terminal that you used for the last screenshot (but actually, select the text and paste that) run the command that I showed [above](https://github.com/ytdl-org/youtube-dl/issues/31452#issuecomment-1373919392).

**Comment by Soulivan71** [comment]
![image](https://user-images.githubusercontent.com/36502190/211080327-1417192e-5029-43ec-b9cc-ae7f38bdb806.png)

**Comment by Soulivan71** [comment]
Mb I re try and have this 
![image](https://user-images.githubusercontent.com/36502190/211082749-78385718-c3a5-446e-9fe9-60c1935963c8.png)

**Comment by Soulivan71** [comment]
Okay it works '-'WTFF

**Comment by Soulivan71** [comment]
U can close it :/

**Comment by dirkf** [comment]
So I guess somehow the bot process found an old yt-dl after a config change?

**Comment by Soulivan71** [comment]
I change nothing

**Comment by dirkf** [comment]
If it happened repeatably, it wasn't just a corrupt transfer or a gamma ray hitting the RAM. Somehow the bot started running an old version, like 2021.06.06, and the problem from #30363 re-appeared.
