### ISSUE TITLE
Epidemic Sound

### ISSUE THREAD

**Issue by UltraBlackLinux** [ytdl-org/youtube-dl#31462]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

Search anything on https://www.epidemicsound.com/

Here is the audio link: https://dkihjuum4jcjr.cloudfront.net/ES_ITUNES/Think%20It's%20over%20Now%20(Instrumental%20Version)/ES_Think%20It's%20over%20Now%20(Instrumental%20Version).mp3

## Description

Epidemicsound allows the user to "preview" the tracks on the website. Whenever pressing the play button while inspecting the site traffic monitor, one can, see that the client receives a link that corresponds to the track's audio.

This should be reasonably easy to retrieve.

In case this is added, please consider that links from the search tool are an easy way to get a playlist of tracks in the user's taste, so being able to download from a search would be appreciated.

**Comment by rautamiekka** [comment]
They also have multiple YouTube channels.

**Comment by UltraBlackLinux** [comment]
it's hard to search the youtube channels for particular genres

**Comment by rautamiekka** [comment]
Very true, at least if they didn't have genre-specific channels, a long list of them, at that: https://www.youtube.com/@epidemicsound/channels

And each one has playlists for even more specificity, like in the case of jazz that I randomly picked: https://www.youtube.com/@EpidemicJazz/playlists

**Comment by UltraBlackLinux** [comment]
it all happens on teh same page:
1. You click the play button on a song
2. You get a response with the link and some metadata

I also found out that they have some kind of api at https://www.epidemicsound.com/json/search/tracks/ but there is no documentation on this, that's why I'm still sticking to yt-dl

**Comment by realRobotix** [comment]
> This is not a real web site (as it doesn't have URLs for different resources within the site) and so isn't suitable for use with yt-dl. Unless anyone can persuade me otherwise this will be closed `wontfix`.

They do actually have URLs for all resources, but this might also be a recent addition. Just hover over a song/sound effect and on the right there is a link icon which copies the URL to the clipboard. Example: https://www.epidemicsound.com/track/yFfQVRpSPz/
