### ISSUE TITLE
leakedzone.com

### ISSUE THREAD

**Issue by bjoernramos** [ytdl-org/youtube-dl#31468]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Hello Team,

I wish you a happy new year!!

Could you add to your 'Supported Sites' the following site:
leakedzone.com

Kind Reagards Björn

**Comment by dirkf** [comment]
Perhaps, if you use the [Site Support Template](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=site-support-request&template=2_site_support_request.md) and provide the information that the template requires.

And Happy New Year to you too!
