### ISSUE TITLE
DMAX - new URL

### ISSUE THREAD

**Issue by Reiner1210** [ytdl-org/youtube-dl#31472]
I think dplaydk.media-edge.prod-vod.h264 is new

dvbtv@DVBTV:~/data/video/tvrec/download/Parkers Neuseeland Abenteuer> youtube-dl --output parker_neuseeland_01_01.mp4 -vvv 'https://dplaydk.media-edge.prod-vod.h264.io/046f6acc-cb4b-40fe-9632-538f890ef610/hls_fairPlay_ts/edge-cache-token=Expires=1673873910&KeyName=media-edge-key-prod-eu-661a302&Signature=fM6yaQKZ4rpZu5H33BYJHdl898wUO5msrpqom2EzaYBIXdXbOFtnu0rKNgZmVGyxuar74cOcibM9EmoHapZPCg/master.m3u8'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--output', u'parker_neuseeland_01_01.mp4', u'-vvv', u'https://dplaydk.media-edge.prod-vod.h264.io/046f6acc-cb4b-40fe-9632-538f890ef610/hls_fairPlay_ts/edge-cache-token=Expires=1673873910&KeyName=media-edge-key-prod-eu-661a302&Signature=fM6yaQKZ4rpZu5H33BYJHdl898wUO5msrpqom2EzaYBIXdXbOFtnu0rKNgZmVGyxuar74cOcibM9EmoHapZPCg/master.m3u8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.8.15-1-default-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[generic] master: Requesting header
WARNING: Falling back on generic information extractor.
[generic] master: Downloading webpage
[generic] master: Downloading m3u8 information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2453, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by dirkf** [comment]
1. That's not a video page from DMax; it's some manifest that you found from the browser's Dev Tools or similar.
2. The URL is supported but there aren't any usable formats in it: probably any video formats are DRM-encumbered, as hinted by the component `/hls_fairPlay_ts/` in the URL.
3. If you have a video page from the `dmax.de` domain that fails, open a new issue.

**Comment by Reiner1210** [comment]
@dirkf the URL was delivered from this tool https://github.com/Brawl345/Get-DMAX-Links
So it is a DMAX link

**Comment by dirkf** [comment]
Please open a new issue for the **actual web page** from which the manifest was harvested if yt-dl doesn't handle it. If yt-dl says "Unsupported" and the site's host isn't a subdomain of  something like .dmax.de, use the site support request form; otherwise use the broken site form.
