### ISSUE TITLE
doesn't work on teachable

### ISSUE THREAD

**Issue by smartk3** [ytdl-org/youtube-dl#31478]
I get error 403. Username and password are correct, and my youtube-dl is up to date. 
![youtube dl error](https://user-images.githubusercontent.com/122817263/213520448-c7c10530-8c5a-4791-a763-07f8843e92c3.png)

**Comment by smartk3** [comment]
C:\Users\Kristine Berthelsen\Downloads>youtube-dl https://edmprod.teachable.com/courses/1706460/lectures/38693626 --username USERNAME --verbose flag
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://edmprod.teachable.com/courses/1706460/lectures/38693626', '--username', 'PRIVATE', '--verbose', 'flag']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 38693626: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 38693626: Downloading webpage
[generic] 38693626: Extracting information
[Teachable] Downloading edmprod.teachable.com login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by dirkf** [comment]
Try providing `--cookies ...` from your logged-in browser session instead of `--username/password ...`. Typically, extractor login using username and password breaks because sites change the login page, require Captcha, etc.

Also, just `--verbose`, not `--verbose flag`, but that doesn't affect access to the site.

**Comment by dirkf** [comment]
Closing for lack of response.

**Comment by hanyang7427** [comment]
https://github.com/FallingLights/Teachable-dl?tab=readme-ov-file, this works

**Comment by hanyang7427** [comment]
https://github.com/FallingLights/Teachable-dl , this works for me at this moment
