### ISSUE TITLE
How can I automatically generate a thumbnail right after video exported using ffmpeg ?

### ISSUE THREAD

**Issue by rijotech** [ytdl-org/youtube-dl#31475]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi I'm using PHP to download the videos and I was wondering how can I automatically  generate a thumbnail using ffmped right after the video finished downloading? 

`    shell_exec( "yt-dlp -f --windows-filenames --restrict-filenames --replace-in-metadata title '#' ' ' 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' $name -v --merge-output-format mp4 -f 137+140" );`

I'm wondering if there is a way to integrate ffmpeg into the command to create a thumbnail after the video output?
If there is no way, there is a way to export a jpg instead of a webp image using `--write-thumbnail  `?

**Comment by dirkf** [comment]
Yes, `--exec ...`, but as you are using yt-dlp ask [there](https://github.com/yt-dlp/yt-dlp/issues). yt-dlp has more options relevant to your question.
