### ISSUE TITLE
Chaturbate Stream Quality

### ISSUE THREAD

**Issue by ttid150** [ytdl-org/youtube-dl#31479]
## Checklist

- [X ] I'm reporting a site feature request
- [X ] I've verified that I'm running youtube-dl version **2021.12.17**
- [X ] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Chaturbate streams offer multiple bitrates and it would be nice to be able to select a different bitrate instead of always getting the max bitrate available.

Examples
```
chunklist_w1304298569_b1668000_t64RlBTOjI5Ljk3.m3u8
chunklist_w1821444746_b1038000_t64RlBTOjI5Ljk3.m3u8
```

**Comment by dirkf** [comment]
Assuming this is what OP wanted.
