### ISSUE TITLE
Windows Installation Exits Immediately

### ISSUE THREAD

**Issue by pocketdrummer** [ytdl-org/youtube-dl#31483]
.

**Comment by LuisBurdallo** [comment]
I believe this is a command line tool and not an app.

**Comment by dirkf** [comment]
Suppose that you followed this from the [Manual](https://github.com/ytdl-org/youtube-dl#user-content-installation):
>Windows users can download an .exe file and place it in any location on their PATH except for %SYSTEMROOT%\System32 (e.g. do not put in C:\Windows\System32).

This isn't an installer, rather it's the program itself. Technically, it might be accurate to say that it temporarily installs Python with the yt-dl program modules whenever you run it.

So, from https://www.howtogeek.com/235101/10-ways-to-open-the-command-prompt-in-windows-10/, for example do this:
>Open Command Prompt from the File Explorer Address Bar
>
>In File Explorer, click the address bar to select it (or press Alt+D). Type “cmd” into the address bar and hit Enter to open the Command Prompt with the path of the current folder already set.

Then type (with Enter/Return)
```
youtube-dl --version
```
to test, expecting the output `2021.12.17`.

If that works, you're ready to formulate more complicated command invocations, following the examples in the Manual.
