### ISSUE TITLE
Where is the repository of http://ytdl-org.github.io/? How to post a PR to remove defunct websites from /supportedsites.html?

### ISSUE THREAD

**Issue by kdf8jsa1** [ytdl-org/youtube-dl#31492]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

I was looking for the repository of http://ytdl-org.github.io/ to post a PR to remove "france inter" and "france culture" from list of supported  sites (content of both websites is now available under www.radiofrance.fr).

Is it possible?

**Comment by dirkf** [comment]
The list is generated automatically from the code and will be updated in the next release after PR #31435 (or some equivalent) is merged.
