### ISSUE TITLE
Download video in article on CNN

### ISSUE THREAD

**Issue by karagiannis** [ytdl-org/youtube-dl#31505]
## Checklist

- [* ] I'm reporting a new site support request
- [* ] I've verified that I'm running youtube-dl version **2021.12.17**
- [* ] I've checked that all provided URLs are alive and playable in a browser
- [* ] I've checked that none of provided URLs violate any copyrights
- [* ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
CNN is supported. Please complete the [site feature request](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=3_site_feature_request.md] template. Include **actual URLs** and how you think they should be handled, or handled better.
