### ISSUE TITLE
Yt speed suddenly back to normal? 

### ISSUE THREAD

**Issue by Qbsoon** [ytdl-org/youtube-dl#31504]
## Checklist

- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

For a long time, like even before the last release, there began a problem with speed in dl from yt. I've read many issues here that said the same, I don't remember exact speeds, but it couldn't achieve speeds higher than 100KB/s I think. I had this problem still about a week ago, and today it's somehow gone. Speeds were higher then 2MB/s. I didn't changed anything in my setup nor in the software itself. Do you know what could happen that solved the issue? Was there a change in yt API or something like that, that could influence these speeds?

**Comment by Qbsoon** [comment]
And back again to these ~56KiB/s, strange.

**Comment by dirkf** [comment]
Continued in #30976.
