### ISSUE TITLE
No video formats found? - ISSUE

### ISSUE THREAD

**Issue by abdurryy** [ytdl-org/youtube-dl#31514]
Error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1118, in __threaded_polling
    raise e
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 91, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 6428, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "/root/SpotifyTelegram/bot.py", line 100, in callback_query
    x = spotify_download.download(f'{i["track"]["artists"][0]["name"]} - {i["track"]["name"]}')
  File "/root/SpotifyTelegram/utils/spotify_download.py", line 9, in download
    url = pafy.new(final_result)
  File "/usr/local/lib/python3.10/dist-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)
  File "/usr/local/lib/python3.10/dist-packages/pafy/backend_youtube_dl.py", line 31, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pafy/backend_shared.py", line 97, in __init__
    self._fetch_basic()
  File "/usr/local/lib/python3.10/dist-packages/pafy/backend_youtube_dl.py", line 43, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Code:
```py
def download(song, t=0):
        try:
            if t == 5:
                return None
            result = [video['link']
                    for video in VideosSearch(song, limit=1).result()['result']]
            final_result = result[0]
            url = pafy.new(final_result)
            media = url.getbestaudio()
            if os.path.isfile("songs/{}.mp3".format(media.title)) == False:
                wget.download(media.url, out="songs/{}.mp3".format(media.title))
            return "songs/{}.mp3".format(media.title)
        except:
            return SpotifyDownload.download(song, t+1)
```

**Comment by dirkf** [comment]
The message said
>Be sure to call youtube-dl with the --verbose flag and include its complete output.

Otherwise raise the issue with the maintainers of whichever package is invoking yt-dl.

**Comment by abdurryy** [comment]
> 

So how do I fix?

**Comment by abdurryy** [comment]
> The message said
> 
> > Be sure to call youtube-dl with the --verbose flag and include its complete output.
> 
> Otherwise raise the issue with the maintainers of whichever package is invoking yt-dl.

So how do I fix it?

**Comment by dirkf** [comment]
Either reproduce the problem with the command-line yt-dl program, or ask the maintainers of whatever packages are calling yt-dl to help. There's no yt-dl code in your back-trace, let alone yt-dl debugging output, except for the diagnostic message that is being inappropriately passed through by the calling package.

**Comment by abdurryy** [comment]
> Either reproduce the problem with the command-line yt-dl program, or ask the maintainers of whatever packages are calling yt-dl to help. There's no yt-dl code in your back-trace, let alone yt-dl debugging output, except for the diagnostic message that is being inappropriately passed through by the calling package.

I still don't understand what you want me to do. 😮‍💨

**Comment by dirkf** [comment]
You aren't directly running _youtube-dl_, the program that is supported here, so we don't have enough information to help you. You can try asking the maintainers of the program that's invoking _youtube-dl_ to help diagnose the issue. The back-trace shows these packages `telebot`, `SpotifyTelegram`, `pafy`.

If you can identify which URL is failing when processed by yt-dl, then run a yt-dl command to download that URL, using the `-v` option, and post the resulting log.

If your problem application is trying to download audio from Spotify it will have trouble. Spotify music is DRM-protected and can't be extracted using yt-dl; Spotify podcasts used to be supported but now (a) exclusive podcasts are DRM-protected too and (b) non-exclusive podcasts may not be so protected but the extractor doesn't know how to find them yet. Or so I understand. Basically this means that Spotify is not supported, though you can still list metadata for a podcast series.

**Comment by abdurryy** [comment]
> You aren't directly running _youtube-dl_, the program that is supported here, so we don't have enough information to help you. You can try asking the maintainers of the program that's invoking _youtube-dl_ to help diagnose the issue. The back-trace shows these packages `telebot`, `SpotifyTelegram`, `pafy`.
> 
> If you can identify which URL is failing when processed by yt-dl, then run a yt-dl command to download that URL, using the `-v` option, and post the resulting log.
> 
> If your problem application is trying to download audio from Spotify it will have trouble. Spotify music is DRM-protected and can't be extracted using yt-dl; Spotify podcasts used to be supported but now (a) exclusive podcasts are DRM-protected too and (b) non-exclusive podcasts may not be so protected but the extractor doesn't know how to find them yet. Or so I understand. Basically this means that Spotify is not supported, though you can still list metadata for a podcast series.

It was working a day before I posted this issue, I believe it might be a Youtube update?

**Comment by dirkf** [comment]
>It was working ...

So far you haven't been able to explain what it was that *was* working.

**Comment by dirkf** [comment]
Looking at your code and the backtrace, an exception is being raised in the `try:` suite but you aren't reporting what happened. Then the call in the `except:` suite is failing. You need to instrument this or run it in the debugger. If that reveals an unexpected failure when invoking yt-dl, please feel free to open a new issue, following #30839, and reference this one.
