### ISSUE TITLE
How to download full HD YouTube videos with original sound without encoding?

### ISSUE THREAD

**Issue by eddievalentin07** [ytdl-org/youtube-dl#31518]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by eddievalentin07** [comment]
> Use the `--format` parameter together with the `height` property: `--format "[height =? 1080]"` to grab 1080p (Full HD) if it exists, then whatever `bestvideo+bestaudio/best` is, but you need to install FFmpeg to get `bestvideo+bestaudio`.
> 
> 
> 
> All that was in the readme, too.

Let me explain better, so I'm trying to download 1080p with 'avc1' without encoded software I just want to have original sound I tried what you told me to do but not working.

**Comment by rautamiekka** [comment]
Original sound, as in what the uploader had in the file before uploading ?

How not working ?

**Comment by eddievalentin07** [comment]
> Original sound, as in what the uploader had in the file before uploading ?
> 
> 
> 
> How not working ?

Exactly

**Comment by eddievalentin07** [comment]
> Original sound, as in what the uploader had in the file before uploading ?
> 
> 
> 
> How not working ?

Exactly. How to do that in YouTube-dl

**Comment by dirkf** [comment]
`avc1` is a video codec.

yt-dl doesn't re-encode audio (or video) unless:
* you actually ask for it, eg `--extract-audio --audio-format ...`, or
* the specified media container requires it (only certain media codecs are allowed in certain containers).

For any further assistance, please post a text format log of yt-dl doing what you don't want it to, using the `-v` option.

**Comment by pukkandan** [comment]
> > Original sound, as in what the uploader had in the file before uploading ?
> > How not working ?
> 
> Exactly. How to do that?

It's not possible. We don't have access to the original files and can only download formats that are playable on browser

**Comment by eddievalentin07** [comment]
> > > Original sound, as in what the uploader had in the file before uploading ?
> 
> > > How not working ?
> 
> > 
> 
> > Exactly. How to do that?
> 
> 
> 
> It's not possible. We don't have access to the original files and can only download formats that are playable on browser

Is it possible download video high resolution for example 1080p with av1 audio?

**Comment by rautamiekka** [comment]
Depends on the particular vid. Check the available formats with:
```batch
youtube-dl --verbose --list-formats "ADDRESS"
```
Sometimes YT changes things, so the formats ain't always the same for every vid.

If a format doesn't exist, then you can't get it.
