### ISSUE TITLE
Problem downloading from youtube

### ISSUE THREAD

**Issue by jd1008** [ytdl-org/youtube-dl#31529]
$ youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

$ ytdl -v -F https://youtu.be/i0JAL7Yniy8?t=150 2>&1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://youtu.be/i0JAL7Yniy8?t=150']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.8 (CPython) - Linux-6.0.8-100.fc35.x86_64-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4.3, ffprobe N-51556-ge278500
[debug] Proxy map: {}
[youtube] i0JAL7Yniy8: Downloading webpage
[youtube] i0JAL7Yniy8: Refetching age-gated info webpage
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
Traceback (most recent call last):
  File "/sdb3/home/jd/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/sdb3/home/jd/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/sdb3/home/jd/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/sdb3/home/jd/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1731, in _real_extract
    raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: Sign in to confirm your age
This video may be inappropriate for some users.

I am indeed logged in to my gmail account

So, what is the problem here???

**Comment by october262** [comment]
you need to use a cookies.txt file in your command.

**Comment by dirkf** [comment]
You may find that the git master version, which has just been updated, bypasses the age gate without passing cookies. However it tells me this:
```
This video contains content from Studiocanal, who has blocked it in your country on copyright grounds
```
Also, do quote the "URL" in case you forget to do so when the URL has `...?t=150&query_param_that_will_be_ignored_and_run_as_a_separate_command`.

**Comment by jd1008** [comment]
please provide an example, as I have never had to do so before.
Thanx!!

**Comment by dirkf** [comment]
Eg, as you are in a POSIX shell, to list formats verbosely:
```
youtube-dl -v -F 'https://youtu.be/i0JAL7Yniy8?t=150'
```

**Comment by jd1008** [comment]
You had mentioned that I need to specify
a file by the name cookies.txt
and I asked for an example of the youtube-dl command
having that file as an arg.
Can you show me such an example?
P.S: I am on Linux.

**Comment by dirkf** [comment]
See the update above.
