### ISSUE TITLE
How to unblock download speed on youtube?

### ISSUE THREAD

**Issue by R-S-M-A-N** [ytdl-org/youtube-dl#31521]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Hello,

Do you have any solution to unlock youtube download speed?
Currently all my transfers are limited to 50-60Kib/s, but once I managed to download at 10-16Mb, so how do I get out of the throttling?
Currently I download videos from my own channel (I need to make a backup, but it's too slow...) I use Youtube-DL without installation on Windows!
If anyone has a solution, I'm interested!

**Comment by Thomas131** [comment]
NewPipe seems to have found a solution. It is a bit volotile, so you really have to keep it up to date and sometimes it doesn't work for some hours.

Links:
* https://newpipe.net/
* https://github.com/TeamNewPipe/
* https://github.com/TeamNewPipe/NewPipeExtractor

Somewhere in the NewPipe issues&PRs (https://github.com/TeamNewPipe/NewPipe/issues), there is the fix, but I couldn't find it right now.

**Comment by dirkf** [comment]
For now, just install the git master using _pip_, or use yt-dlp, or find a repo that builds nightly releases from here. All this has been discussed in existing issues that you claimed to have searched for.
