### ISSUE TITLE
Fix - extract uploader id

### ISSUE THREAD

**Issue by despr0grammer** [ytdl-org/youtube-dl#31538]
Just go to

youtube_dl\extractor\youtube.py

Line 1794 :             
             'uploader_id': self._search_regex(r'/(?:channel/|user/|)([^/?&#]+)', owner_profile_url, 'uploader id', default=None),

Replace with this : 

            'uploader_id': self._search_regex(r'/(?:channel/|user/|@)([^/?&#]+)', owner_profile_url, 'uploader id', default=None),

**Comment by mk-pmb** [comment]
Thanks! For me it also worked to just comment-out the line, as I don't use that field in my download filename template. Good to know because that comment-out approach might work for other fields in similar cases.

**Comment by mk-pmb** [comment]
The old regexp allowed an empty match as the final choice for the "channel" parens. Someone should check whether we want to continue accepting the empty match.

**Comment by dazey3** [comment]
Building `youtube-dl` on windows:
```
...\git\youtube-dl>python -m youtube_dl
Usage: __main__.py [OPTIONS] URL [URL...]

__main__.py: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```
How can I rebuild `youtube-dl` on windows?

**Comment by despr0grammer** [comment]
> Here you have all

Python310\site-packages\youtube_dl\

**Comment by marlouz** [comment]
Hi, I'm sorry, I am a pl/sql developer and not familiar with python. Just trying to get my youtube-dl back to work... I've managed to get the source code locally and changed the uploader_id line. Now when I run 'python -m youtube-dl' it says '...\Python311\python.exe: No module named youtube-dl.__main__; 'youtube-dl' is a package and cannot be directly executed' so obviously I'm missing something. Could you please tell me in baby steps how to get youtube-dl on track again? Thanks!!!

**Comment by Ashborn117** [comment]
I don't understand how to do this on windows

**Comment by steve-ttt** [comment]
> Hi, I'm sorry, I am a pl/sql developer and not familiar with python. Just trying to get my youtube-dl back to work... I've managed to get the source code locally and changed the uploader_id line. Now when I run 'python -m youtube-dl' it says '...\Python311\python.exe: No module named youtube-dl.**main**; 'youtube-dl' is a package and cannot be directly executed' so obviously I'm missing something. Could you please tell me in baby steps how to get youtube-dl on track again? Thanks!!!

$ git clone https://github.com/ytdl-org/youtube-dl.git
$ vi youtube-dl/youtube_dl/extractor/youtube.py
$ cd youtube-dl
$ python setup.py  build
$ sudo python setup.py  install

**Comment by marlouz** [comment]
> 

@steve-ttt Thank you so much!!! I've got a working .exe now, and a better understanding of the process. You are a live saver!

**Comment by djkwee20** [comment]
ERROR: Unable to extract uploader id - error remains after update line youtube.py:1794

$ python /home/djien/anaconda3.8/bin/youtube-dl -v https://www.youtube.com/watch?v=6jSLH9CDPPQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=6jSLH9CDPPQ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.16 (CPython) - Linux-5.4.0-139-generic-x86_64-with-glibc2.10
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube] 6jSLH9CDPPQ: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/djien/anaconda3.8/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/djien/anaconda3.8/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/djien/anaconda3.8/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/djien/anaconda3.8/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user|@)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/djien/anaconda3.8/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

youtube-dl version:
(base) [/mnt/Elements/Youtube.Playlist.2023.1]:$ python /home/djien/anaconda3.8/bin/youtube-dl --version
2021.12.17
Environment: Linux-Ubuntu 20.04
Comment: Error remains after update youtube.py:1794
Line 1794 :
'uploader_id': self._search_regex(r'/(?:channel/|user/|)([^/?&#]+)', owner_profile_url, 'uploader id', default=None),

Replace with this :
        'uploader_id': self._search_regex(r'/(?:channel/|user/|@)([^/?&#]+)', owner_profile_url, 'uploader id', default=None),

**Comment by hyper750** [comment]
Hi, any PR open?

**Comment by dirkf** [comment]
Duplicate of #31530.
