### ISSUE TITLE
Unable to extract https://youtu.be/h3MuIUNCCzI

### ISSUE THREAD

**Issue by juri-zaitsev** [ytdl-org/youtube-dl#31543]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

Unable to extract:
youtube-dl --list-formats https://youtu.be/h3MuIUNCCzI

**Comment by dirkf** [comment]
Read the template and provide the requested information to receive help.

**Comment by schneeschmelze** [comment]
Although I am not the original poster, I'd like to provide the verbose output I've just got on MacOS 12.6.3 with youtube-dl via Homebrew. Hope this helps.

thatsme@workingdirectory % youtube-dl --verbose -f 18 "https://www.youtube.com/watch?v=jBR0PMMGtuU"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', '18', 'https://www.youtube.com/watch?v=jBR0PMMGtuU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 17c872fb5
[debug] Python version 3.10.10 (CPython) - macOS-12.6.3-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube] jBR0PMMGtuU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by angryfullstackdev** [comment]
Hello, I am encountering the same issue since today (yesterday it worked fine). 
I can extract playlist information but not tracks.
```
// working
./youtube-dl.exe 'https://...?list=...' -J --flat-playlist
{uploader_id:...}
```
```
// not working
./youtube-dl.exe 'https://...?v=...' -j
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Available to provide anymore information

**Comment by Vangelis66** [comment]
> ERROR: Unable to extract uploader id;

... Yet another **duplicate** of #31530, in a list of duplicates that, seemingly, explodes exponentially 😡 ...
```diff
-please report this issue on https://yt-dl.org/bug .
+please check whether an issue with the same ERROR message has been already submitted in 
+https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen
+If yes, DON'T CREATE yet another duplicate one...
```

**Comment by elevatorguy** [comment]
https://youtube.com/watch?v=qRACQpkDDDU

**Comment by comicsansgreenki** [comment]
> https://youtube.com/watch?v=qRACQpkDDDU

...huh?

**Comment by dirkf** [comment]
@schneeschmelze, see the existing issue linked above for your problem.

Closing for lack of response.

**Comment by dirkf** [comment]
Marking as duplicate to defeat weird GH issue search.
