### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by jdluther2020** [ytdl-org/youtube-dl#31542]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ X] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [X ] I've read bugs section in FAQ

## Verbose log

```
% youtube-dl --version
2021.12.17

youtube-dl --verbose "https://www.youtube.com/watch?v=gltCxV8cGUs"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=gltCxV8cGUs']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 17c872fb5
[debug] Python version 3.11.2 (CPython) - macOS-13.0-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube] gltCxV8cGUs: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

Download never completed after several attempts. Kept giving error after a few GB download, I'd start it again to continue from the last offset but around 97% it is permanently failing.

**Comment by rajinder-yadav** [comment]
Getting the same error for the following (yt shorts) video: https://www.youtube.com/shorts/IQ0Z6tjC3NU

**Comment by ricciolino** [comment]
Same here

**Comment by tforsberg** [comment]
me too.

**Comment by Kladislav** [comment]
https://github.com/ytdl-patched/yt-dlp/releases/tag/2023.02.17.334 use this patch if u cannot wait for release fix.

**Comment by itseyup** [comment]
Same here.

**Comment by pkolesni** [comment]
the same issue

**Comment by GerritDamen** [comment]
same issue with every youtubevideo I've tried, 2023.02.17.334 (link from kladislav) works

**Comment by dirkf** [comment]
Duplicate of #31530.

**Comment by alexvitkir** [comment]
The same issue for any youtube video

**Comment by StephenSun** [comment]
same issue

**Comment by JohnTRL** [comment]
Y'all, go /youtube_dl/extractor/common.py.

Line 983 change `fatal=True` to `fatal=False`

**Comment by smacm** [comment]
Can verify that dwsiddall's solution works on MacOS.  If installed via homebrew, the file common.py is in:
/opt/homebrew/Cellar/youtube-dl/<version date>/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py

**Comment by dirkf** [comment]
FFS don't screw around with `extractor/common.py`, which (the hint is in the name) is used by all the other extractors as well as the YT extractor. Use the actual [fixed version](https://github.com/ytdl-org/youtube-dl/issues/31530), or make the corresponding change in `extractor/youtube.py` if you really must be a l33t hax0r (but don't).

**Comment by dwsiddall** [comment]
Why was my comment marked as spam?

**Comment by dirkf** [comment]
Commenting on an identified duplicate thread.

**Comment by ErrorOliver** [comment]
theres a thing called marking the comment as a duplicate

**Comment by dwsiddall** [comment]
And I'm sure you're going to tell me that because you included a smiley face I should'nt notice how snarky your comment is.  I guess there's no room for an error on this forum.
