### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by aliammar182** [ytdl-org/youtube-dl#31555]
I am unable to download any audio using this library

**Comment by dirkf** [comment]
Use the issue template to report your issue (start at #30839 if you like). If you had done so you would have been prompted so:

> [ ] I've searched the bugtracker for similar issues including closed ones

From the [search](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+uploader+-label%3Aduplicate) you would have found (I guess, though you provided no diagnostic beyond the issue title) ...

Duplicate of #31530.
