### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by oompaloopa** [ytdl-org/youtube-dl#31575]
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by thedtvn** [comment]
same

**Comment by thedtvn** [comment]
log
```
0|Fantasy  | Traceback (most recent call last):
0|Fantasy  |   File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
0|Fantasy  |     return func(self, *args, **kwargs)
0|Fantasy  |   File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
0|Fantasy  |     ie_result = ie.extract(url)
0|Fantasy  |   File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
0|Fantasy  |     ie_result = self._real_extract(url)
0|Fantasy  |   File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
0|Fantasy  |     'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
0|Fantasy  |   File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
0|Fantasy  |     raise RegexNotFoundError('Unable to extract %s' % _name)
0|Fantasy  | youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
0|Fantasy  | During handling of the above exception, another exception occurred:
0|Fantasy  | Traceback (most recent call last):
0|Fantasy  |   File "/home/pi/code/fantasy/main/cogs/music.py", line 185, in play_audio
0|Fantasy  |     URL = await load_yt_audio()
0|Fantasy  |   File "/home/pi/code/fantasy/main/sync_to_async.py", line 12, in wrapper
0|Fantasy  |     result = await loop.run_in_executor(pool, func, *args, **kwargs)
0|Fantasy  |   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
0|Fantasy  |     result = self.fn(*self.args, **self.kwargs)
0|Fantasy  |   File "/home/pi/code/fantasy/main/cogs/music.py", line 183, in load_yt_audio
0|Fantasy  |     info = ydl.extract_info(pageurl, download=False)
0|Fantasy  |   File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
0|Fantasy  |     return self.__extract_info(url, ie, download, extra_info, process)
0|Fantasy  |   File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 824, in wrapper
0|Fantasy  |     self.report_error(compat_str(e), e.format_traceback())
0|Fantasy  |   File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 628, in report_error
0|Fantasy  |     self.trouble(error_message, tb)
0|Fantasy  |   File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 598, in trouble
0|Fantasy  |     raise DownloadError(message, exc_info)
0|Fantasy  | youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by mariusz-zawadzki** [comment]
I'm getting similar error.
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', 'https://www.youtube.com/watch?v=s5T-oxek4UA', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] s5T-oxek4UA: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

I checked one of the older ones I downloaded and it works fine:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '--verbose', 'https://www.youtube.com/watch?v=WyzrrNUpj-E']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] WyzrrNUpj-E: Downloading webpage
[debug] Invoking downloader on 'https://rr1---sn-uvt5-ajwl.googlevideo.com/videoplayback?expire=1676741722&ei=-bfwY_mJPMeh7ASoo6TwDQ&ip=31.182.230.248&id=o-ADK2UpCqB9gz0ZGtdUlVUqg6ZI-GFsS2Gf5cYbQ_z5EO&itag=140&source=youtube&requiressl=yes&mh=_l&mm=31%2C29&mn=sn-uvt5-ajwl%2Csn-f5f7ln7y&ms=au%2Crdu&mv=m&mvi=1&pl=19&gcr=pl&initcwndbps=2208750&vprv=1&mime=audio%2Fmp4&ns=T08oBfLjzwf6yGdmaN3L3acL&gir=yes&clen=1364875&dur=84.186&lmt=1636100337490580&mt=1676719746&fvip=1&keepalive=yes&fexp=24007246&c=WEB&txp=5432434&n=sZYUig9XMysQUGms&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgMmUyx2tRtTIURmt60-wDpjJUQ7l2-8LW2-u0avgRCCYCIQDVqJ_bCyCyDmol6DpQ1chZQcMPjDKIK5ZxnBkEEKKZgw%3D%3D&sig=AOq0QJ8wRAIgKwJeKA_d2TQBx0fxNHhDVMwhvjbcTyHcZj2J50u_C-oCIAlQwN0DXxBwwXqCl5_1CjULR_ws3lpG4QBC-KhMOndh'
[download] Resuming download at byte 183534

**Comment by colhountech** [comment]
It's the new `@chanelname` parameter

Fixed here --> https://github.com/yt-dlp/yt-dlp/issues/6247

If you want  a quick fix for now, just need to add this new parameter option:`/|(?=@))`

in  .local/lib/python3.8/site-packages/youtube_dl/extractor

Change this:
```
'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
```
to this 
```
 'uploader_id': self._search_regex(r'/(?:channel/|user/|(?=@))([^/?&#]+)', owner_profile_url, 'uploader id', default=None),
```

and wait for a new update soon. :-)

**Comment by schmetris** [comment]
Same issue

**Comment by dmendek** [comment]
Same here:
`PS C:\Users\x> youtube-dl -x --audio-format mp3 --verbose https://www.youtube.com/watch?v=Le5EGqle-uM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '--audio-format', 'mp3', '--verbose', 'https://www.youtube.com/watch?v=Le5EGqle-uM']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Le5EGqle-uM: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by mariusz-zawadzki** [comment]
FYI: I just checked main branch and after "make" I was able to download the video. So I think new release should fix this issue!

**Comment by mariusz-zawadzki** [comment]
Ok, well not "fixed" per se but works as this is now just a warning not a breaking error.

**Comment by elgonzo** [comment]
Well, at least you are honest and left the checkbox for "_I've searched the bugtracker for similar issues including closed ones_" unchecked. Which in my book makes you a better person than all the others that clearly didn't search the bug tracker at all and yet ticked that checkbox in their duplicate issue reports.

Still, i wish you would have spent at least five short seconds searching the bug tracker for exactly the words in the title of your issue report. Guess what you will see: an unmissable bunch of [_duplicate_ issue reports](https://github.com/ytdl-org/youtube-dl/issues?q=Unable+to+extract+uploader+id) made many hours before you made yours. There is simply no need to make yet another duplicate issue anymore, really...

**Comment by palekiller** [comment]
same！If there are any solution, plz tell me!

**Comment by dirkf** [comment]
It's a warning until the value that should be extracted can be determined.
