### ISSUE TITLE
Bass are pretty loud, does youtube-dl perform some EQ?  (maybe via ffmpeg?)

### ISSUE THREAD

**Issue by BecauseTheWorldIsRound** [ytdl-org/youtube-dl#31573]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions (seriously did!)
- [x] I've searched the bugtracker for similar questions including closed ones (sincerely did!)

## Question

Using **yt-dlp-2023.02.17.334** dev build on **Ubuntu 22.04.1** (works fine!)

Downloaded a `-x` (audio only - "Best") `.opus` (default) file from YT. 
That was fast and efficient. Great tool.

However I noticed that the dl file had much more bass than the original heard in YT (Chrome).

I don't have any particular ffmpeg config.

Is it because

- [ ]  The audio rendering plugin in Chrome does "trim" the sound (or has lower quality), and, among other things, reduces basses? (the DL audio would be better)
- [ ]  Does youtube-dl does some "EQualization"?
- [ ]  Or could it be that ffmpeg does some EQ?

Thank you.

**Comment by dirkf** [comment]
Ask the question at https://github.com/yt-dlp/yt-dlp/issues.
