### ISSUE TITLE
not working on youtube

### ISSUE THREAD

**Issue by hazdo** [ytdl-org/youtube-dl#31574]
youtube-dl -q -f best -g 'https://www.youtube.com/watch?v=_7wjPOo88SE'
WARNING: Failed to download m3u8 information: HTTP Error 429: Too Many Requests
WARNING: Failed to download MPD manifest: HTTP Error 429: Too Many Requests
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
See #23638.
