### ISSUE TITLE
Sparky Linux LXQt youtube-dl installed by "curl"

### ISSUE THREAD

**Issue by garvint** [ytdl-org/youtube-dl#31584]
Installed youtube-dl in terminal  where it can update in SparkyLinux LXQt , (which is Debian Stable):

sudo apt-get install curl
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /bin/youtube-dl
cd ../..
cd bin
sudo chmod a+x youtube-dl
youtube-dl -U

The install is completed and updated !

but then running in terminal youtube-dl I get this error:

pc@A4-02-B9-B0-31-4B:~$ youtube-dl https://www.youtube.com/watch?v=ikuHgm9nVDI
[youtube] ikuHgm9nVDI: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
#30839
