### ISSUE TITLE
Unable to extract uploader id;

### ISSUE THREAD

**Issue by yohanespm77** [ytdl-org/youtube-dl#31581]
vid = pafy.new("https://www.youtube.com/watch?v=60ItHLz5WEA&ab_channel=Alan Walker",basic=False)
print(vid)

Error happened : 
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
#30839
