### ISSUE TITLE
ERROR: Unable to extract uploader id;

### ISSUE THREAD

**Issue by G0561** [ytdl-org/youtube-dl#31599]
hello，everyone！
 this bug not fix ，  youtube-dl.exe in window， or sudo -H pip install --upgrade youtube-dl ，the error again！

ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
#30839
