### ISSUE TITLE
Sparky Linux LXQt youtube-dl installed by "curl" in terminal

### ISSUE THREAD

**Issue by garvint** [ytdl-org/youtube-dl#31593]
## Checklist

- [ ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
pc@A4-02-B9-B0-31-4B:~$ youtube-dl -v https://www.youtube.com/watch?v=ikuHgm9nVDI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=ikuHgm9nVDI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-19-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.4.3, ffprobe 4.4.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ikuHgm9nVDI: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE

Installed youtube-dl in terminal where it can update in SparkyLinux LXQt , (which is Debian Stable):

sudo apt-get install curl
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /bin/youtube-dl
cd ../..
cd bin
sudo chmod a+x youtube-dl
youtube-dl -U

The install is completed and updated !

but then running in terminal youtube-dl I get this error:

pc@A4-02-B9-B0-31-4B:~$ youtube-dl https://www.youtube.com/watch?v=ikuHgm9nVDI
[youtube] ikuHgm9nVDI: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
> [x] I've searched the bugtracker for similar issues including closed ones

#30839
