### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by housejunkies01** [ytdl-org/youtube-dl#31595]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
C:\Users\abc123\Downloads\_Aoutube>youtube-dl -v https://www.youtube.com/watch?v=j0wCUKN8tH4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=j0wCUKN8tH4']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] j0wCUKN8tH4: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are
using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag
 and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeD
L.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeD
L.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extracto
r\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extracto
r\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extracto
r\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call yout
ube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
To Whom It May Concern,
I have been successfully using youtube-dl.exe for a couple of years until February 17th, 2023. On the following day, I started getting the error message "unable to extract uploader id". I usually wait for an update or change from your end, but I decided to create a bug report instead. Any assistance you can provide would be greatly appreciated.
Thank you for your time and consideration.
Regards,

**Comment by s1sw4nto** [comment]
I have same problem

**Comment by Rajendran61** [comment]
I have the same above problem "Unable to extract uploader id".

**Comment by jazzfess** [comment]
Ditto.

Thanks for your service.

Best Regards,
Don

**Comment by JohnTRL** [comment]
Y'all, go /youtube_dl/extractor/common.py.
Line 983, change: `fatal=True` to `fatal=False`

**Comment by dirkf** [comment]
#30839

**Comment by housejunkies01** [comment]
Go here to get the last update https://github.com/yt-dlp/yt-dlp/tree/2023.02.17#installation
the new yt-dlp allow you to download again.
Thank you Dirkf for the update!
