### ISSUE TITLE
"sre_constants.error: nothing to repeat" when running under Python 2.7.3

### ISSUE THREAD

**Issue by nachanon** [ytdl-org/youtube-dl#31597]
As I got hit by bug #31530 ("Unable to extract uploader id") [while using the "latest" 2021.12.17 release](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435654669), and someone said there that Git version worked; I cloned the repostory and checked out `master` branch (commit 2dd6c6e), then applied the standard `make` regimen like I did with past tarball releases...

	$ git checkout -qf 2dd6c6e ; git clean -qxdf
	$ make
	mkdir -p zip
	for d in youtube_dl youtube_dl/downloader youtube_dl/extractor youtube_dl/postprocessor ; do \
		  mkdir -p zip/$d ;\
		  cp -pPR $d/*.py zip/$d/ ;\
		done
	touch -t 200001010101 zip/youtube_dl/*.py zip/youtube_dl/*/*.py
	mv zip/youtube_dl/__main__.py zip/
	cd zip ; zip -q ../youtube-dl youtube_dl/*.py youtube_dl/*/*.py __main__.pyhttps://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435654669
	rm -rf zip
	echo '#!/usr/bin/env python' > youtube-dl
	cat youtube-dl.zip >> youtube-dl
	rm youtube-dl.zip
	chmod a+x youtube-dl
	pandoc -f markdown -t plain README.md -o README.txt
	/usr/bin/env python devscripts/prepare_manpage.py youtube-dl.1.temp.md
	pandoc -s -f markdown -t man youtube-dl.1.temp.md -o youtube-dl.1
	rm -f youtube-dl.1.temp.md
	/usr/bin/env python devscripts/bash-completion.py
	/usr/bin/env python devscripts/zsh-completion.py
	/usr/bin/env python devscripts/fish-completion.py
	/usr/bin/env python devscripts/make_supportedsites.py docs/supportedsites.md
	$ 

However, when I actually tested downloading the video with this newly-built version... instead of downloading the video, or fail with video downloading-related issues; **it simply crashed** with:

	$ ./youtube-dl -f 18 --verbose https://www.youtube.com/watch?v=57US7TpC38w
	[debug] System config: []
	[debug] User config: []
	[debug] Custom config: []
	[debug] Command-line args: [u'-f', u'18', u'--verbose', u'https://www.youtube.com/watch?v=57US7TpC38w']
	[debug] Encodings: locale TIS-620, fs TIS-620, out TIS-620, pref TIS-620
	[debug] youtube-dl version 2021.12.17
	[debug] Python version 2.7.3 (CPython) - Linux-3.2.0-4-686-pae-i686-with-debian-7.0
	[debug] exe versions: avconv 0.8.18-6, avprobe 0.8.18-6, ffmpeg 0.8.10-6, ffprobe 0.8.18-6, rtmpdump 2.4
	[debug] Proxy map: {}
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
	    "__main__", fname, loader, pkg_name)
	  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
	    exec code in run_globals
	  File "./youtube-dl/__main__.py", line 19, in <module>
	  File "./youtube-dl/youtube_dl/__init__.py", line 475, in main
	    
	  File "./youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
	    
	  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2081, in download
	  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 801, in extract_info
	  File "./youtube-dl/youtube_dl/extractor/common.py", line 415, in suitable
	  File "/usr/lib/python2.7/re.py", line 190, in compile
	    return _compile(pattern, flags)
	  File "/usr/lib/python2.7/re.py", line 242, in _compile
	    raise error, v # invalid expression
	sre_constants.error: nothing to repeat
	$ 

Since the 2021.12.17 release did not have this error, I suspected a regression; so I have done a `git bisect` test spanning from the 2021.12.17 (5014bd6) "good" to current master (2dd6c6e) "bad". It revealed that:

	e19ec5232216fd801ded88728df5b50bfb05c1cc is the first bad commit
	commit e19ec5232216fd801ded88728df5b50bfb05c1cc
	Author: dirkf <fieldhouse@gmx.net>
	Date:   Sat Feb 11 03:25:14 2023 +0000
	
	    [Vimeo] Support /user{video_id}/{slug} URL format
	
	:040000 040000 295c3c4303d73aa07a4d79f13a3acc31aa67a624 b1578ac329c110ea3096b31c38a4bfee4fd92f1b M	youtube_dl

This offending commit changed the regular expression used for matching Vimeo video URLs, from:

	(?x)
	https?://
	    (?:
	        (?:
	            www|
	            player
	        )
	        \.
	    )?
	    vimeo(?:pro)?\.com/
	    (?!(?:channels|album|showcase)/[^/?#]+/?(?:$|[?#])|[^/]+/review/|ondemand/)
	    (?:.*?/)??
	    (?:
	        (?:
	            play_redirect_hls|
	            moogaloop\.swf)\?clip_id=
	        )?
	    (?:videos?/)?
	    (?P<id>[0-9]+)
	    (?:/(?P<unlisted_hash>[\da-f]{10}))?
	    /?(?:[?&].*)?(?:[#].*)?$

To:

	(?x)
	https?://
	    (?:
	        (?:
	            www|
	            player
	        )
	        \.
	    )?
	    vimeo(?:pro)?\.com/
	    (?:
	        (?P<u>user)|
	        (?!(?:channels|album|showcase)/[^/?#]+/?(?:$|[?#])|[^/]+/review/|ondemand/)
	        (?:.*?/)??
	        (?P<q>
	            (?:
	                play_redirect_hls|
	                moogaloop\.swf)\?clip_id=
	        )?
	        (?:videos?/)?
	    )
	    (?P<id>[0-9]+)
	    (?(u)
	        /(?!videos|likes)[^/?#]+/?|
	        (?(q)|/(?P<unlisted_hash>[\da-f]{10}))?
	    )
	    (?:(?(q)[&]|(?(u)|/?)[?]).*?)?(?:[#].*)?$

Which caused the regex engine to blow up; though I'm not sure of _how_ or which part of it exactly at the moment.

A **workaround** I have found so far is simply checking out the `master` (2dd6c6e) **and** backing out the offending commit using `git show e19ec52 | patch -p1 -R`, and rebuild. This allows YouTube-DL to continue functioning on sites other than Vimeo at least...

	$ git checkout -qf 2dd6c6e ; git clean -qxdf
	$ git show e19ec52 | patch -p1 -R
	patching file youtube_dl/extractor/vimeo.py
	$ make
	mkdir -p zip
	for d in youtube_dl youtube_dl/downloader youtube_dl/extractor youtube_dl/postprocessor ; do \
		  mkdir -p zip/$d ;\
		  cp -pPR $d/*.py zip/$d/ ;\
		done
	touch -t 200001010101 zip/youtube_dl/*.py zip/youtube_dl/*/*.py
	mv zip/youtube_dl/__main__.py zip/
	cd zip ; zip -q ../youtube-dl youtube_dl/*.py youtube_dl/*/*.py __main__.py
	rm -rf zip
	echo '#!/usr/bin/env python' > youtube-dl
	cat youtube-dl.zip >> youtube-dl
	rm youtube-dl.zip
	chmod a+x youtube-dl
	COLUMNS=80 /usr/bin/env python youtube_dl/__main__.py --help | /usr/bin/env python devscripts/make_readme.py
	/usr/bin/env python devscripts/make_contributing.py README.md CONTRIBUTING.md
	pandoc -f markdown -t plain README.md -o README.txt
	/usr/bin/env python devscripts/prepare_manpage.py youtube-dl.1.temp.md
	pandoc -s -f markdown -t man youtube-dl.1.temp.md -o youtube-dl.1
	rm -f youtube-dl.1.temp.md
	/usr/bin/env python devscripts/bash-completion.py
	/usr/bin/env python devscripts/zsh-completion.py
	/usr/bin/env python devscripts/fish-completion.py
	/usr/bin/env python devscripts/make_supportedsites.py docs/supportedsites.md
	$ ./youtube-dl -f 18 --verbose https://www.youtube.com/watch?v=57US7TpC38w 
	[debug] System config: []
	[debug] User config: []
	[debug] Custom config: []
	[debug] Command-line args: [u'-f', u'18', u'--verbose', u'https://www.youtube.com/watch?v=57US7TpC38w']
	[debug] Encodings: locale TIS-620, fs TIS-620, out TIS-620, pref TIS-620
	[debug] youtube-dl version 2021.12.17
	[debug] Python version 2.7.3 (CPython) - Linux-3.2.0-4-686-pae-i686-with-debian-7.0
	[debug] exe versions: avconv 0.8.18-6, avprobe 0.8.18-6, ffmpeg 0.8.10-6, ffprobe 0.8.18-6, rtmpdump 2.4
	[debug] Proxy map: {}
	[youtube] 57US7TpC38w: Downloading webpage
	[debug] [youtube] Decrypted nsig d0mIdthfqTFcGYB9 => Bx5CPss7DOVsLQ
	[debug] [youtube] Decrypted nsig inunSQXPTdftAAps => w5iyFgZFtdJn7w
	WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	[debug] Invoking downloader on u'https://rr6---sn-5np5po4v-c33zr.googlevideo.com/videoplayback?sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&fexp=24007246&ei=duzxY_fbO5rWjuMP286bkAk&ip=110.170.81.7&id=o-AG94A4NxbYuA6XlEpbJxbczQDGRdoR0k3JxJ10W0ez4J&txp=5318224&cnr=14&pcm2=no&requiressl=yes&ratebypass=yes&source=youtube&sig=AOq0QJ8wRQIgehpnYFx8hz5MdEaxvbSQeBbEuZwzSYYHg5pYCGlGEuwCIQCGYHXjwFCNT8ub4Dj0D3hqewPSEe4-0kp53_p08S4eMg%3D%3D&pcm2cms=yes&dur=270.582&ns=iPo85q_revHb3nXbncPW1McL&initcwndbps=1122500&vprv=1&lsig=AG3C_xAwRAIgHP8nUQzNKF47EqNqtJfSIS1ieTlHdUJ8OvxFbSlk1osCIGqzBRycsgnHYoFSliaHsFkdUNeb_BC3Ze5hJ0PEw0VJ&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lmt=1665125565002773&c=WEB&expire=1676820695&mime=video%2Fmp4&fvip=3&itag=18&mm=31%2C26&mn=sn-5np5po4v-c33zr%2Csn-npoldn7d&mh=2r&n=w5iyFgZFtdJn7w&mt=1676798701&mv=m&pl=24&ms=au%2Conr&mvi=6'
	[download] Destination: Jefferz Koi () -English Cover- (Gen Hoshino)-57US7TpC38w.mp4
	[download] 100% of 13.21MiB in 15:25
	$ 

Please investigate and fix.

YouTube-DL 2021.12.17-185-g2dd6c6e (Git 17-Feb-2023)
Python: 2.7.3 (Debian)
System: Debian GNU/Linux 7.0 "Wheezy" i386

**Comment by JohnTRL** [comment]
Y'all, go /youtube_dl/extractor/common.py.
Line 983, change: `fatal=True` to `fatal=False`

**Comment by nachanon** [comment]
I am not too familiar with the nooks and crannies of how regular expression works under Python, but after some tedious experiment by repeatedly calling `re.compile()` on a gradually-chopped-off version offending regular expression, the pattern compiler stopped error'ing out as soon as I chopped off to the third `?` from the end...

	(?x)
	https?://
	    (?:
	        (?:
	            www|
	            player
	        )
	        \.
	    )?
	    vimeo(?:pro)?\.com/
	    (?:
	        (?P<u>user)|
	        (?!(?:channels|album|showcase)/[^/?#]+/?(?:$|[?#])|[^/]+/review/|ondemand/)
	        (?:.*?/)??
	        (?P<q>
	            (?:
	                play_redirect_hls|
	                moogaloop\.swf)\?clip_id=
	        )?
	        (?:videos?/)?
	    )
	    (?P<id>[0-9]+)
	    (?(u)
	        /(?!videos|likes)[^/?#]+/?|
	        (?(q)|/(?P<unlisted_hash>[\da-f]{10}))?
	    )
	    (?:(?(q)[&]|(?(u)|/?)[?]).*?)

^ This regex compiles; though I'm still not exactly sure why the offending one didn't.

I also have tried an alternative way: paraphrasing the offending `(?:...)?` group (first non-capture group on the last line of the regexp from the offending commit  e19ec52), into an alternate form of `(?:(?:...)|)`. **The result compiles:**

	(?x)
	https?://
	    (?:
	        (?:
	            www|
	            player
	        )
	        \.
	    )?
	    vimeo(?:pro)?\.com/
	    (?:
	        (?P<u>user)|
	        (?!(?:channels|album|showcase)/[^/?#]+/?(?:$|[?#])|[^/]+/review/|ondemand/)
	        (?:.*?/)??
	        (?P<q>
	            (?:
	                play_redirect_hls|
	                moogaloop\.swf)\?clip_id=
	        )?
	        (?:videos?/)?
	    )
	    (?P<id>[0-9]+)
	    (?(u)
	        /(?!videos|likes)[^/?#]+/?|
	        (?(q)|/(?P<unlisted_hash>[\da-f]{10}))?
	    )
	    (?:(?:(?(q)[&]|(?(u)|/?)[?]).*?)|)(?:[#].*)?$

Depending on the exact meaning of the expression `(?(q)[&]|(?(u)|/?)[?]).*?` inside the offending group (which I'm not too privy to), this paraphrasing _might_ be a solution.

(I'm curious, is there any test case or list of Vimeo URLs that the offending commit (e19ec52) supposed to fix their recognition, that I could test this paraphrased pattern on?)

Python: 2.7.3 (Debian)
System: Debian GNU/Linux 7.0 "Wheezy" i386

**Comment by dirkf** [comment]
```
$ git remote -v | grep yt-dl
yt-dl	https://github.com/ytdl-org/youtube-dl.git (fetch)
yt-dl	https://github.com/ytdl-org/youtube-dl.git (push)
$ git pull yt-dl master:nachtest
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (4/4), done.
remote: Total 5 (delta 4), reused 4 (delta 4), pack-reused 1
Unpacking objects: 100% (5/5), 894 bytes | 33.00 KiB/s, done.
From https://github.com/ytdl-org/youtube-dl
 * [new branch]          master     -> nachtest
   dd9aa74be..2dd6c6edd  master     -> yt-dl/master
Updating dd9aa74be..2dd6c6edd
Fast-forward
 youtube_dl/extractor/youtube.py | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

$ git checkout nachtest
Switched to branch 'nachtest'
$ python -m youtube_dl -v -F 'https://www.youtube.com/watch?v=57US7TpC38w'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.youtube.com/watch?v=57US7TpC38w']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 2dd6c6edd
[debug] Python version 2.7.18 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] 57US7TpC38w: Downloading webpage
[debug] [youtube] Decrypted nsig UOOzPOJCa1Kvu5uu => yZpl3c2lldSDJQ
[debug] [youtube] Decrypted nsig lvKuNpxGiYBotpZD => HVxpfi4-YG3xvA
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[info] Available formats for 57US7TpC38w:
format code  extension  resolution note
249          webm       audio only tiny   52k , webm_dash container, opus @ 52k (48000Hz), 1.68MiB
250          webm       audio only tiny   69k , webm_dash container, opus @ 69k (48000Hz), 2.23MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 4.18MiB
251          webm       audio only tiny  136k , webm_dash container, opus @136k (48000Hz), 4.39MiB
160          mp4        256x144    144p   66k , mp4_dash container, avc1.4d400c@  66k, 30fps, video only, 2.13MiB
278          webm       256x144    144p   74k , webm_dash container, vp9@  74k, 30fps, video only, 2.40MiB
242          webm       426x240    240p  114k , webm_dash container, vp9@ 114k, 30fps, video only, 3.69MiB
133          mp4        426x240    240p  147k , mp4_dash container, avc1.4d4015@ 147k, 30fps, video only, 4.75MiB
243          webm       640x360    360p  200k , webm_dash container, vp9@ 200k, 30fps, video only, 6.46MiB
134          mp4        640x360    360p  281k , mp4_dash container, avc1.4d401e@ 281k, 30fps, video only, 9.08MiB
244          webm       854x480    480p  313k , webm_dash container, vp9@ 313k, 30fps, video only, 10.10MiB
135          mp4        854x480    480p  519k , mp4_dash container, avc1.4d401f@ 519k, 30fps, video only, 16.76MiB
247          webm       1280x720   720p  526k , webm_dash container, vp9@ 526k, 30fps, video only, 16.98MiB
302          webm       1280x720   720p60  829k , webm_dash container, vp9@ 829k, 60fps, video only, 26.76MiB
136          mp4        1280x720   720p  941k , mp4_dash container, avc1.64001f@ 941k, 30fps, video only, 30.37MiB
298          mp4        1280x720   720p60 1346k , mp4_dash container, avc1.640020@1346k, 60fps, video only, 43.42MiB
303          webm       1920x1080  1080p60 1018k , webm_dash container, vp9@1018k, 60fps, video only, 32.84MiB
299          mp4        1920x1080  1080p60 2364k , mp4_dash container, avc1.64002a@2364k, 60fps, video only, 76.26MiB
18           mp4        640x360    360p  409k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz) (best)
df@Spiridion:~/Documents/src/youtube-dl$

**Comment by dirkf** [comment]
```console
$ pytest -k _Vimeo
============================= test session starts ==============================
platform linux2 -- Python 2.7.18, pytest-4.6.11, py-1.11.0, pluggy-0.13.1
rootdir: .../youtube-dl
collected 2597 items / 2574 deselected / 23 selected                           
...
====== 9 failed, 11 passed, 3 skipped, 2574 deselected in 263.72 seconds =======
```
Looking at https://github.com/ytdl-org/youtube-dl/actions/runs/4203228192/jobs/7292360532, the 9 failures are all due to link rot:
```
404
unable to extract list title
404
403
403
Expected at least 25 ... got only 22
Invalid value for field description, ...
Invalid value for field ext, ...
Invalid value for field description, ...
```
The `_VALID_URL` for each extractor is compiled every time yt-dl runs in order to test the supplied URL(s), which would always reveal a faulty regex, and don't I know it.

**Comment by OverLordGoldDragon** [comment]
Adding my bit, I'm using the Windows exe installer; it's always worked fine in the past.

<details>
  <summary>full output</summary>

```
C:\Users\Name>youtube-dl --extract-audio --audio-format "mp3" --audio-quality 0 --verbose https://youtu.be/dmmnx4VQmPU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', '--verbose', 'https://youtu.be/dmmnx4VQmPU']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] dmmnx4VQmPU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

</details>

<details>
  <summary>system info</summary>

```
     active environment : base
    active env location : D:\Anaconda
            shell level : 1
       user config file : C:\Users\Name\.condarc
 populated config files : C:\Users\Name\.condarc
          conda version : 4.10.3
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages : __cuda=12.0=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : D:\Anaconda  (writable)
      conda av data dir : D:\Anaconda\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda\pkgs
                          C:\Users\Name\.conda\pkgs
                          C:\Users\Name\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda\envs
                          C:\Users\Name\.conda\envs
                          C:\Users\Name\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.24.0 CPython/3.8.3 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : C:\Users\Name/.netrc
           offline mode : False
```

</details>

**Comment by AlgenKrapfen** [comment]
I hit the same issue here is my log:
youtube-dl https://www.youtube.com/watch?v=CEDdNVPMao4 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=CEDdNVPMao4', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: ffmpeg 4.2.3
[debug] Proxy map: {}
[youtube] CEDdNVPMao4: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
@OverLordGoldDragon, @AlgenKrapfen, you have #31530. The problem here is with the fix for that issue in much older Pythons than yours.

**Comment by dirkf** [comment]
Right, here's the deal...

1. The updated RE is a bit too generous with its quantifiers (`?`, `*`, `*?`).

2. In older Pythons up to [somewhere in the 2.7 series](https://github.com/python/cpython/issues/62847) there was a [check for a pattern that might cause an infinite loop](https://lists.archive.carbon60.com/python/python/944170).

3. This check causes the `sre_constants.error: nothing to repeat` error when there are nested quantifiers that can both match the empty string.

4. The solution is to make one quantifier not match the empty string (thanks for your earlier digging):

```diff
--- old/youtube_dl/extractor/vimeo.py
+++ new/youtube_dl/extractor/vimeo.py
@@ -286,7 +286,7 @@
                              /(?!videos|likes)[^/?#]+/?|
                              (?(q)|/(?P<unlisted_hash>[\da-f]{10}))?
                          )
-                         (?:(?(q)[&]|(?(u)|/?)[?]).*?)?(?:[#].*)?$
+                         (?:(?(q)[&]|(?(u)|/?)[?]).+?)?(?:[#].*)?$
                  '''
     IE_NAME = 'vimeo'
     _TESTS = [
```

A minimal test (this failed in the same way, previously):
```console
# python --version
Python 2.7.1
# python test/test_all_urls.py TestAllURLsMatching.test_keywords
.
----------------------------------------------------------------------
Ran 1 test in 74.972s

OK
#
```
The unpatched extractor and a more lenient Python gives the same result:
```console
$ python --version
Python 2.7.18
$ python test/test_all_urls.py TestAllURLsMatching.test_keywords
.
----------------------------------------------------------------------
Ran 1 test in 1.007s

OK
$
```
I think this can be committed.
