### ISSUE TITLE
youtube_dl fails with youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; for YouTube id 9aA9gsaA0Qw

### ISSUE THREAD

**Issue by GoMeister** [ytdl-org/youtube-dl#31604]
Other videos also fail.

log below:

eric@eric-Latitude-E6530:~$ sudo youtube-dl -U
[sudo] password for eric: 
youtube-dl is up-to-date (2021.12.17)
eric@eric-Latitude-E6530:~$ youtube-dl -o '~/Downloads/youtube-dl/%(title)s.%(ext)s' -k 9aA9gsaA0Qw
[youtube] 9aA9gsaA0Qw: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
eric@eric-Latitude-E6530:~$ youtube-dl --verbose -o '~/Downloads/youtube-dl/%(title)s.%(ext)s' -k 9aA9gsaA0Qw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', '~/Downloads/youtube-dl/%(title)s.%(ext)s', '-k', '9aA9gsaA0Qw']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.19.0-32-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 9aA9gsaA0Qw: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/eric/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/eric/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/eric/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/eric/.local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/eric/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by nicolaasjan** [comment]
Known issue, fixed in git master code:

- [YouTube: Unable to extract uploader id](https://github.com/ytdl-org/youtube-dl/issues/31530)

**Comment by dirkf** [comment]
#30839
