### ISSUE TITLE
unable to extract uploader id

### ISSUE THREAD

**Issue by tbhtyson** [ytdl-org/youtube-dl#31605]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
I'm on macOS 13.2.1 and I get this error:unable to extract uploader id.

**Comment by nicolaasjan** [comment]
Known issue, fixed in git master code:

- [YouTube: Unable to extract uploader id](https://github.com/ytdl-org/youtube-dl/issues/31530)

**Comment by dirkf** [comment]
> [ ] I've searched the bugtracker for similar bug reports including closed ones

Do it.

#30839
