### ISSUE TITLE
Is it possible to get a link?

### ISSUE THREAD

**Issue by stefs22** [ytdl-org/youtube-dl#31608]
I read somewhere that youtube-dl can get permanent m3u link from youtube, can someone explain me if this is possible and how to do this?
Thanks!

**Comment by dirkf** [comment]
`--get-url` or `-g`, but the links expire

**Comment by stefs22** [comment]
Is there any way to have permanent links?

**Comment by dirkf** [comment]
Not for YouTube.

Use the YouTube URL and run yt-dl again, or save the media in your own data centre and use the link to tha copy.
