### ISSUE TITLE
Bug (?) report.

### ISSUE THREAD

**Issue by patfla** [ytdl-org/youtube-dl#31607]
> ... Videos>youtube-dl https://www.youtube.com/watch?v=gGHUAOuL2YY  --verbose
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['https://www.youtube.com/watch?v=gGHUAOuL2YY', '--verbose']
> [debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
> [debug] youtube-dl version 2021.12.17
> [debug] Python version 3.8.3 (CPython) - Windows-10-10.0.22621-SP0
> [debug] exe versions: none
> [debug] Proxy map: {}
> [youtube] gGHUAOuL2YY: Downloading webpage
> [youtube] gGHUAOuL2YY: Downloading MPD manifest
> ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "d:\programs\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
>     return func(self, *args, **kwargs)
>   File "d:\programs\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
>     ie_result = ie.extract(url)
>   File "d:\programs\python38\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
>     ie_result = self._real_extract(url)
>   File "d:\programs\python38\lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
>     'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
>   File "d:\programs\python38\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
>     raise RegexNotFoundError('Unable to extract %s' % _name)
> youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> 

2021.12.17 seems quite old - let me try upgrading.

> 
> ... Videos>pip install youtube-dl --upgrade
> WARNING: Ignoring invalid distribution -outube-dlc (d:\programs\python38\lib\site-packages)
> WARNING: Ignoring invalid distribution -illow (d:\programs\python38\lib\site-packages)
> WARNING: Ignoring invalid distribution -outube-dlc (d:\programs\python38\lib\site-packages)
> WARNING: Ignoring invalid distribution -illow (d:\programs\python38\lib\site-packages)
> Requirement already satisfied: youtube-dl in d:\programs\python38\lib\site-packages (2021.12.17)
> WARNING: Ignoring invalid distribution -outube-dlc (d:\programs\python38\lib\site-packages)
> WARNING: Ignoring invalid distribution -illow (d:\programs\python38\lib\site-packages)
> WARNING: Ignoring invalid distribution -outube-dlc (d:\programs\python38\lib\site-packages)
> WARNING: Ignoring invalid distribution -illow (d:\programs\python38\lib\site-packages)
> WARNING: Ignoring invalid distribution -outube-dlc (d:\programs\python38\lib\site-packages)
> WARNING: Ignoring invalid distribution -illow (d:\programs\python38\lib\site-packages)
> WARNING: Ignoring invalid distribution -outube-dlc (d:\programs\python38\lib\site-packages)
> WARNING: Ignoring invalid distribution -illow (d:\programs\python38\lib\site-packages)
>

**Comment by dirkf** [comment]
#30839
