### ISSUE TITLE
ERROR: Unable to extract uploader id;

### ISSUE THREAD

**Issue by arceon6** [ytdl-org/youtube-dl#31609]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
$ youtube-dl -v -F https://www.youtube.com/watch?v=VWGr_89_xdU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.youtube.com/watch?v=VWGr_89_xdU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-6.0.0-6mx-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.5-0.1, ffprobe 4.3.5-0.1
[debug] Proxy map: {}
[youtube] VWGr_89_xdU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

WRITE DESCRIPTION HERE
$ youtube-dl --version
2021.12.17

**Comment by Oragoss** [comment]
Hijacking this Issue to mention I too am experiencing this issue and am using 2021.12.17.

**Comment by tml** [comment]
Confirmed - something seems to have just changed in youtube's page layout.

**Comment by aaronnewsome** [comment]
Same issue here. Verbose output looks similar to above

**Comment by Oragoss** [comment]
> Confirmed - something seems to have just changed in youtube's page layout.
> 
> Commenting line [1794](https://github.com/ytdl-org/youtube-dl/blob/2021.12.17/youtube_dl/extractor/youtube.py#L1794) of `youtube_dl/extractor/youtube.py` seems to resolve the problem temporarily.

Can confirm, commenting out this line made it work

**Comment by SirDagen** [comment]
Here as well the same error:

```
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.15.0-60-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
```

**Comment by syrekable** [comment]
Same here

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['MY_VALID_YOUTUBE_LINK, '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.12 (CPython) - macOS-12.6-arm64-arm-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] QPHfcPewW3g: Downloading webpage
[youtube] QPHfcPewW3g: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by AtomicJohnny201** [comment]
> > Confirmed - something seems to have just changed in youtube's page layout.
> > Commenting line [1794](https://github.com/ytdl-org/youtube-dl/blob/2021.12.17/youtube_dl/extractor/youtube.py#L1794) of `youtube_dl/extractor/youtube.py` seems to resolve the problem temporarily.
> 
> Can confirm, commenting out this line made it work

I'm sorry but how does one do this exactly? Asking for a noob..

**Comment by Brandon23z** [comment]
Same issue here. 

> > Confirmed - something seems to have just changed in youtube's page layout.
> > Commenting line [1794](https://github.com/ytdl-org/youtube-dl/blob/2021.12.17/youtube_dl/extractor/youtube.py#L1794) of `youtube_dl/extractor/youtube.py` seems to resolve the problem temporarily.
> 
> Can confirm, commenting out this line made it work

Can someone explain where this is on my PC if I did a pip install? I could not seem to find this directory, guessing because pip managed the installation.

**Comment by desinfectuser** [comment]
Same here

```
 $ youtube-dl https://www.youtube.com/watch?v=4gSEhNPKT9g --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=4gSEhNPKT9g', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.19.0-32-generic-x86_64-with-Ubuntu-22.04-jammy
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube] 4gSEhNPKT9g: Downloading webpage
[youtube] 4gSEhNPKT9g: Downloading player 11e3a4ec
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

**Comment by jmoverley** [comment]
> > > Confirmed - something seems to have just changed in youtube's page layout.
> > > Commenting line [1794](https://github.com/ytdl-org/youtube-dl/blob/2021.12.17/youtube_dl/extractor/youtube.py#L1794) of `youtube_dl/extractor/youtube.py` seems to resolve the problem temporarily.
> > 
> > 
> > Can confirm, commenting out this line made it work
> 
> I'm sorry but how does one do this exactly? Asking for a noob..

if you've installed via youtune-dlg on M$ you can't as you will have a compiled version of the tool.. just need to wait for an new build / release..

**Comment by tig99xx-834-77** [comment]
> Same issue here.
> 
> > > Confirmed - something seems to have just changed in youtube's page layout.
> > > Commenting line [1794](https://github.com/ytdl-org/youtube-dl/blob/2021.12.17/youtube_dl/extractor/youtube.py#L1794) of `youtube_dl/extractor/youtube.py` seems to resolve the problem temporarily.
> > 
> > 
> > Can confirm, commenting out this line made it work
> 
> Can someone explain where this is on my PC if I did a pip install? I could not seem to find this directory, guessing because pip managed the installation.

I am not sure where the file would be by default after a PIP install.  But you can always do a search for the file.
Sample search is below.  You don't have to use "sudo".

```
$ sudo find / -iname "youtube.py"
/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py
```

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar bug reports including closed ones

Really?

#30839

**Comment by tml** [comment]
I wasn't "guessing at a fix", I was very careful to state that it `seems to resolve the problem` and even noted _temporarily_. I had a very urgent and immediate need for ytdl to work, and there was obviously a very recent issue about the problem when I hit github. I left it there as a trace for other users who might have the same pressing need as I did.

**Comment by dirkf** [comment]
I say again:
>... when an actual fix has already been committed

And which would have apparent from following the guidance in #30839.

**Comment by tml** [comment]
Except that I'm not the one who opened the issue…I came here to see if it was a known issue, discovered it was, and provided other users a temporary solution I had discovered. Are you trying to suggest that you expect users to search for closed issues when an open issue exists that reproduces their problem? That's like continuing to look for your car keys after you found them.

**Comment by dirkf** [comment]
Yes, the issue template **specifically** asks for the search to cover closed issues, which might seem strange at first.

Sometimes the GitHub infrastructure may automatically close an issue that would have better been left open, or an issue may have been closed because the problem seemed to have been transient or otherwise not reproducible, as with #31530.

Also https://github.com/ytdl-org/youtube-dl/issues/31613#issuecomment-1437509345.

However I do appreciate that you presented the fix as temporary.
