### ISSUE TITLE
How can I patch youtube-dl?

### ISSUE THREAD

**Issue by Trenix25** [ytdl-org/youtube-dl#31617]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

It's my understanding that the source code for youtube-dl was restricted and that users must obtain special permission ever since the legal battle.  How then am I supposed to apply a patch to get the current version working again if I am unable to download the source code?  Why is it such an issue to simply patch the software and make the new release available so users can download and install it?

**Comment by nicolaasjan** [comment]
> It's my understanding that the source code for youtube-dl was restricted

Not at all. 🙂

> How then am I supposed to apply a patch to get the current version working again if I am unable to download the source code?

`git clone https://github.com/ytdl-org/youtube-dl.git`
(or download `zip`).

![screenshot1](https://user-images.githubusercontent.com/14093220/220073161-6e40d90d-21b5-466f-a6f3-dbf8a55564d6.png)

**Comment by dirkf** [comment]
Also, #31530.
