### ISSUE TITLE
unable to extract issue

### ISSUE THREAD

**Issue by hassan745** [ytdl-org/youtube-dl#31621]
hi, wherever I past the link on YouTube downloader tool for downloading the video then it will show that... Unable to extract uploader id

## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by hassan745** [comment]
I Don't have experience to report any issue or bug, please help me as soon as possible... video is not downloading on '' YouTube video downloader''  it shows Unable to extract uploader id

**Comment by nibaro-sbT** [comment]
If you go to the github page clone the project and run it with __main__.py it works.

**Comment by nicolaasjan** [comment]
**Pinned issue**:
READ THIS BEFORE OPENING A NEW ISSUE! #30839

> Known issues, fixed in git master code:
> 
> - [YouTube: Unable to extract uploader id](https://github.com/ytdl-org/youtube-dl/issues/31530)

**Comment by dirkf** [comment]
#30839
