### ISSUE TITLE
Unable to extract uploder id

### ISSUE THREAD

**Issue by jgr-indicium** [ytdl-org/youtube-dl#31637]
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unhandled exception in decode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/snap/youtube-dl/4806/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1524, in _n_descramble
    raise ExtractorError('Unhandled exception in decode')
youtube_dl.utils.ExtractorError: Unhandled exception in decode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
jgr@JGR-Acer:~$ youtube-dl -x --audio-format mp3 https://youtu.be/ei3IaJDgZGk?list=RDEM4AA8-pox5guE4W_YtyQAFw
[youtube:tab] Downloading playlist RDEM4AA8-pox5guE4W_YtyQAFw - add --no-playlist to just download video ei3IaJDgZGk
[youtube:tab] RDEM4AA8-pox5guE4W_YtyQAFw: Downloading webpage
[download] Downloading playlist: Mix - Violet Orlandi
[youtube:tab] playlist Mix - Violet Orlandi: Downloading 25 videos
[download] Downloading video 1 of 25
[youtube] ei3IaJDgZGk: Downloading webpage
[youtube] ei3IaJDgZGk: Downloading player 11e3a4ec
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unhandled exception in decode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/snap/youtube-dl/4806/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1524, in _n_descramble
    raise ExtractorError('Unhandled exception in decode')
youtube_dl.utils.ExtractorError: Unhandled exception in decode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by s3lfish** [comment]
I appear to have the same issue:

`youtube-dl -f mp4 "https://www.youtube.com/watch?v=queN9r3Leis" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'mp4', 'https://www.youtube.com/watch?v=queN9r3Leis', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: ba6d87eed
[debug] Python version 3.10.10 (CPython) - macOS-13.2.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube] queN9r3Leis: Downloading webpage
[youtube] queN9r3Leis: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by Rajendran61** [comment]
I also have the same issue - unable extract uploader id.
[youtube] Omd25Ys-cqc: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[rasu@rndr Downloads]$ yt22 --verbose "https://www.youtube.com/watch?v=Omd25Ys-cqc"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '22', '-o', '%(title)s.%(ext)s', '--verbose', 'https://www.youtube.com/watch?v=Omd25Ys-cqc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.5 (CPython) - Linux-5.18.9-arch1-1-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0.1, ffprobe 5.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Omd25Ys-cqc: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Anduin2017** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by jgr-indicium** [comment]
@Anduin2017 Thanks a lot. @:-))

**Comment by housejunkies01** [comment]
Go here to get the last update https://github.com/yt-dlp/yt-dlp/tree/2023.02.17#installation
the new yt-dlp allows you to download again.

**Comment by fabzzap** [comment]
Same. Just git pull'ed
```dev/youtube-dl/bin/youtube-dl --verbose https://www.youtube.com/watch?v=6y2sXujxfxc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=6y2sXujxfxc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 6067451e4
[debug] Python version 3.10.7 (CPython) - Linux-5.19.0-31-generic-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg 5.1.1, ffprobe 5.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 6y2sXujxfxc: Downloading webpage
[debug] [youtube] Decrypted nsig o7KLx5PhazHSqr15 => 9VpE98cSDr5PYw
[debug] [youtube] Decrypted nsig Zd81T6lTPms49i-L => PHe2TrM_2GTW-w
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Then download succeeds. The `unable to extract uploader id` worries however

**Comment by jgr-indicium** [comment]
@all 
++++++++++++++++++++++++++++++++++++++++++
Ubuntu 33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC 
Kernel: 5.19.0-32-generic
bash command: _sudo snap install yt-dlp_
++++++++++++++++++++++++++++++++++++++++++
Greetings from jgr-indicium
@:-).

**Comment by jgr-indicium** [comment]
@ALL
It runs just Audio extract! (_Google kriegt den Hals nicht voll_) @:-(
@:-).

**Comment by dirkf** [comment]
There's never a reason to install yt-dl, and probably not yt-dlp, with snap. Use Python.

**Comment by jgr-indicium** [comment]
I now. @:-).

**Comment by jgr-indicium** [comment]
yt-dlp --extract-audio --audio-format mp3 --audio-quality 0 --verbose https://www.youtube.com/watch?v=k1dKwqFwE-4
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[debug] Command-line config: ['--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', '--verbose', 'https://www.youtube.com/watch?v=k1dKwqFwE-4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b]
[debug] Lazy loading extractors is disabled
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.19.0-32-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1730 extractors
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=k1dKwqFwE-4
[youtube] k1dKwqFwE-4: Downloading webpage
[youtube] k1dKwqFwE-4: Downloading android player API JSON
ERROR: [youtube] k1dKwqFwE-4: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/snap/yt-dlp/178/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 678, in extract
    ie_result = self._real_extract(url)
  File "/snap/yt-dlp/178/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 4018, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/snap/yt-dlp/178/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1232, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
???

**Comment by dirkf** [comment]
> `yt-dlp --extract-audio --audio-format mp3 --audio-quality 0 --verbose https://www.youtube.com/watch?v=k1dKwqFwE-4`

#30839
