### ISSUE TITLE
Cannot download video

### ISSUE THREAD

**Issue by jewmastersol** [ytdl-org/youtube-dl#31638]
Writes: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

But i have last version
![image](https://user-images.githubusercontent.com/125995185/220383574-5af7dd3a-380c-4dc1-b07f-54f547a91e97.png)

**Comment by DjangoFR** [comment]
The same here for https://www.youtube.com/watch?v=GIjTLW7soBk

$ ▶ ./youtube-dl --version
2021.12.17

**Comment by redve-dev** [comment]
same here

**Comment by Yaroslav-Ch** [comment]
I am joining. I have the same

deb-usr@debian-pc:~$ /snap/bin/youtube-dl --verbose https://youtu.be/q0hyYWKXF0Q
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://youtu.be/q0hyYWKXF0Q']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.9 (CPython) - Linux-5.10.0-19-amd64-x86_64-with-glibc2.25
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11
[debug] Proxy map: {}
[youtube] q0hyYWKXF0Q: Downloading webpage
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unhandled exception in decode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/snap/youtube-dl/4806/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1524, in _n_descramble
    raise ExtractorError('Unhandled exception in decode')
youtube_dl.utils.ExtractorError: Unhandled exception in decode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/snap/youtube-dl/4806/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 816, in wrapper
    return func(self, *args, **kwargs)
  File "/snap/youtube-dl/4806/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 837, in __extract_info
    ie_result = ie.extract(url)
  File "/snap/youtube-dl/4806/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/snap/youtube-dl/4806/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1974, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/snap/youtube-dl/4806/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output

**Comment by Anduin2017** [comment]
#31530

**Comment by RayRiver21** [comment]
I'm having same problem

**Comment by darkberet** [comment]
Same issue. Any estimated time when can we expect an update?

**Comment by telecomguyML** [comment]
> Same issue. Any estimated time when can we expect an update?

Your best bet is to follow the other issue report https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by Vangelis66** [comment]
To OP, as well as to all `me, too`s: 

Have you followed the **recommended procedure** on opening a **NEW ISSUE** in this tracker? It's a PINNED issue: 

![NI](https://user-images.githubusercontent.com/9669492/220207414-6870b63d-e78a-4873-ade4-d55442c69aa9.png)

i.e. #30839 

Had you done that, you'd have performed a search for existing issues with the  ERROR 
`ERROR: Unable to extract uploader id`
and (hopefully) you'd have found ca. **110 duplicate issues** with the same/similar error message, plus links to the originating issue (now a [megathread](https://github.com/ytdl-org/youtube-dl/issues/31530)), with content and info on how to hopefully remedy your predicament...

BTW, the 
`WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled`
warning has also been taken care of in `git-master`...
