### ISSUE TITLE
Error in teamspeak bot

### ISSUE THREAD

**Issue by rmoradi2019** [ytdl-org/youtube-dl#31643]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

Hi im using of script on windows for teamspeak bot , 5 day ago bot is good but now i get error Could not load. (youtube-dl failed to load the resource.) 
after using VPN i get error Your value is out of range. Select one between 0 and 0.
can you help me!

**Comment by dirkf** [comment]
Check #31530 in case that's your problem.

Otherwise, we can't help with "teamspeak bot", whatever it might be; does it have it own support channel? See #30839.

**Comment by snizzo** [comment]
@rmoradi2019 Are you using https://github.com/Splamy/TS3AudioBot ?

**Comment by dirkf** [comment]
In which case the answer is https://github.com/Splamy/TS3AudioBot/issues/1022#issuecomment-1435762931, based on #31530. If that doesn't solve your problem, please read #30839 to determine if you should raise a new issue here
