### ISSUE TITLE
Request for a new release of youtube-dl

### ISSUE THREAD

**Issue by BlackRNG** [ytdl-org/youtube-dl#31644]
## Checklist

- [x] I'm reporting a feature request (a new release request)
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Preface
Hello everyone! We hope this message finds you well. We are writing to kindly request a new release of youtube-dl. As many of you know, it has been quite some time since the last release, and we believe that it is time for a new one. In fact, since 2021, there have been no new releases, and we understand that people worldwide require it for archiving purposes, particularly in today's climate of increased censorship and herd mentality. The ability to download and preserve online content is more important than ever, and a new release of youtube-dl would help users continue to exercise their rights to access information freely.

## Description

With that said, we are wondering if there is any plan to release a new version of youtube-dl in the near future?

We believe that a new release would bring many benefits, such as bug fixes, new features, and compatibility updates with the latest changes in popular video hosting platforms. These benefits are crucial for our users to have a better experience when using youtube-dl, and we are committed to providing the best possible experience.

We also understand that releasing a new version can be a challenging task, especially considering the recent legal issues that the project has faced. We want to assure you that we support your efforts in maintaining this project and that we are willing to offer our support and help in any way we can. We believe that the new release will demonstrate the resilience of this project and its importance in enabling free and open access to information on the internet.

<br>

Thank you so much for your attention to this matter, and we hope that you take our request into consideration. We appreciate your hard work and dedication to this project, and we are looking forward to a new release that will benefit everyone. If you have any questions or concerns, please do not hesitate to contact us. Thanks again!

**Comment by Wooden-Toilet** [comment]
Very well said, and I hope a kind soul out there can bring this to the masses o7

**Comment by nicolaasjan** [comment]
Duplicate.
Read the issue [here](https://github.com/ytdl-org/youtube-dl/issues/31585).

> A new release is overdue but depends on solving certain cross-platform issues in the CI build process. Meanwhile for the main platforms, see #31530 for update hints.

**Comment by ananay** [comment]
The only way I could get it to work was cloning the repository, `cd`ing into the cloned repository and running using `python3 -m youtube_dl -x --audio-format mp3 <URL>`.
