### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by VedantMadane** [ytdl-org/youtube-dl#31648]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```

C:\Users\vedantm>youtube-dl "https://www.youtube.com/playlist?list=PLUkh9m2BorqndWimijiJ-VCAXjJUrzJQU"
[youtube:tab] PLUkh9m2BorqndWimijiJ-VCAXjJUrzJQU: Downloading webpage
[download] Downloading playlist: Foundations of Finance
[youtube:tab] playlist Foundations of Finance: Downloading 12 videos
[download] Downloading video 1 of 12
[youtube] aK4qHbDkJ-s: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\vedantm>youtube-dl --version
2021.12.17

C:\Users\vedantm>
```
![image](https://user-images.githubusercontent.com/6527493/220606229-784d41be-d31c-4c0c-a8f2-84e2f429f9fc.png)

## Description

Error message: "Unable to extract uploader id; please report this issue"
Version: 2021.12.17

**Comment by Anduin2017** [comment]
#31530

**Comment by dirkf** [comment]
> [x] I've searched the bugtracker for similar bug reports including closed ones

Yet not really? #30839
