### ISSUE TITLE
RegexNotFoundError while downloading youtube.com video

### ISSUE THREAD

**Issue by squareturn** [ytdl-org/youtube-dl#31649]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl --verbose 'https://www.youtube.com/watch?v=yDo0wX1pK4c'
[debug] System config: []
[debug] User config: ['-o', './%(title)s.%(ext)s', '--xattrs']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=yDo0wX1pK4c']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.6 (CPython) - macOS-13.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-97117-gb5a8ad5623-tessus, ffprobe 4.2.2-tessus
[debug] Proxy map: {}
[youtube] yDo0wX1pK4c: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/spell/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/spell/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/spell/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Users/spell/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/Users/spell/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ youtube-dl --version
2021.12.17
$ youtube-dl -U
youtube-dl is up-to-date (2021.12.17)
$
```

## Description

While attempting to download a video from youtube, an RegexNotFoundError is thrown and the download fails.

Running on macOS Ventura (13.1)

**Comment by OPStellar** [comment]
Likewise

$ youtube-dl --no-check-certificate --audio-quality 0 --format mp4 https://www.youtube.com/watch?v=QTXLdCMOw3Y --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check-certificate', '--audio-quality', '0', '--format', 'mp4', 'https://www.youtube.com/watch?v=QTXLdCMOw3Y', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.8 (CPython) - macOS-10.14.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube] QTXLdCMOw3Y: Downloading webpage
[youtube] QTXLdCMOw3Y: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id

$ youtube-dl --version
2021.12.17

**Comment by Biler49** [comment]
Hi!
You have youtube-dl to update to version 2023.02.17.
I did it this simple way:
Fetch it at https://github.com/yt-dlp/yt-dlp/releases/tag/2023.02.17
Move the downloaded yt-dlp-file to /usr/local/bin/youtube-dl
chmod a+rwx
works!

**Comment by dirkf** [comment]
> [ ] I've searched the bugtracker for similar bug reports including closed ones

Do it: #30839.

**Comment by squareturn** [comment]
Thanks for the suggestion.  I wasn’t aware of the yt-dlp fork.

The 2023.02.17 tag works as expected.




 
Steven Pelletier | Consulting Engineer
SquareTurn Technology, Inc.
46 Cedar Street
West Barnstable, MA 02668
***@***.*** ***@***.***>
+1 (617) 650-3929 <tel:+16176503929>
This email, including attachments, contains private, confidential and/or privileged information for the sole use of the intended recipient(s). Any review, use, distribution or disclosure is strictly prohibited. If you are not the intended recipient or authorized by the recipient, please reply to this e-mail and delete all copies of this message.

**Comment by 8dcc** [comment]
> Hi! You have youtube-dl to update to version 2023.02.17. I did it this simple way: Fetch it at https://github.com/yt-dlp/yt-dlp/releases/tag/2023.02.17 Move the downloaded yt-dlp-file to /usr/local/bin/youtube-dl chmod a+rwx works!

This fixed the issue for me.
