### ISSUE TITLE
*NOOB*

### ISSUE THREAD

**Issue by kela-iah** [ytdl-org/youtube-dl#31651]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Hi, I am on mac OS and love youtube-dl.

Recently (today), I have become unable to download YT videos, receiving an error message of the following: "ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

I am using the latest version & I don't know how to extract the uploader id.

*edit* I am currently trying to reinstall through brew, hopefully that works.

**Comment by dirkf** [comment]
Don't bother.
Start again at pinned issue #30839.
