### ISSUE TITLE
"Troubleshooting: youtube-dl Not Working on Windows 11 - How to Fix It"

### ISSUE THREAD

**Issue by wheels3321** [ytdl-org/youtube-dl#31654]
"I am having an issue with youtube-dl where I am unable to download YouTube videos on Windows 11. When attempting to download a video, I receive the error message 'Downloading webpage ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug. Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.'

I have tried updating to the latest version of youtube-dl and calling it with the --verbose flag, but the issue persists. Can you please provide any advice or guidance on how to resolve this issue? Thank you for your help."

**Comment by dirkf** [comment]
#30839
