### ISSUE TITLE
Famous streaming website Sibnet.ru

### ISSUE THREAD

**Issue by trimechee** [ytdl-org/youtube-dl#31652]
Hello, thank you for this great videos dowloader !

 I discover famous Sibnet streaming website and it will be great and awesome to add support of this wonrderful website that has many interesting videos ! Thank you so much !

Example URLs
https://video.sibnet.ru/day/20230223/video5054979-K_2023_gotov/?utm_source=main_page&utm_medium=video_block_day&utm_cmpaign=main_page_may

https://video.sibnet.ru/

Here the logs : 
```
18:39:48, youtube-dl (external): 2023.2.17
18:39:48, libcurl (internal): libcurl/7.68.0 Schannel zlib/1.2.11 brotli/1.0.7 nghttp2/1.40.0
18:39:48, ffmpeg (internal): lavf 58.29.100, lavc 58.54.100, lavu 56.31.100
18:39:48, #01, Analysis, https://video.sibnet.ru/day/20230223/video5054979-K_2023_gotov?utm_source=main_page&utm_medium=video_block_day&utm_cmpaign=main_page_may
18:39:48, #01, Opening given  URL...
18:40:00, [warning] youtube-dl: WARNING: [generic] Falling back on generic information extractor
18:40:00, skipped results from 'generic' youtube-dl extractor: analyzing URLs from unsupported sites is disallowed
18:40:00, [error] #01, Analysis, unsupported site URL
18:40:00, #01, Ready
```

**Comment by dirkf** [comment]
For a URL like https://video.sibnet.ru/day/20230223/video5054979-K_2023_gotov with id `5054979`, use the equivalent embed URL https://video.sibnet.ru/shell.php?videoid=5054979, which is supported by the generic extractor.

**Comment by trimechee** [comment]
@dirkf Geat awesome marvellous !!!! Thank you very much for your precious help ! 💯 🥇

**Comment by dirkf** [comment]
If anyone wanted a specific extractor for Sibnet to bypass the work-around, the [site support template](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=site-support-request&template=2_site_support_request.md) would have to be completed in full.

**Comment by trimechee** [comment]
Great ! thank you :)

**Comment by Vangelis66** [comment]
>For a URL like 
https://video.sibnet.ru/day/20230223/video5054979-K_2023_gotov 
with id `5054979`, use the equivalent embed URL 
https://video.sibnet.ru/shell.php?videoid=5054979
, which is supported by the generic extractor.
...
If anyone wanted a specific extractor for Sibnet to **bypass the work-around**

... I find **no workaround is needed** if using `git master` code (here in the form of latest "daily" build): 
```shell
yt-dl -v "https://video.sibnet.ru/day/20230223/video5054979-K_2023_gotov" => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', '.\\FFmpeg', '--external-downloader-args', '-v 8 -stats', '-v', 'https://video.sibnet.ru/day/20230223/video5054979-K_2023_gotov']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2023.02.23.114514
** This build is unofficial daily builds, provided for ease of use.
** Please do not ask for any support.
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg n5.2-dev-2245-N-109649-gab8cde6, ffprobe n5.2-dev-2245-N-109649-gab8cde6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] video5054979-K_2023_gotov: Requesting header
[redirect] Following redirect to https://video.sibnet.ru/day/20230223/video5054979-K_2023_gotov/
[generic] video5054979-K_2023_gotov: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video5054979-K_2023_gotov: Downloading webpage
[generic] video5054979-K_2023_gotov: Extracting information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://video.sibnet.ru/v/76db96a8ac0a0d1f4dc7e8812b87d0e0/5054979.mp4'
[download] Destination: К 2023 готов-video5054979-K_2023_gotov.mp4
[download] 100% of 8.22MiB in 00:27
```

**Comment by trimechee** [comment]
Awesome ! thank you :)

**Comment by professeurjt** [comment]
yt-dl not working for sibnet , I just tried a simple method and it works well if it helps you to be able to download from sibnet; I don't know if I have the right to leave you the link! but hey I just do it if it can help. Thank you and good day. 

- youtu.be/xbRl8Vs7pkE

**Comment by trimechee** [comment]
@professeurjt Gorgeous  awesome amazing ! We are very grateful to you, thank you very much ! 🥇 💯

**Comment by dirkf** [comment]
>yt-dl not working for sibnet

@professeurjt, please post URL and verbose log showing this. 

This is not the place to promote your own tools without contributing to the development of yt-dl and certainly not in a video link with no supporting text.

**Comment by Vangelis66** [comment]
> please post URL

This is the sample `sibnet.ru` link contained in the YT clip posted above: 

https://video.sibnet.ru/video4834221-One_Piece_110_VF/

I find this link has no trouble "working" with the latest yt-dl `master` code: 
```console
yt-dl -v "https://video.sibnet.ru/video4834221-One_Piece_110_VF/" => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', '.\\FFmpeg', '--external-downloader-args', '-v 8 -stats', '-v', 'https://video.sibnet.ru/video4834221-One_Piece_110_VF/']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2023.09.24.2107
[debug] Lazy loading extractors enabled
[debug] Single file build
[debug] Python 3.4.10 (CPython x86 32bit) - Windows-Vista-6.0.6003-SP2 - OpenSSL 1.0.2k  26 Jan 2017
[debug] exe versions: ffmpeg n6.1-dev-2615-N-112499-ga76b409, ffprobe n6.1-dev-2615-N-112499-ga76b409, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] video4834221-One_Piece_110_VF: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video4834221-One_Piece_110_VF: Downloading webpage
[generic] video4834221-One_Piece_110_VF: Extracting information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://video.sibnet.ru/v/917402f6cf4406d6680e06eaa2b9dd31/4834221.mp4'
[download] Destination: One_Piece_110_VF-video4834221-One_Piece_110_VF.mp4
[download]   3.9% of 282.76MiB at 187.93KiB/s ETA 24:40
```
... with the only irritant being a **server-throttled** download 😠 ...

Precompiled `yt-dl-nightly` builds below:

https://github.com/ytdl-org/ytdl-nightly/releases/tag/2023.09.25

**Comment by trimechee** [comment]
Mr @dirkf, thank you, Mr @professeurjt did not promote any tool because his solution to download the video does not use any software or script, just by going to the source code of the page in the network section look for the mp4 extension.....

Mr @professeurjt was very kind to make an explanatory videojust wants to help people who have difficulty downloading from this site and we thank you and we thank youtube-dl for all your efforts to make these magnificent software and tips :)

**Comment by dirkf** [comment]
What I said. This is an issue tracker for youtube-dl, not r/learn-how-to-use-browser-devtools.

**Comment by trimechee** [comment]
@dirkf , yes , @professeurjt was generous  to share with us a tip to temporarily fix this problem while waiting for our bleoved youtube-dl to fix this problem, thank you everyone :) 👍 💯

**Comment by professeurjt** [comment]
Merci MR @trimechee, tout ce que vous avez dit est vrai, tout ce que je voulais, c'est partager ce conseil avec vous, pour aider ceux qui veulent télécharger pour le moment à partir du site concerné, alors si cela peut aider les développeurs de youtube-dl.  Je n'ai fait la promotion d'aucun outil, sinon je suis désolé.

**Comment by professeurjt** [comment]
Thank you MR @trimechee, everything you said is true, all I wanted is to share this tip with you, to help those who want to download for the moment from the site concerned, then if it can help the developers of youtube-dl.

I didn't promote any tools, otherwise I'm sorry.

**Comment by trimechee** [comment]
Ouiii M @professeurjt , svp ne vous en faites pas et j'espère ce malentendu avec autre internaute ne vous a pas trop vexé ! 

C'est un simple malentendu et on vous remercie encore pour votre effort généreux et bienveillant  à faire cette magnfique video instructive qui nous facilite la vie ! 

Et on espère tu nous partageras encore d'autres vidéos magnfiques de ce genre sur votre magnifique chaine youtube :) 🥇 💯

**Comment by dirkf** [comment]
Vraiment, ce que j'ai dit!

> ... waiting for our beloved youtube-dl to fix this problem

[Which problem?](https://github.com/Vangelis66)

What problem?

**Comment by professeurjt** [comment]
Je vous remercie beaucoup Mr @trimechee , c'est vraiment gentil 🙏
