### ISSUE TITLE
Cannot download site 'https://www.youtube.com/watch?v=nj-fytN79qc'

### ISSUE THREAD

**Issue by HarryDolan** [ytdl-org/youtube-dl#31656]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

# youtube-dl 'https://www.youtube.com/watch?v=nj-fytN79qc'
[youtube] nj-fytN79qc: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by nicolaasjan** [comment]
> [ x] I've searched the bugtracker for similar bug reports including closed ones

https://github.com/ytdl-org/youtube-dl/issues?q=Unable+to+extract+uploader+id

 Please do that first.

And:

[Read this before opening a new issue](https://github.com/ytdl-org/youtube-dl/issues/30839)

> Known issues, fixed in git master code:
> 
> - [YouTube: Unable to extract uploader id](https://github.com/ytdl-org/youtube-dl/issues/31530)

**Comment by UnicodeMan** [comment]
I've had these problems to the point of seemingly making youtube-dl completely broken. If it's fixed in master, why doesn't anyone release a new version?

**Comment by nicolaasjan** [comment]
> If it's fixed in master, why doesn't anyone release a new version?

They're trying to, but it's rather complicated:  
https://github.com/ytdl-org/youtube-dl/pull/30644

But you could get a "nightly" version from [here](https://github.com/ytdl-patched/youtube-dl/releases).

**Comment by dirkf** [comment]
> [ x] I've searched the bugtracker for similar bug reports including closed ones

Yet not well.

**Comment by HarryDolan** [comment]
Thank you for your help.  yt-dlp worked for me.

Harry
