### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by leoxu1007** [ytdl-org/youtube-dl#31658]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

 u0_a131@localhost  /storage/emulated/0/Video  youtube-dl https://www.youtube.com/watch\?v\=qtQmuFuifzs\&list\=RDqtQmuFuifzs\&start_radio\=1 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=qtQmuFuifzs&list=RDqtQmuFuifzs&start_radio=1', '--verbose']
[debug] Encodings: locale utf-8, fs utf-8, out utf-8, pref utf-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.2 (CPython) - Linux-3.10.84-perf-gfcc38b5-04658-g8b3c663-aarch64-with-libc
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube:tab] Downloading playlist RDqtQmuFuifzs - add --no-playlist to just download video qtQmuFuifzs
[youtube:tab] RDqtQmuFuifzs: Downloading webpage
[download] Downloading playlist: Mix - YOASOBI「好きだ」 from 『ROCK IN JAPAN FESTIVAL 2022』2022.8.06@千葉市蘇我スポーツ公園
[youtube:tab] playlist Mix - YOASOBI「好きだ」 from 『ROCK IN JAPAN FESTIVAL 2022』2022.8.06@千葉市蘇我スポーツ公園: Downloading 25 videos
[download] Downloading video 1 of 25
[youtube] qtQmuFuifzs: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

WRITE DESCRIPTION HERE

 u0_a131@localhost  /storage/emulated/0/Video  youtube-dl https://www.youtube.com/watch\?v\=qtQmuFuifzs\&list\=RDqtQmuFuifzs\&start_radio\=1
[youtube:tab] Downloading playlist RDqtQmuFuifzs - add --no-playlist to just download video qtQmuFuifzs
[youtube:tab] RDqtQmuFuifzs: Downloading webpage
[download] Downloading playlist: Mix - YOASOBI「好きだ」 from 『ROCK IN JAPAN FESTIVAL 2022』2022.8.06@千葉市蘇我スポーツ公園
[youtube:tab] playlist Mix - YOASOBI「好きだ」 from 『ROCK IN JAPAN FESTIVAL 2022』2022.8.06@千葉市蘇我スポーツ公園: Downloading 25 videos
[download] Downloading video 1 of 25
[youtube] qtQmuFuifzs: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ivesleon** [comment]
same problem ERROR: Unable to extract uploader id

**Comment by epogrebnyak** [comment]
same for me

**Comment by mcepl** [comment]
[This patch](https://github.com/yt-dlp/yt-dlp/commit/149eb0bbf34fa8fdf8d1e2aa28e17479d099e26b) seems to fix this.

**Comment by epogrebnyak** [comment]
> [This patch](https://github.com/yt-dlp/yt-dlp/commit/149eb0bbf34fa8fdf8d1e2aa28e17479d099e26b) seems to fix this.

I got 2021.12.17, but the problem is still there

**Comment by mcepl** [comment]
Yes, that patch has not been applied there.

**Comment by epogrebnyak** [comment]
> [This patch](https://github.com/yt-dlp/yt-dlp/commit/149eb0bbf34fa8fdf8d1e2aa28e17479d099e26b) seems to fix this.

My wrong:
 ```yt-dlp  --version                                               
2023.02.17```

works now. Thank you for the clue!

**Comment by leoxu1007** [comment]
u0_a131@localhost  /storage/emulated/0/Video  youtube-dl https://www.youtube.com/watch\?v\=qtQmuFuifzs\&list\=RDqtQmuFuifzs\&start_radio\=1 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=qtQmuFuifzs&list=RDqtQmuFuifzs&start_radio=1', '--verbose']
[debug] Encodings: locale utf-8, fs utf-8, out utf-8, pref utf-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.2 (CPython) - Linux-3.10.84-perf-gfcc38b5-04658-g8b3c663-aarch64-with-libc
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube:tab] Downloading playlist RDqtQmuFuifzs - add --no-playlist to just download video qtQmuFuifzs
[youtube:tab] RDqtQmuFuifzs: Downloading webpage
[download] Downloading playlist: Mix - YOASOBI「好きだ」 from 『ROCK IN JAPAN FESTIVAL 2022』2022.8.06@千葉市蘇我スポーツ公園
[youtube:tab] playlist Mix - YOASOBI「好きだ」 from 『ROCK IN JAPAN FESTIVAL 2022』2022.8.06@千葉市蘇我スポーツ公園: Downloading 25 videos
[download] Downloading video 1 of 25
[youtube] qtQmuFuifzs: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by leoxu1007** [comment]
Actually I am useing termux on Android 7.0, and ssh to my android phone, then I pkg install python and pip install youtube_dl

**Comment by Diamondemon** [comment]
> Actually I am using termux on Android 7.0, and ssh to my android phone, then I pkg install python and pip install youtube_dl

Yes, it looks like the version of the python package has not received any update for the last 14 months, sadly.

**Comment by zhongdj** [comment]
I have same problem, any fix?

**Comment by karstengit** [comment]
> [This patch](https://github.com/yt-dlp/yt-dlp/commit/149eb0bbf34fa8fdf8d1e2aa28e17479d099e26b) seems to fix this.

How can this patch be applied to the script?

Another example that does not work:
```
youtube-dl --verbose -x --audio-format best  https://youtu.be/FWTyW3n97mM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-x', '--audio-format', 'best', 'https://youtu.be/FWTyW3n97mM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-20-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0
[debug] Proxy map: {}
[youtube] FWTyW3n97mM: Downloading webpage
[youtube] FWTyW3n97mM: Downloading player 11e3a4ec
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by dirkf** [comment]
#30839

**Comment by dirkf** [comment]
>Actually I am using termux on Android 7.0, and ssh to my android phone, then I pkg install python and pip install youtube_dl

Use _pip_ to install the latest git master. If your environment has no _git_, install it from the tar.gz supplied by GitHub instead. See #31530.

**Comment by karstengit** [comment]
Hello dirkf,

what are the steps that must be done to get the current version of youtube-dl?

Can you please update the readme.

**Comment by karstengit** [comment]
Pip often has problems. But for others - this works:

```
git clone https://github.com/ytdl-org/youtube-dl.git youtube-dl
cd youtube-dl
make youtube-dl
```

It would be helpful when this post will not be hidden.

**Comment by karstengit** [comment]
With the actual git version the download works.
But there is still the error message in the verbose output:

```
youtube-dl --verbose -x --audio-format best  https://youtu.be/FWTyW3n97mM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-x', '--audio-format', 'best', 'https://youtu.be/FWTyW3n97mM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-20-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0
[debug] Proxy map: {}
[youtube] FWTyW3n97mM: Downloading webpage
[youtube] FWTyW3n97mM: Downloading player 11e3a4ec
[debug] [youtube] Decrypted nsig dPg2grcZFUwErvhT => XrU8KU170TN6wg
[debug] [youtube] Decrypted nsig 6Dp0f-OZTvLj837u => y0i88MrhP-vMbg
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Invoking downloader on 'https://rr1---sn-oxujvavbox-jbos.googlevideo.com/videoplayback?expire=1677169895&ei=h0D3Y6_aJpiP1gLjz6TADA&ip=87.79.98.121&id=o-AKWwiuYy2oEyMhEa9mnevFvQAL7KAyWvewchiy-ZZN4o&itag=251&source=youtube&requiressl=yes&mh=W4&mm=31%2C29&mn=sn-oxujvavbox-jbos%2Csn-4g5lzner&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=23&initcwndbps=2063750&vprv=1&mime=audio%2Fwebm&ns=zVmrel3_oUHWXa-iXcK1m5gL&gir=yes&clen=8073767&dur=477.181&lmt=1641877791557354&mt=1677147928&fvip=1&keepalive=yes&fexp=24007246&c=WEB&txp=5311224&n=XrU8KU170TN6wg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAP3zfzH8q8iYiyorJGzaM6TC-NaxPB0mu1j-rvbs8OFkAiAQh6kMYbHFRIiNyavpzwqN6DWt8OG94gOwh9VyiTKtvg%3D%3D&sig=AOq0QJ8wRQIgKaDn1_3tJpz0O7h7ev0L5niM8n6QwjjVdqbpYbaxjRwCIQDf0Rbu0fw894bU0B29d9_harvgc7ymqze1E2EuMCvcYw%3D%3D'
[download] Destination: Naturaleza - Danit-FWTyW3n97mM.webm
[download] 100% of 7.70MiB in 00:02
[debug] ffmpeg command line: ffprobe -show_streams 'file:Naturaleza - Danit-FWTyW3n97mM.webm'
[ffmpeg] Destination: Naturaleza - Danit-FWTyW3n97mM.opus
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Naturaleza - Danit-FWTyW3n97mM.webm' -vn -acodec copy 'file:Naturaleza - Danit-FWTyW3n97mM.opus'
Deleting original file Naturaleza - Danit-FWTyW3n97mM.webm (pass -k to keep)

```

**Comment by Vangelis66** [comment]
> But there is still the **error** message in the output:

It's NO LONGER an ERROR, but a simple warning:
`WARNING: unable to extract uploader id`
that doesn't thwart the actual downloading...
See [this](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1436130288) comment...

**Comment by p6002** [comment]
Any fix tor that? This is months guys.
