### ISSUE TITLE
No Video Downloading;  Linux Mint;  I've used apt,  curl and wget to make sure it's updated.

### ISSUE THREAD

**Issue by seaweedworkerz** [ytdl-org/youtube-dl#31665]
$ yt-dlp -x --audio-format mp3 --audio-quality 0 https://youtu.be/bpZvg_FjL3Q
[youtube] bpZvg_FjL3Q: Downloading webpage
[youtube] bpZvg_FjL3Q: Downloading android player API JSON
ERROR: [youtube] bpZvg_FjL3Q: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by dirkf** [comment]
#30839
