### ISSUE TITLE
Cannot download from Youtube

### ISSUE THREAD

**Issue by opale7001** [ytdl-org/youtube-dl#31663]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[youtube] q2tIe1wUcAI: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[opale7000@fedora ~]$ youtube-dl -U
youtube-dl is up-to-date (2021.12.17)
[opale7000@fedora ~]$
```

## Description

ERROR: Unable to extract uploader id;

**Comment by Vangelis66** [comment]
... You should've **really** started by loading and **following to the letter** PINNED issue #30839 😞 ...
... And Checklist is supposed to be adhered to, it isn't just there for you to ignore 😡 ...
