### ISSUE TITLE
RegexNotFoundError('Unable to extract %s' % _name)

### ISSUE THREAD

**Issue by burntstore-studio** [ytdl-org/youtube-dl#31678]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
wqbM"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '--audio-format', 'mp3', '--verbose', 'https://www.youtube.com/watch?v=-gsDBuHwqbM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.6 (CPython) - macOS-13.2.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube] -gsDBuHwqbM: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.9/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/jim/Library/Python/3.9/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/jim/Library/Python/3.9/lib/python/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Users/jim/Library/Python/3.9/lib/python/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/Users/jim/Library/Python/3.9/lib/python/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE
Good morning, trying to download a YouTube video for audio extraction, which I've done successfully before using the command line (except the URI).  This time, I get the noted regex error.

**Comment by dirkf** [comment]
> [x] I've searched the bugtracker for similar bug reports including closed ones

But not well enough: #30839.

**Comment by burntstore-studio** [comment]
I’m so sorry, and I won’t submit again, but I’d like to say I did search
and found similar bug reports, but none that mentioned the name regex
reported in my error.  I’m (sincerely) glad you found one duplicate, since
that someone will look into it.

I am sorry.

**Comment by dirkf** [comment]
I was hoping that people couldn't miss the pinned issue #30839 where (a) suggestions about how to search are given (b) the existing issue is listed as a Known Issue. Could it have been clearer, or does it just not show up prominently on the page, maybe on a phone browser?

**Comment by burntstore-studio** [comment]
Hi again,

The pinned issue stands out … I started there before my first attempt.
It’s also very carefully crafted, which I appreciate.

The label:duplicate stands out also, except I was a careless reader two
times and missed it. Saw it this third time reading now … This is
completely my fault.

Re: it being a known issue … I saw that, but was thinking too much like a
developer, and considered in *my* problem that was just a side-effect and
the real problem was the regex. Did I click through on that known issue :(
no I did not.

I hope my info is helpful, in at least learning that your post is well
prepared for a careful reader who isn’t skipping, and for that I apologize
:(

Be well, and thanks for not blowing your top at a newbie! :)

Jim

**Comment by posita** [comment]
@dirkf, #23926 might be the original issue, but that one is locked without any update since 2020. Its presence and apparent staleness might also inspire duplicate reports. (Not applicable to this filing, but just opining about potential noise contributors.)

**Comment by dirkf** [comment]
It isn't.

**Comment by posita** [comment]
> It isn't. Why would you think it is?

My bad. It sounded like a related issue or similar error. Please disregard.
