### ISSUE TITLE
GlobalPlayer

### ISSUE THREAD

**Issue by Treadspear** [ytdl-org/youtube-dl#31688]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: 
- Single video: https://www.globalplayer.com/podcasts/episodes/7Drf561/
- Playlist: https://www.globalplayer.com/podcasts/42KnZn/

## Description

Paywall: NO
Region Blocked: UNKNOWN
Region: GREAT BRITAIN 
Credentials Required: YES
Username: no-reply00456temp@treadspear.com
Password: no-reply00456temp@treadspear.com
Registration: https://www.globalplayer.com/register/

I am a new to the youtube-dl project and I am very impressed so far. I would like to make a script to archive some podcasts on the Global Player. Does anyone have some recommendations I can try to do this?

Thank you,

**Comment by Vangelis66** [comment]
Their site requires **an account/log-in** for audio and/or video content to start playing... That doesn't mean the same is true for `youtube-dl` 😉 ...
Since this is a **UK-based service**, some content might be geo-fenced  from overseas...

I find that the **generic** extractor can handle the "single video" (actually, it's **audio-only**) URI the OP provided: 
```cmd
yt-dl -v -c --no-part --write-description --write-thumbnail --add-metadata --embed-thumbnail "https://www.globalplayer.com/podcasts/episodes/7Drf561/" => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', '.\\FFmpeg', '--external-downloader-args', '-v 8 -stats', '-v', '-c', '--no-part', '--write-description', '--write-thumbnail', '--add-metadata', '--embed-thumbnail', 'https://www.globalplayer.com/podcasts/episodes/7Drf561/']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2023.02.24.43044
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg n5.2-dev-2245-N-109649-gab8cde6, ffprobe n5.2-dev-2245-N-109649-gab8cde6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 7Drf561: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 7Drf561: Downloading webpage
[generic] 7Drf561: Extracting information
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: There's no description to write.
[debug] Invoking downloader on 'https://dax.captivate.fm/637d3b2b-41eb-440d-ab2c-76d95c427ee2/LBC-UK-08022023-035818-08022023-043316.mp3?aw_0_1st.showid=4fb1b093-d258-4b00-ab19-4ffa3debb6cc\\u0026aw_0_1st.episodeid=185ae231-a952-41e9-9d29-eafe15192903'
[download] Destination: Steve Allen - The Whole Show - Podcast _ Global Player-u0026aw_0_1st.mp3
[download] 100% of 126.09MiB in 02:35
[ffmpeg] Adding metadata to 'Steve Allen - The Whole Show - Podcast _ Global Player-u0026aw_0_1st.mp3'
[debug] ffmpeg command line: ".\FFmpeg\ffmpeg" -y -loglevel "repeat+info" -i "file:Steve Allen - The Whole Show - Podcast _ Global Player-u0026aw_0_1st.mp3" -ccopy -metadata "purl=https://www.globalplayer.com/podcasts/episodes/7Drf561/" -metadata "title=Steve Allen - The Whole Show - Podcast | Global Player" -metadata "artist=www.globalplayer.com" "file:Steve Allen - The Whole Show - Podcast _ Global Player-u0026aw_0_1st.temp.mp3"
[embedthumbnail] There aren't any thumbnails to embed
```
Overseas location, thus not being geo-fenced for that particular item... 
FWIW, a proper IE has to be authored if one wants:
a) more meaningful/correct filenames (e.g. including radio station name, date of first broadcast, etc.)
b) complete description/file metadata
c) cover/thumbnail...

**Comment by dirkf** [comment]
The page tested above has:
1. ld+json that we ought to be extracting once the common code recognises a `PodcastEpisode` (also a `RadioEpisode`) as a sort of `Episode`
2. almost the same metadata in `og:...` `<meta>` tags
2. Next.js hydration JSON that could be extracted by a dedicated extractor.

Currently, I expect (without actually testing) that this catch-all in the generic extractor is finding the media link in the hydration JSON:
```py
            found = filter_video(re.findall(
                r'[^A-Za-z0-9]?(?:file|video_url)["\']?:\s*["\'](http(?![^\'"]+\.[0-9]+[\'"])[^\'"]+)["\']', webpage))
```

**Comment by Vangelis66** [comment]
... It's not only MP3 **podcasts**  that are offered via `GlobalPlayer`, it's a full-fledged **catch-up** service for (most) radio programmes broadcast over the [Global Group](https://en.wikipedia.org/wiki/List_of_Global_Group_stations) (commercial) radio network in the UK 😉 ... 

AOD links, e.g. for **CapitalFM**, are like below: 

https://www.globalplayer.com/catchup/capital/uk/episodes/2zGrsPHALvZrD1F7DB837dwSFp/

You'll notice the different structure of the URI compared to the "podcast one" found in OP; `catch-up` has a limited availability time frame of only 7 days after first broadcast, audio is served as a lowly `HE-AACv1@48kbps` encode, inside the MP4 container (with Apple's `.m4a` file extension for audio): 
```shell
yt-dl "https://www.globalplayer.com/catchup/capital/uk/episodes/2zGrsPHALvZrD1F7DB837dwSFp/" => 

[generic] 2zGrsPHALvZrD1F7DB837dwSFp: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2zGrsPHALvZrD1F7DB837dwSFp: Downloading webpage
[generic] 2zGrsPHALvZrD1F7DB837dwSFp: Extracting information
[download] Destination: The Sky VIP Official Big Top 40 _ Global Player-u0026aw_0_1st.m4a
[download] 100% of 61.13MiB in 02:02
```
Hopefully, support for **non-podcast** AOD can be added, too... 😄

**Comment by dirkf** [comment]
The AOD examples lack the ld+json but the page structure is otherwise similar.

**Comment by Vangelis66** [comment]
> FWIW, a proper IE has to be authored if one wants:
a) more meaningful/correct filenames (e.g. including radio station name, date of first broadcast, etc.)
b) complete description/file metadata
c) cover/thumbnail...

Recent "downstream" implementation: 

https://github.com/yt-dlp/yt-dlp/pull/6903

merged as https://github.com/yt-dlp/yt-dlp/commit/30647668a92a0ca5cd108776804baac0996bd9f7 😉 ...

**Comment by dirkf** [comment]
Not a tricky back-port, but needs some core back-ports to be merged first:
```console
$ pytest -k GlobalPlayer============================= test session starts ==============================
platform linux2 -- Python 2.7.18, pytest-4.6.11, py-1.11.0, pluggy-0.13.1
rootdir: /home/df/Documents/src/youtube-dl
collected 2621 items / 2613 deselected / 8 selected                            

test/test_download.py ........                                           [100%]

================== 8 passed, 2613 deselected in 6.22 seconds ===================
$
```
