### ISSUE TITLE
Cannot extract video after upgrading ubuntu 18.04 to 20.0 ..

### ISSUE THREAD

**Issue by bruekc** [ytdl-org/youtube-dl#31695]
1 bruce@bruce-Latitude-E5400:~$ sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
  2   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  3                                  Dload  Upload   Total   Spent    Left  Speed
  4 100     3  100     3    0     0      2      0  0:00:01  0:00:01 --:--:--     2
  5 100     3  100     3    0     0      2      0  0:00:01  0:00:01 --:--:--     2
  6   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  7 100 1794k  100 1794k    0     0   792k      0  0:00:02  0:00:02 --:--:-- 4213k
  8 bruce@bruce-Latitude-E5400:~$ sudo chmod a+rx /usr/local/bin/youtube-dl
  9 bruce@bruce-Latitude-E5400:~$ youtubr-dl --format FORMAT
 10 
 11 Command 'youtubr-dl' not found, did you mean:
 12 
 13   command 'youtube-dl' from snap youtube-dl (2021.12.17+git01bf89e)
 14   command 'youtube-dl' from deb youtube-dl (2020.03.24-1)
 15 
 16 See 'snap info <snapname>' for additional versions.
 17 
 18 bruce@bruce-Latitude-E5400:~$ youtube-dl --format FORMAT
 19 Usage: youtube-dl [OPTIONS] URL [URL...]
 20 
 21 youtube-dl: error: You must provide at least one URL.
 22 Type youtube-dl --help to see a list of all options.
 23 bruce@bruce-Latitude-E5400:~$ youtube-dl --format FORMAT sudo chmod a+rx /usr/local/bin/youtube-dl
 24 ERROR: 'sudo' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:sudo" ) to search YouTube
 25 bruce@bruce-Latitude-E5400:~$
 26 bruce@bruce-Latitude-E5400:~$ youtube-dl --format FORMAT https://www.youtube.com/watch?v=eVlCKD2Ijik
 27 [youtube] eVlCKD2Ijik: Downloading webpage
 28 ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call     youtube-dl with the --verbose flag and include its complete output.
 29 bruce@bruce-Latitude-E5400:~$ youtube-dl --verbose --format FORMAT https://www.youtube.com/watch?v=eVlCKD2Ijik
 30 [debug] System config: []
 31 [debug] User config: []
 32 [debug] Custom config: []
 33 [debug] Command-line args: ['--verbose', '--format', 'FORMAT', 'https://www.youtube.com/watch?v=eVlCKD2Ijik']
 34 [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
 35 [debug] youtube-dl version 2021.12.17
 36 [debug] Python version 3.8.10 (CPython) - Linux-5.4.0-139-generic-x86_64-with-glibc2.29
 37 [debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
 38 [debug] Proxy map: {}
 39 [youtube] eVlCKD2Ijik: Downloading webpage
 40 ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call     youtube-dl with the --verbose flag and include its complete output.
 41 Traceback (most recent call last):
 42   File "/home/bruce/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
 43     return func(self, *args, **kwargs)
 44   File "/home/bruce/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
 45     ie_result = ie.extract(url)
 46   File "/home/bruce/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 534, in extract
 47     ie_result = self._real_extract(url)
 48   File "/home/bruce/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
 49     'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
 50   File "/home/bruce/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
 51     raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl

**Comment by Corrrupt** [comment]
Happens on windows as well

**Comment by Corrrupt** [comment]
Only happens with youtube, relabel as broken-IE

**Comment by dirkf** [comment]
#30839

Also, install or update the Ubuntu _youtube-dl_ package.
