### ISSUE TITLE
No descarga

### ISSUE THREAD

**Issue by nilojuan** [ytdl-org/youtube-dl#31705]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description
Unable to extract uploader id

WRITE DESCRIPTION HERE

**Comment by nicolaasjan** [comment]
Search the bugtracker for similar bug reports including closed ones.

https://github.com/ytdl-org/youtube-dl/issues?q=Unable+to+extract+uploader+id


And:

[Read this before opening a new issue](https://github.com/ytdl-org/youtube-dl/issues/30839)

> Known issues, fixed in git master code:
> 
> - [YouTube: Unable to extract uploader id](https://github.com/ytdl-org/youtube-dl/issues/31530)

**Comment by dirkf** [comment]
Utilice Google Translate, o similar, si no puede leer fácilmente el texto del problema fijado o de otros problemas.
