### ISSUE TITLE
Help with issue

### ISSUE THREAD

**Issue by wsc-direct** [ytdl-org/youtube-dl#31702]
Hi, just wondering what this errors are about.  Just installed via homebrew and tested with random YouTube Url.

 `% youtube-dl -F https://youtu.be/RY9O_kvU-JY`        

[youtube] RY9O_kvU-JY: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

This was when I right clicked copied the url from the video.

 `% youtube-dl -F https://www.youtube.com/watch?v=RY9O_kvU-JY`

zsh: no matches found: https://www.youtube.com/watch?v=RY9O_kvU-JY

This is the same video, address copied from browser address bar.

This happens with all videos.

youtube-dl on MacOs Ventura.

Thank you.

**Comment by nicolaasjan** [comment]
Search the bugtracker for similar bug reports including closed ones.

https://github.com/ytdl-org/youtube-dl/issues?q=Unable+to+extract+uploader+id


And:

[Read this before opening a new issue](https://github.com/ytdl-org/youtube-dl/issues/30839)

> Known issues, fixed in git master code:
> 
> - [YouTube: Unable to extract uploader id](https://github.com/ytdl-org/youtube-dl/issues/31530)

**Comment by dirkf** [comment]
Quote the `'URL'`. The _zsh_ shell is sensitive to `?`.
