### ISSUE TITLE
erro message when downloading

### ISSUE THREAD

**Issue by xyz-cba** [ytdl-org/youtube-dl#31714]
I have youtube-dl version 2021.12.17. When running:
 youtube-dl "https://www.youtube.com/watch?v=ymSq4wHrqyU"

I got:
[youtube] ymSq4wHrqyU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by DJDeDPonYT** [comment]
Ya. i have this is problem to. 
I'm using my music bot in discord, and his can't load any music from youtube. ChatGPT sayd me - "This is problem with update, if you have latest version, go to (github of creator) for sayd about this bug"

**Comment by cheezycroque** [comment]
Same issue.

Steps to reproduce : 
1. youtube-dl --verbose --no-check-certificate <URL>

Actual Result : 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--no-check-certificate', 'https://www.youtube.com/watch?v=IzlIBgN_qYs']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.1 (CPython) - macOS-13.0-arm64-arm-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] IzlIBgN_qYs: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/neo/Dropbox/scripts/tools/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/neo/Dropbox/scripts/tools/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/Users/neo/Dropbox/scripts/tools/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/neo/Dropbox/scripts/tools/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/neo/Dropbox/scripts/tools/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by liamengland1** [comment]
Learn how to search the open issues, FFS

https://github.com/ytdl-org/youtube-dl/issues/30839

**Comment by Spirit-of-the-fox10** [comment]
The issue obviously hasn't been sorted on a large scale, or else the error wouldn't keep popping up. I'm not a coder, developer or otherwise, and I've had to try and navigate this insane platform to try and find out why I couldn't download audio clips for training references. 
HOW can this issue be corrected for those of us with limited cranial capacity for ones and zeros who simply want to explain to lesser developed craniums what health and safety in the workplace is by adding a YOUTUBE download to refer people to when they hurt themselves because they have no systematic discipline towards their surroundings, and if I have to listen to one more "catch up" about this topic I can see myself practising defenestration.
