### ISSUE TITLE
Youtube-DL Doesn't Download Youtube anymore

### ISSUE THREAD

**Issue by 4nanook** [ytdl-org/youtube-dl#31711]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --verbose https://www.youtube.com/watch?v=GeLqHw4MbLY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=GeLqHw4MbLY']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.7 (CPython) - Linux-6.1.14-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg 5.1.1, ffprobe 5.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] GeLqHw4MbLY: Downloading webpage
[youtube] GeLqHw4MbLY: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

WRITE DESCRIPTION HERE
Until recently youtube-dl downloaded youtube videos, now, on youtube, you get the above errors.

**Comment by dirkf** [comment]
> [x] I've searched the bugtracker for similar bug reports including closed ones

But not successfully? #30839

**Comment by 4nanook** [comment]
No, I put the error message in the search field, no match.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment]
If you don't give a shit if your program works or not, so be it.

**Comment by dirkf** [comment]
Your problem is actually mentioned in the pinned issue that I linked and the master issue also appears in the [search](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+%22Unable+to+extract+uploader+id%22+-label%3Aduplicate+) that the pinned issue suggests. Even if you followed one of the other low interest spam issues that haven't yet been tagged as duplicate, you would be directed to the master issue, as above.

**Comment by 4nanook** [comment]
I didn't write the search alogrithm, it would seem a match of the error
should find it, it didn't.  I found whatever youtube changed it's broken a lot
of downloaders as youtube-dlg and yt-dlg also do not work.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by dirkf** [comment]
Check the search link above to see how to do it. Or propose a support contract -- I suggest a retainer plus per-incident rates -- to have someone else do the work for you.

The linked and pinned issue explains what to do if you're a user of a yt-dl wrapper program like those you mention.
