### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by piroXpower** [ytdl-org/youtube-dl#31729]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by toaxdjr** [comment]
"I've searched the bugtracker for similar bug reports including closed ones" well thats a lie https://github.com/ytdl-org/youtube-dl/issues/30839.

**Comment by dirkf** [comment]
"lie" may be a bit judgmental: maybe just didn't bother to read the pinned issue.
