### ISSUE TITLE
Youtube-dl & Youtube DLG are not working anymore on w10

### ISSUE THREAD

**Issue by Hoel2A** [ytdl-org/youtube-dl#31724]
PS C:\Users\lanti\downloads> .\youtube-dl.exe https://www.youtube.com/watch?v=pTcj60sZU1o
[youtube] pTcj60sZU1o: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version;

youtube-dl is up-to-date (2021.12.17)

and with Youtube DLG

Error - Download completed
Percent 0 %   Status Error
Succesfully downloaded  0 URL(s) in 0 day(s) 0 hour(s) 0 minute(s) 3 second(s)

and no file has been dowloaded.

## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
#30839
