### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Troyatfrontporchstudiosdotcom** [ytdl-org/youtube-dl#31720]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
The operation couldn’t be completed. (ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
error -1000.)
```

## Description

will not download youtube video

**Comment by Troyatfrontporchstudiosdotcom** [comment]
This is very hard to report a bug...

**Comment by dirkf** [comment]
Read #30839 (again).
