### ISSUE TITLE
youtube-dl bug: last worked for me Jan 21 2023  Now I get this?!?

### ISSUE THREAD

**Issue by jimmaiullo** [ytdl-org/youtube-dl#31727]
[yitdebug.txt](https://github.com/ytdl-org/youtube-dl/files/10854946/yitdebug.txt)

## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
#30839.
