### ISSUE TITLE
Broken upploader id

### ISSUE THREAD

**Issue by Luffy12432432** [ytdl-org/youtube-dl#31731]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Hello its sayig this ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2023-03-01 10:12:20 ERROR    discord.ext.commands.bot Ignoring exception in command play
idk how to fix that ive tried everything but it still does the same thing pls help

**Comment by dirkf** [comment]
#30839.
