### ISSUE TITLE
youtube-dl error with updated version 12.17

### ISSUE THREAD

**Issue by dasan137** [ytdl-org/youtube-dl#31748]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

updated youtube-dl 12.17 is showing error while version 12.14 is working in windows 10

**Comment by dasan137** [comment]
issue is regarding updated version of youtube-dl 12.17  and 12.14 .Version12..14.0  is working in windows 10. I am at a loss to understand why the updated version is showing error.You may kindly examine the issue.

**Comment by dasan137** [comment]
[yl-error.txt](https://github.com/ytdl-org/youtube-dl/files/10883235/yl-error.txt)

**Comment by dirkf** [comment]
What is 12.14?

What is the error message?

Review #30839 to formulate your issue and most likely identify your problem as an existing issue.

**Comment by dasan137** [comment]
i am having the old version of youtube-dl version 12.14 with which i am able to download files from youtube.I tried this after i got error with ubpdated version 12.17,
The result is reroduced here for information.
D:\yt_dl>youtube-dl https://www.youtube.com/watch?v=9YaaBgDg57g
[youtube] 9YaaBgDg57g: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 then with --verbose flag
D:\yt_dl>youtube-dl --verbose https://www.youtube.com/watch?v=9YaaBgDg57g
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=9YaaBgDg57g']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.2
[debug] Proxy map: {}
[youtube] 9YaaBgDg57g: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 with earlier versio:
D:\yt_dl>youtube-dl https://www.youtube.com/watch?v=9YaaBgDg57g
[youtube] 9YaaBgDg57g: Downloading webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: Intro to Aristotle's Ethics _ Lecture 1 - The Good-9YaaBgDg57g.f137.mp4
[download]   3.3% of 149.57MiB at 53.29KiB/s ETA 46:20
it is working
________________________________

**Comment by dasan137** [comment]
youtube-dl file version 12.14.0
________________________________

**Comment by dirkf** [comment]
I suppose you meant 2020.12.14. There's little chance of that working on most of today's websites.
