### ISSUE TITLE
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### ISSUE THREAD

**Issue by mirodil1** [ytdl-org/youtube-dl#31741]
Getting error while downloading youtube:
```
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by sleibrock** [comment]
This likely stems from old YouTube extraction regex that is not available in the 2021 release. Best bet may be to use the source/master branch. It fails for me on the 2021.12.17 on certain videos.

**Comment by odrotbohm** [comment]
Have been running into the same original issue and can confirm that it works on current `master` as described by @sleibrock.

**Comment by aalub** [comment]
Same error trying to download https://www.youtube.com/watch?v=Hl6gvH1xbfc . Sure I use latest version availiable. Still I get this error:
youtube-dl.exe --verbose https://www.youtube.com/watch?v=Hl6gvH1xbfc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=Hl6gvH1xbfc']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Hl6gvH1xbfc: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by YOONSEOKHEO** [comment]
@sleibrock your suggestion worked for me! thanks! 
By the way, is there any way to speed up? 
I was trying to download a video using the following command:
  python youtube-dl/youtube_dl/__main__.py --verbose https://www.youtube.com/watch?v=uI-vgcqOioU 
  
The speed is 410.50KiB/s. 
I have no idea whether the speed is normal or extremely slow.

**Comment by sleibrock** [comment]
@YOONSEOKHEO As far as I can tell, you're at the mercy of the CDN source of whatever extractor you are using (in this case the YouTube/Google CDNs). The backends can always implement rate-throttlers, but currently I do not know of any way of speeding up the download process.

**Comment by nicolaasjan** [comment]
@YOONSEOKHEO
This is a known issue.
See the [pinned issue](https://github.com/yt-dlp/yt-dlp/issues/6369) in the [yt-dlp issue tracker](https://github.com/yt-dlp/yt-dlp/issues).

**Comment by nicolaasjan** [comment]
> but currently I do not know of any way of speeding up the download process.

I use external downloader `aria2c` and then it is faster, but not optimal in this particular case.
Also on @YOONSEOKHEO's video I get redirects to other download servers...

`[#9f5e87 87MiB/87MiB(99%) CN:1 DL:3.7MiB]`

**Comment by dirkf** [comment]
#30389

The issue title doesn't match the actual error message!

**Comment by aalub** [comment]
> you may want to consider upgrading your Python version, since Python 3.4's end-of-life was over 3 years ago now

My Python is 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36), still I have this error.

**Comment by Vangelis66** [comment]
@dirkf wrote yesterday: 

> #30389

... Make that #30839 😄 ...

**Comment by Vangelis66** [comment]
@aalub 

**Python** versions don't matter in this case; `youtube-dl` strives to be compatible with py2.6/**2.7** and py**3.2**+ :smile: 👍 ; the standalone `youtube-dl.exe` binary has been compiled bundled with a **py3.4**.4 interpreter and **it's fine**... 

Since your actual issue seems indeed to be 
`ERROR: Unable to extract uploader id`,
what you (and the rest of the high-jackers, as well as OP) should have done in the first place is start with PINNED #30839, read it carefully, and hopefully you'll then find yourself in #31530; read the available **fixes** documented in the **description** of said issue...
