### ISSUE TITLE
Youtube-dl is broken on youtube

### ISSUE THREAD

**Issue by Sollidottingen** [ytdl-org/youtube-dl#31755]
## Checklist

- [x] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
#30839.

**Comment by Sollidottingen** [comment]
how can you close it when it's not resolved?
