### ISSUE TITLE
Unable to download video 

### ISSUE THREAD

**Issue by YesThatGy** [ytdl-org/youtube-dl#31752]
With an updated script installed via wget https://blahblahblah I get: 

[bens@tesla ~]$ youtube-dl "https://www.youtube.com/watch?v=F17gkR8CqrQ"
[youtube] F17gkR8CqrQ: Downloading webpage
[youtube] F17gkR8CqrQ: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[bens@tesla ~]$ 

I tried the same thing on another box running Centos 8.

**Comment by uforek** [comment]
I'm receiving the same issue. Maybe YouTube changed something?

**Comment by bjdeleon** [comment]
Same issue with me as well.

**Comment by kkarhan** [comment]
same:

`./youtube-dl https://www.youtube.com/watch?v=jAawhg6JtyY --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=jAawhg6JtyY', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.15.0-67-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] jAawhg6JtyY: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

`

**Comment by kkarhan** [comment]
This may also be a duplicate to #31530 
See also #31585

**Comment by dirkf** [comment]
And #30839 !
