### ISSUE TITLE
youtube-dl error

### ISSUE THREAD

**Issue by Donfio** [ytdl-org/youtube-dl#31764]
I am trying to download classical music from youtube using youtube-dl on a Linux Mint computer. It was working fine but now I am getting this error on anything I attempt - 

ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I am using the latest version of youtube-dl and I have pip3 installed. It taks here about a verbose flag. I have no idea what that is.
Can you help with this??
Thanks
Donfio

**Comment by dirkf** [comment]
#30839.
