### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by Bentsman** [ytdl-org/youtube-dl#31762]
System:
  Kernel: 5.15.0-67-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: MATE 1.26.0 wm: marco
    dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: TOSHIBA product: SATELLITE PRO A50-C v: PS575E-0U106EEN
    serial: <superuser required> Chassis: type: 10 v: Version 1.0 serial: <superuser required>
  Mobo: TOSHIBA model: SATELLITE PRO A50-C v: Version A0 serial: <superuser required>
    UEFI-[Legacy]: TOSHIBA v: Version 7.70 date: 02/07/2017
Battery:
  ID-1: BAT1 charge: 22.1 Wh (100.0%) condition: 22.1/44.4 Wh (49.7%) volts: 14.8 min: 14.8
    model: G71C000JM510 serial: <filter> status: Full
CPU:
  Info: dual core model: Intel Core i7-6500U bits: 64 type: MT MCP arch: Skylake rev: 3 cache:
    L1: 128 KiB L2: 512 KiB L3: 4 MiB
  Speed (MHz): avg: 546 high: 599 min/max: 400/3100 cores: 1: 599 2: 587 3: 500 4: 500
    bogomips: 20799
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel Skylake GT2 [HD Graphics 520] vendor: Toshiba driver: i915 v: kernel ports:
    active: eDP-1 empty: DP-1, DP-2, HDMI-A-1, HDMI-A-2 bus-ID: 00:02.0 chip-ID: 8086:1916
  Device-2: Chicony TOSHIBA Web Camera - FHD type: USB driver: uvcvideo bus-ID: 1-6:5
    chip-ID: 04f2:b537
  Display: x11 server: X.Org v: 1.21.1.3 compositor: marco v: 1.26.0 driver: X:
    loaded: modesetting unloaded: fbdev,vesa gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1368x768 s-dpi: 96
  Monitor-1: eDP-1 model: LM156LF1L03 res: 1368x768 dpi: 101 diag: 395mm (15.5")
  OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 22.2.5 direct render: Yes
Audio:
  Device-1: Intel Sunrise Point-LP HD Audio vendor: Toshiba driver: snd_hda_intel v: kernel
    bus-ID: 00:1f.3 chip-ID: 8086:9d70
  Sound Server-1: ALSA v: k5.15.0-67-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Ethernet I219-V vendor: Toshiba driver: e1000e v: kernel port: N/A
    bus-ID: 00:1f.6 chip-ID: 8086:1570
  IF: enp0s31f6 state: down mac: <filter>
  Device-2: Intel Wireless 8260 driver: iwlwifi v: kernel pcie: speed: 2.5 GT/s lanes: 1
    bus-ID: 01:00.0 chip-ID: 8086:24f3
  IF: wlp1s0 state: up mac: <filter>
Bluetooth:
  Device-1: Intel Bluetooth wireless interface type: USB driver: btusb v: 0.8 bus-ID: 1-8:7
    chip-ID: 8087:0a2b
  Report: hciconfig ID: hci0 rfk-id: 1 state: up address: <filter> bt-v: 2.1 lmp-v: 4.2
    sub-v: 100
Drives:
  Local Storage: total: 990.99 GiB used: 193.17 GiB (19.5%)
  ID-1: /dev/sda vendor: Seagate model: ST1000LM048-2E7172 size: 931.51 GiB speed: 6.0 Gb/s
    serial: <filter>
  ID-2: /dev/sdb type: USB vendor: Generic model: STORAGE DEVICE size: 59.48 GiB
    serial: <filter>
Partition:
  ID-1: / size: 914.83 GiB used: 192.75 GiB (21.1%) fs: ext4 dev: /dev/sda5
  ID-2: /boot/efi size: 512 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/sda2
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 1.3 MiB (0.1%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 12 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002
  Device-1: 1-3:2 info: Logitech Unifying Receiver type: Keyboard,Mouse
    driver: logitech-djreceiver,usbhid rev: 2.0 speed: 12 Mb/s chip-ID: 046d:c534
  Device-2: 1-4:13 info: Genesys Logic Colour arc SD Card Reader [PISEN] type: Mass Storage
    driver: usb-storage rev: 2.0 speed: 480 Mb/s chip-ID: 05e3:0736
  Device-3: 1-5:4 info: Realtek RTS5129 Card Reader Controller type: <vendor specific>
    driver: rtsx_usb,rtsx_usb_ms,rtsx_usb_sdmmc rev: 2.0 speed: 480 Mb/s chip-ID: 0bda:0129
  Device-4: 1-6:5 info: Chicony TOSHIBA Web Camera - FHD type: Video driver: uvcvideo rev: 2.0
    speed: 480 Mb/s chip-ID: 04f2:b537
  Device-5: 1-8:7 info: Intel Bluetooth wireless interface type: Bluetooth driver: btusb
    rev: 2.0 speed: 12 Mb/s chip-ID: 8087:0a2b
  Hub-2: 1-10:6 info: Genesys Logic Hub ports: 4 rev: 2.1 speed: 480 Mb/s chip-ID: 05e3:0608
  Hub-3: 2-0:1 info: Super-speed hub ports: 6 rev: 3.0 speed: 5 Gb/s chip-ID: 1d6b:0003
Sensors:
  System Temperatures: cpu: 42.0 C pch: 36.5 C mobo: N/A
  Fan Speeds (RPM): N/A
Repos:
  Packages: 2813 apt: 2806 flatpak: 7
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //www.mirrorservice.org/sites/packages.linuxmint.com/packages vera main upstream import backport
    2: deb http: //mirror.freethought-internet.co.uk/ubuntu jammy main restricted universe multiverse
    3: deb http: //mirror.freethought-internet.co.uk/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //mirror.freethought-internet.co.uk/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
Info:
  Processes: 231 Uptime: 7h 40m Memory: 7.69 GiB used: 2.53 GiB (33.0%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.3.0 alt: 11/12 Client: Unknown python3.10 client inxi: 3.3.13

-----------------------------------------------------------------------------------------------------------------------------------------
ERROR: Unable to extract uploader id

youtube-dl --verbose https://www.youtube.com/@chillcopyrightfreemusic

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/@chillcopyrightfreemusic']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-67-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] @chillcopyrightfreemusic: Downloading webpage
[download] Downloading playlist: Chill - Copyright Free Music - Home
[youtube:tab] playlist Chill - Copyright Free Music - Home: Downloading 5 videos
[download] Downloading video 1 of 5
[youtube:tab] @chillcopyrightfreemusic: Downloading webpage
[download] Downloading playlist: Chill - Copyright Free Music - Playlists
[youtube:tab] playlist Chill - Copyright Free Music - Playlists: Downloading 8 videos
[download] Downloading video 1 of 8
[youtube:tab] PL06diOotXAJLhZjxE_cbYWbsXmdsvA_22: Downloading webpage
[download] Downloading playlist: Lofi Hip Hop
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] playlist Lofi Hip Hop: Downloading 231 videos
[download] Downloading video 1 of 231
[youtube] hQT6WMJ-Fco: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper

**Comment by dirkf** [comment]
#30839.
