### ISSUE TITLE
New release [Question]

### ISSUE THREAD

**Issue by ProvisionlabTeam** [ytdl-org/youtube-dl#31767]
## Checklist

- [x] I'm asking a question

## Question

Hey guys, any info about the new release?

**Comment by schneeschmelze** [comment]
I second this question. I've been looking for an alternative to youtube-dl for several weeks, to no avail. If there is anything I can do in order to help you fix the issues we had found, would you please let me know.

**Comment by dirkf** [comment]
#30839.
