### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by JF-the-gardener** [ytdl-org/youtube-dl#31788]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'https://www.youtube.com/watch?v=LPsQFhhE8Ww']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2.8.4
[debug] Proxy map: {}
[youtube] LPsQFhhE8Ww: Downloading webpage
[youtube] LPsQFhhE8Ww: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I use youtube-dl.exe on windows 10.
Everything was working fine 3 months ago.
Impossible to download now.

**Comment by SethFalco** [comment]
A work around for this for now is to downgrade youtube-dl version.
For example, 2020.12.29 seems to work, though downloads are very slow.

```sh
pip install youtube-dl==2020.12.29
```

Problem and work around applies to both Debian 11 and Windows 10.

**Comment by peterpt** [comment]
I also have the same issue with last version on windows , same exact error .

youtube-dl -F https://www.youtube.com/watch?v=D2KE2a5qo0g --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.youtube.com/watch?v=D2KE2a5qo0g',
 '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-109650-g9d5e66942c-20230123, ffprobe N-109650-g9d
5e66942c-20230123
[debug] Proxy map: {}
[youtube] D2KE2a5qo0g: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.
org/bug . Make sure you are using the latest version; type  youtube-dl -U  to up
date. Be sure to call youtube-dl with the --verbose flag and include its complet
e output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c
6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c
6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c
6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c
6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c
6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please repor
t this issue on https://yt-dl.org/bug . Make sure you are using the latest versi
on; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbos
e flag and include its complete output.

**Comment by liamengland1** [comment]
https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611

**Comment by dirkf** [comment]
>[] I'm reporting a broken site support issue

Actually, you are.

>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how from #30839.
