### ISSUE TITLE
Bug Report on  youtube_dl.utils.DowmloadError

### ISSUE THREAD

**Issue by lewismunene020** [ytdl-org/youtube-dl#31780]
I encountered this error  while setting up in kali linux : 
youtube_dl.utils.DownloadError: [0;31mERROR:[0m Unable to extract [0;34muploader id[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
What part of Kali Linux setup tries to download a YouTube video, I wonder?

Anyhow, #30839.

**Comment by lewismunene020** [comment]
I am creating a YouTube downloader so I was using YouTube dl
