### ISSUE TITLE
Youtube file download not working. Latest Version installed on Xubuntu 

### ISSUE THREAD

**Issue by hhgoten** [ytdl-org/youtube-dl#31786]
/lwd/video_audio > /usr/bin/youtube-dl --verbose https://www.youtube.com/watch?v=jsETTn7DehI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=jsETTn7DehI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.7 (CPython) - Linux-5.19.0-35-generic-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg 5.1.1, ffprobe 5.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] jsETTn7DehI: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

/lwd/video_audio >

**Comment by dirkf** [comment]
#30839.

**Comment by hhgoten** [comment]
@dirkf 
I logged in, followed the advice in upcomming  download --verbose ..
What am I supposed to do ? What's my fault ?

**Comment by dirkf** [comment]
Fully study and follow the linked pinned issue.
