### ISSUE TITLE
Error: Unable to extract uploader id

### ISSUE THREAD

**Issue by Sandro-Terra** [ytdl-org/youtube-dl#31793]
[youtube] kLPlBpIRY2s: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ sudo youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

$ youtube-dl --verbose https://www.youtube.com/watch?v=kLPlBpIRY2s
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=kLPlBpIRY2s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.19.0-35-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] kLPlBpIRY2s: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by pakkinlau** [comment]
Same problem to me

**Comment by ozfive** [comment]
Just had this issue myself.

**Comment by dirkf** [comment]
#30839.

**Comment by Axoluther** [comment]
Hey, see [https://github.com/yt-dlp/yt-dlp/commit/149eb0bbf34fa8fdf8d1e2aa28e17479d099e26b](this), this work for me

**Comment by Axoluther** [comment]
> #30839.

why did you hide my comment?

**Comment by Sandro-Terra** [comment]
Oooops. Sorry, @Axoluther.

**Comment by BenVlodgi** [comment]
> Hey, look at [this](https://github.com/yt-dlp/yt-dlp/commit/149eb0bbf34fa8fdf8d1e2aa28e17479d099e26b), worked for me

Thank you! I manually updated this line in my python packages so I could use it.

**Comment by pakkinlau** [comment]
> Hey, look at [this](https://github.com/yt-dlp/yt-dlp/commit/149eb0bbf34fa8fdf8d1e2aa28e17479d099e26b), worked for me

Hello, is that mean I have to edit the package by myself? I have never done that before.
Is that changes already included in the latest package version?

**Comment by ozfive** [comment]
> 

Hi, I just fixed this in the package source of my youtube-dl installation on Ubuntu 22.10 which was located at '/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/youtube.py' If you modify the line in the file that is referenced in the [this](https://github.com/yt-dlp/yt-dlp/commit/149eb0bbf34fa8fdf8d1e2aa28e17479d099e26b) link, it should work again.

**Comment by dirkf** [comment]
Use the documented fix linked from the master issue. Don't comment on duplicate issues.

**Comment by Axoluther** [comment]
> Use the documented fix linked from the master issue. Don't comment on duplicate issues.

Perdona pero esto no va a estar solucionado hasta que no se arregle el error en alguna actualización, cosa que no vengan personas a cada 10 minutos a reportar el problema. Además que en el "master issue" igual hay que rebuscarse un poco la respuesta

**Comment by dirkf** [comment]
Everything you need to know about the problem is in, or is linked from, the Description section of the [master issue](https://github.com/ytdl-org/youtube-dl/issues/31530). If no suggested fix works for you, discuss it where everyone can benefit from it; or if a fixed yt-dl fails in some way other than "[Youtube] Unable to extract uploader id", follow #30839 to see if a new issue should be raised.
