### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by semeion** [ytdl-org/youtube-dl#31800]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.youtube.com/watch?v=wNQ7QaHgxsI', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.9 (CPython) - Linux-6.2.2-arch1-1-x86_64-with-glibc2.37
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] wNQ7QaHgxsI: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

The issue happens with this url: 
https://www.youtube.com/watch?v=wNQ7QaHgxsI

I know, have alot of duplicate reports, but maybe it help solve something.

**Comment by Alexi8787** [comment]
bro
It looks like there was an error with youtube-dl when trying to download a video from YouTube. The error message suggests that there was a problem extracting the uploader id from the video page, and it recommends updating to the latest version of youtube-dl and reporting the issue if the problem persists.

If you haven't already, try updating to the latest version of youtube-dl using the instructions at https://yt-dl.org/update. Then, try running the command again with the --verbose flag to get more detailed output. If the problem persists, you can report the issue on the youtube-dl issue tracker at https://github.com/ytdl-org/youtube-dl/issues.

**Comment by tacitus** [comment]
@Alexi8787 The latest version is being used.  I can confirm the error too. I suspect the markup on the page may have changed.

**Comment by slizzerer** [comment]
this is happening to me also. just downloaded the software for the first time and am getting this error.

**Comment by willvincent** [comment]
Seeing the same.

**Comment by reginalluna** [comment]
It happened to me too!!

**Comment by olivierdugast** [comment]
I have the same problem with all the urls.

Thanks

**Comment by 1SlenderGaming1** [comment]
I have the same issue on the latest version. Thanks for putting up an issue.

**Comment by nebbishOne** [comment]
Same issue, first occurring today. 
Here's my --verbose output. 

```
:~$ youtube-dl --verbose -o test https://www.youtube.com/watch?v=1wavwT7paPs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', 'test', 'https://www.youtube.com/watch?v=1wavwT7paPs']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.19.0-35-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 1wavwT7paPs: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by azusemst** [comment]
Same issue here!

**Comment by lalani** [comment]
I too can confirm that I am facing this issue.

**Comment by bitzspider** [comment]
Same error, most recent version.

**Comment by johnzondag** [comment]
Same here, downloading from a playlist:

$ sudo youtube-dl -U
youtube-dl is up-to-date (2021.12.17)
$ youtube-dl -x --audio-format mp3 -o '%(playlist_index)s %(title)s.%(ext)s' --playlist-start 7 https://youtube.com/playlist?list=PLD0HK4hSAhD-XLEWXsf-N2VExtD7sGiHQ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-x', u'--audio-format', u'mp3', u'-o', u'%(playlist_index)s %(title)s.%(ext)s', u'--playlist-start', u'7', u'https://youtube.com/playlist?list=PLD0HK4hSAhD-XLEWXsf-N2VExtD7sGiHQ', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.15.0-60-generic-x86_64-with-Ubuntu-22.04-jammy
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube:tab] PLD0HK4hSAhD-XLEWXsf-N2VExtD7sGiHQ: Downloading webpage
[download] Downloading playlist: Lunatic Soul |2018| Under the Fragmented Sky |full album|
[youtube:tab] playlist Lunatic Soul |2018| Under the Fragmented Sky |full album|: Downloading 2 videos
[download] Downloading video 1 of 2
[youtube] ijMiYLiai6Y: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by sil3abdi** [comment]
I did that, and now it works
the only thing that you would gotta do if you had a problem with says that python didn't exist is:
1- open /usr/local/bin/youtube-dl with sudo (as root)
2- in the shebang (the first line, it starts with #!/usr/bin/env python) change "python" to "python3" (no spaces between python and 3)
3- save your changes
then it'll be working with you ^-^

**Comment by nicolaasjan** [comment]
> the only thing that you would gotta do if you had a problem that says that python didn't exist:
1- open /usr/local/bin/youtube-dl with sudo (as root)
2- in the shebang (the first line, it looks like that: #!/usr/bin/env python) change "python" to "python3" (no spaces between python and 3)
3- save your changes
then it'll be working with you ^-^

Then you'll have to do that each time after updating...

Maybe easier:
In the file `~/.bash_aliases`, add the line:

`alias youtube-dl='python3 /usr/local/bin/youtube-dl'`

**Comment by dirkf** [comment]
>I have the same problem with all the urls.

No, only YouTube, and not all of those.

> in the shebang (the first line, it looks like that: #!/usr/bin/env python) change "python" to "python3" (no spaces between python and 3)

This could, depending on the tool used to edit the file, result in a non-functional `youtube-dl` executable.

>In the file ~/.bash_aliases, add the line:

Not much use in _zsh_ or if yt-dl is being run directly.

Better to install a package like _python-is-python3_ (if available) or just make a symbolic link.

>Thanks for putting up an issue.

Very much not. #30839.

**Comment by MdeLv** [comment]
Same problem on debian 11 'Unable to extract uploader id'.
Trying this solution :
```
sudo curl -L https://github.com/ytdl-patched/youtube-dl/releases/latest/download/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```
Then I need to change `#!/usr/bin/env python` into `#!/usr/bin/env python3` to avoid "/usr/bin/env: ‘python’: No such file or directory".

Then, error:
```
~/Downloads$ youtube-dl -f 37 "https://www.youtube.com/watch?v=<obfuscated>" --verbose
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 16, in <module>
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 548, in _get_data
zipimport.ZipImportError: bad local file header: '/usr/local/bin/youtube-dl'
```

```
$ cat youtube-dl'?
#!/usr/bin/env python3
PK^C^D^T^@^@^@^H^@ ^H!(���r�k^@^@Լ^A^@^W^@^\^@youtube_dl/YoutubeDL.pyUT ^@^C�Qm8�Qm8ux^K^@^A^D�^C^@^@^D{>
d��>vu�~�:�e�-�f%^?7�N{��ʥ�zV��f[Ϯ
```
What is this file 'youtube-dl'? Is it not supposed to be a python program???

**Comment by dirkf** [comment]
>Still, what is this file 'youtube-dl'? Is it not supposed to be a READABLE python program???!!!

Read the master issue.

**Comment by MdeLv** [comment]
Hey!
1/ My previous comment was NOT a spam. This one as well.
2/ What do you mean with "Read the master issue." ?...

**Comment by dirkf** [comment]
I yield to no-one regarding knowledge of Monty Python. A posting that is "unsolicited", in fact specifically deprecated, may be tagged spam here. If GH allowed, I would have deleted issues like this one and only severe self-discipline has prevented them all from being tagged spam already.

Your question "what is this file 'youtube-dl'?" is answered in the FAQ, too.

**Comment by MdeLv** [comment]
I didn't found an answer in the very long FAQ to my key question "what is this file 'youtube-dl' ? " (and why is it not a readable&auditable python script ?) 

You answer very quickly but may be could you just give pointers?
Thanks.

**Comment by dirkf** [comment]
It's meant to be a `youtube-dl` **command**, so appending `.zip` would just confuse people (apart from @MdeLv!).

This was the first yt-dl issue I came across, when I wanted to run the program on a system with a RO `/usr/bin` containing no `env`, the default shebang being `#!/usr/bin/env python`. Because the file below that line has a zip signature I realised what was going on, but actually it's well documented in Python, as linked from the FAQ item. Our bundle includes the source code files, but you can also ship files compiled to Python byte code, much less readable.

This is the normal way of distributing a Python program as single file in the POSIX world. Windows works differently, since there's no shebang concept -- though there almost was at one time. People who use a package manager normally get the program as a Python module with a stub `youtube_dl` program.

**Luckily** the entire source code is sitting there for anyone who wants to understand how this works for yt-dl, such as @MdeLv.
