### ISSUE TITLE
I can't download YouTube file

### ISSUE THREAD

**Issue by margaretsherburne** [ytdl-org/youtube-dl#31803]
## Checklist

- [x ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Can't download anymore

<!  

-->

WRITE DESCRIPTION HERE
I cannot download files for the last few weeks, and I get this error message.  "Video analysis failed".

![Temp](https://user-images.githubusercontent.com/127423435/224077091-596e2195-a984-4d0a-acd0-54037a4bf859.jpg)

**Comment by dirkf** [comment]
> []  I've searched the bugtracker for similar issues including closed ones

Do it. Learn how from #30839, and what to do if a _youtube-dl_ error is reported by a wrapper program.
