### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by ledav-net** [ytdl-org/youtube-dl#31808]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
./youtube-mp3 'https://youtu.be/gEUm7cKV_ik'
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--get-title', 'https://youtu.be/gEUm7cKV_ik']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.10 (CPython) - Linux-6.1.9-100.fc36.x86_64-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0.2, ffprobe 5.0.2
[debug] Proxy map: {}
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 814, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 835, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I got this error multiple times today with different urls...

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how from #30839 (which you were meant to have read already).

**Comment by ledav-net** [comment]
Hi @dirkf, thanks for your answer. I've read that thread (as many others and re-read it again now) but I don't find how to fix this... Also, don't take it badly, but there are tons of comments and it's not that easy to find your way around...
Thanks anyway for the work done, it's a very useful tool.

**Comment by dirkf** [comment]
Did you make the issue search as suggested and find the master issue for the problem?

Easier, did you find your problem in the list of Known Issues, linked to the master issue?

Did you read the Description of the master issue and follow the link to the post that explains how, for the moment, to obtain a fixed version of the program?

**Comment by ledav-net** [comment]
After digging for a while, I finally found some kind of answer and was able to workaround the problem by doing this:
```diff
--- a/youtube.py	2023-03-10 16:58:40.744602155 +0100
+++ b/youtube.py	2023-03-10 16:58:17.644490080 +0100
@@ -1791,7 +1791,7 @@
                 microformat.get('uploadDate')
                 or search_meta('uploadDate')),
             'uploader': video_details['author'],
-            'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
+            'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id', fatal=False) if owner_profile_url else None,
             'uploader_url': owner_profile_url,
             'channel_id': channel_id,
             'channel_url': 'https://www.youtube.com/channel/' + channel_id if channel_id else None,
```
So by just adding a `fatal=False` to the line who produced the error... But I feel it more like a workaround than a real fix...

**Comment by dirkf** [comment]
Because it is. Use the fix in the git master linked from the actual issue that covers this problem. You're trying too hard. The three questions above apply.
