### ISSUE TITLE
Open Video Downloader Issue

### ISSUE THREAD

**Issue by msaustin85** [ytdl-org/youtube-dl#31805]
## Checklist

- [X ] I'm asking a question
- [X ] I've looked through the README and FAQ for similar questions
- [X ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
  I am trying to download a video on open video downloader and I got an error. It says Error reported! Report ID: 1d5007a8 the full error message says: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug. Make sure you are using the latest version; type youtube-dl-U to update. Be sure to call youtube-dl with the --verbose flag and include its composite output.
Can you assist me with getting this issue resolved?

**Comment by dirkf** [comment]
Read #30839 to find out about this error and what to do if a youtube-dl error is reported by a wrapper program..
