### ISSUE TITLE
youtube-dl ERROR

### ISSUE THREAD

**Issue by hapibeli** [ytdl-org/youtube-dl#31814]
youtube-dl https://www.youtube.com/watch?v=6VCBAHufFHM
[youtube] 6VCBAHufFHM: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

youtube-dl --version
2021.12.17

**Comment by btcusury** [comment]
Same error here, first started happening about a week ago, didn't check until today and the error persists with no new -U version yet...

**Comment by nicolaasjan** [comment]
Read #30839 before opening a new issue.
