### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by AndreasWelchlin** [ytdl-org/youtube-dl#31825]
I am closing this. Seems to be Fixed by https://github.com/ytdl-org/youtube-dl/pull/31675

I am using the latest version.

downloading https://www.youtube.com/watch?v=l28OVrWJvc8&list=PLhPyEFL5u-i0MHw41OapxjLlsl0s2XQyE&index=5

ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug .

**Comment by AndreasWelchlin** [comment]
This seems already to be Fixed by https://github.com/ytdl-org/youtube-dl/pull/31675

**Comment by dirkf** [comment]
Read #30839 (again).

**Comment by skycat2216** [comment]
> This seems already to be Fixed by #31675
But the latest release is 2022/12/27, How a version released before #31675 can handle new API?

**Comment by dirkf** [comment]
@skycat2216, [you too](https://github.com/ytdl-org/youtube-dl/issues/31825#issuecomment-1465175511).
