### ISSUE TITLE
error upload id

### ISSUE THREAD

**Issue by NEDTEN** [ytdl-org/youtube-dl#31827]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by NEDTEN** [comment]
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
>[ ] I'm reporting a broken site support issue

No, you are, though you shouldn't be.

>[ ] I've searched the bugtracker for similar bug reports including closed ones

These items are in the template to help you. Learn how by reading #30839 (**again**?).
