### ISSUE TITLE
How stable is the downloader?

### ISSUE THREAD

**Issue by rainbowdesign** [ytdl-org/youtube-dl#31836]
I'm asking a question
I've looked through the README and FAQ for similar questions
I've searched the bugtracker for similar questions including closed ones

Dear youtube-dl team,
I found your app on how to download youtube videos with c# since i like to write something to download youtube videos (and then do other stuff with them).

After downloading the windows exe to test how it actually works i found that it does not i get some error, i updated it but still cannot download a video.

The App is supposed to work out of the box after downloading the requirements, no extra bugfinxing and stuff and also not do extra stuff to make the computer compatible.
So i wonder: Is this situation extraordinary and normally never happens or if i use the youtube-dl can my app break at any time beceuse youtube-dl broke?
When you download the exe for windows execute it and enter a link to download does it work for you?
Kind Regards

**Comment by dirkf** [comment]
Read #30839.

Open an issue if you believe you have found a new problem, after following the procedure laid out there and in the BUGS section of the manual and in the template for your issue.

**Comment by rainbowdesign** [comment]
Hey,
The issue is already listed.
Let me add a bit more data:
Any Video Converter does as far i see base on the youtube-dl and was my favorite app but now it can no longer download videos it does not work for about half a year.
If i make an app i dont want to stop working after a time. 
So the question is do you expect the app to run stable out of the box in a forseeable future.
You certainly understand if someone has this as part of an app he cannot point the users to a bugfix thread.

**Comment by dirkf** [comment]
Raise the issue at AVC, as recommended in #30839.

They need to take the latest code, or follow one of the other update/fix suggestions from #31530. Otherwise you can just hope that they import a new release in due course.
