### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by DocAlex** [ytdl-org/youtube-dl#31844]
Version v2021.12.17

D:\FTP\Youtube Video DL>youtube-dl --no-playlist --audio-quality 0 --audio-format "m4a" --extract-audio --write-all-thumbnails --batch-file Download_These_Files.txt
[youtube] YwGSAFarHRg: Downloading webpage
[youtube] Downloading just video YwGSAFarHRg because of --no-playlist
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Batch File:

D:
cd "D:\FTP\Youtube Video DL"
youtube-dl --no-playlist --audio-quality 0 --audio-format "m4a" --extract-audio --write-all-thumbnails --batch-file Download_These_Files.txt

**Comment by dirkf** [comment]
#30839 !
