### ISSUE TITLE
Failed on DL trying to extract audio

### ISSUE THREAD

**Issue by japuzzo** [ytdl-org/youtube-dl#31853]
$ youtube-dl --format bestaudio --extract-audio --audio-format flac --verbose https://youtu.be/gPFP8bdQKJY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--format', 'bestaudio', '--extract-audio', '--audio-format', 'flac', '--verbose', 'https://youtu.be/gPFP8bdQKJY']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.2 (CPython) - macOS-13.2.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube] gPFP8bdQKJY: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Python/3.8/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/Library/Python/3.8/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Library/Python/3.8/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/Library/Python/3.8/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by japuzzo** [comment]
$ youtube-dl --format bestaudio --extract-audio --audio-format flac --verbose https://youtu.be/Yam5uK6e-bQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--format', 'bestaudio', '--extract-audio', '--audio-format', 'flac', '--verbose', 'https://youtu.be/Yam5uK6e-bQ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.2 (CPython) - macOS-13.2.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube] Yam5uK6e-bQ: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Python/3.8/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/Library/Python/3.8/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Library/Python/3.8/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/Library/Python/3.8/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
As you can easily see, there's no audio extraction happening when the error occurs.

Refer to #30839 as asked.

**Comment by japuzzo** [comment]
Still is a bug thought

$ python3 ~/bin/youtube-dl --version
2021.12.17

$ python3 ~/bin/youtube-dl --format bestaudio --extract-audio --audio-format flac --audio-quality 0 --add-metadata https://youtu.be/gPFP8bdQKJY
[youtube] gPFP8bdQKJY: Downloading webpage
ERROR: Unable to extract uploader id

Please see https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by japuzzo** [comment]
Latest version fixes issue:

$ python3 ~/bin/youtube-dl --version
2023.03.16.1919

$ python3 ~/bin/youtube-dl --format bestaudio --extract-audio --audio-format flac --audio-quality 0 --add-metadata https://youtu.be/gPFP8bdQKJY
[youtube] gPFP8bdQKJY: Downloading webpage
[youtube] gPFP8bdQKJY: Downloading player 837bca82
[dashsegments] Total fragments: 1
[download] Destination: The Cranberries - Linger-gPFP8bdQKJY.webm
[download] 100% of 4.52MiB in 00:01
[ffmpeg] Destination: The Cranberries - Linger-gPFP8bdQKJY.flac
Deleting original file The Cranberries - Linger-gPFP8bdQKJY.webm (pass -k to keep)
[ffmpeg] Adding metadata to 'The Cranberries - Linger-gPFP8bdQKJY.flac'

Please close as duplicate, sorry to waist anyone's time
