### ISSUE TITLE
Unable to extract uploader id along with RegexNotFoundError. Do I need to install 

### ISSUE THREAD

**Issue by gartha1** [ytdl-org/youtube-dl#31862]
H:\>dir youtube-dl.exe
 Volume in drive H is Charlie
 Volume Serial Number is AAEE-1F7E

 Directory of H:\vids\tate\misc

16/03/2023  21:36         8,170,320 youtube-dl.exe
               1 File(s)      8,170,320 bytes
               0 Dir(s)  868,754,944,000 bytes free

H:\>

H:\>youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

H:\>youtube-dl https://www.youtube.com/watch?v=bUZ6fpDDIQM
[youtube] bUZ6fpDDIQM: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type
youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

H:\>youtube-dl --verbose https://www.youtube.com/watch?v=bUZ6fpDDIQM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=bUZ6fpDDIQM']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-94664-g0821bc4eee, ffprobe N-94664-g0821bc4eee
[debug] Proxy map: {}
[youtube] bUZ6fpDDIQM: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type
youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_in
fo
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extra
ct
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _re
al_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _sea
rch_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are us
ing the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I've used it before.. I haven't used python in a while and maybe I don't have python properlry installed.. i'm not sure if i'm meant to have python 2.7? or python 3? or python anything? and in the path?

The way I downloaded youtube-dl  was I grabbed the exe file from under "releases"

Looking here http://ytdl-org.github.io/youtube-dl/download.html  the Windows EXE doesn't require python.. it should be integrated into it.. 

I've definitely got the VS 2010 redistributable installed, i've had it for a long while.. i'm a long time user of youtube-dl
see image of win7 programs and features, showing that installed. https://i.imgur.com/uuJzYaS.png

so i'm not sure where youtube-dl is having an issue.

Thanks

**Comment by dirkf** [comment]
#30839 !

Look, here's a hint:
>ERROR: Unable to extract uploader id; ...
