### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by nttai19984** [ytdl-org/youtube-dl#31865]
[youtube] 1CpdjgaoMFo: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by marcokmoretti** [comment]
C:\Users\marco\Downloads>youtube-dl --verbose https://youtu.be/nZmO8B9rRik
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://youtu.be/nZmO8B9rRik']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] nZmO8B9rRik: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by sumonst21** [comment]
#31867

**Comment by dirkf** [comment]
No, read #30839 properly as asked and expected. Use the checklist.

**Comment by sumonst21** [comment]
> No, read #30839 properly as asked and expected. Use the checklist.

![image](https://user-images.githubusercontent.com/7096865/226552665-4dfc0e4a-8165-4a53-a37c-7685b1e585d0.png)

over 500 issues and counting, this repo should be removed completly from github. shame on all the contribs here. archive it so people don't waste their time. 

how dare you close opened issues when you directed themselves to do it, its a crime now when you know about the problem keep an answer somewhere hidden instead of putting it at the top of everything when it is this popular.

**Comment by dirkf** [comment]
> ...keep an answer somewhere hidden instead of putting it at the top of everything when it is this popular. 

#30839 lists the actual Known Issue that you need to read.

If you couldn't manage to read a whole page of text, it says to use `-label:duplicate` when making the search for existing issues: the target issue is 9th in the result list. Add `in:title` and it becomes \#1.
