### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by candisft** [ytdl-org/youtube-dl#31875]
youtube-dl --list-formats https://www.youtube.com/watch?v=xTUrD
DTJf348
[youtube] xTUrDTJf348: Downloading webpage
[youtube] xTUrDTJf348: Downloading m3u8 information
[youtube] xTUrDTJf348: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
>[ ] I've searched the bugtracker for similar issues including closed ones

The checklist is there to help: use it.

Read #30839 for more help, as asked and expected.
