### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by xzsamit** [ytdl-org/youtube-dl#31876]
Insert Command : 
```
youtube-dl --verbose https://www.youtube.com/watch?v=xxxxx
```
Or
```
youtube-dl -f 'bestvideo[height=1080]+bestaudio/best[height=1080]' https://www.youtube.com/watch?v=xxxxxxx
```

There error
> ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

![image](https://user-images.githubusercontent.com/73475050/226111815-0c223e6d-88fb-4d8c-a611-e4a416b0427e.png)

**Comment by AACF-Arnaud** [comment]
Hello,

Same error for me.

**Comment by nax-bedroom** [comment]
Experiencing this issue as well. 
```
[download] Downloading video 4 of 51
[youtube] 7EVRpmG_6s0: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by xzsamit** [comment]
Yes, same error for me @AACF-Arnaud @nax-bedroom

**Comment by Artekkor** [comment]
Also doesn't work here.
Apparently its a well-known issue that appeared a couple of weeks back. Something about YouTube changing its host server or something like that, can't remember precisely. The other youtube-dl (forgot its name) has already solved this, but this one is a little bit slow on the fix. Presumably we are waiting for a new YouTube-DL version to update to any day now.

**Comment by dirkf** [comment]
Read #30839 properly (**again**?)!

@Artekkor, you're guessing. Why not help the inept OP by posting the actual issue for this problem?
