### ISSUE TITLE
Error downloading the video: 'average_rating'

### ISSUE THREAD

**Issue by ChristianErdtmann** [ytdl-org/youtube-dl#31872]
Hey i get the error: Error downloading the video: 'average_rating'   
  
     # Create pafy object for the video
      video_url = f'https://www.youtube.com/watch?v=HNjW0C1rvmc '
      video = pafy.new(video_url)

      # Get the best available audio and video streams
      best_audio = video.getbestaudio()
      best_video = video.getbestvideo()

      # Download the audio and video streams
      best_audio.download()
      best_video.download()

- [ ]x I'm reporting a broken site support issue
- [ ] xI've verified that I'm running youtube-dl version **2021.12.17**
- [ ] xI've checked that all provided URLs are alive and playable in a browser
- [ ] xI've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] xI've searched the bugtracker for similar bug reports including closed ones
- [ ] xI've read bugs section in FAQ

**Comment by dirkf** [comment]
So where is the error in your report?

Read #30839 (**again**?), especially regarding errors in third-party programs that invoke yt-dl indirectly.
