### ISSUE TITLE
UNABLE TO USE THE CURRENT EXECUTABLE VERSION OF YOUTUBE.DL

### ISSUE THREAD

**Issue by universalsoldierofgod** [ytdl-org/youtube-dl#31890]
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
C:\python>youtube-dl -o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" -f best --verbose --yes-playlist "https://www.youtube.com/playlist?list=PLZ8REt5zt2Plph03SfZKijMWB68FUYfNc"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', '-f', 'best', '--verbose', '--yes-playlist', 'https://www.youtube.com/playlist?list=PLZ8REt5zt2Plph03SfZKijMWB68FUYfNc']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] PLZ8REt5zt2Plph03SfZKijMWB68FUYfNc: Downloading webpage
[download] Downloading playlist: Inteligencia Artificial
[youtube:tab] playlist Inteligencia Artificial: Downloading 25 videos
[download] Downloading video 1 of 25
[youtube] UNFFLJPW7KQ: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
I have tried to use the software as it is described in your manual and i've got this error message. the version is the right one
thanks for your orientation

**Comment by dirkf** [comment]
> [ ] I'm reporting a broken site support issue

No, you are, but you shouldn't be.

>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839 (**again**?).

>[x] I've read bugs section in FAQ

Apply the knowledge.
