### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by mcreal121** [ytdl-org/youtube-dl#31895]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl -v https://youtube.com/playlist?list=PL-5QlDZlK74GrL0fb6V_FZSLX86V9A7j4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtube.com/playlist?list=PL-5QlDZlK74GrL0fb6V_FZSLX86V9A7j4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-144-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] PL-5QlDZlK74GrL0fb6V_FZSLX86V9A7j4: Downloading webpage
[download] Downloading playlist: ERAU Private Pilot (P.A.C.E.)
[youtube:tab] playlist ERAU Private Pilot (P.A.C.E.): Downloading 63 videos
[download] Downloading video 1 of 63
[youtube] 7X8I6QTAm9Q: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

Trying to download a playlist of videos. Same result in linux and windows version.

**Comment by dirkf** [comment]
>[x] I'm reporting a broken site support issue

No, you are, but you shouldn't be.
>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839 (**again**?).

[x] I've read bugs section in FAQ

Apply it.

**Comment by mcreal121** [comment]
Your solution is to use yt-dlp? No wonder you aren't a paid developer. Never will be.

**Comment by liamengland1** [comment]
> Your solution is to use yt-dlp? No wonder you aren't a paid developer. Never will be.

@mcreal121 maybe you have comprehension issues, but there are multiple solutions here: https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611

**Comment by dirkf** [comment]
>... **paid developer** ...

Feel free to propose terms for paid support. An acceptable contract would include a retainer plus an hourly rate for specific issues.

**Comment by mcreal121** [comment]
> > Your solution is to use yt-dlp? No wonder you aren't a paid developer. Never will be.
> 
> @mcreal121 maybe you have comprehension issues, but there are multiple solutions here: [#31530 (comment)](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611)

That isn't a solution. That is an unfixed bug. Clearly this line of work isn't for you. Try applying at KFC.

**Comment by mcreal121** [comment]
> > ... **paid developer** ...
> 
> Feel free to propose terms for paid support. An acceptable contract would include a retainer plus an hourly rate for specific issues.

You won't ever get a paid job in this field.
