### ISSUE TITLE
Youtube DL for VHX videos

### ISSUE THREAD

**Issue by shafeeq-m7** [ytdl-org/youtube-dl#31905]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

I am trying to download a VHX video for personal use as my gym is underground so I do not have internet access - I need this videos offline, however my terminal query doesn't seem to work and gives me a unsupported URL error even though it had worked for a previous video. 

This is what I typed into terminal: youtube-dl --username "my_email_here" --password "my_password_here" --cookies vhx.tv_cookies.txt -v 'https://kinstretchwithbeard.vhx.tv/kinstretch-with-beard/videos/class-3-hip-er-flex-ext-1080-high-new'

I am completely new to youtube-dl btw, so please help me out. Thank you in advance.

**Comment by dirkf** [comment]
This site isn't supported by yt-dl (or yt-dlp). See #14835 (etc).

Try the embed URL instead. You might be able to copy it from the player, or else find it in the source of the page for the problem URL:
```js
window.VHX.config = {
      api_url: "https://api.vhx.tv",
      embed_url: "https://embed.vhx.tv/videos/813503?api=1&amp;autoplay=1&amp;back=KINSTRETCH%20With%20Beard&amp;collection_id=162241&amp;color=3b6691&amp;context=https%3A%2F%2Fkinstretchwithbeard.vhx.tv%2Fkinstretch-with-beard&amp;is_trailer=false&amp;live=0&amp;locale=en&amp;playsinline=1&amp;product_id=56088&amp;referrer=https%3A%2F%2Fgithub.com%2Fytdl-org%2Fyoutube-dl%2Fissues%2F31905&amp;sharing=1&amp;title=0&amp;vimeo=1",
    /* ...snip... */
    };
    window.VHX.video = {
      id: "813503",
      status: "pending",
      isLive: "false",
      scheduled_at: "",
      isDRM: "false",
      isTrailer: "false",
      
    };
```

You could also try the Vimeo player URL https:/player.vimeo.com/video/813503.

Either way, use `--referer ...` specifying the problem URL itself, and omit `--password ...` since you're trying to access the page with cookies.

**Comment by dirkf** [comment]
@shafeeq-m7 ?

**Comment by dirkf** [comment]
Closing for lack of response.
