### ISSUE TITLE
Unable to update youtube-dl

### ISSUE THREAD

**Issue by EvilSupahFly** [ytdl-org/youtube-dl#31904]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones - https://github.com/ytdl-org/youtube-dl/issues/31530 - but the issue persists (at least on Linux)
- [X] I've read bugs section in FAQ

## Verbose log

```
evilsupahfly on Black-Beast Tue Mar 21 18:14:56
[~/src] $ youtube-dl "https://www.youtube.com/watch?v=hK_-y5fflh0" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', 'https://www.youtube.com/watch?v=hK_-y5fflh0', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-6.2.7-060207-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube] hK_-y5fflh0: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I was hoping to download the "DUN DUN DUNNN" sound effect for a video project (and my voicemail) since according to the description text on https://www.youtube.com/watch?v=hK_-y5fflh0, it's royalty free, but every time I try, I get the error  "Unable to extract uploader id" which was allegedly resolved in #31530.

My system: Linux Mint 21.1 x86_64, Kernel: 6.2.7-060207-generic

**Comment by dirkf** [comment]
You found the problem issue (thanks), so your real problem is that you didn't manage to update your yt-dl. Instead of showing a problem log that we all know about, post a log of how you tried to update it. From the above it looks like you should be able to update to a "modern" version of yt-dl with something like:
```
python3 -m pip install --force-reinstall 'git+https://github.com/ytdl-org/youtube-dl.git@master#egg=youtube_dl'
```
or if you don't have _git_ installed:
```
python3 -m pip install --force-reinstall 'https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.tar.gz'
```
You'll need to run the command as admin (_sudo_ etc) since the package was installed system-wide.

**Comment by dirkf** [comment]
In principle the commands that I proposed should have updated the version shown in your logs, but glad it's working now. I expect that Mint will pull the release version when it's ready (#31585 ).
