### ISSUE TITLE
Error to download a youtube video/music

### ISSUE THREAD

**Issue by Kerverosmx1** [ytdl-org/youtube-dl#31902]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ X ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ X ] I've checked that all provided URLs are alive and playable in a browser
- [ X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ X ] I've read bugs section in FAQ

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-errors', '-4', '--geo-bypass', '--buffer-size', '12K', '--http-chunk-size', '10M', '--restrict-filenames', '--no-overwrites', '--console-title', '--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', '-x', '--audio-format', 'mp3', '--audio-quality', '192K', 'https://www.youtube.com/watch?v=mzTew3e0Ygk']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.9 (CPython) - Linux-5.15.89-1-MANJARO-ARM-RPI-aarch64-with-glibc2.35
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 400: Bad Request
[youtube] mzTew3e0Ygk: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

I try to download the mp3 of this link, but have an error, is the first time that hapend, y download more than 13 video and mp3 files

**Comment by dirkf** [comment]
>[ ] I'm reporting a broken site support issue

No, you are, but you shouldn't be.
>[ ] I've searched the bugtracker for similar bug reports including closed ones

Do it. Learn by reading #30839 (**again**?).

>[x] I've read bugs section in FAQ

Apply it.
