### ISSUE TITLE
cannot import name 'functools' from 'youtube_dl.compat'

### ISSUE THREAD

**Issue by CrazyGoatt** [ytdl-org/youtube-dl#31914]
## Checklist
- [✔️ ] I'm reporting a broken site support issue
- [✔️ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [✔️ ] I've checked that all provided URLs are alive and playable in a browser
- [✔️ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [✔️ ] I've searched the bugtracker for similar bug reports including closed ones
- [✔️ ] I've read bugs section in FAQ

## Verbose log

/root/.pm2/logs/kev-error.log last 15 lines:
0|kev      |
0|kev      | The above exception was the direct cause of the following exception:
0|kev      |
0|kev      | Traceback (most recent call last):
0|kev      |   File "/root/Bots/GlobalGoat-v1.0/globalgoat.py", line 22, in <module>
0|kev      |     bot.load_extension(extension)
0|kev      |   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 678, in load_extension
0|kev      |     self._load_from_module_spec(spec, name)
0|kev      |   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
0|kev      |     raise errors.ExtensionFailed(key, e) from e
0|kev      | **discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.music' raised an error: ImportError: cannot import name 'functools' from 'youtube_dl.compat' (/usr/local/lib/python3.7/dist-packages/youtube_dl/compat.py)**
0|kev      | Ignoring exception in command None:
0|kev      | discord.ext.commands.errors.CommandNotFound: Command "entrar" is not found
0|kev      | Ignoring exception in command None:
0|kev      | discord.ext.commands.errors.CommandNotFound: Command "p" is not found

## Description

i made a time ago a discord bot, it works for more than one year but around 3 days ago it give me that error, i already unistall - install it again. remove the machine and create a new one, i already search for error on github but i didnt found nothing about it. thanks for help! :)

**Comment by dirkf** [comment]
`functools` isn't a name that can be imported from `youtube_dl.compat`. Instead, just `import functools`.

But this must be a problem in the bot code. As requested in #30839, try to reproduce the problem with a plain yt-dl command. Otherwise I'll close the issue.

**Comment by dirkf** [comment]
`functools` is used elsewhere in yt-dl but isn't even mentioned in `compat.py`: I doubt that it ever has been. No recent commit involves it.

Look at your build to see what else has changed in the whole application. Try stubbing out the call to the yt-dl API in your code to see what happens and/or making a test harness to emulate your bot environment that you can run locally.

This repo stands for olde code versions, but it does look like your discord server and Python are behind the supported versions.

**Comment by dirkf** [comment]
Closing this as out of scope, but if you do manage to find a problem with yt-dl after debugging this please let us know.
