### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by korallse** [ytdl-org/youtube-dl#31920]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
https://www.youtube.com/watch?v=-LC9LgRDtRU&t=180s

This is the file im trying to download but i get a error. Saying that i should reach out to you guys and get help.

**Comment by dirkf** [comment]
When you do we ask you to read and follow #30839. Why not do that and help yourself too?
