### ISSUE TITLE
Certificate is Expired

### ISSUE THREAD

**Issue by J-Wick4** [ytdl-org/youtube-dl#31928]
Yo, update your certificate, it's preventing download by CURL and Brew.

➜  ~ brew install youtube-dl
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (cloudflare/cloudflare).

You have 15 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Fetching dependencies for youtube-dl: mpdecimal, readline, sqlite, xz and python@3.11
==> Fetching mpdecimal
==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/manifests/2.5.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/blobs/sha256:5b1c62c08b42feb6e48c461a9de4751803f3ccc76830213a517f0905178dbbef
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:5b1c62c08b42feb6e48c461a9de4751803f3ccc76830213a517f0905178dbbef?se=2023-03-24T21%3A00%3A00Z&sig=XTOaANmtupRs46BTm7
curl: (60) SSL: no alternative certificate subject name matches target host name 'pkg-containers.githubusercontent.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Error: youtube-dl: Failed to download resource "mpdecimal"
Download failed: https://ghcr.io/v2/homebrew/core/mpdecimal/blobs/sha256:5b1c62c08b42feb6e48c461a9de4751803f3ccc76830213a517f0905178dbbef

**Comment by dirkf** [comment]
Raise an issue with _brew_ [there](https://github.com/Homebrew/). Apparently something in their formula for a package that I'd never heard of is fetching a file from a server that's redirecting to another server not covered by the original certificate. None of this is controlled by us.
