### ISSUE TITLE
Unable to update on windows

### ISSUE THREAD

**Issue by arthurdecloedt** [ytdl-org/youtube-dl#31937]
## Checklist

- [ ] I'm reporting a broken site support issue 
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser **>irrelevant no urls used**
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PS C:\Users\ArthurDecloedt> python3 -m pip install --force-reinstall 'https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.tar.gz' >>
Collecting https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.tar.gz
  Using cached https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.tar.gz
  Preparing metadata (setup.py) ... done
Installing collected packages: youtube-dl
  Attempting uninstall: youtube-dl
    Found existing installation: youtube-dl 2021.12.17
    Uninstalling youtube-dl-2021.12.17:
      Successfully uninstalled youtube-dl-2021.12.17
  DEPRECATION: youtube-dl is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for youtube-dl ... done
Successfully installed youtube-dl-2021.12.17

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\ArthurDecloedt\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
```

## Description

As multiple users I encountered the Uploader ID problem described in #31530
To install a current version I tried the options mentioned in the thread (see above)  but PIP keeps reinstalling the old version (it uses cached because I retried to get output to paste in issue). The exe release artifact is also still the youtube-dl-2021.12.17 version. Seemingly leaving windows users no way to upgrade their Youtube-dl.
Thx for any advice/help!

**Comment by dirkf** [comment]
Unless, unusually, you originally installed yt-dl via Python and _pip_, you Windows yt-dl will be a single file self-extracting archive.

You could acquire an unofficial nightly build, as [suggested](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611), to replace it.

**Comment by arthurdecloedt** [comment]
orginal issue solved by installing using exe from https://github.com/ytdl-patched/youtube-dl/releases 

Thx @dirkf !!
