### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by frankiefaruk** [ytdl-org/youtube-dl#31932]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

youtube-dl -F 'https://www.youtube.com/watch?v=25kqobiv4ng'
[youtube] 25kqobiv4ng: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
#30839 !

Also: https://github.com/ytdl-org/youtube-dl/issues/31931#issuecomment-1483886289, but s/300/301/.

**Comment by frankiefaruk** [comment]
Thanks
