### ISSUE TITLE
Anyone still able to DL using this (original youtube-dl)? It fails for me.

### ISSUE THREAD

**Issue by goodstuff626** [ytdl-org/youtube-dl#31938]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I want to use this original youtube-dl to download videos, but it fails for me everytime. Log viewer shows - Child process exited with non-zero code: 3221225781
Anyway to fix?

**Comment by dirkf** [comment]
#30839 !

If your issue is not already reported (you need to look at the verbose log with `-v`) create a new issue using the appropriate issue template and including the verbose log.
