### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by muzza-r** [ytdl-org/youtube-dl#31933]
## Checklist

- [ ] I'm reporting a broken site support issue  *** I don't know what this means
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\Richard\F>"youtube-dl (inc Python).exe" https://www.youtube.com/playlist?list=PL-99frSsa2uhj4jxiogC_x3XSwWvlobYn --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/playlist?list=PL-99frSsa2uhj4jxiogC_x3XSwWvlobYn', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] PL-99frSsa2uhj4jxiogC_x3XSwWvlobYn: Downloading webpage
[download] Downloading playlist: Alphalive
[youtube:tab] playlist Alphalive: Downloading 5 videos
[download] Downloading video 1 of 5
[youtube] ijjP9yoed7Q: Downloading webpage
[youtube] ijjP9yoed7Q: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hi,

I have installed the latest youtube-dl with Python from here: http://ytdl-org.github.io/youtube-dl/. I also installed the latest Visual C++ from Microsoft.

I tried to download a playlist but I get the error "Unable to extract uploader id; please report this issue on https://yt-dl.org/bug"
The playlist seems to be recognised and works on Youtube and is public.
I've checked the FAQ.

Any help much appreciated.

Thank you,
Richard

**Comment by muzza-r** [comment]
Update: I have tried downloading a single file and I get a similar error. Here is the error message with a single file:

C:\Users\Richard\F>youtube-dl.exe https://www.youtube.com/watch?v=ijjP9yoed7Q&list=PL-99frSsa2uhj4jxiogC_x3XSwWvlobYn&index=2&t=34s --verbose
[youtube] ijjP9yoed7Q: Downloading webpage
[youtube] ijjP9yoed7Q: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
'list' is not recognized as an internal or external command,
operable program or batch file.
'index' is not recognized as an internal or external command,
operable program or batch file.
't' is not recognized as an internal or external command,
operable program or batch file.

P.S. I am using the latest version:
C:\Users\Richard\F>youtube-dl.exe -U
youtube-dl is up-to-date (2021.12.17)

**Comment by dirkf** [comment]
>[ ] I'm reporting a broken site support issue *** I don't know what this means

It means that you experienced an error with a site that is supposed to be supported by yt-dl. You did, but that doesn't mean you should report it in a new issue.
>[x] I've searched the bugtracker for similar bug reports including closed ones

Read #30839 (**again**?) to find out how.

>[x] I've read bugs section in FAQ

This should also have been useful knowedge.

**Comment by muzza-r** [comment]
That's a disappointing response. I did all the bureaucracy that you asked for. I didn't find the appropriate fix in the bug report. And no, there was nothing useful in the FAQ.

This is not the way to encourage users to flock to your software. Treat us badly and we will walk. 

*gone*

**Comment by dirkf** [comment]
Feel free.

The relevant issue is **actually linked** from the pinned issue that you were asked to read and apply, and it's the only issue with more than 300 comments in the first page of results for `is:issue Unable to extract uploader id -label:duplicate` and the top or thereabouts, depending on whether more dumbass duplicate issues have just been created that haven't yet been marked, after adding `in:title` as suggested.
