### ISSUE TITLE
does youtube-dl require a console to work ?

### ISSUE THREAD

**Issue by dqew** [ytdl-org/youtube-dl#31948]
i have compiled my script to an exe the exe doesnt have a console. when i press the download button on the exe it closes. however when i do this in visual studio with the scripts it works fine. is this because it requires a console to run ??

**Comment by dirkf** [comment]
Manual, Description, l.1:
>youtube-dl is a command-line program ...

...as you found.

**Comment by pukkandan** [comment]
If OP is asking whether the process needs an attached terminal, the answer is no.
