### ISSUE TITLE
My dirkf is malfunctioning

### ISSUE THREAD

**Issue by muzza-r** [ytdl-org/youtube-dl#31945]
I wish to report a malfunctioning developer. 

While I have full respect for the hard work that the developers put in, and I know I'm not paying for a service, but a bit of respect in communicating with users is in order. When we put in the time and effort to follow to the letter the bureaucracy required for making a bug request (and yes I understand why you want it) it is not good behaviour to dismiss us out of hand.

In this respect I wish to report a malfunctioning dirkf. Please can you see what can be done to fix the bugs in this developer. Thank you.

**Comment by muzza-r** [comment]
No sense of humour!
I see you are digging your heels in and not listening to fair feedback. More fool you. Listen to your users!

**Comment by dirkf** [comment]
Somewhat amusing but still spam. Try this https://github.com/ytdl-org/youtube-dl/issues/31931#issuecomment-1483886289 for a laugh.
