### ISSUE TITLE
OSError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### ISSUE THREAD

**Issue by NickDeMiceli20** [ytdl-org/youtube-dl#31958]
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

DownloadError                             Traceback (most recent call last)
DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
[/usr/local/lib/python3.9/dist-packages/pafy/backend_youtube_dl.py](https://localhost:8080/#) in _fetch_basic(self)
     41             # Turn into an IOError since that is what pafy previously raised
     42             except youtube_dl.utils.DownloadError as e:
---> 43                 raise IOError(str(e).replace('YouTube said', 'Youtube says'))
     44 
     45         if self.callback:
     
     
     This is my code:
!pip install speechrecognition -q
!pip install --upgrade pafy
!pip install -U youtube-dl

import speech_recognition as sr
import pafy
import re 
import requests
import os

# authenticate with the YouTube API and retrieve the ID of the live video
# replace YOUR_API_KEY with your actual API key
api_key = '***********************************'
video_url = 'https://www.youtube.com/watch?v=wfAa1GiNdgM'
video = pafy.new(video_url)
pafy_video = video.getbest()

**Comment by dirkf** [comment]
#30839 !
