### ISSUE TITLE
Downolads failed

### ISSUE THREAD

**Issue by dieterle1956** [ytdl-org/youtube-dl#31950]
<Hi to all of you

got problems downloading files with your YDL-UI portable v.2.9.0
Version 2021.06.06

OS: Windows 10 Pro
Version 22H2
Build: 19045.2728
Performance: Windows Featured Experience Pack 120.2212.4190.0
Browser: Google Chrome Version 111.0.5563.111

for example:
Working Directory: C:\Users\HD\Desktop
YDL Version: 2.9.0

Executing: C:\Program Files (x86)\YDL-UI_v2.9.0.0_Portable\bin\youtube-dl.exe --ignore-config --no-overwrites --no-mtime --no-cache-dir --format "bestvideo[height=?1080][fps=?60]+bestaudio/bestvideo[height=?1080][fps=?50]+bestaudio/bestvideo[height=?1080][fps=?48]+bestaudio/bestvideo[height=?1080][fps=?30]+bestaudio/bestvideo[height=?1080][fps=?25]+bestaudio/bestvideo[height=?1080][fps=?24]+bestaudio/bestvideo[height=?720][fps=?60]+bestaudio/bestvideo[height=?720][fps=?50]+bestaudio/bestvideo[height=?720][fps=?48]+bestaudio/bestvideo[height=?720][fps=?30]+bestaudio/bestvideo[height=?720][fps=?25]+bestaudio/bestvideo[height=?720][fps=?24]+bestaudio/bestvideo[height=?480][fps=?60]+bestaudio/bestvideo[height=?480][fps=?50]+bestaudio/bestvideo[height=?480][fps=?48]+bestaudio/bestvideo[height=?480][fps=?30]+bestaudio/bestvideo[height=?480][fps=?25]+bestaudio/bestvideo[height=?480][fps=?24]+bestaudio/bestvideo[height=?360][fps=?60]+bestaudio/bestvideo[height=?360][fps=?50]+bestaudio/bestvideo[height=?360][fps=?48]+bestaudio/bestvideo[height=?360][fps=?30]+bestaudio/bestvideo[height=?360][fps=?25]+bestaudio/bestvideo[height=?360][fps=?24]+bestaudio/bestvideo[height=?240][fps=?60]+bestaudio/bestvideo[height=?240][fps=?50]+bestaudio/bestvideo[height=?240][fps=?48]+bestaudio/bestvideo[height=?240][fps=?30]+bestaudio/bestvideo[height=?240][fps=?25]+bestaudio/bestvideo[height=?240][fps=?24]+bestaudio/bestvideo[height=?144][fps=?60]+bestaudio/bestvideo[height=?144][fps=?50]+bestaudio/bestvideo[height=?144][fps=?48]+bestaudio/bestvideo[height=?144][fps=?30]+bestaudio/bestvideo[height=?144][fps=?25]+bestaudio/bestvideo[height=?144][fps=?24]+bestaudio/bestvideo[height<=?1080][fps<=?60]+bestaudio/best" --prefer-ffmpeg --ffmpeg-location "C:\Program Files (x86)\YDL-UI_v2.9.0.0_Portable\bin\ffmpeg\ffmpeg.exe"  "https://youtu.be/ZH4uoPd6GWA"

[youtube] ZH4uoPd6GWA: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Hope you can help
Thanks in advance
Dieter

######################################################################
  WARNING!
  IGNORING THE FOLLOWING TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE
######################################################################

-->

## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
#30839 !
