### ISSUE TITLE
yt-dlp certificate is not valid for 'www.youtube.com'.

### ISSUE THREAD

**Issue by 781087595** [ytdl-org/youtube-dl#31959]
yt-dlp -F "https://www.youtube.com/watch?v=v9YRQFu6-PI"

WARNING: [youtube] Unable to download API page: <urlopen error [Errno 101] Network is unreachable> (caused by URLError(OSError(101, 'Network is unreachable')))
ERROR: [youtube] v9YRQFu6-PI: Unable to download API page: <urlopen error [Errno 101] Network is unreachable> (caused by URLError(OSError(101, 'Network is unreachable')))
how to deal with it

**Comment by dirkf** [comment]
1. #30839 !
2. yt-dlp? #30839 !
3. Before considering raising this issue in the correct tracker, consider why you think that a "certificate" has anything to do with your problem, rather than that you have unplugged your network in some way.
