### ISSUE TITLE
youtube-dl claims: "Unable to extract uploader id"

### ISSUE THREAD

**Issue by gramo44** [ytdl-org/youtube-dl#31961]
$ youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

$ youtube-dl --verbose https://youtube.com/live/3tAUmLTWB_s
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://youtube.com/live/3tAUmLTWB_s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.14 (CPython) - Linux-5.15.18-desktop-2.mga8-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.5, ffprobe 4.3.5
[debug] Proxy map: {}
[youtube:tab] live: Downloading webpage
[youtube] 3tAUmLTWB_s: Downloading webpage
[youtube] 3tAUmLTWB_s: Downloading m3u8 information
[youtube] 3tAUmLTWB_s: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by shazzner** [comment]
Same issue.
