### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by planetminguez** [ytdl-org/youtube-dl#31973]
[

## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

****************************************THIS IS THE ERROR I AM GETTING*************************

bash-5.2$ [youtube] VroEiMOJPm8: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

****************************************THIS IS THE ERROR I AM GETTING*************************

## Description

WRITE DESCRIPTION HERE

**Comment by spider4216** [comment]
the same

**Comment by gigamarr** [comment]
+

**Comment by planetminguez** [comment]
glad u reported it too.....hopefully they fix it right away......

**Comment by rwr-1958** [comment]
Same error here. And just to add "Be sure to call youtube-dl with the --verbose flag and include its complete output." : 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://youtu.be/c6T5bcK2ed4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-135-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {}
[youtube] c6T5bcK2ed4: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Just-Moh-it** [comment]
If you would've searched GitHub for this issue, you would have found it already 🙃 https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by planetminguez** [comment]
> If you would've searched GitHub for this issue, you would have found it already 🙃 #31530

Is that so......where?

**Comment by planetminguez** [comment]
> If you would've searched GitHub for this issue, you would have found it already 🙃 #31530

Word as bon?!
