### ISSUE TITLE
why the latest vers is the very -old- 2021 one...??!!!

### ISSUE THREAD

**Issue by p060477** [ytdl-org/youtube-dl#31975]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE hi!, why the latest is the very old 2021 vers....??...it really do not work anymore.....:( is this project ELO...??

**Comment by rohnson1999** [comment]
dose this mean the project is no more maintained?
