### ISSUE TITLE
can't find the current version pls try later

### ISSUE THREAD

**Issue by p060477** [ytdl-org/youtube-dl#31979]
hi,
why i always get this error...?...:

C:\YOUTUBE-DL>youtube-dl -U
ERROR: can't find the current version. Please try again later.

C:\YOUTUBE-DL>

**Comment by dirkf** [comment]
#30839 ! Show a verbose log.

However, the error occurs when the text at the URL https://yt-dl.org/update/LATEST_VERSION can't be read, so try accessing that in some other way(s):
```console
$ wget -q -O - 'https://yt-dl.org/update/LATEST_VERSION'; echo
2021.12.17
$
```

**Comment by p060477** [comment]
i've win 10 home 64 and if i try yr suggestion i get this error:

yt-dl.org/update/LATEST_VERSION"'& echo
"$" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
ECHO attivo.

C:\Users\Luca\Desktop\youtube-dl>2021.12.17
"2021.12.17" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

C:\Users\Luca\Desktop\youtube-dl>$ curl -L "https://yt-dl.org/update/LATEST_VERSION"& echo
"$" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
ECHO attivo.

C:\Users\Luca\Desktop\youtube-dl>2021.12.17
"2021.12.17" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

C:\Users\Luca\Desktop\youtube-dl>$
"$" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

C:\Users\Luca\Desktop\youtube-dl>

**Comment by dirkf** [comment]
Leave out the system output: `curl -L "https://yt-dl.org/update/LATEST_VERSION" & echo`

Also, try the URL in your browser.

**Comment by p060477** [comment]
thxs for yr attention:

if i leave out that part i got:

C:\Users\Luca\Desktop\youtube-dl>$ wget -q -O - "https://yt-dl.org/update/LATEST_VERSION"'& echo
"$" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
ECHO attivo.

C:\Users\Luca\Desktop\youtube-dl>2021.12.17

and if i put the url in my browser i got a file downloaded i attach it  here
[LATEST_VERSION.txt](https://github.com/ytdl-org/youtube-dl/files/11124005/LATEST_VERSION.txt)

**Comment by dirkf** [comment]
What I suggested is what you should type, not what you should remove!

The LATEST_VERSIKON.txt is correct.

**Comment by dirkf** [comment]
The line should have had a `.`: `curl -L "https://yt-dl.org/update/LATEST_VERSION" & echo.`

That command just prints out the latest version, which is what your log said was failing with `youtube-dl -U`. If that command is not working you need to show us a verbose log (add the `-v` option).

The command `youtube-dl -U` can be used to update your installation to the latest release version, but you probably have that already. If you want a version that currently **works**, refer to #31530.

**Comment by dirkf** [comment]
You pasted unwanted initial punctuation which broke the _curl_ commands, unlike the one in https://github.com/ytdl-org/youtube-dl/issues/31979#issuecomment-1492366557.

The error that prevented `-U` from working is `SSL: CERTIFICATE_VERIFY_FAILED`. This means that the certificates used by the Python 3.4 in the yt-dl package aren't up-to-date: these certificates are part of your Windows set-up.

This is the same issue as #25491: for a solution in Windows, see https://github.com/ytdl-org/youtube-dl/issues/25491#issuecomment-665978751. For a work-around, use `--no-check-certificates`, but then, obviously, there is no security check that you are really getting the update from the youtube-dl website.

**Comment by p060477** [comment]
ths so much again:
if i past without initial punctuation i got:

C:\Users\Luca\Desktop\youtube-dl>: curl -L "https://yt-dl.org/update/LATEST_VERSION" & echo
C:\Users\Luca\Desktop\youtube-dl>

about the workaround i got:

C:\Users\Luca\Desktop\youtube-dl>youtube-dl -U --no-check-certificates
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: --no-check-certificates

**Comment by dirkf** [comment]
The `:` is a label or comment in _cmd_. Look again, but add the `.` directly after `echo`. That removes the unwanted `ECHO attivo.` ("ECHO is on") response.

#25491 says that you need to update your Windows certificate store to remove an expired certificate. Firefox has its own certificate bundle, regularly updated and won't show the problem. Edge can work out an alternative certificate path to avoid the expired cert. In the end this is an issue with the admin of your Windows system and not something that we can solve. Internet search engines exist that you could use to find out more.

Work-around: `--no-check-certificate` (no `s` in yt-dl, sorry)

**Comment by dirkf** [comment]
Also, bear my earlier comment in mind:
>The command youtube-dl -U can be used to update your installation to the latest release version, but you probably have that already. If you want a version that currently works, refer to #31530.

**Comment by p060477** [comment]
hi, first thxs so much indeed again
the work around rules!...:
C:\Users\Luca\Desktop\youtube-dl>YOUTUBE-DL -U --no-check-certificate
youtube-dl is up-to-date (2021.12.17)

this is what i got since some times ago simply with the: -U  cmd line...

you say that :
"In the end this is an issue with the admin of your Windows system and not something that we can solve"..:
but i'm the admin of my pc..i'm the only user and i've admin rights cause i'm the only admin of my pc..so why i'm not able to solve..??

and you say:
"If you want a version that currently works, refer to https://github.com/ytdl-org/youtube-dl/issues/31530."...:
i've been lost in all the comments of that link...:(
....to sum up what shall i have to do...?? 
aplogize my very few skills...and also english is really not my mother language at all...apologize again..:(

and why the youtube-dl latest vers is so old..??...2021... :(

thxs so much again for yr attention and very kind patience too

cheers

**Comment by dirkf** [comment]
You should be able to solve the certificate problem by researching it and using your admin rights to apply the necessary change. Ask how to do that in a Windows forum, or by searching the Web for, eg, "Windows remove expired certificate", "Windows update certificate store". You may find advice like this https://www.thesslstore.com/blog/how-to-remove-certificates-from-windows-10/, https://woshub.com/updating-trusted-root-certificates-in-windows-10/; I can't say whether these are reliable; also, a list of CA certificates: https://www.e2encrypted.com/certs/ca-certificate-list/.

For now, you should replace your yt-dl with an unofficial nightly build as suggested in the linked issue (follow the link from the Description and read that). If there's too much English, use something like Google Translate.

>and why the youtube-dl latest vers is so old..??...2021... :(

#30585

**Comment by p060477** [comment]
hi and thxs again:
1) which unofficial build you suggest?
2) and about why no updates since 2021 i see the link you gave:https://github.com/ytdl-org/youtube-dl/pull/30585 but i do not
    find an answer...:( which is yours to sum up..??
thxs so much again indeed for yr kind helping and gentle patience
cheers

**Comment by dirkf** [comment]
1. The Windows build at the site linked in the tldr; post.

2. Actually #31585.

**Comment by p060477** [comment]
1) you mean this: https://github.com/yt-dlp/yt-dlp 
   and its 2023.03.04 latest vers? 

thxs so much for yr kind helping
cheers

**Comment by p060477** [comment]
> 1. The Windows build at the site linked in the tldr; post.

1)
Do you mean this: https://github.com/yt-dlp/yt-dlp
and its 2023.03.04 latest version ?

**Comment by dirkf** [comment]
yt-dlp is a fork with additional features but retaining compatibility, depending on options used. The unofficial nightly builds, also linked, are taken from the latest yt-dl code.

**Comment by p060477** [comment]
hi, thxs so much again
"The unofficial nightly builds, also linked, are taken from the latest yt-dl code."...:
could you pls put here the direct link cause i'm not able to discover it...
thxs so much again
cheers

**Comment by nicolaasjan** [comment]
> could you pls put here the direct link cause i'm not able to discover it...

It's indeed a [bit hidden](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611). 
Here you are:
https://github.com/ytdl-patched/youtube-dl/releases

**Comment by p060477** [comment]
finally!
so much thxs indeed dear nicollaasjan!
this works very fine without the bug that forced me to open this issue!
no problem with certificates!!
hats off!
i wish you all the best!
:)
