### ISSUE TITLE
Unable to extract uploader id;

### ISSUE THREAD

**Issue by Bungie2** [ytdl-org/youtube-dl#31978]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
/home/localadmin/Downloads# /usr/local/bin/youtube-dl -v https://www.youtube.com/watch?v=cAU4k_3zvaU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=cAU4k_3zvaU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-21-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.4.3, ffprobe 4.4.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] cAU4k_3zvaU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839 (**again**?).

>[x] I've read bugs section in FAQ

Apply it.

**Comment by Bungie2** [comment]
Hello dirkf,
you may call me stupid, but where or what is the solution to:  ERROR: Unable to extract uploader id;  Im clicking in circles but can't find the fix
Thanks for help in advance Bungie2.

**Comment by dirkf** [comment]
Did you read #30839?

Did you find the list of Known Issues, including the master issue for this error?

If for some reason reading that list was too troublesome, did you 
* carry out the suggested issue search `is:issue Unable to extract uploader id -label:duplicate` and find the 10th issue listed (the only one with >100 comments), or 
* add `in:title` to the search terms and find the top listed issue?

Did you read the Description in that issue and follow the link* that explains how to fix your installation?

*Because of poor design by GitHub, the link requires JavaScript, but I doubt that that's your problem.
