### ISSUE TITLE
ERROR: Unable to extract uploader

### ISSUE THREAD

**Issue by KitaruS** [ytdl-org/youtube-dl#31984]
This error: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. 
Be sure to call youtube-dl with the --verbose flag and include its complete output.

This is my code

os.environ["PATH"] += os.pathsep + r"C:\ffmpeg"

ffmpeg_options = {
    'options': '-vn'
}

@bot.command()
async def join(ctx):
    channel = ctx.author.voice.channel
    await channel.connect()

@bot.command()
async def leave(ctx):
    await ctx.voice_client.disconnect()

@bot.command()
async def play(ctx, url):
    if not ctx.author.voice:
        await ctx.send("Вы должны находиться в голосовом канале, чтобы использовать эту команду.")
        return

    voice_channel = ctx.author.voice.channel
    if ctx.voice_client is None:
        await voice_channel.connect()
    else:
        await ctx.voice_client.move_to(voice_channel)

    try:
        await ctx.send(f"Ищу {url} на YouTube...")
        with youtube_dl.YoutubeDL() as ydl:
            info = ydl.extract_info(url, download=False)
            url2 = info['formats'][0]['url']
        source = await discord.FFmpegOpusAudio.from_probe(url2, **ffmpeg_options)
        ctx.voice_client.play(source)
    except Exception as e:
        await ctx.send(f"Не удалось воспроизвести  {url}: {e}")

**Comment by dirkf** [comment]
#30839 !
