### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by victorlp2000** [ytdl-org/youtube-dl#31987]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X ] I've verified that I'm running youtube-dl version **2021.12.17**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
C:\Users\Victor\youtube-mp3>youtube-dl -F "https://www.youtube.com/watch?v=u1Ry3nQf3Rc" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.youtube.com/watch?v=u1Ry3nQf3Rc', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 5.1.1-essentials_build-www.gyan.dev, ffprobe 5.1.1-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] u1Ry3nQf3Rc: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update
Traceback (most recent call last):
  File "c:\users\victor\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\victor\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\victor\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\users\victor\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "c:\users\victor\appdata\local\programs\python\python38\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version;

## Description

WRITE DESCRIPTION HERE

**Comment by coffeinik** [comment]
As a temporary solution, you can clone the repository and install the latest version:
git clone https://github.com/ytdl-org/youtube-dl.git
cd youtube_dl
pip install .

**Comment by bulletmark** [comment]
I had the same problem with another link but just tried with the latest master version and that works ok.

**Comment by dirkf** [comment]
#30839 !

Use the checklist!
