### ISSUE TITLE
ERROR: Unable to extract uploader id;

### ISSUE THREAD

**Issue by Det1960** [ytdl-org/youtube-dl#31986]
Linux Mint 21
youtube-dl https://www.youtube.com/watch?v=SzP2VFieJM

give
[youtube] SzP2VFieJMo: Downloading webpage
[youtube] SzP2VFieJMo: Downloading MPD manifest
**ERROR**: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

youtube-dl is up-to-date (2021.12.17)

**Comment by Det1960** [comment]
sudo youtube-dl -U

youtube-dl is up-to-date (2021.12.17)

**Comment by dirkf** [comment]
#30839 !
