### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by johnkiguru1337** [ytdl-org/youtube-dl#31982]
➜  Folder sudo chmod a+rx /usr/local/bin/youtube-dl
➜  Folder /usr/local/bin/youtube-dl https://youtu.be/NvjLmhm-QpY
[youtube] NvjLmhm-QpY: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by poxy100** [comment]
I too Have this issue

**Comment by nartes** [comment]
`python3 -m pip install https://github.com/ytdl-org/youtube-dl`
the latest release dates back to 2021-02-17
but upstream has the latest patches regarding youtube API
changes.

@poxy100 @johnkiguru1337

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar issues including closed ones

Learn how by reading #30839 (**again**?).
