### ISSUE TITLE
Youtube-DL for exporting/importing/transferring, & editing/managing/organising YT PL's?

### ISSUE THREAD

**Issue by J-HS-L** [ytdl-org/youtube-dl#31983]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

Sick-to-death of the stock YT link/vid. management, must export all lists to format(s) usable in other bm/link/content managers (or elsewhere), with little-to-no tweaking needed!

But perhaps before doing so, just need to export/import it all to a more GP tool...

One in which I can very easily/quickly fix the terrible organisation/structure it currently has, before deciding where all of my PL's (& sub-PL's) *forever home* will be!

I've scoured the net, but so far only found disparate sol'ns that'll need to be stitched together :(

- **_Can youtube-dl help with this in its entirety, or contribute towards my ultimate aim?_**

- **_Also, any "decent" GUI's for youtube-dl?_**

**Comment by dirkf** [comment]
YT media and playlist details can be written to a JSON file that you can subsequently process, archive, etc. You can only understand if this will meet your needs by reading the documentation. _jq_ may be a useful tool.

If the _yt-dl_ CLI program doesn't exactly meet your needs, you may be able to propose some enhancement that might be generally useful, or you might create a new GUI or CLI wrapper using the `youtube_dl` Python module.

Regarding GUIs, I don't think the situation has changed since #23755. All too likely, the features you would want to use for playlist management won't be exposed by the only GUI wrapper whose UI otherwise makes sense to you.

**Comment by J-HS-L** [comment]
> YT media and playlist details can be written to a JSON file that you can subsequently process, archive, etc. You can only understand if this will meet your needs by reading the documentation. jq may be a useful tool.

Based on your own knowledge of the youtube-dl platform...
Is what I outlined doable entirely via youtube-dl, or some combo of it + other-sw?
Just want to efficiently/quickly edit playlists & their contents, after extracting from yt.
And then transfer those reorganised lists, to sw that's better at managing yt pl/links.

> Regarding GUIs, I don't think the situation has changed since https://github.com/ytdl-org/youtube-dl/issues/23755. _All too likely, the features you would want to use for playlist management won't be exposed by the only GUI wrapper whose UI otherwise makes sense to you_.

What makes you think this???

I noticed there's another project [youtube-dlp](https://github.com/yt-dlp/yt-dlp), which seems to be based on youtube-dlc, which was a fork of this project. Is there collab. between them & you guys? It seems to be more active, at least recently.

Thank you -very much- for your help/time.

**Comment by dirkf** [comment]
>... What makes you think this???

Bitter experience. But then I still prefer Word for Windows 2.0.

> ... Is there collab. between them & you guys? 

[Completely](https://github.com/ytdl-org/youtube-dl/issues/30568). You may find that yt-dlp suits your needs better. Really, you have to work out what playlist information you want to maintain and whether yt-dl or yt-dlp can generate it, and how little external processing you can get away with. Personally, I generally use yt-dl for one-off downloads, testing problem URLs from issues, and downloading catch-up media in a set-top box where the official app is broken, so I can't help much. However I've observed quite a few completists in the yt-dl[p] user base who might be better placed to advise you.

**Comment by pukkandan** [comment]
You may also want to look at some GUI like https://github.com/axcore/tartube, https://github.com/bbilly1/tubearchivist etc. See https://www.reddit.com/r/youtubedl/wiki/info-guis
