### ISSUE TITLE
ERROR: Unable to extract uploader id;

### ISSUE THREAD

**Issue by JonyyLemon** [ytdl-org/youtube-dl#31990]
I'm sick of this comment. I've tried everything I could - Uninstalling youtube-dl and installing it again, running updates, NOTHING

## Checklist

- [ ] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PS C:\Users\nemit> youtube-dl https://www.youtube.com/watch?v=pIN3L4a_P7s
[youtube] pIN3L4a_P7s: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Follow the pinned issue #30839 ! Why didn't you?

Find the existing issue (hint: if you can manage more than a couple of paragraphs of text, the issue is listed and linked in the pinned issue).

Read about the possible solutions.
