### ISSUE TITLE
Unable to extract uploader id [BUG]

### ISSUE THREAD

**Issue by papahuge** [ytdl-org/youtube-dl#31996]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
PS D:\> .\youtube-dl -U
youtube-dl is up-to-date (2021.12.17)
PS D:\> .\youtube-dl.exe -v -f 251 https://www.youtube.com/watch?v=YSkgq9vjlbA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '251', 'https://www.youtube.com/watch?v=YSkgq9vjlbA']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4
[debug] Proxy map: {}
[youtube] YSkgq9vjlbA: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

It's just telling me that it is 'Unable to extract uploader id' for whatever reason. It is doing this with any youtube link, started doing this recently, today was first time I needed to use it in a while, and noticed that its not working. I am using the windows version. Just in case I pre-emptively replaced the .exe with the one from ur site in case of any corruption on my end. This did not fix the issue.

**Comment by dirkf** [comment]
>[ ] I'm reporting a broken site support issue

No, you are but you shoudn't be.

>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839 (**again**?).

>[x] I've read bugs section in FAQ

Also apply this.

**Comment by papahuge** [comment]
well thanks to @RutD0g for the comment, I was able to find and install yt-dlp. That fixed the issue. 

@dirkf If this is a known issue and already patched, why haven't you updated the EXE on ur site yet? just wondering...

**Comment by RutD0g** [comment]
> well thanks to @RutD0g for the comment, I was able to find and install yt-dlp. That fixed the issue.

yw

> @dirkf If this is a known issue and already patched, why haven't you updated the EXE on ur site yet? just wondering...

clicked around a bit, found this...

https://github.com/ytdl-org/youtube-dl/issues/31585

**Comment by papahuge** [comment]
> But all of this information was plainly available to anyone who followed the process set out in #30839, which is pinned with an unsubtle title "**READ THIS BEFORE OPENING A NEW ISSUE! THIS MEANS YOU!**", and where the issue for OP's problem is **actually listed** as a known issue, even if searching the tracker might seem too hard.
> 
> How was it possible to avoid finding this out before opening the issue, especially when following the checklist as claimed?

If only you spent as much time building exe, and updating ur site, as much as you do complaining about rules and regulations on github... then maybe all of this could have been avoided? 🤷‍♂️

**Comment by dirkf** [comment]
Whenever someone ignores the self-help that is already in place and creates an unnecessary duplicate issue, the issue has to be triaged and closed to avoid breaking the issue tracker for future reporters who do follow the self-help. Guess what? That interferes with solving problems like #31585 that need a concentrated dose of my free time.

In this case you followed the issue template correctly unlike most duplicate reporters, so if the template or other self-help could be improved in some way that would have directed you to the existing issue I'd like to know. Hence why I asked
>How was it possible to avoid finding this out before opening the issue, especially when following the checklist as claimed?
