### ISSUE TITLE
Yotube-DL no longer recognizing "extractor upload I.D"  

### ISSUE THREAD

**Issue by HalfEatnPickle** [ytdl-org/youtube-dl#32004]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

As the title says I tried downloading a video via D:\Youtube Videos> youtube-dl.exe -x --audio-format wav (YT LINK) but it doesn't matter what video it still doesn't want to download despite me doing this command almost every time I use YouTube-dl. Is there anyway to fix this or am I just not seeing the Issue. Any help would be appreciated. I've looked through the forms they're to confusing and don't make any sense if they fixed it or not. Its been over a year since I installed youtube-dl and I don't remember how I did it making it even more confusing when other posts have "solutions" but doesnt explain how to fix it

**Comment by aWinglessMonkey** [comment]
I came here because of this exact bug, but issue #31530 has provided a solution. You will need a version of git installed that is accessible to your command line, as well as pip (which is part of python).
Or else find another way to replace your local installation of youtube-dl with the current master version on github here.

**Comment by aWinglessMonkey** [comment]
following up on the edit I made to that comment, here:
https://github.com/ytdl-patched/youtube-dl/releases

**Comment by HalfEatnPickle** [comment]
> following up on the edit I made to that comment, here: https://github.com/ytdl-patched/youtube-dl/releases

Thank you so much

**Comment by dirkf** [comment]
Use #30839, as asked, to find this information without opening a new issue.
