### ISSUE TITLE
can't download any video's and playlist with the use of terminal

### ISSUE THREAD

**Issue by uzairahmed2126** [ytdl-org/youtube-dl#32000]
## Checklist

- [x] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by uzairahmed2126** [comment]
check this isssue

**Comment by dirkf** [comment]
#30839 !
