### ISSUE TITLE
Unable to get OGG format to download

### ISSUE THREAD

**Issue by Catscrath25** [ytdl-org/youtube-dl#32002]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

So I am trying to get my files downloading on a OGG format. When I put nothing into the backend command line (Both yt-dlp.exe and youtube-dl.exe) with either the commands --format -ogg or -f ogg it returns with the download having an error and reporting "Requested format is not available. Use --list-formats for a list of available formats", however even when I put --list-formats in the backend command line it does nothing. Help would be much appreciated.

**Comment by dirkf** [comment]
Please show a verbose log with your yt-dl command.

**Comment by Catscrath25** [comment]
2023-04-06 14:36:52,541-DEBUG-Worker_1-WARNING: [youtube:tab] Unable to recognize playlist. Downloading just video lqzQl0sffm0
2023-04-06 14:36:52,542-DEBUG-Worker_1-ERROR: [youtube] lqzQl0sffm0: Requested format is not available. Use --list-formats for a list of available formats
2023-04-06 14:36:52,542-DEBUG-Worker_1-Child process exited with non-zero code: 1

Like this?

**Comment by Catscrath25** [comment]
The commands I tried were
-f ogg
--format ogg
--format -ogg
all to the same results

**Comment by Catscrath25** [comment]
Well I guess my question is then what do I need to put in to make it download as OGG.

**Comment by dirkf** [comment]
There are two routes to enlightenment, not mutually exclusive:
* post a verbose log showing what you are trying to do and how it's failing (it will show the version of the program, the URL you are trying to process, the options you are using, the environment where it's being run, etc);
* read the documentation as suggested to understand how yt-dl works.

**Comment by Catscrath25** [comment]
I put in -v into the command line and it did not seem to change anything or give any sort of detailed log. I am using the GUI version of the program if that changes anything. Is there a specific button I should be pressing to run the command or a specific format to how I am putting in the commands? I want to get you the logs you need and such but both the program and the reference material is very confusing and difficult to decipher into layman's terms that I can make sense of.

**Comment by dirkf** [comment]
For support with a GUI, [use the support channel for the GUI](https://github.com/ytdl-org/youtube-dl/issues/30839).

For support here, you need to type a command into a terminal window in your system. There are plenty of examples of such commands and logs in other active issues. If the GUI wrapper shows the yt-dl command being run, try using that.

**Comment by Catscrath25** [comment]
So it won't work through the application itself and needs to be put into the command prompt itself? Because here is what I have and it doesn't show any way of running the script other then converting a video and then checking the log which only gives the information I posted before.
![Captureda](https://user-images.githubusercontent.com/34626643/230505641-e9095870-46ce-4903-a648-e41b3b4e047c.PNG)

**Comment by dirkf** [comment]
This GUI is someone else's problem.

If you want help with youtube-dl, ask here with an actual youtube-dl command. You may then be able to apply what you learn to the GUI. Otherwise, ask whoever supports the GUI to help: #30839.

Also, if you want help with yt-dlp, use its issue tracker rather than this one, but I'm fairly sure the same applies.
