### ISSUE TITLE
ERROR: unable to download video data: <urlopen error [Errno 11004] getaddrinfo failed>

### ISSUE THREAD

**Issue by ashwin92** [ytdl-org/youtube-dl#3201]
Windows 7(32 Bit).

It was fine till yesterday and I made a few downloads. No software updates recently. Just installed wo-mic client. 

Getting this Error in my cmd prompt over any video I try.

Note:
When I try this cmd::
C:\Users\Public\Technical Stuff>youtube-dl.exe -F "https://www.youtube.com/watch?v=FQZbDVaT39Q"
[youtube] Setting language
[youtube] FQZbDVaT39Q: Downloading webpage
[youtube] FQZbDVaT39Q: Downloading video info webpage
[youtube] FQZbDVaT39Q: Extracting video information
[info] Available formats for FQZbDVaT39Q:
format code extension resolution  note
171         webm      audio only  DASH audio , audio@ 48k (worst)
140         m4a       audio only  DASH audio , audio@128k
160         mp4       144p        DASH video , video only
242         webm      240p        DASH video , video only
133         mp4       240p        DASH video , video only
243         webm      360p        DASH video , video only
134         mp4       360p        DASH video , video only
244         webm      480p        DASH video , video only
135         mp4       480p        DASH video , video only
247         webm      720p        DASH video , video only
136         mp4       720p        DASH video , video only
248         webm      1080p       DASH video , video only
137         mp4       1080p       DASH video , video only
17          3gp       176x144
36          3gp       320x240
5           flv       400x240
43          webm      640x360
18          mp4       640x360
22          mp4       1280x720    (best)

I get the various formats.

But when I try to download a video, I get this Error.

C:\Users\Public\Technical Stuff>youtube-dl.exe "https://www.youtube.com/watch?v=FQZbDVaT39Q"
[youtube] Setting language
[youtube] FQZbDVaT39Q: Downloading webpage
[youtube] FQZbDVaT39Q: Downloading video info webpage
[youtube] FQZbDVaT39Q: Extracting video information
ERROR: unable to download video data: <urlopen error [Errno 11004] getaddrinfo failed>

No updates as of yet I suppose.
My version of youtube-dl

C:\Users\Public\Technical Stuff>youtube-dl.exe --version
2014.06.26

C:\Users\Public\Technical Stuff>youtube-dl.exe --update
youtube-dl is up-to-date (2014.06.26)

**Comment by Teazane** [comment]
As suggested here, maybe you should check your proxy settings : https://stackoverflow.com/questions/5022945/urllib2-urlerror-urlopen-error-errno-11004-getaddrinfo-failed
