### ISSUE TITLE
discord music bot error

### ISSUE THREAD

**Issue by Dogunbbang** [ytdl-org/youtube-dl#32014]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Hello, I encountered an error while making a discord music bot. Please reply after looking at this attached file. If you solve this error, I will give you my love.
[오류.txt](https://github.com/ytdl-org/youtube-dl/files/11185361/default.txt)

**Comment by dirkf** [comment]
#30839 !

**Comment by Dogunbbang** [comment]
yes?

**Comment by dirkf** [comment]
Read it, find the issue that deals with your problem, apply the appropriate fix according to your system.
