### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by davidfavor** [ytdl-org/youtube-dl#32029]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
(base) imac> youtube-dl -v 'https://www.youtube.com/watch?v=WVMhKgbrQ_I'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=WVMhKgbrQ_I']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.12 (CPython) - macOS-10.16-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] WVMhKgbrQ_I: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/david/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/david/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/david/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Users/david/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/Users/david/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ver```


## Description

<!--
Subject says it all.
-->

WRITE DESCRIPTION HERE

Downloads fail for some URLs.

**Comment by dirkf** [comment]
#30839 says it all, especially regarding how to do this successfully:
>[x] I've searched the bugtracker for similar bug reports including closed ones

>[x] I've read bugs section in FAQ

Apply that.

**Comment by davidfavor** [comment]
How I fixed this on OSX using MacPorts, covered in the ticket number referenced above.

```
sudo port install yt-dlp
sudo yt-dlp --update
yt-dlp 'YOUTUBE URL'
```

**Comment by AskAlice** [comment]
@dirkf thanks I just searched for this and yielded some copypasta telling me to search for it.
For anyone actually trying to solve the problem, see #31530 

Why hasn't a release been cut in more than two years? I feel like less people would be opening issues if they saw new binaries available to download

**Comment by dirkf** [comment]
The pinned issue, which everyone is expected to read before opening an issue, explains how not to open a duplicate issue and includes a **list of major known issues of which #31350 is one**. That issue answers all questions regarding the issue, directly or by linking.
