### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by DrMAF** [ytdl-org/youtube-dl#32022]
Good day.
youtube-dl.exe https://(www youtube com)?list=PL0Zuz27SZ-6PrE9srvEn8nbhOOyxnWXfp gives error:
ERROR: Unable to extract uploader id;
Any suggestions?
Kind regards.

**Comment by im-vinicius** [comment]
Ohayou,

Please see #31530 for solutions

**Comment by Daquisu** [comment]
Ohayou,

Please see #31530 for solutions.

**Comment by dirkf** [comment]
Indeed, as listed in #30839.
