### ISSUE TITLE
youtube-dl does not work for Minr 21.1

### ISSUE THREAD

**Issue by Osprey58** [ytdl-org/youtube-dl#32025]
OS: Linux Mint 21.1 x86_64 
Host: Aspire XC-895 
Kernel: 5.15.0-69-generic 
Uptime: 1 day, 22 hours, 59 mins 
Packages: 4720 (dpkg), 1 (pkg) 
Shell: bash 5.1.16 
Resolution: 1920x1080 
DE: LXDE 
WM: Openbox 
WM Theme: Solarized-Dark-Cyan-3.36 
Theme: Blue-Joy [GTK3] 
Icons: Aqua-Glade_PNG [GTK3] 
Terminal: zx 
CPU: Intel i5-10400 (12) @ 4.300GHz 
GPU: Intel CometLake-S GT2 [UHD Graphics 630] 
Memory: 13586MiB / 15884MiB 

root@magnus:~/svt# yt --verbose https://www.youtube.com/watch?v=FNz-b5dnNwE&ab_channel=Morup-StafsingeHembygdsf%C3%B6rening
[1] 741578
root@magnus:~/svt# [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=FNz-b5dnNwE']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-69-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] FNz-b5dnNwE: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Because you didn't read #30839 properly?

Or didn't actually do this:
>[x] I've searched the bugtracker for similar issues including closed ones
