### ISSUE TITLE
yiotube

### ISSUE THREAD

**Issue by srem1** [ytdl-org/youtube-dl#32038]
youtube-dl https://youtu.be/F1IqONGmy5A?list=PL-1v-bX7GEtLJi6z28iuT_UaMgbhBCoNE
[youtube:tab] Downloading playlist PL-1v-bX7GEtLJi6z28iuT_UaMgbhBCoNE - add --no-playlist to just download video F1IqONGmy5A
[youtube:tab] PL-1v-bX7GEtLJi6z28iuT_UaMgbhBCoNE: Downloading webpage
[youtube:tab] PL-1v-bX7GEtLJi6z28iuT_UaMgbhBCoNE: Downloading webpage
[download] Downloading playlist: dobre stare polskie filmy
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] Downloading page 3
[youtube:tab] Downloading page 4
[youtube:tab] playlist dobre stare polskie filmy: Downloading 449 videos
[download] Downloading video 1 of 449
[youtube] jgre_79-q10: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Fray2000** [comment]
Same here, running `youtube-dl -U`

Result
youtube-dl is up-to-date (2021.12.17)

**Comment by dirkf** [comment]
#30839 !
