### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by hamedyaghoobian** [ytdl-org/youtube-dl#32049]
## Description

When using youtube-dl to download videos from a playlist, the error "Unable to extract uploader id" occurs. This error is preventing the user from being able to download videos from the playlist.

The error occurs when youtube-dl is unable to extract the uploader ID from the video's webpage. This could be due to changes in the video's webpage structure that youtube-dl is not yet able to handle.

The issue can be reported to the youtube-dl developers for them to investigate and make the necessary changes to support the webpage. The user should make sure to include the complete verbose output of youtube-dl that demonstrates the problem and follow the checklist provided in the issue template.

**Comment by dirkf** [comment]
All very true. Read #30839 (**again**?).
