### ISSUE TITLE
 Unable to extract uploader id in version 2021-12-17

### ISSUE THREAD

**Issue by jaderxnet** [ytdl-org/youtube-dl#32044]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.youtube.com/watch?v=ySzrJ4GRF7s', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.16 (CPython) - Linux-5.10.147+-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {'colab_language_server': '/usr/colab/bin/language_service'}
[youtube] ySzrJ4GRF7s: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

I tried to download several videos using youtube_dl and got the same error. On different computers. I saw the previous issues saying that it was already solved, but it doesn't work for me. I made the previous recommendations to force update and I already guaranteed that I am in version 2021-12-17. I saw that it could be something from the region, I'm in Brazil. Can someone help me ?

**Comment by jotaium11** [comment]
This also happened to me

**Comment by jaderxnet** [comment]
Thanks, 

It worked for me:

`!pip install git+https://github.com/ytdl-org/youtube-dl.git@master` 
or 
`!pip install --upgrade --force-reinstall git+https://github.com/ytdl-org/youtube-dl.git@master
 `

 Please put something like this in the Description @dirkf  , it's more efficient for everyone to understand.
