### ISSUE TITLE
Vimeo: Unable to extract info section

### ISSUE THREAD

**Issue by Stiino0** [ytdl-org/youtube-dl#32056]
Using the tool to download a vimeo embedded video using referrer. Thx in advance for any assistance!

C:\TempNew\AGConsult\AB-testen Advanced>youtube-dl --referer https://www.agconsult.com/nl/course/ab-testen-advanced/module-1/intro/ https://player.vimeo.com/video/528777631
[vimeo] 528777631: Downloading webpage
ERROR: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\TempNew\AGConsult\AB-testen Advanced>youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

C:\TempNew\AGConsult\AB-testen Advanced>youtube-dl --referer https://www.agconsult.com/nl/course/ab-testen-advanced/module-1/intro/ https://player.vimeo.com/video/528777631 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--referer', 'https://www.agconsult.com/nl/course/ab-testen-advanced/module-1/intro/', 'https://player.vimeo.com/video/528777631', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: ffmpeg git-2020-06-01-dd76226
[debug] Proxy map: {}
[vimeo] 528777631: Downloading webpage
ERROR: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\vimeo.py", line 652, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Read #30839 to find this existing issue.

As it concerns Vimeo rather than YouTube and doesn't mention `uploader id` in the error message, it's not the same problem as in the linked issue above.
