### ISSUE TITLE
Playlist download url only?

### ISSUE THREAD

**Issue by egscodes** [ytdl-org/youtube-dl#32053]
I've been using `youtube-dl -j --flat-playlist "url" > name.csv` to try and getting the url of videos, but the `--flat-playlist` gives me to much stuff and I've been having to edit the csv just to get the URL id. So I'm just wondering if theres a similar option but to just get a list of every URL in a playlist (aka i don't care about video names, etc.).

**Comment by hardboyvino** [comment]
You could try `youtube-dl --skip-download --get-url -i "url" > name.csv`

**Comment by egscodes** [comment]
When i use a playlist url i just get this `ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

Do wonder is there a way to download every video in the playlist but as mp3?

**Comment by dirkf** [comment]
Obviously yes (read the Manual, `--extract-audio`, etc) and read #30839 again to find help with the `ERROR`.

**Comment by dirkf** [comment]
Closing for lack of response.
