### ISSUE TITLE
Youtube_dl bug

### ISSUE THREAD

**Issue by anunjar26** [ytdl-org/youtube-dl#32061]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by anunjar26** [comment]
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by PetkoVasilev** [comment]
logs with `--verbose`
```
youtube-dl -F --verbose "https://www.youtube.com/watch?v=<redacted>"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--verbose', 'https://www.youtube.com/watch?v=<redacted>']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-67-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube] <redacted>: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by anunjar26** [comment]
File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper      
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error 
    self.trouble(error_message, tb)
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble      
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates

**Comment by anunjar26** [comment]
import youtube_dl 
import telegram
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters


def main():
    import logging
    logging.basicConfig(level=logging.DEBUG)
    updater = Updater('TOKEN', use_context=True)
    dispatcher = updater.dispatcher

    def start(update, context):
        context.bot.send_message(chat_id=update.effective_chat.id, text="¡Hola! Envíame un enlace de YouTube y te enviaré un archivo MP3.")

    def download_mp3(update, context):
        url = update.message.text
        ydl_opts = {
            'format': 'bestaudio/best',
            'outtmpl': '%(id)s.%(ext)s',
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': '192'
            }],
            'verbose': True
        }
        
        with youtube_dl.YoutubeDL(ydl_opts) as ydl:
            info_dict = ydl.extract_info(url, download=True)
            filename = ydl.prepare_filename(info_dict)
            with open(filename, 'rb') as f:
                context.bot.send_audio(chat_id=update.effective_chat.id, audio=f, title=info_dict.get('title'))

    dispatcher.add_handler(CommandHandler('start', start))
    dispatcher.add_handler(MessageHandler(Filters.text & ~Filters.command, download_mp3))

    updater.start_polling()
    updater.idle()

if __name__ == '__main__':
    main()

**Comment by anunjar26** [comment]
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
