### ISSUE TITLE
unable to extract uploader id

### ISSUE THREAD

**Issue by Rahul5252** [ytdl-org/youtube-dl#32068]
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by glxblt14** [comment]
Me too !

**Comment by mildred** [comment]
Probably duplicate of #31530 and yt-dlp seems to have the issue fixed.

**Comment by dirkf** [comment]
>Probably duplicate of #31530 and yt-dlp seems to have the issue fixed.

Why only "Probably"? Also, the problem and its status are clearly and accurately in the issue.

OP et al., follow #30839 **as requested** to avoid unnecessary duplicate issues and find your solution more quickly.
