### ISSUE TITLE
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### ISSUE THREAD

**Issue by EvrenTombul** [ytdl-org/youtube-dl#32067]
## Checklist

- [ x ] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I Downloaded youtube=dl , I updated latest version, I reinstalled python , still gives error, can you help me pls? 

C:\Users\evren.tombul>cd Documents\youtube_download

example; C:\Users\user\Documents\youtube_download>youtube-dl.exe https://youtu.be/dayStqiGf-s

[youtube] dayStqiGf-s: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by melonius** [comment]
Similar Bug in linux:

**Comment by XsquadKc** [comment]
Same issue for me, regardless of what arguments I try. I was inputting a playlist originally with a specified download location and got the error for every video, so I tried just a single video with only the '--verbose' argument, still doesn't work.

[debug] System config: []
[debug] User config: ['--verbose', 'https://www.youtube.com/watch?v=XqbDx8Ls9lI']
[debug] Custom config: []
[debug] Command-line args: []
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: ffmpeg 2021-11-03-git-08a501946f-full_build-www.gyan.dev, ffprobe 2021-11-03-git-08a501946f-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] XqbDx8Ls9lI: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
You're (unnecessarily) reporting a bug, not asking a question.

Follow #30839 properly as requested to avoid unwanted duplicate issues.
