### ISSUE TITLE
Youtube_dl bug

### ISSUE THREAD

**Issue by anunjar26** [ytdl-org/youtube-dl#32063]
PS G:\Mi unidad\antonio\Personal\Python\prueba>  & 'C:\Users\usuario\AppData\Local\Microsoft\WindowsApps\python3.10.exe' 'c:\Users\usuario\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '53703' '--' 'g:\Mi unidad\antonio\Personal\Python\prueba\youtubeANj.py'
DEBUG:telegram.ext.dispatcher:Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x000002038E471D80>
INFO:apscheduler.scheduler:Scheduler started
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:telegram.bot:Entering: get_me
DEBUG:apscheduler.scheduler:No jobs; waiting until a job is added
DEBUG:telegram.bot:{'supports_inline_queries': False, 'can_join_groups': True, 'username': 'YoutubeANJ_bot', 'id': 5817899021, 'can_read_all_group_messages': False, 'is_bot': True, 'first_name': 'YoutubeANJ'}
DEBUG:telegram.bot:Exiting: get_me
DEBUG:telegram.ext.updater:Bot:5817899021:dispatcher - started
DEBUG:telegram.ext.updater:Bot:5817899021:updater - started
DEBUG:telegram.ext.updater:Waiting for Dispatcher and polling to start
DEBUG:telegram.ext.updater:Updater thread started (polling)
DEBUG:telegram.ext.updater:Start network loop retry bootstrap del webhook
DEBUG:telegram.ext.dispatcher:Dispatcher started
DEBUG:telegram.ext.updater:Deleting webhook
DEBUG:telegram.bot:Entering: delete_webhook
DEBUG:telegram.bot:True
DEBUG:telegram.bot:Exiting: delete_webhook
DEBUG:telegram.ext.updater:Bootstrap done
DEBUG:telegram.ext.updater:Start network loop retry getting Updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:Getting updates: [266359428]
DEBUG:telegram.bot:[<telegram.update.Update object at 0x000002038E4D0580>]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.ext.dispatcher:Processing Update: {'message': {'date': 1681936309, 'text': '/start', 'entities': [{'offset': 0, 'length': 6, 'type': 'bot_command'}], 'photo': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'supergroup_chat_created': False, 'chat': {'type': 'private', 'last_name': 'DPS', 'username': 'antonio_dps', 'id': 1161673090, 'first_name': 'Antonio'}, 'message_id': 54, 'caption_entities': [], 'channel_chat_created': False, 'group_chat_created': False, 'new_chat_members': [], 'from': {'last_name': 'DPS', 'username': 'antonio_dps', 'id': 1161673090, 'is_bot': False, 'first_name': 'Antonio', 'language_code': 'es'}}, 'update_id': 266359428}
DEBUG:telegram.bot:Entering: send_message
DEBUG:telegram.bot:{'date': 1681936309, 'text': '¡Hola! Envíame un enlace de YouTube y te enviaré un archivo MP3.', 'entities': [], 'photo': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'supergroup_chat_created': False, 'chat': {'type': 'private', 'last_name': 'DPS', 'username': 'antonio_dps', 'id': 1161673090, 'first_name': 'Antonio'}, 'message_id': 55, 'caption_entities': [], 'channel_chat_created': False, 'group_chat_created': False, 'new_chat_members': [], 'from': {'username': 'YoutubeANJ_bot', 'id': 5817899021, 'is_bot': True, 'first_name': 'YoutubeANJ'}}
DEBUG:telegram.bot:Exiting: send_message
DEBUG:telegram.bot:Getting updates: [266359429]
DEBUG:telegram.bot:[<telegram.update.Update object at 0x000002038E4D0940>]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.ext.dispatcher:Processing Update: {'message': {'date': 1681936316, 'text': 'https://youtu.be/wyNnCJLGK5A', 'entities': [{'offset': 0, 'length': 28, 'type': 'url'}], 'photo': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'supergroup_chat_created': False, 'chat': {'type': 'private', 'last_name': 'DPS', 'username': 'antonio_dps', 'id': 1161673090, 'first_name': 'Antonio'}, 'message_id': 56, 'caption_entities': [], 'channel_chat_created': False, 'group_chat_created': False, 'new_chat_members': [], 'from': {'last_name': 'DPS', 'username': 'antonio_dps', 'id': 1161673090, 'is_bot': False, 'first_name': 'Antonio', 'language_code': 'es'}}, 'update_id': 266359429}
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.11 (CPython) - Windows-10-10.0.19045-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] wyNnCJLGK5A: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper      
    return func(self, *args, **kwargs)
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper      
    return func(self, *args, **kwargs)
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\telegram\ext\handler.py", line 198, in handle_update    return self.callback(update, context)
  File "g:\Mi unidad\antonio\Personal\Python\prueba\youtubeANj.py", line 29, in download_mp3
    info_dict = ydl.extract_info(url, download=True)
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info 
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper      
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error 
    self.trouble(error_message, tb)
  File "C:\Users\usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble      
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates
DEBUG:telegram.bot:No new updates found.
DEBUG:telegram.bot:[]
DEBUG:telegram.bot:Exiting: get_updates
DEBUG:telegram.bot:Entering: get_updates

## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
#30839 !
