### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by NEWCASHFLOW** [ytdl-org/youtube-dl#32072]
Dear youtube-dl team,

I am writing to report an issue that I encountered while using the youtube-dl tool. I was trying to download a video from YouTube using the command line, but I received the following error message:

"ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug. Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

I am using the latest version of youtube-dl and have tried running the command with the --verbose flag, but I still encountered the same error. The video I was trying to download is: [insert URL here].

I believe this issue may be related to a problem with the tool's ability to extract the uploader ID. I would appreciate any assistance you can provide in resolving this issue.

Thank you for your attention to this matter. I look forward to hearing back from you soon.

**Comment by dirkf** [comment]
Please review #30839 as requested.
