### ISSUE TITLE
video.ibm.com/embed/ not working.

### ISSUE THREAD

**Issue by michaelnoe** [ytdl-org/youtube-dl#32088]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose https://video.ibm.com/embed/24972048
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://video.ibm.com/embed/24972048']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - macOS-11.6.2-x86_64-i386-64bit
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0, rtmpdump 2.4
[debug] Proxy map: {}
[ustream] 24972048: Downloading webpage
ERROR: Unable to extract content video IDs; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/ustream.py", line 179, in _real_extract
    content_video_ids = self._parse_json(self._search_regex(
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract content video IDs; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

I have tried downloading this video, however youtube-dl keeps giving me an error...

**Comment by october262** [comment]
video link isn't working

**Comment by dirkf** [comment]
Maybe we should ask this guy: https://clay.earth/profile/d3a08af1-7c19-4757-9576-943b7cb0cdd0.

The problem page, and others, don't have a value assigned to `ustream.vars.offAirContentVideoIds`; instead a list (of 1 ID) is assigned to `ustream.vars.uumfOffAirContentVideoIds`. but that ID then leads to:
```console
...
[ustream] 132715210: Downloading JSON metadata
[ustream] 132715210: Downloading connection info
[ustream] 132715210: Downloading stream info
[ustream] 132715210: Downloading connection info (try 2)
[ustream] 132715210: Downloading stream info (try 2)
[ustream] 132715210: Downloading connection info (try 3)
[ustream] 132715210: Downloading stream info (try 3)
ERROR: No video formats found; ...
```

**Comment by dirkf** [comment]
Ustream extractor test results: 4 failed, 1 skipped.

**Comment by instak1ll** [comment]
` ✘ artem@ARTEM-PC  ~/github/yt   main  youtube-dl --no-check-certificate https://www.youtube.com/watch\?v\=EVUFwyOGMSY\&ab_channel\=NubeColectivaDevs
[youtube] EVUFwyOGMSY: Downloading webpage
[youtube] EVUFwyOGMSY: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 ✘ artem@ARTEM-PC  ~/github/yt   main  youtube-dl --no-check-certificate https://youtu.be/QRSO44Yd1as    
[youtube] QRSO44Yd1as: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 ✘ artem@ARTEM-PC  ~/github/yt   main  youtube-dl --no-check-certificate https://www.youtube.com/watch\?v\=QRSO44Yd1as
[youtube] QRSO44Yd1as: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 ✘ artem@ARTEM-PC  ~/github/yt   main  youtube-dl --no-check-certificate QRSO44Yd1as                     
[youtube] QRSO44Yd1as: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 ✘ artem@ARTEM-PC  ~/github/yt   main  `

**Comment by dirkf** [comment]
@michaelnoe,

1. are you able to play the video?
2. do you have any other video links that the Ustream extractor should handle?

It may be that Ustream has been broken or withdrawn in one of the reorganisations or retrenchments for which the modern IBM is rightly notorious.

**Comment by michaelnoe** [comment]
@dirkf: yes, i am able to play the video... using the url: video.ibm.com/embed/24972048 the video is normally located behind a pay-wall, but by using this url, it works even on a pc I never logged in on. I use chrome...

**Comment by october262** [comment]
video is now playing for me now, yesterday it was playing then all of a sudden it would
no longer load.

**Comment by dirkf** [comment]
>...using the url: video.ibm.com/embed/24972048 the video is normally located behind a pay-wall, but by using this url,...

Which URL? Do you mean not the one you mentioned originally?

**Comment by msadikyildiz** [comment]
The problem remains unsolved.

**Comment by ufgkirk** [comment]
Perhaps this issue should be closed as the URL provided in the original issue doesn't seem valid anymore.... it seems like maybe IBM changed their URL format.  My new issue #32996 contains a valid URL that is alive today and perhaps can be used to further investigate this.

**Comment by dirkf** [comment]
Continued in #32996.
