### ISSUE TITLE
Youtube-dl can't download live streams or playlists anymore

### ISSUE THREAD

**Issue by SavantSusi** [ytdl-org/youtube-dl#32087]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Description

    ~  '/home/susiterry/Don'\''t Delete/yt-dlp_linux' -v https://youtube.com/playlist?list=PLcUIjZkOEObjFCo1BlOFo4xbswhI0SiJw
zsh: no matches found: https://youtube.com/playlist?list=PLcUIjZkOEObjFCo1BlOFo4xbswhI0SiJw
    ~  '/home/susiterry/Don'\''t Delete/yt-dlp_linux' -v https://youtu.be/playlist?list=PLcUIjZkOEObjFCo1BlOFo4xbswhI0SiJw 
zsh: no matches found: https://youtu.be/playlist?list=PLcUIjZkOEObjFCo1BlOFo4xbswhI0SiJw
    ~  '/home/susiterry/Don'\''t Delete/yt-dlp_linux' -v https://www.youtube.com/live/Z7t5Ld3KZno?feature=share
zsh: no matches found: https://www.youtube.com/live/Z7t5Ld3KZno?feature=share
    ~  /home/susiterry/Don'\''t Delete/yt-dlp_linux' -v https://youtu.be/live/Z7t5Ld3KZno?feature=share
zsh: no matches found: https://youtu.be/live/Z7t5Ld3KZno?feature=share
    ~                                                                              1 ✘ 

I've tried copying the link from the address bar, I've tried copying the link after clicking the share button, I've tried editing the url. nothing works anymore.

**Comment by darksamnikk** [comment]
found a solution.............just sudo nano into youtube-dl repo and add this old line ...............
'uploader_id': self._search_regex(r'/(?:channel/|user/|@)([^/?&#]+)', owner_profile_url, 'uploader id', default=None),.......solved!!

**Comment by dirkf** [comment]
>[ ] I'm reporting a broken site support issue

Isn't it one?

>[x] I've searched the bugtracker for similar bug reports including closed ones

>I've tried copying the link from the address bar, I've tried copying the link after clicking the share button, I've tried editing the url. nothing works anymore.

Instead, why not pay attention to #30839, as requested, where the problem is **actually listed** or would be found by performing the above search as suggested.

[x] I've read bugs section in FAQ

Apply this.

> found a solution ...

Why guess or replay a stopgap hack when the problem was solved already?

**Comment by darksamnikk** [comment]
Wasnt solved on mine silly junks
