### ISSUE TITLE
Unable to extract uploader id?

### ISSUE THREAD

**Issue by laoheigou** [ytdl-org/youtube-dl#32081]
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '--audio-format', 'm4a', 'https://www.youtube.com/watch?v=mUP6CaWyaro', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: ffmpeg 2022-10-24-git-d79c240196-essentials_build-www.gyan.dev, ffprobe 2022-10-24-git-d79c240196-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] mUP6CaWyaro: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Used command "youtube-dl -x --audio-format m4a https://www.youtube.com/watch?v=mUP6CaWyaro" and got the error message when I added "--verbose". Help grealty appreciated

**Comment by jpetzke** [comment]
same with a normal download, happens on every video I tried

**Comment by nashjc** [comment]
Same issue:
john@M21:~/dwhelper$ youtube-dl --verbose https://www.youtube.com/watch?v=LMo_G1TMF2w
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=LMo_G1TMF2w']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.19.0-40-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] LMo_G1TMF2w: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Help yourself (yourselves) by reading and following #30839.

>[x] I've searched the bugtracker for similar bug reports including closed ones

Doing that according to the recommendations in #30839 would have helped but shouldn't have been necessary.

>[x] I've read bugs section in FAQ

Apply this.

**Comment by laoheigou** [comment]
> Help yourself (yourselves) by reading and following #30839.
> 
> > [x] I've searched the bugtracker for similar bug reports including closed ones
> 
> Doing that according to the recommendations in #30839 would have helped but shouldn't have been necessary.
> 
> > [x] I've read bugs section in FAQ
> 
> Apply this.

Sounds great. Old guy and literally the first time I've used GitHub. I haven't found squat - if you'd like to point me to the thread instead of the "READ ME FIRST" post, which I did and tried to follow, then that'd be extra helpful.

**Comment by dirkf** [comment]
Your error message
>`... Unable to extract uploader id ...`

Currently the issue you should have found, as well as **being listed in the pinned issue**, is in the first page of [these results](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+Unable+to+extract+uploader+id+-label%3Aduplicate) and is the top issue when `in:title` is added to search terms.
