### ISSUE TITLE
ERROR: Unable to extract uploader id; please report this issue

### ISSUE THREAD

**Issue by spetragl** [ytdl-org/youtube-dl#32086]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

PASTE VERBOSE LOG HERE
youtube-dl.exe --verbose -i -f best -o "%(title)s.%(ext)s" "https://www.youtube.com/watch?v=GWFHVBnR7G0"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-i', '-f', 'best', '-o', '%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=GWFHVBnR7
G0']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] GWFHVBnR7G0: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in__
extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534
, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 17
94, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 101
2, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure
you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include i
ts complete output.

## Description

 Unable to extract uploader id 
Also, C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org doesn't exist on my PC.

**Comment by dirkf** [comment]
>[ ] I'm reporting a broken site support issue

You are, but you shouldn't be.

>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839 (**again**)?

>[x] I've read bugs section in FAQ

Apply this.

>...C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org doesn't exist on my PC.

The pathname is an artefact of the self-extracting single file build for Windows.
