### ISSUE TITLE
Need to clarification about vimeo

### ISSUE THREAD

**Issue by ProvisionlabTeam** [ytdl-org/youtube-dl#32095]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
hey there. any tips to download something from vimeo?
https://vimeo.com/756354595 yt-dl said 
[vimeo] 756354595: Checking Original video URL
[vimeo] 756354595: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 756354595: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 756354595: Downloading fastly_skyfire m3u8 information
[vimeo] 756354595: Downloading fastly_skyfire m3u8 information
[vimeo] 756354595: Downloading akfire_interconnect_quic MPD information
[vimeo] 756354595: Downloading akfire_interconnect_quic MPD information
[vimeo] 756354595: Downloading fastly_skyfire MPD information
[vimeo] 756354595: Downloading fastly_skyfire MPD information
ERROR: requested format not available

**Comment by october262** [comment]
try youtube-dl -f best "https://vimeo.com/756354595"
the video will now download.

**Comment by dirkf** [comment]
OP must have some config that overrides the default `bestvideo+bestaudio/best:
```console
$ python -m youtube_dl --test --ignore-config -v 'https://vimeo.com/756354595'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--test', u'--ignore-config', u'-v', u'https://vimeo.com/756354595']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 64d6dd64c
[debug] Python version 2.7.18 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[vimeo] Extracting URL: https://vimeo.com/756354595
[vimeo] 756354595: Downloading webpage
[vimeo] 756354595: Downloading JSON metadata
[vimeo] 756354595: Downloading JSON metadata
[vimeo] 756354595: Checking Original video URL
[vimeo] 756354595: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 756354595: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 756354595: Downloading fastly_skyfire m3u8 information
[vimeo] 756354595: Downloading fastly_skyfire m3u8 information
[vimeo] 756354595: Downloading akfire_interconnect_quic MPD information
[vimeo] 756354595: Downloading akfire_interconnect_quic MPD information
[vimeo] 756354595: Downloading fastly_skyfire MPD information
[vimeo] 756354595: Downloading fastly_skyfire MPD information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1682293195-0xf3759ef7ba781f5e0c035b398d791a453e2925bf/c6400c54-74f5-468f-8460-b67e32b21045/sep/video/22fb4ba4,6daaa6e4,71fe6fa7,9b40e11e,9f8a0647,a5598d11,a58bde2c/audio/02edd914,20debfd0,f9d660fb/master.mpd?base64_init=1&query_string_ranges=1'
[dashsegments] Total fragments: 1
[download] Destination: We Are Antarctica-756354595.fdash-fastly_skyfire_sep-video-9f8a0647.mp4
[download] 100% of 834.00B in 00:00
[debug] Invoking downloader on u'https://skyfire.vimeocdn.com/1682293195-0xf3759ef7ba781f5e0c035b398d791a453e2925bf/c6400c54-74f5-468f-8460-b67e32b21045/sep/video/22fb4ba4,6daaa6e4,71fe6fa7,9b40e11e,9f8a0647,a5598d11,a58bde2c/audio/02edd914,20debfd0,f9d660fb/master.mpd?base64_init=1&query_string_ranges=1'
[dashsegments] Total fragments: 1
[download] Destination: We Are Antarctica-756354595.fdash-fastly_skyfire_sep-audio-02edd914.m4a
[download] 100% of 710.00B in 00:00
[ffmpeg] Merging formats into "We Are Antarctica-756354595.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:We Are Antarctica-756354595.fdash-fastly_skyfire_sep-video-9f8a0647.mp4' -i 'file:We Are Antarctica-756354595.fdash-fastly_skyfire_sep-audio-02edd914.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:We Are Antarctica-756354595.temp.mp4'
Deleting original file We Are Antarctica-756354595.fdash-fastly_skyfire_sep-video-9f8a0647.mp4 (pass -k to keep)
Deleting original file We Are Antarctica-756354595.fdash-fastly_skyfire_sep-audio-02edd914.m4a (pass -k to keep)
$
```
Some Vimeo URLs need fixes such as `Unable to extract info section`, all of which are included in the latest code, but this one works fine with the 2021.12 release.

**Comment by ProvisionlabTeam** [comment]
thx. indeed. i used this option "format": "bestvideo[height<=360][ext=mp4]+bestaudio[ext=m4a]/best[height<=360][ext=mp4]/best[ext=mp4]"

**Comment by ProvisionlabTeam** [comment]
@dirkf trying to fight with this Vimeo video still )
how to download the 480p video?
I see a lot of formats.
For example, this one suits me. 
'format_id': 'dash-fastly_skyfire_sep-video-9b40e11e', 'manifest_url': 'https://skyfire.vimeocdn.com/1682865096-0x6cc6c7b5a8429baad23a86b1d346f9d4d03fba53/c6400c54-74f5-468f-8460-b67e32b21045/sep/video/22fb4ba4,6daaa6e4,71fe6fa7,9b40e11e,9f8a0647,a5598d11,a58bde2c/audio/02edd914,20debfd0,f9d660fb/master.mpd?base64_init=1&query_string_ranges=1', 'ext': 'mp4', 'width': 960, 'height': 402, 'tbr': 1664.0, 'asr': None, 'fps': 25, 'language': None, 'format_note': 'DASH video', 'filesize': None, 'container': 'mp4_dash', 'vcodec': 'avc1.64001F', 'acodec': 'none', 'url': 'https://skyfire.vimeocdn.com/1682865096-0x6cc6c7b5a8429baad23a86b1d346f9d4d03fba53/c6400c54-74f5-468f-8460-b67e32b21045/sep/video/22fb4ba4,6daaa6e4,71fe6fa7,9b40e11e,9f8a0647,a5598d11,a58bde2c/audio/02edd914,20debfd0,f9d660fb/master.mpd?base64_init=1&query_string_ranges=1', 'fragment_base_url': 'https://skyfire.vimeocdn.com/1682865096-0x6cc6c7b5a8429baad23a86b1d346f9d4d03fba53/c6400c54-74f5-468f-8460-b67e32b21045/sep/video/22fb4ba4,6daaa6e4,71fe6fa7,9b40e11e,9f8a0647,a5598d11,a58bde2c/audio/02edd914,20debfd0,f9d660fb/../../../../../parcel/video/', 'fragments': [{'path': '9b40e11e.mp4?r=dXMtZWFzdDE%3D&range=0-833'}, {'path': '9b40e11e.mp4?r=dXMtZWFzdDE%3D&range=1814-147660', 'duration': 6.0}, {'path': '9b40e11e.mp4?r=dXMtZWFzdDE%3D&range=147661-603615', '................}

when I pass format id to format string see the same error

[vimeo] 756354595: Downloading fastly_skyfire MPD information
Selected format: dash-fastly_skyfire_sep-video-9b40e11e
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): vimeo.com:443
DEBUG:urllib3.connectionpool:https://vimeo.com:443 "GET /756354595 HTTP/1.1" 200 None
[vimeo] 756354595: Downloading webpage
[vimeo] 756354595: Downloading JSON metadata
[vimeo] 756354595: Downloading JSON metadata
[vimeo] 756354595: Checking Original video URL
[vimeo] 756354595: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 756354595: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 756354595: Downloading fastly_skyfire m3u8 information
[vimeo] 756354595: Downloading fastly_skyfire m3u8 information
[vimeo] 756354595: Downloading akfire_interconnect_quic MPD information
[vimeo] 756354595: Downloading akfire_interconnect_quic MPD information
[vimeo] 756354595: Downloading fastly_skyfire MPD information
[vimeo] 756354595: Downloading fastly_skyfire MPD information
ERROR: requested format not available
ERROR:root: Error-Skipping URL: ERROR: requested format not available
How to cope with it?

**Comment by dirkf** [comment]
If you're calling `urllib3` you're probably using yt-dlp. If so, post there.

Either way post the full failing verbose (`-v`) log (embedded in triple back-quotes for extra credit) so that people can see what actual command and options you're using.

**Comment by ProvisionlabTeam** [comment]
i use it with sample code below
```
import youtube_dl
.......

with youtube_dl.YoutubeDL() as ydl:
    info_dict = ydl.extract_info(url, download=False)
    formats = info_dict.get('formats', None)
    video_formats = [fmt for fmt in formats if fmt.get('vcodec', 'none') != 'none']
    video_formats.sort(key=lambda fmt: abs(fmt.get('height', 0) - 480))

selected_format = None
for fmt in video_formats:
    if fmt.get('height', 0) <= 480:
        selected_format = fmt['format_id']
        print(f"Selected format: {selected_format}")
    else:
        break
if not selected_format:
    selected_format = "best"

if "youtube.com" in url or "youtu.be" in url:
    options = {
        "format": f"bestvideo[format_id={selected_format}][ext=webm]+bestaudio[ext=webm]/best[ext=webm]",
        "outtmpl": f"{temp_subfolder}/%(title)s.%(ext)s",
        "writesubtitles": True,
        "subtitlesformat": "vtt",
        "writeautomaticsub": True,
        "postprocessors": [{
            'key': 'FFmpegSubtitlesConvertor',
            'format': 'vtt',
        }],
    }
elif "vimeo.com" in url:
    options = {
        "format": f"{selected_format}+bestaudio[ext=webm]/best[ext=webm]",
        "outtmpl": f"{temp_subfolder}/%(title)s.%(ext)s",
        "writesubtitles": True,
        "subtitlesformat": "vtt",
        "writeautomaticsub": False,
    }

    try:
        response = requests.get(url)
        if response.status_code == 200:
            try:
                with youtube_dl.YoutubeDL(options) as ydl:
                    ydl.download([url])
            except youtube_dl.utils.DownloadError as e:
                if 'ERROR: giving up after 0 retries' in e.args[0]:
                    logging.error(f'Error: {e.args[0]}')
                else:
                    logging.error(f'Error-Skipping URL: {e}')
```
In general this string works well for youtube "format": "bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]/best[height<=480][ext=mp4]/best[ext=mp4]"
But now work with vimeo.
 "format": "best" work for vimeo well. But I get file with 2GB. I don't need such quality.

**Comment by ProvisionlabTeam** [comment]
added "verbose":True,
```
[vimeo] 756354595: Downloading webpage
[vimeo] 756354595: Downloading JSON metadata
[vimeo] 756354595: Downloading JSON metadata
[vimeo] 756354595: Checking Original video URL
[vimeo] 756354595: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 756354595: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 756354595: Downloading fastly_skyfire m3u8 information
[vimeo] 756354595: Downloading fastly_skyfire m3u8 information
[vimeo] 756354595: Downloading akfire_interconnect_quic MPD information
[vimeo] 756354595: Downloading akfire_interconnect_quic MPD information
[vimeo] 756354595: Downloading fastly_skyfire MPD information
[vimeo] 756354595: Downloading fastly_skyfire MPD information
Selected format: hls-akfire_interconnect_quic-1004
Selected format: hls-fastly_skyfire-1004
Selected format: hls-akfire_interconnect_quic_sep-1195
Selected format: hls-fastly_skyfire_sep-1195
Selected format: dash-akfire_interconnect_quic-video-9b40e11e
Selected format: dash-akfire_interconnect_quic_sep-video-9b40e11e
Selected format: dash-fastly_skyfire-video-9b40e11e
Selected format: dash-fastly_skyfire_sep-video-9b40e11e
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): vimeo.com:443
DEBUG:urllib3.connectionpool:https://vimeo.com:443 "GET /756354595 HTTP/1.1" 200 None
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 3d6e19f
[debug] Python version 3.9.10 (CPython) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 2023-01-12-git-fc263f073e-essentials_build-www.gyan.dev, ffprobe 2023-01-12-git-fc263f073e-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[vimeo] 756354595: Downloading webpage
[vimeo] 756354595: Downloading JSON metadata
[vimeo] 756354595: Downloading JSON metadata
[vimeo] 756354595: Checking Original video URL
[vimeo] 756354595: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 756354595: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 756354595: Downloading fastly_skyfire m3u8 information
[vimeo] 756354595: Downloading fastly_skyfire m3u8 information
[vimeo] 756354595: Downloading akfire_interconnect_quic MPD information
[vimeo] 756354595: Downloading akfire_interconnect_quic MPD information
[vimeo] 756354595: Downloading fastly_skyfire MPD information
[vimeo] 756354595: Downloading fastly_skyfire MPD information
ERROR: requested format not available
Traceback (most recent call last):
  File "D:\Python38\venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Python38\venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "D:\Python38\venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "D:\Python38\venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 1683, in process_video_result
    raise ExtractorError('requested format not available',
youtube_dl.utils.ExtractorError: requested format not available
```

**Comment by dirkf** [comment]
You're asking for a DASH format that will be delivered in a MP4 container but requiring a WebM container (`[ext=webm]`). So the format is not available.

Use `--recode-video ...` if that's what you want: in this case, the API equivalent
```console
$ python3.9 devscripts/cli_to_api.py --recode-video webm
{'postprocessors': [{'key': 'FFmpegVideoConvertor', 'preferedformat': 'webm'}]}
$
```

**Comment by ProvisionlabTeam** [comment]
ah. really. why am i forgot for mp4)))
used this "format": "bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]"
works well
thx @dirkf
