### ISSUE TITLE
It has been MONTHS that I couldn't download anything. Fix updater and website.

### ISSUE THREAD

**Issue by rendarz** [ytdl-org/youtube-dl#32096]
I have just installed youtube-dl with:

`sudo curl -L https://yt-dl.org/latest/youtube-dl -o /usr/bin/youtube-dl`

Then, trying to download something with:

`/usr/bin/youtube-dl --verbose --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=RWn37kykoa8`

I get the error:

$  /usr/bin/youtube-dl --verbose --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=RWn37kykoa8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--extract-audio', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=BhU4ylPsNbE']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-21-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] BhU4ylPsNbE: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

NOTE: I HAVE JUST DOWNLOADED A FRESH VERSION DIRECTLY INTO /usr/bin/youtube-dl with curl, so I can't get why it shouldn't work, why running an update with `youtube-dl -U
youtube-dl is up-to-date (2021.12.17)`

doesn't work either, since it gives you an older version.

That's enough! It has been months by now that I couldn't use youtube-dl.
Please fix the website that is used with curl, and the updater tool to get a newer and fixed version.

## Checklist

- [x] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Search for your error using #30839 as requested to find a solution, if not the one you want.
