### ISSUE TITLE
I'm unable to download youtube videos

### ISSUE THREAD

**Issue by HaRsHiNnIv** [ytdl-org/youtube-dl#32092]
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
---------------------------------------------------------------------------
RegexNotFoundError                        Traceback (most recent call last)
[/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py](https://localhost:8080/#) in wrapper(self, *args, **kwargs)
    814             try:
--> 815                 return func(self, *args, **kwargs)
    816             except GeoRestrictedError as e:

14 frames
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

DownloadError                             Traceback (most recent call last)
DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
[/usr/local/lib/python3.9/dist-packages/pafy/backend_youtube_dl.py](https://localhost:8080/#) in _fetch_basic(self)
     41             # Turn into an IOError since that is what pafy previously raised
     42             except youtube_dl.utils.DownloadError as e:
---> 43                 raise IOError(str(e).replace('YouTube said', 'Youtube says'))
     44 
     45         if self.callback:

OSError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

How to resolve this issue?

**Comment by NoMedia-py** [comment]
Same problem, just an different error message:

C:\WINDOWS\system32>youtube-dl -x --audio-format mp3 https://www.youtube.com/watch?v=C_RGm64Dv6w --verbose              [debug] System config: []                                                                                               [debug] User config: []                                                                                                 [debug] Custom config: []                                                                                               [debug] Command-line args: ['-x', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=C_RGm64Dv6w', '--verbose']  [debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252                                                      [debug] youtube-dl version 2021.12.17                                                                                   [debug] Python version 3.9.10 (CPython) - Windows-10-10.0.19045-SP0                                                     [debug] exe versions: ffmpeg 2022-03-28-git-5ee198f9aa-full_build-www.gyan.dev, ffprobe 2022-03-28-git-5ee198f9aa-full_build-www.gyan.dev                                                                                                       [debug] Proxy map: {}                                                                                                   [youtube] C_RGm64Dv6w: Downloading webpage                                                                              ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.                                                                                              Traceback (most recent call last):                                                                                        File "C:\Users\woelf\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper                                                                                                                      return func(self, *args, **kwargs)                                                                                    File "C:\Users\woelf\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info                                                                                                               ie_result = ie.extract(url)                                                                                           File "C:\Users\woelf\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract                                                                                                               ie_result = self._real_extract(url)                                                                                   File "C:\Users\woelf\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract                                                                                                       'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,                                                                                                          File "C:\Users\woelf\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex                                                                                                        raise RegexNotFoundError('Unable to extract %s' % _name)                                                            youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Resolve it by reading and following #30839 as requested to find the issue that already solves this problem; then by following one of the update procedures recommended there.
