### ISSUE TITLE
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by ct1104** [ytdl-org/youtube-dl#32108]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id;

**Comment by ct1104** [comment]
url： https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by jalbarracinv** [comment]
Same error :(

DownloadError                             Traceback (most recent call last)
[/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py](https://localhost:8080/#) in trouble(self, message, tb)
    596             else:
    597                 exc_info = sys.exc_info()
--> 598             raise DownloadError(message, exc_info)
    599         self._download_retcode = 1
    600 

DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
#30839 ! Use the checklist !

**Comment by ct1104** [comment]
> Same error :(
> 
> DownloadError Traceback (most recent call last) [/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py](https://localhost:8080/#) in trouble(self, message, tb) 596 else: 597 exc_info = sys.exc_info() --> 598 raise DownloadError(message, exc_info) 599 self._download_retcode = 1 600
> 
> DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

see: https://github.com/yt-dlp/yt-dlp

**Comment by ct1104** [comment]
> ![image](https://user-images.githubusercontent.com/64592521/234862704-e94d1434-2a10-46dc-82aa-bbfb3c8c2c7f.png) same error.

https://github.com/yt-dlp/yt-dlp

**Comment by ct1104** [comment]
sorry for poor issue description, the sulotion was found in https://github.com/yt-dlp/yt-dlp, thanks @dirkf
