### ISSUE TITLE
Error: Unable to Extract uploader id

### ISSUE THREAD

**Issue by Lewowo** [ytdl-org/youtube-dl#32103]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

I got this error code from a Discord Music Bot. I already did all the things it says i should do and so i thougt im gonna ask here if someone could help me:

ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Python39\lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

The Code is here:

`import discord
import os
import asyncio
import youtube_dl

Discord_Token = "X"

intents = discord.Intents.default()
intents.message_content = True
intents.members = True

client = discord.Client(intents=intents)

voice_clients = {}

yt_dl_opts = {'format': 'bestaudio/best', 'verbose': True}
ytdl = youtube_dl.YoutubeDL(yt_dl_opts)

ffmpeg_options = {'options': "-vn"}

@client.event
async def on_ready():
    print(f"Bot logged in as {client.user}")

@client.event
async def on_message(msg):
    if msg.author != client.user:
        if msg.content.lower().startswith("!hi"):
            await msg.channel.send(f"Hi, {msg.author.display_name}")

    if msg.content.startswith("-play"):
        try:
            url = msg.content.split()[1]

            voice_client = await msg.author.voice.channel.connect()
            voice_clients[voice_client.guild.id] = voice_client

            loop = asyncio.get_event_loop()
            data = await loop.run_in_executor(None, lambda: ytdl.extract_info(url, download=False))

            song = data['url']
            voice_client.play(discord.FFmpegPCMAudio(song, **ffmpeg_options))
        except Exception as err:
            print(err)

    if msg.content.startswith("-pause"):
        try:
            voice_client = voice_clients[msg.guild.id]
            if voice_client.is_playing():
                voice_client.pause()
        except Exception as err:
            print(err)    

    if msg.content.startswith("-stop"):
        try:
            voice_client = voice_clients[msg.guild.id]
            if voice_client.is_playing():
                voice_client.stop()
                del voice_clients[msg.guild.id]
                await voice_client.disconnect()
        except Exception as err:
            print(err)  

    if msg.content.startswith("-queue"):
        try:
            # Implement queue functionality here
            pass

        except Exception as err:
            print(err)  

    if msg.content.startswith("-np"):
        try:
            voice_client = voice_clients[msg.guild.id]
            if voice_client.is_playing():
                current_song = voice_client.source.title
                await msg.channel.send(f"Currently playing: {current_song}")
        except Exception as err:
            print(err)

client.run(Discord_Token)
`

**Comment by DavraYoung** [comment]
Same issue here
youtube-dl --no-continue -f bestvideo[height<=720][fps=30]+bestaudio/best[height<=720] -o ./public/videos/1.mp4 --merge-output-format mp4 https://www.youtube.com/watch?v=4pQPtOJn38k

Video links:
https://www.youtube.com/watch?v=4pQPtOJn38k
https://www.youtube.com/watch?v=vZ6I13Hjv30

**Comment by hmorris94** [comment]
Same here:
```
> youtube-dl --verbose https://www.youtube.com/watch?v=YPrs3DqraWM

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=YPrs3DqraWM']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.0 (CPython) - Windows-10-10.0.22621-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] YPrs3DqraWM: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\hunte\AppData\Roaming\Python\Python311\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\AppData\Roaming\Python\Python311\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\hunte\AppData\Roaming\Python\Python311\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\AppData\Roaming\Python\Python311\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\AppData\Roaming\Python\Python311\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
>... I already did all the things it says i should do ....

Try again, try better: #30839.
