### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by SardarML** [ytdl-org/youtube-dl#32111]
## Checklist

- [x] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by eduardochaves1** [comment]
I'm having same issue.

**Comment by NilsDeWinter** [comment]
Same here

**Comment by SardarML** [comment]
watch this:

https://www.youtube.com/watch?v=tMtszkwxo48

I solved it with him! :)

**Comment by dirkf** [comment]
#30839 ! Use the checklist!
