### ISSUE TITLE
It seems that youtube-dl is unable to extract information

### ISSUE THREAD

**Issue by Kiri2003** [ytdl-org/youtube-dl#32114]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

 youtube-dl --verbose https://yt-dl.org/bug
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://yt-dl.org/bug']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.8 (CPython) - Linux-5.15.0-1032-gcp-x86_64-with-glibc2.35
[debug] exe versions: none
[debug] Proxy map: {}
[generic] bug: Requesting header
[redirect] Following redirect to https://github.com/ytdl-org/youtube-dl/issues
[generic] issues: Requesting header
WARNING: Falling back on generic information extractor.
[generic] issues: Downloading webpage
[generic] issues: Extracting information
ERROR: Unsupported URL: https://github.com/ytdl-org/youtube-dl/issues
Traceback (most recent call last):
  File "/home/runner/ShinyEachConferences/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/runner/ShinyEachConferences/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/runner/ShinyEachConferences/venv/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/runner/ShinyEachConferences/venv/lib/python3.10/site-packages/youtube_dl/extractor/generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://github.com/ytdl-org/youtube-dl/issues
How fix it?

**Comment by dirkf** [comment]
>[x] I've checked that all provided URLs are alive and playable in a browser

Obviously not. What video did you see in the bug tracker? Read #30839 again to see if the actual error you were trying to report was already reported and/or solved.
