### ISSUE TITLE
Fedora 36+ error, for some reason since ver 36. I can not use the plug in anymore. I tried updating, it did not work

### ISSUE THREAD

**Issue by abc1260** [ytdl-org/youtube-dl#32117]
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
#30839 !
