### ISSUE TITLE
Giving error on yt videos

### ISSUE THREAD

**Issue by ridoysheikh** [ytdl-org/youtube-dl#32116]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
#32111

**Comment by dirkf** [comment]
You've found a duplicate issue and opened another duplicate. Basically this is spam. Follow #30839.
