### ISSUE TITLE
Title Extraction error 

### ISSUE THREAD

**Issue by moiseyo** [ytdl-org/youtube-dl#32118]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

Python 3.10.10
```
PASTE VERBOSE LOG HERE
```
Input URL ::https://www.youtube.com/watch?v=5vIZ0kOpWvw
Error:ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
DownloadError('ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')

## Description
Error:ERROR: Unable to extract uploader id;

Code:

roxy=''
    ydl_opts = {}
    ydl_opts['proxy']= proxy
    ydl_opts['outtmpl'] = '%s/%%(title)s.%%(ext)s  ' % (out_dir)
    ydl_opts['logger'] = MyLogger()
    ydl_opts['progress_hooks'] = [my_hook]
    ydl_opts['format'] = 'best[ext=mp4]/best[ext=avi]'
    ul, id = getYouTubeUrl(url)
    # id = ''
    # if m:
    #    id = u = m.group(1)

    ydl = youtube_dl.YoutubeDL(ydl_opts)

    # Add all the available extractors
    ydl.add_default_info_extractors()
    try:
        result = ydl.extract_info(url, download=False)  # We just want to extract the info
    except  (Exception) as err:
        print( repr(err))
        return None

**Comment by dirkf** [comment]
Read and follow #30839. Use the checklist.
