### ISSUE TITLE
ERROR: Unable to extract uploader id - youtube-dl is up-to-date (2021.12.17)

### ISSUE THREAD

**Issue by franferri** [ytdl-org/youtube-dl#32121]
# /usr/local/bin/youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

# /usr/local/bin/youtube-dl -F https://www.youtube.com/watch\?v\=yVMy5_2dj6k --verbose 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.youtube.com/watch?v=yVMy5_2dj6k', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.1 (CPython) - macOS-13.3.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1, ffprobe 5.1
[debug] Proxy map: {}
[youtube] yVMy5_2dj6k: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by timursyrma** [comment]
Hello! 
You need replace 1794 line in /usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py to 
```
            'uploader_id': self._search_regex(r'/(?:channel/|user/|@)([^/?&#]+)', owner_profile_url, 'uploader id', default=None),

```
Solution here: https://www.youtube.com/watch?v=tMtszkwxo48

**Comment by rodrigo1406** [comment]
Why is there no new version for more than a year? The project was abandoned?

**Comment by MdKaif2782** [comment]
I have the similar error on my windows 10 pc .. Can't locate the file to edit it

**Comment by dirkf** [comment]
#30839 !
