### ISSUE TITLE
Is there a version with gui?

### ISSUE THREAD

**Issue by ShantanuTonde** [ytdl-org/youtube-dl#32120]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

A reddt post had a comment indicating that youtube-dl has a gui version. Is it genuine?
Link: https://mrs0m30n3.github.io/youtube-dl-gui/

**Comment by dirkf** [comment]
That's the link I would have pointed you to. I have no experience of these programs, other than people who report yt-dl issues from them.

**Comment by dirkf** [comment]
Sorry, I meant this: https://old.reddit.com/r/youtubedl/wiki/info-guis.
