### ISSUE TITLE
Does this combine downloaded video and audio?

### ISSUE THREAD

**Issue by nonopolarity** [ytdl-org/youtube-dl#32128]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Often the 1080 video and the audio files need to be downloaded separately as 2 files. Does the program combine them into one single .mp4 file?  I couldn't find the answer when searching for "combine" in the README or the website.

**Comment by dirkf** [comment]
Yes, but only if _ffmpeg_ is available to do the combining. The program uses the word "merge".

You can ask for a single combined format but some sites don't have one, or only in a lower quality. Read "FORMAT SELECTION" in the Manual.
