### ISSUE TITLE
youtube-dl Unable to extract uploader id

### ISSUE THREAD

**Issue by jafiune** [ytdl-org/youtube-dl#32126]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

youtube-dl output:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=vO8XQD6mHNg', '2']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-71-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] vO8XQD6mHNg: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jafiune** [comment]
youtube-dl version 2012.12.17 is broken on lubutu

**Comment by irdaislakhuafa** [comment]
same 

> youtube-dl version 2012.12.17 is broken on lubutu

same problem with me, i use youtube-dl version 2021.12.17, below is the error message
```text
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
i use artix linux 
![image](https://user-images.githubusercontent.com/65246900/235372098-f3b482be-a8a5-4e60-95a9-085d6002b082.png)

**Comment by tonit** [comment]
Same on Mac: 2021.12.17

**Comment by dirkf** [comment]
#30839 ! Use the checklist!

**Comment by raulcv** [comment]
The same error on MacOS `ventura 13.3.1 with M1 chip`: **youtube-dl version 2021.12.17**

**Comment by RootlessAgrarian** [comment]
same here, Mac Catalina, even trying to extract audio with -x results in same error msg, can't DL audio

**Comment by dirkf** [comment]
@RootlessAgrarian, just read and follow the [pinned issue](https://github.com/ytdl-org/youtube-dl/issues/30839) to find your solution.

The checklist is what the dunce who opened this issue failed to follow, perhaps because of **not reading** that issue properly: look at the top of this issue to see the empty checkboxes.

These in particular should have caused the issue to be abandoned, even if the poster had failed to see that the problem was mentioned in the pinned issue:
>[ ] I've searched the bugtracker for similar bug reports including closed ones
>[ ] I've read bugs section in FAQ

**Comment by tonit** [comment]
I still don't get it. Is this a duplicate (then link it here) or is this not a bug and youtube-dl does not support YouTube anymore? Or is this purely about the initial ticket creator not ticking all the boxes? Please clarify, I am happy to file a new ticket if that's how it is supposed to work.

**Comment by tonit** [comment]
Ok, what @dirkf is trying to say: it is a duplicate and most info about the situation is here: https://github.com/ytdl-org/youtube-dl/issues/31530#Description

**Comment by dirkf** [comment]
The hint is in the **label** and here 
>... even if the poster had failed to see that **the problem was mentioned in the pinned issue** ...
