### ISSUE TITLE
Unable to extract uploader id, YT v=DclRzwoGV-I

### ISSUE THREAD

**Issue by DocNielsen** [ytdl-org/youtube-dl#32137]
## Checklist
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ
## Verbose log
$ youtube-dl --verbose "https://www.youtube.com/watch?v=DclRzwoGV-I"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=DclRzwoGV-I']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.18.0-2-amd64-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg N-109043-ga7ccfdc0d7-docnielsen, ffprobe N-109043-ga7ccfdc0d7-docnielsen, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] DclRzwoGV-I: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/doc/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/doc/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/doc/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/doc/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/doc/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```


## Description


Just wanted to download a video, and now i broke stuff... sorry
I dont know enough about this to give a better description or offer a possible solution.

But thanks for being more awesome than me :)

Morten

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar bug reports including closed ones

Here, and/or by reading #30839 properly, you should find your answer.
