### ISSUE TITLE
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id => Unable to use youtube-dl after upgrading to windows 11

### ISSUE THREAD

**Issue by Aqueuse** [ytdl-org/youtube-dl#32130]
## Checklist

- [ X ] I'm reporting a broken site support issue
- [ X ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ X ] I've checked that all provided URLs are alive and playable in a browser
- [ X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X ] I've searched the bugtracker for similar bug reports including closed ones
- [ X ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=aB5WQkLZ9iU']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] aB5WQkLZ9iU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hello, I tried to download a video with this command :  
youtube-dl.exe --verbose "https://www.youtube.com/watch?v=aB5WQkLZ9iU"

It worked well before. I have update to windows 11 recently and it's my first use in this os.

**Comment by Aqueuse** [comment]
(error persist after reinstalling python 3.4.4 from the microsoft store)

**Comment by LeontKing2** [comment]
Same Issue Here.

**Comment by LeontKing2** [comment]
Youtube-dl wont update the github version on site for idk reasons

**Comment by firesofmay** [comment]
youtube-dl -f 22 "https://www.youtube.com/watch?v=t2VWglF0sP0&ab_channel=ShreyasDoshi" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '22', 'https://www.youtube.com/watch?v=t2VWglF0sP0&ab_channel=ShreyasDoshi', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.6 (CPython) - macOS-13.3.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] t2VWglF0sP0: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/mayank/Library/Python/3.9/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/mayank/Library/Python/3.9/lib/python/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/mayank/Library/Python/3.9/lib/python/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Users/mayank/Library/Python/3.9/lib/python/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/Users/mayank/Library/Python/3.9/lib/python/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ColinPitrat** [comment]
Same issue here. Using the version from github worked.

**Comment by Aqueuse** [comment]
@dirkf my issue was incomplete ? Nevertheless I have tried to give you all the informations and I have follow the guideline as better as I possibly could. What information is lacking ? Also, you have mark this as closed so what can I do to solve the problem from my side ? Because it still don't work.

**Comment by dirkf** [comment]
Because they're not.

>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839 (**again**?).

>[x] I've read bugs section in FAQ

Apply this.

Generally, don't guess.
