### ISSUE TITLE
Release a new version to inform users about known bugs and prevent duplicate issue reports

### ISSUE THREAD

**Issue by Semnodime** [ytdl-org/youtube-dl#32144]
## Checklist
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description
Maybe create a section in the README with current bugs and other issues which receive too many duplicates.
OR
Release a new youtube-dl version (each time a bug is introduced by a change in youtube's API) with a specific exception handler for the bug while it is not yet fixed to let the user know where they can learn about the issue, that it is nothing they need to report, and that it is worked on….

Related: #32143

**Comment by dirkf** [comment]
See #31585. All the necessary information about current bugs and bug reporting procedures is in #30839 which users must read and apply before opening an issue.

**Comment by bitplane** [comment]
To add to this - I installed the latest version from `pip` and it failed to download `https://www.youtube.com/watch?v=laZusNy8QiY` with a regex extraction error, but latest master works fine. So at least for me, tagging a release would fix things.
