### ISSUE TITLE
How can I use the InfoExtractor class on a url with python?

### ISSUE THREAD

**Issue by RicardFos** [ytdl-org/youtube-dl#32151]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, I'm using youtube-dl in my python scripts, and I'd like to be able to retrieve the information from a video url that the InfoExtractor get internally when downloading a video. I can use the outtmpl parameter to tell the downloader to save certain info from the video in the name (title, id, fps, extension...) like this:

```
ydl_opts = {
    'format': 'bestvideo/best',
    'outtmpl': 'datasets/Test_ffmpeg/download_youtube/%(id)s_%(fps)sfps.%(ext)s',
    'ignore-errors': True
}
try:
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download([f'https://www.youtube.com/watch?v={videoid}'])

except Exception as error:
    print('Error: ', error)
```

But I'd like to retrieve the full dictionary itself.

I've been trying to call InfoExtractor directly but I'm retrieving null results. Any help will be apreciated.

```
extractor = InfoExtractor(ydl)
extracted = extractor.extract(url='https://www.youtube.com/watch?v=LAfk4M0nC3M')
```

**Comment by dirkf** [comment]
One way is to emulate this CLI command:
```console
python -m youtube_dl --dump-single-json 'https://www.youtube.com/watch?v=LAfk4M0nC3M'
```
That corresponds to these options with your script as shown:
```console
$ python3.9 ./devscripts/cli_to_api.py --dump-single-json
{'dump_single_json': True, 'quiet': True, 'simulate': True}
$  
```
You can look at the code of the `download()` method in `YoutubeDL.py` to find that it calls the public `extract_info()` method. So you could also rewrite your script to use that instead:
```py
    def extract_info(self, url, download=True, ie_key=None, extra_info={},
                     process=True, force_generic_extractor=False):
        """
        Return a list with a dictionary for each video extracted.

        Arguments:
        url -- URL to extract

        Keyword arguments:
        download -- whether to download videos during extraction
        ie_key -- extractor key hint
        extra_info -- dictionary containing the extra values to add to each result
        process -- whether to resolve all unresolved references (URLs, playlist items),
            must be True for download to work.
        force_generic_extractor -- force using the generic extractor
        """
```
This returns the raw info rather than the sanitised data in the first solution.

**Comment by dirkf** [comment]
For clarification, `InfoExtractor` is an abstract class.

Inside `YoutubeDL.extract_info()`, the program selects a concrete subclass of `InfoExtractor` suitable for the target URL (eg, `YoutubeIE`), instantiates it, and runs its `extract()` method, calling the `_real_extract()` method of the instance to return the info dict.

**Comment by RicardFos** [comment]
Thanks, I finally used the  extract_info and list_formats methods from the downloader class and it did what I wanted, I was mistaken by using the InfoExtractor class separately.
