### ISSUE TITLE
Youtube direct downloadable link

### ISSUE THREAD

**Issue by muhy06** [ytdl-org/youtube-dl#32150]
Is there a way to get a downloadable link, instead of getting it to play on browsers for youtube ? right now when we open link on browser, it will play. I would like to get a link, which downloads directly.

**Comment by dirkf** [comment]
As documented in the Fine Manual:
`--get-url` (or `-g`)

1. With YouTube, the URL(s) returned expire quite quickly, so your workflow must act on them soon and not (eg) stash them in a queue to be downloaded tomorrow.
2. For a single link that plays both audio and video, use `--format best` (or similar), but not all sites offer such links.
3. If you want both audio and video and the site doesn't offer a combined format with audio and video, or the quality of the best combined format isn't good enough for you, yt-dl can list (eg, with the default format option) the separate audio and video links: you'll have to download them and then merge them into a single AV container with a separate tool (eg _ffmpeg_).
4. If downloading a YT link, the download can be throttled unless you specify an acceptable HTTP chunk size (10MB) for the downloader.
5. The formats offered by a site may change over time (though for YT, point 1 generally overrides this): running yt-dl again ensures that the media link(s) are the best available matching your format specification.

Also read "FORMAT SELECTION" in the Manual.
