### ISSUE TITLE
When I run the .exe, the command line window opens and promptly closes itself

### ISSUE THREAD

**Issue by caseyroberson** [ytdl-org/youtube-dl#32157]
I'm a complete newbie on GitHub things. And it's been years since I've done any command line stuff. I'm on a PC with Windows 7. I downloaded youtube-dl just about a half hour ago today.

**Comment by dirkf** [comment]
Duplicate of [#1995](https://github.com/ytdl-org/youtube-dl/issues/1995#issuecomment-30741689).
