### ISSUE TITLE
Error downloading video: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output..

### ISSUE THREAD

**Issue by ilustraCode** [ytdl-org/youtube-dl#32167]
I'm trying to use in my code PHP, but this return the follow errors:
Error downloading video: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output..

I've updated youtube-dl.exe, but it doesn't work, even executing by CMD.

→ youtube-dl.exe --verbose [URL video] 

When execute [ youtube-dl.exe -U ] return ERROR: can't find the current version. Please try again later.

**Comment by PhilippKilian** [comment]
@ilustraCode if you are using youtube-dl version 2021.12.17, then it's regex check is too old to find then `uploader_id`. 

For a dirty fix, edit `youtube_dl/extractor/youtube.py` line 1794 from 

```python
'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
```

to

```python
'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id', fatal=False) if owner_profile_url else None,
```
Otherwise compile/clone the last version from the github Repo.

**Comment by dirkf** [comment]
#30839 !
