### ISSUE TITLE
unable to extract

### ISSUE THREAD

**Issue by deepgray** [ytdl-org/youtube-dl#32168]
ex0atmospheric@Dad-Mac-Pro Space % /usr/local/bin/youtube-dl -v https://www.youtube.com/@usafaastronauticsspaceops4372/videos
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/@usafaastronauticsspaceops4372/videos']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - macOS-12.6.5-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] @usafaastronauticsspaceops4372: Downloading webpage
[download] Downloading playlist: USAFA Astronautics & Space Ops - Videos
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] playlist USAFA Astronautics & Space Ops - Videos: Downloading 68 videos
[download] Downloading video 1 of 68
[youtube] QPGJLryfNVo: Downloading webpage
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://rr3---sn-8xgp1vo-p5qe7.googlevideo.com/videoplayback?expire=1683658115&ei=I0FaZIbzMcWa8wSElKuADQ&ip=96.231.151.201&id=o-AFj5A-p4y73JI3yxUvm4-b3SnNiyF4ohFwUizq4PW8GU&itag=22&source=youtube&requiressl=yes&mh=72&mm=31%2C29&mn=sn-8xgp1vo-p5qe7%2Csn-p5qlsndd&ms=au%2Crdu&mv=m&mvi=3&pl=18&initcwndbps=1823750&vprv=1&svpuc=1&mime=video%2Fmp4&ns=8uLYmAtwJ60p0VwYtwnLTY0N&cnr=14&ratebypass=yes&dur=1894.655&lmt=1677380755307490&mt=1683636085&fvip=3&fexp=24007246&c=WEB&txp=6218224&n=DmUD4NH-lWt45V7Zk6c&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAP52Lcv1gw_GV4yKiNpOsc4Z3YtO4HlqaXddSnrs2-0DAiAeFRKuRSjUSv4DUfaKEX3wVsDHyoWHVRfZmOm4-1JEDA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgaWhbh-6l6y5yBbi8aEAnM6VYFZlCc7pHGcwxdwcp3bwCIQDaHM3BdP9rAIBVP8okKBeSZZ-k0YHPOVAMn1P2JMmh_Q%3D%3D'
[download] Resuming download at byte 6322314
[download] Destination: LSN 12 - Remote Sensing (extended cut)-QPGJLryfNVo.mp4
[download]   7.8% of 94.03MiB at 80.55KiB/s ETA 18:21

**Comment by dirkf** [comment]
Study #30839 to find the issue that explains why you are getting this `WARNING`, which only affects the metadata, not the video itself.
