### ISSUE TITLE
Latest EXE Download version

### ISSUE THREAD

**Issue by peternewell** [ytdl-org/youtube-dl#32179]
## Checklist

- [x ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

I am having trouble downloading from SBS, and I wanted to make sure that I have the latest version. I operate on Windows, and the latest version available for the EXE filke seems to be 17-12-2021.

Is there a later version available and where do I download it from?

Thanks

**Comment by peternewell** [comment]
Thanks for your response.

So there appears to be an updated sbs.py file, how do I update the Windows version with it?

**Comment by dirkf** [comment]
With difficulty. If you have Python installed, you can run the PR code, but trying to update the Windows bundled .exe is not straightforward even if you understand the relevant technicalities. In particular, the PR code expects newer core code, so you'd have to start from an unofficial nightly build as recommended  in https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611.

A [similar extractor update](https://github.com/yt-dlp/yt-dlp/pull/6839) has been merged in yt-dlp and would be available using a nightly build there.

**Comment by peternewell** [comment]
>In particular, the PR code expects newer core code, so you'd have to start from an unofficial nightly build as recommended in [#31530 (comment)](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611).
> 

I have python installed on my windows computer and I have downloaded the code in the repository (master branch). I have run it  and it still shows a update date of 17-12-2021. This version still has the SBS issue in it.

Where do I find the most recent code?

**Comment by dirkf** [comment]
The modified code is in the PR: https://github.com/ytdl-org/youtube-dl/pull/31880/files.

You can just replace the `extractor/sbs.py` in your downloaded code with the one in the PR (download the `Raw` text from `View File`).

Please post any comments on the PR functionality there.

**Comment by peternewell** [comment]
All seems to be working now.

Thanks for your help.

**Comment by dirkf** [comment]
I'll close the issue, then.

**Comment by Spin35** [comment]
Can I get a copy of the .exe with the SBS fix in it?  I don't have the skills/knowledge to build one myself.
