### ISSUE TITLE
I've tried to download a video from YouTube but i unable to download.

### ISSUE THREAD

**Issue by Biswajitboym416** [ytdl-org/youtube-dl#32173]
I gived command youtube-dl https://youtu.be/l_-oqiR3g3I

I'm getting this error:- 
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thank you.

**Comment by dirkf** [comment]
#30839 !
