### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AstraFRR** [ytdl-org/youtube-dl#32177]
An error occurred: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I dont know what to do

**Comment by AgusP2023** [comment]
Me too. I tried many things, but nothing happens. 

Thank you.

**Comment by dirkf** [comment]
Why not **actually read the [pinned issue](https://github.com/ytdl-org/youtube-dl/issues/30839)**, find the issue that deals with your problem, and apply your preferred fix?
