### ISSUE TITLE
Youtube-dl unable to download youtube videos.

### ISSUE THREAD

**Issue by jkimonyi** [ytdl-org/youtube-dl#32197]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Youtube-dl unable to download youtube videos.
C:\Users\user\Downloads\youtube-dl>youtube-dl -U
youtube-dl is up-to-date (2021.12.17)
ERROR: Unable to extract uploader id

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar bug reports including closed ones
Learn how by reading #30839 (**again**?).

>{x] I've read bugs section in FAQ

Apply this.
