### ISSUE TITLE
Aspect ratio

### ISSUE THREAD

**Issue by doublex** [ytdl-org/youtube-dl#322]
Hello,
Is there a chance to get the aspect ratio?
Youtube display this video 16:9, but it has 600x480 pixels.
Thanks
Markus

**Comment by NatalieStrong** [comment]
here are some samples : 
https://www.youtube.com/watch?v=SlLqssayizs
https://www.youtube.com/watch?v=tt44pKSHNZk
https://www.youtube.com/watch?v=R3ZbcrdFkpw
These videos have 16:9 ratio this is making the video lose quality

**Comment by remitamine** [comment]
youtube-dl downloads what the websites are serving, if someone wants to change the aspect ratio of the videos he can post-process the video.
