### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by AvinashPrajapati** [ytdl-org/youtube-dl#32207]
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by AvinashPrajapati** [comment]
well , i am new to this filed of fetch and download...

**Comment by dirkf** [comment]
Please review #30839 to find the issue where your problem is addressed.
