### ISSUE TITLE
youtube-dl

### ISSUE THREAD

**Issue by Elpsico2** [ytdl-org/youtube-dl#32200]
VERIFICACION:
-La libreria de youtube-dl esta en su ultima version.
-Lo he intentado con varios varios videos 

EL ERROR QUE ME GENERA:

ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

CODIGO:

def run_assistant():
    while True:
        command = listen()
        if 'reproduce' in command and 'youtube' in command:
            video = command.replace('reproduce', '').replace('youtube', '').strip()
            print("Buscando video en YouTube:", video)
            talk("Buscando video en YouTube: " + video)
            try:
                # Realizar la búsqueda en YouTube
                ydl = youtube_dl.YoutubeDL({'format': 'best'})
                with ydl:
                    result = ydl.extract_info("ytsearch:" + video, download=False)
                    if 'entries' in result:
                        url = result['entries'][0]['webpage_url']
                        # Descargar el video de YouTube
                        file_path = './videos'
                        download_video(url, file_path)
                        # Reproducir el video descargado
                        print("Reproduciendo video:", video)
                        talk("Reproduciendo video: " + video)
                        play_video(file_path)
                    else:
                        print("No se encontraron resultados en YouTube para:", video)
                        talk("No se encontraron resultados en YouTube para: " + video)
            except Exception as e:
                print("Error al buscar y reproducir el video:", str(e))
                talk("Ocurrió un error al buscar y reproducir el video")
        elif 'detente' in command or 'para' in command:
            print("Deteniendo reproducción")
            talk("Deteniendo reproducción")
            stop_video()
        elif 'salir' in command:
            print("Saliendo del asistente")
            talk("Hasta luego")
            break

if __name__ == '__main__':
    run_assistant()

Porfavor ayuada con el error que me esta generando el codigo

**Comment by nicolaasjan** [comment]
> ERROR: Unable to extract uploader id

Already reported: #31530

Also read:
#30839
