### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by RiversideYao** [ytdl-org/youtube-dl#32215]
ERROR: Unable to extract uploader id

**Comment by RiversideYao** [comment]
outube-dl --no-check-certificate 'https://www.youtube.com/watch?v=b76ZP4u09WE'
[youtube] b76ZP4u09WE: Downloading webpage
[youtube] b76ZP4u09WE: Downloading player e50626d8
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by alexeybrod** [comment]
Same for me

**Comment by AlwaysBeCalm** [comment]
I used the release of [this](https://github.com/ytdl-patched/youtube-dl) fork
and it's working, I can download videos and playlists.

**Comment by Shad0X** [comment]
I'm also getting the "Unable to extract uploader id" on the fork you linked to @AlwaysBeCalm 😅

**Comment by alichtman** [comment]
I can reproduce this with:

```
$ youtube-dl https://www.youtube.com/watch?v=QP6hRIwWbSU -x
[youtube] QP6hRIwWbSU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ youtube-dl --version
2021.12.17
```

**Comment by nicolaasjan** [comment]
> Unable to extract uploader id

Already reported: #31530

Also read:
#30839

**Comment by tilemoon** [comment]
use brew to install youbute-dl instead of curl, this worked for me.
