### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by Semaichacha** [ytdl-org/youtube-dl#32216]
[youtube] St0vdGfK7Ak: Downloading webpage
[youtube] St0vdGfK7Ak: Downloading player e50626d8
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by cantonbecker** [comment]
Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version;

youtube-dl --version
2021.12.17

**Comment by dirkf** [comment]
#30839 !
