### ISSUE TITLE
youtube_dl.utils.DownloadError

### ISSUE THREAD

**Issue by jiobhai** [ytdl-org/youtube-dl#32222]
i got this error: youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
even though whe i run pip install --upgrade youtube_dl

it says 
Requirement already satisfied: youtube_dl in c:\users\avinash\appdata\local\programs\python\python310\lib\site-packages (2021.12.17)
plz help.

avinash

## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
#30839 !
