### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by Mr-Beta-Version** [ytdl-org/youtube-dl#32229]
$ youtube-dl https://youtu.be/yJg-Y5byMMw
Error :
[youtube] yJg-Y5byMMw: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by RealJustBoo** [comment]
Exact same error. Had been working until now. Is it youtube?

**Comment by Verbsisthehomie** [comment]
Same with me usually when it does this i try another video ..but it hasnt been working all morning what do we do ?

**Comment by dirkf** [comment]
#30839 ! x 3

**Comment by janosroden** [comment]
This helped me: https://github.com/yt-dlp/yt-dlp/issues/6247#issuecomment-1433096554

**Comment by suntong** [comment]
Thanks @janosroden, #30839 says that it is fixed in git master, but I installed from https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip minutes ago and still having the problem; whereas your link solved the problem directly. thanks.

**Comment by dirkf** [comment]
No, because the fix in master that you failed to install (`--force-reinstall` ?) collects the correct metadata.

**Comment by suntong** [comment]
It was a brand new install, with no previous installation, using 

`pip install https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip`

Would `--force-reinstall` still be necessary in such case?
