### ISSUE TITLE
Facing this issue in accessing the video from youtube by using youtube_dl on the Anaconda platform

### ISSUE THREAD

**Issue by MuzamilAhmed-17** [ytdl-org/youtube-dl#32225]
runfile('F:/Anaconda/My Projects/untitled0.py', wdir='F:/Anaconda/My Projects')
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):

  File ~\AppData\Roaming\Python\Python310\site-packages\youtube_dl\YoutubeDL.py:815 in wrapper
    return func(self, *args, **kwargs)

  File ~\AppData\Roaming\Python\Python310\site-packages\youtube_dl\YoutubeDL.py:836 in __extract_info
    ie_result = ie.extract(url)

  File ~\AppData\Roaming\Python\Python310\site-packages\youtube_dl\extractor\common.py:534 in extract
    ie_result = self._real_extract(url)

  File ~\AppData\Roaming\Python\Python310\site-packages\youtube_dl\extractor\youtube.py:1794 in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,

  File ~\AppData\Roaming\Python\Python310\site-packages\youtube_dl\extractor\common.py:1012 in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File ~\AppData\Roaming\Python\Python310\site-packages\pafy\backend_youtube_dl.py:40 in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)

  File ~\AppData\Roaming\Python\Python310\site-packages\youtube_dl\YoutubeDL.py:808 in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)

  File ~\AppData\Roaming\Python\Python310\site-packages\youtube_dl\YoutubeDL.py:824 in wrapper
    self.report_error(compat_str(e), e.format_traceback())

  File ~\AppData\Roaming\Python\Python310\site-packages\youtube_dl\YoutubeDL.py:628 in report_error
    self.trouble(error_message, tb)

  File ~\AppData\Roaming\Python\Python310\site-packages\youtube_dl\YoutubeDL.py:598 in trouble
    raise DownloadError(message, exc_info)

DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File C:\ProgramData\anaconda3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File f:\anaconda\my projects\untitled0.py:37
    data = pafy.new(url)

  File ~\AppData\Roaming\Python\Python310\site-packages\pafy\pafy.py:124 in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)

  File ~\AppData\Roaming\Python\Python310\site-packages\pafy\backend_youtube_dl.py:31 in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)

  File ~\AppData\Roaming\Python\Python310\site-packages\pafy\backend_shared.py:97 in __init__
    self._fetch_basic()

  File ~\AppData\Roaming\Python\Python310\site-packages\pafy\backend_youtube_dl.py:43 in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))

OSError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by MuzamilAhmed-17** [comment]
What should i do ??

**Comment by dirkf** [comment]
Study #30839 more closely.
