### ISSUE TITLE
[TF1] impossible to download

### ISSUE THREAD

**Issue by lm2lm2** [ytdl-org/youtube-dl#32238]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

I think so!

> ## Verbose log
>youtube-dl  "https://prod-player.tf1.fr/6d34d92e-a47c-45eb-be25-b6fec4ecdbe4" --cookies /tmp/AA.txt --verbose
>[debug] System config: []
>[debug] User config: []
>[debug] Custom config: []
>[debug] Command-line args: ['https://prod-player.tf1.fr/6d34d92e-a47c-45eb-be25-b6fec4ecdbe4', '--cookies', '/tmp/AA.txt', '--verbose']
>[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
>[debug] youtube-dl version 2021.12.17
>[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-12-amd64-x86_64-with-glibc2.31
>[debug] exe versions: ffmpeg 4.3.3-0, ffprobe 4.3.3-0
>[debug] Proxy map: {}
>[generic] 6d34d92e-a47c-45eb-be25-b6fec4ecdbe4: Requesting header
WARNING: Could not send HEAD request to https://prod-player.tf1.fr/6d34d92e-a47c-45eb-be25-b6fec4ecdbe4: HTTP Error 403: Forbidden
[generic] 6d34d92e-a47c-45eb-be25-b6fec4ecdbe4: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  >File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  >File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  >File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  >File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
  >  result = func(*args)
 > File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
>    raise HTTPError(req.full_url, code, msg, hdrs, fp)

```


## Description

<!--
Entered a command line, but get a forbidden result
-->

youtube-dl fails with TF1 videos
https://www.tf1.fr/player/f769c9e0-31fe-4234-a2fe-77ecafd2f0f4
from

**Comment by dirkf** [comment]
>I think so!

Change each item that you've checked from `[ ]` to `[x]`, then. Also put a triple backquote before your log, so that that is quoted instead of the description text.

yt-dl is not meant be able to download any random media URL. Rather, it offers a way of reproducing the access to a media URL from a user-facing video or audio website.

Consulting G suggests that you are trying to access the video here: https://www.tf1.fr/tmc/quotidien-avec-yann-barthes/videos/linfluence-meme-polska-et-tootatis-sont-en-manif-a-leur-facon-71394737.html

This fails with the release version but works with the latest master code where the Wat extractor has been updated.

**Comment by lm2lm2** [comment]
> > I think so!
> 
> Change each item that you've checked from `[ ]` to `[x]`, then. Also put a triple backquote before your log, so that that is quoted instead of the description text.
> 
> yt-dl is not meant be able to download any random media URL. Rather, it offers a way of reproducing the access to a media URL from a user-facing video or audio website.
> 
> Consulting G suggests that you are trying to access the video here: https://www.tf1.fr/tmc/quotidien-avec-yann-barthes/videos/linfluence-meme-polska-et-tootatis-sont-en-manif-a-leur-facon-71394737.html
> 
> This fails with the release version but works with the latest master code where the Wat extractor has been updated.

thank you for your reply
yes its this
I tried to get the latest master code by git clone but still on [debug] youtube-dl version 2021.12.17.. how could I download latest code?

thank you

**Comment by dirkf** [comment]
See #31350.

**Comment by lm2lm2** [comment]
> 

sorry but I donnt understand :(

**Comment by dirkf** [comment]
No, sorry, my fault: #31530 ! Follow one of the suggested solutions to fix both that issue and this TF1 issue.

**Comment by lm2lm2** [comment]
> No, sorry, my fault: #31530 ! Follow one of the suggested solutions to fix both that issue and this TF1 issue.

sorry, but I dont see the solution, it's its not only to  add -U to the command line? but it's still the same youtube-dl version that I have?

**Comment by dirkf** [comment]
>... one of the [suggested solutions](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611) ...

**Comment by lm2lm2** [comment]
> > ... one of the [suggested solutions](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611) ...

do you mean those three?

Or you can use the yt-dl git master by installing it with pip from your Python installation (probably 2.7 is the minimum version for which this works, and you need a pip version that is new enough to install from GitHub but old enough to run in 2.7).

Or you can find an unofficial nightly build in a fork of yt-dl, or make your own fork and build the program.

Or you can wait for an official release with the latest changes.



there are toooo many messages..

**Comment by dirkf** [comment]
That's what the linked text says. Pick the one that best suits your installation, or "[none of the suggested methods work for me](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1520185289)".

**Comment by dirkf** [comment]
Superseded by #32299.
