### ISSUE TITLE
youtube-dl error

### ISSUE THREAD

**Issue by milktoast71** [ytdl-org/youtube-dl#32237]
youtube-dl https://www.youtube.com/watch?v=C0DPdy98e4c

[youtube] C0DPdy98e4c: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

youtube-dl --verbose 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.2 (CPython) - Linux-6.2.0-20-generic-x86_64-with-glibc2.37
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

$ youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

**Comment by dirkf** [comment]
#30839 !

**Comment by milktoast71** [comment]
instead of just closing an issue with youtube-dl, update it with this.

___________________

The youtube-dl project is unofficially dead. There have been no updates to the project, though was previously very active. There have been no published responses from the project maintainers, and the project was having serious issues on numerous websites starting several months ago.

Many people have migrated to [yt-dlp](https://github.com/yt-dlp/yt-dlp), which has several install options, including PIP.

_________________

and then close it.

**Comment by dirkf** [comment]
Your issue was closed because you 
* ignored the bug reporting template, and
* apparently ignored the pinned issue #30839, and
* opened an issue that is a duplicate of a known issue listed in the pinned issue.

Apart from that it was a great bug report.
