### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by Pinaevv** [ytdl-org/youtube-dl#32236]
[youtube] fwUcTLcjac4: Downloading webpage ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Ignoring exception in slash command 'play': Traceback (most recent call last): File "/home/runner/TRRP-Bot-By-Ant1ve/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper return func(self, *args, **kwargs) File "/home/runner/TRRP-Bot-By-Ant1ve/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info ie_result = ie.extract(url) File "/home/runner/TRRP-Bot-By-Ant1ve/venv/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract ie_result = self._real_extract(url) File "/home/runner/TRRP-Bot-By-Ant1ve/venv/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract 'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None, File "/home/runner/TRRP-Bot-By-Ant1ve/venv/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex raise RegexNotFoundError('Unable to extract %s' % _name) youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/runner/TRRP-Bot-By-Ant1ve/venv/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 732, in invoke await call_param_func(self.callback, inter, self.cog, **kwargs) File "/home/runner/TRRP-Bot-By-Ant1ve/venv/lib/python3.10/site-packages/disnake/ext/commands/params.py", line 1022, in call_param_func return await maybe_coroutine(safe_call, function, **kwargs) File "/home/runner/TRRP-Bot-By-Ant1ve/venv/lib/python3.10/site-packages/disnake/utils.py", line 600, in maybe_coroutine return await value File "main.py", line 253, in play info = ydl.extract_info(url, download=False) File "/home/runner/TRRP-Bot-By-Ant1ve/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info return self.__extract_info(url, ie, download, extra_info, process) File "/home/runner/TRRP-Bot-By-Ant1ve/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 824, in wrapper self.report_error(compat_str(e), e.format_traceback()) File "/home/runner/TRRP-Bot-By-Ant1ve/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 628, in report_error self.trouble(error_message, tb) File "/home/runner/TRRP-Bot-By-Ant1ve/venv/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 598, in trouble raise DownloadError(message, exc_info) youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/home/runner/TRRP-Bot-By-Ant1ve/venv/lib/python3.10/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1377, in process_application_commands await app_command.invoke(interaction) File "/home/runner/TRRP-Bot-By-Ant1ve/venv/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 741, in invoke raise CommandInvokeError(exc) from exc disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
#30839 !

**Comment by Pinaevv** [comment]
I still don't understand how to solve the problem

**Comment by dirkf** [comment]
Why not? Have you found the solutions linked from the pinned issue? If not, try reading again.
