### ISSUE TITLE
YouTube Live "Unable to extract uploader id"

### ISSUE THREAD

**Issue by markmals** [ytdl-org/youtube-dl#32248]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=KMGJk2VtQ3I', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 4446fe603
[debug] Python version 3.10.11 (CPython) - macOS-13.4-arm64-arm-64bit
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] KMGJk2VtQ3I: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

When trying to download [this YouTube Live video](https://www.youtube.com/watch?v=KMGJk2VtQ3I) ([and](https://www.youtube.com/live/jwppKc4avIk) [several](https://www.youtube.com/live/nY7k3ql5mss) [others](https://www.youtube.com/live/2bkuEIa3Nwk)) via the command `youtube-dl https://www.youtube.com/watch\?v\=KMGJk2VtQ3I`, I get an error from `youtube-dl` saying "Unable to extract uploader id; please report this issue on https://yt-dl.org/bug," which is what I'm doing here.

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar issues including closed ones

Learn how by reading #30839 (**again**?).

>... please report this issue on https://yt-dl.org/bug  ...

Thanks, but this is shorthand for "... please follow the reporting procedure at https://yt-dl.org/bug  ...": the title of the pinned issue "READ THIS BEFORE OPENING A NEW ISSUE! THIS MEANS YOU!" is a hint.

**Comment by markmals** [comment]
Feel free to link me to any existing duplicate issues that follow this checklist. I could not find any.

**Comment by dirkf** [comment]
Have you **actually read** the pinned issue? That exact thing is in the list of known issues.
