### ISSUE TITLE
Error: Unable to extract uploader id

### ISSUE THREAD

**Issue by llayague** [ytdl-org/youtube-dl#32249]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

I have already gone through upgrading my youtube-dl to no avail with uploading any youtube video of my interest. Still this message emerged: "youtube-dl 'https://www.youtube.com/watch?v=dOQowCeAnRs'
[youtube] dOQowCeAnRs: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(base) lowells.layague@Lowells-MacBook-Pro ~ %"
Please help!

**Comment by dirkf** [comment]
Help yourself: read #30839. Also, use the checklist.
