### ISSUE TITLE
error on download a playlist

### ISSUE THREAD

**Issue by meacodes** [ytdl-org/youtube-dl#32254]
hello when i try to download a playlist youtube-dl show an error.
I use youtube-dl (2021.12.17) update

youtube-dl -f 45 https://www.youtube.com/playlist?list=PLRZx7LpGZLGkOW-KXbknkNEhlaLA0cYfj
[youtube:tab] PLRZx7LpGZLGkOW-KXbknkNEhlaLA0cYfj: Downloading webpage
[download] Downloading playlist: آموزش رايگان تحليل تكنيكال
[youtube:tab] Downloading page 1
[youtube:tab] playlist آموزش رايگان تحليل تكنيكال: Downloading 185 videos
[download] Downloading video 1 of 185
[youtube] fI-zGuuz_JM: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
#30839 !
