### ISSUE TITLE
DownloadError: ERROR: Unable to extract uploader id; 

### ISSUE THREAD

**Issue by FapconV** [ytdl-org/youtube-dl#32255]
Unable to reslove this error in the fllowing code

The lastest version of youtebe_dl is installed yet facing the same error

video_url = 'https://www.youtube.com/watch?v=qiQR5rTSshw'

# Set the options for downloading the audio
# Set the options for downloading the audio
options = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '192',
    }],
    'extractor': 'youtube',  # Specify the extractor explicitly
    'outtmpl': '%(title)s.%(ext)s',  # Save audio with the video title as the filename
}

# Download the audio using youtube_dl
with youtube_dl.YoutubeDL(options) as ydl:
    ydl.download([video_url])

**Comment by XPLing** [comment]
I also encountered the same problem. I am using the window system and installed it through Python. The version number is 2021.12.17

**Comment by TheoMalt** [comment]
I also encountered the same problem. I am using Windows and installed via python -m pip install youtube-dl --upgrade
(unrelated note: The pip install for this package tries to update "yside2" which I believe should refer to "PySide2" instead.)

Command example:

youtube-dl -i --socket-timeout 5 --limit-rate 1310720 --retries 1 --buffer-size 16k --cookies "L:/YoutubeDownloads/cookies_20230531.txt" --verbose -f bestaudio --audio-format mp3 --geo-bypass --sleep-interval 2 --max-sleep-interval 5 -o "%%(playlist_uploader)s/%%(playlist)s/%%(playlist_index)s - %%(title)s.%%(ext)s" -i https://www.youtube.com/playlist?list=PLs1-UdHIwbo4pv_vkle3E2kyHwxUIOAbB

Verbose example included below:

[download] Downloading video 9 of 42
[youtube] 3PJIAYcXQ2U: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\lmacc\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\lmacc\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\lmacc\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\lmacc\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Users\lmacc\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
#30839 !

**Comment by dirkf** [comment]
>... The pip install for this package tries to update "yside2" which I believe should refer to "PySide2" instead.

Probably, but yt-dl doesn't have anything to do with it. PySide2 is a GUI library. Some part of your _pip_ setup may be damaged.
