### ISSUE TITLE
Download of pDl9mE73fb0 from youtube does not work with V.2021.12.17

### ISSUE THREAD

**Issue by hovora** [ytdl-org/youtube-dl#32265]
## Checklist

- [ ] I'm reporting a broken site support issue – I don't understand what that means
- [x] I've verified that I'm running youtube-dl version **2021.12.17**

youtube-dl --version
2021.12.17

- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones – No, sorry.
- [ ] I've read bugs section in FAQ – Neither, sorry.

I was asked to "please report this issue on https://yt-dl.org/bug ." That is what I am doing.
Write: "Read all of our FAQs and Bugtracker content, then report this issue", if this is what you want people to do.

## Verbose log

```
PASTE VERBOSE LOG HERE
```

youtube-dl pDl9mE73fb0
[youtube] pDl9mE73fb0: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\hvr\_Programs\youtube-dl>youtube-dl --verbose pDl9mE73fb0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'pDl9mE73fb0']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-78335-g9ee4c89, ffprobe N-78335-g9ee4c89
[debug] Proxy map: {}
[youtube] pDl9mE73fb0: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE

Download of pDl9mE73fb0 from youtube does not work, see log above.

**Comment by dirkf** [comment]
> ... I don't understand what that means

Extraction from a supported site is broken.

I assume your responses that you meant to check the last two items, but if so
>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839 (**again**?).

>[x] I've read bugs section in FAQ

Apply this.
