### ISSUE TITLE
/usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by NickyMcLean** [ytdl-org/youtube-dl#32261]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

   I'm using GNU/Linux Mint 21 without a lot of knowledge about linux systems. My original attempt was 
youtube-dl https://www.youtube.com/watch?v=a4UQJwd3awQ
and this failed with something about a failed certificate,. This led me to consider possible updates of the software, as via youtube-dl -U  but this was rejected. Then via the Software Manager I tried uninstalling and re-installing and re-uninstalling then your manual install instructions
sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
hash -r
and have now reached a confused state whereby the message "/usr/bin/env: ‘python’: No such file or directory" now appears on attempts at invocation of youtube-dl

   I have no idea what to do now, as there is no obvious scheme for installing python, which I think is installed anyway (Dropbox uses it, for example)

   Meanwhile, this is a dual-bootstrap system, with wunduhx XP (software compatibility reasons too irritating to recount) so I have a go at downloading and installing the wunduhs version, presumably the latest available, also with bad results via a DOS window, as below:
-----------------------------------------------------------------------------------------------------
C:\Documents and Settings\Nicky\My Documents\Downloads>youtube-dl.exe --no-check-certificate --verbose https://www.youtube.com/watch?v=F-DvqEHJvFA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check-certificate', '--verbose', 'https://www.youtube.com/watch?v=F-DvqEHJvFA']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] F-DvqEHJvFA: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag
 and include its complete output.
--------------------------------------------------------------------------
   Entering youtube-dl -U didn't produce anything helpful; now I'm back in Linux, because I couldn't sign up to your GitHub system via Firefox on XP, so I don't now recall exactly what didn't work with -U via DOS.
   I can't try the --no-check-certificate on Linux, because youtube-dl command no longer activates, even after a fresh attempt at installing via the Software Manager. Presumably, something somewhere is messed up.
   I can't find mention of python in the README for this context. And now it is time for bed.

**Comment by dirkf** [comment]
Review #31530 to find suggestions for how to install an up-to-date yt-dl on your Linux system.

**Comment by NickyMcLean** [comment]
Thanks. After some noodling around, I used Linux/Mint's Software Manager to install yt-dlp and tried again, with the following intimidating response:
=====================================================================================
nicky@TimeVampire5:~$ yt-dlp https://www.youtube.com/watch?v=a4UQJwd3awQ
[youtube] a4UQJwd3awQ: Downloading webpage
[youtube] a4UQJwd3awQ: Downloading android player API JSON
[youtube] a4UQJwd3awQ: Downloading player f55759b8
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = PZZ3fwE5qwfdy3Y ; player = https://www.youtube.com/s/player/f55759b8/player_ias.vflset/en_US/base.js
a4UQJwd3awQ: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2519, in _decrypt_nsig
    self._player_cache[sig_id] = func(s)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2551, in <lambda>
    return lambda s: jsi.extract_function_from_code(*func_code)([s])
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 513, in extract_function_from_code
    body, remaining = self._separate_at_paren(code[body_start - 1:], '}')
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 117, in _separate_at_paren
    raise ExtractorError(f'No terminating paren {delim} in {expr}')
yt_dlp.utils.ExtractorError: No terminating paren } in {var e=null;switch(b){case "JSON":try{var f=c.responseText}catch(h){throw d=Error("Error reading responseText"),d.params=a,Jy(d),h;}a=c.getResponseHeader("Content-Type")||"";f&&0<=a.indexOf("json")&&(")]}'\n"===f.substring(0,5)&&(f=f.substring(5)),e=JSON.parse(f));break;case "XML":if(a=(a=c.responseXML)?wma(a):null)e={},g.Tb(a.getElementsByTagName("*"),function(h){e[h.tagName]=xma(h)})}d&&yma(e);
return e};
yma=function(a){if(g.Ra(a))for(var b in a)"html_content"==b||Haa(b,"_html")?a[b]=g.ke(a[b]):yma(a[b])};
wma=function(a){return a?(a=("responseXML"in a?a.responseXML:a).getElementsByTagName("root"))&&0<a.length?a[0]:null:null};
xma=function(a){var b="";g.Tb(a.childNodes,function(c){b+=c.nodeValue});
return b};
cz=function(a,b){b.method="POST";b.postParams||(b.postParams={});return g.bz(a,b)};
az=function(a,b,c,d,e,f,h){function l(){4==(m&&"readyState"in m?m.readyState:0)&&b&&g.Iy(b)(m)}
c=void 0===c?"GET":c;d=void 0===d?"":d;var m=nma();if(!m)return null;"onloadend"in m?m.addEventListener("loadend",l,!1):m.onreadystatechange=l;g.Cy("debug_forward_web_query_parameters")&&(a=rma(a,window.location.search));m.open(c,a,!0);f&&(m.responseType=f);h&&(m.withCredentials=!0);c="POST"==c&&(void 0===window.FormData||!(d instanceof FormData));if(e=pma(a,e))for(var n in e)m.setRequestHeader(n,e[n]),"content-type"==n.toLowerCase()&&(c=!1);c&&m.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
m.send(d);return m};
ez=function(a,b){var c=g.ed(b),d;return(new g.zf(function(e,f){c.onSuccess=function(h){g.Wy(h)?e(new zma(h)):f(new dz("Request failed, status="+Vy(h),"net.badstatus",h))};
c.onError=function(h){f(new dz("Unknown request error","net.unknown",h))};
c.onTimeout=function(h){f(new dz("Request timed out","net.timeout",h))};
d=g.bz(a,c); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 (caused by ExtractorError('No terminating paren } in {var e=null;switch(b){case "JSON":try{var f=c.responseText}catch(h){throw d=Error("Error reading responseText"),d.params=a,Jy(d),h;}a=c.getResponseHeader("Content-Type")||"";f&&0<=a.indexOf("json")&&(")]}\'\\n"===f.substring(0,5)&&(f=f.substring(5)),e=JSON.parse(f));break;case "XML":if(a=(a=c.responseXML)?wma(a):null)e={},g.Tb(a.getElementsByTagName("*"),function(h){e[h.tagName]=xma(h)})}d&&yma(e);\nreturn e};\nyma=function(a){if(g.Ra(a))for(var b in a)"html_content"==b||Haa(b,"_html")?a[b]=g.ke(a[b]):yma(a[b])};\nwma=function(a){return a?(a=("responseXML"in a?a.responseXML:a).getElementsByTagName("root"))&&0<a.length?a[0]:null:null};\nxma=function(a){var b="";g.Tb(a.childNodes,function(c){b+=c.nodeValue});\nreturn b};\ncz=function(a,b){b.method="POST";b.postParams||(b.postParams={});return g.bz(a,b)};\naz=function(a,b,c,d,e,f,h){function l(){4==(m&&"readyState"in m?m.readyState:0)&&b&&g.Iy(b)(m)}\nc=void 0===c?"GET":c;d=void 0===d?"":d;var m=nma();if(!m)return null;"onloadend"in m?m.addEventListener("loadend",l,!1):m.onreadystatechange=l;g.Cy("debug_forward_web_query_parameters")&&(a=rma(a,window.location.search));m.open(c,a,!0);f&&(m.responseType=f);h&&(m.withCredentials=!0);c="POST"==c&&(void 0===window.FormData||!(d instanceof FormData));if(e=pma(a,e))for(var n in e)m.setRequestHeader(n,e[n]),"content-type"==n.toLowerCase()&&(c=!1);c&&m.setRequestHeader("Content-Type","application/x-www-form-urlencoded");\nm.send(d);return m};\nez=function(a,b){var c=g.ed(b),d;return(new g.zf(function(e,f){c.onSuccess=function(h){g.Wy(h)?e(new zma(h)):f(new dz("Request failed, status="+Vy(h),"net.badstatus",h))};\nc.onError=function(h){f(new dz("Unknown request error","net.unknown",h))};\nc.onTimeout=function(h){f(new dz("Request timed out","net.timeout",h))};\nd=g.bz(a,c); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = YgDT9SWz2iaf5vA ; player = https://www.youtube.com/s/player/f55759b8/player_ias.vflset/en_US/base.js
a4UQJwd3awQ: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2519, in _decrypt_nsig
    self._player_cache[sig_id] = func(s)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2551, in <lambda>
    return lambda s: jsi.extract_function_from_code(*func_code)([s])
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 513, in extract_function_from_code
    body, remaining = self._separate_at_paren(code[body_start - 1:], '}')
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 117, in _separate_at_paren
    raise ExtractorError(f'No terminating paren {delim} in {expr}')
yt_dlp.utils.ExtractorError: No terminating paren } in {var e=null;switch(b){case "JSON":try{var f=c.responseText}catch(h){throw d=Error("Error reading responseText"),d.params=a,Jy(d),h;}a=c.getResponseHeader("Content-Type")||"";f&&0<=a.indexOf("json")&&(")]}'\n"===f.substring(0,5)&&(f=f.substring(5)),e=JSON.parse(f));break;case "XML":if(a=(a=c.responseXML)?wma(a):null)e={},g.Tb(a.getElementsByTagName("*"),function(h){e[h.tagName]=xma(h)})}d&&yma(e);
return e};
yma=function(a){if(g.Ra(a))for(var b in a)"html_content"==b||Haa(b,"_html")?a[b]=g.ke(a[b]):yma(a[b])};
wma=function(a){return a?(a=("responseXML"in a?a.responseXML:a).getElementsByTagName("root"))&&0<a.length?a[0]:null:null};
xma=function(a){var b="";g.Tb(a.childNodes,function(c){b+=c.nodeValue});
return b};
cz=function(a,b){b.method="POST";b.postParams||(b.postParams={});return g.bz(a,b)};
az=function(a,b,c,d,e,f,h){function l(){4==(m&&"readyState"in m?m.readyState:0)&&b&&g.Iy(b)(m)}
c=void 0===c?"GET":c;d=void 0===d?"":d;var m=nma();if(!m)return null;"onloadend"in m?m.addEventListener("loadend",l,!1):m.onreadystatechange=l;g.Cy("debug_forward_web_query_parameters")&&(a=rma(a,window.location.search));m.open(c,a,!0);f&&(m.responseType=f);h&&(m.withCredentials=!0);c="POST"==c&&(void 0===window.FormData||!(d instanceof FormData));if(e=pma(a,e))for(var n in e)m.setRequestHeader(n,e[n]),"content-type"==n.toLowerCase()&&(c=!1);c&&m.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
m.send(d);return m};
ez=function(a,b){var c=g.ed(b),d;return(new g.zf(function(e,f){c.onSuccess=function(h){g.Wy(h)?e(new zma(h)):f(new dz("Request failed, status="+Vy(h),"net.badstatus",h))};
c.onError=function(h){f(new dz("Unknown request error","net.unknown",h))};
c.onTimeout=function(h){f(new dz("Request timed out","net.timeout",h))};
d=g.bz(a,c); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 (caused by ExtractorError('No terminating paren } in {var e=null;switch(b){case "JSON":try{var f=c.responseText}catch(h){throw d=Error("Error reading responseText"),d.params=a,Jy(d),h;}a=c.getResponseHeader("Content-Type")||"";f&&0<=a.indexOf("json")&&(")]}\'\\n"===f.substring(0,5)&&(f=f.substring(5)),e=JSON.parse(f));break;case "XML":if(a=(a=c.responseXML)?wma(a):null)e={},g.Tb(a.getElementsByTagName("*"),function(h){e[h.tagName]=xma(h)})}d&&yma(e);\nreturn e};\nyma=function(a){if(g.Ra(a))for(var b in a)"html_content"==b||Haa(b,"_html")?a[b]=g.ke(a[b]):yma(a[b])};\nwma=function(a){return a?(a=("responseXML"in a?a.responseXML:a).getElementsByTagName("root"))&&0<a.length?a[0]:null:null};\nxma=function(a){var b="";g.Tb(a.childNodes,function(c){b+=c.nodeValue});\nreturn b};\ncz=function(a,b){b.method="POST";b.postParams||(b.postParams={});return g.bz(a,b)};\naz=function(a,b,c,d,e,f,h){function l(){4==(m&&"readyState"in m?m.readyState:0)&&b&&g.Iy(b)(m)}\nc=void 0===c?"GET":c;d=void 0===d?"":d;var m=nma();if(!m)return null;"onloadend"in m?m.addEventListener("loadend",l,!1):m.onreadystatechange=l;g.Cy("debug_forward_web_query_parameters")&&(a=rma(a,window.location.search));m.open(c,a,!0);f&&(m.responseType=f);h&&(m.withCredentials=!0);c="POST"==c&&(void 0===window.FormData||!(d instanceof FormData));if(e=pma(a,e))for(var n in e)m.setRequestHeader(n,e[n]),"content-type"==n.toLowerCase()&&(c=!1);c&&m.setRequestHeader("Content-Type","application/x-www-form-urlencoded");\nm.send(d);return m};\nez=function(a,b){var c=g.ed(b),d;return(new g.zf(function(e,f){c.onSuccess=function(h){g.Wy(h)?e(new zma(h)):f(new dz("Request failed, status="+Vy(h),"net.badstatus",h))};\nc.onError=function(h){f(new dz("Unknown request error","net.unknown",h))};\nc.onTimeout=function(h){f(new dz("Request timed out","net.timeout",h))};\nd=g.bz(a,c); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] a4UQJwd3awQ: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
nicky@TimeVampire5:~$ yt-dlp -U
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: yt-dlp's self-update mechanism is disabled on Debian.
Please update yt-dlp using apt(8).
See https://packages.debian.org/sid/yt-dlp for the latest packaged version.
=========================================================================
I am not at all clear what might be done now, as apt(8) evokes a syntax error from bash...

**Comment by dirkf** [comment]
#30839: "If you were actually **running yt-dlp** ..."

But, generally, some sort of web search engine will help you.

You seem to have installed a slightly out-of-date yt-dlp. The error you see is fixed in recent versions. When the instructions mention `apt(8)`, `apt` is the command name and `8` is the Unix manual section (system management), so the command `man -s 8 apt` shows you its documentation. But your Mint presumably has some package management GUI that wraps _apt_ and may be more friendly for you.

**Comment by NickyMcLean** [comment]
More confusion, but then success! Thanks.
I had been employing the Software Manager precisely to not strain my limited experience with GNU/Linux Mint and weird commands and strange parameters...
Via the link in bold blue above, I get to https://packages.debian.org/sid/all/yt-dlp/download where I see that "aptitude" or "synaptic" are advised rather than some sort of manual exercise. So:
sudo aptitude install yt-dlp
yt-dlp is already installed at the requested version (2022.04.08-1)
No packages will be installed, upgraded, or removed. etc. 

Righto. This clearly is not the later version guff given on that web page, so I go for the offered link ftp.nz.debian.org/debian and after encouraging Firefox to proceed not via https, poke the result and a presentation similar to that of the Software Manager is shown for yt-dlp and subtitle 2023.03.04-1 which matches the version guff on the webpage, which is good, and then appears "Same version is already installed". Humphf. In all the floundering, I wonder what litter is scattered about.
 But it is worth another try: yt-dlp https://www.youtube.com/watch?v=a4UQJwd3awQ

And it works! Yay!!

Thanks again.

**Comment by dirkf** [comment]
In case you don't get on with _yt-dlp_, you can download an unofficial nightly yt-dl as in the issue linked above.

With these programs, the target websites change too frequently for package managers to keep up with the resulting program changes. As the programs have few dependencies, it's easier to keep pulling new versions from GH. Once you've installed the package manager version, you may be able to update it directly with the _pip_ of your system's Python: again, described in the above linked issue.

**Comment by dirkf** [comment]
Also, it's good practice to put your URLs in 'quotes'. Eg, _bash_ will split off a piece of an unquoted URL that contains `&`.
