### ISSUE TITLE
New release build on Releases?

### ISSUE THREAD

**Issue by karl-police** [ytdl-org/youtube-dl#32274]
## Checklist

- [ X ] I'm asking a question
- [ X ] I've looked through the README and FAQ for similar questions
- [ X ] I've searched the bugtracker for similar questions including closed ones

## Question

When will that happen? Because I get "Unable to extract uploader id" and idk.

**Comment by nicolaasjan** [comment]
Duplicate of #31585.

> A new release is overdue but depends on solving certain cross-platform issues in the CI build process. Meanwhile for the main platforms, see #31530 for update hints.
