### ISSUE TITLE
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id (Python 3.10 / ubuntu)

### ISSUE THREAD

**Issue by jbirtley88** [ytdl-org/youtube-dl#32276]
## Checklist

- [] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --verbose 'https://www.youtube.com/watch?v=bYW0OnkJxEg'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=bYW0OnkJxEg']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-73-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube] bYW0OnkJxEg: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id

Python version 3.10.6 on ubuntu

This happens for every video URL, it may be some incompatibility with my environment (which I've not been able to figure out and cant find anything in the FAQ)

Fantastic product, keep up the good work!

Many thanks,

**Comment by jbirtley88** [comment]
I tracked down the point at which the RegexNotFoundError happens:

youtube.py:1794

Setting 'fatal=False' avoids the error:

`'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id', *fatal=False*) if owner_profile_url else None,`

The values being passed to `_search_regex` are:

  - pattern: ```'/(?:channel|user)/([^/?&#]+)'```
  - string: http://www.youtube.com/@FamouslyFunny
  - name: uploader id

**Comment by jbirtley88** [comment]
FYI: this is not a problem on `main` (commit b8a86dcf1aa837577178ae25357d8241ab4ba6c1)

**Comment by dirkf** [comment]
This is (an example of) why you were asked to read #30839 before posting. Then you would find the issue for this problem, together with remediations.
