### ISSUE TITLE
youtube-dl 2021.12.17 fails against YouTube

### ISSUE THREAD

**Issue by NetwarSystem** [ytdl-org/youtube-dl#32280]
Running youtube-dl 2021.12.17 as a Python pip package under Anaconda 23.3.1 AND as a deb package, both on Ubuntu 22.04, results in a failure to extract an uploader ID:

```
 File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,

  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

```

verbose run and pip freeze from my system.

https://gist.github.com/NetwarSystem/51a7e7842c18e568119f687babe0c5a5

I'm going to pull the code, run it under Pycharm, see if I can provide a more precise description of what's happening.

**Comment by dirkf** [comment]
No need. Instead, read #30839 as asked.
