### ISSUE TITLE
Error while downloading a Playlist

### ISSUE THREAD

**Issue by PranuPranav97** [ytdl-org/youtube-dl#32283]
## Checklist

- [X ] I've verified that I'm running youtube-dl version **2021.12.17**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X ] I've searched the bugtracker for similar bug reports including closed ones
- [X ] I've read bugs section in FAQ

## Verbose log

```
[youtube:tab] PL9DpKzAHkdgrsL5Lm1DCXQT5jfcK1okw5: Downloading webpage
[download] Downloading playlist: Income Tax & TDS by LLA
[youtube:tab] playlist Income Tax & TDS by LLA: Downloading 18 videos
[download] Downloading video 1 of 18
[youtube] Wy017TbTzuY: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I tried downloading a playlist it is throwing error.
OS: Windows 10

**Comment by dirkf** [comment]
>[X] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839 (**again**?).

>[X] I've read bugs section in FAQ

Apply this.

#30839 !
