### ISSUE TITLE
Can I download purchased videos with an API key?

### ISSUE THREAD

**Issue by Sawtaytoes** [ytdl-org/youtube-dl#32294]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

I found numerous similar questions, but not this particular one.

## Question

I want to purchase a show only available on YouTube, but I want to make sure I can download it with youtube-dl.

From what I understand, I need to login to my YouTube account to download these files through youtube-dl, but I'd like to avoid that.

Is there a way to avoid passing my credentials? I saw a way to pass in an API key, will that work or does it need my actual user-pass? What are my options here?

**Comment by october262** [comment]
youtube-dl does not download DRM Protected  purchased shows / movies.
