### ISSUE TITLE
youtube-dl is not ignoring unavailable videos and reflecting error. 

### ISSUE THREAD

**Issue by Ajeet-kumar1** [ytdl-org/youtube-dl#32304]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
I have a big list of urls in which some videos are unavailable. When I run youtube-dl download command it reflect downloading  error after few videos. In my case removing unavailable video link is not possible manually

**Comment by dirkf** [comment]
1. Read #30839 !
2. Use the checklist !
3. Read the manual (eg `--ignore-errors`?)!

**Comment by dirkf** [comment]
@Ajeet-kumar1 ?
