### ISSUE TITLE
KeyError: 'QV'

### ISSUE THREAD

**Issue by hanseungwan5676** [ytdl-org/youtube-dl#32323]
[message (1).txt](https://github.com/ytdl-org/youtube-dl/files/11785261/message.1.txt)

## Checklist

- [v] I'm reporting a broken site support issue
- [v] I've verified that I'm running youtube-dl version **2021.12.17**
- [v] I've checked that all provided URLs are alive and playable in a browser
- [v] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [v] I've searched the bugtracker for similar bug reports including closed ones
- [v] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
What's the problem Please find the bug and fix it or give me some solutions

**Comment by dirkf** [comment]
>[v] I've searched the bugtracker for similar bug reports including closed ones

Learn how by by reading #30839 (**again**?).

>[v] I've read bugs section in FAQ

Apply this.

The template says to put `x` inside the checkboxes, not `v`. GH only recognises `[x]`.
