### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by SRWoody46** [ytdl-org/youtube-dl#32321]
- [ x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
C:\Users\srwoo\Downloads\YouTube>youtube-dl www.youtube.com/watch?v=pVcMsjyKlaM
WARNING: The url doesn't specify the protocol, trying with http
[youtube] pVcMsjyKlaM: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

\Users\srwoo\Downloads\YouTube>youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

## Description

WRITE DESCRIPTION HERE
I have just started to receive this error message and am unable to download videos using youtube-dl

**Comment by PhelanPKell** [comment]
I'm getting the exact same error as well. Just came looking for a fix.

**Comment by urmaskedboi** [comment]
im having the same error too, is youtube-dl just not working for everyone?

**Comment by itisrazza** [comment]
youtube-dl hasn't had a tagged release since 2021. I'm sure the patch for the new YouTube username format was merged, but it's not widely available.

There's another issue tracking this, but I can't find it atm

**Comment by itisrazza** [comment]
Here's the issue: https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by dirkf** [comment]
>[ ] I've searched the bugtracker for similar bug reports including closed ones
>[ ] I've read bugs section in FAQ

Why not?

Use the checklist ! Read and follow #30839, which links to the relevant issue, as shown above ! @PhelanPKell, @urmaskedboi too.

**Comment by Hurt6704** [comment]
Yeah , And I'm getting the same error ,tooo.

My code :
from youtube_dl import YoutubeDL

YDL_OPTIONS = {'format': 'bestaudio', 'verbose': True}

def search(arg):
    with YoutubeDL(YDL_OPTIONS) as ydl:
        search_results = ydl.extract_info(f"ytsearch:{arg}", download=False)['entries']
    return search_results

search_results = search("30 sec video")
