### ISSUE TITLE
This library is not working in order to extract the tags from youtube video

### ISSUE THREAD

**Issue by aqshey** [ytdl-org/youtube-dl#32326]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by aqshey** [comment]
/Users/mr.ak/PycharmProjects/csvparse/venv/bin/python /Users/mr.ak/PycharmProjects/csvparse/youtube_tags/yttagsextractor.py 
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/mr.ak/PycharmProjects/csvparse/youtube_tags/yttagsextractor.py", line 23, in <module>
    tags = video_info['tags']
TypeError: 'NoneType' object is not subscriptable

**Comment by dirkf** [comment]
Follow #30839 ! Complete the checklist !
