### ISSUE TITLE
how youtube dl works ? what is the tech ? Thanks

### ISSUE THREAD

**Issue by SharinganKazekage** [ytdl-org/youtube-dl#32333]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by dirkf** [comment]
Read the code: https://github.com/ytdl-org/youtube-dl

**Comment by SharinganKazekage** [comment]
> Read the code: https://github.com/ytdl-org/youtube-dl

there are several line to read and it may take lot of time, i just want a general idea how this works exaxtly

**Comment by dirkf** [comment]
The program has various subsystems that run in this order:
* Extraction (match site to extractor module, extract site data)
* Core Processing (playlist recursion, format selection, output pathname construction)
* Downloading
* Postprocessing.

You'll see that the subsystems correspond to directories in the program source.
