### ISSUE TITLE
error download 

### ISSUE THREAD

**Issue by o0ocuchuoio0o** [ytdl-org/youtube-dl#32335]
D:\TMDT\HoTroFB\HoTroFB\bin\Debug\Youtubedl>youtube-dl --id 34396VmsYp8
[youtube] 34396VmsYp8: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I download -U new vession

**Comment by dirkf** [comment]
#30839 !
