### ISSUE TITLE
youtube-dl is not work

### ISSUE THREAD

**Issue by RazibuddinSozol** [ytdl-org/youtube-dl#32349]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

YouTube-dl did not work properly in PyCharm. I installed the latest version of YouTube-dl which is 2021.12.17....... :))...
The terminal section shows that reports as debug.

**Comment by dirkf** [comment]
#30839 ! Use the checklist !

If after that, you find that your problem is a new one, post your verbose log in the issue with the completed checklist. The issue may be re-opened if valid.
