### ISSUE TITLE
running into an error, says to report bug

### ISSUE THREAD

**Issue by bam23444** [ytdl-org/youtube-dl#32348]
script:

import youtube_dl

# Set the YouTube channel URL
channel_url = "https://www.youtube.com/channel/CHANNEL_ID"

# Set the download directory
download_dir = "videos/"

# Set the options for downloading videos
ydl_opts = {
    'format': 'bestvideo+bestaudio/best',
    'outtmpl': f'{download_dir}%(title)s.%(ext)s',
}

# Create a YouTube downloader instance
ydl = youtube_dl.YoutubeDL(ydl_opts)

# Download the videos from the channel
with ydl:
    ydl.download([channel_url])

## Checklist

- [ x] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE

I am trying to setup a simple youtube channel video downloader but it seems that is has some sort of bug. any help is greatly appreciated.

**Comment by dirkf** [comment]
What's the actual YT URL you are trying to get?

`https://www.youtube.com/channel/CHANNEL_ID` isn't an actual YT URL: you would replace the text `CHANNEL_ID` with an actual ID like `UCmlqkdCBesrv2Lak1mF_MxA` (the project test channel).

**Comment by alexisnsns** [comment]
@bam23444 do you have updates on this issue or should it be closed? Did you try @dirkf suggestion to change the URL?
Thank you
