### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by RobertSheldon** [ytdl-org/youtube-dl#32347]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
$ youtube-dl --verbose https://www.youtube.com/watch?v=4S94TIDv9CA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=4S94TIDv9CA']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.19.0-45-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 4S94TIDv9CA: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
Seems to be the same problem listed earlier. I assume YouTube keeps changing up its format to cause this.

**Comment by sameeragrawal5210** [comment]
Same issue here.

**Comment by GalaxyVOID** [comment]
Same here

**Comment by dirkf** [comment]
>[ ] I'm reporting a broken site support issue

You are, but shouldn't be: see below.

>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839 (**again**?).

>[x] I've read bugs section in FAQ

Apply this.

>... YouTube keeps changing up its format to cause this.

If anything, you keep not using an updated version of the program. This hasn't changed since February.

**Comment by RobertSheldon** [comment]
Thanks!
Why don't you put it in the "known bugs" part of the FAQ? I didn't see the discussion of yt-dlp anywhere, and I tried updating 3 different ways but kept getting the 2021.12.17 version.
 -yours
Rob

________________________________________
From: dirkf ***@***.***>
Sent: Friday, June 23, 2023 2:02 PM
To: ytdl-org/youtube-dl
Cc: Robert Sheldon; Author
Subject: [Ext] - Re: [ytdl-org/youtube-dl] Unable to extract uploader id (Issue #32347)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


[ ] I'm reporting a broken site support issue

You are, but shouldn't be: see below.

[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.com%2Fytdl-org%2Fyoutube-dl%2Fissues%2F30839&data=05%7C01%7C%7Ce07619b3d91449cf69df08db741c684b%7Cb765b7c18d554c69b7336f16240cd8cb%7C0%7C0%7C638231437595422807%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=I1jsKKSH8OpT8Ysj%2Fnhvvx5%2BM%2FLYPCovDO2coLm8Kcc%3D&reserved=0> (again?).

[x] I've read bugs section in FAQ

Apply this.

... YouTube keeps changing up its format to cause this.

If anything, you keep not using an updated version of the program. This hasn't changed since February.

—
Reply to this email directly, view it on GitHub<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.com%2Fytdl-org%2Fyoutube-dl%2Fissues%2F32347%23issuecomment-1604737093&data=05%7C01%7C%7Ce07619b3d91449cf69df08db741c684b%7Cb765b7c18d554c69b7336f16240cd8cb%7C0%7C0%7C638231437595427793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QySUAOQVcMWbvewNC6miWgUwSn84A7cOJ%2FOCTnlYuCg%3D&reserved=0>, or unsubscribe<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG442BMYMUGEFILJU5LHRE3XMXR4XANCNFSM6AAAAAAZR34OOU&data=05%7C01%7C%7Ce07619b3d91449cf69df08db741c684b%7Cb765b7c18d554c69b7336f16240cd8cb%7C0%7C0%7C638231437595432765%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=C3BQqYANvfm0QjAZ%2FfpMftMV1rJ5kAvVyoZQGTyAC%2Bo%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>
This e-mail including any attachments may contain information that is privileged, confidential, and/or otherwise protected from disclosure to anyone other than its intended recipient(s). Any dissemination or use of this e-mail or its attachments by persons other than the intended recipient(s) is prohibited. If you received this message in error, please contact the sender immediately. Please then delete the e-mail and any attachments in its entirety.

**Comment by dirkf** [comment]
Did you actually read [the pinned issue](https://github.com/ytdl-org/youtube-dl/issues/30839) (**known issues**, link to updating advice)?
