### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by Bluemethyst** [ytdl-org/youtube-dl#32345]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Hello, i have just started using ytdl and i think its a great service :) im having problems when downloading a video, its giving me the output ill put below. I followed this youtube video when installing it so maybe that video was outdated?

Video: https://www.youtube.com/watch?v=vv9UZXKzAB0
Console Output: ```[youtube] -wNyEUrxzFU: Downloading webpage```
```ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

**Comment by dirkf** [comment]
#30839 !
