### ISSUE TITLE
 Unable to extract uploader id

### ISSUE THREAD

**Issue by VoilierBleu** [ytdl-org/youtube-dl#32356]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
:youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

:youtube-dl "https://www.youtube.com/watch?v=oLV23rsdy4I" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=oLV23rsdy4I', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-74700-g628a73f, ffprobe N-74700-g628a73f
[debug] Proxy map: {}
[youtube] oLV23rsdy4I: Downloading webpage
[youtube] oLV23rsdy4I: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

French computer, windows 10 family. well known ID issue, but even with the last version, not working (i've seen https://github.com/ytdl-org/youtube-dl/issues/31530)

**Comment by dirkf** [comment]
Read it, then, and **do what it suggests**. Or post your failing installation log. You are not running a fixed version.

**Comment by benjamin4453** [comment]
Hello, I had the same issue, fixed by installing a youtube-dl version with git like explained here: https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435477247

**Comment by dirkf** [comment]
What I said, in fact, though _git_ is not required.

**Comment by SaintlyCoder** [comment]
His output shows 2021.12.17 which is the latest version as per the https://yt-dl.org/ website.

**Comment by Ytrog** [comment]
Same issue on latest version.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://youtu.be/j__MFhKvGQA', '-s', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Proxy map: {}
[youtube] j__MFhKvGQA: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the la
test version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complet
e output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line
815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line
836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py"
, line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py
", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py"
, line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug .
Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbos
e flag and include its complete output.
```

Did try to update, however this is the latest release.

**Comment by ississi** [comment]
yt-dlp is working for me on windows

**Comment by Ytrog** [comment]
> @SaintlyCoder, @Ytrog, @ississi: do actually read the response to the issue. Follow the link in the issue description to solve the problem.

Yeah I did. Basically the solution is to get the master version via git. It would be nice it it was to be resolved on the stable release and not requiring the users to basically construct a dev environment for this.

**Comment by obadul024** [comment]
> ###
> **[Ytrog](/Ytrog) ** commented [Jun 26, 2023](#issuecomment-1607815386) •

I can confirm this works
Download the compiled binary file and use that

# Description

Ubuntu Linux, Python3.8

**Comment by VoilierBleu** [comment]
> Read it, then, and **do what it suggests**. Or post your failing installation log. You are not running a fixed version.

I did it, and the tool reply me it is up to date. Such a clever tool. Or maybe, such a clever dev in his tower...

> "Make sure you are using the latest version; type  youtube-dl -U  to update"

> -> ":youtube-dl -U
> youtube-dl is up-to-date (2021.12.17)"

But no problem, i tool a serious tool (yt-dlp.exe) and everything works fine now. bye.

**Comment by dirkf** [comment]
So you actually didn't read #31350, then.

**Comment by ississi** [comment]
"Read it, then, and do what it suggests.". yes, i read it. But I'm on Windows and don't know how to use git. And most of the documentation seems to be unix(variant) based. So after a while of digging I found an alternative solution with yt-dlp. Not my fault you don't help people who want to learn.

**Comment by ississi** [comment]
From other people's responses it seems that the relevant article wasn't clear/useful for them either. I couldn't work out how to make or find the latest windows exe. If someone could tell me how to do that from #3150 then that would be really useful, please. thanks.

**Comment by ississi** [comment]
thank you, I've pieced together what I hope are the relevant bits for me from all the posts involved :-)

**Comment by CodeKraft** [comment]
> Ahem, #31530. But apart from that it seems straightforward, if you've used hypertext before.
> 
> 1. In `read the Description below` you follow the linked word `Description`.
> 2. In the Description you follow the linked word `below` in `See below for ways to update to a fixed version`.
> 3. That gives you the post that explains how to update your yt-dl, depending on the type of installation.
> 
> From your log you have a single file Windows build, so you need an unofficial nightly build of the same type: go to the site linked as `example` from `If you want a single file executable ...`. Or, as you decided, you could install yt-dlp if it was suitable.

This tells me nothing, why refer to it if it doesn't contain steps that will resolve the issue?

The youtube video shows a person commenting out the uploaderID line in the python script and they copy and CD in to that directory to access the script.

When I try it, I get an error.

Everything else previous suggests methods that DO NOT EXIST on this linux install.

There is no brew or pip I tried the github thing as aswell and that downloaded and nothing happened to resolve the problem and despite downloading the yt-dlp program, my system says it does not exist.

**Comment by ississi** [comment]
try changing the directory to the folder you downloaded the file, eg yt-dlp, into.
