### ISSUE TITLE
The error message suggests that the YouTube Downloader (youtube_dl) is unable to extract the uploader ID from the YouTube video. This can happen due to changes in the YouTube website structure or issues with the library itself.

### ISSUE THREAD

**Issue by AJM4K** [ytdl-org/youtube-dl#32357]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by dirkf** [comment]
#30839 !
