### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by wuschel16** [ytdl-org/youtube-dl#32368]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
D:\temp>youtube-dl.exe https://www.youtube.com/watch?v=h0ffIJ7ZO4U --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=h0ffIJ7ZO4U', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] h0ffIJ7ZO4U: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Just downloaded the program and tried to use it, but it gave the error you see above. It said I should report the bug.

**Comment by informatimago** [comment]
Another case: ```
12:36[pjb@despina org.xquartz:0 tangerine-dream 30Gi]$ youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

~/Downloads/tangerine-dream
12:37[pjb@despina org.xquartz:0 tangerine-dream 30Gi]$ youtube-dl -x 'https://www.youtube.com/watch?v=HcM2BNZGHlw'
[youtube] HcM2BNZGHlw: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

~/Downloads/tangerine-dream
12:37[pjb@despina org.xquartz:0 tangerine-dream 30Gi]$ youtube-dl --verbose -x 'https://www.youtube.com/watch?v=HcM2BNZGHlw'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-x', 'https://www.youtube.com/watch?v=HcM2BNZGHlw']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.17 (CPython) - macOS-12.6.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.4, ffprobe 4.4.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] HcM2BNZGHlw: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


~/Downloads/tangerine-dream
12:38[pjb@despina org.xquartz:0 tangerine-dream 30Gi]$ wget  --no-check-certificate --server-response 'https://www.youtube.com/watch?v=HcM2BNZGHlw'
--2023-06-27 12:39:06--  https://www.youtube.com/watch?v=HcM2BNZGHlw
Resolving www.youtube.com (www.youtube.com)... 2a00:1450:4007:818::200e, 2a00:1450:4007:819::200e, 2a00:1450:4007:81a::200e, ...
Connecting to www.youtube.com (www.youtube.com)|2a00:1450:4007:818::200e|:443... connected.
WARNING: The certificate of ‘www.youtube.com’ is not trusted.
WARNING: The certificate of ‘www.youtube.com’ doesn't have a known issuer.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Content-Type: text/html; charset=utf-8
  X-Content-Type-Options: nosniff
  Cache-Control: no-cache, no-store, max-age=0, must-revalidate
  Pragma: no-cache
  Expires: Mon, 01 Jan 1990 00:00:00 GMT
  Date: Tue, 27 Jun 2023 10:39:06 GMT
  X-Frame-Options: SAMEORIGIN
  Strict-Transport-Security: max-age=31536000
  Report-To: {"group":"youtube_main","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/youtube_main"}]}
  Origin-Trial: AvC9UlR6RDk2crliDsFl66RWLnTbHrDbp+DiY6AYz/PNQ4G4tdUTjrHYr2sghbkhGQAVxb7jaPTHpEVBz0uzQwkAAAB4eyJvcmlnaW4iOiJodHRwczovL3lvdXR1YmUuY29tOjQ0MyIsImZlYXR1cmUiOiJXZWJWaWV3WFJlcXVlc3RlZFdpdGhEZXByZWNhdGlvbiIsImV4cGlyeSI6MTcxOTUzMjc5OSwiaXNTdWJkb21haW4iOnRydWV9
  Permissions-Policy: ch-ua-arch=*, ch-ua-bitness=*, ch-ua-full-version=*, ch-ua-full-version-list=*, ch-ua-model=*, ch-ua-wow64=*, ch-ua-form-factor=*, ch-ua-platform=*, ch-ua-platform-version=*
  Cross-Origin-Opener-Policy-Report-Only: same-origin-allow-popups; report-to="youtube_main"
  P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=fr for more info."
  Server: ESF
  X-XSS-Protection: 0
  Set-Cookie: YSC=0alSfuAbhlc; Domain=.youtube.com; Path=/; Secure; HttpOnly; SameSite=none
  Set-Cookie: VISITOR_INFO1_LIVE=; Domain=.youtube.com; Expires=Wed, 30-Sep-2020 10:39:06 GMT; Path=/; Secure; HttpOnly; SameSite=none
  Set-Cookie: __Secure-YEC=CgtCYWZ4WkxiV3BZNCjK-OqkBg%3D%3D; Domain=.youtube.com; Expires=Fri, 26-Jul-2024 10:39:05 GMT; Path=/; Secure; HttpOnly; SameSite=lax
  Set-Cookie: CONSENT=PENDING+695; expires=Thu, 26-Jun-2025 10:39:06 GMT; path=/; domain=.youtube.com; Secure
  Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
  Accept-Ranges: none
  Vary: Accept-Encoding
  Transfer-Encoding: chunked
Length: unspecified [text/html]
Saving to: ‘watch?v=HcM2BNZGHlw’

watch?v=HcM2BNZGHlw                        [  <=>                                                                      ]   1.03M  3.04MB/s    in 0.3s    

2023-06-27 12:39:06 (3.04 MB/s) - ‘watch?v=HcM2BNZGHlw’ saved [1083878]

```
[watch?v=HcM2BNZGHlw.zip](https://github.com/ytdl-org/youtube-dl/files/11880997/watch.v.HcM2BNZGHlw.zip)

**Comment by dirkf** [comment]
>...  I should report the bug.

Then you ignored the pinned issue explaining how to do that?

>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by **actually reading** #30839, which BTW also lists your problem to save you the time.

>[x] I've read bugs section in FAQ

Apply this.
