### ISSUE TITLE
Installation stopped after this step

### ISSUE THREAD

**Issue by nicolasgrise** [ytdl-org/youtube-dl#32363]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

I need to know what went wrong in the installation of HomeBrew to stop me from installing Youtube-dl. This is the code:

user@users-MacBook-Air ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
Password:
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /usr/sbin/chown -R user:admin /usr/local/Homebrew
==> Downloading and installing Homebrew...
remote: Enumerating objects: 6492, done.
remote: Counting objects: 100% (3948/3948), done.
remote: Compressing objects: 100% (409/409), done.
remote: Total 6492 (delta 3529), reused 3891 (delta 3495), pack-reused 2544
Receiving objects: 100% (6492/6492), 2.59 MiB | 423.00 KiB/s, done.
Resolving deltas: 100% (4353/4353), completed with 805 local objects.
From https://github.com/Homebrew/brew
 * [new branch]          dependabot/bundler/Library/Homebrew/json_schemer-0.2.25 -> origin/dependabot/bundler/Library/Homebrew/json_schemer-0.2.25
 * [new branch]          dependabot/bundler/Library/Homebrew/parser-3.2.2.3 -> origin/dependabot/bundler/Library/Homebrew/parser-3.2.2.3
   0d749b5db..2ccdb26c4  master     -> origin/master
 * [new tag]             4.0.25     -> 4.0.25
 * [new tag]             4.0.13     -> 4.0.13
 * [new tag]             4.0.14     -> 4.0.14
 * [new tag]             4.0.15     -> 4.0.15
 * [new tag]             4.0.16     -> 4.0.16
 * [new tag]             4.0.17     -> 4.0.17
 * [new tag]             4.0.18     -> 4.0.18
 * [new tag]             4.0.19     -> 4.0.19
 * [new tag]             4.0.20     -> 4.0.20
 * [new tag]             4.0.21     -> 4.0.21
 * [new tag]             4.0.22     -> 4.0.22
 * [new tag]             4.0.23     -> 4.0.23
 * [new tag]             4.0.24     -> 4.0.24
Updating files: 100% (3588/3588), done.
HEAD is now at 2ccdb26c4 Merge pull request #15587 from p-linnane/remove-no-env-filtering-error
Updated 2 taps (homebrew/core and homebrew/cask).
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics data has been sent yet (nor will any be during this install run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Next steps:
- Run these two commands in your terminal to add Homebrew to your PATH:
    (echo; echo 'eval "$(/usr/local/bin/brew shellenv)"') >> /Users/user/.zprofile
    eval "$(/usr/local/bin/brew shellenv)"
- Run brew help to get started
- Further documentation:
    https://docs.brew.sh

user@users-MacBook-Air ~ % sudo brew install youtube-dl
Password:
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

**Comment by dirkf** [comment]
The message seems clear: don't use `sudo`.

From my limited and untested knowledge, you could try `brew install --HEAD youtube-dl` to install from the latest master code, or omit `--HEAD` to get an old and unsatisfactory patched version.

Ask at Homebrew (and/or read the linked docs), if this doesn't help.

**Comment by dirkf** [comment]
@nicolasgrise, did you solve the problem?

**Comment by nicolasgrise** [comment]
Hey! Thank you so much for the info! Sudo was the problem and it is now running smoothly.
