### ISSUE TITLE
HTTP Error 410: Gone For All Videos

### ISSUE THREAD

**Issue by Nasrill1** [ytdl-org/youtube-dl#32377]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
from pytube import YouTube

def Download(link):
    youtubeObject = YouTube(link)
    youtubeObject = youtubeObject.streams.get_highest_resolution()
    try:
        youtubeObject.download(filename = "video.mp4")
    except:
        print("An error has occurred")
    print("Download is completed successfully")


link = input("Enter the YouTube video URL: ")
Download(link)

# This is the link i used https://www.youtube.com/watch?v=O6zOlMjBQr4
```

## Description

any videos that I try and get using this code just come back with HTTP Error 410: Gone even though a couple days ago it was working fine

**Comment by dirkf** [comment]
Your issue is with **Pytube**. Ask there.

yt-dl master handles your problem URL fine.
