### ISSUE TITLE
RegexNotFoundError

### ISSUE THREAD

**Issue by hpvpp** [ytdl-org/youtube-dl#32373]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
humphrey@David:~$ sudo youtube-dl -U
[sudo] password for humphrey: 
youtube-dl is up-to-date (2021.12.17)
humphrey@David:~$ youtube-dl -v https://youtu.be/6-lXAdp6oLI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtu.be/6-lXAdp6oLI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.10 (CPython) - Linux-5.19.0-45-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 6-lXAdp6oLI: Downloading webpage
[youtube] 6-lXAdp6oLI: Downloading MPD manifest
[youtube] 6-lXAdp6oLI: Downloading player 71547d26
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function alias (Msa[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/home/humphrey/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1668, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/home/humphrey/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1640, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/home/humphrey/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1623, in _extract_n_function_name
    real_nfunc = self._search_regex(
  File "/home/humphrey/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1013, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function alias (Msa[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1687946011/ei/u66bZM-3JLPCpge_yLCABA/ip/49.190.138.125/id/ebe95701da7aa0b2/source/youtube/requiressl/yes/playback_host/rr3---sn-v2u0n-hxar.googlevideo.com/mh/_q/mm/31%2C29/mn/sn-v2u0n-hxar%2Csn-v2u0n-ntqk/ms/au%2Crdu/mv/m/mvi/3/pl/17/tx/24698584/txs/24698582%2C24698583%2C24698584%2C24698585%2C24698586%2C24698587%2C24698588/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1516250/spc/qEK7ByLpZ_XDyFE9rb09fClxU3Gvic1IMqPOUYHdmw/vprv/1/mt/1687924150/fvip/2/keepalive/yes/fexp/24007246%2C24363393/beids/24350018/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cspc%2Cvprv%2Citag/sig/AOq0QJ8wRgIhAOTqbM5vB4e4gKiJoPJRcOxzjlzGndbT8e4U92evm8a2AiEAokGL83Ig9hw9RANinXNbOn1xWR4cbx__pVpXoMNSFdA%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhAJjoC_-EqHJJaWE1Vu_tmByT8Z4aTC2YkH0LMNMkZAVJAiEA2aLXCaH3pyidjrPAbJxBlD9f406rXhbbmaizUaowyrA%3D'
[download] HEALING FORCE-Single (Side A)-01-Golden Miles-{1971}-6-lXAdp6oLI.f248.webm has already been downloaded
[download] 100% of 8.19MiB
[debug] Invoking downloader on 'https://rr3---sn-v2u0n-hxar.googlevideo.com/videoplayback?expire=1687946011&ei=u66bZM-3JLPCpge_yLCABA&ip=49.190.138.125&id=o-ADnGE9-5pAigYtODlPflL_bUrlbuic5v3nMWq_L3Y3er&itag=251&source=youtube&requiressl=yes&mh=_q&mm=31%2C29&mn=sn-v2u0n-hxar%2Csn-v2u0n-ntqk&ms=au%2Crdu&mv=m&mvi=3&pl=17&initcwndbps=1516250&spc=qEK7ByLpZ_XDyFE9rb09fClxU3Gvic1IMqPOUYHdmw&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=0vTUFXjfjKfH0oTA0eWFNREN&gir=yes&clen=3574637&otfp=1&dur=205.021&lmt=1586098903806492&mt=1687924150&fvip=2&keepalive=yes&fexp=24007246%2C24363393&beids=24350018&c=WEB&txp=2211222&n=SidKsf5K75ZPQJfCH8&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAOhPlpaY9a7WyDqhmm6aGyINKci6ywJAbO7vZikDr59nAiA2_GpTgdkD--A6Lq0PPw32dEc7BMeNU6L4q59pEH2KOQ%3D%3D&sig=AOq0QJ8wRAIgAYHv0WfyWp0bVKIKio8vwbRjyigXvhlOEEKv8Hzrc9gCIDF5ZV06ACKioR83zOPTsTsKd8POUaqtiLT4FL3oh9_i'
[dashsegments] Total fragments: 1
[download] Destination: HEALING FORCE-Single (Side A)-01-Golden Miles-{1971}-6-lXAdp6oLI.f251.webm
[download] 100% of 3.41MiB in 00:25
[ffmpeg] Merging formats into "HEALING FORCE-Single (Side A)-01-Golden Miles-{1971}-6-lXAdp6oLI.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:HEALING FORCE-Single (Side A)-01-Golden Miles-{1971}-6-lXAdp6oLI.f248.webm' -i 'file:HEALING FORCE-Single (Side A)-01-Golden Miles-{1971}-6-lXAdp6oLI.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:HEALING FORCE-Single (Side A)-01-Golden Miles-{1971}-6-lXAdp6oLI.temp.webm'
Deleting original file HEALING FORCE-Single (Side A)-01-Golden Miles-{1971}-6-lXAdp6oLI.f248.webm (pass -k to keep)
Deleting original file HEALING FORCE-Single (Side A)-01-Golden Miles-{1971}-6-lXAdp6oLI.f251.webm (pass -k to keep)
humphrey@David:~$ 

## Description

WRITE DESCRIPTION HERE

I saw this

WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function alias (Msa[0]); please report this issue on https://yt-dl.org/bug .

and also this

youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function alias (Msa[0]); please report this issue on https://yt-dl.org/bug . 

yet

the downloaded .webm file plays correctly

note

some time ago I encountered a problem with youtube-dl being unable to download anything from youtube, but I found a work-around on he web (I really am sorry,but I do not remember the details) and now youtube-dl -U reports

$ youtube-dl -U
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
humphrey@David:~$ 

current version is as follows

$ youtube-dl --version
2021.12.17
humphrey@David:~$

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar bug reports including closed ones

Review #30839 (**as asked**) for hints and also for your specific issues.
