### ISSUE TITLE
Mixcloud download failing with 403 error the last few days or so

### ISSUE THREAD

**Issue by phinett** [ytdl-org/youtube-dl#32387]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v https://www.mixcloud.com/housemixes/hear-this-2/ --write-info-json -o "c:\hm\" --no-clean-infojson --no-check-certificate --proxy socks5://MYPROXYURL

[debug] Command-line config: ['-v', 'https://www.mixcloud.com/housemixes/hear-this-2/', '--write-info-json', '-o', 'c:\\hm" 0']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.14393-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[mixcloud] Extracting URL: https://www.mixcloud.com/housemixes/hear-this-2/
[mixcloud] housemixes_hear-this-2: Downloading JSON metadata
ERROR: [mixcloud] None: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 708, in extract
  File "yt_dlp\extractor\mixcloud.py", line 82, in _real_extract
  File "yt_dlp\extractor\mixcloud.py", line 22, in _call_api
  File "yt_dlp\extractor\common.py", line 1062, in download_content
  File "yt_dlp\extractor\common.py", line 1026, in download_handle
  File "yt_dlp\extractor\common.py", line 896, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 853, in _request_webpage

  File "yt_dlp\extractor\common.py", line 835, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3786, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

## Description

Been running the exact same script for over 12 months with no problems on many different profiles/media links, stopped working a few days ago and getting a 403 error.

I do run it via socks5 proxy, which works fine, have also tried without the proxy too and get the same error.

Looks like something has changed maybe there end?

**Comment by dirkf** [comment]
Works for me with both yt-dl release and latest master code. Try it with some other network configuration if you can. Also, check this again

>[x] I've checked that all provided URLs are alive and playable in a browser

If so, ensure that the network configuration passed to yt-dl correctly reproduces what the browser has.

**Comment by Ecthanatos** [comment]
@phinett for your information, the part of your error message containing the proxy link is leaking your private user and pass. Anyone can use these to malevolently use these proxies without having to connect through your account. I strongly advise you to delete this part of your post.
