### ISSUE TITLE
Uploader ID extraction failure during YouTube video download

### ISSUE THREAD

**Issue by nobbssSS** [ytdl-org/youtube-dl#32388]
Bug Report

Description:
I encountered an issue while using youtube_dl to download YouTube videos. The uploader ID extraction failed, resulting in an error and preventing the download.

Steps to Reproduce:

1. Execute the following code with youtube_dl library:
import youtube_dl

video_link = "https://www.youtube.com/watch?v=LU4SeNys5JU"
output_path = "/path/to/save/video.mp4"

ydl_opts = {
    'outtmpl': output_path,
    'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
    'nocheckcertificate': True,
    'verbose': True
}

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    try:
        info = ydl.extract_info(video_link, download=True)
        if 'entries' in info:
            info = info['entries'][0]
        video_filename = ydl.prepare_filename(info)
        print(video_filename)
    except youtube_dl.utils.DownloadError as e:
        print(e)

Expected Behavior:
The YouTube video should be downloaded successfully without any errors.

Actual Behavior:
The following error occurs during the extraction of the uploader ID:
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug. Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
#30839 !
