### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by heit0r** [ytdl-org/youtube-dl#32384]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ X] I've verified that I'm running youtube-dl version **2021.12.17**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl --verbose https://www.youtube.com/watch?v=KR2LEr-553s
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=KR2LEr-553s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - Linux-6.2.0-2-rt3-MANJARO-x86_64-with-glibc2.37
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] KR2LEr-553s: Downloading webpage
[youtube] KR2LEr-553s: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ youtube-dl --version
2021.12.17


```

## Description

Nothing special. I tried to download the video above and i got an error. After verbosing, it gave me the output that asked me to follow this link and report a bug, so i did it.

**Comment by NealMcBealTheNavySeal** [comment]
I have this exact same issue I have no idea what's wrong

**Comment by dirkf** [comment]
Why don't you both read #30839, which is part of "reporting the bug", then? And OP, complete the checklist, which is also part of "reporting the bug"!

After that you would not need to open a new duplicate issue.

**Comment by NealMcBealTheNavySeal** [comment]
> Why don't you both read #30839, which is part of "reporting the bug", then? And OP, complete the checklist, which is also part of "reporting the bug"!
> 
> After that you would not need to open a new duplicate issue.

I was just commenting that i had it too man why u so pressed

**Comment by dirkf** [comment]
Before commenting, you could have researched the problem (which in this case just means reading the pinned issue) and found the existing issue with its resolution. Then it would have been helpful to post your findings for OP. This would be useful to the community. "Me too", not so much.
