### ISSUE TITLE
ITVX (https://www.itv.com) stopped working

### ISSUE THREAD

**Issue by AnonymousAlt0** [ytdl-org/youtube-dl#32382]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.itv.com/watch/love-island/2a3697/10a4471a0001', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.2 (CPython) - macOS-13.4.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[generic] 10a4471a0001: Requesting header

## Description

Youtube-dl times out when running `[generic] 10a4471a0001: Requesting header`. It was working 2 days ago.

**Comment by dirkf** [comment]
It shouldn't need to redirect, if you are using the extractor from the master code. I wouldn't expect the 2021.12 release to work at all.

**Comment by AnonymousAlt0** [comment]
It did until 2 days ago. Would you be able to elaborate on what you mean?

**Comment by dirkf** [comment]
Simply that new code was merged after ITVX started that handles the site directly. If the old ITV code works it's by accident.

**Comment by Vangelis66** [comment]
> if you are using the extractor from the `master` code

I can confirm the **latest** iteration of the `itvIE`, as found in the `yt-dl` `master` branch, functions as expected (from a whitelisted **UK** IP address) when given the `itvX` programme referenced in OP: 
```console
yt-dl -vF "https://www.itv.com/watch/love-island/2a3697/10a4471a0001" => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', '.\\FFmpeg', '--external-downloader-args', '-v 8 -stats', '-vF', 'https://www.itv.com/watch/love-island/2a3697/10a4471a0001']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2023.06.30.40298 (single file build)
[debug] Python 3.4.4 (CPython x86 32bit) - Windows-Vista-6.0.6003-SP2 - OpenSSL 1.0.2d 9 Jul 2015
[debug] exe versions: ffmpeg n6.1-dev-1397-N-111281-g285c7f6, ffprobe n6.1-dev-1397-N-111281-g285c7f6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[ITV] 10a4471a0001: Downloading webpage
[ITV] 10a4471a0001: Downloading JSON metadata
[ITV] 10a4471a0001: Downloading m3u8 information
[info] Available formats for 10a4471a0001:
format code  extension  resolution note
hls-68       mp4        audio only   68k , mp4a.40.2@ 64k
hls-102      mp4        audio only  102k , mp4a.40.2@ 96k
hls-285      mp4        512x288     285k , avc1.4D401F@ 203k, 25.0fps, mp4a.40.2@ 64k
hls-636      mp4        512x288     636k , avc1.4D401F@ 503k, 25.0fps, mp4a.40.2@ 96k
hls-848      mp4        512x288     848k , avc1.4D401F@ 703k, 25.0fps, mp4a.40.2@ 96k
hls-1272     mp4        896x504    1272k , avc1.4D401F@1103k, 25.0fps, mp4a.40.2@ 96k
hls-1908     mp4        896x504    1908k , avc1.4D401F@1703k, 25.0fps, mp4a.40.2@ 96k (best)
```
... and:  

```console
yt-dl --console-title --hls-prefer-native --hls-use-mpegts -c --no-part "https://www.itv.com/watch/love-island/2a3697/10a4471a0001" --write-thumbnail --write-description --write-sub --convert-subs=srt => 

[ITV] 10a4471a0001: Downloading webpage
[ITV] 10a4471a0001: Downloading JSON metadata
[ITV] 10a4471a0001: Downloading m3u8 information
[info] Writing video description to: Love Island - Series 9 - Episode 59 - Maya Jama's Top Moments-10a4471a0001.description
[info] Writing video subtitles to: Love Island - Series 9 - Episode 59 - Maya Jama's Top Moments-10a4471a0001.en.vtt
[ITV] 10a4471a0001: Downloading thumbnail ...
[ITV] 10a4471a0001: Writing thumbnail to: Love Island - Series 9 - Episode 59 - Maya Jama's Top Moments-10a4471a0001.jpg
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 94
[download] Destination: Love Island - Series 9 - Episode 59 - Maya Jama's Top Moments-10a4471a0001.mp4
[download]   1.3% of ~123.00MiB at 134.99KiB/s ETA 15:21
...
[download] 100% of 125.29MiB in 04:18
[ffmpeg] Fixing malformed AAC bitstream in "Love Island - Series 9 - Episode 59 - Maya Jama's Top Moments-10a4471a0001.mp4"
[ffmpeg] Converting subtitles
Deleting original file Love Island - Series 9 - Episode 59 - Maya Jama's Top Moments-10a4471a0001.en.vtt (pass -k to keep)
```

**Comment by AnonymousAlt0** [comment]
Is it possible my UK IP address has been blacklisted? I have been using youtube-dl in a daily script for the last few weeks, but itv works fine on a web browser?

**Comment by dirkf** [comment]
So your IP address isn't blacklisted. You'll need to update your yt-dl to use the master code. Pending a new release, #31530 has instructions.

**Comment by AnonymousAlt0** [comment]
I'm still experiencing the same problem using the current master code. Not sure what I'm doing wrong? I just download the whole repo and import it locally in my python script.

**Comment by dirkf** [comment]
Verbose log please. If the master code is a module visible to Python (eg, you're in the `youtube-dl` directory), you can run `python -m youtube_dl -v ...` where `python` is the name of your Python.

**Comment by Vangelis66** [comment]
> and import it locally in **my python script**.

Please try to use `youtube-dl` **directly**, outside of "_your python script_"; pinned #30839 dictates: 

> If your problem occurred when running another package that invokes `youtube-dl`, try to reproduce the problem with a `youtube-dl ...` command, or report it through the support channel for the other package; **similarly if the problem occurred when running your own code.**

In your OP, it is apparent you're on a **Mac**; in which way did you first install `yt-dl` there? Is any of the updating routes linked to previously (in #31530 ) close to that "way"? If you used `brew`, also read [this](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1601276330) ... In any case, please supply what was requested by the app's maintainer...

**Comment by AnonymousAlt0** [comment]
Sorry it is working now using the current master code. I swapped out the youtube-dl folder in my python project, but when I tested it initally it must've been using the old folder somehow. This morning, it's decided to work as expected. Thanks for your help.
