### ISSUE TITLE
[SoundCloud] HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by oszlsm** [ytdl-org/youtube-dl#32383]
> [soundcloud] None: Downloading webpage
> ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Unclosed tags: <u> (x1)

```
$ youtube-dl --verbose https://on.soundcloud.com/T3eq3dhesd3RYeXp7
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://on.soundcloud.com/T3eq3dhesd3RYeXp7']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-76-generic-x86_64-with-glibc2.35 - OpenSSL 3.0.2 15 Mar 2022 - glibc 2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] T3eq3dhesd3RYeXp7: Requesting header
WARNING: Could not send HEAD request to https://on.soundcloud.com/T3eq3dhesd3RYeXp7: HTTP Error 403: Forbidden
[generic] T3eq3dhesd3RYeXp7: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
File "/home/sound/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 635, in _request_webpage
return self._downloader.urlopen(url_or_request)
File "/home/sound/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2356, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "/usr/lib/python3.10/urllib/request.py", line 525, in open
response = meth(req, response)
File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
response = self.parent.error(
File "/usr/lib/python3.10/urllib/request.py", line 557, in error
result = self._call_chain(*args)
File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
result = func(*args)
File "/usr/lib/python3.10/urllib/request.py", line 749, in http_error_302
return self.parent.open(new, timeout=req.timeout)
File "/usr/lib/python3.10/urllib/request.py", line 525, in open
response = meth(req, response)
File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
response = self.parent.error(
File "/usr/lib/python3.10/urllib/request.py", line 563, in error
return self._call_chain(*args)
File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
result = func(*args)
File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)

```

**Comment by oszlsm** [comment]
DownloadError("\x1b[0;31mERROR:\x1b[0m Unable to download webpage: HTTP Error 403: Forbidden (caused by ); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the verbose flag and include its complete output.")

**Comment by dirkf** [comment]
What part of this was unclear?

> Be sure to call youtube-dl with the verbose flag and include its complete output

Also, following #30839 (do it) would have led you to #11598, which offers several possible explanations of your problem.

**Comment by oszlsm** [comment]
> What part of this was unclear?
> 
> > Be sure to call youtube-dl with the verbose flag and include its complete output
> 
> Also, following #30839 (do it) would have led you to #11598, which offers several possible explanations of your problem.

not solved
I think it is the problem of the lib

**Comment by dirkf** [comment]
Where is your verbose log, so that others can verify and try to reproduce your problem?

**Comment by oszlsm** [comment]
> 
![photo_2023-07-01_14-10-54](https://github.com/ytdl-org/youtube-dl/assets/98826241/bba2623a-22ae-4795-953f-9bb23e4e47fb)
So how do I fix the problem?

**Comment by dirkf** [comment]
By posting the log in text format including the original command line with `-v` or `--verbose` in the options.

**Comment by oszlsm** [comment]
> By posting the log in text format including the original command line with `-v` or `--verbose` in the options, like the example in #32387 and many other issues.
> 
> Ans also by correctly completing the issue template: #30839.

$ youtube-dl --verbose https://on.soundcloud.com/T3eq3dhesd3RYeXp7
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://on.soundcloud.com/T3eq3dhesd3RYeXp7']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-76-generic-x86_64-with-glibc2.35 - OpenSSL 3.0.2 15 Mar 2022 - glibc 2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] T3eq3dhesd3RYeXp7: Requesting header
WARNING: Could not send HEAD request to https://on.soundcloud.com/T3eq3dhesd3RYeXp7: HTTP Error 403: Forbidden
[generic] T3eq3dhesd3RYeXp7: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/sound/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 635, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/sound/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2356, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by dirkf** [comment]
Works for me with both release and master yt-dl versions (Py 2.7, 3.9).

**Comment by douineauromain** [comment]
Hello

I have the same problem since today

`/youtube-dl --dump-json -f best --extract-audio --audio-format mp3 --audio-quality 7 -v -- https://soundcloud.com/rackeduproy/fansonly
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--dump-json', u'-f', u'best', u'--extract-audio', u'--audio-format', u'mp3', u'--audio-quality', u'7', u'-v', u'--', u'https://soundcloud.com/rackeduproy/fansonly']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-5-amd64-x86_64-with-debian-10.3
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/yagomusic-website/cloud/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/yagomusic-website/cloud/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

`

youtube-dl is up-to-date (2021.12.17) and I have python 2.7

**Comment by dirkf** [comment]
Mais:
```console
$ youtube-dl -v -F 'https://soundcloud.com/rackeduproy/fansonly'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://soundcloud.com/rackeduproy/fansonly']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17.0
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[soundcloud] rackeduproy/fansonly: Downloading info JSON
[soundcloud] 1527005134: Downloading JSON metadata
[soundcloud] 1527005134: Downloading JSON metadata
[soundcloud] 1527005134: Downloading JSON metadata
[info] Available formats for 1527005134:
format code   extension  resolution note
hls_opus_64   opus       audio only audio@ 64k
hls_mp3_128   mp3        audio only audio@128k
http_mp3_128  mp3        audio only audio@128k (best)
$ python -m youtube_dl -v -F 'https://soundcloud.com/rackeduproy/fansonly'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://soundcloud.com/rackeduproy/fansonly']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: b29abeb6f
[debug] Python 2.7.18 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial - OpenSSL 1.1.1t  7 Feb 2023 - glibc 2.15
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[soundcloud] rackeduproy/fansonly: Downloading info JSON
[soundcloud] 1527005134: Downloading JSON metadata
[soundcloud] 1527005134: Downloading JSON metadata
[soundcloud] 1527005134: Downloading JSON metadata
[info] Available formats for 1527005134:
format code   extension  resolution note
hls_opus_64   opus       audio only audio@ 64k
hls_mp3_128   mp3        audio only audio@128k
http_mp3_128  mp3        audio only audio@128k (best)
$
```

**Comment by oszlsm** [comment]
> Mais:
> 
> ```
> $ youtube-dl -v -F 'https://soundcloud.com/rackeduproy/fansonly'
> [debug] System config: ['--prefer-ffmpeg']
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['-v', '-F', 'https://soundcloud.com/rackeduproy/fansonly']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2021.12.17.0
> [debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
> [debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
> [debug] Proxy map: {}
> [soundcloud] rackeduproy/fansonly: Downloading info JSON
> [soundcloud] 1527005134: Downloading JSON metadata
> [soundcloud] 1527005134: Downloading JSON metadata
> [soundcloud] 1527005134: Downloading JSON metadata
> [info] Available formats for 1527005134:
> format code   extension  resolution note
> hls_opus_64   opus       audio only audio@ 64k
> hls_mp3_128   mp3        audio only audio@128k
> http_mp3_128  mp3        audio only audio@128k (best)
> $ python -m youtube_dl -v -F 'https://soundcloud.com/rackeduproy/fansonly'
> [debug] System config: [u'--prefer-ffmpeg']
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'-v', u'-F', u'https://soundcloud.com/rackeduproy/fansonly']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2021.12.17
> [debug] Git HEAD: b29abeb6f
> [debug] Python 2.7.18 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial - OpenSSL 1.1.1t  7 Feb 2023 - glibc 2.15
> [debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
> [debug] Proxy map: {}
> [soundcloud] rackeduproy/fansonly: Downloading info JSON
> [soundcloud] 1527005134: Downloading JSON metadata
> [soundcloud] 1527005134: Downloading JSON metadata
> [soundcloud] 1527005134: Downloading JSON metadata
> [info] Available formats for 1527005134:
> format code   extension  resolution note
> hls_opus_64   opus       audio only audio@ 64k
> hls_mp3_128   mp3        audio only audio@128k
> http_mp3_128  mp3        audio only audio@128k (best)
> $
> ```

```
$ youtube-dl -v -F 'https://soundcloud.com/rackeduproy/fansonly'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://soundcloud.com/rackeduproy/fansonly']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-76-generic-x86_64-with-glibc2.35 - OpenSSL 3.0.2 15 Mar 2022 - glibc 2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] rackeduproy/fansonly: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 504: Gateway Time-out (caused by <HTTPError 504: 'Gateway Time-out'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/sound/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 635, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/sound/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2356, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by douineauromain** [comment]
very strange.

Solution I found, replace my _youtube-dl_ bin by _yt-dlp_ bin

**Comment by dirkf** [comment]
Follow https://github.com/ytdl-org/youtube-dl/issues/32387#issuecomment-1615838824.

Also, try sending `--user-agent ...` with the UA of your browser that successfully accesses the page and/or `--cookies ...` from the same browser.

**Comment by dirkf** [comment]
>Solution I found, replace my youtube-dl bin by yt-dlp bin

_yt-dlp_ may send some extra headers (`Sec-Fetch-Mode: navigate`, eg). One could add such headers manually in yt-dl if that makes a difference.

**Comment by dscnode** [comment]
Happening with the main site too:
https://old.reddit.com/r/soundcloud/comments/14nkvze/403_error_how_to_fix_this/
https://old.reddit.com/r/soundcloud/comments/14nig4l/403_error/

**Comment by dirkf** [comment]
From the Reddit threads, this was a transient issue for some IPs that ceased to be seen after a few weeks.
