### ISSUE TITLE
Error when trying Python Script with this library.

### ISSUE THREAD

**Issue by almostanexpert** [ytdl-org/youtube-dl#32394]
## Checklist

- [X] I'm reporting a broken site support issue
- [X I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[youtube] aA05SEjqrvA: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
An error occurred during the download
```

## Description

I apologize for the following information if it does not completely follow what is asked for, this is my very first report in GitHub or anywhere for that matter.

I used a python script with this library and in the past it has worked very well but when I recently tried using it again after a few days of the initial try I got this above error.

**Comment by dirkf** [comment]
Read and follow #30839 as asked. Use the checklist.
