### ISSUE TITLE
Error when trying to do an audio only download from Youtube

### ISSUE THREAD

**Issue by foomip** [ytdl-org/youtube-dl#32398]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
:~ $ youtube-dl --verbose -x --audio-format m4a --audio-quality 0 --embed-thumbnail 'https://www.youtube.com/watch?v=lZaLZO61-gY'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-x', u'--audio-format', u'm4a', u'--audio-quality', u'0', u'--embed-thumbnail', u'https://www.youtube.com/watch?v=lZaLZO61-gY']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.16 (CPython) - Linux-5.10.103-v8+-aarch64-with-debian-10.13
[debug] exe versions: ffmpeg 4.1.11-0, ffprobe 4.1.11-0
[debug] Proxy map: {}
[youtube] lZaLZO61-gY: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/foomip/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/foomip/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/foomip/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/foomip/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/foomip/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
Trying to do a audio-only download from a Youtube video, but I get the error above. Using a raspberry pi with Raspbian 10 - made sure to get all the latets updates but did not seem to make any difference,

**Comment by foomip** [comment]
So I downloaded the latest master version and that seems to be working as expected. So no use leaving this here, but in case anyone else comes across the same issue try the latest master version (as of 3 Jul 20232).

**Comment by dirkf** [comment]
As you should have found by reading #30839 and/or checking this
>[x] I've searched the bugtracker for similar bug reports including closed ones
