### ISSUE TITLE
Unexpected I/O error

### ISSUE THREAD

**Issue by TBLgGamin** [ytdl-org/youtube-dl#32403]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

When using the youtube_dl in my python project to play a yutube videos sound through a discord bot it randomly stops playing about 30 seconds in referring to an I/O error. I have not found any related error documentations so I was hoping I could get help here. Many thanks!

Error code PyCharm throws me:

[youtube] ffEnHsmGfdo: Downloading webpage (Playing the youtube videos sound correctly)
Then suddenly after 30seconds or so:

[tls @ 000001a8d4c12d80] Error in the pull function.
[tls @ 000001a8d4c12d80] IO error: Error number -10054 occurred
[tls @ 000001a8d4c12d80] The specified session has been invalidated for some reason.
    Last message repeated 1 times
[in#0/matroska,webm @ 000001a8d4c12380] Error during demuxing: I/O error
[in#0/matroska,webm @ 000001a8d4c12380] Error retrieving a packet from demuxer: I/O error
[2023-07-04 16:56:06] [INFO    ] discord.player: ffmpeg process 20872 successfully terminated with return code of 0.

**Comment by dirkf** [comment]
There's something wrong with your network. 10054 is a Windows error code meaning that the peer closed the connection.

Try to reproduce the problem using a yt-dl command from a terminal (window) without the Discord bot stuff.

**Comment by TBLgGamin** [comment]
That seems to work, It downloads and plays the audio file on my pc correctly. Would you have any idea why it shuts of when being played through a discord bot?

**Comment by dirkf** [comment]
You have to consider how the system on which the bot runs is connected to the outside world and whether something in that system or in the path to YT's download servers is blocking the connection. Unfortunately this is your problem and not related to yt-dl.

**Comment by TBLgGamin** [comment]
Ah okay thanks! Was going through the different sources that could cause the problem. Thanks for taking the time to respond, have a good day!

**Comment by dirkf** [comment]
Good luck!
