### ISSUE TITLE
Bug Report: Unable to Extract Uploader ID

### ISSUE THREAD

**Issue by Deepansekar** [ytdl-org/youtube-dl#32407]
Bug Report: Unable to Extract Uploader ID

Description:
I encountered an issue while using youtube-dl where it was unable to extract the uploader ID. This occurred when attempting to download a video using the following command:

**youtube-dl --verbose "https://www.youtube.com/watch?v=kuCsICnLS-0&ab_channel=C4ETechEnglish"**
Steps to Reproduce:

Run the command youtube-dl --verbose "https://www.youtube.com/watch?v=kuCsICnLS-0&ab_channel=C4ETechEnglish" in a command-line interface.
Observe the error message: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
The verbose output is also attached to this bug report.
Expected Behavior:
I expected youtube-dl to extract the uploader ID successfully and initiate the video download.

Observed Behavior:
youtube-dl failed to extract the uploader ID and returned an error message.

Environment:

Operating System: [Specify your operating system]
youtube-dl version: [Specify the version you are using]
Python version: [Specify your Python version]
Additional Information:

The issue seems to be related to the uploader ID extraction process.
I have followed the troubleshooting steps mentioned in the error message but the issue persists.
I have also ensured that I'm using the latest version of youtube-dl by following the update instructions provided on the youtube-dl website.
Verbose Output:
[Attach the complete verbose output of the youtube-dl command here]

Please let me know if there's any additional information or details you'd like to include in the bug report.

**Comment by dirkf** [comment]
Quite unnecessary. Instead, read #30839.
