### ISSUE TITLE
Cant download Video

### ISSUE THREAD

**Issue by mmm25002500** [ytdl-org/youtube-dl#32412]
```py
╭─tershi@tsx-mac.local ~/Downloads/Project/bityo/BityoDiscordBot/src  ‹main› 
╰─➤  youtube-dl https://www.youtube.com/watch\?v\=EI7j6gNhkJA                                                             2 ↵
[youtube] EI7j6gNhkJA: Downloading webpage
[youtube] EI7j6gNhkJA: Downloading player 1dda5629
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
╭─tershi@tsx-mac.local ~/Downloads/Project/bityo/BityoDiscordBot/src  ‹main› 
╰─➤  youtube-dl --version                                                                                                 1 ↵
2021.12.17
╭─tershi@tsx-mac.local ~/Downloads/Project/bityo/BityoDiscordBot/src  ‹main› 
╰─➤  
```
How can i fix it?

**Comment by checkiiiii** [comment]
almost the same issue with windows 11 system:  

$youtube-dl https://www.youtube.com/watch?v=29ZQ3TDGgRQ
[youtube] 29ZQ3TDGgRQ: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dglittle** [comment]
just wanted to chime in with the same issue, which I'm seeing basically everywhere I try it (both mac and linux), and every youtube video (and also every twitter link),

as one concrete example, like above:
(base) themachine@Thes-MacBook-Pro youtube-dl % ./youtube-dl "https://www.youtube.com/watch?v=ZREv8V5AU_8"
[youtube] ZREv8V5AU_8: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Just read #30839 **as you were (all) asked**.
