### ISSUE TITLE
BadStatusLine

### ISSUE THREAD

**Issue by MysticMerlin** [ytdl-org/youtube-dl#32415]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

youtube-dl https://www.itv.com/watch/emmerdale/Ya0524/1a8694a9701 --verbose

C:\Users\User\Videos\youtube-dl Downloads>youtube-dl https://www.itv.com/watch/emmerdale/Ya0524/1a8694a9701 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.itv.com/watch/emmerdale/Ya0524/1a8694a9701', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-109856-gf8d6d0fbf1-20230213, ffprobe 2023-02-13-git-2296078397-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] 1a8694a9701: Requesting header
WARNING: Could not send HEAD request to https://www.itv.com/watch/emmerdale/Ya0524/1a8694a9701: ''
[generic] 1a8694a9701: Downloading webpage
ERROR: Unable to download webpage: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug.
Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to
call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\utils.py", line 2737, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1186, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1227, in getresponse
  File "C:\Python\Python34\lib\http\client.py", line 386, in begin
  File "C:\Python\Python34\lib\http\client.py", line 356, in _read_status

## Description

WRITE DESCRIPTION HERE
Up to 30/06/2023 I was downloading the ITV News okay & Emmerdale as well as other programmes. I think it was from February 2023 that using a version on youtube-dl it was working again after it had stopped on or about 17/11/2022. So, as from the 30/06/2023 it stopped working & I'm getting 'BadStatusLine' error with the Emmerdale link as above. That link is valid until Monday 12th July 2023. Also, when entering the link on the command line (DOS Prompt) it says 'Requesting Header' for a very long time before eventually the error comes up. Just out of interest etc I can download the ITV News using the STV TV link and the Emmerdale link as well. I did do a search on the whole of the GitHub site & the only reported 'BadStatusLine' error was about 6years ago & it wasn't for the ITV TV.

**Comment by dirkf** [comment]
This `BadStatusLine` typically means that the remote server, or some censorship gateway between you and it, sent an empty response. Although the symptom is different, #32410 is the new underlying problem that has to be solved before worrying about this. Please follow that issue and any resulting PR so that you can test any resulting update.

STV has a different video hoster and the extractor logic is entirely different.
