### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by HachiDragon** [ytdl-org/youtube-dl#32418]
Requirement already satisfied: youtube-dl in c:\users\hachi.ttl.ttd\appdata\local\programs\python\python311\lib\site-packages (2021.12.17)

[youtube] BaW_jenozKc: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by UKNickyD** [comment]
I get the same...

`youtube-dl --verbose https://www.youtube.com/watch?v=JuOWoGpqg1I
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=JuOWoGpqg1I']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.10.0-23-amd64-x86_64-with-debian-11.7
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0
[debug] Proxy map: {}
[youtube] JuOWoGpqg1I: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by ageev-aleksey** [comment]
Hello, I have same problem 
```
youtube-dl --verbose https://www.youtube.com/watch?v=uikbtpVZS2s
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=uikbtpVZS2s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.19.0-45-generic-x86_64-with-glibc2.35
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] uikbtpVZS2s: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by rafae56038** [comment]
A temporal fix can be.
PythonFolder\Lib\site-packages\youtube_dl\extractor\youtube.py (For windows)
Replace line 1794
![imagen](https://github.com/ytdl-org/youtube-dl/assets/39964466/5b0806f3-b06b-4a28-9e2b-59f22af234c6)

**Comment by Mohit020888** [comment]
> A temporal fix can be. PythonFolder\Lib\site-packages\youtube_dl\extractor\youtube.py (For windows) Replace line 1794 ![imagen](https://user-images.githubusercontent.com/39964466/252023153-5b0806f3-b06b-4a28-9e2b-59f22af234c6.png)

Can you please give details step how and where to do this change in the code structure ?

**Comment by Mohit020888** [comment]
I am getting the same error 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydub\audio_segment.py:670](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/Admin/Downloads/my-music-analysis-main/my-music-analysis-main/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/pydub/audio_segment.py:670), in AudioSegment.from_file(cls, file, format, codec, parameters, start_second, duration, **kwargs)
    669 if start_second is None and duration is None:
--> 670     return cls._from_safe_wav(file)
    671 elif start_second is not None and duration is None:

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydub\audio_segment.py:818](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/Admin/Downloads/my-music-analysis-main/my-music-analysis-main/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/pydub/audio_segment.py:818), in AudioSegment._from_safe_wav(cls, file)
    817 file, close_file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
--> 818 file.seek(0)
    819 obj = cls(data=file)

AttributeError: 'bytes' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Cell In[10], line 49
     46 video_id = 'JSggxkx6iDo'
     48 # Identify the songs and their timestamps
---> 49 identified_songs = identify_songs(video_id)
     51 # Print the identified songs
     52 for song in identified_songs:

Cell In[10], line 17, in identify_songs(video_id)
...
--> 678         file.seek(0)
    679 elif is_format("raw") or is_format("pcm"):
    680     sample_width = kwargs['sample_width']

AttributeError: 'bytes' object has no attribute 'seek'
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?f5e3c00c-8059-4a6d-9a2b-b6dde421ca0a) or open in a [text editor](command:workbench.action.openLargeOutput?f5e3c00c-8059-4a6d-9a2b-b6dde421ca0a). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[16], line 51
     48 video_id = 'JSggxkx6iDo'
     50 # Identify the songs and their timestamps
---> 51 identified_songs = identify_songs(video_id)
     53 # Print the identified songs
     54 for song in identified_songs:

Cell In[16], line 19, in identify_songs(video_id)
     16 audio_data, _ = process.communicate()
     18 # Load the audio data with AudioSegment
---> 19 audio = AudioSegment.from_wav(io.BytesIO(audio_data))
     21 # Initialize the ACRCloud recognizer
     22 config = {
     23     'host': ACR_HOST,
     24     'access_key': ACR_ACCESS_KEY,
     25     'access_secret': ACR_ACCESS_SECRET,
     26 }

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydub\audio_segment.py:808](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/Admin/Downloads/my-music-analysis-main/my-music-analysis-main/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/pydub/audio_segment.py:808), in AudioSegment.from_wav(cls, file, parameters)
    806 @classmethod
    807 def from_wav(cls, file, parameters=None):
--> 808     return cls.from_file(file, 'wav', parameters=parameters)
...
   1524     self._close_pipe_fds(p2cread, p2cwrite,
   1525                          c2pread, c2pwrite,
   1526                          errread, errwrite)

FileNotFoundError: [WinError 2] The system cannot find the file specified
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?c058ba2d-b67f-4924-82aa-b2137464422f) or open in a [text editor](command:workbench.action.openLargeOutput?c058ba2d-b67f-4924-82aa-b2137464422f). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
[youtube] vou3ULwk9VQ: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
---------------------------------------------------------------------------
RegexNotFoundError                        Traceback (most recent call last)
File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py:815](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/Admin/Downloads/my-music-analysis-main/my-music-analysis-main/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/youtube_dl/YoutubeDL.py:815), in YoutubeDL.__handle_extraction_exceptions..wrapper(self, *args, **kwargs)
    814 try:
--> 815     return func(self, *args, **kwargs)
    816 except GeoRestrictedError as e:

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py:836](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/Admin/Downloads/my-music-analysis-main/my-music-analysis-main/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/youtube_dl/YoutubeDL.py:836), in YoutubeDL.__extract_info(self, url, ie, download, extra_info, process)
    834 @__handle_extraction_exceptions
    835 def __extract_info(self, url, ie, download, extra_info, process):
--> 836     ie_result = ie.extract(url)
    837     if ie_result is None:  # Finished already (backwards compatibility; listformats and friends should be moved here)

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\extractor\common.py:534](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/Admin/Downloads/my-music-analysis-main/my-music-analysis-main/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/youtube_dl/extractor/common.py:534), in InfoExtractor.extract(self, url)
    533 self.initialize()
--> 534 ie_result = self._real_extract(url)
    535 if self._x_forwarded_for_ip:

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\extractor\youtube.py:1794](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/Admin/Downloads/my-music-analysis-main/my-music-analysis-main/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/youtube_dl/extractor/youtube.py:1794), in YoutubeIE._real_extract(self, url)
   1782 owner_profile_url = microformat.get('ownerProfileUrl')
   1784 info = {
   1785     'id': video_id,
   1786     'title': self._live_title(video_title) if is_live else video_title,
   1787     'formats': formats,
   1788     'thumbnails': thumbnails,
...
    597         exc_info = sys.exc_info()
--> 598     raise DownloadError(message, exc_info)
    599 self._download_retcode = 1

DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?b870da41-974f-490f-8f9e-fd2d764faa1e) or open in a [text editor](command:workbench.action.openLargeOutput?b870da41-974f-490f-8f9e-fd2d764faa1e). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

**Comment by rafae56038** [comment]
In your case u need change this file, ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\extractor\youtube.py](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/Admin/Downloads/my-music-analysis-main/my-music-analysis-main/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/youtube_dl/extractor/youtube.py

With Visual Studio Code u can access to the line 1794, the content of the line is `'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,`
replace it with `'uploader_id': None,`

**Comment by ageev-aleksey** [comment]
[> /usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/youtube.py](https://github.com/ytdl-org/youtube-dl/issues/32418#issuecomment-1627435545)

@rafae56038, thank you. It is works for me. But there is the following problem: low download speed

```
$ youtube-dl https://www.youtube.com/watch?v=uikbtpVZS2s
[youtube] uikbtpVZS2s: Downloading webpage
[download] Resuming download at byte 1103272
[download] Destination: 01 - Relational Model & Relational Algebra (CMU Intro to Database Systems _ Fall 2022)-uikbtpVZS2s.mp4
[download]   0.9% of 208.99MiB at 59.48KiB/s ETA 59:25^C


$yt-dlp  https://www.youtube.com/watch?v=uikbtpVZS2s
[youtube] Extracting URL: https://www.youtube.com/watch?v=uikbtpVZS2s
[youtube] uikbtpVZS2s: Downloading webpage
[youtube] uikbtpVZS2s: Downloading ios player API JSON
[youtube] uikbtpVZS2s: Downloading android player API JSON
[youtube] uikbtpVZS2s: Downloading m3u8 information
[info] uikbtpVZS2s: Downloading 1 format(s): 22
[download] Destination: 01 - Relational Model & Relational Algebra (CMU Intro to Database Systems ⧸ Fall 2022) [uikbtpVZS2s].mp4
[download]  27.4% of  208.99MiB at    7.94MiB/s ETA 00:19^C

**Comment by dirkf** [comment]
OP and all commenters, especially those offering home-grown solutions: #30839 !
