### ISSUE TITLE
Youtube-dl; Unable to extract uploader id

### ISSUE THREAD

**Issue by kevinvh001** [ytdl-org/youtube-dl#32413]
Youtube-dl https://youtu.be/9MLGL0f4gS4
[youtube] 9MLGL0f4gS4: Downloading webpage
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] How To Download Windows 10 ARM Downgrade Instead Of Windows 11 ARM - M1 Mac Parallels VHDX UUP dump-9MLGL0f4gS4.mp4 has already been downloaded
[download] 100% of 16.37MiB

**Comment by fil-at-werma** [comment]
Same issue in Linux Ubuntu 22.04

**Comment by berni421** [comment]
Same here on Debian 11.7:

elbournb@cassandra:~/Downloads$ youtube-dl --verbose https://www.youtube.com/watch?v=bR55Fp_E238
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=bR55Fp_E238']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-23-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.4.4, ffprobe 4.4.4
[debug] Proxy map: {}
[youtube] bR55Fp_E238: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/data/apps/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/data/apps/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/data/apps/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/data/apps/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/data/apps/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by JarFrank** [comment]
I have same issue, is there any workaround?

**Comment by t0akeh** [comment]
it depends on the video, for me it works for some of the videos and for some dont!

**Comment by dirkf** [comment]
#30839 !
