### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Zafkieldark** [ytdl-org/youtube-dl#32422]
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by mk-pmb** [comment]
> Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
#30839 !
