### ISSUE TITLE
Youtube: Unable to extract uploader id

### ISSUE THREAD

**Issue by ikus060** [ytdl-org/youtube-dl#32425]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -citk --verbose --extract-audio --audio-format mp3 "https://www.youtube.com/watch?v=D4EQL_ic6ms"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-citk', '--verbose', '--extract-audio', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=D4EQL_ic6ms']
WARNING: --title is deprecated. Use -o "%(title)s-%(id)s.%(ext)s" instead.
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] D4EQL_ic6ms: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

This is probably due to a youtube changes since that was working 1 or 2 week ago.

When trying to download any youtube video, I'm getting that error.

**Comment by dirkf** [comment]
OP:
>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839 (**again**?).

>[x] I've read bugs section in FAQ

Apply this.

Other commenters: #30839 too.

**Comment by ikus060** [comment]
Hello @dirkf 

Thanks for your response. There are so many noise in the issue tracker that it's impossible to find the real duplicate. could you link it to me ? I can't find it.

**Comment by dirkf** [comment]
Have you actually read #30839 where the **known issue** is listed?

**Comment by ikus060** [comment]
Hello @dirkf 

Thanks a lot of pointing out to the list of know issues ! I found #31530 to be similar to my ticket. And the solution fixed the problem.

Thanks

**Comment by ikus060** [comment]
I understand that a project like youtube-dl might have a huge user base and handling tickets might be challenging.  Considering the number of duplicates, you might consider defining the list of known issue in the issue template directly. Or in the README file. That is the place where I looked first. 

The README file is really the place where I would have gone for most project to have a list of Known Issues. Or at lest a link to the known issues.

**Comment by dirkf** [comment]
Did you find the pinned issue not prominent enough?

Unfortunately, even client-side JS couldn't make it grab the user by the throat. The only way to make it more obvious would be to pin two more issues like this
```
<---- Look here ----
```
