### ISSUE TITLE
Youtube Unable to extract uploader id - NOT DUPLICATE

### ISSUE THREAD

**Issue by durian808** [ytdl-org/youtube-dl#32436]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
% /usr/local/bin/youtube-dl --verbose http://www.youtube.com/watch?v=B8qZ7QfKcjg
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.youtube.com/watch?v=B8qZ7QfKcjg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-693.11.6.el7.x86_64-x86_64-with-centos-7.9.2009-Core
[debug] exe versions: ffmpeg 3.4.12, ffprobe 3.4.12
[debug] Proxy map: {}
[youtube] B8qZ7QfKcjg: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I was getting another error with the current version of yt-download, so I installed from the nightly:

```
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```
This solved the error I was getting before, but introduced this new error, "Unable to extract uploader id".

**Comment by dirkf** [comment]
Really, read #30839 !

**Comment by durian808** [comment]
> Really, read #30839 ! Also, what you show is the main repo, not the nightly.

I installed as instructed "INSTALLAION" here: https://github.com/ytdl-org/ytdl-nightly

**Comment by dirkf** [comment]
Good point. My colleague who originally set this up didn't change those instructions and I didn't check them. Instead, use the [Releases page](https://github.com/ytdl-org/ytdl-nightly/releases) of the site.

**Comment by durian808** [comment]
ha ha... I just found that page by googling for nightly build install info, and found "youtube-dl from nightly build is suspicious?" #32042

Yeah, would be great to have a link to [Releases page](https://github.com/ytdl-org/ytdl-nightly/releases) at the top of each page of "Popular repositories".

thanks for all your work!

**Comment by dirkf** [comment]
Note that #32402 is talking about the **unofficial** nightly release which wasn't being updated when I last looked: one reason why the official one was created by forking it. Ofc any program including either release type is liable to be an antivirus false positive for reasons discussed in that issue.

**Comment by Vangelis66** [comment]
> Note that https://github.com/ytdl-org/youtube-dl/issues/32402 is talking about **the unofficial nightly release**

Is it _really_? 😄 

[How to properly add custom extractor?](https://github.com/ytdl-org/youtube-dl/issues/32402)

Actually, it is #32042 😜 ...

> thanks for all your work!

I second that! 👍

**Comment by durian808** [comment]
I am using https://github.com/ytdl-org/ytdl-nightly/releases/download/2023.07.13.334/youtube-dl

and it's working

**Comment by dirkf** [comment]
So I should hope!

**Comment by durian808** [comment]
Why not augment the youtube-dl error message to recommend update to latest version as first step, but if that fails to fix the error, update to latest nightly version (plus instructions)?  That would make things more efficient for the user as well as the developers.  In my case, I was running the current (master?) version and getting errors for a few weeks, and the -U update was telling me the software was up to date.  Then I started thinking, maybe I need to install a patched version or some other fixed version, and hence this thread.

**Comment by dirkf** [comment]
If that were possible, the program could have been fixed anyway. The current situation will be solved when #31585 is finally resolved.

**Comment by durian808** [comment]
What would prevent this same situation from arising in the future?  I.e. a bug needs to be fixed and the fix isn't included in the current official version, therefore weeks(?) go by with the bug affecting some or all users.  The change in the error message could be added right away.

**Comment by dirkf** [comment]
Typically we (currently, I, or the yt-dlp devs) fix critical issues within a day or two despite RL and now such fixes go into the nightly. When the project build system is fully working again there will also be new releases that update with `-U` as before and get distributed to other sources (_pip_, _apt_, etc).

**Comment by durian808** [comment]
OK, thanks.  When will the project build system be fully working again?  I only ask that because, if it will be months, then why not update the error message as an interim solution?

**Comment by dirkf** [comment]
It's been real soon now for some time. But the updating idea is a chicken-and-egg problem, as I said.

**Comment by durian808** [comment]
OK, I'll check back in a month and see how it's all going.  Thanks for your work!
