### ISSUE TITLE
Unable to extract uploade

### ISSUE THREAD

**Issue by Dinesh7be** [ytdl-org/youtube-dl#32430]
C:\Users\CW>youtube-dl.exe https://youtu.be/5axVgHHDBvU
[youtube] 5axVgHHDBvU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\CW>C:\Users\CW>youtube-dl.exe --verbose https://youtu.be/5axVgHHDBvU
'C:\Users\CW' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dirkf** [comment]
#30839 !
