### ISSUE TITLE
I tried to create a bot that uploads videos from YouTube, but I got this error

### ISSUE THREAD

**Issue by qodirbekz** [ytdl-org/youtube-dl#32432]
Exception has occurred: DownloadError
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

**Comment by dirkf** [comment]
#30839 !
