### ISSUE TITLE
Reporting bug.

### ISSUE THREAD

**Issue by CTICHARA** [ytdl-org/youtube-dl#32437]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: OSError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output

https://github.com/ytdl-org/youtube-dl/assets/130611758/5f1e1ce0-87df-4827-8ccf-81e272e71694


```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
#30839 ! Use the checklist (why is it there?) !

Also, one of the least helpful issue titles that can be imagined.
