### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by Thomas5636** [ytdl-org/youtube-dl#32438]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\Thomas Video Editing>youtube-dl "https://www.youtube.com/watch?t=4&v=BaW_jenozKc" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?t=4&v=BaW_jenozKc', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - Windows-10-10.0.19045-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] BaW_jenozKc: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Thomas Video Editing\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thomas Video Editing\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\Thomas Video Editing\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thomas Video Editing\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thomas Video Editing\AppData\Local\Programs\Python\Python311\Lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Python and command line interface not working. When I try and download any video it doesn't work and it crashes with the following output.

**Comment by gerib** [comment]
Same here on openSUSE Tumbleweed:
```
$ youtube-dl --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=8oYodfK4DkE --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--extract-audio', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=8oYodfK4DkE', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.4 (CPython) - Linux-6.3.9-1-default-x86_64-with-glibc2.37
[debug] exe versions: ffmpeg 5.1.3, ffprobe 5.1.3
[debug] Proxy map: {}
[youtube] 8oYodfK4DkE: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
return func(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
ie_result = ie.extract(url)
^^^^^^^^^^^^^^^
File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
ie_result = self._real_extract(url)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by 0NegrY0** [comment]
Same on Linux Mint 20.3
`youtube-dl --verbose --extract-audio "https://youtu.be/tDcmF7vPVH4"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--extract-audio', 'https://youtu.be/tDcmF7vPVH4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-152-generic-x86_64-with-glibc2.29
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] tDcmF7vPVH4: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1775, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by CaptainChicky** [comment]
The releases section is severely outdated. You need to compile it yourself (I don't even know why this isnt in the readme but w/e) as follows (skip steps as needed if you're already done with them prior):

1. Install the most recent Python version
    https://www.python.org/downloads/
(check the option to install pip as well and the option to add Python to your $PATH)
I have it installed in C:\Program Files and for all users


2. In an elevated command prompt run
    `python -m pip install --upgrade pyinstaller`


3. Download the youtube-dl source code
https://github.com/ytdl-org/youtube-dl/archive/master.zip
Extract to the folder youtube-dl-master.


4. Open a command prompt in the folder youtube-dl-master and run
    `pyinstaller.exe youtube_dl\__main__.py --onefile --name youtube-dl`

youtube-dl.exe can then be found in the newly created `/dist/` subdirectory.

It is this executable that you should use to run youtube-dl, not the 2021 version one. You should replace all of your old youtube-dl.exe's with this new executable you've generated in `/dist/`.

 Here are my logs for when i download the test video, comments in `<>`, and username is censored. Note that I have custum config settings but this doesn't matter on the general scope of the problem:

    C:\Users\*****>youtube-dl "https://www.youtube.com/watch?t=4&v=BaW_jenozKc" -v
    [debug] System config: []
    [debug] User config: [<my config settings>]
    [debug] Custom config: []
    [debug] Command-line args: ['https://www.youtube.com/watch?t=4&v=BaW_jenozKc', '-v']
    [debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
    [debug] youtube-dl version 2021.12.17 (single file build)              <NOTE it shows this older version, but the updated executable works in extraction>
    [debug] Python 3.9.2 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 - OpenSSL 1.1.1i  8 Dec 2020
    [debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev, ffprobe 5.1.2-full_build-www.gyan.dev
    [debug] Proxy map: {}

    [youtube] BaW_jenozKc: Downloading webpage
    [youtube] Downloading just video BaW_jenozKc because of --no-playlist
    [debug] [youtube] Decrypted nsig uFrUvRll4AqZOk0Noi => 5-13kbRfcJEaaA
    [debug] [youtube] Decrypted nsig w5N3_ueFfm3wBVum-s => Mt0kvgipUYwt7g
    [info] Writing video description to: C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.description
    [youtube] BaW_jenozKc: Downloading thumbnail ...
    [youtube] BaW_jenozKc: Writing thumbnail to: C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.jpg
    [debug] Invoking downloader on 'https://rr1---sn-5ghnugvob-2pus.googlevideo.com/videoplayback?expire=1689314233&ei=WI-wZLT3OZ7nir4Pq5yL4AI&ip=24.101.36.14&id=o-ABaLEBXgne-detO-appPGu0vv4Zvc7Dmtjn2iDO270qK&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-5ghnugvob-2pus%2Csn-vgqsrnz7&ms=au%2Crdu&mv=m&mvi=1&pl=19&initcwndbps=1195000&spc=Ul2Sq1mueo6IGv4u5h9HXDMCEs56U4I-eiQnlPxSOQ&vprv=1&svpuc=1&mime=video%2Fwebm&ns=mKMZH6BityvVz1ZABSjBBFIO&gir=yes&clen=988479&dur=9.833&lmt=1544741703689523&mt=1689292423&fvip=3&keepalive=yes&fexp=24007246%2C24362687&c=WEB&txp=5432432&n=5-13kbRfcJEaaA&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJhfoB6AGL5ElVmX2RWZ3ysam8vOlr-ra2Uc26tuWExUAiEAuBRPy8VcXVM7FmA9SG2kiPoWxGCuYlyXxGmhEtIa2hY%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANTkwrEXz1Z0MzScldBruQH8gSazP4yFTTjVtkU-_1vnAiAsNuyoxnfmD5BhvatMvc1hpRFf4HnFnEqwXxRx-uDkcg%3D%3D'
    [dashsegments] Total fragments: 1
    [download] Destination: C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.f248.webm
    [download] 100% of 965.31KiB in 00:00
    [debug] Invoking downloader on 'https://rr1---sn-5ghnugvob-2pus.googlevideo.com/videoplayback?expire=1689314233&ei=WI-wZLT3OZ7nir4Pq5yL4AI&ip=24.101.36.14&id=o-ABaLEBXgne-detO-appPGu0vv4Zvc7Dmtjn2iDO270qK&itag=140&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-5ghnugvob-2pus%2Csn-vgqsrnz7&ms=au%2Crdu&mv=m&mvi=1&pl=19&initcwndbps=1195000&spc=Ul2Sq1mueo6IGv4u5h9HXDMCEs56U4I-eiQnlPxSOQ&vprv=1&svpuc=1&mime=audio%2Fmp4&ns=mKMZH6BityvVz1ZABSjBBFIO&gir=yes&clen=160839&dur=9.891&lmt=1687568430431279&mt=1689292423&fvip=3&keepalive=yes&fexp=24007246%2C24362687&c=WEB&txp=1432434&n=5-13kbRfcJEaaA&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOvlqZDoxdR1Wq2GaeCwsQykBIV0O8v-OouTfmSj-k2WAiAic_8Tfr8xvdPwhIlsumaW9BICdynJHv7T9aCBVcXdsg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANTkwrEXz1Z0MzScldBruQH8gSazP4yFTTjVtkU-_1vnAiAsNuyoxnfmD5BhvatMvc1hpRFf4HnFnEqwXxRx-uDkcg%3D%3D'
    [dashsegments] Total fragments: 1
    [download] Destination: C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.f140.m4a
    [download] 100% of 157.07KiB in 00:00
    [ffmpeg] Merging formats into "C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.mkv"
    [debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.f248.webm" -i "file:C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.temp.mkv"
    Deleting original file C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.f248.webm (pass -k to keep)
    Deleting original file C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.f140.m4a (pass -k to keep)

**Comment by dirkf** [comment]
No you don't.

Read #30839 properly, OP and all commenters. OP should then have seen the **known issue** or found the relevant master issue by following the guidance on doing this:
>[x] I've searched the bugtracker for similar bug reports including closed ones
>
>[x] I've read bugs section in FAQ

And that section should be applied.

**Comment by ToubieObie** [comment]
> The releases section is severely outdated. You need to compile it yourself (I don't even know why this isnt in the readme but w/e) as follows (skip steps as needed if you're already done with them prior):
> 
> 1. Install the most recent Python version
>    https://www.python.org/downloads/
>    (check the option to install pip as well and the option to add Python to your $PATH)
>    I have it installed in C:\Program Files and for all users
> 2. In an elevated command prompt run
>    `python -m pip install --upgrade pyinstaller`
> 3. Download the youtube-dl source code
>    https://github.com/ytdl-org/youtube-dl/archive/master.zip
>    Extract to the folder youtube-dl-master.
> 4. Open a command prompt in the folder youtube-dl-master and run
>    `pyinstaller.exe youtube_dl\__main__.py --onefile --name youtube-dl`
> 
> youtube-dl.exe can then be found in the newly created `/dist/` subdirectory.
> 
> It is this executable that you should use to run youtube-dl, not the 2021 version one. You should replace all of your old youtube-dl.exe's with this new executable you've generated in `/dist/`.
> 
> Here are my logs for when i download the test video, comments in `<>`, and username is censored. Note that I have custum config settings but this doesn't matter on the general scope of the problem:
> 
> ```
> C:\Users\*****>youtube-dl "https://www.youtube.com/watch?t=4&v=BaW_jenozKc" -v
> [debug] System config: []
> [debug] User config: [<my config settings>]
> [debug] Custom config: []
> [debug] Command-line args: ['https://www.youtube.com/watch?t=4&v=BaW_jenozKc', '-v']
> [debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
> [debug] youtube-dl version 2021.12.17 (single file build)              <NOTE it shows this older version, but the updated executable works in extraction>
> [debug] Python 3.9.2 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 - OpenSSL 1.1.1i  8 Dec 2020
> [debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev, ffprobe 5.1.2-full_build-www.gyan.dev
> [debug] Proxy map: {}
> 
> [youtube] BaW_jenozKc: Downloading webpage
> [youtube] Downloading just video BaW_jenozKc because of --no-playlist
> [debug] [youtube] Decrypted nsig uFrUvRll4AqZOk0Noi => 5-13kbRfcJEaaA
> [debug] [youtube] Decrypted nsig w5N3_ueFfm3wBVum-s => Mt0kvgipUYwt7g
> [info] Writing video description to: C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.description
> [youtube] BaW_jenozKc: Downloading thumbnail ...
> [youtube] BaW_jenozKc: Writing thumbnail to: C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.jpg
> [debug] Invoking downloader on 'https://rr1---sn-5ghnugvob-2pus.googlevideo.com/videoplayback?expire=1689314233&ei=WI-wZLT3OZ7nir4Pq5yL4AI&ip=24.101.36.14&id=o-ABaLEBXgne-detO-appPGu0vv4Zvc7Dmtjn2iDO270qK&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-5ghnugvob-2pus%2Csn-vgqsrnz7&ms=au%2Crdu&mv=m&mvi=1&pl=19&initcwndbps=1195000&spc=Ul2Sq1mueo6IGv4u5h9HXDMCEs56U4I-eiQnlPxSOQ&vprv=1&svpuc=1&mime=video%2Fwebm&ns=mKMZH6BityvVz1ZABSjBBFIO&gir=yes&clen=988479&dur=9.833&lmt=1544741703689523&mt=1689292423&fvip=3&keepalive=yes&fexp=24007246%2C24362687&c=WEB&txp=5432432&n=5-13kbRfcJEaaA&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJhfoB6AGL5ElVmX2RWZ3ysam8vOlr-ra2Uc26tuWExUAiEAuBRPy8VcXVM7FmA9SG2kiPoWxGCuYlyXxGmhEtIa2hY%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANTkwrEXz1Z0MzScldBruQH8gSazP4yFTTjVtkU-_1vnAiAsNuyoxnfmD5BhvatMvc1hpRFf4HnFnEqwXxRx-uDkcg%3D%3D'
> [dashsegments] Total fragments: 1
> [download] Destination: C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.f248.webm
> [download] 100% of 965.31KiB in 00:00
> [debug] Invoking downloader on 'https://rr1---sn-5ghnugvob-2pus.googlevideo.com/videoplayback?expire=1689314233&ei=WI-wZLT3OZ7nir4Pq5yL4AI&ip=24.101.36.14&id=o-ABaLEBXgne-detO-appPGu0vv4Zvc7Dmtjn2iDO270qK&itag=140&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-5ghnugvob-2pus%2Csn-vgqsrnz7&ms=au%2Crdu&mv=m&mvi=1&pl=19&initcwndbps=1195000&spc=Ul2Sq1mueo6IGv4u5h9HXDMCEs56U4I-eiQnlPxSOQ&vprv=1&svpuc=1&mime=audio%2Fmp4&ns=mKMZH6BityvVz1ZABSjBBFIO&gir=yes&clen=160839&dur=9.891&lmt=1687568430431279&mt=1689292423&fvip=3&keepalive=yes&fexp=24007246%2C24362687&c=WEB&txp=1432434&n=5-13kbRfcJEaaA&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOvlqZDoxdR1Wq2GaeCwsQykBIV0O8v-OouTfmSj-k2WAiAic_8Tfr8xvdPwhIlsumaW9BICdynJHv7T9aCBVcXdsg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANTkwrEXz1Z0MzScldBruQH8gSazP4yFTTjVtkU-_1vnAiAsNuyoxnfmD5BhvatMvc1hpRFf4HnFnEqwXxRx-uDkcg%3D%3D'
> [dashsegments] Total fragments: 1
> [download] Destination: C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.f140.m4a
> [download] 100% of 157.07KiB in 00:00
> [ffmpeg] Merging formats into "C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.mkv"
> [debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.f248.webm" -i "file:C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.temp.mkv"
> Deleting original file C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.f248.webm (pass -k to keep)
> Deleting original file C:\Users\*****\Downloads\youtube-dl\Philipp_Hagemeister.UCLqxVugv74EIW3VWh2NOa3Q\20121002.youtube-dl_test_video_a_Y.BaW_jenozKc.f140.m4a (pass -k to keep)
> ```

Lifesaver 👑
