### ISSUE TITLE
inspect.getargspec() is removed in Python 3.11

### ISSUE THREAD

**Issue by MRWITEK** [ytdl-org/youtube-dl#32456]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Description

https://github.com/ytdl-org/youtube-dl/blob/47214e46d852e9d7ddf81d69a8e70806e2396c6c/youtube_dl/utils.py#L6250-L6253
causes
```
ERROR: module 'inspect' has no attribute 'getargspec'
```
because `inspect.getargspec()` is removed in Python 3.11 (see https://docs.python.org/3/whatsnew/3.11.html)
> Removed from the [inspect](https://docs.python.org/3/library/inspect.html#module-inspect) module:
  >  The getargspec() function, deprecated since Python 3.0; use [inspect.signature()](https://docs.python.org/3/library/inspect.html#inspect.signature) or [inspect.getfullargspec()](https://docs.python.org/3/library/inspect.html#inspect.getfullargspec) instead.

**Comment by dirkf** [comment]
Bother! Until it's fixed (ASAP, in tonight's nightly), use `python3.11 -O youtube-dl` to run the program, or `python3.11 -m youtube_dl ...` if installed as a module or running in a dev tree, or ofc Py <= 3.10.

**Comment by dirkf** [comment]
From the Python 3.11 `inspect` doc:
>Note that signature() and Signature Object provide the recommended API for callable introspection, and support additional behaviours (like positional-only arguments) that are sometimes encountered in extension module APIs. [inspect.getfullargspec] is retained primarily for use in code that needs to maintain compatibility with the Python 2 inspect module API.

Obviously that's the right way maintain compatibility with the Python 2 inspect module API **that has no `getfullargspec`** function!
