### ISSUE TITLE
[youtube] vzoqbjp1vf8: downloading webpage  error: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . make sure you are using the latest version; type  download -u  to update. be sure to call download with the --verbose flag and include its complete output.

### ISSUE THREAD

**Issue by ke080651** [ytdl-org/youtube-dl#32469]
## Checklist

- [x] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
#30839 !
