### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by surfx** [ytdl-org/youtube-dl#32463]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl -x --audio-format "mp3" --audio-quality 3 https://www.youtube.com/watch?v=euPkapq-ors -o "/home/.../download-yt/musicas/saida/%(title)s.%(ext)s" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '--audio-format', 'mp3', '--audio-quality', '3', 'https://www.youtube.com/watch?v=euPkapq-ors', '-o', '/home/.../download-yt/musicas/saida/%(title)s.%(ext)s', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-4.4.0-22621-Microsoft-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube] euPkapq-ors: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Tentando usar o `youtube-dl` tanto no windows como linux para fazer o download de um vídeo do youtube  e converter para mp3

```
$ youtube-dl -x --audio-format "mp3" --audio-quality 3 https://www.youtube.com/watch?v=euPkapq-ors -o "/home/.../download-yt/musicas/saida/%(title)s.%(ext)s" --verbose
```

![Captura de tela 2023-07-21 225046](https://github.com/ytdl-org/youtube-dl/assets/135773/934e1fa9-704b-494e-9143-c5453bd7243c)

**Comment by surfx** [comment]
Corrigido com:

Problemas - [t.ly/eJDkA](t.ly/eJDkA):

- `$ pip install git+https://github.com/ytdl-org/youtube-dl.git@master#egg=youtube_dl`

**Comment by dirkf** [comment]
Please follow #30839 to find definitive solutions for your issue (also complete the checklist). Unrelated sites like SO and Reddit aren't monitored and advice there may mislead (though maybe not in this case).

And, faz favor, post in English (and post text logs rather than screenshots). Even if I'm happy to exercise my very basic Portuguese, other contributors are more likely to be able to help. Use a web translator if necessary (include your original too).

**Comment by surfx** [comment]
> Please follow #30839 to find definitive solutions for your issue (also complete the checklist). Unrelated sites like SO and Reddit aren't monitored and advice there may mislead (though maybe not in this case).
> 
> And, faz favor, post in English (and post text logs rather than screenshots). Even if I'm happy to exercise my very basic Portuguese, other contributors are more likely to be able to help. Use a web translator if necessary (include your original too).

Agradeço os comentários

Jamais, se eu tive que aprender inglês, você tb pode aprender português. O mundo não gira ao entorno nesse idioma, adeus
#PAS #pt4ver

**Comment by dirkf** [comment]
At github.pt/ytdl-org or github.br/ytdl-org, if they existed, you should definitely post in (the appropriate version of) Portuguese only. Here, we ask contributors do some work to help themselves by using an online translator, asking a friend, or whatever, so that the issue is visible to the largest number of users, many of whom probably have at least good second language skills in English even if they don't understand some other language. G Translate suggests "nossa casa, nossas regras".

**Comment by surfx** [comment]
Acho que você não entendeu o conceito de "adeus" né? Só vou responder a este último comentário e posteriormente nunca mais terá um retorno. Ainda não sei se existe um block nessa plataforma.

Perdão madame, não sabia que você tinha criado o github sozinho. 

Não preciso usar o google tradutor (vergonha sua ter que usá-lo para entender meu texto). Seu você postar em inglês, português, alemão e até um pouco de italiano, conseguirei ler o seu texto.

Já está na hora de mudar essa "realidade" que você citou, não acha ? Vamos adotar o pt/BR, estou fazendo a minha parte. Jamais adotarei o inglês se não for do meu interesse. Sua opinião é irrelevante e acho qeu você deveria se resignar à sua insignificância, adeus
