### ISSUE TITLE
yt-dl error

### ISSUE THREAD

**Issue by royalhypeThT** [ytdl-org/youtube-dl#32474]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

when I used the youtube-dl command in cdm it gived me the following error ... 

ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

please tell me how to fix 
thanks for attention

**Comment by dirkf** [comment]
#30839 !

**Comment by royalhypeThT** [comment]
oh thanks
didnt saw that!

**Comment by dirkf** [comment]
GH doesn't allow the pinned issue font to be 120pt ...
