### ISSUE TITLE
When I download a Youtube video, does it count as a view?

### ISSUE THREAD

**Issue by Agent-E11** [ytdl-org/youtube-dl#32487]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

When I download a Youtube video, does it count as a view?

**Comment by dirkf** [comment]
Try it. I expect that only playing through the player JS in the YT page itself increments the count.

**Comment by alexisnsns** [comment]
Hello,

I've tried downloading 10 times the same video. For this test I used an old video with < 30 views so that I made sure that most probably no other person would be watching this video at the same time. 

The view count did not increase.

**Comment by dirkf** [comment]
Thx for the confirmation.
