### ISSUE TITLE
Exe file closing immediately and python file unrecognized/uninstallable

### ISSUE THREAD

**Issue by Fade-Revamped** [ytdl-org/youtube-dl#32483]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
I have no log since the exe closes immediately without any error messages
```

## Description

The exe file closes after about 5 seconds of being open, and for the brief period of time before it closes there's an error about not having the correct URL, even though I have yet to put one in (since the program closes before I can interact with it), and when I try to run the python version, Python does not recognize that I have the file at all, and pip installing does nothing. I am completely lost.

**Comment by dirkf** [comment]
If you have no log, you aren't running the program in a terminal window: https://github.com/ytdl-org/youtube-dl/issues/31948#issuecomment-1484779935.

Or you want a different program that embeds yt-dl in a GUI: #32120

>[x] I've searched the bugtracker for similar bug reports including closed ones

Really: https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+exe+file+closes+-label%3Aduplicate+in%3Atitle ?

**Comment by dirkf** [comment]
@Fade-Revamped ?

**Comment by Fade-Revamped** [comment]
I might be a bit slow, I didn't realize I had to run the exe through command line. My bad, thanks for showing me the post
