### ISSUE TITLE
--replace-in-metadata does not find '_' in title 

### ISSUE THREAD

**Issue by RalfReddings** [ytdl-org/youtube-dl#32493]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

--replace-in-metadata does not find '_' in title:
```
YT-Dlp https://youtu.be/60m_nfosEyI --restrict-filenames  --replace-in-metadata title "_" "space"
```
The above does not work. The file name still has `_` in it. I have tried the following which works:
```
YT-Dlp https://youtu.be/60m_nfosEyI --restrict-filenames  --replace-in-metadata title "Gui" "xxx"
```
Is this a bug?

**Comment by dirkf** [comment]
Who can say?

#30839: "if you were actually running yt-dlp ..."

My guess: the problem is that the `_` that you're trying to match is an artefact of `--restrict-filenames` and not an actual character in the `title` metadata field.
