### ISSUE TITLE
stoped working through 403 on all youtube links i tested

### ISSUE THREAD

**Issue by hazdo** [ytdl-org/youtube-dl#32506]
hello support i test it on banch of youtube links however i got link but once played i got 403

**Comment by aneniex** [comment]
youtube is broken

**Comment by dirkf** [comment]
#30839 ! Use the issue template !

**Comment by hazdo** [comment]
yeah i got your point mr dirkf so there seem no problem in script since it fetch m3u8 so i can not use the template to report however the link fetched if you try fetch with wget or via browser you got 403

**Comment by dirkf** [comment]
Try to reproduce the problem using the command line client. Review #30839.

yt-dlp users report 403 errors on media links but these have not yet been demonstrated for the links that yt-dl returns.

If you are not actually extracting the media links (eg, m3u8) with yt-dl, there's no reason to expect the links to be usable (eg, not 403). If you are, the links will expire.
