### ISSUE TITLE
Any plans to release new version?🤔

### ISSUE THREAD

**Issue by kloczek** [ytdl-org/youtube-dl#32512]
https://github.com/ytdl-org/youtube-dl/compare/2021.12.17...master  shows +280 commits since last release which was more than 1.5 years ago.
Any plans to release new version? 🤔

**Comment by dirkf** [comment]
#30839, #31585.

**Comment by kloczek** [comment]
Still no new release .. any update? 🤔

**Comment by kloczek** [comment]
gentle ping .. any update? 🤔

**Comment by dirkf** [comment]
Is the nightly build release (as linked from the previous response) unsatisfactory for you?

**Comment by kloczek** [comment]
Is it any problem to tag such release? 🤔

**Comment by dirkf** [comment]
The nightly releases are tagged but the automatic update uses the nightly repo. At some point I'll pull the build process back and tackle logging the 3 years of changes.

**Comment by kloczek** [comment]
Are you sure?
In the repo I see last tag 2021.12.17.

**Comment by dirkf** [comment]
I think I would know. You are perhaps not looking at the separate repo `yt-dl-nightly` where those builds are generated (whenever there's a change in the `master` branch of the main repo.

**Comment by kloczek** [comment]
So this is not primary repo? 🤔

**Comment by dirkf** [comment]
No, it's just not the nightly release repo, which is where (for now) you should go for up-to-date, but not "officially stable" builds.
