### ISSUE TITLE
Password protected Vimeo showcases

### ISSUE THREAD

**Issue by giannoxs** [ytdl-org/youtube-dl#32515]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is it not possible to download password protected Vimeo showcases without knowing the password? If yes, how? I heard it was possible with this tool.

**Comment by alexisnsns** [comment]
Hello,

Could you include the full output of youtube-dl ?

**Comment by giannoxs** [comment]
I just want to know if It is possible, I don't have to put an output, I see that tgere is the command to put the password, but I don't have the password.

**Comment by giannoxs** [comment]
I just want to know if It is possible, I don't have to put an output, I see that tgere is the command to put the password, but I don't have the password.

**Comment by 1268** [comment]
I coded this before, so assuming is the same process yes its pretty straight forward. but as the other user mentioned, unless you can provide an example URL, AND credentials, this issue is likely just gonna sit on the pile with the rest for many years. so ball is in your court buddy.

**Comment by giannoxs** [comment]
Yeah sure, this is example of link, https://vimeo.com/showcase/10117731, no I don't have the password. So cannot I access?

**Comment by giannoxs** [comment]
Yeah sure, this is example of link, https://vimeo.com/showcase/10117731, no I don't have the password. So cannot I access?

**Comment by giannoxs** [comment]
Yeah sure, this is example of link, https://vimeo.com/showcase/10117731, no I don't have the password. So cannot I access?

**Comment by dirkf** [comment]
Isn't that the point of the password?

If you magically ascertained the Vimeo ID of the video you could use `https://player.vimeo.com/video/{vimeo_id}`, but, unsurprisingly, it isn't `10117731`.

**Comment by giannoxs** [comment]
yeah I Don't know video IDs inside the showcase. I just askes cause u can download password protected videos with this app, but not showcases.

**Comment by giannoxs** [comment]
yeah I Don't know video IDs inside the showcase. I just askes cause u can download password protected videos with this app, but not showcases.

**Comment by 1268** [comment]
OK, I am done here. any current YouTube-DL Vimeo abilities regarding passworded videos are going to REQUIRE THE PASSWORD. why would you think it would be possible to download these without a password?

**Comment by giannoxs** [comment]
closed

**Comment by dirkf** [comment]
This is the missing log:
```console
$ ./youtube-dl-20230718 -v -F 'https://vimeo.com/showcase/10117731'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://vimeo.com/showcase/10117731']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2023.07.18 [47214e46d] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 2.7.18 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial - OpenSSL 1.1.1u  30 May 2023 - glibc 2.15
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[vimeo:album] 10117731: Downloading JSON metadata
[vimeo:album] 10117731: Downloading JSON metadata
ERROR: This album is protected by a password, use the --video-password option
Traceback (most recent call last):
  File "./youtube-dl-20230718/youtube_dl/YoutubeDL.py", line 866, in wrapper
    return func(self, *args, **kwargs)
  File "./youtube-dl-20230718/youtube_dl/YoutubeDL.py", line 962, in __extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl-20230718/youtube_dl/extractor/common.py", line 535, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl-20230718/youtube_dl/extractor/vimeo.py", line 999, in _real_extract
    expected=True)
ExtractorError: This album is protected by a password, use the --video-password option

$
