### ISSUE TITLE
Problem z Biblioteka youtube-dl

### ISSUE THREAD

**Issue by Paladyn102** [ytdl-org/youtube-dl#32510]
Gdy chce puścić jakąś muzyke na discordzie (!play (link youtube)) wyskakuje

Wystąpił błąd podczas odtwarzania: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

a w wierszu poleceń napisałem (python.exe -m pip install --upgrade pip)

C:\Users\JA>python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\site-packages (23.0.1)
Collecting pip
  Downloading pip-23.2.1-py3-none-any.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 2.5 MB/s eta 0:00:00
Installing collected packages: pip
  WARNING: The scripts pip.exe, pip3.10.exe and pip3.exe are installed in 'C:\Users\JA\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-23.2.1

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: C:\Users\JA\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

C:\Users\JA>

problem jest ciągle taki sam jak mam to naprawić?

**Comment by dirkf** [comment]
#30839 ! Use the issue template (użyj formularza szablonu problemu) !

Postępuj zgodnie z procedurą raportowania, która pomoże ci zidentyfikować rozwiązany problem. Wyrażenie problemu również w języku angielskim, w razie potrzeby za pomocą tłumacza online, aby uzyskać jak najwięcej pomocy -- tak jak ja tutaj.

You shouldn't need to upgrade (nie musisz aktualizować) _pip_.
