### ISSUE TITLE
ERROR: Unable to download video

### ISSUE THREAD

**Issue by GrodzGit** [ytdl-org/youtube-dl#32525]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I receive this error when trying to download a video:

Error while retrieving info on video with URL https://www.youtube.com/shorts/OsNWkRTu570 with the following message: Error: Command failed with EACCES: node_modules/youtube-dl/bin/youtube-dl -i -o video/%(title)s.mp4 --write-info-json -f bestvideo+bestaudio --merge-output-format mp4 --write-thumbnail --no-clean-info-json -j --dump-json https://www.youtube.com/shorts/OsNWkRTu570 spawn node_modules/youtube-dl/bin/youtube-dl EACCES

I've tried reinstalling, but that doesn't help.

**Comment by dirkf** [comment]
You're reporting an error, not asking a question. Complete the appropriate template (not as incomplete above) and provide the required information. Either edit the original post or close this and open a new issue.

**Comment by RTUnit** [comment]
@GrodzGit, this helped me to overcome the issue with EACCES:
chmod +x /YoutubeDL-Material/backend/node_modules/youtube-dl/bin/youtube-dl

I have installed from another repo (https://github.com/Tzahi12345/YoutubeDL-Material) in a docker container and faced the same issue, hence was googling around and found this. Hope it helps.

**Comment by dirkf** [comment]
This sounds plausible but if that was OP's problem it would be an issue for the YoutubeDL-Material tracker.

**Comment by yorkane** [comment]
> @GrodzGit, this helped me to overcome the issue with EACCES: chmod +x /YoutubeDL-Material/backend/node_modules/youtube-dl/bin/youtube-dl
> 
> I have installed from another repo (https://github.com/Tzahi12345/YoutubeDL-Material) in a docker container and faced the same issue, hence was googling around and found this. Hope it helps.

solved my issue too, lol
