### ISSUE TITLE
hola quiero descargar youtube dl en mi macbook pro como lo hago?

### ISSUE THREAD

**Issue by Magnet88** [ytdl-org/youtube-dl#32526]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by dirkf** [comment]
[Leer aquí/read here](https://github.com/ytdl-org/youtube-dl) y/and [aquí/here](https://github.com/ytdl-org/youtube-dl/issues/30839).
