### ISSUE TITLE
The Nightly repo isn't getting new releases

### ISSUE THREAD

**Issue by gamer191** [ytdl-org/youtube-dl#32529]
https://github.com/ytdl-org/ytdl-nightly is not getting new releases, because the `rebase on upstream` action keeps skipping building (see https://github.com/ytdl-org/ytdl-nightly/actions/runs/5970822982, for example)

Also, the latest build doesn't include the latest commit, see https://github.com/ytdl-org/ytdl-nightly/tree/2023.08.07

Also, out of interest, given the nightly builds already exist, what's blocking a regular release?

**Comment by dirkf** [comment]
The yt-dl nightly update now only builds if rebasing from here changes the HEAD, but some git f***ery (or the author's understanding of it) is causing the nightly-specific commits to be replayed over the rebased changes and thus failing the check.

> ... what's blocking a regular release?

Getting that to work as well, especially since the nightly builds are now supposed to be working.

**Comment by gamer191** [comment]
> The yt-dl nightly update now only builds if rebasing from here changes the HEAD, but some git f***ery (or the author's understanding of it) is causing the nightly-specific commits to be replayed over the rebased changes and thus failing the check.

That's what rebasing does, but the HEAD still changes. In fact, the check passed last time there was a new commit (https://github.com/ytdl-org/ytdl-nightly/actions/runs/5780118509).

The issue, in that case, is just that it's checking out the wrong commit. The logs say it's checking out master though (followed by `d9e081ed4b1177e573e52fda785c337800b740`, which was the head prior to the rebase).
![image](https://github.com/ytdl-org/youtube-dl/assets/83270075/fe013c21-3f32-4f91-94dc-4271872652e7)

Perhaps the real issue is some sort of delay on Github's side that's causing the rebase action to finish locally before it finishes remotely, thus causing the github action to move on before the rebase is finished, and hence causing it to checkout the wrong branch

**Comment by dirkf** [comment]
The `checkout` action in the build workflow may default to checking out the commit in the `GITHUB_SHA` environment value, set when the rebase action was launched. Let's see what happens when it's explicitly told to check out the current `HEAD`.

**Comment by fmonts** [comment]
I tried to build it myself from master, I did:

```
git clone https://github.com/ytdl-org/ytdl-nightly/
apt install pandoc #needed by the install
make install
```

But now if I do:
`/usr/local/bin/youtube-dl --version
`
it says `2021.12.17`... 
how can we build it?

**Comment by dirkf** [comment]
The version data is set in `version.py` by the nightly build workflow. You have to edit it by hand.

The workflow should commit the updated file with the appropriate tag, but perhaps that isn't happening.

**Comment by dirkf** [comment]
I've tweaked various bits of workflow and conflicts that resulted in a successful build and release last night. The nightly repo now has a release branch that contains the version used for the release.

**Comment by dirkf** [comment]
The rebasing action inherited from yt-dl-patched has been replaced by a home-grown version. The difference is that new commits from youtube-dl/master are replayed onto the end of the ytdl-nightly/master commits while unchanged commits specific to ytdl-nightly/master are undisturbed.

Apparently this is now not generating the release branch but I'm sure it will again after it's been roughed up a bit.

**Comment by dirkf** [comment]
This seems to be working now.
