### ISSUE TITLE
I'm not able to download facebook video , all though I'm able to download the youtube videos with the same command

### ISSUE THREAD

**Issue by manthandalwadi17** [ytdl-org/youtube-dl#32527]
I'm facing this issue while try to download the facebook videos, I already checked that i'm using the latest version.

ERROR: [facebook] 971257200757533: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by dirkf** [comment]
#30839: "... if you were actually using _yt-dlp_ ..."
