### ISSUE TITLE
error using any command

### ISSUE THREAD

**Issue by kokj1** [ytdl-org/youtube-dl#32521]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
anytime i at all interact with youtube-dl it prints the following error:

/usr/local/bin/youtube-dl: line 1: syntax error near unexpected token `newline'
/usr/local/bin/youtube-dl: line 1: `<h1>Access denied</h1>'

help much appreciated

also forgot to mention, I CAN"T VERIFY WHICH VERSION I AM RUNNING BECAUSE

**Comment by dirkf** [comment]
Paste the relevant section of your terminal log including the output of the command `uname -a`. This is almost certainly a problem with your environment and not with your yt-dl. Also explain how your yt-dl was installed.

**Comment by kokj1** [comment]
uname -a output:
Linux debian82vg 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux

i installed youtube-dl by the way listed on the github page, using the commands:
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

again, output by trying to use it is:
/usr/local/bin/youtube-dl: line 1: syntax error near unexpected token `newline'
/usr/local/bin/youtube-dl: line 1: `<h1>Access denied</h1>'

**Comment by dirkf** [comment]
See #32495 for explanation and solution.
