### ISSUE TITLE
Ignore channels from the input list 

### ISSUE THREAD

**Issue by snwefly** [ytdl-org/youtube-dl#32530]
When you use -a list.txt is there any way to ignore all the channels from downloading?

Example list 
```
https://www.youtube.com/
https://www.youtube.com/c/dummyname
https://www.youtube.com/@dummyname
https://www.youtube.com/user/dummyname
https://www.youtube.com/channel/UCaabbcc
https://www.youtube.com/playlist?list=PLxyz
https://www.youtube.com/watch?v=12345678901
https://www.youtube.com/watch?v=abc12345678
https://www.youtube.com/watch?v= ...
https://www.youtube.com/watch?v=xyz12345678
``` 
I like to ignore these from downloading

```
https://www.youtube.com/
https://www.youtube.com/c/dummyname
https://www.youtube.com/@dummyname
https://www.youtube.com/user/dummyname
https://www.youtube.com/channel/UCaabbcc
``` 

Thanks

**Comment by dirkf** [comment]
This use-case sounds strange. Plainly you could edit your original batch list to make a temporary list without the unwanted items, so I suppose you have some case where there are multiple batch lists and/or unwanted item sets. Some more background could help.

You could use a script-based solution, either with a shell script appropriate to your OS shell environment, or using a Python script to invoke yt-dl as a module. For instance, _grep_ (Windows: _findstr_) could filter out unwanted items according to a regular expression.

You could also use `--match-filter ...` to exclude videos according to certain criteria, but that only affects the download phase: the extraction phase still has to be executed to establish the values to be matched/excluded.

**Comment by dirkf** [comment]
Closed here too.
