### ISSUE TITLE
Due to a [ruling](https://openjur.de/u/2466945.html) of the Hamburg Regional Court, access to this website is blocked.

### ISSUE THREAD

**Issue by WGroleau** [ytdl-org/youtube-dl#32536]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ  --? not sure where that is

## Verbose log

```
WGroleau@MBP TEMP % youtube-dl  --keep-fragments --verbose https://youtu.be/RYYQnUFgHsQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--keep-fragments', '--verbose', 'https://youtu.be/RYYQnUFgHsQ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.13 (CPython) - macOS-13.5.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] RYYQnUFgHsQ: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[subsequent output skipped]
```
## Description

The embedded advice, as well as the issues "chooser" directs us to https://yt-dl.org/bug which is no longer available:
Access denied
Due to a [ruling](https://openjur.de/u/2466945.html) of the Hamburg Regional Court, access to this website is blocked.
Zugriff gesperrt
Aufgrund eines [Urteils](https://openjur.de/u/2466945.html) des Landgerichts Hamburg ist der Zugriff auf diese Website gesperrt.

**Comment by dirkf** [comment]
#32495
