### ISSUE TITLE
BadStatusLine

### ISSUE THREAD

**Issue by MysticMerlin** [ytdl-org/youtube-dl#32548]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\User\Videos\youtube-dl Downloads>youtube-dl https://www.itv.com/watch/emmerdale/Ya0524/1a8694a9772 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.itv.com/watch/emmerdale/Ya0524/1a8694a9772', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-109856-gf8d6d0fbf1-20230213, ffprobe 2023-02-13-git-2296078397-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] 1a8694a9772: Requesting header
WARNING: Could not send HEAD request to https://www.itv.com/watch/emmerdale/Ya0524/1a8694a9772: ''
[generic] 1a8694a9772: Downloading webpage
ERROR: Unable to download webpage: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug.
Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\utils.py", line 2737, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1186, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1227, in getresponse
  File "C:\Python\Python34\lib\http\client.py", line 386, in begin
  File "C:\Python\Python34\lib\http\client.py", line 356, in _read_status


C:\Users\User\Videos\youtube-dl Downloads>
```

## Description
I've had the BadStatusLine error most of the time since 07/07/2023 until now 08/09/2023 with sometimes the Unable to Extract Params error which I don't get at the mo probably because I get the BadStatusLine error. I'm running the latest version of the software etc as can be seen in the above verbose. Since 07/07/2023 I've been checking on updates etc to the software including the Nightly Builds but that hasn't been worked on for a while. This error occurs whatever I try to download from the ITVX site but I've used the following because for one it is available for about 28days. With last years problem with the ITVX site from 17/11/2023 until I got a working software about 04/02/2023 & now this for the last 2 months it means that I've only had the software working properly for 5 months out of 10 months. So, I'm at a loss what I should do or where to start to correct the error. I'm using the same Wi-Fi now as I have been for at least 3yrs.
This is the line command that I'm using.

youtube-dl https://www.itv.com/watch/emmerdale/Ya0524/1a8694a9772

Thank you.
-->

**Comment by dirkf** [comment]
It's the same situation as #32415.
