### ISSUE TITLE
Unable to download .exe

### ISSUE THREAD

**Issue by RiskfreeDraenor** [ytdl-org/youtube-dl#32541]
Hey i just wanted to know what was going on with the windows donwload of youtbe-dl. from the link in this page to download it i get a screen like this:

Access denied

Due to a [ruling](https://openjur.de/u/2466945.html) of the Hamburg Regional Court, access to this website is blocked.

any ideas? (also vpn DO NOT HELP) tryed.

**Comment by dirkf** [comment]
#30839 !

... would lead to #32495.
