### ISSUE TITLE
403: Forbidden while downloading YouTube videos

### ISSUE THREAD

**Issue by arunkumaraqm** [ytdl-org/youtube-dl#32542]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v https://www.youtube.com/watch?v=rsUTtpb3k-w
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=rsUTtpb3k-w']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.5 (CPython) - Linux-5.15.0-79-generic-x86_64-with-glibc2.10
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {}
[youtube] rsUTtpb3k-w: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description
I haven't been able to download any YouTube videos for close to two months because of 403 error. youtube-dl does seem to work 1% of the time though. (I don't mean it works for a particular video(s))

WRITE DESCRIPTION HERE

**Comment by khansaad1275** [comment]
> ## Checklist
> * [x]  I'm reporting a broken site support
> * [x]  I've verified that I'm running youtube-dl version **2021.12.17**
> * [x]  I've checked that all provided URLs are alive and playable in a browser
> * [x]  I've checked that all URLs and arguments with special characters are properly quoted or escaped
> * [x]  I've searched the bugtracker for similar issues including closed ones
> 
> ## Verbose log
> ```
> $ youtube-dl -v https://www.youtube.com/watch?v=rsUTtpb3k-w
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=rsUTtpb3k-w']
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
> [debug] youtube-dl version 2021.12.17
> [debug] Python version 3.8.5 (CPython) - Linux-5.15.0-79-generic-x86_64-with-glibc2.10
> [debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
> [debug] Proxy map: {}
> [youtube] rsUTtpb3k-w: Downloading webpage
> ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
>     return func(self, *args, **kwargs)
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
>     ie_result = ie.extract(url)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
>     ie_result = self._real_extract(url)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
>     'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
>     raise RegexNotFoundError('Unable to extract %s' % _name)
> youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> ```
> 
> ## Description
> I haven't been able to download any YouTube videos for close to two months because of 403 error. youtube-dl does seem to work 1% of the time though. (I don't mean it works for a particular video(s))
> 
> WRITE DESCRIPTION HERE

They have actually posted a lot about this, like how to change few lines in your code to make it work, but i made tools based on yt-dlp and yotube dl and now I don't wanna write code to change these few lines in people who are using my tools 🥲. 

So if someone have a fork that is working then it will be extremely helpful.

**Comment by dirkf** [comment]
Where is this 403 error in the log? The log shows a known solved problem listed in #30839.

**Comment by latel** [comment]
oh you are using an outed version 2021.12.17

**Comment by dirkf** [comment]
Obviously the version of the program that you are using in your tool is failing.

>... I don't know much about YouTube dl.

Probably best to fix that if you are maintaining a tool that uses it.

Read #30839, #31530, #31585 to start. Also #32499 may be relevant.

**Comment by latel** [comment]
> > oh you are using an outed version 2021.12.17, check out #30839
> 
> What are you guys talking about? If you check my repos there is a tool called Termux-YTD. I wanna fix it, but I see no helpful replies. I am sorry I don't know much about YouTube dl.
> 
> Please help

just use https://github.com/yt-dlp/yt-dlp, an youtube-dl fork

**Comment by Mart-Bogdan** [comment]
> Where is this 403 error in the log? The log shows a known solved problem listed in #30839.

How so it is fixed? it's not even #30839 as you pointed, but #31530 and it is not marked as solved.

and it definitely happend for me on latest version just now (with this URL https://youtu.be/FKv8NqgD51E?si=lyR5REGteiunQSvL )

duplicate #31530

**Comment by Mart-Bogdan** [comment]
version **2021.12.17** is latest one published, according to github tags.

**Comment by dirkf** [comment]
Read #30839 properly and it solves your (@Mart-Bogdan) problem including https://github.com/ytdl-org/youtube-dl/issues/32542#issuecomment-1732407273 and 
https://github.com/ytdl-org/youtube-dl/issues/32542#issuecomment-1732407526 which indicate that you didn't do so before.

This is irrelevant to OP's stated issue, unlike OP's log.

**Comment by dhyanKaro** [comment]
me 2
