### ISSUE TITLE
latest version of yt-uploader is not working   unable to extract uploader id;

### ISSUE THREAD

**Issue by mdale** [ytdl-org/youtube-dl#32545]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

It appears latest version of yt-uploader is not working or not able to pull from youtube? 

```
youtube-dl --get-filename -o '%(title)s.%(ext)s' BaW_jenozKc --restrict-filenames
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar questions including closed ones

Review #30839 as asked.
