### ISSUE TITLE
README and other files need to be updated in light of Hamburg court ruling

### ISSUE THREAD

**Issue by jrbray1** [ytdl-org/youtube-dl#32569]
The README here, (and I guess many other files) refers to site https://yt-dl.org/ which has been blocked due to a court ruling. If there is an alternative site, can it be used instead

**Comment by nicolaasjan** [comment]
See also:
https://github.com/ytdl-org/youtube-dl/issues/32495

**Comment by dirkf** [comment]
In fact, duplicate of that. If the Germans can't control themselves, the next actual release will be fully hosted on GH.

**Comment by jrbray1** [comment]
I really think you need to explain what's going on, and why software which is getting regular commits only mentions a formal release 2 years ago.

**Comment by dirkf** [comment]
#31585.
