### ISSUE TITLE
Vimeo private video : Failed to parse JSON

### ISSUE THREAD

**Issue by christiganc** [ytdl-org/youtube-dl#32567]
## Checklist
- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17** I also tried the latest nightly (verbose log below)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones (I've seen an other issue but it is not the same error)

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vimeo.com/***', '--referer', 'https://vimeo.com/', '--video-password', 'PRIVATE', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2023.09.07 [66ab0814c] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 3.4.4 (CPython AMD64 32bit) - Windows-10-10.0.19041 - OpenSSL 1.0.2d 9 Jul 2015
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo] 864736456: Downloading webpage
[vimeo] 864736456: Downloading JSON metadata
ERROR: 864736456: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 937, in _parse_json
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\json\__init__.py", line 318, in loads
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\json\decoder.py", line 343, in decode
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 937, in _parse_json
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\json\__init__.py", line 318, in loads
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\json\decoder.py", line 343, in decode
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\YoutubeDL.py", line 863, in wrapper
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\YoutubeDL.py", line 959, in __extract_info
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 565, in extract
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\vimeo.py", line 719, in _real_extract
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\vimeo.py", line 607, in _extract_from_api
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 930, in _download_json
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 914, in _download_json_handle
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 941, in _parse_json
youtube_dl.utils.ExtractorError: 864736456: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hello, 
I changed the url in the log because it is a private video.
I used youtube-dl a lot to download replays from courses that I paid but do not allow to download the videos... they set up a limit of 10 days to watch the replay. Well, I don't necessarly have the time to watch it before the video gets deleted.
Last course was last year and it worked great : I could download it via youtube-dl. Now I can't anymore, I think Vimeo has changed the way they stream the videos ? Before using youtube-dl, I could always search within the source code and find the url of the video, I can't anymore.

Thank you

**Comment by dirkf** [comment]
>[x] I've searched the bugtracker for similar issues including closed ones (I've seen an other issue but it is not the same error)

Which one? I expect that the fix for #32271 will also fix this, and that the slightly different error message is down to Python 2 vs 3.

**Comment by christiganc** [comment]
> > [x] I've searched the bugtracker for similar issues including closed ones (I've seen an other issue but it is not the same error)
> 
> Which one? I expect that the fix for #32271 will also fix this, and that the slightly different error message is down to Python 2 vs 3.

Yep that's the one ! How to apply the patch ? Do I have to build a new version ?

**Comment by christiganc** [comment]
I tried the regex modification, still the same error

**Comment by dirkf** [comment]
Looking more closely, this error is in a different place and wouldn't be affected by the patch for #32271. Thanks for the test.

So something else is happening. From the log here, the page is not password-protected, does not have an unlisted hash, and is not a `player.vimeo.com` URL. The page is downloaded OK but the JSON download from, I think, the `config_url` found in the page is empty. 

What happens if you omit the `--referer ...` from the command-line?

If that makes no difference, to progress this further, you would have to provide details of the problem video, or reproduce the issue with a public video, or log the session with `--write-pages` and manually redact the results before uploading.

**Comment by 1268** [comment]
as was mentioned already, need a password to continue.

**Comment by hodgepodge73** [comment]
Hi, I tried replicating this bug with the following link https://vimeo.com/876887878 with all other command line args the same. The download worked for me perfectly. The video is a public video that can only be accessed via the video password (different from a private video where only the account owner can see it). Please let me know if this is the same setup you are using and if using the link I sent works. Also my premium account will expire in 7 days.

**Comment by dirkf** [comment]
That works with, eg, the 20230925 nightly, but doesn't obviously repro the original issue.

OP will have to communicate the details of a failing example to progress the issue.

**Comment by 3052** [comment]
password has been repeatedly requested, and over a month has gone by. I say close the issue, and someone can post a new one, if they actually have credentials.

**Comment by christiganc** [comment]
Hey guys,

Sorry for the delay, I moved and I couln't get internet in my new house. Now I am settled.

So, first, as I told you earlier I won't give you the password for that video. Of course I have the credentials, but it is a private video, right? I can assure you that video works well when I am watching it directly on vimeo. I can give you more details on the password and url of the video in private of course.

So...

I tested again today, I don't get the same error.

`[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 10 of 10)...
ERROR: giving up after 10 fragment retries`

**Comment by 3052** [comment]
you keep commenting like its going to change anything. if you want to keep hiding the password thats your choice, but dont be surprised if the issue is still open in exact the same state 4 years from now. just look at the other 3000 open issues and see for yourself:

https://github.com/ytdl-org/youtube-dl/issues

if you want the issue solved, then give people a problem that is actionable. I am able and willing to code a solution for this today. but I am not going to go through the trouble of setting up my own private Vimeo video just to do it. that is the job of the issue poster.

**Comment by christiganc** [comment]
Lol you don't even read completely what others write, do you?
I just told you that I can give the credentials in private.
You don't have to be rude, I gave all the information I could.
I won't bother you anymore, closing this issue.

**Comment by 3052** [comment]
> I just told you that I can give the credentials in private.

OK, did you do it? I dont see anything in my private boxes. how many times did you want me to ask for it? saying you can do something is different from you doing it. I guess its like they say:

https://wiktionary.org/wiki/you_can_lead_a_horse_to_water,_but_you_can't_make_it_drink

**Comment by dirkf** [comment]
The 403 error on fragments might be solved by choosing a different format (of which Vimeo offers **many**), if it's actually #32409, and then we can declare the original issue here fully sorted.
