### ISSUE TITLE
Unable to extract uploader id when downloading Youtube from Australia

### ISSUE THREAD

**Issue by agenkin** [ytdl-org/youtube-dl#32563]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=7E-cwdnsiow', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 4afb8e560
[debug] Python version 3.10.10 (CPython) - macOS-13.5.2-arm64-arm-64bit
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] 7E-cwdnsiow: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

An attempt to download Youtube video throws an error saying "Unable to extract uploader id"

Btw, error msg says to report the bug to https://yt-dl.org/bug, which is blocked at least from Australia: "Due to a [ruling](https://openjur.de/u/2466945.html) of the Hamburg Regional Court, access to this website is blocked.". I suggest to change to direct link to Github Issues.

**Comment by agenkin** [comment]
Found answer in FAQ

**Comment by arivictor** [comment]
Any change you could paste what the answer was or a link to it?

**Comment by mcsilver** [comment]
> Any change you could paste what the answer was or a link to it?

The only references in the FAQ did not help me.

**Comment by ChiefBreakeverything** [comment]
I'm getting this today too and the FAQ doesn't really mention it. But the download appears to start anyway? How bizarre.

**Comment by arivictor** [comment]
I followed this solution: https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435477247

**Comment by mcsilver** [comment]
Yeah, I was able to download the [nightly build](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases) of `yt-dlp.exe` and then use `-U` to update. Thank you.
