### ISSUE TITLE
Ceska televize download

### ISSUE THREAD

**Issue by jbelvoncik** [ytdl-org/youtube-dl#32584]
youtube-dl --verbose https://www.ceskatelevize.cz/porady/10122978233-udalosti-v-regionech-ostrava/423231100030920/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.ceskatelevize.cz/porady/10122978233-udalosti-v-regionech-ostrava/423231100030920/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: affc4c01a
[debug] Python version 3.12.0 (CPython) - macOS-14.0-arm64-arm-64bit
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[CeskaTelevizePorady] 423231100030920: Downloading webpage
ERROR: Unable to extract iframe player url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/extractor/ceskatelevize.py", line 282, in _real_extract
    data_url = update_url_query(unescapeHTML(self._search_regex(
                                             ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.12/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract iframe player url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
All the versions I have, and _yt-dlp_, give the same error as #31922:
```console
[CeskaTelevize] Extracting URL: https://www.ceskatelevize.cz/porady/10122978233-udalosti-v-regionech-ostrava/423231100030920/
[CeskaTelevize] 423231100030920: Downloading webpage
[CeskaTelevize] 423231100030920: Getting IFRAME hash
ERROR: [CeskaTelevize] 423231100030920: Unable to download webpage: HTTP Error 404: Not Found ...
```

Maybe you are being served a different page, a captcha or similar. Please follow #31922 and test again when that's fixed.
