### ISSUE TITLE
Can't access yt-dl.org

### ISSUE THREAD

**Issue by blakemcbride** [ytdl-org/youtube-dl#32585]
## Checklist

- [ X] I'm reporting a broken site support
- [  ] I've verified that I'm running youtube-dl version **2021.12.17**
- [  ] I've checked that all provided URLs are alive and playable in a browser
- [  ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [  ] I've searched the bugtracker for similar issues including closed ones

## Description

I cannot download your distribution from the United States.  When I try to access yt-dl.org I get:
```
Access denied
Due to a [ruling](https://openjur.de/u/2466945.html) of the Hamburg Regional Court, access to this website is blocked.

Zugriff gesperrt
Aufgrund eines [Urteils](https://openjur.de/u/2466945.html) des Landgerichts Hamburg ist der Zugriff auf diese Website gesperrt.
```
However, I did notice that I can download and run the code from `https://github.com/ytdl-org/youtube-dl`

If you can't get past the block, I suggest you update your documentation and make an easy way to install it from the Git clone.

Thanks!

**Comment by dirkf** [comment]
>[ ] I've searched the bugtracker for similar issues including closed ones

Why do you suppose this is in the template?

**Comment by blakemcbride** [comment]
[ ] means not checked

[X] means checked

**Comment by nicolaasjan** [comment]
Searching the issues for `Hamburg` would have brought you to #32495.
