### ISSUE TITLE
Unable to Download playlists! Incomplete Data Received & [Errno 2]

### ISSUE THREAD

**Issue by GollumArain** [ytdl-org/youtube-dl#32590]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Downloading a single video works effortlessly but I'm unable to download playlists. I'm using YT-DLP with a bot hosted on a VPS. It fetches incomplete data as can be seen below, retries and after 3 tries it simply gives Error related to directory of file, which is not correct, because downloading single files, to the same directory works fine.

NOOB ALERT

app_1  | 2023-10-10 07:51:15,680 - bot - INFO - Downloading with YT-DLP: https://www.youtube.com/playlist?list=PLBsP89CPrMePNK7yIxcyRdiIFentQVHra
app_1  | 2023-10-10 07:51:16,282 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Retrying (1/3)...
app_1  | 2023-10-10 07:51:19,327 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Retrying (2/3)...
app_1  | 2023-10-10 07:51:22,377 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Retrying (3/3)...
app_1  | 2023-10-10 07:51:25,427 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Giving up after 3 retries
app_1  | 2023-10-10 07:51:37,167 - bot - INFO - Checking File/Folder if already in Drive: MKBHD Interviews!
app_1  | 2023-10-10 07:51:37,169 - bot.helper.mirror_utils.gdrive_utlis.helper - INFO - Authorizing with 15.json service account
app_1  | 2023-10-10 07:51:37,556 - bot.helper.mirror_utils.download_utils.yt_dlp_download - INFO - Download with YT_DLP: MKBHD Interviews!
app_1  | 2023-10-10 07:51:38,004 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Retrying (1/3)...
app_1  | 2023-10-10 07:51:41,049 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Retrying (2/3)...
app_1  | 2023-10-10 07:51:44,100 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Retrying (3/3)...
app_1  | 2023-10-10 07:51:47,148 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Giving up after 3 retries
app_1  | 2023-10-10 07:51:47,166 - bot.helper.mirror_utils.download_utils.yt_dlp_download - ERROR - ERROR: [Errno 2] No such file or directory: '/root/media/34/MKBHD Interviews!/MKBHD Interviews!.jpg'

**Comment by dirkf** [comment]
>app_1 | 2023-10-10 07:51:15,680 - bot - INFO - Downloading with YT-DLP: https://www.youtube.com/playlist?list=PLBsP89CPrMePNK7yIxcyRdiIFentQVHra

#30839: "... if you were actually running _yt-dlp_ ..."

However I note that a recent update to _yt-dlp_ addresses a problem where YT fails to send as many  playlist items as it claims to have, causing a similar diagnostic.

**Comment by GollumArain** [comment]
So, what's the solution?

**Comment by dirkf** [comment]
>#30839: "... if you were actually running _yt-dlp_ ..."
