### ISSUE TITLE
Access denied, due to a Hamburg court ruling ...

### ISSUE THREAD

**Issue by jens3** [ytdl-org/youtube-dl#32598]
## Checklist

- [X ] I'm reporting a broken site support
- [ X] I've verified that I'm running youtube-dl version **2021.12.17**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

When I try to go to
 youtube-dl.org
I get the following message:
Access denied
Due to a [ruling](https://openjur.de/u/2466945.html) of the Hamburg Regional Court, access to this website is blocked.

What is going on ..?

**Comment by dirkf** [comment]
So this must be wrong, then:
>[X] I've searched the bugtracker for similar issues including closed ones

Review #30839 as asked.
