### ISSUE TITLE
https://courses/80573/pages/1-dot-1-analisis-de-riesgos-financieros-descripcion-general?module_item_id=3665529

### ISSUE THREAD

**Issue by MarilynSolCa** [ytdl-org/youtube-dl#32591]
## Checklist

- [ ] I'm reporting a new site support request
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [ ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Use the template. Write a description of what support you are asking for.
