### ISSUE TITLE
YT-dl URL Banned by Hamburg Regional Court

### ISSUE THREAD

**Issue by pheonix8905** [ytdl-org/youtube-dl#32605]
## Checklist

- [x] I'm reporting a broken site support
- [/] I've verified that I'm running youtube-dl version **2021.12.17**
- [/] I've checked that all provided URLs are alive and playable in a browser
- [/] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [/] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
No log to show.
```

## Description

The link given to the .exe download is no longer available, as it has been banned worldwide by German courts. This being said, it is impossible to know whether or not this issue has been brought to light already without checking the thousands of reported issues. 
Upon accessing yt-dl.org:
_"Access denied
Due to a [ruling](https://openjur.de/u/2466945.html) of the Hamburg Regional Court, access to this website is blocked."_

**Comment by dirkf** [comment]
>[/] I've searched the bugtracker for similar issues including closed ones

Follow #30839; find #32495.
