### ISSUE TITLE
unable to get formats

### ISSUE THREAD

**Issue by xvtstephen** [ytdl-org/youtube-dl#32619]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl -F --verbose https://youtu.be/5Y8u1SRSJXU?si=lVnDUXL4mXJUQomu
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--verbose', 'https://youtu.be/5Y8u1SRSJXU?si=lVnDUXL4mXJUQomu']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.12 (CPython) - Linux-6.2.0-35-generic-x86_64-with-glibc2.35
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 5Y8u1SRSJXU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

I am trying to get available formats and it does not work.

**Comment by dirkf** [comment]
>[ ] I'm reporting a broken site support issue

No, you are.

>[ ] I've searched the bugtracker for similar bug reports including closed ones
>[ ] I've read bugs section in FAQ

Normally, do these (**that's why the checklist is there**). But here, first read #30839 properly, which covers your issue.

**Comment by alphavirginis** [comment]
Same prob until today

**Comment by xvtstephen** [comment]
I read #30839 and do not see how it addresses the reported issue. there is a similar known issue with Vimeo, but not youtube.

**Comment by dirkf** [comment]
You are asked to:
1. read the pinned issue, which as you found lists the known problem, fixed in the nightly build
2. if necessary, search for your error message using the guidance there, which in this case should also lead to the master issue #31530.

Currently, that issue is \#1 in the list of open issues sorted by "Recently updated".
