### ISSUE TITLE
Spankbang

### ISSUE THREAD

**Issue by Klinekim** [ytdl-org/youtube-dl#32610]
youtube-dl https://la.spankbang.com/8qaz3/video/sseee
[SpankBang] 8qaz3: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call
youtube-dl with the --verbose flag and include its complete output.
root@ubuntu:/#

**Comment by dirkf** [comment]
#30839 !
