### ISSUE TITLE
Playlist not Downloading

### ISSUE THREAD

**Issue by manavchaudhary1** [ytdl-org/youtube-dl#32613]
Playlist not Downloading .
Playlist Link Working ..

youtube-dl -v 'https://youtube.com/playlist?list=PL6PnHQ57ru6xw5oGsTvxduciMfcsagw42&si=R_wxWPb9j_BffgXp'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtube.com/playlist?list=PL6PnHQ57ru6xw5oGsTvxduciMfcsagw42&si=R_wxWPb9j_BffgXp']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.4 (CPython) - Windows-10-10.0.22621-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] PL6PnHQ57ru6xw5oGsTvxduciMfcsagw42: Downloading webpage
[download] Downloading playlist: Copying Data
[youtube:tab] Downloading page 1
[youtube:tab] playlist Copying Data: Downloading 86 videos
[download] Downloading video 1 of 86
[youtube] cPNFg2LeT_Q: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
#30839 !
