### ISSUE TITLE
Website with instructions for reporting bugs is not accessible

### ISSUE THREAD

**Issue by php4fan** [ytdl-org/youtube-dl#32615]
## Checklist

- [Y] I'm reporting a broken site support
- [Y] I've verified that I'm running youtube-dl version **2021.12.17**
- [Y] I've checked that all provided URLs are alive and playable in a browser
- [Y] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [Y] I've searched the bugtracker for similar issues including closed ones

## Description

Here:
https://github.com/ytdl-org/youtube-dl/issues/30839

You say:
> If you are reporting an error with diagnostic output like this
```
youtube_dl...SomeError: oops; please report this issue on https://yt-dl.org/bug ...
```
> **do follow the instructions there**

Except I cannot follow the instructions there if there are no instructions there.

That website is not accessible:

![image](https://github.com/ytdl-org/youtube-dl/assets/13969584/0a4d4fa7-9291-4e63-9b7f-1238c5cbeb1e)

Also note that issue https://github.com/ytdl-org/youtube-dl/issues/30839 should not be closed to comments. It would have been much better for everybody if I could have commented there instead of opening a new issue for this.

**Comment by nicolaasjan** [comment]
> [Y] I've searched the bugtracker for similar issues including closed ones

https://github.com/ytdl-org/youtube-dl/issues?q=hamburg

See: #32495.
