### ISSUE TITLE
OSError: ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by Mrithul-E** [ytdl-org/youtube-dl#32626]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
OSError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Can't download video from youtube

**OSError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.**

**Comment by dirkf** [comment]
Use the checklist! (consider: why is it there?) Read and follow #30839, where your problem may well be **listed already** (but we can't tell because you didn't supply a **verbose  log**).
