### ISSUE TITLE
Download best VO audio

### ISSUE THREAD

**Issue by RPDJF** [ytdl-org/youtube-dl#32621]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## How to download the best audio while keeping the original language ?
I'm making a powershell script that tracks and downloads videos from playlists
I want the script to download the best quality, so I came up with this format : `'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio`

The problem with this line, is that when an alternative language audio have better quality than the original one, it would download the alternate one (in my case, I had spanish on my playlist)

I saw that we can specify language on the README, but I want it to be automatic and just select the original language (so if it was in italian for instance, I want to keep it italian and not in english)

My actual usage:
```powershell
youtube-dl --add-header 'Cookie:' -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 --add-metadata --ignore-errors --yes-playlist --all-subs -o `"$($downloadFolder)\%(title)s.%(ext)s`" $playlistUrl
```

Best regards,

**Comment by dirkf** [comment]
Many extractors don't extract the `language_preference` metadata that you need. In fact it's mentioned by about 0.5% of extractor modules. In fact, even `language` is only mentioned by about 5%.

If you are interested in a particular site, there may be some other way to achieve what you want, or the site extractor could be taught to tell you more about languages.

**Comment by RPDJF** [comment]
> Many extractors don't extract the `language_preference` metadata that you need. In fact it's mentioned by about 0.5% of extractor modules. In fact, even `language` is only mentioned by about 5%.
> 
> If you are interested in a particular site, there may be some other way to achieve what you want, or the site extractor could be taught to tell you more about languages.

So.. there is no way to actually download a video on the best quality without getting random language audio ???
I just want to download my videos at 1440p when available instead of the standard 480p..

**Comment by dirkf** [comment]
As above, it depends on where the videos are hosted.

**Comment by dirkf** [comment]
If someone has a concrete example of this, unlike here, please feel free to open a new issue following #30839.
