### ISSUE TITLE
Pulling all the video formats, how to choose the one I want？

### ISSUE THREAD

**Issue by repairwa11** [ytdl-org/youtube-dl#32637]
## Checklist
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

**As shown in the following figure, what instruction should I use to obtain this video with ID 642？**

![image](https://github.com/ytdl-org/youtube-dl/assets/25572060/9bab2d07-4af4-497a-bfb3-7211cec037f9)

**Comment by repairwa11** [comment]
> Your image is illegible. Post a text log.
> 
> From the F Manual (README or `--help`), which you should have read:
> 
> * to show available formats, with their IDs, `-F` aka `--list-formats`
> * to select a particular format, use its ID with `-f ...` or `--format ...`.
> 
> Also review #30839.

Thank you very much for replying to my question！I'm sorry, I got the text log, it looks very messy. The video with ID 642 is I want. How can I write the command to accurately download this video? I've tried several commands, but they all seem to be incorrect because the resulting video is always in 1080P.

PS E:\Download> E:\Download\yt-dlp.exe -F https://www.youtube.com/watch?v=T_0lN_-7N5s
[youtube] Extracting URL: https://www.youtube.com/watch?v=T_0lN_-7N5s
[youtube] T_0lN_-7N5s: Downloading webpage
[youtube] T_0lN_-7N5s: Downloading ios player API JSON
[youtube] T_0lN_-7N5s: Downloading android player API JSON
WARNING: [youtube] The read operation timed out. Retrying (1/3)...
[youtube] T_0lN_-7N5s: Downloading android player API JSON
[youtube] T_0lN_-7N5s: Downloading m3u8 information
[info] Available formats for T_0lN_-7N5s:
ID  EXT   RESOLUTION FPS HDR CH │   FILESIZE    TBR PROTO │ VCODEC           VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0        │                   mhtml │ images                                   storyboard
sb1 mhtml 89x45        0        │                   mhtml │ images                                   storyboard
sb0 mhtml 179x90       0        │                   mhtml │ images                                   storyboard
233 mp4   audio only            │                   m3u8  │ audio only           unknown             Default
234 mp4   audio only            │                   m3u8  │ audio only           unknown             Default
599 m4a   audio only          2 │    1.12MiB    31k https │ audio only           mp4a.40.5   31k 22k ultralow, m4a_dash
600 webm  audio only          2 │    1.34MiB    37k https │ audio only           opus        37k 48k ultralow, webm_dash
139 m4a   audio only          2 │    1.77MiB    49k https │ audio only           mp4a.40.5   49k 22k low, m4a_dash
249 webm  audio only          2 │    1.94MiB    53k https │ audio only           opus        53k 48k low, webm_dash
250 webm  audio only          2 │    2.56MiB    71k https │ audio only           opus        71k 48k low, webm_dash
140 m4a   audio only          2 │    4.70MiB   129k https │ audio only           mp4a.40.2  129k 44k medium, m4a_dash
251 webm  audio only          2 │    4.96MiB   136k https │ audio only           opus       136k 48k medium, webm_dash
17  3gp   176x144      7      1 │    2.83MiB    78k https │ mp4v.20.3            mp4a.40.2       22k 144p
597 mp4   256x128     15        │    1.12MiB    31k https │ avc1.4d400b      31k video only          144p, mp4_dash
602 mp4   256x128     15        │ ~  4.29MiB   115k m3u8  │ vp09.00.10.08   115k video only
598 webm  256x128     15        │    1.12MiB    31k https │ vp9              31k video only          144p, webm_dash
269 mp4   256x128     30        │ ~  6.70MiB   180k m3u8  │ avc1.4D400C     180k video only
160 mp4   256x128     30        │    2.77MiB    76k https │ avc1.4D400C      76k video only          144p, mp4_dash
603 mp4   256x128     30        │ ~  6.93MiB   186k m3u8  │ vp09.00.11.08   186k video only
278 webm  256x128     30        │    2.90MiB    80k https │ vp09.00.11.08    80k video only          144p, webm_dash
631 mp4   256x128     30 10     │ ~  7.62MiB   205k m3u8  │ vp09.02.11.10   205k video only
330 webm  256x128     30 10     │    4.07MiB   112k https │ vp09.02.11.10   112k video only          144p HDR, webm_dash
229 mp4   426x214     30        │ ~ 13.43MiB   361k m3u8  │ avc1.4D400D     361k video only
133 mp4   426x214     30        │    6.72MiB   185k https │ avc1.4D400D     185k video only          240p, mp4_dash
604 mp4   426x214     30        │ ~ 12.90MiB   346k m3u8  │ vp09.00.20.08   346k video only
242 webm  426x214     30        │    5.76MiB   159k https │ vp09.00.20.08   159k video only          240p, webm_dash
632 mp4   426x214     30 10     │ ~ 11.70MiB   314k m3u8  │ vp09.02.21.10   314k video only
331 webm  426x214     30 10     │    7.45MiB   205k https │ vp09.02.21.10   205k video only          240p HDR, webm_dash
230 mp4   640x320     30        │ ~ 28.98MiB   778k m3u8  │ avc1.4D401E     778k video only
134 mp4   640x320     30        │   13.63MiB   375k https │ avc1.4D401E     375k video only          360p, mp4_dash
18  mp4   640x320     30      2 │ ≈ 18.75MiB   503k https │ avc1.42001E          mp4a.40.2       44k 360p
605 mp4   640x320     30        │ ~ 26.71MiB   717k m3u8  │ vp09.00.21.08   717k video only
243 webm  640x320     30        │   10.68MiB   294k https │ vp09.00.21.08   294k video only          360p, webm_dash
633 mp4   640x320     30 10     │ ~ 25.89MiB   695k m3u8  │ vp09.02.30.10   695k video only
332 webm  640x320     30 10     │   15.99MiB   440k https │ vp09.02.30.10   440k video only          360p HDR, webm_dash
231 mp4   854x428     30        │ ~ 50.38MiB  1353k m3u8  │ avc1.4D401F    1353k video only
135 mp4   854x428     30        │   27.47MiB   756k https │ avc1.4D401F     756k video only          480p, mp4_dash
606 mp4   854x428     30        │ ~ 43.86MiB  1178k m3u8  │ vp09.00.30.08  1178k video only
244 webm  854x428     30        │   20.03MiB   551k https │ vp09.00.30.08   551k video only          480p, webm_dash
634 mp4   854x428     30 10     │ ~ 44.31MiB  1190k m3u8  │ vp09.02.31.10  1190k video only
333 webm  854x428     30 10     │   31.35MiB   863k https │ vp09.02.31.10   863k video only          480p HDR, webm_dash
22  mp4   1280x640    30      2 │ ≈ 61.75MiB  1659k https │ avc1.64001F          mp4a.40.2       44k 720p
232 mp4   1280x640    30        │ ~ 93.92MiB  2523k m3u8  │ avc1.64001F    2523k video only
136 mp4   1280x640    30        │   55.58MiB  1530k https │ avc1.64001F    1530k video only          720p, mp4_dash
609 mp4   1280x640    30        │ ~ 96.78MiB  2599k m3u8  │ vp09.00.31.08  2599k video only
247 webm  1280x640    30        │   40.32MiB  1110k https │ vp09.00.31.08  1110k video only          720p, webm_dash
635 mp4   1280x640    30 10     │ ~ 93.14MiB  2502k m3u8  │ vp09.02.40.10  2502k video only
334 webm  1280x640    30 10     │   72.25MiB  1989k https │ vp09.02.40.10  1989k video only          720p HDR, webm_dash
270 mp4   1920x960    30        │ ~189.07MiB  5078k m3u8  │ avc1.640028    5078k video only
137 mp4   1920x960    30        │  114.02MiB  3139k https │ avc1.640028    3139k video only          1080p, mp4_dash
614 mp4   1920x960    30        │ ~211.41MiB  5678k m3u8  │ vp09.00.40.08  5678k video only
248 webm  1920x960    30        │   82.29MiB  2265k https │ vp09.00.40.08  2265k video only          1080p, webm_dash
636 mp4   1920x960    30 10     │ ~157.06MiB  4219k m3u8  │ vp09.02.41.10  4219k video only
335 webm  1920x960    30 10     │  128.52MiB  3538k https │ vp09.02.41.10  3538k video only          1080p HDR, webm_dash
620 mp4   2560x1280   30        │ ~432.82MiB 11625k m3u8  │ vp09.00.50.08 11625k video only
271 webm  2560x1280   30        │  215.50MiB  5933k https │ vp09.00.50.08  5933k video only          1440p, webm_dash
639 mp4   2560x1280   30 10     │ ~409.03MiB 10986k m3u8  │ vp09.02.50.10 10986k video only
336 webm  2560x1280   30 10     │  360.02MiB  9911k https │ vp09.02.50.10  9911k video only          1440p HDR, webm_dash
625 mp4   3840x1920   30        │ ~825.61MiB 22175k m3u8  │ vp09.00.50.08 22175k video only
313 webm  3840x1920   30        │  431.05MiB 11867k https │ vp09.00.50.08 11867k video only          2160p, webm_dash
642 mp4   3840x1920   30 10     │ ~943.80MiB 25350k m3u8  │ vp09.02.51.10 25350k video only
337 webm  3840x1920   30 10     │  824.24MiB 22692k https │ vp09.02.51.10 22692k video only          2160p HDR, webm_dash
PS E:\Download>

**Comment by dirkf** [comment]
#30839: if you were actually using yt-dlp, ...

However the answer is the same.

642 is a video-only format with VP09 in mp4. Presumably you want some sound too, so pick an audio format, say 251 (since 642 is DASH too). Then `-f 642+251` will tell yt-dl or yt-dlp to download the two streams and invoke _ffmpeg_ to multiplex them into an mp4 container (probably non-standard, but if your player understands it that may be OK - review https://github.com/yt-dlp/yt-dlp/issues/7848). If you don't have _ffmpeg_ installed you can only use format 22.


You can place any console text between lines containing triple backquotes (`\``) to format it in a post.
