### ISSUE TITLE
Unable to run youtube-dl : 1: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by sunbearc22** [ytdl-org/youtube-dl#32647]
## Checklist

- [:heavy_check_mark:] I'm reporting a broken site support issue
- [:heavy_check_mark:] I've verified that I'm running youtube-dl version **2021.12.17**
- [:heavy_check_mark:] I've checked that all provided URLs are alive and playable in a browser
- [:heavy_check_mark:] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [:heavy_check_mark:] I've searched the bugtracker for similar bug reports including closed ones
- [:heavy_check_mark:] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
$ sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   384  100   384    0     0    151      0  0:00:02  0:00:02 --:--:--   151
$ sudo chmod a+rx /usr/local/bin/youtube-dl
$ youtube-dl --version -v
/usr/local/bin/youtube-dl: line 1: syntax error near unexpected token `newline'
/usr/local/bin/youtube-dl: line 1: `<h1>Access denied</h1>'
$ youtube-dl https://www.youtube.com/watch?v=OfOF-fE5PDw&list=TLPQMjcxMTIwMjMRkXl3cvJF_A&index=7&ab_channel=KeithandKristynGetty
[1] 12892
[2] 12893
[3] 12894
[2]-  Done                    list=TLPQMjcxMTIwMjMRkXl3cvJF_A
$ /usr/local/bin/youtube-dl: line 1: syntax error near unexpected token `newline'
/usr/local/bin/youtube-dl: line 1: `<h1>Access denied</h1>'
$ uname -srv
Linux 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2
```

## Description

WRITE DESCRIPTION HERE
youtube-dl fail to execute a version check or download from youtube link. Both events results in the same err msg.

**Comment by sunbearc22** [comment]
I don't understand why the given command `sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl` failed to download the program file.

As such, I did the following to download `youtube-dl` and to make it accessible system-wide:

```
$ git clone https://github.com/ytdl-org/youtube-dl.git youtube-dl
$ cd youtube-dl/
$ make youtube-dl
$ sudo cp youtube-dl /usr/local/bin/
```

**Comment by dirkf** [comment]
You would understand if you had read the issues in the search result that I linked. That's why you are asked to make the search.

**Comment by mosleim** [comment]
when visiting the download url, will show like this:

![image](https://github.com/ytdl-org/youtube-dl/assets/3499544/fbd33f53-752d-4ae2-a144-4ceddabc7a31)

**Comment by rodolfo-medina** [comment]
Right, but then why the Install section continues to give the wrong link for the download?
