### ISSUE TITLE
Incorrect python3 dependency during `brew install --HEAD youtube-dl`

### ISSUE THREAD

**Issue by zwimer** [ytdl-org/youtube-dl#32644]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ brew install --HEAD youtube-dl
==> Fetching youtube-dl
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/8f2197797e3e31050a15cd675af0f9fdb55b4a26/Formula/
Already downloaded: /Users/zwimer/Library/Caches/Homebrew/downloads/db2a58cfb5648dd8d0cde7aa9e5c816b37b55ce7a5a55d9fe959ade71f41a215--youtube-dl.rb
==> Cloning https://github.com/ytdl-org/youtube-dl.git
Updating /Users/zwimer/Library/Caches/Homebrew/youtube-dl--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at aaed4884e fix(youtube): update extractor handling consent
==> make PREFIX=/opt/homebrew/Cellar/youtube-dl/HEAD-aaed488 MANDIR=/opt/homebrew/Cellar/youtube-dl/HEAD-aaed488/share/man
Last 15 lines from /Users/zwimer/Library/Logs/Homebrew/youtube-dl/01.make:
	done
make: *** [youtube-dl.bash-completion] Error 1
make: *** Waiting for unfinished jobs....
make: *** [youtube-dl.zsh] Error 1
/bin/sh: /opt/homebrew/opt/python@3.12/bin/python3: No such file or directory
/bin/sh: /opt/homebrew/opt/python@3.12/bin/python3: No such file or directory
make: *** [README.md] Error 127
touch -t 200001010101 zip/youtube_dl/*.py zip/youtube_dl/*/*.py
mv zip/youtube_dl/__main__.py zip/
cd zip ; zip -q ../youtube-dl youtube_dl/*.py youtube_dl/*/*.py __main__.py
rm -rf zip
echo '#!/opt/homebrew/opt/python@3.12/bin/python3' > youtube-dl
cat youtube-dl.zip >> youtube-dl
rm youtube-dl.zip
chmod a+x youtube-dl

READ THIS: https://docs.brew.sh/Troubleshooting

youtube-dl's formula was built from an unstable upstream --HEAD.
This build failure is expected behaviour.
Do not create issues about this on Homebrew's GitHub repositories.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

## Description

The install is looking for `/opt/homebrew/opt/python@3.12/bin/python3`, but `python@3.12` does not provide this file. Instead it probably should use `/opt/homebrew/opt/python@3.12/bin/python3.12`.

To verify this: I've tested symlinking `/opt/homebrew/opt/python@3.12/bin/python3 -> /opt/homebrew/opt/python@3.12/bin/python3.12` and then the install and tool both work.

**Comment by dirkf** [comment]
The "formula" isn't maintained here but @ Homebrew. The problem seems to be with the Python installation. What happens if you run `which python3`?

**Comment by zwimer** [comment]
I get `/opt/homebrew/bin/python3` (though mac also has a builtin python3, homebrew's is first in my `PATH`). That's a symlink to homebrew's python3.11 install, though since this requires 3.12 by name I assume it should use that instead. If this is a PR I should make to homebrew-core (presumably here https://github.com/Homebrew/homebrew-core/blob/adb653972409c4cfc269cd9ae0d92e27cc0c670b/Formula/y/youtube-dl.rb#L30 ) please let me know and feel free to close this! I'll open an issue there instead. Thanks!

**Comment by zwimer** [comment]
Also, if it matters, this is `--HEAD`, it is not just normal `brew install`; this should grab from `master` I believe. I'm making the issue here first since 1) I'm not sure if this is a ytdl or a brew issue and 2) brew's install head said `Do not create issues about this on Homebrew's GitHub repositories. Any opened issues will be immediately closed without response.` So I'm trying here first.

**Comment by dirkf** [comment]
Presumably the Homebrew formula "sees" your Python 3.12, prefers it as the installation target, as the most recent version, and expects there to be a `python3` in the same directory.

You could try either removing the 3.12, or actually creating a link `/opt/homebrew/opt/python@3.12/bin/python3` --> /opt/homebrew/opt/python@3.12/bin/python3.12`, or reinstalling 3.12.

In any event this a problem of too many and various Pythons and nothing to do with yt-dl itself, or with installing from its `HEAD`. If the suggestions above don't help, you could ask Homebrew why the formula is getting confused: maybe if it expects to find a `python3` it should explicitly check for one first or (assuming 3.12 is also brewed) the Python 3.12 formula (supported, I expect?) is defective in failing to create the expected link.

**Comment by dirkf** [comment]
As this isn't a bug here, I'll close the issue, but feel free to post the result of the Homebrew issue.
