### ISSUE TITLE
Use command without hierarchical order

### ISSUE THREAD

**Issue by 123Axo** [ytdl-org/youtube-dl#32646]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Alright, so I'm using this command:
yt-dlp --audio-format best -x -o '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s'

It basically creates a folder for each playlist. It is great but I have one big massive issue: it numbers each file.
In other words, if I download a playlist called "Cool music" and there's a song called "epic song" it will download the folder with the original name of the playlist BUT, it will download the file for "epic song" as "01.opus", and I don't want it, I want the file to keep it's name.

I've tried everything, erasing portions of the command, adding stuff, and it always breaks something.
Is there a way to keep the file name?

I've searched for the same issue but I can't find anything. I would really appreciate your help!!!

**Comment by dirkf** [comment]
#30839: "If you were actually usin _yt-dlp_ ..."

However, I'd say the answer is the same for yt-dl too: the extractor for the site doesn't know how to find what you believe is the song's title, so the titles get numbered (yt-dl insists on a non-empty title being extracted, so the problem would be different).

Also, `best` is not a valid value of `--audio-format`.
