### ISSUE TITLE
Facebook - No such file or directory

### ISSUE THREAD

**Issue by 0ldcamel** [ytdl-org/youtube-dl#32641]
I tried several combinations, none of them works.

youtube-dl "https://www.facebook.com/100000342225090/videos/1521905521547529/"
[facebook] 1521905521547529: Downloading webpage
[facebook] 1521905521547529: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

youtube-dl "https://www.facebook.com/100000342225090/videos/1521905521547529/"
bash: /usr/bin/youtube-dl: No such file or directory

youtube-dl "https://www.facebook.com/100000342225090"
bash: /usr/bin/youtube-dl: No such file or directory

youtube-dl 'https://www.facebook.com/video.php?v=1521905521547529'
bash: /usr/bin/youtube-dl: No such file or directory

## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Use the checklist (why is it there? why is #30389 pinned?) !

Before you apparently deleted `/usr/bin/youtube-dl`, your Facebook issue was already reported. You can find it yourself.
