### ISSUE TITLE
usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by ixtr** [ytdl-org/youtube-dl#32642]
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
youtube-dl is a program that requires Python, Maybe your installation doesn't have it? Maybe it's called `python3`? As discussed in previous issues that you can find if you can be bothered, there are various ways to solve that problem.

But as you completely ignored the checklist and #30839, we can only guess.
