### ISSUE TITLE
Youtube Video Trancript Downloader

### ISSUE THREAD

**Issue by HafizTamoor** [ytdl-org/youtube-dl#32645]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I got this error:
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Would you please suggest me what should I do

**Comment by dirkf** [comment]
Read #30839 as asked?
