### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by sirmarky** [ytdl-org/youtube-dl#32658]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Since recent updates, I can no longer make youtube-dl work.

The following error appears even for version checking.  The same error when using to download videos.

```
/usr/local/bin/youtube-dl: line 1: syntax error near unexpected token `newline'
/usr/local/bin/youtube-dl: line 1: `<h1>Access denied</h1>'
```
Using Ubuntu 23.10, Python 3.11.6, ffmpeg 6.0-6ubuntu1,

**Comment by nicolaasjan** [comment]
See issue #32647.
You tried to download youtube-dl from `https://yt-dl.org/downloads/latest/youtube-dl`, which is now blocked by a German court.
(so you downloaded a html file...)

[Similar closed issues](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+syntax+error+near+unexpected+token+%60newline%27+is%3Aclosed).

Instead download from GitHub.
Preferably the Nightly build from [here](https://github.com/ytdl-org/ytdl-nightly).

**Comment by dirkf** [comment]
Since the recent update of 2021?

>[X] I've searched the bugtracker for similar bug reports including closed ones

This really would have helped you to solve your problem.

**Comment by sirmarky** [comment]
I did not download from a closed website.  I tried the version from the snap store AND removed that and tried the version from Github.
