### ISSUE TITLE
Retrieve hidden video URLs.

### ISSUE THREAD

**Issue by bySnach** [ytdl-org/youtube-dl#32653]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have just a quick question. Is there any possibility or way to get a list of video URLs from my terminated YouTube channel using "youtube-dl" tool?
I still have access to my account, however, all the videos are hidden now. But If I will know the ID/URL of a specific video - I can generate a temporary direct link to download this particular video.

**Comment by dirkf** [comment]
If you can play your video in the browser when logged in, use `--cookies ...` as described in the FAQ to recover the video using yt-dl. Do use the latest nightly version (#30839).

**Comment by dirkf** [comment]
I think you should try it, using the canonical channel URL from the ID (look at some non-blocked channels for examples) and passing the login cookies as above. Otherwise, if you have a record of the IDs that you added, you may be able to retrieve those in a similar way -- or is that what you mean by "generate a temporary direct link"?

**Comment by bySnach** [comment]
> I think you should try it, using the canonical channel URL from the ID (look at some non-blocked channels for examples) and passing the login cookies as above. Otherwise, if you have a record of the IDs that you added, you may be able to retrieve those in a similar way -- or is that what you mean by "generate a temporary direct link"?

By generated temporary direct link I mean the following example below:

`https://rr5---sn-4g5ednkl.c.youtube.com/videoplayback?expire=1701459824&ei=8MZpZdq1NL61i9oPo9uiiA0&ip=164.92.180.144&cp=X19PYmN2d2ktM01ETEZTSkk6ZjY5Y3d6RGxYUElPam16TmgyNGRUd0hVUmNVVGFsc1oyb1p4cy13SFZtTg&id=3dc6c3dd524215de&itag=18&source=youtube&requiressl=yes&xpc=Egho2aDSNXoBAQ%3D%3D&mh=Fc&mm=32&mn=sn-4g5ednkl&ms=su&mv=u&mvi=5&pl=22&sc=yes&susc=ytcp&mime=video%2Fmp4&vprv=1&prv=1&dur=181.603&lmt=1665262682028893&mt=1701430341&txp=1438434&sparams=expire%2Cei%2Cip%2Ccp%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csusc%2Cmime%2Cvprv%2Cprv%2Cdur%2Clmt&sig=ANLwegAwRAIgXLMhaItGrNvUvdO6ESM8hoHEv9465VDSs8LrGRzzZzwCIGZzsVoR5d5Ncue_sLIGZxiwtPWtJ2CIS4P5j_yHvC5d&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Csc&lsig=AM8Gb2swRQIhALfOMX_oK4unSKpEan9oSTNfTyQlo4ptgw7dGFqXlVfTAiBzCWdkWqrOE-PJWDAUnJcfD1BRQL9p7x6dZJqG25o4VQ%3D%3D`

And this is the only way I can access my videos that are hidden on my terminated YouTube channel.
However, in order to receive such link, **I need to know the URL** of the video that was uploaded on the channel.
I'd like to repeat, my videos are no longer available to me in the regular user interface, this means that I can't find out or get the URL address of each of my videos.

Terminated channels are essentially removed from YouTube's active database, but the videos that were uploaded on them - can still be obtained (generated) compressed.

My main goal here that I want to achieve, is to find a way to get the videos that were uploaded on my channel (which is currently blocked).

**Comment by dirkf** [comment]
If you can't retrieve the channel data and don't know the video IDs then yt-dl can't help. But yt-dl bypasses the JS that runs in the YT page, so possibly it can fetch the channel and video details that aren't available in the browser (_yt-dlp_ uses more retrieval tactics and may offer other options). Hence
>I think you should try it, ...

Also, what's happened to the channel in Invidious (and similar) sites?

**Comment by bySnach** [comment]
> If you can't retrieve the channel data and don't know the video IDs then yt-dl can't help. But yt-dl bypasses the JS that runs in the YT page, so possibly it can fetch the channel and video details that aren't available in the browser (_yt-dlp_ uses more retrieval tactics and may offer other options). Hence
> 
> > I think you should try it, ...
> 
> Also, what's happened to the channel in Invidious (and similar) sites?

Alright, thank you very much for the tips and directions to look into 👍🏼 I will try to find some solutions.
The thing is, my YT channel became terminated due to numerous copyright violations and I really don't want to lose the videos that were uploaded to it, in which I invested my time, energy and soul + memories/nostalgia.

I've already tried to submit an appeal request several times, but it was denied and YT's support itself does not provide any backup archive.

**Comment by dirkf** [comment]
Unfortunately a fickle and unresponsive clown-based service is not a reliable backup mechanism. But I guess you understand that now (and we've all lost data somehow or other). I'll close the issue but feel free to add to it if you have any success, especially if yt-dl helped.
