### ISSUE TITLE
HELP!! :c

### ISSUE THREAD

**Issue by javiercity** [ytdl-org/youtube-dl#32659]
root@javiercity:~# youtube-dl https://www.youtube.com/watch?v=oNEwEQ0uU1Y
[youtube] oNEwEQ0uU1Y: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I've been trying to find the problem for easily an hour but I can't find what to do to make the command run as it should, can someone please help me?

![Captura de pantalla 2023-12-06 152256](https://github.com/ytdl-org/youtube-dl/assets/153130178/71789053-b649-438d-bd98-aeb7bfe4d582)

**Comment by javiercity** [comment]
It doesn't matter anymore, I found the solution in this video, in case someone else doesn't need it.

https://www.youtube.com/watch?v=Ghe058HpmMk

**Comment by dirkf** [comment]
How was it not possible to **find this known issue** in the pinned issue #30839 and, as suggested there, install a nightly build of the program that fixes the issue and dozens more?
