### ISSUE TITLE
How to DL tver.jp/live

### ISSUE THREAD

**Issue by lingless** [ytdl-org/youtube-dl#32661]
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

TVer.jp had a new kind of vedios. Like this: https://tver.jp/live/simul/ler52fd5a6  
How to download these?

**Comment by dirkf** [comment]
Please complete the template.

**Comment by dirkf** [comment]
Test video expired.

**Comment by dirkf** [comment]
Also, the existing TVer extractor is broken and needs to be fixecd, eg by back-porting the _yt-dlp_ extractor, if that works.
