### ISSUE TITLE
Saving Cookies for Watch Later Retrieval ? 

### ISSUE THREAD

**Issue by SheepDomination** [ytdl-org/youtube-dl#32670]
I'm trying to use TubeSync which depends on YouTube-DL to retrieve all the videos from a user account Watch Later List. Unfortunately, no matter how many times I try to export the cookies.txt file in a Netscape format YouTube-DL does not retrieve the videos. As I'm using an extension for Microsoft Edge which as the options of saving cookies from a specific site as well as in Netscape format, although; neither is working ?

**Comment by dirkf** [comment]
You have a bug report, not a question. Please open a new issue of the correct type, following #30839 and the issue checklist.

YouTube Watch Later playlists are meant to be supported either directly or through the `:ytwatchlater` pseudo-URL. You may want to check whether your exported cookie file allows you to perform other "logged-in" actions such as fetching a private video.
