### ISSUE TITLE
Error extracting uploader

### ISSUE THREAD

**Issue by SlashScreen** [ytdl-org/youtube-dl#32675]
Platform: Windows 11, Ubuntu
youtube-dl version: latest

I go to download videos, but it cannot find the ID of the video to download.

console feed: 

```
PS L:\ytdl-vid> youtube-dl --extract-audio https://www.youtube.com/watch?v=mjGo9Ars1qo
[youtube] mjGo9Ars1qo: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

I have also tried another, unrelated, [much shorter video](https://www.youtube.com/watch?v=bp7REZBV4P4, and trying without --extract-audio.

**Comment by dirkf** [comment]
No, it couldn't find the ID of the uploader of the video.

Read and follow #30839 as asked.
