### ISSUE TITLE
Custom postprocessor with python library

### ISSUE THREAD

**Issue by TomW1605** [ytdl-org/youtube-dl#32679]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is there a way to write a custom postprocessor without modifying the library itself?

**Comment by dirkf** [comment]
If you are just using the command-line program, consider using `--exec ...` with a custom script. To add a custom post-processor, I think you'll need to modify files like `youtube_dl/__init__.py`.

If you want to add a custom post-processor in the context of your own program that uses the yt-dl API, it should be possible to make the necessary changes in a subclass. But I haven't tried that.

**Comment by TomW1605** [comment]
i tried making a custom postprocessor subclass but it breaks when it tries to find it in `get_postprocessor` because it is not imported in `youtube_dl/postprocessor/__init__.py` and when execution gets to that file the subclass is out of the `globals()` scope.

this is what i tried:
```py
class MyPostProcessor(PostProcessor):
    def __init__(self, downloader, new_file_format):
        super(MyPostProcessor, self).__init__(downloader)
        self.new_file_format = new_file_format
        print("test0")

    def run(self, information):
        new_file_format = self.new_file_format

        print("test1")

        return [], information

ydl_opts = {
    'format': 'bestaudio/best',
    'logger': MyLogger(),
    'postprocessors': [{
        'key': 'MetadataFromTitle',
        'titleformat': "%(series)s - %(title)s // S%(season)s: Episode %(episode)s",
    }, {
        'key': 'MyPostProcessor',
        'new_file_format': "%(series)s - S0%(season)sE0%(episode)s - %(title)s.%(ext)s",
    }],
    'verbose': True,
    'outtmpl': '%(title)s.%(ext)s'
    # 'dump_single_json': True,
    # 'forcejson': True,
    # 'simulate': True,
}
```

im wondering if there could be a way to pass it the object directly similar to how the logger does it. if the project is open to a PR to add that functionality i would be happy to look into it

**Comment by TomW1605** [comment]
so i had a quick look and it was fairly easy to work out. it adds a new `class` option to the postprocessors dict that gets passed to ydl and if that is present it will use that class instead of using `get_postprocessor` to get the class.

i added some logic to the postprocessor adding for loop in [YoutubeDL.py](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L447-L452):
```py
        for pp_def_raw in self.params.get('postprocessors', []):
            if pp_def_raw.get('class'):
                pp_class = pp_def_raw['class']
                if not issubclass(pp_class, PostProcessor):
                    self.report_error('postprocessor %s is not subclass of PostProcessor'% pp_def_raw.get('class'))
                    continue
            elif pp_def_raw.get('key'):
                try:
                    pp_class = get_postprocessor(pp_def_raw['key'])
                except KeyError:
                    self.report_error('postprocessor %s not found'%pp_def_raw.get('key'))
                    continue
            else:
                self.report_error('postprocessor not found')
                continue

            pp_def = dict(pp_def_raw)
            pp_def.pop("key", None)
            pp_def.pop("class", None)

            pp = pp_class(self, **compat_kwargs(pp_def))
            self.add_post_processor(pp)
```
this checks if the `class` key is present and if it is it will use that class. it will also check if that class is a subclass of `PostProcessor` and throw an error if it isnt.

i also had to add this to the imports in YoutubeDL.py `from .postprocessor.common import PostProcessor`

example `ydl_opts`:
```py
ydl_opts = {
    'postprocessors': [{
        'key': 'MetadataFromTitle',
        'titleformat': "%(series)s - %(title)s // S%(season)s: Episode %(episode)s",
    }, {
        'class': MyPostProcessor,
        'new_file_format': "%(series)s - S0%(season)sE0%(episode)s - %(title)s.%(ext)s",
    }],
}
```

let me know if you would be open to adding this and ill do all the PR things (run tests, update docs, etc) and open a PR. i dont think this can impact any existing code or CLI usages (with the possable exception of the error checking around `get_postprocessor` and that can be removed if its an issue)

**Comment by dirkf** [comment]
What I'd suggest is to see if your problem is solved, or easier to solve, with the _yt-dlp_ codebase, and perhaps propose any necessary improvements there. Then, a PR to back-port the resulting code, or a subset of it, or a PR that implements a subset of that functionality to yt-dl, would be helpful.

Rationale: avoid solving the same/related problem twice, or learning from an existing solution; avoid clashing changes to the CLI and API; considering that _yt-dlp_ will generally port changes made here, avoid making that unduly complex or pointless.

**Comment by TomW1605** [comment]
so here is where i have to addmit something kind of stupid, up untill about an hour ago i thought i was working with yt-dlp. at some point during my initial attempts to get what i want working i clicked a link that i thought was to the yt-dlp repo but was actually to this one and i didnt notice. i have been working witht that tab as the root for my work since then without realising it was not yt-dlp.

and, as you thought might be the case, yt-dlp does infact solve my problem out of the box with no extra work requiered.

im guessing the reason it hasnt been backported to here is because the way they seem to be solving it is by letting *post*processers run as *pre*processers so that the metadata changes they make are applied to the whole process. im assuming that implemenging that here would mean a significant redesigne and that is why it hasnt been done.

if any of the things i have worked on are still useful simply because they implement similar functionality without needing large changes i would be happy to do a PR but if not ill leave it here.

the main things i have done are add a rename from metadata postprocessor, add options to allow custom postprocessor when using the python api and allow MetadataFromTitle to handle numeric fields when given regex. let me know if any of these would be useful

thanks for your advice and help and sorry for the confusion.

ill close #32678 now since it dosnt make sense to have both open

**Comment by dirkf** [comment]
If someone had cared enough, some relevant yt-dlp functionality would have been pulled. Now, the two areas of output formatting and post-processor scheduling have diverged sufficiently that pulling any specific subset of that functionality is not at all trivial.

**Comment by TomW1605** [comment]
yep, that makes sense. ill close this issue now
