### ISSUE TITLE
use MetadataFromTitle output in final file name

### ISSUE THREAD

**Issue by TomW1605** [ytdl-org/youtube-dl#32678]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

is there a way to use the metadata extracted from the title with the `MetadataFromTitle` postprocessor in the final file name? from what i can tell the final file name is being generated before the postprocessor is being run (this makes sense, it is a *post*processor after all) but that means when i try and format my files in a way plex likes i end up with `NA - S0NAE0NA - NA.mkv`. this isnt overly useful unfortunatly. i think i could make it work with the `ExecAfterDownload` postprocessor and some shell commands but that feels messy when this seems like something that should be possable directly with youtube-dl

**Comment by dirkf** [comment]
What if you run yt-dl twice with different parameters, so that on pass one you generate the info JSON with the edited metadata and on pass 2 you actually d/l the media and name it using the previously generated info JSON?

**Comment by TomW1605** [comment]
thanks, ill have a look at doing that

**Comment by TomW1605** [comment]
so i have ended up writing my own post processor (see #32679) because i want to do the meta data extraction a bit differently too (the built in one cant handle extracting ints for season and episode numbers), and i realised it would be fairly easy to genrelise it to be a `RenameFromMetadata` post processor. is that something that would be worth me sticking in a PR?

**Comment by dirkf** [comment]
My comment in [#32679](https://github.com/ytdl-org/youtube-dl/issues/32679#issuecomment-1870200837) applies here too.

**Comment by TomW1605** [comment]
see https://github.com/ytdl-org/youtube-dl/issues/32679#issuecomment-1870245917
