### ISSUE TITLE
support for the Animes OneGai site

### ISSUE THREAD

**Issue by levaculik2** [ytdl-org/youtube-dl#32674]
## Checklist

- [ X ] I'm asking a question
- [ X ] I've looked through the README and FAQ for similar questions
- [ X ] I've searched the bugtracker for similar questions including closed ones

## Question

Hello I would like to know if YT-DLP already has support for the Animes OneGai site?
If yes how can I be testing this! and if the answer is negative if they pretense in the future put this functionality to YT-DLP.

thanks

**Comment by dirkf** [comment]
Review #30839:

"... if you were actually using _yt-dlp_ ..."

But the answer here is the same.

Try the URL of your test video page using the `--verbose` option. If the video is not successfully extracted, there are two cases:
* if you see log entries for an extractor other than `[generic]`, the site appears to be supported, but the extraction is failing: raise a broken site support issue
* if not, raise a site support request.

**Comment by dirkf** [comment]
But I see you've done that already: https://github.com/yt-dlp/yt-dlp/issues/8837.
