### ISSUE TITLE
Unable to extract the uploader ID from YouTube videos

### ISSUE THREAD

**Issue by lehmanbro89** [ytdl-org/youtube-dl#32676]
**Description**
I'm encountering an issue with youtube-dl where it's unable to extract the uploader ID from YouTube videos. This issue occurs even after ensuring that I am using the latest version of youtube-dl (2021.12.17). The error persists across different videos. The issue seems to be a RegexNotFoundError related to extracting the uploader ID, preventing the extraction of audio from YouTube videos.

**Checklist**
 I'm reporting a broken site support issue
 I've verified that I'm running youtube-dl version 2021.12.17
 I've checked that all provided URLs are alive and playable in a browser
 I've checked that all URLs and arguments with special characters are properly quoted or escaped
 I've searched the bugtracker for similar bug reports including closed ones
 I've read bugs section in FAQ

**Verbose log**
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-x', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=G6X1x8CRyBs']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.11 (CPython) - [redacted]
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] G6X1x8CRyBs: Downloading webpage
[youtube] G6X1x8CRyBs: Downloading API JSON
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by creepysta** [comment]
Hey @lehmanbro89, I think the current master branch has the fix. I just cloned and built the package and I don't see the error any more. I was facing this same issue for the following - https://www.youtube.com/watch?v=h_m-BjrxmgI

Can someone share when's the next release planned?

**Comment by Sasino97** [comment]
![image](https://github.com/ytdl-org/youtube-dl/assets/17410173/3d3aa057-b887-4212-9a23-16da53a881b6)
It's ironic but it seems youtube-dl doesn't support YouTube anymore lol

**Comment by aryaky** [comment]
i use this repo: yt-dlp. Hope helpful.

**Comment by dirkf** [comment]
>I've searched the bugtracker for similar bug reports including closed ones
>I've read bugs section in FAQ

Well, did you?

Anyhow, review #30839 as asked to solve your well known issue.

**Comment by lehmanbro89** [comment]
I will give it a try. Thanks for you help. Appreciated.
