### ISSUE TITLE
All content of the sub appeared in the beginning of the video, how to fix this

### ISSUE THREAD

**Issue by pammseyy** [ytdl-org/youtube-dl#32684]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

The entire sub downloaded appeared in the first few seconds of the video.. This is the command I used:

youtube-dl  -v --format bestvideo+bestaudio/best --embed-thumbnail --write-all-thumbnails --write-auto-sub --sub-lang en https://www.youtube.com/watch?v=8TkdrjFJNS4

Please help

this is the verbose log of the original failure:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--format', u'bestvideo+bestaudio/best', u'--embed-thumbnail', u'--write-all-thumbnails', u'--write-auto-sub', u'--sub-lang', u'en', u'https://www.youtube.com/watch?v=8TkdrjFJNS4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-101053-g0a7c648e2d-tessus, ffprobe N-101053-g0a7c648e2d-tessus
[debug] Proxy map: {}
[youtube] 8TkdrjFJNS4: Downloading webpage
[youtube] 8TkdrjFJNS4: Looking for automatic captions
![Screen Shot 2024-01-07 at 21 17 37](https://github.com/ytdl-org/youtube-dl/assets/78685704/5c8184a9-568d-429a-8da5-17839097919e)
![Screen Shot 2024-01-07 at 21 17 47](https://github.com/ytdl-org/youtube-dl/assets/78685704/1af05f9c-29f1-4ddb-86f8-cea65a0a65ac)

**Comment by dirkf** [comment]
Do try this with the nightly build (see #30839, in any case). Your version is even older than the completely obsolete official release.

Also, if this is happening you're not asking a question but reporting a bug. Follow the relevant issue template (#30839 again).

**Comment by dirkf** [comment]
Also:
```console
$ python ./youtube-dl-20231123 -v --skip-download --write-auto-sub --sub-lang 'en' 'https://www.youtube.com/watch?v=8TkdrjFJNS4'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--skip-download', u'--write-auto-sub', u'--sub-lang', u'en', u'https://www.youtube.com/watch?v=8TkdrjFJNS4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2023.11.23 [aaed4884e] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 2.7.15 (CPython i686 32bit) - Linux-6.1.0-17-686-pae-i686-with-debian-12.4 - OpenSSL 1.1.1a  20 Nov 2018 - glibc 2.1.3
[debug] exe versions: ffmpeg 5.1.4-0, ffprobe 5.1.4-0
[debug] Proxy map: {}
[youtube] 8TkdrjFJNS4: Downloading webpage
[debug] [youtube] Decrypted nsig uxaB6vgvZot-SaY7XJh => fRmJS1azHVO3JA
[debug] [youtube] Decrypted nsig QLNi_i0_HudytUWU1rS => Jte0Gjdkp2BlPw
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: [100만]'깻잎이 맛있을까...' 🍃깻잎논쟁에 신박한() 소신발언 하고 간 사내커플 안효섭 김세정 추측 인터뷰💑 (Eng Sub)-8TkdrjFJNS4.en.vtt
$ head -30 \[100만\]\'깻잎이\ 맛있을까...\'\ 🍃깻잎논쟁에\ 신박한\(\)\ 소신발언\ 하고\ 간\ 사내커플\ 안효섭\ 김세정\ 추측\ 인터뷰💑\ \(Eng\ Sub\)-8TkdrjFJNS4.en.vtt 
WEBVTT
Kind: captions
Language: en

00:00:00.000 --> 00:00:02.149 align:start position:0%
 
Ah

00:00:02.149 --> 00:00:02.159 align:start position:0%
 
 

00:00:02.159 --> 00:00:04.519 align:start position:0%
 
3 <00:00:02.309><c>Mr. </c><00:00:02.459><c>Jeong,</c>

00:00:04.519 --> 00:00:04.529 align:start position:0%
3 Mr. Jeong,
 

00:00:04.529 --> 00:00:05.450 align:start position:0%
3 Mr. Jeong,
hello, I'm

00:00:05.450 --> 00:00:05.460 align:start position:0%
hello, I'm
 

00:00:05.460 --> 00:00:08.000 align:start position:0%
hello, I'm
$

**Comment by BalzySte** [comment]
Hello, I'm also experiencing the same bug trying to download autogenerated english subtitles with
```
youtube-dl -v --write-auto-sub --sub-lang en --skip-download [URL]
```

**Comment by BalzySte** [comment]
Hello, I'm also experiencing the same bug trying to download auto-generated English subtitles with
```
youtube-dl -v --write-auto-sub --sub-lang en --skip-download [URL]
```

I'm running version 2021.12.17

**Comment by BalzySte** [comment]
Hello, I'm also experiencing the same bug trying to download auto-generated English subtitles with
```
youtube-dl -v --write-auto-sub --sub-lang en --skip-download [URL]
```

I'm running version 2021.12.17

**Comment by dirkf** [comment]
The [previous](https://github.com/ytdl-org/youtube-dl/issues/32684#issuecomment-1880155636) [comments](https://github.com/ytdl-org/youtube-dl/issues/32684#issuecomment-1880872670) apply equally.
