### ISSUE TITLE
Merging Video and Audio Using youtube-dl

### ISSUE THREAD

**Issue by giauphan** [ytdl-org/youtube-dl#32680]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

I'm experiencing an issue when attempting to merge video and audio using youtube-dl. I have used the following command:
```
youtube-dl -g -e --get-thumbnail  -f 137+140 --merge-output-format mp4 --get-format URL
```

**Comment by dirkf** [comment]
You're not asking a **question**.

First review #30839. Create a new issue following and completing (unlike above) the correct template, including a verbose log to show the software versions in use, what you were trying to do, etc.
