### ISSUE TITLE
Could not send HEAD request to URL_SITE HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by rowanDeveloper** [ytdl-org/youtube-dl#32694]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

I have read through the FAQ about a similar problem/challenge when the youtube-dl script output gives me: "Could not send HEAD request to URL_SITE (what I am trying to download). HTTP Error 403: Forbidden. I have read the FAQ here and also gone through some forums and seek help on Reddit, but to be honest I'm totally lost and would like some advice on how to solve this issue. 

Here is the full output --verbose: 

 youtube-dl --verbose https://video.privacy.com.br/507b65cc-83e5-4649-a5ba-17bae1e65764/mp4/6502f04e-6c2b-47e2-b397-866264e56e33-1705105253171--yasminmineira_Mp4_Avc_Aac_16x9_1280x720p_24Hz_8.5Mbps_qvbr.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://video.privacy.com.br/507b65cc-83e5-4649-a5ba-17bae1e65764/mp4/6502f04e-6c2b-47e2-b397-866264e56e33-1705105253171--yasminmineira_Mp4_Avc_Aac_16x9_1280x720p_24Hz_8.5Mbps_qvbr.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.12 (CPython) - Linux-6.5.0-14-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 6502f04e-6c2b-47e2-b397-866264e56e33-1705105253171--yasminmineira_Mp4_Avc_Aac_16x9_1280x720p_24Hz_8.5Mbps_qvbr: Requesting header
WARNING: Could not send HEAD request to https://video.privacy.com.br/507b65cc-83e5-4649-a5ba-17bae1e65764/mp4/6502f04e-6c2b-47e2-b397-866264e56e33-1705105253171--yasminmineira_Mp4_Avc_Aac_16x9_1280x720p_24Hz_8.5Mbps_qvbr.mp4: HTTP Error 403: Forbidden
[generic] 6502f04e-6c2b-47e2-b397-866264e56e33-1705105253171--yasminmineira_Mp4_Avc_Aac_16x9_1280x720p_24Hz_8.5Mbps_qvbr: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 635, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/YoutubeDL.py", line 2300, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by dirkf** [comment]
This URL format isn't supported and the attempt to handle it with the Generic extractor results in the error 403.

Having said that, your problem URL looks like a link to mp4 media. If so, you should try something else. _yt-dl_ is for getting media links out of opaque sites, and possibly fetching the linked content. If you already have a media link, use _ffmpeg_ or even _curl_ or _wget_. You may need to pass the URL from which you obtained the link as the value of a `Referer` (_sic_) header.

**Comment by Syriuss** [comment]
https://[yt-dl.org](https://yt-dl.org/)/ is shut down now. The script can't download the executable.

**Comment by dirkf** [comment]
OP is clearly running yt-dl, even if @Syriuss can't manage to read #30839.

**Comment by dirkf** [comment]
The bare URL gets 403 regardless. Additional parameters not provided by OP are needed to download this video. OP could try to find the same content at a site that yt-dl supports.

**Comment by rowanDeveloper** [comment]
> This URL format isn't supported and the attempt to handle it with the Generic extractor results in the error 403.
> 
> Having said that, your problem URL looks like a link to mp4 media. If so, you should try something else. _yt-dl_ is for getting media links out of opaque sites, and possibly fetching the linked content. If you already have a media link, use _ffmpeg_ or even _curl_ or _wget_. You may need to pass the URL from which you obtained the link as the value of a `Referer` (_sic_) header.
