### ISSUE TITLE
[YouTube] Itag 18 not loading anymore

### ISSUE THREAD

**Issue by geroale** [ytdl-org/youtube-dl#32697]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[youtube] Extracting URL: 4fk2prKnYnI
[youtube] 4fk2prKnYnI: Downloading webpage
https://www.youtube.com/youtubei/v1/player
b'{"context": {"client": {"clientName": "IOS", "clientVersion": "17.33.2", "deviceModel": "iPhone14,3", "userAgent": "com.google.ios.youtube/17.33.2 (iPhone14,3; U; CPU iOS 15_6 like Mac OS X)", "hl": "en", "timeZone": "UTC", "utcOffsetMinutes": 0}}, "videoId": "4fk2prKnYnI", "playbackContext": {"contentPlaybackContext": {"html5Preference": "HTML5_PREF_WANTS"}}, "contentCheckOk": true, "racyCheckOk": true}'
{'X-YouTube-Client-Name': '5', 'X-YouTube-Client-Version': '17.33.2', 'Origin': 'https://www.youtube.com', 'User-Agent': 'com.google.ios.youtube/17.33.2 (iPhone14,3; U; CPU iOS 15_6 like Mac OS X)', 'content-type': 'application/json'}
[youtube] 4fk2prKnYnI: Downloading ios player API JSON
https://www.youtube.com/youtubei/v1/player
b'{"context": {"client": {"clientName": "ANDROID", "clientVersion": "17.31.35", "androidSdkVersion": 30, "userAgent": "com.google.android.youtube/17.31.35 (Linux; U; Android 11) gzip", "hl": "en", "timeZone": "UTC", "utcOffsetMinutes": 0}}, "videoId": "4fk2prKnYnI", "params": "CgIQBg==", "playbackContext": {"contentPlaybackContext": {"html5Preference": "HTML5_PREF_WANTS"}}, "contentCheckOk": true, "racyCheckOk": true}'
{'X-YouTube-Client-Name': '3', 'X-YouTube-Client-Version': '17.31.35', 'Origin': 'https://www.youtube.com', 'User-Agent': 'com.google.android.youtube/17.31.35 (Linux; U; Android 11) gzip', 'content-type': 'application/json'}
[youtube] 4fk2prKnYnI: Downloading android player API JSON
[youtube] 4fk2prKnYnI: Downloading m3u8 information
[info] 4fk2prKnYnI: Downloading 1 format(s): 18
[download] Resuming download at byte 205009
ERROR: unable to download video data: HTTP Error 404: Not Found

Process finished with exit code 1
```

## Description

ytdl is not able to download itag 18 any more of certain videos, like this one https://www.youtube.com/watch?v=4fk2prKnYnI. Format 18 is returned by both the API and the webpage, but the URL inside of it is not playable (even after deciphering the signature and n-sig) and returns 404. other formats are working.

**Comment by dirkf** [comment]
Provide the entire log, please, but maybe https://github.com/yt-dlp/yt-dlp/issues/9018 is what you actually meant?

**Comment by dirkf** [comment]
FWIW format 18 of the problem video is fine for me. I was able to watch BB's Thrill being Gone all the way through, and no hardship there.

**Comment by mk-pmb** [comment]
Can confirm, I was able to download the whole video. Original report was probably a fluke on YouTube's side.
