### ISSUE TITLE
ERROR: unable to extract key

### ISSUE THREAD

**Issue by cona684** [ytdl-org/youtube-dl#3269]
This error appears when i try to download an Anime from anitube.se:
http://anitube.xpg.uol.com.br/video/56239/Yu-Gi-Oh-Zero-01
The message:

"
C:\Users\myName-win7\Downloads>youtube-dl "http://anitube.se/video/56239
"
[anitube.se] 56239: Downloading webpage
ERROR: Unable to extract key; please report this issue on https://yt-dl.org/bug
. Be sure to call youtube-dl with the --verbose flag and include its complete ou
tput. Make sure you are using the latest version; type  youtube-dl -U  to update
."

I type "youtube-dl -U" but I'm already using the latest version.

ps: How yout can see the two url above are different. The first is the url that appears when I open the anitube website and the other I have changed because of the list of websites that youtube-dl supported, in this case anitube.se, not anitube.xpg.uol.com.br. 
The first page is always refresh to the second. It's that the problem?

How could I fix this problem?

Thank you, and I'm sorry for the errors on the english grammar.

**Comment by charon2019** [comment]
@dstftw, this can be closed. Site is down.
