### ISSUE TITLE
Duration of the download audio twice as long

### ISSUE THREAD

**Issue by GeorgeSinclair0043** [ytdl-org/youtube-dl#32702]
Hello,

Can you check something
I am developing an app.  Among others it allows to download audiotracks on the device.
I noticed when I download a stream which is audio only, the duration of the song is twice as long as the official duration.
Meaning the track keeps on playing but there is no audio.  
I don't have this issue when I download a stream which is audio+video

// following gives issues
// note: print out of the  duration from the asset also indicates a duration time twice as long
let stream = try await YouTube(videoID: <a videoID>").streams
                          .**filterAudioOnly**()
                          .filter { $0.fileExtension == .m4a }
                          .highestAudioBitrateStream()
let streamURL = stream.url

// this one is fine
let stream = try await YouTube(videoID: <sameID>).streams
                          .filter { $0.includesVideoAndAudioTrack && $0.fileExtension == .mp4 }
                          .highestResolutionStream()
let streamURL = stream.url  

Hope to get your response soon.

Best Regards

**Comment by dirkf** [comment]
1. Use the template.
2. Follow #30839 (point 1 again, but more details).
3. As suggested there, provide verbose logs showing your issue with the actual _youtube-dl_ program (or some Python wrapper code if you really must).

**Comment by dirkf** [comment]
@GeorgeSinclair0043 ?
