### ISSUE TITLE
Docs using a non functioning website to download from

### ISSUE THREAD

**Issue by ch33kaboo** [ytdl-org/youtube-dl#32703]
the docs provide `https://yt-dl.org/downloads/latest/youtube-dl` as a url to curl and output its content in a file, but that website is broken, when visiting the website you find this

# Access denied
Due to a [ruling](https://openjur.de/u/2466945.html) of the Hamburg Regional Court, access to this website is blocked.

**Comment by CEDipEngineering** [comment]
Had the same issue, as a temporary fix, went to the releases tab and found the exe in the latest release: https://github.com/ytdl-org/youtube-dl/releases/download/2021.12.17/youtube-dl.exe

**Comment by dirkf** [comment]
Do follow #30839, which:
* reinforces the need to use the template
* links to temporary instructions
* links to the up-to-date nightly build.
