### ISSUE TITLE
Urgent - Vbox7 support needs to be fixed, so that archivists can save nearly all its' videos before they're permanently lost on Feb 22

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [ytdl-org/youtube-dl#32701]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

On February 22nd Vbox7 will be privating nearly all their videos. Archivists and regular users need an easy way to back up videos/channels, whether individually or en masse.
https://www.reddit.com/r/Archiveteam/comments/19d6ou7/video_platform_vbox7_is_about_to_restrict_access/

Related issues:
https://github.com/ytdl-org/youtube-dl/pull/29680
https://github.com/yt-dlp/yt-dlp/pull/8711
https://github.com/yt-dlp/yt-dlp/pull/5661
https://github.com/yt-dlp/yt-dlp/issues/1098

**Comment by dirkf** [comment]
Please test #32710 and report there.
