### ISSUE TITLE
Access denied for Youtube

### ISSUE THREAD

**Issue by chrisspen** [ytdl-org/youtube-dl#32715]
The README's installation and usage example doesn't work for Youtube URLs.

    $ sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
    $ sudo chmod a+rx /usr/local/bin/youtube-dl
    $ youtube-dl https://www.youtube.com/watch?v=B1A9fjoqTn8
    /usr/local/bin/youtube-dl: line 1: syntax error near unexpected token `newline'
    /usr/local/bin/youtube-dl: line 1: `<h1>Access denied</h1>'

**Comment by nicolaasjan** [comment]
> Access denied

`yt-dl.org` has been taken down by A German court.
See: issue #32495.
