### ISSUE TITLE
filemoon.sx jwplayer error

### ISSUE THREAD

**Issue by leetfin** [ytdl-org/youtube-dl#32716]
## Checklist

- [x] I'm reporting a broken site support
- [x] I'm running youtube-dl 2024.02.03 [4416f82c8]
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
Downloads>youtube-dl --verbose https://filemoon.sx/d/dylsgj1mbwn5/video_2024-01-28_02-44-36.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://filemoon.sx/d/dylsgj1mbwn5/video_2024-01-28_02-44-36.mp4']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2024.02.03 [4416f82c8] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 3.4.4 (CPython AMD64 32bit) - Windows-10-10.0.22621 - OpenSSL 1.0.2d 9 Jul 2015
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev, ffprobe 6.0-full_build-www.gyan.dev
[debug] Proxy map: {}
[FileMoon] dylsgj1mbwn5: Downloading webpage
ERROR: Unable to extract jwplayer sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\YoutubeDL.py", line 863, in wrapper
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\YoutubeDL.py", line 959, in __extract_info
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 570, in extract
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\filemoon.py", line 34, in _real_extract
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 1100, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract jwplayer sources; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Site not working with error in verbose log. Please let me know if any other information is needed, thank you!

**Comment by dirkf** [comment]
The variable name in the obfuscated JS has changed:
'''diff
--- old/youtube_dl/extractor/filemoon.py
+++ new/youtube_dl/extractor/filemoon.py
@@ -31,7 +31,7 @@
         unpacked = decode_packed_codes(packed)
         jwplayer_sources = self._parse_json(
             self._search_regex(
-                r'(?s)player\s*\.\s*setup\s*\(\s*\{\s*sources\s*:\s*(.*?])', unpacked, 'jwplayer sources'),
+                r'(?s)(?:videop|player)\s*\.\s*setup\s*\(\s*\{\s*sources\s*:\s*(.*?])', unpacked, 'jwplayer sources'),
             video_id, transform_source=js_to_json)
 
         formats = self._parse_jwplayer_formats(jwplayer_sources, video_id)
```

**Comment by nicolaasjan** [comment]
Works as advertised. 😀️

```
youtube-dl -v --ignore-config -o '~/Desktop/%(title)s.%(ext)s' https://filemoon.sx/d/dylsgj1mbwn5/video_2024-01-28_02-44-36.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', '-o', '~/Desktop/%(title)s.%(ext)s', 'https://filemoon.sx/d/dylsgj1mbwn5/video_2024-01-28_02-44-36.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2024.02.02
[debug] Lazy loading extractors enabled
[debug] Single file build
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-170-generic-x86_64-with-glibc2.29 - OpenSSL 1.1.1f  31 Mar 2020 - glibc 2.31
[debug] exe versions: ffmpeg N-113412-g0b8e51b584-20240124, ffprobe N-113412-g0b8e51b584-20240124, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[FileMoon] dylsgj1mbwn5: Downloading webpage
[FileMoon] dylsgj1mbwn5: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://be4242.rcr52.ams03.cdn112.com/hls2/01/05449/dylsgj1mbwn5_o/index-v1-a1.m3u8?t=XLKyHPQJUWtLmX3QHA5-nAUz1OBYhirC-IiISfsgZZA&s=1707073640&e=43200&f=27249932&srv=25&asn=33915&sp=2000'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1
[download] Destination: /home/user/Desktop/video_2024-01-28_02-44-36.mp4
[download] 100% of 787.62KiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams file:/home/user/Desktop/video_2024-01-28_02-44-36.mp4
[ffmpeg] Fixing malformed AAC bitstream in "/home/user/Desktop/video_2024-01-28_02-44-36.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:/home/user/Desktop/video_2024-01-28_02-44-36.mp4 -c copy -f mp4 -bsf:a aac_adtstoasc file:/home/user/Desktop/video_2024-01-28_02-44-36.temp.mp4
```

However yt-dlp gives this:

```
ERROR: [Piracy] This website is no longer supported since it has been determined to be primarily used for piracy.
       DO NOT open issues for it

```

**Comment by dirkf** [comment]
If your head hurts when you hit it with a hammer, stop hitting it ...

The site's [copyright policy](https://filemoon.sx/copyright) does not support the categorisation as a "Piracy" site, though the site admins may be too busy with a major European war to enforce it.

Our policy is that the initial support request should agree that
>- [x] I've checked that none of provided URLs violate any copyrights

Personally I can't see that that is a useful or usually truthful (or grammatically correct) statement. Normally I like to see a DMCA policy since that is the sort of stuff that pleases people who care about copyright. This site doesn't mention that but it does say that it will remove content on receipt of a complaint supported by evidence of infringement of third-party rights. 

What we want is to make yt-dl no more liable for copyright infringement than Firefox, Chrome, Safari, or Lynx; in particular:
1. to avoid anything that makes yt-dl seem like a sort of Napster, solely dedicated to processing content whose providers have no right to distribute it
2. to avoid including URLs of such content in test cases (such as those that had to be removed in 2021).
