### ISSUE TITLE
Site Blocked / Project Status

### ISSUE THREAD

**Issue by kj37075** [ytdl-org/youtube-dl#32717]
## Checklist

- [x ] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

[What is the current status of this project? 
Access denied for (https://yt-dl.org/)
Due to a [ruling](https://openjur.de/u/2466945.html) of the Hamburg Regional Court, access to this website is blocked.
Do we have any alternative site or packages yet?]

**Comment by jalea98** [comment]
Same problem, just pull it directly from this repo

```
sudo curl -L https://github.com/ytdl-org/youtube-dl/releases/download/2021.12.17/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```

**Comment by dirkf** [comment]
Do read #30839, really. I would make the pinned issue 10 times larger if GitHub allowed it. And then #32495.
