### ISSUE TITLE
MeTube keep downloading wrong video from Instagram

### ISSUE THREAD

**Issue by 1amtimon** [ytdl-org/youtube-dl#32729]
How to fix MetTube to make it download correct reels? It keep downloading first video link I downloaded.

Sometimes error out that user name password is not supplied. I prefer MeTube as it allows me to directly save videos from the browser rather than connecting to my server to download in case of youtube-dl app.

**Comment by dirkf** [comment]
You need to ask this question in the MeTube tracker, which I guess is [this](https://github.com/alexta69/metube/issues).
