### ISSUE TITLE
Issues to work on, apart from fixing typos in the documentation for a new contributor

### ISSUE THREAD

**Issue by KonstantineTzaferis** [ytdl-org/youtube-dl#32737]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

Hello guys, since I am new to GitHub and would pretty much love to make my first contribution to this project, but being a novice programmer doesn't help and I really don't know where to start.
Most difficult thing for me is to navigate through the different directories of the project and where to look to fix some  issues.
Could anyone help me achieve that by suggesting which folders to look at first and why, and give me a rough image of how the folders and scripts interact?
I know it is a very general question but I think that a starting point should be fine.
Thanks in advance.

**Comment by dirkf** [comment]
Glad to hear of your interest. You could read #29310 (ask any related questions there).

One useful activity, that might also help in learning about the code and the processes involved, would be to go through some of the open Pull Requests, maybe from 2023, and check if 
1. the code can be merged into the latest master without conflicts
2. the download tests run correctly (if not, ask the author for updated tests).

**Comment by KonstantineTzaferis** [comment]
Hey @dirkf thanks for the swift answer, will do!

**Comment by mk-pmb** [comment]
@KonstantineTzaferis
Did the other issue sufficiently answer your questions?
Is there anything left to do in this issue?
Please clarify or close.

**Comment by dirkf** [comment]
Closing for now. OP or anyone else should @ me to take this further.
