### ISSUE TITLE
How to download to the windows equivalent of /dev/null for testing. (basically no output)

### ISSUE THREAD

**Issue by franzkruhm** [ytdl-org/youtube-dl#32744]
- [X ] I'm asking a question

I am looking to download youtube videos for testing straight to what would be the windows equivalent of /dev/null (so basically no saving)

Thanks,

**Comment by dirkf** [comment]
Read about `--simulate` and `--skip-download` in the Manual to see which one works for you.

In Windows (since MS-DOS but even now, I believe) `NUL` is a special file name somewhat equivalent to `/dev/null`.

Or there is WSL.

**Comment by dirkf** [comment]
@franzkruhm ?
