### ISSUE TITLE
WARNING: unable to extract uploader id;

### ISSUE THREAD

**Issue by tianmingxing** [ytdl-org/youtube-dl#32743]
## Checklist

- [ ] I'm reporting a broken site support issue
- [v ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ v] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: eb7338abb
[debug] Python version 3.12.2 (CPython) - macOS-14.2.1-arm64-arm-64bit
[debug] exe versions: none
[debug] Proxy map: {'https': 'http://127.0.0.1:7890', 'http': 'http://127.0.0.1:7890', 'all': 'socks5://127.0.0.1:7890'}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```

## Description

WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
https://rr1---sn-i3b7knzs.googlevideo.com/videoplayback?expire=1710330524&ei=PD7xZY3VFs3s2roP4diNiAg&ip=2407%3Acdc0%3Aafb8%3Aee3c%3Ae4f6%3Af8e2%3A12cc%3A7d3e&id=o-ANgHuK4gGESIdpDOuc9e92fy9AtmHgfow1DMt8DS566-&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=Vt&mm=31%2C26&mn=sn-i3b7knzs%2Csn-oguelney&ms=au%2Conr&mv=m&mvi=1&pl=36&initcwndbps=3507500&spc=UWF9f0GMnQBZjYRbkm0S-_G8IF_pSogCdmzpTFQCSOAppcc&vprv=1&svpuc=1&mime=video%2Fmp4&ns=_tdA8l6Qz7p-nuUfU89wfC8Q&gir=yes&clen=190825193&dur=342.233&lmt=1710273642176036&mt=1710308237&fvip=5&keepalive=yes&fexp=24007246&c=WEB&sefc=1&txp=3309224&n=YOAaWmJp9bv-g30zWG&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAKwaMyNNa5tFJvAp1skYFO-GBv0_u4cPMNqyPTC2i-3KAiArfpdiA16UZby8v5G5BK91P0WkA7lVvQTc_tkJ9xNXdA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=APTiJQcwRgIhAOtR9ZwB520u6FAMgWYiFKezpJPQ-vf5ovx0OLY4CcKSAiEAgqsxkBWvp1BbIP7wOb792uGc0jXAT2U8_izvUQnJiSo%3D
https://rr1---sn-i3b7knzs.googlevideo.com/videoplayback?expire=1710330524&ei=PD7xZY3VFs3s2roP4diNiAg&ip=2407%3Acdc0%3Aafb8%3Aee3c%3Ae4f6%3Af8e2%3A12cc%3A7d3e&id=o-ANgHuK4gGESIdpDOuc9e92fy9AtmHgfow1DMt8DS566-&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=Vt&mm=31%2C26&mn=sn-i3b7knzs%2Csn-oguelney&ms=au%2Conr&mv=m&mvi=1&pl=36&initcwndbps=3507500&spc=UWF9f0GMnQBZjYRbkm0S-_G8IF_pSogCdmzpTFQCSOAppcc&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=_tdA8l6Qz7p-nuUfU89wfC8Q&gir=yes&clen=5770396&dur=342.261&lmt=1710273642455699&mt=1710308237&fvip=5&keepalive=yes&fexp=24007246&c=WEB&sefc=1&txp=3308224&n=YOAaWmJp9bv-g30zWG&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAK38_59qxHcC7UTcCyRbdN4RIN84YeLc0wAwtTpDMRf6AiEAiSQI2KTAsrRFMioAj_NfIRWBVR0LMp6AaRrTxMxr-y4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=APTiJQcwRgIhAOtR9ZwB520u6FAMgWYiFKezpJPQ-vf5ovx0OLY4CcKSAiEAgqsxkBWvp1BbIP7wOb792uGc0jXAT2U8_izvUQnJiSo%3D

**Comment by dirkf** [comment]
Follow #30839 as asked to find the solution. 

>[ ] I've searched the bugtracker for similar bug reports including closed ones
>[ ] I've read bugs section in FAQ

Do it.

**Comment by dirkf** [comment]
NB if your version is reporting this as a `WARNING` you probably have the patched version from `brew`.
