### ISSUE TITLE
unable extract uploader id

### ISSUE THREAD

**Issue by raja29x** [ytdl-org/youtube-dl#32754]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[root@hostb ~]# youtube-dl --verbose -x --audio-format mp3 -o "%(title)s.%(ext)s" https://youtu.be/QzfiR45SB9Q
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-x', '--audio-format', 'mp3', '-o', '%(title)s.%(ext)s', 'https://youtu.be/QzfiR45SB9Q']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.8 (CPython) - Linux-4.18.0-513.18.1.el8_9.x86_64-x86_64-with-almalinux-8.9-Midnight_Oncilla
[debug] exe versions: ffmpeg 4.2.9, ffprobe 4.2.9
[debug] Proxy map: {}
[youtube] QzfiR45SB9Q: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Not able to extract audio or download it.

**Comment by dirkf** [comment]
Please refer to #30839 (again?) fior the solution to your problem.

>[x] I've searched the bugtracker for similar bug reports including closed ones
>[x] I've read bugs section in FAQ

Are you sure?

**Comment by raja29x** [comment]
> Please refer to #30839 (again?) fior the solution to your problem.
> 
> > [x] I've searched the bugtracker for similar bug reports including closed ones
> > [x] I've read bugs section in FAQ
> 
> Are you sure?

yes sir.

**Comment by dirkf** [comment]
I asked because, even if you hadn't found the **Known issue** in the [pinned issue](https://github.com/ytdl-org/youtube-dl/issues/30839) that you were asked to read and follow, a search that included the error message should have produced a list of previous issues with links to either the pinned issue or the known issue itself. [Following the search advice](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+%22Unable+to+extract+uploader+id%22+-label%3Aduplicate) in #30839 should show that issue in the first page of results and sorting by `Best match` could make it the top or only result.
