### ISSUE TITLE
[bogus: wrong project] How do I best hook my stream discontinuity handler into ytdl?

### ISSUE THREAD

**Issue by mk-pmb** [ytdl-org/youtube-dl#32759]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I want to run a quick command every time a stream discontinuity happens. (To monitor and predict their timing.)
What's the best way to hook that in? Do I have to parse log output externally (piping to a script) or can I easily hook into that from python?
I happen to already have a wrapper that sets up import paths before calling `youtube_dl._real_main()`, so maybe I could monkey-patch something from there.
I'm trying not to patch the files inside the repo so I can always just pull to update.

**Comment by dirkf** [comment]
Are you talking about M3U8 manifests with `#EXT-X-DISCONTINUITY`, as in #28159, #31368?

Which I believe should be handled as multi-video playlists, if only multi-video worked properly.
