### ISSUE TITLE
How to download the youtube number-only video

### ISSUE THREAD

**Issue by scihou-github** [ytdl-org/youtube-dl#32765]
I have subscribed a youtube channel, I want to download some videos by yt-dlp ,but it shows that

ERROR: [youtube] h7aSM88pUv8: Join this channel to get access to members-only content like this video, and other exclusive perks.

so I need your help , thanks all.

######################################################################
  WARNING!
  IGNORING THE FOLLOWING TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE
######################################################################

-->

## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by dirkf** [comment]
1. #30839: "... if you were actually using _yt-dlp_ ..."
2. Complete the checklist
3. Why not write the question where you were asked?
>WRITE QUESTION HERE

Probably the same answer applies for _yt-dlp_ as for _youtube-dl_. Join the channel using a YT account and then invoke yt-dl[p] with authentication parameters for that account (cookies, or username/pw if that works).
