### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by another-github-username** [ytdl-org/youtube-dl#32766]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
C:\Users\Naeem>youtube-dl --verbose "https://www.youtube.com/watch?v=RRY1jrIDhvU&t=29s"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=RRY1jrIDhvU&t=29s']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.12.1 (CPython) - Windows-11-10.0.22631-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] RRY1jrIDhvU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Naeem\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Naeem\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\Naeem\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Naeem\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Naeem\AppData\Local\Programs\Python\Python312\Lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
Youtube-dl is unable to extract the uploader's id, returns RegexNotFoundError in attempt to do so

**Comment by grantshandy** [comment]
I'm experiencing the same bug with version 2021.12.17 on Linux (NixOS).

**Comment by themagic10** [comment]
This is a known issue, refer to [#30839](https://github.com/ytdl-org/youtube-dl/issues/30839) known issues section for your solution

**Comment by dirkf** [comment]
>[ ] I'm reporting a broken site support issue

You are.

>[x] I've searched the bugtracker for similar bug reports including closed ones
>[x] I've read bugs section in FAQ

But surprisingly this didn't reveal the master issue?

**Comment by softyoda** [comment]
What is the original source of the issue ??? https://github.com/ytdl-org/youtube-dl/issues/30839 doesn't look like a solution (but it's also listed here : https://github.com/ytdl-org/youtube-dl/issues/32774 and here https://github.com/ytdl-org/youtube-dl/issues/32754 and everywhere it always redirect to pinned message but it doesn't redirect to the source issue of this recurrent issue. How would one found the issue without having to read the 92 opened issue that has "uploader id" ?

**Comment by dirkf** [comment]
By simply reading the pinned issue you'll see this, with links to master issues:
>...
>Known issues, fixed in git master code, or update/install from the nightly release repo:
NY
>*    YouTube: Unable to extract yt initial data on playlist (also a swathe of related errors)
>*    YouTube: Unable to extract uploader id 
>,,,

**Comment by softyoda** [comment]
![firefox-Photopea__Online_Photo_Editor_—_Mozilla_Firefox-13-27_21-mai-24_6192-88903_786-777](https://github.com/ytdl-org/youtube-dl/assets/13988751/94dc188d-b5f5-4f49-a6c4-0bbbb024b849)

I'm sorry, i've spend 20min trying to solve this simple error, there is too much to read, 
i'll simply not download my liked youtube video and create another playlist for "liked" video in order to avoid having the capped 5000 playlise of liked video remove first entries.

**Comment by dirkf** [comment]
Just install the latest nightly build, like it says. You don't have to worry about any other historical stuff.

**Comment by softyoda** [comment]
I wouldn't have spent 20 min reading all if downloading the last nightly release would have directly solved my issue (and i wouldn't have made a low quality meme in this thread). But i can't really open a new issue on https://github.com/ytdl-org/ytdl-nightly so i don't really know what else to do than shitpost meme here before being marked as spam.

**Comment by dirkf** [comment]
If the problem is not fixed by the latest nightly, you are probably still running the old version; make sure it's fully uninstalled.

Should the nightly build have a problem, as the nightly repo says, open an issue here (yes, #30839 again). Your original log is clearly the last stable release, where the bug was latent at the time of release and subsequently revealed by YT changes.

I don't think it's too onerous to expect people to search for a known fixed issue in the list, which is so short that Ctrl+F isn't really needed. Still, the meme was funny enough.
