### ISSUE TITLE
Broken subtitles. Timeline isn't correct. All subtitles grouped in two duplicate lines at the top of the VTT file

### ISSUE THREAD

**Issue by obana48** [ytdl-org/youtube-dl#32760]
## Checklist

+ [ ] I'm reporting a broken site support issue
+ [ ] I've verified that I'm running youtube-dl version **2021.12.17**
+ [ ] I've checked that all provided URLs are alive and playable in a browser
+ [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
+ [ ] I've searched the bugtracker for similar bug reports including closed ones
+ [ ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--sub-lang', 'en', '--write-auto-sub', '--skip-download', 'iVmaQdT8AKk']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Single file build
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-26-generic-x86_64-with-glibc2.35 - OpenSSL 3.0.2 15 Mar 2022 - glibc 2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] iVmaQdT8AKk: Downloading webpage
[debug] [youtube] Decrypted nsig YwKFdeGEi4mBDhhW => URg2w5xwRJY0KQ
[debug] [youtube] Decrypted nsig RsmGEIu1cU03pYO5 => yAB-DmY20FTGDw
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: IMPERIALISM - DECADENT, PARASITIC, AND DOOMED EPISODE 8 - WITH JOTI BRAR - CHANGES AND REARRANGES-iVmaQdT8AKk.en.vtt

```

## Description

Provided YT video does have working subtitles. For some reason I cannot download them properly. Instead of correct timeline I'm getting a weird output. The subtitles are grouped into 1 duplicated lines on top of the file. The timeline items do not have any text.

The beginning of the VTT file looks like this:

WEBVTT
Kind: captions
Language: en

00:00:00.760 --> 00:00:02.990 align:start position:0%

hello Garland Nixon here it's Friday  morning and I'm hanging out with Jody BR  and I suspect that we're going to learn  something very important let's  [Music]  [Music]

00:00:02.990 --> 00:00:04.950 align:start position:0%
hello Garland Nixon here it's Friday  morning and I'm hanging out with Jody BR  and I suspect that we're going to learn  something very important let's  [Music]  [Music]

00:00:04.950 --> 00:00:06.710 align:start position:0%
00:00:06.710 --> 00:00:09.230 align:start position:0%
00:00:09.230 --> 00:00:09.240 align:start position:0%
00:00:09.240 --> 00:00:26.470 align:start position:0%
...

**Comment by obana48** [comment]
This bug was resolved in the yt-dlp fork. At least to this date everything works great in yt-dlp.

**Comment by dirkf** [comment]
1. Please complete the template in future.
2. Your issue should be resolved in the nightly build, per https://github.com/ytdl-org/youtube-dl/issues/32684#issuecomment-1880872670.
3. By all means reopen this issue if that does not appear to be so.
