### ISSUE TITLE
Download videos from xvideos.com

### ISSUE THREAD

**Issue by thiliapr** [ytdl-org/youtube-dl#32773]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.xvideos.com/video.iedppof9ba0/hot_girl_masturbate
- Playlist: [https://www.xvideos.com/favorite/89411403/_](https://www.xvideos.com/favorite/89411403/_)

## Description

Looks like it used to be available? But it is no longer available. #31451

**Comment by dirkf** [comment]
The site is supported but the active PR #30774 to improve the extractor has been overtaken by a recent site update.

From https://github.com/ytdl-org/youtube-dl/pull/30774#issuecomment-2056915529:

>If anyone would like to document the site changes with regard to the various types of pages that the site supports and the PR extractor is meant to support, that would make it a lot quicker to update.

Please provide such comments in the PR.
