### ISSUE TITLE
discord.py music bot

### ISSUE THREAD

**Issue by RezaCyber3000** [ytdl-org/youtube-dl#32777]
[youtube] VOmIplFAGeg: Downloading webpage
[youtube] Downloading just video VOmIplFAGeg because of --no-playlist
[youtube] VOmIplFAGeg: Downloading player 5d0dbf62
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output

File "C:\Users\Administrator\Downloads\미츠하\미츠하.py", line 42, in <lambda>
    data = await loop.run_in_executor(None, lambda: ytdl.extract_info(url, download=not stream))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

is Latest version

**Comment by dirkf** [comment]
1. Review #30839, as asked, to find a solution, for you or for the supplier of your bot, of this **known problem**.
2. If that didn't work (it will), complete the **correct issue template**, following #30839.
