### ISSUE TITLE
android-(Bug) The following content is not available on this app. Watch this content on the latest version of YouTube

### ISSUE THREAD

**Issue by liaolingfen4** [ytdl-org/youtube-dl#32771]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by liaolingfen4** [comment]
update client android params to "CgIIAQ==" can't solve this issue

**Comment by dirkf** [comment]
1. Review #30839.
2. The title of this issue doesn't match anything generated by _youtube-dl_: per #30839, consider whether you are reporting it in the correct forum.  
3. If still appropriate, complete the **correct** template.

**Comment by dirkf** [comment]
@liaolingfen4 ?

**Comment by liaolingfen4** [comment]
close the issue
