### ISSUE TITLE
downloading from udemy

### ISSUE THREAD

**Issue by ctamietto** [ytdl-org/youtube-dl#32778]
I'm trying to download a free course from udemy using the docker container 

**docker run --rm -it jauderho/yt-dlp:latest -u **!!!!!!!!!!** -p **???????** -o '~/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/java-tutorial/**

using user and password that I use to login to udemy 
and I get this error

**[udemy:course] Downloading login popup
ERROR: [udemy:course] java-tutorial: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)**

I've tried also to download courses that I have regularly buyed but the error is always the same .

So the question is :

can I use youtube-dl to download courses from udemy or is no longer possible ?
I'm doing something wrong ?

thanks for any response

**Comment by dirkf** [comment]
#30839: "... if you were actually running **yt-dlp** ..."

Regarding the support for udemy here, probably also at yt-dlp, see https://github.com/ytdl-org/youtube-dl/issues/29410#issuecomment-1110932846 and related issues.
