### ISSUE TITLE
/usr/local/bin/youtube-dl: line 1: syntax error near unexpected token `newline' /usr/local/bin/youtube-dl: line 1: `<h1>Access denied</h1>'

### ISSUE THREAD

**Issue by tenet-tenet** [ytdl-org/youtube-dl#32787]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

it continues to give me this error: 
/usr/local/bin/youtube-dl: line 1: syntax error near unexpected token `newline'
/usr/local/bin/youtube-dl: line 1: `<h1>Access denied</h1>'
why?

**Comment by dirkf** [comment]
Please review #30839 as asked for the solution to your problem.
