### ISSUE TITLE
Error: "Unsupported URL" because of website change ORF 

### ISSUE THREAD

**Issue by FranzWinter61** [ytdl-org/youtube-dl#32798]
WRITE QUESTION HERE

ORF Austrian Broadcasting changed 
from: mediathek.orf.at 
to: on.orf.at 
I read "How can I detect whether a given URL is supported by youtube-dl?" 
How to change or extend the supported URLs (seen by --extractor-descriptions) ? 
I don't know, if they also changed the decoder. 

Systeminfos: 
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3

**Comment by dirkf** [comment]
There was some sort of tweak per #30564 but now we have to back-port https://github.com/yt-dlp/yt-dlp/pull/9113. Then 
```console
$ python -m youtube_dl -vF 'https://on.orf.at/video/14178243/universum-portugal-wildnis-zwischen-land-und-ozean'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'https://on.orf.at/video/14178243/universum-portugal-wildnis-zwischen-land-und-ozean']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: b966ccb25
[debug] Python 2.7.15 (CPython i686 32bit) - Linux-6.1.0-20-686-pae-i686-with-debian-12.5 - OpenSSL 1.1.1a  20 Nov 2018 - glibc 2.1.3
[debug] exe versions: ffmpeg 5.1.4-0, ffprobe 5.1.4-0
[debug] Proxy map: {}
[orf:on] 14178243: Downloading webpage
[orf:on] 14178243: Downloading JSON metadata
[orf:on] 14178243: Downloading MPD manifest
[orf:on] 14178243: Downloading MPD manifest
[orf:on] 14178243: Downloading m3u8 information
[orf:on] 14178243: Downloading m3u8 information
[info] Available formats for 14178243:
format code            extension  resolution note
dash-p0va0br1819370-0  mp4        960x540    DASH video 1819k , mp4_dash container, avc1.4d401f, 25fps, video only
dash-p0aa0br191276-0   m4a        audio only [eng] DASH audio  191k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-p0va0br1819370-1  mp4        960x540    DASH video 1819k , mp4_dash container, avc1.4d401f, 25fps, video only
dash-p0aa0br191276-1   m4a        audio only [eng] DASH audio  191k , m4a_dash container, mp4a.40.2 (48000Hz)
hls-1800-0             mp4        unknown    1800k 
hls-1800-1             mp4        unknown    1800k  (best)
$ 
```
There are a few other extractor changes that have to be addressed, but eventually this will have a PR and be incorporated into the nightly release (#30839).

**Comment by FranzWinter61** [comment]
Where to find the "last nightly build"? 
Because I'm blocked "Due to a [ruling](https://openjur.de/u/2466945.html) of the Hamburg Regional Court, access to this website is blocked."

**Comment by dirkf** [comment]
Please test #32802 and report there.

**Comment by FranzWinter61** [comment]
> It's linked above (see "Known Issues"), but won't yet include the ON.ORF update that I have working in test.
> 
Sorry to ask again after your update : what & where to download? Is there an .exe, or must I download the "changed files" from [ORF] Extractor overhaul #32802 ? 
I'm blind to see "Known Issues"

**Comment by dirkf** [comment]
The easiest way to test the PR is to fetch the PR code and run that code with _python_ (so you need to have installed, or install, a Python program).  Let's say you're in a terminal shell. As you have Windows, I'll assume _cmd_ and that you're working in a directory where you can save the code (maybe make a new subdirectory and cd into it). I think Windows has _curl_ now, but you could fetch the ZIP using your browser:
```
curl -L -o ytdl_pr_32802.zip "https://github.com/ytdl-org/youtube-dl/archive/pull/32802/head.zip"
```
As there may be no actual unzip command in your Windows, use Explorer to expand the downloaded `ytdl_pr_32802.zip` file in the directory: name the top-level folder (with `youtube_dl` subdirectory) `youtube-dl` and make it the current directory in your terminal shell. Then run this to check the installation (maybe your Python is called `python3`: use that if so; add `.exe` if you're worried that some `python.com` or `python.bat` may be on the Windows executable search path):
```
python -m youtube_dl --version
```
If that shows a sensible result, you can try out actual download commands, using `python -m youtube_dl` (or `python3 -m youtube_dl`) wherever you would have used `youtube-dl` (or `youtube-dl.exe`), so long as you don't change the current directory.

**Comment by FranzWinter61** [comment]
Tests with local Python installation (Vers. python-3.12.3-amd64): 
A) python -m youtube_dl --version
2021.12.17 

In general the new URL on.orf.at will be recognized. 
Current problem: no sound, video only. Best case extra file with the sound. 
Problem: "malformed AAC bitstream detected. Install ffmpeg or avconv to fix this automatically."

B) python -m youtube_dl --list-extractors: concerning ORF this brings: 
orf:collection
orf:fm4:story
orf:iptv (CURRENTLY BROKEN)
orf:on
orf:sound
ORFONLive

C) Formats of an video from this morning: 
python -m youtube_dl --list-formats https://on.orf.at/video/14228923/fit-aktiv-fuer-junggebliebene-folge-136

[orf:on] 14228923: Downloading webpage
[orf:on] 14228923: Downloading JSON metadata
[orf:on] 14228923: Downloading m3u8 information
[orf:on] 14228923: Downloading m3u8 information
[orf:on] 14228923: Downloading MPD manifest
[orf:on] 14228923: Downloading MPD manifest
[info] Available formats for 14228923:
format code            extension  resolution note
hls-audio-Deutsch-0    mp4        audio only [de]
hls-audio-Deutsch-1    mp4        audio only [de]
dash-p0aa0br192000-0   m4a        audio only [de] DASH audio  192k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-p0aa0br192000-1   m4a        audio only [de] DASH audio  192k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-p0va0br801328-0   mp4        640x360    DASH video  801k , mp4_dash container, avc1.64001e, 25fps, video only
dash-p0va0br801328-1   mp4        640x360    DASH video  801k , mp4_dash container, avc1.64001e, 25fps, video only
hls-992-0              mp4        640x360     992k , video only
hls-992-1              mp4        640x360     992k , video only
dash-p0va0br1801256-0  mp4        960x540    DASH video 1801k , mp4_dash container, avc1.64001f, 25fps, video only
dash-p0va0br1801256-1  mp4        960x540    DASH video 1801k , mp4_dash container, avc1.64001f, 25fps, video only
hls-1992-0             mp4        960x540    1992k , video only
hls-1992-1             mp4        960x540    1992k , video only
dash-p0va0br3001054-0  mp4        1280x720   DASH video 3001k , mp4_dash container, avc1.64001f, 25fps, video only
dash-p0va0br3001054-1  mp4        1280x720   DASH video 3001k , mp4_dash container, avc1.64001f, 25fps, video only
hls-3192-0             mp4        1280x720   3192k , video only
hls-3192-1             mp4        1280x720   3192k , video only (best)

D) Test Download with specific format: 
python -m youtube_dl https://on.orf.at/video/14228923/fit-aktiv-fuer-junggebliebene-folge-136 --format "dash-p0va0br1801256-0"  (I like a smaller format for archiving) 
[orf:on] 14228923: Downloading webpage
[orf:on] 14228923: Downloading JSON metadata
[orf:on] 14228923: Downloading m3u8 information
[orf:on] 14228923: Downloading m3u8 information
[orf:on] 14228923: Downloading MPD manifest
[orf:on] 14228923: Downloading MPD manifest
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 160
[download] Destination: Fit Aktiv für Junggebliebene - Folge 136-14228923.mp4
[download] 100% of 355.73MiB in 00:43
WARNING: 14228923: malformed AAC bitstream detected. Install ffmpeg or avconv to fix this automatically.
=> Problem: the video is without sound 

E) Test Download without any format specification (= best quality) 
python -m youtube_dl https://on.orf.at/video/14228923/fit-aktiv-fuer-junggebliebene-folge-136
[orf:on] 14228923: Downloading webpage
[orf:on] 14228923: Downloading JSON metadata
[orf:on] 14228923: Downloading m3u8 information
[orf:on] 14228923: Downloading m3u8 information
[orf:on] 14228923: Downloading MPD manifest
[orf:on] 14228923: Downloading MPD manifest
WARNING: You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 160
[download] Destination: Fit Aktiv für Junggebliebene - Folge 136-14228923.fhls-3192-1.mp4
[download] 100% of 589.10MiB in 00:39
[dashsegments] Total fragments: 161
[download] Destination: Fit Aktiv für Junggebliebene - Folge 136-14228923.fdash-p0aa0br192000-1.m4a
[download] 100% of 37.20MiB in 00:15
=> Problem: the video itself is WITHOUT sound. The sound is in an extra file  

F) Test another film: 
python -m youtube_dl https://on.orf.at/video/14228865/reisezeit-traumhafte-ziele-piemont --list-formats

=> The same results

**Comment by dirkf** [comment]
When (as in the cases shown) the site only has separate audio-only and video-only streams, you'll need to install _ffmpeg_; then, automatically, the streams will be merged and any "malformed AAC bitstream" will also be fixed: https://github.com/ytdl-org/youtube-dl#user-content-do-i-need-any-other-programs

**Comment by FranzWinter61** [comment]
OK. Got _ffmpeg_ (I take it from [https://github.com/BtbN/FFmpeg-Builds/releases](https://github.com/BtbN/FFmpeg-Builds/releases) ). 
Afterwards I saw I have _ffmpeg_ in the same directory in the previous youtube_dl with a windows .exe). 
=> Problem solved: sound will be merged with the video. 
(I'm not very happy to get no smaller video formats). 

How to get a windows .exe ? I'll search for it.

**Comment by dirkf** [comment]
Once we're happy that the ORF stuff is working about as well as it should (and it seems to be), I'll merge the PR; then it'll automatically be built into the nightly release, which includes a Windows single file .exe version like the one you have.

**The nightly release page is linked from the Known Issues heading in #30839**.

**Comment by FranzWinter61** [comment]
Looking forward to the windows .exe. I tried to make it with _pyinstaller_, but had no success ("_EXE-00.toc is non existent_"). Runtime ("ImportError: attempted relative import with no known parent package") 
Maybe because of "will merge the PR"? We will see. 
Thank you very much for dealing with this case so fast!

**Comment by dirkf** [comment]
The [nightly build](https://github.com/ytdl-org/ytdl-nightly/blob/master/.github/workflows/build.yml) uses _py2exe_ with Python 3.4.4 for Windows. These are the key commands:
```
python -m pip install --upgrade "pip<19.2" "setuptools<44" "wheel<0.34.0" py2exe==0.9.2.2
curl -L -o pycrypto.whl "https://web.archive.org/web/20200627032153/http://www.voidspace.org.uk/python/pycrypto-2.6.1/pycrypto-2.6.1-cp34-none-win32.whl"
python -m pip install pycrypto.whl
del pycrypto.whl
python setup.py py2exe
```

**Comment by dirkf** [comment]
Yes, you need to use an old Python version as I noted. v3.4.4 was specifically chosen to support both old and new Windows systems, but you don't need to worry about that.

What you can do with your 3.12 is to install the PR or nightly build [using _pip_](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/). This will be somewhat faster than the single-file .exe because (1) it doesn't have to unpack the _python_ and _youtube_dl_ programs on each run (2) 3.12 should be faster than the bundled _python_.

**Comment by mundstein** [comment]
This is very helpful, but I am getting different results.

    python -m youtube_dl --version
    2021.12.17

    python -m youtube_dl --list-extractors | grep orf

results in (different from above)

```
orf:burgenland
orf:fm4
orf:fm4:story
orf:iptv
orf:kaernten
orf:noe
orf:oberoesterreich
orf:oe1
orf:oe3
orf:salzburg
orf:steiermark
orf:tirol
orf:tvthek
orf:vorarlberg
orf:wien
```
Notably `orf:on` is missing. This results in a fallback to "generic" and a failed download. 

How do I add this extractor? It seems to be present in the source code. (in `extractor/orf.py`).

**Comment by dirkf** [comment]
Please install a nightly build that includes the updated extractor module. The hint is that 2021.12.17 < 2024.06.11. See #30839.
