### ISSUE TITLE
yt-dl.org is closed, see output message below:

### ISSUE THREAD

**Issue by robertnormanhiggins** [ytdl-org/youtube-dl#32793]
<h1>Access denied</h1>

<p>
  Due to a <a href="https://openjur.de/u/2466945.html" target="_blank">ruling</a> of the Hamburg Regional Court, access to this website is blocked.
</p>

<hr />

<h1>Zugriff gesperrt</h1>

<p>
  Aufgrund eines <a href="https://openjur.de/u/2466945.html" target="_blank">Urteils</a> des Landgerichts Hamburg ist der Zugriff auf diese Website gesperrt.
</p>

**Comment by dirkf** [comment]
Review #30839 for the temporary (?) work-around. The nightly build directs you to go directly to this project site.
