### ISSUE TITLE
Dumb question: Technical difference between downloading a YouTube video and watching it?

### ISSUE THREAD

**Issue by Rekrullurker** [ytdl-org/youtube-dl#32808]
## Checklist

- [X ] I'm asking a question
- [X ] I've looked through the README and FAQ for similar questions
- [X ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

As I'm sure you know, when you watch a video on YouTube, you will be force-fed inline video ads every few minutes, and pretty much every purported method of blocking them doesn't work. Yet, when you download a video, presumably it's getting the file from the exact same source, only there are no ads, just the video file.

I'm curious about the technical differences between downloading a video vs. watching it in a browser. What is it that programs like youtube-dl and yt-dlp do differently than a web browser, that the site just sends the entire video uninterrupted without ads?

Is it a case of the official YouTube video player being able to be remotely controlled by YouTube, so that when they tell it to pause the video and show an ad, it does it?

If that's the case, why has nobody ever written a browser add-on that simply replaces the official player with one that won't obey YouTube's commands? It seems like that would be a better option for avoiding ads, than trying to write some convoluted ad blocker that doesn't even work.

Or is there some technical reason that a stand-alone program can download just the video, but watching a video can only be done with ads?

And yes, I know there are command line options to use youtube-dl to stream videos to a stand-alone media player, like VLC, I'm wondering why the in-browser video player can't be replaced so you get a normal YouTube experience, but without the rage-inducing ads.

**Comment by dirkf** [comment]
When you watch a video on the YT website you are watching through the megabytes of JS code that YT includes in each video page to subvert straightforward HTML5 video. Some of that implements the exciting social media features offered by YT, some selects pointless ads that you're going to ignore.

**Comment by Rekrullurker** [comment]
Why has nobody ever made a browser add-on that selectively bypasses the code that allows them to show ads?

**Comment by dirkf** [comment]
Of course people have found various techniques for bypassing ads but an arms race against YT is not going to be successful. DNS blacklists may have been effective but YT is currently [upping](https://github.com/yt-dlp/yt-dlp/issues/10108) the [stakes](https://github.com/yt-dlp/yt-dlp/issues/10128), so I don't know what the current status is (and anyway this is not on-topic for this tracker).
