### ISSUE TITLE
Court ruling, forked project, what is going on?

### ISSUE THREAD

**Issue by allanonmage** [ytdl-org/youtube-dl#32807]
## Checklist

 N/A due to a court ruling

- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

N/A due to a court ruling

## Question

I haven't used YoutubeDL in a long time, but after 15 minutes of coming back I'm thoroughly confused.  I've read the wikipedia page, a page on reddit, a few bug trackers that mentioned the issue, and looked around here too.  I don't understand why a Github page is linking to a seized domain if there are also releases here, nor why there are 2 projects with the same name.  Getting around a seized-in-only-1-country domain should be relatively easy for a project, and distributing software is also pretty easy.  Having an FAQ is easy, but it seems the FAQ here is from a long time ago and deals with the technical aspects.

Do you guys make Windows releases?  Which one is the official project?

**Comment by dirkf** [comment]
What is the other project with the same name?

Also, instead of Reddit read #30839, where the nightly releases including Windows versions are linked. That's why that pinned issue is so named.

**Comment by dirkf** [comment]
I presume that answered your question, if not mine.
