### ISSUE TITLE
/usr/local/bin/youtube-dl: 2: Syntax error: newline unexpected

### ISSUE THREAD

**Issue by ThePrivacyPlayer** [ytdl-org/youtube-dl#32800]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17** : **Cannot verify - command is broken**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones : https://github.com/ytdl-org/youtube-dl/issues/631
- [X] I've read bugs section in FAQ

## Verbose log

When using command `(sudo) youtube-dl URL` or `(sudo) youtube-dl --update`

```
/usr/local/bin/youtube-dl: 2: Syntax error: newline unexpected
```

When using `(sudo) youtube-dl --version`
```
/usr/local/bin/youtube-dl: line 1: syntax error near unexpected token `newline'
/usr/local/bin/youtube-dl: line 1: `<h1>Access denied</h1>'
```

## Description

I just installed youtube-dl using the curl command followed by chmod, as indicated in the installation section. However, the `youtube-dl` command always gives an error, no matter how it's used, and since the very first use which was done right after chmod.
I'm running python 3.11.2. I tried updating the command, but that also gives an error (as indicated above), and tried updating my whole system with apt but there was nothing to update.

Thanks for any help or insight you may provide here if it's an issue on my side.

**Comment by ThePrivacyPlayer** [comment]
Hi @dirkf ,

Thank you for your update.

Unfortunately I don't really understand what you're saying. I haven't used anything from ytdl.org, I used the exact commands documented here on github in the "INSTALLATION" section (see screenshot below).
![2024-05-29 22_00_33-ytdl-org_youtube-dl_ Command-line program to download videos from YouTube com an](https://github.com/ytdl-org/youtube-dl/assets/161950640/91f314c9-63ab-4176-926c-36a12d3d8889)

Also, after reviewing your linked post for known issues (including related errors for the first one), I don't seem to be able to identify which one my issue corresponds to, as none of them appear to address a failure of the command itself. My verbose logs (using '--verbose') is just the lines I shared (I can send a screenshot if needed), while the logs of all other known issues (i checked every single one of them) are many lines long, and most of them appear to be an issue with extracting data, while for me the command doesn't launch and fails from the getgo at execution. Am I missing or misunderstanding something?

As for the nightly builds, I'm not a developer, and while I did search and read a bunch about developer instructions, I wasn't able to understand if any of it was showing how to install from a nightly build, I'm extremely lost right now, and I don't understand what I'm doing wrong, since I used the exact installation instructions and it seems to work for other people...

Could you help me out here, please?

**Comment by dirkf** [comment]
The _youtube_dl_ program that you thought you were downloading isn't one, but just a page saying some German idiots have blocked the yt-dl.org site.

#30839 explains this and gives you an alternative `README` to follow.

But rather than downloading the old 2021.12.17 version which has **many known bugs** (some are listed in #30839), you should download the appropriate **nightly** build which works much better. This isn't a developer thing: it's just that web sites change so frequently that the program needs to be updated as and when, rather than waiting for a new stable release. Again, the nightly build repository is linked from #30839, alongside the the heading for Known Issues. It's a copy of the main repository that automatically makes a release on any (GMT) night when the main repository has been updated.

**Comment by ThePrivacyPlayer** [comment]
Thank you so much, that makes a lot more sense! And I finally understood how to use the nightly build. Now let me go tackle the next error and get this thing working!

**Comment by aykincakaloz** [comment]
I believe this information should be provided in the installation instructions page. We can make a PR if you agree.

I am not in Germany but I have ran into this. Who knows how widespread it is ?
