### ISSUE TITLE
No more compiled binaries for the patched version?

### ISSUE THREAD

**Issue by Rekrullurker** [ytdl-org/youtube-dl#32818]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
For some time I've been using the patched version of youtube-dl from here;

https://github.com/ytdl-patched/youtube-dl/releases/

However I tend not to update until there's a problem, and up until tonight, it had been working fine. Tonight it won't download from YouTube, so I tried to grab the latest release, but there's no compiled binary. Checking, I found that there hasn't been a binary available since 5/9/24. 

Unfortunately, I don't have the faintest clue how to compile it myself. I have no idea what software I would need, what I would need to download, or how to go about compiling it.

Is the omission of compiled binaries an intentional choice, or has something gone wrong?

Now to address the inevitable response: I have an OLD system that is still running XP. Laugh if you want to, but at the moment, it's what I have, and what I have to use. I can not run the latest yt-dlp, no matter how fantastic it is. My old version of yt-dlp for XP still works, and I did download a newer version by nicolaasjan, but if possible, I'd like to get the latest patched youtube-dl.

**Comment by dirkf** [comment]
That repo was a helpful fallback when releases were not being made here. Now, use a yt-dl nightly release (#30839).

Also, #31585.

**Comment by Rekrullurker** [comment]
The nightly release linked to in the thread you linked to above is dated 6/12/24, almost a week ago, although the actual binary gives a date of 6/11/24. Regardless of the date, it still won't download anything from YouTube.

**Comment by dirkf** [comment]
What gives a date of 2024-06-11? I think you are seeing a filesystem date-time in your TZ. The release date-time is converted to a tag as UTC. 

>... won't download anything from YouTube

#32815

**Comment by Rekrullurker** [comment]
So, the yt-dll nightly releases you linked to are now over a week behind. Do "nightly releases" not happen nightly?

Which brings me back to my original question: Is the fact that there are no more binaries for the patched version (which IS releasing nightly) intentional, or did something break?

**Comment by dirkf** [comment]
I wouldn't see the point of releasing identical code. Releases are built when the code changes. Had anyone submitted a suitable patch for #32202 it might already have been merged and released, but soon https://github.com/ytdl-org/youtube-dl/pull/32820 will be.

In any case it's [no longer so critical](https://github.com/ytdl-org/youtube-dl/issues/32202#issuecomment-2179729975).
