### ISSUE TITLE
Running latest source shows version as 2021-12-17

### ISSUE THREAD

**Issue by Pwner45** [ytdl-org/youtube-dl#32819]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

![imagem](https://github.com/ytdl-org/youtube-dl/assets/90919054/d3ec88c6-8757-40c1-abc2-07da700d8760)
I've downloaded the source in https://github.com/ytdl-patched/youtube-dl/releases/tag/2024.06.18.334 and ran it using python (through a batch file in this case)

Running the --version command however shows it as a 2021-12-17 version, not 2024-06-17. I have no idea how that's happening

**Comment by Pwner45** [comment]
Update: ???
![imagem](https://github.com/ytdl-org/youtube-dl/assets/90919054/cb1d7f91-d8ae-4b73-b0f1-b2c79e4e93c0)

**Comment by dirkf** [comment]
That's the last "stable" (aka obsolete, broken) version. When running from checked-out source the version is shown as the HEAD commit.

For non-development use, run a nightly build (#30839).

See #32039.
