### ISSUE TITLE
[YouTube] Broken site support fix

### ISSUE THREAD

**Issue by jakefrombay** [ytdl-org/youtube-dl#32816]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
sudo apt install python3-pip
pip3 install --user youtube-dl
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=xo7XrRVxH8Y']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.31 - OpenSSL 3.0.13 30 Jan 2024 - glibc 2.31
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {}
[youtube] xo7XrRVxH8Y: Downloading webpage

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
>WRITE DESCRIPTION HERE

That would be helpful.

But first review #30839 as asked.
