### ISSUE TITLE
'ERROR: too many positional arguments' while trying to download entire playlist

### ISSUE THREAD

**Issue by RagingRift** [ytdl-org/youtube-dl#32814]
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

When I put the link to a playlist as a URL, the program throws the following error:
ERROR: too many positional arguments

What is causing this?

Here is my code:
```
import youtube_dl


def chooseFormat():
    options = ["best", "worst", "bestaudio/best"]
    i = 1
    for option in options:
        print(f"{i}. {option}")
        i += 1

    while True:
        try:
            choice = int(input("Option: "))
            if choice < 1 or choice > len(options):
                raise Exception("That option doesn't exist!")

            return options[choice-1]
        except Exception as e:
            print(e)

def downloadVideo(url:str, chosenFormat: str = "best"):
    video_url = url

    # Define options for youtube-dl
    ydl_opts = {
        'ignoreerrors': True,
        'format': chosenFormat,  # You can specify the format you want, e.g., 'best', 'mp4', etc.
        'outtmpl': 'C:\\Users\\Josh\\Documents\\Python Programs\\YouTube downloader\\Videos\\%(title)s.%(ext)s'
    }

    # Download the video
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download([video_url])

if __name__ == "__main__":
    while True:
        try:
            chosenUrl = input("Paste URL here: ")
            chosenFormat = chooseFormat()
            downloadVideo(chosenUrl, chosenFormat)
            break
        except youtube_dl.utils.ExtractorError and youtube_dl.utils.DownloadError:
            print("Please try again \n\n")
        except Exception as e:
            print(e)
```

**Comment by dirkf** [comment]
Create a yt-dl command that should be the equivalent of what your code will run and compare the `ydl_opts` in the two cases.

Otherwise please show a verbose log of your failing code.

Also consider `raw_input()`:
```console
>>> input('Paste URL here\n')
Paste URL here
https://www.youtube.com/watch?v=crnDkGUdoew
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1
    https://www.youtube.com/watch?v=crnDkGUdoew
         ^
SyntaxError: invalid syntax
>>> 
```

**Comment by dirkf** [comment]
@RagingRift ?

**Comment by RagingRift** [comment]
@dirkf  sorry for the late reply. When you say create a yt-dl command, do you mean run it using the executable commandline application? If so i cannot install the exe as it has the install page has been blocked and i can't find it anywhere in the repository.

As for the verbose log literally the only thing it says is "ERROR: too many positional arguments".

And why use raw_input()? I read up on it briefly and apparently newer versions of python have made it so input() has the functons of raw_input(). 

Sorry about btw this im extremely new to programming

**Comment by dirkf** [comment]
Install the nightly build (see #30839).

**Comment by RagingRift** [comment]
Ok i found the exe but the program throws the following error when ran:
![Screenshot 2024-06-25 071018](https://github.com/ytdl-org/youtube-dl/assets/127786147/e4296972-8a61-44c4-acf3-ddf70219bf44)

I dont know if I'm doing something wrong here or its a bug that needs patching

**Comment by RagingRift** [comment]
Nevermind i found the issue. Do you want to know what it was?



The fucking playlist was on private :)

**Comment by dirkf** [comment]
So, did you manage to formulate a successful yt-dl command (eg, using cookies exported from a browser session where you could access the playlist and watch a video from the list)?
