### ISSUE TITLE
Due to a ruling of the Hamburg Regional Court, access to this website is blocked. when try to download

### ISSUE THREAD

**Issue by abdul202** [ytdl-org/youtube-dl#32822]
when i try to download the file i got this message
https://yt-dl.org/downloads/latest/youtube-dl

Access denied
Due to a [ruling](https://openjur.de/u/2466945.html) of the Hamburg Regional Court, access to this website is blocked.

Zugriff gesperrt
Aufgrund eines [Urteils](https://openjur.de/u/2466945.html) des Landgerichts Hamburg ist der Zugriff auf diese Website gesperrt.

**Comment by dirkf** [comment]
Review #30839 as asked before posting.
