### ISSUE TITLE
nightly not working in macOS: env: python: No such file or directory

### ISSUE THREAD

**Issue by superbonaci** [ytdl-org/youtube-dl#32827]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

Download latest nightly:
https://github.com/ytdl-org/ytdl-nightly/releases/download/2024.06.21/youtube-dl

Try to run it on macOS 14.5 (Silicon):

```
$ ./youtube-dl --version
env: python: No such file or directory
```

Requires to set the python program:

```
$ python3 ./youtube-dl --version
2024.06.21
```

Stable version doesn't have this issue:

```
$ /opt/homebrew/bin/youtube-dl --version
2021.12.17
```

**Comment by dirkf** [comment]
Any Homebrew build is not under our control.

The bundled program for POSIX-ish platforms expects to be run by a program called `python` on the executable `PATH`.

If your system doesn't have one, either install using `-m pip` with a Python that is available, or ensure that there is a `python`, perhaps by creating a symlink to some Python executable on your system, like the `python3` that you seem to have. It's also possible to patch the program (which is just a shebang line followed by a zipped copy of the yt-dl code).

See #31107 and #30129 for rationale focussed on Linux, but equally applicable in principle to macOS.

**Comment by superbonaci** [comment]
duplicate
