### ISSUE TITLE
Do we already know meta data at "ERROR: Cannot decrypt nsig without player_url"?

### ISSUE THREAD

**Issue by mk-pmb** [ytdl-org/youtube-dl#32853]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Do we already have meta data at the stage of this error?
If my wrapper script knew the uploader and title, it could improve its decision whether to retry or postpone.
Unfortunately, the info json file has not been written at this stage.

```text
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-call-home', '--abort-on-error', '--no-overwrites', '--keep-video', '--restrict-filenames', '--output', '…', '--write-info-json', '--format=18', '--verbose', '--', 'XebaoWchKxI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 16f5bbc46
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-…-x86_64-with-glibc… - OpenSSL 1.1.1f  31 Mar 2020 - glibc …
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {…}
[youtube] XebaoWchKxI: Downloading webpage
WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests
[youtube] XebaoWchKxI: Downloading API JSON
ERROR: Cannot decrypt nsig without player_url; please report this issue on […]
```

Expected meta data for `XebaoWchKxI`:
Title: `Install youtube-dl in Windows with ffmpeg | fossfrog`
Uploader: `fossfrog`

Also in case someone is wondering, the nsig issue in this case is a proxy problem (IP address reputation), not a ytdl bug.

**Comment by dirkf** [comment]
The metadata is all in the page (or API JSON result) and may or may not have been set into some putative info_dict, but there's no way for the caller to know the values before formats are extracted.

**Comment by mk-pmb** [comment]
I see. I guess there's no good clean way then to write the metadata earlier.
