### ISSUE TITLE
Why was there no non-nightly release since 2021?

### ISSUE THREAD

**Issue by Mis012** [ytdl-org/youtube-dl#32855]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Many distributions have a policy to only update a package when there is a new release. I can't find any reasoning for why there was no release since 2021, and it seems like making a new release would solve the issue with outdated distro packages at least in some cases.

OpenSUSE Tumbleweed for example is stuck with the latest release (https://software.opensuse.org/package/youtube-dl), though alpine which typically doesn't package nightlies seems to have made an exception here (https://pkgs.alpinelinux.org/package/edge/community/x86_64/yt-dlp-core)

**Comment by dirkf** [comment]
#31585
