### ISSUE TITLE
Download site dont work

### ISSUE THREAD

**Issue by korizyx** [ytdl-org/youtube-dl#32850]
## Checklist

- [X] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

![image](https://github.com/user-attachments/assets/53dba346-ac88-472d-b5f4-67bcd501e73a)

## Description

Download site dont work

**Comment by ananaso** [comment]
At the risk of sounding flippant, did you read the [pinned issue regarding things to know before posting](https://github.com/ytdl-org/youtube-dl/issues/30839)? It appears to [address your issue already](https://github.com/ytdl-org/youtube-dl/issues/32495) and recommend you instead download the tool using the guidelines laid out in a [revised README](https://github.com/ytdl-org/youtube-dl/blob/9324d03ef9cfd8e26874cead3a2c1b5c78cdb42c/README.md) instead.

**Comment by dirkf** [comment]
What he said.
