### ISSUE TITLE
use pip version  fk this repo

### ISSUE THREAD

**Issue by jamieduk** [ytdl-org/youtube-dl#32860]
yt https://www.youtube.com/watch?v=ACHdK6qXTF0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]', '-o', '~/Downloads/%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=ACHdK6qXTF0']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Single file build
[debug] Python 3.12.4 (CPython aarch64 64bit) - Linux-6.6.31+rpt-rpi-2712-aarch64-with-glibc2.36 - OpenSSL 3.0.14 4 Jun 2024 - glibc 2.36
[debug] exe versions: ffmpeg 5.1.5-0, ffprobe 5.1.5-0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ACHdK6qXTF0: Downloading webpage
[debug] [youtube] Extracting signature function js_d60b0ef9_107
[youtube] ACHdK6qXTF0: Downloading player d60b0ef9
ERROR: Unable to extract nsig jsi, player_id, func_codefunction code (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1637, in _decrypt_nsig
    jsi, player_id, func_code = self._extract_n_function_code(video_id, player_url)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1680, in _extract_n_function_code
    func_name = self._extract_n_function_name(jscode)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1660, in _extract_n_function_name
    func_name, idx = self._search_regex(
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1101, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1637, in _decrypt_nsig
    jsi, player_id, func_code = self._extract_n_function_code(video_id, player_url)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1680, in _extract_n_function_code
    func_name = self._extract_n_function_name(jscode)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1660, in _extract_n_function_name
    func_name, idx = self._search_regex(
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1101, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 859, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 955, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2108, in _real_extract
    self._unthrottle_format_urls(video_id, player_url, dct)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1725, in _unthrottle_format_urls
    n_response = decrypt_nsig(n_param)(n_param, video_id, player_url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1614, in inner
    raise ret
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1606, in inner
    self._player_cache[cache_id] = func(*args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1639, in _decrypt_nsig
    raise ExtractorError('Unable to extract nsig jsi, player_id, func_codefunction code', cause=e)
youtube_dl.utils.ExtractorError: Unable to extract nsig jsi, player_id, func_codefunction code (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.

(base) jay@jnetaireloaded:~ $ youtube-dl -U
ERROR: can't find the current version. Please try again later.
(base) jay@jnetaireloaded:~ $ youtube-dl --verbose -U
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-U']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Single file build
[debug] Python 3.12.4 (CPython aarch64 64bit) - Linux-6.6.31+rpt-rpi-2712-aarch64-with-glibc2.36 - OpenSSL 3.0.14 4 Jun 2024 - glibc 2.36
[debug] exe versions: ffmpeg 5.1.5-0, ffprobe 5.1.5-0, rtmpdump 2.4
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/update.py", line 48, in update_self
    newversion = opener.open(VERSION_URL).read().decode('utf-8').strip()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/miniconda3/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/jay/miniconda3/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/home/jay/miniconda3/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/miniconda3/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/jay/miniconda3/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

ERROR: can't find the current version. Please try again later.
(base) jay@jnetaireloaded:~ $ sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   384  100   384    0     0   1864      0 --:--:-- --:--:-- --:--:--  1873
(base) jay@jnetaireloaded:~ $ sudo chmod a+rx /usr/local/bin/youtube-dl
(base) jay@jnetaireloaded:~ $ yt https://www.youtube.com/watch?v=ACHdK6qXTF0
/usr/local/bin/youtube-dl: line 1: syntax error near unexpected token `newline'
/usr/local/bin/youtube-dl: line 1: `<h1>Access denied</h1>'
(base) jay@jnetaireloaded:~ $ pip install yt-dlp
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting yt-dlp
  Downloading yt_dlp-2024.7.16-py3-none-any.whl.metadata (170 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 kB 2.9 MB/s eta 0:00:00
Requirement already satisfied: brotli in ./miniconda3/lib/python3.12/site-packages (from yt-dlp) (1.0.9)
Requirement already satisfied: certifi in ./miniconda3/lib/python3.12/site-packages (from yt-dlp) (2024.6.2)
Collecting mutagen (from yt-dlp)
  Downloading https://www.piwheels.org/simple/mutagen/mutagen-1.47.0-py3-none-any.whl (194 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.4/194.4 kB 3.2 MB/s eta 0:00:00
Collecting pycryptodomex (from yt-dlp)
  Downloading pycryptodomex-3.20.0-cp35-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (3.4 kB)
Requirement already satisfied: requests<3,>=2.32.2 in ./miniconda3/lib/python3.12/site-packages (from yt-dlp) (2.32.2)
Requirement already satisfied: urllib3<3,>=1.26.17 in ./miniconda3/lib/python3.12/site-packages (from yt-dlp) (2.2.2)
Collecting websockets>=12.0 (from yt-dlp)
  Downloading websockets-12.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (6.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in ./miniconda3/lib/python3.12/site-packages (from requests<3,>=2.32.2->yt-dlp) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in ./miniconda3/lib/python3.12/site-packages (from requests<3,>=2.32.2->yt-dlp) (3.7)
Downloading yt_dlp-2024.7.16-py3-none-any.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 19.6 MB/s eta 0:00:00
Downloading websockets-12.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.8/131.8 kB 4.2 MB/s eta 0:00:00
Downloading pycryptodomex-3.20.0-cp35-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 21.1 MB/s eta 0:00:00
Installing collected packages: websockets, pycryptodomex, mutagen, yt-dlp
Successfully installed mutagen-1.47.0 pycryptodomex-3.20.0 websockets-12.0 yt-dlp-2024.7.16
(base) jay@jnetaireloaded:~ $ V https://www.youtube.com/watch?v=ACHdK6qXTF0
Command 'V' not found. Attempting to install...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package V
Failed to install 'V'. Aborting.
(base) jay@jnetaireloaded:~ $ yt-dlp https://www.youtube.com/watch?v=ACHdK6qXTF0[youtube] Extracting URL: https://www.youtube.com/watch?v=ACHdK6qXTF0
[youtube] ACHdK6qXTF0: Downloading webpage
[youtube] ACHdK6qXTF0: Downloading ios player API JSON
[youtube] ACHdK6qXTF0: Downloading player d60b0ef9
[youtube] ACHdK6qXTF0: Downloading m3u8 information
[info] ACHdK6qXTF0: Downloading 1 format(s): 248+251
[download] Destination: [VERBAL WAR ZONE] PRESENTS STIMULUS PART 6 0F 6 [ACHdK6qXTF0].f248.webm
[download] 100% of  162.55MiB in 00:00:10 at 15.73MiB/s
[download] Destination: [VERBAL WAR ZONE] PRESENTS STIMULUS PART 6 0F 6 [ACHdK6qXTF0].f251.webm
[download] 100% of   26.80MiB in 00:00:02 at 9.41MiB/s
[Merger] Merging formats into "[VERBAL WAR ZONE] PRESENTS STIMULUS PART 6 0F 6 [ACHdK6qXTF0].webm"
Deleting original file [VERBAL WAR ZONE] PRESENTS STIMULUS PART 6 0F 6 [ACHdK6qXTF0].f248.webm (pass -k to keep)
Deleting original file [VERBAL WAR ZONE] PRESENTS STIMULUS PART 6 0F 6 [ACHdK6qXTF0].f251.webm (pass -k to keep)
(base) jay@jnetaireloaded:~ $ ls
''$'\377\177'
 bdaddr
 bin
 BlueDucky
 bluez
 Bookshelf
 Desktop
 Documents
 DOSGames
 Downloads
 etc
 include
 lib
 lib64
 miniconda3
 mpv-shot0001.jpg
 Music
 nltk_data
 pi-apps
 Pictures
 Public
 pyvenv.cfg
 share
 Templates
 tor-browser
'[VERBAL WAR ZONE] PRESENTS STIMULUS PART 6 0F 6 [ACHdK6qXTF0].webm'
 Videos
(base) jay@jnetaireloaded:~ $ rm *.webm
(base) jay@jnetaireloaded:~ $ ls
''$'\377\177'   Desktop     lib                pi-apps      tor-browser
 bdaddr         Documents   lib64              Pictures     Videos
 bin            DOSGames    miniconda3         Public
 BlueDucky      Downloads   mpv-shot0001.jpg   pyvenv.cfg
 bluez          etc         Music              share

**Comment by dirkf** [comment]
Who can tell what you're reporting? This seems to apply: https://github.com/ytdl-org/youtube-dl/issues/32858#issuecomment-2238815287
