### ISSUE TITLE
[YouTube] VP9 for live stream not available, missing high resolutions

### ISSUE THREAD

**Issue by Djfe** [ytdl-org/youtube-dl#32868]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2024.07.11**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PS I:\> .\youtube-dl.exe -v -F "https://www.youtube.com/watch?v=RI4GTHC1_jM"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.youtube.com/watch?v=RI4GTHC1_jM']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2024.07.11 [16f5bbc46] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 3.4.4 (CPython AMD64 32bit) - Windows-10-10.0.19041 - OpenSSL 1.0.2d 9 Jul 2015
[debug] exe versions: ffmpeg 6.1-full_build-www.gyan.dev, ffprobe 6.1-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] RI4GTHC1_jM: Downloading webpage
[youtube] RI4GTHC1_jM: Downloading m3u8 information
[youtube] RI4GTHC1_jM: Downloading MPD manifest
[info] Available formats for RI4GTHC1_jM:
format code  extension  resolution note
91           mp4        256x144     290k , avc1.42c00b, 15.0fps, mp4a.40.5
92           mp4        426x240     546k , avc1.4d4015, 30.0fps, mp4a.40.5
93           mp4        640x360    1209k , avc1.4d401e, 30.0fps, mp4a.40.2
94           mp4        854x480    1568k , avc1.4d401f, 30.0fps, mp4a.40.2
95           mp4        1280x720   2969k , avc1.4d401f, 30.0fps, mp4a.40.2
96           mp4        1920x1080  5420k , avc1.640028, 30.0fps, mp4a.40.2 (best)
```

## Description

I found a stream on YouTube for which YouTube-DL doesn't extract info on the available video streams in VP9. For this reason 2160p and 1440p aren't available. (H.264 ends at 1080p)
audio is mp4 (aac) for all vp9 streams
https://www.youtube.com/watch?v=RI4GTHC1_jM

![grafik](https://github.com/user-attachments/assets/6b86ae53-c477-46ba-acf6-f61f6c269063)
![grafik](https://github.com/user-attachments/assets/a4ae569b-e3b2-4567-868d-fb143f6d6e9e)
![grafik](https://github.com/user-attachments/assets/14ce45f0-87c9-48f6-b3e5-36a9486eb57e)

I realize the stream will be offline eventually but my report is still useful I feel.

**Comment by dirkf** [comment]
The linked video is showing as Private now (if not before).

The responses to https://github.com/yt-dlp/yt-dlp/issues/10513 identify several features and putative features of _yt-dlp_ that are needed to get these formats. _yt-dl_ is even less well featured in this respect. It may eventually be possible to back-port the necessary features, but for now livestream viewers must watch from far enough away not to notice the difference.

BTW what is the tool whose output you've posted in the images?

**Comment by Djfe** [comment]
I see.

> BTW what is the tool whose output you've posted in the images?

Those are just Screenshots of the YouTube video player.
Right-click the YouTube player and click on "stats for nerds" and this overlay will show up on-top of the video.
It's also available in the YouTube mobile app if you enable it in the settings.
