### ISSUE TITLE
ERROR: Unable to extract nsig function code

### ISSUE THREAD

**Issue by lwhdev** [ytdl-org/youtube-dl#32878]
### app version
[E:\]$ youtube-dl --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Encodings: locale cp936, fs utf-8, out gbk, pref cp936
[debug] youtube-dl version 2021.12.17
[debug] Single file build
[debug] Python 3.12.4 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 - OpenSSL 3.0.13 30 Jan 2024
[debug] exe versions: ffmpeg N-115428-g62d7106c36-20240528, ffprobe N-115428-g62d7106c36-20240528
[debug] Proxy map: {'http': 'http://127.0.0.1:10809', 'https': 'http://127.0.0.1:10809'}
Usage: youtube-dl [OPTIONS] URL [URL...]

### bug loog
youtube-dl "ytsearch:proxy=http://127.0.0.1:10809" https://www.youtube.com/watch?v=1J8a1LmK0M8
[download] Downloading playlist: proxy=http://127.0.0.1:10809
[youtube:search] query "proxy=http://127.0.0.1:10809": Downloading page 1
[youtube:search] playlist proxy=http://127.0.0.1:10809: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] UoS3_cjfyn0: Downloading webpage
[youtube] UoS3_cjfyn0: Downloading player 3400486c
ERROR: Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract Initial JS player n function name; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.

**Comment by a37h** [comment]
Same

**Comment by HorlarhMheporzy** [comment]
Same thing. Help

**Comment by dirkf** [comment]
Please review and follow #30839 to find the relevant existing issue, which has been fixed in the latest nightly build. **Use the template**.
