### ISSUE TITLE
YOUTUBE-DL site in curl download closed by court ruling

### ISSUE THREAD

**Issue by tmjoris** [ytdl-org/youtube-dl#32872]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
The site described in the curl and wget download option has been closed by a court ruling and access is being denied.
![image](https://github.com/user-attachments/assets/6ef5762c-5235-41a9-8e0c-5009a68d2769)
![image](https://github.com/user-attachments/assets/0879eee9-9fd3-4136-b223-5c39e1555c39)

https://yt-dl.org/downloads/latest/youtube-dl

**Comment by dirkf** [comment]
As if we didn't know!

Please review #30839 as asked.
