### ISSUE TITLE
Extractor regex error getting and not downloaded video

### ISSUE THREAD

**Issue by Roxy45l** [ytdl-org/youtube-dl#32889]
Hello i get this error. ERROR: Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract Initial JS player n function name; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
youtube  | 1 - 2024-08-01 09:50:24,872 - WARNING - Video not downloaded and status 0
youtube  | 1 - 2024-08-01 09:50:24,886 - INFO - Download video status updated. Id: 401092, Status: 0
youtube  | 1 - 2024-08-01 09:50:24,887 - INFO - Video init completed for Video URL: https://www.youtube.com/watch?v=lXNwBV79BLI
youtube  | [youtube] lXNwBV79BLI: Downloading webpage
youtube  | WARNING: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:992)>
youtube  | [youtube] gKvfmzhIYc0: Downloading API JSON
youtube  | WARNING: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:992)>
youtube  | [youtube] 7I3l8w6m94U: Downloading API JSON

Can you fix pls

**Comment by dirkf** [comment]
Hello, please follow #30839 as asked when reporting your problem (which looks like a known issue).

**Comment by Roxy45l** [comment]
@dirkf Hello bro, I downloaded the library up to date and I use it. But there is still the same error. I looked at the fixed code and saw that it was in the library. Despite this, my code is indexed to the video

**Comment by dirkf** [comment]
Fixed in master code and https://github.com/ytdl-org/ytdl-nightly/releases/tag/2024.08.02
