### ISSUE TITLE
Unable to extract nsig function code

### ISSUE THREAD

**Issue by nobody93** [ytdl-org/youtube-dl#32880]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
ERROR: Unable to extract nsig function code (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://github.com/ytdl-org/youtube-dl/issues

It was fixed a couple weeks ago, then the same error is back again :-(
$ youtube-dl --version
2024.07.11

**Comment by dirkf** [comment]
[Why do you suppose there is a checklist in the issue template](https://github.com/ytdl-org/youtube-dl/issues/32878#issuecomment-2249274447)?
