### ISSUE TITLE
formats priority of --merge-output-format

### ISSUE THREAD

**Issue by MagicalDrizzle** [ytdl-org/youtube-dl#32886]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

What is the priority of format chosen when merging video+audio? For example `--merge-output-format mp4/webm/mkv`
Is it the same as the priority list of [`format-sort`](https://github.com/yt-dlp/yt-dlp/blob/master/README.md#sorting-formats), and is it influenced by `--prefer-free-formats`?

**Comment by dirkf** [comment]
Your link implies this

#30839 ... if you were actually running _yt-dlp_ ...

and that's how to get a definitive answer for _yt-dlp_.

When you say "priority of format", obviously that means "container format".

In yt-dl, you get the formats you ask for and the container you ask for, with minimal hand-holding.

I expect that in _yt-dlp_, the first container type compatible with the selected formats is used: the code calls `get_compatible_ext()` with parameters including the codecs and `ext`s of the formats and the preferred container types, which are the `--merge-output-formats` or just `('webm', 'mkv')` if `--prefer-free-formats`. This could be a fairly easy back-port if people wanted similar behaviour here.
