### ISSUE TITLE
Bugs when list all available formats

### ISSUE THREAD

**Issue by bert093** [ytdl-org/youtube-dl#32890]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2024.07.25 [e1b3fa242] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 3.4.4 (CPython AMD64 32bit) - Windows-10-10.0.22621 - OpenSSL 1.0.2d 9 Jul 2015
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

## Description

WRITE DESCRIPTION HERE
There is a bug when I want to display all formats from youtube url. By the way I am using the latest youtube-dl nightly build. <br>
![Screenshot 2024-08-01 215333](https://github.com/user-attachments/assets/561f6f45-dda9-48d0-97fa-45bcaa6ddac9)

**Comment by aiur-adept** [comment]
This issue is also being reported at #32885. You should follow there for any updates. There was a patch posted in that thread if you're comfortable applying a patch yourself. Otherwise, I think the fix should be in a nightly release soon.
