### ISSUE TITLE
yt-dlp does not show the webm-dash formats on the last version (2024.08.01)

### ISSUE THREAD

**Issue by YellowSM** [ytdl-org/youtube-dl#32892]
Last version (2024.08.01) `yt-dlp -F` doesn't show webm-dash formats (278,242,243, etc). Although formats exist
And you can't download this formats

Previous version works fine (2024.07.25)

**Comment by bashonly** [comment]
wrong issue tracker
https://github.com/yt-dlp/yt-dlp/issues
