### ISSUE TITLE
I thought youtube-dl can also download video from https://www.bilibili.com, what I could be missing?

### ISSUE THREAD

**Issue by nobody93** [ytdl-org/youtube-dl#32900]
## Checklist

- [ ] I'm reporting a site feature request
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

Platform: Ubuntu
Version: youtube-dl 2024.08.07

I thought youtube-dl can also download video from https://www.bilibili.com/video/BV1Fi4y1a7oB, but I got many errors, what I could be missing?

$ youtube-dl --verbose https://www.bilibili.com/video/BV1Fi4y1a7oB
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.bilibili.com/video/BV1Fi4y1a7oB']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2024.08.07 [c5098961b] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 2.7.15rc1 (CPython x86_64 64bit) - Linux-5.4.0-42-generic-x86_64-with-Ubuntu-18.04-bionic - OpenSSL 1.1.1  11 Sep 2018 - glibc 2.7
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[BiliBili] 1Fi4y1a7oB: Downloading webpage
[BiliBili] 1Fi4y1a7oB: Downloading video info page
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[BiliBili] 1Fi4y1a7oB: Downloading video info page
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 679, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2500, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dirkf** [comment]
https://github.com/ytdl-org/youtube-dl/issues/32722#issuecomment-1950045012
