### ISSUE TITLE
Amend readme.md

### ISSUE THREAD

**Issue by Powsu** [ytdl-org/youtube-dl#32904]
## Checklist

- [x] I'm reporting a site feature request
- [?] I've verified that I'm running youtube-dl version **2021.12.17** `(Not relevant)`
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

This is more of a suggestion/proposal, rather than a feature request, however this is the closest option I have. As your likely aware, the main site was taken down due to legal reasons.

The current "stable" releases are broken.

My suggestion is to amend the readme to divert to nightly instructions for installation by default and for the github pages site to reflect this.

Alternatively, and preferably, a new stable release should be made that makes the program functionally usable and capable of downloading from youtube. The last stable release was published 2021.

I'm likely missing details, and I'm aware that this issue might get closed because of those missing details. But I did try **REALLY HARD** to find an existing suggestion/feature request/issue, maybe I didn't try hard enough. Please provide detailed clarification if I'm wrong, so I can understand the circumstances.

**Comment by dirkf** [comment]
#30839 has the link (see `madness`).

Also #31585, #32876.

Also, https://github.com/ytdl-org/youtube-dl/releases/tag/2021.12.17.
