### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by tambow44** [ytdl-org/youtube-dl#32907]
## Checklist

- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [] I've searched the bugtracker for similar bug reports including closed ones
-    This isn't possible, the bugtracker link tells me the following (I searched github issues as well but nothing came up)
  - "[ruling](https://openjur.de/u/2466945.html) of the Hamburg Regional Court, access to this website is blocked." 
  - I am in NZ, if that matters?
- [x] I've read bugs section in FAQ

## Verbose log

```
> youtube-dl -f bestvideo+bestaudio --merge-output-format mp4 -o "jp.mp4" https://www.youtube.com/watch?v=L397TWLwrUU --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo+bestaudio', '--merge-output-format', 'mp4', '-o', 'jp.mp4', 'https://www.youtube.com/watch?v=L397TWLwrUU', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] L397TWLwrUU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

I'm not entirely familiar with this, but the error states "Unable to extract uploader id", and then fails as "RegexNotFoundError".

I have tested this on Linux Debian, and OpenBSD (with both the their respective package repos and from your instructions re installing via curl (the latest version).

**Comment by nicolaasjan** [comment]
You should use the nightly repo.
https://github.com/ytdl-org/ytdl-nightly/releases

**Comment by dirkf** [comment]
But be aware of #32905.

Also, review and follow #30839 as asked.
