### ISSUE TITLE
Suntax error in Linux

### ISSUE THREAD

**Issue by finid** [ytdl-org/youtube-dl#32903]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v --version
/usr/local/bin/youtube-dl: line 1: syntax error near unexpected token `newline'
/usr/local/bin/youtube-dl: line 1: `<h1>Access denied</h1>'
```

## Description

1. Just installed YouTube-dl on Linux Mint using the manual (curl) method.
2. Got the error above after running `youtube-dl -h` or `youtube-dl --version`.
Mint is running Python 3.8.10

**Comment by FuzzyExpress** [comment]
```shell
fexp@FuzzyExpressKRaider:~/Downloads$ cat /usr/local/bin/youtube-dl
<h1>Access denied</h1>

<p>
  Due to a <a href="https://openjur.de/u/2466945.html" target="_blank">ruling</a> of the Hamburg Regional Court, access to this website is blocked.
</p>

<hr />

<h1>Zugriff gesperrt</h1>

<p>
  Aufgrund eines <a href="https://openjur.de/u/2466945.html" target="_blank">Urteils</a> des Landgerichts Hamburg ist der Zugriff auf diese Website gesperrt.
</p>
```
![image](https://github.com/user-attachments/assets/4c14eae2-d475-42c3-9ce1-805bf41cf423)

Seams like the website that the curl command was pointing to was taken down :shrug:
Instead we installed an almost blank HTML file.

**Comment by finid** [comment]
I know that website is not longer accessible, just did not know binary pointed to it.

**Comment by finid** [comment]
Because of that the application does not work at all.

**Comment by dirkf** [comment]
Use the template.
Follow #30839.
