### ISSUE TITLE
[youtube] eeloLUz_uSs: Downloading webpage ERROR: Sign in to confirm you’re not a bot This helps protect our community. Learn more

### ISSUE THREAD

**Issue by lucasjinreal** [ytdl-org/youtube-dl#32915]
[youtube] eeloLUz_uSs: Downloading webpage
ERROR: Sign in to confirm you’re not a bot
This helps protect our community. Learn more

**Comment by lucasjinreal** [comment]
Thank you for your reply. It appears that the error messages do not explicitly indicate whether the IP was banned or not.

**Comment by dirkf** [comment]
We don't know what causes YT to send that response, but can guess. Review the linked _yt-dlp_ thread for suggestions on avoiding it.
