### ISSUE TITLE
Revanced 4.12.0 

### ISSUE THREAD

**Issue by Aleksandrt6** [ytdl-org/youtube-dl#32926]
![Screenshot_20240907_205823_YouTube](https://github.com/user-attachments/assets/4e5956f9-a0bf-42c6-8c34-eb0977de3398)

## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
1. Complete the template after performing the requested actions!
2. SponsorBlock is not a feature of _youtube-dl_.
3. Review #30839 as asked: "... if you were actually running _yt-dlp_, ..."
