### ISSUE TITLE
Metadata not found 

### ISSUE THREAD

**Issue by Justavinash09** [ytdl-org/youtube-dl#32921]
App version: 1.13.0 (11302)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.08.21.232751

URL: https://www.instagram.com/reel/C7_a5pIJJIe/?igsh=MWY1NGZvbTBiZm5jaA==
WARNING: [Instagram] C7_a5pIJJIe: General metadata extraction failed (some metadata might be missing).
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] C7_a5pIJJIe: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials

**Comment by dirkf** [comment]
#30839: "... if you were actually using _yt-dlp~_ ..."

The Instagram extractor here [needs to be updated](https://github.com/ytdl-org/youtube-dl/issues/31322) even more but attempted updates seemed to be prone to site blockage. Or was that TikTok, or Twitter, or FB? Probably the whole lot.
