### ISSUE TITLE
'entries' is empty

### ISSUE THREAD

**Issue by greenmac** [ytdl-org/youtube-dl#32927]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

result={'id': 'UCacdJgGjbwRwlawZgSyVH5w', 'channel': '이아돌[LeeADol] -雅英', 'channel_id': 'UCacdJgGjbwRwlawZgSyVH5w', 'title': '이아돌[LeeADol] -雅英 - Shorts', 'availability': None, 'channel_follower_count': 439000, 'description': '이아영(Lee A-young) 치어리더/모델/숏폼크리에이터\nbusiness : business@onepickent.co.kr\n李雅英 ', 'tags': ['이아영', '이아돌', '치어리더', '拉拉隊', '李雅英'], 'thumbnails': [{'url': 'https://yt3.googleusercontent.com/64BPUb9z2iUZJqmFdC8lPhervkVPuM-aKIHxnkvJwa5lsWnBZEXl2lqmRSNXz_oQ3YI169cw=w1060-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj', 'height': 175, 'width': 1060, 'preference': -10, 'id': '0', 'resolution': '1060x175'}, {'url': 'https://yt3.googleusercontent.com/64BPUb9z2iUZJqmFdC8lPhervkVPuM-aKIHxnkvJwa5lsWnBZEXl2lqmRSNXz_oQ3YI169cw=w1138-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj', 'height': 188, 'width': 1138, 'preference': -10, 'id': '1', 'resolution': '1138x188'}, {'url': 'https://yt3.googleusercontent.com/64BPUb9z2iUZJqmFdC8lPhervkVPuM-aKIHxnkvJwa5lsWnBZEXl2lqmRSNXz_oQ3YI169cw=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj', 'height': 283, 'width': 1707, 'preference': -10, 'id': '2', 'resolution': '1707x283'}, {'url': 'https://yt3.googleusercontent.com/64BPUb9z2iUZJqmFdC8lPhervkVPuM-aKIHxnkvJwa5lsWnBZEXl2lqmRSNXz_oQ3YI169cw=w2120-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj', 'height': 351, 'width': 2120, 'preference': -10, 'id': '3', 'resolution': '2120x351'}, {'url': 'https://yt3.googleusercontent.com/64BPUb9z2iUZJqmFdC8lPhervkVPuM-aKIHxnkvJwa5lsWnBZEXl2lqmRSNXz_oQ3YI169cw=w2276-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj', 'height': 377, 'width': 2276, 'preference': -10, 'id': '4', 'resolution': '2276x377'}, {'url': 'https://yt3.googleusercontent.com/64BPUb9z2iUZJqmFdC8lPhervkVPuM-aKIHxnkvJwa5lsWnBZEXl2lqmRSNXz_oQ3YI169cw=w2560-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj', 'height': 424, 'width': 2560, 'preference': -10, 'id': '5', 'resolution': '2560x424'}, {'url': 'https://yt3.googleusercontent.com/64BPUb9z2iUZJqmFdC8lPhervkVPuM-aKIHxnkvJwa5lsWnBZEXl2lqmRSNXz_oQ3YI169cw=s0', 'id': 'banner_uncropped', 'preference': -5}, {'url': 'https://yt3.googleusercontent.com/F0yaK2ASNAdohlsJQ8wf6k_iwMHvri_lHQbhKoAvuimYfkaT4-fDwGo7Qu3-cDAkC6KqdUGgtg=s900-c-k-c0x00ffffff-no-rj', 'height': 900, 'width': 900, 'id': '7', 'resolution': '900x900'}, {'url': 'https://yt3.googleusercontent.com/F0yaK2ASNAdohlsJQ8wf6k_iwMHvri_lHQbhKoAvuimYfkaT4-fDwGo7Qu3-cDAkC6KqdUGgtg=s0', 'id': 'avatar_uncropped', 'preference': 1}], 'uploader_id': '@yyyoungggggg', 'uploader_url': 'https://www.youtube.com/@yyyoungggggg', 'modified_date': None, 'view_count': None, 'playlist_count': 0, 'uploader': '이아돌[LeeADol] -雅英', 'channel_url': 'https://www.youtube.com/channel/UCacdJgGjbwRwlawZgSyVH5w', '_type': 'playlist', 'entries': [], 'extractor_key': 'YoutubeTab', 'extractor': 'youtube:tab', 'webpage_url': 'https://www.youtube.com/@yyyoungggggg/shorts', 'original_url': 'https://www.youtube.com/@yyyoungggggg/shorts', 'webpage_url_basename': 'shorts', 'webpage_url_domain': 'youtube.com', 'release_year': None, 'epoch': 1725941326}

## Description

Unable to read the video URL of any video, 'entries' is empty,

**Comment by dirkf** [comment]
@greenmac ?
