### ISSUE TITLE
Tiktok mass download error

### ISSUE THREAD

**Issue by RazyRo** [ytdl-org/youtube-dl#32930]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

ERROR: WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[TikTokUser] sabrinacarpenter: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 502: Bad Gateway (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

CONTEXT: create txt file list of Tiktok user URLs (titkok is ban in our country)

**Comment by dirkf** [comment]
>`ERROR: WARNING: The program functionality for this site has been marked as broken, and will probably not work.`

And unsurprisingly it doesn't. Probably resolving #32761 would solve this.
