### ISSUE TITLE
current veeps support? I've tried searching old issues

### ISSUE THREAD

**Issue by tcafranz** [ytdl-org/youtube-dl#32941]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Just looking for veeps dl support as all issues / discussions I've found are no longer working. The file I'm looking to acquire is a replay of a paid stream that I have purchased if that helps?

**Comment by dirkf** [comment]
You have probably learned as much as anyone knows, unless you ignored [this comment](https://github.com/ytdl-org/youtube-dl/issues/25728#issuecomment-2147583525), which confirms your experience [described downstream](https://github.com/yt-dlp/yt-dlp/issues/11171).
