### ISSUE TITLE
how to pass a variable or argument to an extractor from command line

### ISSUE THREAD

**Issue by ifixthat-gmx** [ytdl-org/youtube-dl#32942]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
above links are not working:
> Zugriff gesperrt
> Aufgrund eines [Urteils](https://openjur.de/u/2466945.html) des Landgerichts Hamburg ist der Zugriff auf diese Website gesperrt.
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

So for debugging purpose I'd like to pass some dynamic variables to the extractor (I have made some modifications to some of yours but also added new ones in my private repository).

I want to do something like this:
` youtube-dl --pass2extractor tmpstore=html,json --pass2extractor pathprefix=$HOME/.tmp/%SOME_UNIQ_AND_DYNAMIC% -f .. -o .. "URL"`
- tmpstore=html,json --> tells the extractor to save the webpages html (get variables for the json-link here), and the downloaded json (contains the wanted video-playlist-data)
- pathprefix tells the location for the html and json (I want store them in a different location than the video)

--pass2extractor %PASS% -> the content of %PASS% should get passed into extractor (it should somehow be available/accessable)

Is it possible to do this and is something like that already implemented?

**Comment by dirkf** [comment]
There's already the `--write-pages` option for saving fetched web pages.

_yt-dlp_ has implemented options similar to what you describe, so it may be useful to check those implementations:
* [`--extractor-args ...`](https://github.com/yt-dlp/yt-dlp#user-content-extractor-arguments) for passing extractor-specific parameters: this will soon have to be implemented here, to control client selection in the YT extractor;
* `--paths TYPE:LOCATION` to specify a directory to be used for the `TYPE` files.

**Comment by ifixthat-gmx** [comment]
> There's already the `--write-pages` option for saving fetched web pages.

I know this - but it doesnt work for me - i need custom path and filename

> _yt-dlp_ has implemented options similar to what you describe, so it may be useful to check those implementations:
>     * [`--extractor-args ...`](https://github.com/yt-dlp/yt-dlp#user-content-extractor-arguments) for passing extractor-specific parameters: this will soon have to be implemented here, to control client selection in the YT extractor

Oh cool - will look at that later

Thanks for the reference.

@dirkf 
out of curiosity - have you checked your [PR 30774](https://github.com/ytdl-org/youtube-dl/pull/30774) recently ?
