### ISSUE TITLE
sorry to lose you

### ISSUE THREAD

**Issue by hnaylor** [ytdl-org/youtube-dl#32952]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
I see that you had a judgement against you for your wonderfully useful program. I am very sad about that. I attend classes at UC Berkeley for which I pay a large amount, and feel that I have a right to the class recordings after they expire. I hope that you may be able to resolve the legal issues one day. Please let me know when that happens, and if you need financial assistance.
Hilary Naylor
hnaylor @ a2zed.us

**Comment by dirkf** [comment]
Thanks, it's only the vanity domain and its hoster that's affected. You can still get what you need here: review #30839.
