### ISSUE TITLE
Redirect to yt-dlp

### ISSUE THREAD

**Issue by ramiropistoia** [ytdl-org/youtube-dl#32958]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Please redirect users to yt-dlp or another tool that is updated regularly, if the latest version is from 2021 and has lots of vulnerabilities

**Comment by alex-free** [comment]
If you look, the source tree is actively maintained, updated, and usable. They no longer publish releases. You should close this.

**Comment by dirkf** [comment]
Essentially, duplicate of #31585, apart from OP **not having read #30839 as asked**.
