### ISSUE TITLE
Bot.

### ISSUE THREAD

**Issue by Athulsuminamukundan** [ytdl-org/youtube-dl#32953]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

> # - [ ] - > WRITE DESCRIPTION HE[
- [x] Bot

**Comment by Athulsuminamukundan** [comment]
Good

**Comment by dirkf** [comment]
So you are.
