### ISSUE TITLE
Can't download from Weverse

### ISSUE THREAD

**Issue by DoctorDovely** [ytdl-org/youtube-dl#32955]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2024.10.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
ytdl>yt-dlp.exe https://weverse.io/lesserafim/media/2-149879004 --hls-prefer-ffmpeg -f bestaudio --merge-output-format mkv --all-subs
[WeverseMedia] Extracting URL: https://weverse.io/lesserafim/media/2-149879004
[WeverseMedia] 2-149879004: Downloading API JSON
[Weverse] Extracting URL: https://weverse.io/lesserafim/live/2-149879004
[Weverse] 2-149879004: Downloading API JSON
[Weverse] 2-149879004: Downloading VOD API key
ERROR: [Weverse] 2-149879004: 2-149879004: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q=
```

## Description

Tried to download a weverse Live video from https://weverse.io/ and keep getting this error. I used to download a video from here every week until i ran into this error. was directed here by the ytdl-nis community. Tried to download with pc and still ran into same issue.

**Comment by dirkf** [comment]
#30839: "... if you were actually running _yt-dlp_ ..."

Also, you didn't read the error message which provided the URL for your error report.

We don't have an extractor for this site, but I can see that the [same issue was already raised at _yt-dlp_](https://github.com/yt-dlp/yt-dlp/issues/11213) and fixed in their nightly release.
