### ISSUE TITLE
Unable to parse videos from www.bilibili.com

### ISSUE THREAD

**Issue by ChengduDreamer** [ytdl-org/youtube-dl#32963]
youtube-dl.exe  "https://www.bilibili.com/video/BV1gCeWehEyT/?spm_id_from=333.1073.channel.secondary_floor_video.click&vd_source=93f53d0f9792c7652f7bb275d0eba4b1"
[BiliBili] 1gCeWehEyT: Downloading webpage
[BiliBili] 1gCeWehEyT: Downloading video info page
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[BiliBili] 1gCeWehEyT: Downloading video info page
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
By **actually reading and following #30839** and using the issue template, you would have found #32782, which reports exactly this issue, and its linked issue #32722, which reported the slightly different original diagnostic when the site changed.
