### ISSUE TITLE
BFM business: videoid error

### ISSUE THREAD

**Issue by theedge456** [ytdl-org/youtube-dl#32965]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2024.10.22**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

youtube-dl "https://www.bfmtv.com/economie/replay-emissions/les-experts/les-experts-travailler-plus-pour-gagner-plus-30-10_VN-202410300360.html" --list-formats
[bfmtv] Extracting URL: https://www.bfmtv.com/economie/replay-emissions/les-experts/les-experts-travailler-plus-pour-gagn...VN-202410300360.html
[bfmtv] 202410300360: Downloading webpage
ERROR: 202410300360: An extractor error has occurred. (caused by KeyError('videoid')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
fabien@ideapad:/tmp$ youtube-dl "https://www.bfmtv.com/economie/replay-emissions/les-experts/les-experts-travailler-plus-pour-gagner-plus-30-10_VN-202410300360.html" --list-formats
[bfmtv] Extracting URL: https://www.bfmtv.com/economie/replay-emissions/les-experts/les-experts-travailler-plus-pour-gagn...VN-202410300360.html
[bfmtv] 202410300360: Downloading webpage
ERROR: 202410300360: An extractor error has occurred. (caused by KeyError('videoid')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
fabien@ideapad:/tmp$ youtube-dl "https://www.bfmtv.com/economie/replay-emissions/les-experts/les-experts-plus-de-0-4-une-croissance-en-trompe-l-il-31-10_VN-202410310327.html" --list-formats
[bfmtv] Extracting URL: https://www.bfmtv.com/economie/replay-emissions/les-experts/les-experts-plus-de-0-4-une-croissanc...VN-202410310327.html
[bfmtv] 202410310327: Downloading webpage
ERROR: 202410310327: An extractor error has occurred. (caused by KeyError('videoid')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
fabien@ideapad:/tmp$ youtube-dl "https://www.bfmtv.com/economie/replay-emissions/les-experts/les-experts-plus-de-0-4-une-croissance-en-trompe-l-il-31-10_VN-202410310327.html" -v
[debug] Command-line config: ['https://www.bfmtv.com/economie/replay-emissions/les-experts/les-experts-plus-de-0-4-une-croissance-en-trompe-l-il-31-10_VN-202410310327.html', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.11.5-x86_64-with-glibc2.36 (OpenSSL 3.0.14 4 Jun 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.1, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[bfmtv] Extracting URL: https://www.bfmtv.com/economie/replay-emissions/les-experts/les-experts-plus-de-0-4-une-croissance-en-trompe-l-il-31-10_VN-202410310327.html
[bfmtv] 202410310327: Downloading webpage
ERROR: 202410310327: An extractor error has occurred. (caused by KeyError('videoid')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/bin/youtube-dl/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/youtube-dl/yt_dlp/extractor/bfmtv.py", line 45, in _real_extract
    return self._brightcove_url_result(video_block['videoid'], video_block)
                                       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'videoid'
```
## Description

<!--
Provide an explanation of your issue in an arbitrary form. Please make sure the description is worded well enough to be understood, see https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->
The program does not provide the available formats anymore.

**Comment by dirkf** [comment]
#30839: "... if you were actually using _yt-dlp_ ..."

However, you should try `--force-generic`, which works with the current nightly build here, and seems also to work with _yt-dlp_.

Basically, the page structure now contains generic Brightcove video and not the video block that the extractor was, rather poorly, trying to find.

**Comment by theedge456** [comment]
On 01/11/2024 21:10, dirkf wrote:
> 
> #30839: &quot;... if you were actually using _yt-dlp_ ...&quot;
youtube-dl is just a symlink to yt-dlp.
Sorry for that.

Thanks for the tip,
Fabien
