### ISSUE TITLE
[Suggestion] Keep proxy connection open through the task

### ISSUE THREAD

**Issue by AnrDaemon** [ytdl-org/youtube-dl#32966]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Please keep proxy connection open through the task to avoid bans due to connection rate limiting.
It is not once I've seen that a program aborts due to remote host resetting connection right before the actual download starts.
I have to wait for ban to reset and it severely limiting the number of downloads I could attempt per minute.

**Comment by dirkf** [comment]
I don't really understand how a connection could be maintained if the remote host resets it?

If you are expecting to download many items per minute and/or using a proxy with YouTube, banning is a more likely result.

**Comment by AnrDaemon** [comment]
The rate limiting is on the proxy side.
I've had to write the log watcher and force unblock the IP the connections are coming from to make the setup reliable.

Now, all that remains is to find out, why it doesn't work with HTTPS proxy. Socks works fine.

**Comment by dirkf** [comment]
#32549
