### ISSUE TITLE
connection reset by peer

### ISSUE THREAD

**Issue by dasmith94** [ytdl-org/youtube-dl#32961]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2024.09.27**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

~ $ yt-dlp youtube-dl --version
2024.09.27
~ $ yt-dlp youtube-dl -v https://youtu.be/VjYmR9_tgbM
[generic] Extracting URL: youtube-dl
[youtube] Extracting URL: https://youtu.be/VjYmR9_tgbM
[youtube] VjYmR9_tgbM: Downloading webpage
[youtube] VjYmR9_tgbM: Downloading ios player API JSON
[youtube] VjYmR9_tgbM: Downloading iframe API JS
[youtube] VjYmR9_tgbM: Downloading web creator player API JSON
[debug] Command-line config: ['--config-locations', '/data/user/0/com.deniscerri.ytdl/cache/config-TERMINAL[1729885407684].txt', '-P', '/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/TERMINAL/2', '--no-cache-dir', '--ffmpeg-location', '/data/app/~~cdoaSXcJYegt0sdMsfB8ng==/com.deniscerri.ytdl--cRyNrPWKDqw9vGeBSXssQ==/lib/arm64/libffmpeg.so']
[debug] | Config "/data/user/0/com.deniscerri.ytdl/cache/config-TERMINAL[1729885407684].txt": ['youtube-dl', '-v', 'https://youtu.be/VjYmR9_tgbM']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (zip)
[debug] Python 3.11.10 (CPython aarch64 64bit) - Linux-5.10.198-android13-4-00050-g12f3388846c3-ab11920634-aarch64-with-libc (OpenSSL 3.3.2 3 Sep 2024, libc)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.20.0, mutagen-1.47.0, sqlite3-3.46.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1838 extractors
ERROR: [generic] 'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:youtube-dl" ) to search YouTube
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/generic.py", line 2358, in _real_extract
    raise ExtractorError(
WARNING: [youtube] Unable to download webpage: [Errno 104] Connection reset by peer
WARNING: [youtube] [Errno 104] Connection reset by peer. Retrying (1/3)...
WARNING: [youtube] [Errno 104] Connection reset by peer. Retrying (2/3)...
WARNING: [youtube] [Errno 104] Connection reset by peer. Retrying (3/3)...
WARNING: [youtube] Unable to download API page: [Errno 104] Connection reset by peer (caused by TransportError('[Errno 104] Connection reset by peer'))
ERROR: [youtube] VjYmR9_tgbM: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/youtube.py", line 4365, in _real_extract
    webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/youtube.py", line 4329, in _download_player_responses
    player_responses, player_url = self._extract_player_responses(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/youtube.py", line 3988, in _extract_player_responses
    raise ExtractorError('Failed to extract any player response')

## Description

WRITE DESCRIPTION HERE

Simply won't download. There were no oddities or unusual things when downloading the APK. This was the first video I attempted to download. All the rest had the same issue. Google Pixel 8a. The only thing worth noting, is that due to my location, I have very poor Internet connect - hence why I'm attempting to download videos. We are talking 0.25 MB/s.

**Comment by dirkf** [comment]
#30839: "...if you were actually using _yt-dlp_ ..."

But maybe I can save you the trip. Your command needs to look like this:
```console
$ yt-dlp -v 'https://youtu.be/VjYmR9_tgbM'
[debug] Command-line config: ['-v', 'https://youtu.be/VjYmR9_tgbM']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
[debug] Python 3.9.19 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-glibc2.23 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.23)
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2019.11.28, requests-2.25.1, secretstorage-3.2.0, sqlite3-3.37.2, urllib3-1.25.11
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1830 extractors
[youtube] Extracting URL: https://youtu.be/VjYmR9_tgbM
[youtube] VjYmR9_tgbM: Downloading webpage
[youtube] VjYmR9_tgbM: Downloading ios player API JSON
[youtube] VjYmR9_tgbM: Downloading web creator player API JSON
[youtube] VjYmR9_tgbM: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] VjYmR9_tgbM: Downloading 1 format(s): 247+251
[debug] Invoking http downloader on "https://rr4---sn-cu-aigsl.googlevideo.com/videoplayback?expire=1729920332&ei=7CgcZ6vYM6HDmLAPu9DayQ4&ip=46.208.6.93&id=o-AO3gOmE4Zv86LyIpI49eYSKa93t8JXU3KDXVzv8iQJda&itag=247&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1729898732%2C&mh=3a&mm=31%2C29&mn=sn-cu-aigsl%2Csn-cu-c9id&ms=au%2Crdu&mv=m&mvi=4&pl=25&rms=au%2Cau&initcwndbps=1987500&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=59815567&dur=1122.566&lmt=1729862774267151&mt=1729898466&fvip=5&keepalive=yes&fexp=51312688%2C51326931&c=IOS&txp=5437434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgOkfwYH4rovtbfnlBW_t18CKjyWIjEguF19KjqVmCzaYCIQDLEyV6Uuz24006H9DnzhTqu3KSsNfLI_LPR0AEqjeZyg%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=ACJ0pHgwRAIgZhCVMyoDGzhmzeMNQ2zDNRsj62LfnOC6ZqiEoa0bQb0CIEB9qkPOkLOWW-7-sQe71_HKATckDvGQAM7qOZIPQHTH"
[download] Destination: Dan Da Dan   01 [VjYmR9_tgbM].f247.webm
[download]  16.6% of   57.04MiB at    1.23MiB/s ETA 00:38 ...
```
[I cancelled the d/l there]
If you were using this version of the program, you'd have `youtube-dl` instead of `yt-dlp`.
