### ISSUE TITLE
Support Balkan TV (tvbalkanuzivo.com)

### ISSUE THREAD

**Issue by dbojan** [ytdl-org/youtube-dl#32984]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs
https://www.tvbalkanuzivo.com/bht-1/

## Description

Hi. Any chance for adding support for the site mentioned?
It works in the browser player (firefox).

Thanks.

**Comment by dirkf** [comment]
Thanks, but you'll need to be more explicit about what to expect on the example page and across the site. Does the site only serve a selection of live TV channels (from, I assume Balkan countries), or is there on-demand content too? 

From general knowledge, I guessed that I would be watching TV channel 1  from Bosnia-Herzegovina. After enabling some external JS, I got a Canli.center player in the box with the list of (?) other channels at the right. But the video was black and the audio garbled.

Please check that the content plays in FF with DRM disabled ([detailed instructions from _yt-dlp_ downstream](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056).

**Comment by dbojan** [comment]
From what I can see, you click on one of  the channels on the right, and the content is displayed in the window to the left.
Just tried it myself and got video and audio.
Tried some other channels, and they work fine in the browser, without disabling anything in firefox.

**Comment by dirkf** [comment]
We can't support DRM encrypted content, which is why I asked if the content would play in FF with **DRM disabled** (DRM = digital rights/restriction management is also termed EME = encrypted media extensions). It doesn't for me.

**Comment by dbojan** [comment]
ok, thanks.

**Comment by dirkf** [comment]
Feel free to test for yourself because I didn't get the specific diagnostic in my browser. If both of these are true, the test would be conclusive:
1. your FF has DRM enabled (and we already know that the content plays), and
2. temporarily disabling it according to the previously linked instructions makes the content fail to play, probably with a diagnostic,

then the site can't be supported.

Otherwise we could re-open the issue.
