### ISSUE TITLE
brew install failing

### ISSUE THREAD

**Issue by MtnBiker** [ytdl-org/youtube-dl#32982]
➜ brew install youtube-dl
Error: youtube-dl has been disabled because it has a failing test since forever and no new release since 2021! It was disabled on 2024-11-23.

**Comment by dirkf** [comment]
Obvs, ignore _brew_ and
* install using _pip_ or _pip3_ from the nightly repo (of which you will be aware since you read #30839, as asked), or
* just use the POSIX single file version from the nightly repo after ensuring that you have a Python >= 2.6 (admittedly quite untested in 3.13) that will be found with `/usr/bin/env python`: eg, make a link named `python` in the `PATH` to a previously installed or system-provided `python3` executable, bearing in mind that 3.9 is now the lowest version supported by the Python S/w Foundation.

**Comment by Isarhamster** [comment]
In this case you should update the installation instructions as this clearly states - use homebrew!
Usually, pip simply leads to an error:
-bash: pip: command not found
So the recommended solution should be downloading the executable directly from [Latest Nightly](https://github.com/ytdl-org/ytdl-nightly/releases/latest)

**Comment by dcast0607** [comment]
[This](https://github.com/ytdl-org/youtube-dl/pull/32928) worked for me.

**Comment by dirkf** [comment]
A solution that installs _yt-dlp_, not a bad thing in itself, would not help OP who wanted to install _youtube_dl_, or would not have posted here.

If you don't have a _pip_ or _pip3_ command in your Python environment, take it up with the supplier of that environment. Some packagers take the view that PyPi is a competitive and potentially conflicting package system and so disable it, even after Python added a _pip_ installation to the default installation.

How did you get on, @MtnBiker ?

**Comment by MtnBiker** [comment]
I don't have frequent enough need for a downloader, so for now will live with the ads. I fight enough computer problems and python isn't something I've used much; so this is a battle I'll pass on. But thanks for trying to help.

**Comment by Isarhamster** [comment]
I had to resort to yt-dlp, as after 
- Downloading youtube_dl
- `ln -s /usr/local/bin/python3 /usr/local/bin/python`
- `brew install ffmpeg`
- `spctl --assess /usr/local/bin/ffmpeg`
- Then going to System Settings -> Security -> Assessing ffmpeg as ok
- Downloading an arbitrary file from youtube I only got 
- `Got server HTTP error: HTTP Error 403: Forbidden. Retrying` ...
whereas yt-dlp didn't have any issue.

**Comment by dirkf** [comment]
No doubt you hit #32905.

**Comment by dirkf** [comment]
If OP had installed _yt-dl_, [those](https://github.com/ytdl-org/youtube-dl/issues/32982#issuecomment-2510120953) look like the necessary steps starting from scratch. The `spctl --assess` command is a useful hint for anyone with a Mac who hasn't wiped the overbearing OS. From [its _man_ page](https://www.unix.com/man-page/osx/8/SPCTL/), you can apparently just run `spctl --add --label ytdl program_path` to white-list each program needed for _yt-dl_.

`spctl --disable --label "Mac App Store"` is an _interesting_ example command.

**Comment by shellscape** [comment]
I'm just surprised y'all haven't worked out the install instructions. The issues here are a minefield of failure reports, and the instructions on the README don't work for most folks without bypassing SSL. Whew.

**Comment by bwoodruff** [comment]
Checking in from 2025 with no working install instructions for macOS. 😭

**Comment by dirkf** [comment]
Various non-HB installation tactics here: https://github.com/ytdl-org/youtube-dl/issues/32842#issuecomment-2225365387
