### ISSUE TITLE
Homebrew install on macOS broken 

### ISSUE THREAD

**Issue by peteyreplies** [ytdl-org/youtube-dl#32994]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

I have a new copy of Homebrew installed on my new laptop. Trying to install youtube-dl throws the following error, just FYI. 

> % brew install youtube-dl
> Error: youtube-dl has been disabled because it has a failing test since forever and no new release since 2021! It was disabled on 2024-11-23.

**Comment by dirkf** [comment]
https://github.com/ytdl-org/youtube-dl/issues/32982#issuecomment-2504964353
