### ISSUE TITLE
Unable to extract nsig function code

### ISSUE THREAD

**Issue by snoopy870** [ytdl-org/youtube-dl#32997]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17** (Also running most recent nightly build)
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
ERROR: Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
```

## Description

Youtube-dl no longer appears to be matching the correct regex pattern to extract videos from YouTube.

**Comment by dirkf** [comment]
#32986.
Try 2024-12-17 nightly, if you didn't already, and open a new issue according to #30839 if you still have a problem.
