### ISSUE TITLE
youtube-dl=2017.12.17,unable.to.extract.uploader.id.from.youtube

### ISSUE THREAD

**Issue by androidup** [ytdl-org/youtube-dl#33000]
## Checklist

system backgrounds:
Laptop，OS.name = Win11 Home，version=10.0.22631,Use 3rd party proxy(like clash.exe，external links only)
more verbose pleaser refer to picture．Besides，I didn't find output template from user guide or manual，do I first retrieve from links with --oufput  then select by my own？many thanks

## Verbose log

 Downloading just video sXVZ5X8CN6g because of --no-playlist
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Program Files\python3_64\lib\site-packages\youtube_dl-2021.12.17-py3.6.egg\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\python3_64\lib\site-packages\youtube_dl-2021.12.17-py3.6.egg\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)                                                   File "C:\Program Files\python3_64\lib\site-packages\youtube_dl-2021.12.17-py3.6.egg\youtube_dl\extractor\common.py", line 534, in extract                         ie_result = self._real_extract(url)                                           File "C:\Program Files\python3_64\lib\site-packages\youtube_dl-2021.12.17-py3.6.egg\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Program Files\python3_64\lib\site-packages\youtube_dl-2021.12.17-py3.6.egg\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
![youtube-dl-2017 12 17=unable-to-extract-uploader-id](https://github.com/user-attachments/assets/a011fcae-432b-4a32-935b-53c52b737d91)

**Comment by dirkf** [comment]
Please read #30839 **as asked**. You need the nightly build version. The output template option `--output ...`/`-o ...` is [described, including the default, in the program documentation](https://github.com/ytdl-org/youtube-dl#user-content-output-template), which you should also read.
