### ISSUE TITLE
So, How I download on 1080p on the newest Nightly build?

### ISSUE THREAD

**Issue by marvyn7** [ytdl-org/youtube-dl#33009]
- [x ] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

So, I was using the older yt-dlp executable, using this command format:

"yt-dlp  (url) -S vcodec:h264,fps,res:720,acodec:m4a "

Which I was told, and latter confirmed, to be able to get the videos on 1080p instead of the highest definition by default (which most of time were too big to be compatible with my cellphone)

Now, I downloaded the new build's executable, and I got the doubt, does using the format for the command as 

"youtube-dl (url)  vcodec:h264,fps,res:720,acodec:m4a" 

Works for the same? I tried to use the -S of the original command, but the prompt said that format is not compatible.

**Comment by tansy** [comment]
Like in old one.

```
$ youtube-dl --help | grep -i format
  Video Format Options:
    -f, --format FORMAT                  Video format code, see the "FORMAT SELECTION" for all the info
(...)
    -F, --list-formats                   List all available formats of requested videos

$ youtube-dl --list-formats https://www.youtube.com/watch?v=NY3jthvTcSg
[info] Available formats for NY3jthvTcSg:
format code  extension  resolution note
(...)
137          mp4        1080x1920  1080p 1147k , mp4_dash container, avc1.640028, 30fps, video only, 38.70MiB
18           mp4        202x360    240p  189k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 6.38MiB (best)

$ youtube-dl --format https://www.youtube.com/watch?v=NY3jthvTcSg
[download] Destination: ...
[download] 100% of 38.07MiB in 00:25

```

**Comment by dirkf** [comment]
OP needs to read #30839 again:
>... if you were actually running _yt-dlp_, ...

**Comment by marvyn7** [comment]
> Like in old one.
> 
> ```
> $ youtube-dl --help | grep -i format
>   Video Format Options:
>     -f, --format FORMAT                  Video format code, see the "FORMAT SELECTION" for all the info
> (...)
>     -F, --list-formats                   List all available formats of requested videos
> 
> $ youtube-dl --list-formats https://www.youtube.com/watch?v=NY3jthvTcSg
> [info] Available formats for NY3jthvTcSg:
> format code  extension  resolution note
> (...)
> 137          mp4        1080x1920  1080p 1147k , mp4_dash container, avc1.640028, 30fps, video only, 38.70MiB
> 18           mp4        202x360    240p  189k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 6.38MiB (best)
> 
> $ youtube-dl --format 137 https://www.youtube.com/watch?v=NY3jthvTcSg
> [download] Destination: ...
> [download] 100% of 38.07MiB in 00:25
> ```

Thank you
