### ISSUE TITLE
Use gzip encoding for communication downloads

### ISSUE THREAD

**Issue by tansy** [ytdl-org/youtube-dl#33010]
## Checklist

- [x ] I'm reporting a feature request
- [x ] I've verified that I'm running youtube-dl version **2024.12.17**
- [x ] I've searched the bugtracker for similar feature requests including closed ones

## Description

Use gzip encoding for communication downloads

When ytdl communicates with site it downloads large amounts of textual data that is easily compressible. If it was able to use gzip encoding it could save lot of time spent on downloading megabytes of server responses.

Quict test shows that ServiceLogin (url taken from extractor/youtube.py:139:) compresses 6 times.
Json downloaded with \`-j' compresses 37 times.
6 times shorter downloads would surely improve speed of the program.

```
URL="https://www.youtube.com/watch?v=9qYJ7GRam84"
SERVICELOGIN_URL="https://accounts.google.com/ServiceLogin?passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Fnext%3D%252F%26action_handle_signin%3Dtrue%26hl%3Den%26app%3Ddesktop%26feature%3Dsign_in_button&hl=en&service=youtube&uilel=3&requestPath=%2FServiceLogin&Page=PasswordSeparationSignIn"

wget -O"ServiceLogin" "$SERVICELOGIN_URL"
wget --header="accept-encoding: gzip" -O"ServiceLogin.gz" "$SERVICELOGIN_URL"

youtube-dl -j "$URL" > 9qYJ7GRam84.json
gzip -k 9qYJ7GRam84.json

wc -c *

 550473 9qYJ7GRam84.json
  14979 9qYJ7GRam84.json.gz
 840181 ServiceLogin
 140345 ServiceLogin.gz
```

PS.
I tried to test that with gzip module but couldn't map memory buffer into file that gzip.GzipFile could use.

**Comment by dirkf** [comment]
If the site wants to send gzipped content, _yt-dl_ should be happy to accept and decode it. This all happens inside the `utils.YoutubeDLHandler` class.

Other RFC content compression methods are supported if the corresponding required compression modules are available. If, say, YT decides to offer Brotli ("invented here") or nothing, and the _yt-dl_ Python environment has no `brotli` module, YT's content won't be compressed.

**Comment by tansy** [comment]
> This all happens inside the utils.YoutubeDLHandler class.

Actually. Didn't see that coming.

> If, say, YT decides to offer Brotli ("invented here") or nothing

YT, nor anything/one does not decide 'to offer' brotli, nor anything else. Requester does - in a sense - requester sends list of accepted encodings and server returns requested content, encoded as asked. So they won't offer you brotli if you don't ask for it.
And btw, this particular server only accepts gzip. Same with github.

Count it as solved.
Happy new year.

-----
[Accept-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding)

**Comment by dirkf** [comment]
Absolutely. s/offer/use only/ !
