### ISSUE TITLE
youtube-dl --get-url is not working .... for dailymotion

### ISSUE THREAD

**Issue by shahzadakram** [ytdl-org/youtube-dl#3553]
I am using this command ..

youtube-dl --get-url http://www.dailymotion.com/arynews

got this message : 

WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.dailymotion.com/arynews; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

but i see its uptodate version :

**Comment by davidlowryduda** [comment]
This issue appears clear and stale. I suggest that it be closed.
