### ISSUE TITLE
YouTube said: This video is not available.

### ISSUE THREAD

**Issue by galets** [ytdl-org/youtube-dl#3700]
youtube-dl "https://www.youtube.com/watch?v=oU7rqB9E_0M&index=2&list=PL2tMgWgIvcWnpy6by9T0ZKyxLcZ2W4Pcs"

[youtube:playlist] Downloading playlist PL2tMgWgIvcWnpy6by9T0ZKyxLcZ2W4Pcs - add --no-playlist to just download video oU7rqB9E_0M
[youtube:playlist] PL2tMgWgIvcWnpy6by9T0ZKyxLcZ2W4Pcs: Downloading webpage
[download] Downloading playlist: Queen's Greatest Hits of the 1970s
[youtube:playlist] playlist Queen's Greatest Hits of the 1970s: Collected 17 video ids (downloading 17 of them)
[download] Downloading video #1 of 17
[youtube] Setting language
[youtube] JofwEB9g1zg: Downloading webpage
[youtube] JofwEB9g1zg: Downloading video info webpage
ERROR: JofwEB9g1zg: YouTube said: This video is not available.

**Comment by Krenair** [comment]
I think when downloading a playlist and finding an unavailable video, instead of just throwing an exception and stopping, the -i parameter should at least be advertised.
