### ISSUE TITLE
youtube-dl fails, wget succeeds

### ISSUE THREAD

**Issue by frostyfrog** [ytdl-org/youtube-dl#372]
So I'm trying to download a bunch of youtube videos from a file, and I keep getting stuck on this error:

```
[youtube] AB_MsFG7Z1k: Downloading video webpage
[youtube] AB_MsFG7Z1k: Downloading video info webpage
[youtube] AB_MsFG7Z1k: Extracting video information
[info] Video description metadata as JSON to: 00011_Nightcore_-_Flying_High_-20110421.flv.info.json
ERROR: unable to download video data: ''
```

I decided to grab the url from the json file and send it to wget, which succeeded. I really want to use youtube-dl though (which doesn't try to skip over the error either :( ). Is there any known way around this problem? (I am able to redownload every video up to this point over again, so I'm not entirely sure it's youtube's fault...)

The command that I've been running is:
`youtube-dl --write-info-json -a vids2 -o "%(autonumber)s_%(stitle)s_-%(upload_date)s-_%(uploader)s.%(ext)s" -wc`

_Edit (Added version info):_

```
[root@Atlanta Desktop]# uname -a
Linux Atlanta 3.3.7-1-ARCH #1 SMP PREEMPT Mon May 21 22:39:59 UTC 2012 i686 GNU/Linux
[root@Atlanta Desktop]# python2.7 --version
Python 2.7.3
[root@Atlanta Desktop]# youtube-dl --version
2012.02.27
```

**Comment by ravkr** [comment]
is this still a problem? or can we close it now?

**Comment by ealgase** [comment]
Tested it, no longer appears to be an issue.
