### ISSUE TITLE
ERROR: Unsupported URL: http://www.biography.com/people/vincent-van-gogh-9515695/videos/vincent-van-gogh-full-episode-2075049808

### ISSUE THREAD

**Issue by scottstensland** [ytdl-org/youtube-dl#3863]
here is a unsupported url

youtube-dl -c -l --verbose  http://www.biography.com/people/vincent-van-gogh-9515695/videos/vincent-van-gogh-full-episode-2075049808
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-c', '-l', '--verbose', 'http://www.biography.com/people/vincent-van-gogh-9515695/videos/vincent-van-gogh-full-episode-2075049808']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.09.29.2
[debug] Python version 2.7.6 - Linux-3.13.0-36-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[generic] vincent-van-gogh-full-episode-2075049808: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vincent-van-gogh-full-episode-2075049808: Downloading webpage
[generic] vincent-van-gogh-full-episode-2075049808: Extracting information
ERROR: Unsupported URL: http://www.biography.com/people/vincent-van-gogh-9515695/videos/vincent-van-gogh-full-episode-2075049808; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 556, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1540, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 9, column 19
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 524, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 191, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 913, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.biography.com/people/vincent-van-gogh-9515695/videos/vincent-van-gogh-full-episode-2075049808; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

youtube-dl --version
2014.09.29.2

 uname -a
Linux kamchatka 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

ununtu 14.04

**Comment by TRox1972** [comment]
ThePlatform-embed
