### ISSUE TITLE
May have found the cause of continuing, long-standing C-Span problems

### ISSUE THREAD

**Issue by bonacker** [ytdl-org/youtube-dl#3878]
I have been frustrated trying to download C-Span videos. Sometimes the same video will not download but then a few minuutes or hours later it will with exactly the same Youtube-dl switches. Then it will continue to fail or succeed intermittently. 

I think I may have figured out why. When the domain for the URL to the .mp4 is cspan-146.c-spanarchives.org, Youtube-dl reports not getting any data blocks. When the domain for the .mp4 is http://d19cp144waw2mw.cloudfront.net the download succeeds.

When I try to play these two URLs in mPlayer, the Cloudfronts play but the c-spanarchives.orgs don't. I used the --write-info-json switch as an easy way to view and copy the .mp4 URLs.

Everything else that Youtube-dl does is identical to the point of writing the .mp4 URL. Then if the URL is bad, it tries rtmpdump, but that never succeeds. I can paste the verbose output if necessary, but I'd like to know if people can confirm the problem is that C-Span serves two different domains with one of them working and the other not. The videos that won't download in Youtube-dl will play in the browser.

If what I described is accurate, would the people who write the scripts be able to fix the program so that both URLs would work? I cannot write scripts or understand a word of Python. Sorry, and TIA.

**Comment by dstftw** [comment]
If this is still actual, post the verbose output demonstrating the issue.
