### ISSUE TITLE
file corruption: youtube, youtube-dl, or what?

### ISSUE THREAD

**Issue by Albretch** [ytdl-org/youtube-dl#411]
Apparently, if you use youtube-dl and for the naming use just the URI or the name given in the verbal description of the file the files contents differ even though their lengths are the same and they "look" the same even if you download the files one right after the other (they don't use tildes ("~") in youtube URIs):

export _YT_URI=qkSuYoexbiY
echo ${_YT_URI}

date
youtube-dl --no-overwrites --continue --no-progress --audio-format
best --max-quality mp4 -o
'%(uploader)s'"/"'%(stitle)s'"~"${_YT_URI}.'%(ext)s'
"http://www.youtube.com/watch?v=${_YT_URI}&hd=1"

date

youtube-dl --no-overwrites --continue --no-progress --audio-format
best --max-quality mp4 -o '%(uploader)s'"/"${_YT_URI}.'%(ext)s'
"http://www.youtube.com/watch?v=${_YT_URI}&hd=1"

date

$ ls -lR
.:
total 4
drwxr-xr-x 2 knoppix knoppix 4096 Aug 29 12:03 TheYoungTurks

./TheYoungTurks:
total 260528
-rw-r--r-- 1 knoppix knoppix 133389811 Jun  4 23:31
Bradley_Manning_Trial_Update~qkSuYoexbiY.mp4
-rw-r--r-- 1 knoppix knoppix 133389811 Jun  4 23:31 qkSuYoexbiY.mp4

$ md5sum -b TheYoungTurks/Bradley_Manning_Trial_Update~qkSuYoexbiY.mp4
d7c2064ee789dd79395da15ab2bcd1b2
*TheYoungTurks/Bradley_Manning_Trial_Update~qkSuYoexbiY.mp4

$ md5sum -b TheYoungTurks/qkSuYoexbiY.mp4
d7a5937fda4ad2d8819e97e1c041b29b *TheYoungTurks/qkSuYoexbiY.mp4

 Which utility would you use to check media files on a binary data level and see if the difference lies in some metadata or it is just some other kind of corruption? So the ultility must "understand" media files?

 What do you think is going on here?

 thanks
 lbrtchx

**Comment by ZainRizvi** [comment]
Seems like an obsolete issue.  Shall we close this?
