### ISSUE TITLE
MLB URL

### ISSUE THREAD

**Issue by RingoTheDog** [ytdl-org/youtube-dl#4216]
URL: http://wapc.mlb.com/cutfour/2014/11/15/101531996/video-japanese-broadcast-calls-samurai-japans-no-hitter?adbid=533657287378731008&adbpl=tw&adbpr=544620720&partnerId=as_mlb_20141115_35679597

youtube-dl -v http://wapc.mlb.com/cutfour/2014/11/15/101531996/video-japanese-broadcast-calls-samurai-japans-no-hitter?adbid=533657287378731008&a
dbpl=tw&adbpr=544620720&partnerId=as_mlb_20141115_35679597
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://wapc.mlb.com/cutfour/2014/11/15/101531
996/video-japanese-broadcast-calls-samurai-japans-no-hitter?adbid=53365728737873
1008']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2014.11.16
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-
[debug] Proxy map: {}
[generic] video-japanese-broadcast-calls-samurai-japans-no-hitter?adbid=53365728
7378731008: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video-japanese-broadcast-calls-samurai-japans-no-hitter?adbid=53365728
7378731008: Downloading webpage
[generic] video-japanese-broadcast-calls-samurai-japans-no-hitter?adbid=53365728
7378731008: Extracting information
ERROR: Unsupported URL: http://wapc.mlb.com/cutfour/2014/11/15/101531996/video-j
apanese-broadcast-calls-samurai-japans-no-hitter?adbid=533657287378731008; pleas
e report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with t
he --verbose flag and include its complete output. Make sure you are using the l
atest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 609, in _real_extract
  File "youtube_dl\utils.pyo", line 1319, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: XML declaration not well-formed: line 1, column 20
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 536, in extract_info
  File "youtube_dl\extractor\common.pyo", line 199, in extract
  File "youtube_dl\extractor\generic.pyo", line 996, in _real_extract
ExtractorError: Unsupported URL: http://wapc.mlb.com/cutfour/2014/11/15/10153199
6/video-japanese-broadcast-calls-samurai-japans-no-hitter?adbid=5336572873787310
08; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-
dl with the --verbose flag and include its complete output. Make sure you are us
ing the latest version; type  youtube-dl -U  to update.

'adbpl' is not recognized as an internal or external command,
operable program or batch file.
'adbpr' is not recognized as an internal or external command,
operable program or batch file.
'partnerId' is not recognized as an internal or external command,
operable program or batch file.

Thanks (or in the is case Domo Arigatou!)
Ringo

**Comment by remitamine** [comment]
No longer accessible.
