### ISSUE TITLE
--no-playlist doesn't work with Vimeo

### ISSUE THREAD

**Issue by edumj** [ytdl-org/youtube-dl#4239]
Hi,

the "--no-playlist" option doesn't work with albums (or channels, users, ...) in Vimeo, it just downloads all videos, although it knows it's a playlist! 

Example:
http://vimeo.com/album/2307466/video/1431107

It says:
[vimeo:album] 2307466: Downloading page 1
[vimeo:album] 2307466: Downloading page 2
[vimeo:album] 2307466: Downloading page 3
[vimeo:album] 2307466: Downloading page 4
[download] Downloading playlist: playlist
[vimeo:album] playlist playlist: Collected 47 video ids (downloading 47 of them)
[download] Downloading video #1 of 47
...

Edu.

**Comment by Jenselme** [comment]
Hi,

I still have this issue with youtube-dl 2015.12.23. Can you fix this please?
