### ISSUE TITLE
TVNZ/brightcove said:

### ISSUE THREAD

**Issue by bohwaz** [ytdl-org/youtube-dl#4256]
This is what I get with TVNZ:

$ youtube-dl -v 'http://tvnz.co.nz/intrepid-nz/s1-ep8-video-6123341'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://tvnz.co.nz/intrepid-nz/s1-ep8-video-6123341']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.20
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.7
[debug] exe versions: avconv 1.0.10, avprobe 1.0.10, ffmpeg 1.0.10, ffprobe 1.0.10, rtmpdump 2.4
[debug] Proxy map: {}
[generic] s1-ep8-video-6123341: Requesting header
WARNING: Falling back on generic information extractor.
[generic] s1-ep8-video-6123341: Downloading webpage
[generic] s1-ep8-video-6123341: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: Intrepid NZ, Series 1, Episode 8 | TVNZ Ondemand
[generic] playlist Intrepid NZ, Series 1, Episode 8 | TVNZ Ondemand: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
[Brightcove] ref:6123341: Downloading webpage
ERROR: brightcove said: 
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 536, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 199, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 202, in _real_extract
    videoPlayer[0], query_str, query, referer=referer)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 226, in _get_video_info
    'brightcove said: %s' % error_msg, expected=True)
ExtractorError: brightcove said:

**Comment by canavan** [comment]
http://www.zeit.de/video/2014-01/3021528351001 results in the same message (ERROR: brightcove said: This player is not enabled for HTML5 delivery.). Is it even theoretically possible to download such videos?

**Comment by jcm36** [comment]
Any updates on this? Would be great to be able to download from tvnz. Thanks.

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by bohwaz** [comment]
Yes that show is not available online anymore.
