### ISSUE TITLE
Add support for portal.stretchinternet.com (was: Yet another Unsupported URL error ; ParseError: not well-formed (invalid token): )

### ISSUE THREAD

**Issue by grouch0** [ytdl-org/youtube-dl#4319]
C:\Users\Mike>.\youtube-dl.exe -U
youtube-dl is up-to-date (2014.11.26.4)

C:\Users\Mike>.\youtube-dl.exe --verbose "http://portal.stretchinternet.com/olivetadmin/full.htm?eventId=173659&streamType=video"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://portal.stretchinternet.com/olivetadmin/full.htm?eventId=173659&streamType=video']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.11.26.4
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[generic] full: Requesting header
WARNING: Could not send HEAD request to http://portal.stretchinternet.com/olivet
admin/full.htm?eventId=173659&streamType=video: HTTP Error 405: Method Not Allow
ed
[generic] full: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] full: Extracting information
ERROR: Unsupported URL: http://portal.stretchinternet.com/olivetadmin/full.htm?e
ventId=173659&streamType=video; please report this issue on https://yt-dl.org/bu
g . Make sure you are using the latest version; type  youtube-dl -U  to update.
Be sure to call youtube-dl with the --verbose flag and include its complete outp
ut.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 651, in _real_extract
  File "youtube_dl\utils.pyo", line 1411, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 198, column 81
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 553, in extract_info
  File "youtube_dl\extractor\common.pyo", line 240, in extract
  File "youtube_dl\extractor\generic.pyo", line 1044, in _real_extract
ExtractorError: Unsupported URL: http://portal.stretchinternet.com/olivetadmin/f
ull.htm?eventId=173659&streamType=video; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
 update. Be sure to call youtube-dl with the --verbose flag and include its comp
lete output.

C:\Users\Mike>

**Comment by mpenkov** [comment]
The bug is still present.

```
$ youtube-dl --verbose "http://portal.stretchinternet.com/olivetadmin/full.htm?eventId=173659&streamType=video"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://portal.stretchinternet.com/olivetadmin/full.htm?eventId=173659&streamType=video']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.5 (CPython) - Linux-4.15.0-29-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] full: Requesting header
[redirect] Following redirect to https://portal.stretchinternet.com/olivetadmin/full.htm?eventId=173659&streamType=video
[generic] full: Requesting header
WARNING: Could not send HEAD request to https://portal.stretchinternet.com/olivetadmin/full.htm?eventId=173659&streamType=video: HTTP Error 405: Method Not Allowed
[generic] full: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] full: Extracting information
ERROR: Unsupported URL: https://portal.stretchinternet.com/olivetadmin/full.htm?eventId=173659&streamType=video
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/generic.py", line 3151, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://portal.stretchinternet.com/olivetadmin/full.htm?eventId=173659&streamType=video

$ youtube-dl --version
2018.03.14
```
