### ISSUE TITLE
[how to] extract all vk urls

### ISSUE THREAD

**Issue by muhasturk** [ytdl-org/youtube-dl#4470]
Hello, 
I would like to extract all urls of [Rumour Balbal](http://vk.com/videos233941067). I run the following command it returns only 12 video urls. But there are 278 videos on his proile.

`youtube-dl http://vk.com/videos233941067\?section\=all --username blabla@blabla.com --password blabla  -g`

How can I extract all 278 urls?

![](http://i.imgur.com/LVXCFQi.jpg)

**Comment by zelenin** [comment]
```js
var videos = cur.videoList.all.list;
for (var i = 0; i < videos.length; i++) {
    var video = videos[i];
    var link = 'https://vk.com/video' + video[0] + '_' + video[1];
    console.log(link);
}
```
I wrote this js for community videos page (https://vk.com/videos-***?section=all)
