### ISSUE TITLE
410 Gone with -f bestvideo on YouTube

### ISSUE THREAD

**Issue by ivan** [ytdl-org/youtube-dl#4532]
YouTube reports that it has format 299 for https://www.youtube.com/watch?v=zj2qtLCxmfE when it doesn't, causing `-f bestvideo` to fail:

```
$ PYTHONPATH=. python3 ./bin/youtube-dl -f bestvideo "https://www.youtube.com/watch?v=zj2qtLCxmfE"
[youtube] zj2qtLCxmfE: Downloading webpage
[youtube] zj2qtLCxmfE: Extracting video information
[youtube] zj2qtLCxmfE: Downloading DASH manifest
[download] Resuming download at byte 1047552
ERROR: unable to download video data: HTTP Error 410: Gone

$ PYTHONPATH=. python3 ./bin/youtube-dl -f 299 "https://www.youtube.com/watch?v=zj2qtLCxmfE"      
[youtube] zj2qtLCxmfE: Downloading webpage
[youtube] zj2qtLCxmfE: Extracting video information
[youtube] zj2qtLCxmfE: Downloading DASH manifest
[download] Resuming download at byte 1047552
ERROR: unable to download video data: HTTP Error 410: Gone
```

It does have the VP9 format 303, though.

It's been that way for a month, so it's not a temporary YouTube error.

Related: #2352 where YouTube is reporting that it has format 43 for m34r0BLy5YU but doesn't.

Maybe it's worth dropping to the next format when getting a 410 Gone?

**Comment by ivan** [comment]
Format 299 for this particular video was fixed on YouTube's side.

**Comment by ivan** [comment]
Never mind, I checked incorrectly.

**Comment by fstirlitz** [comment]
Another video, same issue; this time with `-f bestaudio`. The video stream downloads normally.
```
$ youtube-dl -v VoxZuggJk0I -f bestaudio
[debug] System config: []
[debug] User config: ['--continue', '--add-metadata', '--merge-output-format', 'mkv']
[debug] Command-line args: ['--xattrs', '-v', 'VoxZuggJk0I', '-f', 'bestaudio']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.29
[debug] Python version 3.4.3 - Linux-4.0.4-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg N-72229-gb44a55a, ffprobe N-72229-gb44a55a, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] VoxZuggJk0I: Downloading webpage
[youtube] VoxZuggJk0I: Extracting video information
[youtube] VoxZuggJk0I: Downloading DASH manifest
[debug] Invoking downloader on '[DATA EXPUNGED]'
ERROR: unable to download video data: HTTP Error 410: Gone
```

**Comment by ivan** [comment]
Also happens for https://www.youtube.com/watch?v=p7jUrkfMtr4 - getting bestvideo (format 248) results in 410 Gone.

**Comment by avih** [comment]
Same with https://www.youtube.com/watch?v=OAPOhk4A7ps (video plays fine, `410 gone` for the audio).

**Comment by starrychloe** [comment]
Related, for audio: https://github.com/rg3/youtube-dl/issues/9715

**Comment by christiangenco** [comment]
For posterity, these errors can be ignored with the `--ignore-errors` flag.

**Comment by YashKumarVerma** [comment]
facing this in 2021 :(
tried to download this playlist
https://www.youtube.com/playlist?list=PLU_sdQYzUj2keVENTP0a5rdykRSgg9Wp-

**Comment by llacb47** [comment]
@YashKumarVerma Imagine replying to an old issue because you don't know how to update youtube-dl. Shame.

**Comment by supereckspert** [comment]
@llacb47 Imagine making snarky comments of people not using updated software to people using the latest software. Shame.
```
sudo youtube-dl -U
youtube-dl is up-to-date (2021.06.06)
youtube-dl -f bestvideo+bestaudio/best -ciw -v --socket-timeout 10 --retries infinite -o "%(upload_date)s-%(title)s.%(ext)s" https://www.youtube.com/watch?v=G8E2ynt3af0
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: 'bool' object has no attribute 'split'
```
