### ISSUE TITLE
Graphical user interface

### ISSUE THREAD

**Issue by Rudloff** [ytdl-org/youtube-dl#469]
CLI is fine for me, but not for everyone.

I wrote basic implementations in PHP/HTML and in Perl/GTK here:
https://svn.strasweb.fr/listing.php?repname=Pierre+Rudloff&path=%2Fyoutoubeur%2F

**Comment by nodiscc** [comment]
Is there a youtube-dl Firefox addon without need for a separate server? (toolbar button that calls a local youtube-dl/youtube-dl-gui binary)

It was proposed to add youtube-dl as a backend for https://github.com/IsSuEat/open-livestreamer-firefox-addon (issue [here](https://github.com/IsSuEat/open-livestreamer-firefox-addon/issues/15)) but I wasn't able to add it myself.

I can recommend https://github.com/MrS0m30n3/youtube-dl-gui and https://github.com/Rudloff/alltube, both great.

**Comment by david476** [comment]
I've only spent a day or so on it, but I've been working on a Java based, open-source frontend. Fully functional at the moment, you can specify additional options on top of the downloads folder and username/password. If anyone wants to try it out:

https://github.com/david476/YTDL-Frontend

**Comment by vitorgalvao** [comment]
Many people have built GUIs and websites with `youtube-dl` as a backend, and they’re pretty asy to find. With that in mind, officially supporting a GUI doesn’t seem to be necessary.

I’d say this issue can be closed.

**Comment by yan12125** [comment]
FYI: having a GUI frontend is never considered as an official plan, and IMO it's good to leave this issue open to serve as the role of a Wiki page before #11234 gets resolved.

**Comment by Moriand** [comment]
someone has done graphical interface in wxpython

**Comment by vitorgalvao** [comment]
> someone has done graphical interface in wxpython

@Moriand [That was already mentioned](https://github.com/rg3/youtube-dl/issues/469#issuecomment-36909911).

**Comment by OlHermit** [comment]
Issue appears stale - should it be closed?

1. [readme.md](https://github.com/ytdl-org/youtube-dl/blob/master/README.md) clearly indicates this is a command line only tool
2. Many references within this issue point to other GUI tools now available. 
3. Issue was raised 6 years ago
4. OP introduced another project with links that (presumably) satisfies the original request.
5. Leaving an issue open to indicate it won't be worked on (as per @yan12125 above's opinion) doesn't clearly indicate the intent to work on this issue - closed is a better indicator of 'won't do' and can still be searched in issues database.

**Comment by ByerDev** [comment]
please close, its been so long.
