### ISSUE TITLE
"ERROR: Unable to extract list title" downloading private video from Vimeo.

### ISSUE THREAD

**Issue by escobarj** [ytdl-org/youtube-dl#4917]
youtube-dl --verbose --video-password ****\* http://vimeo.com/album/3086144/video/109059888
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--video-password', u'PRIVATE', 'http://vimeo.com/album/3086144/video/109059888']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.09.2
[debug] Python version 2.7.6 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo:album] 3086144: Downloading page 1
ERROR: Unable to extract list title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 619, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 268, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 475, in _real_extract
    return self._extract_videos(album_id, 'http://vimeo.com/album/%s' % album_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 429, in _extract_videos
    'title': self._extract_list_title(webpage),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 413, in _extract_list_title
    return self._html_search_regex(self._TITLE_RE, webpage, 'list title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 524, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract list title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by phihag** [comment]
Thank you for the report. I believe this issue to be fixed in youtube-dl 2015.02.10.3 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by escobarj** [comment]
Better, but now I get 'ERROR: Wrong password: HTTP Error 418' error.
I know I’m using the correct password because I it works on the webpage.

youtube-dl -v --video-password ***** http://vimeo.com/album/3086144/video/109059888
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--video-password', u'PRIVATE', 'http://vimeo.com/album/3086144/video/109059888']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.10.3
[debug] Python version 2.7.6 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo:album] 3086144: Downloading page 1
[vimeo:album] 3086144: Verifying the password
[vimeo:album] 3086144: Downloading page 2
[download] Downloading playlist: Swift Training Videos
[vimeo:album] playlist Swift Training Videos: Collected 14 video ids (downloading 14 of them)
[download] Downloading video 1 of 14
[vimeo] 108675737: Downloading webpage
[vimeo] 108675737: Extracting information
[vimeo] 108675737: Verifying the password
ERROR: Wrong password: HTTP Error 418: I'm a teapot (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 308, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1610, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by phihag** [comment]
Are there by any chance passwords both on the album and the individual video? If that's the case, we must extend our password functionality to allow for both.

**Comment by escobarj** [comment]
I only enter the password once when viewing the videos on vemio.com. But the videos in the album are also marked private, so its possible.
I can privately email you the password if that would help testing.

**Comment by phihag** [comment]
Yes, that would help a lot. My email address is phihag@phihag.de .

**Comment by m-kozlowski** [comment]
From what i've discovered, album password will grant access to videos only if they are accessed via vimeo.com/album/<album_id>/video/<video_id> scheme.
VimeoAlbumIE however builds playlist using vimeo.com/<video_id>
Accessing videos individually using those shorter URIs is possible but most likely requires different password.

**Comment by NuPied** [comment]
Any updates on this issue? Is it possible to provide two different passwords, one for the album and one for the video, in cases where these are different? Maybe any hints about how this could be fixed in the source code (if it's an easy fix)?

> $ /usr/local/bin/youtube-dl --verbose --playlist-items 5 https://vimeo.com/album/SomeAlbum/video/SomeVideo --video-password SomePassword
> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: [u'--verbose', u'--playlist-items', u'5', u'https://vimeo.com/album/SomeAlbum/video/SomeVideo', u'--video-password', u'PRIVATE']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2016.03.14
> [debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
> [debug] exe versions: avconv 11.4-6, avprobe 11.4-6
> [debug] Proxy map: {}
> [vimeo:album] SomeAlbum: Downloading page 1
> [vimeo:album] SomeAlbum: Verifying the password
> [download] Downloading playlist: SomePlaylist
> [vimeo:album] SomeAlbum: Downloading page 2
> [vimeo:album] playlist SomePlaylist: Downloading 1 videos
> [download] Downloading video 1 of 1
> [vimeo] SomeVideo: Downloading webpage
> [vimeo] SomeVideo: Extracting information
> [vimeo] SomeVideo: Verifying the password
> ERROR: Wrong password: HTTP Error 418: I'm a teapot (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 365, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1929, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 437, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python2.7/urllib2.py", line 475, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
