### ISSUE TITLE
Unsupported URL einsplus.de

### ISSUE THREAD

**Issue by matschmann** [ytdl-org/youtube-dl#5104]
Downloading the video from http://www.einsplus.de/-/id=15131588/11u4oy4/index.html doesn't work:

```
[rs@RainersMac ~/Movies] youtube-dl http://www.einsplus.de/-/id\=15131588/11u4oy4/index.html -v                 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.einsplus.de/-/id=15131588/11u4oy4/index.html', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.28
[debug] Python version 2.7.8 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.3.2, ffprobe 2.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] index: Requesting header
WARNING: Falling back on generic information extractor.
[generic] index: Downloading webpage
[generic] index: Extracting information
ERROR: Unsupported URL: http://www.einsplus.de/-/id=15131588/11u4oy4/index.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 751, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1522, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 227, column 97
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 643, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1202, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.einsplus.de/-/id=15131588/11u4oy4/index.html
```

**Comment by tiktok7** [comment]
Based on a quick look at the request stream from the browser, I could see the following pattern.

Example: `http://www.einsplus.de/go__geek-folge-01/-/id=15131588/did=15175110/nid=15131588/1rx08f1/index.html` contains the following code fragment:

```html
<script>var _nlvq=[['api','picsters'],['uid','YHV29Z'],['width','640'],['height','360']];</script>
```

The video information is requested in json format with the same parameters: `http://nlv.bittubes.com/db/meta.json9.php?api=picsters&uid=YHV29Z`

The available video formats are listed in the json file under the "Source" key name (ignore "Objects"... it contains links to the embedded links displayed during the video replay)

I see a few problems with this:
1. Other programme pages on the site don't seem to use the same method of delivery - [example](http://www.einsplus.de/wochenwebschau-vom-03-gefaehrlicher-trend-swatting-facebook-spioniert-penis-logos/-/id=10618492/did=15329306/nid=10618492/19k9tfu/index.html) or [example2](http://www.einsplus.de/folge-14-science-of-breaking-bad-und-was-alles-so-in-unserem-essen-steckt/-/id=10618492/did=14768114/nid=10618492/y4pifh/index.html)  
2. The generic downloader seems to be at least starting a download with the normal flash video app on the other pages (albeit with errors and warnings)
3. The link for the json seems to be put together by the off-site script (bittubes.com... meta.json9 etc). I could find no reference to the link in the html content.

@matschmann: are you sure this isn't just a once off format for this series? Are there other series with the same format on the site?

**Comment by thtomate** [comment]
einsplus does not exist anymore.
