### ISSUE TITLE
Question: Collection support

### ISSUE THREAD

**Issue by Nokoff** [ytdl-org/youtube-dl#5180]
Regarding "Collections". Under my subscriptions I have many channels that I subscribe to across a variety of genres, however, I would only like to download my music related subscriptions. I have tried adding music related channels to a "Collection" in youtube, and would like to know if possible to download this somehow. The URL in question to my collection is : https://www.youtube.com/feed/SCyEM2kdyBDLdC66Yjrsm2aQ1ZE6YPL3kNs

**Comment by dstftw** [comment]
No longer available.
