### ISSUE TITLE
Site Request:  Comcast Sportsnet

### ISSUE THREAD

**Issue by RingoTheDog** [ytdl-org/youtube-dl#5432]
Comcast Sports uses "ThePlatform"
NOTE: Comcast Sports are affiliated with (co-owned by?) NBCSports, which also use "ThePlatform"

URL: http://www.csnne.com/blog/bruins-talk/charlie-jacobs-disgusted-bs-unacceptable-play

youtube-dl.py -v "http://www.csnne.com/blog/bruins-talk/charlie-jacobs-disgusted-bs-unacceptable-play"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.csnne.com/blog/bruins-talk/charlie-jacobs-disgusted-bs-unacceptable-play']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.6 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-g31dfe20, rtmpdump 2.4
[debug] Proxy map: {}
[generic] charlie-jacobs-disgusted-bs-unacceptable-play: Requesting header
WARNING: Falling back on generic information extractor.
[generic] charlie-jacobs-disgusted-bs-unacceptable-play: Downloading webpage
[generic] charlie-jacobs-disgusted-bs-unacceptable-play: Extracting information
ERROR: Unsupported URL: http://www.csnne.com/blog/bruins-talk/charlie-jacobs-disgusted-bs-unacceptable-play
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 858, in _real_extract
    doc = parse_xml(webpage)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\utils.py", line 1531, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1300, in XML    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror    raise err
ParseError: mismatched tag: line 117, column 2
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 275, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 1364, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.csnne.com/blog/bruins-talk/charlie-jacobs-disgusted-bs-unacceptable-play

Thanks
Ringo

**Comment by RingoTheDog** [comment]
Not sure if these can be added to (or a generic?):
[Yahoo/NBCSports] Fix 5226 and add support for NBC sports #5328

but it seems NBC Sports has number of regional sports channels, in addition to the original post csne.com.  

Here is the list :  http://www.comcastsportsnet.com/  
(NOTE: the NY channel seems different from the rest)

Example URLS.
http://www.csnbaltimore.com/blog/orioles-talk/orioles-lose-fifth-straight-mccullers-dominates
http://www.csnchicago.com/blackhawks/hulk-hogan-believes-blackhawks-are-lot-trouble
http://www.csnbayarea.com/warriors/who-has-edge-nba-finals-warriors-or-cavs
http://www.csncalifornia.com/warriors/who-has-edge-nba-finals-warriors-or-cavs
http://www.csnchicago.com/blackhawks/hulk-hogan-believes-blackhawks-are-lot-trouble
http://www.csnnw.com/blazers/nba-scouts-take-montrezl-harrell-and-christian-wood
http://www.csnphilly.com/football-philadelphia-eagles/scheme-change-byron-maxwell-could-match-no-1-wrs
http://www.csnwashington.com/baseball-washington-nationals/talk/buehrle-pitches-complete-game-shutout-downs-nationals-8-0



Thanks..and amazing work as always!
Ringo

**Comment by remitamine** [comment]
all URLs redirect now to NBC Sports website.
