### ISSUE TITLE
move docs to github wiki

### ISSUE THREAD

**Issue by Adeor** [ytdl-org/youtube-dl#5466]
hi,

would it be possible to move/copy the documentation to the GitHub Wiki?
I think it would be much clearer and easier to navigate (at least for me).

If you want I would gladly port it for you.

**Comment by yan12125** [comment]
By default Github Wikis allow everyone to edit, just like Wikipedia. I'm afraid that it will be bloated with wrong/inproper information. There are some alternatives:

1. Add a section in yt-dl.org and/or rg3.github.com/youtube-dl and sync contents of ```docs/```. I guess pandoc can transform Markdown to HTML, too.
2. [Restrict Wikis to collaborators](https://help.github.com/articles/changing-access-permissions-for-wikis/). An advantage of this approach is that Github provides a [Wiki repository](https://help.github.com/articles/adding-and-editing-wiki-pages-locally/), so the Markdown -> HTML conversion is done by Github.

In both approaches we need to sync changes back manually if files under ```docs/``` are modified. [Github webhooks](https://developer.github.com/v3/repos/hooks/#receiving-webhooks) provides a seemingly simple synching mechanism.

**Comment by rg3** [comment]
Sorry for being late to the party. I was just now browsing issues I'm "participating" on and I noticed #11234. If the team agrees I should change the project settings just mail me and I'll do.

**Comment by siddht4** [comment]
@rg3 thank you for your positive response on  wiki.
@yan12125 only the collaborators can change the wiki. We can post/comment  things like what to add,what to change,etc.(I have tried it myself pr doesnt work).

**Comment by Adeor** [comment]
duplicate, not completed.

**Comment by Adeor** [comment]
.

**Comment by Adeor** [comment]
.
