### ISSUE TITLE
Auto Batch Mode? 

### ISSUE THREAD

**Issue by w524e** [ytdl-org/youtube-dl#557]
Remove the link from a text file assigned by `--batch-file` (or move to a backup file) when a file completed, and automatically resume the list for incomplete download when the last line of the text is done (instead of quitting, process the batch file again--sorry for my poor english), until the list is empty or no more .part file in the current directory. It would be useful for interrupted batch download due to wifi problem or other reasons. Now i'm using sed with some Windows batch code to do this, but it's a bit troublesome. it would be nice if youtube-dl can do this. thanks

**Comment by dirkf** [comment]
Nowadays, `--download-archive ...`.
