### ISSUE TITLE
Wrong error message for yt videos that are both age-gated and private 

### ISSUE THREAD

**Issue by pps** [ytdl-org/youtube-dl#5617]
Getting this error when trying to download this video: https://youtu.be/N-aDHKKRdso

```
[youtube] N-aDHKKRdso: Downloading webpage
[youtube] N-aDHKKRdso: Downloading embed webpage
[youtube] N-aDHKKRdso: Refetching age-gated info webpage
ERROR: N-aDHKKRdso: YouTube said: Please sign in to view this video.
```

Better error message would have been "this video is private".

**Comment by jaimeMF** [comment]
Note, that we are using the message from https://www.youtube.com/embed/N-aDHKKRdso instead of the one in https://www.youtube.com/watch?v=N-aDHKKRdso, because we fallback to the embed page.

**Comment by nathany** [comment]
I saw the age-gated error for this private video https://www.youtube.com/watch?v=YaKQDJgF6pw until I specified login information, after which it said it is private.

Is there a way to skip over private videos in a playlist? youtube-dl reached this video while downloading: https://www.youtube.com/playlist?list=PLDWZ5uzn69eyh791ZTkEA9OaTxVpGY8_g

I've also asked the uploader to address the private video contained in the playlist: https://twitter.com/nathany/status/776495956946587648

**Comment by dstftw** [comment]
@nathany `-i`.

**Comment by tommcintyre** [comment]
I had been having this problem for a while, but it turned out that clearing cookies and logging in again fixed it.
