### ISSUE TITLE
site support request: gyao.yahoo.co.jp

### ISSUE THREAD

**Issue by KornnBread** [ytdl-org/youtube-dl#5811]
Please add support for gyao.yahoo.co.jp as well as streaming.yahoo.co.jp.
Thank you.

**Comment by yan12125** [comment]
Can you post some example URLs?

**Comment by KornnBread** [comment]
Here is main show page link http://streaming.yahoo.co.jp/p/y/00189/v04459/
link to video I am trying to save is http://streaming.yahoo.co.jp/c/y/00189/v04459/v1000000000000001646/
The video is region locked to japan and is also behind a pay wall. It uses hls for streaming but when trying to save the video it give 403 Client Error: Forbidden

**Comment by yan12125** [comment]
Can you paste the [full verbose log](https://github.com/rg3/youtube-dl#bugs)? It may help us on solving the 403 error.

**Comment by KornnBread** [comment]
I apologize as I realized that I am mixing up two separate video downloading tools hosted on github. The error I mentioned above I received using livestreamer but I did get a 401 error using youtube-dl and here is a copy of the -v output
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--no-check-certificate', u'--force-ipv4', u'--hls-prefer-native', u'--list-formats', u'https://gw.gyao.yahoo.co.jp/v1/auth_hls/00189:v04459:v1000000000000001646/variant.m3u8?device_type=1100&delivery_type=2&min_bandwidth=246&appkey=52hd8q-XnozawaXc727tmojaFD.SD1yc&appid=ff_rbJCxg67.bRk_lk7CbWFjhorGVKjvFsRgiLDHW4PE.vN6zxDW6KyRr1Zw3rI-', u'-o', u'02.ts', u'-v']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.9 - Linux-2.6.32-042stab106.4-i686-with-debian-7.5
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] variant.m3u8?device_type=1100&delivery_type=2&min_bandwidth=246&appkey=52hd8q-XnozawaXc727tmojaFD.SD1yc&appid=ff_rbJCxg67.bRk_lk7CbWFjhorGVKjvFsRgiLDHW4PE: Requesting header
WARNING: Could not send HEAD request to https://gw.gyao.yahoo.co.jp/v1/auth_hls/00189:v04459:v1000000000000001646/variant.m3u8?device_type=1100&delivery_type=2&min_bandwidth=246&appkey=52hd8q-XnozawaXc727tmojaFD.SD1yc&appid=ff_rbJCxg67.bRk_lk7CbWFjhorGVKjvFsRgiLDHW4PE.vN6zxDW6KyRr1Zw3rI-: HTTP Error 401: Unauthorized
[generic] variant.m3u8?device_type=1100&delivery_type=2&min_bandwidth=246&appkey=52hd8q-XnozawaXc727tmojaFD.SD1yc&appid=ff_rbJCxg67.bRk_lk7CbWFjhorGVKjvFsRgiLDHW4PE: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1712, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
