### ISSUE TITLE
rtve.es:alacarta - error downloading

### ISSUE THREAD

**Issue by rtveuser** [ytdl-org/youtube-dl#5831]
First of all, thanks for your incredible work.

The problem seems to have started 4-5 day ago. Here is a sample report, obtained with the last yt-dl version available to date:

youtube-dl --verbose http://www.rtve.es/alacarta/videos/brain-games/brain-games-leyes-atraccion/3139808/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.rtve.es/alacarta/videos/brain-games/brain-gam
es-leyes-atraccion/3139808/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-72298-g02cf59f, ffprobe N-72298-g02cf59f, rtmpdump 2.4
[debug] Proxy map: {}
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] 3139808: Downloading JSON metadata
[rtve.es:alacarta] 3139808: Downloading url information
[rtve.es:alacarta] 3139808: Getting video url
ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

  File "youtube_dl\extractor\common.pyo", line 312, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1712, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default

---

**Comment by dstftw** [comment]
Can you watch it in browser?

**Comment by rtveuser** [comment]
Yes, I can both watch it and download it with the url provided by the "download helper" Firefox addon.

**Comment by felisucoibi** [comment]
this bug can be closed i think
