### ISSUE TITLE
Support steam videos (was: Downloading videos from manually specified DASH manifests)

### ISSUE THREAD

**Issue by ChlorideCull** [ytdl-org/youtube-dl#6012]
I would love if a function like this was exposed. I would be happy to implement it myself if I get some pointers for where to implement it. I would assume it would be something like splitting out [_parse_dash_manifest](https://github.com/rg3/youtube-dl/blob/02175a7986c4223a0ed27a872c1ca16926913e05/youtube_dl/extractor/youtube.py#L782) from `youtube.py` and making it prettier/more compliant, and adding another extractor for raw manifests?

**Comment by jaimeMF** [comment]
Could you explain [why you need it and post an example url](https://github.com/rg3/youtube-dl/blob/a69e8bfdd9e94537eb72a358c1b62dbea8a59a04/README.md#bugs)?

**Comment by ChlorideCull** [comment]
For general downloading of DASH video, where the process of getting the manifest is too complicated to automate, for example when you need to solve a captcha to access it. An example would be streaming video from Steam, where you need to be using the Steam client to access the manifest itself.

**Comment by jaimeMF** [comment]
[post an example url](https://github.com/rg3/youtube-dl/blob/a69e8bfdd9e94537eb72a358c1b62dbea8a59a04/README.md#bugs).
Note that if it's only for steam broadcasts, it may actually be better to just add an specific extractor.

**Comment by ChlorideCull** [comment]
I could work on adding the extractor then, I'm working on splitting out the _parse_dash_manifest from `youtube.py` and putting it in `common.py`, as well as making sure it can handle the spec.

As for example URLs, you have the [Steam launch URL](steam://run/373020) and the [Manifest retrieval API page](http://store.steampowered.com/video/details/373020) which requires your User-Agent to be set as `Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; Valve Steam Client/[10 CHARACTERS SPECIFYING VERSION]; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36`, as well as being logged in to the store front.

As for the DASH manifest you get, it looks something like [this](http://hastebin.com/cakinuluni.xml) (scrubbed for privacy, horrible formatting not mine).

**Comment by yan12125** [comment]
It's an innovative idea, while I think implementing a new extractor is more meaningful and friendly than providing an interface for putting DASH manifests. As a result, I mark this ticket as a 'site-support-request' rather than a 'request'.

And FYI, the example DASH manifest above seems to use segments. There's a relevant work at #5886. I implement DASH segments downloading. However, it's for youtube, which does not conforms to the standard.

**Comment by jaimeMF** [comment]
As with youtube the audio and video seem to be in two different streams, which makes it quite hard to implement it for live streams (we don't currently support downloading two files at the same time).

**Comment by ChlorideCull** [comment]
Frankly, I wasn't planning on implementing it for live streams, as I just want it to be able to ditch the stupid Steam player (which tends to break).

**Comment by jaimeMF** [comment]
Could you post a url that is not a live stream?

**Comment by fijam** [comment]
Is there an update on this feature? An example of a steam streaming video: http://store.steampowered.com/app/245550/ 
The steam player launches from http://store.steampowered.com/video/details/245550/ (requires passing a User Agent check and an auth cookie)

**Comment by jaimeMF** [comment]
@fijam that's tracked in other issue: #7740.

**Comment by mpenkov** [comment]
@ChlorideCull Could you please post a URL that is not a live stream?

**Comment by Echtze1t** [comment]
Not sure which of these is the actual video, found these in the source:

https://store.steampowered.com/63702f14-cd00-4e16-9c2e-8a244ca3403f
https://steamvideo-a.akamaihd.net/video/1909223162761573863/thumbnail/53664/0/

The link to the product page is this:

https://store.steampowered.com/app/970070/Fechtbuch_The_Real_Swordfighting_behind_Kingdom_Come/

**Comment by SpectralCascade** [comment]
Bump - would like to see support for individual videos on Steam, e.g. this one of Steam dev days 2016 https://store.steampowered.com/video/watch/550760/

(this is the first video listed for the 2016 Steam dev days, accessed via the store page https://store.steampowered.com/app/534600/Steam_Dev_Days/)

**Comment by dirkf** [comment]
Please open a new site support request for any specific site (according to #30839).

This issue is very much outdated and the discussion here is probably obsolete.
