### ISSUE TITLE
RTVE.es Dowload "broken" - M3U playlist saved as MP4

### ISSUE THREAD

**Issue by jjarava** [ytdl-org/youtube-dl#6073]
Hi!

Trying to download a video from RTVE.es (from a series I've previously downloaded fine) using the latest version (2015.06.15)... the download seems to work, but the output is a 312 bytes file (!) that `file` identifies as:

```
jjarava$ file "Águila Roja - T7- Capítulo 88-3151116.mp4"
Águila Roja - T7- Capítulo 88-3151116.mp4: M3U playlist text
```

The full debug output is:

``` python
jjarava$ youtube-dl -v http://www.rtve.es/alacarta/videos/aguila-roja/aguila-roja-t7-capitulo-88/3151116/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.rtve.es/alacarta/videos/aguila-roja/aguila-roja-t7-capitulo-88/3151116/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.3-tessus
[debug] Proxy map: {}
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] 3151116: Downloading JSON metadata
[rtve.es:alacarta] 3151116: Downloading url information
[rtve.es:alacarta] 3151116: Getting video url
[debug] Invoking downloader on u'http://mvod1.akcdn.rtve.es/resources/TE_NGVA/mp4/2/3/1433187668632.mp4?primaryToken=1435177165_37ec06869264f04807a6e209524d0bbd'
[download] Destination: Águila Roja - T7- Capítulo 88-3151116.mp4
[download] 100% of 312.00B in 00:00
```

Thanks!

**Comment by dstftw** [comment]
Run it with `--verbose --write-pages` and post here the log, *.dump files and the downloaded file.

**Comment by jaimeMF** [comment]
The video can't be played on iOS, it gets a few `403` erors when trying to download the sub manifests, the full manifest looks like:
```
#EXTM3U
#EXT-X-VERSION:1
## Created with Unified Streaming Platform(version=1.7.10)
#EXT-X-STREAM-INF:BANDWIDTH=1684150,CODECS="mp4a.40.2,avc1.100.41",RESOLUTION=1024x576
1433187668632-audio_eng=63821-video_eng=1525000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=67650,CODECS="mp4a.40.2"
1433187668632-audio_eng=63821.m3u8
```

**Comment by jjarava** [comment]
Hi!

Just updated to the latest version (2015.06.25) and the result is the same:

```python
jjarava$ youtube-dl -v http://www.rtve.es/alacarta/videos/aguila-roja/aguila-roja-t7-capitulo-88/3151116/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.rtve.es/alacarta/videos/aguila-roja/aguila-roja-t7-capitulo-88/3151116/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.25
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.3-tessus
[debug] Proxy map: {}
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] 3151116: Downloading JSON metadata
[rtve.es:alacarta] 3151116: Downloading url information
[rtve.es:alacarta] 3151116: Getting video url
[debug] Invoking downloader on u'http://mvod1.akcdn.rtve.es/resources/TE_NGVA/mp4/2/3/1433187668632.mp4?primaryToken=1435223518_6dba1c5c4edfe5192476c3566298f2ba'
[download] Destination: Águila Roja - T7- Capítulo 88-3151116.mp4
[download] 100% of 312.00B in 00:00
```
What is more odd, when running with `--write-pages` as requested in https://github.com/rg3/youtube-dl/issues/6073#issuecomment-115002300, the file **actually** starts downloading!!:

```python
jjarava$ youtube-dl -v --write-pages http://www.rtve.es/alacarta/videos/aguila-roja/aguila-roja-t7-capitulo-88/3151116/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--write-pages', u'http://www.rtve.es/alacarta/videos/aguila-roja/aguila-roja-t7-capitulo-88/3151116/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.25
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.3-tessus
[debug] Proxy map: {}
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] Saving request to None_http_-_www.rtve.es_odin_loki_TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjoxMC4wKSBHZWNrby8yMDE1MDEwMSBGaXJlZm94LzIwLjAgKENocm9tZSk=.dump
[rtve.es:alacarta] 3151116: Downloading JSON metadata
[rtve.es:alacarta] Saving request to 3151116_http_-_www.rtve.es_api_videos_3151116_config_alacarta_videos.json.dump
[rtve.es:alacarta] 3151116: Downloading url information
[rtve.es:alacarta] Saving request to 3151116_http_-_www.rtve.es_ztnr_movil_thumbnail_banebdyede_videos_3151116.png.dump
[rtve.es:alacarta] 3151116: Getting video url
[rtve.es:alacarta] Saving request to 3151116_http_-_flash1.akamaihd.multimedia.cdn.rtve.es_auth_resources_TE_NGVA_mp4_2_3_1433187668632.mp4.dump
[debug] Invoking downloader on u'http://mvod1.akcdn.rtve.es/resources/TE_NGVA/mp4/2/3/1433187668632.mp4?primaryToken=1435223854_8a45b29d6fb74a922030aaefc5daf2e6'
[download] Destination: Águila Roja - T7- Capítulo 88-3151116.mp4
[download]   1.4% of 1.01GiB at 339.16KiB/s ETA 51:24
```

I'm letting it run and will update when the process finishes to see if I really get the proper file downloaded, but as it's going to take a while (the speed has gone down) in the meantime I'm attaching here the files as requested

**Comment by jaimeMF** [comment]
Yes, sometimes I also get the real mp4 video file (you can play it while downloading with mpv or mplayer). But I would doubt it's actually a 1.01GiB file since for others video we have to [modify the url](https://github.com/rg3/youtube-dl/blob/381c06775598da9667548fcc45d5df7a03748f7d/youtube_dl/extractor/rtve.py#L113-L116) because they are reported as 2GiB files (which is completely wrong).

**Comment by jjarava** [comment]
I wouldn't be too surprised to find its a 1 GB file - the episode is about 1 hour long and others from the series have been more or less that size. 

I'll report the final size when I can complete the download (I've had to interrupt it). BTW - once interrupted I've tried to run the *same* command again but instead of resuming as has happened other times, I got a message that the destination had already been downloaded. Deleting the file and .dmp has allowed it to run again 

Anyhow I'll update when the process finishes.

**Comment by jjarava** [comment]
The download finished and instead of the 312 bytes file I have a real MP4 that looks to be "the real thing"

To add more surprise to the mix, I've tried downloading other chapters from the same series from the same server:

- http://www.rtve.es/alacarta/videos/aguila-roja/aguila-roja-7-capitulo-89/3163193/
- http://www.rtve.es/alacarta/videos/aguila-roja/aguila-roja-t7-capitulo-90/3170418/

and both download fine!
And to make it even more strange, I've tried downloading the "*offending*" chapter again and the download seems to be working fine...

Strange things..

**Comment by jaimeMF** [comment]
Well, I'm getting the m3u8 file again. I would consider it a bug on their side.

**Comment by felisucoibi** [comment]
this bug can be closed i think
