### ISSUE TITLE
Return list of videos or call FD.download in playlist IEs

### ISSUE THREAD

**Issue by FiloSottile** [ytdl-org/youtube-dl#608]
@phihag I can't make my mind on this. (We can also have a IRC chat if you want).

Here's the problem: ATM at the end of `YoutubePlaylistIE` we call FD.download on the found ids. This is a pretty practical solution. However, I think we should consider returning a list instead.

Here's the comparison.

Pro `FD.download`:
- The info extraction of each video happens just before the download. This is a fondamental point.
- It works well for URL shortener recognizing.

Pro `return list`:
- It gives control over how many videos are being downloaded, avoiding call cascades. Try `ytdl -o xxx PL63F0C78739B09958`, this is a bug, and it is not easily and elegantly solvable ATM.
- It is step towards APIfication, we really need to stop using the downloader object in the IEs. I am cleaning all those `self._downloader` but this is a blocking issue.

A compromise might be to return two lists, one of info_dicts, one of links to add to the download queue.

**Comment by dirkf** [comment]
That's how it is.
