### ISSUE TITLE
Really long streams incomplete

### ISSUE THREAD

**Issue by mjevans** [ytdl-org/youtube-dl#6089]
Some examples (the two longer segments) were created during the recent Zeldathon.

http://www.twitch.tv/supermcgamer/profile/past_broadcasts

The smaller of the two test cases is listed first:

http://www.twitch.tv/supermcgamer/v/6381583
http://www.twitch.tv/supermcgamer/v/6443616

```
[mp4 @ 0x7ff60ce5fcc0] Non-monotonous DTS in output stream 0:0; previous: 8588246946, current: 2542752867; changing to 8588246947. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7ff60ce5fcc0] Non-monotonous DTS in output stream 0:0; previous: 8588246947, current: 2542755837; changing to 8588246948. This may result in incorrect timestamps in the output file.
```

Using the hlsnative option (and an mkv container just because) also results in an error, however it isn't repeatable...

```
[hlsnative] v6443616: Downloading segment 33482 / 55249
[hlsnative] v6443616: Downloading segment 33483 / 55249
ERROR: unable to download video data: IncompleteRead(173289 bytes read, 611423 more expected)


[hlsnative] v6443616: Downloading segment 44796 / 55249
ERROR: unable to download video data: IncompleteRead(254376 bytes read, 533908 more expected)
```

It looks like hlsnative might need to retry segments up to N times (maybe 5 with increasing backoff?), if that's even possible?

**Comment by AshenDrops** [comment]
Have you tried using an external downloader with the `--external-downloader` flag? It supports curl, wget, and aria2c and this issue seems to be a downloading issue. Aria2 is the most robust of the three so it might work rather well.
