### ISSUE TITLE
[arte] Add support for arte concert

### ISSUE THREAD

**Issue by clampak** [ytdl-org/youtube-dl#6127]
I thought there was support for arte.tv, but I can't download from there.

```
$ youtube-dl -v http://www.arte.tv/sites/de/festivals/africa-festival-2015/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.arte.tv/sites/de/festivals/africa-festival-2015/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.25
[debug] Python version 2.7.10 - CYGWIN_NT-5.1-2.0.4-0.287-5-3-i686-32bit
[debug] exe versions: ffmpeg N-72211-g451be67, ffprobe N-72211-g451be67, rtmpdump 2.4
[debug] Proxy map: {}
[generic] africa-festival-2015: Requesting header
WARNING: Falling back on generic information extractor.
[generic] africa-festival-2015: Downloading webpage
[generic] africa-festival-2015: Extracting information
ERROR: Unsupported URL: http://www.arte.tv/sites/de/festivals/africa-festival-2015/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1070, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/lib/python2.7/site-packages/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: junk after document element: line 3, column 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1636, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.arte.tv/sites/de/festivals/africa-festival-2015/
```

**Comment by cyhojoey** [comment]
Hi  clampak,

Try this:
youtube-dl -v http://concert.arte.tv/fr/oum-au-africa-festival-2015

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://concert.arte.tv/fr/oum-au-africa-festival-2015']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2015.11.24
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
[arte.tv:concert] oum-au-africa-festival-2015: Downloading webpage
[arte.tv:concert] oum-au-africa-festival-2015: Downloading JSON metadata
[arte.tv:concert] oum-au-africa-festival-2015: Checking HTTP_EQ_1 video format URL
[arte.tv:concert] oum-au-africa-festival-2015: Checking HTTP_HQ_1 video format URL
[arte.tv:concert] oum-au-africa-festival-2015: Checking HTTP_MQ_1 video format URL
[arte.tv:concert] oum-au-africa-festival-2015: Checking HTTP_SQ_1 video format URL
[arte.tv:concert] oum-au-africa-festival-2015: Checking HLS_XQ_1 video format URL
[arte.tv:concert] oum-au-africa-festival-2015: Checking HLS_SQ_1 video format URL
[debug] Invoking downloader on u'http://arteconcert.gl-systemhaus.de/am/concert/060000/060900/060998-001-B_SQ_0_VO_01893106_MP4-2200_AMM-ALW.mp4'
[download] Destination: Oum au Africa Festival 2015-060998-001-A.mp4
