### ISSUE TITLE
Promptfile not all formats available

### ISSUE THREAD

**Issue by WeWin55** [ytdl-org/youtube-dl#6239]
If I try to download a Video from Promptfile, the option -F gives me only "sd" with 703.55MiB, but on the website the file is 1.62 GB and if I downlod it in the browser the file is also 1.62 GB. 
Does someone know a fix?

**Comment by jaimeMF** [comment]
Post the [full output you get with the --verbose option](https://github.com/rg3/youtube-dl/blob/b062d94eefcc9327af5e60f3280cedaff9e40ac8/README.md#bugs)

**Comment by WeWin55** [comment]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'--verbose', u'http://www.promptfile.com/l/AA3B278789-1E80A5AD27']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.3 - Linux-3.18.11-v7+-armv7l-with-debian-7.8
[debug] exe versions: avconv 9.14-6, avprobe 9.14-6
[debug] Proxy map: {}
[PromptFile] AA3B278789-1E80A5AD27: Downloading webpage
[PromptFile] AA3B278789-1E80A5AD27: Downloading video page
[info] Available formats for AA3B278789-1E80A5AD27:
format code  extension  resolution note
sd           mkv        unknown
