### ISSUE TITLE
Add support for spherical ("360 degrees") videos

### ISSUE THREAD

**Issue by fstirlitz** [ytdl-org/youtube-dl#6246]
Example: https://youtu.be/S3xOB-Bigc8

The video downloads fine, but it's treated like a planar (flat) video; the resulting file doesn't contain any metadata indicating it's a spherical video, and none are made available through the `-j` option.

There probably isn't that much for youtube-dl to do here: detecting spherical videos, collecting metadata, putting them into `info_dict`, and perhaps doing some fixups in a post-processor.

Google has a draft specification for spherical video metadata, which may or may not be helpful: https://github.com/google/spatial-media/blob/master/docs/spherical-video-rfc.md

**Comment by jaimeMF** [comment]
Apart from the webpage having the tags `360` or `spherical`(which I guess can be manually added for every video), I haven't found anywhere where it says it is a spherical video. How do you think youtube-dl can detect them?

**Comment by fstirlitz** [comment]
Here's a (prettified) fragment of `html5player.js` which seems responsible for detecting it:
```js
    DH.j = function(a) {
        var b = a.X().A.c.toLowerCase(), c;
        c = a.getVideoData();
        a = a.X().experiments;
        if (a.Fa && hz(c) && 3 != c.ga && 4 != c.ga)
            b = "Anaglyph3D";
        else {
            a: {
                if (c.j)
                    for (var d in c.j.j) {
                        var e = c.j.j[d].info.video;
                        if (e && 2 == e.projectionType) {
                            c = true;
                            break a
                        }
                    }
                c = false
            }
            b = c ? "Spherical" : a.$ && vj && "web" == b ? "NoOp" : a.Ha && vj && "web" == b ? "WhiteNoise" : a.P && vj && "web" == b ? "EdgeEnhance" : null
        }
        return b
    };
```

There's a `yt:projectionType` attribute in the DASH manifest, and `projection_type` key buried in the video metadata. The video is fully viewable in Chromium.

**Comment by neuman** [comment]
Any progress on this issue?

**Comment by themegabyte** [comment]
What is the update on this issue guys

**Comment by dj-fiorex** [comment]
Any updates guys?
