### ISSUE TITLE
Add support for Player.pl (TVN)

### ISSUE THREAD

**Issue by marsjaninzmarsa** [ytdl-org/youtube-dl#6396]
For example this video: http://player.pl/programy-online/kuba-wojewodzki-odcinki,455/odcinek-178,ewelina-lisowska-marcin-spenner-dawid-podsiadlo-i-robert-friedrich,S00E178,13204.html

Downloading is possible, for example via this bookmarklets: http://miniskrypt.blogspot.com/2012/12/tvnplayer-downloader-wersja-20.html

I can try to add it, but I don't promise anything. :wink: 

Important note: due to text linked above, extracting of video URL may be restricted to Poland, but downloading video should work worldwide. Also - extracted video URL is valid only up to an hour, so I don't know how to pass unit tests (cause I can't just hardcode valid video URL in source)... any ideas?

**Comment by jaimeMF** [comment]
>  Also - extracted video URL is valid only up to an hour, so I don't know how to pass unit tests (cause I can't just hardcode valid video URL in source)... any ideas?

You don't need to write the video url, [read the introduction on how to write an exctractor](https://github.com/rg3/youtube-dl/blob/f993afb26d20ac79891621494922887b3c8df02b/README.md#adding-support-for-a-new-site) and some simple extractor like [InstagramIE](https://github.com/rg3/youtube-dl/blob/f993afb26d20ac79891621494922887b3c8df02b/youtube_dl/extractor/instagram.py#L12-L43).

**Comment by marsjaninzmarsa** [comment]
Or I can provide regex for test, right, thanks!

Also, you have one of the best guides for new contributors I've ever seen, my pull request should be ready today. :)
