### ISSUE TITLE
YouTube annotations support

### ISSUE THREAD

**Issue by paulguy** [ytdl-org/youtube-dl#6531]
I was wondering how possible it'd be to integrate youtube annotations support in to youtube-dl.  I know it would be a big undertaking but I have done a good bit of the work.  I don't really know how to integrate it with youtube-dl myself and it has some problems that maybe someone more experienced at python or programming or youtube or whatever else might be able to get stuff going and get it in to youtube-dl.

Here's my code: https://github.com/paulguy/minitools/blob/master/ytanno2ass.py

The README in that repository gives a bit more information on the limitations and problems with it.

**Comment by yan12125** [comment]
I've tried ytanno2ass.py against https://www.youtube.com/watch?v=C5zzVemi3m4, and it gives the following error:
```
$ python2 ytanno2ass.py 
Traceback (most recent call last):
  File "ytanno2ass.py", line 337, in <module>
    annos = XMLElementToAnnotationsList(root, 1920, 1080)
  File "ytanno2ass.py", line 268, in XMLElementToAnnotationsList
    raise Exception("Unsupported type")
Exception: Unsupported type
```

The [developer instructions](https://github.com/rg3/youtube-dl#developer-instructions) may be helpful if you're going to work on this feature. Note that we require all codes compatible with python 2.6, 2.7, 3.2, 3.4.

**Comment by paulguy** [comment]
I worked on it a bit more and fixed that and a few other unrelated bugs, though text wrapping is still totally broken.  I didn't add support for those missing annotation types since they involve images and the ASS renderer has no way of inserting raster graphics that I know of.  I don't plan to work on maintaining this full-time, sorry.  It was just a fun little project for me and figured maybe someone more experienced could integrate it once the implementation was more or less done..

**Comment by yan12125** [comment]
Would you like to release ```ytanno2ass.py``` into [public domain](https://en.wikipedia.org/wiki/Public_domain)? This allows others to work on your codes and integrate into youtube-dl without legal issues. Note you should be the original author of those codes to claim public domain release.

Tkinter is not a big issue as it's a python builtin module.

**Comment by paulguy** [comment]
Well, I'd need to rewrite the word wrapping function, I guess.  How would one go about releasing code public domain?
Also the issue with Tkinter is not so much that it's built in or not but the fact that it needs to be able to create a window before it can query anything font related.

**Comment by yan12125** [comment]
> How would one go about releasing code public domain?

A common approach is to add some comments in the file. Here's an example: [pyelftools](https://github.com/eliben/pyelftools/blob/master/elftools/__init__.py)

**Comment by paulguy** [comment]
Rewrote the word wrap function so all the code is written by me and made it public domain.

**Comment by TRox1972** [comment]
As of now, isn't annotations supported? Should this be closed?

**Comment by paulguy** [comment]
It supports converting subtitles to SRT and can write out the annotations XML, but it as far as I can tell, looking over the command line options, it can't output annotations in a way a media player can use them.

**Comment by brandongalbraith** [comment]
[YouTube will delete existing video annotations on January 15, 2019](https://support.google.com/youtube/answer/73427370). This would imply Youtube annotation support can be deprecated after that date.

**Comment by ealgase** [comment]
> [YouTube will delete existing video annotations on January 15, 2019](https://support.google.com/youtube/answer/7342737). This would imply Youtube annotation support can be deprecated after that date.

Invidious may decide to implement annotations and serve backed up annotations themselves.

**Comment by omarroth** [comment]
See omarroth/invidious#303 and the announcement [here](https://www.reddit.com/r/DataHoarder/comments/al7exa/youtube_annotation_archive_update_and_preview/). There's currently a temporary API for serving up what's been archived until everything has been uploaded to archive.org.

[This](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1467) endpoint now returns an empty response for old videos.

**Comment by omarroth** [comment]
See also #19069. Pulling annotations from a different source is considered (understandably) out-of-scope for this project.

**Comment by glmdgrielson** [comment]
Oh hey, my PR!

**Comment by upintheairsheep** [comment]
Close this. It’s a removed feature.
