### ISSUE TITLE
CSN Philly Sport Site: Unsupported Video

### ISSUE THREAD

**Issue by aaronvegh** [ytdl-org/youtube-dl#6656]
$ youtube-dl --version
2015.08.23

Unsupported URL:
http://www.csnphilly.com/video_content_type/morning-buzz-chase-4-ever

**Comment by RingoTheDog** [comment]
FWIW...part of comcast/NBC sports:
https://github.com/rg3/youtube-dl/issues/5432

**Comment by remitamine** [comment]
redirects to NBC Sports website.
