### ISSUE TITLE
Cant download private videos on pornhub that i have access to

### ISSUE THREAD

**Issue by boddcoward** [ytdl-org/youtube-dl#6776]
Tried to download a private video on pornhub using the username and password feature, but i still got the "this video is private" error. does the username and password function only apply to Youtube?

C:\Windows\System32>C:\Users\beb\Downloads\youtube-dl.exe -v --username thisisntmyusername --password donteventry http://www.pornhub.com/view_video.php?viewk
ey=ph55b5c001154ed
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--username', u'PRIVATE', u'--password', u'P
RIVATE', u'http://www.pornhub.com/view_video.php?viewkey=ph55b5c001154ed']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.08.28
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[PornHub] ph55b5c001154ed: Downloading webpage
ERROR: ph55b5c001154ed: PornHub said: Sorry, but this video is private. You must
 be friends with jorgerdz to view this video.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 655, in extract_info
  File "youtube_dl\extractor\common.pyo", line 287, in extract
  File "youtube_dl\extractor\pornhub.pyo", line 65, in _real_extract
ExtractorError: ph55b5c001154ed: PornHub said: Sorry, but this video is private.
 You must be friends with USER to view this video.

**Comment by dirkf** [comment]
This should be working now. Open a new issue if not.
