### ISSUE TITLE
[dailymotion] Add support for crunchyroll embeds

### ISSUE THREAD

**Issue by l29ah** [ytdl-org/youtube-dl#7093]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-c', u'--verbose', u'http://www.dailymotion.com/video/xfh9zx_pale-cocoon-episode-1-ova-1_shortfilms']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.06.2
[debug] Python version 2.7.10 - Linux-4.1.5-grsec+-x86_64-Intel-R-_Core-TM-_i7_CPU_L_620_@_2.00GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] xfh9zx: Downloading webpage
WARNING: unable to extract OpenGraph description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[dailymotion] xfh9zx: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/dailymotion.py", line 201, in _real_extract
    'video info', flags=re.MULTILINE),
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by liaohaohui** [comment]
I can confirm this
``
python -myoutube_dl -F --verbose http://www.dailymotion.com/video/kZtz0EZ4ndM5Y0dgZg4
``
on Arch Linux as well:
[debug] User config: []
[debug] Command-line args: ['-F', '--verbose', 'http://www.dailymotion.com/video/kZtz0EZ4ndM5Y0dgZg4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.06.2
[debug] Git HEAD: 181f814
[debug] Python version 3.4.3 - Linux-4.1.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.0, ffprobe 2.0, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] kZtz0EZ4ndM5Y0dgZg4: Downloading webpage
[dailymotion] kZtz0EZ4ndM5Y0dgZg4: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by nsilberman** [comment]
same for me

**Comment by nsilberman** [comment]
on dailymotion.py, change the regex to `r'getElementById\(\'player\'\), ({.*?})\);$'`, but still format issues

**Comment by nsilberman** [comment]
https://github.com/rg3/youtube-dl/pull/7107

**Comment by dstftw** [comment]
@liaohaohui @nsilberman your issues are unrelated to the OP issue and will be fixed in th next version.

**Comment by nyh** [comment]
I'm having a similar problem, although I am not sure it is the same one (I have no idea what "crunchyroll embeds" in the bug's title mean):

```
 youtube-dl 'http://www.dailymotion.com/video/x2ldvz9'   
[dailymotion] x2ldvz9: Downloading webpage
[dailymotion] x2ldvz9: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
@nyh you are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by oluc** [comment]
still here (seems the same) :
```
$ youtube-dl http://www.dailymotion.com/video/xhts6c --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.dailymotion.com/video/xhts6c', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.25
[debug] Python version 2.7.10 - Linux-4.2.0-040200rc5-generic-i686-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.6-0ubuntu0.15.10.1, avprobe 2.7.6-0ubuntu0.15.10.1, ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] xhts6c: Downloading webpage
[dailymotion] xhts6c: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 343, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 228, in _real_extract
    'video info', flags=re.MULTILINE),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 646, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
