### ISSUE TITLE
xboxlive download

### ISSUE THREAD

**Issue by jcarlosgarciasegovia** [ytdl-org/youtube-dl#7096]
http://download.xboxlive.com/content/mgs/liveplayer/production/amp/october2015.html

**Comment by jcarlosgarciasegovia** [comment]
This is the list of supported manifests:
http://download.xboxlive.com/content/mgs/liveplayer/production/amp/october2015.json

It seems they are in http://www.iis.net/downloads/microsoft/smooth-streaming and https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP

Is there a way to download a MPEG-DASH directly?

**Comment by yan12125** [comment]
YouTube variant DASH is supported, while generic DASH support requires more work. Microsoft Smooth Streaming Protocol is not implemented yet.

**Comment by yan12125** [comment]
Now generic DASH support is done, but I can't play the example video above in Firefox. Is this video still working? Or do you have another example?

**Comment by remitamine** [comment]
All the manifest in JSON file are not accessible(404 Not Found Error).
