### ISSUE TITLE
Unable to download from Youtube.com

### ISSUE THREAD

**Issue by jmunderwood** [ytdl-org/youtube-dl#7249]
youtube-dl --verbose https://www.youtube.com/watch?v=UVp7MzMPZvQ
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=UVp7MzMPZvQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.06.2
[debug] Python version 2.7.6 - Linux-3.2.34-30-armv7l-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] UVp7MzMPZvQ: Downloading webpage
[youtube] UVp7MzMPZvQ: Downloading video info webpage
ERROR: UVp7MzMPZvQ: YouTube said: This video is not available.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1075, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: UVp7MzMPZvQ: YouTube said: This video is not available.

**Comment by dstftw** [comment]
Can you watch it in browser?

**Comment by jmunderwood** [comment]
Yes, I tried a couple of videos and got the same error.  Both videos were playable in Google Chrome on my MacBook Pro.

**Comment by dstftw** [comment]
Can you also watch it in browser when not logged in to your google account?

**Comment by jmunderwood** [comment]
Yes,

I opened my Safari browser, verified I was not logged into my Google account and could play the videos.

**Comment by error39** [comment]
Experienced the same error on *some* videos, for example this one: https://www.youtube.com/watch?v=HMSqNIL3ckE

**Comment by tone87** [comment]
same error https://github.com/rg3/youtube-dl/issues/7284

**Comment by jmunderwood** [comment]
It appears to be random as some vids download fine and others fail.

**Comment by pricejn2** [comment]
Same issue on my end with latest release 2015.11.02. Here is another example URL -- https://www.youtube.com/watch?v=gqVWglDDyNo

**Comment by pricejn2** [comment]
I was able to workaround this problem by manually specifying an alternate `--source-address`.

**Comment by dstftw** [comment]
This issue is probably fixed in 44b2264feae331eeb34e83eed1387def3d61a437.

**Comment by remitamine** [comment]
works fine the latest version.
