### ISSUE TITLE
[youtube] problem with 'popular uploads' playlist

### ISSUE THREAD

**Issue by PSlash** [ytdl-org/youtube-dl#7388]
It fails to download playlist like: https://www.youtube.com/watch?v=ZeaIvjoH1FY&list=PU5nc_ZtjKW1htCVZVRxlQAQ

> [youtube:playlist] Downloading playlist PU5nc_ZtjKW1htCVZVRxlQAQ - add --no-playlist to just download video ZeaIvjoH1FY
> [youtube:playlist] PU5nc_ZtjKW1htCVZVRxlQAQ: Downloading webpage
> WARNING: [youtube:playlist] Youtube gives an alert message: Unknown error.
> ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug .

It happens because program tries to download playlist directly without video id. And this playlist doesn't exist.

**Comment by jaimeMF** [comment]
You can use `--no-playlist` to only download the video.

**Comment by gaming-hacker** [comment]
if you just want to download the video, why screw around with the playlist?

ywtv ZeaIvjoH1FY

[youtube] ZeaIvjoH1FY: Downloading webpage
[youtube] ZeaIvjoH1FY: Downloading video info webpage
[youtube] ZeaIvjoH1FY: Extracting video information
[youtube] ZeaIvjoH1FY: Downloading js player new-en_US-vfl6mEKMp
[youtube] ZeaIvjoH1FY: Downloading DASH manifest
[youtube] ZeaIvjoH1FY: Downloading thumbnail ...
[youtube] ZeaIvjoH1FY: Writing thumbnail to: /Users/glen/Downloads/youtube/video/Flight_Facilities_-_Crave_You_Adventure_Club_Dubstep_Remix.jpg
[download] Destination: /Users/glen/Downloads/youtube/video/Flight_Facilities_-_Crave_You_Adventure_Club_Dubstep_Remix.f136.mp4
[download] 100% of 8.00MiB in 00:02
[download] Destination: /Users/glen/Downloads/youtube/video/Flight_Facilities_-_Crave_You_Adventure_Club_Dubstep_Remix.f141.m4a
[download]  27.6% of 7.20MiB at  3.97MiB/s ETA 00:01

**Comment by PSlash** [comment]
I know about 'no-playlist' option. And saw the code of youtube.py
I need to download the whole playlist. It's "popular uploads" playlist. Sorted by view count. 
It's similar UU (user uploads). And not accessible by ''https://www.youtube.com/playlist?list=%s'' link.

**Comment by Bandicoot** [comment]
More generally, playlist download from YT is broken for the general case, e.g. download a channel's videos:

youtube-dl --verbose -c 'https://www.youtube.c
om/user/craftinamerica/videos'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-c', u'https://www.youtube.com/user/craftinamerica/videos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[youtube:user] craftinamerica: Downloading channel page
[youtube:playlist] UU61CtV_lOiFRqb6w4GSRm_g: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Bandicoot** [comment]
Download a playlist does work today (after updating my system)  -  it wasn't working yesterday, but here it is working:

bandy@bandy-dell-mint ~/Videos $ youtube-dl -c 'https://www.youtube.com/watch?v=GW0M2zEx-7g&list=RDGW0M2zEx-7g'
[youtube:playlist] Downloading playlist RDGW0M2zEx-7g - add --no-playlist to just download video GW0M2zEx-7g
[youtube:playlist] RDGW0M2zEx-7g: Downloading Youtube mix
[download] Downloading playlist: Mix - Please Warm My Weiner - BO CARTER, Delta Blues Guitar Legend (1934)
[youtube:playlist] playlist Mix - Please Warm My Weiner - BO CARTER, Delta Blues Guitar Legend (1934): Collected 26 video ids (downloading 26 of them)
[download] Downloading video 1 of 26
[youtube] GW0M2zEx-7g: Downloading webpage
[youtube] GW0M2zEx-7g: Downloading video info webpage
[youtube] GW0M2zEx-7g: Extracting video information
[youtube] GW0M2zEx-7g: Downloading js player en_US-vflCIicNM
[youtube] GW0M2zEx-7g: Downloading DASH manifest
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[download] Destination: Please Warm My Weiner - BO CARTER, Delta Blues Guitar Legend (1934)-GW0M2zEx-7g.mp4
[download] 100% of 4.27MiB in 00:00
[download] Downloading video 2 of 26
[youtube] HGVShoAWp00: Downloading webpage
[youtube] HGVShoAWp00: Downloading video info webpage
[youtube] HGVShoAWp00: Extracting video information
[youtube] HGVShoAWp00: Downloading DASH manifest
[youtube] HGVShoAWp00: Downloading DASH manifest
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[download] Destination: What's That Smells Like Fish - BLIND BOY FULLER (1938) Ragtime Blues Guitar Legend-HGVShoAWp00.mp4
[download]  10.1% of 4.96MiB at 596.70KiB/s ETA 00:07^C
ERROR: Interrupted by user

**Comment by dstftw** [comment]
@Bandicoot your issue is unrelated. You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by Bandicoot** [comment]
@dstftw youtube-dl --verbose doesn't report its version number?  I literally just updated my Ubuntu 14.04 system before coming here.

**Comment by dstftw** [comment]
It does.
>[debug] youtube-dl version 2015.11.10

**Comment by Bandicoot** [comment]
D'oh!
