### ISSUE TITLE
[Google Plus] Support embedded youtube videos

### ISSUE THREAD

**Issue by ibennetch** [ytdl-org/youtube-dl#7400]
Using the latest version, 2015.11.02 (tested on Mac and Debian Linux) I can't download video from Google Plus:

<pre>
# youtube-dl --verbose "https://plus.google.com/+SETIInstitute/posts/7wrtC852Gsw"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://plus.google.com/+SETIInstitute/posts/7wrtC852Gsw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.7.2-tessus
[debug] Proxy map: {}
[plus.google] 7wrtC852Gsw: Downloading entry webpage
ERROR: Unable to extract video page URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/bennetch/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/Users/bennetch/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/Users/bennetch/bin/youtube-dl/youtube_dl/extractor/googleplus.py", line 44, in _real_extract
    webpage, 'video page URL')
  File "/Users/bennetch/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video page URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
</pre>

Using a different URL (which I'd rather not share publicly since it's not mine and isn't public), I get 

<pre>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://example.com/not/the/real/url]
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.7.2-tessus
[debug] Proxy map: {}
[plus.google] i1U2Fy7EReP: Downloading entry webpage
WARNING: unable to extract OpenGraph description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/bennetch/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/Users/bennetch/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "/Users/bennetch/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "/Users/bennetch/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1666, in download
  File "/Users/bennetch/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
  File "/Users/bennetch/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
  File "/Users/bennetch/bin/youtube-dl/youtube_dl/extractor/googleplus.py", line 32, in _real_extract
AttributeError: 'NoneType' object has no attribute 'splitlines'
</pre>

I'm not sure if the two are related since they're different error messages but both relate to Google Plus.

**Comment by jaimeMF** [comment]
It's a youtube video that you can download using https://www.youtube.com/watch?v=eieBXGpNYyE. For the second problem, unless you open a new issue with the actual link there's nothing we can do.

**Comment by ibennetch** [comment]
Sorry, I'm a bit lost; did I miss something with the youtube link -- like is the Google Plus post that redirects to Youtube, or did you just happen to find it mirrored on Youtube?

About the second one, could I send you the link privately? I don't mind sharing it, I'd just rather not post publicly without permission (from a poster I'm unlikely to be able to contact).

**Comment by jaimeMF** [comment]
> Sorry, I'm a bit lost; did I miss something with the youtube link -- like is the Google Plus post that redirects to Youtube, or did you just happen to find it mirrored on Youtube?

No, it's an embedded youtube video. I see the link in the post itself:
```
Watch here: http://buff.ly/1NVBGHZ﻿
```
But youtube-dl should probably try to download it. I just gave you the link in case you wanted to download it now.

> About the second one, could I send you the link privately? I don't mind sharing it, I'd just rather not post publicly without permission (from a poster I'm unlikely to be able to contact).

I don't have too much time right now, so I would probably forgot. Maybe other developer can do it.

**Comment by ibennetch** [comment]
Thanks for the quick help! I appreciate it.
