### ISSUE TITLE
Site request: www.snappytv.com

### ISSUE THREAD

**Issue by RingoTheDog** [ytdl-org/youtube-dl#7508]
Snappytv.com is a part of twitter...so this may be more related to some of the twitter posts than an actual site request but here goes:

Example URL: 
http://www.snappytv.com/tc/1019871

Output:
C:>youtube-dl -v http://www.snappytv.com/tc/1019871
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.snappytv.com/tc/1019871']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.13
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[generic] 1019871: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1019871: Downloading webpage
[generic] 1019871: Extracting information
ERROR: Unsupported URL: http://www.snappytv.com/tc/1019871
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1241, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 107, column 39
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\generic.pyo", line 1839, in _real_extract
UnsupportedError: Unsupported URL: http://www.snappytv.com/tc/1019871

Now of possible interest to some, if you increase the item number by one it forwards to the twitter post of that same video:

http://www.snappytv.com/tc/1019872 
forwards to
https://twitter.com/CNNSotu/status/665903663488090112

This video (https://twitter.com/CNNSotu/status/665903663488090112) gives the attributes group error which JamieMF addressed in #7489  (thanks again!)

Here is one more example... 
http://www.snappytv.com/tc/1019841
(just keep changing to the last few numbers and spin the video roulette wheel ;-)

Thanks as always
Ringo

**Comment by remitamine** [comment]
SnappyTV URLs redirect to https://media.twitter.com/en_us/articles/products/2019/snappytv-features-are-now-in-twitter-media-studio.html.
