### ISSUE TITLE
[nowTVList] download-archive & complete serie

### ISSUE THREAD

**Issue by AndroKev** [ytdl-org/youtube-dl#7538]
First thank you for the fix, but i think my code is better ;-) https://github.com/AndroKev/youtube-dl/blob/257abcbd3c6b8a4525592878619912953748b725/youtube_dl/extractor/nowtv.py (but yes yours is beautifuler :-)), because with my code you can download also the complete serie(for example: http://www.nowtv.at/rtl/das-supertalent downloads the hole serie with a nice filename - S9E9_-_Folge_9-233919.flv )

and there is also an bug with the download-archive option:
when you load "http://www.nowtv.at/rtl/das-supertalent/list/staffel-9" then "nowtvlist 233919" is added to the archive file, but when you load the video with the direct-video-link "http://www.nowtv.at/rtl/das-supertalent/list/staffel-9/folge-9-2015-11-14-20-15-00/player" then "nowtv 233919" is added. But that should be the same.

I know that this has something todo with the playlist but with the youtube-playlist-extractor it works also correct...(yt_playlist and youtube-direct-link adds "youtube <video-id>" to the file

**Comment by dstftw** [comment]
For videos I would prefer keeping original titles without any additional decoration.

**Comment by AndroKev** [comment]
https://github.com/AndroKev/youtube-dl/blob/AndroKev-nowtv/youtube_dl/extractor/nowtv.py 

maybe now it is correct?
ps. is there are way to return multiple_playlists? so we can return a plalyist for each season--> each season has it own folder (output-template)

**Comment by dirkf** [comment]
In general, process each season separately using the season URL, if the extractor supports this, with a suitable output template.
