### ISSUE TITLE
Any chance to download videos from Steam?

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#7740]
E.g. steam URL to video looks like this: steam://run/374570 and it launches Steam Video Player while logged in on Steam. Steam doesn't provide download feature and I cannot watch streams offline.

You can test on free video e.g.: http://store.steampowered.com/app/374570/?snr=1_7_7_230_150_1 click the green Watch button. It will require to run Steam on your computer.

Really annoying.

**Comment by HASJ** [comment]
~~Youtube-DL works fine with Steam.~~
Oh I see what you mean. Don't know about that.

**Comment by fijam** [comment]
I managed to play a Steam Streaming Video using a captured MPD manifest and VLC nightly build so it seems feasible to implement an extractor for it.

**Comment by rdcampos6** [comment]
If interest someone I make this video today.
[How to download Steam Videos](https://www.youtube.com/watch?v=em1Y86_88Tc)

**Comment by amaklp** [comment]
@rdcampos6 this only works for videos that you can play from the browser. It won't work in this case for example
http://store.steampowered.com/app/633030/Oats_Studios__Volume_1/
Where you've to click the Watch button and view it through the Steam application.

**Comment by rdcampos6** [comment]
@amaklp but I also could open this video on browser! And you can set in steam -> config -> interface to show URL, copy and paste on browser.

**Comment by amaklp** [comment]
@rdcampos6 How do you play it on the browser? What is the URL? Even from Steam if you click Watch it opens a separate window "Steam Video Player". Are we talking about  the same 22 min video?

**Comment by rdcampos6** [comment]
@amakpl ow sorry I understand now you meaning the "live" content, well I think it's also possible and I'll work in a easy solution for you. Maybe capturing the full URL from video with a tool like wireshark, then trying from a browser download or with a command line tool like ffmpeg. Hope come back soon here with news.

**Comment by amaklp** [comment]
@rdcampos6 Yes that's what I meant! I know for fact that there's a way to get the full video since I saw the untouched version of this on a torrent tracker and it was 5.46 GiB.

The uploader wrote:
> Downloaded from Steam - the package included two files, one with a stereo soundtrack and one with multichannel audio. This is the surround version.

So there's a way to download it but I don't know if it's a known method. I haven't dealt with it very much but I believe that if there's a way to get the video maybe it should remain unknown (or at least now widely known) so that Steam won't patch it :)

Unless it's a very easy method, like using wireshark as you suggested, and Steam doesn't really care about security, then it would be nice to know how to do it ;)

**Comment by rdcampos6** [comment]
@amaklp you're right about some "steam security", I tried the URLSpooner app and finded that are some authenticates and checks for certificates passed bye the steam video player. I'll keep searching...

**Comment by fijam** [comment]
@rdcampos6 Steam uses MPEG-DASH. You can get a link to the MPEG-DASH manifest by forging a request to http://store.steampowered.com/video/watch/XXXXXX/ with Steam authentication cookie and User Agent. Newer releases are protected with CENC so you are out of luck. Please stop spamming this thread unless you can implement it in youtube-dl.

**Comment by 1MALKAVIAN** [comment]
Use the version of steam on Chrome. 
Right click and then save the video.

![image](https://user-images.githubusercontent.com/13656343/58372252-47629b80-7f1b-11e9-92d4-897c5f03e29c.png)
