### ISSUE TITLE
Don't call ffmpeg with -x with video splited

### ISSUE THREAD

**Issue by latot** [ytdl-org/youtube-dl#7744]
Hi all, well here a little thing, some pages like youtube actually split the videos in videa and audio, so in this case youtube-dl shouldn't call ffmpeg.

(-x option) && (page with splited videos) && ((audio format not specified) || (audio format = to the downloaded format)) -> don't call ffmpeg

a logic explanation :D (&& and, || or) 

Thx.

**Comment by jaimeMF** [comment]
That's what it does by default:
```
 youtube-dl --ignore-config -v 'http://www.youtube.com/watch?v=BaW_jenozKcj' -x
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ignore-config', u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj', u'-x']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.27.1
[debug] Git HEAD: 62d231c
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg N-42628-g6662ca2, ffprobe N-42628-g6662ca2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading video info webpage
[youtube] BaW_jenozKc: Extracting video information
[youtube] BaW_jenozKc: Downloading DASH manifest
[youtube] BaW_jenozKc: Downloading DASH manifest
[debug] Invoking downloader on u'...'
[download] youtube-dl test video ''_ä↭𝕐-BaW_jenozKc.m4a has already been downloaded
[download] 100% of 310.24KiB
[ffmpeg] Correcting container in "youtube-dl test video ''_ä↭𝕐-BaW_jenozKc.m4a"
[debug] ffmpeg command line: avconv -y -i 'file:youtube-dl test video '"'"''"'"'_ä↭𝕐-BaW_jenozKc.m4a' -c copy -f mp4 'file:youtube-dl test video '"'"''"'"'_ä↭𝕐-BaW_jenozKc.temp.m4a'
[debug] avconv command line: avprobe -show_streams 'file:youtube-dl test video '"'"''"'"'_ä↭𝕐-BaW_jenozKc.m4a'
[ffmpeg] Post-process file youtube-dl test video ''_ä↭𝕐-BaW_jenozKc.m4a exists, skipping
```

**Comment by jaimeMF** [comment]
If that's not what you want, please elaborate on what you need.

**Comment by latot** [comment]
mm, i'll explain a little more.

In windows we don't have always the ffmpeg specially for normal users, so if we want download for example the audio of a youtube video we do 'youtube-dl "some video" -x' and it download the m4a file, but then it try to call ffmpeg, and if only need the audio it feels don't is necesary, bacause when it don't found it send the error messsage, obvs we can use the -i option but we will skip other problems we can be interested, for example an audio don't is downloaded.

**Comment by jaimeMF** [comment]
Ok, but note that some player doesn't play or have problems playing the m4a audio file generated by YouTube and ffmpeg is required to fix the file.

**Comment by latot** [comment]
yes, but if the m4a file is corrupted ffmpeg will can't fix it, but if the player want other format to can reproduce it there call ffmpeg.
