### ISSUE TITLE
How to set user agent in embedded python script ?

### ISSUE THREAD

**Issue by crhuber** [ytdl-org/youtube-dl#7830]
I am calling youtube-dl from a python script. Like so:

```
from __future__ import unicode_literals
import youtube_dl

ydl_opts = {
'format': 'bestaudio/best',
'postprocessors': [{
    'key': 'FFmpegExtractAudio',
    'preferredcodec': 'mp3',
    'preferredquality': '192',
}],
'logger': MyLogger(),
'progress_hooks': [my_hook],
}

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
ydl.download(['http://www.youtube.com/watch?v=BaW_jenozKc'])
```

However, I want to specifically set the user agent to be that of iOS Safari. How would i set the option for user agent? I do not see that as an available option here https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L117-L265

**Comment by phihag** [comment]
Can you elaborate why you want to do that? If some website works better when given another user agent, I'd very much improve youtube-dl to always set the user agent for the website.

**Comment by crhuber** [comment]
@phihag from what I understand some websites return different encoded videos depending on your user agent string. I could be wrong on that. But, when I use youtube_dl from Linux to download a video from bbc.co.uk it is unplayable on QuickTime in mac.

**Comment by Remls** [comment]
For anyone else that found this thread looking for a solution to the same issue, this worked for me:

```python
youtube_dl.utils.std_headers["User-Agent"] = "your user agent"
...
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(["https://youtu.be/dQw4w9WgXcQ"])
```
