### ISSUE TITLE
Excessive whitespace prevents subtitles from being displayed

### ISSUE THREAD

**Issue by forthrin** [ytdl-org/youtube-dl#7908]
```
youtube-dl -f hls-2389 --all-subs --convert-subtitles srt https://tv.nrk.no/serie/historia-om-walt-disney/KOID24008615/sesong-1/episode-1
```

In the downloaded `.srt` file, excessive whitespace in subtitle 11 and many others causes the subtitles not to be displayed in VLC.

```
10
00:01:09,640 --> 00:01:14,819
Walt sa: "Vi får sjå
om han er god. Du har ein idé."

11
00:01:15,120 --> 00:01:19,820

         Walt Disney var 

         internasjonal kjendis før han var 30. 
```

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by forthrin** [comment]
This is still an issue. Geo-restriction is not a hinderance to fix the bug. Here is a simple example that shows what goes wrong. Basically just ignore all formatting and strip all whitespace. 

Original TTML:

      <p begin="00:00:19.680" dur="00:00:03.180" style="left">
        <span style="italic"> I hvor stor grad </span>
        <br />
        <span style="italic"> spiller kjemi og biologi inn? </span>
      </p>

Current, incorrect conversion to SRT:

    6
    00:00:19,679 --> 00:00:22,859
    I hvor stor grad 
        

             spiller kjemi og biologi inn?

Correct conversion to SRT:

    6
    00:00:19,679 --> 00:00:22,859
    I hvor stor grad 
    spiller kjemi og biologi inn?

**Comment by forthrin** [comment]
@dstftw: After years this is still a problem. Isn't this a very easy fix? Just remove all superfluous whitespace (including newlines), and replace `<br/>` with a newline.

**Comment by forthrin** [comment]
@dstftw: Here is a simple patch that should resolve the whitespace issue.

```
diff --git a/youtube_dl/utils.py b/youtube_dl/utils.py
index f5a0bb4..1829a4c 100644
--- a/youtube_dl/utils.py
+++ b/youtube_dl/utils.py
@@ -2809,3 +2809,3 @@ def dfxp2srt(dfxp_data):
         def data(self, data):
-            self._out += data
+            self._out += data.strip()
 
```
