### ISSUE TITLE
VIMEO error (caused by KeyError(u'title',))

### ISSUE THREAD

**Issue by RingoTheDog** [ytdl-org/youtube-dl#8000]
URL: https://vimeo.com/mwpa/review/146686474/64de3b58ad

Output:
youtube-dl -v "https://vimeo.com/mwpa/review/146686474/64de3b58ad"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://vimeo.com/mwpa/review/146686474/64d
e3b58ad']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.23
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[vimeo] 146686474: Downloading webpage
[vimeo] 146686474: Extracting information
ERROR: An extractor error has occured. (caused by KeyError(u'title',)); please r
eport this issue on https://yt-dl.org/bug . Make sure you are using the latest v
ersion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --ve
rbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\common.pyo", line 291, in extract
  File "youtube_dl\extractor\vimeo.pyo", line 358, in _real_extract
KeyError: u'title'
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\extractor\common.pyo", line 297, in extract
ExtractorError: An extractor error has occured. (caused by KeyError(u'title',));
 please report this issue on https://yt-dl.org/bug . Make sure you are using the
 latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with
 the --verbose flag and include its complete output.

Thanks
Ringo

**Comment by mohamed-aziz** [comment]
I think that Youtube-dl don't support vimeo review pages.
