### ISSUE TITLE
facebook:  spanish -> "no descarga el video"

### ISSUE THREAD

**Issue by NodosDsnn** [ytdl-org/youtube-dl#8072]
comment (spanish):
"no descarga el video
 pero si puede verse desde el navegador.
 aparentemente es un video público.
 otros videos si son descargados.
"
debug:
$ youtube-dl --verbose "https://www.facebook.com/GOking2007/videos/967527569949038/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/GOking2007/videos/967527569949038/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.6 - Linux-3.16.0-38-generic-x86_64-with-LinuxMint-17.2-rafaela
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[facebook] 967527569949038: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 330, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1886, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by rg3** [comment]
Comment translation: The video cannot be downloaded but it can be viewed from the web browser. Apparently it's a public video. Other videos are downloaded without problems.

But I can't play it from the web browser either.

**Comment by dstftw** [comment]
Plays fine with Chrome but not Firefox.

**Comment by rg3** [comment]
I don't have Chrome, but I get HTTP error 500 with an up-to-date youtube-dl too. So I'm guessing it's all server-side.

**Comment by remitamine** [comment]
works fine with the latest version.
