### ISSUE TITLE
Yahoo Video downloading is now broken (both http: and https:)

### ISSUE THREAD

**Issue by Bandicoot** [ytdl-org/youtube-dl#8143]
bandy@media:/sagan/Shorts$ sudo youtube-dl -U
[sudo] password for bandy: 
youtube-dl is up-to-date (2016.01.01)
bandy@media:/sagan/Shorts$ youtube-dl --verbose 'https://video.yahoo.com/amazing-alexander-000000031.html'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://video.yahoo.com/amazing-alexander-000000031.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.01
[debug] Python version 2.7.6 - Linux-3.13.0-74-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3, avprobe 11.3, rtmpdump 2.4
[debug] Proxy map: {}
[Yahoo] amazing-alexander: Downloading webpage
ERROR: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/yahoo.py", line 208, in _real_extract
    video_id = self._search_regex(CONTENT_ID_REGEXES, webpage, 'content ID')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 586, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

bandy@media:/sagan/Shorts$ 
bandy@media:/sagan/Shorts$ youtube-dl --verbose -c 'http://video.yahoo.com/amazing-alexander-000000031.html'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-c', u'http://video.yahoo.com/amazing-alexander-000000031.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.01
[debug] Python version 2.7.6 - Linux-3.13.0-74-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3, avprobe 11.3, rtmpdump 2.4
[debug] Proxy map: {}
[Yahoo] amazing-alexander: Downloading webpage
ERROR: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/yahoo.py", line 208, in _real_extract
    video_id = self._search_regex(CONTENT_ID_REGEXES, webpage, 'content ID')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 586, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

bandy@media:/sagan/Shorts$

**Comment by chovy** [comment]
getting same issue here:

http://news.yahoo.com/video/presidential-hopeful-bernie-sanders-talks-202700207.html

**Comment by yan12125** [comment]
@choovy Could you paste/upload the output of the following command
```
youtube-dl -v --dump-pages http://news.yahoo.com/video/presidential-hopeful-bernie-sanders-talks-202700207.html
```
This URL works fine for me with version 2016.01.15.

**Comment by Bandicoot** [comment]
I still see the issue with 2016.01.15.  The video will play just fine in a browser.

root@media:/sagan/Shorts# !whi
which youtube-dl
/usr/local/bin/youtube-dl
root@media:/sagan/Shorts# /usr/local/bin/youtube-dl -U
youtube-dl is up-to-date (2016.01.15)
root@media:/sagan/Shorts# /usr/local/bin/youtube-dl --verbose -c 'https://video.yahoo.com/amazin
g-alexander-000000031.html'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-c', u'https://video.yahoo.com/amazing-alexander-000000031.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.15
[debug] Python version 2.7.6 - Linux-3.13.0-74-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3, avprobe 11.3, rtmpdump 2.4
[debug] Proxy map: {}
[Yahoo] amazing-alexander: Downloading webpage
ERROR: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 312, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/yahoo.py", line 226, in _real_extract
    CONTENT_ID_REGEXES, webpage, 'content ID')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 607, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
This video is geo-restricted. At least it's not available in Taiwan. Which country are you in?

**Comment by Bandicoot** [comment]
USA.
