### ISSUE TITLE
can't detect video

### ISSUE THREAD

**Issue by W5x** [ytdl-org/youtube-dl#8196]
hello ,
the program can detect and download the rest season video's except this one i need to download it in 720p quality  please help 

https://shahid.mbc.net/ar/episode/113347/%D9%85%D8%B3%D8%B1%D8%AD-%D9%85%D8%B5%D8%B1-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-1-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-1.html

thanks in advance

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by W5x** [comment]
here's the log 

[1/10/2016 3:12:08 AM] Unable to add https://shahid.mbc.net/ar/episode/113347/%D9%85%D8%B3%D8%B1%D8%AD-%D9%85%D8%B5%D8%B1-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-1-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-1.html. (Couldn't find any formats)

**Comment by dstftw** [comment]
This does not look like valid youtube-dl log. Read [bug reporting guide](https://github.com/rg3/youtube-dl#bugs).

**Comment by W5x** [comment]
here's the log from command line 
[debug] Encodings: locale cp1256, fs mbcs, out cp720, pref cp1256
[debug] youtube-dl version 2016.01.01
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-77556-g4160900, ffprobe N-77556-g4160900
[debug] Proxy map: {}
[Shahid] 113347: Downloading webpage
[Shahid] 113347: Downloading player JSON
[Shahid] 113347: Downloading m3u8 information

it stopped like that and nothing else happen looks like it's freezes since 5 minutes ago , i tried other episode link that works fine in the UI version and it works normally

**Comment by remitamine** [comment]
i added an error message when the video is drm protected.

**Comment by W5x** [comment]
so no solution for downloading that video ?

**Comment by remitamine** [comment]
it will be difficult to fix this problem(some of the extractor are broken because of DRM protection like nowtv).

**Comment by W5x** [comment]
aha ok, just let me know if you found a solution for that in the future.

thanks for all your help 

best regards

**Comment by 89z** [comment]
Issue should be closed, appears to be resolved
