### ISSUE TITLE
REQ: build information cache; combined search

### ISSUE THREAD

**Issue by luxifr** [ytdl-org/youtube-dl#858]
I'd love to use youtube-dl to completely automate my day-to-day youtube needs ;) However it misses some functionality, that is:
- When searching for videos youtube-dl should not download ALL video ids over and over again but instead build a database that holds metadata associated with the ids like date, user, title and so forth
- also it would be nice to be able to combine searches like all videos from "foo" containing "bar" in the title like "ytuser:foo ytsearch:bar"

with these additions one could automate downloading regular videos from users and only download those that one's interested in... also the cache would speed things up imensely if the ids are retrieved sorted by date...

cheers

**Comment by dirkf** [comment]
Nowadays: `--download-archive ...`. Save info-json too for more data, but it may be superseded by site updates at any time.
