### ISSUE TITLE
Support Dagbladet (Norwegian newspaper)

### ISSUE THREAD

**Issue by forthrin** [ytdl-org/youtube-dl#8653]
Request support for downloading videos from Dagbladet (Norwegian newspaper):

```
~/$ youtube-dl -v http://www.dagbladet.no/2016/02/23/nyheter/nordlys/ski/troms/ver/43254897/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.dagbladet.no/2016/02/23/nyheter/nordlys/ski/troms/ver/43254897/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.10
[debug] Python version 2.7.11 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 43254897: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 43254897: Downloading webpage
[generic] 43254897: Extracting information
ERROR: Unsupported URL: http://www.dagbladet.no/2016/02/23/nyheter/nordlys/ski/troms/ver/43254897/
```

**Comment by TRox1972** [comment]
dbtv.no is already supported, which is what dagbladet.no uses. Extracting the iFrame URL from the provided URL yields www.dbtv.no/lazyplayer/4769123329001, which is supported.

**Comment by TRox1972** [comment]
@remitamine Thanks to 8a8590a61784b9f4a8ff380058a1571d5400ba3d, it is now supported.

**Comment by TRox1972** [comment]
As of 8a8590a61784b9f4a8ff380058a1571d5400ba3d, some videos on the site, such as [this one](https://dbtv.no/5028749599001?dbtvl=6) are working, although not the provided URL as it seems that they've seen to changed their layout.

**Comment by forthrin** [comment]
Still failing. Any update on this? Shouldn't https://github.com/rg3/youtube-dl/pull/10364 have fixed this?
