### ISSUE TITLE
Support p3.no (part of Norwegian Broadcasting Corporation)

### ISSUE THREAD

**Issue by forthrin** [ytdl-org/youtube-dl#8709]
NRK is supported by `youtube-dl`, but the underlying P3 channel (at separate domain p3.no) is not. Example:

```
~$ youtube-dl --verbose http://skam.p3.no
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://skam.p3.no']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.10
[debug] Python version 2.7.11 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] skam.p3: Requesting header
WARNING: Falling back on generic information extractor.
[generic] skam.p3: Downloading webpage
[generic] skam.p3: Extracting information
ERROR: Unsupported URL: http://skam.p3.no
```

**Comment by yan12125** [comment]
This URL looks like the main page of a website. You need to give an URL to a specific video yo youtube-dl.

**Comment by forthrin** [comment]
There are lots of videos if you scroll down on a page, so `youtube-dl` should be able to download all of the videos in the page (similar to a playlist on YouTube). But sine you ask, here is also a specific video page:

http://skam.p3.no/2016/03/04/strong-and-independent/

**Comment by yan12125** [comment]
Thanks for the URL. Sorry if my previous comment sounds offensive.

**Comment by TRox1972** [comment]
To developers: NRK embed

**Comment by forthrin** [comment]
Any update on this, reported two years ago? New series launched the other day, still not downloadable.  https://blank.p3.no/2018/04/16/hvilken-dato/

**Comment by forthrin** [comment]
@yan12125: Example: <https://blank.p3.no/2018/04/18/tungtveiende-grunner/> contains `<div class="flex-video widescreen"><div class="nrk-video" data-nrk-id="d47bde73-7ce9-47be-89f6-01f024235c2b" data-nrk-mode="simple"></div>` which leads to https://static.nrk.no/ludo/latest/video-embed.html#id=d47bde73-7ce9-47be-89f6-01f024235c2b which agains leads to https://nrk-od-31.akamaized.net/world/162931/0/hls/d5ff2bcf29494f9d84b2854be2f34e01/playlist.m3u8.

**Comment by forthrin** [comment]
This code extracts all videos from the front page. Should work inside each video page too. Feel free to create an extractor with it. I may give it a shot too, but I've never written one before, so...

```
#!/usr/bin/env python

import re
import urllib2
import json

def fetch(url):
    req = urllib2.Request(url, headers={"User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"})
    return urllib2.urlopen(req).read()

url = "https://blank.p3.no/"
html = fetch(url)
matches = re.findall("querySelector\('.*?'\), '(.*?)', ludoOptions", html)

playlist = []
for match in reversed(matches):
    url = "https://psapi.nrk.no/playback/manifest/clip/" + match
    data = fetch(url)
    meta = json.loads(data)
    playlist.append(meta["playable"]["assets"][0]["url"])

```
