### ISSUE TITLE
[Crunchyroll] ERROR: Unable to extract video_title

### ISSUE THREAD

**Issue by pablo-escalate** [ytdl-org/youtube-dl#8776]
The extraction of the video title fails because there is something wrong with the regex.
This happens when the video title has characters such as .?!

```
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['-v', '-n', '--get-filename', '-o', '%(title)s.%(ext)s', 'http://www.crunchyroll.com/sailor-moon-crystal/sailor-moon-crystal-pretty-guardian-sailormoon-crystal-trailer-momoiro-clover-z-ver-655891']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 3.4.3 - Linux-4.4.3-300.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three
[debug] exe versions: ffmpeg 2.8.5, ffprobe 2.8.5, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 315, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/crunchyroll.py", line 294, in _real_extract
    webpage, 'video_title')
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 619, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 610, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Post the output of `youtube-dl -v --dump-pages http://www.crunchyroll.com/sailor-moon-crystal/sailor-moon-crystal-pretty-guardian-sailormoon-crystal-trailer-momoiro-clover-z-ver-655891`.

**Comment by pablo-escalate** [comment]
I noticed this seems to happen only when you are logged in. 
The dump-page contains redirect to the front page of Crunchyroll and doesn't seem to contain the video page.

So if you are ok with this, I shall not post it, because I don't feel like looking for any preferences to my personal account. It doesn't seem to have anything of value since there's just a redirect to the front page:
```
<html lang="en">
  <head>
    <title>Redirecting...</title>
    <meta http-equiv="refresh" content="0;url=http://www.crunchyroll.com/" />
  </head>
  <body>
    <script type="text/javascript">
      document.location.href="http:\/\/www.crunchyroll.com\/";
    </script>
  </body>
</html>
```
... and the front page.

**Comment by dstftw** [comment]
Can you watch it in browser when logged in?

**Comment by pablo-escalate** [comment]
Yes it works fine on a browser.

**Comment by pablo-escalate** [comment]
There's also the fact that it happens when using rtmpdump, since when logged in as a premium member you need it for HD. When you aren't logged in, rtmpdump isn't used.

**Comment by 1985Leo** [comment]
Hello Pablo :)
Can You Help me with this problem!

// define meta tags
$meta_title = $video['video_title']; HERE I WANT EXTRA TITLE 
$video['excerpt'] = (empty($video['excerpt'])) ? $video['video_title'] : $video['excerpt'];
$meta_description = generate_excerpt(str_replace('"', '&quot;', $video['excerpt']), 150) .'...';

$meta_keywords = '';
if(is_array($tags_arr))
foreach($tags_arr as $id => $v)
{
	$meta_keywords .= $v['tag'] . ', ';
}
$meta_keywords = substr($meta_keywords, 0, -2);
// end

**Comment by parse2** [comment]
I've started to get this same error today, except it's affecting every video on the site regardless whether I'm logged in or not. The error at common.py is slightly different, though. Example of video with no punctuation in title:

> [debug] System config: []
[debug] User config: [u'-o', u'/Volumes/My Passport2/convenient/youtube-dl_out/%(title)s-%(id)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.crunchyroll.com/citrus/episode-5-under-lover-758993']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.10 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[crunchyroll] 758993: Downloading webpage
ERROR: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/crunchyroll.py", line 446, in _real_extract
    webpage, 'video_title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
