### ISSUE TITLE
Downloading gameinformer.com is broken again (403 errors).

### ISSUE THREAD

**Issue by antdude** [ytdl-org/youtube-dl#8895]
Hello. 

Bad news. It's broken again:

$ youtube-dl -v http://www.gameinformer.com/b/features/archive/2016/03/18/replay-chrono-trigger.aspx
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.gameinformer.com/b/features/archive/2016/03/18/replay-chrono-trigger.aspx']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: ffmpeg 2.8.6-1, ffprobe 2.8.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[GameInformer] replay-chrono-trigger: Downloading webpage
[brightcove:new] 4807556445001: Downloading webpage
[brightcove:new] 4807556445001: Downloading JSON metadata
[brightcove:new] 4807556445001: Downloading m3u8 information
[debug] Invoking downloader on 'http://gamestop.brightcove.com.edgesuite.net/694940074001/201603/874/694940074001_4807764031001_4807556445001.mp4?pubId=694940074001&videoId=4807556445001'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1627, in process_info
    success = dl(filename, info_dict)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1569, in dl
    return fd.download(name, info)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/common.py", line 344, in download
    return self.real_download(filename, info_dict)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1929, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(_args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(_args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Thank you in advance. :)

**Comment by remitamine** [comment]
works for me:
```
youtube-dl -v http://www.gameinformer.com/b/features/archive/2016/03/18/replay-chrono-trigger.aspx
[debug] System config: []
[debug] User config: ['--external-downloader', 'aria2c', '--external-downloader-args', '-x 16', '-f', 'best[height<=?720]/best[height<=?720]+bestaudio', '--sub-format', 'srt/vtt/best', '--convert-subs', 'srt', '--sub-lang', 'ar,arME,en,enUS,en-US', '--write-sub', '--no-check-certificate']
[debug] Command-line args: ['-v', 'http://www.gameinformer.com/b/features/archive/2016/03/18/replay-chrono-trigger.aspx']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.27
[debug] Python version 3.5.1 - Linux-4.4.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0, ffprobe 3.0, rtmpdump 2.4
[debug] Proxy map: {}
[GameInformer] replay-chrono-trigger: Downloading webpage
[brightcove:new] 4807556445001: Downloading webpage
[brightcove:new] 4807556445001: Downloading JSON metadata
[brightcove:new] 4807556445001: Downloading m3u8 information
[debug] Invoking downloader on 'http://gamestoptx.uds.ak.o.brightcove.com/694940074001/694940074001_4807764031001_4807556445001.mp4?pubId=694940074001&videoId=4807556445001'
[download] Destination: Replay - Chrono Trigger-4807556445001.mp4
[debug] aria2c command line: aria2c -c -x 16 --out 'Replay - Chrono Trigger-4807556445001.mp4.part' --header 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0 (Chrome)' --header 'Accept-Encoding: gzip, deflate' --header 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-us,en;q=0.5' --check-certificate=false -- 'http://gamestoptx.uds.ak.o.brightcove.com/694940074001/694940074001_4807764031001_4807556445001.mp4?pubId=694940074001&videoId=4807556445001'
[#fee4ee 10MiB/1.8GiB(0%) CN:16 DL:214KiB ETA:2h25m41s]
```

**Comment by antdude** [comment]
remitamine: Thanks. It also works for me too. Weird!

**Comment by antdude** [comment]
Wait, I found another video that doesn't work:

$  youtube-dl -v http://www.gameinformer.com/b/features/archive/2016/03/25/replay-kabuki-warriors.aspx
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.gameinformer.com/b/features/archive/2016/03/25/replay-kabuki-warriors.aspx']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.27
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: ffmpeg 2.8.6-1, ffprobe 2.8.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[GameInformer] replay-kabuki-warriors: Downloading webpage
[brightcove:new] 4817847791001: Downloading webpage
[brightcove:new] 4817847791001: Downloading JSON metadata
[brightcove:new] 4817847791001: Downloading m3u8 information
[debug] Invoking downloader on 'http://gamestop.brightcove.com.edgesuite.net/694940074001/201603/2248/694940074001_4818015052001_4817847791001.mp4?pubId=694940074001&videoId=4817847791001'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1632, in process_info
    success = dl(filename, info_dict)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1574, in dl
    return fd.download(name, info)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1934, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

I wonder if it only happens with the new videos?
