### ISSUE TITLE
[MDR] Livestream video link extraction doesnt work anymore

### ISSUE THREAD

**Issue by toluwabohu** [ytdl-org/youtube-dl#8984]
Since the major update of www.mdr.de extraction of videolinks from livestream-pages gives error messages. It used to work prior to the update. See log of an example:

youtube-dl -g -v "http://www.mdr.de/mediathek/livestreams/fernsehen/index.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-g', '-v', 'http://www.mdr.de/mediathek/livestreams/fernsehen/index.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.25
[debug] Python version 3.5.1 - Linux-4.4.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0, ffprobe 3.0, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.mdr.de/mediathek/livestreams/fernsehen/index.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 320, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2003, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.mdr.de/mediathek/livestreams/fernsehen/index.html

**Comment by yan12125** [comment]
In the webpage it says:
```
Derzeit kein Livestream verfügbar
```
Or "Currently no Live Stream available" in English according to Google translate. Are there other example?
