### ISSUE TITLE
Unsupported URL: http://www.mymathlabglobal.com/

### ISSUE THREAD

**Issue by garrytre** [ytdl-org/youtube-dl#8998]
I tried to download a video. Failed. I followed instructions, see below. No idea if it's 1)important 2)new bug 3)legal, rah rah.

garry@gauntlet:~$ youtube-dl --verbose http://www.mymathlabglobal.com/Student/MediaPopup.aspx?type=assignedmedia&assignmentId=647911&loc=1&flush=yes&record=1&OnOpenerViewed=doMedia_onViewed
[3] 4038
[4] 4039
[5] 4040
[6] 4041
[7] 4042
[4]   Done                    assignmentId=647911
garry@gauntlet:~$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.mymathlabglobal.com/Student/MediaPopup.aspx?type=assignedmedia']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-29-generic-i686-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[generic] MediaPopup: Requesting header
[redirect] Following redirect to http://www.mymathlabglobal.com/login_mxl.htm?returnurl=%2fStudent%2fMediaPopup.aspx%3ftype%3dassignedmedia
[generic] login_mxl.htm?returnurl=%2fStudent%2fMediaPopup: Requesting header
WARNING: Falling back on generic information extractor.
[generic] login_mxl.htm?returnurl=%2fStudent%2fMediaPopup: Downloading webpage
[generic] login_mxl.htm?returnurl=%2fStudent%2fMediaPopup: Extracting information
ERROR: Unsupported URL: http://www.mymathlabglobal.com/login_mxl.htm?returnurl=%2fStudent%2fMediaPopup.aspx%3ftype%3dassignedmedia; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 380, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.mymathlabglobal.com/login_mxl.htm?returnurl=%2fStudent%2fMediaPopup.aspx%3ftype%3dassignedmedia; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

[3]   Exit 1                  youtube-dl --verbose http://www.mymathlabglobal.com/Student/MediaPopup.aspx?type=assignedmedia
[5]   Done                    loc=1
[6]   Done                    flush=yes
[7]   Done                    record=1
garry@gauntlet:~$

**Comment by dstftw** [comment]
1. You have to either put the URL into quotes or manually escape all the special shell characters. Read [FAQ entry](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command) for details.
2. Provided example URL redirects to http://www.pearsonmylabandmastering.com/global/mymathlab-global/ where there are no videos available.
3. mymathlabglobal.com is not supported.

**Comment by garrytre** [comment]
Sergey thanks, I thought a download probably wouldn't work, being a
for-profit thing that wants to hang on to it's IP.
But no harm testing, and no harm reporting to you guys, as is the open
source ethic.
regards Garry

**Comment by TRox1972** [comment]
@garrytre Could you provide a working URL, or close this issue.
