### ISSUE TITLE
Not Issue but a request

### ISSUE THREAD

**Issue by vfernandes1988** [ytdl-org/youtube-dl#9049]
Can you developer a configuration for delete all videos on playlist after download.

**Comment by yan12125** [comment]
Could you describe your need in more details? If you're not going to save these files, why download it at first?

**Comment by vfernandes1988** [comment]
Well, i have a lot of youtube subscription and i want to download video of all of my subscription channel.
i want add one per one url to download

**Comment by yan12125** [comment]
Seems I misunderstood. Did you mean:

1. You have write access to some playlist on YouTube.
2. You have saved several videos in this playlist.
3. With youtube-dl, all videos are downloaded, and the playlist on YouTube is cleared.

This feature requires login, and I guess it should be feasible.

**Comment by Hrxn** [comment]
I think that is what he meant, yes..

Could be a useful feature, I think I agree.

**Comment by vfernandes1988** [comment]
Well i explain with more details.
If you subscribe on your channel you can see on this link https://www.youtube.com/subscription_manager
i want to download channels that i have subscription

**Comment by yan12125** [comment]
> delete all videos on playlist

Delete what videos?

For example if I subscribe DeepMind's channel (https://www.youtube.com/channel/UCP7jMXSY2xbc3KCAE0MHQ-A), what youtube-dl should do after downloading all videos from DeepMind?
