### ISSUE TITLE
"rtmpdump exited with code 1" when trying to download from Crunchyroll

### ISSUE THREAD

**Issue by SamusAranX** [ytdl-org/youtube-dl#9053]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.01**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\Peter\Videos>youtube-dl.exe http://www.crunchyroll.com/jojos-bizarre-adventure/episode-1-jotaro-kujo-meets-josuke-higashikata-702297 -f 1080p --verbose
[debug] System config: []
[debug] User config: [u'--netrc', u'--user-agent', u'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36']
[debug] Command-line args: [u'http://www.crunchyroll.com/jojos-bizarre-adventure/episode-1-jotaro-kujo-meets-josuke-higashikata-702297', u'-f', u'1080p', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.04.01
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg 2.8.4, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 702297: Downloading webpage
[Crunchyroll] 702297: Downloading media info
[Crunchyroll] 702297: Downloading media info for 360p
[Crunchyroll] 702297: Downloading media info for 480p
[Crunchyroll] 702297: Downloading media info for 720p
[Crunchyroll] 702297: Downloading media info for 1080p
[debug] Invoking downloader on u'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEa0azcLd.aTdmdzbSckb.ddaAcMaIaicQ-bw_UXu-dHa-nAIystJACxw&aifp=0009&slist=c2/s/ve2186853/video.mp4'
[download] Destination: JoJo's Bizarre Adventure Folge 1 – Jtar Kj! Trifft Jsuke Higashikata-702297.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEa0azcLd.aTdmdzbSckb.ddaAcMaIaicQ-bw_UXu-dHa-nAIystJACxw&aifp=0009&slist=c2/s/ve2186853/video.mp4' -o 'JoJo'"'"'s Bizarre Adventure Folge 1 – Jtar Kj! Trifft Jsuke Higashikata-702297.flv.part' --playpath mp4:c2/s/ve2186853/video.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : cp150757.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand/?auth=daEa0azcLd.aTdmdzbSckb.ddaAcMaIaicQ-bw_UXu-dHa-nAIystJACxw&aifp=0009&slist=c2/s/ve2186853/video.mp4
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : cp150757.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:c2/s/ve2186853/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://cp150757.edgefcs.net:1935/ondemand/?auth=daEa0azcLd.aTdmdzbSckb.ddaAcMaIaicQ-bw_UXu-dHa-nAIystJACxw&aifp=0009&slist=c2/s/ve2186853/video.mp4
[rtmpdump] DEBUG: app      : ondemand/?auth=daEa0azcLd.aTdmdzbSckb.ddaAcMaIaicQ-bw_UXu-dHa-nAIystJACxw&aifp=0009&slist=c2/s/ve2186853/video.mp4
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : cp150757.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand/?auth=daEa0azcLd.aTdmdzbSckb.ddaAcMaIaicQ-bw_UXu-dHa-nAIystJACxw&aifp=0009&slist=c2/s/ve2186853/video.mp4
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : cp150757.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:c2/s/ve2186853/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://cp150757.edgefcs.net:1935/ondemand/?auth=daEa0azcLd.aTdmdzbSckb.ddaAcMaIaicQ-bw_UXu-dHa-nAIystJACxw&aifp=0009&slist=c2/s/ve2186853/video.mp4
[rtmpdump] DEBUG: app      : ondemand/?auth=daEa0azcLd.aTdmdzbSckb.ddaAcMaIaicQ-bw_UXu-dHa-nAIystJACxw&aifp=0009&slist=c2/s/ve2186853/video.mp4
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.


ERROR: rtmpdump exited with code 1
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 419, in main
  File "youtube_dl\__init__.pyo", line 409, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1725, in download
  File "youtube_dl\YoutubeDL.pyo", line 680, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 725, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1371, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1633, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1575, in dl
  File "youtube_dl\downloader\common.pyo", line 350, in download
  File "youtube_dl\downloader\rtmp.pyo", line 202, in real_download
  File "youtube_dl\downloader\common.pyo", line 161, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 544, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 506, in trouble
```

---

I'm on vacation, using my landlord's guest network (that, as far as I can tell, blocks all ports but 80 and 443) and wanted to download the newest JoJo so I could watch it on the ride home tomorrow.
As you can see above, I'm outta luck.
My .netrc contains my Crunchyroll login data and my youtube-dl.conf contains `--netrc` and my browser's user agent, because why not.

I can watch the video just fine in Chrome and on my iPhone, all while using the wifi mentioned above, so I'm not 100% sure this error is caused by blocked ports.

I got rtmpdump 2.4 from here: https://ffmpeg.zeranoe.com/forum/viewtopic.php?t=1024
If some site has a newer version, their SEO is shit, because Google doesn't list it.

**Comment by RepoBike** [comment]
I get the same error. Had to update FFmpeg. it was a pain to do. But it worked. Here's the link that i used to update FFmpeg.

https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media

**Comment by edgeyaph** [comment]
I'm having the same error on OS X for a youtube-dl version installed through homebrew, with ffmpeg and rtmpdump installed through homebrew.  Here is my output:

taiga:Season 01 ryu$ youtube-dl --netrc --verbose http://www.crunchyroll.com/sailor-moon-crystal/episode-1-act-1-usagi-sailor-moon-656623
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--netrc', u'--verbose', u'http://www.crunchyroll.com/sailor-moon-crystal/episode-1-act-1-usagi-sailor-moon-656623']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.13
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 656623: Downloading webpage
[Crunchyroll] 656623: Downloading media info
[Crunchyroll] 656623: Downloading media info for 360p
[Crunchyroll] 656623: Downloading media info for 480p
[Crunchyroll] 656623: Downloading media info for 720p
[Crunchyroll] 656623: Downloading media info for 1080p
[debug] Invoking downloader on u'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEb5aTamamdndjbJcTcXarcYcvdWc5bxcq-bxe39D-dHa-sAIwnqJDAxD&aifp=0009&slist=c17/s/ve1439485/v1/video.mp4'
[download] Destination: Sailor Moon Crystal (Eps 1-26) Episode 1 – Act. 1 Usagi - Sailor Moon --656623.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEb5aTamamdndjbJcTcXarcYcvdWc5bxcq-bxe39D-dHa-sAIwnqJDAxD&aifp=0009&slist=c17/s/ve1439485/v1/video.mp4' -o 'Sailor Moon Crystal (Eps 1-26) Episode 1 – Act. 1 Usagi - Sailor Moon --656623.flv.part' --playpath mp4:c17/s/ve1439485/v1/video.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : cp150757.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand/?auth=daEb5aTamamdndjbJcTcXarcYcvdWc5bxcq-bxe39D-dHa-sAIwnqJDAxD&aifp=0009&slist=c17/s/ve1439485/v1/video.mp4
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : cp150757.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:c17/s/ve1439485/v1/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://cp150757.edgefcs.net:1935/ondemand/?auth=daEb5aTamamdndjbJcTcXarcYcvdWc5bxcq-bxe39D-dHa-sAIwnqJDAxD&aifp=0009&slist=c17/s/ve1439485/v1/video.mp4
[rtmpdump] DEBUG: app      : ondemand/?auth=daEb5aTamamdndjbJcTcXarcYcvdWc5bxcq-bxe39D-dHa-sAIwnqJDAxD&aifp=0009&slist=c17/s/ve1439485/v1/video.mp4
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : cp150757.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand/?auth=daEb5aTamamdndjbJcTcXarcYcvdWc5bxcq-bxe39D-dHa-sAIwnqJDAxD&aifp=0009&slist=c17/s/ve1439485/v1/video.mp4
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : cp150757.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:c17/s/ve1439485/v1/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://cp150757.edgefcs.net:1935/ondemand/?auth=daEb5aTamamdndjbJcTcXarcYcvdWc5bxcq-bxe39D-dHa-sAIwnqJDAxD&aifp=0009&slist=c17/s/ve1439485/v1/video.mp4
[rtmpdump] DEBUG: app      : ondemand/?auth=daEb5aTamamdndjbJcTcXarcYcvdWc5bxcq-bxe39D-dHa-sAIwnqJDAxD&aifp=0009&slist=c17/s/ve1439485/v1/video.mp4
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.


ERROR: rtmpdump exited with code 1
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 419, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 409, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1730, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 727, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1376, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1638, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1580, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 161, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 545, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 507, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
