### ISSUE TITLE
Can't download purchased movies from YouTube (encrypted?)

### ISSUE THREAD

**Issue by valerie-makes** [ytdl-org/youtube-dl#9148]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.04.06_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**
### Before submitting an _issue_ make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl 'https://www.youtube.com/watch?v=AEP4zVQGpxk' -u 'david.bailey@archlinux.net' --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=AEP4zVQGpxk', '-u', 'PRIVATE', '--verbose']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 3.5.1 - Linux-4.4.6-1-ck-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
Type 2-step verification code and press [Return]: 
[youtube] Submitting TFA code
[youtube] AEP4zVQGpxk: Downloading webpage
[youtube] AEP4zVQGpxk: Downloading video info webpage
[youtube] AEP4zVQGpxk: Extracting video information
[youtube] {60} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {52} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {146} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {197} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {226} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {227} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {145} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {196} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {224} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {225} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {144} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {195} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {220} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {221} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {222} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {223} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {143} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {194} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {142} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {161} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {148} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {149} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {150} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {198} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] {199} signature length 40.42, html5 player en_US-vfllNvdW4
[youtube] AEP4zVQGpxk: Downloading MPD manifest
[youtube] AEP4zVQGpxk: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vfllNvdW4/base.js
[youtube] AEP4zVQGpxk: Downloading MPD manifest
WARNING: [youtube] AEP4zVQGpxk: Skipping DASH manifest: ExtractorError("Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)
[debug] Invoking downloader on 'https://r5---sn-aigllnsy.c.youtube.com/videoplayback?requiressl=yes&mime=video%2Fwebm&gir=yes&keepalive=yes&expire=1460335770&fexp=9416126%2C9416778%2C9416891%2C9417422%2C9420452%2C9422596%2C9422841%2C9423662%2C9426926%2C9427902%2C9428398%2C9428709%2C9429015%2C9429130%2C9431117%2C9431449%2C9431686%2C9432198%2C9432629%2C9433727&pfa=5&lmt=1454036854132099&mm=30&ipbits=8&mn=sn-aigllnsy&pl=16&sparams=clen%2Ccp%2Cctier%2Cdur%2Cgcr%2Cgir%2Chightc%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpfa%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&cp=U0lVRVNOU19MSkNPNV9LSFdIOmxCX2tJTHF4U2Zn&id=o-APl1-DgzpwBjTzmyiX0GmmXYY9oBTOJsBEq4baDAm-av&mt=1460314055&dur=8178.169&mv=m&initcwndbps=2031250&ms=nxu&itag=197&sver=3&ip=87.113.135.60&ctier=A&hightc=yes&key=yt6&nh=IgpwcjAxLmxocjE0KgkxMjcuMC4wLjE&upn=9Qh79aJevNQ&clen=3301723730&source=youtube&gcr=gb&signature=771846D6EBDC93201839D91C63E6CA504CEFF59C.C7E93C7A9C69C9EA11C08F5897264988E6212CAD&ratebypass=yes'
[download] Resuming download at byte 51772418
[download] Destination: The Matrix-AEP4zVQGpxk.f197.webm
[download]   1.6% of 3.07GiB at 985.82KiB/s ETA 53:37
...
<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=AEP4zVQGpxk
- Single video: https://www.youtube.com/watch?v=91tu3aA0NVU
- (any purchasable movies)

---
### Description of your _issue_, suggested solution and other information

Explanation of your _issue_ in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your _issue_ required an account credentials please provide them or explain how one can obtain them.

When I try to download a movie from YouTube that's been purchased on Google Play, it'll appear to be downloaded successfully, but upon opening the file in the player the screen is black and no sound played. The video length on the seeker is correct, however. I'm not sure what the problem is exactly but I suppose it might be that YouTube uses some sort of extra encryption on movies that isn't present for normal videos.

N.b. I cancelled the download in the log given, but I've confirmed this happens each time when downloading in full. I've also tried other formats, none of which seem to work (the default is 1080p webm).

I've tried with the stable 2016.04.06 version, and the git version.

**Comment by dstftw** [comment]
Most likely they are DRM protected.

**Comment by tech4david** [comment]
I'd be happy to donate to the project for somebody to buy some movies to test this out; is there any way I can do so? I can code but don't have any experience in breaking DRM.

**Comment by dstftw** [comment]
No one had so far (apart from obvious screen capturing and some non practical heuristic pattern based approaches).

**Comment by tech4david** [comment]
I tried this again today just to see if I could use any other apps to remove the DRM but now I got the error 'rental videos unsupported' rather than the previous output. So it looks like this is another #359 duplicate... not sure why it worked initially though (not removing the DRM, but downloading the original file at least).

**Comment by remitamine** [comment]
at least detect that the video or the format are DRM protected.
youtube-dl won't extract DASH formats because when they are protected they will contain `ContentProtection`.
this some information that looks from the js code of the player:
- the `url_data` may contain `drm_families`.
- the `video_info` may contain one of this attributes `license_info`, `drm_session_id`, `fair_play_cert`.

**Comment by sakanaproductions** [comment]
Is there any update on this? I have numerous movies that are purchased that you can use for testing

**Comment by tommcintyre** [comment]
+1; I also have some purchased videos I could test with

**Comment by tommcintyre** [comment]
Actually, I just tried this with a purchased video, and it worked great, aside from one warning that didn't seem to cause a problem. youtube-dl had to log in under my account, obviously. The resulting file is DRM-free. I don't have any "rented" videos to test with, so not sure whether those use different DRM than purchased ones.

```$ youtube-dl -U
youtube-dl is up-to-date (2017.04.11)

$ cat ~/.config/youtube-dl/config
--output '%(upload_date)s_%(title)s-%(id)s.%(ext)s'
--netrc
--cookies ~/.config/youtube-dl/cookies.txt

$ youtube-dl --verbose 'https://www.youtube.com/watch?v=01LfnArRG4c'
[debug] System config: []
[debug] User config: [u'--output', u'%(upload_date)s_%(title)s-%(id)s.%(ext)s', u'--netrc', u'--cookies', u'~/.config/youtube-dl/cookies.txt']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=01LfnArRG4c']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.11
[debug] Python version 2.7.10 - Darwin-16.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
[youtube] 01LfnArRG4c: Downloading webpage
[youtube] 01LfnArRG4c: Downloading video info webpage
[youtube] 01LfnArRG4c: Extracting video information
[youtube] {22} signature length 41.43, html5 player en_US-vflqFHgLE
[youtube] {43} signature length 41.43, html5 player en_US-vflqFHgLE
[youtube] {18} signature length 41.43, html5 player en_US-vflqFHgLE
[youtube] {36} signature length 41.43, html5 player en_US-vflqFHgLE
[youtube] {17} signature length 41.43, html5 player en_US-vflqFHgLE
[youtube] {136} signature length 41.43, html5 player en_US-vflqFHgLE
[youtube] {135} signature length 41.43, html5 player en_US-vflqFHgLE
[youtube] {134} signature length 41.43, html5 player en_US-vflqFHgLE
[youtube] {133} signature length 41.43, html5 player en_US-vflqFHgLE
[youtube] {160} signature length 41.43, html5 player en_US-vflqFHgLE
[youtube] {140} signature length 41.43, html5 player en_US-vflqFHgLE
[youtube] 01LfnArRG4c: Downloading player https://www.youtube.com/yts/jsbin/player-en_US-vflqFHgLE/base.js
[youtube] 01LfnArRG4c: Downloading MPD manifest
WARNING: [youtube] 01LfnArRG4c: Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r8---sn-aigllns6.googlevideo.com/videoplayback?mt=1492013488&mv=m&ei=9FHuWLPzIoWbWq-eosgB&ms=au&ip=82.69.110.61&cmbypass=yes&pl=15&keepalive=yes&mm=31&mn=sn-aigllns6&id=o-AJeqLo5ygLT6Mu5WcorvsodkrwI14jEDFK6dI1hWrmYx&sparams=clen%2Ccmbypass%2Cctier%2Cdur%2Cei%2Cgcr%2Cgir%2Chightc%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpfa%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&clen=567988083&initcwndbps=1393750&ipbits=0&hightc=yes&source=youtube&pfa=5&gcr=gb&dur=3259.840&lmt=1492010483621835&requiressl=yes&ctier=A&gir=yes&key=yt6&mime=video%2Fmp4&itag=136&upn=1nWNM-SlkC0&expire=1492035156&signature=AA7AC0BE9FB5067A5412F79AE8589D528868351B.03161F1C927DF0264BE24EA1BEAABB5243B9A512&ratebypass=yes'
[download] Destination: 20170331_Let's Talk About Tax-01LfnArRG4c.f136.mp4
[download] 100% of 541.68MiB in 02:58
[debug] Invoking downloader on u'https://r8---sn-aigllns6.googlevideo.com/videoplayback?mt=1492013488&mv=m&ei=9FHuWLPzIoWbWq-eosgB&ms=au&ip=82.69.110.61&cmbypass=yes&pl=15&keepalive=yes&mm=31&mn=sn-aigllns6&id=o-AJeqLo5ygLT6Mu5WcorvsodkrwI14jEDFK6dI1hWrmYx&sparams=clen%2Ccmbypass%2Cctier%2Cdur%2Cei%2Cgcr%2Cgir%2Chightc%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpfa%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&clen=51775597&initcwndbps=1393750&ipbits=0&hightc=yes&source=youtube&pfa=5&gcr=gb&dur=3259.895&lmt=1492010629674489&requiressl=yes&ctier=A&gir=yes&key=yt6&mime=audio%2Fmp4&itag=140&upn=1nWNM-SlkC0&expire=1492035156&signature=6410DAEC98744D8D2D265A02F7DF8C8312418773.4DAF3B072F33EAD8B3DCFABA005E0D03DFBEFBC5&ratebypass=yes'
[download] Destination: 20170331_Let's Talk About Tax-01LfnArRG4c.f140.m4a
[download] 100% of 49.38MiB in 00:16
[ffmpeg] Merging formats into "20170331_Let's Talk About Tax-01LfnArRG4c.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:20170331_Let'"'"'s Talk About Tax-01LfnArRG4c.f136.mp4' -i 'file:20170331_Let'"'"'s Talk About Tax-01LfnArRG4c.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:20170331_Let'"'"'s Talk About Tax-01LfnArRG4c.temp.mp4'
Deleting original file 20170331_Let's Talk About Tax-01LfnArRG4c.f136.mp4 (pass -k to keep)
Deleting original file 20170331_Let's Talk About Tax-01LfnArRG4c.f140.m4a (pass -k to keep)

$ file 20170331_Let\'s\ Talk\ About\ Tax-01LfnArRG4c.mp4
20170331_Let's Talk About Tax-01LfnArRG4c.mp4: ISO Media, MP4 Base Media v1 [IS0 14496-12:2003]```

**Comment by tommcintyre** [comment]
@sakanaproductions  Just tried this on the latest version (2017.04.11), and it seems to work fine for purchased videos, despite one warning which didn't seem to affect the output. The resulting file was DRM-free. I don't have any "rented" videos, so not sure if those use different DRM.

**Comment by Semper-discens** [comment]
@tommcintyre what syntax did you use? I am running 2017.04.11 version and I get 2 warnings:
WARNING: Unknown codec dtse[youtube] {329} signature length 41.41, html5 player en_US-vfl5-0t5t
WARNING: Unknown codec eac3[youtube] {350} signature length 41.41, html5 player en_US-vfl5-0t5t
and I have the same issues as the original post.

**Comment by BerLeo** [comment]
I could've sworn I had a working drm-free video file from the 4.27 version, but since 4.28 everything's been unable to be properly played back.

**Comment by nilmanimitra** [comment]
can youtube-dl download DRM protected videos.....?????
