### ISSUE TITLE
Request - Globaltv.com

### ISSUE THREAD

**Issue by g8keepa** [ytdl-org/youtube-dl#9164]
u## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.04.06_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

youtube-dl -v http://bigbrothercanada.globaltv.com/watch/episode-18
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://bigbrothercanada.globaltv.com/watch/episode-18']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.9 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] episode-18: Requesting header
WARNING: Falling back on generic information extractor.
[generic] episode-18: Downloading webpage
[generic] episode-18: Extracting information
ERROR: Unsupported URL: http://bigbrothercanada.globaltv.com/watch/episode-18
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1348, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 279, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 268, in _XML
    parser.feed(text)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 12, column 193
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 323, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2012, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://bigbrothercanada.globaltv.com/watch/episode-18

---

with a different show:

youtube-dl -v http://www.globaltv.com/theyoungandtherestless/video/episode/apr072016/video.html?v=661247043879
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.globaltv.com/theyoungandtherestless/video/episode/apr072016/video.html?v=661247043879']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.9 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video: Downloading webpage
[generic] video: Extracting information
[debug] Invoking downloader on u'http://www.globaltv.com/theyoungandtherestless/video/full-episodes/apr/07/2016/video.html?v=661247043879'
[download] Destination: The Young and the Restless Video - Apr_07_2016 - GlobalTV.com-video.html
[download] 100% of 54.32KiB in 00:00

---
### Description of your _issue_, suggested solution and other information

Not sure if it's simple to add.  But would be appreciated, thanks!

**Comment by yan12125** [comment]
Other examples from #9859:

* http://www.globaltv.com/thetalk/video/episode/troian-bellisario/video.html?v=710029891680
* http://www.globaltv.com/houdinianddoyle/video/episode/strigoi/video.html?v=709396547680
* http://www.globaltv.com/houdinianddoyle/video/webisode/needles/video.html?v=665883715545

I can't check them as all of them reported missing Flash player though I have already the latest Flash.

And by the way, seems they are using custom ThePlatform videos.

**Comment by remitamine** [comment]
> http://www.globaltv.com/thetalk/video/episode/troian-bellisario/video.html?v=710029891680
http://www.globaltv.com/houdinianddoyle/video/episode/strigoi/video.html?v=709396547680
http://www.globaltv.com/houdinianddoyle/video/webisode/needles/video.html?v=665883715545

provides m3u8 manifests protected with Adobe Flash Access.
only the last clip(http://www.globaltv.com/houdinianddoyle/video/webisode/needles/video.html?v=665883715545) has non DRM assets: http://etvideo.smdg.ca/157/202/HoudiniDoyle_WoW_Ep7_highest_16x9.mp4.

**Comment by sjeble** [comment]
Any update on this? Global a no-go still?
https://www.globaltv.com/shows/mary-kills-people/video/twin-flames/1139224643580/
