### ISSUE TITLE
Autonumber and --download-archive

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#9224]
Autonumber doesn't work as expected with `--download-archive`. Not sure whether this should be considered a bug or a feature request, but it is kind of similar to the issue described in https://github.com/rg3/youtube-dl/issues/461.

On each run of youtube-dl with `--download-archive` and `%(autonumber)s` set, youtube-dl will skip over all previously downloaded videos (as expected), but when it reaches a video it hasn't downloaded, it will starting numbering from 00001 again. Essentially this means autonumber is more-or-less useless when using download-archive as each time it is run the numbering will again start from 00001.

Moreover, if `--download-archive` is used on a channel, youtube-dl will download videos from newest to oldest (as expected, nothing particularly wrong with downloading in this order), but it does mean that the latest video will be labelled 00001, while the oldest video will be labelled 00100 (for example, given a 100 video channel). This means if we run youtube-dl later when another video is added, there is no numbering that makes sense for this new video, labelling it as 00101 would put it after the oldest video, and obviously it can't be labelled higher than 00001, the newest video from the previous run. In order for this to be truly "fixed", autonumbering would also have to be reversed when `--download-archive` is used on a channel.

**Comment by glinkot** [comment]
I've just encountered this myself.  My download of the 00007 file failed while using the archive option.  On rerun, it successfully skips the existing videos, but then starts the next one at 00000 again.  Ideally it would still increment the numbering when skipping files.

**Comment by jacksonedmonds** [comment]
Hey glinkot, the issue obviously still hasn't been resolved, but a couple of suggestions that might be useful to you:

- If you're archiving a channel as a one off, you may have better mileage by adding the -i flag so youtube-dl will skip failed files and continue downloading (and therefore continue autonumbering correctly)
- Alternatively, if you're using autonumbering simply as a sorting mechanism, you may achieve similar results by putting %(date)s at the beginning of the file name. The only disadvantage (I can see) of this method compared to a properly implemented autonumbering system is that if an old video is moved from unlisted or privated to public, when it is grabbed by --download-archive, it will be slotted in according to its original publish date rather than its download date, meaning you may not realise a "new" video has been downloaded.

**Comment by glinkot** [comment]
Thanks for that Jackson, much appreciated.  I already have the -i flag in
use.  Right now my workaround is just to get the existing files, put them
in a 'part1' folder, then resume.  At least that way the order is
preserved.

**Comment by nil0bject** [comment]
there's an option to start the autonumbering at a value
`--autonumber-start NUMBER`

**Comment by glinkot** [comment]
Fantastic!  Thanks nilObject.

**Comment by whyicantusemyemailasusername** [comment]
I found the following apprach acceptable:
```bash
TOTAL_TRACKS=$(wc -l < "$OUT_DIR/archive.txt")
NUM_START=$(($TOTAL_TRACKS + 1))
youtube-dl --autonumber-start $NUM_START --download-archive "$OUT_DIR/archive.txt" ...
```
In this way new episodes get a number that is total_episodes_downloaded + 1

**Comment by Doublemyst** [comment]
> 
> 
> I found the following apprach acceptable:
> 
> ```shell
> TOTAL_TRACKS=$(wc -l < "$OUT_DIR/archive.txt")
> NUM_START=$(($TOTAL_TRACKS + 1))
> youtube-dl --autonumber-start $NUM_START --download-archive "$OUT_DIR/archive.txt" ...
> ```
> 
> In this way new episodes get a number that is total_episodes_downloaded + 1
Tried your solution .. it is not working, as it says unvalid intager $NUM_START..
Can you show your whole comand with an example youtube channel?

**Comment by whyicantusemyemailasusername** [comment]
Sure, it seems that I oversimplified the solution in previous post:
```bash
OUT_DIR="/srv/disk/some/download/path"
mkdir -p "$OUT_DIR"

# find first index

if [ -f "$OUT_DIR/archive.txt" ]; then
  TOTAL_TRACKS=$(wc -l < "$OUT_DIR/archive.txt")
else
  TOTAL_TRACKS=0
fi

NUM_START=$(($TOTAL_TRACKS + 1))

# download updates
youtube-dl \
  --extract-audio \
  --add-metadata \
  --autonumber-start $NUM_START \
  --download-archive "$OUT_DIR/archive.txt" \
  -o "$OUT_DIR/%(autonumber)s-%(title)s.%(ext)s" \
  --metadata-from-title "$METADATA_FORMAT" \
  "https://www.bbc.co.uk/programmes/$PLAYLIST/episodes/player"


```

**Comment by Luke-L** [comment]
still waiting for this to be fixed in 2022 lol

**Comment by Nuc1eoN** [comment]
> still waiting for this to be fixed in 2022 lol

Try yt-dlp

**Comment by pukkandan** [comment]
> still waiting for this to be fixed in 2022 lol

There is nothing to be "fixed". As the documentation clearly says, autonumber "will be increased **with each download**, starting at `--autonumber-start`". If videos are skipped from download, like when using archive, the number does not and **should not** increase. I am not sure why the issue has been left open all these years - considering there has been no input from maintainers, I'll assume it was just never triaged.

> It is essential when archiving youtube content like entire channels.

Why not use `playlist_index`?

> Try yt-dlp

While yt-dlp does offer more options like `video_autonumber`/`playlist_autonumber`, the behavior of `autonumber` itself is the same
