### ISSUE TITLE
Add support for PowVideo.net

### ISSUE THREAD

**Issue by saidma** [ytdl-org/youtube-dl#9246]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.04.19_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.19**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v http://powvideo.net/zoqp22jp5bvu
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://powvideo.net/zoqp22jp5bvu']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.19
[debug] Python version 2.7.6 - Linux-3.16.0-70-generic-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] zoqp22jp5bvu: Requesting header
WARNING: Falling back on generic information extractor.
[generic] zoqp22jp5bvu: Downloading webpage
[generic] zoqp22jp5bvu: Extracting information
ERROR: Unsupported URL: http://powvideo.net/zoqp22jp5bvu
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1374, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 279, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 268, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 25, column 17
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 671, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2044, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://powvideo.net/zoqp22jp5bvu

<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video:  http://powvideo.net/zoqp22jp5bvu

---
### Description of your _issue_, suggested solution and other information

Explanation of your _issue_ in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your _issue_ required an account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.

**Comment by saidma** [comment]
Ok, editing...

**Comment by yan12125** [comment]
http://powvideo.net/zoqp22jp5bvu looks like a copyrighted video, too. Does the site buy copyrights from the original authors of the video?

**Comment by Hrxn** [comment]
Look like just another random video hosting site..

**Comment by saidma** [comment]
The film was financed with crowdfunding.

**Comment by saidma** [comment]
If is an amateur video of a person dancing at home, how will we know if the host is allowed to host the video? The authors of the film does not claim copyright to the hosts. In fact, on Youtube there are hundreds of modified versions of the film. In fact, this video is a version with modified audio, fandubbed to spanish language, nonprofit.

**Comment by yan12125** [comment]
Sorry for the late response. For videos in which people dancing home: in my experience such videos are usually uploaded by the recorder, so the hosting website have legal rights to distribute it. However, for this video, [Wikipedia](https://en.wikipedia.org/wiki/Kung_Fury) says it's produced by Laser Unicorns. I guess it's copyright is owned by Laser Unicorns, too. The YouTube version you've mentioned is uploaded by Laser Unicorns, so it seems like a legal copy. On the other hand, there's no clue that the one on powvideo.net is also a legal copy.

**Comment by VertigoRay** [comment]
http://powvideo.net/tos

> In conjunction with Powvideo.net's Intellectual Property Policy, an affiliate account for which Powvideo.net receives one DMCA notification of potential copyright infringement will be permanently suspended. After suspension, the affiliate account can only be restored in one of two ways: 1) the affiliate account holder files a DMCA counter notification; or 2) the affiliate account holder visits the Powvideo.net Copyright Education page, and takes and passes the associated quiz.

Seems similar to YouTube's rules on copyright.
