### ISSUE TITLE
[DPlay] Unable to extract m3u8 manifest for some videos

### ISSUE THREAD

**Issue by TRox1972** [ytdl-org/youtube-dl#9339]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.04.24_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.24**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

```
$ youtube-dl --skip-download -v http://www.dplay.no/neste-sommer/season-3-episode-3
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--skip-download', u'-v', u'http://www.dplay.no/neste-sommer/season-3-episode-3']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.24
[debug] Python version 2.7.11 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[DPlay] season-3-episode-3: Downloading webpage
[DPlay] 25067: Downloading JSON metadata
[DPlay] 25067: Downloading hls stream JSON
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[DPlay] 25067: Downloading hds stream JSON
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[DPlay] 25067: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[DPlay] 25067: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dplay.py", line 140, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 862, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
$ youtube-dl -v http://www.dplay.no/neste-sommer/season-3-episode-4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.dplay.no/neste-sommer/season-3-episode-4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.24
[debug] Python version 2.7.11 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[DPlay] season-3-episode-4: Downloading webpage
[DPlay] 25069: Downloading JSON metadata
[DPlay] 25069: Downloading hls stream JSON
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[DPlay] 25069: Downloading hds stream JSON
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[DPlay] 25069: Downloading m3u8 information
[DPlay] 25069: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 503: Service Unavailable
[debug] Invoking downloader on u'http://sbsvod09-vh.akamaihd.net/i/delivery/9b/a3/9ba3935a-4a9b-4e87-ac07-562400552bcb/NO614614_1_,40,60,15,10,25,6,2,00k.mp4.csmil/index_1_av.m3u8?null=0'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 132
[download] Destination: Episode 4-25069.mp4
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---
### Description of your _issue_, suggested solution and other information

I am able to download the videos from the URLs http://www.dplay.no/neste-sommer/season-3-episode-1-6  except for no. 3, where it fails to download the m3u8 manifest.

**Comment by dirkf** [comment]
Obsolete URL format.
