### ISSUE TITLE
Washington Post URLs not using Washington Post Extractor

### ISSUE THREAD

**Issue by RingoTheDog** [ytdl-org/youtube-dl#9340]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.04.24_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.24**
### Before submitting an _issue_ make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl.py -v "https://www.washingtonpost.com/world/iraqi-leaders-bicker-and-brawl-in-parliament-as-political-crisis-grows/2016/04/13/90551e36-019b-11e6-8bb1-f124a43f84dc_story.ht
ml"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.washingtonpost.com/world/iraqi-leaders-bicker-and-brawl-in-parliament-as-political-crisis-grows/2016/04/13/90551e36-019b-11e6-8bb1-f124a43f84dc_story.htm
l']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.04.24
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 90551e36-019b-11e6-8bb1-f124a43f84dc_story: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 90551e36-019b-11e6-8bb1-f124a43f84dc_story: Downloading webpage
[generic] 90551e36-019b-11e6-8bb1-f124a43f84dc_story: Extracting information
ERROR: Unsupported URL: https://www.washingtonpost.com/world/iraqi-leaders-bicker-and-brawl-in-parliament-as-political-crisis-grows/2016/04/13/90551e36-019b-11e6-8bb1-f124a43f84dc_story.html
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 341, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 2061, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.washingtonpost.com/world/iraqi-leaders-bicker-and-brawl-in-parliament-as-political-crisis-grows/2016/04/13/90551e36-019b-11e6-8bb1-f124a
43f84dc_story.html...


C:\Transmogrifier>youtube-dl.py -v "https://www.washingtonpost.com/posttv/world/iraq-to-track-down-antiquities-after-islamic-state-museum-rampage/2015/02/28/7c57e916-bf86-11e4-9dfb-03366e719af8_video.
html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.washingtonpost.com/posttv/world/iraq-to-track-down-antiquities-after-islamic-state-museum-rampage/2015/02/28/7c57e916-bf86-11e4-9dfb-03366e719af8_video.h
tml']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.04.24
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 7c57e916-bf86-11e4-9dfb-03366e719af8_video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 7c57e916-bf86-11e4-9dfb-03366e719af8_video: Downloading webpage
[generic] 7c57e916-bf86-11e4-9dfb-03366e719af8_video: Extracting information
[Ooyala] NvNzJvczrHg1L1irchrENHs93jlqxXed: Downloading JSON metadata
[Ooyala] NvNzJvczrHg1L1irchrENHs93jlqxXed: Downloading mp4 JSON
ERROR: Ooyala said: movie expired
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 341, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\ooyala.py", line 137, in _real_extract
    return self._extract(content_tree_url, embed_code, domain)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\ooyala.py", line 78, in _extract
    self.IE_NAME, cur_auth_data['message']), expected=True)
youtube_dl.utils.ExtractorError: Ooyala said: movie expired

<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.washingtonpost.com/world/iraqi-leaders-bicker-and-brawl-in-parliament-as-political-crisis-grows/2016/04/13/90551e36-019b-11e6-8bb1-f124a43f84dc_story.html
- Single video: https://www.washingtonpost.com/posttv/world/iraq-to-track-down-antiquities-after-islamic-state-museum-rampage/2015/02/28/7c57e916-bf86-11e4-9dfb-03366e719af8_video.html
- Playlist: n/a

---
### Description of your _issue_, suggested solution and other information

These might be two separate issues (sorry?)
Both are from The Washington Post, but neither one appears to use the Washington Post extractor, and both fail differently.

Thanks as always...
Ringo

**Comment by AdamDanischewski** [comment]
This looks like its still an issue, I tried with the latest version of youtube-dl (2017.08.09) to download a video from https://www.washingtonpost.com/news/checkpoint/wp/2017/08/09/russian-surveillance-plane-soars-over-the-pentagon-capitol-and-other-washington-sights/?tid=pm_world_pop

It errored out, regarding the SSLV3 handshake, with: 
youtube-dl -v "https://www.washingtonpost.com/news/checkpoint/wp/2017/08/09/russian-surveillance-plane-soars-over-the-pentagon-capitol-and-other-washington-sights/?tid=pm_world_pop" 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.washingtonpost.com/news/checkpoint/wp/2017/08/09/russian-surveillance-plane-soars-over-the-pentagon-capitol-and-other-washington-sights/?tid=pm_world_pop']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.09
[debug] Python version 2.7.6 - Linux-3.8.11-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6
[debug] Proxy map: {}
[washingtonpost:article] russian-surveillance-plane-soars-over-the-pentagon-capitol-and-other-washington-sights: Downloading webpage
[download] Downloading playlist: Russian surveillance plane soars over the Pentagon, Capitol and other Washington sites
[washingtonpost:article] playlist Russian surveillance plane soars over the Pentagon, Capitol and other Washington sites: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[washingtonpost] 39087458-779b-11e7-8c17-533c52b2f014: Downloading JSON metadata
[washingtonpost] 39087458-779b-11e7-8c17-533c52b2f014: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
[washingtonpost] 39087458-779b-11e7-8c17-533c52b2f014: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
[washingtonpost] 39087458-779b-11e7-8c17-533c52b2f014: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[debug] Default format spec: best
[debug] Invoking downloader on u'https://d21rhj7n383afu.cloudfront.net/washpost-production/The_Washington_Post/20170802/5981f649e4b08417c4681757/59837cb3e4b0b07aa660c080_1439411933958-zgatlb_t_1501789397479_1920_1080_5400.mp4'
ERROR: unable to download video data: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
Traceback (most recent call last):
  File "/home/cronkilla/REMEDY_DEV/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 1863, in process_info
    success = dl(filename, info_dict)
  File "/home/cronkilla/REMEDY_DEV/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 1805, in dl
    return fd.download(name, info)
  File "/home/cronkilla/REMEDY_DEV/scripts/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/home/cronkilla/REMEDY_DEV/scripts/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/home/cronkilla/REMEDY_DEV/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 2166, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/home/cronkilla/REMEDY_DEV/scripts/youtube-dl/youtube_dl/utils.py", line 1086, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
