### ISSUE TITLE
vidible.tv support

### ISSUE THREAD

**Issue by fstirlitz** [ytdl-org/youtube-dl#9461]
Should be easy. Example: in http://www.huffingtonpost.com/eric-douglas/ignorant-experts-the-wiki_b_9876984.html there is a `<script>` tag pointing to https://delivery.vidible.tv/jsonp/pid=57335f8be4b097137127cf0b/56000e19e4b0e4e194b84b31.js which contains a JSON object with the metadata and video URLs.

**Comment by ccoenen** [comment]
another example is included here: https://www.makers.com/profiles/5aa3d982b36ef856656f6172

**Comment by ccoenen** [comment]
nice :-D I just tested the link above and that worked fine! thanks for reminding me @fstirlitz ❤️
