### ISSUE TITLE
Creating a logfile similar to "--download-archive" (URL, ID, Name, Date and Time)

### ISSUE THREAD

**Issue by tuxeos** [ytdl-org/youtube-dl#9464]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
### Description of your _issue_, suggested solution and other information

I really enjoy using this tool - thank you very much!

Is there a way to log some (accessible) details of the downloaded videos? I'm thinking of somethink like the current output of "--download-archive" but with more details.

I like how I can configure the file output name, but having all these possibilities to create a own logfile-template would be awesome!

**Comment by jaimeMF** [comment]
You can use the `--write-info-json` and use the information stored in the `*.info.json` files. Isn't that enough?

**Comment by tuxeos** [comment]
Thank you for the answer!

--write-info-json is very good, and includes nearly all of the things I want.

The only thing I'm missing is a timestamp when the was finished downloading. If it's possible, I'd like to add it somewhere in the json file, so I just have to collect all the information from one file later on...

**Comment by jaimeMF** [comment]
> The only thing I'm missing is a timestamp when the file was finished downloading. If it's possible, I'd like to add it somewhere in the json file, so I just have to collect all the information from just that file later on...

I think you can just check the change time (ctime) of the video file itself.
