### ISSUE TITLE
http://sverigesradio.se

### ISSUE THREAD

**Issue by Krassegrand** [ytdl-org/youtube-dl#9572]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.05.21.2_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.21.2**
### Before submitting an _issue_ make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---
### Description of your _issue_, suggested solution and other information

Explanation of your _issue_ in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your _issue_ required an account credentials please provide them or explain how one can obtain them.

I Try to download from 
"http://sverigesradio.se/sida/artikel.aspx?programid=4720&artikel=6137924"
but get a fault message.

"jorgen@jorgen-Lenovo-Z50-75:~/Hämtningar/Bamse$ youtube-dl http://sverigesradio.se/sida/artikel.aspx?programid=4720&artikel=6137924
[1] 3223
jorgen@jorgen-Lenovo-Z50-75:~/Hämtningar/Bamse$ [generic] artikel: Requesting header
WARNING: Could not send HEAD request to http://sverigesradio.se/sida/artikel.aspx?programid=4720: HTTP Error 404: Sidan kan inte hittas
[generic] artikel: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Sidan kan inte hittas (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

I have updated to the version 2016.05.21.2

This issue is not important. I just want You to know about it if You feel like doing something about it.

Thank You for a great work on this, the program is fantastic.

Jörgen

**Comment by krokofant** [comment]
Sveriges Radio provides a button to download all episodes as far as I know.

<img width="331" alt="bamse_och_mc-ganget_-_thor_radio___sveriges_radio" src="https://cloud.githubusercontent.com/assets/5908498/15470935/a7e7a204-20f3-11e6-8bc3-2b80cc233237.png">

**Comment by Krassegrand** [comment]
Thank You!
I am a little embarrassed.:)
 
Jörgen

**Comment by TRox1972** [comment]
@Krassegrand Did this solve your issue? If so, close this.

**Comment by Krassegrand** [comment]
well, sort of.
It is ok to download that file and edit it. 
by the way I found the same audio file on Youtube.

Jörgen

**Comment by Brottweiler** [comment]
Some casts cannot be downloaded, I assume it is because they have copyrighted music in them. Example https://sverigesradio.se/sida/avsnitt/814150?programid=3135

However, if you start playing the episode, (then you can pause it), this will show up in the source code (and can be found with inspect element)

```html
<audio id="player-audio" src="https://lyssna-cdn.sr.se/autorec/et2w/p4/p4_dans/2016/12/srp4riks_2016-12-04_201500_2700_a192.m4a" title="P4 Dans med Thomas Deutgen" preload="none"></audio>
```

The link `https://lyssna-cdn.sr.se/autorec/et2w/p4/p4_dans/2016/12/srp4riks_2016-12-04_201500_2700_a192.m4a` can be played using a media player, but it would be nice with youtube-dl support.

**Comment by burnoutberni** [comment]
Hej, just tried youtube-dl on a sverigesradio.se URL today and was surprised to see it isn't supported.

A very brief research shows, that the website sends a GET request to this URL ```https://sverigesradio.se/sida/playerajax/getaudiourl``` when users press on the play button and starts playback once the URL of the corresponding .m4a file has resolved. I haven't looked at it closely, but there seem to be at least two different URL schemes on the SR website:

```
# Episodes of recurring shows e.g. https://sverigesradio.se/sida/avsnitt/1140948?programid=4772
# Note, the URL schema contains avsnitt (Swedish for episode), which apparently corresponds to the GET parameter type=episode
$ http "https://sverigesradio.se/sida/playerajax/getaudiourl?id=1140948&type=episode&quality=high&format=iis"
HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 0
Cache-Control: public, max-age=30
Connection: keep-alive
Content-Length: 183
Content-Type: application/json; charset=utf-8
Date: Fri, 07 Sep 2018 17:15:38 GMT
Expires: Fri, 07 Sep 2018 17:16:08 GMT
Last-Modified: Fri, 07 Sep 2018 17:15:38 GMT
SR-Url: /sida/playerajax/getaudiourl?id=1140948&type=episode&quality=high&format=iis
X-UA-Compatible: IE=Edge

{
    "audioUrl": "https://lyssna-cdn.sr.se/ljudit/p1/sondagsintervjun/2018/09/sondagsintervjun_20180902_0805_192.m4a",
    "codingFormat": 11,
    "duration": 2695,
    "isGeoblockEnabled": false,
    "state": 0
}
```

```
# Audio clips corresponding to news articles e.g. https://sverigesradio.se/sida/artikel.aspx?programid=83&artikel=7038548
# Note, the URL schema contains artikel (Swedish for article), which apparently corresponds to the GET parameter type=publication
$ http "https://sverigesradio.se/sida/playerajax/getaudiourl?id=7038548&type=publication&quality=high&format=iis"
HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 12
Cache-Control: public, max-age=30
Connection: keep-alive
Content-Length: 182
Content-Type: application/json; charset=utf-8
Date: Fri, 07 Sep 2018 17:19:37 GMT
Expires: Fri, 07 Sep 2018 17:20:07 GMT
Last-Modified: Fri, 07 Sep 2018 17:19:37 GMT
SR-Url: /sida/playerajax/getaudiourl?id=7038548&type=publication&quality=high&format=iis
X-UA-Compatible: IE=Edge

{
    "audioUrl": "https://lyssna-cdn.sr.se/isidor/ereg/ekot_nyheter_sthlm/2018/09/6_paverkan_de_app_3a222d3_a192.m4a",
    "codingFormat": 11,
    "duration": 184,
    "isGeoblockEnabled": false,
    "state": 0
}
```

As for the other GET parameters, id seems obvious. There seem to be at least three quality settings: low at 32kbps, medium at 96kbps and high at 196kbps. And for the format, you can drop the parameter and still get a .m4a URL returned and I wouldn't know what else to try, so I have no idea, whether the audio URL can also be requested in a different format.

If there's anyone who'd like to take this from here, please go ahead, otherwise I might look into how to add SR support into youtube-dl sometimes in the future.

**Comment by remitamine** [comment]
will be supported in the next version.
