### ISSUE TITLE
Support videos in CBSNews articles (was: CBSNews unable to download video)

### ISSUE THREAD

**Issue by github-0000** [ytdl-org/youtube-dl#9659]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.05.30.2_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.30.2**
### Before submitting an _issue_ make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl http://www.cbsnews.com/news/gorilla-harambe-death-cincinnati-zoo-debate-on-parents-role/ --verbose      
[debug] System config: []                                                                                                           
[debug] User config: []                                                                                                             
[debug] Command-line args: [u'http://www.cbsnews.com/news/gorilla-harambe-death-cincinnati-zoo-debate-on-parents-role/', u'--verbose']                                                                                                                                  
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8                                                                    
[debug] youtube-dl version 2016.05.30.2                                                                                             
[debug] Python version 2.7.11+ - Linux-4.5.0-2-amd64-x86_64-with-debian-stretch-sid                                                 
[debug] exe versions: ffmpeg 3.0.2-2, ffprobe 3.0.2-2, rtmpdump 2.4                                                                 
[debug] Proxy map: {}                                                                                                               
[CBSNews] gorilla-harambe-death-cincinnati-zoo-debate-on-parents-role: Downloading webpage                                          
ERROR: Unable to extract video JSON info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.           
Traceback (most recent call last):                                                                                                  
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info                                               
    ie_result = ie.extract(url)                                                                                                     
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract                                             
    return self._real_extract(url)                                                                                                  
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cbsnews.py", line 58, in _real_extract                                       
    webpage, 'video JSON info'), video_id)                                                                                          
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 653, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 644, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video JSON info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


...
<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video:   http://www.cbsnews.com/news/gorilla-harambe-death-cincinnati-zoo-debate-on-parents-role/

---
### Description of your _issue_, suggested solution and other information

The video URL given above fails to download.  I have included the verbose output and updated right before trying.

It may be related to this issue:
https://github.com/rg3/youtube-dl/issues/7010

However that issue was closed and it sounds like it was related to it being a live video which this one is not.

**Comment by remitamine** [comment]
try to download the video directly using the video url untill the extraction of video in article pages fixed.
for this article the video url is http://www.cbsnews.com/videos/cops-investigate-gorilla-incident-at-cincinnati-zoo.

**Comment by github-0000** [comment]
That URL works normally.  I actually already obtained the video from another source and was just making this report as I did not see any bugs related to it.  It is already a known issue that you cannot download video's from the article page?  I guess I missed it in the open bugs.
