### ISSUE TITLE
Site support request: tidido.com

### ISSUE THREAD

**Issue by Vladimirek** [ytdl-org/youtube-dl#9703]
You are great. As improvement you can add support for tidido.com:

Single track: http://tidido.com/a35184373619912/al55d60a1813b521ef223e1726/t55d60a1813b521ef223e174f

Album:
http://tidido.com/a35184373619912/al55d60a1813b521ef223e1726

thanks,

-vladimirek-

**Comment by Mennaruuk** [comment]
Site is dead. Issue should be closed.
