### ISSUE TITLE
[TFOU]  "AttributeError: 'NoneType' object has no attribute 'get'"

### ISSUE THREAD

**Issue by Crypt0Graf** [ytdl-org/youtube-dl#9708]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.06.03_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.03**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
~ $  youtube-dl http://www.tfou.fr/mini-ninjas/videos/teaser-episodes-inedits-8635482-739.html -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.tfou.fr/mini-ninjas/videos/teaser-episodes-inedits-8635482-739.html', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.03
[debug] Python version 2.7.6 - Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[TF1] teaser-episodes-inedits-8635482-739: Downloading webpage
[wat.tv] 11126336: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 421, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 411, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1736, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 687, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 740, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/wat.py", line 56, in _real_extract
AttributeError: 'NoneType' object has no attribute 'get'

...
<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.tfou.fr/mini-ninjas/videos/teaser-episodes-inedits-8635482-739.html
- Single video: http://www.wat.tv/embedframe/160823nIc0K1112633687#TFOU/mini-ninjas/inedit/videos
- Playlist: http://www.tfou.fr/mini-ninjas/playlist/

---
### Description of your _issue_, suggested solution and other information

I've tried to download a video from tfou.fr (site is geo-restricted, download with youtube-dl usually works from everywhere; tf1.fr (main site of tfou) is still working great here.). Maybe this is a local issue, as I've reinstalled yt-dl yesterday.

**Comment by yan12125** [comment]
Can you watch this video in browsers?

**Comment by yan12125** [comment]
To developers: the video info is available only in ```/contentv4/``` node.

**Comment by Crypt0Graf** [comment]
@yan12125 Yup, works in my browser.

**Comment by remitamine** [comment]
> To developers: the video info is available only in /contentv4/ node.

if i remember correctly, there is also `/contentv4s/`(did not return related videos info)

**Comment by remitamine** [comment]
No longer accessible.
