### ISSUE TITLE
streamup.com support

### ISSUE THREAD

**Issue by Joseph65** [ytdl-org/youtube-dl#9764]
please add support for this site
https://streamup.com/

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by Joseph65** [comment]
https://streamup.com/athletic-tv

**Comment by Mennaruuk** [comment]
Site is dead. Issue should be closed.
