### ISSUE TITLE
Download error when downloading with LinkedIn account

### ISSUE THREAD

**Issue by tiagobrc** [ytdl-org/youtube-dl#9819]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.06.18.1_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.18.1**
### Before submitting an _issue_ make sure you have:
- [ X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
computer@computer:~/$ youtube-dl --verbose --print-traffic --dump-pages -u private --cookies cookies1.txt https://www.lynda.com/C-tutorials/C-Essential-Training/182674-2.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--print-traffic', u'--dump-pages', u'-u', u'PRIVATE', u'--cookies', u'cookies1.txt', u'https://www.lynda.com/C-tutorials/C-Essential-Training/182674-2.html']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.18.1
[debug] Python version 2.7.10 - Linux-4.2.0-27-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: none
[debug] Proxy map: {}

...
<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---
### Description of your _issue_, suggested solution and other information

I am trying to download some videos and followed every tutorial around. 
I could fix the cookies prerequisites and start the download but, since my account come from linkedin it thrown an error:

ERROR: Unable to login: Please use the "Sign in with LinkedIn" option to sign in.
ExtractorError: Unable to login: Please use the "Sign in with LinkedIn" option to sign in.

There is something can be done about it ?

**Comment by dstftw** [comment]
If you authenticate with cookies you **should not** specify `-u`.

**Comment by tiagobrc** [comment]
When I do that it shows to me :
WARNING: 93 videos are only available for members (or paid members) and will not be downloaded.

**Comment by AbsoluteZero273** [comment]
I have the same problem with passing cookies. I am using organizational login. Also, I tried to download a single locked video, I got `ERROR: lynda returned error: Session has expired
` But I can play the video in browser fine.

**Comment by yan12125** [comment]
An approach to get 3-month premium account: (thanks Mark Mushailov for sharing this)

---

you can get a free account (3 month premium account to both linkedin learning and pluralsight and many more) by signing up to

Steps:

1. Sign up for the FREE Visual Studio Dev Essentials program that you can find here: https://www.visualstudio.com/en-us/products/visual-studio-dev-essentials-vs.aspx
2. After you create your account, Click on the “Get Code” under the Linkedin Learning Tile
