### ISSUE TITLE
Add support for Treehouse

### ISSUE THREAD

**Issue by diman82** [ytdl-org/youtube-dl#9836]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.06.19.1_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.19.1**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.06.19.1
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://teamtreehouse.com/library/django-rest-framework/restful-django/what-is-django-rest-framework
- Single video: https://teamtreehouse.com/library/django-rest-framework/restful-django/model-serializers
- Playlist: https://teamtreehouse.com/library/django-rest-framework

---
### Description of your _issue_, suggested solution and other information

Explanation of your _issue_ in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your _issue_ required an account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by diman82** [comment]
Can you please kindly explain what I've missed? I'm kinda new to this product, so begging your pardon in advance.

**Comment by dstftw** [comment]
>### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

**Comment by diman82** [comment]
Please reopen the issue, I've edited the template as requested.
P.S I'll provide account details if needed.

**Comment by dstftw** [comment]
Udemy is already supported.

**Comment by diman82** [comment]
Sorry my bad - updated to https://teamtreehouse.com/library

**Comment by TRox1972** [comment]
Seems to require an account

**Comment by diman82** [comment]
There is an option for a 7-day trial.
Could 1 week be sufficient?

**Comment by leocaseiro** [comment]
references:

Python
https://github.com/xauwix/treehouse

NodeJS
https://github.com/MakhouT/treehouseDownloader

**Comment by Zildjiandrummerx** [comment]
Hi, I'm looking to download some courses from Treehouse but I keep getting an error.

youtube-dl -v https://teamtreehouse.com/library/python-basics-3
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://teamtreehouse.com/library/python-basics-3']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.01
[debug] Python version 3.7.0 (CPython) - Linux-4.14.67-1-MANJARO-x86_64-with-arch-Manjaro-Linux
[debug] exe versions: ffmpeg n4.0.2, ffprobe n4.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] python-basics-3: Requesting header
WARNING: Falling back on generic information extractor.
[generic] python-basics-3: Downloading webpage
[generic] python-basics-3: Extracting information
ERROR: Unsupported URL: https://teamtreehouse.com/library/python-basics-3
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/generic.py", line 3298, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://teamtreehouse.com/library/python-basics-3

**Comment by jaan143** [comment]
@remitamine  dear brother can you please add this website in script please ?
its too long and still pending

**Comment by remitamine** [comment]
an account is needed to add support for this website.

**Comment by jaan143** [comment]
@remitamine  brother please check your email i sent account detail

thanks

**Comment by Zildjiandrummerx** [comment]
Hi all,

Why am I being Cc'ed on this email?
