### ISSUE TITLE
Dplay 401 error

### ISSUE THREAD

**Issue by lilleindi** [ytdl-org/youtube-dl#9956]
Hi
Im trying to download from Dplay.
I have a account am paying for, and im sure its the right credentials.

But i keep getting a 401 error

The log:
`[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--newline', '-u', 'PRIVATE', '-p', 'PRIVATE', '-i', '--all-subs', '-o', 'C:\en\%(title)s.%(ext)s', '-v', '--no-check-certificate', '-o', "'~/MyVideos/%(playlist)s/%(title)s.%(ext)s'", 'http://www.dplay.dk/x-ray-mega-airport/season-1-fejl-er-ikke-en-mulighed/']

[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.06.27
[debug] Python version 3.4.4 - Windows-2012ServerR2-6.3.9600
[debug] exe versions: ffmpeg N-71883-geb9fb50, ffprobe N-71883-geb9fb50
[debug] Proxy map: {}
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppxjfb828\build\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppxjfb828\build\youtube_dl\extractor\common.py", line 343, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppxjfb828\build\youtube_dl\extractor\dplay.py", line 140, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppxjfb828\build\youtube_dl\extractor\common.py", line 866, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by dstftw** [comment]
dplay authentication is not supported. Use [authenticated cookies](https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl).

**Comment by petersellers66** [comment]
Im also trying to download from Dplay.......

D:\nedlastinger\Youtube videodownloader>youtube-dl --cookies cookies.txt http://
www.dplay.no/forlovelse-pa-prove/season-1-jeg-fikk-visumet/
[DPlay] season-1-jeg-fikk-visumet: Downloading webpage
[DPlay] 1641: Downloading JSON metadata
[DPlay] 1641: Downloading hls stream JSON
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[DPlay] 1641: Downloading hds stream JSON
WARNING: Unable to download JSON metadata: HTTP Error 401: Unauthorized
[DPlay] 1641: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[DPlay] 1641: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.

D:\nedlastinger\Youtube videodownloader>
